FreeOrion: ScanlineRenderer Class Reference
ScanlineRenderer Class Reference
#include <CUIDrawUtil.h>
Classes
class ScanlineRendererImpl
Public Member Functions
ScanlineRenderer ()
~ScanlineRenderer ()
void RenderCircle (const GG::Pt &ul, const GG::Pt &lr)
void RenderRectangle (const GG::Pt &ul, const GG::Pt &lr)
void StartUsing ()
void StopUsing ()
Private Attributes
boost::scoped_ptr
< ScanlineRendererImpl > const pimpl
Detailed Description
ScanlineRenderer renders scanlines in circular/square/arbitrary areas. It loads the scanline shader on first use. There is only expected to by one ScanlineRenderer per compilation unit so that the shader is compiled once.
Bracketing OpenGL primitives with StartUsing() and StopUsing() will render scanlines in that arbitrary area.
Constructor & Destructor Documentation
ScanlineRenderer::ScanlineRenderer ()
ScanlineRenderer::~ScanlineRenderer ()
Member Function Documentation
void ScanlineRenderer::RenderCircle (const GG::Pt & ul, const GG::Pt & lr)
Draw scanlines in the circular area bounded by ul and lr.
References pimpl.
Referenced by RotatingPlanetControl::Render(), ScanlineControl::Render(), and MapWnd::RenderSystems().
void ScanlineRenderer::RenderRectangle (const GG::Pt & ul, const GG::Pt & lr)
Draw scanlines in the square area bounded by ul and lr.
References pimpl.
Referenced by ScanlineControl::Render().
void ScanlineRenderer::StartUsing ()
Start using ScanlineRenderer to draw arbitrary shapes with the scanline shader program.
References pimpl.
Referenced by BuildingIndicator::Render(), and MapWnd::RenderFields().
void ScanlineRenderer::StopUsing ()
Stop using ScanlineRenderer to draw arbitrary shapes with the scanline shader program.
References pimpl.
Referenced by BuildingIndicator::Render(), and MapWnd::RenderFields().
Member Data Documentation
boost::scoped_ptr<ScanlineRendererImpl> const ScanlineRenderer::pimpl private
Referenced by RenderCircle(), RenderRectangle(), StartUsing(), and StopUsing().
The documentation for this class was generated from the following files:
CUIDrawUtil.h
CUIDrawUtil.cpp