FreeOrion: XMLDoc.h File Reference
XMLDoc.h File Reference
#include <GG/Enum.h>
#include <GG/Exception.h>
#include <boost/lexical_cast.hpp>
#include <map>
#include <string>
#include <vector>
#include "Export.h"
Classes
class XMLDoc
struct XMLDoc::RuleDefiner
used to create XML parsing rules at static initialization time
class XMLElement
class XMLElement::Exception
class XMLElement::NoSuchChild
class XMLElement::NoSuchIndex
Functions
template<class Cont >
Cont ContainerFromString (const std::string &str)
template<class T >
unsigned int FlagsFromString (const std::string &str)
template<class T1 , class T2 >
std::map< T1, T2 > MapFromString (const std::string &str)
template<class T1 , class T2 >
std::multimap< T1, T2 > MultimapFromString (const std::string &str)
template<class Cont >
std::string StringFromContainer (const Cont &container)
template<class T >
std::string StringFromFlags (unsigned int flags)
template<class T1 , class T2 >
std::string StringFromMap (const std::map< T1, T2 > &container)
template<class T1 , class T2 >
std::string StringFromMultimap (const std::multimap< T1, T2 > &container)
std::vector< std::string > Tokenize (const std::string &str)
std::pair< std::vector
< std::string >, std::vector
< std::string > > TokenizeMapString (const std::string &str)
Detailed Description
Contains free functions and classes to modify, read and write XML files.
Function Documentation
template<class Cont > Cont ContainerFromString (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Creates a container of the specified type from a string consisting whitespace-delimited list of elements. Due to the key-value pair organization of STL maps, this function does not work with them. Use ContainerFromMapString() instead.
References Tokenize().
template<class T > unsigned int FlagsFromString (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes a string of the form "value1 value2 value3 ..." and returns an unsigned integer that is the result of the bitwise OR-ing of the enumerated values of type T in the string.
Note
This function depends on EnumMap<T> being defined.
References Tokenize().
template<class T1 , class T2 > std::map<T1, T2> MapFromString (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Creates an STL map from a string consisting whitespace-delimited list of elements in the format "(first, second) (first, second) ...".
References TokenizeMapString().
template<class T1 , class T2 > std::multimap<T1, T2> MultimapFromString (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Creates an STL multimap from a string consisting whitespace-delimited list of elements in the format "(first, second) (first, second) ...".
References TokenizeMapString().
template<class Cont > std::string StringFromContainer (const Cont & container)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes any simple STL container (vector, set, etc.) and puts its contents into a whitespace-delimited list. Due to the key-value pair organization of STL maps, this function does not work with them. Use StringFromMap() instead.
template<class T > std::string StringFromFlags (unsigned int flags)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes an unsigned integer that is the result of the bitwise OR-ing of enumerated values of type T, and generates a string of the form "value1 value2 value3 ...". This function will yield the zero-value of enum type T (e.g. "TF_NONE") if no nonzero flags are specified. If no such zero-value exists, the returned string will be empty.
Note
This function depends on EnumMap<T> being defined.
template<class T1 , class T2 > std::string StringFromMap (const std::map< T1, T2 > & container)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes an STL map and puts its contents into a whitespace-delimited list, in the format "(first, second) (first, second) ...".
template<class T1 , class T2 > std::string StringFromMultimap (const std::multimap< T1, T2 > & container)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes an STL multimap and puts its contents into a whitespace-delimited list, in the format "(first, second) (first, second) ...".
std::vector<std::string> Tokenize (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Breaks a given string up into tokens. The resulting vector contains all the non-whitespace characters from str.
Referenced by ContainerFromString(), and FlagsFromString().
std::pair<std::vector<std::string>, std::vector<std::string> > TokenizeMapString (const std::string & str)
Deprecated:
All the GG XML classes are deprecated and will be removed upon the next major release. Takes a string of the form "(first, second) (first, second) ..." and produces two vectors of token strings: one for keys and one for values.
Referenced by MapFromString(), and MultimapFromString().