FreeOrion: ClientNetworking Class Reference
ClientNetworking Class Reference
#include <ClientNetworking.h>
Public Types
typedef boost::array< int, 5 > MessageHeaderBuffer
typedef std::vector< std::pair
< boost::asio::ip::address,
std::string > > ServerList
Public Member Functions
Structors
ClientNetworking ()
Basic ctor.
Accessors
bool Connected () const
bool MessageAvailable () const
int PlayerID () const
int HostPlayerID () const
bool PlayerIsHost (int player_id) const
Mutators
ServerList DiscoverLANServers ()
bool ConnectToServer (const std::string &ip_address, boost::posix_time::seconds timeout=boost::posix_time::seconds(5))
bool ConnectToLocalHostServer (boost::posix_time::seconds timeout=boost::posix_time::seconds(5))
void SendMessage (Message message)
void GetMessage (Message &message)
void SendSynchronousMessage (Message message, Message &response_message)
void DisconnectFromServer ()
void SetPlayerID (int player_id)
void SetHostPlayerID (int host_player_id)
Private Member Functions
void AsyncReadMessage ()
void AsyncWriteMessage ()
void CancelRetries ()
void DisconnectFromServerImpl ()
void HandleConnection (boost::asio::ip::tcp::resolver::iterator *it, boost::asio::deadline_timer *timer, const boost::system::error_code &error)
void HandleException (const boost::system::system_error &error)
void HandleMessageBodyRead (boost::system::error_code error, std::size_t bytes_transferred)
void HandleMessageHeaderRead (boost::system::error_code error, std::size_t bytes_transferred)
void HandleMessageWrite (boost::system::error_code error, std::size_t bytes_transferred)
void NetworkingThread ()
void SendMessageImpl (Message message)
Private Attributes
bool m_cancel_retries
bool m_connected
int m_host_player_id
MessageHeaderBuffer m_incoming_header
Message m_incoming_message
MessageQueue m_incoming_messages
boost::asio::io_service m_io_service
boost::mutex m_mutex
MessageHeaderBuffer m_outgoing_header
std::list< Message > m_outgoing_messages
int m_player_id
boost::asio::ip::tcp::socket m_socket
Detailed Description
Encapsulates the networking facilities of the client. The client must execute its networking code in a separate thread from its main processing thread, for UI and networking responsiveness, and to process synchronous communication with the server.
Because of this, ClientNetworking operates in two threads: the main thread, in which the UI processing operates; the networking thread, which is created and terminates when the client is connected to and disconnected from the server, respectively. The entire public interface is safe to call from the main thread at all times. Note that the main thread must periodically request the next incoming message; the arrival of incoming messages is never explicitly signalled to the main thread. The same applies to unintentional disconnects from the server. The client must periodically check Connected().
The ClientNetworking has three modes of operation. First, it can discover FreeOrion servers on the local network; this is a blocking operation with a timeout. Second, it can send an asynchronous message to the server (when connected); this is a non-blocking operation. Third, it can send a synchronous message to the server (when connected) and return the server's response; this is a blocking operation.
Note that the SendSynchronousMessage() does not interrupt the sending or receiving of asynchronous messages. When SendSynchronousMessage() is called and the main thread blocks to wait for the response message, regular messages are still being sent and received. Some of these regular messages may arrive before the response message, but SendSynchronousMessage() will still return the response message first, even if it is not at the front of the queue at the time. This implies that some response messages may be handled out of order with respect to regular messages, but these are in fact the desired semantics.
Member Typedef Documentation
typedef boost::array<int, 5> ClientNetworking::MessageHeaderBuffer
typedef std::vector<std::pair<boost::asio::ip::address, std::string> > ClientNetworking::ServerList
The type of list returned by a call to DiscoverLANServers().
Constructor & Destructor Documentation
ClientNetworking::ClientNetworking ()
Basic ctor.
Member Function Documentation
void ClientNetworking::AsyncReadMessage () private
References HandleMessageHeaderRead(), m_incoming_header, and m_socket.
Referenced by HandleMessageBodyRead(), and NetworkingThread().
void ClientNetworking::AsyncWriteMessage () private
References HandleMessageWrite(), HeaderToBuffer(), m_outgoing_header, m_outgoing_messages, and m_socket.
Referenced by HandleMessageWrite(), NetworkingThread(), and SendMessageImpl().
void ClientNetworking::CancelRetries () private
References m_cancel_retries.
Referenced by ConnectToServer().
bool ClientNetworking::Connected () const
Returns true iff the client is connected to the server.
References m_connected, and m_mutex.
Referenced by ConnectToServer(), DisconnectFromServer(), DiscoverLANServers(), HumanClientApp::EndGame(), HumanClientApp::HandleSystemEvents(), HumanClientApp::MultiPlayerGame(), HumanClientApp::NewSinglePlayerGame(), HumanClientApp::RequestSavePreviews(), SendMessage(), and HumanClientApp::~HumanClientApp().
bool ClientNetworking::ConnectToLocalHostServer (boost::posix_time::seconds timeout = boost::posix_time::seconds(5))
Connects to the server on the client's host. On failure, repeated attempts will be made until timeout seconds has elapsed.
References ConnectToServer().
Referenced by AIClientApp::ConnectToServer(), HumanClientApp::LoadSinglePlayerGame(), HumanClientApp::NewSinglePlayerGame(), and HumanClientApp::RequestSavePreviews().
bool ClientNetworking::ConnectToServer (const std::string & ip_address, boost::posix_time::seconds timeout = boost::posix_time::seconds(5))
Connects to the server at ip_address. On failure, repeated attempts will be made until timeout seconds has elapsed.
References CancelRetries(), Connected(), DebugLogger, ErrorLogger, GetOptionsDB(), HandleConnection(), m_cancel_retries, m_io_service, m_socket, Networking::MESSAGE_PORT, NetworkingThread(), and Networking::SOCKET_LINGER_TIME.
Referenced by ConnectToLocalHostServer(), and HumanClientApp::MultiPlayerGame().
void ClientNetworking::DisconnectFromServer ()
Disconnects the client from the server.
References Connected(), DisconnectFromServerImpl(), and m_io_service.
Referenced by HumanClientApp::EndGame(), HumanClientApp::NewSinglePlayerGame(), MPLobby::react(), AIClientApp::Run(), AIClientApp::~AIClientApp(), and HumanClientApp::~HumanClientApp().
void ClientNetworking::DisconnectFromServerImpl () private
References m_socket.
Referenced by DisconnectFromServer().
ClientNetworking::ServerList ClientNetworking::DiscoverLANServers ()
Returns a list of the addresses and names of all servers on the Local Area Network.
References Connected(), and m_io_service.
Referenced by ServerConnectWnd::RefreshServerList(), and ServerConnectWnd::ServerConnectWnd().
void ClientNetworking::GetMessage (Message & message)
Gets the next incoming message from the server, places it into message, and removes it from the incoming message queue. The function assumes that there is at least one message in the incoming queue. Users must call MessageAvailable() first to make sure this is the case.
References DebugLogger, ErrorLogger, m_incoming_messages, MessageAvailable(), MessageQueue::PopFront(), and anonymous_namespace{ClientNetworking.cpp}::TRACE_EXECUTION.
Referenced by HumanClientApp::HandleSystemEvents(), and AIClientApp::Run().
void ClientNetworking::HandleConnection (boost::asio::ip::tcp::resolver::iterator * it, boost::asio::deadline_timer * timer, const boost::system::error_code & error) private
References DebugLogger, m_cancel_retries, m_connected, m_mutex, m_socket, and anonymous_namespace{ClientNetworking.cpp}::TRACE_EXECUTION.
Referenced by ConnectToServer().
void ClientNetworking::HandleException (const boost::system::system_error & error) private
References DebugLogger, and ErrorLogger.
Referenced by NetworkingThread().
void ClientNetworking::HandleMessageBodyRead (boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncReadMessage(), m_incoming_header, m_incoming_message, m_incoming_messages, and MessageQueue::PushBack().
Referenced by HandleMessageHeaderRead().
void ClientNetworking::HandleMessageHeaderRead (boost::system::error_code error, std::size_t bytes_transferred) private
References BufferToHeader(), Message::Data(), HandleMessageBodyRead(), anonymous_namespace{ClientNetworking.cpp}::HEADER_SIZE, m_incoming_header, m_incoming_message, m_socket, Message::Resize(), and Message::Size().
Referenced by AsyncReadMessage().
void ClientNetworking::HandleMessageWrite (boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncWriteMessage(), anonymous_namespace{ClientNetworking.cpp}::HEADER_SIZE, m_outgoing_header, and m_outgoing_messages.
Referenced by AsyncWriteMessage().
int ClientNetworking::HostPlayerID () const
Returns the ID of the host player, or INVALID_PLAYER_ID if there is no host player.
References m_host_player_id.
bool ClientNetworking::MessageAvailable () const
Returns true iff there is at least one incoming message available.
References MessageQueue::Empty(), and m_incoming_messages.
Referenced by GetMessage(), and HumanClientApp::HandleSystemEvents().
void ClientNetworking::NetworkingThread () private
References AsyncReadMessage(), AsyncWriteMessage(), MessageQueue::Clear(), DebugLogger, HandleException(), m_connected, m_incoming_messages, m_io_service, m_mutex, m_outgoing_messages, and anonymous_namespace{ClientNetworking.cpp}::TRACE_EXECUTION.
Referenced by ConnectToServer().
int ClientNetworking::PlayerID () const
Returns the ID of the player on this client.
References m_player_id.
Referenced by HumanClientApp::EndGame(), ClientApp::GetClientType(), ClientApp::GetNewDesignID(), ClientApp::GetNewObjectID(), HumanClientApp::NewSinglePlayerGame(), ClientApp::PlayerID(), and ClientApp::StartTurn().
bool ClientNetworking::PlayerIsHost (int player_id) const
Returns whether the indicated player ID is the host.
References Networking::INVALID_PLAYER_ID, and m_host_player_id.
Referenced by MultiPlayerLobbyWnd::ThisClientIsHost().
void ClientNetworking::SendMessage (Message message)
Sends message to the server. This function actually just enqueues the message for sending and returns immediately.
References Connected(), DebugLogger, ErrorLogger, m_io_service, SendMessageImpl(), and anonymous_namespace{ClientNetworking.cpp}::TRACE_EXECUTION.
Referenced by MapWnd::BuildingRightClicked(), HumanClientApp::EndGame(), MapWnd::FieldRightClicked(), MapWnd::FleetsRightClicked(), AIClientApp::HandleMessage(), AIClientApp::HandlePythonAICrash(), HumanClientApp::HandleSaveGameDataRequest(), MultiPlayerLobbyWnd::KeyPress(), HumanClientApp::LoadSinglePlayerGame(), HumanClientApp::MultiPlayerGame(), HumanClientApp::NewSinglePlayerGame(), ObjectListWnd::ObjectRightClicked(), MapWnd::PlanetRightClicked(), PlayerListWnd::PlayerRightClicked(), MapWnd::RClick(), AIClientApp::Run(), HumanClientApp::SaveGame(), anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), AIInterface::SendDiplomaticMessage(), AIInterface::SendPlayerChatMessage(), SendSynchronousMessage(), MultiPlayerLobbyWnd::SendUpdate(), MapWnd::ShipsRightClicked(), ClientApp::StartTurn(), and MapWnd::SystemRightClicked().
void ClientNetworking::SendMessageImpl (Message message) private
References AsyncWriteMessage(), m_outgoing_messages, and swap().
Referenced by SendMessage().
void ClientNetworking::SendSynchronousMessage (Message message, Message & response_message)
Sends message to the server, then blocks until it sees the first synchronous response from the server.
References DebugLogger, MessageQueue::EraseFirstSynchronousResponse(), m_incoming_messages, SendMessage(), and anonymous_namespace{ClientNetworking.cpp}::TRACE_EXECUTION.
Referenced by ClientApp::GetNewDesignID(), ClientApp::GetNewObjectID(), and HumanClientApp::RequestSavePreviews().
void ClientNetworking::SetHostPlayerID (int host_player_id)
Sets Host player ID.
References m_host_player_id.
Referenced by HumanClientApp::EndGame(), HumanClientApp::FreeServer(), AIClientApp::HandleMessage(), HumanClientApp::KillServer(), and HumanClientApp::LoadSinglePlayerGame().
void ClientNetworking::SetPlayerID (int player_id)
Sets player ID for this client.
References DebugLogger, and m_player_id.
Referenced by HumanClientApp::EndGame(), HumanClientApp::FreeServer(), AIClientApp::HandleMessage(), HumanClientApp::KillServer(), and HumanClientApp::LoadSinglePlayerGame().
Member Data Documentation
bool ClientNetworking::m_cancel_retries private
Referenced by CancelRetries(), ConnectToServer(), and HandleConnection().
bool ClientNetworking::m_connected private
Referenced by Connected(), HandleConnection(), and NetworkingThread().
int ClientNetworking::m_host_player_id private
Referenced by HostPlayerID(), PlayerIsHost(), and SetHostPlayerID().
MessageHeaderBuffer ClientNetworking::m_incoming_header private
Referenced by AsyncReadMessage(), HandleMessageBodyRead(), and HandleMessageHeaderRead().
Message ClientNetworking::m_incoming_message private
Referenced by HandleMessageBodyRead(), and HandleMessageHeaderRead().
MessageQueue ClientNetworking::m_incoming_messages private
Referenced by GetMessage(), HandleMessageBodyRead(), MessageAvailable(), NetworkingThread(), and SendSynchronousMessage().
boost::asio::io_service ClientNetworking::m_io_service private
Referenced by ConnectToServer(), DisconnectFromServer(), DiscoverLANServers(), NetworkingThread(), and SendMessage().
boost::mutex ClientNetworking::m_mutex mutable private
Referenced by Connected(), HandleConnection(), and NetworkingThread().
MessageHeaderBuffer ClientNetworking::m_outgoing_header private
Referenced by AsyncWriteMessage(), and HandleMessageWrite().
std::list<Message> ClientNetworking::m_outgoing_messages private
Referenced by AsyncWriteMessage(), HandleMessageWrite(), NetworkingThread(), and SendMessageImpl().
int ClientNetworking::m_player_id private
Referenced by PlayerID(), and SetPlayerID().
boost::asio::ip::tcp::socket ClientNetworking::m_socket private
Referenced by AsyncReadMessage(), AsyncWriteMessage(), ConnectToServer(), DisconnectFromServerImpl(), HandleConnection(), and HandleMessageHeaderRead().
The documentation for this class was generated from the following files:
ClientNetworking.h
ClientNetworking.cpp