FreeOrion: ShipsListBox Class Reference
ShipsListBox Class Reference
Public Member Functions
ShipsListBox (int fleet_id, bool order_issuing_enabled)
virtual void AcceptDrops (const GG::Pt &pt, const std::vector< GG::Wnd * > &wnds, GG::Flags< GG::ModKey > mod_keys)
virtual void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const
void EnableOrderIssuing (bool enable)
GG::Pt ListRowSize () const
void Refresh ()
void SetFleet (int fleet_id)
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Public Member Functions inherited from CUIListBox
CUIListBox (void)
basic ctor
virtual void Render ()
Private Attributes
int m_fleet_id
bool m_order_issuing_enabled
Detailed Description
A CUIListBox subclass used to list all the ships, and handle drag-and-drop operations on them, in FleetDetailPanel.
Constructor & Destructor Documentation
ShipsListBox::ShipsListBox (int fleet_id, bool order_issuing_enabled) inline
Member Function Documentation
virtual void ShipsListBox::AcceptDrops (const GG::Pt & pt, const std::vector< GG::Wnd * > & wnds, GG::Flags< GG::ModKey > mod_keys) inline virtual
References anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), ClientApp::EmpireID(), Ship::FleetID(), HumanClientApp::GetApp(), GetShip(), GetUniverse(), OrderSet::IssueOrder(), m_fleet_id, ObjectMap::Object(), Universe::Objects(), ClientApp::Orders(), and anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING.
virtual void ShipsListBox::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const inline virtual
References ErrorLogger, Ship::FleetID(), GetFleet(), GetShip(), m_order_issuing_enabled, and anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer().
void ShipsListBox::EnableOrderIssuing (bool enable) inline
References m_order_issuing_enabled.
Referenced by FleetDetailPanel::EnableOrderIssuing().
GG::Pt ShipsListBox::ListRowSize () const inline
References anonymous_namespace{FleetWnd.cpp}::ListRowHeight().
Referenced by Refresh(), and SizeMove().
void ShipsListBox::Refresh () inline
References ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), HumanClientApp::GetApp(), GetFleet(), GetUniverse(), ListRowSize(), m_fleet_id, and Fleet::ShipIDs().
Referenced by SetFleet(), and FleetDetailPanel::SetFleet().
void ShipsListBox::SetFleet (int fleet_id) inline
References m_fleet_id, and Refresh().
Referenced by FleetDetailPanel::SetFleet().
virtual void ShipsListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References ListRowSize().
Referenced by FleetDetailPanel::DoLayout().
Member Data Documentation
int ShipsListBox::m_fleet_id private
Referenced by AcceptDrops(), Refresh(), and SetFleet().
bool ShipsListBox::m_order_issuing_enabled private
Referenced by DropsAcceptable(), and EnableOrderIssuing().
The documentation for this class was generated from the following file:
FleetWnd.cpp