FreeOrion: Effect::MoveInOrbit Class Reference
Effect::MoveInOrbit Class Reference
#include <Effect.h>
Public Member Functions
MoveInOrbit (ValueRef::ValueRefBase< double > *speed, Condition::ConditionBase *focal_point_condition)
MoveInOrbit (ValueRef::ValueRefBase< double > *speed, ValueRef::ValueRefBase< double > *focus_x=0, ValueRef::ValueRefBase< double > *focus_y=0)
virtual ~MoveInOrbit ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
Condition::ConditionBase * m_focal_point_condition
ValueRef::ValueRefBase< double > * m_focus_x
ValueRef::ValueRefBase< double > * m_focus_y
ValueRef::ValueRefBase< double > * m_speed
Friends
class boost::serialization::access
Detailed Description
Moves an UniverseObject to a location as though it was moving in orbit of some object or position on the map. Sign of speed indicates CCW / CW rotation.
Constructor & Destructor Documentation
Effect::MoveInOrbit::MoveInOrbit (ValueRef::ValueRefBase< double > * speed, Condition::ConditionBase * focal_point_condition)
Effect::MoveInOrbit::MoveInOrbit (ValueRef::ValueRefBase< double > * speed, ValueRef::ValueRefBase< double > * focus_x = 0, ValueRef::ValueRefBase< double > * focus_y = 0)
Effect::MoveInOrbit::~MoveInOrbit () virtual
References m_focal_point_condition, m_focus_x, m_focus_y, and m_speed.
Member Function Documentation
std::string Effect::MoveInOrbit::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), Condition::ConditionBase::Dump(), DumpIndent(), m_focal_point_condition, m_focus_x, and m_focus_y.
void Effect::MoveInOrbit::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References anonymous_namespace{Effect.cpp}::CreateNewFleet(), ScriptingContext::effect_target, Universe::EffectDestroy(), Fleet::Empty(), ErrorLogger, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), ObjectMap::FindObjects(), GetFleet(), GetSystem(), GetUniverse(), UniverseObject::ID(), INVALID_OBJECT_ID, m_focal_point_condition, m_focus_x, m_focus_y, m_speed, UniverseObject::MoveTo(), Objects(), System::Remove(), Fleet::RemoveShip(), UniverseObject::SetSystem(), UniverseObject::SystemID(), anonymous_namespace{Effect.cpp}::UpdateFleetRoute(), UniverseObject::X(), and UniverseObject::Y().
template<class Archive > void Effect::MoveInOrbit::serialize (Archive & ar, const unsigned int version) private
References m_focal_point_condition, m_focus_x, m_focus_y, and m_speed.
void Effect::MoveInOrbit::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_focal_point_condition, m_focus_x, m_focus_y, m_speed, ValueRef::ValueRefBase< T >::SetTopLevelContent(), and Condition::ConditionBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
Condition::ConditionBase* Effect::MoveInOrbit::m_focal_point_condition private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~MoveInOrbit().
ValueRef::ValueRefBase<double>* Effect::MoveInOrbit::m_focus_x private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~MoveInOrbit().
ValueRef::ValueRefBase<double>* Effect::MoveInOrbit::m_focus_y private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~MoveInOrbit().
ValueRef::ValueRefBase<double>* Effect::MoveInOrbit::m_speed private
Referenced by Execute(), serialize(), SetTopLevelContent(), and ~MoveInOrbit().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp