FreeOrion: anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5 Struct Reference
anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< Condition::ConditionBase
*, std::vector
< Effect::EffectBase * >
, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > conditional_rule
Public Member Functions
effect_parser_rules_5 ()
Public Attributes
conditional_rule conditional
parse::effect_parser_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< Condition::ConditionBase*, std::vector<Effect::EffectBase*>, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::conditional_rule
Constructor & Destructor Documentation
anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::effect_parser_rules_5 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::effect_parser(), parse::lexer::instance(), and parse::label().
Member Data Documentation
conditional_rule anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::conditional
parse::effect_parser_rule anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::start
The documentation for this struct was generated from the following file:
EffectParser5.cpp