FreeOrion: Sound Class Reference
Sound Class Reference
#include <Sound.h>
Classes
struct TempUISoundDisabler
Public Member Functions
void DoFrame ()
void FreeAllSounds ()
void FreeSound (const boost::filesystem::path &path)
void PlayMusic (const boost::filesystem::path &path, int loops=0)
void PlaySound (const boost::filesystem::path &path, bool is_ui_sound=false)
void SetMusicVolume (int vol)
void SetUISoundsVolume (int vol)
void StopMusic ()
Static Public Member Functions
static Sound & GetSound ()
Private Member Functions
Sound ()
ctor.
~Sound ()
dotr.
bool UISoundsTemporarilyDisabled () const
Private Attributes
std::map< std::string, ALuint > m_buffers
the currently-cached (and possibly playing) sounds, if any; keyed on filename
ALuint m_music_buffers [2]
two additional buffers for music. statically defined as they'll be changed many times.
int m_music_loops
the number of loops of the current music to play (< 0 for loop forever)
std::string m_music_name
the name of the currently-playing music file
OggVorbis_File m_ogg_file
the currently open ogg file
ALenum m_ogg_format
mono or stereo
ALsizei m_ogg_freq
sampling frequency
ALuint m_sources [NUM_SOURCES]
OpenAL sound sources. The first one is used for music.
unsigned int m_temporary_disable_count
Count of the number of times sound was disabled. Sound is enabled when this is zero.
Static Private Attributes
static const int NUM_SOURCES = 16
Constructor & Destructor Documentation
Sound::Sound () private
ctor.
References anonymous_namespace{Sound.cpp}::InitOpenAL(), m_music_buffers, m_sources, and NUM_SOURCES.
Sound::~Sound () private
dotr.
References m_buffers, m_music_buffers, m_sources, NUM_SOURCES, and anonymous_namespace{Sound.cpp}::ShutdownOpenAL().
Member Function Documentation
void Sound::DoFrame ()
Does the work that must be done by the sound system once per frame.
this happens if RefillBuffer returns 1, meaning it encountered EOF and the file shouldn't be repeated
this may happen if the source plays all its buffers before we manage to refill them
References m_music_loops, m_music_name, m_ogg_file, m_ogg_format, m_ogg_freq, m_sources, and anonymous_namespace{Sound.cpp}::RefillBuffer().
Referenced by HumanClientApp::RenderBegin().
void Sound::FreeAllSounds ()
Frees all cached sound data.
References ErrorLogger, and m_buffers.
void Sound::FreeSound (const boost::filesystem::path & path)
Frees the cached sound data associated with the filename.
References ErrorLogger, permute_labels::filename, m_buffers, and PathString().
Sound & Sound::GetSound () static
Returns the singleton instance of Sound.
Referenced by HumanClientApp::HumanClientApp(), ClientUI::MessageBox(), CUIScroll::ScrollTab::MouseEnter(), CUIDropDownList::MouseEnter(), CUIButton::MouseHere(), CUIArrowButton::MouseHere(), OptionsWnd::MusicClicked(), OptionsWnd::MusicVolumeSlid(), detail::PlayValueChangedSound::operator()(), anonymous_namespace{CUIControls.cpp}::PlayButtonCheckSound(), anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound(), anonymous_namespace{CUIWnd.cpp}::PlayCloseSound(), anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound(), FleetButton::PlayFleetButtonOpenSound(), FleetButton::PlayFleetButtonRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayItemDropSound(), anonymous_namespace{CUIControls.cpp}::PlayListSelectSound(), anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound(), anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound(), anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound(), anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound(), anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound(), HumanClientApp::RenderBegin(), Sound::TempUISoundDisabler::TempUISoundDisabler(), OptionsWnd::UISoundsVolumeSlid(), and Sound::TempUISoundDisabler::~TempUISoundDisabler().
void Sound::PlayMusic (const boost::filesystem::path & path, int loops = 0)
Plays a music file. The file will be played in an infinitve loop if loop is < 0, and it will be played loops + 1 times otherwise.
References ErrorLogger, permute_labels::filename, m_music_buffers, m_music_loops, m_music_name, m_ogg_file, m_ogg_format, m_ogg_freq, m_sources, PathString(), anonymous_namespace{Sound.cpp}::RefillBuffer(), and StopMusic().
Referenced by HumanClientApp::HumanClientApp(), and OptionsWnd::MusicClicked().
void Sound::PlaySound (const boost::filesystem::path & path, bool is_ui_sound = false)
Plays a sound file.
References ErrorLogger, permute_labels::filename, GetOptionsDB(), m_buffers, m_sources, NUM_SOURCES, PathString(), anonymous_namespace{Sound.cpp}::RefillBuffer(), and UISoundsTemporarilyDisabled().
Referenced by ClientUI::MessageBox(), CUIScroll::ScrollTab::MouseEnter(), CUIDropDownList::MouseEnter(), CUIButton::MouseHere(), CUIArrowButton::MouseHere(), detail::PlayValueChangedSound::operator()(), anonymous_namespace{CUIControls.cpp}::PlayButtonCheckSound(), anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound(), anonymous_namespace{CUIWnd.cpp}::PlayCloseSound(), anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound(), FleetButton::PlayFleetButtonOpenSound(), FleetButton::PlayFleetButtonRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayItemDropSound(), anonymous_namespace{CUIControls.cpp}::PlayListSelectSound(), anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound(), anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound(), anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound(), anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound(), anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound(), and OptionsWnd::UISoundsVolumeSlid().
void Sound::SetMusicVolume (int vol)
Sets the music volume from 0 (muted) to 255 (full volume); vol is range-adjusted.
References ErrorLogger, GetOptionsDB(), m_sources, and OptionsDB::Set().
Referenced by HumanClientApp::HumanClientApp(), and OptionsWnd::MusicVolumeSlid().
void Sound::SetUISoundsVolume (int vol)
Sets the UI sounds volume from 0 (muted) to 255 (full volume); vol is range-adjusted.
References ErrorLogger, GetOptionsDB(), m_sources, NUM_SOURCES, and OptionsDB::Set().
Referenced by HumanClientApp::HumanClientApp(), and OptionsWnd::UISoundsVolumeSlid().
void Sound::StopMusic ()
Stops playing music.
References m_music_name, m_ogg_file, and m_sources.
Referenced by OptionsWnd::MusicClicked(), and PlayMusic().
bool Sound::UISoundsTemporarilyDisabled () const private
References m_temporary_disable_count.
Referenced by PlaySound().
Member Data Documentation
std::map<std::string, ALuint> Sound::m_buffers private
the currently-cached (and possibly playing) sounds, if any; keyed on filename
Referenced by FreeAllSounds(), FreeSound(), PlaySound(), and ~Sound().
ALuint Sound::m_music_buffers[2] private
two additional buffers for music. statically defined as they'll be changed many times.
Referenced by PlayMusic(), Sound(), and ~Sound().
int Sound::m_music_loops private
the number of loops of the current music to play (< 0 for loop forever)
Referenced by DoFrame(), and PlayMusic().
std::string Sound::m_music_name private
the name of the currently-playing music file
Referenced by DoFrame(), PlayMusic(), and StopMusic().
OggVorbis_File Sound::m_ogg_file private
the currently open ogg file
Referenced by DoFrame(), PlayMusic(), and StopMusic().
ALenum Sound::m_ogg_format private
mono or stereo
Referenced by DoFrame(), and PlayMusic().
ALsizei Sound::m_ogg_freq private
sampling frequency
Referenced by DoFrame(), and PlayMusic().
ALuint Sound::m_sources[NUM_SOURCES] private
OpenAL sound sources. The first one is used for music.
Referenced by DoFrame(), PlayMusic(), PlaySound(), SetMusicVolume(), SetUISoundsVolume(), Sound(), StopMusic(), and ~Sound().
unsigned int Sound::m_temporary_disable_count private
Count of the number of times sound was disabled. Sound is enabled when this is zero.
Referenced by Sound::TempUISoundDisabler::TempUISoundDisabler(), UISoundsTemporarilyDisabled(), and Sound::TempUISoundDisabler::~TempUISoundDisabler().
const int Sound::NUM_SOURCES = 16 static private
Referenced by PlaySound(), SetUISoundsVolume(), Sound(), and ~Sound().
The documentation for this class was generated from the following files:
Sound.h
Sound.cpp