FreeOrion: ObjectListBox Class Reference
ObjectListBox Class Reference
Public Member Functions
ObjectListBox ()
virtual ~ObjectListBox ()
bool AnythingCollapsed () const
void ClearContents ()
void CollapseObject (int object_id=INVALID_OBJECT_ID)
void ExpandObject (int object_id=INVALID_OBJECT_ID)
const Condition::ConditionBase
*const FilterCondition () const
GG::Pt ListRowSize () const
bool ObjectCollapsed (int object_id) const
bool ObjectShown (TemporaryPtr< const UniverseObject > obj, bool assume_visible_without_checking=false)
void Refresh ()
void SetFilterCondition (Condition::ConditionBase *condition)
void SetVisibilityFilters (const std::map< UniverseObjectType, std::set< VIS_DISPLAY > > &vis)
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
void SortingClicked (int clicked_column)
void UpdateObjectPanel (int object_id=INVALID_OBJECT_ID)
const std::map
< UniverseObjectType, std::set
< VIS_DISPLAY > > Visibilities () const
Public Member Functions inherited from CUIListBox
CUIListBox (void)
basic ctor
virtual void Render ()
Static Public Member Functions
static GG::Y ListRowHeight ()
Public Attributes
boost::signals2::signal< void()> ExpandCollapseSignal
Private Member Functions
void AddObjectRow (int object_id, int container, const std::set< int > &contents, int indent)
void AddObjectRow (int object_id, int container, const std::set< int > &contents, int indent, GG::ListBox::iterator it)
void ObjectExpandCollapseClicked (int object_id)
void ObjectStateChanged (int object_id)
void RemoveObjectRow (int object_id)
void RemoveObjectRow (GG::ListBox::iterator it)
void UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj)
Private Attributes
std::set< int > m_collapsed_objects
Condition::ConditionBase * m_filter_condition
ObjectHeaderRow * m_header_row
boost::signals2::connection m_obj_deleted_connection
std::map< int,
boost::signals2::connection > m_object_change_connections
std::map< UniverseObjectType,
std::set< VIS_DISPLAY > > m_visibilities
Constructor & Destructor Documentation
ObjectListBox::ObjectListBox () inline
References Condition::All(), ObjectHeaderRow::ColumnHeaderLeftClickSignal, ObjectHeaderRow::ColumnsChangedSignal, GetUniverse(), ListRowHeight(), m_filter_condition, m_header_row, m_obj_deleted_connection, m_visibilities, Refresh(), anonymous_namespace{ObjectListWnd.cpp}::SHOW_PREVIOUSLY_VISIBLE, anonymous_namespace{ObjectListWnd.cpp}::SHOW_VISIBLE, SortingClicked(), and UniverseObjectDeleted().
virtual ObjectListBox::~ObjectListBox () inline virtual
References m_filter_condition.
Member Function Documentation
void ObjectListBox::AddObjectRow (int object_id, int container, const std::set< int > & contents, int indent) inline private
Referenced by Refresh().
void ObjectListBox::AddObjectRow (int object_id, int container, const std::set< int > & contents, int indent, GG::ListBox::iterator it) inline private
References ObjectRow::ExpandCollapseSignal, GetUniverseObject(), UniverseObject::ID(), ListRowSize(), m_object_change_connections, ObjectCollapsed(), ObjectExpandCollapseClicked(), ObjectStateChanged(), and UniverseObject::StateChangedSignal.
bool ObjectListBox::AnythingCollapsed () const inline
References m_collapsed_objects.
Referenced by ObjectListWnd::CollapseExpandClicked(), and ObjectListWnd::DoLayout().
void ObjectListBox::ClearContents () inline
References m_object_change_connections.
Referenced by Refresh().
void ObjectListBox::CollapseObject (int object_id = INVALID_OBJECT_ID) inline
References INVALID_OBJECT_ID, m_collapsed_objects, and Refresh().
Referenced by ObjectListWnd::CollapseExpandClicked(), and ObjectExpandCollapseClicked().
void ObjectListBox::ExpandObject (int object_id = INVALID_OBJECT_ID) inline
References INVALID_OBJECT_ID, m_collapsed_objects, and Refresh().
Referenced by ObjectListWnd::CollapseExpandClicked(), and ObjectExpandCollapseClicked().
const Condition::ConditionBase* const ObjectListBox::FilterCondition () const inline
References m_filter_condition.
Referenced by ObjectListWnd::FilterClicked().
static GG::Y ObjectListBox::ListRowHeight () inline static
References ClientUI::Pts().
Referenced by ListRowSize(), and ObjectListBox().
GG::Pt ObjectListBox::ListRowSize () const inline
References ListRowHeight(), and ClientUI::ScrollWidth().
Referenced by AddObjectRow(), and SizeMove().
bool ObjectListBox::ObjectCollapsed (int object_id) const inline
References INVALID_OBJECT_ID, and m_collapsed_objects.
Referenced by AddObjectRow(), ObjectExpandCollapseClicked(), and Refresh().
void ObjectListBox::ObjectExpandCollapseClicked (int object_id) inline private
References CollapseObject(), ExpandCollapseSignal, ExpandObject(), INVALID_OBJECT_ID, and ObjectCollapsed().
Referenced by AddObjectRow().
bool ObjectListBox::ObjectShown (TemporaryPtr< const UniverseObject > obj, bool assume_visible_without_checking = false) inline
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetUniverse(), UniverseObject::ID(), m_filter_condition, m_visibilities, UniverseObject::ObjectType(), anonymous_namespace{ObjectListWnd.cpp}::SHOW_DESTROYED, anonymous_namespace{ObjectListWnd.cpp}::SHOW_PREVIOUSLY_VISIBLE, and anonymous_namespace{ObjectListWnd.cpp}::SHOW_VISIBLE.
Referenced by Refresh().
void ObjectListBox::ObjectStateChanged (int object_id) inline private
References DebugLogger, GetUniverseObject(), INVALID_OBJECT_ID, UniverseObject::Name(), UniverseObject::ObjectType(), Refresh(), and UpdateObjectPanel().
Referenced by AddObjectRow().
void ObjectListBox::Refresh () inline
References AddObjectRow(), parse::buildings(), ClearContents(), ObjectMap::const_begin(), ObjectMap::const_end(), parse::fields(), GetUniverse(), UniverseObject::ID(), if(), INVALID_OBJECT_ID, m_header_row, ObjectCollapsed(), Universe::Objects(), ObjectShown(), UniverseObject::ObjectType(), and ObjectHeaderRow::Update().
Referenced by CollapseObject(), ExpandObject(), ObjectListBox(), ObjectStateChanged(), ObjectListWnd::Refresh(), SetFilterCondition(), SetVisibilityFilters(), and SortingClicked().
void ObjectListBox::RemoveObjectRow (int object_id) inline private
References INVALID_OBJECT_ID.
Referenced by RemoveObjectRow(), and UniverseObjectDeleted().
void ObjectListBox::RemoveObjectRow (GG::ListBox::iterator it) inline private
References ObjectRow::ContainedByPanel(), ObjectRow::ContainedPanels(), m_object_change_connections, ObjectRow::ObjectID(), and RemoveObjectRow().
void ObjectListBox::SetFilterCondition (Condition::ConditionBase * condition) inline
References m_filter_condition, and Refresh().
Referenced by ObjectListWnd::FilterClicked().
void ObjectListBox::SetVisibilityFilters (const std::map< UniverseObjectType, std::set< VIS_DISPLAY > > & vis) inline
References m_visibilities, and Refresh().
Referenced by ObjectListWnd::FilterClicked().
virtual void ObjectListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References ListRowSize(), and m_header_row.
Referenced by ObjectListWnd::DoLayout().
void ObjectListBox::SortingClicked (int clicked_column) inline
References anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), and Refresh().
Referenced by ObjectListBox().
void ObjectListBox::UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj) inline private
References UniverseObject::ID(), and RemoveObjectRow().
Referenced by ObjectListBox().
void ObjectListBox::UpdateObjectPanel (int object_id = INVALID_OBJECT_ID) inline
References INVALID_OBJECT_ID.
Referenced by ObjectStateChanged().
const std::map<UniverseObjectType, std::set<VIS_DISPLAY> > ObjectListBox::Visibilities () const inline
References m_visibilities.
Referenced by ObjectListWnd::FilterClicked().
Member Data Documentation
boost::signals2::signal<void ()> ObjectListBox::ExpandCollapseSignal mutable
Referenced by ObjectExpandCollapseClicked(), and ObjectListWnd::ObjectListWnd().
std::set<int> ObjectListBox::m_collapsed_objects private
Referenced by AnythingCollapsed(), CollapseObject(), ExpandObject(), and ObjectCollapsed().
Condition::ConditionBase* ObjectListBox::m_filter_condition private
Referenced by FilterCondition(), ObjectListBox(), ObjectShown(), SetFilterCondition(), and ~ObjectListBox().
ObjectHeaderRow* ObjectListBox::m_header_row private
Referenced by ObjectListBox(), Refresh(), and SizeMove().
boost::signals2::connection ObjectListBox::m_obj_deleted_connection private
Referenced by ObjectListBox().
std::map<int, boost::signals2::connection> ObjectListBox::m_object_change_connections private
Referenced by AddObjectRow(), ClearContents(), and RemoveObjectRow().
std::map<UniverseObjectType, std::set<VIS_DISPLAY> > ObjectListBox::m_visibilities private
Referenced by ObjectListBox(), ObjectShown(), SetVisibilityFilters(), and Visibilities().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp