FreeOrion: anonymous_namespace{MarkupBox.cpp} Namespace Reference
anonymous_namespace{MarkupBox.cpp} Namespace Reference
Classes
struct MarkupTextBlock
Enumerations
enum MarkupTextBlockType {
INVALID_MARKUP_TEXT_BLOCK_TYPE = -1, PLAIN_TEXT_MARKUP, HEADING_MARKUP, IMAGE_MARKUP,
NUM_MARKUP_TEXT_BLOCK_TYPES
}
Functions
static const int EDGE_PAD (3)
static const std::string EMPTY_STRING ("")
static const std::string HEADING_TAG ("h")
static const std::string IMAGE_TAG ("img")
std::vector< MarkupTextBlock > ParseMarkupText (const std::string &text)
void RegisterMarkupTags ()
static const GG::X SCROLL_WIDTH (14)
static const GG::Y VERY_FAR_DOWN_LAYOUT_SURFACE (2<< 15)
Variables
static bool markup_tags_registered = false
Enumeration Type Documentation
enum anonymous_namespace{MarkupBox.cpp}::MarkupTextBlockType
types of text that can appear in a MarkupBox input string, depending on present (or absence of) enclosing markup tags.
Enumerator
INVALID_MARKUP_TEXT_BLOCK_TYPE
PLAIN_TEXT_MARKUP
HEADING_MARKUP
IMAGE_MARKUP
NUM_MARKUP_TEXT_BLOCK_TYPES
Function Documentation
static const int anonymous_namespace{MarkupBox.cpp}::EDGE_PAD (3) static
Referenced by MarkupBox::MarkupBox(), MarkupBox::MarkupSurface::Refresh(), and MarkupBox::SizeMove().
static const std::string anonymous_namespace{MarkupBox.cpp}::EMPTY_STRING ("") static
Referenced by MarkupBox::Text().
static const std::string anonymous_namespace{MarkupBox.cpp}::HEADING_TAG ("h") static
static const std::string anonymous_namespace{MarkupBox.cpp}::IMAGE_TAG ("img") static
std::vector<MarkupTextBlock> anonymous_namespace{MarkupBox.cpp}::ParseMarkupText (const std::string & text)
Parses text and returns array of MarkupTextBlock that can be individually interpreted as a single type of object on MarkupSurface (heading, plain text, image...)
References anonymous_namespace{XMLDoc.cpp}::CharData, DebugLogger, ClientUI::GetFont(), HEADING_MARKUP, IMAGE_MARKUP, anonymous_namespace{MarkupBox.cpp}::MarkupTextBlock::params, PLAIN_TEXT_MARKUP, anonymous_namespace{Version.cpp}::retval, anonymous_namespace{MarkupBox.cpp}::MarkupTextBlock::text, and anonymous_namespace{MarkupBox.cpp}::MarkupTextBlock::type.
Referenced by MarkupBox::MarkupSurface::Refresh().
void anonymous_namespace{MarkupBox.cpp}::RegisterMarkupTags ()
Ensures GG::Font knows about markup tags.
Referenced by MarkupBox::MarkupBox().
static const GG::X anonymous_namespace{MarkupBox.cpp}::SCROLL_WIDTH (14) static
Referenced by MarkupBox::AdjustScrolls(), and MarkupBox::SizeMove().
static const GG::Y anonymous_namespace{MarkupBox.cpp}::VERY_FAR_DOWN_LAYOUT_SURFACE (2<< 15) static
Referenced by MarkupBox::MarkupSurface::Refresh().
Variable Documentation
bool anonymous_namespace{MarkupBox.cpp}::markup_tags_registered = false static