FreeOrion: AIClientApp.cpp File Reference
AIClientApp.cpp File Reference
#include "AIClientApp.h"
#include "AIFramework.h"
#include "../ClientNetworking.h"
#include "../../util/Logger.h"
#include "../../util/LoggerWithOptionsDB.h"
#include "../../util/OptionsDB.h"
#include "../../util/Directories.h"
#include "../../util/Serialize.h"
#include "../../util/i18n.h"
#include "../util/AppInterface.h"
#include "../../network/Message.h"
#include "../util/Random.h"
#include "../util/Version.h"
#include "../../universe/System.h"
#include "../../universe/Species.h"
#include "../../universe/Universe.h"
#include "../../util/OrderSet.h"
#include "../../util/Order.h"
#include "../../Empire/Empire.h"
#include "../../Empire/Diplomacy.h"
#include <boost/lexical_cast.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/functional/hash.hpp>
#include <boost/uuid/nil_generator.hpp>
#include <thread>
#include <chrono>
Namespaces
anonymous_namespace{AIClientApp.cpp}
Functions
void anonymous_namespace{AIClientApp.cpp}::AddOptions (OptionsDB &db)
template<typename T >
void anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption (OptionsDB &db, std::string const &root, std::string ROOT, T def, ValidatorBase const &validator)
AddTraitBypassOption creates a set of options for debugging of the form: ai.trait.
CombatLogManager & GetCombatLogManager ()
Variables
bool anonymous_namespace{AIClientApp.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
GetCombatLogManager()
CombatLogManager& GetCombatLogManager ()
Referenced by ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps(), AIClientApp::HandleMessage(), ServerApp::LoadGameInit(), ServerApp::PostCombatProcessTurns(), HumanClientApp::ResetClientData(), ServerApp::SendNewGameStartMessages(), HumanClientApp::UpdateCombatLogManager(), HumanClientApp::UpdateCombatLogs(), ServerApp::UpdateCombatLogs(), and ClientUI::ZoomToCombatLog().