FreeOrion: AIWrapper.cpp File Reference
AIWrapper.cpp File Reference
#include "AIWrapper.h"
#include "AIInterface.h"
#include "../ClientApp.h"
#include "../../universe/Universe.h"
#include "../../util/AppInterface.h"
#include "../../util/Directories.h"
#include "../../util/Logger.h"
#include "../../util/i18n.h"
#include "../../util/MultiplayerCommon.h"
#include "../../util/OptionsDB.h"
#include "../../util/OrderSet.h"
#include "../../util/Order.h"
#include "../../Empire/Empire.h"
#include "../../Empire/EmpireManager.h"
#include "../../Empire/Diplomacy.h"
#include "../../python/SetWrapper.h"
#include "../../python/CommonWrappers.h"
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
#include <boost/python/suite/indexing/map_indexing_suite.hpp>
#include <boost/mpl/vector.hpp>
#include <boost/python/list.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/scope.hpp>
Namespaces
anonymous_namespace{AIWrapper.cpp}
FreeOrionPython
Functions
int anonymous_namespace{AIWrapper.cpp}::AppendFleetMoveOrder (int fleet_id, int destination_id)
void FreeOrionPython::ClearStaticSaveStateString ()
std::string anonymous_namespace{AIWrapper.cpp}::GetAIDir ()
Return the canonical AI directory path.
const std::string & FreeOrionPython::GetStaticSaveStateString ()
boost::python::list anonymous_namespace{AIWrapper.cpp}::GetUserStringList (const std::string &list_key)
template<typename OrderType , typename... Args>
int anonymous_namespace{AIWrapper.cpp}::Issue (Args &&... args)
int anonymous_namespace{AIWrapper.cpp}::IssueAggressionOrder (int object_id, bool aggressive)
int anonymous_namespace{AIWrapper.cpp}::IssueBombardOrder (int ship_id, int planet_id)
int anonymous_namespace{AIWrapper.cpp}::IssueChangeFocusOrder (int planet_id, const std::string &focus)
int anonymous_namespace{AIWrapper.cpp}::IssueColonizeOrder (int ship_id, int planet_id)
int anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrderWrapper (const std::string &name, const std::string &description, const std::string &hull, boost::python::list parts_list, const std::string &icon, const std::string &model, bool name_desc_in_stringtable)
int anonymous_namespace{AIWrapper.cpp}::IssueFleetMoveOrder (int fleet_id, int destination_id)
int anonymous_namespace{AIWrapper.cpp}::IssueFleetTransferOrder (int ship_id, int new_fleet_id)
int anonymous_namespace{AIWrapper.cpp}::IssueGiveObjectToEmpireOrder (int object_id, int recipient_id)
int anonymous_namespace{AIWrapper.cpp}::IssueInvadeOrder (int ship_id, int planet_id)
int anonymous_namespace{AIWrapper.cpp}::IssueNewFleetOrder (const std::string &fleet_name, int ship_id)
int anonymous_namespace{AIWrapper.cpp}::IssueRenameOrder (int object_id, const std::string &new_name)
int anonymous_namespace{AIWrapper.cpp}::IssueScrapOrder (int object_id)
static std::string anonymous_namespace{AIWrapper.cpp}::s_save_state_string ("")
void FreeOrionPython::SetStaticSaveStateString (const std::string &new_state_string)
void FreeOrionPython::WrapAI ()
Expose AIInterface to Python.
Variables
const Empire *(* AIIntGetEmpireInt)(int) = &AIInterface::GetEmpire
const Empire *(* AIIntGetEmpireVoid)(void) = &AIInterface::GetEmpire
const std::string &(* AIIntPlayerNameInt)(int) = &AIInterface::PlayerName
const std::string &(* AIIntPlayerNameVoid)(void) = &AIInterface::PlayerName
Variable Documentation
AIIntGetEmpireInt
const Empire*(* AIIntGetEmpireInt) (int) = &AIInterface::GetEmpire
Referenced by FreeOrionPython::WrapAI().
AIIntGetEmpireVoid
const Empire*(* AIIntGetEmpireVoid) (void) = &AIInterface::GetEmpire
Referenced by FreeOrionPython::WrapAI().
AIIntPlayerNameInt
const std::string&(* AIIntPlayerNameInt) (int) = &AIInterface::PlayerName
Referenced by FreeOrionPython::WrapAI().
AIIntPlayerNameVoid
const std::string&(* AIIntPlayerNameVoid) (void) = &AIInterface::PlayerName
Referenced by FreeOrionPython::WrapAI().