FreeOrion: AppInterface.cpp File Reference
AppInterface.cpp File Reference
#include "AppInterface.h"
#include "../parse/Parse.h"
#include "../Empire/EmpireManager.h"
#include "../universe/Building.h"
#include "../universe/Encyclopedia.h"
#include "../universe/Field.h"
#include "../universe/Special.h"
#include "../universe/Species.h"
#include "../universe/Tech.h"
#include "../util/Directories.h"
#include "../util/GameRules.h"
#include "../util/Pending.h"
#include <boost/filesystem.hpp>
#include <boost/filesystem/operations.hpp>
#include <future>
Functions
template TechManager::TechParseTuple parse::techs< TechManager::TechParseTuple > (const boost::filesystem::path &path)
Variables
const int BEFORE_FIRST_TURN = -(2 << 14)
returned by CurrentGameTurn if the galaxy is currently being set up
const int IMPOSSIBLY_LARGE_TURN = 2 << 15
a number that's almost assuredly larger than any real turn number that might come up
const int INVALID_GAME_TURN = -(2 << 15) + 1
returned by CurrentGameTurn if a game is not currently in progress or being set up.
Function Documentation
parse::techs< TechManager::TechParseTuple >()
template TechManager::TechParseTuple parse::techs< TechManager::TechParseTuple > (const boost::filesystem::path & path)
Variable Documentation
BEFORE_FIRST_TURN
const int BEFORE_FIRST_TURN = -(2 << 14)
returned by CurrentGameTurn if the galaxy is currently being set up
Referenced by UniverseObject::AgeInTurns(), Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), Condition::HasSpecial::Dump(), EffectsProcessingThreads(), Condition::HasSpecial::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Turn::Match(), Condition::HasSpecial::Match(), Condition::CreatedOnTurn::Match(), ServerApp::NewGameInitConcurrentWithJoiners(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), Empire::serialize(), and anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate().
IMPOSSIBLY_LARGE_TURN
const int IMPOSSIBLY_LARGE_TURN = 2 << 15
a number that's almost assuredly larger than any real turn number that might come up
Referenced by Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), Condition::HasSpecial::Dump(), EffectsProcessingThreads(), Condition::HasSpecial::Eval(), Condition::CreatedOnTurn::Eval(), ValueRef::ComplexVariable< T >::Eval(), Condition::Turn::Match(), Condition::HasSpecial::Match(), Condition::CreatedOnTurn::Match(), and Condition::DesignHasPart::Match().
INVALID_GAME_TURN
const int INVALID_GAME_TURN = -(2 << 15) + 1
returned by CurrentGameTurn if a game is not currently in progress or being set up.
Referenced by UniverseObject::AgeInTurns(), EffectsProcessingThreads(), ValueRef::Variable< ToType >::Eval(), SitRepPanel::GetNextNonEmptySitrepsTurn(), ResourceCenter::Init(), Empire::meter_end(), Empire::NumSitRepEntries(), WaitingForGameStart::react(), WaitingForTurnData::react(), ResourceCenter::Reset(), MapWnd::Sanitize(), UniverseObject::SpecialAddedOnTurn(), ResourceCenter::TurnsSinceFocusChange(), SitRepPanel::Update(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateStatRecords(), and FreeOrionPython::WrapAI().