FreeOrion: AppInterface.h File Reference
AppInterface.h File Reference
#include "Export.h"
#include "../universe/Universe.h"
#include "../network/Networking.h"
Classes
class IApp
class IApp::NormalExitException
Functions
int CurrentTurn ()
Returns current game turn.
int EffectsProcessingThreads ()
ObjectMap & EmpireKnownObjects (int empire_id)
Accessor for known objects of specified empire.
EmpireManager & Empires ()
Accessor for the App's empire manager.
std::shared_ptr< Building > GetBuilding (int object_id)
Empire * GetEmpire (int id)
Accessor for Empires.
Networking::ClientType GetEmpireClientType (int empire_id)
std::shared_ptr< Building > GetEmpireKnownBuilding (int object_id, int empire_id)
std::shared_ptr< Field > GetEmpireKnownField (int object_id, int empire_id)
std::shared_ptr< Fleet > GetEmpireKnownFleet (int object_id, int empire_id)
std::shared_ptr< UniverseObject > GetEmpireKnownObject (int object_id, int empire_id)
std::shared_ptr< Planet > GetEmpireKnownPlanet (int object_id, int empire_id)
std::shared_ptr< PopCenter > GetEmpireKnownPopCenter (int object_id, int empire_id)
std::shared_ptr< ResourceCenter > GetEmpireKnownResourceCenter (int object_id, int empire_id)
std::shared_ptr< Ship > GetEmpireKnownShip (int object_id, int empire_id)
std::shared_ptr< System > GetEmpireKnownSystem (int object_id, int empire_id)
std::shared_ptr< Field > GetField (int object_id)
std::shared_ptr< Fleet > GetFleet (int object_id)
const GalaxySetupData & GetGalaxySetupData ()
Returns the galaxy setup settings used in the current game.
std::shared_ptr< const Pathfinder > GetPathfinder ()
Accessor for the App's universe object.
std::shared_ptr< Planet > GetPlanet (int object_id)
Networking::ClientType GetPlayerClientType (int player_id)
std::shared_ptr< PopCenter > GetPopCenter (int object_id)
std::shared_ptr< ResourceCenter > GetResourceCenter (int object_id)
std::shared_ptr< Ship > GetShip (int object_id)
SupplyManager & GetSupplyManager ()
Accessor for the App's empire supply manager.
std::shared_ptr< System > GetSystem (int object_id)
Universe & GetUniverse ()
Accessor for the App's universe object.
std::shared_ptr< UniverseObject > GetUniverseObject (int object_id)
Accessor for individual objects.
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object)
Returns the object name of the universe object.
ObjectMap & Objects ()
Accessor for all (on server) or all known (on client) objects ObjectMap.
Variables
FO_COMMON_API const int BEFORE_FIRST_TURN
returned by CurrentGameTurn if the galaxy is currently being set up
FO_COMMON_API const int IMPOSSIBLY_LARGE_TURN
a number that's almost assuredly larger than any real turn number that might come up
FO_COMMON_API const int INVALID_GAME_TURN
returned by CurrentGameTurn if a game is not currently in progress or being set up.
Function Documentation
CurrentTurn()
int CurrentTurn () inline
Returns current game turn.
This is >= 1 during a game, BEFORE_FIRST_TURN during galaxy setup, or is INVALID_GAME_TURN at other times
References IApp::CurrentTurn(), and IApp::GetApp().
Referenced by DesignWnd::MainPanel::AddDesign(), UniverseObject::AddSpecial(), Empire::AddTech(), UniverseObject::AgeInTurns(), anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipFighter(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), AutoResolveCombat(), Empire::CheckProductionProgress(), ResourceCenter::ClearFocus(), Planet::Conquer(), CreateBuildingBuiltSitRep(), CreateBuildingTypeUnlockedSitRep(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateCombatSitRep(), CreateEmpireEliminatedSitRep(), CreateFleetArrivedAtDestinationSitRep(), CreateGroundCombatSitRep(), CreatePlanetCapturedSitRep(), CreatePlanetColonizedSitRep(), CreatePlanetDepopulatedSitRep(), CreatePlanetOutpostedSitRep(), CreateShipBlockBuiltSitRep(), CreateShipBuiltSitRep(), CreateShipHullUnlockedSitRep(), CreateShipPartUnlockedSitRep(), CreateTechResearchedSitRep(), CreateTechUnlockedSitRep(), CreateVictorySitRep(), MapWnd::EnableOrderIssuing(), Condition::Turn::Eval(), ValueRef::Variable< ToType >::Eval(), Effect::GenerateSitRepMessage::Execute(), FleetWnd::FleetRightClicked(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitTurn(), System::Insert(), AIInterface::IssueCreateShipDesignOrder(), SitRepPanel::LastClicked(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Condition::Turn::Match(), SitRepPanel::NumVisibleSitrepsThisTurn(), PlayingTurn::PlayingTurn(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), DesignWnd::MainPanel::RefreshIncompleteDesign(), Ship::Resupply(), WaitingForTurnEnd::SaveTimedoutHandler(), ResourceCenter::SetFocus(), FleetDetailPanel::ShipRightClicked(), ResourceCenter::TurnsSinceFocusChange(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateStatRecords(), FreeOrionPython::WrapAI(), and FreeOrionPython::WrapServer().
EffectsProcessingThreads()
int EffectsProcessingThreads () inline
References BEFORE_FIRST_TURN, IApp::EffectsProcessingThreads(), FO_COMMON_API, IApp::GetApp(), IMPOSSIBLY_LARGE_TURN, and INVALID_GAME_TURN.
Referenced by Universe::GetEffectsAndTargets().
EmpireKnownObjects()
ObjectMap& EmpireKnownObjects (int empire_id) inline
Accessor for known objects of specified empire.
References IApp::EmpireKnownObjects(), and IApp::GetApp().
Referenced by Universe::ForgetKnownObject(), Universe::InitializeSystemGraph(), Universe::Objects(), anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::operator()(), Empire::UpdateSupplyUnobstructedSystems(), and Empire::UpdateSystemSupplyRanges().
Empires()
EmpireManager& Empires () inline
Accessor for the App's empire manager.
References IApp::Empires(), and IApp::GetApp().
Referenced by anonymous_namespace{Pathfinder.cpp}::GraphImpl::AddSystemPredicate(), anonymous_namespace{SitRepPanel.cpp}::AllSitRepTemplateStrings(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), Fleet::BlockadedAtSystem(), InvadeOrder::Check(), BombardOrder::Check(), GiveObjectToEmpireOrder::Check(), anonymous_namespace{SaveLoad.cpp}::CompileSaveGameEmpireData(), PlayerListWnd::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), Empire::ConquerProductionQueueItemsAtLocation(), Universe::Destroy(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout(), UniverseObject::Dump(), Empire::Eliminate(), ModeratorActionsWnd::EmpireIDFromIndex(), Universe::EmpireVisibleObjectIDs(), BuildingType::EnqueueLocation(), ValueRef::ComplexVariable< T >::Eval(), Effect::GenerateSitRepMessage::Execute(), Effect::SetVisibility::Execute(), MessageWndEdit::FindGameWords(), FleetWnd::FleetRightClicked(), SupplyManager::FleetSupplyableSystemIDs(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep(), anonymous_namespace{ServerWrapper.cpp}::GetAllEmpires(), ConditionWidget::GetCondition(), Universe::GetEffectsAndTargets(), anonymous_namespace{Universe.cpp}::GetEmpiresDetectionStrengths(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetFloatEmpirePropertySingleKey(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetFloatEmpirePropertySumAllIntKeys(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertyNoKey(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySingleKey(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySumAllIntKeys(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySumAllStringKeys(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), ServerFSM::HandleNonLobbyDisconnection(), Fighter::HostileToEmpire(), Ship::HostileToEmpire(), Building::HostileToEmpire(), Fleet::HostileToEmpire(), Planet::HostileToEmpire(), InitEmpires(), MapWnd::InitTurn(), Condition::Capital::Match(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), PlayerListWnd::PlayerRightClicked(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), BuildingType::ProductionCost(), PartType::ProductionCost(), HullType::ProductionCost(), BuildingType::ProductionLocation(), BuildingType::ProductionTime(), PartType::ProductionTime(), HullType::ProductionTime(), SidePanel::PlanetPanel::RClick(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), WaitingForTurnEnd::react(), PlayingTurn::react(), PlayerListWnd::Refresh(), ModeratorActionsWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), Tech::ResearchCost(), Tech::ResearchTime(), Empire::serialize(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies(), SupplyManager::SystemHasFleetSupply(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), Universe::UpdateEmpireObjectVisibilities(), Pathfinder::PathfinderImpl::UpdateEmpireVisibilityFilteredSystemGraphs(), ConditionWidget::UpdateParameterControls(), Universe::UpdateStatRecords(), Empire::UpdateSupplyUnobstructedSystems(), and Empire::Win().
GetBuilding()
std::shared_ptr<Building> GetBuilding (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by BuildingIndicator::BuildingIndicator(), Planet::Colonize(), ScrapOrder::ExecuteImpl(), anonymous_namespace{UniverseWrapper.cpp}::GetBuildingP(), BuildingIndicator::RClick(), BuildingIndicator::Refresh(), SidePanel::PlanetPanel::Refresh(), Planet::Reset(), ScrapOrder::UndoImpl(), BuildingsPanel::Update(), and ClientUI::ZoomToBuilding().
GetEmpire()
Empire* GetEmpire (int id) inline
Accessor for Empires.
References IApp::GetApp(), and IApp::GetEmpire().
Referenced by ProductionWnd::AddBuildToQueueSlot(), DesignWnd::MainPanel::AddDesign(), anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), ResearchWnd::AddTechsToQueueSlot(), TechTreeWnd::AddTechToResearchQueue(), Fleet::BlockadedAtSystem(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), BuildDesignatorWnd::BuildItemRequested(), anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), anonymous_namespace{MapWnd.cpp}::CanResupplyAfterDestination(), BuildDesignatorWnd::CenterOnBuild(), TechTreeWnd::CenterOnTech(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), GiveObjectToEmpireOrder::Check(), ResourceInfoPanel::ClearLocalInfo(), anonymous_namespace{SystemIcon.cpp}::ColorNameByOwners(), IncapacitationEvent::CombatLogDescription(), BuildingsPanel::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), Empire::ConquerProductionQueueItemsAtLocation(), Universe::CountDestructionInStats(), anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), ColorByOwner::Decorate(), anonymous_namespace{SitRepPanel.cpp}::ColorEmpire::Decorate(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), ResearchWnd::DeleteQueueItem(), ProductionWnd::DeleteQueueItem(), Condition::EmpireAffiliation::Description(), Condition::Enqueued::Description(), Condition::ProducedByEmpire::Description(), Condition::EmpireMeterValue::Description(), Condition::VisibleToEmpire::Description(), Condition::ExploredByEmpire::Description(), Condition::FleetSupplyableByEmpire::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), MapWnd::DispatchFleetsExploring(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability(), EmpireManager::DumpDiplomacy(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), anonymous_namespace{CombatEvents.cpp}::EmpireColorWrappedText(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::EmpireDetectionStrength(), anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{ServerWrapper.cpp}::EmpireSetHomeworld(), anonymous_namespace{ServerWrapper.cpp}::EmpireSetName(), anonymous_namespace{ServerWrapper.cpp}::EmpireUnlockItem(), ValueRef::NameLookup::Eval(), ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetEmpireMeter::Execute(), Effect::SetEmpireStockpile::Execute(), Effect::SetEmpireCapital::Execute(), Effect::CreateShip::Execute(), Effect::Victory::Execute(), Effect::SetEmpireTechProgress::Execute(), Effect::GiveEmpireTech::Execute(), Effect::GenerateSitRepMessage::Execute(), Effect::SetVisibility::Execute(), anonymous_namespace{Effect.cpp}::ExploreSystem(), anonymous_namespace{MapWnd.cpp}::ExploringFleetResupplyRoute(), FleetButton::FleetButton(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireIntFloatMap(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireIntIntMap(), anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths(), anonymous_namespace{Universe.cpp}::GetEmpiresDetectionStrengths(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireStringIntMap(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertyNoKeyImpl(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), Order::GetValidatedEmpire(), ServerFSM::HandleNonLobbyDisconnection(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), MapWnd::InitTurn(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), SystemIcon::MouseEnter(), MapWnd::MovementLineData::MovementLineData(), Fleet::MovementPhase(), Fleet::MovePath(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), ObjectListWnd::ObjectRightClicked(), Condition::anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EmpireStockpileValueSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasTechSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipDesignAvailableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipPartAvailableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ExploredByEmpireSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeOutpost(), PlayerListWnd::PlayerRightClicked(), Planet::PopGrowthProductionResearchPhase(), PartsListBox::Populate(), CompletedDesignsListBox::PopulateCore(), BuildDesignatorWnd::BuildSelector::PopulateList(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), ShipDesign::ProductionLocation(), ProductionWnd::QueueItemDuped(), ResearchWnd::QueueItemMoved(), ProductionWnd::QueueItemMoved(), EmptyHullsListBox::QueueItemMoved(), CompletedDesignsListBox::QueueItemMoved(), ResearchWnd::QueueItemPaused(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), TechManager::RecursivePrereqs(), ResearchWnd::Refresh(), ProductionWnd::Refresh(), BuildDesignatorWnd::BuildSelector::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), MapWnd::RefreshDetectionIndicator(), MapWnd::RefreshFleetResourceIndicator(), TechTreeArcs::Impl::RefreshHighlights(), EncyclopediaDetailPanel::RefreshImpl(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTradeResourceIndicator(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render(), MapWnd::RenderSystems(), BuildDesignatorWnd::SetBuild(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), BuildDesignatorWnd::BuildSelector::SetEmpireID(), ResourceInfoPanel::SetEmpireID(), Universe::SetEmpireKnowledgeOfDestroyedObject(), Universe::SetEmpireKnowledgeOfShipDesign(), BasesListBox::SetEmpireShown(), MapWnd::SetFleetMovementLine(), ResourceInfoPanel::SetLocalPointsCost(), MapWnd::SetProjectedFleetMovementLine(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), MapWnd::ShowProduction(), ShipDesignManager::StartGame(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchableByEmpire(), ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchedByEmpire(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), FleetWnd::TitleText(), BuildingsPanel::Update(), ResearchQueue::Update(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), ProductionQueue::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), MapWnd::UpdateEmpireResourcePools(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), ResearchWnd::UpdateInfoPanel(), ProductionWnd::UpdateInfoPanel(), ServerFSM::UpdateIngameLobby(), AIInterface::UpdateProductionQueue(), ResearchWnd::UpdateQueue(), ProductionWnd::UpdateQueue(), AIInterface::UpdateResearchQueue(), AIInterface::UpdateResourcePools(), FreeOrionPython::WrapServer(), ClientUI::ZoomToEmpire(), MapWnd::ZoomToHomeSystem(), and MapWnd::ZoomToSystemWithWastedPP().
GetEmpireClientType()
Networking::ClientType GetEmpireClientType (int empire_id) inline
References IApp::GetApp(), and IApp::GetEmpireClientType().
Referenced by Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()().
GetEmpireKnownBuilding()
std::shared_ptr<Building> GetEmpireKnownBuilding (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownField()
std::shared_ptr<Field> GetEmpireKnownField (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownFleet()
std::shared_ptr<Fleet> GetEmpireKnownFleet (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownObject()
std::shared_ptr<UniverseObject> GetEmpireKnownObject (int object_id, int empire_id) inline
References IApp::EmpireKnownObject(), and IApp::GetApp().
Referenced by CreateCombatDestroyedObjectSitRep(), and anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane().
GetEmpireKnownPlanet()
std::shared_ptr<Planet> GetEmpireKnownPlanet (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownPopCenter()
std::shared_ptr<PopCenter> GetEmpireKnownPopCenter (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownResourceCenter()
std::shared_ptr<ResourceCenter> GetEmpireKnownResourceCenter (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownShip()
std::shared_ptr<Ship> GetEmpireKnownShip (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
GetEmpireKnownSystem()
std::shared_ptr<System> GetEmpireKnownSystem (int object_id, int empire_id) inline
References IApp::EmpireKnownObjects(), IApp::GetApp(), and ObjectMap::Object().
Referenced by FleetMoveOrder::Check(), Fleet::Copy(), Universe::InitializeSystemGraph(), Pathfinder::PathfinderImpl::InitializeSystemGraph(), Fleet::MovePath(), anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::operator()(), anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::operator()(), and Pathfinder::PathfinderImpl::SystemHasVisibleStarlanes().
GetField()
std::shared_ptr<Field> GetField (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by MapWnd::DoFieldIconsLayout(), anonymous_namespace{UniverseWrapper.cpp}::GetFieldP(), MapWnd::InitFieldRenderingBuffers(), FieldIcon::RClick(), and FieldIcon::Refresh().
GetFleet()
std::shared_ptr<Fleet> GetFleet (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by FleetsListBox::AcceptDrops(), FleetWnd::AddFleet(), anonymous_namespace{SidePanel.cpp}::AvailableToBombard(), anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), FleetMoveOrder::Check(), FleetTransferOrder::Check(), ColonizeOrder::Check(), InvadeOrder::Check(), AggressiveOrder::Check(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), FleetWnd::ContainsFleet(), FleetWnd::ContainsFleets(), Ship::Copy(), CreateFleetArrivedAtDestinationSitRep(), MapWnd::CreateFleetButtonsOfType(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), MapWnd::DispatchFleetsExploring(), FleetWnd::DoLayout(), FleetsListBox::DragDropHere(), FleetDataPanel::DropsAcceptable(), FleetsListBox::DropsAcceptable(), ShipsListBox::DropsAcceptable(), Effect::SetOwner::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), AggressiveOrder::ExecuteImpl(), GiveObjectToEmpireOrder::ExecuteImpl(), FleetButton::FleetButton(), MapWnd::FleetButtonRightClicked(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{Pathfinder.cpp}::FleetFromObject(), MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetMoveOrder::FleetMoveOrder(), FleetWnd::FleetRightClicked(), FleetWnd::FleetWnd(), anonymous_namespace{ValueRef.cpp}::FollowReference(), anonymous_namespace{UniverseWrapper.cpp}::GetFleetP(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), CombatInfo::InitializeObjectVisibility(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), anonymous_namespace{MapWnd.cpp}::IssueExploringFleetOrders(), FleetButton::LayoutIcons(), Condition::Stationary::Match(), Condition::Aggressive::Match(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), MapWnd::PlotFleetMovement(), Universe::RecursiveDestroy(), FleetWnd::Refresh(), FleetDataPanel::Refresh(), ShipsListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), FleetWnd::RefreshStateChangedSignals(), FleetDataPanel::RefreshStateChangedSignals(), System::Remove(), FleetWnd::SelectFleet(), MapWnd::SelectFleet(), FleetDetailPanel::SetFleet(), MapWnd::SetFleetMovementLine(), MapWnd::SetProjectedFleetMovementLine(), FleetDataPanel::SetStatIconValues(), FleetDetailPanel::ShipRightClicked(), MapWnd::StopFleetExploring(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), FleetDataPanel::ToggleAggression(), anonymous_namespace{ValueRef.cpp}::TraceReference(), ColonizeOrder::UndoImpl(), InvadeOrder::UndoImpl(), BombardOrder::UndoImpl(), GiveObjectToEmpireOrder::UndoImpl(), FleetWnd::UniverseObjectDeleted(), MapWnd::MapScaleLine::Update(), FleetDataPanel::UpdateAggressionToggle(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), and ClientUI::ZoomToFleet().
GetGalaxySetupData()
const GalaxySetupData& GetGalaxySetupData () inline
Returns the galaxy setup settings used in the current game.
References IApp::GetApp(), and IApp::GetGalaxySetupData().
Referenced by ValueRef::Variable< ToType >::Eval(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), WaitingForGameStart::react(), and FreeOrionPython::WrapServer().
GetPathfinder()
std::shared_ptr<const Pathfinder> GetPathfinder () inline
Accessor for the App's universe object.
References IApp::GetApp(), Universe::GetPathfinder(), and IApp::GetUniverse().
Referenced by Fleet::CalculateRouteTo(), UniverseObject::Dump(), ValueRef::Variable< ToType >::Eval(), Condition::WithinStarlaneJumps::Eval(), ValueRef::ComplexVariable< T >::Eval(), FleetMoveOrder::FleetMoveOrder(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{ServerWrapper.cpp}::JumpDistanceBetweenSystems(), anonymous_namespace{ServerWrapper.cpp}::LinearDistance(), Condition::WithinStarlaneJumps::Match(), Fleet::MovementPhase(), MapWnd::PlotFleetMovement(), anonymous_namespace{Fleet.cpp}::SystemHasNoVisibleStarlanes(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), anonymous_namespace{ServerWrapper.cpp}::SystemsWithinJumps(), and anonymous_namespace{Effect.cpp}::UpdateFleetRoute().
GetPlanet()
std::shared_ptr<Planet> GetPlanet (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), Planet::CardinalSuffix(), ColonizeOrder::Check(), InvadeOrder::Check(), BombardOrder::Check(), ChangeFocusOrder::Check(), Empire::CheckProductionProgress(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), SidePanel::PlanetPanel::CompleteConstruction(), SidePanel::PlanetPanelContainer::DisableNonSelectionCandidates(), ServerApp::EliminatePlayer(), Effect::CreateBuilding::Execute(), Effect::MoveTo::Execute(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), ChangeFocusOrder::ExecuteImpl(), GiveObjectToEmpireOrder::ExecuteImpl(), anonymous_namespace{ValueRef.cpp}::FollowReference(), anonymous_namespace{UniverseWrapper.cpp}::GetPlanetP(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), Condition::Homeworld::Match(), Condition::PlanetType::Match(), Condition::PlanetSize::Match(), Condition::PlanetEnvironment::Match(), Condition::Species::Match(), Condition::FocusType::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), ObjectListWnd::ObjectRightClicked(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetSizeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::SpeciesSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ResourceSupplySimpleMatch::operator()(), System::Owner(), anonymous_namespace{ServerWrapper.cpp}::PlanetAvailableFoci(), anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix(), MapWnd::PlanetDoubleClicked(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetType(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeOutpost(), SidePanel::PlanetSelectable(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetType(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P(), SidePanel::PlanetPanel::RClick(), Universe::RecursiveDestroy(), SidePanel::PlanetPanel::Refresh(), RotatingPlanetControl::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), SetEmpireHomeworld(), SidePanel::PlanetPanel::SetFocus(), SidePanel::PlanetPanelContainer::SetPlanets(), anonymous_namespace{ValueRef.cpp}::TraceReference(), ColonizeOrder::UndoImpl(), InvadeOrder::UndoImpl(), BombardOrder::UndoImpl(), GiveObjectToEmpireOrder::UndoImpl(), BuildingsPanel::Update(), MapWnd::MapScaleLine::Update(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo(), Empire::UpdateSystemSupplyRanges(), ClientUI::ZoomToPlanet(), and ClientUI::ZoomToPlanetPedia().
GetPlayerClientType()
Networking::ClientType GetPlayerClientType (int player_id) inline
References IApp::GetApp(), and IApp::GetPlayerClientType().
GetPopCenter()
std::shared_ptr<PopCenter> GetPopCenter (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by MultiIconValueIndicator::CompleteConstruction(), MultiIconValueIndicator::EventFilter(), and PopulationPool::Update().
GetResourceCenter()
std::shared_ptr<ResourceCenter> GetResourceCenter (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by SidePanel::PlanetPanel::FocusDropListSelectionChangedSlot(), and ResourcePanel::GetResCenter().
GetShip()
std::shared_ptr<Ship> GetShip (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), NewFleetOrder::Check(), ColonizeOrder::Check(), InvadeOrder::Check(), BombardOrder::Check(), ScrapOrder::Check(), SidePanel::PlanetPanel::ClickColonize(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{FleetWnd.cpp}::ContainsArmedShips(), CreateFleetArrivedAtDestinationSitRep(), Fleet::Damage(), anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), FleetsListBox::DragDropHere(), FleetDataPanel::DropsAcceptable(), FleetsListBox::DropsAcceptable(), ShipsListBox::DropsAcceptable(), NewFleetOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), ScrapOrder::ExecuteImpl(), FleetButton::FleetButton(), FleetWnd::FleetRightClicked(), Fleet::GenerateFleetName(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{UniverseWrapper.cpp}::GetShipP(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), Fleet::MaxShipAgeInTurns(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), Universe::SetEmpireObjectVisibility(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies(), Fleet::Shields(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{FleetWnd.cpp}::ShipRow::ShipRow(), Fleet::Speed(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::StatValue(), Fleet::Structure(), ColonizeOrder::UndoImpl(), InvadeOrder::UndoImpl(), BombardOrder::UndoImpl(), ScrapOrder::UndoImpl(), MapWnd::MapScaleLine::Update(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), ShipDamageBrowseWnd::UpdateSummary(), ShipFightersBrowseWnd::UpdateSummary(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), and ClientUI::ZoomToShip().
GetSupplyManager()
SupplyManager& GetSupplyManager () inline
Accessor for the App's empire supply manager.
References IApp::GetApp(), and IApp::GetSupplyManager().
Referenced by anonymous_namespace{EmpireWrapper.cpp}::EmpireFleetSupplyableSystemIDsP(), ValueRef::Variable< ToType >::Eval(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireIntFloatMap(), anonymous_namespace{MapWnd.cpp}::GetNearestSupplyRoute(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), Empire::InitResourcePools(), anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemP(), Fleet::MovementPhase(), Fleet::MovePath(), anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesP(), Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ResourceSupplySimpleMatch::operator()(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), WaitingForGameStart::react(), WaitingForTurnData::react(), SidePanel::PlanetPanel::Refresh(), and MapWnd::RenderSystems().
GetSystem()
std::shared_ptr<System> GetSystem (int object_id) inline
References IApp::GetApp(), IApp::GetUniverse(), ObjectMap::Object(), and Universe::Objects().
Referenced by Empire::AddExploredSystem(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), Fleet::Blockaded(), Fleet::BlockadedAtSystem(), Fleet::CalculateRouteTo(), anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::CanAddStarlaneConnectionSimpleMatch(), Planet::CardinalSuffix(), NewFleetOrder::Check(), GiveObjectToEmpireOrder::Check(), Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), SystemIcon::CompleteConstruction(), Planet::Conquer(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Condition::InSystem::Description(), Condition::ObjectID::Description(), MapWnd::DispatchFleetsExploring(), anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), anonymous_namespace{Supply.cpp}::DistanceBetweenObjects(), MapWnd::DoFleetButtonsLayout(), SidePanel::DoLayout(), MapWnd::DoSystemIconsLayout(), SupplyManager::Dump(), UniverseObject::Dump(), ValueRef::Variable< ToType >::Eval(), Moderator::AddStarlane::Execute(), Moderator::RemoveStarlane::Execute(), Moderator::CreatePlanet::Execute(), Effect::SetOwner::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::AddStarlanes::Execute(), Effect::RemoveStarlanes::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), anonymous_namespace{ValueRef.cpp}::FollowReference(), anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation(), Condition::InSystem::GetDefaultInitialCandidateObjects(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{UniverseWrapper.cpp}::GetSystemP(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitSystemRenderingBuffers(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsOnStarlane(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), Condition::anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane(), FleetButton::LayoutIcons(), Pathfinder::PathfinderImpl::LinearDistance(), Condition::StarType::Match(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), Fleet::MovementPhase(), Fleet::MovePath(), Condition::anonymous_namespace{Condition.cpp}::StarTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), SidePanel::PlanetSelectable(), MapWnd::PlotFleetMovement(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), Empire::RecordPendingLaneUpdate(), Universe::RecursiveDestroy(), SystemIcon::Refresh(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), SidePanel::RefreshImpl(), SidePanel::RefreshInPreRender(), FleetWnd::RefreshStateChangedSignals(), MapWnd::RenderSystems(), BuildDesignatorWnd::SelectDefaultPlanet(), MapWnd::SelectSystem(), SetEmpireHomeworld(), CombatLogWnd::Impl::SetLog(), SidePanel::PlanetPanelContainer::SetPlanets(), SidePanel::SetSystem(), Pathfinder::PathfinderImpl::ShortestPathDistance(), anonymous_namespace{SidePanel.cpp}::SystemRow::SortKey(), anonymous_namespace{ServerWrapper.cpp}::SystemAddStarlane(), anonymous_namespace{ServerWrapper.cpp}::SystemFreeOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetFleets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetNumOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetPlanets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarlanes(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarType(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOccupied(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOfPlanet(), anonymous_namespace{ServerWrapper.cpp}::SystemRemoveStarlane(), MapWnd::SystemRightClicked(), anonymous_namespace{ServerWrapper.cpp}::SystemSetStarType(), FleetWnd::TitleText(), anonymous_namespace{ValueRef.cpp}::TraceReference(), SupplyManager::Update(), MapWnd::MapScaleLine::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), anonymous_namespace{Effect.cpp}::UpdateFleetRoute(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateProduction(), Empire::UpdateUnobstructedFleets(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToNextSystem(), MapWnd::ZoomToPrevOwnedSystem(), MapWnd::ZoomToPrevSystem(), and ClientUI::ZoomToSystem().
GetUniverse()
Universe& GetUniverse () inline
Accessor for the App's universe object.
References IApp::GetApp(), and IApp::GetUniverse().
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse(), Empire::AddShipDesign(), System::ApparentName(), AutomaticallyChosenColonyShip(), anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), BuildDesignatorWnd::CenterOnBuild(), ColonizeOrder::Check(), InvadeOrder::Check(), BombardOrder::Check(), Empire::CheckProductionProgress(), Ship::Clone(), Field::Clone(), Building::Clone(), Planet::Clone(), System::Clone(), Fleet::Clone(), FleetButton::CompleteConstruction(), MapWnd::CompleteConstruction(), FleetWnd::CompleteConstruction(), ObjectListBox::CompleteConstruction(), Planet::Conquer(), Field::Copy(), Building::Copy(), Ship::Copy(), Planet::Copy(), System::Copy(), Fleet::Copy(), ObjectMap::CopyObject(), MapWnd::CorrectMapPosition(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{ServerWrapper.cpp}::CreateSystem(), MapWnd::DeferredRefreshFleetButtons(), Delauney::DelauneyTriangulate(), MapWnd::DispatchFleetsExploring(), MapWnd::DoFleetButtonsLayout(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Moderator::DestroyUniverseObject::Execute(), Moderator::CreateSystem::Execute(), Moderator::CreatePlanet::Execute(), Effect::SetOwner::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), Effect::Destroy::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), Effect::SetDestination::Execute(), Effect::GenerateSitRepMessage::Execute(), Effect::SetVisibility::Execute(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ShipDesignOrder::ExecuteImpl(), ForgetOrder::ExecuteImpl(), ExtractGameStartMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnUpdateMessageData(), MessageWndEdit::FindGameWords(), MapWnd::FleetButtonRightClicked(), FleetDetailPanel::FleetDetailPanel(), MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetWnd::FleetRightClicked(), MapWnd::ForgetObject(), GameStartMessage(), GenerateStarlanes(), anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), Universe::GetObjectVisibilityByEmpire(), GetPredefinedShipDesign(), GetShipDesign(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), anonymous_namespace{ServerWrapper.cpp}::GetUniverseWidth(), UniverseObject::GetVisibility(), ServerFSM::HandleNonLobbyDisconnection(), MapWnd::InitFieldRenderingBuffers(), CombatInfo::InitializeObjectVisibility(), MapWnd::InitTurn(), MapWnd::InitTurnRendering(), MapWnd::InitVisibilityRadiiRenderingBuffers(), ObjectMap::InsertCore(), Empire::KnownStarlanes(), anonymous_namespace{ServerWrapper.cpp}::LoadFleetPlanList(), LoadGame(), anonymous_namespace{ServerWrapper.cpp}::LoadItemSpecList(), anonymous_namespace{ServerWrapper.cpp}::LoadMonsterFleetPlanList(), anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings(), MapWnd::MidTurnUpdate(), IDAllocator::NewID(), ObjectListBox::ObjectShown(), OwnerColoredSystemName::OwnerColoredSystemName(), CompletedDesignsListBox::PopulateCore(), MonstersListBox::PopulateCore(), AllDesignsListBox::PopulateCore(), BuildDesignatorWnd::BuildSelector::PopulateList(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), Ship::PublicName(), Fleet::PublicName(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), PlayingGame::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), WaitingForTurnEnd::react(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), RotatingPlanetControl::Refresh(), ObjectListBox::Refresh(), ShipsListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), MapWnd::RefreshFleetResourceIndicator(), EncyclopediaDetailPanel::RefreshImpl(), BuildingIndicator::Render(), MapWnd::RenderStarfields(), MapWnd::RenderSystems(), MapWnd::ReselectLastFleet(), CombatInfo::save(), SaveGame(), MapWnd::SelectSystem(), EmpireManager::serialize(), CombatLogManager::Impl::serialize(), SpeciesManager::serialize(), Empire::serialize(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireObjectVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), anonymous_namespace{ServerWrapper.cpp}::SetUniverseWidth(), anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), TurnPartialUpdateMessage(), TurnUpdateMessage(), FleetWnd::UniverseObjectDeleted(), BuildingsPanel::Update(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), anonymous_namespace{UniverseWrapper.cpp}::UpdateMetersWrapper(), ConditionWidget::UpdateParameterControls(), MapWnd::UpdateSidePanelSystemObjectMetersAndResourcePools(), Empire::UpdateSupplyUnobstructedSystems(), Empire::UpdateSystemSupplyRanges(), Empire::UpdateUnobstructedFleets(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), UniverseObject::VisibleContainedObjectIDs(), Empire::VisibleStarlanes(), System::VisibleStarlanesWormholes(), FreeOrionPython::WrapAI(), FreeOrionPython::WrapServer(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), ClientUI::ZoomToObject(), MapWnd::ZoomToPrevFleet(), and MapWnd::ZoomToPrevIdleFleet().
GetUniverseObject()
std::shared_ptr<UniverseObject> GetUniverseObject (int object_id) inline
Accessor for individual objects.
References IApp::GetApp(), and IApp::GetUniverseObject().
Referenced by Species::AddHomeworld(), ObjectListBox::AddObjectRow(), anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), Universe::ApplyEffectDerivedVisibilities(), Fleet::CalculateRouteTo(), MapWnd::CenterOnObject(), RenameOrder::Check(), ScrapOrder::Check(), GiveObjectToEmpireOrder::Check(), Empire::CheckProductionProgress(), InitialStealthEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), BuildingsPanel::CompleteConstruction(), MilitaryPanel::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), Universe::CountDestructionInStats(), CreateCombatDamagedObjectSitRep(), InitialStealthEvent::DebugString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), SupplyManager::Dump(), ClientUI::DumpObject(), SidePanel::PlanetPanel::EnableOrderIssuing(), Empire::EnqueuableItem(), anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), ProductionQueue::ProductionItem::EnqueueConditionPassedAt(), BuildingType::EnqueueLocation(), ValueRef::NameLookup::Eval(), ValueRef::ComplexVariable< T >::Eval(), Moderator::SetOwner::Execute(), Effect::EffectBase::Execute(), Universe::ExecuteEffects(), RenameOrder::ExecuteImpl(), anonymous_namespace{ServerWrapper.cpp}::FilterIDsWithCondition(), FleetButton::FleetButton(), MapWnd::ForgetObject(), anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation(), anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), anonymous_namespace{ServerWrapper.cpp}::GetName(), anonymous_namespace{ServerWrapper.cpp}::GetOwner(), MilitaryPanel::GetPlanet(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), anonymous_namespace{UniverseWrapper.cpp}::GetUniverseObjectP(), anonymous_namespace{ServerWrapper.cpp}::GetX(), anonymous_namespace{ServerWrapper.cpp}::GetY(), Special::InitialCapacity(), MeterBrowseWnd::Initialize(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), GraphicalSummaryWnd::MakeSummaries(), UniverseObject::MoveTo(), ObjectListWnd::ObjectRightClicked(), anonymous_namespace{ServerWrapper.cpp}::ObjectsGetSystems(), ObjectListBox::ObjectStateChanged(), PartsListBox::Populate(), Empire::ProducibleItem(), BuildingType::ProductionCost(), PartType::ProductionCost(), HullType::ProductionCost(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingType::ProductionLocation(), ShipDesign::ProductionLocation(), BuildingType::ProductionTime(), PartType::ProductionTime(), HullType::ProductionTime(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), BuildDesignatorWnd::BuildSelector::Refresh(), ObjectPanel::RefreshCache(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), ObjectPanel::RefreshLayout(), anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), Empire::SetCapitalID(), anonymous_namespace{ServerWrapper.cpp}::SetName(), Pathfinder::PathfinderImpl::ShortestPathDistance(), MapWnd::ShowProduction(), Empire::Source(), anonymous_namespace{VarText.cpp}::UniverseObjectString(), MultiMeterStatusBar::Update(), SpecialsPanel::Update(), MultiIconValueIndicator::Update(), MilitaryPanel::Update(), ResourcePanel::Update(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ProductionWnd::UpdateInfoPanel(), MeterBrowseWnd::UpdateSummary(), MapWnd::ZoomToHomeSystem(), and MapWnd::ZoomToSystemWithWastedPP().
GetVisibleObjectName()
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) inline
Returns the object name of the universe object.
This can be apperant object name, if the application isn't supposed to see the real object name.
References IApp::GetApp(), and IApp::GetVisibleObjectName().
Referenced by anonymous_namespace{VarText.cpp}::UniverseObjectString().
Objects()
ObjectMap& Objects () inline
Accessor for all (on server) or all known (on client) objects ObjectMap.
References IApp::GetApp(), IApp::GetUniverse(), and Universe::Objects().
Referenced by anonymous_namespace{Condition.cpp}::AddAllObjectsSet(), anonymous_namespace{Condition.cpp}::AddBuildingSet(), anonymous_namespace{Condition.cpp}::AddFieldSet(), anonymous_namespace{Condition.cpp}::AddFleetSet(), anonymous_namespace{Condition.cpp}::AddPlanetSet(), anonymous_namespace{Condition.cpp}::AddPopCenterSet(), anonymous_namespace{Condition.cpp}::AddResCenterSet(), anonymous_namespace{Condition.cpp}::AddShipSet(), anonymous_namespace{Condition.cpp}::AddSystemSet(), System::ApparentName(), anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), Fleet::BlockadedAtSystem(), anonymous_namespace{UniverseWrapper.cpp}::BuildingIDs(), FleetTransferOrder::Check(), GiveObjectToEmpireOrder::Check(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::CleanUpBombardmentStateInfo(), Planet::Colonize(), CombatInfo::CombatInfo(), Planet::Conquer(), anonymous_namespace{CombatLogWnd.cpp}::CountByOwner(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), ColorByOwner::Decorate(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), MapWnd::DeferredRefreshFleetButtons(), ServerApp::EliminatePlayer(), anonymous_namespace{ServerApp.cpp}::EmpireEliminated(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), FleetTransferOrder::ExecuteImpl(), anonymous_namespace{UniverseWrapper.cpp}::FieldIDs(), anonymous_namespace{UniverseWrapper.cpp}::FleetIDs(), FleetWnd::FleetRightClicked(), Fleet::Fuel(), GenerateStarlanes(), anonymous_namespace{Effect.cpp}::GenerateSystemName(), anonymous_namespace{ModeratorAction.cpp}::GenerateSystemName(), anonymous_namespace{ServerWrapper.cpp}::GetAllObjects(), Condition::InSystem::GetDefaultInitialCandidateObjects(), Condition::ObjectID::GetDefaultInitialCandidateObjects(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{MapWnd.cpp}::GetSystemNamesIDs(), anonymous_namespace{ServerWrapper.cpp}::GetSystems(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{Fleet.cpp}::HasXShips(), Empire::InitResourcePools(), MapWnd::InitTurn(), MapWnd::InitTurnRendering(), anonymous_namespace{Fleet.cpp}::InsertFleetWithShips(), Empire::KnownStarlanes(), Condition::anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane(), Condition::anonymous_namespace{Condition.cpp}::LaneTooCloseToOtherSystem(), Condition::ContainedBy::Match(), Fleet::MaxFuel(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), anonymous_namespace{Fleet.cpp}::MoveFleetWithShips(), Fleet::MovementPhase(), Pathfinder::PathfinderImpl::NearestSystemTo(), IDAllocator::NewID(), anonymous_namespace{UniverseWrapper.cpp}::ObjectIDs(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ParticipantBar::ParticipantBar(), anonymous_namespace{UniverseWrapper.cpp}::PlanetIDs(), SidePanel::PlanetPanel::RClick(), FleetWnd::Refresh(), FleetDataPanel::Refresh(), ObjectListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), MapWnd::RefreshFleetResourceIndicator(), MapWnd::RefreshFleetSignals(), SidePanel::RefreshImpl(), SidePanel::RefreshInPreRender(), MapWnd::RefreshPopulationIndicator(), FleetDataPanel::RefreshStateChangedSignals(), SidePanel::RefreshSystemNames(), MapWnd::RenderSystems(), Fleet::ResourceOutput(), BuildDesignatorWnd::SelectDefaultPlanet(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), Empire::SetCapitalID(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), anonymous_namespace{UniverseWrapper.cpp}::ShipIDs(), Empire::Source(), ProductionQueue::StockpileCapacity(), anonymous_namespace{UniverseWrapper.cpp}::SystemIDs(), MapWnd::SystemRightClicked(), ResourcePool::Update(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), Universe::UpdateEmpireObjectVisibilities(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), Empire::UpdateOwnedObjectCounters(), ConditionWidget::UpdateParameterControls(), SpeciesManager::UpdatePopulationCounter(), SystemResourceSummaryBrowseWnd::UpdateProduction(), anonymous_namespace{ServerApp.cpp}::UpdateResourceCenterFocusHistoryInfo(), Empire::UpdateSupplyUnobstructedSystems(), Empire::UpdateUnobstructedFleets(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), and ClientUI::ZoomToObject().
Variable Documentation
BEFORE_FIRST_TURN
FO_COMMON_API const int BEFORE_FIRST_TURN
returned by CurrentGameTurn if the galaxy is currently being set up
Referenced by EffectsProcessingThreads().
IMPOSSIBLY_LARGE_TURN
FO_COMMON_API const int IMPOSSIBLY_LARGE_TURN
a number that's almost assuredly larger than any real turn number that might come up
Referenced by Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), Condition::HasSpecial::Dump(), EffectsProcessingThreads(), Condition::Turn::Eval(), Condition::HasSpecial::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Turn::Match(), Condition::HasSpecial::Match(), Condition::CreatedOnTurn::Match(), and Condition::DesignHasPart::Match().
INVALID_GAME_TURN
FO_COMMON_API const int INVALID_GAME_TURN
returned by CurrentGameTurn if a game is not currently in progress or being set up.
Referenced by EffectsProcessingThreads().