FreeOrion: Building.cpp File Reference
Building.cpp File Reference
#include "Building.h"
#include "Condition.h"
#include "Effect.h"
#include "Planet.h"
#include "Predicates.h"
#include "Universe.h"
#include "Enums.h"
#include "ValueRef.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../util/OptionsDB.h"
#include "../util/Logger.h"
#include "../util/AppInterface.h"
#include "../util/GameRules.h"
#include "../util/CheckSums.h"
#include "../util/ScopedTimer.h"
#include "../util/i18n.h"
#include <boost/filesystem/fstream.hpp>
Namespaces
anonymous_namespace{Building.cpp}
Functions
void anonymous_namespace{Building.cpp}::AddRules (GameRules &rules)
const BuildingType * GetBuildingType (const std::string &name)
Returns the BuildingType specification object for a building of type name.
BuildingTypeManager & GetBuildingTypeManager ()
returns the singleton building type manager
Variables
bool anonymous_namespace{Building.cpp}::temp_bool = RegisterGameRules(&AddRules)
Function Documentation
GetBuildingType()
const BuildingType* GetBuildingType (const std::string & name)
Returns the BuildingType specification object for a building of type name.
If no such BuildingType exists, 0 is returned instead.
References BuildingTypeManager::GetBuildingType(), and GetBuildingTypeManager().
Referenced by Empire::AddBuildingType(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), Building::Building(), ClientUI::BuildingIcon(), BuildingIndicator::BuildingIndicator(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), Planet::Conquer(), Empire::ConquerProductionQueueItemsAtLocation(), ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), Empire::EnqueuableItem(), anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), ProductionQueue::ProductionItem::EnqueueConditionPassedAt(), Effect::CreateBuilding::Execute(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Building::HasTag(), anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings(), Empire::ProducibleItem(), Empire::ProductionCostAndTime(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingIndicator::RClick(), BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), BuildDesignatorWnd::SetBuild(), Building::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToBuildingType().
GetBuildingTypeManager()
BuildingTypeManager& GetBuildingTypeManager ()
returns the singleton building type manager
References BuildingTypeManager::GetBuildingTypeManager().
Referenced by CheckSumContent(), MessageWndEdit::FindGameWords(), GetBuildingType(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PythonAI::Initialize(), BuildDesignatorWnd::BuildSelector::PopulateList(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().