FreeOrion: Building.h File Reference
Building.h File Reference
#include "UniverseObject.h"
#include "ObjectMap.h"
#include "ShipDesign.h"
#include "../util/Export.h"
#include "../util/Pending.h"
#include <boost/algorithm/string/case_conv.hpp>
Classes
class Building
A Building UniverseObject type.
class BuildingType
A specification for a building of a certain type.
class BuildingTypeManager
Holds all FreeOrion building types.
struct ValueRef::ValueRef< T >
The base class for all ValueRef classes.
Namespaces
Condition
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Effect
ValueRef
Functions
FO_COMMON_API const BuildingType * GetBuildingType (const std::string &name)
Returns the BuildingType specification object for a building of type name.
FO_COMMON_API BuildingTypeManager & GetBuildingTypeManager ()
returns the singleton building type manager
Function Documentation
GetBuildingType()
FO_COMMON_API const BuildingType* GetBuildingType (const std::string & name)
Returns the BuildingType specification object for a building of type name.
If no such BuildingType exists, 0 is returned instead.
GetBuildingTypeManager()
FO_COMMON_API BuildingTypeManager& GetBuildingTypeManager ()
returns the singleton building type manager
References BuildingTypeManager::GetBuildingTypeManager().
Referenced by CheckSumContent(), MessageWndEdit::FindGameWords(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PythonAI::Initialize(), BuildDesignatorWnd::BuildSelector::PopulateList(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().