FreeOrion: BuildingType.h File Reference
BuildingType.h File Reference
#include "CommonParams.h"
#include "ScriptingContext.h"
#include "../util/AppInterface.h"
#include "../util/Enum.h"
#include "../util/Export.h"
#include "../util/Pending.h"
Classes
class BuildingTypeManager
Holds all FreeOrion BuildingTypes. Types may be looked up by name.
struct ValueRef::ValueRef< T >
The base class for all ValueRef classes returning type T.
Namespaces
Condition
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Effect
ValueRef
Functions
FO_ENUM ((CaptureResult),((INVALID_CAPTURE_RESULT, -1))((CR_CAPTURE))((CR_DESTROY))((CR_RETAIN))) class FO_COMMON_API BuildingType
Possible results of a Building being captured by other empires, or an Planet containing the Building being captured.
FO_COMMON_API auto GetBuildingType (const std::string &name) -> const BuildingType *
Returns the BuildingType specification object for a building of type name.
FO_COMMON_API auto GetBuildingTypeManager () -> BuildingTypeManager &
Returns the singleton building type manager.
Function Documentation
FO_ENUM()
FO_ENUM ((CaptureResult) , ((INVALID_CAPTURE_RESULT, -1))((CR_CAPTURE))((CR_DESTROY))((CR_RETAIN)))
Possible results of a Building being captured by other empires, or an Planet containing the Building being captured.
Class to specify a kind of building.
Each building type must have a unique name string, by which it can be looked up using GetBuildingType(...).
Returns the unique name for this type of building
Returns a text description of this type of building
Returns a data file format representation of this object
Returns true if the production cost and time are invariant (does not depend on) the location
Returns the number of production points required to build this building at this location by this empire
Returns the maximum number of production points per turn that can be spend on this building
Returns the number of turns required to build this building at this location by this empire
Returns the ValueRef that determines ProductionCost()
Returns the ValueRef that determines ProductionTime()
Returns whether this building type is producible by players and appears on the production screen
Returns the condition that determines the locations where this building can be produced
Returns a condition that can be used by the UI to further filter (beyond the Location() requirement) where this building will be presented for enqueuing onto the production queue, to avoid clutter in the BuildDesignatorWnd. Example usage: Buildings that are already enqueued at a production location are hidden so they don't appear in the list of available items that can be enqueued/produced (again) at that location.
Returns the EffectsGroups that encapsulate the effects that buildings of this type have when operational.
Returns the name of the grapic file for this building type
Returns true iff the empire with ID empire_id can produce this building at the location with location_id
Returns true iff the empire with ID empire_id meets the requirements of the EnqueueLocation() UI filter method for this building at the location with location_id
Returns CaptureResult for empire with ID to_empire_id capturing from empire with IDs from_empire_id the planet (or other UniverseObject) with id location_id on which this type of Building is located (if as_production_item is false) or which is the location of a Production Queue BuildItem for a building of this type (otherwise)
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function. Useful to verify that the parsed content is consistent without sending it all between clients and server.
References tag_parser::description, Effect::Dump(), Empires(), anonymous_namespace{XMLDoc.cpp}::Name, and Objects().
GetBuildingType()
FO_COMMON_API auto GetBuildingType (const std::string & name) -> const BuildingType *
Returns the BuildingType specification object for a building of type name.
If no such BuildingType exists, nullptr is returned instead.
GetBuildingTypeManager()
FO_COMMON_API auto GetBuildingTypeManager () -> BuildingTypeManager &
Returns the singleton building type manager.
References BuildingTypeManager::GetBuildingTypeManager().
Referenced by CheckSumContent(), MessageWndEdit::FindGameWords(), GetBuildingType(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PythonAI::Initialize(), BuildingTypeManager::NumBuildingTypes(), BuildDesignatorWnd::BuildSelector::PopulateList(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().