FreeOrion: BuildingType.cpp File Reference
BuildingType.cpp File Reference
#include "BuildingType.h"
#include <boost/algorithm/string/case_conv.hpp>
#include "../util/CheckSums.h"
#include "../util/GameRules.h"
#include "../util/Logger.h"
#include "../util/ScopedTimer.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "Condition.h"
#include "Effect.h"
#include "ValueRef.h"
Namespaces
anonymous_namespace{BuildingType.cpp}
Macros
#define UserStringNop(key) key
Functions
void anonymous_namespace{BuildingType.cpp}::AddRules (GameRules &rules)
const BuildingType * GetBuildingType (const std::string &name)
Returns the BuildingType specification object for a building of type name.
BuildingTypeManager & GetBuildingTypeManager ()
Returns the singleton building type manager.
Variables
bool anonymous_namespace{BuildingType.cpp}::temp_bool = RegisterGameRules(&AddRules)
Macro Definition Documentation
UserStringNop
#define UserStringNop (key) key
Referenced by anonymous_namespace{BuildingType.cpp}::AddRules().
Function Documentation
GetBuildingType()
const BuildingType* GetBuildingType (const std::string & name) -> const BuildingType *
Returns the BuildingType specification object for a building of type name.
If no such BuildingType exists, nullptr is returned instead.
References BuildingTypeManager::GetBuildingType(), and GetBuildingTypeManager().
Referenced by BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), Building::Building(), ClientUI::BuildingIcon(), BuildingIndicator::BuildingIndicator(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), Effect::CreateBuilding::Execute(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Building::HasTag(), anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings(), anonymous_namespace{Planet.cpp}::PlanetSizeIncrement(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingIndicator::RClick(), BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), BuildDesignatorWnd::SetBuild(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), Building::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToBuildingType().
GetBuildingTypeManager()
BuildingTypeManager& GetBuildingTypeManager ()
Returns the singleton building type manager.
References BuildingTypeManager::GetBuildingTypeManager().
Referenced by CheckSumContent(), MessageWndEdit::FindGameWords(), GetBuildingType(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PythonAI::Initialize(), BuildingTypeManager::NumBuildingTypes(), BuildDesignatorWnd::BuildSelector::PopulateList(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().