FreeOrion: camain.cpp File Reference
camain.cpp File Reference
#include "AIClientApp.h"
#include "../../parse/Parse.h"
#include "../../util/OptionsDB.h"
#include "../../util/Directories.h"
#include "../../util/Logger.h"
#include "../../util/Version.h"
#include <GG/utf8/checked.h>
#include <boost/filesystem/fstream.hpp>
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References DebugLogger, ErrorLogger, FreeOrionVersionString(), GetConfigPath(), GetOptionsDB(), GetPersistentConfigPath(), parse::init(), InitDirs(), and OptionsDB::SetFromFile().