FreeOrion: chmain.cpp File Reference
chmain.cpp File Reference
#include "HumanClientApp.h"
#include "../../util/OptionsDB.h"
#include "../../util/Directories.h"
#include "../../util/Logger.h"
#include "../../util/Version.h"
#include "../../util/i18n.h"
#include "../../UI/Hotkeys.h"
#include <GG/utf8/checked.h>
#include <boost/format.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/fstream.hpp>
#include <thread>
#include <chrono>
#include <iostream>
Functions
if (help_arg!="NOOP")
if (GetOptionsDB().Get< bool >("version"))
if (mainSetupAndRun()!=0)
int mainConfigOptionsSetup (const std::vector< std::string > &args)
int mainSetupAndRun ()
ShutdownLoggingSystemFileSink ()
Variables
const bool FAKE_MODE_CHANGE_FLAG = true
auto help_arg = GetOptionsDB().Get<std::string>("help")
return
const bool STORE_FULLSCREEN_FLAG = true
Function Documentation
if (help_arg! = "NOOP")
References GetOptionsDB(), OptionsDB::GetUsage(), help_arg, and ShutdownLoggingSystemFileSink().
Referenced by OptionsDB::AddSection(), anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), Empire::CheckProductionProgress(), Ship::Copy(), PoliciesListBox::DropsAcceptable(), PolicySlotControl::DropsAcceptable(), GovernmentWnd::MainPanel::DropsAcceptable(), PartsListBox::DropsAcceptable(), FleetsListBox::DropsAcceptable(), SlotControl::DropsAcceptable(), DesignWnd::MainPanel::DropsAcceptable(), ValueRef::Variable< T >::Eval(), SitRepPanel::GetNextNonEmptySitrepsTurn(), OptionsDB::GetUsage(), parse::detail::Labeller::operator()(), anonymous_namespace{DesignWnd.cpp}::PartALocationSubsumesPartB(), MPLobby::react(), ObjectListBox::Refresh(), and anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending().
if (GetOptionsDB().Get< bool >("version"))
References FreeOrionVersionString(), and ShutdownLoggingSystemFileSink().
if (mainSetupAndRun()! = 0)
References ShutdownLoggingSystemFileSink().
int mainConfigOptionsSetup (const std::vector< std::string > & args)
References OptionsDB::Add(), OptionsDB::AddFlag(), Hotkey::AddOptions(), OptionsDB::AddSection(), OptionsDB::Commit(), CompleteXDGMigration(), DebugLogger, FAKE_MODE_CHANGE_FLAG, FreeOrionVersionString(), GetConfigPath(), GetOptionsDB(), GetPersistentConfigPath(), GetResourceDir(), InitDirs(), PathToString(), OptionsDB::Set(), OptionsDB::SetFromCommandLine(), OptionsDB::SetFromFile(), STORE_FULLSCREEN_FLAG, UserString(), and UserStringNop.
Referenced by main().
int mainSetupAndRun ()
References HumanClientApp::AddWindowSizeOptionsAfterMainStart(), HumanClientApp::ContinueSinglePlayerGame(), DebugLogger, ErrorLogger, FreeOrionVersionString(), OptionsDB::Get(), GetOptionsDB(), HumanClientApp::GetWindowLeftTop(), HumanClientApp::GetWindowWidthHeight(), HumanClientApp::LoadSinglePlayerGame(), HumanClientApp::NewSinglePlayerGame(), and RegisterOptions().
Referenced by GUIController::applicationDidFinishLaunching:.
ShutdownLoggingSystemFileSink ()
Referenced by if(), and main().
Variable Documentation
const bool FAKE_MODE_CHANGE_FLAG = true
Referenced by mainConfigOptionsSetup().
auto help_arg = GetOptionsDB().Get<std::string>("help")
Referenced by if(), and main().
return
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT(), and anonymous_namespace{Logger.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT().
const bool STORE_FULLSCREEN_FLAG = true
Referenced by mainConfigOptionsSetup().