FreeOrion: chmain.h File Reference
chmain.h File Reference
#include <string>
#include <vector>
Functions
int mainConfigOptionsSetup (const std::vector< std::string > &args)
int mainSetupAndRun ()
Function Documentation
mainConfigOptionsSetup()
int mainConfigOptionsSetup (const std::vector< std::string > & args)
References OptionsDB::Add(), OptionsDB::AddFlag(), Hotkey::AddOptions(), OptionsDB::AddSection(), OptionsDB::Commit(), CompleteXDGMigration(), DebugLogger, FAKE_MODE_CHANGE_FLAG, FreeOrionVersionString(), GetConfigPath(), GetOptionsDB(), GetPersistentConfigPath(), GetResourceDir(), InitDirs(), PathToString(), OptionsDB::Set(), OptionsDB::SetFromCommandLine(), OptionsDB::SetFromFile(), STORE_FULLSCREEN_FLAG, UserString(), and UserStringNop.
Referenced by main().
mainSetupAndRun()
int mainSetupAndRun ()
References GGHumanClientApp::AddWindowSizeOptionsAfterMainStart(), GGHumanClientApp::ContinueSinglePlayerGame(), DebugLogger, ErrorLogger, FreeOrionVersionString(), OptionsDB::Get(), GetOptionsDB(), GGHumanClientApp::GetWindowLeftTop(), GGHumanClientApp::GetWindowWidthHeight(), GGHumanClientApp::LoadSinglePlayerGame(), GGHumanClientApp::NewSinglePlayerGame(), RegisterOptions(), and SDLGUI::Run().
Referenced by GUIController::applicationDidFinishLaunching:.