FreeOrion: chmain.mm File Reference
chmain.mm File Reference
#import <Cocoa/Cocoa.h>
#include "../../util/OptionsDB.h"
#include "../../util/Version.h"
#include "chmain.h"
#include <iostream>
Macros
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
Function Documentation
main()
int main (int argc, char * argv[])
References tag_parser::args, FreeOrionVersionString(), OptionsDB::Get(), GetOptionsDB(), OptionsDB::GetUsage(), help_arg, and mainConfigOptionsSetup().