FreeOrion: ShipPartManager Class Reference
ShipPartManager Class Reference
Holds FreeOrion available ShipParts.
#include <ShipPart.h>
Public Types
using iterator = ShipPartMap::const_iterator
using ShipPartMap = std::map< std::string, std::unique_ptr< ShipPart > >
Public Member Functions
auto begin () const -> iterator
Iterator to the first ShipPart.
auto end () const -> iterator
Iterator to one after the last ShipPart.
auto GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
auto GetShipPart (const std::string &name) const -> const ShipPart *
Returns the ShipPart with the name name; you should use the free function GetShipPart() instead.
FO_COMMON_API void SetShipParts (Pending::Pending< ShipPartMap > &&pending_ship_parts)
Sets part types to the future value of pending_ship_parts.
Static Public Member Functions
static auto GetShipPartManager () -> ShipPartManager &
Returns the instance of this singleton class; you should use the free function GetShipPartManager() instead.
Private Member Functions
ShipPartManager ()
void CheckPendingShipParts () const
Assigns any m_pending_ship_parts to m_parts.
Private Attributes
ShipPartMap m_parts
Map of ShipPart::Name to ShipParts.
boost::optional< Pending::Pending< ShipPartMap > > m_pending_ship_parts = boost::none
Future that provides all ShipParts after loaded by the parser.
Static Private Attributes
static ShipPartManager * s_instance = nullptr
Detailed Description
Holds FreeOrion available ShipParts.
Member Typedef Documentation
iterator
using ShipPartManager::iterator = ShipPartMap::const_iterator
ShipPartMap
using ShipPartManager::ShipPartMap = std::map<std::string, std::unique_ptr<ShipPart> >
Constructor & Destructor Documentation
ShipPartManager()
ShipPartManager::ShipPartManager () private
References s_instance.
Member Function Documentation
begin()
ShipPartManager::iterator ShipPartManager::begin () const -> iterator
Iterator to the first ShipPart.
References CheckPendingShipParts(), and m_parts.
CheckPendingShipParts()
void ShipPartManager::CheckPendingShipParts () const private
Assigns any m_pending_ship_parts to m_parts.
References m_parts, m_pending_ship_parts, Pending::SwapPending(), and TraceLogger.
Referenced by begin(), end(), GetCheckSum(), and GetShipPart().
end()
ShipPartManager::iterator ShipPartManager::end () const -> iterator
Iterator to one after the last ShipPart.
References CheckPendingShipParts(), and m_parts.
GetCheckSum()
unsigned int ShipPartManager::GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckPendingShipParts(), CheckSums::CheckSumCombine(), DebugLogger, and m_parts.
Referenced by CheckSumContent().
GetShipPart()
const ShipPart * ShipPartManager::GetShipPart (const std::string & name) const -> const ShipPart*
Returns the ShipPart with the name name; you should use the free function GetShipPart() instead.
References CheckPendingShipParts(), and m_parts.
Referenced by ShipDesign::Defense().
GetShipPartManager()
ShipPartManager & ShipPartManager::GetShipPartManager () -> ShipPartManager& static
Returns the instance of this singleton class; you should use the free function GetShipPartManager() instead.
Referenced by GetShipPart(), and GetShipPartManager().
SetShipParts()
void ShipPartManager::SetShipParts (Pending::Pending< ShipPartMap > && pending_ship_parts)
Sets part types to the future value of pending_ship_parts.
References m_pending_ship_parts.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_parts
ShipPartMap ShipPartManager::m_parts mutable private
Map of ShipPart::Name to ShipParts.
Referenced by begin(), CheckPendingShipParts(), end(), GetCheckSum(), and GetShipPart().
m_pending_ship_parts
boost::optional<Pending::Pending<ShipPartMap> > ShipPartManager::m_pending_ship_parts = boost::none mutable private
Future that provides all ShipParts after loaded by the parser.
Referenced by CheckPendingShipParts(), and SetShipParts().
s_instance
ShipPartManager * ShipPartManager::s_instance = nullptr static private
Referenced by anonymous_namespace{ShipPart.cpp}::IncreaseMeter(), and ShipPartManager().
The documentation for this class was generated from the following files:
ShipPart.h
ShipPart.cpp