FreeOrion: InvadeOrder Class Reference
InvadeOrder Class Reference
the Order subclass that represents a planet invasion action
#include <Order.h>
Public Member Functions
Structors
InvadeOrder (int empire, int ship, int planet)
Accessors
int PlanetID () const
Returns ID of the planet to be invaded.
int ShipID () const
Returns ID of the ship which is invading the planet.
Public Member Functions inherited from Order
void Execute () const
Executes the order on the Universe and Empires.
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Order ()
ctor taking the ID of the Empire issuing the order.
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
ctor taking the ID of the Empire issuing the order.
int EmpireID () const
Returns the ID of the Empire issuing the order.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
Static Public Member Functions
static bool Check (int empire_id, int ship_id, int planet_id)
Private Member Functions
InvadeOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
bool UndoImpl () const override
Private Attributes
int m_planet = INVALID_OBJECT_ID
int m_ship = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents a planet invasion action
Constructor & Destructor Documentation
InvadeOrder() [1/2]
InvadeOrder::InvadeOrder (int empire, int ship, int planet)
References Check().
InvadeOrder() [2/2]
InvadeOrder::InvadeOrder () private default
Member Function Documentation
Check()
bool InvadeOrder::Check (int empire_id, int ship_id, int planet_id) static
References Empires(), ErrorLogger, ObjectMap::get(), EmpireManager::GetDiplomaticStatus(), GetUniverse(), METER_POPULATION, METER_SHIELD, and Objects().
Referenced by ExecuteImpl(), and InvadeOrder().
ExecuteImpl()
void InvadeOrder::ExecuteImpl () const override private virtual
Preconditions:
m_planet must be the ID of a populated planet not owned by the issuing empire
m_ship must be the the ID of a ship owned by the issuing empire
m_ship must be the ID of a ship that can invade and that is in the same system as the planet.
Postconditions:
The ship with ID m_ship will be marked to invade the planet with id m_planet during the next turn processing.
Implements Order.
References Check(), DebugLogger, Order::EmpireID(), ObjectMap::get(), Order::GetValidatedEmpire(), m_planet, m_ship, UniverseObject::Name(), Objects(), and Ship::SetInvadePlanet().
PlanetID()
int InvadeOrder::PlanetID () const inline
Returns ID of the planet to be invaded.
serialize()
template<typename Archive > void InvadeOrder::serialize (Archive & ar, const unsigned int version) private
ShipID()
int InvadeOrder::ShipID () const inline
Returns ID of the ship which is invading the planet.
References Order::ExecuteImpl(), and Order::UndoImpl().
UndoImpl()
bool InvadeOrder::UndoImpl () const override private virtual
Reimplemented from Order.
References ErrorLogger, ObjectMap::get(), m_planet, m_ship, and Objects().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_planet
int InvadeOrder::m_planet = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
m_ship
int InvadeOrder::m_ship = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp