FreeOrion: Effect::SetDestination Class Reference
Effect::SetDestination Class Reference final
Sets the route of the target fleet to move to an UniverseObject that matches the condition location_condition.
#include <Effects.h>
Public Member Functions
SetDestination (std::unique_ptr< Condition::Condition > &&location_condition)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Private Attributes
std::unique_ptr< Condition::Condition > m_location_condition
Detailed Description
Sets the route of the target fleet to move to an UniverseObject that matches the condition location_condition.
If multiple objects match the condition, then one is chosen. If no objects match the condition, then nothing is done.
Constructor & Destructor Documentation
SetDestination()
Effect::SetDestination::SetDestination (std::unique_ptr< Condition::Condition > && location_condition) explicit
Member Function Documentation
Dump()
std::string Effect::SetDestination::Dump (unsigned short ntabs = 0) const override
References DumpIndent(), and m_location_condition.
Execute()
void Effect::SetDestination::Execute (ScriptingContext & context) const override
References ScriptingContext::effect_target, ErrorLogger, Fleet::ETA_NEVER, Fleet::ETA_OUT_OF_RANGE, Universe::GetPathfinder(), GetUniverse(), INVALID_OBJECT_ID, m_location_condition, and RandInt().
GetCheckSum()
unsigned int Effect::SetDestination::GetCheckSum () const override
References CheckSums::CheckSumCombine(), m_location_condition, and TraceLogger.
SetTopLevelContent()
void Effect::SetDestination::SetTopLevelContent (const std::string & content_name) override
References m_location_condition.
Member Data Documentation
m_location_condition
std::unique_ptr<Condition::Condition> Effect::SetDestination::m_location_condition private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp