FreeOrion: IntroScreen Class Reference
IntroScreen Class Reference
This is the first screen the user sees in FreeOrion.
#include <IntroScreen.h>
Public Member Functions
void CompleteConstruction () override
Structors
IntroScreen ()
~IntroScreen ()
Mutators
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void Render () override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void PreRender () override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnContinue ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnSinglePlayer ()
called when single player is clicked
void OnQuickStart ()
called when quick start is clicked
void OnMultiPlayer ()
...
void OnLoadGame ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnOptions ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnPedia ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnAbout ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnWebsite ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnCredits ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
void OnExitGame ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
virtual void Close ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
Private Attributes
std::shared_ptr< GG::Button > m_about
opens a dialog to choose to see credits or license
std::shared_ptr< GG::Button > m_continue
continues from last autosave
std::shared_ptr< GG::Button > m_credits
displays credits
std::shared_ptr< GG::Button > m_exit_game
button that exits the program
std::shared_ptr< GG::Button > m_load_game
loads a saved single player game
std::shared_ptr< GG::StaticGraphic > m_logo
std::shared_ptr< CUIWnd > m_menu
std::shared_ptr< GG::Button > m_multi_player
opens up the multi player game dialog
std::shared_ptr< GG::Button > m_options
opens the options dialog
std::shared_ptr< GG::Button > m_pedia
shows the pedia window
std::shared_ptr< GG::Button > m_quick_start
starts a single-player game with the default options (no dialog)
std::shared_ptr< GG::Button > m_single_player
opens up the single player game dialog
std::shared_ptr< GG::StaticGraphic > m_splash
std::shared_ptr< GG::Label > m_version
std::shared_ptr< GG::Button > m_website
opens web browser (or however system handles urls) to http://freeorion.org
Detailed Description
This is the first screen the user sees in FreeOrion.
It will always be the size of the Application main window. It will display a splash screen with a menu window on one side.
Constructor & Destructor Documentation
IntroScreen()
IntroScreen::IntroScreen ()
~IntroScreen()
IntroScreen::~IntroScreen ()
Member Function Documentation
Close()
void IntroScreen::Close () virtual
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References OnExitGame().
CompleteConstruction()
void IntroScreen::CompleteConstruction () override
References ClientUI::ArtDir(), FreeOrionVersionString(), HumanClientApp::GetApp(), ClientUI::GetTexture(), HumanClientApp::IsLoadGameAvailable(), m_about, m_continue, m_credits, m_exit_game, m_load_game, m_logo, m_menu, m_multi_player, m_options, m_pedia, m_quick_start, m_single_player, m_splash, m_version, m_website, anonymous_namespace{IntroScreen.cpp}::MAIN_MENU_HEIGHT(), anonymous_namespace{IntroScreen.cpp}::MAIN_MENU_WIDTH(), OnAbout(), OnContinue(), OnCredits(), OnExitGame(), OnLoadGame(), OnMultiPlayer(), OnOptions(), OnPedia(), OnQuickStart(), OnSinglePlayer(), OnWebsite(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, and UserString().
KeyPress()
void IntroScreen::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References OnExitGame().
OnAbout()
void IntroScreen::OnAbout ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
Referenced by CompleteConstruction().
OnContinue()
void IntroScreen::OnContinue ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References HumanClientApp::ContinueSinglePlayerGame(), and HumanClientApp::GetApp().
Referenced by CompleteConstruction().
OnCredits()
void IntroScreen::OnCredits ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References m_menu.
Referenced by CompleteConstruction().
OnExitGame()
void IntroScreen::OnExitGame ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
Referenced by Close(), CompleteConstruction(), and KeyPress().
OnLoadGame()
void IntroScreen::OnLoadGame ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References HumanClientApp::GetApp(), and HumanClientApp::LoadSinglePlayerGame().
Referenced by CompleteConstruction().
OnMultiPlayer()
void IntroScreen::OnMultiPlayer ()
...
References HumanClientApp::GetApp(), and HumanClientApp::MultiPlayerGame().
Referenced by CompleteConstruction().
OnOptions()
void IntroScreen::OnOptions ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
Referenced by CompleteConstruction().
OnPedia()
void IntroScreen::OnPedia ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References CLOSABLE, and PINABLE.
Referenced by CompleteConstruction().
OnQuickStart()
void IntroScreen::OnQuickStart ()
called when quick start is clicked
References HumanClientApp::GetApp(), and HumanClientApp::NewSinglePlayerGame().
Referenced by CompleteConstruction().
OnSinglePlayer()
void IntroScreen::OnSinglePlayer ()
called when single player is clicked
References HumanClientApp::GetApp(), and HumanClientApp::NewSinglePlayerGame().
Referenced by CompleteConstruction().
OnWebsite()
void IntroScreen::OnWebsite ()
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References HumanClientApp::GetApp(), and HumanClientApp::OpenURL().
Referenced by CompleteConstruction().
PreRender()
void IntroScreen::PreRender () override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
References OptionsDB::Get(), GetOptionsDB(), m_logo, m_menu, m_splash, and m_version.
Render()
void IntroScreen::Render () override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
SizeMove()
void IntroScreen::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Note: Since there is poor filesystem tracking of deleted savegames, use RequirePreRender() to force an update of the conditional placement of the Continue and Load buttons when a player might have deleted the last savegame.
Member Data Documentation
m_about
std::shared_ptr<GG::Button> IntroScreen::m_about private
opens a dialog to choose to see credits or license
Referenced by CompleteConstruction().
m_continue
std::shared_ptr<GG::Button> IntroScreen::m_continue private
continues from last autosave
Referenced by CompleteConstruction().
m_credits
std::shared_ptr<GG::Button> IntroScreen::m_credits private
displays credits
Referenced by CompleteConstruction().
m_exit_game
std::shared_ptr<GG::Button> IntroScreen::m_exit_game private
button that exits the program
Referenced by CompleteConstruction().
m_load_game
std::shared_ptr<GG::Button> IntroScreen::m_load_game private
loads a saved single player game
Referenced by CompleteConstruction().
m_logo
std::shared_ptr<GG::StaticGraphic> IntroScreen::m_logo private
Referenced by CompleteConstruction(), and PreRender().
m_menu
std::shared_ptr<CUIWnd> IntroScreen::m_menu private
Referenced by CompleteConstruction(), OnCredits(), and PreRender().
m_multi_player
std::shared_ptr<GG::Button> IntroScreen::m_multi_player private
opens up the multi player game dialog
Referenced by CompleteConstruction().
m_options
std::shared_ptr<GG::Button> IntroScreen::m_options private
opens the options dialog
Referenced by CompleteConstruction().
m_pedia
std::shared_ptr<GG::Button> IntroScreen::m_pedia private
shows the pedia window
Referenced by CompleteConstruction().
m_quick_start
std::shared_ptr<GG::Button> IntroScreen::m_quick_start private
starts a single-player game with the default options (no dialog)
Referenced by CompleteConstruction().
m_single_player
std::shared_ptr<GG::Button> IntroScreen::m_single_player private
opens up the single player game dialog
Referenced by CompleteConstruction().
m_splash
std::shared_ptr<GG::StaticGraphic> IntroScreen::m_splash private
Referenced by CompleteConstruction(), and PreRender().
m_version
std::shared_ptr<GG::Label> IntroScreen::m_version private
Referenced by CompleteConstruction(), and PreRender().
m_website
std::shared_ptr<GG::Button> IntroScreen::m_website private
opens web browser (or however system handles urls) to http://freeorion.org
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
IntroScreen.h
IntroScreen.cpp