FreeOrion: TechTreeLayout::Column Class Reference
TechTreeLayout::Column Class Reference
#include <TechTreeLayout.h>
Public Member Functions
auto ClosestFreeIndex (int index, TechTreeLayout::Node *node) -> int
auto Fit (int index, TechTreeLayout::Node *node) -> bool
auto Place (int index, TechTreeLayout::Node *node) -> bool
Public Attributes
std::vector< TechTreeLayout::Node * > column
Member Function Documentation
ClosestFreeIndex()
int TechTreeLayout::Column::ClosestFreeIndex (int index, TechTreeLayout::Node * node) -> int
Referenced by TechTreeLayout::Node::Wobble().
Fit()
bool TechTreeLayout::Column::Fit (int index, TechTreeLayout::Node * node) -> bool
References TechTreeLayout::Node::weight.
Referenced by TechTreeLayout::Node::Wobble().
Place()
bool TechTreeLayout::Column::Place (int index, TechTreeLayout::Node * node) -> bool
References TechTreeLayout::Node::row, and TechTreeLayout::Node::weight.
Referenced by TechTreeLayout::Node::Wobble().
Member Data Documentation
column
std::vector<TechTreeLayout::Node*> TechTreeLayout::Column::column
Referenced by TechTreeLayout::Node::Wobble().
The documentation for this class was generated from the following files:
TechTreeLayout.h
TechTreeLayout.cpp