FreeOrion: SitRepPanel Class Reference
SitRepPanel Class Reference
#include <SitRepPanel.h>
Public Member Functions
Structors
SitRepPanel (const std::string &config_name="")
void CompleteConstruction () override
Accessors
std::set< std::string > HiddenSitRepTemplates () const
int NumVisibleSitrepsThisTurn () const
Mutators
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
loads all the relevant SitReps into the window
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
loads all the relevant SitReps into the window
void Update ()
loads all the relevant SitReps into the window
void ShowSitRepsForTurn (int turn)
loads all the relevant SitReps into the window
void SetHiddenSitRepTemplates (const std::set< std::string > &templates)
loads all the relevant SitReps into the window
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Flash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void StopFlash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetFlashDuration (int ms)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void()> ClosingSignal
Private Member Functions
void CloseClicked () override
called when window is closed via the close button
void DismissalMenu (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &mod)
void DoLayout ()
void FilterClicked ()
int GetNextNonEmptySitrepsTurn (std::map< int, std::list< SitRepEntry >> &turns, int turn, bool forward) const
Search forward from turn for the next turn with valid sitreps.
void IgnoreSitRep (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &mod)
bool IsSitRepInvalid (SitRepEntry &sitrep) const
Return true if the sitrep is not hidden, validates and is not snoozed.
void LastClicked ()
void NextClicked ()
void PrevClicked ()
Private Attributes
std::shared_ptr< GG::Button > m_filter_button = nullptr
std::set< std::string > m_hidden_sitrep_templates
std::shared_ptr< GG::Button > m_last_turn_button = nullptr
std::shared_ptr< GG::Button > m_next_turn_button = nullptr
std::shared_ptr< GG::Button > m_prev_turn_button = nullptr
int m_showing_turn
std::shared_ptr< GG::ListBox > m_sitreps_lb = nullptr
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Constructor & Destructor Documentation
SitRepPanel()
SitRepPanel::SitRepPanel (const std::string & config_name = "")
Member Function Documentation
CloseClicked()
void SitRepPanel::CloseClicked () override private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal.
Referenced by KeyPress().
CompleteConstruction()
void SitRepPanel::CompleteConstruction () override
References CUIWnd::CompleteConstruction(), DismissalMenu(), DoLayout(), FilterClicked(), IgnoreSitRep(), LastClicked(), m_filter_button, m_last_turn_button, m_next_turn_button, m_prev_turn_button, m_sitreps_lb, NextClicked(), PrevClicked(), ClientUI::Pts(), and UserString().
DismissalMenu()
void SitRepPanel::DismissalMenu (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & mod) private
References FlexibleFormat(), ClientUI::GetClientUI(), SitRepEntry::GetLabelString(), VarText::GetStringtableLookupFlag(), VarText::GetText(), SitRepEntry::GetTurn(), m_hidden_sitrep_templates, m_sitreps_lb, anonymous_namespace{SitRepPanel.cpp}::permanently_snoozed_sitreps, anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), anonymous_namespace{SitRepPanel.cpp}::snoozed_sitreps, anonymous_namespace{SitRepPanel.cpp}::SnoozeSitRepForNTurns(), Update(), UserString(), and ClientUI::ZoomToEncyclopediaEntry().
Referenced by CompleteConstruction().
DoLayout()
void SitRepPanel::DoLayout () private
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_filter_button, m_last_turn_button, m_next_turn_button, m_prev_turn_button, m_sitreps_lb, anonymous_namespace{FleetWnd.cpp}::PAD, and ClientUI::Pts().
Referenced by CompleteConstruction(), and SizeMove().
FilterClicked()
void SitRepPanel::FilterClicked () private
References anonymous_namespace{SitRepPanel.cpp}::AllSitRepTemplateStrings(), anonymous_namespace{SitRepPanel.cpp}::label_display_map, m_filter_button, m_hidden_sitrep_templates, anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), Update(), and UserString().
Referenced by CompleteConstruction().
GetNextNonEmptySitrepsTurn()
int SitRepPanel::GetNextNonEmptySitrepsTurn (std::map< int, std::list< SitRepEntry >> & turns, int turn, bool forward) const private
Search forward from turn for the next turn with valid sitreps.
Remove turns from turns that have all invalid or otherwise filtered out sitreps.
References if(), INVALID_GAME_TURN, and IsSitRepInvalid().
Referenced by NextClicked(), PrevClicked(), and Update().
HiddenSitRepTemplates()
std::set<std::string> SitRepPanel::HiddenSitRepTemplates () const inline
References KeyPress(), m_hidden_sitrep_templates, NumVisibleSitrepsThisTurn(), SetHiddenSitRepTemplates(), ShowSitRepsForTurn(), SizeMove(), and Update().
IgnoreSitRep()
void SitRepPanel::IgnoreSitRep (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & mod) private
References VarText::GetText(), SitRepEntry::GetTurn(), anonymous_namespace{SitRepPanel.cpp}::snoozed_sitreps, and Update().
Referenced by CompleteConstruction().
IsSitRepInvalid()
bool SitRepPanel::IsSitRepInvalid (SitRepEntry & sitrep) const private
Return true if the sitrep is not hidden, validates and is not snoozed.
References OptionsDB::Get(), SitRepEntry::GetLabelString(), GetOptionsDB(), VarText::GetTemplateString(), VarText::GetText(), SitRepEntry::GetTurn(), m_hidden_sitrep_templates, anonymous_namespace{SitRepPanel.cpp}::permanently_snoozed_sitreps, anonymous_namespace{SitRepPanel.cpp}::snoozed_sitreps, and VarText::Validate().
Referenced by GetNextNonEmptySitrepsTurn(), and NumVisibleSitrepsThisTurn().
KeyPress()
void SitRepPanel::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
loads all the relevant SitReps into the window
References CloseClicked().
Referenced by HiddenSitRepTemplates().
LastClicked()
void SitRepPanel::LastClicked () private
References CurrentTurn(), and ShowSitRepsForTurn().
Referenced by CompleteConstruction().
NextClicked()
void SitRepPanel::NextClicked () private
References AIInterface::EmpireID(), HumanClientApp::GetApp(), GetNextNonEmptySitrepsTurn(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), m_showing_turn, and ShowSitRepsForTurn().
Referenced by CompleteConstruction().
NumVisibleSitrepsThisTurn()
int SitRepPanel::NumVisibleSitrepsThisTurn () const
References CurrentTurn(), AIInterface::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), and IsSitRepInvalid().
Referenced by HiddenSitRepTemplates().
PrevClicked()
void SitRepPanel::PrevClicked () private
References AIInterface::EmpireID(), HumanClientApp::GetApp(), GetNextNonEmptySitrepsTurn(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), m_showing_turn, and ShowSitRepsForTurn().
Referenced by CompleteConstruction().
SetHiddenSitRepTemplates()
void SitRepPanel::SetHiddenSitRepTemplates (const std::set< std::string > & templates)
loads all the relevant SitReps into the window
References m_hidden_sitrep_templates, and Update().
Referenced by HiddenSitRepTemplates().
ShowSitRepsForTurn()
void SitRepPanel::ShowSitRepsForTurn (int turn)
loads all the relevant SitReps into the window
References m_showing_turn, m_sitreps_lb, and Update().
Referenced by HiddenSitRepTemplates(), LastClicked(), NextClicked(), and PrevClicked().
SizeMove()
void SitRepPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
loads all the relevant SitReps into the window
References DoLayout(), m_sitreps_lb, and CUIWnd::SizeMove().
Referenced by HiddenSitRepTemplates().
Update()
void SitRepPanel::Update ()
loads all the relevant SitReps into the window
References DebugLogger, AIInterface::EmpireID(), FlexibleFormat(), HumanClientApp::GetApp(), GetNextNonEmptySitrepsTurn(), anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn(), INVALID_GAME_TURN, m_last_turn_button, m_next_turn_button, m_prev_turn_button, m_showing_turn, m_sitreps_lb, anonymous_namespace{SitRepPanel.cpp}::OrderedSitrepTemplateStrings(), ClientUI::Pts(), anonymous_namespace{ServerWrapper.cpp}::SetName(), and UserString().
Referenced by DismissalMenu(), FilterClicked(), HiddenSitRepTemplates(), IgnoreSitRep(), SetHiddenSitRepTemplates(), and ShowSitRepsForTurn().
Member Data Documentation
ClosingSignal
boost::signals2::signal<void ()> SitRepPanel::ClosingSignal mutable
Referenced by CloseClicked().
m_filter_button
std::shared_ptr<GG::Button> SitRepPanel::m_filter_button = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and FilterClicked().
m_hidden_sitrep_templates
std::set<std::string> SitRepPanel::m_hidden_sitrep_templates private
Referenced by DismissalMenu(), FilterClicked(), HiddenSitRepTemplates(), IsSitRepInvalid(), and SetHiddenSitRepTemplates().
m_last_turn_button
std::shared_ptr<GG::Button> SitRepPanel::m_last_turn_button = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_next_turn_button
std::shared_ptr<GG::Button> SitRepPanel::m_next_turn_button = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_prev_turn_button
std::shared_ptr<GG::Button> SitRepPanel::m_prev_turn_button = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_showing_turn
int SitRepPanel::m_showing_turn private
Referenced by NextClicked(), PrevClicked(), ShowSitRepsForTurn(), and Update().
m_sitreps_lb
std::shared_ptr<GG::ListBox> SitRepPanel::m_sitreps_lb = nullptr private
Referenced by CompleteConstruction(), DismissalMenu(), DoLayout(), ShowSitRepsForTurn(), SizeMove(), and Update().
The documentation for this class was generated from the following files:
SitRepPanel.h
SitRepPanel.cpp