FreeOrion: OptionsWnd Class Reference
OptionsWnd Class Reference
This is a dialog box that allows the user to control certain basic game parameters, such as sound and music.
#include <OptionsWnd.h>
Classes
class SoundOptionsFeedback
SoundOptionsFeedback enables immediate player feedback when sound options are changed.
Public Member Functions
Structors
OptionsWnd (bool is_game_running_)
~OptionsWnd ()
void CompleteConstruction () override
Mutators
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Flash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void StopFlash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetFlashDuration (int ms)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Private Member Functions
GG::StateButton * BoolOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
void ColorOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
GG::ListBox * CreatePage (const std::string &name)
void CreateSectionHeader (GG::ListBox *page, int indentation_level, const std::string &name, const std::string &tooltip="")
void DirectoryOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text, const boost::filesystem::path &path, bool disabled=false)
void DoLayout ()
void DoneClicked ()
GG::Spin< double > * DoubleOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
void FileOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text, const boost::filesystem::path &path, std::function< bool(const std::string &)> string_validator=nullptr)
void FileOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text, const boost::filesystem::path &path, const std::pair< std::string, std::string > &filter, std::function< bool(const std::string &)> string_validator=nullptr)
void FileOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text, const boost::filesystem::path &path, const std::vector< std::pair< std::string, std::string >> &filters, std::function< bool(const std::string &)> string_validator=nullptr)
void FileOptionImpl (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text, const boost::filesystem::path &path, const std::vector< std::pair< std::string, std::string >> &filters, std::function< bool(const std::string &)> string_validator, bool directory, bool relative_path, bool disabled)
void FontOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
void HotkeyOption (GG::ListBox *page, int indentation_level, const std::string &hotkey_name)
void HotkeysPage ()
GG::Spin< int > * IntOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
void MusicVolumeOption (GG::ListBox *page, int indentation_level, SoundOptionsFeedback &fb)
void ResolutionOption (GG::ListBox *page, int indentation_level)
void SoundFileOption (GG::ListBox *page, int indentation_level, const std::string &option_name, const std::string &text)
void VolumeOption (GG::ListBox *page, int indentation_level, const std::string &toggle_option_name, const std::string &volume_option_name, const std::string &text, bool toggle_value, SoundOptionsFeedback &fb)
Private Attributes
bool is_game_running
std::shared_ptr< GG::Button > m_done_button
SoundOptionsFeedback m_sound_feedback
std::shared_ptr< GG::TabWnd > m_tabs
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable = false
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable = false
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button
the pin button
bool m_pinable = false
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable = false
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 15
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 9
static const int RESIZE_HASHMARK2_OFFSET = 4
static const int TITLE_OFFSET = 2
Detailed Description
This is a dialog box that allows the user to control certain basic game parameters, such as sound and music.
Constructor & Destructor Documentation
OptionsWnd()
OptionsWnd::OptionsWnd (bool is_game_running_)
GetRootDataDir() returns the default browse path when modifying this directory option. The actual default directory (before modifying) is gotten from the specified option name "resource.path"
~OptionsWnd()
OptionsWnd::~OptionsWnd ()
GetRootDataDir() returns the default browse path when modifying this directory option. The actual default directory (before modifying) is gotten from the specified option name "resource.path"
Member Function Documentation
BoolOption()
GG::StateButton * OptionsWnd::BoolOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References GetOptionsDB(), anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN, anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), and UserString().
Referenced by CompleteConstruction(), and ResolutionOption().
CalculatePosition()
GG::Rect OptionsWnd::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), anonymous_namespace{OptionsWnd.cpp}::PAGE_HEIGHT(), and anonymous_namespace{OptionsWnd.cpp}::PAGE_WIDTH().
ColorOption()
void OptionsWnd::ColorOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References anonymous_namespace{OptionsWnd.cpp}::COLOR_SELECTOR_WIDTH(), OptionsDB::Get(), OptionsDB::GetDefault(), GetOptionsDB(), ClientUI::Pts(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), and UserString().
Referenced by CompleteConstruction().
CompleteConstruction()
void OptionsWnd::CompleteConstruction () override
GetRootDataDir() returns the default browse path when modifying this directory option. The actual default directory (before modifying) is gotten from the specified option name "resource.path"
References BoolOption(), ColorOption(), CUIWnd::CompleteConstruction(), CreatePage(), CreateSectionHeader(), DirectoryOption(), DoLayout(), DoneClicked(), DoubleOption(), exec, FileOption(), FlexibleFormat(), FlushLoadedStringTables(), FontOption(), OptionsDB::Get(), HumanClientApp::GetApp(), ClientUI::GetFont(), GetOptionsDB(), GetRootDataDir(), GetUserDataDir(), OptionsDB::GetValueString(), HotkeysPage(), IntOption(), is_game_running, anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN, anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), m_done_button, m_sound_feedback, m_tabs, ClientUI::MessageBox(), anonymous_namespace{OptionsWnd.cpp}::MUSIC_FILE_SUFFIX, MusicVolumeOption(), named, anonymous_namespace{OptionsWnd.cpp}::PAGE_HEIGHT(), anonymous_namespace{OptionsWnd.cpp}::PAGE_WIDTH(), CUIWnd::ResetDefaultPosition(), ResolutionOption(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), CUIWnd::SaveDefaultedOptions(), CUIWnd::SaveOptions(), anonymous_namespace{OptionsWnd.cpp}::ShowFontTextureWnd(), ClientUI::SoundDir(), SoundFileOption(), anonymous_namespace{OptionsWnd.cpp}::STRINGTABLE_FILE_SUFFIX, ClientUI::TextColor(), to_string(), UserString(), anonymous_namespace{OptionsWnd.cpp}::ValidMusicFile(), anonymous_namespace{OptionsWnd.cpp}::ValidStringtableFile(), VolumeOption(), and ClientUI::WndColor().
CreatePage()
GG::ListBox * OptionsWnd::CreatePage (const std::string & name) private
References m_tabs.
Referenced by CompleteConstruction(), and HotkeysPage().
CreateSectionHeader()
void OptionsWnd::CreateSectionHeader (GG::ListBox * page, int indentation_level, const std::string & name, const std::string & tooltip = "") private
References ClientUI::GetFont(), GetOptionsDB(), anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN, ClientUI::Pts(), and anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH().
Referenced by CompleteConstruction(), and HotkeysPage().
DirectoryOption()
void OptionsWnd::DirectoryOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text, const boost::filesystem::path & path, bool disabled = false) private
References FileOptionImpl(), and anonymous_namespace{OptionsWnd.cpp}::ValidDirectory().
Referenced by CompleteConstruction().
DoLayout()
void OptionsWnd::DoLayout () private
References CUIWnd::ClientLowerRight(), ClientUI::GetFont(), anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN, m_done_button, and m_tabs.
Referenced by CompleteConstruction(), and SizeMove().
DoneClicked()
void OptionsWnd::DoneClicked () private
References OptionsDB::Commit(), and GetOptionsDB().
Referenced by CompleteConstruction(), and KeyPress().
DoubleOption()
GG::Spin< double > * OptionsWnd::DoubleOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References ErrorLogger, OptionsDB::Get(), GetOptionsDB(), OptionsDB::GetValidator(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), anonymous_namespace{OptionsWnd.cpp}::SPIN_WIDTH(), and UserString().
Referenced by CompleteConstruction(), and ResolutionOption().
FileOption() [1/3]
void OptionsWnd::FileOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text, const boost::filesystem::path & path, std::function< bool(const std::string &)> string_validator = nullptr) private
Referenced by CompleteConstruction(), FileOption(), FontOption(), and SoundFileOption().
FileOption() [2/3]
void OptionsWnd::FileOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text, const boost::filesystem::path & path, const std::pair< std::string, std::string > & filter, std::function< bool(const std::string &)> string_validator = nullptr) private
References FileOption().
FileOption() [3/3]
void OptionsWnd::FileOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text, const boost::filesystem::path & path, const std::vector< std::pair< std::string, std::string >> & filters, std::function< bool(const std::string &)> string_validator = nullptr) private
References FileOptionImpl().
FileOptionImpl()
void OptionsWnd::FileOptionImpl (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text, const boost::filesystem::path & path, const std::vector< std::pair< std::string, std::string >> & filters, std::function< bool(const std::string &)> string_validator, bool directory, bool relative_path, bool disabled) private
References OptionsDB::Get(), GetOptionsDB(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), anonymous_namespace{OptionsWnd.cpp}::SPIN_WIDTH(), ClientUI::TextColor(), and UserString().
Referenced by DirectoryOption(), and FileOption().
FontOption()
void OptionsWnd::FontOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References FileOption(), anonymous_namespace{OptionsWnd.cpp}::FONT_FILE_SUFFIX, GetRootDataDir(), and anonymous_namespace{OptionsWnd.cpp}::ValidFontFile().
Referenced by CompleteConstruction().
HotkeyOption()
void OptionsWnd::HotkeyOption (GG::ListBox * page, int indentation_level, const std::string & hotkey_name) private
References Hotkey::GetDescription(), anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption(), anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption(), Hotkey::NamedHotkey(), Hotkey::PrettyPrint(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), and UserString().
Referenced by HotkeysPage().
HotkeysPage()
void OptionsWnd::HotkeysPage () private
References CreatePage(), CreateSectionHeader(), HotkeyOption(), anonymous_namespace{OptionsWnd.cpp}::HotkeysBySection(), m_tabs, and UserString().
Referenced by CompleteConstruction().
IntOption()
GG::Spin< int > * OptionsWnd::IntOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References ErrorLogger, OptionsDB::Get(), GetOptionsDB(), OptionsDB::GetValidator(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), anonymous_namespace{OptionsWnd.cpp}::SPIN_WIDTH(), and UserString().
Referenced by CompleteConstruction(), and ResolutionOption().
KeyPress()
void OptionsWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References DoneClicked().
MusicVolumeOption()
void OptionsWnd::MusicVolumeOption (GG::ListBox * page, int indentation_level, SoundOptionsFeedback & fb) private
References GetOptionsDB(), OptionsDB::GetValidator(), OptionsWnd::SoundOptionsFeedback::MusicClicked(), OptionsWnd::SoundOptionsFeedback::MusicVolumeSlid(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsWnd::SoundOptionsFeedback::SetMusicButton(), and UserString().
Referenced by CompleteConstruction().
ResolutionOption()
void OptionsWnd::ResolutionOption (GG::ListBox * page, int indentation_level) private
References BoolOption(), DoubleOption(), OptionsDB::Get(), HumanClientApp::GetApp(), SDLGUI::GetGUI(), GetOptionsDB(), OptionsDB::GetValidator(), IntOption(), anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN, ClientUI::Pts(), HumanClientApp::Reinitialize(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsDB::Set(), and UserString().
Referenced by CompleteConstruction().
SizeMove()
void OptionsWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
SoundFileOption()
void OptionsWnd::SoundFileOption (GG::ListBox * page, int indentation_level, const std::string & option_name, const std::string & text) private
References FileOption(), anonymous_namespace{OptionsWnd.cpp}::SOUND_FILE_SUFFIX, ClientUI::SoundDir(), UserString(), and anonymous_namespace{OptionsWnd.cpp}::ValidSoundFile().
Referenced by CompleteConstruction().
VolumeOption()
void OptionsWnd::VolumeOption (GG::ListBox * page, int indentation_level, const std::string & toggle_option_name, const std::string & volume_option_name, const std::string & text, bool toggle_value, SoundOptionsFeedback & fb) private
References GetOptionsDB(), OptionsDB::GetValidator(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), OptionsWnd::SoundOptionsFeedback::SetEffectsButton(), OptionsWnd::SoundOptionsFeedback::SoundEffectsEnableClicked(), OptionsWnd::SoundOptionsFeedback::UISoundsVolumeSlid(), and UserString().
Referenced by CompleteConstruction().
Member Data Documentation
is_game_running
bool OptionsWnd::is_game_running private
Referenced by CompleteConstruction().
m_done_button
std::shared_ptr<GG::Button> OptionsWnd::m_done_button private
Referenced by CompleteConstruction(), and DoLayout().
m_sound_feedback
SoundOptionsFeedback OptionsWnd::m_sound_feedback private
Referenced by CompleteConstruction().
m_tabs
std::shared_ptr<GG::TabWnd> OptionsWnd::m_tabs private
Referenced by CompleteConstruction(), CreatePage(), DoLayout(), and HotkeysPage().
The documentation for this class was generated from the following files:
OptionsWnd.h
OptionsWnd.cpp