FreeOrion: AIClientApp Class Reference
AIClientApp Class Reference
the application framework for an AI player FreeOrion client.
#include <AIClientApp.h>
Public Member Functions
AIClientApp ()=delete
AIClientApp (const std::vector< std::string > &args)
AIClientApp (const AIClientApp &)=delete
AIClientApp (AIClientApp &&)=delete
~AIClientApp () override
const PythonAI * GetAI ()
returns pointer to AIBase implementation of AI for this client
const AIClientApp & operator= (const AIClientApp &)=delete
AIClientApp & operator= (const AIClientApp &&)=delete
Mutators
void operator() ()
external interface to Run()
void ExitApp (int code=0)
does basic clean-up, then calls exit(); callable from anywhere in user code via GetApp()
void SetPlayerName (const std::string &player_name)
external interface to Run()
Accessors
int EffectsProcessingThreads () const override
Return the player name of this client.
const std::string & PlayerName () const
Return the player name of this client.
Public Member Functions inherited from ClientApp
ClientApp (const ClientApp &)=delete
ClientApp (ClientApp &&)=delete
~ClientApp () override=default
int CurrentTurn () const override
Return the current game turn.
int EmpireID () const
Return the empire identifier of the empire this client controls.
std::shared_ptr< UniverseObject > EmpireKnownObject (int object_id, int empire_id) override
Return the UniverseObject object_id if known by empire_id.
ObjectMap & EmpireKnownObjects (int empire_id) override
Return all Objects known to empire_id.
int EmpirePlayerID (int empire_id) const
Return the player identfier of the player controlling the empire empire_id.
Networking::ClientType GetClientType () const
Return The Networking::ClientType of this client.
Empire * GetEmpire (int empire_id) override
Return the Empire identified by empire_id.
Networking::ClientType GetEmpireClientType (int empire_id) const override
Return the Networking::ClientType of the empire empire_id.
Networking::ClientType GetPlayerClientType (int player_id) const override
Return the Networking::ClientType of the player player_id.
SupplyManager & GetSupplyManager () override
std::shared_ptr< UniverseObject > GetUniverseObject (int object_id) override
Return the UniverseObject associated with object_id.
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override
Return the for this client visible name of object.
virtual void HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id)
Handle server acknowledgement of receipt of orders and clear the orders.
virtual void HandleTurnUpdate ()
Handle the turn update.
const ClientApp & operator= (const ClientApp &)=delete
ClientApp & operator= (ClientApp &&)=delete
int PlayerID () const
Return the player identifier of this client.
void SendPartialOrders ()
Send turn orders updates to server without starting new turn.
void SetCurrentTurn (int turn)
Set the current game turn of this client to turn.
void SetEmpireID (int empire_id)
Set the identifier of the Empire controlled by this client to empire_id.
void SetEmpireStatus (int empire_id, Message::PlayerStatus status)
Set the Message::PlayerStatus status for empire_id.
virtual void StartTurn (const SaveGameUIData &ui_data)
Send the OrderSet and UI data to the server and start a new turn.
virtual void StartTurn (const std::string &save_state_string)
Send the OrderSet and AI state to the server and start a new turn.
bool VerifyCheckSum (const Message &msg)
Compare content checksum from server with client content checksum.
std::map< int, PlayerInfo > & Players ()
Return the players in game as PlayerInfo map.
const std::map< int, PlayerInfo > & Players () const
Return the players in game as PlayerInfo map.
Universe & GetUniverse () override
Return the Universe known to this client.
const Universe & GetUniverse () const
Return the Universe known to this client.
GalaxySetupData & GetGalaxySetupData ()
Return the GalaxySetupData of this game.
const GalaxySetupData & GetGalaxySetupData () const override
Return the GalaxySetupData of this game.
OrderSet & Orders ()
Return the OrderSet of this client.
const OrderSet & Orders () const
Return the OrderSet of this client.
ClientNetworking & Networking ()
Return the networking object of this clients player.
const ClientNetworking & Networking () const
Return the networking object of this clients player.
EmpireManager & Empires () override
Return the set of known Empire s for this client.
const EmpireManager & Empires () const
Return the set of known Empire s for this client.
Public Member Functions inherited from IApp
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
virtual void StartBackgroundParsing ()
Start parsing universe object types on a separate thread.
Static Public Member Functions
static AIClientApp * GetApp ()
returns a AIClientApp pointer to the singleton instance of the app
Static Public Member Functions inherited from ClientApp
static ClientApp * GetApp ()
Return the singleton instance of this Application.
Static Public Member Functions inherited from IApp
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Private Member Functions
void ConnectToServer ()
void HandleMessage (const Message &msg)
void HandlePythonAICrash ()
void Run ()
initializes app state, then executes main event handler/render loop (PollAndRender())
void StartPythonAI ()
Private Attributes
std::unique_ptr< PythonAI > m_AI
Implementation of AI logic.
int m_max_aggression
std::string m_player_name
Additional Inherited Members
Protected Member Functions inherited from ClientApp
ClientApp ()
Protected Member Functions inherited from IApp
IApp ()
Protected Attributes inherited from ClientApp
int m_current_turn
int m_empire_id
EmpireManager m_empires
GalaxySetupData m_galaxy_setup_data
std::shared_ptr< ClientNetworking > m_networking
OrderSet m_orders
std::map< int, PlayerInfo > m_player_info
Indexed by player id, contains info about all players in the game.
SupplyManager m_supply_manager
Universe m_universe
Static Protected Attributes inherited from IApp
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Detailed Description
the application framework for an AI player FreeOrion client.
Constructor & Destructor Documentation
AIClientApp() [1/4]
AIClientApp::AIClientApp () delete
AIClientApp() [2/4]
AIClientApp::AIClientApp (const std::vector< std::string > & args)
References DebugLogger, ExitApp(), FreeOrionVersionString(), OptionsDB::Get(), GetOptionsDB(), GetUserDataDir(), InfoLogger, InitLoggingOptionsDBSystem(), InitLoggingSystem(), m_max_aggression, m_player_name, OverrideAllLoggersThresholds(), PlayerName(), OptionsDB::Set(), and to_LogLevel().
AIClientApp() [3/4]
AIClientApp::AIClientApp (const AIClientApp &) delete
AIClientApp() [4/4]
AIClientApp::AIClientApp (AIClientApp &&) delete
~AIClientApp()
AIClientApp::~AIClientApp () override
References DebugLogger, ClientNetworking::DisconnectFromServer(), ClientApp::Networking(), and PlayerName().
Member Function Documentation
ConnectToServer()
void AIClientApp::ConnectToServer () private
References ExitApp(), and ClientApp::Networking().
Referenced by PlayerName(), and Run().
EffectsProcessingThreads()
int AIClientApp::EffectsProcessingThreads () const override virtual
Return the player name of this client.
Returns
An UTF-8 encoded and NUL terminated string containing the player name of this client.
Implements IApp.
References OptionsDB::Get(), and GetOptionsDB().
Referenced by SetPlayerName().
ExitApp()
void AIClientApp::ExitApp (int code = 0)
does basic clean-up, then calls exit(); callable from anywhere in user code via GetApp()
References DebugLogger.
Referenced by AIClientApp(), ConnectToServer(), and HandleMessage().
GetAI()
const PythonAI * AIClientApp::GetAI ()
returns pointer to AIBase implementation of AI for this client
References m_AI.
Referenced by PythonAI::GenerateOrders(), and PlayerName().
GetApp()
AIClientApp * AIClientApp::GetApp () static
returns a AIClientApp pointer to the singleton instance of the app
References IApp::s_app.
Referenced by anonymous_namespace{AIWrapper.cpp}::AllEmpireIDs(), anonymous_namespace{AIWrapper.cpp}::AllPlayerIDs(), anonymous_namespace{AIWrapper.cpp}::EmpireID(), anonymous_namespace{AIWrapper.cpp}::EmpirePlayerID(), PythonAI::GenerateOrders(), anonymous_namespace{AIWrapper.cpp}::GetEmpireByID(), anonymous_namespace{AIWrapper.cpp}::InitMeterEstimatesAndDiscrepancies(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueTechOrder(), anonymous_namespace{AIWrapper.cpp}::IssuedOrders(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueBuildingProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueShipProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueTechOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::PlayerEmpire(), anonymous_namespace{AIWrapper.cpp}::PlayerEmpireID(), anonymous_namespace{AIWrapper.cpp}::PlayerID(), anonymous_namespace{AIWrapper.cpp}::PlayerIsAI(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), PlayerName(), anonymous_namespace{AIWrapper.cpp}::PlayerName(), anonymous_namespace{AIWrapper.cpp}::PlayerNameByID(), anonymous_namespace{AIWrapper.cpp}::PythonGalaxySetupData(), anonymous_namespace{AIWrapper.cpp}::SendDiplomaticMessage(), anonymous_namespace{AIWrapper.cpp}::SendPlayerChatMessage(), anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates(), anonymous_namespace{AIWrapper.cpp}::UpdateProductionQueue(), anonymous_namespace{AIWrapper.cpp}::UpdateResearchQueue(), and anonymous_namespace{AIWrapper.cpp}::UpdateResourcePools().
HandleMessage()
void AIClientApp::HandleMessage (const Message & msg) private
References AIEndGameAcknowledgeMessage(), OrderSet::ApplyOrders(), DebugLogger, ErrorLogger, ExitApp(), ExtractDiplomacyMessageData(), ExtractDiplomaticStatusMessageData(), ExtractGameStartMessageData(), ExtractJoinAckMessageData(), ExtractLoggerConfigMessageData(), ExtractPlayerInfoMessageData(), ExtractServerPlayerChatMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnProgressMessageData(), ExtractTurnUpdateMessageData(), GetCombatLogManager(), ClientApp::GetEmpire(), ClientApp::GetGalaxySetupData(), GetSpeciesManager(), ClientApp::GetSupplyManager(), ClientApp::GetUniverse(), ClientApp::HandleTurnPhaseUpdate(), Universe::InitializeSystemGraph(), Networking::INVALID_PLAYER_ID, m_AI, ClientApp::m_current_turn, ClientApp::m_empire_id, ClientApp::m_empires, ClientApp::m_galaxy_setup_data, m_max_aggression, ClientApp::m_networking, ClientApp::m_orders, ClientApp::m_player_info, GalaxySetupData::m_seed, ClientApp::m_universe, Empire::Name(), ClientApp::Networking(), ClientApp::Orders(), ClientApp::PlayerID(), RandSmallInt(), OrderSet::Reset(), Seed(), ClientNetworking::SendMessage(), SetLoggerThresholds(), Message::Text(), TraceLogger, Message::Type(), and ClientApp::VerifyCheckSum().
Referenced by PlayerName(), and Run().
HandlePythonAICrash()
void AIClientApp::HandlePythonAICrash () private
References ErrorLogger, ErrorMessage(), FlexibleFormat(), ClientApp::Networking(), ClientApp::PlayerID(), PlayerName(), ClientNetworking::SendMessage(), and UserString().
Referenced by PlayerName(), Run(), and StartPythonAI().
operator()()
void AIClientApp::operator() ()
external interface to Run()
References Run().
operator=() [1/2]
const AIClientApp& AIClientApp::operator= (const AIClientApp &) delete
operator=() [2/2]
AIClientApp& AIClientApp::operator= (const AIClientApp &&) delete
PlayerName()
const std::string& AIClientApp::PlayerName () const inline
Return the player name of this client.
Returns
An UTF-8 encoded and NUL terminated string containing the player name of this client.
References ConnectToServer(), GetAI(), GetApp(), HandleMessage(), HandlePythonAICrash(), m_player_name, Run(), and StartPythonAI().
Referenced by AIClientApp(), HandlePythonAICrash(), anonymous_namespace{AIWrapper.cpp}::PlayerName(), Run(), and ~AIClientApp().
Run()
void AIClientApp::Run () private
initializes app state, then executes main event handler/render loop (PollAndRender())
References Networking::CLIENT_TYPE_AI_PLAYER, ConnectToServer(), ClientNetworking::DisconnectFromServer(), HandleMessage(), HandlePythonAICrash(), JoinGameMessage(), m_AI, ClientApp::Networking(), PlayerName(), ClientNetworking::SendMessage(), IApp::StartBackgroundParsing(), and StartPythonAI().
Referenced by operator()(), and PlayerName().
SetPlayerName()
void AIClientApp::SetPlayerName (const std::string & player_name) inline
external interface to Run()
References EffectsProcessingThreads(), and m_player_name.
StartPythonAI()
void AIClientApp::StartPythonAI () private
References HandlePythonAICrash(), and m_AI.
Referenced by PlayerName(), and Run().
Member Data Documentation
m_AI
std::unique_ptr<PythonAI> AIClientApp::m_AI private
Implementation of AI logic.
Referenced by GetAI(), HandleMessage(), Run(), and StartPythonAI().
m_max_aggression
int AIClientApp::m_max_aggression private
Referenced by AIClientApp(), and HandleMessage().
m_player_name
std::string AIClientApp::m_player_name private
Referenced by AIClientApp(), PlayerName(), and SetPlayerName().
The documentation for this class was generated from the following files:
AIClientApp.h
AIClientApp.cpp