FreeOrion: ShipHull Class Reference
ShipHull Class Reference
Specification for the hull, or base, on which ship designs are created by adding parts.
#include <ShipHull.h>
Classes
struct Slot
Public Member Functions
ShipHull ()
ShipHull (const ShipHullStats &stats, CommonParams &&common_params, const MoreCommonParams &more_common_params, const std::vector< Slot > &slots, const std::string &icon, const std::string &graphic)
~ShipHull ()
auto ColonyCapacity () const -> float
Returns colonist capacity of hull.
auto Description () const -> const std::string &
Returns description, including a description of the stats and effects of this hull.
auto Detection () const -> float
Returns detection ability of hull.
auto Effects () const -> const std::vector< std::shared_ptr< Effect::EffectsGroup >> &
Returns the EffectsGroups that encapsulate the effects this part hull has.
auto Exclusions () const -> const std::set< std::string > &
Returns the names of other content that cannot be used in the same ship design as this part.
auto Fuel () const -> float
Returns fuel capacity of hull.
auto GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
auto Graphic () const -> const std::string &
Returns the image that represents the hull on the design screen.
auto HasTag (const std::string &tag) const -> bool
auto Icon () const -> const std::string &
Returns the small icon to represent hull.
auto Location () const -> const Condition::Condition *
Returns the condition that determines the locations where ShipDesign containing hull can be produced.
auto Name () const -> const std::string &
Returns name of hull.
auto NumSlots () const -> unsigned int
Returns total number of of slots in hull.
auto NumSlots (ShipSlotType slot_type) const -> unsigned int
Returns number of of slots of indicated type in hull.
auto Producible () const -> bool
Returns whether this hull type is producible by players and appears on the design screen.
auto ProductionCost (int empire_id, int location_id, int in_design_id=INVALID_DESIGN_ID) const -> float
Returns the number of production points required to produce this hull.
auto ProductionCostTimeLocationInvariant () const -> bool
Returns true if the production cost and time are invariant (does not depend on) the location.
auto ProductionMeterConsumption () const -> const ConsumptionMap< MeterType > &
auto ProductionSpecialConsumption () const -> const ConsumptionMap< std::string > &
auto ProductionTime (int empire_id, int location_id, int in_design_id=INVALID_DESIGN_ID) const -> int
Returns the number of turns required to produce this hull.
auto Shields () const -> float
Returns shields of hull.
auto Slots () const -> const std::vector< Slot > &
Returns vector of slots in hull.
auto Speed () const -> float
Returns starlane speed of hull.
auto Stealth () const -> float
Returns stealth of hull.
auto Structure () const -> float
Returns structure of hull.
auto Tags () const -> const std::set< std::string > &
auto TroopCapacity () const -> float
Returns the troop capacity of hull.
Private Member Functions
void Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, const ShipHullStats &stats)
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::set< std::string > m_exclusions
float m_fuel = 0.0f
std::string m_graphic
std::string m_icon
std::unique_ptr< Condition::Condition > m_location
std::string m_name
bool m_producible = false
std::unique_ptr< ValueRef::ValueRef< double > > m_production_cost
ConsumptionMap< MeterType > m_production_meter_consumption
ConsumptionMap< std::string > m_production_special_consumption
std::unique_ptr< ValueRef::ValueRef< int > > m_production_time
std::vector< Slot > m_slots
float m_speed = 1.0f
float m_stealth = 0.0f
float m_structure = 0.0f
std::set< std::string > m_tags
Friends
class boost::serialization::access
Detailed Description
Specification for the hull, or base, on which ship designs are created by adding parts.
The hull determines some final design characteristics directly, and also determine how many parts can be added to the design.
Constructor & Destructor Documentation
ShipHull() [1/2]
ShipHull::ShipHull ()
ShipHull() [2/2]
ShipHull::ShipHull (const ShipHullStats & stats, CommonParams && common_params, const MoreCommonParams & more_common_params, const std::vector< Slot > & slots, const std::string & icon, const std::string & graphic)
References Init(), m_name, m_producible, m_tags, and TraceLogger.
~ShipHull()
ShipHull::~ShipHull ()
Member Function Documentation
ColonyCapacity()
auto ShipHull::ColonyCapacity () const -> float inline
Returns colonist capacity of hull.
Referenced by ShipDesign::BuildStatCaches().
Description()
auto ShipHull::Description () const -> const std::string& inline
Returns description, including a description of the stats and effects of this hull.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Detection()
auto ShipHull::Detection () const -> float inline
Returns detection ability of hull.
References INVALID_DESIGN_ID.
Referenced by ShipDesign::BuildStatCaches().
Effects()
auto ShipHull::Effects () const -> const std::vector<std::shared_ptr<Effect::EffectsGroup>>& inline
Returns the EffectsGroups that encapsulate the effects this part hull has.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Exclusions()
auto ShipHull::Exclusions () const -> const std::set<std::string>& inline
Returns the names of other content that cannot be used in the same ship design as this part.
Referenced by DesignWnd::MainPanel::DesignChanged(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Fuel()
auto ShipHull::Fuel () const -> float inline
Returns fuel capacity of hull.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
GetCheckSum()
unsigned int ShipHull::GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_description, m_effects, m_exclusions, m_fuel, m_graphic, m_icon, m_location, m_name, m_producible, m_production_cost, m_production_meter_consumption, m_production_special_consumption, m_production_time, m_slots, m_speed, m_stealth, m_structure, m_tags, and ShipHullManager::s_instance.
Graphic()
auto ShipHull::Graphic () const -> const std::string& inline
Returns the image that represents the hull on the design screen.
Referenced by ClientUI::HullIcon(), and ClientUI::HullTexture().
HasTag()
auto ShipHull::HasTag (const std::string & tag) const -> bool inline
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Icon()
auto ShipHull::Icon () const -> const std::string& inline
Returns the small icon to represent hull.
Referenced by ClientUI::HullIcon(), ClientUI::HullTexture(), and DesignWnd::MainPanel::RefreshIncompleteDesign().
Init()
void ShipHull::Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, const ShipHullStats & stats) private
References ShipHullStats::default_fuel_effects, ShipHullStats::default_speed_effects, ShipHullStats::default_stealth_effects, ShipHullStats::default_structure_effects, anonymous_namespace{ShipHull.cpp}::IncreaseMeter(), m_effects, m_fuel, m_location, m_name, m_production_cost, m_production_time, m_speed, m_stealth, m_structure, METER_MAX_FUEL, METER_MAX_STRUCTURE, METER_SPEED, and METER_STEALTH.
Referenced by ShipHull().
Location()
auto ShipHull::Location () const -> const Condition::Condition* inline
Returns the condition that determines the locations where ShipDesign containing hull can be produced.
Referenced by anonymous_namespace{UniverseWrapper.cpp}::HullProductionLocation(), ShipDesign::ProductionLocation(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Name()
auto ShipHull::Name () const -> const std::string& inline
Returns name of hull.
Referenced by DesignWnd::MainPanel::DesignChanged(), Universe::GetEffectsAndTargets(), DesignWnd::MainPanel::Hull(), DesignWnd::MainPanel::SetHull(), EncyclopediaDetailPanel::SetItem(), and FreeOrionPython::WrapUniverseClasses().
NumSlots() [1/2]
auto ShipHull::NumSlots () const -> unsigned int inline
Returns total number of of slots in hull.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
NumSlots() [2/2]
unsigned int ShipHull::NumSlots (ShipSlotType slot_type) const -> unsigned int
Returns number of of slots of indicated type in hull.
References m_slots.
Producible()
auto ShipHull::Producible () const -> bool inline
Returns whether this hull type is producible by players and appears on the design screen.
Referenced by Empire::AddShipHull(), and ShipDesign::BuildStatCaches().
ProductionCost()
float ShipHull::ProductionCost (int empire_id, int location_id, int in_design_id = INVALID_DESIGN_ID) const -> float
Returns the number of production points required to produce this hull.
References anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_COST, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_cost, and Objects().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
ProductionCostTimeLocationInvariant()
bool ShipHull::ProductionCostTimeLocationInvariant () const -> bool
Returns true if the production cost and time are invariant (does not depend on) the location.
References GetGameRules(), m_production_cost, and m_production_time.
Referenced by FreeOrionPython::WrapUniverseClasses().
ProductionMeterConsumption()
auto ShipHull::ProductionMeterConsumption () const -> const ConsumptionMap<MeterType>& inline
ProductionSpecialConsumption()
auto ShipHull::ProductionSpecialConsumption () const -> const ConsumptionMap<std::string>& inline
ProductionTime()
int ShipHull::ProductionTime (int empire_id, int location_id, int in_design_id = INVALID_DESIGN_ID) const -> int
Returns the number of turns required to produce this hull.
References anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_TURNS, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_time, and Objects().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
serialize()
template<typename Archive > void ShipHull::serialize (Archive & ar, const unsigned int version) private
References CheckSums::CheckSumCombine(), and FO_COMMON_API.
Shields()
auto ShipHull::Shields () const -> float inline
Returns shields of hull.
Referenced by ShipDesign::BuildStatCaches().
Slots()
auto ShipHull::Slots () const -> const std::vector<Slot>& inline
Returns vector of slots in hull.
Referenced by ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{UniverseWrapper.cpp}::HullSlots(), ShipDesign::Parts(), and DesignWnd::MainPanel::Populate().
Speed()
float ShipHull::Speed () const -> float
Returns starlane speed of hull.
References GameRules::Get(), GetGameRules(), and m_speed.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Stealth()
auto ShipHull::Stealth () const -> float inline
Returns stealth of hull.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Structure()
float ShipHull::Structure () const -> float
Returns structure of hull.
References GameRules::Get(), GetGameRules(), and m_structure.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Tags()
auto ShipHull::Tags () const -> const std::set<std::string>& inline
Referenced by Ship::HasTag(), and Ship::Tags().
TroopCapacity()
auto ShipHull::TroopCapacity () const -> float inline
Returns the troop capacity of hull.
Referenced by ShipDesign::BuildStatCaches().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_description
std::string ShipHull::m_description private
Referenced by GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > ShipHull::m_effects private
Referenced by GetCheckSum(), and Init().
m_exclusions
std::set<std::string> ShipHull::m_exclusions private
Referenced by GetCheckSum().
m_fuel
float ShipHull::m_fuel = 0.0f private
Referenced by GetCheckSum(), and Init().
m_graphic
std::string ShipHull::m_graphic private
Referenced by GetCheckSum().
m_icon
std::string ShipHull::m_icon private
Referenced by GetCheckSum().
m_location
std::unique_ptr<Condition::Condition> ShipHull::m_location private
Referenced by GetCheckSum(), and Init().
m_name
std::string ShipHull::m_name private
Referenced by GetCheckSum(), Init(), and ShipHull().
m_producible
bool ShipHull::m_producible = false private
Referenced by GetCheckSum(), and ShipHull().
m_production_cost
std::unique_ptr<ValueRef::ValueRef<double> > ShipHull::m_production_cost private
Referenced by GetCheckSum(), Init(), ProductionCost(), and ProductionCostTimeLocationInvariant().
m_production_meter_consumption
ConsumptionMap<MeterType> ShipHull::m_production_meter_consumption private
Referenced by GetCheckSum().
m_production_special_consumption
ConsumptionMap<std::string> ShipHull::m_production_special_consumption private
Referenced by GetCheckSum().
m_production_time
std::unique_ptr<ValueRef::ValueRef<int> > ShipHull::m_production_time private
Referenced by GetCheckSum(), Init(), ProductionCostTimeLocationInvariant(), and ProductionTime().
m_slots
std::vector<Slot> ShipHull::m_slots private
Referenced by GetCheckSum(), and NumSlots().
m_speed
float ShipHull::m_speed = 1.0f private
Referenced by GetCheckSum(), Init(), and Speed().
m_stealth
float ShipHull::m_stealth = 0.0f private
Referenced by GetCheckSum(), and Init().
m_structure
float ShipHull::m_structure = 0.0f private
Referenced by GetCheckSum(), Init(), and Structure().
m_tags
std::set<std::string> ShipHull::m_tags private
Referenced by GetCheckSum(), and ShipHull().
The documentation for this class was generated from the following files:
ShipHull.h
ShipHull.cpp