FreeOrion: SidePanel::PlanetPanelContainer Class Reference
SidePanel::PlanetPanelContainer Class Reference
Container class that holds PlanetPanels.
Public Member Functions
Structors
PlanetPanelContainer ()
~PlanetPanelContainer ()
Accessors
bool InWindow (const GG::Pt &pt) const override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
int SelectedPlanetID () const
const std::set< int > & SelectionCandidates () const
int ScrollPosition () const
Mutators
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
programatically selects a planet with id planet_id
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
programatically selects a planet with id planet_id
void PreRender () override
programatically selects a planet with id planet_id
void Clear ()
programatically selects a planet with id planet_id
void SetPlanets (const std::vector< int > &planet_ids, StarType star_type)
programatically selects a planet with id planet_id
void SelectPlanet (int planet_id)
programatically selects a planet with id planet_id
void SetValidSelectionPredicate (const std::shared_ptr< UniverseObjectVisitor > &visitor)
programatically selects a planet with id planet_id
void ScrollTo (int pos)
programatically selects a planet with id planet_id
void RefreshAllPlanetPanels (int excluded_planet_id=INVALID_OBJECT_ID, bool require_prerender=false)
Updates data displayed in info panels and redoes layout.
virtual void ShowScrollbar ()
programatically selects a planet with id planet_id
virtual void HideScrollbar ()
programatically selects a planet with id planet_id
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via the PlanetPanels in this PlanetPanelContainer.
Public Attributes
boost::signals2::signal< void(int)> BuildingRightClickedSignal
boost::signals2::signal< void(int)> PlanetClickedSignal
emitted when an enabled planet panel is clicked by the user
boost::signals2::signal< void(int)> PlanetLeftDoubleClickedSignal
emitted when a planet panel is left-double-clicked
boost::signals2::signal< void(int)> PlanetRightClickedSignal
emitted when a planet panel is right-clicked
Private Member Functions
void DisableNonSelectionCandidates ()
disables planet panels that aren't selection candidates
void DoLayout ()
void DoPanelsLayout ()
repositions PlanetPanels, without moving top panel. Panels below may shift if ones above them have resized.
GG::Y ResizePanelsForVScroll (bool use_vscroll)
Resize the panels and use_vscroll if requested.
void VScroll (int pos_top, int pos_bottom, int range_min, int range_max)
responds to user scrolling of planet panels list. all but first parameter ignored
Private Attributes
std::set< int > m_candidate_ids
bool m_ignore_recursive_resize
std::vector< std::shared_ptr< PlanetPanel > > m_planet_panels
int m_selected_planet_id
std::shared_ptr< UniverseObjectVisitor > m_valid_selection_predicate
std::shared_ptr< GG::Scroll > m_vscroll
the vertical scroll (for viewing all the planet panes);
Detailed Description
Container class that holds PlanetPanels.
Creates and destroys PlanetPanel as necessary, and does layout of them after creation and in response to scrolling through them by the user.
Constructor & Destructor Documentation
PlanetPanelContainer()
SidePanel::PlanetPanelContainer::PlanetPanelContainer ()
References m_vscroll, anonymous_namespace{ServerWrapper.cpp}::SetName(), and VScroll().
~PlanetPanelContainer()
SidePanel::PlanetPanelContainer::~PlanetPanelContainer ()
Member Function Documentation
Clear()
void SidePanel::PlanetPanelContainer::Clear ()
programatically selects a planet with id planet_id
References INVALID_OBJECT_ID, m_planet_panels, m_selected_planet_id, and m_vscroll.
Referenced by SetPlanets().
DisableNonSelectionCandidates()
void SidePanel::PlanetPanelContainer::DisableNonSelectionCandidates () private
disables planet panels that aren't selection candidates
References ObjectMap::get(), m_candidate_ids, m_planet_panels, m_valid_selection_predicate, and Objects().
Referenced by SetPlanets().
DoLayout()
void SidePanel::PlanetPanelContainer::DoLayout () private
References DoPanelsLayout(), m_vscroll, and ClientUI::ScrollWidth().
Referenced by PreRender().
DoPanelsLayout()
void SidePanel::PlanetPanelContainer::DoPanelsLayout () private
repositions PlanetPanels, without moving top panel. Panels below may shift if ones above them have resized.
References anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), m_ignore_recursive_resize, m_planet_panels, m_vscroll, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), and ResizePanelsForVScroll().
Referenced by DoLayout().
EnableOrderIssuing()
void SidePanel::PlanetPanelContainer::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via the PlanetPanels in this PlanetPanelContainer.
References m_planet_panels.
HideScrollbar()
void SidePanel::PlanetPanelContainer::HideScrollbar () virtual
programatically selects a planet with id planet_id
References m_vscroll.
InWindow()
bool SidePanel::PlanetPanelContainer::InWindow (const GG::Pt & pt) const override
References m_planet_panels, and anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter().
LDrag()
void SidePanel::PlanetPanelContainer::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override
programatically selects a planet with id planet_id
MouseWheel()
void SidePanel::PlanetPanelContainer::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
References m_vscroll.
PreRender()
void SidePanel::PlanetPanelContainer::PreRender () override
programatically selects a planet with id planet_id
References DoLayout().
RefreshAllPlanetPanels()
void SidePanel::PlanetPanelContainer::RefreshAllPlanetPanels (int excluded_planet_id = INVALID_OBJECT_ID, bool require_prerender = false)
Updates data displayed in info panels and redoes layout.
Parameters
[in] excluded_planet_id Excludes panels with this planet id
[in] require_prerender Set panels to RequirePreRender
References INVALID_OBJECT_ID, and m_planet_panels.
Referenced by SetPlanets().
ResizePanelsForVScroll()
GG::Y SidePanel::PlanetPanelContainer::ResizePanelsForVScroll (bool use_vscroll) private
Resize the panels and use_vscroll if requested.
Return the total height.
References anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), m_planet_panels, and m_vscroll.
Referenced by DoPanelsLayout().
ScrollPosition()
int SidePanel::PlanetPanelContainer::ScrollPosition () const
References m_vscroll.
ScrollTo()
void SidePanel::PlanetPanelContainer::ScrollTo (int pos)
programatically selects a planet with id planet_id
References m_vscroll.
SelectedPlanetID()
int SidePanel::PlanetPanelContainer::SelectedPlanetID () const inline
SelectionCandidates()
const std::set<int>& SidePanel::PlanetPanelContainer::SelectionCandidates () const inline
References INVALID_OBJECT_ID.
SelectPlanet()
void SidePanel::PlanetPanelContainer::SelectPlanet (int planet_id)
programatically selects a planet with id planet_id
References HumanClientApp::GetApp(), INVALID_OBJECT_ID, m_candidate_ids, m_planet_panels, m_selected_planet_id, and ClientApp::SendPartialOrders().
Referenced by SetPlanets().
SetPlanets()
void SidePanel::PlanetPanelContainer::SetPlanets (const std::vector< int > & planet_ids, StarType star_type)
programatically selects a planet with id planet_id
References BuildingRightClickedSignal, Clear(), DisableNonSelectionCandidates(), ErrorLogger, ObjectMap::get(), m_planet_panels, m_selected_planet_id, m_vscroll, Objects(), PlanetClickedSignal, PlanetLeftDoubleClickedSignal, PlanetRightClickedSignal, RefreshAllPlanetPanels(), and SelectPlanet().
SetValidSelectionPredicate()
void SidePanel::PlanetPanelContainer::SetValidSelectionPredicate (const std::shared_ptr< UniverseObjectVisitor > & visitor)
programatically selects a planet with id planet_id
References m_valid_selection_predicate.
ShowScrollbar()
void SidePanel::PlanetPanelContainer::ShowScrollbar () virtual
programatically selects a planet with id planet_id
SizeMove()
void SidePanel::PlanetPanelContainer::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
programatically selects a planet with id planet_id
VScroll()
void SidePanel::PlanetPanelContainer::VScroll (int pos_top, int pos_bottom, int range_min, int range_max) private
responds to user scrolling of planet panels list. all but first parameter ignored
Referenced by PlanetPanelContainer().
Member Data Documentation
BuildingRightClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanelContainer::BuildingRightClickedSignal mutable
Referenced by SetPlanets().
m_candidate_ids
std::set<int> SidePanel::PlanetPanelContainer::m_candidate_ids private
Referenced by DisableNonSelectionCandidates(), and SelectPlanet().
m_ignore_recursive_resize
bool SidePanel::PlanetPanelContainer::m_ignore_recursive_resize private
Referenced by DoPanelsLayout().
m_planet_panels
std::vector<std::shared_ptr<PlanetPanel> > SidePanel::PlanetPanelContainer::m_planet_panels private
Referenced by Clear(), DisableNonSelectionCandidates(), DoPanelsLayout(), EnableOrderIssuing(), InWindow(), RefreshAllPlanetPanels(), ResizePanelsForVScroll(), SelectPlanet(), and SetPlanets().
m_selected_planet_id
int SidePanel::PlanetPanelContainer::m_selected_planet_id private
Referenced by Clear(), SelectPlanet(), and SetPlanets().
m_valid_selection_predicate
std::shared_ptr<UniverseObjectVisitor> SidePanel::PlanetPanelContainer::m_valid_selection_predicate private
Referenced by DisableNonSelectionCandidates(), and SetValidSelectionPredicate().
m_vscroll
std::shared_ptr<GG::Scroll> SidePanel::PlanetPanelContainer::m_vscroll private
the vertical scroll (for viewing all the planet panes);
Referenced by Clear(), DoLayout(), DoPanelsLayout(), HideScrollbar(), MouseWheel(), PlanetPanelContainer(), ResizePanelsForVScroll(), ScrollPosition(), ScrollTo(), and SetPlanets().
PlanetClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanelContainer::PlanetClickedSignal mutable
emitted when an enabled planet panel is clicked by the user
Referenced by SetPlanets().
PlanetLeftDoubleClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanelContainer::PlanetLeftDoubleClickedSignal mutable
emitted when a planet panel is left-double-clicked
Referenced by SetPlanets().
PlanetRightClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanelContainer::PlanetRightClickedSignal mutable
emitted when a planet panel is right-clicked
Referenced by SetPlanets().
The documentation for this class was generated from the following file:
SidePanel.cpp