FreeOrion: anonymous_namespace{DesignWnd.cpp}::AvailabilityManager Class Reference
anonymous_namespace{DesignWnd.cpp}::AvailabilityManager Class Reference
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a ship design.
Public Types
using DisplayedAvailabilies = std::tuple< bool, bool, bool >
Public Member Functions
AvailabilityManager (bool obsolete, bool available, bool unavailable)
boost::optional< DisplayedAvailabilies > DisplayedDesignAvailability (const ShipDesign &design) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the design.
boost::optional< DisplayedAvailabilies > DisplayedHullAvailability (const std::string &name) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the hull name.
boost::optional< DisplayedAvailabilies > DisplayedPartAvailability (const std::string &name) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the part name.
const DisplayedAvailabilies & GetAvailabilities () const
bool GetAvailability (const Availability::Enum type) const
void SetAvailability (const Availability::Enum type, const bool state)
void ToggleAvailability (const Availability::Enum type)
Private Member Functions
boost::optional< DisplayedAvailabilies > DisplayedXAvailability (bool available, bool obsolete) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager and that the X is available and obsolete, return the displayed state of the X.
Private Attributes
DisplayedAvailabilies m_availabilities
Detailed Description
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a ship design.
Member Typedef Documentation
DisplayedAvailabilies
using anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedAvailabilies = std::tuple<bool, bool, bool>
Constructor & Destructor Documentation
AvailabilityManager()
anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::AvailabilityManager (bool obsolete, bool available, bool unavailable)
Member Function Documentation
DisplayedDesignAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability (const ShipDesign & design) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the design.
Return none if the design should not be displayed.
References DisplayedXAvailability(), ClientApp::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), ShipDesign::ID(), and Empire::ShipDesignAvailable().
DisplayedHullAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability (const std::string & name) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the hull name.
Return none if the hull should not be displayed.
References DisplayedXAvailability(), ClientApp::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), and Empire::ShipHullAvailable().
DisplayedPartAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability (const std::string & name) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the part name.
Return none if the part should not be displayed.
References DisplayedXAvailability(), ClientApp::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), and Empire::ShipPartAvailable().
DisplayedXAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedXAvailability (bool available, bool obsolete) const private
Given the GUI's displayed availabilities as stored in this AvailabilityManager and that the X is available and obsolete, return the displayed state of the X.
Return none if the X should not be displayed.
References m_availabilities.
Referenced by DisplayedDesignAvailability(), DisplayedHullAvailability(), and DisplayedPartAvailability().
GetAvailabilities()
const DisplayedAvailabilies& anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::GetAvailabilities () const inline
GetAvailability()
bool anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::GetAvailability (const Availability::Enum type) const
References Availability::Available, Availability::Future, m_availabilities, and Availability::Obsolete.
Referenced by ToggleAvailability().
SetAvailability()
void anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::SetAvailability (const Availability::Enum type, const bool state)
References Availability::Available, Availability::Future, m_availabilities, and Availability::Obsolete.
Referenced by ToggleAvailability().
ToggleAvailability()
void anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::ToggleAvailability (const Availability::Enum type)
References GetAvailability(), and SetAvailability().
Member Data Documentation
m_availabilities
DisplayedAvailabilies anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::m_availabilities private
Referenced by DisplayedXAvailability(), GetAvailability(), and SetAvailability().
The documentation for this class was generated from the following file:
DesignWnd.cpp