FreeOrion: Moderator::DestroyUniverseObject Class Reference
Moderator::DestroyUniverseObject Class Reference
#include <ModeratorAction.h>
Public Member Functions
DestroyUniverseObject ()=default
DestroyUniverseObject (int object_id)
std::string Dump () const override
void Execute () const override
Public Member Functions inherited from Moderator::ModeratorAction
ModeratorAction ()=default
virtual ~ModeratorAction ()=default
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_object_id = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Constructor & Destructor Documentation
DestroyUniverseObject() [1/2]
Moderator::DestroyUniverseObject::DestroyUniverseObject () default
DestroyUniverseObject() [2/2]
Moderator::DestroyUniverseObject::DestroyUniverseObject (int object_id) explicit
Member Function Documentation
Dump()
std::string Moderator::DestroyUniverseObject::Dump () const override virtual
Reimplemented from Moderator::ModeratorAction.
References m_object_id, and to_string().
Execute()
void Moderator::DestroyUniverseObject::Execute () const override virtual
Reimplemented from Moderator::ModeratorAction.
References GetUniverse(), m_object_id, and Universe::RecursiveDestroy().
serialize()
template<typename Archive > template void Moderator::DestroyUniverseObject::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_object_id
int Moderator::DestroyUniverseObject::m_object_id = INVALID_OBJECT_ID private
Referenced by Dump(), and Execute().
The documentation for this class was generated from the following files:
ModeratorAction.h
ModeratorAction.cpp
SerializeModeratorAction.cpp