FreeOrion: anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow Class Reference
anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow Class Reference
Public Member Functions
ProductionItemRow (GG::X w, GG::Y h, const ProductionQueue::ProductionItem &item, int empire_id, int location_id)
const ProductionQueue::ProductionItem & Item () const
int Location () const
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
int m_empire_id
ProductionQueue::ProductionItem m_item
int m_location_id
ProductionItemPanel * m_panel
Constructor & Destructor Documentation
anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow (GG::X w, GG::Y h, const ProductionQueue::ProductionItem & item, int empire_id, int location_id) inline
References BT_SHIP, GetEmpire(), GetOptionsDB(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ServerWrapper.cpp}::SetName(), and to_string().
Member Function Documentation
const ProductionQueue::ProductionItem& anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::Item () const inline
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::Location () const inline
void anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::m_empire_id private
ProductionQueue::ProductionItem anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::m_item private
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::m_location_id private
ProductionItemPanel* anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::m_panel private
The documentation for this class was generated from the following file:
BuildDesignatorWnd.cpp