FreeOrion: ObjectHeaderPanel Class Reference
ObjectHeaderPanel Class Reference
Public Member Functions
ObjectHeaderPanel (GG::X w, GG::Y h)
void Refresh ()
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
boost::signals2::signal< void(int)> ColumnButtonLeftClickSignal
boost::signals2::signal< void()> ColumnsChangedSignal
Private Member Functions
void ButtonRightClicked (int column_id)
void DoLayout ()
std::vector< std::shared_ptr< GG::Button > > GetControls ()
Private Attributes
std::vector< std::shared_ptr< GG::Button > > m_controls
Constructor & Destructor Documentation
ObjectHeaderPanel::ObjectHeaderPanel (GG::X w, GG::Y h) inline
Member Function Documentation
void ObjectHeaderPanel::ButtonRightClicked (int column_id) inline private
References anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), and UserString().
Referenced by Refresh().
void ObjectHeaderPanel::DoLayout () inline private
References anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), and anonymous_namespace{ObjectListWnd.cpp}::PAD().
std::vector<std::shared_ptr<GG::Button> > ObjectHeaderPanel::GetControls () inline private
References anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS(), and UserString().
void ObjectHeaderPanel::Refresh () inline
References ButtonRightClicked().
void ObjectHeaderPanel::Render () inline override
void ObjectHeaderPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
boost::signals2::signal<void (int)> ObjectHeaderPanel::ColumnButtonLeftClickSignal mutable
boost::signals2::signal<void ()> ObjectHeaderPanel::ColumnsChangedSignal mutable
std::vector<std::shared_ptr<GG::Button> > ObjectHeaderPanel::m_controls private
The documentation for this class was generated from the following file:
ObjectListWnd.cpp