FreeOrion: PlayerConnection Class Reference
PlayerConnection Class Reference
Encapsulates the connection to a single player.
#include <ServerNetworking.h>
Public Member Functions
Structors
~PlayerConnection ()
Dtor.
Accessors
bool EstablishedPlayer () const
Returns true if EstablishPlayer() successfully has been called on this connection.
int PlayerID () const
Returns the ID of the player associated with this connection, if any.
const std::string & PlayerName () const
Returns the name of the player associated with this connection, if any.
Networking::ClientType GetClientType () const
Returns the type of client associated with this connection (AI client, human client, ...)
const std::string & ClientVersionString () const
Returns the version string the client provided when joining.
bool IsBinarySerializationUsed () const
Checks if the server will enable binary serialization for this client's connection.
bool IsLocalConnection () const
Checks if client associated with this connection runs on the same physical machine as the server.
bool IsEstablished () const
Checks if the player is established, has a valid name, id and client type.
bool IsAuthenticated () const
Checks if the player was authenticated.
bool HasAuthRole (Networking::RoleType role) const
Checks if the player has a some role.
boost::uuids::uuid Cookie () const
Get cookie associated with this connection.
Mutators
void Start ()
Starts the connection reading incoming messages on its socket.
void SendMessage (const Message &message)
Sends synchronous message to out on the connection.
void AwaitPlayer (Networking::ClientType client_type, const std::string &client_version_string)
Set player properties to use them after authentication successed.
void EstablishPlayer (int id, const std::string &player_name, Networking::ClientType client_type, const std::string &client_version_string)
Establishes a connection as a player with a specific name and id.
void SetClientType (Networking::ClientType client_type)
Sets this connection's client type.
void SetAuthenticated ()
Sets authenticated status for connection.
void SetAuthRoles (const std::initializer_list< Networking::RoleType > &roles)
Sets authorization roles and send message to client.
void SetAuthRoles (const Networking::AuthRoles &roles)
Starts the connection reading incoming messages on its socket.
void SetAuthRole (Networking::RoleType role, bool value=true)
Sets or unset authorizaion role and send message to client.
void SetCookie (boost::uuids::uuid cookie)
Sets cookie value to this connection to update expire date.
Static Public Member Functions
static PlayerConnectionPtr NewConnection (boost::asio::io_context &io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback)
Creates a new PlayerConnection and returns it as a shared_ptr.
Public Attributes
boost::signals2::signal< void(const NullaryFn &)> EventSignal
Private Member Functions
PlayerConnection (boost::asio::io_context &io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback)
void AsyncReadMessage ()
void AsyncWriteMessage ()
void HandleMessageBodyRead (boost::system::error_code error, std::size_t bytes_transferred)
void HandleMessageHeaderRead (boost::system::error_code error, std::size_t bytes_transferred)
Static Private Member Functions
static void AsyncErrorHandler (PlayerConnectionPtr self, boost::system::error_code handled_error, boost::system::error_code error)
static void HandleMessageWrite (PlayerConnectionPtr self, boost::system::error_code error, std::size_t bytes_transferred)
static void SendMessageImpl (PlayerConnectionPtr self, Message message)
Places message to the end of sending queue and start asynchronous write if message was first in the queue.
Private Attributes
bool m_authenticated = false
Networking::ClientType m_client_type = Networking::INVALID_CLIENT_TYPE
std::string m_client_version_string
boost::uuids::uuid m_cookie
ConnectionFn m_disconnected_callback
int m_ID = Networking::INVALID_PLAYER_ID
Message::HeaderBuffer m_incoming_header_buffer
Message m_incoming_message
bool m_new_connection = true
MessageAndConnectionFn m_nonplayer_message_callback
Message::HeaderBuffer m_outgoing_header
std::list< Message > m_outgoing_messages
MessageAndConnectionFn m_player_message_callback
std::string m_player_name
Networking::AuthRoles m_roles
boost::asio::io_context & m_service
boost::asio::ip::tcp::socket m_socket
bool m_valid = true
Friends
class ServerNetworking
Detailed Description
Encapsulates the connection to a single player.
This object should have nearly the same lifetime as the socket it represents, except that the object is constructed just before the socket connection is made. A newly-constructed PlayerConnection has no associated player ID, player name, nor host-player status. Once a PlayerConnection is accepted by the server as an actual player in a game, EstablishPlayer() should be called. This establishes the aforementioned properties.
Constructor & Destructor Documentation
~PlayerConnection()
PlayerConnection::~PlayerConnection ()
Dtor.
References error, ErrorLogger, Networking::INVALID_PLAYER_ID, m_ID, m_socket, and TraceLogger.
PlayerConnection()
PlayerConnection::PlayerConnection (boost::asio::io_context & io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback) private
Referenced by NewConnection().
Member Function Documentation
AsyncErrorHandler()
void PlayerConnection::AsyncErrorHandler (PlayerConnectionPtr self, boost::system::error_code handled_error, boost::system::error_code error) static private
Referenced by HandleMessageWrite().
AsyncReadMessage()
void PlayerConnection::AsyncReadMessage () private
References HandleMessageHeaderRead(), m_incoming_header_buffer, and m_socket.
Referenced by HandleMessageBodyRead(), HandleMessageHeaderRead(), and Start().
AsyncWriteMessage()
void PlayerConnection::AsyncWriteMessage () private
References ErrorLogger, HandleMessageWrite(), HeaderToBuffer(), m_ID, m_outgoing_header, m_outgoing_messages, m_socket, and m_valid.
AwaitPlayer()
void PlayerConnection::AwaitPlayer (Networking::ClientType client_type, const std::string & client_version_string)
Set player properties to use them after authentication successed.
References ErrorLogger, Networking::INVALID_CLIENT_TYPE, m_client_type, m_client_version_string, Networking::NUM_CLIENT_TYPES, and TraceLogger.
ClientVersionString()
const std::string & PlayerConnection::ClientVersionString () const
Returns the version string the client provided when joining.
References m_client_version_string.
Cookie()
boost::uuids::uuid PlayerConnection::Cookie () const
Get cookie associated with this connection.
References m_cookie.
EstablishedPlayer()
bool PlayerConnection::EstablishedPlayer () const
Returns true if EstablishPlayer() successfully has been called on this connection.
References Networking::INVALID_PLAYER_ID, and m_ID.
Referenced by HandleMessageBodyRead().
EstablishPlayer()
void PlayerConnection::EstablishPlayer (int id, const std::string & player_name, Networking::ClientType client_type, const std::string & client_version_string)
Establishes a connection as a player with a specific name and id.
This function must only be called once.
References ErrorLogger, Networking::INVALID_CLIENT_TYPE, IsEstablished(), m_client_type, m_client_version_string, m_ID, m_player_name, Networking::NUM_CLIENT_TYPES, and TraceLogger.
GetClientType()
Networking::ClientType PlayerConnection::GetClientType () const
Returns the type of client associated with this connection (AI client, human client, ...)
References m_client_type.
HandleMessageBodyRead()
void PlayerConnection::HandleMessageBodyRead (boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncReadMessage(), ErrorLogger, EstablishedPlayer(), EventSignal, m_disconnected_callback, m_ID, m_incoming_header_buffer, m_incoming_message, m_nonplayer_message_callback, m_player_message_callback, anonymous_namespace{ServerNetworking.cpp}::MessageTypeName(), Message::Size(), TraceLogger, and Message::Type().
Referenced by HandleMessageHeaderRead().
HandleMessageHeaderRead()
void PlayerConnection::HandleMessageHeaderRead (boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncReadMessage(), BufferToHeader(), Message::Data(), error, ErrorLogger, EventSignal, GetOptionsDB(), HandleMessageBodyRead(), Message::HeaderBufferSize, m_disconnected_callback, m_ID, m_incoming_header_buffer, m_incoming_message, m_new_connection, m_socket, Message::Resize(), and Message::Size().
Referenced by AsyncReadMessage().
HandleMessageWrite()
void PlayerConnection::HandleMessageWrite (PlayerConnectionPtr self, boost::system::error_code error, std::size_t bytes_transferred) static private
References AsyncErrorHandler(), ErrorLogger, and Message::HeaderBufferSize.
Referenced by AsyncWriteMessage().
HasAuthRole()
bool PlayerConnection::HasAuthRole (Networking::RoleType role) const
Checks if the player has a some role.
References Networking::AuthRoles::HasRole(), and m_roles.
IsAuthenticated()
bool PlayerConnection::IsAuthenticated () const
Checks if the player was authenticated.
References m_authenticated.
IsBinarySerializationUsed()
bool PlayerConnection::IsBinarySerializationUsed () const
Checks if the server will enable binary serialization for this client's connection.
References FreeOrionVersionString(), OptionsDB::Get(), GetOptionsDB(), and m_client_version_string.
IsEstablished()
bool PlayerConnection::IsEstablished () const
Checks if the player is established, has a valid name, id and client type.
References Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, m_client_type, m_ID, and m_player_name.
Referenced by EstablishPlayer().
IsLocalConnection()
bool PlayerConnection::IsLocalConnection () const
Checks if client associated with this connection runs on the same physical machine as the server.
References m_socket.
NewConnection()
PlayerConnectionPtr PlayerConnection::NewConnection (boost::asio::io_context & io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback) static
Creates a new PlayerConnection and returns it as a shared_ptr.
References PlayerConnection().
Referenced by ServerNetworking::AcceptNextMessagingConnection().
PlayerID()
int PlayerConnection::PlayerID () const
Returns the ID of the player associated with this connection, if any.
References m_ID.
PlayerName()
const std::string & PlayerConnection::PlayerName () const
Returns the name of the player associated with this connection, if any.
References m_player_name.
SendMessage()
void PlayerConnection::SendMessage (const Message & message)
Sends synchronous message to out on the connection.
References ErrorLogger, m_service, m_valid, and SendMessageImpl().
Referenced by SetAuthenticated(), SetAuthRole(), and SetAuthRoles().
SendMessageImpl()
void PlayerConnection::SendMessageImpl (PlayerConnectionPtr self, Message message) static private
Places message to the end of sending queue and start asynchronous write if message was first in the queue.
References swap().
Referenced by SendMessage().
SetAuthenticated()
void PlayerConnection::SetAuthenticated ()
Sets authenticated status for connection.
References m_authenticated, m_roles, SendMessage(), SetAuthorizationRolesMessage(), and SetAuthRoles().
SetAuthRole()
void PlayerConnection::SetAuthRole (Networking::RoleType role, bool value = true)
Sets or unset authorizaion role and send message to client.
References m_roles, SendMessage(), SetAuthorizationRolesMessage(), and Networking::AuthRoles::SetRole().
SetAuthRoles() [1/2]
void PlayerConnection::SetAuthRoles (const std::initializer_list< Networking::RoleType > & roles)
Sets authorization roles and send message to client.
Referenced by SetAuthenticated().
SetAuthRoles() [2/2]
void PlayerConnection::SetAuthRoles (const Networking::AuthRoles & roles)
Starts the connection reading incoming messages on its socket.
References m_roles, SendMessage(), and SetAuthorizationRolesMessage().
SetClientType()
void PlayerConnection::SetClientType (Networking::ClientType client_type)
Sets this connection's client type.
Useful for already-connected players changing type such as in the multiplayer lobby.
References ErrorLogger, Networking::INVALID_CLIENT_TYPE, and m_client_type.
SetCookie()
void PlayerConnection::SetCookie (boost::uuids::uuid cookie)
Sets cookie value to this connection to update expire date.
References m_cookie.
Start()
void PlayerConnection::Start ()
Starts the connection reading incoming messages on its socket.
References AsyncReadMessage().
Friends And Related Function Documentation
ServerNetworking
friend class ServerNetworking friend
Member Data Documentation
EventSignal
boost::signals2::signal<void (const NullaryFn&)> PlayerConnection::EventSignal mutable
Referenced by HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_authenticated
bool PlayerConnection::m_authenticated = false private
Referenced by IsAuthenticated(), and SetAuthenticated().
m_client_type
Networking::ClientType PlayerConnection::m_client_type = Networking::INVALID_CLIENT_TYPE private
Referenced by AwaitPlayer(), EstablishPlayer(), GetClientType(), IsEstablished(), and SetClientType().
m_client_version_string
std::string PlayerConnection::m_client_version_string private
Referenced by AwaitPlayer(), ClientVersionString(), EstablishPlayer(), and IsBinarySerializationUsed().
m_cookie
boost::uuids::uuid PlayerConnection::m_cookie private
Referenced by Cookie(), and SetCookie().
m_disconnected_callback
ConnectionFn PlayerConnection::m_disconnected_callback private
Referenced by HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_ID
int PlayerConnection::m_ID = Networking::INVALID_PLAYER_ID private
Referenced by AsyncWriteMessage(), EstablishedPlayer(), EstablishPlayer(), HandleMessageBodyRead(), HandleMessageHeaderRead(), IsEstablished(), PlayerID(), and ~PlayerConnection().
m_incoming_header_buffer
Message::HeaderBuffer PlayerConnection::m_incoming_header_buffer private
Referenced by AsyncReadMessage(), HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_incoming_message
Message PlayerConnection::m_incoming_message private
Referenced by HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_new_connection
bool PlayerConnection::m_new_connection = true private
Referenced by HandleMessageHeaderRead().
m_nonplayer_message_callback
MessageAndConnectionFn PlayerConnection::m_nonplayer_message_callback private
Referenced by HandleMessageBodyRead().
m_outgoing_header
Message::HeaderBuffer PlayerConnection::m_outgoing_header private
Referenced by AsyncWriteMessage().
m_outgoing_messages
std::list<Message> PlayerConnection::m_outgoing_messages private
Referenced by AsyncWriteMessage().
m_player_message_callback
MessageAndConnectionFn PlayerConnection::m_player_message_callback private
Referenced by HandleMessageBodyRead().
m_player_name
std::string PlayerConnection::m_player_name private
Referenced by EstablishPlayer(), IsEstablished(), and PlayerName().
m_roles
Networking::AuthRoles PlayerConnection::m_roles private
Referenced by HasAuthRole(), SetAuthenticated(), SetAuthRole(), and SetAuthRoles().
m_service
boost::asio::io_context& PlayerConnection::m_service private
Referenced by SendMessage().
m_socket
boost::asio::ip::tcp::socket PlayerConnection::m_socket private
Referenced by AsyncReadMessage(), AsyncWriteMessage(), HandleMessageHeaderRead(), IsLocalConnection(), and ~PlayerConnection().
m_valid
bool PlayerConnection::m_valid = true private
Referenced by AsyncWriteMessage(), and SendMessage().
The documentation for this class was generated from the following files:
ServerNetworking.h
ServerNetworking.cpp