FreeOrion: anonymous_namespace{SidePanel.cpp}::SystemRow Class Reference
anonymous_namespace{SidePanel.cpp}::SystemRow Class Reference
Public Member Functions
SystemRow (int system_id, GG::Y h)
void Init ()
void PreRender () override
SortKeyType SortKey (std::size_t column) const override
int SystemID () const
Private Attributes
int m_system_id
Constructor & Destructor Documentation
SystemRow()
anonymous_namespace{SidePanel.cpp}::SystemRow::SystemRow (int system_id, GG::Y h) inline
References anonymous_namespace{ServerWrapper.cpp}::SetName().
Member Function Documentation
Init()
void anonymous_namespace{SidePanel.cpp}::SystemRow::Init () inline
References anonymous_namespace{SidePanel.cpp}::SystemNameFontSize().
PreRender()
void anonymous_namespace{SidePanel.cpp}::SystemRow::PreRender () inline override
SortKey()
SortKeyType anonymous_namespace{SidePanel.cpp}::SystemRow::SortKey (std::size_t column) const inline override
References ObjectMap::get(), anonymous_namespace{XMLDoc.cpp}::Name, Objects(), and to_string().
SystemID()
int anonymous_namespace{SidePanel.cpp}::SystemRow::SystemID () const inline
Member Data Documentation
m_system_id
int anonymous_namespace{SidePanel.cpp}::SystemRow::m_system_id private
The documentation for this class was generated from the following file:
SidePanel.cpp