FreeOrion: ScanlineControl Class Reference
ScanlineControl Class Reference
Renders scanlines over its area.
#include <CUIControls.h>
Public Member Functions
ScanlineControl (GG::X x, GG::Y y, GG::X w, GG::Y h, bool square=false, GG::Clr clr=GG::CLR_BLACK)
void Render () override
Changes the color used to draw the scanlines.
void SetColor (GG::Clr clr) override
Private Attributes
GG::Clr m_color
bool m_square = false
Detailed Description
Renders scanlines over its area.
Constructor & Destructor Documentation
ScanlineControl()
ScanlineControl::ScanlineControl (GG::X x, GG::Y y, GG::X w, GG::Y h, bool square = false, GG::Clr clr = GG::CLR_BLACK)
Member Function Documentation
Render()
void ScanlineControl::Render () override
Changes the color used to draw the scanlines.
References m_color, m_square, ScanlineRenderer::RenderCircle(), ScanlineRenderer::RenderRectangle(), anonymous_namespace{CUIControls.cpp}::scanline_shader, and ScanlineRenderer::SetColor().
SetColor()
void ScanlineControl::SetColor (GG::Clr clr) inline override
Member Data Documentation
m_color
GG::Clr ScanlineControl::m_color private
Referenced by Render().
m_square
bool ScanlineControl::m_square = false private
Referenced by Render().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp