FreeOrion: CUIWnd Class Reference
CUIWnd Class Reference
This class is a superclass of all interface windows in GG. It takes care of.
#include <CUIWnd.h>
Public Member Functions
Structors //@{
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
void CompleteConstruction () override
virtual ~CUIWnd ()
Protected Attributes
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Accessors //@{
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Mutators //@{
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
void SaveDefaultedOptions ()
Statics //@{
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Detailed Description
This class is a superclass of all interface windows in GG. It takes care of.
the drawing and handling of common window interfaces like the close button, minimize button, and resize handle, if applicable.
CUIWnd's contain built in close buttons. They also have optional minimize buttons. Resizable windows will have a different look from non-resizable windows.
All windows contain a close button. Pressing this button will un-register the window from the Zlist and de-allocate the memory associated with it. Thus any pointers referencing the window become invalid if the window is closed.
The minimize button functionality is available as a window creation flag: CUIWnd::MINIMIZE. You can bitwise-OR it together with regular GG::Wnd creation flags.
When the GG::Wnd::RESIZABLE flag is specified, the window will receive the resizable graphic style.
There are several things to keep in mind when utilizing these classes.
Pass the title of the window as the first argument of the constructor.
CUIWnd's do their own rendering. Do not override the render function unless you have specific needs. If you do, make sure you call CUIWnd::Render() before adding your own drawing.
Three functions are user-overridable so that new events may be responded to. OnClose() is called before the window's memory is deallocated after the user clicks the close button. OnMinimize() is called before the window becomes minimized after clicking the Minimize button. OnResize() is called as part of a response to the resize signal emitted via GG::Wnd. Users are advised to use this function instead of making a slot connection with boost::signals to respond to the resize signal.
Constructor & Destructor Documentation
CUIWnd::CUIWnd (const std::string & wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE, const std::string & config_name = "", bool visible = true)
Constructs the window to be a CUI window. Specifying config_name causes the window to save its position and other properties to the OptionsDB under that name, if no other windows are currently using that name.
References GetOptionsDB(), m_config_name, OptionsDB::Set(), and anonymous_namespace{ServerWrapper.cpp}::SetName().
CUIWnd::CUIWnd (const std::string & wnd_name, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE, const std::string & config_name = "", bool visible = true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
References anonymous_namespace{ServerWrapper.cpp}::SetName().
CUIWnd::~CUIWnd () virtual
Virtual destructor.
References ErrorLogger, GetOptionsDB(), m_config_name, m_vertex_buffer, OptionsDB::OptionExists(), and OptionsDB::Remove().
Member Function Documentation
const std::string CUIWnd::AddWindowOptions (const std::string & config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized) static protected
Adds OptionsDB entries for a window under a given name along with default values.
References OptionsDB::Add(), ErrorLogger, GetOptionsDB(), anonymous_namespace{CUIWnd.cpp}::INVALID_POS, OptionsDB::OptionExists(), OptionsDB::Remove(), and UserStringNop.
Referenced by AddWindowOptions().
const std::string CUIWnd::AddWindowOptions (const std::string & config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized) static protected
overload that accepts GG::X and GG::Y instead of ints
References AddWindowOptions().
GG::Y CUIWnd::BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
References BORDER_BOTTOM.
Referenced by CUIEditWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::DoButtonLayout(), SaveFileDialog::Init(), and ResourceInfoPanel::MinUsableSize().
GG::Rect CUIWnd::CalculatePosition () const protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented in FilterDialog, GalaxySetupWnd, FleetWnd, MultiPlayerLobbyWnd, SaveFileDialog, ServerConnectWnd, OptionsWnd, PasswordEnterWnd, and InGameMenu.
References anonymous_namespace{CUIWnd.cpp}::INVALID_X, and anonymous_namespace{CUIWnd.cpp}::INVALID_Y.
Referenced by ResetDefaultPosition().
GG::Pt CUIWnd::ClientLowerRight () const override
returns true if window is minimized
References BORDER_BOTTOM, BORDER_RIGHT, and m_minimized.
Referenced by About::DoLayout(), OptionsWnd::DoLayout(), GalaxySetupWnd::DoLayout(), GovernmentWnd::MainPanel::DoLayout(), DesignWnd::MainPanel::DoLayout(), and InitBuffers().
GG::Pt CUIWnd::ClientUpperLeft () const override
returns true if window is minimized
References BORDER_LEFT, m_minimized, and TopBorder().
Referenced by DesignWnd::MainPanel::DoLayout(), InitBuffers(), PositionButtons(), MultiPlayerLobbyWnd::Render(), and GalaxySetupWnd::Render().
void CUIWnd::Close () inline
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void CUIWnd::CloseClicked () virtual
called when window is closed via the close button
Reimplemented in MapWndPopup, FleetWnd, EncyclopediaDetailPanel, MessageWnd, ModeratorActionsWnd, PlayerListWnd, SitRepPanel, ObjectListWnd, and CombatReportWnd.
Referenced by SaveFileDialog::Cancel(), ServerConnectWnd::CancelClicked(), FleetWnd::CloseClicked(), MapWndPopup::CloseClicked(), CUIEditWnd::CompleteConstruction(), SaveFileDialog::Confirm(), InGameMenu::Exit(), InitButtons(), CUIEditWnd::KeyPress(), InGameMenu::Load(), ServerConnectWnd::OkClicked(), CUIEditWnd::OkClicked(), and InGameMenu::Save().
void CUIWnd::CompleteConstruction () override
Constructs the window to be a CUI window. Specifying config_name causes the window to save its position and other properties to the OptionsDB under that name, if no other windows are currently using that name.
References Init(), SetDefaultedOptions(), and ValidatePosition().
Referenced by InGameMenu::CompleteConstruction(), CombatReportWnd::CompleteConstruction(), PlayerListWnd::CompleteConstruction(), About::CompleteConstruction(), SitRepPanel::CompleteConstruction(), ModeratorActionsWnd::CompleteConstruction(), ObjectListWnd::CompleteConstruction(), MessageWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), SidePanel::CompleteConstruction(), SaveFileDialog::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{OptionsWnd.cpp}::FontTextureWnd::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), ResearchQueueWnd::CompleteConstruction(), BuildDesignatorWnd::BuildSelector::CompleteConstruction(), GovernmentWnd::PolicyPalette::CompleteConstruction(), ResourceInfoPanel::CompleteConstruction(), MapWndPopup::CompleteConstruction(), ProductionQueueWnd::CompleteConstruction(), FilterDialog::CompleteConstruction(), GovernmentWnd::MainPanel::CompleteConstruction(), DesignWnd::PartPalette::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), and DesignWnd::MainPanel::CompleteConstruction().
void CUIWnd::Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References SaveOptions().
Referenced by CombatReportWnd::CloseClicked(), SidePanel::CompleteConstruction(), InGameMenu::Load(), LoadOptions(), and MinimizeClicked().
void CUIWnd::Init () protected
performs initialization common to all CUIWnd constructors
References HumanClientApp::FullscreenSwitchSignal, HumanClientApp::GetApp(), InitButtons(), LoadOptions(), m_config_name, m_resizable, HumanClientApp::RepositionWindowsSignal, and ResetDefaultPosition().
Referenced by CompleteConstruction(), and ObjectPanel::Render().
void CUIWnd::InitBuffers () protected virtual
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Reimplemented in SidePanel, and EncyclopediaDetailPanel.
References ClientLowerRight(), ClientUpperLeft(), INNER_BORDER_ANGLE_OFFSET, m_buffer_indices, m_resizable, m_vertex_buffer, OUTER_EDGE_ANGLE_OFFSET, RESIZE_HASHMARK1_OFFSET, and RESIZE_HASHMARK2_OFFSET.
Referenced by Render().
void CUIWnd::InitButtons () protected virtual
called to create the buttons, withtout positioning them
References ClientUI::ArtDir(), CloseClicked(), ClientUI::GetTexture(), m_closable, m_close_button, m_minimizable, m_minimize_button, m_pin_button, m_pinable, MinimizeClicked(), PinClicked(), anonymous_namespace{CUIWnd.cpp}::PlayCloseSound(), PositionButtons(), ClientUI::TitlePts(), and ClientUI::WndInnerBorderColor().
Referenced by Init().
void CUIWnd::InitSizeMove (const GG::Pt & ul, const GG::Pt & lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
References ErrorLogger, OptionsDB::Get(), GetOptionsDB(), anonymous_namespace{CUIWnd.cpp}::INVALID_X, m_config_name, OptionsDB::OptionExists(), SaveDefaultedOptions(), OptionsDB::Set(), SetDefaultedOptions(), and SizeMove().
Referenced by ResetDefaultPosition().
int CUIWnd::InnerBorderAngleOffset () const protected
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
References INNER_BORDER_ANGLE_OFFSET.
bool CUIWnd::InResizeTab (const GG::Pt & pt) const protected
returns true iff the specified pt is in the region where dragging will resize this Wnd
References BORDER_BOTTOM, BORDER_RIGHT, INNER_BORDER_ANGLE_OFFSET, m_minimized, and m_resizable.
Referenced by LButtonDown(), MouseEnter(), and MouseHere().
void CUIWnd::InvalidateUnusedOptions () static
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
References OptionsDB::Commit(), OptionsDB::FindOptions(), GetOptionsDB(), InvalidateWindowOptions(), OptionsDB::OptionExists(), OptionsDB::RemoveUnrecognized(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
Referenced by ClientUI::ClientUI().
void CUIWnd::InvalidateWindowOptions (const std::string & config_name) static protected
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
References ErrorLogger, OptionsDB::Get(), OptionsDB::GetDefault(), GetOptionsDB(), anonymous_namespace{CUIWnd.cpp}::INVALID_POS, OptionsDB::OptionExists(), and OptionsDB::Set().
Referenced by InvalidateUnusedOptions().
bool CUIWnd::InWindow (const GG::Pt & pt) const override
returns true if window is minimized
References m_resizable, and OUTER_EDGE_ANGLE_OFFSET.
void CUIWnd::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References InResizeTab(), and m_drag_offset.
void CUIWnd::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References m_drag_offset, and SaveOptions().
void CUIWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Referenced by TechTreeWnd::LayoutPanel::TechPanel::LButtonUp(), FleetWnd::LClick(), GovernmentWnd::MainPanel::LClick(), and DesignWnd::MainPanel::LClick().
void CUIWnd::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References m_drag_offset, and m_pinned.
GG::X CUIWnd::LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
References BORDER_LEFT.
Referenced by CUIEditWnd::CompleteConstruction(), SaveFileDialog::Init(), and ResourceInfoPanel::MinUsableSize().
void CUIWnd::LoadOptions () protected
loads options for this window from the OptionsDB
References ErrorLogger, OptionsDB::Get(), GetOptionsDB(), Hide(), anonymous_namespace{CUIWnd.cpp}::INVALID_X, anonymous_namespace{CUIWnd.cpp}::INVALID_Y, m_config_name, m_config_save, m_minimized, m_pinned, MinimizeClicked(), OptionsDB::OptionExists(), PinClicked(), ResetDefaultPosition(), Show(), and SizeMove().
Referenced by Init().
void CUIWnd::MinimizeClicked () protected virtual
called when window is minimized or restored via the minimize/restore button
References BORDER_BOTTOM, Hide(), INNER_BORDER_ANGLE_OFFSET, m_close_button, m_minimize_button, m_minimized, m_original_size, m_pin_button, MinimizedSize(), SaveOptions(), Show(), and TopBorder().
Referenced by InitButtons(), and LoadOptions().
bool CUIWnd::Minimized () const inline
returns true if window is minimized
References CUI_MinRestoreButton::Render().
GG::Pt CUIWnd::MinimizedSize () const protected virtual
the size of a minimized CUIWnd
References MINIMIZED_WND_WIDTH, and TopBorder().
Referenced by FleetWnd::CompleteConstruction(), MinimizeClicked(), and SizeMove().
void CUIWnd::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References InResizeTab(), and m_mouse_in_resize_tab.
Referenced by TechTreeWnd::LayoutPanel::TechPanel::LButtonUp().
void CUIWnd::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References InResizeTab(), and m_mouse_in_resize_tab.
void CUIWnd::MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References m_mouse_in_resize_tab.
Referenced by TechTreeWnd::LayoutPanel::TechPanel::LButtonUp().
void CUIWnd::PinClicked () virtual
called when window is pinned or unpinned via the pin button
References m_pin_button, m_pinned, m_resizable, m_vertex_buffer, and SaveOptions().
Referenced by InitButtons(), and LoadOptions().
void CUIWnd::PositionButtons () protected virtual
called to position the buttons
References BORDER_RIGHT, BUTTON_TOP_OFFSET, ClientUpperLeft(), m_close_button, m_minimize_button, m_pin_button, ClientUI::Pts(), and ClientUI::TitlePts().
Referenced by EncyclopediaDetailPanel::DoLayout(), InitButtons(), and SizeMove().
void CUIWnd::Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References BORDER_LEFT, ClientUI::GetTitleFont(), InitBuffers(), m_buffer_indices, m_minimized, m_mouse_in_resize_tab, m_resizable, m_vertex_buffer, anonymous_namespace{XMLDoc.cpp}::Name, ClientUI::TextColor(), TITLE_OFFSET, ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
Referenced by MultiPlayerLobbyWnd::Render(), EncyclopediaDetailPanel::Render(), GalaxySetupWnd::Render(), TechTreeWnd::TechTreeControls::Render(), and PolicySlotControl::SlotIndex().
void CUIWnd::ResetDefaultPosition () protected
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
References CalculatePosition(), InitSizeMove(), and anonymous_namespace{CUIWnd.cpp}::INVALID_X.
Referenced by InGameMenu::CompleteConstruction(), PasswordEnterWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), FilterDialog::CompleteConstruction(), SaveFileDialog::Init(), Init(), and LoadOptions().
GG::X CUIWnd::RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
References BORDER_RIGHT.
Referenced by CUIEditWnd::CompleteConstruction(), SaveFileDialog::Init(), and ResourceInfoPanel::MinUsableSize().
void CUIWnd::SaveDefaultedOptions () protected
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value
References OptionsDB::Get(), GetOptionsDB(), m_config_name, m_defaulted_options, m_minimized, m_original_size, m_pinned, and OptionsDB::SetDefault().
Referenced by ModeratorActionsWnd::CompleteConstruction(), MessageWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), BuildDesignatorWnd::BuildSelector::CompleteConstruction(), GovernmentWnd::PolicyPalette::CompleteConstruction(), FilterDialog::CompleteConstruction(), GovernmentWnd::MainPanel::CompleteConstruction(), DesignWnd::PartPalette::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), DesignWnd::MainPanel::CompleteConstruction(), SaveFileDialog::Init(), and InitSizeMove().
void CUIWnd::SaveOptions () const protected
saves options for this window to the OptionsDB if config_name was specified in the constructor
References OptionsDB::Commit(), ErrorLogger, OptionsDB::Get(), GetOptionsDB(), m_config_name, m_config_save, m_minimized, m_original_size, m_pinned, OptionsDB::OptionExists(), and OptionsDB::Set().
Referenced by OptionsWnd::CompleteConstruction(), FleetWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), FilterDialog::CompleteConstruction(), Hide(), SaveFileDialog::Init(), LButtonUp(), MinimizeClicked(), PinClicked(), Show(), and SizeMove().
void CUIWnd::SetDefaultedOptions () protected
Flags options currently at their default values for later use in SaveDefaultedOptions
References OptionsDB::FindOptions(), GetOptionsDB(), OptionsDB::IsDefaultValue(), m_config_name, and m_defaulted_options.
Referenced by CompleteConstruction(), and InitSizeMove().
void CUIWnd::SetParent (const std::shared_ptr< GG::Wnd > & wnd) override protected
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References CUIEditWnd::BUTTON_WIDTH, CUIEditWnd::CONTROL_MARGIN, and m_vertex_buffer.
void CUIWnd::Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References SaveOptions().
Referenced by LoadOptions(), MinimizeClicked(), and MapWndPopup::~MapWndPopup().
void CUIWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References BORDER_BOTTOM, ErrorLogger, HumanClientApp::GetApp(), INNER_BORDER_ANGLE_OFFSET, m_config_save, m_vertex_buffer, MinimizedSize(), PositionButtons(), SaveOptions(), and TopBorder().
Referenced by InitSizeMove(), LoadOptions(), CombatReportWnd::SizeMove(), ObjectListWnd::SizeMove(), PlayerListWnd::SizeMove(), MessageWnd::SizeMove(), SitRepPanel::SizeMove(), ModeratorActionsWnd::SizeMove(), OptionsWnd::SizeMove(), MultiPlayerLobbyWnd::SizeMove(), EncyclopediaDetailPanel::SizeMove(), SidePanel::SizeMove(), FleetWnd::SizeMove(), GalaxySetupWnd::SizeMove(), TechTreeWnd::TechTreeControls::SizeMove(), anonymous_namespace{OptionsWnd.cpp}::FontTextureWnd::SizeMove(), ResearchQueueWnd::SizeMove(), BuildDesignatorWnd::BuildSelector::SizeMove(), GovernmentWnd::PolicyPalette::SizeMove(), ResourceInfoPanel::SizeMove(), ProductionQueueWnd::SizeMove(), GovernmentWnd::MainPanel::SizeMove(), DesignWnd::PartPalette::SizeMove(), DesignWnd::BaseSelector::SizeMove(), DesignWnd::MainPanel::SizeMove(), and ValidatePosition().
void CUIWnd::ToggleMinimized () inline
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
GG::Y CUIWnd::TopBorder () const
the distance at the top between the outer edge of the window and the inner border
References ClientUI::TitlePts().
Referenced by ClientUpperLeft(), FleetWnd::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::DoButtonLayout(), SaveFileDialog::Init(), MinimizeClicked(), MinimizedSize(), ResourceInfoPanel::MinUsableSize(), and SizeMove().
void CUIWnd::ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
References SizeMove().
Referenced by CompleteConstruction().
Member Data Documentation
const GG::Y CUIWnd::BORDER_BOTTOM static protected
Referenced by BottomBorder(), ClientLowerRight(), SidePanel::ClientUpperLeft(), FleetWnd::CompleteConstruction(), EncyclopediaDetailPanel::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InResizeTab(), MinimizeClicked(), SizeMove(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const GG::X CUIWnd::BORDER_LEFT static protected
Referenced by SidePanel::ClientUpperLeft(), ClientUpperLeft(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::DoLayout(), SidePanel::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), LeftBorder(), Render(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const GG::X CUIWnd::BORDER_RIGHT static protected
Referenced by ClientLowerRight(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InResizeTab(), PositionButtons(), RightBorder(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const GG::X CUIWnd::BUTTON_RIGHT_OFFSET static protected
const GG::Y CUIWnd::BUTTON_TOP_OFFSET static protected
Referenced by PositionButtons(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const int CUIWnd::INNER_BORDER_ANGLE_OFFSET = 11 static protected
Referenced by FleetWnd::CompleteConstruction(), PlayerListWnd::DoLayout(), SitRepPanel::DoLayout(), MessageWnd::DoLayout(), CombatReportWnd::Impl::DoLayout(), SidePanel::DoLayout(), FleetWnd::DoLayout(), ResearchQueueWnd::DoLayout(), BuildDesignatorWnd::BuildSelector::DoLayout(), ProductionQueueWnd::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), InnerBorderAngleOffset(), InResizeTab(), MinimizeClicked(), SizeMove(), CombatReportWnd::Impl::UpdateMinSize(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
std::vector<std::pair<std::size_t, std::size_t> > CUIWnd::m_buffer_indices protected
Referenced by EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), EncyclopediaDetailPanel::Render(), and Render().
bool CUIWnd::m_closable protected
true if the window is able to be closed with a button press
Referenced by InitButtons().
std::shared_ptr<GG::Button> CUIWnd::m_close_button = nullptr protected
the close button
Referenced by EncyclopediaDetailPanel::DoLayout(), InitButtons(), MinimizeClicked(), and PositionButtons().
const std::string CUIWnd::m_config_name protected
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
Referenced by CUIWnd(), Init(), InitSizeMove(), LoadOptions(), SaveDefaultedOptions(), SaveOptions(), SetDefaultedOptions(), and ~CUIWnd().
bool CUIWnd::m_config_save = true protected
true if SaveOptions() is currently allowed to write to the OptionsDB
Referenced by LoadOptions(), SaveOptions(), SizeMove(), and TechTreeWnd::TechTreeControls::SizeMove().
std::unordered_set<std::string> CUIWnd::m_defaulted_options protected
Referenced by SaveDefaultedOptions(), and SetDefaultedOptions().
GG::Pt CUIWnd::m_drag_offset protected
offset from the lower-right corner of the point being used to drag-resize
Referenced by LButtonDown(), LButtonUp(), LDrag(), and TechTreeWnd::TechTreeControls::LDrag().
bool CUIWnd::m_minimizable protected
true if the window is able to be minimized
Referenced by InitButtons().
std::shared_ptr<CUI_MinRestoreButton> CUIWnd::m_minimize_button = nullptr protected
the minimize/restore button
Referenced by InitButtons(), MinimizeClicked(), and PositionButtons().
bool CUIWnd::m_minimized = false protected
true if the window is currently minimized
Referenced by ClientLowerRight(), ClientUpperLeft(), InResizeTab(), LoadOptions(), MinimizeClicked(), EncyclopediaDetailPanel::Render(), Render(), SaveDefaultedOptions(), and SaveOptions().
bool CUIWnd::m_mouse_in_resize_tab = false protected
Referenced by MouseEnter(), MouseHere(), MouseLeave(), and Render().
GG::Pt CUIWnd::m_original_size protected
keeps track of the size of the window before resizing
Referenced by MinimizeClicked(), SaveDefaultedOptions(), and SaveOptions().
std::shared_ptr<CUI_PinButton> CUIWnd::m_pin_button = nullptr protected
the pin button
Referenced by InitButtons(), MinimizeClicked(), PinClicked(), and PositionButtons().
bool CUIWnd::m_pinable protected
true if the window is able to be pinned
Referenced by InitButtons().
bool CUIWnd::m_pinned = false protected
true if the window is currently pinned
Referenced by LDrag(), LoadOptions(), PinClicked(), SaveDefaultedOptions(), and SaveOptions().
bool CUIWnd::m_resizable protected
true if the window is able to be resized
Referenced by Init(), EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), InResizeTab(), InWindow(), PinClicked(), and Render().
GG::GL2DVertexBuffer CUIWnd::m_vertex_buffer protected
Referenced by EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), PinClicked(), EncyclopediaDetailPanel::Render(), Render(), SetParent(), SizeMove(), and ~CUIWnd().
const GG::X CUIWnd::MINIMIZED_WND_WIDTH static protected
Referenced by MinimizedSize(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const int CUIWnd::OUTER_EDGE_ANGLE_OFFSET = 8 static protected
Referenced by EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), InWindow(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const int CUIWnd::RESIZE_HASHMARK1_OFFSET = 7 static protected
Referenced by EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const int CUIWnd::RESIZE_HASHMARK2_OFFSET = 3 static protected
Referenced by EncyclopediaDetailPanel::InitBuffers(), SidePanel::InitBuffers(), InitBuffers(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
const int CUIWnd::TITLE_OFFSET = 3 static protected
Referenced by Render(), and anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption().
The documentation for this class was generated from the following files:
CUIWnd.h
CUIWnd.cpp