FreeOrion: CUIRadioRepresenter Class Reference
CUIRadioRepresenter Class Reference
A FreeOrion styled radio state button.
#include <CUIControls.h>
Public Member Functions
void OnChanged (const GG::StateButton &button, GG::StateButton::ButtonState prev_state) const override
void OnChecked (bool checked) const override
void Render (const GG::StateButton &button) const override
Detailed Description
A FreeOrion styled radio state button.
Member Function Documentation
OnChanged()
void CUIRadioRepresenter::OnChanged (const GG::StateButton & button, GG::StateButton::ButtonState prev_state) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
OnChecked()
void CUIRadioRepresenter::OnChecked (bool checked) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Render()
void CUIRadioRepresenter::Render (const GG::StateButton & button) const override
References AdjustBrightness(), ClientUI::CtrlBorderColor(), anonymous_namespace{ProductionWnd.cpp}::MARGIN, and anonymous_namespace{CUIControls.cpp}::STATE_BUTTON_BRIGHTENING_SCALE_FACTOR.
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp