FreeOrion: SidePanel::SystemNameDropDownList Class Reference
SidePanel::SystemNameDropDownList Class Reference
A class to display all of the system names.
Public Member Functions
SystemNameDropDownList (size_t num_shown_elements)
void EnableOrderIssuing (bool enable=true)
Enable/disable the ability to give orders that modify the system name.
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Public Member Functions inherited from CUIDropDownList
GG::Pt ClientLowerRight () const override
GG::X DroppedRowWidth () const override
Return the width of the dropped row which excludes the DropArrow.
CUIDropDownList (size_t num_shown_elements)
void Render () override
disables rendering of the small downward-facing arrow on the right of the control
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseLeave () override
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Public Attributes
bool m_order_issuing_enabled
Detailed Description
A class to display all of the system names.
Constructor & Destructor Documentation
SystemNameDropDownList()
SidePanel::SystemNameDropDownList::SystemNameDropDownList (size_t num_shown_elements) inline
Member Function Documentation
EnableOrderIssuing()
void SidePanel::SystemNameDropDownList::EnableOrderIssuing (bool enable = true) inline
Enable/disable the ability to give orders that modify the system name.
RClick()
void SidePanel::SystemNameDropDownList::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
References RenameOrder::Check(), ClientUI::EditHiliteColor(), ClientApp::EmpireID(), AIInterface::EmpireID(), HumanClientApp::GetApp(), ClientUI::GetFont(), GetSystem(), OrderSet::IssueOrder(), ClientApp::Orders(), ClientUI::TextColor(), UserString(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
Member Data Documentation
m_order_issuing_enabled
bool SidePanel::SystemNameDropDownList::m_order_issuing_enabled
The documentation for this class was generated from the following file:
SidePanel.cpp