FreeOrion: SystemResourceSummaryBrowseWnd Class Reference
SystemResourceSummaryBrowseWnd Class Reference
Gives information about inporting and exporting of resources to and from this system when mousing over the system resource production summary.
#include <SystemResourceSummaryBrowseWnd.h>
Public Member Functions
SystemResourceSummaryBrowseWnd (ResourceType resource_type, int system_id, int empire_id=ALL_EMPIRES)
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Member Functions
void Clear ()
void Initialize ()
void UpdateAllocation (GG::Y &top)
void UpdateImpl (std::size_t mode, const GG::Wnd *target) override
void UpdateImportExport (GG::Y &top)
void UpdateProduction (GG::Y &top)
Private Attributes
GG::Y allocation_label_top
GG::Y import_export_label_top
double m_allocation = 0.0
std::shared_ptr< GG::Label > m_allocation_label
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_allocation_labels_and_amounts
int m_empire_id = ALL_EMPIRES
std::shared_ptr< GG::Label > m_import_export_label
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_import_export_labels_and_amounts
double m_production = 0.0
std::shared_ptr< GG::Label > m_production_label
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_production_labels_and_amounts
ResourceType m_resource_type {0}
int m_system_id = INVALID_OBJECT_ID
GG::Y production_label_top
GG::Y row_height
Detailed Description
Gives information about inporting and exporting of resources to and from this system when mousing over the system resource production summary.
Constructor & Destructor Documentation
SystemResourceSummaryBrowseWnd()
SystemResourceSummaryBrowseWnd::SystemResourceSummaryBrowseWnd (ResourceType resource_type, int system_id, int empire_id = ALL_EMPIRES)
Member Function Documentation
Clear()
void SystemResourceSummaryBrowseWnd::Clear () private
References m_allocation_label, m_allocation_labels_and_amounts, m_import_export_label, m_import_export_labels_and_amounts, m_production_label, and m_production_labels_and_amounts.
Referenced by UpdateImpl().
Initialize()
void SystemResourceSummaryBrowseWnd::Initialize () private
References allocation_label_top, anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::EDGE_PAD(), ClientUI::GetBoldFont(), import_export_label_top, anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth(), m_allocation_label, m_import_export_label, m_production_label, production_label_top, ClientUI::Pts(), row_height, UpdateAllocation(), UpdateImportExport(), UpdateProduction(), and anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth().
Referenced by UpdateImpl().
Render()
void SystemResourceSummaryBrowseWnd::Render () override
References allocation_label_top, import_export_label_top, OpaqueColor(), production_label_top, row_height, ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
UpdateAllocation()
void SystemResourceSummaryBrowseWnd::UpdateAllocation (GG::Y & top) private
References ALL_EMPIRES, DoubleToString(), ErrorLogger, ObjectMap::find(), FlexibleFormat(), ObjectMap::get(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth(), m_allocation, m_allocation_label, m_allocation_labels_and_amounts, m_empire_id, m_resource_type, m_system_id, anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), Objects(), row_height, UserString(), and anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth().
Referenced by Initialize().
UpdateImpl()
void SystemResourceSummaryBrowseWnd::UpdateImpl (std::size_t mode, const GG::Wnd * target) override private
References Clear(), and Initialize().
UpdateImportExport()
void SystemResourceSummaryBrowseWnd::UpdateImportExport (GG::Y & top) private
References ALL_EMPIRES, DoubleToString(), GetEmpire(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth(), m_allocation, m_empire_id, m_import_export_label, m_import_export_labels_and_amounts, m_production, m_resource_type, row_height, UserString(), and anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth().
Referenced by Initialize().
UpdateProduction()
void SystemResourceSummaryBrowseWnd::UpdateProduction (GG::Y & top) private
References ALL_EMPIRES, DoubleToString(), ObjectMap::find(), FlexibleFormat(), ObjectMap::get(), ResourceCenter::GetMeter(), Meter::Initial(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth(), m_empire_id, m_production, m_production_label, m_production_labels_and_amounts, m_resource_type, m_system_id, Objects(), ResourceToMeter(), row_height, UserString(), and anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth().
Referenced by Initialize().
WndHasBrowseInfo()
bool SystemResourceSummaryBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
allocation_label_top
GG::Y SystemResourceSummaryBrowseWnd::allocation_label_top private
Referenced by Initialize(), and Render().
import_export_label_top
GG::Y SystemResourceSummaryBrowseWnd::import_export_label_top private
Referenced by Initialize(), and Render().
m_allocation
double SystemResourceSummaryBrowseWnd::m_allocation = 0.0 private
Referenced by UpdateAllocation(), and UpdateImportExport().
m_allocation_label
std::shared_ptr<GG::Label> SystemResourceSummaryBrowseWnd::m_allocation_label private
Referenced by Clear(), Initialize(), and UpdateAllocation().
m_allocation_labels_and_amounts
std::vector<std::pair<std::shared_ptr<GG::Label>, std::shared_ptr<GG::Label> > > SystemResourceSummaryBrowseWnd::m_allocation_labels_and_amounts private
Referenced by Clear(), and UpdateAllocation().
m_empire_id
int SystemResourceSummaryBrowseWnd::m_empire_id = ALL_EMPIRES private
Referenced by UpdateAllocation(), UpdateImportExport(), and UpdateProduction().
m_import_export_label
std::shared_ptr<GG::Label> SystemResourceSummaryBrowseWnd::m_import_export_label private
Referenced by Clear(), Initialize(), and UpdateImportExport().
m_import_export_labels_and_amounts
std::vector<std::pair<std::shared_ptr<GG::Label>, std::shared_ptr<GG::Label> > > SystemResourceSummaryBrowseWnd::m_import_export_labels_and_amounts private
Referenced by Clear(), and UpdateImportExport().
m_production
double SystemResourceSummaryBrowseWnd::m_production = 0.0 private
Referenced by UpdateImportExport(), and UpdateProduction().
m_production_label
std::shared_ptr<GG::Label> SystemResourceSummaryBrowseWnd::m_production_label private
Referenced by Clear(), Initialize(), and UpdateProduction().
m_production_labels_and_amounts
std::vector<std::pair<std::shared_ptr<GG::Label>, std::shared_ptr<GG::Label> > > SystemResourceSummaryBrowseWnd::m_production_labels_and_amounts private
Referenced by Clear(), and UpdateProduction().
m_resource_type
ResourceType SystemResourceSummaryBrowseWnd::m_resource_type {0} private
Referenced by UpdateAllocation(), UpdateImportExport(), and UpdateProduction().
m_system_id
int SystemResourceSummaryBrowseWnd::m_system_id = INVALID_OBJECT_ID private
Referenced by UpdateAllocation(), and UpdateProduction().
production_label_top
GG::Y SystemResourceSummaryBrowseWnd::production_label_top private
Referenced by Initialize(), and Render().
row_height
GG::Y SystemResourceSummaryBrowseWnd::row_height private
Referenced by Initialize(), Render(), UpdateAllocation(), UpdateImportExport(), and UpdateProduction().
The documentation for this class was generated from the following files:
SystemResourceSummaryBrowseWnd.h
SystemResourceSummaryBrowseWnd.cpp