FreeOrion: anonymous_namespace{FleetWnd.cpp}::ShipDataPanel Class Reference
anonymous_namespace{FleetWnd.cpp}::ShipDataPanel Class Reference
Shows info about a single ship.
Public Member Functions
ShipDataPanel (GG::X w, GG::Y h, int ship_id)
~ShipDataPanel ()
GG::Pt ClientLowerRight () const override
Excludes border from the client area.
GG::Pt ClientUpperLeft () const override
Excludes border from the client area.
void PreRender () override
void Render () override
Renders black panel background, border with color depending on the current state and a background for the ship's name text.
void RequireRefresh ()
Indicate ship data has changed and needs refresh.
void Select (bool b)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Member Functions
void DoLayout ()
void Init ()
void Refresh ()
void SetShipIcon ()
double StatValue (MeterType stat_name) const
Private Attributes
std::shared_ptr< GG::Label > m_design_name_text
boost::signals2::connection m_fleet_connection
bool m_initialized = false
bool m_needs_refresh = true
std::shared_ptr< ScanlineControl > m_scanline_control
An overlays for orders like scrap, colonize, invade, bombard destroy etc.
bool m_selected = false
statistic icons and associated meter types
boost::signals2::connection m_ship_connection
std::shared_ptr< GG::StaticGraphic > m_ship_icon
std::vector< std::shared_ptr< GG::StaticGraphic > > m_ship_icon_overlays
int m_ship_id = INVALID_OBJECT_ID
std::shared_ptr< GG::Label > m_ship_name_text
std::vector< std::pair< MeterType, std::shared_ptr< StatisticIcon > > > m_stat_icons
Detailed Description
Shows info about a single ship.
Constructor & Destructor Documentation
ShipDataPanel()
anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::ShipDataPanel (GG::X w, GG::Y h, int ship_id)
References RequireRefresh().
~ShipDataPanel()
anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::~ShipDataPanel ()
References m_fleet_connection, and m_ship_connection.
Member Function Documentation
ClientLowerRight()
GG::Pt anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::ClientLowerRight () const override
Excludes border from the client area.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
ClientUpperLeft()
GG::Pt anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::ClientUpperLeft () const override
Excludes border from the client area.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
Referenced by Render().
DoLayout()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::DoLayout () private
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_TEXT_PAD, anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_design_name_text, m_ship_icon, m_ship_icon_overlays, m_ship_name_text, m_stat_icons, and anonymous_namespace{FleetWnd.cpp}::StatIconSize().
Referenced by PreRender().
Init()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init () private
References anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), anonymous_namespace{FleetWnd.cpp}::DamageIcon(), anonymous_namespace{FleetWnd.cpp}::FightersIcon(), FlexibleFormat(), ObjectMap::get(), OptionsDB::Get(), ClientUI::GetClientUI(), GetOptionsDB(), anonymous_namespace{FleetWnd.cpp}::IndustryIcon(), anonymous_namespace{FleetWnd.cpp}::InfluenceIcon(), m_design_name_text, m_fleet_connection, m_initialized, m_ship_connection, m_ship_id, m_ship_name_text, m_stat_icons, ClientUI::MeterIcon(), Objects(), RequireRefresh(), anonymous_namespace{FleetWnd.cpp}::ResearchIcon(), anonymous_namespace{FleetWnd.cpp}::StatIconSize(), to_string(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), UserString(), and ClientUI::ZoomToMeterTypeArticle().
Referenced by PreRender().
PreRender()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::PreRender () override
References DoLayout(), Init(), m_initialized, m_needs_refresh, and Refresh().
Refresh()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh () private
References AssociatedMeterType(), anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), ClientApp::EmpireID(), FlexibleFormat(), ObjectMap::get(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), m_design_name_text, m_needs_refresh, m_ship_id, m_ship_name_text, m_stat_icons, ShipDesign::Name(), Objects(), SetShipIcon(), StatValue(), to_string(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), and UserString().
Referenced by PreRender().
Render()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render () override
Renders black panel background, border with color depending on the current state and a background for the ship's name text.
References ClientUpperLeft(), anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER, anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_selected, ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
RequireRefresh()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::RequireRefresh ()
Indicate ship data has changed and needs refresh.
References m_needs_refresh.
Referenced by Init(), and ShipDataPanel().
Select()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Select (bool b)
References m_design_name_text, m_selected, m_ship_name_text, and ClientUI::TextColor().
SetShipIcon()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon () private
References ClientUI::ArtDir(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconStyle(), ClientApp::EmpireID(), ObjectMap::get(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetOptionsDB(), ClientUI::GetTexture(), ShipDesign::ID(), INVALID_OBJECT_ID, m_scanline_control, m_ship_icon, m_ship_icon_overlays, m_ship_id, Objects(), and ClientUI::ShipDesignIcon().
Referenced by Refresh().
SizeMove()
void anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
StatValue()
double anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::StatValue (MeterType stat_name) const private
References ErrorLogger, m_ship_id, and Objects().
Referenced by Refresh().
Member Data Documentation
m_design_name_text
std::shared_ptr<GG::Label> anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_design_name_text private
Referenced by DoLayout(), Init(), Refresh(), and Select().
m_fleet_connection
boost::signals2::connection anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_fleet_connection private
Referenced by Init(), and ~ShipDataPanel().
m_initialized
bool anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_initialized = false private
Referenced by Init(), and PreRender().
m_needs_refresh
bool anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_needs_refresh = true private
Referenced by PreRender(), Refresh(), and RequireRefresh().
m_scanline_control
std::shared_ptr<ScanlineControl> anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_scanline_control private
An overlays for orders like scrap, colonize, invade, bombard destroy etc.
Referenced by SetShipIcon().
m_selected
bool anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_selected = false private
statistic icons and associated meter types
Referenced by Render(), and Select().
m_ship_connection
boost::signals2::connection anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_ship_connection private
Referenced by Init(), and ~ShipDataPanel().
m_ship_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_ship_icon private
Referenced by DoLayout(), and SetShipIcon().
m_ship_icon_overlays
std::vector<std::shared_ptr<GG::StaticGraphic> > anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_ship_icon_overlays private
Referenced by DoLayout(), and SetShipIcon().
m_ship_id
int anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_ship_id = INVALID_OBJECT_ID private
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipRow::CompleteConstruction(), Init(), Refresh(), SetShipIcon(), anonymous_namespace{FleetWnd.cpp}::ShipRow::ShipID(), anonymous_namespace{FleetWnd.cpp}::ShipRow::ShipRow(), and StatValue().
m_ship_name_text
std::shared_ptr<GG::Label> anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_ship_name_text private
Referenced by DoLayout(), Init(), Refresh(), and Select().
m_stat_icons
std::vector<std::pair<MeterType, std::shared_ptr<StatisticIcon> > > anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::m_stat_icons private
Referenced by DoLayout(), Init(), and Refresh().
The documentation for this class was generated from the following file:
FleetWnd.cpp