FreeOrion: SpeciesManager Class Reference
SpeciesManager Class Reference
Holds all FreeOrion species.
#include <Species.h>
Classes
struct NativeSpecies
struct PlayableSpecies
Public Types
using CensusOrder = std::vector< std::string >
using iterator = SpeciesTypeMap::const_iterator
typedef boost::filter_iterator< NativeSpecies, iterator > native_iterator
typedef boost::filter_iterator< PlayableSpecies, iterator > playable_iterator
using SpeciesTypeMap = std::map< std::string, std::unique_ptr< Species > >
Public Member Functions
SpeciesManager ()=default
void AddSpeciesHomeworld (std::string species, int homeworld_id)
iterator begin () const
iterators for all species
const CensusOrder & census_order () const
returns an ordered list of tags that should be considered for census listings.
void ClearSpeciesHomeworlds ()
void ClearSpeciesOpinions ()
bool empty () const
returns true iff this SpeciesManager is empty.
iterator end () const
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
const Species * GetSpecies (const std::string &name) const
returns the building type with the name name; you should use the free function GetSpecies() instead, mainly to save some typing.
Species * GetSpecies (const std::string &name)
const std::map< std::string, std::map< int, float > > & GetSpeciesEmpireOpinionsMap (int encoding_empire=ALL_EMPIRES) const
returns a map from species name to a map from empire id to each the species' opinion of the empire
std::map< std::string, std::set< int > > GetSpeciesHomeworldsMap (int encoding_empire=ALL_EMPIRES) const
returns a map from species name to a set of object IDs that are the homeworld(s) of that species in the current game.
const std::map< std::string, std::map< std::string, float > > & GetSpeciesSpeciesOpinionsMap (int encoding_empire=ALL_EMPIRES) const
returns a map from species name to a map from other species names to the opinion of the first species about the other species.
native_iterator native_begin () const
iterators for native species.
native_iterator native_end () const
int NumNativeSpecies () const
int NumPlayableSpecies () const
int NumSpecies () const
returns the number of species stored in this manager.
playable_iterator playable_begin () const
iterators for playble species.
playable_iterator playable_end () const
const std::string & RandomPlayableSpeciesName () const
returns the name of a playable species in this manager, or an empty string if there are no playable species.
const std::string & RandomSpeciesName () const
returns the name of a species in this manager, or an empty string if this manager is empty.
void RemoveSpeciesHomeworld (const std::string &species, int homeworld_id)
const std::string & SequentialPlayableSpeciesName (int id) const
void SetSpeciesEmpireOpinion (const std::string &species_name, int empire_id, float opinion)
void SetSpeciesEmpireOpinions (std::map< std::string, std::map< int, float >> &&species_empire_opinions)
sets the opinions of species (indexed by name string) of empires (indexed by id) as a double-valued number.
void SetSpeciesSpeciesOpinion (const std::string &opinionated_species, const std::string &rated_species, float opinion)
void SetSpeciesSpeciesOpinions (std::map< std::string, std::map< std::string, float >> &&species_species_opinions)
sets the opinions of species (indexed by name string) of other species (indexed by name string) as a double-valued number.
void SetSpeciesTypes (Pending::Pending< std::pair< SpeciesTypeMap, CensusOrder >> &&future)
Sets species types to the value of future.
float SpeciesEmpireOpinion (const std::string &species_name, int empire_id) const
returns opinion of species with name species_name about empire with id empire_id or 0.0 if there is no such opinion yet recorded.
std::map< std::string, std::map< int, float > > & SpeciesObjectPopulations (int encoding_empire=ALL_EMPIRES)
std::map< std::string, std::map< std::string, int > > & SpeciesShipsDestroyed (int encoding_empire=ALL_EMPIRES)
float SpeciesSpeciesOpinion (const std::string &opinionated_species_name, const std::string &rated_species_name) const
returns opinion of species with name opinionated_species_name about other species with name rated_species_name or 0.0 if there is no such opinion yet recorded.
std::vector< std::string > SpeciesThatDislike (const std::string &content_name) const
std::vector< std::string > SpeciesThatLike (const std::string &content_name) const
void UpdatePopulationCounter ()
Private Member Functions
void SetSpeciesHomeworlds (std::map< std::string, std::set< int >> &&species_homeworld_ids)
sets the homeworld ids of species in this SpeciesManager to those specified in species_homeworld_ids
Static Private Member Functions
static void CheckPendingSpeciesTypes ()
Assigns any m_pending_types to m_species.
Private Attributes
std::map< std::string, std::map< int, float > > m_species_empire_opinions
std::map< std::string, std::set< int > > m_species_homeworlds
std::map< std::string, std::map< int, float > > m_species_object_populations
std::map< std::string, std::map< std::string, float > > m_species_species_opinions
std::map< std::string, std::map< std::string, int > > m_species_species_ships_destroyed
Friends
template<typename Archive >
void serialize (Archive &, SpeciesManager &, unsigned int const)
Detailed Description
Holds all FreeOrion species.
Types may be looked up by name.
Member Typedef Documentation
CensusOrder
using SpeciesManager::CensusOrder = std::vector<std::string>
iterator
using SpeciesManager::iterator = SpeciesTypeMap::const_iterator
native_iterator
typedef boost::filter_iterator<NativeSpecies, iterator> SpeciesManager::native_iterator
playable_iterator
typedef boost::filter_iterator<PlayableSpecies, iterator> SpeciesManager::playable_iterator
SpeciesTypeMap
using SpeciesManager::SpeciesTypeMap = std::map<std::string, std::unique_ptr<Species> >
Constructor & Destructor Documentation
SpeciesManager()
SpeciesManager::SpeciesManager () default
Member Function Documentation
AddSpeciesHomeworld()
void SpeciesManager::AddSpeciesHomeworld (std::string species, int homeworld_id)
References INVALID_OBJECT_ID.
Referenced by SetEmpireHomeworld(), and anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld().
begin()
SpeciesManager::iterator SpeciesManager::begin () const
iterators for all species
References anonymous_namespace{Species.cpp}::s_species.
census_order()
const SpeciesManager::CensusOrder & SpeciesManager::census_order () const
returns an ordered list of tags that should be considered for census listings.
References anonymous_namespace{Species.cpp}::s_census_order.
CheckPendingSpeciesTypes()
void SpeciesManager::CheckPendingSpeciesTypes () static private
Assigns any m_pending_types to m_species.
References ErrorLogger, anonymous_namespace{Species.cpp}::s_census_order, anonymous_namespace{Species.cpp}::s_pending_types, anonymous_namespace{Species.cpp}::s_species, anonymous_namespace{Species.cpp}::species_mutex, and Pending::SwapPending().
ClearSpeciesHomeworlds()
void SpeciesManager::ClearSpeciesHomeworlds ()
Referenced by ServerApp::GenerateUniverse().
ClearSpeciesOpinions()
void SpeciesManager::ClearSpeciesOpinions ()
empty()
bool SpeciesManager::empty () const
returns true iff this SpeciesManager is empty.
References anonymous_namespace{Species.cpp}::s_species.
end()
SpeciesManager::iterator SpeciesManager::end () const
References anonymous_namespace{Species.cpp}::s_species.
GetCheckSum()
unsigned int SpeciesManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), DebugLogger, and anonymous_namespace{Species.cpp}::s_species.
Referenced by CheckSumContent().
GetSpecies() [1/2]
const Species * SpeciesManager::GetSpecies (const std::string & name) const
returns the building type with the name name; you should use the free function GetSpecies() instead, mainly to save some typing.
References anonymous_namespace{Species.cpp}::s_species.
Referenced by ValueRef::ComplexVariable< T >::Eval(), ServerApp::GetSpecies(), ClientApp::GetSpecies(), anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld(), anonymous_namespace{ServerWrapper.cpp}::SpeciesCanColonize(), anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld(), and anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition().
GetSpecies() [2/2]
Species * SpeciesManager::GetSpecies (const std::string & name)
References anonymous_namespace{Species.cpp}::s_species.
GetSpeciesEmpireOpinionsMap()
const std::map< std::string, std::map< int, float > > & SpeciesManager::GetSpeciesEmpireOpinionsMap (int encoding_empire = ALL_EMPIRES) const
returns a map from species name to a map from empire id to each the species' opinion of the empire
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and serialize().
GetSpeciesHomeworldsMap()
std::map< std::string, std::set< int > > SpeciesManager::GetSpeciesHomeworldsMap (int encoding_empire = ALL_EMPIRES) const
returns a map from species name to a set of object IDs that are the homeworld(s) of that species in the current game.
References ALL_EMPIRES.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), Condition::Homeworld::Match(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), serialize(), and anonymous_namespace{UniverseWrapper.cpp}::SpeciesHomeworlds().
GetSpeciesSpeciesOpinionsMap()
const std::map< std::string, std::map< std::string, float > > & SpeciesManager::GetSpeciesSpeciesOpinionsMap (int encoding_empire = ALL_EMPIRES) const
returns a map from species name to a map from other species names to the opinion of the first species about the other species.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and serialize().
native_begin()
SpeciesManager::native_iterator SpeciesManager::native_begin () const
iterators for native species.
Referenced by anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies().
native_end()
SpeciesManager::native_iterator SpeciesManager::native_end () const
Referenced by anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies().
NumNativeSpecies()
int SpeciesManager::NumNativeSpecies () const
NumPlayableSpecies()
int SpeciesManager::NumPlayableSpecies () const
Referenced by GodotClientApp::NewSinglePlayerGame(), and GGHumanClientApp::NewSinglePlayerGame().
NumSpecies()
int SpeciesManager::NumSpecies () const
returns the number of species stored in this manager.
References anonymous_namespace{Species.cpp}::s_species.
playable_begin()
SpeciesManager::playable_iterator SpeciesManager::playable_begin () const
iterators for playble species.
Referenced by anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies(), GodotClientApp::NewSinglePlayerGame(), GGHumanClientApp::NewSinglePlayerGame(), and SpeciesSelector::SpeciesSelector().
playable_end()
SpeciesManager::playable_iterator SpeciesManager::playable_end () const
Referenced by anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies(), and SpeciesSelector::SpeciesSelector().
RandomPlayableSpeciesName()
const std::string & SpeciesManager::RandomPlayableSpeciesName () const
returns the name of a playable species in this manager, or an empty string if there are no playable species.
References anonymous_namespace{Species.cpp}::EMPTY_STRING, and RandInt().
Referenced by MPLobby::EstablishPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), Idle::react(), and MPLobby::react().
RandomSpeciesName()
const std::string & SpeciesManager::RandomSpeciesName () const
returns the name of a species in this manager, or an empty string if this manager is empty.
References anonymous_namespace{Species.cpp}::EMPTY_STRING, RandInt(), and anonymous_namespace{Species.cpp}::s_species.
RemoveSpeciesHomeworld()
void SpeciesManager::RemoveSpeciesHomeworld (const std::string & species, int homeworld_id)
References INVALID_OBJECT_ID.
Referenced by anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld().
SequentialPlayableSpeciesName()
const std::string & SpeciesManager::SequentialPlayableSpeciesName (int id) const
References DebugLogger, and anonymous_namespace{Species.cpp}::EMPTY_STRING.
Referenced by MPLobby::EstablishPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), Idle::react(), and MPLobby::react().
SetSpeciesEmpireOpinion()
void SpeciesManager::SetSpeciesEmpireOpinion (const std::string & species_name, int empire_id, float opinion)
Referenced by Effect::SetSpeciesEmpireOpinion::Execute().
SetSpeciesEmpireOpinions()
void SpeciesManager::SetSpeciesEmpireOpinions (std::map< std::string, std::map< int, float >> && species_empire_opinions)
sets the opinions of species (indexed by name string) of empires (indexed by id) as a double-valued number.
Referenced by serialize().
SetSpeciesHomeworlds()
void SpeciesManager::SetSpeciesHomeworlds (std::map< std::string, std::set< int >> && species_homeworld_ids) private
sets the homeworld ids of species in this SpeciesManager to those specified in species_homeworld_ids
Referenced by serialize().
SetSpeciesSpeciesOpinion()
void SpeciesManager::SetSpeciesSpeciesOpinion (const std::string & opinionated_species, const std::string & rated_species, float opinion)
Referenced by Effect::SetSpeciesSpeciesOpinion::Execute().
SetSpeciesSpeciesOpinions()
void SpeciesManager::SetSpeciesSpeciesOpinions (std::map< std::string, std::map< std::string, float >> && species_species_opinions)
sets the opinions of species (indexed by name string) of other species (indexed by name string) as a double-valued number.
Referenced by serialize().
SetSpeciesTypes()
void SpeciesManager::SetSpeciesTypes (Pending::Pending< std::pair< SpeciesTypeMap, CensusOrder >> && future)
Sets species types to the value of future.
References anonymous_namespace{Species.cpp}::s_pending_types, and anonymous_namespace{Species.cpp}::species_mutex.
Referenced by IApp::StartBackgroundParsing().
SpeciesEmpireOpinion()
float SpeciesManager::SpeciesEmpireOpinion (const std::string & species_name, int empire_id) const
returns opinion of species with name species_name about empire with id empire_id or 0.0 if there is no such opinion yet recorded.
Referenced by ValueRef::ComplexVariable< T >::Eval(), and Effect::SetSpeciesEmpireOpinion::Execute().
SpeciesObjectPopulations()
std::map< std::string, std::map< int, float > > & SpeciesManager::SpeciesObjectPopulations (int encoding_empire = ALL_EMPIRES)
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and serialize().
SpeciesShipsDestroyed()
std::map< std::string, std::map< std::string, int > > & SpeciesManager::SpeciesShipsDestroyed (int encoding_empire = ALL_EMPIRES)
Referenced by serialize().
SpeciesSpeciesOpinion()
float SpeciesManager::SpeciesSpeciesOpinion (const std::string & opinionated_species_name, const std::string & rated_species_name) const
returns opinion of species with name opinionated_species_name about other species with name rated_species_name or 0.0 if there is no such opinion yet recorded.
Referenced by ValueRef::ComplexVariable< T >::Eval(), and Effect::SetSpeciesSpeciesOpinion::Execute().
SpeciesThatDislike()
std::vector< std::string > SpeciesManager::SpeciesThatDislike (const std::string & content_name) const
References parse::species().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag().
SpeciesThatLike()
std::vector< std::string > SpeciesManager::SpeciesThatLike (const std::string & content_name) const
References parse::species().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag().
UpdatePopulationCounter()
void SpeciesManager::UpdatePopulationCounter ()
References Objects(), and parse::species().
Referenced by ServerApp::PostCombatProcessTurns().
Friends And Related Function Documentation
serialize
template<typename Archive > void serialize (Archive & ar, SpeciesManager & sm, unsigned int const version) friend
Member Data Documentation
m_species_empire_opinions
std::map<std::string, std::map<int, float> > SpeciesManager::m_species_empire_opinions private
m_species_homeworlds
std::map<std::string, std::set<int> > SpeciesManager::m_species_homeworlds private
m_species_object_populations
std::map<std::string, std::map<int, float> > SpeciesManager::m_species_object_populations private
Referenced by serialize().
m_species_species_opinions
std::map<std::string, std::map<std::string, float> > SpeciesManager::m_species_species_opinions private
m_species_species_ships_destroyed
std::map<std::string, std::map<std::string, int> > SpeciesManager::m_species_species_ships_destroyed private
Referenced by serialize().
The documentation for this class was generated from the following files:
Species.h
Species.cpp