FreeOrion: ClientUI Class Reference
ClientUI Class Reference
ClientUI Main Module This is the main class of the ClientUI module.
#include <ClientUI.h>
Public Member Functions
Structors //!@{
ClientUI ()
~ClientUI ()
Accessors //!@{
std::shared_ptr< MapWnd > GetMapWnd ()
Returns the main map window.
MapWnd const * GetMapWndConst () const
Returns the main map window.
std::shared_ptr< MessageWnd > GetMessageWnd ()
Returns the chat / message window.
std::shared_ptr< PlayerListWnd > GetPlayerListWnd ()
Returns the players list window.
std::shared_ptr< IntroScreen > GetIntroScreen ()
Returns the intro screen / splash window.
std::shared_ptr< MultiPlayerLobbyWnd > GetMultiPlayerLobbyWnd ()
Returns the multiplayer lobby window.
std::shared_ptr< PasswordEnterWnd > GetPasswordEnterWnd ()
Returns the authentication window.
std::shared_ptr< SaveFileDialog > GetSaveFileDialog ()
Returns a perhaps nullptr to any existing SaveFileDialog.
ShipDesignManager * GetShipDesignManager ()
Returns the main map window.
void GetSaveGameUIData (SaveGameUIData &data) const
populates the relevant UI state that should be restored after a save-and-load cycle
Mutators //!@{
void ShowIntroScreen ()
Return the IntroScreen.
void ShowMultiPlayerLobbyWnd ()
Return the IntroScreen.
std::string GetFilenameWithSaveFileDialog (const SaveFileDialog::Purpose purpose, const SaveFileDialog::SaveType type)
Creates a SaveFileDialog with purpose, Save or Load and type, SinglePlayer or MultiPlayer if one does not already exist.
void RestoreFromSaveData (const SaveGameUIData &elem)
restores the UI state that was saved in an earlier call to GetSaveGameUIData().
bool ZoomToObject (const std::string &name)
Return the IntroScreen.
bool ZoomToObject (int id)
Return the IntroScreen.
bool ZoomToPlanet (int id)
Zooms to a particular planet on the galaxy map and opens the sidepanel to show it, or if production screen is open selects it.
bool ZoomToPlanetPedia (int id)
Opens the encyclodedia window and presents the entry for the given planet.
bool ZoomToSystem (int id)
Zooms to a particular system on the galaxy map and opens the sidepanel to show it.
bool ZoomToFleet (int id)
Zooms to a particular fleet on the galaxy map and opens the fleet window.
bool ZoomToShip (int id)
Zooms to a particular ship on the galaxy map and opens its fleet and/or ship window.
bool ZoomToBuilding (int id)
Zooms to a particular building on the galaxy map and opens the sidepanel to show it.
bool ZoomToField (int id)
Zooms to a particular field on the map.
bool ZoomToCombatLog (int id)
Opens combat log for indicated combat.
void ZoomToSystem (std::shared_ptr< const System > system)
Zooms to a system on the galaxy map.
void ZoomToFleet (std::shared_ptr< const Fleet > fleet)
Zooms to a particular fleet on the galaxy map and opens the fleet window.
bool ZoomToContent (const std::string &name, bool reverse_lookup=false)
Return the IntroScreen.
bool ZoomToTech (const std::string &tech_name)
Opens the technology screen and presents a description of the given technology.
bool ZoomToBuildingType (const std::string &building_type_name)
Opens the production screen and presents a description of the given building type.
bool ZoomToSpecial (const std::string &special_name)
Opens the ??? screen and presents a description of the given special.
bool ZoomToShipHull (const std::string &hull_name)
Opens the design screen and presents a description of the given hull type.
bool ZoomToShipPart (const std::string &part_name)
Opens the design screen and presents a description of the given part type.
bool ZoomToSpecies (const std::string &species_name)
Opens the ??? screen and presents a description of the given species.
bool ZoomToFieldType (const std::string &field_type_name)
Opens the ??? screen and presents a description of the given field type.
bool ZoomToShipDesign (int design_id)
Opens the design screen and presents a description of the given ship design.
bool ZoomToEmpire (int empire_id)
Opens the ??? screen and presents a description of the given empire.
bool ZoomToMeterTypeArticle (const std::string &meter_string)
Opens the encyclopedia and presents the entry for MeterType meter_type.
bool ZoomToEncyclopediaEntry (const std::string &str)
Opens the encyclodedia window and presents the entry for the given term.
void DumpObject (int object_id)
Displays debug info about specified object in messages window.
void InitializeWindows ()
Return the IntroScreen.
std::shared_ptr< GG::Texture > GetRandomTexture (const boost::filesystem::path &dir, const std::string &prefix, bool mipmap=false)
Loads a texture at random from the set of files starting with prefix in directory dir.
std::shared_ptr< GG::Texture > GetModuloTexture (const boost::filesystem::path &dir, const std::string &prefix, int n, bool mipmap=false)
Loads texture n % N from the set of files starting with prefix in directory dir, where N is the number of files found in dir with prefix prefix.
std::vector< std::shared_ptr< GG::Texture > > GetPrefixedTextures (const boost::filesystem::path &dir, const std::string &prefix, bool mipmap=false)
Returns all textures in the set of files starting with prefix in directory dir.
Static Public Member Functions
static std::string FormatTimestamp (boost::posix_time::ptime timestamp)
Returns formatted POSIX UTC-time in local timezone.
static std::shared_ptr< GG::Font > GetBoldFont (int pts=Pts())
Returns the default font in the specified point size.
static ClientUI * GetClientUI ()
returns a pointer to the singleton ClientUI class
static std::shared_ptr< GG::Font > GetFont (int pts=Pts())
Returns the default font in the specified point size.
static std::shared_ptr< GG::Texture > GetTexture (const boost::filesystem::path &path, bool mipmap=false)
Loads the requested texture from file name; mipmap textures are generated if mipmap is true; loads default missing.png if name isn't found.
static std::shared_ptr< GG::Font > GetTitleFont (int pts=TitlePts())
Returns the default font in the specified point size.
static void MessageBox (const std::string &message, bool play_alert_sound=false)
Shows a message dialog box with the given message; if play_alert_sound is true, and UI sound effects are currently enabled, the default alert sound will be played as the message box opens.
static boost::filesystem::path ArtDir ()
directory holding artwork
static boost::filesystem::path SoundDir ()
directory holding sound and music
static int Pts ()
default point size
static int TitlePts ()
default point size to use for window title
static GG::Clr TextColor ()
color of UI text
static GG::Clr DefaultLinkColor ()
default color of UI links
static GG::Clr RolloverLinkColor ()
rollover color of UI links
static GG::Clr WndColor ()
background color of a UI window
static GG::Clr WndOuterBorderColor ()
color of the outermost border
static GG::Clr WndInnerBorderColor ()
color of the innermost border
static GG::Clr CtrlColor ()
background color of UI controls
static GG::Clr CtrlBorderColor ()
directory holding artwork
static GG::Clr ButtonHiliteColor ()
directory holding artwork
static GG::Clr ButtonHiliteBorderColor ()
directory holding artwork
static int ScrollWidth ()
directory holding artwork
static GG::Clr DropDownListArrowColor ()
directory holding artwork
static GG::Clr EditHiliteColor ()
directory holding artwork
static GG::Clr StatIncrColor ()
used to color increasing stats text (eg "+2")
static GG::Clr StatDecrColor ()
used to color decreasing stats text (eg "-3")
static GG::Clr StateButtonColor ()
colour of selected state button markers
static int SystemIconSize ()
the width/height of a System/Icon at zoom = 1.0
static int SystemTinyIconSizeThreshold ()
the width/height of a system icon below which the tiny system icons should be used
static int SystemCircleSize ()
the width/height of the system-enclosing circle
static int SystemSelectionIndicatorSize ()
the width/height of a system selection indicator
static int SystemSelectionIndicatorRPM ()
revolutions per minute to rotate system selection indicator
static GG::Clr SystemNameTextColor ()
the colour of system names that aren't owned by any player (as far as this client knows)
static double TinyFleetButtonZoomThreshold ()
the minimum zoom level of the map at which to show tiny (any) fleet icons
static double SmallFleetButtonZoomThreshold ()
the minimum zoom level of the map at which to show small fleet icons
static double MediumFleetButtonZoomThreshold ()
the minimum zoom level of the map at which to show medium fleet icons
static bool DisplayTimestamp ()
Will be timestamp shown in the chats.
static std::shared_ptr< GG::Texture > PlanetIcon (PlanetType planet_type)
directory holding artwork
static std::shared_ptr< GG::Texture > PlanetSizeIcon (PlanetSize planet_size)
directory holding artwork
static std::shared_ptr< GG::Texture > MeterIcon (MeterType meter_type)
directory holding artwork
static std::shared_ptr< GG::Texture > BuildingIcon (const std::string &building_type_name)
directory holding artwork
static std::shared_ptr< GG::Texture > CategoryIcon (const std::string &category_name)
directory holding artwork
static std::shared_ptr< GG::Texture > TechIcon (const std::string &tech_name)
directory holding artwork
static std::shared_ptr< GG::Texture > SpecialIcon (const std::string &special_name)
directory holding artwork
static std::shared_ptr< GG::Texture > SpeciesIcon (const std::string &species_name)
directory holding artwork
static std::shared_ptr< GG::Texture > FieldTexture (const std::string &field_type_name)
directory holding artwork
static std::shared_ptr< GG::Texture > PartIcon (const std::string &part_name)
directory holding artwork
static std::shared_ptr< GG::Texture > HullTexture (const std::string &hull_name)
directory holding artwork
static std::shared_ptr< GG::Texture > HullIcon (const std::string &hull_name)
directory holding artwork
static std::shared_ptr< GG::Texture > ShipDesignIcon (int design_id)
directory holding artwork
static GG::Clr KnownTechFillColor ()
directory holding artwork
static GG::Clr KnownTechTextAndBorderColor ()
directory holding artwork
static GG::Clr ResearchableTechFillColor ()
directory holding artwork
static GG::Clr ResearchableTechTextAndBorderColor ()
directory holding artwork
static GG::Clr UnresearchableTechFillColor ()
directory holding artwork
static GG::Clr UnresearchableTechTextAndBorderColor ()
directory holding artwork
static GG::Clr TechWndProgressBarBackgroundColor ()
directory holding artwork
static GG::Clr TechWndProgressBarColor ()
directory holding artwork
static GG::Clr CategoryColor (const std::string &category_name)
directory holding artwork
static std::map< PlanetType, std::string > & PlanetTypeFilePrefixes ()
directory holding artwork
static std::map< StarType, std::string > & StarTypeFilePrefixes ()
directory holding artwork
static std::map< StarType, std::string > & HaloStarTypeFilePrefixes ()
directory holding artwork
Private Types
typedef std::map< std::string, TexturesAndDist > PrefixedTextures
typedef std::pair< std::vector< std::shared_ptr< GG::Texture > >, std::shared_ptr< SmallIntDistType > > TexturesAndDist
Private Member Functions
void HandleFullscreenSwitch () const
void HandleSizeChange (bool fullscreen) const
TexturesAndDist PrefixedTexturesAndDist (const boost::filesystem::path &dir, const std::string &prefix, bool mipmap)
Private Attributes
std::shared_ptr< IntroScreen > m_intro_screen
splash screen / main menu when starting program
std::shared_ptr< MapWnd > m_map_wnd
the galaxy map
std::shared_ptr< MessageWnd > m_message_wnd
the messages / chat display
std::shared_ptr< MultiPlayerLobbyWnd > m_multiplayer_lobby_wnd
the multiplayer lobby
std::shared_ptr< PasswordEnterWnd > m_password_enter_wnd
the authentication window
std::shared_ptr< PlayerListWnd > m_player_list_wnd
the players list
PrefixedTextures m_prefixed_textures
std::shared_ptr< SaveFileDialog > m_savefile_dialog
std::unique_ptr< ShipDesignManager > m_ship_designs
ship designs the client knows about, and their ordering in the UI
Static Private Attributes
static ClientUI * s_the_UI = nullptr
the singleton ClientUI object
Detailed Description
ClientUI Main Module This is the main class of the ClientUI module.
it contains objects of many other classes and controls the display of all information onscreen.
Member Typedef Documentation
PrefixedTextures
typedef std::map<std::string, TexturesAndDist> ClientUI::PrefixedTextures private
TexturesAndDist
typedef std::pair<std::vector<std::shared_ptr<GG::Texture> >, std::shared_ptr<SmallIntDistType> > ClientUI::TexturesAndDist private
Constructor & Destructor Documentation
ClientUI()
ClientUI::ClientUI ()
References ArtDir(), CLOSABLE, anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption(), HumanClientApp::FullscreenSwitchSignal, HumanClientApp::GetApp(), GetOptionsDB(), HandleFullscreenSwitch(), HandleSizeChange(), InitializeWindows(), CUIWnd::InvalidateUnusedOptions(), m_intro_screen, m_message_wnd, m_multiplayer_lobby_wnd, m_password_enter_wnd, m_player_list_wnd, anonymous_namespace{ClientUI.cpp}::MESSAGE_WND_NAME, OptionsDB::OptionChangedSignal(), PINABLE, anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_WND_NAME, Hotkey::ReadFromOptions(), HumanClientApp::RepositionWindowsSignal, and s_the_UI.
~ClientUI()
ClientUI::~ClientUI ()
References s_the_UI.
Member Function Documentation
ArtDir()
fs::path ClientUI::ArtDir () static
directory holding artwork
References GetResourceDir().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::AIIcon(), anonymous_namespace{PlayerListWnd.cpp}::AlliedIcon(), BuildingIcon(), CategoryIcon(), ClientUI(), anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), ModeratorActionsWnd::CompleteConstruction(), AccordionPanel::CompleteConstruction(), IntroScreen::CompleteConstruction(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), SystemIcon::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), CUI_PinButton::CUI_PinButton(), anonymous_namespace{FleetWnd.cpp}::DamageIcon(), anonymous_namespace{PlayerListWnd.cpp}::DetectionIcon(), FieldTexture(), anonymous_namespace{FleetWnd.cpp}::FightersIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveMouseoverIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), FleetBlockadedIcon(), anonymous_namespace{FleetWnd.cpp}::FleetCountIcon(), FleetHeadIcons(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveMouseoverIcon(), FleetSelectionIndicatorIcon(), FleetSizeIcon(), anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures(), anonymous_namespace{MapWnd.cpp}::GetGasTexture(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetHostTexture(), anonymous_namespace{SidePanel.cpp}::GetLightPosition(), anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetReadyTexture(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), GetShipDesignManager(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), GetTexture(), MapWnd::HideDesign(), MapWnd::HideEmpires(), MapWnd::HideMessages(), MapWnd::HideModeratorActions(), MapWnd::HideObjects(), MapWnd::HidePedia(), MapWnd::HideProduction(), MapWnd::HideResearch(), MapWnd::HideSitRep(), anonymous_namespace{PlayerListWnd.cpp}::HostIcon(), HullIcon(), HullTexture(), HumanClientApp::HumanClientApp(), anonymous_namespace{PlayerListWnd.cpp}::HumanIcon(), anonymous_namespace{FleetWnd.cpp}::IndustryIcon(), CUIWnd::InitButtons(), anonymous_namespace{PlayerListWnd.cpp}::LostIcon(), MeterIcon(), anonymous_namespace{PlayerListWnd.cpp}::ModeratorIcon(), anonymous_namespace{MapWnd.cpp}::MoveLineDotTexture(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), anonymous_namespace{PlayerListWnd.cpp}::ObserverIcon(), anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture(), PartIcon(), anonymous_namespace{PlayerListWnd.cpp}::PeaceIcon(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PlanetEnvFilenames(), PlanetIcon(), PlanetSizeIcon(), anonymous_namespace{PlayerListWnd.cpp}::PlayingIcon(), anonymous_namespace{PlayerListWnd.cpp}::ProductionIcon(), BuildingIndicator::Refresh(), SystemIcon::Refresh(), SidePanel::PlanetPanel::Refresh(), RotatingPlanetControl::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSearchResultsTag(), SidePanel::RefreshImpl(), MapWnd::RefreshIndustryResourceIndicator(), ObjectPanel::RefreshLayout(), anonymous_namespace{PlayerListWnd.cpp}::ResearchIcon(), anonymous_namespace{FleetWnd.cpp}::ResearchIcon(), AccordionPanel::SetCollapsed(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), ShipDesignIcon(), anonymous_namespace{PlayerListWnd.cpp}::ShipIcon(), MapWnd::ShowDesign(), MapWnd::ShowEmpires(), MapWnd::ShowMenu(), MapWnd::ShowMessages(), MapWnd::ShowModeratorActions(), MapWnd::ShowObjects(), MapWnd::ShowPedia(), MapWnd::ShowProduction(), MapWnd::ShowResearch(), MapWnd::ShowSitRep(), anonymous_namespace{DesignWnd.cpp}::SlotBackgroundTexture(), SpecialIcon(), SpeciesIcon(), SpeciesSelector::SpeciesSelector(), TechIcon(), CUI_PinButton::Toggle(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{FleetWnd.cpp}::TradeIcon(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), anonymous_namespace{PlayerListWnd.cpp}::UnknownIcon(), anonymous_namespace{PlayerListWnd.cpp}::WaitingIcon(), anonymous_namespace{PlayerListWnd.cpp}::WarIcon(), and anonymous_namespace{PlayerListWnd.cpp}::WonIcon().
BuildingIcon()
std::shared_ptr< GG::Texture > ClientUI::BuildingIcon (const std::string & building_type_name) static
directory holding artwork
References ArtDir(), GetBuildingType(), GetTexture(), and BuildingType::Icon().
Referenced by BuildingIndicator::BuildingIndicator(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
ButtonHiliteBorderColor()
GG::Clr ClientUI::ButtonHiliteBorderColor () static
directory holding artwork
References AdjustBrightness(), and CtrlBorderColor().
Referenced by GetShipDesignManager(), and CUILabelButtonRepresenter::Render().
ButtonHiliteColor()
GG::Clr ClientUI::ButtonHiliteColor () static
directory holding artwork
References AdjustBrightness(), and CtrlColor().
Referenced by GetShipDesignManager(), and CUILabelButtonRepresenter::Render().
CategoryColor()
GG::Clr ClientUI::CategoryColor (const std::string & category_name) static
directory holding artwork
References TechCategory::colour, and GetTechCategory().
Referenced by TechTreeWnd::TechTreeControls::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and TechTreeWnd::TechListBox::TechRow::Update().
CategoryIcon()
std::shared_ptr< GG::Texture > ClientUI::CategoryIcon (const std::string & category_name) static
directory holding artwork
References ArtDir(), GetTechCategory(), and GetTexture().
Referenced by TechTreeWnd::TechTreeControls::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and TechIcon().
CtrlBorderColor()
GG::Clr ClientUI::CtrlBorderColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by ButtonHiliteBorderColor(), InGameMenu::Concede(), GetShipDesignManager(), ColorSelector::LClick(), CUIStyle::NewHScrollTabButton(), CUIStyle::NewHSliderTabButton(), CUIStyle::NewVScrollTabButton(), CUIStyle::NewVSliderTabButton(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), CUISlider< T >::Render(), GraphicalSummaryWnd::Render(), CUICheckBoxRepresenter::Render(), CUIRadioRepresenter::Render(), CUITabRepresenter::Render(), CUILabelButtonRepresenter::Render(), CUIIconButtonRepresenter::Render(), ConditionWidget::Render(), CUIButton::RenderPressed(), CUIButton::RenderRollover(), and CUIButton::RenderUnpressed().
CtrlColor()
GG::Clr ClientUI::CtrlColor () static
background color of UI controls
References OptionsDB::Get(), and GetOptionsDB().
Referenced by ButtonHiliteColor(), EncyclopediaDetailPanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), InGameMenu::Concede(), CUIDropDownList::CUIDropDownList(), GetShipDesignManager(), CombatReportWnd::Impl::Impl(), ColorSelector::LClick(), MessageBox(), CUIStyle::NewHScrollTabButton(), CUIStyle::NewHSliderTabButton(), CUIStyle::NewVScrollTabButton(), CUIStyle::NewVSliderTabButton(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), GraphicalSummaryWnd::Render(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Render(), CUILabelButtonRepresenter::Render(), CUIIconButtonRepresenter::Render(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::Render(), SidePanel::PlanetPanel::Render(), TechTreeWnd::LayoutPanel::Render(), TechTreeWnd::LayoutPanel::TechPanel::Render(), ConditionWidget::Render(), and HumanClientApp::ResetOrExitApp().
DefaultLinkColor()
GG::Clr ClientUI::DefaultLinkColor () static
default color of UI links
References OptionsDB::Get(), and GetOptionsDB().
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), LinkDecorator::Decorate(), ColorByOwner::Decorate(), anonymous_namespace{SitRepPanel.cpp}::ColorEmpire::Decorate(), and GetShipDesignManager().
DisplayTimestamp()
bool ClientUI::DisplayTimestamp () static
Will be timestamp shown in the chats.
References OptionsDB::Get(), and GetOptionsDB().
Referenced by FormatTimestamp(), and GetShipDesignManager().
DropDownListArrowColor()
GG::Clr ClientUI::DropDownListArrowColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), and CUIDropDownList::Render().
DumpObject()
void ClientUI::DumpObject (int object_id)
Displays debug info about specified object in messages window.
References GetUniverseObject(), and m_message_wnd.
Referenced by MapWnd::CompleteConstruction(), and GetShipDesignManager().
EditHiliteColor()
GG::Clr ClientUI::EditHiliteColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by CUISpin< T >::CompleteConstruction(), CUIMultiEdit::CompleteConstruction(), CUIEdit::CUIEdit(), GetShipDesignManager(), and SidePanel::SystemNameDropDownList::RClick().
FieldTexture()
std::shared_ptr< GG::Texture > ClientUI::FieldTexture (const std::string & field_type_name) static
directory holding artwork
References ArtDir(), GetFieldType(), GetTexture(), and FieldType::Graphic().
Referenced by GetShipDesignManager(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), FieldIcon::Refresh(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag().
FormatTimestamp()
std::string ClientUI::FormatTimestamp (boost::posix_time::ptime timestamp) static
Returns formatted POSIX UTC-time in local timezone.
References DisplayTimestamp(), GetLocale(), IsValidUTF8(), and TraceLogger.
Referenced by GetShipDesignManager(), and MessageWnd::HandlePlayerChatMessage().
GetBoldFont()
std::shared_ptr< GG::Font > ClientUI::GetBoldFont (int pts = Pts()) static
Returns the default font in the specified point size.
Uses "ui.font.bold.path" option setting as the font filename, and provides Unicode character sets based on the contents of the stringtable in use.
References GetOptionsDB(), and anonymous_namespace{ClientUI.cpp}::RequiredCharsets().
Referenced by CensusBrowseWnd::CompleteConstruction(), ResourceBrowseWnd::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), WastedStockpiledResourceBrowseWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), GetShipDesignManager(), SystemResourceSummaryBrowseWnd::Initialize(), MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::NewLabelValue(), OwnerColoredSystemName::OwnerColoredSystemName(), IconTextBrowseWnd::PreRender(), SidePanel::RefreshSystemNames(), MapWnd::RenderMovementLineETAIndicators(), TextBrowseWnd::TextBrowseWnd(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), and anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl().
GetClientUI()
ClientUI * ClientUI::GetClientUI () static
returns a pointer to the singleton ClientUI class
References s_the_UI.
Referenced by BuildDesignatorWnd::CenterOnBuild(), MultiPlayerLobbyWnd::ChatMessage(), ModeratorActionsWnd::CompleteConstruction(), SystemIcon::CompleteConstruction(), MapWnd::CompleteConstruction(), MapWndPopup::CompleteConstruction(), SitRepPanel::DismissalMenu(), MapWnd::DoLayout(), MapWnd::EndTurn(), MilitaryPanel::EventFilter(), SpecialsPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), ResourcePanel::EventFilter(), PopulationPanel::EventFilter(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::EventFilter(), FleetDataPanel::EventFilter(), FleetBlockadedIcon(), FleetButton::FleetButton(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), FleetSelectionIndicatorIcon(), FleetSizeIcon(), anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), anonymous_namespace{MapWnd.cpp}::GetGasTexture(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), anonymous_namespace{ChatWnd.cpp}::HandleTextCommand(), HumanClientApp::HandleWindowResize(), MapWnd::HideEmpires(), MapWnd::HideMessages(), MapWnd::HideProduction(), HumanClientApp::LoadSinglePlayerGame(), MessageWnd::MessageEntered(), FleetButton::MouseHere(), SystemIcon::NthFleetButtonUpperLeft(), ObjectListWnd::ObjectDoubleClicked(), ObjectListWnd::ObjectRightClicked(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), PlayerListWnd::PlayerRightClicked(), BuildDesignatorWnd::BuildSelector::PopulateList(), FieldIcon::RClick(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SystemIcon::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), SidePanel::RefreshImpl(), MapWnd::ReturnToMap(), MapWnd::Sanitize(), InGameMenu::Save(), HumanClientApp::SelectLoadFile(), FleetDetailPanel::ShipRightClicked(), MapWnd::ShowEmpires(), MapWnd::ShowMessages(), MapWnd::ShowProduction(), HumanClientApp::StartGame(), MapWnd::ToggleEmpires(), MapWnd::ToggleMessages(), FleetWnd::~FleetWnd(), and MapWndPopup::~MapWndPopup().
GetFilenameWithSaveFileDialog()
std::string ClientUI::GetFilenameWithSaveFileDialog (const SaveFileDialog::Purpose purpose, const SaveFileDialog::SaveType type)
Creates a SaveFileDialog with purpose, Save or Load and type, SinglePlayer or MultiPlayer if one does not already exist.
Returns the filename provided by the player, if any.
References m_savefile_dialog.
Referenced by GetShipDesignManager(), HumanClientApp::LoadSinglePlayerGame(), InGameMenu::Save(), and HumanClientApp::SelectLoadFile().
GetFont()
std::shared_ptr< GG::Font > ClientUI::GetFont (int pts = Pts()) static
Returns the default font in the specified point size.
Uses "ui.font.path" option setting as the font filename, and provides Unicode character sets based on the contents of the stringtable in use.
References GetOptionsDB(), and anonymous_namespace{ClientUI.cpp}::RequiredCharsets().
Referenced by SaveFileColumn::CellForColumn(), GameRulesPanel::CompleteConstruction(), OptionsWnd::CompleteConstruction(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), anonymous_namespace{OptionsWnd.cpp}::FontTextureWnd::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), SaveFileColumn::ComputeFixedWidth(), InGameMenu::Concede(), anonymous_namespace{SaveFileDialog.cpp}::CreateResizingText(), GameRulesPanel::CreateSectionHeader(), OptionsWnd::CreateSectionHeader(), CreditsWnd::CreditsWnd(), SaveFileDirectoryRow::DirectoryNameSize(), OptionsWnd::DoLayout(), GalaxySetupPanel::DoLayout(), GalaxySetupWnd::DoLayout(), StatisticIcon::DoLayout(), OptionsBar::DoLayout(), GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::HairSpaceExtent(), HumanClientApp::HumanClientApp(), CombatReportWnd::Impl::Impl(), SaveFileDialog::Init(), SaveFileDirectoryRow::Init(), ColorSelector::LClick(), MapWnd::MapScaleLine::MapScaleLine(), MessageBox(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), BuildDesignatorWnd::BuildSelector::PopulateList(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), SidePanel::SystemNameDropDownList::RClick(), HumanClientApp::ResetOrExitApp(), CombatReportWnd::Impl::SetLog(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), SaveFileColumn::TitleForColumn(), and CombatReportWnd::Impl::UpdateMinSize().
GetIntroScreen()
std::shared_ptr< IntroScreen > ClientUI::GetIntroScreen ()
Returns the intro screen / splash window.
References m_intro_screen.
GetMapWnd()
std::shared_ptr< MapWnd > ClientUI::GetMapWnd ()
Returns the main map window.
References m_map_wnd.
Referenced by BuildDesignatorWnd::CenterOnBuild(), FleetButton::FleetButton(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), FleetButton::MouseHere(), SystemIcon::NthFleetButtonUpperLeft(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), RestoreFromSaveData(), FleetDetailPanel::ShipRightClicked(), ZoomToBuildingType(), ZoomToCombatLog(), ZoomToEmpire(), ZoomToEncyclopediaEntry(), ZoomToFieldType(), ZoomToFleet(), ZoomToMeterTypeArticle(), ZoomToPlanet(), ZoomToPlanetPedia(), ZoomToShipDesign(), ZoomToShipHull(), ZoomToShipPart(), ZoomToSpecial(), ZoomToSpecies(), ZoomToSystem(), and ZoomToTech().
GetMapWndConst()
MapWnd const * ClientUI::GetMapWndConst () const
Returns the main map window.
References m_map_wnd.
Referenced by GetSaveGameUIData().
GetMessageWnd()
std::shared_ptr< MessageWnd > ClientUI::GetMessageWnd ()
Returns the chat / message window.
References m_message_wnd.
Referenced by HumanClientApp::HandleTurnPhaseUpdate(), WaitingForSPHostAck::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MapWnd::ShowMessages(), and MapWnd::ToggleMessages().
GetModuloTexture()
std::shared_ptr< GG::Texture > ClientUI::GetModuloTexture (const boost::filesystem::path & dir, const std::string & prefix, int n, bool mipmap = false)
Loads texture n % N from the set of files starting with prefix in directory dir, where N is the number of files found in dir with prefix prefix.
References PrefixedTexturesAndDist().
Referenced by ModeratorActionsWnd::CompleteConstruction(), SystemIcon::CompleteConstruction(), FleetSizeIcon(), GetShipDesignManager(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), and SidePanel::RefreshImpl().
GetMultiPlayerLobbyWnd()
std::shared_ptr< MultiPlayerLobbyWnd > ClientUI::GetMultiPlayerLobbyWnd ()
Returns the multiplayer lobby window.
References m_multiplayer_lobby_wnd.
GetPasswordEnterWnd()
std::shared_ptr< PasswordEnterWnd > ClientUI::GetPasswordEnterWnd ()
Returns the authentication window.
References m_password_enter_wnd.
GetPlayerListWnd()
std::shared_ptr< PlayerListWnd > ClientUI::GetPlayerListWnd ()
Returns the players list window.
References m_player_list_wnd.
Referenced by MapWnd::ShowEmpires(), and MapWnd::ToggleEmpires().
GetPrefixedTextures()
std::vector< std::shared_ptr< GG::Texture > > ClientUI::GetPrefixedTextures (const boost::filesystem::path & dir, const std::string & prefix, bool mipmap = false)
Returns all textures in the set of files starting with prefix in directory dir.
References PrefixedTexturesAndDist().
Referenced by anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures(), and GetShipDesignManager().
GetRandomTexture()
std::shared_ptr< GG::Texture > ClientUI::GetRandomTexture (const boost::filesystem::path & dir, const std::string & prefix, bool mipmap = false)
Loads a texture at random from the set of files starting with prefix in directory dir.
References PrefixedTexturesAndDist().
Referenced by GetShipDesignManager().
GetSaveFileDialog()
std::shared_ptr< SaveFileDialog > ClientUI::GetSaveFileDialog ()
Returns a perhaps nullptr to any existing SaveFileDialog.
References m_savefile_dialog.
Referenced by HumanClientApp::HandleSaveGamePreviews().
GetSaveGameUIData()
void ClientUI::GetSaveGameUIData (SaveGameUIData & data) const
populates the relevant UI state that should be restored after a save-and-load cycle
References GetMapWndConst(), MapWnd::GetSaveGameUIData(), and m_ship_designs.
Referenced by MapWnd::EndTurn(), and GetShipDesignManager().
GetShipDesignManager()
ShipDesignManager* ClientUI::GetShipDesignManager () inline
Returns the main map window.
References ArtDir(), BuildingIcon(), ButtonHiliteBorderColor(), ButtonHiliteColor(), CategoryColor(), CategoryIcon(), CtrlBorderColor(), CtrlColor(), DefaultLinkColor(), DisplayTimestamp(), DropDownListArrowColor(), DumpObject(), EditHiliteColor(), FieldTexture(), FormatTimestamp(), GetBoldFont(), GetClientUI(), GetFilenameWithSaveFileDialog(), GetFont(), GetModuloTexture(), GetPrefixedTextures(), GetRandomTexture(), GetSaveGameUIData(), GetTexture(), GetTitleFont(), HaloStarTypeFilePrefixes(), HullIcon(), HullTexture(), InitializeWindows(), KnownTechFillColor(), KnownTechTextAndBorderColor(), m_ship_designs, MediumFleetButtonZoomThreshold(), MessageBox(), MeterIcon(), PartIcon(), PlanetIcon(), PlanetSizeIcon(), PlanetTypeFilePrefixes(), Pts(), ResearchableTechFillColor(), ResearchableTechTextAndBorderColor(), RestoreFromSaveData(), RolloverLinkColor(), ScrollWidth(), ShipDesignIcon(), ShowIntroScreen(), ShowMultiPlayerLobbyWnd(), SmallFleetButtonZoomThreshold(), SoundDir(), SpecialIcon(), SpeciesIcon(), StarTypeFilePrefixes(), StatDecrColor(), StateButtonColor(), StatIncrColor(), SystemCircleSize(), SystemIconSize(), SystemNameTextColor(), SystemSelectionIndicatorRPM(), SystemSelectionIndicatorSize(), SystemTinyIconSizeThreshold(), TechIcon(), TechWndProgressBarBackgroundColor(), TechWndProgressBarColor(), TextColor(), TinyFleetButtonZoomThreshold(), TitlePts(), UnresearchableTechFillColor(), UnresearchableTechTextAndBorderColor(), WndColor(), WndInnerBorderColor(), WndOuterBorderColor(), ZoomToBuilding(), ZoomToBuildingType(), ZoomToCombatLog(), ZoomToContent(), ZoomToEmpire(), ZoomToEncyclopediaEntry(), ZoomToField(), ZoomToFieldType(), ZoomToFleet(), ZoomToMeterTypeArticle(), ZoomToObject(), ZoomToPlanet(), ZoomToPlanetPedia(), ZoomToShip(), ZoomToShipDesign(), ZoomToShipHull(), ZoomToShipPart(), ZoomToSpecial(), ZoomToSpecies(), ZoomToSystem(), and ZoomToTech().
Referenced by anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), BuildDesignatorWnd::BuildSelector::PopulateList(), and HumanClientApp::StartGame().
GetTexture()
std::shared_ptr< GG::Texture > ClientUI::GetTexture (const boost::filesystem::path & path, bool mipmap = false) static
Loads the requested texture from file name; mipmap textures are generated if mipmap is true; loads default missing.png if name isn't found.
References ArtDir(), ErrorLogger, and HumanClientApp::GetApp().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::AIIcon(), anonymous_namespace{PlayerListWnd.cpp}::AlliedIcon(), BuildingIcon(), CategoryIcon(), anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), ModeratorActionsWnd::CompleteConstruction(), AccordionPanel::CompleteConstruction(), IntroScreen::CompleteConstruction(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), SystemIcon::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), CUI_PinButton::CUI_PinButton(), anonymous_namespace{FleetWnd.cpp}::DamageIcon(), anonymous_namespace{PlayerListWnd.cpp}::DetectionIcon(), FieldTexture(), anonymous_namespace{FleetWnd.cpp}::FightersIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveMouseoverIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), FleetBlockadedIcon(), anonymous_namespace{FleetWnd.cpp}::FleetCountIcon(), FleetHeadIcons(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveMouseoverIcon(), FleetSelectionIndicatorIcon(), FleetSizeIcon(), anonymous_namespace{MapWnd.cpp}::GetGasTexture(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetHostTexture(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetReadyTexture(), GetShipDesignManager(), MapWnd::HideDesign(), MapWnd::HideEmpires(), MapWnd::HideMessages(), MapWnd::HideModeratorActions(), MapWnd::HideObjects(), MapWnd::HidePedia(), MapWnd::HideProduction(), MapWnd::HideResearch(), MapWnd::HideSitRep(), anonymous_namespace{PlayerListWnd.cpp}::HostIcon(), HullIcon(), HullTexture(), anonymous_namespace{PlayerListWnd.cpp}::HumanIcon(), anonymous_namespace{FleetWnd.cpp}::IndustryIcon(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), CUIWnd::InitButtons(), anonymous_namespace{PlayerListWnd.cpp}::LostIcon(), MeterIcon(), anonymous_namespace{PlayerListWnd.cpp}::ModeratorIcon(), anonymous_namespace{MapWnd.cpp}::MoveLineDotTexture(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), anonymous_namespace{PlayerListWnd.cpp}::ObserverIcon(), anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture(), PartIcon(), anonymous_namespace{PlayerListWnd.cpp}::PeaceIcon(), PlanetIcon(), PlanetSizeIcon(), anonymous_namespace{PlayerListWnd.cpp}::PlayingIcon(), PrefixedTexturesAndDist(), anonymous_namespace{PlayerListWnd.cpp}::ProductionIcon(), BuildingIndicator::Refresh(), SystemIcon::Refresh(), SidePanel::PlanetPanel::Refresh(), RotatingPlanetControl::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSearchResultsTag(), MapWnd::RefreshIndustryResourceIndicator(), ObjectPanel::RefreshLayout(), anonymous_namespace{PlayerListWnd.cpp}::ResearchIcon(), anonymous_namespace{FleetWnd.cpp}::ResearchIcon(), AccordionPanel::SetCollapsed(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), ShipDesignIcon(), anonymous_namespace{PlayerListWnd.cpp}::ShipIcon(), MapWnd::ShowDesign(), MapWnd::ShowEmpires(), MapWnd::ShowMenu(), MapWnd::ShowMessages(), MapWnd::ShowModeratorActions(), MapWnd::ShowObjects(), MapWnd::ShowPedia(), MapWnd::ShowProduction(), MapWnd::ShowResearch(), MapWnd::ShowSitRep(), anonymous_namespace{DesignWnd.cpp}::SlotBackgroundTexture(), SpecialIcon(), SpeciesIcon(), SpeciesSelector::SpeciesSelector(), TechIcon(), CUI_PinButton::Toggle(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{FleetWnd.cpp}::TradeIcon(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), anonymous_namespace{PlayerListWnd.cpp}::UnknownIcon(), anonymous_namespace{PlayerListWnd.cpp}::WaitingIcon(), anonymous_namespace{PlayerListWnd.cpp}::WarIcon(), and anonymous_namespace{PlayerListWnd.cpp}::WonIcon().
GetTitleFont()
std::shared_ptr< GG::Font > ClientUI::GetTitleFont (int pts = TitlePts()) static
Returns the default font in the specified point size.
Uses "ui.font.title.path" option setting as the font filename, and provides Unicode character sets based on the contents of the stringtable in use.
References GetOptionsDB(), and anonymous_namespace{ClientUI.cpp}::RequiredCharsets().
Referenced by anonymous_namespace{OptionsWnd.cpp}::FontTextureWnd::CompleteConstruction(), GetShipDesignManager(), and CUIWnd::Render().
HaloStarTypeFilePrefixes()
std::map< StarType, std::string > & ClientUI::HaloStarTypeFilePrefixes () static
directory holding artwork
References INVALID_STAR_TYPE, s_the_UI, STAR_BLACK, STAR_BLUE, STAR_NEUTRON, STAR_NONE, STAR_ORANGE, STAR_RED, STAR_WHITE, and STAR_YELLOW.
Referenced by SystemIcon::CompleteConstruction(), GetShipDesignManager(), and anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures().
HandleFullscreenSwitch()
void ClientUI::HandleFullscreenSwitch () const private
References OptionsDB::Get(), HumanClientApp::GetApp(), OptionsDB::GetDefault(), GetOptionsDB(), anonymous_namespace{ClientUI.cpp}::MESSAGE_WND_NAME, and HumanClientApp::RepositionWindowsSignal.
Referenced by ClientUI().
HandleSizeChange()
void ClientUI::HandleSizeChange (bool fullscreen) const private
References OptionsDB::Get(), OptionsDB::GetDefault(), GetOptionsDB(), anonymous_namespace{ClientUI.cpp}::MESSAGE_WND_NAME, and OptionsDB::Set().
Referenced by ClientUI().
HullIcon()
std::shared_ptr< GG::Texture > ClientUI::HullIcon (const std::string & hull_name) static
directory holding artwork
References ArtDir(), GetHullType(), GetTexture(), HullType::Graphic(), and HullType::Icon().
Referenced by GetShipDesignManager(), BasesListBox::HullAndNamePanel::HullAndNamePanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), ShipDesignIcon(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
HullTexture()
std::shared_ptr< GG::Texture > ClientUI::HullTexture (const std::string & hull_name) static
directory holding artwork
References ArtDir(), GetHullType(), GetTexture(), HullType::Graphic(), and HullType::Icon().
Referenced by GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), DesignWnd::MainPanel::SetHull(), and ShipDesignIcon().
InitializeWindows()
void ClientUI::InitializeWindows ()
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), m_message_wnd, m_player_list_wnd, anonymous_namespace{ClientUI.cpp}::MESSAGE_PANEL_WIDTH(), anonymous_namespace{ClientUI.cpp}::PANEL_HEIGHT(), and anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_PANEL_WIDTH().
Referenced by ClientUI(), and GetShipDesignManager().
KnownTechFillColor()
GG::Clr ClientUI::KnownTechFillColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager().
KnownTechTextAndBorderColor()
GG::Clr ClientUI::KnownTechTextAndBorderColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager().
MediumFleetButtonZoomThreshold()
double ClientUI::MediumFleetButtonZoomThreshold () static
the minimum zoom level of the map at which to show medium fleet icons
References OptionsDB::Get(), and GetOptionsDB().
Referenced by MapWnd::FleetButtonSizeType(), and GetShipDesignManager().
MessageBox()
void ClientUI::MessageBox (const std::string & message, bool play_alert_sound = false) static
Shows a message dialog box with the given message; if play_alert_sound is true, and UI sound effects are currently enabled, the default alert sound will be played as the message box opens.
References CtrlColor(), GetFont(), GetOptionsDB(), Sound::GetSound(), Sound::PlaySound(), Pts(), TextColor(), UserString(), WndColor(), and WndOuterBorderColor().
Referenced by OptionsWnd::CompleteConstruction(), GetShipDesignManager(), HumanClientApp::HumanClientApp(), HumanClientApp::LoadSinglePlayerGame(), HumanClientApp::MultiPlayerGame(), HumanClientApp::NewSinglePlayerGame(), anonymous_namespace{OptionsWnd.cpp}::BrowseForPathButtonFunctor::operator()(), WaitingForSPHostAck::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MPLobby::react(), PlayingGame::react(), anonymous_namespace{DesignWnd.cpp}::ReportFileError(), HumanClientApp::RequestSavePreviews(), InGameMenu::Save(), and OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure().
MeterIcon()
std::shared_ptr< GG::Texture > ClientUI::MeterIcon (MeterType meter_type) static
directory holding artwork
References ArtDir(), GetTexture(), METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SPEED, METER_STEALTH, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by MilitaryPanel::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), MapWnd::CompleteConstruction(), FleetWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
PartIcon()
std::shared_ptr< GG::Texture > ClientUI::PartIcon (const std::string & part_name) static
directory holding artwork
References ArtDir(), GetPartType(), GetTexture(), and PartType::Icon().
Referenced by PartControl::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), SlotControl::SetPart(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
PlanetIcon()
std::shared_ptr< GG::Texture > ClientUI::PlanetIcon (PlanetType planet_type) static
directory holding artwork
References ArtDir(), and GetTexture().
Referenced by ModeratorActionsWnd::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
PlanetSizeIcon()
std::shared_ptr< GG::Texture > ClientUI::PlanetSizeIcon (PlanetSize planet_size) static
directory holding artwork
References ArtDir(), GetTexture(), SZ_ASTEROIDS, SZ_GASGIANT, SZ_HUGE, SZ_LARGE, SZ_MEDIUM, SZ_SMALL, and SZ_TINY.
Referenced by ModeratorActionsWnd::CompleteConstruction(), and GetShipDesignManager().
PlanetTypeFilePrefixes()
std::map< PlanetType, std::string > & ClientUI::PlanetTypeFilePrefixes () static
directory holding artwork
Referenced by GetShipDesignManager().
PrefixedTexturesAndDist()
ClientUI::TexturesAndDist ClientUI::PrefixedTexturesAndDist (const boost::filesystem::path & dir, const std::string & prefix, bool mipmap) private
References GetTexture(), m_prefixed_textures, SmallIntDist(), and TextureFileNameCompare().
Referenced by GetModuloTexture(), GetPrefixedTextures(), and GetRandomTexture().
Pts()
int ClientUI::Pts () static
default point size
References OptionsDB::Get(), and GetOptionsDB().
Referenced by OptionsWnd::ColorOption(), CensusBrowseWnd::CompleteConstruction(), SitRepPanel::CompleteConstruction(), ResourceBrowseWnd::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), ProductionWnd::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), WastedStockpiledResourceBrowseWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), FilterDialog::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), GameRulesPanel::CreateSectionHeader(), OptionsWnd::CreateSectionHeader(), CreditsWnd::CreditsWnd(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::DefaultHeight(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::DefaultHeight(), TechTreeWnd::TechTreeControls::DoButtonLayout(), ObjectListWnd::DoLayout(), SitRepPanel::DoLayout(), MultiPlayerLobbyWnd::DoLayout(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::DoLayout(), CensusRowPanel::DoLayout(), EncyclopediaDetailPanel::DoLayout(), GalaxySetupPanel::DoLayout(), ProductionWnd::DoLayout(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout(), BuildDesignatorWnd::BuildSelector::DoLayout(), SidePanel::PlanetPanel::DoLayout(), ResourceInfoPanel::DoLayout(), DesignWnd::PartPalette::DoLayout(), DesignWnd::BaseSelector::DoLayout(), DesignWnd::MainPanel::DoLayout(), ConditionWidget::DropListHeight(), ConditionWidget::DropListWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseLabelWidth(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::FleetDetailBrowseWnd(), FontBasedUpscale(), TechTreeWnd::LayoutPanel::TechPanel::FontSize(), anonymous_namespace{GalaxySetupWnd.cpp}::GameRulesList::GameRulesList(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), GetShipDesignManager(), anonymous_namespace{MultiIconValueIndicator.cpp}::IconSpacing(), anonymous_namespace{TextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), anonymous_namespace{IconTextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), anonymous_namespace{CensusBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), ConditionWidget::Init(), ResourceBrowseWnd::InitBuffer(), WastedStockpiledResourceBrowseWnd::InitBuffer(), SystemResourceSummaryBrowseWnd::Initialize(), MapWnd::InitTurn(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth(), anonymous_namespace{SidePanel.cpp}::LabelWidth(), TechTreeWnd::LayoutPanel::Layout(), anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::ListRowHeight(), SaveFileListBox::ListRowHeight(), PlayerListBox::ListRowHeight(), ObjectListBox::ListRowHeight(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), MessageBox(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseQtyWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), anonymous_namespace{CensusBrowseWnd.cpp}::MeterIconSize(), anonymous_namespace{PopulationPanel.cpp}::MeterIconSize(), anonymous_namespace{MilitaryPanel.cpp}::MeterIconSize(), anonymous_namespace{BuildingsPanel.cpp}::MeterIconSize(), anonymous_namespace{ResourcePanel.cpp}::MeterIconSize(), anonymous_namespace{SidePanel.cpp}::MeterIconSize(), MapWnd::MidTurnUpdate(), ResourceInfoPanel::MinUsableSize(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::NewLabelValue(), anonymous_namespace{OptionsWnd.cpp}::OptionsList::OptionsList(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerReadyBrowseWidth(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowColWidths(), TechTreeWnd::TechListBox::Populate(), CUIWnd::PositionButtons(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), SystemIcon::Refresh(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::Render(), MapWnd::RenderMovementLineETAIndicators(), HumanClientApp::ResetOrExitApp(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::ResetShipDesignLabels(), OptionsWnd::ResolutionOption(), anonymous_namespace{SidePanel.cpp}::RowHeight(), MapWnd::SetZoom(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::SizeMove(), ConditionWidget::SpinDropListWidth(), anonymous_namespace{FleetWnd.cpp}::StatIconSize(), anonymous_namespace{SidePanel.cpp}::SystemNameFontSize(), MapWnd::SystemNamePts(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth(), SitRepPanel::Update(), TechTreeWnd::TechListBox::Update(), ConditionWidget::UpdateParameterControls(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth(), and anonymous_namespace{SidePanel.cpp}::ValueWidth().
ResearchableTechFillColor()
GG::Clr ClientUI::ResearchableTechFillColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by BuildingIndicator::BuildingIndicator(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::QuantitySelector(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::Render(), and anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Render().
ResearchableTechTextAndBorderColor()
GG::Clr ClientUI::ResearchableTechTextAndBorderColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::QuantitySelector(), anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::Render(), and anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Render().
RestoreFromSaveData()
void ClientUI::RestoreFromSaveData (const SaveGameUIData & elem)
restores the UI state that was saved in an earlier call to GetSaveGameUIData().
References GetMapWnd(), and m_ship_designs.
Referenced by GetShipDesignManager().
RolloverLinkColor()
GG::Clr ClientUI::RolloverLinkColor () static
rollover color of UI links
References OptionsDB::Get(), and GetOptionsDB().
Referenced by LinkDecorator::DecorateRollover(), and GetShipDesignManager().
ScrollWidth()
int ClientUI::ScrollWidth () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by TechTreeWnd::LayoutPanel::ClientLowerRight(), TechTreeWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), anonymous_namespace{OptionsWnd.cpp}::FontTextureWnd::DoLayout(), TechTreeWnd::LayoutPanel::DoLayout(), SidePanel::PlanetPanelContainer::DoLayout(), GetShipDesignManager(), TechTreeWnd::InitializeWindows(), anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::ListRowSize(), PlayerListBox::ListRowSize(), BasesListBox::ListRowSize(), PartsListBox::Populate(), TechTreeWnd::TechListBox::Populate(), PartsListBox::SizeMove(), and TechTreeWnd::TechListBox::Update().
ShipDesignIcon()
std::shared_ptr< GG::Texture > ClientUI::ShipDesignIcon (int design_id) static
directory holding artwork
References ArtDir(), GetShipDesign(), GetTexture(), HullIcon(), and HullTexture().
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), and anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon().
ShowIntroScreen()
void ClientUI::ShowIntroScreen ()
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References HumanClientApp::GetApp(), m_intro_screen, m_map_wnd, m_message_wnd, m_multiplayer_lobby_wnd, and m_player_list_wnd.
Referenced by GetShipDesignManager().
ShowMultiPlayerLobbyWnd()
void ClientUI::ShowMultiPlayerLobbyWnd ()
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References HumanClientApp::GetApp(), m_intro_screen, m_map_wnd, m_message_wnd, m_multiplayer_lobby_wnd, and m_player_list_wnd.
Referenced by GetShipDesignManager().
SmallFleetButtonZoomThreshold()
double ClientUI::SmallFleetButtonZoomThreshold () static
the minimum zoom level of the map at which to show small fleet icons
References OptionsDB::Get(), and GetOptionsDB().
Referenced by MapWnd::FleetButtonSizeType(), and GetShipDesignManager().
SoundDir()
fs::path ClientUI::SoundDir () static
directory holding sound and music
References GetResourceDir().
Referenced by OptionsWnd::CompleteConstruction(), GetShipDesignManager(), and OptionsWnd::SoundFileOption().
SpecialIcon()
std::shared_ptr< GG::Texture > ClientUI::SpecialIcon (const std::string & special_name) static
directory holding artwork
References ArtDir(), GetSpecial(), GetTexture(), and Special::Graphic().
Referenced by GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), SpecialsPanel::Update(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
SpeciesIcon()
std::shared_ptr< GG::Texture > ClientUI::SpeciesIcon (const std::string & species_name) static
directory holding artwork
References ArtDir(), GetSpecies(), GetTexture(), Species::Graphic(), and parse::species().
Referenced by CensusRowPanel::CensusRowPanel(), MultiIconValueIndicator::CompleteConstruction(), PopulationPanel::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow().
StarTypeFilePrefixes()
std::map< StarType, std::string > & ClientUI::StarTypeFilePrefixes () static
directory holding artwork
References INVALID_STAR_TYPE, STAR_BLACK, STAR_BLUE, STAR_NEUTRON, STAR_NONE, STAR_ORANGE, STAR_RED, STAR_WHITE, and STAR_YELLOW.
Referenced by ModeratorActionsWnd::CompleteConstruction(), SystemIcon::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), and SidePanel::RefreshImpl().
StatDecrColor()
GG::Clr ClientUI::StatDecrColor () static
used to color decreasing stats text (eg "-3")
References OptionsDB::Get(), and GetOptionsDB().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), GetShipDesignManager(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), MultiMeterStatusBar::Render(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetTotalPointsCost(), and StatisticIcon::ValueColor().
StateButtonColor()
GG::Clr ClientUI::StateButtonColor () static
colour of selected state button markers
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager().
StatIncrColor()
GG::Clr ClientUI::StatIncrColor () static
used to color increasing stats text (eg "+2")
References OptionsDB::Get(), and GetOptionsDB().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), GetShipDesignManager(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), MultiMeterStatusBar::Render(), and StatisticIcon::ValueColor().
SystemCircleSize()
int ClientUI::SystemCircleSize () static
the width/height of the system-enclosing circle
References OptionsDB::Get(), GetOptionsDB(), and SystemIconSize().
Referenced by GetShipDesignManager(), and anonymous_namespace{MapWnd.cpp}::StarlaneEndPointsFromSystemPositions().
SystemIconSize()
int ClientUI::SystemIconSize () static
the width/height of a System/Icon at zoom = 1.0
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), MapWnd::InitSystemRenderingBuffers(), MapWnd::RenderSystems(), FieldIcon::SizeMove(), SystemIcon::SizeMove(), SystemCircleSize(), MapWnd::SystemIconSize(), and SystemSelectionIndicatorSize().
SystemNameTextColor()
GG::Clr ClientUI::SystemNameTextColor () static
the colour of system names that aren't owned by any player (as far as this client knows)
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), and OwnerColoredSystemName::OwnerColoredSystemName().
SystemSelectionIndicatorRPM()
int ClientUI::SystemSelectionIndicatorRPM () static
revolutions per minute to rotate system selection indicator
References OptionsDB::Get(), and GetOptionsDB().
Referenced by SystemIcon::CompleteConstruction(), FleetButton::FleetButton(), and GetShipDesignManager().
SystemSelectionIndicatorSize()
int ClientUI::SystemSelectionIndicatorSize () static
the width/height of a system selection indicator
References OptionsDB::Get(), GetOptionsDB(), and SystemIconSize().
Referenced by GetShipDesignManager(), FieldIcon::SizeMove(), and SystemIcon::SizeMove().
SystemTinyIconSizeThreshold()
int ClientUI::SystemTinyIconSizeThreshold () static
the width/height of a system icon below which the tiny system icons should be used
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), and MapWnd::RenderSystems().
TechIcon()
std::shared_ptr< GG::Texture > ClientUI::TechIcon (const std::string & tech_name) static
directory holding artwork
References ArtDir(), Tech::Category(), CategoryIcon(), TechManager::GetTech(), GetTechManager(), GetTexture(), and Tech::Graphic().
Referenced by TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), GetShipDesignManager(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), and TechRowBrowseWnd().
TechWndProgressBarBackgroundColor()
GG::Clr ClientUI::TechWndProgressBarBackgroundColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by BuildingIndicator::BuildingIndicator(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), and anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel().
TechWndProgressBarColor()
GG::Clr ClientUI::TechWndProgressBarColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by BuildingIndicator::BuildingIndicator(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), GetShipDesignManager(), and anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel().
TextColor()
GG::Clr ClientUI::TextColor () static
color of UI text
References OptionsDB::Get(), and GetOptionsDB().
Referenced by SaveFileColumn::CellForColumn(), MultiPlayerLobbyWnd::ChatMessage(), SaveFileDialog::CheckChoiceValidity(), anonymous_namespace{SystemIcon.cpp}::ColorNameByOwners(), FleetDataPanel::ColorTextForSelect(), anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), PromptRow::CompleteConstruction(), OptionsWnd::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), SidePanel::CompleteConstruction(), EncyclopediaDetailPanel::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), InGameMenu::Concede(), OptionsWnd::FileOptionImpl(), GetShipDesignManager(), HumanClientApp::HumanClientApp(), ColorSelector::LClick(), MapWnd::MapScaleLine::MapScaleLine(), MessageBox(), CUIStyle::NewTabBarTab(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), SidePanel::SystemNameDropDownList::RClick(), SidePanel::PlanetPanel::Refresh(), CUIWnd::Render(), MapWnd::RenderSystems(), HumanClientApp::ResetOrExitApp(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Select(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetTotalPointsCost(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), and StatisticIcon::ValueColor().
TinyFleetButtonZoomThreshold()
double ClientUI::TinyFleetButtonZoomThreshold () static
the minimum zoom level of the map at which to show tiny (any) fleet icons
References OptionsDB::Get(), and GetOptionsDB().
Referenced by MapWnd::FleetButtonSizeType(), GetShipDesignManager(), and MapWnd::RenderFleetMovementLines().
TitlePts()
int ClientUI::TitlePts () static
default point size to use for window title
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), CUIWnd::InitButtons(), CUIWnd::PositionButtons(), and CUIWnd::TopBorder().
UnresearchableTechFillColor()
GG::Clr ClientUI::UnresearchableTechFillColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager().
UnresearchableTechTextAndBorderColor()
GG::Clr ClientUI::UnresearchableTechTextAndBorderColor () static
directory holding artwork
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager().
WndColor()
GG::Clr ClientUI::WndColor () static
background color of a UI window
References OptionsDB::Get(), and GetOptionsDB().
Referenced by CensusBrowseWnd::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), OptionsWnd::CompleteConstruction(), TechTreeWnd::LayoutPanel::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), GetShipDesignManager(), ShipFightersBrowseWnd::Initialize(), MessageBox(), CUIStyle::NewTabBarTab(), SidePanel::SystemNameDropDownList::RClick(), MultiMeterStatusBar::Render(), CensusBrowseWnd::Render(), TextBrowseWnd::Render(), GraphControl::Render(), IconTextBrowseWnd::Render(), SystemResourceSummaryBrowseWnd::Render(), ResourceBrowseWnd::Render(), MeterBrowseWnd::Render(), MultiIconValueIndicator::Render(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Render(), DesignWnd::Render(), WastedStockpiledResourceBrowseWnd::Render(), CensusRowPanel::Render(), BuildingIndicator::Render(), CUIWnd::Render(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::Render(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::Render(), CUIToolBar::Render(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), FleetDataPanel::Render(), ObjectPanel::Render(), TechTreeWnd::TechListBox::TechRow::Render(), BasesListBox::BasesListBoxRow::Render(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::Render(), CUIArrowButton::RenderPressed(), CUIArrowButton::RenderRollover(), CUIArrowButton::RenderUnpressed(), and HumanClientApp::ResetOrExitApp().
WndInnerBorderColor()
GG::Clr ClientUI::WndInnerBorderColor () static
color of the innermost border
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), CUIWnd::InitButtons(), CUI_MinRestoreButton::Render(), GameRulesPanel::Render(), MultiPlayerLobbyWnd::Render(), EncyclopediaDetailPanel::Render(), MultiPlayerLobbyWnd::PlayerLabelRow::Render(), CUIWnd::Render(), GalaxySetupWnd::Render(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), FleetDataPanel::Render(), and ObjectPanel::Render().
WndOuterBorderColor()
GG::Clr ClientUI::WndOuterBorderColor () static
color of the outermost border
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetShipDesignManager(), HumanClientApp::HumanClientApp(), MessageBox(), SidePanel::SystemNameDropDownList::RClick(), MultiMeterStatusBar::Render(), CensusBrowseWnd::Render(), TextBrowseWnd::Render(), GraphControl::Render(), IconTextBrowseWnd::Render(), ResourceBrowseWnd::Render(), SystemResourceSummaryBrowseWnd::Render(), MeterBrowseWnd::Render(), AccordionPanel::Render(), MultiIconValueIndicator::Render(), MultiPlayerLobbyWnd::PlayerLabelRow::Render(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Render(), WastedStockpiledResourceBrowseWnd::Render(), CensusRowPanel::Render(), BuildingIndicator::Render(), CUIWnd::Render(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render(), anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::Render(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), SaveFileRow::Render(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::Render(), SidePanel::PlanetPanel::Render(), CUIToolBar::Render(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), FleetDataPanel::Render(), ObjectPanel::Render(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::Render(), and HumanClientApp::ResetOrExitApp().
ZoomToBuilding()
bool ClientUI::ZoomToBuilding (int id)
Zooms to a particular building on the galaxy map and opens the sidepanel to show it.
References GetBuilding(), ZoomToBuildingType(), and ZoomToPlanet().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToObject().
ZoomToBuildingType()
bool ClientUI::ZoomToBuildingType (const std::string & building_type_name)
Opens the production screen and presents a description of the given building type.
References GetBuildingType(), and GetMapWnd().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), BuildingIndicator::RClick(), ZoomToBuilding(), and ZoomToContent().
ZoomToCombatLog()
bool ClientUI::ZoomToCombatLog (int id)
Opens combat log for indicated combat.
References GetCombatLogManager(), and GetMapWnd().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), and EncyclopediaDetailPanel::HandleLinkClick().
ZoomToContent()
bool ClientUI::ZoomToContent (const std::string & name, bool reverse_lookup = false)
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References GetBuildingTypeManager(), GetHullTypeManager(), GetPartTypeManager(), GetSpeciesManager(), GetTechManager(), SpecialNames(), UserString(), ZoomToBuildingType(), ZoomToShipHull(), ZoomToShipPart(), ZoomToSpecial(), ZoomToSpecies(), and ZoomToTech().
Referenced by GetShipDesignManager().
ZoomToEmpire()
bool ClientUI::ZoomToEmpire (int empire_id)
Opens the ??? screen and presents a description of the given empire.
References GetEmpire(), and GetMapWnd().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and PlayerListWnd::PlayerRightClicked().
ZoomToEncyclopediaEntry()
bool ClientUI::ZoomToEncyclopediaEntry (const std::string & str)
Opens the encyclodedia window and presents the entry for the given term.
References GetMapWnd().
Referenced by SitRepPanel::DismissalMenu(), GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), and CombatReportWnd::Impl::HandleLinkClick().
ZoomToField()
bool ClientUI::ZoomToField (int id)
Zooms to a particular field on the map.
Referenced by GetShipDesignManager(), CombatReportWnd::Impl::HandleLinkClick(), and EncyclopediaDetailPanel::HandleLinkClick().
ZoomToFieldType()
bool ClientUI::ZoomToFieldType (const std::string & field_type_name)
Opens the ??? screen and presents a description of the given field type.
References GetFieldType(), and GetMapWnd().
Referenced by GetShipDesignManager(), CombatReportWnd::Impl::HandleLinkClick(), and FieldIcon::RClick().
ZoomToFleet() [1/2]
bool ClientUI::ZoomToFleet (int id)
Zooms to a particular fleet on the galaxy map and opens the fleet window.
References GetFleet().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), ZoomToObject(), and ZoomToShip().
ZoomToFleet() [2/2]
void ClientUI::ZoomToFleet (std::shared_ptr< const Fleet > fleet)
Zooms to a particular fleet on the galaxy map and opens the fleet window.
References GetMapWnd().
ZoomToMeterTypeArticle()
bool ClientUI::ZoomToMeterTypeArticle (const std::string & meter_string)
Opens the encyclopedia and presents the entry for MeterType meter_type.
References GetMapWnd().
Referenced by MilitaryPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), ResourcePanel::EventFilter(), PopulationPanel::EventFilter(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::EventFilter(), FleetDataPanel::EventFilter(), GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), and CombatReportWnd::Impl::HandleLinkClick().
ZoomToObject() [1/2]
bool ClientUI::ZoomToObject (const std::string & name)
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References GetUniverse(), and Objects().
Referenced by GetShipDesignManager(), and ObjectListWnd::ObjectDoubleClicked().
ZoomToObject() [2/2]
bool ClientUI::ZoomToObject (int id)
Return the IntroScreen.
Hides the MapWnd, MessageWnd and PlayerListWnd if visible, but doesn't create them just to hide them.
References ZoomToBuilding(), ZoomToFleet(), ZoomToPlanet(), ZoomToShip(), and ZoomToSystem().
ZoomToPlanet()
bool ClientUI::ZoomToPlanet (int id)
Zooms to a particular planet on the galaxy map and opens the sidepanel to show it, or if production screen is open selects it.
References GetMapWnd(), and GetPlanet().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), ZoomToBuilding(), and ZoomToObject().
ZoomToPlanetPedia()
bool ClientUI::ZoomToPlanetPedia (int id)
Opens the encyclodedia window and presents the entry for the given planet.
References GetMapWnd(), and GetPlanet().
Referenced by GetShipDesignManager(), ObjectListWnd::ObjectRightClicked(), and SidePanel::PlanetPanel::RClick().
ZoomToShip()
bool ClientUI::ZoomToShip (int id)
Zooms to a particular ship on the galaxy map and opens its fleet and/or ship window.
References GetShip(), and ZoomToFleet().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToObject().
ZoomToShipDesign()
bool ClientUI::ZoomToShipDesign (int design_id)
Opens the design screen and presents a description of the given ship design.
References GetMapWnd(), and GetShipDesign().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and FleetDetailPanel::ShipRightClicked().
ZoomToShipHull()
bool ClientUI::ZoomToShipHull (const std::string & hull_name)
Opens the design screen and presents a description of the given hull type.
References GetHullType(), and GetMapWnd().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToContent().
ZoomToShipPart()
bool ClientUI::ZoomToShipPart (const std::string & part_name)
Opens the design screen and presents a description of the given part type.
References GetMapWnd(), and GetPartType().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToContent().
ZoomToSpecial()
bool ClientUI::ZoomToSpecial (const std::string & special_name)
Opens the ??? screen and presents a description of the given special.
References GetMapWnd(), and GetSpecial().
Referenced by SpecialsPanel::EventFilter(), GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToContent().
ZoomToSpecies()
bool ClientUI::ZoomToSpecies (const std::string & species_name)
Opens the ??? screen and presents a description of the given species.
References GetMapWnd(), and GetSpecies().
Referenced by MultiIconValueIndicator::EventFilter(), PopulationPanel::EventFilter(), GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToContent().
ZoomToSystem() [1/2]
bool ClientUI::ZoomToSystem (int id)
Zooms to a particular system on the galaxy map and opens the sidepanel to show it.
References GetSystem().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToObject().
ZoomToSystem() [2/2]
void ClientUI::ZoomToSystem (std::shared_ptr< const System > system)
Zooms to a system on the galaxy map.
References GetMapWnd().
ZoomToTech()
bool ClientUI::ZoomToTech (const std::string & tech_name)
Opens the technology screen and presents a description of the given technology.
References GetMapWnd(), and GetTech().
Referenced by GetShipDesignManager(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and ZoomToContent().
Member Data Documentation
m_intro_screen
std::shared_ptr<IntroScreen> ClientUI::m_intro_screen private
splash screen / main menu when starting program
Referenced by ClientUI(), GetIntroScreen(), ShowIntroScreen(), and ShowMultiPlayerLobbyWnd().
m_map_wnd
std::shared_ptr<MapWnd> ClientUI::m_map_wnd mutable private
the galaxy map
Referenced by GetMapWnd(), GetMapWndConst(), ShowIntroScreen(), and ShowMultiPlayerLobbyWnd().
m_message_wnd
std::shared_ptr<MessageWnd> ClientUI::m_message_wnd private
the messages / chat display
Referenced by ClientUI(), DumpObject(), GetMessageWnd(), InitializeWindows(), ShowIntroScreen(), and ShowMultiPlayerLobbyWnd().
m_multiplayer_lobby_wnd
std::shared_ptr<MultiPlayerLobbyWnd> ClientUI::m_multiplayer_lobby_wnd private
the multiplayer lobby
Referenced by ClientUI(), GetMultiPlayerLobbyWnd(), ShowIntroScreen(), and ShowMultiPlayerLobbyWnd().
m_password_enter_wnd
std::shared_ptr<PasswordEnterWnd> ClientUI::m_password_enter_wnd private
the authentication window
Referenced by ClientUI(), and GetPasswordEnterWnd().
m_player_list_wnd
std::shared_ptr<PlayerListWnd> ClientUI::m_player_list_wnd private
the players list
Referenced by ClientUI(), GetPlayerListWnd(), InitializeWindows(), ShowIntroScreen(), and ShowMultiPlayerLobbyWnd().
m_prefixed_textures
PrefixedTextures ClientUI::m_prefixed_textures private
Referenced by PrefixedTexturesAndDist().
m_savefile_dialog
std::shared_ptr<SaveFileDialog> ClientUI::m_savefile_dialog private
Referenced by GetFilenameWithSaveFileDialog(), and GetSaveFileDialog().
m_ship_designs
std::unique_ptr<ShipDesignManager> ClientUI::m_ship_designs private
ship designs the client knows about, and their ordering in the UI
Referenced by GetSaveGameUIData(), GetShipDesignManager(), and RestoreFromSaveData().
s_the_UI
ClientUI * ClientUI::s_the_UI = nullptr static private
the singleton ClientUI object
Referenced by ClientUI(), GetClientUI(), HaloStarTypeFilePrefixes(), and ~ClientUI().
The documentation for this class was generated from the following files:
ClientUI.h
ClientUI.cpp