FreeOrion: ScrapOrder Class Reference
ScrapOrder Class Reference
the Order subclass that represents the scrapping / recycling / destroying a building or ship owned by an empire.
#include <Order.h>
Public Member Functions
Structors
ScrapOrder (int empire, int object_id)
Accessors
int ObjectID () const
Returns ID of object selected in this order.
Public Member Functions inherited from Order
void Execute () const
Executes the order on the Universe and Empires.
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Order ()
ctor taking the ID of the Empire issuing the order.
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
ctor taking the ID of the Empire issuing the order.
int EmpireID () const
Returns the ID of the Empire issuing the order.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
Static Public Member Functions
static bool Check (int empire_id, int object_id)
Private Member Functions
ScrapOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
bool UndoImpl () const override
Private Attributes
int m_object_id = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents the scrapping / recycling / destroying a building or ship owned by an empire.
Constructor & Destructor Documentation
ScrapOrder() [1/2]
ScrapOrder::ScrapOrder (int empire, int object_id)
References Check().
ScrapOrder() [2/2]
ScrapOrder::ScrapOrder () private default
Member Function Documentation
Check()
bool ScrapOrder::Check (int empire_id, int object_id) static
References ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, and Objects().
Referenced by ExecuteImpl(), and ScrapOrder().
ExecuteImpl()
void ScrapOrder::ExecuteImpl () const override private virtual
Preconditions:
m_object_id must be the ID of an object owned by issuing empire
the object must be scrappable: ships or buildings
Postconditions:
the object is marked to be scrapped during the next turn processing.
Implements Order.
References Check(), Order::EmpireID(), Order::GetValidatedEmpire(), m_object_id, and Objects().
ObjectID()
int ScrapOrder::ObjectID () const inline
Returns ID of object selected in this order.
References Order::ExecuteImpl(), and Order::UndoImpl().
serialize()
template<typename Archive > void ScrapOrder::serialize (Archive & ar, const unsigned int version) private
UndoImpl()
bool ScrapOrder::UndoImpl () const override private virtual
Reimplemented from Order.
References Order::EmpireID(), Order::GetValidatedEmpire(), m_object_id, and Objects().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_object_id
int ScrapOrder::m_object_id = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp