FreeOrion: ScopedTimer Class Reference
ScopedTimer Class Reference
Logs period during which this object existed.
#include <ScopedTimer.h>
Classes
class Impl
Public Member Functions
ScopedTimer (std::string timed_name="", bool enable_output=false, std::chrono::microseconds threshold=std::chrono::milliseconds(1))
ScopedTimer (std::string timed_name, std::chrono::microseconds threshold)
ScopedTimer (std::function< std::string()> output_text_fn, std::chrono::microseconds threshold)
~ScopedTimer ()
double duration () const
std::string DurationString () const
void restart ()
Private Attributes
std::unique_ptr< Impl > const m_impl
Detailed Description
Logs period during which this object existed.
Created in the scope of a function, and passed the appropriate name, it will output to DebugLogger() the time elapsed while the function was executing.
If enable_output is true and duration is greater than threshold then print output.
Constructor & Destructor Documentation
ScopedTimer() [1/3]
ScopedTimer::ScopedTimer (std::string timed_name = "", bool enable_output = false, std::chrono::microseconds threshold = std::chrono::milliseconds(1)) explicit
ScopedTimer() [2/3]
ScopedTimer::ScopedTimer (std::string timed_name, std::chrono::microseconds threshold)
ScopedTimer() [3/3]
ScopedTimer::ScopedTimer (std::function< std::string()> output_text_fn, std::chrono::microseconds threshold)
~ScopedTimer()
ScopedTimer::~ScopedTimer ()
Note
~ScopedTimer is required because Impl is defined here.
Member Function Documentation
duration()
double ScopedTimer::duration () const
References m_impl.
Referenced by TechTreeWnd::TechListBox::Update(), and SectionedScopedTimer::Impl::~Impl().
DurationString()
std::string ScopedTimer::DurationString () const
References m_impl.
Referenced by ExtractGameStartMessageData(), PythonAI::GenerateOrders(), and TechTreeWnd::TechListBox::Populate().
restart()
void ScopedTimer::restart ()
References m_impl.
Referenced by ExtractGameStartMessageData(), and TechTreeWnd::TechListBox::Update().
Member Data Documentation
m_impl
std::unique_ptr<Impl> const ScopedTimer::m_impl private
Referenced by duration(), DurationString(), and restart().
The documentation for this class was generated from the following files:
ScopedTimer.h
ScopedTimer.cpp