FreeOrion: Effect::SetPlanetType Class Reference
Effect::SetPlanetType Class Reference
#include <Effect.h>
Public Member Functions
SetPlanetType (ValueRef::ValueRefBase< PlanetType > *type)
virtual ~SetPlanetType ()
std::string Dump () const override
void Execute (const ScriptingContext &context) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual unsigned int GetCheckSum () const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< PlanetType > * m_type
Friends
class boost::serialization::access
Detailed Description
Sets the planet type of the target to type. This has no effect on non-Planet targets. Note that changing the type of a PT_ASTEROID or PT_GASGIANT planet will also change its size to SZ_TINY or SZ_HUGE, respectively. Similarly, changing type to PT_ASTEROID or PT_GASGIANT will also cause the size to change to SZ_ASTEROID or SZ_GASGIANT, respectively.
Constructor & Destructor Documentation
Effect::SetPlanetType::SetPlanetType (ValueRef::ValueRefBase< PlanetType > * type) explicit
Effect::SetPlanetType::~SetPlanetType () virtual
References m_type.
Member Function Documentation
std::string Effect::SetPlanetType::Dump () const override virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_type.
void Effect::SetPlanetType::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ValueRef::ValueRefBase< T >::Eval(), m_type, SZ_ASTEROIDS, SZ_GASGIANT, SZ_HUGE, and SZ_TINY.
template<class Archive > void Effect::SetPlanetType::serialize (Archive & ar, const unsigned int version) private
void Effect::SetPlanetType::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_type, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<PlanetType>* Effect::SetPlanetType::m_type private
Referenced by Dump(), Execute(), SetTopLevelContent(), and ~SetPlanetType().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp