FreeOrion: RenameOrder Class Reference
RenameOrder Class Reference
the Order subclass that represents the renaming of a UniverseObject.
#include <Order.h>
Public Member Functions
RenameOrder (int empire, int object, const std::string &name)
std::string Dump () const override
const std::string & Name () const
Returns the new name of the fleet.
int ObjectID () const
Returns ID of fleet selected in this order.
Public Member Functions inherited from Order
Order ()=default
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()=default
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Static Public Member Functions
static bool Check (int empire, int object, const std::string &new_name)
Returns true when the Order parameters are valid.
Private Member Functions
RenameOrder ()=default
void ExecuteImpl () const override
Preconditions of execute:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_name
int m_object = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents the renaming of a UniverseObject.
Constructor & Destructor Documentation
RenameOrder() [1/2]
RenameOrder::RenameOrder (int empire, int object, const std::string & name)
References Check(), INVALID_OBJECT_ID, and m_object.
RenameOrder() [2/2]
RenameOrder::RenameOrder () private default
Member Function Documentation
Check()
bool RenameOrder::Check (int empire, int object, const std::string & new_name) static
Returns true when the Order parameters are valid.
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by ExecuteImpl(), FleetWnd::FleetRightClicked(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), RenameOrder(), and FleetDetailPanel::ShipRightClicked().
Dump()
std::string RenameOrder::Dump () const override virtual
Reimplemented from Order.
References anonymous_namespace{Order.cpp}::ExecutedTag(), FlexibleFormat(), m_name, m_object, and UserString().
ExecuteImpl()
void RenameOrder::ExecuteImpl () const override private virtual
Preconditions of execute:
the designated planet must exist, be owned by the issuing empire
Postconditions:
the planet focus is changed which=0(primary),1(secondary)
Implements Order.
References Check(), Order::EmpireID(), ObjectMap::get(), Order::GetValidatedEmpire(), m_name, m_object, and Objects().
Name()
const std::string& RenameOrder::Name () const inline
Returns the new name of the fleet.
References Order::ExecuteImpl().
ObjectID()
int RenameOrder::ObjectID () const inline
Returns ID of fleet selected in this order.
serialize()
template<typename Archive > void RenameOrder::serialize (Archive & ar, const unsigned int version) private
References m_name, and m_object.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_name
std::string RenameOrder::m_name private
Referenced by Dump(), ExecuteImpl(), serialize(), and ShipDesignOrder::serialize().
m_object
int RenameOrder::m_object = INVALID_OBJECT_ID private
Referenced by Dump(), ExecuteImpl(), RenameOrder(), and serialize().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp