FreeOrion: MultiMeterStatusBar Class Reference
MultiMeterStatusBar Class Reference
Graphically represets current value and projected changes to single meters or pairs of meters, using horizontal indicators.
#include <MultiMeterStatusBar.h>
Public Member Functions
MultiMeterStatusBar (GG::X w, int object_id, const std::vector< std::pair< MeterType, MeterType >> &meter_types)
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void Update ()
Private Attributes
std::vector< GG::Clr > m_bar_colours
std::shared_ptr< GG::Texture > m_bar_shading_texture
std::vector< float > m_initial_values
std::vector< std::pair< MeterType, MeterType > > m_meter_types
int m_object_id
std::vector< float > m_projected_values
std::vector< float > m_target_max_values
Detailed Description
Graphically represets current value and projected changes to single meters or pairs of meters, using horizontal indicators.
Constructor & Destructor Documentation
MultiMeterStatusBar()
MultiMeterStatusBar::MultiMeterStatusBar (GG::X w, int object_id, const std::vector< std::pair< MeterType, MeterType >> & meter_types)
References anonymous_namespace{ServerWrapper.cpp}::SetName(), and Update().
Member Function Documentation
MouseWheel()
void MultiMeterStatusBar::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Render()
void MultiMeterStatusBar::Render () override
References anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_HEIGHT(), anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_PAD(), anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, anonymous_namespace{MultiMeterStatusBar.cpp}::EDGE_PAD(), Meter::INVALID_VALUE, m_bar_colours, m_bar_shading_texture, m_initial_values, m_projected_values, m_target_max_values, anonymous_namespace{MultiMeterStatusBar.cpp}::MULTI_METER_STATUS_BAR_DISPLAYED_METER_RANGE_INCREMENT, ClientUI::StatDecrColor(), ClientUI::StatIncrColor(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
Update()
void MultiMeterStatusBar::Update ()
References anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_HEIGHT(), anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_PAD(), Meter::Current(), anonymous_namespace{MultiMeterStatusBar.cpp}::EDGE_PAD(), ErrorLogger, ObjectMap::get(), Meter::Initial(), Meter::INVALID_VALUE, m_bar_colours, m_initial_values, m_meter_types, m_object_id, m_projected_values, m_target_max_values, anonymous_namespace{MultiMeterStatusBar.cpp}::MeterColor(), and Objects().
Referenced by MultiMeterStatusBar().
Member Data Documentation
m_bar_colours
std::vector<GG::Clr> MultiMeterStatusBar::m_bar_colours private
Referenced by Render(), and Update().
m_bar_shading_texture
std::shared_ptr<GG::Texture> MultiMeterStatusBar::m_bar_shading_texture private
Referenced by Render().
m_initial_values
std::vector<float> MultiMeterStatusBar::m_initial_values private
Referenced by Render(), and Update().
m_meter_types
std::vector<std::pair<MeterType, MeterType> > MultiMeterStatusBar::m_meter_types private
Referenced by Update().
m_object_id
int MultiMeterStatusBar::m_object_id private
Referenced by Update().
m_projected_values
std::vector<float> MultiMeterStatusBar::m_projected_values private
Referenced by Render(), and Update().
m_target_max_values
std::vector<float> MultiMeterStatusBar::m_target_max_values private
Referenced by Render(), and Update().
The documentation for this class was generated from the following files:
MultiMeterStatusBar.h
MultiMeterStatusBar.cpp