FreeOrion: LinkDecorator Class Reference
LinkDecorator Class Reference
A class that can be subclassed to give types of links decorations in link text.
#include <LinkText.h>
Public Member Functions
virtual std::string Decorate (const std::string &target, const std::string &content) const
Gets called for each link of the type this decorator is assigned to.
virtual std::string DecorateRollover (const std::string &target, const std::string &content) const
Gets called when the mouse hovers over a link of the type this decorator is assigned to.
Structors
LinkDecorator ()
virtual ~LinkDecorator ()
Static Protected Member Functions
static int CastStringToInt (const std::string &str)
Try to convert str to int.
Detailed Description
A class that can be subclassed to give types of links decorations in link text.
"Decorations" here mean mostly wrapping the text in some styling tag or other, but a decorator is free to manipulate the decorated text in any way.
Constructor & Destructor Documentation
LinkDecorator()
LinkDecorator::LinkDecorator () inline
~LinkDecorator()
virtual LinkDecorator::~LinkDecorator () inline virtual
References CastStringToInt(), anonymous_namespace{XMLDoc.cpp}::content, Decorate(), and DecorateRollover().
Member Function Documentation
CastStringToInt()
int LinkDecorator::CastStringToInt (const std::string & str) static protected
Try to convert str to int.
Returns -1 if
Parameters
str conversion to an int fails. Helper for interpreting
str as an ID of an object in the game universe.
Referenced by ~LinkDecorator().
Decorate()
std::string LinkDecorator::Decorate (const std::string & target, const std::string & content) const virtual
Gets called for each link of the type this decorator is assigned to.
The return value is shown to the user as the link. The default implementation wraps content in an rgba tag that colors it by ClientUI::DefaultLinkColor
Parameters
target The target of the link. Usually an id of something or the name of an encyclopedia entry.
content The text the link tag was wrapped around.
Returns
The text that should be shown to the user in the place of content
Reimplemented in anonymous_namespace{SitRepPanel.cpp}::ColorEmpire, PathTypeDecorator, and ColorByOwner.
References ClientUI::DefaultLinkColor(), and anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE.
Referenced by PathTypeDecorator::Decorate(), TextLinker::LinkDefaultFormatTag(), and ~LinkDecorator().
DecorateRollover()
std::string LinkDecorator::DecorateRollover (const std::string & target, const std::string & content) const virtual
Gets called when the mouse hovers over a link of the type this decorator is assigned to.
The return value is shown to the user as the link. The default implementation wraps content in an rgba tag that colors it by ClientUI::RolloverLinkColor
Parameters
target The target of the link. Usually an id of something or the name of an encyclopedia entry.
content The text the link tag was wrapped around.
Returns
The text that should be shown to the user in the place of content
Reimplemented in PathTypeDecorator.
References anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE, and ClientUI::RolloverLinkColor().
Referenced by PathTypeDecorator::DecorateRollover(), TextLinker::LinkRolloverFormatTag(), and ~LinkDecorator().
The documentation for this class was generated from the following files:
LinkText.h
LinkText.cpp