FreeOrion: anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox Class Reference
anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox Class Reference
Public Member Functions
ProdQueueListBox ()
void CompleteConstruction () override
void EnableOrderIssuing (bool enable=true) override
Public Member Functions inherited from QueueListBox
QueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
void CompleteConstruction () override
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
int IteraterIndex (const const_iterator it)
scans this ListBox for the input iterator and returns its distance from begin(), or -1 if not present
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDupedSignal
boost::signals2::signal< void(GG::ListBox::iterator, bool)> QueueItemPausedSignal
boost::signals2::signal< void(GG::ListBox::iterator, int)> QueueItemRalliedToSignal
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemSplitSignal
boost::signals2::signal< void(GG::ListBox::iterator, bool)> QueueItemUseImperialPPSignal
boost::signals2::signal< void()> ShowPediaSignal
Public Attributes inherited from QueueListBox
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
Protected Member Functions
void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
Protected Member Functions inherited from QueueListBox
virtual std::function< void()> DeleteAction (GG::ListBox::iterator it) const
Return a functor that will signal that it should be deleted.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
virtual std::function< void()> MoveToBottomAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the bottom of the list.
virtual std::function< void()> MoveToTopAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the top of the list.
Constructor & Destructor Documentation
ProdQueueListBox()
anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ProdQueueListBox () inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::CompleteConstruction () inline override
References QueueListBox::CompleteConstruction().
EnableOrderIssuing()
void anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::EnableOrderIssuing (bool enable = true) inline override virtual
Reimplemented from QueueListBox.
References QueueListBox::EnableOrderIssuing().
ItemRightClickedImpl()
void anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) inline override protected virtual
Reimplemented from QueueListBox.
References ProductionQueue::Element::allowed_imperial_stockpile_use, ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::elem, anonymous_namespace{ProductionWnd.cpp}::QueueRow::elem, ClientApp::EmpireID(), ProductionQueue::ProductionItem::EnqueueConditionPassedAt(), ErrorLogger, FlexibleFormat(), HumanClientApp::GetApp(), GetShipDesign(), ProductionQueue::Element::item, ProductionQueue::Element::location, ProductionQueue::ProductionItem::name, ShipDesign::Name(), Objects(), ProductionQueue::Element::paused, ProductionQueue::Element::remaining, SidePanel::SystemID(), UserString(), and UserStringExists().
Member Data Documentation
QueueItemDupedSignal
boost::signals2::signal<void (GG::ListBox::iterator)> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::QueueItemDupedSignal
QueueItemPausedSignal
boost::signals2::signal<void (GG::ListBox::iterator, bool)> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::QueueItemPausedSignal
QueueItemRalliedToSignal
boost::signals2::signal<void (GG::ListBox::iterator, int)> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::QueueItemRalliedToSignal
QueueItemSplitSignal
boost::signals2::signal<void (GG::ListBox::iterator)> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::QueueItemSplitSignal
QueueItemUseImperialPPSignal
boost::signals2::signal<void (GG::ListBox::iterator, bool)> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::QueueItemUseImperialPPSignal
ShowPediaSignal
boost::signals2::signal<void ()> anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ShowPediaSignal
The documentation for this class was generated from the following file:
ProductionWnd.cpp