FreeOrion: CompletedDesignsListBox Class Reference
CompletedDesignsListBox Class Reference
Public Member Functions
CompletedDesignsListBox (const AvailabilityManager &availabilities_state, const boost::optional< std::string > &drop_type=boost::none)
Public Member Functions inherited from BasesListBox
BasesListBox (const AvailabilityManager &availabilities_state, const boost::optional< std::string > &drop_type=boost::none, const boost::optional< std::string > &empty_prompt=boost::none)
void ChildrenDraggedAway (const std::vector< GG::Wnd *> &wnds, const GG::Wnd *destination) override
void CompleteConstruction () override
virtual void Populate ()
void SetEmpireShown (int empire_id, bool refresh_list=true)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from QueueListBox
QueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
void CompleteConstruction () override
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
virtual void EnableOrderIssuing (bool enable=true)
int IteraterIndex (const const_iterator it)
scans this ListBox for the input iterator and returns its distance from begin(), or -1 if not present
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Protected Member Functions
void BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
void BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
void BaseRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
std::shared_ptr< Row > ChildrenDraggedAwayCore (const GG::Wnd *const wnd) override
If wnd is a valid dragged child return a replacement row.
void PopulateCore () override
An implementation of BasesListBox provides a PopulateCore to fill itself.
void QueueItemMoved (const GG::ListBox::iterator &row_it, const GG::ListBox::iterator &original_position_it) override
void ResetEmptyListPrompt () override
Reset the empty list prompt.
Protected Member Functions inherited from BasesListBox
const AvailabilityManager & AvailabilityState () const
int EmpireID () const
void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
GG::Pt ListRowSize ()
Protected Member Functions inherited from QueueListBox
virtual std::function< void()> DeleteAction (GG::ListBox::iterator it) const
Return a functor that will signal that it should be deleted.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
virtual std::function< void()> MoveToBottomAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the bottom of the list.
virtual std::function< void()> MoveToTopAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the top of the list.
Additional Inherited Members
Public Attributes inherited from BasesListBox
boost::signals2::signal< void(const ShipDesign *)> DesignClickedSignal
boost::signals2::signal< void(const std::string &, const std::vector< std::string > &)> DesignComponentsSelectedSignal
boost::signals2::signal< void(const ShipDesign *)> DesignRightClickedSignal
boost::signals2::signal< void(int)> DesignSelectedSignal
boost::signals2::signal< void(int)> DesignUpdatedSignal
boost::signals2::signal< void(const ShipHull *)> HullClickedSignal
boost::signals2::signal< void(const boost::uuids::uuid &)> SavedDesignSelectedSignal
Public Attributes inherited from QueueListBox
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
Static Public Attributes inherited from BasesListBox
static const std::string BASES_LIST_BOX_DROP_TYPE = "BasesListBoxRow"
Constructor & Destructor Documentation
CompletedDesignsListBox()
CompletedDesignsListBox::CompletedDesignsListBox (const AvailabilityManager & availabilities_state, const boost::optional< std::string > & drop_type = boost::none) inline
References BasesListBox::BaseDoubleClicked(), BasesListBox::BaseLeftClicked(), BasesListBox::BaseRightClicked(), BasesListBox::ChildrenDraggedAwayCore(), BasesListBox::PopulateCore(), BasesListBox::QueueItemMoved(), and BasesListBox::ResetEmptyListPrompt().
Member Function Documentation
BaseDoubleClicked()
void CompletedDesignsListBox::BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References BasesListBox::DesignSelectedSignal, and INVALID_DESIGN_ID.
BaseLeftClicked()
void CompletedDesignsListBox::BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References BasesListBox::DesignClickedSignal, BasesListBox::CompletedDesignListBoxRow::DesignID(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetShipDesign(), BasesListBox::Populate(), and anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns().
BaseRightClicked()
void CompletedDesignsListBox::BaseRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References ALL_EMPIRES, DebugLogger, anonymous_namespace{DesignWnd.cpp}::DeleteFromDisplayedDesigns(), BasesListBox::CompletedDesignListBoxRow::DesignID(), BasesListBox::DesignRightClickedSignal, BasesListBox::DesignUpdatedSignal, BasesListBox::EmpireID(), ErrorLogger, OptionsDB::Get(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetOptionsDB(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), GetShipDesign(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::InsertBefore(), INVALID_DESIGN_ID, OrderSet::IssueOrder(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::MoveBefore(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::OrderedIDs(), ClientApp::Orders(), BasesListBox::Populate(), OptionsDB::Set(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), and UserString().
ChildrenDraggedAwayCore()
std::shared_ptr< BasesListBox::Row > CompletedDesignsListBox::ChildrenDraggedAwayCore (const GG::Wnd *const wnd) override protected virtual
If wnd is a valid dragged child return a replacement row.
Otherwise return nullptr.
Implements BasesListBox.
References BasesListBox::AvailabilityState(), BasesListBox::CompletedDesignListBoxRow::DesignID(), ErrorLogger, GetShipDesign(), and BasesListBox::ListRowSize().
PopulateCore()
void CompletedDesignsListBox::PopulateCore () override protected virtual
An implementation of BasesListBox provides a PopulateCore to fill itself.
Implements BasesListBox.
References BasesListBox::AvailabilityState(), Universe::beginShipDesigns(), DebugLogger, BasesListBox::EmpireID(), Universe::endShipDesigns(), ErrorLogger, anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), GetShipDesign(), GetUniverse(), BasesListBox::ListRowSize(), and ShipDesign::Producible().
QueueItemMoved()
void CompletedDesignsListBox::QueueItemMoved (const GG::ListBox::iterator & row_it, const GG::ListBox::iterator & original_position_it) override protected virtual
Reimplemented from BasesListBox.
References BasesListBox::CompletedDesignListBoxRow::DesignID(), BasesListBox::EmpireID(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), INVALID_DESIGN_ID, BasesListBox::ListRowSize(), and anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::MoveBefore().
ResetEmptyListPrompt()
void CompletedDesignsListBox::ResetEmptyListPrompt () override protected virtual
Reset the empty list prompt.
Reimplemented from BasesListBox.
References GetOptionsDB(), QueueListBox::SetEmptyPromptText(), and UserString().
The documentation for this class was generated from the following file:
DesignWnd.cpp