FreeOrion: CUIIconButtonRepresenter Class Reference
CUIIconButtonRepresenter Class Reference
A FreeOrion styled icon toggle button.
#include <CUIControls.h>
Public Member Functions
CUIIconButtonRepresenter (std::shared_ptr< GG::SubTexture > icon, const GG::Clr &highlight_clr)
CUIIconButtonRepresenter (std::shared_ptr< GG::SubTexture > unchecked_icon, const GG::Clr &unchecked_clr, std::shared_ptr< GG::SubTexture > checked_icon, const GG::Clr &checked_clr)
void OnChecked (bool checked) const override
void Render (const GG::StateButton &button) const override
Private Attributes
GG::Clr m_checked_color
std::shared_ptr< GG::SubTexture > m_checked_icon
GG::Clr m_unchecked_color
std::shared_ptr< GG::SubTexture > m_unchecked_icon
Detailed Description
A FreeOrion styled icon toggle button.
Renders a SubTexture depending on the checked state of the CUIToggleButton. When the button has single texture and is unchecked, it renders the same icon recolored towards grey. If a second SubTexture is assigned to the button, it will render the appropriate SubTexture. When a mouse pointer hovers over this button, the opposing SubTexture and color are used and highlighted.
Constructor & Destructor Documentation
CUIIconButtonRepresenter() [1/2]
CUIIconButtonRepresenter::CUIIconButtonRepresenter (std::shared_ptr< GG::SubTexture > icon, const GG::Clr & highlight_clr)
CUIIconButtonRepresenter() [2/2]
CUIIconButtonRepresenter::CUIIconButtonRepresenter (std::shared_ptr< GG::SubTexture > unchecked_icon, const GG::Clr & unchecked_clr, std::shared_ptr< GG::SubTexture > checked_icon, const GG::Clr & checked_clr)
Member Function Documentation
OnChecked()
void CUIIconButtonRepresenter::OnChecked (bool checked) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Render()
void CUIIconButtonRepresenter::Render (const GG::StateButton & button) const override
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, m_checked_color, m_checked_icon, m_unchecked_color, and m_unchecked_icon.
Member Data Documentation
m_checked_color
GG::Clr CUIIconButtonRepresenter::m_checked_color private
Referenced by Render().
m_checked_icon
std::shared_ptr<GG::SubTexture> CUIIconButtonRepresenter::m_checked_icon private
Referenced by Render().
m_unchecked_color
GG::Clr CUIIconButtonRepresenter::m_unchecked_color private
Referenced by Render().
m_unchecked_icon
std::shared_ptr<GG::SubTexture> CUIIconButtonRepresenter::m_unchecked_icon private
Referenced by Render().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp