FreeOrion: MapWnd Class Reference
MapWnd Class Reference
This class is a window that graphically displays everything in the universe.
#include <MapWnd.h>
Classes
class MapScaleLine
Displays a notched line with number labels to indicate Universe distance on the map.
struct MovementLineData
contains information necessary to render a single fleet movement line on the main map.
Public Member Functions
MapWnd ()
~MapWnd ()
bool AutoEndTurnEnabled () const
void CenterOnMapCoord (double x, double y)
centers the map on map position (x, y)
void CenterOnObject (int id)
centers the map on object with id id
void CenterOnObject (std::shared_ptr< const UniverseObject > obj)
Centers the map on object id.
void ClearProjectedFleetMovementLines ()
removes all projected fleet movement lines
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
void DispatchFleetsExploring ()
called at each turn begin and when a fleet start/stop exploring to redispatch everyone.
void DoLayout ()
void EnableOrderIssuing (bool enable=true)
enables or disables order issuing and pressing the turn button.
FleetButton::SizeType FleetButtonSizeType () const
returns what size type (tiny, small, large) fleet buttons on this map are shown at
void ForgetObject (int id)
Forget object with id.
ModeratorActionSetting GetModeratorActionSetting () const
returns the currently set moderator action in this MapWnd's ModeratorActionsWnd.
void GetSaveGameUIData (SaveGameUIData &data) const
populates the relevant UI state that should be restored after a save-and-load cycle
void HideSystemNames ()
disables the system name text
bool InDesignViewMode () const
returns true if MapWnd is visible and usable behind a design window.
void InitTurn ()
called at the start of each turn
bool InProductionViewMode () const
returns true if MapWnd is visible and usable behind a production window.
bool InResearchViewMode () const
returns true if MapWnd is visible and usable behind a research window.
bool IsFleetExploring (const int fleet_id)
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void KeyRelease (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
void MidTurnUpdate ()
called after receiving updated Universe during turn processing, but not when the full turn update is received
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void PreRender () override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void RegisterPopup (std::shared_ptr< MapWndPopup > &&popup)
registers a MapWndPopup, which can be cleaned up with a call to DeleteAllPopups()
void RegisterWindows ()
registers owned wnds with the GUI (also registers message & player list wnds)
void RemoveFleet (int fleet_id)
removes specified fleet.
void RemovePopup (MapWndPopup *popup)
removes a MapWndPopup from the list cleaned up on a call to DeleteAllPopups()
void RemoveWindows ()
removes owned wnds from the GUI (also removes message & player list wnds)
void Render () override
void ReselectLastFleet ()
re-selects the most recent selected fleet, if a valid one exists
void ReselectLastSystem ()
re-selects the most recently selected system, if a valid one exists
void ResetEmpireShown ()
auto-resets the shown empire in any contained Wnds, to the current client's empire (if any)
void ResetTimeoutClock (int timeout)
start count down timeout seconds
void RestoreFromSaveData (const SaveGameUIData &data)
restores the UI state that was saved in an earlier call to GetSaveGameUIData().
void Sanitize ()
sanitizes the MapWnd after a game
GG::Pt ScreenCoordsFromUniversePosition (double universe_x, double universe_y) const
returns the position on the screen that corresponds to the specified universe X and Y coordinates.
int SelectedPlanetID () const
Returns the id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected.
void SelectFleet (int fleetID)
programatically selects fleets by ID
void SelectFleet (std::shared_ptr< Fleet > fleet)
Programatically selects fleets.
void SelectPlanet (int planetID)
programatically selects planets on sidepanels. catches signals from production wnd or sidepanel for when the user changes the selected planet
void SelectSystem (int systemID)
programatically selects systems on map, sidepanel, and production screen. catches signals from these when the user changes the selected system
void SetFleetExploring (const int fleet_id)
void SetFleetMovementLine (int fleet_id)
creates fleet movement line for a single fleet. Move lines originate from the fleet's button location.
void SetProjectedFleetMovementLine (int fleet_id, const std::list< int > &travel_route)
void SetProjectedFleetMovementLines (const std::vector< int > &fleet_ids, const std::list< int > &travel_route)
void ShowBuildingType (const std::string &building_type_name)
brings up the production screen and displays info about the buildtype type_name
void ShowCombatLog (int log_id)
brings up encyclopedia panel and displays info about the combat
void ShowEmpire (int empire_id)
brings up encyclopedia panel and displays info about the empire with id empire_id
void ShowEncyclopediaEntry (const std::string &str)
brings up encyclopedia panel and displays info about the specified string str
void ShowFieldType (const std::string &field_type_name)
brings up encyclopedia panel and displays info about the field type with name field_type_name
void ShowMeterTypeArticle (const std::string &meter_string)
brings up encyclopedia panel and displays info about the MeterType meter_type
void ShowPlanet (int planet_id)
brings up encyclopedia panel and displays info about the planet
void ShowPolicy (const std::string &policy_name)
brings up ??? and displays info about the policy with name policy_name
void ShowShipDesign (int design_id)
brings up the production screen and displays info about the buildtype type_name
void ShowShipHull (const std::string &ship_hull_name)
Brings up the production screen and displays info about the ShipHull ship_hull_name.
void ShowShipPart (const std::string &ship_part_name)
Brings up the production screen and displays info about the ShipPart ship_part_name.
void ShowSpecial (const std::string &special_name)
brings up encyclopedia panel and displays info about the special with name special_name
void ShowSpecies (const std::string &species_name)
brings up encyclopedia panel and displays info about the species with name species_name
void ShowSystemNames ()
enables the system name text
void ShowTech (const std::string &tech_name)
brings up the research screen and centers the tech tree on tech_name
void StopFleetExploring (const int fleet_id)
double SystemHaloScaleFactor () const
int SystemIconSize () const
int SystemNamePts () const
void TimerFiring (unsigned int ticks, GG::Timer *timer) override
std::pair< double, double > UniversePositionFromScreenCoords (GG::Pt screen_coords) const
returns the universe position (X and Y in pair) that corresponds to the specified screen coordinates.
double ZoomFactor () const
Public Attributes
boost::signals2::signal< void(int)> SystemBrowsedSignal
boost::signals2::signal< void(int)> SystemLeftClickedSignal
boost::signals2::signal< void(int)> SystemRightClickedSignal
boost::signals2::signal< void(double)> ZoomedSignal
Private Member Functions
void BuildingRightClicked (int building_id)
void ClearFieldRenderingBuffers ()
void ClearScaleCircleRenderingBuffer ()
void ClearStarfieldRenderingBuffers ()
void ClearStarlaneRenderingBuffers ()
void ClearSystemRenderingBuffers ()
void ClearVisibilityRadiiRenderingBuffers ()
void CloseAllPopups ()
bool CloseSystemView ()
closes off the current system view
void ConnectKeyboardAcceleratorSignals ()
connects signals from keyboard accelerators to various GUI responses
void CorrectMapPosition (GG::Pt &move_to_pt)
constrains move_to_pt so that if the map is repositioned to that location, it will not be problematically positioned, so that galaxy contents remain visible
template<typename FleetButtonMap , typename FleetsMap >
void CreateFleetButtonsOfType (FleetButtonMap &type_fleet_buttons, const FleetsMap &fleets_map, const FleetButton::SizeType &fleet_button_size)
Use the vectors of fleet ids from fleets_map to create fleet buttons in type_fleet_buttons and record the fleet buttons in m_fleet_buttons.
void DeferredRefreshFleetButtons ()
Removes old / existing and create new fleet buttons.
void DeleteFleetButtons ()
Delete all fleet buttons.
void DoFieldIconsLayout ()
does layout of field icons
void DoFleetButtonsLayout ()
does layout of fleet buttons
void DoSystemIconsLayout ()
does layout of system icons
bool EndTurn ()
void FieldRightClicked (int field_id)
void FleetButtonLeftClicked (const FleetButton *fleet_btn)
void FleetButtonRightClicked (const FleetButton *fleet_btn)
std::vector< int > FleetIDsOfFleetButtonsOverlapping (int fleet_id) const
Return fleets ids of all fleet buttons containing or overlapping the fleet button for fleet_id.
std::vector< int > FleetIDsOfFleetButtonsOverlapping (const FleetButton &fleet_btn) const
Return fleets ids of all fleet buttons containing or overlapping fleet_btn.
void FleetRightClicked (int fleet_id)
void FleetsRightClicked (const std::vector< int > &fleet_ids)
void HideAllPopups ()
void HideDesign ()
void HideEmpires ()
void HideGovernment ()
void HideMessages ()
void HideModeratorActions ()
void HideObjects ()
void HidePedia ()
void HideProduction ()
void HideResearch ()
void HideSidePanel ()
void HideSitRep ()
void InitFieldRenderingBuffers ()
void InitializeWindows ()
void InitScaleCircleRenderingBuffer ()
void InitStarlaneRenderingBuffers ()
initializes or refreshes buffers for rendering of starlanes
void InitSystemRenderingBuffers ()
initializes or refreshes buffers for rendering of system icons and galaxy gas
void InitTurnRendering ()
sets up rendering of system icons, galaxy gas, starlanes at start of turn
void InitVisibilityRadiiRenderingBuffers ()
bool KeyboardZoomIn ()
bool KeyboardZoomOut ()
void MouseEnteringSystem (int system_id, GG::Flags< GG::ModKey > mod_keys)
void MouseLeavingSystem (int system_id)
boost::optional< std::pair< double, double > > MovingFleetMapPositionOnLane (std::shared_ptr< const Fleet > fleet) const
Returns position on map where a moving fleet should be displayed.
void Pan (const GG::Pt &delta)
pans map
bool PanX (GG::X x=GG::X(50))
bool PanY (GG::Y y=GG::Y(50))
void PlanetDoubleClicked (int planet_id)
void PlanetRightClicked (int planet_id)
void PlotFleetMovement (int system_id, bool execute_move, bool append)
issues fleet move orders to appropriate fleets in active FleetWnd
void PushWndStack (std::shared_ptr< GG::Wnd > wnd)
void RefreshDetectionIndicator ()
void RefreshFleetButtons (bool recreate=true)
Mark all fleet buttons for a refresh.
void RefreshFleetButtonSelectionIndicators ()
marks (only) selected fleets' buttons as selected
void RefreshFleetResourceIndicator ()
void RefreshIndustryResourceIndicator ()
void RefreshInfluenceResourceIndicator ()
void RefreshPopulationIndicator ()
void RefreshResearchResourceIndicator ()
void RefreshSliders ()
shows or hides sliders on map
void RefreshTurnButtonTooltip ()
void RemoveFromWndStack (std::shared_ptr< GG::Wnd > wnd)
void RenderFields ()
renders field objects
void RenderFleetMovementLines ()
void RenderGalaxyGas ()
renders gassy substance to make shape of galaxy
void RenderMovementLine (const MapWnd::MovementLineData &move_line, float dot_size, float dot_spacing, float dot_shift, GG::Clr clr=GG::CLR_ZERO)
void RenderMovementLineETAIndicators (const MapWnd::MovementLineData &move_line, GG::Clr clr=GG::CLR_ZERO)
void RenderScaleCircle ()
void RenderStarfields ()
renders the background starfiends
void RenderStarlanes ()
renders the starlanes between the systems
void RenderStarlanes (GG::GL2DVertexBuffer &vertices, GG::GLRGBAColorBuffer &colours, double thickness, bool coloured, bool do_base_render)
void RenderSystemOverlays ()
renders textures "overlayed" on systems by effects
void RenderSystems ()
renders stars and halos
void RenderVisibilityRadii ()
void ReplotProjectedFleetMovement (bool append)
Find any projected movement plots and replots them with the current append state.
void RestoreSidePanel ()
restores side panel, sends to server changes made in other windows
bool ReturnToMap ()
void SelectedFleetsChanged ()
void SelectedShipsChanged ()
void SetZoom (double steps_in, bool update_slide)
sets zoom level of the main map to zoom step size to the power of steps_in and updates zoom slider position if update_slide is true
void SetZoom (double steps_in, bool update_slide, const GG::Pt &position)
sets zoom level of the main map to zoom step size to the power of steps_in and updates zoom slider position if update_slide is true. Keeps the screen position position in the same place after zooming
void ShipRightClicked (int fleet_id)
void ShipsRightClicked (const std::vector< int > &fleet_ids)
void ShowAllPopups ()
void ShowDesign ()
void ShowEmpires ()
void ShowGovernment ()
bool ShowGraphs ()
bool ShowMenu ()
void ShowMessages ()
void ShowModeratorActions ()
void ShowObjects ()
void ShowPedia ()
void ShowProduction ()
void ShowResearch ()
void ShowSitRep ()
void SystemDoubleClicked (int system_id)
void SystemLeftClicked (int system_id)
void SystemRightClicked (int system_id, GG::Flags< GG::ModKey > mod_keys)
void ToggleAutoEndTurn ()
bool ToggleDesign ()
bool ToggleEmpires ()
bool ToggleGovernment ()
bool ToggleMessages ()
bool ToggleModeratorActions ()
bool ToggleObjects ()
bool TogglePedia ()
bool ToggleProduction ()
bool ToggleResearch ()
bool ToggleSitRep ()
void UniverseObjectDeleted (std::shared_ptr< const UniverseObject > obj)
void UpdateEmpireResourcePools ()
recalculates production and predicted changes of player's empire's resource and population pools
void Zoom (int delta)
changes the zoom level of the main map by zoom step size to the power of delta (adds delta to the current zoom exponent)
void Zoom (int delta, const GG::Pt &position)
changes the zoom level of the main map by zoom step size to the power of delta (adds delta to the current zoom exponent) Keeps the screen position position in the same place after zooming
bool ZoomToHomeSystem ()
bool ZoomToNextFleet ()
bool ZoomToNextIdleFleet ()
bool ZoomToNextOwnedSystem ()
bool ZoomToNextSystem ()
bool ZoomToPrevFleet ()
bool ZoomToPrevIdleFleet ()
bool ZoomToPrevOwnedSystem ()
bool ZoomToPrevSystem ()
bool ZoomToSystemWithWastedPP ()
Private Attributes
bool m_auto_end_turn = false
should turns be ended automatically by this client?
std::shared_ptr< GG::Button > m_btn_auto_turn
button that toggles whether to automatically end turns;
std::shared_ptr< GG::Button > m_btn_design
std::shared_ptr< GG::Button > m_btn_empires
std::shared_ptr< GG::Button > m_btn_government
std::shared_ptr< GG::Button > m_btn_graphs
std::shared_ptr< GG::Button > m_btn_menu
std::shared_ptr< GG::Button > m_btn_messages
std::shared_ptr< GG::Button > m_btn_moderator
std::shared_ptr< GG::Button > m_btn_objects
std::shared_ptr< GG::Button > m_btn_pedia
std::shared_ptr< GG::Button > m_btn_production
std::shared_ptr< GG::Button > m_btn_research
std::shared_ptr< GG::Button > m_btn_siterep
std::shared_ptr< GG::Button > m_btn_turn
button that updates player's turn;
std::shared_ptr< CombatReportWnd > m_combat_report_wnd
shows graphical reports of combats
int m_current_fleet_id = INVALID_OBJECT_ID
int m_current_owned_system = INVALID_OBJECT_ID
bool m_deferred_recreate_fleet_buttons = false
indicates that refresh fleet button work should be done before rendering.
bool m_deferred_refresh_fleet_buttons = false
std::unordered_map< int, std::unordered_set< std::shared_ptr< FleetButton > > > m_departing_fleet_buttons
Icons representing fleets at a system that are departing, indexed by system.
std::shared_ptr< DesignWnd > m_design_wnd
design screen
std::shared_ptr< StatisticIcon > m_detection
GG::Pt m_drag_offset = {-GG::X1, -GG::Y1}
distance the cursor is from the upper-left corner of the window during a drag ((-1, -1) if no drag is occurring)
bool m_dragged = false
tracks whether or not a drag occurs during a left button down sequence of events
std::map< int, std::shared_ptr< FieldIcon > > m_field_icons
field icons in the main map, indexed by field id
GG::GL2DVertexBuffer m_field_scanline_circles
GG::GLTexCoordBuffer m_field_texture_coords
std::map< std::shared_ptr< GG::Texture >, std::pair< GG::GL2DVertexBuffer, GG::GL2DVertexBuffer > > m_field_vertices
First buffer is visible fields, second buffer is not visible (scanlined) fields for each texture.
std::shared_ptr< StatisticIcon > m_fleet
std::unordered_map< int, std::shared_ptr< FleetButton > > m_fleet_buttons
fleet icons, index by fleet
std::map< int, MovementLineData > m_fleet_lines
lines used for moving fleets in the main map
std::unordered_map< int, boost::signals2::connection > m_fleet_state_change_signals
std::set< int > m_fleets_exploring
std::shared_ptr< GG::Label > m_FPS
GG::GL2DVertexBuffer m_galaxy_gas_quad_vertices
GG::GLTexCoordBuffer m_galaxy_gas_texture_coords
std::shared_ptr< GovernmentWnd > m_government_wnd
government screen
bool m_in_production_view_mode = false
std::shared_ptr< StatisticIcon > m_industry
std::shared_ptr< GG::Button > m_industry_wasted
std::shared_ptr< StatisticIcon > m_influence
std::pair< int, int > m_line_between_systems = {INVALID_OBJECT_ID, INVALID_OBJECT_ID}
set when map should render line connecting 2 systems
bool m_menu_showing = false
set during ShowMenu() to prevent reentrency
std::shared_ptr< ModeratorActionsWnd > m_moderator_wnd
buttons to select moderator actions
std::unordered_map< std::pair< int, int >, std::unordered_set< std::shared_ptr< FleetButton > >, boost::hash< std::pair< int, int > > > m_moving_fleet_buttons
Icons representing fleets moving on a starlane, keyed by starlane end system ids.
std::unordered_map< std::pair< int, int >, std::vector< int >, boost::hash< std::pair< int, int > > > m_moving_fleets
Sets of fleet ids of fleets moving on a starlane, keyed by starlane end system ids.
std::shared_ptr< ObjectListWnd > m_object_list_wnd
filterable list of objects in universe
std::unordered_map< std::pair< double, double >, std::unordered_set< std::shared_ptr< FleetButton > >, boost::hash< std::pair< double, double > > > m_offroad_fleet_buttons
Icons representing fleets moving and not on a starlane, indexed by (x,y) location.
std::shared_ptr< EncyclopediaDetailPanel > m_pedia_panel
encyclpedia panel
std::shared_ptr< StatisticIcon > m_population
std::list< std::weak_ptr< MapWndPopup > > m_popups
list of currently active popup windows
std::shared_ptr< ProductionWnd > m_production_wnd
production screen
std::map< int, MovementLineData > m_projected_fleet_lines
lines that show the projected path of the active fleet in the FleetWnd
std::vector< std::pair< std::pair< std::size_t, std::size_t >, std::pair< std::size_t, std::size_t > > > m_radii_radii_vertices_indices_runs
GG::GLRGBAColorBuffer m_RC_starlane_colors
GG::GL2DVertexBuffer m_RC_starlane_vertices
bool m_ready_turn = false
is turn orders are ready and sent to server?
std::shared_ptr< StatisticIcon > m_research
std::shared_ptr< GG::Button > m_research_wasted
std::shared_ptr< ResearchWnd > m_research_wnd
research screen
GG::GL2DVertexBuffer m_scale_circle_vertices
std::shared_ptr< MapScaleLine > m_scale_line
indicates the on-screen distance that reprensents an in-universe distance
ScanlineRenderer m_scanline_shader
std::set< int > m_selected_fleet_ids
std::set< int > m_selected_ship_ids
std::shared_ptr< SidePanel > m_side_panel
planet view panel on the side of the main map
bool m_sidepanel_open_before_showing_other = false
was the sidepanel open before switching to production, research or design screens? If so, it should be restored when leaving them.
std::shared_ptr< SitRepPanel > m_sitrep_panel
sitrep panel
GG::GL2DVertexBuffer m_star_circle_vertices
std::map< std::shared_ptr< GG::Texture >, GG::GL2DVertexBuffer > m_star_core_quad_vertices
std::map< std::shared_ptr< GG::Texture >, GG::GL2DVertexBuffer > m_star_halo_quad_vertices
GG::GLTexCoordBuffer m_star_texture_coords
GG::GLRGBAColorBuffer m_starfield_colours
GG::GL3DVertexBuffer m_starfield_verts
GG::GLRGBAColorBuffer m_starlane_colors
std::map< std::pair< int, int >, LaneEndpoints > m_starlane_endpoints
map from starlane start and end system IDs (stored in pair in increasing order) to the universe coordiates at which to draw the starlane ends
GG::GL2DVertexBuffer m_starlane_vertices
std::unordered_map< int, std::unordered_set< std::shared_ptr< FleetButton > > > m_stationary_fleet_buttons
Icons representing fleets at a system that are not departing, indexed by system.
std::shared_ptr< StatisticIcon > m_stockpile
std::unordered_map< int, std::vector< boost::signals2::connection > > m_system_fleet_insert_remove_signals
std::unordered_map< int, std::shared_ptr< SystemIcon > > m_system_icons
system icons in the main map, indexed by system id
GG::Timer m_timeout_clock {1000}
clock to update remaining time
std::shared_ptr< GG::Label > m_timeout_remain
label to show remaining time
std::chrono::time_point< std::chrono::high_resolution_clock > m_timeout_time
std::shared_ptr< CUIToolBar > m_toolbar
GG::GLRGBAColorBuffer m_visibility_radii_border_colors
GG::GL2DVertexBuffer m_visibility_radii_border_vertices
GG::GLRGBAColorBuffer m_visibility_radii_colors
GG::GL2DVertexBuffer m_visibility_radii_vertices
std::vector< std::weak_ptr< GG::Wnd > > m_wnd_stack
stack of open windows, to allow closing them with escape in a LIFO order
std::shared_ptr< GG::Slider< double > > m_zoom_slider
allows user to set zoom level;
double m_zoom_steps_in = 1.0
number of zoom steps in. each 1.0 step increases display scaling by the same zoom step factor
Friends
struct IntroMenu
struct PlayingGame
struct PlayingTurn
struct WaitingForGameStart
Detailed Description
This class is a window that graphically displays everything in the universe.
Constructor & Destructor Documentation
MapWnd()
MapWnd::MapWnd ()
~MapWnd()
MapWnd::~MapWnd ()
Member Function Documentation
AutoEndTurnEnabled()
bool MapWnd::AutoEndTurnEnabled () const
References m_auto_end_turn.
BuildingRightClicked()
void MapWnd::BuildingRightClicked (int building_id) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), GGHumanClientApp::GetApp(), INVALID_OBJECT_ID, m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by CompleteConstruction().
CenterOnMapCoord()
void MapWnd::CenterOnMapCoord (double x, double y)
centers the map on map position (x, y)
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClientUpperLeft(), CorrectMapPosition(), GetOptionsDB(), and ZoomFactor().
Referenced by CenterOnObject(), and InitTurn().
CenterOnObject() [1/2]
void MapWnd::CenterOnObject (int id)
centers the map on object with id id
References CenterOnMapCoord(), and Objects().
Referenced by PlanetDoubleClicked(), SystemDoubleClicked(), ZoomToHomeSystem(), ZoomToNextFleet(), ZoomToNextIdleFleet(), ZoomToNextOwnedSystem(), ZoomToNextSystem(), ZoomToPrevFleet(), ZoomToPrevIdleFleet(), ZoomToPrevOwnedSystem(), ZoomToPrevSystem(), and ZoomToSystemWithWastedPP().
CenterOnObject() [2/2]
void MapWnd::CenterOnObject (std::shared_ptr< const UniverseObject > obj)
Centers the map on object id.
References CenterOnMapCoord().
ClearFieldRenderingBuffers()
void MapWnd::ClearFieldRenderingBuffers () private
References m_field_scanline_circles, m_field_texture_coords, and m_field_vertices.
Referenced by InitFieldRenderingBuffers(), and Sanitize().
ClearProjectedFleetMovementLines()
void MapWnd::ClearProjectedFleetMovementLines ()
removes all projected fleet movement lines
References m_projected_fleet_lines.
Referenced by InitTurnRendering(), ShowDesign(), ShowGovernment(), ShowMenu(), ShowObjects(), ShowPedia(), ShowProduction(), ShowResearch(), ShowSitRep(), and SystemRightClicked().
ClearScaleCircleRenderingBuffer()
void MapWnd::ClearScaleCircleRenderingBuffer () private
References m_scale_circle_vertices.
Referenced by InitScaleCircleRenderingBuffer(), and Sanitize().
ClearStarfieldRenderingBuffers()
void MapWnd::ClearStarfieldRenderingBuffers () private
References m_starfield_colours, and m_starfield_verts.
Referenced by RenderStarfields(), and Sanitize().
ClearStarlaneRenderingBuffers()
void MapWnd::ClearStarlaneRenderingBuffers () private
References m_RC_starlane_colors, m_RC_starlane_vertices, m_starlane_colors, and m_starlane_vertices.
Referenced by InitStarlaneRenderingBuffers(), and Sanitize().
ClearSystemRenderingBuffers()
void MapWnd::ClearSystemRenderingBuffers () private
References m_galaxy_gas_quad_vertices, m_galaxy_gas_texture_coords, m_star_circle_vertices, m_star_core_quad_vertices, m_star_halo_quad_vertices, and m_star_texture_coords.
Referenced by InitSystemRenderingBuffers(), and Sanitize().
ClearVisibilityRadiiRenderingBuffers()
void MapWnd::ClearVisibilityRadiiRenderingBuffers () private
References m_radii_radii_vertices_indices_runs, m_visibility_radii_border_colors, m_visibility_radii_border_vertices, m_visibility_radii_colors, and m_visibility_radii_vertices.
Referenced by InitVisibilityRadiiRenderingBuffers(), and Sanitize().
ClientUpperLeft()
GG::Pt MapWnd::ClientUpperLeft () const override
References anonymous_namespace{MapWnd.cpp}::AppHeight(), and anonymous_namespace{MapWnd.cpp}::AppWidth().
Referenced by CenterOnMapCoord(), LButtonDown(), Pan(), RestoreFromSaveData(), ScreenCoordsFromUniversePosition(), SetZoom(), and UniversePositionFromScreenCoords().
CloseAllPopups()
void MapWnd::CloseAllPopups () private
References m_popups.
Referenced by Sanitize().
CloseSystemView()
bool MapWnd::CloseSystemView () private
closes off the current system view
References INVALID_OBJECT_ID, m_side_panel, and SelectSystem().
CompleteConstruction()
void MapWnd::CompleteConstruction () override
References FleetUIManager::ActiveFleetWndChangedSignal, FleetUIManager::ActiveFleetWndSelectedFleetsChangedSignal, FleetUIManager::ActiveFleetWndSelectedShipsChangedSignal, anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClientUI::ArtDir(), BuildingRightClicked(), SidePanel::BuildingRightClickedSignal, CLOSABLE, anonymous_namespace{MapWnd.cpp}::COMBAT_REPORT_WND_NAME, ConnectKeyboardAcceleratorSignals(), DoLayout(), ClientUI::DumpObject(), Empires(), EndTurn(), FleetRightClicked(), FleetUIManager::FleetRightClickedSignal, FlexibleFormat(), GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), FleetUIManager::GetFleetUIManager(), GetGalaxySetupData(), GetOptionsDB(), GetSpeciesManager(), GetSupplyManager(), ClientUI::GetTexture(), GetUniverse(), anonymous_namespace{MapWnd.cpp}::GOVERNMENT_WND_NAME, HideEmpires(), HideGovernment(), HideMessages(), HideModeratorActions(), HideObjects(), HidePedia(), HideSitRep(), anonymous_namespace{MapWnd.cpp}::ICON_DUAL_WIDTH, anonymous_namespace{MapWnd.cpp}::ICON_SINGLE_WIDTH, anonymous_namespace{MapWnd.cpp}::ICON_SIZE, anonymous_namespace{MapWnd.cpp}::ICON_WIDTH, InitializeWindows(), anonymous_namespace{MapWnd.cpp}::InRect(), anonymous_namespace{MapWnd.cpp}::LAYOUT_MARGIN, m_btn_auto_turn, m_btn_design, m_btn_empires, m_btn_government, m_btn_graphs, m_btn_menu, m_btn_messages, m_btn_moderator, m_btn_objects, m_btn_pedia, m_btn_production, m_btn_research, m_btn_siterep, m_btn_turn, m_combat_report_wnd, m_design_wnd, m_detection, m_fleet, m_FPS, m_government_wnd, m_industry, m_industry_wasted, m_influence, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_population, m_production_wnd, m_research, m_research_wasted, m_research_wnd, m_scale_line, m_selected_fleet_ids, m_side_panel, m_sitrep_panel, m_stockpile, m_timeout_clock, m_timeout_remain, m_toolbar, m_zoom_slider, m_zoom_steps_in, anonymous_namespace{MapWnd.cpp}::MAP_PEDIA_WND_NAME, anonymous_namespace{MapWnd.cpp}::MAP_SIDEPANEL_WND_NAME, anonymous_namespace{MapWnd.cpp}::MENU_ICON_SIZE, ClientUI::MeterIcon(), anonymous_namespace{MapWnd.cpp}::MODERATOR_WND_NAME, anonymous_namespace{MapWnd.cpp}::OBJECT_WND_NAME, OptionsDB::OptionChangedSignal(), PINABLE, PlanetDoubleClicked(), SidePanel::PlanetDoubleClickedSignal, PlanetRightClicked(), SidePanel::PlanetRightClickedSignal, SidePanel::PlanetSelectedSignal, anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound(), PushWndStack(), RefreshIndustryResourceIndicator(), RefreshResearchResourceIndicator(), RefreshSliders(), RefreshTurnButtonTooltip(), GGHumanClientApp::RepositionWindowsSignal, SidePanel::ResourceCenterChangedSignal, anonymous_namespace{MapWnd.cpp}::SCALE_LINE_HEIGHT, anonymous_namespace{MapWnd.cpp}::SCALE_LINE_MAX_WIDTH, ClientUI::ScrollWidth(), SelectedFleetsChanged(), SelectedShipsChanged(), SelectPlanet(), SelectSystem(), anonymous_namespace{ServerWrapper.cpp}::SetName(), SetZoom(), ShipRightClicked(), FleetUIManager::ShipRightClickedSignal, ShowGraphs(), ShowMenu(), anonymous_namespace{MapWnd.cpp}::SITREP_WND_NAME, SidePanel::SystemID(), SidePanel::SystemSelectedSignal, ToggleAutoEndTurn(), ToggleDesign(), ToggleEmpires(), ToggleGovernment(), ToggleMessages(), ToggleModeratorActions(), ToggleObjects(), TogglePedia(), ToggleProduction(), ToggleResearch(), ToggleSitRep(), UniverseObjectDeleted(), Universe::UniverseObjectDeleteSignal, UpdateEmpireResourcePools(), UserString(), anonymous_namespace{MapWnd.cpp}::WndBottom(), anonymous_namespace{MapWnd.cpp}::WndLeft(), anonymous_namespace{MapWnd.cpp}::WndRight(), anonymous_namespace{MapWnd.cpp}::WndTop(), anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MAX_STEPS, anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MIN_STEPS, anonymous_namespace{MapWnd.cpp}::ZOOM_SLIDER_HEIGHT, ZoomFactor(), and ZoomToSystemWithWastedPP().
ConnectKeyboardAcceleratorSignals()
void MapWnd::ConnectKeyboardAcceleratorSignals () private
connects signals from keyboard accelerators to various GUI responses
References HotkeyManager::Connect(), EndTurn(), HotkeyManager::GetManager(), KeyboardZoomIn(), KeyboardZoomOut(), m_design_wnd, m_production_wnd, m_research_wnd, NoModalWndsOpenCondition(), PanX(), PanY(), HotkeyManager::RebuildShortcuts(), ReturnToMap(), ShowGraphs(), ShowMenu(), anonymous_namespace{MapWnd.cpp}::ToggleBoolOption(), ToggleDesign(), ToggleEmpires(), ToggleMessages(), ToggleObjects(), TogglePedia(), ToggleProduction(), ToggleResearch(), ToggleSitRep(), ZoomToHomeSystem(), ZoomToNextFleet(), ZoomToNextIdleFleet(), ZoomToNextOwnedSystem(), ZoomToNextSystem(), ZoomToPrevFleet(), ZoomToPrevIdleFleet(), ZoomToPrevOwnedSystem(), and ZoomToPrevSystem().
Referenced by CompleteConstruction().
CorrectMapPosition()
void MapWnd::CorrectMapPosition (GG::Pt & move_to_pt) private
constrains move_to_pt so that if the map is repositioned to that location, it will not be problematically positioned, so that galaxy contents remain visible
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), GetUniverse(), and ZoomFactor().
Referenced by CenterOnMapCoord(), LDrag(), Pan(), RestoreFromSaveData(), and SetZoom().
CreateFleetButtonsOfType()
template<typename FleetButtonMap , typename FleetsMap > void MapWnd::CreateFleetButtonsOfType (FleetButtonMap & type_fleet_buttons, const FleetsMap & fleets_map, const FleetButton::SizeType & fleet_button_size) private
Use the vectors of fleet ids from fleets_map to create fleet buttons in type_fleet_buttons and record the fleet buttons in m_fleet_buttons.
References ObjectMap::find(), FleetButtonLeftClicked(), FleetButtonRightClicked(), m_fleet_buttons, and Objects().
Referenced by DeferredRefreshFleetButtons().
DeferredRefreshFleetButtons()
void MapWnd::DeferredRefreshFleetButtons () private
Removes old / existing and create new fleet buttons.
Only called once per render interval.
References CreateFleetButtonsOfType(), DeleteFleetButtons(), DoFleetButtonsLayout(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), ErrorLogger, FleetButtonSizeType(), GGHumanClientApp::GetApp(), GetUniverse(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsMovingOnStarlane(), anonymous_namespace{MapWnd.cpp}::IsOffRoad(), anonymous_namespace{MapWnd.cpp}::IsQualifiedFleet(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), m_deferred_recreate_fleet_buttons, m_deferred_refresh_fleet_buttons, m_departing_fleet_buttons, m_fleet_buttons, m_moving_fleet_buttons, m_moving_fleets, m_offroad_fleet_buttons, m_stationary_fleet_buttons, Objects(), RefreshFleetButtonSelectionIndicators(), and SetFleetMovementLine().
Referenced by PreRender().
DeleteFleetButtons()
void MapWnd::DeleteFleetButtons () private
Delete all fleet buttons.
References m_departing_fleet_buttons, m_fleet_buttons, m_moving_fleet_buttons, m_offroad_fleet_buttons, and m_stationary_fleet_buttons.
Referenced by DeferredRefreshFleetButtons(), and Sanitize().
DispatchFleetsExploring()
void MapWnd::DispatchFleetsExploring ()
called at each turn begin and when a fleet start/stop exploring to redispatch everyone.
all systems ID for which an exploring fleet is in route and the fleet assigned
References anonymous_namespace{MapWnd.cpp}::AddNeighboorsToSet(), DebugLogger, ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), ObjectMap::find(), ObjectMap::get(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), anonymous_namespace{MapWnd.cpp}::GetOrderedFleetRoute(), GetUniverse(), anonymous_namespace{MapWnd.cpp}::IssueExploringFleetOrders(), m_fleets_exploring, Objects(), to_string(), TraceLogger, and WarnLogger.
Referenced by InitTurn(), SetFleetExploring(), and StopFleetExploring().
DoFieldIconsLayout()
void MapWnd::DoFieldIconsLayout () private
does layout of field icons
References ErrorLogger, ObjectMap::get(), m_field_icons, Objects(), and ZoomFactor().
Referenced by InitTurnRendering(), and SetZoom().
DoFleetButtonsLayout()
void MapWnd::DoFleetButtonsLayout () private
does layout of fleet buttons
References ErrorLogger, ObjectMap::get(), GetUniverse(), m_departing_fleet_buttons, m_moving_fleet_buttons, m_offroad_fleet_buttons, m_stationary_fleet_buttons, m_system_icons, MovingFleetMapPositionOnLane(), Universe::Objects(), Objects(), SystemIconSize(), and ZoomFactor().
Referenced by DeferredRefreshFleetButtons(), and SetZoom().
DoLayout()
void MapWnd::DoLayout ()
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), FleetUIManager::CullEmptyWnds(), ErrorLogger, ClientUI::GetClientUI(), FleetUIManager::GetFleetUIManager(), m_combat_report_wnd, m_design_wnd, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_production_wnd, m_research_wnd, m_side_panel, m_sitrep_panel, m_toolbar, and anonymous_namespace{MapWnd.cpp}::TOOLBAR_HEIGHT.
Referenced by CompleteConstruction().
DoSystemIconsLayout()
void MapWnd::DoSystemIconsLayout () private
does layout of system icons
References ErrorLogger, ObjectMap::get(), m_system_icons, Objects(), SystemIconSize(), and ZoomFactor().
Referenced by InitTurnRendering(), and SetZoom().
EnableOrderIssuing()
void MapWnd::EnableOrderIssuing (bool enable = true)
enables or disables order issuing and pressing the turn button.
References ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, CurrentTurn(), ClientApp::EmpireID(), FleetUIManager::EnableOrderIssuing(), FlexibleFormat(), GGHumanClientApp::GetApp(), ClientApp::GetClientType(), FleetUIManager::GetFleetUIManager(), m_btn_turn, m_design_wnd, m_government_wnd, m_moderator_wnd, m_production_wnd, m_ready_turn, m_research_wnd, m_side_panel, RefreshTurnButtonTooltip(), to_string(), and UserString().
EndTurn()
bool MapWnd::EndTurn () private
References ErrorLogger, GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), ClientUI::GetSaveGameUIData(), m_ready_turn, GGHumanClientApp::StartTurn(), and GGHumanClientApp::UnreadyTurn().
Referenced by CompleteConstruction(), and ConnectKeyboardAcceleratorSignals().
FieldRightClicked()
void MapWnd::FieldRightClicked (int field_id) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), GGHumanClientApp::GetApp(), m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by InitTurnRendering().
FleetButtonLeftClicked()
void MapWnd::FleetButtonLeftClicked (const FleetButton * fleet_btn) private
References FleetIDsOfFleetButtonsOverlapping(), FleetButton::Fleets(), FleetUIManager::GetFleetUIManager(), HideProduction(), INVALID_OBJECT_ID, m_in_production_view_mode, SelectFleet(), and FleetUIManager::WndForFleetIDs().
Referenced by CreateFleetButtonsOfType().
FleetButtonRightClicked()
void MapWnd::FleetButtonRightClicked (const FleetButton * fleet_btn) private
References FleetUIManager::ActiveFleetWnd(), ClientApp::EmpireID(), FleetIDsOfFleetButtonsOverlapping(), FleetsRightClicked(), ForgetObject(), GGHumanClientApp::GetApp(), FleetUIManager::GetFleetUIManager(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), Objects(), and UserString().
Referenced by CreateFleetButtonsOfType().
FleetButtonSizeType()
FleetButton::SizeType MapWnd::FleetButtonSizeType () const
returns what size type (tiny, small, large) fleet buttons on this map are shown at
References ClientUI::BigFleetButtonZoomThreshold(), FleetButton::LARGE, FleetButton::MEDIUM, ClientUI::MediumFleetButtonZoomThreshold(), FleetButton::NONE, FleetButton::SMALL, ClientUI::SmallFleetButtonZoomThreshold(), FleetButton::TINY, ClientUI::TinyFleetButtonZoomThreshold(), and ZoomFactor().
Referenced by DeferredRefreshFleetButtons(), and SetZoom().
FleetIDsOfFleetButtonsOverlapping() [1/2]
std::vector< int > MapWnd::FleetIDsOfFleetButtonsOverlapping (int fleet_id) const private
Return fleets ids of all fleet buttons containing or overlapping the fleet button for fleet_id.
References ClientApp::EmpireID(), ErrorLogger, ObjectMap::get(), GGHumanClientApp::GetApp(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetUniverse(), anonymous_namespace{MapWnd.cpp}::IsMovingOnStarlane(), anonymous_namespace{MapWnd.cpp}::IsOffRoad(), m_fleet_buttons, m_moving_fleet_buttons, m_offroad_fleet_buttons, and Objects().
Referenced by FleetButtonLeftClicked(), FleetButtonRightClicked(), FleetIDsOfFleetButtonsOverlapping(), and SelectFleet().
FleetIDsOfFleetButtonsOverlapping() [2/2]
std::vector< int > MapWnd::FleetIDsOfFleetButtonsOverlapping (const FleetButton & fleet_btn) const private
Return fleets ids of all fleet buttons containing or overlapping fleet_btn.
References ErrorLogger, FleetIDsOfFleetButtonsOverlapping(), and FleetButton::Fleets().
FleetRightClicked()
void MapWnd::FleetRightClicked (int fleet_id) private
References FleetsRightClicked(), and INVALID_OBJECT_ID.
Referenced by CompleteConstruction().
FleetsRightClicked()
void MapWnd::FleetsRightClicked (const std::vector< int > & fleet_ids) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), GGHumanClientApp::GetApp(), m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by FleetButtonRightClicked(), and FleetRightClicked().
ForgetObject()
void MapWnd::ForgetObject (int id)
Forget object with id.
Used for sensor ghosts.
References ALL_EMPIRES, ClientApp::EmpireID(), Ship::FleetID(), Universe::ForgetKnownObject(), ObjectMap::get(), GGHumanClientApp::GetApp(), GetUniverse(), OrderSet::IssueOrder(), Universe::Objects(), Objects(), ClientApp::Orders(), and RemoveFleet().
Referenced by FleetButtonRightClicked().
GetModeratorActionSetting()
ModeratorActionSetting MapWnd::GetModeratorActionSetting () const
returns the currently set moderator action in this MapWnd's ModeratorActionsWnd.
References m_moderator_wnd.
GetSaveGameUIData()
void MapWnd::GetSaveGameUIData (SaveGameUIData & data) const
populates the relevant UI state that should be restored after a save-and-load cycle
References SaveGameUIData::fleets_exploring, m_fleets_exploring, m_zoom_steps_in, SaveGameUIData::map_left, SaveGameUIData::map_top, and SaveGameUIData::map_zoom_steps_in.
Referenced by ClientUI::GetSaveGameUIData().
HideAllPopups()
void MapWnd::HideAllPopups () private
References m_popups.
Referenced by ShowProduction().
HideDesign()
void MapWnd::HideDesign () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_design, m_design_wnd, RemoveFromWndStack(), and RestoreSidePanel().
Referenced by Sanitize(), ShowEmpires(), ShowGovernment(), ShowMessages(), ShowModeratorActions(), ShowObjects(), ShowPedia(), ShowProduction(), ShowResearch(), ShowSitRep(), and ToggleDesign().
HideEmpires()
void MapWnd::HideEmpires () private
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetTexture(), m_btn_empires, and RemoveFromWndStack().
Referenced by CompleteConstruction(), ReturnToMap(), and ToggleEmpires().
HideGovernment()
void MapWnd::HideGovernment () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_government, m_government_wnd, RemoveFromWndStack(), and RestoreSidePanel().
Referenced by CompleteConstruction(), ReturnToMap(), Sanitize(), ShowModeratorActions(), and ToggleGovernment().
HideMessages()
void MapWnd::HideMessages () private
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetTexture(), m_btn_messages, and RemoveFromWndStack().
Referenced by CompleteConstruction(), ReturnToMap(), and ToggleMessages().
HideModeratorActions()
void MapWnd::HideModeratorActions () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_moderator, m_moderator_wnd, and RemoveFromWndStack().
Referenced by CompleteConstruction(), InitTurn(), and ToggleModeratorActions().
HideObjects()
void MapWnd::HideObjects () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_objects, m_object_list_wnd, and RemoveFromWndStack().
Referenced by CompleteConstruction(), and ToggleObjects().
HidePedia()
void MapWnd::HidePedia () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_pedia, m_pedia_panel, and RemoveFromWndStack().
Referenced by CompleteConstruction(), ShowProduction(), and TogglePedia().
HideProduction()
void MapWnd::HideProduction () private
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetTexture(), m_btn_production, m_in_production_view_mode, m_production_wnd, RegisterWindows(), RemoveFromWndStack(), RestoreSidePanel(), and ShowAllPopups().
Referenced by FleetButtonLeftClicked(), Sanitize(), ShowDesign(), ShowEmpires(), ShowGovernment(), ShowMessages(), ShowModeratorActions(), ShowObjects(), ShowPedia(), ShowResearch(), ShowSitRep(), and ToggleProduction().
HideResearch()
void MapWnd::HideResearch () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_research, m_research_wnd, RemoveFromWndStack(), and RestoreSidePanel().
Referenced by Sanitize(), ShowDesign(), ShowEmpires(), ShowGovernment(), ShowMessages(), ShowModeratorActions(), ShowObjects(), ShowPedia(), ShowProduction(), ShowSitRep(), and ToggleResearch().
HideSidePanel()
void MapWnd::HideSidePanel () private
References m_side_panel, and m_sidepanel_open_before_showing_other.
Referenced by ShowDesign(), ShowProduction(), and ShowResearch().
HideSitRep()
void MapWnd::HideSitRep () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_btn_siterep, m_sitrep_panel, and RemoveFromWndStack().
Referenced by CompleteConstruction(), and ToggleSitRep().
HideSystemNames()
void MapWnd::HideSystemNames ()
disables the system name text
References m_system_icons.
Referenced by InitTurn(), MidTurnUpdate(), and SetZoom().
InDesignViewMode()
bool MapWnd::InDesignViewMode () const
returns true if MapWnd is visible and usable behind a design window.
MapWnd interactions are restricted to those appropriate to the design window Currently, there are no interactions with the MapWnd while the design window is visible because although the MapWnd is visible the design window is opaque and on top.
References m_design_wnd.
Referenced by anonymous_namespace{MapWnd.cpp}::NotCoveredMapWndCondition::operator()().
InitFieldRenderingBuffers()
void MapWnd::InitFieldRenderingBuffers () private
References BufferStoreCircleArcVertices(), ClearFieldRenderingBuffers(), CurrentTurn(), DebugLogger, ClientApp::EmpireID(), ObjectMap::get(), GGHumanClientApp::GetApp(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), m_field_icons, m_field_scanline_circles, m_field_texture_coords, m_field_vertices, Objects(), and anonymous_namespace{MapWnd.cpp}::TWO_PI.
Referenced by InitTurnRendering().
InitializeWindows()
void MapWnd::InitializeWindows () private
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), GetOptionsDB(), anonymous_namespace{MapWnd.cpp}::LAYOUT_MARGIN, m_combat_report_wnd, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_scale_line, m_side_panel, m_sitrep_panel, m_toolbar, anonymous_namespace{MapWnd.cpp}::SCALE_LINE_MAX_WIDTH, anonymous_namespace{MapWnd.cpp}::SITREP_PANEL_HEIGHT, and anonymous_namespace{MapWnd.cpp}::SITREP_PANEL_WIDTH.
Referenced by CompleteConstruction().
InitScaleCircleRenderingBuffer()
void MapWnd::InitScaleCircleRenderingBuffer () private
References BufferStoreCircleArcVertices(), ClearScaleCircleRenderingBuffer(), ObjectMap::get(), m_scale_circle_vertices, m_scale_line, Objects(), SidePanel::SystemID(), and anonymous_namespace{MapWnd.cpp}::TWO_PI.
Referenced by RenderScaleCircle(), SelectSystem(), and SetZoom().
InitStarlaneRenderingBuffers()
void MapWnd::InitStarlaneRenderingBuffers () private
initializes or refreshes buffers for rendering of starlanes
References anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), ClearStarlaneRenderingBuffers(), DebugLogger, GGHumanClientApp::GetApp(), m_RC_starlane_colors, m_RC_starlane_vertices, m_starlane_colors, m_starlane_endpoints, m_starlane_vertices, m_system_icons, anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), and anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender().
Referenced by InitTurn(), and InitTurnRendering().
InitSystemRenderingBuffers()
void MapWnd::InitSystemRenderingBuffers () private
initializes or refreshes buffers for rendering of system icons and galaxy gas
References ClearSystemRenderingBuffers(), DebugLogger, ErrorLogger, ObjectMap::get(), anonymous_namespace{MapWnd.cpp}::GetGasTexture(), m_galaxy_gas_quad_vertices, m_galaxy_gas_texture_coords, m_star_core_quad_vertices, m_star_halo_quad_vertices, m_star_texture_coords, m_system_icons, Objects(), and ClientUI::SystemIconSize().
Referenced by InitTurnRendering().
InitTurn()
void MapWnd::InitTurn ()
called at the start of each turn
References ObjectMap::all(), Universe::ApplyAppearanceEffects(), OrderSet::ApplyOrders(), CenterOnMapCoord(), Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, CurrentTurn(), DebugLogger, DispatchFleetsExploring(), Empires(), SectionedScopedTimer::EnterSection(), FlexibleFormat(), OptionsDB::Get(), GGHumanClientApp::GetApp(), ClientApp::GetClientType(), FleetUIManager::GetFleetUIManager(), GetGalaxySetupData(), GetOptionsDB(), Sound::GetSound(), GetSpeciesManager(), GetSupplyManager(), GetUniverse(), HideModeratorActions(), HideSystemNames(), Universe::InitMeterEstimatesAndDiscrepancies(), InitStarlaneRenderingBuffers(), InitTurnRendering(), m_btn_auto_turn, m_btn_moderator, m_btn_turn, m_combat_report_wnd, m_design_wnd, m_fleet_state_change_signals, m_FPS, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_production_wnd, m_ready_turn, m_research_wnd, m_scale_line, m_sitrep_panel, m_system_fleet_insert_remove_signals, m_toolbar, anonymous_namespace{MapWnd.cpp}::MIN_SYSTEM_NAME_SIZE, Universe::Objects(), ClientApp::Orders(), Sound::PlaySound(), ClientUI::Pts(), SidePanel::Refresh(), FleetUIManager::RefreshAll(), RefreshDetectionIndicator(), RefreshFleetButtons(), RefreshFleetResourceIndicator(), RefreshIndustryResourceIndicator(), RefreshInfluenceResourceIndicator(), RefreshPopulationIndicator(), RefreshResearchResourceIndicator(), RefreshSliders(), RefreshTurnButtonTooltip(), SelectSystem(), ShowSitRep(), ShowSystemNames(), to_string(), TraceLogger, Universe::UpdateMeterEstimates(), UserString(), and ZoomFactor().
InitTurnRendering()
void MapWnd::InitTurnRendering () private
sets up rendering of system icons, galaxy gas, starlanes at start of turn
References ObjectMap::all(), anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClearProjectedFleetMovementLines(), DebugLogger, DoFieldIconsLayout(), DoSystemIconsLayout(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), FieldRightClicked(), GGHumanClientApp::GetApp(), GetUniverse(), InitFieldRenderingBuffers(), InitStarlaneRenderingBuffers(), InitSystemRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), m_field_icons, m_fleet_lines, m_starfield_colours, m_starfield_verts, m_system_icons, MouseEnteringSystem(), MouseLeavingSystem(), Objects(), RefreshFleetButtons(), SystemDoubleClicked(), SidePanel::SystemID(), SystemLeftClicked(), SystemRightClicked(), and anonymous_namespace{MapWnd.cpp}::ZOOM_MAX.
Referenced by InitTurn(), and MidTurnUpdate().
InitVisibilityRadiiRenderingBuffers()
void MapWnd::InitVisibilityRadiiRenderingBuffers () private
References AdjustBrightness(), BufferStoreCircleArcVertices(), ClearVisibilityRadiiRenderingBuffers(), Meter::Current(), DebugLogger, Universe::DestroyedObjectIds(), ClientApp::EmpireID(), Universe::EmpireStaleKnowledgeObjectIDs(), ErrorLogger, ObjectMap::get(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), GetUniverse(), INVALID_OBJECT_ID, m_radii_radii_vertices_indices_runs, m_visibility_radii_border_colors, m_visibility_radii_border_vertices, m_visibility_radii_colors, m_visibility_radii_vertices, Objects(), and anonymous_namespace{MapWnd.cpp}::TWO_PI.
Referenced by InitTurnRendering().
InProductionViewMode()
bool MapWnd::InProductionViewMode () const
returns true if MapWnd is visible and usable behind a production window.
MapWnd interactions are restricted to those appropriate to the production window
References m_in_production_view_mode.
InResearchViewMode()
bool MapWnd::InResearchViewMode () const
returns true if MapWnd is visible and usable behind a research window.
MapWnd interactions are restricted to those appropriate to the research window. Currently, there are no interactions with the MapWnd while the research window is visible because although the MapWnd is visible the research window is opaque and on top.
References m_research_wnd.
Referenced by anonymous_namespace{MapWnd.cpp}::NotCoveredMapWndCondition::operator()().
IsFleetExploring()
bool MapWnd::IsFleetExploring (const int fleet_id)
References m_fleets_exploring.
KeyboardZoomIn()
bool MapWnd::KeyboardZoomIn () private
References Zoom().
Referenced by ConnectKeyboardAcceleratorSignals().
KeyboardZoomOut()
bool MapWnd::KeyboardZoomOut () private
References Zoom().
Referenced by ConnectKeyboardAcceleratorSignals().
KeyPress()
void MapWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References ReplotProjectedFleetMovement().
KeyRelease()
void MapWnd::KeyRelease (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References ReplotProjectedFleetMovement().
LButtonDown()
void MapWnd::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References ClientUpperLeft(), and m_drag_offset.
LButtonUp()
void MapWnd::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_drag_offset, and m_dragged.
LClick()
void MapWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References FleetUIManager::ActiveFleetWnd(), FleetUIManager::CloseAll(), OptionsDB::Get(), FleetUIManager::GetFleetUIManager(), GetOptionsDB(), INVALID_OBJECT_ID, m_drag_offset, m_dragged, m_in_production_view_mode, m_side_panel, and SelectSystem().
LDrag()
void MapWnd::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), CorrectMapPosition(), GetOptionsDB(), m_drag_offset, and m_dragged.
MidTurnUpdate()
void MapWnd::MidTurnUpdate ()
called after receiving updated Universe during turn processing, but not when the full turn update is received
References DebugLogger, Empires(), FleetUIManager::GetFleetUIManager(), GetUniverse(), HideSystemNames(), Universe::InitializeSystemGraph(), InitTurnRendering(), anonymous_namespace{MapWnd.cpp}::MIN_SYSTEM_NAME_SIZE, Objects(), ClientUI::Pts(), SidePanel::Refresh(), FleetUIManager::RefreshAll(), ShowSystemNames(), Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap(), and ZoomFactor().
MouseEnteringSystem()
void MapWnd::MouseEnteringSystem (int system_id, GG::Flags< GG::ModKey > mod_keys) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), m_in_production_view_mode, PlotFleetMovement(), and SystemBrowsedSignal.
Referenced by InitTurnRendering(), and MouseLeavingSystem().
MouseLeavingSystem()
void MapWnd::MouseLeavingSystem (int system_id) private
References INVALID_OBJECT_ID, and MouseEnteringSystem().
Referenced by InitTurnRendering().
MouseWheel()
void MapWnd::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
References Zoom().
MovingFleetMapPositionOnLane()
boost::optional< std::pair< double, double > > MapWnd::MovingFleetMapPositionOnLane (std::shared_ptr< const Fleet > fleet) const private
Returns position on map where a moving fleet should be displayed.
This is different from the fleet's actual universe position due to the squishing of fleets moving along a lane into the space between the system circles at the ends of the lane. Return boost::none if the fleet has no valid screen position.
References m_starlane_endpoints, and anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane().
Referenced by DoFleetButtonsLayout().
Pan()
void MapWnd::Pan (const GG::Pt & delta) private
pans map
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClientUpperLeft(), and CorrectMapPosition().
Referenced by PanX(), and PanY().
PanX()
bool MapWnd::PanX (GG::X x = GG::X(50)) private
References Pan().
Referenced by ConnectKeyboardAcceleratorSignals().
PanY()
bool MapWnd::PanY (GG::Y y = GG::Y(50)) private
References Pan().
Referenced by ConnectKeyboardAcceleratorSignals().
PlanetDoubleClicked()
void MapWnd::PlanetDoubleClicked (int planet_id) private
References CenterOnObject(), ObjectMap::get(), INVALID_OBJECT_ID, m_in_production_view_mode, m_production_wnd, Objects(), and ToggleProduction().
Referenced by CompleteConstruction().
PlanetRightClicked()
void MapWnd::PlanetRightClicked (int planet_id) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), GGHumanClientApp::GetApp(), INVALID_OBJECT_ID, m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by CompleteConstruction().
PlotFleetMovement()
void MapWnd::PlotFleetMovement (int system_id, bool execute_move, bool append) private
issues fleet move orders to appropriate fleets in active FleetWnd
References FleetUIManager::ActiveFleetWnd(), DebugLogger, ClientApp::EmpireID(), ObjectMap::find(), ObjectMap::get(), GGHumanClientApp::GetApp(), FleetUIManager::GetFleetUIManager(), Universe::GetPathfinder(), GetUniverse(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), m_projected_fleet_lines, Objects(), ClientApp::Orders(), FleetWnd::SelectedFleetIDs(), SetProjectedFleetMovementLine(), StopFleetExploring(), and TraceLogger.
Referenced by MouseEnteringSystem(), ReplotProjectedFleetMovement(), and SystemRightClicked().
PreRender()
void MapWnd::PreRender () override
References DeferredRefreshFleetButtons(), m_design_wnd, and m_research_wnd.
PushWndStack()
void MapWnd::PushWndStack (std::shared_ptr< GG::Wnd > wnd) private
References m_wnd_stack, and RemoveFromWndStack().
Referenced by CompleteConstruction(), SelectFleet(), SelectSystem(), ShowCombatLog(), ShowDesign(), ShowEmpires(), ShowGovernment(), ShowMessages(), ShowModeratorActions(), ShowObjects(), ShowPedia(), ShowProduction(), ShowResearch(), and ShowSitRep().
RClick()
void MapWnd::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetOptionsDB(), m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), ClientNetworking::SendMessage(), OptionsDB::Set(), UniversePositionFromScreenCoords(), and UserString().
RefreshDetectionIndicator()
void MapWnd::RefreshDetectionIndicator () private
References GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), m_detection, and UserString().
Referenced by InitTurn().
RefreshFleetButtons()
void MapWnd::RefreshFleetButtons (bool recreate = true) private
Mark all fleet buttons for a refresh.
References m_deferred_recreate_fleet_buttons, and m_deferred_refresh_fleet_buttons.
Referenced by InitTurn(), InitTurnRendering(), RemoveFleet(), and SetZoom().
RefreshFleetButtonSelectionIndicators()
void MapWnd::RefreshFleetButtonSelectionIndicators () private
marks (only) selected fleets' buttons as selected
References m_departing_fleet_buttons, m_fleet_buttons, m_moving_fleet_buttons, m_offroad_fleet_buttons, m_selected_fleet_ids, and m_stationary_fleet_buttons.
Referenced by DeferredRefreshFleetButtons(), and SelectedFleetsChanged().
RefreshFleetResourceIndicator()
void MapWnd::RefreshFleetResourceIndicator () private
References ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), FontBasedUpscale(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), GetUniverse(), m_fleet, and Objects().
Referenced by InitTurn().
RefreshIndustryResourceIndicator()
void MapWnd::RefreshIndustryResourceIndicator () private
References ClientUI::ArtDir(), DebugLogger, GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), ClientUI::GetTexture(), m_industry, m_industry_wasted, m_stockpile, and UserString().
Referenced by CompleteConstruction(), and InitTurn().
RefreshInfluenceResourceIndicator()
void MapWnd::RefreshInfluenceResourceIndicator () private
References DebugLogger, GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), m_influence, and UserString().
Referenced by InitTurn().
RefreshPopulationIndicator()
void MapWnd::RefreshPopulationIndicator () private
References ObjectMap::find(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), GetSpecies(), GetSpeciesManager(), m_population, Objects(), parse::species(), and UserString().
Referenced by InitTurn().
RefreshResearchResourceIndicator()
void MapWnd::RefreshResearchResourceIndicator () private
References DebugLogger, GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), m_research, m_research_wasted, and UserString().
Referenced by CompleteConstruction(), and InitTurn().
RefreshSliders()
void MapWnd::RefreshSliders () private
shows or hides sliders on map
References GetOptionsDB(), and m_zoom_slider.
Referenced by CompleteConstruction(), and InitTurn().
RefreshTurnButtonTooltip()
void MapWnd::RefreshTurnButtonTooltip () private
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, GGHumanClientApp::GetApp(), ClientApp::GetClientType(), GetOptionsDB(), m_btn_turn, m_ready_turn, GGHumanClientApp::SinglePlayerGame(), and UserString().
Referenced by CompleteConstruction(), EnableOrderIssuing(), and InitTurn().
RegisterPopup()
void MapWnd::RegisterPopup (std::shared_ptr< MapWndPopup > && popup)
registers a MapWndPopup, which can be cleaned up with a call to DeleteAllPopups()
References m_popups.
RegisterWindows()
void MapWnd::RegisterWindows ()
registers owned wnds with the GUI (also registers message & player list wnds)
References GGHumanClientApp::GetApp(), m_combat_report_wnd, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_side_panel, and m_sitrep_panel.
Referenced by HideProduction().
RemoveFleet()
void MapWnd::RemoveFleet (int fleet_id)
removes specified fleet.
References m_fleet_lines, m_projected_fleet_lines, m_selected_fleet_ids, and RefreshFleetButtons().
Referenced by ForgetObject(), and UniverseObjectDeleted().
RemoveFromWndStack()
void MapWnd::RemoveFromWndStack (std::shared_ptr< GG::Wnd > wnd) private
References m_wnd_stack.
Referenced by HideDesign(), HideEmpires(), HideGovernment(), HideMessages(), HideModeratorActions(), HideObjects(), HidePedia(), HideProduction(), HideResearch(), HideSitRep(), PushWndStack(), and SelectSystem().
RemovePopup()
void MapWnd::RemovePopup (MapWndPopup * popup)
removes a MapWndPopup from the list cleaned up on a call to DeleteAllPopups()
References m_popups.
RemoveWindows()
void MapWnd::RemoveWindows ()
removes owned wnds from the GUI (also removes message & player list wnds)
References GGHumanClientApp::GetApp(), m_combat_report_wnd, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_side_panel, and m_sitrep_panel.
Referenced by Sanitize(), and ShowProduction().
Render()
void MapWnd::Render () override
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), FleetUIManager::CullEmptyWnds(), FleetUIManager::GetFleetUIManager(), m_design_wnd, m_research_wnd, RenderFields(), RenderFleetMovementLines(), RenderGalaxyGas(), RenderStarfields(), RenderStarlanes(), RenderSystemOverlays(), RenderSystems(), RenderVisibilityRadii(), and ZoomFactor().
RenderFields()
void MapWnd::RenderFields () private
renders field objects
References ALL_EMPIRES, ClientApp::EmpireID(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetOptionsDB(), m_field_scanline_circles, m_field_texture_coords, m_field_vertices, m_scanline_shader, ScanlineRenderer::SetColor(), ScanlineRenderer::StartUsing(), and ScanlineRenderer::StopUsing().
Referenced by Render().
RenderFleetMovementLines()
void MapWnd::RenderFleetMovementLines () private
References anonymous_namespace{MapWnd.cpp}::BUFFER_CAPACITY(), anonymous_namespace{MapWnd.cpp}::dot_star_texture_coords, OptionsDB::Get(), GetOptionsDB(), m_fleet_lines, m_projected_fleet_lines, m_selected_fleet_ids, anonymous_namespace{MapWnd.cpp}::MoveLineDotTexture(), RenderMovementLine(), RenderMovementLineETAIndicators(), ClientUI::TinyFleetButtonZoomThreshold(), and ZoomFactor().
Referenced by Render().
RenderGalaxyGas()
void MapWnd::RenderGalaxyGas () private
renders gassy substance to make shape of galaxy
References anonymous_namespace{MapWnd.cpp}::GetGasTexture(), GetOptionsDB(), m_galaxy_gas_quad_vertices, and m_galaxy_gas_texture_coords.
Referenced by Render().
RenderMovementLine()
void MapWnd::RenderMovementLine (const MapWnd::MovementLineData & move_line, float dot_size, float dot_spacing, float dot_shift, GG::Clr clr = GG::CLR_ZERO) private
References anonymous_namespace{MapWnd.cpp}::BUFFER_CAPACITY(), anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, MapWnd::MovementLineData::colour, anonymous_namespace{MapWnd.cpp}::dot_star_texture_coords, anonymous_namespace{MapWnd.cpp}::dot_vertices_buffer, ScreenCoordsFromUniversePosition(), and MapWnd::MovementLineData::vertices.
Referenced by RenderFleetMovementLines().
RenderMovementLineETAIndicators()
void MapWnd::RenderMovementLineETAIndicators (const MapWnd::MovementLineData & move_line, GG::Clr clr = GG::CLR_ZERO) private
References CircleArc(), anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, MapWnd::MovementLineData::colour, ClientUI::GetBoldFont(), ClientUI::Pts(), ScreenCoordsFromUniversePosition(), to_string(), anonymous_namespace{MapWnd.cpp}::TWO_PI, and MapWnd::MovementLineData::vertices.
Referenced by RenderFleetMovementLines().
RenderScaleCircle()
void MapWnd::RenderScaleCircle () private
References GetOptionsDB(), InitScaleCircleRenderingBuffer(), INVALID_OBJECT_ID, m_scale_circle_vertices, and SidePanel::SystemID().
Referenced by RenderSystems().
RenderStarfields()
void MapWnd::RenderStarfields () private
renders the background starfiends
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClearStarfieldRenderingBuffers(), OptionsDB::Get(), GetOptionsDB(), GetUniverse(), m_starfield_colours, m_starfield_verts, RandDouble(), RandGaussian(), RandZeroToOne(), Seed(), Universe::UniverseWidth(), and ZoomFactor().
Referenced by Render().
RenderStarlanes() [1/2]
void MapWnd::RenderStarlanes () private
renders the starlanes between the systems
References OptionsDB::Get(), GetGameRules(), GetOptionsDB(), m_RC_starlane_colors, m_RC_starlane_vertices, m_starlane_colors, m_starlane_vertices, and ZoomFactor().
Referenced by Render().
RenderStarlanes() [2/2]
void MapWnd::RenderStarlanes (GG::GL2DVertexBuffer & vertices, GG::GLRGBAColorBuffer & colours, double thickness, bool coloured, bool do_base_render) private
References OptionsDB::Get(), and GetOptionsDB().
RenderSystemOverlays()
void MapWnd::RenderSystemOverlays () private
renders textures "overlayed" on systems by effects
References m_system_icons, and ZoomFactor().
Referenced by Render().
RenderSystems()
void MapWnd::RenderSystems () private
renders stars and halos
References ALL_EMPIRES, CircleArc(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), SupplyManager::EmpireThatCanSupplyAt(), ErrorLogger, OptionsDB::Get(), GGHumanClientApp::GetApp(), GetEmpire(), Universe::GetObjectVisibilityByEmpire(), GetOptionsDB(), GetSupplyManager(), GetUniverse(), m_scanline_shader, m_star_core_quad_vertices, m_star_halo_quad_vertices, m_star_texture_coords, m_system_icons, Objects(), ScanlineRenderer::RenderCircle(), RenderScaleCircle(), ScanlineRenderer::SetColor(), SystemHaloScaleFactor(), ClientUI::SystemIconSize(), ClientUI::SystemTinyIconSizeThreshold(), ClientUI::TextColor(), anonymous_namespace{MapWnd.cpp}::TWO_PI, and ZoomFactor().
Referenced by Render().
RenderVisibilityRadii()
void MapWnd::RenderVisibilityRadii () private
References GetOptionsDB(), m_radii_radii_vertices_indices_runs, m_visibility_radii_border_colors, m_visibility_radii_border_vertices, m_visibility_radii_colors, and m_visibility_radii_vertices.
Referenced by Render().
ReplotProjectedFleetMovement()
void MapWnd::ReplotProjectedFleetMovement (bool append) private
Find any projected movement plots and replots them with the current append state.
References INVALID_OBJECT_ID, m_projected_fleet_lines, MapWnd::MovementLineData::path, PlotFleetMovement(), and TraceLogger.
Referenced by KeyPress(), and KeyRelease().
ReselectLastFleet()
void MapWnd::ReselectLastFleet ()
re-selects the most recent selected fleet, if a valid one exists
References ObjectMap::find(), GetUniverse(), ObjectMap::insert(), m_selected_fleet_ids, Universe::Objects(), and SelectFleet().
ReselectLastSystem()
void MapWnd::ReselectLastSystem ()
re-selects the most recently selected system, if a valid one exists
References INVALID_OBJECT_ID, SelectSystem(), and SidePanel::SystemID().
Referenced by RestoreSidePanel().
ResetEmpireShown()
void MapWnd::ResetEmpireShown ()
auto-resets the shown empire in any contained Wnds, to the current client's empire (if any)
References GGHumanClientApp::GetApp(), m_production_wnd, and m_research_wnd.
Referenced by Sanitize().
ResetTimeoutClock()
void MapWnd::ResetTimeoutClock (int timeout)
start count down timeout seconds
References m_timeout_clock, m_timeout_time, and TimerFiring().
RestoreFromSaveData()
void MapWnd::RestoreFromSaveData (const SaveGameUIData & data)
restores the UI state that was saved in an earlier call to GetSaveGameUIData().
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClientUpperLeft(), CorrectMapPosition(), SaveGameUIData::fleets_exploring, m_fleets_exploring, m_zoom_steps_in, SaveGameUIData::map_left, SaveGameUIData::map_top, and SaveGameUIData::map_zoom_steps_in.
RestoreSidePanel()
void MapWnd::RestoreSidePanel () private
restores side panel, sends to server changes made in other windows
References GGHumanClientApp::GetApp(), m_sidepanel_open_before_showing_other, ReselectLastSystem(), and ClientApp::SendPartialOrders().
Referenced by HideDesign(), HideGovernment(), HideProduction(), and HideResearch().
ReturnToMap()
bool MapWnd::ReturnToMap () private
References FleetUIManager::CloseAll(), ErrorLogger, ClientUI::GetClientUI(), FleetUIManager::GetFleetUIManager(), HideEmpires(), HideGovernment(), HideMessages(), INVALID_OBJECT_ID, m_combat_report_wnd, m_design_wnd, m_government_wnd, m_moderator_wnd, m_object_list_wnd, m_pedia_panel, m_production_wnd, m_research_wnd, m_side_panel, m_sitrep_panel, m_wnd_stack, SelectSystem(), ToggleDesign(), ToggleModeratorActions(), ToggleObjects(), TogglePedia(), ToggleProduction(), ToggleResearch(), and ToggleSitRep().
Referenced by ConnectKeyboardAcceleratorSignals().
Sanitize()
void MapWnd::Sanitize ()
sanitizes the MapWnd after a game
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClearFieldRenderingBuffers(), ClearScaleCircleRenderingBuffer(), ClearStarfieldRenderingBuffers(), ClearStarlaneRenderingBuffers(), ClearSystemRenderingBuffers(), ClearVisibilityRadiiRenderingBuffers(), CloseAllPopups(), DeleteFleetButtons(), ClientUI::GetClientUI(), HideDesign(), HideGovernment(), HideProduction(), HideResearch(), INVALID_GAME_TURN, INVALID_OBJECT_ID, m_auto_end_turn, m_combat_report_wnd, m_design_wnd, m_fleet_lines, m_fleet_state_change_signals, m_fleets_exploring, m_FPS, m_government_wnd, m_line_between_systems, m_pedia_panel, m_production_wnd, m_projected_fleet_lines, m_research_wnd, m_scale_line, m_selected_fleet_ids, m_selected_ship_ids, m_sitrep_panel, m_starfield_colours, m_starfield_verts, m_starlane_endpoints, m_system_fleet_insert_remove_signals, m_system_icons, m_toolbar, m_zoom_slider, m_zoom_steps_in, RemoveWindows(), ResetEmpireShown(), SelectSystem(), ShowAllPopups(), and ToggleAutoEndTurn().
ScreenCoordsFromUniversePosition()
GG::Pt MapWnd::ScreenCoordsFromUniversePosition (double universe_x, double universe_y) const
returns the position on the screen that corresponds to the specified universe X and Y coordinates.
References ClientUpperLeft(), and ZoomFactor().
Referenced by RenderMovementLine(), and RenderMovementLineETAIndicators().
SelectedFleetsChanged()
void MapWnd::SelectedFleetsChanged () private
References FleetUIManager::GetFleetUIManager(), m_selected_fleet_ids, and RefreshFleetButtonSelectionIndicators().
Referenced by CompleteConstruction().
SelectedPlanetID()
int MapWnd::SelectedPlanetID () const
Returns the id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected.
References m_production_wnd.
SelectedShipsChanged()
void MapWnd::SelectedShipsChanged () private
References FleetUIManager::GetFleetUIManager(), m_selected_ship_ids, and SidePanel::Update().
Referenced by CompleteConstruction().
SelectFleet() [1/2]
void MapWnd::SelectFleet (int fleetID)
programatically selects fleets by ID
References Objects().
Referenced by FleetButtonLeftClicked(), ReselectLastFleet(), ZoomToNextFleet(), ZoomToNextIdleFleet(), ZoomToPrevFleet(), and ZoomToPrevIdleFleet().
SelectFleet() [2/2]
void MapWnd::SelectFleet (std::shared_ptr< Fleet > fleet)
Programatically selects fleets.
References FleetUIManager::ActiveFleetWnd(), FleetWnd::DeselectAllFleets(), FleetIDsOfFleetButtonsOverlapping(), FleetUIManager::GetFleetUIManager(), m_fleet_buttons, m_selected_fleet_ids, FleetUIManager::NewFleetWnd(), FleetButton::PlayFleetButtonOpenSound(), PushWndStack(), FleetUIManager::SetActiveFleetWnd(), FleetUIManager::WndForFleetID(), and ZoomFactor().
SelectPlanet()
void MapWnd::SelectPlanet (int planetID)
programatically selects planets on sidepanels. catches signals from production wnd or sidepanel for when the user changes the selected planet
References m_production_wnd.
Referenced by CompleteConstruction().
SelectSystem()
void MapWnd::SelectSystem (int systemID)
programatically selects systems on map, sidepanel, and production screen. catches signals from these when the user changes the selected system
References Empires(), ErrorLogger, ObjectMap::get(), GetGalaxySetupData(), GetOptionsDB(), GetSpeciesManager(), GetSupplyManager(), GetUniverse(), InitScaleCircleRenderingBuffer(), INVALID_OBJECT_ID, m_in_production_view_mode, m_production_wnd, m_side_panel, m_system_icons, Objects(), PushWndStack(), RemoveFromWndStack(), SidePanel::SetSystem(), SidePanel::SystemID(), and Universe::UpdateMeterEstimates().
Referenced by CloseSystemView(), CompleteConstruction(), InitTurn(), LClick(), ReselectLastSystem(), ReturnToMap(), Sanitize(), ShowProduction(), SystemLeftClicked(), ZoomToHomeSystem(), ZoomToNextOwnedSystem(), ZoomToNextSystem(), ZoomToPrevOwnedSystem(), ZoomToPrevSystem(), and ZoomToSystemWithWastedPP().
SetFleetExploring()
void MapWnd::SetFleetExploring (const int fleet_id)
References DispatchFleetsExploring(), and m_fleets_exploring.
SetFleetMovementLine()
void MapWnd::SetFleetMovementLine (int fleet_id)
creates fleet movement line for a single fleet. Move lines originate from the fleet's button location.
References ErrorLogger, ObjectMap::get(), GetEmpire(), INVALID_OBJECT_ID, m_fleet_lines, m_starlane_endpoints, and Objects().
Referenced by DeferredRefreshFleetButtons().
SetProjectedFleetMovementLine()
void MapWnd::SetProjectedFleetMovementLine (int fleet_id, const std::list< int > & travel_route)
References ScriptingContext::ContextObjects(), ErrorLogger, ObjectMap::get(), ScriptingContext::GetEmpire(), INVALID_OBJECT_ID, m_projected_fleet_lines, and m_starlane_endpoints.
Referenced by PlotFleetMovement(), and SetProjectedFleetMovementLines().
SetProjectedFleetMovementLines()
void MapWnd::SetProjectedFleetMovementLines (const std::vector< int > & fleet_ids, const std::list< int > & travel_route)
References SetProjectedFleetMovementLine().
SetZoom() [1/2]
void MapWnd::SetZoom (double steps_in, bool update_slide) private
sets zoom level of the main map to zoom step size to the power of steps_in and updates zoom slider position if update_slide is true
References anonymous_namespace{MapWnd.cpp}::AppHeight(), and anonymous_namespace{MapWnd.cpp}::AppWidth().
Referenced by CompleteConstruction(), and Zoom().
SetZoom() [2/2]
void MapWnd::SetZoom (double steps_in, bool update_slide, const GG::Pt & position) private
sets zoom level of the main map to zoom step size to the power of steps_in and updates zoom slider position if update_slide is true. Keeps the screen position position in the same place after zooming
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), ClientUpperLeft(), CorrectMapPosition(), DoFieldIconsLayout(), DoFleetButtonsLayout(), DoSystemIconsLayout(), FleetButtonSizeType(), GetOptionsDB(), HideSystemNames(), InitScaleCircleRenderingBuffer(), m_field_icons, m_scale_line, m_selected_fleet_ids, m_zoom_slider, m_zoom_steps_in, anonymous_namespace{MapWnd.cpp}::MIN_SYSTEM_NAME_SIZE, ClientUI::Pts(), RefreshFleetButtons(), ShowSystemNames(), SidePanel::SystemID(), to_string(), anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MAX_STEPS, anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MIN_STEPS, ZoomedSignal, and ZoomFactor().
ShipRightClicked()
void MapWnd::ShipRightClicked (int fleet_id) private
References INVALID_OBJECT_ID, and ShipsRightClicked().
Referenced by CompleteConstruction().
ShipsRightClicked()
void MapWnd::ShipsRightClicked (const std::vector< int > & fleet_ids) private
References anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), GGHumanClientApp::GetApp(), m_moderator_wnd, ModeratorActionMessage(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by ShipRightClicked().
ShowAllPopups()
void MapWnd::ShowAllPopups () private
References m_popups.
Referenced by HideProduction(), and Sanitize().
ShowBuildingType()
void MapWnd::ShowBuildingType (const std::string & building_type_name)
brings up the production screen and displays info about the buildtype type_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowCombatLog()
void MapWnd::ShowCombatLog (int log_id)
brings up encyclopedia panel and displays info about the combat
References m_combat_report_wnd, and PushWndStack().
ShowDesign()
void MapWnd::ShowDesign () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), HideProduction(), HideResearch(), HideSidePanel(), m_btn_design, m_design_wnd, and PushWndStack().
Referenced by ToggleDesign().
ShowEmpire()
void MapWnd::ShowEmpire (int empire_id)
brings up encyclopedia panel and displays info about the empire with id empire_id
References m_in_production_view_mode, m_pedia_panel, m_production_wnd, and TogglePedia().
ShowEmpires()
void MapWnd::ShowEmpires () private
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetPlayerListWnd(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_empires, and PushWndStack().
Referenced by ToggleEmpires().
ShowEncyclopediaEntry()
void MapWnd::ShowEncyclopediaEntry (const std::string & str)
brings up encyclopedia panel and displays info about the specified string str
References m_pedia_panel, and TogglePedia().
ShowFieldType()
void MapWnd::ShowFieldType (const std::string & field_type_name)
brings up encyclopedia panel and displays info about the field type with name field_type_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowGovernment()
void MapWnd::ShowGovernment () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_government, m_government_wnd, and PushWndStack().
Referenced by ToggleGovernment().
ShowGraphs()
bool MapWnd::ShowGraphs () private
References TextLinker::ENCYCLOPEDIA_TAG, m_pedia_panel, and ShowPedia().
Referenced by CompleteConstruction(), and ConnectKeyboardAcceleratorSignals().
ShowMenu()
bool MapWnd::ShowMenu () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), m_btn_menu, and m_menu_showing.
Referenced by CompleteConstruction(), and ConnectKeyboardAcceleratorSignals().
ShowMessages()
void MapWnd::ShowMessages () private
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetMessageWnd(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_messages, and PushWndStack().
Referenced by ToggleMessages().
ShowMeterTypeArticle()
void MapWnd::ShowMeterTypeArticle (const std::string & meter_string)
brings up encyclopedia panel and displays info about the MeterType meter_type
References m_pedia_panel, and ShowPedia().
ShowModeratorActions()
void MapWnd::ShowModeratorActions () private
References ClientUI::ArtDir(), ClientUI::GetTexture(), HideDesign(), HideGovernment(), HideProduction(), HideResearch(), m_btn_moderator, m_moderator_wnd, and PushWndStack().
Referenced by ToggleModeratorActions().
ShowObjects()
void MapWnd::ShowObjects () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_objects, m_object_list_wnd, and PushWndStack().
Referenced by ToggleObjects().
ShowPedia()
void MapWnd::ShowPedia () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_pedia, m_in_production_view_mode, m_pedia_panel, m_production_wnd, m_research_wnd, and PushWndStack().
Referenced by ShowGraphs(), ShowMeterTypeArticle(), ShowPlanet(), and TogglePedia().
ShowPlanet()
void MapWnd::ShowPlanet (int planet_id)
brings up encyclopedia panel and displays info about the planet
References m_in_production_view_mode, m_pedia_panel, m_production_wnd, and ShowPedia().
ShowPolicy()
void MapWnd::ShowPolicy (const std::string & policy_name)
brings up ??? and displays info about the policy with name policy_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowProduction()
void MapWnd::ShowProduction () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), GetEmpire(), GetOptionsDB(), ClientUI::GetTexture(), HideAllPopups(), HideDesign(), HidePedia(), HideResearch(), HideSidePanel(), INVALID_OBJECT_ID, m_btn_production, m_in_production_view_mode, m_production_wnd, Objects(), PushWndStack(), RemoveWindows(), SelectSystem(), and SidePanel::SystemID().
Referenced by ToggleProduction(), and ZoomToSystemWithWastedPP().
ShowResearch()
void MapWnd::ShowResearch () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), GetOptionsDB(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideSidePanel(), m_btn_research, m_research_wnd, and PushWndStack().
Referenced by ToggleResearch().
ShowShipDesign()
void MapWnd::ShowShipDesign (int design_id)
brings up the production screen and displays info about the buildtype type_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowShipHull()
void MapWnd::ShowShipHull (const std::string & ship_hull_name)
Brings up the production screen and displays info about the ShipHull ship_hull_name.
References m_design_wnd, m_pedia_panel, and TogglePedia().
ShowShipPart()
void MapWnd::ShowShipPart (const std::string & ship_part_name)
Brings up the production screen and displays info about the ShipPart ship_part_name.
References m_design_wnd, m_in_production_view_mode, m_pedia_panel, m_production_wnd, and TogglePedia().
ShowSitRep()
void MapWnd::ShowSitRep () private
References ClientUI::ArtDir(), ClearProjectedFleetMovementLines(), ClientUI::GetTexture(), HideDesign(), HideProduction(), HideResearch(), m_btn_siterep, m_sitrep_panel, and PushWndStack().
Referenced by InitTurn(), and ToggleSitRep().
ShowSpecial()
void MapWnd::ShowSpecial (const std::string & special_name)
brings up encyclopedia panel and displays info about the special with name special_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowSpecies()
void MapWnd::ShowSpecies (const std::string & species_name)
brings up encyclopedia panel and displays info about the species with name species_name
References m_pedia_panel, m_production_wnd, and TogglePedia().
ShowSystemNames()
void MapWnd::ShowSystemNames ()
enables the system name text
References m_system_icons.
Referenced by InitTurn(), MidTurnUpdate(), and SetZoom().
ShowTech()
void MapWnd::ShowTech (const std::string & tech_name)
brings up the research screen and centers the tech tree on tech_name
References m_in_production_view_mode, m_pedia_panel, m_production_wnd, m_research_wnd, and TogglePedia().
StopFleetExploring()
void MapWnd::StopFleetExploring (const int fleet_id)
References DispatchFleetsExploring(), m_fleets_exploring, and Objects().
Referenced by PlotFleetMovement().
SystemDoubleClicked()
void MapWnd::SystemDoubleClicked (int system_id) private
References CenterOnObject(), m_in_production_view_mode, m_production_wnd, and ToggleProduction().
Referenced by InitTurnRendering().
SystemHaloScaleFactor()
double MapWnd::SystemHaloScaleFactor () const
References ZoomFactor().
Referenced by RenderSystems().
SystemIconSize()
int MapWnd::SystemIconSize () const
References ClientUI::SystemIconSize(), and ZoomFactor().
Referenced by DoFleetButtonsLayout(), and DoSystemIconsLayout().
SystemLeftClicked()
void MapWnd::SystemLeftClicked (int system_id) private
References SelectSystem(), and SystemLeftClickedSignal.
Referenced by InitTurnRendering().
SystemNamePts()
int MapWnd::SystemNamePts () const
References ClientUI::Pts(), and ZoomFactor().
SystemRightClicked()
void MapWnd::SystemRightClicked (int system_id, GG::Flags< GG::ModKey > mod_keys) private
References FleetUIManager::ActiveFleetWnd(), ClearProjectedFleetMovementLines(), anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), ObjectMap::find(), ObjectMap::get(), GGHumanClientApp::GetApp(), FleetUIManager::GetFleetUIManager(), INVALID_OBJECT_ID, m_in_production_view_mode, m_moderator_wnd, m_ready_turn, ModeratorActionMessage(), ClientApp::Networking(), Objects(), PlotFleetMovement(), ClientNetworking::SendMessage(), SidePanel::SystemID(), and SystemRightClickedSignal.
Referenced by InitTurnRendering().
TimerFiring()
void MapWnd::TimerFiring (unsigned int ticks, GG::Timer * timer) override
References FlexibleFormat(), m_timeout_clock, m_timeout_remain, m_timeout_time, and UserString().
Referenced by ResetTimeoutClock().
ToggleAutoEndTurn()
void MapWnd::ToggleAutoEndTurn () private
References ClientUI::ArtDir(), GetOptionsDB(), ClientUI::GetTexture(), m_auto_end_turn, m_btn_auto_turn, and UserString().
Referenced by CompleteConstruction(), and Sanitize().
ToggleDesign()
bool MapWnd::ToggleDesign () private
References HideDesign(), m_design_wnd, and ShowDesign().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), and ReturnToMap().
ToggleEmpires()
bool MapWnd::ToggleEmpires () private
References ClientUI::GetClientUI(), ClientUI::GetPlayerListWnd(), HideEmpires(), m_design_wnd, m_production_wnd, m_research_wnd, and ShowEmpires().
Referenced by CompleteConstruction(), and ConnectKeyboardAcceleratorSignals().
ToggleGovernment()
bool MapWnd::ToggleGovernment () private
References HideGovernment(), m_design_wnd, m_government_wnd, m_production_wnd, m_research_wnd, and ShowGovernment().
Referenced by CompleteConstruction().
ToggleMessages()
bool MapWnd::ToggleMessages () private
References ClientUI::GetClientUI(), ClientUI::GetMessageWnd(), HideMessages(), m_design_wnd, m_production_wnd, m_research_wnd, and ShowMessages().
Referenced by CompleteConstruction(), and ConnectKeyboardAcceleratorSignals().
ToggleModeratorActions()
bool MapWnd::ToggleModeratorActions () private
References HideModeratorActions(), m_design_wnd, m_moderator_wnd, m_production_wnd, m_research_wnd, and ShowModeratorActions().
Referenced by CompleteConstruction(), and ReturnToMap().
ToggleObjects()
bool MapWnd::ToggleObjects () private
References HideObjects(), m_design_wnd, m_object_list_wnd, m_production_wnd, m_research_wnd, and ShowObjects().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), and ReturnToMap().
TogglePedia()
bool MapWnd::TogglePedia () private
References HidePedia(), m_design_wnd, m_pedia_panel, m_production_wnd, m_research_wnd, and ShowPedia().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), ReturnToMap(), ShowBuildingType(), ShowEmpire(), ShowEncyclopediaEntry(), ShowFieldType(), ShowPolicy(), ShowShipDesign(), ShowShipHull(), ShowShipPart(), ShowSpecial(), ShowSpecies(), and ShowTech().
ToggleProduction()
bool MapWnd::ToggleProduction () private
References HideProduction(), m_in_production_view_mode, m_side_panel, and ShowProduction().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), PlanetDoubleClicked(), ReturnToMap(), and SystemDoubleClicked().
ToggleResearch()
bool MapWnd::ToggleResearch () private
References HideResearch(), m_research_wnd, and ShowResearch().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), and ReturnToMap().
ToggleSitRep()
bool MapWnd::ToggleSitRep () private
References HideSitRep(), m_design_wnd, m_production_wnd, m_research_wnd, m_sitrep_panel, and ShowSitRep().
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), and ReturnToMap().
UniverseObjectDeleted()
void MapWnd::UniverseObjectDeleted (std::shared_ptr< const UniverseObject > obj) private
References DebugLogger, and RemoveFleet().
Referenced by CompleteConstruction().
UniversePositionFromScreenCoords()
std::pair< double, double > MapWnd::UniversePositionFromScreenCoords (GG::Pt screen_coords) const
returns the universe position (X and Y in pair) that corresponds to the specified screen coordinates.
References ClientUpperLeft(), and ZoomFactor().
Referenced by RClick().
UpdateEmpireResourcePools()
void MapWnd::UpdateEmpireResourcePools () private
recalculates production and predicted changes of player's empire's resource and population pools
References Empires(), GGHumanClientApp::GetApp(), EmpireManager::GetEmpire(), and SidePanel::Update().
Referenced by CompleteConstruction().
Zoom() [1/2]
void MapWnd::Zoom (int delta) private
changes the zoom level of the main map by zoom step size to the power of delta (adds delta to the current zoom exponent)
References anonymous_namespace{MapWnd.cpp}::AppHeight(), and anonymous_namespace{MapWnd.cpp}::AppWidth().
Referenced by KeyboardZoomIn(), KeyboardZoomOut(), and MouseWheel().
Zoom() [2/2]
void MapWnd::Zoom (int delta, const GG::Pt & position) private
changes the zoom level of the main map by zoom step size to the power of delta (adds delta to the current zoom exponent) Keeps the screen position position in the same place after zooming
References m_zoom_steps_in, and SetZoom().
ZoomFactor()
double MapWnd::ZoomFactor () const
References m_zoom_steps_in, and anonymous_namespace{MapWnd.cpp}::ZoomScaleFactor().
Referenced by CenterOnMapCoord(), CompleteConstruction(), CorrectMapPosition(), DoFieldIconsLayout(), DoFleetButtonsLayout(), DoSystemIconsLayout(), FleetButtonSizeType(), InitTurn(), MidTurnUpdate(), Render(), RenderFleetMovementLines(), RenderStarfields(), RenderStarlanes(), RenderSystemOverlays(), RenderSystems(), ScreenCoordsFromUniversePosition(), SelectFleet(), SetZoom(), SystemHaloScaleFactor(), SystemIconSize(), SystemNamePts(), and UniversePositionFromScreenCoords().
ZoomToHomeSystem()
bool MapWnd::ZoomToHomeSystem () private
References CenterOnObject(), ObjectMap::get(), GGHumanClientApp::GetApp(), GetEmpire(), INVALID_OBJECT_ID, Objects(), and SelectSystem().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToNextFleet()
bool MapWnd::ZoomToNextFleet () private
References CenterOnObject(), Universe::DestroyedObjectIds(), ObjectMap::findIDs(), GGHumanClientApp::GetApp(), GetUniverse(), INVALID_OBJECT_ID, m_current_fleet_id, Universe::Objects(), and SelectFleet().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToNextIdleFleet()
bool MapWnd::ZoomToNextIdleFleet () private
References CenterOnObject(), Universe::DestroyedObjectIds(), ObjectMap::findIDs(), GGHumanClientApp::GetApp(), GetUniverse(), INVALID_OBJECT_ID, m_current_fleet_id, Universe::Objects(), and SelectFleet().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToNextOwnedSystem()
bool MapWnd::ZoomToNextOwnedSystem () private
References CenterOnObject(), ObjectMap::get(), GGHumanClientApp::GetApp(), anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs(), Objects(), SelectSystem(), and SidePanel::SystemID().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToNextSystem()
bool MapWnd::ZoomToNextSystem () private
References CenterOnObject(), ObjectMap::get(), anonymous_namespace{MapWnd.cpp}::GetSystemNamesIDs(), Objects(), SelectSystem(), and SidePanel::SystemID().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToPrevFleet()
bool MapWnd::ZoomToPrevFleet () private
References CenterOnObject(), Universe::DestroyedObjectIds(), ObjectMap::findIDs(), GGHumanClientApp::GetApp(), GetUniverse(), INVALID_OBJECT_ID, m_current_fleet_id, Universe::Objects(), and SelectFleet().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToPrevIdleFleet()
bool MapWnd::ZoomToPrevIdleFleet () private
References CenterOnObject(), Universe::DestroyedObjectIds(), ObjectMap::findIDs(), GGHumanClientApp::GetApp(), GetUniverse(), INVALID_OBJECT_ID, m_current_fleet_id, Universe::Objects(), and SelectFleet().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToPrevOwnedSystem()
bool MapWnd::ZoomToPrevOwnedSystem () private
References CenterOnObject(), ObjectMap::get(), GGHumanClientApp::GetApp(), anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs(), Objects(), SelectSystem(), and SidePanel::SystemID().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToPrevSystem()
bool MapWnd::ZoomToPrevSystem () private
References CenterOnObject(), ObjectMap::get(), anonymous_namespace{MapWnd.cpp}::GetSystemNamesIDs(), Objects(), SelectSystem(), and SidePanel::SystemID().
Referenced by ConnectKeyboardAcceleratorSignals().
ZoomToSystemWithWastedPP()
bool MapWnd::ZoomToSystemWithWastedPP () private
References CenterOnObject(), ClientApp::EmpireID(), ObjectMap::find(), GGHumanClientApp::GetApp(), GetEmpire(), INVALID_OBJECT_ID, Objects(), SelectSystem(), and ShowProduction().
Referenced by CompleteConstruction().
Friends And Related Function Documentation
IntroMenu
friend struct IntroMenu friend
PlayingGame
friend struct PlayingGame friend
PlayingTurn
friend struct PlayingTurn friend
WaitingForGameStart
friend struct WaitingForGameStart friend
Member Data Documentation
m_auto_end_turn
bool MapWnd::m_auto_end_turn = false private
should turns be ended automatically by this client?
Referenced by AutoEndTurnEnabled(), Sanitize(), and ToggleAutoEndTurn().
m_btn_auto_turn
std::shared_ptr<GG::Button> MapWnd::m_btn_auto_turn private
button that toggles whether to automatically end turns;
Referenced by CompleteConstruction(), InitTurn(), and ToggleAutoEndTurn().
m_btn_design
std::shared_ptr<GG::Button> MapWnd::m_btn_design private
Referenced by CompleteConstruction(), HideDesign(), and ShowDesign().
m_btn_empires
std::shared_ptr<GG::Button> MapWnd::m_btn_empires private
Referenced by CompleteConstruction(), HideEmpires(), and ShowEmpires().
m_btn_government
std::shared_ptr<GG::Button> MapWnd::m_btn_government private
Referenced by CompleteConstruction(), HideGovernment(), and ShowGovernment().
m_btn_graphs
std::shared_ptr<GG::Button> MapWnd::m_btn_graphs private
Referenced by CompleteConstruction().
m_btn_menu
std::shared_ptr<GG::Button> MapWnd::m_btn_menu private
Referenced by CompleteConstruction(), and ShowMenu().
m_btn_messages
std::shared_ptr<GG::Button> MapWnd::m_btn_messages private
Referenced by CompleteConstruction(), HideMessages(), and ShowMessages().
m_btn_moderator
std::shared_ptr<GG::Button> MapWnd::m_btn_moderator private
Referenced by CompleteConstruction(), HideModeratorActions(), InitTurn(), and ShowModeratorActions().
m_btn_objects
std::shared_ptr<GG::Button> MapWnd::m_btn_objects private
Referenced by CompleteConstruction(), HideObjects(), and ShowObjects().
m_btn_pedia
std::shared_ptr<GG::Button> MapWnd::m_btn_pedia private
Referenced by CompleteConstruction(), HidePedia(), and ShowPedia().
m_btn_production
std::shared_ptr<GG::Button> MapWnd::m_btn_production private
Referenced by CompleteConstruction(), HideProduction(), and ShowProduction().
m_btn_research
std::shared_ptr<GG::Button> MapWnd::m_btn_research private
Referenced by CompleteConstruction(), HideResearch(), and ShowResearch().
m_btn_siterep
std::shared_ptr<GG::Button> MapWnd::m_btn_siterep private
Referenced by CompleteConstruction(), HideSitRep(), and ShowSitRep().
m_btn_turn
std::shared_ptr<GG::Button> MapWnd::m_btn_turn private
button that updates player's turn;
Referenced by CompleteConstruction(), EnableOrderIssuing(), InitTurn(), and RefreshTurnButtonTooltip().
m_combat_report_wnd
std::shared_ptr<CombatReportWnd> MapWnd::m_combat_report_wnd private
shows graphical reports of combats
Referenced by CompleteConstruction(), DoLayout(), InitializeWindows(), InitTurn(), RegisterWindows(), RemoveWindows(), ReturnToMap(), Sanitize(), and ShowCombatLog().
m_current_fleet_id
int MapWnd::m_current_fleet_id = INVALID_OBJECT_ID private
Referenced by ZoomToNextFleet(), ZoomToNextIdleFleet(), ZoomToPrevFleet(), and ZoomToPrevIdleFleet().
m_current_owned_system
int MapWnd::m_current_owned_system = INVALID_OBJECT_ID private
m_deferred_recreate_fleet_buttons
bool MapWnd::m_deferred_recreate_fleet_buttons = false private
indicates that refresh fleet button work should be done before rendering.
Referenced by DeferredRefreshFleetButtons(), and RefreshFleetButtons().
m_deferred_refresh_fleet_buttons
bool MapWnd::m_deferred_refresh_fleet_buttons = false private
Referenced by DeferredRefreshFleetButtons(), and RefreshFleetButtons().
m_departing_fleet_buttons
std::unordered_map<int, std::unordered_set<std::shared_ptr<FleetButton> > > MapWnd::m_departing_fleet_buttons private
Icons representing fleets at a system that are departing, indexed by system.
Referenced by DeferredRefreshFleetButtons(), DeleteFleetButtons(), DoFleetButtonsLayout(), and RefreshFleetButtonSelectionIndicators().
m_design_wnd
std::shared_ptr<DesignWnd> MapWnd::m_design_wnd private
design screen
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), DoLayout(), EnableOrderIssuing(), HideDesign(), InDesignViewMode(), InitTurn(), PreRender(), Render(), ReturnToMap(), Sanitize(), ShowDesign(), ShowShipHull(), ShowShipPart(), ToggleDesign(), ToggleEmpires(), ToggleGovernment(), ToggleMessages(), ToggleModeratorActions(), ToggleObjects(), TogglePedia(), and ToggleSitRep().
m_detection
std::shared_ptr<StatisticIcon> MapWnd::m_detection private
Referenced by CompleteConstruction(), and RefreshDetectionIndicator().
m_drag_offset
GG::Pt MapWnd::m_drag_offset = {-GG::X1, -GG::Y1} private
distance the cursor is from the upper-left corner of the window during a drag ((-1, -1) if no drag is occurring)
Referenced by LButtonDown(), LButtonUp(), LClick(), and LDrag().
m_dragged
bool MapWnd::m_dragged = false private
tracks whether or not a drag occurs during a left button down sequence of events
Referenced by LButtonUp(), LClick(), and LDrag().
m_field_icons
std::map<int, std::shared_ptr<FieldIcon> > MapWnd::m_field_icons private
field icons in the main map, indexed by field id
Referenced by DoFieldIconsLayout(), InitFieldRenderingBuffers(), InitTurnRendering(), and SetZoom().
m_field_scanline_circles
GG::GL2DVertexBuffer MapWnd::m_field_scanline_circles private
Referenced by ClearFieldRenderingBuffers(), InitFieldRenderingBuffers(), and RenderFields().
m_field_texture_coords
GG::GLTexCoordBuffer MapWnd::m_field_texture_coords private
Referenced by ClearFieldRenderingBuffers(), InitFieldRenderingBuffers(), and RenderFields().
m_field_vertices
std::map<std::shared_ptr<GG::Texture>, std::pair<GG::GL2DVertexBuffer, GG::GL2DVertexBuffer> > MapWnd::m_field_vertices private
First buffer is visible fields, second buffer is not visible (scanlined) fields for each texture.
Referenced by ClearFieldRenderingBuffers(), InitFieldRenderingBuffers(), and RenderFields().
m_fleet
std::shared_ptr<StatisticIcon> MapWnd::m_fleet private
Referenced by CompleteConstruction(), and RefreshFleetResourceIndicator().
m_fleet_buttons
std::unordered_map<int, std::shared_ptr<FleetButton> > MapWnd::m_fleet_buttons private
fleet icons, index by fleet
Referenced by CreateFleetButtonsOfType(), DeferredRefreshFleetButtons(), DeleteFleetButtons(), FleetIDsOfFleetButtonsOverlapping(), RefreshFleetButtonSelectionIndicators(), and SelectFleet().
m_fleet_lines
std::map<int, MovementLineData> MapWnd::m_fleet_lines private
lines used for moving fleets in the main map
Referenced by InitTurnRendering(), RemoveFleet(), RenderFleetMovementLines(), Sanitize(), and SetFleetMovementLine().
m_fleet_state_change_signals
std::unordered_map<int, boost::signals2::connection> MapWnd::m_fleet_state_change_signals private
Referenced by InitTurn(), and Sanitize().
m_fleets_exploring
std::set<int> MapWnd::m_fleets_exploring private
Referenced by DispatchFleetsExploring(), GetSaveGameUIData(), IsFleetExploring(), RestoreFromSaveData(), Sanitize(), SetFleetExploring(), and StopFleetExploring().
m_FPS
std::shared_ptr<GG::Label> MapWnd::m_FPS private
Referenced by CompleteConstruction(), InitTurn(), and Sanitize().
m_galaxy_gas_quad_vertices
GG::GL2DVertexBuffer MapWnd::m_galaxy_gas_quad_vertices private
Referenced by ClearSystemRenderingBuffers(), InitSystemRenderingBuffers(), and RenderGalaxyGas().
m_galaxy_gas_texture_coords
GG::GLTexCoordBuffer MapWnd::m_galaxy_gas_texture_coords private
Referenced by ClearSystemRenderingBuffers(), InitSystemRenderingBuffers(), and RenderGalaxyGas().
m_government_wnd
std::shared_ptr<GovernmentWnd> MapWnd::m_government_wnd private
government screen
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), HideGovernment(), InitializeWindows(), InitTurn(), RegisterWindows(), RemoveWindows(), ReturnToMap(), Sanitize(), ShowGovernment(), and ToggleGovernment().
m_in_production_view_mode
bool MapWnd::m_in_production_view_mode = false private
Referenced by FleetButtonLeftClicked(), HideProduction(), InProductionViewMode(), LClick(), MouseEnteringSystem(), PlanetDoubleClicked(), SelectSystem(), ShowEmpire(), ShowPedia(), ShowPlanet(), ShowProduction(), ShowShipPart(), ShowTech(), SystemDoubleClicked(), SystemRightClicked(), and ToggleProduction().
m_industry
std::shared_ptr<StatisticIcon> MapWnd::m_industry private
Referenced by CompleteConstruction(), and RefreshIndustryResourceIndicator().
m_industry_wasted
std::shared_ptr<GG::Button> MapWnd::m_industry_wasted private
Referenced by CompleteConstruction(), and RefreshIndustryResourceIndicator().
m_influence
std::shared_ptr<StatisticIcon> MapWnd::m_influence private
Referenced by CompleteConstruction(), and RefreshInfluenceResourceIndicator().
m_line_between_systems
std::pair<int, int> MapWnd::m_line_between_systems = {INVALID_OBJECT_ID, INVALID_OBJECT_ID} private
set when map should render line connecting 2 systems
Referenced by Sanitize().
m_menu_showing
bool MapWnd::m_menu_showing = false private
set during ShowMenu() to prevent reentrency
Referenced by ShowMenu().
m_moderator_wnd
std::shared_ptr<ModeratorActionsWnd> MapWnd::m_moderator_wnd private
buttons to select moderator actions
Referenced by BuildingRightClicked(), CompleteConstruction(), DoLayout(), EnableOrderIssuing(), FieldRightClicked(), FleetsRightClicked(), GetModeratorActionSetting(), HideModeratorActions(), InitializeWindows(), InitTurn(), PlanetRightClicked(), RClick(), RegisterWindows(), RemoveWindows(), ReturnToMap(), ShipsRightClicked(), ShowModeratorActions(), SystemRightClicked(), and ToggleModeratorActions().
m_moving_fleet_buttons
std::unordered_map<std::pair<int, int>, std::unordered_set<std::shared_ptr<FleetButton> >, boost::hash<std::pair<int, int> > > MapWnd::m_moving_fleet_buttons private
Icons representing fleets moving on a starlane, keyed by starlane end system ids.
Referenced by DeferredRefreshFleetButtons(), DeleteFleetButtons(), DoFleetButtonsLayout(), FleetIDsOfFleetButtonsOverlapping(), and RefreshFleetButtonSelectionIndicators().
m_moving_fleets
std::unordered_map<std::pair<int, int>, std::vector<int>, boost::hash<std::pair<int, int> > > MapWnd::m_moving_fleets private
Sets of fleet ids of fleets moving on a starlane, keyed by starlane end system ids.
Referenced by DeferredRefreshFleetButtons().
m_object_list_wnd
std::shared_ptr<ObjectListWnd> MapWnd::m_object_list_wnd private
filterable list of objects in universe
Referenced by CompleteConstruction(), DoLayout(), HideObjects(), InitializeWindows(), InitTurn(), RegisterWindows(), RemoveWindows(), ReturnToMap(), ShowObjects(), and ToggleObjects().
m_offroad_fleet_buttons
std::unordered_map<std::pair<double, double>, std::unordered_set<std::shared_ptr<FleetButton> >, boost::hash<std::pair<double, double> > > MapWnd::m_offroad_fleet_buttons private
Icons representing fleets moving and not on a starlane, indexed by (x,y) location.
Referenced by DeferredRefreshFleetButtons(), DeleteFleetButtons(), DoFleetButtonsLayout(), FleetIDsOfFleetButtonsOverlapping(), and RefreshFleetButtonSelectionIndicators().
m_pedia_panel
std::shared_ptr<EncyclopediaDetailPanel> MapWnd::m_pedia_panel private
encyclpedia panel
Referenced by CompleteConstruction(), DoLayout(), HidePedia(), InitializeWindows(), InitTurn(), RegisterWindows(), RemoveWindows(), ReturnToMap(), Sanitize(), ShowBuildingType(), ShowEmpire(), ShowEncyclopediaEntry(), ShowFieldType(), ShowGraphs(), ShowMeterTypeArticle(), ShowPedia(), ShowPlanet(), ShowPolicy(), ShowShipDesign(), ShowShipHull(), ShowShipPart(), ShowSpecial(), ShowSpecies(), ShowTech(), and TogglePedia().
m_population
std::shared_ptr<StatisticIcon> MapWnd::m_population private
Referenced by CompleteConstruction(), and RefreshPopulationIndicator().
m_popups
std::list<std::weak_ptr<MapWndPopup> > MapWnd::m_popups private
list of currently active popup windows
Referenced by CloseAllPopups(), HideAllPopups(), RegisterPopup(), RemovePopup(), and ShowAllPopups().
m_production_wnd
std::shared_ptr<ProductionWnd> MapWnd::m_production_wnd private
production screen
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), DoLayout(), EnableOrderIssuing(), HideProduction(), InitTurn(), PlanetDoubleClicked(), ResetEmpireShown(), ReturnToMap(), Sanitize(), SelectedPlanetID(), SelectPlanet(), SelectSystem(), ShowBuildingType(), ShowEmpire(), ShowFieldType(), ShowPedia(), ShowPlanet(), ShowPolicy(), ShowProduction(), ShowShipDesign(), ShowShipPart(), ShowSpecial(), ShowSpecies(), ShowTech(), SystemDoubleClicked(), ToggleEmpires(), ToggleGovernment(), ToggleMessages(), ToggleModeratorActions(), ToggleObjects(), TogglePedia(), and ToggleSitRep().
m_projected_fleet_lines
std::map<int, MovementLineData> MapWnd::m_projected_fleet_lines private
lines that show the projected path of the active fleet in the FleetWnd
Referenced by ClearProjectedFleetMovementLines(), PlotFleetMovement(), RemoveFleet(), RenderFleetMovementLines(), ReplotProjectedFleetMovement(), Sanitize(), and SetProjectedFleetMovementLine().
m_radii_radii_vertices_indices_runs
std::vector<std::pair<std::pair<std::size_t, std::size_t>, std::pair<std::size_t, std::size_t> > > MapWnd::m_radii_radii_vertices_indices_runs private
Referenced by ClearVisibilityRadiiRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), and RenderVisibilityRadii().
m_RC_starlane_colors
GG::GLRGBAColorBuffer MapWnd::m_RC_starlane_colors private
Referenced by ClearStarlaneRenderingBuffers(), InitStarlaneRenderingBuffers(), and RenderStarlanes().
m_RC_starlane_vertices
GG::GL2DVertexBuffer MapWnd::m_RC_starlane_vertices private
Referenced by ClearStarlaneRenderingBuffers(), InitStarlaneRenderingBuffers(), and RenderStarlanes().
m_ready_turn
bool MapWnd::m_ready_turn = false private
is turn orders are ready and sent to server?
Referenced by EnableOrderIssuing(), EndTurn(), InitTurn(), RefreshTurnButtonTooltip(), and SystemRightClicked().
m_research
std::shared_ptr<StatisticIcon> MapWnd::m_research private
Referenced by CompleteConstruction(), and RefreshResearchResourceIndicator().
m_research_wasted
std::shared_ptr<GG::Button> MapWnd::m_research_wasted private
Referenced by CompleteConstruction(), and RefreshResearchResourceIndicator().
m_research_wnd
std::shared_ptr<ResearchWnd> MapWnd::m_research_wnd private
research screen
Referenced by CompleteConstruction(), ConnectKeyboardAcceleratorSignals(), DoLayout(), EnableOrderIssuing(), HideResearch(), InitTurn(), InResearchViewMode(), PreRender(), Render(), ResetEmpireShown(), ReturnToMap(), Sanitize(), ShowPedia(), ShowResearch(), ShowTech(), ToggleEmpires(), ToggleGovernment(), ToggleMessages(), ToggleModeratorActions(), ToggleObjects(), TogglePedia(), ToggleResearch(), and ToggleSitRep().
m_scale_circle_vertices
GG::GL2DVertexBuffer MapWnd::m_scale_circle_vertices private
Referenced by ClearScaleCircleRenderingBuffer(), InitScaleCircleRenderingBuffer(), and RenderScaleCircle().
m_scale_line
std::shared_ptr<MapScaleLine> MapWnd::m_scale_line private
indicates the on-screen distance that reprensents an in-universe distance
Referenced by CompleteConstruction(), InitializeWindows(), InitScaleCircleRenderingBuffer(), InitTurn(), Sanitize(), and SetZoom().
m_scanline_shader
ScanlineRenderer MapWnd::m_scanline_shader private
Referenced by RenderFields(), and RenderSystems().
m_selected_fleet_ids
std::set<int> MapWnd::m_selected_fleet_ids private
Referenced by CompleteConstruction(), RefreshFleetButtonSelectionIndicators(), RemoveFleet(), RenderFleetMovementLines(), ReselectLastFleet(), Sanitize(), SelectedFleetsChanged(), SelectFleet(), and SetZoom().
m_selected_ship_ids
std::set<int> MapWnd::m_selected_ship_ids private
Referenced by Sanitize(), and SelectedShipsChanged().
m_side_panel
std::shared_ptr<SidePanel> MapWnd::m_side_panel private
planet view panel on the side of the main map
Referenced by CloseSystemView(), CompleteConstruction(), DoLayout(), EnableOrderIssuing(), HideSidePanel(), InitializeWindows(), LClick(), RegisterWindows(), RemoveWindows(), ReturnToMap(), SelectSystem(), and ToggleProduction().
m_sidepanel_open_before_showing_other
bool MapWnd::m_sidepanel_open_before_showing_other = false private
was the sidepanel open before switching to production, research or design screens? If so, it should be restored when leaving them.
Referenced by HideSidePanel(), and RestoreSidePanel().
m_sitrep_panel
std::shared_ptr<SitRepPanel> MapWnd::m_sitrep_panel private
sitrep panel
Referenced by CompleteConstruction(), DoLayout(), HideSitRep(), InitializeWindows(), InitTurn(), RegisterWindows(), RemoveWindows(), ReturnToMap(), Sanitize(), ShowSitRep(), and ToggleSitRep().
m_star_circle_vertices
GG::GL2DVertexBuffer MapWnd::m_star_circle_vertices private
Referenced by ClearSystemRenderingBuffers().
m_star_core_quad_vertices
std::map<std::shared_ptr<GG::Texture>, GG::GL2DVertexBuffer> MapWnd::m_star_core_quad_vertices private
Referenced by ClearSystemRenderingBuffers(), InitSystemRenderingBuffers(), and RenderSystems().
m_star_halo_quad_vertices
std::map<std::shared_ptr<GG::Texture>, GG::GL2DVertexBuffer> MapWnd::m_star_halo_quad_vertices private
Referenced by ClearSystemRenderingBuffers(), InitSystemRenderingBuffers(), and RenderSystems().
m_star_texture_coords
GG::GLTexCoordBuffer MapWnd::m_star_texture_coords private
Referenced by ClearSystemRenderingBuffers(), InitSystemRenderingBuffers(), and RenderSystems().
m_starfield_colours
GG::GLRGBAColorBuffer MapWnd::m_starfield_colours private
Referenced by ClearStarfieldRenderingBuffers(), InitTurnRendering(), RenderStarfields(), and Sanitize().
m_starfield_verts
GG::GL3DVertexBuffer MapWnd::m_starfield_verts private
Referenced by ClearStarfieldRenderingBuffers(), InitTurnRendering(), RenderStarfields(), and Sanitize().
m_starlane_colors
GG::GLRGBAColorBuffer MapWnd::m_starlane_colors private
Referenced by ClearStarlaneRenderingBuffers(), InitStarlaneRenderingBuffers(), and RenderStarlanes().
m_starlane_endpoints
std::map<std::pair<int, int>, LaneEndpoints> MapWnd::m_starlane_endpoints private
map from starlane start and end system IDs (stored in pair in increasing order) to the universe coordiates at which to draw the starlane ends
Referenced by InitStarlaneRenderingBuffers(), MovingFleetMapPositionOnLane(), Sanitize(), SetFleetMovementLine(), and SetProjectedFleetMovementLine().
m_starlane_vertices
GG::GL2DVertexBuffer MapWnd::m_starlane_vertices private
Referenced by ClearStarlaneRenderingBuffers(), InitStarlaneRenderingBuffers(), and RenderStarlanes().
m_stationary_fleet_buttons
std::unordered_map<int, std::unordered_set<std::shared_ptr<FleetButton> > > MapWnd::m_stationary_fleet_buttons private
Icons representing fleets at a system that are not departing, indexed by system.
Referenced by DeferredRefreshFleetButtons(), DeleteFleetButtons(), DoFleetButtonsLayout(), and RefreshFleetButtonSelectionIndicators().
m_stockpile
std::shared_ptr<StatisticIcon> MapWnd::m_stockpile private
Referenced by CompleteConstruction(), and RefreshIndustryResourceIndicator().
m_system_fleet_insert_remove_signals
std::unordered_map<int, std::vector<boost::signals2::connection> > MapWnd::m_system_fleet_insert_remove_signals private
Referenced by InitTurn(), and Sanitize().
m_system_icons
std::unordered_map<int, std::shared_ptr<SystemIcon> > MapWnd::m_system_icons private
system icons in the main map, indexed by system id
Referenced by DoFleetButtonsLayout(), DoSystemIconsLayout(), HideSystemNames(), InitStarlaneRenderingBuffers(), InitSystemRenderingBuffers(), InitTurnRendering(), RenderSystemOverlays(), RenderSystems(), Sanitize(), SelectSystem(), and ShowSystemNames().
m_timeout_clock
GG::Timer MapWnd::m_timeout_clock {1000} private
clock to update remaining time
Referenced by CompleteConstruction(), ResetTimeoutClock(), and TimerFiring().
m_timeout_remain
std::shared_ptr<GG::Label> MapWnd::m_timeout_remain private
label to show remaining time
Referenced by CompleteConstruction(), and TimerFiring().
m_timeout_time
std::chrono::time_point<std::chrono::high_resolution_clock> MapWnd::m_timeout_time private
Referenced by ResetTimeoutClock(), and TimerFiring().
m_toolbar
std::shared_ptr<CUIToolBar> MapWnd::m_toolbar private
Referenced by CompleteConstruction(), DoLayout(), InitializeWindows(), InitTurn(), and Sanitize().
m_visibility_radii_border_colors
GG::GLRGBAColorBuffer MapWnd::m_visibility_radii_border_colors private
Referenced by ClearVisibilityRadiiRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), and RenderVisibilityRadii().
m_visibility_radii_border_vertices
GG::GL2DVertexBuffer MapWnd::m_visibility_radii_border_vertices private
Referenced by ClearVisibilityRadiiRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), and RenderVisibilityRadii().
m_visibility_radii_colors
GG::GLRGBAColorBuffer MapWnd::m_visibility_radii_colors private
Referenced by ClearVisibilityRadiiRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), and RenderVisibilityRadii().
m_visibility_radii_vertices
GG::GL2DVertexBuffer MapWnd::m_visibility_radii_vertices private
Referenced by ClearVisibilityRadiiRenderingBuffers(), InitVisibilityRadiiRenderingBuffers(), and RenderVisibilityRadii().
m_wnd_stack
std::vector<std::weak_ptr<GG::Wnd> > MapWnd::m_wnd_stack private
stack of open windows, to allow closing them with escape in a LIFO order
Referenced by PushWndStack(), RemoveFromWndStack(), and ReturnToMap().
m_zoom_slider
std::shared_ptr<GG::Slider<double> > MapWnd::m_zoom_slider private
allows user to set zoom level;
Referenced by CompleteConstruction(), RefreshSliders(), Sanitize(), and SetZoom().
m_zoom_steps_in
double MapWnd::m_zoom_steps_in = 1.0 private
number of zoom steps in. each 1.0 step increases display scaling by the same zoom step factor
Referenced by CompleteConstruction(), GetSaveGameUIData(), RestoreFromSaveData(), Sanitize(), SetZoom(), Zoom(), and ZoomFactor().
SystemBrowsedSignal
boost::signals2::signal<void (int)> MapWnd::SystemBrowsedSignal mutable
Referenced by MouseEnteringSystem().
SystemLeftClickedSignal
boost::signals2::signal<void (int)> MapWnd::SystemLeftClickedSignal mutable
Referenced by SystemLeftClicked().
SystemRightClickedSignal
boost::signals2::signal<void (int)> MapWnd::SystemRightClickedSignal mutable
Referenced by SystemRightClicked().
ZoomedSignal
boost::signals2::signal<void (double)> MapWnd::ZoomedSignal mutable
Referenced by SetZoom().
The documentation for this class was generated from the following files:
MapWnd.h
MapWnd.cpp