FreeOrion: SaveFileDialog Class Reference
SaveFileDialog Class Reference
#include <SaveFileDialog.h>
Public Types
enum Purpose { Purpose::Save, Purpose::Load }
enum SaveType { SaveType::SinglePlayer, SaveType::MultiPlayer }
Public Member Functions
std::string Result () const
Get the chosen save files full path.
Structors
SaveFileDialog (const Purpose purpose=Purpose::Load, const SaveType type=SaveType::SinglePlayer)
void CompleteConstruction () override
~SaveFileDialog ()
Mutators
void ModalInit () override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void SetPreviewList (const PreviewInformation &preview_info)
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
void CompleteConstruction () override
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
void SaveDefaultedOptions ()
Private Member Functions
SaveFileDialog (const SaveFileDialog &)
Remove copy ctor, assign.
void AskDelete ()
when a file is trying to be deleted
void Cancel ()
when m_load_btn button is pressed
bool CheckChoiceValidity ()
Disables confirm if filename invalid. Returns false if not valid.
void Confirm ()
when m_save_btn button is pressed
void DirectoryEdited (const std::string &filename)
Called when the directory text changes.
void DoubleClickRow (GG::ListBox::iterator row, const GG::Pt &pt, const GG::Flags< GG::ModKey > &mod)
void FileNameEdited (const std::string &filename)
Called when the filename changes.
std::string GetDirPath () const
Gets the current directory path string clean of display decorations.
void Init ()
SaveFileDialog & operator= (const SaveFileDialog &)
void SelectionChanged (const GG::ListBox::SelectionSet &files)
When file selection changes.
void SetDirPath (const std::string &path)
Sets the shown directory path, applying decorations if applicable.
void SetPreviewList (const boost::filesystem::path &path)
void SetPreviewListCore (const std::function< void()> &setup_preview_info)
void UpdateDirectory (const std::string &newdir)
Change current directory.
void UpdatePreviewList ()
Private Attributes
std::shared_ptr< GG::Button > m_confirm_btn
Button to confirm choice;.
std::shared_ptr< GG::Edit > m_current_dir_edit
The editor for the save directory;.
std::string m_extension
The save game file name extension.
std::shared_ptr< SaveFileListBox > m_file_list
The list of available saves.
std::shared_ptr< GG::Layout > m_layout
The layout of the dialog;.
bool m_load_only
Whether we are loading.
std::string m_loaded_dir
The directory whose contents are currently shown.
std::shared_ptr< GG::Edit > m_name_edit
The file name edit control;.
bool m_server_previews
If true, get the previews from the server.
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "UI.windows."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
A dialog for choosing save files. Shows some additional infoormation in the listing and more in a preview section to the side.
Member Enumeration Documentation
enum SaveFileDialog::Purpose strong
Enumerator
Save
Load
enum SaveFileDialog::SaveType strong
Enumerator
SinglePlayer
MultiPlayer
Constructor & Destructor Documentation
SaveFileDialog::SaveFileDialog (const Purpose purpose = Purpose::Load, const SaveType type = SaveType::SinglePlayer)
SaveFileDialog::~SaveFileDialog ()
SaveFileDialog::SaveFileDialog (const SaveFileDialog &) private
Remove copy ctor, assign.
Member Function Documentation
void SaveFileDialog::AskDelete () private
when a file is trying to be deleted
References m_file_list, m_name_edit, m_server_previews, anonymous_namespace{SaveFileDialog.cpp}::Prompt(), Result(), and UserString().
Referenced by Init(), and KeyPress().
GG::Rect SaveFileDialog::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), and anonymous_namespace{MapWnd.cpp}::AppWidth().
void SaveFileDialog::Cancel () private
when m_load_btn button is pressed
References CUIWnd::CloseClicked(), DebugLogger, and m_name_edit.
Referenced by Init(), and KeyPress().
bool SaveFileDialog::CheckChoiceValidity () private
Disables confirm if filename invalid. Returns false if not valid.
References FilenameToPath(), GetDirPath(), m_confirm_btn, m_current_dir_edit, m_file_list, m_load_only, m_name_edit, m_server_previews, and ClientUI::TextColor().
Referenced by Confirm(), DirectoryEdited(), FileNameEdited(), KeyPress(), SelectionChanged(), SetPreviewListCore(), and UpdatePreviewList().
void SaveFileDialog::CompleteConstruction () override
References CUIWnd::CompleteConstruction(), and Init().
void SaveFileDialog::Confirm () private
when m_save_btn button is pressed
Check if we chose a directory
References CheckChoiceValidity(), CUIWnd::CloseClicked(), DebugLogger, ErrorLogger, FilenameToPath(), FlexibleFormat(), GetDirPath(), IsValidUTF8(), m_extension, m_load_only, m_name_edit, m_server_previews, PathToString(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), Result(), UpdateDirectory(), UserString(), and WarnLogger.
Referenced by DoubleClickRow(), Init(), and KeyPress().
void SaveFileDialog::DirectoryEdited (const std::string & filename) private
Called when the directory text changes.
References CheckChoiceValidity().
Referenced by Init().
void SaveFileDialog::DoubleClickRow (GG::ListBox::iterator row, const GG::Pt & pt, const GG::Flags< GG::ModKey > & mod) private
References Confirm(), and m_file_list.
Referenced by Init().
void SaveFileDialog::FileNameEdited (const std::string & filename) private
Called when the filename changes.
References CheckChoiceValidity().
Referenced by Init().
std::string SaveFileDialog::GetDirPath () const private
Gets the current directory path string clean of display decorations.
References DebugLogger, ErrorLogger, m_current_dir_edit, and m_server_previews.
Referenced by CheckChoiceValidity(), Confirm(), KeyPress(), Result(), and UpdatePreviewList().
void SaveFileDialog::Init () private
References AskDelete(), CUIWnd::BottomBorder(), Cancel(), Confirm(), DebugLogger, DirectoryEdited(), DoubleClickRow(), FileNameEdited(), FilenameTimestamp(), HumanClientApp::GetApp(), ClientUI::GetFont(), GetSaveDir(), CUIWnd::LeftBorder(), m_confirm_btn, m_current_dir_edit, m_extension, m_file_list, m_layout, m_load_only, m_name_edit, m_server_previews, MP_SAVE_FILE_EXTENSION, PathToString(), CUIWnd::ResetDefaultPosition(), CUIWnd::RightBorder(), anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_BUTTON_MARGIN(), CUIWnd::SaveDefaultedOptions(), CUIWnd::SaveOptions(), SelectionChanged(), SetDirPath(), HumanClientApp::SinglePlayerGame(), SP_SAVE_FILE_EXTENSION, CUIWnd::TopBorder(), UpdatePreviewList(), and UserString().
Referenced by CompleteConstruction().
void SaveFileDialog::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Update the previews with preview_info
References AskDelete(), Cancel(), CheckChoiceValidity(), Confirm(), GetDirPath(), m_current_dir_edit, m_loaded_dir, m_name_edit, and UpdatePreviewList().
void SaveFileDialog::ModalInit () override
Update the previews with preview_info
References m_name_edit.
SaveFileDialog& SaveFileDialog::operator= (const SaveFileDialog &) private
std::string SaveFileDialog::Result () const
Get the chosen save files full path.
References FilenameToPath(), GetDirPath(), m_name_edit, and PathToString().
Referenced by AskDelete(), and Confirm().
void SaveFileDialog::SelectionChanged (const GG::ListBox::SelectionSet & files) private
When file selection changes.
References CheckChoiceValidity(), DebugLogger, SaveFileRow::Filename(), and m_name_edit.
Referenced by Init().
void SaveFileDialog::SetDirPath (const std::string & path) private
Sets the shown directory path, applying decorations if applicable.
References m_current_dir_edit, m_server_previews, and PathToString().
Referenced by Init(), SetPreviewList(), and UpdateDirectory().
void SaveFileDialog::SetPreviewList (const PreviewInformation & preview_info)
Update the previews with preview_info
References PreviewInformation::folder, m_file_list, PreviewInformation::previews, SetDirPath(), SetPreviewListCore(), and PreviewInformation::subdirectories.
Referenced by UpdatePreviewList().
void SaveFileDialog::SetPreviewList (const boost::filesystem::path & path) private
Update the preview list from a local save directory
void SaveFileDialog::SetPreviewListCore (const std::function< void()> & setup_preview_info) private
Update the previews with preview info set by setup_preview_info
References CheckChoiceValidity(), and m_file_list.
Referenced by SetPreviewList(), and UpdatePreviewList().
void SaveFileDialog::UpdateDirectory (const std::string & newdir) private
Change current directory.
References SetDirPath(), and UpdatePreviewList().
Referenced by Confirm().
void SaveFileDialog::UpdatePreviewList () private
Either directly update from the local save directory, or request the server for save preview information
References CheckChoiceValidity(), FilenameToPath(), HumanClientApp::GetApp(), GetDirPath(), m_extension, m_file_list, m_server_previews, HumanClientApp::RequestSavePreviews(), SetPreviewList(), and SetPreviewListCore().
Referenced by Init(), KeyPress(), and UpdateDirectory().
Member Data Documentation
std::shared_ptr<GG::Button> SaveFileDialog::m_confirm_btn private
Button to confirm choice;.
Referenced by CheckChoiceValidity(), and Init().
std::shared_ptr<GG::Edit> SaveFileDialog::m_current_dir_edit private
The editor for the save directory;.
Referenced by CheckChoiceValidity(), GetDirPath(), Init(), KeyPress(), and SetDirPath().
std::string SaveFileDialog::m_extension private
The save game file name extension.
Referenced by Confirm(), Init(), and UpdatePreviewList().
std::shared_ptr<SaveFileListBox> SaveFileDialog::m_file_list private
The list of available saves.
Referenced by AskDelete(), CheckChoiceValidity(), DoubleClickRow(), Init(), SetPreviewList(), SetPreviewListCore(), and UpdatePreviewList().
std::shared_ptr<GG::Layout> SaveFileDialog::m_layout private
The layout of the dialog;.
Referenced by Init().
bool SaveFileDialog::m_load_only private
Whether we are loading.
Referenced by CheckChoiceValidity(), Confirm(), and Init().
std::string SaveFileDialog::m_loaded_dir private
The directory whose contents are currently shown.
Referenced by KeyPress().
std::shared_ptr<GG::Edit> SaveFileDialog::m_name_edit private
The file name edit control;.
Referenced by AskDelete(), Cancel(), CheckChoiceValidity(), Confirm(), Init(), KeyPress(), ModalInit(), Result(), and SelectionChanged().
bool SaveFileDialog::m_server_previews private
If true, get the previews from the server.
Referenced by AskDelete(), CheckChoiceValidity(), Confirm(), GetDirPath(), Init(), SetDirPath(), and UpdatePreviewList().
The documentation for this class was generated from the following files:
SaveFileDialog.h
SaveFileDialog.cpp