FreeOrion: SpecialsManager Class Reference
SpecialsManager Class Reference
Look up table for specials.
#include <Special.h>
Public Types
using SpecialsTypeMap = std::map< std::string, std::unique_ptr< Special > >
Public Member Functions
SpecialsManager ()
~SpecialsManager ()
unsigned int GetCheckSum () const
const Special * GetSpecial (const std::string &name) const
int NumSpecials () const
void SetSpecialsTypes (Pending::Pending< SpecialsTypeMap > &&future)
Sets types to the value of future.
std::vector< std::string > SpecialNames () const
Private Member Functions
void CheckPendingSpecialsTypes () const
Assigns any m_pending_types to m_specials.
Private Attributes
boost::optional< Pending::Pending< SpecialsTypeMap > > m_pending_types = boost::none
Future types being parsed by parser.
SpecialsTypeMap m_specials
Detailed Description
Look up table for specials.
Member Typedef Documentation
SpecialsTypeMap
using SpecialsManager::SpecialsTypeMap = std::map<std::string, std::unique_ptr<Special> >
Constructor & Destructor Documentation
SpecialsManager()
SpecialsManager::SpecialsManager ()
~SpecialsManager()
SpecialsManager::~SpecialsManager ()
Member Function Documentation
CheckPendingSpecialsTypes()
void SpecialsManager::CheckPendingSpecialsTypes () const private
Assigns any m_pending_types to m_specials.
References m_pending_types, m_specials, and Pending::SwapPending().
Referenced by GetCheckSum(), GetSpecial(), and SpecialNames().
GetCheckSum()
unsigned int SpecialsManager::GetCheckSum () const
References CheckPendingSpecialsTypes(), CheckSums::CheckSumCombine(), DebugLogger, and m_specials.
Referenced by CheckSumContent().
GetSpecial()
const Special * SpecialsManager::GetSpecial (const std::string & name) const
References CheckPendingSpecialsTypes(), and m_specials.
Referenced by GetSpecial().
NumSpecials()
int SpecialsManager::NumSpecials () const inline
References GetSpecial(), and SpecialNames().
SetSpecialsTypes()
void SpecialsManager::SetSpecialsTypes (Pending::Pending< SpecialsTypeMap > && future)
Sets types to the value of future.
References m_pending_types.
Referenced by IApp::StartBackgroundParsing().
SpecialNames()
std::vector< std::string > SpecialsManager::SpecialNames () const
References CheckPendingSpecialsTypes(), and m_specials.
Referenced by SpecialNames().
Member Data Documentation
m_pending_types
boost::optional<Pending::Pending<SpecialsTypeMap> > SpecialsManager::m_pending_types = boost::none mutable private
Future types being parsed by parser.
mutable so that it can be assigned to m_species_types when completed.
Referenced by CheckPendingSpecialsTypes(), and SetSpecialsTypes().
m_specials
SpecialsTypeMap SpecialsManager::m_specials mutable private
Referenced by CheckPendingSpecialsTypes(), GetCheckSum(), GetSpecial(), and SpecialNames().
The documentation for this class was generated from the following files:
Special.h
Special.cpp