FreeOrion: ShipDesignPanel Class Reference
ShipDesignPanel Class Reference
#include <ShipDesignPanel.h>
Public Member Functions
Structors
ShipDesignPanel (GG::X w, GG::Y h, int design_id)
Accessors
int DesignID () const
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Render () override
void Update ()
Protected Attributes
GG::StaticGraphic * m_graphic
GG::Label * m_name
Private Attributes
int m_design_id
id for the ShipDesign this panel displays
Detailed Description
Represents a ShipDesign
Constructor & Destructor Documentation
ShipDesignPanel::ShipDesignPanel (GG::X w, GG::Y h, int design_id)
References GetShipDesign(), m_design_id, m_graphic, m_name, and ClientUI::ShipDesignIcon().
Member Function Documentation
int ShipDesignPanel::DesignID () const inline
References m_design_id, Render(), SizeMove(), and Update().
void ShipDesignPanel::Render () override
Referenced by DesignID().
void ShipDesignPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References m_graphic, and m_name.
Referenced by DesignID().
void ShipDesignPanel::Update ()
References GetShipDesign(), m_design_id, and m_name.
Referenced by DesignID().
Member Data Documentation
int ShipDesignPanel::m_design_id private
id for the ShipDesign this panel displays
Referenced by DesignID(), ShipDesignPanel(), and Update().
GG::StaticGraphic* ShipDesignPanel::m_graphic protected
Referenced by ShipDesignPanel(), and SizeMove().
GG::Label* ShipDesignPanel::m_name protected
Referenced by ShipDesignPanel(), SizeMove(), and Update().
The documentation for this class was generated from the following files:
ShipDesignPanel.h
ShipDesignPanel.cpp