FreeOrion: anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd Class Reference
anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd Class Reference
BrowseInfoWnd for the fleet icon tooltip.
Public Types
typedef std::pair< std::shared_ptr< CUILabel >, std::shared_ptr< CUILabel > > LabelValueType
Public Member Functions
FleetDetailBrowseWnd (int empire_id, GG::X width)
void DoLayout ()
void NewLabelValue (const std::string &descr, bool title=false)
Constructs and attaches new description and value labels for the given description row descr.
void PreRender () override
void Render () override
void UpdateLabels ()
Updates the text displayed for the value of each label.
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Protected Member Functions
void LayoutRow (const std::string &descr, GG::Pt &descr_ul, GG::Pt &descr_lr, GG::Pt &value_ul, GG::Pt &value_lr, const GG::Pt &row_advance)
Resize/Move controls for row descr and then advance sizes by row_advance.
void LayoutRow (LabelValueType &row, GG::Pt &descr_ul, GG::Pt &descr_lr, GG::Pt &value_ul, GG::Pt &value_lr, const GG::Pt &row_advance)
void ResetShipDesignLabels ()
Remove the old labels for ship design counts, and add the new ones.
void UpdateValues ()
Updates the value for display with each label.
Private Member Functions
void UpdateImpl (size_t mode, const Wnd *target) override
Private Attributes
std::vector< GG::X > m_col_widths
widths of each column
int m_empire_id
ID of the viewing empire.
std::unordered_map< std::string, LabelValueType > m_labels
Label controls mapped to the description key.
int m_margin
margin between controls
std::unordered_map< int, int > m_ship_design_counts
Map of ship design ids to the number of ships with that id.
std::vector< LabelValueType > m_ship_design_labels
Label controls for ship designs, sorted by disply name.
std::unordered_map< std::string, int > m_values
Internal value for display with a description.
Detailed Description
BrowseInfoWnd for the fleet icon tooltip.
Member Typedef Documentation
typedef std::pair<std::shared_ptr<CUILabel>, std::shared_ptr<CUILabel> > anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::LabelValueType
Constructor & Destructor Documentation
anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::FleetDetailBrowseWnd (int empire_id, GG::X width) inline
References ClientUI::Pts().
Member Function Documentation
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout () inline
References anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_ARMED_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_CARRIER_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_COLONY_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_PART_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SHIP_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SLOT_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_TROOP_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_UNARMED_COUNT, and ClientUI::Pts().
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::LayoutRow (const std::string & descr, GG::Pt & descr_ul, GG::Pt & descr_lr, GG::Pt & value_ul, GG::Pt & value_lr, const GG::Pt & row_advance) inline protected
Resize/Move controls for row descr and then advance sizes by row_advance.
References ErrorLogger.
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::LayoutRow (LabelValueType & row, GG::Pt & descr_ul, GG::Pt & descr_lr, GG::Pt & value_ul, GG::Pt & value_lr, const GG::Pt & row_advance) inline protected
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::NewLabelValue (const std::string & descr, bool title = false) inline
Constructs and attaches new description and value labels for the given description row descr.
References ClientUI::GetBoldFont(), ClientUI::Pts(), and UserString().
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender () inline override
References anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_ARMED_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_CARRIER_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_COLONY_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_PART_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SHIP_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SLOT_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_TROOP_COUNT, and anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_UNARMED_COUNT.
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::Render () inline override
References ClientUI::Pts(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::ResetShipDesignLabels () inline protected
Remove the old labels for ship design counts, and add the new ones.
The stats themselves are updated in UpdateValues.
References GetShipDesign(), ShipDesign::Name(), ClientUI::Pts(), and to_string().
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateImpl (size_t mode, const Wnd * target) inline override private
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateLabels () inline
Updates the text displayed for the value of each label.
References to_string().
void anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues () inline protected
Updates the value for display with each label.
References ALL_EMPIRES, Universe::EmpireKnownDestroyedObjectIDs(), anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_ARMED_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_CARRIER_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_COLONY_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_PART_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SHIP_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SLOT_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_TROOP_COUNT, anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_UNARMED_COUNT, GetUniverse(), ShipDesign::ID(), Objects(), and ShipDesign::Parts().
bool anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const inline override
Member Data Documentation
std::vector<GG::X> anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_col_widths private
widths of each column
int anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_empire_id private
ID of the viewing empire.
std::unordered_map<std::string, LabelValueType> anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_labels private
Label controls mapped to the description key.
int anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_margin private
margin between controls
std::unordered_map<int, int> anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_ship_design_counts private
Map of ship design ids to the number of ships with that id.
std::vector<LabelValueType> anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_ship_design_labels private
Label controls for ship designs, sorted by disply name.
std::unordered_map<std::string, int> anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::m_values private
Internal value for display with a description.
The documentation for this class was generated from the following file:
MapWnd.cpp