FreeOrion: DesignWnd Class Reference
DesignWnd Class Reference
#include <DesignWnd.h>
Classes
class BaseSelector
class MainPanel
class PartPalette
Public Member Functions
Structors
DesignWnd (GG::X w, GG::Y h)
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Render () override
void Reset ()
void Sanitize ()
void ShowPartTypeInEncyclopedia (const std::string &part_type)
void ShowHullTypeInEncyclopedia (const std::string &hull_type)
void ShowShipDesignInEncyclopedia (int design_id)
void EnableOrderIssuing (bool enable=true)
Private Member Functions
void AddDesign ()
adds current design to those stored by this empire, allowing ships of this design to be produced
int AddDesignCore ()
Adds the current design to those stored by the empire and returns the new_id or INVALID_DESIGN_ID on failure.
void DesignChanged ()
void DesignNameChanged ()
void InitializeWindows ()
void ReplaceDesign ()
replace selected completed design with the current design in the stored designs of this empire
Private Attributes
BaseSelector * m_base_selector
EncyclopediaDetailPanel * m_detail_panel
MainPanel * m_main_panel
PartPalette * m_part_palette
Detailed Description
Lets the player design ships
Constructor & Destructor Documentation
DesignWnd::DesignWnd (GG::X w, GG::Y h)
References AddDesign(), DesignWnd::MainPanel::AddPart(), DesignWnd::MainPanel::CompleteDesignClickedSignal, anonymous_namespace{DesignWnd.cpp}::DES_BASE_SELECTOR_WND_NAME, anonymous_namespace{DesignWnd.cpp}::DES_MAIN_WND_NAME, anonymous_namespace{DesignWnd.cpp}::DES_PART_PALETTE_WND_NAME, anonymous_namespace{DesignWnd.cpp}::DES_PEDIA_WND_NAME, DesignChanged(), DesignWnd::MainPanel::DesignChangedSignal, DesignWnd::BaseSelector::DesignClickedSignal, DesignWnd::BaseSelector::DesignComponentsSelectedSignal, DesignWnd::MainPanel::DesignConfirmedSignal, DesignNameChanged(), DesignWnd::MainPanel::DesignNameChangedSignal, DesignWnd::MainPanel::DesignReplacedSignal, DesignWnd::BaseSelector::DesignSelectedSignal, HumanClientApp::GetApp(), DesignWnd::BaseSelector::HullClickedSignal, DesignWnd::MainPanel::HullTypeClickedSignal, InitializeWindows(), m_base_selector, m_detail_panel, m_main_panel, m_part_palette, DesignWnd::PartPalette::PartTypeClickedSignal, DesignWnd::MainPanel::PartTypeClickedSignal, DesignWnd::PartPalette::PartTypeDoubleClickedSignal, PINABLE, ReplaceDesign(), HumanClientApp::RepositionWindowsSignal, DesignWnd::MainPanel::Sanitize(), DesignWnd::BaseSelector::SavedDesignSelectedSignal, EncyclopediaDetailPanel::SetDesign(), DesignWnd::MainPanel::SetDesign(), DesignWnd::MainPanel::SetDesignComponents(), and EncyclopediaDetailPanel::SetItem().
Member Function Documentation
void DesignWnd::AddDesign () private
adds current design to those stored by this empire, allowing ships of this design to be produced
References AddDesignCore().
Referenced by DesignWnd().
int DesignWnd::AddDesignCore () private
Adds the current design to those stored by the empire and returns the new_id or INVALID_DESIGN_ID on failure.
References CurrentTurn(), DebugLogger, DesignWnd::MainPanel::DesignChangedSignal, DesignWnd::MainPanel::DesignDescription(), ClientApp::EmpireID(), AIInterface::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), ClientApp::GetApp(), GetEmpire(), GetHullType(), ClientApp::GetNewDesignID(), DesignWnd::MainPanel::Hull(), ShipDesign::INVALID_DESIGN_ID, OrderSet::IssueOrder(), m_main_panel, ShipDesign::Name(), ClientApp::Orders(), DesignWnd::MainPanel::Parts(), DesignWnd::MainPanel::ReregisterDesigns(), DesignWnd::MainPanel::ValidatedDesignName(), and ShipDesign::ValidDesign().
Referenced by AddDesign(), and ReplaceDesign().
void DesignWnd::DesignChanged () private
References DesignWnd::MainPanel::GetIncompleteDesign(), m_detail_panel, m_main_panel, and EncyclopediaDetailPanel::SetIncompleteDesign().
Referenced by DesignWnd().
void DesignWnd::DesignNameChanged () private
References DesignWnd::MainPanel::GetIncompleteDesign(), m_detail_panel, m_main_panel, and EncyclopediaDetailPanel::SetIncompleteDesign().
Referenced by DesignWnd().
void DesignWnd::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this DesignWnd.
References DesignWnd::BaseSelector::EnableOrderIssuing(), and m_base_selector.
Referenced by MapWnd::EnableOrderIssuing().
void DesignWnd::InitializeWindows () private
References CUIWnd::InitSizeMove(), m_base_selector, m_detail_panel, m_main_panel, and m_part_palette.
Referenced by DesignWnd().
void DesignWnd::Render () override
Shows part_type in design encyclopedia window
References ClientUI::WndColor().
void DesignWnd::ReplaceDesign () private
replace selected completed design with the current design in the stored designs of this empire
References AddDesignCore(), DebugLogger, ClientApp::EmpireID(), HumanClientApp::GetApp(), DesignWnd::MainPanel::GetReplacedDesignID(), ShipDesign::INVALID_DESIGN_ID, OrderSet::IssueOrder(), m_main_panel, and ClientApp::Orders().
Referenced by DesignWnd().
void DesignWnd::Reset ()
Shows part_type in design encyclopedia window
References m_base_selector, m_detail_panel, m_main_panel, m_part_palette, EncyclopediaDetailPanel::Refresh(), DesignWnd::PartPalette::Reset(), DesignWnd::BaseSelector::Reset(), and DesignWnd::MainPanel::Sanitize().
Referenced by MapWnd::ShowDesign().
void DesignWnd::Sanitize ()
Shows part_type in design encyclopedia window
References m_main_panel, and DesignWnd::MainPanel::Sanitize().
Referenced by MapWnd::Sanitize().
void DesignWnd::ShowHullTypeInEncyclopedia (const std::string & hull_type)
Shows hull_type in design encyclopedia window
References m_detail_panel, and EncyclopediaDetailPanel::SetHullType().
Referenced by MapWnd::ShowHullType().
void DesignWnd::ShowPartTypeInEncyclopedia (const std::string & part_type)
Shows part_type in design encyclopedia window
References m_detail_panel, and EncyclopediaDetailPanel::SetPartType().
Referenced by MapWnd::ShowPartType().
void DesignWnd::ShowShipDesignInEncyclopedia (int design_id)
Shows ship design with id design_id in design encyclopedia window
References m_detail_panel, and EncyclopediaDetailPanel::SetDesign().
void DesignWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Shows part_type in design encyclopedia window
References m_base_selector, m_detail_panel, m_main_panel, m_part_palette, and CUIWnd::ValidatePosition().
Member Data Documentation
BaseSelector* DesignWnd::m_base_selector private
Referenced by DesignWnd(), EnableOrderIssuing(), InitializeWindows(), Reset(), and SizeMove().
EncyclopediaDetailPanel* DesignWnd::m_detail_panel private
Referenced by DesignChanged(), DesignNameChanged(), DesignWnd(), InitializeWindows(), Reset(), ShowHullTypeInEncyclopedia(), ShowPartTypeInEncyclopedia(), ShowShipDesignInEncyclopedia(), and SizeMove().
MainPanel* DesignWnd::m_main_panel private
Referenced by AddDesignCore(), DesignChanged(), DesignNameChanged(), DesignWnd(), InitializeWindows(), ReplaceDesign(), Reset(), Sanitize(), and SizeMove().
PartPalette* DesignWnd::m_part_palette private
Referenced by DesignWnd(), InitializeWindows(), Reset(), and SizeMove().
The documentation for this class was generated from the following files:
DesignWnd.h
DesignWnd.cpp