FreeOrion: ColonizeOrder Class Reference
ColonizeOrder Class Reference
#include <Order.h>
Public Member Functions
Structors
ColonizeOrder (int empire, int ship, int planet)
Accessors
int PlanetID () const
int ShipID () const
Public Member Functions inherited from Order
void Execute () const
bool Undo () const
Order ()
Order (int empire)
virtual ~Order ()
int EmpireID () const
Private Member Functions
ColonizeOrder ()=default
void ExecuteImpl () const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
bool UndoImpl () const override
Private Attributes
int m_planet = INVALID_OBJECT_ID
int m_ship = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
bool Executed () const
Detailed Description
the Order subclass that represents a planet colonization action
Constructor & Destructor Documentation
ColonizeOrder::ColonizeOrder (int empire, int ship, int planet)
ColonizeOrder::ColonizeOrder () private default
Member Function Documentation
void ColonizeOrder::ExecuteImpl () const override private virtual
Preconditions:
m_planet must be the ID of an un-owned planet.
m_ship must be the the ID of a ship owned by the issuing empire
m_ship must be the ID of a ship that can colonize and that is in the same system as the planet.
Postconditions:
The ship with ID m_ship will be marked to colonize the planet with id m_planet during the next turn processing.
Implements Order.
References Order::EmpireID(), ErrorLogger, GetFleet(), GetPlanet(), GetShip(), GetUniverse(), Order::GetValidatedEmpire(), INVALID_OBJECT_ID, m_planet, m_ship, and METER_POPULATION.
int ColonizeOrder::PlanetID () const inline
Returns ID of the planet to be colonized.
template<class Archive > void ColonizeOrder::serialize (Archive & ar, const unsigned int version) private
int ColonizeOrder::ShipID () const inline
Returns ID of the ship which is colonizing the planet.
References Order::ExecuteImpl(), and Order::UndoImpl().
bool ColonizeOrder::UndoImpl () const override private virtual
Reimplemented from Order.
References ErrorLogger, GetFleet(), GetPlanet(), GetShip(), m_planet, and m_ship.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
int ColonizeOrder::m_planet = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
int ColonizeOrder::m_ship = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp