FreeOrion: Effect::Destroy Class Reference
Effect::Destroy Class Reference final
Destroys the target object.
#include <Effects.h>
Public Member Functions
Destroy ()
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
virtual void Execute (ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Destroys the target object.
When executed on objects that contain other objects (such as Fleets and Planets), all contained objects are destroyed as well. Destroy effects delay the desctruction of their targets until after other all effects have executed, to ensure the source or target of other effects are present when they execute.
Constructor & Destructor Documentation
Destroy()
Effect::Destroy::Destroy ()
Member Function Documentation
Dump()
std::string Effect::Destroy::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent().
Execute()
void Effect::Destroy::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References ScriptingContext::effect_target, Universe::EffectDestroy(), ErrorLogger, GetUniverse(), INVALID_OBJECT_ID, and ScriptingContext::source.
GetCheckSum()
unsigned int Effect::Destroy::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), and TraceLogger.
serialize()
template<typename Archive > void Effect::Destroy::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::Destroy::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Effect::Effect.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp