FreeOrion: ShipDesignManager Class Reference
ShipDesignManager Class Reference
ShipDesignManager tracks information known to the client about ShipDesigns.
#include <DesignWnd.h>
Classes
class Designs
Designs provides ordered lists of designs for display in the UI.
Public Member Functions
ShipDesignManager ()
virtual ~ShipDesignManager ()
virtual Designs * DisplayedDesigns ()
DisplayedDesigns are design currently producible by the empire, in the ProductionWnd.
virtual void Load (const SaveGameUIData &data)
virtual void Save (SaveGameUIData &data) const
virtual Designs * SavedDesigns ()
SavedDesigns are designs that the player has saved on their own machine for future use.
virtual void StartGame (int empire_id, bool is_new_game)
Private Attributes
std::unique_ptr< Designs > m_displayed_designs
std::unique_ptr< Designs > m_saved_designs
Detailed Description
ShipDesignManager tracks information known to the client about ShipDesigns.
This includes the order of designs to be shown DesignWnd and the BuildDesignator.
Constructor & Destructor Documentation
ShipDesignManager()
ShipDesignManager::ShipDesignManager ()
~ShipDesignManager()
ShipDesignManager::~ShipDesignManager () virtual
Member Function Documentation
DisplayedDesigns()
ShipDesignManager::Designs * ShipDesignManager::DisplayedDesigns () virtual
DisplayedDesigns are design currently producible by the empire, in the ProductionWnd.
References ErrorLogger, and m_displayed_designs.
Referenced by anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), and BuildDesignatorWnd::BuildSelector::PopulateList().
Load()
void ShipDesignManager::Load (const SaveGameUIData & data) virtual
References anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::Load(), SaveGameUIData::obsolete_ship_parts, SaveGameUIData::obsolete_ui_event_count, SaveGameUIData::ordered_ship_design_ids_and_obsolete, and SaveGameUIData::ordered_ship_hull_and_obsolete.
Save()
void ShipDesignManager::Save (SaveGameUIData & data) const virtual
References anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), SaveGameUIData::obsolete_ship_parts, SaveGameUIData::obsolete_ui_event_count, SaveGameUIData::ordered_ship_design_ids_and_obsolete, SaveGameUIData::ordered_ship_hull_and_obsolete, and anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::Save().
SavedDesigns()
ShipDesignManager::Designs * ShipDesignManager::SavedDesigns () virtual
SavedDesigns are designs that the player has saved on their own machine for future use.
They may/may not also be in use in the current game.
References ErrorLogger, and m_saved_designs.
Referenced by anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager().
StartGame()
void ShipDesignManager::StartGame (int empire_id, bool is_new_game) virtual
References DebugLogger, ErrorLogger, HumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), GetShipHullManager(), OrderSet::IssueOrder(), m_displayed_designs, m_saved_designs, ClientApp::Orders(), and TraceLogger.
Referenced by HumanClientApp::StartGame().
Member Data Documentation
m_displayed_designs
std::unique_ptr<Designs> ShipDesignManager::m_displayed_designs private
Referenced by DisplayedDesigns(), and StartGame().
m_saved_designs
std::unique_ptr<Designs> ShipDesignManager::m_saved_designs private
Referenced by SavedDesigns(), and StartGame().
The documentation for this class was generated from the following files:
DesignWnd.h
DesignWnd.cpp