FreeOrion: anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager Class Reference
anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager Class Reference
Public Member Functions
SavedDesignsManager ()
void CheckPendingDesigns () const
void Erase (const boost::uuids::uuid &erased_uuid)
const ShipDesign * GetDesign (const boost::uuids::uuid &uuid) const
std::list< boost::uuids::uuid >::const_iterator InsertBefore (const ShipDesign &design, std::list< boost::uuids::uuid >::const_iterator next)
bool MoveBefore (const boost::uuids::uuid &moved_uuid, const boost::uuids::uuid &next_uuid)
const std::list< boost::uuids::uuid > & OrderedDesignUUIDs () const
std::vector< int > OrderedIDs () const override
void SaveManifest ()
void StartParsingDesignsFromFileSystem (bool is_new_game)
Private Member Functions
void SaveDesign (const boost::uuids::uuid &uuid)
Save the design with the original filename or throw out_of_range.
void SaveDesignConst (const boost::uuids::uuid &uuid) const
SaveDesignConst allows CheckPendingDesigns to correct the designs in the saved directory.
void SaveManifestConst () const
A const version of SaveManifest to allow CheckPendingDesigns to correct and save the loaded designs.
Private Attributes
bool m_is_new_game = false
std::list< boost::uuids::uuid > m_ordered_uuids
boost::optional< std::future< PredefinedShipDesignManager::ParsedShipDesignsType > > m_pending_designs = boost::none
Future ship design type being parsed by parser.
std::unordered_map< boost::uuids::uuid, std::pair< std::unique_ptr< ShipDesign >, boost::filesystem::path >, boost::hash< boost::uuids::uuid > > m_saved_designs
Saved designs with filename.
Constructor & Destructor Documentation
SavedDesignsManager()
anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SavedDesignsManager () inline
Member Function Documentation
CheckPendingDesigns()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns () const
References anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), DebugLogger, anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_EXTENSION, ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), GetOptionsDB(), LoadShipDesignsAndManifestOrderFromParseResults(), TraceLogger, and WarnLogger.
Referenced by anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::OrderedIDs().
Erase()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::Erase (const boost::uuids::uuid & erased_uuid)
GetDesign()
const ShipDesign * anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign (const boost::uuids::uuid & uuid) const
Referenced by anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), DesignWnd::MainPanel::EditingSavedDesign(), SavedDesignsListBox::PopulateCore(), and DesignWnd::MainPanel::SetDesign().
InsertBefore()
std::list< boost::uuids::uuid >::const_iterator anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::InsertBefore (const ShipDesign & design, std::list< boost::uuids::uuid >::const_iterator next)
References anonymous_namespace{DesignWnd.cpp}::CreateSaveFileNameForDesign(), ErrorLogger, ShipDesign::Name(), and ShipDesign::UUID().
Referenced by CompletedDesignsListBox::BaseRightClicked().
MoveBefore()
bool anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::MoveBefore (const boost::uuids::uuid & moved_uuid, const boost::uuids::uuid & next_uuid)
References ErrorLogger.
Referenced by SavedDesignsListBox::BaseRightClicked().
OrderedDesignUUIDs()
const std::list< boost::uuids::uuid > & anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::OrderedDesignUUIDs () const
Referenced by SavedDesignsListBox::BaseRightClicked().
OrderedIDs()
std::vector< int > anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::OrderedIDs () const override virtual
Implements ShipDesignManager::Designs.
SaveDesign()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveDesign (const boost::uuids::uuid & uuid) private
Save the design with the original filename or throw out_of_range.
References anonymous_namespace{DesignWnd.cpp}::WriteToFile().
SaveDesignConst()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveDesignConst (const boost::uuids::uuid & uuid) const private
SaveDesignConst allows CheckPendingDesigns to correct the designs in the saved directory.
SaveManifest()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifest ()
SaveManifestConst()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifestConst () const private
A const version of SaveManifest to allow CheckPendingDesigns to correct and save the loaded designs.
References anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_EXTENSION, anonymous_namespace{DesignWnd.cpp}::GetDesignsDir(), PathToString(), and anonymous_namespace{DesignWnd.cpp}::WriteToFile().
StartParsingDesignsFromFileSystem()
void anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::StartParsingDesignsFromFileSystem (bool is_new_game)
References anonymous_namespace{DesignWnd.cpp}::SavedDesignsDir(), parse::ship_designs(), and TraceLogger.
Member Data Documentation
m_is_new_game
bool anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::m_is_new_game = false mutable private
m_ordered_uuids
std::list<boost::uuids::uuid> anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::m_ordered_uuids mutable private
m_pending_designs
boost::optional<std::future<PredefinedShipDesignManager::ParsedShipDesignsType> > anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::m_pending_designs = boost::none mutable private
Future ship design type being parsed by parser.
mutable so that it can be assigned to m_saved_designs when completed.
m_saved_designs
std::unordered_map<boost::uuids::uuid, std::pair<std::unique_ptr<ShipDesign>, boost::filesystem::path>, boost::hash<boost::uuids::uuid> > anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::m_saved_designs mutable private
Saved designs with filename.
The documentation for this class was generated from the following file:
DesignWnd.cpp