FreeOrion: anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel Class Reference
anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel Class Reference
Public Member Functions
CombatLogAccordionPanel (GG::X w, CombatLogWnd::Impl &log_, int viewing_empire_id_, ConstCombatEventPtr event_)
~CombatLogAccordionPanel ()
void CompleteConstruction () override
Public Member Functions inherited from AccordionPanel
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
void Render () override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void SetInteriorColor (GG::Clr c)
void SetBorderMargin (unsigned int margin)
Private Member Functions
void ToggleExpansion ()
Private Attributes
std::vector< GG::Wnd * > details
ConstCombatEventPtr event
CombatLogWnd::Impl & log
LinkText * title
int viewing_empire_id
Static Private Attributes
static const unsigned int BORDER_MARGIN = 5
Additional Inherited Members
Public Types inherited from AccordionPanel
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Public Attributes inherited from AccordionPanel
ExpandCollapseSignalType ExpandCollapseSignal
Static Public Attributes inherited from AccordionPanel
static const int EXPAND_BUTTON_SIZE = 16
Protected Member Functions inherited from AccordionPanel
virtual void DoLayout ()
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Protected Attributes inherited from AccordionPanel
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin
The number of pixels between the expansion button and the client area.
bool m_collapsed
GG::Button * m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary
GG::Clr m_interior_color
bool m_is_left
Is expand button on the left?
Detailed Description
A Single section in the CombatLog showing general outline of a ship's combat and expanding into specifics.
Constructor & Destructor Documentation
anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CombatLogAccordionPanel (GG::X w, CombatLogWnd::Impl & log_, int viewing_empire_id_, ConstCombatEventPtr event_)
anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::~CombatLogAccordionPanel ()
References AccordionPanel::IsCollapsed().
Member Function Documentation
void anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction () override
References BORDER_MARGIN, AccordionPanel::CompleteConstruction(), ClientUI::CtrlColor(), AccordionPanel::ExpandCollapseSignal, CombatLogWnd::Impl::HandleWndChanged(), log, AccordionPanel::m_expand_button, AccordionPanel::SetBorderMargin(), AccordionPanel::SetCollapsed(), AccordionPanel::SetInteriorColor(), title, and ToggleExpansion().
void anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::ToggleExpansion () private
toggles panel expanded or collapsed
References event, AccordionPanel::IsCollapsed(), log, CombatLogWnd::Impl::PopulateWithFlatLogs(), AccordionPanel::SetCollapsed(), and viewing_empire_id.
Referenced by CompleteConstruction().
Member Data Documentation
const unsigned int anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::BORDER_MARGIN = 5 static private
Referenced by CompleteConstruction().
std::vector<GG::Wnd *> anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::details private
ConstCombatEventPtr anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::event private
Referenced by ToggleExpansion().
CombatLogWnd::Impl& anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::log private
Referenced by CompleteConstruction(), and ToggleExpansion().
LinkText* anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::title private
Referenced by CompleteConstruction().
int anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::viewing_empire_id private
Referenced by ToggleExpansion().
The documentation for this class was generated from the following file:
CombatLogWnd.cpp