FreeOrion: SaveFileColumn Class Reference
SaveFileColumn Class Reference
Describes how a column should be set up in the dialog.
Public Member Functions
bool Fixed () const
GG::X FixedWidth () const
const std::string & Name () const
double Stretch () const
Static Public Member Functions
static std::shared_ptr< GG::Control > CellForColumn (const SaveFileColumn &column, const FullPreview &full, GG::X max_width)
static std::shared_ptr< std::vector< SaveFileColumn > > GetColumns (GG::X max_width)
static std::shared_ptr< GG::Control > TitleForColumn (const SaveFileColumn &column)
Private Member Functions
SaveFileColumn (std::string name, std::string wide_as, GG::X max_width)
Creates a fixed width column.
SaveFileColumn (std::string name, double stretch, GG::X max_width)
Creates a stretchy column.
std::string Title () const
Static Private Member Functions
static GG::X ComputeFixedWidth (const std::string &title, const std::string &wide_as, GG::X max_width)
static SaveFileColumn GetColumn (const std::string &name, GG::X max_width)
Private Attributes
bool m_fixed
If true, column width is fixed to be the width of m_wide_as under the current font.
GG::X m_fixed_width
The wideset fixed width from wide_as or the title.
std::string m_name
The identifier of what data to show. Must be valid.
double m_stretch
The stretch of the column.
std::string m_wide_as
The string to be used in determining the width of the column.
Detailed Description
Describes how a column should be set up in the dialog.
Constructor & Destructor Documentation
SaveFileColumn() [1/2]
SaveFileColumn::SaveFileColumn (std::string name, std::string wide_as, GG::X max_width) inline private
Creates a fixed width column.
SaveFileColumn() [2/2]
SaveFileColumn::SaveFileColumn (std::string name, double stretch, GG::X max_width) inline private
Creates a stretchy column.
Member Function Documentation
CellForColumn()
static std::shared_ptr<GG::Control> SaveFileColumn::CellForColumn (const SaveFileColumn & column, const FullPreview & full, GG::X max_width) inline static
References ColumnInPreview(), anonymous_namespace{SaveFileDialog.cpp}::CreateResizingText(), FixedWidth(), ClientUI::GetFont(), m_fixed, m_name, SaveGamePreviewData::main_player_empire_colour, FullPreview::preview, and ClientUI::TextColor().
Referenced by SaveFileFileRow::Init().
ComputeFixedWidth()
static GG::X SaveFileColumn::ComputeFixedWidth (const std::string & title, const std::string & wide_as, GG::X max_width) inline static private
References ClientUI::GetFont().
Fixed()
bool SaveFileColumn::Fixed () const inline
FixedWidth()
GG::X SaveFileColumn::FixedWidth () const inline
Referenced by SaveFileRow::AdjustColumns(), CellForColumn(), and SaveFileListBox::Init().
GetColumn()
static SaveFileColumn SaveFileColumn::GetColumn (const std::string & name, GG::X max_width) inline static private
References OptionsDB::Get(), GetOptionsDB(), and OptionsDB::OptionExists().
GetColumns()
static std::shared_ptr<std::vector<SaveFileColumn> > SaveFileColumn::GetColumns (GG::X max_width) inline static
References anonymous_namespace{SaveFileDialog.cpp}::VALID_PREVIEW_COLUMN_COUNT.
Referenced by SaveFileListBox::Init().
Name()
const std::string& SaveFileColumn::Name () const inline
Stretch()
double SaveFileColumn::Stretch () const inline
Referenced by SaveFileRow::AdjustColumns(), and SaveFileListBox::Init().
Title()
std::string SaveFileColumn::Title () const inline private
References ErrorLogger, and UserString().
Referenced by TitleForColumn().
TitleForColumn()
static std::shared_ptr<GG::Control> SaveFileColumn::TitleForColumn (const SaveFileColumn & column) inline static
References ClientUI::GetFont(), and Title().
Referenced by SaveFileHeaderRow::CompleteConstruction().
Member Data Documentation
m_fixed
bool SaveFileColumn::m_fixed private
If true, column width is fixed to be the width of m_wide_as under the current font.
If false, column stretches with factor m_stretch
Referenced by CellForColumn().
m_fixed_width
GG::X SaveFileColumn::m_fixed_width private
The wideset fixed width from wide_as or the title.
m_name
std::string SaveFileColumn::m_name private
The identifier of what data to show. Must be valid.
Referenced by CellForColumn().
m_stretch
double SaveFileColumn::m_stretch private
The stretch of the column.
m_wide_as
std::string SaveFileColumn::m_wide_as private
The string to be used in determining the width of the column.
The documentation for this class was generated from the following file:
SaveFileDialog.cpp