FreeOrion: IApp Class Reference
IApp Class Reference abstract
#include <AppInterface.h>
Classes
class NormalExitException
Public Member Functions
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
virtual int CurrentTurn () const =0
Returns the current game turn.
virtual int EffectsProcessingThreads () const =0
virtual std::shared_ptr< UniverseObject > EmpireKnownObject (int object_id, int empire_id)=0
virtual ObjectMap & EmpireKnownObjects (int empire_id)=0
Accessor for known objects of specified empire.
virtual EmpireManager & Empires ()=0
Returns the set of known Empires for this application.
virtual Empire * GetEmpire (int id)=0
virtual Networking::ClientType GetEmpireClientType (int empire_id) const =0
Returns the networking client type for the given empire_id.
virtual const GalaxySetupData & GetGalaxySetupData () const =0
Returns the galaxy setup data used for the current game.
virtual Networking::ClientType GetPlayerClientType (int player_id) const =0
Returns the networking client type for the given player_id.
virtual SupplyManager & GetSupplyManager ()=0
virtual Universe & GetUniverse ()=0
Returns the Universe known to this application.
virtual std::shared_ptr< UniverseObject > GetUniverseObject (int object_id)=0
virtual std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object)=0
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
virtual void StartBackgroundParsing ()
Start parsing universe object types on a separate thread.
Static Public Member Functions
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Protected Member Functions
IApp ()
Static Protected Attributes
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Constructor & Destructor Documentation
IApp() [1/3]
IApp::IApp () protected
References s_app.
IApp() [2/3]
IApp::IApp (const IApp &) delete
IApp() [3/3]
IApp::IApp (IApp &&) delete
~IApp()
IApp::~IApp () virtual
References s_app.
Member Function Documentation
CurrentTurn()
virtual int IApp::CurrentTurn () const pure virtual
Returns the current game turn.
Returns
The number representing the current game turn.
Implemented in ServerApp, and ClientApp.
Referenced by CurrentTurn().
EffectsProcessingThreads()
virtual int IApp::EffectsProcessingThreads () const pure virtual
Implemented in ServerApp, HumanClientApp, and AIClientApp.
Referenced by EffectsProcessingThreads().
EmpireKnownObject()
virtual std::shared_ptr<UniverseObject> IApp::EmpireKnownObject (int object_id, int empire_id) pure virtual
Implemented in ClientApp, and ServerApp.
EmpireKnownObjects()
virtual ObjectMap& IApp::EmpireKnownObjects (int empire_id) pure virtual
Accessor for known objects of specified empire.
Implemented in ClientApp, and ServerApp.
Referenced by EmpireKnownObjects().
Empires()
virtual EmpireManager& IApp::Empires () pure virtual
Returns the set of known Empires for this application.
Implemented in ClientApp, and ServerApp.
Referenced by Empires().
GetApp()
IApp * IApp::GetApp () static
Returns a IApp pointer to the singleton instance of the app.
References s_app.
Referenced by CurrentTurn(), EffectsProcessingThreads(), EmpireKnownObjects(), Empires(), GetEmpire(), GetEmpireClientType(), GetGalaxySetupData(), GetPathfinder(), GetPlayerClientType(), GetSupplyManager(), GetUniverse(), GetVisibleObjectName(), and Objects().
GetEmpire()
virtual Empire* IApp::GetEmpire (int id) pure virtual
Implemented in ClientApp, and ServerApp.
Referenced by GetEmpire().
GetEmpireClientType()
virtual Networking::ClientType IApp::GetEmpireClientType (int empire_id) const pure virtual
Returns the networking client type for the given empire_id.
Implemented in ClientApp, and ServerApp.
Referenced by GetEmpireClientType().
GetGalaxySetupData()
virtual const GalaxySetupData& IApp::GetGalaxySetupData () const pure virtual
Returns the galaxy setup data used for the current game.
Implemented in ClientApp, and ServerApp.
Referenced by GetGalaxySetupData().
GetPlayerClientType()
virtual Networking::ClientType IApp::GetPlayerClientType (int player_id) const pure virtual
Returns the networking client type for the given player_id.
Implemented in ClientApp, and ServerApp.
Referenced by GetPlayerClientType().
GetSupplyManager()
virtual SupplyManager& IApp::GetSupplyManager () pure virtual
Implemented in ClientApp, and ServerApp.
Referenced by GetSupplyManager().
GetUniverse()
virtual Universe& IApp::GetUniverse () pure virtual
Returns the Universe known to this application.
Returns
A constant reference to the single Universe instance representing the known universe of this application.
Implemented in ClientApp, and ServerApp.
Referenced by GetPathfinder(), and GetUniverse().
GetUniverseObject()
virtual std::shared_ptr<UniverseObject> IApp::GetUniverseObject (int object_id) pure virtual
Implemented in ClientApp, and ServerApp.
GetVisibleObjectName()
virtual std::string IApp::GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) pure virtual
Implemented in ClientApp, and ServerApp.
Referenced by GetVisibleObjectName().
MAX_AI_PLAYERS()
int IApp::MAX_AI_PLAYERS () static
Maximum number of AIs.
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption(), and GalaxySetupWnd::CompleteConstruction().
operator=() [1/2]
const IApp& IApp::operator= (const IApp &) delete
operator=() [2/2]
IApp& IApp::operator= (IApp &&) delete
StartBackgroundParsing()
void IApp::StartBackgroundParsing () virtual
Start parsing universe object types on a separate thread.
Reimplemented in ServerApp.
References GameRules::Add(), parse::buildings(), parse::encyclopedia_articles(), ErrorLogger, parse::fields(), parse::game_rules(), GetBuildingTypeManager(), GetEncyclopedia(), GetFieldTypeManager(), GetGameRules(), GetHullTypeManager(), GetPredefinedShipDesignManager(), GetResourceDir(), GetShipPartManager(), GetSpecialsManager(), GetSpeciesManager(), GetTechManager(), InitEmpireColors(), Encyclopedia::SetArticles(), BuildingTypeManager::SetBuildingTypes(), FieldTypeManager::SetFieldTypes(), HullTypeManager::SetHullTypes(), PredefinedShipDesignManager::SetMonsterDesignTypes(), PredefinedShipDesignManager::SetShipDesignTypes(), ShipPartManager::SetShipParts(), SpecialsManager::SetSpecialsTypes(), SpeciesManager::SetSpeciesTypes(), TechManager::SetTechs(), parse::ship_designs(), parse::ship_hulls(), parse::ship_parts(), parse::specials(), parse::species(), and Pending::StartParsing().
Referenced by HumanClientApp::HandleResoureDirChange(), HumanClientApp::HumanClientApp(), AIClientApp::Run(), and ServerApp::StartBackgroundParsing().
Member Data Documentation
s_app
IApp * IApp::s_app = nullptr static protected
a IApp pointer to the singleton instance of the app
Referenced by GetApp(), ServerApp::GetApp(), AIClientApp::GetApp(), ClientApp::GetApp(), IApp(), and ~IApp().
The documentation for this class was generated from the following files:
AppInterface.h
AppInterface.cpp