FreeOrion: ClientApp Class Reference
ClientApp Class Reference
Abstract base class for the application framework classes.
#include <ClientApp.h>
Public Member Functions
ClientApp (const ClientApp &)=delete
ClientApp (ClientApp &&)=delete
~ClientApp () override=default
int CurrentTurn () const override
Return the current game turn.
int EmpireID () const
Return the empire identifier of the empire this client controls.
std::shared_ptr< UniverseObject > EmpireKnownObject (int object_id, int empire_id) override
Return the UniverseObject object_id if known by empire_id.
ObjectMap & EmpireKnownObjects (int empire_id) override
Return all Objects known to empire_id.
int EmpirePlayerID (int empire_id) const
Return the player identfier of the player controlling the empire empire_id.
Networking::ClientType GetClientType () const
Return The Networking::ClientType of this client.
Empire * GetEmpire (int empire_id) override
Return the Empire identified by empire_id.
Networking::ClientType GetEmpireClientType (int empire_id) const override
Return the Networking::ClientType of the empire empire_id.
Networking::ClientType GetPlayerClientType (int player_id) const override
Return the Networking::ClientType of the player player_id.
SupplyManager & GetSupplyManager () override
std::shared_ptr< UniverseObject > GetUniverseObject (int object_id) override
Return the UniverseObject associated with object_id.
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override
Return the for this client visible name of object.
virtual void HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id)
Handle server acknowledgement of receipt of orders and clear the orders.
virtual void HandleTurnUpdate ()
Handle the turn update.
const ClientApp & operator= (const ClientApp &)=delete
ClientApp & operator= (ClientApp &&)=delete
int PlayerID () const
Return the player identifier of this client.
void SendPartialOrders ()
Send turn orders updates to server without starting new turn.
void SetCurrentTurn (int turn)
Set the current game turn of this client to turn.
void SetEmpireID (int empire_id)
Set the identifier of the Empire controlled by this client to empire_id.
void SetEmpireStatus (int empire_id, Message::PlayerStatus status)
Set the Message::PlayerStatus status for empire_id.
virtual void StartTurn (const SaveGameUIData &ui_data)
Send the OrderSet and UI data to the server and start a new turn.
virtual void StartTurn (const std::string &save_state_string)
Send the OrderSet and AI state to the server and start a new turn.
bool VerifyCheckSum (const Message &msg)
Compare content checksum from server with client content checksum.
std::map< int, PlayerInfo > & Players ()
Return the players in game as PlayerInfo map.
const std::map< int, PlayerInfo > & Players () const
Return the players in game as PlayerInfo map.
std::map< int, Message::PlayerStatus > & EmpireStatus ()
Return the empire statuses in game.
const std::map< int, Message::PlayerStatus > & EmpireStatus () const
Return the empire statuses in game.
Universe & GetUniverse () override
Return the Universe known to this client.
const Universe & GetUniverse () const
Return the Universe known to this client.
GalaxySetupData & GetGalaxySetupData ()
Return the GalaxySetupData of this game.
const GalaxySetupData & GetGalaxySetupData () const override
Return the GalaxySetupData of this game.
OrderSet & Orders ()
Return the OrderSet of this client.
const OrderSet & Orders () const
Return the OrderSet of this client.
ClientNetworking & Networking ()
Return the networking object of this clients player.
const ClientNetworking & Networking () const
Return the networking object of this clients player.
EmpireManager & Empires () override
Return the set of known Empire s for this client.
const EmpireManager & Empires () const
Return the set of known Empire s for this client.
Public Member Functions inherited from IApp
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
virtual int EffectsProcessingThreads () const =0
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
virtual void StartBackgroundParsing ()
Start parsing universe object types on a separate thread.
Static Public Member Functions
static ClientApp * GetApp ()
Return the singleton instance of this Application.
Static Public Member Functions inherited from IApp
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Protected Member Functions
ClientApp ()
Protected Member Functions inherited from IApp
IApp ()
Protected Attributes
int m_current_turn
int m_empire_id
std::map< int, Message::PlayerStatus > m_empire_status
Indexed by empire id, contains the last known PlayerStatus for each empire.
EmpireManager m_empires
GalaxySetupData m_galaxy_setup_data
std::shared_ptr< ClientNetworking > m_networking
OrderSet m_orders
std::map< int, PlayerInfo > m_player_info
Indexed by player id, contains info about all players in the game.
SupplyManager m_supply_manager
Universe m_universe
Additional Inherited Members
Static Protected Attributes inherited from IApp
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Detailed Description
Abstract base class for the application framework classes.
The static functions are designed to give both types of client (which are very different) a unified interface. This allows code in either type of client app to handle Messages and gain access to the data structures common to both apps, without worrying about which type of app the code is being run in.
Constructor & Destructor Documentation
ClientApp() [1/3]
ClientApp::ClientApp () protected
ClientApp() [2/3]
ClientApp::ClientApp (const ClientApp &) delete
ClientApp() [3/3]
ClientApp::ClientApp (ClientApp &&) delete
~ClientApp()
ClientApp::~ClientApp () override default
Member Function Documentation
CurrentTurn()
int ClientApp::CurrentTurn () const override virtual
Return the current game turn.
Returns
The number representing the current game turn.
Implements IApp.
References m_current_turn.
Referenced by HumanClientApp::Autosave(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), and HumanClientApp::StartTurn().
EmpireID()
int ClientApp::EmpireID () const
Return the empire identifier of the empire this client controls.
Returns
An empire identifier.
References m_empire_id.
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), ProductionWnd::AddBuildToQueueSlot(), DesignWnd::MainPanel::AddDesign(), ResearchWnd::AddTechsToQueueSlot(), TechTreeWnd::AddTechToResearchQueue(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), HumanClientApp::Autosave(), BuildDesignatorWnd::CenterOnBuild(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), FleetButton::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), MapWnd::DeferredRefreshFleetButtons(), ResearchWnd::DeleteQueueItem(), ProductionWnd::DeleteQueueItem(), DesignWnd::MainPanel::DesignChanged(), MapWnd::DispatchFleetsExploring(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability(), FleetWnd::DoLayout(), FleetDataPanel::DropsAcceptable(), AIInterface::EmpireID(), MapWnd::EnableOrderIssuing(), SidePanel::PlanetPanel::EnableOrderIssuing(), FleetButton::FleetButton(), MapWnd::FleetButtonRightClicked(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetWnd::FleetRightClicked(), MapWnd::ForgetObject(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), DesignWnd::PartPalette::HandlePartTypeRightClicked(), FleetDataPanel::Init(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitTurnRendering(), MapWnd::InitVisibilityRadiiRenderingBuffers(), AIInterface::IssueAllowStockpileProductionOrder(), AIInterface::IssueChangeProductionQuantityOrder(), AIInterface::IssueCreateShipDesignOrder(), AIInterface::IssueDequeueProductionOrder(), AIInterface::IssueDequeueTechOrder(), AIInterface::IssueEnqueueBuildingProductionOrder(), AIInterface::IssueEnqueueShipProductionOrder(), AIInterface::IssueEnqueueTechOrder(), AIInterface::IssuePauseProductionOrder(), AIInterface::IssueRequeueProductionOrder(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), SystemIcon::MouseEnter(), ObjectListWnd::ObjectRightClicked(), ObjectListBox::ObjectShown(), OwnerColoredSystemName::OwnerColoredSystemName(), ParticipantBar::ParticipantBar(), SidePanel::PlanetSelectable(), PlayerListWnd::PlayerRightClicked(), MapWnd::PlotFleetMovement(), PartsListBox::Populate(), ProductionWnd::QueueItemDuped(), ResearchWnd::QueueItemMoved(), ProductionWnd::QueueItemMoved(), ResearchWnd::QueueItemPaused(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), ShipsListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshFleetResourceIndicator(), SidePanel::RefreshImpl(), DesignWnd::MainPanel::RefreshIncompleteDesign(), BuildingIndicator::Render(), MapWnd::RenderFields(), MapWnd::RenderSystems(), DesignWnd::MainPanel::ReplaceDesign(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), DesignWnd::BaseSelector::Reset(), anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane(), BuildDesignatorWnd::SetBuild(), SidePanel::PlanetPanel::SetFocus(), CombatLogWnd::Impl::SetLog(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), HumanClientApp::StartGame(), HumanClientApp::StartTurn(), FleetWnd::TitleText(), FleetDataPanel::ToggleAggression(), BuildingsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), AIInterface::UpdateProductionQueue(), AIInterface::UpdateResearchQueue(), AIInterface::UpdateResourcePools(), and MapWnd::ZoomToSystemWithWastedPP().
EmpireKnownObject()
std::shared_ptr< UniverseObject > ClientApp::EmpireKnownObject (int object_id, int empire_id) override virtual
Return the UniverseObject object_id if known by empire_id.
Parameters
object_id An UniverseObject identifier.
empire_id An empire identifier.
Returns
A pointer to the UniverseObject, that is identified by object_id and known by the Empire identified by empire_id. If there is no such object or if that object is not known to the empire a nullptr is returned.
Implements IApp.
References EmpireKnownObjects(), and ObjectMap::Object().
EmpireKnownObjects()
ObjectMap & ClientApp::EmpireKnownObjects (int empire_id) override virtual
Return all Objects known to empire_id.
Parameters
empire_id An empire identifier.
Returns
A map containing all Objects known to the Empire identified by empire_id. If there is no Empire an empty map is returned.
Implements IApp.
References ALL_EMPIRES, Universe::EmpireKnownObjects(), m_empire_id, m_universe, and Universe::Objects().
Referenced by EmpireKnownObject().
EmpirePlayerID()
int ClientApp::EmpirePlayerID (int empire_id) const
Return the player identfier of the player controlling the empire empire_id.
Parameters
empire_id An empire identifier representing an empire.
Returns
The player identifier of the client controlling the empire.
References Networking::INVALID_PLAYER_ID, and m_player_info.
Referenced by AIInterface::EmpirePlayerID(), GetEmpireClientType(), PlayerListWnd::Refresh(), and AIInterface::SendDiplomaticMessage().
Empires() [1/2]
EmpireManager & ClientApp::Empires () override virtual
Return the set of known Empire s for this client.
Returns
The EmpireManager instance in charge of maintaining the Empire object instances.
Implements IApp.
References m_empires.
Referenced by HumanClientApp::CanSaveNow().
Empires() [2/2]
const EmpireManager & ClientApp::Empires () const
Return the set of known Empire s for this client.
Returns
The EmpireManager instance in charge of maintaining the Empire object instances.
References m_empires.
EmpireStatus() [1/2]
std::map< int, Message::PlayerStatus > & ClientApp::EmpireStatus ()
Return the empire statuses in game.
Returns
Return a map containing PlayerStatus instances as value and their empire identifier as key.
References m_empire_status.
EmpireStatus() [2/2]
const std::map< int, Message::PlayerStatus > & ClientApp::EmpireStatus () const
Return the empire statuses in game.
Returns
Return a map containing PlayerStatus instances as value and their empire identifier as key.
References m_empire_status.
GetApp()
ClientApp * ClientApp::GetApp () static
Return the singleton instance of this Application.
Returns
A pointer to the single ClientApp instance of this client.
References IApp::s_app.
Referenced by DesignWnd::MainPanel::AddDesign(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), HandleTurnUpdate(), MultiPlayerLobbyWnd::HasAuthRole(), anonymous_namespace{AIWrapper.cpp}::Issue(), AIInterface::IssueCreateShipDesignOrder(), anonymous_namespace{AIWrapper.cpp}::IssueNewFleetOrder(), ParticipantBar::ParticipantBar(), anonymous_namespace{SidePanel.cpp}::PendingBombardOrders(), anonymous_namespace{SidePanel.cpp}::PendingColonizationOrders(), anonymous_namespace{SidePanel.cpp}::PendingInvadeOrders(), anonymous_namespace{BuildingsPanel.cpp}::PendingScrapOrders(), anonymous_namespace{FleetWnd.cpp}::PendingScrapOrders(), PlayerListWnd::PlayerRightClicked(), PlayerListWnd::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), DesignWnd::MainPanel::RefreshIncompleteDesign(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeSelector(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update().
GetClientType()
Networking::ClientType ClientApp::GetClientType () const
Return The Networking::ClientType of this client.
Returns
the networking client type of this players client.
References GetPlayerClientType(), and m_networking.
Referenced by anonymous_namespace{BuildingsPanel.cpp}::ClientPlayerIsModerator(), anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{SidePanel.cpp}::ClientPlayerIsModerator(), MapWnd::EnableOrderIssuing(), MapWnd::InitTurn(), ObjectListWnd::ObjectRightClicked(), and PlayerListWnd::PlayerRightClicked().
GetEmpire()
Empire * ClientApp::GetEmpire (int empire_id) override virtual
Return the Empire identified by empire_id.
Parameters
empire_id An empire identifier.
Returns
A pointer to the Empire instance represented by empire_id. If there is no Empire with this empire_id or if the Empire is not yet known to this client a nullptr is returned.
Implements IApp.
References EmpireManager::GetEmpire(), and m_empires.
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings(), AIInterface::GetEmpire(), AIClientApp::HandleMessage(), AIInterface::IssueAllowStockpileProductionOrder(), AIInterface::IssueChangeProductionQuantityOrder(), AIInterface::IssueDequeueProductionOrder(), AIInterface::IssueEnqueueBuildingProductionOrder(), AIInterface::IssueEnqueueShipProductionOrder(), AIInterface::IssuePauseProductionOrder(), AIInterface::IssueRequeueProductionOrder(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), and HumanClientApp::StartTurn().
GetEmpireClientType()
Networking::ClientType ClientApp::GetEmpireClientType (int empire_id) const override virtual
Return the Networking::ClientType of the empire empire_id.
Parameters
empire_id An empire identifier.
Returns
the networking client type of the empire represented by empire_id parameter.
Implements IApp.
References EmpirePlayerID(), and GetPlayerClientType().
Referenced by HumanClientApp::CanSaveNow().
GetGalaxySetupData() [1/2]
GalaxySetupData & ClientApp::GetGalaxySetupData ()
Return the GalaxySetupData of this game.
Returns
A reference to the GalaxySetupData used in this game session.
References m_galaxy_setup_data.
Referenced by AIInterface::GetGalaxySetupData(), AIClientApp::HandleMessage(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag().
GetGalaxySetupData() [2/2]
const GalaxySetupData & ClientApp::GetGalaxySetupData () const override virtual
Return the GalaxySetupData of this game.
Returns
A reference to the GalaxySetupData used in this game session.
Implements IApp.
References m_galaxy_setup_data.
GetPlayerClientType()
Networking::ClientType ClientApp::GetPlayerClientType (int player_id) const override virtual
Return the Networking::ClientType of the player player_id.
Parameters
player_id An client identifier.
Returns
the networking client type of the player represented by player_id parameter.
Implements IApp.
References Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, and m_player_info.
Referenced by GetClientType(), GetEmpireClientType(), and AIInterface::PlayerIsAI().
GetSupplyManager()
SupplyManager & ClientApp::GetSupplyManager () override virtual
Implements IApp.
References m_supply_manager.
Referenced by AIClientApp::HandleMessage().
GetUniverse() [1/2]
Universe & ClientApp::GetUniverse () override virtual
Return the Universe known to this client.
Returns
A reference to the single Universe instance representing the known universe of this client.
Implements IApp.
References m_universe.
Referenced by GetUniverseObject(), AIClientApp::HandleMessage(), AIInterface::InitMeterEstimatesAndDiscrepancies(), and AIInterface::UpdateMeterEstimates().
GetUniverse() [2/2]
const Universe & ClientApp::GetUniverse () const
Return the Universe known to this client.
Returns
A reference to the single Universe instance representing the known universe of this client.
References m_universe.
GetUniverseObject()
std::shared_ptr< UniverseObject > ClientApp::GetUniverseObject (int object_id) override virtual
Return the UniverseObject associated with object_id.
Parameters
object_id An object identifier
Returns
A pointer to the UniverseObject associated with object_id. When there is no matching object or the client does not know of the object existence the pointer may be nullptr.
Implements IApp.
References GetUniverse(), ObjectMap::Object(), and Universe::Objects().
GetVisibleObjectName()
std::string ClientApp::GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override virtual
Return the for this client visible name of object.
Parameters
object The object to obtain the name from.
Returns
The name of the object. Depdending on Visibility it may not match with the actual object name.
Implements IApp.
References ErrorLogger, and m_empire_id.
HandleTurnPhaseUpdate()
void ClientApp::HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id) virtual
Handle server acknowledgement of receipt of orders and clear the orders.
Reimplemented in HumanClientApp.
Referenced by AIClientApp::HandleMessage(), and HumanClientApp::HandleTurnPhaseUpdate().
HandleTurnUpdate()
virtual void ClientApp::HandleTurnUpdate () inline virtual
Handle the turn update.
Reimplemented in HumanClientApp.
References GetApp(), SetEmpireStatus(), and VerifyCheckSum().
Networking() [1/2]
ClientNetworking & ClientApp::Networking ()
Return the networking object of this clients player.
Returns
A reference to the ClientNetworking object of this client.
References m_networking.
Referenced by HumanClientApp::Autosave(), MapWnd::BuildingRightClicked(), HumanClientApp::CanSaveNow(), AIClientApp::ConnectToServer(), MapWnd::FieldRightClicked(), MapWnd::FleetsRightClicked(), AIClientApp::HandleMessage(), AIClientApp::HandlePythonAICrash(), HumanClientApp::HandleSystemEvents(), MultiPlayerLobbyWnd::HasAuthRole(), anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction(), ObjectListWnd::ObjectRightClicked(), PasswordEnterWnd::OkClicked(), MapWnd::PlanetRightClicked(), ServerConnectWnd::PopulateServerList(), MapWnd::RClick(), AIClientApp::Run(), anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), AIInterface::SendDiplomaticMessage(), AIInterface::SendPlayerChatMessage(), MultiPlayerLobbyWnd::SendUpdate(), MapWnd::ShipsRightClicked(), MapWnd::SystemRightClicked(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeSelector(), and AIClientApp::~AIClientApp().
Networking() [2/2]
const ClientNetworking & ClientApp::Networking () const
Return the networking object of this clients player.
Returns
A reference to the ClientNetworking object of this client.
References m_networking.
operator=() [1/2]
const ClientApp& ClientApp::operator= (const ClientApp &) delete
operator=() [2/2]
ClientApp& ClientApp::operator= (ClientApp &&) delete
Orders() [1/2]
OrderSet & ClientApp::Orders ()
Return the OrderSet of this client.
Returns
A reference to the OrderSet of this client.
References m_orders.
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), ProductionWnd::AddBuildToQueueSlot(), DesignWnd::MainPanel::AddDesign(), anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), ResearchWnd::AddTechsToQueueSlot(), CompletedDesignsListBox::BaseRightClicked(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), ResearchWnd::DeleteQueueItem(), ProductionWnd::DeleteQueueItem(), FleetWnd::FleetRightClicked(), MapWnd::ForgetObject(), AIClientApp::HandleMessage(), MapWnd::InitTurn(), AIInterface::IssueAllowStockpileProductionOrder(), AIInterface::IssueChangeProductionQuantityOrder(), AIInterface::IssueCreateShipDesignOrder(), AIInterface::IssueDequeueProductionOrder(), AIInterface::IssueDequeueTechOrder(), AIInterface::IssuedOrders(), AIInterface::IssueEnqueueBuildingProductionOrder(), AIInterface::IssueEnqueueShipProductionOrder(), AIInterface::IssueEnqueueTechOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetExploreOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetResupplyOrder(), AIInterface::IssuePauseProductionOrder(), AIInterface::IssueRequeueProductionOrder(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), anonymous_namespace{SidePanel.cpp}::PendingBombardOrders(), anonymous_namespace{SidePanel.cpp}::PendingColonizationOrders(), anonymous_namespace{SidePanel.cpp}::PendingInvadeOrders(), anonymous_namespace{BuildingsPanel.cpp}::PendingScrapOrders(), anonymous_namespace{FleetWnd.cpp}::PendingScrapOrders(), MapWnd::PlotFleetMovement(), ProductionWnd::QueueItemDuped(), ResearchWnd::QueueItemMoved(), ProductionWnd::QueueItemMoved(), ResearchWnd::QueueItemPaused(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), DesignWnd::MainPanel::ReplaceDesign(), SidePanel::PlanetPanel::SetFocus(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), FleetDetailPanel::ShipRightClicked(), and FleetDataPanel::ToggleAggression().
Orders() [2/2]
const OrderSet & ClientApp::Orders () const
Return the OrderSet of this client.
Returns
A reference to the OrderSet of this client.
References m_orders.
PlayerID()
int ClientApp::PlayerID () const
Return the player identifier of this client.
Returns
The player identifier of this client as assigned by the server.
References m_networking.
Referenced by HumanClientApp::Autosave(), HumanClientApp::CanSaveNow(), AIClientApp::HandleMessage(), AIClientApp::HandlePythonAICrash(), AIInterface::PlayerID(), PlayerListWnd::PlayerRightClicked(), MultiPlayerLobbyWnd::PopulatePlayerList(), MultiPlayerLobbyWnd::ReadyClicked(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), AIInterface::SendDiplomaticMessage(), and HumanClientApp::SendLoggingConfigToServer().
Players() [1/2]
std::map< int, PlayerInfo > & ClientApp::Players ()
Return the players in game as PlayerInfo map.
Returns
Return a map containing PlayerInfo instances as value and their player identifier as key.
References m_player_info.
Referenced by AIInterface::PlayerIsHost(), AIInterface::PlayerName(), PlayerListWnd::Refresh(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update().
Players() [2/2]
const std::map< int, PlayerInfo > & ClientApp::Players () const
Return the players in game as PlayerInfo map.
Returns
Return a map containing PlayerInfo instances as value and their player identifier as key.
References m_player_info.
SendPartialOrders()
void ClientApp::SendPartialOrders ()
Send turn orders updates to server without starting new turn.
References OrderSet::ExtractChanges(), m_networking, m_orders, and TurnPartialOrdersMessage().
Referenced by anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), InGameMenu::Resign(), MapWnd::RestoreSidePanel(), InGameMenu::Save(), and SidePanel::PlanetPanelContainer::SelectPlanet().
SetCurrentTurn()
void ClientApp::SetCurrentTurn (int turn)
Set the current game turn of this client to turn.
Parameters
turn The new turn number of this client.
References m_current_turn.
SetEmpireID()
void ClientApp::SetEmpireID (int empire_id)
Set the identifier of the Empire controlled by this client to empire_id.
Parameters
empire_id The new Empire identifier.
References m_empire_id.
Referenced by HumanClientApp::FreeServer(), HumanClientApp::LoadSinglePlayerGame(), and HumanClientApp::ResetClientData().
SetEmpireStatus()
void ClientApp::SetEmpireStatus (int empire_id, Message::PlayerStatus status)
Set the Message::PlayerStatus status for empire_id.
Parameters
player_id A empire identifier.
status The new Message::PlayerStatus of the player identified by empire_id.
References ALL_EMPIRES, and m_empire_status.
Referenced by HandleTurnUpdate().
StartTurn() [1/2]
void ClientApp::StartTurn (const SaveGameUIData & ui_data) virtual
Send the OrderSet and UI data to the server and start a new turn.
Reimplemented in HumanClientApp.
References m_networking, m_orders, and TurnOrdersMessage().
Referenced by AIInterface::DoneTurn(), and HumanClientApp::StartTurn().
StartTurn() [2/2]
void ClientApp::StartTurn (const std::string & save_state_string) virtual
Send the OrderSet and AI state to the server and start a new turn.
References m_networking, m_orders, and TurnOrdersMessage().
VerifyCheckSum()
bool ClientApp::VerifyCheckSum (const Message & msg)
Compare content checksum from server with client content checksum.
Returns
true if verify successed.
References CheckSumContent(), ExtractContentCheckSumMessageData(), InfoLogger, and WarnLogger.
Referenced by AIClientApp::HandleMessage(), and HandleTurnUpdate().
Member Data Documentation
m_current_turn
int ClientApp::m_current_turn protected
Referenced by CurrentTurn(), AIClientApp::HandleMessage(), and SetCurrentTurn().
m_empire_id
int ClientApp::m_empire_id protected
Referenced by EmpireID(), EmpireKnownObjects(), GetVisibleObjectName(), AIClientApp::HandleMessage(), and SetEmpireID().
m_empire_status
std::map<int, Message::PlayerStatus> ClientApp::m_empire_status protected
Indexed by empire id, contains the last known PlayerStatus for each empire.
Referenced by HumanClientApp::CanSaveNow(), EmpireStatus(), AIClientApp::HandleMessage(), and SetEmpireStatus().
m_empires
EmpireManager ClientApp::m_empires protected
Referenced by Empires(), GetEmpire(), AIClientApp::HandleMessage(), and HumanClientApp::ResetClientData().
m_galaxy_setup_data
GalaxySetupData ClientApp::m_galaxy_setup_data protected
Referenced by GetGalaxySetupData(), and AIClientApp::HandleMessage().
m_networking
std::shared_ptr<ClientNetworking> ClientApp::m_networking protected
Referenced by HumanClientApp::EliminateSelf(), HumanClientApp::FreeServer(), GetClientType(), AIClientApp::HandleMessage(), HumanClientApp::HandleSetAuthRoles(), HumanClientApp::HandleSystemEvents(), HumanClientApp::LoadSinglePlayerGame(), HumanClientApp::MultiPlayerGame(), Networking(), HumanClientApp::NewSinglePlayerGame(), PlayerID(), HumanClientApp::RequestSavePreviews(), HumanClientApp::ResetClientData(), HumanClientApp::SaveGame(), HumanClientApp::SaveGameCompleted(), HumanClientApp::SendLoggingConfigToServer(), SendPartialOrders(), HumanClientApp::StartServer(), StartTurn(), HumanClientApp::UnreadyTurn(), HumanClientApp::UpdateCombatLogManager(), and HumanClientApp::~HumanClientApp().
m_orders
OrderSet ClientApp::m_orders protected
Referenced by AIClientApp::HandleMessage(), Orders(), HumanClientApp::ResetClientData(), SendPartialOrders(), and StartTurn().
m_player_info
std::map<int, PlayerInfo> ClientApp::m_player_info protected
Indexed by player id, contains info about all players in the game.
Referenced by EmpirePlayerID(), GetPlayerClientType(), AIClientApp::HandleMessage(), and Players().
m_supply_manager
SupplyManager ClientApp::m_supply_manager protected
Referenced by GetSupplyManager().
m_universe
Universe ClientApp::m_universe protected
Referenced by EmpireKnownObjects(), GetUniverse(), AIClientApp::HandleMessage(), and HumanClientApp::ResetClientData().
The documentation for this class was generated from the following files:
ClientApp.h
ClientApp.cpp