FreeOrion: ProductionWnd Class Reference
ProductionWnd Class Reference
Contains a BuildDesignatorWnd, some stats on the empire-wide production queue, and the queue itself.
#include <ProductionWnd.h>
Public Member Functions
void CompleteConstruction () override
Structors
ProductionWnd (GG::X w, GG::Y h)
virtual ~ProductionWnd ()
Accessors
int SelectedPlanetID () const
int ShownEmpireID () const
Mutators
bool InWindow (const GG::Pt &pt) const override
Shows building_type in production encyclopedia window.
bool InClient (const GG::Pt &pt) const override
Shows building_type in production encyclopedia window.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Shows building_type in production encyclopedia window.
void Render () override
Shows building_type in production encyclopedia window.
void SetEmpireShown (int empire_id)
Shows building_type in production encyclopedia window.
void Refresh ()
Shows building_type in production encyclopedia window.
void Reset ()
Shows building_type in production encyclopedia window.
void Update ()
Shows building_type in production encyclopedia window.
void ShowBuildingTypeInEncyclopedia (const std::string &building_type)
Shows building_type in production encyclopedia window.
void ShowShipDesignInEncyclopedia (int design_id)
Shows ShipDesign with id design_id in production encyclopedia window.
void ShowPlanetInEncyclopedia (int planet_id)
Shows planet in production encyclopedia window.
void ShowTechInEncyclopedia (const std::string &tech_name)
Shows tech in production encyclopedia window.
void ShowPartTypeInEncyclopedia (const std::string &part_type_name)
Shows ship_part in production encyclopedia window.
void ShowSpeciesInEncyclopedia (const std::string &species_name)
Shows species in production encyclopedia window.
void ShowEmpireInEncyclopedia (int empire_id)
Shows empire in production encyclopedia window.
void ShowSpecialInEncyclopedia (const std::string &special_name)
Shows special in production encyclopedia window.
void ShowFieldTypeInEncyclopedia (const std::string &field_type_name)
Shows field_type in production encyclopedia window.
void ShowPedia ()
Change visibility of production encyclopdia panel.
void HidePedia ()
Shows building_type in production encyclopedia window.
void TogglePedia ()
Shows building_type in production encyclopedia window.
bool PediaVisible ()
Returns true if pedia is visible.
void CenterOnBuild (int queue_idx, bool open=false)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window.
void SelectSystem (int system_id)
Programatically sets this Wnd's selected system.
void SelectPlanet (int planet_id)
Programatically sets this Wnd's selected planet.
void SelectDefaultPlanet ()
Attempts to find a planet to select, and if successful, selects that planet.
void Sanitize ()
Shows building_type in production encyclopedia window.
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via this ProductionWnd.
Public Attributes
boost::signals2::signal< void(int)> PlanetSelectedSignal
emitted when the user changes the selected planet in the production screen
boost::signals2::signal< void(int, int)> RowQuantChangedSignal
boost::signals2::signal< void(int)> SystemSelectedSignal
emitted when the user changes the selected system in the production screen
Private Member Functions
void AddBuildToQueueSlot (const ProductionQueue::ProductionItem &item, int number, int location, int pos)
void ChangeBuildQuantityBlockSlot (int queue_idx, int quantity, int blocksize)
void ChangeBuildQuantitySlot (int queue_idx, int quantity)
void DeleteQueueItem (GG::ListBox::iterator it)
void DoLayout ()
void ProductionQueueChangedSlot ()
void QueueItemClickedSlot (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void QueueItemDoubleClickedSlot (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void QueueItemDuped (GG::ListBox::iterator it)
void QueueItemMoved (const GG::ListBox::iterator &row_it, const GG::ListBox::iterator &original_position_it)
void QueueItemPaused (GG::ListBox::iterator it, bool pause)
void QueueItemRallied (GG::ListBox::iterator it, int object_id)
void QueueItemSplit (GG::ListBox::iterator it)
void QueueItemUseImperialPP (GG::ListBox::iterator it, bool allow)
void UpdateInfoPanel ()
Updates production summary at top left of production screen, and signals that the empire's minerals resource pool has changed (propagates to the mapwnd to update indicator)
void UpdateQueue ()
Clears and repopulates queue list with listitems corresponding to contents of empire's production queue.
Private Attributes
std::shared_ptr< BuildDesignatorWnd > m_build_designator_wnd
boost::signals2::connection m_empire_connection
int m_empire_shown_id
bool m_order_issuing_enabled
std::shared_ptr< ResourceInfoPanel > m_production_info_panel
std::shared_ptr< ProductionQueueWnd > m_queue_wnd
Detailed Description
Contains a BuildDesignatorWnd, some stats on the empire-wide production queue, and the queue itself.
Constructor & Destructor Documentation
ProductionWnd()
ProductionWnd::ProductionWnd (GG::X w, GG::Y h)
~ProductionWnd()
ProductionWnd::~ProductionWnd () virtual
References m_empire_connection.
Member Function Documentation
AddBuildToQueueSlot()
void ProductionWnd::AddBuildToQueueSlot (const ProductionQueue::ProductionItem & item, int number, int location, int pos) private
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), OrderSet::IssueOrder(), m_build_designator_wnd, m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), ProductionQueueOrder::PLACE_IN_QUEUE, and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
CenterOnBuild()
void ProductionWnd::CenterOnBuild (int queue_idx, bool open = false)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window.
If open is true, the location is set as the selected planet.
References m_build_designator_wnd.
ChangeBuildQuantityBlockSlot()
void ProductionWnd::ChangeBuildQuantityBlockSlot (int queue_idx, int quantity, int blocksize) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, ClientApp::Orders(), ProductionQueueOrder::SET_QUANTITY_AND_BLOCK_SIZE, and Empire::UpdateProductionQueue().
Referenced by UpdateQueue().
ChangeBuildQuantitySlot()
void ProductionWnd::ChangeBuildQuantitySlot (int queue_idx, int quantity) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, ClientApp::Orders(), ProductionQueueOrder::SET_QUANTITY, and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
CompleteConstruction()
void ProductionWnd::CompleteConstruction () override
References AddBuildToQueueSlot(), ChangeBuildQuantitySlot(), DeleteQueueItem(), GetOptionsDB(), m_build_designator_wnd, m_production_info_panel, m_queue_wnd, ClientUI::Pts(), QueueItemClickedSlot(), QueueItemDoubleClickedSlot(), QueueItemDuped(), QueueItemMoved(), QueueItemPaused(), QueueItemRallied(), QueueItemSplit(), QueueItemUseImperialPP(), ShowPedia(), SystemSelectedSignal, and UserString().
DeleteQueueItem()
void ProductionWnd::DeleteQueueItem (GG::ListBox::iterator it) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), ProductionQueueOrder::REMOVE_FROM_QUEUE, and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction(), and QueueItemClickedSlot().
DoLayout()
void ProductionWnd::DoLayout () private
References GetOptionsDB(), m_build_designator_wnd, m_production_info_panel, m_queue_wnd, and ClientUI::Pts().
Referenced by SizeMove().
EnableOrderIssuing()
void ProductionWnd::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this ProductionWnd.
References m_order_issuing_enabled, and m_queue_wnd.
HidePedia()
void ProductionWnd::HidePedia ()
Shows building_type in production encyclopedia window.
References m_build_designator_wnd.
InClient()
bool ProductionWnd::InClient (const GG::Pt & pt) const override
Shows building_type in production encyclopedia window.
References m_build_designator_wnd, m_production_info_panel, and m_queue_wnd.
InWindow()
bool ProductionWnd::InWindow (const GG::Pt & pt) const override
Shows building_type in production encyclopedia window.
References m_build_designator_wnd, m_production_info_panel, and m_queue_wnd.
PediaVisible()
bool ProductionWnd::PediaVisible ()
Returns true if pedia is visible.
References m_build_designator_wnd.
ProductionQueueChangedSlot()
void ProductionWnd::ProductionQueueChangedSlot () private
References m_build_designator_wnd, UpdateInfoPanel(), and UpdateQueue().
Referenced by Refresh().
QueueItemClickedSlot()
void ProductionWnd::QueueItemClickedSlot (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References DeleteQueueItem(), m_build_designator_wnd, and m_queue_wnd.
Referenced by CompleteConstruction().
QueueItemDoubleClickedSlot()
void ProductionWnd::QueueItemDoubleClickedSlot (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References m_build_designator_wnd, and m_queue_wnd.
Referenced by CompleteConstruction().
QueueItemDuped()
void ProductionWnd::QueueItemDuped (GG::ListBox::iterator it) private
References ProductionQueueOrder::DUPLICATE_ITEM, ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
QueueItemMoved()
void ProductionWnd::QueueItemMoved (const GG::ListBox::iterator & row_it, const GG::ListBox::iterator & original_position_it) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ProductionQueueOrder::MOVE_ITEM_TO_INDEX, ClientApp::Orders(), and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
QueueItemPaused()
void ProductionWnd::QueueItemPaused (GG::ListBox::iterator it, bool pause) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), ProductionQueueOrder::PAUSE_PRODUCTION, ProductionQueueOrder::RESUME_PRODUCTION, and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
QueueItemRallied()
void ProductionWnd::QueueItemRallied (GG::ListBox::iterator it, int object_id) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), ProductionQueueOrder::SET_RALLY_POINT, SidePanel::SystemID(), and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
QueueItemSplit()
void ProductionWnd::QueueItemSplit (GG::ListBox::iterator it) private
References ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), ProductionQueueOrder::SPLIT_INCOMPLETE, and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
QueueItemUseImperialPP()
void ProductionWnd::QueueItemUseImperialPP (GG::ListBox::iterator it, bool allow) private
References ProductionQueueOrder::ALLOW_STOCKPILE_USE, ProductionQueueOrder::DISALLOW_STOCKPILE_USE, ClientApp::EmpireID(), ProductionQueue::end(), ProductionQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_queue_wnd, ClientApp::Orders(), and Empire::UpdateProductionQueue().
Referenced by CompleteConstruction().
Refresh()
void ProductionWnd::Refresh ()
Shows building_type in production encyclopedia window.
References GetEmpire(), m_build_designator_wnd, m_empire_connection, m_empire_shown_id, ProductionQueueChangedSlot(), UpdateInfoPanel(), and UpdateQueue().
Referenced by Reset(), and SetEmpireShown().
Render()
void ProductionWnd::Render () override
Shows building_type in production encyclopedia window.
Reset()
void ProductionWnd::Reset ()
Shows building_type in production encyclopedia window.
References ALL_EMPIRES, m_empire_shown_id, m_queue_wnd, and Refresh().
Sanitize()
void ProductionWnd::Sanitize ()
Shows building_type in production encyclopedia window.
References m_build_designator_wnd.
SelectDefaultPlanet()
void ProductionWnd::SelectDefaultPlanet ()
Attempts to find a planet to select, and if successful, selects that planet.
References m_build_designator_wnd.
SelectedPlanetID()
int ProductionWnd::SelectedPlanetID () const
References m_build_designator_wnd.
Referenced by UpdateInfoPanel().
SelectPlanet()
void ProductionWnd::SelectPlanet (int planet_id)
Programatically sets this Wnd's selected planet.
Does not emit a PlanetSelectedSignal.
References m_build_designator_wnd, and UpdateInfoPanel().
SelectSystem()
void ProductionWnd::SelectSystem (int system_id)
Programatically sets this Wnd's selected system.
Does not emit a SystemSelectedSignal.
References m_build_designator_wnd, SidePanel::SystemID(), and Update().
SetEmpireShown()
void ProductionWnd::SetEmpireShown (int empire_id)
Shows building_type in production encyclopedia window.
References m_empire_shown_id, and Refresh().
ShowBuildingTypeInEncyclopedia()
void ProductionWnd::ShowBuildingTypeInEncyclopedia (const std::string & building_type)
Shows building_type in production encyclopedia window.
References m_build_designator_wnd.
ShowEmpireInEncyclopedia()
void ProductionWnd::ShowEmpireInEncyclopedia (int empire_id)
Shows empire in production encyclopedia window.
References m_build_designator_wnd.
ShowFieldTypeInEncyclopedia()
void ProductionWnd::ShowFieldTypeInEncyclopedia (const std::string & field_type_name)
Shows field_type in production encyclopedia window.
References m_build_designator_wnd.
ShownEmpireID()
int ProductionWnd::ShownEmpireID () const
References m_empire_shown_id.
ShowPartTypeInEncyclopedia()
void ProductionWnd::ShowPartTypeInEncyclopedia (const std::string & part_type_name)
Shows ship_part in production encyclopedia window.
References m_build_designator_wnd.
ShowPedia()
void ProductionWnd::ShowPedia ()
Change visibility of production encyclopdia panel.
References m_build_designator_wnd.
Referenced by CompleteConstruction().
ShowPlanetInEncyclopedia()
void ProductionWnd::ShowPlanetInEncyclopedia (int planet_id)
Shows planet in production encyclopedia window.
References m_build_designator_wnd.
ShowShipDesignInEncyclopedia()
void ProductionWnd::ShowShipDesignInEncyclopedia (int design_id)
Shows ShipDesign with id design_id in production encyclopedia window.
References m_build_designator_wnd.
ShowSpecialInEncyclopedia()
void ProductionWnd::ShowSpecialInEncyclopedia (const std::string & special_name)
Shows special in production encyclopedia window.
References m_build_designator_wnd.
ShowSpeciesInEncyclopedia()
void ProductionWnd::ShowSpeciesInEncyclopedia (const std::string & species_name)
Shows species in production encyclopedia window.
References m_build_designator_wnd.
ShowTechInEncyclopedia()
void ProductionWnd::ShowTechInEncyclopedia (const std::string & tech_name)
Shows tech in production encyclopedia window.
References m_build_designator_wnd.
SizeMove()
void ProductionWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Shows building_type in production encyclopedia window.
References DoLayout().
TogglePedia()
void ProductionWnd::TogglePedia ()
Shows building_type in production encyclopedia window.
References m_build_designator_wnd.
Update()
void ProductionWnd::Update ()
Shows building_type in production encyclopedia window.
References m_build_designator_wnd, UpdateInfoPanel(), and UpdateQueue().
Referenced by SelectSystem().
UpdateInfoPanel()
void ProductionWnd::UpdateInfoPanel () private
Updates production summary at top left of production screen, and signals that the empire's minerals resource pool has changed (propagates to the mapwnd to update indicator)
References ProductionQueue::AllocatedPP(), ProductionQueue::AllocatedStockpilePP(), ProductionQueue::AvailablePP(), ObjectMap::get(), GetEmpire(), Empire::GetProductionQueue(), Empire::GetResourcePool(), m_empire_shown_id, m_production_info_panel, Objects(), Empire::ResourceOutput(), SelectedPlanetID(), ProductionQueue::StockpileCapacity(), ProductionQueue::TotalPPsSpent(), and UserString().
Referenced by ProductionQueueChangedSlot(), Refresh(), SelectPlanet(), and Update().
UpdateQueue()
void ProductionWnd::UpdateQueue () private
Clears and repopulates queue list with listitems corresponding to contents of empire's production queue.
References ChangeBuildQuantityBlockSlot(), QueueListBox::Clear(), DebugLogger, GetEmpire(), Empire::GetProductionQueue(), m_empire_shown_id, m_queue_wnd, and QueueListBox::RowWidth().
Referenced by ProductionQueueChangedSlot(), Refresh(), and Update().
Member Data Documentation
m_build_designator_wnd
std::shared_ptr<BuildDesignatorWnd> ProductionWnd::m_build_designator_wnd private
Referenced by AddBuildToQueueSlot(), CenterOnBuild(), CompleteConstruction(), DoLayout(), HidePedia(), InClient(), InWindow(), PediaVisible(), ProductionQueueChangedSlot(), QueueItemClickedSlot(), QueueItemDoubleClickedSlot(), Refresh(), Sanitize(), SelectDefaultPlanet(), SelectedPlanetID(), SelectPlanet(), SelectSystem(), ShowBuildingTypeInEncyclopedia(), ShowEmpireInEncyclopedia(), ShowFieldTypeInEncyclopedia(), ShowPartTypeInEncyclopedia(), ShowPedia(), ShowPlanetInEncyclopedia(), ShowShipDesignInEncyclopedia(), ShowSpecialInEncyclopedia(), ShowSpeciesInEncyclopedia(), ShowTechInEncyclopedia(), TogglePedia(), and Update().
m_empire_connection
boost::signals2::connection ProductionWnd::m_empire_connection private
Referenced by Refresh(), and ~ProductionWnd().
m_empire_shown_id
int ProductionWnd::m_empire_shown_id private
Referenced by Refresh(), Reset(), SetEmpireShown(), ShownEmpireID(), UpdateInfoPanel(), and UpdateQueue().
m_order_issuing_enabled
bool ProductionWnd::m_order_issuing_enabled private
Referenced by AddBuildToQueueSlot(), ChangeBuildQuantityBlockSlot(), ChangeBuildQuantitySlot(), DeleteQueueItem(), EnableOrderIssuing(), QueueItemDuped(), QueueItemMoved(), QueueItemPaused(), QueueItemRallied(), QueueItemSplit(), and QueueItemUseImperialPP().
m_production_info_panel
std::shared_ptr<ResourceInfoPanel> ProductionWnd::m_production_info_panel private
Referenced by CompleteConstruction(), DoLayout(), InClient(), InWindow(), and UpdateInfoPanel().
m_queue_wnd
std::shared_ptr<ProductionQueueWnd> ProductionWnd::m_queue_wnd private
Referenced by AddBuildToQueueSlot(), CompleteConstruction(), DeleteQueueItem(), DoLayout(), EnableOrderIssuing(), InClient(), InWindow(), QueueItemClickedSlot(), QueueItemDoubleClickedSlot(), QueueItemDuped(), QueueItemMoved(), QueueItemPaused(), QueueItemRallied(), QueueItemSplit(), QueueItemUseImperialPP(), Reset(), and UpdateQueue().
PlanetSelectedSignal
boost::signals2::signal<void (int)> ProductionWnd::PlanetSelectedSignal mutable
emitted when the user changes the selected planet in the production screen
RowQuantChangedSignal
boost::signals2::signal<void (int,int)> ProductionWnd::RowQuantChangedSignal mutable
SystemSelectedSignal
boost::signals2::signal<void (int)> ProductionWnd::SystemSelectedSignal mutable
emitted when the user changes the selected system in the production screen
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
ProductionWnd.h
ProductionWnd.cpp