FreeOrion: anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow Class Reference
anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow Class Reference
Public Member Functions
ShipFightersBrowseRow (const std::string &label, int qty, double value, double base_value=0.0f)
void CompleteConstruction () override
Private Attributes
std::shared_ptr< CUILabel > m_label_control
std::shared_ptr< CUILabel > m_qty_control
std::shared_ptr< CUILabel > m_value_control
Constructor & Destructor Documentation
anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow (const std::string & label, int qty, double value, double base_value = 0.0f) inline
Ctor
Parameters
[in] label text for the descriptive label, aligned to right
[in] qty quantity of source effect in label, not displayed when less or equal to 1.
[in] value value for label positioned to right of qty
[in] base_value optional; If greater than 0.0f: the value label is formatted to "value of base_value"
References anonymous_namespace{MeterBrowseWnd.cpp}::ColourWrappedtext(), FlexibleFormat(), anonymous_namespace{MeterBrowseWnd.cpp}::IntToString(), and UserString().
Member Function Documentation
void anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction () inline override
References anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseQtyWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight(), and anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth().
Member Data Documentation
std::shared_ptr<CUILabel> anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::m_label_control private
std::shared_ptr<CUILabel> anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::m_qty_control private
std::shared_ptr<CUILabel> anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::m_value_control private
The documentation for this class was generated from the following file:
MeterBrowseWnd.cpp