FreeOrion: Effect::SetShipPartMeter Class Reference
Effect::SetShipPartMeter Class Reference final
Sets the indicated meter on all ship parts in the indicated subset.
#include <Effect.h>
Public Member Functions
SetShipPartMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRefBase< std::string >> &&part_name, std::unique_ptr< ValueRef::ValueRefBase< double >> &&value)
Affects the meter_type meter that belongs to part(s) named part_name.
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
void Execute (const ScriptingContext &context, const TargetSet &targets) const override
void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const override
unsigned int GetCheckSum () const override
MeterType GetMeterType () const
const ValueRef::ValueRefBase< std::string > * GetPartName () const
bool IsMeterEffect () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
MeterType m_meter
std::unique_ptr< ValueRef::ValueRefBase< std::string > > m_part_name
std::unique_ptr< ValueRef::ValueRefBase< double > > m_value
Friends
class boost::serialization::access
Detailed Description
Sets the indicated meter on all ship parts in the indicated subset.
This has no effect on non-Ship targets. If slot_type is specified, only parts that can mount in the indicated slot type (internal or external) are affected (this is not the same at the slot type in which the part is actually located, as a part might be mountable in both types, and located in a different type than specified, and would be matched).
Constructor & Destructor Documentation
SetShipPartMeter()
Effect::SetShipPartMeter::SetShipPartMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRefBase< std::string >> && part_name, std::unique_ptr< ValueRef::ValueRefBase< double >> && value)
Affects the meter_type meter that belongs to part(s) named part_name.
Member Function Documentation
Dump()
std::string Effect::SetShipPartMeter::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), m_meter, m_part_name, m_value, METER_CAPACITY, METER_MAX_CAPACITY, METER_MAX_SECONDARY_STAT, and METER_SECONDARY_STAT.
Referenced by Execute().
Execute() [1/3]
void Effect::SetShipPartMeter::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References Meter::Current(), DebugLogger, ScriptingContext::effect_target, ErrorLogger, m_meter, m_part_name, m_value, and Meter::SetCurrent().
Referenced by Execute().
Execute() [2/3]
void Effect::SetShipPartMeter::Execute (const ScriptingContext & context, const TargetSet & targets) const override virtual
Reimplemented from Effect::EffectBase.
References Meter::AddToCurrent(), DebugLogger, ErrorLogger, Effect::EffectBase::Execute(), m_meter, m_part_name, m_value, ValueRef::MINUS, ValueRef::PLUS, and Meter::SetCurrent().
Execute() [3/3]
void Effect::SetShipPartMeter::Execute (const ScriptingContext & context, const TargetSet & targets, AccountingMap * accounting_map, const EffectCause & effect_cause, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const override virtual
Reimplemented from Effect::EffectBase.
References Dump(), Execute(), and TraceLogger.
GetCheckSum()
unsigned int Effect::SetShipPartMeter::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_meter, m_part_name, m_value, and TraceLogger.
GetMeterType()
MeterType Effect::SetShipPartMeter::GetMeterType () const inline
GetPartName()
const ValueRef::ValueRefBase<std::string>* Effect::SetShipPartMeter::GetPartName () const inline
IsMeterEffect()
bool Effect::SetShipPartMeter::IsMeterEffect () const inline override virtual
Reimplemented from Effect::EffectBase.
serialize()
template<class Archive > void Effect::SetShipPartMeter::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::SetShipPartMeter::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_part_name, and m_value.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_meter
MeterType Effect::SetShipPartMeter::m_meter private
Referenced by Dump(), Execute(), and GetCheckSum().
m_part_name
std::unique_ptr<ValueRef::ValueRefBase<std::string> > Effect::SetShipPartMeter::m_part_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_value
std::unique_ptr<ValueRef::ValueRefBase<double> > Effect::SetShipPartMeter::m_value private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp