FreeOrion: FieldType Class Reference
FieldType Class Reference
A specification for a type of field.
#include <Field.h>
Public Member Functions
Structors
FieldType (const std::string &name, const std::string &description, float stealth, const std::set< std::string > &tags, std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, const std::string &graphic)
~FieldType ()
Accessors
const std::string & Name () const
returns the unique name for this type of field
const std::string & Description () const
returns a text description of this type of building
std::string Dump (unsigned short ntabs=0) const
returns a data file format representation of this object
float Stealth () const
returns stealth of field type
const std::set< std::string > & Tags () const
returns the unique name for this type of field
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
Returns the EffectsGroups that encapsulate the effects of thisi FieldType.
const std::string & Graphic () const
returns the name of the grapic file for this field type
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Private Attributes
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::string m_graphic
std::string m_name
float m_stealth
std::set< std::string > m_tags
Detailed Description
A specification for a type of field.
Constructor & Destructor Documentation
FieldType()
FieldType::FieldType (const std::string & name, const std::string & description, float stealth, const std::set< std::string > & tags, std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, const std::string & graphic)
References anonymous_namespace{Field.cpp}::IncreaseMeter(), m_effects, m_name, m_stealth, m_tags, and METER_STEALTH.
~FieldType()
FieldType::~FieldType ()
Member Function Documentation
Description()
const std::string& FieldType::Description () const inline
returns a text description of this type of building
References Effect::Dump().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), and FreeOrionPython::WrapUniverseClasses().
Dump()
std::string FieldType::Dump (unsigned short ntabs = 0) const
returns a data file format representation of this object
References DumpIndent(), m_description, m_effects, m_graphic, and m_name.
Referenced by FreeOrionPython::WrapUniverseClasses().
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& FieldType::Effects () const inline
Returns the EffectsGroups that encapsulate the effects of thisi FieldType.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag().
GetCheckSum()
unsigned int FieldType::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), DebugLogger, m_description, m_effects, m_graphic, m_name, m_stealth, m_tags, and FieldTypeManager::s_instance.
Graphic()
const std::string& FieldType::Graphic () const inline
returns the name of the grapic file for this field type
Referenced by ClientUI::FieldTexture().
Name()
const std::string& FieldType::Name () const inline
returns the unique name for this type of field
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), Effect::CreateField::Execute(), Field::Field(), EncyclopediaDetailPanel::SetItem(), and FreeOrionPython::WrapUniverseClasses().
Stealth()
float FieldType::Stealth () const inline
returns stealth of field type
Tags()
const std::set<std::string>& FieldType::Tags () const inline
returns the unique name for this type of field
Referenced by Field::HasTag(), and Field::Tags().
Member Data Documentation
m_description
std::string FieldType::m_description private
Referenced by Dump(), and GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > FieldType::m_effects private
Referenced by Dump(), FieldType(), and GetCheckSum().
m_graphic
std::string FieldType::m_graphic private
Referenced by Dump(), and GetCheckSum().
m_name
std::string FieldType::m_name private
Referenced by Dump(), FieldType(), and GetCheckSum().
m_stealth
float FieldType::m_stealth private
Referenced by FieldType(), and GetCheckSum().
m_tags
std::set<std::string> FieldType::m_tags private
Referenced by FieldType(), and GetCheckSum().
The documentation for this class was generated from the following files:
Field.h
Field.cpp