FreeOrion: Effect::SetSpeciesSpeciesOpinion Class Reference
Effect::SetSpeciesSpeciesOpinion Class Reference final
Sets the opinion of Species opinionated_species for other species rated_species to opinion.
#include <Effects.h>
Public Member Functions
SetSpeciesSpeciesOpinion (std::unique_ptr< ValueRef::ValueRef< std::string >> &&opinionated_species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> &&rated_species_name, std::unique_ptr< ValueRef::ValueRef< double >> &&opinion)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
virtual void Execute (ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Attributes
std::unique_ptr< ValueRef::ValueRef< double > > m_opinion
std::unique_ptr< ValueRef::ValueRef< std::string > > m_opinionated_species_name
std::unique_ptr< ValueRef::ValueRef< std::string > > m_rated_species_name
Detailed Description
Sets the opinion of Species opinionated_species for other species rated_species to opinion.
Constructor & Destructor Documentation
SetSpeciesSpeciesOpinion()
Effect::SetSpeciesSpeciesOpinion::SetSpeciesSpeciesOpinion (std::unique_ptr< ValueRef::ValueRef< std::string >> && opinionated_species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> && rated_species_name, std::unique_ptr< ValueRef::ValueRef< double >> && opinion)
Member Function Documentation
Dump()
std::string Effect::SetSpeciesSpeciesOpinion::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent().
Execute()
void Effect::SetSpeciesSpeciesOpinion::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References ScriptingContext::effect_target, GetSpeciesManager(), m_opinion, m_opinionated_species_name, m_rated_species_name, SpeciesManager::SetSpeciesSpeciesOpinion(), and SpeciesManager::SpeciesSpeciesOpinion().
GetCheckSum()
unsigned int Effect::SetSpeciesSpeciesOpinion::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), m_opinion, m_opinionated_species_name, m_rated_species_name, and TraceLogger.
SetTopLevelContent()
void Effect::SetSpeciesSpeciesOpinion::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::Effect.
References m_opinion, m_opinionated_species_name, and m_rated_species_name.
Member Data Documentation
m_opinion
std::unique_ptr<ValueRef::ValueRef<double> > Effect::SetSpeciesSpeciesOpinion::m_opinion private
Referenced by Execute(), GetCheckSum(), and SetTopLevelContent().
m_opinionated_species_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::SetSpeciesSpeciesOpinion::m_opinionated_species_name private
Referenced by Execute(), GetCheckSum(), and SetTopLevelContent().
m_rated_species_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::SetSpeciesSpeciesOpinion::m_rated_species_name private
Referenced by Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp