FreeOrion: BasesListBox::CompletedDesignListBoxRow Class Reference
BasesListBox::CompletedDesignListBoxRow Class Reference
Public Member Functions
CompletedDesignListBoxRow (GG::X w, GG::Y h, const ShipDesign &design)
void CompleteConstruction () override
int DesignID () const
Public Member Functions inherited from BasesListBox::BasesListBoxRow
BasesListBoxRow (GG::X w, GG::Y h, const std::string &hull, const std::string &name)
void CompleteConstruction () override
void Render () override
virtual void SetAvailability (const AvailabilityManager::DisplayedAvailabilies &type)
virtual void SetDisplayName (const std::string &name)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
int m_design_id = INVALID_DESIGN_ID
Constructor & Destructor Documentation
CompletedDesignListBoxRow()
BasesListBox::CompletedDesignListBoxRow::CompletedDesignListBoxRow (GG::X w, GG::Y h, const ShipDesign & design)
Member Function Documentation
CompleteConstruction()
void BasesListBox::CompletedDesignListBoxRow::CompleteConstruction () override
References BasesListBox::BASES_LIST_BOX_DROP_TYPE, anonymous_namespace{DesignWnd.cpp}::COMPLETE_DESIGN_ROW_DROP_STRING, and BasesListBox::BasesListBoxRow::CompleteConstruction().
DesignID()
int BasesListBox::CompletedDesignListBoxRow::DesignID () const inline
Referenced by CompletedDesignsListBox::BaseLeftClicked(), MonstersListBox::BaseLeftClicked(), AllDesignsListBox::BaseLeftClicked(), CompletedDesignsListBox::BaseRightClicked(), CompletedDesignsListBox::ChildrenDraggedAwayCore(), MonstersListBox::ChildrenDraggedAwayCore(), AllDesignsListBox::ChildrenDraggedAwayCore(), and CompletedDesignsListBox::QueueItemMoved().
Member Data Documentation
m_design_id
int BasesListBox::CompletedDesignListBoxRow::m_design_id = INVALID_DESIGN_ID private
The documentation for this class was generated from the following file:
DesignWnd.cpp