FreeOrion: Special Class Reference
Special Class Reference
#include <Special.h>
Public Member Functions
Structors
Special (const std::string &name, const std::string &description, std::unique_ptr< ValueRef::ValueRefBase< double >> &&stealth, std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, double spawn_rate=1.0, int spawn_limit=99999, std::unique_ptr< ValueRef::ValueRefBase< double >> &&initial_capaicty=nullptr, std::unique_ptr< Condition::ConditionBase > &&location=nullptr, const std::string &graphic="")
~Special ()
Accessors
const std::string & Name () const
returns the unique name for this type of special
std::string Description () const
returns a text description of this type of special
std::string Dump (unsigned short ntabs=0) const
returns a data file format representation of this object
const ValueRef::ValueRefBase< double > * Stealth () const
returns the stealth of the special, which determines how easily it is seen by empires
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
float SpawnRate () const
returns the unique name for this type of special
int SpawnLimit () const
returns the unique name for this type of special
const ValueRef::ValueRefBase< double > * InitialCapacity () const
returns the ValueRef to use to set the initial capacity of the special when placed
float InitialCapacity (int object_id) const
evaluates initial apacity ValueRef using the object with specified object_id as the object on which the special will be placed
const Condition::ConditionBase * Location () const
returns the condition that determines whether an UniverseObject can have this special applied during universe creation
const std::string & Graphic () const
returns the unique name for this type of special
unsigned int GetCheckSum () const
returns the name of the grapic file for this special
Private Member Functions
void Init ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::string m_graphic
std::unique_ptr< ValueRef::ValueRefBase< double > > m_initial_capacity
std::unique_ptr< Condition::ConditionBase > m_location
std::string m_name
int m_spawn_limit
float m_spawn_rate
std::unique_ptr< ValueRef::ValueRefBase< double > > m_stealth
Friends
class boost::serialization::access
Detailed Description
A predefined set of EffectsGroups that can be attached to a UniverseObject (often referred to as the "source" object). The effects of a Special are not limited to the object to which it is attached. Each kind of Special must have a unique name string, by which it can be looked up using GetSpecial().
Constructor & Destructor Documentation
Special::Special (const std::string & name, const std::string & description, std::unique_ptr< ValueRef::ValueRefBase< double >> && stealth, std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, double spawn_rate = 1.0, int spawn_limit = 99999, std::unique_ptr< ValueRef::ValueRefBase< double >> && initial_capaicty = nullptr, std::unique_ptr< Condition::ConditionBase > && location = nullptr, const std::string & graphic = "")
References Init(), and m_effects.
Special::~Special ()
Member Function Documentation
std::string Special::Description () const
returns a text description of this type of special
References m_description, m_effects, and UserString().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), SpecialsPanel::Update(), and FreeOrionPython::WrapUniverseClasses().
std::string Special::Dump (unsigned short ntabs = 0) const
returns a data file format representation of this object
References DumpIndent(), m_description, m_effects, m_graphic, m_initial_capacity, m_location, m_name, m_spawn_limit, m_spawn_rate, m_stealth, and to_string().
Referenced by FreeOrionPython::WrapUniverseClasses().
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& Special::Effects () const inline
Returns the EffectsGroups that encapsulate the effects that specials of this type have.
Referenced by Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), and SpecialsPanel::Update().
unsigned int Special::GetCheckSum () const
returns the name of the grapic file for this special
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function. Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_description, m_effects, m_graphic, m_initial_capacity, m_location, m_name, m_spawn_limit, m_spawn_rate, and m_stealth.
const std::string& Special::Graphic () const inline
returns the unique name for this type of special
Referenced by ClientUI::SpecialIcon().
void Special::Init () private
References m_effects, m_initial_capacity, m_location, m_name, and m_stealth.
Referenced by Special().
const ValueRef::ValueRefBase<double>* Special::InitialCapacity () const inline
returns the ValueRef to use to set the initial capacity of the special when placed
Referenced by anonymous_namespace{ServerWrapper.cpp}::AddSpecial().
float Special::InitialCapacity (int object_id) const
evaluates initial apacity ValueRef using the object with specified object_id as the object on which the special will be placed
References GetUniverseObject(), and m_initial_capacity.
const Condition::ConditionBase* Special::Location () const inline
returns the condition that determines whether an UniverseObject can have this special applied during universe creation
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{ServerWrapper.cpp}::SpecialHasLocation(), and anonymous_namespace{ServerWrapper.cpp}::SpecialLocations().
const std::string& Special::Name () const inline
returns the unique name for this type of special
References Effect::Dump().
Referenced by EncyclopediaDetailPanel::SetItem(), SpecialsPanel::Update(), and FreeOrionPython::WrapUniverseClasses().
template<class Archive > void Special::serialize (Archive & ar, const unsigned int version) private
int Special::SpawnLimit () const inline
returns the unique name for this type of special
Referenced by anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnLimit(), and FreeOrionPython::WrapUniverseClasses().
float Special::SpawnRate () const inline
returns the unique name for this type of special
Referenced by anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnRate(), and FreeOrionPython::WrapUniverseClasses().
const ValueRef::ValueRefBase<double>* Special::Stealth () const inline
returns the stealth of the special, which determines how easily it is seen by empires
Referenced by anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::string Special::m_description private
Referenced by Description(), Dump(), and GetCheckSum().
std::vector<std::shared_ptr<Effect::EffectsGroup> > Special::m_effects private
Referenced by Description(), Dump(), GetCheckSum(), Init(), and Special().
std::string Special::m_graphic private
Referenced by Dump(), and GetCheckSum().
std::unique_ptr<ValueRef::ValueRefBase<double> > Special::m_initial_capacity private
Referenced by Dump(), GetCheckSum(), Init(), and InitialCapacity().
std::unique_ptr<Condition::ConditionBase> Special::m_location private
Referenced by Dump(), GetCheckSum(), and Init().
std::string Special::m_name private
Referenced by Dump(), GetCheckSum(), and Init().
int Special::m_spawn_limit private
Referenced by Dump(), and GetCheckSum().
float Special::m_spawn_rate private
Referenced by Dump(), and GetCheckSum().
std::unique_ptr<ValueRef::ValueRefBase<double> > Special::m_stealth private
Referenced by Dump(), GetCheckSum(), and Init().
The documentation for this class was generated from the following files:
Special.h
Special.cpp