FreeOrion: BombardOrder Class Reference
BombardOrder Class Reference
the Order subclass that represents a planet bombardment action
#include <Order.h>
Public Member Functions
Structors
BombardOrder (int empire, int ship, int planet)
Accessors
int PlanetID () const
Returns ID of the planet to be bombarded.
int ShipID () const
Returns ID of the ship which is bombarding the planet.
Public Member Functions inherited from Order
void Execute () const
Executes the order on the Universe and Empires.
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Order ()
ctor taking the ID of the Empire issuing the order.
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
ctor taking the ID of the Empire issuing the order.
int EmpireID () const
Returns the ID of the Empire issuing the order.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
Static Public Member Functions
static bool Check (int empire_id, int ship_id, int planet_id)
Private Member Functions
BombardOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
bool UndoImpl () const override
Private Attributes
int m_planet = INVALID_OBJECT_ID
int m_ship = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents a planet bombardment action
Constructor & Destructor Documentation
BombardOrder() [1/2]
BombardOrder::BombardOrder (int empire, int ship, int planet)
References Check().
BombardOrder() [2/2]
BombardOrder::BombardOrder () private default
Member Function Documentation
Check()
bool BombardOrder::Check (int empire_id, int ship_id, int planet_id) static
References Empires(), ErrorLogger, ObjectMap::get(), EmpireManager::GetDiplomaticStatus(), GetUniverse(), INVALID_OBJECT_ID, and Objects().
Referenced by BombardOrder(), and ExecuteImpl().
ExecuteImpl()
void BombardOrder::ExecuteImpl () const override private virtual
Preconditions:
m_planet must be the ID of a planet
m_ship must be the the ID of a ship owned by the issuing empire
Postconditions:
The ship with ID m_ship will be marked to bombard the planet with id m_planet during the next turn processing.
Implements Order.
References Check(), DebugLogger, Order::EmpireID(), ObjectMap::get(), Order::GetValidatedEmpire(), m_planet, m_ship, UniverseObject::Name(), Objects(), and Ship::SetBombardPlanet().
PlanetID()
int BombardOrder::PlanetID () const inline
Returns ID of the planet to be bombarded.
serialize()
template<typename Archive > void BombardOrder::serialize (Archive & ar, const unsigned int version) private
ShipID()
int BombardOrder::ShipID () const inline
Returns ID of the ship which is bombarding the planet.
References Order::ExecuteImpl(), and Order::UndoImpl().
UndoImpl()
bool BombardOrder::UndoImpl () const override private virtual
Reimplemented from Order.
References ErrorLogger, ObjectMap::get(), m_planet, m_ship, and Objects().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_planet
int BombardOrder::m_planet = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
m_ship
int BombardOrder::m_ship = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp