FreeOrion: CUIMultiEdit Class Reference
CUIMultiEdit Class Reference
a FreeOrion MultiEdit control
#include <CUIControls.h>
Public Member Functions
void CompleteConstruction () override
Structors
CUIMultiEdit (const std::string &str, GG::Flags< GG::MultiEditStyle > style=GG::MULTI_LINEWRAP)
Mutators
void Render () override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Detailed Description
a FreeOrion MultiEdit control
Constructor & Destructor Documentation
CUIMultiEdit()
CUIMultiEdit::CUIMultiEdit (const std::string & str, GG::Flags< GG::MultiEditStyle > style = GG::MULTI_LINEWRAP) explicit
Member Function Documentation
CompleteConstruction()
void CUIMultiEdit::CompleteConstruction () override
References ClientUI::EditHiliteColor().
Referenced by CUILinkTextMultiEdit::CompleteConstruction().
RClick()
void CUIMultiEdit::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References UserString().
Render()
void CUIMultiEdit::Render () override
Referenced by CUILinkTextMultiEdit::Render().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp