FreeOrion: ProductionQueueOrder Class Reference
ProductionQueueOrder Class Reference
#include <Order.h>
Public Member Functions
Structors
ProductionQueueOrder ()
ProductionQueueOrder (int empire, const ProductionQueue::ProductionItem &item, int number, int location, int pos=-1)
ProductionQueueOrder (int empire, int index, int new_quantity, bool dummy)
ProductionQueueOrder (int empire, int index, int rally_point_id, bool dummy1, bool dummy2)
ProductionQueueOrder (int empire, int index, int new_quantity, int new_blocksize)
ProductionQueueOrder (int empire, int index, int new_index)
ProductionQueueOrder (int empire, int index)
ProductionQueueOrder (int empire, int index, bool pause, float dummy)
Public Member Functions inherited from Order
void Execute () const
bool Undo () const
Order ()
Order (int empire)
virtual ~Order ()
int EmpireID () const
Private Member Functions
void ExecuteImpl () const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_index
ProductionQueue::ProductionItem m_item
int m_location
int m_new_blocksize
int m_new_index
int m_new_quantity
int m_number
int m_pause
int m_rally_point_id
Static Private Attributes
static const int INVALID_INDEX = -500
static const int INVALID_PAUSE_RESUME = -1
static const int INVALID_QUANTITY = -1000
static const int PAUSE = 1
static const int RESUME = 2
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
void ValidateEmpireID () const
bool Executed () const
Detailed Description
The Order subclass that represents changing an empire's production queue. The ProductionItem ctor adds the build to the beginning or end of empire's queue, the 3-arg ctor moves an existing build from its current location at index to a new one at new_index, and the 2-arg ctor removes the build at index from empire's queue.
Constructor & Destructor Documentation
ProductionQueueOrder::ProductionQueueOrder ()
ProductionQueueOrder::ProductionQueueOrder (int empire, const ProductionQueue::ProductionItem & item, int number, int location, int pos = -1)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index, int new_quantity, bool dummy)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index, int rally_point_id, bool dummy1, bool dummy2)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index, int new_quantity, int new_blocksize)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index, int new_index)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index)
ProductionQueueOrder::ProductionQueueOrder (int empire, int index, bool pause, float dummy)
Member Function Documentation
void ProductionQueueOrder::ExecuteImpl () const override private virtual
Implements Order.
References BT_BUILDING, BT_SHIP, ProductionQueue::ProductionItem::build_type, DebugLogger, Order::EmpireID(), ErrorLogger, GetEmpire(), INVALID_INDEX, INVALID_OBJECT_ID, INVALID_QUANTITY, m_index, m_item, m_location, m_new_blocksize, m_new_index, m_new_quantity, m_number, m_pause, m_rally_point_id, Empire::MoveProductionWithinQueue(), PAUSE, Empire::PauseProduction(), Empire::PlaceProductionOnQueue(), Empire::RemoveProductionFromQueue(), RESUME, Empire::ResumeProduction(), Empire::SetProductionQuantity(), Empire::SetProductionQuantityAndBlocksize(), Empire::SetProductionRallyPoint(), and Order::ValidateEmpireID().
template<class Archive > void ProductionQueueOrder::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
const int ProductionQueueOrder::INVALID_INDEX = -500 static private
Referenced by ExecuteImpl().
const int ProductionQueueOrder::INVALID_PAUSE_RESUME = -1 static private
const int ProductionQueueOrder::INVALID_QUANTITY = -1000 static private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_index private
Referenced by ExecuteImpl().
ProductionQueue::ProductionItem ProductionQueueOrder::m_item private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_location private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_new_blocksize private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_new_index private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_new_quantity private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_number private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_pause private
Referenced by ExecuteImpl().
int ProductionQueueOrder::m_rally_point_id private
Referenced by ExecuteImpl().
const int ProductionQueueOrder::PAUSE = 1 static private
Referenced by ExecuteImpl().
const int ProductionQueueOrder::RESUME = 2 static private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp