FreeOrion: CombatLogWnd::Impl Class Reference
CombatLogWnd::Impl Class Reference
Public Member Functions
Impl (CombatLogWnd &_log)
void AddRow (std::shared_ptr< GG::Wnd > wnd)
Add a row wnd at the end of the combat report.
std::shared_ptr< LinkText > DecorateLinkText (std::string text)
DecorateLinkText creates a CUILinkTextMultiEdit using text and attaches it to handlers and_flags are anded to the default flags.
void HandleWndChanged ()
When windows changes forces a re-layout.
std::vector< std::shared_ptr< GG::Wnd > > MakeCombatLogPanel (GG::X w, int viewing_empire_id, ConstCombatEventPtr event)
GG::Pt MinUsableSize () const
void PopulateWithFlatLogs (GG::X w, int viewing_empire_id, std::vector< std::shared_ptr< GG::Wnd >> &new_logs, ConstCombatEventPtr &event, std::string &&details)
Fill new_logs with pointers to the flat log contents of event using the pre-calculated details.
void SetFont (std::shared_ptr< GG::Font > font)
void SetLog (int log_id)
Set which log to show.
Public Attributes
std::shared_ptr< GG::Font > m_font
GG::Flags< GG::TextFormat > m_text_format_flags
CombatLogWnd & m_wnd
Constructor & Destructor Documentation
Impl()
CombatLogWnd::Impl::Impl (CombatLogWnd & _log)
Member Function Documentation
AddRow()
void CombatLogWnd::Impl::AddRow (std::shared_ptr< GG::Wnd > wnd)
Add a row wnd at the end of the combat report.
References m_wnd.
Referenced by SetLog().
DecorateLinkText()
std::shared_ptr< LinkText > CombatLogWnd::Impl::DecorateLinkText (std::string text)
DecorateLinkText creates a CUILinkTextMultiEdit using text and attaches it to handlers and_flags are anded to the default flags.
References VarText::EMPIRE_ID_TAG, HandleWndChanged(), m_font, m_text_format_flags, m_wnd, VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, and VarText::SYSTEM_ID_TAG.
Referenced by MakeCombatLogPanel(), PopulateWithFlatLogs(), SetLog(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::ToggleExpansion().
HandleWndChanged()
void CombatLogWnd::Impl::HandleWndChanged ()
When windows changes forces a re-layout.
References m_wnd.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction(), DecorateLinkText(), and SetLog().
MakeCombatLogPanel()
std::vector< std::shared_ptr< GG::Wnd > > CombatLogWnd::Impl::MakeCombatLogPanel (GG::X w, int viewing_empire_id, ConstCombatEventPtr event)
References DecorateLinkText(), GetUniverse(), Objects(), and PopulateWithFlatLogs().
Referenced by PopulateWithFlatLogs(), and SetLog().
MinUsableSize()
GG::Pt CombatLogWnd::Impl::MinUsableSize () const
References m_font.
PopulateWithFlatLogs()
void CombatLogWnd::Impl::PopulateWithFlatLogs (GG::X w, int viewing_empire_id, std::vector< std::shared_ptr< GG::Wnd >> & new_logs, ConstCombatEventPtr & event, std::string && details)
Fill new_logs with pointers to the flat log contents of event using the pre-calculated details.
References DecorateLinkText(), and MakeCombatLogPanel().
Referenced by MakeCombatLogPanel(), and anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::ToggleExpansion().
SetFont()
void CombatLogWnd::Impl::SetFont (std::shared_ptr< GG::Font > font)
References m_font.
SetLog()
void CombatLogWnd::Impl::SetLog (int log_id)
Set which log to show.
< numrows, numcols
< wnd margin, cell margin
References AddRow(), DebugLogger, DecorateLinkText(), ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), ObjectMap::get(), GGHumanClientApp::GetApp(), GetCombatLog(), HandleWndChanged(), LinkTaggedIDText(), m_font, m_wnd, MakeCombatLogPanel(), Objects(), anonymous_namespace{CombatLogWnd.cpp}::SegregateForces(), VarText::SYSTEM_ID_TAG, and UserString().
Member Data Documentation
m_font
std::shared_ptr<GG::Font> CombatLogWnd::Impl::m_font
Referenced by DecorateLinkText(), MinUsableSize(), SetFont(), and SetLog().
m_text_format_flags
GG::Flags<GG::TextFormat> CombatLogWnd::Impl::m_text_format_flags
Referenced by DecorateLinkText().
m_wnd
CombatLogWnd& CombatLogWnd::Impl::m_wnd
Referenced by AddRow(), DecorateLinkText(), HandleWndChanged(), and SetLog().
The documentation for this class was generated from the following file:
CombatLogWnd.cpp