FreeOrion: TechTreeWnd::LayoutPanel::TechPanel Class Reference
TechTreeWnd::LayoutPanel::TechPanel Class Reference
Represents a single tech in the LayoutPanel.
Public Member Functions
TechPanel (const std::string &tech_name, const TechTreeWnd::LayoutPanel *panel)
virtual ~TechPanel ()
void CompleteConstruction () override
int FontSize () const
bool InWindow (const GG::Pt &pt) const override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseLeave () override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void PreRender () override
Update layout and format only if required.
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void Select (bool select)
void Update ()
Public Attributes
TechTreeWnd::TechClickSignalType TechDoubleClickedSignal
TechTreeWnd::TechClickSignalType TechLeftClickedSignal
TechTreeWnd::TechSignalType TechPediaDisplaySignal
Private Member Functions
void InitBuffers ()
Private Attributes
GG::GL2DVertexBuffer m_border_buffer
bool m_browse_highlight
GG::Clr m_colour
std::shared_ptr< GG::TextControl > m_cost_and_duration_label
std::string m_cost_and_duration_text
bool m_enqueued
GG::GL2DVertexBuffer m_enqueued_indicator_buffer
int m_eta
GG::GL2DVertexBuffer m_eta_border_buffer
std::shared_ptr< GG::TextControl > m_eta_label
std::string m_eta_text
std::shared_ptr< GG::StaticGraphic > m_icon
const TechTreeWnd::LayoutPanel * m_layout_panel
std::shared_ptr< GG::TextControl > m_name_label
std::string m_name_text
bool m_selected
TechStatus m_status
const std::string & m_tech_name
std::vector< std::shared_ptr< GG::StaticGraphic > > m_unlock_icons
Detailed Description
Represents a single tech in the LayoutPanel.
Constructor & Destructor Documentation
TechPanel()
TechTreeWnd::LayoutPanel::TechPanel::TechPanel (const std::string & tech_name, const TechTreeWnd::LayoutPanel * panel)
References FontSize(), ClientUI::GetFont(), GetOptionsDB(), m_cost_and_duration_label, m_eta_label, m_icon, m_name_label, m_tech_name, ClientUI::TechIcon(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), and ClientUI::TextColor().
~TechPanel()
TechTreeWnd::LayoutPanel::TechPanel::~TechPanel () virtual
Member Function Documentation
CompleteConstruction()
void TechTreeWnd::LayoutPanel::TechPanel::CompleteConstruction () override
References GetOptionsDB(), and Update().
FontSize()
int TechTreeWnd::LayoutPanel::TechPanel::FontSize () const
References ClientUI::Pts().
Referenced by PreRender(), Render(), and TechPanel().
InitBuffers()
void TechTreeWnd::LayoutPanel::TechPanel::InitBuffers () private
InWindow()
bool TechTreeWnd::LayoutPanel::TechPanel::InWindow (const GG::Pt & pt) const override
References TechTreeWnd::LayoutPanel::ConvertPtScreenToZoomed(), m_icon, m_layout_panel, anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), and anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth().
LButtonDown()
void TechTreeWnd::LayoutPanel::TechPanel::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
LButtonUp()
void TechTreeWnd::LayoutPanel::TechPanel::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
References CUIWnd::LClick(), CUIWnd::MouseEnter(), and CUIWnd::MouseLeave().
LClick()
void TechTreeWnd::LayoutPanel::TechPanel::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_layout_panel, TechTreeWnd::LayoutPanel::m_selected_tech_name, m_tech_name, and TechLeftClickedSignal.
LDoubleClick()
void TechTreeWnd::LayoutPanel::TechPanel::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_tech_name, and TechDoubleClickedSignal.
Referenced by RClick().
LDrag()
void TechTreeWnd::LayoutPanel::TechPanel::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) inline override
MouseEnter()
void TechTreeWnd::LayoutPanel::TechPanel::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_browse_highlight.
MouseLeave()
void TechTreeWnd::LayoutPanel::TechPanel::MouseLeave () override
References m_browse_highlight.
MouseWheel()
void TechTreeWnd::LayoutPanel::TechPanel::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) inline override
References TechTreeWnd::Update().
PreRender()
void TechTreeWnd::LayoutPanel::TechPanel::PreRender () override
Update layout and format only if required.
References anonymous_namespace{AIWrapper.cpp}::EmpireID(), FontSize(), HumanClientApp::GetApp(), GetEmpire(), m_cost_and_duration_label, m_cost_and_duration_text, m_eta, m_eta_label, m_layout_panel, m_name_label, m_name_text, m_tech_name, m_unlock_icons, anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, TechTreeWnd::LayoutPanel::Scale(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth(), and Empire::TechResearched().
RClick()
void TechTreeWnd::LayoutPanel::TechPanel::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References FlexibleFormat(), LDoubleClick(), m_enqueued, m_status, m_tech_name, TechPediaDisplaySignal, and UserString().
Render()
void TechTreeWnd::LayoutPanel::TechPanel::Render () override
Need to render children too
Need to render text too
References CircleArc(), ClientUI::CtrlColor(), TechTreeWnd::LayoutPanel::DoZoom(), FontSize(), m_browse_highlight, m_colour, m_cost_and_duration_label, m_enqueued, m_eta, m_eta_label, m_icon, m_layout_panel, m_name_label, m_selected, m_status, m_unlock_icons, anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, PartlyRoundedRect(), anonymous_namespace{TechTreeWnd.cpp}::PI, TechTreeWnd::LayoutPanel::Scale(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth(), and TechTreeWnd::LayoutPanel::UndoZoom().
Select()
void TechTreeWnd::LayoutPanel::TechPanel::Select (bool select)
References m_selected.
Referenced by Update().
Update()
void TechTreeWnd::LayoutPanel::TechPanel::Update ()
References ClientUI::BuildingIcon(), ClientUI::CategoryColor(), ValueRef::ValueRef< T >::ConstantExpr(), DoubleToString(), ClientApp::EmpireID(), ResearchQueue::end(), ValueRef::ValueRef< T >::Eval(), ResearchQueue::find(), FlexibleFormat(), HumanClientApp::GetApp(), GetEmpire(), GetTech(), ClientUI::HullIcon(), m_colour, m_cost_and_duration_label, m_cost_and_duration_text, m_enqueued, m_eta, m_eta_label, m_eta_text, m_icon, m_layout_panel, m_name_label, m_name_text, TechTreeWnd::LayoutPanel::m_selected_tech_name, m_status, m_tech_name, m_unlock_icons, ClientUI::MeterIcon(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, ClientUI::PartIcon(), Select(), ClientUI::SpecialIcon(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), TechRowBrowseWnd(), to_string(), UIT_BUILDING, UIT_SHIP_HULL, UIT_SHIP_PART, and UserString().
Referenced by CompleteConstruction().
Member Data Documentation
m_border_buffer
GG::GL2DVertexBuffer TechTreeWnd::LayoutPanel::TechPanel::m_border_buffer private
m_browse_highlight
bool TechTreeWnd::LayoutPanel::TechPanel::m_browse_highlight private
Referenced by MouseEnter(), MouseLeave(), and Render().
m_colour
GG::Clr TechTreeWnd::LayoutPanel::TechPanel::m_colour private
Referenced by Render(), and Update().
m_cost_and_duration_label
std::shared_ptr<GG::TextControl> TechTreeWnd::LayoutPanel::TechPanel::m_cost_and_duration_label private
Referenced by PreRender(), Render(), TechPanel(), and Update().
m_cost_and_duration_text
std::string TechTreeWnd::LayoutPanel::TechPanel::m_cost_and_duration_text private
Referenced by PreRender(), and Update().
m_enqueued
bool TechTreeWnd::LayoutPanel::TechPanel::m_enqueued private
Referenced by RClick(), Render(), and Update().
m_enqueued_indicator_buffer
GG::GL2DVertexBuffer TechTreeWnd::LayoutPanel::TechPanel::m_enqueued_indicator_buffer private
m_eta
int TechTreeWnd::LayoutPanel::TechPanel::m_eta private
Referenced by PreRender(), Render(), and Update().
m_eta_border_buffer
GG::GL2DVertexBuffer TechTreeWnd::LayoutPanel::TechPanel::m_eta_border_buffer private
m_eta_label
std::shared_ptr<GG::TextControl> TechTreeWnd::LayoutPanel::TechPanel::m_eta_label private
Referenced by PreRender(), Render(), TechPanel(), and Update().
m_eta_text
std::string TechTreeWnd::LayoutPanel::TechPanel::m_eta_text private
Referenced by Update().
m_icon
std::shared_ptr<GG::StaticGraphic> TechTreeWnd::LayoutPanel::TechPanel::m_icon private
Referenced by InWindow(), Render(), TechPanel(), and Update().
m_layout_panel
const TechTreeWnd::LayoutPanel* TechTreeWnd::LayoutPanel::TechPanel::m_layout_panel private
Referenced by InWindow(), LClick(), PreRender(), Render(), and Update().
m_name_label
std::shared_ptr<GG::TextControl> TechTreeWnd::LayoutPanel::TechPanel::m_name_label private
Referenced by PreRender(), Render(), TechPanel(), and Update().
m_name_text
std::string TechTreeWnd::LayoutPanel::TechPanel::m_name_text private
Referenced by PreRender(), and Update().
m_selected
bool TechTreeWnd::LayoutPanel::TechPanel::m_selected private
Referenced by Render(), and Select().
m_status
TechStatus TechTreeWnd::LayoutPanel::TechPanel::m_status private
Referenced by RClick(), Render(), and Update().
m_tech_name
const std::string& TechTreeWnd::LayoutPanel::TechPanel::m_tech_name private
Referenced by LClick(), LDoubleClick(), PreRender(), RClick(), TechPanel(), and Update().
m_unlock_icons
std::vector<std::shared_ptr<GG::StaticGraphic> > TechTreeWnd::LayoutPanel::TechPanel::m_unlock_icons private
Referenced by PreRender(), Render(), and Update().
TechDoubleClickedSignal
TechTreeWnd::TechClickSignalType TechTreeWnd::LayoutPanel::TechPanel::TechDoubleClickedSignal mutable
Referenced by LDoubleClick().
TechLeftClickedSignal
TechTreeWnd::TechClickSignalType TechTreeWnd::LayoutPanel::TechPanel::TechLeftClickedSignal mutable
Referenced by LClick().
TechPediaDisplaySignal
TechTreeWnd::TechSignalType TechTreeWnd::LayoutPanel::TechPanel::TechPediaDisplaySignal mutable
Referenced by RClick().
The documentation for this class was generated from the following file:
TechTreeWnd.cpp