FreeOrion: anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel Class Reference
anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel Class Reference
Public Member Functions
QueueProductionItemPanel (GG::X x, GG::Y y, GG::X w, const ProductionQueue::Element &build, double turn_cost, double total_cost, int turns, int number, double completed_progress)
void CompleteConstruction () override
void ItemBlocksizeChanged (int quant, int blocksize)
void ItemQuantityChanged (int quant, int blocksize)
void PreRender () override
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Static Public Member Functions
static GG::Y DefaultHeight ()
Public Attributes
boost::signals2::signal< void(int, int)> PanelUpdateQuantSignal
Private Member Functions
void DoLayout ()
void Draw (GG::Clr clr, bool fill)
Private Attributes
const ProductionQueue::Element elem
std::shared_ptr< QuantitySelector > m_block_size_selector
double m_completed_progress
std::shared_ptr< GG::StaticGraphic > m_icon
bool m_in_progress
std::shared_ptr< GG::Label > m_location_text
std::shared_ptr< GG::Label > m_name_text
bool m_order_issuing_enabled
std::shared_ptr< GG::Label > m_PPs_and_turns_text
std::shared_ptr< MultiTurnProgressBar > m_progress_bar
std::shared_ptr< QuantitySelector > m_quantity_selector
double m_total_cost
int m_total_turns
double m_turn_spending
std::shared_ptr< GG::Label > m_turns_remaining_until_next_complete_text
Constructor & Destructor Documentation
QueueProductionItemPanel()
anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::QueueProductionItemPanel (GG::X x, GG::Y y, GG::X w, const ProductionQueue::Element & build, double turn_cost, double total_cost, int turns, int number, double completed_progress)
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction () override
References BT_BUILDING, BT_SHIP, BT_STOCKPILE, ProductionQueue::ProductionItem::build_type, ClientUI::BuildingIcon(), Empire::Color(), ProductionQueue::ProductionItem::design_id, DoubleToString(), elem, ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), OptionsDB::Get(), HumanClientApp::GetApp(), ClientUI::GetBoldFont(), GetEmpire(), GetOptionsDB(), GetShipDesign(), ClientUI::GetTexture(), GetUniverseObject(), INVALID_OBJECT_ID, ProductionQueue::Element::item, ItemBlocksizeChanged(), ItemQuantityChanged(), ProductionQueue::Element::location, m_block_size_selector, m_completed_progress, m_icon, m_in_progress, m_location_text, m_name_text, m_PPs_and_turns_text, m_progress_bar, m_quantity_selector, m_total_cost, m_total_turns, m_turn_spending, m_turns_remaining_until_next_complete_text, METER_STOCKPILE, ClientUI::MeterIcon(), ProductionQueue::ProductionItem::name, ShipDesign::Name(), ClientUI::Pts(), ProductionQueue::Element::rally_point_id, ClientUI::ResearchableTechFillColor(), ClientUI::ResearchableTechTextAndBorderColor(), ClientUI::ShipDesignIcon(), SidePanel::SystemID(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), ProductionQueue::Element::turns_left_to_next_item, and UserString().
DefaultHeight()
GG::Y anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::DefaultHeight () static
References ClientUI::Pts().
DoLayout()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::DoLayout () private
References m_block_size_selector, m_icon, m_location_text, m_name_text, m_PPs_and_turns_text, m_progress_bar, m_quantity_selector, m_turns_remaining_until_next_complete_text, anonymous_namespace{ProductionWnd.cpp}::MARGIN, and ClientUI::Pts().
Referenced by ProductionQueueWnd::CompleteConstruction(), PreRender(), and ProductionQueueWnd::SizeMove().
Draw()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Draw (GG::Clr clr, bool fill) private
References PartlyRoundedRect().
Referenced by Render().
ItemBlocksizeChanged()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::ItemBlocksizeChanged (int quant, int blocksize)
References elem, PanelUpdateQuantSignal, and ProductionQueue::Element::remaining.
Referenced by CompleteConstruction().
ItemQuantityChanged()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::ItemQuantityChanged (int quant, int blocksize)
References ProductionQueue::Element::blocksize, elem, and PanelUpdateQuantSignal.
Referenced by CompleteConstruction().
PreRender()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::PreRender () override
References DoLayout(), m_block_size_selector, and m_quantity_selector.
Render()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Render () override
References Draw(), m_in_progress, ClientUI::ResearchableTechFillColor(), and ClientUI::ResearchableTechTextAndBorderColor().
SizeMove()
void anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Member Data Documentation
elem
const ProductionQueue::Element anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::elem private
Referenced by CompleteConstruction(), ItemBlocksizeChanged(), ItemQuantityChanged(), and anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl().
m_block_size_selector
std::shared_ptr<QuantitySelector> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_block_size_selector private
Referenced by CompleteConstruction(), DoLayout(), and PreRender().
m_completed_progress
double anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_completed_progress private
Referenced by CompleteConstruction().
m_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_icon private
Referenced by CompleteConstruction(), and DoLayout().
m_in_progress
bool anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_in_progress private
Referenced by CompleteConstruction(), and Render().
m_location_text
std::shared_ptr<GG::Label> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_location_text private
Referenced by CompleteConstruction(), and DoLayout().
m_name_text
std::shared_ptr<GG::Label> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_name_text private
Referenced by CompleteConstruction(), and DoLayout().
m_order_issuing_enabled
bool anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_order_issuing_enabled private
m_PPs_and_turns_text
std::shared_ptr<GG::Label> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_PPs_and_turns_text private
Referenced by CompleteConstruction(), and DoLayout().
m_progress_bar
std::shared_ptr<MultiTurnProgressBar> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_progress_bar private
Referenced by CompleteConstruction(), and DoLayout().
m_quantity_selector
std::shared_ptr<QuantitySelector> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_quantity_selector private
Referenced by CompleteConstruction(), DoLayout(), and PreRender().
m_total_cost
double anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_total_cost private
Referenced by CompleteConstruction().
m_total_turns
int anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_total_turns private
Referenced by CompleteConstruction().
m_turn_spending
double anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_turn_spending private
Referenced by CompleteConstruction().
m_turns_remaining_until_next_complete_text
std::shared_ptr<GG::Label> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::m_turns_remaining_until_next_complete_text private
Referenced by CompleteConstruction(), and DoLayout().
PanelUpdateQuantSignal
boost::signals2::signal<void(int,int)> anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::PanelUpdateQuantSignal mutable
Referenced by ItemBlocksizeChanged(), and ItemQuantityChanged().
The documentation for this class was generated from the following file:
ProductionWnd.cpp