FreeOrion: PlayerListWnd Class Reference
PlayerListWnd Class Reference
#include <PlayerListWnd.h>
Public Member Functions
PlayerListWnd (const std::string &config_name)
void Clear ()
void CompleteConstruction () override
void HandleDiplomaticMessageChange (int empire1_id, int empire2_id)
void Refresh ()
std::set< int > SelectedPlayerIDs () const
void SetSelectedPlayers (const std::set< int > &player_ids)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Update ()
Public Member Functions inherited from CUIWnd
CUIWnd (std::string wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (std::string wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
virtual ~CUIWnd ()
Virtual destructor.
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void Close ()
void CompleteConstruction () override
void Flash ()
void Hide () override
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
bool InWindow (const GG::Pt &pt) const override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
bool Minimized () const
returns true if window is minimized
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseLeave () override
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
void Render () override
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
void SetFlashDuration (int ms)
void Show () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void StopFlash ()
void ToggleMinimized ()
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Public Attributes
boost::signals2::signal< void()> ClosingSignal
boost::signals2::signal< void(int)> PlayerDoubleClickedSignal
boost::signals2::signal< void()> SelectedPlayersChangedSignal
Private Member Functions
void CloseClicked () override
called when window is closed via the close button
void DoLayout ()
int EmpireInRow (GG::ListBox::iterator it) const
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
void PlayerDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
int PlayerInRow (GG::ListBox::iterator it) const
void PlayerRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void PlayerSelectionChanged (const GG::ListBox::SelectionSet &rows)
Private Attributes
std::shared_ptr< PlayerListBox > m_player_list
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
void Init ()
performs initialization common to all CUIWnd constructors
virtual void InitBuffers ()
virtual void InitButtons ()
called to create the buttons, withtout positioning them
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void LoadOptions ()
loads options for this window from the OptionsDB
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
virtual void PositionButtons ()
called to position the buttons
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SaveDefaultedOptions ()
sets the default value any options previously determined from calls to SetDefaultedOptions to their current value
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
void SetDefaultedOptions ()
flags options currently at their default values for later use in SaveDefaultedOptions
void SetParent (std::shared_ptr< GG::Wnd > wnd) override
Static Protected Member Functions inherited from CUIWnd
static std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable = false
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable = false
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button
the pin button
bool m_pinable = false
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable = false
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 15
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 9
static const int RESIZE_HASHMARK2_OFFSET = 4
static const int TITLE_OFFSET = 2
Constructor & Destructor Documentation
PlayerListWnd()
PlayerListWnd::PlayerListWnd (const std::string & config_name)
Member Function Documentation
Clear()
void PlayerListWnd::Clear ()
References m_player_list.
CloseClicked()
void PlayerListWnd::CloseClicked () override private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal, and CUIWnd::StopFlash().
CompleteConstruction()
void PlayerListWnd::CompleteConstruction () override
References CUIWnd::CompleteConstruction(), EmpireManager::DiplomaticMessageChangedSignal, EmpireManager::DiplomaticStatusChangedSignal, DoLayout(), Empires(), m_player_list, PlayerDoubleClicked(), PlayerRightClicked(), PlayerSelectionChanged(), Refresh(), and Update().
DoLayout()
void PlayerListWnd::DoLayout () private
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, and m_player_list.
Referenced by CompleteConstruction(), and SizeMove().
EmpireInRow()
int PlayerListWnd::EmpireInRow (GG::ListBox::iterator it) const private
References ALL_EMPIRES, and m_player_list.
Referenced by PlayerRightClicked().
HandleDiplomaticMessageChange()
void PlayerListWnd::HandleDiplomaticMessageChange (int empire1_id, int empire2_id)
References ALL_EMPIRES, ClientApp::EmpireID(), Empires(), ErrorLogger, CUIWnd::Flash(), ClientApp::GetApp(), EmpireManager::GetDiplomaticMessage(), CUIWnd::Show(), CUIWnd::StopFlash(), and Update().
LClick()
void PlayerListWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override private
References CUIWnd::LClick(), and CUIWnd::StopFlash().
LDrag()
void PlayerListWnd::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override private
References CUIWnd::LDrag(), and CUIWnd::StopFlash().
PlayerDoubleClicked()
void PlayerListWnd::PlayerDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References Networking::INVALID_PLAYER_ID, PlayerDoubleClickedSignal, and PlayerInRow().
Referenced by CompleteConstruction().
PlayerInRow()
int PlayerListWnd::PlayerInRow (GG::ListBox::iterator it) const private
References Networking::INVALID_PLAYER_ID, and m_player_list.
Referenced by PlayerDoubleClicked(), and SelectedPlayerIDs().
PlayerRightClicked()
void PlayerListWnd::PlayerRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References AcceptAlliesDiplomaticMessage(), AcceptPeaceDiplomaticMessage(), ALL_EMPIRES, AlliesProposalDiplomaticMessage(), CancelDiplomaticMessage(), Networking::CLIENT_TYPE_HUMAN_PLAYER, ClientApp::EmpireID(), EmpireInRow(), Empires(), EndAllianceDiplomaticMessage(), ErrorLogger, FlexibleFormat(), ClientApp::GetApp(), ClientApp::GetClientType(), ClientUI::GetClientUI(), EmpireManager::GetDiplomaticMessage(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), Networking::INVALID_PLAYER_ID, anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction(), anonymous_namespace{XMLDoc.cpp}::Name, PeaceProposalDiplomaticMessage(), ClientApp::PlayerID(), RejectProposalDiplomaticMessage(), UserString(), WarDeclarationDiplomaticMessage(), and ClientUI::ZoomToEmpire().
Referenced by CompleteConstruction().
PlayerSelectionChanged()
void PlayerListWnd::PlayerSelectionChanged (const GG::ListBox::SelectionSet & rows) private
References ErrorLogger, m_player_list, and SelectedPlayersChangedSignal.
Referenced by CompleteConstruction(), and SetSelectedPlayers().
Refresh()
void PlayerListWnd::Refresh ()
References ALL_EMPIRES, ClientApp::EmpirePlayerID(), Empires(), ErrorLogger, ClientApp::GetApp(), m_player_list, ClientApp::Players(), SelectedPlayerIDs(), and SetSelectedPlayers().
Referenced by CompleteConstruction().
SelectedPlayerIDs()
std::set< int > PlayerListWnd::SelectedPlayerIDs () const
References Networking::INVALID_PLAYER_ID, m_player_list, and PlayerInRow().
Referenced by Refresh().
SetSelectedPlayers()
void PlayerListWnd::SetSelectedPlayers (const std::set< int > & player_ids)
References ErrorLogger, m_player_list, and PlayerSelectionChanged().
Referenced by Refresh().
SizeMove()
void PlayerListWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
Update()
void PlayerListWnd::Update ()
References m_player_list.
Referenced by CompleteConstruction(), and HandleDiplomaticMessageChange().
Member Data Documentation
ClosingSignal
boost::signals2::signal<void ()> PlayerListWnd::ClosingSignal mutable
Referenced by CloseClicked().
m_player_list
std::shared_ptr<PlayerListBox> PlayerListWnd::m_player_list private
Referenced by Clear(), CompleteConstruction(), DoLayout(), EmpireInRow(), PlayerInRow(), PlayerSelectionChanged(), Refresh(), SelectedPlayerIDs(), SetSelectedPlayers(), and Update().
PlayerDoubleClickedSignal
boost::signals2::signal<void (int)> PlayerListWnd::PlayerDoubleClickedSignal mutable
Referenced by PlayerDoubleClicked().
SelectedPlayersChangedSignal
boost::signals2::signal<void ()> PlayerListWnd::SelectedPlayersChangedSignal mutable
Referenced by PlayerSelectionChanged().
The documentation for this class was generated from the following files:
PlayerListWnd.h
PlayerListWnd.cpp