FreeOrion: SupplyManager Class Reference
SupplyManager Class Reference
Used to calcuate all empires' supply distributions.
#include <Supply.h>
Public Member Functions
Structors
SupplyManager ()
SupplyManager & operator= (const SupplyManager &rhs)
Accessors
const std::map< int, std::set< std::pair< int, int > > > & SupplyStarlaneTraversals () const
Returns set of directed starlane traversals along which supply can flow.
const std::set< std::pair< int, int > > & SupplyStarlaneTraversals (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
const std::map< int, std::set< std::pair< int, int > > > & SupplyObstructedStarlaneTraversals () const
Returns set of directed starlane traversals along which supply could flow for this empire, but which can't due to some obstruction in one of the systems.
const std::set< std::pair< int, int > > & SupplyObstructedStarlaneTraversals (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
const std::map< int, std::set< int > > & FleetSupplyableSystemIDs () const
Returns set of system ids where fleets can be supplied by this empire (as determined by object supply meters and rules of supply propagation and blockade).
const std::set< int > & FleetSupplyableSystemIDs (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
std::set< int > FleetSupplyableSystemIDs (int empire_id, bool include_allies) const
Returns set of directed starlane traversals along which supply can flow.
int EmpireThatCanSupplyAt (int system_id) const
Returns set of directed starlane traversals along which supply can flow.
const std::map< int, std::set< std::set< int > > > & ResourceSupplyGroups () const
Returns set of sets of systems that can share industry (systems in separate groups are blockaded or otherwise separated).
const std::set< std::set< int > > & ResourceSupplyGroups (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
const std::map< int, float > & PropagatedSupplyRanges () const
Returns the range from each system some empire can propagate supply.
const std::map< int, float > & PropagatedSupplyRanges (int empire_id) const
Returns the range from each system that the empire with id empire_id can propagate supply.
const std::map< int, float > & PropagatedSupplyDistances () const
Returns the distance from each system some empire is away from its closest source of supply without passing through obstructed systems for that empire.
const std::map< int, float > & PropagatedSupplyDistances (int empire_id) const
Returns the distance from each system for the empire with id empire_id to the closest source of supply without passing through obstructed systems for that empire.
bool SystemHasFleetSupply (int system_id, int empire_id) const
Returns true if system with id system_id is fleet supplyable or in one of the resource supply groups for empire with id empire_id.
bool SystemHasFleetSupply (int system_id, int empire_id, bool include_allies) const
Returns set of directed starlane traversals along which supply can flow.
std::string Dump (int empire_id=ALL_EMPIRES) const
Returns set of directed starlane traversals along which supply can flow.
Mutators
void Update ()
Calculates systems at which fleets of empires can be supplied, and groups of systems that can exchange resources, and the starlane traversals used to do so.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::map< int, std::map< int, float > > m_empire_propagated_supply_distances
for each empire, what systems it can propagate supply into, and how far that system is from the closest source of supply for that empire, along possible supply propgation connections (ie.
std::map< int, std::map< int, float > > m_empire_propagated_supply_ranges
for each empire, what systems it can propagate supply into, and how many further supply jumps it could propagate past this system, if not blocked from doing so by supply obstructions.
std::map< int, std::set< int > > m_fleet_supplyable_system_ids
ids of systems where fleets can be resupplied.
std::map< int, float > m_propagated_supply_distances
for whichever empire can propagate supply into this system, how far that system is from the closest source of supply for that empire, along possible supply propgation connections (ie.
std::map< int, float > m_propagated_supply_ranges
for whichever empire can propagate supply into this system, what is the additional range from this system that empire can propagate supply
std::map< int, std::set< std::set< int > > > m_resource_supply_groups
sets of system ids that are connected by supply lines and are able to share resources between systems or between objects in systems.
std::map< int, std::set< std::pair< int, int > > > m_supply_starlane_obstructed_traversals
ordered pairs of system ids between which a starlane could be used to convey resources between system, but is not because something is obstructing the resource flow.
std::map< int, std::set< std::pair< int, int > > > m_supply_starlane_traversals
ordered pairs of system ids between which a starlane runs that can be used to convey resources between systems.
Friends
class boost::serialization::access
Detailed Description
Used to calcuate all empires' supply distributions.
Constructor & Destructor Documentation
SupplyManager()
SupplyManager::SupplyManager ()
Member Function Documentation
Dump()
std::string SupplyManager::Dump (int empire_id = ALL_EMPIRES) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References ALL_EMPIRES, ErrorLogger, ObjectMap::get(), m_fleet_supplyable_system_ids, m_resource_supply_groups, m_supply_starlane_obstructed_traversals, m_supply_starlane_traversals, Objects(), and to_string().
EmpireThatCanSupplyAt()
int SupplyManager::EmpireThatCanSupplyAt (int system_id) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References ALL_EMPIRES, and m_fleet_supplyable_system_ids.
Referenced by ValueRef::Variable< ToType >::Eval(), and MapWnd::RenderSystems().
FleetSupplyableSystemIDs() [1/3]
const std::map< int, std::set< int > > & SupplyManager::FleetSupplyableSystemIDs () const
Returns set of system ids where fleets can be supplied by this empire (as determined by object supply meters and rules of supply propagation and blockade).
References m_fleet_supplyable_system_ids.
Referenced by anonymous_namespace{EmpireWrapper.cpp}::EmpireFleetSupplyableSystemIDsP(), FleetSupplyableSystemIDs(), anonymous_namespace{MapWnd.cpp}::GetNearestSupplyRoute(), Fleet::MovePath(), and Condition::anonymous_namespace{Conditions.cpp}::FleetSupplyableSimpleMatch::operator()().
FleetSupplyableSystemIDs() [2/3]
const std::set< int > & SupplyManager::FleetSupplyableSystemIDs (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_SET, and m_fleet_supplyable_system_ids.
FleetSupplyableSystemIDs() [3/3]
std::set< int > SupplyManager::FleetSupplyableSystemIDs (int empire_id, bool include_allies) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References Empires(), FleetSupplyableSystemIDs(), EmpireManager::GetDiplomaticStatus(), and m_fleet_supplyable_system_ids.
operator=()
SupplyManager & SupplyManager::operator= (const SupplyManager & rhs)
References m_fleet_supplyable_system_ids, m_resource_supply_groups, m_supply_starlane_obstructed_traversals, and m_supply_starlane_traversals.
PropagatedSupplyDistances() [1/2]
const std::map< int, float > & SupplyManager::PropagatedSupplyDistances () const
Returns the distance from each system some empire is away from its closest source of supply without passing through obstructed systems for that empire.
References m_propagated_supply_distances.
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntFloatMap().
PropagatedSupplyDistances() [2/2]
const std::map< int, float > & SupplyManager::PropagatedSupplyDistances (int empire_id) const
Returns the distance from each system for the empire with id empire_id to the closest source of supply without passing through obstructed systems for that empire.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_FLOAT_MAP, and m_empire_propagated_supply_distances.
PropagatedSupplyRanges() [1/2]
const std::map< int, float > & SupplyManager::PropagatedSupplyRanges () const
Returns the range from each system some empire can propagate supply.
References m_propagated_supply_ranges.
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntFloatMap().
PropagatedSupplyRanges() [2/2]
const std::map< int, float > & SupplyManager::PropagatedSupplyRanges (int empire_id) const
Returns the range from each system that the empire with id empire_id can propagate supply.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_FLOAT_MAP, and m_empire_propagated_supply_ranges.
ResourceSupplyGroups() [1/2]
const std::map< int, std::set< std::set< int > > > & SupplyManager::ResourceSupplyGroups () const
Returns set of sets of systems that can share industry (systems in separate groups are blockaded or otherwise separated).
References m_resource_supply_groups.
Referenced by Condition::anonymous_namespace{Conditions.cpp}::ResourceSupplySimpleMatch::operator()().
ResourceSupplyGroups() [2/2]
const std::set< std::set< int > > & SupplyManager::ResourceSupplyGroups (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_SET_SET, and m_resource_supply_groups.
serialize()
template<typename Archive > template void SupplyManager::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
SupplyObstructedStarlaneTraversals() [1/2]
const std::map< int, std::set< std::pair< int, int > > > & SupplyManager::SupplyObstructedStarlaneTraversals () const
Returns set of directed starlane traversals along which supply could flow for this empire, but which can't due to some obstruction in one of the systems.
References m_supply_starlane_obstructed_traversals.
Referenced by anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesP(), and anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender().
SupplyObstructedStarlaneTraversals() [2/2]
const std::set< std::pair< int, int > > & SupplyManager::SupplyObstructedStarlaneTraversals (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_PAIR_SET, and m_supply_starlane_obstructed_traversals.
SupplyStarlaneTraversals() [1/2]
const std::map< int, std::set< std::pair< int, int > > > & SupplyManager::SupplyStarlaneTraversals () const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References m_supply_starlane_traversals.
Referenced by anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), and anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender().
SupplyStarlaneTraversals() [2/2]
const std::set< std::pair< int, int > > & SupplyManager::SupplyStarlaneTraversals (int empire_id) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References anonymous_namespace{Supply.cpp}::EMPTY_INT_PAIR_SET, and m_supply_starlane_traversals.
SystemHasFleetSupply() [1/2]
bool SupplyManager::SystemHasFleetSupply (int system_id, int empire_id) const
Returns true if system with id system_id is fleet supplyable or in one of the resource supply groups for empire with id empire_id.
References ALL_EMPIRES, INVALID_OBJECT_ID, and m_fleet_supplyable_system_ids.
Referenced by Fleet::MovementPhase(), and SystemHasFleetSupply().
SystemHasFleetSupply() [2/2]
bool SupplyManager::SystemHasFleetSupply (int system_id, int empire_id, bool include_allies) const
Returns set of directed starlane traversals along which supply can flow.
Results are pairs of system ids of start and end system of traversal.
References ALL_EMPIRES, Empires(), EmpireManager::GetEmpireIDsWithDiplomaticStatusWithEmpire(), INVALID_OBJECT_ID, m_fleet_supplyable_system_ids, and SystemHasFleetSupply().
Update()
void SupplyManager::Update ()
Calculates systems at which fleets of empires can be supplied, and groups of systems that can exchange resources, and the starlane traversals used to do so.
References ObjectMap::all(), ALL_EMPIRES, DebugLogger, anonymous_namespace{Supply.cpp}::DistanceBetweenObjects(), Empire::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRange(), anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRangeSumInSystem(), ErrorLogger, ObjectMap::find(), EmpireManager::GetEmpireIDsWithDiplomaticStatusWithEmpire(), GetUniverse(), INVALID_OBJECT_ID, Empire::KnownStarlanes(), m_empire_propagated_supply_distances, m_empire_propagated_supply_ranges, m_fleet_supplyable_system_ids, m_propagated_supply_distances, m_propagated_supply_ranges, m_resource_supply_groups, m_supply_starlane_obstructed_traversals, m_supply_starlane_traversals, Objects(), Universe::Objects(), Empire::SupplyUnobstructedSystems(), Empire::SystemSupplyRanges(), and TraceLogger.
Referenced by UpdateEmpireSupply().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_empire_propagated_supply_distances
std::map<int, std::map<int, float> > SupplyManager::m_empire_propagated_supply_distances private
for each empire, what systems it can propagate supply into, and how far that system is from the closest source of supply for that empire, along possible supply propgation connections (ie.
not though a supply obstructed system)
Referenced by PropagatedSupplyDistances(), and Update().
m_empire_propagated_supply_ranges
std::map<int, std::map<int, float> > SupplyManager::m_empire_propagated_supply_ranges private
for each empire, what systems it can propagate supply into, and how many further supply jumps it could propagate past this system, if not blocked from doing so by supply obstructions.
Referenced by PropagatedSupplyRanges(), and Update().
m_fleet_supplyable_system_ids
std::map<int, std::set<int> > SupplyManager::m_fleet_supplyable_system_ids private
ids of systems where fleets can be resupplied.
indexed by empire id.
Referenced by Dump(), EmpireThatCanSupplyAt(), FleetSupplyableSystemIDs(), operator=(), SystemHasFleetSupply(), and Update().
m_propagated_supply_distances
std::map<int, float> SupplyManager::m_propagated_supply_distances private
for whichever empire can propagate supply into this system, how far that system is from the closest source of supply for that empire, along possible supply propgation connections (ie.
not though a supply obstructed system for that empire)
Referenced by PropagatedSupplyDistances(), and Update().
m_propagated_supply_ranges
std::map<int, float> SupplyManager::m_propagated_supply_ranges private
for whichever empire can propagate supply into this system, what is the additional range from this system that empire can propagate supply
Referenced by PropagatedSupplyRanges(), and Update().
m_resource_supply_groups
std::map<int, std::set<std::set<int> > > SupplyManager::m_resource_supply_groups private
sets of system ids that are connected by supply lines and are able to share resources between systems or between objects in systems.
indexed by empire id.
Referenced by Dump(), operator=(), ResourceSupplyGroups(), and Update().
m_supply_starlane_obstructed_traversals
std::map<int, std::set<std::pair<int, int> > > SupplyManager::m_supply_starlane_obstructed_traversals private
ordered pairs of system ids between which a starlane could be used to convey resources between system, but is not because something is obstructing the resource flow.
That is, the resource flow isn't limited by range, but by something blocking its flow.
Referenced by Dump(), operator=(), SupplyObstructedStarlaneTraversals(), and Update().
m_supply_starlane_traversals
std::map<int, std::set<std::pair<int, int> > > SupplyManager::m_supply_starlane_traversals private
ordered pairs of system ids between which a starlane runs that can be used to convey resources between systems.
indexed first by empire id.
Referenced by Dump(), operator=(), SupplyStarlaneTraversals(), and Update().
The documentation for this class was generated from the following files:
Supply.h
Supply.cpp
SerializeEmpire.cpp