FreeOrion: BuildingTypeManager Class Reference
BuildingTypeManager Class Reference
Holds all FreeOrion building types.
#include <Building.h>
Public Types
using BuildingTypeMap = std::map< std::string, std::unique_ptr< BuildingType > >
using iterator = BuildingTypeMap::const_iterator
Public Member Functions
FO_COMMON_API void SetBuildingTypes (Pending::Pending< BuildingTypeMap > &&pending_building_types)
Sets building types to the future value of pending_building_types.
Private Member Functions
BuildingTypeManager ()
void CheckPendingBuildingTypes () const
Assigns any m_pending_building_types to m_bulding_types.
Private Attributes
BuildingTypeMap m_building_types
Set of building types.
boost::optional< Pending::Pending< BuildingTypeMap > > m_pending_building_types = boost::none
Future building type being parsed by parser.
Static Private Attributes
static BuildingTypeManager * s_instance = nullptr
Accessors
const BuildingType * GetBuildingType (const std::string &name) const
returns the building type with the name name; you should use the free function GetBuildingType(...) instead, mainly to save some typing.
FO_COMMON_API iterator begin () const
iterator to the first building type
FO_COMMON_API iterator end () const
iterator to the last + 1th building type
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
static BuildingTypeManager & GetBuildingTypeManager ()
returns the instance of this singleton class; you should use the free function GetBuildingTypeManager() instead
Detailed Description
Holds all FreeOrion building types.
Types may be looked up by name.
Member Typedef Documentation
BuildingTypeMap
using BuildingTypeManager::BuildingTypeMap = std::map<std::string, std::unique_ptr<BuildingType> >
iterator
using BuildingTypeManager::iterator = BuildingTypeMap::const_iterator
Constructor & Destructor Documentation
BuildingTypeManager()
BuildingTypeManager::BuildingTypeManager () private
References s_instance.
Member Function Documentation
begin()
BuildingTypeManager::iterator BuildingTypeManager::begin () const
iterator to the first building type
References CheckPendingBuildingTypes(), and m_building_types.
Referenced by BuildDesignatorWnd::BuildSelector::PopulateList().
CheckPendingBuildingTypes()
void BuildingTypeManager::CheckPendingBuildingTypes () const private
Assigns any m_pending_building_types to m_bulding_types.
References m_building_types, m_pending_building_types, and Pending::SwapPending().
Referenced by begin(), end(), GetBuildingType(), and GetCheckSum().
end()
BuildingTypeManager::iterator BuildingTypeManager::end () const
iterator to the last + 1th building type
References CheckPendingBuildingTypes(), and m_building_types.
Referenced by BuildDesignatorWnd::BuildSelector::PopulateList().
GetBuildingType()
const BuildingType * BuildingTypeManager::GetBuildingType (const std::string & name) const
returns the building type with the name name; you should use the free function GetBuildingType(...) instead, mainly to save some typing.
References CheckPendingBuildingTypes(), and m_building_types.
Referenced by GetBuildingType().
GetBuildingTypeManager()
BuildingTypeManager & BuildingTypeManager::GetBuildingTypeManager () static
returns the instance of this singleton class; you should use the free function GetBuildingTypeManager() instead
Referenced by GetBuildingType(), and GetBuildingTypeManager().
GetCheckSum()
unsigned int BuildingTypeManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckPendingBuildingTypes(), CheckSums::CheckSumCombine(), DebugLogger, and m_building_types.
Referenced by CheckSumContent().
SetBuildingTypes()
void BuildingTypeManager::SetBuildingTypes (Pending::Pending< BuildingTypeMap > && pending_building_types)
Sets building types to the future value of pending_building_types.
References m_pending_building_types.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_building_types
BuildingTypeMap BuildingTypeManager::m_building_types mutable private
Set of building types.
mutable so that when the parse complete it can be updated.
Referenced by begin(), CheckPendingBuildingTypes(), end(), GetBuildingType(), and GetCheckSum().
m_pending_building_types
boost::optional<Pending::Pending<BuildingTypeMap> > BuildingTypeManager::m_pending_building_types = boost::none mutable private
Future building type being parsed by parser.
mutable so that it can be assigned to m_building_types when completed.
Referenced by CheckPendingBuildingTypes(), and SetBuildingTypes().
s_instance
BuildingTypeManager * BuildingTypeManager::s_instance = nullptr static private
Referenced by BuildingTypeManager(), and BuildingType::GetCheckSum().
The documentation for this class was generated from the following files:
Building.h
Building.cpp