FreeOrion: ServerConnectWnd Class Reference
ServerConnectWnd Class Reference
#include <ServerConnectWnd.h>
Public Member Functions
Structors
ServerConnectWnd ()
Mutators
void ModalInit () override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Accessors
const std::pair< std::string, std::string > & Result () const
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide (bool children=true) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show (bool children=true) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init (const std::string &t)
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (GG::Wnd *wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Private Member Functions
void CancelClicked ()
void EnableDisableControls ()
void IPAddressEdited (const std::string &str)
void OkClicked ()
void PopulateServerList ()
void ServerSelected (const GG::ListBox::SelectionSet &selections)
Private Attributes
GG::Button * m_cancel_bn
GG::Button * m_find_LAN_servers_bn
GG::RadioButtonGroup * m_host_or_join_radio_group
GG::Label * m_internet_game_label
GG::Edit * m_IP_address_edit
GG::Label * m_LAN_game_label
GG::Button * m_ok_bn
GG::Edit * m_player_name_edit
std::pair< std::string, std::string > m_result
GG::ListBox * m_servers_lb
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "UI.windows."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
GG::Button * m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
CUI_MinRestoreButton * m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
CUI_PinButton * m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
server connections window
Constructor & Destructor Documentation
ServerConnectWnd::ServerConnectWnd ()
References CancelClicked(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::CONTROL_MARGIN, EnableDisableControls(), OptionsDB::Get(), GetOptionsDB(), IPAddressEdited(), m_cancel_bn, m_find_LAN_servers_bn, m_host_or_join_radio_group, m_internet_game_label, m_IP_address_edit, m_LAN_game_label, m_ok_bn, m_player_name_edit, m_servers_lb, OkClicked(), PopulateServerList(), CUIWnd::ResetDefaultPosition(), ServerSelected(), and UserString().
Member Function Documentation
GG::Rect ServerConnectWnd::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), anonymous_namespace{ServerConnectWnd.cpp}::WINDOW_HEIGHT(), and anonymous_namespace{ServerConnectWnd.cpp}::WINDOW_WIDTH().
void ServerConnectWnd::CancelClicked () inline private
References CUIWnd::CloseClicked(), and EnableDisableControls().
Referenced by KeyPress(), and ServerConnectWnd().
void ServerConnectWnd::EnableDisableControls () private
References m_find_LAN_servers_bn, m_host_or_join_radio_group, m_internet_game_label, m_IP_address_edit, m_LAN_game_label, m_ok_bn, m_player_name_edit, m_servers_lb, and anonymous_namespace{ServerConnectWnd.cpp}::NameOK().
Referenced by CancelClicked(), IPAddressEdited(), ServerConnectWnd(), and ServerSelected().
void ServerConnectWnd::IPAddressEdited (const std::string & str) private
References EnableDisableControls(), m_servers_lb, and ServerSelected().
Referenced by ServerConnectWnd().
void ServerConnectWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References CancelClicked(), m_ok_bn, and OkClicked().
void ServerConnectWnd::ModalInit () override
References m_player_name_edit.
void ServerConnectWnd::OkClicked () private
References CUIWnd::CloseClicked(), OptionsDB::Commit(), GetOptionsDB(), m_host_or_join_radio_group, m_IP_address_edit, m_player_name_edit, m_result, m_servers_lb, and OptionsDB::Set().
Referenced by KeyPress(), and ServerConnectWnd().
void ServerConnectWnd::PopulateServerList () private
References ClientNetworking::DiscoverLANServerNames(), HumanClientApp::GetApp(), m_servers_lb, and ClientApp::Networking().
Referenced by ServerConnectWnd().
const std::pair< std::string, std::string > & ServerConnectWnd::Result () const
returns a the player's name (.first) and the location of the server (.second – IP address or name), or "" if none was selected
References m_result.
Referenced by HumanClientApp::MultiPlayerGame().
void ServerConnectWnd::ServerSelected (const GG::ListBox::SelectionSet & selections) private
References EnableDisableControls(), and m_IP_address_edit.
Referenced by IPAddressEdited(), and ServerConnectWnd().
Member Data Documentation
GG::Button* ServerConnectWnd::m_cancel_bn private
Referenced by ServerConnectWnd().
GG::Button* ServerConnectWnd::m_find_LAN_servers_bn private
Referenced by EnableDisableControls(), and ServerConnectWnd().
GG::RadioButtonGroup* ServerConnectWnd::m_host_or_join_radio_group private
Referenced by EnableDisableControls(), OkClicked(), and ServerConnectWnd().
GG::Label* ServerConnectWnd::m_internet_game_label private
Referenced by EnableDisableControls(), and ServerConnectWnd().
GG::Edit* ServerConnectWnd::m_IP_address_edit private
Referenced by EnableDisableControls(), OkClicked(), ServerConnectWnd(), and ServerSelected().
GG::Label* ServerConnectWnd::m_LAN_game_label private
Referenced by EnableDisableControls(), and ServerConnectWnd().
GG::Button* ServerConnectWnd::m_ok_bn private
Referenced by EnableDisableControls(), KeyPress(), and ServerConnectWnd().
GG::Edit* ServerConnectWnd::m_player_name_edit private
Referenced by EnableDisableControls(), ModalInit(), OkClicked(), and ServerConnectWnd().
std::pair<std::string, std::string> ServerConnectWnd::m_result private
Referenced by OkClicked(), and Result().
GG::ListBox* ServerConnectWnd::m_servers_lb private
Referenced by EnableDisableControls(), IPAddressEdited(), OkClicked(), PopulateServerList(), and ServerConnectWnd().
The documentation for this class was generated from the following files:
ServerConnectWnd.h
ServerConnectWnd.cpp