FreeOrion: Process::Impl Class Reference
Process::Impl Class Reference
Public Member Functions
Impl (const std::string &cmd, const std::vector< std::string > &argv)
~Impl ()
void Free ()
void Kill ()
bool SetLowPriority (bool low)
bool Terminate ()
Private Attributes
bool m_free = false
pid_t m_process_id
Constructor & Destructor Documentation
Impl()
Process::Impl::Impl (const std::string & cmd, const std::vector< std::string > & argv)
Referenced by Process::Free().
~Impl()
Process::Impl::~Impl ()
References Process::Kill().
Referenced by Process::Free().
Member Function Documentation
Free()
void Process::Impl::Free ()
Kill()
void Process::Impl::Kill ()
References DebugLogger.
Referenced by Process::Free().
SetLowPriority()
bool Process::Impl::SetLowPriority (bool low)
Referenced by Process::Free().
Terminate()
bool Process::Impl::Terminate ()
References DebugLogger, and WarnLogger.
Referenced by Process::Free().
Member Data Documentation
m_free
bool Process::Impl::m_free = false private
m_process_id
pid_t Process::Impl::m_process_id private
The documentation for this class was generated from the following file:
Process.cpp