FreeOrion: FleetButton Class Reference
FleetButton Class Reference
#include <FleetButton.h>
Public Types
enum SizeType {
FLEET_BUTTON_NONE, FLEET_BUTTON_TINY, FLEET_BUTTON_SMALL, FLEET_BUTTON_MEDIUM,
FLEET_BUTTON_LARGE
}
Public Member Functions
Structors
FleetButton (const std::vector< int > &fleet_IDs, SizeType size_type=FLEET_BUTTON_LARGE)
FleetButton (int fleet_id, SizeType size_type=FLEET_BUTTON_LARGE)
void CompleteConstruction () override
virtual ~FleetButton ()
Accessors
bool InWindow (const GG::Pt &pt) const override
const std::vector< int > & Fleets () const
returns the fleets represented by this control
bool Selected () const
returns whether this button has been marked selected
Static Public Member Functions
static void PlayFleetButtonOpenSound ()
static void PlayFleetButtonRolloverSound ()
Private Member Functions
void LayoutIcons ()
Private Attributes
bool m_fleet_blockaded
std::vector< int > m_fleets
the fleets represented by this button
std::vector< std::shared_ptr< GG::StaticGraphic > > m_icons
std::shared_ptr< ScanlineControl > m_scanline_control
bool m_selected
should this button render itself specially to show that it is selected?
std::shared_ptr< RotatingGraphic > m_selection_indicator
Mutators
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
void SetSelected (bool selected=true)
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
void RenderUnpressed () override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
void RenderPressed () override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
void RenderRollover () override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
Detailed Description
represents one or more fleets of an empire at a location on the map.
Member Enumeration Documentation
enum FleetButton::SizeType
Enumerator
FLEET_BUTTON_NONE
FLEET_BUTTON_TINY
FLEET_BUTTON_SMALL
FLEET_BUTTON_MEDIUM
FLEET_BUTTON_LARGE
Constructor & Destructor Documentation
FleetButton::FleetButton (const std::vector< int > & fleet_IDs, SizeType size_type = FLEET_BUTTON_LARGE)
References ALL_EMPIRES, ClientApp::EmpireID(), ErrorLogger, FleetBlockadedIcon(), FleetHeadIcons(), FleetSelectionIndicatorIcon(), FleetSizeIcon(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), GetEmpire(), GetFleet(), ClientUI::GetMapWnd(), GetOptionsDB(), GetShip(), GetUniverseObject(), INVALID_OBJECT_ID, LayoutIcons(), m_fleet_blockaded, m_fleets, m_icons, m_scanline_control, m_selection_indicator, ClientUI::SystemSelectionIndicatorRPM(), and anonymous_namespace{FleetButton.cpp}::TWO_PI.
FleetButton::FleetButton (int fleet_id, SizeType size_type = FLEET_BUTTON_LARGE)
FleetButton::~FleetButton () virtual
Member Function Documentation
void FleetButton::CompleteConstruction () override
References ALL_EMPIRES, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetOptionsDB(), GetUniverse(), m_fleets, m_icons, and m_scanline_control.
const std::vector<int>& FleetButton::Fleets () const inline
returns the fleets represented by this control
References m_fleets.
Referenced by MapWnd::FleetButtonLeftClicked(), and MapWnd::FleetButtonRightClicked().
bool FleetButton::InWindow (const GG::Pt & pt) const override
Returns true if pt is within or over the button.
void FleetButton::LayoutIcons () private
References ALL_EMPIRES, AIInterface::EmpireID(), OptionsDB::Get(), HumanClientApp::GetApp(), GetFleet(), GetOptionsDB(), GetSystem(), m_fleet_blockaded, m_fleets, m_icons, m_selection_indicator, and UserString().
Referenced by FleetButton(), Selected(), SetSelected(), and SizeMove().
void FleetButton::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
References ClientUI::GetClientUI(), ClientUI::GetMapWnd(), and PlayFleetButtonRolloverSound().
Referenced by Selected().
void FleetButton::PlayFleetButtonOpenSound () static
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by Selected(), and MapWnd::SelectFleet().
void FleetButton::PlayFleetButtonRolloverSound () static
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by MouseHere(), and Selected().
void FleetButton::RenderPressed () override protected
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
References CircleArc(), RenderUnpressed(), and anonymous_namespace{FleetButton.cpp}::TWO_PI.
Referenced by Selected().
void FleetButton::RenderRollover () override protected
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
References CircleArc(), RenderUnpressed(), and anonymous_namespace{FleetButton.cpp}::TWO_PI.
Referenced by Selected().
void FleetButton::RenderUnpressed () override protected
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
Referenced by RenderPressed(), RenderRollover(), and Selected().
bool FleetButton::Selected () const inline
returns whether this button has been marked selected
References LayoutIcons(), m_selected, MouseHere(), PlayFleetButtonOpenSound(), PlayFleetButtonRolloverSound(), RenderPressed(), RenderRollover(), RenderUnpressed(), SetSelected(), and SizeMove().
void FleetButton::SetSelected (bool selected = true)
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
References LayoutIcons(), m_selected, and m_selection_indicator.
Referenced by Selected().
void FleetButton::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
sets selection status of button. if selected = true, marks button as selected. otherwise marks button as not selected
References LayoutIcons().
Referenced by Selected().
Member Data Documentation
bool FleetButton::m_fleet_blockaded private
Referenced by FleetButton(), and LayoutIcons().
std::vector<int> FleetButton::m_fleets private
the fleets represented by this button
Referenced by CompleteConstruction(), FleetButton(), Fleets(), and LayoutIcons().
std::vector<std::shared_ptr<GG::StaticGraphic> > FleetButton::m_icons private
Referenced by CompleteConstruction(), FleetButton(), and LayoutIcons().
std::shared_ptr<ScanlineControl> FleetButton::m_scanline_control private
Referenced by CompleteConstruction(), and FleetButton().
bool FleetButton::m_selected private
should this button render itself specially to show that it is selected?
Referenced by Selected(), and SetSelected().
std::shared_ptr<RotatingGraphic> FleetButton::m_selection_indicator private
Referenced by FleetButton(), LayoutIcons(), and SetSelected().
The documentation for this class was generated from the following files:
FleetButton.h
FleetButton.cpp