FreeOrion: Tech Class Reference
Tech Class Reference
encasulates the data for a single FreeOrion technology
#include <Tech.h>
Classes
struct TechInfo
Helper struct for parsing tech definitions.
Public Member Functions
Tech (std::string &&name, std::string &&description, std::string &&short_description, std::string &&category, std::unique_ptr< ValueRef::ValueRef< double >> &&research_cost, std::unique_ptr< ValueRef::ValueRef< int >> &&research_turns, bool researchable, std::set< std::string > &&tags, std::vector< std::shared_ptr< Effect::EffectsGroup >> &&effects, std::set< std::string > &&prerequisites, std::vector< UnlockableItem > &&unlocked_items, std::string &&graphic)
Tech (TechInfo &&tech_info, std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, std::set< std::string > &&prerequisites, std::vector< UnlockableItem > &&unlocked_items, std::string &&graphic)
basic ctor taking helper struct to reduce number of direct parameters in order to making parsing work.
~Tech ()
const std::string & Category () const
retursn the name of the category to which this tech belongs
const std::string & Description () const
Returns the text description of this tech.
std::string Dump (unsigned short ntabs=0) const
Returns a text representation of this object.
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
returns the effects that are applied to the discovering empire's capital when this tech is researched; not all techs have effects, in which case this returns 0
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
const std::string & Graphic () const
returns the name of the grapic file for this tech
const std::string & Name () const
returns name of this tech
float PerTurnCost (int empire_id) const
returns the maximum number of RPs per turn allowed to be spent on researching this tech
const std::set< std::string > & Prerequisites () const
returns the set of names of all techs required before this one can be researched
bool Researchable () const
returns whether this tech is researchable by players and appears on the tech tree
float ResearchCost (int empire_id) const
returns the total research cost in RPs required to research this tech
int ResearchTime (int empire_id) const
returns the number of turns required to research this tech, if ResearchCost() RPs are spent per turn
const std::string & ShortDescription () const
Returns the single-line short text description of this tech.
const std::set< std::string > & Tags () const
const std::vector< UnlockableItem > & UnlockedItems () const
Returns the set all items that are unlocked by researching this tech.
const std::set< std::string > & UnlockedTechs () const
returns the set of names of all techs for which this one is a prerequisite
Private Member Functions
Tech (const Tech &)
void Init ()
const Tech & operator= (const Tech &)
Private Attributes
std::string m_category
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::string m_graphic
std::string m_name
std::set< std::string > m_prerequisites
std::unique_ptr< ValueRef::ValueRef< double > > m_research_cost
std::unique_ptr< ValueRef::ValueRef< int > > m_research_turns
bool m_researchable = false
std::string m_short_description
std::set< std::string > m_tags
std::vector< UnlockableItem > m_unlocked_items
std::set< std::string > m_unlocked_techs
Friends
class TechManager
Detailed Description
encasulates the data for a single FreeOrion technology
Constructor & Destructor Documentation
Tech() [1/3]
Tech::Tech (std::string && name, std::string && description, std::string && short_description, std::string && category, std::unique_ptr< ValueRef::ValueRef< double >> && research_cost, std::unique_ptr< ValueRef::ValueRef< int >> && research_turns, bool researchable, std::set< std::string > && tags, std::vector< std::shared_ptr< Effect::EffectsGroup >> && effects, std::set< std::string > && prerequisites, std::vector< UnlockableItem > && unlocked_items, std::string && graphic)
References Init(), and m_tags.
Tech() [2/3]
Tech::Tech (TechInfo && tech_info, std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, std::set< std::string > && prerequisites, std::vector< UnlockableItem > && unlocked_items, std::string && graphic)
basic ctor taking helper struct to reduce number of direct parameters in order to making parsing work.
References Init(), m_effects, and m_tags.
~Tech()
Tech::~Tech ()
Tech() [3/3]
Tech::Tech (const Tech &) private
Member Function Documentation
Category()
const std::string& Tech::Category () const inline
retursn the name of the category to which this tech belongs
Referenced by TechTreeLayout::Node::AddChild(), TechTreeWnd::CenterOnTech(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), TechTreeLayout::DoLayout(), TechTreeLayout::Node::operator<(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), ClientUI::TechIcon(), TechRowBrowseWnd(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), TechTreeWnd::TechListBox::TechRow::Update(), and FreeOrionPython::WrapEmpire().
Description()
const std::string& Tech::Description () const inline
Returns the text description of this tech.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and FreeOrionPython::WrapEmpire().
Dump()
std::string Tech::Dump (unsigned short ntabs = 0) const
Returns a text representation of this object.
References DumpIndent(), m_category, m_description, m_effects, m_graphic, m_name, m_prerequisites, m_research_cost, m_research_turns, m_short_description, and m_unlocked_items.
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& Tech::Effects () const inline
returns the effects that are applied to the discovering empire's capital when this tech is researched; not all techs have effects, in which case this returns 0
Referenced by Universe::GetEffectsAndTargets(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag().
GetCheckSum()
unsigned int Tech::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_category, m_description, m_effects, m_graphic, m_name, m_prerequisites, m_research_cost, m_research_turns, m_researchable, m_short_description, m_tags, m_unlocked_items, m_unlocked_techs, and TechManager::s_instance.
Graphic()
const std::string& Tech::Graphic () const inline
returns the name of the grapic file for this tech
Referenced by ClientUI::TechIcon().
Init()
void Tech::Init () private
References m_effects, m_name, m_research_cost, and m_research_turns.
Referenced by Tech().
Name()
const std::string& Tech::Name () const inline
returns name of this tech
Referenced by TechManager::AllChildren(), TechManager::FindFirstDependencyCycle(), anonymous_namespace{Tech.cpp}::NextTechs(), EncyclopediaDetailPanel::SetItem(), and FreeOrionPython::WrapEmpire().
operator=()
const Tech& Tech::operator= (const Tech &) private
PerTurnCost()
float Tech::PerTurnCost (int empire_id) const
returns the maximum number of RPs per turn allowed to be spent on researching this tech
References ResearchCost(), and ResearchTime().
Referenced by anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), TechRowBrowseWnd(), and FreeOrionPython::WrapEmpire().
Prerequisites()
const std::set<std::string>& Tech::Prerequisites () const inline
returns the set of names of all techs required before this one can be researched
Referenced by TechManager::FindFirstDependencyCycle(), anonymous_namespace{Tech.cpp}::NextTechs(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), TechManager::RecursivePrereqs(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), TechRowBrowseWnd(), ResearchQueue::Update(), and FreeOrionPython::WrapEmpire().
Researchable()
bool Tech::Researchable () const inline
returns whether this tech is researchable by players and appears on the tech tree
Referenced by anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), TechRowBrowseWnd(), and anonymous_namespace{TechTreeWnd.cpp}::TechVisible().
ResearchCost()
float Tech::ResearchCost (int empire_id) const
returns the total research cost in RPs required to research this tech
References ALL_EMPIRES, anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_COST, Empires(), GetGameRules(), EmpireManager::GetSource(), and m_research_cost.
Referenced by anonymous_namespace{Tech.cpp}::Cheapest(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), PerTurnCost(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), TechManager::RecursivePrereqs(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), anonymous_namespace{ResearchQueue.cpp}::SetTechQueueElementSpending(), TechRowBrowseWnd(), ResearchQueue::Update(), TechTreeWnd::TechListBox::TechRow::Update(), and FreeOrionPython::WrapEmpire().
ResearchTime()
int Tech::ResearchTime (int empire_id) const
returns the number of turns required to research this tech, if ResearchCost() RPs are spent per turn
References ALL_EMPIRES, anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_TURNS, Empires(), GetGameRules(), EmpireManager::GetSource(), and m_research_turns.
Referenced by TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), PerTurnCost(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), anonymous_namespace{ResearchQueue.cpp}::SetTechQueueElementSpending(), TechRowBrowseWnd(), ResearchQueue::Update(), TechTreeWnd::TechListBox::TechRow::Update(), and FreeOrionPython::WrapEmpire().
ShortDescription()
const std::string& Tech::ShortDescription () const inline
Returns the single-line short text description of this tech.
References Effect::Dump().
Referenced by TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), TechRowBrowseWnd(), and FreeOrionPython::WrapEmpire().
Tags()
const std::set<std::string>& Tech::Tags () const inline
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet().
UnlockedItems()
const std::vector<UnlockableItem>& Tech::UnlockedItems () const inline
Returns the set all items that are unlocked by researching this tech.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and FreeOrionPython::WrapEmpire().
UnlockedTechs()
const std::set<std::string>& Tech::UnlockedTechs () const inline
returns the set of names of all techs for which this one is a prerequisite
Referenced by TechManager::AllChildren(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), ResearchQueue::Update(), and FreeOrionPython::WrapEmpire().
Friends And Related Function Documentation
TechManager
friend class TechManager friend
Member Data Documentation
m_category
std::string Tech::m_category private
Referenced by Dump(), and GetCheckSum().
m_description
std::string Tech::m_description private
Referenced by Dump(), and GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > Tech::m_effects private
Referenced by Dump(), GetCheckSum(), Init(), and Tech().
m_graphic
std::string Tech::m_graphic private
Referenced by Dump(), and GetCheckSum().
m_name
std::string Tech::m_name private
Referenced by Dump(), GetCheckSum(), and Init().
m_prerequisites
std::set<std::string> Tech::m_prerequisites private
Referenced by Dump(), and GetCheckSum().
m_research_cost
std::unique_ptr<ValueRef::ValueRef<double> > Tech::m_research_cost private
Referenced by Dump(), GetCheckSum(), Init(), and ResearchCost().
m_research_turns
std::unique_ptr<ValueRef::ValueRef<int> > Tech::m_research_turns private
Referenced by Dump(), GetCheckSum(), Init(), and ResearchTime().
m_researchable
bool Tech::m_researchable = false private
Referenced by GetCheckSum().
m_short_description
std::string Tech::m_short_description private
Referenced by Dump(), and GetCheckSum().
m_tags
std::set<std::string> Tech::m_tags private
Referenced by GetCheckSum(), and Tech().
m_unlocked_items
std::vector<UnlockableItem> Tech::m_unlocked_items private
Referenced by Dump(), and GetCheckSum().
m_unlocked_techs
std::set<std::string> Tech::m_unlocked_techs private
Referenced by GetCheckSum().
The documentation for this class was generated from the following files:
Tech.h
Tech.cpp