FreeOrion: PartType Class Reference
PartType Class Reference
A type of ship part.
#include <ShipDesign.h>
Public Member Functions
Structors
PartType ()
PartType (ShipPartClass part_class, double capacity, double stat2, CommonParams &common_params, const MoreCommonParams &more_common_params, std::vector< ShipSlotType > mountable_slot_types, const std::string &icon, bool add_standard_capacity_effect=true, std::unique_ptr< Condition::ConditionBase > &&combat_targets=nullptr)
~PartType ()
Accessors
const std::string & Name () const
returns name of part
const std::string & Description () const
returns name of part
ShipPartClass Class () const
returns that class of part that this is.
float Capacity () const
returns name of part
std::string CapacityDescription () const
returns a translated description of the part capacity, with numeric value
float SecondaryStat () const
returns name of part
bool CanMountInSlotType (ShipSlotType slot_type) const
returns true if this part can be placed in a slot of the indicated type
const Condition::ConditionBase * CombatTargets () const
returns the condition for possible targets. may be nullptr if no condition was specified.
const std::vector< ShipSlotType > & MountableSlotTypes () const
returns name of part
bool ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
float ProductionCost (int empire_id, int location_id) const
returns the number of production points required to produce this part
int ProductionTime (int empire_id, int location_id) const
returns the number of turns required to produce this part
bool Producible () const
returns whether this part type is producible by players and appears on the design screen
const CommonParams::ConsumptionMap< MeterType > & ProductionMeterConsumption () const
returns name of part
const CommonParams::ConsumptionMap< std::string > & ProductionSpecialConsumption () const
returns name of part
const std::set< std::string > & Tags () const
returns name of part
const Condition::ConditionBase * Location () const
returns the condition that determines the locations where ShipDesign containing part can be produced
const std::set< std::string > & Exclusions () const
returns the names of other content that cannot be used in the same ship design as this part
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
Returns the EffectsGroups that encapsulate the effects this part has.
const std::string & Icon () const
returns icon graphic that represents part in UI
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Private Member Functions
void Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_add_standard_capacity_effect = false
float m_capacity = 0.0f
ShipPartClass m_class
std::unique_ptr< Condition::ConditionBase > m_combat_targets
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::set< std::string > m_exclusions
std::string m_icon
std::unique_ptr< Condition::ConditionBase > m_location
std::vector< ShipSlotType > m_mountable_slot_types
std::string m_name
bool m_producible = false
std::unique_ptr< ValueRef::ValueRefBase< double > > m_production_cost
CommonParams::ConsumptionMap< MeterType > m_production_meter_consumption
CommonParams::ConsumptionMap< std::string > m_production_special_consumption
std::unique_ptr< ValueRef::ValueRefBase< int > > m_production_time
float m_secondary_stat = 0.0f
std::set< std::string > m_tags
Friends
class boost::serialization::access
Detailed Description
A type of ship part.
Constructor & Destructor Documentation
PartType() [1/2]
PartType::PartType ()
PartType() [2/2]
PartType::PartType (ShipPartClass part_class, double capacity, double stat2, CommonParams & common_params, const MoreCommonParams & more_common_params, std::vector< ShipSlotType > mountable_slot_types, const std::string & icon, bool add_standard_capacity_effect = true, std::unique_ptr< Condition::ConditionBase > && combat_targets = nullptr)
References CommonParams::effects, Init(), m_add_standard_capacity_effect, m_capacity, m_class, m_description, m_icon, m_name, m_producible, m_secondary_stat, m_tags, CommonParams::tags, and TraceLogger.
~PartType()
PartType::~PartType ()
Member Function Documentation
CanMountInSlotType()
bool PartType::CanMountInSlotType (ShipSlotType slot_type) const
returns true if this part can be placed in a slot of the indicated type
References m_mountable_slot_types.
Referenced by DesignWnd::MainPanel::FindEmptySlotForPart(), DesignWnd::MainPanel::FindSlotForPartWithSwapping(), anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), DesignWnd::MainPanel::SetPart(), and FreeOrionPython::WrapUniverseClasses().
Capacity()
float PartType::Capacity () const
returns name of part
returns description string, generally a UserString key.
References GameRules::Get(), GetGameRules(), m_capacity, m_class, PC_ARMOUR, and PC_SPEED.
Referenced by ShipDesign::AdjustedAttack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStatsP(), ShipDesign::BuildStatCaches(), CapacityDescription(), ShipDesign::Defense(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{DesignWnd.cpp}::GetMainStat(), and FreeOrionPython::WrapUniverseClasses().
CapacityDescription()
std::string PartType::CapacityDescription () const
returns a translated description of the part capacity, with numeric value
References Capacity(), FlexibleFormat(), m_class, PC_COLONY, PC_DETECTION, PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, PC_FUEL, PC_SHIELD, PC_TROOPS, SecondaryStat(), and UserString().
Referenced by PartControl::CompleteConstruction(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag().
Class()
ShipPartClass PartType::Class () const inline
returns that class of part that this is.
Referenced by ShipDesign::AdjustedAttack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStatsP(), ShipDesign::BuildStatCaches(), Ship::ColonyCapacity(), ShipDesign::Defense(), ValueRef::ComplexVariable< T >::Eval(), Ship::FighterCount(), Ship::FighterMax(), DesignWnd::MainPanel::FindEmptySlotForPart(), DesignWnd::MainPanel::FindSlotForPartWithSwapping(), anonymous_namespace{DesignWnd.cpp}::GetMainStat(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), Ship::Ship(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), ShipDesign::Weapons(), and FreeOrionPython::WrapUniverseClasses().
CombatTargets()
const Condition::ConditionBase* PartType::CombatTargets () const inline
returns the condition for possible targets. may be nullptr if no condition was specified.
Referenced by anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths().
Description()
const std::string& PartType::Description () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by PartControl::CompleteConstruction(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), and SlotControl::SetPart().
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& PartType::Effects () const inline
Returns the EffectsGroups that encapsulate the effects this part has.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag().
Exclusions()
const std::set<std::string>& PartType::Exclusions () const inline
returns the names of other content that cannot be used in the same ship design as this part
Referenced by DesignWnd::MainPanel::DesignChanged(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag().
GetCheckSum()
unsigned int PartType::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_add_standard_capacity_effect, m_capacity, m_class, m_description, m_effects, m_exclusions, m_icon, m_location, m_mountable_slot_types, m_name, m_producible, m_production_cost, m_production_meter_consumption, m_production_special_consumption, m_production_time, m_secondary_stat, and m_tags.
Icon()
const std::string& PartType::Icon () const inline
returns icon graphic that represents part in UI
Referenced by ClientUI::PartIcon().
Init()
void PartType::Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects) private
References anonymous_namespace{ShipDesign.cpp}::IncreaseMeter(), m_add_standard_capacity_effect, m_capacity, m_class, m_combat_targets, m_effects, m_location, m_name, m_production_cost, m_production_time, m_secondary_stat, METER_CAPACITY, METER_DETECTION, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_SPEED, METER_STEALTH, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, PC_ARMOUR, PC_COLONY, PC_DETECTION, PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, PC_FUEL, PC_INDUSTRY, PC_RESEARCH, PC_SHIELD, PC_SPEED, PC_STEALTH, PC_TRADE, and PC_TROOPS.
Referenced by PartType().
Location()
const Condition::ConditionBase* PartType::Location () const inline
returns the condition that determines the locations where ShipDesign containing part can be produced
Referenced by PartALocationSubsumesPartB(), ShipDesign::ProductionLocation(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag().
MountableSlotTypes()
const std::vector<ShipSlotType>& PartType::MountableSlotTypes () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by FreeOrionPython::WrapUniverseClasses().
Name()
const std::string& PartType::Name () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by DesignWnd::MainPanel::AddPart(), DesignWnd::MainPanel::ClearPart(), PartControl::CompleteConstruction(), DesignWnd::MainPanel::FindEmptySlotForPart(), DesignWnd::MainPanel::FindSlotForPartWithSwapping(), DesignWnd::PartPalette::HandlePartTypeClicked(), DesignWnd::PartPalette::HandlePartTypeRightClicked(), PartALocationSubsumesPartB(), DesignWnd::MainPanel::Parts(), PartsListBox::Populate(), EncyclopediaDetailPanel::SetItem(), SlotControl::SetPart(), Ship::Ship(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), and FreeOrionPython::WrapUniverseClasses().
Producible()
bool PartType::Producible () const inline
returns whether this part type is producible by players and appears on the design screen
Referenced by Empire::AddPartType(), and ShipDesign::BuildStatCaches().
ProductionCost()
float PartType::ProductionCost (int empire_id, int location_id) const
returns the number of production points required to produce this part
References Empires(), GetGameRules(), EmpireManager::GetSource(), GetUniverseObject(), and m_production_cost.
Referenced by PartsListBox::CullSuperfluousParts(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), and FreeOrionPython::WrapUniverseClasses().
ProductionCostTimeLocationInvariant()
bool PartType::ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
References GetGameRules(), m_production_cost, and m_production_time.
Referenced by FreeOrionPython::WrapUniverseClasses().
ProductionMeterConsumption()
const CommonParams::ConsumptionMap<MeterType>& PartType::ProductionMeterConsumption () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by ProductionQueue::ProductionItem::CompletionMeterConsumption().
ProductionSpecialConsumption()
const CommonParams::ConsumptionMap<std::string>& PartType::ProductionSpecialConsumption () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by ProductionQueue::ProductionItem::CompletionSpecialConsumption().
ProductionTime()
int PartType::ProductionTime (int empire_id, int location_id) const
returns the number of turns required to produce this part
References Empires(), GetGameRules(), EmpireManager::GetSource(), GetUniverseObject(), and m_production_time.
Referenced by PartsListBox::CullSuperfluousParts(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), and FreeOrionPython::WrapUniverseClasses().
SecondaryStat()
float PartType::SecondaryStat () const
returns name of part
returns description string, generally a UserString key.
References m_secondary_stat.
Referenced by ShipDesign::AdjustedAttack(), ShipDesign::BuildStatCaches(), CapacityDescription(), ValueRef::ComplexVariable< T >::Eval(), and FreeOrionPython::WrapUniverseClasses().
serialize()
template<class Archive > void PartType::serialize (Archive & ar, const unsigned int version) private
Tags()
const std::set<std::string>& PartType::Tags () const inline
returns name of part
returns description string, generally a UserString key.
Referenced by Ship::HasTag().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_add_standard_capacity_effect
bool PartType::m_add_standard_capacity_effect = false private
Referenced by GetCheckSum(), Init(), and PartType().
m_capacity
float PartType::m_capacity = 0.0f private
Referenced by Capacity(), GetCheckSum(), Init(), and PartType().
m_class
ShipPartClass PartType::m_class private
Referenced by Capacity(), CapacityDescription(), GetCheckSum(), Init(), and PartType().
m_combat_targets
std::unique_ptr<Condition::ConditionBase> PartType::m_combat_targets private
Referenced by Init().
m_description
std::string PartType::m_description private
Referenced by GetCheckSum(), and PartType().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > PartType::m_effects private
Referenced by GetCheckSum(), and Init().
m_exclusions
std::set<std::string> PartType::m_exclusions private
Referenced by GetCheckSum().
m_icon
std::string PartType::m_icon private
Referenced by GetCheckSum(), and PartType().
m_location
std::unique_ptr<Condition::ConditionBase> PartType::m_location private
Referenced by GetCheckSum(), and Init().
m_mountable_slot_types
std::vector<ShipSlotType> PartType::m_mountable_slot_types private
Referenced by CanMountInSlotType(), and GetCheckSum().
m_name
std::string PartType::m_name private
Referenced by GetCheckSum(), Init(), and PartType().
m_producible
bool PartType::m_producible = false private
Referenced by GetCheckSum(), and PartType().
m_production_cost
std::unique_ptr<ValueRef::ValueRefBase<double> > PartType::m_production_cost private
Referenced by GetCheckSum(), Init(), ProductionCost(), and ProductionCostTimeLocationInvariant().
m_production_meter_consumption
CommonParams::ConsumptionMap<MeterType> PartType::m_production_meter_consumption private
Referenced by GetCheckSum().
m_production_special_consumption
CommonParams::ConsumptionMap<std::string> PartType::m_production_special_consumption private
Referenced by GetCheckSum().
m_production_time
std::unique_ptr<ValueRef::ValueRefBase<int> > PartType::m_production_time private
Referenced by GetCheckSum(), Init(), ProductionCostTimeLocationInvariant(), and ProductionTime().
m_secondary_stat
float PartType::m_secondary_stat = 0.0f private
Referenced by GetCheckSum(), Init(), PartType(), and SecondaryStat().
m_tags
std::set<std::string> PartType::m_tags private
Referenced by GetCheckSum(), and PartType().
The documentation for this class was generated from the following files:
ShipDesign.h
ShipDesign.cpp