FreeOrion: anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds Class Reference
anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds Class Reference
LoggersToSinkFrontEnds is used to track all of the global named loggers.
Public Member Functions
void AddOrReplaceLoggerName (const std::string &channel_name, boost::shared_ptr< LoggerTextFileSinkFrontend > front_end=nullptr)
void ConfigureFrontEnds (const boost::shared_ptr< LoggerTextFileSinkFrontend::sink_backend_type > &file_sink_backend)
Configure front ends for any logger with stored configuration functions.
std::vector< std::string > LoggersNames ()
void ShutdownFileSinks ()
void StoreConfigurerWithLoggerName (const std::string &channel_name, const LoggerFileSinkFrontEndConfigurer &configure_front_end)
Store a configuration function configure_front_end to be applied later.
Private Attributes
std::mutex m_mutex = {}
m_mutex serializes access from different threads
std::unordered_map< std::string, LoggerFileSinkFrontEndConfigurer > m_names_to_front_end_configurers = {}
std::unordered_map< std::string, boost::shared_ptr< LoggerTextFileSinkFrontend > > m_names_to_front_ends = {}
Detailed Description
LoggersToSinkFrontEnds is used to track all of the global named loggers.
It maps the names to the sink front ends.
It is used to:
bind their sink front ends to the file logger backend
to provide a complete list of loggers names (i.e. to OptionsDB)
Member Function Documentation
AddOrReplaceLoggerName()
void anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::AddOrReplaceLoggerName (const std::string & channel_name, boost::shared_ptr< LoggerTextFileSinkFrontend > front_end = nullptr) inline
References anonymous_namespace{Logger.cpp}::DisplayName(), boost::get(), and InfoLogger.
Referenced by anonymous_namespace{Logger.cpp}::ConfigureToFileSinkFrontEndCore().
ConfigureFrontEnds()
void anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::ConfigureFrontEnds (const boost::shared_ptr< LoggerTextFileSinkFrontend::sink_backend_type > & file_sink_backend) inline
Configure front ends for any logger with stored configuration functions.
References anonymous_namespace{Logger.cpp}::ConfigureToFileSinkFrontEndCore().
Referenced by InitLoggingSystem().
LoggersNames()
std::vector<std::string> anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::LoggersNames () inline
Referenced by CreatedLoggersNames().
ShutdownFileSinks()
void anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::ShutdownFileSinks () inline
References boost::get().
Referenced by ShutdownLoggingSystemFileSink().
StoreConfigurerWithLoggerName()
void anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::StoreConfigurerWithLoggerName (const std::string & channel_name, const LoggerFileSinkFrontEndConfigurer & configure_front_end) inline
Store a configuration function configure_front_end to be applied later.
Referenced by ApplyConfigurationToFileSinkFrontEnd().
Member Data Documentation
m_mutex
std::mutex anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::m_mutex = {} private
m_mutex serializes access from different threads
m_names_to_front_end_configurers
std::unordered_map<std::string, LoggerFileSinkFrontEndConfigurer> anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::m_names_to_front_end_configurers = {} private
m_names_to_front_ends
std::unordered_map<std::string, boost::shared_ptr<LoggerTextFileSinkFrontend> > anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::m_names_to_front_ends = {} private
The documentation for this class was generated from the following file:
Logger.cpp