FreeOrion: PolicySlotControl Class Reference
PolicySlotControl Class Reference
UI representation and drop-target for policies of a government.
Public Member Functions
void CompleteConstruction () override
Structors
PolicySlotControl ()
PolicySlotControl (const std::string &slot_category, int category_index, unsigned int slot_index)
Accessors
const std::string & SlotCategory () const
const Policy * GetPolicy () const
int CategoryIndex () const
unsigned int SlotIndex () const
Mutators
void StartingChildDragDrop (const GG::Wnd *wnd, const GG::Pt &offset) override
used to programmatically set the PolicyControl in this slot.
void CancellingChildDragDrop (const std::vector< const GG::Wnd *> &wnds) override
used to programmatically set the PolicyControl in this slot.
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
used to programmatically set the PolicyControl in this slot.
void ChildrenDraggedAway (const std::vector< GG::Wnd *> &wnds, const GG::Wnd *destination) override
used to programmatically set the PolicyControl in this slot.
void DragDropEnter (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
used to programmatically set the PolicyControl in this slot.
void DragDropLeave () override
used to programmatically set the PolicyControl in this slot.
void Render () override
used to programmatically set the PolicyControl in this slot.
void Highlight (bool actually=true)
used to programmatically set the PolicyControl in this slot.
void SetPolicy (const std::string &policy_name)
used to programmatically set the PolicyControl in this slot.
void SetPolicy (const Policy *policy)
used to programmatically set the PolicyControl in this slot.
Public Attributes
boost::signals2::signal< void(const Policy *, GG::Flags< GG::ModKey >)> PolicyClickedSignal
boost::signals2::signal< void(const Policy *, bool)> SlotContentsAlteredSignal
emitted when the contents of a slot are altered by the dragging a PolicyControl in or out of the slot.
Protected Member Functions
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
bool EventFilter (GG::Wnd *w, const GG::WndEvent &event) override
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_background = nullptr
int m_category_index = -1
bool m_highlighted = false
std::shared_ptr< PolicyControl > m_policy_control = nullptr
std::string m_slot_category = ""
unsigned int m_slot_index = 0
Detailed Description
UI representation and drop-target for policies of a government.
PolicyControl may be dropped into slots to add the corresponding policies to the government, or the policy may be set programmatically with SetPolicy().
Constructor & Destructor Documentation
PolicySlotControl() [1/2]
PolicySlotControl::PolicySlotControl ()
PolicySlotControl() [2/2]
PolicySlotControl::PolicySlotControl (const std::string & slot_category, int category_index, unsigned int slot_index)
Member Function Documentation
AcceptDrops()
void PolicySlotControl::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
used to programmatically set the PolicyControl in this slot.
References ErrorLogger, and SlotContentsAlteredSignal.
CancellingChildDragDrop()
void PolicySlotControl::CancellingChildDragDrop (const std::vector< const GG::Wnd *> & wnds) override
used to programmatically set the PolicyControl in this slot.
References m_policy_control.
CategoryIndex()
int PolicySlotControl::CategoryIndex () const inline
ChildrenDraggedAway()
void PolicySlotControl::ChildrenDraggedAway (const std::vector< GG::Wnd *> & wnds, const GG::Wnd * destination) override
used to programmatically set the PolicyControl in this slot.
References m_policy_control, and SlotContentsAlteredSignal.
CompleteConstruction()
void PolicySlotControl::CompleteConstruction () override
References GetOptionsDB(), m_background, m_slot_category, anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_HEIGHT(), anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_WIDTH(), anonymous_namespace{GovernmentWnd.cpp}::SlotBackgroundTexture(), and UserString().
DragDropEnter()
void PolicySlotControl::DragDropEnter (const GG::Pt & pt, std::map< const Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
used to programmatically set the PolicyControl in this slot.
References DropsAcceptable(), and m_policy_control.
DragDropLeave()
void PolicySlotControl::DragDropLeave () override
used to programmatically set the PolicyControl in this slot.
References m_policy_control.
DropsAcceptable()
void PolicySlotControl::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const override protected
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), if(), m_policy_control, m_slot_category, anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_DROP_TYPE_STRING, and Empire::PolicyAvailable().
Referenced by DragDropEnter().
EventFilter()
bool PolicySlotControl::EventFilter (GG::Wnd * w, const GG::WndEvent & event) override protected
GetPolicy()
const Policy * PolicySlotControl::GetPolicy () const
References m_policy_control.
Referenced by SetPolicy().
Highlight()
void PolicySlotControl::Highlight (bool actually = true)
used to programmatically set the PolicyControl in this slot.
References m_highlighted.
Render()
void PolicySlotControl::Render () override
used to programmatically set the PolicyControl in this slot.
SetPolicy() [1/2]
void PolicySlotControl::SetPolicy (const std::string & policy_name)
used to programmatically set the PolicyControl in this slot.
References GetPolicy().
SetPolicy() [2/2]
void PolicySlotControl::SetPolicy (const Policy * policy)
used to programmatically set the PolicyControl in this slot.
References Policy::Category(), Policy::Description(), GetOptionsDB(), m_policy_control, Policy::Name(), PolicyClickedSignal, ClientUI::PolicyIcon(), SlotContentsAlteredSignal, and UserString().
SlotCategory()
const std::string& PolicySlotControl::SlotCategory () const inline
References GetPolicy().
SlotIndex()
unsigned int PolicySlotControl::SlotIndex () const inline
References CUIWnd::Render().
StartingChildDragDrop()
void PolicySlotControl::StartingChildDragDrop (const GG::Wnd * wnd, const GG::Pt & offset) override
used to programmatically set the PolicyControl in this slot.
References m_policy_control.
Member Data Documentation
m_background
std::shared_ptr<GG::StaticGraphic> PolicySlotControl::m_background = nullptr private
Referenced by CompleteConstruction().
m_category_index
int PolicySlotControl::m_category_index = -1 private
m_highlighted
bool PolicySlotControl::m_highlighted = false private
Referenced by Highlight().
m_policy_control
std::shared_ptr<PolicyControl> PolicySlotControl::m_policy_control = nullptr private
Referenced by CancellingChildDragDrop(), ChildrenDraggedAway(), DragDropEnter(), DragDropLeave(), DropsAcceptable(), GetPolicy(), SetPolicy(), and StartingChildDragDrop().
m_slot_category
std::string PolicySlotControl::m_slot_category = "" private
Referenced by CompleteConstruction(), and DropsAcceptable().
m_slot_index
unsigned int PolicySlotControl::m_slot_index = 0 private
PolicyClickedSignal
boost::signals2::signal<void (const Policy*, GG::Flags<GG::ModKey>)> PolicySlotControl::PolicyClickedSignal mutable
Referenced by SetPolicy().
SlotContentsAlteredSignal
boost::signals2::signal<void (const Policy*, bool)> PolicySlotControl::SlotContentsAlteredSignal mutable
emitted when the contents of a slot are altered by the dragging a PolicyControl in or out of the slot.
signal should be caught and the slot contents set using SetPolicy accordingly
Referenced by AcceptDrops(), ChildrenDraggedAway(), and SetPolicy().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp