FreeOrion: ResourcePanel Class Reference
ResourcePanel Class Reference
Shows resource meters with meter-bars.
#include <ResourcePanel.h>
Public Member Functions
ResourcePanel (GG::X w, int object_id)
~ResourcePanel ()
void CompleteConstruction () override
void ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
void PreRender () override
void Refresh ()
updates, redoes layout, resizes indicator
int ResourceCenterID () const
void Update ()
updates indicators with values of associated object.
Public Member Functions inherited from AccordionPanel
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
void SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Protected Member Functions
void DoLayout () override
resizes panel and positions widgets
Protected Member Functions inherited from AccordionPanel
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Private Member Functions
void ExpandCollapseButtonPressed ()
toggles panel expanded or collapsed
Private Attributes
std::vector< std::pair< MeterType, std::shared_ptr< StatisticIcon > > > m_meter_stats
Icons for the associated meter type.
std::shared_ptr< MultiIconValueIndicator > m_multi_icon_value_indicator
textually / numerically indicates resource production and construction meter
std::shared_ptr< MultiMeterStatusBar > m_multi_meter_status_bar
graphically indicates meter values
int m_rescenter_id
object id for the ResourceCenter that this panel displays
Static Private Attributes
static std::map< int, bool > s_expanded_map
map indexed by popcenter ID indicating whether the PopulationPanel for each object is expanded (true) or collapsed (false)
Additional Inherited Members
Public Types inherited from AccordionPanel
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Public Attributes inherited from AccordionPanel
ExpandCollapseSignalType ExpandCollapseSignal
Protected Attributes inherited from AccordionPanel
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin = 1
The number of pixels between the expansion button and the client area.
bool m_collapsed = true
std::shared_ptr< GG::Button > m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
GG::Clr m_interior_color
bool m_is_left = false
Is expand button on the left?
Detailed Description
Shows resource meters with meter-bars.
Constructor & Destructor Documentation
ResourcePanel()
ResourcePanel::ResourcePanel (GG::X w, int object_id)
~ResourcePanel()
ResourcePanel::~ResourcePanel ()
Member Function Documentation
CompleteConstruction()
void ResourcePanel::CompleteConstruction () override
References AssociatedMeterType(), AccordionPanel::CompleteConstruction(), anonymous_namespace{ResourcePanel.cpp}::EDGE_PAD(), ErrorLogger, ExpandCollapseButtonPressed(), FlexibleFormat(), ObjectMap::get(), ClientUI::GetClientUI(), AccordionPanel::m_expand_button, m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_rescenter_id, ClientUI::MeterIcon(), anonymous_namespace{ResourcePanel.cpp}::MeterIconSize(), Objects(), Refresh(), s_expanded_map, anonymous_namespace{ServerWrapper.cpp}::SetName(), UserString(), and ClientUI::ZoomToMeterTypeArticle().
DoLayout()
void ResourcePanel::DoLayout () override protected virtual
resizes panel and positions widgets
Reimplemented from AccordionPanel.
References AccordionPanel::DoLayout(), anonymous_namespace{ResourcePanel.cpp}::EDGE_PAD(), AccordionPanel::m_expand_button, m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_rescenter_id, anonymous_namespace{ResourcePanel.cpp}::MeterIconSize(), s_expanded_map, and AccordionPanel::SetCollapsed().
Referenced by PreRender(), and ResourceCenterID().
ExpandCollapse()
void ResourcePanel::ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
References m_rescenter_id, and s_expanded_map.
Referenced by ExpandCollapseButtonPressed(), and ResourceCenterID().
ExpandCollapseButtonPressed()
void ResourcePanel::ExpandCollapseButtonPressed () private
toggles panel expanded or collapsed
References ExpandCollapse(), m_rescenter_id, and s_expanded_map.
Referenced by CompleteConstruction(), and ResourceCenterID().
PreRender()
void ResourcePanel::PreRender () override
References DoLayout(), and Update().
Referenced by ResourceCenterID().
Refresh()
void ResourcePanel::Refresh ()
updates, redoes layout, resizes indicator
References m_meter_stats.
Referenced by CompleteConstruction(), and ResourceCenterID().
ResourceCenterID()
int ResourcePanel::ResourceCenterID () const inline
References DoLayout(), ExpandCollapse(), ExpandCollapseButtonPressed(), m_rescenter_id, PreRender(), Refresh(), and Update().
Update()
void ResourcePanel::Update ()
updates indicators with values of associated object.
Does not do layout and resizing.
References AssociatedMeterType(), ErrorLogger, ObjectMap::get(), m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_rescenter_id, Objects(), and anonymous_namespace{ResourcePanel.cpp}::SortByMeterValue().
Referenced by PreRender(), and ResourceCenterID().
Member Data Documentation
m_meter_stats
std::vector<std::pair<MeterType, std::shared_ptr<StatisticIcon> > > ResourcePanel::m_meter_stats private
Icons for the associated meter type.
Referenced by CompleteConstruction(), DoLayout(), Refresh(), and Update().
m_multi_icon_value_indicator
std::shared_ptr<MultiIconValueIndicator> ResourcePanel::m_multi_icon_value_indicator private
textually / numerically indicates resource production and construction meter
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_multi_meter_status_bar
std::shared_ptr<MultiMeterStatusBar> ResourcePanel::m_multi_meter_status_bar private
graphically indicates meter values
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_rescenter_id
int ResourcePanel::m_rescenter_id private
object id for the ResourceCenter that this panel displays
Referenced by CompleteConstruction(), DoLayout(), ExpandCollapse(), ExpandCollapseButtonPressed(), ResourceCenterID(), and Update().
s_expanded_map
std::map< int, bool > ResourcePanel::s_expanded_map static private
map indexed by popcenter ID indicating whether the PopulationPanel for each object is expanded (true) or collapsed (false)
Referenced by CompleteConstruction(), DoLayout(), ExpandCollapse(), and ExpandCollapseButtonPressed().
The documentation for this class was generated from the following files:
ResourcePanel.h
ResourcePanel.cpp