FreeOrion: ResearchQueueListBox Class Reference
ResearchQueueListBox Class Reference
Public Member Functions
ResearchQueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void CompleteConstruction () override
Public Member Functions inherited from QueueListBox
QueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
void CompleteConstruction () override
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
virtual void EnableOrderIssuing (bool enable=true)
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
boost::signals2::signal< void(GG::ListBox::iterator, bool)> QueueItemPausedSignal
boost::signals2::signal< void()> ShowPediaSignal
Public Attributes inherited from QueueListBox
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
Protected Member Functions
void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
Protected Member Functions inherited from QueueListBox
virtual std::function< void()> DeleteAction (GG::ListBox::iterator it) const
Return a functor that will signal that it should be deleted.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
virtual std::function< void()> MoveToBottomAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the bottom of the list.
virtual std::function< void()> MoveToTopAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the top of the list.
Constructor & Destructor Documentation
ResearchQueueListBox()
ResearchQueueListBox::ResearchQueueListBox (const boost::optional< std::string > & drop_type_str, const std::string & prompt_str) inline
Member Function Documentation
CompleteConstruction()
void ResearchQueueListBox::CompleteConstruction () inline override
References QueueListBox::CompleteConstruction().
ItemRightClickedImpl()
void ResearchQueueListBox::ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) inline override protected virtual
Reimplemented from QueueListBox.
References ErrorLogger, FlexibleFormat(), UserString(), and UserStringExists().
Member Data Documentation
QueueItemPausedSignal
boost::signals2::signal<void (GG::ListBox::iterator, bool)> ResearchQueueListBox::QueueItemPausedSignal
ShowPediaSignal
boost::signals2::signal<void ()> ResearchQueueListBox::ShowPediaSignal
The documentation for this class was generated from the following file:
ResearchWnd.cpp