FreeOrion: Pathfinder::PathfinderImpl Class Reference
Pathfinder::PathfinderImpl Class Reference
Public Member Functions
PathfinderImpl ()
void HandleCacheMiss (size_t ii, distance_matrix_storage< short >::row_ref row) const
When a cache miss occurs fill row with the distances from index ii to every other index.
std::multimap< double, int > ImmediateNeighbors (int system_id, int empire_id=ALL_EMPIRES) const
void InitializeSystemGraph (const std::vector< int > system_ids, int for_empire_id=ALL_EMPIRES)
int JumpDistanceBetweenObjects (int object1_id, int object2_id) const
short JumpDistanceBetweenSystems (int system1_id, int system2_id) const
std::pair< std::list< int >, int > LeastJumpsPath (int system1_id, int system2_id, int empire_id=ALL_EMPIRES, int max_jumps=INT_MAX) const
double LinearDistance (int object1_id, int object2_id) const
int NearestSystemTo (double x, double y) const
boost::unordered_multimap< int, int > Neighbors (int system_id, size_t n_outer=1, size_t n_inner=0) const
void NeighborsCacheHit (boost::unordered_multimap< int, int > &result, size_t _n_outer, size_t _n_inner, size_t ii, distance_matrix_storage< short >::row_ref row) const
When a cache hit occurs use row to populate and return the multimap for Neighbors.
std::pair< std::list< int >, double > ShortestPath (int system1_id, int system2_id, int empire_id=ALL_EMPIRES) const
std::pair< std::list< int >, double > ShortestPath (int system1_id, int system2_id, int empire_id, const Pathfinder::SystemExclusionPredicateType &sys_pred) const
double ShortestPathDistance (int object1_id, int object2_id) const
bool SystemHasVisibleStarlanes (int system_id, int empire_id=ALL_EMPIRES) const
bool SystemsConnected (int system1_id, int system2_id, int empire_id=ALL_EMPIRES) const
void UpdateEmpireVisibilityFilteredSystemGraphs (int for_empire_id=ALL_EMPIRES)
std::unordered_set< int > WithinJumps (size_t jumps, const std::vector< int > &candidates) const
void WithinJumpsCacheHit (std::unordered_set< int > *result, size_t jump_limit, size_t ii, distance_matrix_storage< short >::row_ref row) const
std::pair< std::vector< std::shared_ptr< const UniverseObject > >, std::vector< std::shared_ptr< const UniverseObject > > > WithinJumpsOfOthers (int jumps, const std::vector< std::shared_ptr< const UniverseObject >> &candidates, const std::vector< std::shared_ptr< const UniverseObject >> &stationary) const
bool WithinJumpsOfOthers (int jumps, int system_id, const std::vector< std::shared_ptr< const UniverseObject >> &others) const
Return true if system_id is within jumps of any of others.
void WithinJumpsOfOthersCacheHit (bool &answer, int jumps, const std::vector< std::shared_ptr< const UniverseObject >> &others, size_t ii, distance_matrix_storage< short >::row_ref row) const
If any of others are within jumps of ii return true in answer.
Public Attributes
std::shared_ptr< GraphImpl > m_graph_impl
a graph in which the systems are vertices and the starlanes are edges
boost::unordered_map< int, size_t > m_system_id_to_graph_index
distance_matrix_storage< short > m_system_jumps
indexed by system graph index (not system id), caches the smallest number of jumps to travel between all the systems
Constructor & Destructor Documentation
PathfinderImpl()
Pathfinder::PathfinderImpl::PathfinderImpl () inline
References ALL_EMPIRES, anonymous_namespace{UniverseWrapper.cpp}::JumpDistanceBetweenObjects(), anonymous_namespace{ServerWrapper.cpp}::JumpDistanceBetweenSystems(), anonymous_namespace{UniverseWrapper.cpp}::LeastJumpsPath(), anonymous_namespace{UniverseWrapper.cpp}::LinearDistance(), anonymous_namespace{UniverseWrapper.cpp}::ShortestPath(), and anonymous_namespace{UniverseWrapper.cpp}::ShortestPathDistance().
Member Function Documentation
HandleCacheMiss()
void Pathfinder::PathfinderImpl::HandleCacheMiss (size_t ii, distance_matrix_storage< short >::row_ref row) const
When a cache miss occurs fill row with the distances from index ii to every other index.
HandleCacheMiss requires that row be locked by exterior context.
Referenced by JumpDistanceBetweenSystems(), WithinJumps(), and WithinJumpsOfOthers().
ImmediateNeighbors()
std::multimap< double, int > Pathfinder::PathfinderImpl::ImmediateNeighbors (int system_id, int empire_id = ALL_EMPIRES) const
References ALL_EMPIRES, and SystemPathing::ImmediateNeighborsImpl().
InitializeSystemGraph()
void Pathfinder::PathfinderImpl::InitializeSystemGraph (const std::vector< int > system_ids, int for_empire_id = ALL_EMPIRES)
References EmpireKnownObjects(), ObjectMap::get(), boost::get(), Pathfinder::LinearDistance(), TraceLogger, Pathfinder::UpdateEmpireVisibilityFilteredSystemGraphs(), and anonymous_namespace{Pathfinder.cpp}::WORMHOLE_TRAVEL_DISTANCE.
JumpDistanceBetweenObjects()
int Pathfinder::PathfinderImpl::JumpDistanceBetweenObjects (int object1_id, int object2_id) const
References anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation().
JumpDistanceBetweenSystems()
short Pathfinder::PathfinderImpl::JumpDistanceBetweenSystems (int system1_id, int system2_id) const
References ErrorLogger, and HandleCacheMiss().
LeastJumpsPath()
std::pair< std::list< int >, int > Pathfinder::PathfinderImpl::LeastJumpsPath (int system1_id, int system2_id, int empire_id = ALL_EMPIRES, int max_jumps = INT_MAX) const
References ALL_EMPIRES, ErrorLogger, and SystemPathing::LeastJumpsPathImpl().
LinearDistance()
double Pathfinder::PathfinderImpl::LinearDistance (int object1_id, int object2_id) const
References ErrorLogger, ObjectMap::get(), and Objects().
NearestSystemTo()
int Pathfinder::PathfinderImpl::NearestSystemTo (double x, double y) const
References ObjectMap::all(), INVALID_OBJECT_ID, Objects(), and UniverseObject::X().
Neighbors()
boost::unordered_multimap<int, int> Pathfinder::PathfinderImpl::Neighbors (int system_id, size_t n_outer = 1, size_t n_inner = 0) const
NeighborsCacheHit()
void Pathfinder::PathfinderImpl::NeighborsCacheHit (boost::unordered_multimap< int, int > & result, size_t _n_outer, size_t _n_inner, size_t ii, distance_matrix_storage< short >::row_ref row) const
When a cache hit occurs use row to populate and return the multimap for Neighbors.
ShortestPath() [1/2]
std::pair< std::list< int >, double > Pathfinder::PathfinderImpl::ShortestPath (int system1_id, int system2_id, int empire_id = ALL_EMPIRES) const
References ALL_EMPIRES, ErrorLogger, Pathfinder::LinearDistance(), and SystemPathing::ShortestPathImpl().
ShortestPath() [2/2]
std::pair< std::list< int >, double > Pathfinder::PathfinderImpl::ShortestPath (int system1_id, int system2_id, int empire_id, const Pathfinder::SystemExclusionPredicateType & sys_pred) const
References ALL_EMPIRES, ErrorLogger, Pathfinder::LinearDistance(), and SystemPathing::ShortestPathImpl().
ShortestPathDistance()
double Pathfinder::PathfinderImpl::ShortestPathDistance (int object1_id, int object2_id) const
References ErrorLogger, anonymous_namespace{Pathfinder.cpp}::FleetFromObject(), ObjectMap::get(), UniverseObject::ID(), Objects(), and Pathfinder::ShortestPath().
SystemHasVisibleStarlanes()
bool Pathfinder::PathfinderImpl::SystemHasVisibleStarlanes (int system_id, int empire_id = ALL_EMPIRES) const
References EmpireKnownObjects().
SystemsConnected()
bool Pathfinder::PathfinderImpl::SystemsConnected (int system1_id, int system2_id, int empire_id = ALL_EMPIRES) const
References Pathfinder::LeastJumpsPath(), and TraceLogger.
UpdateEmpireVisibilityFilteredSystemGraphs()
void Pathfinder::PathfinderImpl::UpdateEmpireVisibilityFilteredSystemGraphs (int for_empire_id = ALL_EMPIRES)
References ALL_EMPIRES, and Empires().
WithinJumps()
std::unordered_set< int > Pathfinder::PathfinderImpl::WithinJumps (size_t jumps, const std::vector< int > & candidates) const
References ErrorLogger, HandleCacheMiss(), and WithinJumpsCacheHit().
WithinJumpsCacheHit()
void Pathfinder::PathfinderImpl::WithinJumpsCacheHit (std::unordered_set< int > * result, size_t jump_limit, size_t ii, distance_matrix_storage< short >::row_ref row) const
Referenced by WithinJumps().
WithinJumpsOfOthers() [1/2]
std::pair< std::vector< std::shared_ptr< const UniverseObject > >, std::vector< std::shared_ptr< const UniverseObject > > > Pathfinder::PathfinderImpl::WithinJumpsOfOthers (int jumps, const std::vector< std::shared_ptr< const UniverseObject >> & candidates, const std::vector< std::shared_ptr< const UniverseObject >> & stationary) const
References anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation().
WithinJumpsOfOthers() [2/2]
bool Pathfinder::PathfinderImpl::WithinJumpsOfOthers (int jumps, int system_id, const std::vector< std::shared_ptr< const UniverseObject >> & others) const
Return true if system_id is within jumps of any of others.
References ErrorLogger, HandleCacheMiss(), and WithinJumpsOfOthersCacheHit().
WithinJumpsOfOthersCacheHit()
void Pathfinder::PathfinderImpl::WithinJumpsOfOthersCacheHit (bool & answer, int jumps, const std::vector< std::shared_ptr< const UniverseObject >> & others, size_t ii, distance_matrix_storage< short >::row_ref row) const
If any of others are within jumps of ii return true in answer.
The return value must be in a parameter so that after being bound to answer and jumps the function signature is that required by the cache_hit_handler type.
References anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation().
Referenced by WithinJumpsOfOthers().
Member Data Documentation
m_graph_impl
std::shared_ptr<GraphImpl> Pathfinder::PathfinderImpl::m_graph_impl
a graph in which the systems are vertices and the starlanes are edges
m_system_id_to_graph_index
boost::unordered_map<int, size_t> Pathfinder::PathfinderImpl::m_system_id_to_graph_index
m_system_jumps
distance_matrix_storage<short> Pathfinder::PathfinderImpl::m_system_jumps mutable
indexed by system graph index (not system id), caches the smallest number of jumps to travel between all the systems
The documentation for this class was generated from the following file:
Pathfinder.cpp