FreeOrion: CUIEdit Class Reference
CUIEdit Class Reference
a FreeOrion Edit control
#include <CUIControls.h>
Public Member Functions
void CompleteConstruction () override
Structors
CUIEdit (const std::string &str)
Mutators
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void GainingFocus () override
void LosingFocus () override
void Render () override
virtual bool AutoComplete ()
Public Attributes
boost::signals2::signal< void()> GainingFocusSignal
boost::signals2::signal< void()> LosingFocusSignal
Detailed Description
a FreeOrion Edit control
Constructor & Destructor Documentation
CUIEdit()
CUIEdit::CUIEdit (const std::string & str) explicit
Member Function Documentation
AutoComplete()
virtual bool CUIEdit::AutoComplete () inline virtual
Reimplemented in MessageWndEdit.
Referenced by CompleteConstruction().
CompleteConstruction()
void CUIEdit::CompleteConstruction () override
References AutoComplete(), HotkeyManager::Connect(), ClientUI::EditHiliteColor(), HotkeyManager::GetManager(), anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound(), and HotkeyManager::RebuildShortcuts().
GainingFocus()
void CUIEdit::GainingFocus () override
References GainingFocusSignal.
KeyPress()
void CUIEdit::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Referenced by MessageWndEdit::KeyPress(), CensoredCUIEdit::KeyPress(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SearchEdit::KeyPress().
LosingFocus()
void CUIEdit::LosingFocus () override
References LosingFocusSignal.
RClick()
void CUIEdit::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References UserString().
Render()
void CUIEdit::Render () override
Member Data Documentation
GainingFocusSignal
boost::signals2::signal<void ()> CUIEdit::GainingFocusSignal mutable
Referenced by GainingFocus().
LosingFocusSignal
boost::signals2::signal<void ()> CUIEdit::LosingFocusSignal mutable
Referenced by LosingFocus().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp