FreeOrion: CombatLogManager Class Reference
CombatLogManager Class Reference
Stores and retreives combat logs.
#include <CombatLogManager.h>
Classes
class Impl
Public Member Functions
Accessors
boost::optional< const CombatLog & > GetLog (int log_id) const
Return the requested combat log or boost::none.
boost::optional< std::vector< int > > IncompleteLogIDs () const
Return the ids of all incomplete logs or boost::none if they are all complete.
Mutators
int AddNewLog (const CombatLog &log)
Replace incomplete log with id with log.
void CompleteLog (int id, const CombatLog &log)
Replace incomplete log with id with log.
void Clear ()
Replace incomplete log with id with log.
template<typename Archive >
void SerializeIncompleteLogs (Archive &ar, const unsigned int version)
Serialize log headers so that the receiving LogManager can then request complete logs in the background.
Static Public Member Functions
static CombatLogManager & GetCombatLogManager ()
Private Member Functions
CombatLogManager ()
~CombatLogManager ()
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< Impl > const m_impl
Friends
class boost::serialization::access
Detailed Description
Stores and retreives combat logs.
Constructor & Destructor Documentation
CombatLogManager()
CombatLogManager::CombatLogManager () private
~CombatLogManager()
CombatLogManager::~CombatLogManager () private
Member Function Documentation
AddNewLog()
int CombatLogManager::AddNewLog (const CombatLog & log)
Replace incomplete log with id with log.
An incomplete log is a partially downloaded log where only the log id is known.
References m_impl.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
Clear()
void CombatLogManager::Clear ()
Replace incomplete log with id with log.
An incomplete log is a partially downloaded log where only the log id is known.
References m_impl.
Referenced by ExtractGameStartMessageData(), and HumanClientApp::ResetClientData().
CompleteLog()
void CombatLogManager::CompleteLog (int id, const CombatLog & log)
Replace incomplete log with id with log.
An incomplete log is a partially downloaded log where only the log id is known.
References m_impl.
Referenced by HumanClientApp::UpdateCombatLogs().
GetCombatLogManager()
CombatLogManager & CombatLogManager::GetCombatLogManager () static
Referenced by GetCombatLog(), and GetCombatLogManager().
GetLog()
boost::optional< const CombatLog & > CombatLogManager::GetLog (int log_id) const
Return the requested combat log or boost::none.
References m_impl.
Referenced by GetCombatLog(), and ServerApp::UpdateCombatLogs().
IncompleteLogIDs()
boost::optional< std::vector< int > > CombatLogManager::IncompleteLogIDs () const
Return the ids of all incomplete logs or boost::none if they are all complete.
References m_impl.
Referenced by HumanClientApp::UpdateCombatLogManager().
serialize()
template<typename Archive > template FO_COMMON_API void CombatLogManager::serialize< freeorion_xml_oarchive > (Archive & ar, const unsigned int version) private
References m_impl.
SerializeIncompleteLogs()
template<typename Archive > template void CombatLogManager::SerializeIncompleteLogs< freeorion_xml_iarchive > (Archive & ar, const unsigned int version)
Serialize log headers so that the receiving LogManager can then request complete logs in the background.
References m_impl.
Referenced by ExtractGameStartMessageData(), ExtractTurnUpdateMessageData(), GameStartMessage(), and TurnUpdateMessage().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_impl
std::unique_ptr<Impl> const CombatLogManager::m_impl private
Referenced by AddNewLog(), Clear(), CompleteLog(), GetLog(), IncompleteLogIDs(), serialize(), and SerializeIncompleteLogs().
The documentation for this class was generated from the following files:
CombatLogManager.h
CombatLogManager.cpp