FreeOrion: GovernmentWnd::MainPanel Class Reference
GovernmentWnd::MainPanel Class Reference
Public Member Functions
MainPanel (GG::X w, GG::Y h)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void AddPolicy (const Policy *policy)
If a suitable slot is available, adds the specified policy to the government.
bool CanPolicyBeAdded (const Policy *policy) const
void ClearPolicies ()
removes all policies from government
void ClearPolicy (const std::string &policy_name)
void CompleteConstruction () override
std::vector< std::string > Policies () const
returns vector of names of policies in slots of current shown design. empty slots are represented with empty string
void Refresh ()
void Sanitize ()
void SetPolicies (const std::vector< std::string > &policies)
puts specified policies in slots. attempts to put each policy into the slot corresponding to its place in the passed vector. if a policy cannot be placed, it is ignored. more policies than there are slots available are ignored, and slots for which there are insufficient policies in the passed vector are unmodified
void SetPolicy (const std::string &policy_name, unsigned int slot)
puts specified policy in specified slot. does nothing if slot is out of range of available slots for category
void SetPolicy (const Policy *policy, unsigned int slot)
Sets the policy in slot to policy.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
boost::signals2::signal< void(const Policy *, GG::Flags< GG::ModKey >)> PolicyClickedSignal
Protected Member Functions
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
Private Member Functions
bool AddPolicyEmptySlot (const Policy *policy, int slot_number)
void DoLayout ()
positions SlotControls
int FindEmptySlotForPolicy (const Policy *policy) const
void Populate ()
creates and places SlotControls for empire
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_background_image
std::shared_ptr< GG::Button > m_clear_button
std::vector< std::shared_ptr< PolicySlotControl > > m_slots
Constructor & Destructor Documentation
MainPanel()
GovernmentWnd::MainPanel::MainPanel (GG::X w, GG::Y h)
Member Function Documentation
AcceptDrops()
void GovernmentWnd::MainPanel::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
AddPolicy()
void GovernmentWnd::MainPanel::AddPolicy (const Policy * policy)
If a suitable slot is available, adds the specified policy to the government.
References AddPolicyEmptySlot(), and FindEmptySlotForPolicy().
Referenced by GovernmentWnd::CompleteConstruction().
AddPolicyEmptySlot()
bool GovernmentWnd::MainPanel::AddPolicyEmptySlot (const Policy * policy, int slot_number) private
References SetPolicy().
Referenced by AddPolicy().
CanPolicyBeAdded()
bool GovernmentWnd::MainPanel::CanPolicyBeAdded (const Policy * policy) const
References FindEmptySlotForPolicy().
ClearPolicies()
void GovernmentWnd::MainPanel::ClearPolicies ()
removes all policies from government
References m_slots, and SetPolicy().
Referenced by CompleteConstruction(), Sanitize(), and SetPolicies().
ClearPolicy()
void GovernmentWnd::MainPanel::ClearPolicy (const std::string & policy_name)
References m_slots, and Policy::Name().
Referenced by GovernmentWnd::CompleteConstruction().
CompleteConstruction()
void GovernmentWnd::MainPanel::CompleteConstruction () override
References ClearPolicies(), DoLayout(), m_clear_button, and UserString().
DoLayout()
void GovernmentWnd::MainPanel::DoLayout () private
positions SlotControls
References CUIWnd::ClientLowerRight(), m_background_image, m_clear_button, m_slots, anonymous_namespace{GovernmentWnd.cpp}::PAD(), and ClientUI::Pts().
Referenced by CompleteConstruction(), Populate(), and SizeMove().
DropsAcceptable()
void GovernmentWnd::MainPanel::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const override protected
References if().
FindEmptySlotForPolicy()
int GovernmentWnd::MainPanel::FindEmptySlotForPolicy (const Policy * policy) const private
References Policy::Category(), ClientApp::EmpireID(), GGHumanClientApp::GetApp(), GetEmpire(), GetPolicy(), m_slots, and Policy::Name().
Referenced by AddPolicy(), and CanPolicyBeAdded().
Policies()
std::vector< std::string > GovernmentWnd::MainPanel::Policies () const
returns vector of names of policies in slots of current shown design. empty slots are represented with empty string
References m_slots, and Policy::Name().
Populate()
void GovernmentWnd::MainPanel::Populate () private
creates and places SlotControls for empire
References anonymous_namespace{GovernmentWnd.cpp}::ConcatenatedCategorySlots(), DoLayout(), ClientApp::EmpireID(), GGHumanClientApp::GetApp(), GetEmpire(), m_slots, PolicyClickedSignal, and SetPolicy().
Referenced by Refresh(), and SetPolicy().
Refresh()
void GovernmentWnd::MainPanel::Refresh ()
References Populate().
Sanitize()
void GovernmentWnd::MainPanel::Sanitize ()
References ClearPolicies().
SetPolicies()
void GovernmentWnd::MainPanel::SetPolicies (const std::vector< std::string > & policies)
puts specified policies in slots. attempts to put each policy into the slot corresponding to its place in the passed vector. if a policy cannot be placed, it is ignored. more policies than there are slots available are ignored, and slots for which there are insufficient policies in the passed vector are unmodified
References ClearPolicies(), m_slots, and SetPolicy().
SetPolicy() [1/2]
void GovernmentWnd::MainPanel::SetPolicy (const std::string & policy_name, unsigned int slot)
puts specified policy in specified slot. does nothing if slot is out of range of available slots for category
References GetPolicy().
Referenced by AddPolicyEmptySlot(), ClearPolicies(), Populate(), and SetPolicies().
SetPolicy() [2/2]
void GovernmentWnd::MainPanel::SetPolicy (const Policy * policy, unsigned int slot)
Sets the policy in slot to policy.
References ClientApp::EmpireID(), Empires(), anonymous_namespace{GovernmentWnd.cpp}::EMPTY_STRING, ErrorLogger, GGHumanClientApp::GetApp(), GetEmpire(), FleetUIManager::GetFleetUIManager(), GetUniverse(), OrderSet::IssueOrder(), m_slots, Policy::Name(), ClientApp::Orders(), Populate(), SidePanel::Refresh(), FleetUIManager::RefreshAll(), and Universe::UpdateMeterEstimates().
SizeMove()
void GovernmentWnd::MainPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
Member Data Documentation
m_background_image
std::shared_ptr<GG::StaticGraphic> GovernmentWnd::MainPanel::m_background_image private
Referenced by DoLayout().
m_clear_button
std::shared_ptr<GG::Button> GovernmentWnd::MainPanel::m_clear_button private
Referenced by CompleteConstruction(), and DoLayout().
m_slots
std::vector<std::shared_ptr<PolicySlotControl> > GovernmentWnd::MainPanel::m_slots private
Referenced by ClearPolicies(), ClearPolicy(), DoLayout(), FindEmptySlotForPolicy(), Policies(), Populate(), SetPolicies(), and SetPolicy().
PolicyClickedSignal
boost::signals2::signal<void (const Policy*, GG::Flags<GG::ModKey>)> GovernmentWnd::MainPanel::PolicyClickedSignal mutable
Referenced by Populate().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp