FreeOrion: FieldTypeManager Class Reference
FieldTypeManager Class Reference
#include <FieldType.h>
Public Types
using container_type = std::map< std::string, std::unique_ptr< FieldType > >
using iterator = container_type::const_iterator
Public Member Functions
FO_COMMON_API auto begin () const -> iterator
iterator to the first field type
FO_COMMON_API auto end () const -> iterator
iterator to the last + 1th field type
auto GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
auto GetFieldType (const std::string &name) const -> const FieldType *
Returns the field type with the name name; you should use the free free function GetFieldType(...) instead, mainly to save some typing.
FO_COMMON_API void SetFieldTypes (Pending::Pending< container_type > &&future)
Sets types to the value of future.
Static Public Member Functions
static auto GetFieldTypeManager () -> FieldTypeManager &
Returns the instance of this singleton class; you should use the free function GetFieldTypeManager() instead.
Private Member Functions
FieldTypeManager ()
void CheckPendingFieldTypes () const
Assigns any m_pending_types to m_field_types.
Private Attributes
container_type m_field_types
boost::optional< Pending::Pending< container_type > > m_pending_types = boost::none
Future types being parsed by parser.
Static Private Attributes
static FieldTypeManager * s_instance = nullptr
Member Typedef Documentation
container_type
using FieldTypeManager::container_type = std::map<std::string, std::unique_ptr<FieldType> >
iterator
using FieldTypeManager::iterator = container_type::const_iterator
Constructor & Destructor Documentation
FieldTypeManager()
FieldTypeManager::FieldTypeManager () private
Member Function Documentation
begin()
FieldTypeManager::iterator FieldTypeManager::begin () const -> iterator
iterator to the first field type
CheckPendingFieldTypes()
void FieldTypeManager::CheckPendingFieldTypes () const private
Assigns any m_pending_types to m_field_types.
References Pending::SwapPending().
end()
FieldTypeManager::iterator FieldTypeManager::end () const -> iterator
iterator to the last + 1th field type
GetCheckSum()
unsigned int FieldTypeManager::GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), and DebugLogger.
Referenced by CheckSumContent().
GetFieldType()
const FieldType * FieldTypeManager::GetFieldType (const std::string & name) const -> const FieldType*
Returns the field type with the name name; you should use the free free function GetFieldType(...) instead, mainly to save some typing.
GetFieldTypeManager()
FieldTypeManager & FieldTypeManager::GetFieldTypeManager () -> FieldTypeManager& static
Returns the instance of this singleton class; you should use the free function GetFieldTypeManager() instead.
Referenced by GetFieldType(), and GetFieldTypeManager().
SetFieldTypes()
void FieldTypeManager::SetFieldTypes (Pending::Pending< container_type > && future)
Sets types to the value of future.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_field_types
container_type FieldTypeManager::m_field_types mutable private
m_pending_types
boost::optional<Pending::Pending<container_type> > FieldTypeManager::m_pending_types = boost::none mutable private
Future types being parsed by parser.
mutable so that it can be assigned to m_field_types when completed.
s_instance
FieldTypeManager * FieldTypeManager::s_instance = nullptr static private
Referenced by FieldType::GetCheckSum().
The documentation for this class was generated from the following files:
FieldType.h
FieldType.cpp