FreeOrion: parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1 Class Reference
parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1 Class Reference
Note: This simpler to use version of deconstruct_movable works with clang version 4.0.1 and gcc version 7.2.1 with boost 1.63.
#include <MovableEnvelope.h>
Public Member Functions
template<typename T >
std::unique_ptr< T > operator() (const MovableEnvelope< T > &obj, bool &pass) const
template<typename T >
std::vector< std::unique_ptr< T > > operator() (const std::vector< MovableEnvelope< T >> &objs, bool &pass) const
template<typename T >
std::vector< std::pair< std::string, std::unique_ptr< T > > > operator() (const std::vector< std::pair< std::string, MovableEnvelope< T >>> &objs, bool &pass)
Detailed Description
Note: This simpler to use version of deconstruct_movable works with clang version 4.0.1 and gcc version 7.2.1 with boost 1.63.
It does not work with clang 3.6.0 or gcc 4.8.4 or MSVC2015, with boost 1.58 on the continuous integration servers. It is because of improved support for decltype in the newer compilers.
When the project moves the required versions past these versions this simpler, more uniform code could be adopted.
/ ** deconstruct_movable is a functor that extracts the unique_ptr from a MovableEnvelope<T>. This is a one time operation that empties the MovableEnvelope<T>. It is typically done while calling the constructor from outside of boost::spirit that expects a unique_ptr<T>
Member Function Documentation
operator()() [1/3]
template<typename T > std::unique_ptr<T> parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1::operator() (const MovableEnvelope< T > & obj, bool & pass) const inline
References parse::detail::MovableEnvelope< T >::OpenEnvelope().
operator()() [2/3]
template<typename T > std::vector<std::unique_ptr<T> > parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1::operator() (const std::vector< MovableEnvelope< T >> & objs, bool & pass) const inline
References parse::detail::OpenEnvelopes().
operator()() [3/3]
template<typename T > std::vector<std::pair<std::string, std::unique_ptr<T> > > parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1::operator() (const std::vector< std::pair< std::string, MovableEnvelope< T >>> & objs, bool & pass) inline
References parse::detail::OpenEnvelopes().
The documentation for this class was generated from the following file:
MovableEnvelope.h