FreeOrion: anonymous_namespace{SitRepPanel.cpp}::SitRepRow Class Reference
anonymous_namespace{SitRepPanel.cpp}::SitRepRow Class Reference
Public Member Functions
SitRepRow (GG::X w, GG::Y h, const SitRepEntry &sitrep)
void CompleteConstruction () override
const SitRepEntry & GetSitRepEntry () const
void Init ()
void PreRender () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
SitRepDataPanel * m_panel
const SitRepEntry m_sitrep
Detailed Description
A ListBox::Row subclass used to display SitReps.
Constructor & Destructor Documentation
anonymous_namespace{SitRepPanel.cpp}::SitRepRow::SitRepRow (GG::X w, GG::Y h, const SitRepEntry & sitrep) inline
References anonymous_namespace{ServerWrapper.cpp}::SetName().
Member Function Documentation
void anonymous_namespace{SitRepPanel.cpp}::SitRepRow::CompleteConstruction () inline override
References anonymous_namespace{SitRepPanel.cpp}::GetIconSize(), and ClientUI::Pts().
const SitRepEntry& anonymous_namespace{SitRepPanel.cpp}::SitRepRow::GetSitRepEntry () const inline
void anonymous_namespace{SitRepPanel.cpp}::SitRepRow::Init () inline
void anonymous_namespace{SitRepPanel.cpp}::SitRepRow::PreRender () inline override
void anonymous_namespace{SitRepPanel.cpp}::SitRepRow::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
SitRepDataPanel* anonymous_namespace{SitRepPanel.cpp}::SitRepRow::m_panel private
const SitRepEntry anonymous_namespace{SitRepPanel.cpp}::SitRepRow::m_sitrep private
The documentation for this class was generated from the following file:
SitRepPanel.cpp