FreeOrion: DiplomaticMessage Class Reference
DiplomaticMessage Class Reference
#include <Diplomacy.h>
Public Types
enum DiplomaticMessageType : int {
INVALID_DIPLOMATIC_MESSAGE_TYPE = -1, WAR_DECLARATION, PEACE_PROPOSAL, ACCEPT_PEACE_PROPOSAL,
ALLIES_PROPOSAL, ACCEPT_ALLIES_PROPOSAL, END_ALLIANCE_DECLARATION, CANCEL_PROPOSAL,
REJECT_PROPOSAL
}
Public Member Functions
DiplomaticMessage ()
DiplomaticMessage (int sender_empire_id, int recipient_empire_id, DiplomaticMessageType type)
std::string Dump () const
DiplomaticMessageType GetType () const
bool IsAllowed () const
Tells if this dimplomatic message allowed by game rules.
int RecipientEmpireID () const
int SenderEmpireID () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_recipient_empire
int m_sender_empire
DiplomaticMessageType m_type
Friends
class boost::serialization::access
Member Enumeration Documentation
DiplomaticMessageType
enum DiplomaticMessage::DiplomaticMessageType : int
Enumerator
INVALID_DIPLOMATIC_MESSAGE_TYPE
WAR_DECLARATION
PEACE_PROPOSAL
ACCEPT_PEACE_PROPOSAL
ALLIES_PROPOSAL
ACCEPT_ALLIES_PROPOSAL
END_ALLIANCE_DECLARATION
CANCEL_PROPOSAL
REJECT_PROPOSAL
Constructor & Destructor Documentation
DiplomaticMessage() [1/2]
DiplomaticMessage::DiplomaticMessage ()
DiplomaticMessage() [2/2]
DiplomaticMessage::DiplomaticMessage (int sender_empire_id, int recipient_empire_id, DiplomaticMessageType type)
Member Function Documentation
Dump()
std::string DiplomaticMessage::Dump () const
References ACCEPT_ALLIES_PROPOSAL, ACCEPT_PEACE_PROPOSAL, ALLIES_PROPOSAL, CANCEL_PROPOSAL, END_ALLIANCE_DECLARATION, INVALID_DIPLOMATIC_MESSAGE_TYPE, m_recipient_empire, m_sender_empire, m_type, PEACE_PROPOSAL, REJECT_PROPOSAL, to_string(), and WAR_DECLARATION.
GetType()
DiplomaticMessageType DiplomaticMessage::GetType () const inline
Referenced by EmpireManager::HandleDiplomaticMessage(), PlayerListWnd::HandleDiplomaticMessageChange(), operator==(), PlayerListWnd::PlayerRightClicked(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render(), and FreeOrionPython::WrapEmpire().
IsAllowed()
bool DiplomaticMessage::IsAllowed () const
Tells if this dimplomatic message allowed by game rules.
References GameRules::Get(), GetGameRules(), and UserStringNop.
Referenced by EmpireManager::HandleDiplomaticMessage().
RecipientEmpireID()
int DiplomaticMessage::RecipientEmpireID () const inline
References Effect::Dump().
Referenced by EmpireManager::HandleDiplomaticMessage(), operator==(), anonymous_namespace{AIWrapper.cpp}::SendDiplomaticMessage(), EmpireManager::SetDiplomaticMessage(), and FreeOrionPython::WrapEmpire().
SenderEmpireID()
int DiplomaticMessage::SenderEmpireID () const inline
Referenced by EmpireManager::HandleDiplomaticMessage(), operator==(), EmpireManager::SetDiplomaticMessage(), and FreeOrionPython::WrapEmpire().
serialize()
template<typename Archive > template void DiplomaticMessage::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_recipient_empire
int DiplomaticMessage::m_recipient_empire private
Referenced by Dump().
m_sender_empire
int DiplomaticMessage::m_sender_empire private
Referenced by Dump().
m_type
DiplomaticMessageType DiplomaticMessage::m_type private
Referenced by Dump().
The documentation for this class was generated from the following files:
Diplomacy.h
Diplomacy.cpp
SerializeEmpire.cpp