FreeOrion: AggressiveOrder Class Reference
AggressiveOrder Class Reference
the Order subclass that represents setting the aggression state of objects controlled by an empire.
#include <Order.h>
Public Member Functions
Structors
AggressiveOrder (int empire, int object_id, bool aggression=true)
Accessors
int ObjectID () const
Returns ID of object selected in this order.
bool Aggression () const
Returns aggression state to set object to.
Public Member Functions inherited from Order
void Execute () const
Executes the order on the Universe and Empires.
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Order ()
ctor taking the ID of the Empire issuing the order.
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
ctor taking the ID of the Empire issuing the order.
int EmpireID () const
Returns the ID of the Empire issuing the order.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
Static Public Member Functions
static bool Check (int empire_id, int object_id, bool aggression)
Private Member Functions
AggressiveOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_aggression = false
int m_object_id = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents setting the aggression state of objects controlled by an empire.
Constructor & Destructor Documentation
AggressiveOrder() [1/2]
AggressiveOrder::AggressiveOrder (int empire, int object_id, bool aggression = true)
References Check().
AggressiveOrder() [2/2]
AggressiveOrder::AggressiveOrder () private default
Member Function Documentation
Aggression()
bool AggressiveOrder::Aggression () const inline
Returns aggression state to set object to.
References Order::ExecuteImpl().
Check()
bool AggressiveOrder::Check (int empire_id, int object_id, bool aggression) static
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by AggressiveOrder(), and ExecuteImpl().
ExecuteImpl()
void AggressiveOrder::ExecuteImpl () const override private virtual
Preconditions:
m_object_id must be the ID of an object owned by issuing empire
the object must have an aggression status: fleets
Postconditions:
the object is set to the new aggression state
Implements Order.
References Check(), Order::EmpireID(), ObjectMap::get(), Order::GetValidatedEmpire(), m_aggression, m_object_id, Objects(), and Fleet::SetAggressive().
ObjectID()
int AggressiveOrder::ObjectID () const inline
Returns ID of object selected in this order.
serialize()
template<typename Archive > void AggressiveOrder::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_aggression
bool AggressiveOrder::m_aggression = false private
Referenced by ExecuteImpl().
m_object_id
int AggressiveOrder::m_object_id = INVALID_OBJECT_ID private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp