FreeOrion: ShipDamageBrowseWnd Class Reference
ShipDamageBrowseWnd Class Reference
Gives details about what effects contribute to a meter's maximum value (Effect Accounting) and shows the current turn's current meter value and the predicted current meter value for next turn.
#include <MeterBrowseWnd.h>
Public Member Functions
ShipDamageBrowseWnd (int object_id, MeterType primary_meter_type)
Public Member Functions inherited from MeterBrowseWnd
MeterBrowseWnd (int object_id, MeterType primary_meter_type, MeterType secondary_meter_type)
MeterBrowseWnd (int object_id, MeterType primary_meter_type)
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Member Functions
void Initialize ()
void UpdateEffectLabelsAndValues (GG::Y &top)
void UpdateImpl (std::size_t mode, const Wnd *target) override
void UpdateSummary ()
Additional Inherited Members
Protected Member Functions inherited from MeterBrowseWnd
void Initialize ()
void UpdateEffectLabelsAndValues (GG::Y &top)
void UpdateImpl (std::size_t mode, const Wnd *target) override
void UpdateSummary ()
Protected Attributes inherited from MeterBrowseWnd
std::shared_ptr< GG::Label > m_change_label = nullptr
std::shared_ptr< GG::Label > m_change_value = nullptr
std::shared_ptr< GG::Label > m_current_label = nullptr
std::shared_ptr< GG::Label > m_current_value = nullptr
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_effect_labels_and_values
bool m_initialized = false
std::shared_ptr< GG::Label > m_meter_title = nullptr
std::shared_ptr< GG::Label > m_next_turn_label = nullptr
std::shared_ptr< GG::Label > m_next_turn_value = nullptr
int m_object_id
MeterType m_primary_meter_type
GG::Y m_row_height = GG::Y1
MeterType m_secondary_meter_type
std::shared_ptr< GG::Label > m_summary_title = nullptr
Detailed Description
Gives details about what effects contribute to a meter's maximum value (Effect Accounting) and shows the current turn's current meter value and the predicted current meter value for next turn.
Constructor & Destructor Documentation
ShipDamageBrowseWnd()
ShipDamageBrowseWnd::ShipDamageBrowseWnd (int object_id, MeterType primary_meter_type)
Member Function Documentation
Initialize()
void ShipDamageBrowseWnd::Initialize () private
References anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), ErrorLogger, ClientUI::GetBoldFont(), GetShip(), MeterBrowseWnd::m_initialized, MeterBrowseWnd::m_meter_title, MeterBrowseWnd::m_object_id, MeterBrowseWnd::m_row_height, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), UpdateEffectLabelsAndValues(), and UpdateSummary().
Referenced by UpdateImpl().
UpdateEffectLabelsAndValues()
void ShipDamageBrowseWnd::UpdateEffectLabelsAndValues (GG::Y & top) private
References PartType::Class(), anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), ErrorLogger, FlexibleFormat(), GetPartType(), GetShip(), GetShipDesign(), MeterBrowseWnd::m_effect_labels_and_values, MeterBrowseWnd::m_object_id, MeterBrowseWnd::m_row_height, METER_CAPACITY, METER_SECONDARY_STAT, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), ShipDesign::Name(), ShipDesign::Parts(), PC_DIRECT_WEAPON, and UserString().
Referenced by Initialize().
UpdateImpl()
void ShipDamageBrowseWnd::UpdateImpl (std::size_t mode, const Wnd * target) override private
References Initialize(), and MeterBrowseWnd::m_initialized.
UpdateSummary()
void ShipDamageBrowseWnd::UpdateSummary () private
References DoubleToString(), FlexibleFormat(), GetShip(), MeterBrowseWnd::m_meter_title, MeterBrowseWnd::m_object_id, and UserString().
Referenced by Initialize().
The documentation for this class was generated from the following files:
MeterBrowseWnd.h
MeterBrowseWnd.cpp