FreeOrion: GalaxySetupWnd Class Reference
GalaxySetupWnd Class Reference
This class is the Galaxy Setup window.
#include <GalaxySetupWnd.h>
Public Member Functions
Structors
GalaxySetupWnd ()
void CompleteConstruction () override
Accessors
bool EndedWithOk () const
returns true iff the dialog is finished running and it was closed with the "OK" button
const std::string & EmpireName () const
returns the panel containing all the user-chosen options.
GG::Clr EmpireColor () const
returns true iff the dialog is finished running and it was closed with the "OK" button
const std::string & StartingSpeciesName () const
returns true iff the dialog is finished running and it was closed with the "OK" button
int NumberAIs () const
returns true iff the dialog is finished running and it was closed with the "OK" button
std::vector< std::pair< std::string, std::string > > GetRulesAsStrings () const
returns true iff the dialog is finished running and it was closed with the "OK" button
Mutators
void Render () override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Private Member Functions
void CancelClicked ()
void DoLayout ()
void EmpireNameChanged (const std::string &name)
void OkClicked ()
void PlayerNameChanged (const std::string &name)
void PreviewImageChanged (std::shared_ptr< GG::Texture > new_image)
Private Attributes
std::shared_ptr< GG::Button > m_cancel
Cancel button;.
std::shared_ptr< GG::Label > m_empire_color_label
std::shared_ptr< EmpireColorSelector > m_empire_color_selector
std::shared_ptr< GG::Edit > m_empire_name_edit
std::shared_ptr< GG::Label > m_empire_name_label
bool m_ended_with_ok = false
indicates whether or not we ended the dialog with OK or not
std::shared_ptr< GalaxySetupPanel > m_galaxy_setup_panel
The GalaxySetupPanel that does most of the work of the dialog.
std::shared_ptr< GameRulesPanel > m_game_rules_panel
std::shared_ptr< GG::Label > m_number_ais_label
std::shared_ptr< GG::Spin< int > > m_number_ais_spin
std::shared_ptr< GG::Button > m_ok
OK button;.
std::shared_ptr< GG::Edit > m_player_name_edit
std::shared_ptr< GG::Label > m_player_name_label
std::shared_ptr< GG::StaticGraphic > m_preview_image
The galaxy shape preview image;.
GG::Pt m_preview_ul
std::shared_ptr< SpeciesSelector > m_starting_secies_selector
std::shared_ptr< GG::Label > m_starting_species_label
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
This class is the Galaxy Setup window.
It is a modal window that allows the user to choose a galaxy style, size, etc.
Constructor & Destructor Documentation
GalaxySetupWnd::GalaxySetupWnd ()
Member Function Documentation
GG::Rect GalaxySetupWnd::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndHeight(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndWidth(), and HumanClientApp::GetApp().
void GalaxySetupWnd::CancelClicked () private
References m_ended_with_ok.
Referenced by CompleteConstruction(), and KeyPress().
void GalaxySetupWnd::CompleteConstruction () override
References CancelClicked(), CUIWnd::CompleteConstruction(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_HEIGHT(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), GalaxySetupPanel::DefaultWidth(), DoLayout(), EmpireNameChanged(), OptionsDB::Get(), GetOptionsDB(), m_cancel, m_empire_color_label, m_empire_color_selector, m_empire_name_edit, m_empire_name_label, m_galaxy_setup_panel, m_game_rules_panel, m_number_ais_label, m_number_ais_spin, m_ok, m_player_name_edit, m_player_name_label, m_preview_image, m_starting_secies_selector, m_starting_species_label, IApp::MAX_AI_PLAYERS(), OkClicked(), PlayerNameChanged(), PreviewImageChanged(), CUIWnd::ResetDefaultPosition(), CUIWnd::SaveDefaultedOptions(), and UserString().
void GalaxySetupWnd::DoLayout () private
References CUIWnd::ClientLowerRight(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_HEIGHT(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_MARGIN(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), GalaxySetupPanel::DefaultWidth(), anonymous_namespace{GalaxySetupWnd.cpp}::GAL_SETUP_PANEL_HT(), ClientUI::GetFont(), m_cancel, m_empire_color_label, m_empire_color_selector, m_empire_name_edit, m_empire_name_label, m_galaxy_setup_panel, m_game_rules_panel, m_number_ais_label, m_number_ais_spin, m_ok, m_player_name_edit, m_player_name_label, m_preview_image, m_preview_ul, m_starting_secies_selector, m_starting_species_label, anonymous_namespace{GalaxySetupWnd.cpp}::PANEL_CONTROL_SPACING(), and anonymous_namespace{GalaxySetupWnd.cpp}::PREVIEW_SZ().
Referenced by CompleteConstruction(), PreviewImageChanged(), and SizeMove().
GG::Clr GalaxySetupWnd::EmpireColor () const
returns true iff the dialog is finished running and it was closed with the "OK" button
References m_empire_color_selector.
const std::string & GalaxySetupWnd::EmpireName () const
returns the panel containing all the user-chosen options.
References m_empire_name_edit.
Referenced by OkClicked().
void GalaxySetupWnd::EmpireNameChanged (const std::string & name) private
References m_ok.
Referenced by CompleteConstruction().
bool GalaxySetupWnd::EndedWithOk () const inline
returns true iff the dialog is finished running and it was closed with the "OK" button
References GameRulesPanel::DoLayout(), GameRulesPanel::GetRulesAsStrings(), GameRulesPanel::Render(), and GameRulesPanel::SizeMove().
std::vector< std::pair< std::string, std::string > > GalaxySetupWnd::GetRulesAsStrings () const
returns true iff the dialog is finished running and it was closed with the "OK" button
References m_game_rules_panel.
void GalaxySetupWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References CancelClicked(), m_ok, and OkClicked().
int GalaxySetupWnd::NumberAIs () const
returns true iff the dialog is finished running and it was closed with the "OK" button
References m_number_ais_spin.
void GalaxySetupWnd::OkClicked () private
References OptionsDB::Commit(), EmpireName(), GetOptionsDB(), m_empire_color_selector, m_ended_with_ok, m_galaxy_setup_panel, m_number_ais_spin, m_player_name_edit, m_starting_secies_selector, and OptionsDB::Set().
Referenced by CompleteConstruction(), and KeyPress().
void GalaxySetupWnd::PlayerNameChanged (const std::string & name) private
References m_ok.
Referenced by CompleteConstruction().
void GalaxySetupWnd::PreviewImageChanged (std::shared_ptr< GG::Texture > new_image) private
References DoLayout(), and m_preview_image.
Referenced by CompleteConstruction().
void GalaxySetupWnd::Render () override
References CUIWnd::ClientUpperLeft(), m_preview_ul, anonymous_namespace{GalaxySetupWnd.cpp}::PREVIEW_SZ(), CUIWnd::Render(), and ClientUI::WndInnerBorderColor().
void GalaxySetupWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
const std::string & GalaxySetupWnd::StartingSpeciesName () const
returns true iff the dialog is finished running and it was closed with the "OK" button
References m_starting_secies_selector.
Member Data Documentation
std::shared_ptr<GG::Button> GalaxySetupWnd::m_cancel private
Cancel button;.
Referenced by CompleteConstruction(), and DoLayout().
std::shared_ptr<GG::Label> GalaxySetupWnd::m_empire_color_label private
Referenced by CompleteConstruction(), and DoLayout().
std::shared_ptr<EmpireColorSelector> GalaxySetupWnd::m_empire_color_selector private
Referenced by CompleteConstruction(), DoLayout(), EmpireColor(), and OkClicked().
std::shared_ptr<GG::Edit> GalaxySetupWnd::m_empire_name_edit private
Referenced by CompleteConstruction(), DoLayout(), and EmpireName().
std::shared_ptr<GG::Label> GalaxySetupWnd::m_empire_name_label private
Referenced by CompleteConstruction(), and DoLayout().
bool GalaxySetupWnd::m_ended_with_ok = false private
indicates whether or not we ended the dialog with OK or not
Referenced by CancelClicked(), and OkClicked().
std::shared_ptr<GalaxySetupPanel> GalaxySetupWnd::m_galaxy_setup_panel private
The GalaxySetupPanel that does most of the work of the dialog.
Referenced by CompleteConstruction(), DoLayout(), and OkClicked().
std::shared_ptr<GameRulesPanel> GalaxySetupWnd::m_game_rules_panel private
Referenced by CompleteConstruction(), DoLayout(), and GetRulesAsStrings().
std::shared_ptr<GG::Label> GalaxySetupWnd::m_number_ais_label private
Referenced by CompleteConstruction(), and DoLayout().
std::shared_ptr<GG::Spin<int> > GalaxySetupWnd::m_number_ais_spin private
Referenced by CompleteConstruction(), DoLayout(), NumberAIs(), and OkClicked().
std::shared_ptr<GG::Button> GalaxySetupWnd::m_ok private
OK button;.
Referenced by CompleteConstruction(), DoLayout(), EmpireNameChanged(), KeyPress(), and PlayerNameChanged().
std::shared_ptr<GG::Edit> GalaxySetupWnd::m_player_name_edit private
Referenced by CompleteConstruction(), DoLayout(), and OkClicked().
std::shared_ptr<GG::Label> GalaxySetupWnd::m_player_name_label private
Referenced by CompleteConstruction(), and DoLayout().
std::shared_ptr<GG::StaticGraphic> GalaxySetupWnd::m_preview_image private
The galaxy shape preview image;.
Referenced by CompleteConstruction(), DoLayout(), and PreviewImageChanged().
GG::Pt GalaxySetupWnd::m_preview_ul private
Referenced by DoLayout(), and Render().
std::shared_ptr<SpeciesSelector> GalaxySetupWnd::m_starting_secies_selector private
Referenced by CompleteConstruction(), DoLayout(), OkClicked(), and StartingSpeciesName().
std::shared_ptr<GG::Label> GalaxySetupWnd::m_starting_species_label private
Referenced by CompleteConstruction(), and DoLayout().
The documentation for this class was generated from the following files:
GalaxySetupWnd.h
GalaxySetupWnd.cpp