FreeOrion: DiscoveryServer Class Reference
DiscoveryServer Class Reference
A simple server that listens for FreeOrion-server-discovery UDP datagrams on the local network and sends out responses to them.
Public Member Functions
DiscoveryServer (boost::asio::io_context &io_context)
Private Member Functions
void HandleReceive (const boost::system::error_code &error)
void Listen ()
Private Attributes
std::array< char, 1024 > m_recv_buffer = {}
boost::asio::ip::udp::endpoint m_remote_endpoint
boost::asio::ip::udp::socket m_socket
Detailed Description
A simple server that listens for FreeOrion-server-discovery UDP datagrams on the local network and sends out responses to them.
Constructor & Destructor Documentation
DiscoveryServer()
DiscoveryServer::DiscoveryServer (boost::asio::io_context & io_context) inline
References Networking::DiscoveryPort(), ErrorLogger, and GetOptionsDB().
Member Function Documentation
HandleReceive()
void DiscoveryServer::HandleReceive (const boost::system::error_code & error) inline private
References DebugLogger, Networking::DISCOVERY_ANSWER, Networking::DISCOVERY_QUESTION, parse::double_free_variable(), ErrorLogger, parse::int_free_variable(), ValueRef::NON_OBJECT_REFERENCE, parse::string_free_variable(), and to_string().
Referenced by Listen().
Listen()
void DiscoveryServer::Listen () inline private
References HandleReceive().
Member Data Documentation
m_recv_buffer
std::array<char, 1024> DiscoveryServer::m_recv_buffer = {} private
m_remote_endpoint
boost::asio::ip::udp::endpoint DiscoveryServer::m_remote_endpoint private
m_socket
boost::asio::ip::udp::socket DiscoveryServer::m_socket private
The documentation for this class was generated from the following file:
ServerNetworking.cpp