FreeOrion: Hotkey Class Reference
Hotkey Class Reference
A single hotkey, ie just a combination key+modifier that has been given a certain name.
#include <Hotkeys.h>
Public Member Functions
std::string GetDescription () const
Returns the name of the user string containing the description of the shortcut.
bool IsDefault () const
Is the hotkey safe to recognize while typing text?
bool IsTypingSafe () const
std::string PrettyPrint () const
void SetFromString (const std::string &str)
std::string ToString () const
Static Public Member Functions
static void AddHotkey (const std::string &name, const std::string &description, GG::Key key, GG::Flags< GG::ModKey > mod=GG::MOD_KEY_NONE)
Registers a hotkey name (ie the one used for storing in the database) along with a description and a default value.
static void AddOptions (OptionsDB &db)
Adds hotkey-related options to the options data base.
static void ClearHotkey (const Hotkey &hotkey)
Sets the value of the given named hotkey to no key.
static std::set< std::string > DefinedHotkeys ()
Returns the name of all defined hotkeys.
static std::pair< GG::Key, GG::Flags< GG::ModKey > > HotkeyFromString (const std::string &str)
Converts a string back to the pair key/modifier.
static std::string HotkeyToString (GG::Key key, GG::Flags< GG::ModKey > mod)
Returns a string that can later be parsed again with HotkeyFromString()
static bool IsTypingSafe (GG::Key key, GG::Flags< GG::ModKey > mod)
Whether or not the given key combination is safe to recognize while typing text.
static const Hotkey & NamedHotkey (const std::string &name)
Returns the Hotkey of the given name, or raises an exception if there is no such hotkey.
static std::string PrettyPrint (GG::Key key, GG::Flags< GG::ModKey > mod)
Pretty print, ie transform into something that may look reasonably nice for the user, but won't be parseable anymore.
static void ReadFromOptions (OptionsDB &db)
static void ResetHotkey (const Hotkey &hotkey)
Sets the value of the given named hotkey to its default, and updates the corresponding option.
static void SetHotkey (const Hotkey &hotkey, GG::Key key, GG::Flags< GG::ModKey > mod=GG::MOD_KEY_NONE)
Sets the value of the given named hotkey, and updates the corresponding option.
Public Attributes
std::string m_description
The human readable description of what this Hot does.
GG::Key m_key
Is the hotkey set to its default value ?
GG::Key m_key_default
GG::Flags< GG::ModKey > m_mod_keys
GG::Flags< GG::ModKey > m_mod_keys_default
std::string m_name
Internal name (code-like).
Private Member Functions
Hotkey (const std::string &name, const std::string &description, GG::Key key, GG::Flags< GG::ModKey > mod=GG::MOD_KEY_NONE)
Static Private Member Functions
static Hotkey & PrivateNamedHotkey (const std::string &name)
Returns a modifiable version of the hotkey.
Static Private Attributes
static std::map< std::string, Hotkey > * s_hotkeys = nullptr
The global hotkey storage.
Detailed Description
A single hotkey, ie just a combination key+modifier that has been given a certain name.
Constructor & Destructor Documentation
Hotkey()
Hotkey::Hotkey (const std::string & name, const std::string & description, GG::Key key, GG::Flags< GG::ModKey > mod = GG::MOD_KEY_NONE) private
Member Function Documentation
AddHotkey()
void Hotkey::AddHotkey (const std::string & name, const std::string & description, GG::Key key, GG::Flags< GG::ModKey > mod = GG::MOD_KEY_NONE) static
Registers a hotkey name (ie the one used for storing in the database) along with a description and a default value.
Referenced by anonymous_namespace{CUIControls.cpp}::AddOptions(), anonymous_namespace{HumanClientApp.cpp}::AddOptions(), and anonymous_namespace{MapWnd.cpp}::AddOptions().
AddOptions()
void Hotkey::AddOptions (OptionsDB & db) static
Adds hotkey-related options to the options data base.
This function must be called after the initialization of all the hotkey lists, which is probably why it should be called from main(), or something like that.
References OptionsDB::Add(), GetDescription(), m_name, and ToString().
Referenced by mainConfigOptionsSetup().
ClearHotkey()
void Hotkey::ClearHotkey (const Hotkey & hotkey) static
Sets the value of the given named hotkey to no key.
References SetHotkey().
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption().
DefinedHotkeys()
std::set< std::string > Hotkey::DefinedHotkeys () static
Returns the name of all defined hotkeys.
Referenced by anonymous_namespace{OptionsWnd.cpp}::HotkeysBySection().
GetDescription()
std::string Hotkey::GetDescription () const
Returns the name of the user string containing the description of the shortcut.
References m_description.
Referenced by AddOptions(), and OptionsWnd::HotkeyOption().
HotkeyFromString()
std::pair< GG::Key, GG::Flags< GG::ModKey > > Hotkey::HotkeyFromString (const std::string & str) static
Converts a string back to the pair key/modifier.
References ErrorLogger, and details::mod().
HotkeyToString()
std::string Hotkey::HotkeyToString (GG::Key key, GG::Flags< GG::ModKey > mod) static
Returns a string that can later be parsed again with HotkeyFromString()
References details::mod().
IsDefault()
bool Hotkey::IsDefault () const
Is the hotkey safe to recognize while typing text?
References m_key, m_key_default, m_mod_keys, and m_mod_keys_default.
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption().
IsTypingSafe() [1/2]
bool Hotkey::IsTypingSafe (GG::Key key, GG::Flags< GG::ModKey > mod) static
Whether or not the given key combination is safe to recognize while typing text.
IsTypingSafe() [2/2]
bool Hotkey::IsTypingSafe () const
References m_key, and m_mod_keys.
Referenced by HotkeyManager::ProcessNamedShortcut().
NamedHotkey()
const Hotkey & Hotkey::NamedHotkey (const std::string & name) static
Returns the Hotkey of the given name, or raises an exception if there is no such hotkey.
References PrivateNamedHotkey().
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption(), anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption(), OptionsWnd::HotkeyOption(), and HotkeyManager::RebuildShortcuts().
PrettyPrint() [1/2]
std::string Hotkey::PrettyPrint (GG::Key key, GG::Flags< GG::ModKey > mod) static
Pretty print, ie transform into something that may look reasonably nice for the user, but won't be parseable anymore.
References ReplaceInString().
Referenced by OptionsWnd::HotkeyOption().
PrettyPrint() [2/2]
std::string Hotkey::PrettyPrint () const
PrivateNamedHotkey()
Hotkey & Hotkey::PrivateNamedHotkey (const std::string & name) static private
Returns a modifiable version of the hotkey.
References s_hotkeys.
Referenced by NamedHotkey(), ResetHotkey(), and SetHotkey().
ReadFromOptions()
void Hotkey::ReadFromOptions (OptionsDB & db) static
References DebugLogger, ErrorLogger, OptionsDB::Get(), m_key, m_mod_keys, m_name, OptionsDB::OptionExists(), and TraceLogger.
Referenced by ClientUI::ClientUI().
ResetHotkey()
void Hotkey::ResetHotkey (const Hotkey & hotkey) static
Sets the value of the given named hotkey to its default, and updates the corresponding option.
References GetOptionsDB(), m_key, m_key_default, m_mod_keys, m_mod_keys_default, m_name, PrivateNamedHotkey(), OptionsDB::Set(), and ToString().
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption().
SetFromString()
void Hotkey::SetFromString (const std::string & str)
SetHotkey()
void Hotkey::SetHotkey (const Hotkey & hotkey, GG::Key key, GG::Flags< GG::ModKey > mod = GG::MOD_KEY_NONE) static
Sets the value of the given named hotkey, and updates the corresponding option.
References GetOptionsDB(), m_key, m_mod_keys, m_name, PrivateNamedHotkey(), OptionsDB::Set(), and ToString().
Referenced by ClearHotkey(), and anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption().
ToString()
std::string Hotkey::ToString () const
Referenced by AddOptions(), ResetHotkey(), and SetHotkey().
Member Data Documentation
m_description
std::string Hotkey::m_description
The human readable description of what this Hot does.
Referenced by GetDescription().
m_key
GG::Key Hotkey::m_key
Is the hotkey set to its default value ?
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption(), IsDefault(), IsTypingSafe(), ReadFromOptions(), HotkeyManager::RebuildShortcuts(), ResetHotkey(), and SetHotkey().
m_key_default
GG::Key Hotkey::m_key_default
Referenced by IsDefault(), and ResetHotkey().
m_mod_keys
GG::Flags<GG::ModKey> Hotkey::m_mod_keys
Referenced by anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption(), IsDefault(), IsTypingSafe(), ReadFromOptions(), HotkeyManager::RebuildShortcuts(), ResetHotkey(), and SetHotkey().
m_mod_keys_default
GG::Flags<GG::ModKey> Hotkey::m_mod_keys_default
Referenced by IsDefault(), and ResetHotkey().
m_name
std::string Hotkey::m_name
Internal name (code-like).
Referenced by AddOptions(), ReadFromOptions(), HotkeyManager::RebuildShortcuts(), ResetHotkey(), and SetHotkey().
s_hotkeys
std::map< std::string, Hotkey > * Hotkey::s_hotkeys = nullptr static private
The global hotkey storage.
Referenced by PrivateNamedHotkey().
The documentation for this class was generated from the following files:
Hotkeys.h
Hotkeys.cpp