FreeOrion: Alignment Class Reference
Alignment Class Reference
#include <Empire.h>
Public Member Functions
Alignment (const std::string &name, const std::string &description, const std::string &graphic)
Alignment ()
const std::string & Description () const
const std::string & Graphic () const
const std::string & Name () const
Private Attributes
std::string m_description
std::string m_graphic
std::string m_name
Constructor & Destructor Documentation
Alignment::Alignment (const std::string & name, const std::string & description, const std::string & graphic) inline
Alignment::Alignment () inline
References Description(), Graphic(), and Name().
Member Function Documentation
const std::string & Alignment::Description () const
Referenced by Alignment().
const std::string & Alignment::Graphic () const
Referenced by Alignment().
const std::string & Alignment::Name () const
Referenced by Alignment().
Member Data Documentation
std::string Alignment::m_description private
std::string Alignment::m_graphic private
std::string Alignment::m_name private
The documentation for this class was generated from the following files:
Empire.h
Empire.cpp