FreeOrion: GGHumanClientApp Class Reference
GGHumanClientApp Class Reference
the application framework class for the human player FreeOrion client.
#include <GGHumanClientApp.h>
Public Types
typedef boost::signals2::signal< void(bool)> FullscreenSwitchSignalType
typedef boost::signals2::signal< void()> RepositionWindowsSignalType
Public Member Functions
GGHumanClientApp ()=delete
GGHumanClientApp (int width, int height, bool calculate_FPS, std::string name, int x, int y, bool fullscreen, bool fake_mode_change)
GGHumanClientApp (const GGHumanClientApp &)=delete
GGHumanClientApp (GGHumanClientApp &&)=delete
~GGHumanClientApp () override
void Autosave ()
Autosaves the current game, iff autosaves are enabled and any turn number requirements are met.
int AutoTurnsLeft () const
returns number of turns left to execute automatically
void BrowsePath (const boost::filesystem::path &browse_path)
Opens the users preferred application for file manager at the specified path browse_path.
void CancelMultiplayerGameFromLobby ()
cancels out of multiplayer game
bool CanSaveNow () const
returns true / false to indicate whether this client can currently safely initiate a game save
void ChangeLoggerThreshold (const std::string &option_name, LogLevel option_value)
Update the logger in OptionsDB and the other processes if hosting.
void ContinueSinglePlayerGame ()
Load the newest single player autosave and continue playing game.
void DecAutoTurns (int n=1)
Decrease auto turn counter.
int EffectsProcessingThreads () const override
void EliminateSelf ()
Resign from the game.
void ExitApp (int exit_code=0) override
Exit the App with exit_code.
ClientUI & GetClientUI ()
boost::intrusive_ptr< const boost::statechart::event_base > GetDeferredPostedEvent ()
float GLVersion () const
void HandleSaveGamePreviews (const Message &msg)
Update any open SaveGameDialog with previews from the server.
void HandleSetAuthRoles (const Message &msg)
Update this client's authorization roles.
void HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id) override
Handle UI and state updates with changes in turn phase.
bool HaveWindowFocus () const
as far as the HCA knows, does the game window have focus?
void InitAutoTurns (int auto_turns)
Initialize auto turn counter.
bool IsLoadGameAvailable () const
void LoadSinglePlayerGame (std::string filename="")
void MultiPlayerGame ()
shows multiplayer connection window, and then transitions to multiplayer lobby if connected
void NewSinglePlayerGame (bool quickstart=false)
void OpenURL (const std::string &url)
const GGHumanClientApp & operator= (const GGHumanClientApp &)=delete
GGHumanClientApp & operator= (const GGHumanClientApp &&)=delete
void PostDeferredEvent (boost::intrusive_ptr< const boost::statechart::event_base > event)
void Reinitialize ()
void RequestSavePreviews (const std::string &relative_directory)
Requests the savegame previews from the server in relative_directory to the server save directory.
void ResetClientData (bool save_connection=false)
void ResetToIntro (bool skip_savegame)
void SaveGame (const std::string &filename)
saves the current game; blocks until all save-related network traffic is resolved
void SaveGameCompleted ()
Accepts acknowledgement that server has completed the save.
std::string SelectLoadFile ()
Lets the user select a multiplayer save to load.
void SendLoggingConfigToServer ()
If hosting then send the logger state to the server.
void SetSinglePlayerGame (bool sp=true)
bool SinglePlayerGame () const
returns true iff this game is a single-player game
void StartGame (bool is_new_game)
is_new_game should be true for a new game and false for a loaded game.
void StartMultiPlayerGameFromLobby ()
begins
void StartTurn (const SaveGameUIData &ui_data) override
Send the OrderSet and UI data to the server and start a new turn.
void UnreadyTurn ()
Revoke ready state of turn orders.
void UpdateCombatLogManager ()
Check if the CombatLogManager has incomplete logs that need fetching and start fetching them from the server.
void UpdateCombatLogs (const Message &msg)
Public Member Functions inherited from ClientApp
ClientApp (const ClientApp &)=delete
ClientApp (ClientApp &&)=delete
~ClientApp () override=default
int CurrentTurn () const override
Return the current game turn.
int EmpireID () const
Return the empire identifier of the empire this client controls.
ObjectMap & EmpireKnownObjects (int empire_id) override
Return all Objects known to empire_id.
int EmpirePlayerID (int empire_id) const
Return the player identfier of the player controlling the empire empire_id.
Networking::ClientType GetClientType () const
Return The Networking::ClientType of this client.
Empire * GetEmpire (int empire_id) override
Return the Empire identified by empire_id.
Networking::ClientType GetEmpireClientType (int empire_id) const override
Return the Networking::ClientType of the empire empire_id.
Networking::ClientType GetPlayerClientType (int player_id) const override
Return the Networking::ClientType of the player player_id.
Species * GetSpecies (const std::string &name) override
SpeciesManager & GetSpeciesManager () override
const SpeciesManager & GetSpeciesManager () const
SupplyManager & GetSupplyManager () override
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override
Return the for this client visible name of object.
const ClientApp & operator= (const ClientApp &)=delete
ClientApp & operator= (ClientApp &&)=delete
int PlayerID () const
Return the player identifier of this client.
void SendPartialOrders ()
Send turn orders updates to server without starting new turn.
void SetCurrentTurn (int turn)
Set the current game turn of this client to turn.
void SetEmpireID (int empire_id)
Set the identifier of the ::Empire controlled by this client to empire_id.
void SetEmpireStatus (int empire_id, Message::PlayerStatus status)
Set the Message::PlayerStatus status for empire_id.
virtual void StartTurn (const std::string &save_state_string)
Send the OrderSet and AI state to the server and start a new turn.
bool VerifyCheckSum (const Message &msg)
Compare content checksum from server with client content checksum.
std::map< int, PlayerInfo > & Players ()
Return the players in game as PlayerInfo map.
const std::map< int, PlayerInfo > & Players () const
Return the players in game as PlayerInfo map.
Universe & GetUniverse () override
Return the Universe known to this client.
const Universe & GetUniverse () const
Return the Universe known to this client.
GalaxySetupData & GetGalaxySetupData ()
Return the GalaxySetupData of this game.
const GalaxySetupData & GetGalaxySetupData () const override
Return the GalaxySetupData of this game.
OrderSet & Orders ()
Return the OrderSet of this client.
const OrderSet & Orders () const
Return the OrderSet of this client.
ClientNetworking & Networking ()
Return the networking object of this clients player.
const ClientNetworking & Networking () const
Return the networking object of this clients player.
EmpireManager & Empires () override
Return the set of known Empire s for this client.
const EmpireManager & Empires () const
Return the set of known Empire s for this client.
Public Member Functions inherited from IApp
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
virtual void StartBackgroundParsing ()
Start parsing universe object types on a separate thread.
Public Member Functions inherited from SDLGUI
SDLGUI (int w=1024, int h=768, bool calc_FPS=false, std::string app_name="GG", int x=SDL_WINDOWPOS_UNDEFINED, int y=SDL_WINDOWPOS_UNDEFINED, bool fullscreen=false, bool fake_mode_change=false)
virtual ~SDLGUI ()
bool AppHasMouseFocus () const override
GG::Y AppHeight () const override
GG::X AppWidth () const override
std::string ClipboardText () const override
void Enter2DMode () override
void Exit2DMode () override
void ExitApp (int code=0) override
virtual bool FakeModeChange () const final
bool FramebuffersAvailable () const
virtual bool Fullscreen () const final
virtual GG::Pt GetDefaultResolution (int display_id) const override
virtual std::vector< std::string > GetSupportedResolutions () const override
void HandleSystemEvents () override
void RenderBegin () override
void RenderEnd () override
void Run () override
bool SetClipboardText (const std::string &text) override
void SetVideoMode (GG::X width, GG::Y height, bool fullscreen, bool fake_mode_change)
void SetWindowTitle (const std::string &title)
unsigned int Ticks () const override
Static Public Member Functions
static void AddWindowSizeOptionsAfterMainStart (OptionsDB &db)
Adds window dimension options to OptionsDB after the start of main, but before GGHumanClientApp constructor.
static std::string EncodeServerAddressOption (const std::string &server)
Converts server address to correct option name.
static GGHumanClientApp * GetApp ()
returns GGHumanClientApp pointer to the single instance of the app
static std::pair< int, int > GetWindowLeftTop ()
static std::pair< int, int > GetWindowWidthHeight ()
Static Public Member Functions inherited from ClientApp
static ClientApp * GetApp ()
Return the singleton instance of this Application.
Static Public Member Functions inherited from IApp
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Static Public Member Functions inherited from SDLGUI
static GG::Pt GetDefaultResolutionStatic (int display_id)
static SDLGUI * GetGUI ()
allows any code to access the gui framework by calling SDLGUI::GetGUI()
static int MaximumPossibleHeight ()
Returns the largest possible height if all displays are aligned vertically.
static int MaximumPossibleWidth ()
Returns the largest possible width if all displays are aligned horizontally.
static int NumVideoDisplaysStatic ()
Public Attributes
FullscreenSwitchSignalType FullscreenSwitchSignal
RepositionWindowsSignalType RepositionWindowsSignal
Protected Member Functions
void Initialize () override
Provides one-time gui initialization.
Protected Member Functions inherited from ClientApp
ClientApp ()
Protected Member Functions inherited from IApp
IApp ()
Protected Member Functions inherited from SDLGUI
void FinalCleanup ()
Provides one-time gui cleanup.
void GLInit ()
Allows user to specify OpenGL initialization code; called at the end of SDLInit().
void HandleNonGGEvent (const SDL_Event &event)
event handler for all SDL events that are not GG-related.
void ResetFramebuffer ()
Resizes or deletes the framebuffer for fake fullscreen.
void SDLInit ()
Initializes SDL, FE, and SDL OpenGL functionality.
void SDLQuit ()
Cleans up SDL and (if used) FE.
void SetAppSize (const GG::Pt &size)
Private Member Functions
void ConnectKeyboardAcceleratorSignals ()
installs the following 3 global hotkeys: quit, exit, togglefullscreen
void DisconnectedFromServer ()
called by ClientNetworking when the TCP connection to the server is lost
void ExitSDL (int exit_code)
ExitSDL is bound by ResetOrExitApp() to exit the application.
void FreeServer ()
Frees (relinquishes ownership and control of) any running server process already started by this client; performs no cleanup of other processes, such as AIs.
void HandleAppQuitting ()
void HandleFocusChange (bool gained_focus)
bool HandleHotkeyExitApp ()
quit current game & freeorion to Desktop
bool HandleHotkeyResetGame ()
quit current game to IntroScreen
void HandleMessage (Message &&msg)
void HandleResoureDirChange ()
If a game is not running re-parse the universe otherwise inform the player changes will effect new games.
void HandleSystemEvents () override
void HandleWindowMove (GG::X w, GG::Y h)
void HandleWindowResize (GG::X w, GG::Y h)
void RenderBegin () override
void ResetOrExitApp (bool reset, bool skip_savegame, int exit_code=0)
Either reset to IntroMenu (reset is true), or exit the application.
void StartServer ()
Starts a server process on localhost.
bool ToggleFullscreen ()
toggle to/from fullscreen display
void UpdateFPSLimit ()
polls options database to find if FPS should be limited, and if so, to what rate
Private Attributes
int m_auto_turns = 0
auto turn counter
bool m_connected = false
true if we are in a state in which we are supposed to be connected to the server
std::mutex m_event_queue_guard
bool m_exit_handled = false
true when the exit logic is already being handled
std::unique_ptr< HumanClientFSM > m_fsm
std::queue< std::string > m_game_saves_in_progress
Filenames of all in progress saves.
bool m_game_started = false
true when a game is currently in progress
bool m_have_window_focus = true
std::list< boost::intrusive_ptr< const boost::statechart::event_base > > m_posted_event_queue
Process m_server_process
the server process (when hosting a game or playing single player); will be empty when playing multiplayer as a non-host player
bool m_single_player_game = true
true when this game is a single-player game
std::unique_ptr< ClientUI > m_ui
The only instance of the ClientUI.
boost::signals2::signal< void()> SaveGamesCompletedSignal
Additional Inherited Members
Static Protected Member Functions inherited from SDLGUI
static int MaximumPossibleDimension (bool is_width=true)
Given is_width = true (false) it returns the largest possible window width (height) if all displays are aligned horizontally (vertically).
Protected Attributes inherited from ClientApp
int m_current_turn = INVALID_GAME_TURN
int m_empire_id = ALL_EMPIRES
EmpireManager m_empires
GalaxySetupData m_galaxy_setup_data
std::shared_ptr< ClientNetworking > m_networking
OrderSet m_orders
std::map< int, PlayerInfo > m_player_info
Indexed by player id, contains info about all players in the game.
SpeciesManager m_species_manager
SupplyManager m_supply_manager
Universe m_universe
Static Protected Attributes inherited from IApp
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Detailed Description
the application framework class for the human player FreeOrion client.
Member Typedef Documentation
FullscreenSwitchSignalType
typedef boost::signals2::signal<void (bool)> GGHumanClientApp::FullscreenSwitchSignalType
RepositionWindowsSignalType
typedef boost::signals2::signal<void ()> GGHumanClientApp::RepositionWindowsSignalType
Constructor & Destructor Documentation
GGHumanClientApp() [1/4]
GGHumanClientApp::GGHumanClientApp () delete
GGHumanClientApp() [2/4]
GGHumanClientApp::GGHumanClientApp (int width, int height, bool calculate_FPS, std::string name, int x, int y, bool fullscreen, bool fake_mode_change)
References ClientUI::ArtDir(), ConnectKeyboardAcceleratorSignals(), Sound::Enable(), ErrorLogger, SDLGUI::FramebuffersAvailable(), FreeOrionVersionString(), OptionsDB::Get(), ClientUI::GetFont(), anonymous_namespace{GGHumanClientApp.cpp}::GetGLVersion(), anonymous_namespace{GGHumanClientApp.cpp}::GetGLVersionString(), GetOptionsDB(), Sound::GetSound(), GetUserDataDir(), HandleAppQuitting(), HandleFocusChange(), HandleResoureDirChange(), HandleWindowMove(), HandleWindowResize(), InfoLogger, InitLoggingOptionsDBSystem(), InitLoggingSystem(), LogDependencyVersions(), m_auto_turns, m_fsm, m_ui, ClientUI::MessageBox(), OptionsDB::OptionChangedSignal(), OverrideAllLoggersThresholds(), Sound::PlayMusic(), RegisterLinkTags(), RegisterLoggerWithOptionsDB(), OptionsDB::Set(), anonymous_namespace{GGHumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), Sound::SetMusicVolume(), anonymous_namespace{GGHumanClientApp.cpp}::SetStringtableDependentOptionDefaults(), Sound::SetUISoundsVolume(), IApp::StartBackgroundParsing(), ClientUI::TextColor(), to_LogLevel(), UpdateFPSLimit(), UserString(), and ClientUI::WndOuterBorderColor().
GGHumanClientApp() [3/4]
GGHumanClientApp::GGHumanClientApp (const GGHumanClientApp &) delete
GGHumanClientApp() [4/4]
GGHumanClientApp::GGHumanClientApp (GGHumanClientApp &&) delete
~GGHumanClientApp()
GGHumanClientApp::~GGHumanClientApp () override
References DebugLogger, ClientApp::m_networking, m_server_process, and Process::RequestTermination().
Member Function Documentation
AddWindowSizeOptionsAfterMainStart()
void GGHumanClientApp::AddWindowSizeOptionsAfterMainStart (OptionsDB & db) static
Adds window dimension options to OptionsDB after the start of main, but before GGHumanClientApp constructor.
OSX will not tolerate static initialization of SDL, to check screen size.
References OptionsDB::Add(), anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_HEIGHT, anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_LEFT, anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_TOP, anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_WIDTH, SDLGUI::MaximumPossibleHeight(), SDLGUI::MaximumPossibleWidth(), anonymous_namespace{GGHumanClientApp.cpp}::MIN_HEIGHT, anonymous_namespace{GGHumanClientApp.cpp}::MIN_WIDTH, and UserStringNop.
Referenced by mainSetupAndRun().
Autosave()
void GGHumanClientApp::Autosave ()
Autosaves the current game, iff autosaves are enabled and any turn number requirements are met.
References anonymous_namespace{GGHumanClientApp.cpp}::CreateNewAutosaveFilePath(), ClientApp::CurrentTurn(), DebugLogger, ClientApp::EmpireID(), ErrorLogger, OptionsDB::Get(), GetOptionsDB(), GetSaveDir(), GetServerSaveDir(), m_game_started, m_single_player_game, ClientApp::Networking(), PathToString(), ClientApp::PlayerID(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), anonymous_namespace{GGHumanClientApp.cpp}::RemoveOldestFiles(), and SaveGame().
Referenced by ResetOrExitApp(), and StartTurn().
AutoTurnsLeft()
int GGHumanClientApp::AutoTurnsLeft () const
returns number of turns left to execute automatically
References m_auto_turns.
BrowsePath()
void GGHumanClientApp::BrowsePath (const boost::filesystem::path & browse_path)
Opens the users preferred application for file manager at the specified path browse_path.
References DebugLogger, ErrorLogger, InfoLogger, NULL, PathToString(), and WarnLogger.
Referenced by GetClientUI(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), and EncyclopediaDetailPanel::HandleLinkClick().
CancelMultiplayerGameFromLobby()
void GGHumanClientApp::CancelMultiplayerGameFromLobby ()
cancels out of multiplayer game
References m_fsm.
Referenced by PasswordEnterWnd::CancelClicked(), and MultiPlayerLobbyWnd::CancelClicked().
CanSaveNow()
bool GGHumanClientApp::CanSaveNow () const
returns true / false to indicate whether this client can currently safely initiate a game save
References Networking::CLIENT_TYPE_AI_PLAYER, ClientApp::Empires(), ClientApp::GetEmpireClientType(), ClientApp::Networking(), ClientApp::PlayerID(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), and SinglePlayerGame().
Referenced by InGameMenu::Save().
ChangeLoggerThreshold()
void GGHumanClientApp::ChangeLoggerThreshold (const std::string & option_name, LogLevel option_value)
Update the logger in OptionsDB and the other processes if hosting.
References ChangeLoggerThresholdInOptionsDB(), and SendLoggingConfigToServer().
Referenced by anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption().
ConnectKeyboardAcceleratorSignals()
void GGHumanClientApp::ConnectKeyboardAcceleratorSignals () private
installs the following 3 global hotkeys: quit, exit, togglefullscreen
References HotkeyManager::Connect(), HotkeyManager::GetManager(), HandleHotkeyExitApp(), HandleHotkeyResetGame(), NoModalWndsOpenCondition(), HotkeyManager::RebuildShortcuts(), and ToggleFullscreen().
Referenced by GGHumanClientApp().
ContinueSinglePlayerGame()
void GGHumanClientApp::ContinueSinglePlayerGame ()
Load the newest single player autosave and continue playing game.
References LoadSinglePlayerGame(), and anonymous_namespace{GGHumanClientApp.cpp}::NewestSinglePlayerSavegame().
Referenced by mainSetupAndRun(), and IntroScreen::OnContinue().
DecAutoTurns()
void GGHumanClientApp::DecAutoTurns (int n = 1)
Decrease auto turn counter.
References InitAutoTurns(), and m_auto_turns.
DisconnectedFromServer()
void GGHumanClientApp::DisconnectedFromServer () private
called by ClientNetworking when the TCP connection to the server is lost
References DebugLogger, and m_fsm.
Referenced by HandleSystemEvents().
EffectsProcessingThreads()
int GGHumanClientApp::EffectsProcessingThreads () const override virtual
Implements IApp.
References OptionsDB::Get(), and GetOptionsDB().
EliminateSelf()
void GGHumanClientApp::EliminateSelf ()
Resign from the game.
References EliminateSelfMessage(), and ClientApp::m_networking.
Referenced by InGameMenu::Concede().
EncodeServerAddressOption()
std::string GGHumanClientApp::EncodeServerAddressOption (const std::string & server) static
Converts server address to correct option name.
Referenced by MultiPlayerGame(), and WaitingForMPJoinAck::react().
ExitApp()
void GGHumanClientApp::ExitApp (int exit_code = 0) override
Exit the App with exit_code.
References ResetOrExitApp().
Referenced by HandleAppQuitting().
ExitSDL()
void GGHumanClientApp::ExitSDL (int exit_code) private
ExitSDL is bound by ResetOrExitApp() to exit the application.
References SDLGUI::ExitApp().
Referenced by ResetOrExitApp().
FreeServer()
void GGHumanClientApp::FreeServer () private
Frees (relinquishes ownership and control of) any running server process already started by this client; performs no cleanup of other processes, such as AIs.
References ALL_EMPIRES, Process::Free(), Networking::INVALID_PLAYER_ID, ClientApp::m_networking, m_server_process, and ClientApp::SetEmpireID().
Referenced by MultiPlayerGame().
GetApp()
GGHumanClientApp * GGHumanClientApp::GetApp () static
returns GGHumanClientApp pointer to the single instance of the app
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), ProductionWnd::AddBuildToQueueSlot(), DesignWnd::MainPanel::AddDesign(), anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), ResearchWnd::AddTechsToQueueSlot(), TechTreeWnd::AddTechToResearchQueue(), anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), CompletedDesignsListBox::BaseRightClicked(), MapWnd::BuildingRightClicked(), BuildDesignatorWnd::BuildItemRequested(), InGameMenu::CalculatePosition(), GalaxySetupWnd::CalculatePosition(), anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), PasswordEnterWnd::CancelClicked(), MultiPlayerLobbyWnd::CancelClicked(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), BuildDesignatorWnd::CenterOnBuild(), TechTreeWnd::CenterOnTech(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), MultiPlayerLobbyWnd::ChatMessage(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{BuildingsPanel.cpp}::ClientPlayerIsModerator(), anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{SidePanel.cpp}::ClientPlayerIsModerator(), ClientUI::ClientUI(), FleetUIManager::CloseAll(), InGameMenu::CompleteConstruction(), BuildDesignatorWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), IntroScreen::CompleteConstruction(), TechTreeWnd::CompleteConstruction(), DesignWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), ResearchQueueWnd::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), ProductionQueueWnd::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), InGameMenu::Concede(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), MapWnd::DeferredRefreshFleetButtons(), anonymous_namespace{DesignWnd.cpp}::DeleteFromDisplayedDesigns(), ResearchWnd::DeleteQueueItem(), ProductionWnd::DeleteQueueItem(), DesignWnd::MainPanel::DesignChanged(), MapWnd::DispatchFleetsExploring(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability(), anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::DisplayedPolicyAvailability(), FleetWnd::DoLayout(), PolicySlotControl::DropsAcceptable(), FleetDataPanel::DropsAcceptable(), anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings(), MapWnd::EnableOrderIssuing(), SidePanel::PlanetPanel::EnableOrderIssuing(), MapWnd::EndTurn(), MapWnd::FieldRightClicked(), GovernmentWnd::MainPanel::FindEmptySlotForPolicy(), MapWnd::FleetButtonRightClicked(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetWnd::FleetRightClicked(), MapWnd::FleetsRightClicked(), FleetUIManager::FleetWndClosing(), MapWnd::ForgetObject(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ClientUI::GetTexture(), ClientUI::HandleFullscreenSwitch(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), DesignWnd::PartPalette::HandleShipPartRightClicked(), SaveFileDialog::Init(), CUIWnd::Init(), FleetDataPanel::Init(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitTurn(), MapWnd::InitTurnRendering(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{MapWnd.cpp}::IssueFleetExploreOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetResupplyOrder(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), SitRepPanel::LastClicked(), FleetButton::LayoutIcons(), InGameMenu::Load(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), SystemIcon::MouseEnter(), SitRepPanel::NextClicked(), SitRepPanel::NumVisibleSitrepsThisTurn(), ObjectListWnd::ObjectRightClicked(), ObjectListBox::ObjectShown(), PasswordEnterWnd::OkClicked(), IntroScreen::OnContinue(), IntroScreen::OnLoadGame(), IntroScreen::OnMultiPlayer(), IntroScreen::OnQuickStart(), IntroScreen::OnSinglePlayer(), IntroScreen::OnWebsite(), OwnerColoredSystemName::OwnerColoredSystemName(), MapWnd::PlanetRightClicked(), SidePanel::PlanetSelectable(), MapWnd::PlotFleetMovement(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), PoliciesListBox::Populate(), GovernmentWnd::MainPanel::Populate(), PartsListBox::Populate(), MultiPlayerLobbyWnd::PopulatePlayerList(), ServerConnectWnd::PopulateServerList(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), SitRepPanel::PrevClicked(), ProductionWnd::QueueItemDuped(), ResearchWnd::QueueItemMoved(), ProductionWnd::QueueItemMoved(), ResearchWnd::QueueItemPaused(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), BuildingIndicator::RClick(), MapWnd::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), MultiPlayerLobbyWnd::ReadyClicked(), ResearchWnd::Refresh(), FleetButton::Refresh(), BuildDesignatorWnd::Refresh(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), RotatingPlanetControl::Refresh(), FleetDataPanel::Refresh(), ShipsListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshDetectionIndicator(), MapWnd::RefreshFleetResourceIndicator(), TechTreeArcs::Impl::RefreshHighlights(), SidePanel::RefreshImpl(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshInfluenceResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTurnButtonTooltip(), MapWnd::RegisterWindows(), MapWnd::RemoveWindows(), BuildingIndicator::Render(), MapWnd::RenderFields(), anonymous_namespace{SidePanel.cpp}::RenderPlanet(), MapWnd::RenderSystems(), DesignWnd::MainPanel::ReplaceDesign(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), DesignWnd::BaseSelector::Reset(), MapWnd::ResetEmpireShown(), InGameMenu::Resign(), OptionsWnd::ResolutionOption(), MapWnd::RestoreSidePanel(), InGameMenu::Save(), MultiPlayerLobbyWnd::SaveGameBrowse(), anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane(), SidePanel::PlanetPanelContainer::SelectPlanet(), anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), MultiPlayerLobbyWnd::SendUpdate(), BuildDesignatorWnd::SetBuild(), SidePanel::PlanetPanel::SetFocus(), CombatLogWnd::Impl::SetLog(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), GovernmentWnd::MainPanel::SetPolicy(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), ShaderProgram::shaderProgramFactory(), FleetDetailPanel::ShipRightClicked(), MapWnd::ShipsRightClicked(), ClientUI::ShowIntroScreen(), ClientUI::ShowMultiPlayerLobbyWnd(), MapWnd::ShowProduction(), CUIWnd::SizeMove(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), ShipDesignManager::StartGame(), MapWnd::SystemRightClicked(), TechTreeWnd::TechListBox::TechRightClicked(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), FleetWnd::TitleText(), FleetDataPanel::ToggleAggression(), SitRepPanel::Update(), BuildingsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), MapWnd::UpdateEmpireResourcePools(), SaveFileDialog::UpdatePreviewList(), ResearchWnd::UpdateQueue(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), MapWnd::ZoomToHomeSystem(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToPrevFleet(), MapWnd::ZoomToPrevIdleFleet(), MapWnd::ZoomToPrevOwnedSystem(), and MapWnd::ZoomToSystemWithWastedPP().
GetClientUI()
ClientUI& GGHumanClientApp::GetClientUI () inline
References BrowsePath(), GLVersion(), HandleSaveGamePreviews(), HandleSetAuthRoles(), m_ui, OpenURL(), Reinitialize(), and UpdateCombatLogs().
Referenced by BuildDesignatorWnd::CenterOnBuild(), HandleSaveGamePreviews(), HandleTurnPhaseUpdate(), WaitingForSPHostAck::react(), WaitingForMPHostAck::react(), and WaitingForMPJoinAck::react().
GetDeferredPostedEvent()
boost::intrusive_ptr< const boost::statechart::event_base > GGHumanClientApp::GetDeferredPostedEvent ()
References m_event_queue_guard, and m_posted_event_queue.
Referenced by HandleSystemEvents().
GetWindowLeftTop()
std::pair< int, int > GGHumanClientApp::GetWindowLeftTop () static
References OptionsDB::Get(), and GetOptionsDB().
Referenced by mainSetupAndRun().
GetWindowWidthHeight()
std::pair< int, int > GGHumanClientApp::GetWindowWidthHeight () static
References OptionsDB::Commit(), OptionsDB::Get(), SDLGUI::GetDefaultResolutionStatic(), GetOptionsDB(), and OptionsDB::Set().
Referenced by mainSetupAndRun(), and Reinitialize().
GLVersion()
float GGHumanClientApp::GLVersion () const
References anonymous_namespace{GGHumanClientApp.cpp}::GetGLVersion().
Referenced by GetClientUI().
HandleAppQuitting()
void GGHumanClientApp::HandleAppQuitting () private
References DebugLogger, and ExitApp().
Referenced by GGHumanClientApp(), and HandleHotkeyExitApp().
HandleFocusChange()
void GGHumanClientApp::HandleFocusChange (bool gained_focus) private
References DebugLogger, OptionsDB::Get(), GetOptionsDB(), Sound::GetSound(), m_have_window_focus, Sound::PauseMusic(), and Sound::ResumeMusic().
Referenced by GGHumanClientApp().
HandleHotkeyExitApp()
bool GGHumanClientApp::HandleHotkeyExitApp () private
quit current game & freeorion to Desktop
References DebugLogger, and HandleAppQuitting().
Referenced by ConnectKeyboardAcceleratorSignals().
HandleHotkeyResetGame()
bool GGHumanClientApp::HandleHotkeyResetGame () private
quit current game to IntroScreen
References DebugLogger, and ResetToIntro().
Referenced by ConnectKeyboardAcceleratorSignals().
HandleMessage()
void GGHumanClientApp::HandleMessage (Message && msg) private
References ErrorLogger, HandleSaveGamePreviews(), HandleSetAuthRoles(), anonymous_namespace{GGHumanClientApp.cpp}::INSTRUMENT_MESSAGE_HANDLING, and m_fsm.
Referenced by HandleSystemEvents().
HandleResoureDirChange()
void GGHumanClientApp::HandleResoureDirChange () private
If a game is not running re-parse the universe otherwise inform the player changes will effect new games.
References DebugLogger, m_game_started, IApp::StartBackgroundParsing(), and WarnLogger.
Referenced by GGHumanClientApp().
HandleSaveGamePreviews()
void GGHumanClientApp::HandleSaveGamePreviews (const Message & msg)
Update any open SaveGameDialog with previews from the server.
References DebugLogger, ExtractDispatchSavePreviewsMessageData(), GetClientUI(), ClientUI::GetSaveFileDialog(), and PreviewInformation::previews.
Referenced by GetClientUI(), and HandleMessage().
HandleSetAuthRoles()
void GGHumanClientApp::HandleSetAuthRoles (const Message & msg)
Update this client's authorization roles.
References DebugLogger, ExtractSetAuthorizationRolesMessage(), and ClientApp::m_networking.
Referenced by GetClientUI(), and HandleMessage().
HandleSystemEvents()
void GGHumanClientApp::HandleSystemEvents () override private
References DisconnectedFromServer(), ErrorLogger, GetDeferredPostedEvent(), HandleMessage(), SDLGUI::HandleSystemEvents(), m_connected, m_fsm, ClientApp::m_networking, and ClientApp::Networking().
HandleTurnPhaseUpdate()
void GGHumanClientApp::HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id) override virtual
Handle UI and state updates with changes in turn phase.
Reimplemented from ClientApp.
References GetClientUI(), ClientUI::GetMessageWnd(), and ClientApp::HandleTurnPhaseUpdate().
HandleWindowMove()
void GGHumanClientApp::HandleWindowMove (GG::X w, GG::Y h) private
References OptionsDB::Commit(), SDLGUI::Fullscreen(), GetOptionsDB(), and OptionsDB::Set().
Referenced by GGHumanClientApp().
HandleWindowResize()
void GGHumanClientApp::HandleWindowResize (GG::X w, GG::Y h) private
References OptionsDB::Commit(), ClientUI::GetClientUI(), GetOptionsDB(), RepositionWindowsSignal, and OptionsDB::Set().
Referenced by GGHumanClientApp().
HaveWindowFocus()
bool GGHumanClientApp::HaveWindowFocus () const
as far as the HCA knows, does the game window have focus?
References m_have_window_focus.
InitAutoTurns()
void GGHumanClientApp::InitAutoTurns (int auto_turns)
Initialize auto turn counter.
References m_auto_turns, and m_game_started.
Referenced by DecAutoTurns().
Initialize()
void GGHumanClientApp::Initialize () override protected virtual
Provides one-time gui initialization.
Implements SDLGUI.
IsLoadGameAvailable()
bool GGHumanClientApp::IsLoadGameAvailable () const
References anonymous_namespace{GGHumanClientApp.cpp}::NewestSinglePlayerSavegame().
Referenced by IntroScreen::CompleteConstruction().
LoadSinglePlayerGame()
void GGHumanClientApp::LoadSinglePlayerGame (std::string filename = "")
References ALL_EMPIRES, DebugLogger, ErrorLogger, SinglePlayerSetupData::filename, FilenameToPath(), ClientUI::GetClientUI(), ClientUI::GetFilenameWithSaveFileDialog(), GetOptionsDB(), HostSPGameMessage(), Networking::INVALID_PLAYER_ID, SaveFileDialog::Load, m_connected, m_fsm, m_game_started, ClientApp::m_networking, m_single_player_game, m_ui, ClientUI::MessageBox(), SinglePlayerSetupData::new_game, ResetToIntro(), ClientApp::SetEmpireID(), SaveFileDialog::SinglePlayer, StartServer(), and UserString().
Referenced by ContinueSinglePlayerGame(), InGameMenu::Load(), mainSetupAndRun(), and IntroScreen::OnLoadGame().
MultiPlayerGame()
void GGHumanClientApp::MultiPlayerGame ()
shows multiplayer connection window, and then transitions to multiplayer lobby if connected
References OptionsDB::Add(), anonymous_namespace{GGHumanClientApp.cpp}::ClearPreviousPendingSaves(), EncodeServerAddressOption(), ErrorLogger, FreeServer(), anonymous_namespace{Random.cpp}::gen, OptionsDB::Get(), GetOptionsDB(), HostMPGameMessage(), JoinGameMessage(), m_connected, m_fsm, m_game_saves_in_progress, ClientApp::m_networking, m_single_player_game, ClientUI::MessageBox(), OptionsDB::OptionExists(), ResetToIntro(), OptionsDB::Set(), StartServer(), to_string(), UserString(), and WarnLogger.
Referenced by IntroScreen::OnMultiPlayer().
NewSinglePlayerGame()
void GGHumanClientApp::NewSinglePlayerGame (bool quickstart = false)
References GalaxySetupData::age, GalaxySetupData::ai_aggr, ALL_EMPIRES, anonymous_namespace{GGHumanClientApp.cpp}::ClearPreviousPendingSaves(), PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, PlayerSetupData::empire_color, PlayerSetupData::empire_name, EmpireColors(), ErrorLogger, SinglePlayerSetupData::filename, GalaxySetupData::game_rules, parse::game_rules(), OptionsDB::Get(), GetGameRules(), GetOptionsDB(), GameRules::GetRulesAsStrings(), ClientApp::GetSpecies(), ClientApp::GetSpeciesManager(), HostSPGameMessage(), m_connected, m_fsm, m_game_saves_in_progress, ClientApp::m_networking, m_single_player_game, ClientUI::MessageBox(), GalaxySetupData::monster_freq, GalaxySetupData::native_freq, SinglePlayerSetupData::new_game, SpeciesManager::NumPlayableSpecies(), GalaxySetupData::planet_density, SpeciesManager::playable_begin(), PlayerSetupData::player_name, SinglePlayerSetupData::players, ResetToIntro(), PlayerSetupData::save_game_empire_id, GalaxySetupData::SetSeed(), GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, PlayerSetupData::starting_species_name, StartServer(), to_string(), TraceLogger, and UserString().
Referenced by mainSetupAndRun(), IntroScreen::OnQuickStart(), and IntroScreen::OnSinglePlayer().
OpenURL()
void GGHumanClientApp::OpenURL (const std::string & url)
References ErrorLogger.
Referenced by GetClientUI(), EncyclopediaDetailPanel::HandleLinkClick(), and IntroScreen::OnWebsite().
operator=() [1/2]
const GGHumanClientApp& GGHumanClientApp::operator= (const GGHumanClientApp &) delete
operator=() [2/2]
GGHumanClientApp& GGHumanClientApp::operator= (const GGHumanClientApp &&) delete
PostDeferredEvent()
void GGHumanClientApp::PostDeferredEvent (boost::intrusive_ptr< const boost::statechart::event_base > event)
References m_event_queue_guard, and m_posted_event_queue.
Reinitialize()
void GGHumanClientApp::Reinitialize ()
References SDLGUI::AppHeight(), SDLGUI::AppWidth(), SDLGUI::Fullscreen(), FullscreenSwitchSignal, OptionsDB::Get(), GetOptionsDB(), GetWindowWidthHeight(), RepositionWindowsSignal, and SDLGUI::SetVideoMode().
Referenced by GetClientUI(), OptionsWnd::ResolutionOption(), and ToggleFullscreen().
RenderBegin()
void GGHumanClientApp::RenderBegin () override private
References Sound::DoFrame(), Sound::GetSound(), and SDLGUI::RenderBegin().
RequestSavePreviews()
void GGHumanClientApp::RequestSavePreviews (const std::string & relative_directory)
Requests the savegame previews from the server in relative_directory to the server save directory.
References DebugLogger, ErrorLogger, m_connected, ClientApp::m_networking, m_single_player_game, ClientUI::MessageBox(), RequestSavePreviewsMessage(), ResetToIntro(), SendLoggingConfigToServer(), StartServer(), TraceLogger, and UserString().
Referenced by SaveFileDialog::UpdatePreviewList().
ResetClientData()
void GGHumanClientApp::ResetClientData (bool save_connection = false)
References ALL_EMPIRES, CombatLogManager::Clear(), EmpireManager::Clear(), Universe::Clear(), anonymous_namespace{GGHumanClientApp.cpp}::ClearPreviousPendingSaves(), GetCombatLogManager(), Networking::INVALID_PLAYER_ID, ClientApp::m_empires, m_game_saves_in_progress, ClientApp::m_networking, ClientApp::m_orders, m_ui, ClientApp::m_universe, OrderSet::Reset(), and ClientApp::SetEmpireID().
Referenced by ResetOrExitApp().
ResetOrExitApp()
void GGHumanClientApp::ResetOrExitApp (bool reset, bool skip_savegame, int exit_code = 0) private
Either reset to IntroMenu (reset is true), or exit the application.
If skip_savegame is true abort in progress save games. exit_code is the exit code.
References Autosave(), Networking::CLIENT_TYPE_HUMAN_PLAYER, ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), DebugLogger, ExitSDL(), OptionsDB::Get(), ClientApp::GetClientType(), EmpireManager::GetEmpire(), ClientUI::GetFont(), GetOptionsDB(), ClientApp::m_empire_id, ClientApp::m_empires, m_exit_handled, m_fsm, m_game_saves_in_progress, m_game_started, m_server_process, m_single_player_game, ClientUI::Pts(), ResetClientData(), SaveGamesCompletedSignal, ClientUI::TextColor(), UserString(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
Referenced by ExitApp(), and ResetToIntro().
ResetToIntro()
void GGHumanClientApp::ResetToIntro (bool skip_savegame)
References ResetOrExitApp().
Referenced by HandleHotkeyResetGame(), LoadSinglePlayerGame(), MultiPlayerGame(), NewSinglePlayerGame(), RequestSavePreviews(), and InGameMenu::Resign().
SaveGame()
void GGHumanClientApp::SaveGame (const std::string & filename)
saves the current game; blocks until all save-related network traffic is resolved
References DebugLogger, HostSaveGameInitiateMessage(), m_game_saves_in_progress, and ClientApp::m_networking.
Referenced by Autosave(), and InGameMenu::Save().
SaveGameCompleted()
void GGHumanClientApp::SaveGameCompleted ()
Accepts acknowledgement that server has completed the save.
References DebugLogger, HostSaveGameInitiateMessage(), m_game_saves_in_progress, ClientApp::m_networking, and SaveGamesCompletedSignal.
SelectLoadFile()
std::string GGHumanClientApp::SelectLoadFile ()
Lets the user select a multiplayer save to load.
References ClientUI::GetClientUI(), ClientUI::GetFilenameWithSaveFileDialog(), SaveFileDialog::Load, and SaveFileDialog::MultiPlayer.
Referenced by MultiPlayerLobbyWnd::SaveGameBrowse().
SendLoggingConfigToServer()
void GGHumanClientApp::SendLoggingConfigToServer ()
If hosting then send the logger state to the server.
References both, LoggerConfigMessage(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), ClientApp::m_networking, and ClientApp::PlayerID().
Referenced by ChangeLoggerThreshold(), and RequestSavePreviews().
SetSinglePlayerGame()
void GGHumanClientApp::SetSinglePlayerGame (bool sp = true)
References m_single_player_game.
SinglePlayerGame()
bool GGHumanClientApp::SinglePlayerGame () const
returns true iff this game is a single-player game
References m_single_player_game.
Referenced by CanSaveNow(), InGameMenu::CompleteConstruction(), SaveFileDialog::Init(), MapWnd::RefreshTurnButtonTooltip(), and InGameMenu::Save().
StartGame()
void GGHumanClientApp::StartGame (bool is_new_game)
is_new_game should be true for a new game and false for a loaded game.
References ClientApp::EmpireID(), ClientUI::GetClientUI(), ClientUI::GetShipDesignManager(), m_game_started, ShipDesignManager::StartGame(), and UpdateCombatLogManager().
StartMultiPlayerGameFromLobby()
void GGHumanClientApp::StartMultiPlayerGameFromLobby ()
begins
References m_fsm.
StartServer()
void GGHumanClientApp::StartServer () private
Starts a server process on localhost.
Throws a runtime_error if the server process can't be started.
Throws LocalServerAlreadyRunningException (derived from runtime_error in GGHumanClientApp.cpp) if another server is already running.
References tag_parser::args, DebugLogger, ErrorLogger, OptionsDB::Get(), GetOptionsDB(), ClientApp::m_networking, m_server_process, m_single_player_game, and anonymous_namespace{GGHumanClientApp.cpp}::ServerClientExe().
Referenced by LoadSinglePlayerGame(), MultiPlayerGame(), NewSinglePlayerGame(), and RequestSavePreviews().
StartTurn()
void GGHumanClientApp::StartTurn (const SaveGameUIData & ui_data) override virtual
Send the OrderSet and UI data to the server and start a new turn.
Reimplemented from ClientApp.
References Autosave(), ClientApp::CurrentTurn(), DebugLogger, ClientApp::EmpireID(), OptionsDB::Get(), ClientApp::GetEmpire(), GetOptionsDB(), m_fsm, m_single_player_game, and ClientApp::StartTurn().
Referenced by MapWnd::EndTurn().
ToggleFullscreen()
bool GGHumanClientApp::ToggleFullscreen () private
toggle to/from fullscreen display
References OptionsDB::Get(), GetOptionsDB(), Reinitialize(), and OptionsDB::Set().
Referenced by ConnectKeyboardAcceleratorSignals().
UnreadyTurn()
void GGHumanClientApp::UnreadyTurn ()
Revoke ready state of turn orders.
References ClientApp::m_networking, and UnreadyMessage().
Referenced by MapWnd::EndTurn().
UpdateCombatLogManager()
void GGHumanClientApp::UpdateCombatLogManager ()
Check if the CombatLogManager has incomplete logs that need fetching and start fetching them from the server.
References GetCombatLogManager(), CombatLogManager::IncompleteLogIDs(), ClientApp::m_networking, and RequestCombatLogsMessage().
Referenced by StartGame().
UpdateCombatLogs()
void GGHumanClientApp::UpdateCombatLogs (const Message & msg)
References CombatLogManager::CompleteLog(), ExtractDispatchCombatLogsMessageData(), and GetCombatLogManager().
Referenced by GetClientUI().
UpdateFPSLimit()
void GGHumanClientApp::UpdateFPSLimit () private
polls options database to find if FPS should be limited, and if so, to what rate
References DebugLogger, OptionsDB::Get(), and GetOptionsDB().
Referenced by GGHumanClientApp().
Member Data Documentation
FullscreenSwitchSignal
FullscreenSwitchSignalType GGHumanClientApp::FullscreenSwitchSignal mutable
Referenced by ClientUI::ClientUI(), CUIWnd::Init(), and Reinitialize().
m_auto_turns
int GGHumanClientApp::m_auto_turns = 0 private
auto turn counter
Referenced by AutoTurnsLeft(), DecAutoTurns(), GGHumanClientApp(), and InitAutoTurns().
m_connected
bool GGHumanClientApp::m_connected = false private
true if we are in a state in which we are supposed to be connected to the server
Referenced by HandleSystemEvents(), LoadSinglePlayerGame(), MultiPlayerGame(), NewSinglePlayerGame(), and RequestSavePreviews().
m_event_queue_guard
std::mutex GGHumanClientApp::m_event_queue_guard private
Referenced by GetDeferredPostedEvent(), and PostDeferredEvent().
m_exit_handled
bool GGHumanClientApp::m_exit_handled = false private
true when the exit logic is already being handled
Referenced by ResetOrExitApp().
m_fsm
std::unique_ptr<HumanClientFSM> GGHumanClientApp::m_fsm private
Referenced by CancelMultiplayerGameFromLobby(), DisconnectedFromServer(), GGHumanClientApp(), HandleMessage(), HandleSystemEvents(), LoadSinglePlayerGame(), MultiPlayerGame(), NewSinglePlayerGame(), ResetOrExitApp(), StartMultiPlayerGameFromLobby(), and StartTurn().
m_game_saves_in_progress
std::queue<std::string> GGHumanClientApp::m_game_saves_in_progress private
Filenames of all in progress saves.
There maybe multiple saves in progress if a player and an autosave are initiated at the same time.
Referenced by MultiPlayerGame(), NewSinglePlayerGame(), ResetClientData(), ResetOrExitApp(), SaveGame(), and SaveGameCompleted().
m_game_started
bool GGHumanClientApp::m_game_started = false private
true when a game is currently in progress
Referenced by Autosave(), HandleResoureDirChange(), InitAutoTurns(), LoadSinglePlayerGame(), ResetOrExitApp(), and StartGame().
m_have_window_focus
bool GGHumanClientApp::m_have_window_focus = true private
Referenced by HandleFocusChange(), and HaveWindowFocus().
m_posted_event_queue
std::list<boost::intrusive_ptr<const boost::statechart::event_base> > GGHumanClientApp::m_posted_event_queue private
Referenced by GetDeferredPostedEvent(), and PostDeferredEvent().
m_server_process
Process GGHumanClientApp::m_server_process private
the server process (when hosting a game or playing single player); will be empty when playing multiplayer as a non-host player
Referenced by FreeServer(), ResetOrExitApp(), StartServer(), and ~GGHumanClientApp().
m_single_player_game
bool GGHumanClientApp::m_single_player_game = true private
true when this game is a single-player game
Referenced by Autosave(), LoadSinglePlayerGame(), MultiPlayerGame(), NewSinglePlayerGame(), RequestSavePreviews(), ResetOrExitApp(), SetSinglePlayerGame(), SinglePlayerGame(), StartServer(), and StartTurn().
m_ui
std::unique_ptr<ClientUI> GGHumanClientApp::m_ui private
The only instance of the ClientUI.
Referenced by GetClientUI(), GGHumanClientApp(), LoadSinglePlayerGame(), and ResetClientData().
RepositionWindowsSignal
RepositionWindowsSignalType GGHumanClientApp::RepositionWindowsSignal mutable
Referenced by ClientUI::ClientUI(), BuildDesignatorWnd::CompleteConstruction(), TechTreeWnd::CompleteConstruction(), DesignWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), ClientUI::HandleFullscreenSwitch(), HandleWindowResize(), CUIWnd::Init(), and Reinitialize().
SaveGamesCompletedSignal
boost::signals2::signal<void ()> GGHumanClientApp::SaveGamesCompletedSignal private
Referenced by ResetOrExitApp(), and SaveGameCompleted().
The documentation for this class was generated from the following files:
GGHumanClientApp.h
GGHumanClientApp.cpp