FreeOrion: ModeratorActionsWnd Class Reference
ModeratorActionsWnd Class Reference
#include <ModeratorActionsWnd.h>
Public Member Functions
Structors //!@{
ModeratorActionsWnd (const std::string &config_name="")
void CompleteConstruction () override
virtual ~ModeratorActionsWnd ()
Accessors
ModeratorActionSetting SelectedAction () const
PlanetType SelectedPlanetType () const
PlanetSize SelectedPlanetSize () const
StarType SelectedStarType () const
int SelectedEmpire () const
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Refresh ()
void EnableActions (bool enable=true)
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Flash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void StopFlash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetFlashDuration (int ms)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void()> AddStarlaneActionSelectedSignal
boost::signals2::signal< void()> ClosingSignal
boost::signals2::signal< void(PlanetType)> CreatePlanetActionSelectedSignal
boost::signals2::signal< void(StarType)> CreateSystemActionSelectedSignal
boost::signals2::signal< void()> DeleteObjectActionSelectedSignal
boost::signals2::signal< void()> NoActionSelectedSignal
boost::signals2::signal< void(int)> SetOwnerActionSelectedSignal
Private Member Functions
void AddStarlane ()
void CloseClicked () override
called when window is closed via the close button
void CreatePlanet ()
void CreateSystem ()
void DeleteObject ()
void DoLayout ()
int EmpireIDFromIndex (std::size_t i) const
void NoAction ()
PlanetSize PlanetSizeFromIndex (std::size_t i) const
PlanetType PlanetTypeFromIndex (std::size_t i) const
void RemoveStarlane ()
void SetOwner ()
StarType StarTypeFromIndex (std::size_t i) const
Private Attributes
bool m_actions_enabled
std::shared_ptr< GG::Button > m_add_starlane_button
std::shared_ptr< GG::Button > m_create_planet_button
std::shared_ptr< GG::Button > m_create_system_button
std::shared_ptr< GG::Button > m_delete_object_button
std::shared_ptr< GG::DropDownList > m_empire_drop
std::shared_ptr< GG::Button > m_no_action_button
std::shared_ptr< GG::DropDownList > m_planet_size_drop
std::shared_ptr< GG::DropDownList > m_planet_type_drop
std::shared_ptr< GG::Button > m_remove_starlane_button
ModeratorActionSetting m_selected_action
std::shared_ptr< GG::Button > m_set_owner_button
std::shared_ptr< GG::DropDownList > m_star_type_drop
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Constructor & Destructor Documentation
ModeratorActionsWnd()
ModeratorActionsWnd::ModeratorActionsWnd (const std::string & config_name = "")
~ModeratorActionsWnd()
ModeratorActionsWnd::~ModeratorActionsWnd () virtual
Member Function Documentation
AddStarlane()
void ModeratorActionsWnd::AddStarlane () private
References AddStarlaneActionSelectedSignal, m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, and MAS_AddStarlane.
Referenced by CompleteConstruction().
CloseClicked()
void ModeratorActionsWnd::CloseClicked () override private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal.
CompleteConstruction()
void ModeratorActionsWnd::CompleteConstruction () override
References AddStarlane(), ClientUI::ArtDir(), CUIWnd::CompleteConstruction(), anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_HEIGHT(), anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_WIDTH(), CreatePlanet(), CreateSystem(), DeleteObject(), DoLayout(), anonymous_namespace{ModeratorActionsWnd.cpp}::DROP_WIDTH(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), GetOptionsDB(), ClientUI::GetTexture(), m_add_starlane_button, m_create_planet_button, m_create_system_button, m_delete_object_button, m_empire_drop, m_no_action_button, m_planet_size_drop, m_planet_type_drop, m_remove_starlane_button, m_set_owner_button, m_star_type_drop, NoAction(), ClientUI::PlanetIcon(), ClientUI::PlanetSizeIcon(), RemoveStarlane(), CUIWnd::SaveDefaultedOptions(), SetOwner(), STAR_BLUE, ClientUI::StarTypeFilePrefixes(), SZ_TINY, and UserString().
CreatePlanet()
void ModeratorActionsWnd::CreatePlanet () private
References CreatePlanetActionSelectedSignal, m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, and SelectedPlanetType().
Referenced by CompleteConstruction().
CreateSystem()
void ModeratorActionsWnd::CreateSystem () private
References CreateSystemActionSelectedSignal, m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, MAS_CreateSystem, and SelectedStarType().
Referenced by CompleteConstruction().
DeleteObject()
void ModeratorActionsWnd::DeleteObject () private
References DeleteObjectActionSelectedSignal, m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, and MAS_Destroy.
Referenced by CompleteConstruction().
DoLayout()
void ModeratorActionsWnd::DoLayout () private
References anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_HEIGHT(), anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_WIDTH(), anonymous_namespace{ModeratorActionsWnd.cpp}::DROP_WIDTH(), m_add_starlane_button, m_create_planet_button, m_create_system_button, m_delete_object_button, m_empire_drop, m_no_action_button, m_planet_size_drop, m_planet_type_drop, m_remove_starlane_button, m_set_owner_button, m_star_type_drop, and anonymous_namespace{ModeratorActionsWnd.cpp}::PAD().
Referenced by CompleteConstruction(), and SizeMove().
EmpireIDFromIndex()
int ModeratorActionsWnd::EmpireIDFromIndex (std::size_t i) const private
References ALL_EMPIRES, and Empires().
Referenced by SelectedEmpire().
EnableActions()
void ModeratorActionsWnd::EnableActions (bool enable = true)
References m_actions_enabled.
NoAction()
void ModeratorActionsWnd::NoAction () private
References m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, MAS_NoAction, and NoActionSelectedSignal.
Referenced by CompleteConstruction().
PlanetSizeFromIndex()
PlanetSize ModeratorActionsWnd::PlanetSizeFromIndex (std::size_t i) const private
References SZ_MEDIUM.
Referenced by SelectedPlanetSize().
PlanetTypeFromIndex()
PlanetType ModeratorActionsWnd::PlanetTypeFromIndex (std::size_t i) const private
Referenced by SelectedPlanetType().
Refresh()
void ModeratorActionsWnd::Refresh ()
References Empire::Color(), Empires(), m_empire_drop, Empire::Name(), and UserString().
RemoveStarlane()
void ModeratorActionsWnd::RemoveStarlane () private
References AddStarlaneActionSelectedSignal, m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, and MAS_RemoveStarlane.
Referenced by CompleteConstruction().
SelectedAction()
ModeratorActionSetting ModeratorActionsWnd::SelectedAction () const
References m_selected_action.
SelectedEmpire()
int ModeratorActionsWnd::SelectedEmpire () const
References EmpireIDFromIndex(), and m_empire_drop.
Referenced by SetOwner().
SelectedPlanetSize()
PlanetSize ModeratorActionsWnd::SelectedPlanetSize () const
References m_planet_size_drop, and PlanetSizeFromIndex().
SelectedPlanetType()
PlanetType ModeratorActionsWnd::SelectedPlanetType () const
References m_planet_type_drop, and PlanetTypeFromIndex().
Referenced by CreatePlanet().
SelectedStarType()
StarType ModeratorActionsWnd::SelectedStarType () const
References m_star_type_drop, and StarTypeFromIndex().
Referenced by CreateSystem().
SetOwner()
void ModeratorActionsWnd::SetOwner () private
References m_empire_drop, m_planet_size_drop, m_planet_type_drop, m_selected_action, m_star_type_drop, MAS_SetOwner, SelectedEmpire(), and SetOwnerActionSelectedSignal.
Referenced by CompleteConstruction().
SizeMove()
void ModeratorActionsWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
StarTypeFromIndex()
StarType ModeratorActionsWnd::StarTypeFromIndex (std::size_t i) const private
References STAR_BLUE.
Referenced by SelectedStarType().
Member Data Documentation
AddStarlaneActionSelectedSignal
boost::signals2::signal<void ()> ModeratorActionsWnd::AddStarlaneActionSelectedSignal mutable
Referenced by AddStarlane(), and RemoveStarlane().
ClosingSignal
boost::signals2::signal<void ()> ModeratorActionsWnd::ClosingSignal mutable
Referenced by CloseClicked().
CreatePlanetActionSelectedSignal
boost::signals2::signal<void (PlanetType)> ModeratorActionsWnd::CreatePlanetActionSelectedSignal mutable
Referenced by CreatePlanet().
CreateSystemActionSelectedSignal
boost::signals2::signal<void (StarType)> ModeratorActionsWnd::CreateSystemActionSelectedSignal mutable
Referenced by CreateSystem().
DeleteObjectActionSelectedSignal
boost::signals2::signal<void ()> ModeratorActionsWnd::DeleteObjectActionSelectedSignal mutable
Referenced by DeleteObject().
m_actions_enabled
bool ModeratorActionsWnd::m_actions_enabled private
Referenced by EnableActions().
m_add_starlane_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_add_starlane_button private
Referenced by CompleteConstruction(), and DoLayout().
m_create_planet_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_create_planet_button private
Referenced by CompleteConstruction(), and DoLayout().
m_create_system_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_create_system_button private
Referenced by CompleteConstruction(), and DoLayout().
m_delete_object_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_delete_object_button private
Referenced by CompleteConstruction(), and DoLayout().
m_empire_drop
std::shared_ptr<GG::DropDownList> ModeratorActionsWnd::m_empire_drop private
Referenced by AddStarlane(), CompleteConstruction(), CreatePlanet(), CreateSystem(), DeleteObject(), DoLayout(), NoAction(), Refresh(), RemoveStarlane(), SelectedEmpire(), and SetOwner().
m_no_action_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_no_action_button private
Referenced by CompleteConstruction(), and DoLayout().
m_planet_size_drop
std::shared_ptr<GG::DropDownList> ModeratorActionsWnd::m_planet_size_drop private
Referenced by AddStarlane(), CompleteConstruction(), CreatePlanet(), CreateSystem(), DeleteObject(), DoLayout(), NoAction(), RemoveStarlane(), SelectedPlanetSize(), and SetOwner().
m_planet_type_drop
std::shared_ptr<GG::DropDownList> ModeratorActionsWnd::m_planet_type_drop private
Referenced by AddStarlane(), CompleteConstruction(), CreatePlanet(), CreateSystem(), DeleteObject(), DoLayout(), NoAction(), RemoveStarlane(), SelectedPlanetType(), and SetOwner().
m_remove_starlane_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_remove_starlane_button private
Referenced by CompleteConstruction(), and DoLayout().
m_selected_action
ModeratorActionSetting ModeratorActionsWnd::m_selected_action private
Referenced by AddStarlane(), CreatePlanet(), CreateSystem(), DeleteObject(), NoAction(), RemoveStarlane(), SelectedAction(), and SetOwner().
m_set_owner_button
std::shared_ptr<GG::Button> ModeratorActionsWnd::m_set_owner_button private
Referenced by CompleteConstruction(), and DoLayout().
m_star_type_drop
std::shared_ptr<GG::DropDownList> ModeratorActionsWnd::m_star_type_drop private
Referenced by AddStarlane(), CompleteConstruction(), CreatePlanet(), CreateSystem(), DeleteObject(), DoLayout(), NoAction(), RemoveStarlane(), SelectedStarType(), and SetOwner().
NoActionSelectedSignal
boost::signals2::signal<void ()> ModeratorActionsWnd::NoActionSelectedSignal mutable
Referenced by NoAction().
SetOwnerActionSelectedSignal
boost::signals2::signal<void (int)> ModeratorActionsWnd::SetOwnerActionSelectedSignal mutable
Referenced by SetOwner().
The documentation for this class was generated from the following files:
ModeratorActionsWnd.h
ModeratorActionsWnd.cpp