FreeOrion: ChangeFocusOrder Class Reference
ChangeFocusOrder Class Reference
the Order subclass that represents changing a planet focus
#include <Order.h>
Public Member Functions
ChangeFocusOrder (int empire, int planet, const std::string &focus)
int PlanetID () const
Public Member Functions inherited from Order
Order ()
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Static Public Member Functions
static bool Check (int empire_id, int planet_id, const std::string &focus)
Private Member Functions
ChangeFocusOrder ()=default
void ExecuteImpl () const override
Preconditions of execute:
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_focus = ""
int m_planet = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents changing a planet focus
Constructor & Destructor Documentation
ChangeFocusOrder() [1/2]
ChangeFocusOrder::ChangeFocusOrder (int empire, int planet, const std::string & focus)
References Check().
ChangeFocusOrder() [2/2]
ChangeFocusOrder::ChangeFocusOrder () private default
Member Function Documentation
Check()
bool ChangeFocusOrder::Check (int empire_id, int planet_id, const std::string & focus) static
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by ChangeFocusOrder(), and ExecuteImpl().
ExecuteImpl()
void ChangeFocusOrder::ExecuteImpl () const override private virtual
Preconditions of execute:
the designated planet must exist, be owned by the issuing empire
Postconditions:
the planet focus is changed
Implements Order.
References Check(), Order::EmpireID(), ObjectMap::get(), Order::GetValidatedEmpire(), m_focus, m_planet, Objects(), and ResourceCenter::SetFocus().
PlanetID()
int ChangeFocusOrder::PlanetID () const inline
References Order::ExecuteImpl().
serialize()
template<typename Archive > void ChangeFocusOrder::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_focus
std::string ChangeFocusOrder::m_focus = "" private
Referenced by ExecuteImpl().
m_planet
int ChangeFocusOrder::m_planet = INVALID_OBJECT_ID private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp