FreeOrion: GraphControl Class Reference
GraphControl Class Reference
#include <GraphControl.h>
Public Member Functions
Structors //@{
GraphControl ()
Mutators //@{
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void AddSeries (const std::vector< std::pair< double, double >> &data, const GG::Clr &clr)
void Clear ()
void SetXMin (double x_min)
void SetYMin (double y_min)
void SetXMax (double x_max)
void SetYMax (double y_max)
void SetRange (double x1, double x2, double y1, double y2)
void AutoSetRange ()
void ShowPoints (bool show=true)
void ShowLines (bool show=true)
void ShowScale (bool show=true)
void UseLogScale (bool log=true)
void ScaleToZero (bool zero=true)
Private Member Functions
void DoLayout ()
Private Attributes
GG::GLRGBAColorBuffer m_colour_buf
std::vector< std::pair< std::vector< std::pair< double, double > >, GG::Clr > > m_data
bool m_log_scale = false
bool m_show_lines = true
bool m_show_points = true
bool m_show_scale = true
GG::GL2DVertexBuffer m_vert_buf
double m_x_max = 1.0f
double m_x_min = 0.0f
double m_y_max = 1.0f
double m_y_min = 0.0f
std::map< GG::Y, double > m_y_scale_ticks
bool m_zero_in_range = false
Constructor & Destructor Documentation
GraphControl()
GraphControl::GraphControl ()
References AutoSetRange().
Member Function Documentation
AddSeries()
void GraphControl::AddSeries (const std::vector< std::pair< double, double >> & data, const GG::Clr & clr)
References DoLayout(), and m_data.
AutoSetRange()
void GraphControl::AutoSetRange ()
References m_data, and SetRange().
Referenced by GraphControl().
Clear()
void GraphControl::Clear ()
References DoLayout(), and m_data.
DoLayout()
void GraphControl::DoLayout () private
References m_colour_buf, m_data, m_log_scale, m_show_scale, m_vert_buf, m_x_max, m_x_min, m_y_max, m_y_min, m_y_scale_ticks, m_zero_in_range, anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, and ClientUI::WndColor().
Referenced by AddSeries(), Clear(), ScaleToZero(), SetRange(), SetXMax(), SetXMin(), SetYMax(), SetYMin(), ShowLines(), ShowPoints(), ShowScale(), SizeMove(), and UseLogScale().
RClick()
void GraphControl::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_log_scale, m_show_lines, m_show_points, m_show_scale, m_zero_in_range, ScaleToZero(), ShowLines(), ShowPoints(), ShowScale(), UseLogScale(), and UserString().
Render()
void GraphControl::Render () override
References ClientUI::GetFont(), m_colour_buf, m_show_lines, m_show_points, m_show_scale, m_vert_buf, m_y_scale_ticks, anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, ClientUI::TextColor(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
ScaleToZero()
void GraphControl::ScaleToZero (bool zero = true)
References DoLayout(), and m_zero_in_range.
Referenced by RClick().
SetRange()
void GraphControl::SetRange (double x1, double x2, double y1, double y2)
References DoLayout(), m_x_max, m_x_min, m_y_max, and m_y_min.
Referenced by AutoSetRange().
SetXMax()
void GraphControl::SetXMax (double x_max)
References DoLayout(), and m_x_max.
SetXMin()
void GraphControl::SetXMin (double x_min)
References DoLayout(), and m_x_min.
SetYMax()
void GraphControl::SetYMax (double y_max)
References DoLayout(), and m_y_max.
SetYMin()
void GraphControl::SetYMin (double y_min)
References DoLayout(), and m_y_min.
ShowLines()
void GraphControl::ShowLines (bool show = true)
References DoLayout(), and m_show_lines.
Referenced by RClick().
ShowPoints()
void GraphControl::ShowPoints (bool show = true)
References DoLayout(), and m_show_points.
Referenced by RClick().
ShowScale()
void GraphControl::ShowScale (bool show = true)
References DoLayout(), and m_show_scale.
Referenced by RClick().
SizeMove()
void GraphControl::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
UseLogScale()
void GraphControl::UseLogScale (bool log = true)
References DoLayout(), and m_log_scale.
Referenced by RClick().
Member Data Documentation
m_colour_buf
GG::GLRGBAColorBuffer GraphControl::m_colour_buf private
Referenced by DoLayout(), and Render().
m_data
std::vector<std::pair<std::vector<std::pair<double, double> >, GG::Clr> > GraphControl::m_data private
Referenced by AddSeries(), AutoSetRange(), Clear(), and DoLayout().
m_log_scale
bool GraphControl::m_log_scale = false private
Referenced by DoLayout(), RClick(), and UseLogScale().
m_show_lines
bool GraphControl::m_show_lines = true private
Referenced by RClick(), Render(), and ShowLines().
m_show_points
bool GraphControl::m_show_points = true private
Referenced by RClick(), Render(), and ShowPoints().
m_show_scale
bool GraphControl::m_show_scale = true private
Referenced by DoLayout(), RClick(), Render(), and ShowScale().
m_vert_buf
GG::GL2DVertexBuffer GraphControl::m_vert_buf private
Referenced by DoLayout(), and Render().
m_x_max
double GraphControl::m_x_max = 1.0f private
Referenced by DoLayout(), SetRange(), and SetXMax().
m_x_min
double GraphControl::m_x_min = 0.0f private
Referenced by DoLayout(), SetRange(), and SetXMin().
m_y_max
double GraphControl::m_y_max = 1.0f private
Referenced by DoLayout(), SetRange(), and SetYMax().
m_y_min
double GraphControl::m_y_min = 0.0f private
Referenced by DoLayout(), SetRange(), and SetYMin().
m_y_scale_ticks
std::map<GG::Y, double> GraphControl::m_y_scale_ticks private
Referenced by DoLayout(), and Render().
m_zero_in_range
bool GraphControl::m_zero_in_range = false private
Referenced by DoLayout(), RClick(), and ScaleToZero().
The documentation for this class was generated from the following files:
GraphControl.h
GraphControl.cpp