FreeOrion: ScanlineRenderer::Impl Class Reference
ScanlineRenderer::Impl Class Reference
Public Member Functions
Impl ()
void RenderCircle (const GG::Pt &ul, const GG::Pt &lr)
void RenderRectangle (const GG::Pt &ul, const GG::Pt &lr)
void SetColor (GG::Clr clr)
void StartUsing ()
void StopUsing ()
Public Attributes
GG::Clr m_color
bool m_failed_init
std::unique_ptr< ShaderProgram > m_scanline_shader
Constructor & Destructor Documentation
Impl()
ScanlineRenderer::Impl::Impl () inline
References m_color.
Member Function Documentation
RenderCircle()
void ScanlineRenderer::Impl::RenderCircle (const GG::Pt & ul, const GG::Pt & lr) inline
References CircleArc(), StartUsing(), StopUsing(), and anonymous_namespace{CUIDrawUtil.cpp}::TWO_PI.
RenderRectangle()
void ScanlineRenderer::Impl::RenderRectangle (const GG::Pt & ul, const GG::Pt & lr) inline
References StartUsing(), and StopUsing().
SetColor()
void ScanlineRenderer::Impl::SetColor (GG::Clr clr) inline
References m_color.
StartUsing()
void ScanlineRenderer::Impl::StartUsing () inline
References ErrorLogger, OptionsDB::Get(), GetOptionsDB(), GetRootDataDir(), m_color, m_failed_init, m_scanline_shader, anonymous_namespace{About.cpp}::ReadFile(), and ShaderProgram::shaderProgramFactory().
Referenced by RenderCircle(), and RenderRectangle().
StopUsing()
void ScanlineRenderer::Impl::StopUsing () inline
References m_scanline_shader.
Referenced by RenderCircle(), and RenderRectangle().
Member Data Documentation
m_color
GG::Clr ScanlineRenderer::Impl::m_color
Referenced by Impl(), SetColor(), and StartUsing().
m_failed_init
bool ScanlineRenderer::Impl::m_failed_init
Referenced by StartUsing().
m_scanline_shader
std::unique_ptr<ShaderProgram> ScanlineRenderer::Impl::m_scanline_shader
Referenced by StartUsing(), and StopUsing().
The documentation for this class was generated from the following file:
CUIDrawUtil.cpp