FreeOrion: ResourceBrowseWnd Class Reference
ResourceBrowseWnd Class Reference
#include <ResourceBrowseWnd.h>
Public Member Functions
ResourceBrowseWnd (const std::string &title_text, const std::string &unit_label, float used, float output, float target_output)
void CompleteConstruction () override
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Member Functions
virtual void InitBuffer ()
Private Attributes
GG::GL2DVertexBuffer m_buffer
GG::Pt m_offset
std::shared_ptr< GG::Label > m_output_points
std::shared_ptr< GG::Label > m_output_points_label
std::shared_ptr< GG::Label > m_output_points_P_label
std::shared_ptr< GG::Label > m_target_points
std::shared_ptr< GG::Label > m_target_points_label
std::shared_ptr< GG::Label > m_target_points_P_label
std::shared_ptr< GG::Label > m_title_text
std::shared_ptr< GG::Label > m_used_points
std::shared_ptr< GG::Label > m_used_points_label
std::shared_ptr< GG::Label > m_used_points_P_label
Detailed Description
A popup tooltop for display when mousing over in-game icons. A title and some detail text.
Constructor & Destructor Documentation
ResourceBrowseWnd::ResourceBrowseWnd (const std::string & title_text, const std::string & unit_label, float used, float output, float target_output)
Member Function Documentation
void ResourceBrowseWnd::CompleteConstruction () override
References anonymous_namespace{ResourceBrowseWnd.cpp}::BrowseTextWidth(), anonymous_namespace{ResourceBrowseWnd.cpp}::EDGE_PAD(), FontBasedUpscale(), ClientUI::GetBoldFont(), InitBuffer(), m_offset, m_output_points, m_output_points_label, m_output_points_P_label, m_target_points, m_target_points_label, m_target_points_P_label, m_title_text, m_used_points, m_used_points_label, m_used_points_P_label, and ClientUI::Pts().
void ResourceBrowseWnd::InitBuffer () private virtual
References m_buffer, and ClientUI::Pts().
Referenced by CompleteConstruction().
void ResourceBrowseWnd::Render () override
References m_buffer, m_offset, ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
bool ResourceBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
GG::GL2DVertexBuffer ResourceBrowseWnd::m_buffer private
Referenced by InitBuffer(), and Render().
GG::Pt ResourceBrowseWnd::m_offset private
Referenced by CompleteConstruction(), and Render().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_output_points private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_output_points_label private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_output_points_P_label private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_target_points private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_target_points_label private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_target_points_P_label private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_title_text private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_used_points private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_used_points_label private
Referenced by CompleteConstruction().
std::shared_ptr<GG::Label> ResourceBrowseWnd::m_used_points_P_label private
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
ResourceBrowseWnd.h
ResourceBrowseWnd.cpp