FreeOrion: Building Class Reference
Building Class Reference
A Building UniverseObject type.
#include <Building.h>
Public Member Functions
Building (int empire_id, const std::string &building_type, int produced_by_empire_id=ALL_EMPIRES)
~Building ()
std::shared_ptr< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const override
Accepts a visitor object.
const std::string & BuildingTypeName () const
Returns the name of the BuildingType object for this building.
bool ContainedBy (int object_id) const override
int ContainerObjectID () const override
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
void Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES) override
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
std::string Dump (unsigned short ntabs=0) const override
Return human readable string description of object offset ntabs from margin.
bool HasTag (const std::string &name) const override
Returns true iff this object has the tag with the indicated name.
bool HostileToEmpire (int empire_id) const override
Object owner is at war with empire empire_id.
UniverseObjectType ObjectType () const override
bool OrderedScrapped () const
int PlanetID () const
returns the ID number of the planet this building is on
int ProducedByEmpireID () const
returns the empire ID of the empire that produced this building
void Reset ()
resets any building state, and removes owners
void ResetTargetMaxUnpairedMeters () override
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE.
void SetOrderedScrapped (bool b=true)
flags building for scrapping
void SetPlanetID (int planet_id)
sets the planet on which the building is located
std::set< std::string > Tags () const override
returns the capacity of the special with name name or 0 if that special is not present
Public Member Functions inherited from UniverseObject
virtual ~UniverseObject ()
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
virtual void BackPropagateMeters ()
Sets all this UniverseObject's meters' initial values equal to their current values.
virtual void ClampMeters ()
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
virtual const std::set< int > & ContainedObjectIDs () const
Returns ids of objects contained within this object.
virtual bool Contains (int object_id) const
Returns true if there is an object with id object_id is contained within this UniverseObject.
int CreationTurn () const
returns game turn on which object was created
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const MeterMap & Meters () const
returns this UniverseObject's meters
MeterMap & Meters ()
returns this UniverseObject's meters
void Move (double x, double y)
moves this object by relative displacements x and y.
virtual void MovementPhase ()
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
void MoveTo (int object_id)
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
void MoveTo (std::shared_ptr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
void MoveTo (double x, double y)
moves this object to map coordinates (x, y).
const std::string & Name () const
returns the name of this object; some valid objects will have no name
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
virtual void PopGrowthProductionResearchPhase ()
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
virtual const std::string & PublicName (int empire_id) const
Returns the name of this objectas it appears to empire empire_id .
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void Rename (const std::string &name)
renames this object to name
virtual void ResetPairedActiveMeters ()
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
void SetID (int id)
sets the ID number of the object to id
virtual void SetOwner (int id)
Sets the empire that owns this object.
void SetSpecialCapacity (const std::string &name, float capacity)
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
const std::map< std::string, std::pair< int, float > > & Specials () const
returns the Specials attached to this object
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
bool Unowned () const
returns true iff there are no owners of this object
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
Protected Member Functions
Building * Clone (int empire_id=ALL_EMPIRES) const override
Returns new copy of this Building.
Protected Member Functions inherited from UniverseObject
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (std::shared_ptr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
void Init ()
adds stealth meter
Private Attributes
std::string m_building_type
bool m_ordered_scrapped = false
int m_planet_id = INVALID_OBJECT_ID
int m_produced_by_empire_id = ALL_EMPIRES
Friends
template<typename T >
void boost::python::detail::value_destroyer (T const volatile *p)
template<typename Archive >
void serialize (Archive &, Building &, unsigned int const)
Additional Inherited Members
Public Types inherited from UniverseObject
typedef flat_map< MeterType, Meter, std::less< MeterType > > MeterMap
typedef boost::signals2::signal< void(), blocking_combiner< boost::signals2::optional_last_value< void > > > StateChangedSignalType
typedef StateChangedSignalType::slot_type StateChangedSlotType
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
A Building UniverseObject type.
Constructor & Destructor Documentation
Building()
Building::Building (int empire_id, const std::string & building_type, int produced_by_empire_id = ALL_EMPIRES)
References GetBuildingType(), UniverseObject::Init(), m_building_type, UniverseObject::Rename(), UniverseObject::SetOwner(), and UserString().
Referenced by Clone().
~Building()
Building::~Building () inline
References ALL_EMPIRES, and UniverseObject::Clone().
Member Function Documentation
Accept()
std::shared_ptr< UniverseObject > Building::Accept (const UniverseObjectVisitor & visitor) const override virtual
Accepts a visitor object.
See also
UniverseObjectVisitor
Reimplemented from UniverseObject.
References UniverseObjectVisitor::Visit().
BuildingTypeName()
const std::string& Building::BuildingTypeName () const inline
Returns the name of the BuildingType object for this building.
Referenced by anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), and FreeOrionPython::WrapUniverseClasses().
Clone()
Building * Building::Clone (int empire_id = ALL_EMPIRES) const override protected virtual
Returns new copy of this Building.
Implements UniverseObject.
References Building(), Copy(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), m_building_type, m_produced_by_empire_id, UniverseObject::Owner(), VIS_BASIC_VISIBILITY, and VIS_FULL_VISIBILITY.
ContainedBy()
bool Building::ContainedBy (int object_id) const override virtual
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, m_planet_id, and UniverseObject::SystemID().
ContainerObjectID()
int Building::ContainerObjectID () const inline override virtual
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
Reimplemented from UniverseObject.
References UniverseObject::Accept(), and UniverseObject::ContainedBy().
Copy()
void Building::Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) override virtual
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
Implements UniverseObject.
References UniverseObject::Copy(), ErrorLogger, Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), m_building_type, UniverseObject::m_name, m_ordered_scrapped, m_planet_id, m_produced_by_empire_id, VIS_BASIC_VISIBILITY, VIS_FULL_VISIBILITY, and VIS_PARTIAL_VISIBILITY.
Referenced by Clone().
Dump()
std::string Building::Dump (unsigned short ntabs = 0) const override virtual
Return human readable string description of object offset ntabs from margin.
Reimplemented from UniverseObject.
References UniverseObject::Dump(), m_building_type, and m_produced_by_empire_id.
HasTag()
bool Building::HasTag (const std::string & name) const override virtual
Returns true iff this object has the tag with the indicated name.
Reimplemented from UniverseObject.
References GetBuildingType(), and m_building_type.
HostileToEmpire()
bool Building::HostileToEmpire (int empire_id) const override virtual
Object owner is at war with empire empire_id.
Reimplemented from UniverseObject.
References ALL_EMPIRES, Empires(), EmpireManager::GetDiplomaticStatus(), UniverseObject::OwnedBy(), UniverseObject::Owner(), and UniverseObject::Unowned().
ObjectType()
UniverseObjectType Building::ObjectType () const override virtual
Reimplemented from UniverseObject.
OrderedScrapped()
bool Building::OrderedScrapped () const inline
References ALL_EMPIRES, UniverseObject::Copy(), and UniverseObject::ResetTargetMaxUnpairedMeters().
Referenced by FreeOrionPython::WrapUniverseClasses().
PlanetID()
int Building::PlanetID () const inline
returns the ID number of the planet this building is on
Referenced by FreeOrionPython::WrapUniverseClasses().
ProducedByEmpireID()
int Building::ProducedByEmpireID () const inline
returns the empire ID of the empire that produced this building
Referenced by FreeOrionPython::WrapUniverseClasses().
Reset()
void Building::Reset ()
resets any building state, and removes owners
References ALL_EMPIRES, m_ordered_scrapped, and UniverseObject::SetOwner().
ResetTargetMaxUnpairedMeters()
void Building::ResetTargetMaxUnpairedMeters () override virtual
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE.
This should be done before any Effects that alter these meter(s) act on the object.
Reimplemented from UniverseObject.
References UniverseObject::ResetTargetMaxUnpairedMeters().
SetOrderedScrapped()
void Building::SetOrderedScrapped (bool b = true)
flags building for scrapping
References m_ordered_scrapped, and UniverseObject::StateChangedSignal.
SetPlanetID()
void Building::SetPlanetID (int planet_id)
sets the planet on which the building is located
References m_planet_id, and UniverseObject::StateChangedSignal.
Tags()
std::set< std::string > Building::Tags () const override virtual
returns the capacity of the special with name name or 0 if that special is not present
Returns all tags this object has.
Reimplemented from UniverseObject.
References GetBuildingType(), and m_building_type.
Friends And Related Function Documentation
boost::python::detail::value_destroyer
template<typename T > void boost::python::detail::value_destroyer (T const volatile * p) friend
serialize
template<typename Archive > void serialize (Archive & ar, Building & obj, unsigned int const version) friend
Member Data Documentation
m_building_type
std::string Building::m_building_type private
Referenced by Building(), Clone(), Copy(), Dump(), HasTag(), serialize(), and Tags().
m_ordered_scrapped
bool Building::m_ordered_scrapped = false private
Referenced by Copy(), Reset(), serialize(), and SetOrderedScrapped().
m_planet_id
int Building::m_planet_id = INVALID_OBJECT_ID private
Referenced by ContainedBy(), Copy(), serialize(), and SetPlanetID().
m_produced_by_empire_id
int Building::m_produced_by_empire_id = ALL_EMPIRES private
Referenced by Clone(), Copy(), Dump(), and serialize().
The documentation for this class was generated from the following files:
Building.h
Building.cpp