FreeOrion: StatisticIcon Class Reference
StatisticIcon Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
StatisticIcon (const std::shared_ptr< GG::Texture > texture, GG::X w=GG::X1, GG::Y h=GG::Y1)
initialized with no value (just an icon)
StatisticIcon (const std::shared_ptr< GG::Texture > texture, double value, int digits, bool showsign, GG::X w=GG::X1, GG::Y h=GG::Y1)
initializes with one value
StatisticIcon (const std::shared_ptr< GG::Texture > texture, double value0, double value1, int digits0, int digits1, bool showsign0, bool showsign1, GG::X w=GG::X1, GG::Y h=GG::Y1)
initializes with two values
Accessors
double GetValue (int index=0) const
GG::Pt MinUsableSize () const override
Mutators
void PreRender () override
sets displayed value with index
void Render () override
sets displayed value with index
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
sets displayed value with index
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void RButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void SetValue (double value, int index=0)
sets displayed value with index
Public Attributes
boost::signals2::signal< void()> LeftClickedSignal
boost::signals2::signal< void()> RightClickedSignal
Private Member Functions
void DoLayout ()
GG::Clr ValueColor (int index) const
returns colour in which to draw value
Private Attributes
std::vector< int > m_digits
GG::StaticGraphic * m_icon
int m_num_values
std::vector< bool > m_show_signs
GG::Label * m_text
std::vector< double > m_values
Detailed Description
Encapsulates an icon and text that goes with it in a single control. For example, "[trade icon] +1" or "[population icon] 66 (+5)", where [... icon] is an icon image, not text. The icon may have one or two numerical values. If one, just that number is displayed. If two, the first number is displayed followed by the second in brackets "()"
Sizing StatisticIcon correctly in the constructor saves time because resizing the value string is processor intensive.
Constructor & Destructor Documentation
StatisticIcon::StatisticIcon (const std::shared_ptr< GG::Texture > texture, GG::X w = GG::X1, GG::Y h = GG::Y1)
initialized with no value (just an icon)
References GetOptionsDB(), and m_icon.
StatisticIcon::StatisticIcon (const std::shared_ptr< GG::Texture > texture, double value, int digits, bool showsign, GG::X w = GG::X1, GG::Y h = GG::Y1)
initializes with one value
References GetOptionsDB(), and m_icon.
StatisticIcon::StatisticIcon (const std::shared_ptr< GG::Texture > texture, double value0, double value1, int digits0, int digits1, bool showsign0, bool showsign1, GG::X w = GG::X1, GG::Y h = GG::Y1)
initializes with two values
References GetOptionsDB(), m_digits, m_icon, m_show_signs, m_values, and anonymous_namespace{ServerWrapper.cpp}::SetName().
Member Function Documentation
void StatisticIcon::DoLayout () private
References DoubleToString(), ClientUI::GetFont(), m_digits, m_icon, m_num_values, m_show_signs, m_text, m_values, anonymous_namespace{CUIControls.cpp}::STAT_ICON_PAD, and ValueColor().
Referenced by PreRender().
double StatisticIcon::GetValue (int index = 0) const
References m_num_values, and m_values.
void StatisticIcon::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void StatisticIcon::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
References LeftClickedSignal.
GG::Pt StatisticIcon::MinUsableSize () const override
References m_icon, m_num_values, and m_text.
Referenced by MilitaryPanel::DoLayout(), ResourcePanel::DoLayout(), and PopulationPanel::DoLayout().
void StatisticIcon::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void StatisticIcon::PreRender () override
sets displayed value with index
References DoLayout().
void StatisticIcon::RButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
void StatisticIcon::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets displayed value with index
References RightClickedSignal.
void StatisticIcon::Render () inline override
sets displayed value with index
References CUILabel::RClick().
void StatisticIcon::SetValue (double value, int index = 0)
sets displayed value with index
References m_digits, m_num_values, m_show_signs, and m_values.
Referenced by MapWnd::RefreshDetectionIndicator(), MapWnd::RefreshFleetResourceIndicator(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), and MapWnd::RefreshTradeResourceIndicator().
void StatisticIcon::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
sets displayed value with index
Referenced by MilitaryPanel::DoLayout(), PopulationPanel::DoLayout(), ResourcePanel::DoLayout(), and SpecialsPanel::Update().
GG::Clr StatisticIcon::ValueColor (int index) const private
returns colour in which to draw value
References EffectiveSign(), m_num_values, m_values, ClientUI::StatDecrColor(), ClientUI::StatIncrColor(), and ClientUI::TextColor().
Referenced by DoLayout().
Member Data Documentation
boost::signals2::signal<void ()> StatisticIcon::LeftClickedSignal mutable
Referenced by LClick(), and MapWnd::MapWnd().
std::vector<int> StatisticIcon::m_digits private
Referenced by DoLayout(), SetValue(), and StatisticIcon().
GG::StaticGraphic* StatisticIcon::m_icon private
Referenced by DoLayout(), MinUsableSize(), and StatisticIcon().
int StatisticIcon::m_num_values private
Referenced by DoLayout(), GetValue(), MinUsableSize(), SetValue(), and ValueColor().
std::vector<bool> StatisticIcon::m_show_signs private
Referenced by DoLayout(), SetValue(), and StatisticIcon().
GG::Label* StatisticIcon::m_text private
Referenced by DoLayout(), and MinUsableSize().
std::vector<double> StatisticIcon::m_values private
Referenced by DoLayout(), GetValue(), SetValue(), StatisticIcon(), and ValueColor().
boost::signals2::signal<void ()> StatisticIcon::RightClickedSignal mutable
Referenced by RClick().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp