FreeOrion: SavedDesignsListBox::SavedDesignListBoxRow Class Reference
SavedDesignsListBox::SavedDesignListBoxRow Class Reference
Public Member Functions
SavedDesignListBoxRow (GG::X w, GG::Y h, const ShipDesign &design)
void CompleteConstruction () override
const std::string & Description () const
const std::string & DesignName () const
const boost::uuids::uuid DesignUUID () const
bool LookupInStringtable () const
Private Attributes
boost::uuids::uuid m_design_uuid
Constructor & Destructor Documentation
SavedDesignListBoxRow()
SavedDesignsListBox::SavedDesignListBoxRow::SavedDesignListBoxRow (GG::X w, GG::Y h, const ShipDesign & design)
Member Function Documentation
CompleteConstruction()
void SavedDesignsListBox::SavedDesignListBoxRow::CompleteConstruction () override
References BasesListBox::BasesListBoxRow::CompleteConstruction(), and anonymous_namespace{DesignWnd.cpp}::SAVED_DESIGN_ROW_DROP_STRING.
Description()
const std::string & SavedDesignsListBox::SavedDesignListBoxRow::Description () const
References ShipDesign::Description(), anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and m_design_uuid.
DesignName()
const std::string & SavedDesignsListBox::SavedDesignListBoxRow::DesignName () const
References anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), m_design_uuid, and ShipDesign::Name().
DesignUUID()
const boost::uuids::uuid SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID () const
References ErrorLogger, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), m_design_uuid, and ShipDesign::UUID().
Referenced by SavedDesignsListBox::BaseLeftClicked(), SavedDesignsListBox::BaseRightClicked(), and SavedDesignsListBox::QueueItemMoved().
LookupInStringtable()
bool SavedDesignsListBox::SavedDesignListBoxRow::LookupInStringtable () const
References anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), ShipDesign::LookupInStringtable(), and m_design_uuid.
Member Data Documentation
m_design_uuid
boost::uuids::uuid SavedDesignsListBox::SavedDesignListBoxRow::m_design_uuid private
Referenced by Description(), DesignName(), DesignUUID(), and LookupInStringtable().
The documentation for this class was generated from the following file:
DesignWnd.cpp