FreeOrion: ServerNetworking Class Reference
ServerNetworking Class Reference
Encapsulates the networking facilities of the server.
#include <ServerNetworking.h>
Classes
struct EstablishedPlayer
Public Types
typedef boost::filter_iterator< EstablishedPlayer, PlayerConnections::const_iterator > const_established_iterator
typedef std::set< PlayerConnectionPtr >::const_iterator const_iterator
typedef boost::filter_iterator< EstablishedPlayer, PlayerConnections::iterator > established_iterator
typedef std::set< PlayerConnectionPtr >::iterator iterator
Public Member Functions
ServerNetworking (boost::asio::io_context &io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback)
~ServerNetworking ()
const_iterator begin () const
Returns an iterator to the first PlayerConnection object.
iterator begin ()
Returns an iterator to the first PlayerConnection object.
bool CheckCookie (boost::uuids::uuid cookie, const std::string &player_name, Networking::AuthRoles &roles, bool &authenticated) const
Returns whether player have non-expired cookie with this player name.
void CleanupCookies ()
Clean up expired cookies.
void Disconnect (int id)
Disconnects the server from player id.
void Disconnect (PlayerConnectionPtr player_connection)
Disconnects the server from the client represented by player_connection.
void DisconnectAll ()
Disconnects the server from all clients.
bool empty () const
Returns true if size() == 0.
const_iterator end () const
Returns an iterator to the one-past-the-last PlayerConnection object.
iterator end ()
Returns an iterator to the one-past-the-last PlayerConnection object.
const_established_iterator established_begin () const
Returns an iterator to the first established PlayerConnection object.
established_iterator established_begin ()
Returns an iterator to the first established PlayerConnection object.
const_established_iterator established_end () const
Returns an iterator to the one-past-the-last established PlayerConnection object.
established_iterator established_end ()
Returns an iterator to the one-past-the-last established PlayerConnection object.
boost::uuids::uuid GenerateCookie (std::string player_name, const Networking::AuthRoles &roles, bool authenticated)
Generate cookies for player's name, roles, and authentication status.
int GetCookiesSize () const
Returns count of stored cookies so we don't collide with reserved player names.
const_established_iterator GetPlayer (int id) const
Returns an iterator to the established PlayerConnection object with ID id, or established_end() if none is found.
established_iterator GetPlayer (int id)
Returns an iterator to the established PlayerConnection object with ID id, or end() if none is found.
void HandleNextEvent ()
Dequeues and executes the next event in the queue.
int HostPlayerID () const
Returns the ID of the host player, or INVALID_PLAYER_ID if there is no host player.
bool IsAvailableNameInCookies (const std::string &player_name) const
Returns whether there no non-expired cookie with this player name.
bool ModeratorsInGame () const
Returns whether there are any moderators in the game.
int NewPlayerID () const
Returns the ID number for new player, which will be larger than the ID of all the established players.
std::size_t NumEstablishedPlayers () const
Returns the number of established-player PlayerConnections.
bool PlayerIsHost (int player_id) const
Returns whether the indicated player ID is the host.
void SendMessageAll (const Message &message)
Sends a synchronous message message to the all established players.
void SetHostPlayerID (int host_player_id)
Sets Host player ID.
std::size_t size () const
Returns the total number of PlayerConnections (not just established ones).
void UpdateCookie (boost::uuids::uuid cookie)
Bump cookie's expired date.
Private Types
typedef std::set< PlayerConnectionPtr > PlayerConnections
Private Member Functions
void AcceptNextMessagingConnection ()
void AcceptPlayerMessagingConnection (PlayerConnectionPtr player_connection, const boost::system::error_code &error)
void DisconnectImpl (PlayerConnectionPtr player_connection)
void EnqueueEvent (const NullaryFn &fn)
void Init ()
Private Attributes
std::unordered_map< boost::uuids::uuid, CookieData, boost::hash< boost::uuids::uuid > > m_cookies
ConnectionFn m_disconnected_callback
DiscoveryServer * m_discovery_server
std::queue< NullaryFn > m_event_queue
int m_host_player_id
MessageAndConnectionFn m_nonplayer_message_callback
boost::asio::ip::tcp::acceptor m_player_connection_acceptor
PlayerConnections m_player_connections
MessageAndConnectionFn m_player_message_callback
Detailed Description
Encapsulates the networking facilities of the server.
This class listens for incoming UDP LAN server-discovery requests and TCP player connections. The server also sends and receives messages over the TCP player connections.
Member Typedef Documentation
const_established_iterator
typedef boost::filter_iterator<EstablishedPlayer, PlayerConnections::const_iterator> ServerNetworking::const_established_iterator
const_iterator
typedef std::set<PlayerConnectionPtr>::const_iterator ServerNetworking::const_iterator
established_iterator
typedef boost::filter_iterator<EstablishedPlayer, PlayerConnections::iterator> ServerNetworking::established_iterator
iterator
typedef std::set<PlayerConnectionPtr>::iterator ServerNetworking::iterator
PlayerConnections
typedef std::set<PlayerConnectionPtr> ServerNetworking::PlayerConnections private
Constructor & Destructor Documentation
ServerNetworking()
ServerNetworking::ServerNetworking (boost::asio::io_context & io_context, MessageAndConnectionFn nonplayer_message_callback, MessageAndConnectionFn player_message_callback, ConnectionFn disconnected_callback)
References Init().
~ServerNetworking()
ServerNetworking::~ServerNetworking ()
References m_discovery_server.
Member Function Documentation
AcceptNextMessagingConnection()
void ServerNetworking::AcceptNextMessagingConnection () private
References AcceptPlayerMessagingConnection(), DisconnectImpl(), EnqueueEvent(), m_nonplayer_message_callback, m_player_connection_acceptor, m_player_message_callback, and PlayerConnection::NewConnection().
Referenced by AcceptPlayerMessagingConnection(), and Init().
AcceptPlayerMessagingConnection()
void ServerNetworking::AcceptPlayerMessagingConnection (PlayerConnectionPtr player_connection, const boost::system::error_code & error) private
References AcceptNextMessagingConnection(), error, m_player_connections, and TraceLogger.
Referenced by AcceptNextMessagingConnection().
begin() [1/2]
ServerNetworking::const_iterator ServerNetworking::begin () const
Returns an iterator to the first PlayerConnection object.
References m_player_connections.
begin() [2/2]
ServerNetworking::iterator ServerNetworking::begin ()
Returns an iterator to the first PlayerConnection object.
References m_player_connections.
CheckCookie()
bool ServerNetworking::CheckCookie (boost::uuids::uuid cookie, const std::string & player_name, Networking::AuthRoles & roles, bool & authenticated) const
Returns whether player have non-expired cookie with this player name.
Fills roles and authentication status on success.
References m_cookies.
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
CleanupCookies()
void ServerNetworking::CleanupCookies ()
Clean up expired cookies.
References established_begin(), established_end(), and m_cookies.
Referenced by ServerFSM::HandleNonLobbyDisconnection().
Disconnect() [1/2]
void ServerNetworking::Disconnect (int id)
Disconnects the server from player id.
References ErrorLogger, established_end(), and GetPlayer().
Referenced by ServerFSM::EstablishPlayer(), ServerApp::HandleMessage(), ServerApp::HandleNonPlayerMessage(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), and WaitingForTurnEnd::react().
Disconnect() [2/2]
void ServerNetworking::Disconnect (PlayerConnectionPtr player_connection)
Disconnects the server from the client represented by player_connection.
References DisconnectImpl(), and TraceLogger.
DisconnectAll()
void ServerNetworking::DisconnectAll ()
Disconnects the server from all clients.
References DisconnectImpl(), m_player_connections, and TraceLogger.
Referenced by ShuttingDownServer::react().
DisconnectImpl()
void ServerNetworking::DisconnectImpl (PlayerConnectionPtr player_connection) private
References m_disconnected_callback, m_player_connections, and TraceLogger.
Referenced by AcceptNextMessagingConnection(), Disconnect(), and DisconnectAll().
empty()
bool ServerNetworking::empty () const
Returns true if size() == 0.
References m_player_connections.
Referenced by ServerApp::CleanupAIs(), ShuttingDownServer::ShuttingDownServer(), and MPLobby::ValidateClientLimits().
end() [1/2]
ServerNetworking::const_iterator ServerNetworking::end () const
Returns an iterator to the one-past-the-last PlayerConnection object.
References m_player_connections.
end() [2/2]
ServerNetworking::iterator ServerNetworking::end ()
Returns an iterator to the one-past-the-last PlayerConnection object.
References m_player_connections.
EnqueueEvent()
void ServerNetworking::EnqueueEvent (const NullaryFn & fn) private
References m_event_queue.
Referenced by AcceptNextMessagingConnection().
established_begin() [1/2]
ServerNetworking::const_established_iterator ServerNetworking::established_begin () const
Returns an iterator to the first established PlayerConnection object.
References m_player_connections.
Referenced by anonymous_namespace{ServerApp.cpp}::AIPlayerIDWithName(), CleanupCookies(), ServerApp::EliminatePlayer(), ServerFSM::EstablishPlayer(), MPLobby::EstablishPlayer(), GetPlayer(), ServerApp::GetPlayerInfoMap(), ServerApp::HandleDiplomaticStatusChange(), ServerApp::HandleLoggerConfig(), ServerFSM::HandleNonLobbyDisconnection(), ServerApp::IsAvailableName(), ServerApp::LoadGameInit(), ServerApp::LoadSPGameInit(), ServerApp::NewGameInitVerifyJoiners(), ServerApp::NewMPGameInit(), NumEstablishedPlayers(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), MPLobby::react(), WaitingForMPGameJoiners::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), ServerApp::SelectNewHost(), SendMessageAll(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerApp::SendNewGameStartMessages(), ServerFSM::UpdateIngameLobby(), and MPLobby::ValidateClientLimits().
established_begin() [2/2]
ServerNetworking::established_iterator ServerNetworking::established_begin ()
Returns an iterator to the first established PlayerConnection object.
References m_player_connections.
established_end() [1/2]
ServerNetworking::const_established_iterator ServerNetworking::established_end () const
Returns an iterator to the one-past-the-last established PlayerConnection object.
References m_player_connections.
Referenced by anonymous_namespace{ServerApp.cpp}::AIPlayerIDWithName(), CleanupCookies(), Disconnect(), ServerApp::EliminatePlayer(), ServerFSM::EstablishPlayer(), MPLobby::EstablishPlayer(), GetPlayer(), ServerApp::GetPlayerClientType(), ServerApp::GetPlayerInfoMap(), ServerApp::HandleDiplomaticMessageChange(), ServerApp::HandleDiplomaticStatusChange(), ServerApp::HandleLoggerConfig(), ServerFSM::HandleNonLobbyDisconnection(), anonymous_namespace{ServerApp.cpp}::HumanPlayerWithIdConnected(), ServerApp::IsAvailableName(), ServerApp::IsLocalHumanPlayer(), ServerApp::LoadGameInit(), ServerApp::LoadSPGameInit(), ServerApp::NewGameInitVerifyJoiners(), ServerApp::NewMPGameInit(), NumEstablishedPlayers(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), MPLobby::react(), WaitingForMPGameJoiners::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), ServerApp::SelectNewHost(), SendMessageAll(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), anonymous_namespace{ServerFSM.cpp}::SendMessageToHost(), ServerApp::SendNewGameStartMessages(), ServerFSM::UpdateIngameLobby(), and MPLobby::ValidateClientLimits().
established_end() [2/2]
ServerNetworking::established_iterator ServerNetworking::established_end ()
Returns an iterator to the one-past-the-last established PlayerConnection object.
References m_player_connections.
GenerateCookie()
boost::uuids::uuid ServerNetworking::GenerateCookie (std::string player_name, const Networking::AuthRoles & roles, bool authenticated)
Generate cookies for player's name, roles, and authentication status.
References GetOptionsDB(), and m_cookies.
Referenced by ServerFSM::EstablishPlayer().
GetCookiesSize()
int ServerNetworking::GetCookiesSize () const
Returns count of stored cookies so we don't collide with reserved player names.
References m_cookies.
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
GetPlayer() [1/2]
ServerNetworking::const_established_iterator ServerNetworking::GetPlayer (int id) const
Returns an iterator to the established PlayerConnection object with ID id, or established_end() if none is found.
References established_begin(), and established_end().
Referenced by Disconnect(), ServerApp::GetPlayerClientType(), ServerApp::HandleDiplomaticMessageChange(), anonymous_namespace{ServerApp.cpp}::HumanPlayerWithIdConnected(), ServerApp::IsLocalHumanPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), MPLobby::react(), and anonymous_namespace{ServerFSM.cpp}::SendMessageToHost().
GetPlayer() [2/2]
ServerNetworking::established_iterator ServerNetworking::GetPlayer (int id)
Returns an iterator to the established PlayerConnection object with ID id, or end() if none is found.
References established_begin(), and established_end().
HandleNextEvent()
void ServerNetworking::HandleNextEvent ()
Dequeues and executes the next event in the queue.
Results in a noop if the queue is empty.
References m_event_queue.
Referenced by ServerApp::Run().
HostPlayerID()
int ServerNetworking::HostPlayerID () const
Returns the ID of the host player, or INVALID_PLAYER_ID if there is no host player.
References m_host_player_id.
Referenced by ServerFSM::EstablishPlayer(), ServerApp::HandleLoggerConfig(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadSPGameInit(), ServerApp::NewGameInitVerifyJoiners(), WaitingForSPGameJoiners::react(), ServerApp::SelectNewHost(), anonymous_namespace{ServerFSM.cpp}::SendMessageToHost(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
Init()
void ServerNetworking::Init () private
References AcceptNextMessagingConnection(), ErrorLogger, GetOptionsDB(), m_player_connection_acceptor, Networking::MessagePort(), and Networking::SOCKET_LINGER_TIME.
Referenced by ServerNetworking().
IsAvailableNameInCookies()
bool ServerNetworking::IsAvailableNameInCookies (const std::string & player_name) const
Returns whether there no non-expired cookie with this player name.
References m_cookies.
Referenced by ServerApp::IsAvailableName().
ModeratorsInGame()
bool ServerNetworking::ModeratorsInGame () const
Returns whether there are any moderators in the game.
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, and m_player_connections.
Referenced by WaitingForTurnEnd::react().
NewPlayerID()
int ServerNetworking::NewPlayerID () const
Returns the ID number for new player, which will be larger than the ID of all the established players.
References Networking::INVALID_PLAYER_ID, and m_player_connections.
Referenced by ServerFSM::EstablishPlayer(), Idle::react(), WaitingForMPGameJoiners::react(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
NumEstablishedPlayers()
std::size_t ServerNetworking::NumEstablishedPlayers () const
Returns the number of established-player PlayerConnections.
References established_begin(), and established_end().
Referenced by ServerApp::LoadGameInit(), ServerApp::NewGameInitVerifyJoiners(), MPLobby::react(), WaitingForSPGameJoiners::react(), PlayingGame::react(), and MPLobby::ValidateClientLimits().
PlayerIsHost()
bool ServerNetworking::PlayerIsHost (int player_id) const
Returns whether the indicated player ID is the host.
References Networking::INVALID_PLAYER_ID, and m_host_player_id.
Referenced by ServerApp::GetPlayerInfoMap(), ServerApp::HandleLoggerConfig(), ServerFSM::HandleNonLobbyDisconnection(), ServerApp::HandleShutdownMessage(), ServerApp::PostCombatProcessTurns(), MPLobby::react(), WaitingForTurnEnd::react(), and MPLobby::ValidateClientLimits().
SendMessageAll()
void ServerNetworking::SendMessageAll (const Message & message)
Sends a synchronous message message to the all established players.
References established_begin(), and established_end().
Referenced by ServerApp::AddPlayerIntoGame(), ServerApp::CreateAIClients(), ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadChatHistory(), ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::NewGameInitVerifyJoiners(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), ServerApp::ProcessCombats(), ServerApp::PushChatMessage(), and ServerApp::SelectNewHost().
SetHostPlayerID()
void ServerNetworking::SetHostPlayerID (int host_player_id)
Sets Host player ID.
References m_host_player_id.
Referenced by Idle::react(), and ServerApp::SelectNewHost().
size()
std::size_t ServerNetworking::size () const
Returns the total number of PlayerConnections (not just established ones).
References m_player_connections.
Referenced by ServerApp::HandleNonPlayerMessage().
UpdateCookie()
void ServerNetworking::UpdateCookie (boost::uuids::uuid cookie)
Bump cookie's expired date.
References GetOptionsDB(), and m_cookies.
Referenced by ServerApp::HandleMessage(), and ServerFSM::HandleNonLobbyDisconnection().
Member Data Documentation
m_cookies
std::unordered_map<boost::uuids::uuid, CookieData, boost::hash<boost::uuids::uuid> > ServerNetworking::m_cookies private
Referenced by CheckCookie(), CleanupCookies(), GenerateCookie(), GetCookiesSize(), IsAvailableNameInCookies(), and UpdateCookie().
m_disconnected_callback
ConnectionFn ServerNetworking::m_disconnected_callback private
Referenced by DisconnectImpl().
m_discovery_server
DiscoveryServer* ServerNetworking::m_discovery_server private
Referenced by ~ServerNetworking().
m_event_queue
std::queue<NullaryFn> ServerNetworking::m_event_queue private
Referenced by EnqueueEvent(), and HandleNextEvent().
m_host_player_id
int ServerNetworking::m_host_player_id private
Referenced by HostPlayerID(), PlayerIsHost(), and SetHostPlayerID().
m_nonplayer_message_callback
MessageAndConnectionFn ServerNetworking::m_nonplayer_message_callback private
Referenced by AcceptNextMessagingConnection().
m_player_connection_acceptor
boost::asio::ip::tcp::acceptor ServerNetworking::m_player_connection_acceptor private
Referenced by AcceptNextMessagingConnection(), and Init().
m_player_connections
PlayerConnections ServerNetworking::m_player_connections private
Referenced by AcceptPlayerMessagingConnection(), begin(), DisconnectAll(), DisconnectImpl(), empty(), end(), established_begin(), established_end(), ModeratorsInGame(), NewPlayerID(), and size().
m_player_message_callback
MessageAndConnectionFn ServerNetworking::m_player_message_callback private
Referenced by AcceptNextMessagingConnection().
The documentation for this class was generated from the following files:
ServerNetworking.h
ServerNetworking.cpp