FreeOrion: CreditsWnd Class Reference
CreditsWnd Class Reference
Displays scrolling credits.
Public Member Functions
CreditsWnd (GG::X x, GG::Y y, GG::X w, GG::Y h, const XMLElement &credits, int cx, int cy, int cw, int ch, int co)
~CreditsWnd ()
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
Private Member Functions
void DrawCredits (GG::X x1, GG::Y y1, GG::X x2, GG::Y y2, int transparency)
void OnExit ()
Private Attributes
int m_ch
int m_co
XMLElement m_credits
int m_credits_height
int m_cw
int m_cx
int m_cy
int m_display_list_id
std::shared_ptr< GG::Font > m_font
int m_render
int m_scroll_offset = 0
int m_start_time
Detailed Description
Displays scrolling credits.
Constructor & Destructor Documentation
CreditsWnd()
CreditsWnd::CreditsWnd (GG::X x, GG::Y y, GG::X w, GG::Y h, const XMLElement & credits, int cx, int cy, int cw, int ch, int co)
Handle app resizing by closing the credits window.
References ClientUI::GetFont(), m_font, OnExit(), and ClientUI::Pts().
~CreditsWnd()
CreditsWnd::~CreditsWnd ()
References m_display_list_id.
Member Function Documentation
DrawCredits()
void CreditsWnd::DrawCredits (GG::X x1, GG::Y y1, GG::X x2, GG::Y y2, int transparency) private
References XMLElement::attributes, XMLElement::children, m_credits, m_credits_height, m_font, XMLElement::Tag(), to_string(), and UserString().
Referenced by Render().
KeyPress()
void CreditsWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) inline override
LClick()
void CreditsWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
MouseWheel()
void CreditsWnd::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) inline override
OnExit()
void CreditsWnd::OnExit () private
References m_display_list_id, and m_render.
Referenced by CreditsWnd(), and Render().
Render()
void CreditsWnd::Render () override
References anonymous_namespace{MapWnd.cpp}::AppHeight(), DrawCredits(), m_ch, m_co, m_credits_height, m_cw, m_cx, m_cy, m_display_list_id, m_render, m_scroll_offset, m_start_time, and OnExit().
Member Data Documentation
m_ch
int CreditsWnd::m_ch private
Referenced by Render().
m_co
int CreditsWnd::m_co private
Referenced by Render().
m_credits
XMLElement CreditsWnd::m_credits private
Referenced by DrawCredits().
m_credits_height
int CreditsWnd::m_credits_height private
Referenced by DrawCredits(), and Render().
m_cw
int CreditsWnd::m_cw private
Referenced by Render().
m_cx
int CreditsWnd::m_cx private
Referenced by Render().
m_cy
int CreditsWnd::m_cy private
Referenced by Render().
m_display_list_id
int CreditsWnd::m_display_list_id private
Referenced by OnExit(), Render(), and ~CreditsWnd().
m_font
std::shared_ptr<GG::Font> CreditsWnd::m_font private
Referenced by CreditsWnd(), and DrawCredits().
m_render
int CreditsWnd::m_render private
Referenced by OnExit(), and Render().
m_scroll_offset
int CreditsWnd::m_scroll_offset = 0 private
Referenced by Render().
m_start_time
int CreditsWnd::m_start_time private
Referenced by Render().
The documentation for this class was generated from the following file:
IntroScreen.cpp