FreeOrion: CUILinkTextBlock Class Reference
CUILinkTextBlock Class Reference
#include <CUILinkTextBlock.h>
Classes
class Factory
Public Member Functions
CUILinkTextBlock (const std::string &str, const std::shared_ptr< GG::Font > &font, GG::Flags< GG::TextFormat > format, const GG::Clr &color, GG::Flags< GG::WndFlag > flags)
void Render () override
GG::Pt SetMaxWidth (GG::X width) override
CUILinkTextMultiEdit & Text ()
Private Attributes
CUILinkTextMultiEdit * m_link_text
Constructor & Destructor Documentation
CUILinkTextBlock::CUILinkTextBlock (const std::string & str, const std::shared_ptr< GG::Font > & font, GG::Flags< GG::TextFormat > format, const GG::Clr & color, GG::Flags< GG::WndFlag > flags)
References m_link_text.
Referenced by CUILinkTextBlock::Factory::CreateFromTag().
Member Function Documentation
void CUILinkTextBlock::Render () inline override
References Text().
GG::Pt CUILinkTextBlock::SetMaxWidth (GG::X width) override
References m_link_text.
CUILinkTextMultiEdit & CUILinkTextBlock::Text ()
References m_link_text.
Referenced by Render().
Member Data Documentation
CUILinkTextMultiEdit* CUILinkTextBlock::m_link_text private
Referenced by CUILinkTextBlock::Factory::CreateFromTag(), CUILinkTextBlock(), SetMaxWidth(), and Text().
The documentation for this class was generated from the following files:
CUILinkTextBlock.h
CUILinkTextBlock.cpp