FreeOrion: ShipFightersBrowseWnd Class Reference
ShipFightersBrowseWnd Class Reference
#include <MeterBrowseWnd.h>
Public Member Functions
ShipFightersBrowseWnd (int object_id, MeterType primary_meter_type, bool show_all_bouts=false)
Public Member Functions inherited from MeterBrowseWnd
MeterBrowseWnd (int object_id, MeterType primary_meter_type, MeterType secondary_meter_type)
MeterBrowseWnd (int object_id, MeterType primary_meter_type)
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Member Functions
void Initialize ()
void UpdateEffectLabelsAndValues (GG::Y &top)
void UpdateImpl (std::size_t mode, const Wnd *target) override
void UpdateSummary ()
Private Attributes
std::shared_ptr< GG::ListBox > m_bay_list
std::shared_ptr< GG::ListBox > m_hangar_list
bool m_show_all_bouts
Additional Inherited Members
Protected Member Functions inherited from MeterBrowseWnd
void Initialize ()
void UpdateEffectLabelsAndValues (GG::Y &top)
void UpdateImpl (std::size_t mode, const Wnd *target) override
void UpdateSummary ()
Protected Attributes inherited from MeterBrowseWnd
std::shared_ptr< GG::Label > m_change_label
std::shared_ptr< GG::Label > m_change_value
std::shared_ptr< GG::Label > m_current_label
std::shared_ptr< GG::Label > m_current_value
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_effect_labels_and_values
bool m_initialized = false
std::shared_ptr< GG::Label > m_meter_title
std::shared_ptr< GG::Label > m_next_turn_label
std::shared_ptr< GG::Label > m_next_turn_value
int m_object_id
MeterType m_primary_meter_type
GG::Y m_row_height = GG::Y1
MeterType m_secondary_meter_type
std::shared_ptr< GG::Label > m_summary_title
Constructor & Destructor Documentation
ShipFightersBrowseWnd()
ShipFightersBrowseWnd::ShipFightersBrowseWnd (int object_id, MeterType primary_meter_type, bool show_all_bouts = false)
Member Function Documentation
Initialize()
void ShipFightersBrowseWnd::Initialize () private
References anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), ErrorLogger, anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseListWidth(), ObjectMap::get(), ClientUI::GetBoldFont(), m_bay_list, m_hangar_list, MeterBrowseWnd::m_initialized, MeterBrowseWnd::m_meter_title, MeterBrowseWnd::m_object_id, MeterBrowseWnd::m_row_height, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseQtyWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), Objects(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), UpdateEffectLabelsAndValues(), UpdateSummary(), and ClientUI::WndColor().
Referenced by UpdateImpl().
UpdateEffectLabelsAndValues()
void ShipFightersBrowseWnd::UpdateEffectLabelsAndValues (GG::Y & top) private
References anonymous_namespace{MeterBrowseWnd.cpp}::ColouredInt(), anonymous_namespace{MeterBrowseWnd.cpp}::ColourWrappedtext(), DoubleToString(), anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), ErrorLogger, anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseListWidth(), FlexibleFormat(), ObjectMap::get(), ClientUI::GetBoldFont(), GetShipDesign(), GetShipPart(), anonymous_namespace{MeterBrowseWnd.cpp}::IntToString(), m_bay_list, MeterBrowseWnd::m_effect_labels_and_values, m_hangar_list, MeterBrowseWnd::m_object_id, MeterBrowseWnd::m_row_height, m_show_all_bouts, METER_CAPACITY, METER_MAX_CAPACITY, METER_SECONDARY_STAT, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseQtyWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), Objects(), ShipDesign::Parts(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH(), and UserString().
Referenced by Initialize().
UpdateImpl()
void ShipFightersBrowseWnd::UpdateImpl (std::size_t mode, const Wnd * target) override private
References Initialize(), and MeterBrowseWnd::m_initialized.
UpdateSummary()
void ShipFightersBrowseWnd::UpdateSummary () private
References DoubleToString(), Ship::FighterCount(), FlexibleFormat(), ObjectMap::get(), MeterBrowseWnd::m_meter_title, MeterBrowseWnd::m_object_id, Objects(), and UserString().
Referenced by Initialize().
Member Data Documentation
m_bay_list
std::shared_ptr<GG::ListBox> ShipFightersBrowseWnd::m_bay_list private
Referenced by Initialize(), and UpdateEffectLabelsAndValues().
m_hangar_list
std::shared_ptr<GG::ListBox> ShipFightersBrowseWnd::m_hangar_list private
Referenced by Initialize(), and UpdateEffectLabelsAndValues().
m_show_all_bouts
bool ShipFightersBrowseWnd::m_show_all_bouts private
Referenced by UpdateEffectLabelsAndValues().
The documentation for this class was generated from the following files:
MeterBrowseWnd.h
MeterBrowseWnd.cpp