FreeOrion: MessageWnd Class Reference
MessageWnd Class Reference
#include <ChatWnd.h>
Public Member Functions
MessageWnd (GG::Flags< GG::WndFlag > flags, const std::string &config_name="")
void Clear ()
void CompleteConstruction () override
std::string GetText () const
void HandleDiplomaticStatusChange (int empire1_id, int empire2_id)
void HandleGameStatusUpdate (const std::string &text)
void HandleLogMessage (const std::string &text)
void HandlePlayerChatMessage (const std::string &text, const std::string &player_name, GG::Clr text_color, const boost::posix_time::ptime &timestamp, int recipient_player_id, bool pm)
void HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id, bool prefixed=false)
void OpenForInput ()
void PreRender () override
void SetChatText (const std::string &chat_text)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIWnd
CUIWnd (std::string wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (std::string wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
virtual ~CUIWnd ()
Virtual destructor.
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void Close ()
void CompleteConstruction () override
void Flash ()
void Hide () override
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
bool InWindow (const GG::Pt &pt) const override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
bool Minimized () const
returns true if window is minimized
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseLeave () override
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
void Render () override
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
void SetFlashDuration (int ms)
void Show () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void StopFlash ()
void ToggleMinimized ()
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Public Attributes
boost::signals2::signal< void()> ClosingSignal
boost::signals2::signal< void()> DoneTypingSignal
emitted when the edit loses focus.
boost::signals2::signal< void()> TypingSignal
emitted when the edit gains focus.
Private Member Functions
void CloseClicked () override
called when window is closed via the close button
void DoLayout ()
void HandleTextCommand (const std::string &text)
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
void MessageEntered ()
void MessageHistoryDownRequested ()
void MessageHistoryUpRequested ()
Private Attributes
std::shared_ptr< GG::MultiEdit > m_display
int m_display_show_time
std::shared_ptr< MessageWndEdit > m_edit
std::deque< std::string > m_history
int m_history_position
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
void Init ()
performs initialization common to all CUIWnd constructors
virtual void InitBuffers ()
virtual void InitButtons ()
called to create the buttons, withtout positioning them
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void LoadOptions ()
loads options for this window from the OptionsDB
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
virtual void PositionButtons ()
called to position the buttons
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SaveDefaultedOptions ()
sets the default value any options previously determined from calls to SetDefaultedOptions to their current value
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
void SetDefaultedOptions ()
flags options currently at their default values for later use in SaveDefaultedOptions
void SetParent (std::shared_ptr< GG::Wnd > wnd) override
Static Protected Member Functions inherited from CUIWnd
static std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable = false
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable = false
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button
the pin button
bool m_pinable = false
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable = false
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 15
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 9
static const int RESIZE_HASHMARK2_OFFSET = 4
static const int TITLE_OFFSET = 2
Constructor & Destructor Documentation
MessageWnd()
MessageWnd::MessageWnd (GG::Flags< GG::WndFlag > flags, const std::string & config_name = "")
Member Function Documentation
Clear()
void MessageWnd::Clear ()
References m_display.
CloseClicked()
void MessageWnd::CloseClicked () override private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal, and CUIWnd::StopFlash().
CompleteConstruction()
void MessageWnd::CompleteConstruction () override
References CUIWnd::CompleteConstruction(), EmpireManager::DiplomaticStatusChangedSignal, DoLayout(), DoneTypingSignal, Empires(), HandleDiplomaticStatusChange(), m_display, m_edit, m_history, MessageEntered(), MessageHistoryDownRequested(), MessageHistoryUpRequested(), CUIWnd::SaveDefaultedOptions(), and TypingSignal.
DoLayout()
void MessageWnd::DoLayout () private
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_display, m_edit, and anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD.
Referenced by CompleteConstruction(), and PreRender().
GetText()
std::string MessageWnd::GetText () const
References m_display.
HandleDiplomaticStatusChange()
void MessageWnd::HandleDiplomaticStatusChange (int empire1_id, int empire2_id)
References ClientApp::EmpireID(), Empires(), ErrorLogger, CUIWnd::Flash(), FlexibleFormat(), ClientApp::GetApp(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), m_display, m_display_show_time, CUIWnd::Show(), and UserString().
Referenced by CompleteConstruction().
HandleGameStatusUpdate()
void MessageWnd::HandleGameStatusUpdate (const std::string & text)
References m_display, and m_display_show_time.
HandleLogMessage()
void MessageWnd::HandleLogMessage (const std::string & text)
References m_display, and m_display_show_time.
HandlePlayerChatMessage()
void MessageWnd::HandlePlayerChatMessage (const std::string & text, const std::string & player_name, GG::Clr text_color, const boost::posix_time::ptime & timestamp, int recipient_player_id, bool pm)
References ErrorLogger, CUIWnd::Flash(), ClientUI::FormatTimestamp(), ClientApp::GetApp(), m_display, m_display_show_time, ClientApp::PlayerID(), ClientApp::Players(), CUIWnd::Show(), anonymous_namespace{ChatWnd.cpp}::StringtableTextSubstitute(), TraceLogger, and UserString().
HandleTextCommand()
void MessageWnd::HandleTextCommand (const std::string & text) private
References anonymous_namespace{ChatWnd.cpp}::ExtractMessage(), anonymous_namespace{ChatWnd.cpp}::ExtractPlayerID(), ClientUI::GetClientUI(), Networking::INVALID_PLAYER_ID, m_display, m_display_show_time, anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), UserString(), and UserStringNop.
Referenced by MessageEntered().
HandleTurnPhaseUpdate()
void MessageWnd::HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id, bool prefixed = false)
References ErrorLogger, FlexibleFormat(), m_display, m_display_show_time, and UserString().
LClick()
void MessageWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override private
References CUIWnd::LClick(), and CUIWnd::StopFlash().
LDrag()
void MessageWnd::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override private
References CUIWnd::LDrag(), and CUIWnd::StopFlash().
MessageEntered()
void MessageWnd::MessageEntered () private
References ClientUI::GetClientUI(), HandleTextCommand(), m_display_show_time, m_edit, m_history, m_history_position, anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), and CUIWnd::StopFlash().
Referenced by CompleteConstruction().
MessageHistoryDownRequested()
void MessageWnd::MessageHistoryDownRequested () private
References m_edit, m_history, and m_history_position.
Referenced by CompleteConstruction().
MessageHistoryUpRequested()
void MessageWnd::MessageHistoryUpRequested () private
References m_edit, m_history, and m_history_position.
Referenced by CompleteConstruction().
OpenForInput()
void MessageWnd::OpenForInput ()
References m_display_show_time, and m_edit.
PreRender()
void MessageWnd::PreRender () override
References DoLayout().
SetChatText()
void MessageWnd::SetChatText (const std::string & chat_text)
References m_display.
SizeMove()
void MessageWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References CUIWnd::SizeMove().
Member Data Documentation
ClosingSignal
boost::signals2::signal<void ()> MessageWnd::ClosingSignal mutable
Referenced by CloseClicked().
DoneTypingSignal
boost::signals2::signal<void ()> MessageWnd::DoneTypingSignal mutable
emitted when the edit loses focus.
not necessary when a message is sent
Referenced by CompleteConstruction().
m_display
std::shared_ptr<GG::MultiEdit> MessageWnd::m_display private
Referenced by Clear(), CompleteConstruction(), DoLayout(), GetText(), HandleDiplomaticStatusChange(), HandleGameStatusUpdate(), HandleLogMessage(), HandlePlayerChatMessage(), HandleTextCommand(), HandleTurnPhaseUpdate(), and SetChatText().
m_display_show_time
int MessageWnd::m_display_show_time private
Referenced by HandleDiplomaticStatusChange(), HandleGameStatusUpdate(), HandleLogMessage(), HandlePlayerChatMessage(), HandleTextCommand(), HandleTurnPhaseUpdate(), MessageEntered(), and OpenForInput().
m_edit
std::shared_ptr<MessageWndEdit> MessageWnd::m_edit private
Referenced by CompleteConstruction(), DoLayout(), MessageEntered(), MessageHistoryDownRequested(), MessageHistoryUpRequested(), and OpenForInput().
m_history
std::deque<std::string> MessageWnd::m_history private
Referenced by CompleteConstruction(), MessageEntered(), MessageHistoryDownRequested(), and MessageHistoryUpRequested().
m_history_position
int MessageWnd::m_history_position private
Referenced by MessageEntered(), MessageHistoryDownRequested(), and MessageHistoryUpRequested().
TypingSignal
boost::signals2::signal<void ()> MessageWnd::TypingSignal mutable
emitted when the edit gains focus.
Keyboard accelerators elsewhere should be disabled
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
ChatWnd.h
ChatWnd.cpp