FreeOrion: CUICheckBoxRepresenter Class Reference
CUICheckBoxRepresenter Class Reference
A FreeOrion styled check box state button.
#include <CUIControls.h>
Public Member Functions
void OnChanged (const GG::StateButton &button, GG::StateButton::ButtonState prev_state) const override
void OnChecked (bool checked) const override
void Render (const GG::StateButton &button) const override
Detailed Description
A FreeOrion styled check box state button.
Member Function Documentation
OnChanged()
void CUICheckBoxRepresenter::OnChanged (const GG::StateButton & button, GG::StateButton::ButtonState prev_state) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
OnChecked()
void CUICheckBoxRepresenter::OnChecked (bool checked) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Render()
void CUICheckBoxRepresenter::Render (const GG::StateButton & button) const override
References AdjustBrightness(), AngledCornerRectangle(), anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, ClientUI::CtrlBorderColor(), anonymous_namespace{CombatLogWnd.cpp}::MARGIN, and anonymous_namespace{CUIControls.cpp}::STATE_BUTTON_BRIGHTENING_SCALE_FACTOR.
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp