FreeOrion: OptionsDB Class Reference
OptionsDB Class Reference
a database of values of arbitrarily mixed types that can be initialized from an XML config file and/or the command line.
#include <OptionsDB.h>
Classes
struct Option
struct OptionSection
Public Types
typedef boost::signals2::signal< void(const std::string &)> OptionAddedSignalType
emitted when an option is added
typedef boost::signals2::signal< void()> OptionChangedSignalType
emitted when an option has changed
typedef boost::signals2::signal< void(const std::string &)> OptionRemovedSignalType
emitted when an option is removed
Public Member Functions
template<typename T >
void Add (const std::string &name, const std::string &description, T default_value, const ValidatorBase &validator=Validator< T >(), bool storable=true, const std::string &section=std::string())
adds an Option, optionally with a custom validator
template<typename T >
void Add (char short_name, const std::string &name, const std::string &description, T default_value, const ValidatorBase &validator=Validator< T >(), bool storable=true, const std::string &section=std::string())
adds an Option with an alternative one-character shortened name, optionally with a custom validator
void AddFlag (const std::string &name, const std::string &description, bool storable=true, const std::string &section=std::string())
adds a flag Option, which is treated as a boolean value with a default of false.
void AddFlag (char short_name, const std::string &name, const std::string &description, bool storable=true, const std::string &section=std::string())
adds an Option with an alternative one-character shortened name, which is treated as a boolean value with a default of false.
void AddSection (const std::string &name, const std::string &description, std::function< bool(const std::string &)> option_predicate=nullptr)
Defines an option section with a description and optionally a option predicate.
bool Commit (bool only_if_dirty=true, bool only_non_default=true)
write the optionDB's non-default state to the XML config file.
bool CommitPersistent ()
Write any options that are not at default value to persistent config, replacing any existing file.
void FindOptions (std::set< std::string > &ret, const std::string &prefix, bool allow_unrecognized=false) const
find all registered Options that begin with prefix and store them in ret.
template<typename T >
T Get (const std::string &name) const
returns the value of option name.
template<typename T >
T GetDefault (const std::string &name) const
returns the default value of option name.
std::string GetDefaultValueString (const std::string &option_name) const
returns the string representation of the default value of the option name.
const std::string & GetDescription (const std::string &option_name) const
returns the description string for option option_name, or throws std::runtime_error if no such Option exists.
void GetUsage (std::ostream &os, const std::string &command_line="", bool allow_unrecognized=false) const
writes a usage message to os
std::shared_ptr< const ValidatorBase > GetValidator (const std::string &option_name) const
returns the validator for option option_name, or throws std::runtime_error if no such Option exists.
std::string GetValueString (const std::string &option_name) const
returns the string representation of the value of the option name.
void GetXML (XMLDoc &doc, bool non_default_only=false, bool include_version=true) const
Saves the contents of the options DB to the doc XMLDoc.
bool IsDefaultValue (const std::string &name) const
OptionChangedSignalType & OptionChangedSignal (const std::string &option)
the option changed signal object for the given option
bool OptionExists (const std::string &name) const
indicates whether an option with name name has been added to this OptionsDB.
void Remove (const std::string &name)
removes an Option
void RemoveUnrecognized (const std::string &prefix="")
removes all unrecognized Options that begin with prefix.
template<typename T >
void Set (const std::string &name, const T &value)
sets the value of option name to value
template<typename T >
void SetDefault (const std::string &name, const T &value)
Set the default value of option name to value.
void SetFromCommandLine (const std::vector< std::string > &args)
fills some or all of the options of the DB from values passed in from the command line
void SetFromFile (const boost::filesystem::path &file_path, const std::string &version="")
if an xml file exists at file_path and has the same version tag as version, fill the DB options contained in that file (read the file using XMLDoc, then fill the DB using SetFromXML) if the version string is empty, bypass that check
void SetFromXML (const XMLDoc &doc)
fills some or all of the options of the DB from values stored in XMLDoc doc
void Validate (const std::string &name, const std::string &value) const
validates a value for an option.
Public Attributes
OptionAddedSignalType OptionAddedSignal
the option added signal object for this DB
OptionRemovedSignalType OptionRemovedSignal
the change removed signal object for this DB
Private Member Functions
OptionsDB ()
bool IsDefaultValue (std::map< std::string, Option >::const_iterator it) const
indicates whether the current value of the option references by is the default value for that option
bool OptionExists (std::map< std::string, Option >::const_iterator it) const
indicates whether the option referenced by it has been added to this OptionsDB.
std::unordered_map< std::string, std::set< std::string > > OptionsBySection (bool allow_unrecognized=false) const
Determine known option sections and which options each contains A special "root" section is added for determined top-level sections.
void SetFromXMLRecursive (const XMLElement &elem, const std::string &section_name)
Private Attributes
bool m_dirty
std::map< std::string, Option > m_options
std::unordered_map< std::string, OptionSection > m_sections
Static Private Attributes
static OptionsDB * s_options_db = nullptr
Friends
FO_COMMON_API OptionsDB & GetOptionsDB ()
returns the single instance of the OptionsDB class
Detailed Description
a database of values of arbitrarily mixed types that can be initialized from an XML config file and/or the command line.
OptionsDB should be used for initializing global settings for an application that should be specified from the command line or from config files. Such options might be the resolution to use when running the program, the color depth, number of players, etc. The entire DB can be written out to config file, to later be reloaded. This allows runtime settings to be preserved from one execution to the next, and still allows overrides of these settings from the command line.
OptionsDB must have its options and their types specified before any values are assigned to those options. This is because setting an option in the DB requires the type of the option to be known in advance. To specify the options, you may either use static initialization time or normal runtime calls to Add() and AddFlag(). Note that the exact type of added item must be specified with Add*(), so that subsequent calls to Get() do not throw. For instance, if you want to add an unsigned value accessible as "foo", you should call:
      Add("foo", "The number of foos.", 1u);
Making the same call as above with "1" instead of "1u" will cause a later call to Get<unsigned int>("foo") to throw, since "foo" would be an int, not an unsigned int. To guard against this, you may wish to call Add() with an explicit template parameterization, such as Add<unsigned int>(...).
Flag options are just boolean values that are false by default. Their values may be read and set normally, the same as any other boolean option. For exapmple, reading a flag's value form the DB can be done using using:
      Get<bool>(flag_name);endverbatim
* <br><br>Adding options at static initialization time means that the options
* specified will be available before main() is called, and yet you do not
* have to fill main.cpp with all your option specifications.  Instead, you
* can put them in the files in which their options are used.
* <br><br>OptionsDB has an optional dotted notation for option names.  This
* is important in use with XML only.  When options are specified as e.g.
* "foo.bar1" and "foo.bar2", the resulting XML file will show them as:\verbatim
      <foo>
          <bar1>x</bar>
          <bar2>y</bar>
      </foo>
This allows options to be grouped in ways that are sensible for the application. This is only done as a convenience to the user. It does not change the way the options are treated in any way. Note that is is perfectly legal also to have an option "foo" containing a value "z" in the example above.
A few things should be said about the command-line version of options. All flag command-line options (specified with AddFlag()) are assumed to have false as their default value. This means that their mere presence on the command line means that they indicate a value of true; they need no argument. For example, specifying "--version" on the command line sets the option "version" in the DB to true, and leaving it out sets the option to false.
Long-form names should be preceded with "--", and the single-character version should be preceded with "-". An exception to this is that multiple single-character (boolean) options may be run together (e.g. "-cxvf"). Also, the last option in such a group may take an argument, which must immediately follow the group, separated by a space as (usual.
Finally, note that std::runtime_error exceptions will be thrown any time a problem occurs with an option (calling Get() for one that doesn't exist, Add()ing one twice, etc.), and boost::bad_any_cast exceptions will be thrown in situations in which an invalid type-conversion occurs, including string-to-type, type-to-string or type-to-type as in the case of Get() calls with the wrong tempate parameter.
See also
RegisterOptions (for static-time options specification)
Member Typedef Documentation
OptionAddedSignalType
typedef boost::signals2::signal<void (const std::string&)> OptionsDB::OptionAddedSignalType
emitted when an option is added
OptionChangedSignalType
typedef boost::signals2::signal<void ()> OptionsDB::OptionChangedSignalType
emitted when an option has changed
OptionRemovedSignalType
typedef boost::signals2::signal<void (const std::string&)> OptionsDB::OptionRemovedSignalType
emitted when an option is removed
Constructor & Destructor Documentation
OptionsDB()
OptionsDB::OptionsDB () private
References s_options_db.
Member Function Documentation
Add() [1/2]
template<typename T > void OptionsDB::Add (const std::string & name, const std::string & description, T default_value, const ValidatorBase & validator = Validator<T>(), bool storable = true, const std::string & section = std::string()) inline
adds an Option, optionally with a custom validator
References ErrorLogger.
Referenced by GameRules::Add(), anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), anonymous_namespace{Networking.cpp}::AddOptions(), anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{ResearchWnd.cpp}::AddOptions(), anonymous_namespace{SitRepPanel.cpp}::AddOptions(), anonymous_namespace{ProductionWnd.cpp}::AddOptions(), anonymous_namespace{ServerConnectWnd.cpp}::AddOptions(), anonymous_namespace{TechTreeWnd.cpp}::AddOptions(), anonymous_namespace{BuildDesignatorWnd.cpp}::AddOptions(), anonymous_namespace{ObjectListWnd.cpp}::AddOptions(), anonymous_namespace{FleetButton.cpp}::AddOptions(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::AddOptions(), anonymous_namespace{GraphicalSummary.cpp}::AddOptions(), anonymous_namespace{SaveFileDialog.cpp}::AddOptions(), anonymous_namespace{Universe.cpp}::AddOptions(), Hotkey::AddOptions(), anonymous_namespace{HumanClientApp.cpp}::AddOptions(), anonymous_namespace{MapWnd.cpp}::AddOptions(), anonymous_namespace{GalaxySetupWnd.cpp}::AddOptions(), anonymous_namespace{FleetWnd.cpp}::AddOptions(), anonymous_namespace{SidePanel.cpp}::AddOptions(), anonymous_namespace{ClientUI.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption(), CUIWnd::AddWindowOptions(), HumanClientApp::AddWindowSizeOptionsAfterMainStart(), main(), mainConfigOptionsSetup(), HumanClientApp::MultiPlayerGame(), anonymous_namespace{IntroScreen.cpp}::Options(), ServerConnectWnd::PopulateServerList(), and WaitingForMPJoinAck::react().
Add() [2/2]
template<typename T > void OptionsDB::Add (char short_name, const std::string & name, const std::string & description, T default_value, const ValidatorBase & validator = Validator<T>(), bool storable = true, const std::string & section = std::string()) inline
adds an Option with an alternative one-character shortened name, optionally with a custom validator
References ErrorLogger.
AddFlag() [1/2]
void OptionsDB::AddFlag (const std::string & name, const std::string & description, bool storable = true, const std::string & section = std::string()) inline
adds a flag Option, which is treated as a boolean value with a default of false.
Using the flag on the command line at all indicates that its value it set to true.
References ErrorLogger.
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{CUIWnd.cpp}::AddOptions(), main(), mainConfigOptionsSetup(), and anonymous_namespace{IntroScreen.cpp}::Options().
AddFlag() [2/2]
void OptionsDB::AddFlag (char short_name, const std::string & name, const std::string & description, bool storable = true, const std::string & section = std::string()) inline
adds an Option with an alternative one-character shortened name, which is treated as a boolean value with a default of false.
Using the flag on the command line at all indicates that its value it set to true.
References ErrorLogger.
AddSection()
void OptionsDB::AddSection (const std::string & name, const std::string & description, std::function< bool(const std::string &)> option_predicate = nullptr)
Defines an option section with a description and optionally a option predicate.
Parameters
name Name of section, typically in the form of a left side subset of an option name.
description Stringtable key used for local description
option_predicate Functor accepting a option name in the form of a std::string const ref and returning a bool. Options which return true are displayed in the section for name
References if(), and m_sections.
Referenced by mainConfigOptionsSetup().
Commit()
bool OptionsDB::Commit (bool only_if_dirty = true, bool only_non_default = true)
write the optionDB's non-default state to the XML config file.
References ErrorLogger, GetConfigPath(), GetOptionsDB, GetXML(), m_dirty, PathToString(), UserString(), and XMLDoc::WriteDoc().
Referenced by OptionsWnd::DoneClicked(), HumanClientApp::GetWindowWidthHeight(), HumanClientApp::HandleWindowMove(), HumanClientApp::HandleWindowResize(), CUIWnd::InvalidateUnusedOptions(), mainConfigOptionsSetup(), ServerConnectWnd::OkClicked(), GalaxySetupWnd::OkClicked(), WaitingForMPJoinAck::react(), CUIWnd::SaveOptions(), BarSizer::Set(), anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), and TechTreeWnd::SetTechStatus().
CommitPersistent()
bool OptionsDB::CommitPersistent ()
Write any options that are not at default value to persistent config, replacing any existing file.
Returns
bool If file was successfully written
References ErrorLogger, GetOptionsDB, GetPersistentConfigPath(), GetXML(), UserString(), and XMLDoc::WriteDoc().
FindOptions()
void OptionsDB::FindOptions (std::set< std::string > & ret, const std::string & prefix, bool allow_unrecognized = false) const
find all registered Options that begin with prefix and store them in ret.
If allow_unrecognized then include unrecognized options.
References m_options.
Referenced by GetUsage(), CUIWnd::InvalidateUnusedOptions(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), ServerConnectWnd::PopulateServerList(), and CUIWnd::SetDefaultedOptions().
Get()
template<typename T > T OptionsDB::Get (const std::string & name) const inline
returns the value of option name.
Note that the exact type of item stored in the option name must be known in advance. This means that Get() must be called as Get<int>("foo"), etc.
References ErrorLogger.
Referenced by GameRules::Add(), AIClientApp::AIClientApp(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), HumanClientApp::Autosave(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), OptionsWnd::ColorOption(), OptionsWnd::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), CompleteXDGMigration(), ServerApp::CreateAIClients(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), ClientUI::DefaultLinkColor(), Networking::DiscoveryPort(), MapWnd::DispatchFleetsExploring(), ClientUI::DisplayTimestamp(), OptionsWnd::DoubleOption(), ClientUI::DropDownListArrowColor(), ClientUI::EditHiliteColor(), AIClientApp::EffectsProcessingThreads(), HumanClientApp::EffectsProcessingThreads(), ServerApp::EffectsProcessingThreads(), SystemIcon::EnclosingCircleDiameter(), OptionsWnd::FileOptionImpl(), SaveFileListBox::FilterColumns(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), BarSizer::Get(), SaveFileColumn::GetColumn(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), anonymous_namespace{SitRepPanel.cpp}::GetIconSize(), anonymous_namespace{MapWnd.cpp}::GetOrderedFleetRoute(), GetSaveDir(), GetServerSaveDir(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{i18n.cpp}::GetStringTableFileName(), HumanClientApp::GetWindowLeftTop(), HumanClientApp::GetWindowWidthHeight(), HumanClientApp::HandleFocusChange(), ClientUI::HandleFullscreenSwitch(), ServerFSM::HandleNonLobbyDisconnection(), EncyclopediaDetailPanel::HandleSearchTextEntered(), ClientUI::HandleSizeChange(), anonymous_namespace{SitRepPanel.cpp}::HiddenSitRepTemplateStringsFromOptions(), HumanClientApp::HumanClientApp(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), CUIWnd::InitSizeMove(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), MapWnd::InitVisibilityRadiiRenderingBuffers(), OptionsWnd::IntOption(), CUIWnd::InvalidateWindowOptions(), PlayerConnection::IsBinarySerializationUsed(), ServerApp::IsHostless(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), SitRepPanel::IsSitRepInvalid(), ClientUI::KnownTechFillColor(), ClientUI::KnownTechTextAndBorderColor(), TechTreeWnd::LayoutPanel::Layout(), FleetButton::LayoutIcons(), MapWnd::LClick(), CUIWnd::LoadOptions(), SaveFileListBox::LoadSaveGamePreviews(), main(), mainSetupAndRun(), anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), ClientUI::MediumFleetButtonZoomThreshold(), Networking::MessagePort(), SystemIcon::MouseEnter(), HumanClientApp::MultiPlayerGame(), anonymous_namespace{FleetWnd.cpp}::NewFleetsAggressiveOptionSetting(), HumanClientApp::NewSinglePlayerGame(), detail::PlayValueChangedSound::operator()(), ParticipantBar::ParticipantBar(), anonymous_namespace{SidePanel.cpp}::PlanetDiameter(), anonymous_namespace{SystemIcon.cpp}::PlaySounds(), ServerConnectWnd::PopulateServerList(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), IntroScreen::PreRender(), ClientUI::Pts(), MapWnd::RClick(), Idle::react(), MPLobby::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), Hotkey::ReadFromOptions(), BuildingIndicator::Refresh(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), HumanClientApp::Reinitialize(), MapWnd::RenderFields(), MapWnd::RenderFleetMovementLines(), MapWnd::RenderStarfields(), MapWnd::RenderStarlanes(), MapWnd::RenderSystems(), anonymous_namespace{ClientUI.cpp}::RequiredCharsets(), ClientUI::ResearchableTechFillColor(), ClientUI::ResearchableTechTextAndBorderColor(), HumanClientApp::ResetOrExitApp(), OptionsWnd::ResolutionOption(), ClientUI::RolloverLinkColor(), CUIWnd::SaveDefaultedOptions(), SaveGame(), CUIWnd::SaveOptions(), ClientUI::ScrollWidth(), ServerApp::ServerApp(), anonymous_namespace{HumanClientApp.cpp}::SetEmptyStringDefaultOption(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), SystemIcon::SizeMove(), ClientUI::SmallFleetButtonZoomThreshold(), HumanClientApp::StartServer(), HumanClientApp::StartTurn(), ScanlineRenderer::Impl::StartUsing(), ClientUI::StatDecrColor(), ClientUI::StateButtonColor(), ClientUI::StatIncrColor(), ClientUI::SystemCircleSize(), ClientUI::SystemIconSize(), ClientUI::SystemNameTextColor(), ClientUI::SystemSelectionIndicatorRPM(), ClientUI::SystemSelectionIndicatorSize(), ClientUI::SystemTinyIconSizeThreshold(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), ClientUI::TextColor(), ClientUI::TinyFleetButtonZoomThreshold(), ClientUI::TitlePts(), anonymous_namespace{MapWnd.cpp}::ToggleBoolOption(), HumanClientApp::ToggleFullscreen(), ClientUI::UnresearchableTechFillColor(), ClientUI::UnresearchableTechTextAndBorderColor(), FleetDataPanel::UpdateAggressionToggle(), FPSIndicator::UpdateEnabled(), MapWnd::MapScaleLine::UpdateEnabled(), HumanClientApp::UpdateFPSLimit(), Universe::UpdateMeterEstimates(), MPLobby::ValidateClientLimits(), WaitingForTurnEnd::WaitingForTurnEnd(), ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
GetDefault()
template<typename T > T OptionsDB::GetDefault (const std::string & name) const inline
returns the default value of option name.
Note that the exact type of item stored in the option name must be known in advance. This means that GetDefault() must be called as Get<int>("foo"), etc.
References ErrorLogger.
Referenced by OptionsWnd::ColorOption(), GetSaveDir(), GetServerSaveDir(), anonymous_namespace{i18n.cpp}::GetStringTable(), anonymous_namespace{i18n.cpp}::GetStringTableFileName(), ClientUI::HandleFullscreenSwitch(), ClientUI::HandleSizeChange(), CUIWnd::InvalidateWindowOptions(), and anonymous_namespace{ClientUI.cpp}::RequiredCharsets().
GetDefaultValueString()
std::string OptionsDB::GetDefaultValueString (const std::string & option_name) const
returns the string representation of the default value of the option name.
References m_options, and OptionExists().
GetDescription()
const std::string & OptionsDB::GetDescription (const std::string & option_name) const
returns the description string for option option_name, or throws std::runtime_error if no such Option exists.
References m_options, and OptionExists().
GetUsage()
void OptionsDB::GetUsage (std::ostream & os, const std::string & command_line = "", bool allow_unrecognized = false) const
writes a usage message to os
References FindOptions(), if(), m_options, m_sections, anonymous_namespace{OptionsDB.cpp}::OptionNameHasParentSection(), OptionsBySection(), OverrideAllLoggersThresholds(), anonymous_namespace{OptionsDB.cpp}::SplitText(), UserString(), and warn.
Referenced by if(), and main().
GetValidator()
std::shared_ptr< const ValidatorBase > OptionsDB::GetValidator (const std::string & option_name) const
returns the validator for option option_name, or throws std::runtime_error if no such Option exists.
References m_options, and OptionExists().
Referenced by OptionsWnd::DoubleOption(), OptionsWnd::IntOption(), OptionsWnd::MusicVolumeOption(), OptionsWnd::ResolutionOption(), and OptionsWnd::VolumeOption().
GetValueString()
std::string OptionsDB::GetValueString (const std::string & option_name) const
returns the string representation of the value of the option name.
References m_options, and OptionExists().
Referenced by OptionsWnd::CompleteConstruction().
GetXML()
void OptionsDB::GetXML (XMLDoc & doc, bool non_default_only = false, bool include_version = true) const
Saves the contents of the options DB to the doc XMLDoc.
Parameters
[in,out] doc The document this OptionsDB should be written to. This resets the given doc.
[in] non_default_only Do not include options which are set to their default value, is unrecognized, or is "version.string"
References XMLElement::children, IsDefaultValue(), m_options, anonymous_namespace{OptionsDB.cpp}::PreviousSectionName(), XMLDoc::root_node, XMLElement::SetText(), and XMLElement::Tag().
Referenced by Commit(), and CommitPersistent().
IsDefaultValue() [1/2]
bool OptionsDB::IsDefaultValue (const std::string & name) const inline
Referenced by GetXML(), and CUIWnd::SetDefaultedOptions().
IsDefaultValue() [2/2]
bool OptionsDB::IsDefaultValue (std::map< std::string, Option >::const_iterator it) const inline private
indicates whether the current value of the option references by is the default value for that option
OptionChangedSignal()
OptionsDB::OptionChangedSignalType & OptionsDB::OptionChangedSignal (const std::string & option)
the option changed signal object for the given option
References m_options.
Referenced by ClientUI::ClientUI(), MapWnd::CompleteConstruction(), MapWnd::MapScaleLine::CompleteConstruction(), anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption(), FPSIndicator::FPSIndicator(), GetResourceDir(), and HumanClientApp::HumanClientApp().
OptionExists() [1/2]
bool OptionsDB::OptionExists (const std::string & name) const inline
indicates whether an option with name name has been added to this OptionsDB.
Referenced by GameRules::Add(), anonymous_namespace{ResearchWnd.cpp}::AddOptions(), anonymous_namespace{ProductionWnd.cpp}::AddOptions(), CUIWnd::AddWindowOptions(), SaveFileColumn::GetColumn(), GetDefaultValueString(), GetDescription(), GetValidator(), GetValueString(), CUIWnd::InitSizeMove(), CUIWnd::InvalidateUnusedOptions(), CUIWnd::InvalidateWindowOptions(), CUIWnd::LoadOptions(), HumanClientApp::MultiPlayerGame(), OptionsDB::Get< std::vector< std::string > >(), Hotkey::ReadFromOptions(), CUIWnd::SaveOptions(), SetLoggerThresholds(), Validate(), FreeOrionPython::WrapConfig(), and CUIWnd::~CUIWnd().
OptionExists() [2/2]
bool OptionsDB::OptionExists (std::map< std::string, Option >::const_iterator it) const inline private
indicates whether the option referenced by it has been added to this OptionsDB.
Overloaded for convenient use within other OptionsDB functions
OptionsBySection()
std::unordered_map< std::string, std::set< std::string > > OptionsDB::OptionsBySection (bool allow_unrecognized = false) const private
Determine known option sections and which options each contains A special "root" section is added for determined top-level sections.
References m_options, and m_sections.
Referenced by GetUsage().
Remove()
void OptionsDB::Remove (const std::string & name)
removes an Option
References m_dirty, m_options, OptionRemovedSignal, and OptionsDB::Option::short_names.
Referenced by CUIWnd::AddWindowOptions(), RemoveUnrecognized(), and CUIWnd::~CUIWnd().
RemoveUnrecognized()
void OptionsDB::RemoveUnrecognized (const std::string & prefix = "")
removes all unrecognized Options that begin with prefix.
A blank string will remove all unrecognized Options.
References m_options, and Remove().
Referenced by CUIWnd::InvalidateUnusedOptions().
Set()
template<typename T > void OptionsDB::Set (const std::string & name, const T & value) inline
sets the value of option name to value
Referenced by AIClientApp::AIClientApp(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), OptionsWnd::BoolOption(), OptionsWnd::ColorOption(), CompleteXDGMigration(), CUIWnd::CUIWnd(), OptionsWnd::DoubleOption(), OptionsWnd::FileOptionImpl(), HumanClientApp::GetWindowWidthHeight(), ClientUI::HandleSizeChange(), HumanClientApp::HandleWindowMove(), HumanClientApp::HandleWindowResize(), TechTreeWnd::HidePedia(), BuildDesignatorWnd::HidePedia(), HumanClientApp::HumanClientApp(), CUIWnd::InitSizeMove(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), OptionsWnd::IntOption(), CUIWnd::InvalidateWindowOptions(), mainConfigOptionsSetup(), HumanClientApp::MultiPlayerGame(), OptionsWnd::SoundOptionsFeedback::MusicClicked(), OptionsWnd::SoundOptionsFeedback::MusicVolumeSlid(), ServerConnectWnd::OkClicked(), GalaxySetupWnd::OkClicked(), MapWnd::RClick(), WaitingForMPJoinAck::react(), Hotkey::ResetHotkey(), OptionsWnd::ResolutionOption(), CUIWnd::SaveOptions(), ServerApp::ServerApp(), BarSizer::Set(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), anonymous_namespace{HumanClientApp.cpp}::SetEmptyStringDefaultOption(), anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), Hotkey::SetHotkey(), SetLoggerThresholds(), Sound::Impl::SetMusicVolume(), anonymous_namespace{FleetWnd.cpp}::SetNewFleetAggressiveOptionSetting(), TechTreeWnd::LayoutPanel::SetScale(), TechTreeWnd::SetTechStatus(), Sound::Impl::SetUISoundsVolume(), TechTreeWnd::ShowPedia(), BuildDesignatorWnd::ShowPedia(), OptionsWnd::SoundOptionsFeedback::SoundEffectsEnableClicked(), OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure(), anonymous_namespace{MapWnd.cpp}::ToggleBoolOption(), HumanClientApp::ToggleFullscreen(), OptionsWnd::SoundOptionsFeedback::UISoundsVolumeSlid(), and MPLobby::ValidateClientLimits().
SetDefault()
template<typename T > void OptionsDB::SetDefault (const std::string & name, const T & value) inline
Set the default value of option name to value.
References tag_parser::args.
Referenced by anonymous_namespace{i18n.cpp}::InitStringtableFileName(), CUIWnd::SaveDefaultedOptions(), and anonymous_namespace{HumanClientApp.cpp}::SetEmptyStringDefaultOption().
SetFromCommandLine()
void OptionsDB::SetFromCommandLine (const std::vector< std::string > & args)
fills some or all of the options of the DB from values passed in from the command line
References OptionsDB::Option::flag, m_dirty, m_options, OptionsDB::Option::name, OptionsDB::Option::SetFromString(), OptionsDB::Option::short_names, anonymous_namespace{OptionsDB.cpp}::StripQuotation(), OptionsDB::Option::value, and WarnLogger.
Referenced by main(), and mainConfigOptionsSetup().
SetFromFile()
void OptionsDB::SetFromFile (const boost::filesystem::path & file_path, const std::string & version = "")
if an xml file exists at file_path and has the same version tag as version, fill the DB options contained in that file (read the file using XMLDoc, then fill the DB using SetFromXML) if the version string is empty, bypass that check
References XMLElement::Child(), XMLElement::ContainsChild(), GetOptionsDB, XMLDoc::ReadDoc(), XMLDoc::root_node, SetFromXML(), XMLElement::Text(), and UserString().
Referenced by main(), and mainConfigOptionsSetup().
SetFromXML()
void OptionsDB::SetFromXML (const XMLDoc & doc)
fills some or all of the options of the DB from values stored in XMLDoc doc
References XMLElement::children, XMLDoc::root_node, and SetFromXMLRecursive().
Referenced by SetFromFile().
SetFromXMLRecursive()
void OptionsDB::SetFromXMLRecursive (const XMLElement & elem, const std::string & section_name) private
References XMLElement::children, ErrorLogger, OptionsDB::Option::flag, m_dirty, m_options, OptionsDB::Option::SetFromString(), XMLElement::Tag(), XMLElement::Text(), TraceLogger, and OptionsDB::Option::value.
Referenced by SetFromXML().
Validate()
void OptionsDB::Validate (const std::string & name, const std::string & value) const
validates a value for an option.
throws std::runtime_error if no option name exists. throws bad_lexical_cast if value cannot be converted to the type of the option name.
References m_options, and OptionExists().
Friends And Related Function Documentation
GetOptionsDB
FO_COMMON_API OptionsDB& GetOptionsDB () friend
returns the single instance of the OptionsDB class
Referenced by Commit(), CommitPersistent(), and SetFromFile().
Member Data Documentation
m_dirty
bool OptionsDB::m_dirty private
Referenced by Commit(), Remove(), SetFromCommandLine(), and SetFromXMLRecursive().
m_options
std::map<std::string, Option> OptionsDB::m_options private
Referenced by FindOptions(), GetDefaultValueString(), GetDescription(), GetUsage(), GetValidator(), GetValueString(), GetXML(), OptionChangedSignal(), OptionsBySection(), OptionsDB::Get< std::vector< std::string > >(), Remove(), RemoveUnrecognized(), SetFromCommandLine(), SetFromXMLRecursive(), and Validate().
m_sections
std::unordered_map<std::string, OptionSection> OptionsDB::m_sections private
Referenced by AddSection(), GetUsage(), and OptionsBySection().
OptionAddedSignal
OptionAddedSignalType OptionsDB::OptionAddedSignal mutable
the option added signal object for this DB
OptionRemovedSignal
OptionRemovedSignalType OptionsDB::OptionRemovedSignal mutable
the change removed signal object for this DB
Referenced by Remove().
s_options_db
OptionsDB * OptionsDB::s_options_db = nullptr static private
Referenced by OptionsDB(), and OptionsDB::OptionSection::OptionSection().
The documentation for this class was generated from the following files:
OptionsDB.h
OptionsDB.cpp