FreeOrion: RotatingPlanetControl Class Reference
RotatingPlanetControl Class Reference
Public Member Functions
RotatingPlanetControl (GG::X x, GG::Y y, int planet_id, StarType star_type)
void Refresh ()
void Render () override
Private Attributes
int m_atmosphere_alpha = 1
GG::Rect m_atmosphere_planet_rect
std::shared_ptr< GG::Texture > m_atmosphere_texture
double m_axial_tilt = 0.0
int m_diameter = 1
double m_initial_rotation = 0.0
std::shared_ptr< GG::Texture > m_overlay_texture
int m_planet_id = INVALID_OBJECT_ID
double m_rpm = 1.0
double m_shininess = 0.0
StarType m_star_type = StarType::STAR_WHITE
std::shared_ptr< GG::Texture > m_surface_texture
Visibility m_visibility = Visibility::VIS_BASIC_VISIBILITY
Static Private Attributes
static ScanlineRenderer s_scanline_shader
Constructor & Destructor Documentation
RotatingPlanetControl()
RotatingPlanetControl::RotatingPlanetControl (GG::X x, GG::Y y, int planet_id, StarType star_type) inline
References Refresh().
Member Function Documentation
Refresh()
void RotatingPlanetControl::Refresh () inline
References ClientUI::ArtDir(), ObjectMap::get(), GGHumanClientApp::GetApp(), Universe::GetObjectVisibilityByEmpire(), anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), ClientUI::GetTexture(), GetUniverse(), m_atmosphere_alpha, m_atmosphere_planet_rect, m_atmosphere_texture, m_axial_tilt, m_diameter, m_overlay_texture, m_planet_id, m_rpm, m_shininess, m_surface_texture, m_visibility, Objects(), anonymous_namespace{SidePanel.cpp}::PlanetDiameter(), and RandInt().
Referenced by SidePanel::PlanetPanel::PlanetID(), and RotatingPlanetControl().
Render()
void RotatingPlanetControl::Render () inline override
References GetOptionsDB(), m_atmosphere_alpha, m_atmosphere_planet_rect, m_atmosphere_texture, m_axial_tilt, m_diameter, m_initial_rotation, m_overlay_texture, m_rpm, m_shininess, m_star_type, m_surface_texture, m_visibility, ScanlineRenderer::RenderCircle(), anonymous_namespace{SidePanel.cpp}::RenderPlanet(), s_scanline_shader, and ScanlineRenderer::SetColor().
Referenced by SidePanel::PlanetPanel::PlanetID().
Member Data Documentation
m_atmosphere_alpha
int RotatingPlanetControl::m_atmosphere_alpha = 1 private
Referenced by Refresh(), and Render().
m_atmosphere_planet_rect
GG::Rect RotatingPlanetControl::m_atmosphere_planet_rect private
Referenced by Refresh(), and Render().
m_atmosphere_texture
std::shared_ptr<GG::Texture> RotatingPlanetControl::m_atmosphere_texture private
Referenced by Refresh(), and Render().
m_axial_tilt
double RotatingPlanetControl::m_axial_tilt = 0.0 private
Referenced by Refresh(), and Render().
m_diameter
int RotatingPlanetControl::m_diameter = 1 private
Referenced by Refresh(), and Render().
m_initial_rotation
double RotatingPlanetControl::m_initial_rotation = 0.0 private
Referenced by Render().
m_overlay_texture
std::shared_ptr<GG::Texture> RotatingPlanetControl::m_overlay_texture private
Referenced by Refresh(), and Render().
m_planet_id
int RotatingPlanetControl::m_planet_id = INVALID_OBJECT_ID private
Referenced by SidePanel::PlanetPanel::PlanetID(), and Refresh().
m_rpm
double RotatingPlanetControl::m_rpm = 1.0 private
Referenced by Refresh(), and Render().
m_shininess
double RotatingPlanetControl::m_shininess = 0.0 private
Referenced by Refresh(), and Render().
m_star_type
StarType RotatingPlanetControl::m_star_type = StarType::STAR_WHITE private
Referenced by Render().
m_surface_texture
std::shared_ptr<GG::Texture> RotatingPlanetControl::m_surface_texture private
Referenced by Refresh(), and Render().
m_visibility
Visibility RotatingPlanetControl::m_visibility = Visibility::VIS_BASIC_VISIBILITY private
Referenced by Refresh(), and Render().
s_scanline_shader
ScanlineRenderer RotatingPlanetControl::s_scanline_shader static private
Referenced by Render().
The documentation for this class was generated from the following file:
SidePanel.cpp