FreeOrion: BuildingIndicator Class Reference
BuildingIndicator Class Reference
Represents and allows some user interaction with a building.
#include <BuildingsPanel.h>
Public Member Functions
BuildingIndicator (GG::X w, int building_id)
Constructor for use when building is completed, shown without progress bar.
BuildingIndicator (GG::X w, const std::string &building_type, double turns_completed, double total_turns, double total_cost, double turn_spending)
Constructor for use when building is partially complete, to show progress bar.
void CompleteConstruction () override
Mutators
void PreRender () override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
void Render () override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
Public Attributes
boost::signals2::signal< void(int)> RightClickedSignal
Private Member Functions
void DoLayout ()
void Refresh ()
Private Attributes
int m_building_id
std::shared_ptr< GG::StaticGraphic > m_graphic
bool m_order_issuing_enabled = true
std::shared_ptr< MultiTurnProgressBar > m_progress_bar
std::shared_ptr< GG::StaticGraphic > m_scrap_indicator
shown to indicate building was ordered scrapped
Static Private Attributes
static ScanlineRenderer s_scanline_shader
Detailed Description
Represents and allows some user interaction with a building.
Constructor & Destructor Documentation
BuildingIndicator() [1/2]
BuildingIndicator::BuildingIndicator (GG::X w, int building_id)
Constructor for use when building is completed, shown without progress bar.
References m_building_id, and Objects().
BuildingIndicator() [2/2]
BuildingIndicator::BuildingIndicator (GG::X w, const std::string & building_type, double turns_completed, double total_turns, double total_cost, double turn_spending)
Constructor for use when building is partially complete, to show progress bar.
References ClientUI::BuildingIcon(), BuildingType::Description(), GetBuildingType(), m_graphic, m_progress_bar, ClientUI::ResearchableTechFillColor(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), and UserString().
Member Function Documentation
CompleteConstruction()
void BuildingIndicator::CompleteConstruction () override
References INVALID_OBJECT_ID, m_building_id, m_graphic, m_progress_bar, and Refresh().
DoLayout()
void BuildingIndicator::DoLayout () private
References m_graphic, m_progress_bar, and m_scrap_indicator.
Referenced by Refresh(), and SizeMove().
EnableOrderIssuing()
void BuildingIndicator::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
References m_order_issuing_enabled.
MouseWheel()
void BuildingIndicator::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
PreRender()
void BuildingIndicator::PreRender () override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
References Refresh().
RClick()
void BuildingIndicator::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
References anonymous_namespace{BuildingsPanel.cpp}::ClientPlayerIsModerator(), ClientApp::EmpireID(), FlexibleFormat(), ObjectMap::get(), HumanClientApp::GetApp(), GetBuildingType(), ClientUI::GetClientUI(), ClientUI::GetMapWnd(), OrderSet::IssueOrder(), m_building_id, m_order_issuing_enabled, MAS_NoAction, Objects(), ClientApp::Orders(), anonymous_namespace{BuildingsPanel.cpp}::PendingScrapOrders(), OrderSet::RescindOrder(), RightClickedSignal, UserString(), and ClientUI::ZoomToBuildingType().
Refresh()
void BuildingIndicator::Refresh () private
References ClientUI::ArtDir(), ClientUI::BuildingIcon(), DoLayout(), Effect::Dump(), ObjectMap::get(), OptionsDB::Get(), GetBuildingType(), GetOptionsDB(), ClientUI::GetTexture(), m_building_id, m_graphic, m_scrap_indicator, METER_STEALTH, Objects(), and UserString().
Referenced by CompleteConstruction(), and PreRender().
Render()
void BuildingIndicator::Render () override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
References ALL_EMPIRES, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetOptionsDB(), GetUniverse(), INVALID_OBJECT_ID, m_building_id, s_scanline_shader, ScanlineRenderer::StartUsing(), ScanlineRenderer::StopUsing(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
SizeMove()
void BuildingIndicator::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Enables, or disables if enable is false, issuing orders via this BuildingIndicator.
References DoLayout().
Member Data Documentation
m_building_id
int BuildingIndicator::m_building_id private
Referenced by BuildingIndicator(), CompleteConstruction(), RClick(), Refresh(), and Render().
m_graphic
std::shared_ptr<GG::StaticGraphic> BuildingIndicator::m_graphic private
Referenced by BuildingIndicator(), CompleteConstruction(), DoLayout(), and Refresh().
m_order_issuing_enabled
bool BuildingIndicator::m_order_issuing_enabled = true private
Referenced by EnableOrderIssuing(), and RClick().
m_progress_bar
std::shared_ptr<MultiTurnProgressBar> BuildingIndicator::m_progress_bar private
Referenced by BuildingIndicator(), CompleteConstruction(), and DoLayout().
m_scrap_indicator
std::shared_ptr<GG::StaticGraphic> BuildingIndicator::m_scrap_indicator private
shown to indicate building was ordered scrapped
Referenced by DoLayout(), and Refresh().
RightClickedSignal
boost::signals2::signal<void (int)> BuildingIndicator::RightClickedSignal mutable
Referenced by RClick().
s_scanline_shader
ScanlineRenderer BuildingIndicator::s_scanline_shader static private
Referenced by BuildingsPanel::DoLayout(), and Render().
The documentation for this class was generated from the following files:
BuildingsPanel.h
BuildingsPanel.cpp