FreeOrion: Effect::Conditional Class Reference
Effect::Conditional Class Reference
#include <Effect.h>
Public Member Functions
Conditional (Condition::ConditionBase *target_condition, const std::vector< EffectBase * > &true_effects, const std::vector< EffectBase * > &false_effects)
std::string Dump () const override
void Execute (const ScriptingContext &context) const override
void Execute (const ScriptingContext &context, const TargetSet &targets) const override
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const override
bool IsAppearanceEffect () const override
bool IsConditionalEffect () const override
bool IsMeterEffect () const override
bool IsSitrepEffect () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual bool IsEmpireMeterEffect () const
Protected Member Functions
void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< EffectBase * > m_false_effects
Condition::ConditionBase * m_target_condition
std::vector< EffectBase * > m_true_effects
Friends
class boost::serialization::access
Detailed Description
Executes a set of effects if an execution-time condition is met, or an alterative set of effects if the condition is not met.
Constructor & Destructor Documentation
Effect::Conditional::Conditional (Condition::ConditionBase * target_condition, const std::vector< EffectBase * > & true_effects, const std::vector< EffectBase * > & false_effects)
Member Function Documentation
std::string Effect::Conditional::Dump () const override virtual
Implements Effect::EffectBase.
References Condition::ConditionBase::Dump(), DumpIndent(), g_indent, m_false_effects, m_target_condition, and m_true_effects.
void Effect::Conditional::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, Condition::ConditionBase::Eval(), m_false_effects, m_target_condition, and m_true_effects.
void Effect::Conditional::Execute (const ScriptingContext & context, const TargetSet & targets) const override virtual
Note: executes all of the true or all of the false effects on each target, without considering any of the only_* type flags.
Reimplemented from Effect::EffectBase.
References Condition::ConditionBase::Eval(), m_false_effects, m_target_condition, m_true_effects, and Condition::MATCHES.
void Effect::Conditional::Execute (const TargetsCauses & targets_causes, AccountingMap * accounting_map = nullptr, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const override virtual
Reimplemented from Effect::EffectBase.
References Condition::ConditionBase::Eval(), Effect::anonymous_namespace{Effect.cpp}::GetFilteredEffects(), GetUniverseObject(), m_false_effects, m_target_condition, m_true_effects, Condition::MATCHES, and ScriptingContext::source.
void Effect::Conditional::Execute (const ScriptingContext & context, const TargetSet & targets, AccountingMap * accounting_map = nullptr, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const protected
References Condition::ConditionBase::Eval(), Effect::anonymous_namespace{Effect.cpp}::GetFilteredEffects(), m_false_effects, m_target_condition, m_true_effects, and Condition::MATCHES.
bool Effect::Conditional::IsAppearanceEffect () const override virtual
Reimplemented from Effect::EffectBase.
References m_false_effects, and m_true_effects.
bool Effect::Conditional::IsConditionalEffect () const inline override virtual
Reimplemented from Effect::EffectBase.
bool Effect::Conditional::IsMeterEffect () const override virtual
Reimplemented from Effect::EffectBase.
References m_false_effects, and m_true_effects.
bool Effect::Conditional::IsSitrepEffect () const override virtual
Reimplemented from Effect::EffectBase.
References m_false_effects, and m_true_effects.
template<class Archive > void Effect::Conditional::serialize (Archive & ar, const unsigned int version) private
void Effect::Conditional::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_false_effects, m_target_condition, m_true_effects, and Condition::ConditionBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<EffectBase*> Effect::Conditional::m_false_effects private
Referenced by Dump(), Execute(), IsAppearanceEffect(), IsMeterEffect(), IsSitrepEffect(), and SetTopLevelContent().
Condition::ConditionBase* Effect::Conditional::m_target_condition private
Referenced by Dump(), Execute(), and SetTopLevelContent().
std::vector<EffectBase*> Effect::Conditional::m_true_effects private
Referenced by Dump(), Execute(), IsAppearanceEffect(), IsMeterEffect(), IsSitrepEffect(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp