FreeOrion: PartTypeManager Class Reference
PartTypeManager Class Reference
Holds FreeOrion ship part types.
#include <ShipDesign.h>
Public Types
using iterator = PartTypeMap::const_iterator
using PartTypeMap = std::map< std::string, std::unique_ptr< PartType > >
Public Member Functions
FO_COMMON_API void SetPartTypes (Pending::Pending< PartTypeMap > &&pending_part_types)
Sets part types to the future value of pending_part_types.
Private Member Functions
PartTypeManager ()
void CheckPendingPartTypes () const
Assigns any m_pending_part_types to m_bulding_types.
Private Attributes
std::map< std::string, std::unique_ptr< PartType > > m_parts
Set of part types.
boost::optional< Pending::Pending< PartTypeMap > > m_pending_part_types = boost::none
Future part type being parsed by parser.
Static Private Attributes
static PartTypeManager * s_instance = nullptr
Accessors
const PartType * GetPartType (const std::string &name) const
returns the part type with the name name; you should use the free function GetPartType() instead
iterator begin () const
iterator to the first part type
iterator end () const
iterator to the last + 1th part type
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
static PartTypeManager & GetPartTypeManager ()
returns the instance of this singleton class; you should use the free function GetPartTypeManager() instead
Detailed Description
Holds FreeOrion ship part types.
Member Typedef Documentation
iterator
using PartTypeManager::iterator = PartTypeMap::const_iterator
PartTypeMap
using PartTypeManager::PartTypeMap = std::map<std::string, std::unique_ptr<PartType> >
Constructor & Destructor Documentation
PartTypeManager()
PartTypeManager::PartTypeManager () private
Member Function Documentation
begin()
PartTypeManager::iterator PartTypeManager::begin () const
iterator to the first part type
CheckPendingPartTypes()
void PartTypeManager::CheckPendingPartTypes () const private
Assigns any m_pending_part_types to m_bulding_types.
References Pending::SwapPending(), and TraceLogger.
end()
PartTypeManager::iterator PartTypeManager::end () const
iterator to the last + 1th part type
GetCheckSum()
unsigned int PartTypeManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), and DebugLogger.
Referenced by CheckSumContent().
GetPartType()
const PartType * PartTypeManager::GetPartType (const std::string & name) const
returns the part type with the name name; you should use the free function GetPartType() instead
Referenced by ShipDesign::Defense(), and GetPartType().
GetPartTypeManager()
PartTypeManager & PartTypeManager::GetPartTypeManager () static
returns the instance of this singleton class; you should use the free function GetPartTypeManager() instead
Referenced by GetPartTypeManager().
SetPartTypes()
void PartTypeManager::SetPartTypes (Pending::Pending< PartTypeMap > && pending_part_types)
Sets part types to the future value of pending_part_types.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_parts
std::map<std::string, std::unique_ptr<PartType> > PartTypeManager::m_parts mutable private
Set of part types.
mutable so that when the parse completes it can be updated.
m_pending_part_types
boost::optional<Pending::Pending<PartTypeMap> > PartTypeManager::m_pending_part_types = boost::none mutable private
Future part type being parsed by parser.
mutable so that it can be assigned to m_part_types when completed.
s_instance
PartTypeManager * PartTypeManager::s_instance = nullptr static private
Referenced by CommonParams::~CommonParams().
The documentation for this class was generated from the following files:
ShipDesign.h
ShipDesign.cpp