FreeOrion: PythonCommon Class Reference
PythonCommon Class Reference
#include <PythonCommon.h>
Public Member Functions
PythonCommon ()
virtual ~PythonCommon ()
void Finalize ()
void HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
virtual bool InitCommonImports ()
bool Initialize ()
bool IsPythonRunning () const
IsPythonRunning returns true is the python interpreter is initialized.
Private Attributes
boost::python::object m_system_exit
Constructor & Destructor Documentation
PythonCommon()
PythonCommon::PythonCommon ()
~PythonCommon()
PythonCommon::~PythonCommon () virtual
References Finalize().
Member Function Documentation
Finalize()
void PythonCommon::Finalize ()
References ErrorLogger, and m_system_exit.
Referenced by PythonBase::Finalize(), HandleErrorAlreadySet(), and ~PythonCommon().
HandleErrorAlreadySet()
void PythonCommon::HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
If the error is SystemExit the python interpreter is finalized and no longer available.
Call PyErr_Print() if the exception is an error.
HandleErrorAlreadySet is idempotent, calling it multiple times won't crash or hang the process.
References ErrorLogger, Finalize(), and m_system_exit.
Referenced by PythonBase::ErrorReport(), ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), PythonAI::GenerateOrders(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), PythonBase::Initialize(), Initialize(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
InitCommonImports()
bool PythonCommon::InitCommonImports () virtual
Reimplemented in PythonBase.
Referenced by Initialize().
Initialize()
bool PythonCommon::Initialize ()
References DebugLogger, ErrorLogger, HandleErrorAlreadySet(), InitCommonImports(), and m_system_exit.
Referenced by GGHumanClientApp::GGHumanClientApp(), GGHumanClientApp::HandleResoureDirChange(), and PythonBase::Initialize().
IsPythonRunning()
bool PythonCommon::IsPythonRunning () const
IsPythonRunning returns true is the python interpreter is initialized.
It is typically called after HandleErrorAlreadySet() to determine if the error caused the interpreter to shutdown.
Referenced by ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), PythonAI::GenerateOrders(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), ServerApp::InitializePython(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), ServerApp::PushChatMessage(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), ServerApp::ServerApp(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
Member Data Documentation
m_system_exit
boost::python::object PythonCommon::m_system_exit private
Referenced by Finalize(), HandleErrorAlreadySet(), and Initialize().
The documentation for this class was generated from the following files:
PythonCommon.h
PythonCommon.cpp