FreeOrion: BasesListBox::AvailabilityManager Class Reference
BasesListBox::AvailabilityManager Class Reference
Public Member Functions
AvailabilityManager (bool obsolete, bool available, bool unavailable)
bool GetAvailability (const Availability::Enum type) const
void SetAvailability (const Availability::Enum type, const bool state)
void ToggleAvailability (const Availability::Enum type)
Private Attributes
std::tuple< bool, bool, bool > m_availabilities
Detailed Description
A class to allow the storage of availabilty in a common location to all the various BasesListBoxes.
Constructor & Destructor Documentation
BasesListBox::AvailabilityManager::AvailabilityManager (bool obsolete, bool available, bool unavailable)
Member Function Documentation
bool BasesListBox::AvailabilityManager::GetAvailability (const Availability::Enum type) const
References Availability::Available, Availability::Future, m_availabilities, and Availability::Obsolete.
Referenced by DesignWnd::BaseSelector::BaseSelector(), EmptyHullsListBox::PopulateCore(), CompletedDesignsListBox::PopulateCore(), SavedDesignsListBox::PopulateCore(), ToggleAvailability(), and DesignWnd::BaseSelector::ToggleAvailability().
void BasesListBox::AvailabilityManager::SetAvailability (const Availability::Enum type, const bool state)
References Availability::Available, Availability::Future, m_availabilities, and Availability::Obsolete.
Referenced by ToggleAvailability().
void BasesListBox::AvailabilityManager::ToggleAvailability (const Availability::Enum type)
References GetAvailability(), and SetAvailability().
Referenced by DesignWnd::BaseSelector::ToggleAvailability().
Member Data Documentation
std::tuple<bool, bool, bool> BasesListBox::AvailabilityManager::m_availabilities private
Referenced by GetAvailability(), and SetAvailability().
The documentation for this class was generated from the following file:
DesignWnd.cpp