FreeOrion: FreeOrionNode Class Reference
FreeOrionNode Class Reference
Node for GDNative library of FreeOrion Godot client.
#include <FreeOrionNode.h>
Public Member Functions
FreeOrionNode ()
~FreeOrionNode ()
void _init ()
Calls when Godot initializes Node.
Static Public Member Functions
static void _register_methods ()
Registers GDNative methods, properties and signals.
Private Member Functions
void _exit_tree ()
Calls when Godot remove Node from scene at finalization.
godot::String get_version () const
Returns FreeOrion version.
void HandleMessage (Message &&)
Process message in the networking thread.
void network_thread ()
Function called in a separate networking thread.
void new_single_player_game ()
Starts new single player game.
Private Attributes
std::unique_ptr< GodotClientApp > app
Detailed Description
Node for GDNative library of FreeOrion Godot client.
Constructor & Destructor Documentation
FreeOrionNode()
FreeOrionNode::FreeOrionNode ()
~FreeOrionNode()
FreeOrionNode::~FreeOrionNode ()
Member Function Documentation
_exit_tree()
void FreeOrionNode::_exit_tree () private
Calls when Godot remove Node from scene at finalization.
Should be used instead of destructor.
References app, quit(), and ShutdownLoggingSystemFileSink().
Referenced by _register_methods().
_init()
void FreeOrionNode::_init ()
Calls when Godot initializes Node.
Should be used instead of constructor.
References OptionsDB::Add(), app, tag_parser::args, CompleteXDGMigration(), DebugLogger, FreeOrionVersionString(), GetBinDir(), GetConfigPath(), GetOptionsDB(), GetPersistentConfigPath(), GetResourceDir(), InitDirs(), PathToString(), OptionsDB::Set(), OptionsDB::SetFromCommandLine(), OptionsDB::SetFromFile(), and UserStringNop.
_register_methods()
void FreeOrionNode::_register_methods () static
Registers GDNative methods, properties and signals.
References _exit_tree(), get_version(), network_thread(), and new_single_player_game().
get_version()
godot::String FreeOrionNode::get_version () const private
Returns FreeOrion version.
References FreeOrionVersionString().
Referenced by _register_methods().
HandleMessage()
void FreeOrionNode::HandleMessage (Message && msg) private
Process message in the networking thread.
References ALL_EMPIRES, app, DebugLogger, Empires(), ErrorLogger, ExtractAuthRequestMessageData(), ExtractErrorMessageData(), ExtractGameStartMessageData(), ExtractJoinAckMessageData(), ExtractPlayerStatusMessageData(), ExtractSetAuthorizationRolesMessage(), GetCombatLogManager(), GetGameRules(), GetSpeciesManager(), GetSupplyManager(), GetUniverse(), INVALID_GAME_TURN, Networking::INVALID_PLAYER_ID, Message::PlayerStatus, and GameRules::SetFromStrings().
Referenced by network_thread().
network_thread()
void FreeOrionNode::network_thread () private
Function called in a separate networking thread.
References app, HandleMessage(), and quit().
Referenced by _register_methods().
new_single_player_game()
void FreeOrionNode::new_single_player_game () private
Starts new single player game.
References app.
Referenced by _register_methods().
Member Data Documentation
app
std::unique_ptr<GodotClientApp> FreeOrionNode::app private
Referenced by _exit_tree(), _init(), HandleMessage(), network_thread(), and new_single_player_game().
The documentation for this class was generated from the following files:
FreeOrionNode.h
FreeOrionNode.cpp