FreeOrion: Process Class Reference
Process Class Reference
Encapsulates a spawned child process in a platform-independent manner.
#include <Process.h>
Classes
class Impl
Public Member Functions
Structors
Process ()
Creates a Process with no associated child process.
Process (const std::string &cmd, const std::vector< std::string > &argv)
Ctor requiring a command and a full argv-style command line.
Accessors
bool Empty () const
returns true if this is a default-constructed object with no associated process
bool HasLowPriority ()
true if process is set to low priority
Mutators
bool SetLowPriority (bool low)
sets process priority
void Kill ()
kills the controlled process immediately.
bool Terminate ()
terminate the controlled process and wait for finish.
void RequestTermination ()
kills the controlled process iff it has not been freed.
void Free ()
frees the controlled process from auto-deletion when this Process object is destroyed.
Private Attributes
bool m_empty = false
true iff this is a default-constructed Process (no associated process exists)
std::shared_ptr< Impl > m_impl
bool m_low_priority = false
true if this process is set to low priority
Detailed Description
Encapsulates a spawned child process in a platform-independent manner.
A Process object holds a shared_ptr to the data on the process it creates; therefore Process objects can be freely copied, with the same copy semantics as a shared_ptr. In addition, the created process is automatically killed when its owning Process object is destroyed, unless it is explicitly Free()d. Note that whether or not the process is explicitly Free()d, it may be explicitly Kill()ed at any time.
Currently, creating processes is supported on these operating systems:
Linux (this is the default): requires definition of FREEORION_LINUX
Win32 (use for MinGW apps as well): requires definition of FREEORION_WIN32 one of them must be used. Note that the Win32 version of Process calls TerminateProcess(), and so the killed process does minimal cleanup; in particular, it will not terminate any of its child processes and may not release DLLs it may be using.
Constructor & Destructor Documentation
Process() [1/2]
Process::Process ()
Creates a Process with no associated child process.
A child process will never be associated with this default-constructed Process unless another Process is assigned to it.
Process() [2/2]
Process::Process (const std::string & cmd, const std::vector< std::string > & argv)
Ctor requiring a command and a full argv-style command line.
The command may be a relative or an absolute path name. The first token on the command line must be the name of the executable of the process to be created.
Example: cmd: "/usr/bin/cvs", argv: "cvs update -C project_file.cpp".
Of course, each arg should be in its own string within argv, and argv strings containing spaces must be enclosed in quotes.
Exceptions
std::runtime_error If the process cannot be successfully created.
Process returns immediately.
Member Function Documentation
Empty()
bool Process::Empty () const inline
returns true if this is a default-constructed object with no associated process
Referenced by QuittingGame::react().
Free()
void Process::Free ()
frees the controlled process from auto-deletion when this Process object is destroyed.
References ErrorLogger, Process::Impl::Impl(), Process::Impl::Kill(), Kill(), m_impl, Process::Impl::SetLowPriority(), Process::Impl::Terminate(), and Process::Impl::~Impl().
Referenced by HumanClientApp::FreeServer(), QuittingGame::react(), and ShuttingDownServer::react().
HasLowPriority()
bool Process::HasLowPriority () inline
true if process is set to low priority
Kill()
void Process::Kill ()
kills the controlled process immediately.
References DebugLogger, m_empty, m_impl, m_low_priority, and RequestTermination().
Referenced by Free(), and Process::Impl::~Impl().
RequestTermination()
void Process::RequestTermination ()
kills the controlled process iff it has not been freed.
References m_empty, m_impl, and m_low_priority.
Referenced by Kill(), QuittingGame::react(), Terminate(), and HumanClientApp::~HumanClientApp().
SetLowPriority()
bool Process::SetLowPriority (bool low)
sets process priority
References m_empty, m_impl, and m_low_priority.
Terminate()
bool Process::Terminate ()
terminate the controlled process and wait for finish.
Return true if exit status was 0.
References DebugLogger, m_empty, m_impl, m_low_priority, and RequestTermination().
Member Data Documentation
m_empty
bool Process::m_empty = false private
true iff this is a default-constructed Process (no associated process exists)
Referenced by Kill(), RequestTermination(), SetLowPriority(), and Terminate().
m_impl
std::shared_ptr<Impl> Process::m_impl private
Referenced by Free(), Kill(), RequestTermination(), SetLowPriority(), and Terminate().
m_low_priority
bool Process::m_low_priority = false private
true if this process is set to low priority
Referenced by Kill(), RequestTermination(), SetLowPriority(), and Terminate().
The documentation for this class was generated from the following files:
Process.h
Process.cpp