FreeOrion: PolicyManager Class Reference
PolicyManager Class Reference
Keeps track of policies that can be chosen by empires.
#include <Government.h>
Public Types
using iterator = PoliciesTypeMap::const_iterator
using PoliciesTypeMap = std::map< std::string, std::unique_ptr< Policy > >
Public Member Functions
PolicyManager ()
~PolicyManager ()
iterator begin () const
iterator end () const
iterator to the first policy
unsigned int GetCheckSum () const
const Policy * GetPolicy (const std::string &name) const
returns the policy with the name name; you should use the free function GetPolicy() instead
std::set< std::string > PolicyCategories () const
std::vector< std::string > PolicyNames () const
std::vector< std::string > PolicyNames (const std::string &name) const
returns list of names of policies in specified category
void SetPolicies (Pending::Pending< PoliciesTypeMap > &&future)
iterator to the last + 1th policy
Private Member Functions
void CheckPendingPolicies () const
Private Attributes
boost::optional< Pending::Pending< PoliciesTypeMap > > m_pending_types = boost::none
Assigns any m_pending_types to m_specials.
PoliciesTypeMap m_policies
Detailed Description
Keeps track of policies that can be chosen by empires.
Member Typedef Documentation
iterator
using PolicyManager::iterator = PoliciesTypeMap::const_iterator
PoliciesTypeMap
using PolicyManager::PoliciesTypeMap = std::map<std::string, std::unique_ptr<Policy> >
Constructor & Destructor Documentation
PolicyManager()
PolicyManager::PolicyManager ()
~PolicyManager()
PolicyManager::~PolicyManager ()
Member Function Documentation
begin()
PolicyManager::iterator PolicyManager::begin () const
CheckPendingPolicies()
void PolicyManager::CheckPendingPolicies () const private
References Pending::SwapPending().
end()
PolicyManager::iterator PolicyManager::end () const
iterator to the first policy
GetCheckSum()
unsigned int PolicyManager::GetCheckSum () const
References CheckSums::CheckSumCombine(), and DebugLogger.
GetPolicy()
const Policy * PolicyManager::GetPolicy (const std::string & name) const
returns the policy with the name name; you should use the free function GetPolicy() instead
Referenced by GetPolicy(), and ClientUI::PolicyIcon().
PolicyCategories()
std::set< std::string > PolicyManager::PolicyCategories () const
Referenced by PoliciesListBox::ShowAllCategories(), and FreeOrionPython::WrapEmpire().
PolicyNames() [1/2]
std::vector< std::string > PolicyManager::PolicyNames () const
Referenced by FreeOrionPython::WrapEmpire().
PolicyNames() [2/2]
std::vector< std::string > PolicyManager::PolicyNames (const std::string & name) const
returns list of names of policies in specified category
SetPolicies()
void PolicyManager::SetPolicies (Pending::Pending< PoliciesTypeMap > && future)
iterator to the last + 1th policy
sets types to the value of future
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_pending_types
boost::optional<Pending::Pending<PoliciesTypeMap> > PolicyManager::m_pending_types = boost::none mutable private
Assigns any m_pending_types to m_specials.
Future types being parsed by parser. mutable so that it can be assigned to m_species_types when completed.
m_policies
PoliciesTypeMap PolicyManager::m_policies mutable private
The documentation for this class was generated from the following files:
Government.h
Government.cpp