FreeOrion: ShipHullManager Class Reference
ShipHullManager Class Reference
Holds FreeOrion hull types.
#include <ShipHull.h>
Public Types
using container_type = std::map< std::string, std::unique_ptr< ShipHull > >
using iterator = container_type::const_iterator
Public Member Functions
auto begin () const -> iterator
iterator to the first hull type
auto end () const -> iterator
iterator to the last + 1th hull type
auto GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
auto GetShipHull (const std::string &name) const -> const ShipHull *
Returns the hull type with the name name; you should use the free function GetShipHull() instead.
FO_COMMON_API void SetShipHulls (Pending::Pending< container_type > &&pending_ship_hulls)
Sets hull types to the future value of pending_ship_hulls.
auto size () const -> std::size_t
How many hulls are known?
Static Public Member Functions
static auto GetShipHullManager () -> ShipHullManager &
Returns the instance of this singleton class; you should use the free function GetShipHullManager() instead.
Private Member Functions
ShipHullManager ()
void CheckPendingShipHulls () const
Assigns any m_pending_ship_hulls to m_bulding_types.
Private Attributes
container_type m_hulls
Set of hull types.
boost::optional< Pending::Pending< container_type > > m_pending_ship_hulls = boost::none
Future hull type being parsed by parser.
Static Private Attributes
static ShipHullManager * s_instance = nullptr
Detailed Description
Holds FreeOrion hull types.
Member Typedef Documentation
container_type
using ShipHullManager::container_type = std::map<std::string, std::unique_ptr<ShipHull> >
iterator
using ShipHullManager::iterator = container_type::const_iterator
Constructor & Destructor Documentation
ShipHullManager()
ShipHullManager::ShipHullManager () private
References s_instance.
Member Function Documentation
begin()
ShipHullManager::iterator ShipHullManager::begin () const -> iterator
iterator to the first hull type
References CheckPendingShipHulls(), and m_hulls.
Referenced by ShipDesign::MaybeInvalidDesign().
CheckPendingShipHulls()
void ShipHullManager::CheckPendingShipHulls () const private
Assigns any m_pending_ship_hulls to m_bulding_types.
References ErrorLogger, m_hulls, m_pending_ship_hulls, Pending::SwapPending(), and TraceLogger.
Referenced by begin(), end(), GetCheckSum(), GetShipHull(), and size().
end()
ShipHullManager::iterator ShipHullManager::end () const -> iterator
iterator to the last + 1th hull type
References CheckPendingShipHulls(), and m_hulls.
GetCheckSum()
unsigned int ShipHullManager::GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckPendingShipHulls(), CheckSums::CheckSumCombine(), DebugLogger, and m_hulls.
Referenced by CheckSumContent().
GetShipHull()
const ShipHull * ShipHullManager::GetShipHull (const std::string & name) const -> const ShipHull*
Returns the hull type with the name name; you should use the free function GetShipHull() instead.
References CheckPendingShipHulls(), and m_hulls.
Referenced by ShipDesign::MaybeInvalidDesign(), ShipDesign::Parts(), and EmptyHullsListBox::PopulateCore().
GetShipHullManager()
ShipHullManager & ShipHullManager::GetShipHullManager () -> ShipHullManager& static
Returns the instance of this singleton class; you should use the free function GetShipHullManager() instead.
Referenced by GetShipHull(), and GetShipHullManager().
SetShipHulls()
void ShipHullManager::SetShipHulls (Pending::Pending< container_type > && pending_ship_hulls)
Sets hull types to the future value of pending_ship_hulls.
References m_pending_ship_hulls.
Referenced by IApp::StartBackgroundParsing().
size()
std::size_t ShipHullManager::size () const -> std::size_t
How many hulls are known?
References CheckPendingShipHulls(), and m_hulls.
Referenced by EmptyHullsListBox::PopulateCore().
Member Data Documentation
m_hulls
container_type ShipHullManager::m_hulls mutable private
Set of hull types.
Referenced by begin(), CheckPendingShipHulls(), end(), GetCheckSum(), GetShipHull(), and size().
m_pending_ship_hulls
boost::optional<Pending::Pending<container_type> > ShipHullManager::m_pending_ship_hulls = boost::none mutable private
Future hull type being parsed by parser.
Referenced by CheckPendingShipHulls(), and SetShipHulls().
s_instance
ShipHullManager * ShipHullManager::s_instance = nullptr static private
Referenced by anonymous_namespace{ShipHull.cpp}::IncreaseMeter(), and ShipHullManager().
The documentation for this class was generated from the following files:
ShipHull.h
ShipHull.cpp