FreeOrion: Effect::SetOverlayTexture Class Reference
Effect::SetOverlayTexture Class Reference
#include <Effect.h>
Public Member Functions
SetOverlayTexture (const std::string &texture, ValueRef::ValueRefBase< double > *size)
virtual ~SetOverlayTexture ()
std::string Dump () const override
void Execute (const ScriptingContext &context) const override
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const override
unsigned int GetCheckSum () const override
bool IsAppearanceEffect () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< double > * m_size
std::string m_texture
Friends
class boost::serialization::access
Detailed Description
Applies an overlay texture to Systems.
Constructor & Destructor Documentation
Effect::SetOverlayTexture::SetOverlayTexture (const std::string & texture, ValueRef::ValueRefBase< double > * size)
Effect::SetOverlayTexture::~SetOverlayTexture () virtual
References m_size.
Member Function Documentation
std::string Effect::SetOverlayTexture::Dump () const override virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_size, and m_texture.
void Effect::SetOverlayTexture::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ValueRef::ValueRefBase< T >::Eval(), m_size, and m_texture.
void Effect::SetOverlayTexture::Execute (const TargetsCauses & targets_causes, AccountingMap * accounting_map = nullptr, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const override virtual
Reimplemented from Effect::EffectBase.
References Effect::EffectBase::Execute(), GetUniverseObject(), and ScriptingContext::source.
unsigned int Effect::SetOverlayTexture::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_size, m_texture, and TraceLogger.
bool Effect::SetOverlayTexture::IsAppearanceEffect () const inline override virtual
Reimplemented from Effect::EffectBase.
template<class Archive > void Effect::SetOverlayTexture::serialize (Archive & ar, const unsigned int version) private
void Effect::SetOverlayTexture::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_size, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<double>* Effect::SetOverlayTexture::m_size private
Referenced by Dump(), Execute(), GetCheckSum(), SetTopLevelContent(), and ~SetOverlayTexture().
std::string Effect::SetOverlayTexture::m_texture private
Referenced by Dump(), Execute(), and GetCheckSum().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp