FreeOrion: HullTypeManager Class Reference
HullTypeManager Class Reference
Holds FreeOrion hull types.
#include <ShipPartHull.h>
Public Types
using HullTypeMap = std::map< std::string, std::unique_ptr< HullType > >
using iterator = HullTypeMap::const_iterator
Public Member Functions
FO_COMMON_API void SetHullTypes (Pending::Pending< HullTypeMap > &&pending_hull_types)
Sets hull types to the future value of pending_hull_types.
Private Member Functions
HullTypeManager ()
void CheckPendingHullTypes () const
Assigns any m_pending_hull_types to m_bulding_types.
Private Attributes
HullTypeMap m_hulls
Set of hull types.
boost::optional< Pending::Pending< HullTypeMap > > m_pending_hull_types = boost::none
Future hull type being parsed by parser.
Static Private Attributes
static HullTypeManager * s_instance = nullptr
Accessors
const HullType * GetHullType (const std::string &name) const
returns the hull type with the name name; you should use the free function GetHullType() instead
iterator begin () const
iterator to the first hull type
iterator end () const
iterator to the last + 1th hull type
std::size_t size () const
how many hulls are known?
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
static HullTypeManager & GetHullTypeManager ()
returns the instance of this singleton class; you should use the free function GetHullTypeManager() instead
Detailed Description
Holds FreeOrion hull types.
Member Typedef Documentation
HullTypeMap
using HullTypeManager::HullTypeMap = std::map<std::string, std::unique_ptr<HullType> >
iterator
using HullTypeManager::iterator = HullTypeMap::const_iterator
Constructor & Destructor Documentation
HullTypeManager()
HullTypeManager::HullTypeManager () private
Member Function Documentation
begin()
HullTypeManager::iterator HullTypeManager::begin () const
iterator to the first hull type
Referenced by ShipDesign::MaybeInvalidDesign().
CheckPendingHullTypes()
void HullTypeManager::CheckPendingHullTypes () const private
Assigns any m_pending_hull_types to m_bulding_types.
References ErrorLogger, Pending::SwapPending(), and TraceLogger.
end()
HullTypeManager::iterator HullTypeManager::end () const
iterator to the last + 1th hull type
GetCheckSum()
unsigned int HullTypeManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), and DebugLogger.
Referenced by CheckSumContent().
GetHullType()
const HullType * HullTypeManager::GetHullType (const std::string & name) const
returns the hull type with the name name; you should use the free function GetHullType() instead
Referenced by GetHullType(), ShipDesign::MaybeInvalidDesign(), ShipDesign::Parts(), and EmptyHullsListBox::PopulateCore().
GetHullTypeManager()
HullTypeManager & HullTypeManager::GetHullTypeManager () static
returns the instance of this singleton class; you should use the free function GetHullTypeManager() instead
Referenced by GetHullTypeManager().
SetHullTypes()
void HullTypeManager::SetHullTypes (Pending::Pending< HullTypeMap > && pending_hull_types)
Sets hull types to the future value of pending_hull_types.
Referenced by IApp::StartBackgroundParsing().
size()
std::size_t HullTypeManager::size () const
how many hulls are known?
Referenced by EmptyHullsListBox::PopulateCore().
Member Data Documentation
m_hulls
HullTypeMap HullTypeManager::m_hulls mutable private
Set of hull types.
mutable so that when the parse completes it can be updated.
m_pending_hull_types
boost::optional<Pending::Pending<HullTypeMap> > HullTypeManager::m_pending_hull_types = boost::none mutable private
Future hull type being parsed by parser.
mutable so that it can be assigned to m_hull_types when completed.
s_instance
HullTypeManager * HullTypeManager::s_instance = nullptr static private
Referenced by HullType::GetCheckSum().
The documentation for this class was generated from the following files:
ShipPartHull.h
ShipDesign.cpp