FreeOrion: ShipDesignOrder Class Reference
ShipDesignOrder Class Reference
The Order subclass that represents manipulating an empire's ship designs.
#include <Order.h>
Public Member Functions
ShipDesignOrder (int empire, int existing_design_id_to_remember)
ShipDesignOrder (int empire, int design_id_to_erase, bool dummy)
ShipDesignOrder (int empire, const ShipDesign &ship_design)
ShipDesignOrder (int empire, int existing_design_id, const std::string &new_name, const std::string &new_description="")
int DesignID () const
std::string Dump () const override
Public Member Functions inherited from Order
Order ()
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Private Member Functions
ShipDesignOrder ()
void ExecuteImpl () const override
Preconditions of execute:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_3D_model
bool m_create_new_design = false
bool m_delete_design_from_empire = false
std::string m_description
int m_design_id = INVALID_DESIGN_ID
m_design_id is mutable to save the id for the server when the client calls ExecuteImpl.
int m_designed_on_turn = 0
std::string m_hull
std::string m_icon
bool m_is_monster = false
std::string m_name
bool m_name_desc_in_stringtable = false
std::vector< std::string > m_parts
bool m_update_name_or_description = false
boost::uuids::uuid m_uuid
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
The Order subclass that represents manipulating an empire's ship designs.
The 2-arg ctor adds the existing ship design to the empire's set of designs - remembering, or "keeping" the design and enabling the empire to produce ships of that design (if all design prerequisites are met) The 3-arg ctor taking a bool removes the indicated design from the empire's set of remembered designs. The 3-arg ctor taking a ShipDesign argument creates a new shipdesign in the universe's catalog of shipdesigns with the passed new design id, and adds this design to the empire's set of remembered designs. The new design must be marked as designed by this empire.
Constructor & Destructor Documentation
ShipDesignOrder() [1/5]
ShipDesignOrder::ShipDesignOrder (int empire, int existing_design_id_to_remember)
ShipDesignOrder() [2/5]
ShipDesignOrder::ShipDesignOrder (int empire, int design_id_to_erase, bool dummy)
ShipDesignOrder() [3/5]
ShipDesignOrder::ShipDesignOrder (int empire, const ShipDesign & ship_design)
ShipDesignOrder() [4/5]
ShipDesignOrder::ShipDesignOrder (int empire, int existing_design_id, const std::string & new_name, const std::string & new_description = "")
ShipDesignOrder() [5/5]
ShipDesignOrder::ShipDesignOrder () private
Member Function Documentation
DesignID()
int ShipDesignOrder::DesignID () const inline
References Order::ExecuteImpl().
Dump()
std::string ShipDesignOrder::Dump () const override virtual
Reimplemented from Order.
References UserString().
ExecuteImpl()
void ShipDesignOrder::ExecuteImpl () const override private virtual
Preconditions of execute:
For creating a new design, the passed design is a valid reference to a design created by the empire issuing the order
For remembering an existing ship design, there exists a ship design with the passed id, and the empire is aware of this ship design
For removing a shipdesign from the empire's set of designs, there empire has a design with the passed id in its set of designs
Postconditions:
For creating a new ship design, the universe will contain a new ship design, and the creating empire will have the new design as of of its designs
For remembering a ship design, the empire will have the design's id in its set of design ids
For removing a design, the empire will no longer have the design's id in its set of design ids
Implements Order.
References DebugLogger, ShipDesign::DesignedByEmpire(), Order::EmpireID(), Universe::EmpireKnownShipDesignIDs(), ErrorLogger, GetShipDesign(), Universe::GetShipDesign(), GetUniverse(), Order::GetValidatedEmpire(), ShipDesign::ID(), Universe::InsertShipDesign(), Universe::InsertShipDesignID(), INVALID_DESIGN_ID, m_3D_model, m_create_new_design, m_delete_design_from_empire, m_description, m_design_id, m_designed_on_turn, m_hull, m_icon, m_is_monster, m_name, m_name_desc_in_stringtable, m_parts, m_update_name_or_description, m_uuid, Universe::RenameShipDesign(), and Universe::SetEmpireKnowledgeOfShipDesign().
serialize()
template<typename Archive > void ShipDesignOrder::serialize (Archive & ar, const unsigned int version) private
References RenameOrder::m_name, and to_string().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_3D_model
std::string ShipDesignOrder::m_3D_model private
Referenced by ExecuteImpl().
m_create_new_design
bool ShipDesignOrder::m_create_new_design = false private
Referenced by ExecuteImpl().
m_delete_design_from_empire
bool ShipDesignOrder::m_delete_design_from_empire = false private
Referenced by ExecuteImpl().
m_description
std::string ShipDesignOrder::m_description private
Referenced by ExecuteImpl().
m_design_id
int ShipDesignOrder::m_design_id = INVALID_DESIGN_ID mutable private
m_design_id is mutable to save the id for the server when the client calls ExecuteImpl.
Referenced by ExecuteImpl().
m_designed_on_turn
int ShipDesignOrder::m_designed_on_turn = 0 private
Referenced by ExecuteImpl().
m_hull
std::string ShipDesignOrder::m_hull private
Referenced by ExecuteImpl().
m_icon
std::string ShipDesignOrder::m_icon private
Referenced by ExecuteImpl().
m_is_monster
bool ShipDesignOrder::m_is_monster = false private
Referenced by ExecuteImpl().
m_name
std::string ShipDesignOrder::m_name private
Referenced by ExecuteImpl().
m_name_desc_in_stringtable
bool ShipDesignOrder::m_name_desc_in_stringtable = false private
Referenced by ExecuteImpl().
m_parts
std::vector<std::string> ShipDesignOrder::m_parts private
Referenced by ExecuteImpl().
m_update_name_or_description
bool ShipDesignOrder::m_update_name_or_description = false private
Referenced by ExecuteImpl().
m_uuid
boost::uuids::uuid ShipDesignOrder::m_uuid private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp