FreeOrion: Effect::SetSpeciesEmpireOpinion Class Reference
Effect::SetSpeciesEmpireOpinion Class Reference
#include <Effect.h>
Public Member Functions
SetSpeciesEmpireOpinion (ValueRef::ValueRefBase< std::string > *species_name, ValueRef::ValueRefBase< int > *empire_id, ValueRef::ValueRefBase< double > *opinion)
virtual ~SetSpeciesEmpireOpinion ()
std::string Dump () const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< int > * m_empire_id
ValueRef::ValueRefBase< double > * m_opinion
ValueRef::ValueRefBase< std::string > * m_species_name
Friends
class boost::serialization::access
Detailed Description
Sets the opinion of Species species for empire with id empire_id to opinion
Constructor & Destructor Documentation
Effect::SetSpeciesEmpireOpinion::SetSpeciesEmpireOpinion (ValueRef::ValueRefBase< std::string > * species_name, ValueRef::ValueRefBase< int > * empire_id, ValueRef::ValueRefBase< double > * opinion)
Effect::SetSpeciesEmpireOpinion::~SetSpeciesEmpireOpinion () virtual
References m_empire_id, m_opinion, and m_species_name.
Member Function Documentation
std::string Effect::SetSpeciesEmpireOpinion::Dump () const override virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_empire_id.
void Effect::SetSpeciesEmpireOpinion::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ALL_EMPIRES, ScriptingContext::effect_target, ValueRef::ValueRefBase< T >::Eval(), GetSpeciesManager(), m_empire_id, m_opinion, m_species_name, SpeciesManager::SetSpeciesEmpireOpinion(), and SpeciesManager::SpeciesEmpireOpinion().
unsigned int Effect::SetSpeciesEmpireOpinion::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_empire_id, m_opinion, m_species_name, and TraceLogger.
template<class Archive > void Effect::SetSpeciesEmpireOpinion::serialize (Archive & ar, const unsigned int version) private
void Effect::SetSpeciesEmpireOpinion::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_empire_id, m_opinion, m_species_name, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<int>* Effect::SetSpeciesEmpireOpinion::m_empire_id private
Referenced by Dump(), Execute(), GetCheckSum(), SetTopLevelContent(), and ~SetSpeciesEmpireOpinion().
ValueRef::ValueRefBase<double>* Effect::SetSpeciesEmpireOpinion::m_opinion private
Referenced by Execute(), GetCheckSum(), SetTopLevelContent(), and ~SetSpeciesEmpireOpinion().
ValueRef::ValueRefBase<std::string>* Effect::SetSpeciesEmpireOpinion::m_species_name private
Referenced by Execute(), GetCheckSum(), SetTopLevelContent(), and ~SetSpeciesEmpireOpinion().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp