FreeOrion: anonymous_namespace{ProductionWnd.cpp}::QuantitySelector Class Reference
anonymous_namespace{ProductionWnd.cpp}::QuantitySelector Class Reference
Public Attributes
boost::signals2::signal< void(int, int)> QuantChangedSignal
Structors
const ProductionQueue::Element elem
int quantity
int prevQuant
int blocksize
int prevBlocksize
bool amBlockType
bool amOn
GG::Y h
QuantitySelector (const ProductionQueue::Element &build, GG::X xoffset, GG::Y yoffset, GG::Y h, bool inProgress, GG::X nwidth, bool amBlockType)
void SelectionChanged (GG::DropDownList::iterator it)
void LosingFocus () override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Additional Inherited Members
Public Member Functions inherited from CUIDropDownList
GG::Pt ClientLowerRight () const override
GG::X DroppedRowWidth () const override
CUIDropDownList (size_t num_shown_elements)
void Render () override
disables rendering of the small downward-facing arrow on the right of the control
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseLeave () override
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Constructor & Destructor Documentation
anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::QuantitySelector (const ProductionQueue::Element & build, GG::X xoffset, GG::Y yoffset, GG::Y h, bool inProgress, GG::X nwidth, bool amBlockType) inline
References ProductionQueue::Element::blocksize, ProductionQueue::ProductionItem::design_id, ProductionQueue::Element::item, ProductionQueue::Element::remaining, ClientUI::ResearchableTechFillColor(), and ClientUI::ResearchableTechTextAndBorderColor().
Member Function Documentation
void anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override private
void anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override private
void anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::LosingFocus () inline override private
void anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::SelectionChanged (GG::DropDownList::iterator it) inline
References DebugLogger.
Member Data Documentation
bool anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::amBlockType private
bool anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::amOn private
int anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::blocksize private
const ProductionQueue::Element anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::elem private
GG::Y anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::h private
int anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::prevBlocksize private
int anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::prevQuant private
boost::signals2::signal<void (int, int)> anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::QuantChangedSignal mutable
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Init().
int anonymous_namespace{ProductionWnd.cpp}::QuantitySelector::quantity private
The documentation for this class was generated from the following file:
ProductionWnd.cpp