FreeOrion: Species Class Reference
Species Class Reference
A predefined type of population that can exist on a PopulationCenter.
#include <Species.h>
Public Member Functions
Structors
Species (const SpeciesStrings &strings, const std::vector< FocusType > &foci, const std::string &preferred_focus, const std::map< PlanetType, PlanetEnvironment > &planet_environments, std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, std::unique_ptr< Condition::Condition > &&combat_targets, const SpeciesParams &params, const std::set< std::string > &tags, const std::string &graphic)
~Species ()
Accessors
const std::string & Name () const
returns the unique name for this type of species
const std::string & Description () const
returns a text description of this type of species
std::string GameplayDescription () const
returns a text description of this type of species
const std::set< int > & Homeworlds () const
returns the ids of objects that are homeworlds for this species
const std::map< int, double > & EmpireOpinions () const
returns the positive/negative opinions of this species about empires
const std::map< std::string, double > & OtherSpeciesOpinions () const
returns the positive/negative opinions of this species about other species
const Condition::Condition * Location () const
returns the condition determining what planets on which this species may spawn
const Condition::Condition * CombatTargets () const
returns the condition for possible targets. may be nullptr if no condition was specified.
std::string Dump (unsigned short ntabs=0) const
returns a data file format representation of this object
const std::vector< FocusType > & Foci () const
returns the focus types this species can use
const std::string & PreferredFocus () const
returns the name of the planetary focus this species prefers. Default for new colonies and may affect happiness if on a different focus?
const std::map< PlanetType, PlanetEnvironment > & PlanetEnvironments () const
returns a map from PlanetType to the PlanetEnvironment this Species has on that PlanetType
PlanetEnvironment GetPlanetEnvironment (PlanetType planet_type) const
returns the PlanetEnvironment this species has on PlanetType planet_type
PlanetType NextBetterPlanetType (PlanetType initial_planet_type) const
returns the next better PlanetType for this species from the initial_planet_type specified
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
Returns the EffectsGroups that encapsulate the effects that species of this type have.
bool Playable () const
returns whether this species is a suitable starting species for players
bool Native () const
returns whether this species is a suitable native species (for non player-controlled planets)
bool CanColonize () const
returns whether this species can colonize planets
bool CanProduceShips () const
returns whether this species can produce ships
const std::set< std::string > & Tags () const
returns the unique name for this type of species
const std::string & Graphic () const
returns the name of the grapic file for this species
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Mutators
void AddHomeworld (int homeworld_id)
void RemoveHomeworld (int homeworld_id)
void SetHomeworlds (const std::set< int > &homeworld_ids)
void SetEmpireOpinions (const std::map< int, double > &opinions)
void SetEmpireOpinion (int empire_id, double opinion)
void SetOtherSpeciesOpinions (const std::map< std::string, double > &opinions)
void SetOtherSpeciesOpinion (const std::string &species_name, double opinion)
Private Member Functions
void Init ()
Private Attributes
bool m_can_colonize
bool m_can_produce_ships
std::unique_ptr< Condition::Condition > m_combat_targets
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::map< int, double > m_empire_opinions
std::vector< FocusType > m_foci
std::string m_gameplay_description
std::string m_graphic
std::set< int > m_homeworlds
std::unique_ptr< Condition::Condition > m_location
std::string m_name
bool m_native
std::map< std::string, double > m_other_species_opinions
std::map< PlanetType, PlanetEnvironment > m_planet_environments
bool m_playable
std::string m_preferred_focus
std::set< std::string > m_tags
Detailed Description
A predefined type of population that can exist on a PopulationCenter.
Species have associated sets of EffectsGroups, and various other properties that affect how the object on which they reside functions. Each kind of Species must have a unique name string, by which it can be looked up using GetSpecies().
Constructor & Destructor Documentation
Species()
Species::Species (const SpeciesStrings & strings, const std::vector< FocusType > & foci, const std::string & preferred_focus, const std::map< PlanetType, PlanetEnvironment > & planet_environments, std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, std::unique_ptr< Condition::Condition > && combat_targets, const SpeciesParams & params, const std::set< std::string > & tags, const std::string & graphic)
References Init(), m_effects, and m_tags.
~Species()
Species::~Species ()
Member Function Documentation
AddHomeworld()
void Species::AddHomeworld (int homeworld_id)
References DebugLogger, m_homeworlds, and Objects().
Referenced by SetEmpireHomeworld(), and anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld().
CanColonize()
bool Species::CanColonize () const inline
returns whether this species can colonize planets
Referenced by Ship::CanColonize(), ShipDesign::ProductionLocation(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), anonymous_namespace{ServerWrapper.cpp}::SpeciesCanColonize(), and FreeOrionPython::WrapUniverseClasses().
CanProduceShips()
bool Species::CanProduceShips () const inline
returns whether this species can produce ships
Referenced by ShipDesign::ProductionLocation(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and FreeOrionPython::WrapUniverseClasses().
CombatTargets()
const Condition::Condition* Species::CombatTargets () const inline
returns the condition for possible targets. may be nullptr if no condition was specified.
References Effect::Dump().
Referenced by anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition().
Description()
const std::string& Species::Description () const inline
returns a text description of this type of species
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and FreeOrionPython::WrapUniverseClasses().
Dump()
std::string Species::Dump (unsigned short ntabs = 0) const
returns a data file format representation of this object
References DumpIndent(), m_can_colonize, m_can_produce_ships, m_combat_targets, m_description, m_effects, m_foci, m_gameplay_description, m_graphic, m_name, m_native, m_planet_environments, m_playable, anonymous_namespace{Species.cpp}::PlanetEnvironmentToString(), and anonymous_namespace{Species.cpp}::PlanetTypeToString().
Referenced by Init(), and FreeOrionPython::WrapUniverseClasses().
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& Species::Effects () const inline
Returns the EffectsGroups that encapsulate the effects that species of this type have.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag().
EmpireOpinions()
const std::map<int, double>& Species::EmpireOpinions () const inline
returns the positive/negative opinions of this species about empires
Foci()
const std::vector<FocusType>& Species::Foci () const inline
returns the focus types this species can use
Referenced by anonymous_namespace{UniverseWrapper.cpp}::SpeciesFoci().
GameplayDescription()
std::string Species::GameplayDescription () const
returns a text description of this type of species
References tag_parser::description, m_effects, m_gameplay_description, and UserString().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow().
GetCheckSum()
unsigned int Species::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_can_colonize, m_can_produce_ships, m_combat_targets, m_description, m_effects, m_foci, m_gameplay_description, m_graphic, m_location, m_name, m_native, m_planet_environments, m_playable, m_preferred_focus, m_tags, and SpeciesManager::s_instance.
GetPlanetEnvironment()
PlanetEnvironment Species::GetPlanetEnvironment (PlanetType planet_type) const
returns the PlanetEnvironment this species has on PlanetType planet_type
References m_planet_environments.
Referenced by AutomaticallyChosenColonyShip(), Planet::EnvironmentForSpecies(), NextBetterPlanetType(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment(), and FreeOrionPython::WrapUniverseClasses().
Graphic()
const std::string& Species::Graphic () const inline
returns the name of the grapic file for this species
Referenced by ClientUI::SpeciesIcon().
Homeworlds()
const std::set<int>& Species::Homeworlds () const inline
returns the ids of objects that are homeworlds for this species
Referenced by SpeciesManager::GetSpeciesHomeworldsMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and FreeOrionPython::WrapUniverseClasses().
Init()
void Species::Init () private
References Dump(), m_combat_targets, m_effects, m_location, m_name, and TraceLogger.
Referenced by Species().
Location()
const Condition::Condition* Species::Location () const inline
returns the condition determining what planets on which this species may spawn
Name()
const std::string& Species::Name () const inline
returns the unique name for this type of species
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), EncyclopediaDetailPanel::SetItem(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow(), and FreeOrionPython::WrapUniverseClasses().
Native()
bool Species::Native () const inline
returns whether this species is a suitable native species (for non player-controlled planets)
NextBetterPlanetType()
PlanetType Species::NextBetterPlanetType (PlanetType initial_planet_type) const
returns the next better PlanetType for this species from the initial_planet_type specified
References GetPlanetEnvironment(), m_planet_environments, anonymous_namespace{Species.cpp}::RingNextPlanetType(), and anonymous_namespace{Species.cpp}::RingPreviousPlanetType().
Referenced by Planet::NextBetterPlanetTypeForSpecies().
OtherSpeciesOpinions()
const std::map<std::string, double>& Species::OtherSpeciesOpinions () const inline
returns the positive/negative opinions of this species about other species
PlanetEnvironments()
const std::map<PlanetType, PlanetEnvironment>& Species::PlanetEnvironments () const inline
returns a map from PlanetType to the PlanetEnvironment this Species has on that PlanetType
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and SetEmpireHomeworld().
Playable()
bool Species::Playable () const inline
returns whether this species is a suitable starting species for players
PreferredFocus()
const std::string& Species::PreferredFocus () const inline
returns the name of the planetary focus this species prefers. Default for new colonies and may affect happiness if on a different focus?
Referenced by Planet::Colonize(), ValueRef::Variable< ToType >::Eval(), Effect::SetSpecies::Execute(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{ServerWrapper.cpp}::SpeciesPreferredFocus(), and FreeOrionPython::WrapUniverseClasses().
RemoveHomeworld()
void Species::RemoveHomeworld (int homeworld_id)
References DebugLogger, and m_homeworlds.
Referenced by anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld().
SetEmpireOpinion()
void Species::SetEmpireOpinion (int empire_id, double opinion)
SetEmpireOpinions()
void Species::SetEmpireOpinions (const std::map< int, double > & opinions)
SetHomeworlds()
void Species::SetHomeworlds (const std::set< int > & homeworld_ids)
References m_homeworlds.
Referenced by SpeciesManager::SetSpeciesHomeworlds().
SetOtherSpeciesOpinion()
void Species::SetOtherSpeciesOpinion (const std::string & species_name, double opinion)
SetOtherSpeciesOpinions()
void Species::SetOtherSpeciesOpinions (const std::map< std::string, double > & opinions)
Tags()
const std::set<std::string>& Species::Tags () const inline
returns the unique name for this type of species
Referenced by Planet::HasTag(), Ship::HasTag(), Planet::Tags(), and FreeOrionPython::WrapUniverseClasses().
Member Data Documentation
m_can_colonize
bool Species::m_can_colonize private
Referenced by Dump(), and GetCheckSum().
m_can_produce_ships
bool Species::m_can_produce_ships private
Referenced by Dump(), and GetCheckSum().
m_combat_targets
std::unique_ptr<Condition::Condition> Species::m_combat_targets private
Referenced by Dump(), GetCheckSum(), and Init().
m_description
std::string Species::m_description private
Referenced by Dump(), and GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > Species::m_effects private
Referenced by Dump(), GameplayDescription(), GetCheckSum(), Init(), and Species().
m_empire_opinions
std::map<int, double> Species::m_empire_opinions private
m_foci
std::vector<FocusType> Species::m_foci private
Referenced by Dump(), and GetCheckSum().
m_gameplay_description
std::string Species::m_gameplay_description private
Referenced by Dump(), GameplayDescription(), and GetCheckSum().
m_graphic
std::string Species::m_graphic private
Referenced by Dump(), and GetCheckSum().
m_homeworlds
std::set<int> Species::m_homeworlds private
Referenced by AddHomeworld(), RemoveHomeworld(), and SetHomeworlds().
m_location
std::unique_ptr<Condition::Condition> Species::m_location private
Referenced by GetCheckSum(), and Init().
m_name
std::string Species::m_name private
Referenced by Dump(), GetCheckSum(), and Init().
m_native
bool Species::m_native private
Referenced by Dump(), and GetCheckSum().
m_other_species_opinions
std::map<std::string, double> Species::m_other_species_opinions private
m_planet_environments
std::map<PlanetType, PlanetEnvironment> Species::m_planet_environments private
Referenced by Dump(), GetCheckSum(), GetPlanetEnvironment(), and NextBetterPlanetType().
m_playable
bool Species::m_playable private
Referenced by Dump(), and GetCheckSum().
m_preferred_focus
std::string Species::m_preferred_focus private
Referenced by GetCheckSum().
m_tags
std::set<std::string> Species::m_tags private
Referenced by GetCheckSum(), and Species().
The documentation for this class was generated from the following files:
Species.h
Species.cpp