FreeOrion: OrderSet Class Reference
OrderSet Class Reference
A collection of orders that may be searched using arbitrary predicate functions and functors.
#include <OrderSet.h>
Public Types
typedef OrderMap::const_iterator const_iterator
typedef OrderMap::difference_type difference_type
typedef OrderMap::iterator iterator
typedef OrderMap::key_compare key_compare
typedef OrderMap::key_type key_type
typedef OrderMap::size_type size_type
typedef OrderMap::value_type value_type
Public Member Functions
Accessors
const_iterator begin () const
returns the begin const_iterator for the OrderSet
const_iterator end () const
returns the end const_iterator for the OrderSet
iterator begin ()
returns the begin const_iterator for the OrderSet
iterator end ()
returns the end const_iterator for the OrderSet
std::size_t size () const
returns the begin const_iterator for the OrderSet
bool empty () const
returns the begin const_iterator for the OrderSet
iterator find (const key_type &k)
returns the begin const_iterator for the OrderSet
std::pair< iterator, bool > insert (const value_type &val)
direct insert without saving changes
void erase (const key_type &k)
direct erase without saving changes
OrderPtr & operator[] (std::size_t i)
returns the begin const_iterator for the OrderSet
key_compare key_comp () const
returns the begin const_iterator for the OrderSet
Mutators
int IssueOrder (const OrderPtr &order)
Execute the order immediately on the client.
int IssueOrder (OrderPtr &&order)
Execute the order immediately on the client.
void ApplyOrders ()
Applies all Orders in the OrderSet.
bool RescindOrder (int order)
Try to Undo() order and if it succeeds remove the order from the set.
void Reset ()
clears all orders; should be called at the beginning of a new turn
std::pair< OrderSet, std::set< int > > ExtractChanges ()
extract and clear changed orders
Private Types
typedef std::map< int, OrderPtr > OrderMap
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::set< int > m_last_added_orders
set of ids added/updated orders
std::set< int > m_last_deleted_orders
set of ids deleted orders
OrderMap m_orders
Friends
class boost::serialization::access
Detailed Description
A collection of orders that may be searched using arbitrary predicate functions and functors.
An OrderSet is typically composed on the client with IssueOrder(order), and then sent to the server to be executed again. IssueOrder(order) immediately executes the order to change the client's backend state. The second execution on the server changes the server game state. Orders only executed on the client do not change the server save game state.
On game reload, reloaded orders need to be re-executed on the client because the client state start from the last saved server state. Orders are saved/serialized as unexecuted so that when they are loaded they can be mixed with newly issued orders and both the loaded and newly issued orders will only execute once.
RescindOrder(order) will try Order::Undo() and if that succeeds remove the order from the set.
Member Typedef Documentation
const_iterator
typedef OrderMap::const_iterator OrderSet::const_iterator
difference_type
typedef OrderMap::difference_type OrderSet::difference_type
iterator
typedef OrderMap::iterator OrderSet::iterator
key_compare
typedef OrderMap::key_compare OrderSet::key_compare
key_type
typedef OrderMap::key_type OrderSet::key_type
OrderMap
typedef std::map<int, OrderPtr> OrderSet::OrderMap private
size_type
typedef OrderMap::size_type OrderSet::size_type
value_type
typedef OrderMap::value_type OrderSet::value_type
Member Function Documentation
ApplyOrders()
void OrderSet::ApplyOrders ()
Applies all Orders in the OrderSet.
As of this writing, this is needed only after deserializing an OrderSet client-side during game loading.
References DebugLogger, and ErrorLogger.
Referenced by AIClientApp::HandleMessage(), and MapWnd::InitTurn().
begin() [1/2]
const_iterator OrderSet::begin () const inline
returns the begin const_iterator for the OrderSet
begin() [2/2]
iterator OrderSet::begin () inline
returns the begin const_iterator for the OrderSet
empty()
bool OrderSet::empty () const inline
returns the begin const_iterator for the OrderSet
end() [1/2]
const_iterator OrderSet::end () const inline
returns the end const_iterator for the OrderSet
end() [2/2]
iterator OrderSet::end () inline
returns the end const_iterator for the OrderSet
erase()
void OrderSet::erase (const key_type & k) inline
direct erase without saving changes
ExtractChanges()
std::pair< OrderSet, std::set< int > > OrderSet::ExtractChanges ()
extract and clear changed orders
References find(), and m_orders.
Referenced by ClientApp::SendPartialOrders().
find()
iterator OrderSet::find (const key_type & k) inline
returns the begin const_iterator for the OrderSet
Referenced by ExtractChanges().
insert()
std::pair<iterator,bool> OrderSet::insert (const value_type & val) inline
direct insert without saving changes
IssueOrder() [1/2]
int OrderSet::IssueOrder (const OrderPtr & order)
Execute the order immediately on the client.
Store the order in the OrderSet to be executed later on the server. Return an index that can be used to reference the order.
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), ProductionWnd::AddBuildToQueueSlot(), DesignWnd::MainPanel::AddDesign(), anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), ResearchWnd::AddTechsToQueueSlot(), CompletedDesignsListBox::BaseRightClicked(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{DesignWnd.cpp}::DeleteFromDisplayedDesigns(), ResearchWnd::DeleteQueueItem(), ProductionWnd::DeleteQueueItem(), FleetWnd::FleetRightClicked(), MapWnd::ForgetObject(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueTechOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueBuildingProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueShipProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueTechOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetExploreOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetResupplyOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), MapWnd::PlotFleetMovement(), ProductionWnd::QueueItemDuped(), ResearchWnd::QueueItemMoved(), ProductionWnd::QueueItemMoved(), ResearchWnd::QueueItemPaused(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), DesignWnd::MainPanel::ReplaceDesign(), SidePanel::PlanetPanel::SetFocus(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), FleetDetailPanel::ShipRightClicked(), ShipDesignManager::StartGame(), and FleetDataPanel::ToggleAggression().
IssueOrder() [2/2]
int OrderSet::IssueOrder (OrderPtr && order)
Execute the order immediately on the client.
Store the order in the OrderSet to be executed later on the server. Return an index that can be used to reference the order.
References TraceLogger.
key_comp()
key_compare OrderSet::key_comp () const inline
returns the begin const_iterator for the OrderSet
operator[]()
OrderPtr & OrderSet::operator[] (std::size_t i)
returns the begin const_iterator for the OrderSet
References anonymous_namespace{OrderSet.cpp}::EMPTY_ORDER_PTR.
RescindOrder()
bool OrderSet::RescindOrder (int order)
Try to Undo() order and if it succeeds remove the order from the set.
Return true if order exists and was successfully removed.
Referenced by anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), FleetWnd::FleetRightClicked(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), and FleetDetailPanel::ShipRightClicked().
Reset()
void OrderSet::Reset ()
clears all orders; should be called at the beginning of a new turn
Referenced by AIClientApp::HandleMessage(), and HumanClientApp::ResetClientData().
serialize()
template<class Archive > void OrderSet::serialize (Archive & ar, const unsigned int version) private
size()
std::size_t OrderSet::size () const inline
returns the begin const_iterator for the OrderSet
Referenced by FreeOrionPython::WrapAI().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_last_added_orders
std::set<int> OrderSet::m_last_added_orders private
set of ids added/updated orders
m_last_deleted_orders
std::set<int> OrderSet::m_last_deleted_orders private
set of ids deleted orders
m_orders
OrderMap OrderSet::m_orders private
Referenced by ServerApp::AddPlayerIntoGame(), and ExtractChanges().
The documentation for this class was generated from the following files:
OrderSet.h
OrderSet.cpp