FreeOrion: GraphicalSummaryWnd Class Reference
GraphicalSummaryWnd Class Reference
Shows a graphical summary of the battle results.
#include <GraphicalSummary.h>
Public Member Functions
GraphicalSummaryWnd ()
~GraphicalSummaryWnd ()
void DoLayout ()
Position and sizes things appropriately.
GG::Pt MinUsableSize () const override
Get the minimum size of this window required to show all of its children.
void Render () override
void SetLog (int log_id)
Sets the log to show.
Public Attributes
boost::signals2::signal< void()> MinSizeChangedSignal
Private Member Functions
void DeleteSideBars ()
void GenerateGraph ()
void HandleButtonChanged ()
void MakeSummaries (int log_id)
Private Attributes
std::shared_ptr< OptionsBar > m_options_bar
std::vector< std::shared_ptr< SideBar > > m_side_boxes
std::unique_ptr< BarSizer > m_sizer
std::map< int, CombatSummary > m_summaries
Detailed Description
Shows a graphical summary of the battle results.
Constructor & Destructor Documentation
GraphicalSummaryWnd()
GraphicalSummaryWnd::GraphicalSummaryWnd ()
~GraphicalSummaryWnd()
GraphicalSummaryWnd::~GraphicalSummaryWnd ()
Member Function Documentation
DeleteSideBars()
void GraphicalSummaryWnd::DeleteSideBars () private
References m_side_boxes.
Referenced by GenerateGraph().
DoLayout()
void GraphicalSummaryWnd::DoLayout ()
Position and sizes things appropriately.
References m_options_bar, m_side_boxes, m_sizer, anonymous_namespace{GraphicalSummary.cpp}::OPTION_BAR_HEIGHT(), and anonymous_namespace{GraphicalSummary.cpp}::SIDE_BOX_MARGIN().
Referenced by GenerateGraph(), and HandleButtonChanged().
GenerateGraph()
void GraphicalSummaryWnd::GenerateGraph () private
References DebugLogger, DeleteSideBars(), DoLayout(), anonymous_namespace{GraphicalSummary.cpp}::EPSILON, HandleButtonChanged(), m_options_bar, m_side_boxes, m_sizer, m_summaries, and MinSizeChangedSignal.
Referenced by MakeSummaries().
HandleButtonChanged()
void GraphicalSummaryWnd::HandleButtonChanged () private
References DoLayout(), and MinSizeChangedSignal.
Referenced by GenerateGraph().
MakeSummaries()
void GraphicalSummaryWnd::MakeSummaries (int log_id) private
References DebugLogger, ErrorLogger, GenerateGraph(), GetCombatLog(), GetUniverseObject(), and m_summaries.
Referenced by SetLog().
MinUsableSize()
GG::Pt GraphicalSummaryWnd::MinUsableSize () const override
Get the minimum size of this window required to show all of its children.
References m_options_bar, and m_sizer.
Render()
void GraphicalSummaryWnd::Render () override
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
SetLog()
void GraphicalSummaryWnd::SetLog (int log_id)
Sets the log to show.
References MakeSummaries().
Member Data Documentation
m_options_bar
std::shared_ptr<OptionsBar> GraphicalSummaryWnd::m_options_bar private
Referenced by DoLayout(), GenerateGraph(), and MinUsableSize().
m_side_boxes
std::vector<std::shared_ptr<SideBar> > GraphicalSummaryWnd::m_side_boxes private
Referenced by DeleteSideBars(), DoLayout(), and GenerateGraph().
m_sizer
std::unique_ptr<BarSizer> GraphicalSummaryWnd::m_sizer private
Referenced by DoLayout(), GenerateGraph(), and MinUsableSize().
m_summaries
std::map<int, CombatSummary> GraphicalSummaryWnd::m_summaries private
Referenced by GenerateGraph(), and MakeSummaries().
MinSizeChangedSignal
boost::signals2::signal<void()> GraphicalSummaryWnd::MinSizeChangedSignal
Referenced by GenerateGraph(), and HandleButtonChanged().
The documentation for this class was generated from the following files:
GraphicalSummary.h
GraphicalSummary.cpp