FreeOrion: anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel Class Reference
anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel Class Reference
A section used in initial forces and destroyed forces, displays empire's name and forces count; and can be expanded to enumerate all forces of this empire that take part in the combat.
Public Member Functions
EmpireForcesAccordionPanel (GG::X w, CombatLogWnd::Impl &log_, int viewing_empire_id_, int empire_id, std::vector< std::vector< std::shared_ptr< UniverseObject >>> forces_)
~EmpireForcesAccordionPanel ()
void CompleteConstruction () override
Public Member Functions inherited from AccordionPanel
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
void SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Member Functions
void ToggleExpansion ()
Static Private Member Functions
static size_t CountForces (std::vector< std::vector< std::shared_ptr< UniverseObject >>> forces)
Private Attributes
std::shared_ptr< LinkText > details
std::vector< std::vector< std::shared_ptr< UniverseObject > > > forces
CombatLogWnd::Impl & log
std::shared_ptr< LinkText > title
const int viewing_empire_id = ALL_EMPIRES
Static Private Attributes
static constexpr unsigned int BORDER_MARGIN = 5
Additional Inherited Members
Public Types inherited from AccordionPanel
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Public Attributes inherited from AccordionPanel
ExpandCollapseSignalType ExpandCollapseSignal
Protected Member Functions inherited from AccordionPanel
virtual void DoLayout ()
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Protected Attributes inherited from AccordionPanel
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin = 1
The number of pixels between the expansion button and the client area.
bool m_collapsed = true
std::shared_ptr< GG::Button > m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
GG::Clr m_interior_color
bool m_is_left = false
Is expand button on the left?
Detailed Description
A section used in initial forces and destroyed forces, displays empire's name and forces count; and can be expanded to enumerate all forces of this empire that take part in the combat.
Constructor & Destructor Documentation
EmpireForcesAccordionPanel()
anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::EmpireForcesAccordionPanel (GG::X w, CombatLogWnd::Impl & log_, int viewing_empire_id_, int empire_id, std::vector< std::vector< std::shared_ptr< UniverseObject >>> forces_)
~EmpireForcesAccordionPanel()
anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::~EmpireForcesAccordionPanel ()
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction () override
References BORDER_MARGIN, AccordionPanel::CompleteConstruction(), ClientUI::CtrlColor(), AccordionPanel::ExpandCollapseSignal, CombatLogWnd::Impl::HandleWndChanged(), log, AccordionPanel::m_expand_button, AccordionPanel::SetBorderMargin(), AccordionPanel::SetCollapsed(), AccordionPanel::SetInteriorColor(), title, and ToggleExpansion().
CountForces()
size_t anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CountForces (std::vector< std::vector< std::shared_ptr< UniverseObject >>> forces) static private
References forces.
ToggleExpansion()
void anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::ToggleExpansion () private
References CombatLogWnd::Impl::DecorateLinkText(), forces, anonymous_namespace{CombatLogWnd.cpp}::ForcesToText(), AccordionPanel::IsCollapsed(), log, AccordionPanel::SetCollapsed(), and viewing_empire_id.
Referenced by CompleteConstruction().
Member Data Documentation
BORDER_MARGIN
constexpr unsigned int anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::BORDER_MARGIN = 5 static private
Referenced by CompleteConstruction().
details
std::shared_ptr<LinkText> anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::details private
forces
std::vector<std::vector<std::shared_ptr<UniverseObject> > > anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::forces private
Referenced by CountForces(), and ToggleExpansion().
log
CombatLogWnd::Impl& anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::log private
Referenced by CompleteConstruction(), and ToggleExpansion().
title
std::shared_ptr<LinkText> anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::title private
Referenced by CompleteConstruction().
viewing_empire_id
const int anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::viewing_empire_id = ALL_EMPIRES private
Referenced by ToggleExpansion().
The documentation for this class was generated from the following file:
CombatLogWnd.cpp