FreeOrion: PolicyOrder Class Reference
PolicyOrder Class Reference
the Order subclass that represents the adoptiong imperial polices.
#include <Order.h>
Public Member Functions
PolicyOrder (int empire, const std::string &name, const std::string &category, bool adopt, int slot=-1)
bool Adopt () const
const std::string & CategoryName () const
std::string Dump () const override
const std::string & PolicyName () const
Returns ID of fleet selected in this order.
int Slot () const
Public Member Functions inherited from Order
Order ()=default
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()=default
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Private Member Functions
PolicyOrder ()=default
void ExecuteImpl () const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_adopt = false
std::string m_category
std::string m_policy_name
int m_slot = -1
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents the adoptiong imperial polices.
Constructor & Destructor Documentation
PolicyOrder() [1/2]
PolicyOrder::PolicyOrder (int empire, const std::string & name, const std::string & category, bool adopt, int slot = -1)
PolicyOrder() [2/2]
PolicyOrder::PolicyOrder () private default
Member Function Documentation
Adopt()
bool PolicyOrder::Adopt () const inline
CategoryName()
const std::string& PolicyOrder::CategoryName () const inline
Dump()
std::string PolicyOrder::Dump () const override virtual
Reimplemented from Order.
References m_adopt, and UserString().
ExecuteImpl()
void PolicyOrder::ExecuteImpl () const override private virtual
Implements Order.
References DebugLogger, Order::GetValidatedEmpire(), m_adopt, m_category, m_policy_name, m_slot, and Objects().
PolicyName()
const std::string& PolicyOrder::PolicyName () const inline
Returns ID of fleet selected in this order.
serialize()
template<typename Archive > void PolicyOrder::serialize (Archive & ar, const unsigned int version) private
Slot()
int PolicyOrder::Slot () const inline
References Order::ExecuteImpl().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_adopt
bool PolicyOrder::m_adopt = false private
Referenced by Dump(), and ExecuteImpl().
m_category
std::string PolicyOrder::m_category private
Referenced by ExecuteImpl().
m_policy_name
std::string PolicyOrder::m_policy_name private
Referenced by ExecuteImpl().
m_slot
int PolicyOrder::m_slot = -1 private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp