FreeOrion: Moderator::AddStarlane Class Reference
Moderator::AddStarlane Class Reference
#include <ModeratorAction.h>
Public Member Functions
AddStarlane ()
AddStarlane (int system_1_id, int system_2_id)
std::string Dump () const override
void Execute () const override
Public Member Functions inherited from Moderator::ModeratorAction
ModeratorAction ()=default
virtual ~ModeratorAction ()=default
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_id_1 = INVALID_OBJECT_ID
int m_id_2 = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Constructor & Destructor Documentation
AddStarlane() [1/2]
Moderator::AddStarlane::AddStarlane ()
AddStarlane() [2/2]
Moderator::AddStarlane::AddStarlane (int system_1_id, int system_2_id)
Member Function Documentation
Dump()
std::string Moderator::AddStarlane::Dump () const override virtual
Reimplemented from Moderator::ModeratorAction.
References m_id_1, m_id_2, and to_string().
Execute()
void Moderator::AddStarlane::Execute () const override virtual
Reimplemented from Moderator::ModeratorAction.
References ErrorLogger, ObjectMap::get(), m_id_1, m_id_2, and Objects().
serialize()
template<typename Archive > template void Moderator::AddStarlane::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_id_1
int Moderator::AddStarlane::m_id_1 = INVALID_OBJECT_ID private
Referenced by Dump(), and Execute().
m_id_2
int Moderator::AddStarlane::m_id_2 = INVALID_OBJECT_ID private
Referenced by Dump(), and Execute().
The documentation for this class was generated from the following files:
ModeratorAction.h
ModeratorAction.cpp
SerializeModeratorAction.cpp