FreeOrion: Effect::CreateShip Class Reference
Effect::CreateShip Class Reference final
Creates a new Ship with specified predefined_ship_design_name design from those in the list of PredefinedShipDesignManager, and owned by the empire with the specified empire_id.
#include <Effects.h>
Public Member Functions
CreateShip (std::unique_ptr< ValueRef::ValueRef< std::string >> &&predefined_ship_design_name, std::unique_ptr< ValueRef::ValueRef< int >> &&empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> &&species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> &&ship_name, std::vector< std::unique_ptr< Effect >> &&effects_to_apply_after)
CreateShip (std::unique_ptr< ValueRef::ValueRef< int >> &&ship_design_id, std::unique_ptr< ValueRef::ValueRef< int >> &&empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> &&species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> &&ship_name, std::vector< std::unique_ptr< Effect >> &&effects_to_apply_after)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
virtual void Execute (ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_design_id
std::unique_ptr< ValueRef::ValueRef< std::string > > m_design_name
std::vector< std::unique_ptr< Effect > > m_effects_to_apply_after
std::unique_ptr< ValueRef::ValueRef< int > > m_empire_id
std::unique_ptr< ValueRef::ValueRef< std::string > > m_name
std::unique_ptr< ValueRef::ValueRef< std::string > > m_species_name
Friends
class boost::serialization::access
Detailed Description
Creates a new Ship with specified predefined_ship_design_name design from those in the list of PredefinedShipDesignManager, and owned by the empire with the specified empire_id.
Constructor & Destructor Documentation
CreateShip() [1/2]
Effect::CreateShip::CreateShip (std::unique_ptr< ValueRef::ValueRef< std::string >> && predefined_ship_design_name, std::unique_ptr< ValueRef::ValueRef< int >> && empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> && species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> && ship_name, std::vector< std::unique_ptr< Effect >> && effects_to_apply_after)
CreateShip() [2/2]
Effect::CreateShip::CreateShip (std::unique_ptr< ValueRef::ValueRef< int >> && ship_design_id, std::unique_ptr< ValueRef::ValueRef< int >> && empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> && species_name, std::unique_ptr< ValueRef::ValueRef< std::string >> && ship_name, std::vector< std::unique_ptr< Effect >> && effects_to_apply_after)
Member Function Documentation
Dump()
std::string Effect::CreateShip::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent(), m_design_id, m_design_name, m_empire_id, m_name, and m_species_name.
Execute()
void Effect::CreateShip::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References ALL_EMPIRES, ScriptingContext::ContextObjects(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), ScriptingContext::effect_target, ErrorLogger, ObjectMap::get(), GetEmpire(), GetPredefinedShipDesign(), GetShipDesign(), GetSpecies(), GetUniverse(), ShipDesign::ID(), Universe::InsertNew(), INVALID_DESIGN_ID, m_design_id, m_design_name, m_effects_to_apply_after, m_empire_id, m_name, m_species_name, NewMonsterName(), Empire::NewShipName(), Universe::SetEmpireKnowledgeOfShipDesign(), UserString(), and UserStringExists().
GetCheckSum()
unsigned int Effect::CreateShip::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), m_design_id, m_design_name, m_effects_to_apply_after, m_empire_id, m_name, m_species_name, and TraceLogger.
serialize()
template<typename Archive > void Effect::CreateShip::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::CreateShip::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::Effect.
References m_design_id, m_design_name, m_effects_to_apply_after, m_empire_id, m_name, and m_species_name.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_design_id
std::unique_ptr<ValueRef::ValueRef<int> > Effect::CreateShip::m_design_id private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_design_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::CreateShip::m_design_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_effects_to_apply_after
std::vector<std::unique_ptr<Effect> > Effect::CreateShip::m_effects_to_apply_after private
Referenced by Execute(), GetCheckSum(), and SetTopLevelContent().
m_empire_id
std::unique_ptr<ValueRef::ValueRef<int> > Effect::CreateShip::m_empire_id private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::CreateShip::m_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_species_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::CreateShip::m_species_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp