FreeOrion: LinkText Class Reference
LinkText Class Reference
#include <LinkText.h>
Public Member Functions
Structors
LinkText (GG::X x, GG::Y y, GG::X w, const std::string &str, const std::shared_ptr< GG::Font > &font, GG::Flags< GG::TextFormat > format=GG::FORMAT_NONE, GG::Clr color=GG::CLR_BLACK)
ctor taking a font directly
LinkText (GG::X x, GG::Y y, const std::string &str, const std::shared_ptr< GG::Font > &font, GG::Clr color=GG::CLR_BLACK)
Accessors
GG::Pt TextUpperLeft () const override
GG::Pt TextLowerRight () const override
const std::vector< GG::Font::LineData > & GetLineData () const override
const std::shared_ptr< GG::Font > & GetFont () const override
const std::string & RawText () const override
Mutators
void Render () override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseLeave () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void SetText (const std::string &str) override
Public Member Functions inherited from TextLinker
void SetDecorator (const std::string &link_type, LinkDecorator *decorator)
link clicked signals: first string is the link type, second string is the specific item clicked
TextLinker ()
virtual ~TextLinker ()
Private Member Functions
void SetLinkedText (const std::string &str) override
Private Attributes
std::string m_raw_text
Additional Inherited Members
Public Attributes inherited from TextLinker
boost::signals2::signal< void(const std::string &, const std::string &)> LinkClickedSignal
boost::signals2::signal< void(const std::string &, const std::string &)> LinkDoubleClickedSignal
boost::signals2::signal< void(const std::string &, const std::string &)> LinkRightClickedSignal
Static Public Attributes inherited from TextLinker
static const std::string BROWSE_PATH_TAG
static const std::string ENCYCLOPEDIA_TAG
static const std::string GRAPH_TAG
static const std::string URL_TAG
Protected Member Functions inherited from TextLinker
void FindLinks ()
finds the links in the text, with which to populate m_links.
int GetLinkUnderPt (const GG::Pt &pt)
returns the index of the link under screen coordinate pt, or -1 if none
void LClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LDoubleClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LocateLinks ()
calculates the physical locations of the links in m_links
void MarkLinks ()
wraps text for each link in text formatting tags so that the links appear visually distinct from other text
void MouseHere_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void MouseLeave_ ()
void RClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void Render_ ()
Detailed Description
Allows text that the user sees to emit signals when clicked, and indicates to the user visually which text represents a link. There is one type of signal for each type of ZoomTo*() method in ClientUI. This allows any text that refers to game elements to be tagged as such and clicked by the user, with the appropriate ClientUI response function called. The followig tags are currently supported:
* <planet ID>
* <system ID>
* <fleet ID>
* <ship ID>
* <building ID>
* <empire ID>
* <tech [string]>
* <buildingtype [string]>
* <special [string]>
* <shiphull [string]>
* <shippart [string]>
* <species [string]>
* <encyclopedia [string]>
The ID parameters refer to the UniverseObjects that should be zoomed to for each link. Encyclopedia entries and content items are referred to by strings.
Note that for link tags to be correctly handled, they must not overlap each other at all, even though overlap with regular GG::Font tags is fine.
Constructor & Destructor Documentation
LinkText::LinkText (GG::X x, GG::Y y, GG::X w, const std::string & str, const std::shared_ptr< GG::Font > & font, GG::Flags< GG::TextFormat > format = GG::FORMAT_NONE, GG::Clr color = GG::CLR_BLACK)
ctor taking a font directly
References TextLinker::FindLinks(), TextLinker::MarkLinks(), TextLowerRight(), and TextUpperLeft().
LinkText::LinkText (GG::X x, GG::Y y, const std::string & str, const std::shared_ptr< GG::Font > & font, GG::Clr color = GG::CLR_BLACK)
ctor that does not require window size. Window size is determined from the string and font; the window will be large enough to fit the text as rendered, and no larger.
See also
DynamicText::DynamicText()
References TextLinker::FindLinks(), and TextLinker::MarkLinks().
Member Function Documentation
const std::shared_ptr< GG::Font > & LinkText::GetFont () const override virtual
Returns text displayed before link formatting is added.
Implements TextLinker.
const std::vector< GG::Font::LineData > & LinkText::GetLineData () const override virtual
Returns text displayed before link formatting is added.
Implements TextLinker.
void LinkText::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::LClick_().
void LinkText::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::MouseHere_().
void LinkText::MouseLeave () override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::MouseLeave_().
const std::string & LinkText::RawText () const override virtual
Returns text displayed before link formatting is added.
Implements TextLinker.
References m_raw_text.
void LinkText::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::GetLinkUnderPt(), TextLinker::RClick_(), and UserString().
Referenced by anonymous_namespace{SitRepPanel.cpp}::SitRepLinkText::RClick().
void LinkText::Render () override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::Render_().
void LinkText::SetLinkedText (const std::string & str) override private virtual
Implements TextLinker.
void LinkText::SetText (const std::string & str) override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::FindLinks(), m_raw_text, and TextLinker::MarkLinks().
void LinkText::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::LocateLinks().
Referenced by anonymous_namespace{CombatLogWnd.cpp}::LazyScrollerLinkText::SizeMove().
GG::Pt LinkText::TextLowerRight () const override virtual
Returns text displayed before link formatting is added.
Implements TextLinker.
Referenced by LinkText().
GG::Pt LinkText::TextUpperLeft () const override virtual
Returns text displayed before link formatting is added.
Implements TextLinker.
Referenced by LinkText().
Member Data Documentation
std::string LinkText::m_raw_text private
Referenced by RawText(), and SetText().
The documentation for this class was generated from the following files:
LinkText.h
LinkText.cpp