FreeOrion: ClientNetworking::Impl Class Reference
ClientNetworking::Impl Class Reference
Public Types
using ServerList = std::vector< std::pair< boost::asio::ip::address, std::string > >
The type of list returned by a call to DiscoverLANServers().
Public Member Functions
Structors
Impl ()
Accessors
bool IsConnected () const
Returns true iff the client is full duplex connected to the server.
bool IsRxConnected () const
Returns true iff the client is connected to receive from the server.
bool IsTxConnected () const
Returns true iff the client is connected to send to the server.
int PlayerID () const
Returns the ID of the player on this client.
int HostPlayerID () const
Returns the ID of the host player, or INVALID_PLAYER_ID if there is no host player.
bool PlayerIsHost (int player_id) const
Returns whether the indicated player ID is the host.
bool HasAuthRole (Networking::RoleType role) const
Checks if the client has some authorization role.
const std::string & Destination () const
Returns destination address of server.
Mutators
ClientNetworking::ServerNames DiscoverLANServerNames ()
Returns a list of the addresses and names of all servers on the Local Area Network.
bool ConnectToServer (const ClientNetworking *const self, const std::string &ip_address, const std::chrono::milliseconds &timeout=std::chrono::seconds(10), bool expect_timeout=false)
Connects to the server at ip_address.
bool ConnectToLocalHostServer (const ClientNetworking *const self, const std::chrono::milliseconds &timeout=std::chrono::seconds(10), bool expect_timeout=false)
Connects to the server on the client's host.
void SendMessage (const Message &message)
Sends message to the server.
boost::optional< Message > GetMessage ()
Return the next incoming message from the server if available or boost::none.
void DisconnectFromServer ()
Disconnects the client from the server.
void SetPlayerID (int player_id)
Sets player ID for this client.
void SetHostPlayerID (int host_player_id)
Sets Host player ID.
Networking::AuthRoles & AuthorizationRoles ()
Get authorization roles access.
Private Member Functions
void AsyncReadMessage (const std::shared_ptr< const ClientNetworking > &keep_alive)
void AsyncWriteMessage ()
void DisconnectFromServerImpl ()
void HandleConnection (boost::asio::ip::tcp::resolver::iterator *it, const boost::system::error_code &error)
void HandleException (const boost::system::system_error &error)
void HandleMessageBodyRead (const std::shared_ptr< const ClientNetworking > &keep_alive, boost::system::error_code error, std::size_t bytes_transferred)
void HandleMessageHeaderRead (const std::shared_ptr< const ClientNetworking > &keep_alive, boost::system::error_code error, std::size_t bytes_transferred)
void HandleMessageWrite (boost::system::error_code error, std::size_t bytes_transferred)
void NetworkingThread (const std::shared_ptr< const ClientNetworking > self)
void SendMessageImpl (Message message)
Private Attributes
std::string m_destination
int m_host_player_id
Message::HeaderBuffer m_incoming_header
Message m_incoming_message
MessageQueue m_incoming_messages
boost::asio::io_context m_io_context
boost::mutex m_mutex
Message::HeaderBuffer m_outgoing_header
std::list< Message > m_outgoing_messages
int m_player_id
Networking::AuthRoles m_roles
bool m_rx_connected
boost::asio::ip::tcp::socket m_socket
bool m_tx_connected
Member Typedef Documentation
ServerList
using ClientNetworking::Impl::ServerList = std::vector<std::pair<boost::asio::ip::address, std::string> >
The type of list returned by a call to DiscoverLANServers().
Constructor & Destructor Documentation
Impl()
ClientNetworking::Impl::Impl ()
Member Function Documentation
AsyncReadMessage()
void ClientNetworking::Impl::AsyncReadMessage (const std::shared_ptr< const ClientNetworking > & keep_alive) private
References DisconnectFromServerImpl(), HandleMessageHeaderRead(), m_incoming_header, and m_socket.
Referenced by HandleMessageBodyRead(), and NetworkingThread().
AsyncWriteMessage()
void ClientNetworking::Impl::AsyncWriteMessage () private
References ErrorLogger, HandleMessageWrite(), HeaderToBuffer(), m_outgoing_header, m_outgoing_messages, and m_socket.
Referenced by HandleMessageWrite(), NetworkingThread(), and SendMessageImpl().
AuthorizationRoles()
Networking::AuthRoles & ClientNetworking::Impl::AuthorizationRoles ()
Get authorization roles access.
References m_roles.
ConnectToLocalHostServer()
bool ClientNetworking::Impl::ConnectToLocalHostServer (const ClientNetworking *const self, const std::chrono::milliseconds & timeout = std::chrono::seconds(10), bool expect_timeout = false)
Connects to the server on the client's host.
On failure, repeated attempts will be made until timeout seconds has elapsed. If expect_timeout is true, timeout is not reported as an error.
References ConnectToServer().
ConnectToServer()
bool ClientNetworking::Impl::ConnectToServer (const ClientNetworking *const self, const std::string & ip_address, const std::chrono::milliseconds & timeout = std::chrono::seconds(10), bool expect_timeout = false)
Connects to the server at ip_address.
On failure, repeated attempts will be made until timeout seconds has elapsed. If expect_timeout is true, timeout is not reported as an error.
References DebugLogger, ErrorLogger, HandleConnection(), IsConnected(), m_destination, m_io_context, m_socket, Networking::MessagePort(), NetworkingThread(), Networking::SOCKET_LINGER_TIME, to_string(), and TraceLogger.
Referenced by ConnectToLocalHostServer().
Destination()
const std::string & ClientNetworking::Impl::Destination () const
Returns destination address of server.
References m_destination.
DisconnectFromServer()
void ClientNetworking::Impl::DisconnectFromServer ()
Disconnects the client from the server.
References DisconnectFromServerImpl(), m_io_context, m_mutex, m_rx_connected, and m_tx_connected.
DisconnectFromServerImpl()
void ClientNetworking::Impl::DisconnectFromServerImpl () private
References m_mutex, m_outgoing_messages, m_rx_connected, m_socket, and m_tx_connected.
Referenced by AsyncReadMessage(), DisconnectFromServer(), and HandleMessageWrite().
DiscoverLANServerNames()
ClientNetworking::ServerNames ClientNetworking::Impl::DiscoverLANServerNames ()
Returns a list of the addresses and names of all servers on the Local Area Network.
References IsConnected(), and m_io_context.
GetMessage()
boost::optional< Message > ClientNetworking::Impl::GetMessage ()
Return the next incoming message from the server if available or boost::none.
Remove the message from the incoming message queue.
References m_incoming_messages, MessageQueue::PopFront(), and TraceLogger.
HandleConnection()
void ClientNetworking::Impl::HandleConnection (boost::asio::ip::tcp::resolver::iterator * it, const boost::system::error_code & error) private
References m_mutex, m_rx_connected, m_tx_connected, and TraceLogger.
Referenced by ConnectToServer().
HandleException()
void ClientNetworking::Impl::HandleException (const boost::system::system_error & error) private
References DebugLogger, ErrorLogger, and m_socket.
Referenced by NetworkingThread().
HandleMessageBodyRead()
void ClientNetworking::Impl::HandleMessageBodyRead (const std::shared_ptr< const ClientNetworking > & keep_alive, boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncReadMessage(), m_incoming_header, m_incoming_message, m_incoming_messages, and MessageQueue::PushBack().
Referenced by HandleMessageHeaderRead().
HandleMessageHeaderRead()
void ClientNetworking::Impl::HandleMessageHeaderRead (const std::shared_ptr< const ClientNetworking > & keep_alive, boost::system::error_code error, std::size_t bytes_transferred) private
References BufferToHeader(), Message::Data(), HandleMessageBodyRead(), Message::HeaderBufferSize, m_incoming_header, m_incoming_message, m_socket, Message::Resize(), and Message::Size().
Referenced by AsyncReadMessage().
HandleMessageWrite()
void ClientNetworking::Impl::HandleMessageWrite (boost::system::error_code error, std::size_t bytes_transferred) private
References AsyncWriteMessage(), DisconnectFromServerImpl(), Message::HeaderBufferSize, m_mutex, m_outgoing_header, m_outgoing_messages, and m_tx_connected.
Referenced by AsyncWriteMessage().
HasAuthRole()
bool ClientNetworking::Impl::HasAuthRole (Networking::RoleType role) const
Checks if the client has some authorization role.
References Networking::AuthRoles::HasRole(), and m_roles.
HostPlayerID()
int ClientNetworking::Impl::HostPlayerID () const
Returns the ID of the host player, or INVALID_PLAYER_ID if there is no host player.
References m_host_player_id.
IsConnected()
bool ClientNetworking::Impl::IsConnected () const
Returns true iff the client is full duplex connected to the server.
References m_mutex, m_rx_connected, and m_tx_connected.
Referenced by ConnectToServer(), and DiscoverLANServerNames().
IsRxConnected()
bool ClientNetworking::Impl::IsRxConnected () const
Returns true iff the client is connected to receive from the server.
References m_mutex, and m_rx_connected.
IsTxConnected()
bool ClientNetworking::Impl::IsTxConnected () const
Returns true iff the client is connected to send to the server.
References m_mutex, and m_tx_connected.
Referenced by SendMessage().
NetworkingThread()
void ClientNetworking::Impl::NetworkingThread (const std::shared_ptr< const ClientNetworking > self) private
References AsyncReadMessage(), AsyncWriteMessage(), error, HandleException(), m_io_context, m_mutex, m_outgoing_messages, m_rx_connected, m_tx_connected, and TraceLogger.
Referenced by ConnectToServer().
PlayerID()
int ClientNetworking::Impl::PlayerID () const
Returns the ID of the player on this client.
References m_player_id.
PlayerIsHost()
bool ClientNetworking::Impl::PlayerIsHost (int player_id) const
Returns whether the indicated player ID is the host.
References Networking::INVALID_PLAYER_ID, and m_host_player_id.
SendMessage()
void ClientNetworking::Impl::SendMessage (const Message & message)
Sends message to the server.
This function actually just enqueues the message for sending and returns immediately.
References ErrorLogger, IsTxConnected(), m_io_context, SendMessageImpl(), and TraceLogger.
SendMessageImpl()
void ClientNetworking::Impl::SendMessageImpl (Message message) private
References AsyncWriteMessage(), m_outgoing_messages, and swap().
Referenced by SendMessage().
SetHostPlayerID()
void ClientNetworking::Impl::SetHostPlayerID (int host_player_id)
Sets Host player ID.
References m_host_player_id.
SetPlayerID()
void ClientNetworking::Impl::SetPlayerID (int player_id)
Sets player ID for this client.
References DebugLogger, and m_player_id.
Member Data Documentation
m_destination
std::string ClientNetworking::Impl::m_destination private
Referenced by ConnectToServer(), and Destination().
m_host_player_id
int ClientNetworking::Impl::m_host_player_id private
Referenced by HostPlayerID(), PlayerIsHost(), and SetHostPlayerID().
m_incoming_header
Message::HeaderBuffer ClientNetworking::Impl::m_incoming_header private
Referenced by AsyncReadMessage(), HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_incoming_message
Message ClientNetworking::Impl::m_incoming_message private
Referenced by HandleMessageBodyRead(), and HandleMessageHeaderRead().
m_incoming_messages
MessageQueue ClientNetworking::Impl::m_incoming_messages private
Referenced by GetMessage(), and HandleMessageBodyRead().
m_io_context
boost::asio::io_context ClientNetworking::Impl::m_io_context private
Referenced by ConnectToServer(), DisconnectFromServer(), DiscoverLANServerNames(), NetworkingThread(), and SendMessage().
m_mutex
boost::mutex ClientNetworking::Impl::m_mutex mutable private
Referenced by DisconnectFromServer(), DisconnectFromServerImpl(), HandleConnection(), HandleMessageWrite(), IsConnected(), IsRxConnected(), IsTxConnected(), and NetworkingThread().
m_outgoing_header
Message::HeaderBuffer ClientNetworking::Impl::m_outgoing_header private
Referenced by AsyncWriteMessage(), and HandleMessageWrite().
m_outgoing_messages
std::list<Message> ClientNetworking::Impl::m_outgoing_messages private
Referenced by AsyncWriteMessage(), DisconnectFromServerImpl(), HandleMessageWrite(), NetworkingThread(), and SendMessageImpl().
m_player_id
int ClientNetworking::Impl::m_player_id private
Referenced by PlayerID(), and SetPlayerID().
m_roles
Networking::AuthRoles ClientNetworking::Impl::m_roles private
Referenced by AuthorizationRoles(), and HasAuthRole().
m_rx_connected
bool ClientNetworking::Impl::m_rx_connected private
Referenced by DisconnectFromServer(), DisconnectFromServerImpl(), HandleConnection(), IsConnected(), IsRxConnected(), and NetworkingThread().
m_socket
boost::asio::ip::tcp::socket ClientNetworking::Impl::m_socket private
Referenced by AsyncReadMessage(), AsyncWriteMessage(), ConnectToServer(), DisconnectFromServerImpl(), HandleException(), and HandleMessageHeaderRead().
m_tx_connected
bool ClientNetworking::Impl::m_tx_connected private
Referenced by DisconnectFromServer(), DisconnectFromServerImpl(), HandleConnection(), HandleMessageWrite(), IsConnected(), IsTxConnected(), and NetworkingThread().
The documentation for this class was generated from the following file:
ClientNetworking.cpp