FreeOrion: ForgetOrder Class Reference
ForgetOrder Class Reference
ForgetOrder removes the object from the empire's known objects.
#include <Order.h>
Public Member Functions
ForgetOrder (int empire, int object_id)
std::string Dump () const override
int ObjectID () const
Returns ID of object selected in this order.
Public Member Functions inherited from Order
Order ()=default
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()=default
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Private Member Functions
ForgetOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_object_id = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
ForgetOrder removes the object from the empire's known objects.
Constructor & Destructor Documentation
ForgetOrder() [1/2]
ForgetOrder::ForgetOrder (int empire, int object_id)
ForgetOrder() [2/2]
ForgetOrder::ForgetOrder () private default
Member Function Documentation
Dump()
std::string ForgetOrder::Dump () const override virtual
Reimplemented from Order.
References UserString().
ExecuteImpl()
void ForgetOrder::ExecuteImpl () const override private virtual
Preconditions:
m_object_id must be the ID of an object not owned by issuing empire
Postconditions:
the object is removed from the table of known objects.
Implements Order.
References DebugLogger, Order::EmpireID(), Universe::ForgetKnownObject(), GetUniverse(), Order::GetValidatedEmpire(), and m_object_id.
ObjectID()
int ForgetOrder::ObjectID () const inline
Returns ID of object selected in this order.
serialize()
template<typename Archive > void ForgetOrder::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_object_id
int ForgetOrder::m_object_id = INVALID_OBJECT_ID private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp