FreeOrion: ServerApp Class Reference
ServerApp Class Reference
the application framework class for the FreeOrion server.
#include <ServerApp.h>
Public Member Functions
ServerApp ()
ServerApp (const ServerApp &)=delete
ServerApp (ServerApp &&)=delete
~ServerApp () override
void AddObserverPlayerIntoGame (const PlayerConnectionPtr &player_connection)
Adds new observing player to running game.
int AddPlayerIntoGame (const PlayerConnectionPtr &player_connection, int target_empire_id)
Adds new player to running game.
bool AllOrdersReceived ()
Determines if all empired have submitted their orders for this turn It will loop the turn squence vector and check for a set order_set.
void CheckForEmpireElimination ()
Determines if any empires are eliminated (for the first time this turn, skipping any which were also eliminated previously) and if any empires are thereby victorious.
void ClearEmpireTurnOrders ()
Sets all empire turn orders to an empty set.
void CreateAIClients (const std::vector< PlayerSetupData > &player_setup_data, int max_aggression=4)
creates an AI client child process for each element of AIs
int CurrentTurn () const override
Returns the current game turn.
void DropPlayerEmpireLink (int planet_id)
Drop link between player with player_id and his empire.
int EffectsProcessingThreads () const override
bool EliminatePlayer (const PlayerConnectionPtr &player_connection)
Eliminate player's empire by player_connection.
ObjectMap & EmpireKnownObjects (int empire_id) override
Returns the server's map for known objects of specified empire.
int EmpirePlayerID (int empire_id) const
Returns the player ID for the player controlling the empire with id empire_id.
EmpireManager & Empires () override
Returns the set of known Empires for this application.
void ExpireTurn ()
Sets turn to be expired.
std::list< PlayerSetupData > FillListPlayers ()
Returns list of player for multiplayer quickstart.
const boost::circular_buffer< ChatHistoryEntity > & GetChatHistory () const
Returns chat history buffer.
Empire * GetEmpire (int id) override
Networking::ClientType GetEmpireClientType (int empire_id) const override
Returns the networking client type for the given empire_id.
const GalaxySetupData & GetGalaxySetupData () const override
Returns the galaxy setup data used for the current game.
GalaxySetupData & GetGalaxySetupData ()
Returns the galaxy setup data used for the current game.
Networking::ClientType GetPlayerClientType (int player_id) const override
Returns the networking client type for the given player_id.
std::list< std::string > GetPlayerDelegation (const std::string &player_name)
Get list of players delegated by player_name.
std::vector< PlayerSaveGameData > GetPlayerSaveGameData () const
Extracts player save game data.
Species * GetSpecies (const std::string &name) override
SpeciesManager & GetSpeciesManager () override
SupplyManager & GetSupplyManager () override
Universe & GetUniverse () override
Returns the Universe known to this application.
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override
bool IsAuthRequiredOrFillRoles (const std::string &player_name, Networking::AuthRoles &roles)
Checks if player_name requires auth to login and fill roles if not.
bool IsAuthSuccessAndFillRoles (const std::string &player_name, const std::string &auth, Networking::AuthRoles &roles)
Checks if auth match player_name and fill roles if successed.
bool IsAvailableName (const std::string &player_name) const
Checks if player_name are not used by other players.
bool IsHaveWinner () const
bool IsHostless () const
Checks if server runs in a hostless mode.
bool IsLocalHumanPlayer (int player_id)
Checks if player with ID player_id is a human player who's client runs on the same machine as the server.
bool IsTurnExpired () const
void LoadChatHistory ()
Loads chat history via python script.
void LoadMPGameInit (const MultiplayerLobbyData &lobby_data, const std::vector< PlayerSaveGameData > &player_save_game_data, std::shared_ptr< ServerSaveGameData > server_save_game_data)
Restores saved multiplayer gamestate and human and AI client state information.
void LoadSPGameInit (const std::vector< PlayerSaveGameData > &player_save_game_data, std::shared_ptr< ServerSaveGameData > server_save_game_data)
Restores saved single player gamestate and human and AI client state information.
ServerNetworking & Networking ()
returns the networking object for the server
void NewMPGameInit (const MultiplayerLobbyData &multiplayer_lobby_data)
Intializes multi player game universe, sends out initial game state to clients, and signals clients to start first turn.
void NewSPGameInit (const SinglePlayerSetupData &single_player_setup_data)
Intializes single player game universe.
void operator() ()
external interface to Run()
const ServerApp & operator= (const ServerApp &)=delete
ServerApp & operator= (IApp &&)=delete
int PlayerEmpireID (int player_id) const
Returns the empire ID for the player with ID player_id.
void PostCombatProcessTurns ()
Determines resource and supply distribution pathes and connections, updates research, production, influence spending, does population growth, updates current turn number, checks for eliminated or victorious empires / players, sends new turn updates.
void PreCombatProcessTurns ()
Executes player orders, does colonization, does ordered scrapping, does fleet movements, and updates visibility before combats are handled.
void ProcessCombats ()
Determines which combats will occur, handles running the combats and updating the universe after the results are available.
void PushChatMessage (const std::string &text, const std::string &player_name, std::array< unsigned char, 4 > text_color, const boost::posix_time::ptime &timestamp)
void RevokeEmpireTurnReadyness (int empire_id)
Revokes turn order's ready state for the given empire.
void SetEmpireSaveGameData (int empire_id, std::unique_ptr< PlayerSaveGameData > &&save_game_data)
Adds save game data includes turn orders for the given empire for the current turn.
void StartBackgroundParsing (const PythonParser &python, std::promise< void > &&barrier) override
Launches asynchronous parsing of game content, then starts additional content parsing in the calling thread.
void UpdateCombatLogs (const Message &msg, PlayerConnectionPtr player_connection)
Send the requested combat logs to the client.
void UpdateMonsterTravelRestrictions ()
Used post combat, to selectively clear the m_arrival_starlane flag of monsters so that they can impose blockades.
void UpdatePartialOrders (int empire_id, const OrderSet &added, const std::set< int > &deleted)
Updated empire orders without changes in readiness status.
void UpdateSavePreviews (const Message &msg, PlayerConnectionPtr player_connection)
bool VerifySPGameAIs (const SinglePlayerSetupData &single_player_setup_data)
Return true if single player game AIs are compatible with created universe and are ready to start a new game.
Public Member Functions inherited from IApp
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
Static Public Member Functions
static ServerApp * GetApp ()
Returns a ClientApp pointer to the singleton instance of the app.
Static Public Member Functions inherited from IApp
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Private Member Functions
void AddEmpireTurn (int empire_id, const PlayerSaveGameData &psgd)
Adds an existing empire to turn processing.
void CleanupAIs ()
cleans up AI processes: kills the process and empties the container of AI processes
void ExecuteScriptedTurnEvents ()
Calls Python turn events script.
void GenerateUniverse (std::map< int, PlayerSetupData > &player_setup_data)
Calls Python universe generator script.
std::map< int, PlayerInfo > GetPlayerInfoMap () const
Get players info map to send it in GameStart message.
void HandleDiplomaticMessageChange (int empire1_id, int empire2_id)
Called when this sever's EmpireManager changes the diplmatic message between two empires.
void HandleDiplomaticStatusChange (int empire1_id, int empire2_id)
Called when this server's EmpireManager changes the diplomatic status between two empires.
void HandleLoggerConfig (const Message &msg, PlayerConnectionPtr player_connection)
Checks validity of logger config message and then update logger and loggers of all AIs.
void HandleMessage (const Message &msg, PlayerConnectionPtr player_connection)
Handles an incoming message from the server with the appropriate action or response.
void HandleNonPlayerMessage (const Message &msg, PlayerConnectionPtr player_connection)
When Messages arrive from connections that are not established players, they arrive via a call to this function.
void HandleShutdownMessage (const Message &msg, PlayerConnectionPtr player_connection)
Checks validity of shut down message from player, then attempts to cleanly shut down this server process.
void InitializePython ()
Initialize the python engine if not already running.
void LoadGameInit (const std::vector< PlayerSaveGameData > &player_save_game_data, const std::vector< std::pair< int, int >> &player_id_to_save_game_data_index, std::shared_ptr< ServerSaveGameData > server_save_game_data)
Clears any old game stored orders, victors or eliminated players, ads empires to turn processing list, does start-of-turn empire supply and resource pool determination, regenerates pathfinding graphc, restores any UI or AI state information players had saved, and compiles info about all players to send out to all other players are part of game start messages.
void NewGameInitConcurrentWithJoiners (const GalaxySetupData &galaxy_setup_data, const std::vector< PlayerSetupData > &player_setup_data)
Clears any old game stored orders, victors or eliminated players, ads empires to turn processing list, does start-of-turn empire supply and resource pool determination.
bool NewGameInitVerifyJoiners (const std::vector< PlayerSetupData > &player_setup_data)
Return true if player data is consistent with starting a new game.
void PlayerDisconnected (PlayerConnectionPtr player_connection)
Called by ServerNetworking when a player's TCP connection is closed.
void RemoveEmpireTurn (int empire_id)
Removes an empire from turn processing.
void Run ()
initializes app state, then executes main event handler/render loop (Poll())
void SelectNewHost ()
Called when the host player has disconnected.
void SendNewGameStartMessages ()
Sends out initial new game state to clients, and signals clients to start first turn.
void SetAIsProcessPriorityToLow (bool set_to_low)
Sets the priority for all AI processes.
void ShutdownTimedoutHandler (boost::system::error_code error)
Handle shutdown timeout by killing all ais.
void SignalHandler (const boost::system::error_code &error, int signal_number)
Called when server process receive termination signal.
Private Attributes
std::map< std::string, Process > m_ai_client_processes
AI client child processes indexed by player name.
boost::circular_buffer< ChatHistoryEntity > m_chat_history
Stored last chat messages.
int m_current_turn = INVALID_GAME_TURN
current turn number
EmpireManager m_empires
ServerFSM * m_fsm
GalaxySetupData m_galaxy_setup_data
stored setup data for the game currently being played
boost::asio::io_context m_io_context
ServerNetworking m_networking
std::map< int, int > m_player_empire_ids
map from player id to empire id that the player controls.
PythonServer m_python_server
boost::asio::signal_set m_signals
bool m_single_player_game = false
true when the game being played is single-player
SpeciesManager m_species_manager
SupplyManager m_supply_manager
bool m_turn_expired = false
true when turn exceeds its timeout
std::map< int, std::unique_ptr< PlayerSaveGameData > > m_turn_sequence
Turn sequence map is used for turn processing.
Universe m_universe
Friends
struct Idle
struct MPLobby
struct PlayingGame
struct ProcessingTurn
struct ServerFSM
struct ShuttingDownServer
struct WaitingForMPGameJoiners
struct WaitingForSaveData
struct WaitingForSPGameJoiners
struct WaitingForTurnEnd
struct WaitingForTurnEndIdle
Additional Inherited Members
Protected Member Functions inherited from IApp
IApp ()
Static Protected Attributes inherited from IApp
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Detailed Description
the application framework class for the FreeOrion server.
Constructor & Destructor Documentation
ServerApp() [1/3]
ServerApp::ServerApp ()
References GalaxySetupData::age, GalaxySetupData::ai_aggr, EmpireManager::DiplomaticMessageChangedSignal, EmpireManager::DiplomaticStatusChangedSignal, Empires(), FreeOrionVersionString(), GalaxySetupData::game_uid, OptionsDB::Get(), GetOptionsDB(), GetResourceDir(), GetUserDataDir(), HandleDiplomaticMessageChange(), HandleDiplomaticStatusChange(), InfoLogger, InitializePython(), InitLoggingOptionsDBSystem(), InitLoggingSystem(), PythonCommon::IsPythonRunning(), LogDependencyVersions(), m_fsm, m_galaxy_setup_data, m_python_server, m_signals, GalaxySetupData::monster_freq, GalaxySetupData::native_freq, OverrideAllLoggersThresholds(), GalaxySetupData::planet_density, GalaxySetupData::seed, OptionsDB::Set(), GalaxySetupData::shape, SignalHandler(), GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, StartBackgroundParsing(), and to_LogLevel().
ServerApp() [2/3]
ServerApp::ServerApp (const ServerApp &) delete
ServerApp() [3/3]
ServerApp::ServerApp (ServerApp &&) delete
~ServerApp()
ServerApp::~ServerApp () override
References CleanupAIs(), DebugLogger, and m_fsm.
Member Function Documentation
AddEmpireTurn()
void ServerApp::AddEmpireTurn (int empire_id, const PlayerSaveGameData & psgd) private
Adds an existing empire to turn processing.
The position the empire is in the vector is it's position in the turn processing.
References m_turn_sequence.
Referenced by GetGalaxySetupData(), LoadGameInit(), and NewGameInitConcurrentWithJoiners().
AddObserverPlayerIntoGame()
void ServerApp::AddObserverPlayerIntoGame (const PlayerConnectionPtr & player_connection)
Adds new observing player to running game.
Simply sends GAME_START message so established player knows he is in the game.
References ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, ErrorLogger, GameStartMessage(), GetCombatLogManager(), GetPlayerInfoMap(), GetSpeciesManager(), GetSupplyManager(), m_current_turn, m_empires, m_galaxy_setup_data, m_single_player_game, and m_universe.
Referenced by PlayingGame::EstablishPlayer(), and GetGalaxySetupData().
AddPlayerIntoGame()
int ServerApp::AddPlayerIntoGame (const PlayerConnectionPtr & player_connection, int target_empire_id)
Adds new player to running game.
Search empire by player's name or delegation list if target_empire_id set and return empire id if success and ALL_EMPIRES if no empire found. Simply sends GAME_START message so established player knows he is in the game. Notificates the player about statuses of other empires.
References ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::Disconnect(), DropPlayerEmpireLink(), anonymous_namespace{CUIWnd.cpp}::dummy, EmpirePlayerID(), Empires(), ServerNetworking::established_end(), GameStartMessage(), OptionsDB::Get(), GetCombatLogManager(), EmpireManager::GetEmpire(), GetEmpireClientType(), GetOptionsDB(), ServerNetworking::GetPlayer(), GetPlayerDelegation(), GetPlayerInfoMap(), GetSpeciesManager(), GetSupplyManager(), InfoLogger, Networking::INVALID_PLAYER_ID, m_ai_client_processes, m_current_turn, m_empires, m_galaxy_setup_data, m_networking, m_player_empire_ids, m_single_player_game, m_turn_sequence, m_universe, PlayerStatusMessage(), ServerNetworking::SendMessageAll(), and WarnLogger.
Referenced by PlayingGame::EstablishPlayer(), GetGalaxySetupData(), and PlayingGame::react().
AllOrdersReceived()
bool ServerApp::AllOrdersReceived ()
Determines if all empired have submitted their orders for this turn It will loop the turn squence vector and check for a set order_set.
A order_set of 0 indicates that the empire has not yet submitted their orders for the given turn
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ErrorLogger, GetEmpire(), GetEmpireClientType(), m_current_turn, m_turn_expired, and m_turn_sequence.
Referenced by GetGalaxySetupData(), and WaitingForTurnEnd::react().
CheckForEmpireElimination()
void ServerApp::CheckForEmpireElimination ()
Determines if any empires are eliminated (for the first time this turn, skipping any which were also eliminated previously) and if any empires are thereby victorious.
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, anonymous_namespace{ServerApp.cpp}::EmpireEliminated(), EmpirePlayerID(), Empires(), ServerNetworking::established_end(), GameRules::Get(), EmpireManager::GetDiplomaticStatus(), GetEmpireClientType(), GetGameRules(), ServerNetworking::GetPlayer(), m_ai_client_processes, m_networking, m_single_player_game, m_universe, Universe::Objects(), RemoveEmpireTurn(), and UserStringNop.
Referenced by GetGalaxySetupData(), and PostCombatProcessTurns().
CleanupAIs()
void ServerApp::CleanupAIs () private
cleans up AI processes: kills the process and empties the container of AI processes
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::empty(), EndGameMessage(), ErrorLogger, m_ai_client_processes, and m_networking.
Referenced by CreateAIClients(), GetGalaxySetupData(), and ~ServerApp().
ClearEmpireTurnOrders()
void ServerApp::ClearEmpireTurnOrders ()
Sets all empire turn orders to an empty set.
References Empires(), and m_turn_sequence.
Referenced by GetGalaxySetupData(), and PreCombatProcessTurns().
CreateAIClients()
void ServerApp::CreateAIClients (const std::vector< PlayerSetupData > & player_setup_data, int max_aggression = 4)
creates an AI client child process for each element of AIs
References anonymous_namespace{ServerApp.cpp}::AIClientExe(), tag_parser::args, CleanupAIs(), Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ErrorLogger, OptionsDB::Get(), GetOptionsDB(), m_ai_client_processes, m_networking, ServerNetworking::SendMessageAll(), SetAIsProcessPriorityToLow(), and TurnProgressMessage().
Referenced by GetGalaxySetupData(), WaitingForMPGameJoiners::WaitingForMPGameJoiners(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
CurrentTurn()
int ServerApp::CurrentTurn () const inline override virtual
Returns the current game turn.
Returns
The number representing the current game turn.
Implements IApp.
References m_current_turn.
Referenced by anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo(), ServerFSM::HandleNonLobbyDisconnection(), PostCombatProcessTurns(), ProcessCombats(), PlayingGame::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), and ServerFSM::UpdateIngameLobby().
DropPlayerEmpireLink()
void ServerApp::DropPlayerEmpireLink (int planet_id)
Drop link between player with player_id and his empire.
References m_player_empire_ids.
Referenced by AddPlayerIntoGame(), ServerFSM::EstablishPlayer(), GetGalaxySetupData(), and ServerFSM::HandleNonLobbyDisconnection().
EffectsProcessingThreads()
int ServerApp::EffectsProcessingThreads () const override virtual
Implements IApp.
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetGalaxySetupData().
EliminatePlayer()
bool ServerApp::EliminatePlayer (const PlayerConnectionPtr & player_connection)
Eliminate player's empire by player_connection.
Return true if player was eliminated.
References ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_PLAYER, Empires(), ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ObjectMap::find(), GameRules::Get(), GetEmpire(), GetEmpireClientType(), GetGameRules(), GetUniverse(), Networking::INVALID_CLIENT_TYPE, m_networking, m_player_empire_ids, m_universe, Universe::Objects(), PlayerEmpireID(), PlayerStatusMessage(), Universe::RecursiveDestroy(), RemoveEmpireTurn(), and UserStringNop.
Referenced by GetGalaxySetupData(), and PlayingGame::react().
EmpireKnownObjects()
ObjectMap & ServerApp::EmpireKnownObjects (int empire_id) override virtual
Returns the server's map for known objects of specified empire.
Implements IApp.
References Universe::EmpireKnownObjects(), and m_universe.
EmpirePlayerID()
int ServerApp::EmpirePlayerID (int empire_id) const
Returns the player ID for the player controlling the empire with id empire_id.
References Networking::INVALID_PLAYER_ID, and m_player_empire_ids.
Referenced by AddPlayerIntoGame(), CheckForEmpireElimination(), GetEmpireClientType(), GetGalaxySetupData(), and HandleDiplomaticMessageChange().
Empires()
EmpireManager & ServerApp::Empires () override virtual
Returns the set of known Empires for this application.
Implements IApp.
References m_empires.
Referenced by AddPlayerIntoGame(), CheckForEmpireElimination(), ClearEmpireTurnOrders(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), EliminatePlayer(), HandleDiplomaticMessageChange(), HandleDiplomaticStatusChange(), PostCombatProcessTurns(), PreCombatProcessTurns(), PlayingGame::react(), ProcessingTurn::react(), and ServerApp().
ExecuteScriptedTurnEvents()
void ServerApp::ExecuteScriptedTurnEvents () private
Calls Python turn events script.
Supposed to be called every turn so it can be used by content scripters to implement user customizable turn events.
References ErrorLogger, ErrorMessage(), PythonServer::ExecuteTurnEvents(), GetApp(), GetPythonTurnEventsDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by GetGalaxySetupData(), and PostCombatProcessTurns().
ExpireTurn()
void ServerApp::ExpireTurn ()
Sets turn to be expired.
Server doesn't wait for human player turns.
References InfoLogger, and m_turn_expired.
Referenced by GetGalaxySetupData().
FillListPlayers()
std::list< PlayerSetupData > ServerApp::FillListPlayers ()
Returns list of player for multiplayer quickstart.
References ErrorLogger, ErrorMessage(), PythonServer::FillListPlayers(), GetApp(), GetPythonAuthDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by GetGalaxySetupData(), and Idle::react().
GenerateUniverse()
void ServerApp::GenerateUniverse (std::map< int, PlayerSetupData > & player_setup_data) private
Calls Python universe generator script.
Supposed to be called to create a new universe so it can be used by content scripters to customize universe generation.
References PredefinedShipDesignManager::AddShipDesignsToUniverse(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), Universe::BackPropagateObjectMeters(), Universe::Clear(), SpeciesManager::ClearSpeciesHomeworlds(), ClockSeed(), PythonServer::CreateUniverse(), DebugLogger, ObjectMap::Dump(), ErrorLogger, ErrorMessage(), GetApp(), GetOptionsDB(), GetPredefinedShipDesignManager(), GetPythonUniverseGeneratorDir(), GalaxySetupData::GetSeed(), PythonCommon::HandleErrorAlreadySet(), InitEmpires(), PythonCommon::IsPythonRunning(), m_empires, m_fsm, m_galaxy_setup_data, m_python_server, m_species_manager, m_supply_manager, m_universe, Networking(), Universe::Objects(), Universe::ResetAllIDAllocation(), Seed(), GalaxySetupData::seed, ServerNetworking::SendMessageAll(), SetActiveMetersToTargetMaxCurrentValues(), PythonBase::SetCurrentDir(), GalaxySetupData::SetGameUID(), SetNativePopulationValues(), GalaxySetupData::SetSeed(), to_string(), TraceLogger, Universe::UpdateEmpireObjectVisibilities(), Universe::UpdateMeterEstimates(), and UserStringNop.
Referenced by GetGalaxySetupData(), and NewGameInitConcurrentWithJoiners().
GetApp()
ServerApp * ServerApp::GetApp () static
Returns a ClientApp pointer to the singleton instance of the app.
References IApp::s_app.
Referenced by ExecuteScriptedTurnEvents(), FillListPlayers(), GenerateUniverse(), GetPlayerDelegation(), IsAuthRequiredOrFillRoles(), IsAuthSuccessAndFillRoles(), LoadChatHistory(), LoadGame(), PushChatMessage(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), and anonymous_namespace{ServerFSM.cpp}::SendMessageToHost().
GetChatHistory()
const boost::circular_buffer< ChatHistoryEntity > & ServerApp::GetChatHistory () const
Returns chat history buffer.
References m_chat_history.
Referenced by ServerFSM::EstablishPlayer(), and GetGalaxySetupData().
GetEmpire()
Empire * ServerApp::GetEmpire (int id) override virtual
Implements IApp.
References EmpireManager::GetEmpire(), and m_empires.
Referenced by AllOrdersReceived(), anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps(), EliminatePlayer(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), PreCombatProcessTurns(), RevokeEmpireTurnReadyness(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
GetEmpireClientType()
Networking::ClientType ServerApp::GetEmpireClientType (int empire_id) const override virtual
Returns the networking client type for the given empire_id.
Implements IApp.
References EmpirePlayerID(), and GetPlayerClientType().
Referenced by AddPlayerIntoGame(), AllOrdersReceived(), CheckForEmpireElimination(), EliminatePlayer(), GetGalaxySetupData(), and ServerFSM::HandleNonLobbyDisconnection().
GetGalaxySetupData() [1/2]
const GalaxySetupData& ServerApp::GetGalaxySetupData () const inline override virtual
Returns the galaxy setup data used for the current game.
Implements IApp.
References EffectsProcessingThreads(), EmpirePlayerID(), GetChatHistory(), GetEmpireClientType(), GetPlayerClientType(), GetPlayerSaveGameData(), IsAvailableName(), IsHaveWinner(), IsHostless(), IsLocalHumanPlayer(), IsTurnExpired(), m_galaxy_setup_data, operator()(), PlayerEmpireID(), and StartBackgroundParsing().
Referenced by ServerFSM::UpdateIngameLobby().
GetGalaxySetupData() [2/2]
GalaxySetupData& ServerApp::GetGalaxySetupData () inline
Returns the galaxy setup data used for the current game.
References AddEmpireTurn(), AddObserverPlayerIntoGame(), AddPlayerIntoGame(), AllOrdersReceived(), CheckForEmpireElimination(), CleanupAIs(), ClearEmpireTurnOrders(), CreateAIClients(), DropPlayerEmpireLink(), EliminatePlayer(), error, ExecuteScriptedTurnEvents(), ExpireTurn(), FillListPlayers(), GenerateUniverse(), GetPlayerDelegation(), GetPlayerInfoMap(), HandleDiplomaticMessageChange(), HandleDiplomaticStatusChange(), HandleLoggerConfig(), HandleMessage(), HandleNonPlayerMessage(), HandleShutdownMessage(), InitializePython(), IsAuthRequiredOrFillRoles(), IsAuthSuccessAndFillRoles(), LoadChatHistory(), LoadGameInit(), LoadMPGameInit(), LoadSPGameInit(), m_galaxy_setup_data, Networking(), NewGameInitConcurrentWithJoiners(), NewGameInitVerifyJoiners(), NewMPGameInit(), NewSPGameInit(), PlayerDisconnected(), PostCombatProcessTurns(), PreCombatProcessTurns(), ProcessCombats(), PushChatMessage(), RemoveEmpireTurn(), RevokeEmpireTurnReadyness(), Run(), SelectNewHost(), SendNewGameStartMessages(), SetAIsProcessPriorityToLow(), SetEmpireSaveGameData(), ShutdownTimedoutHandler(), SignalHandler(), UpdateCombatLogs(), UpdateMonsterTravelRestrictions(), UpdatePartialOrders(), UpdateSavePreviews(), and VerifySPGameAIs().
GetPlayerClientType()
Networking::ClientType ServerApp::GetPlayerClientType (int player_id) const override virtual
Returns the networking client type for the given player_id.
Implements IApp.
References ServerNetworking::established_end(), ServerNetworking::GetPlayer(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, and m_networking.
Referenced by GetEmpireClientType(), and GetGalaxySetupData().
GetPlayerDelegation()
std::list< std::string > ServerApp::GetPlayerDelegation (const std::string & player_name)
Get list of players delegated by player_name.
References ErrorLogger, ErrorMessage(), GetApp(), PythonServer::GetPlayerDelegation(), GetPythonAuthDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by AddPlayerIntoGame(), and GetGalaxySetupData().
GetPlayerInfoMap()
std::map< int, PlayerInfo > ServerApp::GetPlayerInfoMap () const private
Get players info map to send it in GameStart message.
References ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ErrorLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), m_networking, PlayerEmpireID(), and ServerNetworking::PlayerIsHost().
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), GetGalaxySetupData(), LoadGameInit(), SendNewGameStartMessages(), and ServerFSM::UpdateIngameLobby().
GetPlayerSaveGameData()
std::vector< PlayerSaveGameData > ServerApp::GetPlayerSaveGameData () const
Extracts player save game data.
References DebugLogger, and m_turn_sequence.
Referenced by GetGalaxySetupData(), ServerFSM::HandleNonLobbyDisconnection(), PlayingGame::react(), and WaitingForTurnEnd::react().
GetSpecies()
Species * ServerApp::GetSpecies (const std::string & name) override virtual
Implements IApp.
References SpeciesManager::GetSpecies(), and m_species_manager.
GetSpeciesManager()
SpeciesManager & ServerApp::GetSpeciesManager () override virtual
Implements IApp.
References m_species_manager.
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), LoadGameInit(), PostCombatProcessTurns(), and SendNewGameStartMessages().
GetSupplyManager()
SupplyManager & ServerApp::GetSupplyManager () override virtual
Implements IApp.
References m_supply_manager.
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), LoadGameInit(), PostCombatProcessTurns(), and SendNewGameStartMessages().
GetUniverse()
Universe & ServerApp::GetUniverse () override virtual
Returns the Universe known to this application.
Returns
A constant reference to the single Universe instance representing the known universe of this application.
Implements IApp.
References m_universe.
Referenced by anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::CleanUpBombardmentStateInfo(), EliminatePlayer(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), and anonymous_namespace{ServerApp.cpp}::UpdateResourceCenterFocusHistoryInfo().
GetVisibleObjectName()
std::string ServerApp::GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override virtual
Implements IApp.
References ErrorLogger.
HandleDiplomaticMessageChange()
void ServerApp::HandleDiplomaticMessageChange (int empire1_id, int empire2_id) private
Called when this sever's EmpireManager changes the diplmatic message between two empires.
Updates those empires of the change.
References DiplomacyMessage(), EmpirePlayerID(), Empires(), ServerNetworking::established_end(), EmpireManager::GetDiplomaticMessage(), ServerNetworking::GetPlayer(), Networking::INVALID_PLAYER_ID, and m_networking.
Referenced by GetGalaxySetupData(), and ServerApp().
HandleDiplomaticStatusChange()
void ServerApp::HandleDiplomaticStatusChange (int empire1_id, int empire2_id) private
Called when this server's EmpireManager changes the diplomatic status between two empires.
Updates those empires of the change.
References DiplomaticStatusMessage(), Empires(), ServerNetworking::established_begin(), ServerNetworking::established_end(), EmpireManager::GetDiplomaticStatus(), and m_networking.
Referenced by GetGalaxySetupData(), and ServerApp().
HandleLoggerConfig()
void ServerApp::HandleLoggerConfig (const Message & msg, PlayerConnectionPtr player_connection) private
Checks validity of logger config message and then update logger and loggers of all AIs.
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), ExtractLoggerConfigMessageData(), ServerNetworking::HostPlayerID(), Networking::INVALID_PLAYER_ID, LoggerConfigMessage(), m_networking, ServerNetworking::PlayerIsHost(), SetLoggerThresholds(), and WarnLogger.
Referenced by GetGalaxySetupData(), and HandleMessage().
HandleMessage()
void ServerApp::HandleMessage (const Message & msg, PlayerConnectionPtr player_connection) private
Handles an incoming message from the server with the appropriate action or response.
References ServerNetworking::Disconnect(), ErrorLogger, HandleLoggerConfig(), HandleShutdownMessage(), m_fsm, m_networking, Message::Type(), ServerNetworking::UpdateCookie(), and UpdateSavePreviews().
Referenced by GetGalaxySetupData().
HandleNonPlayerMessage()
void ServerApp::HandleNonPlayerMessage (const Message & msg, PlayerConnectionPtr player_connection) private
When Messages arrive from connections that are not established players, they arrive via a call to this function.
References DebugLogger, ServerNetworking::Disconnect(), ErrorLogger, m_fsm, m_networking, ServerNetworking::size(), and Message::Type().
Referenced by GetGalaxySetupData().
HandleShutdownMessage()
void ServerApp::HandleShutdownMessage (const Message & msg, PlayerConnectionPtr player_connection) private
Checks validity of shut down message from player, then attempts to cleanly shut down this server process.
References DebugLogger, m_fsm, m_networking, and ServerNetworking::PlayerIsHost().
Referenced by GetGalaxySetupData(), and HandleMessage().
InitializePython()
void ServerApp::InitializePython () private
Initialize the python engine if not already running.
References ErrorLogger, PythonBase::Initialize(), PythonCommon::IsPythonRunning(), and m_python_server.
Referenced by GetGalaxySetupData(), Idle::react(), ServerApp(), and WaitingForMPGameJoiners::WaitingForMPGameJoiners().
IsAuthRequiredOrFillRoles()
bool ServerApp::IsAuthRequiredOrFillRoles (const std::string & player_name, Networking::AuthRoles & roles)
Checks if player_name requires auth to login and fill roles if not.
References ErrorLogger, ErrorMessage(), GetApp(), GetPythonAuthDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), PythonServer::IsRequireAuthOrReturnRoles(), m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by GetGalaxySetupData(), MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
IsAuthSuccessAndFillRoles()
bool ServerApp::IsAuthSuccessAndFillRoles (const std::string & player_name, const std::string & auth, Networking::AuthRoles & roles)
Checks if auth match player_name and fill roles if successed.
References ErrorLogger, ErrorMessage(), GetApp(), GetPythonAuthDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), PythonServer::IsSuccessAuthAndReturnRoles(), m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by GetGalaxySetupData(), MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
IsAvailableName()
bool ServerApp::IsAvailableName (const std::string & player_name) const
Checks if player_name are not used by other players.
References ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerNetworking::IsAvailableNameInCookies(), and m_networking.
Referenced by GetGalaxySetupData(), MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
IsHaveWinner()
bool ServerApp::IsHaveWinner () const
References m_empires.
Referenced by GetGalaxySetupData().
IsHostless()
bool ServerApp::IsHostless () const
Checks if server runs in a hostless mode.
References OptionsDB::Get(), and GetOptionsDB().
Referenced by GetGalaxySetupData(), ServerFSM::HandleNonLobbyDisconnection(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), NewGameInitVerifyJoiners(), PlayingGame::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), and MPLobby::ValidateClientLimits().
IsLocalHumanPlayer()
bool ServerApp::IsLocalHumanPlayer (int player_id)
Checks if player with ID player_id is a human player who's client runs on the same machine as the server.
References Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, ServerNetworking::established_end(), ServerNetworking::GetPlayer(), and m_networking.
Referenced by GetGalaxySetupData(), and WaitingForTurnEnd::react().
IsTurnExpired()
bool ServerApp::IsTurnExpired () const
References m_turn_expired.
Referenced by GetGalaxySetupData(), and WaitingForTurnEnd::react().
LoadChatHistory()
void ServerApp::LoadChatHistory ()
Loads chat history via python script.
References ErrorLogger, ErrorMessage(), GetApp(), GetPythonChatDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), PythonServer::LoadChatHistory(), m_chat_history, m_fsm, m_python_server, Networking(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by GetGalaxySetupData(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), and Idle::react().
LoadGameInit()
void ServerApp::LoadGameInit (const std::vector< PlayerSaveGameData > & player_save_game_data, const std::vector< std::pair< int, int >> & player_id_to_save_game_data_index, std::shared_ptr< ServerSaveGameData > server_save_game_data) private
Clears any old game stored orders, victors or eliminated players, ads empires to turn processing list, does start-of-turn empire supply and resource pool determination, regenerates pathfinding graphc, restores any UI or AI state information players had saved, and compiles info about all players to send out to all other players are part of game start messages.
References AddEmpireTurn(), ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, PlayerSaveHeaderData::empire_id, ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), GameStartMessage(), GetCombatLogManager(), EmpireManager::GetEmpire(), GetGameRules(), GalaxySetupData::GetGameRules(), GetPlayerInfoMap(), GetSpeciesManager(), GetSupplyManager(), Universe::InitializeSystemGraph(), m_current_turn, m_empires, m_galaxy_setup_data, m_networking, m_player_empire_ids, m_single_player_game, m_species_manager, m_supply_manager, m_turn_sequence, m_universe, ServerNetworking::NumEstablishedPlayers(), Universe::Objects(), PlayerSaveGameData::orders, PlayerEmpireID(), RevokeEmpireTurnReadyness(), PlayerSaveGameData::save_state_string, ServerNetworking::SendMessageAll(), GameRules::SetFromStrings(), PlayerSaveGameData::ui_data, anonymous_namespace{ServerApp.cpp}::UpdateEmpireSupply(), Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps(), and UserStringNop.
Referenced by GetGalaxySetupData(), LoadMPGameInit(), and LoadSPGameInit().
LoadMPGameInit()
void ServerApp::LoadMPGameInit (const MultiplayerLobbyData & lobby_data, const std::vector< PlayerSaveGameData > & player_save_game_data, std::shared_ptr< ServerSaveGameData > server_save_game_data)
Restores saved multiplayer gamestate and human and AI client state information.
References PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForAIPlayer(), anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForHumanPlayer(), LoadGameInit(), m_networking, and MultiplayerLobbyData::players.
Referenced by GetGalaxySetupData(), MPLobby::react(), and WaitingForMPGameJoiners::react().
LoadSPGameInit()
void ServerApp::LoadSPGameInit (const std::vector< PlayerSaveGameData > & player_save_game_data, std::shared_ptr< ServerSaveGameData > server_save_game_data)
Restores saved single player gamestate and human and AI client state information.
References PlayerSaveHeaderData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerNetworking::HostPlayerID(), LoadGameInit(), and m_networking.
Referenced by GetGalaxySetupData(), and WaitingForSPGameJoiners::react().
Networking()
ServerNetworking & ServerApp::Networking ()
returns the networking object for the server
References m_networking.
Referenced by ServerFSM::EstablishPlayer(), ExecuteScriptedTurnEvents(), FillListPlayers(), GenerateUniverse(), GetGalaxySetupData(), GetPlayerDelegation(), ServerFSM::HandleNonLobbyDisconnection(), IsAuthRequiredOrFillRoles(), IsAuthSuccessAndFillRoles(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), LoadChatHistory(), PushChatMessage(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), anonymous_namespace{ServerFSM.cpp}::SendMessageToHost(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
NewGameInitConcurrentWithJoiners()
void ServerApp::NewGameInitConcurrentWithJoiners (const GalaxySetupData & galaxy_setup_data, const std::vector< PlayerSetupData > & player_setup_data) private
Clears any old game stored orders, victors or eliminated players, ads empires to turn processing list, does start-of-turn empire supply and resource pool determination.
References AddEmpireTurn(), Universe::ApplyGenerateSitRepEffects(), BEFORE_FIRST_TURN, EmpireManager::Clear(), Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ErrorLogger, ErrorMessage(), GenerateUniverse(), EmpireManager::GetEmpire(), GetGameRules(), GalaxySetupData::GetGameRules(), Networking::INVALID_PLAYER_ID, m_current_turn, m_empires, m_galaxy_setup_data, m_networking, m_player_empire_ids, m_species_manager, m_supply_manager, m_turn_expired, m_turn_sequence, m_universe, ServerNetworking::SendMessageAll(), GameRules::SetFromStrings(), TurnProgressMessage(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireSupply(), Universe::UpdateStatRecords(), and UserStringNop.
Referenced by GetGalaxySetupData(), NewMPGameInit(), and NewSPGameInit().
NewGameInitVerifyJoiners()
bool ServerApp::NewGameInitVerifyJoiners (const std::vector< PlayerSetupData > & player_setup_data) private
Return true if player data is consistent with starting a new game.
References PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerNetworking::HostPlayerID(), Networking::INVALID_CLIENT_TYPE, IsHostless(), m_networking, ServerNetworking::NumEstablishedPlayers(), PlayerSetupData::player_name, ServerNetworking::SendMessageAll(), and UserStringNop.
Referenced by GetGalaxySetupData(), NewMPGameInit(), and VerifySPGameAIs().
NewMPGameInit()
void ServerApp::NewMPGameInit (const MultiplayerLobbyData & multiplayer_lobby_data)
Intializes multi player game universe, sends out initial game state to clients, and signals clients to start first turn.
References PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), Networking::INVALID_PLAYER_ID, m_networking, NewGameInitConcurrentWithJoiners(), NewGameInitVerifyJoiners(), PlayerSetupData::player_id, PlayerSetupData::player_name, MultiplayerLobbyData::players, and SendNewGameStartMessages().
Referenced by GetGalaxySetupData(), MPLobby::react(), and WaitingForMPGameJoiners::react().
NewSPGameInit()
void ServerApp::NewSPGameInit (const SinglePlayerSetupData & single_player_setup_data)
Intializes single player game universe.
References NewGameInitConcurrentWithJoiners(), and SinglePlayerSetupData::players.
Referenced by GetGalaxySetupData(), WaitingForSPGameJoiners::react(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
operator()()
void ServerApp::operator() ()
external interface to Run()
References Run().
Referenced by GetGalaxySetupData().
operator=() [1/2]
const ServerApp& ServerApp::operator= (const ServerApp &) delete
operator=() [2/2]
ServerApp& ServerApp::operator= (IApp &&) delete
PlayerDisconnected()
void ServerApp::PlayerDisconnected (PlayerConnectionPtr player_connection) private
Called by ServerNetworking when a player's TCP connection is closed.
References m_fsm.
Referenced by GetGalaxySetupData().
PlayerEmpireID()
int ServerApp::PlayerEmpireID (int player_id) const
Returns the empire ID for the player with ID player_id.
References ALL_EMPIRES, and m_player_empire_ids.
Referenced by EliminatePlayer(), GetGalaxySetupData(), GetPlayerInfoMap(), ServerFSM::HandleNonLobbyDisconnection(), LoadGameInit(), PostCombatProcessTurns(), PreCombatProcessTurns(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), SendNewGameStartMessages(), and ServerFSM::UpdateIngameLobby().
PostCombatProcessTurns()
void ServerApp::PostCombatProcessTurns ()
Determines resource and supply distribution pathes and connections, updates research, production, influence spending, does population growth, updates current turn number, checks for eliminated or victorious empires / players, sends new turn updates.
References ObjectMap::all(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), Universe::BackPropagateObjectMeters(), CheckForEmpireElimination(), Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, CurrentTurn(), DebugLogger, ObjectMap::Dump(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ExecuteScriptedTurnEvents(), ObjectMap::get(), GetCombatLogManager(), GetGameRules(), GetSpeciesManager(), GetSupplyManager(), Universe::InitializeSystemGraph(), INVALID_OBJECT_ID, m_current_turn, m_empires, m_galaxy_setup_data, m_networking, m_species_manager, m_supply_manager, m_turn_expired, m_universe, Universe::ObfuscateIDGenerator(), Universe::Objects(), PlayerEmpireID(), ServerNetworking::PlayerIsHost(), Seed(), GalaxySetupData::seed, ServerNetworking::SendMessageAll(), TraceLogger, TurnProgressMessage(), TurnUpdateMessage(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateEmpireObjectVisibilities(), anonymous_namespace{ServerApp.cpp}::UpdateEmpirePolicies(), Universe::UpdateEmpireStaleObjectKnowledge(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireSupply(), Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps(), Universe::UpdateMeterEstimates(), UpdateMonsterTravelRestrictions(), SpeciesManager::UpdatePopulationCounter(), and Universe::UpdateStatRecords().
Referenced by GetGalaxySetupData(), and ProcessingTurn::react().
PreCombatProcessTurns()
void ServerApp::PreCombatProcessTurns ()
Executes player orders, does colonization, does ordered scrapping, does fleet movements, and updates visibility before combats are handled.
References ObjectMap::all(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::CleanUpBombardmentStateInfo(), ClearEmpireTurnOrders(), Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, CreateFleetArrivedAtDestinationSitRep(), DebugLogger, Empires(), ServerNetworking::established_begin(), ServerNetworking::established_end(), GetEmpire(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), m_empires, m_galaxy_setup_data, m_networking, m_species_manager, m_supply_manager, m_turn_sequence, m_universe, Universe::Objects(), PlayerEmpireID(), Universe::ResetAllObjectMeters(), ServerNetworking::SendMessageAll(), TurnPartialUpdateMessage(), TurnProgressMessage(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateEmpireObjectVisibilities(), anonymous_namespace{ServerApp.cpp}::UpdateEmpirePolicies(), Universe::UpdateEmpireStaleObjectKnowledge(), Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps(), and anonymous_namespace{ServerApp.cpp}::UpdateResourceCenterFocusHistoryInfo().
Referenced by GetGalaxySetupData(), and ProcessingTurn::react().
ProcessCombats()
void ServerApp::ProcessCombats ()
Determines which combats will occur, handles running the combats and updating the universe after the results are available.
References anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo(), AutoResolveCombat(), anonymous_namespace{ServerApp.cpp}::BackProjectSystemCombatInfoObjectMeters(), anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps(), CurrentTurn(), DebugLogger, anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), m_empires, m_galaxy_setup_data, m_networking, m_species_manager, m_supply_manager, m_universe, Universe::Objects(), ServerNetworking::SendMessageAll(), to_string(), TraceLogger, TurnProgressMessage(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), and Universe::UpdateEmpireStaleObjectKnowledge().
Referenced by GetGalaxySetupData(), and ProcessingTurn::react().
PushChatMessage()
void ServerApp::PushChatMessage (const std::string & text, const std::string & player_name, std::array< unsigned char, 4 > text_color, const boost::posix_time::ptime & timestamp)
References ErrorLogger, ErrorMessage(), GetApp(), GetPythonChatDir(), PythonCommon::HandleErrorAlreadySet(), PythonBase::Initialize(), PythonCommon::IsPythonRunning(), m_chat_history, m_fsm, m_python_server, Networking(), PythonServer::PutChatHistoryEntity(), ServerNetworking::SendMessageAll(), PythonBase::SetCurrentDir(), and UserStringNop.
Referenced by ServerFSM::EstablishPlayer(), GetGalaxySetupData(), ServerFSM::HandleNonLobbyDisconnection(), MPLobby::react(), WaitingForMPGameJoiners::react(), and MPLobby::ValidateClientLimits().
RemoveEmpireTurn()
void ServerApp::RemoveEmpireTurn (int empire_id) private
Removes an empire from turn processing.
This is most likely called when an empire is eliminated from the game
References m_turn_sequence.
Referenced by CheckForEmpireElimination(), EliminatePlayer(), and GetGalaxySetupData().
RevokeEmpireTurnReadyness()
void ServerApp::RevokeEmpireTurnReadyness (int empire_id)
Revokes turn order's ready state for the given empire.
References GetEmpire().
Referenced by GetGalaxySetupData(), and LoadGameInit().
Run()
void ServerApp::Run () private
initializes app state, then executes main event handler/render loop (Poll())
References DebugLogger, ServerNetworking::HandleNextEvent(), m_io_context, and m_networking.
Referenced by GetGalaxySetupData(), and operator()().
SelectNewHost()
void ServerApp::SelectNewHost () private
Called when the host player has disconnected.
Select a new host player
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), HostIDMessage(), ServerNetworking::HostPlayerID(), Networking::INVALID_PLAYER_ID, m_networking, ServerNetworking::SendMessageAll(), ServerNetworking::SetHostPlayerID(), and UserStringNop.
Referenced by GetGalaxySetupData(), ServerFSM::HandleNonLobbyDisconnection(), and MPLobby::ValidateClientLimits().
SendNewGameStartMessages()
void ServerApp::SendNewGameStartMessages () private
Sends out initial new game state to clients, and signals clients to start first turn.
References DebugLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), GameStartMessage(), GetCombatLogManager(), GetPlayerInfoMap(), GetSpeciesManager(), GetSupplyManager(), m_current_turn, m_empires, m_galaxy_setup_data, m_networking, m_single_player_game, m_universe, and PlayerEmpireID().
Referenced by GetGalaxySetupData(), NewMPGameInit(), and WaitingForSPGameJoiners::react().
SetAIsProcessPriorityToLow()
void ServerApp::SetAIsProcessPriorityToLow (bool set_to_low) private
Sets the priority for all AI processes.
References ErrorLogger, and m_ai_client_processes.
Referenced by CreateAIClients(), GetGalaxySetupData(), WaitingForTurnEnd::react(), and ProcessingTurn::react().
SetEmpireSaveGameData()
void ServerApp::SetEmpireSaveGameData (int empire_id, std::unique_ptr< PlayerSaveGameData > && save_game_data)
Adds save game data includes turn orders for the given empire for the current turn.
save_game_data will be freed when all processing is done for the turn
References m_turn_sequence.
Referenced by GetGalaxySetupData(), and WaitingForTurnEnd::react().
ShutdownTimedoutHandler()
void ServerApp::ShutdownTimedoutHandler (boost::system::error_code error) private
Handle shutdown timeout by killing all ais.
References DebugLogger, and m_fsm.
Referenced by GetGalaxySetupData(), and ShuttingDownServer::ShuttingDownServer().
SignalHandler()
void ServerApp::SignalHandler (const boost::system::error_code & error, int signal_number) private
Called when server process receive termination signal.
References ErrorLogger, and m_fsm.
Referenced by GetGalaxySetupData(), and ServerApp().
StartBackgroundParsing()
void ServerApp::StartBackgroundParsing (const PythonParser & python, std::promise< void > && barrier) override virtual
Launches asynchronous parsing of game content, then starts additional content parsing in the calling thread.
barrier is unblocked when the asynchronous parsing of named value refs is completed, but the synchronous parsing of in the calling thread or the other asynchronous parsing may still be ongoing at that time. Requires python to be initialized.
Reimplemented from IApp.
References ErrorLogger, parse::fleet_plans(), GetResourceDir(), parse::items(), m_universe, parse::monster_fleet_plans(), Universe::SetEmpireStats(), Universe::SetInitiallyUnlockedBuildings(), Universe::SetInitiallyUnlockedFleetPlans(), Universe::SetInitiallyUnlockedItems(), Universe::SetMonsterFleetPlans(), Pending::StartAsyncParsing(), IApp::StartBackgroundParsing(), parse::starting_buildings(), and parse::statistics().
Referenced by GetGalaxySetupData(), and ServerApp().
UpdateCombatLogs()
void ServerApp::UpdateCombatLogs (const Message & msg, PlayerConnectionPtr player_connection)
Send the requested combat logs to the client.
References DebugLogger, DispatchCombatLogsMessage(), ErrorLogger, ExtractRequestCombatLogsMessageData(), GetCombatLogManager(), and CombatLogManager::GetLog().
Referenced by GetGalaxySetupData().
UpdateMonsterTravelRestrictions()
void ServerApp::UpdateMonsterTravelRestrictions ()
Used post combat, to selectively clear the m_arrival_starlane flag of monsters so that they can impose blockades.
References ErrorLogger, ObjectMap::ExistingSystems(), ObjectMap::find(), INVALID_OBJECT_ID, m_universe, and Universe::Objects().
Referenced by GetGalaxySetupData(), and PostCombatProcessTurns().
UpdatePartialOrders()
void ServerApp::UpdatePartialOrders (int empire_id, const OrderSet & added, const std::set< int > & deleted)
Updated empire orders without changes in readiness status.
Removes all deleted orders and insert added orders.
References m_turn_sequence.
Referenced by GetGalaxySetupData(), and WaitingForTurnEnd::react().
UpdateSavePreviews()
void ServerApp::UpdateSavePreviews (const Message & msg, PlayerConnectionPtr player_connection)
References DebugLogger, DispatchSavePreviewsMessage(), ErrorLogger, ExtractRequestSavePreviewsMessageData(), FilenameToPath(), PreviewInformation::folder, GetServerSaveDir(), anonymous_namespace{ServerApp.cpp}::IsInServerSaveDir(), anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories(), LoadSaveGamePreviews(), m_single_player_game, MP_SAVE_FILE_EXTENSION, PreviewInformation::previews, SP_SAVE_FILE_EXTENSION, and PreviewInformation::subdirectories.
Referenced by GetGalaxySetupData(), and HandleMessage().
VerifySPGameAIs()
bool ServerApp::VerifySPGameAIs (const SinglePlayerSetupData & single_player_setup_data)
Return true if single player game AIs are compatible with created universe and are ready to start a new game.
References NewGameInitVerifyJoiners(), and SinglePlayerSetupData::players.
Referenced by GetGalaxySetupData(), and WaitingForSPGameJoiners::react().
Friends And Related Function Documentation
Idle
friend struct Idle friend
MPLobby
friend struct MPLobby friend
PlayingGame
friend struct PlayingGame friend
ProcessingTurn
friend struct ProcessingTurn friend
ServerFSM
friend struct ServerFSM friend
ShuttingDownServer
friend struct ShuttingDownServer friend
WaitingForMPGameJoiners
friend struct WaitingForMPGameJoiners friend
WaitingForSaveData
friend struct WaitingForSaveData friend
WaitingForSPGameJoiners
friend struct WaitingForSPGameJoiners friend
WaitingForTurnEnd
friend struct WaitingForTurnEnd friend
WaitingForTurnEndIdle
friend struct WaitingForTurnEndIdle friend
Member Data Documentation
m_ai_client_processes
std::map<std::string, Process> ServerApp::m_ai_client_processes private
AI client child processes indexed by player name.
Referenced by AddPlayerIntoGame(), CheckForEmpireElimination(), CleanupAIs(), CreateAIClients(), WaitingForMPGameJoiners::react(), PlayingGame::react(), ShuttingDownServer::react(), SetAIsProcessPriorityToLow(), ShuttingDownServer::ShuttingDownServer(), and MPLobby::ValidateClientLimits().
m_chat_history
boost::circular_buffer<ChatHistoryEntity> ServerApp::m_chat_history private
Stored last chat messages.
Referenced by GetChatHistory(), LoadChatHistory(), and PushChatMessage().
m_current_turn
int ServerApp::m_current_turn = INVALID_GAME_TURN private
current turn number
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), AllOrdersReceived(), CurrentTurn(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), WaitingForTurnEnd::react(), and SendNewGameStartMessages().
m_empires
EmpireManager ServerApp::m_empires private
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), Empires(), GenerateUniverse(), GetEmpire(), IsHaveWinner(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), PreCombatProcessTurns(), ProcessCombats(), and SendNewGameStartMessages().
m_fsm
ServerFSM* ServerApp::m_fsm private
Referenced by ExecuteScriptedTurnEvents(), FillListPlayers(), GenerateUniverse(), GetPlayerDelegation(), HandleMessage(), ServerFSM::HandleNonLobbyDisconnection(), HandleNonPlayerMessage(), HandleShutdownMessage(), IsAuthRequiredOrFillRoles(), IsAuthSuccessAndFillRoles(), LoadChatHistory(), PlayerDisconnected(), PushChatMessage(), PlayingGame::react(), ServerApp(), ShutdownTimedoutHandler(), SignalHandler(), and ~ServerApp().
m_galaxy_setup_data
GalaxySetupData ServerApp::m_galaxy_setup_data private
stored setup data for the game currently being played
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), GenerateUniverse(), GetGalaxySetupData(), ServerFSM::HandleNonLobbyDisconnection(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), PreCombatProcessTurns(), ProcessCombats(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), SendNewGameStartMessages(), and ServerApp().
m_io_context
boost::asio::io_context ServerApp::m_io_context private
Referenced by Run().
m_networking
ServerNetworking ServerApp::m_networking private
Referenced by AddPlayerIntoGame(), CheckForEmpireElimination(), CleanupAIs(), CreateAIClients(), EliminatePlayer(), ServerFSM::EstablishPlayer(), MPLobby::EstablishPlayer(), GetPlayerClientType(), GetPlayerInfoMap(), HandleDiplomaticMessageChange(), HandleDiplomaticStatusChange(), HandleLoggerConfig(), HandleMessage(), ServerFSM::HandleNonLobbyDisconnection(), HandleNonPlayerMessage(), HandleShutdownMessage(), IsAvailableName(), IsLocalHumanPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), LoadGameInit(), LoadMPGameInit(), LoadSPGameInit(), Networking(), NewGameInitConcurrentWithJoiners(), NewGameInitVerifyJoiners(), NewMPGameInit(), PostCombatProcessTurns(), PreCombatProcessTurns(), ProcessCombats(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), ShuttingDownServer::react(), Run(), SelectNewHost(), SendNewGameStartMessages(), ShuttingDownServer::ShuttingDownServer(), ServerFSM::UpdateIngameLobby(), MPLobby::ValidateClientLimits(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
m_player_empire_ids
std::map<int, int> ServerApp::m_player_empire_ids private
map from player id to empire id that the player controls.
Referenced by AddPlayerIntoGame(), DropPlayerEmpireLink(), EliminatePlayer(), EmpirePlayerID(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), and PlayerEmpireID().
m_python_server
PythonServer ServerApp::m_python_server private
Referenced by ExecuteScriptedTurnEvents(), FillListPlayers(), GenerateUniverse(), GetPlayerDelegation(), InitializePython(), IsAuthRequiredOrFillRoles(), IsAuthSuccessAndFillRoles(), LoadChatHistory(), PushChatMessage(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), ServerApp(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
m_signals
boost::asio::signal_set ServerApp::m_signals private
Referenced by ServerApp().
m_single_player_game
bool ServerApp::m_single_player_game = false private
true when the game being played is single-player
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), CheckForEmpireElimination(), ServerFSM::HandleNonLobbyDisconnection(), LoadGameInit(), Idle::react(), PlayingGame::react(), WaitingForTurnEnd::react(), SendNewGameStartMessages(), and UpdateSavePreviews().
m_species_manager
SpeciesManager ServerApp::m_species_manager private
Referenced by GenerateUniverse(), GetSpecies(), GetSpeciesManager(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), PreCombatProcessTurns(), and ProcessCombats().
m_supply_manager
SupplyManager ServerApp::m_supply_manager private
Referenced by GenerateUniverse(), GetSupplyManager(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), PreCombatProcessTurns(), and ProcessCombats().
m_turn_expired
bool ServerApp::m_turn_expired = false private
true when turn exceeds its timeout
Referenced by AllOrdersReceived(), ExpireTurn(), IsTurnExpired(), NewGameInitConcurrentWithJoiners(), and PostCombatProcessTurns().
m_turn_sequence
std::map<int, std::unique_ptr<PlayerSaveGameData> > ServerApp::m_turn_sequence private
Turn sequence map is used for turn processing.
Each empire is added at the start of a game or reload and then the map maintains OrderSets for that turn. The map contains pointer to orders from empire with ready state which should be true to advance turn.
Referenced by AddEmpireTurn(), AddPlayerIntoGame(), AllOrdersReceived(), ClearEmpireTurnOrders(), GetPlayerSaveGameData(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PreCombatProcessTurns(), RemoveEmpireTurn(), SetEmpireSaveGameData(), and UpdatePartialOrders().
m_universe
Universe ServerApp::m_universe private
Referenced by AddObserverPlayerIntoGame(), AddPlayerIntoGame(), CheckForEmpireElimination(), EliminatePlayer(), EmpireKnownObjects(), GenerateUniverse(), GetUniverse(), LoadGameInit(), NewGameInitConcurrentWithJoiners(), PostCombatProcessTurns(), PreCombatProcessTurns(), ProcessCombats(), SendNewGameStartMessages(), StartBackgroundParsing(), and UpdateMonsterTravelRestrictions().
The documentation for this class was generated from the following files:
ServerApp.h
ServerApp.cpp