FreeOrion: CensusRowPanel Class Reference
CensusRowPanel Class Reference
Public Member Functions
CensusRowPanel (GG::X w, GG::Y h, const std::string &name, double census_val, bool show_icon)
void CompleteConstruction () override
void Render () override
Private Member Functions
void DoLayout ()
void InitBuffer ()
Private Attributes
GG::GL2DVertexBuffer m_buffer
std::shared_ptr< GG::Label > m_census_val
std::shared_ptr< GG::StaticGraphic > m_icon
std::shared_ptr< GG::Label > m_name
bool m_show_icon
Constructor & Destructor Documentation
CensusRowPanel()
CensusRowPanel::CensusRowPanel (GG::X w, GG::Y h, const std::string & name, double census_val, bool show_icon) inline
References DoubleToString(), m_census_val, m_icon, m_name, m_show_icon, ClientUI::SpeciesIcon(), and UserString().
Member Function Documentation
CompleteConstruction()
void CensusRowPanel::CompleteConstruction () inline override
References DoLayout(), m_census_val, m_icon, m_name, and m_show_icon.
DoLayout()
void CensusRowPanel::DoLayout () inline private
References anonymous_namespace{CensusBrowseWnd.cpp}::EDGE_PAD(), InitBuffer(), m_census_val, m_icon, m_name, m_show_icon, anonymous_namespace{CensusBrowseWnd.cpp}::MeterIconSize(), and ClientUI::Pts().
Referenced by CompleteConstruction().
InitBuffer()
void CensusRowPanel::InitBuffer () inline private
References m_buffer.
Referenced by DoLayout().
Render()
void CensusRowPanel::Render () inline override
References m_buffer, ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
Member Data Documentation
m_buffer
GG::GL2DVertexBuffer CensusRowPanel::m_buffer private
Referenced by InitBuffer(), and Render().
m_census_val
std::shared_ptr<GG::Label> CensusRowPanel::m_census_val private
Referenced by CensusRowPanel(), CompleteConstruction(), and DoLayout().
m_icon
std::shared_ptr<GG::StaticGraphic> CensusRowPanel::m_icon private
Referenced by CensusRowPanel(), CompleteConstruction(), and DoLayout().
m_name
std::shared_ptr<GG::Label> CensusRowPanel::m_name private
Referenced by CensusRowPanel(), CompleteConstruction(), and DoLayout().
m_show_icon
bool CensusRowPanel::m_show_icon private
Referenced by CensusRowPanel(), CompleteConstruction(), and DoLayout().
The documentation for this class was generated from the following file:
CensusBrowseWnd.cpp