FreeOrion: SitRepEntry Class Reference
SitRepEntry Class Reference
Represents a situation report entry for a significant game event.
#include <SitRepEntry.h>
Public Member Functions
SitRepEntry ()
SitRepEntry (const char *template_string, int turn, const char *icon, const char *label, bool stringtable_lookup)
SitRepEntry (std::string &&template_string, int turn, std::string &&icon, std::string &&label, bool stringtable_lookup)
std::string Dump () const
int GetDataIDNumber (const std::string &tag) const
const std::string & GetDataString (const std::string &tag) const
const std::string & GetIcon () const
const std::string & GetLabelString () const
int GetTurn () const
Public Member Functions inherited from VarText
VarText ()
Create a VarText instance with an empty m_template_string.
VarText (std::string template_string, bool stringtable_lookup=true)
Create a VarText instance from the given template_string.
void AddVariable (const std::string &tag, const std::string &data)
Assign data to a given tag.
void AddVariable (const std::string &tag, std::string &&data)
Assign data to a given tag.
void AddVariables (std::vector< std::pair< std::string, std::string >> &&data)
Assign data as tags.
bool GetStringtableLookupFlag () const
Return the m_stringtable_lookup_flag.
const std::string & GetTemplateString () const
Return the m_template_string.
const std::string & GetText () const
Return the text generated after substituting all variables.
std::vector< std::string > GetVariableTags () const
Return the variables available for substitution.
void SetTemplateString (std::string template_string, bool stringtable_lookup=true)
Set the m_template_string to the given template_string.
bool Validate () const
Return if the text substitution was successful.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_icon
std::string m_label
int m_turn
Friends
class boost::serialization::access
Additional Inherited Members
Static Public Attributes inherited from VarText
static const std::string TEXT_TAG = "text"
Variable value is a StringTable key.
static const std::string RAW_TEXT_TAG = "rawtext"
Variable value is a literal string.
static const std::string PLANET_ID_TAG = "planet"
Variable value is a Planet::ID().
static const std::string SYSTEM_ID_TAG = "system"
Variable value is a System::ID().
static const std::string SHIP_ID_TAG = "ship"
Variable value is a Ship::ID().
static const std::string FLEET_ID_TAG = "fleet"
Variable value is a Fleet::ID().
static const std::string BUILDING_ID_TAG = "building"
Variable value is a Building::ID().
static const std::string FIELD_ID_TAG = "field"
Variable value is a Field::ID().
static const std::string COMBAT_ID_TAG = "combat"
Variable value represents a CombatLog.
static const std::string EMPIRE_ID_TAG = "empire"
Variable value is an Empire::EmpireID().
static const std::string DESIGN_ID_TAG = "shipdesign"
Variable value is a ShipDesign::ID().
static const std::string PREDEFINED_DESIGN_TAG = "predefinedshipdesign"
Variable value is a ShipDesign::ID() of a predefined ShipDesign.
static const std::string TECH_TAG = "tech"
Variable value is a Tech::Name().
static const std::string POLICY_TAG = "policy"
Variable value is a Policy::Name().
static const std::string BUILDING_TYPE_TAG = "buildingtype"
Variable value is a BuildingType::Name().
static const std::string SPECIAL_TAG = "special"
Variable value is a Special::Name().
static const std::string SHIP_HULL_TAG = "shiphull"
Variable value is a ShipHull::Name().
static const std::string SHIP_PART_TAG = "shippart"
Variable value is a ShipPart::Name().
static const std::string SPECIES_TAG = "species"
Variable value is a Species::Name().
static const std::string FIELD_TYPE_TAG = "fieldtype"
Variable value is a FieldType::Name().
static const std::string METER_TYPE_TAG = "metertype"
Variable value is a predefined MeterType string representation.
static const std::string FOCS_VALUE_TAG = "value"
Variable value is the name of a registed ValueRef.
Protected Member Functions inherited from VarText
void GenerateVarText () const
Combines the template with the variables contained in object to create a string with variables replaced with text.
Protected Attributes inherited from VarText
bool m_stringtable_lookup_flag = false
If true the m_template_string will be looked up in the stringtable prior to substitution for variables.
std::string m_template_string
The template text used by this VarText, into which variables are substituted to render the text as user-readable.
std::string m_text
m_template_string with applied m_variables substitute.
bool m_validated = false
True if the m_template_string stubstitution was executed without errors.
std::map< std::string, std::string > m_variables
Maps variable tags into values, which are used during text substitution.
Detailed Description
Represents a situation report entry for a significant game event.
Constructor & Destructor Documentation
SitRepEntry() [1/3]
SitRepEntry::SitRepEntry ()
Referenced by CreateCombatDamagedObjectSitRep(), and CreateCombatDestroyedObjectSitRep().
SitRepEntry() [2/3]
SitRepEntry::SitRepEntry (const char * template_string, int turn, const char * icon, const char * label, bool stringtable_lookup)
SitRepEntry() [3/3]
SitRepEntry::SitRepEntry (std::string && template_string, int turn, std::string && icon, std::string && label, bool stringtable_lookup)
Member Function Documentation
Dump()
std::string SitRepEntry::Dump () const
References m_icon, m_label, VarText::m_template_string, m_turn, VarText::m_variables, and to_string().
GetDataIDNumber()
int SitRepEntry::GetDataIDNumber (const std::string & tag) const
References VarText::m_variables.
Referenced by FreeOrionPython::WrapEmpire().
GetDataString()
const std::string & SitRepEntry::GetDataString (const std::string & tag) const
References anonymous_namespace{CombatSystem.cpp}::EMPTY_STRING, and VarText::m_variables.
Referenced by FreeOrionPython::WrapEmpire().
GetIcon()
const std::string& SitRepEntry::GetIcon () const inline
GetLabelString()
const std::string& SitRepEntry::GetLabelString () const inline
References Effect::Dump().
Referenced by SitRepPanel::DismissalMenu(), and SitRepPanel::IsSitRepInvalid().
GetTurn()
int SitRepEntry::GetTurn () const inline
Referenced by SitRepPanel::DismissalMenu(), SitRepPanel::IgnoreSitRep(), SitRepPanel::IsSitRepInvalid(), and FreeOrionPython::WrapEmpire().
serialize()
template<typename Archive > void SitRepEntry::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_icon
std::string SitRepEntry::m_icon private
Referenced by Dump().
m_label
std::string SitRepEntry::m_label private
Referenced by Dump().
m_turn
int SitRepEntry::m_turn private
Referenced by Dump().
The documentation for this class was generated from the following files:
SitRepEntry.h
SitRepEntry.cpp