FreeOrion: BarSizer Class Reference
BarSizer Class Reference
Public Types
typedef std::map< int, CombatSummary > CombatSummaryMap
Public Member Functions
BarSizer (const CombatSummaryMap &combat_summaries, const GG::Pt &available_size)
GG::X CalculateAliveWidth (const ParticipantSummary &participant, const GG::Pt &total_space) const
GG::X CalculateDeadWidth (const ParticipantSummary &participant, const GG::Pt &total_space) const
bool Get (const std::string &option) const
GG::Pt GetBarSize (const ParticipantSummary &participant, const GG::X &label_margin) const
GG::Pt GetMinSize () const
GG::Pt GetSideBarSize (const Empire *empire) const
void Set (const std::string &option, bool value)
void SetAvailableSize (GG::Pt size)
Private Member Functions
GG::Pt GetSideBarSize (int empire_id) const
Private Attributes
GG::Y m_available_participant_bar_height
GG::Pt m_available_side_bar_space
GG::Pt m_available_space
float m_max_total_max_health
int m_max_units_on_a_side
float m_min_of_max_max_healths
float m_sum_of_max_max_healths
const CombatSummaryMap & m_summaries
Member Typedef Documentation
CombatSummaryMap
typedef std::map<int, CombatSummary> BarSizer::CombatSummaryMap
Constructor & Destructor Documentation
BarSizer()
BarSizer::BarSizer (const CombatSummaryMap & combat_summaries, const GG::Pt & available_size) inline
References m_available_space, m_max_total_max_health, m_max_units_on_a_side, m_min_of_max_max_healths, m_sum_of_max_max_healths, and SetAvailableSize().
Member Function Documentation
CalculateAliveWidth()
GG::X BarSizer::CalculateAliveWidth (const ParticipantSummary & participant, const GG::Pt & total_space) const inline
References ParticipantSummary::current_health, Get(), m_max_total_max_health, m_max_units_on_a_side, and anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_WIDTH_PROPORTIONAL.
Referenced by GetBarSize().
CalculateDeadWidth()
GG::X BarSizer::CalculateDeadWidth (const ParticipantSummary & participant, const GG::Pt & total_space) const inline
References Get(), m_max_total_max_health, m_max_units_on_a_side, ParticipantSummary::max_health, and anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_WIDTH_PROPORTIONAL.
Referenced by GetBarSize().
Get()
bool BarSizer::Get (const std::string & option) const inline
References OptionsDB::Get(), GetOptionsDB(), and anonymous_namespace{GraphicalSummary.cpp}::OPTIONS_ROOT.
Referenced by CalculateAliveWidth(), CalculateDeadWidth(), GetBarSize(), GetMinSize(), and GetSideBarSize().
GetBarSize()
GG::Pt BarSizer::GetBarSize (const ParticipantSummary & participant, const GG::X & label_margin) const inline
References anonymous_namespace{GraphicalSummary.cpp}::AdjustForAxes(), CalculateAliveWidth(), CalculateDeadWidth(), ParticipantSummary::current_health, ParticipantSummary::empire_id, ErrorLogger, Get(), GetSideBarSize(), m_summaries, ParticipantSummary::max_health, CombatSummary::max_max_health, ParticipantSummary::object_id, and anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEIGHT_PROPORTIONAL.
GetMinSize()
GG::Pt BarSizer::GetMinSize () const inline
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT(), Get(), m_min_of_max_max_healths, m_sum_of_max_max_healths, m_summaries, anonymous_namespace{GraphicalSummary.cpp}::MIN_PARTICIPANT_BAR_HEIGHT, anonymous_namespace{GraphicalSummary.cpp}::MIN_SIDE_BAR_WIDTH, anonymous_namespace{GraphicalSummary.cpp}::SIDE_BAR_UP_MARGIN(), anonymous_namespace{GraphicalSummary.cpp}::SIDE_BOX_MARGIN(), anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_GRAPH_HEIGHT_PROPORTIONAL, and anonymous_namespace{GraphicalSummary.cpp}::X_AXIS_LABEL_MARGIN().
GetSideBarSize() [1/2]
GG::Pt BarSizer::GetSideBarSize (const Empire * empire) const inline
References ALL_EMPIRES, and Empire::EmpireID().
Referenced by GetBarSize().
GetSideBarSize() [2/2]
GG::Pt BarSizer::GetSideBarSize (int empire_id) const inline private
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT(), Get(), m_sum_of_max_max_healths, anonymous_namespace{GraphicalSummary.cpp}::MIN_SIDE_BAR_HEIGHT, anonymous_namespace{GraphicalSummary.cpp}::MIN_SIDE_BAR_WIDTH, anonymous_namespace{GraphicalSummary.cpp}::SIDE_BAR_UP_MARGIN(), anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_GRAPH_HEIGHT_PROPORTIONAL, and anonymous_namespace{GraphicalSummary.cpp}::X_AXIS_LABEL_MARGIN().
Set()
void BarSizer::Set (const std::string & option, bool value) inline
References OptionsDB::Commit(), GetOptionsDB(), anonymous_namespace{GraphicalSummary.cpp}::OPTIONS_ROOT, and OptionsDB::Set().
SetAvailableSize()
void BarSizer::SetAvailableSize (GG::Pt size) inline
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT(), anonymous_namespace{GraphicalSummary.cpp}::BEVEL_MARGIN_X(), m_available_participant_bar_height, m_available_side_bar_space, m_available_space, m_summaries, anonymous_namespace{GraphicalSummary.cpp}::SIDE_BAR_UP_MARGIN(), anonymous_namespace{GraphicalSummary.cpp}::SIDE_BOX_MARGIN(), and anonymous_namespace{GraphicalSummary.cpp}::X_AXIS_LABEL_MARGIN().
Referenced by BarSizer().
Member Data Documentation
m_available_participant_bar_height
GG::Y BarSizer::m_available_participant_bar_height private
Referenced by SetAvailableSize().
m_available_side_bar_space
GG::Pt BarSizer::m_available_side_bar_space private
Referenced by SetAvailableSize().
m_available_space
GG::Pt BarSizer::m_available_space private
Referenced by BarSizer(), and SetAvailableSize().
m_max_total_max_health
float BarSizer::m_max_total_max_health private
Referenced by BarSizer(), CalculateAliveWidth(), and CalculateDeadWidth().
m_max_units_on_a_side
int BarSizer::m_max_units_on_a_side private
Referenced by BarSizer(), CalculateAliveWidth(), and CalculateDeadWidth().
m_min_of_max_max_healths
float BarSizer::m_min_of_max_max_healths private
Referenced by BarSizer(), and GetMinSize().
m_sum_of_max_max_healths
float BarSizer::m_sum_of_max_max_healths private
Referenced by BarSizer(), GetMinSize(), and GetSideBarSize().
m_summaries
const CombatSummaryMap& BarSizer::m_summaries private
Referenced by GetBarSize(), GetMinSize(), and SetAvailableSize().
The documentation for this class was generated from the following file:
GraphicalSummary.cpp