FreeOrion: PopulationPanel Class Reference
PopulationPanel Class Reference
Shows population with meter bars.
#include <PopulationPanel.h>
Public Member Functions
void CompleteConstruction () override
Structors
PopulationPanel (GG::X w, int object_id)
~PopulationPanel ()
Accessors
int PopCenterID () const
Public Member Functions inherited from AccordionPanel
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
void Render () override
Sets the interior color of the box.
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Sets the interior color of the box.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Sets the interior color of the box.
void SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
void SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
Private Member Functions
void ExpandCollapseButtonPressed ()
toggles panel expanded or collapsed
Private Attributes
std::vector< std::pair< MeterType, std::shared_ptr< StatisticIcon > > > m_meter_stats
Icons for the associated meter type.
std::shared_ptr< MultiIconValueIndicator > m_multi_icon_value_indicator
textually / numerically indicates population
std::shared_ptr< MultiMeterStatusBar > m_multi_meter_status_bar
graphically indicates meter values
int m_popcenter_id = INVALID_OBJECT_ID
object id for the PopulationCenter that this panel displays
Static Private Attributes
static std::map< int, bool > s_expanded_map
map indexed by popcenter ID indicating whether the PopulationPanel for each object is expanded (true) or collapsed (false)
Mutators
void PreRender () override
expands or collapses panel to show details or just summary info
void ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
void Update ()
updates indicators with values of associated object.
void Refresh ()
updates, redoes layout, resizes indicator
void DoLayout () override
resizes panel and positions widgets
Additional Inherited Members
Public Types inherited from AccordionPanel
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Public Attributes inherited from AccordionPanel
ExpandCollapseSignalType ExpandCollapseSignal
Protected Member Functions inherited from AccordionPanel
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Protected Attributes inherited from AccordionPanel
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin = 1
The number of pixels between the expansion button and the client area.
bool m_collapsed = true
std::shared_ptr< GG::Button > m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
GG::Clr m_interior_color
bool m_is_left = false
Is expand button on the left?
Detailed Description
Shows population with meter bars.
Constructor & Destructor Documentation
PopulationPanel()
PopulationPanel::PopulationPanel (GG::X w, int object_id)
~PopulationPanel()
PopulationPanel::~PopulationPanel ()
Member Function Documentation
CompleteConstruction()
void PopulationPanel::CompleteConstruction () override
References AssociatedMeterType(), AccordionPanel::CompleteConstruction(), anonymous_namespace{PopulationPanel.cpp}::EDGE_PAD(), ErrorLogger, ExpandCollapseButtonPressed(), FlexibleFormat(), ObjectMap::get(), ClientUI::GetClientUI(), AccordionPanel::m_expand_button, m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_popcenter_id, METER_CONSTRUCTION, METER_HAPPINESS, METER_POPULATION, ClientUI::MeterIcon(), anonymous_namespace{PopulationPanel.cpp}::MeterIconSize(), Objects(), Refresh(), s_expanded_map, anonymous_namespace{ServerWrapper.cpp}::SetName(), ClientUI::SpeciesIcon(), PopCenter::SpeciesName(), UserString(), ClientUI::ZoomToMeterTypeArticle(), and ClientUI::ZoomToSpecies().
DoLayout()
void PopulationPanel::DoLayout () override protected virtual
resizes panel and positions widgets
Reimplemented from AccordionPanel.
References AccordionPanel::DoLayout(), anonymous_namespace{PopulationPanel.cpp}::EDGE_PAD(), AccordionPanel::m_expand_button, m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_popcenter_id, anonymous_namespace{PopulationPanel.cpp}::MeterIconSize(), s_expanded_map, and AccordionPanel::SetCollapsed().
Referenced by ExpandCollapse(), PopCenterID(), and PreRender().
ExpandCollapse()
void PopulationPanel::ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
References DoLayout(), m_popcenter_id, and s_expanded_map.
Referenced by ExpandCollapseButtonPressed(), and PopCenterID().
ExpandCollapseButtonPressed()
void PopulationPanel::ExpandCollapseButtonPressed () private
toggles panel expanded or collapsed
References ExpandCollapse(), m_popcenter_id, and s_expanded_map.
Referenced by CompleteConstruction(), and PopCenterID().
PopCenterID()
int PopulationPanel::PopCenterID () const inline
References DoLayout(), ExpandCollapse(), ExpandCollapseButtonPressed(), m_popcenter_id, PreRender(), Refresh(), and Update().
PreRender()
void PopulationPanel::PreRender () override
expands or collapses panel to show details or just summary info
References DoLayout(), and Update().
Referenced by PopCenterID().
Refresh()
void PopulationPanel::Refresh ()
updates, redoes layout, resizes indicator
References m_meter_stats.
Referenced by CompleteConstruction(), and PopCenterID().
Update()
void PopulationPanel::Update ()
updates indicators with values of associated object.
Does not do layout and resizing.
References AssociatedMeterType(), ErrorLogger, ObjectMap::get(), m_meter_stats, m_multi_icon_value_indicator, m_multi_meter_status_bar, m_popcenter_id, and Objects().
Referenced by PopCenterID(), and PreRender().
Member Data Documentation
m_meter_stats
std::vector<std::pair<MeterType, std::shared_ptr<StatisticIcon> > > PopulationPanel::m_meter_stats private
Icons for the associated meter type.
Referenced by CompleteConstruction(), DoLayout(), Refresh(), and Update().
m_multi_icon_value_indicator
std::shared_ptr<MultiIconValueIndicator> PopulationPanel::m_multi_icon_value_indicator private
textually / numerically indicates population
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_multi_meter_status_bar
std::shared_ptr<MultiMeterStatusBar> PopulationPanel::m_multi_meter_status_bar private
graphically indicates meter values
Referenced by CompleteConstruction(), DoLayout(), and Update().
m_popcenter_id
int PopulationPanel::m_popcenter_id = INVALID_OBJECT_ID private
object id for the PopulationCenter that this panel displays
Referenced by CompleteConstruction(), DoLayout(), ExpandCollapse(), ExpandCollapseButtonPressed(), PopCenterID(), and Update().
s_expanded_map
std::map< int, bool > PopulationPanel::s_expanded_map static private
map indexed by popcenter ID indicating whether the PopulationPanel for each object is expanded (true) or collapsed (false)
Referenced by CompleteConstruction(), DoLayout(), ExpandCollapse(), and ExpandCollapseButtonPressed().
The documentation for this class was generated from the following files:
PopulationPanel.h
PopulationPanel.cpp