FreeOrion: anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem Class Reference
anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem Class Reference
Used by GetEffectsAndTargets to process a vector of effects groups.
Classes
struct ConditionCache
Public Member Functions
StoreTargetsAndCausesOfEffectsGroupsWorkItem (const std::shared_ptr< Effect::EffectsGroup > &the_effects_group, const std::vector< std::shared_ptr< const UniverseObject >> &the_sources, EffectsCauseType the_effect_cause_type, const std::string &the_specific_cause_name, Effect::TargetSet &the_target_objects, Effect::TargetsCauses &the_targets_causes, std::map< int, std::shared_ptr< ConditionCache >> &the_source_cached_condition_matches, ConditionCache &the_invariant_cached_condition_matches, boost::shared_mutex &the_global_mutex)
std::string GenerateReport () const
Return a report of that state of this work item.
void operator() ()
Static Private Member Functions
static Effect::TargetSet & GetConditionMatches (const Condition::ConditionBase *cond, ConditionCache &cached_condition_matches, std::shared_ptr< const UniverseObject > source, const ScriptingContext &source_context, Effect::TargetSet &target_objects, std::string &match_log, const std::string &specific_cause_name)
Private Attributes
EffectsCauseType m_effect_cause_type
std::shared_ptr< Effect::EffectsGroup > m_effects_group
boost::shared_mutex * m_global_mutex
ConditionCache * m_invariant_cached_condition_matches
std::map< int, std::shared_ptr< ConditionCache > > * m_source_cached_condition_matches
const std::vector< std::shared_ptr< const UniverseObject > > * m_sources
const std::string m_specific_cause_name
Effect::TargetSet * m_target_objects
Effect::TargetsCauses * m_targets_causes
Detailed Description
Used by GetEffectsAndTargets to process a vector of effects groups.
Stores target set of specified effects_groups and source_object_id in targets_causes NOTE: this method will modify target_objects temporarily, but restore its contents before returning. This is a calleable class instead of an ordinary method so that we can use it as work item in parallel scheduling.
Constructor & Destructor Documentation
StoreTargetsAndCausesOfEffectsGroupsWorkItem()
anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::StoreTargetsAndCausesOfEffectsGroupsWorkItem (const std::shared_ptr< Effect::EffectsGroup > & the_effects_group, const std::vector< std::shared_ptr< const UniverseObject >> & the_sources, EffectsCauseType the_effect_cause_type, const std::string & the_specific_cause_name, Effect::TargetSet & the_target_objects, Effect::TargetsCauses & the_targets_causes, std::map< int, std::shared_ptr< ConditionCache >> & the_source_cached_condition_matches, ConditionCache & the_invariant_cached_condition_matches, boost::shared_mutex & the_global_mutex)
Referenced by Universe::GetEffectsAndTargets().
Member Function Documentation
GenerateReport()
std::string anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GenerateReport () const
Return a report of that state of this work item.
References m_effects_group, m_global_mutex, m_sources, m_specific_cause_name, and to_string().
Referenced by operator()().
GetConditionMatches()
Effect::TargetSet & anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GetConditionMatches (const Condition::ConditionBase * cond, StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache & cached_condition_matches, std::shared_ptr< const UniverseObject > source, const ScriptingContext & source_context, Effect::TargetSet & target_objects, std::string & match_log, const std::string & specific_cause_name) static private
References Condition::ConditionBase::Dump(), anonymous_namespace{Universe.cpp}::EMPTY_TARGET_SET, Condition::ConditionBase::Eval(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::Find(), INVALID_OBJECT_ID, anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::MarkComplete(), to_string(), and TraceLogger.
Referenced by operator()().
operator()()
void anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator() ()
References GenerateReport(), GetConditionMatches(), INVALID_OBJECT_ID, anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::LockShared(), m_effect_cause_type, m_effects_group, m_global_mutex, m_invariant_cached_condition_matches, m_sources, m_specific_cause_name, m_target_objects, m_targets_causes, to_string(), and TraceLogger.
Member Data Documentation
m_effect_cause_type
EffectsCauseType anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_effect_cause_type private
Referenced by operator()().
m_effects_group
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_effects_group private
Referenced by GenerateReport(), and operator()().
m_global_mutex
boost::shared_mutex* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_global_mutex private
Referenced by GenerateReport(), and operator()().
m_invariant_cached_condition_matches
ConditionCache* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_invariant_cached_condition_matches private
Referenced by operator()().
m_source_cached_condition_matches
std::map<int, std::shared_ptr<ConditionCache> >* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_source_cached_condition_matches private
m_sources
const std::vector<std::shared_ptr<const UniverseObject> >* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_sources private
Referenced by GenerateReport(), and operator()().
m_specific_cause_name
const std::string anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_specific_cause_name private
Referenced by GenerateReport(), and operator()().
m_target_objects
Effect::TargetSet* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_target_objects private
Referenced by operator()().
m_targets_causes
Effect::TargetsCauses* anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::m_targets_causes private
Referenced by operator()().
The documentation for this class was generated from the following file:
Universe.cpp