FreeOrion: BuildingsPanel Class Reference
BuildingsPanel Class Reference
Contains various BuildingIndicator to represent buildings on a planet.
#include <BuildingsPanel.h>
Public Member Functions
void CompleteConstruction () override
Structors
BuildingsPanel (GG::X w, int columns, int planet_id)
~BuildingsPanel ()
Accessors
int PlanetID () const
Public Member Functions inherited from AccordionPanel
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
void Render () override
Sets the interior color of the box.
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Sets the interior color of the box.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Sets the interior color of the box.
void SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
void SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
Public Attributes
boost::signals2::signal< void(int)> BuildingRightClickedSignal
Public Attributes inherited from AccordionPanel
ExpandCollapseSignalType ExpandCollapseSignal
Private Member Functions
void ExpandCollapseButtonPressed ()
toggles panel expanded or collapsed
Private Attributes
std::vector< std::shared_ptr< BuildingIndicator > > m_building_indicators
int m_columns
number of columns in which to display building indicators
int m_planet_id
object id for the Planet whose buildings this panel displays
Static Private Attributes
static std::map< int, bool > s_expanded_map
map indexed by planet ID indicating whether the BuildingsPanel for each object is expanded (true) or collapsed (false)
Mutators
void PreRender () override
updates, redoes layout, resizes indicator
void Refresh ()
updates, redoes layout, resizes indicator
void ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via this panel.
void DoLayout () override
resizes panel and positions widgets
void Update ()
updates indicators with values of associated object.
void RefreshImpl ()
updates, redoes layout, resizes indicator
Additional Inherited Members
Public Types inherited from AccordionPanel
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Protected Member Functions inherited from AccordionPanel
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Protected Attributes inherited from AccordionPanel
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin = 1
The number of pixels between the expansion button and the client area.
bool m_collapsed = true
std::shared_ptr< GG::Button > m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
GG::Clr m_interior_color
bool m_is_left = false
Is expand button on the left?
Detailed Description
Contains various BuildingIndicator to represent buildings on a planet.
Constructor & Destructor Documentation
BuildingsPanel::BuildingsPanel (GG::X w, int columns, int planet_id)
BuildingsPanel::~BuildingsPanel ()
Member Function Documentation
void BuildingsPanel::CompleteConstruction () override
References AccordionPanel::CompleteConstruction(), ErrorLogger, ExpandCollapseButtonPressed(), GetEmpire(), GetUniverseObject(), m_columns, AccordionPanel::m_expand_button, m_planet_id, ProductionQueue::ProductionQueueChangedSignal, and anonymous_namespace{ServerWrapper.cpp}::SetName().
void BuildingsPanel::DoLayout () override protected virtual
resizes panel and positions widgets
Reimplemented from AccordionPanel.
References AccordionPanel::DoLayout(), m_building_indicators, m_columns, AccordionPanel::m_expand_button, m_planet_id, anonymous_namespace{BuildingsPanel.cpp}::MeterIconSize(), s_expanded_map, BuildingIndicator::s_scanline_shader, and AccordionPanel::SetCollapsed().
Referenced by ExpandCollapse(), and RefreshImpl().
void BuildingsPanel::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this panel.
References m_building_indicators.
Referenced by PlanetID().
void BuildingsPanel::ExpandCollapse (bool expanded)
expands or collapses panel to show details or just summary info
References DoLayout(), m_planet_id, and s_expanded_map.
Referenced by ExpandCollapseButtonPressed(), and PlanetID().
void BuildingsPanel::ExpandCollapseButtonPressed () private
toggles panel expanded or collapsed
References ExpandCollapse(), m_planet_id, and s_expanded_map.
Referenced by CompleteConstruction().
int BuildingsPanel::PlanetID () const inline
References EnableOrderIssuing(), ExpandCollapse(), m_planet_id, PreRender(), and Refresh().
void BuildingsPanel::PreRender () override
updates, redoes layout, resizes indicator
References RefreshImpl().
Referenced by PlanetID().
void BuildingsPanel::Refresh ()
updates, redoes layout, resizes indicator
Referenced by PlanetID().
void BuildingsPanel::RefreshImpl () protected
updates, redoes layout, resizes indicator
References DoLayout(), and Update().
Referenced by PreRender().
void BuildingsPanel::Update () protected
updates indicators with values of associated object.
Does not do layout and resizing.
References BT_BUILDING, BuildingRightClickedSignal, ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), ErrorLogger, HumanClientApp::GetApp(), GetBuilding(), GetEmpire(), GetPlanet(), Empire::GetProductionQueue(), GetUniverse(), m_building_indicators, m_columns, m_planet_id, Empire::ProductionCostAndTime(), and Empire::ProductionStatus().
Referenced by RefreshImpl().
Member Data Documentation
boost::signals2::signal<void (int)> BuildingsPanel::BuildingRightClickedSignal mutable
Referenced by Update().
std::vector<std::shared_ptr<BuildingIndicator> > BuildingsPanel::m_building_indicators private
Referenced by DoLayout(), EnableOrderIssuing(), and Update().
int BuildingsPanel::m_columns private
number of columns in which to display building indicators
Referenced by CompleteConstruction(), DoLayout(), and Update().
int BuildingsPanel::m_planet_id private
object id for the Planet whose buildings this panel displays
Referenced by CompleteConstruction(), DoLayout(), ExpandCollapse(), ExpandCollapseButtonPressed(), PlanetID(), and Update().
std::map< int, bool > BuildingsPanel::s_expanded_map static private
map indexed by planet ID indicating whether the BuildingsPanel for each object is expanded (true) or collapsed (false)
Referenced by DoLayout(), ExpandCollapse(), and ExpandCollapseButtonPressed().
The documentation for this class was generated from the following files:
BuildingsPanel.h
BuildingsPanel.cpp