FreeOrion: GiveObjectToEmpireOrder Class Reference
GiveObjectToEmpireOrder Class Reference
the Order subclass that represents giving control of a ship to another empire
#include <Order.h>
Public Member Functions
GiveObjectToEmpireOrder (int empire, int object_id, int recipient)
std::string Dump () const override
int ObjectID () const
Returns ID of object selected in this order.
int RecipientEmpireID ()
Returns ID of empire to which object is given.
Public Member Functions inherited from Order
Order ()
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Static Public Member Functions
static bool Check (int empire_id, int object_id, int recipient_empire_id)
Private Member Functions
GiveObjectToEmpireOrder ()=default
void ExecuteImpl () const override
Preconditions:
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
bool UndoImpl () const override
Private Attributes
int m_object_id = INVALID_OBJECT_ID
int m_recipient_empire_id = ALL_EMPIRES
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents giving control of a ship to another empire
Constructor & Destructor Documentation
GiveObjectToEmpireOrder() [1/2]
GiveObjectToEmpireOrder::GiveObjectToEmpireOrder (int empire, int object_id, int recipient)
References Check().
GiveObjectToEmpireOrder() [2/2]
GiveObjectToEmpireOrder::GiveObjectToEmpireOrder () private default
Member Function Documentation
Check()
bool GiveObjectToEmpireOrder::Check (int empire_id, int object_id, int recipient_empire_id) static
References Empires(), ErrorLogger, ObjectMap::find(), ObjectMap::get(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), and Objects().
Referenced by ExecuteImpl(), and GiveObjectToEmpireOrder().
Dump()
std::string GiveObjectToEmpireOrder::Dump () const override virtual
Reimplemented from Order.
References UserString().
ExecuteImpl()
void GiveObjectToEmpireOrder::ExecuteImpl () const override private virtual
Preconditions:
m_object_id must be the ID of an object owned by issuing empire
m_recipient_empire_id must be the ID of another empire
Postconditions:
the object's ownership is set to the other empire
Implements Order.
References Check(), Order::EmpireID(), Order::GetValidatedEmpire(), m_object_id, m_recipient_empire_id, and Objects().
ObjectID()
int GiveObjectToEmpireOrder::ObjectID () const inline
Returns ID of object selected in this order.
RecipientEmpireID()
int GiveObjectToEmpireOrder::RecipientEmpireID () inline
Returns ID of empire to which object is given.
serialize()
template<typename Archive > void GiveObjectToEmpireOrder::serialize (Archive & ar, const unsigned int version) private
UndoImpl()
bool GiveObjectToEmpireOrder::UndoImpl () const override private virtual
Reimplemented from Order.
References Order::EmpireID(), Order::GetValidatedEmpire(), m_object_id, and Objects().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_object_id
int GiveObjectToEmpireOrder::m_object_id = INVALID_OBJECT_ID private
Referenced by ExecuteImpl(), and UndoImpl().
m_recipient_empire_id
int GiveObjectToEmpireOrder::m_recipient_empire_id = ALL_EMPIRES private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp