FreeOrion: TextBrowseWnd Class Reference
TextBrowseWnd Class Reference
A popup tooltop for display when mousing over in-game icons.
#include <TextBrowseWnd.h>
Public Member Functions
TextBrowseWnd (const std::string &title_text, const std::string &main_text, GG::X w=GG::X(200))
void CompleteConstruction () override
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Attributes
std::shared_ptr< GG::Label > m_main_text
GG::Pt m_offset
std::shared_ptr< GG::Label > m_title_text
Detailed Description
A popup tooltop for display when mousing over in-game icons.
A title and some detail text.
Constructor & Destructor Documentation
TextBrowseWnd()
TextBrowseWnd::TextBrowseWnd (const std::string & title_text, const std::string & main_text, GG::X w = GG::X(200))
References anonymous_namespace{TextBrowseWnd.cpp}::EDGE_PAD(), ClientUI::GetBoldFont(), anonymous_namespace{TextBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT(), anonymous_namespace{TextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), m_main_text, m_offset, and m_title_text.
Member Function Documentation
CompleteConstruction()
void TextBrowseWnd::CompleteConstruction () override
References anonymous_namespace{TextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), m_main_text, and m_title_text.
Render()
void TextBrowseWnd::Render () override
References anonymous_namespace{TextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), m_offset, ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
WndHasBrowseInfo()
bool TextBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
m_main_text
std::shared_ptr<GG::Label> TextBrowseWnd::m_main_text private
Referenced by CompleteConstruction(), and TextBrowseWnd().
m_offset
GG::Pt TextBrowseWnd::m_offset private
Referenced by Render(), and TextBrowseWnd().
m_title_text
std::shared_ptr<GG::Label> TextBrowseWnd::m_title_text private
Referenced by CompleteConstruction(), and TextBrowseWnd().
The documentation for this class was generated from the following files:
TextBrowseWnd.h
TextBrowseWnd.cpp