FreeOrion: MultiIconValueIndicator Class Reference
MultiIconValueIndicator Class Reference
#include <MultiIconValueIndicator.h>
Public Member Functions
MultiIconValueIndicator (GG::X w)
MultiIconValueIndicator (GG::X w, int object_id, const std::vector< std::pair< MeterType, MeterType >> &meter_types)
MultiIconValueIndicator (GG::X w, const std::vector< int > &object_ids, const std::vector< std::pair< MeterType, MeterType >> &meter_types)
void ClearToolTip (MeterType meter_type)
void CompleteConstruction () override
bool Empty ()
bool EventFilter (GG::Wnd *w, const GG::WndEvent &event) override
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void SetToolTip (MeterType meter_type, const std::shared_ptr< GG::BrowseInfoWnd > &browse_wnd)
void Update ()
Private Attributes
std::vector< StatisticIcon * > m_icons
const std::vector< std::pair< MeterType, MeterType > > m_meter_types
std::vector< int > m_object_ids
Detailed Description
Display icon and number for various meter-related quantities associated with objects. Typical use would be to display the resource production values or population for a planet. Given a set of MeterType, the indicator will present the appropriate values for each.
Constructor & Destructor Documentation
MultiIconValueIndicator::MultiIconValueIndicator (GG::X w)
Initializes with no icons shown.
MultiIconValueIndicator::MultiIconValueIndicator (GG::X w, int object_id, const std::vector< std::pair< MeterType, MeterType >> & meter_types)
MultiIconValueIndicator::MultiIconValueIndicator (GG::X w, const std::vector< int > & object_ids, const std::vector< std::pair< MeterType, MeterType >> & meter_types)
Member Function Documentation
void MultiIconValueIndicator::ClearToolTip (MeterType meter_type)
References m_icons, and m_meter_types.
Referenced by PopulationPanel::Update(), and ResourcePanel::Update().
void MultiIconValueIndicator::CompleteConstruction () override
References anonymous_namespace{MultiIconValueIndicator.cpp}::EDGE_PAD(), GetPopCenter(), anonymous_namespace{MultiIconValueIndicator.cpp}::IconHeight(), anonymous_namespace{MultiIconValueIndicator.cpp}::IconSpacing(), anonymous_namespace{MultiIconValueIndicator.cpp}::IconWidth(), m_icons, m_meter_types, m_object_ids, METER_POPULATION, ClientUI::MeterIcon(), ClientUI::Pts(), anonymous_namespace{ServerWrapper.cpp}::SetName(), ClientUI::SpeciesIcon(), and Update().
bool MultiIconValueIndicator::Empty ()
References m_object_ids.
Referenced by SidePanel::RefreshImpl().
bool MultiIconValueIndicator::EventFilter (GG::Wnd * w, const GG::WndEvent & event) override
References ErrorLogger, FlexibleFormat(), ClientUI::GetClientUI(), GetPopCenter(), INVALID_METER_TYPE, m_icons, m_meter_types, m_object_ids, METER_POPULATION, UserString(), UserStringExists(), ClientUI::ZoomToMeterTypeArticle(), and ClientUI::ZoomToSpecies().
void MultiIconValueIndicator::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
void MultiIconValueIndicator::Render () override
References ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void MultiIconValueIndicator::SetToolTip (MeterType meter_type, const std::shared_ptr< GG::BrowseInfoWnd > & browse_wnd)
References m_icons, and m_meter_types.
Referenced by SidePanel::RefreshImpl(), MilitaryPanel::Update(), ResourcePanel::Update(), and PopulationPanel::Update().
void MultiIconValueIndicator::Update ()
References ErrorLogger, GetUniverseObject(), m_icons, m_meter_types, and m_object_ids.
Referenced by CompleteConstruction(), SidePanel::RefreshImpl(), MilitaryPanel::Update(), ResourcePanel::Update(), PopulationPanel::Update(), and SidePanel::UpdateImpl().
Member Data Documentation
std::vector<StatisticIcon*> MultiIconValueIndicator::m_icons private
Referenced by ClearToolTip(), CompleteConstruction(), EventFilter(), SetToolTip(), and Update().
const std::vector<std::pair<MeterType, MeterType> > MultiIconValueIndicator::m_meter_types private
Referenced by ClearToolTip(), CompleteConstruction(), EventFilter(), SetToolTip(), and Update().
std::vector<int> MultiIconValueIndicator::m_object_ids private
Referenced by CompleteConstruction(), Empty(), EventFilter(), and Update().
The documentation for this class was generated from the following files:
MultiIconValueIndicator.h
MultiIconValueIndicator.cpp