FreeOrion: Planet Class Reference
Planet Class Reference
a class representing a FreeOrion planet.
#include <Planet.h>
Public Member Functions
Accessors
std::set< std::string > Tags () const override
An orbital period is equal to a planets "year".
bool HasTag (const std::string &name) const override
An orbital period is equal to a planets "year".
UniverseObjectType ObjectType () const override
An orbital period is equal to a planets "year".
std::string Dump (unsigned short ntabs=0) const override
An orbital period is equal to a planets "year".
int ContainerObjectID () const override
An orbital period is equal to a planets "year".
const std::set< int > & ContainedObjectIDs () const override
An orbital period is equal to a planets "year".
bool Contains (int object_id) const override
An orbital period is equal to a planets "year".
bool ContainedBy (int object_id) const override
An orbital period is equal to a planets "year".
const Meter * GetMeter (MeterType type) const override
An orbital period is equal to a planets "year".
std::shared_ptr< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const override
An orbital period is equal to a planets "year".
std::vector< std::string > AvailableFoci () const override
An orbital period is equal to a planets "year".
const std::string & FocusIcon (const std::string &focus_name) const override
An orbital period is equal to a planets "year".
PlanetType Type () const
An orbital period is equal to a planets "year".
PlanetType OriginalType () const
An orbital period is equal to a planets "year".
int DistanceFromOriginalType () const
An orbital period is equal to a planets "year".
PlanetSize Size () const
An orbital period is equal to a planets "year".
int HabitableSize () const
An orbital period is equal to a planets "year".
bool HostileToEmpire (int empire_id) const override
An orbital period is equal to a planets "year".
PlanetEnvironment EnvironmentForSpecies (const std::string &species_name="") const
An orbital period is equal to a planets "year".
PlanetType NextBetterPlanetTypeForSpecies (const std::string &species_name="") const
An orbital period is equal to a planets "year".
PlanetType NextCloserToOriginalPlanetType () const
An orbital period is equal to a planets "year".
PlanetType ClockwiseNextPlanetType () const
An orbital period is equal to a planets "year".
PlanetType CounterClockwiseNextPlanetType () const
An orbital period is equal to a planets "year".
PlanetSize NextLargerPlanetSize () const
An orbital period is equal to a planets "year".
PlanetSize NextSmallerPlanetSize () const
An orbital period is equal to a planets "year".
float OrbitalPeriod () const
An orbital period is equal to a planets "year".
float InitialOrbitalPosition () const
float OrbitalPositionOnTurn (int turn) const
float RotationalPeriod () const
The rotational period represents a planets "day".
float AxialTilt () const
const std::set< int > & BuildingIDs () const
An orbital period is equal to a planets "year".
bool IsAboutToBeColonized () const
An orbital period is equal to a planets "year".
bool IsAboutToBeInvaded () const
An orbital period is equal to a planets "year".
bool IsAboutToBeBombarded () const
An orbital period is equal to a planets "year".
int OrderedGivenToEmpire () const
An orbital period is equal to a planets "year".
int LastTurnAttackedByShip () const
An orbital period is equal to a planets "year".
int LastTurnColonized () const
An orbital period is equal to a planets "year".
int LastTurnConquered () const
An orbital period is equal to a planets "year".
const std::string & SurfaceTexture () const
An orbital period is equal to a planets "year".
std::string CardinalSuffix () const
returns a roman number representing this planets orbit in relation to other planets
Mutators
void Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES) override
sets the type of this Planet to type
Meter * GetMeter (MeterType type) override
sets the type of this Planet to type
void Reset () override
sets the type of this Planet to type
void Depopulate () override
sets the type of this Planet to type
void SetSpecies (const std::string &species_name) override
sets the type of this Planet to type
void SetType (PlanetType type)
sets the type of this Planet to type
void SetOriginalType (PlanetType type)
sets the original type of this Planet to type
void SetSize (PlanetSize size)
sets the size of this Planet to size
void SetRotationalPeriod (float days)
sets the rotational period of this planet
void SetHighAxialTilt ()
randomly generates a new, high axial tilt
void AddBuilding (int building_id)
adds the building to the planet
bool RemoveBuilding (int building_id)
removes the building from the planet; returns false if no such building was found
void Conquer (int conquerer)
Called during combat when a planet changes hands.
bool Colonize (int empire_id, const std::string &species_name, double population)
Called during colonization handling to do the actual colonizing.
void SetIsAboutToBeColonized (bool b)
Called during colonization when a planet is about to be colonized.
void ResetIsAboutToBeColonized ()
Called after colonization, to reset the number of prospective colonizers to 0.
void SetIsAboutToBeInvaded (bool b)
Marks planet as being invaded or not, depending on whether b is true or false.
void ResetIsAboutToBeInvaded ()
Marks planet as not being invaded.
void SetIsAboutToBeBombarded (bool b)
Marks planet as being bombarded or not, depending on whether b is true or false.
void ResetIsAboutToBeBombarded ()
Marks planet as not being bombarded.
void SetGiveToEmpire (int empire_id)
Marks planet to be given to empire.
void ClearGiveToEmpire ()
Marks planet not to be given to any empire.
void SetLastTurnAttackedByShip (int turn)
Sets the last turn this planet was attacked by a ship.
void SetSurfaceTexture (const std::string &texture)
sets the type of this Planet to type
void ResetTargetMaxUnpairedMeters () override
sets the type of this Planet to type
Public Member Functions inherited from UniverseObject
void SetID (int id)
sets the ID number of the object to id
void Rename (const std::string &name)
renames this object to name
void Move (double x, double y)
moves this object by relative displacements x and y.
void MoveTo (int object_id)
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
void MoveTo (std::shared_ptr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
void MoveTo (double x, double y)
moves this object to map coordinates (x, y).
MeterMap & Meters ()
returns this UniverseObject's meters
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void BackPropagateMeters ()
Sets all this UniverseObject's meters' initial values equal to their current values.
virtual void SetOwner (int id)
Sets the empire that owns this object.
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void SetSpecialCapacity (const std::string &name, float capacity)
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
virtual void MovementPhase ()
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
virtual void ResetPairedActiveMeters ()
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const std::string & Name () const
returns the name of this object; some valid objects will have no name
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
bool Unowned () const
returns true iff there are no owners of this object
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
const std::map< std::string, std::pair< int, float > > & Specials () const
returns the Specials attached to this object
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
emitted when the UniverseObject is altered in any way
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
const MeterMap & Meters () const
returns this UniverseObject's meters
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
virtual const std::string & PublicName (int empire_id) const
Returns the name of this objectas it appears to empire empire_id .
int CreationTurn () const
returns game turn on which object was created
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
virtual ~UniverseObject ()
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Public Member Functions inherited from PopCenter
PopCenter ()
PopCenter (const std::string &species_name)
virtual ~PopCenter ()
const std::string & SpeciesName () const
returns the name of the species that populates this planet
std::string Dump (unsigned short ntabs=0) const
returns the name of the species that populates this planet
void Copy (std::shared_ptr< const PopCenter > copied_object, Visibility vis)
sets the species of the population to species_name
void Copy (std::shared_ptr< const PopCenter > copied_object)
sets the species of the population to species_name
Public Member Functions inherited from ResourceCenter
ResourceCenter ()
ResourceCenter (const ResourceCenter &rhs)
virtual ~ResourceCenter ()
void Copy (std::shared_ptr< const ResourceCenter > copied_object, Visibility vis)
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
void Copy (std::shared_ptr< const ResourceCenter > copied_object)
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
void SetFocus (const std::string &focus)
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
void ClearFocus ()
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
void UpdateFocusHistory ()
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
const std::string & Focus () const
current focus to which this ResourceCenter is set
int TurnsSinceFocusChange () const
number of turns since focus was last changed.
std::string Dump (unsigned short ntabs=0) const
the state changed signal object for this ResourceCenter
Static Public Member Functions
static int TypeDifference (PlanetType type1, PlanetType type2)
Private Member Functions
void AddMeter (MeterType meter_type) override
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
void ClampMeters () override
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
Visibility GetVisibility (int empire_id) const override
implementation should return the visibility of this ResourceCenter for the empire with the specified empire_id
void Init ()
void PopGrowthProductionResearchPhase () override
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
float m_axial_tilt = 23.0f
std::set< int > m_buildings
float m_initial_orbital_position = 0.0f
bool m_is_about_to_be_bombarded = false
bool m_is_about_to_be_colonized = false
bool m_is_about_to_be_invaded = false
int m_last_turn_attacked_by_ship = -1
float m_orbital_period = 1.0f
int m_ordered_given_to_empire_id = ALL_EMPIRES
PlanetType m_original_type
float m_rotational_period = 1.0f
PlanetSize m_size
std::string m_surface_texture
int m_turn_last_colonized = INVALID_GAME_TURN
int m_turn_last_conquered = INVALID_GAME_TURN
PlanetType m_type
Friends
class boost::serialization::access
class ObjectMap
class Universe
Structors
template<typename T >
void boost::python::detail::value_destroyer (T const volatile *p)
Create planet from type and size.
Planet (PlanetType type, PlanetSize size)
Create planet from type and size.
~Planet ()
Create planet from type and size.
Planet ()
Create planet from type and size.
Planet * Clone (int empire_id=ALL_EMPIRES) const override
returns new copy of this Planet.
Additional Inherited Members
Public Types inherited from UniverseObject
typedef flat_map< MeterType, Meter, std::less< MeterType > > MeterMap
typedef boost::signals2::signal< void(), blocking_combiner< boost::signals2::optional_last_value< void > > > StateChangedSignalType
typedef StateChangedSignalType::slot_type StateChangedSlotType
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Public Attributes inherited from ResourceCenter
boost::signals2::signal< void()> ResourceCenterChangedSignal
the state changed signal object for this ResourceCenter
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Member Functions inherited from UniverseObject
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (std::shared_ptr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
void Init ()
adds stealth meter
UniverseObject ()
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
UniverseObject (const std::string name, double x, double y)
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Protected Member Functions inherited from PopCenter
void Init ()
initialization that needs to be called by derived class after derived class is constructed
void PopCenterClampMeters ()
void PopCenterPopGrowthProductionResearchPhase ()
void PopCenterResetTargetMaxUnpairedMeters ()
Protected Member Functions inherited from ResourceCenter
void Init ()
initialization that needs to be called by derived class after derived class is constructed
void ResourceCenterClampMeters ()
void ResourceCenterResetTargetMaxUnpairedMeters ()
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
a class representing a FreeOrion planet.
Constructor & Destructor Documentation
Planet() [1/2]
Planet::Planet () protected
Create planet from type and size.
Referenced by Clone().
Planet() [2/2]
Planet::Planet (PlanetType type, PlanetSize size)
Create planet from type and size.
References PopCenter::Init(), ResourceCenter::Init(), Init(), UniverseObject::Init(), m_rotational_period, m_size, RandGaussian(), RandZeroToOne(), and anonymous_namespace{Planet.cpp}::SizeRotationFactor().
~Planet()
Planet::~Planet () inline
Create planet from type and size.
References ALL_EMPIRES, ObjectMap::Clone(), and PopCenter::Init().
Member Function Documentation
Accept()
std::shared_ptr< UniverseObject > Planet::Accept (const UniverseObjectVisitor & visitor) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References UniverseObjectVisitor::Visit().
AddBuilding()
void Planet::AddBuilding (int building_id)
adds the building to the planet
References m_buildings, and UniverseObject::StateChangedSignal.
AddMeter()
void Planet::AddMeter (MeterType meter_type) inline override private virtual
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
Implements PopCenter.
References UniverseObject::AddMeter(), UniverseObject::ClampMeters(), and UniverseObject::PopGrowthProductionResearchPhase().
Referenced by Init().
AvailableFoci()
std::vector< std::string > Planet::AvailableFoci () const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from ResourceCenter.
References GetSpecies(), and parse::species().
Referenced by Colonize().
AxialTilt()
float Planet::AxialTilt () const
Returns
an angle in degree.
References m_axial_tilt.
BuildingIDs()
const std::set<int>& Planet::BuildingIDs () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by Colonize(), and FreeOrionPython::WrapUniverseClasses().
CardinalSuffix()
std::string Planet::CardinalSuffix () const
returns a roman number representing this planets orbit in relation to other planets
References ErrorLogger, ObjectMap::get(), UniverseObject::ID(), INVALID_OBJECT_ID, UniverseObject::Name(), Objects(), RomanNumber(), UniverseObject::SystemID(), Type(), UserString(), and WarnLogger.
ClampMeters()
void Planet::ClampMeters () override private virtual
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
Reimplemented from UniverseObject.
References Meter::ClampCurrentToRange(), UniverseObject::ClampMeters(), Meter::DEFAULT_VALUE, UniverseObject::GetMeter(), METER_DEFENSE, METER_DETECTION, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_REBEL_TROOPS, METER_SHIELD, METER_STOCKPILE, METER_SUPPLY, METER_TROOPS, PopCenter::PopCenterClampMeters(), and ResourceCenter::ResourceCenterClampMeters().
ClearGiveToEmpire()
void Planet::ClearGiveToEmpire ()
Marks planet not to be given to any empire.
References ALL_EMPIRES, and SetGiveToEmpire().
ClockwiseNextPlanetType()
PlanetType Planet::ClockwiseNextPlanetType () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References anonymous_namespace{Planet.cpp}::LoopPlanetTypeIncrement(), and m_type.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
Clone()
Planet * Planet::Clone (int empire_id = ALL_EMPIRES) const override protected virtual
returns new copy of this Planet.
Implements UniverseObject.
References Copy(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), and Planet().
Colonize()
bool Planet::Colonize (int empire_id, const std::string & species_name, double population)
Called during colonization handling to do the actual colonizing.
References ALL_EMPIRES, AvailableFoci(), UniverseObject::BackPropagateMeters(), BuildingIDs(), CurrentTurn(), DebugLogger, EnvironmentForSpecies(), ErrorLogger, GetMeter(), GetSpecies(), m_buildings, m_is_about_to_be_bombarded, m_is_about_to_be_colonized, m_is_about_to_be_invaded, m_turn_last_colonized, m_type, METER_POPULATION, METER_TARGET_POPULATION, Objects(), UniverseObject::OwnedBy(), Species::PreferredFocus(), PopCenter::Reset(), Reset(), Meter::SetCurrent(), ResourceCenter::SetFocus(), UniverseObject::SetOwner(), SetSpecies(), and parse::species().
Conquer()
void Planet::Conquer (int conquerer)
Called during combat when a planet changes hands.
References Meter::BackPropagate(), Empire::ConquerProductionQueueItemsAtLocation(), CR_CAPTURE, CR_DESTROY, CurrentTurn(), Universe::Destroy(), ObjectMap::get(), GetBuildingType(), BuildingType::GetCaptureResult(), GetMeter(), GetUniverse(), UniverseObject::ID(), m_buildings, m_turn_last_conquered, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_HAPPINESS, METER_INDUSTRY, METER_INFLUENCE, METER_RESEARCH, METER_SHIELD, METER_STOCKPILE, METER_SUPPLY, Objects(), RemoveBuilding(), Meter::SetCurrent(), UniverseObject::SetOwner(), and UniverseObject::SystemID().
ContainedBy()
bool Planet::ContainedBy (int object_id) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and UniverseObject::SystemID().
ContainedObjectIDs()
const std::set< int > & Planet::ContainedObjectIDs () const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References m_buildings.
ContainerObjectID()
int Planet::ContainerObjectID () const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References UniverseObject::SystemID().
Contains()
bool Planet::Contains (int object_id) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and m_buildings.
Copy()
void Planet::Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) override virtual
sets the type of this Planet to type
Implements UniverseObject.
References PopCenter::Copy(), ResourceCenter::Copy(), UniverseObject::Copy(), ErrorLogger, Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), Universe::InhibitUniverseObjectSignals(), m_axial_tilt, m_buildings, m_initial_orbital_position, m_is_about_to_be_bombarded, m_is_about_to_be_colonized, m_is_about_to_be_invaded, m_last_turn_attacked_by_ship, UniverseObject::m_name, m_orbital_period, m_ordered_given_to_empire_id, m_original_type, m_rotational_period, m_size, m_turn_last_colonized, m_turn_last_conquered, m_type, and UniverseObject::Rename().
Referenced by Clone().
CounterClockwiseNextPlanetType()
PlanetType Planet::CounterClockwiseNextPlanetType () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References anonymous_namespace{Planet.cpp}::LoopPlanetTypeIncrement(), and m_type.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
Depopulate()
void Planet::Depopulate () override virtual
sets the type of this Planet to type
Reimplemented from PopCenter.
References ResourceCenter::ClearFocus(), PopCenter::Depopulate(), GetMeter(), METER_CONSTRUCTION, METER_INDUSTRY, METER_INFLUENCE, METER_RESEARCH, and Meter::Reset().
DistanceFromOriginalType()
int Planet::DistanceFromOriginalType () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
Dump()
std::string Planet::Dump (unsigned short ntabs = 0) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References ALL_EMPIRES, PopCenter::Dump(), ResourceCenter::Dump(), UniverseObject::Dump(), m_axial_tilt, m_buildings, m_is_about_to_be_bombarded, m_is_about_to_be_colonized, m_is_about_to_be_invaded, m_last_turn_attacked_by_ship, m_ordered_given_to_empire_id, m_original_type, m_rotational_period, m_size, m_turn_last_colonized, m_turn_last_conquered, and m_type.
EnvironmentForSpecies()
PlanetEnvironment Planet::EnvironmentForSpecies (const std::string & species_name = "") const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References ErrorLogger, Species::GetPlanetEnvironment(), GetSpecies(), m_type, parse::species(), and PopCenter::SpeciesName().
Referenced by Colonize(), ValueRef::ComplexVariable< T >::Eval(), and FreeOrionPython::WrapUniverseClasses().
FocusIcon()
const std::string & Planet::FocusIcon (const std::string & focus_name) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from ResourceCenter.
References anonymous_namespace{Planet.cpp}::EMPTY_STRING, GetSpecies(), parse::species(), and PopCenter::SpeciesName().
GetMeter() [1/2]
const Meter * Planet::GetMeter (MeterType type) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Implements PopCenter.
References UniverseObject::GetMeter().
Referenced by Colonize(), Conquer(), Depopulate(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), HostileToEmpire(), PopGrowthProductionResearchPhase(), Reset(), ResetTargetMaxUnpairedMeters(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop().
GetMeter() [2/2]
Meter * Planet::GetMeter (MeterType type) override virtual
sets the type of this Planet to type
Implements PopCenter.
References UniverseObject::GetMeter().
GetVisibility()
Visibility Planet::GetVisibility (int empire_id) const inline override private virtual
implementation should return the visibility of this ResourceCenter for the empire with the specified empire_id
Implements ResourceCenter.
References UniverseObject::GetVisibility().
HabitableSize()
int Planet::HabitableSize () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References GetGameRules(), m_size, SZ_ASTEROIDS, SZ_GASGIANT, SZ_HUGE, SZ_LARGE, SZ_MEDIUM, SZ_SMALL, and SZ_TINY.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
HasTag()
bool Planet::HasTag (const std::string & name) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References GetSpecies(), parse::species(), PopCenter::SpeciesName(), and Species::Tags().
Referenced by PopGrowthProductionResearchPhase().
HostileToEmpire()
bool Planet::HostileToEmpire (int empire_id) const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References ALL_EMPIRES, Empires(), EmpireManager::GetDiplomaticStatus(), GetMeter(), METER_TARGET_POPULATION, UniverseObject::OwnedBy(), UniverseObject::Owner(), and UniverseObject::Unowned().
Init()
void Planet::Init () private
References AddMeter(), METER_DEFENSE, METER_DETECTION, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_REBEL_TROOPS, METER_SHIELD, METER_STOCKPILE, METER_SUPPLY, and METER_TROOPS.
Referenced by Planet().
InitialOrbitalPosition()
float Planet::InitialOrbitalPosition () const
Returns
an angle in radians.
References m_initial_orbital_position.
Referenced by FreeOrionPython::WrapUniverseClasses().
IsAboutToBeBombarded()
bool Planet::IsAboutToBeBombarded () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
IsAboutToBeColonized()
bool Planet::IsAboutToBeColonized () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
IsAboutToBeInvaded()
bool Planet::IsAboutToBeInvaded () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
LastTurnAttackedByShip()
int Planet::LastTurnAttackedByShip () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
LastTurnColonized()
int Planet::LastTurnColonized () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by ValueRef::Variable< ToType >::Eval().
LastTurnConquered()
int Planet::LastTurnConquered () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
NextBetterPlanetTypeForSpecies()
PlanetType Planet::NextBetterPlanetTypeForSpecies (const std::string & species_name = "") const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References ErrorLogger, GetSpecies(), m_type, Species::NextBetterPlanetType(), parse::species(), and PopCenter::SpeciesName().
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
NextCloserToOriginalPlanetType()
PlanetType Planet::NextCloserToOriginalPlanetType () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References m_original_type, m_type, anonymous_namespace{Planet.cpp}::RingNextPlanetType(), and anonymous_namespace{Planet.cpp}::RingPreviousPlanetType().
Referenced by ValueRef::Variable< ToType >::Eval().
NextLargerPlanetSize()
PlanetSize Planet::NextLargerPlanetSize () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References m_size, and anonymous_namespace{Planet.cpp}::PlanetSizeIncrement().
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
NextSmallerPlanetSize()
PlanetSize Planet::NextSmallerPlanetSize () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References m_size, and anonymous_namespace{Planet.cpp}::PlanetSizeIncrement().
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
ObjectType()
UniverseObjectType Planet::ObjectType () const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
OrbitalPeriod()
float Planet::OrbitalPeriod () const
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References m_orbital_period.
Referenced by OrbitalPositionOnTurn(), and FreeOrionPython::WrapUniverseClasses().
OrbitalPositionOnTurn()
float Planet::OrbitalPositionOnTurn (int turn) const
Returns
an angle in radians.
References m_initial_orbital_position, and OrbitalPeriod().
Referenced by FreeOrionPython::WrapUniverseClasses().
OrderedGivenToEmpire()
int Planet::OrderedGivenToEmpire () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
OriginalType()
PlanetType Planet::OriginalType () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
PopGrowthProductionResearchPhase()
void Planet::PopGrowthProductionResearchPhase () override private virtual
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
Reimplemented from UniverseObject.
References CreatePlanetDepopulatedSitRep(), GetEmpire(), GetMeter(), HasTag(), UniverseObject::ID(), METER_POPULATION, UniverseObject::Owner(), PopCenter::PopCenterPopGrowthProductionResearchPhase(), UniverseObject::PopGrowthProductionResearchPhase(), PopCenter::Reset(), PopCenter::SpeciesName(), UniverseObject::StateChangedSignal, and anonymous_namespace{Planet.cpp}::TAG_STAT_SKIP_DEPOP.
RemoveBuilding()
bool Planet::RemoveBuilding (int building_id)
removes the building from the planet; returns false if no such building was found
References m_buildings, and UniverseObject::StateChangedSignal.
Referenced by Conquer(), and Universe::RecursiveDestroy().
Reset()
void Planet::Reset () override virtual
sets the type of this Planet to type
Reimplemented from PopCenter.
References ALL_EMPIRES, GetMeter(), m_buildings, m_is_about_to_be_bombarded, m_is_about_to_be_colonized, m_is_about_to_be_invaded, METER_DEFENSE, METER_DETECTION, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_REBEL_TROOPS, METER_SHIELD, METER_STOCKPILE, METER_SUPPLY, Objects(), UniverseObject::OwnedBy(), PopCenter::Reset(), Meter::Reset(), ResourceCenter::Reset(), and UniverseObject::SetOwner().
Referenced by Colonize().
ResetIsAboutToBeBombarded()
void Planet::ResetIsAboutToBeBombarded ()
Marks planet as not being bombarded.
References SetIsAboutToBeBombarded().
ResetIsAboutToBeColonized()
void Planet::ResetIsAboutToBeColonized ()
Called after colonization, to reset the number of prospective colonizers to 0.
References SetIsAboutToBeColonized().
Referenced by anonymous_namespace{ServerApp.cpp}::HandleColonization().
ResetIsAboutToBeInvaded()
void Planet::ResetIsAboutToBeInvaded ()
Marks planet as not being invaded.
References SetIsAboutToBeInvaded().
Referenced by anonymous_namespace{ServerApp.cpp}::HandleInvasion().
ResetTargetMaxUnpairedMeters()
void Planet::ResetTargetMaxUnpairedMeters () override virtual
sets the type of this Planet to type
Reimplemented from UniverseObject.
References GetMeter(), METER_DETECTION, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_REBEL_TROOPS, PopCenter::PopCenterResetTargetMaxUnpairedMeters(), Meter::ResetCurrent(), UniverseObject::ResetTargetMaxUnpairedMeters(), and ResourceCenter::ResourceCenterResetTargetMaxUnpairedMeters().
RotationalPeriod()
float Planet::RotationalPeriod () const
The rotational period represents a planets "day".
A "day" is arbitrarily defined to be 1/360 of a "year", and 1/90 of a turn.
References m_rotational_period.
Referenced by FreeOrionPython::WrapUniverseClasses().
serialize()
template<typename Archive > void Planet::serialize (Archive & ar, const unsigned int version) private
References CurrentTurn(), anonymous_namespace{CUIWnd.cpp}::dummy, and INVALID_GAME_TURN.
SetGiveToEmpire()
void Planet::SetGiveToEmpire (int empire_id)
Marks planet to be given to empire.
References m_ordered_given_to_empire_id, and UniverseObject::StateChangedSignal.
Referenced by ClearGiveToEmpire().
SetHighAxialTilt()
void Planet::SetHighAxialTilt ()
randomly generates a new, high axial tilt
References anonymous_namespace{Planet.cpp}::HIGH_TILT_THERESHOLD, m_axial_tilt, and RandZeroToOne().
SetIsAboutToBeBombarded()
void Planet::SetIsAboutToBeBombarded (bool b)
Marks planet as being bombarded or not, depending on whether b is true or false.
References m_is_about_to_be_bombarded, and UniverseObject::StateChangedSignal.
Referenced by ResetIsAboutToBeBombarded().
SetIsAboutToBeColonized()
void Planet::SetIsAboutToBeColonized (bool b)
Called during colonization when a planet is about to be colonized.
References m_is_about_to_be_colonized, and UniverseObject::StateChangedSignal.
Referenced by ResetIsAboutToBeColonized().
SetIsAboutToBeInvaded()
void Planet::SetIsAboutToBeInvaded (bool b)
Marks planet as being invaded or not, depending on whether b is true or false.
References m_is_about_to_be_invaded, and UniverseObject::StateChangedSignal.
Referenced by ResetIsAboutToBeInvaded().
SetLastTurnAttackedByShip()
void Planet::SetLastTurnAttackedByShip (int turn)
Sets the last turn this planet was attacked by a ship.
References m_last_turn_attacked_by_ship.
SetOriginalType()
void Planet::SetOriginalType (PlanetType type)
sets the original type of this Planet to type
References m_original_type, and UniverseObject::StateChangedSignal.
SetRotationalPeriod()
void Planet::SetRotationalPeriod (float days)
sets the rotational period of this planet
References m_rotational_period.
SetSize()
void Planet::SetSize (PlanetSize size)
sets the size of this Planet to size
References m_size, UniverseObject::StateChangedSignal, SZ_GASGIANT, SZ_NOWORLD, and SZ_TINY.
SetSpecies()
void Planet::SetSpecies (const std::string & species_name) override virtual
sets the type of this Planet to type
Reimplemented from PopCenter.
References CurrentTurn(), m_turn_last_colonized, PopCenter::SetSpecies(), and PopCenter::SpeciesName().
Referenced by Colonize(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop().
SetSurfaceTexture()
void Planet::SetSurfaceTexture (const std::string & texture)
sets the type of this Planet to type
References m_surface_texture, and UniverseObject::StateChangedSignal.
SetType()
void Planet::SetType (PlanetType type)
sets the type of this Planet to type
References m_type, and UniverseObject::StateChangedSignal.
Size()
PlanetSize Planet::Size () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References UniverseObject::HostileToEmpire().
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
SurfaceTexture()
const std::string& Planet::SurfaceTexture () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
References ALL_EMPIRES, PopCenter::Copy(), PopCenter::Depopulate(), PopCenter::GetMeter(), PopCenter::Reset(), UniverseObject::ResetTargetMaxUnpairedMeters(), and PopCenter::SetSpecies().
Tags()
std::set< std::string > Planet::Tags () const override virtual
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Reimplemented from UniverseObject.
References GetSpecies(), parse::species(), PopCenter::SpeciesName(), and Species::Tags().
Type()
PlanetType Planet::Type () const inline
An orbital period is equal to a planets "year".
A "year" is arbitrarily defined to be 4 turns.
Referenced by CardinalSuffix(), ValueRef::Variable< ToType >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), and FreeOrionPython::WrapUniverseClasses().
TypeDifference()
int Planet::TypeDifference (PlanetType type1, PlanetType type2) static
Friends And Related Function Documentation
boost::python::detail::value_destroyer
template<typename T > void boost::python::detail::value_destroyer (T const volatile * p) friend
Create planet from type and size.
boost::serialization::access
friend class boost::serialization::access friend
ObjectMap
friend class ObjectMap friend
Universe
friend class Universe friend
Member Data Documentation
m_axial_tilt
float Planet::m_axial_tilt = 23.0f private
Referenced by AxialTilt(), Copy(), Dump(), and SetHighAxialTilt().
m_buildings
std::set<int> Planet::m_buildings private
Referenced by AddBuilding(), ObjectMap::AuditContainment(), Colonize(), Conquer(), ContainedObjectIDs(), Contains(), Copy(), Dump(), RemoveBuilding(), and Reset().
m_initial_orbital_position
float Planet::m_initial_orbital_position = 0.0f private
Referenced by Copy(), InitialOrbitalPosition(), and OrbitalPositionOnTurn().
m_is_about_to_be_bombarded
bool Planet::m_is_about_to_be_bombarded = false private
Referenced by Colonize(), Copy(), Dump(), Reset(), and SetIsAboutToBeBombarded().
m_is_about_to_be_colonized
bool Planet::m_is_about_to_be_colonized = false private
Referenced by Colonize(), Copy(), Dump(), Reset(), and SetIsAboutToBeColonized().
m_is_about_to_be_invaded
bool Planet::m_is_about_to_be_invaded = false private
Referenced by Colonize(), Copy(), Dump(), Reset(), and SetIsAboutToBeInvaded().
m_last_turn_attacked_by_ship
int Planet::m_last_turn_attacked_by_ship = -1 private
Referenced by Copy(), Dump(), and SetLastTurnAttackedByShip().
m_orbital_period
float Planet::m_orbital_period = 1.0f private
Referenced by Copy(), and OrbitalPeriod().
m_ordered_given_to_empire_id
int Planet::m_ordered_given_to_empire_id = ALL_EMPIRES private
Referenced by Copy(), Dump(), and SetGiveToEmpire().
m_original_type
PlanetType Planet::m_original_type private
Referenced by Copy(), Dump(), NextCloserToOriginalPlanetType(), and SetOriginalType().
m_rotational_period
float Planet::m_rotational_period = 1.0f private
Referenced by Copy(), Dump(), Planet(), RotationalPeriod(), and SetRotationalPeriod().
m_size
PlanetSize Planet::m_size private
Referenced by Copy(), Dump(), HabitableSize(), NextLargerPlanetSize(), NextSmallerPlanetSize(), Planet(), and SetSize().
m_surface_texture
std::string Planet::m_surface_texture private
Referenced by SetSurfaceTexture().
m_turn_last_colonized
int Planet::m_turn_last_colonized = INVALID_GAME_TURN private
Referenced by Colonize(), Copy(), Dump(), and SetSpecies().
m_turn_last_conquered
int Planet::m_turn_last_conquered = INVALID_GAME_TURN private
Referenced by Conquer(), Copy(), and Dump().
m_type
PlanetType Planet::m_type private
Referenced by ClockwiseNextPlanetType(), Colonize(), Copy(), CounterClockwiseNextPlanetType(), Dump(), EnvironmentForSpecies(), NextBetterPlanetTypeForSpecies(), NextCloserToOriginalPlanetType(), and SetType().
The documentation for this class was generated from the following files:
Planet.h
Planet.cpp
SerializeUniverse.cpp