FreeOrion: Encyclopedia Class Reference
Encyclopedia Class Reference
#include <Encyclopedia.h>
Public Types
using ArticleMap = std::map< std::string, std::vector< EncyclopediaArticle > >
Public Member Functions
Encyclopedia ()
FO_COMMON_API const ArticleMap & Articles () const
FO_COMMON_API const EncyclopediaArticle & GetArticleByCategoryAndKey (const std::string &category, const std::string &key) const
FO_COMMON_API const EncyclopediaArticle & GetArticleByKey (const std::string &key) const
FO_COMMON_API const EncyclopediaArticle & GetArticleByName (const std::string &name) const
unsigned int GetCheckSum () const
FO_COMMON_API void SetArticles (Pending::Pending< ArticleMap > &&future)
Sets articles to the value of future.
Public Attributes
const EncyclopediaArticle empty_article
Private Attributes
ArticleMap m_articles
boost::optional< Pending::Pending< ArticleMap > > m_pending_articles = boost::none
Future articles.
Member Typedef Documentation
ArticleMap
using Encyclopedia::ArticleMap = std::map<std::string, std::vector<EncyclopediaArticle> >
Constructor & Destructor Documentation
Encyclopedia()
Encyclopedia::Encyclopedia () inline
References FO_COMMON_API.
Member Function Documentation
Articles()
const Encyclopedia::ArticleMap & Encyclopedia::Articles () const
References m_articles, m_pending_articles, EncyclopediaArticle::name, swap(), TraceLogger, and Pending::WaitForPending().
Referenced by GetArticleByCategoryAndKey(), GetArticleByKey(), GetArticleByName(), GetCheckSum(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires().
GetArticleByCategoryAndKey()
const EncyclopediaArticle & Encyclopedia::GetArticleByCategoryAndKey (const std::string & category, const std::string & key) const
References Articles(), and empty_article.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::SearchPediaArticlesForWords().
GetArticleByKey()
const EncyclopediaArticle & Encyclopedia::GetArticleByKey (const std::string & key) const
References Articles(), and empty_article.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires().
GetArticleByName()
const EncyclopediaArticle & Encyclopedia::GetArticleByName (const std::string & name) const
References Articles(), empty_article, and UserString().
GetCheckSum()
unsigned int Encyclopedia::GetCheckSum () const
References Articles(), and CheckSums::CheckSumCombine().
Referenced by CheckSumContent().
SetArticles()
void Encyclopedia::SetArticles (Pending::Pending< ArticleMap > && future)
Sets articles to the value of future.
References m_pending_articles.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
empty_article
const EncyclopediaArticle Encyclopedia::empty_article
Referenced by GetArticleByCategoryAndKey(), GetArticleByKey(), and GetArticleByName().
m_articles
ArticleMap Encyclopedia::m_articles mutable private
Referenced by Articles().
m_pending_articles
boost::optional<Pending::Pending<ArticleMap> > Encyclopedia::m_pending_articles = boost::none mutable private
Future articles.
mutable so that it can be assigned to m_articles when completed.
Referenced by Articles(), and SetArticles().
The documentation for this class was generated from the following files:
Encyclopedia.h
Encyclopedia.cpp