FreeOrion: StringTable Class Reference
StringTable Class Reference
Provides a key based translation string lookup with fallback.
#include <StringTable.h>
Public Member Functions
StringTable ()
Create a StringTable instance by loading translations from the default translation file.
StringTable (const std::string &filename, std::shared_ptr< const StringTable > fallback=nullptr)
Create a StringTable from the given filename.
~StringTable ()
const std::string & Filename () const
Returns the translation file name this StringTable was loaded from.
const std::string & Language () const
Returns the native language name of this StringTable.
const std::string & operator[] (const std::string &key) const
Returns a translation for key.
bool StringExists (const std::string &key) const
Returns if a translation for key exists.
Private Member Functions
void Load (std::shared_ptr< const StringTable > fallback=nullptr)
Loads this StringTable from m_filename.
Private Attributes
std::unordered_set< std::string > m_error_strings
Cache for missing translation keys to ensure the returned error reference string is not destroyed due local scope.
std::string m_filename
The filename this StringTable was loaded from.
bool m_initialized = false
True if the StringTable was completely loaded and all references were successfully resolved.
std::string m_language
The native language name of the StringTable translations.
std::mutex m_mutex
Ensure that multithreaded access to a StringTable is done in an orderly fashion.
std::map< std::string, std::string > m_strings
Mapping of translation entry keys to translated strings.
Detailed Description
Provides a key based translation string lookup with fallback.
StringTable is a map to look up translations based on key representing a translation entry. When a translation for a key is not found the StringTable delegates the lookup to another fallback StringTable, which is filled with entries from another language. When no fallback StringTable contains the requested translation entry an error string is returned, pointing out the missing translation entry.
StringTables are loaded from text files which contain the translation entries for a specific language. Those translation files are named like
<LANG ISO 639-1>.txt
where <LANG ISO 639-1> is the two letter language identifier for a language according to ISO 639-1 (e.g English=en, Russian=ru, German=de, ...).
The format of those translation files consists of newline separated entries where:
The first line is the native language name.
Linse starting with a hash sign # are considered comments and are ignored when loading the file.
Empty lines are ignored when loading the file.
The translation entries consist of an key followed by a newline, followed by the translated text followed by a newline.
An identifer must be unique within an translation file.
Identifiers consist of the any latin character, digits or an underscore. Spaces or other characters are not allowed.
The translated text is a valid UTF-8 based string, which will either be terminated by a newline, trimming of any whitespace at the begining or end of the translated string or a multi-line string.
A multi-line string starts and ends with three single quotes `'''`. As the name implies a multi-line string can span over multiple lines and any whitespace inside the string will be preseved.
A minimal example translation file for the english language en.txt should look like:
English
# This line is a comment, the line above is the native language name.
# The two lines below are an translation entry consisting of an identifer
# and a single line of translated text.
A_SINGLE_LINE
This is the translated text associated with A_SINGLE_LINE
# The line below is a translation entry with multiple lines of translated
# text.
A_MULTI_LINE
'''This text
spans over
multiple lines.
    The whitespace before this line is preseved, same goes for the newlines
after this line up to the triple single quotes.
'''
# This translation entry doesn't preserve whitespace
SINGLE_LINE_WS_TRIM
         This text is intended in the translation file, but the whitespace will be trimmed.
# This translation entry preseves whitespace
SINGLE_LINE_WS_PRESERVE
'''      This text will keep its leading and trailing whitespace   '''
StringTables implement multiple string substitution mechanism.
The first substitution mechanism replaces references to a translation entry with the text of another translation entry. The syntax for a reference consist of two opening square brackets [[, the referenced key and two closing brackets ]]. For example:
REFERENCE
I am the replaced text
TRANSLATION_ENTRY
This translation embeds another translation right here > [[REFERENCE]]
would return
This translation embeds another translaion right here > I am the replaced text
The second substitution mechanism replaces typed references with type links and the translation text. The syntax for a typed reference consists of two opening square brackets [[, a type key, a space, the referenced key and two closing brackets ]]`. For example:
REFERENCE
I am referenced
TRANSLATION_ENTRY
This translation links to [[foo_type REFERENCE]]
would return
This translation links to <foo_type REFERENCE>I am referenced</foo_type>
Constructor & Destructor Documentation
StringTable() [1/2]
StringTable::StringTable ()
Create a StringTable instance by loading translations from the default translation file.
References Load().
StringTable() [2/2]
StringTable::StringTable (const std::string & filename, std::shared_ptr< const StringTable > fallback = nullptr)
Create a StringTable from the given filename.
Parameters
filename The file name of the translation file to load.
fallback A StringTable that should be used look up unknown translation entries.
References Load().
~StringTable()
StringTable::~StringTable ()
Member Function Documentation
Filename()
const std::string& StringTable::Filename () const inline
Returns the translation file name this StringTable was loaded from.
References Load(), and m_filename.
Language()
const std::string& StringTable::Language () const inline
Returns the native language name of this StringTable.
References m_language.
Referenced by Language().
Load()
void StringTable::Load (std::shared_ptr< const StringTable > fallback = nullptr) private
Loads this StringTable from m_filename.
Parameters
fallback A StringTable that should be used look up unknown translation entries.
References DebugLogger, ErrorLogger, parse::file_substitution(), FilenameToPath(), m_filename, m_initialized, m_language, m_mutex, m_strings, and parse::read_file().
Referenced by Filename(), and StringTable().
operator[]()
const std::string & StringTable::operator[] (const std::string & key) const
Returns a translation for key.
Parameters
key The identifying key of a translation entry.
Returns
The translation for key or S_ERROR_STRING if no translation was found.
References error, anonymous_namespace{StringTable.cpp}::ERROR_STRING, m_error_strings, m_mutex, and m_strings.
StringExists()
bool StringTable::StringExists (const std::string & key) const
Returns if a translation for key exists.
Parameters
key The identifying key of a translation entry.
Returns
True iff a translation with that key exists, false otherwise.
References m_mutex, and m_strings.
Referenced by UserStringExists().
Member Data Documentation
m_error_strings
std::unordered_set<std::string> StringTable::m_error_strings mutable private
Cache for missing translation keys to ensure the returned error reference string is not destroyed due local scope.
Referenced by operator[]().
m_filename
std::string StringTable::m_filename private
The filename this StringTable was loaded from.
Referenced by Filename(), and Load().
m_initialized
bool StringTable::m_initialized = false private
True if the StringTable was completely loaded and all references were successfully resolved.
Referenced by Load().
m_language
std::string StringTable::m_language private
The native language name of the StringTable translations.
Referenced by Language(), and Load().
m_mutex
std::mutex StringTable::m_mutex mutable private
Ensure that multithreaded access to a StringTable is done in an orderly fashion.
Referenced by Load(), operator[](), and StringExists().
m_strings
std::map<std::string, std::string> StringTable::m_strings private
Mapping of translation entry keys to translated strings.
Referenced by Load(), operator[](), and StringExists().
The documentation for this class was generated from the following files:
StringTable.h
StringTable.cpp