FreeOrion: anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox Class Reference
anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox Class Reference
Public Member Functions
BuildableItemsListBox (void)
GG::Pt ListRowSize () const
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Static Public Member Functions
static GG::Y ListRowHeight ()
Constructor & Destructor Documentation
BuildableItemsListBox()
anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::BuildableItemsListBox (void) inline
References anonymous_namespace{FleetWnd.cpp}::ListRowHeight().
Member Function Documentation
ListRowHeight()
static GG::Y anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::ListRowHeight () inline static
References ClientUI::Pts().
ListRowSize()
GG::Pt anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::ListRowSize () const inline
References anonymous_namespace{FleetWnd.cpp}::ListRowHeight(), and ClientUI::ScrollWidth().
SizeMove()
void anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
The documentation for this class was generated from the following file:
BuildDesignatorWnd.cpp