FreeOrion: CUILabelButtonRepresenter Class Reference
CUILabelButtonRepresenter Class Reference
A FreeOrion styled label toggle button.
#include <CUIControls.h>
Public Member Functions
void OnChanged (const GG::StateButton &button, GG::StateButton::ButtonState prev_state) const override
void OnChecked (bool checked) const override
void Render (const GG::StateButton &button) const override
Detailed Description
A FreeOrion styled label toggle button.
Member Function Documentation
OnChanged()
void CUILabelButtonRepresenter::OnChanged (const GG::StateButton & button, GG::StateButton::ButtonState prev_state) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
OnChecked()
void CUILabelButtonRepresenter::OnChecked (bool checked) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Render()
void CUILabelButtonRepresenter::Render (const GG::StateButton & button) const override
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::ButtonHiliteBorderColor(), ClientUI::ButtonHiliteColor(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), and anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET.
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp