FreeOrion: Effect::MoveTowards Class Reference
Effect::MoveTowards Class Reference final
Moves an UniverseObject a specified distance towards some object or position on the map.
#include <Effects.h>
Public Member Functions
MoveTowards (std::unique_ptr< ValueRef::ValueRef< double >> &&speed, std::unique_ptr< Condition::Condition > &&dest_condition)
MoveTowards (std::unique_ptr< ValueRef::ValueRef< double >> &&speed, std::unique_ptr< ValueRef::ValueRef< double >> &&dest_x=nullptr, std::unique_ptr< ValueRef::ValueRef< double >> &&dest_y=nullptr)
std::unique_ptr< Effect > Clone () const override
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Private Attributes
std::unique_ptr< Condition::Condition > m_dest_condition
std::unique_ptr< ValueRef::ValueRef< double > > m_dest_x
std::unique_ptr< ValueRef::ValueRef< double > > m_dest_y
std::unique_ptr< ValueRef::ValueRef< double > > m_speed
Detailed Description
Moves an UniverseObject a specified distance towards some object or position on the map.
Constructor & Destructor Documentation
MoveTowards() [1/2]
Effect::MoveTowards::MoveTowards (std::unique_ptr< ValueRef::ValueRef< double >> && speed, std::unique_ptr< Condition::Condition > && dest_condition)
MoveTowards() [2/2]
Effect::MoveTowards::MoveTowards (std::unique_ptr< ValueRef::ValueRef< double >> && speed, std::unique_ptr< ValueRef::ValueRef< double >> && dest_x = nullptr, std::unique_ptr< ValueRef::ValueRef< double >> && dest_y = nullptr)
Member Function Documentation
Clone()
std::unique_ptr< Effect > Effect::MoveTowards::Clone () const override
References ValueRef::CloneUnique(), m_dest_condition, m_dest_x, m_dest_y, and m_speed.
Dump()
std::string Effect::MoveTowards::Dump (unsigned short ntabs = 0) const override
References DumpIndent(), m_dest_condition, m_dest_x, and m_dest_y.
Execute()
void Effect::MoveTowards::Execute (ScriptingContext & context) const override
References Fleet::Aggression(), ScriptingContext::ContextObjects(), ScriptingContext::ContextUniverse(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), ScriptingContext::effect_target, Universe::EffectDestroy(), ErrorLogger, ObjectMap::find(), ObjectMap::get(), GetUniverse(), INVALID_OBJECT_ID, m_dest_condition, m_dest_x, m_dest_y, m_speed, and anonymous_namespace{Effects.cpp}::UpdateFleetRoute().
GetCheckSum()
unsigned int Effect::MoveTowards::GetCheckSum () const override
References CheckSums::CheckSumCombine(), m_dest_condition, m_dest_x, m_dest_y, m_speed, and TraceLogger.
SetTopLevelContent()
void Effect::MoveTowards::SetTopLevelContent (const std::string & content_name) override
References m_dest_condition, m_dest_x, m_dest_y, and m_speed.
Member Data Documentation
m_dest_condition
std::unique_ptr<Condition::Condition> Effect::MoveTowards::m_dest_condition private
Referenced by Clone(), Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_dest_x
std::unique_ptr<ValueRef::ValueRef<double> > Effect::MoveTowards::m_dest_x private
Referenced by Clone(), Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_dest_y
std::unique_ptr<ValueRef::ValueRef<double> > Effect::MoveTowards::m_dest_y private
Referenced by Clone(), Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_speed
std::unique_ptr<ValueRef::ValueRef<double> > Effect::MoveTowards::m_speed private
Referenced by Clone(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp