FreeOrion: ShipDesign Class Reference
ShipDesign Class Reference
Returns true if the two designs have the same hull and parts.
#include <ShipDesign.h>
Public Member Functions
ShipDesign (const boost::optional< std::invalid_argument > &should_throw, std::string name, std::string description, int designed_on_turn, int designed_by_empire, std::string hull, std::vector< std::string > parts, std::string icon, std::string model, bool name_desc_in_stringtable=false, bool monster=false, boost::uuids::uuid uuid=boost::uuids::nil_uuid())
The public ShipDesign constructor will only construct valid ship designs, as long as the ShipHullManager has at least one hull.
ShipDesign (const ParsedShipDesign &design)
Convert a parsed ship design and do any required verification.
float AdjustedAttack (float shield) const
float Attack () const
bool CanBombard () const
bool CanColonize () const
float ColonyCapacity () const
returns the colonization capacity of this design
float Defense () const
const std::string & Description (bool stringtable_lookup=true) const
returns description of design.
int DesignedByEmpire () const
returns turn on which design was created
int DesignedOnTurn () const
float Detection () const
returns the detection ability of this design
std::string Dump (unsigned short ntabs=0) const
returns a data file format representation of this object
float Fuel () const
returns the max fuel capacity of this design
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
bool HasDirectWeapons () const
bool HasFighters () const
bool HasTroops () const
const std::string & Hull () const
returns name of hull on which design is based
const std::string & Icon () const
returns filename for small-size icon graphic for design
int ID () const
returns id number of design
float IndustryGeneration () const
returns the industry output from this ship design
float InfluenceGeneration () const
returns the influence output from this ship design
bool IsArmed () const
bool IsMonster () const
bool IsProductionLocation () const
returns true if this ship design can be a production location
bool LookupInStringtable () const
const std::string & Model () const
returns filename of 3D model that represents ships of design
const std::string & Name (bool stringtable_lookup=true) const
returns name of design.
const std::map< ShipPartClass, int > & PartClassCount () const
returns number of parts in this ship design, indexed by ShipPartClass
int PartCount () const
const std::vector< std::string > & Parts () const
returns vector of names of all parts in this design, with position in vector corresponding to slot positions
std::vector< std::string > Parts (ShipSlotType slot_type) const
returns vector of names of parts in slots of indicated type in this design, unrelated to slot positions
float PerTurnCost (int empire_id, int location_id) const
returns the maximum per-turn number of production points that can be spent on building a ship of this design
bool Producible () const
returns whether this design is producible by players and appears on the production screen list
float ProductionCost (int empire_id, int location_id) const
returns the total cost to build a ship of this design
bool ProductionCostTimeLocationInvariant () const
returns id of empire that created this design
bool ProductionLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id can produce this design at the location with location_id
int ProductionTime (int empire_id, int location_id) const
returns the time in turns it takes to build a ship of this design
void Rename (const std::string &name)
renames this design to name
float ResearchGeneration () const
returns the research output from this ship design
void SetDescription (const std::string &description)
void SetID (int id)
sets the ID number of the design to id . Should only be used by Universe class when inserting new design into Universe.
void SetMonster (const bool is_monster)
void SetName (const std::string &name)
void SetUUID (const boost::uuids::uuid &uuid)
Set the UUID.
float Shields () const
returns the max shields of this design
const std::map< std::string, int > & ShipPartCount () const
Returns number of parts in this ship design, indexed by ShipPart name.
float Speed () const
returns design speed along starlanes
float Stealth () const
returns the stealth of this design
float Structure () const
returns the max structure of this design
float TroopCapacity () const
returns the troop capacity of this design
boost::uuids::uuid UUID () const
Return the UUID.
std::vector< std::string > Weapons () const
returns vector of names of weapon parts in, unrelated to slot positions
Static Public Member Functions
static bool ValidDesign (const std::string &hull, const std::vector< std::string > &parts)
Return true if hull and parts would make a valid design.
Private Member Functions
void BuildStatCaches ()
void ForceValidDesignOrThrow (const boost::optional< std::invalid_argument > &should_throw, bool produce_log)
Force design invariants to be true.
Static Private Member Functions
static boost::optional< std::pair< std::string, std::vector< std::string > > > MaybeInvalidDesign (const std::string &hull, std::vector< std::string > &parts, bool produce_log)
Return a valid hull and parts pair iff the hull and parts vectors would not make a valid ShipDesign.
Private Attributes
std::string m_3D_model
bool m_can_bombard = false
float m_colony_capacity = 0.0f
std::string m_description
int m_designed_by_empire = ALL_EMPIRES
int m_designed_on_turn = INVALID_GAME_TURN
float m_detection = 0.0f
float m_fuel = 0.0f
bool m_has_direct_weapons = false
bool m_has_fighters = false
std::string m_hull
std::string m_icon
int m_id = INVALID_OBJECT_ID
float m_industry_generation = 0.0f
float m_influence_generation = 0.0f
bool m_is_armed = false
bool m_is_monster = false
bool m_is_production_location = false
std::string m_name
bool m_name_desc_in_stringtable = false
std::map< ShipPartClass, int > m_num_part_classes
std::map< std::string, int > m_num_ship_parts
std::vector< std::string > m_parts
bool m_producible = false
float m_research_generation = 0.0f
float m_shields = 0.0f
float m_speed = 0.0f
float m_stealth = 0.0f
float m_structure = 0.0f
float m_troop_capacity = 0.0f
boost::uuids::uuid m_uuid
Friends
FO_COMMON_API bool operator== (const ShipDesign &first, const ShipDesign &second)
template<typename Archive >
void serialize (Archive &, ShipDesign &, unsigned int const)
Detailed Description
Returns true if the two designs have the same hull and parts.
Constructor & Destructor Documentation
ShipDesign() [1/2]
ShipDesign::ShipDesign (const boost::optional< std::invalid_argument > & should_throw, std::string name, std::string description, int designed_on_turn, int designed_by_empire, std::string hull, std::vector< std::string > parts, std::string icon, std::string model, bool name_desc_in_stringtable = false, bool monster = false, boost::uuids::uuid uuid = boost::uuids::nil_uuid())
The public ShipDesign constructor will only construct valid ship designs, as long as the ShipHullManager has at least one hull.
If should_throw is not boost::none and the passed in parameters (hull and parts) would result in an invalid design it generates an explicit log message showing the FOCS corresponding to the passed in parameters and the FOCS corresponding to a corrected valid design and then throws std::invalid_argument. This can be used to test design validity and provide an explcit log message.
should_throw is not used but it is a literal reminder that std::invalid_argument should be caught.
If should_throw is boost::none it will correct the errors in parameters, print a log message and return a valid ship design. The only exception is if there are no ship hull in the HullManager. Then the constructor will not throw, but will return an invalid ship design with a empty "" hull.
References BuildStatCaches(), and ForceValidDesignOrThrow().
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse().
ShipDesign() [2/2]
ShipDesign::ShipDesign (const ParsedShipDesign & design)
Convert a parsed ship design and do any required verification.
Member Function Documentation
AdjustedAttack()
float ShipDesign::AdjustedAttack (float shield) const
References GameRules::Get(), GetGameRules(), GetShipPart(), and m_parts.
Referenced by Attack().
Attack()
float ShipDesign::Attack () const
References AdjustedAttack().
Referenced by FreeOrionPython::WrapUniverseClasses().
BuildStatCaches()
void ShipDesign::BuildStatCaches () private
References ShipHull::ColonyCapacity(), ShipHull::Detection(), ErrorLogger, ShipHull::Fuel(), GetShipHull(), GetShipPart(), m_can_bombard, m_colony_capacity, m_detection, m_fuel, m_has_direct_weapons, m_has_fighters, m_hull, m_industry_generation, m_influence_generation, m_is_armed, m_is_production_location, m_num_part_classes, m_num_ship_parts, m_parts, m_producible, m_research_generation, m_shields, m_speed, m_stealth, m_structure, m_troop_capacity, ShipHull::Producible(), ShipHull::Shields(), ShipHull::Speed(), ShipHull::Stealth(), ShipHull::Structure(), and ShipHull::TroopCapacity().
Referenced by serialize(), and ShipDesign().
CanBombard()
bool ShipDesign::CanBombard () const inline
Referenced by Ship::CanBombard().
CanColonize()
bool ShipDesign::CanColonize () const
References GetShipPart(), and m_parts.
Referenced by Ship::CanColonize(), ProductionLocation(), and FreeOrionPython::WrapUniverseClasses().
ColonyCapacity()
float ShipDesign::ColonyCapacity () const inline
returns the colonization capacity of this design
Referenced by AutomaticallyChosenColonyShip(), and FreeOrionPython::WrapUniverseClasses().
Defense()
float ShipDesign::Defense () const
References ShipPartManager::GetShipPart(), GetShipPartManager(), and Parts().
Referenced by FreeOrionPython::WrapUniverseClasses().
Description()
const std::string & ShipDesign::Description (bool stringtable_lookup = true) const
returns description of design.
if stringtable_lookup is true and the design was constructed specifying name_desc_in_stringtable true, the description string is looked up in the stringtable before being returned. otherwise, the raw name string is returned.
References m_description, m_name_desc_in_stringtable, and UserString().
Referenced by SavedDesignsListBox::SavedDesignListBoxRow::Description(), anonymous_namespace{ShipDesign.cpp}::DesignsTheSame(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), DesignWnd::MainPanel::SetDesign(), and FreeOrionPython::WrapUniverseClasses().
DesignedByEmpire()
int ShipDesign::DesignedByEmpire () const inline
returns turn on which design was created
Referenced by ShipDesignOrder::ExecuteImpl(), and Universe::GetShipDesignsToSerialize().
DesignedOnTurn()
int ShipDesign::DesignedOnTurn () const inline
Referenced by anonymous_namespace{ShipDesign.cpp}::DesignsTheSame(), Condition::anonymous_namespace{Conditions.cpp}::PredefinedShipDesignSimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
Detection()
float ShipDesign::Detection () const inline
returns the detection ability of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
Dump()
std::string ShipDesign::Dump (unsigned short ntabs = 0) const
returns a data file format representation of this object
References DumpIndent(), m_3D_model, m_description, m_hull, m_icon, m_name, m_name_desc_in_stringtable, m_parts, m_uuid, and to_string().
Referenced by ForceValidDesignOrThrow(), and FreeOrionPython::WrapUniverseClasses().
ForceValidDesignOrThrow()
void ShipDesign::ForceValidDesignOrThrow (const boost::optional< std::invalid_argument > & should_throw, bool produce_log) private
Force design invariants to be true.
If design invariants are not begin met and produce_log is true provide an explicit log message about how it was corrected and throw std::invalid_argument if should_throw is not none.
should_throw is not used but it is a literal reminder that std::invalid_argument should be caught.
References Dump(), ErrorLogger, m_hull, m_parts, MaybeInvalidDesign(), and WarnLogger.
Referenced by serialize(), and ShipDesign().
Fuel()
float ShipDesign::Fuel () const inline
returns the max fuel capacity of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
GetCheckSum()
unsigned int ShipDesign::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_3D_model, m_description, m_designed_by_empire, m_designed_on_turn, m_hull, m_icon, m_id, m_is_monster, m_name, m_name_desc_in_stringtable, m_parts, and m_uuid.
HasDirectWeapons()
bool ShipDesign::HasDirectWeapons () const inline
Referenced by FreeOrionPython::WrapUniverseClasses().
HasFighters()
bool ShipDesign::HasFighters () const inline
Referenced by Ship::HasFighters(), and FreeOrionPython::WrapUniverseClasses().
HasTroops()
bool ShipDesign::HasTroops () const inline
Referenced by Ship::CanHaveTroops(), and FreeOrionPython::WrapUniverseClasses().
Hull()
const std::string& ShipDesign::Hull () const inline
returns name of hull on which design is based
Referenced by anonymous_namespace{ShipDesign.cpp}::DesignsTheSame(), ValueRef::ComplexVariable< T >::Eval(), DesignWnd::MainPanel::GetCleanDesignDump(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), Universe::GetEffectsAndTargets(), Ship::HasTag(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasHullSimpleMatch::operator()(), operator==(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), DesignWnd::MainPanel::SetDesign(), Empire::ShipDesignAvailable(), Ship::Tags(), and FreeOrionPython::WrapUniverseClasses().
Icon()
const std::string& ShipDesign::Icon () const inline
returns filename for small-size icon graphic for design
Referenced by anonymous_namespace{ShipDesign.cpp}::DesignsTheSame().
ID()
int ShipDesign::ID () const inline
returns id number of design
References anonymous_namespace{XMLDoc.cpp}::Name, and anonymous_namespace{ServerWrapper.cpp}::SetName().
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse(), Empire::AddShipDesign(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateShip::Execute(), ShipDesignOrder::ExecuteImpl(), Universe::GetShipDesignsToSerialize(), Universe::InsertShipDesign(), DesignWnd::MainPanel::SetDesign(), EncyclopediaDetailPanel::SetItem(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues(), and FreeOrionPython::WrapUniverseClasses().
IndustryGeneration()
float ShipDesign::IndustryGeneration () const inline
returns the industry output from this ship design
Referenced by FreeOrionPython::WrapUniverseClasses().
InfluenceGeneration()
float ShipDesign::InfluenceGeneration () const inline
returns the influence output from this ship design
Referenced by FreeOrionPython::WrapUniverseClasses().
IsArmed()
bool ShipDesign::IsArmed () const inline
Referenced by FreeOrionPython::WrapUniverseClasses().
IsMonster()
bool ShipDesign::IsMonster () const inline
References anonymous_namespace{CombatSystem.cpp}::Attack().
Referenced by Universe::GetShipDesignsToSerialize(), Ship::IsMonster(), MonstersListBox::PopulateCore(), DesignWnd::MainPanel::SetDesign(), and FreeOrionPython::WrapUniverseClasses().
IsProductionLocation()
bool ShipDesign::IsProductionLocation () const inline
returns true if this ship design can be a production location
LookupInStringtable()
bool ShipDesign::LookupInStringtable () const inline
Referenced by SavedDesignsListBox::SavedDesignListBoxRow::LookupInStringtable().
MaybeInvalidDesign()
boost::optional< std::pair< std::string, std::vector< std::string > > > ShipDesign::MaybeInvalidDesign (const std::string & hull, std::vector< std::string > & parts, bool produce_log) static private
Return a valid hull and parts pair iff the hull and parts vectors would not make a valid ShipDesign.
Also pad parts with "" if it is shorter than the hull number of slots. Otherwise return none. If produce_log is true then produce log messages.
References ShipHullManager::begin(), DebugLogger, ErrorLogger, ShipHullManager::GetShipHull(), GetShipHullManager(), GetShipPart(), and WarnLogger.
Referenced by ForceValidDesignOrThrow(), and ValidDesign().
Model()
const std::string& ShipDesign::Model () const inline
returns filename of 3D model that represents ships of design
Referenced by anonymous_namespace{ShipDesign.cpp}::DesignsTheSame().
Name()
const std::string & ShipDesign::Name (bool stringtable_lookup = true) const
returns name of design.
if stringtable_lookup is true and the design was constructed specifying name_desc_in_stringtable true, the name string is looked up in the stringtable before being returned. otherwise, the raw name string is returned.
References m_name, m_name_desc_in_stringtable, and UserString().
Referenced by Empire::AddShipDesign(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), SavedDesignsListBox::SavedDesignListBoxRow::DesignName(), anonymous_namespace{ShipDesign.cpp}::DesignsTheSame(), ValueRef::NameLookup::Eval(), DesignWnd::MainPanel::GetCleanDesignDump(), Universe::GetGenericShipDesign(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::InsertBefore(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue(), ObjectListWnd::ObjectRightClicked(), Condition::anonymous_namespace{Conditions.cpp}::PredefinedShipDesignSimpleMatch::operator()(), anonymous_namespace{VarText.cpp}::PredefinedShipDesignString(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), Ship::PublicName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::ResetShipDesignLabels(), DesignWnd::MainPanel::SetDesign(), FleetDetailPanel::ShipRightClicked(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), and FreeOrionPython::WrapUniverseClasses().
PartClassCount()
const std::map<ShipPartClass, int>& ShipDesign::PartClassCount () const inline
returns number of parts in this ship design, indexed by ShipPartClass
References Effect::Dump(), FO_COMMON_API, and operator==().
Referenced by Empire::UpdateOwnedObjectCounters().
PartCount()
int ShipDesign::PartCount () const
References m_num_part_classes.
Referenced by ValueRef::ComplexVariable< T >::Eval().
Parts() [1/2]
const std::vector<std::string>& ShipDesign::Parts () const inline
returns vector of names of all parts in this design, with position in vector corresponding to slot positions
Referenced by Ship::ColonyCapacity(), Defense(), anonymous_namespace{ShipDesign.cpp}::DesignsTheSame(), ValueRef::ComplexVariable< T >::Eval(), DesignWnd::MainPanel::GetCleanDesignDump(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), Universe::GetEffectsAndTargets(), Ship::HasTag(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartSimpleMatch::operator()(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartClassSimpleMatch::operator()(), operator==(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), DesignWnd::MainPanel::SetDesign(), Empire::ShipDesignAvailable(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), Ship::TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapUniverseClasses().
Parts() [2/2]
std::vector< std::string > ShipDesign::Parts (ShipSlotType slot_type) const
returns vector of names of parts in slots of indicated type in this design, unrelated to slot positions
References ErrorLogger, ShipHullManager::GetShipHull(), GetShipHullManager(), m_hull, m_parts, and ShipHull::Slots().
PerTurnCost()
float ShipDesign::PerTurnCost (int empire_id, int location_id) const
returns the maximum per-turn number of production points that can be spent on building a ship of this design
References ProductionCost(), and ProductionTime().
Referenced by anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
Producible()
bool ShipDesign::Producible () const inline
returns whether this design is producible by players and appears on the production screen list
Referenced by BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), CompletedDesignsListBox::PopulateCore(), Empire::ProducibleItem(), and Empire::ShipDesignAvailable().
ProductionCost()
float ShipDesign::ProductionCost (int empire_id, int location_id) const
returns the total cost to build a ship of this design
References anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_COST, GetGameRules(), GetShipHull(), GetShipPart(), m_hull, m_id, and m_parts.
Referenced by ValueRef::ComplexVariable< T >::Eval(), PerTurnCost(), Empire::ProductionCostAndTime(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
ProductionCostTimeLocationInvariant()
bool ShipDesign::ProductionCostTimeLocationInvariant () const
returns id of empire that created this design
returns true if the production cost and time are invariant (does not depend on) the location
References GetGameRules(), GetShipHull(), GetShipPart(), m_hull, and m_parts.
Referenced by ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
ProductionLocation()
bool ShipDesign::ProductionLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id can produce this design at the location with location_id
References Species::CanColonize(), CanColonize(), Species::CanProduceShips(), DebugLogger, anonymous_namespace{ShipDesign.cpp}::EMPTY_STRING, ErrorLogger, ObjectMap::get(), GetEmpire(), GetShipHull(), GetShipPart(), GetSpecies(), ShipHull::Location(), m_hull, m_parts, Objects(), parse::species(), Ship::SpeciesName(), and WarnLogger.
Referenced by Empire::ProducibleItem(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
ProductionTime()
int ShipDesign::ProductionTime (int empire_id, int location_id) const
returns the time in turns it takes to build a ship of this design
References GetGameRules(), GetShipHull(), GetShipPart(), m_hull, and m_parts.
Referenced by PerTurnCost(), Empire::ProductionCostAndTime(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
Rename()
void ShipDesign::Rename (const std::string & name) inline
renames this design to name
ResearchGeneration()
float ShipDesign::ResearchGeneration () const inline
returns the research output from this ship design
Referenced by FreeOrionPython::WrapUniverseClasses().
SetDescription()
void ShipDesign::SetDescription (const std::string & description)
References tag_parser::description, and m_description.
Referenced by Universe::RenameShipDesign().
SetID()
void ShipDesign::SetID (int id)
sets the ID number of the design to id . Should only be used by Universe class when inserting new design into Universe.
References m_id.
Referenced by Universe::InsertShipDesignID().
SetMonster()
void ShipDesign::SetMonster (const bool is_monster) inline
SetName()
void ShipDesign::SetName (const std::string & name)
References m_name.
Referenced by Universe::RenameShipDesign().
SetUUID()
void ShipDesign::SetUUID (const boost::uuids::uuid & uuid)
Set the UUID.
References m_uuid.
Shields()
float ShipDesign::Shields () const inline
returns the max shields of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
ShipPartCount()
const std::map<std::string, int>& ShipDesign::ShipPartCount () const inline
Returns number of parts in this ship design, indexed by ShipPart name.
Referenced by Empire::UpdateOwnedObjectCounters().
Speed()
float ShipDesign::Speed () const inline
returns design speed along starlanes
Referenced by FreeOrionPython::WrapUniverseClasses().
Stealth()
float ShipDesign::Stealth () const inline
returns the stealth of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
Structure()
float ShipDesign::Structure () const inline
returns the max structure of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
TroopCapacity()
float ShipDesign::TroopCapacity () const inline
returns the troop capacity of this design
Referenced by FreeOrionPython::WrapUniverseClasses().
UUID()
boost::uuids::uuid ShipDesign::UUID () const inline
Return the UUID.
Referenced by anonymous_namespace{DesignWnd.cpp}::CreateSaveFileNameForDesign(), SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::InsertBefore(), and DesignWnd::MainPanel::SetDesign().
ValidDesign()
bool ShipDesign::ValidDesign (const std::string & hull, const std::vector< std::string > & parts) static
Return true if hull and parts would make a valid design.
References MaybeInvalidDesign().
Referenced by DesignWnd::MainPanel::DesignChanged(), and FreeOrionPython::WrapUniverseClasses().
Weapons()
std::vector< std::string > ShipDesign::Weapons () const
returns vector of names of weapon parts in, unrelated to slot positions
References GetShipPart(), and m_parts.
Friends And Related Function Documentation
operator==
FO_COMMON_API bool operator== (const ShipDesign & first, const ShipDesign & second) friend
serialize
template<typename Archive > void serialize (Archive & ar, ShipDesign & obj, unsigned int const version) friend
Member Data Documentation
m_3D_model
std::string ShipDesign::m_3D_model private
Referenced by Dump(), GetCheckSum(), and serialize().
m_can_bombard
bool ShipDesign::m_can_bombard = false private
Referenced by BuildStatCaches().
m_colony_capacity
float ShipDesign::m_colony_capacity = 0.0f private
Referenced by BuildStatCaches().
m_description
std::string ShipDesign::m_description private
Referenced by Description(), Dump(), GetCheckSum(), serialize(), and SetDescription().
m_designed_by_empire
int ShipDesign::m_designed_by_empire = ALL_EMPIRES private
Referenced by GetCheckSum(), and serialize().
m_designed_on_turn
int ShipDesign::m_designed_on_turn = INVALID_GAME_TURN private
Referenced by GetCheckSum(), and serialize().
m_detection
float ShipDesign::m_detection = 0.0f private
Referenced by BuildStatCaches().
m_fuel
float ShipDesign::m_fuel = 0.0f private
Referenced by BuildStatCaches().
m_has_direct_weapons
bool ShipDesign::m_has_direct_weapons = false private
Referenced by BuildStatCaches().
m_has_fighters
bool ShipDesign::m_has_fighters = false private
Referenced by BuildStatCaches().
m_hull
std::string ShipDesign::m_hull private
Referenced by BuildStatCaches(), Dump(), ForceValidDesignOrThrow(), GetCheckSum(), Parts(), ProductionCost(), ProductionCostTimeLocationInvariant(), ProductionLocation(), ProductionTime(), and serialize().
m_icon
std::string ShipDesign::m_icon private
Referenced by Dump(), GetCheckSum(), and serialize().
m_id
int ShipDesign::m_id = INVALID_OBJECT_ID private
Referenced by GetCheckSum(), ProductionCost(), serialize(), and SetID().
m_industry_generation
float ShipDesign::m_industry_generation = 0.0f private
Referenced by BuildStatCaches().
m_influence_generation
float ShipDesign::m_influence_generation = 0.0f private
Referenced by BuildStatCaches().
m_is_armed
bool ShipDesign::m_is_armed = false private
Referenced by BuildStatCaches().
m_is_monster
bool ShipDesign::m_is_monster = false private
Referenced by GetCheckSum(), and serialize().
m_is_production_location
bool ShipDesign::m_is_production_location = false private
Referenced by BuildStatCaches().
m_name
std::string ShipDesign::m_name private
Referenced by Dump(), GetCheckSum(), Name(), serialize(), and SetName().
m_name_desc_in_stringtable
bool ShipDesign::m_name_desc_in_stringtable = false private
Referenced by Description(), Dump(), GetCheckSum(), Name(), and serialize().
m_num_part_classes
std::map<ShipPartClass, int> ShipDesign::m_num_part_classes private
Referenced by BuildStatCaches(), and PartCount().
m_num_ship_parts
std::map<std::string, int> ShipDesign::m_num_ship_parts private
Referenced by BuildStatCaches().
m_parts
std::vector<std::string> ShipDesign::m_parts private
Referenced by AdjustedAttack(), BuildStatCaches(), CanColonize(), Dump(), ForceValidDesignOrThrow(), GetCheckSum(), Parts(), ProductionCost(), ProductionCostTimeLocationInvariant(), ProductionLocation(), ProductionTime(), serialize(), and Weapons().
m_producible
bool ShipDesign::m_producible = false private
Referenced by BuildStatCaches().
m_research_generation
float ShipDesign::m_research_generation = 0.0f private
Referenced by BuildStatCaches().
m_shields
float ShipDesign::m_shields = 0.0f private
Referenced by BuildStatCaches().
m_speed
float ShipDesign::m_speed = 0.0f private
Referenced by BuildStatCaches().
m_stealth
float ShipDesign::m_stealth = 0.0f private
Referenced by BuildStatCaches().
m_structure
float ShipDesign::m_structure = 0.0f private
Referenced by BuildStatCaches().
m_troop_capacity
float ShipDesign::m_troop_capacity = 0.0f private
Referenced by BuildStatCaches().
m_uuid
boost::uuids::uuid ShipDesign::m_uuid private
Referenced by Dump(), GetCheckSum(), serialize(), and SetUUID().
The documentation for this class was generated from the following files:
ShipDesign.h
ShipDesign.cpp