FreeOrion: SavedDesignsListBox Class Reference
SavedDesignsListBox Class Reference
Classes
class SavedDesignListBoxRow
Public Member Functions
SavedDesignsListBox (const AvailabilityManager &availabilities_state, const boost::optional< std::string > &drop_type=boost::none)
Public Member Functions inherited from BasesListBox
void CompleteConstruction () override
BasesListBox (const AvailabilityManager &availabilities_state, const boost::optional< std::string > &drop_type=boost::none, const boost::optional< std::string > &empty_prompt=boost::none)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void ChildrenDraggedAway (const std::vector< GG::Wnd *> &wnds, const GG::Wnd *destination) override
void SetEmpireShown (int empire_id, bool refresh_list=true)
virtual void Populate ()
Public Member Functions inherited from QueueListBox
QueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
void CompleteConstruction () override
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
virtual void EnableOrderIssuing (bool enable=true)
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Protected Member Functions
void BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
void BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
void BaseRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
std::shared_ptr< Row > ChildrenDraggedAwayCore (const GG::Wnd *const wnd) override
If wnd is a valid dragged child return a replacement row.
void PopulateCore () override
An implementation of BasesListBox provides a PopulateCore to fill itself.
void QueueItemMoved (const GG::ListBox::iterator &row_it, const GG::ListBox::iterator &original_position_it) override
void ResetEmptyListPrompt () override
Reset the empty list prompt.
Protected Member Functions inherited from BasesListBox
void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
int EmpireID () const
const AvailabilityManager & AvailabilityState () const
GG::Pt ListRowSize ()
Protected Member Functions inherited from QueueListBox
virtual std::function< void()> DeleteAction (GG::ListBox::iterator it) const
Return a functor that will signal that it should be deleted.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
virtual std::function< void()> MoveToBottomAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the bottom of the list.
virtual std::function< void()> MoveToTopAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the top of the list.
Additional Inherited Members
Public Attributes inherited from BasesListBox
boost::signals2::signal< void(const ShipDesign *)> DesignClickedSignal
boost::signals2::signal< void(const std::string &, const std::vector< std::string > &)> DesignComponentsSelectedSignal
boost::signals2::signal< void(const ShipDesign *)> DesignRightClickedSignal
boost::signals2::signal< void(int)> DesignSelectedSignal
boost::signals2::signal< void(const HullType *)> HullClickedSignal
boost::signals2::signal< void(const boost::uuids::uuid &)> SavedDesignSelectedSignal
Public Attributes inherited from QueueListBox
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
Static Public Attributes inherited from BasesListBox
static const std::string BASES_LIST_BOX_DROP_TYPE = "BasesListBoxRow"
Constructor & Destructor Documentation
SavedDesignsListBox()
SavedDesignsListBox::SavedDesignsListBox (const AvailabilityManager & availabilities_state, const boost::optional< std::string > & drop_type = boost::none) inline
Member Function Documentation
BaseDoubleClicked()
void SavedDesignsListBox::BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References BasesListBox::SavedDesignSelectedSignal.
BaseLeftClicked()
void SavedDesignsListBox::BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), BasesListBox::DesignClickedSignal, SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID(), BasesListBox::EmpireID(), and anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager().
BaseRightClicked()
void SavedDesignsListBox::BaseRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from BasesListBox.
References anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns(), anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns(), DebugLogger, BasesListBox::DesignRightClickedSignal, SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID(), BasesListBox::EmpireID(), OptionsDB::Get(), GetOptionsDB(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::MoveBefore(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::OrderedDesignUUIDs(), BasesListBox::Populate(), OptionsDB::Set(), and UserString().
ChildrenDraggedAwayCore()
std::shared_ptr< BasesListBox::Row > SavedDesignsListBox::ChildrenDraggedAwayCore (const GG::Wnd *const wnd) override protected virtual
If wnd is a valid dragged child return a replacement row.
Otherwise return nullptr.
Implements BasesListBox.
References BasesListBox::AvailabilityState(), ErrorLogger, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and BasesListBox::ListRowSize().
PopulateCore()
void SavedDesignsListBox::PopulateCore () override protected virtual
An implementation of BasesListBox provides a PopulateCore to fill itself.
Implements BasesListBox.
References BasesListBox::AvailabilityState(), DebugLogger, anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and BasesListBox::ListRowSize().
QueueItemMoved()
void SavedDesignsListBox::QueueItemMoved (const GG::ListBox::iterator & row_it, const GG::ListBox::iterator & original_position_it) override protected virtual
Reimplemented from BasesListBox.
References SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and BasesListBox::ListRowSize().
ResetEmptyListPrompt()
void SavedDesignsListBox::ResetEmptyListPrompt () override protected virtual
Reset the empty list prompt.
Reimplemented from BasesListBox.
References QueueListBox::SetEmptyPromptText(), and UserString().
The documentation for this class was generated from the following file:
DesignWnd.cpp