FreeOrion: GovernmentWnd Class Reference
GovernmentWnd Class Reference
#include <GovernmentWnd.h>
Classes
class MainPanel
class PolicyPalette
Public Member Functions
void CompleteConstruction () override
Structors
GovernmentWnd (GG::X w, GG::Y h)
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Render () override
void Reset ()
void Sanitize ()
void EnableOrderIssuing (bool enable=true)
Private Member Functions
void InitializeWindows ()
void PoliciesChanged ()
Private Attributes
std::shared_ptr< MainPanel > m_main_panel
std::shared_ptr< PolicyPalette > m_policy_palette
Detailed Description
Lets the player design ships
Constructor & Destructor Documentation
GovernmentWnd::GovernmentWnd (GG::X w, GG::Y h)
Member Function Documentation
void GovernmentWnd::CompleteConstruction () override
References GovernmentWnd::MainPanel::AddPolicy(), GovernmentWnd::MainPanel::ClearPolicy(), HumanClientApp::GetApp(), anonymous_namespace{GovernmentWnd.cpp}::GOV_MAIN_WND_NAME, anonymous_namespace{GovernmentWnd.cpp}::GOV_POLICY_PALETTE_WND_NAME, InitializeWindows(), m_main_panel, m_policy_palette, PoliciesChanged(), and HumanClientApp::RepositionWindowsSignal.
void GovernmentWnd::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this DesignWnd.
void GovernmentWnd::InitializeWindows () private
References m_main_panel, and m_policy_palette.
Referenced by CompleteConstruction().
void GovernmentWnd::PoliciesChanged () private
Referenced by CompleteConstruction().
void GovernmentWnd::Render () override
Enables, or disables if enable is false, issuing orders via this DesignWnd.
References ClientUI::WndColor().
void GovernmentWnd::Reset ()
Enables, or disables if enable is false, issuing orders via this DesignWnd.
References m_main_panel, and m_policy_palette.
void GovernmentWnd::Sanitize ()
Enables, or disables if enable is false, issuing orders via this DesignWnd.
References m_main_panel.
void GovernmentWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Enables, or disables if enable is false, issuing orders via this DesignWnd.
References m_main_panel, and m_policy_palette.
Member Data Documentation
std::shared_ptr<MainPanel> GovernmentWnd::m_main_panel private
Referenced by CompleteConstruction(), InitializeWindows(), Reset(), Sanitize(), and SizeMove().
std::shared_ptr<PolicyPalette> GovernmentWnd::m_policy_palette private
Referenced by CompleteConstruction(), InitializeWindows(), Reset(), and SizeMove().
The documentation for this class was generated from the following files:
GovernmentWnd.h
GovernmentWnd.cpp