FreeOrion: Universe Class Reference
Universe Class Reference
The Universe class contains the majority of FreeOrion gamestate: All the UniverseObjects in a game, and (of less importance) all ShipDesigns in a game.
#include <Universe.h>
Public Types
typedef std::map< int, ObjectMap > EmpireObjectMap
Known information each empire had about objects in the Universe; keyed by empire id.
typedef std::map< int, ObjectSpecialsMap > EmpireObjectSpecialsMap
map from empire id to ObjectSpecialsMap of known specials for objects for that empire
typedef std::map< int, ObjectVisibilityMap > EmpireObjectVisibilityMap
map from empire id to ObjectVisibilityMap for that empire
typedef std::map< int, ObjectVisibilityTurnMap > EmpireObjectVisibilityTurnMap
Each empire's most recent turns on which object information was known; keyed by empire id.
using EmpireStatsMap = std::map< std::string, std::unique_ptr< ValueRef::ValueRef< double > >>
Set the empire stats from future.
typedef std::map< int, std::set< std::string > > ObjectSpecialsMap
map from object id to names of specials on an object
typedef std::map< int, Visibility > ObjectVisibilityMap
map from object id to Visibility level for a particular empire
typedef std::map< int, VisibilityTurnMap > ObjectVisibilityTurnMap
Most recent turn number on which the objects were observed at various Visibility ratings; keyed by object id.
typedef ShipDesignMap::const_iterator ship_design_iterator
const iterator over ship designs created by players that are known by this client
typedef std::map< int, ShipDesign * > ShipDesignMap
ShipDesigns in universe; keyed by design id.
typedef boost::signals2::signal< void(std::shared_ptr< const UniverseObject >)> UniverseObjectDeleteSignalType
emitted just before the UniverseObject is deleted
typedef std::map< Visibility, int > VisibilityTurnMap
Most recent turn number on which a something, such as a Universe object, was observed at various Visibility ratings or better.
Public Member Functions
Universe ()
virtual ~Universe ()
void ApplyAllEffectsAndUpdateMeters (ScriptingContext &context, bool do_accounting=true)
Determines all effectsgroups' target sets, then resets meters and executes all effects on all objects.
void ApplyAppearanceEffects (const std::vector< int > &object_ids, ScriptingContext &context)
Executes effects that modify objects' appearance in the human client.
void ApplyAppearanceEffects (ScriptingContext &context)
Executes effects that modify objects' apperance for all objects.
void ApplyEffectDerivedVisibilities (EmpireManager &empires)
Applies empire-object visibilities set by effects.
void ApplyGenerateSitRepEffects (ScriptingContext &context)
Executes effects that modify objects' apperance for all objects.
void ApplyMeterEffectsAndUpdateMeters (const std::vector< int > &object_ids, ScriptingContext &context, bool do_accounting=true)
Determines all effectsgroups' target sets, then resets meters and executes only SetMeter effects on all objects whose ids are listed in object_ids.
void ApplyMeterEffectsAndUpdateMeters (ScriptingContext &context, bool do_accounting=true)
Calls above ApplyMeterEffectsAndUpdateMeters() function on all objects.
void BackPropagateObjectMeters ()
Sets all objects' meters' initial values to their current values.
ship_design_iterator beginShipDesigns () const
void Clear ()
Clears main ObjectMap, empires' latest known objects map, and ShipDesign map.
void CountDestructionInStats (int object_id, int source_object_id, ScriptingContext &context)
Record in statistics that object_id was destroyed by species/empire associated with source_object_id.
bool Delete (int object_id)
Permanently deletes object with ID number object_id.
bool DeleteShipDesign (int design_id)
Permanently deletes the ship design with ID number design_id.
void Destroy (int object_id, bool update_destroyed_object_knowers=true)
Removes the object with ID number object_id from the universe's map of existing objects, and adds the object's id to the set of destroyed object ids.
const std::set< int > & DestroyedObjectIds () const
Returns IDs of objects that have been destroyed.
void EffectDestroy (int object_id, int source_object_id=INVALID_OBJECT_ID)
Used by the Destroy effect to mark an object for destruction later during turn processing.
const std::set< int > & EmpireKnownDestroyedObjectIDs (int empire_id) const
Returns IDs of objects that the Empire with id empire_id knows have been destroyed.
const ObjectMap & EmpireKnownObjects (int empire_id=ALL_EMPIRES) const
Returns latest known state of objects for the Empire with id empire_id or the true / complete state of all objects in this Universe (the same as calling Objects()) if empire_id is ALL_EMPIRES.
ObjectMap & EmpireKnownObjects (int empire_id=ALL_EMPIRES)
const std::set< int > & EmpireKnownShipDesignIDs (int empire_id) const
Returns IDs of ship designs that the Empire with id empire_id has seen during the game.
const std::set< int > & EmpireStaleKnowledgeObjectIDs (int empire_id) const
Returns IDs of objects that the Empire with id empire_id has stale knowledge of in its latest known objects.
std::set< int > EmpireVisibleObjectIDs (int empire_id, const EmpireManager &empires) const
Returns IDs of objects that the Empire with id empire_id has vision of on the current turn, or objects that at least one empire has vision of on the current turn if empire_id = ALL_EMPIRES.
ship_design_iterator endShipDesigns () const
void ForgetKnownObject (int empire_id, int object_id)
If an empire_id can't currently see object_id, then remove object_id' object from the object map and the set of known objects.
const Effect::AccountingMap & GetEffectAccountingMap () const
Returns map, indexed by object id, to map, indexed by MeterType, to vector of EffectAccountInfo for the meter, in order effects were applied to the meter.
Effect::AccountingMap & GetEffectAccountingMap ()
const EmpireObjectVisibilityMap & GetEmpireObjectVisibility () const
const EmpireObjectVisibilityTurnMap & GetEmpireObjectVisibilityTurnMap () const
const ShipDesign * GetGenericShipDesign (const std::string &name) const
Visibility GetObjectVisibilityByEmpire (int object_id, int empire_id) const
Returns the Visibility level of empire with id empire_id of UniverseObject with id object_id as determined by calling UpdateEmpireObjectVisibilities.
const VisibilityTurnMap & GetObjectVisibilityTurnMapByEmpire (int object_id, int empire_id) const
Returns the map from Visibility level to turn number on which the empire with id empire_id last had the various Visibility levels of the UniverseObject with id object_id .
std::set< std::string > GetObjectVisibleSpecialsByEmpire (int object_id, int empire_id) const
Returns the set of specials attached to the object with id object_id that the empire with id empire_id can see this turn.
std::shared_ptr< const Pathfinder > GetPathfinder () const
Return the Pathfinder.
const ShipDesign * GetShipDesign (int ship_design_id) const
returns the ship design with id ship_design id, or 0 if non exists
const std::map< std::string, std::map< int, std::map< int, double > > > & GetStatRecords () const
int HighestDestroyedObjectID () const
void InhibitUniverseObjectSignals (bool inhibit=true)
Sets whether to inhibit UniverseObjectSignals.
void InitializeSystemGraph (const EmpireManager &empires, const ObjectMap &objects)
Fills pathfinding data structure and determines least jumps distances between systems based on the objects in objects.
const std::vector< UnlockableItem > & InitiallyUnlockedBuildings () const
Buildings unlocked before turn 1.
std::vector< const FleetPlan * > InitiallyUnlockedFleetPlans () const
Fleets unlocked before turn 1.
const std::vector< UnlockableItem > & InitiallyUnlockedItems () const
Items unlocked before turn 1.
void InitMeterEstimatesAndDiscrepancies (ScriptingContext &context)
For all objects and meters, determines discrepancies between actual meter maxes and what the known universe should produce, and and stores in m_effect_discrepancy_map.
template<typename T , typename... Args>
std::shared_ptr< T > InsertByEmpireWithID (int empire_id, int id, Args &&... args)
empire_id inserts object obj into the universe with the given id.
template<typename T , typename... Args>
std::shared_ptr< T > InsertNew (Args &&... args)
InsertNew constructs and inserts a UniverseObject into the object map with a new id.
bool InsertShipDesign (ShipDesign *ship_design)
Inserts ship_design into the universe.
bool InsertShipDesignID (ShipDesign *ship_design, boost::optional< int > empire_id, int id)
Inserts ship_design into the universe with given id; returns true on success, or false on failure.
template<typename T , typename... Args>
std::shared_ptr< T > InsertTemp (Args &&... args)
InsertTemp constructs and inserts a temporary UniverseObject into the object map with a temporary id.
std::vector< const MonsterFleetPlan * > MonsterFleetPlans () const
Items unlocked before turn 1.
size_t NumShipDesigns () const
void ObfuscateIDGenerator ()
ObfuscateIDGenerator applies randomization to the IDAllocator to prevent clients from inferring too much information about other client's id generation activities.
const ObjectMap & Objects () const
Returns objects in this Universe.
ObjectMap & Objects ()
Universe & operator= (Universe &&other) noexcept
std::set< int > RecursiveDestroy (int object_id)
Destroys object with ID object_id, and destroys any associted objects, such as contained buildings of planets, contained anything of systems, or fleets if their last ship has id object_id and the fleet is thus empty.
void RenameShipDesign (int design_id, const std::string &name="", const std::string &description="")
void ResetAllIDAllocation (const std::vector< int > &empire_ids=std::vector< int >())
Reset object and ship design id allocation for a new game.
void ResetAllObjectMeters (bool target_max_unpaired=true, bool active=true)
Resets meters.
void SetEffectDerivedVisibility (int empire_id, int object_id, int source_id, const ValueRef::ValueRef< Visibility > *vis)
Sets a special record of visibility that overrides the standard empire-object visibility after the latter is processed.
void SetEmpireKnowledgeOfDestroyedObject (int object_id, int empire_id)
Adds the object ID object_id to the set of object ids for the empire with id empire_id that the empire knows have been destroyed.
void SetEmpireKnowledgeOfShipDesign (int ship_design_id, int empire_id)
Adds the ship design ID ship_design_id to the set of ship design ids known by the empire with id empire_id.
void SetEmpireObjectVisibility (int empire_id, int object_id, Visibility vis)
Sets visibility for indicated empire_id of object with object_id a vis.
void SetEmpireSpecialVisibility (int empire_id, int object_id, const std::string &special_name, bool visible=true)
Sets visibility for indicated empire_id for the indicated special.
void SetEmpireStats (Pending::Pending< EmpireStatsMap > future)
void SetInitiallyUnlockedBuildings (Pending::Pending< std::vector< UnlockableItem >> &&future)
Set buildings unlocked before turn 1 from future.
void SetInitiallyUnlockedFleetPlans (Pending::Pending< std::vector< std::unique_ptr< FleetPlan >>> &&future)
Set fleets unlocked before turn 1 from future.
void SetInitiallyUnlockedItems (Pending::Pending< std::vector< UnlockableItem >> &&future)
Set items unlocked before turn 1 from future.
void SetMonsterFleetPlans (Pending::Pending< std::vector< std::unique_ptr< MonsterFleetPlan >>> &&future)
Set items unlocked before turn 1 from future.
void SetUniverseWidth (double width)
const bool & UniverseObjectSignalsInhibited ()
Returns true if UniverseOjbectSignals are inhibited, false otherwise.
double UniverseWidth () const
void UpdateEmpireLatestKnownObjectsAndVisibilityTurns ()
Stores latest known information about each object for each empire and updates the record of the last turn on which each empire has visibility of object that can be seen on the current turn with the level of visibility that the empire has this turn.
void UpdateEmpireObjectVisibilities (EmpireManager &empires)
Determines which empires can see which objects at what visibility level, based on.
void UpdateEmpireStaleObjectKnowledge (EmpireManager &empires)
Checks latest known information about each object for each empire and, in cases when the latest known state (stealth and location) suggests that the empire should be able to see the object, but the object can't be seen by the empire, updates the latest known state to note this.
void UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap (const EmpireManager &empires)
void UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps (const EmpireManager &empires)
Regenerates per-empire system view graphs by filtering the complete system graph based on empire visibility.
void UpdateMeterEstimates (const std::vector< int > &objects_vec, ScriptingContext &context)
Based on (known subset of, if in a client) universe and any orders given so far this turn, updates estimated meter maxes for next turn for the objects with ids indicated in objects_vec.
void UpdateMeterEstimates (int object_id, ScriptingContext &context, bool update_contained_objects=false)
Updates indicated object's meters, and if applicable, the meters of objects contained within the indicated object.
void UpdateMeterEstimates (ScriptingContext &context)
Updates all meters for all (known) objects.
void UpdateMeterEstimates (ScriptingContext &context, bool do_accounting)
void UpdateStatRecords (EmpireManager &empires)
Public Attributes
UniverseObjectDeleteSignalType UniverseObjectDeleteSignal
the state changed signal object for this UniverseObject
Private Types
typedef std::unordered_map< int, boost::container::flat_map< MeterType, double > > DiscrepancyMap
Discrepancy between meter's value at start of turn, and the value that this client calculate that the meter should have with the knowledge available -> the unknown factor affecting the meter.
typedef std::map< int, ObjSrcVisValRefVecMap > EmpireObjectVisValueRefMap
typedef std::map< int, std::set< int > > ObjectKnowledgeMap
IDs of Empires which know information about an object (or deleted object); keyed by object id.
typedef std::map< int, SrcVisValRefVec > ObjSrcVisValRefVecMap
typedef std::vector< std::pair< int, VisValRef > > SrcVisValRefVec
typedef const ValueRef::ValueRef< Visibility > * VisValRef
Private Member Functions
const EmpireStatsMap & EmpireStats () const
void ExecuteEffects (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > &source_effects_targets_causes, ScriptingContext &context, bool update_effect_accounting, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false)
Executes all effects.
int GenerateDesignID ()
Generates design ID for a new (ship) design.
int GenerateObjectID ()
Generates an object ID for a future object.
void GetDestroyedObjectsToSerialize (std::set< int > &destroyed_object_ids, int encoding_empire) const
Fills destroyed_object_ids with ids of objects known to be destroyed by the empire with ID encoding empire.
void GetEffectsAndTargets (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > &source_effects_targets_causes, const ScriptingContext &context, bool only_meter_effects=false) const
Clears source_effects_targets_causes, and then populates with all EffectsGroups and their targets in the known universe.
void GetEffectsAndTargets (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > &source_effects_targets_causes, const std::vector< int > &target_objects, const ScriptingContext &context, bool only_meter_effects=false) const
Removes entries in source_effects_targets_causes about effects groups acting on objects in target_objects, and then repopulates for EffectsGroups that act on at least one of the objects in target_objects.
void GetEmpireKnownDestroyedObjects (ObjectKnowledgeMap &empire_known_destroyed_object_ids, int encoding_empire) const
void GetEmpireKnownObjectsToSerialize (EmpireObjectMap &empire_latest_known_objects, int encoding_empire) const
Fills empire_latest_known_objects map with the latest known data about UniverseObjects for the empire with id encoding_empire.
void GetEmpireObjectVisibilityMap (EmpireObjectVisibilityMap &empire_object_visibility, int encoding_empire) const
void GetEmpireObjectVisibilityTurnMap (EmpireObjectVisibilityTurnMap &empire_object_visibility_turns, int encoding_empire) const
void GetEmpireStaleKnowledgeObjects (ObjectKnowledgeMap &empire_stale_knowledge_object_ids, int encoding_empire) const
void GetObjectsToSerialize (ObjectMap &objects, int encoding_empire) const
Fills objects with copies of UniverseObjects that should be sent to the empire with id encoding_empires.
void GetShipDesignsToSerialize (ShipDesignMap &designs_to_serialize, int encoding_empire) const
Fills designs_to_serialize with ShipDesigns known to the empire with the ID encoding empire.
template<typename T , typename... Args>
std::shared_ptr< T > InsertID (int id, Args &&... args)
Inserts object obj into the universe with the given id.
void InsertIDCore (std::shared_ptr< UniverseObject > obj, int id)
Inserts object obj into the universe with the given id.
void ResetObjectMeters (const std::vector< std::shared_ptr< UniverseObject >> &objects, bool target_max_unpaired=true, bool active=true)
void UpdateMeterEstimatesImpl (const std::vector< int > &objects_vec, ScriptingContext &context, bool do_accounting)
Does actual updating of meter estimates after the public function have processed objects_vec or whatever they were passed and cleared the relevant effect accounting for those objects and meters.
bool VerifyUnusedObjectID (const int empire_id, const int id)
Verify that an object ID id could be generated by empire_id.
Private Attributes
std::unique_ptr< IDAllocator > m_design_id_allocator
Manages allocating and verifying new ship design ids.
std::set< int > m_destroyed_object_ids
all ids of objects that have been destroyed (on server) or that a player knows were destroyed (on clients)
Effect::AccountingMap m_effect_accounting_map
map from target object id, to map from target meter, to orderered list of structs with details of an effect and what it does to the meter
DiscrepancyMap m_effect_discrepancy_map
map from target object id, to map from target meter, to discrepancy between meter's actual initial value, and the initial value that this meter should have as far as the client can tell: the unknown factor affecting the meter.
EmpireObjectVisValueRefMap m_effect_specified_empire_object_visibilities
ObjectKnowledgeMap m_empire_known_destroyed_object_ids
map from empire id to (set of object ids that the empire knows have been destroyed)
std::map< int, std::set< int > > m_empire_known_ship_design_ids
ship designs known to each empire
EmpireObjectMap m_empire_latest_known_objects
map from empire id to (map from object id to latest known information about each object by that empire)
EmpireObjectVisibilityMap m_empire_object_visibility
map from empire id to (map from object id to visibility of that object for that empire)
EmpireObjectVisibilityTurnMap m_empire_object_visibility_turns
map from empire id to (map from object id to (map from Visibility rating to turn number on which the empire last saw the object at the indicated Visibility rating or higher)
EmpireObjectSpecialsMap m_empire_object_visible_specials
map from empire id to (map from object id to (set of names of specials that empire can see are on that object))
ObjectKnowledgeMap m_empire_stale_knowledge_object_ids
map from empire id to (set of object ids that the empire has previously observed but has subsequently been unable to detect at its last known location despite expecting to be able to detect it based on stealth of the object and having detectors in range)
bool m_inhibit_universe_object_signals = false
std::map< int, std::set< int > > m_marked_destroyed
used while applying effects to cache objects that have been destroyed. this allows to-be-destroyed objects to remain undestroyed until all effects have been processed, which ensures that to-be-destroyed objects still exist when other effects need to access them as a source object. key is destroyed object, and value set are the ids of objects that caused the destruction (may be multiples destroying a single target on a given turn)
std::unique_ptr< IDAllocator > m_object_id_allocator
Manages allocating and verifying new object ids.
std::unique_ptr< ObjectMap > m_objects
map from object id to UniverseObjects in the universe. for the server: all of them, up to date and true information about object is stored; for clients, only limited information based on what the client knows about is sent.
std::shared_ptr< Pathfinder > m_pathfinder
ShipDesignMap m_ship_designs
ship designs in the universe
std::map< std::string, std::map< int, std::map< int, double > > > m_stat_records
storage for statistics calculated for empires. Indexed by stat name (string), contains a map indexed by empire id, contains a map from turn number (int) to stat value (double).
double m_universe_width = 1000.0
Parsed items
Various unlocked items are kept as a Pending::Pending while being parsed and then transfered.
They are mutable to allow processing in const accessors.
boost::optional< Pending::Pending< std::vector< UnlockableItem > > > m_pending_items = boost::none
boost::optional< Pending::Pending< std::vector< UnlockableItem > > > m_pending_buildings = boost::none
boost::optional< Pending::Pending< std::vector< std::unique_ptr< FleetPlan > > > > m_pending_fleet_plans = boost::none
boost::optional< Pending::Pending< std::vector< std::unique_ptr< MonsterFleetPlan > > > > m_pending_monster_fleet_plans = boost::none
boost::optional< Pending::Pending< EmpireStatsMap > > m_pending_empire_stats = boost::none
std::vector< UnlockableItem > m_unlocked_items
std::vector< UnlockableItem > m_unlocked_buildings
std::vector< std::unique_ptr< FleetPlan > > m_unlocked_fleet_plans
std::vector< std::unique_ptr< MonsterFleetPlan > > m_monster_fleet_plans
EmpireStatsMap m_empire_stats
Friends
template<typename Archive >
void serialize (Archive &, Universe &, unsigned int const)
Detailed Description
The Universe class contains the majority of FreeOrion gamestate: All the UniverseObjects in a game, and (of less importance) all ShipDesigns in a game.
(Other gamestate is contained in the Empire class.) The Universe class also provides functions with which to access objects in it, information about the objects, and information about the objects' relationships to each other. As well, there are functions that generate and populate new Universe gamestates when new games are started.
Member Typedef Documentation
DiscrepancyMap
typedef std::unordered_map<int, boost::container::flat_map<MeterType, double> > Universe::DiscrepancyMap private
Discrepancy between meter's value at start of turn, and the value that this client calculate that the meter should have with the knowledge available -> the unknown factor affecting the meter.
This is used when generating effect accounting, in the case where the expected and actual meter values don't match.
EmpireObjectMap
typedef std::map<int, ObjectMap> Universe::EmpireObjectMap
Known information each empire had about objects in the Universe; keyed by empire id.
EmpireObjectSpecialsMap
typedef std::map<int, ObjectSpecialsMap> Universe::EmpireObjectSpecialsMap
map from empire id to ObjectSpecialsMap of known specials for objects for that empire
EmpireObjectVisibilityMap
typedef std::map<int, ObjectVisibilityMap> Universe::EmpireObjectVisibilityMap
map from empire id to ObjectVisibilityMap for that empire
EmpireObjectVisibilityTurnMap
typedef std::map<int, ObjectVisibilityTurnMap> Universe::EmpireObjectVisibilityTurnMap
Each empire's most recent turns on which object information was known; keyed by empire id.
EmpireObjectVisValueRefMap
typedef std::map<int, ObjSrcVisValRefVecMap> Universe::EmpireObjectVisValueRefMap private
EmpireStatsMap
using Universe::EmpireStatsMap = std::map<std::string, std::unique_ptr<ValueRef::ValueRef<double> >>
Set the empire stats from future.
ObjectKnowledgeMap
typedef std::map<int, std::set<int> > Universe::ObjectKnowledgeMap private
IDs of Empires which know information about an object (or deleted object); keyed by object id.
ObjectSpecialsMap
typedef std::map<int, std::set<std::string> > Universe::ObjectSpecialsMap
map from object id to names of specials on an object
ObjectVisibilityMap
typedef std::map<int, Visibility> Universe::ObjectVisibilityMap
map from object id to Visibility level for a particular empire
ObjectVisibilityTurnMap
typedef std::map<int, VisibilityTurnMap> Universe::ObjectVisibilityTurnMap
Most recent turn number on which the objects were observed at various Visibility ratings; keyed by object id.
ObjSrcVisValRefVecMap
typedef std::map<int, SrcVisValRefVec> Universe::ObjSrcVisValRefVecMap private
ship_design_iterator
typedef ShipDesignMap::const_iterator Universe::ship_design_iterator
const iterator over ship designs created by players that are known by this client
ShipDesignMap
typedef std::map<int, ShipDesign*> Universe::ShipDesignMap
ShipDesigns in universe; keyed by design id.
SrcVisValRefVec
typedef std::vector<std::pair<int, VisValRef> > Universe::SrcVisValRefVec private
UniverseObjectDeleteSignalType
typedef boost::signals2::signal<void (std::shared_ptr<const UniverseObject>)> Universe::UniverseObjectDeleteSignalType
emitted just before the UniverseObject is deleted
VisibilityTurnMap
typedef std::map<Visibility, int> Universe::VisibilityTurnMap
Most recent turn number on which a something, such as a Universe object, was observed at various Visibility ratings or better.
VisValRef
typedef const ValueRef::ValueRef<Visibility>* Universe::VisValRef private
Constructor & Destructor Documentation
Universe()
Universe::Universe ()
~Universe()
Universe::~Universe () virtual
Member Function Documentation
ApplyAllEffectsAndUpdateMeters()
void Universe::ApplyAllEffectsAndUpdateMeters (ScriptingContext & context, bool do_accounting = true)
Determines all effectsgroups' target sets, then resets meters and executes all effects on all objects.
Then clamps meter values so target and max meters are within a reasonable range and any current meters with associated max meters are limited by their max.
References ObjectMap::all(), ScriptingContext::ContextObjects(), ScriptingContext::Empires(), ExecuteEffects(), OptionsDB::Get(), GetEffectsAndTargets(), GetOptionsDB(), m_effect_specified_empire_object_visibilities, and ResetAllObjectMeters().
Referenced by ServerApp::GenerateUniverse(), and ServerApp::PostCombatProcessTurns().
ApplyAppearanceEffects() [1/2]
void Universe::ApplyAppearanceEffects (const std::vector< int > & object_ids, ScriptingContext & context)
Executes effects that modify objects' appearance in the human client.
References ExecuteEffects(), GetEffectsAndTargets(), and to_string().
Referenced by MapWnd::InitTurn().
ApplyAppearanceEffects() [2/2]
void Universe::ApplyAppearanceEffects (ScriptingContext & context)
Executes effects that modify objects' apperance for all objects.
References ExecuteEffects(), and GetEffectsAndTargets().
ApplyEffectDerivedVisibilities()
void Universe::ApplyEffectDerivedVisibilities (EmpireManager & empires)
Applies empire-object visibilities set by effects.
References ALL_EMPIRES, INVALID_OBJECT_ID, m_effect_specified_empire_object_visibilities, m_empire_object_visibility, and m_objects.
Referenced by UpdateEmpireObjectVisibilities().
ApplyGenerateSitRepEffects()
void Universe::ApplyGenerateSitRepEffects (ScriptingContext & context)
Executes effects that modify objects' apperance for all objects.
References ExecuteEffects(), and GetEffectsAndTargets().
Referenced by ServerApp::NewGameInitConcurrentWithJoiners().
ApplyMeterEffectsAndUpdateMeters() [1/2]
void Universe::ApplyMeterEffectsAndUpdateMeters (const std::vector< int > & object_ids, ScriptingContext & context, bool do_accounting = true)
Determines all effectsgroups' target sets, then resets meters and executes only SetMeter effects on all objects whose ids are listed in object_ids.
Then clamps meter values so target and max meters are within a reasonable range and any current meters with associated max meters are limited by their max.
References ScriptingContext::ContextObjects(), ExecuteEffects(), ObjectMap::find(), OptionsDB::Get(), GetEffectsAndTargets(), GetOptionsDB(), ResetObjectMeters(), and to_string().
Referenced by ServerApp::GenerateUniverse(), ServerApp::PostCombatProcessTurns(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop().
ApplyMeterEffectsAndUpdateMeters() [2/2]
void Universe::ApplyMeterEffectsAndUpdateMeters (ScriptingContext & context, bool do_accounting = true)
Calls above ApplyMeterEffectsAndUpdateMeters() function on all objects.
References ObjectMap::all(), ScriptingContext::ContextObjects(), ScriptingContext::Empires(), ExecuteEffects(), OptionsDB::Get(), GetEffectsAndTargets(), GetOptionsDB(), and TraceLogger.
BackPropagateObjectMeters()
void Universe::BackPropagateObjectMeters ()
Sets all objects' meters' initial values to their current values.
References m_objects.
Referenced by ServerApp::GenerateUniverse(), and ServerApp::PostCombatProcessTurns().
beginShipDesigns()
ship_design_iterator Universe::beginShipDesigns () const inline
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), CompletedDesignsListBox::PopulateCore(), MonstersListBox::PopulateCore(), and AllDesignsListBox::PopulateCore().
Clear()
void Universe::Clear ()
Clears main ObjectMap, empires' latest known objects map, and ShipDesign map.
References m_destroyed_object_ids, m_effect_accounting_map, m_effect_discrepancy_map, m_effect_specified_empire_object_visibilities, m_empire_known_destroyed_object_ids, m_empire_known_ship_design_ids, m_empire_latest_known_objects, m_empire_object_visibility, m_empire_object_visibility_turns, m_empire_object_visible_specials, m_empire_stale_knowledge_object_ids, m_marked_destroyed, m_objects, m_pathfinder, m_ship_designs, m_stat_records, m_universe_width, and ResetAllIDAllocation().
Referenced by ServerApp::GenerateUniverse(), LoadGame(), GGHumanClientApp::ResetClientData(), and serialize().
CountDestructionInStats()
void Universe::CountDestructionInStats (int object_id, int source_object_id, ScriptingContext & context)
Record in statistics that object_id was destroyed by species/empire associated with source_object_id.
References ScriptingContext::ContextObjects(), ObjectMap::get(), and ScriptingContext::GetEmpire().
Referenced by ExecuteEffects().
Delete()
bool Universe::Delete (int object_id)
Permanently deletes object with ID number object_id.
no information about this object is retained in the Universe. Can be performed on objects whether or not the have been destroyed. Returns true if such an object was found, false otherwise.
References DebugLogger, ErrorLogger, and m_objects.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
DeleteShipDesign()
bool Universe::DeleteShipDesign (int design_id)
Permanently deletes the ship design with ID number design_id.
No information about this design is retained in the Universe.
References m_ship_designs.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag().
Destroy()
void Universe::Destroy (int object_id, bool update_destroyed_object_knowers = true)
Removes the object with ID number object_id from the universe's map of existing objects, and adds the object's id to the set of destroyed object ids.
If update_destroyed_object_knowers is true, empires that currently have visibility of the object have its id added to their set of objects' ids that are known to have been destroyed. Older or limited versions of objects remain in empires latest known objects ObjectMap, regardless of whether the empire knows the object is destroyed.
References Empires(), ErrorLogger, m_destroyed_object_ids, m_objects, SetEmpireKnowledgeOfDestroyedObject(), and UniverseObjectDeleteSignal.
Referenced by anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{Planet.cpp}::PlanetSizeIncrement(), and RecursiveDestroy().
DestroyedObjectIds()
const std::set< int > & Universe::DestroyedObjectIds () const
Returns IDs of objects that have been destroyed.
References m_destroyed_object_ids.
Referenced by GetEffectsAndTargets(), MapWnd::InitVisibilityRadiiRenderingBuffers(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToPrevFleet(), and MapWnd::ZoomToPrevIdleFleet().
EffectDestroy()
void Universe::EffectDestroy (int object_id, int source_object_id = INVALID_OBJECT_ID)
Used by the Destroy effect to mark an object for destruction later during turn processing.
(objects can't be destroyed immediately as other effects might depend on their existence)
References m_marked_destroyed.
Referenced by Effect::SetOwner::Execute(), Effect::Destroy::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), and Effect::MoveTowards::Execute().
EmpireKnownDestroyedObjectIDs()
const std::set< int > & Universe::EmpireKnownDestroyedObjectIDs (int empire_id) const
Returns IDs of objects that the Empire with id empire_id knows have been destroyed.
Each empire's latest known objects data contains the last known information about each object, whether it has been destroyed or not. If empire_id = ALL_EMPIRES an empty set of IDs is returned.
References m_destroyed_object_ids, and m_empire_known_destroyed_object_ids.
Referenced by anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), MapWnd::DeferredRefreshFleetButtons(), MapWnd::DispatchFleetsExploring(), MapWnd::InitTurnRendering(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), ServerApp::PostCombatProcessTurns(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), ShipsListBox::Refresh(), MapWnd::RefreshFleetResourceIndicator(), MapWnd::RenderSystems(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), BuildingsPanel::Update(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues(), and FreeOrionPython::WrapUniverseClasses().
EmpireKnownObjects() [1/2]
const ObjectMap & Universe::EmpireKnownObjects (int empire_id = ALL_EMPIRES) const
Returns latest known state of objects for the Empire with id empire_id or the true / complete state of all objects in this Universe (the same as calling Objects()) if empire_id is ALL_EMPIRES.
References ALL_EMPIRES, m_empire_latest_known_objects, and m_objects.
Referenced by anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), ServerApp::EmpireKnownObjects(), ClientApp::EmpireKnownObjects(), ForgetKnownObject(), and anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters().
EmpireKnownObjects() [2/2]
ObjectMap & Universe::EmpireKnownObjects (int empire_id = ALL_EMPIRES)
References ALL_EMPIRES, ObjectMap::clear(), m_empire_latest_known_objects, and m_objects.
EmpireKnownShipDesignIDs()
const std::set< int > & Universe::EmpireKnownShipDesignIDs (int empire_id) const
Returns IDs of ship designs that the Empire with id empire_id has seen during the game.
If empire_id = ALL_EMPIRES an empty set of ids is returned
References m_empire_known_ship_design_ids.
Referenced by ShipDesignOrder::ExecuteImpl().
EmpireStaleKnowledgeObjectIDs()
const std::set< int > & Universe::EmpireStaleKnowledgeObjectIDs (int empire_id) const
Returns IDs of objects that the Empire with id empire_id has stale knowledge of in its latest known objects.
The latest known data about these objects suggests that they should be visible, but they are not.
References m_empire_stale_knowledge_object_ids.
Referenced by MapWnd::DeferredRefreshFleetButtons(), MapWnd::InitTurnRendering(), MapWnd::InitVisibilityRadiiRenderingBuffers(), FleetWnd::Refresh(), ShipsListBox::Refresh(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), BuildingsPanel::Update(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update().
EmpireStats()
const Universe::EmpireStatsMap & Universe::EmpireStats () const private
References m_empire_stats, m_pending_empire_stats, and Pending::SwapPending().
Referenced by UpdateStatRecords().
EmpireVisibleObjectIDs()
std::set< int > Universe::EmpireVisibleObjectIDs (int empire_id, const EmpireManager & empires) const
Returns IDs of objects that the Empire with id empire_id has vision of on the current turn, or objects that at least one empire has vision of on the current turn if empire_id = ALL_EMPIRES.
References ALL_EMPIRES, GetObjectVisibilityByEmpire(), and m_objects.
endShipDesigns()
ship_design_iterator Universe::endShipDesigns () const inline
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), CompletedDesignsListBox::PopulateCore(), MonstersListBox::PopulateCore(), AllDesignsListBox::PopulateCore(), and BuildDesignatorWnd::BuildSelector::PopulateList().
ExecuteEffects()
void Universe::ExecuteEffects (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > & source_effects_targets_causes, ScriptingContext & context, bool update_effect_accounting, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) private
Executes all effects.
For use on server when processing turns. If only_meter_effects is true, then only SetMeter effects are executed. This is useful on server or clients to update meter values after the rest of effects (including non-meter effects) have been executed.
References ScriptingContext::ContextObjects(), ScriptingContext::ContextUniverse(), CountDestructionInStats(), ObjectMap::get(), m_effect_accounting_map, m_marked_destroyed, m_objects, RecursiveDestroy(), TraceLogger, and WarnLogger.
Referenced by ApplyAllEffectsAndUpdateMeters(), ApplyAppearanceEffects(), ApplyGenerateSitRepEffects(), ApplyMeterEffectsAndUpdateMeters(), and UpdateMeterEstimatesImpl().
ForgetKnownObject()
void Universe::ForgetKnownObject (int empire_id, int object_id)
If an empire_id can't currently see object_id, then remove object_id' object from the object map and the set of known objects.
References ALL_EMPIRES, EmpireKnownObjects(), ObjectMap::empty(), ObjectMap::erase(), ErrorLogger, ObjectMap::get(), and INVALID_OBJECT_ID.
Referenced by ForgetOrder::ExecuteImpl(), and MapWnd::ForgetObject().
GenerateDesignID()
int Universe::GenerateDesignID () private
Generates design ID for a new (ship) design.
Usually used by the server to service new ID requests.
References m_design_id_allocator.
Referenced by InsertShipDesign().
GenerateObjectID()
int Universe::GenerateObjectID () private
Generates an object ID for a future object.
Usually used by the server to service new ID requests.
References m_object_id_allocator.
GetDestroyedObjectsToSerialize()
void Universe::GetDestroyedObjectsToSerialize (std::set< int > & destroyed_object_ids, int encoding_empire) const private
Fills destroyed_object_ids with ids of objects known to be destroyed by the empire with ID encoding empire.
If encoding_empire is ALL_EMPIRES, then all destroyed objects are included.
References ALL_EMPIRES, m_destroyed_object_ids, and m_empire_known_destroyed_object_ids.
Referenced by serialize().
GetEffectAccountingMap() [1/2]
const Effect::AccountingMap& Universe::GetEffectAccountingMap () const inline
Returns map, indexed by object id, to map, indexed by MeterType, to vector of EffectAccountInfo for the meter, in order effects were applied to the meter.
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), UpdateMeterEstimatesImpl(), and FreeOrionPython::WrapUniverseClasses().
GetEffectAccountingMap() [2/2]
Effect::AccountingMap& Universe::GetEffectAccountingMap () inline
GetEffectsAndTargets() [1/2]
void Universe::GetEffectsAndTargets (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > & source_effects_targets_causes, const ScriptingContext & context, bool only_meter_effects = false) const private
Clears source_effects_targets_causes, and then populates with all EffectsGroups and their targets in the known universe.
Referenced by ApplyAllEffectsAndUpdateMeters(), ApplyAppearanceEffects(), ApplyGenerateSitRepEffects(), ApplyMeterEffectsAndUpdateMeters(), and UpdateMeterEstimatesImpl().
GetEffectsAndTargets() [2/2]
void Universe::GetEffectsAndTargets (std::map< int, Effect::SourcesEffectsTargetsAndCausesVec > & source_effects_targets_causes, const std::vector< int > & target_objects, const ScriptingContext & context, bool only_meter_effects = false) const private
Removes entries in source_effects_targets_causes about effects groups acting on objects in target_objects, and then repopulates for EffectsGroups that act on at least one of the objects in target_objects.
If target_objects is empty then default target candidates will be used.
References ObjectMap::all(), ScriptingContext::ContextObjects(), ScriptingContext::ContextUniverse(), DestroyedObjectIds(), anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations(), Policy::Effects(), Special::Effects(), Tech::Effects(), EffectsProcessingThreads(), Empires(), ScriptingContext::Empires(), SectionedScopedTimer::EnterSection(), ErrorLogger, ObjectMap::find(), GetBuildingType(), GetBuildingTypeManager(), GetFieldType(), GetFieldTypeManager(), GetPolicy(), GetShipHull(), GetShipHullManager(), GetShipPart(), GetShipPartManager(), GetSpecial(), GetSpecies(), GetTech(), ShipDesign::Hull(), boost::asio::thread_pool::join(), ShipDesign::Parts(), SpecialNames(), parse::species(), ScriptingContext::species, and TraceLogger.
GetEmpireKnownDestroyedObjects()
void Universe::GetEmpireKnownDestroyedObjects (ObjectKnowledgeMap & empire_known_destroyed_object_ids, int encoding_empire) const private
References ALL_EMPIRES, and m_empire_known_destroyed_object_ids.
Referenced by serialize().
GetEmpireKnownObjectsToSerialize()
void Universe::GetEmpireKnownObjectsToSerialize (EmpireObjectMap & empire_latest_known_objects, int encoding_empire) const private
Fills empire_latest_known_objects map with the latest known data about UniverseObjects for the empire with id encoding_empire.
If the encoding empire is ALL_EMPIRES then all stored empire object knowledge is included.
References ALL_EMPIRES, ObjectMap::CopyForSerialize(), DebugLogger, anonymous_namespace{Universe.cpp}::ENABLE_VISIBILITY_EMPIRE_MEMORY, and m_empire_latest_known_objects.
Referenced by serialize().
GetEmpireObjectVisibility()
const Universe::EmpireObjectVisibilityMap & Universe::GetEmpireObjectVisibility () const
References m_empire_object_visibility.
GetEmpireObjectVisibilityMap()
void Universe::GetEmpireObjectVisibilityMap (EmpireObjectVisibilityMap & empire_object_visibility, int encoding_empire) const private
References ALL_EMPIRES, GetObjectVisibilityByEmpire(), m_empire_object_visibility, m_objects, and VIS_NO_VISIBILITY().
Referenced by serialize().
GetEmpireObjectVisibilityTurnMap() [1/2]
const Universe::EmpireObjectVisibilityTurnMap & Universe::GetEmpireObjectVisibilityTurnMap () const
References m_empire_object_visibility_turns.
Referenced by serialize().
GetEmpireObjectVisibilityTurnMap() [2/2]
void Universe::GetEmpireObjectVisibilityTurnMap (EmpireObjectVisibilityTurnMap & empire_object_visibility_turns, int encoding_empire) const private
References ALL_EMPIRES, and m_empire_object_visibility_turns.
GetEmpireStaleKnowledgeObjects()
void Universe::GetEmpireStaleKnowledgeObjects (ObjectKnowledgeMap & empire_stale_knowledge_object_ids, int encoding_empire) const private
References ALL_EMPIRES, and m_empire_stale_knowledge_object_ids.
Referenced by serialize().
GetGenericShipDesign()
const ShipDesign * Universe::GetGenericShipDesign (const std::string & name) const
References m_ship_designs, and ShipDesign::Name().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateShip::Execute(), Effect::GenerateSitRepMessage::Execute(), anonymous_namespace{VarText.cpp}::PredefinedShipDesignString(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate(), and FreeOrionPython::WrapUniverseClasses().
GetObjectsToSerialize()
void Universe::GetObjectsToSerialize (ObjectMap & objects, int encoding_empire) const private
Fills objects with copies of UniverseObjects that should be sent to the empire with id encoding_empires.
References ALL_EMPIRES, ObjectMap::AuditContainment(), ObjectMap::clear(), ObjectMap::Copy(), ObjectMap::CopyForSerialize(), anonymous_namespace{Universe.cpp}::ENABLE_VISIBILITY_EMPIRE_MEMORY, m_empire_known_destroyed_object_ids, m_empire_latest_known_objects, and m_objects.
Referenced by serialize().
GetObjectVisibilityByEmpire()
Visibility Universe::GetObjectVisibilityByEmpire (int object_id, int empire_id) const
Returns the Visibility level of empire with id empire_id of UniverseObject with id object_id as determined by calling UpdateEmpireObjectVisibilities.
References ALL_EMPIRES, m_empire_object_visibility, and VIS_NO_VISIBILITY().
Referenced by Building::Clone(), Ship::Clone(), Field::Clone(), Building::Copy(), Field::Copy(), Ship::Copy(), EmpireVisibleObjectIDs(), ValueRef::ComplexVariable< T >::Eval(), MapWnd::FleetButtonRightClicked(), GetEmpireObjectVisibilityMap(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), MapWnd::InitFieldRenderingBuffers(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), FleetButton::Refresh(), SidePanel::PlanetPanel::Refresh(), RotatingPlanetControl::Refresh(), MapWnd::RenderSystems(), anonymous_namespace{Fleet.cpp}::TruncateRouteToEndAtSystem(), and FreeOrionPython::WrapUniverseClasses().
GetObjectVisibilityTurnMapByEmpire()
const Universe::VisibilityTurnMap & Universe::GetObjectVisibilityTurnMapByEmpire (int object_id, int empire_id) const
Returns the map from Visibility level to turn number on which the empire with id empire_id last had the various Visibility levels of the UniverseObject with id object_id .
The returned map may be empty or not have entries for all visibility levels, if the empire has not seen the object at that visibility level yet.
References m_empire_object_visibility_turns.
Referenced by MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetWnd::FleetRightClicked(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), FleetDetailPanel::ShipRightClicked(), and FreeOrionPython::WrapUniverseClasses().
GetObjectVisibleSpecialsByEmpire()
std::set< std::string > Universe::GetObjectVisibleSpecialsByEmpire (int object_id, int empire_id) const
Returns the set of specials attached to the object with id object_id that the empire with id empire_id can see this turn.
References ALL_EMPIRES, m_empire_object_visible_specials, and m_objects.
Referenced by Building::Copy(), Field::Copy(), Ship::Copy(), and anonymous_namespace{Fleet.cpp}::TruncateRouteToEndAtSystem().
GetPathfinder()
std::shared_ptr<const Pathfinder> Universe::GetPathfinder () const inline
Return the Pathfinder.
Referenced by ValueRef::Variable< ToType >::Eval(), Condition::WithinStarlaneJumps::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetDestination::Execute(), FleetMoveOrder::FleetMoveOrder(), GetPathfinder(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{Fleet.cpp}::HasXShips(), Condition::WithinStarlaneJumps::Match(), MapWnd::PlotFleetMovement(), anonymous_namespace{ServerWrapper.cpp}::SystemsWithinJumps(), anonymous_namespace{Effects.cpp}::UpdateFleetRoute(), FreeOrionPython::WrapServer(), and FreeOrionPython::WrapUniverseClasses().
GetShipDesign()
const ShipDesign * Universe::GetShipDesign (int ship_design_id) const
returns the ship design with id ship_design id, or 0 if non exists
References INVALID_DESIGN_ID, and m_ship_designs.
Referenced by Ship::AllWeaponsDamage(), Ship::AllWeaponsMaxDamage(), CompletedDesignsListBox::BaseLeftClicked(), MonstersListBox::BaseLeftClicked(), AllDesignsListBox::BaseLeftClicked(), CompletedDesignsListBox::BaseRightClicked(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns(), CompletedDesignsListBox::ChildrenDraggedAwayCore(), MonstersListBox::ChildrenDraggedAwayCore(), AllDesignsListBox::ChildrenDraggedAwayCore(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), Ship::Design(), DesignWnd::MainPanel::EditingCurrentDesign(), ValueRef::NameLookup::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateShip::Execute(), ShipDesignOrder::ExecuteImpl(), Ship::HasTag(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsObsolete(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue(), ObjectListWnd::ObjectRightClicked(), Condition::anonymous_namespace{Conditions.cpp}::PredefinedShipDesignSimpleMatch::operator()(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), CompletedDesignsListBox::PopulateCore(), BuildDesignatorWnd::BuildSelector::PopulateList(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), BuildDesignatorWnd::SetBuild(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), anonymous_namespace{VarText.cpp}::ShipDesignString(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), and FreeOrionPython::WrapUniverseClasses().
GetShipDesignsToSerialize()
void Universe::GetShipDesignsToSerialize (ShipDesignMap & designs_to_serialize, int encoding_empire) const private
Fills designs_to_serialize with ShipDesigns known to the empire with the ID encoding empire.
If encoding_empire is ALL_EMPIRES, then all designs are included.
References ALL_EMPIRES, ShipDesign::DesignedByEmpire(), ErrorLogger, ShipDesign::ID(), ShipDesign::IsMonster(), m_empire_known_ship_design_ids, and m_ship_designs.
Referenced by serialize().
GetStatRecords()
const std::map<std::string, std::map<int, std::map<int, double> > >& Universe::GetStatRecords () const inline
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), EncyclopediaDetailPanel::RefreshImpl(), and FreeOrionPython::WrapUniverseClasses().
HighestDestroyedObjectID()
int Universe::HighestDestroyedObjectID () const
References INVALID_OBJECT_ID, and m_destroyed_object_ids.
InhibitUniverseObjectSignals()
void Universe::InhibitUniverseObjectSignals (bool inhibit = true)
Sets whether to inhibit UniverseObjectSignals.
Inhibits if inhibit is true, and (re)enables UniverseObjectSignals if inhibit is false.
References m_inhibit_universe_object_signals.
Referenced by AutomaticallyChosenColonyShip(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), FleetDataPanel::ToggleAggression(), and anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates().
InitializeSystemGraph()
void Universe::InitializeSystemGraph (const EmpireManager & empires, const ObjectMap & objects)
Fills pathfinding data structure and determines least jumps distances between systems based on the objects in objects.
References m_pathfinder.
Referenced by GenerateStarlanes(), AIClientApp::HandleMessage(), ServerApp::LoadGameInit(), MapWnd::MidTurnUpdate(), and ServerApp::PostCombatProcessTurns().
InitiallyUnlockedBuildings()
const std::vector< UnlockableItem > & Universe::InitiallyUnlockedBuildings () const
Buildings unlocked before turn 1.
References m_pending_buildings, m_unlocked_buildings, and Pending::SwapPending().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings().
InitiallyUnlockedFleetPlans()
std::vector< const FleetPlan * > Universe::InitiallyUnlockedFleetPlans () const
Fleets unlocked before turn 1.
References m_pending_fleet_plans, m_unlocked_fleet_plans, and Pending::SwapPending().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadFleetPlanList().
InitiallyUnlockedItems()
const std::vector< UnlockableItem > & Universe::InitiallyUnlockedItems () const
Items unlocked before turn 1.
References m_pending_items, m_unlocked_items, and Pending::SwapPending().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadUnlockableItemList().
InitMeterEstimatesAndDiscrepancies()
void Universe::InitMeterEstimatesAndDiscrepancies (ScriptingContext & context)
For all objects and meters, determines discrepancies between actual meter maxes and what the known universe should produce, and and stores in m_effect_discrepancy_map.
References DebugLogger, ErrorLogger, INVALID_OBJECT_ID, m_destroyed_object_ids, m_effect_accounting_map, m_effect_discrepancy_map, m_objects, TraceLogger, and UpdateMeterEstimates().
Referenced by anonymous_namespace{AIWrapper.cpp}::InitMeterEstimatesAndDiscrepancies(), and MapWnd::InitTurn().
InsertByEmpireWithID()
template<typename T , typename... Args> std::shared_ptr<T> Universe::InsertByEmpireWithID (int empire_id, int id, Args &&... args) inline
empire_id inserts object obj into the universe with the given id.
This is provided for use with Orders which are run once on the client and receive a new id and then are run a second time on the server using the id assigned on the client.
References tag_parser::args.
Referenced by NewFleetOrder::ExecuteImpl().
InsertID()
template<typename T , typename... Args> std::shared_ptr<T> Universe::InsertID (int id, Args &&... args) inline private
Inserts object obj into the universe with the given id.
References tag_parser::args.
InsertIDCore()
void Universe::InsertIDCore (std::shared_ptr< UniverseObject > obj, int id) private
Inserts object obj into the universe with the given id.
References ErrorLogger, INVALID_OBJECT_ID, m_object_id_allocator, and m_objects.
InsertNew()
template<typename T , typename... Args> std::shared_ptr<T> Universe::InsertNew (Args &&... args) inline
InsertNew constructs and inserts a UniverseObject into the object map with a new id.
It returns the new object.
References tag_parser::args.
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{ServerWrapper.cpp}::CreateSystem(), Moderator::CreateSystem::Execute(), Moderator::CreatePlanet::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), NewFleetOrder::ExecuteImpl(), and anonymous_namespace{Empire.cpp}::SanitizeResearchQueue().
InsertShipDesign()
bool Universe::InsertShipDesign (ShipDesign * ship_design)
Inserts ship_design into the universe.
Return true on success. The ship design's id will be the newly assigned id.
Note
Universe gains ownership of ship_design once inserted.
References GenerateDesignID(), ShipDesign::ID(), InsertShipDesignID(), INVALID_DESIGN_ID, and m_ship_designs.
Referenced by anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse(), ShipDesignOrder::ExecuteImpl(), and anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate().
InsertShipDesignID()
bool Universe::InsertShipDesignID (ShipDesign * ship_design, boost::optional< int > empire_id, int id)
Inserts ship_design into the universe with given id; returns true on success, or false on failure.
An empire id of none indicates that the server is allocating an id on behalf of itself. This can be removed when no longer supporting legacy id allocation in pending Orders.
Note
Universe gains ownership of ship_design once inserted.
References ErrorLogger, m_design_id_allocator, m_ship_designs, and ShipDesign::SetID().
Referenced by ShipDesignOrder::ExecuteImpl(), InsertShipDesign(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag().
InsertTemp()
template<typename T , typename... Args> std::shared_ptr<T> Universe::InsertTemp (Args &&... args) inline
InsertTemp constructs and inserts a temporary UniverseObject into the object map with a temporary id.
It returns the new object.
References tag_parser::args, and TEMPORARY_OBJECT_ID.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
MonsterFleetPlans()
std::vector< const MonsterFleetPlan * > Universe::MonsterFleetPlans () const
Items unlocked before turn 1.
References m_monster_fleet_plans, m_pending_monster_fleet_plans, and Pending::SwapPending().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadMonsterFleetPlanList().
NumShipDesigns()
size_t Universe::NumShipDesigns () const inline
References anonymous_namespace{CombatSystem.cpp}::GetObjectVisibilityByEmpire().
ObfuscateIDGenerator()
void Universe::ObfuscateIDGenerator ()
ObfuscateIDGenerator applies randomization to the IDAllocator to prevent clients from inferring too much information about other client's id generation activities.
References m_design_id_allocator, and m_object_id_allocator.
Referenced by ServerApp::PostCombatProcessTurns().
Objects() [1/2]
const ObjectMap& Universe::Objects () const inline
Returns objects in this Universe.
Referenced by anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo(), BuildDesignatorWnd::CenterOnBuild(), ServerApp::CheckForEmpireElimination(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), CombatInfo::CombatInfo(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), MapWnd::DoFleetButtonsLayout(), ServerApp::EliminatePlayer(), ClientApp::EmpireKnownObjects(), MessageWndEdit::FindGameWords(), FleetMoveOrder::FleetMoveOrder(), MapWnd::ForgetObject(), ServerApp::GenerateUniverse(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), ClientApp::GetVisibleObjectName(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), AIClientApp::HandleMessage(), anonymous_namespace{Fleet.cpp}::HasXShips(), MapWnd::InitTurn(), ServerApp::LoadGameInit(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), ServerApp::ProcessCombats(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), MapWnd::ReselectLastFleet(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetAllSystemsBasicallyVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), FleetDataPanel::SetStatIconValues(), anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies(), FleetWnd::UniverseObjectDeleted(), anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates(), ServerApp::UpdateMonsterTravelRestrictions(), FreeOrionPython::WrapUniverseClasses(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToPrevFleet(), and MapWnd::ZoomToPrevIdleFleet().
Objects() [2/2]
ObjectMap& Universe::Objects () inline
References ALL_EMPIRES, tag_parser::description, and EmpireKnownObjects().
operator=()
Universe & Universe::operator= (Universe && other) noexcept
References m_design_id_allocator, m_destroyed_object_ids, m_effect_accounting_map, m_effect_discrepancy_map, m_effect_specified_empire_object_visibilities, m_empire_known_destroyed_object_ids, m_empire_known_ship_design_ids, m_empire_latest_known_objects, m_empire_object_visibility, m_empire_object_visibility_turns, m_empire_object_visible_specials, m_empire_stale_knowledge_object_ids, m_empire_stats, m_inhibit_universe_object_signals, m_marked_destroyed, m_monster_fleet_plans, m_object_id_allocator, m_objects, m_pathfinder, m_ship_designs, m_stat_records, m_universe_width, m_unlocked_buildings, m_unlocked_fleet_plans, and m_unlocked_items.
RecursiveDestroy()
std::set< int > Universe::RecursiveDestroy (int object_id)
Destroys object with ID object_id, and destroys any associted objects, such as contained buildings of planets, contained anything of systems, or fleets if their last ship has id object_id and the fleet is thus empty.
Returns the ids of all destroyed objects.
References DebugLogger, Destroy(), INVALID_OBJECT_ID, and m_objects.
Referenced by anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), ServerApp::EliminatePlayer(), Moderator::DestroyUniverseObject::Execute(), ExecuteEffects(), and anonymous_namespace{ServerApp.cpp}::HandleInvasion().
RenameShipDesign()
void Universe::RenameShipDesign (int design_id, const std::string & name = "", const std::string & description = "")
References DebugLogger, m_ship_designs, ShipDesign::SetDescription(), and ShipDesign::SetName().
Referenced by ShipDesignOrder::ExecuteImpl().
ResetAllIDAllocation()
void Universe::ResetAllIDAllocation (const std::vector< int > & empire_ids = std::vector<int>())
Reset object and ship design id allocation for a new game.
References ALL_EMPIRES, DebugLogger, INVALID_DESIGN_ID, INVALID_OBJECT_ID, m_design_id_allocator, m_object_id_allocator, m_objects, m_ship_designs, and TEMPORARY_OBJECT_ID.
Referenced by Clear(), ServerApp::GenerateUniverse(), and serialize().
ResetAllObjectMeters()
void Universe::ResetAllObjectMeters (bool target_max_unpaired = true, bool active = true)
Resets meters.
References m_objects.
Referenced by ApplyAllEffectsAndUpdateMeters(), and ServerApp::PreCombatProcessTurns().
ResetObjectMeters()
void Universe::ResetObjectMeters (const std::vector< std::shared_ptr< UniverseObject >> & objects, bool target_max_unpaired = true, bool active = true) private
Referenced by ApplyMeterEffectsAndUpdateMeters().
SetEffectDerivedVisibility()
void Universe::SetEffectDerivedVisibility (int empire_id, int object_id, int source_id, const ValueRef::ValueRef< Visibility > * vis)
Sets a special record of visibility that overrides the standard empire-object visibility after the latter is processed.
References ALL_EMPIRES, INVALID_OBJECT_ID, and m_effect_specified_empire_object_visibilities.
Referenced by Effect::SetVisibility::Execute().
SetEmpireKnowledgeOfDestroyedObject()
void Universe::SetEmpireKnowledgeOfDestroyedObject (int object_id, int empire_id)
Adds the object ID object_id to the set of object ids for the empire with id empire_id that the empire knows have been destroyed.
References ErrorLogger, GetEmpire(), INVALID_OBJECT_ID, and m_empire_known_destroyed_object_ids.
Referenced by Destroy(), and anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo().
SetEmpireKnowledgeOfShipDesign()
void Universe::SetEmpireKnowledgeOfShipDesign (int ship_design_id, int empire_id)
Adds the ship design ID ship_design_id to the set of ship design ids known by the empire with id empire_id.
References ALL_EMPIRES, ErrorLogger, GetEmpire(), INVALID_DESIGN_ID, and m_empire_known_ship_design_ids.
Referenced by anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), Effect::CreateShip::Execute(), Effect::GenerateSitRepMessage::Execute(), ShipDesignOrder::ExecuteImpl(), SetEmpireObjectVisibility(), and anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies().
SetEmpireObjectVisibility()
void Universe::SetEmpireObjectVisibility (int empire_id, int object_id, Visibility vis)
Sets visibility for indicated empire_id of object with object_id a vis.
References ALL_EMPIRES, INVALID_OBJECT_ID, m_empire_object_visibility, m_objects, SetEmpireKnowledgeOfShipDesign(), and VIS_NO_VISIBILITY().
Referenced by anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), NewFleetOrder::ExecuteImpl(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetAllSystemsBasicallyVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireObjectVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), and anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible().
SetEmpireSpecialVisibility()
void Universe::SetEmpireSpecialVisibility (int empire_id, int object_id, const std::string & special_name, bool visible = true)
Sets visibility for indicated empire_id for the indicated special.
References ALL_EMPIRES, INVALID_OBJECT_ID, and m_empire_object_visible_specials.
Referenced by anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires().
SetEmpireStats()
void Universe::SetEmpireStats (Pending::Pending< EmpireStatsMap > future)
References m_pending_empire_stats.
Referenced by ServerApp::StartBackgroundParsing().
SetInitiallyUnlockedBuildings()
void Universe::SetInitiallyUnlockedBuildings (Pending::Pending< std::vector< UnlockableItem >> && future)
Set buildings unlocked before turn 1 from future.
References m_pending_buildings.
Referenced by ServerApp::StartBackgroundParsing().
SetInitiallyUnlockedFleetPlans()
void Universe::SetInitiallyUnlockedFleetPlans (Pending::Pending< std::vector< std::unique_ptr< FleetPlan >>> && future)
Set fleets unlocked before turn 1 from future.
References m_pending_fleet_plans.
Referenced by ServerApp::StartBackgroundParsing().
SetInitiallyUnlockedItems()
void Universe::SetInitiallyUnlockedItems (Pending::Pending< std::vector< UnlockableItem >> && future)
Set items unlocked before turn 1 from future.
References m_pending_items.
Referenced by ServerApp::StartBackgroundParsing().
SetMonsterFleetPlans()
void Universe::SetMonsterFleetPlans (Pending::Pending< std::vector< std::unique_ptr< MonsterFleetPlan >>> && future)
Set items unlocked before turn 1 from future.
References m_pending_monster_fleet_plans.
Referenced by ServerApp::StartBackgroundParsing().
SetUniverseWidth()
void Universe::SetUniverseWidth (double width) inline
Referenced by FreeOrionPython::WrapServer().
UniverseObjectSignalsInhibited()
const bool & Universe::UniverseObjectSignalsInhibited ()
Returns true if UniverseOjbectSignals are inhibited, false otherwise.
References m_inhibit_universe_object_signals.
UniverseWidth()
double Universe::UniverseWidth () const
References m_universe_width.
Referenced by Delauney::DelauneyTriangulate(), ValueRef::Variable< ToType >::Eval(), MapWnd::RenderStarfields(), and FreeOrionPython::WrapServer().
UpdateEmpireLatestKnownObjectsAndVisibilityTurns()
void Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns ()
Stores latest known information about each object for each empire and updates the record of the last turn on which each empire has visibility of object that can be seen on the current turn with the level of visibility that the empire has this turn.
References CurrentTurn(), ErrorLogger, ObjectMap::get(), ObjectMap::insert(), INVALID_GAME_TURN, m_empire_latest_known_objects, m_empire_object_visibility, m_empire_object_visibility_turns, m_objects, and VIS_NO_VISIBILITY().
Referenced by ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), and ServerApp::ProcessCombats().
UpdateEmpireObjectVisibilities()
void Universe::UpdateEmpireObjectVisibilities (EmpireManager & empires)
Determines which empires can see which objects at what visibility level, based on.
References ApplyEffectDerivedVisibilities(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), GetGameRules(), anonymous_namespace{EncyclopediaParser.cpp}::insert, m_empire_known_ship_design_ids, m_empire_object_visibility, m_empire_object_visible_specials, m_objects, anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToSystemsAlongStarlanes(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetAllSystemsBasicallyVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireObjectVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), and anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies().
Referenced by ServerApp::GenerateUniverse(), ServerApp::PostCombatProcessTurns(), and ServerApp::PreCombatProcessTurns().
UpdateEmpireStaleObjectKnowledge()
void Universe::UpdateEmpireStaleObjectKnowledge (EmpireManager & empires)
Checks latest known information about each object for each empire and, in cases when the latest known state (stealth and location) suggests that the empire should be able to see the object, but the object can't be seen by the empire, updates the latest known state to note this.
References ObjectMap::all(), anonymous_namespace{Universe.cpp}::FilterObjectIDsByKnownDestruction(), anonymous_namespace{Universe.cpp}::FilterObjectPositionsByDetectorPositionsAndRanges(), ObjectMap::find(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), m_empire_known_destroyed_object_ids, m_empire_latest_known_objects, m_empire_object_visibility, m_empire_stale_knowledge_object_ids, m_objects, and VIS_NO_VISIBILITY().
Referenced by ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), and ServerApp::ProcessCombats().
UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap()
void Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap (const EmpireManager & empires)
References m_objects, and m_pathfinder.
Referenced by AIClientApp::HandleMessage(), and MapWnd::MidTurnUpdate().
UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps()
void Universe::UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps (const EmpireManager & empires)
Regenerates per-empire system view graphs by filtering the complete system graph based on empire visibility.
Does not regenerate the base graph to account for actual system-starlane connectivity changes.
References m_empire_latest_known_objects, and m_pathfinder.
Referenced by ServerApp::LoadGameInit(), ServerApp::PostCombatProcessTurns(), and ServerApp::PreCombatProcessTurns().
UpdateMeterEstimates() [1/4]
void Universe::UpdateMeterEstimates (const std::vector< int > & objects_vec, ScriptingContext & context)
Based on (known subset of, if in a client) universe and any orders given so far this turn, updates estimated meter maxes for next turn for the objects with ids indicated in objects_vec.
References OptionsDB::Get(), GetOptionsDB(), m_destroyed_object_ids, m_effect_accounting_map, and UpdateMeterEstimatesImpl().
Referenced by AutomaticallyChosenColonyShip(), ServerApp::GenerateUniverse(), InitMeterEstimatesAndDiscrepancies(), MapWnd::InitTurn(), ServerApp::PostCombatProcessTurns(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), MapWnd::SelectSystem(), GovernmentWnd::MainPanel::SetPolicy(), anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates(), UpdateMeterEstimates(), anonymous_namespace{UniverseWrapper.cpp}::UpdateMetersWrapper(), and MapWnd::UpdateSidePanelSystemObjectMetersAndResourcePools().
UpdateMeterEstimates() [2/4]
void Universe::UpdateMeterEstimates (int object_id, ScriptingContext & context, bool update_contained_objects = false)
Updates indicated object's meters, and if applicable, the meters of objects contained within the indicated object.
If object_id is INVALID_OBJECT_ID, then all objects' meters are updated.
References ErrorLogger, GetOptionsDB(), INVALID_OBJECT_ID, m_effect_accounting_map, m_objects, UpdateMeterEstimates(), and UpdateMeterEstimatesImpl().
UpdateMeterEstimates() [3/4]
void Universe::UpdateMeterEstimates (ScriptingContext & context)
Updates all meters for all (known) objects.
References GetOptionsDB(), and UpdateMeterEstimates().
UpdateMeterEstimates() [4/4]
void Universe::UpdateMeterEstimates (ScriptingContext & context, bool do_accounting)
References m_effect_accounting_map, m_objects, and UpdateMeterEstimatesImpl().
UpdateMeterEstimatesImpl()
void Universe::UpdateMeterEstimatesImpl (const std::vector< int > & objects_vec, ScriptingContext & context, bool do_accounting) private
Does actual updating of meter estimates after the public function have processed objects_vec or whatever they were passed and cleared the relevant effect accounting for those objects and meters.
If an empty vector is passed, it will instead update all existing objects.
References Meter::AddToCurrent(), ScriptingContext::ContextObjects(), ScriptingContext::ContextUniverse(), Meter::Current(), Meter::DEFAULT_VALUE, Meter::Dump(), ExecuteEffects(), ObjectMap::ExistingObjects(), GetEffectAccountingMap(), GetEffectsAndTargets(), INVALID_OBJECT_ID, m_effect_discrepancy_map, m_objects, to_string(), and TraceLogger.
Referenced by UpdateMeterEstimates().
UpdateStatRecords()
void Universe::UpdateStatRecords (EmpireManager & empires)
References CurrentTurn(), EmpireStats(), ErrorLogger, INVALID_GAME_TURN, m_objects, and m_stat_records.
Referenced by ServerApp::NewGameInitConcurrentWithJoiners(), and ServerApp::PostCombatProcessTurns().
VerifyUnusedObjectID()
bool Universe::VerifyUnusedObjectID (const int empire_id, const int id) private
Verify that an object ID id could be generated by empire_id.
References ErrorLogger, and m_object_id_allocator.
Friends And Related Function Documentation
serialize
template<typename Archive > void serialize (Archive & ar, Universe & u, unsigned int const version) friend
Member Data Documentation
m_design_id_allocator
std::unique_ptr<IDAllocator> Universe::m_design_id_allocator private
Manages allocating and verifying new ship design ids.
Referenced by GenerateDesignID(), InsertShipDesignID(), ObfuscateIDGenerator(), operator=(), ResetAllIDAllocation(), and serialize().
m_destroyed_object_ids
std::set<int> Universe::m_destroyed_object_ids private
all ids of objects that have been destroyed (on server) or that a player knows were destroyed (on clients)
Referenced by Clear(), Destroy(), DestroyedObjectIds(), EmpireKnownDestroyedObjectIDs(), GetDestroyedObjectsToSerialize(), HighestDestroyedObjectID(), InitMeterEstimatesAndDiscrepancies(), operator=(), serialize(), and UpdateMeterEstimates().
m_effect_accounting_map
Effect::AccountingMap Universe::m_effect_accounting_map private
map from target object id, to map from target meter, to orderered list of structs with details of an effect and what it does to the meter
Referenced by Clear(), ExecuteEffects(), InitMeterEstimatesAndDiscrepancies(), operator=(), and UpdateMeterEstimates().
m_effect_discrepancy_map
DiscrepancyMap Universe::m_effect_discrepancy_map private
map from target object id, to map from target meter, to discrepancy between meter's actual initial value, and the initial value that this meter should have as far as the client can tell: the unknown factor affecting the meter.
Referenced by Clear(), InitMeterEstimatesAndDiscrepancies(), operator=(), and UpdateMeterEstimatesImpl().
m_effect_specified_empire_object_visibilities
EmpireObjectVisValueRefMap Universe::m_effect_specified_empire_object_visibilities private
Referenced by ApplyAllEffectsAndUpdateMeters(), ApplyEffectDerivedVisibilities(), Clear(), operator=(), and SetEffectDerivedVisibility().
m_empire_known_destroyed_object_ids
ObjectKnowledgeMap Universe::m_empire_known_destroyed_object_ids private
map from empire id to (set of object ids that the empire knows have been destroyed)
Referenced by Clear(), EmpireKnownDestroyedObjectIDs(), GetDestroyedObjectsToSerialize(), GetEmpireKnownDestroyedObjects(), GetObjectsToSerialize(), operator=(), serialize(), SetEmpireKnowledgeOfDestroyedObject(), and UpdateEmpireStaleObjectKnowledge().
m_empire_known_ship_design_ids
std::map<int, std::set<int> > Universe::m_empire_known_ship_design_ids private
ship designs known to each empire
Referenced by Clear(), EmpireKnownShipDesignIDs(), GetShipDesignsToSerialize(), operator=(), serialize(), SetEmpireKnowledgeOfShipDesign(), and UpdateEmpireObjectVisibilities().
m_empire_latest_known_objects
EmpireObjectMap Universe::m_empire_latest_known_objects private
map from empire id to (map from object id to latest known information about each object by that empire)
Referenced by Clear(), EmpireKnownObjects(), GetEmpireKnownObjectsToSerialize(), GetObjectsToSerialize(), operator=(), serialize(), UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), UpdateEmpireStaleObjectKnowledge(), and UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps().
m_empire_object_visibility
EmpireObjectVisibilityMap Universe::m_empire_object_visibility private
map from empire id to (map from object id to visibility of that object for that empire)
Referenced by ApplyEffectDerivedVisibilities(), Clear(), GetEmpireObjectVisibility(), GetEmpireObjectVisibilityMap(), GetObjectVisibilityByEmpire(), operator=(), serialize(), SetEmpireObjectVisibility(), UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), UpdateEmpireObjectVisibilities(), and UpdateEmpireStaleObjectKnowledge().
m_empire_object_visibility_turns
EmpireObjectVisibilityTurnMap Universe::m_empire_object_visibility_turns private
map from empire id to (map from object id to (map from Visibility rating to turn number on which the empire last saw the object at the indicated Visibility rating or higher)
Referenced by Clear(), GetEmpireObjectVisibilityTurnMap(), GetObjectVisibilityTurnMapByEmpire(), operator=(), serialize(), and UpdateEmpireLatestKnownObjectsAndVisibilityTurns().
m_empire_object_visible_specials
EmpireObjectSpecialsMap Universe::m_empire_object_visible_specials private
map from empire id to (map from object id to (set of names of specials that empire can see are on that object))
Referenced by Clear(), GetObjectVisibleSpecialsByEmpire(), operator=(), SetEmpireSpecialVisibility(), and UpdateEmpireObjectVisibilities().
m_empire_stale_knowledge_object_ids
ObjectKnowledgeMap Universe::m_empire_stale_knowledge_object_ids private
map from empire id to (set of object ids that the empire has previously observed but has subsequently been unable to detect at its last known location despite expecting to be able to detect it based on stealth of the object and having detectors in range)
Referenced by Clear(), EmpireStaleKnowledgeObjectIDs(), GetEmpireStaleKnowledgeObjects(), operator=(), serialize(), and UpdateEmpireStaleObjectKnowledge().
m_empire_stats
EmpireStatsMap Universe::m_empire_stats mutable private
Referenced by EmpireStats(), and operator=().
m_inhibit_universe_object_signals
bool Universe::m_inhibit_universe_object_signals = false private
Referenced by InhibitUniverseObjectSignals(), operator=(), and UniverseObjectSignalsInhibited().
m_marked_destroyed
std::map<int, std::set<int> > Universe::m_marked_destroyed private
used while applying effects to cache objects that have been destroyed. this allows to-be-destroyed objects to remain undestroyed until all effects have been processed, which ensures that to-be-destroyed objects still exist when other effects need to access them as a source object. key is destroyed object, and value set are the ids of objects that caused the destruction (may be multiples destroying a single target on a given turn)
Referenced by Clear(), EffectDestroy(), ExecuteEffects(), and operator=().
m_monster_fleet_plans
std::vector<std::unique_ptr<MonsterFleetPlan> > Universe::m_monster_fleet_plans mutable private
Referenced by MonsterFleetPlans(), and operator=().
m_object_id_allocator
std::unique_ptr<IDAllocator> Universe::m_object_id_allocator private
Manages allocating and verifying new object ids.
Referenced by GenerateObjectID(), InsertIDCore(), ObfuscateIDGenerator(), operator=(), ResetAllIDAllocation(), serialize(), and VerifyUnusedObjectID().
m_objects
std::unique_ptr<ObjectMap> Universe::m_objects private
map from object id to UniverseObjects in the universe. for the server: all of them, up to date and true information about object is stored; for clients, only limited information based on what the client knows about is sent.
Referenced by ApplyEffectDerivedVisibilities(), BackPropagateObjectMeters(), Clear(), Delete(), Destroy(), EmpireKnownObjects(), EmpireVisibleObjectIDs(), ExecuteEffects(), GetEmpireObjectVisibilityMap(), GetObjectsToSerialize(), GetObjectVisibleSpecialsByEmpire(), InitMeterEstimatesAndDiscrepancies(), InsertIDCore(), operator=(), RecursiveDestroy(), ResetAllIDAllocation(), ResetAllObjectMeters(), serialize(), SetEmpireObjectVisibility(), UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), UpdateEmpireObjectVisibilities(), UpdateEmpireStaleObjectKnowledge(), UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap(), UpdateMeterEstimates(), UpdateMeterEstimatesImpl(), and UpdateStatRecords().
m_pathfinder
std::shared_ptr<Pathfinder> Universe::m_pathfinder private
Referenced by Clear(), InitializeSystemGraph(), operator=(), UpdateEmpireVisibilityFilteredSystemGraphsWithMainObjectMap(), and UpdateEmpireVisibilityFilteredSystemGraphsWithOwnObjectMaps().
m_pending_buildings
boost::optional<Pending::Pending<std::vector<UnlockableItem> > > Universe::m_pending_buildings = boost::none mutable private
Referenced by InitiallyUnlockedBuildings(), and SetInitiallyUnlockedBuildings().
m_pending_empire_stats
boost::optional<Pending::Pending<EmpireStatsMap> > Universe::m_pending_empire_stats = boost::none mutable private
Referenced by EmpireStats(), and SetEmpireStats().
m_pending_fleet_plans
boost::optional<Pending::Pending<std::vector<std::unique_ptr<FleetPlan> > > > Universe::m_pending_fleet_plans = boost::none mutable private
Referenced by InitiallyUnlockedFleetPlans(), and SetInitiallyUnlockedFleetPlans().
m_pending_items
boost::optional<Pending::Pending<std::vector<UnlockableItem> > > Universe::m_pending_items = boost::none mutable private
Referenced by InitiallyUnlockedItems(), and SetInitiallyUnlockedItems().
m_pending_monster_fleet_plans
boost::optional<Pending::Pending<std::vector<std::unique_ptr<MonsterFleetPlan> > > > Universe::m_pending_monster_fleet_plans = boost::none mutable private
Referenced by MonsterFleetPlans(), and SetMonsterFleetPlans().
m_ship_designs
ShipDesignMap Universe::m_ship_designs private
ship designs in the universe
Referenced by Clear(), DeleteShipDesign(), GetGenericShipDesign(), GetShipDesign(), GetShipDesignsToSerialize(), InsertShipDesign(), InsertShipDesignID(), operator=(), RenameShipDesign(), ResetAllIDAllocation(), and serialize().
m_stat_records
std::map<std::string, std::map<int, std::map<int, double> > > Universe::m_stat_records private
storage for statistics calculated for empires. Indexed by stat name (string), contains a map indexed by empire id, contains a map from turn number (int) to stat value (double).
Referenced by Clear(), operator=(), serialize(), and UpdateStatRecords().
m_universe_width
double Universe::m_universe_width = 1000.0 private
Referenced by Clear(), operator=(), serialize(), and UniverseWidth().
m_unlocked_buildings
std::vector<UnlockableItem> Universe::m_unlocked_buildings mutable private
Referenced by InitiallyUnlockedBuildings(), and operator=().
m_unlocked_fleet_plans
std::vector<std::unique_ptr<FleetPlan> > Universe::m_unlocked_fleet_plans mutable private
Referenced by InitiallyUnlockedFleetPlans(), and operator=().
m_unlocked_items
std::vector<UnlockableItem> Universe::m_unlocked_items mutable private
Referenced by InitiallyUnlockedItems(), and operator=().
UniverseObjectDeleteSignal
UniverseObjectDeleteSignalType Universe::UniverseObjectDeleteSignal mutable
the state changed signal object for this UniverseObject
Referenced by MapWnd::CompleteConstruction(), FleetWnd::CompleteConstruction(), ObjectListBox::CompleteConstruction(), Destroy(), and FleetDetailPanel::FleetDetailPanel().
The documentation for this class was generated from the following files:
Universe.h
Universe.cpp