FreeOrion: GovernmentWnd::PolicyPalette Class Reference
GovernmentWnd::PolicyPalette Class Reference
Contains graphical list of PolicyControl which can be dragged and dropped onto slots to assign policies to those slots.
Public Member Functions
Structors
PolicyPalette (GG::X w, GG::Y h)
void CompleteConstruction () override
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void ShowCategory (const std::string &category, bool refresh_list=true)
void ShowAllCategories (bool refresh_list=true)
void HideCategory (const std::string &category, bool refresh_list=true)
void HideAllCategories (bool refresh_list=true)
void ToggleCategory (const std::string &category, bool refresh_list=true)
void ToggleAllCategories (bool refresh_list=true)
void ToggleAvailability (const Availability::Enum type)
void Populate ()
Public Attributes
boost::signals2::signal< void(const std::string &)> ClearPolicySignal
boost::signals2::signal< void(const Policy *, GG::Flags< GG::ModKey >)> PolicyClickedSignal
boost::signals2::signal< void(const Policy *)> PolicyDoubleClickedSignal
boost::signals2::signal< void(const Policy *, const GG::Pt &pt)> PolicyRightClickedSignal
Private Member Functions
void DoLayout ()
void HandlePolicyClicked (const Policy *, GG::Flags< GG::ModKey >)
A policy type click with ctrl obsoletes policy.
void HandlePolicyRightClicked (const Policy *, const GG::Pt &pt)
Private Attributes
std::tuple< std::shared_ptr< CUIStateButton >, std::shared_ptr< CUIStateButton >, std::shared_ptr< CUIStateButton > > m_availabilities_buttons {nullptr, nullptr, nullptr}
AvailabilityManager m_availabilities_state {false, true, false}
std::map< std::string, std::shared_ptr< CUIStateButton > > m_category_buttons
std::shared_ptr< PoliciesListBox > m_policies_list = nullptr
Detailed Description
Contains graphical list of PolicyControl which can be dragged and dropped onto slots to assign policies to those slots.
Constructor & Destructor Documentation
PolicyPalette()
GovernmentWnd::PolicyPalette::PolicyPalette (GG::X w, GG::Y h)
Member Function Documentation
CompleteConstruction()
void GovernmentWnd::PolicyPalette::CompleteConstruction () override
References Availability::Available, ClearPolicySignal, DoLayout(), Availability::Future, GetPolicyManager(), HandlePolicyClicked(), HandlePolicyRightClicked(), m_availabilities_buttons, m_availabilities_state, m_category_buttons, m_policies_list, PolicyDoubleClickedSignal, Populate(), ShowAllCategories(), ToggleAvailability(), ToggleCategory(), and UserString().
DoLayout()
void GovernmentWnd::PolicyPalette::DoLayout () private
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_availabilities_buttons, m_category_buttons, m_policies_list, and ClientUI::Pts().
Referenced by CompleteConstruction(), and SizeMove().
HandlePolicyClicked()
void GovernmentWnd::PolicyPalette::HandlePolicyClicked (const Policy * policy_type, GG::Flags< GG::ModKey > modkeys) private
A policy type click with ctrl obsoletes policy.
References PolicyClickedSignal.
Referenced by CompleteConstruction().
HandlePolicyRightClicked()
void GovernmentWnd::PolicyPalette::HandlePolicyRightClicked (const Policy * policy_type, const GG::Pt & pt) private
References PolicyRightClickedSignal.
Referenced by CompleteConstruction().
HideAllCategories()
void GovernmentWnd::PolicyPalette::HideAllCategories (bool refresh_list = true)
References m_category_buttons, and m_policies_list.
Referenced by ToggleAllCategories().
HideCategory()
void GovernmentWnd::PolicyPalette::HideCategory (const std::string & category, bool refresh_list = true)
References ErrorLogger, m_category_buttons, and m_policies_list.
Referenced by ToggleCategory().
Populate()
void GovernmentWnd::PolicyPalette::Populate ()
References m_policies_list.
Referenced by CompleteConstruction(), and ToggleAvailability().
ShowAllCategories()
void GovernmentWnd::PolicyPalette::ShowAllCategories (bool refresh_list = true)
References m_category_buttons, and m_policies_list.
Referenced by CompleteConstruction(), and ToggleAllCategories().
ShowCategory()
void GovernmentWnd::PolicyPalette::ShowCategory (const std::string & category, bool refresh_list = true)
References ErrorLogger, m_category_buttons, and m_policies_list.
Referenced by ToggleCategory().
SizeMove()
void GovernmentWnd::PolicyPalette::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
ToggleAllCategories()
void GovernmentWnd::PolicyPalette::ToggleAllCategories (bool refresh_list = true)
References HideAllCategories(), m_category_buttons, m_policies_list, and ShowAllCategories().
ToggleAvailability()
void GovernmentWnd::PolicyPalette::ToggleAvailability (const Availability::Enum type)
References Availability::Available, Availability::Future, m_availabilities_buttons, m_availabilities_state, Availability::Obsolete, and Populate().
Referenced by CompleteConstruction().
ToggleCategory()
void GovernmentWnd::PolicyPalette::ToggleCategory (const std::string & category, bool refresh_list = true)
References ErrorLogger, HideCategory(), m_category_buttons, m_policies_list, and ShowCategory().
Referenced by CompleteConstruction().
Member Data Documentation
ClearPolicySignal
boost::signals2::signal<void (const std::string&)> GovernmentWnd::PolicyPalette::ClearPolicySignal mutable
Referenced by CompleteConstruction().
m_availabilities_buttons
std::tuple<std::shared_ptr<CUIStateButton>, std::shared_ptr<CUIStateButton>, std::shared_ptr<CUIStateButton> > GovernmentWnd::PolicyPalette::m_availabilities_buttons {nullptr, nullptr, nullptr} private
Referenced by CompleteConstruction(), DoLayout(), and ToggleAvailability().
m_availabilities_state
AvailabilityManager GovernmentWnd::PolicyPalette::m_availabilities_state {false, true, false} private
Referenced by CompleteConstruction(), and ToggleAvailability().
m_category_buttons
std::map<std::string, std::shared_ptr<CUIStateButton> > GovernmentWnd::PolicyPalette::m_category_buttons private
Referenced by CompleteConstruction(), DoLayout(), HideAllCategories(), HideCategory(), ShowAllCategories(), ShowCategory(), ToggleAllCategories(), and ToggleCategory().
m_policies_list
std::shared_ptr<PoliciesListBox> GovernmentWnd::PolicyPalette::m_policies_list = nullptr private
Referenced by CompleteConstruction(), DoLayout(), HideAllCategories(), HideCategory(), Populate(), ShowAllCategories(), ShowCategory(), ToggleAllCategories(), and ToggleCategory().
PolicyClickedSignal
boost::signals2::signal<void (const Policy*, GG::Flags<GG::ModKey>)> GovernmentWnd::PolicyPalette::PolicyClickedSignal mutable
Referenced by HandlePolicyClicked().
PolicyDoubleClickedSignal
boost::signals2::signal<void (const Policy*)> GovernmentWnd::PolicyPalette::PolicyDoubleClickedSignal mutable
Referenced by CompleteConstruction().
PolicyRightClickedSignal
boost::signals2::signal<void (const Policy*, const GG::Pt& pt)> GovernmentWnd::PolicyPalette::PolicyRightClickedSignal mutable
Referenced by HandlePolicyRightClicked().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp