FreeOrion: anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd Class Reference
anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd Class Reference
Public Member Functions
SystemMeterBrowseWnd (MeterType meter_type, int system_id)
void Render () override
void UpdateImpl (std::size_t mode, const GG::Wnd *target) override
bool WndHasBrowseInfo (const GG::Wnd *wnd, std::size_t mode) const override
Private Attributes
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_labels_and_amounts
MeterType m_meter_type
int m_system_id
Constructor & Destructor Documentation
SystemMeterBrowseWnd()
anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::SystemMeterBrowseWnd (MeterType meter_type, int system_id) inline
Member Function Documentation
Render()
void anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::Render () inline override
References OpaqueColor(), anonymous_namespace{SidePanel.cpp}::RowHeight(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
UpdateImpl()
void anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl (std::size_t mode, const GG::Wnd * target) inline override
References DoubleToString(), ObjectMap::FindObjects(), ClientUI::GetBoldFont(), GetSystem(), anonymous_namespace{SidePanel.cpp}::LabelWidth(), METER_SUPPLY, UniverseObject::Name(), Objects(), anonymous_namespace{SidePanel.cpp}::RowHeight(), UserString(), and anonymous_namespace{SidePanel.cpp}::ValueWidth().
WndHasBrowseInfo()
bool anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::WndHasBrowseInfo (const GG::Wnd * wnd, std::size_t mode) const inline override
Member Data Documentation
m_labels_and_amounts
std::vector<std::pair<std::shared_ptr<GG::Label>, std::shared_ptr<GG::Label> > > anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::m_labels_and_amounts private
m_meter_type
MeterType anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::m_meter_type private
m_system_id
int anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::m_system_id private
The documentation for this class was generated from the following file:
SidePanel.cpp