FreeOrion: IconTextBrowseWnd Class Reference
IconTextBrowseWnd Class Reference
A popup tooltop for display when mousing over in-game icons.
#include <IconTextBrowseWnd.h>
Public Member Functions
IconTextBrowseWnd (const std::shared_ptr< GG::Texture > texture, const std::string &title_text, const std::string &main_text)
void PreRender () override
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_icon
const std::string m_main_text
std::shared_ptr< GG::Label > m_main_text_label
const std::shared_ptr< GG::Texture > m_texture
const std::string m_title_text
std::shared_ptr< GG::Label > m_title_text_label
Detailed Description
A popup tooltop for display when mousing over in-game icons.
Has an icon and title and some detail text.
Constructor & Destructor Documentation
IconTextBrowseWnd()
IconTextBrowseWnd::IconTextBrowseWnd (const std::shared_ptr< GG::Texture > texture, const std::string & title_text, const std::string & main_text)
Member Function Documentation
PreRender()
void IconTextBrowseWnd::PreRender () override
References anonymous_namespace{IconTextBrowseWnd.cpp}::EDGE_PAD(), ClientUI::GetBoldFont(), anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT(), anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_ICON_WIDTH(), anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_TEXT_WIDTH(), anonymous_namespace{IconTextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), m_icon, m_main_text, m_main_text_label, m_texture, m_title_text, and m_title_text_label.
Render()
void IconTextBrowseWnd::Render () override
References anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_ICON_WIDTH(), anonymous_namespace{IconTextBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
WndHasBrowseInfo()
bool IconTextBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
m_icon
std::shared_ptr<GG::StaticGraphic> IconTextBrowseWnd::m_icon private
Referenced by PreRender().
m_main_text
const std::string IconTextBrowseWnd::m_main_text private
Referenced by PreRender().
m_main_text_label
std::shared_ptr<GG::Label> IconTextBrowseWnd::m_main_text_label private
Referenced by PreRender().
m_texture
const std::shared_ptr<GG::Texture> IconTextBrowseWnd::m_texture private
Referenced by PreRender().
m_title_text
const std::string IconTextBrowseWnd::m_title_text private
Referenced by PreRender().
m_title_text_label
std::shared_ptr<GG::Label> IconTextBrowseWnd::m_title_text_label private
Referenced by PreRender().
The documentation for this class was generated from the following files:
IconTextBrowseWnd.h
IconTextBrowseWnd.cpp