FreeOrion: PredefinedShipDesignManager Class Reference
PredefinedShipDesignManager Class Reference
#include <ShipDesign.h>
Public Types
using ParsedShipDesignsType = std::pair< std::vector< std::pair< std::unique_ptr< ParsedShipDesign >, boost::filesystem::path > >, std::vector< boost::uuids::uuid > >
Public Member Functions
void AddShipDesignsToUniverse () const
Adds designs in this manager to the universe with the design creator left as no empire.
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
int GetDesignID (const std::string &name) const
Returns the ID for the design in the Universe for the predefined design with the specified name.
std::vector< const ShipDesign * > GetOrderedMonsterDesigns () const
Return pointers the ShipDesigns in order.
std::vector< const ShipDesign * > GetOrderedShipDesigns () const
Return pointers the ShipDesigns in order.
FO_COMMON_API void SetMonsterDesignTypes (Pending::Pending< ParsedShipDesignsType > &&pending_designs)
Sets monster design types to the future value of pending_design_types found in subdir.
FO_COMMON_API void SetShipDesignTypes (Pending::Pending< ParsedShipDesignsType > &&pending_designs)
Sets ship design types to the future value of pending_designs found in subdir.
Static Public Member Functions
static PredefinedShipDesignManager & GetPredefinedShipDesignManager ()
Returns the predefined ShipDesign with the name name.
Private Member Functions
PredefinedShipDesignManager ()
void CheckPendingDesignsTypes () const
Assigns any m_pending_designs.
Private Attributes
std::unordered_map< std::string, int > m_design_generic_ids
std::unordered_map< boost::uuids::uuid, std::unique_ptr< ShipDesign >, boost::hash< boost::uuids::uuid > > m_designs
std::vector< boost::uuids::uuid > m_monster_ordering
std::unordered_map< std::string, boost::uuids::uuid > m_name_to_monster_design
std::unordered_map< std::string, boost::uuids::uuid > m_name_to_ship_design
boost::optional< Pending::Pending< ParsedShipDesignsType > > m_pending_designs = boost::none
Future ship design type being parsed by parser.
boost::optional< Pending::Pending< ParsedShipDesignsType > > m_pending_monsters = boost::none
std::vector< boost::uuids::uuid > m_ship_ordering
Static Private Attributes
static PredefinedShipDesignManager * s_instance = nullptr
Member Typedef Documentation
ParsedShipDesignsType
using PredefinedShipDesignManager::ParsedShipDesignsType = std::pair< std::vector<std::pair<std::unique_ptr<ParsedShipDesign>, boost::filesystem::path> >, std::vector<boost::uuids::uuid> >
Constructor & Destructor Documentation
PredefinedShipDesignManager()
PredefinedShipDesignManager::PredefinedShipDesignManager () private
Member Function Documentation
AddShipDesignsToUniverse()
void PredefinedShipDesignManager::AddShipDesignsToUniverse () const
Adds designs in this manager to the universe with the design creator left as no empire.
References anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse().
Referenced by ServerApp::GenerateUniverse().
CheckPendingDesignsTypes()
void PredefinedShipDesignManager::CheckPendingDesignsTypes () const private
Assigns any m_pending_designs.
References anonymous_namespace{ShipDesign.cpp}::CheckPendingAndFillDesignsOrderingAndNameTables().
GetCheckSum()
unsigned int PredefinedShipDesignManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), and DebugLogger.
Referenced by CheckSumContent().
GetDesignID()
int PredefinedShipDesignManager::GetDesignID (const std::string & name) const
Returns the ID for the design in the Universe for the predefined design with the specified name.
If there is generic design available for the specified name, then INVALID_DESIGN_ID is returned.
References INVALID_DESIGN_ID.
GetOrderedMonsterDesigns()
std::vector< const ShipDesign * > PredefinedShipDesignManager::GetOrderedMonsterDesigns () const
Return pointers the ShipDesigns in order.
GetOrderedShipDesigns()
std::vector< const ShipDesign * > PredefinedShipDesignManager::GetOrderedShipDesigns () const
Return pointers the ShipDesigns in order.
Referenced by MessageWndEdit::FindGameWords().
GetPredefinedShipDesignManager()
PredefinedShipDesignManager & PredefinedShipDesignManager::GetPredefinedShipDesignManager () static
Returns the predefined ShipDesign with the name name.
If no such ship design exists, 0 is returned instead.
Referenced by GetPredefinedShipDesignManager().
SetMonsterDesignTypes()
void PredefinedShipDesignManager::SetMonsterDesignTypes (Pending::Pending< ParsedShipDesignsType > && pending_designs)
Sets monster design types to the future value of pending_design_types found in subdir.
Referenced by IApp::StartBackgroundParsing().
SetShipDesignTypes()
void PredefinedShipDesignManager::SetShipDesignTypes (Pending::Pending< ParsedShipDesignsType > && pending_designs)
Sets ship design types to the future value of pending_designs found in subdir.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_design_generic_ids
std::unordered_map<std::string, int> PredefinedShipDesignManager::m_design_generic_ids mutable private
m_designs
std::unordered_map<boost::uuids::uuid, std::unique_ptr<ShipDesign>, boost::hash<boost::uuids::uuid> > PredefinedShipDesignManager::m_designs mutable private
m_monster_ordering
std::vector<boost::uuids::uuid> PredefinedShipDesignManager::m_monster_ordering mutable private
m_name_to_monster_design
std::unordered_map<std::string, boost::uuids::uuid> PredefinedShipDesignManager::m_name_to_monster_design mutable private
m_name_to_ship_design
std::unordered_map<std::string, boost::uuids::uuid> PredefinedShipDesignManager::m_name_to_ship_design mutable private
m_pending_designs
boost::optional<Pending::Pending<ParsedShipDesignsType> > PredefinedShipDesignManager::m_pending_designs = boost::none mutable private
Future ship design type being parsed by parser.
mutable so that it can be assigned to m_ship design_types when completed.
m_pending_monsters
boost::optional<Pending::Pending<ParsedShipDesignsType> > PredefinedShipDesignManager::m_pending_monsters = boost::none mutable private
m_ship_ordering
std::vector<boost::uuids::uuid> PredefinedShipDesignManager::m_ship_ordering mutable private
s_instance
PredefinedShipDesignManager * PredefinedShipDesignManager::s_instance = nullptr static private
Referenced by operator==().
The documentation for this class was generated from the following files:
ShipDesign.h
ShipDesign.cpp