FreeOrion: Effect::SetSpecies Class Reference
Effect::SetSpecies Class Reference final
Sets the species on the target to species_name.
#include <Effects.h>
Public Member Functions
SetSpecies (std::unique_ptr< ValueRef::ValueRef< std::string >> &&species)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
virtual void Execute (ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< std::string > > m_species_name
Friends
class boost::serialization::access
Detailed Description
Sets the species on the target to species_name.
This works on planets and ships, but has no effect on other objects.
Constructor & Destructor Documentation
SetSpecies()
Effect::SetSpecies::SetSpecies (std::unique_ptr< ValueRef::ValueRef< std::string >> && species) explicit
Member Function Documentation
Dump()
std::string Effect::SetSpecies::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent(), and m_species_name.
Execute()
void Effect::SetSpecies::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References ScriptingContext::effect_target, GetSpecies(), m_species_name, Species::PreferredFocus(), and parse::species().
GetCheckSum()
unsigned int Effect::SetSpecies::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), m_species_name, and TraceLogger.
serialize()
template<typename Archive > void Effect::SetSpecies::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::SetSpecies::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::Effect.
References m_species_name.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_species_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Effect::SetSpecies::m_species_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp