FreeOrion: PythonParser Class Reference
PythonParser Class Reference
#include <PythonParser.h>
Public Member Functions
PythonParser (PythonCommon &_python, const boost::filesystem::path &scripting_dir)
PythonParser (const PythonParser &)=delete
PythonParser (PythonParser &&)=delete
~PythonParser ()
const PythonParser & operator= (const PythonParser &)=delete
PythonParser & operator= (PythonParser &&)=delete
bool ParseFileCommon (const boost::filesystem::path &path, const boost::python::dict &globals, std::string &filename, std::string &file_contents) const
Public Attributes
boost::python::object type_bool
boost::python::object type_float
boost::python::object type_int
boost::python::object type_str
Private Member Functions
boost::python::object create_module (const module_spec &spec)
boost::python::object exec_module (boost::python::object &module)
boost::python::object find_spec (const std::string &fullname, const boost::python::object &path, const boost::python::object &target) const
Private Attributes
boost::optional< boost::python::dict > m_current_globals
boost::python::list m_meta_path
PythonCommon & m_python
const boost::filesystem::path & m_scripting_dir
Constructor & Destructor Documentation
PythonParser() [1/3]
PythonParser::PythonParser (PythonCommon & _python, const boost::filesystem::path & scripting_dir)
~PythonParser()
PythonParser::~PythonParser ()
PythonParser() [2/3]
PythonParser::PythonParser (const PythonParser &) delete
PythonParser() [3/3]
PythonParser::PythonParser (PythonParser &&) delete
Member Function Documentation
create_module()
py::object PythonParser::create_module (const module_spec & spec) private
exec_module()
py::object PythonParser::exec_module (boost::python::object & module) private
References ErrorLogger, module_spec::fullname, and anonymous_namespace{About.cpp}::ReadFile().
find_spec()
py::object PythonParser::find_spec (const std::string & fullname, const boost::python::object & path, const boost::python::object & target) const private
References module_spec::module_spec(), and module_spec::parent.
operator=() [1/2]
const PythonParser& PythonParser::operator= (const PythonParser &) delete
operator=() [2/2]
PythonParser& PythonParser::operator= (PythonParser &&) delete
ParseFileCommon()
bool PythonParser::ParseFileCommon (const boost::filesystem::path & path, const boost::python::dict & globals, std::string & filename, std::string & file_contents) const
References ErrorLogger, and anonymous_namespace{About.cpp}::ReadFile().
Referenced by py_parse::detail::parse_file().
Member Data Documentation
m_current_globals
boost::optional<boost::python::dict> PythonParser::m_current_globals mutable private
m_meta_path
boost::python::list PythonParser::m_meta_path private
m_python
PythonCommon& PythonParser::m_python private
m_scripting_dir
const boost::filesystem::path& PythonParser::m_scripting_dir private
type_bool
boost::python::object PythonParser::type_bool
type_float
boost::python::object PythonParser::type_float
Referenced by anonymous_namespace{TechsParser.cpp}::insert_game_rule_(), and anonymous_namespace{TechsParser.cpp}::insert_minmaxoneof_().
type_int
boost::python::object PythonParser::type_int
Referenced by anonymous_namespace{TechsParser.cpp}::insert_game_rule_(), and anonymous_namespace{TechsParser.cpp}::insert_minmaxoneof_().
type_str
boost::python::object PythonParser::type_str
The documentation for this class was generated from the following files:
PythonParser.h
DummyParsers.cpp
PythonParser.cpp