FreeOrion: ShaderProgram Class Reference
ShaderProgram Class Reference
#include <ShaderProgram.h>
Public Member Functions
ShaderProgram (const std::string &vertex_shader, const std::string &fragment_shader)
~ShaderProgram ()
bool AllValuesBound ()
void Bind (const std::string &name, float f)
void Bind (const std::string &name, float f0, float f1)
void Bind (const std::string &name, float f0, float f1, float f2)
void Bind (const std::string &name, float f0, float f1, float f2, float f3)
void Bind (const std::string &name, std::size_t element_size, const std::vector< float > &floats)
void Bind (const std::string &name, GLuint texture_id)
void BindInt (const std::string &name, int i)
void BindInts (const std::string &name, int i0, int i1)
void BindInts (const std::string &name, int i0, int i1, int i2)
void BindInts (const std::string &name, int i0, int i1, int i2, int i3)
void BindInts (const std::string &name, std::size_t element_size, const std::vector< GLint > &ints)
const std::string & FragmentShaderInfoLog () const
bool LinkSucceeded () const
GLuint ProgramID () const
const std::string & ProgramInfoLog () const
const std::string & ProgramValidityInfoLog () const
void stopUse ()
void Use ()
const std::string & VertexShaderInfoLog () const
Static Public Member Functions
static std::unique_ptr< ShaderProgram > shaderProgramFactory (const std::string &vertex_shader, const std::string &fragment_shader)
Private Member Functions
ShaderProgram ()
Private Attributes
GLuint m_fragment_shader_id
std::string m_fragment_shader_log
bool m_link_succeeded
GLuint m_program_id
std::string m_program_log
std::string m_program_validity_log
GLuint m_vertex_shader_id
std::string m_vertex_shader_log
Constructor & Destructor Documentation
ShaderProgram() [1/2]
ShaderProgram::ShaderProgram () private
ShaderProgram() [2/2]
ShaderProgram::ShaderProgram (const std::string & vertex_shader, const std::string & fragment_shader)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), anonymous_namespace{ShaderProgram.cpp}::GetProgramLog(), anonymous_namespace{ShaderProgram.cpp}::GetShaderLog(), m_fragment_shader_id, m_fragment_shader_log, m_link_succeeded, m_program_id, m_program_log, m_vertex_shader_id, and m_vertex_shader_log.
~ShaderProgram()
ShaderProgram::~ShaderProgram ()
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), m_fragment_shader_id, m_program_id, and m_vertex_shader_id.
Member Function Documentation
AllValuesBound()
bool ShaderProgram::AllValuesBound ()
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), anonymous_namespace{ShaderProgram.cpp}::GetProgramLog(), m_program_id, and m_program_validity_log.
Bind() [1/6]
void ShaderProgram::Bind (const std::string & name, float f)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
Bind() [2/6]
void ShaderProgram::Bind (const std::string & name, float f0, float f1)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
Bind() [3/6]
void ShaderProgram::Bind (const std::string & name, float f0, float f1, float f2)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
Bind() [4/6]
void ShaderProgram::Bind (const std::string & name, float f0, float f1, float f2, float f3)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
Bind() [5/6]
void ShaderProgram::Bind (const std::string & name, std::size_t element_size, const std::vector< float > & floats)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
Bind() [6/6]
void ShaderProgram::Bind (const std::string & name, GLuint texture_id)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
BindInt()
void ShaderProgram::BindInt (const std::string & name, int i)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
BindInts() [1/4]
void ShaderProgram::BindInts (const std::string & name, int i0, int i1)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
BindInts() [2/4]
void ShaderProgram::BindInts (const std::string & name, int i0, int i1, int i2)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
BindInts() [3/4]
void ShaderProgram::BindInts (const std::string & name, int i0, int i1, int i2, int i3)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
BindInts() [4/4]
void ShaderProgram::BindInts (const std::string & name, std::size_t element_size, const std::vector< GLint > & ints)
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
FragmentShaderInfoLog()
const std::string & ShaderProgram::FragmentShaderInfoLog () const
References m_fragment_shader_log.
LinkSucceeded()
bool ShaderProgram::LinkSucceeded () const
References m_link_succeeded.
ProgramID()
GLuint ShaderProgram::ProgramID () const
References m_program_id.
ProgramInfoLog()
const std::string & ShaderProgram::ProgramInfoLog () const
References m_program_log.
ProgramValidityInfoLog()
const std::string & ShaderProgram::ProgramValidityInfoLog () const
References m_program_validity_log.
shaderProgramFactory()
std::unique_ptr< ShaderProgram > ShaderProgram::shaderProgramFactory (const std::string & vertex_shader, const std::string & fragment_shader) static
References HumanClientApp::GetApp().
Referenced by ScanlineRenderer::Impl::StartUsing().
stopUse()
void ShaderProgram::stopUse ()
Use()
void ShaderProgram::Use ()
References anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR(), and m_program_id.
VertexShaderInfoLog()
const std::string & ShaderProgram::VertexShaderInfoLog () const
References m_vertex_shader_log.
Member Data Documentation
m_fragment_shader_id
GLuint ShaderProgram::m_fragment_shader_id private
Referenced by ShaderProgram(), and ~ShaderProgram().
m_fragment_shader_log
std::string ShaderProgram::m_fragment_shader_log private
Referenced by FragmentShaderInfoLog(), and ShaderProgram().
m_link_succeeded
bool ShaderProgram::m_link_succeeded private
Referenced by LinkSucceeded(), and ShaderProgram().
m_program_id
GLuint ShaderProgram::m_program_id private
Referenced by AllValuesBound(), Bind(), BindInt(), BindInts(), ProgramID(), ShaderProgram(), Use(), and ~ShaderProgram().
m_program_log
std::string ShaderProgram::m_program_log private
Referenced by ProgramInfoLog(), and ShaderProgram().
m_program_validity_log
std::string ShaderProgram::m_program_validity_log private
Referenced by AllValuesBound(), and ProgramValidityInfoLog().
m_vertex_shader_id
GLuint ShaderProgram::m_vertex_shader_id private
Referenced by ShaderProgram(), and ~ShaderProgram().
m_vertex_shader_log
std::string ShaderProgram::m_vertex_shader_log private
Referenced by ShaderProgram(), and VertexShaderInfoLog().
The documentation for this class was generated from the following files:
ShaderProgram.h
ShaderProgram.cpp