FreeOrion: TechTreeArcs Class Reference
TechTreeArcs Class Reference
#include <TechTreeArcs.h>
Classes
class Impl
Public Member Functions
TechTreeArcs ()
TechTreeArcs (TechTreeArcs &other)=delete
TechTreeArcs (const TechTreeLayout &layout, const std::set< std::string > &techs_to_show)
~TechTreeArcs ()
TechTreeArcs & operator= (TechTreeArcs &other)=delete
void Render (double scale)
void Reset ()
Clears the arcs.
void Reset (const TechTreeLayout &layout, const std::set< std::string > &techs_to_show)
Recalculates the arcs.
Private Attributes
std::unique_ptr< Impl > m_impl
Detailed Description
This class is responsible for drawing the lines of a TechTreeLayout on screen.
Constructor & Destructor Documentation
TechTreeArcs::TechTreeArcs () default
Referenced by TechTreeArcs::Impl::FillArcBuffer().
TechTreeArcs::TechTreeArcs (TechTreeArcs & other) delete
TechTreeArcs::TechTreeArcs (const TechTreeLayout & layout, const std::set< std::string > & techs_to_show)
References ~TechTreeArcs().
TechTreeArcs::~TechTreeArcs () default
Referenced by TechTreeArcs().
Member Function Documentation
TechTreeArcs& TechTreeArcs::operator= (TechTreeArcs & other) delete
void TechTreeArcs::Render (double scale)
References m_impl.
Referenced by TechTreeWnd::LayoutPanel::Render().
void TechTreeArcs::Reset ()
Clears the arcs.
References m_impl.
Referenced by TechTreeWnd::LayoutPanel::Clear(), and TechTreeWnd::LayoutPanel::Layout().
void TechTreeArcs::Reset (const TechTreeLayout & layout, const std::set< std::string > & techs_to_show)
Recalculates the arcs.
References m_impl.
Member Data Documentation
std::unique_ptr<Impl> TechTreeArcs::m_impl private
Referenced by Render(), and Reset().
The documentation for this class was generated from the following files:
TechTreeArcs.h
TechTreeArcs.cpp