FreeOrion: CUITabRepresenter Class Reference
CUITabRepresenter Class Reference
A FreeOrion styled TabBar tab.
#include <CUIControls.h>
Public Member Functions
GG::Pt MinUsableSize (const GG::StateButton &button) const override
void OnChanged (const GG::StateButton &button, GG::StateButton::ButtonState prev_state) const override
void OnChecked (bool checked) const override
void Render (const GG::StateButton &button) const override
Detailed Description
A FreeOrion styled TabBar tab.
Member Function Documentation
MinUsableSize()
GG::Pt CUITabRepresenter::MinUsableSize (const GG::StateButton & button) const override
OnChanged()
void CUITabRepresenter::OnChanged (const GG::StateButton & button, GG::StateButton::ButtonState prev_state) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
OnChecked()
void CUITabRepresenter::OnChecked (bool checked) const override
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Render()
void CUITabRepresenter::Render (const GG::StateButton & button) const override
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::CtrlBorderColor(), and anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET.
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp