FreeOrion: TechManager Class Reference
TechManager Class Reference
holds all FreeOrion techs.
#include <Tech.h>
Classes
struct CategoryIndex
struct NameIndex
Public Types
typedef TechContainer::index< CategoryIndex >::type::const_iterator category_iterator
iterator that runs over techs within a category
typedef TechContainer::index< NameIndex >::type::const_iterator iterator
iterator that runs over all techs
using TechCategoryMap = std::map< std::string, std::unique_ptr< TechCategory > >
typedef boost::multi_index_container< std::unique_ptr< Tech >, boost::multi_index::indexed_by< boost::multi_index::ordered_non_unique< boost::multi_index::tag< CategoryIndex >, boost::multi_index::const_mem_fun< Tech, const std::string &, &Tech::Category > >, boost::multi_index::ordered_unique< boost::multi_index::tag< NameIndex >, boost::multi_index::const_mem_fun< Tech, const std::string &, &Tech::Name > > > > TechContainer
using TechParseTuple = std::tuple< TechManager::TechContainer, std::map< std::string, std::unique_ptr< TechCategory > >, std::set< std::string > >
Public Member Functions
std::vector< const Tech * > AllNextTechs (const std::set< std::string > &known_techs)
returns all researchable techs
iterator begin () const
iterator to the first tech
category_iterator category_begin (const std::string &name) const
iterator to the first tech in category name
category_iterator category_end (const std::string &name) const
iterator to the last + 1th tech in category name
std::vector< std::string > CategoryNames () const
returns the list of category names
const Tech * CheapestNextTech (const std::set< std::string > &known_techs, int empire_id)
returns the cheapest researchable tech
const Tech * CheapestNextTechTowards (const std::set< std::string > &known_techs, const std::string &desired_tech, int empire_id)
returns the cheapest researchable tech that progresses from the given known techs to the given desired tech
iterator end () const
iterator to the last + 1th tech
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
const Tech * GetTech (const std::string &name) const
returns the tech with the name name; you should use the free function GetTech() instead
const TechCategory * GetTechCategory (const std::string &name) const
returns the tech category with the name name; you should use the free function GetTechCategory() instead
std::vector< const Tech * > NextTechsTowards (const std::set< std::string > &known_techs, const std::string &desired_tech, int empire_id)
returns all researchable techs that progress from the given known techs to the given desired tech
std::vector< std::string > RecursivePrereqs (const std::string &tech_name, int empire_id, bool min_required=true) const
Returns names of indicated tech's prerequisites, and all prereqs of those techs, etc.
FO_COMMON_API void SetTechs (Pending::Pending< TechParseTuple > &&future)
Sets types to the value of future.
size_t size () const
std::vector< std::string > TechNames () const
returns list of all tech names
std::vector< std::string > TechNames (const std::string &name) const
returns list of names of techs in specified category
Static Public Member Functions
static TechManager & GetTechManager ()
returns the instance of this singleton class; you should use the free function GetTechManager() instead
Private Member Functions
TechManager ()
void AllChildren (const Tech *tech, std::map< std::string, std::string > &children) const
void CheckPendingTechs () const
Assigns any m_pending_types to m_techs.
std::string FindFirstDependencyCycle () const
returns an error string indicating the first prerequisite dependency cycle found in m_techs, or an empty string if there are no dependency cycles
std::string FindIllegalDependencies () const
returns an error string indicating the first instance of an illegal prerequisite relationship between two techs in m_techs, or an empty string if there are no illegal dependencies
std::string FindRedundantDependency () const
returns an error string indicating the first instance of a redundant dependency, or an empty string if there are no redundant dependencies.
Private Attributes
TechCategoryMap m_categories
boost::optional< Pending::Pending< TechParseTuple > > m_pending_types = boost::none
Future types being parsed by parser.
TechContainer m_techs
Static Private Attributes
static TechManager * s_instance = nullptr
Detailed Description
holds all FreeOrion techs.
Techs may be looked up by name and by category, and the next researchable techs can be querried, given a set of currently-known techs.
Member Typedef Documentation
category_iterator
typedef TechContainer::index<CategoryIndex>::type::const_iterator TechManager::category_iterator
iterator that runs over techs within a category
iterator
typedef TechContainer::index<NameIndex>::type::const_iterator TechManager::iterator
iterator that runs over all techs
TechCategoryMap
using TechManager::TechCategoryMap = std::map<std::string, std::unique_ptr<TechCategory> >
TechContainer
typedef boost::multi_index_container< std::unique_ptr<Tech>, boost::multi_index::indexed_by< boost::multi_index::ordered_non_unique< boost::multi_index::tag<CategoryIndex>, boost::multi_index::const_mem_fun< Tech, const std::string&, &Tech::Category > >, boost::multi_index::ordered_unique< boost::multi_index::tag<NameIndex>, boost::multi_index::const_mem_fun< Tech, const std::string&, &Tech::Name > > > > TechManager::TechContainer
TechParseTuple
using TechManager::TechParseTuple = std::tuple< TechManager::TechContainer, std::map<std::string, std::unique_ptr<TechCategory> >, std::set<std::string> >
Constructor & Destructor Documentation
TechManager()
TechManager::TechManager () private
Member Function Documentation
AllChildren()
void TechManager::AllChildren (const Tech * tech, std::map< std::string, std::string > & children) const private
References ErrorLogger, GetTech(), Tech::Name(), and Tech::UnlockedTechs().
AllNextTechs()
std::vector< const Tech * > TechManager::AllNextTechs (const std::set< std::string > & known_techs)
returns all researchable techs
References anonymous_namespace{Tech.cpp}::NextTechs().
begin()
TechManager::iterator TechManager::begin () const
iterator to the first tech
category_begin()
TechManager::category_iterator TechManager::category_begin (const std::string & name) const
iterator to the first tech in category name
category_end()
TechManager::category_iterator TechManager::category_end (const std::string & name) const
iterator to the last + 1th tech in category name
CategoryNames()
std::vector< std::string > TechManager::CategoryNames () const
returns the list of category names
Referenced by TechTreeWnd::LayoutPanel::ShowAllCategories(), TechTreeWnd::TechListBox::ShowAllCategories(), TechTreeWnd::ToggleAllCategories(), and FreeOrionPython::WrapEmpire().
CheapestNextTech()
const Tech * TechManager::CheapestNextTech (const std::set< std::string > & known_techs, int empire_id)
returns the cheapest researchable tech
References anonymous_namespace{Tech.cpp}::Cheapest().
CheapestNextTechTowards()
const Tech * TechManager::CheapestNextTechTowards (const std::set< std::string > & known_techs, const std::string & desired_tech, int empire_id)
returns the cheapest researchable tech that progresses from the given known techs to the given desired tech
References anonymous_namespace{Tech.cpp}::Cheapest().
CheckPendingTechs()
void TechManager::CheckPendingTechs () const private
Assigns any m_pending_types to m_techs.
References ErrorLogger, GetTech(), UserString(), and Pending::WaitForPending().
end()
TechManager::iterator TechManager::end () const
iterator to the last + 1th tech
FindFirstDependencyCycle()
std::string TechManager::FindFirstDependencyCycle () const private
returns an error string indicating the first prerequisite dependency cycle found in m_techs, or an empty string if there are no dependency cycles
References GetTech(), Tech::Name(), and Tech::Prerequisites().
FindIllegalDependencies()
std::string TechManager::FindIllegalDependencies () const private
returns an error string indicating the first instance of an illegal prerequisite relationship between two techs in m_techs, or an empty string if there are no illegal dependencies
References GetTech().
FindRedundantDependency()
std::string TechManager::FindRedundantDependency () const private
returns an error string indicating the first instance of a redundant dependency, or an empty string if there are no redundant dependencies.
An example of a redundant dependency is A –> C, if A –> B and B –> C.
References GetTech().
GetCheckSum()
unsigned int TechManager::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), and DebugLogger.
Referenced by CheckSumContent().
GetTech()
const Tech * TechManager::GetTech (const std::string & name) const
returns the tech with the name name; you should use the free function GetTech() instead
Referenced by GetTech(), and ClientUI::TechIcon().
GetTechCategory()
const TechCategory * TechManager::GetTechCategory (const std::string & name) const
returns the tech category with the name name; you should use the free function GetTechCategory() instead
Referenced by GetTechCategory().
GetTechManager()
TechManager & TechManager::GetTechManager () static
returns the instance of this singleton class; you should use the free function GetTechManager() instead
Referenced by GetTechManager().
NextTechsTowards()
std::vector< const Tech * > TechManager::NextTechsTowards (const std::set< std::string > & known_techs, const std::string & desired_tech, int empire_id)
returns all researchable techs that progress from the given known techs to the given desired tech
References anonymous_namespace{Tech.cpp}::NextTechs().
RecursivePrereqs()
std::vector< std::string > TechManager::RecursivePrereqs (const std::string & tech_name, int empire_id, bool min_required = true) const
Returns names of indicated tech's prerequisites, and all prereqs of those techs, etc.
recursively. If min_required is false then prereqs will be included and recursed into even if already known to the empire.
References GetEmpire(), GetTech(), Tech::Prerequisites(), and Tech::ResearchCost().
Referenced by TechTreeWnd::AddTechToResearchQueue(), and FreeOrionPython::WrapEmpire().
SetTechs()
void TechManager::SetTechs (Pending::Pending< TechParseTuple > && future)
Sets types to the value of future.
Referenced by IApp::StartBackgroundParsing().
size()
size_t TechManager::size () const
TechNames() [1/2]
std::vector< std::string > TechManager::TechNames () const
returns list of all tech names
Referenced by FreeOrionPython::WrapEmpire().
TechNames() [2/2]
std::vector< std::string > TechManager::TechNames (const std::string & name) const
returns list of names of techs in specified category
Member Data Documentation
m_categories
TechCategoryMap TechManager::m_categories mutable private
m_pending_types
boost::optional<Pending::Pending<TechParseTuple> > TechManager::m_pending_types = boost::none mutable private
Future types being parsed by parser.
mutable so that it can be assigned to m_species_types when completed.
m_techs
TechContainer TechManager::m_techs mutable private
s_instance
TechManager * TechManager::s_instance = nullptr static private
Referenced by Tech::GetCheckSum().
The documentation for this class was generated from the following files:
Tech.h
Tech.cpp