FreeOrion: MessageWndEdit Class Reference
MessageWndEdit Class Reference
Public Member Functions
MessageWndEdit ()
bool AutoComplete () override
Autocomplete current word.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Public Member Functions inherited from CUIEdit
CUIEdit (std::string str)
void AcceptPastedText (const std::string &text) override
void CompleteConstruction () override
void DisallowChars (const std::string &chars)
void GainingFocus () override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void LosingFocus () override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
Public Attributes
boost::signals2::signal< void()> DownPressedSignal
boost::signals2::signal< void()> TextEnteredSignal
emitted when user presses enter/return while entering text
boost::signals2::signal< void()> UpPressedSignal
Public Attributes inherited from CUIEdit
boost::signals2::signal< void()> GainingFocusSignal
boost::signals2::signal< void()> LosingFocusSignal
Private Member Functions
bool CompleteWord (const std::set< std::string > &names, const std::string &partial_word, const std::pair< GG::CPSize, const GG::CPSize > &cursor_pos, std::string &text)
AutoComplete helper function.
void FindGameWords ()
Finds all game words for autocomplete.
Private Attributes
std::vector< std::string > m_auto_complete_choices
std::set< std::string > m_game_words
std::string m_last_game_word
std::string m_last_line_read
unsigned int m_repeated_tab_count = 0
Constructor & Destructor Documentation
MessageWndEdit()
MessageWndEdit::MessageWndEdit ()
Member Function Documentation
AutoComplete()
bool MessageWndEdit::AutoComplete () override virtual
Autocomplete current word.
Reimplemented from CUIEdit.
References CompleteWord(), FindGameWords(), m_auto_complete_choices, m_game_words, m_last_game_word, m_last_line_read, and m_repeated_tab_count.
CompleteWord()
bool MessageWndEdit::CompleteWord (const std::set< std::string > & names, const std::string & partial_word, const std::pair< GG::CPSize, const GG::CPSize > & cursor_pos, std::string & text) private
AutoComplete helper function.
References m_auto_complete_choices, m_last_game_word, m_last_line_read, and m_repeated_tab_count.
Referenced by AutoComplete().
FindGameWords()
void MessageWndEdit::FindGameWords () private
Finds all game words for autocomplete.
References ObjectMap::all(), Empires(), GetBuildingTypeManager(), PredefinedShipDesignManager::GetOrderedShipDesigns(), GetPredefinedShipDesignManager(), GetSpeciesManager(), GetTechManager(), GetUniverse(), m_game_words, Universe::Objects(), SpecialNames(), parse::species(), TechManager::TechNames(), and UserString().
Referenced by AutoComplete().
KeyPress()
void MessageWndEdit::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References DownPressedSignal, CUIEdit::KeyPress(), TextEnteredSignal, and UpPressedSignal.
Member Data Documentation
DownPressedSignal
boost::signals2::signal<void ()> MessageWndEdit::DownPressedSignal mutable
Referenced by KeyPress().
m_auto_complete_choices
std::vector<std::string> MessageWndEdit::m_auto_complete_choices private
Referenced by AutoComplete(), and CompleteWord().
m_game_words
std::set<std::string> MessageWndEdit::m_game_words private
Referenced by AutoComplete(), and FindGameWords().
m_last_game_word
std::string MessageWndEdit::m_last_game_word private
Referenced by AutoComplete(), and CompleteWord().
m_last_line_read
std::string MessageWndEdit::m_last_line_read private
Referenced by AutoComplete(), and CompleteWord().
m_repeated_tab_count
unsigned int MessageWndEdit::m_repeated_tab_count = 0 private
Referenced by AutoComplete(), and CompleteWord().
TextEnteredSignal
boost::signals2::signal<void ()> MessageWndEdit::TextEnteredSignal mutable
emitted when user presses enter/return while entering text
Referenced by KeyPress().
UpPressedSignal
boost::signals2::signal<void ()> MessageWndEdit::UpPressedSignal mutable
Referenced by KeyPress().
The documentation for this class was generated from the following file:
ChatWnd.cpp