FreeOrion: PythonServer Class Reference
PythonServer Class Reference
#include <ServerFramework.h>
Public Member Functions
bool CreateUniverse (std::map< int, PlayerSetupData > &player_setup_data)
bool ExecuteTurnEvents ()
bool FillListPlayers (std::list< PlayerSetupData > &players) const
bool GetPlayerDelegation (const std::string &player_name, std::list< std::string > &result) const
bool InitImports () override
Initializes server Python imports.
bool InitModules () override
Initializes server Python modules.
bool IsRequireAuthOrReturnRoles (const std::string &player_name, bool &result, Networking::AuthRoles &roles) const
bool IsSuccessAuthAndReturnRoles (const std::string &player_name, const std::string &auth, bool &result, Networking::AuthRoles &roles) const
bool LoadChatHistory (boost::circular_buffer< ChatHistoryEntity > &chat_history)
bool PutChatHistoryEntity (const ChatHistoryEntity &chat_history_entity)
Public Member Functions inherited from PythonBase
PythonBase ()
virtual ~PythonBase ()
void AddToSysPath (const std::string dir)
std::vector< std::string > ErrorReport ()
virtual bool InitCommonImports () override
bool Initialize ()
void SetCurrentDir (const std::string dir)
void SetErrorModule (boost::python::object &module)
Public Member Functions inherited from PythonCommon
PythonCommon ()
virtual ~PythonCommon ()
void Finalize ()
void HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
bool Initialize ()
bool IsPythonRunning () const
IsPythonRunning returns true is the python interpreter is initialized.
Private Attributes
boost::python::object m_python_module_auth
boost::python::object m_python_module_chat
boost::python::object m_python_module_turn_events
boost::python::object m_python_module_universe_generator
Member Function Documentation
CreateUniverse()
auto PythonServer::CreateUniverse (std::map< int, PlayerSetupData > & player_setup_data)
References ErrorLogger, and GetPythonUniverseGeneratorDir().
Referenced by ServerApp::GenerateUniverse().
ExecuteTurnEvents()
auto PythonServer::ExecuteTurnEvents ()
References ErrorLogger.
Referenced by ServerApp::ExecuteScriptedTurnEvents().
FillListPlayers()
auto PythonServer::FillListPlayers (std::list< PlayerSetupData > & players) const
References DebugLogger, and ErrorLogger.
Referenced by ServerApp::FillListPlayers().
GetPlayerDelegation()
auto PythonServer::GetPlayerDelegation (const std::string & player_name, std::list< std::string > & result) const
References DebugLogger, and ErrorLogger.
Referenced by ServerApp::GetPlayerDelegation().
InitImports()
auto PythonServer::InitImports () override virtual
Initializes server Python imports.
Implements PythonBase.
References DebugLogger.
InitModules()
auto PythonServer::InitModules () override virtual
Initializes server Python modules.
Implements PythonBase.
References DebugLogger, ErrorLogger, GetPythonAuthDir(), GetPythonChatDir(), GetPythonTurnEventsDir(), and GetPythonUniverseGeneratorDir().
IsRequireAuthOrReturnRoles()
auto PythonServer::IsRequireAuthOrReturnRoles (const std::string & player_name, bool & result, Networking::AuthRoles & roles) const
References ErrorLogger.
Referenced by ServerApp::IsAuthRequiredOrFillRoles().
IsSuccessAuthAndReturnRoles()
auto PythonServer::IsSuccessAuthAndReturnRoles (const std::string & player_name, const std::string & auth, bool & result, Networking::AuthRoles & roles) const
References DebugLogger, and ErrorLogger.
Referenced by ServerApp::IsAuthSuccessAndFillRoles().
LoadChatHistory()
auto PythonServer::LoadChatHistory (boost::circular_buffer< ChatHistoryEntity > & chat_history)
References ErrorLogger, ChatHistoryEntity::player_name, ChatHistoryEntity::text, ChatHistoryEntity::text_color, and ChatHistoryEntity::timestamp.
Referenced by ServerApp::LoadChatHistory().
PutChatHistoryEntity()
auto PythonServer::PutChatHistoryEntity (const ChatHistoryEntity & chat_history_entity)
References ErrorLogger.
Referenced by ServerApp::PushChatMessage().
Member Data Documentation
m_python_module_auth
boost::python::object PythonServer::m_python_module_auth private
m_python_module_chat
boost::python::object PythonServer::m_python_module_chat private
m_python_module_turn_events
boost::python::object PythonServer::m_python_module_turn_events private
m_python_module_universe_generator
boost::python::object PythonServer::m_python_module_universe_generator private
The documentation for this class was generated from the following files:
ServerFramework.h
ServerFramework.cpp