FreeOrion: CUIArrowButton Class Reference
CUIArrowButton Class Reference
a FreeOrion triangular arrow button
#include <CUIControls.h>
Public Member Functions
CUIArrowButton (ShapeOrientation orientation, bool fill_background, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE)
bool InWindow (const GG::Pt &pt) const override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Protected Member Functions
void RenderPressed () override
void RenderRollover () override
void RenderUnpressed () override
Private Attributes
bool m_fill_background_with_wnd_color
ShapeOrientation m_orientation
Detailed Description
a FreeOrion triangular arrow button
Constructor & Destructor Documentation
CUIArrowButton()
CUIArrowButton::CUIArrowButton (ShapeOrientation orientation, bool fill_background, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE)
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Member Function Documentation
InWindow()
bool CUIArrowButton::InWindow (const GG::Pt & pt) const override
References InIsoscelesTriangle(), m_fill_background_with_wnd_color, and m_orientation.
MouseHere()
void CUIArrowButton::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
RenderPressed()
void CUIArrowButton::RenderPressed () override protected
References anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, m_fill_background_with_wnd_color, RenderUnpressed(), and ClientUI::WndColor().
RenderRollover()
void CUIArrowButton::RenderRollover () override protected
References AdjustBrightness(), anonymous_namespace{CUIControls.cpp}::ARROW_BRIGHTENING_SCALE_FACTOR, anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, IsoscelesTriangle(), m_fill_background_with_wnd_color, m_orientation, and ClientUI::WndColor().
RenderUnpressed()
void CUIArrowButton::RenderUnpressed () override protected
References anonymous_namespace{ServerFSM.cpp}::CLR_ZERO, IsoscelesTriangle(), m_fill_background_with_wnd_color, m_orientation, and ClientUI::WndColor().
Referenced by RenderPressed().
Member Data Documentation
m_fill_background_with_wnd_color
bool CUIArrowButton::m_fill_background_with_wnd_color private
Referenced by InWindow(), RenderPressed(), RenderRollover(), and RenderUnpressed().
m_orientation
ShapeOrientation CUIArrowButton::m_orientation private
Referenced by InWindow(), RenderRollover(), and RenderUnpressed().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp