FreeOrion: MeterBrowseWnd Class Reference
MeterBrowseWnd Class Reference
#include <MeterBrowseWnd.h>
Public Member Functions
MeterBrowseWnd (int object_id, MeterType primary_meter_type, MeterType secondary_meter_type)
MeterBrowseWnd (int object_id, MeterType primary_meter_type)
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Protected Member Functions
void Initialize ()
void UpdateEffectLabelsAndValues (GG::Y &top)
void UpdateImpl (std::size_t mode, const Wnd *target) override
void UpdateSummary ()
Protected Attributes
std::shared_ptr< GG::Label > m_change_label = nullptr
std::shared_ptr< GG::Label > m_change_value = nullptr
std::shared_ptr< GG::Label > m_current_label = nullptr
std::shared_ptr< GG::Label > m_current_value = nullptr
std::vector< std::pair< std::shared_ptr< GG::Label >, std::shared_ptr< GG::Label > > > m_effect_labels_and_values
bool m_initialized = false
std::shared_ptr< GG::Label > m_meter_title = nullptr
std::shared_ptr< GG::Label > m_next_turn_label = nullptr
std::shared_ptr< GG::Label > m_next_turn_value = nullptr
int m_object_id
MeterType m_primary_meter_type
GG::Y m_row_height = GG::Y1
MeterType m_secondary_meter_type
std::shared_ptr< GG::Label > m_summary_title = nullptr
Detailed Description
Gives details about what effects contribute to a meter's maximum value (Effect Accounting) and shows the current turn's current meter value and the predicted current meter value for next turn.
Constructor & Destructor Documentation
MeterBrowseWnd::MeterBrowseWnd (int object_id, MeterType primary_meter_type, MeterType secondary_meter_type)
MeterBrowseWnd::MeterBrowseWnd (int object_id, MeterType primary_meter_type)
Member Function Documentation
void MeterBrowseWnd::Initialize () protected
References anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), ErrorLogger, FlexibleFormat(), ClientUI::GetBoldFont(), GetUniverseObject(), m_change_label, m_change_value, m_current_label, m_current_value, m_initialized, m_meter_title, m_next_turn_label, m_next_turn_value, m_object_id, m_primary_meter_type, m_row_height, m_secondary_meter_type, m_summary_title, METER_POPULATION, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterToUserString(), UpdateEffectLabelsAndValues(), UpdateSummary(), and UserString().
Referenced by UpdateImpl().
void MeterBrowseWnd::Render () override
References anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD(), m_meter_title, m_summary_title, OpaqueColor(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void MeterBrowseWnd::UpdateEffectLabelsAndValues (GG::Y & top) protected
References anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), FlexibleFormat(), anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), GetEmpire(), GetPlanet(), GetUniverseObject(), info, INVALID_METER_TYPE, m_effect_labels_and_values, m_object_id, m_primary_meter_type, m_row_height, m_secondary_meter_type, anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth(), and UserString().
Referenced by Initialize().
void MeterBrowseWnd::UpdateImpl (std::size_t mode, const Wnd * target) override protected
References Initialize(), and m_initialized.
void MeterBrowseWnd::UpdateSummary () protected
References anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), Meter::Current(), DoubleToString(), ErrorLogger, FlexibleFormat(), GetUniverseObject(), Meter::Initial(), m_change_value, m_current_value, m_meter_title, m_next_turn_value, m_object_id, m_primary_meter_type, m_secondary_meter_type, anonymous_namespace{MeterBrowseWnd.cpp}::MeterToUserString(), and UserString().
Referenced by Initialize().
bool MeterBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
std::shared_ptr<GG::Label> MeterBrowseWnd::m_change_label = nullptr protected
Referenced by Initialize().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_change_value = nullptr protected
Referenced by Initialize(), and UpdateSummary().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_current_label = nullptr protected
Referenced by Initialize().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_current_value = nullptr protected
Referenced by Initialize(), and UpdateSummary().
std::vector<std::pair<std::shared_ptr<GG::Label>, std::shared_ptr<GG::Label> > > MeterBrowseWnd::m_effect_labels_and_values protected
Referenced by UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
bool MeterBrowseWnd::m_initialized = false protected
Referenced by Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), UpdateImpl(), ShipDamageBrowseWnd::UpdateImpl(), and ShipFightersBrowseWnd::UpdateImpl().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_meter_title = nullptr protected
Referenced by Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), Render(), UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_next_turn_label = nullptr protected
Referenced by Initialize().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_next_turn_value = nullptr protected
Referenced by Initialize(), and UpdateSummary().
int MeterBrowseWnd::m_object_id protected
Referenced by Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
MeterType MeterBrowseWnd::m_primary_meter_type protected
Referenced by Initialize(), UpdateEffectLabelsAndValues(), and UpdateSummary().
GG::Y MeterBrowseWnd::m_row_height = GG::Y1 protected
Referenced by Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
MeterType MeterBrowseWnd::m_secondary_meter_type protected
Referenced by Initialize(), UpdateEffectLabelsAndValues(), and UpdateSummary().
std::shared_ptr<GG::Label> MeterBrowseWnd::m_summary_title = nullptr protected
Referenced by Initialize(), and Render().
The documentation for this class was generated from the following files:
MeterBrowseWnd.h
MeterBrowseWnd.cpp