FreeOrion: GameRulesPanel Class Reference
GameRulesPanel Class Reference
Displays game rules options.
#include <GalaxySetupWnd.h>
Public Member Functions
void CompleteConstruction () override
Structors
GameRulesPanel (GG::X w=GG::X1, GG::Y h=GG::Y1)
Accessors
std::map< std::string, std::string > GetRulesAsStrings () const
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Render () override
void Disable (bool b=true) override
Public Attributes
boost::signals2::signal< void()> SettingsChangedSignal
Private Member Functions
void BoolRuleChanged (bool value, const std::string &rule_name)
GG::StateButton * BoolRuleWidget (GG::ListBox *page, int indentation_level, const std::string &rule_name)
GG::ListBox * CreatePage (const std::string &name)
void CreateSectionHeader (GG::ListBox *page, int indentation_level, const std::string &name, const std::string &tooltip="")
void DoLayout ()
void DoubleRuleChanged (double value, const std::string &rule_name)
GG::Spin< double > * DoubleRuleWidget (GG::ListBox *page, int indentation_level, const std::string &rule_name)
void IntRuleChanged (int value, const std::string &rule_name)
GG::Spin< int > * IntRuleWidget (GG::ListBox *page, int indentation_level, const std::string &rule_name)
void SettingChanged ()
void StringRuleChanged (const GG::DropDownList *drop, const std::string &rule_name)
GG::DropDownList * StringRuleWidget (GG::ListBox *page, int indentation_level, const std::string &rule_name)
Private Attributes
std::map< std::string, std::string > m_rules
std::shared_ptr< GG::TabWnd > m_tabs
Detailed Description
Displays game rules options.
Constructor & Destructor Documentation
GameRulesPanel()
GameRulesPanel::GameRulesPanel (GG::X w = GG::X1, GG::Y h = GG::Y1)
Member Function Documentation
BoolRuleChanged()
void GameRulesPanel::BoolRuleChanged (bool value, const std::string & rule_name) private
References DebugLogger, GetGameRules(), GameRules::GetValidator(), m_rules, and SettingChanged().
Referenced by BoolRuleWidget().
BoolRuleWidget()
GG::StateButton * GameRulesPanel::BoolRuleWidget (GG::ListBox * page, int indentation_level, const std::string & rule_name) private
References BoolRuleChanged(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), GetGameRules(), GetOptionsDB(), and UserString().
Referenced by CompleteConstruction().
CompleteConstruction()
void GameRulesPanel::CompleteConstruction () override
References BoolRuleWidget(), CreatePage(), DebugLogger, DoLayout(), GameRules::DOUBLE, DoubleRuleWidget(), ErrorLogger, ClientUI::GetFont(), GetGameRules(), GameRules::INT, IntRuleWidget(), m_tabs, anonymous_namespace{GalaxySetupWnd.cpp}::SPIN_WIDTH(), GameRules::STRING, StringRuleWidget(), ClientUI::TextColor(), GameRules::TOGGLE, UserString(), and ClientUI::WndColor().
CreatePage()
GG::ListBox * GameRulesPanel::CreatePage (const std::string & name) private
References ErrorLogger, and m_tabs.
Referenced by CompleteConstruction().
CreateSectionHeader()
void GameRulesPanel::CreateSectionHeader (GG::ListBox * page, int indentation_level, const std::string & name, const std::string & tooltip = "") private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), ClientUI::GetFont(), GetOptionsDB(), and ClientUI::Pts().
Disable()
void GameRulesPanel::Disable (bool b = true) override
Referenced by GalaxySetupPanel::Render().
DoLayout()
void GameRulesPanel::DoLayout () private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_MARGIN(), anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), and m_tabs.
Referenced by CompleteConstruction(), GalaxySetupWnd::EndedWithOk(), GalaxySetupPanel::Render(), and SizeMove().
DoubleRuleChanged()
void GameRulesPanel::DoubleRuleChanged (double value, const std::string & rule_name) private
References DebugLogger, GetGameRules(), GameRules::GetValidator(), m_rules, and SettingChanged().
Referenced by DoubleRuleWidget().
DoubleRuleWidget()
GG::Spin< double > * GameRulesPanel::DoubleRuleWidget (GG::ListBox * page, int indentation_level, const std::string & rule_name) private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), DoubleRuleChanged(), ErrorLogger, GameRules::Get(), GetGameRules(), GetOptionsDB(), GameRules::GetValidator(), anonymous_namespace{GalaxySetupWnd.cpp}::SPIN_WIDTH(), and UserString().
Referenced by CompleteConstruction().
GetRulesAsStrings()
std::map< std::string, std::string > GameRulesPanel::GetRulesAsStrings () const
References m_rules.
Referenced by GalaxySetupWnd::EndedWithOk().
IntRuleChanged()
void GameRulesPanel::IntRuleChanged (int value, const std::string & rule_name) private
References DebugLogger, GetGameRules(), GameRules::GetValidator(), m_rules, and SettingChanged().
Referenced by IntRuleWidget().
IntRuleWidget()
GG::Spin< int > * GameRulesPanel::IntRuleWidget (GG::ListBox * page, int indentation_level, const std::string & rule_name) private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), ErrorLogger, GameRules::Get(), GetGameRules(), GetOptionsDB(), GameRules::GetValidator(), IntRuleChanged(), anonymous_namespace{GalaxySetupWnd.cpp}::SPIN_WIDTH(), and UserString().
Referenced by CompleteConstruction().
Render()
void GameRulesPanel::Render () override
References m_tabs, and ClientUI::WndInnerBorderColor().
Referenced by GalaxySetupWnd::EndedWithOk().
SettingChanged()
void GameRulesPanel::SettingChanged () private
References SettingsChangedSignal.
Referenced by BoolRuleChanged(), DoubleRuleChanged(), IntRuleChanged(), GalaxySetupPanel::Render(), and StringRuleChanged().
SizeMove()
void GameRulesPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
Referenced by GalaxySetupWnd::EndedWithOk().
StringRuleChanged()
void GameRulesPanel::StringRuleChanged (const GG::DropDownList * drop, const std::string & rule_name) private
References DebugLogger, ErrorLogger, GetGameRules(), GameRules::GetValidator(), m_rules, and SettingChanged().
Referenced by StringRuleWidget().
StringRuleWidget()
GG::DropDownList * GameRulesPanel::StringRuleWidget (GG::ListBox * page, int indentation_level, const std::string & rule_name) private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN(), GameRules::Get(), GetGameRules(), GetOptionsDB(), GameRules::GetValidator(), anonymous_namespace{GalaxySetupWnd.cpp}::SPIN_WIDTH(), StringRuleChanged(), and UserString().
Referenced by CompleteConstruction().
Member Data Documentation
m_rules
std::map<std::string, std::string> GameRulesPanel::m_rules private
Referenced by BoolRuleChanged(), DoubleRuleChanged(), GetRulesAsStrings(), IntRuleChanged(), and StringRuleChanged().
m_tabs
std::shared_ptr<GG::TabWnd> GameRulesPanel::m_tabs private
Referenced by CompleteConstruction(), CreatePage(), DoLayout(), and Render().
SettingsChangedSignal
boost::signals2::signal<void ()> GameRulesPanel::SettingsChangedSignal mutable
Referenced by SettingChanged().
The documentation for this class was generated from the following files:
GalaxySetupWnd.h
GalaxySetupWnd.cpp