FreeOrion: QueueListBox Class Reference
QueueListBox Class Reference
A list box type for representing queues (eg the research and production queues).
#include <QueueListBox.h>
Public Member Functions
QueueListBox (const boost::optional< std::string > &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
void CompleteConstruction () override
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
virtual void EnableOrderIssuing (bool enable=true)
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
Protected Member Functions
virtual std::function< void()> DeleteAction (GG::ListBox::iterator it) const
Return a functor that will signal that it should be deleted.
virtual void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
virtual std::function< void()> MoveToBottomAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the bottom of the list.
virtual std::function< void()> MoveToTopAction (GG::ListBox::iterator it)
Return a functor that will signal that it should be moved to the top of the list.
Private Member Functions
void EnsurePromptHiddenSlot (iterator it)
void ItemRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void ShowPromptConditionallySlot (iterator it)
void ShowPromptSlot ()
Private Attributes
iterator m_drop_point
bool m_order_issuing_enabled
std::string m_prompt_str
bool m_show_drop_point
bool m_showing_prompt
Detailed Description
A list box type for representing queues (eg the research and production queues).
Constructor & Destructor Documentation
QueueListBox::QueueListBox (const boost::optional< std::string > & drop_type_str, const std::string & prompt_str)
Member Function Documentation
void QueueListBox::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
References ErrorLogger.
void QueueListBox::Clear ()
References DragDropLeave().
Referenced by BasesListBox::Populate(), ResearchWnd::UpdateQueue(), and ProductionWnd::UpdateQueue().
void QueueListBox::CompleteConstruction () override
References EnsurePromptHiddenSlot(), ItemRightClicked(), ShowPromptConditionallySlot(), and ShowPromptSlot().
Referenced by ResearchQueueListBox::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::CompleteConstruction(), and BasesListBox::CompleteConstruction().
std::function< void()> QueueListBox::DeleteAction (GG::ListBox::iterator it) const protected virtual
Return a functor that will signal that it should be deleted.
References QueueItemDeletedSignal.
Referenced by ItemRightClickedImpl().
bool QueueListBox::DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
References m_showing_prompt.
void QueueListBox::DragDropHere (const GG::Pt & pt, std::map< const Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
References m_drop_point, and m_show_drop_point.
void QueueListBox::DragDropLeave () override
References m_drop_point, and m_show_drop_point.
Referenced by Clear().
void QueueListBox::EnableOrderIssuing (bool enable = true) virtual
Reimplemented in MonstersListBox, and EmptyHullsListBox.
References m_order_issuing_enabled.
Referenced by BasesListBox::CompleteConstruction(), EmptyHullsListBox::EmptyHullsListBox(), EmptyHullsListBox::EnableOrderIssuing(), MonstersListBox::EnableOrderIssuing(), and MonstersListBox::MonstersListBox().
void QueueListBox::EnsurePromptHiddenSlot (iterator it) private
References m_showing_prompt.
Referenced by CompleteConstruction().
void QueueListBox::ItemRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ItemRightClickedImpl().
Referenced by CompleteConstruction().
void QueueListBox::ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) protected virtual
Reimplemented in BasesListBox, anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox, and ResearchQueueListBox.
References DeleteAction(), MoveToBottomAction(), MoveToTopAction(), and UserString().
Referenced by ItemRightClicked().
void QueueListBox::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override protected
References QueueItemDeletedSignal.
std::function< void()> QueueListBox::MoveToBottomAction (GG::ListBox::iterator it) protected virtual
Return a functor that will signal that it should be moved to the bottom of the list.
Referenced by ItemRightClickedImpl().
std::function< void()> QueueListBox::MoveToTopAction (GG::ListBox::iterator it) protected virtual
Return a functor that will signal that it should be moved to the top of the list.
Referenced by ItemRightClickedImpl().
bool QueueListBox::OrderIssuingEnabled () const inline
void QueueListBox::Render () override
References m_drop_point, m_order_issuing_enabled, and m_show_drop_point.
GG::X QueueListBox::RowWidth () const
Referenced by SizeMove(), ResearchWnd::UpdateQueue(), and ProductionWnd::UpdateQueue().
void QueueListBox::SetEmptyPromptText (const std::string prompt)
Change the empty list prompt text.
References m_prompt_str, m_showing_prompt, and ShowPromptSlot().
Referenced by BasesListBox::Populate(), BasesListBox::ResetEmptyListPrompt(), CompletedDesignsListBox::ResetEmptyListPrompt(), and SavedDesignsListBox::ResetEmptyListPrompt().
void QueueListBox::ShowPromptConditionallySlot (iterator it) private
References ShowPromptSlot().
Referenced by CompleteConstruction().
void QueueListBox::ShowPromptSlot () private
References m_prompt_str, and m_showing_prompt.
Referenced by CompleteConstruction(), SetEmptyPromptText(), and ShowPromptConditionallySlot().
void QueueListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References RowWidth().
Member Data Documentation
iterator QueueListBox::m_drop_point private
Referenced by DragDropHere(), DragDropLeave(), and Render().
bool QueueListBox::m_order_issuing_enabled private
Referenced by EnableOrderIssuing(), and Render().
std::string QueueListBox::m_prompt_str private
Referenced by SetEmptyPromptText(), and ShowPromptSlot().
bool QueueListBox::m_show_drop_point private
Referenced by DragDropHere(), DragDropLeave(), and Render().
bool QueueListBox::m_showing_prompt private
Referenced by DisplayingValidQueueItems(), EnsurePromptHiddenSlot(), SetEmptyPromptText(), and ShowPromptSlot().
boost::signals2::signal<void (GG::ListBox::iterator)> QueueListBox::QueueItemDeletedSignal
Referenced by DeleteAction(), and KeyPress().
The documentation for this class was generated from the following files:
QueueListBox.h
QueueListBox.cpp