FreeOrion: PartControl Class Reference
PartControl Class Reference
UI representation of a ship part.
Public Member Functions
PartControl (const ShipPart *part)
void CompleteConstruction () override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
const ShipPart * Part () const
const std::string & PartName () const
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void SetAvailability (const AvailabilityManager::DisplayedAvailabilies &type)
Public Attributes
boost::signals2::signal< void(const ShipPart *, GG::Flags< GG::ModKey >)> ClickedSignal
boost::signals2::signal< void(const ShipPart *)> DoubleClickedSignal
boost::signals2::signal< void(const ShipPart *, const GG::Pt &pt)> RightClickedSignal
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_background = nullptr
std::shared_ptr< GG::StaticGraphic > m_icon = nullptr
const ShipPart * m_part = nullptr
Detailed Description
UI representation of a ship part.
Displayed in the PartPalette, and can be dragged onto SlotControls to add parts to the design.
Constructor & Destructor Documentation
PartControl()
PartControl::PartControl (const ShipPart * part)
Member Function Documentation
CompleteConstruction()
void PartControl::CompleteConstruction () override
References GetOptionsDB(), m_background, m_icon, m_part, anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_DROP_TYPE_STRING, anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_HEIGHT(), anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_WIDTH(), anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture(), ClientUI::PartIcon(), anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_HEIGHT(), anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH(), and UserString().
LClick()
void PartControl::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References ClickedSignal, and m_part.
LDoubleClick()
void PartControl::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References DoubleClickedSignal, and m_part.
Part()
const ShipPart* PartControl::Part () const inline
Referenced by SlotControl::AcceptDrops(), and PartsListBox::PartsListBoxRow::ChildrenDraggedAway().
PartName()
const std::string& PartControl::PartName () const inline
References anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING.
RClick()
void PartControl::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_part, and RightClickedSignal.
Render()
void PartControl::Render () override
SetAvailability()
void PartControl::SetAvailability (const AvailabilityManager::DisplayedAvailabilies & type)
References m_background, and m_icon.
Member Data Documentation
ClickedSignal
boost::signals2::signal<void (const ShipPart*, GG::Flags<GG::ModKey>)> PartControl::ClickedSignal mutable
Referenced by LClick().
DoubleClickedSignal
boost::signals2::signal<void (const ShipPart*)> PartControl::DoubleClickedSignal mutable
Referenced by LDoubleClick().
m_background
std::shared_ptr<GG::StaticGraphic> PartControl::m_background = nullptr private
Referenced by CompleteConstruction(), and SetAvailability().
m_icon
std::shared_ptr<GG::StaticGraphic> PartControl::m_icon = nullptr private
Referenced by CompleteConstruction(), and SetAvailability().
m_part
const ShipPart* PartControl::m_part = nullptr private
Referenced by CompleteConstruction(), LClick(), LDoubleClick(), and RClick().
RightClickedSignal
boost::signals2::signal<void (const ShipPart*, const GG::Pt& pt)> PartControl::RightClickedSignal mutable
Referenced by RClick().
The documentation for this class was generated from the following file:
DesignWnd.cpp