FreeOrion: TechTreeWnd::LayoutPanel Class Reference
TechTreeWnd::LayoutPanel Class Reference
The window that contains the actual tech panels and dependency arcs.
Classes
class LayoutSurface
class TechPanel
Represents a single tech in the LayoutPanel.
Public Member Functions
void CompleteConstruction () override
Structors
LayoutPanel (GG::X w, GG::Y h)
Mutators //@{
void Render () override
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void Update ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void Clear ()
remove all tech panels
void Reset ()
redo layout, recentre on a tech
void SetScale (double scale)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void ShowCategory (const std::string &category)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void ShowAllCategories ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void HideCategory (const std::string &category)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void HideAllCategories ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void ShowStatus (TechStatus status)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void HideStatus (TechStatus status)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void SelectTech (const std::string &tech_name)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void CenterOnTech (const std::string &tech_name)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void DoZoom (const GG::Pt &pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
void UndoZoom () const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
GG::Pt ConvertPtScreenToZoomed (const GG::Pt &pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
GG::Pt ConvertPtZoomedToScreen (const GG::Pt &pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
Private Member Functions
void ConnectKeyboardAcceleratorSignals ()
void DoLayout ()
void Layout (bool keep_position)
void ScrolledSlot (int, int, int, int)
void TreeDragBegin (const GG::Pt &move)
void TreeDragEnd (const GG::Pt &move)
void TreeDraggedSlot (const GG::Pt &move)
void TreeZoomedSlot (int move)
bool TreeZoomInKeyboard ()
bool TreeZoomOutKeyboard ()
Private Attributes
std::string m_browsed_tech_name
std::set< std::string > m_categories_shown
TechTreeArcs m_dependency_arcs
double m_drag_scroll_position_x = 0.0
double m_drag_scroll_position_y = 0.0
TechTreeLayout m_graph
std::shared_ptr< GG::Scroll > m_hscroll
std::shared_ptr< LayoutSurface > m_layout_surface
double m_scale = INITIAL_SCALE
double m_scroll_position_x = 0.0
double m_scroll_position_y = 0.0
std::string m_selected_tech_name
std::set< TechStatus > m_tech_statuses_shown
std::map< std::string, std::shared_ptr< TechPanel > > m_techs
std::shared_ptr< GG::Scroll > m_vscroll
std::shared_ptr< GG::Button > m_zoom_in_button
std::shared_ptr< GG::Button > m_zoom_out_button
Accessors
TechTreeWnd::TechClickSignalType TechSelectedSignal
TechTreeWnd::TechClickSignalType TechDoubleClickedSignal
TechTreeWnd::TechSignalType TechPediaDisplaySignal
GG::Pt ClientLowerRight () const override
double Scale () const
std::set< std::string > GetCategoriesShown () const
std::set< TechStatus > GetTechStatusesShown () const
Detailed Description
The window that contains the actual tech panels and dependency arcs.
Constructor & Destructor Documentation
LayoutPanel()
TechTreeWnd::LayoutPanel::LayoutPanel (GG::X w, GG::Y h)
Member Function Documentation
CenterOnTech()
void TechTreeWnd::LayoutPanel::CenterOnTech (const std::string & tech_name)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References DebugLogger, m_hscroll, m_techs, and m_vscroll.
Referenced by Layout().
Clear()
void TechTreeWnd::LayoutPanel::Clear ()
remove all tech panels
References TechTreeLayout::Clear(), m_dependency_arcs, m_graph, m_hscroll, m_layout_surface, m_selected_tech_name, m_techs, m_vscroll, and TechTreeArcs::Reset().
Referenced by Layout().
ClientLowerRight()
GG::Pt TechTreeWnd::LayoutPanel::ClientLowerRight () const override
References ClientUI::ScrollWidth().
CompleteConstruction()
void TechTreeWnd::LayoutPanel::CompleteConstruction () override
References ConnectKeyboardAcceleratorSignals(), DoLayout(), GetOptionsDB(), GetTechManager(), m_categories_shown, m_hscroll, m_layout_surface, m_scale, m_tech_statuses_shown, m_vscroll, m_zoom_in_button, m_zoom_out_button, ScrolledSlot(), TreeDragBegin(), TreeDragEnd(), TreeDraggedSlot(), TreeZoomedSlot(), TS_COMPLETE, TS_RESEARCHABLE, ClientUI::WndColor(), and anonymous_namespace{TechTreeWnd.cpp}::ZOOM_STEP_SIZE.
ConnectKeyboardAcceleratorSignals()
void TechTreeWnd::LayoutPanel::ConnectKeyboardAcceleratorSignals () private
References HotkeyManager::Connect(), HotkeyManager::GetManager(), NoModalWndsOpenCondition(), HotkeyManager::RebuildShortcuts(), TreeZoomInKeyboard(), and TreeZoomOutKeyboard().
Referenced by CompleteConstruction().
ConvertPtScreenToZoomed()
GG::Pt TechTreeWnd::LayoutPanel::ConvertPtScreenToZoomed (const GG::Pt & pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References m_scale, m_scroll_position_x, and m_scroll_position_y.
Referenced by TechTreeWnd::LayoutPanel::TechPanel::InWindow().
ConvertPtZoomedToScreen()
GG::Pt TechTreeWnd::LayoutPanel::ConvertPtZoomedToScreen (const GG::Pt & pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References m_scale, m_scroll_position_x, and m_scroll_position_y.
DoLayout()
void TechTreeWnd::LayoutPanel::DoLayout () private
References m_hscroll, m_vscroll, m_zoom_in_button, m_zoom_out_button, and ClientUI::ScrollWidth().
Referenced by CompleteConstruction(), and SizeMove().
DoZoom()
void TechTreeWnd::LayoutPanel::DoZoom (const GG::Pt & pt) const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References m_scale, m_scroll_position_x, and m_scroll_position_y.
Referenced by Render(), and TechTreeWnd::LayoutPanel::TechPanel::Render().
GetCategoriesShown()
std::set< std::string > TechTreeWnd::LayoutPanel::GetCategoriesShown () const
References m_categories_shown.
GetTechStatusesShown()
std::set< TechStatus > TechTreeWnd::LayoutPanel::GetTechStatusesShown () const
References m_tech_statuses_shown.
HideAllCategories()
void TechTreeWnd::LayoutPanel::HideAllCategories ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout(), and m_categories_shown.
HideCategory()
void TechTreeWnd::LayoutPanel::HideCategory (const std::string & category)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout(), and m_categories_shown.
HideStatus()
void TechTreeWnd::LayoutPanel::HideStatus (TechStatus status)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout(), and m_tech_statuses_shown.
Layout()
void TechTreeWnd::LayoutPanel::Layout (bool keep_position) private
References TechTreeLayout::AddEdge(), TechTreeLayout::AddNode(), CenterOnTech(), Clear(), DebugLogger, TechTreeLayout::DoLayout(), OptionsDB::Get(), TechTreeLayout::GetHeight(), TechTreeLayout::GetNode(), GetOptionsDB(), GetTechManager(), TechTreeLayout::GetWidth(), TechTreeLayout::Node::GetX(), TechTreeLayout::Node::GetY(), m_categories_shown, m_dependency_arcs, m_graph, m_hscroll, m_layout_surface, m_selected_tech_name, m_tech_statuses_shown, m_techs, m_vscroll, ClientUI::Pts(), TechTreeArcs::Reset(), SelectTech(), TechDoubleClickedSignal, anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight(), anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth(), TechPediaDisplaySignal, anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), and anonymous_namespace{ProductionWnd.cpp}::X_MARGIN.
Referenced by HideAllCategories(), HideCategory(), HideStatus(), Reset(), ShowAllCategories(), ShowCategory(), ShowStatus(), and Update().
Render()
void TechTreeWnd::LayoutPanel::Render () override
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References ClientUI::CtrlColor(), DoZoom(), m_dependency_arcs, m_hscroll, m_scale, m_vscroll, TechTreeArcs::Render(), and UndoZoom().
Reset()
void TechTreeWnd::LayoutPanel::Reset ()
redo layout, recentre on a tech
References Layout().
Scale()
double TechTreeWnd::LayoutPanel::Scale () const
References m_scale.
Referenced by TechTreeWnd::LayoutPanel::TechPanel::PreRender(), and TechTreeWnd::LayoutPanel::TechPanel::Render().
ScrolledSlot()
void TechTreeWnd::LayoutPanel::ScrolledSlot (int , int , int , int) private
References m_hscroll, m_scroll_position_x, m_scroll_position_y, and m_vscroll.
Referenced by CompleteConstruction().
SelectTech()
void TechTreeWnd::LayoutPanel::SelectTech (const std::string & tech_name)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References m_selected_tech_name, m_techs, and TechSelectedSignal.
Referenced by Layout().
SetScale()
void TechTreeWnd::LayoutPanel::SetScale (double scale)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References GetOptionsDB(), m_scale, m_techs, anonymous_namespace{TechTreeWnd.cpp}::MAX_SCALE, anonymous_namespace{TechTreeWnd.cpp}::MIN_SCALE, OptionsDB::Set(), and anonymous_namespace{TechTreeWnd.cpp}::ZOOM_STEP_SIZE.
Referenced by TreeZoomedSlot().
ShowAllCategories()
void TechTreeWnd::LayoutPanel::ShowAllCategories ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References TechManager::CategoryNames(), GetTechManager(), Layout(), and m_categories_shown.
ShowCategory()
void TechTreeWnd::LayoutPanel::ShowCategory (const std::string & category)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout(), and m_categories_shown.
ShowStatus()
void TechTreeWnd::LayoutPanel::ShowStatus (TechStatus status)
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout(), and m_tech_statuses_shown.
SizeMove()
void TechTreeWnd::LayoutPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References DoLayout().
TreeDragBegin()
void TechTreeWnd::LayoutPanel::TreeDragBegin (const GG::Pt & move) private
References m_drag_scroll_position_x, m_drag_scroll_position_y, m_scroll_position_x, and m_scroll_position_y.
Referenced by CompleteConstruction().
TreeDragEnd()
void TechTreeWnd::LayoutPanel::TreeDragEnd (const GG::Pt & move) private
References m_drag_scroll_position_x, m_drag_scroll_position_y, m_scroll_position_x, and m_scroll_position_y.
Referenced by CompleteConstruction().
TreeDraggedSlot()
void TechTreeWnd::LayoutPanel::TreeDraggedSlot (const GG::Pt & move) private
References m_drag_scroll_position_x, m_drag_scroll_position_y, m_hscroll, m_scale, m_scroll_position_x, m_scroll_position_y, and m_vscroll.
Referenced by CompleteConstruction().
TreeZoomedSlot()
void TechTreeWnd::LayoutPanel::TreeZoomedSlot (int move) private
References m_scale, SetScale(), and anonymous_namespace{TechTreeWnd.cpp}::ZOOM_STEP_SIZE.
Referenced by CompleteConstruction(), TreeZoomInKeyboard(), and TreeZoomOutKeyboard().
TreeZoomInKeyboard()
bool TechTreeWnd::LayoutPanel::TreeZoomInKeyboard () private
References TreeZoomedSlot().
Referenced by ConnectKeyboardAcceleratorSignals().
TreeZoomOutKeyboard()
bool TechTreeWnd::LayoutPanel::TreeZoomOutKeyboard () private
References TreeZoomedSlot().
Referenced by ConnectKeyboardAcceleratorSignals().
UndoZoom()
void TechTreeWnd::LayoutPanel::UndoZoom () const
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
Referenced by Render(), and TechTreeWnd::LayoutPanel::TechPanel::Render().
Update()
void TechTreeWnd::LayoutPanel::Update ()
update indicated tech panel or all panels if tech_name is an empty string, without redoing layout
References Layout().
Referenced by TechTreeWnd::TechListBox::TechRow::GetTech().
Member Data Documentation
m_browsed_tech_name
std::string TechTreeWnd::LayoutPanel::m_browsed_tech_name private
m_categories_shown
std::set<std::string> TechTreeWnd::LayoutPanel::m_categories_shown private
Referenced by CompleteConstruction(), GetCategoriesShown(), HideAllCategories(), HideCategory(), Layout(), ShowAllCategories(), and ShowCategory().
m_dependency_arcs
TechTreeArcs TechTreeWnd::LayoutPanel::m_dependency_arcs private
Referenced by Clear(), Layout(), and Render().
m_drag_scroll_position_x
double TechTreeWnd::LayoutPanel::m_drag_scroll_position_x = 0.0 private
Referenced by TreeDragBegin(), TreeDragEnd(), and TreeDraggedSlot().
m_drag_scroll_position_y
double TechTreeWnd::LayoutPanel::m_drag_scroll_position_y = 0.0 private
Referenced by TreeDragBegin(), TreeDragEnd(), and TreeDraggedSlot().
m_graph
TechTreeLayout TechTreeWnd::LayoutPanel::m_graph private
Referenced by Clear(), and Layout().
m_hscroll
std::shared_ptr<GG::Scroll> TechTreeWnd::LayoutPanel::m_hscroll private
Referenced by CenterOnTech(), Clear(), CompleteConstruction(), DoLayout(), Layout(), Render(), ScrolledSlot(), and TreeDraggedSlot().
m_layout_surface
std::shared_ptr<LayoutSurface> TechTreeWnd::LayoutPanel::m_layout_surface private
Referenced by Clear(), CompleteConstruction(), and Layout().
m_scale
double TechTreeWnd::LayoutPanel::m_scale = INITIAL_SCALE private
Referenced by CompleteConstruction(), ConvertPtScreenToZoomed(), ConvertPtZoomedToScreen(), DoZoom(), Render(), Scale(), SetScale(), TreeDraggedSlot(), and TreeZoomedSlot().
m_scroll_position_x
double TechTreeWnd::LayoutPanel::m_scroll_position_x = 0.0 private
Referenced by ConvertPtScreenToZoomed(), ConvertPtZoomedToScreen(), DoZoom(), ScrolledSlot(), TreeDragBegin(), TreeDragEnd(), and TreeDraggedSlot().
m_scroll_position_y
double TechTreeWnd::LayoutPanel::m_scroll_position_y = 0.0 private
Referenced by ConvertPtScreenToZoomed(), ConvertPtZoomedToScreen(), DoZoom(), ScrolledSlot(), TreeDragBegin(), TreeDragEnd(), and TreeDraggedSlot().
m_selected_tech_name
std::string TechTreeWnd::LayoutPanel::m_selected_tech_name private
Referenced by Clear(), Layout(), TechTreeWnd::LayoutPanel::TechPanel::LClick(), SelectTech(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
m_tech_statuses_shown
std::set<TechStatus> TechTreeWnd::LayoutPanel::m_tech_statuses_shown private
Referenced by CompleteConstruction(), GetTechStatusesShown(), HideStatus(), Layout(), and ShowStatus().
m_techs
std::map<std::string, std::shared_ptr<TechPanel> > TechTreeWnd::LayoutPanel::m_techs private
Referenced by CenterOnTech(), Clear(), Layout(), SelectTech(), and SetScale().
m_vscroll
std::shared_ptr<GG::Scroll> TechTreeWnd::LayoutPanel::m_vscroll private
Referenced by CenterOnTech(), Clear(), CompleteConstruction(), DoLayout(), Layout(), Render(), ScrolledSlot(), and TreeDraggedSlot().
m_zoom_in_button
std::shared_ptr<GG::Button> TechTreeWnd::LayoutPanel::m_zoom_in_button private
Referenced by CompleteConstruction(), and DoLayout().
m_zoom_out_button
std::shared_ptr<GG::Button> TechTreeWnd::LayoutPanel::m_zoom_out_button private
Referenced by CompleteConstruction(), and DoLayout().
TechDoubleClickedSignal
TechTreeWnd::TechClickSignalType TechTreeWnd::LayoutPanel::TechDoubleClickedSignal mutable
Referenced by Layout().
TechPediaDisplaySignal
TechTreeWnd::TechSignalType TechTreeWnd::LayoutPanel::TechPediaDisplaySignal mutable
Referenced by Layout().
TechSelectedSignal
TechTreeWnd::TechClickSignalType TechTreeWnd::LayoutPanel::TechSelectedSignal mutable
Referenced by SelectTech().
The documentation for this class was generated from the following file:
TechTreeWnd.cpp