FreeOrion: CombatReportWnd::Impl Class Reference
CombatReportWnd::Impl Class Reference
Public Member Functions
Impl (CombatReportWnd &wnd)
void DoLayout ()
GG::Pt GetMinSize () const
void HandleLinkClick (const std::string &link_type, const std::string &data)
void HandleLinkDoubleClick (const std::string &link_type, const std::string &data)
void SetLog (int log_id)
Private Member Functions
void HandleTabChanged (size_t tabnum)
void HandleWindowChanged ()
void UpdateMinSize ()
Private Attributes
GraphicalSummaryWnd * m_graphical
CombatLogWnd * m_log
GG::ScrollPanel * m_log_scroller
GG::Pt m_min_size
GG::TabWnd * m_tabs
CombatReportWnd & m_wnd
Constructor & Destructor Documentation
CombatReportWnd::Impl::Impl (CombatReportWnd & wnd) inline
References ClientUI::CtrlColor(), ClientUI::GetFont(), HandleLinkClick(), HandleLinkDoubleClick(), HandleTabChanged(), HandleWindowChanged(), CombatLogWnd::LinkClickedSignal, CombatLogWnd::LinkDoubleClickedSignal, CombatLogWnd::LinkRightClickedSignal, m_graphical, m_log, m_log_scroller, m_tabs, m_wnd, GraphicalSummaryWnd::MinSizeChangedSignal, CombatLogWnd::SetFont(), UpdateMinSize(), UserString(), and CombatLogWnd::WndChangedSignal.
Member Function Documentation
void CombatReportWnd::Impl::DoLayout () inline
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_tabs, and m_wnd.
Referenced by HandleWindowChanged().
GG::Pt CombatReportWnd::Impl::GetMinSize () const inline
References m_min_size.
void CombatReportWnd::Impl::HandleLinkClick (const std::string & link_type, const std::string & data) inline
References VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, ErrorLogger, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, ClientUI::GetClientUI(), GetPredefinedShipDesign(), TextLinker::GRAPH_TAG, VarText::METER_TYPE_TAG, VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, ClientUI::ZoomToBuilding(), ClientUI::ZoomToBuildingType(), ClientUI::ZoomToCombatLog(), ClientUI::ZoomToEmpire(), ClientUI::ZoomToEncyclopediaEntry(), ClientUI::ZoomToField(), ClientUI::ZoomToFieldType(), ClientUI::ZoomToFleet(), ClientUI::ZoomToMeterTypeArticle(), ClientUI::ZoomToPlanet(), ClientUI::ZoomToShip(), ClientUI::ZoomToShipDesign(), ClientUI::ZoomToShipHull(), ClientUI::ZoomToShipPart(), ClientUI::ZoomToSpecial(), ClientUI::ZoomToSpecies(), ClientUI::ZoomToSystem(), and ClientUI::ZoomToTech().
Referenced by HandleLinkDoubleClick(), and Impl().
void CombatReportWnd::Impl::HandleLinkDoubleClick (const std::string & link_type, const std::string & data) inline
References HandleLinkClick().
Referenced by Impl().
void CombatReportWnd::Impl::HandleTabChanged (size_t tabnum) inline private
References CombatLogWnd::HandleMadeVisible(), and HandleWindowChanged().
Referenced by Impl().
void CombatReportWnd::Impl::HandleWindowChanged () inline private
References DoLayout(), and UpdateMinSize().
Referenced by HandleTabChanged(), and Impl().
void CombatReportWnd::Impl::SetLog (int log_id) inline
References ClientUI::GetFont(), m_graphical, m_log, m_log_scroller, CombatLogWnd::SetFont(), CombatLogWnd::SetLog(), and GraphicalSummaryWnd::SetLog().
void CombatReportWnd::Impl::UpdateMinSize () inline private
References ClientUI::GetFont(), and CUIWnd::INNER_BORDER_ANGLE_OFFSET.
Referenced by HandleWindowChanged(), and Impl().
Member Data Documentation
GraphicalSummaryWnd* CombatReportWnd::Impl::m_graphical private
Referenced by Impl(), and SetLog().
CombatLogWnd* CombatReportWnd::Impl::m_log private
Referenced by Impl(), and SetLog().
GG::ScrollPanel* CombatReportWnd::Impl::m_log_scroller private
Referenced by Impl(), and SetLog().
GG::Pt CombatReportWnd::Impl::m_min_size private
Referenced by GetMinSize().
GG::TabWnd* CombatReportWnd::Impl::m_tabs private
Referenced by DoLayout(), and Impl().
CombatReportWnd& CombatReportWnd::Impl::m_wnd private
Referenced by DoLayout(), and Impl().
The documentation for this class was generated from the following file:
CombatReportWnd.cpp