FreeOrion: FilterDialog Class Reference
FilterDialog Class Reference
Public Member Functions
FilterDialog (std::map< UniverseObjectType, std::set< VIS_DISPLAY >> vis_filters, const Condition::Condition *const condition_filter)
bool ChangesAccepted ()
void CompleteConstruction () override
std::unique_ptr< Condition::Condition > GetConditionFilter ()
std::map< UniverseObjectType, std::set< VIS_DISPLAY > > GetVisibilityFilters () const
Public Member Functions inherited from CUIWnd
CUIWnd (std::string wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (std::string wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
virtual ~CUIWnd ()
Virtual destructor.
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void Close ()
virtual void CloseClicked ()
called when window is closed via the close button
void CompleteConstruction () override
void Flash ()
void Hide () override
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
bool InWindow (const GG::Pt &pt) const override
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
bool Minimized () const
returns true if window is minimized
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void MouseLeave () override
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
void Render () override
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
void SetFlashDuration (int ms)
void Show () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void StopFlash ()
void ToggleMinimized ()
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
void Init ()
performs initialization common to all CUIWnd constructors
virtual void InitBuffers ()
virtual void InitButtons ()
called to create the buttons, withtout positioning them
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void LoadOptions ()
loads options for this window from the OptionsDB
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
virtual void PositionButtons ()
called to position the buttons
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SaveDefaultedOptions ()
sets the default value any options previously determined from calls to SetDefaultedOptions to their current value
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
void SetDefaultedOptions ()
flags options currently at their default values for later use in SaveDefaultedOptions
void SetParent (std::shared_ptr< GG::Wnd > wnd) override
Private Member Functions
void AcceptClicked ()
void CancelClicked ()
void UpdateStateButtonsFromVisFilters ()
void UpdateVisFilterFromVisibilityButton (VIS_DISPLAY vis)
void UpdateVisFiltersFromObjectTypeButton (UniverseObjectType type)
void UpdateVisFiltersFromStateButtons (bool button_checked)
Private Attributes
bool m_accept_changes = false
std::shared_ptr< GG::Button > m_apply_button
std::shared_ptr< GG::Button > m_cancel_button
std::shared_ptr< ConditionWidget > m_condition_widget
std::map< UniverseObjectType, std::map< VIS_DISPLAY, std::shared_ptr< GG::StateButton > > > m_filter_buttons
std::shared_ptr< GG::Layout > m_filters_layout
std::map< UniverseObjectType, std::set< VIS_DISPLAY > > m_vis_filters
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable = false
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable = false
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button
the pin button
bool m_pinable = false
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable = false
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 15
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 9
static const int RESIZE_HASHMARK2_OFFSET = 4
static const int TITLE_OFFSET = 2
Constructor & Destructor Documentation
FilterDialog()
FilterDialog::FilterDialog (std::map< UniverseObjectType, std::set< VIS_DISPLAY >> vis_filters, const Condition::Condition *const condition_filter)
References m_condition_widget.
Member Function Documentation
AcceptClicked()
void FilterDialog::AcceptClicked () private
References m_accept_changes.
Referenced by CompleteConstruction().
CalculatePosition()
GG::Rect FilterDialog::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
CancelClicked()
void FilterDialog::CancelClicked () private
References m_accept_changes.
Referenced by CompleteConstruction().
ChangesAccepted()
bool FilterDialog::ChangesAccepted ()
References m_accept_changes.
CompleteConstruction()
void FilterDialog::CompleteConstruction () override
References AcceptClicked(), CancelClicked(), CUIWnd::CompleteConstruction(), m_apply_button, m_cancel_button, m_condition_widget, m_filter_buttons, m_filters_layout, m_vis_filters, ClientUI::Pts(), CUIWnd::ResetDefaultPosition(), CUIWnd::SaveDefaultedOptions(), CUIWnd::SaveOptions(), UpdateVisFilterFromVisibilityButton(), UpdateVisFiltersFromObjectTypeButton(), UpdateVisFiltersFromStateButtons(), UserString(), and UserStringNop.
GetConditionFilter()
std::unique_ptr< Condition::Condition > FilterDialog::GetConditionFilter ()
References m_condition_widget.
GetVisibilityFilters()
std::map< UniverseObjectType, std::set< VIS_DISPLAY > > FilterDialog::GetVisibilityFilters () const
References m_vis_filters.
UpdateStateButtonsFromVisFilters()
void FilterDialog::UpdateStateButtonsFromVisFilters () private
References m_filter_buttons, and m_vis_filters.
Referenced by UpdateVisFilterFromVisibilityButton(), and UpdateVisFiltersFromObjectTypeButton().
UpdateVisFilterFromVisibilityButton()
void FilterDialog::UpdateVisFilterFromVisibilityButton (VIS_DISPLAY vis) private
References m_filter_buttons, m_vis_filters, and UpdateStateButtonsFromVisFilters().
Referenced by CompleteConstruction().
UpdateVisFiltersFromObjectTypeButton()
void FilterDialog::UpdateVisFiltersFromObjectTypeButton (UniverseObjectType type) private
References m_vis_filters, and UpdateStateButtonsFromVisFilters().
Referenced by CompleteConstruction().
UpdateVisFiltersFromStateButtons()
void FilterDialog::UpdateVisFiltersFromStateButtons (bool button_checked) private
References m_filter_buttons, and m_vis_filters.
Referenced by CompleteConstruction().
Member Data Documentation
m_accept_changes
bool FilterDialog::m_accept_changes = false private
Referenced by AcceptClicked(), CancelClicked(), and ChangesAccepted().
m_apply_button
std::shared_ptr<GG::Button> FilterDialog::m_apply_button private
Referenced by CompleteConstruction().
m_cancel_button
std::shared_ptr<GG::Button> FilterDialog::m_cancel_button private
Referenced by CompleteConstruction().
m_condition_widget
std::shared_ptr<ConditionWidget> FilterDialog::m_condition_widget private
Referenced by CompleteConstruction(), FilterDialog(), and GetConditionFilter().
m_filter_buttons
std::map<UniverseObjectType, std::map<VIS_DISPLAY, std::shared_ptr<GG::StateButton> > > FilterDialog::m_filter_buttons private
Referenced by CompleteConstruction(), UpdateStateButtonsFromVisFilters(), UpdateVisFilterFromVisibilityButton(), and UpdateVisFiltersFromStateButtons().
m_filters_layout
std::shared_ptr<GG::Layout> FilterDialog::m_filters_layout private
Referenced by CompleteConstruction().
m_vis_filters
std::map<UniverseObjectType, std::set<VIS_DISPLAY> > FilterDialog::m_vis_filters private
Referenced by CompleteConstruction(), GetVisibilityFilters(), UpdateStateButtonsFromVisFilters(), UpdateVisFilterFromVisibilityButton(), UpdateVisFiltersFromObjectTypeButton(), and UpdateVisFiltersFromStateButtons().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp