FreeOrion: GameRules Class Reference
GameRules Class Reference
Database of values that control how the game mechanics function.
#include <GameRules.h>
Classes
struct Rule
Public Types
using GameRulesTypeMap = std::unordered_map< std::string, Rule >
enum Type : int {
Type::INVALID = -1, Type::TOGGLE, Type::INT, Type::DOUBLE,
Type::STRING
}
Public Member Functions
template<typename T >
void Add (const std::string &name, const std::string &description, const std::string &category, T default_value, bool engine_interal, const ValidatorBase &validator=Validator< T >())
Adds a rule, optionally with a custom validator.
void Add (Pending::Pending< GameRules > &&future)
Adds rules from the future.
std::unordered_map< std::string, Rule >::const_iterator begin () const
void ClearExternalRules ()
Removes game rules that were added without being specified as engine internal.
bool Empty () const
std::unordered_map< std::string, Rule >::const_iterator end () const
template<typename T >
T Get (const std::string &name) const
const std::string & GetDescription (const std::string &rule_name) const
returns the description string for rule rule_name, or throws std::runtime_error if no such rule exists.
std::map< std::string, std::string > GetRulesAsStrings () const
returns all contained rules as map of name and value string.
Type GetType (const std::string &name) const
std::shared_ptr< const ValidatorBase > GetValidator (const std::string &rule_name) const
returns the validator for rule rule_name, or throws std::runtime_error if no such rule exists.
void ResetToDefaults ()
Resets all rules to default values.
bool RuleExists (const std::string &name) const
bool RuleExists (const std::string &name, Type type) const
bool RuleIsInternal (const std::string &name) const
template<typename T >
void Set (const std::string &name, const T &value)
void SetFromStrings (const std::map< std::string, std::string > &names_values)
Static Public Member Functions
static constexpr Type RuleTypeForType (bool dummy)
static constexpr Type RuleTypeForType (int dummy)
static constexpr Type RuleTypeForType (double dummy)
static Type RuleTypeForType (std::string dummy)
Private Member Functions
void CheckPendingGameRules () const
Assigns any m_pending_rules to m_game_rules.
Private Attributes
GameRulesTypeMap m_game_rules
boost::optional< Pending::Pending< GameRules > > m_pending_rules = boost::none
Future rules being parsed by parser.
Friends
FO_COMMON_API GameRules & GetGameRules ()
returns the single instance of the GameRules class
Detailed Description
Database of values that control how the game mechanics function.
Member Typedef Documentation
GameRulesTypeMap
using GameRules::GameRulesTypeMap = std::unordered_map<std::string, Rule>
Member Enumeration Documentation
Type
enum GameRules::Type : int strong
Enumerator
INVALID
TOGGLE
INT
DOUBLE
STRING
Member Function Documentation
Add() [1/2]
template<typename T > void GameRules::Add (const std::string & name, const std::string & description, const std::string & category, T default_value, bool engine_interal, const ValidatorBase & validator = Validator<T>()) inline
Adds a rule, optionally with a custom validator.
Adds option setup.rules.{RULE_NAME} to override default value and option setup.rules.server-locked.{RULE_NAME} to block rule changes from players
References OptionsDB::Add(), DebugLogger, tag_parser::description, OptionsDB::Get(), GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by anonymous_namespace{Diplomacy.cpp}::AddRules(), anonymous_namespace{CombatEvents.cpp}::AddRules(), anonymous_namespace{System.cpp}::AddRules(), anonymous_namespace{ShipDesign.cpp}::AddRules(), anonymous_namespace{ShipHull.cpp}::AddRules(), anonymous_namespace{Government.cpp}::AddRules(), anonymous_namespace{Tech.cpp}::AddRules(), anonymous_namespace{ProductionQueue.cpp}::AddRules(), anonymous_namespace{BuildingType.cpp}::AddRules(), anonymous_namespace{MultiplayerCommon.cpp}::AddRules(), anonymous_namespace{Universe.cpp}::AddRules(), insert_rule_(), and IApp::StartBackgroundParsing().
Add() [2/2]
void GameRules::Add (Pending::Pending< GameRules > && future)
Adds rules from the future.
References m_pending_rules.
begin()
std::unordered_map< std::string, GameRules::Rule >::const_iterator GameRules::begin () const
References CheckPendingGameRules(), and m_game_rules.
CheckPendingGameRules()
void GameRules::CheckPendingGameRules () const private
Assigns any m_pending_rules to m_game_rules.
References DebugLogger, ErrorLogger, GetRulesAsStrings(), m_game_rules, m_pending_rules, OptionsDB::Option::name, OptionsDB::Option::value, and Pending::WaitForPending().
Referenced by begin(), ClearExternalRules(), Empty(), end(), GetDescription(), GetRulesAsStrings(), GetType(), GetValidator(), ResetToDefaults(), RuleExists(), RuleIsInternal(), and SetFromStrings().
ClearExternalRules()
void GameRules::ClearExternalRules ()
Removes game rules that were added without being specified as engine internal.
References CheckPendingGameRules(), and m_game_rules.
Empty()
bool GameRules::Empty () const
References CheckPendingGameRules(), and m_game_rules.
Referenced by FreeOrionPython::WrapGalaxySetupData().
end()
std::unordered_map< std::string, GameRules::Rule >::const_iterator GameRules::end () const
References CheckPendingGameRules(), and m_game_rules.
Get()
template<typename T > T GameRules::Get (const std::string & name) const inline
References ErrorLogger.
Referenced by ShipDesign::AdjustedAttack(), AutoResolveCombat(), anonymous_namespace{ProductionQueue.cpp}::CalculateProductionPerTurnLimit(), ServerApp::CheckForEmpireElimination(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GameRulesPanel::DoubleRuleWidget(), ServerApp::EliminatePlayer(), ValueRef::ComplexVariable< T >::Eval(), GenerateStarlanes(), anonymous_namespace{ShipHull.cpp}::IncreaseMeter(), anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled(), GameRulesPanel::IntRuleWidget(), operator!=(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), GameRulesPanel::StringRuleWidget(), and anonymous_namespace{Ship.cpp}::WeaponDamageImpl().
GetDescription()
const std::string & GameRules::GetDescription (const std::string & rule_name) const
returns the description string for rule rule_name, or throws std::runtime_error if no such rule exists.
References CheckPendingGameRules(), and m_game_rules.
Referenced by FreeOrionPython::WrapGalaxySetupData().
GetRulesAsStrings()
std::map< std::string, std::string > GameRules::GetRulesAsStrings () const
returns all contained rules as map of name and value string.
References CheckPendingGameRules(), and m_game_rules.
Referenced by CheckPendingGameRules(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), GGHumanClientApp::NewSinglePlayerGame(), Idle::react(), and FreeOrionPython::WrapGalaxySetupData().
GetType()
GameRules::Type GameRules::GetType (const std::string & name) const
References CheckPendingGameRules(), INVALID, and m_game_rules.
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetValidator()
std::shared_ptr< const ValidatorBase > GameRules::GetValidator (const std::string & rule_name) const
returns the validator for rule rule_name, or throws std::runtime_error if no such rule exists.
References CheckPendingGameRules(), and m_game_rules.
Referenced by GameRulesPanel::BoolRuleChanged(), GameRulesPanel::DoubleRuleChanged(), GameRulesPanel::DoubleRuleWidget(), GameRulesPanel::IntRuleChanged(), GameRulesPanel::IntRuleWidget(), GameRulesPanel::StringRuleChanged(), and GameRulesPanel::StringRuleWidget().
ResetToDefaults()
void GameRules::ResetToDefaults ()
Resets all rules to default values.
References CheckPendingGameRules(), and m_game_rules.
Referenced by IntroMenu::IntroMenu(), and SetFromStrings().
RuleExists() [1/2]
bool GameRules::RuleExists (const std::string & name) const
References CheckPendingGameRules(), and m_game_rules.
Referenced by ValueRef::ComplexVariable< T >::Eval(), and FreeOrionPython::WrapGalaxySetupData().
RuleExists() [2/2]
bool GameRules::RuleExists (const std::string & name, Type type) const
References CheckPendingGameRules(), INVALID, m_game_rules, and GameRules::Rule::type.
RuleIsInternal()
bool GameRules::RuleIsInternal (const std::string & name) const
References CheckPendingGameRules(), and m_game_rules.
RuleTypeForType() [1/4]
static constexpr Type GameRules::RuleTypeForType (bool dummy) inline static
RuleTypeForType() [2/4]
static constexpr Type GameRules::RuleTypeForType (int dummy) inline static
RuleTypeForType() [3/4]
static constexpr Type GameRules::RuleTypeForType (double dummy) inline static
RuleTypeForType() [4/4]
static Type GameRules::RuleTypeForType (std::string dummy) inline static
Set()
template<typename T > void GameRules::Set (const std::string & name, const T & value) inline
SetFromStrings()
void GameRules::SetFromStrings (const std::map< std::string, std::string > & names_values)
References CheckPendingGameRules(), DebugLogger, ErrorLogger, InfoLogger, m_game_rules, OptionsDB::Option::name, ResetToDefaults(), and OptionsDB::Option::value.
Referenced by ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), and WaitingForGameStart::react().
Friends And Related Function Documentation
GetGameRules
FO_COMMON_API GameRules& GetGameRules () friend
returns the single instance of the GameRules class
Member Data Documentation
m_game_rules
GameRulesTypeMap GameRules::m_game_rules mutable private
Referenced by begin(), CheckPendingGameRules(), ClearExternalRules(), Empty(), end(), GetDescription(), GetRulesAsStrings(), GetType(), GetValidator(), ResetToDefaults(), RuleExists(), RuleIsInternal(), and SetFromStrings().
m_pending_rules
boost::optional<Pending::Pending<GameRules> > GameRules::m_pending_rules = boost::none mutable private
Future rules being parsed by parser.
mutable so that it can be assigned to m_game_rules when completed.
Referenced by Add(), and CheckPendingGameRules().
The documentation for this class was generated from the following files:
GameRules.h
GameRules.cpp