FreeOrion: anonymous_namespace{Special.cpp}::SpecialManager Class Reference
anonymous_namespace{Special.cpp}::SpecialManager Class Reference
Public Member Functions
SpecialManager ()
unsigned int GetCheckSum () const
const Special * GetSpecial (const std::string &name) const
std::vector< std::string > SpecialNames () const
Private Attributes
std::map< std::string, std::unique_ptr< Special > > m_specials
Constructor & Destructor Documentation
anonymous_namespace{Special.cpp}::SpecialManager::SpecialManager () inline
References ErrorLogger, parse::specials(), and TraceLogger.
Member Function Documentation
unsigned int anonymous_namespace{Special.cpp}::SpecialManager::GetCheckSum () const inline
References CheckSums::CheckSumCombine(), and DebugLogger.
const Special* anonymous_namespace{Special.cpp}::SpecialManager::GetSpecial (const std::string & name) const inline
Referenced by GetSpecial().
std::vector<std::string> anonymous_namespace{Special.cpp}::SpecialManager::SpecialNames () const inline
Referenced by SpecialNames().
Member Data Documentation
std::map<std::string, std::unique_ptr<Special> > anonymous_namespace{Special.cpp}::SpecialManager::m_specials private
The documentation for this class was generated from the following file:
Special.cpp