FreeOrion: BasesListBox::HullAndPartsListBoxRow Class Reference
BasesListBox::HullAndPartsListBoxRow Class Reference
Public Member Functions
HullAndPartsListBoxRow (GG::X w, GG::Y h, const std::string &hull, const std::vector< std::string > &parts)
void CompleteConstruction () override
const std::string & Hull () const
const std::vector< std::string > & Parts () const
Public Member Functions inherited from BasesListBox::BasesListBoxRow
BasesListBoxRow (GG::X w, GG::Y h, const std::string &hull, const std::string &name)
void CompleteConstruction () override
void Render () override
virtual void SetAvailability (const AvailabilityManager::DisplayedAvailabilies &type)
virtual void SetDisplayName (const std::string &name)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Protected Attributes
std::string m_hull_name
std::vector< std::string > m_parts
Constructor & Destructor Documentation
HullAndPartsListBoxRow()
BasesListBox::HullAndPartsListBoxRow::HullAndPartsListBoxRow (GG::X w, GG::Y h, const std::string & hull, const std::vector< std::string > & parts)
Member Function Documentation
CompleteConstruction()
void BasesListBox::HullAndPartsListBoxRow::CompleteConstruction () override
References BasesListBox::BasesListBoxRow::CompleteConstruction(), and anonymous_namespace{DesignWnd.cpp}::HULL_PARTS_ROW_DROP_TYPE_STRING.
Hull()
const std::string& BasesListBox::HullAndPartsListBoxRow::Hull () const inline
Referenced by EmptyHullsListBox::BaseLeftClicked(), EmptyHullsListBox::BaseRightClicked(), EmptyHullsListBox::ChildrenDraggedAwayCore(), and EmptyHullsListBox::QueueItemMoved().
Parts()
const std::vector<std::string>& BasesListBox::HullAndPartsListBoxRow::Parts () const inline
Member Data Documentation
m_hull_name
std::string BasesListBox::HullAndPartsListBoxRow::m_hull_name protected
m_parts
std::vector<std::string> BasesListBox::HullAndPartsListBoxRow::m_parts protected
The documentation for this class was generated from the following file:
DesignWnd.cpp