FreeOrion: Effect::SetOwner Class Reference
Effect::SetOwner Class Reference
#include <Effect.h>
Public Member Functions
SetOwner (std::unique_ptr< ValueRef::ValueRefBase< int >> &&empire_id)
virtual ~SetOwner ()
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRefBase< int > > m_empire_id
Friends
class boost::serialization::access
Detailed Description
Sets empire empire_id as the owner of the target. This has no effect if empire_id was already the owner of the target object.
Constructor & Destructor Documentation
Effect::SetOwner::SetOwner (std::unique_ptr< ValueRef::ValueRefBase< int >> && empire_id) explicit
Effect::SetOwner::~SetOwner () virtual
Member Function Documentation
std::string Effect::SetOwner::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), and m_empire_id.
void Effect::SetOwner::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References anonymous_namespace{Effect.cpp}::CreateNewFleet(), ScriptingContext::effect_target, Universe::EffectDestroy(), GetFleet(), GetSystem(), GetUniverse(), INVALID_OBJECT_ID, and m_empire_id.
unsigned int Effect::SetOwner::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_empire_id, and TraceLogger.
template<class Archive > void Effect::SetOwner::serialize (Archive & ar, const unsigned int version) private
void Effect::SetOwner::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_empire_id.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::unique_ptr<ValueRef::ValueRefBase<int> > Effect::SetOwner::m_empire_id private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp