FreeOrion: BuildDesignatorWnd Class Reference
BuildDesignatorWnd Class Reference
#include <BuildDesignatorWnd.h>
Classes
class BuildSelector
Public Member Functions
void CompleteConstruction () override
Structors
BuildDesignatorWnd (GG::X w, GG::Y h)
Accessors
bool InWindow (const GG::Pt &pt) const override
returns set of BulldType shown in this selector
bool InClient (const GG::Pt &pt) const override
returns set of BulldType shown in this selector
const std::set< BuildType > & GetBuildTypesShown () const
returns set of BulldType shown in this selector
const std::pair< bool, bool > & GetAvailabilitiesShown () const
.first -> available items; .second -> unavailable items
int SelectedPlanetID () const
returns set of BulldType shown in this selector
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void CenterOnBuild (int queue_idx, bool open=false)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void SelectSystem (int system_id)
Programatically sets this Wnd's selected system.
void SelectPlanet (int planet_id)
Programatically sets this Wnd's selected planet.
void SelectDefaultPlanet ()
Attempts to find a planet to select, and if successful, selects that planet.
void Refresh ()
Sets BuildSelector's empire ID to empire of this client, and then calls Update.
void Update ()
Updates sidepanels and refreshes encyclopedia and build selector.
void Reset ()
Sets sidepanel to no system, build location to no planet, refreshes build selector and sets encyclopedia to show nothing, and resets shown types and availabilities to default.
void Clear ()
Resets, and also clears default planet selections for each system.
void ShowType (BuildType type, bool refresh_list=true)
Show or hide indicated types of buildable items.
void ShowAllTypes (bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void HideType (BuildType type, bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void HideAllTypes (bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ToggleType (BuildType type, bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ToggleAllTypes (bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowAvailability (bool available, bool refresh_list=true)
Show or hide indicated availabilities of buildable items.
void HideAvailability (bool available, bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ToggleAvailabilitly (bool available, bool refresh_list=true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowBuildingTypeInEncyclopedia (const std::string &building_type)
Open a pedia entry on the encyclopedia.
void ShowShipDesignInEncyclopedia (int design_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowPlanetInEncyclopedia (int planet_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowTechInEncyclopedia (const std::string &tech_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowPartTypeInEncyclopedia (const std::string &part_type_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowSpeciesInEncyclopedia (const std::string &species_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowEmpireInEncyclopedia (int empire_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowSpecialInEncyclopedia (const std::string &special_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowFieldTypeInEncyclopedia (const std::string &field_type_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void ShowPedia ()
Show or hide the encyclopedia detail panel.
void HidePedia ()
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
void TogglePedia ()
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
bool PediaVisible ()
returns true if the encyclopedia detail panel is visible
Public Attributes
boost::signals2::signal< void(const ProductionQueue::ProductionItem &, int, int, int)> AddBuildToQueueSignal
emitted when the indicated build is indicated by the user
boost::signals2::signal< void(int, int)> BuildQuantityChangedSignal
emitted when the quantity of items in a single build queue item is changed by the user
boost::signals2::signal< void(int)> PlanetSelectedSignal
emitted when the user changes the planet selection from within this Wnd (but not when this Wnd's selected planet is set programatically)
boost::signals2::signal< void(int)> SystemSelectedSignal
emitted when the user selects a system from within this Wnd (but not when this Wnd's system is set programatically)
Static Public Attributes
static const std::string PRODUCTION_ITEM_DROP_TYPE = "Production Item"
Private Member Functions
void BuildItemRequested (const ProductionQueue::ProductionItem &item, int num_to_build, int pos)
int BuildLocation () const
void BuildQuantityChanged (int queue_idx, int quantity)
void InitializeWindows ()
void SetBuild (int queue_idx)
Private Attributes
std::shared_ptr< BuildSelector > m_build_selector
std::shared_ptr< EncyclopediaDetailPanel > m_enc_detail_panel
std::shared_ptr< SidePanel > m_side_panel
std::map< int, int > m_system_default_planets
map from system id to id of planet to auto select when viewing each system
Constructor & Destructor Documentation
BuildDesignatorWnd()
BuildDesignatorWnd::BuildDesignatorWnd (GG::X w, GG::Y h)
Member Function Documentation
BuildItemRequested()
void BuildDesignatorWnd::BuildItemRequested (const ProductionQueue::ProductionItem & item, int num_to_build, int pos) private
References AddBuildToQueueSignal, BuildLocation(), AIInterface::EmpireID(), Empire::EnqueuableItem(), HumanClientApp::GetApp(), and GetEmpire().
Referenced by CompleteConstruction().
BuildLocation()
int BuildDesignatorWnd::BuildLocation () const private
References m_side_panel.
Referenced by BuildItemRequested(), and SelectPlanet().
BuildQuantityChanged()
void BuildDesignatorWnd::BuildQuantityChanged (int queue_idx, int quantity) private
References BuildQuantityChangedSignal.
CenterOnBuild()
void BuildDesignatorWnd::CenterOnBuild (int queue_idx, bool open = false)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References ClientApp::EmpireID(), ErrorLogger, ObjectMap::get(), HumanClientApp::GetApp(), HumanClientApp::GetClientUI(), ClientUI::GetClientUI(), GetEmpire(), ClientUI::GetMapWnd(), Empire::GetProductionQueue(), GetUniverse(), Universe::Objects(), SelectPlanet(), SetBuild(), and ProductionQueue::size().
Clear()
void BuildDesignatorWnd::Clear ()
Resets, and also clears default planet selections for each system.
References INVALID_OBJECT_ID, m_system_default_planets, Reset(), and SidePanel::SetSystem().
Referenced by CompleteConstruction().
CompleteConstruction()
void BuildDesignatorWnd::CompleteConstruction () override
References BT_BUILDING, BT_SHIP, BuildItemRequested(), Clear(), CLOSABLE, HumanClientApp::GetApp(), HidePedia(), InitializeWindows(), m_build_selector, m_enc_detail_panel, m_side_panel, PINABLE, SidePanel::PlanetSelectedSignal, PlanetSelectedSignal, anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_PEDIA_WND_NAME, anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_SELECTOR_WND_NAME, anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_SIDEPANEL_WND_NAME, HumanClientApp::RepositionWindowsSignal, EncyclopediaDetailPanel::SetEncyclopediaArticle(), EncyclopediaDetailPanel::SetItem(), ShowPedia(), SidePanel::SystemSelectedSignal, SystemSelectedSignal, ToggleAvailabilitly(), and ToggleType().
GetAvailabilitiesShown()
const std::pair< bool, bool > & BuildDesignatorWnd::GetAvailabilitiesShown () const
.first -> available items; .second -> unavailable items
References m_build_selector.
GetBuildTypesShown()
const std::set< BuildType > & BuildDesignatorWnd::GetBuildTypesShown () const
returns set of BulldType shown in this selector
References m_build_selector.
HideAllTypes()
void BuildDesignatorWnd::HideAllTypes (bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References BT_BUILDING, BT_SHIP, and m_build_selector.
Referenced by ToggleAllTypes().
HideAvailability()
void BuildDesignatorWnd::HideAvailability (bool available, bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_build_selector.
Referenced by Reset(), and ToggleAvailabilitly().
HidePedia()
void BuildDesignatorWnd::HidePedia ()
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References GetOptionsDB(), m_enc_detail_panel, anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_PEDIA_WND_NAME, and OptionsDB::Set().
Referenced by CompleteConstruction(), and TogglePedia().
HideType()
void BuildDesignatorWnd::HideType (BuildType type, bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References BT_BUILDING, BT_SHIP, BT_STOCKPILE, DebugLogger, and m_build_selector.
Referenced by ToggleType().
InClient()
bool BuildDesignatorWnd::InClient (const GG::Pt & pt) const override
returns set of BulldType shown in this selector
References m_build_selector, m_enc_detail_panel, and m_side_panel.
InitializeWindows()
void BuildDesignatorWnd::InitializeWindows () private
References GetOptionsDB(), m_build_selector, m_enc_detail_panel, m_side_panel, and anonymous_namespace{ClientUI.cpp}::PANEL_HEIGHT().
Referenced by CompleteConstruction().
InWindow()
bool BuildDesignatorWnd::InWindow (const GG::Pt & pt) const override
returns set of BulldType shown in this selector
References m_build_selector, m_enc_detail_panel, and m_side_panel.
PediaVisible()
bool BuildDesignatorWnd::PediaVisible ()
returns true if the encyclopedia detail panel is visible
References m_enc_detail_panel.
Refresh()
void BuildDesignatorWnd::Refresh ()
Sets BuildSelector's empire ID to empire of this client, and then calls Update.
References AIInterface::EmpireID(), HumanClientApp::GetApp(), m_build_selector, and Update().
Reset()
void BuildDesignatorWnd::Reset ()
Sets sidepanel to no system, build location to no planet, refreshes build selector and sets encyclopedia to show nothing, and resets shown types and availabilities to default.
References HideAvailability(), INVALID_OBJECT_ID, m_build_selector, m_enc_detail_panel, SelectSystem(), ShowAllTypes(), and ShowAvailability().
Referenced by Clear().
SelectDefaultPlanet()
void BuildDesignatorWnd::SelectDefaultPlanet ()
Attempts to find a planet to select, and if successful, selects that planet.
References ErrorLogger, ObjectMap::find(), ObjectMap::get(), INVALID_OBJECT_ID, m_side_panel, m_system_default_planets, METER_POPULATION, Objects(), SelectPlanet(), and SidePanel::SystemID().
Referenced by SelectSystem().
SelectedPlanetID()
int BuildDesignatorWnd::SelectedPlanetID () const
returns set of BulldType shown in this selector
References m_side_panel.
SelectPlanet()
void BuildDesignatorWnd::SelectPlanet (int planet_id)
Programatically sets this Wnd's selected planet.
Does not emit a PlanetSelectedSignal.
References BuildLocation(), INVALID_OBJECT_ID, m_build_selector, m_system_default_planets, SidePanel::SelectPlanet(), and SidePanel::SystemID().
Referenced by CenterOnBuild(), and SelectDefaultPlanet().
SelectSystem()
void BuildDesignatorWnd::SelectSystem (int system_id)
Programatically sets this Wnd's selected system.
Does not emit a SystemSelectedSignal.
References INVALID_OBJECT_ID, SelectDefaultPlanet(), SidePanel::SetSystem(), and SidePanel::SystemID().
Referenced by Reset().
SetBuild()
void BuildDesignatorWnd::SetBuild (int queue_idx) private
References BT_BUILDING, BT_SHIP, BT_STOCKPILE, ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), GetBuildingType(), GetEmpire(), Empire::GetProductionQueue(), GetShipDesign(), m_build_selector, m_enc_detail_panel, and ProductionQueue::size().
Referenced by CenterOnBuild().
ShowAllTypes()
void BuildDesignatorWnd::ShowAllTypes (bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References BT_BUILDING, BT_SHIP, and m_build_selector.
Referenced by Reset(), and ToggleAllTypes().
ShowAvailability()
void BuildDesignatorWnd::ShowAvailability (bool available, bool refresh_list = true)
Show or hide indicated availabilities of buildable items.
Available items are those which have been unlocked for this selector's emipre.
References m_build_selector.
Referenced by Reset(), and ToggleAvailabilitly().
ShowBuildingTypeInEncyclopedia()
void BuildDesignatorWnd::ShowBuildingTypeInEncyclopedia (const std::string & building_type)
Open a pedia entry on the encyclopedia.
References m_enc_detail_panel.
ShowEmpireInEncyclopedia()
void BuildDesignatorWnd::ShowEmpireInEncyclopedia (int empire_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowFieldTypeInEncyclopedia()
void BuildDesignatorWnd::ShowFieldTypeInEncyclopedia (const std::string & field_type_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowPartTypeInEncyclopedia()
void BuildDesignatorWnd::ShowPartTypeInEncyclopedia (const std::string & part_type_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowPedia()
void BuildDesignatorWnd::ShowPedia ()
Show or hide the encyclopedia detail panel.
References GetOptionsDB(), m_enc_detail_panel, anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_PEDIA_WND_NAME, and OptionsDB::Set().
Referenced by CompleteConstruction(), and TogglePedia().
ShowPlanetInEncyclopedia()
void BuildDesignatorWnd::ShowPlanetInEncyclopedia (int planet_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowShipDesignInEncyclopedia()
void BuildDesignatorWnd::ShowShipDesignInEncyclopedia (int design_id)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowSpecialInEncyclopedia()
void BuildDesignatorWnd::ShowSpecialInEncyclopedia (const std::string & special_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowSpeciesInEncyclopedia()
void BuildDesignatorWnd::ShowSpeciesInEncyclopedia (const std::string & species_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowTechInEncyclopedia()
void BuildDesignatorWnd::ShowTechInEncyclopedia (const std::string & tech_name)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_enc_detail_panel.
ShowType()
void BuildDesignatorWnd::ShowType (BuildType type, bool refresh_list = true)
Show or hide indicated types of buildable items.
References BT_BUILDING, BT_SHIP, BT_STOCKPILE, ErrorLogger, and m_build_selector.
Referenced by ToggleType().
SizeMove()
void BuildDesignatorWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References m_build_selector, m_enc_detail_panel, and m_side_panel.
ToggleAllTypes()
void BuildDesignatorWnd::ToggleAllTypes (bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References HideAllTypes(), m_build_selector, and ShowAllTypes().
ToggleAvailabilitly()
void BuildDesignatorWnd::ToggleAvailabilitly (bool available, bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References HideAvailability(), m_build_selector, and ShowAvailability().
Referenced by CompleteConstruction().
TogglePedia()
void BuildDesignatorWnd::TogglePedia ()
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References HidePedia(), m_enc_detail_panel, and ShowPedia().
ToggleType()
void BuildDesignatorWnd::ToggleType (BuildType type, bool refresh_list = true)
Centres map wnd on location of item on queue with index queue_idx and displays info about that item in encyclopedia window If open is true, the sidepanel for that planet is opened and it is set as the selected location (so items queued will be built there).
References BT_BUILDING, BT_SHIP, HideType(), m_build_selector, and ShowType().
Referenced by CompleteConstruction().
Update()
void BuildDesignatorWnd::Update ()
Updates sidepanels and refreshes encyclopedia and build selector.
References m_build_selector, m_enc_detail_panel, and SidePanel::Update().
Referenced by Refresh().
Member Data Documentation
AddBuildToQueueSignal
boost::signals2::signal<void (const ProductionQueue::ProductionItem&, int, int, int)> BuildDesignatorWnd::AddBuildToQueueSignal mutable
emitted when the indicated build is indicated by the user
Referenced by BuildItemRequested().
BuildQuantityChangedSignal
boost::signals2::signal<void (int, int)> BuildDesignatorWnd::BuildQuantityChangedSignal mutable
emitted when the quantity of items in a single build queue item is changed by the user
Referenced by BuildQuantityChanged().
m_build_selector
std::shared_ptr<BuildSelector> BuildDesignatorWnd::m_build_selector private
Referenced by CompleteConstruction(), GetAvailabilitiesShown(), GetBuildTypesShown(), HideAllTypes(), HideAvailability(), HideType(), InClient(), InitializeWindows(), InWindow(), Refresh(), Reset(), SelectPlanet(), SetBuild(), ShowAllTypes(), ShowAvailability(), ShowType(), SizeMove(), ToggleAllTypes(), ToggleAvailabilitly(), ToggleType(), and Update().
m_enc_detail_panel
std::shared_ptr<EncyclopediaDetailPanel> BuildDesignatorWnd::m_enc_detail_panel private
Referenced by CompleteConstruction(), HidePedia(), InClient(), InitializeWindows(), InWindow(), PediaVisible(), Reset(), SetBuild(), ShowBuildingTypeInEncyclopedia(), ShowEmpireInEncyclopedia(), ShowFieldTypeInEncyclopedia(), ShowPartTypeInEncyclopedia(), ShowPedia(), ShowPlanetInEncyclopedia(), ShowShipDesignInEncyclopedia(), ShowSpecialInEncyclopedia(), ShowSpeciesInEncyclopedia(), ShowTechInEncyclopedia(), SizeMove(), TogglePedia(), and Update().
m_side_panel
std::shared_ptr<SidePanel> BuildDesignatorWnd::m_side_panel private
Referenced by BuildLocation(), CompleteConstruction(), InClient(), InitializeWindows(), InWindow(), SelectDefaultPlanet(), SelectedPlanetID(), and SizeMove().
m_system_default_planets
std::map<int, int> BuildDesignatorWnd::m_system_default_planets private
map from system id to id of planet to auto select when viewing each system
Referenced by Clear(), SelectDefaultPlanet(), and SelectPlanet().
PlanetSelectedSignal
boost::signals2::signal<void (int)> BuildDesignatorWnd::PlanetSelectedSignal mutable
emitted when the user changes the planet selection from within this Wnd (but not when this Wnd's selected planet is set programatically)
Referenced by CompleteConstruction().
PRODUCTION_ITEM_DROP_TYPE
const std::string BuildDesignatorWnd::PRODUCTION_ITEM_DROP_TYPE = "Production Item" static
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), and anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow().
SystemSelectedSignal
boost::signals2::signal<void (int)> BuildDesignatorWnd::SystemSelectedSignal mutable
emitted when the user selects a system from within this Wnd (but not when this Wnd's system is set programatically)
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
BuildDesignatorWnd.h
BuildDesignatorWnd.cpp