FreeOrion: SDLGUI Class Reference
SDLGUI Class Reference abstract
This is an abstract singleton class that represents the GUI framework of an SDL OpenGL application.
#include <SDLGUI.h>
Public Member Functions
bool FramebuffersAvailable () const
Structors
SDLGUI (int w=1024, int h=768, bool calc_FPS=false, const std::string &app_name="GG", int x=SDL_WINDOWPOS_UNDEFINED, int y=SDL_WINDOWPOS_UNDEFINED, bool fullscreen=false, bool fake_mode_change=false)
virtual ~SDLGUI ()
Accessors
GG::X AppWidth () const override
GG::Y AppHeight () const override
unsigned int Ticks () const override
std::string ClipboardText () const override
virtual std::vector< std::string > GetSupportedResolutions () const override
virtual GG::Pt GetDefaultResolution (int display_id) const override
virtual bool Fullscreen () const final
virtual bool FakeModeChange () const final
Mutators
void ExitApp (int code=0) override
bool SetClipboardText (const std::string &text) override
void Enter2DMode () override
void Exit2DMode () override
void HandleSystemEvents () override
void RenderBegin () override
void RenderEnd () override
void Run () override
bool AppHasMouseFocus () const override
void SetWindowTitle (const std::string &title)
void SetVideoMode (GG::X width, GG::Y height, bool fullscreen, bool fake_mode_change)
Static Public Member Functions
static GG::Pt GetDefaultResolutionStatic (int display_id)
static SDLGUI * GetGUI ()
allows any code to access the gui framework by calling SDLGUI::GetGUI()
static int MaximumPossibleHeight ()
Returns the largest possible height if all displays are aligned vertically.
static int MaximumPossibleWidth ()
Returns the largest possible width if all displays are aligned horizontally.
static int NumVideoDisplaysStatic ()
Protected Member Functions
void FinalCleanup ()
Provides one-time gui cleanup.
void GLInit ()
Allows user to specify OpenGL initialization code; called at the end of SDLInit().
void HandleNonGGEvent (const SDL_Event &event)
event handler for all SDL events that are not GG-related.
virtual void Initialize ()=0
Provides one-time gui initialization.
void ResetFramebuffer ()
Resizes or deletes the framebuffer for fake fullscreen.
void SDLInit ()
Initializes SDL, FE, and SDL OpenGL functionality.
void SDLQuit ()
Cleans up SDL and (if used) FE.
void SetAppSize (const GG::Pt &size)
Static Protected Member Functions
static int MaximumPossibleDimension (bool is_width=true)
Given is_width = true (false) it returns the largest possible window width (height) if all displays are aligned horizontally (vertically).
Private Member Functions
void RelayTextInput (const SDL_TextInputEvent &text, GG::Pt mouse_pos)
Static Private Member Functions
static void SDLMinimalInit ()
Bare minimum SDL video initialization to allow queries to display sizes etc.
Private Attributes
GG::Y m_app_height {768}
GG::X m_app_width {1024}
application width and height (defaults to 1024 x 768)
int m_display_id = 0
bool m_done = false
Set true true when we should exit.
bool m_fake_mode_change = false
std::unique_ptr< Framebuffer > m_framebuffer
Virtual screen for fake fullscreen.
bool m_fullscreen = false
SDL_GLContext m_gl_context = nullptr
The OpenGL context.
GG::X m_initial_x {0}
The initial position of the application window.
GG::Y m_initial_y {0}
SDL_Window * m_window = nullptr
The sdl window.
Detailed Description
This is an abstract singleton class that represents the GUI framework of an SDL OpenGL application.
Usage:
Any application including an object of this class should declare that object as a local variable in main(). The name of this variable will herein be assumed to be "gui". It should be allocated on the stack; if it is created dynamically a leak may occur. SDLGUI is designed so the main() of the application can consist of just the one line "gui();".
To do this, the user needs only to override the Initialize() and FinalCleanup() methods, and ensure that the program does not terminate abnormally; this ensures FinalCleanup() is called when gui's destructor is invoked. ExitApp() can also perform cleanup and terminate the application cleanly.
Most of the member methods of SDLGUI have been declared virtual, to give the user great control when subclassing. The virtual function calls are usually not a performance issue, since none of the methods is called repeatedly, except HandleEvent(); if this is a problem, just create a new function in your subclass and call that from within Run() instead of HandleEvent(). Note that though the bulk of the program execution takes place within Run(), Run() itself is also only called once.
SDLGUI takes a two-tiered approach to event handling. The event pump calls HandleSystemEvents(), which polls for SDL events and handles them by first determining whether the event is GG-related, or some other non-GG event, such as SDL_QUIT, etc. GG events and non-GG events are passed to HandleGGEvent() and HandleNonGGEvent(), respectively. For most uses, there should be no need to override the behavior of HandleSDLEvents(). However, the HandleNonGGEvent() default implementation only responds to SDL_QUIT events, and so should be overridden in most cases.
Constructor & Destructor Documentation
SDLGUI()
SDLGUI::SDLGUI (int w = 1024, int h = 768, bool calc_FPS = false, const std::string & app_name = "GG", int x = SDL_WINDOWPOS_UNDEFINED, int y = SDL_WINDOWPOS_UNDEFINED, bool fullscreen = false, bool fake_mode_change = false) explicit
References SDLInit().
~SDLGUI()
SDLGUI::~SDLGUI () virtual
References SDLQuit().
Member Function Documentation
AppHasMouseFocus()
bool SDLGUI::AppHasMouseFocus () const override
References m_window.
AppHeight()
Y SDLGUI::AppHeight () const override
References m_app_height.
Referenced by InGameMenu::CalculatePosition(), Enter2DMode(), and HumanClientApp::Reinitialize().
AppWidth()
X SDLGUI::AppWidth () const override
References m_app_width.
Referenced by Enter2DMode(), and HumanClientApp::Reinitialize().
ClipboardText()
std::string SDLGUI::ClipboardText () const override
Enter2DMode()
void SDLGUI::Enter2DMode () override
References AppHeight(), AppWidth(), and anonymous_namespace{SDLGUI.cpp}::Enter2DModeImpl().
Referenced by anonymous_namespace{SidePanel.cpp}::RenderPlanet().
Exit2DMode()
void SDLGUI::Exit2DMode () override
Referenced by RenderEnd(), and anonymous_namespace{SidePanel.cpp}::RenderPlanet().
ExitApp()
void SDLGUI::ExitApp (int code = 0) override
Referenced by HumanClientApp::ExitSDL(), and SDLInit().
FakeModeChange()
bool SDLGUI::FakeModeChange () const final virtual
References m_fake_mode_change.
FinalCleanup()
void SDLGUI::FinalCleanup () protected
Provides one-time gui cleanup.
References m_gl_context, and m_window.
Referenced by SDLQuit().
FramebuffersAvailable()
bool SDLGUI::FramebuffersAvailable () const
Referenced by HumanClientApp::HumanClientApp(), and SetVideoMode().
Fullscreen()
bool SDLGUI::Fullscreen () const final virtual
References m_fullscreen.
Referenced by HumanClientApp::HandleWindowMove(), and HumanClientApp::Reinitialize().
GetDefaultResolution()
Pt SDLGUI::GetDefaultResolution (int display_id) const override virtual
References GetDefaultResolutionStatic().
GetDefaultResolutionStatic()
Pt SDLGUI::GetDefaultResolutionStatic (int display_id) static
References SDLMinimalInit().
Referenced by GetDefaultResolution(), and HumanClientApp::GetWindowWidthHeight().
GetGUI()
SDLGUI * SDLGUI::GetGUI () static
allows any code to access the gui framework by calling SDLGUI::GetGUI()
Referenced by OptionsWnd::ResolutionOption().
GetSupportedResolutions()
std::vector< std::string > SDLGUI::GetSupportedResolutions () const override virtual
References m_display_id, and SDLMinimalInit().
GLInit()
void SDLGUI::GLInit () protected
Allows user to specify OpenGL initialization code; called at the end of SDLInit().
References m_app_height, and m_app_width.
Referenced by SDLInit().
HandleNonGGEvent()
void SDLGUI::HandleNonGGEvent (const SDL_Event & event) protected
event handler for all SDL events that are not GG-related.
Referenced by HandleSystemEvents().
HandleSystemEvents()
void SDLGUI::HandleSystemEvents () override
References anonymous_namespace{SDLGUI.cpp}::GetSDLModKeys(), HandleNonGGEvent(), m_app_height, m_app_width, m_fake_mode_change, m_fullscreen, RelayTextInput(), and ResetFramebuffer().
Referenced by HumanClientApp::HandleSystemEvents().
Initialize()
virtual void SDLGUI::Initialize () protected pure virtual
Provides one-time gui initialization.
Implemented in HumanClientApp.
Referenced by Run().
MaximumPossibleDimension()
int SDLGUI::MaximumPossibleDimension (bool is_width = true) static protected
Given is_width = true (false) it returns the largest possible window width (height) if all displays are aligned horizontally (vertically).
Ideally it returns the actual width (height) of a multi-monitor display.
References NumVideoDisplaysStatic().
Referenced by MaximumPossibleHeight(), and MaximumPossibleWidth().
MaximumPossibleHeight()
int SDLGUI::MaximumPossibleHeight () static
Returns the largest possible height if all displays are aligned vertically.
Ideally it reports the actual desktop height using all displays.
References MaximumPossibleDimension().
Referenced by CUIWnd::AddWindowOptions(), HumanClientApp::AddWindowSizeOptionsAfterMainStart(), and CUIWnd::SizeMove().
MaximumPossibleWidth()
int SDLGUI::MaximumPossibleWidth () static
Returns the largest possible width if all displays are aligned horizontally.
Ideally it reports actual desktop width using all displays.
References MaximumPossibleDimension().
Referenced by CUIWnd::AddWindowOptions(), HumanClientApp::AddWindowSizeOptionsAfterMainStart(), and CUIWnd::SizeMove().
NumVideoDisplaysStatic()
int SDLGUI::NumVideoDisplaysStatic () static
References SDLMinimalInit().
Referenced by MaximumPossibleDimension().
RelayTextInput()
void SDLGUI::RelayTextInput (const SDL_TextInputEvent & text, GG::Pt mouse_pos) private
Referenced by HandleSystemEvents().
RenderBegin()
void SDLGUI::RenderBegin () override
References m_app_height, m_app_width, m_fake_mode_change, m_framebuffer, and m_fullscreen.
Referenced by HumanClientApp::RenderBegin().
RenderEnd()
void SDLGUI::RenderEnd () override
References anonymous_namespace{SDLGUI.cpp}::Enter2DModeImpl(), Exit2DMode(), m_fake_mode_change, m_framebuffer, m_fullscreen, and m_window.
ResetFramebuffer()
void SDLGUI::ResetFramebuffer () protected
Resizes or deletes the framebuffer for fake fullscreen.
References m_app_height, m_app_width, m_fake_mode_change, m_framebuffer, and m_fullscreen.
Referenced by HandleSystemEvents(), SDLInit(), and SetVideoMode().
Run()
void SDLGUI::Run () override
References Initialize(), and m_done.
Referenced by mainSetupAndRun().
SDLInit()
void SDLGUI::SDLInit () protected
Initializes SDL, FE, and SDL OpenGL functionality.
References ExitApp(), GLInit(), m_app_height, m_app_width, m_fake_mode_change, m_fullscreen, m_gl_context, m_initial_x, m_initial_y, m_window, ResetFramebuffer(), SDLMinimalInit(), and SetVideoMode().
Referenced by SDLGUI().
SDLMinimalInit()
void SDLGUI::SDLMinimalInit () static private
Bare minimum SDL video initialization to allow queries to display sizes etc.
If called during static initialization, it will cause OSX to crash on exit.
Referenced by GetDefaultResolutionStatic(), GetSupportedResolutions(), NumVideoDisplaysStatic(), and SDLInit().
SDLQuit()
void SDLGUI::SDLQuit () protected
Cleans up SDL and (if used) FE.
References FinalCleanup(), m_app_height, m_app_width, and SetVideoMode().
Referenced by ~SDLGUI().
SetAppSize()
void SDLGUI::SetAppSize (const GG::Pt & size) protected
References m_app_height, and m_app_width.
SetClipboardText()
bool SDLGUI::SetClipboardText (const std::string & text) override
SetVideoMode()
void SDLGUI::SetVideoMode (GG::X width, GG::Y height, bool fullscreen, bool fake_mode_change)
References FramebuffersAvailable(), m_app_height, m_app_width, m_display_id, m_fake_mode_change, m_fullscreen, m_window, ResetFramebuffer(), and anonymous_namespace{SDLGUI.cpp}::SetSDLFullscreenSize().
Referenced by HumanClientApp::Reinitialize(), SDLInit(), and SDLQuit().
SetWindowTitle()
void SDLGUI::SetWindowTitle (const std::string & title)
References m_window.
Ticks()
unsigned int SDLGUI::Ticks () const override
Member Data Documentation
m_app_height
GG::Y SDLGUI::m_app_height {768} private
Referenced by AppHeight(), GLInit(), HandleSystemEvents(), RenderBegin(), ResetFramebuffer(), SDLInit(), SDLQuit(), SetAppSize(), and SetVideoMode().
m_app_width
GG::X SDLGUI::m_app_width {1024} private
application width and height (defaults to 1024 x 768)
Referenced by AppWidth(), GLInit(), HandleSystemEvents(), RenderBegin(), ResetFramebuffer(), SDLInit(), SDLQuit(), SetAppSize(), and SetVideoMode().
m_display_id
int SDLGUI::m_display_id = 0 private
Referenced by GetSupportedResolutions(), and SetVideoMode().
m_done
bool SDLGUI::m_done = false private
Set true true when we should exit.
Referenced by Run().
m_fake_mode_change
bool SDLGUI::m_fake_mode_change = false private
Referenced by FakeModeChange(), HandleSystemEvents(), RenderBegin(), RenderEnd(), ResetFramebuffer(), SDLInit(), and SetVideoMode().
m_framebuffer
std::unique_ptr<Framebuffer> SDLGUI::m_framebuffer private
Virtual screen for fake fullscreen.
Equals nullptr ifi m_fake_mode_change == false.
Referenced by RenderBegin(), RenderEnd(), and ResetFramebuffer().
m_fullscreen
bool SDLGUI::m_fullscreen = false private
Referenced by Fullscreen(), HandleSystemEvents(), RenderBegin(), RenderEnd(), ResetFramebuffer(), SDLInit(), and SetVideoMode().
m_gl_context
SDL_GLContext SDLGUI::m_gl_context = nullptr private
The OpenGL context.
Referenced by FinalCleanup(), and SDLInit().
m_initial_x
GG::X SDLGUI::m_initial_x {0} private
The initial position of the application window.
Referenced by SDLInit().
m_initial_y
GG::Y SDLGUI::m_initial_y {0} private
Referenced by SDLInit().
m_window
SDL_Window* SDLGUI::m_window = nullptr private
The sdl window.
Referenced by AppHasMouseFocus(), FinalCleanup(), RenderEnd(), SDLInit(), SetVideoMode(), and SetWindowTitle().
The documentation for this class was generated from the following files:
SDLGUI.h
SDLGUI.cpp