FreeOrion: Effect::Victory Class Reference
Effect::Victory Class Reference final
Causes the owner empire of the target object to win the game.
#include <Effect.h>
Public Member Functions
Victory (const std::string &reason_string)
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_reason_string
Friends
class boost::serialization::access
Detailed Description
Causes the owner empire of the target object to win the game.
If the target object has multiple owners, nothing is done.
Constructor & Destructor Documentation
Victory()
Effect::Victory::Victory (const std::string & reason_string) explicit
Member Function Documentation
Dump()
std::string Effect::Victory::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), and m_reason_string.
Execute()
void Effect::Victory::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ErrorLogger, GetEmpire(), and m_reason_string.
GetCheckSum()
unsigned int Effect::Victory::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_reason_string, and TraceLogger.
serialize()
template<class Archive > void Effect::Victory::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::Victory::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Effect::EffectBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_reason_string
std::string Effect::Victory::m_reason_string private
Referenced by Dump(), Execute(), and GetCheckSum().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp