FreeOrion: CensusBrowseWnd Class Reference
CensusBrowseWnd Class Reference
A popup tooltop for display when mousing over in-game icons.
#include <CensusBrowseWnd.h>
Public Member Functions
CensusBrowseWnd (std::string title_text, std::map< std::string, float > population_counts, std::map< std::string, float > tag_counts, std::vector< std::string > census_order)
void CompleteConstruction () override
void Render () override
bool WndHasBrowseInfo (const Wnd *wnd, std::size_t mode) const override
Private Member Functions
virtual void InitBuffer ()
void InitRowSizes ()
Private Attributes
GG::GL2DVertexBuffer m_buffer
std::vector< std::string > m_census_order
std::shared_ptr< GG::ListBox > m_list
GG::Pt m_offset
std::map< std::string, float > m_population_counts
std::shared_ptr< GG::Label > m_species_text
std::map< std::string, float > m_tag_counts
std::shared_ptr< GG::ListBox > m_tags_list
std::shared_ptr< GG::Label > m_tags_text
std::shared_ptr< GG::Label > m_title_text
Detailed Description
A popup tooltop for display when mousing over in-game icons.
A title and some detail text.
Constructor & Destructor Documentation
CensusBrowseWnd()
CensusBrowseWnd::CensusBrowseWnd (std::string title_text, std::map< std::string, float > population_counts, std::map< std::string, float > tag_counts, std::vector< std::string > census_order)
Member Function Documentation
CompleteConstruction()
void CensusBrowseWnd::CompleteConstruction () override
References anonymous_namespace{CensusBrowseWnd.cpp}::BrowseTextWidth(), anonymous_namespace{CensusBrowseWnd.cpp}::EDGE_PAD(), ClientUI::GetBoldFont(), InitBuffer(), m_census_order, m_list, m_offset, m_population_counts, m_species_text, m_tag_counts, m_tags_list, m_tags_text, m_title_text, anonymous_namespace{CensusBrowseWnd.cpp}::MeterIconSize(), ClientUI::Pts(), and ClientUI::WndColor().
InitBuffer()
void CensusBrowseWnd::InitBuffer () private virtual
References anonymous_namespace{CensusBrowseWnd.cpp}::IconTextBrowseWndRowHeight(), and m_buffer.
Referenced by CompleteConstruction().
InitRowSizes()
void CensusBrowseWnd::InitRowSizes () private
Render()
void CensusBrowseWnd::Render () override
References m_buffer, m_offset, ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
WndHasBrowseInfo()
bool CensusBrowseWnd::WndHasBrowseInfo (const Wnd * wnd, std::size_t mode) const override
Member Data Documentation
m_buffer
GG::GL2DVertexBuffer CensusBrowseWnd::m_buffer private
Referenced by InitBuffer(), and Render().
m_census_order
std::vector<std::string> CensusBrowseWnd::m_census_order private
Referenced by CompleteConstruction().
m_list
std::shared_ptr<GG::ListBox> CensusBrowseWnd::m_list private
Referenced by CompleteConstruction().
m_offset
GG::Pt CensusBrowseWnd::m_offset private
Referenced by CompleteConstruction(), and Render().
m_population_counts
std::map<std::string, float> CensusBrowseWnd::m_population_counts private
Referenced by CompleteConstruction().
m_species_text
std::shared_ptr<GG::Label> CensusBrowseWnd::m_species_text private
Referenced by CompleteConstruction().
m_tag_counts
std::map<std::string, float> CensusBrowseWnd::m_tag_counts private
Referenced by CompleteConstruction().
m_tags_list
std::shared_ptr<GG::ListBox> CensusBrowseWnd::m_tags_list private
Referenced by CompleteConstruction().
m_tags_text
std::shared_ptr<GG::Label> CensusBrowseWnd::m_tags_text private
Referenced by CompleteConstruction().
m_title_text
std::shared_ptr<GG::Label> CensusBrowseWnd::m_title_text private
Referenced by CompleteConstruction().
The documentation for this class was generated from the following files:
CensusBrowseWnd.h
CensusBrowseWnd.cpp