FreeOrion: Moderator::CreatePlanet Class Reference
Moderator::CreatePlanet Class Reference
#include <ModeratorAction.h>
Public Member Functions
CreatePlanet ()
CreatePlanet (int system_id, PlanetType planet_type, PlanetSize planet_size)
std::string Dump () const override
void Execute () const override
Public Member Functions inherited from Moderator::ModeratorAction
ModeratorAction ()
virtual ~ModeratorAction ()
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
PlanetSize m_planet_size
PlanetType m_planet_type
int m_system_id = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Constructor & Destructor Documentation
CreatePlanet() [1/2]
Moderator::CreatePlanet::CreatePlanet () explicit
CreatePlanet() [2/2]
Moderator::CreatePlanet::CreatePlanet (int system_id, PlanetType planet_type, PlanetSize planet_size)
Member Function Documentation
Dump()
std::string Moderator::CreatePlanet::Dump () const override virtual
Reimplemented from Moderator::ModeratorAction.
References m_planet_size, m_planet_type, m_system_id, and to_string().
Execute()
void Moderator::CreatePlanet::Execute () const override virtual
Reimplemented from Moderator::ModeratorAction.
References ErrorLogger, ObjectMap::get(), GetUniverse(), Universe::InsertNew(), m_planet_size, m_planet_type, m_system_id, and Objects().
serialize()
template<typename Archive > void Moderator::CreatePlanet::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_planet_size
PlanetSize Moderator::CreatePlanet::m_planet_size private
Referenced by Dump(), and Execute().
m_planet_type
PlanetType Moderator::CreatePlanet::m_planet_type private
Referenced by Dump(), and Execute().
m_system_id
int Moderator::CreatePlanet::m_system_id = INVALID_OBJECT_ID private
Referenced by Dump(), and Execute().
The documentation for this class was generated from the following files:
ModeratorAction.h
ModeratorAction.cpp
SerializeModeratorAction.cpp