FreeOrion: ConditionWidget::StringRow Class Reference
ConditionWidget::StringRow Class Reference
Public Member Functions
StringRow (const std::string &text, GG::Y row_height, bool stringtable_lookup=true)
const std::string & Text () const
Private Attributes
std::string m_string
Constructor & Destructor Documentation
ConditionWidget::StringRow::StringRow (const std::string & text, GG::Y row_height, bool stringtable_lookup = true) inline
References parse::detail::label(), and UserString().
Member Function Documentation
const std::string& ConditionWidget::StringRow::Text () const inline
Referenced by ConditionWidget::GetString().
Member Data Documentation
std::string ConditionWidget::StringRow::m_string private
The documentation for this class was generated from the following file:
ObjectListWnd.cpp