FreeOrion: Policy Class Reference
Policy Class Reference
#include <Government.h>
Public Member Functions
Policy (std::string name, std::string description, std::string short_description, std::string category, std::unique_ptr< ValueRef::ValueRef< double >> &&adoption_cost, std::set< std::string > &&prerequisites, std::set< std::string > &&exclusions, std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, std::vector< UnlockableItem > &&unlocked_items, std::string graphic)
float AdoptionCost (int empire_id, const ObjectMap &objects=Objects()) const
const std::string & Category () const
const std::string & Description () const
std::string Dump (unsigned short ntabs=0) const
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
returns the effects that are applied to the discovering empire's capital when this policy is adopted.
const std::set< std::string > & Exclusions () const
*unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
const std::string & Graphic () const
const std::string & Name () const
const std::set< std::string > & Prerequisites () const
const std::string & ShortDescription () const
const std::vector< UnlockableItem > & UnlockedItems () const
Private Member Functions
Policy (const Policy &)=delete
Policy & operator= (const Policy &)=delete
Private Attributes
std::unique_ptr< ValueRef::ValueRef< double > > m_adoption_cost
std::string m_category
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::set< std::string > m_exclusions
std::string m_graphic
std::string m_name
std::set< std::string > m_prerequisites
std::string m_short_description
std::vector< UnlockableItem > m_unlocked_items
Friends
class PolicyManager
Constructor & Destructor Documentation
Policy() [1/2]
Policy::Policy (std::string name, std::string description, std::string short_description, std::string category, std::unique_ptr< ValueRef::ValueRef< double >> && adoption_cost, std::set< std::string > && prerequisites, std::set< std::string > && exclusions, std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, std::vector< UnlockableItem > && unlocked_items, std::string graphic)
References m_adoption_cost, m_effects, and m_name.
Policy() [2/2]
Policy::Policy (const Policy &) private delete
Member Function Documentation
AdoptionCost()
float Policy::AdoptionCost (int empire_id, const ObjectMap & objects = Objects()) const
References ALL_EMPIRES, Empires(), GetGameRules(), EmpireManager::GetSource(), and m_adoption_cost.
Referenced by anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), and FreeOrionPython::WrapEmpire().
Category()
const std::string& Policy::Category () const inline
References Objects().
Referenced by GovernmentWnd::MainPanel::FindEmptySlotForPolicy(), anonymous_namespace{AIWrapper.cpp}::IssueAdoptPolicyOrder(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBackgroundTexture(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), PolicySlotControl::SetPolicy(), and FreeOrionPython::WrapEmpire().
Description()
const std::string& Policy::Description () const inline
Referenced by anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), PolicySlotControl::SetPolicy(), and FreeOrionPython::WrapEmpire().
Dump()
std::string Policy::Dump (unsigned short ntabs = 0) const
References DumpIndent(), m_adoption_cost, m_category, m_description, m_effects, m_exclusions, m_graphic, m_name, m_prerequisites, m_short_description, and m_unlocked_items.
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& Policy::Effects () const inline
returns the effects that are applied to the discovering empire's capital when this policy is adopted.
Referenced by Universe::GetEffectsAndTargets(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag().
Exclusions()
const std::set<std::string>& Policy::Exclusions () const inline
Referenced by anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag().
GetCheckSum()
unsigned int Policy::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_adoption_cost, m_category, m_description, m_effects, m_graphic, m_name, and m_short_description.
Graphic()
const std::string& Policy::Graphic () const inline
Referenced by ClientUI::PolicyIcon().
Name()
const std::string& Policy::Name () const inline
Referenced by GovernmentWnd::MainPanel::ClearPolicy(), GovernmentWnd::CompleteConstruction(), PolicyControl::CompleteConstruction(), anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::DisplayedPolicyAvailability(), GovernmentWnd::MainPanel::FindEmptySlotForPolicy(), GovernmentWnd::MainPanel::Policies(), EncyclopediaDetailPanel::SetItem(), PolicySlotControl::SetPolicy(), GovernmentWnd::MainPanel::SetPolicy(), and FreeOrionPython::WrapEmpire().
operator=()
Policy& Policy::operator= (const Policy &) private delete
Prerequisites()
const std::set<std::string>& Policy::Prerequisites () const inline
Referenced by anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag().
ShortDescription()
const std::string& Policy::ShortDescription () const inline
References Effect::Dump().
Referenced by anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), and FreeOrionPython::WrapEmpire().
UnlockedItems()
const std::vector<UnlockableItem>& Policy::UnlockedItems () const inline
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag().
Friends And Related Function Documentation
PolicyManager
friend class PolicyManager friend
Member Data Documentation
m_adoption_cost
std::unique_ptr<ValueRef::ValueRef<double> > Policy::m_adoption_cost private
Referenced by AdoptionCost(), Dump(), GetCheckSum(), and Policy().
m_category
std::string Policy::m_category private
Referenced by Dump(), and GetCheckSum().
m_description
std::string Policy::m_description private
Referenced by Dump(), and GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > Policy::m_effects private
Referenced by Dump(), GetCheckSum(), and Policy().
m_exclusions
std::set<std::string> Policy::m_exclusions private
Referenced by Dump().
m_graphic
std::string Policy::m_graphic private
Referenced by Dump(), and GetCheckSum().
m_name
std::string Policy::m_name private
Referenced by Dump(), GetCheckSum(), and Policy().
m_prerequisites
std::set<std::string> Policy::m_prerequisites private
Referenced by Dump().
m_short_description
std::string Policy::m_short_description private
Referenced by Dump(), and GetCheckSum().
m_unlocked_items
std::vector<UnlockableItem> Policy::m_unlocked_items private
Referenced by Dump().
The documentation for this class was generated from the following files:
Government.h
Government.cpp