FreeOrion: MapWnd::MapScaleLine Class Reference
MapWnd::MapScaleLine Class Reference
Displays a notched line with number labels to indicate Universe distance on the map.
Public Member Functions
MapScaleLine (GG::X x, GG::Y y, GG::X w, GG::Y h)
virtual ~MapScaleLine ()
void CompleteConstruction () override
GG::X GetLength () const
double GetScaleFactor () const
void Render () override
void Update (double zoom_factor, std::set< int > &fleet_ids, int sel_system_id)
Private Member Functions
void UpdateEnabled ()
Private Attributes
bool m_enabled = false
std::shared_ptr< GG::TextControl > m_label
GG::X m_line_length = GG::X1
double m_scale_factor = 1.0
Detailed Description
Displays a notched line with number labels to indicate Universe distance on the map.
Constructor & Destructor Documentation
MapScaleLine()
MapWnd::MapScaleLine::MapScaleLine (GG::X x, GG::Y y, GG::X w, GG::Y h) inline
References ClientUI::GetFont(), and ClientUI::TextColor().
~MapScaleLine()
virtual MapWnd::MapScaleLine::~MapScaleLine () inline virtual
Member Function Documentation
CompleteConstruction()
void MapWnd::MapScaleLine::CompleteConstruction () inline override
References anonymous_namespace{CUIWnd.cpp}::dummy, GetOptionsDB(), INVALID_OBJECT_ID, and OptionsDB::OptionChangedSignal().
GetLength()
GG::X MapWnd::MapScaleLine::GetLength () const inline
GetScaleFactor()
double MapWnd::MapScaleLine::GetScaleFactor () const inline
Render()
void MapWnd::MapScaleLine::Render () inline override
Update()
void MapWnd::MapScaleLine::Update (double zoom_factor, std::set< int > & fleet_ids, int sel_system_id) inline
References DebugLogger, ObjectMap::find(), FlexibleFormat(), METER_DETECTION, Objects(), to_string(), UserString(), anonymous_namespace{MapWnd.cpp}::ZOOM_MAX, anonymous_namespace{MapWnd.cpp}::ZOOM_MIN, and anonymous_namespace{MapWnd.cpp}::ZOOM_STEP_SIZE.
UpdateEnabled()
void MapWnd::MapScaleLine::UpdateEnabled () inline private
References OptionsDB::Get(), and GetOptionsDB().
Member Data Documentation
m_enabled
bool MapWnd::MapScaleLine::m_enabled = false private
m_label
std::shared_ptr<GG::TextControl> MapWnd::MapScaleLine::m_label private
m_line_length
GG::X MapWnd::MapScaleLine::m_line_length = GG::X1 private
m_scale_factor
double MapWnd::MapScaleLine::m_scale_factor = 1.0 private
The documentation for this class was generated from the following file:
MapWnd.cpp