FreeOrion: anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel Class Reference
anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel Class Reference
Public Member Functions
QueueTechPanel (GG::X x, GG::Y y, GG::X w, const std::string &tech_name, double allocated_rp, int turns_left, double turns_completed, int empire_id, bool paused=false)
void CompleteConstruction () override
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Static Public Member Functions
static GG::Y DefaultHeight ()
Private Member Functions
void Draw (GG::Clr clr, bool fill)
Private Attributes
int m_empire_id
std::shared_ptr< GG::StaticGraphic > m_icon
bool m_in_progress
std::shared_ptr< GG::Label > m_name_text
bool m_paused
std::shared_ptr< MultiTurnProgressBar > m_progress_bar
std::shared_ptr< GG::Label > m_RPs_and_turns_text
const std::string & m_tech_name
int m_total_turns
std::shared_ptr< GG::Label > m_turns_remaining_text
Constructor & Destructor Documentation
QueueTechPanel()
anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel (GG::X x, GG::Y y, GG::X w, const std::string & tech_name, double allocated_rp, int turns_left, double turns_completed, int empire_id, bool paused = false)
References Tech::Category(), ClientUI::CategoryColor(), DefaultHeight(), DoubleToString(), FlexibleFormat(), GetTech(), m_empire_id, m_icon, m_in_progress, m_name_text, m_paused, m_progress_bar, m_RPs_and_turns_text, m_tech_name, m_total_turns, m_turns_remaining_text, anonymous_namespace{ResearchWnd.cpp}::MARGIN, ClientUI::Pts(), ClientUI::ResearchableTechFillColor(), ClientUI::ResearchableTechTextAndBorderColor(), Tech::ResearchCost(), Tech::ResearchTime(), ClientUI::TechIcon(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), and UserString().
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::CompleteConstruction () override
References m_icon, m_name_text, m_progress_bar, m_RPs_and_turns_text, and m_turns_remaining_text.
DefaultHeight()
GG::Y anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::DefaultHeight () static
References ClientUI::Pts().
Referenced by QueueTechPanel(), and SizeMove().
Draw()
void anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::Draw (GG::Clr clr, bool fill) private
References PartlyRoundedRect().
Referenced by Render().
Render()
void anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::Render () override
References Draw(), m_in_progress, ClientUI::ResearchableTechFillColor(), and ClientUI::ResearchableTechTextAndBorderColor().
SizeMove()
void anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DefaultHeight(), m_name_text, m_progress_bar, m_RPs_and_turns_text, m_turns_remaining_text, and ClientUI::Pts().
Member Data Documentation
m_empire_id
int anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_empire_id private
Referenced by QueueTechPanel().
m_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_icon private
Referenced by CompleteConstruction(), and QueueTechPanel().
m_in_progress
bool anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_in_progress private
Referenced by QueueTechPanel(), and Render().
m_name_text
std::shared_ptr<GG::Label> anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_name_text private
Referenced by CompleteConstruction(), QueueTechPanel(), and SizeMove().
m_paused
bool anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_paused private
Referenced by QueueTechPanel().
m_progress_bar
std::shared_ptr<MultiTurnProgressBar> anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_progress_bar private
Referenced by CompleteConstruction(), QueueTechPanel(), and SizeMove().
m_RPs_and_turns_text
std::shared_ptr<GG::Label> anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_RPs_and_turns_text private
Referenced by CompleteConstruction(), QueueTechPanel(), and SizeMove().
m_tech_name
const std::string& anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_tech_name private
Referenced by QueueTechPanel().
m_total_turns
int anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_total_turns private
Referenced by QueueTechPanel().
m_turns_remaining_text
std::shared_ptr<GG::Label> anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::m_turns_remaining_text private
Referenced by CompleteConstruction(), QueueTechPanel(), and SizeMove().
The documentation for this class was generated from the following file:
ResearchWnd.cpp