FreeOrion: anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel Class Reference
anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel Class Reference
Public Member Functions
ProductionItemPanel (GG::X w, GG::Y h, const ProductionQueue::ProductionItem &item, int empire_id, int location_id)
void Render () override
Renders panel background and border.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Member Functions
void DoLayout ()
void Init ()
Private Attributes
std::shared_ptr< GG::Label > m_desc
int m_empire_id = ALL_EMPIRES
std::shared_ptr< GG::StaticGraphic > m_icon
bool m_initialized = false
const ProductionQueue::ProductionItem m_item
int m_location_id = INVALID_OBJECT_ID
std::shared_ptr< GG::Label > m_name
std::shared_ptr< GG::Label > m_time
Constructor & Destructor Documentation
ProductionItemPanel()
anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::ProductionItemPanel (GG::X w, GG::Y h, const ProductionQueue::ProductionItem & item, int empire_id, int location_id) inline
Member Function Documentation
DoLayout()
void anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::DoLayout () inline private
References ClientUI::Pts().
Init()
void anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init () inline private
References ClientUI::BuildingIcon(), ErrorLogger, GetEmpire(), Empire::GetProductionQueue(), Empire::GetResourcePool(), GetShipDesign(), ClientUI::GetTexture(), METER_STOCKPILE, ClientUI::MeterIcon(), ShipDesign::Name(), Empire::ProductionCostAndTime(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionTurns(), RE_INDUSTRY, ClientUI::ShipDesignIcon(), ProductionQueue::StockpileCapacity(), to_string(), and UserString().
Render()
void anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Render () inline override
Renders panel background and border.
References ClientUI::CtrlColor(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
SizeMove()
void anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
m_desc
std::shared_ptr<GG::Label> anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_desc private
m_empire_id
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_empire_id = ALL_EMPIRES private
m_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_icon private
m_initialized
bool anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_initialized = false private
m_item
const ProductionQueue::ProductionItem anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_item private
m_location_id
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_location_id = INVALID_OBJECT_ID private
m_name
std::shared_ptr<GG::Label> anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_name private
m_time
std::shared_ptr<GG::Label> anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::m_time private
The documentation for this class was generated from the following file:
BuildDesignatorWnd.cpp