FreeOrion: Effect::RemoveStarlanes Class Reference
Effect::RemoveStarlanes Class Reference
#include <Effect.h>
Public Member Functions
RemoveStarlanes (Condition::ConditionBase *other_lane_endpoint_condition)
virtual ~RemoveStarlanes ()
std::string Dump () const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
Condition::ConditionBase * m_other_lane_endpoint_condition
Friends
class boost::serialization::access
Detailed Description
Removes starlane(s) between the target system and systems that match other_lane_endpoint_condition
Constructor & Destructor Documentation
Effect::RemoveStarlanes::RemoveStarlanes (Condition::ConditionBase * other_lane_endpoint_condition) explicit
Effect::RemoveStarlanes::~RemoveStarlanes () virtual
References m_other_lane_endpoint_condition.
Member Function Documentation
std::string Effect::RemoveStarlanes::Dump () const override virtual
Implements Effect::EffectBase.
References Condition::ConditionBase::Dump(), DumpIndent(), and m_other_lane_endpoint_condition.
void Effect::RemoveStarlanes::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ErrorLogger, Condition::ConditionBase::Eval(), GetSystem(), and m_other_lane_endpoint_condition.
unsigned int Effect::RemoveStarlanes::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_other_lane_endpoint_condition, and TraceLogger.
template<class Archive > void Effect::RemoveStarlanes::serialize (Archive & ar, const unsigned int version) private
void Effect::RemoveStarlanes::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_other_lane_endpoint_condition, and Condition::ConditionBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
Condition::ConditionBase* Effect::RemoveStarlanes::m_other_lane_endpoint_condition private
Referenced by Dump(), Execute(), GetCheckSum(), SetTopLevelContent(), and ~RemoveStarlanes().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp