FreeOrion: DesignWnd::MainPanel Class Reference
DesignWnd::MainPanel Class Reference
Classes
class I18nString
I18nString stores a string that might be in the stringtable.
Public Member Functions
Structors
MainPanel (const std::string &config_name)
void CompleteConstruction () override
Accessors
boost::optional< const ShipDesign * > EditingCurrentDesign () const
If editing a current design return a ShipDesign* otherwise boost::none.
boost::optional< const ShipDesign * > EditingSavedDesign () const
If editing a saved design return a ShipDesign* otherwise boost::none.
const std::vector< std::string > Parts () const
returns vector of names of parts in slots of current shown design. empty slots are represented with empty stri
const std::string & Hull () const
returns name of hull of current shown design
bool IsDesignNameValid () const
checks design name validity
std::pair< I18nString, I18nString > ValidatedNameAndDescription () const
Return a validated name and description.
const I18nString ValidatedDesignName () const
returns name currently entered for design or valid default
const I18nString DesignDescription () const
returns description currently entered for design
std::shared_ptr< const ShipDesign > GetIncompleteDesign () const
Returns a pointer to the design currently being modified (if any).
boost::optional< int > GetReplacedDesignID () const
returns ID of completed design selected to be replaced.
boost::optional< const ShipDesign * > CurrentDesignIsRegistered ()
If a design with the same hull and parts is registered with the empire then return the design, otherwise return boost::none.
Mutators
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void Sanitize ()
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void SetPart (const std::string &part_name, unsigned int slot)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void SetPart (const PartType *part, unsigned int slot, bool emit_signal=false, bool change_all_similar_parts=false)
Sets the part in slot to part and emits and signal if requested.
void SetParts (const std::vector< std::string > &parts)
puts specified parts in slots. attempts to put each part into the slot corresponding to its place in the passed vector. if a part cannot be placed, it is ignored. more parts than there are slots available are ignored, and slots for which there are insufficient parts in the passed vector are unmodified
void AddPart (const PartType *part)
Attempts to add the specified part to the design, if possible.
bool CanPartBeAdded (const PartType *part)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void ClearParts ()
removes all parts from design. hull is not altered
void ClearPart (const std::string &part_name)
Remove parts called part_name.
void SetHull (const std::string &hull_name, bool signal=true)
Set the design hull hull_name, displaying appropriate background image and creating appropriate SlotControls.
void SetHull (const HullType *hull, bool signal=true)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void SetDesign (const ShipDesign *ship_design)
sets the displayed design by setting the appropriate hull and parts
void SetDesign (int design_id)
sets the displayed design by setting the appropriate hull and parts
void SetDesign (const boost::uuids::uuid &uuid)
SetDesign to the design with uuid from the SavedDesignManager.
void SetDesignComponents (const std::string &hull, const std::vector< std::string > &parts)
sets design hull and parts to those specified
void SetDesignComponents (const std::string &hull, const std::vector< std::string > &parts, const std::string &name, const std::string &desc)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void DesignChanged ()
Responds to the design being changed.
std::pair< int, boost::uuids::uuid > AddDesign ()
Add a design.
void ReplaceDesign ()
Replace an existing design.
void ToggleDescriptionEditor ()
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
void HighlightSlotType (std::vector< ShipSlotType > &slot_types)
renders slots of the indicated types differently, perhaps to indicate that that those slots can be drop targets for a particular part?
void HandleBaseTypeChange (const DesignWnd::BaseSelector::BaseSelectorTab base_type)
Track changes in base type.
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Flash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void StopFlash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetFlashDuration (int ms)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void(int)> CompleteDesignClickedSignal
emitted when the user clicks on the background of this main panel and a completed design is showing
boost::signals2::signal< void()> DesignChangedSignal
emitted when the design is changed (by adding or removing parts, not name or description changes)
boost::signals2::signal< void()> DesignConfirmedSignal
emitted when the user clicks the m_confirm_button to add the new design to the player's empire
boost::signals2::signal< void()> DesignNameChangedSignal
emitted when the design name is changed
boost::signals2::signal< void()> DesignReplacedSignal
emitted when the user clicks the m_replace_button to replace the currently selected design with the new design in the player's empire
boost::signals2::signal< void(const HullType *)> HullTypeClickedSignal
boost::signals2::signal< void(const PartType *, GG::Flags< GG::ModKey >)> PartTypeClickedSignal
propagates signals from contained SlotControls that signal that a part has been clicked
Protected Member Functions
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Private Member Functions
bool AddPartEmptySlot (const PartType *part, int slot_number)
Adds part to slot number.
bool AddPartWithSwapping (const PartType *part, std::pair< int, int > swap_and_empty_slot)
Swaps part in slot # pair.first to slot # pair.second, adds given part to slot # pair.first.
void DesignNameChanged ()
responds to the design name being changed
void DesignNameEditedSlot (const std::string &new_name)
triggered when m_design_name's AfterTextChangedSignal fires. Used for basic name validation.
void DoLayout ()
positions buttons, text entry boxes and SlotControls
int FindEmptySlotForPart (const PartType *part)
Determines if a part can be added to any empty slot, returns the slot index if possible, otherwise -1.
std::pair< int, int > FindSlotForPartWithSwapping (const PartType *part)
Determines if a part can be added to a slot with swapping, returns a pair containing the slot to swap and an empty slot, otherwise a pair with -1 This function only tries to find a way to add the given part by swapping a part already in a slot to an empty slot If theres an open slot that the given part could go into but all of the occupied slots contain parts that can't swap into the open slot This function will indicate that it could not add the part, even though adding the part is possible.
std::string GetCleanDesignDump (const ShipDesign *ship_design)
similar to ship design dump but without 'lookup_strings', icon and model entries
void Populate ()
creates and places SlotControls for current hull
void RefreshIncompleteDesign () const
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_background_image = nullptr
std::shared_ptr< GG::Button > m_clear_button = nullptr
std::shared_ptr< GG::Button > m_confirm_button = nullptr
std::shared_ptr< GG::MultiEdit > m_design_description_edit = nullptr
std::shared_ptr< GG::StateButton > m_design_description_toggle = nullptr
std::shared_ptr< GG::Edit > m_design_name = nullptr
std::shared_ptr< GG::Label > m_design_name_label = nullptr
bool m_disabled_by_name = false
bool m_disabled_by_part_conflict = false
boost::signals2::connection m_empire_designs_changed_signal
const HullType * m_hull = nullptr
std::shared_ptr< ShipDesign > m_incomplete_design = nullptr
std::shared_ptr< GG::Button > m_replace_button = nullptr
boost::optional< int > m_replaced_design_id = boost::none
boost::optional< boost::uuids::uuid > m_replaced_design_uuid = boost::none
std::vector< std::shared_ptr< SlotControl > > m_slots
DesignWnd::BaseSelector::BaseSelectorTab m_type_to_create = DesignWnd::BaseSelector::BaseSelectorTab::Current
Whether to add new designs to current or saved designs This tracks the last relevant selected tab in the base selector.
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable = false
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable = false
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button
the pin button
bool m_pinable = false
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable = false
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 15
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 9
static const int RESIZE_HASHMARK2_OFFSET = 4
static const int TITLE_OFFSET = 2
Constructor & Destructor Documentation
MainPanel()
DesignWnd::MainPanel::MainPanel (const std::string & config_name)
Member Function Documentation
AcceptDrops()
void DesignWnd::MainPanel::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References ErrorLogger, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), GetShipDesign(), SetDesign(), and SetDesignComponents().
AddDesign()
std::pair< int, boost::uuids::uuid > DesignWnd::MainPanel::AddDesign ()
Add a design.
References CurrentTurn(), DebugLogger, DesignChangedSignal, DesignDescription(), ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), ClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetEmpire(), GetHullType(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), Hull(), INVALID_DESIGN_ID, OrderSet::IssueOrder(), m_type_to_create, ClientApp::Orders(), Parts(), DesignWnd::BaseSelector::Saved, and ValidatedDesignName().
Referenced by CompleteConstruction(), and ReplaceDesign().
AddPart()
void DesignWnd::MainPanel::AddPart (const PartType * part)
Attempts to add the specified part to the design, if possible.
will first attempt to add part to an empty slot of the appropriate type, and if no appropriate slots are available, may or may not move other parts around within the design to open up a compatible slot in which to add this part (and then add it). may also do nothing.
References AddPartEmptySlot(), AddPartWithSwapping(), DebugLogger, FindEmptySlotForPart(), FindSlotForPartWithSwapping(), and PartType::Name().
Referenced by DesignWnd::CompleteConstruction().
AddPartEmptySlot()
bool DesignWnd::MainPanel::AddPartEmptySlot (const PartType * part, int slot_number) private
Adds part to slot number.
References DesignChangedSignal, and SetPart().
Referenced by AddPart().
AddPartWithSwapping()
bool DesignWnd::MainPanel::AddPartWithSwapping (const PartType * part, std::pair< int, int > swap_and_empty_slot) private
Swaps part in slot # pair.first to slot # pair.second, adds given part to slot # pair.first.
References DesignChangedSignal, m_slots, and SetPart().
Referenced by AddPart().
CanPartBeAdded()
bool DesignWnd::MainPanel::CanPartBeAdded (const PartType * part)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References FindEmptySlotForPart(), and FindSlotForPartWithSwapping().
ClearPart()
void DesignWnd::MainPanel::ClearPart (const std::string & part_name)
Remove parts called part_name.
References DesignChangedSignal, m_slots, and PartType::Name().
Referenced by DesignWnd::CompleteConstruction().
ClearParts()
void DesignWnd::MainPanel::ClearParts ()
removes all parts from design. hull is not altered
References DesignChangedSignal, and m_slots.
Referenced by CompleteConstruction().
CompleteConstruction()
void DesignWnd::MainPanel::CompleteConstruction () override
References AddDesign(), ClearParts(), CUIWnd::CompleteConstruction(), DesignChanged(), DesignChangedSignal, DesignConfirmedSignal, DesignNameEditedSlot(), DesignReplacedSignal, DoLayout(), GetOptionsDB(), m_clear_button, m_confirm_button, m_design_description_edit, m_design_description_toggle, m_design_name, m_design_name_label, m_replace_button, ReplaceDesign(), CUIWnd::SaveDefaultedOptions(), ToggleDescriptionEditor(), and UserString().
CurrentDesignIsRegistered()
boost::optional< const ShipDesign * > DesignWnd::MainPanel::CurrentDesignIsRegistered ()
If a design with the same hull and parts is registered with the empire then return the design, otherwise return boost::none.
References ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), GetEmpire(), GetIncompleteDesign(), and GetShipDesign().
Referenced by DesignChanged(), and ReplaceDesign().
DesignChanged()
void DesignWnd::MainPanel::DesignChanged ()
Responds to the design being changed.
References ALL_EMPIRES, DesignWnd::BaseSelector::Current, CurrentDesignIsRegistered(), DesignWnd::MainPanel::I18nString::DisplayText(), EditingCurrentDesign(), EditingSavedDesign(), ClientApp::EmpireID(), PartType::Exclusions(), HullType::Exclusions(), FlexibleFormat(), HumanClientApp::GetApp(), GetIncompleteDesign(), GetPartType(), IsDesignNameValid(), m_confirm_button, m_disabled_by_name, m_disabled_by_part_conflict, m_hull, m_replace_button, m_type_to_create, HullType::Name(), Parts(), DesignWnd::BaseSelector::Saved, UserString(), ValidatedDesignName(), and ShipDesign::ValidDesign().
Referenced by DesignWnd::CompleteConstruction(), CompleteConstruction(), and HandleBaseTypeChange().
DesignDescription()
const DesignWnd::MainPanel::I18nString DesignWnd::MainPanel::DesignDescription () const
returns description currently entered for design
References ValidatedNameAndDescription().
Referenced by AddDesign().
DesignNameChanged()
void DesignWnd::MainPanel::DesignNameChanged () private
responds to the design name being changed
References DesignChangedSignal, DesignNameChangedSignal, GetOptionsDB(), IsDesignNameValid(), m_confirm_button, m_disabled_by_name, and RefreshIncompleteDesign().
Referenced by DesignNameEditedSlot().
DesignNameEditedSlot()
void DesignWnd::MainPanel::DesignNameEditedSlot (const std::string & new_name) private
triggered when m_design_name's AfterTextChangedSignal fires. Used for basic name validation.
References DesignNameChanged().
Referenced by CompleteConstruction().
DoLayout()
void DesignWnd::MainPanel::DoLayout () private
positions buttons, text entry boxes and SlotControls
References CUIWnd::ClientLowerRight(), CUIWnd::ClientUpperLeft(), m_background_image, m_clear_button, m_confirm_button, m_design_description_edit, m_design_description_toggle, m_design_name, m_design_name_label, m_replace_button, m_slots, anonymous_namespace{DesignWnd.cpp}::PAD(), and ClientUI::Pts().
Referenced by CompleteConstruction(), SetHull(), and SizeMove().
DropsAcceptable()
void DesignWnd::MainPanel::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const override protected
References if().
EditingCurrentDesign()
boost::optional< const ShipDesign * > DesignWnd::MainPanel::EditingCurrentDesign () const
If editing a current design return a ShipDesign* otherwise boost::none.
References anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), GetShipDesign(), and m_replaced_design_id.
Referenced by DesignChanged(), and ReplaceDesign().
EditingSavedDesign()
boost::optional< const ShipDesign * > DesignWnd::MainPanel::EditingSavedDesign () const
If editing a saved design return a ShipDesign* otherwise boost::none.
References anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and m_replaced_design_uuid.
Referenced by DesignChanged(), ReplaceDesign(), and ValidatedNameAndDescription().
FindEmptySlotForPart()
int DesignWnd::MainPanel::FindEmptySlotForPart (const PartType * part) private
Determines if a part can be added to any empty slot, returns the slot index if possible, otherwise -1.
References PartType::CanMountInSlotType(), PartType::Class(), m_slots, PartType::Name(), and PC_FIGHTER_HANGAR.
Referenced by AddPart(), and CanPartBeAdded().
FindSlotForPartWithSwapping()
std::pair< int, int > DesignWnd::MainPanel::FindSlotForPartWithSwapping (const PartType * part) private
Determines if a part can be added to a slot with swapping, returns a pair containing the slot to swap and an empty slot, otherwise a pair with -1 This function only tries to find a way to add the given part by swapping a part already in a slot to an empty slot If theres an open slot that the given part could go into but all of the occupied slots contain parts that can't swap into the open slot This function will indicate that it could not add the part, even though adding the part is possible.
References PartType::CanMountInSlotType(), PartType::Class(), m_slots, PartType::Name(), and PC_FIGHTER_HANGAR.
Referenced by AddPart(), and CanPartBeAdded().
GetCleanDesignDump()
std::string DesignWnd::MainPanel::GetCleanDesignDump (const ShipDesign * ship_design) private
similar to ship design dump but without 'lookup_strings', icon and model entries
References ShipDesign::Hull(), ShipDesign::Name(), and ShipDesign::Parts().
GetIncompleteDesign()
std::shared_ptr< const ShipDesign > DesignWnd::MainPanel::GetIncompleteDesign () const
Returns a pointer to the design currently being modified (if any).
May return an empty pointer if not currently modifying a design.
References m_incomplete_design, and RefreshIncompleteDesign().
Referenced by CurrentDesignIsRegistered(), and DesignChanged().
GetReplacedDesignID()
boost::optional< int > DesignWnd::MainPanel::GetReplacedDesignID () const
returns ID of completed design selected to be replaced.
References m_replaced_design_id.
HandleBaseTypeChange()
void DesignWnd::MainPanel::HandleBaseTypeChange (const DesignWnd::BaseSelector::BaseSelectorTab base_type)
Track changes in base type.
References DesignWnd::BaseSelector::Current, DesignChanged(), m_type_to_create, and DesignWnd::BaseSelector::Saved.
Referenced by DesignWnd::CompleteConstruction().
HighlightSlotType()
void DesignWnd::MainPanel::HighlightSlotType (std::vector< ShipSlotType > & slot_types)
renders slots of the indicated types differently, perhaps to indicate that that those slots can be drop targets for a particular part?
References m_slots.
Hull()
const std::string & DesignWnd::MainPanel::Hull () const
returns name of hull of current shown design
References anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING, m_hull, and HullType::Name().
Referenced by AddDesign(), and RefreshIncompleteDesign().
IsDesignNameValid()
bool DesignWnd::MainPanel::IsDesignNameValid () const
checks design name validity
References m_design_name.
Referenced by DesignChanged(), DesignNameChanged(), and ValidatedNameAndDescription().
LClick()
void DesignWnd::MainPanel::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References HullTypeClickedSignal, CUIWnd::LClick(), and m_hull.
Parts()
const std::vector< std::string > DesignWnd::MainPanel::Parts () const
returns vector of names of parts in slots of current shown design. empty slots are represented with empty stri
References m_slots, and PartType::Name().
Referenced by AddDesign(), DesignChanged(), and RefreshIncompleteDesign().
Populate()
void DesignWnd::MainPanel::Populate () private
creates and places SlotControls for current hull
References m_hull, m_slots, PartTypeClickedSignal, SetPart(), HullType::Slots(), HullType::Slot::type, HullType::Slot::x, and HullType::Slot::y.
Referenced by SetHull().
RefreshIncompleteDesign()
void DesignWnd::MainPanel::RefreshIncompleteDesign () const private
References CurrentTurn(), ClientApp::EmpireID(), anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING, ErrorLogger, ClientApp::GetApp(), Hull(), HullType::Icon(), m_hull, m_incomplete_design, Parts(), and ValidatedNameAndDescription().
Referenced by DesignNameChanged(), and GetIncompleteDesign().
ReplaceDesign()
void DesignWnd::MainPanel::ReplaceDesign ()
Replace an existing design.
References AddDesign(), DesignWnd::BaseSelector::Current, CurrentDesignIsRegistered(), DebugLogger, DesignChangedSignal, EditingCurrentDesign(), EditingSavedDesign(), ClientApp::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), INVALID_DESIGN_ID, OrderSet::IssueOrder(), m_type_to_create, ClientApp::Orders(), DesignWnd::BaseSelector::Saved, and SetDesign().
Referenced by CompleteConstruction().
Sanitize()
void DesignWnd::MainPanel::Sanitize ()
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References m_design_description_edit, m_design_name, m_empire_designs_changed_signal, SetHull(), and UserString().
SetDesign() [1/3]
void DesignWnd::MainPanel::SetDesign (const ShipDesign * ship_design)
sets the displayed design by setting the appropriate hull and parts
References ShipDesign::Description(), DesignChangedSignal, anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), ShipDesign::Hull(), ShipDesign::ID(), ShipDesign::IsMonster(), m_design_description_edit, m_design_name, m_incomplete_design, m_replaced_design_id, m_replaced_design_uuid, ShipDesign::Name(), ShipDesign::Parts(), SetHull(), SetParts(), and ShipDesign::UUID().
Referenced by AcceptDrops(), DesignWnd::CompleteConstruction(), ReplaceDesign(), and SetDesign().
SetDesign() [2/3]
void DesignWnd::MainPanel::SetDesign (int design_id)
sets the displayed design by setting the appropriate hull and parts
References GetShipDesign(), and SetDesign().
SetDesign() [3/3]
void DesignWnd::MainPanel::SetDesign (const boost::uuids::uuid & uuid)
SetDesign to the design with uuid from the SavedDesignManager.
References anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and SetDesign().
SetDesignComponents() [1/2]
void DesignWnd::MainPanel::SetDesignComponents (const std::string & hull, const std::vector< std::string > & parts)
sets design hull and parts to those specified
References m_replaced_design_id, m_replaced_design_uuid, SetHull(), and SetParts().
Referenced by AcceptDrops(), DesignWnd::CompleteConstruction(), and SetDesignComponents().
SetDesignComponents() [2/2]
void DesignWnd::MainPanel::SetDesignComponents (const std::string & hull, const std::vector< std::string > & parts, const std::string & name, const std::string & desc)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References m_design_description_edit, m_design_name, and SetDesignComponents().
SetHull() [1/2]
void DesignWnd::MainPanel::SetHull (const std::string & hull_name, bool signal = true)
Set the design hull hull_name, displaying appropriate background image and creating appropriate SlotControls.
If signal is false do not emit the the DesignChangedSignal().
References GetHullType().
Referenced by Sanitize(), SetDesign(), and SetDesignComponents().
SetHull() [2/2]
void DesignWnd::MainPanel::SetHull (const HullType * hull, bool signal = true)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References DesignChangedSignal, DoLayout(), ClientUI::HullTexture(), m_background_image, m_hull, HullType::Name(), and Populate().
SetPart() [1/2]
void DesignWnd::MainPanel::SetPart (const std::string & part_name, unsigned int slot)
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References GetPartType().
Referenced by AddPartEmptySlot(), AddPartWithSwapping(), Populate(), and SetParts().
SetPart() [2/2]
void DesignWnd::MainPanel::SetPart (const PartType * part, unsigned int slot, bool emit_signal = false, bool change_all_similar_parts = false)
Sets the part in slot to part and emits and signal if requested.
Changes all similar parts if change_all_similar_parts.
References PartType::CanMountInSlotType(), DesignChangedSignal, ErrorLogger, and m_slots.
SetParts()
void DesignWnd::MainPanel::SetParts (const std::vector< std::string > & parts)
puts specified parts in slots. attempts to put each part into the slot corresponding to its place in the passed vector. if a part cannot be placed, it is ignored. more parts than there are slots available are ignored, and slots for which there are insufficient parts in the passed vector are unmodified
References DesignChangedSignal, m_slots, and SetPart().
Referenced by SetDesign(), and SetDesignComponents().
SizeMove()
void DesignWnd::MainPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References DoLayout(), and CUIWnd::SizeMove().
ToggleDescriptionEditor()
void DesignWnd::MainPanel::ToggleDescriptionEditor ()
puts specified part in specified slot. does nothing if slot is out of range of available slots for current hull
References m_design_description_edit, and m_design_description_toggle.
Referenced by CompleteConstruction().
ValidatedDesignName()
const DesignWnd::MainPanel::I18nString DesignWnd::MainPanel::ValidatedDesignName () const
returns name currently entered for design or valid default
References ValidatedNameAndDescription().
Referenced by AddDesign(), and DesignChanged().
ValidatedNameAndDescription()
std::pair< DesignWnd::MainPanel::I18nString, DesignWnd::MainPanel::I18nString > DesignWnd::MainPanel::ValidatedNameAndDescription () const
Return a validated name and description.
If the design is a saved design then either both or neither will be stringtable values.
References EditingSavedDesign(), IsDesignNameValid(), m_design_description_edit, m_design_name, UserString(), and UserStringExists().
Referenced by DesignDescription(), RefreshIncompleteDesign(), and ValidatedDesignName().
Member Data Documentation
CompleteDesignClickedSignal
boost::signals2::signal<void (int)> DesignWnd::MainPanel::CompleteDesignClickedSignal mutable
emitted when the user clicks on the background of this main panel and a completed design is showing
DesignChangedSignal
boost::signals2::signal<void ()> DesignWnd::MainPanel::DesignChangedSignal mutable
emitted when the design is changed (by adding or removing parts, not name or description changes)
Referenced by AddDesign(), AddPartEmptySlot(), AddPartWithSwapping(), ClearPart(), ClearParts(), CompleteConstruction(), DesignNameChanged(), ReplaceDesign(), SetDesign(), SetHull(), SetPart(), and SetParts().
DesignConfirmedSignal
boost::signals2::signal<void ()> DesignWnd::MainPanel::DesignConfirmedSignal mutable
emitted when the user clicks the m_confirm_button to add the new design to the player's empire
Referenced by CompleteConstruction().
DesignNameChangedSignal
boost::signals2::signal<void ()> DesignWnd::MainPanel::DesignNameChangedSignal mutable
emitted when the design name is changed
Referenced by DesignNameChanged().
DesignReplacedSignal
boost::signals2::signal<void ()> DesignWnd::MainPanel::DesignReplacedSignal mutable
emitted when the user clicks the m_replace_button to replace the currently selected design with the new design in the player's empire
Referenced by CompleteConstruction().
HullTypeClickedSignal
boost::signals2::signal<void (const HullType*)> DesignWnd::MainPanel::HullTypeClickedSignal mutable
Referenced by LClick().
m_background_image
std::shared_ptr<GG::StaticGraphic> DesignWnd::MainPanel::m_background_image = nullptr private
Referenced by DoLayout(), and SetHull().
m_clear_button
std::shared_ptr<GG::Button> DesignWnd::MainPanel::m_clear_button = nullptr private
Referenced by CompleteConstruction(), and DoLayout().
m_confirm_button
std::shared_ptr<GG::Button> DesignWnd::MainPanel::m_confirm_button = nullptr private
Referenced by CompleteConstruction(), DesignChanged(), DesignNameChanged(), and DoLayout().
m_design_description_edit
std::shared_ptr<GG::MultiEdit> DesignWnd::MainPanel::m_design_description_edit = nullptr private
Referenced by CompleteConstruction(), DoLayout(), Sanitize(), SetDesign(), SetDesignComponents(), ToggleDescriptionEditor(), and ValidatedNameAndDescription().
m_design_description_toggle
std::shared_ptr<GG::StateButton> DesignWnd::MainPanel::m_design_description_toggle = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and ToggleDescriptionEditor().
m_design_name
std::shared_ptr<GG::Edit> DesignWnd::MainPanel::m_design_name = nullptr private
Referenced by CompleteConstruction(), DoLayout(), IsDesignNameValid(), Sanitize(), SetDesign(), SetDesignComponents(), and ValidatedNameAndDescription().
m_design_name_label
std::shared_ptr<GG::Label> DesignWnd::MainPanel::m_design_name_label = nullptr private
Referenced by CompleteConstruction(), and DoLayout().
m_disabled_by_name
bool DesignWnd::MainPanel::m_disabled_by_name = false private
Referenced by DesignChanged(), and DesignNameChanged().
m_disabled_by_part_conflict
bool DesignWnd::MainPanel::m_disabled_by_part_conflict = false private
Referenced by DesignChanged().
m_empire_designs_changed_signal
boost::signals2::connection DesignWnd::MainPanel::m_empire_designs_changed_signal private
Referenced by Sanitize().
m_hull
const HullType* DesignWnd::MainPanel::m_hull = nullptr private
Referenced by DesignChanged(), Hull(), LClick(), Populate(), RefreshIncompleteDesign(), and SetHull().
m_incomplete_design
std::shared_ptr<ShipDesign> DesignWnd::MainPanel::m_incomplete_design = nullptr mutable private
Referenced by GetIncompleteDesign(), RefreshIncompleteDesign(), and SetDesign().
m_replace_button
std::shared_ptr<GG::Button> DesignWnd::MainPanel::m_replace_button = nullptr private
Referenced by CompleteConstruction(), DesignChanged(), and DoLayout().
m_replaced_design_id
boost::optional<int> DesignWnd::MainPanel::m_replaced_design_id = boost::none private
Referenced by EditingCurrentDesign(), GetReplacedDesignID(), SetDesign(), and SetDesignComponents().
m_replaced_design_uuid
boost::optional<boost::uuids::uuid> DesignWnd::MainPanel::m_replaced_design_uuid = boost::none private
Referenced by EditingSavedDesign(), SetDesign(), and SetDesignComponents().
m_slots
std::vector<std::shared_ptr<SlotControl> > DesignWnd::MainPanel::m_slots private
Referenced by AddPartWithSwapping(), ClearPart(), ClearParts(), DoLayout(), FindEmptySlotForPart(), FindSlotForPartWithSwapping(), HighlightSlotType(), Parts(), Populate(), SetPart(), and SetParts().
m_type_to_create
DesignWnd::BaseSelector::BaseSelectorTab DesignWnd::MainPanel::m_type_to_create = DesignWnd::BaseSelector::BaseSelectorTab::Current private
Whether to add new designs to current or saved designs This tracks the last relevant selected tab in the base selector.
Referenced by AddDesign(), DesignChanged(), HandleBaseTypeChange(), and ReplaceDesign().
PartTypeClickedSignal
boost::signals2::signal<void (const PartType*, GG::Flags<GG::ModKey>)> DesignWnd::MainPanel::PartTypeClickedSignal mutable
propagates signals from contained SlotControls that signal that a part has been clicked
Referenced by Populate().
The documentation for this class was generated from the following file:
DesignWnd.cpp