FreeOrion: GodotClientApp Class Reference
GodotClientApp Class Reference
#include <GodotClientApp.h>
Public Member Functions
GodotClientApp ()
GodotClientApp (const GodotClientApp &)=delete
GodotClientApp (GodotClientApp &&)=delete
~GodotClientApp () override
int EffectsProcessingThreads () const override
void NewSinglePlayerGame ()
const GodotClientApp & operator= (const GodotClientApp &)=delete
GodotClientApp & operator= (const GodotClientApp &&)=delete
void SetSinglePlayerGame (bool sp=true)
bool SinglePlayerGame () const
returns true iff this game is a single-player game
Public Member Functions inherited from ClientApp
ClientApp (const ClientApp &)=delete
ClientApp (ClientApp &&)=delete
~ClientApp () override=default
int CurrentTurn () const override
Return the current game turn.
int EmpireID () const
Return the empire identifier of the empire this client controls.
ObjectMap & EmpireKnownObjects (int empire_id) override
Return all Objects known to empire_id.
int EmpirePlayerID (int empire_id) const
Return the player identfier of the player controlling the empire empire_id.
Networking::ClientType GetClientType () const
Return The Networking::ClientType of this client.
Empire * GetEmpire (int empire_id) override
Return the Empire identified by empire_id.
Networking::ClientType GetEmpireClientType (int empire_id) const override
Return the Networking::ClientType of the empire empire_id.
Networking::ClientType GetPlayerClientType (int player_id) const override
Return the Networking::ClientType of the player player_id.
Species * GetSpecies (const std::string &name) override
SpeciesManager & GetSpeciesManager () override
const SpeciesManager & GetSpeciesManager () const
SupplyManager & GetSupplyManager () override
std::string GetVisibleObjectName (std::shared_ptr< const UniverseObject > object) override
Return the for this client visible name of object.
virtual void HandleTurnPhaseUpdate (Message::TurnProgressPhase phase_id)
Handle server acknowledgement of receipt of orders and clear the orders.
const ClientApp & operator= (const ClientApp &)=delete
ClientApp & operator= (ClientApp &&)=delete
int PlayerID () const
Return the player identifier of this client.
void SendPartialOrders ()
Send turn orders updates to server without starting new turn.
void SetCurrentTurn (int turn)
Set the current game turn of this client to turn.
void SetEmpireID (int empire_id)
Set the identifier of the ::Empire controlled by this client to empire_id.
void SetEmpireStatus (int empire_id, Message::PlayerStatus status)
Set the Message::PlayerStatus status for empire_id.
virtual void StartTurn (const SaveGameUIData &ui_data)
Send the OrderSet and UI data to the server and start a new turn.
virtual void StartTurn (const std::string &save_state_string)
Send the OrderSet and AI state to the server and start a new turn.
bool VerifyCheckSum (const Message &msg)
Compare content checksum from server with client content checksum.
std::map< int, PlayerInfo > & Players ()
Return the players in game as PlayerInfo map.
const std::map< int, PlayerInfo > & Players () const
Return the players in game as PlayerInfo map.
Universe & GetUniverse () override
Return the Universe known to this client.
const Universe & GetUniverse () const
Return the Universe known to this client.
GalaxySetupData & GetGalaxySetupData ()
Return the GalaxySetupData of this game.
const GalaxySetupData & GetGalaxySetupData () const override
Return the GalaxySetupData of this game.
OrderSet & Orders ()
Return the OrderSet of this client.
const OrderSet & Orders () const
Return the OrderSet of this client.
ClientNetworking & Networking ()
Return the networking object of this clients player.
const ClientNetworking & Networking () const
Return the networking object of this clients player.
EmpireManager & Empires () override
Return the set of known Empire s for this client.
const EmpireManager & Empires () const
Return the set of known Empire s for this client.
Public Member Functions inherited from IApp
IApp (const IApp &)=delete
IApp (IApp &&)=delete
virtual ~IApp ()
const IApp & operator= (const IApp &)=delete
IApp & operator= (IApp &&)=delete
virtual void StartBackgroundParsing (const PythonParser &python, std::promise< void > &&barrier)
Launches asynchronous parsing of game content, then starts additional content parsing in the calling thread.
Static Public Member Functions
static GodotClientApp * GetApp ()
Static Public Member Functions inherited from ClientApp
static ClientApp * GetApp ()
Return the singleton instance of this Application.
Static Public Member Functions inherited from IApp
static IApp * GetApp ()
Returns a IApp pointer to the singleton instance of the app.
static int MAX_AI_PLAYERS ()
Maximum number of AIs.
Private Member Functions
void FreeServer ()
Frees (relinquishes ownership and control of) any running server process already started by this client; performs no cleanup of other processes, such as AIs.
void StartServer ()
Starts a server process on localhost.
Private Attributes
std::queue< std::string > m_game_saves_in_progress
Filenames of all in progress saves.
Process m_server_process
the server process (when hosting a game or playing single player); will be empty when playing multiplayer as a non-host player
bool m_single_player_game = true
true when this game is a single-player game
Additional Inherited Members
Protected Member Functions inherited from ClientApp
ClientApp ()
Protected Member Functions inherited from IApp
IApp ()
Protected Attributes inherited from ClientApp
int m_current_turn = INVALID_GAME_TURN
int m_empire_id = ALL_EMPIRES
EmpireManager m_empires
GalaxySetupData m_galaxy_setup_data
std::shared_ptr< ClientNetworking > m_networking
OrderSet m_orders
std::map< int, PlayerInfo > m_player_info
Indexed by player id, contains info about all players in the game.
SpeciesManager m_species_manager
SupplyManager m_supply_manager
Universe m_universe
Static Protected Attributes inherited from IApp
static IApp * s_app = nullptr
a IApp pointer to the singleton instance of the app
Constructor & Destructor Documentation
GodotClientApp() [1/3]
GodotClientApp::GodotClientApp ()
References DebugLogger, FreeOrionVersionString(), GetOptionsDB(), GetResourceDir(), GetUserDataDir(), InfoLogger, PythonCommon::Initialize(), InitLoggingOptionsDBSystem(), InitLoggingSystem(), LogDependencyVersions(), OptionsDB::Set(), and anonymous_namespace{GodotClientApp.cpp}::SetStringtableDependentOptionDefaults().
GodotClientApp() [2/3]
GodotClientApp::GodotClientApp (const GodotClientApp &) delete
GodotClientApp() [3/3]
GodotClientApp::GodotClientApp (GodotClientApp &&) delete
~GodotClientApp()
GodotClientApp::~GodotClientApp () override
Member Function Documentation
EffectsProcessingThreads()
int GodotClientApp::EffectsProcessingThreads () const override virtual
Implements IApp.
References OptionsDB::Get(), and GetOptionsDB().
FreeServer()
void GodotClientApp::FreeServer () private
Frees (relinquishes ownership and control of) any running server process already started by this client; performs no cleanup of other processes, such as AIs.
References ALL_EMPIRES, and Networking::INVALID_PLAYER_ID.
GetApp()
GodotClientApp * GodotClientApp::GetApp () static
NewSinglePlayerGame()
void GodotClientApp::NewSinglePlayerGame ()
References GalaxySetupData::age, GalaxySetupData::ai_aggr, ALL_EMPIRES, anonymous_namespace{GodotClientApp.cpp}::ClearPreviousPendingSaves(), PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, PlayerSetupData::empire_color, PlayerSetupData::empire_name, EmpireColors(), ErrorLogger, SinglePlayerSetupData::filename, parse::game_rules(), GalaxySetupData::game_rules, OptionsDB::Get(), GetGameRules(), GetOptionsDB(), GameRules::GetRulesAsStrings(), GetSpecies(), GetSpeciesManager(), HostSPGameMessage(), GalaxySetupData::monster_freq, GalaxySetupData::native_freq, SinglePlayerSetupData::new_game, SpeciesManager::NumPlayableSpecies(), GalaxySetupData::planet_density, SpeciesManager::playable_begin(), PlayerSetupData::player_name, SinglePlayerSetupData::players, PlayerSetupData::save_game_empire_id, GalaxySetupData::SetSeed(), GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, PlayerSetupData::starting_species_name, and to_string().
operator=() [1/2]
const GodotClientApp& GodotClientApp::operator= (const GodotClientApp &) delete
operator=() [2/2]
GodotClientApp& GodotClientApp::operator= (const GodotClientApp &&) delete
SetSinglePlayerGame()
void GodotClientApp::SetSinglePlayerGame (bool sp = true)
SinglePlayerGame()
bool GodotClientApp::SinglePlayerGame () const
returns true iff this game is a single-player game
StartServer()
void GodotClientApp::StartServer () private
Starts a server process on localhost.
Throws a runtime_error if the server process can't be started.
Throws LocalServerAlreadyRunningException (derived from runtime_error in HumanClientApp.cpp) if another server is already running.
References tag_parser::args, DebugLogger, ErrorLogger, OptionsDB::Get(), and GetOptionsDB().
Member Data Documentation
m_game_saves_in_progress
std::queue<std::string> GodotClientApp::m_game_saves_in_progress private
Filenames of all in progress saves.
There maybe multiple saves in progress if a player and an autosave are initiated at the same time.
m_server_process
Process GodotClientApp::m_server_process private
the server process (when hosting a game or playing single player); will be empty when playing multiplayer as a non-host player
m_single_player_game
bool GodotClientApp::m_single_player_game = true private
true when this game is a single-player game
The documentation for this class was generated from the following files:
GodotClientApp.h
GodotClientApp.cpp