FreeOrion: parse::detail::Labeller Class Reference
parse::detail::Labeller Class Reference
#include <ParseImpl.h>
Public Member Functions
Labeller (const parse::lexer &tok_)
label_rule & rule (const char *name)
Private Attributes
std::unordered_map< const char *, label_rule > m_rules
const parse::lexer & m_tok
Detailed Description
Store label_rules.
Constructor & Destructor Documentation
parse::detail::Labeller::Labeller (const parse::lexer & tok_)
Member Function Documentation
label_rule & parse::detail::Labeller::rule (const char * name)
Retrieve or create a label rule for name.
References m_rules, m_tok, parse::lexer::name_token(), and PARSING_LABELS_OPTIONAL.
Referenced by parse::detail::arithmetic_rules< T >::arithmetic_rules(), parse::detail::common_params_rules::common_params_rules(), parse::detail::condition_parser_rules_1::condition_parser_rules_1(), parse::detail::condition_parser_rules_2::condition_parser_rules_2(), parse::detail::condition_parser_rules_3::condition_parser_rules_3(), parse::detail::condition_parser_rules_4::condition_parser_rules_4(), parse::detail::condition_parser_rules_5::condition_parser_rules_5(), parse::detail::condition_parser_rules_6::condition_parser_rules_6(), parse::detail::condition_parser_rules_7::condition_parser_rules_7(), parse::double_complex_parser_grammar::double_complex_parser_grammar(), parse::detail::effect_parser_rules_1::effect_parser_rules_1(), parse::detail::effect_parser_rules_2::effect_parser_rules_2(), parse::detail::effect_parser_rules_3::effect_parser_rules_3(), parse::detail::effect_parser_rules_4::effect_parser_rules_4(), parse::detail::effect_parser_rules_5::effect_parser_rules_5(), parse::effects_group_grammar::effects_group_grammar(), initialize_nonnumeric_statistic_parser(), parse::int_complex_parser_grammar::int_complex_parser_grammar(), parse::detail::item_spec_grammar::item_spec_grammar(), anonymous_namespace{ShipDesignsParser.cpp}::manifest_grammar::manifest_grammar(), parse::detail::string_complex_parser_grammar::string_complex_parser_grammar(), parse::detail::tags_grammar::tags_grammar(), and parse::detail::visibility_complex_parser_grammar::visibility_complex_parser_grammar().
Member Data Documentation
std::unordered_map<const char*, label_rule> parse::detail::Labeller::m_rules private
Referenced by rule().
const parse::lexer& parse::detail::Labeller::m_tok private
Referenced by rule().
The documentation for this class was generated from the following files:
ParseImpl.h
Parse.cpp