FreeOrion: PolicyControl Class Reference
PolicyControl Class Reference
UI representation of a government policy.
Public Member Functions
PolicyControl (const Policy *policy)
void CompleteConstruction () override
const Policy * GetPolicy () const
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
const std::string & PolicyName () const
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void SetAvailability (const AvailabilityManager::DisplayedAvailabilies &type)
Public Attributes
boost::signals2::signal< void(const Policy *, GG::Flags< GG::ModKey >)> ClickedSignal
boost::signals2::signal< void(const Policy *)> DoubleClickedSignal
boost::signals2::signal< void(const Policy *, const GG::Pt &pt)> RightClickedSignal
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_background
std::shared_ptr< GG::StaticGraphic > m_icon
const Policy * m_policy = nullptr
Detailed Description
UI representation of a government policy.
Displayed in the PolicyPalette, and can be dragged onto SlotControls to add policies to the government.
Constructor & Destructor Documentation
PolicyControl()
PolicyControl::PolicyControl (const Policy * policy) explicit
Member Function Documentation
CompleteConstruction()
void PolicyControl::CompleteConstruction () override
References GetOptionsDB(), m_background, m_icon, m_policy, Policy::Name(), anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_DROP_TYPE_STRING, anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_HEIGHT(), anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_WIDTH(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBackgroundTexture(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), ClientUI::PolicyIcon(), anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_HEIGHT(), and anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_WIDTH().
GetPolicy()
const Policy* PolicyControl::GetPolicy () const inline
References anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::SetAvailability().
Referenced by PoliciesListBox::PoliciesListBoxRow::ChildrenDraggedAway().
LClick()
void PolicyControl::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References ClickedSignal, and m_policy.
LDoubleClick()
void PolicyControl::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References DoubleClickedSignal, and m_policy.
PolicyName()
const std::string& PolicyControl::PolicyName () const inline
References anonymous_namespace{GovernmentWnd.cpp}::EMPTY_STRING.
RClick()
void PolicyControl::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References m_policy, and RightClickedSignal.
Render()
void PolicyControl::Render () override
SetAvailability()
void PolicyControl::SetAvailability (const AvailabilityManager::DisplayedAvailabilies & type)
References m_background, and m_icon.
Member Data Documentation
ClickedSignal
boost::signals2::signal<void (const Policy*, GG::Flags<GG::ModKey>)> PolicyControl::ClickedSignal mutable
Referenced by LClick().
DoubleClickedSignal
boost::signals2::signal<void (const Policy*)> PolicyControl::DoubleClickedSignal mutable
Referenced by LDoubleClick().
m_background
std::shared_ptr<GG::StaticGraphic> PolicyControl::m_background private
Referenced by CompleteConstruction(), and SetAvailability().
m_icon
std::shared_ptr<GG::StaticGraphic> PolicyControl::m_icon private
Referenced by CompleteConstruction(), and SetAvailability().
m_policy
const Policy* PolicyControl::m_policy = nullptr private
Referenced by CompleteConstruction(), LClick(), LDoubleClick(), and RClick().
RightClickedSignal
boost::signals2::signal<void (const Policy*, const GG::Pt& pt)> PolicyControl::RightClickedSignal mutable
Referenced by RClick().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp