FreeOrion: CUIStyle Class Reference
CUIStyle Class Reference
#include <CUIStyle.h>
Public Member Functions
std::shared_ptr< GG::Button > NewButton (std::string str, const std::shared_ptr< GG::Font > &font, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE) const override
std::shared_ptr< GG::DropDownList > NewDropDownList (size_t num_shown_elements, GG::Clr color) const override
std::shared_ptr< GG::Edit > NewEdit (std::string str, const std::shared_ptr< GG::Font > &font, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK, GG::Clr interior=GG::CLR_ZERO) const override
std::shared_ptr< GG::Button > NewHScrollTabButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewHSliderTabButton (GG::Clr color) const override
std::shared_ptr< GG::Slider< int > > NewIntSlider (int min, int max, GG::Orientation orientation, GG::Clr color, int tab_width, int line_width=5) const override
std::shared_ptr< GG::ListBox > NewListBox (GG::Clr color, GG::Clr interior=GG::CLR_ZERO) const override
std::shared_ptr< GG::Scroll > NewScroll (GG::Orientation orientation, GG::Clr color, GG::Clr interior) const override
std::shared_ptr< GG::Button > NewScrollDownButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewScrollLeftButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewScrollRightButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewScrollUpButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewSpinDecrButton (const std::shared_ptr< GG::Font > &font, GG::Clr color) const override
std::shared_ptr< GG::Button > NewSpinIncrButton (const std::shared_ptr< GG::Font > &font, GG::Clr color) const override
std::shared_ptr< GG::TabBar > NewTabBar (const std::shared_ptr< GG::Font > &font, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK) const override
std::shared_ptr< GG::Button > NewTabBarLeftButton (const std::shared_ptr< GG::Font > &font, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK) const override
std::shared_ptr< GG::Button > NewTabBarRightButton (const std::shared_ptr< GG::Font > &font, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK) const override
std::shared_ptr< GG::StateButton > NewTabBarTab (std::string str, const std::shared_ptr< GG::Font > &font, GG::Flags< GG::TextFormat > format, GG::Clr color, GG::Clr text_color=GG::CLR_BLACK) const override
std::shared_ptr< GG::Button > NewVScrollTabButton (GG::Clr color) const override
std::shared_ptr< GG::Button > NewVSliderTabButton (GG::Clr color) const override
std::string Translate (const std::string &text) const override
Member Function Documentation
NewButton()
std::shared_ptr< GG::Button > CUIStyle::NewButton (std::string str, const std::shared_ptr< GG::Font > & font, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE) const override
NewDropDownList()
std::shared_ptr< GG::DropDownList > CUIStyle::NewDropDownList (size_t num_shown_elements, GG::Clr color) const override
NewEdit()
std::shared_ptr< GG::Edit > CUIStyle::NewEdit (std::string str, const std::shared_ptr< GG::Font > & font, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK, GG::Clr interior = GG::CLR_ZERO) const override
NewHScrollTabButton()
std::shared_ptr< GG::Button > CUIStyle::NewHScrollTabButton (GG::Clr color) const override
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
NewHSliderTabButton()
std::shared_ptr< GG::Button > CUIStyle::NewHSliderTabButton (GG::Clr color) const override
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
NewIntSlider()
std::shared_ptr< GG::Slider< int > > CUIStyle::NewIntSlider (int min, int max, GG::Orientation orientation, GG::Clr color, int tab_width, int line_width = 5) const override
References max, and min.
NewListBox()
std::shared_ptr< GG::ListBox > CUIStyle::NewListBox (GG::Clr color, GG::Clr interior = GG::CLR_ZERO) const override
NewScroll()
std::shared_ptr< GG::Scroll > CUIStyle::NewScroll (GG::Orientation orientation, GG::Clr color, GG::Clr interior) const override
NewScrollDownButton()
std::shared_ptr< GG::Button > CUIStyle::NewScrollDownButton (GG::Clr color) const override
References NewScrollUpButton().
NewScrollLeftButton()
std::shared_ptr< GG::Button > CUIStyle::NewScrollLeftButton (GG::Clr color) const override
References NewScrollUpButton().
NewScrollRightButton()
std::shared_ptr< GG::Button > CUIStyle::NewScrollRightButton (GG::Clr color) const override
References NewScrollUpButton().
NewScrollUpButton()
std::shared_ptr< GG::Button > CUIStyle::NewScrollUpButton (GG::Clr color) const override
Referenced by NewScrollDownButton(), NewScrollLeftButton(), and NewScrollRightButton().
NewSpinDecrButton()
std::shared_ptr< GG::Button > CUIStyle::NewSpinDecrButton (const std::shared_ptr< GG::Font > & font, GG::Clr color) const override
References DOWN.
NewSpinIncrButton()
std::shared_ptr< GG::Button > CUIStyle::NewSpinIncrButton (const std::shared_ptr< GG::Font > & font, GG::Clr color) const override
References UP.
NewTabBar()
std::shared_ptr< GG::TabBar > CUIStyle::NewTabBar (const std::shared_ptr< GG::Font > & font, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK) const override
NewTabBarLeftButton()
std::shared_ptr< GG::Button > CUIStyle::NewTabBarLeftButton (const std::shared_ptr< GG::Font > & font, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK) const override
References LEFT.
NewTabBarRightButton()
std::shared_ptr< GG::Button > CUIStyle::NewTabBarRightButton (const std::shared_ptr< GG::Font > & font, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK) const override
References RIGHT.
NewTabBarTab()
std::shared_ptr< GG::StateButton > CUIStyle::NewTabBarTab (std::string str, const std::shared_ptr< GG::Font > & font, GG::Flags< GG::TextFormat > format, GG::Clr color, GG::Clr text_color = GG::CLR_BLACK) const override
References ClientUI::TextColor(), and ClientUI::WndColor().
NewVScrollTabButton()
std::shared_ptr< GG::Button > CUIStyle::NewVScrollTabButton (GG::Clr color) const override
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
NewVSliderTabButton()
std::shared_ptr< GG::Button > CUIStyle::NewVSliderTabButton (GG::Clr color) const override
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
Translate()
std::string CUIStyle::Translate (const std::string & text) const override
References UserString().
The documentation for this class was generated from the following files:
CUIStyle.h
CUIStyle.cpp