FreeOrion: Effect::EffectsGroup Class Reference
Effect::EffectsGroup Class Reference
Contains one or more Effects, a Condition which indicates the objects in the scope of the Effect(s), and a Condition which indicates whether or not the Effect(s) will be executed on the objects in scope during the current turn.
#include <Effect.h>
Public Member Functions
EffectsGroup (std::unique_ptr< Condition::ConditionBase > &&scope, std::unique_ptr< Condition::ConditionBase > &&activation, std::vector< std::unique_ptr< EffectBase >> &&effects, const std::string &accounting_label="", const std::string &stacking_group="", int priority=0, const std::string &description="", const std::string &content_name="")
virtual ~EffectsGroup ()
const std::string & AccountingLabel () const
Condition::ConditionBase * Activation () const
std::string Dump (unsigned short ntabs=0) const
const std::vector< EffectBase * > EffectsList () const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=nullptr, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
execute all effects in group
virtual unsigned int GetCheckSum () const
const std::string & GetDescription () const
bool HasAppearanceEffects () const
bool HasMeterEffects () const
bool HasSitrepEffects () const
int Priority () const
Condition::ConditionBase * Scope () const
void SetTopLevelContent (const std::string &content_name)
const std::string & StackingGroup () const
const std::string & TopLevelContent () const
Protected Attributes
std::string m_accounting_label
std::unique_ptr< Condition::ConditionBase > m_activation
std::string m_content_name
std::string m_description
std::vector< std::unique_ptr< EffectBase > > m_effects
int m_priority
std::unique_ptr< Condition::ConditionBase > m_scope
std::string m_stacking_group
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Contains one or more Effects, a Condition which indicates the objects in the scope of the Effect(s), and a Condition which indicates whether or not the Effect(s) will be executed on the objects in scope during the current turn.
Since Conditions operate on sets of objects (usually all objects in the universe), the activation condition bears some explanation. It exists to allow an EffectsGroup to be activated or suppressed based on the source object only (the object to which the EffectsGroup is attached). It does this by considering the "universe" containing only the source object. If the source object meets the activation condition, the EffectsGroup will be active in the current turn.
Constructor & Destructor Documentation
EffectsGroup()
Effect::EffectsGroup::EffectsGroup (std::unique_ptr< Condition::ConditionBase > && scope, std::unique_ptr< Condition::ConditionBase > && activation, std::vector< std::unique_ptr< EffectBase >> && effects, const std::string & accounting_label = "", const std::string & stacking_group = "", int priority = 0, const std::string & description = "", const std::string & content_name = "")
~EffectsGroup()
Effect::EffectsGroup::~EffectsGroup () virtual
Member Function Documentation
AccountingLabel()
const std::string& Effect::EffectsGroup::AccountingLabel () const inline
Referenced by Universe::ExecuteEffects().
Activation()
Condition::ConditionBase* Effect::EffectsGroup::Activation () const inline
Dump()
std::string Effect::EffectsGroup::Dump (unsigned short ntabs = 0) const
References DumpIndent(), m_activation, m_content_name, m_effects, m_scope, and m_stacking_group.
EffectsList()
const std::vector< EffectBase * > Effect::EffectsGroup::EffectsList () const
References m_effects.
Execute()
void Effect::EffectsGroup::Execute (const TargetsCauses & targets_causes, AccountingMap * accounting_map = nullptr, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const
execute all effects in group
References m_effects.
Referenced by Effect::EffectBase::Execute(), and Universe::ExecuteEffects().
GetCheckSum()
unsigned int Effect::EffectsGroup::GetCheckSum () const virtual
References CheckSums::CheckSumCombine(), m_accounting_label, m_activation, m_description, m_effects, m_priority, m_scope, m_stacking_group, and TraceLogger.
GetDescription()
const std::string & Effect::EffectsGroup::GetDescription () const
References m_description.
HasAppearanceEffects()
bool Effect::EffectsGroup::HasAppearanceEffects () const
References m_effects.
Referenced by Universe::ExecuteEffects().
HasMeterEffects()
bool Effect::EffectsGroup::HasMeterEffects () const
References m_effects.
Referenced by Universe::ExecuteEffects().
HasSitrepEffects()
bool Effect::EffectsGroup::HasSitrepEffects () const
References m_effects.
Referenced by Universe::ExecuteEffects().
Priority()
int Effect::EffectsGroup::Priority () const inline
References Effect::Dump().
Referenced by Universe::ExecuteEffects().
Scope()
Condition::ConditionBase* Effect::EffectsGroup::Scope () const inline
serialize()
template<class Archive > void Effect::EffectsGroup::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::EffectsGroup::SetTopLevelContent (const std::string & content_name)
References m_activation, m_content_name, m_effects, and m_scope.
StackingGroup()
const std::string& Effect::EffectsGroup::StackingGroup () const inline
Referenced by Universe::ExecuteEffects().
TopLevelContent()
const std::string& Effect::EffectsGroup::TopLevelContent () const inline
Referenced by Universe::ExecuteEffects().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_accounting_label
std::string Effect::EffectsGroup::m_accounting_label protected
Referenced by GetCheckSum().
m_activation
std::unique_ptr<Condition::ConditionBase> Effect::EffectsGroup::m_activation protected
Referenced by Dump(), GetCheckSum(), and SetTopLevelContent().
m_content_name
std::string Effect::EffectsGroup::m_content_name protected
Referenced by Dump(), and SetTopLevelContent().
m_description
std::string Effect::EffectsGroup::m_description protected
Referenced by GetCheckSum(), and GetDescription().
m_effects
std::vector<std::unique_ptr<EffectBase> > Effect::EffectsGroup::m_effects protected
Referenced by Dump(), EffectsList(), Execute(), GetCheckSum(), HasAppearanceEffects(), HasMeterEffects(), HasSitrepEffects(), and SetTopLevelContent().
m_priority
int Effect::EffectsGroup::m_priority protected
Referenced by GetCheckSum().
m_scope
std::unique_ptr<Condition::ConditionBase> Effect::EffectsGroup::m_scope protected
Referenced by Dump(), GetCheckSum(), and SetTopLevelContent().
m_stacking_group
std::string Effect::EffectsGroup::m_stacking_group protected
Referenced by Dump(), and GetCheckSum().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp