FreeOrion: XMLDoc Class Reference
XMLDoc Class Reference
Represents a document formatted with XML markup.
#include <XMLDoc.h>
Classes
struct RuleDefiner
Creates the XML parsing rules at static initialization time.
Public Member Functions
XMLDoc (const std::string &root_tag="XMLDoc")
Create an empty document with the given tag-name root_tag.
XMLDoc (const std::istream &is)
Construct a document from the given input stream is.
std::istream & ReadDoc (std::istream &is)
Clears the current content of this XMLDoc instance and read a new document from the given input stream is.
void ReadDoc (const std::string &s)
Clears the current content of this XMLDoc instance and read a new document from the given string s.
std::ostream & WriteDoc (std::ostream &os, bool indent=true) const
Write the contents of the XMLDoc into the given output stream os with optional indent.
Public Attributes
XMLElement root_node
The root element that contains the parsed document, which is represented by XMLElements.
Static Private Attributes
static XMLDoc * s_curr_parsing_doc = nullptr
Holds the XMLDoc to which the XML parser should add parsed elements.
static std::vector< XMLElement * > s_element_stack
Holds the current environment for reading XMLElements (the current enclosing XMLElements).
static RuleDefiner s_rule_definer
static XMLElement s_temp_elem
Convert string tokens into XMLElement attributes.
static std::string s_temp_attr_name
Convert string tokens into XMLElement attributes.
static void SetElemName (const char *first, const char *last)
Convert string tokens into XMLElement attributes.
static void SetAttributeName (const char *first, const char *last)
Convert string tokens into XMLElement attributes.
static void AddAttribute (const char *first, const char *last)
Convert string tokens into XMLElement attributes.
static void PushElem1 (const char *, const char *)
Convert string tokens into XMLElement attributes.
static void PushElem2 (const char *, const char *)
Convert string tokens into XMLElement attributes.
static void PopElem (const char *, const char *)
Convert string tokens into XMLElement attributes.
static void AppendToText (const char *first, const char *last)
Convert string tokens into XMLElement attributes.
Detailed Description
Represents a document formatted with XML markup.
Each XMLDoc instance is assumed to represent a complete document. It contains a tree of nested XMLElements, starting from the always existing root XMLElement node.
Constructor & Destructor Documentation
XMLDoc() [1/2]
XMLDoc::XMLDoc (const std::string & root_tag = "XMLDoc")
Create an empty document with the given tag-name root_tag.
Parameters
[in] root_tag The tag-name of the created root XMLElement.
XMLDoc() [2/2]
XMLDoc::XMLDoc (const std::istream & is)
Construct a document from the given input stream is.
Parameters
[in] is An input stream that provides an XML markup document once read.
Bug:
is isn't actually read but ignored and an empty (and maybe invalid) document is created. Use XMLDoc::ReadDoc(std::istream&) instead.
Member Function Documentation
AddAttribute()
void XMLDoc::AddAttribute (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References XMLElement::attributes, s_temp_attr_name, and s_temp_elem.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
AppendToText()
void XMLDoc::AppendToText (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References s_element_stack.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
PopElem()
void XMLDoc::PopElem (const char * , const char *) static private
Convert string tokens into XMLElement attributes.
References s_element_stack.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
PushElem1()
void XMLDoc::PushElem1 (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References s_element_stack, and s_temp_elem.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
PushElem2()
void XMLDoc::PushElem2 (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References s_element_stack, and s_temp_elem.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
ReadDoc() [1/2]
std::istream & XMLDoc::ReadDoc (std::istream & is)
Clears the current content of this XMLDoc instance and read a new document from the given input stream is.
Parameters
[in] is An input stream that provides an XML markup document once read.
Returns
The given is input stream.
References anonymous_namespace{XMLDoc.cpp}::document, root_node, s_curr_parsing_doc, and s_element_stack.
Referenced by CreditsWnd::CreditsWnd(), anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetLightPosition(), anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), InitEmpireColors(), ReadDoc(), and OptionsDB::SetFromFile().
ReadDoc() [2/2]
void XMLDoc::ReadDoc (const std::string & s)
Clears the current content of this XMLDoc instance and read a new document from the given string s.
Parameters
[in] s A string containing an XML markup document.
References ReadDoc().
SetAttributeName()
void XMLDoc::SetAttributeName (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References s_temp_attr_name.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
SetElemName()
void XMLDoc::SetElemName (const char * first, const char * last) static private
Convert string tokens into XMLElement attributes.
References s_temp_elem.
Referenced by XMLDoc::RuleDefiner::RuleDefiner().
WriteDoc()
std::ostream & XMLDoc::WriteDoc (std::ostream & os, bool indent = true) const
Write the contents of the XMLDoc into the given output stream os with optional indent.
Parameters
[in] os The output stream this document should be written to.
[in] indent If set to true the XML elements are indented and newline separated.
Returns
The given os output stream.
References root_node, and XMLElement::WriteElement().
Referenced by OptionsDB::Commit(), and OptionsDB::CommitPersistent().
Member Data Documentation
root_node
XMLElement XMLDoc::root_node
The root element that contains the parsed document, which is represented by XMLElements.
Referenced by CreditsWnd::CreditsWnd(), anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetLightPosition(), anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), OptionsDB::GetXML(), InitEmpireColors(), ReadDoc(), OptionsDB::SetFromFile(), OptionsDB::SetFromXML(), and WriteDoc().
s_curr_parsing_doc
XMLDoc * XMLDoc::s_curr_parsing_doc = nullptr static private
Holds the XMLDoc to which the XML parser should add parsed elements.
Todo:
No need to hold a static instance here, pass the document into the parser as additional attribute. This also avoids potential problems in multithreaded setups.
Referenced by ReadDoc(), and XMLElement::SetText().
s_element_stack
std::vector< XMLElement * > XMLDoc::s_element_stack static private
Holds the current environment for reading XMLElements (the current enclosing XMLElements).
Referenced by AppendToText(), PopElem(), PushElem1(), PushElem2(), ReadDoc(), and XMLElement::SetText().
s_rule_definer
XMLDoc::RuleDefiner XMLDoc::s_rule_definer static private
Referenced by XMLElement::SetText().
s_temp_attr_name
std::string XMLDoc::s_temp_attr_name static private
Convert string tokens into XMLElement attributes.
Referenced by AddAttribute(), SetAttributeName(), and XMLElement::SetText().
s_temp_elem
XMLElement XMLDoc::s_temp_elem static private
Convert string tokens into XMLElement attributes.
Referenced by AddAttribute(), PushElem1(), PushElem2(), SetElemName(), and XMLElement::SetText().
The documentation for this class was generated from the following files:
XMLDoc.h
XMLDoc.cpp