FreeOrion: CUI_MinRestoreButton Class Reference
CUI_MinRestoreButton Class Reference
a simple minimize/restore button that toggles its appearance between the styles for minimize and restore
#include <CUIWnd.h>
Public Types
enum Mode { Mode::MINIMIZE, Mode::RESTORE }
the two modes of operation of this class of button: as a minimize button or as a restore button
Public Member Functions
CUI_MinRestoreButton ()
Mode GetMode () const
returns the current mode of this button (is it a minimize button or a restore button?)
void Render () override
void Toggle ()
toggles modes between MIN_BUTTON and RESTORE_BUTTON
Private Attributes
Mode m_mode
Detailed Description
a simple minimize/restore button that toggles its appearance between the styles for minimize and restore
Member Enumeration Documentation
Mode
enum CUI_MinRestoreButton::Mode strong
the two modes of operation of this class of button: as a minimize button or as a restore button
Enumerator
MINIMIZE
RESTORE
Constructor & Destructor Documentation
CUI_MinRestoreButton()
CUI_MinRestoreButton::CUI_MinRestoreButton ()
References Toggle().
Member Function Documentation
GetMode()
Mode CUI_MinRestoreButton::GetMode () const inline
returns the current mode of this button (is it a minimize button or a restore button?)
References m_mode, Render(), and Toggle().
Render()
void CUI_MinRestoreButton::Render () override
References AdjustBrightness(), anonymous_namespace{CUIWnd.cpp}::BUTTON_DIMMING_SCALE_FACTOR, m_mode, MINIMIZE, and ClientUI::WndInnerBorderColor().
Referenced by GetMode(), and CUIWnd::Minimized().
Toggle()
void CUI_MinRestoreButton::Toggle ()
toggles modes between MIN_BUTTON and RESTORE_BUTTON
References m_mode, MINIMIZE, anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound(), anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound(), and RESTORE.
Referenced by CUI_MinRestoreButton(), and GetMode().
Member Data Documentation
m_mode
Mode CUI_MinRestoreButton::m_mode private
Referenced by GetMode(), Render(), and Toggle().
The documentation for this class was generated from the following files:
CUIWnd.h
CUIWnd.cpp