FreeOrion: SidePanel::PlanetPanel Class Reference
SidePanel::PlanetPanel Class Reference
A single planet's info and controls; several of these may appear at any one time in a SidePanel.
Public Member Functions
void CompleteConstruction () override
Structors
PlanetPanel (GG::X w, int planet_id, StarType star_type)
~PlanetPanel ()
Accessors
bool InWindow (const GG::Pt &pt) const override
int PlanetID () const
Mutators
void PreRender () override
updates panels, shows / hides colonize button, redoes layout of infopanels
void Render () override
updates panels, shows / hides colonize button, redoes layout of infopanels
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
updates panels, shows / hides colonize button, redoes layout of infopanels
void Select (bool selected)
updates panels, shows / hides colonize button, redoes layout of infopanels
void Refresh ()
updates panels, shows / hides colonize button, redoes layout of infopanels
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via this PlanetPanel.
Public Attributes
boost::signals2::signal< void(int)> BuildingRightClickedSignal
boost::signals2::signal< void(const std::string &)> FocusChangedSignal
emitted when focus is changed
boost::signals2::signal< void(int)> LeftClickedSignal
emitted when the planet panel is left clicked by the user.
boost::signals2::signal< void(int)> LeftDoubleClickedSignal
emitted when the planet is left double clicked by the user.
boost::signals2::signal< void(int)> OrderButtonChangedSignal
Emitted when an order button changes state, used to update controls of panels for other planets in the same system.
boost::signals2::signal< void()> ResizedSignal
emitted when resized, so external container can redo layout
boost::signals2::signal< void(int)> RightClickedSignal
emitted when the planet panel is right clicked by the user.
Private Member Functions
void ClickBombard ()
called if bombard button is pressed
void ClickColonize ()
called if colonize button is pressed
void ClickInvade ()
called if invade button is pressed
void DoLayout ()
void FocusDropListSelectionChangedSlot (GG::DropDownList::iterator selected)
called when droplist selection changes, emits FocusChangedSignal
void RefreshPlanetGraphic ()
void SetFocus (const std::string &focus)
set the focus of the planet to focus
Private Attributes
std::shared_ptr< GG::Button > m_bombard_button
btn which can be pressed to bombard this planet;
std::shared_ptr< BuildingsPanel > m_buildings_panel
contains icons representing buildings
std::shared_ptr< GG::Button > m_colonize_button
btn which can be pressed to colonize this planet;
GG::Clr m_empire_colour
colour to use for empire-specific highlighting. set based on ownership of planet.
std::shared_ptr< GG::Label > m_env_size
indicates size and planet environment rating uncolonized planets;
std::shared_ptr< GG::DropDownList > m_focus_drop
displays and allows selection of planetary focus;
std::shared_ptr< GG::Button > m_invade_button
btn which can be pressed to invade this planet;
std::shared_ptr< MilitaryPanel > m_military_panel
contains icons representing military-related meters
bool m_order_issuing_enabled
can orders be issues via this planet panel?
boost::signals2::connection m_planet_connection
std::shared_ptr< GG::DynamicGraphic > m_planet_graphic
image of the planet (can be a frameset); this is now used only for asteroids;
int m_planet_id
id for the planet with is represented by this planet panel
std::shared_ptr< GG::TextControl > m_planet_name
planet name;
std::shared_ptr< GG::StaticGraphic > m_planet_status_graphic
gives information about the planet status, like supply disconnection
std::shared_ptr< PopulationPanel > m_population_panel
contains info about population and health
std::shared_ptr< ResourcePanel > m_resource_panel
contains info about resources production and focus selection UI
std::shared_ptr< RotatingPlanetControl > m_rotating_planet_graphic
a realtime-rendered planet that rotates, with a textured surface mapped onto it
bool m_selected
is this planet panel selected
std::shared_ptr< SpecialsPanel > m_specials_panel
contains icons representing specials
StarType m_star_type
Detailed Description
A single planet's info and controls; several of these may appear at any one time in a SidePanel.
Constructor & Destructor Documentation
PlanetPanel()
SidePanel::PlanetPanel::PlanetPanel (GG::X w, int planet_id, StarType star_type)
~PlanetPanel()
SidePanel::PlanetPanel::~PlanetPanel ()
Member Function Documentation
ClickBombard()
void SidePanel::PlanetPanel::ClickBombard () private
called if bombard button is pressed
References ALL_EMPIRES, AutomaticallyChosenBombardShips(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetPlanet(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_planet_id, METER_POPULATION, OrderButtonChangedSignal, ClientApp::Orders(), anonymous_namespace{SidePanel.cpp}::PendingBombardOrders(), OrderSet::RescindOrder(), and anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips().
Referenced by CompleteConstruction().
ClickColonize()
void SidePanel::PlanetPanel::ClickColonize () private
called if colonize button is pressed
References ALL_EMPIRES, AutomaticallyChosenColonyShip(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), GetPlanet(), GetShip(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_planet_id, METER_POPULATION, OrderButtonChangedSignal, ClientApp::Orders(), anonymous_namespace{SidePanel.cpp}::PendingColonizationOrders(), OrderSet::RescindOrder(), SidePanel::SystemID(), and ValidSelectedColonyShip().
Referenced by CompleteConstruction().
ClickInvade()
void SidePanel::PlanetPanel::ClickInvade () private
called if invade button is pressed
References ALL_EMPIRES, AutomaticallyChosenInvasionShips(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetPlanet(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_planet_id, METER_POPULATION, OrderButtonChangedSignal, ClientApp::Orders(), anonymous_namespace{SidePanel.cpp}::PendingInvadeOrders(), OrderSet::RescindOrder(), and anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips().
Referenced by CompleteConstruction().
CompleteConstruction()
void SidePanel::PlanetPanel::CompleteConstruction () override
References BuildingRightClickedSignal, Empire::CapitalID(), ClickBombard(), ClickColonize(), ClickInvade(), anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), Empires(), ErrorLogger, FocusChangedSignal, FocusDropListSelectionChangedSlot(), ClientUI::GetBoldFont(), ClientUI::GetFont(), GetOptionsDB(), GetPlanet(), m_bombard_button, m_buildings_panel, m_colonize_button, m_env_size, m_focus_drop, m_invade_button, m_military_panel, m_planet_id, m_planet_name, m_population_panel, m_resource_panel, m_specials_panel, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), ClientUI::Pts(), Refresh(), SetFocus(), anonymous_namespace{ServerWrapper.cpp}::SetName(), ClientUI::TextColor(), and UserString().
DoLayout()
void SidePanel::PlanetPanel::DoLayout () private
References anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), m_bombard_button, m_buildings_panel, m_colonize_button, m_env_size, m_focus_drop, m_invade_button, m_military_panel, m_planet_graphic, m_planet_name, m_population_panel, m_resource_panel, m_specials_panel, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), anonymous_namespace{SidePanel.cpp}::MeterIconSize(), ClientUI::Pts(), RefreshPlanetGraphic(), and ResizedSignal.
Referenced by PreRender().
EnableOrderIssuing()
void SidePanel::PlanetPanel::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this PlanetPanel.
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetUniverseObject(), m_bombard_button, m_buildings_panel, m_colonize_button, m_focus_drop, m_invade_button, m_order_issuing_enabled, and m_planet_id.
FocusDropListSelectionChangedSlot()
void SidePanel::PlanetPanel::FocusDropListSelectionChangedSlot (GG::DropDownList::iterator selected) private
called when droplist selection changes, emits FocusChangedSignal
References DebugLogger, ErrorLogger, FocusChangedSignal, GetResourceCenter(), m_focus_drop, and m_planet_id.
Referenced by CompleteConstruction().
InWindow()
bool SidePanel::PlanetPanel::InWindow (const GG::Pt & pt) const override
References m_planet_graphic, m_rotating_planet_graphic, and anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter().
LClick()
void SidePanel::PlanetPanel::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
References LeftClickedSignal, and m_planet_id.
LDoubleClick()
void SidePanel::PlanetPanel::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
References LeftDoubleClickedSignal, and m_planet_id.
MouseWheel()
void SidePanel::PlanetPanel::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
PlanetID()
int SidePanel::PlanetPanel::PlanetID () const inline
References RotatingPlanetControl::m_planet_id, RotatingPlanetControl::Refresh(), and RotatingPlanetControl::Render().
PreRender()
void SidePanel::PlanetPanel::PreRender () override
updates panels, shows / hides colonize button, redoes layout of infopanels
References DoLayout().
RClick()
void SidePanel::PlanetPanel::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
updates panels, shows / hides colonize button, redoes layout of infopanels
References ALL_EMPIRES, RenameOrder::Check(), anonymous_namespace{SidePanel.cpp}::ClientPlayerIsModerator(), ClientApp::EmpireID(), AIInterface::EmpireID(), Empires(), ObjectMap::find(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), EmpireManager::GetDiplomaticStatus(), ClientUI::GetMapWnd(), GetPlanet(), GetSystem(), OrderSet::IssueOrder(), m_order_issuing_enabled, m_planet_id, m_planet_name, MAS_NoAction, Objects(), ClientApp::Orders(), Refresh(), OrderSet::RescindOrder(), RightClickedSignal, UserString(), and ClientUI::ZoomToPlanetPedia().
Refresh()
void SidePanel::PlanetPanel::Refresh ()
updates panels, shows / hides colonize button, redoes layout of infopanels
References ALL_EMPIRES, ClientUI::ArtDir(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), anonymous_namespace{SidePanel.cpp}::colony_projections, Meter::Current(), CurrentTurn(), DebugLogger, DoubleToString(), anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ErrorLogger, FlexibleFormat(), OptionsDB::Get(), HumanClientApp::GetApp(), GetBuilding(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), Empire::GetMeter(), Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetOptionsDB(), GetPlanet(), Species::GetPlanetEnvironment(), anonymous_namespace{SidePanel.cpp}::GetPlanetEnvironmentName(), anonymous_namespace{SidePanel.cpp}::GetPlanetSizeName(), anonymous_namespace{SidePanel.cpp}::GetPlanetTypeName(), GetShip(), GetSpecies(), GetSpeciesManager(), GetSupplyManager(), GetSystem(), ClientUI::GetTexture(), GetUniverse(), info, Universe::InhibitUniverseObjectSignals(), m_bombard_button, m_buildings_panel, m_colonize_button, m_empire_colour, m_env_size, m_focus_drop, m_invade_button, m_military_panel, m_planet_connection, m_planet_id, m_planet_name, m_planet_status_graphic, m_population_panel, m_resource_panel, m_specials_panel, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), METER_HAPPINESS, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_TROOPS, METER_POPULATION, METER_SHIELD, METER_STEALTH, METER_TARGET_POPULATION, METER_TROOPS, anonymous_namespace{SidePanel.cpp}::MeterIconSize(), anonymous_namespace{SidePanel.cpp}::SHOW_ALL_PLANET_PANELS, parse::species(), ClientUI::StatDecrColor(), ClientUI::StatIncrColor(), SidePanel::SystemID(), TAG_SHIPYARD, ClientUI::TextColor(), to_string(), Universe::UpdateMeterEstimates(), UserString(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), and anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips().
Referenced by CompleteConstruction(), and RClick().
RefreshPlanetGraphic()
void SidePanel::PlanetPanel::RefreshPlanetGraphic () private
References anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures(), GetOptionsDB(), GetPlanet(), m_planet_graphic, m_planet_id, m_rotating_planet_graphic, m_star_type, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), anonymous_namespace{SidePanel.cpp}::PlanetDiameter(), and RandSmallInt().
Referenced by DoLayout().
Render()
void SidePanel::PlanetPanel::Render () override
updates panels, shows / hides colonize button, redoes layout of infopanels
References ClientUI::CtrlColor(), anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), m_empire_colour, m_planet_graphic, m_planet_name, m_rotating_planet_graphic, m_selected, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), and ClientUI::WndOuterBorderColor().
Select()
void SidePanel::PlanetPanel::Select (bool selected)
updates panels, shows / hides colonize button, redoes layout of infopanels
References m_selected.
SetFocus()
void SidePanel::PlanetPanel::SetFocus (const std::string & focus) private
set the focus of the planet to focus
References anonymous_namespace{SidePanel.cpp}::colony_projections, ClientApp::EmpireID(), AIInterface::EmpireID(), HumanClientApp::GetApp(), GetPlanet(), OrderSet::IssueOrder(), m_planet_id, ClientApp::Orders(), and anonymous_namespace{SidePanel.cpp}::species_colony_projections.
Referenced by CompleteConstruction().
SizeMove()
void SidePanel::PlanetPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
updates panels, shows / hides colonize button, redoes layout of infopanels
Member Data Documentation
BuildingRightClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanel::BuildingRightClickedSignal mutable
Referenced by CompleteConstruction().
FocusChangedSignal
boost::signals2::signal<void (const std::string&)> SidePanel::PlanetPanel::FocusChangedSignal mutable
emitted when focus is changed
Referenced by CompleteConstruction(), and FocusDropListSelectionChangedSlot().
LeftClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanel::LeftClickedSignal mutable
emitted when the planet panel is left clicked by the user.
returns the id of the clicked planet
Referenced by LClick().
LeftDoubleClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanel::LeftDoubleClickedSignal mutable
emitted when the planet is left double clicked by the user.
returns id of the clicked planet
Referenced by LDoubleClick().
m_bombard_button
std::shared_ptr<GG::Button> SidePanel::PlanetPanel::m_bombard_button private
btn which can be pressed to bombard this planet;
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), and Refresh().
m_buildings_panel
std::shared_ptr<BuildingsPanel> SidePanel::PlanetPanel::m_buildings_panel private
contains icons representing buildings
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), and Refresh().
m_colonize_button
std::shared_ptr<GG::Button> SidePanel::PlanetPanel::m_colonize_button private
btn which can be pressed to colonize this planet;
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), and Refresh().
m_empire_colour
GG::Clr SidePanel::PlanetPanel::m_empire_colour private
colour to use for empire-specific highlighting. set based on ownership of planet.
Referenced by Refresh(), and Render().
m_env_size
std::shared_ptr<GG::Label> SidePanel::PlanetPanel::m_env_size private
indicates size and planet environment rating uncolonized planets;
Referenced by CompleteConstruction(), DoLayout(), and Refresh().
m_focus_drop
std::shared_ptr<GG::DropDownList> SidePanel::PlanetPanel::m_focus_drop private
displays and allows selection of planetary focus;
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), FocusDropListSelectionChangedSlot(), and Refresh().
m_invade_button
std::shared_ptr<GG::Button> SidePanel::PlanetPanel::m_invade_button private
btn which can be pressed to invade this planet;
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), and Refresh().
m_military_panel
std::shared_ptr<MilitaryPanel> SidePanel::PlanetPanel::m_military_panel private
contains icons representing military-related meters
Referenced by CompleteConstruction(), DoLayout(), and Refresh().
m_order_issuing_enabled
bool SidePanel::PlanetPanel::m_order_issuing_enabled private
can orders be issues via this planet panel?
Referenced by ClickBombard(), ClickColonize(), ClickInvade(), EnableOrderIssuing(), and RClick().
m_planet_connection
boost::signals2::connection SidePanel::PlanetPanel::m_planet_connection private
Referenced by Refresh().
m_planet_graphic
std::shared_ptr<GG::DynamicGraphic> SidePanel::PlanetPanel::m_planet_graphic private
image of the planet (can be a frameset); this is now used only for asteroids;
Referenced by DoLayout(), InWindow(), RefreshPlanetGraphic(), and Render().
m_planet_id
int SidePanel::PlanetPanel::m_planet_id private
id for the planet with is represented by this planet panel
Referenced by ClickBombard(), ClickColonize(), ClickInvade(), CompleteConstruction(), EnableOrderIssuing(), FocusDropListSelectionChangedSlot(), LClick(), LDoubleClick(), RClick(), Refresh(), RefreshPlanetGraphic(), and SetFocus().
m_planet_name
std::shared_ptr<GG::TextControl> SidePanel::PlanetPanel::m_planet_name private
planet name;
Referenced by CompleteConstruction(), DoLayout(), RClick(), Refresh(), and Render().
m_planet_status_graphic
std::shared_ptr<GG::StaticGraphic> SidePanel::PlanetPanel::m_planet_status_graphic private
gives information about the planet status, like supply disconnection
Referenced by Refresh().
m_population_panel
std::shared_ptr<PopulationPanel> SidePanel::PlanetPanel::m_population_panel private
contains info about population and health
Referenced by CompleteConstruction(), DoLayout(), and Refresh().
m_resource_panel
std::shared_ptr<ResourcePanel> SidePanel::PlanetPanel::m_resource_panel private
contains info about resources production and focus selection UI
Referenced by CompleteConstruction(), DoLayout(), and Refresh().
m_rotating_planet_graphic
std::shared_ptr<RotatingPlanetControl> SidePanel::PlanetPanel::m_rotating_planet_graphic private
a realtime-rendered planet that rotates, with a textured surface mapped onto it
Referenced by InWindow(), RefreshPlanetGraphic(), and Render().
m_selected
bool SidePanel::PlanetPanel::m_selected private
is this planet panel selected
Referenced by Render(), and Select().
m_specials_panel
std::shared_ptr<SpecialsPanel> SidePanel::PlanetPanel::m_specials_panel private
contains icons representing specials
Referenced by CompleteConstruction(), DoLayout(), and Refresh().
m_star_type
StarType SidePanel::PlanetPanel::m_star_type private
Referenced by RefreshPlanetGraphic().
OrderButtonChangedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanel::OrderButtonChangedSignal mutable
Emitted when an order button changes state, used to update controls of panels for other planets in the same system.
Referenced by ClickBombard(), ClickColonize(), and ClickInvade().
ResizedSignal
boost::signals2::signal<void ()> SidePanel::PlanetPanel::ResizedSignal mutable
emitted when resized, so external container can redo layout
Referenced by DoLayout().
RightClickedSignal
boost::signals2::signal<void (int)> SidePanel::PlanetPanel::RightClickedSignal mutable
emitted when the planet panel is right clicked by the user.
returns the id of the clicked planet
Referenced by RClick().
The documentation for this class was generated from the following file:
SidePanel.cpp