FreeOrion: PythonAI Class Reference
PythonAI Class Reference
Class allowing AI to recieve basic game events.
#include <AIFramework.h>
Public Member Functions
void GenerateOrders ()
Call when the server has sent a new turn update.
const std::string & GetSaveStateString () const
Called when the server is saving the game.
void HandleChatMessage (int sender_id, const std::string &msg)
Called when another player sends a chat message to this AI.
void HandleDiplomaticMessage (const DiplomaticMessage &msg)
Called when another player sends a diplomatic message that affects this player.
void HandleDiplomaticStatusUpdate (const DiplomaticStatusUpdateInfo &u)
Called when two empires diplomatic status changes.
bool Initialize ()
bool InitImports () override
Initializes AI Python imports.
bool InitModules () override
Initializes AI Python modules.
void ResumeLoadedGame (const std::string &save_state_string)
Called when a game is loaded from a save.
void SetAggression (int aggr)
Set the aggressiveness of this AI.
void StartNewGame ()
Called when a new game (not loaded) is started.
Public Member Functions inherited from PythonBase
PythonBase ()
virtual ~PythonBase ()
void AddToSysPath (const std::string dir)
std::vector< std::string > ErrorReport ()
void HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
bool Initialize ()
bool IsPythonRunning ()
IsPythonRunning returns true is the python interpreter is initialized.
void SetCurrentDir (const std::string dir)
void SetErrorModule (boost::python::object &module)
Private Attributes
int m_aggression
The current aggressiveness of this AI.
boost::python::object m_python_module_ai
Detailed Description
Class allowing AI to recieve basic game events.
Member Function Documentation
GenerateOrders()
void PythonAI::GenerateOrders ()
Call when the server has sent a new turn update.
The AI subclass should review the new gamestate and send orders for this turn.
References DebugLogger, ScopedTimer::DurationString(), ErrorLogger, AIClientApp::GetAI(), AIClientApp::GetApp(), GetOptionsDB(), GetSaveStateString(), PythonBase::HandleErrorAlreadySet(), PythonBase::IsPythonRunning(), m_python_module_ai, and ClientApp::StartTurn().
GetSaveStateString()
auto PythonAI::GetSaveStateString () const
Called when the server is saving the game.
The AI should store any state information it will need to resume at any later time, and return this information.
Returns
The serialized state information of the game running.
References FreeOrionPython::GetStaticSaveStateString(), and m_python_module_ai.
Referenced by GenerateOrders().
HandleChatMessage()
void PythonAI::HandleChatMessage (int sender_id, const std::string & msg)
Called when another player sends a chat message to this AI.
The AI subclass should respond or react to the message in a meaningful way.
Parameters
sender_id The player identifier representing the player, who sent the message.
msg The text body of the sent message.
References m_python_module_ai.
HandleDiplomaticMessage()
void PythonAI::HandleDiplomaticMessage (const DiplomaticMessage & msg)
Called when another player sends a diplomatic message that affects this player.
The AI subclass should respond or react to the message in a meaningful way.
Parameters
msg The diplomatic message sent.
References m_python_module_ai.
HandleDiplomaticStatusUpdate()
void PythonAI::HandleDiplomaticStatusUpdate (const DiplomaticStatusUpdateInfo & u)
Called when two empires diplomatic status changes.
The AI subclass should respond or react to the change in a meaningful way.
Parameters
u The diplomatic status changed.
References m_python_module_ai.
Initialize()
auto PythonAI::Initialize ()
References GetBuildingTypeManager(), and PythonBase::Initialize().
InitImports()
auto PythonAI::InitImports () override virtual
Initializes AI Python imports.
Implements PythonBase.
References DebugLogger.
InitModules()
auto PythonAI::InitModules () override virtual
Initializes AI Python modules.
Implements PythonBase.
References DebugLogger, ErrorLogger, GetOptionsDB(), and GetResourceDir().
ResumeLoadedGame()
void PythonAI::ResumeLoadedGame (const std::string & save_state_string)
Called when a game is loaded from a save.
The AI subclass should extract any state information stored in save_state so it is able to continue generating orders when asked to do so.
Parameters
save_state The serialized state information from a previous game run.
References FreeOrionPython::GetStaticSaveStateString(), m_python_module_ai, and FreeOrionPython::SetStaticSaveStateString().
SetAggression()
void PythonAI::SetAggression (int aggr)
Set the aggressiveness of this AI.
The AI should change their behaviour when setting another aggression level.
Parameters
aggr The new aggression level. The value should be one of Aggression.
References m_aggression.
StartNewGame()
void PythonAI::StartNewGame ()
Called when a new game (not loaded) is started.
The AI subclass should clear its state and prepare to start for a new game.
References FreeOrionPython::ClearStaticSaveStateString(), m_aggression, and m_python_module_ai.
Member Data Documentation
m_aggression
int PythonAI::m_aggression private
The current aggressiveness of this AI.
The value should be one of Aggression.
Referenced by SetAggression(), and StartNewGame().
m_python_module_ai
boost::python::object PythonAI::m_python_module_ai private
Referenced by GenerateOrders(), GetSaveStateString(), HandleChatMessage(), HandleDiplomaticMessage(), HandleDiplomaticStatusUpdate(), ResumeLoadedGame(), and StartNewGame().
The documentation for this class was generated from the following files:
AIFramework.h
AIFramework.cpp