FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector Class Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector Class Reference
Classes
class Spacer
class TypeRow
Public Member Functions
TypeSelector (GG::X w, GG::Y h, Networking::ClientType client_type, bool disabled)
void SelectionChanged (GG::DropDownList::iterator it)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIDropDownList
GG::Pt ClientLowerRight () const override
GG::X DroppedRowWidth () const override
Return the width of the dropped row which excludes the DropArrow.
CUIDropDownList (size_t num_shown_elements)
void Render () override
disables rendering of the small downward-facing arrow on the right of the control
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseLeave () override
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Public Attributes
boost::signals2::signal< void(Networking::ClientType)> TypeChangedSignal
Constructor & Destructor Documentation
TypeSelector()
anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeSelector (GG::X w, GG::Y h, Networking::ClientType client_type, bool disabled) inline
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ClientApp::GetApp(), ClientNetworking::HasAuthRole(), Networking::INVALID_CLIENT_TYPE, ClientApp::Networking(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, and Networking::ROLE_CLIENT_TYPE_PLAYER.
Member Function Documentation
SelectionChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::SelectionChanged (GG::DropDownList::iterator it) inline
References anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeRow::type.
SizeMove()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
TypeChangedSignal
boost::signals2::signal<void (Networking::ClientType)> anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeChangedSignal mutable
The documentation for this class was generated from the following file:
MultiplayerLobbyWnd.cpp