FreeOrion: TechTreeArcs::Impl Class Reference
TechTreeArcs::Impl Class Reference
Public Member Functions
Impl (const TechTreeLayout &layout, const std::set< std::string > &techs_to_show)
void RefreshHighlights ()
void Render (double scale)
Private Member Functions
void FillArcBuffer (GG::GL2DVertexBuffer &buffer, const std::set< std::string > &techs)
Fills buffer with the ends points for the lines that connect technologies in techs.
Private Attributes
GG::GL2DVertexBuffer m_buffer
std::map< std::string, std::set< std::string > > m_edges_to_show
GG::GL2DVertexBuffer m_highlight_buffer
const TechTreeLayout & m_layout
Constructor & Destructor Documentation
Impl()
TechTreeArcs::Impl::Impl (const TechTreeLayout & layout, const std::set< std::string > & techs_to_show) inline
References FillArcBuffer(), m_buffer, and RefreshHighlights().
Member Function Documentation
FillArcBuffer()
void TechTreeArcs::Impl::FillArcBuffer (GG::GL2DVertexBuffer & buffer, const std::set< std::string > & techs) inline private
Fills buffer with the ends points for the lines that connect technologies in techs.
References ErrorLogger, TechTreeLayout::GetOutEdges(), GetTech(), and TechTreeArcs::TechTreeArcs().
Referenced by Impl(), and RefreshHighlights().
RefreshHighlights()
void TechTreeArcs::Impl::RefreshHighlights () inline
References FillArcBuffer(), HumanClientApp::GetApp(), GetEmpire(), ResearchQueue::InQueue(), ResearchQueue::insert(), m_edges_to_show, m_highlight_buffer, and TS_COMPLETE.
Referenced by Impl().
Render()
void TechTreeArcs::Impl::Render (double scale) inline
References anonymous_namespace{TechTreeArcs.cpp}::ARC_THICKNESS, m_buffer, and m_highlight_buffer.
Member Data Documentation
m_buffer
GG::GL2DVertexBuffer TechTreeArcs::Impl::m_buffer private
Referenced by Impl(), and Render().
m_edges_to_show
std::map<std::string, std::set<std::string> > TechTreeArcs::Impl::m_edges_to_show private
Referenced by RefreshHighlights().
m_highlight_buffer
GG::GL2DVertexBuffer TechTreeArcs::Impl::m_highlight_buffer private
Referenced by RefreshHighlights(), and Render().
m_layout
const TechTreeLayout& TechTreeArcs::Impl::m_layout private
The documentation for this class was generated from the following file:
TechTreeArcs.cpp