FreeOrion: ValueRefDecorator Class Reference
ValueRefDecorator Class Reference
#include <LinkText.h>
Public Member Functions
std::string Decorate (const std::string &value_ref_name, const std::string &content) const override
Gets called for each link of the type this decorator is assigned to.
std::string DecorateRollover (const std::string &value_ref_name, const std::string &content) const override
Gets called when the mouse hovers over a link of the type this decorator is assigned to.
Public Member Functions inherited from LinkDecorator
LinkDecorator ()
virtual ~LinkDecorator ()
Additional Inherited Members
Static Protected Member Functions inherited from LinkDecorator
static int CastStringToInt (const std::string &str)
Try to convert str to int.
Member Function Documentation
Decorate()
std::string ValueRefDecorator::Decorate (const std::string & target, const std::string & content) const override virtual
Gets called for each link of the type this decorator is assigned to.
The return value is shown to the user as the link. The default implementation wraps content in an rgba tag that colors it by ClientUI::DefaultLinkColor
Parameters
target The target of the link. Usually an id of something or the name of an encyclopedia entry.
content The text the link tag was wrapped around.
Returns
The text that should be shown to the user in the place of content
Reimplemented from LinkDecorator.
References ClientUI::DefaultTooltipColor(), anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE, and anonymous_namespace{LinkText.cpp}::ValueRefLinkText().
DecorateRollover()
std::string ValueRefDecorator::DecorateRollover (const std::string & target, const std::string & content) const override virtual
Gets called when the mouse hovers over a link of the type this decorator is assigned to.
The return value is shown to the user as the link. The default implementation wraps content in an rgba tag that colors it by ClientUI::RolloverLinkColor
Parameters
target The target of the link. Usually an id of something or the name of an encyclopedia entry.
content The text the link tag was wrapped around.
Returns
The text that should be shown to the user in the place of content
Reimplemented from LinkDecorator.
References anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE, ClientUI::RolloverTooltipColor(), and anonymous_namespace{LinkText.cpp}::ValueRefLinkText().
The documentation for this class was generated from the following files:
LinkText.h
LinkText.cpp