FreeOrion: NewFleetOrder Class Reference
NewFleetOrder Class Reference
the Order subclass that represents forming a new fleet.
#include <Order.h>
Public Member Functions
NewFleetOrder (int empire, std::string fleet_name, std::vector< int > ship_ids, bool aggressive, bool passive=false, bool defensive=false)
NewFleetOrder (int empire, std::string fleet_name, std::vector< int > ship_ids, FleetAggression aggression)
FleetAggression Aggression () const
bool Aggressive () const
std::string Dump () const override
const int & FleetID () const
const std::string & FleetName () const
const std::vector< int > & ShipIDs () const
Public Member Functions inherited from Order
Order ()=default
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()=default
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Static Public Member Functions
static bool Check (int empire, const std::string &fleet_name, const std::vector< int > &ship_ids, FleetAggression aggression)
Private Member Functions
NewFleetOrder ()=default
void ExecuteImpl () const override
Preconditions of execute: None.
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
FleetAggression m_aggression {0}
int m_fleet_id = INVALID_OBJECT_ID
m_fleet_id is mutable because ExecuteImpl generates the fleet id.
std::string m_fleet_name
std::vector< int > m_ship_ids
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
the Order subclass that represents forming a new fleet.
Only one of system or position will be used to place the new fleet.
Constructor & Destructor Documentation
NewFleetOrder() [1/3]
NewFleetOrder::NewFleetOrder (int empire, std::string fleet_name, std::vector< int > ship_ids, bool aggressive, bool passive = false, bool defensive = false)
NewFleetOrder() [2/3]
NewFleetOrder::NewFleetOrder (int empire, std::string fleet_name, std::vector< int > ship_ids, FleetAggression aggression)
References Check(), m_aggression, m_fleet_name, and m_ship_ids.
NewFleetOrder() [3/3]
NewFleetOrder::NewFleetOrder () private default
Member Function Documentation
Aggression()
FleetAggression NewFleetOrder::Aggression () const inline
References Order::ExecuteImpl().
Aggressive()
bool NewFleetOrder::Aggressive () const
References m_aggression.
Check()
bool NewFleetOrder::Check (int empire, const std::string & fleet_name, const std::vector< int > & ship_ids, FleetAggression aggression) static
References ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, and Objects().
Referenced by ExecuteImpl(), anonymous_namespace{AIWrapper.cpp}::IssueNewFleetOrder(), and NewFleetOrder().
Dump()
std::string NewFleetOrder::Dump () const override virtual
Reimplemented from Order.
References anonymous_namespace{Order.cpp}::ExecutedTag(), FlexibleFormat(), m_aggression, m_fleet_name, m_ship_ids, to_string(), and UserString().
ExecuteImpl()
void NewFleetOrder::ExecuteImpl () const override private virtual
Preconditions of execute: None.
Postconditions:
new fleets will exist in system with id m_system_id, and will belong to the creating empire.
Implements Order.
References BEFORE_FIRST_TURN, Check(), Universe::Destroy(), Order::EmpireID(), ErrorLogger, ObjectMap::find(), ObjectMap::get(), GetUniverse(), Order::GetValidatedEmpire(), Universe::InhibitUniverseObjectSignals(), Universe::InsertByEmpireWithID(), Universe::InsertNew(), INVALID_OBJECT_ID, Meter::LARGE_VALUE, m_aggression, m_fleet_id, m_fleet_name, m_ship_ids, Objects(), and Universe::SetEmpireObjectVisibility().
FleetID()
const int& NewFleetOrder::FleetID () const inline
FleetName()
const std::string& NewFleetOrder::FleetName () const inline
serialize()
template<typename Archive > void NewFleetOrder::serialize (Archive & ar, const unsigned int version) private
ShipIDs()
const std::vector<int>& NewFleetOrder::ShipIDs () const inline
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_aggression
FleetAggression NewFleetOrder::m_aggression {0} private
Referenced by Aggressive(), Dump(), ExecuteImpl(), and NewFleetOrder().
m_fleet_id
int NewFleetOrder::m_fleet_id = INVALID_OBJECT_ID mutable private
m_fleet_id is mutable because ExecuteImpl generates the fleet id.
Referenced by ExecuteImpl().
m_fleet_name
std::string NewFleetOrder::m_fleet_name private
Referenced by Dump(), ExecuteImpl(), and NewFleetOrder().
m_ship_ids
std::vector<int> NewFleetOrder::m_ship_ids private
Referenced by Dump(), ExecuteImpl(), and NewFleetOrder().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp