FreeOrion: SettableInWindowCUIButton Class Reference
SettableInWindowCUIButton Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
SettableInWindowCUIButton (const GG::SubTexture &unpressed, const GG::SubTexture &pressed, const GG::SubTexture &rollover, boost::function< bool(const SettableInWindowCUIButton *, const GG::Pt &)> in_window_function)
Accessors
bool InWindow (const GG::Pt &pt) const override
Public Member Functions inherited from CUIButton
CUIButton (const std::string &str)
CUIButton (const GG::SubTexture &unpressed, const GG::SubTexture &pressed, const GG::SubTexture &rollover)
GG::Pt MinUsableSize () const override
bool InWindow (const GG::Pt &pt) const override
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
Private Attributes
boost::function< bool(const SettableInWindowCUIButton *, const GG::Pt &)> m_in_window_func
Additional Inherited Members
Protected Member Functions inherited from CUIButton
void RenderPressed () override
void RenderRollover () override
void RenderUnpressed () override
Constructor & Destructor Documentation
SettableInWindowCUIButton()
SettableInWindowCUIButton::SettableInWindowCUIButton (const GG::SubTexture & unpressed, const GG::SubTexture & pressed, const GG::SubTexture & rollover, boost::function< bool(const SettableInWindowCUIButton *, const GG::Pt &)> in_window_function)
References m_in_window_func.
Member Function Documentation
InWindow()
bool SettableInWindowCUIButton::InWindow (const GG::Pt & pt) const override
References CUIButton::InWindow(), and m_in_window_func.
Member Data Documentation
m_in_window_func
boost::function<bool(const SettableInWindowCUIButton*, const GG::Pt&)> SettableInWindowCUIButton::m_in_window_func private
Referenced by InWindow(), and SettableInWindowCUIButton().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp