FreeOrion: Networking::AuthRoles Class Reference
Networking::AuthRoles Class Reference
#include <Networking.h>
Public Member Functions
AuthRoles ()=default
AuthRoles (const std::initializer_list< RoleType > &roles)
void Clear ()
bool HasRole (RoleType role) const
void SetRole (RoleType role, bool value=true)
void SetText (const std::string &text)
std::string Text () const
Private Attributes
std::bitset< int(RoleType::Roles_Count)> m_roles
Constructor & Destructor Documentation
AuthRoles() [1/2]
Networking::AuthRoles::AuthRoles () default
AuthRoles() [2/2]
Networking::AuthRoles::AuthRoles (const std::initializer_list< RoleType > & roles)
References m_roles.
Member Function Documentation
Clear()
void Networking::AuthRoles::Clear ()
References m_roles.
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
HasRole()
bool Networking::AuthRoles::HasRole (RoleType role) const
References m_roles.
Referenced by ClientNetworking::Impl::HasAuthRole(), and PlayerConnection::HasAuthRole().
SetRole()
void Networking::AuthRoles::SetRole (RoleType role, bool value = true)
References m_roles.
Referenced by PlayerConnection::SetAuthRole().
SetText()
void Networking::AuthRoles::SetText (const std::string & text)
References m_roles.
Referenced by ExtractSetAuthorizationRolesMessage().
Text()
std::string Networking::AuthRoles::Text () const
References m_roles.
Referenced by ServerFSM::EstablishPlayer(), WaitingForMPGameJoiners::react(), and SetAuthorizationRolesMessage().
Member Data Documentation
m_roles
std::bitset<int(RoleType::Roles_Count)> Networking::AuthRoles::m_roles private
Referenced by AuthRoles(), Clear(), HasRole(), SetRole(), SetText(), and Text().
The documentation for this class was generated from the following files:
Networking.h
Networking.cpp