FreeOrion: MultiPlayerLobbyWnd Class Reference
MultiPlayerLobbyWnd Class Reference
multiplayer lobby window
#include <MultiplayerLobbyWnd.h>
Classes
struct PlayerLabelRow
Public Member Functions
Structors
MultiPlayerLobbyWnd ()
void CompleteConstruction () override
Accessors
GG::Pt MinUsableSize () const override
bool LoadGameSelected () const
std::string GetChatText () const
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Render () override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void ChatMessage (int player_id, const boost::posix_time::ptime &timestamp, const std::string &msg)
void ChatMessage (const std::string &message_text, const std::string &player_name, GG::Clr text_color, const boost::posix_time::ptime &timestamp)
void TurnPhaseUpdate (Message::TurnProgressPhase phase_id)
void LobbyUpdate (const MultiplayerLobbyData &lobby_data)
void Refresh ()
void CleanupChat ()
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Flash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void StopFlash ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetFlashDuration (int ms)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
GG::Rect CalculatePosition () const override
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Private Member Functions
void AnyCanEdit (bool checked)
void CancelClicked ()
bool CanStart () const
void DoLayout ()
void GalaxySetupPanelChanged ()
bool HasAuthRole (Networking::RoleType role) const
void NewLoadClicked (std::size_t idx)
bool PlayerDataAcceptable () const
void PlayerDataChangedLocally ()
bool PopulatePlayerList ()
repopulate list with rows built from current m_lobby_data. returns true iff something in the lobby data was changed during population and an update should be sent back to the server
void PreviewImageChanged (std::shared_ptr< GG::Texture > new_image)
void ReadyClicked ()
void SaveGameBrowse ()
void SendUpdate ()
Private Attributes
std::shared_ptr< CUIStateButton > m_any_can_edit
std::shared_ptr< GG::Button > m_browse_saves_btn
std::shared_ptr< GG::Button > m_cancel_bn
std::shared_ptr< MessageWnd > m_chat_wnd
std::shared_ptr< GalaxySetupPanel > m_galaxy_setup_panel
MultiplayerLobbyData m_lobby_data
a copy of the most recently received lobby update
std::shared_ptr< GG::RadioButtonGroup > m_new_load_game_buttons
std::shared_ptr< GG::ListBox > m_players_lb
std::shared_ptr< PlayerLabelRow > m_players_lb_headers
std::shared_ptr< GG::StaticGraphic > m_preview_image
std::shared_ptr< GG::Button > m_ready_bn
std::shared_ptr< GG::Label > m_save_file_text
std::shared_ptr< GG::Label > m_start_conditions_text
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
int m_flash_duration = 1000
time in milliseconds to switch between bright and dark
bool m_flashing = false
true if the window is currently flashing
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
multiplayer lobby window
Constructor & Destructor Documentation
MultiPlayerLobbyWnd()
MultiPlayerLobbyWnd::MultiPlayerLobbyWnd ()
Member Function Documentation
AnyCanEdit()
void MultiPlayerLobbyWnd::AnyCanEdit (bool checked) private
References HasAuthRole(), m_any_can_edit, MultiplayerLobbyData::m_any_can_edit, m_lobby_data, Networking::ROLE_HOST, and SendUpdate().
Referenced by CompleteConstruction().
CalculatePosition()
GG::Rect MultiPlayerLobbyWnd::CalculatePosition () const override protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), and anonymous_namespace{MapWnd.cpp}::AppWidth().
CancelClicked()
void MultiPlayerLobbyWnd::CancelClicked () private
References HumanClientApp::CancelMultiplayerGameFromLobby(), and HumanClientApp::GetApp().
Referenced by CompleteConstruction().
CanStart()
bool MultiPlayerLobbyWnd::CanStart () const private
References PlayerDataAcceptable().
ChatMessage() [1/2]
void MultiPlayerLobbyWnd::ChatMessage (int player_id, const boost::posix_time::ptime & timestamp, const std::string & msg)
References HumanClientApp::GetApp(), ClientUI::GetClientUI(), Networking::INVALID_PLAYER_ID, m_chat_wnd, m_lobby_data, MultiplayerLobbyData::m_players, AIInterface::PlayerID(), ClientUI::TextColor(), to_string(), and UserString().
ChatMessage() [2/2]
void MultiPlayerLobbyWnd::ChatMessage (const std::string & message_text, const std::string & player_name, GG::Clr text_color, const boost::posix_time::ptime & timestamp)
References HumanClientApp::GetApp(), m_chat_wnd, and AIInterface::PlayerID().
CleanupChat()
void MultiPlayerLobbyWnd::CleanupChat ()
References m_chat_wnd.
CompleteConstruction()
void MultiPlayerLobbyWnd::CompleteConstruction () override
References AnyCanEdit(), CancelClicked(), CUIWnd::CompleteConstruction(), DoLayout(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_HEIGHT(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_WIDTH(), GalaxySetupPanelChanged(), GetOptionsDB(), m_any_can_edit, m_browse_saves_btn, m_cancel_bn, m_chat_wnd, m_galaxy_setup_panel, m_new_load_game_buttons, m_players_lb, m_players_lb_headers, m_preview_image, m_ready_bn, m_save_file_text, m_start_conditions_text, NewLoadClicked(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowColWidths(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight(), PreviewImageChanged(), ReadyClicked(), Refresh(), CUIWnd::ResetDefaultPosition(), CUIWnd::SaveDefaultedOptions(), SaveGameBrowse(), TraceLogger, and UserString().
DoLayout()
void MultiPlayerLobbyWnd::DoLayout () private
References anonymous_namespace{MultiplayerLobbyWnd.cpp}::CHAT_WIDTH(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::CONTROL_MARGIN, anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_HEIGHT(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_WIDTH(), m_any_can_edit, m_browse_saves_btn, m_cancel_bn, m_chat_wnd, m_galaxy_setup_panel, m_new_load_game_buttons, m_players_lb, m_players_lb_headers, m_preview_image, m_ready_bn, m_save_file_text, m_start_conditions_text, anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowColWidths(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PREVIEW_SZ(), and ClientUI::Pts().
Referenced by CompleteConstruction(), PreviewImageChanged(), and SizeMove().
GalaxySetupPanelChanged()
void MultiPlayerLobbyWnd::GalaxySetupPanelChanged () private
References m_galaxy_setup_panel, m_lobby_data, and SendUpdate().
Referenced by CompleteConstruction().
GetChatText()
std::string MultiPlayerLobbyWnd::GetChatText () const
References m_chat_wnd.
HasAuthRole()
bool MultiPlayerLobbyWnd::HasAuthRole (Networking::RoleType role) const private
References ClientApp::GetApp(), ClientNetworking::HasAuthRole(), and ClientApp::Networking().
Referenced by AnyCanEdit(), LobbyUpdate(), PopulatePlayerList(), and Refresh().
KeyPress()
void MultiPlayerLobbyWnd::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References m_cancel_bn, and m_ready_bn.
LoadGameSelected()
bool MultiPlayerLobbyWnd::LoadGameSelected () const
References m_new_load_game_buttons.
LobbyUpdate()
void MultiPlayerLobbyWnd::LobbyUpdate (const MultiplayerLobbyData & lobby_data)
References HasAuthRole(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LogPlayerSetupData(), m_any_can_edit, MultiplayerLobbyData::m_any_can_edit, m_galaxy_setup_panel, m_lobby_data, MultiplayerLobbyData::m_new_game, m_new_load_game_buttons, MultiplayerLobbyData::m_players, m_save_file_text, MultiplayerLobbyData::m_save_game, PopulatePlayerList(), Networking::ROLE_GALAXY_SETUP, and SendUpdate().
MinUsableSize()
GG::Pt MultiPlayerLobbyWnd::MinUsableSize () const override
NewLoadClicked()
void MultiPlayerLobbyWnd::NewLoadClicked (std::size_t idx) private
References m_browse_saves_btn, m_galaxy_setup_panel, m_lobby_data, MultiplayerLobbyData::m_new_game, m_save_file_text, PopulatePlayerList(), and SendUpdate().
Referenced by CompleteConstruction().
PlayerDataAcceptable()
bool MultiPlayerLobbyWnd::PlayerDataAcceptable () const private
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, and m_players_lb.
Referenced by CanStart().
PlayerDataChangedLocally()
void MultiPlayerLobbyWnd::PlayerDataChangedLocally () private
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::INVALID_PLAYER_ID, m_lobby_data, MultiplayerLobbyData::m_players, m_players_lb, and SendUpdate().
Referenced by PopulatePlayerList().
PopulatePlayerList()
bool MultiPlayerLobbyWnd::PopulatePlayerList () private
repopulate list with rows built from current m_lobby_data. returns true iff something in the lobby data was changed during population and an update should be sent back to the server
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, HumanClientApp::GetApp(), HasAuthRole(), PlayerSetupData::m_client_type, MultiplayerLobbyData::m_in_game, m_lobby_data, MultiplayerLobbyData::m_new_game, PlayerSetupData::m_player_ready, MultiplayerLobbyData::m_players, m_players_lb, m_players_lb_headers, m_ready_bn, MultiplayerLobbyData::m_save_game_empire_data, m_start_conditions_text, MultiplayerLobbyData::m_start_lock_cause, MultiplayerLobbyData::m_start_locked, PlayerDataChangedLocally(), ClientApp::PlayerID(), AIInterface::PlayerID(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowColWidths(), Refresh(), Networking::ROLE_GALAXY_SETUP, Networking::ROLE_HOST, and UserString().
Referenced by LobbyUpdate(), NewLoadClicked(), ReadyClicked(), and SaveGameBrowse().
PreviewImageChanged()
void MultiPlayerLobbyWnd::PreviewImageChanged (std::shared_ptr< GG::Texture > new_image) private
References DoLayout(), and m_preview_image.
Referenced by CompleteConstruction().
ReadyClicked()
void MultiPlayerLobbyWnd::ReadyClicked () private
References HumanClientApp::GetApp(), m_lobby_data, MultiplayerLobbyData::m_players, m_ready_bn, ClientApp::PlayerID(), PopulatePlayerList(), and SendUpdate().
Referenced by CompleteConstruction().
Refresh()
void MultiPlayerLobbyWnd::Refresh ()
References HasAuthRole(), m_any_can_edit, m_browse_saves_btn, m_galaxy_setup_panel, m_new_load_game_buttons, m_save_file_text, Networking::ROLE_GALAXY_SETUP, and Networking::ROLE_HOST.
Referenced by CompleteConstruction(), and PopulatePlayerList().
Render()
void MultiPlayerLobbyWnd::Render () override
References CUIWnd::ClientUpperLeft(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PREVIEW_SZ(), CUIWnd::Render(), and ClientUI::WndInnerBorderColor().
SaveGameBrowse()
void MultiPlayerLobbyWnd::SaveGameBrowse () private
References HumanClientApp::GetApp(), m_lobby_data, MultiplayerLobbyData::m_save_game, MultiplayerLobbyData::m_save_game_empire_data, PopulatePlayerList(), HumanClientApp::SelectLoadFile(), and SendUpdate().
Referenced by CompleteConstruction().
SendUpdate()
void MultiPlayerLobbyWnd::SendUpdate () private
References HumanClientApp::GetApp(), Networking::INVALID_PLAYER_ID, LobbyUpdateMessage(), m_lobby_data, ClientApp::Networking(), AIInterface::PlayerID(), and ClientNetworking::SendMessage().
Referenced by AnyCanEdit(), GalaxySetupPanelChanged(), LobbyUpdate(), NewLoadClicked(), PlayerDataChangedLocally(), ReadyClicked(), and SaveGameBrowse().
SizeMove()
void MultiPlayerLobbyWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
TurnPhaseUpdate()
void MultiPlayerLobbyWnd::TurnPhaseUpdate (Message::TurnProgressPhase phase_id)
References m_chat_wnd.
Member Data Documentation
m_any_can_edit
std::shared_ptr<CUIStateButton> MultiPlayerLobbyWnd::m_any_can_edit private
Referenced by AnyCanEdit(), CompleteConstruction(), DoLayout(), LobbyUpdate(), and Refresh().
m_browse_saves_btn
std::shared_ptr<GG::Button> MultiPlayerLobbyWnd::m_browse_saves_btn private
Referenced by CompleteConstruction(), DoLayout(), NewLoadClicked(), and Refresh().
m_cancel_bn
std::shared_ptr<GG::Button> MultiPlayerLobbyWnd::m_cancel_bn private
Referenced by CompleteConstruction(), DoLayout(), and KeyPress().
m_chat_wnd
std::shared_ptr<MessageWnd> MultiPlayerLobbyWnd::m_chat_wnd private
Referenced by ChatMessage(), CleanupChat(), CompleteConstruction(), DoLayout(), GetChatText(), and TurnPhaseUpdate().
m_galaxy_setup_panel
std::shared_ptr<GalaxySetupPanel> MultiPlayerLobbyWnd::m_galaxy_setup_panel private
Referenced by CompleteConstruction(), DoLayout(), GalaxySetupPanelChanged(), LobbyUpdate(), NewLoadClicked(), and Refresh().
m_lobby_data
MultiplayerLobbyData MultiPlayerLobbyWnd::m_lobby_data private
a copy of the most recently received lobby update
Referenced by AnyCanEdit(), ChatMessage(), GalaxySetupPanelChanged(), LobbyUpdate(), NewLoadClicked(), PlayerDataChangedLocally(), PopulatePlayerList(), ReadyClicked(), SaveGameBrowse(), and SendUpdate().
m_new_load_game_buttons
std::shared_ptr<GG::RadioButtonGroup> MultiPlayerLobbyWnd::m_new_load_game_buttons private
Referenced by CompleteConstruction(), DoLayout(), LoadGameSelected(), LobbyUpdate(), and Refresh().
m_players_lb
std::shared_ptr<GG::ListBox> MultiPlayerLobbyWnd::m_players_lb private
Referenced by CompleteConstruction(), DoLayout(), PlayerDataAcceptable(), PlayerDataChangedLocally(), and PopulatePlayerList().
m_players_lb_headers
std::shared_ptr<PlayerLabelRow> MultiPlayerLobbyWnd::m_players_lb_headers private
Referenced by CompleteConstruction(), DoLayout(), and PopulatePlayerList().
m_preview_image
std::shared_ptr<GG::StaticGraphic> MultiPlayerLobbyWnd::m_preview_image private
Referenced by CompleteConstruction(), DoLayout(), and PreviewImageChanged().
m_ready_bn
std::shared_ptr<GG::Button> MultiPlayerLobbyWnd::m_ready_bn private
Referenced by CompleteConstruction(), DoLayout(), KeyPress(), PopulatePlayerList(), and ReadyClicked().
m_save_file_text
std::shared_ptr<GG::Label> MultiPlayerLobbyWnd::m_save_file_text private
Referenced by CompleteConstruction(), DoLayout(), LobbyUpdate(), NewLoadClicked(), and Refresh().
m_start_conditions_text
std::shared_ptr<GG::Label> MultiPlayerLobbyWnd::m_start_conditions_text private
Referenced by CompleteConstruction(), DoLayout(), and PopulatePlayerList().
The documentation for this class was generated from the following files:
MultiplayerLobbyWnd.h
MultiplayerLobbyWnd.cpp