FreeOrion: EncyclopediaDetailPanel Class Reference
EncyclopediaDetailPanel Class Reference
UI class that displays in-game encyclopedic information about game content.
#include <EncyclopediaDetailPanel.h>
Public Member Functions
Structors //!@{
EncyclopediaDetailPanel (GG::Flags< GG::WndFlag > flags=GG::ONTOP|GG::INTERACTIVE|GG::DRAGABLE|GG::RESIZABLE|CLOSABLE|PINABLE, const std::string &config_name="")
void CompleteConstruction () override
virtual ~EncyclopediaDetailPanel ()
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void PreRender () override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void Render () override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
GG::Pt ClientUpperLeft () const override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void AddItem (const std::string &type, const std::string &name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void PopItem ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void ClearItems ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
int GetItemsSize ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetPlanet (int planet_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (std::shared_ptr< const Planet > planet)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetTech (const std::string &tech_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const Tech *tech)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetPartType (const std::string &part_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const PartType *part)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetHullType (const std::string &hull_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const HullType *hull_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetBuildingType (const std::string &building_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const BuildingType *building_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetSpecial (const std::string &special_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const Special *special)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetSpecies (const std::string &species_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const Species *species)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetFieldType (const std::string &field_type_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const FieldType *field_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetObject (int object_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetObject (const std::string &object_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (std::shared_ptr< const UniverseObject > obj)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetEmpire (int empire_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetEmpire (const std::string &empire_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const Empire *empire)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetDesign (int design_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetDesign (const std::string &design_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const ShipDesign *design)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetIncompleteDesign (std::weak_ptr< const ShipDesign > incomplete_design)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetMeterType (const std::string &meter_string)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetItem (const MeterType &meter_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetGraph (const std::string &graph_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetIndex ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void SetEncyclopediaArticle (const std::string &name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void Refresh ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void OnIndex ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void OnBack ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void OnNext ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs the window to be a CUI window.
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
Constructs a CUI window without specifying the initial (default) position, either call InitSizeMove() if the window is positioned by something else or override CalculatePosition() then call ResetDefaultPosition() for windows that position themselves.
void CompleteConstruction () override
Constructs the window to be a CUI window.
virtual ~CUIWnd ()
Virtual destructor.
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void()> ClosingSignal
Protected Member Functions
void InitBuffers () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetText (const std::string &text, bool lookup_in_stringtable=true)
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
Flags options currently at their default values for later use in SaveDefaultedOptions.
void SaveDefaultedOptions ()
Sets the default value any options previously determined from calls to SetDefaultedOptions to their current value.
Private Member Functions
void CloseClicked () override
called when window is closed via the close button
void DoLayout ()
bool EventFilter (GG::Wnd *w, const GG::WndEvent &event) override
void HandleLinkClick (const std::string &link_type, const std::string &data)
void HandleLinkDoubleClick (const std::string &link_type, const std::string &data)
void HandleSearchTextEntered ()
void RefreshImpl ()
Private Attributes
std::shared_ptr< GG::Button > m_back_button = nullptr
std::shared_ptr< GG::Label > m_cost_text = nullptr
std::shared_ptr< GG::RichText > m_description_rich_text = nullptr
std::shared_ptr< GraphControl > m_graph = nullptr
std::shared_ptr< GG::StaticGraphic > m_icon = nullptr
std::weak_ptr< const ShipDesign > m_incomplete_design
std::shared_ptr< GG::Button > m_index_button = nullptr
std::shared_ptr< GG::Label > m_name_text = nullptr
bool m_needs_refresh = false
std::shared_ptr< GG::Button > m_next_button = nullptr
std::shared_ptr< GG::ScrollPanel > m_scroll_panel = nullptr
std::shared_ptr< GG::Edit > m_search_edit = nullptr
std::shared_ptr< GG::Label > m_summary_text = nullptr
Static Private Attributes
static std::list< std::pair< std::string, std::string > > m_items = std::list<std::pair<std::string, std::string>>(0)
static std::list< std::pair< std::string, std::string > >::iterator m_items_it = m_items.begin()
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
UI class that displays in-game encyclopedic information about game content.
Tech, PartType, HullType, BuildingType, ShipDesign, etc.
Constructor & Destructor Documentation
EncyclopediaDetailPanel::EncyclopediaDetailPanel (GG::Flags< GG::WndFlag > flags = GG::ONTOP | GG::INTERACTIVE | GG::DRAGABLE | GG::RESIZABLE | CLOSABLE | PINABLE, const std::string & config_name = "")
EncyclopediaDetailPanel::~EncyclopediaDetailPanel () virtual
Member Function Documentation
void EncyclopediaDetailPanel::AddItem (const std::string & type, const std::string & name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_back_button, m_items, m_items_it, m_next_button, m_scroll_panel, and Refresh().
Referenced by CompleteConstruction(), HandleSearchTextEntered(), OnIndex(), SetBuildingType(), SetDesign(), SetEmpire(), SetEncyclopediaArticle(), SetFieldType(), SetGraph(), SetHullType(), SetIncompleteDesign(), SetIndex(), SetMeterType(), SetObject(), SetPartType(), SetPlanet(), SetSpecial(), SetSpecies(), SetTech(), and SetText().
void EncyclopediaDetailPanel::ClearItems ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_items, m_items_it, m_scroll_panel, and Refresh().
GG::Pt EncyclopediaDetailPanel::ClientUpperLeft () const override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
void EncyclopediaDetailPanel::CloseClicked () override private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal.
void EncyclopediaDetailPanel::CompleteConstruction () override
References AddItem(), ClientUI::ArtDir(), CUIWnd::CompleteConstruction(), ClientUI::CtrlColor(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DESCRIPTION_PADDING(), DoLayout(), TextLinker::ENCYCLOPEDIA_TAG, ClientUI::GetBoldFont(), ClientUI::GetFont(), ClientUI::GetTexture(), HandleLinkClick(), HandleLinkDoubleClick(), HandleSearchTextEntered(), m_back_button, m_cost_text, m_description_rich_text, m_graph, m_index_button, m_name_text, m_next_button, m_scroll_panel, m_search_edit, m_summary_text, OnBack(), OnIndex(), OnNext(), ClientUI::Pts(), CUIWnd::SaveDefaultedOptions(), and ClientUI::TextColor().
void EncyclopediaDetailPanel::DoLayout () private
References CUIWnd::BORDER_BOTTOM, CUIWnd::BORDER_LEFT, CUIWnd::BORDER_RIGHT, SectionedScopedTimer::EnterSection(), m_back_button, CUIWnd::m_close_button, m_cost_text, m_graph, m_icon, m_index_button, m_name_text, m_next_button, m_scroll_panel, m_search_edit, m_summary_text, CUIWnd::PositionButtons(), ClientUI::Pts(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::TEXT_MARGIN_Y().
Referenced by CompleteConstruction(), and PreRender().
bool EncyclopediaDetailPanel::EventFilter (GG::Wnd * w, const GG::WndEvent & event) override private
int EncyclopediaDetailPanel::GetItemsSize () inline
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_items, OnBack(), OnIndex(), OnNext(), Refresh(), SetBuildingType(), SetDesign(), SetEmpire(), SetEncyclopediaArticle(), SetFieldType(), SetGraph(), SetHullType(), SetIncompleteDesign(), SetIndex(), SetItem(), SetMeterType(), SetObject(), SetPartType(), SetPlanet(), SetSpecial(), SetSpecies(), SetTech(), and parse::species().
void EncyclopediaDetailPanel::HandleLinkClick (const std::string & link_type, const std::string & data) private
References TextLinker::BROWSE_PATH_TAG, HumanClientApp::BrowsePath(), VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, ErrorLogger, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, FilenameToPath(), VarText::FLEET_ID_TAG, HumanClientApp::GetApp(), ClientUI::GetClientUI(), GetPredefinedShipDesign(), TextLinker::GRAPH_TAG, VarText::METER_TYPE_TAG, HumanClientApp::OpenURL(), VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, SetBuildingType(), SetDesign(), SetEmpire(), SetFieldType(), SetGraph(), SetHullType(), SetMeterType(), SetPartType(), SetPlanet(), SetSpecial(), SetSpecies(), SetTech(), SetText(), VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, TextLinker::URL_TAG, ClientUI::ZoomToBuilding(), ClientUI::ZoomToCombatLog(), ClientUI::ZoomToField(), ClientUI::ZoomToFleet(), ClientUI::ZoomToPlanet(), ClientUI::ZoomToShip(), and ClientUI::ZoomToSystem().
Referenced by CompleteConstruction().
void EncyclopediaDetailPanel::HandleLinkDoubleClick (const std::string & link_type, const std::string & data) private
References VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, ErrorLogger, VarText::FLEET_ID_TAG, ClientUI::GetClientUI(), GetPredefinedShipDesign(), TextLinker::GRAPH_TAG, VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, SetGraph(), SetText(), VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, ClientUI::ZoomToBuilding(), ClientUI::ZoomToBuildingType(), ClientUI::ZoomToEmpire(), ClientUI::ZoomToFleet(), ClientUI::ZoomToPlanet(), ClientUI::ZoomToShip(), ClientUI::ZoomToShipDesign(), ClientUI::ZoomToShipHull(), ClientUI::ZoomToShipPart(), ClientUI::ZoomToSpecial(), ClientUI::ZoomToSpecies(), ClientUI::ZoomToSystem(), and ClientUI::ZoomToTech().
Referenced by CompleteConstruction().
void EncyclopediaDetailPanel::HandleSearchTextEntered () private
References AddItem(), EncyclopediaArticle::description, OptionsDB::Get(), GetOptionsDB(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetPediaArticle(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSubDirs(), m_search_edit, anonymous_namespace{EncyclopediaDetailPanel.cpp}::TEXT_SEARCH_RESULTS, TraceLogger, and UserString().
Referenced by CompleteConstruction().
void EncyclopediaDetailPanel::InitBuffers () override protected virtual
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Reimplemented from CUIWnd.
References CUIWnd::BORDER_BOTTOM, CUIWnd::BORDER_LEFT, CUIWnd::BORDER_RIGHT, CUIWnd::INNER_BORDER_ANGLE_OFFSET, CUIWnd::m_buffer_indices, m_name_text, CUIWnd::m_resizable, m_summary_text, CUIWnd::m_vertex_buffer, CUIWnd::OUTER_EDGE_ANGLE_OFFSET, CUIWnd::RESIZE_HASHMARK1_OFFSET, and CUIWnd::RESIZE_HASHMARK2_OFFSET.
void EncyclopediaDetailPanel::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_scroll_panel, m_search_edit, and OnBack().
void EncyclopediaDetailPanel::OnBack ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_back_button, m_items, m_items_it, m_next_button, m_scroll_panel, and Refresh().
Referenced by CompleteConstruction(), GetItemsSize(), and KeyPress().
void EncyclopediaDetailPanel::OnIndex ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), and TextLinker::ENCYCLOPEDIA_TAG.
Referenced by CompleteConstruction(), and GetItemsSize().
void EncyclopediaDetailPanel::OnNext ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_back_button, m_items, m_items_it, m_next_button, m_scroll_panel, and Refresh().
Referenced by CompleteConstruction(), and GetItemsSize().
void EncyclopediaDetailPanel::PopItem ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_items, m_items_it, m_scroll_panel, and Refresh().
void EncyclopediaDetailPanel::PreRender () override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References DoLayout(), m_needs_refresh, and RefreshImpl().
void EncyclopediaDetailPanel::Refresh ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References m_needs_refresh.
Referenced by AddItem(), ClearItems(), GetItemsSize(), OnBack(), OnNext(), PopItem(), and SetIncompleteDesign().
void EncyclopediaDetailPanel::RefreshImpl () private
References DoubleToString(), FlexibleFormat(), GetEmpire(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetRefreshDetailPanelInfo(), Universe::GetStatRecords(), GetUniverse(), TextLinker::GRAPH_TAG, m_cost_text, m_description_rich_text, m_graph, m_icon, m_incomplete_design, m_items, m_items_it, m_name_text, m_scroll_panel, m_summary_text, and UserString().
Referenced by PreRender().
void EncyclopediaDetailPanel::Render () override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References CUIWnd::m_buffer_indices, CUIWnd::m_minimized, CUIWnd::m_vertex_buffer, CUIWnd::Render(), and ClientUI::WndInnerBorderColor().
void EncyclopediaDetailPanel::SetBuildingType (const std::string & building_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetDesign (int design_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), INVALID_DESIGN_ID, m_items, m_items_it, and to_string().
Referenced by DesignWnd::CompleteConstruction(), GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetDesign (const std::string & design_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
void EncyclopediaDetailPanel::SetEmpire (int empire_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), ALL_EMPIRES, m_items, m_items_it, and to_string().
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetEmpire (const std::string & empire_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
void EncyclopediaDetailPanel::SetEncyclopediaArticle (const std::string & name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), and TextLinker::ENCYCLOPEDIA_TAG.
Referenced by BuildDesignatorWnd::CompleteConstruction(), and GetItemsSize().
void EncyclopediaDetailPanel::SetFieldType (const std::string & field_type_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetGraph (const std::string & graph_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), and TextLinker::GRAPH_TAG.
Referenced by GetItemsSize(), HandleLinkClick(), and HandleLinkDoubleClick().
void EncyclopediaDetailPanel::SetHullType (const std::string & hull_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetIncompleteDesign (std::weak_ptr< const ShipDesign > incomplete_design)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, anonymous_namespace{EncyclopediaDetailPanel.cpp}::INCOMPLETE_DESIGN, m_incomplete_design, m_items, m_items_it, and Refresh().
Referenced by GetItemsSize().
void EncyclopediaDetailPanel::SetIndex ()
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), and TextLinker::ENCYCLOPEDIA_TAG.
Referenced by GetItemsSize(), and SetText().
void EncyclopediaDetailPanel::SetItem (std::shared_ptr< const Planet > planet)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References INVALID_OBJECT_ID, and SetPlanet().
Referenced by BuildDesignatorWnd::CompleteConstruction(), DesignWnd::CompleteConstruction(), and GetItemsSize().
void EncyclopediaDetailPanel::SetItem (const Tech * tech)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, Tech::Name(), and SetTech().
void EncyclopediaDetailPanel::SetItem (const PartType * part)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, PartType::Name(), and SetPartType().
void EncyclopediaDetailPanel::SetItem (const HullType * hull_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, HullType::Name(), and SetHullType().
void EncyclopediaDetailPanel::SetItem (const BuildingType * building_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, BuildingType::Name(), and SetBuildingType().
void EncyclopediaDetailPanel::SetItem (const Special * special)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, Special::Name(), and SetSpecial().
void EncyclopediaDetailPanel::SetItem (const Species * species)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, Species::Name(), and SetSpecies().
void EncyclopediaDetailPanel::SetItem (const FieldType * field_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING, FieldType::Name(), and SetFieldType().
void EncyclopediaDetailPanel::SetItem (std::shared_ptr< const UniverseObject > obj)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References INVALID_OBJECT_ID, and SetObject().
void EncyclopediaDetailPanel::SetItem (const Empire * empire)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References ALL_EMPIRES, Empire::EmpireID(), and SetEmpire().
void EncyclopediaDetailPanel::SetItem (const ShipDesign * design)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References ShipDesign::ID(), INVALID_DESIGN_ID, and SetDesign().
void EncyclopediaDetailPanel::SetItem (const MeterType & meter_type)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References SetMeterType().
void EncyclopediaDetailPanel::SetMeterType (const std::string & meter_string)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem().
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetObject (int object_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), INVALID_OBJECT_ID, m_items, m_items_it, to_string(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::UNIVERSE_OBJECT.
Referenced by GetItemsSize(), and SetItem().
void EncyclopediaDetailPanel::SetObject (const std::string & object_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, m_items_it, and anonymous_namespace{EncyclopediaDetailPanel.cpp}::UNIVERSE_OBJECT.
void EncyclopediaDetailPanel::SetPartType (const std::string & part_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetPlanet (int planet_id)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), INVALID_OBJECT_ID, m_items, m_items_it, anonymous_namespace{EncyclopediaDetailPanel.cpp}::PLANET_SUITABILITY_REPORT, and to_string().
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetSpecial (const std::string & special_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetSpecies (const std::string & species_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetTech (const std::string & tech_name)
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References AddItem(), m_items, and m_items_it.
Referenced by GetItemsSize(), HandleLinkClick(), and SetItem().
void EncyclopediaDetailPanel::SetText (const std::string & text, bool lookup_in_stringtable = true) protected
References AddItem(), TextLinker::ENCYCLOPEDIA_TAG, m_items, m_items_it, SetIndex(), and UserString().
Referenced by HandleLinkClick(), and HandleLinkDoubleClick().
void EncyclopediaDetailPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Need to redefine this so that icons and name can be put at the top of the Wnd, rather than being restricted to the client area of a CUIWnd.
References CUIWnd::SizeMove().
Member Data Documentation
boost::signals2::signal<void ()> EncyclopediaDetailPanel::ClosingSignal mutable
Referenced by CloseClicked().
std::shared_ptr<GG::Button> EncyclopediaDetailPanel::m_back_button = nullptr private
Referenced by AddItem(), CompleteConstruction(), DoLayout(), OnBack(), and OnNext().
std::shared_ptr<GG::Label> EncyclopediaDetailPanel::m_cost_text = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and RefreshImpl().
std::shared_ptr<GG::RichText> EncyclopediaDetailPanel::m_description_rich_text = nullptr private
Referenced by CompleteConstruction(), and RefreshImpl().
std::shared_ptr<GraphControl> EncyclopediaDetailPanel::m_graph = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and RefreshImpl().
std::shared_ptr<GG::StaticGraphic> EncyclopediaDetailPanel::m_icon = nullptr private
Referenced by DoLayout(), and RefreshImpl().
std::weak_ptr<const ShipDesign> EncyclopediaDetailPanel::m_incomplete_design private
Referenced by RefreshImpl(), and SetIncompleteDesign().
std::shared_ptr<GG::Button> EncyclopediaDetailPanel::m_index_button = nullptr private
Referenced by CompleteConstruction(), and DoLayout().
std::list< std::pair< std::string, std::string > > EncyclopediaDetailPanel::m_items = std::list<std::pair<std::string, std::string>>(0) static private
Referenced by AddItem(), ClearItems(), GetItemsSize(), OnBack(), OnNext(), PopItem(), RefreshImpl(), SetBuildingType(), SetDesign(), SetEmpire(), SetFieldType(), SetHullType(), SetIncompleteDesign(), SetObject(), SetPartType(), SetPlanet(), SetSpecial(), SetSpecies(), SetTech(), and SetText().
std::list< std::pair< std::string, std::string > >::iterator EncyclopediaDetailPanel::m_items_it = m_items.begin() static private
Referenced by AddItem(), ClearItems(), OnBack(), OnNext(), PopItem(), RefreshImpl(), SetBuildingType(), SetDesign(), SetEmpire(), SetFieldType(), SetHullType(), SetIncompleteDesign(), SetObject(), SetPartType(), SetPlanet(), SetSpecial(), SetSpecies(), SetTech(), and SetText().
std::shared_ptr<GG::Label> EncyclopediaDetailPanel::m_name_text = nullptr private
Referenced by CompleteConstruction(), DoLayout(), InitBuffers(), and RefreshImpl().
bool EncyclopediaDetailPanel::m_needs_refresh = false private
Referenced by PreRender(), and Refresh().
std::shared_ptr<GG::Button> EncyclopediaDetailPanel::m_next_button = nullptr private
Referenced by AddItem(), CompleteConstruction(), DoLayout(), OnBack(), and OnNext().
std::shared_ptr<GG::ScrollPanel> EncyclopediaDetailPanel::m_scroll_panel = nullptr private
Referenced by AddItem(), ClearItems(), CompleteConstruction(), DoLayout(), KeyPress(), OnBack(), OnNext(), PopItem(), and RefreshImpl().
std::shared_ptr<GG::Edit> EncyclopediaDetailPanel::m_search_edit = nullptr private
Referenced by CompleteConstruction(), DoLayout(), HandleSearchTextEntered(), and KeyPress().
std::shared_ptr<GG::Label> EncyclopediaDetailPanel::m_summary_text = nullptr private
Referenced by CompleteConstruction(), DoLayout(), InitBuffers(), and RefreshImpl().
The documentation for this class was generated from the following files:
EncyclopediaDetailPanel.h
EncyclopediaDetailPanel.cpp