FreeOrion: EmpireManager Class Reference
EmpireManager Class Reference
Maintains all of the Empire objects that exist in the application.
#include <EmpireManager.h>
Public Types
typedef std::map< int, Empire * >::const_iterator const_iterator
Const Iterator over Empires.
typedef boost::signals2::signal< void(int, int)> DiploSignalType
typedef std::map< int, Empire * >::iterator iterator
Iterator over Empires.
Public Member Functions
Structors
EmpireManager ()
assignment operator (move semantics)
virtual ~EmpireManager ()
assignment operator (move semantics)
const EmpireManager & operator= (EmpireManager &rhs)
assignment operator (move semantics)
Accessors
const Empire * GetEmpire (int id) const
Returns the empire whose ID is ID, or 0 if none exists.
std::shared_ptr< const UniverseObject > GetSource (int id) const
Return the empire source or nullptr if the empire or source doesn't exist.
const std::string & GetEmpireName (int id) const
Returns the empire whose ID is ID, or 0 if none exists.
const_iterator begin () const
Returns the empire whose ID is ID, or 0 if none exists.
const_iterator end () const
Returns the empire whose ID is ID, or 0 if none exists.
int NumEmpires () const
Returns the empire whose ID is ID, or 0 if none exists.
int NumEliminatedEmpires () const
Returns the empire whose ID is ID, or 0 if none exists.
DiplomaticStatus GetDiplomaticStatus (int empire1, int empire2) const
Returns the empire whose ID is ID, or 0 if none exists.
std::set< int > GetEmpireIDsWithDiplomaticStatusWithEmpire (int empire_id, DiplomaticStatus diplo_status) const
Returns the empire whose ID is ID, or 0 if none exists.
bool DiplomaticMessageAvailable (int sender_id, int recipient_id) const
Returns the empire whose ID is ID, or 0 if none exists.
const DiplomaticMessage & GetDiplomaticMessage (int sender_id, int recipient_id) const
Returns the empire whose ID is ID, or 0 if none exists.
std::string Dump () const
Returns the empire whose ID is ID, or 0 if none exists.
Mutators
Empire * GetEmpire (int id)
Returns the empire whose ID is id, or 0 if none exists.
iterator begin ()
Returns the empire whose ID is id, or 0 if none exists.
iterator end ()
Returns the empire whose ID is id, or 0 if none exists.
void BackPropagateMeters ()
Returns the empire whose ID is id, or 0 if none exists.
void SetDiplomaticStatus (int empire1, int empire2, DiplomaticStatus status)
Returns the empire whose ID is id, or 0 if none exists.
void HandleDiplomaticMessage (const DiplomaticMessage &message)
Returns the empire whose ID is id, or 0 if none exists.
void SetDiplomaticMessage (const DiplomaticMessage &message)
Returns the empire whose ID is id, or 0 if none exists.
void RemoveDiplomaticMessage (int sender_id, int recipient_id)
Returns the empire whose ID is id, or 0 if none exists.
void ResetDiplomacy ()
Returns the empire whose ID is id, or 0 if none exists.
Empire * CreateEmpire (int empire_id, const std::string &name, const std::string &player_name, const GG::Clr &color, bool authenticated)
Creates and inserts an empire with the specified properties and returns a pointer to it.
void Clear ()
Removes and deletes all empires from the manager.
Public Attributes
DiploSignalType DiplomaticMessageChangedSignal
DiploSignalType DiplomaticStatusChangedSignal
Private Member Functions
std::string DumpDiplomacy () const
void GetDiplomaticMessagesToSerialize (std::map< std::pair< int, int >, DiplomaticMessage > &messages, int encoding_empire) const
void InsertEmpire (Empire *empire)
Adds the given empire to the manager.
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::map< std::pair< int, int >, DiplomaticMessage > m_diplomatic_messages
std::map< std::pair< int, int >, DiplomaticStatus > m_empire_diplomatic_statuses
std::map< int, Empire * > m_empire_map
Friends
class boost::serialization::access
class ClientApp
class ServerApp
Detailed Description
Maintains all of the Empire objects that exist in the application.
Member Typedef Documentation
const_iterator
typedef std::map<int, Empire*>::const_iterator EmpireManager::const_iterator
Const Iterator over Empires.
DiploSignalType
typedef boost::signals2::signal<void (int, int)> EmpireManager::DiploSignalType
iterator
typedef std::map<int, Empire*>::iterator EmpireManager::iterator
Iterator over Empires.
Constructor & Destructor Documentation
EmpireManager()
EmpireManager::EmpireManager ()
assignment operator (move semantics)
~EmpireManager()
EmpireManager::~EmpireManager () virtual
assignment operator (move semantics)
Member Function Documentation
BackPropagateMeters()
void EmpireManager::BackPropagateMeters ()
Returns the empire whose ID is id, or 0 if none exists.
Referenced by ServerApp::GenerateUniverse(), and Empire::meter_end().
begin() [1/2]
EmpireManager::const_iterator EmpireManager::begin () const
Returns the empire whose ID is ID, or 0 if none exists.
begin() [2/2]
EmpireManager::iterator EmpireManager::begin ()
Returns the empire whose ID is id, or 0 if none exists.
Clear()
void EmpireManager::Clear ()
Removes and deletes all empires from the manager.
Referenced by LoadGame(), ServerApp::NewGameInitConcurrentWithJoiners(), and HumanClientApp::ResetClientData().
CreateEmpire()
Empire * EmpireManager::CreateEmpire (int empire_id, const std::string & name, const std::string & player_name, const GG::Clr & color, bool authenticated)
Creates and inserts an empire with the specified properties and returns a pointer to it.
This will only set up the data in Empire. It is the caller's responsibility to make sure that universe updates planet ownership.
Referenced by InitEmpires().
DiplomaticMessageAvailable()
bool EmpireManager::DiplomaticMessageAvailable (int sender_id, int recipient_id) const
Returns the empire whose ID is ID, or 0 if none exists.
References DiplomaticMessage::INVALID_DIPLOMATIC_MESSAGE_TYPE.
Dump()
std::string EmpireManager::Dump () const
Returns the empire whose ID is ID, or 0 if none exists.
DumpDiplomacy()
std::string EmpireManager::DumpDiplomacy () const private
References GetEmpire(), DiplomaticMessage::INVALID_DIPLOMATIC_MESSAGE_TYPE, Empire::Name(), and to_string().
end() [1/2]
EmpireManager::const_iterator EmpireManager::end () const
Returns the empire whose ID is ID, or 0 if none exists.
end() [2/2]
EmpireManager::iterator EmpireManager::end ()
Returns the empire whose ID is id, or 0 if none exists.
GetDiplomaticMessage()
const DiplomaticMessage & EmpireManager::GetDiplomaticMessage (int sender_id, int recipient_id) const
Returns the empire whose ID is ID, or 0 if none exists.
Referenced by PlayerListWnd::HandleDiplomaticMessageChange(), ServerApp::HandleDiplomaticMessageChange(), PlayerListWnd::PlayerRightClicked(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
GetDiplomaticMessagesToSerialize()
void EmpireManager::GetDiplomaticMessagesToSerialize (std::map< std::pair< int, int >, DiplomaticMessage > & messages, int encoding_empire) const private
References ALL_EMPIRES.
GetDiplomaticStatus()
DiplomaticStatus EmpireManager::GetDiplomaticStatus (int empire1, int empire2) const
Returns the empire whose ID is ID, or 0 if none exists.
References ALL_EMPIRES, anonymous_namespace{EmpireManager.cpp}::DiploKey(), and ErrorLogger.
Referenced by Fleet::BlockadedAtSystem(), InvadeOrder::Check(), BombardOrder::Check(), GiveObjectToEmpireOrder::Check(), ServerApp::CheckForEmpireElimination(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), Effect::GenerateSitRepMessage::Execute(), Effect::SetVisibility::Execute(), FleetWnd::FleetRightClicked(), SupplyManager::FleetSupplyableSystemIDs(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), MessageWnd::HandleDiplomaticStatusChange(), ServerApp::HandleDiplomaticStatusChange(), Fighter::HostileToEmpire(), Ship::HostileToEmpire(), Building::HostileToEmpire(), Fleet::HostileToEmpire(), Planet::HostileToEmpire(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), PlayerListWnd::PlayerRightClicked(), SidePanel::PlanetPanel::RClick(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), and Empire::UpdateSupplyUnobstructedSystems().
GetEmpire() [1/2]
const Empire * EmpireManager::GetEmpire (int id) const
Returns the empire whose ID is ID, or 0 if none exists.
Referenced by ServerApp::AddPlayerIntoGame(), ServerApp::GetEmpire(), ClientApp::GetEmpire(), HumanClientApp::ResetOrExitApp(), Empire::serialize(), and ClientApp::SetEmpireStatus().
GetEmpire() [2/2]
Empire * EmpireManager::GetEmpire (int id)
Returns the empire whose ID is id, or 0 if none exists.
GetEmpireIDsWithDiplomaticStatusWithEmpire()
std::set< int > EmpireManager::GetEmpireIDsWithDiplomaticStatusWithEmpire (int empire_id, DiplomaticStatus diplo_status) const
Returns the empire whose ID is ID, or 0 if none exists.
References ALL_EMPIRES.
Referenced by SupplyManager::SystemHasFleetSupply(), and SupplyManager::Update().
GetEmpireName()
const std::string & EmpireManager::GetEmpireName (int id) const
Returns the empire whose ID is ID, or 0 if none exists.
References anonymous_namespace{EmpireManager.cpp}::EMPTY_STRING.
Referenced by UniverseObject::Dump().
GetSource()
std::shared_ptr< const UniverseObject > EmpireManager::GetSource (int id) const
Return the empire source or nullptr if the empire or source doesn't exist.
Referenced by BuildingType::EnqueueLocation(), BuildingType::ProductionCost(), PartType::ProductionCost(), HullType::ProductionCost(), BuildingType::ProductionLocation(), BuildingType::ProductionTime(), PartType::ProductionTime(), HullType::ProductionTime(), Tech::ResearchCost(), and Tech::ResearchTime().
HandleDiplomaticMessage()
void EmpireManager::HandleDiplomaticMessage (const DiplomaticMessage & message)
Returns the empire whose ID is id, or 0 if none exists.
References DiplomaticMessage::ACCEPT_ALLIES_PROPOSAL, DiplomaticMessage::ACCEPT_PEACE_PROPOSAL, DiplomaticMessage::ALLIES_PROPOSAL, DiplomaticMessage::CANCEL_PROPOSAL, DiplomaticMessage::END_ALLIANCE_DECLARATION, DiplomaticMessage::GetType(), DiplomaticMessage::IsAllowed(), DiplomaticMessage::PEACE_PROPOSAL, DiplomaticMessage::RecipientEmpireID(), DiplomaticMessage::REJECT_PROPOSAL, DiplomaticMessage::SenderEmpireID(), and DiplomaticMessage::WAR_DECLARATION.
Referenced by WaitingForMPGameJoiners::react().
InsertEmpire()
void EmpireManager::InsertEmpire (Empire * empire) private
Adds the given empire to the manager.
References Empire::EmpireID(), and ErrorLogger.
NumEliminatedEmpires()
int EmpireManager::NumEliminatedEmpires () const
Returns the empire whose ID is ID, or 0 if none exists.
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout().
NumEmpires()
int EmpireManager::NumEmpires () const
Returns the empire whose ID is ID, or 0 if none exists.
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout().
operator=()
const EmpireManager & EmpireManager::operator= (EmpireManager & rhs)
assignment operator (move semantics)
References m_diplomatic_messages, m_empire_diplomatic_statuses, and m_empire_map.
RemoveDiplomaticMessage()
void EmpireManager::RemoveDiplomaticMessage (int sender_id, int recipient_id)
Returns the empire whose ID is id, or 0 if none exists.
References DiplomaticMessage::INVALID_DIPLOMATIC_MESSAGE_TYPE.
ResetDiplomacy()
void EmpireManager::ResetDiplomacy ()
Returns the empire whose ID is id, or 0 if none exists.
References anonymous_namespace{EmpireManager.cpp}::DiploKey().
Referenced by InitEmpires().
serialize()
template<class Archive > template void EmpireManager::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References anonymous_namespace{SerializeEmpire.cpp}::DiploKey(), ErrorLogger, and GetUniverse().
SetDiplomaticMessage()
void EmpireManager::SetDiplomaticMessage (const DiplomaticMessage & message)
Returns the empire whose ID is id, or 0 if none exists.
References DiplomaticMessage::RecipientEmpireID(), and DiplomaticMessage::SenderEmpireID().
Referenced by PlayingGame::react().
SetDiplomaticStatus()
void EmpireManager::SetDiplomaticStatus (int empire1, int empire2, DiplomaticStatus status)
Returns the empire whose ID is id, or 0 if none exists.
References anonymous_namespace{EmpireManager.cpp}::DiploKey().
Referenced by InitEmpires(), and PlayingGame::react().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
ClientApp
friend class ClientApp friend
ServerApp
friend class ServerApp friend
Member Data Documentation
DiplomaticMessageChangedSignal
DiploSignalType EmpireManager::DiplomaticMessageChangedSignal mutable
Referenced by PlayerListWnd::CompleteConstruction(), and ServerApp::ServerApp().
DiplomaticStatusChangedSignal
DiploSignalType EmpireManager::DiplomaticStatusChangedSignal mutable
Referenced by PlayerListWnd::CompleteConstruction(), MessageWnd::CompleteConstruction(), and ServerApp::ServerApp().
m_diplomatic_messages
std::map<std::pair<int, int>, DiplomaticMessage> EmpireManager::m_diplomatic_messages private
Referenced by operator=().
m_empire_diplomatic_statuses
std::map<std::pair<int, int>, DiplomaticStatus> EmpireManager::m_empire_diplomatic_statuses private
Referenced by operator=().
m_empire_map
std::map<int, Empire*> EmpireManager::m_empire_map private
Referenced by operator=().
The documentation for this class was generated from the following files:
EmpireManager.h
EmpireManager.cpp
SerializeEmpire.cpp