FreeOrion: anonymous_namespace{ProductionWnd.cpp}::QuantLabel Class Reference
anonymous_namespace{ProductionWnd.cpp}::QuantLabel Class Reference
Public Member Functions
QuantLabel (int quantity, int designID, GG::X nwidth, GG::Y h, bool inProgress, bool amBlockType)
void CompleteConstruction () override
void Render () override
Public Attributes
std::shared_ptr< CUILabel > m_text
Constructor & Destructor Documentation
QuantLabel()
anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel (int quantity, int designID, GG::X nwidth, GG::Y h, bool inProgress, bool amBlockType) inline
References FlexibleFormat(), ClientUI::ResearchableTechTextAndBorderColor(), and UserString().
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{ProductionWnd.cpp}::QuantLabel::CompleteConstruction () inline override
Render()
void anonymous_namespace{ProductionWnd.cpp}::QuantLabel::Render () inline override
Member Data Documentation
m_text
std::shared_ptr<CUILabel> anonymous_namespace{ProductionWnd.cpp}::QuantLabel::m_text
The documentation for this class was generated from the following file:
ProductionWnd.cpp