FreeOrion: anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager Class Reference
anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager Class Reference
DisplayedShipDesignManager allows for the storage and manipulation of an ordered list of design ids that are used to order the display of ShipDesigns in the DesignWnd and the ProductionWnd.
Public Member Functions
DisplayedShipDesignManager ()
std::vector< int > AllOrderedIDs () const
Return all ids including obsoleted designs.
void InsertBefore (const int id, const int next_id)
void InsertHullBefore (const std::string &id, const std::string &next_id="")
template<typename T >
void InsertOrderedIDs (const T &new_order)
boost::optional< int > IsHullObsolete (const std::string &hull) const
Return UI event number that obsoletes hull if it is obsolete.
bool IsKnown (const int id) const
boost::optional< bool > IsObsolete (const int id) const
Return true if design id is obsolete or boost::none if id is not in the manager.
boost::optional< int > IsPartObsolete (const std::string &part) const
Return UI event number that obsoletes part if it is obsolete.
void Load (const int obsolete_ui_event_count, const std::vector< std::pair< int, boost::optional< std::pair< bool, int >>>> &design_ids_and_obsoletes, const std::vector< std::pair< std::string, std::pair< bool, int >>> &hulls_and_obsoletes, const std::unordered_map< std::string, int > &obsolete_parts)
bool MoveBefore (const int moved_id, const int next_id)
std::vector< std::string > OrderedHulls () const
Return non-obsolete available hulls.
std::vector< int > OrderedIDs () const override
Return non-obsolete available ordered ids.
void Remove (const int id)
void Save (int &obsolete_ui_event_count, std::vector< std::pair< int, boost::optional< std::pair< bool, int >>>> &design_ids_and_obsoletes, std::vector< std::pair< std::string, std::pair< bool, int >>> &hulls_and_obsoletes, std::unordered_map< std::string, int > &obsolete_parts)
Save modifies each of its parameters to store obsolete and ordering data in the UI save data.
void SetHullObsolete (const std::string &hull, const bool obsolete)
Set hull's obsolescence to obsolete.
void SetObsolete (const int id, const bool obsolete)
If id is in manager, set id's obsolescence to obsolete.
void SetPartObsolete (const std::string &part, const bool obsolete)
Set part's obsolescence to obsolete.
Private Member Functions
int NextUIObsoleteEvent ()
Private Attributes
std::unordered_map< std::string, std::pair< std::pair< bool, int >, std::list< std::string >::const_iterator > > m_hull_to_obsolete_and_loc
std::unordered_map< int, std::pair< boost::optional< std::pair< bool, int > >, std::list< int >::const_iterator > > m_id_to_obsolete_and_loc
std::unordered_map< std::string, int > m_obsolete_parts
int m_obsolete_ui_event_count = 1
std::list< int > m_ordered_design_ids
std::list< std::string > m_ordered_hulls
Detailed Description
DisplayedShipDesignManager allows for the storage and manipulation of an ordered list of design ids that are used to order the display of ShipDesigns in the DesignWnd and the ProductionWnd.
Constructor & Destructor Documentation
anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::DisplayedShipDesignManager () inline
Member Function Documentation
std::vector< int > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::AllOrderedIDs () const
Return all ids including obsoleted designs.
Referenced by anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns().
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::InsertBefore (const int id, const int next_id)
References ErrorLogger, INVALID_DESIGN_ID, and WarnLogger.
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::InsertHullBefore (const std::string & id, const std::string & next_id = "")
References ErrorLogger.
Referenced by EmptyHullsListBox::QueueItemMoved().
template<typename T > void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::InsertOrderedIDs (const T & new_order)
References INVALID_DESIGN_ID.
boost::optional< int > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsHullObsolete (const std::string & hull) const
Return UI event number that obsoletes hull if it is obsolete.
bool anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsKnown (const int id) const
boost::optional< bool > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsObsolete (const int id) const
Return true if design id is obsolete or boost::none if id is not in the manager.
References ErrorLogger, and GetShipDesign().
boost::optional< int > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsPartObsolete (const std::string & part) const
Return UI event number that obsoletes part if it is obsolete.
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::Load (const int obsolete_ui_event_count, const std::vector< std::pair< int, boost::optional< std::pair< bool, int >>>> & design_ids_and_obsoletes, const std::vector< std::pair< std::string, std::pair< bool, int >>> & hulls_and_obsoletes, const std::unordered_map< std::string, int > & obsolete_parts)
References ErrorLogger.
Referenced by ShipDesignManager::Load().
bool anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::MoveBefore (const int moved_id, const int next_id)
References ErrorLogger, and INVALID_DESIGN_ID.
Referenced by CompletedDesignsListBox::BaseRightClicked(), and CompletedDesignsListBox::QueueItemMoved().
int anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::NextUIObsoleteEvent () private
References ErrorLogger.
std::vector< std::string > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::OrderedHulls () const
Return non-obsolete available hulls.
std::vector< int > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::OrderedIDs () const override virtual
Return non-obsolete available ordered ids.
Implements ShipDesignManager::Designs.
References anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), and anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager().
Referenced by CompletedDesignsListBox::BaseRightClicked().
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::Remove (const int id)
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::Save (int & obsolete_ui_event_count, std::vector< std::pair< int, boost::optional< std::pair< bool, int >>>> & design_ids_and_obsoletes, std::vector< std::pair< std::string, std::pair< bool, int >>> & hulls_and_obsoletes, std::unordered_map< std::string, int > & obsolete_parts)
Save modifies each of its parameters to store obsolete and ordering data in the UI save data.
References ErrorLogger.
Referenced by ShipDesignManager::Save().
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::SetHullObsolete (const std::string & hull, const bool obsolete)
Set hull's obsolescence to obsolete.
References ErrorLogger.
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::SetObsolete (const int id, const bool obsolete)
If id is in manager, set id's obsolescence to obsolete.
void anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::SetPartObsolete (const std::string & part, const bool obsolete)
Set part's obsolescence to obsolete.
Member Data Documentation
std::unordered_map<std::string, std::pair<std::pair<bool, int>, std::list<std::string>::const_iterator> > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_hull_to_obsolete_and_loc private
std::unordered_map<int, std::pair<boost::optional<std::pair<bool, int> >, std::list<int>::const_iterator> > anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_id_to_obsolete_and_loc private
std::unordered_map<std::string, int> anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_obsolete_parts private
int anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_obsolete_ui_event_count = 1 private
std::list<int> anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_ordered_design_ids private
std::list<std::string> anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::m_ordered_hulls private
The documentation for this class was generated from the following file:
DesignWnd.cpp