FreeOrion: OwnerColoredSystemName Class Reference
OwnerColoredSystemName Class Reference
A label like GG::Control that displays the name of a system in the color(s) of the owning empire(s).
#include <SystemIcon.h>
Public Member Functions
OwnerColoredSystemName (int system_id, int font_size, bool blank_unexplored_and_none)
void CompleteConstruction () override
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
std::shared_ptr< GG::TextControl > m_text
Detailed Description
A label like GG::Control that displays the name of a system in the color(s) of the owning empire(s).
This class is derived from GG::Control because GG::ListBox::Row accepts GG::Control but not GG::Wnd being added to them. OwnerColoredSystemName are added to the list of systems on the SidePanel.
Constructor & Destructor Documentation
OwnerColoredSystemName()
OwnerColoredSystemName::OwnerColoredSystemName (int system_id, int font_size, bool blank_unexplored_and_none)
References anonymous_namespace{SystemIcon.cpp}::ColorNameByOwners(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ObjectMap::find(), ObjectMap::get(), HumanClientApp::GetApp(), ClientUI::GetBoldFont(), GetEmpire(), ClientUI::GetFont(), GetOptionsDB(), SpeciesManager::GetSpeciesHomeworldsMap(), GetSpeciesManager(), GetUniverse(), UniverseObject::ID(), m_text, Objects(), ClientUI::SystemNameTextColor(), TAG_SHIPYARD, ClientUI::TextColor(), and to_string().
Member Function Documentation
CompleteConstruction()
void OwnerColoredSystemName::CompleteConstruction () override
References ErrorLogger, and m_text.
Render()
void OwnerColoredSystemName::Render () override
SizeMove()
void OwnerColoredSystemName::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Member Data Documentation
m_text
std::shared_ptr<GG::TextControl> OwnerColoredSystemName::m_text private
Referenced by CompleteConstruction(), and OwnerColoredSystemName().
The documentation for this class was generated from the following files:
SystemIcon.h
SystemIcon.cpp