FreeOrion: DesignWnd::BaseSelector Class Reference
DesignWnd::BaseSelector Class Reference
Public Types
enum BaseSelectorTab : std::size_t {
BaseSelectorTab::Hull, BaseSelectorTab::Current, BaseSelectorTab::Saved, BaseSelectorTab::Monster,
BaseSelectorTab::All
}
Public Member Functions
Structors
BaseSelector (const std::string &config_name)
void CompleteConstruction () override
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Reset ()
void ToggleAvailability (const Availability::Enum type)
void SetEmpireShown (int empire_id, bool refresh_list)
void EnableOrderIssuing (bool enable)
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
void CompleteConstruction () override
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void(const ShipDesign *)> DesignClickedSignal
boost::signals2::signal< void(const std::string &, const std::vector< std::string > &)> DesignComponentsSelectedSignal
boost::signals2::signal< void(int)> DesignSelectedSignal
boost::signals2::signal< void(const HullType *)> HullClickedSignal
boost::signals2::signal< void(const boost::uuids::uuid &)> SavedDesignSelectedSignal
boost::signals2::signal< void(const BaseSelectorTab)> TabChangedSignal
Private Member Functions
void DoLayout ()
Private Attributes
std::shared_ptr< AllDesignsListBox > m_all_list = nullptr
std::tuple< std::shared_ptr< CUIStateButton >, std::shared_ptr< CUIStateButton >, std::shared_ptr< CUIStateButton > > m_availabilities_buttons
AvailabilityManager m_availabilities_state {false, true, false}
std::shared_ptr< CompletedDesignsListBox > m_designs_list = nullptr
std::shared_ptr< EmptyHullsListBox > m_hulls_list = nullptr
std::shared_ptr< MonstersListBox > m_monsters_list = nullptr
std::shared_ptr< SavedDesignsListBox > m_saved_designs_list = nullptr
std::shared_ptr< GG::TabWnd > m_tabs = nullptr
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
void SaveDefaultedOptions ()
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Member Enumeration Documentation
enum DesignWnd::BaseSelector::BaseSelectorTab : std::size_t strong
Enumerator
Hull
Current
Saved
Monster
All
Constructor & Destructor Documentation
DesignWnd::BaseSelector::BaseSelector (const std::string & config_name)
Member Function Documentation
void DesignWnd::BaseSelector::CompleteConstruction () override
References Availability::Available, anonymous_namespace{DesignWnd.cpp}::COMPLETE_DESIGN_ROW_DROP_STRING, CUIWnd::CompleteConstruction(), DesignClickedSignal, DesignComponentsSelectedSignal, DesignSelectedSignal, DoLayout(), Availability::Future, ClientUI::GetFont(), anonymous_namespace{DesignWnd.cpp}::HULL_PARTS_ROW_DROP_TYPE_STRING, HullClickedSignal, m_all_list, m_availabilities_buttons, m_availabilities_state, m_designs_list, m_hulls_list, m_monsters_list, m_saved_designs_list, m_tabs, Availability::Obsolete, Reset(), anonymous_namespace{DesignWnd.cpp}::SAVED_DESIGN_ROW_DROP_STRING, SavedDesignSelectedSignal, CUIWnd::SaveDefaultedOptions(), ClientUI::TextColor(), ToggleAvailability(), UserString(), and ClientUI::WndColor().
void DesignWnd::BaseSelector::DoLayout () private
References m_availabilities_buttons, m_tabs, and ClientUI::Pts().
Referenced by CompleteConstruction(), and SizeMove().
void DesignWnd::BaseSelector::EnableOrderIssuing (bool enable)
References m_designs_list, m_hulls_list, m_monsters_list, and m_saved_designs_list.
void DesignWnd::BaseSelector::Reset ()
References All, Current, ClientApp::EmpireID(), HumanClientApp::GetApp(), Hull, m_tabs, Monster, Saved, SetEmpireShown(), and TabChangedSignal.
Referenced by DesignWnd::CompleteConstruction(), and CompleteConstruction().
void DesignWnd::BaseSelector::SetEmpireShown (int empire_id, bool refresh_list)
References m_designs_list, m_hulls_list, and m_saved_designs_list.
Referenced by Reset().
void DesignWnd::BaseSelector::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout(), and CUIWnd::SizeMove().
void DesignWnd::BaseSelector::ToggleAvailability (const Availability::Enum type)
References Availability::Available, Availability::Future, m_availabilities_buttons, m_availabilities_state, m_designs_list, m_hulls_list, m_saved_designs_list, and Availability::Obsolete.
Referenced by CompleteConstruction().
Member Data Documentation
boost::signals2::signal<void (const ShipDesign*)> DesignWnd::BaseSelector::DesignClickedSignal mutable
Referenced by CompleteConstruction().
boost::signals2::signal<void (const std::string&, const std::vector<std::string>&)> DesignWnd::BaseSelector::DesignComponentsSelectedSignal mutable
Referenced by CompleteConstruction().
boost::signals2::signal<void (int)> DesignWnd::BaseSelector::DesignSelectedSignal mutable
Referenced by CompleteConstruction().
boost::signals2::signal<void (const HullType*)> DesignWnd::BaseSelector::HullClickedSignal mutable
Referenced by CompleteConstruction().
std::shared_ptr<AllDesignsListBox> DesignWnd::BaseSelector::m_all_list = nullptr private
Referenced by CompleteConstruction().
std::tuple<std::shared_ptr<CUIStateButton>, std::shared_ptr<CUIStateButton>, std::shared_ptr<CUIStateButton> > DesignWnd::BaseSelector::m_availabilities_buttons private
Referenced by CompleteConstruction(), DoLayout(), and ToggleAvailability().
AvailabilityManager DesignWnd::BaseSelector::m_availabilities_state {false, true, false} private
Referenced by CompleteConstruction(), and ToggleAvailability().
std::shared_ptr<CompletedDesignsListBox> DesignWnd::BaseSelector::m_designs_list = nullptr private
Referenced by CompleteConstruction(), EnableOrderIssuing(), SetEmpireShown(), and ToggleAvailability().
std::shared_ptr<EmptyHullsListBox> DesignWnd::BaseSelector::m_hulls_list = nullptr private
Referenced by CompleteConstruction(), EnableOrderIssuing(), SetEmpireShown(), and ToggleAvailability().
std::shared_ptr<MonstersListBox> DesignWnd::BaseSelector::m_monsters_list = nullptr private
Referenced by CompleteConstruction(), and EnableOrderIssuing().
std::shared_ptr<SavedDesignsListBox> DesignWnd::BaseSelector::m_saved_designs_list = nullptr private
Referenced by CompleteConstruction(), EnableOrderIssuing(), SetEmpireShown(), and ToggleAvailability().
std::shared_ptr<GG::TabWnd> DesignWnd::BaseSelector::m_tabs = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and Reset().
boost::signals2::signal<void (const boost::uuids::uuid&)> DesignWnd::BaseSelector::SavedDesignSelectedSignal mutable
Referenced by CompleteConstruction().
boost::signals2::signal<void (const BaseSelectorTab)> DesignWnd::BaseSelector::TabChangedSignal mutable
Referenced by Reset().
The documentation for this class was generated from the following file:
DesignWnd.cpp