FreeOrion: TextLinker Class Reference
TextLinker Class Reference abstract
#include <LinkText.h>
Classes
struct Link
Public Member Functions
void SetDecorator (const std::string &link_type, LinkDecorator *decorator)
Sets the link decorator for a link type.
Structors
TextLinker ()
virtual ~TextLinker ()
Public Attributes
boost::signals2::signal< void(const std::string &, const std::string &)> LinkClickedSignal
boost::signals2::signal< void(const std::string &, const std::string &)> LinkDoubleClickedSignal
boost::signals2::signal< void(const std::string &, const std::string &)> LinkRightClickedSignal
Static Public Attributes
static const std::string BROWSE_PATH_TAG
Tag for clickable link to open users file manager at a specified directory.
static const std::string ENCYCLOPEDIA_TAG
static const std::string GRAPH_TAG
static const std::string URL_TAG
Protected Member Functions
void FindLinks ()
finds the links in the text, with which to populate m_links.
virtual const std::shared_ptr< GG::Font > & GetFont () const =0
virtual const std::vector< GG::Font::LineData > & GetLineData () const =0
int GetLinkUnderPt (const GG::Pt &pt)
returns the index of the link under screen coordinate pt, or -1 if none
void LClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LDoubleClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LocateLinks ()
calculates the physical locations of the links in m_links
void MarkLinks ()
wraps text for each link in text formatting tags so that the links appear visually distinct from other text
void MouseHere_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void MouseLeave_ ()
virtual const std::string & RawText () const =0
returns text being displayed before any link formatting is added
void RClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void Render_ ()
virtual void SetLinkedText (const std::string &str)=0
virtual GG::Pt TextLowerRight () const =0
virtual GG::Pt TextUpperLeft () const =0
Private Member Functions
std::string LinkDefaultFormatTag (const Link &link, const std::string &content) const
std::string LinkRolloverFormatTag (const Link &link, const std::string &content) const
Private Attributes
std::map< std::string, LinkDecoratorPtr > m_decorators
std::vector< Link > m_links
int m_rollover_link
Static Private Attributes
static const LinkDecorator DEFAULT_DECORATOR
Constructor & Destructor Documentation
TextLinker()
TextLinker::TextLinker ()
References RegisterLinkTags().
~TextLinker()
TextLinker::~TextLinker () virtual
Member Function Documentation
FindLinks()
void TextLinker::FindLinks () protected
finds the links in the text, with which to populate m_links.
References anonymous_namespace{LinkText.cpp}::AllParamsAsString(), BROWSE_PATH_TAG, VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, TextLinker::Link::data, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, ENCYCLOPEDIA_TAG, ErrorLogger, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, GetLineData(), GRAPH_TAG, LocateLinks(), m_links, VarText::METER_TYPE_TAG, PathTypeToString(), VarText::PLANET_ID_TAG, VarText::POLICY_TAG, VarText::PREDEFINED_DESIGN_TAG, RawText(), TextLinker::Link::real_text_posn, anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes(), SetLinkedText(), VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, TextLinker::Link::text_posn, TextLinker::Link::type, and URL_TAG.
Referenced by CUILinkTextMultiEdit::CompleteConstruction(), LinkText::LinkText(), LinkText::SetText(), and CUILinkTextMultiEdit::SetText().
GetFont()
virtual const std::shared_ptr<GG::Font>& TextLinker::GetFont () const protected pure virtual
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by LocateLinks().
GetLineData()
virtual const std::vector<GG::Font::LineData>& TextLinker::GetLineData () const protected pure virtual
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by FindLinks(), and LocateLinks().
GetLinkUnderPt()
int TextLinker::GetLinkUnderPt (const GG::Pt & pt) protected
returns the index of the link under screen coordinate pt, or -1 if none
References ErrorLogger, m_links, TextLinker::Link::rects, and TextUpperLeft().
Referenced by LClick_(), LDoubleClick_(), MouseHere_(), LinkText::RClick(), CUILinkTextMultiEdit::RClick(), and RClick_().
LClick_()
void TextLinker::LClick_ (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) protected
References ErrorLogger, GetLinkUnderPt(), LinkClickedSignal, and m_links.
Referenced by LinkText::LClick(), and CUILinkTextMultiEdit::LClick().
LDoubleClick_()
void TextLinker::LDoubleClick_ (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) protected
References ErrorLogger, GetLinkUnderPt(), LinkDoubleClickedSignal, and m_links.
LinkDefaultFormatTag()
std::string TextLinker::LinkDefaultFormatTag (const Link & link, const std::string & content) const private
References TextLinker::Link::data, LinkDecorator::Decorate(), DEFAULT_DECORATOR, m_decorators, and TextLinker::Link::type.
Referenced by MarkLinks().
LinkRolloverFormatTag()
std::string TextLinker::LinkRolloverFormatTag (const Link & link, const std::string & content) const private
References TextLinker::Link::data, LinkDecorator::DecorateRollover(), DEFAULT_DECORATOR, m_decorators, and TextLinker::Link::type.
Referenced by MarkLinks().
LocateLinks()
void TextLinker::LocateLinks () protected
calculates the physical locations of the links in m_links
References GetFont(), GetLineData(), and m_links.
Referenced by FindLinks(), CUILinkTextMultiEdit::SetText(), and LinkText::SizeMove().
MarkLinks()
void TextLinker::MarkLinks () protected
wraps text for each link in text formatting tags so that the links appear visually distinct from other text
References anonymous_namespace{XMLDoc.cpp}::content, DEFAULT_DECORATOR, LinkDefaultFormatTag(), LinkRolloverFormatTag(), m_links, m_rollover_link, RawText(), TextLinker::Link::real_text_posn, SetLinkedText(), and TextLinker::Link::text_posn.
Referenced by CUILinkTextMultiEdit::CompleteConstruction(), LinkText::LinkText(), MouseHere_(), MouseLeave_(), SetDecorator(), LinkText::SetText(), and CUILinkTextMultiEdit::SetText().
MouseHere_()
void TextLinker::MouseHere_ (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) protected
References GetLinkUnderPt(), m_rollover_link, and MarkLinks().
Referenced by LinkText::MouseHere(), and CUILinkTextMultiEdit::MouseHere().
MouseLeave_()
void TextLinker::MouseLeave_ () protected
References m_rollover_link, and MarkLinks().
Referenced by LinkText::MouseLeave(), and CUILinkTextMultiEdit::MouseLeave().
RawText()
virtual const std::string& TextLinker::RawText () const protected pure virtual
returns text being displayed before any link formatting is added
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by FindLinks(), and MarkLinks().
RClick_()
void TextLinker::RClick_ (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) protected
References ErrorLogger, GetLinkUnderPt(), LinkRightClickedSignal, and m_links.
Referenced by LinkText::RClick(), and CUILinkTextMultiEdit::RClick().
Render_()
void TextLinker::Render_ () protected
References m_links, anonymous_namespace{LinkText.cpp}::RENDER_DEBUGGING_LINK_RECTS, TextLowerRight(), and TextUpperLeft().
Referenced by LinkText::Render(), and CUILinkTextMultiEdit::Render().
SetDecorator()
void TextLinker::SetDecorator (const std::string & link_type, LinkDecorator * decorator)
Sets the link decorator for a link type.
Parameters
link_type The link type (tag) to be decorated. Eg. "planet"
decorator The decorator to use. Assumes ownership. link clicked signals: first string is the link type, second string is the specific item clicked
References m_decorators, and MarkLinks().
SetLinkedText()
virtual void TextLinker::SetLinkedText (const std::string & str) protected pure virtual
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by FindLinks(), and MarkLinks().
TextLowerRight()
virtual GG::Pt TextLinker::TextLowerRight () const protected pure virtual
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by Render_().
TextUpperLeft()
virtual GG::Pt TextLinker::TextUpperLeft () const protected pure virtual
Implemented in CUILinkTextMultiEdit, and LinkText.
Referenced by GetLinkUnderPt(), and Render_().
Member Data Documentation
BROWSE_PATH_TAG
const std::string TextLinker::BROWSE_PATH_TAG static
Tag for clickable link to open users file manager at a specified directory.
Referenced by anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), CUILinkTextBlock::Factory::CreateFromTag(), FindLinks(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), and RegisterLinkTags().
DEFAULT_DECORATOR
const LinkDecorator TextLinker::DEFAULT_DECORATOR static private
Referenced by LinkDefaultFormatTag(), LinkRolloverFormatTag(), and MarkLinks().
ENCYCLOPEDIA_TAG
const std::string TextLinker::ENCYCLOPEDIA_TAG static
Referenced by EncyclopediaDetailPanel::CompleteConstruction(), FindLinks(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetRefreshDetailPanelInfo(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), EncyclopediaDetailPanel::OnIndex(), RegisterLinkTags(), EncyclopediaDetailPanel::SetEncyclopediaArticle(), EncyclopediaDetailPanel::SetIndex(), EncyclopediaDetailPanel::SetText(), and MapWnd::ShowGraphs().
GRAPH_TAG
const std::string TextLinker::GRAPH_TAG static
Referenced by FindLinks(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetRefreshDetailPanelInfo(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), EncyclopediaDetailPanel::RefreshImpl(), RegisterLinkTags(), and EncyclopediaDetailPanel::SetGraph().
LinkClickedSignal
boost::signals2::signal<void (const std::string&, const std::string&)> TextLinker::LinkClickedSignal mutable
Referenced by LClick_().
LinkDoubleClickedSignal
boost::signals2::signal<void (const std::string&, const std::string&)> TextLinker::LinkDoubleClickedSignal mutable
Referenced by LDoubleClick_().
LinkRightClickedSignal
boost::signals2::signal<void (const std::string&, const std::string&)> TextLinker::LinkRightClickedSignal mutable
Referenced by RClick_().
m_decorators
std::map<std::string, LinkDecoratorPtr> TextLinker::m_decorators private
Referenced by LinkDefaultFormatTag(), LinkRolloverFormatTag(), and SetDecorator().
m_links
std::vector<Link> TextLinker::m_links private
Referenced by FindLinks(), GetLinkUnderPt(), LClick_(), LDoubleClick_(), LocateLinks(), MarkLinks(), RClick_(), and Render_().
m_rollover_link
int TextLinker::m_rollover_link private
Referenced by MarkLinks(), MouseHere_(), and MouseLeave_().
URL_TAG
const std::string TextLinker::URL_TAG static
Referenced by FindLinks(), EncyclopediaDetailPanel::HandleLinkClick(), and RegisterLinkTags().
The documentation for this class was generated from the following files:
LinkText.h
LinkText.cpp