FreeOrion: anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager Class Reference
anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager Class Reference
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a policy.
Public Types
using DisplayedAvailabilies = std::tuple< bool, bool, bool >
Public Member Functions
AvailabilityManager (bool restricted, bool available, bool unavailable)
boost::optional< DisplayedAvailabilies > DisplayedPolicyAvailability (const Policy *policy) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the policy.
const DisplayedAvailabilies & GetAvailabilities () const
bool GetAvailability (const Availability::Enum type) const
void SetAvailability (const Availability::Enum type, const bool state)
void ToggleAvailability (const Availability::Enum type)
Private Member Functions
boost::optional< DisplayedAvailabilies > DisplayedXAvailability (bool available, bool restricted) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager and that the X is available and restricted, return the displayed state of the X.
Private Attributes
DisplayedAvailabilies m_availabilities
Detailed Description
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a policy.
Member Typedef Documentation
DisplayedAvailabilies
using anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::DisplayedAvailabilies = std::tuple<bool, bool, bool>
Constructor & Destructor Documentation
AvailabilityManager()
anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::AvailabilityManager (bool restricted, bool available, bool unavailable)
Member Function Documentation
DisplayedPolicyAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::DisplayedPolicyAvailability (const Policy * policy) const
Given the GUI's displayed availabilities as stored in this AvailabilityManager, return the displayed state of the policy.
Return none if the policy should not be displayed.
References DisplayedXAvailability(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), and Policy::Name().
DisplayedXAvailability()
boost::optional< AvailabilityManager::DisplayedAvailabilies > anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::DisplayedXAvailability (bool available, bool restricted) const private
Given the GUI's displayed availabilities as stored in this AvailabilityManager and that the X is available and restricted, return the displayed state of the X.
Return none if the X should not be displayed.
References m_availabilities.
Referenced by DisplayedPolicyAvailability().
GetAvailabilities()
const DisplayedAvailabilies& anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::GetAvailabilities () const inline
GetAvailability()
bool anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::GetAvailability (const Availability::Enum type) const
References Availability::Available, Availability::Future, m_availabilities, and Availability::Restricted.
Referenced by ToggleAvailability().
SetAvailability()
void anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::SetAvailability (const Availability::Enum type, const bool state)
References Availability::Available, Availability::Future, m_availabilities, and Availability::Restricted.
Referenced by PolicyControl::GetPolicy(), and ToggleAvailability().
ToggleAvailability()
void anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::ToggleAvailability (const Availability::Enum type)
References GetAvailability(), and SetAvailability().
Member Data Documentation
m_availabilities
DisplayedAvailabilies anonymous_namespace{GovernmentWnd.cpp}::AvailabilityManager::m_availabilities private
Referenced by DisplayedXAvailability(), GetAvailability(), and SetAvailability().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp