FreeOrion: Moderator::CreateSystem Class Reference
Moderator::CreateSystem Class Reference
#include <ModeratorAction.h>
Public Member Functions
CreateSystem ()
CreateSystem (double x, double y, StarType star_type)
std::string Dump () const override
void Execute () const override
Public Member Functions inherited from Moderator::ModeratorAction
ModeratorAction ()=default
virtual ~ModeratorAction ()=default
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
StarType m_star_type
double m_x = 0.0
double m_y = 0.0
Friends
class boost::serialization::access
Constructor & Destructor Documentation
CreateSystem() [1/2]
Moderator::CreateSystem::CreateSystem ()
CreateSystem() [2/2]
Moderator::CreateSystem::CreateSystem (double x, double y, StarType star_type)
Member Function Documentation
Dump()
std::string Moderator::CreateSystem::Dump () const override virtual
Reimplemented from Moderator::ModeratorAction.
References m_star_type, m_x, m_y, and to_string().
Execute()
void Moderator::CreateSystem::Execute () const override virtual
Reimplemented from Moderator::ModeratorAction.
References ErrorLogger, anonymous_namespace{ModeratorAction.cpp}::GenerateSystemName(), GetUniverse(), Universe::InsertNew(), m_star_type, m_x, and m_y.
serialize()
template<typename Archive > template void Moderator::CreateSystem::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_star_type
StarType Moderator::CreateSystem::m_star_type private
Referenced by Dump(), and Execute().
m_x
double Moderator::CreateSystem::m_x = 0.0 private
Referenced by Dump(), and Execute().
m_y
double Moderator::CreateSystem::m_y = 0.0 private
Referenced by Dump(), and Execute().
The documentation for this class was generated from the following files:
ModeratorAction.h
ModeratorAction.cpp
SerializeModeratorAction.cpp