FreeOrion: Effect::CreateBuilding Class Reference
Effect::CreateBuilding Class Reference final
Creates a new Building with specified type on the target Planet.
#include <Effect.h>
Public Member Functions
CreateBuilding (std::unique_ptr< ValueRef::ValueRefBase< std::string >> &&building_type_name, std::unique_ptr< ValueRef::ValueRefBase< std::string >> &&name, std::vector< std::unique_ptr< EffectBase >> &&effects_to_apply_after)
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRefBase< std::string > > m_building_type_name
std::vector< std::unique_ptr< EffectBase > > m_effects_to_apply_after
std::unique_ptr< ValueRef::ValueRefBase< std::string > > m_name
Friends
class boost::serialization::access
Detailed Description
Creates a new Building with specified type on the target Planet.
Constructor & Destructor Documentation
CreateBuilding()
Effect::CreateBuilding::CreateBuilding (std::unique_ptr< ValueRef::ValueRefBase< std::string >> && building_type_name, std::unique_ptr< ValueRef::ValueRefBase< std::string >> && name, std::vector< std::unique_ptr< EffectBase >> && effects_to_apply_after)
Member Function Documentation
Dump()
std::string Effect::CreateBuilding::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), m_building_type_name, and m_name.
Execute()
void Effect::CreateBuilding::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ALL_EMPIRES, ScriptingContext::effect_target, ErrorLogger, GetBuildingType(), GetPlanet(), GetSystem(), GetUniverse(), Universe::InsertNew(), m_building_type_name, m_effects_to_apply_after, m_name, UserString(), and UserStringExists().
GetCheckSum()
unsigned int Effect::CreateBuilding::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_building_type_name, m_effects_to_apply_after, m_name, and TraceLogger.
serialize()
template<class Archive > void Effect::CreateBuilding::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::CreateBuilding::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_building_type_name, m_effects_to_apply_after, and m_name.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_building_type_name
std::unique_ptr<ValueRef::ValueRefBase<std::string> > Effect::CreateBuilding::m_building_type_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_effects_to_apply_after
std::vector<std::unique_ptr<EffectBase> > Effect::CreateBuilding::m_effects_to_apply_after private
Referenced by Execute(), GetCheckSum(), and SetTopLevelContent().
m_name
std::unique_ptr<ValueRef::ValueRefBase<std::string> > Effect::CreateBuilding::m_name private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp