FreeOrion: AccordionPanel Class Reference
AccordionPanel Class Reference
#include <AccordionPanel.h>
Public Types
typedef boost::signals2::signal< void()> ExpandCollapseSignalType
Public Member Functions
GG::Pt ClientLowerRight () const override
GG::Pt ClientUpperLeft () const override
void CompleteConstruction () override
Structors
AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left=false)
virtual ~AccordionPanel ()
Mutators
void Render () override
Sets the interior color of the box.
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Sets the interior color of the box.
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Sets the interior color of the box.
void SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
void SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
Public Attributes
ExpandCollapseSignalType ExpandCollapseSignal
Protected Member Functions
virtual void DoLayout ()
virtual void InitBuffer ()
bool IsCollapsed () const
void SetCollapsed (bool collapsed)
Protected Attributes
GG::GL2DVertexBuffer m_border_buffer
unsigned int m_border_margin = 1
The number of pixels between the expansion button and the client area.
bool m_collapsed = true
std::shared_ptr< GG::Button > m_expand_button
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
GG::Clr m_interior_color
bool m_is_left = false
Is expand button on the left?
Member Typedef Documentation
ExpandCollapseSignalType
typedef boost::signals2::signal<void ()> AccordionPanel::ExpandCollapseSignalType
Constructor & Destructor Documentation
AccordionPanel()
AccordionPanel::AccordionPanel (GG::X w, GG::Y h, bool is_button_on_left = false)
~AccordionPanel()
AccordionPanel::~AccordionPanel () virtual
References m_border_buffer.
Member Function Documentation
ClientLowerRight()
GG::Pt AccordionPanel::ClientLowerRight () const override
References anonymous_namespace{AccordionPanel.cpp}::EXPAND_BUTTON_SIZE, m_border_margin, and m_is_left.
ClientUpperLeft()
GG::Pt AccordionPanel::ClientUpperLeft () const override
References anonymous_namespace{AccordionPanel.cpp}::EXPAND_BUTTON_SIZE, m_border_margin, and m_is_left.
CompleteConstruction()
void AccordionPanel::CompleteConstruction () override
References ClientUI::ArtDir(), DoLayout(), anonymous_namespace{AccordionPanel.cpp}::EXPAND_BUTTON_SIZE, ClientUI::GetTexture(), InitBuffer(), and m_expand_button.
Referenced by BuildingsPanel::CompleteConstruction(), MilitaryPanel::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction().
DoLayout()
void AccordionPanel::DoLayout () protected virtual
Reimplemented in PopulationPanel, ResourcePanel, BuildingsPanel, and MilitaryPanel.
References anonymous_namespace{AccordionPanel.cpp}::EXPAND_BUTTON_SIZE, m_border_margin, m_expand_button, and m_is_left.
Referenced by CompleteConstruction(), MilitaryPanel::DoLayout(), BuildingsPanel::DoLayout(), ResourcePanel::DoLayout(), PopulationPanel::DoLayout(), and SizeMove().
InitBuffer()
void AccordionPanel::InitBuffer () protected virtual
References m_border_buffer.
Referenced by CompleteConstruction(), and SizeMove().
IsCollapsed()
bool AccordionPanel::IsCollapsed () const protected
References m_collapsed.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::ToggleExpansion(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::ToggleExpansion().
MouseWheel()
void AccordionPanel::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
Sets the interior color of the box.
Render()
void AccordionPanel::Render () override
Sets the interior color of the box.
References m_border_buffer, m_interior_color, and ClientUI::WndOuterBorderColor().
SetBorderMargin()
void AccordionPanel::SetBorderMargin (unsigned int margin)
Set the number of pixels between the expansion symbol and the client area.
References m_border_margin.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction().
SetCollapsed()
void AccordionPanel::SetCollapsed (bool collapsed) protected
References ClientUI::ArtDir(), ExpandCollapseSignal, ClientUI::GetTexture(), m_collapsed, and m_expand_button.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction(), MilitaryPanel::DoLayout(), BuildingsPanel::DoLayout(), ResourcePanel::DoLayout(), PopulationPanel::DoLayout(), anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::ToggleExpansion(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::ToggleExpansion().
SetInteriorColor()
void AccordionPanel::SetInteriorColor (GG::Clr c)
Sets the interior color of the box.
References m_interior_color.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), and anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction().
SizeMove()
void AccordionPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Sets the interior color of the box.
References DoLayout(), and InitBuffer().
Member Data Documentation
ExpandCollapseSignal
ExpandCollapseSignalType AccordionPanel::ExpandCollapseSignal mutable
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction(), and SetCollapsed().
m_border_buffer
GG::GL2DVertexBuffer AccordionPanel::m_border_buffer protected
Referenced by InitBuffer(), Render(), and ~AccordionPanel().
m_border_margin
unsigned int AccordionPanel::m_border_margin = 1 protected
The number of pixels between the expansion button and the client area.
Referenced by ClientLowerRight(), ClientUpperLeft(), DoLayout(), and SetBorderMargin().
m_collapsed
bool AccordionPanel::m_collapsed = true protected
Referenced by IsCollapsed(), and SetCollapsed().
m_expand_button
std::shared_ptr<GG::Button> AccordionPanel::m_expand_button protected
at top right/left of panel, toggles the panel open/closed to show details or minimal summary;
Referenced by BuildingsPanel::CompleteConstruction(), CompleteConstruction(), MilitaryPanel::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CompleteConstruction(), anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::CompleteConstruction(), MilitaryPanel::DoLayout(), DoLayout(), BuildingsPanel::DoLayout(), PopulationPanel::DoLayout(), ResourcePanel::DoLayout(), and SetCollapsed().
m_interior_color
GG::Clr AccordionPanel::m_interior_color protected
Referenced by Render(), and SetInteriorColor().
m_is_left
bool AccordionPanel::m_is_left = false protected
Is expand button on the left?
Referenced by ClientLowerRight(), ClientUpperLeft(), and DoLayout().
The documentation for this class was generated from the following files:
AccordionPanel.h
AccordionPanel.cpp