FreeOrion: anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel Class Reference
anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel Class Reference
Represents a player.
Public Member Functions
PlayerDataPanel (GG::X w, GG::Y h, int player_id, int empire_id)
GG::Pt ClientLowerRight () const override
Excludes border from the client area.
GG::Pt ClientUpperLeft () const override
Excludes border from the client area.
void CompleteConstruction () override
void Render () override
Renders panel background, border with color depending on the current state.
void Select (bool b)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Update ()
Private Types
enum { WON, LOST, NEITHER }
Private Member Functions
void DoLayout ()
int IconSize () const
Private Attributes
std::shared_ptr< DiplomaticStatusIndicator > m_allied_indicator
GG::Pt m_detection_icon_ul
GG::Pt m_diplo_msg_ul
DiplomaticStatus m_diplo_status
GG::Pt m_diplo_status_icon_ul
std::shared_ptr< GG::Label > m_empire_detection_text
int m_empire_id
std::shared_ptr< GG::Label > m_empire_name_text
std::shared_ptr< GG::Label > m_empire_planet_text
std::shared_ptr< GG::Label > m_empire_production_text
std::shared_ptr< GG::Label > m_empire_research_text
std::shared_ptr< GG::Label > m_empire_ship_text
bool m_host = false
GG::Pt m_host_icon_ul
std::shared_ptr< DiplomaticStatusIndicator > m_peace_indicator
GG::Pt m_planet_icon_ul
int m_player_id
GG::Pt m_player_status_icon_ul
Networking::ClientType m_player_type
GG::Pt m_player_type_icon_ul
GG::Pt m_production_icon_ul
GG::Pt m_research_icon_ul
bool m_selected = false
GG::Pt m_ship_icon_ul
std::shared_ptr< DiplomaticStatusIndicator > m_war_indicator
enum anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel:: { ... } m_win_status = NEITHER
GG::Pt m_win_status_icon_ul
Detailed Description
Represents a player.
This class is used as the sole Control in each PlayerRow.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
WON
LOST
NEITHER
Constructor & Destructor Documentation
PlayerDataPanel()
anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::PlayerDataPanel (GG::X w, GG::Y h, int player_id, int empire_id) inline
Member Function Documentation
ClientLowerRight()
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::ClientLowerRight () const inline override
Excludes border from the client area.
ClientUpperLeft()
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::ClientUpperLeft () const inline override
Excludes border from the client area.
CompleteConstruction()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::CompleteConstruction () inline override
DoLayout()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout () inline private
References anonymous_namespace{MultiplayerLobbyWnd.cpp}::EMPIRE_NAME_WIDTH(), Empires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::IconSize(), EmpireManager::NumEliminatedEmpires(), EmpireManager::NumEmpires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, and ClientUI::Pts().
IconSize()
int anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::IconSize () const inline private
Render()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render () inline override
Renders panel background, border with color depending on the current state.
References anonymous_namespace{PlayerListWnd.cpp}::AIIcon(), anonymous_namespace{PlayerListWnd.cpp}::AlliedIcon(), Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, anonymous_namespace{PlayerListWnd.cpp}::DetectionIcon(), ClientApp::EmpireID(), Empires(), ErrorLogger, ClientApp::GetApp(), EmpireManager::GetDiplomaticMessage(), GetEmpire(), DiplomaticMessage::GetType(), anonymous_namespace{PlayerListWnd.cpp}::HostIcon(), anonymous_namespace{PlayerListWnd.cpp}::HumanIcon(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::IconSize(), DiplomaticMessage::INVALID_DIPLOMATIC_MESSAGE_TYPE, anonymous_namespace{PlayerListWnd.cpp}::LostIcon(), anonymous_namespace{PlayerListWnd.cpp}::MessageIcon(), anonymous_namespace{PlayerListWnd.cpp}::ModeratorIcon(), anonymous_namespace{PlayerListWnd.cpp}::ObserverIcon(), anonymous_namespace{PlayerListWnd.cpp}::PeaceIcon(), ClientUI::PlanetIcon(), anonymous_namespace{PlayerListWnd.cpp}::PlayingIcon(), anonymous_namespace{PlayerListWnd.cpp}::ProductionIcon(), anonymous_namespace{PlayerListWnd.cpp}::ResearchIcon(), anonymous_namespace{PlayerListWnd.cpp}::ShipIcon(), anonymous_namespace{PlayerListWnd.cpp}::UnknownIcon(), anonymous_namespace{PlayerListWnd.cpp}::WaitingIcon(), anonymous_namespace{PlayerListWnd.cpp}::WarIcon(), ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), ClientUI::WndOuterBorderColor(), and anonymous_namespace{PlayerListWnd.cpp}::WonIcon().
Select()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Select (bool b) inline
SizeMove()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Update()
void anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update () inline
References ObjectMap::all(), ALL_EMPIRES, PlayerInfo::client_type, Empire::Color(), Meter::Current(), DoubleToString(), Empire::Eliminated(), ClientApp::EmpireID(), Empire::EmpireID(), anonymous_namespace{AIWrapper.cpp}::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), Universe::EmpireStaleKnowledgeObjectIDs(), ErrorLogger, HumanClientApp::GetApp(), ClientApp::GetApp(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), Empire::GetMeter(), GetUniverse(), PlayerInfo::host, Networking::INVALID_CLIENT_TYPE, METER_INDUSTRY, METER_RESEARCH, Empire::Name(), PlayerInfo::name, Objects(), ClientApp::Players(), ClientUI::TextColor(), UserString(), and Empire::Won().
Member Data Documentation
m_allied_indicator
std::shared_ptr<DiplomaticStatusIndicator> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_allied_indicator private
m_detection_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_detection_icon_ul private
m_diplo_msg_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_diplo_msg_ul private
m_diplo_status
DiplomaticStatus anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_diplo_status private
m_diplo_status_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_diplo_status_icon_ul private
m_empire_detection_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_detection_text private
m_empire_id
int anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_id private
m_empire_name_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_name_text private
m_empire_planet_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_planet_text private
m_empire_production_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_production_text private
m_empire_research_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_research_text private
m_empire_ship_text
std::shared_ptr<GG::Label> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_empire_ship_text private
m_host
bool anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_host = false private
m_host_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_host_icon_ul private
m_peace_indicator
std::shared_ptr<DiplomaticStatusIndicator> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_peace_indicator private
m_planet_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_planet_icon_ul private
m_player_id
int anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_player_id private
m_player_status_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_player_status_icon_ul private
m_player_type
Networking::ClientType anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_player_type private
m_player_type_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_player_type_icon_ul private
m_production_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_production_icon_ul private
m_research_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_research_icon_ul private
m_selected
bool anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_selected = false private
m_ship_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_ship_icon_ul private
m_war_indicator
std::shared_ptr<DiplomaticStatusIndicator> anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_war_indicator private
m_win_status
enum { ... } anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_win_status
m_win_status_icon_ul
GG::Pt anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::m_win_status_icon_ul private
The documentation for this class was generated from the following file:
PlayerListWnd.cpp