FreeOrion: Fighter Class Reference
Fighter Class Reference
a class representing a Fighter in combat.
#include <Fighter.h>
Public Member Functions
Fighter (int empire_id, int launched_from_id, const std::string &species_name, float damage, const ::Condition::Condition *combat_targets)
Fighter ()
~Fighter ()
std::shared_ptr< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const override
Accepts a visitor object.
const ::Condition::Condition * CombatTargets () const
void Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES) override
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
float Damage () const
bool Destroyed () const
std::string Dump (unsigned short ntabs=0) const override
Return human readable string description of object offset ntabs from margin.
bool HostileToEmpire (int empire_id) const override
Object owner is at war with empire empire_id.
int LaunchedFrom () const
UniverseObjectType ObjectType () const override
void SetDestroyed (bool destroyed=true)
const std::string & SpeciesName () const
Public Member Functions inherited from UniverseObject
virtual ~UniverseObject ()
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
virtual void BackPropagateMeters ()
Sets all this UniverseObject's meters' initial values equal to their current values.
virtual void ClampMeters ()
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
virtual bool ContainedBy (int object_id) const
virtual const std::set< int > & ContainedObjectIDs () const
Returns ids of objects contained within this object.
virtual int ContainerObjectID () const
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
virtual bool Contains (int object_id) const
Returns true if there is an object with id object_id is contained within this UniverseObject.
int CreationTurn () const
returns game turn on which object was created
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
virtual bool HasTag (const std::string &name) const
Returns true iff this object has the tag with the indicated name.
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const MeterMap & Meters () const
returns this UniverseObject's meters
MeterMap & Meters ()
returns this UniverseObject's meters
void Move (double x, double y)
moves this object by relative displacements x and y.
virtual void MovementPhase ()
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
void MoveTo (int object_id)
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
void MoveTo (std::shared_ptr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
void MoveTo (double x, double y)
moves this object to map coordinates (x, y).
const std::string & Name () const
returns the name of this object; some valid objects will have no name
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
virtual void PopGrowthProductionResearchPhase ()
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
virtual const std::string & PublicName (int empire_id) const
Returns the name of this objectas it appears to empire empire_id .
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void Rename (const std::string &name)
renames this object to name
virtual void ResetPairedActiveMeters ()
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
virtual void ResetTargetMaxUnpairedMeters ()
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE.
void SetID (int id)
sets the ID number of the object to id
virtual void SetOwner (int id)
Sets the empire that owns this object.
void SetSpecialCapacity (const std::string &name, float capacity)
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
const std::map< std::string, std::pair< int, float > > & Specials () const
returns the Specials attached to this object
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
virtual std::set< std::string > Tags () const
returns the capacity of the special with name name or 0 if that special is not present
bool Unowned () const
returns true iff there are no owners of this object
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
Protected Member Functions
Fighter * Clone (int empire_id=ALL_EMPIRES) const override
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Protected Member Functions inherited from UniverseObject
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (std::shared_ptr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
void Init ()
adds stealth meter
Private Attributes
const ::Condition::Condition * m_combat_targets = nullptr
float m_damage = 0.0f
bool m_destroyed = false
int m_launched_from_id = INVALID_OBJECT_ID
std::string m_species_name
Additional Inherited Members
Public Types inherited from UniverseObject
typedef flat_map< MeterType, Meter, std::less< MeterType > > MeterMap
typedef boost::signals2::signal< void(), blocking_combiner< boost::signals2::optional_last_value< void > > > StateChangedSignalType
typedef StateChangedSignalType::slot_type StateChangedSlotType
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
a class representing a Fighter in combat.
Derived from UniverseObject so it can be stored in the same container as other combat objects.
Constructor & Destructor Documentation
Fighter() [1/2]
Fighter::Fighter (int empire_id, int launched_from_id, const std::string & species_name, float damage, const ::Condition::Condition * combat_targets)
References UniverseObject::Init(), and UniverseObject::SetOwner().
Fighter() [2/2]
Fighter::Fighter ()
Referenced by Clone().
~Fighter()
Fighter::~Fighter ()
Member Function Documentation
Accept()
std::shared_ptr< UniverseObject > Fighter::Accept (const UniverseObjectVisitor & visitor) const override virtual
Accepts a visitor object.
See also
UniverseObjectVisitor
Reimplemented from UniverseObject.
References UniverseObjectVisitor::Visit().
Clone()
Fighter * Fighter::Clone (int empire_id = ALL_EMPIRES) const override protected virtual
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Caller takes ownership of returned pointee.
Implements UniverseObject.
References Copy(), and Fighter().
CombatTargets()
const ::Condition::Condition * Fighter::CombatTargets () const
References m_combat_targets.
Copy()
void Fighter::Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) override virtual
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
Implements UniverseObject.
References UniverseObject::Copy(), ErrorLogger, m_combat_targets, m_damage, m_destroyed, and VIS_FULL_VISIBILITY.
Referenced by Clone().
Damage()
float Fighter::Damage () const
References m_damage.
Destroyed()
bool Fighter::Destroyed () const
References m_destroyed.
Dump()
std::string Fighter::Dump (unsigned short ntabs = 0) const override virtual
Return human readable string description of object offset ntabs from margin.
Reimplemented from UniverseObject.
References UniverseObject::Dump(), m_damage, and m_destroyed.
HostileToEmpire()
bool Fighter::HostileToEmpire (int empire_id) const override virtual
Object owner is at war with empire empire_id.
Reimplemented from UniverseObject.
References ALL_EMPIRES, Empires(), EmpireManager::GetDiplomaticStatus(), UniverseObject::OwnedBy(), UniverseObject::Owner(), and UniverseObject::Unowned().
LaunchedFrom()
int Fighter::LaunchedFrom () const
References m_launched_from_id.
ObjectType()
UniverseObjectType Fighter::ObjectType () const override virtual
Reimplemented from UniverseObject.
SetDestroyed()
void Fighter::SetDestroyed (bool destroyed = true)
References m_destroyed.
SpeciesName()
const std::string & Fighter::SpeciesName () const
References m_species_name.
Member Data Documentation
m_combat_targets
const ::Condition::Condition* Fighter::m_combat_targets = nullptr private
Referenced by CombatTargets(), and Copy().
m_damage
float Fighter::m_damage = 0.0f private
Referenced by Copy(), Damage(), and Dump().
m_destroyed
bool Fighter::m_destroyed = false private
Referenced by Copy(), Destroyed(), Dump(), and SetDestroyed().
m_launched_from_id
int Fighter::m_launched_from_id = INVALID_OBJECT_ID private
Referenced by LaunchedFrom().
m_species_name
std::string Fighter::m_species_name private
Referenced by SpeciesName().
The documentation for this class was generated from the following files:
Fighter.h
Fighter.cpp