FreeOrion: anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator Class Reference
anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator Class Reference
Shows specified diplomatic status from specified empire to each other empire.
Public Member Functions
DiplomaticStatusIndicator (GG::X w, GG::Y h, int empire_id, DiplomaticStatus diplo_status)
void CompleteConstruction () override
void RButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void Render () override
void Update ()
Private Member Functions
int IconSize () const
Private Attributes
DiplomaticStatus m_diplo_status
int m_empire_id
std::vector< int > m_empire_ids
std::shared_ptr< GG::Texture > m_icon
int PAD = 3
Detailed Description
Shows specified diplomatic status from specified empire to each other empire.
Constructor & Destructor Documentation
DiplomaticStatusIndicator()
anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::DiplomaticStatusIndicator (GG::X w, GG::Y h, int empire_id, DiplomaticStatus diplo_status) inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::CompleteConstruction () inline override
References anonymous_namespace{PlayerListWnd.cpp}::AlliedIcon(), anonymous_namespace{PlayerListWnd.cpp}::PeaceIcon(), anonymous_namespace{PlayerListWnd.cpp}::UnknownIcon(), and anonymous_namespace{PlayerListWnd.cpp}::WarIcon().
IconSize()
int anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::IconSize () const inline private
RButtonDown()
void anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::RButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
RClick()
void anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline override
Render()
void anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render () inline override
References Empires(), anonymous_namespace{MapWnd.cpp}::ICON_SIZE, anonymous_namespace{EncyclopediaDetailPanel.cpp}::IconSize(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD, and ClientUI::WndOuterBorderColor().
Update()
void anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update () inline
References Empires(), ErrorLogger, ClientApp::GetApp(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), GetOptionsDB(), and UserString().
Member Data Documentation
m_diplo_status
DiplomaticStatus anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::m_diplo_status private
m_empire_id
int anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::m_empire_id private
m_empire_ids
std::vector<int> anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::m_empire_ids private
m_icon
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::m_icon private
PAD
int anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::PAD = 3 private
The documentation for this class was generated from the following file:
PlayerListWnd.cpp