FreeOrion: SaveFileFileRow Class Reference
SaveFileFileRow Class Reference
Public Member Functions
SaveFileFileRow (const FullPreview &full, const std::shared_ptr< std::vector< SaveFileColumn >> &visible_columns, const std::shared_ptr< std::vector< SaveFileColumn >> &columns, int tooltip_delay)
Creates a row for the given savefile.
void CompleteConstruction () override
void Init () override
SortKeyType SortKey (std::size_t column) const override
Public Member Functions inherited from SaveFileRow
SaveFileRow ()
SaveFileRow (const std::shared_ptr< std::vector< SaveFileColumn >> &columns, const std::string &filename)
virtual void AdjustColumns ()
Forces the columns to column widths not defined by ListBox.
GG::Pt ClientLowerRight () const override
Excludes border from the client area.
GG::Pt ClientUpperLeft () const override
Excludes border from the client area.
const std::string & Filename () const
void PreRender () override
void Render () override
Private Attributes
std::shared_ptr< std::vector< SaveFileColumn > > m_all_columns
All possible columns.
const FullPreview m_full_preview
Additional Inherited Members
Protected Attributes inherited from SaveFileRow
std::shared_ptr< std::vector< SaveFileColumn > > m_columns
std::string m_filename
bool m_initialized
Constructor & Destructor Documentation
SaveFileFileRow()
SaveFileFileRow::SaveFileFileRow (const FullPreview & full, const std::shared_ptr< std::vector< SaveFileColumn >> & visible_columns, const std::shared_ptr< std::vector< SaveFileColumn >> & columns, int tooltip_delay) inline
Creates a row for the given savefile.
Member Function Documentation
CompleteConstruction()
void SaveFileFileRow::CompleteConstruction () inline override
Init()
void SaveFileFileRow::Init () inline override virtual
Reimplemented from SaveFileRow.
References VarText::AddVariable(), SaveFileColumn::CellForColumn(), ColumnInPreview(), VarText::GetText(), SaveFileRow::Init(), and UserStringNop.
SortKey()
SortKeyType SaveFileFileRow::SortKey (std::size_t column) const inline override
Member Data Documentation
m_all_columns
std::shared_ptr<std::vector<SaveFileColumn> > SaveFileFileRow::m_all_columns private
All possible columns.
m_full_preview
const FullPreview SaveFileFileRow::m_full_preview private
The documentation for this class was generated from the following file:
SaveFileDialog.cpp