FreeOrion: anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel Class Reference
anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel Class Reference
Public Member Functions
SitRepDataPanel (GG::X left, GG::Y top, GG::X w, GG::Y h, const SitRepEntry &sitrep)
void CompleteConstruction () override
const SitRepEntry & GetSitRepEntry () const
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
boost::signals2::signal< void(const GG::Pt &, GG::Flags< GG::ModKey >)> RightClickedSignal
Protected Member Functions
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod) override
Private Member Functions
void DoLayout (const GG::Pt &ul, const GG::X &width)
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_icon = nullptr
std::shared_ptr< SitRepLinkText > m_link_text = nullptr
const SitRepEntry & m_sitrep_entry
Constructor & Destructor Documentation
SitRepDataPanel()
anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::SitRepDataPanel (GG::X left, GG::Y top, GG::X w, GG::Y h, const SitRepEntry & sitrep) inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction () inline override
References ClientUI::ArtDir(), TextLinker::BROWSE_PATH_TAG, VarText::EMPIRE_ID_TAG, ClientUI::GetFont(), anonymous_namespace{SitRepPanel.cpp}::GetIconSize(), ClientUI::GetTexture(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), details::mod(), and ClientUI::TextColor().
DoLayout()
void anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::DoLayout (const GG::Pt & ul, const GG::X & width) inline private
References anonymous_namespace{SitRepPanel.cpp}::GetIconSize().
GetSitRepEntry()
const SitRepEntry& anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::GetSitRepEntry () const inline
RClick()
void anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod) inline override protected
Render()
void anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::Render () inline override
References ClientUI::CtrlColor(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
SizeMove()
void anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
m_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::m_icon = nullptr private
m_link_text
std::shared_ptr<SitRepLinkText> anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::m_link_text = nullptr private
m_sitrep_entry
const SitRepEntry& anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::m_sitrep_entry private
RightClickedSignal
boost::signals2::signal<void(const GG::Pt&, GG::Flags<GG::ModKey>)> anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::RightClickedSignal mutable
The documentation for this class was generated from the following file:
SitRepPanel.cpp