FreeOrion: SpeciesSelector Class Reference
SpeciesSelector Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
SpeciesSelector (GG::X w, GG::Y h)
populates with all species in SpeciesManager
Accessors
const std::string & CurrentSpeciesName () const
returns the name of the species that is currently selected
std::vector< std::string > AvailableSpeciesNames () const
returns the names of species in the selector
Mutators
void SelectSpecies (const std::string &species_name)
Public Member Functions inherited from CUIDropDownList
GG::Pt ClientLowerRight () const override
GG::X DroppedRowWidth () const override
CUIDropDownList (size_t num_shown_elements)
void Render () override
disables rendering of the small downward-facing arrow on the right of the control
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseLeave () override
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Public Attributes
boost::signals2::signal< void(const std::string &)> SpeciesChangedSignal
Private Member Functions
void SelectionChanged (GG::DropDownList::iterator it)
Detailed Description
A control used to pick from at list of species names.
Constructor & Destructor Documentation
SpeciesSelector::SpeciesSelector (GG::X w, GG::Y h)
populates with all species in SpeciesManager
References ClientUI::ArtDir(), GetSpeciesManager(), ClientUI::GetTexture(), SpeciesManager::playable_begin(), SpeciesManager::playable_end(), SelectionChanged(), and UserString().
Member Function Documentation
std::vector< std::string > SpeciesSelector::AvailableSpeciesNames () const
returns the names of species in the selector
Referenced by GalaxySetupWnd::GalaxySetupWnd().
const std::string & SpeciesSelector::CurrentSpeciesName () const
returns the name of the species that is currently selected
References anonymous_namespace{CUIControls.cpp}::EMPTY_STRING(), and ErrorLogger.
Referenced by GalaxySetupWnd::OkClicked(), and GalaxySetupWnd::StartingSpeciesName().
void SpeciesSelector::SelectionChanged (GG::DropDownList::iterator it) private
References anonymous_namespace{CUIControls.cpp}::COLOR_SELECTOR_WIDTH(), anonymous_namespace{CUIControls.cpp}::EMPTY_STRING(), and SpeciesChangedSignal.
Referenced by SpeciesSelector().
void SpeciesSelector::SelectSpecies (const std::string & species_name)
References ErrorLogger.
Referenced by GalaxySetupWnd::GalaxySetupWnd(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::NewGamePlayerRow().
Member Data Documentation
boost::signals2::signal<void (const std::string&)> SpeciesSelector::SpeciesChangedSignal mutable
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::NewGamePlayerRow(), and SelectionChanged().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp