FreeOrion: ResearchWnd Class Reference
ResearchWnd Class Reference
Contains a TechTreeWnd, some stats on the empire-wide research queue, and the queue itself.
#include <ResearchWnd.h>
Public Member Functions
void CompleteConstruction () override
Structors
ResearchWnd (GG::X w, GG::Y h, bool initially_hidden=true)
~ResearchWnd ()
Accessors
int ShownEmpireID () const
bool PediaVisible ()
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void Render () override
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void SetEmpireShown (int empire_id)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void Refresh ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void Reset ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void Update ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void CenterOnTech (const std::string &tech_name)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void ShowTech (const std::string &tech_name, bool force=true)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void QueueItemMoved (const GG::ListBox::iterator &row_it, const GG::ListBox::iterator &original_position_it)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void Sanitize ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void ShowPedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void HidePedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void TogglePedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via this ResearchWnd.
Private Member Functions
void AddTechsToQueueSlot (const std::vector< std::string > &tech_vec, int pos=-1)
void DeleteQueueItem (GG::ListBox::iterator it)
void DoLayout (bool init=false)
void QueueItemClickedSlot (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void QueueItemDoubleClickedSlot (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void QueueItemPaused (GG::ListBox::iterator it, bool pause)
void ResearchQueueChangedSlot ()
void UpdateInfoPanel ()
Updates research summary at top left of production screen, and signals that the empire's minerals research pool has changed (propagates to the mapwnd to update indicator)
void UpdateQueue ()
Private Attributes
boost::signals2::connection m_empire_connection
int m_empire_shown_id
bool m_enabled
std::shared_ptr< ResearchQueueWnd > m_queue_wnd
std::shared_ptr< ResourceInfoPanel > m_research_info_panel
std::shared_ptr< TechTreeWnd > m_tech_tree_wnd
Detailed Description
Contains a TechTreeWnd, some stats on the empire-wide research queue, and the queue itself.
Constructor & Destructor Documentation
ResearchWnd()
ResearchWnd::ResearchWnd (GG::X w, GG::Y h, bool initially_hidden = true)
References AddTechsToQueueSlot(), DeleteQueueItem(), GetOptionsDB(), m_queue_wnd, m_research_info_panel, m_tech_tree_wnd, QueueItemClickedSlot(), QueueItemDoubleClickedSlot(), QueueItemMoved(), QueueItemPaused(), ShowPedia(), and UserString().
~ResearchWnd()
ResearchWnd::~ResearchWnd ()
References m_empire_connection.
Member Function Documentation
AddTechsToQueueSlot()
void ResearchWnd::AddTechsToQueueSlot (const std::vector< std::string > & tech_vec, int pos = -1) private
References ResearchQueue::begin(), ClientApp::EmpireID(), ResearchQueue::find(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetResearchQueue(), ResearchQueue::InQueue(), OrderSet::IssueOrder(), m_enabled, ClientApp::Orders(), Empire::TechResearched(), and Empire::UpdateResearchQueue().
Referenced by ResearchWnd().
CenterOnTech()
void ResearchWnd::CenterOnTech (const std::string & tech_name)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
CompleteConstruction()
void ResearchWnd::CompleteConstruction () override
References DoLayout(), m_queue_wnd, m_research_info_panel, and m_tech_tree_wnd.
DeleteQueueItem()
void ResearchWnd::DeleteQueueItem (GG::ListBox::iterator it) private
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), OrderSet::IssueOrder(), m_enabled, m_queue_wnd, and ClientApp::Orders().
Referenced by QueueItemClickedSlot(), and ResearchWnd().
DoLayout()
void ResearchWnd::DoLayout (bool init = false) private
References GetOptionsDB(), m_queue_wnd, m_research_info_panel, and m_tech_tree_wnd.
Referenced by CompleteConstruction(), and SizeMove().
EnableOrderIssuing()
void ResearchWnd::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this ResearchWnd.
References m_enabled, and m_queue_wnd.
HidePedia()
void ResearchWnd::HidePedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
PediaVisible()
bool ResearchWnd::PediaVisible ()
References m_tech_tree_wnd.
QueueItemClickedSlot()
void ResearchWnd::QueueItemClickedSlot (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References DeleteQueueItem(), m_enabled, m_queue_wnd, and ShowTech().
Referenced by ResearchWnd().
QueueItemDoubleClickedSlot()
void ResearchWnd::QueueItemDoubleClickedSlot (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References m_queue_wnd, and ShowTech().
Referenced by ResearchWnd().
QueueItemMoved()
void ResearchWnd::QueueItemMoved (const GG::ListBox::iterator & row_it, const GG::ListBox::iterator & original_position_it)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References ALL_EMPIRES, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), OrderSet::IssueOrder(), m_enabled, m_queue_wnd, and ClientApp::Orders().
Referenced by ResearchWnd().
QueueItemPaused()
void ResearchWnd::QueueItemPaused (GG::ListBox::iterator it, bool pause) private
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), OrderSet::IssueOrder(), m_enabled, m_queue_wnd, ClientApp::Orders(), and Empire::UpdateResearchQueue().
Referenced by ResearchWnd().
Refresh()
void ResearchWnd::Refresh ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References anonymous_namespace{AIWrapper.cpp}::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), m_empire_connection, ResearchQueueChangedSlot(), and Update().
Referenced by SetEmpireShown().
Render()
void ResearchWnd::Render () override
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
ResearchQueueChangedSlot()
void ResearchWnd::ResearchQueueChangedSlot () private
References m_tech_tree_wnd, UpdateInfoPanel(), and UpdateQueue().
Referenced by Refresh().
Reset()
void ResearchWnd::Reset ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_queue_wnd, m_tech_tree_wnd, UpdateInfoPanel(), and UpdateQueue().
Sanitize()
void ResearchWnd::Sanitize ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
SetEmpireShown()
void ResearchWnd::SetEmpireShown (int empire_id)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_empire_shown_id, and Refresh().
ShownEmpireID()
int ResearchWnd::ShownEmpireID () const
ShowPedia()
void ResearchWnd::ShowPedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
Referenced by ResearchWnd().
ShowTech()
void ResearchWnd::ShowTech (const std::string & tech_name, bool force = true)
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
Referenced by QueueItemClickedSlot(), and QueueItemDoubleClickedSlot().
SizeMove()
void ResearchWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References DoLayout().
TogglePedia()
void ResearchWnd::TogglePedia ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd.
Update()
void ResearchWnd::Update ()
Set encyclopedia entry to tech article for tech_name Selects and centers tech tech_name if tech is initially visible or if force is true(default).
References m_tech_tree_wnd, UpdateInfoPanel(), and UpdateQueue().
Referenced by Refresh().
UpdateInfoPanel()
void ResearchWnd::UpdateInfoPanel () private
Updates research summary at top left of production screen, and signals that the empire's minerals research pool has changed (propagates to the mapwnd to update indicator)
References GetEmpire(), Empire::GetResearchQueue(), m_empire_shown_id, m_research_info_panel, RE_RESEARCH, Empire::ResourceOutput(), ResearchQueue::TotalRPsSpent(), and UserString().
Referenced by ResearchQueueChangedSlot(), Reset(), and Update().
UpdateQueue()
void ResearchWnd::UpdateQueue () private
References QueueListBox::Clear(), DebugLogger, anonymous_namespace{AIWrapper.cpp}::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetResearchQueue(), m_empire_shown_id, m_queue_wnd, and QueueListBox::RowWidth().
Referenced by ResearchQueueChangedSlot(), Reset(), and Update().
Member Data Documentation
m_empire_connection
boost::signals2::connection ResearchWnd::m_empire_connection private
Referenced by Refresh(), and ~ResearchWnd().
m_empire_shown_id
int ResearchWnd::m_empire_shown_id private
Referenced by SetEmpireShown(), UpdateInfoPanel(), and UpdateQueue().
m_enabled
bool ResearchWnd::m_enabled private
Referenced by AddTechsToQueueSlot(), DeleteQueueItem(), EnableOrderIssuing(), QueueItemClickedSlot(), QueueItemMoved(), and QueueItemPaused().
m_queue_wnd
std::shared_ptr<ResearchQueueWnd> ResearchWnd::m_queue_wnd private
Referenced by CompleteConstruction(), DeleteQueueItem(), DoLayout(), EnableOrderIssuing(), QueueItemClickedSlot(), QueueItemDoubleClickedSlot(), QueueItemMoved(), QueueItemPaused(), ResearchWnd(), Reset(), and UpdateQueue().
m_research_info_panel
std::shared_ptr<ResourceInfoPanel> ResearchWnd::m_research_info_panel private
Referenced by CompleteConstruction(), DoLayout(), ResearchWnd(), and UpdateInfoPanel().
m_tech_tree_wnd
std::shared_ptr<TechTreeWnd> ResearchWnd::m_tech_tree_wnd private
Referenced by CenterOnTech(), CompleteConstruction(), DoLayout(), HidePedia(), PediaVisible(), ResearchQueueChangedSlot(), ResearchWnd(), Reset(), Sanitize(), ShowPedia(), ShowTech(), TogglePedia(), and Update().
The documentation for this class was generated from the following files:
ResearchWnd.h
ResearchWnd.cpp