FreeOrion: Moderator::ModeratorAction Class Reference
Moderator::ModeratorAction Class Reference
The abstract base class for serializable moderator actions.
#include <ModeratorAction.h>
Public Member Functions
ModeratorAction ()
virtual ~ModeratorAction ()
virtual std::string Dump () const
virtual void Execute () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
The abstract base class for serializable moderator actions.
Moderators make a change in the client, and the update is sent to the server which actually implements the action, and sends back the resulting gamestate (if applicable)
Constructor & Destructor Documentation
ModeratorAction()
Moderator::ModeratorAction::ModeratorAction () explicit
~ModeratorAction()
virtual Moderator::ModeratorAction::~ModeratorAction () inline virtual
Member Function Documentation
Dump()
virtual std::string Moderator::ModeratorAction::Dump () const inline virtual
Reimplemented in Moderator::CreatePlanet, Moderator::CreateSystem, Moderator::RemoveStarlane, Moderator::AddStarlane, Moderator::SetOwner, and Moderator::DestroyUniverseObject.
Referenced by PlayingGame::react().
Execute()
virtual void Moderator::ModeratorAction::Execute () const inline virtual
Reimplemented in Moderator::CreatePlanet, Moderator::CreateSystem, Moderator::RemoveStarlane, Moderator::AddStarlane, Moderator::SetOwner, and Moderator::DestroyUniverseObject.
Referenced by PlayingGame::react().
serialize()
template<typename Archive > template void Moderator::ModeratorAction::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this class was generated from the following files:
ModeratorAction.h
ModeratorAction.cpp
SerializeModeratorAction.cpp