FreeOrion: Empire Class Reference
Empire Class Reference
Class to maintain the state of a single empire.
#include <Empire.h>
Public Types
Iterator Types
typedef std::set< int >::const_iterator SystemIDItr
typedef std::vector< SitRepEntry >::const_iterator SitRepItr
Public Member Functions
Structors
Empire (const std::string &name, const std::string &player_name, int ID, const GG::Clr &color, bool authenticated)
basic constructor
~Empire ()
basic constructor
Accessors
const std::string & Name () const
Returns the Empire's name.
const std::string & PlayerName () const
Returns the Empire's player's name.
bool IsAuthenticated () const
Returns the Empire's player's authentication status.
int EmpireID () const
Returns the Empire's unique numeric ID.
const GG::Clr & Color () const
Returns the Empire's color.
int CapitalID () const
Returns the numeric ID of the empire's capital.
int SourceID () const
Return an object id that is owned by the empire or INVALID_OBJECT_ID.
std::shared_ptr< const UniverseObject > Source () const
Return an object that is owned by the empire or null.
std::string Dump () const
Returns the Empire's name.
const std::map< std::string, int > & ResearchedTechs () const
Returns the set of Tech names available to this empire.
const std::set< std::string > & AvailableBuildingTypes () const
Returns the set of BuildingType names availble to this empire.
std::set< int > AvailableShipDesigns () const
Returns the set of ShipDesign IDs available for this empire to build.
const std::set< int > & ShipDesigns () const
Returns the set of all ship design ids of this empire.
const std::set< std::string > & AvailableShipParts () const
Returns the set of ship part names this empire that the empire can currently build.
const std::set< std::string > & AvailableShipHulls () const
Returns the set of ship hull names that that the empire can currently build.
const std::string & TopPriorityEnqueuedTech () const
Returns the Empire's name.
const std::string & MostExpensiveEnqueuedTech () const
Returns the Empire's name.
const std::string & LeastExpensiveEnqueuedTech () const
Returns the Empire's name.
const std::string & MostRPSpentEnqueuedTech () const
Returns the Empire's name.
const std::string & MostRPCostLeftEnqueuedTech () const
Returns the Empire's name.
const std::string & TopPriorityResearchableTech () const
Returns the Empire's name.
const std::string & MostExpensiveResearchableTech () const
Returns the Empire's name.
const std::string & LeastExpensiveResearchableTech () const
Returns the Empire's name.
const std::string & MostRPSpentResearchableTech () const
Returns the Empire's name.
const std::string & MostRPCostLeftResearchableTech () const
Returns the Empire's name.
const Meter * GetMeter (const std::string &name) const
Returns the Empire's name.
std::map< std::string, Meter >::const_iterator meter_begin () const
Returns the Empire's name.
std::map< std::string, Meter >::const_iterator meter_end () const
Returns the Empire's name.
const ResearchQueue & GetResearchQueue () const
Returns the queue of techs being or queued to be researched.
const ProductionQueue & GetProductionQueue () const
Returns the queue of items being or queued to be produced.
bool ResearchableTech (const std::string &name) const
Returns true iff name is a tech that has not been researched, and has no unresearched prerequisites.
float ResearchProgress (const std::string &name) const
Returns the RPs spent towards tech name if it has partial research progress, or 0.0 if it is already researched.
bool TechResearched (const std::string &name) const
Returns true iff this tech has been completely researched.
bool HasResearchedPrereqAndUnresearchedPrereq (const std::string &name) const
Returns true iff this tech has some but not all prerequisites researched.
TechStatus GetTechStatus (const std::string &name) const
Returns the status (researchable, researched, unresearchable) for this tech for this.
bool BuildingTypeAvailable (const std::string &name) const
Returns true if the given building type is known to this empire, false if it is not.
bool ShipDesignAvailable (const ShipDesign &design) const
Returns true iff this ship design can be built by this empire.
bool ShipDesignAvailable (int ship_design_id) const
Returns true iff this ship design can be built by this empire. If no such ship design exists, returns false.
bool ShipDesignKept (int ship_design_id) const
Returns true iff the given ship design id is in the set of design ids of this empire. That is, it has been added to this empire.
bool ShipPartAvailable (const std::string &name) const
Returns true iff this ship part can be built by this empire. If no such ship part exists, returns false.
bool ShipHullAvailable (const std::string &name) const
Returns true iff this ship hull can be built by this empire. If no such ship hull exists, returns false.
float ProductionStatus (int i) const
Returns the PPs spent towards item i in the build queue if it has partial progress, -1.0 if there is no such index in the production queue.
std::pair< float, int > ProductionCostAndTime (const ProductionQueue::Element &element) const
Returns the total cost per item (blocksize 1) and the minimum number of turns required to produce the indicated item, or (-1.0, -1) if the item is unknown, unavailable, or invalid.
std::pair< float, int > ProductionCostAndTime (const ProductionQueue::ProductionItem &item, int location_id) const
Returns the Empire's name.
bool ProducibleItem (BuildType build_type, int location) const
Returns true iff this empire can produce the specified item at the specified location.
bool ProducibleItem (BuildType build_type, const std::string &name, int location) const
Returns true iff this empire can produce the specified item at the specified location.
bool ProducibleItem (BuildType build_type, int design_id, int location) const
Returns true iff this empire can produce the specified item at the specified location.
bool ProducibleItem (const ProductionQueue::ProductionItem &item, int location) const
Returns true iff this empire can produce the specified item at the specified location.
bool EnqueuableItem (BuildType build_type, const std::string &name, int location) const
Returns true iff this empire can enqueue the specified item at the specified location.
bool EnqueuableItem (const ProductionQueue::ProductionItem &item, int location) const
Returns true iff this empire can enqueue the specified item at the specified location.
bool HasExploredSystem (int ID) const
returns true if the given item is in the appropriate list, false if it is not.
bool Eliminated () const
whether this empire has lost the game
bool Won () const
whether this empire has won the game
bool Ready () const
Returns readiness status of empire.
int NumSitRepEntries (int turn=INVALID_GAME_TURN) const
number of entries in the SitRep.
const std::map< int, float > & SystemSupplyRanges () const
Returns distance in jumps away from each system that this empire can propagate supply.
const std::set< int > & SupplyUnobstructedSystems () const
Returns set of system ids that are able to propagate supply from one system to the next, or at which supply can be delivered to fleets if supply can reach the system from elsewhere, or in which planets can exchange supply between themselves (even if not leaving the system).
const bool PreservedLaneTravel (int start_system_id, int dest_system_id) const
Returns true if the specified lane travel is preserved against being blockaded (i.e., the empire has in the start system at least one fleet that meets the requirements to preserve the lane (which is determined in Empire::UpdateSupplyUnobstructedSystems().
const std::set< int > & ExploredSystems () const
returns set of ids of systems that this empire has explored
const std::map< int, std::set< int > > KnownStarlanes () const
returns map from system id (start) to set of system ids (endpoints) of all starlanes known to this empire
const std::map< int, std::set< int > > VisibleStarlanes () const
returns map from system id (start) to set of system ids (endpoints) of all starlanes visible to this empire this turn
SitRepItr SitRepBegin () const
starting iterator for sitrep entries for this empire
SitRepItr SitRepEnd () const
end iterator for sitreps
float ProductionPoints () const
Returns the empire's current production point output (this is available industry not including stockpile)
const std::shared_ptr< ResourcePool > GetResourcePool (ResourceType resource_type) const
Returns ResourcePool for resource_type or 0 if no such ResourcePool exists.
float ResourceStockpile (ResourceType type) const
returns current stockpiled amount of resource type
float ResourceOutput (ResourceType type) const
returns amount of resource type being generated by ResourceCenters
float ResourceAvailable (ResourceType type) const
returns amount of resource type immediately available. This = production + stockpile
const PopulationPool & GetPopulationPool () const
Returns PopulationPool.
float Population () const
returns total Population of empire
Mutators
void SetCapitalID (int id)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Meter * GetMeter (const std::string &name)
Returns the meter with the indicated name if it exists, or nullptr.
void BackPropagateMeters ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
void PlaceTechInQueue (const std::string &name, int pos=-1)
Adds tech to the research queue, placing it before position pos.
void RemoveTechFromQueue (const std::string &name)
Removes tech with name from the research queue, if it is in the research queue already.
void PauseResearch (const std::string &name)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
void ResumeResearch (const std::string &name)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
void SetTechResearchProgress (const std::string &name, float progress)
Sets research progress of tech with name to progress.
void PlaceProductionOnQueue (const ProductionQueue::ProductionItem &item, boost::uuids::uuid uuid, int number, int blocksize, int location, int pos=-1)
Adds the indicated build to the production queue, placing it before position pos.
void SplitIncompleteProductionItem (int index, boost::uuids::uuid uuid)
Adds a copy of the production item at position index below it in the queue, with one less quantity.
void DuplicateProductionItem (int index, boost::uuids::uuid uuid)
Adds a copy of the production item at position index below it in the queue, with no progress.
void SetProductionQuantity (int index, int quantity)
Changes the remaining number to produce for queue item index to quantity.
void SetProductionQuantityAndBlocksize (int index, int quantity, int blocksize)
Changes the remaining number and blocksize to produce for queue item index to quantity and blocksize.
void SetProductionRallyPoint (int index, int rally_point_id=INVALID_OBJECT_ID)
Sets the rally point for ships produced by this produce, to which they are automatically ordered to move after they are produced.
void MoveProductionWithinQueue (int index, int new_index)
Moves tech from the production queue, if it is in the production queue already.
void RemoveProductionFromQueue (int index)
Removes the produce at position index in the production queue, if such an index exists.
void PauseProduction (int index)
Sets the production of produce at postion index paused, if such an index exists.
void ResumeProduction (int index)
Sets the production of produce at postion index unpaused, if such an index exists.
void AllowUseImperialPP (int index, bool allow=true)
Allows or disallows the use of the imperial stockpile for production.
void AddNewlyResearchedTechToGrantAtStartOfNextTurn (const std::string &name)
Inserts the given Tech into the Empire's list of innovations. Call ApplyAddedTech to make it effective.
void ApplyNewTechs ()
Moves all Techs from the Empire's list of innovations into the Empire's list of available technologies.
void UnlockItem (const UnlockableItem &item)
Adds a given producible item (Building, Ship Hull, Ship part) to the list of available items.
void AddBuildingType (const std::string &name)
Inserts the given BuildingType into the Empire's list of available BuldingTypes.
void AddShipPart (const std::string &name)
Inserts the given ShipPart into the Empire's list of available ShipParts.
void AddHullType (const std::string &name)
Inserts the given ship HullType into the Empire's list of available BuldingTypes.
void AddExploredSystem (int ID)
Inserts the given ID into the Empire's list of explored systems.
void AddShipDesign (int ship_design_id, int next_design_id=INVALID_DESIGN_ID)
inserts given design id into the empire's set of designs in front of next design
int AddShipDesign (ShipDesign *ship_design)
inserts given ShipDesign into the Universe, adds the design's id to the Empire's set of ids, and returns the new design's id, which is INVALID_OBJECT_ID on failure. If successful, universe takes ownership of passed ShipDesign.
std::string NewShipName ()
generates a random ship name, appending II, III, etc., to it if it has been used before by this empire
void Eliminate ()
Marks empire as eliminated and cleans up empire after it is eliminated. Queues are cleared, capital is reset, and other state info not relevant to an eliminated empire is cleared.
void Win (const std::string &reason)
Marks this empire as having won for this reason, and sends the appropriate sitreps.
void SetReady (bool ready)
Marks this empire with readiness status.
void AddSitRepEntry (const SitRepEntry &entry)
Inserts the a pointer to given SitRep entry into the empire's sitrep list.
void ClearSitRep ()
Clears all sitrep entries.
void RemoveTech (const std::string &name)
Removes the given Tech from the empire's list.
void LockItem (const UnlockableItem &item)
Removes a given producible item (Building, Ship Hull, Ship Part) from the list of available items.
void RemoveBuildingType (const std::string &name)
Removes the given BuildingType from the empire's list.
void RemoveShipPart (const std::string &name)
Removes the given ShipPart from the empire's list.
void RemoveHullType (const std::string &name)
Removes the given HullType from the empire's list.
void RemoveShipDesign (int ship_design_id)
Removes the ShipDesign with the given id from the empire's set.
void UpdateSystemSupplyRanges (const std::set< int > &known_objects)
Calculates ranges that systems can send fleet and resource supplies, using the specified st of known_objects as the source for supply- producing objects and systems through which it can be propagated.
void UpdateSystemSupplyRanges ()
Calculates ranges that systems can send fleet and resource supplies.
void UpdateSupplyUnobstructedSystems (const std::set< int > &known_systems, bool precombat=false)
Calculates systems that can propagate supply (fleet or resource) using the specified set of known_systems.
void UpdateSupplyUnobstructedSystems (bool precombat=false)
Calculates systems that can propagate supply using this empire's own / internal list of explored systems.
void UpdateUnobstructedFleets ()
Updates fleet ArrivalStarlane to flag fleets of this empire that are not blockaded post-combat must be done after all noneliminated empires have updated their unobstructed systems*.
void RecordPendingLaneUpdate (int start_system_id, int dest_system_id)
Records, in a list of pending updates, the start_system exit lane to the specified destination as accessible to this empire.
void UpdatePreservedLanes ()
Processes all the pending lane access updates.
void CheckProductionProgress ()
Checks for production projects that have been completed, and places them at their respective production sites.
std::vector< std::string > CheckResearchProgress ()
Checks for tech projects that have been completed, and returns a vector of the techs that should be added to the known techs list.
void CheckTradeSocialProgress ()
Eventually : Will check for social projects that have been completed and / or process ongoing social projects...
void SetColor (const GG::Clr &color)
Mutator for empire color.
void SetName (const std::string &name)
Mutator for empire name.
void SetPlayerName (const std::string &player_name)
Mutator for empire's player name.
void SetResourceStockpile (ResourceType resource_type, float stockpile)
Sets current stockpile amount of indicated resource_type.
void InitResourcePools ()
Determines ResourceCenters that can provide resources for this empire and sets the supply groups used for each ResourcePool as appropriate for each resource.
void UpdateResourcePools ()
Resets production of resources and calculates allocated resources (on each item in queues and overall) for each resource by calling UpdateResearchQueue, UpdateProductionQueue, UpdateTradeSpending.
void UpdateResearchQueue ()
Calls Update() on empire's research queue, which recalculates the RPs spent on and number of turns left for each tech in the queue.
void UpdateProductionQueue ()
Calls Update() on empire's production queue, which recalculates the PPs spent on and number of turns left for each project in the queue.
void UpdateTradeSpending ()
Eventually: Calls appropriate subsystem Update to calculate trade spent on social projects and maintenance of buildings.
void UpdatePopulationGrowth ()
Has m_population_pool recalculate all PopCenters' and empire's total expected population growth.
void ResetMeters ()
Resets empire meters.
void UpdateOwnedObjectCounters ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
void SetAuthenticated (bool authenticated=true)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
int TotalShipsOwned () const
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
int TotalShipPartsOwned () const
Total number of parts for all owned ships in this empire.
int TotalBuildingsOwned () const
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesShipsOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & ShipPartsOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< ShipPartClass, int > & ShipPartClassOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesColoniesOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
int & OutpostsOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & BuildingTypesOwned ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & EmpireShipsDestroyed ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsDestroyed ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesShipsDestroyed ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesPlanetsInvaded ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsInProduction ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesShipsProduced ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsProduced ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesShipsLost ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsLost ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesShipsScrapped ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< int, int > & ShipDesignsScrapped ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesPlanetsDepoped ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & SpeciesPlanetsBombed ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & BuildingTypesProduced ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
std::map< std::string, int > & BuildingTypesScrapped ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Static Public Member Functions
static void ConquerProductionQueueItemsAtLocation (int location_id, int empire_id)
Processes Builditems on queues of empires other than the indicated empires, at the location with id location_id and, as appropriate, adds them to the build queue of the indicated empires (if it is an empire), deletes them, or leaves them on the build queue of their current empire.
Public Attributes
boost::signals2::signal< void()> ShipDesignsChangedSignal
Private Member Functions
Empire ()
void Init ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_authenticated
Empire's Player's authentication flag.
std::set< std::string > m_available_building_types
list of acquired BuildingType.
std::set< std::string > m_available_hull_types
list of acquired ship HullType. These are string names referencing HullType objects
std::set< std::string > m_available_ship_parts
List of acquired ShipPart referenced by name.
std::map< std::string, int > m_building_types_owned
how many buildings does this empire currently own?
std::map< std::string, int > m_building_types_produced
how many buildings of each type has this empire produced?
std::map< std::string, int > m_building_types_scrapped
how many buildings of each type has this empire scrapped?
int m_capital_id = INVALID_OBJECT_ID
the ID of the empire's capital planet
GG::Clr m_color
Empire's color.
bool m_eliminated = false
Whether the empire has lost.
std::map< int, int > m_empire_ships_destroyed
how many ships of each empire has this empire destroyed?
std::set< int > m_explored_systems
systems explored by this empire
int m_id = ALL_EMPIRES
Empire's unique numeric id.
std::set< int > m_known_ship_designs
ids of ship designs in the universe that this empire knows about
std::map< std::string, Meter > m_meters
empire meters, including ratings scales used by species to judge empires
std::string m_name
Empire's name.
std::set< std::string > m_newly_researched_techs
names of researched but not yet effective technologies, and turns on which they were acquired.
int m_outposts_owned = 0
how many uncolonized outposts does this empire currently own?
std::map< int, std::set< int > > m_pending_system_exit_lanes
pending updates to m_preserved_system_exit_lanes
std::string m_player_name
Empire's Player's name.
PopulationPool m_population_pool
std::map< int, std::set< int > > m_preserved_system_exit_lanes
for each system known to this empire, the set of exit lanes preserved for fleet travel even if otherwise blockaded
ProductionQueue m_production_queue
the queue of items being or waiting to be built
bool m_ready
readiness status of empire
std::map< std::string, float > m_research_progress
progress of partially-researched techs; fully researched techs are removed
ResearchQueue m_research_queue
the queue of techs being or waiting to be researched
std::map< ResourceType, std::shared_ptr< ResourcePool > > m_resource_pools
std::map< int, int > m_ship_designs_destroyed
how many ships of each design has this empire destroyed?
std::map< int, int > m_ship_designs_in_production
how many ships of each design has this empire in active production in its production queue
std::map< int, int > m_ship_designs_lost
how many ships of each design has this empire lost in combat?
std::map< int, int > m_ship_designs_owned
how many ships of each design does this empire currently own?
std::map< int, int > m_ship_designs_produced
how many ships of each design has this empire produced?
std::map< int, int > m_ship_designs_scrapped
how many ships of each design has this empire scrapped?
std::map< std::string, int > m_ship_names_used
map from name to number of times used
std::map< ShipPartClass, int > m_ship_part_class_owned
how many ship parts are currently owned, indexed by ShipPartClass
std::map< std::string, int > m_ship_parts_owned
How many ShipParts are currently owned, indexed by ShipPart.
std::vector< SitRepEntry > m_sitrep_entries
The Empire's sitrep entries.
int m_source_id = INVALID_OBJECT_ID
The source id is the id of any object owned by the empire.
std::map< std::string, int > m_species_colonies_owned
how many colonies of each species does this empire currently own?
std::map< std::string, int > m_species_planets_bombed
how many planets populated by each species has this empire bombarded?
std::map< std::string, int > m_species_planets_depoped
how many planets populated by each species have depopulated while owned by this empire?
std::map< std::string, int > m_species_planets_invaded
how many planets populated by each species has this empire captured?
std::map< std::string, int > m_species_ships_destroyed
how many ships crewed by each species has this empire destroyed?
std::map< std::string, int > m_species_ships_lost
how mahy ships crewed by each species has this empire lost in combat?
std::map< std::string, int > m_species_ships_owned
how many ships of each species does this empire currently own?
std::map< std::string, int > m_species_ships_produced
how many ships crewed by each species has this empire produced?
std::map< std::string, int > m_species_ships_scrapped
how many ships crewed by each species has this empire scrapped?
std::map< int, float > m_supply_system_ranges
number of starlane jumps away from each system (by id) supply can be conveyed. This is the number due to a system's contents conveying supply and is computed and set by UpdateSystemSupplyRanges
std::set< int > m_supply_unobstructed_systems
ids of system that don't block supply from flowing
std::map< std::string, int > m_techs
names of researched technologies, and turns on which they were acquired.
std::set< std::string > m_victories
The ways that the empire has won, if any.
Friends
class boost::serialization::access
class EmpireManager
Detailed Description
Class to maintain the state of a single empire.
In both the client and server, Empires are managed by a subclass of EmpireManager, and can be accessed from other modules by using the EmpireManager::Lookup() method to obtain a pointer.
Member Typedef Documentation
SitRepItr
typedef std::vector<SitRepEntry>::const_iterator Empire::SitRepItr
SystemIDItr
typedef std::set<int>::const_iterator Empire::SystemIDItr
Constructor & Destructor Documentation
Empire() [1/2]
Empire::Empire (const std::string & name, const std::string & player_name, int ID, const GG::Clr & color, bool authenticated)
basic constructor
References DebugLogger, and Init().
~Empire()
Empire::~Empire ()
basic constructor
References ClearSitRep().
Empire() [2/2]
Empire::Empire () private
References Init().
Member Function Documentation
AddBuildingType()
void Empire::AddBuildingType (const std::string & name)
Inserts the given BuildingType into the Empire's list of available BuldingTypes.
References AddSitRepEntry(), CreateBuildingTypeUnlockedSitRep(), ErrorLogger, GetBuildingType(), m_available_building_types, and BuildingType::Producible().
Referenced by UnlockItem().
AddExploredSystem()
void Empire::AddExploredSystem (int ID)
Inserts the given ID into the Empire's list of explored systems.
References ErrorLogger, m_explored_systems, and Objects().
Referenced by Fleet::MovementPhase(), and SetEmpireHomeworld().
AddHullType()
void Empire::AddHullType (const std::string & name)
Inserts the given ship HullType into the Empire's list of available BuldingTypes.
References AddSitRepEntry(), CreateShipHullUnlockedSitRep(), ErrorLogger, GetHullType(), m_available_hull_types, and HullType::Producible().
Referenced by UnlockItem().
AddNewlyResearchedTechToGrantAtStartOfNextTurn()
void Empire::AddNewlyResearchedTechToGrantAtStartOfNextTurn (const std::string & name)
Inserts the given Tech into the Empire's list of innovations. Call ApplyAddedTech to make it effective.
References ErrorLogger, GetTech(), m_newly_researched_techs, and m_techs.
Referenced by Effect::GiveEmpireTech::Execute(), ServerApp::PostCombatProcessTurns(), and UnlockItem().
AddShipDesign() [1/2]
void Empire::AddShipDesign (int ship_design_id, int next_design_id = INVALID_DESIGN_ID)
inserts given design id into the empire's set of designs in front of next design
References EmpireID(), ErrorLogger, Universe::GetShipDesign(), GetUniverse(), m_known_ship_designs, ShipDesign::Name(), ShipDesignsChangedSignal, and TraceLogger.
Referenced by AddShipDesign(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), and UnlockItem().
AddShipDesign() [2/2]
int Empire::AddShipDesign (ShipDesign * ship_design)
inserts given ShipDesign into the Universe, adds the design's id to the Empire's set of ids, and returns the new design's id, which is INVALID_OBJECT_ID on failure. If successful, universe takes ownership of passed ShipDesign.
References AddShipDesign(), Universe::beginShipDesigns(), Universe::endShipDesigns(), ErrorLogger, GetUniverse(), ShipDesign::ID(), Universe::InsertShipDesign(), and INVALID_OBJECT_ID.
AddShipPart()
void Empire::AddShipPart (const std::string & name)
Inserts the given ShipPart into the Empire's list of available ShipParts.
References AddSitRepEntry(), CreateShipPartUnlockedSitRep(), ErrorLogger, GetShipPart(), and m_available_ship_parts.
Referenced by UnlockItem().
AddSitRepEntry()
void Empire::AddSitRepEntry (const SitRepEntry & entry)
Inserts the a pointer to given SitRep entry into the empire's sitrep list.
Warning
When you call this method, you are transferring ownership of the entry object to the Empire. The object pointed to by 'entry' will be deallocated when the empire's sitrep is cleared. Be careful you do not have any references to SitRepEntries lying around when this happens. You must pass in a dynamically allocated sitrep entry
References m_sitrep_entries.
Referenced by AddBuildingType(), AddHullType(), AddShipPart(), ApplyNewTechs(), CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps(), Effect::GenerateSitRepMessage::Execute(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep(), and anonymous_namespace{ServerApp.cpp}::HandleColonization().
AllowUseImperialPP()
void Empire::AllowUseImperialPP (int index, bool allow = true)
Allows or disallows the use of the imperial stockpile for production.
References DebugLogger, ErrorLogger, m_production_queue, and ProductionQueue::size().
ApplyNewTechs()
void Empire::ApplyNewTechs ()
Moves all Techs from the Empire's list of innovations into the Empire's list of available technologies.
References AddSitRepEntry(), CreateTechResearchedSitRep(), CurrentTurn(), ErrorLogger, GetTech(), m_newly_researched_techs, m_techs, Tech::UnlockedItems(), and UnlockItem().
Referenced by ServerApp::PostCombatProcessTurns().
AvailableBuildingTypes()
const std::set< std::string > & Empire::AvailableBuildingTypes () const
Returns the set of BuildingType names availble to this empire.
References m_available_building_types.
Referenced by ObjectListWnd::ObjectRightClicked(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and FreeOrionPython::WrapEmpire().
AvailableShipDesigns()
std::set< int > Empire::AvailableShipDesigns () const
Returns the set of ShipDesign IDs available for this empire to build.
References m_known_ship_designs, and ShipDesignAvailable().
Referenced by ObjectListWnd::ObjectRightClicked(), and FreeOrionPython::WrapEmpire().
AvailableShipHulls()
const std::set< std::string > & Empire::AvailableShipHulls () const
Returns the set of ship hull names that that the empire can currently build.
References m_available_hull_types.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and FreeOrionPython::WrapEmpire().
AvailableShipParts()
const std::set< std::string > & Empire::AvailableShipParts () const
Returns the set of ship part names this empire that the empire can currently build.
References m_available_ship_parts.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and FreeOrionPython::WrapEmpire().
BackPropagateMeters()
void Empire::BackPropagateMeters ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References m_meters.
BuildingTypeAvailable()
bool Empire::BuildingTypeAvailable (const std::string & name) const
Returns true if the given building type is known to this empire, false if it is not.
References m_available_building_types.
Referenced by Condition::anonymous_namespace{Conditions.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch::operator()(), ProducibleItem(), and FreeOrionPython::WrapEmpire().
BuildingTypesOwned()
std::map<std::string, int>& Empire::BuildingTypesOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap().
BuildingTypesProduced()
std::map<std::string, int>& Empire::BuildingTypesProduced () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
BuildingTypesScrapped()
std::map<std::string, int>& Empire::BuildingTypesScrapped () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
CapitalID()
int Empire::CapitalID () const
Returns the numeric ID of the empire's capital.
References m_capital_id.
Referenced by CheckProductionProgress(), SidePanel::PlanetPanel::CompleteConstruction(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), PartsListBox::Populate(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), FreeOrionPython::WrapEmpire(), and MapWnd::ZoomToHomeSystem().
CheckProductionProgress()
void Empire::CheckProductionProgress ()
Checks for production projects that have been completed, and places them at their respective production sites.
Which projects have been completed is determined by the results of previously-called Update() on the production queue (which determines how much PP each project receives but does not actually spend them). This function spends the PP, removes complete items from the queue and creates the results in the universe.
References AddSitRepEntry(), Meter::BackPropagate(), CapitalID(), CreateBuildingBuiltSitRep(), CreateShipBlockBuiltSitRep(), CreateShipBuiltSitRep(), Meter::Current(), CurrentTurn(), DebugLogger, anonymous_namespace{Empire.cpp}::EPSILON, ErrorLogger, ObjectMap::get(), GetShipDesign(), GetUniverse(), UniverseObject::ID(), if(), Universe::InsertNew(), INVALID_OBJECT_ID, m_building_types_produced, m_id, m_production_queue, m_ship_designs_produced, m_species_ships_produced, NewShipName(), Objects(), ProducibleItem(), ProductionCostAndTime(), RE_INDUSTRY, Meter::SetCurrent(), Fleet::SetNextAndPreviousSystems(), SetResourceStockpile(), and to_string().
Referenced by ServerApp::PostCombatProcessTurns().
CheckResearchProgress()
std::vector< std::string > Empire::CheckResearchProgress ()
Checks for tech projects that have been completed, and returns a vector of the techs that should be added to the known techs list.
References anonymous_namespace{Empire.cpp}::EPSILON, ErrorLogger, GetTech(), GetTechManager(), GetTechStatus(), m_id, m_research_progress, m_research_queue, m_resource_pools, Tech::PerTurnCost(), RE_RESEARCH, Tech::ResearchCost(), ResearchProgress(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), and TS_RESEARCHABLE.
Referenced by ServerApp::PostCombatProcessTurns().
CheckTradeSocialProgress()
void Empire::CheckTradeSocialProgress ()
Eventually : Will check for social projects that have been completed and / or process ongoing social projects...
(not sure exactly what form "social projects" will take or how they will work). Also will update the empire's trade stockpile to account for trade production and expenditures. Currently: Deducts cost of maintenance of buildings from empire's trade stockpile
References m_resource_pools, and RE_TRADE.
Referenced by ServerApp::PostCombatProcessTurns().
ClearSitRep()
void Empire::ClearSitRep ()
Clears all sitrep entries.
References m_sitrep_entries.
Referenced by ~Empire().
Color()
const GG::Clr & Empire::Color () const
Returns the Empire's color.
References m_color.
Referenced by anonymous_namespace{SystemIcon.cpp}::ColorNameByOwners(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ColorByOwner::Decorate(), anonymous_namespace{SitRepPanel.cpp}::ColorEmpire::Decorate(), anonymous_namespace{CombatEvents.cpp}::EmpireColorWrappedText(), MessageWnd::HandleDiplomaticStatusChange(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), ModeratorActionsWnd::Refresh(), MapWnd::SetFleetMovementLine(), MapWnd::SetProjectedFleetMovementLine(), CombatSummary::SideColor(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), and FreeOrionPython::WrapEmpire().
ConquerProductionQueueItemsAtLocation()
void Empire::ConquerProductionQueueItemsAtLocation (int location_id, int empire_id) static
Processes Builditems on queues of empires other than the indicated empires, at the location with id location_id and, as appropriate, adds them to the build queue of the indicated empires (if it is an empire), deletes them, or leaves them on the build queue of their current empire.
References ALL_EMPIRES, ProductionQueue::begin(), ProductionQueue::ProductionItem::build_type, CR_CAPTURE, CR_DESTROY, DebugLogger, Empires(), ProductionQueue::end(), ProductionQueue::erase(), ErrorLogger, GetBuildingType(), BuildingType::GetCaptureResult(), GetEmpire(), INVALID_CAPTURE_RESULT, INVALID_OBJECT_ID, m_production_queue, ProductionQueue::ProductionItem::name, ProductionQueue::Element::progress, and ProductionQueue::push_back().
Referenced by Planet::Conquer(), and anonymous_namespace{ServerApp.cpp}::HandleGifting().
Dump()
std::string Empire::Dump () const
Returns the Empire's name.
References m_capital_id, m_id, m_meters, m_name, to_string(), and UserString().
DuplicateProductionItem()
void Empire::DuplicateProductionItem (int index, boost::uuids::uuid uuid)
Adds a copy of the production item at position index below it in the queue, with no progress.
References DebugLogger, m_production_queue, PlaceProductionOnQueue(), and ProductionQueue::size().
Eliminate()
void Empire::Eliminate ()
Marks empire as eliminated and cleans up empire after it is eliminated. Queues are cleared, capital is reset, and other state info not relevant to an eliminated empire is cleared.
References ResearchQueue::clear(), ProductionQueue::clear(), CreateEmpireEliminatedSitRep(), EmpireID(), Empires(), INVALID_OBJECT_ID, m_capital_id, m_eliminated, m_population_pool, m_production_queue, m_research_progress, m_research_queue, m_resource_pools, m_sitrep_entries, m_supply_system_ranges, m_supply_unobstructed_systems, and PopulationPool::SetPopCenters().
Referenced by ServerApp::EliminatePlayer().
Eliminated()
bool Empire::Eliminated () const
whether this empire has lost the game
References m_eliminated.
Referenced by ServerApp::AddPlayerIntoGame(), ServerFSM::HandleNonLobbyDisconnection(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), WaitingForTurnEnd::react(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), UpdateEmpireSupply(), and FreeOrionPython::WrapEmpire().
EmpireID()
int Empire::EmpireID () const
Returns the Empire's unique numeric ID.
References m_id.
Referenced by AddShipDesign(), Eliminate(), anonymous_namespace{EmpireWrapper.cpp}::EmpireFleetSupplyableSystemIDsP(), anonymous_namespace{MapWnd.cpp}::GetNearestSupplyRoute(), BarSizer::GetSideBarSize(), EmpireManager::InsertEmpire(), anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemP(), KnownStarlanes(), anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesP(), WaitingForTurnEnd::react(), anonymous_namespace{CombatReportData.cpp}::SafeEmpireId(), SetEmpireHomeworld(), EncyclopediaDetailPanel::SetItem(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), UpdateProductionQueue(), UpdateSupplyUnobstructedSystems(), UpdateSystemSupplyRanges(), UpdateUnobstructedFleets(), Win(), and FreeOrionPython::WrapEmpire().
EmpireShipsDestroyed()
std::map<int, int>& Empire::EmpireShipsDestroyed () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
EnqueuableItem() [1/2]
bool Empire::EnqueuableItem (BuildType build_type, const std::string & name, int location) const
Returns true iff this empire can enqueue the specified item at the specified location.
References ObjectMap::get(), GetBuildingType(), m_id, and Objects().
Referenced by BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), BuildDesignatorWnd::BuildItemRequested(), EnqueuableItem(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueBuildingProductionOrder(), ObjectListWnd::ObjectRightClicked(), and PlaceProductionOnQueue().
EnqueuableItem() [2/2]
bool Empire::EnqueuableItem (const ProductionQueue::ProductionItem & item, int location) const
Returns true iff this empire can enqueue the specified item at the specified location.
References ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, EnqueuableItem(), ProductionQueue::ProductionItem::name, and ProducibleItem().
ExploredSystems()
const std::set< int > & Empire::ExploredSystems () const
returns set of ids of systems that this empire has explored
References m_explored_systems.
Referenced by MapWnd::DispatchFleetsExploring(), and FreeOrionPython::WrapEmpire().
GetMeter() [1/2]
const Meter * Empire::GetMeter (const std::string & name) const
Returns the Empire's name.
References m_meters.
Referenced by ValueRef::ComplexVariable< T >::Eval(), Effect::SetEmpireMeter::Execute(), Condition::EmpireMeterValue::Match(), SidePanel::PlanetPanel::Refresh(), MapWnd::RefreshDetectionIndicator(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update().
GetMeter() [2/2]
Meter * Empire::GetMeter (const std::string & name)
Returns the meter with the indicated name if it exists, or nullptr.
References m_meters.
GetPopulationPool()
const PopulationPool & Empire::GetPopulationPool () const
Returns PopulationPool.
References m_population_pool.
Referenced by MapWnd::RefreshPopulationIndicator().
GetProductionQueue()
const ProductionQueue & Empire::GetProductionQueue () const
Returns the queue of items being or queued to be produced.
References m_production_queue.
Referenced by anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), BuildDesignatorWnd::CenterOnBuild(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), ProductionWnd::DeleteQueueItem(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::operator()(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P(), ProductionWnd::QueueItemDuped(), ProductionWnd::QueueItemMoved(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), MapWnd::RefreshIndustryResourceIndicator(), BuildDesignatorWnd::SetBuild(), BuildingsPanel::Update(), ProductionWnd::UpdateInfoPanel(), ProductionWnd::UpdateQueue(), FreeOrionPython::WrapEmpire(), and MapWnd::ZoomToSystemWithWastedPP().
GetResearchQueue()
const ResearchQueue & Empire::GetResearchQueue () const
Returns the queue of techs being or queued to be researched.
References m_research_queue.
Referenced by ResearchWnd::AddTechsToQueueSlot(), ValueRef::ComplexVariable< T >::Eval(), MapWnd::RefreshResearchResourceIndicator(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), ResearchWnd::UpdateInfoPanel(), ResearchWnd::UpdateQueue(), and FreeOrionPython::WrapEmpire().
GetResourcePool()
const std::shared_ptr< ResourcePool > Empire::GetResourcePool (ResourceType resource_type) const
Returns ResourcePool for resource_type or 0 if no such ResourcePool exists.
References m_resource_pools.
Referenced by anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P(), ProductionPoints(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshResearchResourceIndicator(), ProductionQueue::Update(), ProductionWnd::UpdateInfoPanel(), FreeOrionPython::WrapEmpire(), and MapWnd::ZoomToSystemWithWastedPP().
GetTechStatus()
TechStatus Empire::GetTechStatus (const std::string & name) const
Returns the status (researchable, researched, unresearchable) for this tech for this.
References HasResearchedPrereqAndUnresearchedPrereq(), ResearchableTech(), TechResearched(), TS_COMPLETE, TS_HAS_RESEARCHED_PREREQ, TS_RESEARCHABLE, and TS_UNRESEARCHABLE.
Referenced by TechTreeWnd::AddTechToResearchQueue(), TechTreeWnd::CenterOnTech(), CheckResearchProgress(), TechRowBrowseWnd(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), ResearchQueue::Update(), and FreeOrionPython::WrapEmpire().
HasExploredSystem()
bool Empire::HasExploredSystem (int ID) const
returns true if the given item is in the appropriate list, false if it is not.
References m_explored_systems.
Referenced by MapWnd::DispatchFleetsExploring(), SystemIcon::MouseEnter(), Condition::anonymous_namespace{Conditions.cpp}::ExploredByEmpireSimpleMatch::operator()(), and FreeOrionPython::WrapEmpire().
HasResearchedPrereqAndUnresearchedPrereq()
bool Empire::HasResearchedPrereqAndUnresearchedPrereq (const std::string & name) const
Returns true iff this tech has some but not all prerequisites researched.
References GetTech(), m_techs, and Tech::Prerequisites().
Referenced by GetTechStatus().
Init()
void Empire::Init () private
References m_eliminated, m_meters, m_resource_pools, RE_INDUSTRY, RE_RESEARCH, RE_TRADE, and UserStringNop.
Referenced by Empire().
InitResourcePools()
void Empire::InitResourcePools ()
Determines ResourceCenters that can provide resources for this empire and sets the supply groups used for each ResourcePool as appropriate for each resource.
call UpdateResourceSupply before calling this.
References GetSupplyManager(), m_id, m_population_pool, m_resource_pools, Objects(), RE_INDUSTRY, RE_RESEARCH, RE_TRADE, and PopulationPool::SetPopCenters().
Referenced by UpdateEmpireSupply().
IsAuthenticated()
bool Empire::IsAuthenticated () const
Returns the Empire's player's authentication status.
References m_authenticated.
KnownStarlanes()
const std::map< int, std::set< int > > Empire::KnownStarlanes () const
returns map from system id (start) to set of system ids (endpoints) of all starlanes known to this empire
References EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), GetUniverse(), m_id, Objects(), and TraceLogger.
Referenced by anonymous_namespace{MapWnd.cpp}::AddNeighboorsToSet(), anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemP(), and SupplyManager::Update().
LeastExpensiveEnqueuedTech()
const std::string & Empire::LeastExpensiveEnqueuedTech () const
Returns the Empire's name.
References ResearchQueue::empty(), anonymous_namespace{Empire.cpp}::EMPTY_STRING, GetTech(), m_id, m_research_queue, ResearchQueue::Element::name, and Tech::ResearchCost().
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().
LeastExpensiveResearchableTech()
const std::string & Empire::LeastExpensiveResearchableTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING.
Referenced by ValueRef::ComplexVariable< T >::Eval().
LockItem()
void Empire::LockItem (const UnlockableItem & item)
Removes a given producible item (Building, Ship Hull, Ship Part) from the list of available items.
References ErrorLogger, GetPredefinedShipDesignManager(), RemoveBuildingType(), RemoveHullType(), RemoveShipDesign(), RemoveShipPart(), and RemoveTech().
meter_begin()
std::map<std::string, Meter>::const_iterator Empire::meter_begin () const inline
Returns the Empire's name.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
meter_end()
std::map<std::string, Meter>::const_iterator Empire::meter_end () const inline
Returns the Empire's name.
References EmpireManager::BackPropagateMeters(), anonymous_namespace{XMLDoc.cpp}::element, INVALID_DESIGN_ID, INVALID_GAME_TURN, INVALID_OBJECT_ID, anonymous_namespace{ServerWrapper.cpp}::SetName(), anonymous_namespace{AIWrapper.cpp}::UpdateProductionQueue(), anonymous_namespace{AIWrapper.cpp}::UpdateResearchQueue(), and anonymous_namespace{AIWrapper.cpp}::UpdateResourcePools().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
MostExpensiveEnqueuedTech()
const std::string & Empire::MostExpensiveEnqueuedTech () const
Returns the Empire's name.
References ResearchQueue::empty(), anonymous_namespace{Empire.cpp}::EMPTY_STRING, GetTech(), m_id, m_research_queue, ResearchQueue::Element::name, and Tech::ResearchCost().
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().
MostExpensiveResearchableTech()
const std::string & Empire::MostExpensiveResearchableTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING.
Referenced by ValueRef::ComplexVariable< T >::Eval().
MostRPCostLeftEnqueuedTech()
const std::string & Empire::MostRPCostLeftEnqueuedTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING, GetTech(), ResearchQueue::InQueue(), m_id, m_research_progress, m_research_queue, and Tech::ResearchCost().
Referenced by ValueRef::Variable< ToType >::Eval().
MostRPCostLeftResearchableTech()
const std::string & Empire::MostRPCostLeftResearchableTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING.
MostRPSpentEnqueuedTech()
const std::string & Empire::MostRPSpentEnqueuedTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING, ResearchQueue::InQueue(), m_research_progress, and m_research_queue.
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().
MostRPSpentResearchableTech()
const std::string & Empire::MostRPSpentResearchableTech () const
Returns the Empire's name.
References anonymous_namespace{Empire.cpp}::EMPTY_STRING.
MoveProductionWithinQueue()
void Empire::MoveProductionWithinQueue (int index, int new_index)
Moves tech from the production queue, if it is in the production queue already.
References ProductionQueue::begin(), DebugLogger, ProductionQueue::erase(), ErrorLogger, ProductionQueue::insert(), m_production_queue, and ProductionQueue::size().
Name()
const std::string & Empire::Name () const
Returns the Empire's name.
References m_name.
Referenced by ResourceInfoPanel::ClearLocalInfo(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), EmpireManager::DumpDiplomacy(), anonymous_namespace{CombatEvents.cpp}::EmpireLink(), ValueRef::NameLookup::Eval(), Effect::SetEmpireMeter::Execute(), MessageWnd::HandleDiplomaticStatusChange(), AIClientApp::HandleMessage(), ModeratorActionsWnd::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), ResourceInfoPanel::SetEmpireID(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), CombatSummary::SideName(), FleetWnd::TitleText(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), and FreeOrionPython::WrapEmpire().
NewShipName()
std::string Empire::NewShipName ()
generates a random ship name, appending II, III, etc., to it if it has been used before by this empire
References m_ship_names_used, RandSmallInt(), RomanNumber(), UserString(), and UserStringList().
Referenced by CheckProductionProgress(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::CreateShip::Execute().
NumSitRepEntries()
int Empire::NumSitRepEntries (int turn = INVALID_GAME_TURN) const
number of entries in the SitRep.
References INVALID_GAME_TURN, and m_sitrep_entries.
Referenced by anonymous_namespace{EmpireWrapper.cpp}::GetSitRep(), and FreeOrionPython::WrapEmpire().
OutpostsOwned()
int& Empire::OutpostsOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertyNoKeyImpl().
PauseProduction()
void Empire::PauseProduction (int index)
Sets the production of produce at postion index paused, if such an index exists.
References DebugLogger, ErrorLogger, m_production_queue, and ProductionQueue::size().
PauseResearch()
void Empire::PauseResearch (const std::string & name)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References ResearchQueue::end(), ResearchQueue::find(), and m_research_queue.
PlaceProductionOnQueue()
void Empire::PlaceProductionOnQueue (const ProductionQueue::ProductionItem & item, boost::uuids::uuid uuid, int number, int blocksize, int location, int pos = -1)
Adds the indicated build to the production queue, placing it before position pos.
If pos < 0 or queue.size() <= pos, the build is placed at the end of the queue.
References ProductionQueue::begin(), ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, EnqueuableItem(), ErrorLogger, ProductionQueue::insert(), m_id, m_production_queue, MAX_PROD_QUEUE_SIZE, ProductionQueue::ProductionItem::name, ProducibleItem(), ProductionQueue::push_back(), and ProductionQueue::size().
Referenced by DuplicateProductionItem(), and SplitIncompleteProductionItem().
PlaceTechInQueue()
void Empire::PlaceTechInQueue (const std::string & name, int pos = -1)
Adds tech to the research queue, placing it before position pos.
If tech is already in the queue, it is moved to pos, then removed from its former position. If pos < 0 or queue.size() <= pos, tech is placed at the end of the queue. If tech is already available, no action is taken.
References ResearchQueue::begin(), ResearchQueue::end(), ResearchQueue::erase(), ResearchQueue::find(), GetTech(), ResearchQueue::insert(), m_newly_researched_techs, m_research_queue, m_techs, ResearchQueue::push_back(), Tech::Researchable(), ResearchQueue::size(), and TechResearched().
PlayerName()
const std::string & Empire::PlayerName () const
Returns the Empire's player's name.
References m_player_name.
Referenced by ServerApp::AddPlayerIntoGame(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), WaitingForTurnEnd::react(), and FreeOrionPython::WrapEmpire().
Population()
float Empire::Population () const
returns total Population of empire
References m_population_pool, and PopulationPool::Population().
Referenced by FreeOrionPython::WrapEmpire().
PreservedLaneTravel()
const bool Empire::PreservedLaneTravel (int start_system_id, int dest_system_id) const
Returns true if the specified lane travel is preserved against being blockaded (i.e., the empire has in the start system at least one fleet that meets the requirements to preserve the lane (which is determined in Empire::UpdateSupplyUnobstructedSystems().
References m_preserved_system_exit_lanes.
Referenced by Fleet::MovePath(), MapWnd::SetFleetMovementLine(), MapWnd::SetProjectedFleetMovementLine(), and FreeOrionPython::WrapEmpire().
ProducibleItem() [1/4]
bool Empire::ProducibleItem (BuildType build_type, int location) const
Returns true iff this empire can produce the specified item at the specified location.
References ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, m_id, Objects(), and WarnLogger.
Referenced by BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), CheckProductionProgress(), EnqueuableItem(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueBuildingProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueEnqueueShipProductionOrder(), ObjectListWnd::ObjectRightClicked(), PlaceProductionOnQueue(), ProducibleItem(), and ProductionQueue::Update().
ProducibleItem() [2/4]
bool Empire::ProducibleItem (BuildType build_type, const std::string & name, int location) const
Returns true iff this empire can produce the specified item at the specified location.
References BuildingTypeAvailable(), ErrorLogger, ObjectMap::get(), GetBuildingType(), m_id, and Objects().
ProducibleItem() [3/4]
bool Empire::ProducibleItem (BuildType build_type, int design_id, int location) const
Returns true iff this empire can produce the specified item at the specified location.
References ErrorLogger, ObjectMap::get(), GetShipDesign(), m_id, Objects(), ShipDesign::Producible(), ShipDesign::ProductionLocation(), and ShipDesignAvailable().
ProducibleItem() [4/4]
bool Empire::ProducibleItem (const ProductionQueue::ProductionItem & item, int location) const
Returns true iff this empire can produce the specified item at the specified location.
References ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, ProductionQueue::ProductionItem::name, and ProducibleItem().
ProductionCostAndTime() [1/2]
std::pair< float, int > Empire::ProductionCostAndTime (const ProductionQueue::Element & element) const
Returns the total cost per item (blocksize 1) and the minimum number of turns required to produce the indicated item, or (-1.0, -1) if the item is unknown, unavailable, or invalid.
References ProductionQueue::Element::item, and ProductionQueue::Element::location.
Referenced by CheckProductionProgress(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{EmpireWrapper.cpp}::ProductionCostAndTimeP(), ProductionStatus(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), BuildingsPanel::Update(), and ProductionQueue::Update().
ProductionCostAndTime() [2/2]
std::pair< float, int > Empire::ProductionCostAndTime (const ProductionQueue::ProductionItem & item, int location_id) const
Returns the Empire's name.
References ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, ErrorLogger, GetBuildingType(), GetShipDesign(), m_id, ProductionQueue::ProductionItem::name, BuildingType::ProductionCost(), ShipDesign::ProductionCost(), BuildingType::ProductionTime(), and ShipDesign::ProductionTime().
ProductionPoints()
float Empire::ProductionPoints () const
Returns the empire's current production point output (this is available industry not including stockpile)
References GetResourcePool(), and RE_INDUSTRY.
Referenced by FreeOrionPython::WrapEmpire().
ProductionStatus()
float Empire::ProductionStatus (int i) const
Returns the PPs spent towards item i in the build queue if it has partial progress, -1.0 if there is no such index in the production queue.
References m_production_queue, ProductionCostAndTime(), and ProductionQueue::size().
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), and BuildingsPanel::Update().
Ready()
bool Empire::Ready () const
Returns readiness status of empire.
References m_ready.
Referenced by HumanClientApp::ResetOrExitApp().
RecordPendingLaneUpdate()
void Empire::RecordPendingLaneUpdate (int start_system_id, int dest_system_id)
Records, in a list of pending updates, the start_system exit lane to the specified destination as accessible to this empire.
References ObjectMap::get(), anonymous_namespace{EncyclopediaParser.cpp}::insert, m_pending_system_exit_lanes, m_supply_unobstructed_systems, and Objects().
Referenced by Fleet::MovementPhase().
RemoveBuildingType()
void Empire::RemoveBuildingType (const std::string & name)
Removes the given BuildingType from the empire's list.
References DebugLogger, and m_available_building_types.
Referenced by LockItem().
RemoveHullType()
void Empire::RemoveHullType (const std::string & name)
Removes the given HullType from the empire's list.
References DebugLogger, and m_available_hull_types.
Referenced by LockItem().
RemoveProductionFromQueue()
void Empire::RemoveProductionFromQueue (int index)
Removes the produce at position index in the production queue, if such an index exists.
References DebugLogger, ProductionQueue::erase(), ErrorLogger, m_production_queue, and ProductionQueue::size().
RemoveShipDesign()
void Empire::RemoveShipDesign (int ship_design_id)
Removes the ShipDesign with the given id from the empire's set.
References DebugLogger, m_known_ship_designs, and ShipDesignsChangedSignal.
Referenced by LockItem().
RemoveShipPart()
void Empire::RemoveShipPart (const std::string & name)
Removes the given ShipPart from the empire's list.
References DebugLogger, and m_available_ship_parts.
Referenced by LockItem().
RemoveTech()
void Empire::RemoveTech (const std::string & name)
Removes the given Tech from the empire's list.
References m_techs.
Referenced by LockItem().
RemoveTechFromQueue()
void Empire::RemoveTechFromQueue (const std::string & name)
Removes tech with name from the research queue, if it is in the research queue already.
References ResearchQueue::end(), ResearchQueue::erase(), ResearchQueue::find(), and m_research_queue.
ResearchableTech()
bool Empire::ResearchableTech (const std::string & name) const
Returns true iff name is a tech that has not been researched, and has no unresearched prerequisites.
References GetTech(), m_techs, and Tech::Prerequisites().
Referenced by GetTechStatus(), ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchableByEmpire(), and TopPriorityResearchableTech().
ResearchedTechs()
const std::map< std::string, int > & Empire::ResearchedTechs () const
Returns the set of Tech names available to this empire.
References m_techs.
Referenced by Universe::GetEffectsAndTargets(), ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{EmpireWrapper.cpp}::ResearchedTechNames().
ResearchProgress()
float Empire::ResearchProgress (const std::string & name) const
Returns the RPs spent towards tech name if it has partial research progress, or 0.0 if it is already researched.
References GetTech(), m_id, m_research_progress, and Tech::ResearchCost().
Referenced by CheckResearchProgress(), Effect::SetEmpireTechProgress::Execute(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), TechRowBrowseWnd(), and FreeOrionPython::WrapEmpire().
ResetMeters()
void Empire::ResetMeters ()
Resets empire meters.
References m_meters.
ResourceAvailable()
float Empire::ResourceAvailable (ResourceType type) const
returns amount of resource type immediately available. This = production + stockpile
References m_resource_pools.
Referenced by FreeOrionPython::WrapEmpire().
ResourceOutput()
float Empire::ResourceOutput (ResourceType type) const
returns amount of resource type being generated by ResourceCenters
References m_resource_pools.
Referenced by MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshResearchResourceIndicator(), ProductionQueue::Update(), ResearchWnd::UpdateInfoPanel(), ProductionWnd::UpdateInfoPanel(), and FreeOrionPython::WrapEmpire().
ResourceStockpile()
float Empire::ResourceStockpile (ResourceType type) const
returns current stockpiled amount of resource type
References m_resource_pools.
Referenced by Effect::SetEmpireStockpile::Execute(), Condition::EmpireStockpileValue::Match(), MapWnd::RefreshTradeResourceIndicator(), and FreeOrionPython::WrapEmpire().
ResumeProduction()
void Empire::ResumeProduction (int index)
Sets the production of produce at postion index unpaused, if such an index exists.
References DebugLogger, ErrorLogger, m_production_queue, and ProductionQueue::size().
ResumeResearch()
void Empire::ResumeResearch (const std::string & name)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References ResearchQueue::end(), ResearchQueue::find(), and m_research_queue.
serialize()
template<class Archive > template void Empire::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References ALL_EMPIRES, Universe::AllObjectsVisible(), BEFORE_FIRST_TURN, BOOST_CLASS_VERSION(), Empires(), Universe::EncodingEmpire(), EmpireManager::GetEmpire(), GetGameRules(), GetUniverse(), and m_techs.
SetAuthenticated()
void Empire::SetAuthenticated (bool authenticated = true)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References m_authenticated.
Referenced by ServerApp::AddPlayerIntoGame().
SetCapitalID()
void Empire::SetCapitalID (int id)
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References ObjectMap::ExistingObject(), ObjectMap::get(), INVALID_OBJECT_ID, m_capital_id, m_id, m_source_id, and Objects().
Referenced by Effect::SetEmpireCapital::Execute(), and SetEmpireHomeworld().
SetColor()
void Empire::SetColor (const GG::Clr & color)
Mutator for empire color.
References m_color.
SetName()
void Empire::SetName (const std::string & name)
Mutator for empire name.
References m_name.
Referenced by anonymous_namespace{ServerWrapper.cpp}::EmpireSetName().
SetPlayerName()
void Empire::SetPlayerName (const std::string & player_name)
Mutator for empire's player name.
References m_player_name.
SetProductionQuantity()
void Empire::SetProductionQuantity (int index, int quantity)
Changes the remaining number to produce for queue item index to quantity.
References m_production_queue, and ProductionQueue::size().
SetProductionQuantityAndBlocksize()
void Empire::SetProductionQuantityAndBlocksize (int index, int quantity, int blocksize)
Changes the remaining number and blocksize to produce for queue item index to quantity and blocksize.
References DebugLogger, m_production_queue, and ProductionQueue::size().
SetProductionRallyPoint()
void Empire::SetProductionRallyPoint (int index, int rally_point_id = INVALID_OBJECT_ID)
Sets the rally point for ships produced by this produce, to which they are automatically ordered to move after they are produced.
References m_production_queue, and ProductionQueue::size().
SetReady()
void Empire::SetReady (bool ready)
Marks this empire with readiness status.
References m_ready.
Referenced by ServerApp::AddPlayerIntoGame(), and WaitingForTurnEnd::react().
SetResourceStockpile()
void Empire::SetResourceStockpile (ResourceType resource_type, float stockpile)
Sets current stockpile amount of indicated resource_type.
References m_resource_pools.
Referenced by CheckProductionProgress(), and Effect::SetEmpireStockpile::Execute().
SetTechResearchProgress()
void Empire::SetTechResearchProgress (const std::string & name, float progress)
Sets research progress of tech with name to progress.
References ErrorLogger, GetTech(), ResearchQueue::InQueue(), m_id, m_research_progress, m_research_queue, ResearchQueue::push_back(), Tech::ResearchCost(), and TechResearched().
Referenced by Effect::SetEmpireTechProgress::Execute().
ShipDesignAvailable() [1/2]
bool Empire::ShipDesignAvailable (const ShipDesign & design) const
Returns true iff this ship design can be built by this empire.
References ShipDesign::Hull(), ShipDesign::Parts(), ShipDesign::Producible(), ShipHullAvailable(), and ShipPartAvailable().
Referenced by AvailableShipDesigns(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), Condition::anonymous_namespace{Conditions.cpp}::OwnerHasShipDesignAvailableSimpleMatch::operator()(), ProducibleItem(), ShipDesignAvailable(), and FreeOrionPython::WrapEmpire().
ShipDesignAvailable() [2/2]
bool Empire::ShipDesignAvailable (int ship_design_id) const
Returns true iff this ship design can be built by this empire. If no such ship design exists, returns false.
References GetShipDesign(), and ShipDesignAvailable().
ShipDesignKept()
bool Empire::ShipDesignKept (int ship_design_id) const
Returns true iff the given ship design id is in the set of design ids of this empire. That is, it has been added to this empire.
References m_known_ship_designs.
ShipDesigns()
const std::set< int > & Empire::ShipDesigns () const
Returns the set of all ship design ids of this empire.
References m_known_ship_designs.
Referenced by Universe::UpdateEmpireObjectVisibilities(), and FreeOrionPython::WrapEmpire().
ShipDesignsDestroyed()
std::map<int, int>& Empire::ShipDesignsDestroyed () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
ShipDesignsInProduction()
std::map<int, int>& Empire::ShipDesignsInProduction () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap().
ShipDesignsLost()
std::map<int, int>& Empire::ShipDesignsLost () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
ShipDesignsOwned()
std::map<int, int>& Empire::ShipDesignsOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap().
ShipDesignsProduced()
std::map<int, int>& Empire::ShipDesignsProduced () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
ShipDesignsScrapped()
std::map<int, int>& Empire::ShipDesignsScrapped () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
ShipHullAvailable()
bool Empire::ShipHullAvailable (const std::string & name) const
Returns true iff this ship hull can be built by this empire. If no such ship hull exists, returns false.
References m_available_hull_types.
Referenced by anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability(), and ShipDesignAvailable().
ShipPartAvailable()
bool Empire::ShipPartAvailable (const std::string & name) const
Returns true iff this ship part can be built by this empire. If no such ship part exists, returns false.
References m_available_ship_parts.
Referenced by anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability(), Condition::anonymous_namespace{Conditions.cpp}::OwnerHasShipPartAvailableSimpleMatch::operator()(), and ShipDesignAvailable().
ShipPartClassOwned()
std::map<ShipPartClass, int>& Empire::ShipPartClassOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::ComplexVariable< T >::Eval().
ShipPartsOwned()
std::map<std::string, int>& Empire::ShipPartsOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap().
SitRepBegin()
Empire::SitRepItr Empire::SitRepBegin () const
starting iterator for sitrep entries for this empire
References m_sitrep_entries.
Referenced by anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings(), and anonymous_namespace{EmpireWrapper.cpp}::GetSitRep().
SitRepEnd()
Empire::SitRepItr Empire::SitRepEnd () const
end iterator for sitreps
References m_sitrep_entries.
Referenced by anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings().
Source()
std::shared_ptr< const UniverseObject > Empire::Source () const
Return an object that is owned by the empire or null.
References ObjectMap::all(), ObjectMap::get(), INVALID_OBJECT_ID, m_capital_id, m_eliminated, m_id, m_source_id, and Objects().
Referenced by Universe::GetEffectsAndTargets(), and SourceID().
SourceID()
int Empire::SourceID () const
Return an object id that is owned by the empire or INVALID_OBJECT_ID.
References INVALID_OBJECT_ID, and Source().
SpeciesColoniesOwned()
std::map<std::string, int>& Empire::SpeciesColoniesOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap().
SpeciesPlanetsBombed()
std::map<std::string, int>& Empire::SpeciesPlanetsBombed () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
SpeciesPlanetsDepoped()
std::map<std::string, int>& Empire::SpeciesPlanetsDepoped () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
SpeciesPlanetsInvaded()
std::map<std::string, int>& Empire::SpeciesPlanetsInvaded () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo().
SpeciesShipsDestroyed()
std::map<std::string, int>& Empire::SpeciesShipsDestroyed () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
SpeciesShipsLost()
std::map<std::string, int>& Empire::SpeciesShipsLost () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), and anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo().
SpeciesShipsOwned()
std::map<std::string, int>& Empire::SpeciesShipsOwned () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap().
SpeciesShipsProduced()
std::map<std::string, int>& Empire::SpeciesShipsProduced () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
SpeciesShipsScrapped()
std::map<std::string, int>& Empire::SpeciesShipsScrapped () inline
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag().
SplitIncompleteProductionItem()
void Empire::SplitIncompleteProductionItem (int index, boost::uuids::uuid uuid)
Adds a copy of the production item at position index below it in the queue, with one less quantity.
Sets the quantity of the production item at position index to 1, retaining its incomplete progress.
References ProductionQueue::Element::blocksize, DebugLogger, ProductionQueue::Element::item, ProductionQueue::Element::location, m_production_queue, PlaceProductionOnQueue(), ProductionQueue::Element::remaining, and ProductionQueue::size().
SupplyUnobstructedSystems()
const std::set< int > & Empire::SupplyUnobstructedSystems () const
Returns set of system ids that are able to propagate supply from one system to the next, or at which supply can be delivered to fleets if supply can reach the system from elsewhere, or in which planets can exchange supply between themselves (even if not leaving the system).
References m_supply_unobstructed_systems.
Referenced by MapWnd::MovementLineData::MovementLineData(), Fleet::MovementPhase(), Fleet::MovePath(), SupplyManager::Update(), and FreeOrionPython::WrapEmpire().
SystemSupplyRanges()
const std::map< int, float > & Empire::SystemSupplyRanges () const
Returns distance in jumps away from each system that this empire can propagate supply.
References m_supply_system_ranges.
Referenced by ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntFloatMap(), SupplyManager::Update(), UpdateSupplyUnobstructedSystems(), and FreeOrionPython::WrapEmpire().
TechResearched()
bool Empire::TechResearched (const std::string & name) const
Returns true iff this tech has been completely researched.
References m_techs.
Referenced by ResearchWnd::AddTechsToQueueSlot(), GetTechStatus(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), Condition::anonymous_namespace{Conditions.cpp}::OwnerHasTechSimpleMatch::operator()(), PlaceTechInQueue(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), SetTechResearchProgress(), TechTreeWnd::TechListBox::TechRightClicked(), ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchedByEmpire(), and FreeOrionPython::WrapEmpire().
TopPriorityEnqueuedTech()
const std::string & Empire::TopPriorityEnqueuedTech () const
Returns the Empire's name.
References ResearchQueue::begin(), ResearchQueue::empty(), anonymous_namespace{Empire.cpp}::EMPTY_STRING, and m_research_queue.
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().
TopPriorityResearchableTech()
const std::string & Empire::TopPriorityResearchableTech () const
Returns the Empire's name.
References ResearchQueue::empty(), anonymous_namespace{Empire.cpp}::EMPTY_STRING, m_research_queue, and ResearchableTech().
Referenced by ValueRef::ComplexVariable< T >::Eval().
TotalBuildingsOwned()
int Empire::TotalBuildingsOwned () const
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References m_building_types_owned.
TotalShipPartsOwned()
int Empire::TotalShipPartsOwned () const
Total number of parts for all owned ships in this empire.
References m_ship_part_class_owned.
TotalShipsOwned()
int Empire::TotalShipsOwned () const
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References m_ship_designs_owned.
UnlockItem()
void Empire::UnlockItem (const UnlockableItem & item)
Adds a given producible item (Building, Ship Hull, Ship part) to the list of available items.
References AddBuildingType(), AddHullType(), AddNewlyResearchedTechToGrantAtStartOfNextTurn(), AddShipDesign(), AddShipPart(), ErrorLogger, and GetPredefinedShipDesignManager().
Referenced by ApplyNewTechs(), and anonymous_namespace{ServerWrapper.cpp}::EmpireUnlockItem().
UpdateOwnedObjectCounters()
void Empire::UpdateOwnedObjectCounters ()
If the object with id id is a planet owned by this empire, sets that planet to be this empire's capital, and otherwise does nothing.
References ProductionQueue::ProductionItem::build_type, ProductionQueue::ProductionItem::design_id, GetShipDesign(), m_building_types_owned, m_outposts_owned, m_production_queue, m_ship_designs_in_production, m_ship_designs_owned, m_ship_part_class_owned, m_ship_parts_owned, m_species_colonies_owned, m_species_ships_owned, Objects(), ShipDesign::PartClassCount(), and ShipDesign::ShipPartCount().
UpdatePopulationGrowth()
void Empire::UpdatePopulationGrowth ()
Has m_population_pool recalculate all PopCenters' and empire's total expected population growth.
References m_population_pool, and PopulationPool::Update().
Referenced by UpdateResourcePools().
UpdatePreservedLanes()
void Empire::UpdatePreservedLanes ()
Processes all the pending lane access updates.
This is managed as a two step process to avoid order-of-processing issues.
References m_pending_system_exit_lanes, and m_preserved_system_exit_lanes.
Referenced by ServerApp::PostCombatProcessTurns().
UpdateProductionQueue()
void Empire::UpdateProductionQueue ()
Calls Update() on empire's production queue, which recalculates the PPs spent on and number of turns left for each project in the queue.
References DebugLogger, EmpireID(), m_production_queue, m_resource_pools, RE_INDUSTRY, and ProductionQueue::Update().
Referenced by ProductionWnd::AddBuildToQueueSlot(), ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), ProductionWnd::DeleteQueueItem(), ProductionWnd::QueueItemDuped(), ProductionWnd::QueueItemMoved(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), ProductionWnd::QueueItemUseImperialPP(), anonymous_namespace{AIWrapper.cpp}::UpdateProductionQueue(), and UpdateResourcePools().
UpdateResearchQueue()
void Empire::UpdateResearchQueue ()
Calls Update() on empire's research queue, which recalculates the RPs spent on and number of turns left for each tech in the queue.
References m_research_progress, m_research_queue, m_resource_pools, RE_RESEARCH, and ResearchQueue::Update().
Referenced by ResearchWnd::AddTechsToQueueSlot(), ResearchWnd::QueueItemPaused(), anonymous_namespace{AIWrapper.cpp}::UpdateResearchQueue(), and UpdateResourcePools().
UpdateResourcePools()
void Empire::UpdateResourcePools ()
Resets production of resources and calculates allocated resources (on each item in queues and overall) for each resource by calling UpdateResearchQueue, UpdateProductionQueue, UpdateTradeSpending.
Does not actually "spend" resources, but just determines how much and on what to spend. Actual consumption of resources, removal of items from queue, processing of finished items and population growth happens in various Check(Whatever)Progress functions.
References UpdatePopulationGrowth(), UpdateProductionQueue(), UpdateResearchQueue(), and UpdateTradeSpending().
Referenced by MapWnd::UpdateEmpireResourcePools(), UpdateEmpireSupply(), and anonymous_namespace{AIWrapper.cpp}::UpdateResourcePools().
UpdateSupplyUnobstructedSystems() [1/2]
void Empire::UpdateSupplyUnobstructedSystems (const std::set< int > & known_systems, bool precombat = false)
Calculates systems that can propagate supply (fleet or resource) using the specified set of known_systems.
References ALL_EMPIRES, DebugLogger, EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ObjectMap::find(), EmpireManager::GetDiplomaticStatus(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetUniverse(), INVALID_OBJECT_ID, m_id, m_name, m_preserved_system_exit_lanes, m_supply_unobstructed_systems, Objects(), SystemSupplyRanges(), and TraceLogger.
Referenced by ServerApp::PreCombatProcessTurns(), UpdateEmpireSupply(), and UpdateSupplyUnobstructedSystems().
UpdateSupplyUnobstructedSystems() [2/2]
void Empire::UpdateSupplyUnobstructedSystems (bool precombat = false)
Calculates systems that can propagate supply using this empire's own / internal list of explored systems.
References EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), EmpireKnownObjects(), GetUniverse(), and UpdateSupplyUnobstructedSystems().
UpdateSystemSupplyRanges() [1/2]
void Empire::UpdateSystemSupplyRanges (const std::set< int > & known_objects)
Calculates ranges that systems can send fleet and resource supplies, using the specified st of known_objects as the source for supply- producing objects and systems through which it can be propagated.
References INVALID_OBJECT_ID, m_supply_system_ranges, METER_SUPPLY, and Objects().
Referenced by UpdateEmpireSupply().
UpdateSystemSupplyRanges() [2/2]
void Empire::UpdateSystemSupplyRanges ()
Calculates ranges that systems can send fleet and resource supplies.
References ObjectMap::all(), EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), EmpireKnownObjects(), and GetUniverse().
UpdateTradeSpending()
void Empire::UpdateTradeSpending ()
Eventually: Calls appropriate subsystem Update to calculate trade spent on social projects and maintenance of buildings.
Later call to CheckTradeSocialProgress() will then have the correct allocations of trade. Currently: Sums maintenance costs of all buildings owned by empire, sets m_maintenance_total_cost
References m_resource_pools, and RE_TRADE.
Referenced by UpdateResourcePools().
UpdateUnobstructedFleets()
void Empire::UpdateUnobstructedFleets ()
Updates fleet ArrivalStarlane to flag fleets of this empire that are not blockaded post-combat must be done after all noneliminated empires have updated their unobstructed systems*.
References EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), GetUniverse(), m_id, m_supply_unobstructed_systems, and Objects().
Referenced by ServerApp::PostCombatProcessTurns().
VisibleStarlanes()
const std::map< int, std::set< int > > Empire::VisibleStarlanes () const
returns map from system id (start) to set of system ids (endpoints) of all starlanes visible to this empire this turn
References ObjectMap::all(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), ObjectMap::insert(), m_id, and Universe::Objects().
Win()
void Empire::Win (const std::string & reason)
Marks this empire as having won for this reason, and sends the appropriate sitreps.
References CreateVictorySitRep(), EmpireID(), Empires(), and m_victories.
Won()
bool Empire::Won () const
whether this empire has won the game
References m_victories.
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), and FreeOrionPython::WrapEmpire().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
EmpireManager
friend class EmpireManager friend
Member Data Documentation
m_authenticated
bool Empire::m_authenticated private
Empire's Player's authentication flag.
Set if only player with empire's player's name should play this empire.
Referenced by IsAuthenticated(), and SetAuthenticated().
m_available_building_types
std::set<std::string> Empire::m_available_building_types private
list of acquired BuildingType.
These are string names referencing BuildingType objects
Referenced by AddBuildingType(), AvailableBuildingTypes(), BuildingTypeAvailable(), and RemoveBuildingType().
m_available_hull_types
std::set<std::string> Empire::m_available_hull_types private
list of acquired ship HullType. These are string names referencing HullType objects
Referenced by AddHullType(), AvailableShipHulls(), RemoveHullType(), and ShipHullAvailable().
m_available_ship_parts
std::set<std::string> Empire::m_available_ship_parts private
List of acquired ShipPart referenced by name.
Referenced by AddShipPart(), AvailableShipParts(), RemoveShipPart(), and ShipPartAvailable().
m_building_types_owned
std::map<std::string, int> Empire::m_building_types_owned private
how many buildings does this empire currently own?
Referenced by TotalBuildingsOwned(), and UpdateOwnedObjectCounters().
m_building_types_produced
std::map<std::string, int> Empire::m_building_types_produced private
how many buildings of each type has this empire produced?
Referenced by CheckProductionProgress().
m_building_types_scrapped
std::map<std::string, int> Empire::m_building_types_scrapped private
how many buildings of each type has this empire scrapped?
m_capital_id
int Empire::m_capital_id = INVALID_OBJECT_ID private
the ID of the empire's capital planet
Referenced by CapitalID(), Dump(), Eliminate(), SetCapitalID(), and Source().
m_color
GG::Clr Empire::m_color private
Empire's color.
Referenced by Color(), and SetColor().
m_eliminated
bool Empire::m_eliminated = false private
Whether the empire has lost.
Referenced by Eliminate(), Eliminated(), Init(), and Source().
m_empire_ships_destroyed
std::map<int, int> Empire::m_empire_ships_destroyed private
how many ships of each empire has this empire destroyed?
m_explored_systems
std::set<int> Empire::m_explored_systems private
systems explored by this empire
Referenced by AddExploredSystem(), ExploredSystems(), and HasExploredSystem().
m_id
int Empire::m_id = ALL_EMPIRES private
Empire's unique numeric id.
Referenced by CheckProductionProgress(), CheckResearchProgress(), Dump(), EmpireID(), EnqueuableItem(), InitResourcePools(), KnownStarlanes(), LeastExpensiveEnqueuedTech(), MostExpensiveEnqueuedTech(), MostRPCostLeftEnqueuedTech(), PlaceProductionOnQueue(), ProducibleItem(), ProductionCostAndTime(), ResearchProgress(), SetCapitalID(), SetTechResearchProgress(), Source(), UpdateSupplyUnobstructedSystems(), UpdateUnobstructedFleets(), and VisibleStarlanes().
m_known_ship_designs
std::set<int> Empire::m_known_ship_designs private
ids of ship designs in the universe that this empire knows about
Referenced by AddShipDesign(), AvailableShipDesigns(), RemoveShipDesign(), ShipDesignKept(), and ShipDesigns().
m_meters
std::map<std::string, Meter> Empire::m_meters private
empire meters, including ratings scales used by species to judge empires
Referenced by BackPropagateMeters(), Dump(), GetMeter(), Init(), and ResetMeters().
m_name
std::string Empire::m_name private
Empire's name.
Referenced by Dump(), Name(), SetName(), and UpdateSupplyUnobstructedSystems().
m_newly_researched_techs
std::set<std::string> Empire::m_newly_researched_techs private
names of researched but not yet effective technologies, and turns on which they were acquired.
Referenced by AddNewlyResearchedTechToGrantAtStartOfNextTurn(), ApplyNewTechs(), and PlaceTechInQueue().
m_outposts_owned
int Empire::m_outposts_owned = 0 private
how many uncolonized outposts does this empire currently own?
Referenced by UpdateOwnedObjectCounters().
m_pending_system_exit_lanes
std::map<int, std::set<int> > Empire::m_pending_system_exit_lanes private
pending updates to m_preserved_system_exit_lanes
Referenced by RecordPendingLaneUpdate(), and UpdatePreservedLanes().
m_player_name
std::string Empire::m_player_name private
Empire's Player's name.
Referenced by PlayerName(), and SetPlayerName().
m_population_pool
PopulationPool Empire::m_population_pool private
Referenced by Eliminate(), GetPopulationPool(), InitResourcePools(), Population(), and UpdatePopulationGrowth().
m_preserved_system_exit_lanes
std::map<int, std::set<int> > Empire::m_preserved_system_exit_lanes private
for each system known to this empire, the set of exit lanes preserved for fleet travel even if otherwise blockaded
Referenced by PreservedLaneTravel(), UpdatePreservedLanes(), and UpdateSupplyUnobstructedSystems().
m_production_queue
ProductionQueue Empire::m_production_queue private
the queue of items being or waiting to be built
Referenced by AllowUseImperialPP(), CheckProductionProgress(), ConquerProductionQueueItemsAtLocation(), DuplicateProductionItem(), Eliminate(), GetProductionQueue(), MoveProductionWithinQueue(), PauseProduction(), PlaceProductionOnQueue(), ProductionStatus(), RemoveProductionFromQueue(), ResumeProduction(), SetProductionQuantity(), SetProductionQuantityAndBlocksize(), SetProductionRallyPoint(), SplitIncompleteProductionItem(), UpdateOwnedObjectCounters(), and UpdateProductionQueue().
m_ready
bool Empire::m_ready private
readiness status of empire
Referenced by Ready(), and SetReady().
m_research_progress
std::map<std::string, float> Empire::m_research_progress private
progress of partially-researched techs; fully researched techs are removed
Referenced by CheckResearchProgress(), Eliminate(), MostRPCostLeftEnqueuedTech(), MostRPSpentEnqueuedTech(), ResearchProgress(), SetTechResearchProgress(), and UpdateResearchQueue().
m_research_queue
ResearchQueue Empire::m_research_queue private
the queue of techs being or waiting to be researched
Referenced by CheckResearchProgress(), Eliminate(), GetResearchQueue(), LeastExpensiveEnqueuedTech(), MostExpensiveEnqueuedTech(), MostRPCostLeftEnqueuedTech(), MostRPSpentEnqueuedTech(), PauseResearch(), PlaceTechInQueue(), RemoveTechFromQueue(), ResumeResearch(), SetTechResearchProgress(), TopPriorityEnqueuedTech(), TopPriorityResearchableTech(), and UpdateResearchQueue().
m_resource_pools
std::map<ResourceType, std::shared_ptr<ResourcePool> > Empire::m_resource_pools private
Referenced by CheckResearchProgress(), CheckTradeSocialProgress(), Eliminate(), GetResourcePool(), Init(), InitResourcePools(), ResourceAvailable(), ResourceOutput(), ResourceStockpile(), SetResourceStockpile(), UpdateProductionQueue(), UpdateResearchQueue(), and UpdateTradeSpending().
m_ship_designs_destroyed
std::map<int, int> Empire::m_ship_designs_destroyed private
how many ships of each design has this empire destroyed?
m_ship_designs_in_production
std::map<int, int> Empire::m_ship_designs_in_production private
how many ships of each design has this empire in active production in its production queue
Referenced by UpdateOwnedObjectCounters().
m_ship_designs_lost
std::map<int, int> Empire::m_ship_designs_lost private
how many ships of each design has this empire lost in combat?
m_ship_designs_owned
std::map<int, int> Empire::m_ship_designs_owned private
how many ships of each design does this empire currently own?
Referenced by TotalShipsOwned(), and UpdateOwnedObjectCounters().
m_ship_designs_produced
std::map<int, int> Empire::m_ship_designs_produced private
how many ships of each design has this empire produced?
Referenced by CheckProductionProgress().
m_ship_designs_scrapped
std::map<int, int> Empire::m_ship_designs_scrapped private
how many ships of each design has this empire scrapped?
m_ship_names_used
std::map<std::string, int> Empire::m_ship_names_used private
map from name to number of times used
Referenced by NewShipName().
m_ship_part_class_owned
std::map<ShipPartClass, int> Empire::m_ship_part_class_owned private
how many ship parts are currently owned, indexed by ShipPartClass
Referenced by TotalShipPartsOwned(), and UpdateOwnedObjectCounters().
m_ship_parts_owned
std::map<std::string, int> Empire::m_ship_parts_owned private
How many ShipParts are currently owned, indexed by ShipPart.
Referenced by UpdateOwnedObjectCounters().
m_sitrep_entries
std::vector<SitRepEntry> Empire::m_sitrep_entries private
The Empire's sitrep entries.
Referenced by AddSitRepEntry(), ClearSitRep(), Eliminate(), NumSitRepEntries(), SitRepBegin(), and SitRepEnd().
m_source_id
int Empire::m_source_id = INVALID_OBJECT_ID mutable private
The source id is the id of any object owned by the empire.
It is mutable so that Source() can be const and still cache its result.
Referenced by SetCapitalID(), and Source().
m_species_colonies_owned
std::map<std::string, int> Empire::m_species_colonies_owned private
how many colonies of each species does this empire currently own?
Referenced by UpdateOwnedObjectCounters().
m_species_planets_bombed
std::map<std::string, int> Empire::m_species_planets_bombed private
how many planets populated by each species has this empire bombarded?
m_species_planets_depoped
std::map<std::string, int> Empire::m_species_planets_depoped private
how many planets populated by each species have depopulated while owned by this empire?
m_species_planets_invaded
std::map<std::string, int> Empire::m_species_planets_invaded private
how many planets populated by each species has this empire captured?
m_species_ships_destroyed
std::map<std::string, int> Empire::m_species_ships_destroyed private
how many ships crewed by each species has this empire destroyed?
m_species_ships_lost
std::map<std::string, int> Empire::m_species_ships_lost private
how mahy ships crewed by each species has this empire lost in combat?
m_species_ships_owned
std::map<std::string, int> Empire::m_species_ships_owned private
how many ships of each species does this empire currently own?
Referenced by UpdateOwnedObjectCounters().
m_species_ships_produced
std::map<std::string, int> Empire::m_species_ships_produced private
how many ships crewed by each species has this empire produced?
Referenced by CheckProductionProgress().
m_species_ships_scrapped
std::map<std::string, int> Empire::m_species_ships_scrapped private
how many ships crewed by each species has this empire scrapped?
m_supply_system_ranges
std::map<int, float> Empire::m_supply_system_ranges private
number of starlane jumps away from each system (by id) supply can be conveyed. This is the number due to a system's contents conveying supply and is computed and set by UpdateSystemSupplyRanges
Referenced by Eliminate(), SystemSupplyRanges(), and UpdateSystemSupplyRanges().
m_supply_unobstructed_systems
std::set<int> Empire::m_supply_unobstructed_systems private
ids of system that don't block supply from flowing
Referenced by Eliminate(), RecordPendingLaneUpdate(), SupplyUnobstructedSystems(), UpdateSupplyUnobstructedSystems(), and UpdateUnobstructedFleets().
m_techs
std::map<std::string, int> Empire::m_techs private
names of researched technologies, and turns on which they were acquired.
Referenced by AddNewlyResearchedTechToGrantAtStartOfNextTurn(), ApplyNewTechs(), HasResearchedPrereqAndUnresearchedPrereq(), PlaceTechInQueue(), RemoveTech(), ResearchableTech(), ResearchedTechs(), serialize(), and TechResearched().
m_victories
std::set<std::string> Empire::m_victories private
The ways that the empire has won, if any.
Referenced by Win(), and Won().
ShipDesignsChangedSignal
boost::signals2::signal<void ()> Empire::ShipDesignsChangedSignal mutable
Referenced by AddShipDesign(), and RemoveShipDesign().
The documentation for this class was generated from the following files:
Empire.h
Empire.cpp
SerializeEmpire.cpp