FreeOrion: FleetUIManager Class Reference
FleetUIManager Class Reference
Manages the lifetimes of FleetWnds.
#include <FleetWnd.h>
Public Types
typedef std::set< std::weak_ptr< FleetWnd > >::const_iterator iterator
Public Member Functions
FleetWnd * ActiveFleetWnd () const
iterator begin () const
bool CloseAll ()
void CullEmptyWnds ()
bool empty () const
void EnableOrderIssuing (bool enable=true)
Enables, or disables if enable is false, issuing orders via FleetWnds.
iterator end () const
std::shared_ptr< FleetWnd > NewFleetWnd (const std::vector< int > &fleet_ids, double allowed_bounding_box_leeway=0, int selected_fleet_id=INVALID_OBJECT_ID, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE|GG::DRAGABLE|GG::ONTOP|CLOSABLE|GG::RESIZABLE)
void RefreshAll ()
int SelectedShipID () const
std::set< int > SelectedShipIDs () const
void SetActiveFleetWnd (std::shared_ptr< FleetWnd > fleet_wnd)
std::shared_ptr< FleetWnd > WndForFleetID (int fleet_id) const
std::shared_ptr< FleetWnd > WndForFleetIDs (const std::vector< int > &fleet_ids_) const
Static Public Member Functions
static FleetUIManager & GetFleetUIManager ()
Public Attributes
boost::signals2::signal< void()> ActiveFleetWndChangedSignal
emitted when the selected FleetWnd changes
boost::signals2::signal< void()> ActiveFleetWndSelectedFleetsChangedSignal
emitted when the selected fleets in the active FleetWnd change
boost::signals2::signal< void()> ActiveFleetWndSelectedShipsChangedSignal
emitted when the selected ships in the active FleetWnd change
boost::signals2::signal< void(int)> FleetRightClickedSignal
emitted when a fleet is right-clicked
boost::signals2::signal< void(int)> ShipRightClickedSignal
emitted when a ship is right-clicked
Private Member Functions
FleetUIManager ()
void FleetWndClicked (std::shared_ptr< FleetWnd > fleet_wnd)
sets active FleetWnd
void FleetWndClosing (FleetWnd *fleet_wnd)
Private Attributes
std::weak_ptr< FleetWnd > m_active_fleet_wnd
Active fleet window.
std::vector< boost::signals2::connection > m_active_fleet_wnd_signals
std::set< std::weak_ptr< FleetWnd >, std::owner_less< std::weak_ptr< FleetWnd > > > m_fleet_wnds
All fleet windows.
bool m_order_issuing_enabled
Detailed Description
Manages the lifetimes of FleetWnds.
Member Typedef Documentation
iterator
typedef std::set<std::weak_ptr<FleetWnd> >::const_iterator FleetUIManager::iterator
Constructor & Destructor Documentation
FleetUIManager()
FleetUIManager::FleetUIManager () private
Member Function Documentation
ActiveFleetWnd()
FleetWnd * FleetUIManager::ActiveFleetWnd () const
References m_active_fleet_wnd.
Referenced by MapWnd::FleetButtonRightClicked(), MapWnd::LClick(), MapWnd::PlotFleetMovement(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), MapWnd::SelectFleet(), and MapWnd::SystemRightClicked().
begin()
FleetUIManager::iterator FleetUIManager::begin () const
References m_fleet_wnds.
CloseAll()
bool FleetUIManager::CloseAll ()
References ActiveFleetWndChangedSignal, GGHumanClientApp::GetApp(), m_active_fleet_wnd, m_fleet_wnds, and ClientApp::SendPartialOrders().
Referenced by MapWnd::LClick(), NewFleetWnd(), and MapWnd::ReturnToMap().
CullEmptyWnds()
void FleetUIManager::CullEmptyWnds ()
References m_fleet_wnds.
Referenced by MapWnd::DoLayout(), and MapWnd::Render().
empty()
bool FleetUIManager::empty () const
References m_fleet_wnds.
Referenced by anonymous_namespace{GalaxySetupWnd.cpp}::RuleListRow::SizeMove().
EnableOrderIssuing()
void FleetUIManager::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via FleetWnds.
References m_fleet_wnds, and m_order_issuing_enabled.
Referenced by MapWnd::EnableOrderIssuing().
end()
FleetUIManager::iterator FleetUIManager::end () const
References m_fleet_wnds.
FleetWndClicked()
void FleetUIManager::FleetWndClicked (std::shared_ptr< FleetWnd > fleet_wnd) private
sets active FleetWnd
References m_active_fleet_wnd, and SetActiveFleetWnd().
Referenced by NewFleetWnd().
FleetWndClosing()
void FleetUIManager::FleetWndClosing (FleetWnd * fleet_wnd) private
References ActiveFleetWndChangedSignal, GGHumanClientApp::GetApp(), and m_active_fleet_wnd.
Referenced by NewFleetWnd().
GetFleetUIManager()
FleetUIManager & FleetUIManager::GetFleetUIManager () static
Referenced by MapWnd::CompleteConstruction(), MapWnd::DoLayout(), MapWnd::EnableOrderIssuing(), MapWnd::FleetButtonLeftClicked(), MapWnd::FleetButtonRightClicked(), MapWnd::InitTurn(), MapWnd::LClick(), MapWnd::MidTurnUpdate(), MapWnd::PlotFleetMovement(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), MapWnd::Render(), MapWnd::ReturnToMap(), MapWnd::SelectedFleetsChanged(), MapWnd::SelectedShipsChanged(), MapWnd::SelectFleet(), GovernmentWnd::MainPanel::SetPolicy(), MapWnd::SystemRightClicked(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), and ClientUI::ZoomToFleet().
NewFleetWnd()
std::shared_ptr< FleetWnd > FleetUIManager::NewFleetWnd (const std::vector< int > & fleet_ids, double allowed_bounding_box_leeway = 0, int selected_fleet_id = INVALID_OBJECT_ID, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE | GG::DRAGABLE | GG::ONTOP | CLOSABLE | GG::RESIZABLE)
References CloseAll(), anonymous_namespace{FleetWnd.cpp}::FLEET_WND_NAME, FleetRightClickedSignal, FleetWndClicked(), FleetWndClosing(), GetOptionsDB(), m_fleet_wnds, m_order_issuing_enabled, and ShipRightClickedSignal.
Referenced by MapWnd::SelectFleet().
RefreshAll()
void FleetUIManager::RefreshAll ()
References m_fleet_wnds.
Referenced by MapWnd::InitTurn(), MapWnd::MidTurnUpdate(), and GovernmentWnd::MainPanel::SetPolicy().
SelectedShipID()
int FleetUIManager::SelectedShipID () const
References INVALID_OBJECT_ID, and m_active_fleet_wnd.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
SelectedShipIDs()
std::set< int > FleetUIManager::SelectedShipIDs () const
References m_active_fleet_wnd.
SetActiveFleetWnd()
void FleetUIManager::SetActiveFleetWnd (std::shared_ptr< FleetWnd > fleet_wnd)
References ActiveFleetWndChangedSignal, ActiveFleetWndSelectedFleetsChangedSignal, ActiveFleetWndSelectedShipsChangedSignal, m_active_fleet_wnd, and m_active_fleet_wnd_signals.
Referenced by FleetWndClicked(), and MapWnd::SelectFleet().
WndForFleetID()
std::shared_ptr< FleetWnd > FleetUIManager::WndForFleetID (int fleet_id) const
References m_fleet_wnds.
Referenced by MapWnd::SelectFleet(), and ClientUI::ZoomToFleet().
WndForFleetIDs()
std::shared_ptr< FleetWnd > FleetUIManager::WndForFleetIDs (const std::vector< int > & fleet_ids_) const
References m_fleet_wnds.
Referenced by MapWnd::FleetButtonLeftClicked().
Member Data Documentation
ActiveFleetWndChangedSignal
boost::signals2::signal<void ()> FleetUIManager::ActiveFleetWndChangedSignal mutable
emitted when the selected FleetWnd changes
Referenced by CloseAll(), MapWnd::CompleteConstruction(), FleetWndClosing(), and SetActiveFleetWnd().
ActiveFleetWndSelectedFleetsChangedSignal
boost::signals2::signal<void ()> FleetUIManager::ActiveFleetWndSelectedFleetsChangedSignal mutable
emitted when the selected fleets in the active FleetWnd change
Referenced by MapWnd::CompleteConstruction(), and SetActiveFleetWnd().
ActiveFleetWndSelectedShipsChangedSignal
boost::signals2::signal<void ()> FleetUIManager::ActiveFleetWndSelectedShipsChangedSignal mutable
emitted when the selected ships in the active FleetWnd change
Referenced by MapWnd::CompleteConstruction(), and SetActiveFleetWnd().
FleetRightClickedSignal
boost::signals2::signal<void (int)> FleetUIManager::FleetRightClickedSignal mutable
emitted when a fleet is right-clicked
Referenced by MapWnd::CompleteConstruction(), and NewFleetWnd().
m_active_fleet_wnd
std::weak_ptr<FleetWnd> FleetUIManager::m_active_fleet_wnd mutable private
Active fleet window.
mutable so expired ptr can be reset().
Referenced by ActiveFleetWnd(), CloseAll(), FleetWndClicked(), FleetWndClosing(), SelectedShipID(), SelectedShipIDs(), and SetActiveFleetWnd().
m_active_fleet_wnd_signals
std::vector<boost::signals2::connection> FleetUIManager::m_active_fleet_wnd_signals private
Referenced by SetActiveFleetWnd().
m_fleet_wnds
std::set<std::weak_ptr<FleetWnd>, std::owner_less<std::weak_ptr<FleetWnd> > > FleetUIManager::m_fleet_wnds mutable private
All fleet windows.
mutable so expired ptrs can be reset().
Referenced by begin(), CloseAll(), CullEmptyWnds(), empty(), EnableOrderIssuing(), end(), NewFleetWnd(), RefreshAll(), WndForFleetID(), and WndForFleetIDs().
m_order_issuing_enabled
bool FleetUIManager::m_order_issuing_enabled private
Referenced by EnableOrderIssuing(), and NewFleetWnd().
ShipRightClickedSignal
boost::signals2::signal<void (int)> FleetUIManager::ShipRightClickedSignal mutable
emitted when a ship is right-clicked
Referenced by MapWnd::CompleteConstruction(), and NewFleetWnd().
The documentation for this class was generated from the following files:
FleetWnd.h
FleetWnd.cpp