FreeOrion: Meter Class Reference
Meter Class Reference
A Meter is a value with an associated maximum value.
#include <Meter.h>
Public Member Functions
Structors
Meter ()
Creates a new meter with both initial and current value set to DEFAULT_VALUE.
Meter (float current_value)
Creates a new meter with the current value set to current_value and the initial value set to DEFAULT_VALUE.
Meter (float current_value, float initial_value)
Creates a new meter with the current value set to current_value and the initial value set to initial_value.
Accessors
float Current () const
returns the current value of the meter
float Initial () const
returns the value of the meter as it was at the beginning of the turn
std::string Dump (unsigned short ntabs=0) const
returns text of meter values
Mutators
void SetCurrent (float current_value)
sets current value, leaving initial value unchanged
void Set (float current_value, float initial_value)
sets current and initial values
void ResetCurrent ()
sets current value to DEFAULT_VALUE
void Reset ()
sets current and initial values to DEFAULT_VALUE
void AddToCurrent (float adjustment)
adds current to the current value of the Meter
void ClampCurrentToRange (float min=DEFAULT_VALUE, float max=LARGE_VALUE)
ensures the current value falls in the range [min, max]
void BackPropagate ()
sets previous equal to initial, then sets initial equal to current
Static Public Attributes
static constexpr float DEFAULT_VALUE = 0.0f
value assigned to current or initial when resetting or when no value is specified in a constructor
static const float INVALID_VALUE = -LARGE_VALUE
sentinel value to indicate no valid value for this meter
static const float LARGE_VALUE = static_cast<float>(2 << 15)
a very large number, which is useful to set current to when it will be later clamped, to ensure that the result is the max value in the clamp range
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
float m_current_value = DEFAULT_VALUE
float m_initial_value = DEFAULT_VALUE
Friends
class boost::serialization::access
Detailed Description
A Meter is a value with an associated maximum value.
A typical example is the population meter. The max represents the max pop for a planet, and the current represents the current pop there. The max may be adjusted upwards or downwards, and the current may be as well.
Constructor & Destructor Documentation
Meter() [1/3]
Meter::Meter ()
Creates a new meter with both initial and current value set to DEFAULT_VALUE.
Meter() [2/3]
Meter::Meter (float current_value) explicit
Creates a new meter with the current value set to current_value and the initial value set to DEFAULT_VALUE.
Meter() [3/3]
Meter::Meter (float current_value, float initial_value)
Creates a new meter with the current value set to current_value and the initial value set to initial_value.
Member Function Documentation
AddToCurrent()
void Meter::AddToCurrent (float adjustment)
adds current to the current value of the Meter
References m_current_value.
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), Universe::InitMeterEstimatesAndDiscrepancies(), and Universe::UpdateMeterEstimatesImpl().
BackPropagate()
void Meter::BackPropagate ()
sets previous equal to initial, then sets initial equal to current
References m_current_value, and m_initial_value.
Referenced by Empire::CheckProductionProgress(), Planet::Conquer(), and Ship::Resupply().
ClampCurrentToRange()
void Meter::ClampCurrentToRange (float min = DEFAULT_VALUE, float max = LARGE_VALUE)
ensures the current value falls in the range [min, max]
References m_current_value.
Referenced by Ship::ClampMeters(), Field::ClampMeters(), Planet::ClampMeters(), UniverseObject::ClampMeters(), PopCenter::PopCenterClampMeters(), and ResourceCenter::ResourceCenterClampMeters().
Current()
float Meter::Current () const
returns the current value of the meter
References m_current_value.
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetFighter(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), Fleet::BlockadedAtSystem(), Empire::CheckProductionProgress(), Ship::ClampMeters(), UniverseObject::Copy(), anonymous_namespace{CombatLogManager.cpp}::CurrentHealth(), PopCenter::CurrentMeterValue(), Ship::Dump(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), Effect::SetEmpireMeter::Execute(), Fleet::Fuel(), anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths(), anonymous_namespace{Universe.cpp}::GetEmpiresDetectionStrengths(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), Field::InField(), Universe::InitMeterEstimatesAndDiscrepancies(), MapWnd::InitVisibilityRadiiRenderingBuffers(), Condition::EmpireMeterValue::Match(), Fleet::MaxFuel(), anonymous_namespace{CombatLogManager.cpp}::MaxHealth(), Condition::anonymous_namespace{Conditions.cpp}::ShipPartMeterValueSimpleMatch::operator()(), SidePanel::PlanetPanel::Refresh(), MapWnd::RefreshDetectionIndicator(), Ship::Resupply(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), SetNativePopulationValues(), MultiMeterStatusBar::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), Universe::UpdateMeterEstimatesImpl(), MeterBrowseWnd::UpdateSummary(), and FreeOrionPython::WrapUniverseClasses().
Dump()
std::string Meter::Dump (unsigned short ntabs = 0) const
returns text of meter values
References m_current_value, and m_initial_value.
Referenced by Universe::UpdateMeterEstimatesImpl(), and FreeOrionPython::WrapUniverseClasses().
Initial()
float Meter::Initial () const
returns the value of the meter as it was at the beginning of the turn
References m_initial_value.
Referenced by UniverseObject::Copy(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), MultiMeterStatusBar::Update(), MeterBrowseWnd::UpdateSummary(), and FreeOrionPython::WrapUniverseClasses().
Reset()
void Meter::Reset ()
sets current and initial values to DEFAULT_VALUE
References DEFAULT_VALUE, m_current_value, and m_initial_value.
Referenced by PopCenter::Depopulate(), Planet::Depopulate(), PopCenter::Reset(), ResourceCenter::Reset(), and Planet::Reset().
ResetCurrent()
void Meter::ResetCurrent ()
sets current value to DEFAULT_VALUE
References DEFAULT_VALUE, and m_current_value.
Referenced by PopCenter::PopCenterResetTargetMaxUnpairedMeters(), Ship::ResetTargetMaxUnpairedMeters(), Field::ResetTargetMaxUnpairedMeters(), Planet::ResetTargetMaxUnpairedMeters(), and ResourceCenter::ResourceCenterResetTargetMaxUnpairedMeters().
serialize()
template<class Archive > void Meter::serialize (Archive & ar, const unsigned int version) private
Set()
void Meter::Set (float current_value, float initial_value)
sets current and initial values
References m_current_value, and m_initial_value.
Referenced by Field::Field(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop().
SetCurrent()
void Meter::SetCurrent (float current_value)
sets current value, leaving initial value unchanged
References m_current_value.
Referenced by Empire::CheckProductionProgress(), Planet::Colonize(), Planet::Conquer(), Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), Effect::SetEmpireMeter::Execute(), Ship::Resupply(), SetNativePopulationValues(), and Ship::SetShipMetersToMax().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
DEFAULT_VALUE
constexpr float Meter::DEFAULT_VALUE = 0.0f static
value assigned to current or initial when resetting or when no value is specified in a constructor
Referenced by Ship::ClampMeters(), Planet::ClampMeters(), Reset(), ResetCurrent(), and Universe::UpdateMeterEstimatesImpl().
INVALID_VALUE
const float Meter::INVALID_VALUE = -LARGE_VALUE static
sentinel value to indicate no valid value for this meter
Referenced by MultiMeterStatusBar::Render(), and MultiMeterStatusBar::Update().
LARGE_VALUE
const float Meter::LARGE_VALUE = static_cast<float>(2 << 15) static
a very large number, which is useful to set current to when it will be later clamped, to ensure that the result is the max value in the clamp range
Referenced by UniverseObject::CensoredMeters(), UniverseObject::Copy(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), NewFleetOrder::ExecuteImpl(), Fleet::Fuel(), anonymous_namespace{ServerWrapper.cpp}::LargeMeterValue(), Condition::MeterValue::Match(), Condition::ShipPartMeterValue::Match(), Condition::EmpireMeterValue::Match(), Condition::EmpireStockpileValue::Match(), Fleet::MaxFuel(), SetEmpireHomeworld(), and Ship::SetShipMetersToMax().
m_current_value
float Meter::m_current_value = DEFAULT_VALUE private
Referenced by AddToCurrent(), BackPropagate(), ClampCurrentToRange(), Current(), Dump(), Reset(), ResetCurrent(), Set(), and SetCurrent().
m_initial_value
float Meter::m_initial_value = DEFAULT_VALUE private
Referenced by BackPropagate(), Dump(), Initial(), Reset(), and Set().
The documentation for this class was generated from the following files:
Meter.h
Meter.cpp