FreeOrion: TechTreeWnd::TechListBox::TechRow Class Reference
TechTreeWnd::TechListBox::TechRow Class Reference
Public Member Functions
TechRow (GG::X w, const std::string &tech_name)
void CompleteConstruction () override
const std::string & GetTech ()
void Render () override
void Update ()
Static Public Member Functions
static std::vector< GG::Alignment > ColAlignments ()
static std::vector< GG::X > ColWidths (GG::X total_width)
Private Attributes
GG::Clr m_background_color
bool m_enqueued
std::string m_tech
Constructor & Destructor Documentation
TechRow()
TechTreeWnd::TechListBox::TechRow::TechRow (GG::X w, const std::string & tech_name)
Member Function Documentation
ColAlignments()
std::vector< GG::Alignment > TechTreeWnd::TechListBox::TechRow::ColAlignments () static
Referenced by TechTreeWnd::TechListBox::CompleteConstruction().
ColWidths()
std::vector< GG::X > TechTreeWnd::TechListBox::TechRow::ColWidths (GG::X total_width) static
References GetOptionsDB().
Referenced by TechTreeWnd::TechListBox::CompleteConstruction(), CompleteConstruction(), and TechTreeWnd::TechListBox::Update().
CompleteConstruction()
void TechTreeWnd::TechListBox::TechRow::CompleteConstruction () override
References Tech::Category(), ClientUI::CategoryColor(), ColWidths(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetTech(), m_tech, ClientUI::Pts(), Tech::ResearchCost(), Tech::ResearchTime(), Tech::ShortDescription(), ClientUI::TechIcon(), to_string(), and UserString().
GetTech()
const std::string& TechTreeWnd::TechListBox::TechRow::GetTech () inline
References TechTreeWnd::LayoutPanel::Update().
Referenced by CompleteConstruction(), TechTreeWnd::TechListBox::TechDoubleClicked(), TechTreeWnd::TechListBox::TechRightClicked(), and Update().
Render()
void TechTreeWnd::TechListBox::TechRow::Render () override
References ClientUI::WndColor().
Update()
void TechTreeWnd::TechListBox::TechRow::Update ()
References AdjustBrightness(), Tech::Category(), ClientUI::CategoryColor(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), GetTech(), ResearchQueue::InQueue(), m_background_color, m_enqueued, m_tech, Tech::ResearchCost(), Tech::ResearchTime(), TechRowBrowseWnd(), ClientUI::TextColor(), and to_string().
Member Data Documentation
m_background_color
GG::Clr TechTreeWnd::TechListBox::TechRow::m_background_color private
Referenced by Update().
m_enqueued
bool TechTreeWnd::TechListBox::TechRow::m_enqueued private
Referenced by Update().
m_tech
std::string TechTreeWnd::TechListBox::TechRow::m_tech private
Referenced by CompleteConstruction(), and Update().
The documentation for this class was generated from the following file:
TechTreeWnd.cpp