FreeOrion: CensoredCUIEdit Class Reference
CensoredCUIEdit Class Reference
a FreeOrion Edit control that replaces its displayed characters with a placeholder.
#include <CUIControls.h>
Public Member Functions
Structors
CensoredCUIEdit (const std::string &str, char display_placeholder= '*')
Accessors
const std::string & RawText () const
Mutators
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void SetText (const std::string &str) override
void AcceptPastedText (const std::string &text) override
Public Member Functions inherited from CUIEdit
CUIEdit (const std::string &str)
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
void GainingFocus () override
void LosingFocus () override
void Render () override
Protected Attributes
char m_placeholder = '*'
Private Member Functions
void ClearSelected ()
Private Attributes
std::string m_raw_text = ""
Additional Inherited Members
Public Attributes inherited from CUIEdit
boost::signals2::signal< void()> GainingFocusSignal
boost::signals2::signal< void()> LosingFocusSignal
Detailed Description
a FreeOrion Edit control that replaces its displayed characters with a placeholder.
Useful for password entry.
Constructor & Destructor Documentation
CensoredCUIEdit::CensoredCUIEdit (const std::string & str, char display_placeholder = '*') explicit
References m_placeholder, and m_raw_text.
Member Function Documentation
void CensoredCUIEdit::AcceptPastedText (const std::string & text) override
References ClearSelected(), m_raw_text, and SetText().
void CensoredCUIEdit::ClearSelected () private
References m_raw_text, and SetText().
Referenced by AcceptPastedText(), and KeyPress().
void CensoredCUIEdit::KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
References ClearSelected(), and CUIEdit::KeyPress().
const std::string & CensoredCUIEdit::RawText () const
References m_raw_text.
void CensoredCUIEdit::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
References UserString().
void CensoredCUIEdit::SetText (const std::string & str) override
References ErrorLogger, m_placeholder, and m_raw_text.
Referenced by AcceptPastedText(), and ClearSelected().
Member Data Documentation
char CensoredCUIEdit::m_placeholder = '*' protected
Referenced by CensoredCUIEdit(), and SetText().
std::string CensoredCUIEdit::m_raw_text = "" private
Referenced by AcceptPastedText(), CensoredCUIEdit(), ClearSelected(), RawText(), and SetText().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp