FreeOrion: PoliciesListBox Class Reference
PoliciesListBox Class Reference
Arrangement of PolicyControls that can be dragged onto SlotControls.
Classes
class PoliciesListBoxRow
Public Member Functions
PoliciesListBox (const AvailabilityManager &availabilities_state)
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
const AvailabilityManager & AvailabilityState () const
const std::set< std::string > & GetCategoriesShown () const
void HideAllCategories (bool refresh_list=true)
void HideCategory (const std::string &category, bool refresh_list=true)
void Populate ()
void ShowAllCategories (bool refresh_list=true)
void ShowCategory (const std::string &category, bool refresh_list=true)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
boost::signals2::signal< void(const std::string &)> ClearPolicySignal
boost::signals2::signal< void(const Policy *, GG::Flags< GG::ModKey >)> PolicyClickedSignal
boost::signals2::signal< void(const Policy *)> PolicyDoubleClickedSignal
boost::signals2::signal< void(const Policy *, const GG::Pt &pt)> PolicyRightClickedSignal
Protected Member Functions
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
PoliciesListBox accepts policies that are being removed from a PolicySlotControl.
Private Member Functions
std::map< std::string, std::vector< const Policy * > > GroupAvailableDisplayablePolicies (const Empire *empire) const
Private Attributes
const AvailabilityManager & m_availabilities_state
boost::signals2::connection m_empire_policies_changed_signal_connection
std::set< std::string > m_policy_categories_shown
int m_previous_num_columns = -1
Detailed Description
Arrangement of PolicyControls that can be dragged onto SlotControls.
Constructor & Destructor Documentation
PoliciesListBox()
PoliciesListBox::PoliciesListBox (const AvailabilityManager & availabilities_state) explicit
Member Function Documentation
AcceptDrops()
void PoliciesListBox::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
References ClearPolicySignal.
AvailabilityState()
const AvailabilityManager& PoliciesListBox::AvailabilityState () const inline
DropsAcceptable()
void PoliciesListBox::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const override protected
PoliciesListBox accepts policies that are being removed from a PolicySlotControl.
References if(), and anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_DROP_TYPE_STRING.
GetCategoriesShown()
const std::set< std::string > & PoliciesListBox::GetCategoriesShown () const
References m_policy_categories_shown.
GroupAvailableDisplayablePolicies()
std::map< std::string, std::vector< const Policy * > > PoliciesListBox::GroupAvailableDisplayablePolicies (const Empire * empire) const private
References GetPolicyManager(), m_availabilities_state, and m_policy_categories_shown.
Referenced by Populate().
HideAllCategories()
void PoliciesListBox::HideAllCategories (bool refresh_list = true)
References m_policy_categories_shown, and Populate().
HideCategory()
void PoliciesListBox::HideCategory (const std::string & category, bool refresh_list = true)
References m_policy_categories_shown, and Populate().
Populate()
void PoliciesListBox::Populate ()
References ClientApp::EmpireID(), GGHumanClientApp::GetApp(), GetEmpire(), GroupAvailableDisplayablePolicies(), m_availabilities_state, m_empire_policies_changed_signal_connection, m_previous_num_columns, anonymous_namespace{GovernmentWnd.cpp}::PAD, PolicyClickedSignal, PolicyDoubleClickedSignal, PolicyRightClickedSignal, ClientUI::ScrollWidth(), anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_HEIGHT, anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_WIDTH, and UserString().
Referenced by HideAllCategories(), HideCategory(), ShowAllCategories(), ShowCategory(), and SizeMove().
ShowAllCategories()
void PoliciesListBox::ShowAllCategories (bool refresh_list = true)
References GetPolicyManager(), m_policy_categories_shown, PolicyManager::PolicyCategories(), and Populate().
ShowCategory()
void PoliciesListBox::ShowCategory (const std::string & category, bool refresh_list = true)
References m_policy_categories_shown, and Populate().
SizeMove()
void PoliciesListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References m_previous_num_columns, anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS(), anonymous_namespace{GovernmentWnd.cpp}::PAD, Populate(), ClientUI::ScrollWidth(), and anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_WIDTH.
Member Data Documentation
ClearPolicySignal
boost::signals2::signal<void (const std::string&)> PoliciesListBox::ClearPolicySignal mutable
Referenced by AcceptDrops().
m_availabilities_state
const AvailabilityManager& PoliciesListBox::m_availabilities_state private
Referenced by GroupAvailableDisplayablePolicies(), and Populate().
m_empire_policies_changed_signal_connection
boost::signals2::connection PoliciesListBox::m_empire_policies_changed_signal_connection mutable private
Referenced by Populate().
m_policy_categories_shown
std::set<std::string> PoliciesListBox::m_policy_categories_shown private
Referenced by GetCategoriesShown(), GroupAvailableDisplayablePolicies(), HideAllCategories(), HideCategory(), ShowAllCategories(), and ShowCategory().
m_previous_num_columns
int PoliciesListBox::m_previous_num_columns = -1 private
Referenced by Populate(), and SizeMove().
PolicyClickedSignal
boost::signals2::signal<void (const Policy*, GG::Flags<GG::ModKey>)> PoliciesListBox::PolicyClickedSignal mutable
Referenced by Populate().
PolicyDoubleClickedSignal
boost::signals2::signal<void (const Policy*)> PoliciesListBox::PolicyDoubleClickedSignal mutable
Referenced by Populate().
PolicyRightClickedSignal
boost::signals2::signal<void (const Policy*, const GG::Pt& pt)> PoliciesListBox::PolicyRightClickedSignal mutable
Referenced by Populate().
The documentation for this class was generated from the following file:
GovernmentWnd.cpp