FreeOrion: BasesListBox Class Reference
BasesListBox Class Reference
Classes
class BasesListBoxRow
class CompletedDesignListBoxRow
class HullAndPartsListBoxRow
class HullPanel
class SavedDesignListBoxRow
class SavedDesignPanel
Public Member Functions
Structors
BasesListBox (const std::string &drop_type="")
Accessors
const std::pair< bool, bool > & GetAvailabilitiesShown () const
Mutators
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void ChildrenDraggedAway (const std::vector< GG::Wnd * > &wnds, const GG::Wnd *destination) override
void EnableOrderIssuing (bool enable=true) override
void QueueItemMoved (GG::ListBox::Row *row, std::size_t position)
void SetEmpireShown (int empire_id, bool refresh_list=true)
virtual void Populate ()
void ShowEmptyHulls (bool refresh_list=true)
void ShowCompletedDesigns (bool refresh_list=true)
void ShowSavedDesigns (bool refresh_list=true)
void ShowMonsters (bool refresh_list=true)
void ShowAvailability (bool available, bool refresh_list=true)
void HideAvailability (bool available, bool refresh_list=true)
Public Member Functions inherited from QueueListBox
QueueListBox (const std::string &drop_type_str, const std::string &prompt_str)
void AcceptDrops (const GG::Pt &pt, const std::vector< GG::Wnd * > &wnds, GG::Flags< GG::ModKey > mod_keys) override
void Clear ()
bool DisplayingValidQueueItems ()
whether or not this QueueListBox is displaying valid queue items, as opposed to, for example, a prompt for the user to enter an item
void DragDropHere (const GG::Pt &pt, std::map< const GG::Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
bool OrderIssuingEnabled () const
void Render () override
GG::X RowWidth () const
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
boost::signals2::signal< void(const ShipDesign *)> DesignClickedSignal
boost::signals2::signal< void(const std::string &, const std::vector< std::string > &)> DesignComponentsSelectedSignal
boost::signals2::signal< void(const ShipDesign *)> DesignRightClickedSignal
boost::signals2::signal< void(int)> DesignSelectedSignal
boost::signals2::signal< void(const HullType *)> HullClickedSignal
boost::signals2::signal< void(const std::string &)> SavedDesignSelectedSignal
Public Attributes inherited from QueueListBox
boost::signals2::signal< void(GG::ListBox::iterator)> QueueItemDeletedSignal
boost::signals2::signal< void(GG::ListBox::Row *, std::size_t)> QueueItemMovedSignal
Static Public Attributes
static const std::string BASES_LIST_BOX_DROP_TYPE = "BasesListBoxRow"
Protected Member Functions
void ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys) override
Protected Member Functions inherited from QueueListBox
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
void KeyPress (GG::Key key, std::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) override
Private Member Functions
void BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void BaseRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void InitRowSizes ()
GG::Pt ListRowSize ()
void PopulateWithCompletedDesigns ()
void PopulateWithEmptyHulls ()
void PopulateWithMonsters ()
void PopulateWithSavedDesigns ()
Private Attributes
std::pair< bool, bool > m_availabilities_shown
boost::signals2::connection m_empire_designs_changed_signal
int m_empire_id_shown
bool m_enabled
active player (true) or observer (false)
std::set< std::string > m_hulls_in_list
std::set< std::string > m_saved_desgins_in_list
bool m_showing_completed_designs
bool m_showing_empty_hulls
bool m_showing_monsters
bool m_showing_saved_designs
Detailed Description
List of starting points for designs, such as empty hulls, existing designs kept by this empire or seen elsewhere in the universe, design template scripts or saved (on disk) designs from previous games.
Constructor & Destructor Documentation
BasesListBox::BasesListBox (const std::string & drop_type = "")
References BaseDoubleClicked(), BaseLeftClicked(), InitRowSizes(), m_enabled, m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, QueueItemMoved(), and QueueListBox::QueueItemMovedSignal.
Member Function Documentation
void BasesListBox::BaseDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References DesignComponentsSelectedSignal, BasesListBox::CompletedDesignListBoxRow::DesignID(), BasesListBox::SavedDesignListBoxRow::DesignName(), DesignSelectedSignal, BasesListBox::HullAndPartsListBoxRow::Hull(), ShipDesign::INVALID_DESIGN_ID, BasesListBox::HullAndPartsListBoxRow::Parts(), and SavedDesignSelectedSignal.
Referenced by BasesListBox().
void BasesListBox::BaseLeftClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References DesignClickedSignal, BasesListBox::CompletedDesignListBoxRow::DesignID(), BasesListBox::SavedDesignListBoxRow::DesignName(), AIInterface::EmpireID(), HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), GetHullType(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), GetShipDesign(), BasesListBox::HullAndPartsListBoxRow::Hull(), HullClickedSignal, OrderSet::IssueOrder(), ClientApp::Orders(), and BasesListBox::HullAndPartsListBoxRow::Parts().
Referenced by BasesListBox().
void BasesListBox::BaseRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ALL_EMPIRES, DebugLogger, ShipDesign::DesignedByEmpire(), DesignRightClickedSignal, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), ClientApp::GetNewDesignID(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), GetShipDesign(), OrderSet::IssueOrder(), ShipDesign::Name(), ClientApp::Orders(), CUIEditWnd::Result(), anonymous_namespace{DesignWnd.cpp}::ShowSaveDesignDialog(), and UserString().
Referenced by ItemRightClickedImpl().
void BasesListBox::ChildrenDraggedAway (const std::vector< GG::Wnd * > & wnds, const GG::Wnd * destination) override
References anonymous_namespace{DesignWnd.cpp}::COMPLETE_DESIGN_ROW_DROP_STRING, BasesListBox::CompletedDesignListBoxRow::DesignID(), BasesListBox::SavedDesignListBoxRow::DesignName(), ErrorLogger, BasesListBox::HullAndPartsListBoxRow::Hull(), anonymous_namespace{DesignWnd.cpp}::HULL_PARTS_ROW_DROP_TYPE_STRING, ListRowSize(), and anonymous_namespace{DesignWnd.cpp}::SAVED_DESIGN_ROW_DROP_STRING.
void BasesListBox::EnableOrderIssuing (bool enable = true) override virtual
Reimplemented from QueueListBox.
References QueueListBox::EnableOrderIssuing(), m_enabled, and m_showing_completed_designs.
Referenced by DesignWnd::BaseSelector::EnableOrderIssuing(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
const std::pair< bool, bool > & BasesListBox::GetAvailabilitiesShown () const
References m_availabilities_shown.
Referenced by DesignWnd::BaseSelector::ToggleAvailability().
void BasesListBox::HideAvailability (bool available, bool refresh_list = true)
References m_availabilities_shown, and Populate().
Referenced by DesignWnd::BaseSelector::HideAvailability().
void BasesListBox::InitRowSizes () private
Referenced by BasesListBox().
void BasesListBox::ItemRightClickedImpl (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) override protected virtual
Reimplemented from QueueListBox.
References BaseRightClicked().
GG::Pt BasesListBox::ListRowSize () private
References anonymous_namespace{DesignWnd.cpp}::BASES_LIST_BOX_ROW_HEIGHT(), and ClientUI::ScrollWidth().
Referenced by ChildrenDraggedAway(), PopulateWithCompletedDesigns(), PopulateWithEmptyHulls(), PopulateWithMonsters(), PopulateWithSavedDesigns(), QueueItemMoved(), and SizeMove().
void BasesListBox::Populate () virtual
References DebugLogger, m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, PopulateWithCompletedDesigns(), PopulateWithEmptyHulls(), PopulateWithMonsters(), and PopulateWithSavedDesigns().
Referenced by HideAvailability(), SetEmpireShown(), ShowAvailability(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
void BasesListBox::PopulateWithCompletedDesigns () private
References Universe::beginShipDesigns(), QueueListBox::Clear(), DebugLogger, Universe::endShipDesigns(), GetEmpire(), GetShipDesign(), GetUniverse(), ListRowSize(), m_availabilities_shown, m_empire_id_shown, Empire::OrderedShipDesigns(), ShipDesign::Producible(), and Empire::ShipDesignAvailable().
Referenced by Populate().
void BasesListBox::PopulateWithEmptyHulls () private
References DebugLogger, GetEmpire(), GetHullTypeManager(), ListRowSize(), m_availabilities_shown, m_empire_id_shown, m_hulls_in_list, HullType::Producible(), and Empire::ShipHullAvailable().
Referenced by Populate().
void BasesListBox::PopulateWithMonsters () private
References Universe::beginShipDesigns(), QueueListBox::Clear(), Universe::endShipDesigns(), GetUniverse(), ShipDesign::IsMonster(), and ListRowSize().
Referenced by Populate().
void BasesListBox::PopulateWithSavedDesigns () private
References QueueListBox::Clear(), DebugLogger, anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), and ListRowSize().
Referenced by Populate().
void BasesListBox::QueueItemMoved (GG::ListBox::Row * row, std::size_t position)
References BasesListBox::CompletedDesignListBoxRow::DesignID(), HumanClientApp::GetApp(), GetEmpire(), ShipDesign::INVALID_DESIGN_ID, OrderSet::IssueOrder(), ListRowSize(), m_empire_id_shown, and ClientApp::Orders().
Referenced by BasesListBox().
void BasesListBox::SetEmpireShown (int empire_id, bool refresh_list = true)
References GetEmpire(), m_empire_designs_changed_signal, m_empire_id_shown, and Populate().
Referenced by DesignWnd::BaseSelector::SetEmpireShown().
void BasesListBox::ShowAvailability (bool available, bool refresh_list = true)
References m_availabilities_shown, and Populate().
Referenced by DesignWnd::BaseSelector::ShowAvailability().
void BasesListBox::ShowCompletedDesigns (bool refresh_list = true)
References EnableOrderIssuing(), m_enabled, m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, and Populate().
Referenced by DesignWnd::BaseSelector::BaseSelector().
void BasesListBox::ShowEmptyHulls (bool refresh_list = true)
References EnableOrderIssuing(), m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, and Populate().
Referenced by DesignWnd::BaseSelector::BaseSelector().
void BasesListBox::ShowMonsters (bool refresh_list = true)
References EnableOrderIssuing(), m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, and Populate().
Referenced by DesignWnd::BaseSelector::BaseSelector().
void BasesListBox::ShowSavedDesigns (bool refresh_list = true)
References EnableOrderIssuing(), m_showing_completed_designs, m_showing_empty_hulls, m_showing_monsters, m_showing_saved_designs, and Populate().
Referenced by DesignWnd::BaseSelector::BaseSelector().
void BasesListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References ListRowSize().
Member Data Documentation
const std::string BasesListBox::BASES_LIST_BOX_DROP_TYPE = "BasesListBoxRow" static
Referenced by BasesListBox::SavedDesignListBoxRow::LookupInStringtable().
boost::signals2::signal<void (const ShipDesign*)> BasesListBox::DesignClickedSignal mutable
Referenced by BaseLeftClicked(), and DesignWnd::BaseSelector::BaseSelector().
boost::signals2::signal<void (const std::string&, const std::vector<std::string>&)> BasesListBox::DesignComponentsSelectedSignal mutable
Referenced by BaseDoubleClicked(), and DesignWnd::BaseSelector::BaseSelector().
boost::signals2::signal<void (const ShipDesign*)> BasesListBox::DesignRightClickedSignal mutable
Referenced by BaseRightClicked().
boost::signals2::signal<void (int)> BasesListBox::DesignSelectedSignal mutable
Referenced by BaseDoubleClicked(), and DesignWnd::BaseSelector::BaseSelector().
boost::signals2::signal<void (const HullType*)> BasesListBox::HullClickedSignal mutable
Referenced by BaseLeftClicked(), and DesignWnd::BaseSelector::BaseSelector().
std::pair<bool, bool> BasesListBox::m_availabilities_shown private
Referenced by GetAvailabilitiesShown(), HideAvailability(), PopulateWithCompletedDesigns(), PopulateWithEmptyHulls(), and ShowAvailability().
boost::signals2::connection BasesListBox::m_empire_designs_changed_signal private
Referenced by SetEmpireShown().
int BasesListBox::m_empire_id_shown private
Referenced by PopulateWithCompletedDesigns(), PopulateWithEmptyHulls(), QueueItemMoved(), and SetEmpireShown().
bool BasesListBox::m_enabled private
active player (true) or observer (false)
Referenced by BasesListBox(), EnableOrderIssuing(), and ShowCompletedDesigns().
std::set<std::string> BasesListBox::m_hulls_in_list private
Referenced by PopulateWithEmptyHulls().
std::set<std::string> BasesListBox::m_saved_desgins_in_list private
bool BasesListBox::m_showing_completed_designs private
Referenced by BasesListBox(), EnableOrderIssuing(), Populate(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
bool BasesListBox::m_showing_empty_hulls private
Referenced by BasesListBox(), Populate(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
bool BasesListBox::m_showing_monsters private
Referenced by BasesListBox(), Populate(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
bool BasesListBox::m_showing_saved_designs private
Referenced by BasesListBox(), Populate(), ShowCompletedDesigns(), ShowEmptyHulls(), ShowMonsters(), and ShowSavedDesigns().
boost::signals2::signal<void (const std::string&)> BasesListBox::SavedDesignSelectedSignal mutable
Referenced by BaseDoubleClicked(), and DesignWnd::BaseSelector::BaseSelector().
The documentation for this class was generated from the following file:
DesignWnd.cpp