FreeOrion: Effect::SetMeter Class Reference
Effect::SetMeter Class Reference
#include <Effect.h>
Public Member Functions
SetMeter (MeterType meter, std::unique_ptr< ValueRef::ValueRefBase< double >> &&value)
SetMeter (MeterType meter, std::unique_ptr< ValueRef::ValueRefBase< double >> &&value, const std::string &accounting_label)
virtual ~SetMeter ()
const std::string & AccountingLabel () const
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
void Execute (const ScriptingContext &context, const TargetSet &targets) const override
void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const override
unsigned int GetCheckSum () const override
MeterType GetMeterType () const
bool IsMeterEffect () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_accounting_label
MeterType m_meter
std::unique_ptr< ValueRef::ValueRefBase< double > > m_value
Friends
class boost::serialization::access
Detailed Description
Sets the meter of the given kind to value. The max value of the meter is set if max == true; otherwise the current value of the meter is set. If the target of the Effect does not have the requested meter, nothing is done.
Constructor & Destructor Documentation
Effect::SetMeter::SetMeter (MeterType meter, std::unique_ptr< ValueRef::ValueRefBase< double >> && value)
Effect::SetMeter::SetMeter (MeterType meter, std::unique_ptr< ValueRef::ValueRefBase< double >> && value, const std::string & accounting_label)
Effect::SetMeter::~SetMeter () virtual
Member Function Documentation
const std::string& Effect::SetMeter::AccountingLabel () const inline
std::string Effect::SetMeter::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), m_meter, m_value, METER_BATTLE_DETECTION, METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STEALTH, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by Execute().
void Effect::SetMeter::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References Meter::Current(), ScriptingContext::effect_target, m_meter, m_value, and Meter::SetCurrent().
Referenced by Execute().
void Effect::SetMeter::Execute (const ScriptingContext & context, const TargetSet & targets) const override virtual
Reimplemented from Effect::EffectBase.
References Meter::AddToCurrent(), ErrorLogger, Effect::EffectBase::Execute(), ValueRef::Operation< T >::GetOpType(), m_meter, m_value, ValueRef::MINUS, ValueRef::PLUS, ValueRef::Operation< T >::RHS(), and Meter::SetCurrent().
void Effect::SetMeter::Execute (const ScriptingContext & context, const TargetSet & targets, AccountingMap * accounting_map, const EffectCause & effect_cause, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const override virtual
Reimplemented from Effect::EffectBase.
References Effect::EffectCause::cause_type, Meter::Current(), Effect::EffectCause::custom_label, Dump(), Execute(), info, m_accounting_label, m_meter, Effect::AccountingInfo::meter_change, Effect::AccountingInfo::running_meter_total, ScriptingContext::source, Effect::AccountingInfo::source_id, Effect::EffectCause::specific_cause, and TraceLogger.
unsigned int Effect::SetMeter::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_accounting_label, m_meter, m_value, and TraceLogger.
MeterType Effect::SetMeter::GetMeterType () const inline
bool Effect::SetMeter::IsMeterEffect () const inline override virtual
Reimplemented from Effect::EffectBase.
template<class Archive > void Effect::SetMeter::serialize (Archive & ar, const unsigned int version) private
void Effect::SetMeter::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_value.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::string Effect::SetMeter::m_accounting_label private
Referenced by Execute(), and GetCheckSum().
MeterType Effect::SetMeter::m_meter private
Referenced by Dump(), Execute(), and GetCheckSum().
std::unique_ptr<ValueRef::ValueRefBase<double> > Effect::SetMeter::m_value private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp