FreeOrion: Effect::MoveTo Class Reference
Effect::MoveTo Class Reference final
Moves an UniverseObject to a location of another UniverseObject that matches the condition location_condition.
#include <Effects.h>
Public Member Functions
MoveTo (std::unique_ptr< Condition::Condition > &&location_condition)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
virtual void Execute (ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< Condition::Condition > m_location_condition
Friends
class boost::serialization::access
Detailed Description
Moves an UniverseObject to a location of another UniverseObject that matches the condition location_condition.
If multiple objects match the condition, then one is chosen. If no objects match the condition, then nothing is done.
Constructor & Destructor Documentation
MoveTo()
Effect::MoveTo::MoveTo (std::unique_ptr< Condition::Condition > && location_condition) explicit
Member Function Documentation
Dump()
std::string Effect::MoveTo::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent(), and m_location_condition.
Execute()
void Effect::MoveTo::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References ObjectMap::all(), ScriptingContext::ContextObjects(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), ScriptingContext::effect_target, Universe::EffectDestroy(), ErrorLogger, anonymous_namespace{Effects.cpp}::ExploreSystem(), ObjectMap::find(), ObjectMap::get(), GetUniverse(), INVALID_OBJECT_ID, m_location_condition, UniverseObject::Owner(), System::Remove(), Fleet::RemoveShips(), and anonymous_namespace{Effects.cpp}::UpdateFleetRoute().
GetCheckSum()
unsigned int Effect::MoveTo::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), m_location_condition, and TraceLogger.
serialize()
template<typename Archive > void Effect::MoveTo::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::MoveTo::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::Effect.
References m_location_condition.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_location_condition
std::unique_ptr<Condition::Condition> Effect::MoveTo::m_location_condition private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp