FreeOrion: SidePanel Class Reference
SidePanel Class Reference
#include <SidePanel.h>
Classes
class PlanetPanel
class PlanetPanelContainer
class SystemNameDropDownList
Public Member Functions
Structors
SidePanel (const std::string &config_name)
void CompleteConstruction () override
~SidePanel ()
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
void CompleteConstruction () override
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
GG::Pt ClientUpperLeft () const override
returns true if window is minimized
GG::Pt ClientLowerRight () const override
returns true if window is minimized
bool InWindow (const GG::Pt &pt) const override
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Render () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void MouseLeave () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Hide () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Show () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Static Public Attributes
static boost::signals2::signal< void(int)> BuildingRightClickedSignal
static boost::signals2::signal< void(int)> PlanetDoubleClickedSignal
static boost::signals2::signal< void(int)> PlanetRightClickedSignal
static boost::signals2::signal< void(int)> PlanetSelectedSignal
static boost::signals2::signal< void()> ResourceCenterChangedSignal
static boost::signals2::signal< void(int)> SystemSelectedSignal
Protected Member Functions
void InitBuffers () override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
void LoadOptions ()
loads options for this window from the OptionsDB
void Init ()
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
void SetParent (const std::shared_ptr< GG::Wnd > &wnd) override
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void SetDefaultedOptions ()
void SaveDefaultedOptions ()
Private Member Functions
void DoLayout ()
void NextButtonClicked ()
responts to user clicking previous system button
void PlanetClickedSlot (int planet_id)
void PrevButtonClicked ()
responds to user clicking next system button
void RefreshImpl ()
fully refreshes contents. to be used when objects are created, destroyed or added to system
void RefreshInPreRender ()
void RefreshSystemNames ()
void SystemNameDropListOpenedSlot (bool is_open)
void SystemSelectionChangedSlot (GG::DropDownList::iterator it)
void UpdateImpl ()
updates contents quickly. to be used when meters or other objects' data changes
Static Private Member Functions
static void FleetsInserted (const std::vector< std::shared_ptr< Fleet >> &fleets)
static void FleetsRemoved (const std::vector< std::shared_ptr< Fleet >> &fleets)
Private Attributes
std::shared_ptr< GG::Button > m_button_next = nullptr
std::shared_ptr< GG::Button > m_button_prev = nullptr
std::vector< GG::SubTexture > m_fleet_icons
std::shared_ptr< PlanetPanelContainer > m_planet_panel_container = nullptr
bool m_selection_enabled = false
std::shared_ptr< GG::DynamicGraphic > m_star_graphic = nullptr
std::shared_ptr< GG::TextControl > m_star_type_text = nullptr
std::shared_ptr< SystemNameDropDownList > m_system_name = nullptr
std::shared_ptr< MultiIconValueIndicator > m_system_resource_summary = nullptr
Static Private Attributes
static std::map< int, boost::signals2::connection > s_fleet_state_change_signals
static bool s_needs_refresh = false
static bool s_needs_update = false
static int s_planet_id = INVALID_OBJECT_ID
static std::set< std::weak_ptr< SidePanel >, std::owner_less< std::weak_ptr< SidePanel > > > s_side_panels
static std::set< boost::signals2::connection > s_system_connections
static int s_system_id = INVALID_OBJECT_ID
Accessors
bool InWindow (const GG::Pt &pt) const override
GG::Pt ClientUpperLeft () const override
int SelectedPlanetID () const
bool PlanetSelectable (int planet_id) const
static int SystemID ()
Mutators
void PreRender () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void EnableSelection (bool enable=true)
void EnableOrderIssuing (bool enable=true)
static void Update ()
static void Refresh ()
static void SelectPlanet (int planet_id)
static void SetSystem (int system_id)
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "ui."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
std::shared_ptr< GG::Button > m_close_button = nullptr
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save = true
true if SaveOptions() is currently allowed to write to the OptionsDB
std::unordered_set< std::string > m_defaulted_options
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
std::shared_ptr< CUI_MinRestoreButton > m_minimize_button = nullptr
the minimize/restore button
bool m_minimized = false
true if the window is currently minimized
bool m_mouse_in_resize_tab = false
GG::Pt m_original_size
keeps track of the size of the window before resizing
std::shared_ptr< CUI_PinButton > m_pin_button = nullptr
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned = false
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Constructor & Destructor Documentation
SidePanel::SidePanel (const std::string & config_name)
SidePanel::~SidePanel ()
References s_fleet_state_change_signals, and s_system_connections.
Member Function Documentation
GG::Pt SidePanel::ClientUpperLeft () const override
Returns the id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected
References CUIWnd::BORDER_BOTTOM, and CUIWnd::BORDER_LEFT.
Referenced by InitBuffers().
void SidePanel::CompleteConstruction () override
References ClientUI::ArtDir(), CUIWnd::BORDER_LEFT, CUIWnd::BORDER_RIGHT, BuildingRightClickedSignal, CUIWnd::CompleteConstruction(), anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), ClientUI::GetFont(), ClientUI::GetTexture(), CUIWnd::Hide(), m_button_next, m_button_prev, m_planet_panel_container, m_star_type_text, m_system_name, m_system_resource_summary, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), NextButtonClicked(), anonymous_namespace{SidePanel.cpp}::PLANET_PANEL_TOP, PlanetClickedSlot(), PlanetDoubleClickedSignal, PlanetRightClickedSignal, PrevButtonClicked(), s_needs_refresh, s_needs_update, s_side_panels, SystemNameDropListOpenedSlot(), SystemSelectionChangedSlot(), and ClientUI::TextColor().
void SidePanel::DoLayout () private
References CUIWnd::BORDER_LEFT, anonymous_namespace{SidePanel.cpp}::EDGE_PAD(), GetSystem(), CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_button_next, m_button_prev, m_planet_panel_container, m_star_type_text, m_system_name, m_system_resource_summary, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), anonymous_namespace{SidePanel.cpp}::PLANET_PANEL_TOP, and s_system_id.
Referenced by PreRender().
void SidePanel::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via the SidePanel.
References m_planet_panel_container, and m_system_name.
void SidePanel::EnableSelection (bool enable = true)
Enables, or disables if enable is false, selection of planet panels within this SidePanel. Panels that can be selected are those which meet selection conditions that need to be figured out and perhaps made more configurable, but for now are just those planets owned by this client's empire.
References m_selection_enabled.
void SidePanel::FleetsInserted (const std::vector< std::shared_ptr< Fleet >> & fleets) static private
Responds to insertion fleets into system during a turn. may update colonize buttons.
References s_fleet_state_change_signals, and Update().
Referenced by RefreshInPreRender().
void SidePanel::FleetsRemoved (const std::vector< std::shared_ptr< Fleet >> & fleets) static private
Responds to removal fleets from system during a turn. may update colonize buttons.
References s_fleet_state_change_signals, and Update().
Referenced by RefreshInPreRender().
void SidePanel::InitBuffers () override protected virtual
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Reimplemented from CUIWnd.
References CUIWnd::BORDER_BOTTOM, CUIWnd::BORDER_RIGHT, ClientUpperLeft(), CUIWnd::INNER_BORDER_ANGLE_OFFSET, CUIWnd::m_buffer_indices, CUIWnd::m_resizable, CUIWnd::m_vertex_buffer, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), CUIWnd::OUTER_EDGE_ANGLE_OFFSET, anonymous_namespace{SidePanel.cpp}::PLANET_PANEL_TOP, CUIWnd::RESIZE_HASHMARK1_OFFSET, and CUIWnd::RESIZE_HASHMARK2_OFFSET.
bool SidePanel::InWindow (const GG::Pt & pt) const override
Returns the id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected
References m_planet_panel_container, m_system_resource_summary, and anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter().
void SidePanel::NextButtonClicked () private
responts to user clicking previous system button
References m_system_name, and SystemSelectionChangedSlot().
Referenced by CompleteConstruction().
void SidePanel::PlanetClickedSlot (int planet_id) private
Respond to the user clicking a planet by selecting it if selection is enabled.
References m_selection_enabled, and SelectPlanet().
Referenced by CompleteConstruction().
bool SidePanel::PlanetSelectable (int planet_id) const
Returns whether this SidePanel contains an object with the indicated object_id that can be selected within the SidePanel.
References ALL_EMPIRES, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetPlanet(), GetSystem(), m_selection_enabled, and s_system_id.
void SidePanel::PreRender () override
Enables, or disables if enable is false, selection of planet panels within this SidePanel. Panels that can be selected are those which meet selection conditions that need to be figured out and perhaps made more configurable, but for now are just those planets owned by this client's empire.
References DoLayout(), m_planet_panel_container, RefreshInPreRender(), s_needs_refresh, s_needs_update, s_planet_id, and s_side_panels.
void SidePanel::PrevButtonClicked () private
responds to user clicking next system button
References m_system_name, and SystemSelectionChangedSlot().
Referenced by CompleteConstruction().
void SidePanel::Refresh () static
Make refresh of sidepanel and contents happen during pre-render. PreRender() Will recreate all contents from the stored system id. All SidePanels are refreshed.
References s_needs_refresh, and s_side_panels.
Referenced by MapWnd::InitTurn(), MapWnd::MidTurnUpdate(), GovernmentWnd::MainPanel::SetPolicy(), and SetSystem().
void SidePanel::RefreshImpl () private
fully refreshes contents. to be used when objects are created, destroyed or added to system
References ALL_EMPIRES, ClientUI::ArtDir(), ClientApp::EmpireID(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), anonymous_namespace{SidePanel.cpp}::GetStarTypeName(), GetSystem(), m_planet_panel_container, m_selection_enabled, m_star_graphic, m_star_type_text, m_system_resource_summary, anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), METER_DEFENSE, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_RESEARCH, METER_SHIELD, METER_STOCKPILE, METER_SUPPLY, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TROOPS, MeterToResource(), Objects(), RefreshSystemNames(), s_system_id, and ClientUI::StarTypeFilePrefixes().
void SidePanel::RefreshInPreRender () private
Fully refreshes sidepanel and contents, recreating all contents from stored system id. All SidePanels are refreshed.
References anonymous_namespace{SidePanel.cpp}::colony_projections, ErrorLogger, ObjectMap::FindObjects(), FleetsInserted(), FleetsRemoved(), GetSystem(), INVALID_OBJECT_ID, Objects(), ResourceCenterChangedSignal, s_fleet_state_change_signals, s_side_panels, s_system_connections, s_system_id, anonymous_namespace{SidePanel.cpp}::species_colony_projections, and Update().
Referenced by PreRender().
void SidePanel::RefreshSystemNames () private
Insert all known systems into the SystemName drop down list.
References ClientUI::GetBoldFont(), m_system_name, Objects(), s_system_id, and anonymous_namespace{SidePanel.cpp}::SystemNameFontSize().
Referenced by RefreshImpl(), and SystemNameDropListOpenedSlot().
int SidePanel::SelectedPlanetID () const
Returns the id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected
References INVALID_OBJECT_ID, m_selection_enabled, and s_planet_id.
void SidePanel::SelectPlanet (int planet_id) static
Selects the planet with id planet_id within the current system, if such a planet exists. All SidePanels' selected planets are set, if those panels have planet selection enabled.
References INVALID_OBJECT_ID, PlanetSelectedSignal, s_planet_id, and s_side_panels.
Referenced by PlanetClickedSlot(), and BuildDesignatorWnd::SelectPlanet().
void SidePanel::SetSystem (int system_id) static
Sets the system currently being viewed in all side panels
References GetSystem(), INVALID_OBJECT_ID, anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound(), Refresh(), and s_system_id.
Referenced by BuildDesignatorWnd::Clear(), BuildDesignatorWnd::SelectSystem(), and MapWnd::SelectSystem().
void SidePanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Enables, or disables if enable is false, selection of planet panels within this SidePanel. Panels that can be selected are those which meet selection conditions that need to be figured out and perhaps made more configurable, but for now are just those planets owned by this client's empire.
References CUIWnd::SizeMove().
int SidePanel::SystemID () static
Returns the id of the system shown in the SidePanels, or INVALID_OBJECT_ID if no system is shown
References s_system_id.
Referenced by SidePanel::PlanetPanel::ClickColonize(), MapWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitTurnRendering(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), ProductionWnd::QueueItemRallied(), SidePanel::PlanetPanel::Refresh(), MapWnd::RenderScaleCircle(), MapWnd::ReselectLastSystem(), BuildDesignatorWnd::SelectDefaultPlanet(), BuildDesignatorWnd::SelectPlanet(), BuildDesignatorWnd::SelectSystem(), ProductionWnd::SelectSystem(), MapWnd::SelectSystem(), MapWnd::SetZoom(), MapWnd::ShowProduction(), MapWnd::SystemRightClicked(), SystemSelectionChangedSlot(), MapWnd::UpdateSidePanelSystemObjectMetersAndResourcePools(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToNextSystem(), MapWnd::ZoomToPrevOwnedSystem(), and MapWnd::ZoomToPrevSystem().
void SidePanel::SystemNameDropListOpenedSlot (bool is_open) private
Refresh the system name list when it closes, in case the known systems changed while it was open.
References RefreshSystemNames().
Referenced by CompleteConstruction().
void SidePanel::SystemSelectionChangedSlot (GG::DropDownList::iterator it) private
Handle the user selecting a system in the droplist while the list is closed, using keys. It may emit SystemSelectedSignal.
This handles cases when the list is dropped and not dropped in the same way. Refresh should not update the list of systems if the list is open.
References INVALID_OBJECT_ID, m_system_name, SystemID(), and SystemSelectedSignal.
Referenced by CompleteConstruction(), NextButtonClicked(), and PrevButtonClicked().
void SidePanel::Update () static
Updates contents of sidepanel, but doesn't recreate contents or check that object pointers are still valid. All SidePanels' are updated
References s_needs_update, and s_side_panels.
Referenced by FleetsInserted(), FleetsRemoved(), RefreshInPreRender(), MapWnd::SelectedShipsChanged(), BuildDesignatorWnd::Update(), and MapWnd::UpdateEmpireResourcePools().
void SidePanel::UpdateImpl () private
updates contents quickly. to be used when meters or other objects' data changes
References m_planet_panel_container, and m_system_resource_summary.
Member Data Documentation
boost::signals2::signal< void(int)> SidePanel::BuildingRightClickedSignal static
emitted when a building is right clicked
Referenced by CompleteConstruction(), and MapWnd::CompleteConstruction().
std::shared_ptr<GG::Button> SidePanel::m_button_next = nullptr private
Referenced by CompleteConstruction(), and DoLayout().
std::shared_ptr<GG::Button> SidePanel::m_button_prev = nullptr private
Referenced by CompleteConstruction(), and DoLayout().
std::vector<GG::SubTexture> SidePanel::m_fleet_icons private
std::shared_ptr<PlanetPanelContainer> SidePanel::m_planet_panel_container = nullptr private
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), InWindow(), PreRender(), RefreshImpl(), and UpdateImpl().
bool SidePanel::m_selection_enabled = false private
Referenced by EnableSelection(), PlanetClickedSlot(), PlanetSelectable(), RefreshImpl(), and SelectedPlanetID().
std::shared_ptr<GG::DynamicGraphic> SidePanel::m_star_graphic = nullptr private
Referenced by RefreshImpl().
std::shared_ptr<GG::TextControl> SidePanel::m_star_type_text = nullptr private
Referenced by CompleteConstruction(), DoLayout(), and RefreshImpl().
std::shared_ptr<SystemNameDropDownList> SidePanel::m_system_name = nullptr private
Referenced by CompleteConstruction(), DoLayout(), EnableOrderIssuing(), NextButtonClicked(), PrevButtonClicked(), RefreshSystemNames(), and SystemSelectionChangedSlot().
std::shared_ptr<MultiIconValueIndicator> SidePanel::m_system_resource_summary = nullptr private
Referenced by CompleteConstruction(), DoLayout(), InWindow(), RefreshImpl(), and UpdateImpl().
boost::signals2::signal< void(int)> SidePanel::PlanetDoubleClickedSignal static
emitted when a planet is left double clicked
Referenced by CompleteConstruction(), and MapWnd::CompleteConstruction().
boost::signals2::signal< void(int)> SidePanel::PlanetRightClickedSignal static
emitted when a planet is right clicked
Referenced by CompleteConstruction(), and MapWnd::CompleteConstruction().
boost::signals2::signal< void(int)> SidePanel::PlanetSelectedSignal static
emitted when a rotating planet in the side panel is clicked by the user
Referenced by BuildDesignatorWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), and SelectPlanet().
boost::signals2::signal< void()> SidePanel::ResourceCenterChangedSignal static
emitted when a planet's resourcecenter has changed, including when focus is changed
Referenced by MapWnd::CompleteConstruction(), and RefreshInPreRender().
std::map< int, boost::signals2::connection > SidePanel::s_fleet_state_change_signals static private
Referenced by FleetsInserted(), FleetsRemoved(), RefreshInPreRender(), and ~SidePanel().
bool SidePanel::s_needs_refresh = false static private
Referenced by CompleteConstruction(), PreRender(), and Refresh().
bool SidePanel::s_needs_update = false static private
Referenced by CompleteConstruction(), PreRender(), and Update().
int SidePanel::s_planet_id = INVALID_OBJECT_ID static private
The id of the currently-selected planet, or INVALID_OBJECT_ID if no planet is selected.
Referenced by PreRender(), SelectedPlanetID(), and SelectPlanet().
std::set< std::weak_ptr< SidePanel >, std::owner_less< std::weak_ptr< SidePanel > > > SidePanel::s_side_panels static private
Referenced by CompleteConstruction(), PreRender(), Refresh(), RefreshInPreRender(), SelectPlanet(), and Update().
std::set< boost::signals2::connection > SidePanel::s_system_connections static private
Referenced by RefreshInPreRender(), and ~SidePanel().
int SidePanel::s_system_id = INVALID_OBJECT_ID static private
Referenced by DoLayout(), PlanetSelectable(), RefreshImpl(), RefreshInPreRender(), RefreshSystemNames(), SetSystem(), and SystemID().
boost::signals2::signal< void(int)> SidePanel::SystemSelectedSignal static
emitted when something in the sidepanel wants to change the selected system, including the droplist or back/forward arrows
Referenced by BuildDesignatorWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), and SystemSelectionChangedSlot().
The documentation for this class was generated from the following files:
SidePanel.h
SidePanel.cpp