FreeOrion: Effect::Effect Class Reference
Effect::Effect Class Reference abstract
The base class for all Effects.
#include <Effect.h>
Public Member Functions
virtual ~Effect ()
virtual std::string Dump (unsigned short ntabs=0) const =0
virtual void Execute (const ScriptingContext &context) const =0
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual unsigned int GetCheckSum () const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
virtual void SetTopLevelContent (const std::string &content_name)=0
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
The base class for all Effects.
When an Effect is executed, the source object (the object to which the Effect or its containing EffectGroup is attached) and the target object are both required. Note that this means that ValueRefs contained within Effects can refer to values in either the source or target objects.
Constructor & Destructor Documentation
~Effect()
Effect::Effect::~Effect () virtual
Member Function Documentation
Dump()
virtual std::string Effect::Effect::Dump (unsigned short ntabs = 0) const pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, Effect::SetMeter, and Effect::NoOp.
Execute() [1/4]
virtual void Effect::Effect::Execute (const ScriptingContext & context) const pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, Effect::SetMeter, and Effect::NoOp.
Referenced by Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), and Effect::SetEmpireMeter::Execute().
Execute() [2/4]
void Effect::Effect::Execute (const ScriptingContext & context, const TargetSet & targets) const virtual
Reimplemented in Effect::Conditional, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
References ScriptingContext::effect_target, and Effect::EffectsGroup::Execute().
Execute() [3/4]
void Effect::Effect::Execute (const TargetsCauses & targets_causes, AccountingMap * accounting_map, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const
References Effect::EffectsGroup::Execute(), and Objects().
Execute() [4/4]
void Effect::Effect::Execute (const ScriptingContext & context, const TargetSet & targets, AccountingMap * accounting_map, const EffectCause & effect_cause, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const virtual
Reimplemented in Effect::Conditional, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
References Effect::EffectsGroup::Execute().
GetCheckSum()
unsigned int Effect::Effect::GetCheckSum () const virtual
Reimplemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, Effect::SetMeter, and Effect::NoOp.
References CheckSums::CheckSumCombine(), and TraceLogger.
IsAppearanceEffect()
virtual bool Effect::Effect::IsAppearanceEffect () const inline virtual
Reimplemented in Effect::Conditional, Effect::SetTexture, and Effect::SetOverlayTexture.
IsConditionalEffect()
virtual bool Effect::Effect::IsConditionalEffect () const inline virtual
Reimplemented in Effect::Conditional.
IsEmpireMeterEffect()
virtual bool Effect::Effect::IsEmpireMeterEffect () const inline virtual
Reimplemented in Effect::SetEmpireMeter.
IsMeterEffect()
virtual bool Effect::Effect::IsMeterEffect () const inline virtual
Reimplemented in Effect::Conditional, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
IsSitrepEffect()
virtual bool Effect::Effect::IsSitrepEffect () const inline virtual
Reimplemented in Effect::Conditional, and Effect::GenerateSitRepMessage.
serialize()
template<class Archive > void Effect::Effect::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
virtual void Effect::Effect::SetTopLevelContent (const std::string & content_name) pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, Effect::SetMeter, and Effect::NoOp.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this class was generated from the following files:
Effect.h
Effects.cpp
Effects.h