FreeOrion: BuildingType Class Reference
BuildingType Class Reference
A specification for a building of a certain type.
#include <Building.h>
Public Member Functions
Structors
BuildingType (const std::string &name, const std::string &description, CommonParams &common_params, CaptureResult capture_result, const std::string &icon)
~BuildingType ()
Accessors
const std::string & Name () const
returns the unique name for this type of building
const std::string & Description () const
returns a text description of this type of building
std::string Dump (unsigned short ntabs=0) const
returns a data file format representation of this object
bool ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
float ProductionCost (int empire_id, int location_id) const
returns the number of production points required to build this building at this location by this empire
float PerTurnCost (int empire_id, int location_id) const
returns the maximum number of production points per turn that can be spend on this building
int ProductionTime (int empire_id, int location_id) const
returns the number of turns required to build this building at this location by this empire
const ValueRef::ValueRef< double > * Cost () const
returns the ValueRef that determines ProductionCost()
const ValueRef::ValueRef< int > * Time () const
returns the ValueRef that determines ProductionTime()
bool Producible () const
returns whether this building type is producible by players and appears on the production screen
const CommonParams::ConsumptionMap< MeterType > & ProductionMeterConsumption () const
returns the unique name for this type of building
const CommonParams::ConsumptionMap< std::string > & ProductionSpecialConsumption () const
returns the unique name for this type of building
const std::set< std::string > & Tags () const
returns the unique name for this type of building
const Condition::Condition * Location () const
returns the condition that determines the locations where this building can be produced
const Condition::Condition * EnqueueLocation () const
Returns a condition that can be used by the UI to further filter (beyond the Location() requirement) where this building will be presented for enqueuing onto the production queue, to avoid clutter in the BuildDesignatorWnd.
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
Returns the EffectsGroups that encapsulate the effects that buildings ofi this type have when operational.
const std::string & Icon () const
returns the name of the grapic file for this building type
bool ProductionLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id can produce this building at the location with location_id
bool EnqueueLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id meets the requirements of the EnqueueLocation() UI filter method for this building at the location with location_id
CaptureResult GetCaptureResult (int from_empire_id, int to_empire_id, int location_id, bool as_production_item) const
returns CaptureResult for empire with ID to_empire_id capturing from empire with IDs from_empire_id the planet (or other UniverseObject) with id location_id on which this type of Building is located (if as_production_item is false) or which is the location of a Production Queue BuildItem for a building of this type (otherwise)
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Private Member Functions
void Init ()
Private Attributes
CaptureResult m_capture_result
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::unique_ptr< Condition::Condition > m_enqueue_location
std::string m_icon
std::unique_ptr< Condition::Condition > m_location
std::string m_name
bool m_producible
std::unique_ptr< ValueRef::ValueRef< double > > m_production_cost
CommonParams::ConsumptionMap< MeterType > m_production_meter_consumption
CommonParams::ConsumptionMap< std::string > m_production_special_consumption
std::unique_ptr< ValueRef::ValueRef< int > > m_production_time
std::set< std::string > m_tags
Detailed Description
A specification for a building of a certain type.
Each building type must have a unique name string, by which it can be looked up using GetBuildingType(...).
Constructor & Destructor Documentation
BuildingType()
BuildingType::BuildingType (const std::string & name, const std::string & description, CommonParams & common_params, CaptureResult capture_result, const std::string & icon)
References CommonParams::effects, Init(), m_effects, m_tags, and CommonParams::tags.
~BuildingType()
BuildingType::~BuildingType ()
Member Function Documentation
Cost()
const ValueRef::ValueRef<double>* BuildingType::Cost () const inline
returns the ValueRef that determines ProductionCost()
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
Description()
const std::string& BuildingType::Description () const inline
returns a text description of this type of building
References Effect::Dump().
Referenced by BuildingIndicator::BuildingIndicator(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), and FreeOrionPython::WrapUniverseClasses().
Dump()
std::string BuildingType::Dump (unsigned short ntabs = 0) const
returns a data file format representation of this object
References DumpIndent(), m_capture_result, m_description, m_effects, m_enqueue_location, m_icon, m_location, m_name, m_producible, m_production_cost, m_production_time, and m_tags.
Referenced by FreeOrionPython::WrapUniverseClasses().
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& BuildingType::Effects () const inline
Returns the EffectsGroups that encapsulate the effects that buildings ofi this type have when operational.
Referenced by Universe::GetEffectsAndTargets(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
EnqueueLocation() [1/2]
const Condition::Condition* BuildingType::EnqueueLocation () const inline
Returns a condition that can be used by the UI to further filter (beyond the Location() requirement) where this building will be presented for enqueuing onto the production queue, to avoid clutter in the BuildDesignatorWnd.
Example usage: Buildings that are already enqueued at a production location are hidden so they don't appear in the list of available items that can be enqueued/produced (again) at that location.
Referenced by anonymous_namespace{UniverseWrapper.cpp}::EnqueueLocationTest(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
EnqueueLocation() [2/2]
bool BuildingType::EnqueueLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id meets the requirements of the EnqueueLocation() UI filter method for this building at the location with location_id
References Empires(), ObjectMap::get(), EmpireManager::GetSource(), m_enqueue_location, and Objects().
GetCaptureResult()
CaptureResult BuildingType::GetCaptureResult (int from_empire_id, int to_empire_id, int location_id, bool as_production_item) const inline
returns CaptureResult for empire with ID to_empire_id capturing from empire with IDs from_empire_id the planet (or other UniverseObject) with id location_id on which this type of Building is located (if as_production_item is false) or which is the location of a Production Queue BuildItem for a building of this type (otherwise)
Referenced by Planet::Conquer(), Empire::ConquerProductionQueueItemsAtLocation(), and FreeOrionPython::WrapUniverseClasses().
GetCheckSum()
unsigned int BuildingType::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_capture_result, m_description, m_effects, m_enqueue_location, m_icon, m_location, m_name, m_producible, m_production_cost, m_production_meter_consumption, m_production_special_consumption, m_production_time, m_tags, and BuildingTypeManager::s_instance.
Icon()
const std::string& BuildingType::Icon () const inline
returns the name of the grapic file for this building type
Referenced by ClientUI::BuildingIcon().
Init()
void BuildingType::Init () private
References m_effects, m_enqueue_location, m_location, m_name, m_production_cost, and m_production_time.
Referenced by BuildingType().
Location()
const Condition::Condition* BuildingType::Location () const inline
returns the condition that determines the locations where this building can be produced
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
Name()
const std::string& BuildingType::Name () const inline
returns the unique name for this type of building
Referenced by Building::Building(), EncyclopediaDetailPanel::SetItem(), and FreeOrionPython::WrapUniverseClasses().
PerTurnCost()
float BuildingType::PerTurnCost (int empire_id, int location_id) const
returns the maximum number of production points per turn that can be spend on this building
References ProductionCost(), and ProductionTime().
Referenced by anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
Producible()
bool BuildingType::Producible () const inline
returns whether this building type is producible by players and appears on the production screen
Referenced by Empire::AddBuildingType(), and BuildDesignatorWnd::BuildSelector::BuildableItemVisible().
ProductionCost()
float BuildingType::ProductionCost (int empire_id, int location_id) const
returns the number of production points required to build this building at this location by this empire
References anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_COST, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_cost, and Objects().
Referenced by PerTurnCost(), Empire::ProductionCostAndTime(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), and FreeOrionPython::WrapUniverseClasses().
ProductionCostTimeLocationInvariant()
bool BuildingType::ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
References GetGameRules(), m_production_cost, and m_production_time.
Referenced by ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), and FreeOrionPython::WrapUniverseClasses().
ProductionLocation()
bool BuildingType::ProductionLocation (int empire_id, int location_id) const
returns true iff the empire with ID empire_id can produce this building at the location with location_id
References Empires(), ObjectMap::get(), EmpireManager::GetSource(), m_location, and Objects().
Referenced by anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), and FreeOrionPython::WrapUniverseClasses().
ProductionMeterConsumption()
const CommonParams::ConsumptionMap<MeterType>& BuildingType::ProductionMeterConsumption () const inline
returns the unique name for this type of building
ProductionSpecialConsumption()
const CommonParams::ConsumptionMap<std::string>& BuildingType::ProductionSpecialConsumption () const inline
returns the unique name for this type of building
ProductionTime()
int BuildingType::ProductionTime (int empire_id, int location_id) const
returns the number of turns required to build this building at this location by this empire
References anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_TURNS, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_time, and Objects().
Referenced by PerTurnCost(), Empire::ProductionCostAndTime(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), and FreeOrionPython::WrapUniverseClasses().
Tags()
const std::set<std::string>& BuildingType::Tags () const inline
returns the unique name for this type of building
Referenced by Building::HasTag(), and Building::Tags().
Time()
const ValueRef::ValueRef<int>* BuildingType::Time () const inline
returns the ValueRef that determines ProductionTime()
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
Member Data Documentation
m_capture_result
CaptureResult BuildingType::m_capture_result private
Referenced by Dump(), and GetCheckSum().
m_description
std::string BuildingType::m_description private
Referenced by Dump(), and GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > BuildingType::m_effects private
Referenced by BuildingType(), Dump(), GetCheckSum(), and Init().
m_enqueue_location
std::unique_ptr<Condition::Condition> BuildingType::m_enqueue_location private
Referenced by Dump(), EnqueueLocation(), GetCheckSum(), and Init().
m_icon
std::string BuildingType::m_icon private
Referenced by Dump(), and GetCheckSum().
m_location
std::unique_ptr<Condition::Condition> BuildingType::m_location private
Referenced by Dump(), GetCheckSum(), Init(), and ProductionLocation().
m_name
std::string BuildingType::m_name private
Referenced by Dump(), GetCheckSum(), and Init().
m_producible
bool BuildingType::m_producible private
Referenced by Dump(), and GetCheckSum().
m_production_cost
std::unique_ptr<ValueRef::ValueRef<double> > BuildingType::m_production_cost private
Referenced by Dump(), GetCheckSum(), Init(), ProductionCost(), and ProductionCostTimeLocationInvariant().
m_production_meter_consumption
CommonParams::ConsumptionMap<MeterType> BuildingType::m_production_meter_consumption private
Referenced by GetCheckSum().
m_production_special_consumption
CommonParams::ConsumptionMap<std::string> BuildingType::m_production_special_consumption private
Referenced by GetCheckSum().
m_production_time
std::unique_ptr<ValueRef::ValueRef<int> > BuildingType::m_production_time private
Referenced by Dump(), GetCheckSum(), Init(), ProductionCostTimeLocationInvariant(), and ProductionTime().
m_tags
std::set<std::string> BuildingType::m_tags private
Referenced by BuildingType(), Dump(), and GetCheckSum().
The documentation for this class was generated from the following files:
Building.h
Building.cpp