FreeOrion: FleetDataPanel Class Reference
FleetDataPanel Class Reference
Represents a single fleet.
Public Member Functions
FleetDataPanel (GG::X w, GG::Y h, int fleet_id)
FleetDataPanel (GG::X w, GG::Y h, int system_id, bool new_fleet_drop_target)
~FleetDataPanel ()
void AcceptDrops (const GG::Pt &pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
void CheckDrops (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
GG::Pt ClientLowerRight () const override
Lower right minus border insets.
GG::Pt ClientUpperLeft () const override
Upper left plus border insets.
void DragDropHere (const GG::Pt &pt, std::map< const Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
void DragDropLeave () override
NewFleetAggression GetNewFleetAggression () const
void PreRender () override
void Render () override
void RequireRefresh ()
Indicate fleet data has changed and needs refresh.
void Select (bool b)
bool Selected () const
void SetSystemID (int id)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
boost::signals2::signal< void(const std::vector< int > &)> NewFleetFromShipsSignal
Protected Member Functions
void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const override
bool EventFilter (GG::Wnd *w, const GG::WndEvent &event) override
Private Member Functions
void ColorTextForSelect ()
void DoLayout ()
void Init ()
void Refresh ()
void RefreshStateChangedSignals ()
void SetStatIconValues ()
void ToggleAggression ()
void UpdateAggressionToggle ()
Private Attributes
std::shared_ptr< GG::Button > m_aggression_toggle = nullptr
boost::signals2::connection m_fleet_connection
std::shared_ptr< GG::Label > m_fleet_destination_text = nullptr
std::shared_ptr< GG::Control > m_fleet_icon = nullptr
std::vector< std::shared_ptr< GG::StaticGraphic > > m_fleet_icon_overlays
const int m_fleet_id = INVALID_OBJECT_ID
std::shared_ptr< GG::Label > m_fleet_name_text = nullptr
bool m_initialized = false
const bool m_is_new_fleet_drop_target = false
bool m_needs_refresh = true
NewFleetAggression m_new_fleet_aggression = FLEET_PASSIVE
std::shared_ptr< ScanlineControl > m_scanline_control = nullptr
bool m_selected = false
std::vector< boost::signals2::connection > m_ship_connections
std::vector< std::pair< MeterType, std::shared_ptr< StatisticIcon > > > m_stat_icons
int m_system_id = INVALID_OBJECT_ID
Detailed Description
Represents a single fleet.
This class is used as the drop-target in FleetWnd or as the sole Control in each FleetRow.
Constructor & Destructor Documentation
FleetDataPanel() [1/2]
FleetDataPanel::FleetDataPanel (GG::X w, GG::Y h, int fleet_id)
References RequireRefresh().
FleetDataPanel() [2/2]
FleetDataPanel::FleetDataPanel (GG::X w, GG::Y h, int system_id, bool new_fleet_drop_target)
~FleetDataPanel()
FleetDataPanel::~FleetDataPanel ()
Member Function Documentation
AcceptDrops()
void FleetDataPanel::AcceptDrops (const GG::Pt & pt, std::vector< std::shared_ptr< GG::Wnd >> wnds, GG::Flags< GG::ModKey > mod_keys) override
References DebugLogger, m_is_new_fleet_drop_target, NewFleetFromShipsSignal, and to_string().
CheckDrops()
void FleetDataPanel::CheckDrops (const GG::Pt & pt, std::map< const Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
References m_is_new_fleet_drop_target.
ClientLowerRight()
GG::Pt FleetDataPanel::ClientLowerRight () const override
Lower right minus border insets.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
ClientUpperLeft()
GG::Pt FleetDataPanel::ClientUpperLeft () const override
Upper left plus border insets.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
Referenced by Render().
ColorTextForSelect()
void FleetDataPanel::ColorTextForSelect () private
References m_fleet_destination_text, m_fleet_name_text, m_selected, and ClientUI::TextColor().
Referenced by Init(), and Select().
DoLayout()
void FleetDataPanel::DoLayout () private
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_TEXT_PAD, anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_aggression_toggle, m_fleet_destination_text, m_fleet_icon, m_fleet_icon_overlays, m_fleet_name_text, m_scanline_control, m_stat_icons, and anonymous_namespace{FleetWnd.cpp}::StatIconSize().
Referenced by PreRender(), and SizeMove().
DragDropHere()
void FleetDataPanel::DragDropHere (const GG::Pt & pt, std::map< const Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) override
References DropsAcceptable(), m_is_new_fleet_drop_target, and Select().
DragDropLeave()
void FleetDataPanel::DragDropLeave () override
References Select().
DropsAcceptable()
void FleetDataPanel::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const override protected
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetFleet(), GetShip(), INVALID_OBJECT_ID, m_fleet_id, m_is_new_fleet_drop_target, m_system_id, and anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING.
Referenced by DragDropHere(), and FleetsListBox::DragDropHere().
EventFilter()
bool FleetDataPanel::EventFilter (GG::Wnd * w, const GG::WndEvent & event) override protected
References ErrorLogger, FlexibleFormat(), ClientUI::GetClientUI(), INVALID_METER_TYPE, m_stat_icons, UserString(), UserStringExists(), and ClientUI::ZoomToMeterTypeArticle().
GetNewFleetAggression()
NewFleetAggression FleetDataPanel::GetNewFleetAggression () const
References m_new_fleet_aggression.
Init()
void FleetDataPanel::Init () private
References anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), ColorTextForSelect(), anonymous_namespace{FleetWnd.cpp}::DamageIcon(), ClientApp::EmpireID(), anonymous_namespace{FleetWnd.cpp}::FightersIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveMouseoverIcon(), anonymous_namespace{FleetWnd.cpp}::FleetCountIcon(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveIcon(), OptionsDB::Get(), HumanClientApp::GetApp(), GetFleet(), GetOptionsDB(), anonymous_namespace{FleetWnd.cpp}::IndustryIcon(), INVALID_OBJECT_ID, m_aggression_toggle, m_fleet_destination_text, m_fleet_id, m_fleet_name_text, m_initialized, m_stat_icons, METER_CAPACITY, METER_FUEL, METER_INDUSTRY, METER_POPULATION, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STRUCTURE, METER_TRADE, METER_TROOPS, ClientUI::MeterIcon(), anonymous_namespace{FleetWnd.cpp}::ResearchIcon(), anonymous_namespace{FleetWnd.cpp}::StatIconSize(), ToggleAggression(), anonymous_namespace{FleetWnd.cpp}::TradeIcon(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), and UserString().
Referenced by PreRender().
PreRender()
void FleetDataPanel::PreRender () override
References DoLayout(), Init(), m_initialized, m_needs_refresh, and Refresh().
Refresh()
void FleetDataPanel::Refresh () private
References ALL_EMPIRES, ClientUI::ArtDir(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconStyle(), ClientApp::EmpireID(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetHeadIcons(), FleetSizeIcon(), FlexibleFormat(), OptionsDB::Get(), HumanClientApp::GetApp(), GetEmpire(), GetFleet(), GetOptionsDB(), ClientUI::GetTexture(), INVALID_OBJECT_ID, FleetButton::LARGE, m_fleet_destination_text, m_fleet_icon, m_fleet_icon_overlays, m_fleet_id, m_fleet_name_text, m_is_new_fleet_drop_target, m_needs_refresh, m_scanline_control, Empire::Name(), ObjectMap::Object(), Objects(), RefreshStateChangedSignals(), SetStatIconValues(), to_string(), UpdateAggressionToggle(), UserString(), and WarnLogger.
Referenced by ShipsListBox::CompleteConstruction(), PreRender(), and ShipsListBox::SetFleet().
RefreshStateChangedSignals()
void FleetDataPanel::RefreshStateChangedSignals () private
References GetFleet(), m_fleet_connection, m_fleet_id, m_ship_connections, Objects(), and RequireRefresh().
Referenced by Refresh().
Render()
void FleetDataPanel::Render () override
References ClientUpperLeft(), anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER, anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_selected, ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
RequireRefresh()
void FleetDataPanel::RequireRefresh ()
Indicate fleet data has changed and needs refresh.
References m_needs_refresh.
Referenced by FleetDataPanel(), and RefreshStateChangedSignals().
Select()
void FleetDataPanel::Select (bool b)
References ColorTextForSelect(), and m_selected.
Referenced by FleetsListBox::ClearHighlighting(), DragDropHere(), DragDropLeave(), and FleetsListBox::HighlightRow().
Selected()
bool FleetDataPanel::Selected () const
References m_selected.
Referenced by FleetsListBox::ClearHighlighting(), FleetsListBox::DragDropHere(), and FleetsListBox::HighlightRow().
SetStatIconValues()
void FleetDataPanel::SetStatIconValues () private
References ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), GetFleet(), GetUniverse(), m_fleet_id, m_stat_icons, METER_CAPACITY, METER_FUEL, METER_INDUSTRY, METER_POPULATION, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STRUCTURE, METER_TRADE, METER_TROOPS, and Objects().
Referenced by Refresh().
SetSystemID()
void FleetDataPanel::SetSystemID (int id)
References m_system_id.
SizeMove()
void FleetDataPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
ToggleAggression()
void FleetDataPanel::ToggleAggression () private
References ALL_EMPIRES, anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetFleet(), OrderSet::IssueOrder(), m_aggression_toggle, m_fleet_id, m_is_new_fleet_drop_target, m_new_fleet_aggression, ClientApp::Orders(), anonymous_namespace{FleetWnd.cpp}::SetNewFleetAggressiveOptionSetting(), and UpdateAggressionToggle().
Referenced by Init().
UpdateAggressionToggle()
void FleetDataPanel::UpdateAggressionToggle () private
References anonymous_namespace{FleetWnd.cpp}::FleetAggressiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAggressiveMouseoverIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoIcon(), anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveIcon(), anonymous_namespace{FleetWnd.cpp}::FleetPassiveMouseoverIcon(), OptionsDB::Get(), GetFleet(), GetOptionsDB(), m_aggression_toggle, m_fleet_id, m_is_new_fleet_drop_target, m_new_fleet_aggression, and UserString().
Referenced by Refresh(), and ToggleAggression().
Member Data Documentation
m_aggression_toggle
std::shared_ptr<GG::Button> FleetDataPanel::m_aggression_toggle = nullptr private
Referenced by DoLayout(), Init(), ToggleAggression(), and UpdateAggressionToggle().
m_fleet_connection
boost::signals2::connection FleetDataPanel::m_fleet_connection private
Referenced by RefreshStateChangedSignals().
m_fleet_destination_text
std::shared_ptr<GG::Label> FleetDataPanel::m_fleet_destination_text = nullptr private
Referenced by ColorTextForSelect(), DoLayout(), Init(), and Refresh().
m_fleet_icon
std::shared_ptr<GG::Control> FleetDataPanel::m_fleet_icon = nullptr private
Referenced by DoLayout(), and Refresh().
m_fleet_icon_overlays
std::vector<std::shared_ptr<GG::StaticGraphic> > FleetDataPanel::m_fleet_icon_overlays private
Referenced by DoLayout(), and Refresh().
m_fleet_id
const int FleetDataPanel::m_fleet_id = INVALID_OBJECT_ID private
Referenced by ShipsListBox::AcceptDrops(), anonymous_namespace{FleetWnd.cpp}::FleetRow::CompleteConstruction(), DropsAcceptable(), anonymous_namespace{FleetWnd.cpp}::FleetRow::FleetID(), Init(), Refresh(), ShipsListBox::Refresh(), RefreshStateChangedSignals(), ShipsListBox::SetFleet(), SetStatIconValues(), ToggleAggression(), and UpdateAggressionToggle().
m_fleet_name_text
std::shared_ptr<GG::Label> FleetDataPanel::m_fleet_name_text = nullptr private
Referenced by ColorTextForSelect(), DoLayout(), Init(), and Refresh().
m_initialized
bool FleetDataPanel::m_initialized = false private
Referenced by Init(), and PreRender().
m_is_new_fleet_drop_target
const bool FleetDataPanel::m_is_new_fleet_drop_target = false private
Referenced by AcceptDrops(), CheckDrops(), DragDropHere(), DropsAcceptable(), Refresh(), ToggleAggression(), and UpdateAggressionToggle().
m_needs_refresh
bool FleetDataPanel::m_needs_refresh = true private
Referenced by PreRender(), Refresh(), and RequireRefresh().
m_new_fleet_aggression
NewFleetAggression FleetDataPanel::m_new_fleet_aggression = FLEET_PASSIVE private
Referenced by GetNewFleetAggression(), ToggleAggression(), and UpdateAggressionToggle().
m_scanline_control
std::shared_ptr<ScanlineControl> FleetDataPanel::m_scanline_control = nullptr private
Referenced by DoLayout(), and Refresh().
m_selected
bool FleetDataPanel::m_selected = false private
Referenced by ColorTextForSelect(), Render(), Select(), and Selected().
m_ship_connections
std::vector<boost::signals2::connection> FleetDataPanel::m_ship_connections private
Referenced by RefreshStateChangedSignals().
m_stat_icons
std::vector<std::pair<MeterType, std::shared_ptr<StatisticIcon> > > FleetDataPanel::m_stat_icons private
Referenced by DoLayout(), EventFilter(), Init(), and SetStatIconValues().
m_system_id
int FleetDataPanel::m_system_id = INVALID_OBJECT_ID private
Referenced by DropsAcceptable(), and SetSystemID().
NewFleetFromShipsSignal
boost::signals2::signal<void (const std::vector<int>&)> FleetDataPanel::NewFleetFromShipsSignal mutable
Referenced by AcceptDrops().
The documentation for this class was generated from the following file:
FleetWnd.cpp