FreeOrion: OptionsWnd::SoundOptionsFeedback Class Reference
OptionsWnd::SoundOptionsFeedback Class Reference
SoundOptionsFeedback enables immediate player feedback when sound options are changed.
Public Member Functions
SoundOptionsFeedback ()
void MusicClicked (bool checked)
Enables/disables background music when the music check box is clicked.
void MusicVolumeSlid (int value) const
Adjusts the music volume.
void SetEffectsButton (std::shared_ptr< GG::StateButton > button)
Stores a pointer to the sound effects check box.
void SetMusicButton (std::shared_ptr< GG::StateButton > button)
Stores pointer to music enable check box.
void SoundEffectsEnableClicked (bool checked)
Enables/disables sound effects when the sound effects check box is clicked.
void SoundInitializationFailure (Sound::InitializationFailureException const &e)
Handles a sound initialization failure by setting sound effects and music enable check boxes to disabled and informing the player with a popup message box.
void UISoundsVolumeSlid (int value) const
Adjusts the effects volume.
Private Attributes
std::shared_ptr< GG::StateButton > m_effects_button
std::shared_ptr< GG::StateButton > m_music_button
Detailed Description
SoundOptionsFeedback enables immediate player feedback when sound options are changed.
Constructor & Destructor Documentation
SoundOptionsFeedback()
OptionsWnd::SoundOptionsFeedback::SoundOptionsFeedback () inline
References MusicClicked(), MusicVolumeSlid(), SetEffectsButton(), SetMusicButton(), SoundEffectsEnableClicked(), SoundInitializationFailure(), and UISoundsVolumeSlid().
Member Function Documentation
MusicClicked()
void OptionsWnd::SoundOptionsFeedback::MusicClicked (bool checked)
Enables/disables background music when the music check box is clicked.
References Sound::Disable(), Sound::Enable(), GetOptionsDB(), Sound::GetSound(), Sound::PlayMusic(), OptionsDB::Set(), and Sound::StopMusic().
Referenced by OptionsWnd::MusicVolumeOption(), and SoundOptionsFeedback().
MusicVolumeSlid()
void OptionsWnd::SoundOptionsFeedback::MusicVolumeSlid (int value) const
Adjusts the music volume.
References GetOptionsDB(), Sound::GetSound(), OptionsDB::Set(), and Sound::SetMusicVolume().
Referenced by OptionsWnd::MusicVolumeOption(), and SoundOptionsFeedback().
SetEffectsButton()
void OptionsWnd::SoundOptionsFeedback::SetEffectsButton (std::shared_ptr< GG::StateButton > button)
Stores a pointer to the sound effects check box.
Referenced by SoundOptionsFeedback(), and OptionsWnd::VolumeOption().
SetMusicButton()
void OptionsWnd::SoundOptionsFeedback::SetMusicButton (std::shared_ptr< GG::StateButton > button)
Stores pointer to music enable check box.
Referenced by OptionsWnd::MusicVolumeOption(), and SoundOptionsFeedback().
SoundEffectsEnableClicked()
void OptionsWnd::SoundOptionsFeedback::SoundEffectsEnableClicked (bool checked)
Enables/disables sound effects when the sound effects check box is clicked.
References Sound::Disable(), Sound::Enable(), GetOptionsDB(), Sound::GetSound(), Sound::PlaySound(), and OptionsDB::Set().
Referenced by SoundOptionsFeedback(), and OptionsWnd::VolumeOption().
SoundInitializationFailure()
void OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure (Sound::InitializationFailureException const & e)
Handles a sound initialization failure by setting sound effects and music enable check boxes to disabled and informing the player with a popup message box.
References GetOptionsDB(), ClientUI::MessageBox(), OptionsDB::Set(), and UserString().
Referenced by SoundOptionsFeedback().
UISoundsVolumeSlid()
void OptionsWnd::SoundOptionsFeedback::UISoundsVolumeSlid (int value) const
Adjusts the effects volume.
References GetOptionsDB(), Sound::GetSound(), Sound::PlaySound(), OptionsDB::Set(), and Sound::SetUISoundsVolume().
Referenced by SoundOptionsFeedback(), and OptionsWnd::VolumeOption().
Member Data Documentation
m_effects_button
std::shared_ptr<GG::StateButton> OptionsWnd::SoundOptionsFeedback::m_effects_button private
m_music_button
std::shared_ptr<GG::StateButton> OptionsWnd::SoundOptionsFeedback::m_music_button private
The documentation for this class was generated from the following files:
OptionsWnd.h
OptionsWnd.cpp