FreeOrion: PythonBase Class Reference
PythonBase Class Reference abstract
#include <CommonFramework.h>
Public Member Functions
PythonBase ()
virtual ~PythonBase ()
void AddToSysPath (const std::string dir)
std::vector< std::string > ErrorReport ()
void HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
bool Initialize ()
virtual bool InitImports ()=0
virtual bool InitModules ()=0
bool IsPythonRunning ()
IsPythonRunning returns true is the python interpreter is initialized.
void SetCurrentDir (const std::string dir)
void SetErrorModule (boost::python::object &module)
Private Member Functions
void Finalize ()
Private Attributes
boost::optional< boost::python::dict > m_namespace
boost::python::object * m_python_module_error = nullptr
boost::python::object m_system_exit
Constructor & Destructor Documentation
PythonBase()
PythonBase::PythonBase ()
~PythonBase()
PythonBase::~PythonBase () virtual
References Finalize().
Member Function Documentation
AddToSysPath()
void PythonBase::AddToSysPath (const std::string dir)
References ErrorLogger, exec, and m_namespace.
Referenced by Initialize().
ErrorReport()
std::vector< std::string > PythonBase::ErrorReport ()
References ErrorLogger, HandleErrorAlreadySet(), and m_python_module_error.
Finalize()
void PythonBase::Finalize () private
References DebugLogger, ErrorLogger, m_namespace, m_python_module_error, and m_system_exit.
Referenced by HandleErrorAlreadySet(), and ~PythonBase().
HandleErrorAlreadySet()
void PythonBase::HandleErrorAlreadySet ()
Handles boost::python::error_already_set.
If the error is SystemExit the python interpreter is finalized and no longer available.
Call PyErr_Print() if the exception is an error.
HandleErrorAlreadySet is idempotent, calling it multiple times won't crash or hang the process.
References ErrorLogger, Finalize(), and m_system_exit.
Referenced by ErrorReport(), ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), PythonAI::GenerateOrders(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), Initialize(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
Initialize()
bool PythonBase::Initialize ()
References AddToSysPath(), DebugLogger, ErrorLogger, GetPythonCommonDir(), HandleErrorAlreadySet(), InitImports(), InitModules(), m_namespace, and m_system_exit.
Referenced by ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), ServerApp::GetPlayerDelegation(), PythonAI::Initialize(), ServerApp::InitializePython(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
InitImports()
virtual bool PythonBase::InitImports () pure virtual
Implemented in PythonAI, and PythonServer.
Referenced by Initialize().
InitModules()
virtual bool PythonBase::InitModules () pure virtual
Implemented in PythonAI, and PythonServer.
Referenced by Initialize().
IsPythonRunning()
bool PythonBase::IsPythonRunning ()
IsPythonRunning returns true is the python interpreter is initialized.
It is typically called after HandleErrorAlreadySet() to determine if the error caused the interpreter to shutdown.
Referenced by ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), PythonAI::GenerateOrders(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), ServerApp::InitializePython(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), ServerApp::PushChatMessage(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
SetCurrentDir()
void PythonBase::SetCurrentDir (const std::string dir)
References ErrorLogger, exec, and m_namespace.
Referenced by ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
SetErrorModule()
void PythonBase::SetErrorModule (boost::python::object & module)
References m_python_module_error.
Member Data Documentation
m_namespace
boost::optional<boost::python::dict> PythonBase::m_namespace private
Referenced by AddToSysPath(), Finalize(), Initialize(), and SetCurrentDir().
m_python_module_error
boost::python::object* PythonBase::m_python_module_error = nullptr private
Referenced by ErrorReport(), Finalize(), and SetErrorModule().
m_system_exit
boost::python::object PythonBase::m_system_exit private
Referenced by Finalize(), HandleErrorAlreadySet(), and Initialize().
The documentation for this class was generated from the following files:
CommonFramework.h
CommonFramework.cpp