FreeOrion: Order Class Reference
Order Class Reference abstract
The abstract base class for serializable player actions.
#include <Order.h>
Public Member Functions
Order ()
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
virtual std::string Dump () const
int EmpireID () const
Returns the ID of the Empire issuing the order.
void Execute () const
Executes the order on the Universe and Empires.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Protected Member Functions
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Private Member Functions
virtual void ExecuteImpl () const =0
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
virtual bool UndoImpl () const
Private Attributes
int m_empire = ALL_EMPIRES
bool m_executed = false
Indicates that Execute() has occured, and so an undo is legal.
Friends
class boost::serialization::access
Detailed Description
The abstract base class for serializable player actions.
Orders are generally executed on the client side as soon as they are issued. Those that define UndoImpl() may also be undone on the client side. Subclass- defined UndoImpl() must return true, indicating that the call had some effect; the default implementation does nothing and returns false. Note that only some Order subclasses define UndoImpl(), specifically those that need to be undone before another order of a similar type can be issued. For example, ColonizeOrder needs to be undoable; otherwise, once the user clicks the colonize button, she is locked in to this decision.
Constructor & Destructor Documentation
Order() [1/2]
Order::Order () inline
Order() [2/2]
Order::Order (int empire) inline
ctor taking the ID of the Empire issuing the order.
~Order()
virtual Order::~Order () inline virtual
Member Function Documentation
Dump()
virtual std::string Order::Dump () const inline virtual
Reimplemented in ForgetOrder, GiveObjectToEmpireOrder, AggressiveOrder, ScrapOrder, ShipDesignOrder, ProductionQueueOrder, ResearchQueueOrder, PolicyOrder, ChangeFocusOrder, BombardOrder, InvadeOrder, ColonizeOrder, FleetTransferOrder, FleetMoveOrder, NewFleetOrder, and RenameOrder.
EmpireID()
int Order::EmpireID () const inline
Returns the ID of the Empire issuing the order.
Referenced by RenameOrder::ExecuteImpl(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), ChangeFocusOrder::ExecuteImpl(), ShipDesignOrder::ExecuteImpl(), ScrapOrder::ExecuteImpl(), AggressiveOrder::ExecuteImpl(), GiveObjectToEmpireOrder::ExecuteImpl(), ForgetOrder::ExecuteImpl(), FleetMoveOrder::FleetMoveOrder(), GetValidatedEmpire(), ScrapOrder::UndoImpl(), GiveObjectToEmpireOrder::UndoImpl(), and FreeOrionPython::WrapAI().
Execute()
void Order::Execute () const
Executes the order on the Universe and Empires.
Preconditions of Execute(): For all order subclasses, the empire ID for the order must be that of an existing empire.
The order has not already been executed.
Subclasses add additional preconditions. An std::runtime_error should be thrown if any precondition fails.
References ExecuteImpl(), and m_executed.
Executed()
bool Order::Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
References m_executed.
Referenced by anonymous_namespace{Order.cpp}::ExecutedTag(), and FreeOrionPython::WrapAI().
ExecuteImpl()
virtual void Order::ExecuteImpl () const private pure virtual
Implemented in ForgetOrder, GiveObjectToEmpireOrder, AggressiveOrder, ScrapOrder, ShipDesignOrder, ProductionQueueOrder, ResearchQueueOrder, PolicyOrder, ChangeFocusOrder, BombardOrder, InvadeOrder, ColonizeOrder, FleetTransferOrder, FleetMoveOrder, NewFleetOrder, and RenameOrder.
Referenced by NewFleetOrder::Aggressive(), Execute(), RenameOrder::Name(), ChangeFocusOrder::PlanetID(), FleetMoveOrder::Route(), ColonizeOrder::ShipID(), InvadeOrder::ShipID(), BombardOrder::ShipID(), FleetTransferOrder::Ships(), and PolicyOrder::Slot().
GetValidatedEmpire()
Empire * Order::GetValidatedEmpire () const protected
Verifies that the empire ID in this order is valid and return the Empire pointer.
Throws an std::runtime_error if not valid.
References EmpireID(), and GetEmpire().
Referenced by RenameOrder::ExecuteImpl(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), ChangeFocusOrder::ExecuteImpl(), PolicyOrder::ExecuteImpl(), ResearchQueueOrder::ExecuteImpl(), ProductionQueueOrder::ExecuteImpl(), ShipDesignOrder::ExecuteImpl(), ScrapOrder::ExecuteImpl(), AggressiveOrder::ExecuteImpl(), GiveObjectToEmpireOrder::ExecuteImpl(), ForgetOrder::ExecuteImpl(), ScrapOrder::UndoImpl(), and GiveObjectToEmpireOrder::UndoImpl().
serialize()
template<typename Archive > void Order::serialize (Archive & ar, const unsigned int version) private
Undo()
bool Order::Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
If an order is undone on the client and then still sent to the server it will be executed on the server, which is probably not desired.
References m_executed, and UndoImpl().
UndoImpl()
bool Order::UndoImpl () const private virtual
Reimplemented in GiveObjectToEmpireOrder, ScrapOrder, BombardOrder, InvadeOrder, and ColonizeOrder.
Referenced by ColonizeOrder::ShipID(), InvadeOrder::ShipID(), BombardOrder::ShipID(), and Undo().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_empire
int Order::m_empire = ALL_EMPIRES private
m_executed
bool Order::m_executed = false mutable private
Indicates that Execute() has occured, and so an undo is legal.
Referenced by Execute(), Executed(), and Undo().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp