FreeOrion: ResearchQueueOrder Class Reference
ResearchQueueOrder Class Reference
#include <Order.h>
Public Member Functions
Structors
ResearchQueueOrder ()
ResearchQueueOrder (int empire, const std::string &tech_name)
ResearchQueueOrder (int empire, const std::string &tech_name, int position)
ResearchQueueOrder (int empire, const std::string &tech_name, bool pause, float dummy)
Public Member Functions inherited from Order
void Execute () const
bool Undo () const
Order ()
Order (int empire)
virtual ~Order ()
int EmpireID () const
Private Member Functions
void ExecuteImpl () const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_pause
int m_position
bool m_remove
std::string m_tech_name
Static Private Attributes
static const int INVALID_INDEX = -500
static const int INVALID_PAUSE_RESUME = -1
static const int PAUSE = 1
static const int RESUME = 2
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
void ValidateEmpireID () const
bool Executed () const
Detailed Description
The Order subclass that represents changing an empire's research queue. The 2-arg ctor removes the named tech from empire's queue, whereas the 3-arg ctor places tech_name at position position in empire's research queue.
Constructor & Destructor Documentation
ResearchQueueOrder::ResearchQueueOrder ()
ResearchQueueOrder::ResearchQueueOrder (int empire, const std::string & tech_name)
ResearchQueueOrder::ResearchQueueOrder (int empire, const std::string & tech_name, int position)
ResearchQueueOrder::ResearchQueueOrder (int empire, const std::string & tech_name, bool pause, float dummy)
Member Function Documentation
void ResearchQueueOrder::ExecuteImpl () const override private virtual
Implements Order.
References DebugLogger, Order::EmpireID(), ErrorLogger, GetEmpire(), INVALID_INDEX, m_pause, m_position, m_remove, m_tech_name, PAUSE, Empire::PauseResearch(), Empire::PlaceTechInQueue(), Empire::RemoveTechFromQueue(), RESUME, Empire::ResumeResearch(), and Order::ValidateEmpireID().
template<class Archive > void ResearchQueueOrder::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
const int ResearchQueueOrder::INVALID_INDEX = -500 static private
Referenced by ExecuteImpl().
const int ResearchQueueOrder::INVALID_PAUSE_RESUME = -1 static private
int ResearchQueueOrder::m_pause private
Referenced by ExecuteImpl().
int ResearchQueueOrder::m_position private
Referenced by ExecuteImpl().
bool ResearchQueueOrder::m_remove private
Referenced by ExecuteImpl().
std::string ResearchQueueOrder::m_tech_name private
Referenced by ExecuteImpl().
const int ResearchQueueOrder::PAUSE = 1 static private
Referenced by ExecuteImpl().
const int ResearchQueueOrder::RESUME = 2 static private
Referenced by ExecuteImpl().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp