FreeOrion: FPSIndicator Class Reference
FPSIndicator Class Reference
Displays current rendering frames per second.
#include <CUIControls.h>
Public Member Functions
FPSIndicator ()
void PreRender () override
void Render () override
Private Member Functions
void UpdateEnabled ()
Private Attributes
int m_displayed_FPS = 0
bool m_enabled = false
Detailed Description
Displays current rendering frames per second.
Constructor & Destructor Documentation
FPSIndicator()
FPSIndicator::FPSIndicator ()
References GetOptionsDB(), OptionsDB::OptionChangedSignal(), and UpdateEnabled().
Member Function Documentation
PreRender()
void FPSIndicator::PreRender () override
References FlexibleFormat(), m_displayed_FPS, m_enabled, and UserString().
Render()
void FPSIndicator::Render () override
References m_displayed_FPS, m_enabled, and to_string().
UpdateEnabled()
void FPSIndicator::UpdateEnabled () private
References OptionsDB::Get(), GetOptionsDB(), and m_enabled.
Referenced by FPSIndicator().
Member Data Documentation
m_displayed_FPS
int FPSIndicator::m_displayed_FPS = 0 private
Referenced by PreRender(), and Render().
m_enabled
bool FPSIndicator::m_enabled = false private
Referenced by PreRender(), Render(), and UpdateEnabled().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp