FreeOrion: HullType Class Reference
HullType Class Reference
Specification for the hull, or base, on which ship designs are created by adding parts.
#include <ShipPartHull.h>
Classes
struct Slot
Public Member Functions
Structors
HullType ()
HullType (const HullTypeStats &stats, CommonParams &&common_params, const MoreCommonParams &more_common_params, const std::vector< Slot > &slots, const std::string &icon, const std::string &graphic)
~HullType ()
Accessors
const std::string & Name () const
returns name of hull
const std::string & Description () const
returns description, including a description of the stats and effects of this hull
float Speed () const
returns starlane speed of hull
float Fuel () const
returns fuel capacity of hull
float Stealth () const
returns stealth of hull
float Structure () const
returns structure of hull
float Shields () const
returns shields of hull
float ColonyCapacity () const
returns colonist capacity of hull
float TroopCapacity () const
returns the troop capacity of hull
float Detection () const
returns detection ability of hull
bool ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
float ProductionCost (int empire_id, int location_id, int in_design_id=INVALID_DESIGN_ID) const
returns the number of production points required to produce this hull
int ProductionTime (int empire_id, int location_id, int in_design_id=INVALID_DESIGN_ID) const
returns the number of turns required to produce this hull
bool Producible () const
returns whether this hull type is producible by players and appears on the design screen
const ConsumptionMap< MeterType > & ProductionMeterConsumption () const
returns name of hull
const ConsumptionMap< std::string > & ProductionSpecialConsumption () const
returns name of hull
unsigned int NumSlots () const
returns total number of of slots in hull
unsigned int NumSlots (ShipSlotType slot_type) const
returns number of of slots of indicated type in hull
const std::vector< Slot > & Slots () const
returns vector of slots in hull
const std::set< std::string > & Tags () const
returns name of hull
bool HasTag (const std::string &tag) const
returns name of hull
const Condition::Condition * Location () const
returns the condition that determines the locations where ShipDesign containing hull can be produced
const std::set< std::string > & Exclusions () const
returns the names of other content that cannot be used in the same ship design as this part
const std::vector< std::shared_ptr< Effect::EffectsGroup > > & Effects () const
Returns the EffectsGroups that encapsulate the effects this part hull has.
const std::string & Graphic () const
returns the image that represents the hull on the design screen
const std::string & Icon () const
returns the small icon to represent hull
unsigned int GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Private Member Functions
void Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> &&effects, const HullTypeStats &stats)
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_description
std::vector< std::shared_ptr< Effect::EffectsGroup > > m_effects
std::set< std::string > m_exclusions
float m_fuel = 0.0f
std::string m_graphic
std::string m_icon
std::unique_ptr< Condition::Condition > m_location
std::string m_name
bool m_producible = false
std::unique_ptr< ValueRef::ValueRef< double > > m_production_cost
ConsumptionMap< MeterType > m_production_meter_consumption
ConsumptionMap< std::string > m_production_special_consumption
std::unique_ptr< ValueRef::ValueRef< int > > m_production_time
std::vector< Slot > m_slots
float m_speed = 1.0f
float m_stealth = 0.0f
float m_structure = 0.0f
std::set< std::string > m_tags
Friends
class boost::serialization::access
Detailed Description
Specification for the hull, or base, on which ship designs are created by adding parts.
The hull determines some final design characteristics directly, and also determine how many parts can be added to the design.
Constructor & Destructor Documentation
HullType() [1/2]
HullType::HullType ()
HullType() [2/2]
HullType::HullType (const HullTypeStats & stats, CommonParams && common_params, const MoreCommonParams & more_common_params, const std::vector< Slot > & slots, const std::string & icon, const std::string & graphic)
References Init(), m_name, m_producible, m_tags, and TraceLogger.
~HullType()
HullType::~HullType ()
Member Function Documentation
ColonyCapacity()
float HullType::ColonyCapacity () const inline
returns colonist capacity of hull
Referenced by ShipDesign::BuildStatCaches().
Description()
const std::string& HullType::Description () const inline
returns description, including a description of the stats and effects of this hull
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Detection()
float HullType::Detection () const inline
returns detection ability of hull
References INVALID_DESIGN_ID.
Referenced by ShipDesign::BuildStatCaches().
Effects()
const std::vector<std::shared_ptr<Effect::EffectsGroup> >& HullType::Effects () const inline
Returns the EffectsGroups that encapsulate the effects this part hull has.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Exclusions()
const std::set<std::string>& HullType::Exclusions () const inline
returns the names of other content that cannot be used in the same ship design as this part
Referenced by DesignWnd::MainPanel::DesignChanged(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Fuel()
float HullType::Fuel () const inline
returns fuel capacity of hull
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
GetCheckSum()
unsigned int HullType::GetCheckSum () const
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), m_description, m_effects, m_exclusions, m_fuel, m_graphic, m_icon, m_location, m_name, m_producible, m_production_cost, m_production_meter_consumption, m_production_special_consumption, m_production_time, m_slots, m_speed, m_stealth, m_structure, m_tags, and HullTypeManager::s_instance.
Graphic()
const std::string& HullType::Graphic () const inline
returns the image that represents the hull on the design screen
Referenced by ClientUI::HullIcon(), and ClientUI::HullTexture().
HasTag()
bool HullType::HasTag (const std::string & tag) const inline
returns name of hull
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Icon()
const std::string& HullType::Icon () const inline
returns the small icon to represent hull
Referenced by ClientUI::HullIcon(), ClientUI::HullTexture(), and DesignWnd::MainPanel::RefreshIncompleteDesign().
Init()
void HullType::Init (std::vector< std::unique_ptr< Effect::EffectsGroup >> && effects, const HullTypeStats & stats) private
References HullTypeStats::default_fuel_effects, HullTypeStats::default_speed_effects, HullTypeStats::default_stealth_effects, HullTypeStats::default_structure_effects, anonymous_namespace{ShipDesign.cpp}::IncreaseMeter(), m_effects, m_fuel, m_location, m_name, m_production_cost, m_production_time, m_speed, m_stealth, m_structure, METER_MAX_FUEL, METER_MAX_STRUCTURE, METER_SPEED, and METER_STEALTH.
Referenced by HullType().
Location()
const Condition::Condition* HullType::Location () const inline
returns the condition that determines the locations where ShipDesign containing hull can be produced
Referenced by anonymous_namespace{UniverseWrapper.cpp}::HullProductionLocation(), ShipDesign::ProductionLocation(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
Name()
const std::string& HullType::Name () const inline
returns name of hull
Referenced by DesignWnd::MainPanel::DesignChanged(), Universe::GetEffectsAndTargets(), DesignWnd::MainPanel::Hull(), DesignWnd::MainPanel::SetHull(), EncyclopediaDetailPanel::SetItem(), and FreeOrionPython::WrapUniverseClasses().
NumSlots() [1/2]
unsigned int HullType::NumSlots () const inline
returns total number of of slots in hull
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().
NumSlots() [2/2]
unsigned int HullType::NumSlots (ShipSlotType slot_type) const
returns number of of slots of indicated type in hull
References m_slots.
Producible()
bool HullType::Producible () const inline
returns whether this hull type is producible by players and appears on the design screen
Referenced by Empire::AddHullType(), and ShipDesign::BuildStatCaches().
ProductionCost()
float HullType::ProductionCost (int empire_id, int location_id, int in_design_id = INVALID_DESIGN_ID) const
returns the number of production points required to produce this hull
References anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_COST, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_cost, and Objects().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
ProductionCostTimeLocationInvariant()
bool HullType::ProductionCostTimeLocationInvariant () const
returns true if the production cost and time are invariant (does not depend on) the location
References GetGameRules(), m_production_cost, and m_production_time.
Referenced by FreeOrionPython::WrapUniverseClasses().
ProductionMeterConsumption()
const ConsumptionMap<MeterType>& HullType::ProductionMeterConsumption () const inline
returns name of hull
ProductionSpecialConsumption()
const ConsumptionMap<std::string>& HullType::ProductionSpecialConsumption () const inline
returns name of hull
ProductionTime()
int HullType::ProductionTime (int empire_id, int location_id, int in_design_id = INVALID_DESIGN_ID) const
returns the number of turns required to produce this hull
References anonymous_namespace{ShipDesign.cpp}::ARBITRARY_LARGE_TURNS, Empires(), ObjectMap::get(), GetGameRules(), EmpireManager::GetSource(), m_production_time, and Objects().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
serialize()
template<typename Archive > void HullType::serialize (Archive & ar, const unsigned int version) private
Shields()
float HullType::Shields () const inline
returns shields of hull
Referenced by ShipDesign::BuildStatCaches().
Slots()
const std::vector<Slot>& HullType::Slots () const inline
returns vector of slots in hull
Referenced by ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{UniverseWrapper.cpp}::HullSlots(), ShipDesign::Parts(), and DesignWnd::MainPanel::Populate().
Speed()
float HullType::Speed () const
returns starlane speed of hull
References GameRules::Get(), GetGameRules(), and m_speed.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Stealth()
float HullType::Stealth () const inline
returns stealth of hull
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Structure()
float HullType::Structure () const
returns structure of hull
References GameRules::Get(), GetGameRules(), and m_structure.
Referenced by ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), and FreeOrionPython::WrapUniverseClasses().
Tags()
const std::set<std::string>& HullType::Tags () const inline
returns name of hull
Referenced by Ship::HasTag(), and Ship::Tags().
TroopCapacity()
float HullType::TroopCapacity () const inline
returns the troop capacity of hull
Referenced by ShipDesign::BuildStatCaches().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_description
std::string HullType::m_description private
Referenced by GetCheckSum().
m_effects
std::vector<std::shared_ptr<Effect::EffectsGroup> > HullType::m_effects private
Referenced by GetCheckSum(), and Init().
m_exclusions
std::set<std::string> HullType::m_exclusions private
Referenced by GetCheckSum().
m_fuel
float HullType::m_fuel = 0.0f private
Referenced by GetCheckSum(), and Init().
m_graphic
std::string HullType::m_graphic private
Referenced by GetCheckSum().
m_icon
std::string HullType::m_icon private
Referenced by GetCheckSum().
m_location
std::unique_ptr<Condition::Condition> HullType::m_location private
Referenced by GetCheckSum(), and Init().
m_name
std::string HullType::m_name private
Referenced by GetCheckSum(), HullType(), and Init().
m_producible
bool HullType::m_producible = false private
Referenced by GetCheckSum(), and HullType().
m_production_cost
std::unique_ptr<ValueRef::ValueRef<double> > HullType::m_production_cost private
Referenced by GetCheckSum(), Init(), ProductionCost(), and ProductionCostTimeLocationInvariant().
m_production_meter_consumption
ConsumptionMap<MeterType> HullType::m_production_meter_consumption private
Referenced by GetCheckSum().
m_production_special_consumption
ConsumptionMap<std::string> HullType::m_production_special_consumption private
Referenced by GetCheckSum().
m_production_time
std::unique_ptr<ValueRef::ValueRef<int> > HullType::m_production_time private
Referenced by GetCheckSum(), Init(), ProductionCostTimeLocationInvariant(), and ProductionTime().
m_slots
std::vector<Slot> HullType::m_slots private
Referenced by GetCheckSum(), and NumSlots().
m_speed
float HullType::m_speed = 1.0f private
Referenced by GetCheckSum(), Init(), and Speed().
m_stealth
float HullType::m_stealth = 0.0f private
Referenced by GetCheckSum(), and Init().
m_structure
float HullType::m_structure = 0.0f private
Referenced by GetCheckSum(), Init(), and Structure().
m_tags
std::set<std::string> HullType::m_tags private
Referenced by GetCheckSum(), and HullType().
The documentation for this class was generated from the following files:
ShipPartHull.h
ShipDesign.cpp