FreeOrion: parse::detail::MovableEnvelope< T > Class Template Reference
parse::detail::MovableEnvelope< T > Class Template Reference
MovableEnvelope enables the boost::spirit parser to handle a T with move semantics.
#include <MovableEnvelope.h>
Public Types
using enveloped_type = T
Public Member Functions
virtual ~MovableEnvelope ()
bool IsEmptiedEnvelope () const
std::unique_ptr< T > OpenEnvelope (bool &pass) const
OpenEnvelope returns the enclosed obj and throws an expectation exception if the wrapped pointer was already moved out of this MovableEnvelope.
Rule of Five constructors and operators.
MovableEnvelope satisfies the rule of five with the following constructors and operator=().
MovableEnvelope ()
MovableEnvelope (const MovableEnvelope &other)
MovableEnvelope (MovableEnvelope &&other)
MovableEnvelope & operator= (MovableEnvelope &&other)
MovableEnvelope & operator= (const MovableEnvelope &other)
Converting constructors and operators.
MovableEnvelope allows conversion between compatible types with the following constructors and operators.
MovableEnvelope (std::nullptr_t)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope (std::unique_ptr< U > &&obj_)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope (U *obj_)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope (const MovableEnvelope< U > &other)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope (MovableEnvelope< U > &&other)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope & operator= (MovableEnvelope< U > &&other)
template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr>
MovableEnvelope & operator= (const MovableEnvelope< U > &other)
Private Attributes
std::unique_ptr< T > obj
T * original_obj = nullptr
Friends
template<typename U >
class MovableEnvelope
Detailed Description
template<typename T>
class parse::detail::MovableEnvelope< T >
MovableEnvelope enables the boost::spirit parser to handle a T with move semantics.
boost::spirit is designed only work with value semantics. The boost::phoenix actors only handle value semantics. Types with move only semantics like unique_ptr will not work as expected.
boost::spirit is designed to work with compile time polymorphism. With run-time polymorphism using raw pointers to track heap objects, each time the parser backtracks it leaks memory.
MovableEnvelope makes a unique_ptr<T> with move only semantics appear to have copy semantics, by moving it each time that it is copied. This allows boost::phoenix actors to handle it correctly if the movement is one way from creation at the parse location to consumption in a larger parsed component.
MovableEnvelope is a work around. It can be removed if boost::spirit supports move semantics, or the parser is changed to use compile time polymorphism.
Member Typedef Documentation
enveloped_type
template<typename T> using parse::detail::MovableEnvelope< T >::enveloped_type = T
Constructor & Destructor Documentation
MovableEnvelope() [1/8]
template<typename T> parse::detail::MovableEnvelope< T >::MovableEnvelope () inline
MovableEnvelope() [2/8]
template<typename T> parse::detail::MovableEnvelope< T >::MovableEnvelope (const MovableEnvelope< T > & other) inline
MovableEnvelope() [3/8]
template<typename T> parse::detail::MovableEnvelope< T >::MovableEnvelope (MovableEnvelope< T > && other) inline
~MovableEnvelope()
template<typename T> virtual parse::detail::MovableEnvelope< T >::~MovableEnvelope () inline virtual
MovableEnvelope() [4/8]
template<typename T> parse::detail::MovableEnvelope< T >::MovableEnvelope (std::nullptr_t) inline
MovableEnvelope() [5/8]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> parse::detail::MovableEnvelope< T >::MovableEnvelope (std::unique_ptr< U > && obj_) inline explicit
MovableEnvelope() [6/8]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> parse::detail::MovableEnvelope< T >::MovableEnvelope (U * obj_) inline explicit
MovableEnvelope() [7/8]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> parse::detail::MovableEnvelope< T >::MovableEnvelope (const MovableEnvelope< U > & other) inline
MovableEnvelope() [8/8]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> parse::detail::MovableEnvelope< T >::MovableEnvelope (MovableEnvelope< U > && other) inline
Member Function Documentation
IsEmptiedEnvelope()
template<typename T> bool parse::detail::MovableEnvelope< T >::IsEmptiedEnvelope () const inline
References parse::detail::MovableEnvelope< T >::obj, and parse::detail::MovableEnvelope< T >::original_obj.
Referenced by parse::detail::MovableEnvelope< T >::OpenEnvelope().
OpenEnvelope()
template<typename T> std::unique_ptr<T> parse::detail::MovableEnvelope< T >::OpenEnvelope (bool & pass) const inline
OpenEnvelope returns the enclosed obj and throws an expectation exception if the wrapped pointer was already moved out of this MovableEnvelope.
OpenEnvelope is a one-shot. Calling OpenEnvelope a second time will throw, since the obj has already been removed.
pass should refer to qi::_pass_type to facilitate the expectation exception.
References ErrorLogger, parse::detail::MovableEnvelope< T >::IsEmptiedEnvelope(), and parse::detail::MovableEnvelope< T >::obj.
Referenced by parse::construct_EffectsGroup(), parse::detail::construct_GenerateSitRepMessage2(), anonymous_namespace{BuildingsParser.cpp}::insert_building(), anonymous_namespace{ShipHullsParser.cpp}::insert_shiphull(), anonymous_namespace{ShipPartsParser.cpp}::insert_shippart(), anonymous_namespace{TechsParser.cpp}::insert_tech(), parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1::operator()(), and parse::detail::deconstruct_movable::operator()().
operator=() [1/4]
template<typename T> MovableEnvelope& parse::detail::MovableEnvelope< T >::operator= (MovableEnvelope< T > && other) inline
References parse::detail::MovableEnvelope< T >::obj, and parse::detail::MovableEnvelope< T >::original_obj.
operator=() [2/4]
template<typename T> MovableEnvelope& parse::detail::MovableEnvelope< T >::operator= (const MovableEnvelope< T > & other) inline
References parse::detail::MovableEnvelope< T >::obj, and parse::detail::MovableEnvelope< T >::original_obj.
operator=() [3/4]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> MovableEnvelope& parse::detail::MovableEnvelope< T >::operator= (MovableEnvelope< U > && other) inline
References parse::detail::MovableEnvelope< T >::obj, and parse::detail::MovableEnvelope< T >::original_obj.
operator=() [4/4]
template<typename T> template<typename U , typename std::enable_if_t< std::is_convertible_v< std::unique_ptr< U >, std::unique_ptr< T >>> * = nullptr> MovableEnvelope& parse::detail::MovableEnvelope< T >::operator= (const MovableEnvelope< U > & other) inline
References parse::detail::MovableEnvelope< T >::obj, and parse::detail::MovableEnvelope< T >::original_obj.
Friends And Related Function Documentation
MovableEnvelope
template<typename T> template<typename U > friend class MovableEnvelope friend
Member Data Documentation
obj
template<typename T> std::unique_ptr<T> parse::detail::MovableEnvelope< T >::obj mutable private
Referenced by parse::detail::MovableEnvelope< T >::IsEmptiedEnvelope(), parse::detail::MovableEnvelope< T >::OpenEnvelope(), parse::detail::construct_movable::operator()(), and parse::detail::MovableEnvelope< T >::operator=().
original_obj
template<typename T> T* parse::detail::MovableEnvelope< T >::original_obj = nullptr mutable private
Referenced by parse::detail::MovableEnvelope< T >::IsEmptiedEnvelope(), and parse::detail::MovableEnvelope< T >::operator=().
The documentation for this class was generated from the following file:
MovableEnvelope.h