FreeOrion: PlayerListBox Class Reference
PlayerListBox Class Reference
Public Member Functions
PlayerListBox (void)
GG::Pt ListRowSize () const
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Static Public Member Functions
static GG::Y ListRowHeight ()
Constructor & Destructor Documentation
PlayerListBox::PlayerListBox (void) inline
Member Function Documentation
static GG::Y PlayerListBox::ListRowHeight () inline static
References ClientUI::Pts().
GG::Pt PlayerListBox::ListRowSize () const inline
References anonymous_namespace{FleetWnd.cpp}::ListRowHeight(), and ClientUI::ScrollWidth().
Referenced by PlayerListWnd::Refresh().
void PlayerListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Referenced by PlayerListWnd::DoLayout().
The documentation for this class was generated from the following file:
PlayerListWnd.cpp