FreeOrion: NamedValueRefManager Class Reference
NamedValueRefManager Class Reference
Holds all FreeOrion named ValueRefs. ValueRefs may be looked up by name.
#include <NamedValueRefManager.h>
Public Types
using any_container_type = std::map< key_type, std::reference_wrapper< ValueRef::ValueRefBase > >
using any_entry_type = std::pair< key_type, std::reference_wrapper< ValueRef::ValueRefBase > >
using container_type = std::map< key_type, value_type >
using double_container_type = std::map< key_type, double_value_type >
using double_entry_type = std::pair< key_type, double_value_type >
using double_value_type = std::unique_ptr< ValueRef::ValueRef< double > >
using entry_type = std::pair< key_type, value_type >
using int_container_type = std::map< key_type, int_value_type >
using int_entry_type = std::pair< key_type, int_value_type >
using int_value_type = std::unique_ptr< ValueRef::ValueRef< int > >
using iterator = container_type::const_iterator
using key_type = const std::string
using NamedValueRefParseMap = std::map< std::string, std::unique_ptr< ValueRef::ValueRefBase > >
using value_type = std::unique_ptr< ValueRef::ValueRefBase >
Public Member Functions
NamedValueRefManager (NamedValueRefManager const &)=delete
~NamedValueRefManager ()=default
auto GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
auto GetItems () const -> any_container_type
returns a map with all named value refs
template<typename T >
auto GetValueRef (const std::string &name, const bool wait_for_named_value_focs_txt_parse=false) -> ValueRef::ValueRef< T > *const
Returns the ValueRef with the name name or nullptr if there is nov ValueRef with such a name or of the wrong type use the free function GetValueRef(...) instead, mainly to save some typing.
template<typename T >
ValueRef::ValueRef< T > *const GetValueRef (const std::string &name, const bool wait_for_named_value_focs_txt_parse)
template<>
ValueRef::ValueRef< int > *const GetValueRef (const std::string &name, const bool wait_for_named_value_focs_txt_parse)
template<>
ValueRef::ValueRef< double > *const GetValueRef (const std::string &name, const bool wait_for_named_value_focs_txt_parse)
auto GetValueRefBase (const std::string &name) const -> ValueRef::ValueRefBase *const
Returns the ValueRef with the name name; you should use the free function GetValueRef(...) instead, mainly to save some typing.
NamedValueRefManager & operator= (NamedValueRefManager const &)=delete
template<typename T >
void RegisterValueRef (std::string &&name, std::unique_ptr< ValueRef::ValueRef< T >> &&vref)
Register the value_ref under the evaluated name.
template<>
void RegisterValueRef (std::string &&valueref_name, std::unique_ptr< ValueRef::ValueRef< int >> &&vref)
template<>
void RegisterValueRef (std::string &&valueref_name, std::unique_ptr< ValueRef::ValueRef< double >> &&vref)
FO_COMMON_API void SetNamedValueRefParse (Pending::Pending< NamedValueRefParseMap > &&future)
This sets the asynchronous parse, so we can block on that when a function needs to access a registry.
Static Public Member Functions
static NamedValueRefManager & GetNamedValueRefManager ()
Returns the instance of this singleton class; you should use the free function GetNamedValueRefManager() instead.
Private Member Functions
NamedValueRefManager ()
void CheckPendingNamedValueRefs () const
Waits for parsing of named_value_refs.focs.txt to finish.
Private Attributes
boost::optional< Pending::Pending< NamedValueRefParseMap > > m_pending_named_value_refs_focs_txt = boost::none
container_type m_value_refs
double_container_type m_value_refs_double
Map of ValueRefs identified by a name and mutexes for those to allow asynchronous registration.
std::mutex m_value_refs_double_mutex
int_container_type m_value_refs_int
std::mutex m_value_refs_int_mutex
std::mutex m_value_refs_mutex
Static Private Attributes
static NamedValueRefManager * s_instance = nullptr
Detailed Description
Holds all FreeOrion named ValueRefs. ValueRefs may be looked up by name.
Member Typedef Documentation
any_container_type
using NamedValueRefManager::any_container_type = std::map<key_type, std::reference_wrapper<ValueRef::ValueRefBase> >
any_entry_type
using NamedValueRefManager::any_entry_type = std::pair<key_type, std::reference_wrapper<ValueRef::ValueRefBase> >
container_type
using NamedValueRefManager::container_type = std::map<key_type, value_type>
double_container_type
using NamedValueRefManager::double_container_type = std::map<key_type, double_value_type>
double_entry_type
using NamedValueRefManager::double_entry_type = std::pair<key_type, double_value_type>
double_value_type
using NamedValueRefManager::double_value_type = std::unique_ptr<ValueRef::ValueRef<double> >
entry_type
using NamedValueRefManager::entry_type = std::pair<key_type, value_type>
int_container_type
using NamedValueRefManager::int_container_type = std::map<key_type, int_value_type>
int_entry_type
using NamedValueRefManager::int_entry_type = std::pair<key_type, int_value_type>
int_value_type
using NamedValueRefManager::int_value_type = std::unique_ptr<ValueRef::ValueRef<int> >
iterator
using NamedValueRefManager::iterator = container_type::const_iterator
key_type
using NamedValueRefManager::key_type = const std::string
NamedValueRefParseMap
using NamedValueRefManager::NamedValueRefParseMap = std::map<std::string, std::unique_ptr<ValueRef::ValueRefBase> >
value_type
using NamedValueRefManager::value_type = std::unique_ptr<ValueRef::ValueRefBase>
Constructor & Destructor Documentation
NamedValueRefManager() [1/2]
NamedValueRefManager::NamedValueRefManager (NamedValueRefManager const &) delete
~NamedValueRefManager()
NamedValueRefManager::~NamedValueRefManager () default
NamedValueRefManager() [2/2]
NamedValueRefManager::NamedValueRefManager () private
References InfoLogger, and s_instance.
Member Function Documentation
CheckPendingNamedValueRefs()
void NamedValueRefManager::CheckPendingNamedValueRefs () const private
Waits for parsing of named_value_refs.focs.txt to finish.
References m_pending_named_value_refs_focs_txt, and Pending::WaitForPending().
Referenced by GetCheckSum(), GetItems(), GetValueRef(), and GetValueRefBase().
GetCheckSum()
unsigned int NamedValueRefManager::GetCheckSum () const -> unsigned int
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function.
Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckPendingNamedValueRefs(), CheckSums::CheckSumCombine(), DebugLogger, m_value_refs, m_value_refs_double, and m_value_refs_int.
Referenced by CheckSumContent().
GetItems()
NamedValueRefManager::any_container_type NamedValueRefManager::GetItems () const -> any_container_type
returns a map with all named value refs
References CheckPendingNamedValueRefs(), m_value_refs, m_value_refs_double, and m_value_refs_int.
GetNamedValueRefManager()
NamedValueRefManager & NamedValueRefManager::GetNamedValueRefManager () static
Returns the instance of this singleton class; you should use the free function GetNamedValueRefManager() instead.
References TraceLogger.
Referenced by GetNamedValueRefManager(), GetValueRef(), GetValueRefBase(), and RegisterValueRef().
GetValueRef() [1/4]
template<typename T > auto NamedValueRefManager::GetValueRef (const std::string & name, const bool wait_for_named_value_focs_txt_parse = false) -> ValueRef::ValueRef< T > *const
Returns the ValueRef with the name name or nullptr if there is nov ValueRef with such a name or of the wrong type use the free function GetValueRef(...) instead, mainly to save some typing.
Referenced by GetValueRef(), and RegisterValueRef().
GetValueRef() [2/4]
template<typename T > ValueRef::ValueRef<T>* const NamedValueRefManager::GetValueRef (const std::string & name, const bool wait_for_named_value_focs_txt_parse)
References CheckPendingNamedValueRefs(), anonymous_namespace{NamedValueRefManager.cpp}::GetValueRefImpl(), and m_value_refs.
GetValueRef() [3/4]
template<> ValueRef::ValueRef<int>* const NamedValueRefManager::GetValueRef (const std::string & name, const bool wait_for_named_value_focs_txt_parse)
References CheckPendingNamedValueRefs(), anonymous_namespace{NamedValueRefManager.cpp}::GetValueRefImpl(), and m_value_refs_int.
GetValueRef() [4/4]
template<> ValueRef::ValueRef<double>* const NamedValueRefManager::GetValueRef (const std::string & name, const bool wait_for_named_value_focs_txt_parse)
References CheckPendingNamedValueRefs(), anonymous_namespace{NamedValueRefManager.cpp}::GetValueRefImpl(), and m_value_refs_double.
GetValueRefBase()
ValueRef::ValueRefBase *const NamedValueRefManager::GetValueRefBase (const std::string & name) const -> ValueRef::ValueRefBase* const
Returns the ValueRef with the name name; you should use the free function GetValueRef(...) instead, mainly to save some typing.
References CheckPendingNamedValueRefs(), and m_value_refs.
Referenced by GetValueRefBase().
operator=()
NamedValueRefManager& NamedValueRefManager::operator= (NamedValueRefManager const &) delete
RegisterValueRef() [1/3]
template<typename T > void NamedValueRefManager::RegisterValueRef (std::string && name, std::unique_ptr< ValueRef::ValueRef< T >> && vref)
Register the value_ref under the evaluated name.
References m_value_refs, m_value_refs_mutex, and anonymous_namespace{NamedValueRefManager.cpp}::RegisterValueRefImpl().
Referenced by RegisterValueRef().
RegisterValueRef() [2/3]
template<> void NamedValueRefManager::RegisterValueRef (std::string && valueref_name, std::unique_ptr< ValueRef::ValueRef< int >> && vref)
References m_value_refs_int, m_value_refs_int_mutex, and anonymous_namespace{NamedValueRefManager.cpp}::RegisterValueRefImpl().
RegisterValueRef() [3/3]
template<> void NamedValueRefManager::RegisterValueRef (std::string && valueref_name, std::unique_ptr< ValueRef::ValueRef< double >> && vref)
References m_value_refs_double, m_value_refs_double_mutex, and anonymous_namespace{NamedValueRefManager.cpp}::RegisterValueRefImpl().
SetNamedValueRefParse()
void NamedValueRefManager::SetNamedValueRefParse (Pending::Pending< NamedValueRefParseMap > && future)
This sets the asynchronous parse, so we can block on that when a function needs to access a registry.
References m_pending_named_value_refs_focs_txt.
Referenced by IApp::StartBackgroundParsing().
Member Data Documentation
m_pending_named_value_refs_focs_txt
boost::optional<Pending::Pending<NamedValueRefParseMap> > NamedValueRefManager::m_pending_named_value_refs_focs_txt = boost::none mutable private
Referenced by CheckPendingNamedValueRefs(), and SetNamedValueRefParse().
m_value_refs
container_type NamedValueRefManager::m_value_refs private
Referenced by GetCheckSum(), GetItems(), GetValueRef(), GetValueRefBase(), and RegisterValueRef().
m_value_refs_double
double_container_type NamedValueRefManager::m_value_refs_double private
Map of ValueRefs identified by a name and mutexes for those to allow asynchronous registration.
Referenced by GetCheckSum(), GetItems(), GetValueRef(), and RegisterValueRef().
m_value_refs_double_mutex
std::mutex NamedValueRefManager::m_value_refs_double_mutex private
Referenced by RegisterValueRef().
m_value_refs_int
int_container_type NamedValueRefManager::m_value_refs_int private
Referenced by GetCheckSum(), GetItems(), GetValueRef(), and RegisterValueRef().
m_value_refs_int_mutex
std::mutex NamedValueRefManager::m_value_refs_int_mutex private
Referenced by RegisterValueRef().
m_value_refs_mutex
std::mutex NamedValueRefManager::m_value_refs_mutex private
Referenced by RegisterValueRef().
s_instance
NamedValueRefManager * NamedValueRefManager::s_instance = nullptr static private
Referenced by NamedValueRefManager().
The documentation for this class was generated from the following files:
NamedValueRefManager.h
NamedValueRefManager.cpp