FreeOrion: FleetTransferOrder Class Reference
FleetTransferOrder Class Reference
The Order subclass that represents transfer of ships between existing fleets A FleetTransferOrder is used to transfer ships from one existing fleet to another.
#include <Order.h>
Public Member Functions
Structors
FleetTransferOrder (int empire, int dest_fleet, const std::vector< int > &ships)
Accessors
int DestinationFleet () const
Returns IDs of the ships selected for addition to the fleet.
const std::vector< int > & Ships () const
Returns IDs of the ships selected for addition to the fleet.
Public Member Functions inherited from Order
void Execute () const
Executes the order on the Universe and Empires.
bool Undo () const
If this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect.
Order ()
ctor taking the ID of the Empire issuing the order.
Order (int empire)
ctor taking the ID of the Empire issuing the order.
virtual ~Order ()
ctor taking the ID of the Empire issuing the order.
int EmpireID () const
Returns the ID of the Empire issuing the order.
bool Executed () const
Returns true iff this order has been executed (a second execution indicates server-side execution).
Static Public Member Functions
static bool Check (int empire_id, int dest_fleet_id, const std::vector< int > &ship_ids)
Private Member Functions
FleetTransferOrder ()=default
void ExecuteImpl () const override
FleetTransferOrder's preconditions are:
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< int > m_add_ships
int m_dest_fleet = INVALID_OBJECT_ID
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
Empire * GetValidatedEmpire () const
Verifies that the empire ID in this order is valid and return the Empire pointer.
Detailed Description
The Order subclass that represents transfer of ships between existing fleets A FleetTransferOrder is used to transfer ships from one existing fleet to another.
Constructor & Destructor Documentation
FleetTransferOrder::FleetTransferOrder (int empire, int dest_fleet, const std::vector< int > & ships)
References Check().
FleetTransferOrder::FleetTransferOrder () private default
Member Function Documentation
bool FleetTransferOrder::Check (int empire_id, int dest_fleet_id, const std::vector< int > & ship_ids) static
References ErrorLogger, GetFleet(), INVALID_OBJECT_ID, and Objects().
Referenced by ExecuteImpl(), and FleetTransferOrder().
int FleetTransferOrder::DestinationFleet () const inline
Returns IDs of the ships selected for addition to the fleet.
Referenced by ExecuteImpl().
void FleetTransferOrder::ExecuteImpl () const override private virtual
FleetTransferOrder's preconditions are:
m_into_fleet must be the ID of a fleet owned by the issuing empire
each element of m_add_ships must be the ID of a ship owned by the issuing empire
Postconditions:
all ships in m_add_ships will be moved from their initial fleet to the destination fleet
any resulting empty fleets will be deleted
Implements Order.
References Check(), DestinationFleet(), Universe::Destroy(), Order::EmpireID(), ObjectMap::FindObjects(), GetFleet(), GetSystem(), GetUniverse(), Order::GetValidatedEmpire(), Universe::InhibitUniverseObjectSignals(), m_add_ships, and Objects().
template<class Archive > void FleetTransferOrder::serialize (Archive & ar, const unsigned int version) private
const std::vector<int>& FleetTransferOrder::Ships () const inline
Returns IDs of the ships selected for addition to the fleet.
References Order::ExecuteImpl().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<int> FleetTransferOrder::m_add_ships private
Referenced by ExecuteImpl().
int FleetTransferOrder::m_dest_fleet = INVALID_OBJECT_ID private
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp