FreeOrion: TechTreeLayout Class Reference
TechTreeLayout Class Reference
This class stores internal information for layouting the tech graph.
#include <TechTreeLayout.h>
Classes
class Column
class Edge
class Node
Public Member Functions
~TechTreeLayout ()
releases all resources
void AddEdge (std::string const &parent, std::string const &child)
void AddNode (std::string const &tech, GG::X width, GG::Y height)
void Clear ()
void Debug () const
void DoLayout (double column_width, double row_height, double x_margin)
creates and initialises all nodes
auto GetHeight (std::string const &name) const
auto GetHeight () const -> GG::Y const
auto GetNode (std::string const &name) const -> Node const *
auto GetOutEdges (std::string const &name) const -> std::vector< Edge *> const &
auto GetWidth (std::string const &name) const -> double
auto GetWidth () const -> GG::X const
Private Attributes
int m_column_count = 0
double m_height = 0
height of the complete graph
std::map< std::string, Node * > m_node_map
map name->node for external access by name
std::vector< Node * > m_nodes
list of nodes for sorting
int m_row_count = 0
double m_width = 0
width of the complete graph
Detailed Description
This class stores internal information for layouting the tech graph.
The whole space is organized in a table. Every tech is assign a tech level, or depth, which is the maximum distance it is from start techs. Every tech level (depth) is one column. The first column has depth 1 techs, 2nd column has depth 2 tech, etc. An initial column is filled with techs grouped by category (may be middle or first, or ? column) Nodes in adjacent columns are placed near the average of children or parent nodes in adjacent columns For children or parents that don't lie in the next column we generate dummy techs that are rendered as horizontal line (part of the future connection arrow) that connect the low tech with the high tech. This allows complex connection lines. Dummy techs are directly processed in order to keep them as straight as possible.
sample (without category) A->DE B->D C->F D->F E->F A(1) D(2) E(2) B(1) D(2) C(1) F(3) C(1)->F(3) changed to C(1)->G*(2)->F(3) (Dummy)
Column We sort the start Techs A | | B | | C | | C has a Dummy child, which is placed at once A | | B | | C | G |
Column D has parents A, B. The average is 1 a free place A | D | B | | C | G* | E has parents A. The average is 1 but already used, it's place in 2 A | D | B | E | C | G* |
Column F has parents G*, D, E note that C was replaced with a dummy. The average is 2 a free place A | D | B | E | F C | G* |
now we create the arrows A--/->D–\ B-/ ->E—>F C --—G*-/
author Lathanda
Constructor & Destructor Documentation
~TechTreeLayout()
TechTreeLayout::~TechTreeLayout ()
releases all resources
References m_nodes.
Member Function Documentation
AddEdge()
void TechTreeLayout::AddEdge (std::string const & parent, std::string const & child)
References m_node_map.
Referenced by TechTreeWnd::LayoutPanel::Layout().
AddNode()
void TechTreeLayout::AddNode (std::string const & tech, GG::X width, GG::Y height)
References GetTech(), m_node_map, and m_nodes.
Referenced by TechTreeWnd::LayoutPanel::Layout().
Clear()
void TechTreeLayout::Clear ()
!! IMPORTANT !!! Node have to be delete in order depth ascending or we will access freed memory!
References m_node_map, and m_nodes.
Referenced by TechTreeWnd::LayoutPanel::Clear().
Debug()
void TechTreeLayout::Debug () const
References m_nodes.
DoLayout()
void TechTreeLayout::DoLayout (double column_width, double row_height, double x_margin)
creates and initialises all nodes
Parameters
column_width width of each column
row_height height of each row
x_margin horizontal part of arrow before changing direction to child node
References Tech::Category(), DebugLogger, GetTech(), m_height, m_nodes, m_width, and anonymous_namespace{TechTreeLayout.cpp}::NODE_CELL_HEIGHT.
Referenced by TechTreeWnd::LayoutPanel::Layout().
GetHeight() [1/2]
auto TechTreeLayout::GetHeight (std::string const & name) const
Referenced by TechTreeWnd::LayoutPanel::Layout().
GetHeight() [2/2]
const GG::Y TechTreeLayout::GetHeight () const -> GG::Y const
References m_height.
GetNode()
const TechTreeLayout::Node * TechTreeLayout::GetNode (std::string const & name) const -> Node const *
References TechTreeLayout::Edge::Debug(), DebugLogger, and m_node_map.
Referenced by TechTreeWnd::LayoutPanel::Layout().
GetOutEdges()
const std::vector< TechTreeLayout::Edge * > & TechTreeLayout::GetOutEdges (std::string const & name) const -> std::vector<Edge*> const &
References TechTreeLayout::Edge::Debug(), DebugLogger, and m_node_map.
Referenced by TechTreeArcs::Impl::FillArcBuffer().
GetWidth() [1/2]
auto TechTreeLayout::GetWidth (std::string const & name) const -> double
Referenced by TechTreeWnd::LayoutPanel::Layout().
GetWidth() [2/2]
const GG::X TechTreeLayout::GetWidth () const -> GG::X const
References m_width.
Member Data Documentation
m_column_count
int TechTreeLayout::m_column_count = 0 private
m_height
double TechTreeLayout::m_height = 0 private
height of the complete graph
Referenced by DoLayout(), and GetHeight().
m_node_map
std::map<std::string, Node*> TechTreeLayout::m_node_map private
map name->node for external access by name
Referenced by AddEdge(), AddNode(), Clear(), GetNode(), and GetOutEdges().
m_nodes
std::vector<Node*> TechTreeLayout::m_nodes private
list of nodes for sorting
Referenced by AddNode(), Clear(), Debug(), DoLayout(), and ~TechTreeLayout().
m_row_count
int TechTreeLayout::m_row_count = 0 private
m_width
double TechTreeLayout::m_width = 0 private
width of the complete graph
Referenced by DoLayout(), and GetWidth().
The documentation for this class was generated from the following files:
TechTreeLayout.h
TechTreeLayout.cpp