FreeOrion: boost::iostreams::core_access Class Reference
boost::iostreams::core_access Class Reference
#include <base64_filter.h>
Classes
struct device_operations
struct filter_operations
Static Private Member Functions
template<class RepositionalSink , class CharT >
static void close_with_flush (RepositionalSink &sink, const CharT *s, std::streamsize n)
template<class RepositionalOutputFilter , class Sink >
static void close_with_flush (RepositionalOutputFilter &filter, Sink &sink, const typename boost::iostreams::char_type_of< Sink >::type *s, std::streamsize n)
template<class RepositionalSource , class CharT >
static std::streamsize read_blocks (RepositionalSource &src, CharT *s, std::streamsize n)
template<class RepositionalInputFilter , class Source >
static std::streamsize read_blocks (RepositionalInputFilter &filter, Source &src, typename boost::iostreams::char_type_of< Source >::type *s, std::streamsize n)
template<class RepositionalDevice >
static std::streampos seek_blocks (RepositionalDevice &dev, boost::iostreams::stream_offset off, BOOST_IOS::seekdir way)
template<class RepositionalSink , class CharT >
static std::streamsize write_blocks (RepositionalSink &sink, const CharT *s, std::streamsize n)
template<class RepositionalOutputFilter , class Sink >
static std::streamsize write_blocks (RepositionalOutputFilter &filter, Sink &sink, const typename boost::iostreams::char_type_of< Sink >::type *s, std::streamsize n)
Friends
template<class Derived , class CharT , std::streamsize MaxBlockSize>
class arbitrary_positional_facade
struct device_operations
template<class Device >
struct filter_operations
Member Function Documentation
template<class RepositionalSink , class CharT > static void boost::iostreams::core_access::close_with_flush (RepositionalSink & sink, const CharT * s, std::streamsize n) inline static private
Referenced by boost::iostreams::arbitrary_positional_facade< basic_base64_encoder< Traits >, char, 3 >::close().
template<class RepositionalOutputFilter , class Sink > static void boost::iostreams::core_access::close_with_flush (RepositionalOutputFilter & filter, Sink & sink, const typename boost::iostreams::char_type_of< Sink >::type * s, std::streamsize n) inline static private
template<class RepositionalSource , class CharT > static std::streamsize boost::iostreams::core_access::read_blocks (RepositionalSource & src, CharT * s, std::streamsize n) inline static private
Referenced by boost::iostreams::core_access::device_operations::read_blocks(), boost::iostreams::core_access::filter_operations< Device >::read_blocks(), and boost::iostreams::arbitrary_positional_facade< basic_base64_encoder< Traits >, char, 3 >::seek().
template<class RepositionalInputFilter , class Source > static std::streamsize boost::iostreams::core_access::read_blocks (RepositionalInputFilter & filter, Source & src, typename boost::iostreams::char_type_of< Source >::type * s, std::streamsize n) inline static private
template<class RepositionalDevice > static std::streampos boost::iostreams::core_access::seek_blocks (RepositionalDevice & dev, boost::iostreams::stream_offset off, BOOST_IOS::seekdir way) inline static private
Referenced by boost::iostreams::arbitrary_positional_facade< basic_base64_encoder< Traits >, char, 3 >::seek().
template<class RepositionalSink , class CharT > static std::streamsize boost::iostreams::core_access::write_blocks (RepositionalSink & sink, const CharT * s, std::streamsize n) inline static private
Referenced by boost::iostreams::core_access::device_operations::write_blocks(), and boost::iostreams::core_access::filter_operations< Device >::write_blocks().
template<class RepositionalOutputFilter , class Sink > static std::streamsize boost::iostreams::core_access::write_blocks (RepositionalOutputFilter & filter, Sink & sink, const typename boost::iostreams::char_type_of< Sink >::type * s, std::streamsize n) inline static private
Friends And Related Function Documentation
template<class Derived , class CharT , std::streamsize MaxBlockSize> friend class arbitrary_positional_facade friend
friend struct device_operations friend
template<class Device > friend struct filter_operations friend
The documentation for this class was generated from the following file:
base64_filter.h