FreeOrion: System Class Reference
System Class Reference
contains UniverseObjects and connections to other systems (starlanes and wormholes).
#include <System.h>
Public Member Functions
int Owner () const override
Systems are unowned unless at least one planet is owned by an empire and no other empire owns any planets in the system.
int SystemID () const override
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
Mutators
void Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES) override
Adding owner to system objects is a no-op.
void SetOwner (int id) override
Adding owner to system objects is a no-op.
void ResetTargetMaxUnpairedMeters () override
Adding owner to system objects is a no-op.
void Insert (std::shared_ptr< UniverseObject > obj, int orbit=-1)
adds an object to this system.
void Remove (int id)
removes the object with ID number id from this system.
void SetStarType (StarType type)
sets the type of the star in this Systems to StarType
void AddStarlane (int id)
adds a starlane between this system and the system with ID number id.
void AddWormhole (int id)
adds a wormhole between this system and the system with ID number id
bool RemoveStarlane (int id)
removes a starlane between this system and the system with ID number id. Returns false if there was no starlane from this system to system id.
bool RemoveWormhole (int id)
removes a wormhole between this system and the system with ID number id. Returns false if there was no wormhole from this system to system id.
void SetLastTurnBattleHere (int turn)
Sets the last turn there was a battle at this system.
void SetOverlayTexture (const std::string &texture, double size)
Adding owner to system objects is a no-op.
Public Member Functions inherited from UniverseObject
void SetID (int id)
sets the ID number of the object to id
void Rename (const std::string &name)
renames this object to name
void Move (double x, double y)
moves this object by relative displacements x and y.
void MoveTo (int object_id)
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
void MoveTo (std::shared_ptr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
void MoveTo (double x, double y)
moves this object to map coordinates (x, y).
MeterMap & Meters ()
returns this UniverseObject's meters
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void BackPropagateMeters ()
Sets all this UniverseObject's meters' initial values equal to their current values.
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void SetSpecialCapacity (const std::string &name, float capacity)
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
virtual void MovementPhase ()
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
virtual void ResetPairedActiveMeters ()
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
virtual void ClampMeters ()
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
virtual void PopGrowthProductionResearchPhase ()
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const std::string & Name () const
returns the name of this object; some valid objects will have no name
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
bool Unowned () const
returns true iff there are no owners of this object
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual bool HostileToEmpire (int empire_id) const
Object owner is at war with empire empire_id.
const std::map< std::string, std::pair< int, float > > & Specials () const
returns the Specials attached to this object
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
emitted when the UniverseObject is altered in any way
virtual std::set< std::string > Tags () const
returns the capacity of the special with name name or 0 if that special is not present
virtual bool HasTag (const std::string &name) const
Returns true iff this object has the tag with the indicated name.
virtual int ContainerObjectID () const
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
const MeterMap & Meters () const
returns this UniverseObject's meters
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
virtual const std::string & PublicName (int empire_id) const
Returns the name of this objectas it appears to empire empire_id .
int CreationTurn () const
returns game turn on which object was created
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
virtual ~UniverseObject ()
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::set< int > m_buildings
std::set< int > m_fields
std::set< int > m_fleets
int m_last_turn_battle_here = INVALID_GAME_TURN
the turn on which there was last a battle in this system
std::set< int > m_objects
std::vector< int > m_orbits = std::vector<int>(SYSTEM_ORBITS, INVALID_OBJECT_ID)
indexed by orbit number, indicates the id of the planet in that orbit
double m_overlay_size = 1.0
std::string m_overlay_texture
std::set< int > m_planets
std::set< int > m_ships
StarType m_star
std::map< int, bool > m_starlanes_wormholes
the ints represent the IDs of other connected systems; the bools indicate whether the connection is a wormhole (true) or a starlane (false)
Friends
class boost::serialization::access
class ObjectMap
class Universe
Accessors
boost::signals2::signal< void(const std::vector< std::shared_ptr< Fleet >> &)> FleetsInsertedSignal
fleets are inserted into system
boost::signals2::signal< void(const std::vector< std::shared_ptr< Fleet >> &)> FleetsRemovedSignal
fleets are removed from system
UniverseObjectType ObjectType () const override
fleets are inserted into system
std::string Dump (unsigned short ntabs=0) const override
fleets are inserted into system
const std::set< int > & ContainedObjectIDs () const override
fleets are inserted into system
bool Contains (int object_id) const override
fleets are inserted into system
bool ContainedBy (int object_id) const override
fleets are inserted into system
std::shared_ptr< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const override
fleets are inserted into system
const std::string & ApparentName (int empire_id, bool blank_unexplored_and_none=false) const
returns the name to display for players for this system.
StarType GetStarType () const
returns the type of star for this system
StarType NextOlderStarType () const
fleets are inserted into system
StarType NextYoungerStarType () const
fleets are inserted into system
int Orbits () const
returns the number of orbits in this system
int NumStarlanes () const
returns the number of starlanes from this system to other systems
int NumWormholes () const
returns the number of wormholes from this system to other systems
bool HasStarlaneTo (int id) const
returns true if there is a starlane from this system to the system with ID number id
bool HasWormholeTo (int id) const
returns true if there is a wormhole from this system to the system with ID number id
const std::set< int > & ObjectIDs () const
fleets are inserted into system
const std::set< int > & PlanetIDs () const
fleets are inserted into system
const std::set< int > & BuildingIDs () const
fleets are inserted into system
const std::set< int > & FleetIDs () const
fleets are inserted into system
const std::set< int > & ShipIDs () const
fleets are inserted into system
const std::set< int > & FieldIDs () const
fleets are inserted into system
const std::vector< int > & PlanetIDsByOrbit () const
fleets are inserted into system
int PlanetInOrbit (int orbit) const
returns the ID of the planet in the specified orbit, or INVALID_OBJECT_ID if there is no planet in that orbit or it is an invalid orbit
int OrbitOfPlanet (int object_id) const
returns the orbit ID in which the planet with object_id is located, or -1 the specified ID is not a planet in an orbit of this system
bool OrbitOccupied (int orbit) const
returns true if there is an object in orbit
std::set< int > FreeOrbits () const
returns the set of orbit numbers that are unoccupied
const std::map< int, bool > & StarlanesWormholes () const
returns map of all starlanes and wormholes; map contains keys that are IDs of connected systems, and bool values indicating whether each is a starlane (false) or a wormhole (true)
std::map< int, bool > VisibleStarlanesWormholes (int empire_id) const
returns a map of the starlanes and wormholes visible to empire empire_id; the map contains keys that are IDs of connected systems, and bool values indicating whether each is a starlane (false) or a wormhole (true)
int LastTurnBattleHere () const
fleets are inserted into system
const std::string & OverlayTexture () const
fleets are inserted into system
double OverlaySize () const
size in universe units
Structors
template<typename T >
void boost::python::detail::value_destroyer (T const volatile *p)
Returns new copy of this System.
System (StarType star, const std::string &name, double x, double y)
Returns new copy of this System.
~System ()
Returns new copy of this System.
System ()
Returns new copy of this System.
System (StarType star, const std::map< int, bool > &lanes_and_holes, const std::string &name, double x, double y)
Returns new copy of this System.
System * Clone (int empire_id=ALL_EMPIRES) const override
Returns new copy of this System.
Additional Inherited Members
Public Types inherited from UniverseObject
typedef flat_map< MeterType, Meter, std::less< MeterType > > MeterMap
typedef boost::signals2::signal< void(), blocking_combiner< boost::signals2::optional_last_value< void > > > StateChangedSignalType
typedef StateChangedSignalType::slot_type StateChangedSlotType
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Member Functions inherited from UniverseObject
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (std::shared_ptr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
void Init ()
adds stealth meter
UniverseObject ()
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
UniverseObject (const std::string name, double x, double y)
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system.
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
contains UniverseObjects and connections to other systems (starlanes and wormholes).
All systems are UniversObjects contained within the universe, and (nearly) all systems also contain UniverseObjects. Systems are searchable using arbirary predicates, much in the same way that Universes are. Each System consists of a star and 0 or more orbits. UniversObjects can be placed in the system "at large" or in a particular orbit. No checking is done to determine whether an object is orbit-bound (like a Planet) or not (like a Fleet) when placing them with the Insert() functions. Iteration is available over all starlanes and wormholes (together), all system objects, all free system objects (those not in an orbit), and all objects in a paricular orbit.
Constructor & Destructor Documentation
System() [1/3]
System::System () explicit protected
Returns new copy of this System.
Referenced by Clone().
System() [2/3]
System::System (StarType star, const std::string & name, double x, double y)
Returns new copy of this System.
References UniverseObject::Init(), INVALID_OBJECT_ID, INVALID_STAR_TYPE, m_orbits, m_star, and anonymous_namespace{System.h}::SYSTEM_ORBITS.
System() [3/3]
System::System (StarType star, const std::map< int, bool > & lanes_and_holes, const std::string & name, double x, double y) protected
Returns new copy of this System.
References UniverseObject::ID(), UniverseObject::Init(), INVALID_OBJECT_ID, INVALID_STAR_TYPE, m_orbits, m_star, UniverseObject::SetSystem(), and anonymous_namespace{System.h}::SYSTEM_ORBITS.
~System()
System::~System () inline
Returns new copy of this System.
References ALL_EMPIRES, and Fleet::Clone().
Member Function Documentation
Accept()
std::shared_ptr< UniverseObject > System::Accept (const UniverseObjectVisitor & visitor) const override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
References UniverseObjectVisitor::Visit().
AddStarlane()
void System::AddStarlane (int id)
adds a starlane between this system and the system with ID number id.
Note
Adding a starlane to a system to which there is already a wormhole erases the wormhole; you may want to check for a wormhole before calling this function.
References HasStarlaneTo(), UniverseObject::ID(), m_starlanes_wormholes, UniverseObject::Name(), UniverseObject::StateChangedSignal, and TraceLogger.
Referenced by Effect::AddStarlanes::Execute().
AddWormhole()
void System::AddWormhole (int id)
adds a wormhole between this system and the system with ID number id
Note
Adding a wormhole to a system to which there is already a starlane erases the starlane; you may want to check for a starlane before calling this function.
References HasWormholeTo(), UniverseObject::ID(), m_starlanes_wormholes, and UniverseObject::StateChangedSignal.
ApparentName()
const std::string & System::ApparentName (int empire_id, bool blank_unexplored_and_none = false) const
returns the name to display for players for this system.
While all systems may have a proper name assigned, if they contain no planets or star, then "Deep Space" (or its translation) Or, a system that is not yet explored might be "Unexplored Region", rather than an empty string for the name. This is distinct from PublicName functions, which filter the name based on ownership.
References ALL_EMPIRES, anonymous_namespace{Empire.cpp}::EMPTY_STRING, Universe::GetObjectVisibilityTurnMapByEmpire(), GetUniverse(), UniverseObject::ID(), INVALID_STAR_TYPE, m_star, Objects(), UniverseObject::PublicName(), STAR_NONE, and UserString().
Referenced by anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), and FleetButton::LayoutIcons().
BuildingIDs()
const std::set<int>& System::BuildingIDs () const inline
fleets are inserted into system
Referenced by FreeOrionPython::WrapUniverseClasses().
Clone()
System * System::Clone (int empire_id = ALL_EMPIRES) const override protected virtual
Returns new copy of this System.
Implements UniverseObject.
References Copy(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), and System().
ContainedBy()
bool System::ContainedBy (int object_id) const inline override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
References Fleet::Accept().
ContainedObjectIDs()
const std::set< int > & System::ContainedObjectIDs () const override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
References m_objects.
Contains()
bool System::Contains (int object_id) const override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and m_objects.
Copy()
void System::Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) override virtual
Adding owner to system objects is a no-op.
Implements UniverseObject.
References UniverseObject::Copy(), ErrorLogger, Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), INVALID_OBJECT_ID, m_buildings, m_fields, m_fleets, m_last_turn_battle_here, UniverseObject::m_name, m_objects, m_orbits, m_planets, m_ships, m_star, and m_starlanes_wormholes.
Referenced by Clone().
Dump()
std::string System::Dump (unsigned short ntabs = 0) const override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
References UniverseObject::Dump(), INVALID_OBJECT_ID, m_last_turn_battle_here, m_objects, m_orbits, m_star, and m_starlanes_wormholes.
FieldIDs()
const std::set<int>& System::FieldIDs () const inline
fleets are inserted into system
Referenced by FreeOrionPython::WrapUniverseClasses().
FleetIDs()
const std::set<int>& System::FleetIDs () const inline
fleets are inserted into system
Referenced by anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), and FreeOrionPython::WrapUniverseClasses().
FreeOrbits()
std::set< int > System::FreeOrbits () const
returns the set of orbit numbers that are unoccupied
References INVALID_OBJECT_ID, and m_orbits.
Referenced by Insert().
GetStarType()
StarType System::GetStarType () const inline
returns the type of star for this system
Referenced by ValueRef::Variable< ToType >::Eval(), and FreeOrionPython::WrapUniverseClasses().
HasStarlaneTo()
bool System::HasStarlaneTo (int id) const
returns true if there is a starlane from this system to the system with ID number id
References m_starlanes_wormholes.
Referenced by AddStarlane(), RemoveStarlane(), and FreeOrionPython::WrapUniverseClasses().
HasWormholeTo()
bool System::HasWormholeTo (int id) const
returns true if there is a wormhole from this system to the system with ID number id
References m_starlanes_wormholes.
Referenced by AddWormhole(), RemoveWormhole(), and FreeOrionPython::WrapUniverseClasses().
Insert()
void System::Insert (std::shared_ptr< UniverseObject > obj, int orbit = -1)
adds an object to this system.
References CurrentTurn(), DebugLogger, ErrorLogger, FleetsInsertedSignal, FreeOrbits(), UniverseObject::ID(), INVALID_OBJECT_ID, m_buildings, m_fields, m_fleets, m_objects, m_orbits, m_planets, m_ships, OrbitOccupied(), OrbitOfPlanet(), UniverseObject::StateChangedSignal, UniverseObject::X(), and UniverseObject::Y().
Referenced by Effect::CreateBuilding::Execute(), and Effect::CreateField::Execute().
LastTurnBattleHere()
int System::LastTurnBattleHere () const inline
fleets are inserted into system
Referenced by FreeOrionPython::WrapUniverseClasses().
NextOlderStarType()
StarType System::NextOlderStarType () const
fleets are inserted into system
References INVALID_STAR_TYPE, m_star, and STAR_RED.
Referenced by ValueRef::Variable< ToType >::Eval().
NextYoungerStarType()
StarType System::NextYoungerStarType () const
fleets are inserted into system
References INVALID_STAR_TYPE, m_star, STAR_BLUE, and STAR_RED.
Referenced by ValueRef::Variable< ToType >::Eval().
NumStarlanes()
int System::NumStarlanes () const
returns the number of starlanes from this system to other systems
References m_starlanes_wormholes.
Referenced by FreeOrionPython::WrapUniverseClasses().
NumWormholes()
int System::NumWormholes () const
returns the number of wormholes from this system to other systems
References m_starlanes_wormholes.
Referenced by FreeOrionPython::WrapUniverseClasses().
ObjectIDs()
const std::set<int>& System::ObjectIDs () const inline
fleets are inserted into system
Referenced by Condition::InOrIsSystem::GetDefaultInitialCandidateObjects().
ObjectType()
UniverseObjectType System::ObjectType () const override virtual
fleets are inserted into system
Reimplemented from UniverseObject.
Referenced by MapWnd::SystemRightClicked().
OrbitOccupied()
bool System::OrbitOccupied (int orbit) const
returns true if there is an object in orbit
References INVALID_OBJECT_ID, and m_orbits.
Referenced by Insert().
OrbitOfPlanet()
int System::OrbitOfPlanet (int object_id) const
returns the orbit ID in which the planet with object_id is located, or -1 the specified ID is not a planet in an orbit of this system
References INVALID_OBJECT_ID, and m_orbits.
Referenced by Insert().
Orbits()
int System::Orbits () const inline
returns the number of orbits in this system
OverlaySize()
double System::OverlaySize () const inline
size in universe units
OverlayTexture()
const std::string& System::OverlayTexture () const inline
fleets are inserted into system
Owner()
int System::Owner () const override virtual
Systems are unowned unless at least one planet is owned by an empire and no other empire owns any planets in the system.
Reimplemented from UniverseObject.
References ALL_EMPIRES, m_planets, and Objects().
PlanetIDs()
const std::set<int>& System::PlanetIDs () const inline
fleets are inserted into system
Referenced by anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), SidePanel::PlanetSelectable(), and FreeOrionPython::WrapUniverseClasses().
PlanetIDsByOrbit()
const std::vector<int>& System::PlanetIDsByOrbit () const inline
fleets are inserted into system
PlanetInOrbit()
int System::PlanetInOrbit (int orbit) const
returns the ID of the planet in the specified orbit, or INVALID_OBJECT_ID if there is no planet in that orbit or it is an invalid orbit
References INVALID_OBJECT_ID, and m_orbits.
Remove()
void System::Remove (int id)
removes the object with ID number id from this system.
References FleetsRemovedSignal, INVALID_OBJECT_ID, m_buildings, m_fields, m_fleets, m_objects, m_orbits, m_planets, m_ships, Objects(), and UniverseObject::StateChangedSignal.
Referenced by anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), Effect::MoveTo::Execute(), Effect::MoveTowards::Execute(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), and anonymous_namespace{ServerApp.cpp}::HandleScrapping().
RemoveStarlane()
bool System::RemoveStarlane (int id)
removes a starlane between this system and the system with ID number id. Returns false if there was no starlane from this system to system id.
References HasStarlaneTo(), m_starlanes_wormholes, and UniverseObject::StateChangedSignal.
RemoveWormhole()
bool System::RemoveWormhole (int id)
removes a wormhole between this system and the system with ID number id. Returns false if there was no wormhole from this system to system id.
References HasWormholeTo(), m_starlanes_wormholes, and UniverseObject::StateChangedSignal.
ResetTargetMaxUnpairedMeters()
void System::ResetTargetMaxUnpairedMeters () override virtual
Adding owner to system objects is a no-op.
Reimplemented from UniverseObject.
References UniverseObject::GetMeter(), METER_STEALTH, and UniverseObject::ResetTargetMaxUnpairedMeters().
serialize()
template<typename Archive > template void System::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References Universe::m_objects.
SetLastTurnBattleHere()
void System::SetLastTurnBattleHere (int turn)
Sets the last turn there was a battle at this system.
References m_last_turn_battle_here.
SetOverlayTexture()
void System::SetOverlayTexture (const std::string & texture, double size)
Adding owner to system objects is a no-op.
References m_overlay_size, m_overlay_texture, and UniverseObject::StateChangedSignal.
SetOwner()
void System::SetOwner (int id) inline override virtual
Adding owner to system objects is a no-op.
Reimplemented from UniverseObject.
References Fleet::ResetTargetMaxUnpairedMeters().
Referenced by anonymous_namespace{ServerApp.cpp}::HandleGifting().
SetStarType()
void System::SetStarType (StarType type)
sets the type of the star in this Systems to StarType
References ErrorLogger, INVALID_STAR_TYPE, m_star, and UniverseObject::StateChangedSignal.
ShipIDs()
const std::set<int>& System::ShipIDs () const inline
fleets are inserted into system
References Fleet::m_ships.
Referenced by FleetWnd::FleetRightClicked(), and FreeOrionPython::WrapUniverseClasses().
StarlanesWormholes()
const std::map< int, bool > & System::StarlanesWormholes () const
returns map of all starlanes and wormholes; map contains keys that are IDs of connected systems, and bool values indicating whether each is a starlane (false) or a wormhole (true)
References m_starlanes_wormholes.
Referenced by FreeOrionPython::WrapUniverseClasses().
SystemID()
int System::SystemID () const inline override virtual
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
Reimplemented from UniverseObject.
References Fleet::ContainedObjectIDs(), Fleet::Contains(), Fleet::Dump(), UniverseObject::ID(), and Fleet::ObjectType().
VisibleStarlanesWormholes()
std::map< int, bool > System::VisibleStarlanesWormholes (int empire_id) const
returns a map of the starlanes and wormholes visible to empire empire_id; the map contains keys that are IDs of connected systems, and bool values indicating whether each is a starlane (false) or a wormhole (true)
References ALL_EMPIRES, ErrorLogger, ObjectMap::find(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), INVALID_OBJECT_ID, m_starlanes_wormholes, and Universe::Objects().
Friends And Related Function Documentation
boost::python::detail::value_destroyer
template<typename T > void boost::python::detail::value_destroyer (T const volatile * p) friend
Returns new copy of this System.
boost::serialization::access
friend class boost::serialization::access friend
ObjectMap
friend class ObjectMap friend
Universe
friend class Universe friend
Member Data Documentation
FleetsInsertedSignal
boost::signals2::signal<void (const std::vector<std::shared_ptr<Fleet>>&)> System::FleetsInsertedSignal mutable
fleets are inserted into system
Referenced by Insert().
FleetsRemovedSignal
boost::signals2::signal<void (const std::vector<std::shared_ptr<Fleet>>&)> System::FleetsRemovedSignal mutable
fleets are removed from system
Referenced by Remove().
m_buildings
std::set<int> System::m_buildings private
Referenced by Copy(), Insert(), and Remove().
m_fields
std::set<int> System::m_fields private
Referenced by Copy(), Insert(), and Remove().
m_fleets
std::set<int> System::m_fleets private
Referenced by Copy(), Insert(), and Remove().
m_last_turn_battle_here
int System::m_last_turn_battle_here = INVALID_GAME_TURN private
the turn on which there was last a battle in this system
Referenced by Copy(), Dump(), and SetLastTurnBattleHere().
m_objects
std::set<int> System::m_objects private
Referenced by ObjectMap::AuditContainment(), ContainedObjectIDs(), Contains(), Copy(), Dump(), Insert(), and Remove().
m_orbits
std::vector<int> System::m_orbits = std::vector<int>(SYSTEM_ORBITS, INVALID_OBJECT_ID) private
indexed by orbit number, indicates the id of the planet in that orbit
Referenced by Copy(), Dump(), FreeOrbits(), Insert(), OrbitOccupied(), OrbitOfPlanet(), PlanetInOrbit(), Remove(), and System().
m_overlay_size
double System::m_overlay_size = 1.0 private
Referenced by SetOverlayTexture().
m_overlay_texture
std::string System::m_overlay_texture private
Referenced by SetOverlayTexture().
m_planets
std::set<int> System::m_planets private
Referenced by Copy(), Insert(), Owner(), and Remove().
m_ships
std::set<int> System::m_ships private
Referenced by Copy(), Insert(), and Remove().
m_star
StarType System::m_star private
Referenced by ApparentName(), Copy(), Dump(), NextOlderStarType(), NextYoungerStarType(), SetStarType(), and System().
m_starlanes_wormholes
std::map<int, bool> System::m_starlanes_wormholes private
the ints represent the IDs of other connected systems; the bools indicate whether the connection is a wormhole (true) or a starlane (false)
Referenced by AddStarlane(), AddWormhole(), Copy(), Dump(), HasStarlaneTo(), HasWormholeTo(), NumStarlanes(), NumWormholes(), RemoveStarlane(), RemoveWormhole(), StarlanesWormholes(), and VisibleStarlanesWormholes().
The documentation for this class was generated from the following files:
System.h
System.cpp
SerializeUniverse.cpp