FreeOrion: Effect::SetEmpireMeter Class Reference
Effect::SetEmpireMeter Class Reference final
Sets the indicated meter on the empire with the indicated id to the indicated value.
#include <Effects.h>
Public Member Functions
SetEmpireMeter (const std::string &meter, std::unique_ptr< ValueRef::ValueRef< double >> &&value)
SetEmpireMeter (std::unique_ptr< ValueRef::ValueRef< int >> &&empire_id, const std::string &meter, std::unique_ptr< ValueRef::ValueRef< double >> &&value)
std::string Dump (unsigned short ntabs=0) const override
void Execute (ScriptingContext &context) const override
void Execute (ScriptingContext &context, const TargetSet &targets) const override
void Execute (ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const override
unsigned int GetCheckSum () const override
bool IsEmpireMeterEffect () const override
bool IsMeterEffect () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::Effect
virtual ~Effect ()
void Execute (ScriptingContext &context, const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_empire_id
std::string m_meter
std::unique_ptr< ValueRef::ValueRef< double > > m_value
Friends
class boost::serialization::access
Detailed Description
Sets the indicated meter on the empire with the indicated id to the indicated value.
If meter is not a valid meter for empires, does nothing.
Constructor & Destructor Documentation
SetEmpireMeter() [1/2]
Effect::SetEmpireMeter::SetEmpireMeter (const std::string & meter, std::unique_ptr< ValueRef::ValueRef< double >> && value)
SetEmpireMeter() [2/2]
Effect::SetEmpireMeter::SetEmpireMeter (std::unique_ptr< ValueRef::ValueRef< int >> && empire_id, const std::string & meter, std::unique_ptr< ValueRef::ValueRef< double >> && value)
Member Function Documentation
Dump()
std::string Effect::SetEmpireMeter::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::Effect.
References DumpIndent(), m_empire_id, m_meter, and m_value.
Execute() [1/3]
void Effect::SetEmpireMeter::Execute (ScriptingContext & context) const override virtual
Implements Effect::Effect.
References Meter::Current(), DebugLogger, ScriptingContext::effect_target, ErrorLogger, GetEmpire(), Empire::GetMeter(), m_empire_id, m_meter, m_value, Empire::Name(), and Meter::SetCurrent().
Referenced by Execute().
Execute() [2/3]
void Effect::SetEmpireMeter::Execute (ScriptingContext & context, const TargetSet & targets) const override virtual
Reimplemented from Effect::Effect.
References ErrorLogger, Effect::Effect::Execute(), m_empire_id, m_meter, and m_value.
Execute() [3/3]
void Effect::SetEmpireMeter::Execute (ScriptingContext & context, const TargetSet & targets, AccountingMap * accounting_map, const EffectCause & effect_cause, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const override virtual
Reimplemented from Effect::Effect.
References Execute().
GetCheckSum()
unsigned int Effect::SetEmpireMeter::GetCheckSum () const override virtual
Reimplemented from Effect::Effect.
References CheckSums::CheckSumCombine(), m_empire_id, m_meter, m_value, and TraceLogger.
IsEmpireMeterEffect()
bool Effect::SetEmpireMeter::IsEmpireMeterEffect () const inline override virtual
Reimplemented from Effect::Effect.
IsMeterEffect()
bool Effect::SetEmpireMeter::IsMeterEffect () const inline override virtual
Reimplemented from Effect::Effect.
serialize()
template<typename Archive > void Effect::SetEmpireMeter::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::SetEmpireMeter::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::Effect.
References m_empire_id, and m_value.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_empire_id
std::unique_ptr<ValueRef::ValueRef<int> > Effect::SetEmpireMeter::m_empire_id private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
m_meter
std::string Effect::SetEmpireMeter::m_meter private
Referenced by Dump(), Execute(), and GetCheckSum().
m_value
std::unique_ptr<ValueRef::ValueRef<double> > Effect::SetEmpireMeter::m_value private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effects.h
Effects.cpp