FreeOrion: FleetPlan Class Reference
FleetPlan Class Reference
A combination of names of ShipDesign that can be put together to make a fleet of ships, and a name for such a fleet, loaded from default/scripting/starting_unlocks/fleets.inf ShipDesign names refer to designs listed in default/scripting/ship_designs.
#include <UniverseGenerator.h>
Public Member Functions
FleetPlan (const std::string &fleet_name, const std::vector< std::string > &ship_design_names, bool lookup_name_userstring=false)
FleetPlan ()
virtual ~FleetPlan ()
const std::string & Name () const
const std::vector< std::string > & ShipDesigns () const
Protected Attributes
std::string m_name
bool m_name_in_stringtable
std::vector< std::string > m_ship_designs
Detailed Description
A combination of names of ShipDesign that can be put together to make a fleet of ships, and a name for such a fleet, loaded from default/scripting/starting_unlocks/fleets.inf ShipDesign names refer to designs listed in default/scripting/ship_designs.
Useful for saving or specifying prearranged combinations of prearranged ShipDesigns to automatically put together, such as during universe creation.
Constructor & Destructor Documentation
FleetPlan::FleetPlan (const std::string & fleet_name, const std::vector< std::string > & ship_design_names, bool lookup_name_userstring = false) inline
FleetPlan::FleetPlan () inline
virtual FleetPlan::~FleetPlan () inline virtual
References Name().
Member Function Documentation
const std::string & FleetPlan::Name () const
References UserString().
Referenced by ~FleetPlan().
const std::vector<std::string>& FleetPlan::ShipDesigns () const inline
References m_ship_designs.
Member Data Documentation
std::string FleetPlan::m_name protected
bool FleetPlan::m_name_in_stringtable protected
std::vector<std::string> FleetPlan::m_ship_designs protected
Referenced by ShipDesigns().
The documentation for this class was generated from the following files:
UniverseGenerator.h
UniverseGenerator.cpp