FreeOrion: Effect::AddStarlanes Class Reference
Effect::AddStarlanes Class Reference final
Creates starlane(s) between the target system and systems that match other_lane_endpoint_condition.
#include <Effect.h>
Public Member Functions
AddStarlanes (std::unique_ptr< Condition::ConditionBase > &&other_lane_endpoint_condition)
std::string Dump (unsigned short ntabs=0) const override
void Execute (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets, AccountingMap *accounting_map, const EffectCause &effect_cause, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual bool IsAppearanceEffect () const
virtual bool IsConditionalEffect () const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< Condition::ConditionBase > m_other_lane_endpoint_condition
Friends
class boost::serialization::access
Detailed Description
Creates starlane(s) between the target system and systems that match other_lane_endpoint_condition.
Constructor & Destructor Documentation
AddStarlanes()
Effect::AddStarlanes::AddStarlanes (std::unique_ptr< Condition::ConditionBase > && other_lane_endpoint_condition) explicit
Member Function Documentation
Dump()
std::string Effect::AddStarlanes::Dump (unsigned short ntabs = 0) const override virtual
Implements Effect::EffectBase.
References DumpIndent(), and m_other_lane_endpoint_condition.
Execute()
void Effect::AddStarlanes::Execute (const ScriptingContext & context) const override virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ErrorLogger, GetSystem(), and m_other_lane_endpoint_condition.
GetCheckSum()
unsigned int Effect::AddStarlanes::GetCheckSum () const override virtual
Reimplemented from Effect::EffectBase.
References CheckSums::CheckSumCombine(), m_other_lane_endpoint_condition, and TraceLogger.
serialize()
template<class Archive > void Effect::AddStarlanes::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Effect::AddStarlanes::SetTopLevelContent (const std::string & content_name) override virtual
Implements Effect::EffectBase.
References m_other_lane_endpoint_condition.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_other_lane_endpoint_condition
std::unique_ptr<Condition::ConditionBase> Effect::AddStarlanes::m_other_lane_endpoint_condition private
Referenced by Dump(), Execute(), GetCheckSum(), and SetTopLevelContent().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp