FreeOrion: GalaxySetupPanel Class Reference
GalaxySetupPanel Class Reference
Encapsulates the galaxy setup options so that they may be reused in the GalaxySetupWnd and the MultiPlayerLobbyWnd.
#include <GalaxySetupWnd.h>
Public Member Functions
GalaxySetupPanel (GG::X w=GG::X(FontBasedUpscale(305)), GG::Y h=GG::Y(330))
void CompleteConstruction () override
void Disable (bool b=true) override
GalaxySetupOption GetAge () const
Returns the age of the galaxy.
Aggression GetAIAggression () const
Returns the maximum AI aggression level.
GalaxySetupOption GetMonsterFrequency () const
Returns the frequency of space monsters.
GalaxySetupOption GetNativeFrequency () const
Returns the frequency of natives.
GalaxySetupOption GetPlanetDensity () const
Returns the density of planets within systems.
const std::string & GetSeed () const
Returns string version of seed. This value is converted to a number or (if that fails) hashed to get the actual seed value.
void GetSetupData (GalaxySetupData &setup_data) const
fills values in setup_data from the panel's current state
Shape GetShape () const
Returns the shape of the galaxy.
GalaxySetupOption GetSpecialsFrequency () const
Returns the rarity of planetary and system specials.
GalaxySetupOption GetStarlaneFrequency () const
Returns the frequency of starlanes in the galaxy.
std::shared_ptr< GG::Texture > PreviewImage () const
Returns the current preview image texture.
void Render () override
void SetFromSetupData (const GalaxySetupData &setup_data)
sets the controls from a GalaxySetupData
void SetSeed (const std::string &seed, bool inhibit_single=false)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
int Systems () const
Returns the number of star systems to use in generating the galaxy.
Static Public Member Functions
static const GG::X DefaultWidth ()
Public Attributes
boost::signals2::signal< void(std::shared_ptr< GG::Texture >)> ImageChangedSignal
the image changed signal object for this GalaxySetupPanel
boost::signals2::signal< void()> SettingsChangedSignal
the settings changed signal object for this GalaxySetupPanel
Private Member Functions
void DoLayout ()
void RandomClicked ()
void SettingChanged ()
void ShapeChanged (GG::ListBox::iterator it)
Private Attributes
std::shared_ptr< GG::Label > m_ai_aggression_label
std::shared_ptr< GG::DropDownList > m_ai_aggression_list
The max aggression choices for AI opponents;.
std::shared_ptr< GG::Label > m_galaxy_ages_label
std::shared_ptr< GG::DropDownList > m_galaxy_ages_list
The possible ages for the galaxy;.
std::shared_ptr< GG::Label > m_galaxy_shapes_label
std::shared_ptr< GG::DropDownList > m_galaxy_shapes_list
The possible shapes for the galaxy;.
std::shared_ptr< GG::Label > m_monster_freq_label
std::shared_ptr< GG::DropDownList > m_monster_freq_list
The frequency of monsters;.
std::shared_ptr< GG::Label > m_native_freq_label
std::shared_ptr< GG::DropDownList > m_native_freq_list
The frequency of natives;.
std::shared_ptr< GG::Label > m_planet_density_label
std::shared_ptr< GG::DropDownList > m_planet_density_list
The density of planets in each system;.
std::shared_ptr< GG::Button > m_random
Random seed button;.
std::string m_seed
std::shared_ptr< CUIEdit > m_seed_edit
The seed used in the generation of the galaxy;.
std::shared_ptr< GG::Label > m_seed_label
std::shared_ptr< GG::Label > m_specials_freq_label
std::shared_ptr< GG::DropDownList > m_specials_freq_list
The frequency of specials in systems and on planets;.
std::shared_ptr< GG::Label > m_starlane_freq_label
std::shared_ptr< GG::DropDownList > m_starlane_freq_list
The frequency of starlanes in the galaxy;.
std::shared_ptr< GG::Label > m_stars_label
std::shared_ptr< GG::Spin< int > > m_stars_spin
The number of stars to include in the galaxy;.
std::vector< std::shared_ptr< GG::Texture > > m_textures
Textures for galaxy previews.
Detailed Description
Encapsulates the galaxy setup options so that they may be reused in the GalaxySetupWnd and the MultiPlayerLobbyWnd.
Constructor & Destructor Documentation
GalaxySetupPanel()
GalaxySetupPanel::GalaxySetupPanel (GG::X w = GG::X(FontBasedUpscale(305)), GG::Y h = GG::Y(330))
Member Function Documentation
CompleteConstruction()
void GalaxySetupPanel::CompleteConstruction () override
References ClientUI::ArtDir(), DebugLogger, DoLayout(), OptionsDB::Get(), GetOptionsDB(), GetSeed(), ClientUI::GetTexture(), m_ai_aggression_label, m_ai_aggression_list, m_galaxy_ages_label, m_galaxy_ages_list, m_galaxy_shapes_label, m_galaxy_shapes_list, m_monster_freq_label, m_monster_freq_list, m_native_freq_label, m_native_freq_list, m_planet_density_label, m_planet_density_list, m_random, m_seed, m_seed_edit, m_seed_label, m_specials_freq_label, m_specials_freq_list, m_starlane_freq_label, m_starlane_freq_list, m_stars_label, m_stars_spin, m_textures, RandomClicked(), SetSeed(), SettingChanged(), SettingsChangedSignal, ShapeChanged(), TraceLogger, and UserString().
DefaultWidth()
const GG::X GalaxySetupPanel::DefaultWidth () static
References FontBasedUpscale().
Referenced by GalaxySetupWnd::CompleteConstruction(), and GalaxySetupWnd::DoLayout().
Disable()
void GalaxySetupPanel::Disable (bool b = true) override
DoLayout()
void GalaxySetupPanel::DoLayout () private
References anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_HEIGHT, anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_MARGIN, anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN, ClientUI::GetFont(), m_ai_aggression_label, m_ai_aggression_list, m_galaxy_ages_label, m_galaxy_ages_list, m_galaxy_shapes_label, m_galaxy_shapes_list, m_monster_freq_label, m_monster_freq_list, m_native_freq_label, m_native_freq_list, m_planet_density_label, m_planet_density_list, m_random, m_seed_edit, m_seed_label, m_specials_freq_label, m_specials_freq_list, m_starlane_freq_label, m_starlane_freq_list, m_stars_label, m_stars_spin, anonymous_namespace{GalaxySetupWnd.cpp}::PANEL_CONTROL_SPACING, and ClientUI::Pts().
Referenced by CompleteConstruction(), and SizeMove().
GetAge()
GalaxySetupOption GalaxySetupPanel::GetAge () const
Returns the age of the galaxy.
References m_galaxy_ages_list.
Referenced by GetSetupData().
GetAIAggression()
Aggression GalaxySetupPanel::GetAIAggression () const
Returns the maximum AI aggression level.
References m_ai_aggression_list.
Referenced by GetSetupData().
GetMonsterFrequency()
GalaxySetupOption GalaxySetupPanel::GetMonsterFrequency () const
Returns the frequency of space monsters.
References m_monster_freq_list.
Referenced by GetSetupData().
GetNativeFrequency()
GalaxySetupOption GalaxySetupPanel::GetNativeFrequency () const
Returns the frequency of natives.
References m_native_freq_list.
Referenced by GetSetupData().
GetPlanetDensity()
GalaxySetupOption GalaxySetupPanel::GetPlanetDensity () const
Returns the density of planets within systems.
References m_planet_density_list.
Referenced by GetSetupData().
GetSeed()
const std::string & GalaxySetupPanel::GetSeed () const
Returns string version of seed. This value is converted to a number or (if that fails) hashed to get the actual seed value.
References m_seed.
Referenced by CompleteConstruction(), and GetSetupData().
GetSetupData()
void GalaxySetupPanel::GetSetupData (GalaxySetupData & setup_data) const
fills values in setup_data from the panel's current state
References GalaxySetupData::age, GalaxySetupData::ai_aggr, GetAge(), GetAIAggression(), GetMonsterFrequency(), GetNativeFrequency(), GetPlanetDensity(), GetSeed(), GetShape(), GetSpecialsFrequency(), GetStarlaneFrequency(), GalaxySetupData::monster_freq, GalaxySetupData::native_freq, GalaxySetupData::planet_density, GalaxySetupData::SetSeed(), GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, and Systems().
GetShape()
Shape GalaxySetupPanel::GetShape () const
Returns the shape of the galaxy.
References m_galaxy_shapes_list.
Referenced by GetSetupData(), and PreviewImage().
GetSpecialsFrequency()
GalaxySetupOption GalaxySetupPanel::GetSpecialsFrequency () const
Returns the rarity of planetary and system specials.
References m_specials_freq_list.
Referenced by GetSetupData().
GetStarlaneFrequency()
GalaxySetupOption GalaxySetupPanel::GetStarlaneFrequency () const
Returns the frequency of starlanes in the galaxy.
References m_starlane_freq_list.
Referenced by GetSetupData().
PreviewImage()
std::shared_ptr< GG::Texture > GalaxySetupPanel::PreviewImage () const
Returns the current preview image texture.
References GetShape(), and m_textures.
RandomClicked()
void GalaxySetupPanel::RandomClicked () private
References GetOptionsDB(), m_seed, and SetSeed().
Referenced by CompleteConstruction().
Render()
void GalaxySetupPanel::Render () inline override
References GameRulesPanel::Disable(), GameRulesPanel::DoLayout(), and GameRulesPanel::SettingChanged().
SetFromSetupData()
void GalaxySetupPanel::SetFromSetupData (const GalaxySetupData & setup_data)
sets the controls from a GalaxySetupData
References GalaxySetupData::age, GalaxySetupData::ai_aggr, m_ai_aggression_list, m_galaxy_ages_list, m_galaxy_shapes_list, m_monster_freq_list, m_native_freq_list, m_planet_density_list, m_specials_freq_list, m_starlane_freq_list, m_stars_spin, GalaxySetupData::monster_freq, GalaxySetupData::native_freq, GalaxySetupData::planet_density, GalaxySetupData::seed, SetSeed(), GalaxySetupData::shape, ShapeChanged(), GalaxySetupData::size, GalaxySetupData::specials_freq, and GalaxySetupData::starlane_freq.
SetSeed()
void GalaxySetupPanel::SetSeed (const std::string & seed, bool inhibit_single = false)
References m_seed, m_seed_edit, SettingChanged(), and UserString().
Referenced by CompleteConstruction(), RandomClicked(), and SetFromSetupData().
SettingChanged()
void GalaxySetupPanel::SettingChanged () private
References SettingsChangedSignal.
Referenced by CompleteConstruction(), and SetSeed().
ShapeChanged()
void GalaxySetupPanel::ShapeChanged (GG::ListBox::iterator it) private
References ImageChangedSignal, m_galaxy_shapes_list, and m_textures.
Referenced by CompleteConstruction(), and SetFromSetupData().
SizeMove()
void GalaxySetupPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
Systems()
int GalaxySetupPanel::Systems () const
Returns the number of star systems to use in generating the galaxy.
References m_stars_spin.
Referenced by GetSetupData().
Member Data Documentation
ImageChangedSignal
boost::signals2::signal<void (std::shared_ptr<GG::Texture>)> GalaxySetupPanel::ImageChangedSignal mutable
the image changed signal object for this GalaxySetupPanel
Referenced by ShapeChanged().
m_ai_aggression_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_ai_aggression_label private
Referenced by CompleteConstruction(), and DoLayout().
m_ai_aggression_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_ai_aggression_list private
The max aggression choices for AI opponents;.
Referenced by CompleteConstruction(), DoLayout(), GetAIAggression(), and SetFromSetupData().
m_galaxy_ages_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_galaxy_ages_label private
Referenced by CompleteConstruction(), and DoLayout().
m_galaxy_ages_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_galaxy_ages_list private
The possible ages for the galaxy;.
Referenced by CompleteConstruction(), DoLayout(), GetAge(), and SetFromSetupData().
m_galaxy_shapes_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_galaxy_shapes_label private
Referenced by CompleteConstruction(), and DoLayout().
m_galaxy_shapes_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_galaxy_shapes_list private
The possible shapes for the galaxy;.
Referenced by CompleteConstruction(), DoLayout(), GetShape(), SetFromSetupData(), and ShapeChanged().
m_monster_freq_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_monster_freq_label private
Referenced by CompleteConstruction(), and DoLayout().
m_monster_freq_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_monster_freq_list private
The frequency of monsters;.
Referenced by CompleteConstruction(), DoLayout(), GetMonsterFrequency(), and SetFromSetupData().
m_native_freq_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_native_freq_label private
Referenced by CompleteConstruction(), and DoLayout().
m_native_freq_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_native_freq_list private
The frequency of natives;.
Referenced by CompleteConstruction(), DoLayout(), GetNativeFrequency(), and SetFromSetupData().
m_planet_density_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_planet_density_label private
Referenced by CompleteConstruction(), and DoLayout().
m_planet_density_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_planet_density_list private
The density of planets in each system;.
Referenced by CompleteConstruction(), DoLayout(), GetPlanetDensity(), and SetFromSetupData().
m_random
std::shared_ptr<GG::Button> GalaxySetupPanel::m_random private
Random seed button;.
Referenced by CompleteConstruction(), and DoLayout().
m_seed
std::string GalaxySetupPanel::m_seed private
Referenced by CompleteConstruction(), GetSeed(), RandomClicked(), and SetSeed().
m_seed_edit
std::shared_ptr<CUIEdit> GalaxySetupPanel::m_seed_edit private
The seed used in the generation of the galaxy;.
Referenced by CompleteConstruction(), DoLayout(), and SetSeed().
m_seed_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_seed_label private
Referenced by CompleteConstruction(), and DoLayout().
m_specials_freq_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_specials_freq_label private
Referenced by CompleteConstruction(), and DoLayout().
m_specials_freq_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_specials_freq_list private
The frequency of specials in systems and on planets;.
Referenced by CompleteConstruction(), DoLayout(), GetSpecialsFrequency(), and SetFromSetupData().
m_starlane_freq_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_starlane_freq_label private
Referenced by CompleteConstruction(), and DoLayout().
m_starlane_freq_list
std::shared_ptr<GG::DropDownList> GalaxySetupPanel::m_starlane_freq_list private
The frequency of starlanes in the galaxy;.
Referenced by CompleteConstruction(), DoLayout(), GetStarlaneFrequency(), and SetFromSetupData().
m_stars_label
std::shared_ptr<GG::Label> GalaxySetupPanel::m_stars_label private
Referenced by CompleteConstruction(), and DoLayout().
m_stars_spin
std::shared_ptr<GG::Spin<int> > GalaxySetupPanel::m_stars_spin private
The number of stars to include in the galaxy;.
Referenced by CompleteConstruction(), DoLayout(), SetFromSetupData(), and Systems().
m_textures
std::vector<std::shared_ptr<GG::Texture> > GalaxySetupPanel::m_textures private
Textures for galaxy previews.
Referenced by CompleteConstruction(), PreviewImage(), and ShapeChanged().
SettingsChangedSignal
boost::signals2::signal<void ()> GalaxySetupPanel::SettingsChangedSignal mutable
the settings changed signal object for this GalaxySetupPanel
Referenced by CompleteConstruction(), and SettingChanged().
The documentation for this class was generated from the following files:
GalaxySetupWnd.h
GalaxySetupWnd.cpp