FreeOrion: FieldIcon Class Reference
FieldIcon Class Reference
A control that allows interaction with a field.
#include <FieldIcon.h>
Public Member Functions
void CompleteConstruction () override
Structors //!@{
FieldIcon (int field_id)
~FieldIcon ()
Accessors //!@{
bool InWindow (const GG::Pt &pt) const override
Checks to see if point lies inside in-system fleet buttons before checking parent InWindow method.
int FieldID () const
returns ID of system this icon represents
const std::shared_ptr< GG::Texture > & FieldTexture () const
Returns the field texture.
Private Attributes
int m_field_id
the Field associated with this FieldIcon
std::shared_ptr< GG::StaticGraphic > m_mouseover_indicator
shown when the mouse cursor is over the system;
std::shared_ptr< GG::Label > m_name
the control that holds the name of the system;
bool m_selected = false
is this icon presently selected / should it show m_selected_indicator
std::shared_ptr< GG::DynamicGraphic > m_selection_indicator
shown to indicate system is selected in sidepanel;
std::shared_ptr< GG::Texture > m_texture
Mutators //!@{
boost::signals2::signal< void(int)> MouseEnteringSignal
shows/hides the selection indicator over this field
boost::signals2::signal< void(int)> MouseLeavingSignal
shows/hides the selection indicator over this field
boost::signals2::signal< void(int)> LeftClickedSignal
shows/hides the selection indicator over this field
boost::signals2::signal< void(int)> RightClickedSignal
shows/hides the selection indicator over this field
boost::signals2::signal< void(int)> LeftDoubleClickedSignal
shows/hides the selection indicator over this field
boost::signals2::signal< void(int)> RightDoubleClickedSignal
shows/hides the selection indicator over this field
void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
shows/hides the selection indicator over this field
void Render () override
shows/hides the selection indicator over this field
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void RDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void MouseLeave () override
shows/hides the selection indicator over this field
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
void Refresh ()
shows/hides the selection indicator over this field
void SetSelected (bool selected=true)
shows/hides the selection indicator over this field
Detailed Description
A control that allows interaction with a field.
This class allows user interaction with fields on the galaxy map. It contains the graphic to display the field, along with the object ID of the UniverseObject associated with it.
Constructor & Destructor Documentation
FieldIcon()
FieldIcon::FieldIcon (int field_id)
~FieldIcon()
FieldIcon::~FieldIcon ()
Member Function Documentation
CompleteConstruction()
void FieldIcon::CompleteConstruction () override
References ClientUI::ArtDir(), ClientUI::GetTexture(), m_mouseover_indicator, and Refresh().
FieldID()
int FieldIcon::FieldID () const
returns ID of system this icon represents
References m_field_id.
FieldTexture()
const std::shared_ptr< GG::Texture > & FieldIcon::FieldTexture () const
Returns the field texture.
References m_texture.
InWindow()
bool FieldIcon::InWindow (const GG::Pt & pt) const override
Checks to see if point lies inside in-system fleet buttons before checking parent InWindow method.
LButtonDown()
void FieldIcon::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
LButtonUp()
void FieldIcon::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
LClick()
void FieldIcon::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
References LeftClickedSignal, and m_field_id.
LDoubleClick()
void FieldIcon::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
References LeftDoubleClickedSignal, and m_field_id.
LDrag()
void FieldIcon::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
MouseEnter()
void FieldIcon::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
References m_field_id, m_mouseover_indicator, and MouseEnteringSignal.
MouseLeave()
void FieldIcon::MouseLeave () override
shows/hides the selection indicator over this field
References m_field_id, m_mouseover_indicator, and MouseLeavingSignal.
MouseWheel()
void FieldIcon::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
RClick()
void FieldIcon::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
References Field::FieldTypeName(), FlexibleFormat(), ObjectMap::get(), ClientUI::GetClientUI(), m_field_id, Objects(), RightClickedSignal, UserString(), and ClientUI::ZoomToFieldType().
RDoubleClick()
void FieldIcon::RDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) override
shows/hides the selection indicator over this field
References m_field_id, and RightDoubleClickedSignal.
Refresh()
void FieldIcon::Refresh ()
shows/hides the selection indicator over this field
References ClientUI::FieldTexture(), m_field_id, m_texture, and Objects().
Referenced by CompleteConstruction().
Render()
void FieldIcon::Render () override
shows/hides the selection indicator over this field
SetSelected()
void FieldIcon::SetSelected (bool selected = true)
shows/hides the selection indicator over this field
References m_selected.
SizeMove()
void FieldIcon::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
shows/hides the selection indicator over this field
References m_mouseover_indicator, m_selected, and m_selection_indicator.
Member Data Documentation
LeftClickedSignal
boost::signals2::signal<void (int)> FieldIcon::LeftClickedSignal mutable
shows/hides the selection indicator over this field
Referenced by LClick().
LeftDoubleClickedSignal
boost::signals2::signal<void (int)> FieldIcon::LeftDoubleClickedSignal mutable
shows/hides the selection indicator over this field
Referenced by LDoubleClick().
m_field_id
int FieldIcon::m_field_id private
the Field associated with this FieldIcon
Referenced by FieldID(), LClick(), LDoubleClick(), MouseEnter(), MouseLeave(), RClick(), RDoubleClick(), and Refresh().
m_mouseover_indicator
std::shared_ptr<GG::StaticGraphic> FieldIcon::m_mouseover_indicator private
shown when the mouse cursor is over the system;
Referenced by CompleteConstruction(), MouseEnter(), MouseLeave(), and SizeMove().
m_name
std::shared_ptr<GG::Label> FieldIcon::m_name private
the control that holds the name of the system;
m_selected
bool FieldIcon::m_selected = false private
is this icon presently selected / should it show m_selected_indicator
Referenced by SetSelected(), and SizeMove().
m_selection_indicator
std::shared_ptr<GG::DynamicGraphic> FieldIcon::m_selection_indicator private
shown to indicate system is selected in sidepanel;
Referenced by SizeMove().
m_texture
std::shared_ptr<GG::Texture> FieldIcon::m_texture private
Referenced by FieldTexture(), and Refresh().
MouseEnteringSignal
boost::signals2::signal<void (int)> FieldIcon::MouseEnteringSignal mutable
shows/hides the selection indicator over this field
Referenced by MouseEnter().
MouseLeavingSignal
boost::signals2::signal<void (int)> FieldIcon::MouseLeavingSignal mutable
shows/hides the selection indicator over this field
Referenced by MouseLeave().
RightClickedSignal
boost::signals2::signal<void (int)> FieldIcon::RightClickedSignal mutable
shows/hides the selection indicator over this field
Referenced by RClick().
RightDoubleClickedSignal
boost::signals2::signal<void (int)> FieldIcon::RightDoubleClickedSignal mutable
shows/hides the selection indicator over this field
Referenced by RDoubleClick().
The documentation for this class was generated from the following files:
FieldIcon.h
FieldIcon.cpp