FreeOrion: CUI_PinButton Class Reference
CUI_PinButton Class Reference
#include <CUIWnd.h>
Public Member Functions
CUI_PinButton ()
void Toggle (bool pinned)
Detailed Description
a basic Pin-shaped pin button.
Constructor & Destructor Documentation
CUI_PinButton::CUI_PinButton ()
References ClientUI::ArtDir(), ClientUI::GetTexture(), and anonymous_namespace{CUIWnd.cpp}::PlayCloseSound().
Member Function Documentation
void CUI_PinButton::Toggle (bool pinned)
References ClientUI::ArtDir(), CLOSABLE(), ClientUI::GetTexture(), MINIMIZABLE(), and PINABLE().
The documentation for this class was generated from the following files:
CUIWnd.h
CUIWnd.cpp