FreeOrion: BasesListBox::BasesListBoxRow Class Reference
BasesListBox::BasesListBoxRow Class Reference
Public Member Functions
BasesListBoxRow (GG::X w, GG::Y h, const std::string &hull, std::string name)
void CompleteConstruction () override
void Render () override
virtual void SetAvailability (const AvailabilityManager::DisplayedAvailabilies &type)
virtual void SetDisplayName (std::string name)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
std::shared_ptr< HullAndNamePanel > m_hull_panel
Constructor & Destructor Documentation
BasesListBoxRow()
BasesListBox::BasesListBoxRow::BasesListBoxRow (GG::X w, GG::Y h, const std::string & hull, std::string name)
References BasesListBox::BASES_LIST_BOX_DROP_TYPE, ErrorLogger, GetOptionsDB(), and m_hull_panel.
Member Function Documentation
CompleteConstruction()
void BasesListBox::BasesListBoxRow::CompleteConstruction () override
References m_hull_panel.
Referenced by BasesListBox::HullAndPartsListBoxRow::CompleteConstruction(), BasesListBox::CompletedDesignListBoxRow::CompleteConstruction(), and SavedDesignsListBox::SavedDesignListBoxRow::CompleteConstruction().
Render()
void BasesListBox::BasesListBoxRow::Render () override
References ClientUI::WndColor().
SetAvailability()
void BasesListBox::BasesListBoxRow::SetAvailability (const AvailabilityManager::DisplayedAvailabilies & type) virtual
References m_hull_panel, and UserString().
SetDisplayName()
void BasesListBox::BasesListBoxRow::SetDisplayName (std::string name) virtual
References m_hull_panel.
SizeMove()
void BasesListBox::BasesListBoxRow::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
Member Data Documentation
m_hull_panel
std::shared_ptr<HullAndNamePanel> BasesListBox::BasesListBoxRow::m_hull_panel private
Referenced by BasesListBoxRow(), CompleteConstruction(), SetAvailability(), and SetDisplayName().
The documentation for this class was generated from the following file:
DesignWnd.cpp