FreeOrion: anonymous_namespace{Logger.cpp}::LoggerThresholdSetter Class Reference
anonymous_namespace{Logger.cpp}::LoggerThresholdSetter Class Reference
LoggerThresholdSetter sets the threshold of a logger.
Public Member Functions
std::pair< std::string, LogLevel > SetThreshold (const std::string &source, LogLevel threshold)
Private Attributes
expr::channel_severity_filter_actor< std::string, LogLevel > m_min_channel_severity = expr::channel_severity_filter(log_channel, log_severity)
std::mutex m_mutex = {}
m_mutex serializes access from different threads
Detailed Description
LoggerThresholdSetter sets the threshold of a logger.
Member Function Documentation
SetThreshold()
std::pair<std::string, LogLevel> anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::SetThreshold (const std::string & source, LogLevel threshold) inline
References anonymous_namespace{Logger.cpp}::DisplayName(), anonymous_namespace{Logger.cpp}::ForcedThreshold(), and boost::get().
Referenced by anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore().
Member Data Documentation
m_min_channel_severity
expr::channel_severity_filter_actor<std::string, LogLevel> anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::m_min_channel_severity = expr::channel_severity_filter(log_channel, log_severity) private
m_mutex
std::mutex anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::m_mutex = {} private
m_mutex serializes access from different threads
The documentation for this class was generated from the following file:
Logger.cpp