FreeOrion: CUIToolBar Class Reference
CUIToolBar Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
CUIToolBar ()
Accessors
bool InWindow (const GG::Pt &pt) const override
Mutators
void Render () override
Constructor & Destructor Documentation
CUIToolBar()
CUIToolBar::CUIToolBar ()
Member Function Documentation
InWindow()
bool CUIToolBar::InWindow (const GG::Pt & pt) const override
Render()
void CUIToolBar::Render () override
References anonymous_namespace{CUIControls.cpp}::EMPTY_STRING(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp