FreeOrion: Field Class Reference
Field Class Reference
a class representing a region of space
#include <Field.h>
Public Member Functions
Field (const std::string &field_type, double x, double y, double radius)
~Field ()
std::shared_ptr< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const override
Accepts a visitor object.
void ClampMeters () override
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
bool ContainedBy (int object_id) const override
int ContainerObjectID () const override
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
void Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES) override
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
std::string Dump (unsigned short ntabs=0) const override
Return human readable string description of object offset ntabs from margin.
const std::string & FieldTypeName () const
bool HasTag (const std::string &name) const override
Returns true iff this object has the tag with the indicated name.
bool InField (std::shared_ptr< const UniverseObject > obj) const
bool InField (double x, double y) const
UniverseObjectType ObjectType () const override
const std::string & PublicName (int empire_id) const override
Returns the name of this objectas it appears to empire empire_id .
void ResetTargetMaxUnpairedMeters () override
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE.
std::set< std::string > Tags () const override
returns the capacity of the special with name name or 0 if that special is not present
Public Member Functions inherited from UniverseObject
virtual ~UniverseObject ()
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
virtual void BackPropagateMeters ()
Sets all this UniverseObject's meters' initial values equal to their current values.
virtual const std::set< int > & ContainedObjectIDs () const
Returns ids of objects contained within this object.
virtual bool Contains (int object_id) const
Returns true if there is an object with id object_id is contained within this UniverseObject.
int CreationTurn () const
returns game turn on which object was created
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
virtual bool HostileToEmpire (int empire_id) const
Object owner is at war with empire empire_id.
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const MeterMap & Meters () const
returns this UniverseObject's meters
MeterMap & Meters ()
returns this UniverseObject's meters
void Move (double x, double y)
moves this object by relative displacements x and y.
virtual void MovementPhase ()
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
void MoveTo (int object_id)
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
void MoveTo (std::shared_ptr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
void MoveTo (double x, double y)
moves this object to map coordinates (x, y).
const std::string & Name () const
returns the name of this object; some valid objects will have no name
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
virtual void PopGrowthProductionResearchPhase ()
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void Rename (const std::string &name)
renames this object to name
virtual void ResetPairedActiveMeters ()
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
void SetID (int id)
sets the ID number of the object to id
virtual void SetOwner (int id)
Sets the empire that owns this object.
void SetSpecialCapacity (const std::string &name, float capacity)
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
const std::map< std::string, std::pair< int, float > > & Specials () const
returns the Specials attached to this object
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
bool Unowned () const
returns true iff there are no owners of this object
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
Protected Member Functions
Field ()
Field * Clone (int empire_id=ALL_EMPIRES) const override
Returns new copy of this Field.
Protected Member Functions inherited from UniverseObject
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (std::shared_ptr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
void Init ()
adds stealth meter
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_type_name
Friends
template<typename T >
void boost::python::detail::value_destroyer (T const volatile *p)
class boost::serialization::access
class Universe
Additional Inherited Members
Public Types inherited from UniverseObject
typedef flat_map< MeterType, Meter, std::less< MeterType > > MeterMap
typedef boost::signals2::signal< void(), blocking_combiner< boost::signals2::optional_last_value< void > > > StateChangedSignalType
typedef StateChangedSignalType::slot_type StateChangedSlotType
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
a class representing a region of space
Constructor & Destructor Documentation
Field() [1/2]
Field::Field () protected
Referenced by Clone().
Field() [2/2]
Field::Field (const std::string & field_type, double x, double y, double radius)
References UniverseObject::AddMeter(), GetFieldType(), UniverseObject::GetMeter(), UniverseObject::Init(), m_type_name, METER_SIZE, METER_SPEED, UniverseObject::Rename(), Meter::Set(), and UserString().
~Field()
Field::~Field ()
Member Function Documentation
Accept()
std::shared_ptr< UniverseObject > Field::Accept (const UniverseObjectVisitor & visitor) const override virtual
Accepts a visitor object.
See also
UniverseObjectVisitor
Reimplemented from UniverseObject.
References UniverseObjectVisitor::Visit().
ClampMeters()
void Field::ClampMeters () override virtual
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
Reimplemented from UniverseObject.
References Meter::ClampCurrentToRange(), UniverseObject::ClampMeters(), UniverseObject::GetMeter(), and METER_SIZE.
Clone()
Field * Field::Clone (int empire_id = ALL_EMPIRES) const override protected virtual
Returns new copy of this Field.
Implements UniverseObject.
References Copy(), Field(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), and UniverseObject::ID().
ContainedBy()
bool Field::ContainedBy (int object_id) const override virtual
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and UniverseObject::SystemID().
ContainerObjectID()
int Field::ContainerObjectID () const override virtual
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
Reimplemented from UniverseObject.
References UniverseObject::SystemID().
Copy()
void Field::Copy (std::shared_ptr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) override virtual
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
Implements UniverseObject.
References UniverseObject::Copy(), ErrorLogger, Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), UniverseObject::m_name, and m_type_name.
Referenced by Clone().
Dump()
std::string Field::Dump (unsigned short ntabs = 0) const override virtual
Return human readable string description of object offset ntabs from margin.
Reimplemented from UniverseObject.
References UniverseObject::Dump(), and m_type_name.
FieldTypeName()
const std::string& Field::FieldTypeName () const inline
References ALL_EMPIRES.
Referenced by FieldIcon::RClick(), and FreeOrionPython::WrapUniverseClasses().
HasTag()
bool Field::HasTag (const std::string & name) const override virtual
Returns true iff this object has the tag with the indicated name.
Reimplemented from UniverseObject.
References GetFieldType(), m_type_name, and FieldType::Tags().
InField() [1/2]
bool Field::InField (std::shared_ptr< const UniverseObject > obj) const
Referenced by anonymous_namespace{UniverseWrapper.cpp}::ObjectInField().
InField() [2/2]
bool Field::InField (double x, double y) const
References Meter::Current(), UniverseObject::GetMeter(), METER_SIZE, UniverseObject::X(), and UniverseObject::Y().
ObjectType()
UniverseObjectType Field::ObjectType () const override virtual
Reimplemented from UniverseObject.
PublicName()
const std::string & Field::PublicName (int empire_id) const override virtual
Returns the name of this objectas it appears to empire empire_id .
Reimplemented from UniverseObject.
References m_type_name, and UserString().
ResetTargetMaxUnpairedMeters()
void Field::ResetTargetMaxUnpairedMeters () override virtual
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE.
This should be done before any Effects that alter these meter(s) act on the object.
Reimplemented from UniverseObject.
References UniverseObject::GetMeter(), METER_SPEED, Meter::ResetCurrent(), and UniverseObject::ResetTargetMaxUnpairedMeters().
serialize()
template<typename Archive > void Field::serialize (Archive & ar, const unsigned int version) private
Tags()
std::set< std::string > Field::Tags () const override virtual
returns the capacity of the special with name name or 0 if that special is not present
Returns all tags this object has.
Reimplemented from UniverseObject.
References GetFieldType(), m_type_name, and FieldType::Tags().
Friends And Related Function Documentation
boost::python::detail::value_destroyer
template<typename T > void boost::python::detail::value_destroyer (T const volatile * p) friend
boost::serialization::access
friend class boost::serialization::access friend
Universe
friend class Universe friend
Member Data Documentation
m_type_name
std::string Field::m_type_name private
Referenced by Copy(), Dump(), Field(), HasTag(), PublicName(), and Tags().
The documentation for this class was generated from the following files:
Field.h
Field.cpp
SerializeUniverse.cpp