FreeOrion: ObjectMap Class Reference
ObjectMap Class Reference
Contains a set of objects that make up a (known or complete) Universe.
#include <ObjectMap.h>
Public Types
template<typename T >
using container_type = std::map< int, std::shared_ptr< T > >
using id_range = boost::any_range< int, boost::forward_traversal_tag >
Public Member Functions
ObjectMap ()
~ObjectMap ()
template<typename T = UniverseObject>
boost::select_second_const_range< container_type< T > > all () const
Returns all the objects of type T.
template<typename T = UniverseObject>
boost::select_second_mutable_range< container_type< T > > all ()
Returns all the objects of type T.
void AuditContainment (const std::set< int > &destroyed_object_ids)
Recalculates contained objects for all objects in this ObjectMap based on what other objects exist in this ObjectMap.
void clear ()
Empties map, removing shared ownership by this map of all previously contained objects.
ObjectMap * Clone (int empire_id=ALL_EMPIRES) const
Copies contents of this ObjectMap to a new ObjectMap, which is returned.
void Copy (const ObjectMap &copied_map, int empire_id=ALL_EMPIRES)
Copies the contents of the ObjectMap copied_map into this ObjectMap.
void CopyForSerialize (const ObjectMap &copied_map)
Copies the contents of the ObjectMap copied_map into this ObjectMap, in preparation for serializing this ObjectMap.
void CopyObject (std::shared_ptr< const UniverseObject > source, int empire_id=ALL_EMPIRES)
Copies the passed object into this ObjectMap, overwriting any existing information about that object or creating a new object in this map as appropriate with UniverseObject::Copy or UniverseObject::Clone.
std::string Dump (unsigned short ntabs=0) const
bool empty () const
Returns true if this ObjectMap contains no objects.
std::shared_ptr< UniverseObject > erase (int id)
Removes object with id id from map, and returns that object, if there was an object under that ID in the map.
const container_type< const UniverseObject > & ExistingBuildings () const
const container_type< const UniverseObject > & ExistingFields () const
const container_type< const UniverseObject > & ExistingFleets () const
std::shared_ptr< const UniverseObject > ExistingObject (int id) const
const container_type< const UniverseObject > & ExistingObjects () const
const container_type< const UniverseObject > & ExistingPlanets () const
const container_type< const UniverseObject > & ExistingPopCenters () const
const container_type< const UniverseObject > & ExistingResourceCenters () const
const container_type< const UniverseObject > & ExistingShips () const
const container_type< const UniverseObject > & ExistingSystems () const
template<typename T = UniverseObject>
std::vector< std::shared_ptr< const T > > find (const id_range &object_ids) const
Returns a vector containing the objects with ids in object_ids that are of type T.
template<typename T = UniverseObject>
std::vector< std::shared_ptr< T > > find (const id_range &object_ids)
Returns a vector containing the objects with ids in object_ids that are of type T.
template<typename T = UniverseObject>
std::vector< std::shared_ptr< const T > > find (const UniverseObjectVisitor &visitor) const
Returns all the objects that match visitor.
template<typename T = UniverseObject>
std::vector< std::shared_ptr< T > > find (const UniverseObjectVisitor &visitor)
Returns all the objects that match visitor.
std::vector< int > FindExistingObjectIDs () const
Returns the IDs of all objects not known to have been destroyed.
template<typename T = UniverseObject>
std::shared_ptr< const T > get (int id) const
Returns a pointer to the object of type T with ID number id.
template<typename T = UniverseObject>
std::shared_ptr< T > get (int id)
Returns a pointer to the object of type T with ID number id.
int HighestObjectID () const
Returns highest used object ID in this ObjectMap.
template<typename T >
void insert (std::shared_ptr< T > obj, int empire_id=ALL_EMPIRES)
Adds object obj to the map under its ID, if it is a valid object.
template<>
FO_COMMON_API const ObjectMap::container_type< UniverseObject > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< ResourceCenter > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< PopCenter > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< Ship > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< Fleet > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< Planet > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< System > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< Building > & Map () const
template<>
FO_COMMON_API const ObjectMap::container_type< Field > & Map () const
template<>
FO_COMMON_API ObjectMap::container_type< UniverseObject > & Map ()
template<>
FO_COMMON_API ObjectMap::container_type< ResourceCenter > & Map ()
template<>
FO_COMMON_API ObjectMap::container_type< PopCenter > & Map ()
template<>
FO_COMMON_API ObjectMap::container_type< Ship > & Map ()
template<>
FO_COMMON_API ObjectMap::container_type< Fleet > & Map ()
template<>
const ObjectMap::container_type< UniverseObject > & Map () const
template<>
FO_COMMON_API ObjectMap::container_type< Planet > & Map ()
template<>
const ObjectMap::container_type< ResourceCenter > & Map () const
template<>
FO_COMMON_API ObjectMap::container_type< System > & Map ()
template<>
FO_COMMON_API ObjectMap::container_type< Building > & Map ()
template<>
const ObjectMap::container_type< PopCenter > & Map () const
template<>
FO_COMMON_API ObjectMap::container_type< Field > & Map ()
template<>
const ObjectMap::container_type< Ship > & Map () const
template<>
const ObjectMap::container_type< Fleet > & Map () const
template<>
const ObjectMap::container_type< Planet > & Map () const
template<>
const ObjectMap::container_type< System > & Map () const
template<>
const ObjectMap::container_type< Building > & Map () const
template<>
const ObjectMap::container_type< Field > & Map () const
template<>
ObjectMap::container_type< UniverseObject > & Map ()
template<>
ObjectMap::container_type< ResourceCenter > & Map ()
template<>
ObjectMap::container_type< PopCenter > & Map ()
template<>
ObjectMap::container_type< Ship > & Map ()
template<>
ObjectMap::container_type< Fleet > & Map ()
template<>
ObjectMap::container_type< Planet > & Map ()
template<>
ObjectMap::container_type< System > & Map ()
template<>
ObjectMap::container_type< Building > & Map ()
template<>
ObjectMap::container_type< Field > & Map ()
template<typename T = UniverseObject>
std::size_t size () const
Returns the number of objects of the specified class in this ObjectMap.
void swap (ObjectMap &rhs)
Swaps the contents of *this with rhs.
void UpdateCurrentDestroyedObjects (const std::set< int > &destroyed_object_ids)
Private Member Functions
void CopyObjectsToSpecializedMaps ()
void insertCore (std::shared_ptr< UniverseObject > item, int empire_id=ALL_EMPIRES)
template<typename T >
const container_type< T > & Map () const
template<typename T >
container_type< T > & Map ()
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Static Private Member Functions
template<typename T >
static void SwapMap (container_type< T > &map, ObjectMap &rhs)
Private Attributes
container_type< Building > m_buildings
container_type< const UniverseObject > m_existing_buildings
container_type< const UniverseObject > m_existing_fields
container_type< const UniverseObject > m_existing_fleets
container_type< const UniverseObject > m_existing_objects
container_type< const UniverseObject > m_existing_planets
container_type< const UniverseObject > m_existing_pop_centers
container_type< const UniverseObject > m_existing_resource_centers
container_type< const UniverseObject > m_existing_ships
container_type< const UniverseObject > m_existing_systems
container_type< Field > m_fields
container_type< Fleet > m_fleets
container_type< UniverseObject > m_objects
container_type< Planet > m_planets
container_type< PopCenter > m_pop_centers
container_type< ResourceCenter > m_resource_centers
container_type< Ship > m_ships
container_type< System > m_systems
Friends
class boost::serialization::access
Detailed Description
Contains a set of objects that make up a (known or complete) Universe.
Member Typedef Documentation
container_type
template<typename T > using ObjectMap::container_type = std::map<int, std::shared_ptr<T> >
id_range
using ObjectMap::id_range = boost::any_range<int, boost::forward_traversal_tag>
Constructor & Destructor Documentation
ObjectMap()
ObjectMap::ObjectMap ()
Referenced by Clone().
~ObjectMap()
ObjectMap::~ObjectMap ()
Member Function Documentation
all() [1/2]
template<typename T = UniverseObject> boost::select_second_const_range<container_type<T> > ObjectMap::all () const inline
Returns all the objects of type T.
Referenced by Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), AuditContainment(), AutomaticallyChosenBombardShips(), AutoResolveCombat(), Universe::BackPropagateObjectMeters(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CleanEmpires(), CombatLog::CombatLog(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), Copy(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), Dump(), Universe::EmpireVisibleObjectIDs(), Effect::MoveTo::Execute(), MessageWndEdit::FindGameWords(), GenerateStarlanes(), anonymous_namespace{Effects.cpp}::GenerateSystemName(), Universe::GetEffectsAndTargets(), Universe::GetEmpireObjectVisibilityMap(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), CombatInfo::GetMonsterDetection(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), CombatInfo::InitializeObjectVisibility(), Universe::InitMeterEstimatesAndDiscrepancies(), MapWnd::InitTurn(), MapWnd::InitTurnRendering(), Condition::anonymous_namespace{Conditions.cpp}::LaneCrossesExistingLane(), Condition::anonymous_namespace{Conditions.cpp}::LaneTooCloseToOtherSystem(), Pathfinder::PathfinderImpl::NearestSystemTo(), anonymous_namespace{UniverseWrapper.cpp}::ObjectIDs(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackers(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToSystemsAlongStarlanes(), anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), Universe::RecursiveDestroy(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), Universe::ResetAllIDAllocation(), Universe::ResetAllObjectMeters(), SetActiveMetersToTargetMaxCurrentValues(), anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires(), anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), SetNativePopulationValues(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), Empire::Source(), SupplyManager::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateEmpireStaleObjectKnowledge(), anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates(), Empire::UpdateSystemSupplyRanges(), and Empire::VisibleStarlanes().
all() [2/2]
template<typename T = UniverseObject> boost::select_second_mutable_range<container_type<T> > ObjectMap::all () inline
Returns all the objects of type T.
References Effect::Dump().
AuditContainment()
void ObjectMap::AuditContainment (const std::set< int > & destroyed_object_ids)
Recalculates contained objects for all objects in this ObjectMap based on what other objects exist in this ObjectMap.
Useful to eliminate cases where there are inconsistencies between whan an object thinks it contains, and what other objects think they are contained by the first object.
References all(), Planet::m_buildings, System::m_objects, and Fleet::m_ships.
Referenced by Universe::GetObjectsToSerialize().
clear()
void ObjectMap::clear ()
Empties map, removing shared ownership by this map of all previously contained objects.
References anonymous_namespace{ObjectMap.cpp}::ClearMap(), FOR_EACH_EXISTING_MAP, and FOR_EACH_MAP.
Referenced by Universe::Clear(), Universe::EmpireKnownObjects(), CombatInfo::GetObjectsToSerialize(), Universe::GetObjectsToSerialize(), and Universe::serialize().
Clone()
ObjectMap * ObjectMap::Clone (int empire_id = ALL_EMPIRES) const
Copies contents of this ObjectMap to a new ObjectMap, which is returned.
Copies are limited to only duplicate information that the empire with id empire_id would know about the copied objects.
References Copy(), and ObjectMap().
Referenced by Fleet::~Fleet(), and Planet::~Planet().
Copy()
void ObjectMap::Copy (const ObjectMap & copied_map, int empire_id = ALL_EMPIRES)
Copies the contents of the ObjectMap copied_map into this ObjectMap.
Each object in copied_map has information transferred to this map. If there already is a version of an object in copied_map in this map then information is copied onto this map's version of the object using the UniverseObject::Copy function. If there is no corresponding object in this map, a new object is created using the UinverseObject::Clone function. The copied objects are complete copies if empire_id is ALL_EMPIRES, but if another empire_id is specified, the copied information is limited by passing empire_id to are limited to the Copy or Clone functions of the copied UniverseObjects. Any objects in this ObjectMap that have no corresponding object in copied_map are left unchanged.
References all(), and CopyObject().
Referenced by Clone(), and Universe::GetObjectsToSerialize().
CopyForSerialize()
void ObjectMap::CopyForSerialize (const ObjectMap & copied_map)
Copies the contents of the ObjectMap copied_map into this ObjectMap, in preparation for serializing this ObjectMap.
The normal object-by-object CopyObject process is bypassed and only m_objects is copied, in a direct fashion.
References m_objects.
Referenced by Universe::GetEmpireKnownObjectsToSerialize(), and Universe::GetObjectsToSerialize().
CopyObject()
void ObjectMap::CopyObject (std::shared_ptr< const UniverseObject > source, int empire_id = ALL_EMPIRES)
Copies the passed object into this ObjectMap, overwriting any existing information about that object or creating a new object in this map as appropriate with UniverseObject::Copy or UniverseObject::Clone.
The object is fully copied if empire_id is ALL_EMPIRES, but if another empire id is specified, then the copied information is limited by passing the visibility of the object by the empire specified by empire_id to Copy or Clone of the object. The passed object is unchanged.
References GetUniverse(), and insertCore().
Referenced by Copy(), anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo(), and anonymous_namespace{ServerApp.cpp}::HandleInvasion().
CopyObjectsToSpecializedMaps()
void ObjectMap::CopyObjectsToSpecializedMaps () private
References anonymous_namespace{ObjectMap.cpp}::ClearMap(), FOR_EACH_SPECIALIZED_MAP, and anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap().
Dump()
std::string ObjectMap::Dump (unsigned short ntabs = 0) const
References all().
Referenced by AutoResolveCombat(), anonymous_namespace{UniverseWrapper.cpp}::DumpObjects(), ServerApp::GenerateUniverse(), and ServerApp::PostCombatProcessTurns().
empty()
bool ObjectMap::empty () const
Returns true if this ObjectMap contains no objects.
References m_objects.
Referenced by AutoResolveCombat(), and Universe::ForgetKnownObject().
erase()
std::shared_ptr< UniverseObject > ObjectMap::erase (int id)
Removes object with id id from map, and returns that object, if there was an object under that ID in the map.
If no such object existed in the map, a null shared_ptr is returned and nothing is removed. The ObjectMap will no longer share ownership of the returned object.
References anonymous_namespace{ObjectMap.cpp}::EraseFromMap(), FOR_EACH_EXISTING_MAP, FOR_EACH_SPECIALIZED_MAP, and m_objects.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), Universe::Delete(), Universe::Destroy(), and Universe::ForgetKnownObject().
ExistingBuildings()
const container_type<const UniverseObject>& ObjectMap::ExistingBuildings () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddBuildingSet().
ExistingFields()
const container_type<const UniverseObject>& ObjectMap::ExistingFields () const inline
References ALL_EMPIRES, anonymous_namespace{EncyclopediaParser.cpp}::insert, and swap().
Referenced by anonymous_namespace{Conditions.cpp}::AddFieldSet().
ExistingFleets()
const container_type<const UniverseObject>& ObjectMap::ExistingFleets () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddFleetSet().
ExistingObject()
std::shared_ptr< const UniverseObject > ObjectMap::ExistingObject (int id) const
References m_existing_objects.
Referenced by Condition::ObjectID::GetDefaultInitialCandidateObjects(), and Empire::SetCapitalID().
ExistingObjects()
const container_type<const UniverseObject>& ObjectMap::ExistingObjects () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddAllObjectsSet(), anonymous_namespace{CombatSystem.cpp}::AddAllObjectsSet(), and Universe::UpdateMeterEstimatesImpl().
ExistingPlanets()
const container_type<const UniverseObject>& ObjectMap::ExistingPlanets () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddPlanetSet().
ExistingPopCenters()
const container_type<const UniverseObject>& ObjectMap::ExistingPopCenters () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddPopCenterSet().
ExistingResourceCenters()
const container_type<const UniverseObject>& ObjectMap::ExistingResourceCenters () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddResCenterSet().
ExistingShips()
const container_type<const UniverseObject>& ObjectMap::ExistingShips () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddShipSet().
ExistingSystems()
const container_type<const UniverseObject>& ObjectMap::ExistingSystems () const inline
Referenced by anonymous_namespace{Conditions.cpp}::AddSystemSet(), and ServerApp::UpdateMonsterTravelRestrictions().
find() [1/4]
template<typename T > std::vector< std::shared_ptr< const T > > ObjectMap::find (const id_range & object_ids) const
Returns a vector containing the objects with ids in object_ids that are of type T.
Referenced by Universe::ApplyMeterEffectsAndUpdateMeters(), AutomaticallyChosenColonyShip(), Fleet::BlockadedAtSystem(), GiveObjectToEmpireOrder::Check(), CombatInfo::CombatInfo(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), MapWnd::CreateFleetButtonsOfType(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), Fleet::Damage(), MapWnd::DispatchFleetsExploring(), ServerApp::EliminatePlayer(), anonymous_namespace{ServerApp.cpp}::EmpireEliminated(), anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRangeSumInSystem(), Condition::Contains::Eval(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), FleetButton::FleetButton(), FleetWnd::FleetRightClicked(), Condition::InOrIsSystem::GetDefaultInitialCandidateObjects(), Condition::OnPlanet::GetDefaultInitialCandidateObjects(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasUnlauchedArmedFighters(), anonymous_namespace{Fleet.cpp}::InsertFleetWithShips(), Condition::ContainedBy::Match(), Fleet::MaxShipAgeInTurns(), Fleet::MovementPhase(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P(), SidePanel::PlanetPanel::RClick(), FleetWnd::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), SidePanel::RefreshInPreRender(), MapWnd::RefreshPopulationIndicator(), FleetDataPanel::RefreshStateChangedSignals(), MapWnd::ReselectLastFleet(), BuildDesignatorWnd::SelectDefaultPlanet(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), Fleet::Shields(), Fleet::Speed(), Fleet::Structure(), MapWnd::SystemRightClicked(), SupplyManager::Update(), MapWnd::MapScaleLine::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), Universe::UpdateEmpireStaleObjectKnowledge(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), Universe::UpdateMeterEstimatesImpl(), ServerApp::UpdateMonsterTravelRestrictions(), SystemResourceSummaryBrowseWnd::UpdateProduction(), Empire::UpdateSupplyUnobstructedSystems(), System::VisibleStarlanesWormholes(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToPrevFleet(), MapWnd::ZoomToPrevIdleFleet(), and MapWnd::ZoomToSystemWithWastedPP().
find() [2/4]
template<typename T > std::vector< std::shared_ptr< T > > ObjectMap::find (const id_range & object_ids)
Returns a vector containing the objects with ids in object_ids that are of type T.
find() [3/4]
template<typename T > std::vector< std::shared_ptr< const T > > ObjectMap::find (const UniverseObjectVisitor & visitor) const
Returns all the objects that match visitor.
find() [4/4]
template<typename T > std::vector< std::shared_ptr< T > > ObjectMap::find (const UniverseObjectVisitor & visitor)
Returns all the objects that match visitor.
FindExistingObjectIDs()
std::vector< int > ObjectMap::FindExistingObjectIDs () const
Returns the IDs of all objects not known to have been destroyed.
References m_existing_objects.
Referenced by Universe::UpdateMeterEstimates().
get() [1/2]
template<typename T > std::shared_ptr< const T > ObjectMap::get (int id) const
Returns a pointer to the object of type T with ID number id.
Returns a null std::shared_ptr if none exists or the object with ID id is not of type T.
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), FleetWnd::AddFleet(), anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), Universe::ApplyEffectDerivedVisibilities(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), AutoResolveCombat(), anonymous_namespace{SidePanel.cpp}::AvailableToBombard(), anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), Fleet::Blockaded(), Fleet::BlockadedAtSystem(), Fleet::CalculateRouteTo(), anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), Planet::CardinalSuffix(), BuildDesignatorWnd::CenterOnBuild(), RenameOrder::Check(), NewFleetOrder::Check(), FleetMoveOrder::Check(), FleetTransferOrder::Check(), ColonizeOrder::Check(), InvadeOrder::Check(), BombardOrder::Check(), ChangeFocusOrder::Check(), ScrapOrder::Check(), AggressiveOrder::Check(), GiveObjectToEmpireOrder::Check(), Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), CombatInfo::CombatInfo(), InitialStealthEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), BuildingsPanel::CompleteConstruction(), MilitaryPanel::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), Planet::Conquer(), FleetWnd::ContainsFleet(), FleetWnd::ContainsFleets(), Fleet::Copy(), Universe::CountDestructionInStats(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), CreateFleetArrivedAtDestinationSitRep(), anonymous_namespace{Effects.cpp}::CreateNewFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), InitialStealthEvent::DebugString(), ColorByOwner::Decorate(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), Universe::Delete(), Universe::Destroy(), SidePanel::PlanetPanelContainer::DisableNonSelectionCandidates(), anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations(), MapWnd::DispatchFleetsExploring(), anonymous_namespace{Supply.cpp}::DistanceBetweenObjects(), MapWnd::DoFieldIconsLayout(), MapWnd::DoFleetButtonsLayout(), SidePanel::DoLayout(), MapWnd::DoSystemIconsLayout(), FleetsListBox::DragDropHere(), FleetDataPanel::DropsAcceptable(), FleetsListBox::DropsAcceptable(), ShipsListBox::DropsAcceptable(), SupplyManager::Dump(), UniverseObject::Dump(), ClientUI::DumpObject(), ServerApp::EmpireKnownObject(), ClientApp::EmpireKnownObject(), anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRangeSumInSystem(), SidePanel::PlanetPanel::EnableOrderIssuing(), Empire::EnqueuableItem(), ProductionQueue::ProductionItem::EnqueueConditionPassedAt(), BuildingType::EnqueueLocation(), ValueRef::NameLookup::Eval(), ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Moderator::SetOwner::Execute(), Moderator::AddStarlane::Execute(), Moderator::RemoveStarlane::Execute(), Moderator::CreatePlanet::Execute(), Effect::SetOwner::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::AddStarlanes::Execute(), Effect::RemoveStarlanes::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), Universe::ExecuteEffects(), RenameOrder::ExecuteImpl(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), ChangeFocusOrder::ExecuteImpl(), AggressiveOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{Pathfinder.cpp}::FleetFromObject(), MapWnd::FleetIDsOfFleetButtonsOverlapping(), FleetMoveOrder::FleetMoveOrder(), FleetWnd::FleetRightClicked(), FleetWnd::FleetWnd(), SidePanel::PlanetPanel::FocusDropListSelectionChangedSlot(), anonymous_namespace{ValueRefs.cpp}::FollowReference(), Universe::ForgetKnownObject(), MapWnd::ForgetObject(), anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation(), anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), anonymous_namespace{UniverseWrapper.cpp}::GetBuildingP(), Condition::InOrIsSystem::GetDefaultInitialCandidateObjects(), Condition::OnPlanet::GetDefaultInitialCandidateObjects(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{UniverseWrapper.cpp}::GetFieldP(), anonymous_namespace{UniverseWrapper.cpp}::GetFleetP(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerWrapper.cpp}::GetName(), Universe::GetObjectVisibleSpecialsByEmpire(), anonymous_namespace{ServerWrapper.cpp}::GetOwner(), anonymous_namespace{UniverseWrapper.cpp}::GetPlanetP(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), anonymous_namespace{UniverseWrapper.cpp}::GetShipP(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), CombatInfo::GetSystem(), anonymous_namespace{UniverseWrapper.cpp}::GetSystemP(), ServerApp::GetUniverseObject(), ClientApp::GetUniverseObject(), anonymous_namespace{UniverseWrapper.cpp}::GetUniverseObjectP(), anonymous_namespace{ServerWrapper.cpp}::GetX(), anonymous_namespace{ServerWrapper.cpp}::GetY(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{Fleet.cpp}::HasXShips(), anonymous_namespace{UniverseWrapper.cpp}::HullProductionLocation(), anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), ObjectPanel::Init(), MapWnd::InitFieldRenderingBuffers(), Special::InitialCapacity(), MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), Pathfinder::PathfinderImpl::InitializeSystemGraph(), Universe::InitMeterEstimatesAndDiscrepancies(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitSystemRenderingBuffers(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsOnStarlane(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), anonymous_namespace{MapWnd.cpp}::IssueExploringFleetOrders(), Condition::anonymous_namespace{Conditions.cpp}::LaneCrossesExistingLane(), FleetButton::LayoutIcons(), Pathfinder::PathfinderImpl::LinearDistance(), GraphicalSummaryWnd::MakeSummaries(), Condition::Homeworld::Match(), Condition::PlanetType::Match(), Condition::PlanetSize::Match(), Condition::PlanetEnvironment::Match(), Condition::Species::Match(), Condition::FocusType::Match(), Condition::StarType::Match(), Condition::Stationary::Match(), Condition::Aggressive::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), Fleet::MovementPhase(), Fleet::MovePath(), ObjectListWnd::ObjectRightClicked(), ObjectListBox::ObjectStateChanged(), anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::operator()(), anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ParticipantBar::ParticipantBar(), anonymous_namespace{ServerWrapper.cpp}::PlanetAvailableFoci(), anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix(), MapWnd::PlanetDoubleClicked(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetType(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeOutpost(), SidePanel::PlanetSelectable(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetType(), MapWnd::PlotFleetMovement(), PartsListBox::Populate(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), Empire::ProducibleItem(), BuildingType::ProductionCost(), ShipHull::ProductionCost(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingType::ProductionLocation(), ShipDesign::ProductionLocation(), BuildingType::ProductionTime(), ShipHull::ProductionTime(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), FieldIcon::RClick(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), Empire::RecordPendingLaneUpdate(), anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), Universe::RecursiveDestroy(), BuildingIndicator::Refresh(), SystemIcon::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), RotatingPlanetControl::Refresh(), FleetDataPanel::Refresh(), ShipsListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), SidePanel::RefreshImpl(), SidePanel::RefreshInPreRender(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), FleetDataPanel::RefreshStateChangedSignals(), anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane(), BuildDesignatorWnd::SelectDefaultPlanet(), MapWnd::SelectSystem(), Empire::SetCapitalID(), SetEmpireHomeworld(), Universe::SetEmpireObjectVisibility(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), FleetDetailPanel::SetFleet(), MapWnd::SetFleetMovementLine(), SidePanel::PlanetPanel::SetFocus(), CombatLogWnd::Impl::SetLog(), anonymous_namespace{ServerWrapper.cpp}::SetName(), SidePanel::PlanetPanelContainer::SetPlanets(), MapWnd::SetProjectedFleetMovementLine(), Fleet::SetRoute(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), FleetDataPanel::SetStatIconValues(), SidePanel::SetSystem(), anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies(), anonymous_namespace{UniverseWrapper.cpp}::ShipPartProductionLocation(), FleetDetailPanel::ShipRightClicked(), Pathfinder::PathfinderImpl::ShortestPathDistance(), anonymous_namespace{SidePanel.cpp}::SystemRow::SortKey(), Empire::Source(), anonymous_namespace{ServerWrapper.cpp}::SystemAddStarlane(), anonymous_namespace{ServerWrapper.cpp}::SystemFreeOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetFleets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetNumOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetPlanets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarlanes(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarType(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOccupied(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOfPlanet(), anonymous_namespace{ServerWrapper.cpp}::SystemRemoveStarlane(), MapWnd::SystemRightClicked(), anonymous_namespace{ServerWrapper.cpp}::SystemSetStarType(), FleetDataPanel::ToggleAggression(), anonymous_namespace{ValueRefs.cpp}::TraceReference(), ColonizeOrder::UndoImpl(), InvadeOrder::UndoImpl(), BombardOrder::UndoImpl(), FleetWnd::UniverseObjectDeleted(), anonymous_namespace{VarText.cpp}::UniverseObjectString(), SpecialsPanel::Update(), MultiMeterStatusBar::Update(), MilitaryPanel::Update(), PopulationPanel::Update(), ResourcePanel::Update(), BuildingsPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), anonymous_namespace{Effects.cpp}::UpdateFleetRoute(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), ProductionWnd::UpdateInfoPanel(), Universe::UpdateMeterEstimates(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), ShipFightersBrowseWnd::UpdateSummary(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), MapWnd::ZoomToHomeSystem(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToNextSystem(), MapWnd::ZoomToPrevOwnedSystem(), and MapWnd::ZoomToPrevSystem().
get() [2/2]
template<typename T > std::shared_ptr< T > ObjectMap::get (int id)
Returns a pointer to the object of type T with ID number id.
Returns a null std::shared_ptr if none exists or the object with ID id is not of type T.
HighestObjectID()
int ObjectMap::HighestObjectID () const
Returns highest used object ID in this ObjectMap.
References INVALID_OBJECT_ID, and m_objects.
insert()
template<typename T > void ObjectMap::insert (std::shared_ptr< T > obj, int empire_id = ALL_EMPIRES)
Adds object obj to the map under its ID, if it is a valid object.
If there already was an object in the map with the id id then that object will be removed.
References FO_COMMON_API, and Map().
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), CombatInfo::CombatInfo(), Condition::ContainedBy::Eval(), Universe::InsertIDCore(), MapWnd::ReselectLastFleet(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), and Empire::VisibleStarlanes().
insertCore()
void ObjectMap::insertCore (std::shared_ptr< UniverseObject > item, int empire_id = ALL_EMPIRES) private
References FOR_EACH_MAP, GetUniverse(), m_existing_buildings, m_existing_fields, m_existing_fleets, m_existing_objects, m_existing_planets, m_existing_pop_centers, m_existing_resource_centers, m_existing_ships, m_existing_systems, and anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap().
Referenced by CopyObject().
Map() [1/38]
template<typename T > const container_type<T>& ObjectMap::Map () const private
Referenced by insert(), and SwapMap().
Map() [2/38]
template<typename T > container_type<T>& ObjectMap::Map () private
Map() [3/38]
template<> FO_COMMON_API const ObjectMap::container_type<UniverseObject>& ObjectMap::Map () const
Map() [4/38]
template<> FO_COMMON_API const ObjectMap::container_type<ResourceCenter>& ObjectMap::Map () const
Map() [5/38]
template<> FO_COMMON_API const ObjectMap::container_type<PopCenter>& ObjectMap::Map () const
Map() [6/38]
template<> FO_COMMON_API const ObjectMap::container_type<Ship>& ObjectMap::Map () const
Map() [7/38]
template<> FO_COMMON_API const ObjectMap::container_type<Fleet>& ObjectMap::Map () const
Map() [8/38]
template<> FO_COMMON_API const ObjectMap::container_type<Planet>& ObjectMap::Map () const
Map() [9/38]
template<> FO_COMMON_API const ObjectMap::container_type<System>& ObjectMap::Map () const
Map() [10/38]
template<> FO_COMMON_API const ObjectMap::container_type<Building>& ObjectMap::Map () const
Map() [11/38]
template<> FO_COMMON_API const ObjectMap::container_type<Field>& ObjectMap::Map () const
Map() [12/38]
template<> FO_COMMON_API ObjectMap::container_type<UniverseObject>& ObjectMap::Map ()
Map() [13/38]
template<> FO_COMMON_API ObjectMap::container_type<ResourceCenter>& ObjectMap::Map ()
Map() [14/38]
template<> FO_COMMON_API ObjectMap::container_type<PopCenter>& ObjectMap::Map ()
Map() [15/38]
template<> FO_COMMON_API ObjectMap::container_type<Ship>& ObjectMap::Map ()
Map() [16/38]
template<> FO_COMMON_API ObjectMap::container_type<Fleet>& ObjectMap::Map ()
Map() [17/38]
template<> const ObjectMap::container_type<UniverseObject>& ObjectMap::Map () const
References m_objects.
Map() [18/38]
template<> FO_COMMON_API ObjectMap::container_type<Planet>& ObjectMap::Map ()
Map() [19/38]
template<> const ObjectMap::container_type<ResourceCenter>& ObjectMap::Map () const
References m_resource_centers.
Map() [20/38]
template<> FO_COMMON_API ObjectMap::container_type<System>& ObjectMap::Map ()
Map() [21/38]
template<> FO_COMMON_API ObjectMap::container_type<Building>& ObjectMap::Map ()
Map() [22/38]
template<> const ObjectMap::container_type<PopCenter>& ObjectMap::Map () const
References m_pop_centers.
Map() [23/38]
template<> FO_COMMON_API ObjectMap::container_type<Field>& ObjectMap::Map ()
Map() [24/38]
template<> const ObjectMap::container_type<Ship>& ObjectMap::Map () const
References m_ships.
Map() [25/38]
template<> const ObjectMap::container_type<Fleet>& ObjectMap::Map () const
References m_fleets.
Map() [26/38]
template<> const ObjectMap::container_type<Planet>& ObjectMap::Map () const
References m_planets.
Map() [27/38]
template<> const ObjectMap::container_type<System>& ObjectMap::Map () const
References m_systems.
Map() [28/38]
template<> const ObjectMap::container_type<Building>& ObjectMap::Map () const
References m_buildings.
Map() [29/38]
template<> const ObjectMap::container_type<Field>& ObjectMap::Map () const
References m_fields.
Map() [30/38]
template<> ObjectMap::container_type<UniverseObject>& ObjectMap::Map ()
References m_objects.
Map() [31/38]
template<> ObjectMap::container_type<ResourceCenter>& ObjectMap::Map ()
References m_resource_centers.
Map() [32/38]
template<> ObjectMap::container_type<PopCenter>& ObjectMap::Map ()
References m_pop_centers.
Map() [33/38]
template<> ObjectMap::container_type<Ship>& ObjectMap::Map ()
References m_ships.
Map() [34/38]
template<> ObjectMap::container_type<Fleet>& ObjectMap::Map ()
References m_fleets.
Map() [35/38]
template<> ObjectMap::container_type<Planet>& ObjectMap::Map ()
References m_planets.
Map() [36/38]
template<> ObjectMap::container_type<System>& ObjectMap::Map ()
References m_systems.
Map() [37/38]
template<> ObjectMap::container_type<Building>& ObjectMap::Map ()
References m_buildings.
Map() [38/38]
template<> ObjectMap::container_type<Field>& ObjectMap::Map ()
References m_fields.
serialize()
template<typename Archive > void ObjectMap::serialize (Archive & ar, const unsigned int version) private
size()
template<typename T > std::size_t ObjectMap::size () const
Returns the number of objects of the specified class in this ObjectMap.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), Universe::InitMeterEstimatesAndDiscrepancies(), anonymous_namespace{UniverseWrapper.cpp}::ObjectIDs(), and Universe::serialize().
swap()
void ObjectMap::swap (ObjectMap & rhs)
Swaps the contents of *this with rhs.
References FOR_EACH_MAP, m_existing_buildings, m_existing_fields, m_existing_fleets, m_existing_objects, m_existing_planets, m_existing_pop_centers, m_existing_resource_centers, m_existing_ships, m_existing_systems, and SwapMap().
Referenced by CombatInfo::load(), and Universe::serialize().
SwapMap()
template<typename T > void ObjectMap::SwapMap (ObjectMap::container_type< T > & map, ObjectMap & rhs) static private
References Map().
Referenced by swap().
UpdateCurrentDestroyedObjects()
void ObjectMap::UpdateCurrentDestroyedObjects (const std::set< int > & destroyed_object_ids)
References anonymous_namespace{ObjectMap.cpp}::ClearMap(), FOR_EACH_EXISTING_MAP, m_existing_buildings, m_existing_fields, m_existing_fleets, m_existing_objects, m_existing_planets, m_existing_pop_centers, m_existing_resource_centers, m_existing_ships, m_existing_systems, and m_objects.
Referenced by Universe::serialize().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_buildings
container_type<Building> ObjectMap::m_buildings private
Referenced by Map().
m_existing_buildings
container_type<const UniverseObject> ObjectMap::m_existing_buildings private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_fields
container_type<const UniverseObject> ObjectMap::m_existing_fields private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_fleets
container_type<const UniverseObject> ObjectMap::m_existing_fleets private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_objects
container_type<const UniverseObject> ObjectMap::m_existing_objects private
Referenced by ExistingObject(), FindExistingObjectIDs(), insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_planets
container_type<const UniverseObject> ObjectMap::m_existing_planets private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_pop_centers
container_type<const UniverseObject> ObjectMap::m_existing_pop_centers private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_resource_centers
container_type<const UniverseObject> ObjectMap::m_existing_resource_centers private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_ships
container_type<const UniverseObject> ObjectMap::m_existing_ships private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_existing_systems
container_type<const UniverseObject> ObjectMap::m_existing_systems private
Referenced by insertCore(), swap(), and UpdateCurrentDestroyedObjects().
m_fields
container_type<Field> ObjectMap::m_fields private
Referenced by Map().
m_fleets
container_type<Fleet> ObjectMap::m_fleets private
Referenced by Map().
m_objects
container_type<UniverseObject> ObjectMap::m_objects private
Referenced by CopyForSerialize(), empty(), erase(), HighestObjectID(), Map(), and UpdateCurrentDestroyedObjects().
m_planets
container_type<Planet> ObjectMap::m_planets private
Referenced by Map().
m_pop_centers
container_type<PopCenter> ObjectMap::m_pop_centers private
Referenced by Map().
m_resource_centers
container_type<ResourceCenter> ObjectMap::m_resource_centers private
Referenced by Map().
m_ships
container_type<Ship> ObjectMap::m_ships private
Referenced by Map().
m_systems
container_type<System> ObjectMap::m_systems private
Referenced by Map().
The documentation for this class was generated from the following files:
ObjectMap.h
ObjectMap.cpp
SerializeUniverse.cpp