FreeOrion: anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager Class Reference
anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager Class Reference
Public Member Functions
CurrentShipDesignManager ()
std::vector< int > AllOrderedIDs () const
void InsertBefore (const int id, const int next_id)
void InsertHullBefore (const std::string &id, const std::string &next_id="")
template<typename T >
void InsertOrderedIDs (const T &new_order)
bool IsHullObsolete (const std::string &hull) const
bool IsKnown (const int id) const
boost::optional< bool > IsObsolete (const int id) const
bool IsPartObsolete (const std::string &part) const
void Load (const std::vector< std::pair< int, boost::optional< bool >>> &design_ids_and_obsoletes, const std::vector< std::pair< std::string, bool >> &hulls_and_obsoletes, const std::unordered_set< std::string > &obsolete_parts)
bool MoveBefore (const int moved_id, const int next_id)
std::vector< std::string > OrderedHulls () const
std::vector< int > OrderedIDs () const override
void Remove (const int id)
void Save (std::vector< std::pair< int, boost::optional< bool >>> &design_ids_and_obsoletes, std::vector< std::pair< std::string, bool >> &hulls_and_obsoletes, std::unordered_set< std::string > &obsolete_parts)
void SetHullObsolete (const std::string &hull, const bool obsolete)
void SetObsolete (const int id, const bool obsolete)
void SetPartObsolete (const std::string &part, const bool obsolete)
Private Attributes
std::unordered_map< std::string, std::pair< bool, std::list< std::string >::const_iterator > > m_hull_to_obsolete_and_loc
std::unordered_map< int, std::pair< boost::optional< bool >, std::list< int >::const_iterator > > m_id_to_obsolete_and_loc
std::unordered_set< std::string > m_obsolete_parts
std::list< int > m_ordered_design_ids
std::list< std::string > m_ordered_hulls
Detailed Description
CurrentShipDesignManager allows for the storage and manipulation of an ordered list of design ids that are used to order the display of ShipDesigns in the DesignWnd and the ProductionWnd.
Constructor & Destructor Documentation
anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::CurrentShipDesignManager () inline
Member Function Documentation
std::vector< int > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::AllOrderedIDs () const
Return all ids including obsoleted designs.
Referenced by anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToCurrentDesigns().
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::InsertBefore (const int id, const int next_id)
References ErrorLogger, INVALID_DESIGN_ID, and WarnLogger.
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::InsertHullBefore (const std::string & id, const std::string & next_id = "")
References ErrorLogger.
Referenced by EmptyHullsListBox::QueueItemMoved().
template<typename T > void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::InsertOrderedIDs (const T & new_order)
References INVALID_DESIGN_ID.
bool anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::IsHullObsolete (const std::string & hull) const
Return true if hull is obsolete.
bool anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::IsKnown (const int id) const
boost::optional< bool > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::IsObsolete (const int id) const
Return true if id is obsolete or boost::none if is not in the manager.
References ErrorLogger, and GetShipDesign().
bool anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::IsPartObsolete (const std::string & part) const
Return true if part is obsolete.
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::Load (const std::vector< std::pair< int, boost::optional< bool >>> & design_ids_and_obsoletes, const std::vector< std::pair< std::string, bool >> & hulls_and_obsoletes, const std::unordered_set< std::string > & obsolete_parts)
References ErrorLogger.
Referenced by ShipDesignManager::Load().
bool anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::MoveBefore (const int moved_id, const int next_id)
References ErrorLogger, and INVALID_DESIGN_ID.
Referenced by CompletedDesignsListBox::QueueItemMoved().
std::vector< std::string > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::OrderedHulls () const
Return non-obsolete available hulls.
std::vector< int > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::OrderedIDs () const override virtual
Return non-obsolete available ordered ids.
Implements ShipDesignManager::Designs.
References anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), and anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager().
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::Remove (const int id)
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::Save (std::vector< std::pair< int, boost::optional< bool >>> & design_ids_and_obsoletes, std::vector< std::pair< std::string, bool >> & hulls_and_obsoletes, std::unordered_set< std::string > & obsolete_parts)
Save modifies each of its parameters to store obsolete and ordering data in the UI save data.
References ErrorLogger.
Referenced by ShipDesignManager::Save().
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::SetHullObsolete (const std::string & hull, const bool obsolete)
Set hull's obsolescence to obsolete.
References ErrorLogger.
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::SetObsolete (const int id, const bool obsolete)
If id is in manager, set id's obsolescence to obsolete.
References ErrorLogger, and GetShipDesign().
void anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::SetPartObsolete (const std::string & part, const bool obsolete)
Set part's obsolescence to obsolete.
Member Data Documentation
std::unordered_map<std::string, std::pair<bool, std::list<std::string>::const_iterator> > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::m_hull_to_obsolete_and_loc private
std::unordered_map<int, std::pair<boost::optional<bool>, std::list<int>::const_iterator> > anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::m_id_to_obsolete_and_loc private
std::unordered_set<std::string> anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::m_obsolete_parts private
std::list<int> anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::m_ordered_design_ids private
std::list<std::string> anonymous_namespace{DesignWnd.cpp}::CurrentShipDesignManager::m_ordered_hulls private
The documentation for this class was generated from the following file:
DesignWnd.cpp