FreeOrion: Sound::InitializationFailureException Class Reference
Sound::InitializationFailureException Class Reference
#include <Sound.h>
Public Member Functions
InitializationFailureException (const std::string &s)
Constructor & Destructor Documentation
InitializationFailureException()
Sound::InitializationFailureException::InitializationFailureException (const std::string & s) inline explicit
References Sound::Disable(), Sound::DoFrame(), Sound::Enable(), Sound::FreeAllSounds(), Sound::FreeSound(), Sound::GetSound(), Sound::PauseMusic(), Sound::PlayMusic(), Sound::PlaySound(), Sound::ResumeMusic(), Sound::SetMusicVolume(), Sound::SetUISoundsVolume(), and Sound::StopMusic().
The documentation for this class was generated from the following file:
Sound.h