FreeOrion: ClientUI.cpp File Reference
ClientUI.cpp File Reference
#include "ClientUI.h"
#include "CUIControls.h"
#include "FleetWnd.h"
#include "IntroScreen.h"
#include "MapWnd.h"
#include "DesignWnd.h"
#include "ChatWnd.h"
#include "PlayerListWnd.h"
#include "MultiplayerLobbyWnd.h"
#include "PasswordEnterWnd.h"
#include "Sound.h"
#include "Hotkeys.h"
#include "../util/Random.h"
#include "../util/Directories.h"
#include "../util/i18n.h"
#include "../util/OptionsDB.h"
#include "../universe/Building.h"
#include "../universe/Fleet.h"
#include "../universe/Planet.h"
#include "../universe/System.h"
#include "../universe/Ship.h"
#include "../universe/ShipDesign.h"
#include "../universe/Tech.h"
#include "../universe/Special.h"
#include "../universe/Species.h"
#include "../universe/Field.h"
#include "../universe/Enums.h"
#include "../Empire/Government.h"
#include "../combat/CombatLogManager.h"
#include "../client/human/HumanClientApp.h"
#include <GG/Clr.h>
#include <GG/dialogs/ThreeButtonDlg.h>
#include <GG/DrawUtil.h>
#include <GG/GUI.h>
#include <GG/RichText/ImageBlock.h>
#include <GG/UnicodeCharsets.h>
#include <boost/spirit/include/classic.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/system/system_error.hpp>
#include <boost/date_time/posix_time/posix_time_io.hpp>
#include <boost/date_time/c_local_time_adjustor.hpp>
#include <string>
#include <algorithm>
#include <boost/locale/formatting.hpp>
#include <boost/locale/date_time.hpp>
Namespaces
anonymous_namespace{ClientUI.cpp}
GG
Functions
void anonymous_namespace{ClientUI.cpp}::AddOptions (OptionsDB &db)
template<class OptionType , class PredicateType >
void anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption (const std::string &option_name, const OptionsDB::OptionChangedSignalType::slot_type &slot, OptionType ref_val, PredicateType pred)
template<class OptionType , class PredicateType >
void anonymous_namespace{ClientUI.cpp}::ConditionalForward (const std::string &option_name, const OptionsDB::OptionChangedSignalType::slot_type &slot, OptionType ref_val, PredicateType pred)
int FontBasedUpscale (int x)
const Tech * GetTech (const std::string &name)
Return the Tech identified by name.
const GG::X anonymous_namespace{ClientUI.cpp}::MESSAGE_PANEL_WIDTH (345)
std::ostream & operator<< (std::ostream &os, const GG::UnicodeCharset &chset)
std::ostream & GG::operator<< (std::ostream &os, const Clr &clr)
std::istream & GG::operator>> (std::istream &is, Clr &clr)
const GG::Y anonymous_namespace{ClientUI.cpp}::PANEL_HEIGHT (160)
const GG::X anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_PANEL_WIDTH (445)
const std::vector< GG::UnicodeCharset > & anonymous_namespace{ClientUI.cpp}::RequiredCharsets ()
bool TextureFileNameCompare (const std::shared_ptr< GG::Texture > t1, const std::shared_ptr< GG::Texture > t2)
Variables
const std::string anonymous_namespace{ClientUI.cpp}::MESSAGE_WND_NAME = "map.messages"
const std::string anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_WND_NAME = "map.empires"
bool anonymous_namespace{ClientUI.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
int FontBasedUpscale (int x)
Increases the given value when font size is larger than 12
References ClientUI::Pts().
Referenced by anonymous_namespace{ResourceBrowseWnd.cpp}::BrowseTextWidth(), anonymous_namespace{CensusBrowseWnd.cpp}::BrowseTextWidth(), ResourceBrowseWnd::CompleteConstruction(), WastedStockpiledResourceBrowseWnd::CompleteConstruction(), GalaxySetupPanel::DefaultWidth(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndHeight(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndWidth(), and MapWnd::RefreshFleetResourceIndicator().
const Tech* GetTech (const std::string & name)
Return the Tech identified by name.
Parameters
name The identifying name of the requested Tech.
Returns
A pointer to the Tech matching name or nullptr if no Tech with that name was found.
Referenced by ClientUI::ZoomToTech().
std::ostream& operator<< (std::ostream & os, const GG::UnicodeCharset & chset)
bool TextureFileNameCompare (const std::shared_ptr< GG::Texture > t1, const std::shared_ptr< GG::Texture > t2)
Referenced by ClientUI::PrefixedTexturesAndDist().