FreeOrion: CombatSystem.h File Reference
CombatSystem.h File Reference
#include "../universe/Universe.h"
#include "../util/AppInterface.h"
#include "CombatEvent.h"
#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_member.hpp>
#include <boost/serialization/version.hpp>
Classes
struct CombatInfo
Contains information about the state of a combat before or after the combat occurs.
Functions
void AutoResolveCombat (CombatInfo &combat_info)
Auto-resolves a battle.
Function Documentation
void AutoResolveCombat (CombatInfo & combat_info)
Auto-resolves a battle.
References ObjectMap::begin(), CombatInfo::combat_events, anonymous_namespace{CombatSystem.cpp}::CombatRound(), CurrentTurn(), DebugLogger, ObjectMap::Dump(), CombatInfo::empire_known_objects, ObjectMap::Empty(), ErrorLogger, GameRules::Get(), GetGameRules(), ObjectMap::Object(), CombatInfo::objects, anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), Seed(), and CombatInfo::system_id.
Referenced by ServerApp::ProcessCombats().