FreeOrion: CombatLogManager.h File Reference
CombatLogManager.h File Reference
#include "CombatSystem.h"
#include "../util/Export.h"
#include "../util/Serialize.h"
#include <boost/optional/optional.hpp>
#include <boost/serialization/nvp.hpp>
#include <memory>
Classes
struct CombatLog
class CombatLogManager
Stores and retreives combat logs.
struct CombatParticipantState
Functions
BOOST_CLASS_VERSION (CombatLog, 1)
FO_COMMON_API boost::optional< const CombatLog & > GetCombatLog (int log_id)
Returns the CombatLog with the indicated id, or an empty log if there is no avaiable log with that id.
FO_COMMON_API CombatLogManager & GetCombatLogManager ()
returns the singleton combat log manager
Function Documentation
BOOST_CLASS_VERSION()
BOOST_CLASS_VERSION (CombatLog , 1)
Referenced by BoutEvent::serialize(), ProductionQueue::Element::serialize(), SimultaneousEvents::serialize(), InitialStealthEvent::serialize(), StealthChangeEvent::StealthChangeEventDetail::serialize(), StealthChangeEvent::serialize(), WeaponFireEvent::serialize(), IncapacitationEvent::serialize(), FightersAttackFightersEvent::serialize(), FightersDestroyedEvent::serialize(), WeaponsPlatformEvent::serialize(), and Empire::serialize().
GetCombatLog()
FO_COMMON_API boost::optional<const CombatLog&> GetCombatLog (int log_id)
Returns the CombatLog with the indicated id, or an empty log if there is no avaiable log with that id.
References GetCombatLogManager(), and CombatLogManager::GetLog().
Referenced by GraphicalSummaryWnd::MakeSummaries(), and CombatLogWnd::Impl::SetLog().
GetCombatLogManager()
FO_COMMON_API CombatLogManager& GetCombatLogManager ()
returns the singleton combat log manager