FreeOrion: CombatLogManager.cpp File Reference
CombatLogManager.cpp File Reference
#include "CombatLogManager.h"
#include "../universe/Meter.h"
#include "../universe/UniverseObject.h"
#include "../universe/Enums.h"
#include "../util/Serialize.h"
#include "../util/Serialize.ipp"
#include "../util/Logger.h"
#include "CombatEvents.h"
#include <boost/unordered_map.hpp>
Classes
class CombatLogManager::Impl
Namespaces
anonymous_namespace{CombatLogManager.cpp}
Functions
static float anonymous_namespace{CombatLogManager.cpp}::CurrentHealth (const UniverseObject &object)
static void anonymous_namespace{CombatLogManager.cpp}::FillState (CombatParticipantState &state, const UniverseObject &object)
boost::optional< const CombatLog & > GetCombatLog (int log_id)
Returns the CombatLog with the indicated id, or an empty log if there is no avaiable log with that id.
CombatLogManager & GetCombatLogManager ()
returns the singleton combat log manager
static float anonymous_namespace{CombatLogManager.cpp}::MaxHealth (const UniverseObject &object)
Function Documentation
boost::optional<const CombatLog&> GetCombatLog (int log_id)
Returns the CombatLog with the indicated id, or an empty log if there is no avaiable log with that id.
References CombatLogManager::GetCombatLogManager(), and CombatLogManager::GetLog().
Referenced by GraphicalSummaryWnd::MakeSummaries(), and CombatLogWnd::Impl::SetLog().
CombatLogManager& GetCombatLogManager ()
returns the singleton combat log manager
References CombatLogManager::GetCombatLogManager().
Referenced by ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps(), AIClientApp::HandleMessage(), ServerFSM::HandleNonLobbyDisconnection(), ServerApp::LoadGameInit(), ServerApp::PostCombatProcessTurns(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), WaitingForTurnEnd::react(), HumanClientApp::ResetClientData(), ServerApp::SendNewGameStartMessages(), HumanClientApp::UpdateCombatLogManager(), HumanClientApp::UpdateCombatLogs(), ServerApp::UpdateCombatLogs(), and ClientUI::ZoomToCombatLog().