FreeOrion: CombatSystem.cpp File Reference
CombatSystem.cpp File Reference
#include "CombatSystem.h"
#include "CombatEvents.h"
#include "../universe/Universe.h"
#include "../util/GameRules.h"
#include "../util/OptionsDB.h"
#include "../universe/Planet.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/Fighter.h"
#include "../universe/ShipDesign.h"
#include "../universe/ShipPart.h"
#include "../universe/System.h"
#include "../universe/Species.h"
#include "../universe/Conditions.h"
#include "../universe/ValueRefs.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/Random.h"
#include "../util/i18n.h"
#include "../network/Message.h"
#include <boost/format.hpp>
#include <iterator>
#include <sstream>
Classes
struct anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo
A collection of information the autoresolution must keep around.
struct anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo
struct anonymous_namespace{CombatSystem.cpp}::PartAttackInfo
Namespaces
anonymous_namespace{CombatSystem.cpp}
Functions
void anonymous_namespace{CombatSystem.cpp}::AddAllObjectsSet (ObjectMap &obj_map, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{CombatSystem.cpp}::Attack (const std::shared_ptr< UniverseObject > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< UniverseObject > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr platform_event, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
void anonymous_namespace{CombatSystem.cpp}::AttackFighterFighter (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
void anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event)
void anonymous_namespace{CombatSystem.cpp}::AttackFighterShip (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event)
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetFighter (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetPlanet (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void anonymous_namespace{CombatSystem.cpp}::AttackShipFighter (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void anonymous_namespace{CombatSystem.cpp}::AttackShipShip (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AutoResolveCombat (CombatInfo &combat_info)
Auto-resolves a battle.
void anonymous_namespace{CombatSystem.cpp}::CombatRound (AutoresolveInfo &combat_state)
anonymous_namespace{CombatSystem.cpp}::DeclareThreadSafeLogger (combat)
std::shared_ptr< const Empire > anonymous_namespace{CombatSystem.cpp}::GetEmpire (int id, const CombatInfo &combat_info)
std::map< int, float > anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths (const CombatInfo &combat_info)
Visibility anonymous_namespace{CombatSystem.cpp}::GetObjectVisibilityByEmpire (int obj_id, int empire_id, const CombatInfo &combat_info)
std::vector< PartAttackInfo > anonymous_namespace{CombatSystem.cpp}::GetWeapons (const std::shared_ptr< UniverseObject > &attacker)
void anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount (std::shared_ptr< Ship > &ship, float recovered_fighters)
void anonymous_namespace{CombatSystem.cpp}::LaunchFighters (std::shared_ptr< UniverseObject > attacker, const std::vector< PartAttackInfo > &weapons, AutoresolveInfo &combat_state, int round, FighterLaunchesEventPtr &launches_event)
bool anonymous_namespace{CombatSystem.cpp}::ObjectCanAttack (const std::shared_ptr< const UniverseObject > &obj, const ObjectMap &objects)
void anonymous_namespace{CombatSystem.cpp}::RecoverFighters (CombatInfo &combat_info, int bout, FighterLaunchesEventPtr &launches_event)
void anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount (std::shared_ptr< Ship > &ship, float launched_fighters)
std::vector< PartAttackInfo > anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths (const std::shared_ptr< const Ship > &ship)
void anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons (const std::shared_ptr< UniverseObject > &attacker, AutoresolveInfo &combat_state, int round, AttacksEventPtr &attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr &platform_event, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
const Condition::Condition * anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition (const std::shared_ptr< UniverseObject > &attacker)
Condition::Condition * anonymous_namespace{CombatSystem.cpp}::VisibleEnemyOfOwnerCondition ()
Variables
const std::unique_ptr< Condition::Condition > anonymous_namespace{CombatSystem.cpp}::if_source_is_planet_then_ships_else_all
const std::unique_ptr< Condition::Condition > anonymous_namespace{CombatSystem.cpp}::is_enemy_ship
const std::unique_ptr< Condition::Condition > anonymous_namespace{CombatSystem.cpp}::is_enemy_ship_fighter_or_armed_planet
const std::unique_ptr< Condition::Condition > anonymous_namespace{CombatSystem.cpp}::is_enemy_ship_or_fighter
Function Documentation
AutoResolveCombat()
void AutoResolveCombat (CombatInfo & combat_info)
Auto-resolves a battle.
References CombatInfo::bout, CombatInfo::combat_events, anonymous_namespace{CombatSystem.cpp}::CombatRound(), DebugLogger, ErrorLogger, CombatInfo::galaxy_setup_data, GameRules::Get(), GetGameRules(), GalaxySetupData::GetSeed(), CombatInfo::objects, anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), Seed(), CombatInfo::system_id, and CombatInfo::turn.
Referenced by ServerApp::ProcessCombats().