FreeOrion: CommonFramework.h File Reference
CommonFramework.h File Reference
#include <boost/optional.hpp>
#include <boost/python.hpp>
#include <boost/python/dict.hpp>
#include <vector>
#include <string>
Classes
class PythonBase
Functions
const std::string GetPythonCommonDir ()
const std::string GetPythonDir ()
Function Documentation
GetPythonCommonDir()
const std::string GetPythonCommonDir ()
References GetPythonDir().
Referenced by PythonBase::Initialize().
GetPythonDir()
const std::string GetPythonDir ()
References GetResourceDir().
Referenced by GetPythonAuthDir(), GetPythonChatDir(), GetPythonCommonDir(), GetPythonTurnEventsDir(), and GetPythonUniverseGeneratorDir().