FreeOrion: Condition.cpp File Reference
Condition.cpp File Reference
#include "Condition.h"
#include "../util/Logger.h"
#include "../util/Random.h"
#include "../util/i18n.h"
#include "UniverseObject.h"
#include "Pathfinder.h"
#include "Universe.h"
#include "Building.h"
#include "Fighter.h"
#include "Fleet.h"
#include "Ship.h"
#include "ObjectMap.h"
#include "Planet.h"
#include "System.h"
#include "Species.h"
#include "Special.h"
#include "Meter.h"
#include "ValueRef.h"
#include "Enums.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Supply.h"
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/bind.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/st_connected.hpp>
#include <boost/smart_ptr/make_unique.hpp>
Classes
struct Condition::anonymous_namespace{Condition.cpp}::BuildingSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ChanceSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ContainedBySimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ContainsSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::CreatedOnTurnSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::DesignHasHullSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::DesignHasPartClassSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::EmpireStockpileValueSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ExploredByEmpireSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::HasSpecialSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::HasTagSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::InSystemSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::MeterValueSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::NumberedShipDesignSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ObjectIDSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipDesignAvailableSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipPartAvailableSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::OwnerHasTechSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::PlanetSizeSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::PlanetTypeSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::PredefinedShipDesignSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ProducedByEmpireSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ResourceSupplySimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::SpeciesSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::StarTypeSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::TypeSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::VisibleToEmpireSimpleMatch
struct Condition::anonymous_namespace{Condition.cpp}::WithinDistanceSimpleMatch
struct Condition::ConditionBase::MatchHelper
Namespaces
anonymous_namespace{Condition.cpp}
Condition
this namespace holds ConditionBase and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Condition::anonymous_namespace{Condition.cpp}
Macros
#define CHECK_COND_VREF_MEMBER(m_ptr)
Functions
void anonymous_namespace{Condition.cpp}::AddAllObjectsSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddBuildingSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddFieldSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddFleetSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddPlanetSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddPopCenterSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddResCenterSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddShipSet (Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Condition.cpp}::AddSystemSet (Condition::ObjectSet &condition_non_targets)
std::string Condition::anonymous_namespace{Condition.cpp}::CompareTypeString (ComparisonType comp)
bool Condition::anonymous_namespace{Condition.cpp}::Comparison (float val1, ComparisonType comp, float val2)
bool Condition::anonymous_namespace{Condition.cpp}::Comparison (const std::string &val1, ComparisonType comp, const std::string &val2)
std::string Condition::ConditionDescription (const std::vector< ConditionBase * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Returns a single string which describes a vector of Conditions.
std::map< std::string, bool > anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest (const std::vector< Condition::ConditionBase *> &conditions, const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate_object)
std::string Condition::ConditionFailedDescription (const std::vector< ConditionBase * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Same as ConditionDescription, but returns a string only with conditions that have not been met.
float Condition::anonymous_namespace{Condition.cpp}::CrossProduct (float dx1, float dy1, float dx2, float dy2)
int Condition::anonymous_namespace{Condition.cpp}::CustomRandInt (int max_plus_one)
Random number genrator function to use with random_shuffle.
anonymous_namespace{Condition.cpp}::DeclareThreadSafeLogger (conditions)
template<class Pred >
void anonymous_namespace{Condition.cpp}::EvalImpl (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, Condition::SearchDomain search_domain, const Pred &pred)
Used by 4-parameter ConditionBase::Eval function, and some of its overrides, to scan through matches or non_matches set and apply pred to each object, to test if it should remain in its current set or be transferred from the search_domain specified set into the other.
void Condition::FCMoveContent (Condition::ObjectSet &from_set, Condition::ObjectSet &to_set)
std::vector< Condition::ConditionBase * > anonymous_namespace{Condition.cpp}::FlattenAndNestedConditions (const std::vector< Condition::ConditionBase *> &input_conditions)
const ConditionBase * Condition::anonymous_namespace{Condition.cpp}::GetCombatTargetCondition (ContentType content_type, const std::string &name)
const std::string & Condition::anonymous_namespace{Condition.cpp}::GetContentTypeName (ContentType content_type)
const ConditionBase * Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition (ContentType content_type, const std::string &name1, const std::string &name2)
bool Condition::anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
bool Condition::anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose (std::shared_ptr< const UniverseObject > sys1, std::shared_ptr< const UniverseObject > lane1_sys2, std::shared_ptr< const UniverseObject > lane2_sys2)
bool Condition::anonymous_namespace{Condition.cpp}::LanesCross (std::shared_ptr< const System > lane1_end_sys1, std::shared_ptr< const System > lane1_end_sys2, std::shared_ptr< const System > lane2_end_sys1, std::shared_ptr< const System > lane2_end_sys2)
bool Condition::anonymous_namespace{Condition.cpp}::LaneTooCloseToOtherSystem (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
std::string Condition::anonymous_namespace{Condition.cpp}::MeterTypeDumpString (MeterType meter)
int Condition::anonymous_namespace{Condition.cpp}::NumberOnQueue (const ProductionQueue &queue, BuildType build_type, const int location_id, const std::string &name="", int design_id=INVALID_DESIGN_ID)
bool Condition::anonymous_namespace{Condition.cpp}::ObjectTooCloseToLane (std::shared_ptr< const UniverseObject > lane_end_sys1, std::shared_ptr< const UniverseObject > lane_end_sys2, std::shared_ptr< const UniverseObject > obj)
void Condition::anonymous_namespace{Condition.cpp}::TransferRandomObjects (unsigned int number, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
void Condition::anonymous_namespace{Condition.cpp}::TransferSortedObjects (unsigned int number, ValueRef::ValueRefBase< double > *sort_key, const ScriptingContext &context, SortingMethod sorting_method, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
bool UserStringExists (const std::string &str)
Variables
int(* Condition::anonymous_namespace{Condition.cpp}::CRI)(int) = CustomRandInt
const std::string anonymous_namespace{Condition.cpp}::EMPTY_STRING
FO_COMMON_API const int INVALID_DESIGN_ID
Macro Definition Documentation
CHECK_COND_VREF_MEMBER
#define CHECK_COND_VREF_MEMBER (m_ptr)
Value:
{ if (m_ptr == rhs_.m_ptr) {              \
                                            /* check next member */             \
                                        } else if (!m_ptr || !rhs_.m_ptr) {     \
                                            return false;                       \
                                        } else {                                \
                                            if (*m_ptr != *(rhs_.m_ptr))        \
                                                return false;                   \
                                        }   }
Referenced by Condition::Number::operator==(), Condition::Turn::operator==(), Condition::SortedNumberOf::operator==(), Condition::EmpireAffiliation::operator==(), Condition::Homeworld::operator==(), Condition::Type::operator==(), Condition::Building::operator==(), Condition::HasSpecial::operator==(), Condition::HasTag::operator==(), Condition::CreatedOnTurn::operator==(), Condition::Contains::operator==(), Condition::ContainedBy::operator==(), Condition::InSystem::operator==(), Condition::ObjectID::operator==(), Condition::PlanetType::operator==(), Condition::PlanetSize::operator==(), Condition::PlanetEnvironment::operator==(), Condition::Species::operator==(), Condition::Enqueued::operator==(), Condition::FocusType::operator==(), Condition::StarType::operator==(), Condition::DesignHasHull::operator==(), Condition::DesignHasPart::operator==(), Condition::DesignHasPartClass::operator==(), Condition::PredefinedShipDesign::operator==(), Condition::NumberedShipDesign::operator==(), Condition::ProducedByEmpire::operator==(), Condition::Chance::operator==(), Condition::MeterValue::operator==(), Condition::ShipPartMeterValue::operator==(), Condition::EmpireMeterValue::operator==(), Condition::EmpireStockpileValue::operator==(), Condition::OwnerHasTech::operator==(), Condition::OwnerHasBuildingTypeAvailable::operator==(), Condition::OwnerHasShipDesignAvailable::operator==(), Condition::OwnerHasShipPartAvailable::operator==(), Condition::VisibleToEmpire::operator==(), Condition::WithinDistance::operator==(), Condition::WithinStarlaneJumps::operator==(), Condition::CanAddStarlaneConnection::operator==(), Condition::ExploredByEmpire::operator==(), Condition::FleetSupplyableByEmpire::operator==(), Condition::ResourceSupplyConnectedByEmpire::operator==(), Condition::OrderedBombarded::operator==(), Condition::ValueTest::operator==(), Condition::Location::operator==(), Condition::CombatTarget::operator==(), Condition::And::operator==(), Condition::Or::operator==(), Condition::Not::operator==(), Condition::OrderedAlternativesOf::operator==(), and Condition::Described::operator==().
Function Documentation
UserStringExists()
bool UserStringExists (const std::string & str)
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), PartsListBox::CullSuperfluousParts(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::PlanetEnvironment::Description(), Condition::Enqueued::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::PredefinedShipDesign::Description(), Condition::ShipPartMeterValue::Description(), Condition::OwnerHasTech::Description(), Condition::Described::Description(), ValueRef::UserStringLookup< FromType >::Eval(), MilitaryPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), PopulationPanel::EventFilter(), ResourcePanel::EventFilter(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::EventFilter(), FleetDataPanel::EventFilter(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{VarText.cpp}::MeterTypeString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString(), anonymous_namespace{ChatWnd.cpp}::UserStringSubstituteAndAppend::operator()(), anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::operator()(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), DesignWnd::MainPanel::ValidatedNameAndDescription(), anonymous_namespace{OptionsWnd.cpp}::ValidSectionForHotkey(), and FreeOrionPython::WrapAI().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by Condition::Enqueued::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::Enqueued::Match(), Condition::OwnerHasShipDesignAvailable::Match(), Condition::anonymous_namespace{Condition.cpp}::NumberOnQueue(), and Condition::anonymous_namespace{Condition.cpp}::NumberedShipDesignSimpleMatch::operator()().