FreeOrion: Conditions.cpp File Reference
Conditions.cpp File Reference
#include "Conditions.h"
#include <array>
#include <boost/algorithm/cxx11/all_of.hpp>
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/st_connected.hpp>
#include "BuildingType.h"
#include "Building.h"
#include "Fighter.h"
#include "Fleet.h"
#include "Meter.h"
#include "ObjectMap.h"
#include "Pathfinder.h"
#include "Planet.h"
#include "ShipDesign.h"
#include "ShipHull.h"
#include "ShipPart.h"
#include "Ship.h"
#include "Special.h"
#include "Species.h"
#include "System.h"
#include "UniverseObject.h"
#include "Universe.h"
#include "ValueRefs.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../Empire/Supply.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/Random.h"
#include "../util/ScopedTimer.h"
#include "../util/i18n.h"
Classes
struct Condition::anonymous_namespace{Conditions.cpp}::BuildingSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ChanceSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ContainedBySimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ContainsSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::CreatedOnTurnSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::DesignHasHullSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartClassSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ExploredByEmpireSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::FleetSupplyableSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::FocusTypeSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::HasSpecialSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::HasTagSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::HomeworldSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::InSystemSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::MeterValueSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::NumberedShipDesignSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ObjectIDSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OnPlanetSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OrderedBombardedSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OwnerHasShipDesignAvailableSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OwnerHasShipPartAvailableSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::OwnerHasTechSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::PlanetEnvironmentSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::PlanetSizeSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::PlanetTypeSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::PredefinedShipDesignSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ProducedByEmpireSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ResourceSupplySimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::ShipPartMeterValueSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::SpeciesSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::StarTypeSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::TypeSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::VisibleToEmpireSimpleMatch
struct Condition::anonymous_namespace{Conditions.cpp}::WithinDistanceSimpleMatch
struct Condition::Condition::MatchHelper
Namespaces
anonymous_namespace{Conditions.cpp}
Condition
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Condition::anonymous_namespace{Conditions.cpp}
Macros
#define CHECK_COND_VREF_MEMBER(m_ptr)
Functions
void anonymous_namespace{Conditions.cpp}::AddAllObjectsSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddBuildingSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddFieldSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddFleetSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddOptions (OptionsDB &db)
void anonymous_namespace{Conditions.cpp}::AddPlanetSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddPopCenterSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddResCenterSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddShipSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void anonymous_namespace{Conditions.cpp}::AddSystemSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
std::string Condition::anonymous_namespace{Conditions.cpp}::CompareTypeString (ComparisonType comp)
bool Condition::anonymous_namespace{Conditions.cpp}::Comparison (float val1, ComparisonType comp, float val2)
bool Condition::anonymous_namespace{Conditions.cpp}::Comparison (const std::string &val1, ComparisonType comp, const std::string &val2)
std::string Condition::ConditionDescription (const std::vector< const Condition * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Returns a single string which describes a vector of Conditions.
std::map< std::string, bool > anonymous_namespace{Conditions.cpp}::ConditionDescriptionAndTest (const std::vector< const Condition::Condition *> &conditions, const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate_object)
std::string Condition::ConditionFailedDescription (const std::vector< const Condition * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Same as ConditionDescription, but returns a string only with conditions that have not been met.
float Condition::anonymous_namespace{Conditions.cpp}::CrossProduct (float dx1, float dy1, float dx2, float dy2)
anonymous_namespace{Conditions.cpp}::DeclareThreadSafeLogger (conditions)
template<typename Pred >
void anonymous_namespace{Conditions.cpp}::EvalImpl (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, Condition::SearchDomain search_domain, const Pred &pred)
Used by 4-parameter Condition::Eval function, and some of its overrides, to scan through matches or non_matches set and apply pred to each object, to test if it should remain in its current set or be transferred from the search_domain specified set into the other.
void Condition::anonymous_namespace{Conditions.cpp}::FCMoveContent (ObjectSet &from_set, ObjectSet &to_set)
std::vector< const Condition::Condition * > anonymous_namespace{Conditions.cpp}::FlattenAndNestedConditions (const std::vector< const Condition::Condition *> &input_conditions)
const std::string & Condition::anonymous_namespace{Conditions.cpp}::GetCandidateFocus (const UniverseObject *candidate, const ObjectMap &objects)
const std::string & Condition::anonymous_namespace{Conditions.cpp}::GetCandidateSpecies (const UniverseObject *candidate, const ObjectMap &objects)
const Condition * Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition (ContentType content_type, const std::string &name)
const std::string & Condition::anonymous_namespace{Conditions.cpp}::GetContentTypeName (ContentType content_type)
const Condition * Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition (ContentType content_type, const std::string &name1, const std::string &name2)
bool Condition::anonymous_namespace{Conditions.cpp}::LaneCrossesExistingLane (const System *lane_end_sys1, const System *lane_end_sys2, const ObjectMap &objects)
bool Condition::anonymous_namespace{Conditions.cpp}::LanesAngularlyTooClose (const UniverseObject *sys1, const UniverseObject *lane1_sys2, const UniverseObject *lane2_sys2)
bool Condition::anonymous_namespace{Conditions.cpp}::LanesCross (const System *lane1_end_sys1, const System *lane1_end_sys2, const System *lane2_end_sys1, const System *lane2_end_sys2)
bool Condition::anonymous_namespace{Conditions.cpp}::LaneTooCloseToOtherSystem (const System *lane_end_sys1, const System *lane_end_sys2, const ObjectMap &objects)
std::string Condition::anonymous_namespace{Conditions.cpp}::MeterTypeDumpString (MeterType meter)
int Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue (const ProductionQueue &queue, BuildType build_type, const int location_id, const std::string &name="", int design_id=INVALID_DESIGN_ID)
bool Condition::anonymous_namespace{Conditions.cpp}::ObjectTooCloseToLane (const UniverseObject *lane_end_sys1, const UniverseObject *lane_end_sys2, const UniverseObject *obj)
void Condition::anonymous_namespace{Conditions.cpp}::TransferRandomObjects (unsigned int number, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
void Condition::anonymous_namespace{Conditions.cpp}::TransferSortedObjects (unsigned int number, ValueRef::ValueRef< double > *sort_key, const ScriptingContext &context, SortingMethod sorting_method, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
bool UserStringExists (const std::string &str)
Variables
const std::string anonymous_namespace{Conditions.cpp}::EMPTY_STRING
FO_COMMON_API const int INVALID_DESIGN_ID
bool anonymous_namespace{Conditions.cpp}::temp_bool = RegisterOptions(&AddOptions)
Macro Definition Documentation
CHECK_COND_VREF_MEMBER
#define CHECK_COND_VREF_MEMBER (m_ptr)
Value:
{ if (m_ptr == rhs_.m_ptr) {              \
                                            /* check next member */             \
                                        } else if (!m_ptr || !rhs_.m_ptr) {     \
                                            return false;                       \
                                        } else {                                \
                                            if (*m_ptr != *(rhs_.m_ptr))        \
                                                return false;                   \
                                        }   }
Referenced by Condition::Number::operator==(), Condition::Turn::operator==(), Condition::SortedNumberOf::operator==(), Condition::EmpireAffiliation::operator==(), Condition::Homeworld::operator==(), Condition::Type::operator==(), Condition::Building::operator==(), Condition::HasSpecial::operator==(), Condition::HasTag::operator==(), Condition::CreatedOnTurn::operator==(), Condition::Contains::operator==(), Condition::ContainedBy::operator==(), Condition::InOrIsSystem::operator==(), Condition::OnPlanet::operator==(), Condition::ObjectID::operator==(), Condition::PlanetType::operator==(), Condition::PlanetSize::operator==(), Condition::PlanetEnvironment::operator==(), Condition::Species::operator==(), Condition::Enqueued::operator==(), Condition::FocusType::operator==(), Condition::StarType::operator==(), Condition::DesignHasHull::operator==(), Condition::DesignHasPart::operator==(), Condition::DesignHasPartClass::operator==(), Condition::PredefinedShipDesign::operator==(), Condition::NumberedShipDesign::operator==(), Condition::ProducedByEmpire::operator==(), Condition::Chance::operator==(), Condition::MeterValue::operator==(), Condition::ShipPartMeterValue::operator==(), Condition::EmpireMeterValue::operator==(), Condition::EmpireStockpileValue::operator==(), Condition::EmpireHasAdoptedPolicy::operator==(), Condition::OwnerHasTech::operator==(), Condition::OwnerHasBuildingTypeAvailable::operator==(), Condition::OwnerHasShipDesignAvailable::operator==(), Condition::OwnerHasShipPartAvailable::operator==(), Condition::VisibleToEmpire::operator==(), Condition::WithinDistance::operator==(), Condition::WithinStarlaneJumps::operator==(), Condition::CanAddStarlaneConnection::operator==(), Condition::ExploredByEmpire::operator==(), Condition::FleetSupplyableByEmpire::operator==(), Condition::ResourceSupplyConnectedByEmpire::operator==(), Condition::OrderedBombarded::operator==(), Condition::ValueTest::operator==(), Condition::Location::operator==(), Condition::CombatTarget::operator==(), Condition::And::operator==(), Condition::Or::operator==(), Condition::Not::operator==(), Condition::OrderedAlternativesOf::operator==(), and Condition::Described::operator==().
Function Documentation
UserStringExists()
bool UserStringExists (const std::string & str)
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), PartsListBox::CullSuperfluousParts(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::PlanetEnvironment::Description(), Condition::Enqueued::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::PredefinedShipDesign::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireHasAdoptedPolicy::Description(), Condition::OwnerHasTech::Description(), Condition::Described::Description(), ValueRef::UserStringLookup< FromType >::Eval(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{VarText.cpp}::MeterTypeString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), anonymous_namespace{ChatWnd.cpp}::UserStringSubstitute(), DesignWnd::MainPanel::ValidatedNameAndDescription(), anonymous_namespace{OptionsWnd.cpp}::ValidSectionForHotkey(), ValueRefLinkText(), and FreeOrionPython::WrapAI().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by Condition::Enqueued::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::Enqueued::Match(), Condition::OwnerHasShipDesignAvailable::Match(), Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue(), and Condition::anonymous_namespace{Conditions.cpp}::NumberedShipDesignSimpleMatch::operator()().