FreeOrion: CUIWnd.cpp File Reference
CUIWnd.cpp File Reference
#include "CUIWnd.h"
#include "../client/human/GGHumanClientApp.h"
#include "ClientUI.h"
#include "CUIControls.h"
#include "Sound.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include <GG/GUI.h>
#include <limits>
#include <boost/algorithm/string.hpp>
Namespaces
anonymous_namespace{CUIWnd.cpp}
Functions
void anonymous_namespace{CUIWnd.cpp}::AddOptions (OptionsDB &db)
GG::WndFlag CLOSABLE (1<< 11)
GG::WndFlag MINIMIZABLE (1<< 10)
GG::WndFlag PINABLE (1<< 12)
void anonymous_namespace{CUIWnd.cpp}::PlayCloseSound ()
void anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound ()
void anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound ()
bool anonymous_namespace{CUIWnd.cpp}::RegisterWndFlags ()
std::string anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption (const std::string &option_name)
Variables
const double anonymous_namespace{CUIWnd.cpp}::BUTTON_DIMMING_SCALE_FACTOR = 0.75
bool anonymous_namespace{CUIWnd.cpp}::dummy = RegisterWndFlags()
const GG::X::value_type anonymous_namespace{CUIWnd.cpp}::INVALID_POS = std::numeric_limits<GG::X::value_type>::min()
const GG::X anonymous_namespace{CUIWnd.cpp}::INVALID_X = GG::X(INVALID_POS)
const GG::Y anonymous_namespace{CUIWnd.cpp}::INVALID_Y = GG::Y(INVALID_POS)
bool anonymous_namespace{CUIWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
CLOSABLE()
GG::WndFlag CLOSABLE (1<< 11)
Referenced by anonymous_namespace{CUIWnd.cpp}::RegisterWndFlags(), and CUI_PinButton::Toggle().
MINIMIZABLE()
GG::WndFlag MINIMIZABLE (1<< 10)
Referenced by anonymous_namespace{CUIWnd.cpp}::RegisterWndFlags(), and CUI_PinButton::Toggle().
PINABLE()
GG::WndFlag PINABLE (1<< 12)
Referenced by anonymous_namespace{CUIWnd.cpp}::RegisterWndFlags(), and CUI_PinButton::Toggle().