FreeOrion: DependencyVersions.cpp File Reference
DependencyVersions.cpp File Reference
Implement free functions to access the dependency versions.
#include "Version.h"
#include "Logger.h"
#include <sstream>
#include <zlib.h>
#include <boost/version.hpp>
Namespaces
anonymous_namespace{DependencyVersions.cpp}
Functions
std::map< std::string, std::string > DependencyVersions ()
Returns a map of dependency versions.
void LogDependencyVersions ()
Log the map returned by DependencyVersions() into the info log channel.
Detailed Description
Implement free functions to access the dependency versions.
Function Documentation
DependencyVersions()
std::map<std::string, std::string> DependencyVersions ()
Returns a map of dependency versions.
Returns
A map with the dependency versions. The key represents the dependency name, the value corresponding dependency version string.
Note
This function returns different dependencies, depending on which game executable it was called from.
Referenced by LogDependencyVersions().
LogDependencyVersions()
void LogDependencyVersions ()
Log the map returned by DependencyVersions() into the info log channel.
References DependencyVersions(), and InfoLogger.
Referenced by HumanClientApp::HumanClientApp(), and ServerApp::ServerApp().