FreeOrion: DesignWnd.cpp File Reference
DesignWnd.cpp File Reference
#include "DesignWnd.h"
#include "ClientUI.h"
#include "CUIWnd.h"
#include "CUIControls.h"
#include "QueueListBox.h"
#include "EncyclopediaDetailPanel.h"
#include "IconTextBrowseWnd.h"
#include "Sound.h"
#include "TextBrowseWnd.h"
#include "../parse/Parse.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/Order.h"
#include "../util/OptionsDB.h"
#include "../util/ScopedTimer.h"
#include "../util/Directories.h"
#include "../Empire/Empire.h"
#include "../client/human/HumanClientApp.h"
#include "../universe/Conditions.h"
#include "../universe/UniverseObject.h"
#include "../universe/ShipDesign.h"
#include "../universe/Enums.h"
#include <GG/DrawUtil.h>
#include <GG/StaticGraphic.h>
#include <GG/TabWnd.h>
#include <boost/cast.hpp>
#include <boost/function.hpp>
#include <boost/algorithm/string/replace.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/smart_ptr/make_unique.hpp>
#include <algorithm>
#include <iterator>
#include <unordered_set>
#include <unordered_map>
#include <functional>
Classes
class AllDesignsListBox
class anonymous_namespace{DesignWnd.cpp}::AvailabilityManager
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a ship design.
class anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager
DisplayedShipDesignManager allows for the storage and manipulation of an ordered list of design ids that are used to order the display of ShipDesigns in the DesignWnd and the ProductionWnd.
class anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager
class BasesListBox
List of starting points for designs, such as empty hulls, existing designs kept by this empire or seen elsewhere in the universe, design template scripts or saved (on disk) designs from previous games.
class BasesListBox::BasesListBoxRow
class BasesListBox::CompletedDesignListBoxRow
class BasesListBox::HullAndNamePanel
class BasesListBox::HullAndPartsListBoxRow
class CompletedDesignsListBox
class DesignWnd::BaseSelector
class DesignWnd::MainPanel
class DesignWnd::MainPanel::I18nString
I18nString stores a string that might be in the stringtable.
class DesignWnd::PartPalette
Contains graphical list of PartControl which can be dragged and dropped onto slots to assign parts to those slots.
class EmptyHullsListBox
class MonstersListBox
class PartControl
UI representation of a ship part.
class PartsListBox
Arrangement of PartControls that can be dragged onto SlotControls.
class PartsListBox::PartsListBoxRow
class SavedDesignsListBox
class SavedDesignsListBox::SavedDesignListBoxRow
class SlotControl
UI representation and drop-target for slots of a design.
Namespaces
anonymous_namespace{DesignWnd.cpp}
Typedefs
typedef std::map< std::pair< ShipPartClass, ShipSlotType >, std::vector< const PartType * > > anonymous_namespace{DesignWnd.cpp}::PartGroupsType
Functions
void anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns (const boost::uuids::uuid &uuid, int empire_id, bool is_front=true)
Add design to the is_front of empire_id's list of current designs.
const GG::Y anonymous_namespace{DesignWnd.cpp}::BASES_LIST_BOX_ROW_HEIGHT (100)
bool anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns (const ShipDesign *design)
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::CreateSaveFileNameForDesign (const ShipDesign &design)
void anonymous_namespace{DesignWnd.cpp}::DeleteFromDisplayedDesigns (const int design_id)
Remove design from DisplayedDesigns.
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::GetDesignsDir ()
DisplayedShipDesignManager & anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager ()
float anonymous_namespace{DesignWnd.cpp}::GetMainStat (const PartType *part_type)
SavedDesignsManager & anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager ()
bool LocationASubsumesLocationB (const Condition::Condition *check_part_loc, const Condition::Condition *ref_part_loc)
const int anonymous_namespace{DesignWnd.cpp}::PAD (3)
const GG::Y anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_HEIGHT (54)
const GG::X anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_WIDTH (54)
bool PartALocationSubsumesPartB (const PartType *check_part, const PartType *ref_part)
std::shared_ptr< GG::Texture > anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture (const PartType *part)
Returns background texture with which to render a PartControl, depending on the types of slot that the indicated part can be put into.
void anonymous_namespace{DesignWnd.cpp}::ReportFileError (const boost::filesystem::path &file)
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::SavedDesignsDir ()
void anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns (const int design_id, bool obsolete)
Set whether a currently known design is obsolete or not.
const GG::Y anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_HEIGHT (60)
const GG::X anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH (60)
std::shared_ptr< GG::Texture > anonymous_namespace{DesignWnd.cpp}::SlotBackgroundTexture (ShipSlotType slot_type)
Returns texture with which to render a SlotControl, depending on slot_type.
void anonymous_namespace{DesignWnd.cpp}::WriteToFile (const boost::filesystem::path &file, const std::string &ss)
Variables
const std::string anonymous_namespace{DesignWnd.cpp}::COMPLETE_DESIGN_ROW_DROP_STRING = "Complete Design Row"
const std::string anonymous_namespace{DesignWnd.cpp}::DES_BASE_SELECTOR_WND_NAME = "design.selector"
const std::string anonymous_namespace{DesignWnd.cpp}::DES_MAIN_WND_NAME = "design.edit"
const std::string anonymous_namespace{DesignWnd.cpp}::DES_PART_PALETTE_WND_NAME = "design.parts"
const std::string anonymous_namespace{DesignWnd.cpp}::DES_PEDIA_WND_NAME = "design.pedia"
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_EXTENSION = ".focs.txt"
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_PREFIX = "ShipDesign-"
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_MANIFEST_PREFIX = "ShipDesignOrdering"
const std::string anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING = ""
const std::string anonymous_namespace{DesignWnd.cpp}::HULL_PARTS_ROW_DROP_TYPE_STRING = "Hull and Parts Row"
FO_COMMON_API const int INVALID_DESIGN_ID
const std::string anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_DROP_TYPE_STRING = "Part Control"
const std::string anonymous_namespace{DesignWnd.cpp}::SAVED_DESIGN_ROW_DROP_STRING = "Saved Design Row"
const std::string anonymous_namespace{DesignWnd.cpp}::UNABLE_TO_OPEN_FILE = "Unable to open file"
Function Documentation
LocationASubsumesLocationB()
bool LocationASubsumesLocationB (const Condition::Condition * check_part_loc, const Condition::Condition * ref_part_loc)
Referenced by PartALocationSubsumesPartB().
PartALocationSubsumesPartB()
bool PartALocationSubsumesPartB (const PartType * check_part, const PartType * ref_part)
References if(), PartType::Location(), LocationASubsumesLocationB(), and PartType::Name().
Referenced by PartsListBox::CullSuperfluousParts().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by DesignWnd::MainPanel::AddDesign(), CompletedDesignsListBox::BaseDoubleClicked(), MonstersListBox::BaseDoubleClicked(), AllDesignsListBox::BaseDoubleClicked(), CompletedDesignsListBox::BaseRightClicked(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::InsertBefore(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::InsertOrderedIDs(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::MoveBefore(), CompletedDesignsListBox::QueueItemMoved(), and DesignWnd::MainPanel::ReplaceDesign().