FreeOrion: Diplomacy.h File Reference
Diplomacy.h File Reference
#include <string>
#include <boost/serialization/access.hpp>
#include "../util/Export.h"
Classes
class DiplomaticMessage
Functions
FO_COMMON_API DiplomaticMessage AcceptAlliesDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage AcceptPeaceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage AlliesProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage CancelDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage EndAllianceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
bool operator!= (const DiplomaticMessage &lhs, const DiplomaticMessage &rhs)
bool operator== (const DiplomaticMessage &lhs, const DiplomaticMessage &rhs)
FO_COMMON_API DiplomaticMessage PeaceProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage RejectProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
FO_COMMON_API DiplomaticMessage WarDeclarationDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
Function Documentation
FO_COMMON_API DiplomaticMessage AcceptAlliesDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ACCEPT_ALLIES_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage AcceptPeaceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ACCEPT_PEACE_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage AlliesProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ALLIES_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage CancelDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::CANCEL_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage EndAllianceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::END_ALLIANCE_DECLARATION.
Referenced by PlayerListWnd::PlayerRightClicked().
bool operator!= (const DiplomaticMessage & lhs, const DiplomaticMessage & rhs)
bool operator== (const DiplomaticMessage & lhs, const DiplomaticMessage & rhs)
References DiplomaticMessage::GetType(), DiplomaticMessage::RecipientEmpireID(), and DiplomaticMessage::SenderEmpireID().
Referenced by Condition::Aggressive::Aggressive(), Condition::All::All(), Condition::And::And(), Condition::Armed::Armed(), Condition::Building::Building(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Condition::CanColonize::CanColonize(), Condition::CanProduceShips::CanProduceShips(), Condition::Capital::Capital(), Condition::Chance::Chance(), Condition::ConditionBase::ConditionBase(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), Condition::CreatedOnTurn::CreatedOnTurn(), Condition::Described::Described(), Condition::DesignHasHull::DesignHasHull(), Condition::DesignHasPart::DesignHasPart(), Condition::DesignHasPartClass::DesignHasPartClass(), Condition::EmpireAffiliation::EmpireAffiliation(), Condition::EmpireMeterValue::EmpireMeterValue(), Condition::EmpireStockpileValue::EmpireStockpileValue(), Condition::Enqueued::Enqueued(), Condition::ExploredByEmpire::ExploredByEmpire(), Condition::FleetSupplyableByEmpire::FleetSupplyableByEmpire(), Condition::FocusType::FocusType(), Condition::HasSpecial::HasSpecial(), Condition::HasTag::HasTag(), Condition::Homeworld::Homeworld(), Condition::InSystem::InSystem(), Condition::Location::Location(), Condition::MeterValue::MeterValue(), Condition::Monster::Monster(), Condition::None::None(), Condition::Not::Not(), Condition::Number::Number(), Condition::NumberedShipDesign::NumberedShipDesign(), Condition::ObjectID::ObjectID(), Condition::Or::Or(), Condition::OrderedBombarded::OrderedBombarded(), Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable(), Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable(), Condition::OwnerHasShipPartAvailable::OwnerHasShipPartAvailable(), Condition::OwnerHasTech::OwnerHasTech(), Condition::PlanetEnvironment::PlanetEnvironment(), Condition::PlanetSize::PlanetSize(), Condition::PlanetType::PlanetType(), Condition::PredefinedShipDesign::PredefinedShipDesign(), Condition::ProducedByEmpire::ProducedByEmpire(), Condition::ResourceSupplyConnectedByEmpire::ResourceSupplyConnectedByEmpire(), Condition::RootCandidate::RootCandidate(), Condition::ShipPartMeterValue::ShipPartMeterValue(), Condition::SortedNumberOf::SortedNumberOf(), Condition::Source::Source(), Condition::Species::Species(), Condition::StarType::StarType(), Condition::Stationary::Stationary(), Condition::Target::Target(), Condition::Turn::Turn(), Condition::Type::Type(), Condition::ValueTest::ValueTest(), Condition::VisibleToEmpire::VisibleToEmpire(), Condition::WithinDistance::WithinDistance(), Condition::WithinStarlaneJumps::WithinStarlaneJumps(), and ValueRef::ValueRefBase< UniverseObjectType >::~ValueRefBase().
FO_COMMON_API DiplomaticMessage PeaceProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::PEACE_PROPOSAL.
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage RejectProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::REJECT_PROPOSAL.
Referenced by PlayerListWnd::PlayerRightClicked().
FO_COMMON_API DiplomaticMessage WarDeclarationDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::WAR_DECLARATION.
Referenced by PlayerListWnd::PlayerRightClicked().