FreeOrion: Diplomacy.cpp File Reference
Diplomacy.cpp File Reference
#include "Diplomacy.h"
Functions
DiplomaticMessage AcceptAlliesDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage AcceptPeaceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage AlliesProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage CancelDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage EndAllianceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
bool operator!= (const DiplomaticMessage &lhs, const DiplomaticMessage &rhs)
bool operator== (const DiplomaticMessage &lhs, const DiplomaticMessage &rhs)
DiplomaticMessage PeaceProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage RejectProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
DiplomaticMessage WarDeclarationDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
Variables
FO_COMMON_API const int ALL_EMPIRES
Function Documentation
DiplomaticMessage AcceptAlliesDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ACCEPT_ALLIES_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage AcceptPeaceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ACCEPT_PEACE_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage AlliesProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::ALLIES_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage CancelDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::CANCEL_PROPOSAL, and DiplomaticMessage::DiplomaticMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage EndAllianceDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::END_ALLIANCE_DECLARATION.
Referenced by PlayerListWnd::PlayerRightClicked().
bool operator!= (const DiplomaticMessage & lhs, const DiplomaticMessage & rhs)
bool operator== (const DiplomaticMessage & lhs, const DiplomaticMessage & rhs)
References DiplomaticMessage::GetType(), DiplomaticMessage::RecipientEmpireID(), and DiplomaticMessage::SenderEmpireID().
Referenced by Condition::Aggressive::Aggressive(), Condition::All::All(), Condition::Armed::Armed(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Condition::CanColonize::CanColonize(), Condition::CanProduceShips::CanProduceShips(), Condition::Capital::Capital(), Condition::ConditionBase::ConditionBase(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), Condition::Described::Described(), Condition::Monster::Monster(), Condition::None::None(), Condition::RootCandidate::RootCandidate(), Condition::Source::Source(), Condition::Stationary::Stationary(), Condition::Target::Target(), and ValueRef::ValueRefBase< T >::~ValueRefBase().
DiplomaticMessage PeaceProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::PEACE_PROPOSAL.
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage RejectProposalDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::REJECT_PROPOSAL.
Referenced by PlayerListWnd::PlayerRightClicked().
DiplomaticMessage WarDeclarationDiplomaticMessage (int sender_empire_id, int recipient_empire_id)
References DiplomaticMessage::DiplomaticMessage(), and DiplomaticMessage::WAR_DECLARATION.
Referenced by PlayerListWnd::PlayerRightClicked().
Variable Documentation
FO_COMMON_API const int ALL_EMPIRES