FreeOrion: Directories.cpp File Reference
Directories.cpp File Reference
#include "Directories.h"
#include "OptionsDB.h"
#include "i18n.h"
#include <GG/utf8/checked.h>
#include "../universe/Enums.h"
#include <boost/filesystem/convenience.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <cstdlib>
Namespaces
anonymous_namespace{Directories.cpp}
Functions
void CompleteXDGMigration ()
Migrates outstating user configuration and data to a XDG Base Diretory spec compliant directory.
auto FilenameTimestamp () -> std::string
Returns current timestamp in a form that can be used in file names.
auto FilenameToPath (std::string const &path_str) -> fs::path
Converts UTF-8 string into a path, doing any required wide-character conversions as determined by the operating system / filesystem.
auto GetBinDir () -> fs::path const
Returns the directory where the binaries are located.
auto GetConfigPath () -> fs::path const
Returns the full path to the configfile.
auto GetPath (PathType path_type) -> fs::path
Returns path currently defined for path_type.
auto GetPath (std::string const &path_string) -> fs::path
Returns path for path type cast from path_string.
auto GetPersistentConfigPath () -> fs::path const
Returns the full path to the configfile.
auto GetResourceDir () -> fs::path const
Returns the directory that contains all game resources.
auto GetRootDataDir () -> fs::path const
Returns the root data directory of FreeOrion.
auto GetSaveDir () -> fs::path const
Returns the directory where save files are located.
auto GetServerSaveDir () -> fs::path const
Returns the directory where server save files are located.
auto GetUserConfigDir () -> fs::path const
Returns the directory where FreeOrion store user configurations.
auto GetUserDataDir () -> fs::path const
Returns the directory where FreeOrion stores user specific data.
void InitBinDir (std::string const &argv0)
void InitDirs (std::string const &argv0)
Initializes the directories used by FreeOrion.
auto IsExistingFile (const fs::path &path) -> bool
auto IsFOCScript (const fs::path &path) -> bool
auto IsInDir (fs::path const &dir, fs::path const &test_dir) -> bool
auto ListDir (const fs::path &path, std::function< bool(const fs::path &)> predicate) -> std::vector< fs::path >
auto PathToString (fs::path const &path) -> std::string
auto PathTypeStrings () -> std::vector< std::string > const &
Returns a vector of strings for all PathTypes.
auto PathTypeToString (PathType path_type) -> std::string const &
auto RelativePath (fs::path const &from, fs::path const &to) -> fs::path
Variables
fs::path anonymous_namespace{Directories.cpp}::bin_dir = fs::initial_path()
const std::string anonymous_namespace{Directories.cpp}::EMPTY_STRING = ""
bool anonymous_namespace{Directories.cpp}::g_initialized = false
const std::string anonymous_namespace{Directories.cpp}::PATH_BINARY_STR = "PATH_BINARY"
const std::string anonymous_namespace{Directories.cpp}::PATH_CONFIG_STR = "PATH_CONFIG"
const std::string anonymous_namespace{Directories.cpp}::PATH_DATA_ROOT_STR = "PATH_DATA_ROOT"
const std::string anonymous_namespace{Directories.cpp}::PATH_DATA_USER_STR = "PATH_DATA_USER"
const std::string anonymous_namespace{Directories.cpp}::PATH_INVALID_STR = "PATH_INVALID"
const std::string anonymous_namespace{Directories.cpp}::PATH_PYTHON_STR = "PATH_PYTHON"
const std::string anonymous_namespace{Directories.cpp}::PATH_RESOURCE_STR = "PATH_RESOURCE"
const std::string anonymous_namespace{Directories.cpp}::PATH_SAVE_STR = "PATH_SAVE"
const std::string anonymous_namespace{Directories.cpp}::PATH_TEMP_STR = "PATH_TEMP"
Function Documentation
CompleteXDGMigration()
void CompleteXDGMigration ()
Migrates outstating user configuration and data to a XDG Base Diretory spec compliant directory.
It stores the current working directory as well as creating local directories if they do not yet exist.
Note
This function must be called before any Get*Dir function is called.
References OptionsDB::Get(), GetOptionsDB(), GetUserDataDir(), and OptionsDB::Set().
Referenced by mainConfigOptionsSetup().
FilenameTimestamp()
auto FilenameTimestamp () -> std::string
Returns current timestamp in a form that can be used in file names.
References TraceLogger.
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), and SaveFileDialog::Init().
FilenameToPath()
auto FilenameToPath (std::string const & path_str) -> boost::filesystem::path
Converts UTF-8 string into a path, doing any required wide-character conversions as determined by the operating system / filesystem.
Referenced by SaveFileDialog::CheckChoiceValidity(), SaveFileDialog::Confirm(), GetPath(), GetResourceDir(), GetSaveDir(), GetServerSaveDir(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), InitBinDir(), StringTable::Load(), LoadEmpireSaveGameData(), LoadGalaxySetupData(), LoadGame(), LoadPlayerSaveHeaderData(), HumanClientApp::LoadSinglePlayerGame(), SaveFileDialog::Result(), SaveGame(), SaveFileDialog::UpdatePreviewList(), ServerApp::UpdateSavePreviews(), anonymous_namespace{OptionsWnd.cpp}::ValidDirectory(), anonymous_namespace{OptionsWnd.cpp}::ValidFontFile(), anonymous_namespace{OptionsWnd.cpp}::ValidMusicFile(), anonymous_namespace{OptionsWnd.cpp}::ValidSoundFile(), and anonymous_namespace{OptionsWnd.cpp}::ValidStringtableFile().
GetBinDir()
auto GetBinDir () -> boost::filesystem::path const
Returns the directory where the binaries are located.
Defaults to:
Windows: Path to the installation directory.
Mac OS: Path to <FreeOrion App bundle>/Contents/Executables.
UNIX-like: Path to <installation prefix>/bin.
Note
This directory and everything in it should be assumed read-only!
References anonymous_namespace{Directories.cpp}::bin_dir, anonymous_namespace{Directories.cpp}::g_initialized, GetBinDir(), and InitDirs().
Referenced by anonymous_namespace{ServerApp.cpp}::AIClientExe(), GetBinDir(), GetPath(), and anonymous_namespace{HumanClientApp.cpp}::ServerClientExe().
GetConfigPath()
auto GetConfigPath () -> fs::path const
Returns the full path to the configfile.
References GetUserConfigDir().
Referenced by OptionsDB::Commit(), main(), and mainConfigOptionsSetup().
GetPath() [1/2]
auto GetPath (PathType path_type) -> fs::path
Returns path currently defined for path_type.
References ErrorLogger, GetBinDir(), GetResourceDir(), GetRootDataDir(), GetSaveDir(), GetUserConfigDir(), and GetUserDataDir().
Referenced by GetPath(), and anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes().
GetPath() [2/2]
auto GetPath (std::string const & path_string) -> fs::path
Returns path for path type cast from path_string.
References ErrorLogger, FilenameToPath(), GetPath(), PathToString(), and PathTypeStrings().
GetPersistentConfigPath()
auto GetPersistentConfigPath () -> fs::path const
Returns the full path to the configfile.
References GetUserConfigDir().
Referenced by OptionsDB::CommitPersistent(), main(), and mainConfigOptionsSetup().
GetResourceDir()
auto GetResourceDir () -> boost::filesystem::path const
Returns the directory that contains all game resources.
This covers:
game entity defintions
graphics
Translations
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by ClientUI::ArtDir(), CreditsWnd::CreditsWnd(), anonymous_namespace{i18n.cpp}::DevDefaultEnglishStringtablePath(), anonymous_namespace{AIWrapper.cpp}::GetAIDir(), anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName(), GetPath(), GetPythonDir(), anonymous_namespace{ServerWrapper.cpp}::GetResourceDirWrapper(), PythonAI::InitModules(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), ListDir(), mainConfigOptionsSetup(), parse::process_include_substitutions(), ClientUI::SoundDir(), IApp::StartBackgroundParsing(), and ServerApp::StartBackgroundParsing().
GetRootDataDir()
auto GetRootDataDir () -> boost::filesystem::path const
Returns the root data directory of FreeOrion.
Defaults to:
Windows: Path to the installation directory.
Mac OS: Path to <FreeOrion App bundle>/Contents/Resources.
UNIX-like: Path to <installation prefix>/share/freeorion.
Note
This directory and everything in it should be assumed read-only!
References br_find_data_dir, anonymous_namespace{Directories.cpp}::g_initialized, and InitDirs().
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{ClientUI.cpp}::AddOptions(), About::CompleteConstruction(), OptionsWnd::CompleteConstruction(), OptionsWnd::FontOption(), GetPath(), and ScanlineRenderer::Impl::StartUsing().
GetSaveDir()
auto GetSaveDir () -> boost::filesystem::path const
Returns the directory where save files are located.
This is typically the directory "save" within the user directory.
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by HumanClientApp::Autosave(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), GetPath(), SaveFileDialog::Init(), InitDirs(), SaveFileListBox::LoadLocalSaveGamePreviews(), anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame(), and SaveGame().
GetServerSaveDir()
auto GetServerSaveDir () -> boost::filesystem::path const
Returns the directory where server save files are located.
This is typically the directory "save" within the user directory.
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by HumanClientApp::Autosave(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), anonymous_namespace{ServerApp.cpp}::IsInServerSaveDir(), anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories(), MPLobby::react(), SaveGame(), and ServerApp::UpdateSavePreviews().
GetUserConfigDir()
auto GetUserConfigDir () -> boost::filesystem::path const
Returns the directory where FreeOrion store user configurations.
This covers:
user configuration
Defaults to:
Windows: Path to appdata%.
MacOS: Path to${HOME}/Library/FreeOrion.
UNIX-like: Follows XDG Base Dir spec; Path to${XDG_CONFIG_HOME}/freeorion`.
Note
If the directory does not exist, it will be created.
This directory can be considered writable!
References GetUserDataDir().
Referenced by GetConfigPath(), GetPath(), GetPersistentConfigPath(), anonymous_namespace{ConfigWrapper.cpp}::GetUserConfigDirWrapper(), and InitDirs().
GetUserDataDir()
auto GetUserDataDir () -> boost::filesystem::path const
Returns the directory where FreeOrion stores user specific data.
This covers:
savegames
log files
Defaults to:
Windows: Path to appdata%.
MacOS: Path to${HOME}/Library/FreeOrion.
UNIX-like: Follows XDG Base Dir spec; Path to${XDG_DATA_HOME}/freeorion`.
Note
If the directory does not exist, it will be created.
This directory can be considered writable!
References anonymous_namespace{Directories.cpp}::g_initialized, and InitDirs().
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), AIClientApp::AIClientApp(), OptionsWnd::CompleteConstruction(), CompleteXDGMigration(), GetPath(), GetUserConfigDir(), anonymous_namespace{ConfigWrapper.cpp}::GetUserDataDirWrapper(), HumanClientApp::HumanClientApp(), InitDirs(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsDir(), and ServerApp::ServerApp().
InitBinDir()
void InitBinDir (std::string const & argv0)
References anonymous_namespace{Directories.cpp}::bin_dir, br_find_bin_dir, and FilenameToPath().
Referenced by InitDirs().
InitDirs()
void InitDirs (std::string const & argv0)
Initializes the directories used by FreeOrion.
Note
This function completes the migration of directories to the XDG specified location by updating the save.path option to the new location after the option is loaded from XML files. It only updates the option if it is set to the old default option.
References br_init, anonymous_namespace{Directories.cpp}::g_initialized, GetSaveDir(), GetUserConfigDir(), GetUserDataDir(), and InitBinDir().
Referenced by GetBinDir(), GetRootDataDir(), GetUserDataDir(), main(), and mainConfigOptionsSetup().
IsExistingFile()
auto IsExistingFile (const fs::path & path) -> bool
References ErrorLogger, and PathToString().
Referenced by anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::PlanetEnvFilenames().
IsFOCScript()
auto IsFOCScript (const fs::path & path) -> bool
Referenced by parse::buildings(), parse::encyclopedia_articles(), parse::fields(), parse::policies(), parse::ship_designs(), parse::ship_hulls(), parse::ship_parts(), parse::specials(), parse::species(), parse::statistics(), and parse::techs().
IsInDir()
auto IsInDir (fs::path const & dir, fs::path const & test_dir) -> bool
Referenced by anonymous_namespace{ServerApp.cpp}::IsInServerSaveDir(), and SaveGame().
ListDir()
auto ListDir (const fs::path & path, std::function< bool(const fs::path &)> predicate) -> std::vector<fs::path>
References DebugLogger, GetResourceDir(), PathToString(), and TraceLogger.
Referenced by parse::buildings(), parse::encyclopedia_articles(), parse::fields(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PlanetEnvFilenames(), parse::policies(), parse::process_include_substitutions(), parse::ship_designs(), parse::ship_hulls(), parse::ship_parts(), parse::specials(), parse::species(), parse::statistics(), and parse::techs().
PathToString()
auto PathToString (fs::path const & path) -> std::string
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), HumanClientApp::Autosave(), HumanClientApp::BrowsePath(), OptionsDB::Commit(), SaveFileDialog::Confirm(), anonymous_namespace{DesignWnd.cpp}::CreateSaveFileNameForDesign(), SaveFileListBox::FindLocalRelativeDirs(), Sound::Impl::FreeSound(), anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName(), GetPath(), anonymous_namespace{ServerWrapper.cpp}::GetResourceDirWrapper(), anonymous_namespace{i18n.cpp}::GetStringTable(), anonymous_namespace{ConfigWrapper.cpp}::GetUserConfigDirWrapper(), anonymous_namespace{ConfigWrapper.cpp}::GetUserDataDirWrapper(), SaveFileDialog::Init(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), IsExistingFile(), ListDir(), anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories(), anonymous_namespace{SaveGamePreviewUtils.cpp}::LoadSaveGamePreviewData(), mainConfigOptionsSetup(), anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::PlanetEnvFilenames(), Sound::Impl::PlayMusic(), Sound::Impl::PlaySound(), parse::process_include_substitutions(), anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes(), SaveFileDialog::Result(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifestConst(), anonymous_namespace{HumanClientApp.cpp}::ServerClientExe(), SaveFileDialog::SetDirPath(), and anonymous_namespace{DesignWnd.cpp}::WriteToFile().
PathTypeStrings()
auto PathTypeStrings () -> std::vector<std::string> const&
Returns a vector of strings for all PathTypes.
References PathTypeToString().
Referenced by GetPath(), and anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes().
PathTypeToString()
auto PathTypeToString (PathType path_type) -> std::string const&
References anonymous_namespace{Directories.cpp}::EMPTY_STRING, anonymous_namespace{Directories.cpp}::PATH_BINARY_STR, anonymous_namespace{Directories.cpp}::PATH_CONFIG_STR, anonymous_namespace{Directories.cpp}::PATH_DATA_ROOT_STR, anonymous_namespace{Directories.cpp}::PATH_DATA_USER_STR, anonymous_namespace{Directories.cpp}::PATH_INVALID_STR, anonymous_namespace{Directories.cpp}::PATH_PYTHON_STR, anonymous_namespace{Directories.cpp}::PATH_RESOURCE_STR, anonymous_namespace{Directories.cpp}::PATH_SAVE_STR, and anonymous_namespace{Directories.cpp}::PATH_TEMP_STR.
Referenced by anonymous_namespace{LinkText.cpp}::BrowsePathLinkText(), TextLinker::FindLinks(), and PathTypeStrings().
RelativePath()
auto RelativePath (fs::path const & from, fs::path const & to) -> fs::path
Referenced by anonymous_namespace{OptionsWnd.cpp}::BrowseForPathButtonFunctor::operator()().