FreeOrion: Directories.h File Reference
Directories.h File Reference
#include <string>
#include <boost/filesystem/path.hpp>
#include <GG/Enum.h>
#include "Export.h"
Functions
FO_COMMON_API void CompleteXDGMigration ()
Migrates outstating user configuration and data to a XDG Base Diretory spec compliant directory.
FO_COMMON_API auto FilenameTimestamp () -> std::string
Returns current timestamp in a form that can be used in file names.
FO_COMMON_API auto FilenameToPath (std::string const &path_str) -> boost::filesystem::path
Converts UTF-8 string into a path, doing any required wide-character conversions as determined by the operating system / filesystem.
FO_COMMON_API auto GetBinDir () -> boost::filesystem::path const
Returns the directory where the binaries are located.
FO_COMMON_API auto GetConfigPath () -> boost::filesystem::path const
Returns the full path to the configfile.
FO_COMMON_API auto GetPath (PathType path_type) -> boost::filesystem::path
Returns path currently defined for path_type.
FO_COMMON_API auto GetPath (std::string const &path_string) -> boost::filesystem::path
Returns path for path type cast from path_string.
FO_COMMON_API auto GetPersistentConfigPath () -> boost::filesystem::path const
Returns the full path to the configfile.
FO_COMMON_API auto GetResourceDir () -> boost::filesystem::path const
Returns the directory that contains all game resources.
FO_COMMON_API auto GetRootDataDir () -> boost::filesystem::path const
Returns the root data directory of FreeOrion.
FO_COMMON_API auto GetSaveDir () -> boost::filesystem::path const
Returns the directory where save files are located.
FO_COMMON_API auto GetServerSaveDir () -> boost::filesystem::path const
Returns the directory where server save files are located.
FO_COMMON_API auto GetUserConfigDir () -> boost::filesystem::path const
Returns the directory where FreeOrion store user configurations.
FO_COMMON_API auto GetUserDataDir () -> boost::filesystem::path const
Returns the directory where FreeOrion stores user specific data.
GG_ENUM (PathType, PATH_BINARY, PATH_RESOURCE, PATH_PYTHON, PATH_DATA_ROOT, PATH_DATA_USER, PATH_CONFIG, PATH_SAVE, PATH_TEMP, PATH_INVALID) FO_COMMON_API auto PathTypeToString(PathType path_type) -> std::string const &
Types of root directories.
FO_COMMON_API void InitDirs (std::string const &argv0)
Initializes the directories used by FreeOrion.
FO_COMMON_API auto IsExistingFile (boost::filesystem::path const &path) -> bool
Returns true iff path exists and is a regular file.
FO_COMMON_API auto IsFOCScript (boost::filesystem::path const &path) -> bool
Returns true if the given path referrs to a FO content script and false otherwise.
FO_COMMON_API auto IsInDir (boost::filesystem::path const &dir, boost::filesystem::path const &test_dir) -> bool
Returns true iff the test_dir is in dir and dir is existing directory.
FO_COMMON_API auto ListDir (boost::filesystem::path const &path, std::function< bool(boost::filesystem::path const &)> predicate=nullptr) -> std::vector< boost::filesystem::path >
Returns a vector of pathes within path including a recursive search though sub-dirs.
FO_COMMON_API auto PathToString (boost::filesystem::path const &path) -> std::string
Returns an utf-8 encoded string from the given filesystem path.
FO_COMMON_API auto PathTypeStrings () -> std::vector< std::string > const &
Returns a vector of strings for all PathTypes.
FO_COMMON_API auto RelativePath (boost::filesystem::path const &from, boost::filesystem::path const &to) -> boost::filesystem::path
Returns the path to to, as it appears from from.
Function Documentation
CompleteXDGMigration()
FO_COMMON_API void CompleteXDGMigration ()
Migrates outstating user configuration and data to a XDG Base Diretory spec compliant directory.
It stores the current working directory as well as creating local directories if they do not yet exist.
Note
This function must be called before any Get*Dir function is called.
References OptionsDB::Get(), GetOptionsDB(), GetUserDataDir(), and OptionsDB::Set().
Referenced by mainConfigOptionsSetup().
FilenameTimestamp()
FO_COMMON_API auto FilenameTimestamp () -> std::string
Returns current timestamp in a form that can be used in file names.
References TraceLogger.
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), and SaveFileDialog::Init().
FilenameToPath()
FO_COMMON_API auto FilenameToPath (std::string const & path_str) -> boost::filesystem::path
Converts UTF-8 string into a path, doing any required wide-character conversions as determined by the operating system / filesystem.
Referenced by SaveFileDialog::CheckChoiceValidity(), SaveFileDialog::Confirm(), GetPath(), GetResourceDir(), GetSaveDir(), GetServerSaveDir(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), InitBinDir(), StringTable::Load(), LoadEmpireSaveGameData(), LoadGalaxySetupData(), LoadGame(), LoadPlayerSaveHeaderData(), HumanClientApp::LoadSinglePlayerGame(), SaveFileDialog::Result(), SaveGame(), SaveFileDialog::UpdatePreviewList(), ServerApp::UpdateSavePreviews(), anonymous_namespace{OptionsWnd.cpp}::ValidDirectory(), anonymous_namespace{OptionsWnd.cpp}::ValidFontFile(), anonymous_namespace{OptionsWnd.cpp}::ValidMusicFile(), anonymous_namespace{OptionsWnd.cpp}::ValidSoundFile(), and anonymous_namespace{OptionsWnd.cpp}::ValidStringtableFile().
GetBinDir()
FO_COMMON_API auto GetBinDir () -> boost::filesystem::path const
Returns the directory where the binaries are located.
Defaults to:
Windows: Path to the installation directory.
Mac OS: Path to <FreeOrion App bundle>/Contents/Executables.
UNIX-like: Path to <installation prefix>/bin.
Note
This directory and everything in it should be assumed read-only!
References anonymous_namespace{Directories.cpp}::bin_dir, anonymous_namespace{Directories.cpp}::g_initialized, GetBinDir(), and InitDirs().
Referenced by anonymous_namespace{ServerApp.cpp}::AIClientExe(), GetBinDir(), GetPath(), and anonymous_namespace{HumanClientApp.cpp}::ServerClientExe().
GetConfigPath()
FO_COMMON_API auto GetConfigPath () -> boost::filesystem::path const
Returns the full path to the configfile.
References GetUserConfigDir().
Referenced by OptionsDB::Commit(), main(), and mainConfigOptionsSetup().
GetPath() [1/2]
FO_COMMON_API auto GetPath (PathType path_type) -> boost::filesystem::path
Returns path currently defined for path_type.
References ErrorLogger, GetBinDir(), GetResourceDir(), GetRootDataDir(), GetSaveDir(), GetUserConfigDir(), and GetUserDataDir().
Referenced by GetPath(), and anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes().
GetPath() [2/2]
FO_COMMON_API auto GetPath (std::string const & path_string) -> boost::filesystem::path
Returns path for path type cast from path_string.
References ErrorLogger, FilenameToPath(), GetPath(), PathToString(), and PathTypeStrings().
GetPersistentConfigPath()
FO_COMMON_API auto GetPersistentConfigPath () -> boost::filesystem::path const
Returns the full path to the configfile.
References GetUserConfigDir().
Referenced by OptionsDB::CommitPersistent(), main(), and mainConfigOptionsSetup().
GetResourceDir()
FO_COMMON_API auto GetResourceDir () -> boost::filesystem::path const
Returns the directory that contains all game resources.
This covers:
game entity defintions
graphics
Translations
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by ClientUI::ArtDir(), anonymous_namespace{i18n.cpp}::DevDefaultEnglishStringtablePath(), anonymous_namespace{AIWrapper.cpp}::GetAIDir(), anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName(), GetPath(), GetPythonDir(), anonymous_namespace{ServerWrapper.cpp}::GetResourceDirWrapper(), PythonAI::InitModules(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), ListDir(), mainConfigOptionsSetup(), IntroScreen::OnCredits(), parse::process_include_substitutions(), ClientUI::SoundDir(), IApp::StartBackgroundParsing(), and ServerApp::StartBackgroundParsing().
GetRootDataDir()
FO_COMMON_API auto GetRootDataDir () -> boost::filesystem::path const
Returns the root data directory of FreeOrion.
Defaults to:
Windows: Path to the installation directory.
Mac OS: Path to <FreeOrion App bundle>/Contents/Resources.
UNIX-like: Path to <installation prefix>/share/freeorion.
Note
This directory and everything in it should be assumed read-only!
References br_find_data_dir, anonymous_namespace{Directories.cpp}::g_initialized, and InitDirs().
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{ClientUI.cpp}::AddOptions(), About::CompleteConstruction(), OptionsWnd::CompleteConstruction(), OptionsWnd::FontOption(), GetPath(), and ScanlineRenderer::Impl::StartUsing().
GetSaveDir()
FO_COMMON_API auto GetSaveDir () -> boost::filesystem::path const
Returns the directory where save files are located.
This is typically the directory "save" within the user directory.
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by HumanClientApp::Autosave(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), GetPath(), SaveFileDialog::Init(), InitDirs(), SaveFileListBox::LoadLocalSaveGamePreviews(), anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame(), and SaveGame().
GetServerSaveDir()
FO_COMMON_API auto GetServerSaveDir () -> boost::filesystem::path const
Returns the directory where server save files are located.
This is typically the directory "save" within the user directory.
References FilenameToPath(), OptionsDB::Get(), OptionsDB::GetDefault(), and GetOptionsDB().
Referenced by HumanClientApp::Autosave(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), anonymous_namespace{ServerApp.cpp}::IsInServerSaveDir(), anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories(), MPLobby::react(), SaveGame(), and ServerApp::UpdateSavePreviews().
GetUserConfigDir()
FO_COMMON_API auto GetUserConfigDir () -> boost::filesystem::path const
Returns the directory where FreeOrion store user configurations.
This covers:
user configuration
Defaults to:
Windows: Path to appdata%.
MacOS: Path to${HOME}/Library/FreeOrion.
UNIX-like: Follows XDG Base Dir spec; Path to${XDG_CONFIG_HOME}/freeorion`.
Note
If the directory does not exist, it will be created.
This directory can be considered writable!
References GetUserDataDir().
Referenced by GetConfigPath(), GetPath(), GetPersistentConfigPath(), anonymous_namespace{ConfigWrapper.cpp}::GetUserConfigDirWrapper(), and InitDirs().
GetUserDataDir()
FO_COMMON_API auto GetUserDataDir () -> boost::filesystem::path const
Returns the directory where FreeOrion stores user specific data.
This covers:
savegames
log files
Defaults to:
Windows: Path to appdata%.
MacOS: Path to${HOME}/Library/FreeOrion.
UNIX-like: Follows XDG Base Dir spec; Path to${XDG_DATA_HOME}/freeorion`.
Note
If the directory does not exist, it will be created.
This directory can be considered writable!
References anonymous_namespace{Directories.cpp}::g_initialized, and InitDirs().
Referenced by anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), AIClientApp::AIClientApp(), OptionsWnd::CompleteConstruction(), CompleteXDGMigration(), GetPath(), GetUserConfigDir(), anonymous_namespace{ConfigWrapper.cpp}::GetUserDataDirWrapper(), HumanClientApp::HumanClientApp(), InitDirs(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsDir(), and ServerApp::ServerApp().
GG_ENUM()
GG_ENUM (PathType , PATH_BINARY , PATH_RESOURCE , PATH_PYTHON , PATH_DATA_ROOT , PATH_DATA_USER , PATH_CONFIG , PATH_SAVE , PATH_TEMP , PATH_INVALID) -> std::string const &
Types of root directories.
Returns a string representation of PathType
InitDirs()
FO_COMMON_API void InitDirs (std::string const & argv0)
Initializes the directories used by FreeOrion.
Note
This function completes the migration of directories to the XDG specified location by updating the save.path option to the new location after the option is loaded from XML files. It only updates the option if it is set to the old default option.
References br_init, anonymous_namespace{Directories.cpp}::g_initialized, GetSaveDir(), GetUserConfigDir(), GetUserDataDir(), and InitBinDir().
Referenced by GetBinDir(), GetRootDataDir(), GetUserDataDir(), main(), and mainConfigOptionsSetup().
IsExistingFile()
FO_COMMON_API auto IsExistingFile (boost::filesystem::path const & path) -> bool
Returns true iff path exists and is a regular file.
IsFOCScript()
FO_COMMON_API auto IsFOCScript (boost::filesystem::path const & path) -> bool
Returns true if the given path referrs to a FO content script and false otherwise.
IsInDir()
FO_COMMON_API auto IsInDir (boost::filesystem::path const & dir, boost::filesystem::path const & test_dir) -> bool
Returns true iff the test_dir is in dir and dir is existing directory.
ListDir()
FO_COMMON_API auto ListDir (boost::filesystem::path const & path, std::function< bool(boost::filesystem::path const &)> predicate = nullptr) -> std::vector< boost::filesystem::path >
Returns a vector of pathes within path including a recursive search though sub-dirs.
When passing a predicate, the pathes need to match this predicate. If no predicate is given pathes need to refer to files.
PathToString()
FO_COMMON_API auto PathToString (boost::filesystem::path const & path) -> std::string
Returns an utf-8 encoded string from the given filesystem path.
PathTypeStrings()
FO_COMMON_API auto PathTypeStrings () -> std::vector< std::string > const &
Returns a vector of strings for all PathTypes.
References PathTypeToString().
Referenced by GetPath(), and anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes().
RelativePath()
FO_COMMON_API auto RelativePath (boost::filesystem::path const & from, boost::filesystem::path const & to) -> boost::filesystem::path
Returns the path to to, as it appears from from.