FreeOrion: dmain.cpp File Reference
dmain.cpp File Reference
#include "ServerApp.h"
#include <codecvt>
#include <locale>
#include "../util/OptionsDB.h"
#include "../util/Directories.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/Version.h"
#include <boost/filesystem/fstream.hpp>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References OptionsDB::Add(), OptionsDB::AddFlag(), tag_parser::args, DebugLogger, ErrorLogger, FreeOrionVersionString(), OptionsDB::Get(), GetConfigPath(), GetOptionsDB(), GetPersistentConfigPath(), OptionsDB::GetUsage(), help_arg, InitDirs(), OptionsDB::SetFromCommandLine(), OptionsDB::SetFromFile(), ShutdownLoggingSystemFileSink(), and UserStringNop.