FreeOrion: EmpireManager.h File Reference
EmpireManager.h File Reference
#include "Diplomacy.h"
#include "../universe/EnumsFwd.h"
#include "../util/Export.h"
#include "../util/Serialize.h"
#include <GG/Clr.h>
#include <boost/filesystem.hpp>
#include <boost/serialization/access.hpp>
#include <boost/signals2/signal.hpp>
#include <map>
#include <set>
#include <string>
#include <vector>
Classes
class EmpireManager
Maintains all of the Empire objects that exist in the application.
Functions
FO_COMMON_API const std::vector< GG::Clr > & EmpireColors ()
The colors that are available for use for empires in the game.
FO_COMMON_API void InitEmpireColors (const boost::filesystem::path &path)
Initialize empire colors from path.
Function Documentation
FO_COMMON_API const std::vector<GG::Clr>& EmpireColors ()
The colors that are available for use for empires in the game.
References EmpireColorsNonConst().
Referenced by EmpireColorSelector::EmpireColorSelector(), anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour(), InitEmpires(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), and HumanClientApp::NewSinglePlayerGame().
FO_COMMON_API void InitEmpireColors (const boost::filesystem::path & path)
Initialize empire colors from path.
References XMLElement::attributes, XMLElement::children, EmpireColorsNonConst(), ErrorLogger, XMLDoc::ReadDoc(), and XMLDoc::root_node.
Referenced by IApp::StartBackgroundParsing().