FreeOrion: EmpireManager.cpp File Reference
EmpireManager.cpp File Reference
#include "EmpireManager.h"
#include "Empire.h"
#include "../util/Directories.h"
#include "../util/GameRules.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/XMLDoc.h"
#include <boost/filesystem/fstream.hpp>
Namespaces
anonymous_namespace{EmpireManager.cpp}
Functions
std::pair< int, int > anonymous_namespace{EmpireManager.cpp}::DiploKey (int id1, int ind2)
const std::vector< EmpireColor > & EmpireColors ()
The colors that are available for use for empires in the game.
std::vector< EmpireColor > & EmpireColorsNonConst ()
EmpireColor HexClr (const std::string &hex_colour)
Named ctor that constructs a EmpireColor from a string that represents the color channels in the format '#RRGGBB', '#RRGGBBAA' where each channel value ranges from 0 to FF.
void InitEmpireColors (const boost::filesystem::path &path)
Initialize empire colors from path.
Variables
const std::string anonymous_namespace{EmpireManager.cpp}::EMPTY_STRING
Function Documentation
EmpireColors()
const std::vector<EmpireColor>& EmpireColors ()
The colors that are available for use for empires in the game.
References EmpireColorsNonConst().
Referenced by EmpireColorSelector::EmpireColorSelector(), anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour(), InitEmpires(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), and GGHumanClientApp::NewSinglePlayerGame().
EmpireColorsNonConst()
std::vector<EmpireColor>& EmpireColorsNonConst ()
Referenced by EmpireColors(), and InitEmpireColors().
HexClr()
EmpireColor HexClr (const std::string & hex_colour) inline
Named ctor that constructs a EmpireColor from a string that represents the color channels in the format '#RRGGBB', '#RRGGBBAA' where each channel value ranges from 0 to FF.
When the alpha component is left out the alpha value FF is assumed.
Exceptions
std::invalid_argument if the hex_colour string is not well formed
Referenced by anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), and InitEmpireColors().
InitEmpireColors()
void InitEmpireColors (const boost::filesystem::path & path)
Initialize empire colors from path.
References XMLElement::attributes, XMLElement::children, EmpireColorsNonConst(), ErrorLogger, HexClr(), XMLDoc::ReadDoc(), anonymous_namespace{About.cpp}::ReadFile(), and XMLDoc::root_node.
Referenced by IApp::StartBackgroundParsing().