FreeOrion: Encyclopedia.h File Reference
Encyclopedia.h File Reference
#include <map>
#include <string>
#include <vector>
#include <boost/optional/optional.hpp>
#include "../util/Export.h"
#include "../util/Pending.h"
Classes
class Encyclopedia
struct EncyclopediaArticle
Functions
FO_COMMON_API Encyclopedia & GetEncyclopedia ()
Function Documentation
GetEncyclopedia()
FO_COMMON_API Encyclopedia& GetEncyclopedia ()
Referenced by CheckSumContent(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SearchPediaArticlesForWords(), and IApp::StartBackgroundParsing().