FreeOrion: Encyclopedia.cpp File Reference
Encyclopedia.cpp File Reference
#include "Encyclopedia.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/CheckSums.h"
#include "../parse/Parse.h"
Namespaces
CheckSums
Functions
void CheckSums::CheckSumCombine (unsigned int &sum, const Encyclopedia &c)
const Encyclopedia & GetEncyclopedia ()
Function Documentation
const Encyclopedia& GetEncyclopedia ()
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetPediaArticle(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag().