FreeOrion: Enums.cpp File Reference
Enums.cpp File Reference
#include "Enums.h"
#include <cassert>
Namespaces
anonymous_namespace{Enums.cpp}
Functions
MeterType AssociatedMeterType (MeterType meter_type)
const std::map< MeterType, MeterType > & AssociatedMeterTypes ()
ResourceType MeterToResource (MeterType type)
const std::vector< std::string > & PathTypeStrings ()
const std::string & PathTypeToString (PathType path_type)
MeterType ResourceToMeter (ResourceType type)
MeterType ResourceToTargetMeter (ResourceType type)
Variables
const std::string anonymous_namespace{Enums.cpp}::EMPTY_STRING = ""
const std::string anonymous_namespace{Enums.cpp}::PATH_BINARY_STR = "PATH_BINARY"
const std::string anonymous_namespace{Enums.cpp}::PATH_CONFIG_STR = "PATH_CONFIG"
const std::string anonymous_namespace{Enums.cpp}::PATH_DATA_ROOT_STR = "PATH_DATA_ROOT"
const std::string anonymous_namespace{Enums.cpp}::PATH_DATA_USER_STR = "PATH_DATA_USER"
const std::string anonymous_namespace{Enums.cpp}::PATH_INVALID_STR = "PATH_INVALID"
const std::string anonymous_namespace{Enums.cpp}::PATH_PYTHON_STR = "PATH_PYTHON"
const std::string anonymous_namespace{Enums.cpp}::PATH_RESOURCE_STR = "PATH_RESOURCE"
const std::string anonymous_namespace{Enums.cpp}::PATH_SAVE_STR = "PATH_SAVE"
const std::string anonymous_namespace{Enums.cpp}::PATH_TEMP_STR = "PATH_TEMP"
Function Documentation
MeterType AssociatedMeterType (MeterType meter_type)
Returns the target or max meter type that is associated with the given active meter type. If no associated meter type exists, INVALID_METER_TYPE is returned.
References AssociatedMeterTypes(), and INVALID_METER_TYPE.
Referenced by MilitaryPanel::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), MilitaryPanel::Update(), ResourcePanel::Update(), and PopulationPanel::Update().
const std::map<MeterType, MeterType>& AssociatedMeterTypes ()
Returns mapping from active to target or max meter types that correspond. eg. METER_RESEARCH -> METER_TARGET_RESEARCH
References METER_CONSTRUCTION, METER_DEFENSE, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_RESEARCH, METER_SHIELD, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by AssociatedMeterType(), and SetActiveMetersToTargetMaxCurrentValues().
ResourceType MeterToResource (MeterType type)
Returns the equivalent resource type for the given meter type; if no such resource type exists, returns INVALID_RESOURCE_TYPE.
References METER_INDUSTRY, METER_RESEARCH, METER_STOCKPILE, and METER_TRADE.
Referenced by SidePanel::RefreshImpl().
const std::vector<std::string>& PathTypeStrings ()
References PathTypeToString().
Referenced by GetPath(), and anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes().
const std::string& PathTypeToString (PathType path_type)
References anonymous_namespace{Enums.cpp}::EMPTY_STRING, anonymous_namespace{Enums.cpp}::PATH_BINARY_STR, anonymous_namespace{Enums.cpp}::PATH_CONFIG_STR, anonymous_namespace{Enums.cpp}::PATH_DATA_ROOT_STR, anonymous_namespace{Enums.cpp}::PATH_DATA_USER_STR, anonymous_namespace{Enums.cpp}::PATH_INVALID_STR, anonymous_namespace{Enums.cpp}::PATH_PYTHON_STR, anonymous_namespace{Enums.cpp}::PATH_RESOURCE_STR, anonymous_namespace{Enums.cpp}::PATH_SAVE_STR, and anonymous_namespace{Enums.cpp}::PATH_TEMP_STR.
Referenced by anonymous_namespace{LinkText.cpp}::BrowsePathLinkText(), TextLinker::FindLinks(), and PathTypeStrings().
MeterType ResourceToMeter (ResourceType type)
References INVALID_METER_TYPE, METER_INDUSTRY, METER_RESEARCH, METER_STOCKPILE, and METER_TRADE.
Referenced by Fleet::ResourceOutput(), ResourcePool::Update(), and SystemResourceSummaryBrowseWnd::UpdateProduction().
MeterType ResourceToTargetMeter (ResourceType type)
References INVALID_METER_TYPE, METER_MAX_STOCKPILE, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, and METER_TARGET_TRADE.
Referenced by ResourcePool::Update().