FreeOrion: EnumText.cpp File Reference
EnumText.cpp File Reference
#include "EnumText.h"
#include "i18n.h"
Namespaces
anonymous_namespace{EnumText.cpp}
Functions
const std::string & TextForAIAggression (Aggression a)
Returns a user readable string for an Aggression.
const std::string & TextForGalaxySetupSetting (GalaxySetupOption gso)
Returns a user readable string for a GalaxySetupOption.
const std::string & TextForGalaxyShape (Shape shape)
Returns a user readable string for a Shape.
Variables
const std::string anonymous_namespace{EnumText.cpp}::EMPTY_STRING
Function Documentation
TextForAIAggression()
const std::string& TextForAIAggression (Aggression a)
Returns a user readable string for an Aggression.
References AGGRESSIVE, BEGINNER, CAUTIOUS, anonymous_namespace{EnumText.cpp}::EMPTY_STRING, MANIACAL, TURTLE, TYPICAL, and UserString().
Referenced by ColumnInPreview(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag().
TextForGalaxySetupSetting()
const std::string& TextForGalaxySetupSetting (GalaxySetupOption gso)
Returns a user readable string for a GalaxySetupOption.
References anonymous_namespace{EnumText.cpp}::EMPTY_STRING, and UserString().
Referenced by ColumnInPreview(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag().
TextForGalaxyShape()
const std::string& TextForGalaxyShape (Shape shape)
Returns a user readable string for a Shape.
References anonymous_namespace{EnumText.cpp}::EMPTY_STRING, and UserString().
Referenced by ColumnInPreview(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag().