FreeOrion: FieldType.cpp File Reference
FieldType.cpp File Reference
#include "FieldType.h"
#include <boost/algorithm/string/case_conv.hpp>
#include "ConditionSource.h"
#include "Effects.h"
#include "Enums.h"
#include "UniverseObject.h"
#include "ValueRefs.h"
#include "../util/CheckSums.h"
Namespaces
anonymous_namespace{FieldType.cpp}
Functions
const FieldType * GetFieldType (const std::string &name)
Returns the BuildingType specification object for a field of type name.
FieldTypeManager & GetFieldTypeManager ()
Returns the singleton field type manager.
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{FieldType.cpp}::IncreaseMeter (MeterType meter_type, double increase)
Function Documentation
GetFieldType()
const FieldType* GetFieldType (const std::string & name) -> const FieldType *
Returns the BuildingType specification object for a field of type name.
If no such FieldType exists, nullptr is returned instead.
References FieldTypeManager::GetFieldTypeManager().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), Effect::CreateField::Execute(), Field::Field(), ClientUI::FieldTexture(), Universe::GetEffectsAndTargets(), GetSpeciesConst(), Field::HasTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), Field::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToFieldType().
GetFieldTypeManager()
FieldTypeManager& GetFieldTypeManager ()
Returns the singleton field type manager.
References FieldTypeManager::GetFieldTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and IApp::StartBackgroundParsing().