FreeOrion: Field.h File Reference
Field.h File Reference
#include "UniverseObject.h"
#include "../util/Export.h"
#include "../util/Pending.h"
Classes
class Field
a class representing a region of space
class FieldType
A specification for a type of field.
class FieldTypeManager
Namespaces
Effect
Functions
FO_COMMON_API const FieldType * GetFieldType (const std::string &name)
Returns the BuildingType specification object for a field of type name.
FO_COMMON_API FieldTypeManager & GetFieldTypeManager ()
returns the singleton field type manager
Function Documentation
GetFieldType()
FO_COMMON_API const FieldType* GetFieldType (const std::string & name)
Returns the BuildingType specification object for a field of type name.
If no such FieldType exists, 0 is returned instead.
GetFieldTypeManager()
FO_COMMON_API FieldTypeManager& GetFieldTypeManager ()
returns the singleton field type manager
References FieldTypeManager::GetFieldTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and IApp::StartBackgroundParsing().