FreeOrion: FieldType.h File Reference
FieldType.h File Reference
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include "../util/Export.h"
#include "../util/Pending.h"
Classes
class FieldType
A specification for a type of Field.
class FieldTypeManager
Namespaces
Effect
Functions
FO_COMMON_API auto GetFieldType (const std::string &name) -> const FieldType *
Returns the BuildingType specification object for a field of type name.
FO_COMMON_API auto GetFieldTypeManager () -> FieldTypeManager &
Returns the singleton field type manager.
Function Documentation
GetFieldType()
FO_COMMON_API auto GetFieldType (const std::string & name) -> const FieldType *
Returns the BuildingType specification object for a field of type name.
If no such FieldType exists, nullptr is returned instead.
GetFieldTypeManager()
FO_COMMON_API auto GetFieldTypeManager () -> FieldTypeManager &
Returns the singleton field type manager.
References FieldTypeManager::GetFieldTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and IApp::StartBackgroundParsing().