FreeOrion: Field.cpp File Reference
Field.cpp File Reference
#include "Field.h"
#include "ConditionSource.h"
#include "Effects.h"
#include "Enums.h"
#include "Meter.h"
#include "Predicates.h"
#include "Universe.h"
#include "ValueRefs.h"
#include "../util/AppInterface.h"
#include "../util/OptionsDB.h"
#include "../util/Logger.h"
#include "../util/CheckSums.h"
#include "../util/ScopedTimer.h"
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/filesystem/fstream.hpp>
Namespaces
anonymous_namespace{Field.cpp}
Functions
const FieldType * GetFieldType (const std::string &name)
Returns the BuildingType specification object for a field of type name.
FieldTypeManager & GetFieldTypeManager ()
returns the singleton field type manager
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{Field.cpp}::IncreaseMeter (MeterType meter_type, double increase)
Function Documentation
GetFieldType()
const FieldType* GetFieldType (const std::string & name)
Returns the BuildingType specification object for a field of type name.
If no such FieldType exists, 0 is returned instead.
References FieldTypeManager::GetFieldType(), and FieldTypeManager::GetFieldTypeManager().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), Effect::CreateField::Execute(), Field::Field(), ClientUI::FieldTexture(), Universe::GetEffectsAndTargets(), Field::HasTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), Field::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToFieldType().
GetFieldTypeManager()
FieldTypeManager& GetFieldTypeManager ()
returns the singleton field type manager
References FieldTypeManager::GetFieldTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and IApp::StartBackgroundParsing().