FreeOrion: FleetButton.cpp File Reference
FleetButton.cpp File Reference
#include "FleetButton.h"
#include "FleetWnd.h"
#include "MapWnd.h"
#include "Sound.h"
#include "CUIDrawUtil.h"
#include "CUIControls.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../client/human/GGHumanClientApp.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/System.h"
#include "../Empire/Empire.h"
#include <GG/GLClientAndServerBuffer.h>
#include <algorithm>
Namespaces
anonymous_namespace{FleetButton.cpp}
Functions
void anonymous_namespace{FleetButton.cpp}::AddOptions (OptionsDB &db)
std::shared_ptr< GG::Texture > FleetBlockadedIcon (FleetButton::SizeType size_type)
float anonymous_namespace{FleetButton.cpp}::FleetButtonScaling ()
std::vector< std::shared_ptr< GG::Texture > > FleetHeadIcons (const Fleet *fleet, FleetButton::SizeType size_type)
std::vector< std::shared_ptr< GG::Texture > > FleetHeadIcons (const std::vector< const Fleet *> &fleets, FleetButton::SizeType size_type)
const std::string & anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix (FleetButton::SizeType size_type)
std::shared_ptr< GG::Texture > FleetSelectionIndicatorIcon ()
std::shared_ptr< GG::Texture > FleetSizeIcon (const Fleet *fleet, FleetButton::SizeType size_type)
std::shared_ptr< GG::Texture > FleetSizeIcon (unsigned int fleet_size, FleetButton::SizeType size_type)
int anonymous_namespace{FleetButton.cpp}::FleetSizeIconNumber (int number_ships)
Variables
bool anonymous_namespace{FleetButton.cpp}::temp_bool = RegisterOptions(&AddOptions)
constexpr float anonymous_namespace{FleetButton.cpp}::TWO_PI = 2.0*3.14159f
Function Documentation
FleetBlockadedIcon()
std::shared_ptr<GG::Texture> FleetBlockadedIcon (FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), ClientUI::GetClientUI(), ClientUI::GetTexture(), FleetButton::NONE, and FleetButton::TINY.
Referenced by FleetButton::Refresh().
FleetHeadIcons() [1/2]
std::vector<std::shared_ptr<GG::Texture> > FleetHeadIcons (const Fleet * fleet, FleetButton::SizeType size_type)
References FleetHeadIcons().
Referenced by FleetHeadIcons(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), FleetButton::Refresh(), and FleetDataPanel::Refresh().
FleetHeadIcons() [2/2]
std::vector<std::shared_ptr<GG::Texture> > FleetHeadIcons (const std::vector< const Fleet *> & fleets, FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), ClientUI::GetTexture(), and Objects().
FleetSelectionIndicatorIcon()
std::shared_ptr<GG::Texture> FleetSelectionIndicatorIcon ()
References ClientUI::ArtDir(), ClientUI::GetClientUI(), and ClientUI::GetTexture().
Referenced by FleetButton::Refresh().
FleetSizeIcon() [1/2]
std::shared_ptr<GG::Texture> FleetSizeIcon (const Fleet * fleet, FleetButton::SizeType size_type)
References FleetSizeIcon().
Referenced by FleetSizeIcon(), SystemIcon::NthFleetButtonUpperLeft(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), FleetButton::Refresh(), and FleetDataPanel::Refresh().
FleetSizeIcon() [2/2]
std::shared_ptr<GG::Texture> FleetSizeIcon (unsigned int fleet_size, FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), anonymous_namespace{FleetButton.cpp}::FleetSizeIconNumber(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), ClientUI::GetTexture(), FleetButton::NONE, and FleetButton::TINY.