FreeOrion: Fleet.h File Reference
Fleet.h File Reference
#include "ObjectMap.h"
#include "UniverseObject.h"
#include "../util/Enum.h"
#include "../util/Export.h"
Classes
struct MovePathNode
Contains info about a single notable point on the move path of a fleet or other UniverseObject.
Functions
EmpireManager & Empires ()
Accessor for the App's empire manager.
ObjectMap & Objects ()
Accessor for all (on server) or all known (on client) objects ObjectMap.
Function Documentation
Empires()
EmpireManager& Empires () inline
Accessor for the App's empire manager.
References IApp::Empires(), and IApp::GetApp().
Objects()
ObjectMap& Objects () inline
Accessor for all (on server) or all known (on client) objects ObjectMap.
References IApp::GetApp().