FreeOrion: FleetButton.h File Reference
FleetButton.h File Reference
#include <GG/Button.h>
#include <GG/StaticGraphic.h>
#include <memory>
Classes
class FleetButton
represents one or more fleets of an empire at a location on the map.
Functions
std::shared_ptr< GG::Texture > FleetBlockadedIcon (FleetButton::SizeType size_type)
std::vector< std::shared_ptr< GG::Texture > > FleetHeadIcons (const Fleet *fleet, FleetButton::SizeType size_type)
std::vector< std::shared_ptr< GG::Texture > > FleetHeadIcons (const std::vector< const Fleet *> &fleets, FleetButton::SizeType size_type)
std::shared_ptr< GG::Texture > FleetSelectionIndicatorIcon ()
std::shared_ptr< GG::Texture > FleetSizeIcon (const Fleet *fleet, FleetButton::SizeType size_type)
std::shared_ptr< GG::Texture > FleetSizeIcon (unsigned int fleet_size, FleetButton::SizeType size_type)
Function Documentation
FleetBlockadedIcon()
std::shared_ptr<GG::Texture> FleetBlockadedIcon (FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), ClientUI::GetClientUI(), ClientUI::GetTexture(), FleetButton::NONE, and FleetButton::TINY.
Referenced by FleetButton::Refresh().
FleetHeadIcons() [1/2]
std::vector<std::shared_ptr<GG::Texture> > FleetHeadIcons (const Fleet * fleet, FleetButton::SizeType size_type)
References FleetHeadIcons().
Referenced by FleetHeadIcons(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), FleetButton::Refresh(), and FleetDataPanel::Refresh().
FleetHeadIcons() [2/2]
std::vector<std::shared_ptr<GG::Texture> > FleetHeadIcons (const std::vector< const Fleet *> & fleets, FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), and ClientUI::GetTexture().
FleetSelectionIndicatorIcon()
std::shared_ptr<GG::Texture> FleetSelectionIndicatorIcon ()
References ClientUI::ArtDir(), ClientUI::GetClientUI(), and ClientUI::GetTexture().
Referenced by FleetButton::Refresh().
FleetSizeIcon() [1/2]
std::shared_ptr<GG::Texture> FleetSizeIcon (const Fleet * fleet, FleetButton::SizeType size_type)
References FleetSizeIcon(), and Fleet::NumShips().
Referenced by FleetSizeIcon(), SystemIcon::NthFleetButtonUpperLeft(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), FleetButton::Refresh(), and FleetDataPanel::Refresh().
FleetSizeIcon() [2/2]
std::shared_ptr<GG::Texture> FleetSizeIcon (unsigned int fleet_size, FleetButton::SizeType size_type)
References ClientUI::ArtDir(), anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix(), anonymous_namespace{FleetButton.cpp}::FleetSizeIconNumber(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), ClientUI::GetTexture(), FleetButton::NONE, and FleetButton::TINY.