FreeOrion: GameRules.h File Reference
GameRules.h File Reference
#include "OptionsDB.h"
#include "Pending.h"
Classes
class GameRules
Database of values that control how the game mechanics function.
struct GameRules::Rule
Typedefs
using GameRulesFn = void(*)(GameRules &)
the function signature for functions that add Rules to the GameRules (void (GameRules&))
Functions
FO_COMMON_API GameRules & GetGameRules ()
returns the single instance of the GameRules class
FO_COMMON_API bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules.
Typedef Documentation
GameRulesFn
using GameRulesFn = void (*) (GameRules&)
the function signature for functions that add Rules to the GameRules (void (GameRules&))
Function Documentation
GetGameRules()
FO_COMMON_API GameRules& GetGameRules ()
returns the single instance of the GameRules class
References DebugLogger, parse::game_rules(), and anonymous_namespace{GameRules.cpp}::GameRulesRegistry().
Referenced by ShipDesign::AdjustedAttack(), Policy::AdoptionCost(), AutoResolveCombat(), GameRulesPanel::BoolRuleChanged(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), anonymous_namespace{ProductionQueue.cpp}::CalculateProductionPerTurnLimit(), ServerApp::CheckForEmpireElimination(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), InGameMenu::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), GameRulesPanel::DoubleRuleChanged(), GameRulesPanel::DoubleRuleWidget(), ServerApp::EliminatePlayer(), ValueRef::ComplexVariable< T >::Eval(), GenerateStarlanes(), Planet::HabitableSize(), anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled(), CombatInfo::InitializeObjectVisibility(), IntroMenu::IntroMenu(), GameRulesPanel::IntRuleChanged(), GameRulesPanel::IntRuleWidget(), DiplomaticMessage::IsAllowed(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), HumanClientApp::NewSinglePlayerGame(), ServerApp::PostCombatProcessTurns(), BuildingType::ProductionCost(), ShipHull::ProductionCost(), ShipDesign::ProductionCost(), BuildingType::ProductionCostTimeLocationInvariant(), ShipHull::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionCostTimeLocationInvariant(), BuildingType::ProductionTime(), ShipHull::ProductionTime(), ShipDesign::ProductionTime(), Idle::react(), WaitingForGameStart::react(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), MapWnd::RenderStarlanes(), Tech::ResearchCost(), Tech::ResearchTime(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), ShipHull::Speed(), IApp::StartBackgroundParsing(), GameRulesPanel::StringRuleChanged(), GameRulesPanel::StringRuleWidget(), ShipHull::Structure(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapGalaxySetupData().
RegisterGameRules()
FO_COMMON_API bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules.
This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterGameRules(&foo)").
References anonymous_namespace{GameRules.cpp}::GameRulesRegistry().