FreeOrion: GameRulesParser.cpp File Reference
GameRulesParser.cpp File Reference
#include "../util/GameRules.h"
#include "PythonParserImpl.h"
#include <boost/python/args.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/object_core.hpp>
#include <boost/python/raw_function.hpp>
#include <boost/python/object_fwd.hpp>
#include <boost/python/str.hpp>
#include <boost/python/exec.hpp>
#include <boost/python/import.hpp>
#include <boost/python/stl_iterator.hpp>
#include <functional>
#include <string>
Classes
struct grammar
Namespaces
parse
The namespace that encloses the script file lexer and parser.
Functions
GameRules parse::game_rules (const PythonParser &parser, const boost::filesystem::path &path)
object insert_rule_ (const grammar &g, GameRules &game_rules, const tuple &args, const dict &kw)
Function Documentation
insert_rule_()
object insert_rule_ (const grammar & g, GameRules & game_rules, const tuple & args, const dict & kw)
References GameRules::Add(), DebugLogger, ErrorLogger, parse::game_rules(), max, and min.
Referenced by grammar::operator()().