FreeOrion: GameRules.cpp File Reference
GameRules.cpp File Reference
#include "GameRules.h"
Namespaces
anonymous_namespace{GameRules.cpp}
Functions
std::vector< GameRulesFn > & anonymous_namespace{GameRules.cpp}::GameRulesRegistry ()
GameRules & GetGameRules ()
returns the single instance of the GameRules class
bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules.
Function Documentation
GetGameRules()
GameRules& GetGameRules ()
returns the single instance of the GameRules class
References DebugLogger, parse::game_rules(), and anonymous_namespace{GameRules.cpp}::GameRulesRegistry().
Referenced by ShipDesign::AdjustedAttack(), AutoResolveCombat(), GameRulesPanel::BoolRuleChanged(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), anonymous_namespace{ProductionQueue.cpp}::CalculateProductionPerTurnLimit(), PartType::Capacity(), ServerApp::CheckForEmpireElimination(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), InGameMenu::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), GameRulesPanel::DoubleRuleChanged(), GameRulesPanel::DoubleRuleWidget(), ServerApp::EliminatePlayer(), ValueRef::ComplexVariable< T >::Eval(), GenerateStarlanes(), Planet::HabitableSize(), CombatInfo::InitializeObjectVisibility(), IntroMenu::IntroMenu(), GameRulesPanel::IntRuleChanged(), GameRulesPanel::IntRuleWidget(), DiplomaticMessage::IsAllowed(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), HumanClientApp::NewSinglePlayerGame(), ServerApp::PostCombatProcessTurns(), BuildingType::ProductionCost(), PartType::ProductionCost(), HullType::ProductionCost(), ShipDesign::ProductionCost(), BuildingType::ProductionCostTimeLocationInvariant(), PartType::ProductionCostTimeLocationInvariant(), HullType::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionCostTimeLocationInvariant(), BuildingType::ProductionTime(), PartType::ProductionTime(), HullType::ProductionTime(), ShipDesign::ProductionTime(), Idle::react(), WaitingForGameStart::react(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), MapWnd::RenderStarlanes(), Tech::ResearchCost(), Tech::ResearchTime(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), Empire::serialize(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), HullType::Speed(), IApp::StartBackgroundParsing(), GameRulesPanel::StringRuleChanged(), GameRulesPanel::StringRuleWidget(), HullType::Structure(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapGalaxySetupData().
RegisterGameRules()
bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules.
This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterGameRules(&foo)").
References anonymous_namespace{GameRules.cpp}::GameRulesRegistry().