FreeOrion: Government.h File Reference
Government.h File Reference
#include "../universe/ValueRef.h"
#include "../util/AppInterface.h"
#include "../util/Export.h"
#include "../util/Pending.h"
#include <boost/optional/optional.hpp>
#include <memory>
#include <string>
#include <map>
#include <set>
Classes
class Policy
class PolicyManager
Keeps track of policies that can be chosen by empires.
Namespaces
Effect
Functions
FO_COMMON_API const Policy * GetPolicy (const std::string &name)
FO_COMMON_API PolicyManager & GetPolicyManager ()
Function Documentation
GetPolicy()
FO_COMMON_API const Policy* GetPolicy (const std::string & name)
GetPolicyManager()
FO_COMMON_API PolicyManager& GetPolicyManager ()
Referenced by GovernmentWnd::PolicyPalette::CompleteConstruction(), GetPolicy(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PoliciesListBox::GroupAvailableDisplayablePolicies(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), ClientUI::PolicyIcon(), PoliciesListBox::ShowAllCategories(), IApp::StartBackgroundParsing(), and FreeOrionPython::WrapEmpire().