FreeOrion: Government.cpp File Reference
Government.cpp File Reference
#include "Government.h"
#include "../universe/Effect.h"
#include "../universe/UniverseObject.h"
#include "../universe/ObjectMap.h"
#include "../universe/ValueRef.h"
#include "../util/OptionsDB.h"
#include "../util/Logger.h"
#include "../util/AppInterface.h"
#include "../util/GameRules.h"
#include "../util/MultiplayerCommon.h"
#include "../util/CheckSums.h"
#include "../util/ScopedTimer.h"
#include "../Empire/EmpireManager.h"
#include <boost/filesystem/fstream.hpp>
Namespaces
anonymous_namespace{Government.cpp}
Functions
void anonymous_namespace{Government.cpp}::AddRules (GameRules &rules)
const Policy * GetPolicy (const std::string &name)
PolicyManager & GetPolicyManager ()
Variables
bool anonymous_namespace{Government.cpp}::temp_bool = RegisterGameRules(&AddRules)
Function Documentation
GetPolicy()
const Policy* GetPolicy (const std::string & name)
References PolicyManager::GetPolicy(), and GetPolicyManager().
Referenced by GovernmentWnd::MainPanel::FindEmptySlotForPolicy(), Universe::GetEffectsAndTargets(), anonymous_namespace{AIWrapper.cpp}::IssueAdoptPolicyOrder(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), GovernmentWnd::MainPanel::SetPolicy(), PolicySlotControl::SlotCategory(), InfluenceQueue::Update(), FreeOrionPython::WrapEmpire(), and ClientUI::ZoomToPolicy().
GetPolicyManager()
PolicyManager& GetPolicyManager ()
Referenced by GovernmentWnd::PolicyPalette::CompleteConstruction(), GetPolicy(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PoliciesListBox::GroupAvailableDisplayablePolicies(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), ClientUI::PolicyIcon(), PoliciesListBox::ShowAllCategories(), IApp::StartBackgroundParsing(), and FreeOrionPython::WrapEmpire().