FreeOrion: Hotkeys.h File Reference
Hotkeys.h File Reference
#include <GG/GUI.h>
#include <GG/Wnd.h>
#include <boost/signals2/shared_connection_block.hpp>
#include <functional>
#include <initializer_list>
Classes
class AndCondition
class FocusWindowCondition
On when the given window is visible.
class FocusWindowIsA< W >
class Hotkey
A single hotkey, ie just a combination key+modifier that has been given a certain name.
class HotkeyManager
class InvisibleWindowCondition
On when the given windows are invisible.
class OrCondition
class VisibleWindowCondition
On when the given window is visible.
Functions
bool NoModalWndsOpenCondition ()
On only when no modal Wnds are open.
Function Documentation
NoModalWndsOpenCondition()
bool NoModalWndsOpenCondition () inline
On only when no modal Wnds are open.
Referenced by HumanClientApp::ConnectKeyboardAcceleratorSignals(), MapWnd::ConnectKeyboardAcceleratorSignals(), and TechTreeWnd::LayoutPanel::ConnectKeyboardAcceleratorSignals().