FreeOrion: HumanClientFSM.cpp File Reference
HumanClientFSM.cpp File Reference
#include "HumanClientFSM.h"
#include "HumanClientApp.h"
#include "../../Empire/Empire.h"
#include "../../universe/System.h"
#include "../../universe/Species.h"
#include "../../network/Networking.h"
#include "../../network/ClientNetworking.h"
#include "../../util/i18n.h"
#include "../../util/MultiplayerCommon.h"
#include "../../util/OptionsDB.h"
#include "../../UI/ChatWnd.h"
#include "../../UI/PlayerListWnd.h"
#include "../../UI/IntroScreen.h"
#include "../../UI/MultiplayerLobbyWnd.h"
#include "../../UI/MapWnd.h"
#include <boost/format.hpp>
#include <thread>
Namespaces
anonymous_namespace{HumanClientFSM.cpp}
Macros
#define EVENT_CASE(r, data, name)
Functions
CombatLogManager & GetCombatLogManager ()
bool TraceHumanClientFSMExecution ()
Variables
const auto QUITTING_POLLING_INTERVAL = std::chrono::milliseconds(10)
const auto QUITTING_TIMEOUT = std::chrono::milliseconds(5000)
const bool anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION = true
Macro Definition Documentation
#define EVENT_CASE (r, data, name)
Value:
else if (dynamic_cast<const name*>(event_ptr))                      \
        most_derived_message_type_str = BOOST_PP_STRINGIZE(name);
Referenced by HumanClientFSM::unconsumed_event().
Function Documentation
CombatLogManager& GetCombatLogManager ()
Referenced by WaitingForGameStart::react(), and WaitingForTurnData::react().
bool TraceHumanClientFSMExecution ()
This function returns true iff the FSM's state instrumentation should be output to the logger's debug stream.
References anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
Variable Documentation
const auto QUITTING_POLLING_INTERVAL = std::chrono::milliseconds(10)
Referenced by QuittingGame::react().
const auto QUITTING_TIMEOUT = std::chrono::milliseconds(5000)
Referenced by QuittingGame::react().