FreeOrion: i18n.h File Reference
i18n.h File Reference
#include <string>
#include <vector>
#include <boost/format.hpp>
#include <boost/lexical_cast.hpp>
#include "Export.h"
Macros
#define UserStringNop(key) key
Placeholder for non local translations, evaluates to a non operation.
Functions
FO_COMMON_API std::string DoubleToString (double val, int digits, bool always_show_sign)
Converts double to string with digits digits.
FO_COMMON_API int EffectiveSign (double val)
Returns sign of value, accounting for SMALL_UI_DISPLAY_VALUE: +1 for positive values and -1 for negative values if their absolute value is larger than SMALL VALUE, and returns 0 for zero values or values with absolute value less than SMALL_UI_DISPLAY_VALUE.
FO_COMMON_API boost::format FlexibleFormat (const std::string &string_to_format)
Wraps boost::format such that it won't crash if passed the wrong number of arguments.
template<typename HeaderContainer , typename ListContainer >
boost::format FlexibleFormatList (const HeaderContainer &header_words, const ListContainer &words, const std::string &plural_header_template, const std::string &single_header_template, const std::string &empty_header_template, const std::string &dual_header_template)
returns a boost::format pre-filled with a list of up to 10 items with some introductory text similar to These are 3 fruit: apples, pears and bananas.
template<typename Container >
boost::format FlexibleFormatList (const Container &words)
template<typename Container >
boost::format FlexibleFormatList (const Container &words, const std::string &all_header)
template<typename Container >
boost::format FlexibleFormatList (const Container &words, const std::string &plural_header, const std::string &single_header)
template<typename Container >
boost::format FlexibleFormatList (const Container &words, const std::string &plural_header, const std::string &single_header, const std::string &empty_header)
template<typename T1 , typename T2 >
boost::format FlexibleFormatList (const T2 &header_words, const T1 &words)
template<typename T1 , typename T2 >
boost::format FlexibleFormatList (const T2 &header_words, const T1 &words, const std::string &all_header)
template<typename T1 , typename T2 >
boost::format FlexibleFormatList (const T2 &header_words, const T1 &words, const std::string &plural_header, const std::string &single_header)
template<typename T1 , typename T2 >
boost::format FlexibleFormatList (const T2 &header_words, const T1 &words, const std::string &plural_header, const std::string &single_header, const std::string &empty_header)
FO_COMMON_API void FlushLoadedStringTables ()
Clears all loaded strings, so that subsequent UserString lookups will cause the stringtable(s) to be reloaded.
FO_COMMON_API std::locale GetLocale (const std::string &name=std::string(""))
Returns locale, which may be previously cached.
const std::string & Language ()
Returns the language of the StringTable currently in use.
FO_COMMON_API std::string RomanNumber (unsigned int n)
Returns the stringified form of n as a roman number.
FO_COMMON_API const std::string & UserString (const std::string &str)
Returns a language-specific string for the key-string str.
FO_COMMON_API bool UserStringExists (const std::string &str)
Returns true iff a user-string exists for the key string str.
FO_COMMON_API std::vector< std::string > UserStringList (const std::string &key)
Returns a language-specific vector of strings for given key.
Macro Definition Documentation
UserStringNop
#define UserStringNop (key) key
Placeholder for non local translations, evaluates to a non operation.
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), anonymous_namespace{Networking.cpp}::AddOptions(), anonymous_namespace{MultiplayerCommon.cpp}::AddOptions(), anonymous_namespace{ResearchWnd.cpp}::AddOptions(), anonymous_namespace{CUIWnd.cpp}::AddOptions(), anonymous_namespace{SitRepPanel.cpp}::AddOptions(), anonymous_namespace{CUIControls.cpp}::AddOptions(), anonymous_namespace{ProductionWnd.cpp}::AddOptions(), anonymous_namespace{ServerConnectWnd.cpp}::AddOptions(), anonymous_namespace{TechTreeWnd.cpp}::AddOptions(), anonymous_namespace{BuildDesignatorWnd.cpp}::AddOptions(), anonymous_namespace{ObjectListWnd.cpp}::AddOptions(), anonymous_namespace{Universe.cpp}::AddOptions(), anonymous_namespace{FleetButton.cpp}::AddOptions(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::AddOptions(), anonymous_namespace{GraphicalSummary.cpp}::AddOptions(), anonymous_namespace{SaveFileDialog.cpp}::AddOptions(), anonymous_namespace{HumanClientApp.cpp}::AddOptions(), anonymous_namespace{MapWnd.cpp}::AddOptions(), anonymous_namespace{GalaxySetupWnd.cpp}::AddOptions(), anonymous_namespace{FleetWnd.cpp}::AddOptions(), anonymous_namespace{SidePanel.cpp}::AddOptions(), anonymous_namespace{ClientUI.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption(), CUIWnd::AddWindowOptions(), HumanClientApp::AddWindowSizeOptionsAfterMainStart(), anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), ServerApp::CheckForEmpireElimination(), FleetWnd::CompleteConstruction(), FilterDialog::CompleteConstruction(), CreateBuildingBuiltSitRep(), CreateBuildingTypeUnlockedSitRep(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateCombatSitRep(), CreateEmpireEliminatedSitRep(), CreateFleetArrivedAtDestinationSitRep(), CreateGroundCombatSitRep(), CreatePlanetCapturedSitRep(), CreatePlanetColonizedSitRep(), CreatePlanetDepopulatedSitRep(), CreatePlanetOutpostedSitRep(), CreateShipBlockBuiltSitRep(), CreateShipBuiltSitRep(), CreateShipHullUnlockedSitRep(), CreateShipPartUnlockedSitRep(), CreateTechResearchedSitRep(), CreateTechUnlockedSitRep(), CreateVictorySitRep(), ServerApp::EliminatePlayer(), ServerFSM::EstablishPlayer(), ServerApp::ExecuteScriptedTurnEvents(), ExtractErrorMessageData(), ServerApp::FillListPlayers(), ServerApp::GenerateUniverse(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), anonymous_namespace{CombatSystem.cpp}::GetWeapons(), ServerFSM::HandleNonLobbyDisconnection(), anonymous_namespace{ChatWnd.cpp}::HandleTextCommand(), Empire::Init(), SaveFileFileRow::Init(), DiplomaticMessage::IsAllowed(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), ServerApp::LoadGameInit(), main(), mainConfigOptionsSetup(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::NewGameInitVerifyJoiners(), anonymous_namespace{IntroScreen.cpp}::Options(), ProductionQueue::ProductionItem::ProductionItem(), ServerApp::PushChatMessage(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), ServerApp::SelectNewHost(), ServerFSM::UpdateIngameLobby(), MPLobby::ValidateClientLimits(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
Function Documentation
DoubleToString()
FO_COMMON_API std::string DoubleToString (double val, int digits, bool always_show_sign)
Converts double to string with digits digits.
Represents large numbers with SI prefixes.
References EffectiveSign(), anonymous_namespace{i18n.cpp}::LARGE_UI_DISPLAY_VALUE, anonymous_namespace{i18n.cpp}::RoundMagnitude(), to_string(), anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE, and UserString().
Referenced by anonymous_namespace{i18n.cpp}::TestRounding().
EffectiveSign()
FO_COMMON_API int EffectiveSign (double val)
Returns sign of value, accounting for SMALL_UI_DISPLAY_VALUE: +1 for positive values and -1 for negative values if their absolute value is larger than SMALL VALUE, and returns 0 for zero values or values with absolute value less than SMALL_UI_DISPLAY_VALUE.
References anonymous_namespace{i18n.cpp}::SMALL_UI_DISPLAY_VALUE, and anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE.
Referenced by DoubleToString(), and StatisticIcon::ValueColor().
FlexibleFormat()
FO_COMMON_API boost::format FlexibleFormat (const std::string & string_to_format)
Wraps boost::format such that it won't crash if passed the wrong number of arguments.
References ErrorLogger, and UserString().
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), PartType::CapacityDescription(), ResourceInfoPanel::Clear(), ResourceInfoPanel::ClearLocalInfo(), BoutBeginEvent::CombatLogDescription(), BoutEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), WeaponFireEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), FightersAttackFightersEvent::CombatLogDescription(), FighterLaunchEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), WeaponFireEvent::CombatLogDetails(), OptionsWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ValueRef::ComplexVariableDescription(), SaveFileDialog::Confirm(), Condition::Number::Description(), Condition::Turn::Description(), Condition::SortedNumberOf::Description(), Condition::EmpireAffiliation::Description(), Condition::Homeworld::Description(), Condition::Type::Description(), Condition::Building::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::CreatedOnTurn::Description(), Condition::Contains::Description(), Condition::ContainedBy::Description(), Condition::InSystem::Description(), Condition::ObjectID::Description(), Condition::PlanetType::Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), Condition::Species::Description(), Condition::Enqueued::Description(), Condition::FocusType::Description(), Condition::StarType::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::OwnerHasTech::Description(), Condition::VisibleToEmpire::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), Condition::CanAddStarlaneConnection::Description(), Condition::ExploredByEmpire::Description(), Condition::FleetSupplyableByEmpire::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), Condition::CanColonize::Description(), Condition::CanProduceShips::Description(), Condition::OrderedBombarded::Description(), Condition::ValueTest::Description(), Condition::Location::Description(), Condition::CombatTarget::Description(), DesignWnd::MainPanel::DesignChanged(), SitRepPanel::DismissalMenu(), MapWnd::EnableOrderIssuing(), ValueRef::Operation< T >::EvalImpl(), MilitaryPanel::EventFilter(), SpecialsPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), ResourcePanel::EventFilter(), PopulationPanel::EventFilter(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::EventFilter(), FleetDataPanel::EventFilter(), Effect::CreatePlanet::Execute(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FlexibleFormatList(), ValueRef::FormatedDescriptionPropertyNames(), Fleet::GenerateFleetName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), MessageWnd::HandleDiplomaticStatusChange(), AIClientApp::HandlePythonAICrash(), MessageWnd::HandleTurnPhaseUpdate(), MeterBrowseWnd::Initialize(), MapWnd::InitTurn(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::operator()(), PlayerListWnd::PlayerRightClicked(), PlayingTurn::PlayingTurn(), FPSIndicator::PreRender(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), FieldIcon::RClick(), BuildingIndicator::RClick(), TechTreeWnd::LayoutPanel::TechPanel::RClick(), MPLobby::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnData::react(), PlayingTurn::react(), BuildDesignatorWnd::BuildSelector::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), EncyclopediaDetailPanel::RefreshImpl(), anonymous_namespace{DesignWnd.cpp}::ReportFileError(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), ResourceInfoPanel::SetEmpireID(), ResourceInfoPanel::SetLocalPointsCost(), CombatLogWnd::Impl::SetLog(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), ValueRef::StatisticDescription(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), MapWnd::TimerFiring(), FleetWnd::TitleText(), SpecialsPanel::Update(), SitRepPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), MapWnd::MapScaleLine::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
FlexibleFormatList() [1/9]
template<typename HeaderContainer , typename ListContainer > boost::format FlexibleFormatList (const HeaderContainer & header_words, const ListContainer & words, const std::string & plural_header_template, const std::string & single_header_template, const std::string & empty_header_template, const std::string & dual_header_template)
returns a boost::format pre-filled with a list of up to 10 items with some introductory text similar to These are 3 fruit: apples, pears and bananas.
The Container types need to support size(), begin() and end(). The headers are boost::format strings fed the size of the words list and then any header words passed in. TODO: Adopt an out of house i18n framework and handle of empty, singular, pairs, triplets etc. correctly.
References FlexibleFormat(), and UserString().
Referenced by InitialStealthEvent::CombatLogDescription(), StealthChangeEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), and FlexibleFormatList().
FlexibleFormatList() [2/9]
template<typename Container > boost::format FlexibleFormatList (const Container & words)
References FlexibleFormatList(), and UserString().
FlexibleFormatList() [3/9]
template<typename Container > boost::format FlexibleFormatList (const Container & words, const std::string & all_header)
References FlexibleFormatList().
FlexibleFormatList() [4/9]
template<typename Container > boost::format FlexibleFormatList (const Container & words, const std::string & plural_header, const std::string & single_header)
References FlexibleFormatList().
FlexibleFormatList() [5/9]
template<typename Container > boost::format FlexibleFormatList (const Container & words, const std::string & plural_header, const std::string & single_header, const std::string & empty_header)
References FlexibleFormatList().
FlexibleFormatList() [6/9]
template<typename T1 , typename T2 > boost::format FlexibleFormatList (const T2 & header_words, const T1 & words)
References FlexibleFormatList(), and UserString().
FlexibleFormatList() [7/9]
template<typename T1 , typename T2 > boost::format FlexibleFormatList (const T2 & header_words, const T1 & words, const std::string & all_header)
References FlexibleFormatList().
FlexibleFormatList() [8/9]
template<typename T1 , typename T2 > boost::format FlexibleFormatList (const T2 & header_words, const T1 & words, const std::string & plural_header, const std::string & single_header)
References FlexibleFormatList().
FlexibleFormatList() [9/9]
template<typename T1 , typename T2 > boost::format FlexibleFormatList (const T2 & header_words, const T1 & words, const std::string & plural_header, const std::string & single_header, const std::string & empty_header)
References FlexibleFormatList().
FlushLoadedStringTables()
FO_COMMON_API void FlushLoadedStringTables ()
Clears all loaded strings, so that subsequent UserString lookups will cause the stringtable(s) to be reloaded.
References anonymous_namespace{i18n.cpp}::stringtable_access_mutex, and anonymous_namespace{i18n.cpp}::stringtables.
Referenced by OptionsWnd::CompleteConstruction().
GetLocale()
FO_COMMON_API std::locale GetLocale (const std::string & name = std::string(""))
Returns locale, which may be previously cached.
References ErrorLogger, InfoLogger, and TraceLogger.
Referenced by ClientUI::FormatTimestamp(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), anonymous_namespace{ObjectListWnd.cpp}::CustomRowCmp::operator()(), anonymous_namespace{MapWnd.cpp}::CustomRowCmp::operator()(), and TechTreeWnd::TechListBox::TechRowCmp().
Language()
const std::string& Language ()
Returns the language of the StringTable currently in use.
References anonymous_namespace{i18n.cpp}::GetStringTable(), StringTable::Language(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
RomanNumber()
FO_COMMON_API std::string RomanNumber (unsigned int n)
Returns the stringified form of n as a roman number.
"Only" defined for 1 <= n <= 3999, as we can't display the symbol for 5000.
Referenced by Planet::CardinalSuffix(), NewMonsterName(), Empire::NewShipName(), and FreeOrionPython::WrapServer().
UserString()
FO_COMMON_API const std::string& UserString (const std::string & str)
Returns a language-specific string for the key-string str.
References anonymous_namespace{i18n.cpp}::GetDefaultStringTable(), anonymous_namespace{i18n.cpp}::GetStringTable(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
Referenced by System::ApparentName(), SaveFileDialog::AskDelete(), EmptyHullsListBox::BaseRightClicked(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), OptionsWnd::BoolOption(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{LinkText.cpp}::BrowsePathLinkText(), Building::Building(), BuildingIndicator::BuildingIndicator(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), ObjectHeaderPanel::ButtonRightClicked(), PartType::CapacityDescription(), Planet::CardinalSuffix(), CensusRowPanel::CensusRowPanel(), MultiPlayerLobbyWnd::ChatMessage(), TechManager::CheckPendingTechs(), ResourceInfoPanel::Clear(), ResourceInfoPanel::ClearLocalInfo(), anonymous_namespace{ServerConnectWnd.cpp}::ClientTypeRow::ClientTypeRow(), OptionsWnd::ColorOption(), BoutBeginEvent::CombatLogDescription(), BoutEvent::CombatLogDescription(), InitialStealthEvent::CombatLogDescription(), StealthChangeEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), WeaponFireEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), FightersAttackFightersEvent::CombatLogDescription(), FighterLaunchEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), WeaponFireEvent::CombatLogDetails(), OptionsDB::Commit(), OptionsDB::CommitPersistent(), anonymous_namespace{SaveLoad.cpp}::CompileSaveGamePreviewData(), InGameMenu::CompleteConstruction(), PasswordEnterWnd::CompleteConstruction(), About::CompleteConstruction(), SitRepPanel::CompleteConstruction(), ModeratorActionsWnd::CompleteConstruction(), ObjectListWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), ProductionWnd::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), IntroScreen::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), SideBar::CompleteConstruction(), ResearchQueueWnd::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), anonymous_namespace{GalaxySetupWnd.cpp}::UserStringRow::CompleteConstruction(), BuildDesignatorWnd::BuildSelector::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), OptionsBar::CompleteConstruction(), FilterDialog::CompleteConstruction(), PartControl::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), DesignWnd::PartPalette::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), SlotControl::CompleteConstruction(), DesignWnd::MainPanel::CompleteConstruction(), ValueRef::ComplexVariableDescription(), InGameMenu::Concede(), Condition::ConditionDescription(), Condition::ConditionFailedDescription(), SaveFileDialog::Confirm(), anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateMonsterFleet(), anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), PartsListBox::CullSuperfluousParts(), Special::Description(), Condition::Number::Description(), ValueRef::Constant< T >::Description(), Condition::Turn::Description(), Condition::SortedNumberOf::Description(), Condition::All::Description(), Condition::None::Description(), Condition::EmpireAffiliation::Description(), Condition::Source::Description(), Condition::RootCandidate::Description(), Condition::Target::Description(), Condition::Homeworld::Description(), Condition::Capital::Description(), Condition::Monster::Description(), ShipDesign::Description(), Condition::Armed::Description(), Condition::Type::Description(), Condition::Building::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::CreatedOnTurn::Description(), Condition::Contains::Description(), Condition::ContainedBy::Description(), Condition::InSystem::Description(), Condition::ObjectID::Description(), Condition::PlanetType::Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), Condition::Species::Description(), Condition::Enqueued::Description(), Condition::FocusType::Description(), Condition::StarType::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::OwnerHasTech::Description(), Condition::OwnerHasBuildingTypeAvailable::Description(), Condition::OwnerHasShipDesignAvailable::Description(), Condition::OwnerHasShipPartAvailable::Description(), Condition::VisibleToEmpire::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), Condition::CanAddStarlaneConnection::Description(), Condition::ExploredByEmpire::Description(), Condition::Stationary::Description(), Condition::Aggressive::Description(), Condition::FleetSupplyableByEmpire::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), Condition::CanColonize::Description(), Condition::CanProduceShips::Description(), Condition::OrderedBombarded::Description(), Condition::ValueTest::Description(), Condition::Location::Description(), Condition::CombatTarget::Description(), Condition::And::Description(), Condition::Or::Description(), Condition::OrderedAlternativesOf::Description(), Condition::Described::Description(), DesignWnd::MainPanel::DesignChanged(), SitRepPanel::DismissalMenu(), DesignWnd::MainPanel::I18nString::DisplayText(), ObjectListWnd::DoLayout(), OptionsWnd::DoubleOption(), GameRulesPanel::DoubleRuleWidget(), DoubleToString(), CreditsWnd::DrawCredits(), Empire::Dump(), Condition::DesignHasPartClass::Dump(), anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings(), MapWnd::EnableOrderIssuing(), ServerFSM::EstablishPlayer(), ValueRef::StringCast< FromType >::Eval(), ValueRef::UserStringLookup< FromType >::Eval(), MilitaryPanel::EventFilter(), SpecialsPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), PopulationPanel::EventFilter(), ResourcePanel::EventFilter(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::EventFilter(), FleetDataPanel::EventFilter(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), Field::Field(), anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), OptionsWnd::FileOptionImpl(), SitRepPanel::FilterClicked(), MessageWndEdit::FindGameWords(), MapWnd::FleetButtonRightClicked(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), FlexibleFormat(), FlexibleFormatList(), ValueRef::FormatedDescriptionPropertyNames(), Species::GameplayDescription(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GeneralTypeOfObject(), Fleet::GenerateFleetName(), VarText::GenerateVarText(), ConditionWidget::GetCondition(), Condition::anonymous_namespace{Condition.cpp}::GetContentTypeName(), ObjectHeaderPanel::GetControls(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{SidePanel.cpp}::GetPlanetEnvironmentName(), anonymous_namespace{SidePanel.cpp}::GetPlanetSizeName(), anonymous_namespace{SidePanel.cpp}::GetPlanetTypeName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{SidePanel.cpp}::GetStarTypeName(), OptionsDB::GetUsage(), MessageWnd::HandleDiplomaticStatusChange(), DesignWnd::PartPalette::HandlePartTypeRightClicked(), AIClientApp::HandlePythonAICrash(), EncyclopediaDetailPanel::HandleSearchTextEntered(), MessageWnd::HandleTurnPhaseUpdate(), OptionsWnd::HotkeyOption(), OptionsWnd::HotkeysPage(), HumanClientApp::HumanClientApp(), anonymous_namespace{VarText.cpp}::IDString(), CombatReportWnd::Impl::Impl(), SaveFileDialog::Init(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), FleetDataPanel::Init(), InitEmpires(), MeterBrowseWnd::Initialize(), MapWnd::InitTurn(), OptionsWnd::IntOption(), GameRulesPanel::IntRuleWidget(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), QueueListBox::ItemRightClickedImpl(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), FleetButton::LayoutIcons(), LinkTaggedText(), LoadEmpireSaveGameData(), LoadPlayerSaveHeaderData(), HumanClientApp::LoadSinglePlayerGame(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), mainConfigOptionsSetup(), ClientUI::MessageBox(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterToUserString(), anonymous_namespace{VarText.cpp}::MeterTypeString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString(), HumanClientApp::MultiPlayerGame(), OptionsWnd::MusicVolumeOption(), FleetPlan::Name(), ShipDesign::Name(), anonymous_namespace{VarText.cpp}::NameString(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::NewLabelValue(), NewMonsterName(), Empire::NewShipName(), HumanClientApp::NewSinglePlayerGame(), ObjectListWnd::ObjectRightClicked(), anonymous_namespace{ChatWnd.cpp}::UserStringSubstituteAndAppend::operator()(), anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::operator()(), anonymous_namespace{VarText.cpp}::Substitute::operator()(), anonymous_namespace{SitRepPanel.cpp}::OrderedSitrepTemplateStrings(), anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix(), PlayerListWnd::PlayerRightClicked(), PlayingTurn::PlayingTurn(), PartsListBox::Populate(), BasesListBox::Populate(), MultiPlayerLobbyWnd::PopulatePlayerList(), FPSIndicator::PreRender(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), Field::PublicName(), Ship::PublicName(), Fleet::PublicName(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), FieldIcon::RClick(), CUILabel::RClick(), BuildingIndicator::RClick(), MapWnd::RClick(), LinkText::RClick(), CUIEdit::RClick(), CensoredCUIEdit::RClick(), CUIMultiEdit::RClick(), CUILinkTextMultiEdit::RClick(), SidePanel::PlanetPanel::RClick(), ColorSelector::RClick(), TechTreeWnd::LayoutPanel::TechPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), WaitingForSPHostAck::react(), Idle::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MPLobby::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnData::react(), PlayingTurn::react(), ModeratorActionsWnd::Refresh(), BuildingIndicator::Refresh(), BuildDesignatorWnd::BuildSelector::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSearchResultsTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshDetectionIndicator(), EncyclopediaDetailPanel::RefreshImpl(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTradeResourceIndicator(), anonymous_namespace{DesignWnd.cpp}::ReportFileError(), HumanClientApp::RequestSavePreviews(), ResearchWnd::ResearchWnd(), BasesListBox::ResetEmptyListPrompt(), CompletedDesignsListBox::ResetEmptyListPrompt(), SavedDesignsListBox::ResetEmptyListPrompt(), HumanClientApp::ResetOrExitApp(), OptionsWnd::ResolutionOption(), ResourceBrowseWnd::ResourceBrowseWnd(), DesignWnd::MainPanel::Sanitize(), InGameMenu::Save(), SaveGame(), BasesListBox::BasesListBoxRow::SetAvailability(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), ResourceInfoPanel::SetEmpireID(), OptionsDB::SetFromFile(), ResourceInfoPanel::SetLocalPointsCost(), CombatLogWnd::Impl::SetLog(), SlotControl::SetPart(), GalaxySetupPanel::SetSeed(), ResourceInfoPanel::SetStockpileCost(), anonymous_namespace{HumanClientApp.cpp}::SetStringtableDependentOptionDefaults(), EncyclopediaDetailPanel::SetText(), ResourceInfoPanel::SetTotalPointsCost(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), anonymous_namespace{CombatEvents.cpp}::ShipPartLink(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), About::ShowVision(), CombatSummary::SideName(), OptionsWnd::SoundFileOption(), OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow(), SpeciesSelector::SpeciesSelector(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), ValueRef::StatisticDescription(), ConditionWidget::StringRow::StringRow(), GameRulesPanel::StringRuleWidget(), anonymous_namespace{VarText.cpp}::SubstitutionMap(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), TextForAIAggression(), TextForGalaxySetupSetting(), TextForGalaxyShape(), MapWnd::TimerFiring(), SaveFileColumn::Title(), FleetWnd::TitleText(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{ValueRef.cpp}::TraceReference(), CUIStyle::Translate(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeRow::TypeRow(), SpecialsPanel::Update(), SitRepPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), MapWnd::MapScaleLine::Update(), FleetDataPanel::UpdateAggressionToggle(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), ResearchWnd::UpdateInfoPanel(), ProductionWnd::UpdateInfoPanel(), ConditionWidget::UpdateParameterControls(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), ShipFightersBrowseWnd::UpdateSummary(), UserStringList(), DesignWnd::MainPanel::ValidatedNameAndDescription(), OptionsWnd::VolumeOption(), FreeOrionPython::WrapAI(), FreeOrionPython::WrapServer(), anonymous_namespace{CombatEvents.cpp}::WrapUserStringWithTag(), and ClientUI::ZoomToContent().
UserStringExists()
FO_COMMON_API bool UserStringExists (const std::string & str)
Returns true iff a user-string exists for the key string str.
References anonymous_namespace{i18n.cpp}::GetDefaultStringTable(), anonymous_namespace{i18n.cpp}::GetStringTable(), StringTable::StringExists(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
UserStringList()
FO_COMMON_API std::vector<std::string> UserStringList (const std::string & key)
Returns a language-specific vector of strings for given key.
References anonymous_namespace{i18n.cpp}::stringtable_access_mutex, and UserString().
Referenced by anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), anonymous_namespace{Effect.cpp}::GenerateSystemName(), anonymous_namespace{ModeratorAction.cpp}::GenerateSystemName(), anonymous_namespace{AIWrapper.cpp}::GetUserStringList(), NewMonsterName(), and Empire::NewShipName().