FreeOrion: i18n.cpp File Reference
i18n.cpp File Reference
#include "i18n.h"
#include "Directories.h"
#include "Logger.h"
#include "OptionsDB.h"
#include "StringTable.h"
#include <boost/locale.hpp>
#include <boost/algorithm/string/case_conv.hpp>
#include <mutex>
Namespaces
anonymous_namespace{i18n.cpp}
Functions
const std::map< std::string, std::string > & AllStringtableEntries (bool default_table)
Returns all entries in current stringtable.
boost::filesystem::path anonymous_namespace{i18n.cpp}::DevDefaultEnglishStringtablePath ()
std::string DoubleToString (double val, int digits, bool always_show_sign)
Converts double to string with digits digits.
int EffectiveSign (double val)
Returns sign of value, accounting for SMALL_UI_DISPLAY_VALUE: +1 for positive values and -1 for negative values if their absolute value is larger than SMALL VALUE, and returns 0 for zero values or values with absolute value less than SMALL_UI_DISPLAY_VALUE.
boost::format FlexibleFormat (const std::string &string_to_format)
Wraps boost::format such that it won't crash if passed the wrong number of arguments.
void FlushLoadedStringTables ()
Clears all loaded strings, so that subsequent UserString lookups will cause the stringtable(s) to be reloaded.
boost::filesystem::path anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName ()
const StringTable & anonymous_namespace{i18n.cpp}::GetDevDefaultStringTable ()
std::locale GetLocale (const std::string &name)
Returns locale, which may be previously cached.
const StringTable & anonymous_namespace{i18n.cpp}::GetStringTable (boost::filesystem::path stringtable_path)
const StringTable & anonymous_namespace{i18n.cpp}::GetStringTable ()
std::string anonymous_namespace{i18n.cpp}::GetStringTableFileName ()
void anonymous_namespace{i18n.cpp}::InitStringtableFileName ()
const std::string & Language ()
Returns the language of the StringTable currently in use.
std::string RomanNumber (unsigned int n)
Returns the stringified form of n as a roman number.
double anonymous_namespace{i18n.cpp}::RoundMagnitude (double mag, int digits)
const std::string & UserString (const std::string &str)
Returns a language-specific string for the key-string str.
bool UserStringExists (const std::string &str)
Returns true iff a user-string exists for the key string str.
std::vector< std::string > UserStringList (const std::string &key)
Returns a language-specific vector of strings for given key.
Variables
const double anonymous_namespace{i18n.cpp}::LARGE_UI_DISPLAY_VALUE = 9.99999999e+9
const double anonymous_namespace{i18n.cpp}::SMALL_UI_DISPLAY_VALUE = 1.0e-6
std::recursive_mutex anonymous_namespace{i18n.cpp}::stringtable_access_mutex
bool anonymous_namespace{i18n.cpp}::stringtable_filename_init = false
std::map< std::string, std::shared_ptr< const StringTable > > anonymous_namespace{i18n.cpp}::stringtables
const double anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE = std::numeric_limits<double>::infinity()
Function Documentation
AllStringtableEntries()
const std::map<std::string, std::string>& AllStringtableEntries (bool default_table)
Returns all entries in current stringtable.
References StringTable::AllStrings(), anonymous_namespace{i18n.cpp}::GetDevDefaultStringTable(), anonymous_namespace{i18n.cpp}::GetStringTable(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires().
DoubleToString()
std::string DoubleToString (double val, int digits, bool always_show_sign)
Converts double to string with digits digits.
Represents large numbers with SI prefixes.
References EffectiveSign(), anonymous_namespace{i18n.cpp}::LARGE_UI_DISPLAY_VALUE, anonymous_namespace{i18n.cpp}::RoundMagnitude(), to_string(), anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE, and UserString().
Referenced by CensusRowPanel::CensusRowPanel(), anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ValueRef::Constant< T >::Description(), ValueRef::ComplexVariable< T >::Eval(), ValueRef::StringCast< FromType >::Eval(), ParticipantBar::ParticipantBar(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), EncyclopediaDetailPanel::RefreshImpl(), ResourceBrowseWnd::ResourceBrowseWnd(), anonymous_namespace{GGHumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), StatisticIcon::SetValue(), TechRowBrowseWnd(), SpecialsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
EffectiveSign()
int EffectiveSign (double val)
Returns sign of value, accounting for SMALL_UI_DISPLAY_VALUE: +1 for positive values and -1 for negative values if their absolute value is larger than SMALL VALUE, and returns 0 for zero values or values with absolute value less than SMALL_UI_DISPLAY_VALUE.
References anonymous_namespace{i18n.cpp}::SMALL_UI_DISPLAY_VALUE, and anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE.
Referenced by DoubleToString(), and StatisticIcon::SetValue().
FlexibleFormat()
boost::format FlexibleFormat (const std::string & string_to_format)
Wraps boost::format such that it won't crash if passed the wrong number of arguments.
References ErrorLogger, and UserString().
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), ResourceInfoPanel::Clear(), ResourceInfoPanel::ClearLocalInfo(), BoutBeginEvent::CombatLogDescription(), BoutEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), WeaponFireEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), FightersAttackFightersEvent::CombatLogDescription(), FighterLaunchEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), WeaponFireEvent::CombatLogDetails(), MilitaryPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), OptionsWnd::CompleteConstruction(), PopulationPanel::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), MapWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ValueRef::ComplexVariableDescription(), SaveFileDialog::Confirm(), Condition::Number::Description(), Condition::Turn::Description(), Condition::SortedNumberOf::Description(), Condition::EmpireAffiliation::Description(), Condition::Homeworld::Description(), Condition::Type::Description(), Condition::Building::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::CreatedOnTurn::Description(), Condition::Contains::Description(), Condition::ContainedBy::Description(), Condition::InOrIsSystem::Description(), Condition::OnPlanet::Description(), Condition::ObjectID::Description(), Condition::PlanetType::Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), Condition::Species::Description(), Condition::Enqueued::Description(), Condition::FocusType::Description(), Condition::StarType::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::EmpireHasAdoptedPolicy::Description(), Condition::OwnerHasTech::Description(), Condition::VisibleToEmpire::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), Condition::CanAddStarlaneConnection::Description(), Condition::ExploredByEmpire::Description(), Condition::FleetSupplyableByEmpire::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), Condition::CanColonize::Description(), Condition::CanProduceShips::Description(), Condition::OrderedBombarded::Description(), Condition::ValueTest::Description(), Condition::Location::Description(), Condition::CombatTarget::Description(), DesignWnd::MainPanel::DesignChanged(), SitRepPanel::DismissalMenu(), RenameOrder::Dump(), NewFleetOrder::Dump(), MapWnd::EnableOrderIssuing(), ValueRef::Operation< T >::EvalImpl(), Effect::CreatePlanet::Execute(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FlexibleFormatList(), ValueRef::FormatedDescriptionPropertyNames(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), MessageWnd::HandleDiplomaticStatusChange(), AIClientApp::HandlePythonAICrash(), EncyclopediaDetailPanel::HandleSearchTextEntered(), MessageWnd::HandleTurnPhaseUpdate(), anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), MeterBrowseWnd::Initialize(), anonymous_namespace{Fleet.cpp}::IsCombatShip(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), PlayerListWnd::PlayerRightClicked(), PlayingTurn::PlayingTurn(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), FPSIndicator::PreRender(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), FieldIcon::RClick(), BuildingIndicator::RClick(), TechTreeWnd::LayoutPanel::TechPanel::RClick(), MPLobby::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnData::react(), PlayingTurn::react(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), BuildDesignatorWnd::BuildSelector::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), EncyclopediaDetailPanel::RefreshImpl(), anonymous_namespace{DesignWnd.cpp}::ReportFileError(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), ResourceInfoPanel::SetEmpireID(), ResourceInfoPanel::SetLocalPointsCost(), CombatLogWnd::Impl::SetLog(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), ValueRef::StatisticDescription(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), MapWnd::TimerFiring(), FleetWnd::TitleText(), SpecialsPanel::Update(), SitRepPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), MapWnd::MapScaleLine::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), ShipFightersBrowseWnd::UpdateSummary(), and anonymous_namespace{ChatWnd.cpp}::UserStringSubstitute().
FlushLoadedStringTables()
void FlushLoadedStringTables ()
Clears all loaded strings, so that subsequent UserString lookups will cause the stringtable(s) to be reloaded.
References anonymous_namespace{i18n.cpp}::stringtable_access_mutex, and anonymous_namespace{i18n.cpp}::stringtables.
Referenced by OptionsWnd::CompleteConstruction().
GetLocale()
std::locale GetLocale (const std::string & name)
Returns locale, which may be previously cached.
References ErrorLogger, InfoLogger, and TraceLogger.
Referenced by ClientUI::FormatTimestamp(), anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName(), anonymous_namespace{CombatLogWnd.cpp}::OrderByNameAndId::operator()(), anonymous_namespace{ObjectListWnd.cpp}::CustomRowCmp::operator()(), anonymous_namespace{MapWnd.cpp}::CustomRowCmp::operator()(), and TechTreeWnd::TechListBox::TechRowCmp().
Language()
const std::string& Language ()
Returns the language of the StringTable currently in use.
References anonymous_namespace{i18n.cpp}::GetStringTable(), StringTable::Language(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
RomanNumber()
std::string RomanNumber (unsigned int n)
Returns the stringified form of n as a roman number.
"Only" defined for 1 <= n <= 3999, as we can't display the symbol for 5000.
Referenced by NewMonsterName(), anonymous_namespace{Planet.cpp}::PlanetSizeIncrement(), and FreeOrionPython::WrapServer().
UserString()
const std::string& UserString (const std::string & str)
Returns a language-specific string for the key-string str.
References anonymous_namespace{i18n.cpp}::GetDevDefaultStringTable(), anonymous_namespace{i18n.cpp}::GetStringTable(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
Referenced by SaveFileDialog::AskDelete(), EmptyHullsListBox::BaseRightClicked(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), OptionsWnd::BoolOption(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{LinkText.cpp}::BrowsePathLinkText(), Building::Building(), BuildingIndicator::BuildingIndicator(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), ObjectHeaderPanel::ButtonRightClicked(), CensusRowPanel::CensusRowPanel(), MultiPlayerLobbyWnd::ChatMessage(), TechManager::CheckPendingTechs(), ResourceInfoPanel::Clear(), ResourceInfoPanel::ClearLocalInfo(), anonymous_namespace{ServerConnectWnd.cpp}::ClientTypeRow::ClientTypeRow(), OptionsWnd::ColorOption(), BoutBeginEvent::CombatLogDescription(), BoutEvent::CombatLogDescription(), InitialStealthEvent::CombatLogDescription(), StealthChangeEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), WeaponFireEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), FightersAttackFightersEvent::CombatLogDescription(), FighterLaunchEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), WeaponFireEvent::CombatLogDetails(), OptionsDB::Commit(), OptionsDB::CommitPersistent(), anonymous_namespace{SaveLoad.cpp}::CompileSaveGamePreviewData(), InGameMenu::CompleteConstruction(), About::CompleteConstruction(), PasswordEnterWnd::CompleteConstruction(), SitRepPanel::CompleteConstruction(), ObjectListWnd::CompleteConstruction(), MilitaryPanel::CompleteConstruction(), OptionsWnd::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ProductionWnd::CompleteConstruction(), ResourcePanel::CompleteConstruction(), IntroScreen::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), GameRulesPanel::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), SideBar::CompleteConstruction(), ResearchQueueWnd::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), anonymous_namespace{GalaxySetupWnd.cpp}::UserStringRow::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), OptionsBar::CompleteConstruction(), GovernmentWnd::PolicyPalette::CompleteConstruction(), BuildDesignatorWnd::BuildSelector::CompleteConstruction(), PolicySlotControl::CompleteConstruction(), FilterDialog::CompleteConstruction(), GovernmentWnd::MainPanel::CompleteConstruction(), PartControl::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), DesignWnd::PartPalette::CompleteConstruction(), DesignWnd::BaseSelector::CompleteConstruction(), SlotControl::CompleteConstruction(), DesignWnd::MainPanel::CompleteConstruction(), ValueRef::ComplexVariableDescription(), InGameMenu::Concede(), Condition::ConditionDescription(), Condition::ConditionFailedDescription(), SaveFileDialog::Confirm(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{GGHumanClientApp.cpp}::CreateNewAutosaveFilePath(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), CreditsWnd::CreditsWnd(), PartsListBox::CullSuperfluousParts(), Condition::All::Description(), Condition::Source::Description(), ValueRef::NamedRef< T >::Description(), Special::Description(), ValueRef::Constant< T >::Description(), Condition::Number::Description(), ShipDesign::Description(), Condition::Turn::Description(), Condition::SortedNumberOf::Description(), Condition::None::Description(), Condition::NoOp::Description(), Condition::EmpireAffiliation::Description(), Condition::RootCandidate::Description(), Condition::Target::Description(), Condition::Homeworld::Description(), Condition::Capital::Description(), Condition::Monster::Description(), Condition::Armed::Description(), Condition::Type::Description(), Condition::Building::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::CreatedOnTurn::Description(), Condition::Contains::Description(), Condition::ContainedBy::Description(), Condition::InOrIsSystem::Description(), Condition::OnPlanet::Description(), Condition::ObjectID::Description(), Condition::PlanetType::Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), Condition::Species::Description(), Condition::Enqueued::Description(), Condition::FocusType::Description(), Condition::StarType::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::EmpireHasAdoptedPolicy::Description(), Condition::OwnerHasTech::Description(), Condition::OwnerHasBuildingTypeAvailable::Description(), Condition::OwnerHasShipDesignAvailable::Description(), Condition::OwnerHasShipPartAvailable::Description(), Condition::VisibleToEmpire::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), Condition::CanAddStarlaneConnection::Description(), Condition::ExploredByEmpire::Description(), Condition::Stationary::Description(), Condition::Aggressive::Description(), Condition::FleetSupplyableByEmpire::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), Condition::CanColonize::Description(), Condition::CanProduceShips::Description(), Condition::OrderedBombarded::Description(), Condition::ValueTest::Description(), Condition::Location::Description(), Condition::CombatTarget::Description(), Condition::And::Description(), Condition::Or::Description(), Condition::OrderedAlternativesOf::Description(), Condition::Described::Description(), DesignWnd::MainPanel::DesignChanged(), SitRepPanel::DismissalMenu(), DesignWnd::MainPanel::I18nString::DisplayText(), ObjectListWnd::DoLayout(), OptionsWnd::DoubleOption(), GameRulesPanel::DoubleRuleWidget(), DoubleToString(), RenameOrder::Dump(), NewFleetOrder::Dump(), FleetMoveOrder::Dump(), FleetTransferOrder::Dump(), ColonizeOrder::Dump(), InvadeOrder::Dump(), BombardOrder::Dump(), ChangeFocusOrder::Dump(), PolicyOrder::Dump(), ResearchQueueOrder::Dump(), ProductionQueueOrder::Dump(), ShipDesignOrder::Dump(), ScrapOrder::Dump(), AggressiveOrder::Dump(), GiveObjectToEmpireOrder::Dump(), Condition::DesignHasPartClass::Dump(), ForgetOrder::Dump(), anonymous_namespace{CombatLogWnd.cpp}::EmpireIdToText(), anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings(), MapWnd::EnableOrderIssuing(), ServerFSM::EstablishPlayer(), ValueRef::StringCast< FromType >::Eval(), ValueRef::UserStringLookup< FromType >::Eval(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), anonymous_namespace{Order.cpp}::ExecutedTag(), Field::Field(), anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), OptionsWnd::FileOptionImpl(), SitRepPanel::FilterClicked(), MessageWndEdit::FindGameWords(), MapWnd::FleetButtonRightClicked(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), FlexibleFormat(), FlexibleFormatList(), ValueRef::FormatedDescriptionPropertyNames(), Species::GameplayDescription(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GeneralTypeOfObject(), anonymous_namespace{Effects.cpp}::GenerateSystemName(), VarText::GenerateVarText(), Encyclopedia::GetArticleByName(), ConditionWidget::GetCondition(), Condition::anonymous_namespace{Conditions.cpp}::GetContentTypeName(), ObjectHeaderPanel::GetControls(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{SidePanel.cpp}::GetPlanetEnvironmentName(), anonymous_namespace{SidePanel.cpp}::GetPlanetSizeName(), anonymous_namespace{SidePanel.cpp}::GetPlanetTypeName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{SidePanel.cpp}::GetStarTypeName(), OptionsDB::GetUsage(), GGHumanClientApp::GGHumanClientApp(), MessageWnd::HandleDiplomaticStatusChange(), MessageWnd::HandlePlayerChatMessage(), AIClientApp::HandlePythonAICrash(), EncyclopediaDetailPanel::HandleSearchTextEntered(), DesignWnd::PartPalette::HandleShipPartRightClicked(), MessageWnd::HandleTextCommand(), MessageWnd::HandleTurnPhaseUpdate(), OptionsWnd::HotkeyOption(), OptionsWnd::HotkeysPage(), anonymous_namespace{VarText.cpp}::IDString(), CombatReportWnd::Impl::Impl(), anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled(), SaveFileDialog::Init(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), InitEmpires(), MeterBrowseWnd::Initialize(), OptionsWnd::IntOption(), GameRulesPanel::IntRuleWidget(), anonymous_namespace{Fleet.cpp}::IsCombatShip(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), QueueListBox::ItemRightClickedImpl(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), FleetButton::LayoutIcons(), LinkTaggedText(), LoadEmpireSaveGameData(), LoadPlayerSaveHeaderData(), GGHumanClientApp::LoadSinglePlayerGame(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), mainConfigOptionsSetup(), ClientUI::MessageBox(), anonymous_namespace{MeterBrowseWnd.cpp}::MeterToUserString(), anonymous_namespace{VarText.cpp}::MeterTypeString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString(), GGHumanClientApp::MultiPlayerGame(), OptionsWnd::MusicVolumeOption(), FleetPlan::Name(), ShipDesign::Name(), anonymous_namespace{VarText.cpp}::NameString(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::NewLabelValue(), NewMonsterName(), GGHumanClientApp::NewSinglePlayerGame(), ObjectListWnd::ObjectRightClicked(), anonymous_namespace{VarText.cpp}::Substitute::operator()(), anonymous_namespace{SitRepPanel.cpp}::OrderedSitrepTemplateStrings(), anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix(), anonymous_namespace{Planet.cpp}::PlanetSizeIncrement(), PlayerListWnd::PlayerRightClicked(), PlayingTurn::PlayingTurn(), anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), PoliciesListBox::Populate(), PartsListBox::Populate(), BasesListBox::Populate(), MultiPlayerLobbyWnd::PopulatePlayerList(), FPSIndicator::PreRender(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{SaveFileDialog.cpp}::Prompt(), Field::PublicName(), Ship::PublicName(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), anonymous_namespace{ProductionWnd.cpp}::QuantLabel::QuantLabel(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), GraphControl::RClick(), FieldIcon::RClick(), CUILabel::RClick(), BuildingIndicator::RClick(), MapWnd::RClick(), LinkText::RClick(), CUIEdit::RClick(), CensoredCUIEdit::RClick(), CUIMultiEdit::RClick(), CUILinkTextMultiEdit::RClick(), ColorSelector::RClick(), SidePanel::PlanetPanel::RClick(), TechTreeWnd::LayoutPanel::TechPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), WaitingForSPHostAck::react(), Idle::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MPLobby::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), PlayingTurn::react(), BuildingIndicator::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), BuildDesignatorWnd::BuildSelector::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSearchResultsTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshDetectionIndicator(), EncyclopediaDetailPanel::RefreshImpl(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshInfluenceResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTurnButtonTooltip(), anonymous_namespace{DesignWnd.cpp}::ReportFileError(), GGHumanClientApp::RequestSavePreviews(), ResearchWnd::ResearchWnd(), BasesListBox::ResetEmptyListPrompt(), CompletedDesignsListBox::ResetEmptyListPrompt(), SavedDesignsListBox::ResetEmptyListPrompt(), GGHumanClientApp::ResetOrExitApp(), OptionsWnd::ResolutionOption(), ResourceBrowseWnd::ResourceBrowseWnd(), DesignWnd::MainPanel::Sanitize(), InGameMenu::Save(), SaveGame(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SearchPediaArticlesForWords(), BasesListBox::BasesListBoxRow::SetAvailability(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), ResourceInfoPanel::SetEmpireID(), OptionsDB::SetFromFile(), ResourceInfoPanel::SetLocalPointsCost(), CombatLogWnd::Impl::SetLog(), SlotControl::SetPart(), PolicySlotControl::SetPolicy(), GalaxySetupPanel::SetSeed(), ResourceInfoPanel::SetStockpileCost(), anonymous_namespace{GGHumanClientApp.cpp}::SetStringtableDependentOptionDefaults(), EncyclopediaDetailPanel::SetText(), ResourceInfoPanel::SetTotalPointsCost(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), anonymous_namespace{CombatEvents.cpp}::ShipPartLink(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), About::ShowVision(), CombatSummary::SideName(), OptionsWnd::SoundFileOption(), OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow(), SpeciesSelector::SpeciesSelector(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), ValueRef::StatisticDescription(), ConditionWidget::StringRow::StringRow(), GameRulesPanel::StringRuleWidget(), anonymous_namespace{VarText.cpp}::SubstitutionMap(), TechTreeWnd::TechListBox::TechRightClicked(), TechRowBrowseWnd(), TextForAIAggression(), TextForGalaxySetupSetting(), TextForGalaxyShape(), MapWnd::TimerFiring(), SaveFileColumn::Title(), FleetWnd::TitleText(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{ValueRefs.cpp}::TraceReference(), CUIStyle::Translate(), anonymous_namespace{Fleet.cpp}::TruncateRouteToEndAtSystem(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::TypeSelector::TypeRow::TypeRow(), SpecialsPanel::Update(), SitRepPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), MapWnd::MapScaleLine::Update(), FleetDataPanel::UpdateAggressionToggle(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), ResearchWnd::UpdateInfoPanel(), ProductionWnd::UpdateInfoPanel(), ConditionWidget::UpdateParameterControls(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), ShipFightersBrowseWnd::UpdateSummary(), UserStringList(), anonymous_namespace{ChatWnd.cpp}::UserStringSubstitute(), DesignWnd::MainPanel::ValidatedNameAndDescription(), OptionsWnd::VolumeOption(), FreeOrionPython::WrapAI(), FreeOrionPython::WrapServer(), anonymous_namespace{CombatEvents.cpp}::WrapUserStringWithTag(), and ClientUI::ZoomToContent().
UserStringExists()
bool UserStringExists (const std::string & str)
Returns true iff a user-string exists for the key string str.
References anonymous_namespace{i18n.cpp}::GetDevDefaultStringTable(), anonymous_namespace{i18n.cpp}::GetStringTable(), StringTable::StringExists(), and anonymous_namespace{i18n.cpp}::stringtable_access_mutex.
Referenced by BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), ValueRef::ComplexVariableDescription(), PartsListBox::CullSuperfluousParts(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::PlanetEnvironment::Description(), Condition::Enqueued::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::PredefinedShipDesign::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireHasAdoptedPolicy::Description(), Condition::OwnerHasTech::Description(), Condition::Described::Description(), ValueRef::UserStringLookup< FromType >::Eval(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), ResearchQueueListBox::ItemRightClickedImpl(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{VarText.cpp}::MeterTypeString(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), ValueRef::StatisticDescription(), anonymous_namespace{ChatWnd.cpp}::UserStringSubstitute(), DesignWnd::MainPanel::ValidatedNameAndDescription(), anonymous_namespace{OptionsWnd.cpp}::ValidSectionForHotkey(), ValueRefLinkText(), and FreeOrionPython::WrapAI().
UserStringList()
std::vector<std::string> UserStringList (const std::string & key)
Returns a language-specific vector of strings for given key.
References anonymous_namespace{i18n.cpp}::stringtable_access_mutex, and UserString().
Referenced by anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), anonymous_namespace{ModeratorAction.cpp}::GenerateSystemName(), anonymous_namespace{Effects.cpp}::GenerateSystemName(), anonymous_namespace{AIWrapper.cpp}::GetUserStringList(), NewMonsterName(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag().