FreeOrion: LinkText.h File Reference
LinkText.h File Reference
#include <GG/TextControl.h>
#include <boost/signals2/signal.hpp>
Classes
class ColorByOwner
class LinkDecorator
A class that can be subclassed to give types of links decorations in link text.
class LinkText
Allows text that the user sees to emit signals when clicked, and indicates to the user visually which text represents a link.
class PathTypeDecorator
class TextLinker
Typedefs
typedef std::shared_ptr< LinkDecorator > LinkDecoratorPtr
Functions
std::string LinkTaggedIDText (const std::string &tag, int id, const std::string &text)
Helper for generating a link string.
std::string LinkTaggedPresetText (const std::string &tag, const std::string &stringtable_entry, const std::string &display_text)
Helper for generating a link string with preset display text (not to be looked up in stringtable)
std::string LinkTaggedText (const std::string &tag, const std::string &stringtable_entry)
Helper for generating a link string with content from a stringtable entry.
void RegisterLinkTags ()
Free function to register link tags that TextLinker knows of.
Typedef Documentation
LinkDecoratorPtr
typedef std::shared_ptr<LinkDecorator> LinkDecoratorPtr
Function Documentation
LinkTaggedIDText()
std::string LinkTaggedIDText (const std::string & tag, int id, const std::string & text)
Helper for generating a link string.
References to_string().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and CombatLogWnd::Impl::SetLog().
LinkTaggedPresetText()
std::string LinkTaggedPresetText (const std::string & tag, const std::string & stringtable_entry, const std::string & display_text)
Helper for generating a link string with preset display text (not to be looked up in stringtable)
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterTypeDirEntry().
LinkTaggedText()
std::string LinkTaggedText (const std::string & tag, const std::string & stringtable_entry)
Helper for generating a link string with content from a stringtable entry.
References UserString().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1().
RegisterLinkTags()
void RegisterLinkTags ()
Free function to register link tags that TextLinker knows of.
This allows GG::Font to remove them so that they will not be rendered. Must be called at least once before text with embedded XML tags is handled by GG::Font
References TextLinker::BROWSE_PATH_TAG, VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, TextLinker::GRAPH_TAG, anonymous_namespace{LinkText.cpp}::link_tags_registered, VarText::METER_TYPE_TAG, VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, and TextLinker::URL_TAG.
Referenced by HumanClientApp::HumanClientApp(), and TextLinker::TextLinker().