FreeOrion: LinkText.cpp File Reference
LinkText.cpp File Reference
#include "LinkText.h"
#include "ClientUI.h"
#include "CUIControls.h"
#include "../Empire/Empire.h"
#include "../universe/UniverseObject.h"
#include "../util/AppInterface.h"
#include "../util/Logger.h"
#include "../util/VarText.h"
#include "../util/i18n.h"
#include "../util/Directories.h"
#include "../universe/Enums.h"
#include <GG/DrawUtil.h>
#include <GG/WndEvent.h>
#include <GG/GUI.h>
#include <boost/xpressive/xpressive.hpp>
#include <boost/algorithm/string.hpp>
Classes
struct TextLinker::Link
Namespaces
anonymous_namespace{LinkText.cpp}
Functions
std::string anonymous_namespace{LinkText.cpp}::AllParamsAsString (const std::vector< GG::Font::Substring > &params)
const std::string anonymous_namespace{LinkText.cpp}::BROWSEPATH_TAG_CLOSE ("</"+TextLinker::BROWSE_PATH_TAG+">")
const std::string anonymous_namespace{LinkText.cpp}::BROWSEPATH_TAG_OPEN_PRE ("<"+TextLinker::BROWSE_PATH_TAG)
std::string anonymous_namespace{LinkText.cpp}::BrowsePathLinkText (const std::string &text)
Parses TextLinker::BROWSE_PATH_TAGs within text, replacing string representation of PathTypes with current path for that PathType.
std::string LinkTaggedIDText (const std::string &tag, int id, const std::string &text)
Helper for generating a link string.
std::string LinkTaggedPresetText (const std::string &tag, const std::string &stringtable_entry, const std::string &display_text)
Helper for generating a link string with preset display text (not to be looked up in stringtable)
std::string LinkTaggedText (const std::string &tag, const std::string &stringtable_entry)
Helper for generating a link string with content from a stringtable entry.
void RegisterLinkTags ()
Free function to register link tags that TextLinker knows of.
std::string anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes (const std::string &text)
Variables
const xpr::sregex anonymous_namespace{LinkText.cpp}::BROWSEPATH_SEARCH
static const std::string anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE = "</rgba>"
static bool anonymous_namespace{LinkText.cpp}::link_tags_registered = false
const xpr::sregex anonymous_namespace{LinkText.cpp}::REGEX_NON_BRACKET = *~(xpr::set= '<', '>')
static const bool anonymous_namespace{LinkText.cpp}::RENDER_DEBUGGING_LINK_RECTS = false
Function Documentation
LinkTaggedIDText()
std::string LinkTaggedIDText (const std::string & tag, int id, const std::string & text)
Helper for generating a link string.
References to_string().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and CombatLogWnd::Impl::SetLog().
LinkTaggedPresetText()
std::string LinkTaggedPresetText (const std::string & tag, const std::string & stringtable_entry, const std::string & display_text)
Helper for generating a link string with preset display text (not to be looked up in stringtable)
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterTypeDirEntry().
LinkTaggedText()
std::string LinkTaggedText (const std::string & tag, const std::string & stringtable_entry)
Helper for generating a link string with content from a stringtable entry.
References UserString().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1().
RegisterLinkTags()
void RegisterLinkTags ()
Free function to register link tags that TextLinker knows of.
This allows GG::Font to remove them so that they will not be rendered. Must be called at least once before text with embedded XML tags is handled by GG::Font
References TextLinker::BROWSE_PATH_TAG, VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, TextLinker::GRAPH_TAG, anonymous_namespace{LinkText.cpp}::link_tags_registered, VarText::METER_TYPE_TAG, VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, and TextLinker::URL_TAG.
Referenced by HumanClientApp::HumanClientApp(), and TextLinker::TextLinker().