FreeOrion: Logger.cpp File Reference
Logger.cpp File Reference
#include "Logger.h"
#include <boost/log/core.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/attributes/value_extraction.hpp>
#include <boost/log/expressions/keyword.hpp>
#include <boost/log/sinks/frontend_requirements.hpp>
#include <boost/log/sinks/text_ostream_backend.hpp>
#include <boost/log/sinks/text_file_backend.hpp>
#include <boost/log/sinks/sync_frontend.hpp>
#include <boost/log/sources/global_logger_storage.hpp>
#include <boost/log/sources/record_ostream.hpp>
#include <boost/log/sources/severity_channel_logger.hpp>
#include <boost/log/support/date_time.hpp>
#include <boost/log/utility/manipulators/add_value.hpp>
#include <boost/log/utility/setup/common_attributes.hpp>
#include <boost/log/utility/setup/file.hpp>
#include <boost/log/utility/setup/filter_parser.hpp>
#include <boost/log/utility/setup/formatter_parser.hpp>
#include <boost/optional.hpp>
#include <ctime>
#include <mutex>
#include <regex>
#include <unordered_map>
Classes
class anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds
class anonymous_namespace{Logger.cpp}::LoggerThresholdSetter
Namespaces
anonymous_namespace{Logger.cpp}
Typedefs
using anonymous_namespace{Logger.cpp}::TextFileSinkBackend = sinks::text_file_backend
using anonymous_namespace{Logger.cpp}::TextFileSinkFrontend = sinks::synchronous_sink< TextFileSinkBackend >
Functions
anonymous_namespace{Logger.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log), NamedThreadedLogger)
void ConfigureLogger (NamedThreadedLogger &logger, const std::string &name)
std::vector< std::string > CreatedLoggersNames ()
void anonymous_namespace{Logger.cpp}::CreateFileSinkFrontEnd (const std::string &channel_name)
const std::string & DefaultExecLoggerName ()
const std::string & anonymous_namespace{Logger.cpp}::DisplayName (const std::string &channel_name)
std::string DumpIndent ()
boost::optional< LogLevel > & anonymous_namespace{Logger.cpp}::ForcedThreshold ()
LoggersToSinkFrontEnds & anonymous_namespace{Logger.cpp}::GetLoggersToSinkFrontEnds ()
boost::shared_ptr< TextFileSinkBackend > & anonymous_namespace{Logger.cpp}::GetSinkBackend ()
bool anonymous_namespace{Logger.cpp}::InitializeLoggerCreatedSignal ()
void InitLoggingSystem (const std::string &log_file, const std::string &_unnamed_logger_identifier)
std::stringstream anonymous_namespace{Logger.cpp}::InvalidLogLevelWarning (const std::string &text)
std::string & anonymous_namespace{Logger.cpp}::LocalUnnamedLoggerIdentifier ()
template<typename CharT , typename TraitsT >
std::basic_ostream< CharT, TraitsT > & operator<< (std::basic_ostream< CharT, TraitsT > &os, const LogLevel &level)
template<typename CharT , typename TraitsT >
std::basic_istream< CharT, TraitsT > & operator>> (std::basic_istream< CharT, TraitsT > &is, LogLevel &level)
void OverrideAllLoggersThresholds (const boost::optional< LogLevel > &threshold)
void SetLoggerThreshold (const std::string &source, LogLevel threshold)
std::pair< std::string, LogLevel > anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore (const std::string &source, LogLevel threshold)
void ShutdownLoggingSystemFileSink ()
LogLevel to_LogLevel (const std::string &text)
std::string to_string (const LogLevel level)
std::unordered_map< std::string, LogLevel > ValidNameToLogLevel ()
Variables
int g_indent = 0
constexpr const char *const anonymous_namespace{Logger.cpp}::log_level_names [] = {"trace", "debug", "info", "warn", "error"}
LoggerCreatedSignalType LoggerCreatedSignal
Function Documentation
void ConfigureLogger (NamedThreadedLogger & logger, const std::string & name)
References anonymous_namespace{Logger.cpp}::CreateFileSinkFrontEnd(), default_log_level_threshold, anonymous_namespace{CUIWnd.cpp}::dummy, anonymous_namespace{Logger.cpp}::InitializeLoggerCreatedSignal(), LoggerCreatedSignal, and anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore().
Referenced by InitLoggingSystem().
std::vector<std::string> CreatedLoggersNames ()
References anonymous_namespace{Logger.cpp}::GetLoggersToSinkFrontEnds(), and anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::LoggersNames().
Referenced by InitLoggingOptionsDBSystem(), and InitLoggingSystem().
const std::string& DefaultExecLoggerName ()
References anonymous_namespace{Logger.cpp}::LocalUnnamedLoggerIdentifier().
Referenced by InitLoggingOptionsDBSystem(), and SetLoggerThresholds().
std::string DumpIndent ()
A function that returns the correct amount of spacing for the current indentation level during a dump.
Referenced by FocusType::Dump(), Special::Dump(), Effect::EffectsGroup::Dump(), FieldType::Dump(), Tech::Dump(), BuildingType::Dump(), Effect::NoOp::Dump(), Species::Dump(), Condition::Number::Dump(), Effect::SetMeter::Dump(), Condition::Turn::Dump(), Effect::SetShipPartMeter::Dump(), Effect::SetEmpireMeter::Dump(), Condition::SortedNumberOf::Dump(), Condition::All::Dump(), Effect::SetEmpireStockpile::Dump(), Effect::SetEmpireCapital::Dump(), Condition::None::Dump(), Effect::SetPlanetType::Dump(), Effect::SetPlanetSize::Dump(), Condition::EmpireAffiliation::Dump(), Effect::SetSpecies::Dump(), Condition::Source::Dump(), Effect::SetOwner::Dump(), Effect::SetSpeciesEmpireOpinion::Dump(), Condition::RootCandidate::Dump(), Effect::SetSpeciesSpeciesOpinion::Dump(), Condition::Target::Dump(), ShipDesign::Dump(), Effect::CreatePlanet::Dump(), Effect::CreateBuilding::Dump(), Condition::Homeworld::Dump(), Effect::CreateShip::Dump(), Condition::Capital::Dump(), Condition::Monster::Dump(), Effect::CreateField::Dump(), Condition::Armed::Dump(), Effect::CreateSystem::Dump(), Effect::Destroy::Dump(), Condition::Type::Dump(), Effect::AddSpecial::Dump(), Condition::Building::Dump(), Effect::RemoveSpecial::Dump(), Effect::AddStarlanes::Dump(), Effect::RemoveStarlanes::Dump(), Condition::HasSpecial::Dump(), Effect::SetStarType::Dump(), Condition::HasTag::Dump(), Effect::MoveTo::Dump(), Effect::MoveInOrbit::Dump(), Condition::CreatedOnTurn::Dump(), Effect::MoveTowards::Dump(), Condition::Contains::Dump(), Effect::SetDestination::Dump(), Effect::SetAggression::Dump(), Condition::ContainedBy::Dump(), Effect::Victory::Dump(), Condition::InSystem::Dump(), Effect::GiveEmpireTech::Dump(), Condition::ObjectID::Dump(), Effect::GenerateSitRepMessage::Dump(), Condition::PlanetType::Dump(), Condition::PlanetSize::Dump(), Effect::SetOverlayTexture::Dump(), Effect::SetTexture::Dump(), Condition::PlanetEnvironment::Dump(), Effect::SetVisibility::Dump(), Condition::Species::Dump(), Effect::Conditional::Dump(), Condition::Enqueued::Dump(), Condition::FocusType::Dump(), Condition::StarType::Dump(), Condition::DesignHasHull::Dump(), Condition::DesignHasPart::Dump(), Condition::DesignHasPartClass::Dump(), Condition::PredefinedShipDesign::Dump(), Condition::NumberedShipDesign::Dump(), Condition::ProducedByEmpire::Dump(), Condition::Chance::Dump(), Condition::MeterValue::Dump(), Condition::ShipPartMeterValue::Dump(), Condition::EmpireMeterValue::Dump(), Condition::EmpireStockpileValue::Dump(), Condition::OwnerHasTech::Dump(), Condition::OwnerHasBuildingTypeAvailable::Dump(), Condition::OwnerHasShipDesignAvailable::Dump(), Condition::OwnerHasShipPartAvailable::Dump(), Condition::VisibleToEmpire::Dump(), Condition::WithinDistance::Dump(), Condition::WithinStarlaneJumps::Dump(), Condition::CanAddStarlaneConnection::Dump(), Condition::ExploredByEmpire::Dump(), Condition::Stationary::Dump(), Condition::Aggressive::Dump(), Condition::FleetSupplyableByEmpire::Dump(), Condition::ResourceSupplyConnectedByEmpire::Dump(), Condition::CanColonize::Dump(), Condition::CanProduceShips::Dump(), Condition::OrderedBombarded::Dump(), Condition::ValueTest::Dump(), Condition::Location::Dump(), Condition::And::Dump(), Condition::Or::Dump(), and Condition::Not::Dump().
void InitLoggingSystem (const std::string & log_file, const std::string & unnamed_logger_identifier)
Initializes the logging system. Log to the log_file. If log_file already exists it will be deleted. unnamed_logger_identifier is the name used in the log file to identify logs from the singular unnamed logger for this executable. Logs from the named loggers are identified by their own name.
References ConfigureLogger(), CreatedLoggersNames(), anonymous_namespace{Logger.cpp}::CreateFileSinkFrontEnd(), default_log_level_threshold, FO_GLOBAL_LOGGER_NAME, boost::get(), anonymous_namespace{Logger.cpp}::GetSinkBackend(), InfoLogger, anonymous_namespace{Logger.cpp}::LocalUnnamedLoggerIdentifier(), and anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore().
Referenced by AIClientApp::AIClientApp(), HumanClientApp::HumanClientApp(), and ServerApp::ServerApp().
template<typename CharT , typename TraitsT > std::basic_ostream<CharT, TraitsT>& operator<< (std::basic_ostream< CharT, TraitsT > & os, const LogLevel & level)
template<typename CharT , typename TraitsT > std::basic_istream<CharT, TraitsT >& operator>> (std::basic_istream< CharT, TraitsT > & is, LogLevel & level) inline
References to_LogLevel().
void OverrideAllLoggersThresholds (const boost::optional< LogLevel > & threshold)
Sets all logger thresholds to threshold permanently. If threshold is boost::none then remove the ovverride and allow subsequent SetLoggerThreshold() to work as normal.
References anonymous_namespace{Logger.cpp}::ForcedThreshold(), anonymous_namespace{Logger.cpp}::GetLoggersToSinkFrontEnds(), InfoLogger, anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore(), and to_string().
Referenced by AIClientApp::AIClientApp(), HumanClientApp::HumanClientApp(), and ServerApp::ServerApp().
void SetLoggerThreshold (const std::string & source, LogLevel threshold)
Sets the threshold of source. source == "" is the default logger.
References InfoLogger, and anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore().
Referenced by InitLoggingOptionsDBSystem(), RegisterLoggerWithOptionsDB(), and SetLoggerThresholds().
void ShutdownLoggingSystemFileSink ()
Shutdown the file sink. This should be called near the end of main() before the start of static de-initialization.
The file sink may not be safe to use during static deinitialization, because of the following bug:
http://www.boost.org/doc/libs/1_64_0/libs/log/doc/html/log/rationale/why_crash_on_term.html https://svn.boost.org/trac/boost/ticket/8642 https://svn.boost.org/trac/boost/ticket/9119
When either ticket is fixed the ShutdownLoggingSystemFileSink() function can be removed.
References anonymous_namespace{Logger.cpp}::GetLoggersToSinkFrontEnds(), and anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::ShutdownFileSinks().
Referenced by if(), and main().
LogLevel to_LogLevel (const std::string & text)
References debug, anonymous_namespace{Logger.cpp}::InvalidLogLevelWarning(), ValidNameToLogLevel(), and WarnLogger.
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), AIClientApp::AIClientApp(), HumanClientApp::HumanClientApp(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), operator>>(), and ServerApp::ServerApp().
std::string to_string (const LogLevel level)
References anonymous_namespace{Logger.cpp}::log_level_names.
Referenced by FleetDataPanel::AcceptDrops(), anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), anonymous_namespace{ObjectListWnd.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption(), Universe::ApplyAppearanceEffects(), Universe::ApplyMeterEffectsAndUpdateMeters(), Empire::CheckProductionProgress(), ColumnInPreview(), CombatInfo::CombatInfo(), FightersAttackFightersEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), ClientNetworking::Impl::ConnectToServer(), anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), CreateBuildingBuiltSitRep(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateCombatSitRep(), CreateEmpireEliminatedSitRep(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), CreateFleetArrivedAtDestinationSitRep(), CreateGroundCombatSitRep(), CreatePlanetCapturedSitRep(), CreatePlanetColonizedSitRep(), CreatePlanetDepopulatedSitRep(), CreatePlanetOutpostedSitRep(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), CreateShipBlockBuiltSitRep(), CreateShipBuiltSitRep(), CreateVictorySitRep(), Condition::Number::Description(), Condition::Turn::Description(), ValueRef::Constant< T >::Description(), Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), Condition::Enqueued::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::NumberedShipDesign::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), anonymous_namespace{ClientNetworking.cpp}::ServerDiscoverer::DiscoverServers(), DispatchDesignIDMessage(), DispatchObjectIDMessage(), DoubleToString(), CreditsWnd::DrawCredits(), SitRepEntry::Dump(), DiplomaticMessage::Dump(), ResourcePool::Dump(), Moderator::DestroyUniverseObject::Dump(), Special::Dump(), SupplyManager::Dump(), Moderator::SetOwner::Dump(), Moderator::AddStarlane::Dump(), Moderator::RemoveStarlane::Dump(), Moderator::CreateSystem::Dump(), ProductionQueue::ProductionItem::Dump(), Moderator::CreatePlanet::Dump(), ProductionQueue::Element::Dump(), Empire::Dump(), ShipDesign::Dump(), Condition::HasSpecial::Dump(), EmpireManager::DumpDiplomacy(), AIInterface::EmpirePlayerID(), ValueRef::Variable< T >::Eval(), ValueRef::StringCast< FromType >::Eval(), Universe::ExecuteEffects(), FleetMoveOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GenerateReport(), ServerApp::GenerateUniverse(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), HostIDMessage(), HostMPAckMessage(), HostSPAckMessage(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), ShipDataPanel::Init(), InitEmpires(), MapWnd::InitTurn(), anonymous_namespace{MeterBrowseWnd.cpp}::IntToString(), anonymous_namespace{Logger.cpp}::InvalidLogLevelWarning(), JoinAckMessage(), LinkTaggedIDText(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{ServerFSM.cpp}::LogPlayerSetupData(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LogPlayerSetupData(), HumanClientApp::NewSinglePlayerGame(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator()(), OptionsWnd::OptionsWnd(), OverrideAllLoggersThresholds(), OwnerColoredSystemName::OwnerColoredSystemName(), AIInterface::PlayerName(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackersAndTargets(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), MPLobby::react(), ShipDataPanel::Refresh(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), RegisterLoggerWithOptionsDB(), FPSIndicator::Render(), MapWnd::RenderMovementLineETAIndicators(), parse::replace_macro_references(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportAttackabilityOfTarget(), anonymous_namespace{CombatSystem.cpp}::ReportInvalidTargets(), anonymous_namespace{ClientUI.cpp}::RequiredCharsets(), anonymous_namespace{DesignWnd.cpp}::SaveDesign(), ShipDesign::serialize(), ShipDesignOrder::serialize(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnWidth(), EncyclopediaDetailPanel::SetDesign(), EncyclopediaDetailPanel::SetEmpire(), SetLoggerThresholds(), EncyclopediaDetailPanel::SetObject(), EncyclopediaDetailPanel::SetPlanet(), anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), anonymous_namespace{SidePanel.cpp}::SystemRow::SortKey(), TechTreeWnd::TechListBox::TechRow::TechRow(), anonymous_namespace{ValueRef.cpp}::TraceReference(), MapWnd::MapScaleLine::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateLabels(), Universe::UpdateMeterEstimatesImpl(), ValidNameToLogLevel(), WaitingForSPGameJoiners::WaitingForSPGameJoiners(), and anonymous_namespace{CombatEvents.cpp}::WrapWithTagAndId().
std::unordered_map<std::string, LogLevel> ValidNameToLogLevel ()
References max, min, and to_string().
Referenced by LogLevelValidator(), and to_LogLevel().
Variable Documentation
int g_indent = 0
Referenced by FocusType::Dump(), Special::Dump(), Effect::EffectsGroup::Dump(), FieldType::Dump(), Tech::Dump(), BuildingType::Dump(), Species::Dump(), Condition::Number::Dump(), Condition::SortedNumberOf::Dump(), ShipDesign::Dump(), Condition::Contains::Dump(), Condition::ContainedBy::Dump(), Effect::GenerateSitRepMessage::Dump(), Effect::Conditional::Dump(), Condition::WithinDistance::Dump(), Condition::WithinStarlaneJumps::Dump(), Condition::CanAddStarlaneConnection::Dump(), Condition::ResourceSupplyConnectedByEmpire::Dump(), Condition::And::Dump(), Condition::Or::Dump(), and Condition::Not::Dump().
LoggerCreatedSignalType LoggerCreatedSignal
Referenced by ConfigureLogger(), and InitLoggingOptionsDBSystem().