FreeOrion: LoggerWithOptionsDB.cpp File Reference
LoggerWithOptionsDB.cpp File Reference
#include "LoggerWithOptionsDB.h"
#include "OptionsDB.h"
#include "i18n.h"
#include <functional>
#include <regex>
Namespaces
anonymous_namespace{LoggerWithOptionsDB.cpp}
Functions
LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB (const std::string &full_option_name)
Add the log threshold for a logger with full_option_name to OptionsDB and return the threshold read from OptionsDB.
anonymous_namespace{LoggerWithOptionsDB.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log), NamedThreadedLogger)
void ChangeLoggerThresholdInOptionsDB (const std::string &full_option, LogLevel option_value)
std::regex anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex ("(?:logging\execs\)(\+)")
void InitLoggingOptionsDBSystem ()
Initializes the logging system with settings from OptionsDB and starts capturing LoggerCreatedSignal to add new loggers to OptionsDB on the fly.
std::set< std::tuple< std::string, std::string, LogLevel > > anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels (const std::string prefix, const std::regex &prefix_regex)
Returns the list of full option names, logger names and thresholds for loggers in OptionsDB will prefix using prefix_regex.
std::set< std::tuple< std::string, std::string, LogLevel > > LoggerOptionsLabelsAndLevels (const LoggerTypes types)
Return the option names, labels and levels for the requested types from OptionsDB.
std::unique_ptr< DiscreteValidator< std::string > > LogLevelValidator ()
void RegisterLoggerWithOptionsDB (const std::string &logger_name, const bool is_exec_logger)
void SetLoggerThresholds (const std::set< std::tuple< std::string, std::string, LogLevel >> &fulloption_name_and_levels)
Sets the logger thresholds from a list of options, labels and thresholds.
std::regex anonymous_namespace{LoggerWithOptionsDB.cpp}::source_name_regex ("(?:logging\sources\)(\+)")
Variables
constexpr LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::default_sink_level = default_log_level_threshold
constexpr LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::default_source_level = default_log_level_threshold
constexpr auto anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix = "logging.execs."
constexpr auto anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix = "logging.sources."
Function Documentation
ChangeLoggerThresholdInOptionsDB()
void ChangeLoggerThresholdInOptionsDB (const std::string & full_option, LogLevel option_value)
References ErrorLogger, anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex(), SetLoggerThresholds(), and anonymous_namespace{LoggerWithOptionsDB.cpp}::source_name_regex().
Referenced by GGHumanClientApp::ChangeLoggerThreshold().
InitLoggingOptionsDBSystem()
void InitLoggingOptionsDBSystem ()
Initializes the logging system with settings from OptionsDB and starts capturing LoggerCreatedSignal to add new loggers to OptionsDB on the fly.
References anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), CreatedLoggersNames(), DefaultExecLoggerName(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix, InfoLogger, LoggerCreatedSignal, RegisterLoggerWithOptionsDB(), and SetLoggerThreshold().
Referenced by AIClientApp::AIClientApp(), GGHumanClientApp::GGHumanClientApp(), and ServerApp::ServerApp().
LoggerOptionsLabelsAndLevels()
std::set<std::tuple<std::string, std::string, LogLevel> > LoggerOptionsLabelsAndLevels (const LoggerTypes types)
Return the option names, labels and levels for the requested types from OptionsDB.
Return the option names, labels and levels for logger oy type from OptionsDB.
References exec, anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix, LoggerOptionsLabelsAndLevels(), named, anonymous_namespace{LoggerWithOptionsDB.cpp}::source_name_regex(), and anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix.
Referenced by LoggerOptionsLabelsAndLevels().
LogLevelValidator()
std::unique_ptr<DiscreteValidator<std::string> > LogLevelValidator ()
References ValidNameToLogLevel().
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), and anonymous_namespace{MultiplayerCommon.cpp}::AddOptions().
RegisterLoggerWithOptionsDB()
void RegisterLoggerWithOptionsDB (const std::string & logger_name, const bool is_exec_logger)
References anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), DebugLogger, anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix, SetLoggerThreshold(), anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix, and to_string().
Referenced by GGHumanClientApp::GGHumanClientApp(), and InitLoggingOptionsDBSystem().
SetLoggerThresholds()
void SetLoggerThresholds (const std::set< std::tuple< std::string, std::string, LogLevel >> & fulloption_name_and_levels)
Sets the logger thresholds from a list of options, labels and thresholds.
References DefaultExecLoggerName(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex(), GetOptionsDB(), OptionsDB::Set(), SetLoggerThreshold(), and to_string().
Referenced by ChangeLoggerThresholdInOptionsDB(), ServerApp::HandleLoggerConfig(), and AIClientApp::HandleMessage().