FreeOrion: LoggerWithOptionsDB.h File Reference
LoggerWithOptionsDB.h File Reference
This extends the logging system to be configured from values stored in OptionsDB.
#include "OptionsDB.h"
#include <string>
#include <set>
#include <tuple>
#include "Export.h"
#include "Logger.h"
Functions
std::string DumpIndent ()
FO_COMMON_API void InitLoggingOptionsDBSystem ()
FO_COMMON_API std::set< std::tuple< std::string, std::string, LogLevel > > LoggerExecutableOptionsLabelsAndLevels ()
FO_COMMON_API std::set< std::tuple< std::string, std::string, LogLevel > > LoggerSourceOptionsLabelsAndLevels ()
DiscreteValidator< std::string > LogLevelValidator ()
FO_COMMON_API void RegisterLoggerWithOptionsDB (const std::string logger)
FO_COMMON_API void SetLoggerThresholds (const std::set< std::tuple< std::string, std::string, LogLevel >> &)
FO_COMMON_API void UpdateLoggerThresholdsFromOptionsDB ()
Variables
int g_indent
Detailed Description
This extends the logging system to be configured from values stored in OptionsDB.
Enabling/disabling the default executable logger and named sources is controlled statically on startup through OptionsDB, with either the files config.xml and/or persistent_config.xml or dynamically with the app options window.
The logging section in the configuration file looks like:
<logging> <execs> <client>info</client> <server>debug</server> <ai>debug</ai> </execs> <sources> <combat>debug</combat> <combat-log>info</combat-log> <network>warn</network>
...
<ai>debug</ai> </sources> </logging>
The <execs> section controls the default log threshold of each client (freeorion.log), server (freeoriond.log) and AI (AI_x.log) files.
The <sources> section controls the log threshold of the named loggers.
Function Documentation
std::string DumpIndent ()
A function that returns the correct amount of spacing for the current indentation level during a dump.
Referenced by FocusType::Dump(), Special::Dump(), Effect::EffectsGroup::Dump(), FieldType::Dump(), Tech::Dump(), BuildingType::Dump(), Effect::NoOp::Dump(), Species::Dump(), Effect::SetMeter::Dump(), Condition::Number::Dump(), Condition::Turn::Dump(), Effect::SetShipPartMeter::Dump(), Effect::SetEmpireMeter::Dump(), Condition::SortedNumberOf::Dump(), Effect::SetEmpireStockpile::Dump(), Condition::All::Dump(), Effect::SetEmpireCapital::Dump(), Condition::None::Dump(), Effect::SetPlanetType::Dump(), Effect::SetPlanetSize::Dump(), Condition::EmpireAffiliation::Dump(), Effect::SetSpecies::Dump(), Condition::Source::Dump(), Effect::SetOwner::Dump(), Effect::SetSpeciesEmpireOpinion::Dump(), Condition::RootCandidate::Dump(), Effect::SetSpeciesSpeciesOpinion::Dump(), Condition::Target::Dump(), Effect::CreatePlanet::Dump(), ShipDesign::Dump(), Effect::CreateBuilding::Dump(), Condition::Homeworld::Dump(), Effect::CreateShip::Dump(), Condition::Capital::Dump(), Effect::CreateField::Dump(), Condition::Monster::Dump(), Condition::Armed::Dump(), Effect::CreateSystem::Dump(), Effect::Destroy::Dump(), Condition::Type::Dump(), Effect::AddSpecial::Dump(), Condition::Building::Dump(), Effect::RemoveSpecial::Dump(), Effect::AddStarlanes::Dump(), Effect::RemoveStarlanes::Dump(), Condition::HasSpecial::Dump(), Effect::SetStarType::Dump(), Effect::MoveTo::Dump(), Condition::HasTag::Dump(), Effect::MoveInOrbit::Dump(), Condition::CreatedOnTurn::Dump(), Effect::MoveTowards::Dump(), Effect::SetDestination::Dump(), Condition::Contains::Dump(), Effect::SetAggression::Dump(), Effect::Victory::Dump(), Condition::ContainedBy::Dump(), Condition::InSystem::Dump(), Effect::GiveEmpireTech::Dump(), Condition::ObjectID::Dump(), Effect::GenerateSitRepMessage::Dump(), Condition::PlanetType::Dump(), Effect::SetOverlayTexture::Dump(), Condition::PlanetSize::Dump(), Effect::SetTexture::Dump(), Condition::PlanetEnvironment::Dump(), Effect::SetVisibility::Dump(), Condition::Species::Dump(), Effect::Conditional::Dump(), Condition::Enqueued::Dump(), Condition::FocusType::Dump(), Condition::StarType::Dump(), Condition::DesignHasHull::Dump(), Condition::DesignHasPart::Dump(), Condition::DesignHasPartClass::Dump(), Condition::PredefinedShipDesign::Dump(), Condition::NumberedShipDesign::Dump(), Condition::ProducedByEmpire::Dump(), Condition::Chance::Dump(), Condition::MeterValue::Dump(), Condition::ShipPartMeterValue::Dump(), Condition::EmpireMeterValue::Dump(), Condition::EmpireStockpileValue::Dump(), Condition::OwnerHasTech::Dump(), Condition::OwnerHasBuildingTypeAvailable::Dump(), Condition::OwnerHasShipDesignAvailable::Dump(), Condition::OwnerHasShipPartAvailable::Dump(), Condition::VisibleToEmpire::Dump(), Condition::WithinDistance::Dump(), Condition::WithinStarlaneJumps::Dump(), Condition::CanAddStarlaneConnection::Dump(), Condition::ExploredByEmpire::Dump(), Condition::Stationary::Dump(), Condition::Aggressive::Dump(), Condition::FleetSupplyableByEmpire::Dump(), Condition::ResourceSupplyConnectedByEmpire::Dump(), Condition::CanColonize::Dump(), Condition::CanProduceShips::Dump(), Condition::OrderedBombarded::Dump(), Condition::ValueTest::Dump(), Condition::Location::Dump(), Condition::And::Dump(), Condition::Or::Dump(), and Condition::Not::Dump().
FO_COMMON_API void InitLoggingOptionsDBSystem ()
Initializes the logging system with settings from OptionsDB and starts capturing LoggerCreatedSignal to add new loggers to OptionsDB on the fly.
References anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), CreatedLoggersNames(), DefaultExecLoggerName(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix, InfoLogger, LoggerCreatedSignal, RegisterLoggerWithOptionsDB(), and SetLoggerThreshold().
Referenced by AIClientApp::AIClientApp(), HumanClientApp::HumanClientApp(), and ServerApp::ServerApp().
FO_COMMON_API std::set<std::tuple<std::string, std::string, LogLevel> > LoggerExecutableOptionsLabelsAndLevels ()
Return the option names, labels and levels for all executables from OptionsDB.
References anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix, and anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels().
Referenced by UpdateLoggerThresholdsFromOptionsDB().
FO_COMMON_API std::set<std::tuple<std::string, std::string, LogLevel> > LoggerSourceOptionsLabelsAndLevels ()
Return the option names, labels and levels for all sources/channels from OptionsDB.
References anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), anonymous_namespace{LoggerWithOptionsDB.cpp}::source_name_regex(), and anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix.
Referenced by UpdateLoggerThresholdsFromOptionsDB().
DiscreteValidator<std::string> LogLevelValidator ()
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), and anonymous_namespace{MultiplayerCommon.cpp}::AddOptions().
FO_COMMON_API void RegisterLoggerWithOptionsDB (const std::string logger)
References anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), DebugLogger, SetLoggerThreshold(), anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix, and to_string().
Referenced by InitLoggingOptionsDBSystem().
FO_COMMON_API void SetLoggerThresholds (const std::set< std::tuple< std::string, std::string, LogLevel >> & fulloption_name_and_levels)
Sets the logger thresholds from a list of options, labels and thresholds.
References DefaultExecLoggerName(), anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex(), GetOptionsDB(), OptionsDB::OptionExists(), OptionsDB::Set(), SetLoggerThreshold(), and to_string().
Referenced by UpdateLoggerThresholdsFromOptionsDB().
FO_COMMON_API void UpdateLoggerThresholdsFromOptionsDB ()
References LoggerExecutableOptionsLabelsAndLevels(), LoggerSourceOptionsLabelsAndLevels(), and SetLoggerThresholds().
Variable Documentation
int g_indent