FreeOrion: Message.cpp File Reference
Message.cpp File Reference
#include "Message.h"
#include "../combat/CombatLogManager.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Supply.h"
#include "../Empire/Diplomacy.h"
#include "../util/Logger.h"
#include "../util/ModeratorAction.h"
#include "../util/SaveGamePreviewUtils.h"
#include "../universe/Species.h"
#include "../universe/Universe.h"
#include "../util/OptionsDB.h"
#include "../util/OrderSet.h"
#include "../util/Serialize.h"
#include "../util/ScopedTimer.h"
#include "../util/i18n.h"
#include "../util/Version.h"
#include <boost/algorithm/string/erase.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/serialization/deque.hpp>
#include <boost/serialization/list.hpp>
#include <boost/serialization/map.hpp>
#include <boost/serialization/set.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/serialization/weak_ptr.hpp>
#include <boost/date_time/posix_time/time_serialize.hpp>
#include <boost/uuid/uuid_serialize.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <zlib.h>
#include <iostream>
#include <stdexcept>
#include <sstream>
#include <map>
Namespaces
anonymous_namespace{Message.cpp}
Functions
Message AIEndGameAcknowledgeMessage ()
creates an AI_END_GAME_ACK message used to indicate that the AI has shutdown.
Message AuthRequestMessage (const std::string &player_name, const std::string &auth)
creates a AUTH_REQUEST message containing player_name to login and auth additional authentication data.
Message AuthResponseMessage (const std::string &player_name, const std::string &auth)
creates a AUTH_RESPONSE message containing player_name to login and auth credentials.
void BufferToHeader (const Message::HeaderBuffer &buffer, Message &message)
Fills in the relevant portions of message with the values in the buffer buffer.
Message ChatHistoryMessage (const std::vector< std::reference_wrapper< const ChatHistoryEntity >> &chat_history)
creates an CHAT_HISTORY message containing latest chat messages.
Message ContentCheckSumMessage ()
creates a CHECKSUM message containing checksums of parsed content.
Message DiplomacyMessage (const DiplomaticMessage &diplo_message)
creates a DIPLOMACY message, which is sent between players via the server to declare, proposed, or accept / reject diplomatic arrangements or agreements.
Message DiplomaticStatusMessage (const DiplomaticStatusUpdateInfo &diplo_update)
creates a DIPLOMATIC_STATUS message, which is sent to players by the server to update them on diplomatic status changes between players.
Message DispatchCombatLogsMessage (const std::vector< std::pair< int, const CombatLog >> &logs, bool use_binary_serialization)
returns combat logs to the client
Message DispatchSavePreviewsMessage (const PreviewInformation &previews)
returns the savegame previews to the client
Message EliminateSelfMessage ()
creates a ELIMINATE_SELF message to resign from the game.
Message EndGameMessage (Message::EndGameReason reason, const std::string &reason_player_name)
creates an END_GAME message used to terminate an active game.
Message ErrorMessage (const std::string &problem, bool fatal, int player_id)
creates an ERROR_MSG message
void ExtractAuthRequestMessageData (const Message &msg, std::string &player_name, std::string &auth)
void ExtractAuthResponseMessageData (const Message &msg, std::string &player_name, std::string &auth)
void ExtractChatHistoryMessage (const Message &msg, std::vector< ChatHistoryEntity > &chat_history)
void ExtractContentCheckSumMessageData (const Message &msg, std::map< std::string, unsigned int > &checksums)
void ExtractDiplomacyMessageData (const Message &msg, DiplomaticMessage &diplo_message)
void ExtractDiplomaticStatusMessageData (const Message &msg, DiplomaticStatusUpdateInfo &diplo_update)
FO_COMMON_API void ExtractDispatchCombatLogsMessageData (const Message &msg, std::vector< std::pair< int, CombatLog >> &logs)
void ExtractDispatchSavePreviewsMessageData (const Message &msg, PreviewInformation &previews)
void ExtractEndGameMessageData (const Message &msg, Message::EndGameReason &reason, std::string &reason_player_name)
void ExtractErrorMessageData (const Message &msg, int &player_id, std::string &problem, bool &fatal)
void ExtractGameStartMessageData (const Message &msg, bool &single_player_game, int &empire_id, int &current_turn, EmpireManager &empires, Universe &universe, SpeciesManager &species, CombatLogManager &combat_logs, SupplyManager &supply, std::map< int, PlayerInfo > &players, OrderSet &orders, bool &loaded_game_data, bool &ui_data_available, SaveGameUIData &ui_data, bool &save_state_string_available, std::string &save_state_string, GalaxySetupData &galaxy_setup_data)
void ExtractHostMPGameMessageData (const Message &msg, std::string &host_player_name, std::string &client_version_string)
void ExtractHostSPGameMessageData (const Message &msg, SinglePlayerSetupData &setup_data, std::string &client_version_string)
void ExtractJoinAckMessageData (const Message &msg, int &player_id, boost::uuids::uuid &cookie)
void ExtractJoinGameMessageData (const Message &msg, std::string &player_name, Networking::ClientType &client_type, std::string &version_string, boost::uuids::uuid &cookie)
void ExtractLobbyUpdateMessageData (const Message &msg, MultiplayerLobbyData &lobby_data)
FO_COMMON_API void ExtractLoggerConfigMessageData (const Message &msg, std::set< std::tuple< std::string, std::string, LogLevel >> &options)
void ExtractModeratorActionMessageData (const Message &msg, Moderator::ModeratorAction *&mod_action)
void ExtractPlayerChatMessageData (const Message &msg, std::set< int > &recipients, std::string &data, bool &pm)
void ExtractPlayerInfoMessageData (const Message &msg, std::map< int, PlayerInfo > &players)
void ExtractPlayerStatusMessageData (const Message &msg, Message::PlayerStatus &status, int &about_empire_id)
FO_COMMON_API void ExtractRequestCombatLogsMessageData (const Message &msg, std::vector< int > &ids)
void ExtractRequestSavePreviewsMessageData (const Message &msg, std::string &directory)
void ExtractServerPlayerChatMessageData (const Message &msg, int &sender, boost::posix_time::ptime &timestamp, std::string &data, bool &pm)
FO_COMMON_API void ExtractServerSaveGameCompleteMessageData (const Message &msg, std::string &save_filename, int &bytes_written)
void ExtractSetAuthorizationRolesMessage (const Message &msg, Networking::AuthRoles &roles)
void ExtractTurnOrdersMessageData (const Message &msg, OrderSet &orders, bool &ui_data_available, SaveGameUIData &ui_data, bool &save_state_string_available, std::string &save_state_string)
void ExtractTurnPartialOrdersMessageData (const Message &msg, OrderSet &added, std::set< int > &deleted)
void ExtractTurnPartialUpdateMessageData (const Message &msg, int empire_id, Universe &universe)
void ExtractTurnProgressMessageData (const Message &msg, Message::TurnProgressPhase &phase_id)
void ExtractTurnUpdateMessageData (const Message &msg, int empire_id, int &current_turn, EmpireManager &empires, Universe &universe, SpeciesManager &species, CombatLogManager &combat_logs, SupplyManager &supply, std::map< int, PlayerInfo > &players)
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, const OrderSet &orders, const SaveGameUIData *ui_data, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, const OrderSet &orders, const std::string *save_state_string, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
void HeaderToBuffer (const Message &message, Message::HeaderBuffer &buffer)
Fills header_buf from the relevant portions of message.
Message HostIDMessage (int host_player_id)
creates a HOST_ID message.
Message HostMPAckMessage (int player_id)
creates a HOST_MP_GAME acknowledgement message.
Message HostMPGameMessage (const std::string &host_player_name)
creates a minimal HOST_MP_GAME message used to initiate multiplayer "lobby" setup
Message HostSaveGameInitiateMessage (const std::string &filename)
creates a SAVE_GAME_INITIATE request message.
Message HostSPAckMessage (int player_id)
creates a HOST_SP_GAME acknowledgement message.
Message HostSPGameMessage (const SinglePlayerSetupData &setup_data)
creates a HOST_SP_GAME message
Message JoinAckMessage (int player_id, boost::uuids::uuid cookie)
creates a JOIN_GAME acknowledgement message.
Message JoinGameMessage (const std::string &player_name, Networking::ClientType client_type, boost::uuids::uuid cookie)
creates a JOIN_GAME message.
Message LobbyUpdateMessage (const MultiplayerLobbyData &lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the server, then to other users.
Message LoggerConfigMessage (int sender, const std::set< std::tuple< std::string, std::string, LogLevel >> &options)
Sends logger configuration details to server or ai process.
Message ModeratorActionMessage (const Moderator::ModeratorAction &action)
creates a MODERATOR_ACTION message used to implement moderator commands.
bool operator!= (const Message &lhs, const Message &rhs)
std::ostream & operator<< (std::ostream &os, const Message &msg)
Writes msg to os.
bool operator== (const Message &lhs, const Message &rhs)
Message PlayerChatMessage (const std::string &data, std::set< int > recipients, bool pm)
creates an PLAYER_CHAT message containing a chat string to be broadcast to player receiver, or all players if receiver is Networking::INVALID_PLAYER_ID.
Message PlayerInfoMessage (const std::map< int, PlayerInfo > &players)
creates a PLAYER_INFO message to notify player about changes in the player list.
Message PlayerStatusMessage (Message::PlayerStatus player_status, int about_empire_id)
creates a PLAYER_STATUS message.
Message RequestCombatLogsMessage (const std::vector< int > &ids)
requests combat logs from server
Message RequestSavePreviewsMessage (std::string relative_directory)
requests previews of savefiles from server synchronously
Message ServerLobbyUpdateMessage (const MultiplayerLobbyData &lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the users.
Message ServerPlayerChatMessage (int sender, const boost::posix_time::ptime &timestamp, const std::string &data, bool pm)
creates an PLAYER_CHAT message containing a chat string from sender at timestamp to be displayed in chat.
Message ServerSaveGameCompleteMessage (const std::string &save_filename, int bytes_written)
creates a SAVE_GAME_COMPLETE complete message.
Message SetAuthorizationRolesMessage (const Networking::AuthRoles &roles)
notifies client about changes in his authorization roles.
Message ShutdownServerMessage ()
tells server to shut down.
Message StartMPGameMessage ()
creates a START_MP_GAME used to finalize the multiplayer lobby setup.
void swap (Message &lhs, Message &rhs)
Swaps the contents of lhs and rhs. Does not throw.
Message TurnOrdersMessage (const OrderSet &orders, const SaveGameUIData &ui_data)
creates a TURN_ORDERS message, including UI data but without a state string.
Message TurnOrdersMessage (const OrderSet &orders, const std::string &save_state_string)
creates a TURN_ORDERS message, without UI data but with a state string.
Message TurnPartialOrdersMessage (const std::pair< OrderSet, std::set< int >> &orders_updates)
creates a TURN_PARTIAL_ORDERS message with orders changes.
Message TurnPartialUpdateMessage (int empire_id, const Universe &universe, bool use_binary_serialization)
create a TURN_PARTIAL_UPDATE message.
Message TurnProgressMessage (Message::TurnProgressPhase phase_id)
creates a TURN_PROGRESS message.
Message TurnTimeoutMessage (int timeout_remaining)
creates a TURN_TIMEOUT message with remaining time timeout_.
Message TurnUpdateMessage (int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, bool use_binary_serialization)
creates a TURN_UPDATE message.
Message UnreadyMessage ()
creates a UNREADY message to revoke ready state of turn orders or acknowledge it
Variables
const std::string anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE = "Lathanda"
Function Documentation
AIEndGameAcknowledgeMessage()
Message AIEndGameAcknowledgeMessage ()
creates an AI_END_GAME_ACK message used to indicate that the AI has shutdown.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by AIClientApp::HandleMessage().
AuthRequestMessage()
Message AuthRequestMessage (const std::string & player_name, const std::string & auth)
creates a AUTH_REQUEST message containing player_name to login and auth additional authentication data.
References Message::Message().
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
AuthResponseMessage()
Message AuthResponseMessage (const std::string & player_name, const std::string & auth)
creates a AUTH_RESPONSE message containing player_name to login and auth credentials.
References Message::Message().
Referenced by PasswordEnterWnd::OkClicked().
BufferToHeader()
void BufferToHeader (const Message::HeaderBuffer & buffer, Message & message)
Fills in the relevant portions of message with the values in the buffer buffer.
References Message::m_message_size, and Message::m_type.
Referenced by ClientNetworking::Impl::HandleMessageHeaderRead(), and PlayerConnection::HandleMessageHeaderRead().
ChatHistoryMessage()
Message ChatHistoryMessage (const std::vector< std::reference_wrapper< const ChatHistoryEntity >> & chat_history)
creates an CHAT_HISTORY message containing latest chat messages.
This message should only be sent by the server.
References Message::Message().
Referenced by ServerFSM::EstablishPlayer().
ContentCheckSumMessage()
Message ContentCheckSumMessage ()
creates a CHECKSUM message containing checksums of parsed content.
References CheckSumContent(), and Message::Message().
Referenced by ServerFSM::EstablishPlayer(), Idle::react(), and WaitingForSPGameJoiners::react().
DiplomacyMessage()
Message DiplomacyMessage (const DiplomaticMessage & diplo_message)
creates a DIPLOMACY message, which is sent between players via the server to declare, proposed, or accept / reject diplomatic arrangements or agreements.
References Message::Message().
Referenced by ServerApp::HandleDiplomaticMessageChange(), anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction(), and anonymous_namespace{AIWrapper.cpp}::SendDiplomaticMessage().
DiplomaticStatusMessage()
Message DiplomaticStatusMessage (const DiplomaticStatusUpdateInfo & diplo_update)
creates a DIPLOMATIC_STATUS message, which is sent to players by the server to update them on diplomatic status changes between players.
References DiplomaticStatusUpdateInfo::diplo_status, DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, and Message::Message().
Referenced by ServerApp::HandleDiplomaticStatusChange().
DispatchCombatLogsMessage()
Message DispatchCombatLogsMessage (const std::vector< std::pair< int, const CombatLog >> & logs, bool use_binary_serialization)
returns combat logs to the client
References ErrorLogger, and Message::Message().
Referenced by ServerApp::UpdateCombatLogs().
DispatchSavePreviewsMessage()
Message DispatchSavePreviewsMessage (const PreviewInformation & previews)
returns the savegame previews to the client
References Message::Message().
Referenced by ServerApp::UpdateSavePreviews().
EliminateSelfMessage()
Message EliminateSelfMessage ()
creates a ELIMINATE_SELF message to resign from the game.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by HumanClientApp::EliminateSelf().
EndGameMessage()
Message EndGameMessage (Message::EndGameReason reason, const std::string & reason_player_name = "")
creates an END_GAME message used to terminate an active game.
References Message::Message().
Referenced by ServerApp::CleanupAIs(), and ShuttingDownServer::ShuttingDownServer().
ErrorMessage()
Message ErrorMessage (const std::string & problem, bool fatal, int player_id)
creates an ERROR_MSG message
References Message::Message().
Referenced by ServerApp::EliminatePlayer(), ServerFSM::EstablishPlayer(), ServerApp::ExecuteScriptedTurnEvents(), ServerApp::FillListPlayers(), ServerApp::GenerateUniverse(), ServerApp::GetPlayerDelegation(), anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), ServerFSM::HandleNonLobbyDisconnection(), AIClientApp::HandlePythonAICrash(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadChatHistory(), ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::NewGameInitVerifyJoiners(), ServerApp::PushChatMessage(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), ServerApp::SelectNewHost(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
ExtractAuthRequestMessageData()
void ExtractAuthRequestMessageData (const Message & msg, std::string & player_name, std::string & auth)
References ErrorLogger, and Message::Text().
Referenced by WaitingForMPJoinAck::react().
ExtractAuthResponseMessageData()
void ExtractAuthResponseMessageData (const Message & msg, std::string & player_name, std::string & auth)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
ExtractChatHistoryMessage()
void ExtractChatHistoryMessage (const Message & msg, std::vector< ChatHistoryEntity > & chat_history)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react().
ExtractContentCheckSumMessageData()
void ExtractContentCheckSumMessageData (const Message & msg, std::map< std::string, unsigned int > & checksums)
References ErrorLogger, and Message::Text().
Referenced by ClientApp::VerifyCheckSum().
ExtractDiplomacyMessageData()
void ExtractDiplomacyMessageData (const Message & msg, DiplomaticMessage & diplo_message)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
ExtractDiplomaticStatusMessageData()
void ExtractDiplomaticStatusMessageData (const Message & msg, DiplomaticStatusUpdateInfo & diplo_update)
References DiplomaticStatusUpdateInfo::diplo_status, DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
ExtractDispatchCombatLogsMessageData()
FO_COMMON_API void ExtractDispatchCombatLogsMessageData (const Message & msg, std::vector< std::pair< int, CombatLog >> & logs)
References Message::Data(), ErrorLogger, and Message::Text().
Referenced by HumanClientApp::UpdateCombatLogs().
ExtractDispatchSavePreviewsMessageData()
void ExtractDispatchSavePreviewsMessageData (const Message & msg, PreviewInformation & previews)
References ErrorLogger, and Message::Text().
Referenced by HumanClientApp::HandleSaveGamePreviews().
ExtractEndGameMessageData()
void ExtractEndGameMessageData (const Message & msg, Message::EndGameReason & reason, std::string & reason_player_name)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react().
ExtractErrorMessageData()
void ExtractErrorMessageData (const Message & msg, int & player_id, std::string & problem, bool & fatal)
References ErrorLogger, Message::Text(), and UserStringNop.
Referenced by anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), WaitingForSPHostAck::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MPLobby::react(), and PlayingGame::react().
ExtractGameStartMessageData()
void ExtractGameStartMessageData (const Message & msg, bool & single_player_game, int & empire_id, int & current_turn, EmpireManager & empires, Universe & universe, SpeciesManager & species, CombatLogManager & combat_logs, SupplyManager & supply, std::map< int, PlayerInfo > & players, OrderSet & orders, bool & loaded_game_data, bool & ui_data_available, SaveGameUIData & ui_data, bool & save_state_string_available, std::string & save_state_string, GalaxySetupData & galaxy_setup_data)
References CombatLogManager::Clear(), Message::Data(), DebugLogger, Deserialize(), ScopedTimer::DurationString(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), ScopedTimer::restart(), CombatLogManager::SerializeIncompleteLogs(), Message::Text(), and TraceLogger.
Referenced by AIClientApp::HandleMessage(), and WaitingForGameStart::react().
ExtractHostMPGameMessageData()
void ExtractHostMPGameMessageData (const Message & msg, std::string & host_player_name, std::string & client_version_string)
References ErrorLogger, and Message::Text().
Referenced by Idle::react().
ExtractHostSPGameMessageData()
void ExtractHostSPGameMessageData (const Message & msg, SinglePlayerSetupData & setup_data, std::string & client_version_string)
References ErrorLogger, and Message::Text().
Referenced by Idle::react().
ExtractJoinAckMessageData()
void ExtractJoinAckMessageData (const Message & msg, int & player_id, boost::uuids::uuid & cookie)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and WaitingForMPJoinAck::react().
ExtractJoinGameMessageData()
void ExtractJoinGameMessageData (const Message & msg, std::string & player_name, Networking::ClientType & client_type, std::string & version_string, boost::uuids::uuid & cookie)
References DebugLogger, ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
ExtractLobbyUpdateMessageData()
void ExtractLobbyUpdateMessageData (const Message & msg, MultiplayerLobbyData & lobby_data)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), and PlayingGame::react().
ExtractLoggerConfigMessageData()
FO_COMMON_API void ExtractLoggerConfigMessageData (const Message & msg, std::set< std::tuple< std::string, std::string, LogLevel >> & options)
References ErrorLogger, and Message::Text().
Referenced by ServerApp::HandleLoggerConfig(), and AIClientApp::HandleMessage().
ExtractModeratorActionMessageData()
void ExtractModeratorActionMessageData (const Message & msg, Moderator::ModeratorAction *& mod_action)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react().
ExtractPlayerChatMessageData()
void ExtractPlayerChatMessageData (const Message & msg, std::set< int > & recipients, std::string & data, bool & pm)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), and WaitingForMPGameJoiners::react().
ExtractPlayerInfoMessageData()
void ExtractPlayerInfoMessageData (const Message & msg, std::map< int, PlayerInfo > & players)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
ExtractPlayerStatusMessageData()
void ExtractPlayerStatusMessageData (const Message & msg, Message::PlayerStatus & status, int & about_empire_id)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react(), and PlayingTurn::react().
ExtractRequestCombatLogsMessageData()
FO_COMMON_API void ExtractRequestCombatLogsMessageData (const Message & msg, std::vector< int > & ids)
References ErrorLogger, and Message::Text().
Referenced by ServerApp::UpdateCombatLogs().
ExtractRequestSavePreviewsMessageData()
void ExtractRequestSavePreviewsMessageData (const Message & msg, std::string & directory)
References Message::Text().
Referenced by ServerApp::UpdateSavePreviews().
ExtractServerPlayerChatMessageData()
void ExtractServerPlayerChatMessageData (const Message & msg, int & sender, boost::posix_time::ptime & timestamp, std::string & data, bool & pm)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), MPLobby::react(), and PlayingGame::react().
ExtractServerSaveGameCompleteMessageData()
FO_COMMON_API void ExtractServerSaveGameCompleteMessageData (const Message & msg, std::string & save_filename, int & bytes_written)
References ErrorLogger, and Message::Text().
Referenced by WaitingForTurnData::react(), and PlayingTurn::react().
ExtractSetAuthorizationRolesMessage()
void ExtractSetAuthorizationRolesMessage (const Message & msg, Networking::AuthRoles & roles)
References Networking::AuthRoles::SetText(), and Message::Text().
Referenced by HumanClientApp::HandleSetAuthRoles().
ExtractTurnOrdersMessageData()
void ExtractTurnOrdersMessageData (const Message & msg, OrderSet & orders, bool & ui_data_available, SaveGameUIData & ui_data, bool & save_state_string_available, std::string & save_state_string)
References DebugLogger, Deserialize(), ErrorLogger, and Message::Text().
Referenced by WaitingForTurnEnd::react().
ExtractTurnPartialOrdersMessageData()
void ExtractTurnPartialOrdersMessageData (const Message & msg, OrderSet & added, std::set< int > & deleted)
References DebugLogger, Deserialize(), ErrorLogger, and Message::Text().
Referenced by WaitingForTurnEnd::react().
ExtractTurnPartialUpdateMessageData()
void ExtractTurnPartialUpdateMessageData (const Message & msg, int empire_id, Universe & universe)
References Message::Data(), Deserialize(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
ExtractTurnProgressMessageData()
void ExtractTurnProgressMessageData (const Message & msg, Message::TurnProgressPhase & phase_id)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), MPLobby::react(), and PlayingGame::react().
ExtractTurnUpdateMessageData()
void ExtractTurnUpdateMessageData (const Message & msg, int empire_id, int & current_turn, EmpireManager & empires, Universe & universe, SpeciesManager & species, CombatLogManager & combat_logs, SupplyManager & supply, std::map< int, PlayerInfo > & players)
References Message::Data(), Deserialize(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), CombatLogManager::SerializeIncompleteLogs(), and Message::Text().
Referenced by AIClientApp::HandleMessage(), and WaitingForTurnData::react().
GameStartMessage() [1/3]
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
Contains the initial game state visible to the player.
References Universe::EncodingEmpire(), GetUniverse(), GalaxySetupData::m_encoding_empire, Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
Referenced by ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), ServerApp::LoadGameInit(), and ServerApp::SendNewGameStartMessages().
GameStartMessage() [2/3]
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, const OrderSet & orders, const SaveGameUIData * ui_data, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
Contains the initial game state visible to the player. Also includes data loaded from a saved game.
References Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), GalaxySetupData::m_encoding_empire, Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
GameStartMessage() [3/3]
Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, const OrderSet & orders, const std::string * save_state_string, GalaxySetupData galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message.
Contains the initial game state visible to the player. Also includes state string loaded from a saved game.
References Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), GalaxySetupData::m_encoding_empire, Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
HeaderToBuffer()
void HeaderToBuffer (const Message & message, Message::HeaderBuffer & buffer)
Fills header_buf from the relevant portions of message.
References Message::Size(), and Message::Type().
Referenced by ClientNetworking::Impl::AsyncWriteMessage(), and PlayerConnection::AsyncWriteMessage().
HostIDMessage()
Message HostIDMessage (int host_player_id)
creates a HOST_ID message.
The player ID of the host is sent in the message.
References Message::Message(), and to_string().
Referenced by ServerFSM::EstablishPlayer(), and ServerApp::SelectNewHost().
HostMPAckMessage()
Message HostMPAckMessage (int player_id)
creates a HOST_MP_GAME acknowledgement message.
The player_id is the ID of the receiving player. This message should only be sent by the server.
References Message::Message(), and to_string().
Referenced by Idle::react().
HostMPGameMessage()
Message HostMPGameMessage (const std::string & host_player_name)
creates a minimal HOST_MP_GAME message used to initiate multiplayer "lobby" setup
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::MultiPlayerGame().
HostSaveGameInitiateMessage()
Message HostSaveGameInitiateMessage (const std::string & filename)
creates a SAVE_GAME_INITIATE request message.
This message should only be sent by the host player.
References Message::Message().
Referenced by WaitingForTurnEnd::react(), ProcessingTurn::react(), HumanClientApp::SaveGame(), HumanClientApp::SaveGameCompleted(), and WaitingForTurnEnd::SaveTimedoutHandler().
HostSPAckMessage()
Message HostSPAckMessage (int player_id)
creates a HOST_SP_GAME acknowledgement message.
The player_id is the ID of the receiving player. This message should only be sent by the server.
References Message::Message(), and to_string().
Referenced by Idle::react().
HostSPGameMessage()
Message HostSPGameMessage (const SinglePlayerSetupData & setup_data)
creates a HOST_SP_GAME message
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::LoadSinglePlayerGame(), and HumanClientApp::NewSinglePlayerGame().
JoinAckMessage()
Message JoinAckMessage (int player_id, boost::uuids::uuid cookie)
creates a JOIN_GAME acknowledgement message.
The player_id is the ID of the receiving player and cookie is a token to quickly authenticate player. This message should only be sent by the server.
References Message::Message().
Referenced by ServerFSM::EstablishPlayer(), WaitingForSPGameJoiners::react(), and WaitingForMPGameJoiners::react().
JoinGameMessage()
Message JoinGameMessage (const std::string & player_name, Networking::ClientType client_type, boost::uuids::uuid cookie)
creates a JOIN_GAME message.
The sender's player name, client type, and cookie are sent in the message.
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::MultiPlayerGame(), and AIClientApp::Run().
LobbyUpdateMessage()
Message LobbyUpdateMessage (const MultiplayerLobbyData & lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the server, then to other users.
Clients must send all such updates to the server directly; the server will send updates to the other clients as needed.
References Message::Message().
Referenced by MultiPlayerLobbyWnd::SendUpdate().
LoggerConfigMessage()
Message LoggerConfigMessage (int sender, const std::set< std::tuple< std::string, std::string, LogLevel >> & options)
Sends logger configuration details to server or ai process.
References Message::Message().
Referenced by MPLobby::EstablishPlayer(), ServerApp::HandleLoggerConfig(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and HumanClientApp::SendLoggingConfigToServer().
ModeratorActionMessage()
Message ModeratorActionMessage (const Moderator::ModeratorAction & mod_action)
creates a MODERATOR_ACTION message used to implement moderator commands.
References tag_parser::action, and Message::Message().
Referenced by MapWnd::BuildingRightClicked(), MapWnd::FieldRightClicked(), MapWnd::FleetsRightClicked(), ObjectListWnd::ObjectRightClicked(), MapWnd::PlanetRightClicked(), MapWnd::RClick(), MapWnd::ShipsRightClicked(), and MapWnd::SystemRightClicked().
operator!=()
bool operator!= (const Message & lhs, const Message & rhs)
operator<<()
std::ostream& operator<< (std::ostream & os, const Message & msg)
Writes msg to os.
The format of the output is designed for debugging purposes.
References Message::Text(), and Message::Type().
operator==()
bool operator== (const Message & lhs, const Message & rhs)
References Message::Text(), and Message::Type().
PlayerChatMessage()
Message PlayerChatMessage (const std::string & text, std::set< int > recipients, bool pm)
creates an PLAYER_CHAT message containing a chat string to be broadcast to player receiver, or all players if receiver is Networking::INVALID_PLAYER_ID.
Note that the receiver of this message is always the server.
References Message::Message().
Referenced by anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), and anonymous_namespace{AIWrapper.cpp}::SendPlayerChatMessage().
PlayerInfoMessage()
Message PlayerInfoMessage (const std::map< int, PlayerInfo > & players)
creates a PLAYER_INFO message to notify player about changes in the player list.
References Message::Message().
Referenced by ServerFSM::UpdateIngameLobby().
PlayerStatusMessage()
Message PlayerStatusMessage (Message::PlayerStatus player_status, int about_empire_id)
creates a PLAYER_STATUS message.
References Message::Message().
Referenced by ServerApp::AddPlayerIntoGame(), ServerApp::EliminatePlayer(), WaitingForTurnEnd::react(), and ProcessingTurn::react().
RequestCombatLogsMessage()
Message RequestCombatLogsMessage (const std::vector< int > & ids)
requests combat logs from server
References Message::Message().
Referenced by HumanClientApp::UpdateCombatLogManager().
RequestSavePreviewsMessage()
Message RequestSavePreviewsMessage (std::string relative_directory)
requests previews of savefiles from server synchronously
requests previews of savefiles from server
References Message::Message().
Referenced by HumanClientApp::RequestSavePreviews().
ServerLobbyUpdateMessage()
Message ServerLobbyUpdateMessage (const MultiplayerLobbyData & lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the users.
This message should only be sent by the server.
References Message::Message().
Referenced by MPLobby::EstablishPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), MPLobby::react(), ServerFSM::UpdateIngameLobby(), and MPLobby::ValidateClientLimits().
ServerPlayerChatMessage()
Message ServerPlayerChatMessage (int sender, const boost::posix_time::ptime & timestamp, const std::string & text, bool pm = false)
creates an PLAYER_CHAT message containing a chat string from sender at timestamp to be displayed in chat.
This message should only be sent by the server.
References Message::Message().
Referenced by ServerFSM::EstablishPlayer(), ServerFSM::HandleNonLobbyDisconnection(), MPLobby::react(), WaitingForMPGameJoiners::react(), and MPLobby::ValidateClientLimits().
ServerSaveGameCompleteMessage()
Message ServerSaveGameCompleteMessage (const std::string & save_filename, int bytes_written)
creates a SAVE_GAME_COMPLETE complete message.
This message should only be sent by the server to inform clients that the last initiated save has been completed successfully.
References Message::Message().
Referenced by ServerFSM::HandleNonLobbyDisconnection(), PlayingGame::react(), and WaitingForTurnEnd::react().
SetAuthorizationRolesMessage()
Message SetAuthorizationRolesMessage (const Networking::AuthRoles & roles)
notifies client about changes in his authorization roles.
References Message::Message(), and Networking::AuthRoles::Text().
Referenced by PlayerConnection::SetAuthenticated(), PlayerConnection::SetAuthRole(), and PlayerConnection::SetAuthRoles().
ShutdownServerMessage()
Message ShutdownServerMessage ()
tells server to shut down.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by QuittingGame::react().
StartMPGameMessage()
Message StartMPGameMessage ()
creates a START_MP_GAME used to finalize the multiplayer lobby setup.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by MPLobby::react().
swap()
void swap (Message & lhs, Message & rhs)
Swaps the contents of lhs and rhs. Does not throw.
References Message::Swap().
Referenced by Encyclopedia::Articles(), anonymous_namespace{HumanClientApp.cpp}::ClearPreviousPendingSaves(), ObjectMap::ExistingFields(), MessageEventBase::MessageEventBase(), MessageQueue::PopFront(), MessageQueue::PushBack(), ClientNetworking::Impl::SendMessageImpl(), PlayerConnection::SendMessageImpl(), Message::Swap(), Pending::SwapPending(), and Pending::SwapPendingRawPointers().
TurnOrdersMessage() [1/2]
Message TurnOrdersMessage (const OrderSet & orders, const SaveGameUIData & ui_data)
creates a TURN_ORDERS message, including UI data but without a state string.
References Message::Message(), and Serialize().
Referenced by ClientApp::StartTurn().
TurnOrdersMessage() [2/2]
Message TurnOrdersMessage (const OrderSet & orders, const std::string & save_state_string)
creates a TURN_ORDERS message, without UI data but with a state string.
References Message::Message(), and Serialize().
TurnPartialOrdersMessage()
Message TurnPartialOrdersMessage (const std::pair< OrderSet, std::set< int >> & orders_updates)
creates a TURN_PARTIAL_ORDERS message with orders changes.
References Message::Message(), and Serialize().
Referenced by ClientApp::SendPartialOrders().
TurnPartialUpdateMessage()
Message TurnPartialUpdateMessage (int empire_id, const Universe & universe, bool use_binary_serialization)
create a TURN_PARTIAL_UPDATE message.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), and Serialize().
Referenced by ServerApp::PreCombatProcessTurns(), and PlayingGame::react().
TurnProgressMessage()
Message TurnProgressMessage (Message::TurnProgressPhase phase_id)
creates a TURN_PROGRESS message.
References Message::Message().
Referenced by ServerApp::CreateAIClients(), LoadGame(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), ServerApp::ProcessCombats(), PlayingGame::react(), and WaitingForTurnEnd::react().
TurnTimeoutMessage()
Message TurnTimeoutMessage (int timeout_remainig)
creates a TURN_TIMEOUT message with remaining time timeout_.
References Message::Message(), and to_string().
Referenced by PlayingGame::EstablishPlayer(), and WaitingForTurnEnd::WaitingForTurnEnd().
TurnUpdateMessage()
Message TurnUpdateMessage (int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, bool use_binary_serialization)
creates a TURN_UPDATE message.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
Referenced by ServerApp::PostCombatProcessTurns().
UnreadyMessage()
Message UnreadyMessage ()
creates a UNREADY message to revoke ready state of turn orders or acknowledge it
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by HumanClientApp::UnreadyTurn().