FreeOrion: Message.h File Reference
Message.h File Reference
#include "Networking.h"
#include "../util/Export.h"
#include <GG/Enum.h>
#include <boost/shared_array.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
#include <boost/uuid/uuid.hpp>
#include <array>
#include <set>
#include <map>
#include <string>
#include <vector>
Classes
class Message
Namespaces
Moderator
Functions
FO_COMMON_API Message AIEndGameAcknowledgeMessage ()
FO_COMMON_API Message AuthRequestMessage (const std::string &player_name, const std::string &auth)
FO_COMMON_API Message AuthResponseMessage (const std::string &player_name, const std::string &auth)
FO_COMMON_API void BufferToHeader (const Message::HeaderBuffer &buffer, Message &message)
FO_COMMON_API Message ChatHistoryMessage (const std::vector< std::reference_wrapper< const ChatHistoryEntity >> &chat_history)
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet &orders, const SaveGameUIData &ui_data)
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet &orders, const std::string &save_state_string)
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet &orders)
FO_COMMON_API Message ContentCheckSumMessage ()
FO_COMMON_API Message DiplomacyMessage (const DiplomaticMessage &diplo_message)
FO_COMMON_API Message DiplomaticStatusMessage (const DiplomaticStatusUpdateInfo &diplo_update)
FO_COMMON_API Message DispatchCombatLogsMessage (const std::vector< std::pair< int, const CombatLog >> &logs)
FO_COMMON_API Message DispatchSavePreviewsMessage (const PreviewInformation &preview)
FO_COMMON_API Message EliminateSelfMessage ()
FO_COMMON_API Message EndGameMessage (Message::EndGameReason reason, const std::string &reason_player_name="")
FO_COMMON_API Message ErrorMessage (const std::string &problem, bool fatal=true, int player_id=Networking::INVALID_PLAYER_ID)
FO_COMMON_API void ExtractAuthRequestMessageData (const Message &msg, std::string &player_name, std::string &auth)
FO_COMMON_API void ExtractAuthResponseMessageData (const Message &msg, std::string &player_name, std::string &auth)
FO_COMMON_API void ExtractChatHistoryMessage (const Message &msg, std::vector< ChatHistoryEntity > &chat_history)
FO_COMMON_API void ExtractClientSaveDataMessageData (const Message &msg, OrderSet &orders, bool &ui_data_available, SaveGameUIData &ui_data, bool &save_state_string_available, std::string &save_state_string)
FO_COMMON_API void ExtractContentCheckSumMessageData (const Message &msg, std::map< std::string, unsigned int > &checksums)
FO_COMMON_API void ExtractDiplomacyMessageData (const Message &msg, DiplomaticMessage &diplo_message)
FO_COMMON_API void ExtractDiplomaticStatusMessageData (const Message &msg, DiplomaticStatusUpdateInfo &diplo_update)
FO_COMMON_API void ExtractDispatchCombatLogsMessageData (const Message &msg, std::vector< std::pair< int, CombatLog >> &logs)
FO_COMMON_API void ExtractDispatchSavePreviewsMessageData (const Message &msg, PreviewInformation &previews)
FO_COMMON_API void ExtractEndGameMessageData (const Message &msg, Message::EndGameReason &reason, std::string &reason_player_name)
FO_COMMON_API void ExtractErrorMessageData (const Message &msg, int &player_id, std::string &problem, bool &fatal)
FO_COMMON_API void ExtractGameStartMessageData (const Message &msg, bool &single_player_game, int &empire_id, int &current_turn, EmpireManager &empires, Universe &universe, SpeciesManager &species, CombatLogManager &combat_logs, SupplyManager &supply, std::map< int, PlayerInfo > &players, OrderSet &orders, bool &loaded_game_data, bool &ui_data_available, SaveGameUIData &ui_data, bool &save_state_string_available, std::string &save_state_string, GalaxySetupData &galaxy_setup_data)
FO_COMMON_API void ExtractHostMPGameMessageData (const Message &msg, std::string &host_player_name, std::string &client_version_string)
FO_COMMON_API void ExtractHostSPGameMessageData (const Message &msg, SinglePlayerSetupData &setup_data, std::string &client_version_string)
FO_COMMON_API void ExtractJoinAckMessageData (const Message &msg, int &player_id, boost::uuids::uuid &cookie)
FO_COMMON_API void ExtractJoinGameMessageData (const Message &msg, std::string &player_name, Networking::ClientType &client_type, std::string &version_string, boost::uuids::uuid &cookie)
FO_COMMON_API void ExtractLobbyUpdateMessageData (const Message &msg, MultiplayerLobbyData &lobby_data)
FO_COMMON_API void ExtractLoggerConfigMessageData (const Message &msg, std::set< std::tuple< std::string, std::string, LogLevel >> &options)
FO_COMMON_API void ExtractModeratorActionMessageData (const Message &msg, Moderator::ModeratorAction *&action)
FO_COMMON_API void ExtractPlayerChatMessageData (const Message &msg, int &receiver, std::string &data)
FO_COMMON_API void ExtractPlayerStatusMessageData (const Message &msg, int &about_player_id, Message::PlayerStatus &status)
FO_COMMON_API void ExtractRequestCombatLogsMessageData (const Message &msg, std::vector< int > &ids)
FO_COMMON_API void ExtractRequestSavePreviewsMessageData (const Message &msg, std::string &directory)
FO_COMMON_API void ExtractServerPlayerChatMessageData (const Message &msg, int &sender, boost::posix_time::ptime &timestamp, std::string &data)
FO_COMMON_API void ExtractServerSaveGameCompleteMessageData (const Message &msg, std::string &save_filename, int &bytes_written)
FO_COMMON_API void ExtractSetAuthorizationRolesMessage (const Message &msg, Networking::AuthRoles &roles)
FO_COMMON_API void ExtractTurnOrdersMessageData (const Message &msg, OrderSet &orders)
FO_COMMON_API void ExtractTurnPartialUpdateMessageData (const Message &msg, int empire_id, Universe &universe)
FO_COMMON_API void ExtractTurnProgressMessageData (const Message &msg, Message::TurnProgressPhase &phase_id)
FO_COMMON_API void ExtractTurnUpdateMessageData (const Message &msg, int empire_id, int &current_turn, EmpireManager &empires, Universe &universe, SpeciesManager &species, CombatLogManager &combat_logs, SupplyManager &supply, std::map< int, PlayerInfo > &players)
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, const GalaxySetupData &galaxy_setup_data, bool use_binary_serialization)
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, const OrderSet &orders, const SaveGameUIData *ui_data, const GalaxySetupData &galaxy_setup_data, bool use_binary_serialization)
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, const OrderSet &orders, const std::string *save_state_string, const GalaxySetupData &galaxy_setup_data, bool use_binary_serialization)
FO_COMMON_API void HeaderToBuffer (const Message &message, Message::HeaderBuffer &buffer)
FO_COMMON_API Message HostIDMessage (int host_player_id)
FO_COMMON_API Message HostMPAckMessage (int player_id)
FO_COMMON_API Message HostMPGameMessage (const std::string &host_player_name)
FO_COMMON_API Message HostSaveGameInitiateMessage (const std::string &filename)
FO_COMMON_API Message HostSPAckMessage (int player_id)
FO_COMMON_API Message HostSPGameMessage (const SinglePlayerSetupData &setup_data)
FO_COMMON_API Message JoinAckMessage (int player_id, boost::uuids::uuid cookie)
FO_COMMON_API Message JoinGameMessage (const std::string &player_name, Networking::ClientType client_type, boost::uuids::uuid cookie)
FO_COMMON_API Message LobbyUpdateMessage (const MultiplayerLobbyData &lobby_data)
FO_COMMON_API Message LoggerConfigMessage (int sender, const std::set< std::tuple< std::string, std::string, LogLevel >> &options)
FO_COMMON_API Message ModeratorActionMessage (const Moderator::ModeratorAction &mod_action)
bool operator!= (const Message &lhs, const Message &rhs)
FO_COMMON_API std::ostream & operator<< (std::ostream &os, const Message &msg)
bool operator== (const Message &lhs, const Message &rhs)
FO_COMMON_API Message PlayerChatMessage (const std::string &text, int receiver=Networking::INVALID_PLAYER_ID)
FO_COMMON_API Message PlayerStatusMessage (int about_player_id, Message::PlayerStatus player_status)
FO_COMMON_API Message RequestCombatLogsMessage (const std::vector< int > &ids)
FO_COMMON_API Message RequestSavePreviewsMessage (std::string relative_directory)
FO_COMMON_API Message ServerLobbyUpdateMessage (const MultiplayerLobbyData &lobby_data)
FO_COMMON_API Message ServerPlayerChatMessage (int sender, const boost::posix_time::ptime &timestamp, const std::string &text)
FO_COMMON_API Message ServerSaveGameCompleteMessage (const std::string &save_filename, int bytes_written)
FO_COMMON_API Message ServerSaveGameDataRequestMessage ()
FO_COMMON_API Message SetAuthorizationRolesMessage (const Networking::AuthRoles &roles)
FO_COMMON_API Message ShutdownServerMessage ()
FO_COMMON_API Message StartMPGameMessage ()
FO_COMMON_API void swap (Message &lhs, Message &rhs)
Swaps the contents of lhs and rhs. Does not throw.
FO_COMMON_API Message TurnOrdersMessage (const OrderSet &orders)
FO_COMMON_API Message TurnPartialUpdateMessage (int empire_id, const Universe &universe, bool use_binary_serialization)
FO_COMMON_API Message TurnProgressMessage (Message::TurnProgressPhase phase_id)
FO_COMMON_API Message TurnUpdateMessage (int empire_id, int current_turn, const EmpireManager &empires, const Universe &universe, const SpeciesManager &species, CombatLogManager &combat_logs, const SupplyManager &supply, const std::map< int, PlayerInfo > &players, bool use_binary_serialization)
Function Documentation
FO_COMMON_API Message AIEndGameAcknowledgeMessage ()
creates an AI_END_GAME_ACK message used to indicate that the AI has shutdown.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by AIClientApp::HandleMessage().
FO_COMMON_API Message AuthRequestMessage (const std::string & player_name, const std::string & auth)
creates a AUTH_REQUEST message containing player_name to login and auth additional authentication data.
References Message::Message().
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
FO_COMMON_API Message AuthResponseMessage (const std::string & player_name, const std::string & auth)
creates a AUTH_RESPONSE message containing player_name to login and auth credentials.
References Message::Message().
Referenced by PasswordEnterWnd::OkClicked().
FO_COMMON_API void BufferToHeader (const Message::HeaderBuffer & buffer, Message & message)
Fills in the relevant portions of message with the values in the buffer buffer.
References Message::m_message_size, and Message::m_type.
Referenced by ClientNetworking::Impl::HandleMessageHeaderRead(), and PlayerConnection::HandleMessageHeaderRead().
FO_COMMON_API Message ChatHistoryMessage (const std::vector< std::reference_wrapper< const ChatHistoryEntity >> & chat_history)
creates an CHAT_HISTORY message containing latest chat messages. This message should only be sent by the server.
References Message::Message().
Referenced by ServerFSM::EstablishPlayer().
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet & orders, const SaveGameUIData & ui_data)
creates a CLIENT_SAVE_DATA message, including UI data but without a state string.
References Message::Message(), and Serialize().
Referenced by AIClientApp::HandleMessage(), and HumanClientApp::HandleSaveGameDataRequest().
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet & orders, const std::string & save_state_string)
creates a CLIENT_SAVE_DATA message, without UI data but with a state string.
References Message::Message(), and Serialize().
FO_COMMON_API Message ClientSaveDataMessage (const OrderSet & orders)
creates a CLIENT_SAVE_DATA message, without UI data and without a state string.
References Message::Message(), and Serialize().
FO_COMMON_API Message ContentCheckSumMessage ()
creates a CHECKSUM message containing checksums of parsed content.
References CheckSumContent(), and Message::Message().
Referenced by ServerFSM::EstablishPlayer(), Idle::react(), and WaitingForSPGameJoiners::react().
FO_COMMON_API Message DiplomacyMessage (const DiplomaticMessage & diplo_message)
creates a DIPLOMACY message, which is sent between players via the server to declare, proposed, or accept / reject diplomatic arrangements or agreements.
References Message::Message().
Referenced by ServerApp::HandleDiplomaticMessageChange(), anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction(), and AIInterface::SendDiplomaticMessage().
FO_COMMON_API Message DiplomaticStatusMessage (const DiplomaticStatusUpdateInfo & diplo_update)
creates a DIPLOMATIC_STATUS message, which is sent to players by the server to update them on diplomatic status changes between players.
References DiplomaticStatusUpdateInfo::diplo_status, DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, and Message::Message().
Referenced by ServerApp::HandleDiplomaticStatusChange().
FO_COMMON_API Message DispatchCombatLogsMessage (const std::vector< std::pair< int, const CombatLog >> & logs)
returns combat logs to the client
References Message::Message().
Referenced by ServerApp::UpdateCombatLogs().
FO_COMMON_API Message DispatchSavePreviewsMessage (const PreviewInformation & previews)
returns the savegame previews to the client
References Message::Message().
Referenced by ServerApp::UpdateSavePreviews().
FO_COMMON_API Message EliminateSelfMessage ()
creates a ELIMINATE_SELF message to resign from the game.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by HumanClientApp::EliminateSelf().
FO_COMMON_API Message EndGameMessage (Message::EndGameReason reason, const std::string & reason_player_name = "")
creates an END_GAME message used to terminate an active game.
References Message::Message().
Referenced by ServerApp::CleanupAIs(), and ShuttingDownServer::ShuttingDownServer().
FO_COMMON_API Message ErrorMessage (const std::string & problem, bool fatal = true, int player_id = Networking::INVALID_PLAYER_ID)
creates an ERROR_MSG message
References Message::Message().
Referenced by ServerApp::EliminatePlayer(), ServerFSM::EstablishPlayer(), PlayingGame::EstablishPlayer(), ServerApp::ExecuteScriptedTurnEvents(), ServerApp::GenerateUniverse(), anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), AIClientApp::HandlePythonAICrash(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::NewGameInitVerifyJoiners(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), WaitingForTurnEnd::react(), WaitingForTurnEndIdle::react(), WaitingForSaveData::react(), ServerApp::SelectNewHost(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
FO_COMMON_API void ExtractAuthRequestMessageData (const Message & msg, std::string & player_name, std::string & auth)
References ErrorLogger, and Message::Text().
Referenced by WaitingForMPJoinAck::react().
FO_COMMON_API void ExtractAuthResponseMessageData (const Message & msg, std::string & player_name, std::string & auth)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
FO_COMMON_API void ExtractChatHistoryMessage (const Message & msg, std::vector< ChatHistoryEntity > & chat_history)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react().
FO_COMMON_API void ExtractClientSaveDataMessageData (const Message & msg, OrderSet & orders, bool & ui_data_available, SaveGameUIData & ui_data, bool & save_state_string_available, std::string & save_state_string)
References DebugLogger, Deserialize(), ErrorLogger, and Message::Text().
Referenced by WaitingForSaveData::react().
FO_COMMON_API void ExtractContentCheckSumMessageData (const Message & msg, std::map< std::string, unsigned int > & checksums)
References ErrorLogger, and Message::Text().
Referenced by ClientApp::VerifyCheckSum().
FO_COMMON_API void ExtractDiplomacyMessageData (const Message & msg, DiplomaticMessage & diplo_message)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), PlayingGame::react(), and WaitingForMPGameJoiners::react().
FO_COMMON_API void ExtractDiplomaticStatusMessageData (const Message & msg, DiplomaticStatusUpdateInfo & diplo_update)
References DiplomaticStatusUpdateInfo::diplo_status, DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
FO_COMMON_API void ExtractDispatchCombatLogsMessageData (const Message & msg, std::vector< std::pair< int, CombatLog >> & logs)
References ErrorLogger, and Message::Text().
Referenced by HumanClientApp::UpdateCombatLogs().
FO_COMMON_API void ExtractDispatchSavePreviewsMessageData (const Message & msg, PreviewInformation & previews)
References ErrorLogger, and Message::Text().
Referenced by HumanClientApp::HandleSaveGamePreviews().
FO_COMMON_API void ExtractEndGameMessageData (const Message & msg, Message::EndGameReason & reason, std::string & reason_player_name)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react().
FO_COMMON_API void ExtractErrorMessageData (const Message & msg, int & player_id, std::string & problem, bool & fatal)
References ErrorLogger, Message::Text(), and UserStringNop.
Referenced by anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), WaitingForSPHostAck::react(), WaitingForMPHostAck::react(), WaitingForMPJoinAck::react(), MPLobby::react(), and PlayingGame::react().
FO_COMMON_API void ExtractGameStartMessageData (const Message & msg, bool & single_player_game, int & empire_id, int & current_turn, EmpireManager & empires, Universe & universe, SpeciesManager & species, CombatLogManager & combat_logs, SupplyManager & supply, std::map< int, PlayerInfo > & players, OrderSet & orders, bool & loaded_game_data, bool & ui_data_available, SaveGameUIData & ui_data, bool & save_state_string_available, std::string & save_state_string, GalaxySetupData & galaxy_setup_data)
References CombatLogManager::Clear(), Message::Data(), DebugLogger, Deserialize(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), CombatLogManager::SerializeIncompleteLogs(), and Message::Text().
Referenced by AIClientApp::HandleMessage(), and WaitingForGameStart::react().
FO_COMMON_API void ExtractHostMPGameMessageData (const Message & msg, std::string & host_player_name, std::string & client_version_string)
References ErrorLogger, and Message::Text().
Referenced by Idle::react().
FO_COMMON_API void ExtractHostSPGameMessageData (const Message & msg, SinglePlayerSetupData & setup_data, std::string & client_version_string)
References ErrorLogger, and Message::Text().
Referenced by Idle::react().
FO_COMMON_API void ExtractJoinAckMessageData (const Message & msg, int & player_id, boost::uuids::uuid & cookie)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and WaitingForMPJoinAck::react().
FO_COMMON_API void ExtractJoinGameMessageData (const Message & msg, std::string & player_name, Networking::ClientType & client_type, std::string & version_string, boost::uuids::uuid & cookie)
References DebugLogger, ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and PlayingGame::react().
FO_COMMON_API void ExtractLobbyUpdateMessageData (const Message & msg, MultiplayerLobbyData & lobby_data)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react().
FO_COMMON_API void ExtractLoggerConfigMessageData (const Message & msg, std::set< std::tuple< std::string, std::string, LogLevel >> & options)
References ErrorLogger, and Message::Text().
Referenced by ServerApp::HandleLoggerConfig(), and AIClientApp::HandleMessage().
FO_COMMON_API void ExtractModeratorActionMessageData (const Message & msg, Moderator::ModeratorAction *& action)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react().
FO_COMMON_API void ExtractPlayerChatMessageData (const Message & msg, int & receiver, std::string & data)
References ErrorLogger, and Message::Text().
Referenced by MPLobby::react(), and WaitingForMPGameJoiners::react().
FO_COMMON_API void ExtractPlayerStatusMessageData (const Message & msg, int & about_player_id, Message::PlayerStatus & status)
References ErrorLogger, and Message::Text().
Referenced by PlayingGame::react(), and PlayingTurn::react().
FO_COMMON_API void ExtractRequestCombatLogsMessageData (const Message & msg, std::vector< int > & ids)
References ErrorLogger, and Message::Text().
Referenced by ServerApp::UpdateCombatLogs().
FO_COMMON_API void ExtractRequestSavePreviewsMessageData (const Message & msg, std::string & directory)
References Message::Text().
Referenced by ServerApp::UpdateSavePreviews().
FO_COMMON_API void ExtractServerPlayerChatMessageData (const Message & msg, int & sender, boost::posix_time::ptime & timestamp, std::string & data)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), MPLobby::react(), and PlayingGame::react().
FO_COMMON_API void ExtractServerSaveGameCompleteMessageData (const Message & msg, std::string & save_filename, int & bytes_written)
References ErrorLogger, and Message::Text().
Referenced by WaitingForTurnData::react(), and PlayingTurn::react().
FO_COMMON_API void ExtractSetAuthorizationRolesMessage (const Message & msg, Networking::AuthRoles & roles)
References Networking::AuthRoles::SetText(), and Message::Text().
Referenced by HumanClientApp::HandleSetAuthRoles().
FO_COMMON_API void ExtractTurnOrdersMessageData (const Message & msg, OrderSet & orders)
References Deserialize(), ErrorLogger, and Message::Text().
Referenced by WaitingForTurnEnd::react().
FO_COMMON_API void ExtractTurnPartialUpdateMessageData (const Message & msg, int empire_id, Universe & universe)
References Message::Data(), Deserialize(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
FO_COMMON_API void ExtractTurnProgressMessageData (const Message & msg, Message::TurnProgressPhase & phase_id)
References ErrorLogger, and Message::Text().
Referenced by AIClientApp::HandleMessage(), and PlayingGame::react().
FO_COMMON_API void ExtractTurnUpdateMessageData (const Message & msg, int empire_id, int & current_turn, EmpireManager & empires, Universe & universe, SpeciesManager & species, CombatLogManager & combat_logs, SupplyManager & supply, std::map< int, PlayerInfo > & players)
References Message::Data(), Deserialize(), Universe::EncodingEmpire(), ErrorLogger, GetUniverse(), CombatLogManager::SerializeIncompleteLogs(), and Message::Text().
Referenced by AIClientApp::HandleMessage(), and WaitingForTurnData::react().
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, const GalaxySetupData & galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message. Contains the initial game state visible to the player.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
Referenced by ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), ServerApp::LoadGameInit(), and ServerApp::SendNewGameStartMessages().
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, const OrderSet & orders, const SaveGameUIData * ui_data, const GalaxySetupData & galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message. Contains the initial game state visible to the player. Also includes data loaded from a saved game.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
FO_COMMON_API Message GameStartMessage (bool single_player_game, int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, const OrderSet & orders, const std::string * save_state_string, const GalaxySetupData & galaxy_setup_data, bool use_binary_serialization)
creates a GAME_START message. Contains the initial game state visible to the player. Also includes state string loaded from a saved game.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
FO_COMMON_API void HeaderToBuffer (const Message & message, Message::HeaderBuffer & buffer)
Fills header_buf from the relevant portions of message.
References Message::Size(), and Message::Type().
Referenced by ClientNetworking::Impl::AsyncWriteMessage(), and PlayerConnection::SyncWriteMessage().
FO_COMMON_API Message HostIDMessage (int host_player_id)
creates a HOST_ID message. The player ID of the host is sent in the message.
References Message::Message(), and to_string().
Referenced by ServerFSM::EstablishPlayer(), and ServerApp::SelectNewHost().
FO_COMMON_API Message HostMPAckMessage (int player_id)
creates a HOST_MP_GAME acknowledgement message. The player_id is the ID of the receiving player. This message should only be sent by the server.
References Message::Message(), and to_string().
Referenced by Idle::react().
FO_COMMON_API Message HostMPGameMessage (const std::string & host_player_name)
creates a minimal HOST_MP_GAME message used to initiate multiplayer "lobby" setup
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::MultiPlayerGame().
FO_COMMON_API Message HostSaveGameInitiateMessage (const std::string & filename)
creates a SAVE_GAME_INITIATE request message. This message should only be sent by the host player.
References Message::Message().
Referenced by ProcessingTurn::react(), HumanClientApp::SaveGame(), and HumanClientApp::SaveGameCompleted().
FO_COMMON_API Message HostSPAckMessage (int player_id)
creates a HOST_SP_GAME acknowledgement message. The player_id is the ID of the receiving player. This message should only be sent by the server.
References Message::Message(), and to_string().
Referenced by Idle::react().
FO_COMMON_API Message HostSPGameMessage (const SinglePlayerSetupData & setup_data)
creates a HOST_SP_GAME message
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::LoadSinglePlayerGame(), and HumanClientApp::NewSinglePlayerGame().
FO_COMMON_API Message JoinAckMessage (int player_id, boost::uuids::uuid cookie)
creates a JOIN_GAME acknowledgement message. The player_id is the ID of the receiving player and cookie is a token to quickly authenticate player. This message should only be sent by the server.
References Message::Message().
Referenced by ServerFSM::EstablishPlayer(), WaitingForSPGameJoiners::react(), and WaitingForMPGameJoiners::react().
FO_COMMON_API Message JoinGameMessage (const std::string & player_name, Networking::ClientType client_type, boost::uuids::uuid cookie)
creates a JOIN_GAME message. The sender's player name, client type, and cookie are sent in the message.
References FreeOrionVersionString(), and Message::Message().
Referenced by HumanClientApp::MultiPlayerGame(), and AIClientApp::Run().
FO_COMMON_API Message LobbyUpdateMessage (const MultiplayerLobbyData & lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the server, then to other users. Clients must send all such updates to the server directly; the server will send updates to the other clients as needed.
References Message::Message().
Referenced by MultiPlayerLobbyWnd::SendUpdate().
FO_COMMON_API Message LoggerConfigMessage (int sender, const std::set< std::tuple< std::string, std::string, LogLevel >> & options)
Sends logger configuration details to server or ai process.
References Message::Message().
Referenced by MPLobby::EstablishPlayer(), ServerApp::HandleLoggerConfig(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and HumanClientApp::SendLoggingConfigToServer().
FO_COMMON_API Message ModeratorActionMessage (const Moderator::ModeratorAction & mod_action)
creates a MODERATOR_ACTION message used to implement moderator commands.
References Message::Message().
Referenced by MapWnd::BuildingRightClicked(), MapWnd::FieldRightClicked(), MapWnd::FleetsRightClicked(), ObjectListWnd::ObjectRightClicked(), MapWnd::PlanetRightClicked(), MapWnd::RClick(), MapWnd::ShipsRightClicked(), and MapWnd::SystemRightClicked().
bool operator!= (const Message & lhs, const Message & rhs)
FO_COMMON_API std::ostream& operator<< (std::ostream & os, const Message & msg)
Writes msg to os. The format of the output is designed for debugging purposes.
References Message::Text(), and Message::Type().
bool operator== (const Message & lhs, const Message & rhs)
References Message::Text(), and Message::Type().
FO_COMMON_API Message PlayerChatMessage (const std::string & text, int receiver = Networking::INVALID_PLAYER_ID)
creates an PLAYER_CHAT message containing a chat string to be broadcast to player receiver, or all players if receiver is Networking::INVALID_PLAYER_ID. Note that the receiver of this message is always the server.
References Message::Message().
Referenced by anonymous_namespace{ChatWnd.cpp}::SendChatMessage(), and AIInterface::SendPlayerChatMessage().
FO_COMMON_API Message PlayerStatusMessage (int about_player_id, Message::PlayerStatus player_status)
creates a PLAYER_STATUS message.
References Message::Message().
Referenced by WaitingForTurnEnd::react(), and ProcessingTurn::react().
FO_COMMON_API Message RequestCombatLogsMessage (const std::vector< int > & ids)
requests combat logs from server
References Message::Message().
Referenced by HumanClientApp::UpdateCombatLogManager().
FO_COMMON_API Message RequestSavePreviewsMessage (std::string relative_directory)
requests previews of savefiles from server
requests previews of savefiles from server synchronously
References Message::Message().
Referenced by HumanClientApp::RequestSavePreviews().
FO_COMMON_API Message ServerLobbyUpdateMessage (const MultiplayerLobbyData & lobby_data)
creates an LOBBY_UPDATE message containing changes to the lobby settings that need to propogate to the users. This message should only be sent by the server.
References Message::Message().
Referenced by MPLobby::EstablishPlayer(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), MPLobby::react(), and MPLobby::ValidateClientLimits().
FO_COMMON_API Message ServerPlayerChatMessage (int sender, const boost::posix_time::ptime & timestamp, const std::string & text)
creates an PLAYER_CHAT message containing a chat string from sender at timestamp to be displayed in chat. This message should only be sent by the server.
References Message::Message().
Referenced by MPLobby::react(), and WaitingForMPGameJoiners::react().
FO_COMMON_API Message ServerSaveGameCompleteMessage (const std::string & save_filename, int bytes_written)
creates a SAVE_GAME_COMPLETE complete message. This message should only be sent by the server to inform clients that the last initiated save has been completed successfully.
References Message::Message().
Referenced by WaitingForSaveData::react().
FO_COMMON_API Message ServerSaveGameDataRequestMessage ()
creates a SAVE_GAME_DATA_REQUEST data request message. This message should only be sent by the server to get game data from a client, or to respond to the host player requesting a save be initiated.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by WaitingForSaveData::WaitingForSaveData().
FO_COMMON_API Message SetAuthorizationRolesMessage (const Networking::AuthRoles & roles)
notifies client about changes in his authorization roles.
References Message::Message(), and Networking::AuthRoles::Text().
Referenced by PlayerConnection::SetAuthenticated(), PlayerConnection::SetAuthRole(), and PlayerConnection::SetAuthRoles().
FO_COMMON_API Message ShutdownServerMessage ()
tells server to shut down.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by QuittingGame::react().
FO_COMMON_API Message StartMPGameMessage ()
creates a START_MP_GAME used to finalize the multiplayer lobby setup.
References anonymous_namespace{Message.cpp}::DUMMY_EMPTY_MESSAGE, and Message::Message().
Referenced by MPLobby::react().
FO_COMMON_API void swap (Message & lhs, Message & rhs)
Swaps the contents of lhs and rhs. Does not throw.
References Message::Swap().
Referenced by Encyclopedia::Articles(), anonymous_namespace{HumanClientApp.cpp}::ClearPreviousPendingSaves(), ObjectMap::ExistingFields(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::GetShuffledValidAttackerIDs(), MessageEventBase::MessageEventBase(), MessageQueue::PopFront(), MessageQueue::PushBack(), ClientNetworking::Impl::SendMessageImpl(), Message::Swap(), Pending::SwapPending(), and Pending::SwapPendingRawPointers().
FO_COMMON_API Message TurnOrdersMessage (const OrderSet & orders)
creates a TURN_ORDERS message.
References Message::Message(), and Serialize().
Referenced by ClientApp::StartTurn().
FO_COMMON_API Message TurnPartialUpdateMessage (int empire_id, const Universe & universe, bool use_binary_serialization)
create a TURN_PARTIAL_UPDATE message.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), and Serialize().
Referenced by ServerApp::PreCombatProcessTurns(), and PlayingGame::react().
FO_COMMON_API Message TurnProgressMessage (Message::TurnProgressPhase phase_id)
creates a TURN_PROGRESS message.
References Message::Message().
Referenced by ServerApp::CreateAIClients(), LoadGame(), ServerApp::NewGameInitConcurrentWithJoiners(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), ServerApp::ProcessCombats(), PlayingGame::react(), and WaitingForTurnEnd::react().
FO_COMMON_API Message TurnUpdateMessage (int empire_id, int current_turn, const EmpireManager & empires, const Universe & universe, const SpeciesManager & species, CombatLogManager & combat_logs, const SupplyManager & supply, const std::map< int, PlayerInfo > & players, bool use_binary_serialization)
creates a TURN_UPDATE message.
References Universe::EncodingEmpire(), GetUniverse(), Message::Message(), Serialize(), and CombatLogManager::SerializeIncompleteLogs().
Referenced by ServerApp::PostCombatProcessTurns().