FreeOrion: MultiplayerCommon.h File Reference
MultiplayerCommon.h File Reference
#include "../universe/EnumsFwd.h"
#include "../network/Networking.h"
#include "Export.h"
#include "OptionsDB.h"
#include "Pending.h"
#include "Serialize.h"
#include <GG/Clr.h>
#include <list>
#include <set>
#include <vector>
#include <map>
#include <boost/serialization/access.hpp>
#include <boost/date_time/posix_time/posix_time_types.hpp>
Classes
struct ChatHistoryEntity
struct GalaxySetupData
class GameRules
struct GameRules::Rule
struct MultiplayerLobbyData
struct PlayerInfo
struct PlayerSetupData
struct SaveGameEmpireData
struct SaveGameUIData
struct SinglePlayerSetupData
Typedefs
using GameRulesFn = void(*)(GameRules &)
the function signature for functions that add Rules to the GameRules (void (GameRules&))
Functions
BOOST_CLASS_VERSION (GalaxySetupData, 1)
BOOST_CLASS_VERSION (SaveGameUIData, 1)
FO_COMMON_API GameRules & GetGameRules ()
bool operator!= (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
bool FO_COMMON_API operator== (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
FO_COMMON_API bool RegisterGameRules (GameRulesFn function)
Variables
FO_COMMON_API const int ALL_EMPIRES
FO_COMMON_API const std::string MP_SAVE_FILE_EXTENSION
FO_COMMON_API const std::string SP_SAVE_FILE_EXTENSION
Typedef Documentation
using GameRulesFn = void (*) (GameRules&)
the function signature for functions that add Rules to the GameRules (void (GameRules&))
Function Documentation
BOOST_CLASS_VERSION (GalaxySetupData , 1)
BOOST_CLASS_VERSION (SaveGameUIData , 1)
FO_COMMON_API GameRules& GetGameRules ()
returns the single instance of the GameRules class
References DebugLogger, parse::game_rules(), and anonymous_namespace{MultiplayerCommon.cpp}::GameRulesRegistry().
Referenced by ShipDesign::AdjustedAttack(), AutoResolveCombat(), GameRulesPanel::BoolRuleChanged(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{Empire.cpp}::CalculateNewStockpile(), PartType::Capacity(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GameRulesPanel::CompleteConstruction(), GameRulesPanel::DoubleRuleChanged(), GameRulesPanel::DoubleRuleWidget(), ValueRef::ComplexVariable< T >::Eval(), GenerateStarlanes(), Planet::HabitableSize(), GameRulesPanel::IntRuleChanged(), GameRulesPanel::IntRuleWidget(), ServerApp::NewGameInitConcurrentWithJoiners(), HumanClientApp::NewSinglePlayerGame(), ServerApp::PostCombatProcessTurns(), PartType::ProductionCost(), BuildingType::ProductionCost(), HullType::ProductionCost(), ShipDesign::ProductionCost(), PartType::ProductionCostTimeLocationInvariant(), BuildingType::ProductionCostTimeLocationInvariant(), HullType::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionCostTimeLocationInvariant(), PartType::ProductionTime(), BuildingType::ProductionTime(), HullType::ProductionTime(), ShipDesign::ProductionTime(), WaitingForGameStart::react(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), MapWnd::RenderStarlanes(), Tech::ResearchCost(), Tech::ResearchTime(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), HullType::Speed(), IApp::StartBackgroundParsing(), GameRulesPanel::StringRuleChanged(), GameRulesPanel::StringRuleWidget(), HullType::Structure(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapGalaxySetupData().
bool operator!= (const PlayerSetupData & lhs, const PlayerSetupData & rhs)
bool FO_COMMON_API operator== (const PlayerSetupData & lhs, const PlayerSetupData & rhs)
References PlayerSetupData::m_client_type, PlayerSetupData::m_empire_color, PlayerSetupData::m_empire_name, PlayerSetupData::m_player_name, PlayerSetupData::m_player_ready, PlayerSetupData::m_save_game_empire_id, and PlayerSetupData::m_starting_species_name.
FO_COMMON_API bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules. This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterGameRules(&foo)").
References anonymous_namespace{MultiplayerCommon.cpp}::GameRulesRegistry().
Variable Documentation
FO_COMMON_API const int ALL_EMPIRES
FO_COMMON_API const std::string MP_SAVE_FILE_EXTENSION
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), SaveFileDialog::Init(), ProcessingTurn::react(), anonymous_namespace{HumanClientApp.cpp}::RemoveOldestFiles(), and ServerApp::UpdateSavePreviews().
FO_COMMON_API const std::string SP_SAVE_FILE_EXTENSION
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), SaveFileDialog::Init(), anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame(), anonymous_namespace{HumanClientApp.cpp}::RemoveOldestFiles(), and ServerApp::UpdateSavePreviews().