FreeOrion: MultiplayerCommon.cpp File Reference
MultiplayerCommon.cpp File Reference
#include "MultiplayerCommon.h"
#include "Directories.h"
#include "i18n.h"
#include "LoggerWithOptionsDB.h"
#include "OptionsDB.h"
#include "Random.h"
#include "../universe/Fleet.h"
#include "../universe/Planet.h"
#include "../universe/System.h"
#include "../universe/Enums.h"
Namespaces
anonymous_namespace{MultiplayerCommon.cpp}
Functions
void anonymous_namespace{MultiplayerCommon.cpp}::AddOptions (OptionsDB &db)
std::vector< GameRulesFn > & anonymous_namespace{MultiplayerCommon.cpp}::GameRulesRegistry ()
GameRules & GetGameRules ()
template<typename T1 >
int anonymous_namespace{MultiplayerCommon.cpp}::GetIdx (const T1 &enum_vals_count, const std::string &seed)
bool operator!= (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
bool operator== (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
bool RegisterGameRules (GameRulesFn function)
Variables
static char anonymous_namespace{MultiplayerCommon.cpp}::alphanum [] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
const std::string MP_SAVE_FILE_EXTENSION = ".mps"
const std::string SP_SAVE_FILE_EXTENSION = ".sav"
bool anonymous_namespace{MultiplayerCommon.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
GameRules& GetGameRules ()
returns the single instance of the GameRules class
References DebugLogger, parse::game_rules(), and anonymous_namespace{MultiplayerCommon.cpp}::GameRulesRegistry().
Referenced by ShipDesign::AdjustedAttack(), AutoResolveCombat(), GameRulesPanel::BoolRuleChanged(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{Empire.cpp}::CalculateNewStockpile(), anonymous_namespace{Empire.cpp}::CalculateProductionPerTurnLimit(), PartType::Capacity(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GameRulesPanel::CompleteConstruction(), GameRulesPanel::DoubleRuleChanged(), GameRulesPanel::DoubleRuleWidget(), ValueRef::ComplexVariable< T >::Eval(), GenerateStarlanes(), Planet::HabitableSize(), GameRulesPanel::IntRuleChanged(), GameRulesPanel::IntRuleWidget(), ServerApp::NewGameInitConcurrentWithJoiners(), HumanClientApp::NewSinglePlayerGame(), ServerApp::PostCombatProcessTurns(), PartType::ProductionCost(), BuildingType::ProductionCost(), HullType::ProductionCost(), ShipDesign::ProductionCost(), PartType::ProductionCostTimeLocationInvariant(), BuildingType::ProductionCostTimeLocationInvariant(), HullType::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionCostTimeLocationInvariant(), PartType::ProductionTime(), BuildingType::ProductionTime(), HullType::ProductionTime(), ShipDesign::ProductionTime(), WaitingForGameStart::react(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), MapWnd::RenderStarlanes(), Tech::ResearchCost(), Tech::ResearchTime(), anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts(), HullType::Speed(), IApp::StartBackgroundParsing(), GameRulesPanel::StringRuleChanged(), GameRulesPanel::StringRuleWidget(), HullType::Structure(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapGalaxySetupData().
bool operator!= (const PlayerSetupData & lhs, const PlayerSetupData & rhs)
bool operator== (const PlayerSetupData & lhs, const PlayerSetupData & rhs)
References PlayerSetupData::m_client_type, PlayerSetupData::m_empire_color, PlayerSetupData::m_empire_name, PlayerSetupData::m_player_name, PlayerSetupData::m_player_ready, PlayerSetupData::m_save_game_empire_id, and PlayerSetupData::m_starting_species_name.
bool RegisterGameRules (GameRulesFn function)
adds function to a vector of pointers to functions that add Rules to the GameRules. This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterGameRules(&foo)").
References anonymous_namespace{MultiplayerCommon.cpp}::GameRulesRegistry().
Variable Documentation
const std::string MP_SAVE_FILE_EXTENSION = ".mps"
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), SaveFileDialog::Init(), ProcessingTurn::react(), anonymous_namespace{HumanClientApp.cpp}::RemoveOldestFiles(), and ServerApp::UpdateSavePreviews().
const std::string SP_SAVE_FILE_EXTENSION = ".sav"
Referenced by anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath(), SaveFileDialog::Init(), anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame(), anonymous_namespace{HumanClientApp.cpp}::RemoveOldestFiles(), and ServerApp::UpdateSavePreviews().