FreeOrion: anonymous_namespace{ProductionQueue.cpp} Namespace Reference
anonymous_namespace{ProductionQueue.cpp} Namespace Reference
Functions
void AddRules (GameRules &rules)
float CalculateNewStockpile (int empire_id, float starting_stockpile, float project_transfer_to_stockpile, const std::map< std::set< int >, float > &available_pp, const std::map< std::set< int >, float > &allocated_pp, const std::map< std::set< int >, float > &allocated_stockpile_pp)
float CalculateProductionPerTurnLimit (const ProductionQueue::Element &queue_element, float item_cost, int build_turns)
float SetProdQueueElementSpending (std::map< std::set< int >, float > available_pp, float available_stockpile, float stockpile_limit, const std::vector< std::set< int >> &queue_element_resource_sharing_object_groups, const std::map< std::pair< ProductionQueue::ProductionItem, int >, std::pair< float, int >> &queue_item_costs_and_times, const std::vector< bool > &is_producible, ProductionQueue::QueueType &queue, std::map< std::set< int >, float > &allocated_pp, std::map< std::set< int >, float > &allocated_stockpile_pp, int &projects_in_progress, bool simulating)
Sets the allocated_pp value for each Element in the passed ProductionQueue queue.
Variables
const float EPSILON = 0.001f
bool temp_bool = RegisterGameRules(&AddRules)
Function Documentation
AddRules()
void anonymous_namespace{ProductionQueue.cpp}::AddRules (GameRules & rules)
References GameRules::Add().
CalculateNewStockpile()
float anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile (int empire_id, float starting_stockpile, float project_transfer_to_stockpile, const std::map< std::set< int >, float > & available_pp, const std::map< std::set< int >, float > & allocated_pp, const std::map< std::set< int >, float > & allocated_stockpile_pp)
References ErrorLogger, GetEmpire(), GetGameRules(), Empire::GetProductionQueue(), if(), ProductionQueue::StockpileCapacity(), and TraceLogger.
Referenced by ProductionQueue::Update().
CalculateProductionPerTurnLimit()
float anonymous_namespace{ProductionQueue.cpp}::CalculateProductionPerTurnLimit (const ProductionQueue::Element & queue_element, float item_cost, int build_turns)
References ProductionQueue::Element::blocksize, GameRules::Get(), GetGameRules(), ProductionQueue::Element::progress, and ProductionQueue::Element::remaining.
Referenced by SetProdQueueElementSpending().
SetProdQueueElementSpending()
float anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending (std::map< std::set< int >, float > available_pp, float available_stockpile, float stockpile_limit, const std::vector< std::set< int >> & queue_element_resource_sharing_object_groups, const std::map< std::pair< ProductionQueue::ProductionItem, int >, std::pair< float, int >> & queue_item_costs_and_times, const std::vector< bool > & is_producible, ProductionQueue::QueueType & queue, std::map< std::set< int >, float > & allocated_pp, std::map< std::set< int >, float > & allocated_stockpile_pp, int & projects_in_progress, bool simulating)
Sets the allocated_pp value for each Element in the passed ProductionQueue queue.
Elements are allocated PP based on their need, the limits they can be given per turn, and the amount available at their production location (which is itself limited by the resource supply system groups that are able to exchange resources with the build location and the amount of minerals and industry produced in the group). Elements will not receive funding if they cannot be produced by the empire with the indicated empire_id this turn at their build location. Also checks if elements will be completed this turn. Returns the amount of PP which gets transferred to the stockpile using stockpile project build items.
References CalculateProductionPerTurnLimit(), ErrorLogger, GetGameRules(), if(), INVALID_OBJECT_ID, and TraceLogger.
Referenced by ProductionQueue::Update().
Variable Documentation
EPSILON
const float anonymous_namespace{ProductionQueue.cpp}::EPSILON = 0.001f
Referenced by ProductionQueue::Update().
temp_bool
bool anonymous_namespace{ProductionQueue.cpp}::temp_bool = RegisterGameRules(&AddRules)