FreeOrion: anonymous_namespace{SDLGUI.cpp} Namespace Reference
anonymous_namespace{SDLGUI.cpp} Namespace Reference
Classes
class FramebufferFailedException
struct QuitSignal
Functions
void Enter2DModeImpl (int width, int height)
Flags< ModKey > GetSDLModKeys ()
Pt SetSDLFullscreenSize (SDL_Window *window, int display_id, int width, int height)
Function Documentation
Enter2DModeImpl()
void anonymous_namespace{SDLGUI.cpp}::Enter2DModeImpl (int width, int height)
Referenced by SDLGUI::Enter2DMode(), and SDLGUI::RenderEnd().
GetSDLModKeys()
Flags<ModKey> anonymous_namespace{SDLGUI.cpp}::GetSDLModKeys ()
Referenced by SDLGUI::HandleSystemEvents().
SetSDLFullscreenSize()
Pt anonymous_namespace{SDLGUI.cpp}::SetSDLFullscreenSize (SDL_Window * window, int display_id, int width, int height)
Referenced by SDLGUI::SetVideoMode().