FreeOrion: anonymous_namespace{UniverseWrapper.cpp} Namespace Reference
anonymous_namespace{UniverseWrapper.cpp} Namespace Reference
Functions
std::vector< int > AttackStatsP (const ShipDesign &ship_design)
std::vector< int > BuildingIDs (const Universe &universe)
void DumpObjects (const Universe &universe)
bool EnqueueLocationTest (const BuildingType &building_type, int empire_id, int loc_id)
std::vector< int > FieldIDs (const Universe &universe)
std::vector< int > FleetIDs (const Universe &universe)
const Building * GetBuildingP (const Universe &universe, int id)
const Field * GetFieldP (const Universe &universe, int id)
const Fleet * GetFleetP (const Universe &universe, int id)
const Planet * GetPlanetP (const Universe &universe, int id)
const Ship * GetShipP (const Universe &universe, int id)
const System * GetSystemP (const Universe &universe, int id)
const UniverseObject * GetUniverseObjectP (const Universe &universe, int id)
std::vector< ShipSlotType > HullSlots (const HullType &hull)
std::vector< int > ImmediateNeighborsP (const Universe &universe, int system1_id, int empire_id=ALL_EMPIRES)
int JumpDistanceBetweenObjects (const Universe &universe, int object1_id, int object2_id)
std::vector< int > LeastJumpsPath (const Universe &universe, int start_sys, int end_sys, int empire_id)
double LinearDistance (const Universe &universe, int system1_id, int system2_id)
std::vector< int > ObjectIDs (const Universe &universe)
bool ObjectInField (const Field &field, const UniverseObject &obj)
std::vector< std::string > ObjectSpecials (const UniverseObject &object)
std::vector< int > PlanetIDs (const Universe &universe)
bool RuleExistsAnyType (const GameRules &rules, const std::string &name)
bool RuleExistsWithType (const GameRules &rules, const std::string &name, GameRules::Type type)
const std::string & ShipDesignDescription (const ShipDesign &ship_design)
const std::string & ShipDesignName (const ShipDesign &ship_design)
std::vector< int > ShipIDs (const Universe &universe)
std::vector< int > ShortestNonHostilePath (const Universe &universe, int start_sys, int end_sys, int empire_id)
std::vector< int > ShortestPath (const Universe &universe, int start_sys, int end_sys, int empire_id)
double ShortestPathDistance (const Universe &universe, int object1_id, int object2_id)
std::vector< std::string > SpeciesFoci (const Species &species)
bool SystemHasVisibleStarlanesP (const Universe &universe, int system_id, int empire_id=ALL_EMPIRES)
std::vector< int > SystemIDs (const Universe &universe)
std::map< int, double > SystemNeighborsMapP (const Universe &universe, int system1_id, int empire_id=ALL_EMPIRES)
bool SystemsConnectedP (const Universe &universe, int system1_id, int system2_id, int empire_id=ALL_EMPIRES)
void UpdateMetersWrapper (const Universe &universe, const boost::python::list &objList)
Variables
boost::function< std::vector< int >const ShipDesign &)> AttackStatsFunc = &AttackStatsP
boost::function< std::vector< ShipSlotType >const HullType &)> HullSlotsFunc = &HullSlots
boost::function< std::vector< int >const Universe &, int, int)> ImmediateNeighborsFunc = &ImmediateNeighborsP
boost::function< int(const Universe &, int, int)> JumpDistanceFunc = &JumpDistanceBetweenObjects
boost::function< std::vector< int >const Universe &, int, int, int)> LeastJumpsFunc = &LeastJumpsPath
boost::function< double(const Universe &, int, int)> LinearDistanceFunc = &LinearDistance
bool(Field::* LocationInField)(double x, double y) const = &Field::InField
unsigned int(HullType::* NumSlotsOfSlotType)(ShipSlotType) const = &HullType::NumSlots
unsigned int(HullType::* NumSlotsTotal)(void) const = &HullType::NumSlots
const Meter *(UniverseObject::* ObjectGetMeter)(MeterType) const = &UniverseObject::GetMeter
const std::map< MeterType, Meter > &(UniverseObject::* ObjectMeters)(void) const = &UniverseObject::Meters
const std::vector< std::string > &(ShipDesign::* PartsVoid)(void) const = &ShipDesign::Parts
boost::function< const std::string &(const ShipDesign &)> ShipDesignDescriptionFunc = &ShipDesignDescription
boost::function< const std::string &(const ShipDesign &)> ShipDesignNameFunc = &ShipDesignName
const Meter *(Ship::* ShipGetPartMeter)(MeterType, const std::string &) const = &Ship::GetPartMeter
const Ship::PartMeterMap &(Ship::* ShipPartMeters)(void) const = &Ship::PartMeters
boost::function< std::vector< int >const Universe &, int, int, int)> ShortestNonHostilePathFunc = &ShortestNonHostilePath
boost::function< double(const Universe &, int, int)> ShortestPathDistanceFunc = &ShortestPathDistance
boost::function< std::vector< int >const Universe &, int, int, int)> ShortestPathFunc = &ShortestPath
float(Special::* SpecialInitialCapacityOnObject)(int) const = &Special::InitialCapacity
boost::function< bool(const Universe &, int, int)> SystemHasVisibleStarlanesFunc = &SystemHasVisibleStarlanesP
boost::function< std::map< int, double >const Universe &, int, int)> SystemNeighborsMapFunc = &SystemNeighborsMapP
boost::function< bool(const Universe &, int, int, int)> SystemsConnectedFunc = &SystemsConnectedP
bool(* ValidDesignHullAndParts)(const std::string &hull, const std::vector< std::string > &parts) = &ShipDesign::ValidDesign
Function Documentation
AttackStatsP()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::AttackStatsP (const ShipDesign & ship_design)
References PartType::Capacity(), PartType::Class(), GetPartType(), ShipDesign::Parts(), and PC_DIRECT_WEAPON.
BuildingIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::BuildingIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
DumpObjects()
void anonymous_namespace{UniverseWrapper.cpp}::DumpObjects (const Universe & universe)
References DebugLogger, ObjectMap::Dump(), and Universe::Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
EnqueueLocationTest()
bool anonymous_namespace{UniverseWrapper.cpp}::EnqueueLocationTest (const BuildingType & building_type, int empire_id, int loc_id)
References BuildingType::EnqueueLocation().
Referenced by FreeOrionPython::WrapUniverseClasses().
FieldIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::FieldIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
FleetIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::FleetIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetBuildingP()
const Building* anonymous_namespace{UniverseWrapper.cpp}::GetBuildingP (const Universe & universe, int id)
References GetBuilding().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetFieldP()
const Field* anonymous_namespace{UniverseWrapper.cpp}::GetFieldP (const Universe & universe, int id)
References GetField().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetFleetP()
const Fleet* anonymous_namespace{UniverseWrapper.cpp}::GetFleetP (const Universe & universe, int id)
References GetFleet().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetPlanetP()
const Planet* anonymous_namespace{UniverseWrapper.cpp}::GetPlanetP (const Universe & universe, int id)
References GetPlanet().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetShipP()
const Ship* anonymous_namespace{UniverseWrapper.cpp}::GetShipP (const Universe & universe, int id)
References GetShip().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetSystemP()
const System* anonymous_namespace{UniverseWrapper.cpp}::GetSystemP (const Universe & universe, int id)
References GetSystem().
Referenced by FreeOrionPython::WrapUniverseClasses().
GetUniverseObjectP()
const UniverseObject* anonymous_namespace{UniverseWrapper.cpp}::GetUniverseObjectP (const Universe & universe, int id)
References GetUniverseObject().
Referenced by FreeOrionPython::WrapUniverseClasses().
HullSlots()
std::vector<ShipSlotType> anonymous_namespace{UniverseWrapper.cpp}::HullSlots (const HullType & hull)
References HullType::Slots().
ImmediateNeighborsP()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::ImmediateNeighborsP (const Universe & universe, int system1_id, int empire_id = ALL_EMPIRES)
References Universe::GetPathfinder().
JumpDistanceBetweenObjects()
int anonymous_namespace{UniverseWrapper.cpp}::JumpDistanceBetweenObjects (const Universe & universe, int object1_id, int object2_id)
References Universe::GetPathfinder().
Referenced by Pathfinder::PathfinderImpl::PathfinderImpl().
LeastJumpsPath()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::LeastJumpsPath (const Universe & universe, int start_sys, int end_sys, int empire_id)
References Universe::GetPathfinder().
Referenced by Pathfinder::PathfinderImpl::PathfinderImpl().
LinearDistance()
double anonymous_namespace{UniverseWrapper.cpp}::LinearDistance (const Universe & universe, int system1_id, int system2_id)
References Universe::GetPathfinder().
ObjectIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::ObjectIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
ObjectInField()
bool anonymous_namespace{UniverseWrapper.cpp}::ObjectInField (const Field & field, const UniverseObject & obj)
References Field::InField(), UniverseObject::X(), and UniverseObject::Y().
Referenced by FreeOrionPython::WrapUniverseClasses().
ObjectSpecials()
std::vector<std::string> anonymous_namespace{UniverseWrapper.cpp}::ObjectSpecials (const UniverseObject & object)
Referenced by FreeOrionPython::WrapUniverseClasses().
PlanetIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::PlanetIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
RuleExistsAnyType()
bool anonymous_namespace{UniverseWrapper.cpp}::RuleExistsAnyType (const GameRules & rules, const std::string & name)
References GameRules::RuleExists().
Referenced by FreeOrionPython::WrapGalaxySetupData().
RuleExistsWithType()
bool anonymous_namespace{UniverseWrapper.cpp}::RuleExistsWithType (const GameRules & rules, const std::string & name, GameRules::Type type)
References GameRules::RuleExists().
Referenced by FreeOrionPython::WrapGalaxySetupData().
ShipDesignDescription()
const std::string& anonymous_namespace{UniverseWrapper.cpp}::ShipDesignDescription (const ShipDesign & ship_design)
References ShipDesign::Description().
ShipDesignName()
const std::string& anonymous_namespace{UniverseWrapper.cpp}::ShipDesignName (const ShipDesign & ship_design)
References ShipDesign::Name().
ShipIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::ShipIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
ShortestNonHostilePath()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::ShortestNonHostilePath (const Universe & universe, int start_sys, int end_sys, int empire_id)
References Universe::GetPathfinder().
ShortestPath()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::ShortestPath (const Universe & universe, int start_sys, int end_sys, int empire_id)
References Universe::GetPathfinder().
Referenced by Pathfinder::PathfinderImpl::PathfinderImpl().
ShortestPathDistance()
double anonymous_namespace{UniverseWrapper.cpp}::ShortestPathDistance (const Universe & universe, int object1_id, int object2_id)
References Universe::GetPathfinder().
Referenced by Pathfinder::PathfinderImpl::PathfinderImpl().
SpeciesFoci()
std::vector<std::string> anonymous_namespace{UniverseWrapper.cpp}::SpeciesFoci (const Species & species)
References Species::Foci().
Referenced by FreeOrionPython::WrapUniverseClasses().
SystemHasVisibleStarlanesP()
bool anonymous_namespace{UniverseWrapper.cpp}::SystemHasVisibleStarlanesP (const Universe & universe, int system_id, int empire_id = ALL_EMPIRES)
References Universe::GetPathfinder().
SystemIDs()
std::vector<int> anonymous_namespace{UniverseWrapper.cpp}::SystemIDs (const Universe & universe)
References ObjectMap::FindObjectIDs(), and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
SystemNeighborsMapP()
std::map<int,double> anonymous_namespace{UniverseWrapper.cpp}::SystemNeighborsMapP (const Universe & universe, int system1_id, int empire_id = ALL_EMPIRES)
References Universe::GetPathfinder().
SystemsConnectedP()
bool anonymous_namespace{UniverseWrapper.cpp}::SystemsConnectedP (const Universe & universe, int system1_id, int system2_id, int empire_id = ALL_EMPIRES)
References Universe::GetPathfinder().
UpdateMetersWrapper()
void anonymous_namespace{UniverseWrapper.cpp}::UpdateMetersWrapper (const Universe & universe, const boost::python::list & objList)
References GetUniverse(), and Universe::UpdateMeterEstimates().
Referenced by FreeOrionPython::WrapUniverseClasses().
Variable Documentation
AttackStatsFunc
boost::function<std::vector<int>const ShipDesign&)> anonymous_namespace{UniverseWrapper.cpp}::AttackStatsFunc = &AttackStatsP
Referenced by FreeOrionPython::WrapUniverseClasses().
HullSlotsFunc
boost::function<std::vector<ShipSlotType>const HullType&)> anonymous_namespace{UniverseWrapper.cpp}::HullSlotsFunc = &HullSlots
Referenced by FreeOrionPython::WrapUniverseClasses().
ImmediateNeighborsFunc
boost::function<std::vector<int>const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::ImmediateNeighborsFunc = &ImmediateNeighborsP
Referenced by FreeOrionPython::WrapUniverseClasses().
JumpDistanceFunc
boost::function<int(const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::JumpDistanceFunc = &JumpDistanceBetweenObjects
LeastJumpsFunc
boost::function<std::vector<int>const Universe&, int, int, int)> anonymous_namespace{UniverseWrapper.cpp}::LeastJumpsFunc = &LeastJumpsPath
Referenced by FreeOrionPython::WrapUniverseClasses().
LinearDistanceFunc
boost::function<double(const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::LinearDistanceFunc = &LinearDistance
LocationInField
bool(Field::* anonymous_namespace{UniverseWrapper.cpp}::LocationInField) (double x, double y) const = &Field::InField
Referenced by FreeOrionPython::WrapUniverseClasses().
NumSlotsOfSlotType
unsigned int(HullType::* anonymous_namespace{UniverseWrapper.cpp}::NumSlotsOfSlotType) (ShipSlotType) const = &HullType::NumSlots
Referenced by FreeOrionPython::WrapUniverseClasses().
NumSlotsTotal
unsigned int(HullType::* anonymous_namespace{UniverseWrapper.cpp}::NumSlotsTotal) (void) const = &HullType::NumSlots
Referenced by FreeOrionPython::WrapUniverseClasses().
ObjectGetMeter
const Meter*(UniverseObject::* anonymous_namespace{UniverseWrapper.cpp}::ObjectGetMeter) (MeterType) const = &UniverseObject::GetMeter
Referenced by FreeOrionPython::WrapUniverseClasses().
ObjectMeters
const std::map<MeterType, Meter>&(UniverseObject::* anonymous_namespace{UniverseWrapper.cpp}::ObjectMeters) (void) const = &UniverseObject::Meters
Referenced by FreeOrionPython::WrapUniverseClasses().
PartsVoid
const std::vector<std::string>&(ShipDesign::* anonymous_namespace{UniverseWrapper.cpp}::PartsVoid) (void) const = &ShipDesign::Parts
Referenced by FreeOrionPython::WrapUniverseClasses().
ShipDesignDescriptionFunc
boost::function<const std::string& (const ShipDesign&)> anonymous_namespace{UniverseWrapper.cpp}::ShipDesignDescriptionFunc = &ShipDesignDescription
Referenced by FreeOrionPython::WrapUniverseClasses().
ShipDesignNameFunc
boost::function<const std::string& (const ShipDesign&)> anonymous_namespace{UniverseWrapper.cpp}::ShipDesignNameFunc = &ShipDesignName
Referenced by FreeOrionPython::WrapUniverseClasses().
ShipGetPartMeter
const Meter*(Ship::* anonymous_namespace{UniverseWrapper.cpp}::ShipGetPartMeter) (MeterType, const std::string &) const = &Ship::GetPartMeter
Referenced by FreeOrionPython::WrapUniverseClasses().
ShipPartMeters
const Ship::PartMeterMap&(Ship::* anonymous_namespace{UniverseWrapper.cpp}::ShipPartMeters) (void) const = &Ship::PartMeters
Referenced by FreeOrionPython::WrapUniverseClasses().
ShortestNonHostilePathFunc
boost::function<std::vector<int>const Universe&, int, int, int)> anonymous_namespace{UniverseWrapper.cpp}::ShortestNonHostilePathFunc = &ShortestNonHostilePath
Referenced by FreeOrionPython::WrapUniverseClasses().
ShortestPathDistanceFunc
boost::function<double(const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::ShortestPathDistanceFunc = &ShortestPathDistance
ShortestPathFunc
boost::function<std::vector<int>const Universe&, int, int, int)> anonymous_namespace{UniverseWrapper.cpp}::ShortestPathFunc = &ShortestPath
Referenced by FreeOrionPython::WrapUniverseClasses().
SpecialInitialCapacityOnObject
float(Special::* anonymous_namespace{UniverseWrapper.cpp}::SpecialInitialCapacityOnObject) (int) const = &Special::InitialCapacity
Referenced by FreeOrionPython::WrapUniverseClasses().
SystemHasVisibleStarlanesFunc
boost::function<bool(const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::SystemHasVisibleStarlanesFunc = &SystemHasVisibleStarlanesP
SystemNeighborsMapFunc
boost::function<std::map<int, double>const Universe&, int, int)> anonymous_namespace{UniverseWrapper.cpp}::SystemNeighborsMapFunc = &SystemNeighborsMapP
Referenced by FreeOrionPython::WrapUniverseClasses().
SystemsConnectedFunc
boost::function<bool(const Universe&, int, int, int)> anonymous_namespace{UniverseWrapper.cpp}::SystemsConnectedFunc = &SystemsConnectedP
ValidDesignHullAndParts
bool(* anonymous_namespace{UniverseWrapper.cpp}::ValidDesignHullAndParts) (const std::string &hull, const std::vector< std::string > &parts) = &ShipDesign::ValidDesign
Referenced by FreeOrionPython::WrapUniverseClasses().