FreeOrion: anonymous_namespace{ChatWnd.cpp} Namespace Reference
anonymous_namespace{ChatWnd.cpp} Namespace Reference
Functions
std::string ExtractMessage (const std::string &text)
int ExtractPlayerID (const std::string &text)
void SendChatMessage (const std::string &text, std::set< int > recipients, bool pm)
std::string StringtableTextSubstitute (const std::string &input)
std::string UserStringSubstitute (const boost::xpressive::smatch &match)
Function Documentation
ExtractMessage()
std::string anonymous_namespace{ChatWnd.cpp}::ExtractMessage (const std::string & text)
Referenced by MessageWnd::HandleTextCommand().
ExtractPlayerID()
int anonymous_namespace{ChatWnd.cpp}::ExtractPlayerID (const std::string & text)
References ErrorLogger, ClientApp::GetApp(), Networking::INVALID_PLAYER_ID, and ClientApp::Players().
Referenced by MessageWnd::HandleTextCommand().
SendChatMessage()
void anonymous_namespace{ChatWnd.cpp}::SendChatMessage (const std::string & text, std::set< int > recipients, bool pm)
References ErrorLogger, HumanClientApp::GetApp(), ClientApp::GetApp(), ClientApp::Networking(), PlayerChatMessage(), and ClientNetworking::SendMessage().
Referenced by MessageWnd::HandleTextCommand(), and MessageWnd::MessageEntered().
StringtableTextSubstitute()
std::string anonymous_namespace{ChatWnd.cpp}::StringtableTextSubstitute (const std::string & input)
References UserStringSubstitute().
Referenced by MessageWnd::HandlePlayerChatMessage().
UserStringSubstitute()
std::string anonymous_namespace{ChatWnd.cpp}::UserStringSubstitute (const boost::xpressive::smatch & match)
References FlexibleFormat(), UserString(), and UserStringExists().
Referenced by StringtableTextSubstitute().