FreeOrion: anonymous_namespace{DesignWnd.cpp} Namespace Reference
anonymous_namespace{DesignWnd.cpp} Namespace Reference
Classes
class AvailabilityManager
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a ship design.
class DisplayedShipDesignManager
DisplayedShipDesignManager allows for the storage and manipulation of an ordered list of design ids that are used to order the display of ShipDesigns in the DesignWnd and the ProductionWnd.
class SavedDesignsManager
Typedefs
typedef std::map< std::pair< ShipPartClass, ShipSlotType >, std::vector< const ShipPart * > > PartGroupsType
Functions
void AddSavedDesignToDisplayedDesigns (const boost::uuids::uuid &uuid, int empire_id, bool is_front=true)
Add design to the is_front of empire_id's list of current designs.
const GG::Y BASES_LIST_BOX_ROW_HEIGHT (100)
bool CanAddDesignToDisplayedDesigns (const ShipDesign *design)
boost::filesystem::path CreateSaveFileNameForDesign (const ShipDesign &design)
void DeleteFromDisplayedDesigns (const int design_id)
Remove design from DisplayedDesigns.
boost::filesystem::path GetDesignsDir ()
DisplayedShipDesignManager & GetDisplayedDesignsManager ()
float GetMainStat (const ShipPart *part)
SavedDesignsManager & GetSavedDesignsManager ()
bool LocationASubsumesLocationB (const Condition::Condition *check_part_loc, const Condition::Condition *ref_part_loc)
const int PAD (3)
const GG::Y PART_CONTROL_HEIGHT (54)
const GG::X PART_CONTROL_WIDTH (54)
bool PartALocationSubsumesPartB (const ShipPart *check_part, const ShipPart *ref_part)
std::shared_ptr< GG::Texture > PartBackgroundTexture (const ShipPart *part)
Returns background texture with which to render a PartControl, depending on the types of slot that the indicated part can be put into.
void ReportFileError (const boost::filesystem::path &file)
boost::filesystem::path SavedDesignsDir ()
void SetObsoleteInDisplayedDesigns (const int design_id, bool obsolete)
Set whether a currently known design is obsolete or not.
const GG::Y SLOT_CONTROL_HEIGHT (60)
const GG::X SLOT_CONTROL_WIDTH (60)
std::shared_ptr< GG::Texture > SlotBackgroundTexture (ShipSlotType slot_type)
Returns texture with which to render a SlotControl, depending on slot_type.
void WriteToFile (const boost::filesystem::path &file, const std::string &ss)
Variables
const GG::Pt BASES_MIN_SIZE {GG::X{160}, GG::Y{160}}
const std::string COMPLETE_DESIGN_ROW_DROP_STRING = "Complete Design Row"
const std::string DES_BASE_SELECTOR_WND_NAME = "design.selector"
const std::string DES_MAIN_WND_NAME = "design.edit"
const std::string DES_PART_PALETTE_WND_NAME = "design.parts"
const std::string DES_PEDIA_WND_NAME = "design.pedia"
const std::string DESIGN_FILENAME_EXTENSION = ".focs.txt"
const std::string DESIGN_FILENAME_PREFIX = "ShipDesign-"
const std::string DESIGN_MANIFEST_PREFIX = "ShipDesignOrdering"
const std::string EMPTY_STRING = ""
const std::string HULL_PARTS_ROW_DROP_TYPE_STRING = "Hull and Parts Row"
const GG::Pt MAIN_PANEL_MIN_SIZE {GG::X{400}, GG::Y{160}}
const GG::Pt PALETTE_MIN_SIZE {GG::X{450}, GG::Y{400}}
const std::string PART_CONTROL_DROP_TYPE_STRING = "Part Control"
const std::string SAVED_DESIGN_ROW_DROP_STRING = "Saved Design Row"
const std::string UNABLE_TO_OPEN_FILE = "Unable to open file"
Typedef Documentation
PartGroupsType
typedef std::map<std::pair<ShipPartClass, ShipSlotType>, std::vector<const ShipPart*> > anonymous_namespace{DesignWnd.cpp}::PartGroupsType
Function Documentation
AddSavedDesignToDisplayedDesigns()
void anonymous_namespace{DesignWnd.cpp}::AddSavedDesignToDisplayedDesigns (const boost::uuids::uuid & uuid, int empire_id, bool is_front = true)
Add design to the is_front of empire_id's list of current designs.
References CanAddDesignToDisplayedDesigns(), DebugLogger, ErrorLogger, HumanClientApp::GetApp(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), GetDisplayedDesignsManager(), GetEmpire(), GetSavedDesignsManager(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), ClientApp::Orders(), and TraceLogger.
Referenced by SavedDesignsListBox::BaseLeftClicked(), SavedDesignsListBox::BaseRightClicked(), and anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns().
BASES_LIST_BOX_ROW_HEIGHT()
const GG::Y anonymous_namespace{DesignWnd.cpp}::BASES_LIST_BOX_ROW_HEIGHT (100)
Referenced by BasesListBox::ListRowSize().
CanAddDesignToDisplayedDesigns()
bool anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns (const ShipDesign * design)
References anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::AllOrderedIDs(), GetDisplayedDesignsManager(), and GetShipDesign().
Referenced by AddSavedDesignToDisplayedDesigns(), and SavedDesignsListBox::BaseRightClicked().
CreateSaveFileNameForDesign()
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::CreateSaveFileNameForDesign (const ShipDesign & design)
References GetDesignsDir(), PathToString(), to_string(), and ShipDesign::UUID().
Referenced by anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::InsertBefore().
DeleteFromDisplayedDesigns()
void anonymous_namespace{DesignWnd.cpp}::DeleteFromDisplayedDesigns (const int design_id)
Remove design from DisplayedDesigns.
References ClientApp::EmpireID(), HumanClientApp::GetApp(), GetDisplayedDesignsManager(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by CompletedDesignsListBox::BaseRightClicked().
GetDesignsDir()
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::GetDesignsDir ()
References SavedDesignsDir().
Referenced by CreateSaveFileNameForDesign(), and anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifestConst().
GetDisplayedDesignsManager()
DisplayedShipDesignManager& anonymous_namespace{DesignWnd.cpp}::GetDisplayedDesignsManager ()
References ShipDesignManager::DisplayedDesigns(), ClientUI::GetClientUI(), and ClientUI::GetShipDesignManager().
Referenced by DesignWnd::MainPanel::AddDesign(), AddSavedDesignToDisplayedDesigns(), EmptyHullsListBox::BaseLeftClicked(), CompletedDesignsListBox::BaseLeftClicked(), EmptyHullsListBox::BaseRightClicked(), CompletedDesignsListBox::BaseRightClicked(), CanAddDesignToDisplayedDesigns(), DeleteFromDisplayedDesigns(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedDesignAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedHullAvailability(), anonymous_namespace{DesignWnd.cpp}::AvailabilityManager::DisplayedPartAvailability(), DesignWnd::MainPanel::EditingCurrentDesign(), DesignWnd::PartPalette::HandleShipPartClicked(), DesignWnd::PartPalette::HandleShipPartRightClicked(), ShipDesignManager::Load(), EmptyHullsListBox::PopulateCore(), CompletedDesignsListBox::PopulateCore(), EmptyHullsListBox::QueueItemMoved(), CompletedDesignsListBox::QueueItemMoved(), DesignWnd::MainPanel::ReplaceDesign(), ShipDesignManager::Save(), and SetObsoleteInDisplayedDesigns().
GetMainStat()
float anonymous_namespace{DesignWnd.cpp}::GetMainStat (const ShipPart * part)
Referenced by PartsListBox::CullSuperfluousParts(), and PartsListBox::Populate().
GetSavedDesignsManager()
SavedDesignsManager& anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager ()
References ClientUI::GetClientUI(), ClientUI::GetShipDesignManager(), and ShipDesignManager::SavedDesigns().
Referenced by DesignWnd::MainPanel::AcceptDrops(), DesignWnd::MainPanel::AddDesign(), AddSavedDesignToDisplayedDesigns(), SavedDesignsListBox::BaseLeftClicked(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::ChildrenDraggedAwayCore(), SavedDesignsListBox::SavedDesignListBoxRow::Description(), SavedDesignsListBox::SavedDesignListBoxRow::DesignName(), SavedDesignsListBox::SavedDesignListBoxRow::DesignUUID(), DesignWnd::MainPanel::EditingSavedDesign(), SavedDesignsListBox::SavedDesignListBoxRow::LookupInStringtable(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::OrderedIDs(), SavedDesignsListBox::PopulateCore(), SavedDesignsListBox::QueueItemMoved(), DesignWnd::MainPanel::ReplaceDesign(), and DesignWnd::MainPanel::SetDesign().
LocationASubsumesLocationB()
bool anonymous_namespace{DesignWnd.cpp}::LocationASubsumesLocationB (const Condition::Condition * check_part_loc, const Condition::Condition * ref_part_loc)
Referenced by PartALocationSubsumesPartB().
PAD()
const int anonymous_namespace{DesignWnd.cpp}::PAD (3)
Referenced by DesignWnd::MainPanel::DoLayout(), PartsListBox::Populate(), and PartsListBox::SizeMove().
PART_CONTROL_HEIGHT()
const GG::Y anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_HEIGHT (54)
Referenced by PartControl::CompleteConstruction().
PART_CONTROL_WIDTH()
const GG::X anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_WIDTH (54)
Referenced by PartControl::CompleteConstruction().
PartALocationSubsumesPartB()
bool anonymous_namespace{DesignWnd.cpp}::PartALocationSubsumesPartB (const ShipPart * check_part, const ShipPart * ref_part)
References if(), and LocationASubsumesLocationB().
Referenced by PartsListBox::CullSuperfluousParts().
PartBackgroundTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{DesignWnd.cpp}::PartBackgroundTexture (const ShipPart * part)
Returns background texture with which to render a PartControl, depending on the types of slot that the indicated part can be put into.
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by PartControl::CompleteConstruction().
ReportFileError()
void anonymous_namespace{DesignWnd.cpp}::ReportFileError (const boost::filesystem::path & file)
References ErrorLogger, FlexibleFormat(), ClientUI::MessageBox(), and UserString().
Referenced by WriteToFile().
SavedDesignsDir()
boost::filesystem::path anonymous_namespace{DesignWnd.cpp}::SavedDesignsDir ()
References GetUserDataDir().
Referenced by GetDesignsDir(), and anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::StartParsingDesignsFromFileSystem().
SetObsoleteInDisplayedDesigns()
void anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns (const int design_id, bool obsolete)
Set whether a currently known design is obsolete or not.
Not obsolete means that it is known to the empire (on the server) and will appear in the production list. Obsolete means that it will only appear in the list of obsolete designs.
References ClientApp::EmpireID(), ErrorLogger, HumanClientApp::GetApp(), GetDisplayedDesignsManager(), GetShipDesign(), OrderSet::IssueOrder(), ClientApp::Orders(), and WarnLogger.
Referenced by CompletedDesignsListBox::BaseLeftClicked(), and CompletedDesignsListBox::BaseRightClicked().
SLOT_CONTROL_HEIGHT()
const GG::Y anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_HEIGHT (60)
Referenced by PartControl::CompleteConstruction(), SlotControl::CompleteConstruction(), and PartsListBox::Populate().
SLOT_CONTROL_WIDTH()
const GG::X anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH (60)
Referenced by PartControl::CompleteConstruction(), SlotControl::CompleteConstruction(), PartsListBox::Populate(), and PartsListBox::SizeMove().
SlotBackgroundTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{DesignWnd.cpp}::SlotBackgroundTexture (ShipSlotType slot_type)
Returns texture with which to render a SlotControl, depending on slot_type.
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by SlotControl::CompleteConstruction().
WriteToFile()
void anonymous_namespace{DesignWnd.cpp}::WriteToFile (const boost::filesystem::path & file, const std::string & ss)
References ErrorLogger, PathToString(), ReportFileError(), and TraceLogger.
Referenced by anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveDesign(), and anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifestConst().
Variable Documentation
BASES_MIN_SIZE
const GG::Pt anonymous_namespace{DesignWnd.cpp}::BASES_MIN_SIZE {GG::X{160}, GG::Y{160}}
Referenced by DesignWnd::BaseSelector::CompleteConstruction().
COMPLETE_DESIGN_ROW_DROP_STRING
const std::string anonymous_namespace{DesignWnd.cpp}::COMPLETE_DESIGN_ROW_DROP_STRING = "Complete Design Row"
Referenced by BasesListBox::CompletedDesignListBoxRow::CompleteConstruction(), and DesignWnd::BaseSelector::CompleteConstruction().
DES_BASE_SELECTOR_WND_NAME
const std::string anonymous_namespace{DesignWnd.cpp}::DES_BASE_SELECTOR_WND_NAME = "design.selector"
Referenced by DesignWnd::CompleteConstruction().
DES_MAIN_WND_NAME
const std::string anonymous_namespace{DesignWnd.cpp}::DES_MAIN_WND_NAME = "design.edit"
Referenced by DesignWnd::CompleteConstruction().
DES_PART_PALETTE_WND_NAME
const std::string anonymous_namespace{DesignWnd.cpp}::DES_PART_PALETTE_WND_NAME = "design.parts"
Referenced by DesignWnd::CompleteConstruction().
DES_PEDIA_WND_NAME
const std::string anonymous_namespace{DesignWnd.cpp}::DES_PEDIA_WND_NAME = "design.pedia"
Referenced by DesignWnd::CompleteConstruction().
DESIGN_FILENAME_EXTENSION
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_EXTENSION = ".focs.txt"
Referenced by anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), and anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::SaveManifestConst().
DESIGN_FILENAME_PREFIX
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_FILENAME_PREFIX = "ShipDesign-"
DESIGN_MANIFEST_PREFIX
const std::string anonymous_namespace{DesignWnd.cpp}::DESIGN_MANIFEST_PREFIX = "ShipDesignOrdering"
EMPTY_STRING
const std::string anonymous_namespace{DesignWnd.cpp}::EMPTY_STRING = ""
Referenced by SavedDesignsListBox::SavedDesignListBoxRow::Description(), SavedDesignsListBox::SavedDesignListBoxRow::DesignName(), DesignWnd::MainPanel::Hull(), PartControl::PartName(), and DesignWnd::MainPanel::RefreshIncompleteDesign().
HULL_PARTS_ROW_DROP_TYPE_STRING
const std::string anonymous_namespace{DesignWnd.cpp}::HULL_PARTS_ROW_DROP_TYPE_STRING = "Hull and Parts Row"
Referenced by BasesListBox::HullAndPartsListBoxRow::CompleteConstruction(), and DesignWnd::BaseSelector::CompleteConstruction().
MAIN_PANEL_MIN_SIZE
const GG::Pt anonymous_namespace{DesignWnd.cpp}::MAIN_PANEL_MIN_SIZE {GG::X{400}, GG::Y{160}}
Referenced by DesignWnd::MainPanel::CompleteConstruction().
PALETTE_MIN_SIZE
const GG::Pt anonymous_namespace{DesignWnd.cpp}::PALETTE_MIN_SIZE {GG::X{450}, GG::Y{400}}
Referenced by EncyclopediaDetailPanel::CompleteConstruction(), and DesignWnd::PartPalette::CompleteConstruction().
PART_CONTROL_DROP_TYPE_STRING
const std::string anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_DROP_TYPE_STRING = "Part Control"
Referenced by PartControl::CompleteConstruction(), PartsListBox::DropsAcceptable(), and SlotControl::DropsAcceptable().
SAVED_DESIGN_ROW_DROP_STRING
const std::string anonymous_namespace{DesignWnd.cpp}::SAVED_DESIGN_ROW_DROP_STRING = "Saved Design Row"
Referenced by SavedDesignsListBox::SavedDesignListBoxRow::CompleteConstruction(), and DesignWnd::BaseSelector::CompleteConstruction().
UNABLE_TO_OPEN_FILE
const std::string anonymous_namespace{DesignWnd.cpp}::UNABLE_TO_OPEN_FILE = "Unable to open file"