FreeOrion: anonymous_namespace{CombatLogWnd.cpp} Namespace Reference
anonymous_namespace{CombatLogWnd.cpp} Namespace Reference
Classes
class CombatLogAccordionPanel
A Single section in the CombatLog showing general outline of a ship's combat and expanding into specifics.
class EmpireForcesAccordionPanel
A section used in initial forces and destroyed forces, displays empire's name and forces count; and can be expanded to enumerate all forces of this empire that take part in the combat.
class LazyScrollerLinkText
LazyScrollerLinkText is a link text that initially populates itself with an ellipsis.
class OrderByNameAndId
Functions
std::string CountToText (int empire_id, int forces_count)
converts to "Empire_name: n" text
DeclareThreadSafeLogger (combat_log)
std::string EmpireIdToText (int empire_id)
template<typename T >
T const * FindParentOfType (GG::Wnd const *parent)
Find a parent of type T.
std::string ForcesToText (int viewing_empire_id, const std::vector< std::vector< std::shared_ptr< UniverseObject >>> &forces, const std::string &delimiter=", ", const std::string &category_delimiter="\\)
bool HasPopulation (std::shared_ptr< UniverseObject > object)
bool IsShip (std::shared_ptr< UniverseObject > object)
const std::string & LinkTag (UniverseObjectType obj_type)
std::map< int, std::vector< std::vector< std::shared_ptr< UniverseObject > > > > SegregateForces (const std::set< int > &owners, const std::set< int > &objects, std::vector< std::function< bool(std::shared_ptr< UniverseObject >)>> categories, std::function< bool(std::shared_ptr< UniverseObject >, std::shared_ptr< UniverseObject >)> order)
Segregates objects into categories based on categories and ownership; only applies to objects owned by one of owners; within a category, sorts by order.
std::string WrapWithTagAndId (const std::string &meat, const std::string &tag, int id)
Function Documentation
CountToText()
std::string anonymous_namespace{CombatLogWnd.cpp}::CountToText (int empire_id, int forces_count)
converts to "Empire_name: n" text
References EmpireIdToText().
DeclareThreadSafeLogger()
anonymous_namespace{CombatLogWnd.cpp}::DeclareThreadSafeLogger (combat_log)
EmpireIdToText()
std::string anonymous_namespace{CombatLogWnd.cpp}::EmpireIdToText (int empire_id)
References ClientUI::DefaultLinkColor(), VarText::EMPIRE_ID_TAG, GetEmpire(), to_string(), and UserString().
Referenced by CountToText().
FindParentOfType()
template<typename T > T const* anonymous_namespace{CombatLogWnd.cpp}::FindParentOfType (GG::Wnd const * parent)
Find a parent of type T.
ForcesToText()
std::string anonymous_namespace{CombatLogWnd.cpp}::ForcesToText (int viewing_empire_id, const std::vector< std::vector< std::shared_ptr< UniverseObject >>> & forces, const std::string & delimiter = ", ", const std::string & category_delimiter = "\n-\n")
References LinkTag(), and WrapWithTagAndId().
Referenced by anonymous_namespace{CombatLogWnd.cpp}::EmpireForcesAccordionPanel::ToggleExpansion().
HasPopulation()
bool anonymous_namespace{CombatLogWnd.cpp}::HasPopulation (std::shared_ptr< UniverseObject > object)
IsShip()
bool anonymous_namespace{CombatLogWnd.cpp}::IsShip (std::shared_ptr< UniverseObject > object)
LinkTag()
const std::string& anonymous_namespace{CombatLogWnd.cpp}::LinkTag (UniverseObjectType obj_type)
References VarText::BUILDING_ID_TAG, anonymous_namespace{Empire.cpp}::EMPTY_STRING, VarText::FLEET_ID_TAG, VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, and VarText::SYSTEM_ID_TAG.
Referenced by ForcesToText().
SegregateForces()
std::map<int, std::vector<std::vector<std::shared_ptr<UniverseObject> > > > anonymous_namespace{CombatLogWnd.cpp}::SegregateForces (const std::set< int > & owners, const std::set< int > & objects, std::vector< std::function< bool(std::shared_ptr< UniverseObject >)>> categories, std::function< bool(std::shared_ptr< UniverseObject >, std::shared_ptr< UniverseObject >)> order)
Segregates objects into categories based on categories and ownership; only applies to objects owned by one of owners; within a category, sorts by order.
References Objects().
Referenced by CombatLogWnd::Impl::SetLog().
WrapWithTagAndId()
std::string anonymous_namespace{CombatLogWnd.cpp}::WrapWithTagAndId (const std::string & meat, const std::string & tag, int id)
Referenced by ForcesToText().