FreeOrion: anonymous_namespace{GraphicalSummary.cpp} Namespace Reference
anonymous_namespace{GraphicalSummary.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
GG::Pt AdjustForAxes (const GG::Pt &size)
constexpr GG::Y AXIS_HEIGHT (10)
constexpr GG::X AXIS_WIDTH (10)
constexpr GG::X BEVEL_MARGIN_X (6)
constexpr GG::Y BEVEL_MARGIN_Y (12)
template<typename T >
T interpolate (double modifier, const T &value1, const T &value2)
GG::Y OPTION_BAR_HEIGHT (25)
constexpr GG::Y OPTION_BUTTON_HEIGHT (20)
constexpr GG::X OPTION_BUTTON_PADDING (8)
constexpr GG::Y SIDE_BAR_UP_MARGIN (5)
constexpr GG::Y SIDE_BOX_MARGIN (8)
constexpr GG::Y X_AXIS_LABEL_MARGIN (8)
constexpr GG::X Y_AXIS_LABEL_MARGIN (3)
Variables
constexpr float EPSILON = 0.00001f
int MIN_PARTICIPANT_BAR_HEIGHT
constexpr int MIN_SIDE_BAR_HEIGHT = 40
constexpr int MIN_SIDE_BAR_WIDTH = 100
const std::string OPTIONS_ROOT = "ui.combat.summary.graph."
bool temp_bool = RegisterOptions(&AddOptions)
const std::string TOGGLE_BAR_HEALTH_SMOOTH = "bar.health.smooth.enabled"
const std::string TOGGLE_BAR_HEIGHT_PROPORTIONAL = "bar.proportional.height.enabled"
const std::string TOGGLE_BAR_WIDTH_PROPORTIONAL = "bar.proportional.width.enabled"
const std::string TOGGLE_GRAPH_HEIGHT_PROPORTIONAL = "height.proportional.enabled"
Function Documentation
AddOptions()
void anonymous_namespace{GraphicalSummary.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), TOGGLE_BAR_HEALTH_SMOOTH, TOGGLE_BAR_HEIGHT_PROPORTIONAL, TOGGLE_BAR_WIDTH_PROPORTIONAL, TOGGLE_GRAPH_HEIGHT_PROPORTIONAL, and UserStringNop.
AdjustForAxes()
GG::Pt anonymous_namespace{GraphicalSummary.cpp}::AdjustForAxes (const GG::Pt & size)
Referenced by BarSizer::GetBarSize().
AXIS_HEIGHT()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT (10)
Referenced by BarSizer::GetMinSize(), BarSizer::GetSideBarSize(), SideBar::RelativeClientUpperLeft(), and BarSizer::SetAvailableSize().
AXIS_WIDTH()
constexpr GG::X anonymous_namespace{GraphicalSummary.cpp}::AXIS_WIDTH (10)
Referenced by SideBar::DoLayout(), and SideBar::RelativeClientUpperLeft().
BEVEL_MARGIN_X()
constexpr GG::X anonymous_namespace{GraphicalSummary.cpp}::BEVEL_MARGIN_X (6)
Referenced by BarSizer::SetAvailableSize().
BEVEL_MARGIN_Y()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::BEVEL_MARGIN_Y (12)
interpolate()
template<typename T > T anonymous_namespace{GraphicalSummary.cpp}::interpolate (double modifier, const T & value1, const T & value2)
Referenced by ParticipantBar::Render().
OPTION_BAR_HEIGHT()
GG::Y anonymous_namespace{GraphicalSummary.cpp}::OPTION_BAR_HEIGHT (25)
Referenced by GraphicalSummaryWnd::DoLayout(), and OptionsBar::MinUsableSize().
OPTION_BUTTON_HEIGHT()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::OPTION_BUTTON_HEIGHT (20)
Referenced by OptionsBar::DoLayout().
OPTION_BUTTON_PADDING()
constexpr GG::X anonymous_namespace{GraphicalSummary.cpp}::OPTION_BUTTON_PADDING (8)
Referenced by OptionsBar::DoLayout(), and OptionsBar::MinUsableSize().
SIDE_BAR_UP_MARGIN()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::SIDE_BAR_UP_MARGIN (5)
Referenced by SideBar::DoLayout(), BarSizer::GetMinSize(), BarSizer::GetSideBarSize(), SideBar::RelativeClientUpperLeft(), and BarSizer::SetAvailableSize().
SIDE_BOX_MARGIN()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::SIDE_BOX_MARGIN (8)
Referenced by GraphicalSummaryWnd::DoLayout(), BarSizer::GetMinSize(), and BarSizer::SetAvailableSize().
X_AXIS_LABEL_MARGIN()
constexpr GG::Y anonymous_namespace{GraphicalSummary.cpp}::X_AXIS_LABEL_MARGIN (8)
Referenced by BarSizer::GetMinSize(), BarSizer::GetSideBarSize(), SideBar::RelativeClientUpperLeft(), and BarSizer::SetAvailableSize().
Y_AXIS_LABEL_MARGIN()
constexpr GG::X anonymous_namespace{GraphicalSummary.cpp}::Y_AXIS_LABEL_MARGIN (3)
Referenced by SideBar::RelativeClientUpperLeft().
Variable Documentation
EPSILON
constexpr float anonymous_namespace{GraphicalSummary.cpp}::EPSILON = 0.00001f
Referenced by GraphicalSummaryWnd::GenerateGraph().
MIN_PARTICIPANT_BAR_HEIGHT
int anonymous_namespace{GraphicalSummary.cpp}::MIN_PARTICIPANT_BAR_HEIGHT
Initial value:
= MIN_SIDE_BAR_HEIGHT -
                                     Value(AXIS_HEIGHT) -
                                     Value(X_AXIS_LABEL_MARGIN) -
                                     Value(SIDE_BAR_UP_MARGIN)
Referenced by BarSizer::GetMinSize().
MIN_SIDE_BAR_HEIGHT
constexpr int anonymous_namespace{GraphicalSummary.cpp}::MIN_SIDE_BAR_HEIGHT = 40
Referenced by BarSizer::GetSideBarSize().
MIN_SIDE_BAR_WIDTH
constexpr int anonymous_namespace{GraphicalSummary.cpp}::MIN_SIDE_BAR_WIDTH = 100
Referenced by BarSizer::GetMinSize(), and BarSizer::GetSideBarSize().
OPTIONS_ROOT
const std::string anonymous_namespace{GraphicalSummary.cpp}::OPTIONS_ROOT = "ui.combat.summary.graph."
Referenced by BarSizer::Get(), and BarSizer::Set().
temp_bool
bool anonymous_namespace{GraphicalSummary.cpp}::temp_bool = RegisterOptions(&AddOptions)
TOGGLE_BAR_HEALTH_SMOOTH
const std::string anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEALTH_SMOOTH = "bar.health.smooth.enabled"
Referenced by AddOptions(), OptionsBar::CompleteConstruction(), and ParticipantBar::Render().
TOGGLE_BAR_HEIGHT_PROPORTIONAL
const std::string anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEIGHT_PROPORTIONAL = "bar.proportional.height.enabled"
Referenced by AddOptions(), OptionsBar::CompleteConstruction(), and BarSizer::GetBarSize().
TOGGLE_BAR_WIDTH_PROPORTIONAL
const std::string anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_WIDTH_PROPORTIONAL = "bar.proportional.width.enabled"
Referenced by AddOptions(), BarSizer::CalculateAliveWidth(), BarSizer::CalculateDeadWidth(), and OptionsBar::CompleteConstruction().
TOGGLE_GRAPH_HEIGHT_PROPORTIONAL
const std::string anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_GRAPH_HEIGHT_PROPORTIONAL = "height.proportional.enabled"
Referenced by AddOptions(), OptionsBar::CompleteConstruction(), BarSizer::GetMinSize(), and BarSizer::GetSideBarSize().