FreeOrion: anonymous_namespace{BuildingsPanel.cpp} Namespace Reference
anonymous_namespace{BuildingsPanel.cpp} Namespace Reference
Functions
bool ClientPlayerIsModerator ()
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
std::map< int, int > PendingScrapOrders ()
Returns map from object ID to issued colonize orders affecting it.
Function Documentation
ClientPlayerIsModerator()
bool anonymous_namespace{BuildingsPanel.cpp}::ClientPlayerIsModerator ()
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, HumanClientApp::GetApp(), and ClientApp::GetClientType().
Referenced by BuildingIndicator::RClick().
MeterIconSize()
GG::Pt anonymous_namespace{BuildingsPanel.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by BuildingsPanel::DoLayout().
PendingScrapOrders()
std::map<int, int> anonymous_namespace{BuildingsPanel.cpp}::PendingScrapOrders ()
Returns map from object ID to issued colonize orders affecting it.
References ClientApp::GetApp(), and ClientApp::Orders().
Referenced by BuildingIndicator::RClick().