FreeOrion: anonymous_namespace{GalaxySetupWnd.cpp} Namespace Reference
anonymous_namespace{GalaxySetupWnd.cpp} Namespace Reference
Classes
class GameRulesList
class RowContentsWnd
class RuleListRow
Functions
void AddOptions (OptionsDB &db)
const GG::Y CONTROL_HEIGHT (30)
const GG::X CONTROL_MARGIN (5)
const GG::Y CONTROL_VMARGIN (5)
const GG::Y GAL_SETUP_PANEL_HT (PANEL_CONTROL_SPACING *10)
const GG::Y GalSetupWndHeight ()
const GG::X GalSetupWndWidth ()
const GG::X INDENTATION (20)
const GG::Y PANEL_CONTROL_SPACING (33)
const GG::Pt PREVIEW_SZ (GG::X(248), GG::Y(186))
const GG::X SPIN_WIDTH (92)
Variables
const bool ALLOW_NO_STARLANES = false
static char alphanum [] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
void anonymous_namespace{GalaxySetupWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), BEGINNER, MANIACAL, IApp::MAX_AI_PLAYERS(), and UserStringNop.
const GG::Y anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_HEIGHT (30)
Referenced by GalaxySetupPanel::DoLayout(), GalaxySetupWnd::DoLayout(), and GalaxySetupWnd::GalaxySetupWnd().
const GG::X anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_MARGIN (5)
Referenced by GameRulesPanel::DoLayout(), GalaxySetupPanel::DoLayout(), and GalaxySetupWnd::DoLayout().
const GG::Y anonymous_namespace{GalaxySetupWnd.cpp}::CONTROL_VMARGIN (5)
Referenced by GameRulesPanel::BoolRuleWidget(), GameRulesPanel::CreateSectionHeader(), GameRulesPanel::DoLayout(), GalaxySetupPanel::DoLayout(), GalaxySetupWnd::DoLayout(), GameRulesPanel::DoubleRuleWidget(), GalaxySetupWnd::GalaxySetupWnd(), and GameRulesPanel::IntRuleWidget().
const GG::Y anonymous_namespace{GalaxySetupWnd.cpp}::GAL_SETUP_PANEL_HT (PANEL_CONTROL_SPACING * 10)
Referenced by GalaxySetupWnd::DoLayout().
const GG::Y anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndHeight ()
References FontBasedUpscale(), and PREVIEW_SZ().
Referenced by GalaxySetupWnd::CalculatePosition().
const GG::X anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndWidth ()
References FontBasedUpscale().
Referenced by GalaxySetupWnd::CalculatePosition().
const GG::X anonymous_namespace{GalaxySetupWnd.cpp}::INDENTATION (20)
const GG::Y anonymous_namespace{GalaxySetupWnd.cpp}::PANEL_CONTROL_SPACING (33)
Referenced by GalaxySetupPanel::DoLayout(), and GalaxySetupWnd::DoLayout().
const GG::Pt anonymous_namespace{GalaxySetupWnd.cpp}::PREVIEW_SZ (GG::X(248) , GG::Y(186))
Referenced by GalaxySetupWnd::DoLayout(), GalSetupWndHeight(), and GalaxySetupWnd::Render().
const GG::X anonymous_namespace{GalaxySetupWnd.cpp}::SPIN_WIDTH (92)
Referenced by GameRulesPanel::DoubleRuleWidget(), GameRulesPanel::GameRulesPanel(), and GameRulesPanel::IntRuleWidget().
Variable Documentation
const bool anonymous_namespace{GalaxySetupWnd.cpp}::ALLOW_NO_STARLANES = false
Referenced by GalaxySetupPanel::GalaxySetupPanel(), GalaxySetupPanel::GetStarlaneFrequency(), and GalaxySetupPanel::SetFromSetupData().
char anonymous_namespace{GalaxySetupWnd.cpp}::alphanum[] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz" static
Referenced by GalaxySetupPanel::RandomClicked().
bool anonymous_namespace{GalaxySetupWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)