FreeOrion: Condition Namespace Reference
Condition Namespace Reference
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Namespaces
anonymous_namespace{Conditions.cpp}
Classes
struct Aggressive
Matches objects that are aggressive fleets or are in aggressive fleets.
struct All
Matches all objects.
struct And
Matches all objects that match every Condition in operands.
struct Armed
Matches armed ships and monsters.
struct Building
Matches all Building objects that are one of the building types specified in names.
struct CanAddStarlaneConnection
Matches objects that are in systems that could have starlanes added between them and all (not just one) of the systems containing (or that are) one of the objects matched by condition.
struct CanColonize
Matches objects whose species has the ability to found new colonies.
struct CanProduceShips
Matches objects whose species has the ability to produce ships.
struct Capital
Matches planets that are an empire's capital.
struct Chance
Matches a given object with a linearly distributed probability of chance.
struct CombatTarget
Matches objects that match the combat targeting condition of the specified content.
struct Condition
The base class for all Conditions.
struct ContainedBy
Matches all objects that are contained by an object that matches Condition condition.
struct Contains
Matches all objects that contain an object that matches Condition condition.
struct CreatedOnTurn
Matches all objects that were created on turns within the specified range.
struct Described
Matches whatever its subcondition matches, but has a customized description string that is returned by Description() by looking up in the stringtable.
struct DesignHasHull
Matches all ships whose ShipDesign has the hull specified by name.
struct DesignHasPart
Matches all ships whose ShipDesign has >= low and < high of the ship part specified by name.
struct DesignHasPartClass
Matches ships whose ShipDesign has >= low and < high of ship parts of the specified part_class.
struct EmpireAffiliation
Matches all objects that are owned (if exclusive == false) or only owned (if exclusive == true) by an empire that has affilitation type affilitation with Empire empire_id.
struct EmpireHasAdoptedPolicy
Matches all objects if the empire with id empire_id has adopted the imperial policy with name name.
struct EmpireMeterValue
Matches all objects if the empire with id empire_id has an empire meter meter whose current value is >= low and <= high.
struct EmpireStockpileValue
Matches all objects whose owner's stockpile of stockpile is between low and high, inclusive.
struct Enqueued
Matches planets where the indicated number of the indicated building type or ship design are enqueued on the production queue.
struct ExploredByEmpire
Matches systems that have been explored by at least one Empire in empire_ids.
struct FleetSupplyableByEmpire
Matches objects that are in systems that can be fleet supplied by the empire with id empire_id.
struct FocusType
Matches all ProdCenter objects that have one of the FocusTypes in foci.
struct HasSpecial
Matches all objects that have an attached Special named name.
struct HasTag
Matches all objects that have the tag tag.
struct Homeworld
Matches planets that are a homeworld for any of the species specified in names.
struct InOrIsSystem
Matches all objects that are in the system with the indicated system_id or that are that system.
struct Location
Matches objects that match the location condition of the specified content.
struct MeterValue
Matches all objects that have a meter of type meter, and whose current value is >= low and <= high.
struct Monster
Matches space monsters.
struct None
Matches no objects.
struct Not
Matches all objects that do not match the Condition operand.
struct Number
Matches all objects if the number of objects that match Condition condition is is >= low and < high.
struct NumberedShipDesign
Matches ships whose design id id.
struct ObjectID
Matches the object with the id object_id.
struct OnPlanet
Matches all objects that are on the planet with the indicated planet_id or that are that planet.
struct Or
Matches all objects that match at least one Condition in operands.
struct OrderedAlternativesOf
Tests conditions in operands in order, to find the first condition that matches at least one candidate object.
struct OrderedBombarded
Matches the objects that have been targeted for bombardment by at least one object that matches m_by_object_condition.
struct OwnerHasBuildingTypeAvailable
Matches all objects whose owner who has the building type name available.
struct OwnerHasShipDesignAvailable
Matches all objects whose owner who has the ship design id available.
struct OwnerHasShipPartAvailable
Matches all objects whose owner who has the ship part name available.
struct OwnerHasTech
Matches all objects whose owner who has tech name.
struct PlanetEnvironment
Matches all Planet objects that have one of the PlanetEnvironments in environments.
struct PlanetSize
Matches all Planet objects that have one of the PlanetSizes in sizes.
struct PlanetType
Matches all Planet objects that have one of the PlanetTypes in types.
struct PredefinedShipDesign
Matches ships who ShipDesign is a predefined shipdesign with the name name.
struct ProducedByEmpire
Matches ships or buildings produced by the empire with id empire_id.
struct ResourceSupplyConnectedByEmpire
Matches objects that are in systems that are connected by resource-sharing to at least one object that meets condition using the resource-sharing network of the empire with id empire_id.
struct RootCandidate
Matches the root candidate object in a condition tree.
struct ShipPartMeterValue
Matches ships that have a ship part meter of type meter for part part whose current value is >= low and <= high.
struct SortedNumberOf
Matches a specified number of objects that match Condition condition or as many objects as match the condition if the number of objects is less than the number requested.
struct Source
Matches the source object only.
struct Species
Matches all planets or ships that have one of the species in species.
struct StarType
Matches all System objects that have one of the StarTypes in types.
struct Stationary
Matches objects that are moving.
struct Target
There is no LocalCandidate condition.
struct Turn
Matches all objects if the current game turn is >= low and < high.
struct Type
Matches all objects that are of UniverseObjectType type.
struct ValueTest
Matches all objects if the comparisons between values of ValueRefs meet the specified comparison types.
struct VisibleToEmpire
Matches all objects that are visible to the Empire with id empire_id.
struct WithinDistance
Matches all objects that are within distance units of at least one object that meets condition.
struct WithinStarlaneJumps
Matches all objects that are within jumps starlane jumps of at least one object that meets condition.
Typedefs
typedef std::vector< std::shared_ptr< const UniverseObject > > ObjectSet
Enumerations
enum ComparisonType : int {
ComparisonType::INVALID_COMPARISON = -1, ComparisonType::EQUAL, ComparisonType::GREATER_THAN, ComparisonType::GREATER_THAN_OR_EQUAL,
ComparisonType::LESS_THAN, ComparisonType::LESS_THAN_OR_EQUAL, ComparisonType::NOT_EQUAL
}
enum ContentType : int {
ContentType::CONTENT_BUILDING, ContentType::CONTENT_SPECIES, ContentType::CONTENT_SHIP_HULL, ContentType::CONTENT_SHIP_PART,
ContentType::CONTENT_SPECIAL, ContentType::CONTENT_FOCUS
}
enum SearchDomain : int { SearchDomain::NON_MATCHES, SearchDomain::MATCHES }
enum SortingMethod : int { SortingMethod::SORT_MAX, SortingMethod::SORT_MIN, SortingMethod::SORT_MODE, SortingMethod::SORT_RANDOM }
Functions
std::string ConditionDescription (const std::vector< const Condition * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Returns a single string which describes a vector of Conditions.
std::string ConditionFailedDescription (const std::vector< const Condition * > &conditions, std::shared_ptr< const UniverseObject > candidate_object=nullptr, std::shared_ptr< const UniverseObject > source_object=nullptr)
Same as ConditionDescription, but returns a string only with conditions that have not been met.
Detailed Description
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Typedef Documentation
ObjectSet
typedef std::vector< std::shared_ptr< const UniverseObject > > Condition::ObjectSet
Enumeration Type Documentation
ComparisonType
enum Condition::ComparisonType : int strong
Enumerator
INVALID_COMPARISON
EQUAL
GREATER_THAN
GREATER_THAN_OR_EQUAL
LESS_THAN
LESS_THAN_OR_EQUAL
NOT_EQUAL
ContentType
enum Condition::ContentType : int strong
Enumerator
CONTENT_BUILDING
CONTENT_SPECIES
CONTENT_SHIP_HULL
CONTENT_SHIP_PART
CONTENT_SPECIAL
CONTENT_FOCUS
SearchDomain
enum Condition::SearchDomain : int strong
Enumerator
NON_MATCHES
The Condition will only examine items in the non matches set; those that match the Condition will be inserted into the matches set.
MATCHES
The Condition will only examine items in the matches set; those that do not match the Condition will be inserted into the nonmatches set.
SortingMethod
enum Condition::SortingMethod : int strong
Enumerator
SORT_MAX
Objects with the largest sort key will be selected.
SORT_MIN
Objects with the smallest sort key will be selected.
SORT_MODE
Objects with the most common sort key will be selected.
SORT_RANDOM
Objects will be selected randomly, without consideration of property values.
Function Documentation
ConditionDescription()
FO_COMMON_API std::string Condition::Condition::ConditionDescription (const std::vector< const Condition * > & conditions, std::shared_ptr< const UniverseObject > candidate_object = nullptr, std::shared_ptr< const UniverseObject > source_object = nullptr)
Returns a single string which describes a vector of Conditions.
If multiple conditions are passed, they are treated as if they were contained by an And condition. Subconditions within an And (or nested And) are listed as lines in a list, with duplicates removed, titled something like "All of...". Subconditions within an Or (or nested Ors) are similarly listed as lines in a list, with duplicates removed, titled something like "One of...". If a candidate object is provided, the returned string will indicate which subconditions the candidate matches, and indicate if the overall combination of conditions matches the object.
References anonymous_namespace{Conditions.cpp}::ConditionDescriptionAndTest(), and UserString().
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), and anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().
ConditionFailedDescription()
FO_COMMON_API std::string Condition::Condition::ConditionFailedDescription (const std::vector< const Condition * > & conditions, std::shared_ptr< const UniverseObject > candidate_object = nullptr, std::shared_ptr< const UniverseObject > source_object = nullptr)
Same as ConditionDescription, but returns a string only with conditions that have not been met.
References anonymous_namespace{Conditions.cpp}::ConditionDescriptionAndTest(), and UserString().
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), and anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().