FreeOrion: anonymous_namespace{SystemIcon.cpp} Namespace Reference
anonymous_namespace{SystemIcon.cpp} Namespace Reference
Functions
std::string ColorNameByOwners (const std::string &name_o, std::set< int > &owner_empire_ids, const EmpireManager &empires)
Adds color tags to name_o according to the empires in owner_empire_ids.
std::string ColorTag (const std::string &content, GG::Clr color)
bool PlaySounds ()
void PlaySystemIconRolloverSound ()
Variables
constexpr unsigned int MAX_TRIES = 128
constexpr double PI = 3.1415926535
Function Documentation
ColorNameByOwners()
std::string anonymous_namespace{SystemIcon.cpp}::ColorNameByOwners (const std::string & name_o, std::set< int > & owner_empire_ids, const EmpireManager & empires)
Adds color tags to name_o according to the empires in owner_empire_ids.
References ColorTag(), EmpireManager::GetEmpire(), GetEmpire(), and ClientUI::TextColor().
Referenced by OwnerColoredSystemName::OwnerColoredSystemName().
ColorTag()
std::string anonymous_namespace{SystemIcon.cpp}::ColorTag (const std::string & content, GG::Clr color)
Referenced by ColorNameByOwners().
PlaySounds()
bool anonymous_namespace{SystemIcon.cpp}::PlaySounds ()
References OptionsDB::Get(), and GetOptionsDB().
Referenced by PlaySystemIconRolloverSound().
PlaySystemIconRolloverSound()
void anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound ()
References GetOptionsDB(), Sound::GetSound(), Sound::PlaySound(), and PlaySounds().
Referenced by SystemIcon::MouseEnter().
Variable Documentation
MAX_TRIES
constexpr unsigned int anonymous_namespace{SystemIcon.cpp}::MAX_TRIES = 128
Referenced by ValueRef::NamedRef< T >::NamedRefInitInvariants(), and SystemIcon::NthFleetButtonUpperLeft().
PI
constexpr double anonymous_namespace{SystemIcon.cpp}::PI = 3.1415926535
Referenced by BufferStoreCircleArcVertices(), BufferStorePartlyRoundedRectVertices(), and SystemIcon::NthFleetButtonUpperLeft().