FreeOrion: anonymous_namespace{ShaderProgram.cpp} Namespace Reference
anonymous_namespace{ShaderProgram.cpp} Namespace Reference
Functions
void CHECK_ERROR (const char *fn, const char *e)
void GetProgramLog (GLuint program, std::string &log)
void GetShaderLog (GLuint shader, std::string &log)
Function Documentation
CHECK_ERROR()
void anonymous_namespace{ShaderProgram.cpp}::CHECK_ERROR (const char * fn, const char * e)
References error, and ErrorLogger.
Referenced by ShaderProgram::AllValuesBound(), ShaderProgram::Bind(), ShaderProgram::BindInt(), ShaderProgram::BindInts(), GetProgramLog(), GetShaderLog(), ShaderProgram::ShaderProgram(), ShaderProgram::Use(), and ShaderProgram::~ShaderProgram().
GetProgramLog()
void anonymous_namespace{ShaderProgram.cpp}::GetProgramLog (GLuint program, std::string & log)
References CHECK_ERROR().
Referenced by ShaderProgram::AllValuesBound(), and ShaderProgram::ShaderProgram().
GetShaderLog()
void anonymous_namespace{ShaderProgram.cpp}::GetShaderLog (GLuint shader, std::string & log)
References CHECK_ERROR().
Referenced by ShaderProgram::ShaderProgram().