FreeOrion: anonymous_namespace{EmpireWrapper.cpp} Namespace Reference
anonymous_namespace{EmpireWrapper.cpp} Namespace Reference
Classes
struct PairToTupleConverter
Typedefs
typedef std::pair< float, int > FloatIntPair
typedef PairToTupleConverter< float, int > FloatIntPairConverter
typedef std::pair< int, int > IntPair
typedef std::set< int > IntSet
typedef PairToTupleConverter< int, int > myIntIntPairConverter
typedef std::map< std::pair< int, int >, int > PairIntInt_IntMap
Functions
BuildType BuildTypeFromProductionQueueElement (const ProductionQueue::Element &element)
int DesignIDFromProductionQueueElement (const ProductionQueue::Element &element)
const std::set< int > & EmpireFleetSupplyableSystemIDsP (const Empire &empire)
const SitRepEntry & GetSitRep (const Empire &empire, int index)
std::map< int, int > jumpsToSuppliedSystemP (const Empire &empire)
const std::string & NameFromProductionQueueElement (const ProductionQueue::Element &element)
std::vector< IntPair > obstructedStarlanesP (const Empire &empire)
std::map< std::set< int >, float > PlanetsWithAllocatedPP_P (const Empire &empire)
std::map< std::set< int >, float > PlanetsWithAvailablePP_P (const Empire &empire)
std::set< std::set< int > > PlanetsWithWastedPP_P (const Empire &empire)
FloatIntPair ProductionCostAndTimeP (const Empire &empire, const ProductionQueue::Element &element)
std::set< std::string > ResearchedTechNames (const Empire &empire)
const std::string & TechFromResearchQueueElement (const ResearchQueue::Element &element)
std::vector< std::string > TechRecursivePrereqs (const Tech &tech, int empire_id)
Variables
bool(Empire::* BuildableItemBuilding)(BuildType, const std::string &, int) const = &Empire::ProducibleItem
bool(Empire::* BuildableItemShip)(BuildType, int, int) const = &Empire::ProducibleItem
auto empireFleetSupplyableSystemIDsFunc = &EmpireFleetSupplyableSystemIDsP
const Meter *(Empire::* EmpireGetMeter)(const std::string &) const = &Empire::GetMeter
auto GetEmpireSitRepFunc = GetSitRep
auto InQueueFromResearchQueueElementFunc
auto jumpsToSuppliedSystemFunc = &jumpsToSuppliedSystemP
auto obstructedStarlanesFunc = &obstructedStarlanesP
auto PlanetsWithAllocatedPP_Func = &PlanetsWithAllocatedPP_P
auto PlanetsWithAvailablePP_Func = &PlanetsWithAvailablePP_P
auto PlanetsWithWastedPP_Func = &PlanetsWithWastedPP_P
auto ProductionCostAndTimeFunc = &ProductionCostAndTimeP
const ProductionQueue::Element &(ProductionQueue::* ProductionQueueOperatorSquareBrackets)(int) const = &ProductionQueue::operator[]
auto ResearchTechNamesFunc = &ResearchedTechNames
std::vector< std::string >(TechManager::* TechNamesCategory)(const std::string &) const = &TechManager::TechNames
auto TechNamesCategoryMemberFunc = TechNamesCategory
auto TechNamesMemberFunc = TechNamesVoid
std::vector< std::string >(TechManager::* TechNamesVoid)(void) const = &TechManager::TechNames
auto TechRecursivePrereqsFunc = TechRecursivePrereqs
Typedef Documentation
FloatIntPair
typedef std::pair<float, int> anonymous_namespace{EmpireWrapper.cpp}::FloatIntPair
FloatIntPairConverter
typedef PairToTupleConverter<float, int> anonymous_namespace{EmpireWrapper.cpp}::FloatIntPairConverter
IntPair
typedef std::pair<int, int> anonymous_namespace{EmpireWrapper.cpp}::IntPair
IntSet
typedef std::set<int> anonymous_namespace{EmpireWrapper.cpp}::IntSet
myIntIntPairConverter
typedef PairToTupleConverter<int, int> anonymous_namespace{EmpireWrapper.cpp}::myIntIntPairConverter
PairIntInt_IntMap
typedef std::map<std::pair<int, int>,int > anonymous_namespace{EmpireWrapper.cpp}::PairIntInt_IntMap
Function Documentation
BuildTypeFromProductionQueueElement()
BuildType anonymous_namespace{EmpireWrapper.cpp}::BuildTypeFromProductionQueueElement (const ProductionQueue::Element & element)
References ProductionQueue::ProductionItem::build_type, and ProductionQueue::Element::item.
Referenced by FreeOrionPython::WrapEmpire().
DesignIDFromProductionQueueElement()
int anonymous_namespace{EmpireWrapper.cpp}::DesignIDFromProductionQueueElement (const ProductionQueue::Element & element)
References ProductionQueue::ProductionItem::design_id, and ProductionQueue::Element::item.
Referenced by FreeOrionPython::WrapEmpire().
EmpireFleetSupplyableSystemIDsP()
const std::set<int>& anonymous_namespace{EmpireWrapper.cpp}::EmpireFleetSupplyableSystemIDsP (const Empire & empire)
References Empire::EmpireID(), SupplyManager::FleetSupplyableSystemIDs(), and GetSupplyManager().
GetSitRep()
const SitRepEntry& anonymous_namespace{EmpireWrapper.cpp}::GetSitRep (const Empire & empire, int index)
References Empire::NumSitRepEntries(), and Empire::SitRepBegin().
jumpsToSuppliedSystemP()
std::map<int, int> anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemP (const Empire & empire)
References Empire::EmpireID(), GetSupplyManager(), and Empire::KnownStarlanes().
NameFromProductionQueueElement()
const std::string& anonymous_namespace{EmpireWrapper.cpp}::NameFromProductionQueueElement (const ProductionQueue::Element & element)
References ProductionQueue::Element::item, and ProductionQueue::ProductionItem::name.
Referenced by FreeOrionPython::WrapEmpire().
obstructedStarlanesP()
std::vector<IntPair> anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesP (const Empire & empire)
References Empire::EmpireID(), GetSupplyManager(), and SupplyManager::SupplyObstructedStarlaneTraversals().
PlanetsWithAllocatedPP_P()
std::map<std::set<int>, float> anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_P (const Empire & empire)
References ObjectMap::find(), Empire::GetProductionQueue(), ProductionQueue::insert(), and Objects().
PlanetsWithAvailablePP_P()
std::map<std::set<int>, float> anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P (const Empire & empire)
References ProductionQueue::AvailablePP(), ObjectMap::find(), Empire::GetProductionQueue(), Empire::GetResourcePool(), ProductionQueue::insert(), and Objects().
PlanetsWithWastedPP_P()
std::set<std::set<int> > anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P (const Empire & empire)
References ObjectMap::find(), Empire::GetProductionQueue(), Empire::GetResourcePool(), ProductionQueue::insert(), Objects(), and ProductionQueue::ObjectsWithWastedPP().
ProductionCostAndTimeP()
FloatIntPair anonymous_namespace{EmpireWrapper.cpp}::ProductionCostAndTimeP (const Empire & empire, const ProductionQueue::Element & element)
References Empire::ProductionCostAndTime().
ResearchedTechNames()
std::set<std::string> anonymous_namespace{EmpireWrapper.cpp}::ResearchedTechNames (const Empire & empire)
References Empire::ResearchedTechs().
TechFromResearchQueueElement()
const std::string& anonymous_namespace{EmpireWrapper.cpp}::TechFromResearchQueueElement (const ResearchQueue::Element & element)
References ResearchQueue::Element::name.
TechRecursivePrereqs()
std::vector<std::string> anonymous_namespace{EmpireWrapper.cpp}::TechRecursivePrereqs (const Tech & tech, int empire_id)
References GetTechManager(), Tech::Name(), and TechManager::RecursivePrereqs().
Variable Documentation
BuildableItemBuilding
bool(Empire::* anonymous_namespace{EmpireWrapper.cpp}::BuildableItemBuilding) (BuildType, const std::string &, int) const = &Empire::ProducibleItem
Referenced by FreeOrionPython::WrapEmpire().
BuildableItemShip
bool(Empire::* anonymous_namespace{EmpireWrapper.cpp}::BuildableItemShip) (BuildType, int, int) const = &Empire::ProducibleItem
Referenced by FreeOrionPython::WrapEmpire().
empireFleetSupplyableSystemIDsFunc
auto anonymous_namespace{EmpireWrapper.cpp}::empireFleetSupplyableSystemIDsFunc = &EmpireFleetSupplyableSystemIDsP
Referenced by FreeOrionPython::WrapEmpire().
EmpireGetMeter
const Meter*(Empire::* anonymous_namespace{EmpireWrapper.cpp}::EmpireGetMeter) (const std::string &) const = &Empire::GetMeter
Referenced by FreeOrionPython::WrapEmpire().
GetEmpireSitRepFunc
auto anonymous_namespace{EmpireWrapper.cpp}::GetEmpireSitRepFunc = GetSitRep
Referenced by FreeOrionPython::WrapEmpire().
InQueueFromResearchQueueElementFunc
auto anonymous_namespace{EmpireWrapper.cpp}::InQueueFromResearchQueueElementFunc
Initial value:
=
        boost::bind(&ResearchQueue::InQueue, _1, boost::bind(TechFromResearchQueueElement, _2))
Referenced by FreeOrionPython::WrapEmpire().
jumpsToSuppliedSystemFunc
auto anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemFunc = &jumpsToSuppliedSystemP
Referenced by FreeOrionPython::WrapEmpire().
obstructedStarlanesFunc
auto anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesFunc = &obstructedStarlanesP
Referenced by FreeOrionPython::WrapEmpire().
PlanetsWithAllocatedPP_Func
auto anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_Func = &PlanetsWithAllocatedPP_P
Referenced by FreeOrionPython::WrapEmpire().
PlanetsWithAvailablePP_Func
auto anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_Func = &PlanetsWithAvailablePP_P
Referenced by FreeOrionPython::WrapEmpire().
PlanetsWithWastedPP_Func
auto anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_Func = &PlanetsWithWastedPP_P
Referenced by FreeOrionPython::WrapEmpire().
ProductionCostAndTimeFunc
auto anonymous_namespace{EmpireWrapper.cpp}::ProductionCostAndTimeFunc = &ProductionCostAndTimeP
Referenced by FreeOrionPython::WrapEmpire().
ProductionQueueOperatorSquareBrackets
const ProductionQueue::Element&(ProductionQueue::* anonymous_namespace{EmpireWrapper.cpp}::ProductionQueueOperatorSquareBrackets) (int) const = &ProductionQueue::operator[]
Referenced by FreeOrionPython::WrapEmpire().
ResearchTechNamesFunc
auto anonymous_namespace{EmpireWrapper.cpp}::ResearchTechNamesFunc = &ResearchedTechNames
Referenced by FreeOrionPython::WrapEmpire().
TechNamesCategory
std::vector<std::string>(TechManager::* anonymous_namespace{EmpireWrapper.cpp}::TechNamesCategory) (const std::string &) const = &TechManager::TechNames
TechNamesCategoryMemberFunc
auto anonymous_namespace{EmpireWrapper.cpp}::TechNamesCategoryMemberFunc = TechNamesCategory
Referenced by FreeOrionPython::WrapEmpire().
TechNamesMemberFunc
auto anonymous_namespace{EmpireWrapper.cpp}::TechNamesMemberFunc = TechNamesVoid
Referenced by FreeOrionPython::WrapEmpire().
TechNamesVoid
std::vector<std::string>(TechManager::* anonymous_namespace{EmpireWrapper.cpp}::TechNamesVoid) (void) const = &TechManager::TechNames
TechRecursivePrereqsFunc
auto anonymous_namespace{EmpireWrapper.cpp}::TechRecursivePrereqsFunc = TechRecursivePrereqs
Referenced by FreeOrionPython::WrapEmpire().