FreeOrion: details Namespace Reference
details Namespace Reference
Functions
template<class T >
T mod (T dividend, T divisor)
template<>
double mod< double > (double dividend, double divisor)
template<>
float mod< float > (float dividend, float divisor)
template<>
long double mod< long double > (long double dividend, long double divisor)
Function Documentation
mod()
template<class T > T details::mod (T dividend, T divisor) inline
Referenced by HotkeyManager::Connect(), Hotkey::HotkeyFromString(), Hotkey::HotkeyToString(), and StepValidator< T >::Validate().
mod< double >()
template<> double details::mod< double > (double dividend, double divisor) inline
mod< float >()
template<> float details::mod< float > (float dividend, float divisor) inline
mod< long double >()
template<> long double details::mod< long double > (long double dividend, long double divisor) inline