FreeOrion: anonymous_namespace{Species.cpp} Namespace Reference
anonymous_namespace{Species.cpp} Namespace Reference
Functions
std::string PlanetEnvironmentToString (PlanetEnvironment env)
std::string PlanetTypeToString (PlanetType type)
PlanetType RingNextPlanetType (PlanetType current_type)
PlanetType RingPreviousPlanetType (PlanetType current_type)
Variables
const std::string EMPTY_STRING
Function Documentation
PlanetEnvironmentToString()
std::string anonymous_namespace{Species.cpp}::PlanetEnvironmentToString (PlanetEnvironment env)
References tag_parser::description, FocusType::Dump(), Effect::Dump(), DumpIndent(), FocusType::m_description, FocusType::m_graphic, FocusType::m_location, FocusType::m_name, PlanetTypeToString(), TraceLogger, and UserString().
PlanetTypeToString()
std::string anonymous_namespace{Species.cpp}::PlanetTypeToString (PlanetType type)
Referenced by PlanetEnvironmentToString().
RingNextPlanetType()
PlanetType anonymous_namespace{Species.cpp}::RingNextPlanetType (PlanetType current_type)
Referenced by RingPreviousPlanetType().
RingPreviousPlanetType()
PlanetType anonymous_namespace{Species.cpp}::RingPreviousPlanetType (PlanetType current_type)
References CheckSums::CheckSumCombine(), DebugLogger, FocusType::m_description, FocusType::m_graphic, FocusType::m_location, FocusType::m_name, Objects(), RingNextPlanetType(), and SpeciesManager::s_instance.
Variable Documentation
EMPTY_STRING
const std::string anonymous_namespace{Species.cpp}::EMPTY_STRING
Referenced by SpeciesManager::RandomPlayableSpeciesName(), SpeciesManager::RandomSpeciesName(), and SpeciesManager::SequentialPlayableSpeciesName().