FreeOrion: SystemPathing Namespace Reference
SystemPathing Namespace Reference
Classes
class BFSVisitorImpl
Complete BFS visitor implementing:
struct PathFindingShortCircuitingVisitor
Used to short-circuit the use of BFS (breadth-first search) or Dijkstra's algorithm for pathfinding when it finds the desired destination system.
struct vertex_system_id_t
a system graph property map type
Functions
template<typename Graph >
std::multimap< double, int > ImmediateNeighborsImpl (const Graph &graph, int system_id, const boost::unordered_map< int, size_t > &id_to_graph_index)
template<typename Graph >
std::pair< std::list< int >, int > LeastJumpsPathImpl (const Graph &graph, int system1_id, int system2_id, const boost::unordered_map< int, size_t > &id_to_graph_index, int max_jumps=INT_MAX)
Returns the path between vertices system1_id and system2_id of graph that takes the fewest number of jumps (edge traversals), and the number of jumps this path takes.
template<typename Graph >
std::pair< std::list< int >, double > ShortestPathImpl (const Graph &graph, int system1_id, int system2_id, double linear_distance, const boost::unordered_map< int, size_t > &id_to_graph_index)
Returns the path between vertices system1_id and system2_id of graph that travels the shorest distance on starlanes, and the path length.
Function Documentation
ImmediateNeighborsImpl()
template<typename Graph > std::multimap<double, int> SystemPathing::ImmediateNeighborsImpl (const Graph & graph, int system_id, const boost::unordered_map< int, size_t > & id_to_graph_index)
References boost::get().
Referenced by Pathfinder::PathfinderImpl::ImmediateNeighbors().
LeastJumpsPathImpl()
template<typename Graph > std::pair<std::list<int>, int> SystemPathing::LeastJumpsPathImpl (const Graph & graph, int system1_id, int system2_id, const boost::unordered_map< int, size_t > & id_to_graph_index, int max_jumps = INT_MAX)
Returns the path between vertices system1_id and system2_id of graph that takes the fewest number of jumps (edge traversals), and the number of jumps this path takes.
If system1_id is the same vertex as system2_id, the path has just that system in it, and the path lenth is 0. If there is no path between the two vertices, then the list is empty and the path length is -1
References boost::get().
Referenced by Pathfinder::PathfinderImpl::LeastJumpsPath().
ShortestPathImpl()
template<typename Graph > std::pair<std::list<int>, double> SystemPathing::ShortestPathImpl (const Graph & graph, int system1_id, int system2_id, double linear_distance, const boost::unordered_map< int, size_t > & id_to_graph_index)
Returns the path between vertices system1_id and system2_id of graph that travels the shorest distance on starlanes, and the path length.
If system1_id is the same vertex as system2_id, the path has just that system in it, and the path lenth is 0. If there is no path between the two vertices, then the list is empty and the path length is -1.0
References boost::get().
Referenced by Pathfinder::PathfinderImpl::ShortestPath().