FreeOrion: anonymous_namespace{Effects.cpp} Namespace Reference
anonymous_namespace{Effects.cpp} Namespace Reference
Functions
std::shared_ptr< Fleet > CreateNewFleet (double x, double y, std::shared_ptr< Ship > ship, Universe &universe, FleetAggression aggression=FleetAggression::INVALID_FLEET_AGGRESSION)
creates a new fleet at a specified x and y location within the Universe, and and inserts ship into it.
std::shared_ptr< Fleet > CreateNewFleet (std::shared_ptr< System > system, std::shared_ptr< Ship > ship, Universe &universe, FleetAggression aggression=FleetAggression::INVALID_FLEET_AGGRESSION)
Creates a new fleet at system and inserts ship into it.
DeclareThreadSafeLogger (effects)
void ExploreSystem (int system_id, const std::shared_ptr< const UniverseObject > &target_object, ScriptingContext &context)
Explores the system with the specified system_id for the owner of the specified target_object.
std::string GenerateSystemName (const ObjectMap &objects)
void UpdateFleetRoute (const std::shared_ptr< Fleet > &fleet, int new_next_system, int new_previous_system, const ScriptingContext &context)
Resets the previous and next systems of fleet and recalcultes / resets the fleet's move route.
Function Documentation
CreateNewFleet() [1/2]
std::shared_ptr<Fleet> anonymous_namespace{Effects.cpp}::CreateNewFleet (double x, double y, std::shared_ptr< Ship > ship, Universe & universe, FleetAggression aggression = FleetAggression::INVALID_FLEET_AGGRESSION)
creates a new fleet at a specified x and y location within the Universe, and and inserts ship into it.
Used when a ship has been moved by the MoveTo effect separately from the fleet that previously held it. All ships need to be within fleets.
References Fleet::AddShips(), Universe::InsertNew(), Meter::LARGE_VALUE, and Objects().
CreateNewFleet() [2/2]
std::shared_ptr<Fleet> anonymous_namespace{Effects.cpp}::CreateNewFleet (std::shared_ptr< System > system, std::shared_ptr< Ship > ship, Universe & universe, FleetAggression aggression = FleetAggression::INVALID_FLEET_AGGRESSION)
Creates a new fleet at system and inserts ship into it.
Used when a ship has been moved by the MoveTo effect separately from the fleet that previously held it. Also used by CreateShip effect to give the new ship a fleet. All ships need to be within fleets.
References ObjectMap::get(), INVALID_OBJECT_ID, and Universe::Objects().
Referenced by Effect::SetOwner::Execute(), Effect::CreateShip::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), and Effect::MoveTowards::Execute().
DeclareThreadSafeLogger()
anonymous_namespace{Effects.cpp}::DeclareThreadSafeLogger (effects)
ExploreSystem()
void anonymous_namespace{Effects.cpp}::ExploreSystem (int system_id, const std::shared_ptr< const UniverseObject > & target_object, ScriptingContext & context)
Explores the system with the specified system_id for the owner of the specified target_object.
Used when moving objects into a system with the MoveTo effect, as otherwise the system wouldn't get explored, and objects being moved into unexplored systems might disappear for players or confuse the AI.
References ScriptingContext::GetEmpire().
Referenced by Effect::MoveTo::Execute().
GenerateSystemName()
std::string anonymous_namespace{Effects.cpp}::GenerateSystemName (const ObjectMap & objects)
References ObjectMap::all(), CheckSums::CheckSumCombine(), tag_parser::description, Effect::Dump(), DumpIndent(), operator==(), RandInt(), ObjectMap::size(), ScriptingContext::source, to_string(), TraceLogger, UserString(), UserStringList(), and WarnLogger.
Referenced by Effect::CreateSystem::Execute().
UpdateFleetRoute()
void anonymous_namespace{Effects.cpp}::UpdateFleetRoute (const std::shared_ptr< Fleet > & fleet, int new_next_system, int new_previous_system, const ScriptingContext & context)
Resets the previous and next systems of fleet and recalcultes / resets the fleet's move route.
Used after a fleet has been moved with the MoveTo effect, as its previous route was assigned based on its previous location, and may not be valid for its new location.
References ScriptingContext::ContextObjects(), ScriptingContext::ContextUniverse(), ErrorLogger, ObjectMap::get(), Universe::GetPathfinder(), and INVALID_OBJECT_ID.
Referenced by Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), and Effect::MoveTowards::Execute().