FreeOrion: anonymous_namespace{IconTextBrowseWnd.cpp} Namespace Reference
anonymous_namespace{IconTextBrowseWnd.cpp} Namespace Reference
Functions
int IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
Variables
constexpr int EDGE_PAD = 3
constexpr GG::Y ICON_BROWSE_ICON_HEIGHT {64}
constexpr GG::X ICON_BROWSE_ICON_WIDTH {64}
constexpr GG::X ICON_BROWSE_TEXT_WIDTH {400}
Function Documentation
IconTextBrowseWndRowHeight()
int anonymous_namespace{IconTextBrowseWnd.cpp}::IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
References ClientUI::Pts().
Referenced by IconTextBrowseWnd::PreRender(), and IconTextBrowseWnd::Render().
Variable Documentation
EDGE_PAD
constexpr int anonymous_namespace{IconTextBrowseWnd.cpp}::EDGE_PAD = 3
Referenced by IconTextBrowseWnd::PreRender().
ICON_BROWSE_ICON_HEIGHT
constexpr GG::Y anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT {64}
Referenced by IconTextBrowseWnd::PreRender().
ICON_BROWSE_ICON_WIDTH
constexpr GG::X anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_ICON_WIDTH {64}
Referenced by IconTextBrowseWnd::PreRender(), and IconTextBrowseWnd::Render().
ICON_BROWSE_TEXT_WIDTH
constexpr GG::X anonymous_namespace{IconTextBrowseWnd.cpp}::ICON_BROWSE_TEXT_WIDTH {400}
Referenced by IconTextBrowseWnd::PreRender().