FreeOrion: anonymous_namespace{ModeratorActionsWnd.cpp} Namespace Reference
anonymous_namespace{ModeratorActionsWnd.cpp} Namespace Reference
Functions
const GG::Y CONTROL_HEIGHT (32)
const GG::X CONTROL_WIDTH (32)
const GG::X DROP_WIDTH (96)
const int PAD (3)
Function Documentation
CONTROL_HEIGHT()
const GG::Y anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_HEIGHT (32)
Referenced by ModeratorActionsWnd::CompleteConstruction(), and ModeratorActionsWnd::DoLayout().
CONTROL_WIDTH()
const GG::X anonymous_namespace{ModeratorActionsWnd.cpp}::CONTROL_WIDTH (32)
Referenced by ModeratorActionsWnd::CompleteConstruction(), and ModeratorActionsWnd::DoLayout().
DROP_WIDTH()
const GG::X anonymous_namespace{ModeratorActionsWnd.cpp}::DROP_WIDTH (96)
Referenced by ModeratorActionsWnd::CompleteConstruction(), and ModeratorActionsWnd::DoLayout().
PAD()
const int anonymous_namespace{ModeratorActionsWnd.cpp}::PAD (3)
Referenced by ModeratorActionsWnd::DoLayout().