FreeOrion: anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp} Namespace Reference
anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
GG::X LabelWidth ()
double ObjectResourceConsumption (std::shared_ptr< const UniverseObject > obj, ResourceType resource_type, int empire_id=ALL_EMPIRES)
Returns how much of specified resource_type is being consumed by the empire with id empire_id at the location of the specified object obj.
GG::X ValueWidth ()
Function Documentation
EDGE_PAD()
const int anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::EDGE_PAD (3)
Referenced by SystemResourceSummaryBrowseWnd::Initialize(), and ObjectResourceConsumption().
LabelWidth()
GG::X anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::LabelWidth ()
References ClientUI::Pts().
Referenced by SystemResourceSummaryBrowseWnd::Initialize(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), and SystemResourceSummaryBrowseWnd::UpdateProduction().
ObjectResourceConsumption()
double anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption (std::shared_ptr< const UniverseObject > obj, ResourceType resource_type, int empire_id = ALL_EMPIRES)
Returns how much of specified resource_type is being consumed by the empire with id empire_id at the location of the specified object obj.
References ALL_EMPIRES, DebugLogger, EDGE_PAD(), Empires(), ErrorLogger, GetEmpire(), and Empire::GetProductionQueue().
Referenced by SystemResourceSummaryBrowseWnd::UpdateAllocation().
ValueWidth()
GG::X anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ValueWidth ()
References ClientUI::Pts().
Referenced by SystemResourceSummaryBrowseWnd::Initialize(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), and SystemResourceSummaryBrowseWnd::UpdateProduction().