FreeOrion: anonymous_namespace{SidePanel.cpp} Namespace Reference
anonymous_namespace{SidePanel.cpp} Namespace Reference
Classes
struct PlanetAtmosphereData
struct RotatingPlanetData
class SystemMeterBrowseWnd
class SystemRow
Functions
void AddOptions (OptionsDB &db)
Adds options related to sidepanel to Options DB.
bool AvailableToBombard (const Ship *ship, int system_id, int empire_id)
bool AvailableToColonize (const Ship *ship, int system_id, int empire_id)
bool AvailableToInvade (const Ship *ship, int system_id, int empire_id)
std::vector< std::string > BombardTagsForShip (const Ship *ship)
Content tags that note if a Ship should be auto-selected for bombarding a Planet.
void CancelColonizeInvadeBombardScrapShipOrders (const Ship *ship)
bool CanColonizePlanetType (const Ship *ship, PlanetType planet_type)
bool ClientPlayerIsModerator ()
const int EDGE_PAD (3)
double GetAsteroidsFPS ()
const std::vector< std::shared_ptr< GG::Texture > > & GetAsteroidTextures ()
GLfloat * GetLightPosition ()
const std::map< std::string, PlanetAtmosphereData > & GetPlanetAtmosphereData ()
const std::string & GetPlanetEnvironmentName (const Planet *planet, const std::string &species_name)
const std::string & GetPlanetSizeName (const Planet *planet)
const std::string & GetPlanetTypeName (const Planet *planet)
double GetRotatingPlanetAmbientIntensity ()
const std::map< PlanetType, std::vector< RotatingPlanetData > > & GetRotatingPlanetData ()
double GetRotatingPlanetDiffuseIntensity ()
const std::map< StarType, std::vector< float > > & GetStarLightColors ()
const std::string & GetStarTypeName (const System *system)
bool IsAvailable (const Ship *ship, int system_id, int empire_id)
GG::X LabelWidth ()
int MaxPlanetDiameter ()
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
std::map< int, std::set< int > > PendingBombardOrders ()
Returns map from planet ID to issued bombard orders affecting it.
std::map< int, int > PendingColonizationOrders ()
Returns map from planet ID to issued colonize orders affecting it.
std::map< int, std::set< int > > PendingInvadeOrders ()
Returns map from planet ID to issued invasion orders affecting it.
int PlanetDiameter (PlanetSize size)
void PlaySidePanelOpenSound ()
void RenderPlanet (const GG::Pt &center, int diameter, std::shared_ptr< GG::Texture > texture, std::shared_ptr< GG::Texture > overlay_texture, double initial_rotation, double RPM, double axial_tilt, double shininess, StarType star_type)
void RenderSphere (double radius, const GG::Clr &ambient, const GG::Clr &diffuse, const GG::Clr &spec, double shine, std::shared_ptr< GG::Texture > texture)
GG::Y RowHeight ()
const std::vector< float > & StarLightColour (StarType star_type)
int SystemNameFontSize ()
std::set< const Ship * > ValidSelectedBombardShips (int system_id)
std::set< const Ship * > ValidSelectedInvasionShips (int system_id)
GG::X ValueWidth ()
Variables
std::map< std::pair< int, int >, float > colony_projections
const std::string EMPTY_STRING
const GG::Y PLANET_PANEL_TOP = GG::Y(140)
static const bool SHOW_ALL_PLANET_PANELS = false
toggles whether to show population, resource, military and building info panels on planet panels that this player doesn't control
std::map< std::pair< std::string, int >, float > species_colony_projections
const std::string TAG_BOMBARD_ALWAYS = "CTRL_ALWAYS_BOMBARD"
const std::string TAG_BOMBARD_PREFIX = "CTRL_BOMBARD_"
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{SidePanel.cpp}::AddOptions (OptionsDB & db)
Adds options related to sidepanel to Options DB.
References OptionsDB::Add(), and UserStringNop.
AvailableToBombard()
bool anonymous_namespace{SidePanel.cpp}::AvailableToBombard (const Ship * ship, int system_id, int empire_id)
References Ship::CanBombard(), Ship::FleetID(), INVALID_OBJECT_ID, IsAvailable(), Objects(), and Ship::OrderedBombardPlanet().
Referenced by AutomaticallyChosenBombardShips().
AvailableToColonize()
bool anonymous_namespace{SidePanel.cpp}::AvailableToColonize (const Ship * ship, int system_id, int empire_id)
References Ship::CanColonize(), Ship::FleetID(), INVALID_OBJECT_ID, IsAvailable(), Objects(), and Ship::OrderedColonizePlanet().
Referenced by AutomaticallyChosenColonyShip().
AvailableToInvade()
bool anonymous_namespace{SidePanel.cpp}::AvailableToInvade (const Ship * ship, int system_id, int empire_id)
References Ship::FleetID(), Ship::HasTroops(), INVALID_OBJECT_ID, IsAvailable(), Objects(), and Ship::OrderedInvadePlanet().
Referenced by AutomaticallyChosenInvasionShips().
BombardTagsForShip()
std::vector<std::string> anonymous_namespace{SidePanel.cpp}::BombardTagsForShip (const Ship * ship)
Content tags that note if a Ship should be auto-selected for bombarding a Planet.
These tags are determined from the TAG_BOMBARD_PREFIX tags of ship and potentially match those of a Planet. For example, a planet might have a "ROBOTIC" tag because its species does, and if the ship has the corresponding "CTRL_BOMBARD_ROBOTIC" tag, the ship would be auto-selected to bombard that planet. If the Ship contains the content tag defined in TAG_BOMBARD_ALWAYS, only that tag will be returned.
References TAG_BOMBARD_ALWAYS, TAG_BOMBARD_PREFIX, and Ship::Tags().
Referenced by AutomaticallyChosenBombardShips().
CancelColonizeInvadeBombardScrapShipOrders()
void anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders (const Ship * ship)
References HumanClientApp::GetApp(), ClientApp::GetApp(), INVALID_OBJECT_ID, Ship::OrderedBombardPlanet(), Ship::OrderedColonizePlanet(), Ship::OrderedInvadePlanet(), Ship::OrderedScrapped(), ClientApp::Orders(), and OrderSet::RescindOrder().
Referenced by SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), and SidePanel::PlanetPanel::ClickInvade().
CanColonizePlanetType()
bool anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType (const Ship * ship, PlanetType planet_type)
References Ship::CanColonize(), ShipDesign::ColonyCapacity(), Ship::Design(), GetSpecies(), and Ship::SpeciesName().
Referenced by AutomaticallyChosenColonyShip().
ClientPlayerIsModerator()
bool anonymous_namespace{SidePanel.cpp}::ClientPlayerIsModerator ()
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, HumanClientApp::GetApp(), and ClientApp::GetClientType().
Referenced by SidePanel::PlanetPanel::RClick().
EDGE_PAD()
const int anonymous_namespace{SidePanel.cpp}::EDGE_PAD (3)
Referenced by SidePanel::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), SidePanel::DoLayout(), SidePanel::PlanetPanel::DoLayout(), SidePanel::PlanetPanelContainer::DoPanelsLayout(), PlanetDiameter(), SidePanel::PlanetPanel::Refresh(), SidePanel::PlanetPanel::Render(), and SidePanel::PlanetPanelContainer::ResizePanelsForVScroll().
GetAsteroidsFPS()
double anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLElement::ContainsChild(), XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Text().
Referenced by SidePanel::PlanetPanel::RefreshPlanetGraphic().
GetAsteroidTextures()
const std::vector<std::shared_ptr<GG::Texture> >& anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures ()
References ClientUI::ArtDir(), ClientUI::GetClientUI(), and ClientUI::GetPrefixedTextures().
Referenced by SidePanel::PlanetPanel::RefreshPlanetGraphic().
GetLightPosition()
GLfloat* anonymous_namespace{SidePanel.cpp}::GetLightPosition ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Text().
Referenced by RenderPlanet().
GetPlanetAtmosphereData()
const std::map<std::string, PlanetAtmosphereData>& anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData ()
References ClientUI::ArtDir(), XMLElement::children, ErrorLogger, anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::planet_filename, XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Tag().
Referenced by RotatingPlanetControl::Refresh().
GetPlanetEnvironmentName()
const std::string& anonymous_namespace{SidePanel.cpp}::GetPlanetEnvironmentName (const Planet * planet, const std::string & species_name)
References UserString().
Referenced by SidePanel::PlanetPanel::Refresh().
GetPlanetSizeName()
const std::string& anonymous_namespace{SidePanel.cpp}::GetPlanetSizeName (const Planet * planet)
References UserString().
Referenced by SidePanel::PlanetPanel::Refresh().
GetPlanetTypeName()
const std::string& anonymous_namespace{SidePanel.cpp}::GetPlanetTypeName (const Planet * planet)
References UserString().
Referenced by SidePanel::PlanetPanel::Refresh().
GetRotatingPlanetAmbientIntensity()
double anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLElement::ContainsChild(), XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Text().
Referenced by RenderPlanet().
GetRotatingPlanetData()
const std::map<PlanetType, std::vector<RotatingPlanetData> >& anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLElement::children, XMLElement::ContainsChild(), ErrorLogger, anonymous_namespace{SidePanel.cpp}::RotatingPlanetData::planet_type, XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Tag().
Referenced by RotatingPlanetControl::Refresh().
GetRotatingPlanetDiffuseIntensity()
double anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLElement::ContainsChild(), XMLDoc::ReadDoc(), XMLDoc::root_node, and XMLElement::Text().
Referenced by RenderPlanet().
GetStarLightColors()
const std::map<StarType, std::vector<float> >& anonymous_namespace{SidePanel.cpp}::GetStarLightColors ()
References ClientUI::ArtDir(), XMLElement::Child(), XMLElement::children, XMLElement::ContainsChild(), HexClr(), XMLDoc::ReadDoc(), and XMLDoc::root_node.
Referenced by StarLightColour().
GetStarTypeName()
const std::string& anonymous_namespace{SidePanel.cpp}::GetStarTypeName (const System * system)
References UserString().
Referenced by SidePanel::RefreshImpl().
IsAvailable()
bool anonymous_namespace{SidePanel.cpp}::IsAvailable (const Ship * ship, int system_id, int empire_id)
References Ship::FleetID(), ObjectMap::get(), INVALID_OBJECT_ID, Objects(), and Ship::OrderedScrapped().
Referenced by AvailableToBombard(), AvailableToColonize(), and AvailableToInvade().
LabelWidth()
GG::X anonymous_namespace{SidePanel.cpp}::LabelWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl().
MaxPlanetDiameter()
int anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter ()
References OptionsDB::Get(), and GetOptionsDB().
Referenced by SidePanel::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), SidePanel::DoLayout(), SidePanel::PlanetPanel::DoLayout(), SidePanel::PlanetPanelContainer::DoPanelsLayout(), SidePanel::InitBuffers(), SidePanel::InWindow(), SidePanel::PlanetPanel::InWindow(), SidePanel::PlanetPanelContainer::InWindow(), PlanetDiameter(), SidePanel::PlanetPanel::Refresh(), SidePanel::RefreshImpl(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), and SidePanel::PlanetPanel::Render().
MeterIconSize()
GG::Pt anonymous_namespace{SidePanel.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by SidePanel::PlanetPanel::DoLayout(), and SidePanel::PlanetPanel::Refresh().
PendingBombardOrders()
std::map<int, std::set<int> > anonymous_namespace{SidePanel.cpp}::PendingBombardOrders ()
Returns map from planet ID to issued bombard orders affecting it.
There may be multiple ships bombarding a single planet.
References ClientApp::GetApp(), and ClientApp::Orders().
Referenced by SidePanel::PlanetPanel::ClickBombard().
PendingColonizationOrders()
std::map<int, int> anonymous_namespace{SidePanel.cpp}::PendingColonizationOrders ()
Returns map from planet ID to issued colonize orders affecting it.
There should be only one ship colonzing each planet for this client.
References ClientApp::GetApp(), and ClientApp::Orders().
Referenced by SidePanel::PlanetPanel::ClickColonize().
PendingInvadeOrders()
std::map<int, std::set<int> > anonymous_namespace{SidePanel.cpp}::PendingInvadeOrders ()
Returns map from planet ID to issued invasion orders affecting it.
There may be multiple ships invading a single planet.
References ClientApp::GetApp(), and ClientApp::Orders().
Referenced by SidePanel::PlanetPanel::ClickInvade().
PlanetDiameter()
int anonymous_namespace{SidePanel.cpp}::PlanetDiameter (PlanetSize size)
References tag_parser::default, EDGE_PAD(), OptionsDB::Get(), GetOptionsDB(), and MaxPlanetDiameter().
Referenced by RotatingPlanetControl::Refresh(), and SidePanel::PlanetPanel::RefreshPlanetGraphic().
PlaySidePanelOpenSound()
void anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by SidePanel::SetSystem().
RenderPlanet()
void anonymous_namespace{SidePanel.cpp}::RenderPlanet (const GG::Pt & center, int diameter, std::shared_ptr< GG::Texture > texture, std::shared_ptr< GG::Texture > overlay_texture, double initial_rotation, double RPM, double axial_tilt, double shininess, StarType star_type)
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{MapWnd.cpp}::AppWidth(), SDLGUI::Enter2DMode(), SDLGUI::Exit2DMode(), HumanClientApp::GetApp(), GetLightPosition(), GetRotatingPlanetAmbientIntensity(), GetRotatingPlanetDiffuseIntensity(), RenderSphere(), and StarLightColour().
Referenced by RotatingPlanetControl::Render().
RenderSphere()
void anonymous_namespace{SidePanel.cpp}::RenderSphere (double radius, const GG::Clr & ambient, const GG::Clr & diffuse, const GG::Clr & spec, double shine, std::shared_ptr< GG::Texture > texture)
Referenced by RenderPlanet().
RowHeight()
GG::Y anonymous_namespace{SidePanel.cpp}::RowHeight ()
References ClientUI::Pts().
Referenced by anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::Render(), and anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl().
StarLightColour()
const std::vector<float>& anonymous_namespace{SidePanel.cpp}::StarLightColour (StarType star_type)
References GetStarLightColors().
Referenced by RenderPlanet().
SystemNameFontSize()
int anonymous_namespace{SidePanel.cpp}::SystemNameFontSize ()
References ClientUI::Pts().
Referenced by anonymous_namespace{SidePanel.cpp}::SystemRow::Init(), and SidePanel::RefreshSystemNames().
ValidSelectedBombardShips()
std::set<const Ship*> anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips (int system_id)
References HumanClientApp::GetApp(), FleetUIManager::GetFleetUIManager(), INVALID_OBJECT_ID, and Objects().
Referenced by SidePanel::PlanetPanel::ClickBombard(), and SidePanel::PlanetPanel::Refresh().
ValidSelectedInvasionShips()
std::set<const Ship*> anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips (int system_id)
References HumanClientApp::GetApp(), FleetUIManager::GetFleetUIManager(), GetUniverse(), INVALID_OBJECT_ID, and Objects().
Referenced by SidePanel::PlanetPanel::ClickInvade(), and SidePanel::PlanetPanel::Refresh().
ValueWidth()
GG::X anonymous_namespace{SidePanel.cpp}::ValueWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl().
Variable Documentation
colony_projections
std::map<std::pair<int,int>,float> anonymous_namespace{SidePanel.cpp}::colony_projections
Referenced by AutomaticallyChosenColonyShip(), SidePanel::PlanetPanel::Refresh(), SidePanel::RefreshInPreRender(), and SidePanel::PlanetPanel::SetFocus().
EMPTY_STRING
const std::string anonymous_namespace{SidePanel.cpp}::EMPTY_STRING
PLANET_PANEL_TOP
const GG::Y anonymous_namespace{SidePanel.cpp}::PLANET_PANEL_TOP = GG::Y(140)
Referenced by SidePanel::CompleteConstruction(), SidePanel::DoLayout(), and SidePanel::InitBuffers().
SHOW_ALL_PLANET_PANELS
const bool anonymous_namespace{SidePanel.cpp}::SHOW_ALL_PLANET_PANELS = false static
toggles whether to show population, resource, military and building info panels on planet panels that this player doesn't control
Referenced by SidePanel::PlanetPanel::Refresh().
species_colony_projections
std::map<std::pair<std::string,int>,float> anonymous_namespace{SidePanel.cpp}::species_colony_projections
Referenced by AutomaticallyChosenColonyShip(), SidePanel::RefreshInPreRender(), and SidePanel::PlanetPanel::SetFocus().
TAG_BOMBARD_ALWAYS
const std::string anonymous_namespace{SidePanel.cpp}::TAG_BOMBARD_ALWAYS = "CTRL_ALWAYS_BOMBARD"
CTRL_ALWAYS_BOMBARD Select this ship during automatic ship selection for bombard, regardless of any tags
Referenced by AutomaticallyChosenBombardShips(), and BombardTagsForShip().
TAG_BOMBARD_PREFIX
const std::string anonymous_namespace{SidePanel.cpp}::TAG_BOMBARD_PREFIX = "CTRL_BOMBARD_"
CTRL_BOMBARD_ Prefix tag allowing automatic ship selection for bombard, must post-fix a valid planet tag
Referenced by BombardTagsForShip().
temp_bool
bool anonymous_namespace{SidePanel.cpp}::temp_bool = RegisterOptions(&AddOptions)