FreeOrion: anonymous_namespace{GodotClientApp.cpp} Namespace Reference
anonymous_namespace{GodotClientApp.cpp} Namespace Reference
Classes
class LocalServerAlreadyRunningException
Functions
void AddOptions (OptionsDB &db)
void ClearPreviousPendingSaves (std::queue< std::string > &pending_saves)
void SetEmptyStringDefaultOption (const std::string &option_name, const std::string &option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
void SetStringtableDependentOptionDefaults ()
Variables
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{GodotClientApp.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
ClearPreviousPendingSaves()
void anonymous_namespace{GodotClientApp.cpp}::ClearPreviousPendingSaves (std::queue< std::string > & pending_saves)
References swap(), to_string(), and WarnLogger.
Referenced by GodotClientApp::NewSinglePlayerGame().
SetEmptyStringDefaultOption()
void anonymous_namespace{GodotClientApp.cpp}::SetEmptyStringDefaultOption (const std::string & option_name, const std::string & option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
References OptionsDB::Get(), GetOptionsDB(), OptionsDB::Set(), and OptionsDB::SetDefault().
Referenced by SetStringtableDependentOptionDefaults().
SetStringtableDependentOptionDefaults()
void anonymous_namespace{GodotClientApp.cpp}::SetStringtableDependentOptionDefaults ()
References SetEmptyStringDefaultOption(), and UserString().
Referenced by GodotClientApp::GodotClientApp().
Variable Documentation
temp_bool
bool anonymous_namespace{GodotClientApp.cpp}::temp_bool = RegisterOptions(&AddOptions)