FreeOrion: anonymous_namespace{ModeratorAction.cpp} Namespace Reference
anonymous_namespace{ModeratorAction.cpp} Namespace Reference
Functions
std::string GenerateSystemName ()
Function Documentation
GenerateSystemName()
std::string anonymous_namespace{ModeratorAction.cpp}::GenerateSystemName ()
References ObjectMap::all(), Objects(), and UserStringList().
Referenced by Moderator::CreateSystem::Execute().