FreeOrion: NamedValueRefManager.cpp File Reference
NamedValueRefManager.cpp File Reference
#include "NamedValueRefManager.h"
#include "ValueRefs.h"
#include <functional>
#include <iomanip>
#include <iterator>
#include <mutex>
#include <unordered_map>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
#include "Enums.h"
#include "Field.h"
#include "Fighter.h"
#include "Fleet.h"
#include "Pathfinder.h"
#include "Planet.h"
#include "ShipDesign.h"
#include "ShipHull.h"
#include "ShipPart.h"
#include "Ship.h"
#include "Species.h"
#include "System.h"
#include "Tech.h"
#include "UniverseObjectVisitors.h"
#include "UniverseObject.h"
#include "Universe.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../Empire/Supply.h"
#include "../util/GameRules.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/Random.h"
Namespaces
anonymous_namespace{NamedValueRefManager.cpp}
ValueRef
Functions
NamedValueRefManager & GetNamedValueRefManager ()
Returns the singleton manager for named value refs.
template<typename T >
ValueRef::ValueRef< T > *const GetValueRef (const std::string &name)
Returns the ValueRef object registered with the given name in the registry matching the given type T.
ValueRef::ValueRefBase *const GetValueRefBase (const std::string &name)
Returns the ValueRef object registered with the given name.
template<typename V >
V *const anonymous_namespace{NamedValueRefManager.cpp}::GetValueRefImpl (std::map< NamedValueRefManager::key_type, std::unique_ptr< V >> &registry, const std::string &label, const std::string &name)
template<typename T >
void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< T >> &&vref)
Register and take possesion of the ValueRef object vref under the given name.
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< int >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< double >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetEnvironment >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetSize >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetType >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< StarType >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< UniverseObjectType >> &&vref)
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< Visibility >> &&vref)
template<typename R , typename VR >
void anonymous_namespace{NamedValueRefManager.cpp}::RegisterValueRefImpl (R &container, std::mutex &mutex, const std::string &label, std::string &&valueref_name, std::unique_ptr< VR > &&vref)
helper function for NamedValueRefManager::RegisterValueRef
Function Documentation
GetNamedValueRefManager()
NamedValueRefManager& GetNamedValueRefManager ()
Returns the singleton manager for named value refs.
References NamedValueRefManager::GetNamedValueRefManager().
Referenced by CheckSumContent(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires().
GetValueRef()
template<typename T > template ValueRef::ValueRef< double > *const GetValueRef (const std::string & name) -> ValueRef::ValueRef< T > *const
Returns the ValueRef object registered with the given name in the registry matching the given type T.
If no such ValueRef exists, nullptr is returned instead.
References NamedValueRefManager::GetNamedValueRefManager(), and NamedValueRefManager::GetValueRef().
GetValueRefBase()
ValueRef::ValueRefBase* const GetValueRefBase (const std::string & name) -> ValueRef::ValueRefBase *const
Returns the ValueRef object registered with the given name.
If no such ValueRef exists, nullptr is returned instead.
References DebugLogger, NamedValueRefManager::GetNamedValueRefManager(), NamedValueRefManager::GetValueRefBase(), and InfoLogger.
Referenced by anonymous_namespace{VarText.cpp}::SubstitutionMap(), and anonymous_namespace{LinkText.cpp}::ValueRefLinkText().
RegisterValueRef() [1/9]
template<typename T > void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< T >> && vref)
Register and take possesion of the ValueRef object vref under the given name.
References NamedValueRefManager::GetNamedValueRefManager(), NamedValueRefManager::GetValueRef(), and NamedValueRefManager::RegisterValueRef().
RegisterValueRef() [2/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< int >> && vref)
RegisterValueRef() [3/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< double >> && vref)
RegisterValueRef() [4/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetEnvironment >> && vref)
RegisterValueRef() [5/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetSize >> && vref)
RegisterValueRef() [6/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< PlanetType >> && vref)
RegisterValueRef() [7/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< StarType >> && vref)
RegisterValueRef() [8/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< UniverseObjectType >> && vref)
RegisterValueRef() [9/9]
template void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< Visibility >> && vref)