FreeOrion: anonymous_namespace{GGHumanClientApp.cpp} Namespace Reference
anonymous_namespace{GGHumanClientApp.cpp} Namespace Reference
Classes
class LocalServerAlreadyRunningException
Functions
void AddOptions (OptionsDB &db)
void ClearPreviousPendingSaves (std::queue< std::string > &pending_saves)
boost::filesystem::path CreateNewAutosaveFilePath (int client_empire_id, bool is_single_player)
float GetGLVersion ()
std::string GetGLVersionString ()
boost::optional< std::string > NewestSinglePlayerSavegame ()
void RemoveOldestFiles (int files_limit, boost::filesystem::path &p)
void SetEmptyStringDefaultOption (const std::string &option_name, const std::string &option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
void SetGLVersionDependentOptionDefaults ()
void SetStringtableDependentOptionDefaults ()
Variables
constexpr int DEFAULT_HEIGHT = 768
constexpr int DEFAULT_LEFT = static_cast<int>(SDL_WINDOWPOS_CENTERED)
constexpr int DEFAULT_TOP = 50
constexpr int DEFAULT_WIDTH = 1024
These options can only be validated after the graphics system (SDL) is initialized, so that display size can be detected.
constexpr bool INSTRUMENT_MESSAGE_HANDLING = false
constexpr int MIN_HEIGHT = 600
constexpr int MIN_WIDTH = 800
static float stored_gl_version = -1.0f
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{GGHumanClientApp.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), Hotkey::AddHotkey(), and UserStringNop.
ClearPreviousPendingSaves()
void anonymous_namespace{GGHumanClientApp.cpp}::ClearPreviousPendingSaves (std::queue< std::string > & pending_saves)
References swap(), to_string(), and WarnLogger.
Referenced by GGHumanClientApp::MultiPlayerGame(), GGHumanClientApp::NewSinglePlayerGame(), and GGHumanClientApp::ResetClientData().
CreateNewAutosaveFilePath()
boost::filesystem::path anonymous_namespace{GGHumanClientApp.cpp}::CreateNewAutosaveFilePath (int client_empire_id, bool is_single_player)
References ClientApp::CurrentTurn(), ErrorLogger, FilenameTimestamp(), ClientApp::GetEmpire(), GetSaveDir(), GetServerSaveDir(), MP_SAVE_FILE_EXTENSION, SP_SAVE_FILE_EXTENSION, and UserString().
Referenced by GGHumanClientApp::Autosave().
GetGLVersion()
float anonymous_namespace{GGHumanClientApp.cpp}::GetGLVersion ()
References GetGLVersionString(), and stored_gl_version.
Referenced by GGHumanClientApp::GGHumanClientApp(), GGHumanClientApp::GLVersion(), and SetGLVersionDependentOptionDefaults().
GetGLVersionString()
std::string anonymous_namespace{GGHumanClientApp.cpp}::GetGLVersionString ()
Referenced by GetGLVersion(), and GGHumanClientApp::GGHumanClientApp().
NewestSinglePlayerSavegame()
boost::optional<std::string> anonymous_namespace{GGHumanClientApp.cpp}::NewestSinglePlayerSavegame ()
References ErrorLogger, GetSaveDir(), PathToString(), SaveFileWithValidHeader(), and SP_SAVE_FILE_EXTENSION.
Referenced by GGHumanClientApp::ContinueSinglePlayerGame(), and GGHumanClientApp::IsLoadGameAvailable().
RemoveOldestFiles()
void anonymous_namespace{GGHumanClientApp.cpp}::RemoveOldestFiles (int files_limit, boost::filesystem::path & p)
References ErrorLogger, MP_SAVE_FILE_EXTENSION, and SP_SAVE_FILE_EXTENSION.
Referenced by GGHumanClientApp::Autosave().
SetEmptyStringDefaultOption()
void anonymous_namespace{GGHumanClientApp.cpp}::SetEmptyStringDefaultOption (const std::string & option_name, const std::string & option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
References OptionsDB::Get(), GetOptionsDB(), OptionsDB::Set(), and OptionsDB::SetDefault().
Referenced by SetStringtableDependentOptionDefaults().
SetGLVersionDependentOptionDefaults()
void anonymous_namespace{GGHumanClientApp.cpp}::SetGLVersionDependentOptionDefaults ()
References DebugLogger, DoubleToString(), ErrorLogger, GetGLVersion(), GetOptionsDB(), and OptionsDB::Set().
Referenced by GGHumanClientApp::GGHumanClientApp().
SetStringtableDependentOptionDefaults()
void anonymous_namespace{GGHumanClientApp.cpp}::SetStringtableDependentOptionDefaults ()
References SetEmptyStringDefaultOption(), and UserString().
Referenced by GGHumanClientApp::GGHumanClientApp().
Variable Documentation
DEFAULT_HEIGHT
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_HEIGHT = 768
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_LEFT
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_LEFT = static_cast<int>(SDL_WINDOWPOS_CENTERED)
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_TOP
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_TOP = 50
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_WIDTH
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::DEFAULT_WIDTH = 1024
These options can only be validated after the graphics system (SDL) is initialized, so that display size can be detected.
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
INSTRUMENT_MESSAGE_HANDLING
constexpr bool anonymous_namespace{GGHumanClientApp.cpp}::INSTRUMENT_MESSAGE_HANDLING = false
Referenced by GGHumanClientApp::HandleMessage().
MIN_HEIGHT
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::MIN_HEIGHT = 600
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
MIN_WIDTH
constexpr int anonymous_namespace{GGHumanClientApp.cpp}::MIN_WIDTH = 800
Referenced by GGHumanClientApp::AddWindowSizeOptionsAfterMainStart().
stored_gl_version
float anonymous_namespace{GGHumanClientApp.cpp}::stored_gl_version = -1.0f static
Referenced by GetGLVersion().
temp_bool
bool anonymous_namespace{GGHumanClientApp.cpp}::temp_bool = RegisterOptions(&AddOptions)