FreeOrion: anonymous_namespace{CombatLogManager.cpp} Namespace Reference
anonymous_namespace{CombatLogManager.cpp} Namespace Reference
Functions
static float CurrentHealth (const UniverseObject &object)
static void FillState (CombatParticipantState &state, const UniverseObject &object)
static float MaxHealth (const UniverseObject &object)
Function Documentation
CurrentHealth()
static float anonymous_namespace{CombatLogManager.cpp}::CurrentHealth (const UniverseObject & object) static
References Meter::Current(), METER_CONSTRUCTION, METER_DEFENSE, METER_SHIELD, and METER_STRUCTURE.
Referenced by FillState().
FillState()
static void anonymous_namespace{CombatLogManager.cpp}::FillState (CombatParticipantState & state, const UniverseObject & object) static
References CombatParticipantState::current_health, CurrentHealth(), CombatParticipantState::max_health, and MaxHealth().
Referenced by CombatParticipantState::CombatParticipantState().
MaxHealth()
static float anonymous_namespace{CombatLogManager.cpp}::MaxHealth (const UniverseObject & object) static
References Meter::Current(), METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STRUCTURE, and METER_TARGET_CONSTRUCTION.
Referenced by FillState().