FreeOrion: py_parse::detail Namespace Reference
py_parse::detail Namespace Reference
Functions
template<typename T , typename F , typename V >
void flatten_list (const boost::python::object &l, const F &f, V &retval)
template<typename Grammar >
bool parse_file (const PythonParser &parser, const boost::filesystem::path &path, const Grammar &grammar)
template<typename Grammar , typename Arg1 >
bool parse_file (const PythonParser &parser, const boost::filesystem::path &path, const Grammar &grammar, Arg1 &arg1)
template<typename Grammar , typename Arg1 , typename Arg2 >
bool parse_file (const PythonParser &parser, const boost::filesystem::path &path, const Grammar &grammar, Arg1 &arg1, Arg2 &arg2)
Function Documentation
flatten_list()
template<typename T , typename F , typename V > void py_parse::detail::flatten_list (const boost::python::object & l, const F & f, V & retval)
References tag_parser::args.
parse_file() [1/3]
template<typename Grammar > bool py_parse::detail::parse_file (const PythonParser & parser, const boost::filesystem::path & path, const Grammar & grammar)
References PythonParser::ParseFileCommon().
parse_file() [2/3]
template<typename Grammar , typename Arg1 > bool py_parse::detail::parse_file (const PythonParser & parser, const boost::filesystem::path & path, const Grammar & grammar, Arg1 & arg1)
References PythonParser::ParseFileCommon().
parse_file() [3/3]
template<typename Grammar , typename Arg1 , typename Arg2 > bool py_parse::detail::parse_file (const PythonParser & parser, const boost::filesystem::path & path, const Grammar & grammar, Arg1 & arg1, Arg2 & arg2)
References PythonParser::ParseFileCommon().