FreeOrion: ValueRef Namespace Reference
ValueRef Namespace Reference
Namespaces
anonymous_namespace{ValueRefs.cpp}
Classes
struct ComplexVariable
The complex variable ValueRef class.
struct Constant
the constant value leaf ValueRef class.
struct NamedRef
The NamedRef class.
struct NameLookup
Returns the in-game name of the object / empire / etc.
struct Operation
An arithmetic operation node ValueRef class.
struct StaticCast
The variable static_cast class.
struct Statistic
The variable statistic class.
struct StringCast
The variable lexical_cast to string class.
struct UserStringLookup
Looks up a string ValueRef or vector of string ValueRefs, and returns and returns the UserString equivalent(s).
struct ValueRef
The base class for all ValueRef classes returning type T.
struct ValueRefBase
The common base class for all ValueRef classes.
struct Variable
The variable value ValueRef class.
Enumerations
enum OpType : int {
OpType::PLUS, OpType::MINUS, OpType::TIMES, OpType::DIVIDE,
OpType::NEGATE, OpType::EXPONENTIATE, OpType::ABS, OpType::LOGARITHM,
OpType::SINE, OpType::COSINE, OpType::MINIMUM, OpType::MAXIMUM,
OpType::RANDOM_UNIFORM, OpType::RANDOM_PICK, OpType::SUBSTITUTION, OpType::COMPARE_EQUAL,
OpType::COMPARE_GREATER_THAN, OpType::COMPARE_GREATER_THAN_OR_EQUAL, OpType::COMPARE_LESS_THAN, OpType::COMPARE_LESS_THAN_OR_EQUAL,
OpType::COMPARE_NOT_EQUAL, OpType::ROUND_NEAREST, OpType::ROUND_UP, OpType::ROUND_DOWN,
OpType::SIGN
}
enum ReferenceType : int {
ReferenceType::INVALID_REFERENCE_TYPE = -1, ReferenceType::NON_OBJECT_REFERENCE, ReferenceType::SOURCE_REFERENCE, ReferenceType::EFFECT_TARGET_REFERENCE,
ReferenceType::EFFECT_TARGET_VALUE_REFERENCE, ReferenceType::CONDITION_LOCAL_CANDIDATE_REFERENCE, ReferenceType::CONDITION_ROOT_CANDIDATE_REFERENCE
}
Functions
template<typename T >
std::unique_ptr< T > CloneUnique (const std::shared_ptr< T > &ptr)
template<typename T >
std::vector< std::unique_ptr< T > > CloneUnique (const std::vector< std::unique_ptr< T >> &vec)
template<typename T >
std::vector< std::pair< std::string, std::unique_ptr< T > > > CloneUnique (const std::vector< std::pair< std::string, std::unique_ptr< T >>> &vec)
std::string ComplexVariableDescription (const std::vector< std::string > &property_names, const ValueRef< int > *int_ref1, const ValueRef< int > *int_ref2, const ValueRef< int > *int_ref3, const ValueRef< std::string > *string_ref1, const ValueRef< std::string > *string_ref2)
std::string ComplexVariableDump (const std::vector< std::string > &property_names, const ValueRef< int > *int_ref1, const ValueRef< int > *int_ref2, const ValueRef< int > *int_ref3, const ValueRef< std::string > *string_ref1, const ValueRef< std::string > *string_ref2)
template<typename T , typename std::enable_if_t< std::is_arithmetic_v< T >> * = nullptr>
std::string FlexibleToString (T &&t)
std::string FlexibleToString (std::string &&t)
FO_ENUM ((StatisticType),((INVALID_STATISTIC_TYPE, -1))((IF))((COUNT))((UNIQUE_COUNT))((HISTO_MAX))((HISTO_MIN))((HISTO_SPREAD))((SUM))((MEAN))((RMS))((MODE))((MAX))((MIN))((SPREAD))((STDEV))((PRODUCT))) template< typename T > [[nodiscard]] inline std
std::string FormatedDescriptionPropertyNames (ReferenceType ref_type, const std::vector< std::string > &property_names, bool return_immediate_value)
const std::string & MeterToName (MeterType meter)
MeterType NameToMeter (const std::string &name)
std::string ReconstructName (const std::vector< std::string > &property_name, ReferenceType ref_type, bool return_immediate_value)
template<typename T , typename V , typename std::enable_if_t< std::is_arithmetic_v< T > &&std::is_arithmetic_v< V >> * = nullptr>
T ReduceData (StatisticType stat_type, std::vector< V > object_property_values)
template<typename T , typename V , typename std::enable_if_t< std::is_enum_v< T >> * = nullptr, typename std::enable_if_t< std::is_same_v< T, V >> * = nullptr>
T ReduceData (StatisticType stat_type, std::vector< T > object_property_values)
template<typename T , typename V , typename std::enable_if_t< std::is_arithmetic_v< T >> * = nullptr, typename std::enable_if_t<!std::is_arithmetic_v< V >> * = nullptr>
T ReduceData (StatisticType stat_type, std::vector< V > object_property_values)
std::string StatisticDescription (StatisticType stat_type, const std::string &value_desc, const std::string &condition_desc)
Enumeration Type Documentation
OpType
enum ValueRef::OpType : int strong
Enumerator
PLUS
MINUS
TIMES
DIVIDE
NEGATE
EXPONENTIATE
ABS
LOGARITHM
SINE
COSINE
MINIMUM
MAXIMUM
RANDOM_UNIFORM
RANDOM_PICK
SUBSTITUTION
COMPARE_EQUAL
COMPARE_GREATER_THAN
COMPARE_GREATER_THAN_OR_EQUAL
COMPARE_LESS_THAN
COMPARE_LESS_THAN_OR_EQUAL
COMPARE_NOT_EQUAL
ROUND_NEAREST
ROUND_UP
ROUND_DOWN
SIGN
ReferenceType
enum ValueRef::ReferenceType : int strong
Enumerator
INVALID_REFERENCE_TYPE
NON_OBJECT_REFERENCE
SOURCE_REFERENCE
EFFECT_TARGET_REFERENCE
EFFECT_TARGET_VALUE_REFERENCE
CONDITION_LOCAL_CANDIDATE_REFERENCE
CONDITION_ROOT_CANDIDATE_REFERENCE
Function Documentation
CloneUnique() [1/3]
template<typename T > std::unique_ptr<T> ValueRef::CloneUnique (const std::shared_ptr< T > & ptr) inline
Referenced by Effect::SetMeter::Clone(), Condition::Number::Clone(), Effect::SetShipPartMeter::Clone(), Condition::Turn::Clone(), Effect::SetEmpireMeter::Clone(), Condition::SortedNumberOf::Clone(), ValueRef::Statistic< T, V >::Clone(), Effect::SetEmpireStockpile::Clone(), Effect::SetEmpireCapital::Clone(), Condition::EmpireAffiliation::Clone(), Effect::SetPlanetType::Clone(), Effect::SetPlanetSize::Clone(), Effect::SetSpecies::Clone(), ValueRef::StaticCast< FromType, ToType >::Clone(), Effect::SetOwner::Clone(), Condition::Homeworld::Clone(), ValueRef::StringCast< FromType >::Clone(), Effect::SetSpeciesEmpireOpinion::Clone(), ValueRef::UserStringLookup< FromType >::Clone(), Effect::SetSpeciesSpeciesOpinion::Clone(), Effect::CreatePlanet::Clone(), ValueRef::NameLookup::Clone(), Effect::CreateBuilding::Clone(), Condition::Type::Clone(), Condition::Building::Clone(), Effect::CreateShip::Clone(), Effect::CreateField::Clone(), Condition::HasTag::Clone(), Effect::CreateSystem::Clone(), Condition::CreatedOnTurn::Clone(), Condition::Contains::Clone(), Effect::AddSpecial::Clone(), Condition::ContainedBy::Clone(), Effect::RemoveSpecial::Clone(), Effect::AddStarlanes::Clone(), Condition::InOrIsSystem::Clone(), Effect::RemoveStarlanes::Clone(), Condition::OnPlanet::Clone(), Effect::SetStarType::Clone(), Condition::ObjectID::Clone(), Effect::MoveTo::Clone(), Effect::MoveInOrbit::Clone(), Condition::PlanetType::Clone(), Condition::PlanetSize::Clone(), Effect::MoveTowards::Clone(), Effect::SetDestination::Clone(), Condition::PlanetEnvironment::Clone(), Condition::Species::Clone(), Effect::SetEmpireTechProgress::Clone(), Effect::GiveEmpireContent::Clone(), Condition::FocusType::Clone(), Condition::StarType::Clone(), Effect::GenerateSitRepMessage::Clone(), Condition::DesignHasHull::Clone(), Effect::SetOverlayTexture::Clone(), Condition::DesignHasPart::Clone(), Condition::DesignHasPartClass::Clone(), Effect::SetVisibility::Clone(), Condition::PredefinedShipDesign::Clone(), Condition::NumberedShipDesign::Clone(), Effect::Conditional::Clone(), Condition::ProducedByEmpire::Clone(), Condition::Chance::Clone(), Condition::MeterValue::Clone(), Condition::ShipPartMeterValue::Clone(), Condition::EmpireMeterValue::Clone(), Condition::EmpireStockpileValue::Clone(), Condition::EmpireHasAdoptedPolicy::Clone(), Condition::OwnerHasTech::Clone(), Condition::OwnerHasBuildingTypeAvailable::Clone(), Condition::OwnerHasShipDesignAvailable::Clone(), Condition::OwnerHasShipPartAvailable::Clone(), Condition::VisibleToEmpire::Clone(), Condition::WithinDistance::Clone(), Condition::WithinStarlaneJumps::Clone(), Condition::CanAddStarlaneConnection::Clone(), Condition::ExploredByEmpire::Clone(), Condition::FleetSupplyableByEmpire::Clone(), Condition::ResourceSupplyConnectedByEmpire::Clone(), Condition::OrderedBombarded::Clone(), Condition::Location::Clone(), Condition::CombatTarget::Clone(), Condition::And::Clone(), Condition::Or::Clone(), Condition::Not::Clone(), Condition::OrderedAlternativesOf::Clone(), Condition::Described::Clone(), CloneUnique(), anonymous_namespace{TechsParser.cpp}::insert_contained_by_(), anonymous_namespace{TechsParser.cpp}::insert_contains_(), anonymous_namespace{TechsParser.cpp}::insert_effects_group_(), anonymous_namespace{TechsParser.cpp}::insert_generate_sit_rep_message_(), anonymous_namespace{TechsParser.cpp}::insert_has_tag_(), anonymous_namespace{TechsParser.cpp}::insert_meter_value_(), anonymous_namespace{TechsParser.cpp}::insert_minmaxoneof_(), anonymous_namespace{TechsParser.cpp}::insert_owned_by_(), anonymous_namespace{TechsParser.cpp}::insert_planet_(), anonymous_namespace{TechsParser.cpp}::insert_set_meter_(), anonymous_namespace{TechsParser.cpp}::insert_visible_to_empire_(), operator*(), operator+(), operator-(), operator<(), operator==(), and anonymous_namespace{TechsParser.cpp}::py_insert_tech_().
CloneUnique() [2/3]
template<typename T > std::vector<std::unique_ptr<T> > ValueRef::CloneUnique (const std::vector< std::unique_ptr< T >> & vec) inline
References CloneUnique().
CloneUnique() [3/3]
template<typename T > std::vector<std::pair<std::string, std::unique_ptr<T> > > ValueRef::CloneUnique (const std::vector< std::pair< std::string, std::unique_ptr< T >>> & vec) inline
References CloneUnique().
ComplexVariableDescription()
FO_COMMON_API std::string ValueRef::ComplexVariableDescription (const std::vector< std::string > & property_names, const ValueRef< int > * int_ref1, const ValueRef< int > * int_ref2, const ValueRef< int > * int_ref3, const ValueRef< std::string > * string_ref1, const ValueRef< std::string > * string_ref2)
References ValueRef::ValueRefBase::Description(), ErrorLogger, FlexibleFormat(), UserString(), and UserStringExists().
Referenced by ValueRef::ComplexVariable< T >::Description().
ComplexVariableDump()
FO_COMMON_API std::string ValueRef::ComplexVariableDump (const std::vector< std::string > & property_names, const ValueRef< int > * int_ref1, const ValueRef< int > * int_ref2, const ValueRef< int > * int_ref3, const ValueRef< std::string > * string_ref1, const ValueRef< std::string > * string_ref2)
References ValueRef::ValueRefBase::Dump(), and ErrorLogger.
Referenced by ValueRef::ComplexVariable< T >::Dump().
FlexibleToString() [1/2]
template<typename T , typename std::enable_if_t< std::is_arithmetic_v< T >> * = nullptr> std::string ValueRef::FlexibleToString (T && t)
References DoubleToString(), and to_string().
Referenced by ValueRef::ValueRef< ToType >::EvalAsString(), and FlexibleToString().
FlexibleToString() [2/2]
std::string ValueRef::FlexibleToString (std::string && t) inline
References FlexibleToString(), FO_COMMON_API, and operator==().
FO_ENUM()
ValueRef::FO_ENUM ((StatisticType) , ((INVALID_STATISTIC_TYPE, -1))((IF))((COUNT))((UNIQUE_COUNT))((HISTO_MAX))((HISTO_MIN))((HISTO_SPREAD))((SUM))((MEAN))((RMS))((MODE))((MAX))((MIN))((SPREAD))((STDEV))((PRODUCT)))
FormatedDescriptionPropertyNames()
FO_COMMON_API std::string ValueRef::FormatedDescriptionPropertyNames (ReferenceType ref_type, const std::vector< std::string > & property_names, bool return_immediate_value)
References FlexibleFormat(), and UserString().
Referenced by ValueRef::Variable< ToType >::Description().
MeterToName()
FO_COMMON_API const std::string & ValueRef::MeterToName (MeterType meter)
References anonymous_namespace{ValueRefs.cpp}::EMPTY_STRING, and anonymous_namespace{ValueRefs.cpp}::GetMeterNameMap().
Referenced by anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes().
NameToMeter()
FO_COMMON_API MeterType ValueRef::NameToMeter (const std::string & name)
References anonymous_namespace{ValueRefs.cpp}::GetMeterNameMap().
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().
ReconstructName()
FO_COMMON_API std::string ValueRef::ReconstructName (const std::vector< std::string > & property_name, ReferenceType ref_type, bool return_immediate_value)
Referenced by ValueRef::Variable< ToType >::Dump(), and anonymous_namespace{ValueRefs.cpp}::TraceReference().
ReduceData() [1/3]
template<typename T , typename V , typename std::enable_if_t< std::is_arithmetic_v< T > &&std::is_arithmetic_v< V >> * = nullptr> T ValueRef::ReduceData (StatisticType stat_type, std::vector< V > object_property_values)
References max, and min.
ReduceData() [2/3]
template<typename T , typename V , typename std::enable_if_t< std::is_enum_v< T >> * = nullptr, typename std::enable_if_t< std::is_same_v< T, V >> * = nullptr> T ValueRef::ReduceData (StatisticType stat_type, std::vector< T > object_property_values)
References max.
ReduceData() [3/3]
template<typename T , typename V , typename std::enable_if_t< std::is_arithmetic_v< T >> * = nullptr, typename std::enable_if_t<!std::is_arithmetic_v< V >> * = nullptr> T ValueRef::ReduceData (StatisticType stat_type, std::vector< V > object_property_values)
References max, and min.
StatisticDescription()
FO_COMMON_API std::string ValueRef::StatisticDescription (StatisticType stat_type, const std::string & value_desc, const std::string & condition_desc)
References FlexibleFormat(), UserString(), and UserStringExists().
Referenced by ValueRef::Statistic< T, V >::Description().