FreeOrion: anonymous_namespace{LinkText.cpp} Namespace Reference
anonymous_namespace{LinkText.cpp} Namespace Reference
Functions
std::string AllParamsAsString (const std::vector< GG::Font::Substring > &params)
const std::string BROWSEPATH_TAG_CLOSE ("</"+TextLinker::BROWSE_PATH_TAG+">")
const std::string BROWSEPATH_TAG_OPEN_PRE ("<"+TextLinker::BROWSE_PATH_TAG)
std::string BrowsePathLinkText (const std::string &text)
Parses TextLinker::BROWSE_PATH_TAGs within text, replacing string representation of PathTypes with current path for that PathType.
std::string ResolveNestedPathTypes (const std::string &text)
Variables
const xpr::sregex BROWSEPATH_SEARCH
static const std::string LINK_FORMAT_CLOSE = "</rgba>"
static bool link_tags_registered = false
const xpr::sregex REGEX_NON_BRACKET = *~(xpr::set= '<', '>')
static const bool RENDER_DEBUGGING_LINK_RECTS = false
Function Documentation
AllParamsAsString()
std::string anonymous_namespace{LinkText.cpp}::AllParamsAsString (const std::vector< GG::Font::Substring > & params)
Referenced by TextLinker::FindLinks().
BROWSEPATH_TAG_CLOSE()
const std::string anonymous_namespace{LinkText.cpp}::BROWSEPATH_TAG_CLOSE ("</"+TextLinker::BROWSE_PATH_TAG+">")
Referenced by BrowsePathLinkText().
BROWSEPATH_TAG_OPEN_PRE()
const std::string anonymous_namespace{LinkText.cpp}::BROWSEPATH_TAG_OPEN_PRE ()
Referenced by BrowsePathLinkText().
BrowsePathLinkText()
std::string anonymous_namespace{LinkText.cpp}::BrowsePathLinkText (const std::string & text)
Parses TextLinker::BROWSE_PATH_TAGs within text, replacing string representation of PathTypes with current path for that PathType.
If link label is empty, inserts resolved link argument as label
References BROWSEPATH_SEARCH, BROWSEPATH_TAG_CLOSE(), BROWSEPATH_TAG_OPEN_PRE(), PathTypeToString(), ResolveNestedPathTypes(), and UserString().
Referenced by PathTypeDecorator::Decorate(), and PathTypeDecorator::DecorateRollover().
ResolveNestedPathTypes()
std::string anonymous_namespace{LinkText.cpp}::ResolveNestedPathTypes (const std::string & text)
References GetPath(), PathToString(), and PathTypeStrings().
Referenced by BrowsePathLinkText(), and TextLinker::FindLinks().
Variable Documentation
BROWSEPATH_SEARCH
const xpr::sregex anonymous_namespace{LinkText.cpp}::BROWSEPATH_SEARCH
Initial value:
= BROWSEPATH_TAG_OPEN_PRE >> xpr::_s >> (xpr::s1 = REGEX_NON_BRACKET) >> ">" >>
                                          (xpr::s2 = REGEX_NON_BRACKET) >> BROWSEPATH_TAG_CLOSE
Referenced by BrowsePathLinkText().
LINK_FORMAT_CLOSE
const std::string anonymous_namespace{LinkText.cpp}::LINK_FORMAT_CLOSE = "</rgba>" static
Referenced by LinkDecorator::Decorate(), ValueRefDecorator::Decorate(), LinkDecorator::DecorateRollover(), and ValueRefDecorator::DecorateRollover().
link_tags_registered
bool anonymous_namespace{LinkText.cpp}::link_tags_registered = false static
Referenced by RegisterLinkTags().
REGEX_NON_BRACKET
const xpr::sregex anonymous_namespace{LinkText.cpp}::REGEX_NON_BRACKET = *~(xpr::set= '<', '>')
Referenced by ValueRefLinkText().
RENDER_DEBUGGING_LINK_RECTS
const bool anonymous_namespace{LinkText.cpp}::RENDER_DEBUGGING_LINK_RECTS = false static
Referenced by TextLinker::Render_().