FreeOrion: anonymous_namespace{Universe.cpp} Namespace Reference
anonymous_namespace{Universe.cpp} Namespace Reference
Classes
struct constant_property
Functions
void AddOptions (OptionsDB &db)
void AddRules (GameRules &rules)
DeclareThreadSafeLogger (effects)
DeclareThreadSafeLogger (conditions)
void DispatchEffectsGroupScopeEvaluations (EffectsCauseType effect_cause_type, const std::string &specific_cause_name, const Condition::ObjectSet &source_objects, const std::vector< std::shared_ptr< Effect::EffectsGroup >> &effects_groups, bool only_meter_effects, ScriptingContext context, const Condition::ObjectSet &potential_targets, const std::unordered_set< int > &potential_target_ids, std::list< std::pair< Effect::SourcesEffectsTargetsAndCausesVec, Effect::SourcesEffectsTargetsAndCausesVec *>> &source_effects_targets_causes_reorder_buffer_out, boost::asio::thread_pool &thread_pool, int &n)
Collect info for scope condition evaluations and dispatch those evaluations to thread_pool.
void FilterObjectIDsByKnownDestruction (std::vector< int > &object_ids, int empire_id, const std::map< int, std::set< int >> &empire_known_destroyed_object_ids)
removes ids of objects that the indicated empire knows have been destroyed
std::vector< int > FilterObjectPositionsByDetectorPositionsAndRanges (const std::map< std::pair< double, double >, std::vector< int >> &object_positions, const std::map< std::pair< double, double >, float > &detector_position_ranges)
filters set of objects at locations by which of those locations are within range of a set of detectors and ranges
std::map< int, float > GetEmpiresDetectionStrengths (const EmpireManager &empires, int empire_id=ALL_EMPIRES)
auto GetEmpiresPositionDetectionRanges (const ObjectMap &objects)
for each empire: for each position where the empire has detector objects, what is the empire's detection range at that location? (this is the largest of the detection ranges of objects the empire has at that spot)
std::map< int, std::map< std::pair< double, double >, std::vector< int > > > GetEmpiresPositionsPotentiallyDetectableObjects (const ObjectMap &objects, const EmpireManager &empires, int empire_id=ALL_EMPIRES)
for each empire: for each position, what objects have low enough stealth that the empire could detect them if an detector owned by the empire is in range?
void PropagateVisibilityToContainerObjects (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void PropagateVisibilityToSystemsAlongStarlanes (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void SetAllObjectsVisibleToAllEmpires (Universe &universe)
sets all objects visible to all empires
void SetAllSystemsBasicallyVisibleToAllEmpires (Universe &universe)
sets all systems basically visible to all empires
void SetEmpireFieldVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> &empire_location_detection_ranges, const ObjectMap &objects)
sets visibility of field objects for empires based on input locations and stealth of fields in supplied ObjectMap and input empire detection ranges at locations.
void SetEmpireObjectVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> &empire_location_detection_ranges, const std::map< int, std::map< std::pair< double, double >, std::vector< int >>> &empire_location_potentially_detectable_objects)
sets visibility of objects for empires based on input locations of potentially detectable objects (if in range) and and input empire detection ranges at locations.
void SetEmpireOwnedObjectVisibilities (Universe &universe)
sets visibility of objects that empires own for those objects
void SetEmpireSpecialVisibilities (const ScriptingContext &input_context, Universe::EmpireObjectVisibilityMap &empire_object_visibility, Universe::EmpireObjectSpecialsMap &empire_object_visible_specials)
void SetSameSystemPlanetsVisible (const ObjectMap &objects)
sets planets that an empire has at some time had visibility of, which are also in system where an empire owns an object, to be basically visible, and those systems to be partially visible
void SetTravelledStarlaneEndpointsVisible (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void ShareVisbilitiesBetweenAllies (Universe &universe, const EmpireManager &empires, Universe::EmpireObjectVisibilityMap &empire_object_visibility, Universe::EmpireObjectSpecialsMap &empire_object_visible_specials)
void StoreTargetsAndCausesOfEffectsGroup (ScriptingContext &context, const Effect::EffectsGroup *effects_group, const Condition::ObjectSet &source_objects, EffectsCauseType effect_cause_type, const std::string &specific_cause_name, const std::unordered_set< int > &candidate_object_ids, Effect::TargetSet &candidate_objects_in, Effect::SourcesEffectsTargetsAndCausesVec &source_effects_targets_causes_out, int n)
Evaluate activation, and scope conditions of effects_group for each of the objects in source_objects for the candidate target objects in candidate_objects_in (unless it is empty, in which case the default candidate objects for the scope condition is used.
Variables
constexpr bool ENABLE_VISIBILITY_EMPIRE_MEMORY = true
bool temp_bool = RegisterOptions(&AddOptions)
bool temp_bool2 = RegisterGameRules(&AddRules)
Function Documentation
AddOptions()
void anonymous_namespace{Universe.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
AddRules()
void anonymous_namespace{Universe.cpp}::AddRules (GameRules & rules)
References GameRules::Add(), and UserStringNop.
DeclareThreadSafeLogger() [1/2]
anonymous_namespace{Universe.cpp}::DeclareThreadSafeLogger (effects)
DeclareThreadSafeLogger() [2/2]
anonymous_namespace{Universe.cpp}::DeclareThreadSafeLogger (conditions)
DispatchEffectsGroupScopeEvaluations()
void anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations (EffectsCauseType effect_cause_type, const std::string & specific_cause_name, const Condition::ObjectSet & source_objects, const std::vector< std::shared_ptr< Effect::EffectsGroup >> & effects_groups, bool only_meter_effects, ScriptingContext context, const Condition::ObjectSet & potential_targets, const std::unordered_set< int > & potential_target_ids, std::list< std::pair< Effect::SourcesEffectsTargetsAndCausesVec, Effect::SourcesEffectsTargetsAndCausesVec *>> & source_effects_targets_causes_reorder_buffer_out, boost::asio::thread_pool & thread_pool, int & n)
Collect info for scope condition evaluations and dispatch those evaluations to thread_pool.
Not thread-safe, but the individual condition evaluations should be safe to evaluate in parallel.
References Condition::MATCHES, boost::asio::post(), ScriptingContext::source, StoreTargetsAndCausesOfEffectsGroup(), to_string(), and TraceLogger.
Referenced by Universe::GetEffectsAndTargets().
FilterObjectIDsByKnownDestruction()
void anonymous_namespace{Universe.cpp}::FilterObjectIDsByKnownDestruction (std::vector< int > & object_ids, int empire_id, const std::map< int, std::set< int >> & empire_known_destroyed_object_ids)
removes ids of objects that the indicated empire knows have been destroyed
References ALL_EMPIRES.
Referenced by Universe::UpdateEmpireStaleObjectKnowledge().
FilterObjectPositionsByDetectorPositionsAndRanges()
std::vector<int> anonymous_namespace{Universe.cpp}::FilterObjectPositionsByDetectorPositionsAndRanges (const std::map< std::pair< double, double >, std::vector< int >> & object_positions, const std::map< std::pair< double, double >, float > & detector_position_ranges)
filters set of objects at locations by which of those locations are within range of a set of detectors and ranges
Referenced by SetEmpireObjectVisibilitiesFromRanges(), and Universe::UpdateEmpireStaleObjectKnowledge().
GetEmpiresDetectionStrengths()
std::map<int, float> anonymous_namespace{Universe.cpp}::GetEmpiresDetectionStrengths (const EmpireManager & empires, int empire_id = ALL_EMPIRES)
References ALL_EMPIRES, Meter::Current(), and EmpireManager::GetEmpire().
Referenced by GetEmpiresPositionsPotentiallyDetectableObjects().
GetEmpiresPositionDetectionRanges()
auto anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges (const ObjectMap & objects)
for each empire: for each position where the empire has detector objects, what is the empire's detection range at that location? (this is the largest of the detection ranges of objects the empire has at that spot)
References ObjectMap::all(), Meter::Current(), ObjectMap::get(), and INVALID_OBJECT_ID.
Referenced by Universe::UpdateEmpireObjectVisibilities(), and Universe::UpdateEmpireStaleObjectKnowledge().
GetEmpiresPositionsPotentiallyDetectableObjects()
std::map<int, std::map<std::pair<double, double>, std::vector<int> > > anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects (const ObjectMap & objects, const EmpireManager & empires, int empire_id = ALL_EMPIRES)
for each empire: for each position, what objects have low enough stealth that the empire could detect them if an detector owned by the empire is in range?
References ObjectMap::all(), Meter::Current(), and GetEmpiresDetectionStrengths().
Referenced by Universe::UpdateEmpireObjectVisibilities(), and Universe::UpdateEmpireStaleObjectKnowledge().
PropagateVisibilityToContainerObjects()
void anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects (const ObjectMap & objects, Universe::EmpireObjectVisibilityMap & empire_object_visibility)
References ObjectMap::all(), and VIS_NO_VISIBILITY().
Referenced by Universe::UpdateEmpireObjectVisibilities().
PropagateVisibilityToSystemsAlongStarlanes()
void anonymous_namespace{Universe.cpp}::PropagateVisibilityToSystemsAlongStarlanes (const ObjectMap & objects, Universe::EmpireObjectVisibilityMap & empire_object_visibility)
References ObjectMap::all().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetAllObjectsVisibleToAllEmpires()
void anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires (Universe & universe)
sets all objects visible to all empires
References ObjectMap::all(), Empires(), Universe::Objects(), Universe::SetEmpireObjectVisibility(), and Universe::SetEmpireSpecialVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetAllSystemsBasicallyVisibleToAllEmpires()
void anonymous_namespace{Universe.cpp}::SetAllSystemsBasicallyVisibleToAllEmpires (Universe & universe)
sets all systems basically visible to all empires
References ObjectMap::all(), Empires(), Universe::Objects(), and Universe::SetEmpireObjectVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetEmpireFieldVisibilitiesFromRanges()
void anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> & empire_location_detection_ranges, const ObjectMap & objects)
sets visibility of field objects for empires based on input locations and stealth of fields in supplied ObjectMap and input empire detection ranges at locations.
the rules for detection of fields are more permissive than other object types, so a special function for them is needed in addition to SetEmpireObjectVisibilitiesFromRanges(...)
References ObjectMap::all(), Meter::Current(), GetEmpire(), GetUniverse(), and Universe::SetEmpireObjectVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetEmpireObjectVisibilitiesFromRanges()
void anonymous_namespace{Universe.cpp}::SetEmpireObjectVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> & empire_location_detection_ranges, const std::map< int, std::map< std::pair< double, double >, std::vector< int >>> & empire_location_potentially_detectable_objects)
sets visibility of objects for empires based on input locations of potentially detectable objects (if in range) and and input empire detection ranges at locations.
References FilterObjectPositionsByDetectorPositionsAndRanges(), GetUniverse(), and Universe::SetEmpireObjectVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetEmpireOwnedObjectVisibilities()
void anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities (Universe & universe)
sets visibility of objects that empires own for those objects
References ObjectMap::all(), Universe::Objects(), and Universe::SetEmpireObjectVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetEmpireSpecialVisibilities()
void anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities (const ScriptingContext & input_context, Universe::EmpireObjectVisibilityMap & empire_object_visibility, Universe::EmpireObjectSpecialsMap & empire_object_visible_specials)
References ScriptingContext::ContextObjects(), Meter::Current(), Empires(), ObjectMap::get(), GetSpecial(), Special::Stealth(), and VIS_NO_VISIBILITY().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetSameSystemPlanetsVisible()
void anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible (const ObjectMap & objects)
sets planets that an empire has at some time had visibility of, which are also in system where an empire owns an object, to be basically visible, and those systems to be partially visible
References ObjectMap::all(), GameRules::Get(), GetGameRules(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetUniverse(), INVALID_OBJECT_ID, and Universe::SetEmpireObjectVisibility().
Referenced by Universe::UpdateEmpireObjectVisibilities().
SetTravelledStarlaneEndpointsVisible()
void anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible (const ObjectMap & objects, Universe::EmpireObjectVisibilityMap & empire_object_visibility)
References ObjectMap::find(), INVALID_OBJECT_ID, and Fleet::PreviousSystemID().
Referenced by Universe::UpdateEmpireObjectVisibilities().
ShareVisbilitiesBetweenAllies()
void anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies (Universe & universe, const EmpireManager & empires, Universe::EmpireObjectVisibilityMap & empire_object_visibility, Universe::EmpireObjectSpecialsMap & empire_object_visible_specials)
References ErrorLogger, ObjectMap::get(), Universe::Objects(), Universe::SetEmpireKnowledgeOfShipDesign(), and parse::specials().
Referenced by Universe::UpdateEmpireObjectVisibilities().
StoreTargetsAndCausesOfEffectsGroup()
void anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroup (ScriptingContext & context, const Effect::EffectsGroup * effects_group, const Condition::ObjectSet & source_objects, EffectsCauseType effect_cause_type, const std::string & specific_cause_name, const std::unordered_set< int > & candidate_object_ids, Effect::TargetSet & candidate_objects_in, Effect::SourcesEffectsTargetsAndCausesVec & source_effects_targets_causes_out, int n)
Evaluate activation, and scope conditions of effects_group for each of the objects in source_objects for the candidate target objects in candidate_objects_in (unless it is empty, in which case the default candidate objects for the scope condition is used.
Stores the objects that matched the effects group's scope condition, for each source object, as a separate entry in targets_cases_out
References ErrorLogger, ScriptingContext::source, to_string(), and TraceLogger.
Referenced by DispatchEffectsGroupScopeEvaluations().
Variable Documentation
ENABLE_VISIBILITY_EMPIRE_MEMORY
constexpr bool anonymous_namespace{Universe.cpp}::ENABLE_VISIBILITY_EMPIRE_MEMORY = true
Referenced by Universe::GetEmpireKnownObjectsToSerialize(), and Universe::GetObjectsToSerialize().
temp_bool
bool anonymous_namespace{Universe.cpp}::temp_bool = RegisterOptions(&AddOptions)
temp_bool2
bool anonymous_namespace{Universe.cpp}::temp_bool2 = RegisterGameRules(&AddRules)