FreeOrion: anonymous_namespace{HumanClientApp.cpp} Namespace Reference
anonymous_namespace{HumanClientApp.cpp} Namespace Reference
Classes
class LocalServerAlreadyRunningException
Functions
void AddOptions (OptionsDB &db)
void ClearPreviousPendingSaves (std::queue< std::string > &pending_saves)
boost::filesystem::path CreateNewAutosaveFilePath (int client_empire_id, bool is_single_player)
float GetGLVersion ()
std::string GetGLVersionString ()
boost::optional< std::string > NewestSinglePlayerSavegame ()
void RemoveOldestFiles (int files_limit, boost::filesystem::path &p)
std::string ServerClientExe ()
void SetEmptyStringDefaultOption (const std::string &option_name, const std::string &option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
void SetGLVersionDependentOptionDefaults ()
void SetStringtableDependentOptionDefaults ()
Variables
const int DEFAULT_HEIGHT = 768
const int DEFAULT_LEFT = static_cast<int>(SDL_WINDOWPOS_CENTERED)
const int DEFAULT_TOP = 50
const int DEFAULT_WIDTH = 1024
These options can only be validated after the graphics system (SDL) is initialized, so that display size can be detected.
const bool INSTRUMENT_MESSAGE_HANDLING = false
const int MIN_HEIGHT = 600
const int MIN_WIDTH = 800
static float stored_gl_version = -1.0f
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{HumanClientApp.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), Hotkey::AddHotkey(), and UserStringNop.
ClearPreviousPendingSaves()
void anonymous_namespace{HumanClientApp.cpp}::ClearPreviousPendingSaves (std::queue< std::string > & pending_saves)
References swap(), to_string(), and WarnLogger.
Referenced by HumanClientApp::MultiPlayerGame(), HumanClientApp::NewSinglePlayerGame(), and HumanClientApp::ResetClientData().
CreateNewAutosaveFilePath()
boost::filesystem::path anonymous_namespace{HumanClientApp.cpp}::CreateNewAutosaveFilePath (int client_empire_id, bool is_single_player)
References ClientApp::CurrentTurn(), ErrorLogger, FilenameTimestamp(), ClientApp::GetEmpire(), GetSaveDir(), GetServerSaveDir(), MP_SAVE_FILE_EXTENSION, SP_SAVE_FILE_EXTENSION, and UserString().
Referenced by HumanClientApp::Autosave().
GetGLVersion()
float anonymous_namespace{HumanClientApp.cpp}::GetGLVersion ()
References GetGLVersionString(), and stored_gl_version.
Referenced by HumanClientApp::GLVersion(), HumanClientApp::HumanClientApp(), and SetGLVersionDependentOptionDefaults().
GetGLVersionString()
std::string anonymous_namespace{HumanClientApp.cpp}::GetGLVersionString ()
Referenced by GetGLVersion(), and HumanClientApp::HumanClientApp().
NewestSinglePlayerSavegame()
boost::optional<std::string> anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame ()
References ErrorLogger, GetSaveDir(), PathToString(), SaveFileWithValidHeader(), and SP_SAVE_FILE_EXTENSION.
Referenced by HumanClientApp::ContinueSinglePlayerGame(), and HumanClientApp::IsLoadGameAvailable().
RemoveOldestFiles()
void anonymous_namespace{HumanClientApp.cpp}::RemoveOldestFiles (int files_limit, boost::filesystem::path & p)
References ErrorLogger, MP_SAVE_FILE_EXTENSION, and SP_SAVE_FILE_EXTENSION.
Referenced by HumanClientApp::Autosave().
ServerClientExe()
std::string anonymous_namespace{HumanClientApp.cpp}::ServerClientExe ()
References GetBinDir(), and PathToString().
Referenced by HumanClientApp::StartServer().
SetEmptyStringDefaultOption()
void anonymous_namespace{HumanClientApp.cpp}::SetEmptyStringDefaultOption (const std::string & option_name, const std::string & option_value)
Sets the default and current values for the string option option_name to option_value if initially empty.
References OptionsDB::Get(), GetOptionsDB(), OptionsDB::Set(), and OptionsDB::SetDefault().
Referenced by SetStringtableDependentOptionDefaults().
SetGLVersionDependentOptionDefaults()
void anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults ()
References DebugLogger, DoubleToString(), ErrorLogger, GetGLVersion(), GetOptionsDB(), and OptionsDB::Set().
Referenced by HumanClientApp::HumanClientApp().
SetStringtableDependentOptionDefaults()
void anonymous_namespace{HumanClientApp.cpp}::SetStringtableDependentOptionDefaults ()
References SetEmptyStringDefaultOption(), and UserString().
Referenced by HumanClientApp::HumanClientApp().
Variable Documentation
DEFAULT_HEIGHT
const int anonymous_namespace{HumanClientApp.cpp}::DEFAULT_HEIGHT = 768
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_LEFT
const int anonymous_namespace{HumanClientApp.cpp}::DEFAULT_LEFT = static_cast<int>(SDL_WINDOWPOS_CENTERED)
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_TOP
const int anonymous_namespace{HumanClientApp.cpp}::DEFAULT_TOP = 50
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
DEFAULT_WIDTH
const int anonymous_namespace{HumanClientApp.cpp}::DEFAULT_WIDTH = 1024
These options can only be validated after the graphics system (SDL) is initialized, so that display size can be detected.
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
INSTRUMENT_MESSAGE_HANDLING
const bool anonymous_namespace{HumanClientApp.cpp}::INSTRUMENT_MESSAGE_HANDLING = false
Referenced by HumanClientApp::HandleMessage().
MIN_HEIGHT
const int anonymous_namespace{HumanClientApp.cpp}::MIN_HEIGHT = 600
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
MIN_WIDTH
const int anonymous_namespace{HumanClientApp.cpp}::MIN_WIDTH = 800
Referenced by HumanClientApp::AddWindowSizeOptionsAfterMainStart().
stored_gl_version
float anonymous_namespace{HumanClientApp.cpp}::stored_gl_version = -1.0f static
Referenced by GetGLVersion().
temp_bool
bool anonymous_namespace{HumanClientApp.cpp}::temp_bool = RegisterOptions(&AddOptions)