FreeOrion: anonymous_namespace{i18n.cpp} Namespace Reference
anonymous_namespace{i18n.cpp} Namespace Reference
Functions
boost::filesystem::path DevDefaultEnglishStringtablePath ()
boost::filesystem::path GetDefaultStringTableFileName ()
const StringTable & GetDevDefaultStringTable ()
const StringTable & GetStringTable (boost::filesystem::path stringtable_path)
const StringTable & GetStringTable ()
std::string GetStringTableFileName ()
void InitStringtableFileName ()
double RoundMagnitude (double mag, int digits)
Variables
constexpr double LARGE_UI_DISPLAY_VALUE = 9.99999999e+9
constexpr double SMALL_UI_DISPLAY_VALUE = 1.0e-6
std::recursive_mutex stringtable_access_mutex
bool stringtable_filename_init = false
std::map< std::string, std::shared_ptr< const StringTable > > stringtables
constexpr double UNKNOWN_UI_DISPLAY_VALUE = std::numeric_limits<double>::infinity()
Function Documentation
DevDefaultEnglishStringtablePath()
boost::filesystem::path anonymous_namespace{i18n.cpp}::DevDefaultEnglishStringtablePath ()
References GetResourceDir().
Referenced by GetDefaultStringTableFileName(), and GetDevDefaultStringTable().
GetDefaultStringTableFileName()
boost::filesystem::path anonymous_namespace{i18n.cpp}::GetDefaultStringTableFileName ()
References DebugLogger, DevDefaultEnglishStringtablePath(), ErrorLogger, GetLocale(), GetResourceDir(), IsExistingFile(), PathToString(), and WarnLogger.
Referenced by InitStringtableFileName().
GetDevDefaultStringTable()
const StringTable& anonymous_namespace{i18n.cpp}::GetDevDefaultStringTable ()
References DevDefaultEnglishStringtablePath(), and GetStringTable().
Referenced by AllStringtableEntries(), UserString(), and UserStringExists().
GetStringTable() [1/2]
const StringTable& anonymous_namespace{i18n.cpp}::GetStringTable (boost::filesystem::path stringtable_path)
References OptionsDB::GetDefault(), GetOptionsDB(), InitStringtableFileName(), and PathToString().
GetStringTable() [2/2]
const StringTable& anonymous_namespace{i18n.cpp}::GetStringTable ()
References GetStringTableFileName().
Referenced by AllStringtableEntries(), GetDevDefaultStringTable(), Language(), UserString(), and UserStringExists().
GetStringTableFileName()
std::string anonymous_namespace{i18n.cpp}::GetStringTableFileName ()
References OptionsDB::Get(), OptionsDB::GetDefault(), GetOptionsDB(), and InitStringtableFileName().
Referenced by GetStringTable().
InitStringtableFileName()
void anonymous_namespace{i18n.cpp}::InitStringtableFileName ()
References DebugLogger, ErrorLogger, OptionsDB::Get(), GetDefaultStringTableFileName(), GetOptionsDB(), GetResourceDir(), IsExistingFile(), PathToString(), OptionsDB::Set(), and OptionsDB::SetDefault().
Referenced by GetStringTable(), and GetStringTableFileName().
RoundMagnitude()
double anonymous_namespace{i18n.cpp}::RoundMagnitude (double mag, int digits)
Referenced by DoubleToString().
Variable Documentation
LARGE_UI_DISPLAY_VALUE
constexpr double anonymous_namespace{i18n.cpp}::LARGE_UI_DISPLAY_VALUE = 9.99999999e+9
Referenced by DoubleToString().
SMALL_UI_DISPLAY_VALUE
constexpr double anonymous_namespace{i18n.cpp}::SMALL_UI_DISPLAY_VALUE = 1.0e-6
Referenced by EffectiveSign().
stringtable_access_mutex
std::recursive_mutex anonymous_namespace{i18n.cpp}::stringtable_access_mutex
Referenced by AllStringtableEntries(), FlushLoadedStringTables(), Language(), UserString(), UserStringExists(), and UserStringList().
stringtable_filename_init
bool anonymous_namespace{i18n.cpp}::stringtable_filename_init = false
stringtables
std::map<std::string, std::shared_ptr<const StringTable> > anonymous_namespace{i18n.cpp}::stringtables
Referenced by FlushLoadedStringTables().
UNKNOWN_UI_DISPLAY_VALUE
constexpr double anonymous_namespace{i18n.cpp}::UNKNOWN_UI_DISPLAY_VALUE = std::numeric_limits<double>::infinity()
Referenced by DoubleToString(), and EffectiveSign().