FreeOrion: anonymous_namespace{Fleet.cpp} Namespace Reference
anonymous_namespace{Fleet.cpp} Namespace Reference
Functions
bool HasXShips (const std::function< bool(const std::shared_ptr< const Ship > &)> &pred, const std::set< int > &ship_ids, const ObjectMap &objects)
void InsertFleetWithShips (Fleet &fleet, std::shared_ptr< System > &system)
bool IsCombatShip (const Ship &ship)
void MoveFleetWithShips (Fleet &fleet, double x, double y, ObjectMap &objects)
bool SystemHasNoVisibleStarlanes (int system_id, const ObjectMap &objects)
std::list< int > TruncateRouteToEndAtSystem (const std::list< int > &full_route, const ObjectMap &objects, int last_system)
Return full_route terminates at last_system or before the first system not known to the empire_id.
Variables
const bool ALLOW_ALLIED_SUPPLY = true
const std::set< int > EMPTY_SET
const double FLEET_MOVEMENT_EPSILON = 0.1
const double MAX_SHIP_SPEED = 500.0
Function Documentation
HasXShips()
bool anonymous_namespace{Fleet.cpp}::HasXShips (const std::function< bool(const std::shared_ptr< const Ship > &)> & pred, const std::set< int > & ship_ids, const ObjectMap & objects)
References ALLOW_ALLIED_SUPPLY, ScriptingContext::ContextDiploStatus(), ScriptingContext::ContextObjects(), DebugLogger, ErrorLogger, ObjectMap::find(), ObjectMap::get(), GetEmpire(), ScriptingContext::GetEmpire(), Universe::GetPathfinder(), GetSupplyManager(), InsertFleetWithShips(), INVALID_OBJECT_ID, MAX_SHIP_SPEED, MoveFleetWithShips(), anonymous_namespace{XMLDoc.cpp}::Name, Universe::Objects(), Objects(), ResourceToMeter(), Ship::Resupply(), SupplyManager::SystemHasFleetSupply(), TraceLogger, TruncateRouteToEndAtSystem(), UniverseObjectVisitor::Visit(), and WarnLogger.
InsertFleetWithShips()
void anonymous_namespace{Fleet.cpp}::InsertFleetWithShips (Fleet & fleet, std::shared_ptr< System > & system)
References ObjectMap::find(), and Objects().
Referenced by HasXShips().
IsCombatShip()
bool anonymous_namespace{Fleet.cpp}::IsCombatShip (const Ship & ship)
References ALL_EMPIRES, Ship::CanBombard(), Ship::CanHaveTroops(), ObjectMap::find(), FlexibleFormat(), Ship::HasFighters(), INVALID_OBJECT_ID, Ship::IsArmed(), UserString(), and UserStringNop.
MoveFleetWithShips()
void anonymous_namespace{Fleet.cpp}::MoveFleetWithShips (Fleet & fleet, double x, double y, ObjectMap & objects)
References ObjectMap::find().
Referenced by HasXShips().
SystemHasNoVisibleStarlanes()
bool anonymous_namespace{Fleet.cpp}::SystemHasNoVisibleStarlanes (int system_id, const ObjectMap & objects)
References GetPathfinder().
Referenced by TruncateRouteToEndAtSystem().
TruncateRouteToEndAtSystem()
std::list<int> anonymous_namespace{Fleet.cpp}::TruncateRouteToEndAtSystem (const std::list< int > & full_route, const ObjectMap & objects, int last_system)
Return full_route terminates at last_system or before the first system not known to the empire_id.
References ALL_EMPIRES, ALLOW_ALLIED_SUPPLY, BEFORE_FIRST_TURN, ScriptingContext::ContextObjects(), Meter::Current(), DebugLogger, Effect::Dump(), EmpireKnownObjects(), EMPTY_SET, ErrorLogger, MovePathNode::eta, ObjectMap::find(), FLEET_MOVEMENT_EPSILON, SupplyManager::FleetSupplyableSystemIDs(), ObjectMap::get(), EmpireManager::GetDiplomaticStatus(), ScriptingContext::GetEmpire(), Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), INVALID_OBJECT_ID, Meter::LARGE_VALUE, anonymous_namespace{XMLDoc.cpp}::Name, MovePathNode::object_id, Objects(), ScriptingContext::supply, SystemHasNoVisibleStarlanes(), TraceLogger, UserString(), and VIS_NO_VISIBILITY().
Referenced by HasXShips().
Variable Documentation
ALLOW_ALLIED_SUPPLY
const bool anonymous_namespace{Fleet.cpp}::ALLOW_ALLIED_SUPPLY = true
Referenced by HasXShips(), and TruncateRouteToEndAtSystem().
EMPTY_SET
const std::set<int> anonymous_namespace{Fleet.cpp}::EMPTY_SET
Referenced by TruncateRouteToEndAtSystem().
FLEET_MOVEMENT_EPSILON
const double anonymous_namespace{Fleet.cpp}::FLEET_MOVEMENT_EPSILON = 0.1
Referenced by TruncateRouteToEndAtSystem().
MAX_SHIP_SPEED
const double anonymous_namespace{Fleet.cpp}::MAX_SHIP_SPEED = 500.0
Referenced by HasXShips().