FreeOrion: anonymous_namespace{ShipHull.cpp} Namespace Reference
anonymous_namespace{ShipHull.cpp} Namespace Reference
Functions
void AddRules (GameRules &rules)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
Variables
const float ARBITRARY_LARGE_COST = 999999.9f
const int ARBITRARY_LARGE_TURNS = 999999
bool temp_bool = RegisterGameRules(&AddRules)
Function Documentation
AddRules()
void anonymous_namespace{ShipHull.cpp}::AddRules (GameRules & rules)
References GameRules::Add(), and UserStringNop.
IncreaseMeter() [1/3]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> && increase_vr)
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, and ValueRef::PLUS.
IncreaseMeter() [2/3]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
References IncreaseMeter().
IncreaseMeter() [3/3]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, float base_increase, const std::string & scaling_factor_rule_name)
References ARBITRARY_LARGE_COST, ARBITRARY_LARGE_TURNS, CheckSums::CheckSumCombine(), ScriptingContext::ContextObjects(), tag_parser::description, ObjectMap::get(), GameRules::Get(), ScriptingContext::GetEmpire(), GetGameRules(), ShipHullManager::s_instance, ScriptingContext::source, ValueRef::TIMES, and TraceLogger.
Referenced by IncreaseMeter().
Variable Documentation
ARBITRARY_LARGE_COST
const float anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_COST = 999999.9f
Referenced by IncreaseMeter().
ARBITRARY_LARGE_TURNS
const int anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_TURNS = 999999
Referenced by IncreaseMeter(), and Tech::ResearchTime().
temp_bool
bool anonymous_namespace{ShipHull.cpp}::temp_bool = RegisterGameRules(&AddRules)