FreeOrion: anonymous_namespace{MeterBrowseWnd.cpp} Namespace Reference
anonymous_namespace{MeterBrowseWnd.cpp} Namespace Reference
Classes
struct FighterBoutInfo
Container for return values of ResolveFighterBouts.
class ShipFightersBrowseRow
Functions
std::string ColouredInt (int number, bool prepend=true, GG::Clr clr=ClientUI::StatIncrColor(), GG::Clr neg_clr=ClientUI::StatDecrColor())
Returns a string representation of number wrapped in GG RGBA tags for clr.
std::string ColouredNumber (double number, unsigned int digits=3)
Returns text representation of number wrapped in GG RGBA tags for colour depending on whether number is positive, negative or 0.0.
std::string ColourWrappedtext (const std::string &text, const GG::Clr colour)
Returns text wrapped in GG RGBA tags for specified colour.
const int EDGE_PAD (3)
GG::X FighterBrowseLabelWidth ()
GG::X FighterBrowseListWidth ()
boost::optional< const std::vector< Effect::AccountingInfo > & > GetAccountingInfo (int obj_id, const MeterType &meter_type)
Return the vector of accounting information from obj_id of meter_type.
std::string IntToString (int number, bool prepend=false)
Cast int to string, prepend sign if requested.
GG::X MeterBrowseLabelWidth ()
GG::X MeterBrowseQtyWidth ()
const GG::Y MeterBrowseRowHeight ()
GG::X MeterBrowseValueWidth ()
const std::string & MeterToUserString (MeterType meter_type)
std::map< int, FighterBoutInfo > ResolveFighterBouts (int bay_capacity, int current_docked, float fighter_damage, int limit_to_bout=-1)
Populate fighter state quantities and damages for each combat round until limit_to_bout.
Function Documentation
ColouredInt()
std::string anonymous_namespace{MeterBrowseWnd.cpp}::ColouredInt (int number, bool prepend = true, GG::Clr clr = ClientUI::StatIncrColor(), GG::Clr neg_clr = ClientUI::StatDecrColor())
Returns a string representation of number wrapped in GG RGBA tags for clr.
If number is less than 0, wraps with neg_clr instead.
References ColourWrappedtext(), EDGE_PAD(), and IntToString().
Referenced by ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
ColouredNumber()
std::string anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber (double number, unsigned int digits = 3)
Returns text representation of number wrapped in GG RGBA tags for colour depending on whether number is positive, negative or 0.0.
References ColourWrappedtext(), DoubleToString(), ClientUI::StatDecrColor(), ClientUI::StatIncrColor(), and ClientUI::TextColor().
Referenced by MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), and MeterBrowseWnd::UpdateSummary().
ColourWrappedtext()
std::string anonymous_namespace{MeterBrowseWnd.cpp}::ColourWrappedtext (const std::string & text, const GG::Clr colour)
Returns text wrapped in GG RGBA tags for specified colour.
Referenced by ColouredInt(), ColouredNumber(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
EDGE_PAD()
const int anonymous_namespace{MeterBrowseWnd.cpp}::EDGE_PAD (3)
Referenced by ColouredInt(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction(), MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), MeterBrowseWnd::Render(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
FighterBrowseLabelWidth()
GG::X anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseLabelWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction(), FighterBrowseListWidth(), ShipFightersBrowseWnd::Initialize(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
FighterBrowseListWidth()
GG::X anonymous_namespace{MeterBrowseWnd.cpp}::FighterBrowseListWidth ()
References FighterBrowseLabelWidth(), MeterBrowseQtyWidth(), and MeterBrowseValueWidth().
Referenced by ShipFightersBrowseWnd::Initialize(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
GetAccountingInfo()
boost::optional<const std::vector<Effect::AccountingInfo>&> anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo (int obj_id, const MeterType & meter_type)
Return the vector of accounting information from obj_id of meter_type.
References ErrorLogger, ObjectMap::get(), Universe::GetEffectAccountingMap(), GetUniverse(), and Objects().
Referenced by MeterBrowseWnd::UpdateEffectLabelsAndValues().
IntToString()
std::string anonymous_namespace{MeterBrowseWnd.cpp}::IntToString (int number, bool prepend = false)
Cast int to string, prepend sign if requested.
References to_string().
Referenced by ColouredInt(), anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::ShipFightersBrowseRow(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
MeterBrowseLabelWidth()
GG::X anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseLabelWidth ()
References ClientUI::Pts().
Referenced by MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), and ShipDamageBrowseWnd::UpdateEffectLabelsAndValues().
MeterBrowseQtyWidth()
GG::X anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseQtyWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction(), FighterBrowseListWidth(), ShipFightersBrowseWnd::Initialize(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
MeterBrowseRowHeight()
const GG::Y anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseRowHeight ()
References ClientUI::Pts().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction(), MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), and ShipFightersBrowseWnd::Initialize().
MeterBrowseValueWidth()
GG::X anonymous_namespace{MeterBrowseWnd.cpp}::MeterBrowseValueWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{MeterBrowseWnd.cpp}::ShipFightersBrowseRow::CompleteConstruction(), FighterBrowseListWidth(), MeterBrowseWnd::Initialize(), ShipDamageBrowseWnd::Initialize(), ShipFightersBrowseWnd::Initialize(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), and ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().
MeterToUserString()
const std::string& anonymous_namespace{MeterBrowseWnd.cpp}::MeterToUserString (MeterType meter_type)
References UserString().
Referenced by MeterBrowseWnd::Initialize(), and MeterBrowseWnd::UpdateSummary().
ResolveFighterBouts()
std::map<int, FighterBoutInfo> anonymous_namespace{MeterBrowseWnd.cpp}::ResolveFighterBouts (int bay_capacity, int current_docked, float fighter_damage, int limit_to_bout = -1)
Populate fighter state quantities and damages for each combat round until limit_to_bout.
References GameRules::Get(), and GetGameRules().
Referenced by ShipFightersBrowseWnd::UpdateEffectLabelsAndValues().