FreeOrion: Pending Namespace Reference
Pending Namespace Reference
namespace Pending collection classes and functions used for asynchronously parsing universe types, statistics etc.
Classes
struct Parsing
Helper struct for use with std::async.
struct Pending
Pending holds the std::future results of a T.
Functions
template<typename Func >
auto ParseSynchronously (const Func &parser, const boost::filesystem::path &path) -> Pending< decltype(parser(path))>
Return a Pending<T> constructed with parser and path which executes the parser in the calling thread and stores the result before returning.
template<typename Func >
auto StartAsyncParsing (const Func &parser, const boost::filesystem::path &path) -> Pending< decltype(parser(path))>
Return a Pending<T> constructed with parser and path.
template<typename Func >
auto StartAsyncParsing (Func parser, const boost::filesystem::path &path, std::promise< void > &&barrier) -> Pending< decltype(parser(path))>
Return a Pending<T> constructed with parser and path and notify barrier.
template<typename T >
T & SwapPending (boost::optional< Pending< T >> &pending, T &stored)
If there is a pending parse, wait for it and swap it with the stored value.
template<typename T >
boost::optional< T > WaitForPending (boost::optional< Pending< T >> &pending, bool do_not_care_about_result=false)
Wait for the pending parse to complete.
template<typename T >
boost::optional< T > WaitForPendingUnlocked (Pending< T > &&pending, bool do_not_care_about_result=false)
Detailed Description
namespace Pending collection classes and functions used for asynchronously parsing universe types, statistics etc.
Function Documentation
ParseSynchronously()
template<typename Func > auto Pending::ParseSynchronously (const Func & parser, const boost::filesystem::path & path) -> Pending<decltype(parser(path))>
Return a Pending<T> constructed with parser and path which executes the parser in the calling thread and stores the result before returning.
Referenced by IApp::StartBackgroundParsing().
StartAsyncParsing() [1/2]
template<typename Func > auto Pending::StartAsyncParsing (const Func & parser, const boost::filesystem::path & path) -> Pending<decltype(parser(path))>
Return a Pending<T> constructed with parser and path.
Referenced by IApp::StartBackgroundParsing(), and ServerApp::StartBackgroundParsing().
StartAsyncParsing() [2/2]
template<typename Func > auto Pending::StartAsyncParsing (Func parser, const boost::filesystem::path & path, std::promise< void > && barrier) -> Pending<decltype(parser(path))>
Return a Pending<T> constructed with parser and path and notify barrier.
SwapPending()
template<typename T > T& Pending::SwapPending (boost::optional< Pending< T >> & pending, T & stored)
If there is a pending parse, wait for it and swap it with the stored value.
Return the stored value.
References swap(), and WaitForPendingUnlocked().
Referenced by BuildingTypeManager::CheckPendingBuildingTypes(), FieldTypeManager::CheckPendingFieldTypes(), PolicyManager::CheckPendingPolicies(), ShipHullManager::CheckPendingShipHulls(), ShipPartManager::CheckPendingShipParts(), SpecialsManager::CheckPendingSpecialsTypes(), SpeciesManager::CheckPendingSpeciesTypes(), Universe::EmpireStats(), Universe::InitiallyUnlockedBuildings(), Universe::InitiallyUnlockedFleetPlans(), Universe::InitiallyUnlockedItems(), and Universe::MonsterFleetPlans().
WaitForPending()
template<typename T > boost::optional<T> Pending::WaitForPending (boost::optional< Pending< T >> & pending, bool do_not_care_about_result = false)
Wait for the pending parse to complete.
Set pending to boost::none and return the parsed T. Destroys the shared state in the wrapped std::future. Return boost::none on errors.
References WaitForPendingUnlocked().
Referenced by Encyclopedia::Articles(), anonymous_namespace{ShipDesign.cpp}::CheckPendingAndFillDesignsOrderingAndNameTables(), GameRules::CheckPendingGameRules(), NamedValueRefManager::CheckPendingNamedValueRefs(), and TechManager::CheckPendingTechs().
WaitForPendingUnlocked()
template<typename T > boost::optional<T> Pending::WaitForPendingUnlocked (Pending< T > && pending, bool do_not_care_about_result = false)
References DebugLogger, and ErrorLogger.
Referenced by SwapPending(), and WaitForPending().