FreeOrion: anonymous_namespace{MultiplayerCommon.cpp} Namespace Reference
anonymous_namespace{MultiplayerCommon.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
void AddRules (GameRules &rules)
template<typename T1 >
int GetIdx (const T1 &enum_vals_count, const std::string &seed)
Variables
static char alphanum [] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
bool temp_bool = RegisterOptions(&AddOptions)
bool temp_bool2 = RegisterGameRules(&AddRules)
Function Documentation
AddOptions()
void anonymous_namespace{MultiplayerCommon.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), OptionsDB::AddFlag(), BEGINNER, GetRootDataDir(), GetUserDataDir(), LogLevelValidator(), MANIACAL, IApp::MAX_AI_PLAYERS(), PathToString(), and UserStringNop.
AddRules()
void anonymous_namespace{MultiplayerCommon.cpp}::AddRules (GameRules & rules)
References GameRules::Add().
GetIdx()
template<typename T1 > int anonymous_namespace{MultiplayerCommon.cpp}::GetIdx (const T1 & enum_vals_count, const std::string & seed)
References DebugLogger.
Referenced by GalaxySetupData::GetAge(), GalaxySetupData::GetMonsterFreq(), GalaxySetupData::GetNativeFreq(), GalaxySetupData::GetPlanetDensity(), GalaxySetupData::GetShape(), GalaxySetupData::GetSpecialsFreq(), and GalaxySetupData::GetStarlaneFreq().
Variable Documentation
alphanum
char anonymous_namespace{MultiplayerCommon.cpp}::alphanum[] = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz" static
Referenced by GalaxySetupData::SetSeed().
temp_bool
bool anonymous_namespace{MultiplayerCommon.cpp}::temp_bool = RegisterOptions(&AddOptions)
temp_bool2
bool anonymous_namespace{MultiplayerCommon.cpp}::temp_bool2 = RegisterGameRules(&AddRules)