FreeOrion: anonymous_namespace{SitRepPanel.cpp} Namespace Reference
anonymous_namespace{SitRepPanel.cpp} Namespace Reference
Classes
class ColorEmpire
class SitRepDataPanel
class SitRepLinkText
class SitRepRow
A ListBox::Row subclass used to display SitReps.
Functions
void AddOptions (OptionsDB &db)
Adds options related to SitRepPanel to Options DB.
std::vector< std::string > AllSitRepTemplateStrings ()
std::set< std::string > EmpireSitRepTemplateStrings (int empire_id)
int GetIconSize ()
std::map< int, std::list< SitRepEntry > > GetUnvalidatedSitRepsSortedByTurn (int empire_id)
void HandleLinkClick (const std::string &link_type, const std::string &data)
std::set< std::string > HiddenSitRepTemplateStringsFromOptions ()
std::vector< std::string > OrderedSitrepTemplateStrings ()
void SetHiddenSitRepTemplateStringsInOptions (const std::set< std::string > &set)
constexpr int sitrep_edge_to_content_spacing (sitrep_edge_to_outline_spacing+1+2)
constexpr int sitrep_edge_to_outline_spacing (2)
constexpr int sitrep_row_margin (1)
constexpr int sitrep_spacing (2)
void SnoozeSitRepForNTurns (std::string sitrep_text, int start_turn, int num_turns)
Variables
std::map< std::string, std::string > label_display_map
std::set< std::string > permanently_snoozed_sitreps
std::map< int, std::set< std::string > > snoozed_sitreps
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{SitRepPanel.cpp}::AddOptions (OptionsDB & db)
Adds options related to SitRepPanel to Options DB.
References OptionsDB::Add(), and UserStringNop.
AllSitRepTemplateStrings()
std::vector<std::string> anonymous_namespace{SitRepPanel.cpp}::AllSitRepTemplateStrings ()
References Empires(), EmpireSitRepTemplateStrings(), and OrderedSitrepTemplateStrings().
Referenced by SitRepPanel::FilterClicked().
EmpireSitRepTemplateStrings()
std::set<std::string> anonymous_namespace{SitRepPanel.cpp}::EmpireSitRepTemplateStrings (int empire_id)
References GGHumanClientApp::GetApp(), ClientApp::GetEmpire(), and UserString().
Referenced by AllSitRepTemplateStrings().
GetIconSize()
int anonymous_namespace{SitRepPanel.cpp}::GetIconSize ()
References OptionsDB::Get(), and GetOptionsDB().
Referenced by anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction(), anonymous_namespace{SitRepPanel.cpp}::SitRepRow::CompleteConstruction(), and anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::DoLayout().
GetUnvalidatedSitRepsSortedByTurn()
std::map<int, std::list<SitRepEntry> > anonymous_namespace{SitRepPanel.cpp}::GetUnvalidatedSitRepsSortedByTurn (int empire_id)
References Empires(), and GetEmpire().
Referenced by SitRepPanel::LastClicked(), SitRepPanel::NextClicked(), SitRepPanel::NumVisibleSitrepsThisTurn(), SitRepPanel::PrevClicked(), and SitRepPanel::Update().
HandleLinkClick()
void anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick (const std::string & link_type, const std::string & data)
References TextLinker::BROWSE_PATH_TAG, GGHumanClientApp::BrowsePath(), VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, ErrorLogger, FilenameToPath(), VarText::FLEET_ID_TAG, GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), GetUniverse(), VarText::METER_TYPE_TAG, VarText::PLANET_ID_TAG, VarText::POLICY_TAG, VarText::PREDEFINED_DESIGN_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, ClientUI::ZoomToBuilding(), ClientUI::ZoomToBuildingType(), ClientUI::ZoomToCombatLog(), ClientUI::ZoomToEmpire(), ClientUI::ZoomToEncyclopediaEntry(), ClientUI::ZoomToFleet(), ClientUI::ZoomToMeterTypeArticle(), ClientUI::ZoomToPlanet(), ClientUI::ZoomToPolicy(), ClientUI::ZoomToShip(), ClientUI::ZoomToShipDesign(), ClientUI::ZoomToShipHull(), ClientUI::ZoomToShipPart(), ClientUI::ZoomToSpecial(), ClientUI::ZoomToSpecies(), ClientUI::ZoomToSystem(), and ClientUI::ZoomToTech().
Referenced by anonymous_namespace{SitRepPanel.cpp}::SitRepDataPanel::CompleteConstruction().
HiddenSitRepTemplateStringsFromOptions()
std::set<std::string> anonymous_namespace{SitRepPanel.cpp}::HiddenSitRepTemplateStringsFromOptions ()
References OptionsDB::Get(), and GetOptionsDB().
OrderedSitrepTemplateStrings()
std::vector<std::string> anonymous_namespace{SitRepPanel.cpp}::OrderedSitrepTemplateStrings ()
References UserString().
Referenced by AllSitRepTemplateStrings(), and SitRepPanel::Update().
SetHiddenSitRepTemplateStringsInOptions()
void anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions (const std::set< std::string > & set)
References OptionsDB::Commit(), GetOptionsDB(), and OptionsDB::Set().
Referenced by SitRepPanel::DismissalMenu(), and SitRepPanel::FilterClicked().
sitrep_edge_to_content_spacing()
constexpr int anonymous_namespace{SitRepPanel.cpp}::sitrep_edge_to_content_spacing (sitrep_edge_to_outline_spacing+1+ 2)
sitrep_edge_to_outline_spacing()
constexpr int anonymous_namespace{SitRepPanel.cpp}::sitrep_edge_to_outline_spacing (2)
sitrep_row_margin()
constexpr int anonymous_namespace{SitRepPanel.cpp}::sitrep_row_margin (1)
sitrep_spacing()
constexpr int anonymous_namespace{SitRepPanel.cpp}::sitrep_spacing (2)
SnoozeSitRepForNTurns()
void anonymous_namespace{SitRepPanel.cpp}::SnoozeSitRepForNTurns (std::string sitrep_text, int start_turn, int num_turns)
References anonymous_namespace{EncyclopediaParser.cpp}::insert.
Referenced by SitRepPanel::DismissalMenu().
Variable Documentation
label_display_map
std::map<std::string, std::string> anonymous_namespace{SitRepPanel.cpp}::label_display_map
Referenced by SitRepPanel::FilterClicked().
permanently_snoozed_sitreps
std::set<std::string> anonymous_namespace{SitRepPanel.cpp}::permanently_snoozed_sitreps
Referenced by SitRepPanel::DismissalMenu(), and SitRepPanel::IsSitRepInvalid().
snoozed_sitreps
std::map<int, std::set<std::string> > anonymous_namespace{SitRepPanel.cpp}::snoozed_sitreps
Referenced by SitRepPanel::DismissalMenu(), SitRepPanel::IgnoreSitRep(), and SitRepPanel::IsSitRepInvalid().
temp_bool
bool anonymous_namespace{SitRepPanel.cpp}::temp_bool = RegisterOptions(&AddOptions)