FreeOrion: anonymous_namespace{CombatSystem.cpp} Namespace Reference
anonymous_namespace{CombatSystem.cpp} Namespace Reference
Classes
struct AutoresolveInfo
A collection of information the autoresolution must keep around.
struct EmpireCombatInfo
struct PartAttackInfo
Functions
void AddAllObjectsSet (ObjectMap &obj_map, Condition::ObjectSet &condition_non_targets)
void Attack (const std::shared_ptr< UniverseObject > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< UniverseObject > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr platform_event, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
void AttackFighterFighter (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
void AttackFighterPlanet (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event)
void AttackFighterShip (const std::shared_ptr< Fighter > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, AttacksEventPtr &attacks_event)
void AttackPlanetFighter (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AttackPlanetPlanet (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AttackPlanetShip (const std::shared_ptr< Planet > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AttackShipFighter (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Fighter > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AttackShipPlanet (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Planet > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void AttackShipShip (const std::shared_ptr< Ship > &attacker, const PartAttackInfo &weapon, const std::shared_ptr< Ship > &target, CombatInfo &combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr &combat_event)
void CombatRound (AutoresolveInfo &combat_state)
DeclareThreadSafeLogger (combat)
std::shared_ptr< const Empire > GetEmpire (int id, const CombatInfo &combat_info)
std::map< int, float > GetEmpiresDetectionStrengths (const CombatInfo &combat_info)
Visibility GetObjectVisibilityByEmpire (int obj_id, int empire_id, const CombatInfo &combat_info)
std::vector< PartAttackInfo > GetWeapons (const std::shared_ptr< UniverseObject > &attacker)
void IncreaseStoredFighterCount (std::shared_ptr< Ship > &ship, float recovered_fighters)
void LaunchFighters (std::shared_ptr< UniverseObject > attacker, const std::vector< PartAttackInfo > &weapons, AutoresolveInfo &combat_state, int round, FighterLaunchesEventPtr &launches_event)
bool ObjectCanAttack (const std::shared_ptr< const UniverseObject > &obj, const ObjectMap &objects)
void RecoverFighters (CombatInfo &combat_info, int bout, FighterLaunchesEventPtr &launches_event)
void ReduceStoredFighterCount (std::shared_ptr< Ship > &ship, float launched_fighters)
std::vector< PartAttackInfo > ShipWeaponsStrengths (const std::shared_ptr< const Ship > &ship)
void ShootAllWeapons (const std::shared_ptr< UniverseObject > &attacker, AutoresolveInfo &combat_state, int round, AttacksEventPtr &attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr &platform_event, std::shared_ptr< FightersAttackFightersEvent > &fighter_on_fighter_event)
const Condition::Condition * SpeciesTargettingCondition (const std::shared_ptr< UniverseObject > &attacker)
Condition::Condition * VisibleEnemyOfOwnerCondition ()
Variables
const std::unique_ptr< Condition::Condition > if_source_is_planet_then_ships_else_all
const std::unique_ptr< Condition::Condition > is_enemy_ship
const std::unique_ptr< Condition::Condition > is_enemy_ship_fighter_or_armed_planet
const std::unique_ptr< Condition::Condition > is_enemy_ship_or_fighter
Function Documentation
AddAllObjectsSet()
void anonymous_namespace{CombatSystem.cpp}::AddAllObjectsSet (ObjectMap & obj_map, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingObjects().
Referenced by ShootAllWeapons().
Attack()
void anonymous_namespace{CombatSystem.cpp}::Attack (const std::shared_ptr< UniverseObject > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< UniverseObject > & target, CombatInfo & combat_info, int bout, int round, AttacksEventPtr & attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr platform_event, std::shared_ptr< FightersAttackFightersEvent > & fighter_on_fighter_event)
References AttackFighterFighter(), AttackFighterPlanet(), AttackFighterShip(), AttackPlanetFighter(), AttackPlanetPlanet(), AttackPlanetShip(), AttackShipFighter(), AttackShipPlanet(), and AttackShipShip().
Referenced by ShipDesign::IsMonster(), and ShootAllWeapons().
AttackFighterFighter()
void anonymous_namespace{CombatSystem.cpp}::AttackFighterFighter (const std::shared_ptr< Fighter > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Fighter > & target, CombatInfo & combat_info, int bout, int round, std::shared_ptr< FightersAttackFightersEvent > & fighter_on_fighter_event)
References DebugLogger.
Referenced by Attack().
AttackFighterPlanet()
void anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet (const std::shared_ptr< Fighter > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Planet > & target, CombatInfo & combat_info, int bout, int round, AttacksEventPtr & attacks_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
AttackFighterShip()
void anonymous_namespace{CombatSystem.cpp}::AttackFighterShip (const std::shared_ptr< Fighter > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Ship > & target, CombatInfo & combat_info, int bout, int round, AttacksEventPtr & attacks_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
AttackPlanetFighter()
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetFighter (const std::shared_ptr< Planet > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Fighter > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References Meter::Current(), DebugLogger, and anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name.
Referenced by Attack().
AttackPlanetPlanet()
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetPlanet (const std::shared_ptr< Planet > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Planet > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, and anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name.
Referenced by Attack().
AttackPlanetShip()
void anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip (const std::shared_ptr< Planet > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Ship > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
AttackShipFighter()
void anonymous_namespace{CombatSystem.cpp}::AttackShipFighter (const std::shared_ptr< Ship > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Fighter > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References DebugLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::part_attack, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
AttackShipPlanet()
void anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet (const std::shared_ptr< Ship > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Planet > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::part_attack, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
AttackShipShip()
void anonymous_namespace{CombatSystem.cpp}::AttackShipShip (const std::shared_ptr< Ship > & attacker, const PartAttackInfo & weapon, const std::shared_ptr< Ship > & target, CombatInfo & combat_info, int bout, int round, WeaponsPlatformEvent::WeaponsPlatformEventPtr & combat_event)
References Meter::AddToCurrent(), Meter::Current(), CombatInfo::damaged_object_ids, DebugLogger, ErrorLogger, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::part_attack, anonymous_namespace{CombatSystem.cpp}::PartAttackInfo::ship_part_name, and CombatInfo::turn.
Referenced by Attack().
CombatRound()
void anonymous_namespace{CombatSystem.cpp}::CombatRound (AutoresolveInfo & combat_state)
Remove all who died in the bout
References ALL_EMPIRES, CombatInfo::bout, CombatInfo::combat_events, anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::combat_info, anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), DebugLogger, CombatInfo::empire_ids, CombatInfo::empire_object_visibility, GameRules::Get(), GetGameRules(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::GetShuffledValidAttackerIDs(), GetWeapons(), LaunchFighters(), ObjectCanAttack(), CombatInfo::objects, ShootAllWeapons(), TraceLogger, and anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::valid_attacker_object_ids.
Referenced by AutoResolveCombat().
DeclareThreadSafeLogger()
anonymous_namespace{CombatSystem.cpp}::DeclareThreadSafeLogger (combat)
GetEmpire()
std::shared_ptr<const Empire> anonymous_namespace{CombatSystem.cpp}::GetEmpire (int id, const CombatInfo & combat_info)
References CombatInfo::empires.
GetEmpiresDetectionStrengths()
std::map<int, float> anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths (const CombatInfo & combat_info)
References ALL_EMPIRES, Meter::Current(), CombatInfo::empire_ids, ErrorLogger, GetEmpire(), and CombatInfo::GetMonsterDetection().
Referenced by CombatInfo::InitializeObjectVisibility().
GetObjectVisibilityByEmpire()
Visibility anonymous_namespace{CombatSystem.cpp}::GetObjectVisibilityByEmpire (int obj_id, int empire_id, const CombatInfo & combat_info)
References CombatInfo::empire_object_visibility, and VIS_NO_VISIBILITY().
Referenced by AutomaticallyChosenColonyShip(), ColonizeOrder::Check(), InvadeOrder::Check(), BombardOrder::Check(), ObjectMap::CopyObject(), CombatInfo::InitializeObjectVisibility(), Universe::NumShipDesigns(), ObjectListBox::ObjectShown(), and BuildingIndicator::Render().
GetWeapons()
std::vector<PartAttackInfo> anonymous_namespace{CombatSystem.cpp}::GetWeapons (const std::shared_ptr< UniverseObject > & attacker)
References DebugLogger, ShipWeaponsStrengths(), TraceLogger, and UserStringNop.
Referenced by CombatRound(), and ShootAllWeapons().
IncreaseStoredFighterCount()
void anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount (std::shared_ptr< Ship > & ship, float recovered_fighters)
References DebugLogger, ErrorLogger, GetShipPart(), and ShipDesign::Parts().
Referenced by RecoverFighters().
LaunchFighters()
void anonymous_namespace{CombatSystem.cpp}::LaunchFighters (std::shared_ptr< UniverseObject > attacker, const std::vector< PartAttackInfo > & weapons, AutoresolveInfo & combat_state, int round, FighterLaunchesEventPtr & launches_event)
References anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), CombatInfo::bout, anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::combat_info, DebugLogger, FlexibleFormat(), ScriptingContext::GetEmpire(), ReduceStoredFighterCount(), Ship::SpeciesName(), TraceLogger, CombatInfo::turn, and UserString().
Referenced by CombatRound().
ObjectCanAttack()
bool anonymous_namespace{CombatSystem.cpp}::ObjectCanAttack (const std::shared_ptr< const UniverseObject > & obj, const ObjectMap & objects)
References ObjectMap::get().
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), CombatRound(), and anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackers().
RecoverFighters()
void anonymous_namespace{CombatSystem.cpp}::RecoverFighters (CombatInfo & combat_info, int bout, FighterLaunchesEventPtr & launches_event)
References DebugLogger, CombatInfo::destroyed_object_ids, ErrorLogger, IncreaseStoredFighterCount(), and CombatInfo::objects.
Referenced by AutoResolveCombat().
ReduceStoredFighterCount()
void anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount (std::shared_ptr< Ship > & ship, float launched_fighters)
References ErrorLogger, GetShipPart(), and ShipDesign::Parts().
Referenced by LaunchFighters().
ShipWeaponsStrengths()
std::vector<PartAttackInfo> anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths (const std::shared_ptr< const Ship > & ship)
References GetShipDesign(), GetShipPart(), ShipDesign::Parts(), TraceLogger, UserString(), and UserStringExists().
Referenced by GetWeapons(), and anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasUnlauchedArmedFighters().
ShootAllWeapons()
void anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons (const std::shared_ptr< UniverseObject > & attacker, AutoresolveInfo & combat_state, int round, AttacksEventPtr & attacks_event, WeaponsPlatformEvent::WeaponsPlatformEventPtr & platform_event, std::shared_ptr< FightersAttackFightersEvent > & fighter_on_fighter_event)
References AddAllObjectsSet(), Attack(), CombatInfo::bout, anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::combat_info, ScriptingContext::ContextObjects(), DebugLogger, ScriptingContext::diplo_statuses, ScriptingContext::empire_object_vis, ScriptingContext::Empires(), ErrorLogger, GetWeapons(), Condition::MATCHES, CombatInfo::objects, RandInt(), ObjectMap::size(), SpeciesTargettingCondition(), TraceLogger, and VIS_NO_VISIBILITY().
Referenced by CombatRound().
SpeciesTargettingCondition()
const Condition::Condition* anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition (const std::shared_ptr< UniverseObject > & attacker)
References Species::CombatTargets(), GetSpecies(), and ScriptingContext::species.
Referenced by ShootAllWeapons().
VisibleEnemyOfOwnerCondition()
Condition::Condition* anonymous_namespace{CombatSystem.cpp}::VisibleEnemyOfOwnerCondition ()
References ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, Condition::NOT_EQUAL, and ValueRef::SOURCE_REFERENCE.
Variable Documentation
if_source_is_planet_then_ships_else_all
const std::unique_ptr<Condition::Condition> anonymous_namespace{CombatSystem.cpp}::if_source_is_planet_then_ships_else_all
Initial value:
=
        std::make_unique<Condition::Or>(
            std::make_unique<Condition::And>(
                std::make_unique<Condition::Number>(
                    std::make_unique<ValueRef::Constant<int>>(1),
                    nullptr,
                    std::make_unique<Condition::And>(
                        std::make_unique<Condition::Source>(),
                        std::make_unique<Condition::Type>(UniverseObjectType::OBJ_PLANET)
                    )
                ),
                std::make_unique<Condition::Type>(UniverseObjectType::OBJ_SHIP)
            ),
            std::make_unique<Condition::Number>(
                nullptr,
                std::make_unique<ValueRef::Constant<int>>(0),
                std::make_unique<Condition::And>(
                    std::make_unique<Condition::Source>(),
                    std::make_unique<Condition::Type>(UniverseObjectType::OBJ_PLANET)
                )
            )
        )
is_enemy_ship
const std::unique_ptr<Condition::Condition> anonymous_namespace{CombatSystem.cpp}::is_enemy_ship
Initial value:
=
        std::make_unique<Condition::And>(
            std::make_unique<Condition::Type>(UniverseObjectType::OBJ_SHIP),
            std::make_unique<Condition::Not>(
                std::make_unique<Condition::MeterValue>(
                    MeterType::METER_STRUCTURE,
                    nullptr,
                    std::make_unique<ValueRef::Constant<double>>(0.0))),
            std::unique_ptr<Condition::Condition>{VisibleEnemyOfOwnerCondition()})
is_enemy_ship_fighter_or_armed_planet
const std::unique_ptr<Condition::Condition> anonymous_namespace{CombatSystem.cpp}::is_enemy_ship_fighter_or_armed_planet
is_enemy_ship_or_fighter
const std::unique_ptr<Condition::Condition> anonymous_namespace{CombatSystem.cpp}::is_enemy_ship_or_fighter
Initial value:
=
        std::make_unique<Condition::And>(
            std::make_unique<Condition::Or>(
                std::make_unique<Condition::And>(
                    std::make_unique<Condition::Type>(UniverseObjectType::OBJ_SHIP),
                    std::make_unique<Condition::Not>(
                        std::make_unique<Condition::MeterValue>(
                            MeterType::METER_STRUCTURE,
                            nullptr,
                            std::make_unique<ValueRef::Constant<double>>(0.0)))),
                std::make_unique<Condition::Type>(UniverseObjectType::OBJ_FIGHTER)),
            std::unique_ptr<Condition::Condition>{VisibleEnemyOfOwnerCondition()})