FreeOrion: anonymous_namespace{ConfigWrapper.cpp} Namespace Reference
anonymous_namespace{ConfigWrapper.cpp} Namespace Reference
Functions
boost::python::object GetOptionsDBOptionBool (std::string const &option)
boost::python::object GetOptionsDBOptionDouble (std::string const &option)
boost::python::object GetOptionsDBOptionInt (std::string const &option)
boost::python::object GetOptionsDBOptionStr (std::string const &option)
boost::python::str GetUserConfigDirWrapper ()
boost::python::str GetUserDataDirWrapper ()
Function Documentation
GetOptionsDBOptionBool()
boost::python::object anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionBool (std::string const & option)
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapConfig().
GetOptionsDBOptionDouble()
boost::python::object anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionDouble (std::string const & option)
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapConfig().
GetOptionsDBOptionInt()
boost::python::object anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionInt (std::string const & option)
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapConfig().
GetOptionsDBOptionStr()
boost::python::object anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionStr (std::string const & option)
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapConfig().
GetUserConfigDirWrapper()
boost::python::str anonymous_namespace{ConfigWrapper.cpp}::GetUserConfigDirWrapper ()
References GetUserConfigDir(), and PathToString().
Referenced by FreeOrionPython::WrapConfig().
GetUserDataDirWrapper()
boost::python::str anonymous_namespace{ConfigWrapper.cpp}::GetUserDataDirWrapper ()
References GetUserDataDir(), and PathToString().
Referenced by FreeOrionPython::WrapConfig().