FreeOrion: anonymous_namespace{ClientUI.cpp} Namespace Reference
anonymous_namespace{ClientUI.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
template<typename OptionType , typename PredicateType >
void ConditionalConnectOption (const std::string &option_name, const OptionsDB::OptionChangedSignalType::slot_type &slot, OptionType ref_val, PredicateType pred)
template<typename OptionType , typename PredicateType >
void ConditionalForward (const std::string &option_name, const OptionsDB::OptionChangedSignalType::slot_type &slot, OptionType ref_val, PredicateType pred)
const GG::X MESSAGE_PANEL_WIDTH (345)
const GG::Y PANEL_HEIGHT (160)
const GG::X PLAYER_LIST_PANEL_WIDTH (445)
const std::vector< GG::UnicodeCharset > & RequiredCharsets ()
Variables
const std::string MESSAGE_WND_NAME = "map.messages"
const std::string PLAYER_LIST_WND_NAME = "map.empires"
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{ClientUI.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), GetRootDataDir(), and UserStringNop.
ConditionalConnectOption()
template<typename OptionType , typename PredicateType > void anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption (const std::string & option_name, const OptionsDB::OptionChangedSignalType::slot_type & slot, OptionType ref_val, PredicateType pred)
References GetOptionsDB(), and OptionsDB::OptionChangedSignal().
Referenced by ClientUI::ClientUI().
ConditionalForward()
template<typename OptionType , typename PredicateType > void anonymous_namespace{ClientUI.cpp}::ConditionalForward (const std::string & option_name, const OptionsDB::OptionChangedSignalType::slot_type & slot, OptionType ref_val, PredicateType pred)
References GetOptionsDB().
MESSAGE_PANEL_WIDTH()
const GG::X anonymous_namespace{ClientUI.cpp}::MESSAGE_PANEL_WIDTH (345)
Referenced by ClientUI::InitializeWindows().
PANEL_HEIGHT()
const GG::Y anonymous_namespace{ClientUI.cpp}::PANEL_HEIGHT (160)
Referenced by ClientUI::InitializeWindows(), and BuildDesignatorWnd::InitializeWindows().
PLAYER_LIST_PANEL_WIDTH()
const GG::X anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_PANEL_WIDTH (445)
Referenced by ClientUI::InitializeWindows().
RequiredCharsets()
const std::vector<GG::UnicodeCharset>& anonymous_namespace{ClientUI.cpp}::RequiredCharsets ()
References DebugLogger, OptionsDB::Get(), OptionsDB::GetDefault(), GetOptionsDB(), and to_string().
Referenced by ClientUI::GetBoldFont(), ClientUI::GetFont(), and ClientUI::GetTitleFont().
Variable Documentation
MESSAGE_WND_NAME
const std::string anonymous_namespace{ClientUI.cpp}::MESSAGE_WND_NAME = "map.messages"
Referenced by ClientUI::GetMessageWnd(), ClientUI::HandleFullscreenSwitch(), and ClientUI::HandleSizeChange().
PLAYER_LIST_WND_NAME
const std::string anonymous_namespace{ClientUI.cpp}::PLAYER_LIST_WND_NAME = "map.empires"
Referenced by ClientUI::GetPlayerListWnd().
temp_bool
bool anonymous_namespace{ClientUI.cpp}::temp_bool = RegisterOptions(&AddOptions)