FreeOrion: anonymous_namespace{ResourceBrowseWnd.cpp} Namespace Reference
anonymous_namespace{ResourceBrowseWnd.cpp} Namespace Reference
Functions
const GG::X BrowseTextWidth ()
const int EDGE_PAD (3)
const GG::Y ICON_BROWSE_ICON_HEIGHT (64)
Function Documentation
BrowseTextWidth()
const GG::X anonymous_namespace{ResourceBrowseWnd.cpp}::BrowseTextWidth ()
References FontBasedUpscale().
Referenced by ResourceBrowseWnd::CompleteConstruction(), and WastedStockpiledResourceBrowseWnd::CompleteConstruction().
EDGE_PAD()
const int anonymous_namespace{ResourceBrowseWnd.cpp}::EDGE_PAD (3)
Referenced by ResourceBrowseWnd::CompleteConstruction(), and WastedStockpiledResourceBrowseWnd::CompleteConstruction().
ICON_BROWSE_ICON_HEIGHT()
const GG::Y anonymous_namespace{ResourceBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT (64)