FreeOrion: NamedValueRefManager.h File Reference
NamedValueRefManager.h File Reference
#include "ValueRef.h"
Classes
class NamedValueRefManager
Holds all FreeOrion named ValueRefs. ValueRefs may be looked up by name.
struct ValueRef::NamedRef< T >
The NamedRef class.
Namespaces
ValueRef
Functions
FO_COMMON_API auto GetNamedValueRefManager () -> NamedValueRefManager &
Returns the singleton manager for named value refs.
template<typename T >
FO_COMMON_API auto GetValueRef (const std::string &name) -> ValueRef::ValueRef< T > *const
Returns the ValueRef object registered with the given name in the registry matching the given type T.
FO_COMMON_API auto GetValueRefBase (const std::string &name) -> ValueRef::ValueRefBase *const
Returns the ValueRef object registered with the given name.
template<typename T >
FO_COMMON_API void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< T >> &&vref)
Register and take possesion of the ValueRef object vref under the given name.
Function Documentation
GetNamedValueRefManager()
FO_COMMON_API auto GetNamedValueRefManager () -> NamedValueRefManager &
Returns the singleton manager for named value refs.
References NamedValueRefManager::GetNamedValueRefManager().
Referenced by CheckSumContent(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires().
GetValueRef()
template<typename T > FO_COMMON_API auto GetValueRef (const std::string & name) -> ValueRef::ValueRef< T > *const
Returns the ValueRef object registered with the given name in the registry matching the given type T.
If no such ValueRef exists, nullptr is returned instead.
References NamedValueRefManager::GetNamedValueRefManager(), and NamedValueRefManager::GetValueRef().
GetValueRefBase()
FO_COMMON_API auto GetValueRefBase (const std::string & name) -> ValueRef::ValueRefBase *const
Returns the ValueRef object registered with the given name.
If no such ValueRef exists, nullptr is returned instead.
RegisterValueRef()
template<typename T > FO_COMMON_API void RegisterValueRef (std::string name, std::unique_ptr< ValueRef::ValueRef< T >> && vref)
Register and take possesion of the ValueRef object vref under the given name.
References NamedValueRefManager::GetNamedValueRefManager(), NamedValueRefManager::GetValueRef(), and NamedValueRefManager::RegisterValueRef().