FreeOrion: anonymous_namespace{GovernmentWnd.cpp} Namespace Reference
anonymous_namespace{GovernmentWnd.cpp} Namespace Reference
Classes
class AvailabilityManager
A class to allow the storage of the state of a GUI availabilty filter and the querying of that state WRT a policy.
Functions
std::vector< std::pair< std::string, int > > ConcatenatedCategorySlots (int empire_id)
const int PAD (3)
const GG::Y POLICY_CONTROL_HEIGHT (54)
const GG::X POLICY_CONTROL_WIDTH (54)
std::shared_ptr< GG::Texture > PolicyBackgroundTexture (const Policy *policy)
Returns background texture with which to render a PolicyControl, depending on the category of slot that the indicated policy can be put into.
std::shared_ptr< GG::BrowseInfoWnd > PolicyBroseWnd (const std::string &policy_name)
const GG::Y SLOT_CONTROL_HEIGHT (60)
const GG::X SLOT_CONTROL_WIDTH (60)
std::shared_ptr< GG::Texture > SlotBackgroundTexture (const std::string &category)
Returns texture with which to render a PolicySlotControl, depending on category.
Variables
const std::string EMPTY_STRING = ""
const std::string POLICY_CONTROL_DROP_TYPE_STRING = "Policy Control"
Function Documentation
ConcatenatedCategorySlots()
std::vector<std::pair<std::string, int> > anonymous_namespace{GovernmentWnd.cpp}::ConcatenatedCategorySlots (int empire_id)
References GetEmpire().
Referenced by GovernmentWnd::MainPanel::Populate().
PAD()
const int anonymous_namespace{GovernmentWnd.cpp}::PAD (3)
Referenced by GovernmentWnd::MainPanel::DoLayout(), PoliciesListBox::Populate(), and PoliciesListBox::SizeMove().
POLICY_CONTROL_HEIGHT()
const GG::Y anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_HEIGHT (54)
Referenced by PolicyControl::CompleteConstruction().
POLICY_CONTROL_WIDTH()
const GG::X anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_WIDTH (54)
Referenced by PolicyControl::CompleteConstruction().
PolicyBackgroundTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{GovernmentWnd.cpp}::PolicyBackgroundTexture (const Policy * policy)
Returns background texture with which to render a PolicyControl, depending on the category of slot that the indicated policy can be put into.
References ClientUI::ArtDir(), Policy::Category(), and ClientUI::GetTexture().
Referenced by PolicyControl::CompleteConstruction().
PolicyBroseWnd()
std::shared_ptr<GG::BrowseInfoWnd> anonymous_namespace{GovernmentWnd.cpp}::PolicyBroseWnd (const std::string & policy_name)
References Policy::AdoptionCost(), Policy::Category(), Policy::Description(), ClientApp::EmpireID(), FlexibleFormat(), GGHumanClientApp::GetApp(), GetEmpire(), GetPolicy(), ClientUI::PolicyIcon(), Policy::ShortDescription(), and UserString().
Referenced by PolicyControl::CompleteConstruction().
SLOT_CONTROL_HEIGHT()
const GG::Y anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_HEIGHT (60)
Referenced by PolicyControl::CompleteConstruction(), PolicySlotControl::CompleteConstruction(), and PoliciesListBox::Populate().
SLOT_CONTROL_WIDTH()
const GG::X anonymous_namespace{GovernmentWnd.cpp}::SLOT_CONTROL_WIDTH (60)
Referenced by PolicyControl::CompleteConstruction(), PolicySlotControl::CompleteConstruction(), PoliciesListBox::Populate(), and PoliciesListBox::SizeMove().
SlotBackgroundTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{GovernmentWnd.cpp}::SlotBackgroundTexture (const std::string & category)
Returns texture with which to render a PolicySlotControl, depending on category.
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by PolicySlotControl::CompleteConstruction().
Variable Documentation
EMPTY_STRING
const std::string anonymous_namespace{GovernmentWnd.cpp}::EMPTY_STRING = ""
Referenced by PolicyControl::PolicyName(), and GovernmentWnd::MainPanel::SetPolicy().
POLICY_CONTROL_DROP_TYPE_STRING
const std::string anonymous_namespace{GovernmentWnd.cpp}::POLICY_CONTROL_DROP_TYPE_STRING = "Policy Control"
Referenced by PolicyControl::CompleteConstruction(), PoliciesListBox::DropsAcceptable(), and PolicySlotControl::DropsAcceptable().