FreeOrion: anonymous_namespace{Empire.cpp} Namespace Reference
anonymous_namespace{Empire.cpp} Namespace Reference
Functions
float CalculateNewStockpile (int empire_id, float starting_stockpile, const std::map< std::set< int >, float > &available_pp, const std::map< std::set< int >, float > &allocated_pp, const std::map< std::set< int >, float > &allocated_stockpile_pp)
float CalculateProductionPerTurnLimit (const ProductionQueue::Element &queue_element, float item_cost, int build_turns)
float GetQueueFrontloadFactor ()
float GetQueueToppingFactor ()
void SanitizeResearchQueue (ResearchQueue &queue)
void SetProdQueueElementSpending (std::map< std::set< int >, float > available_pp, float available_stockpile, const std::vector< std::set< int >> &queue_element_resource_sharing_object_groups, const std::map< std::pair< ProductionQueue::ProductionItem, int >, std::pair< float, int >> &queue_item_costs_and_times, const std::vector< bool > &is_producible, ProductionQueue::QueueType &queue, std::map< std::set< int >, float > &allocated_pp, std::map< std::set< int >, float > &allocated_stockpile_pp, int &projects_in_progress, bool simulating)
void SetTechQueueElementSpending (float RPs, const std::map< std::string, float > &research_progress, const std::map< std::string, TechStatus > &research_status, ResearchQueue::QueueType &queue, float &total_RPs_spent, int &projects_in_progress, int empire_id)
Variables
const std::string EMPTY_STRING
const float EPSILON = 0.01f
Function Documentation
float anonymous_namespace{Empire.cpp}::CalculateNewStockpile (int empire_id, float starting_stockpile, const std::map< std::set< int >, float > & available_pp, const std::map< std::set< int >, float > & allocated_pp, const std::map< std::set< int >, float > & allocated_stockpile_pp)
References ErrorLogger, GetEmpire(), Empire::GetProductionQueue(), if(), ProductionQueue::StockpileCapacity(), and TraceLogger.
Referenced by ProductionQueue::Update().
float anonymous_namespace{Empire.cpp}::CalculateProductionPerTurnLimit (const ProductionQueue::Element & queue_element, float item_cost, int build_turns)
References ProductionQueue::Element::blocksize, GetQueueFrontloadFactor(), GetQueueToppingFactor(), ProductionQueue::Element::progress, and ProductionQueue::Element::remaining.
Referenced by SetProdQueueElementSpending().
float anonymous_namespace{Empire.cpp}::GetQueueFrontloadFactor ()
References UserString(), and UserStringExists().
Referenced by CalculateProductionPerTurnLimit().
float anonymous_namespace{Empire.cpp}::GetQueueToppingFactor ()
References UserString(), and UserStringExists().
Referenced by CalculateProductionPerTurnLimit().
void anonymous_namespace{Empire.cpp}::SanitizeResearchQueue (ResearchQueue & queue)
References ResearchQueue::begin(), DebugLogger, ResearchQueue::EmpireID(), ResearchQueue::end(), ResearchQueue::erase(), and AIInterface::GetTech().
Referenced by Empire::CheckResearchProgress().
void anonymous_namespace{Empire.cpp}::SetProdQueueElementSpending (std::map< std::set< int >, float > available_pp, float available_stockpile, const std::vector< std::set< int >> & queue_element_resource_sharing_object_groups, const std::map< std::pair< ProductionQueue::ProductionItem, int >, std::pair< float, int >> & queue_item_costs_and_times, const std::vector< bool > & is_producible, ProductionQueue::QueueType & queue, std::map< std::set< int >, float > & allocated_pp, std::map< std::set< int >, float > & allocated_stockpile_pp, int & projects_in_progress, bool simulating)
Sets the allocated_pp value for each Element in the passed ProductionQueue queue. Elements are allocated PP based on their need, the limits they can be given per turn, and the amount available at their production location (which is itself limited by the resource supply system groups that are able to exchange resources with the build location and the amount of minerals and industry produced in the group). Elements will not receive funding if they cannot be produced by the empire with the indicated empire_id this turn at their build location. Also checks if elements will be completed this turn.
References CalculateProductionPerTurnLimit(), ErrorLogger, if(), INVALID_OBJECT_ID, and TraceLogger.
Referenced by ProductionQueue::Update().
void anonymous_namespace{Empire.cpp}::SetTechQueueElementSpending (float RPs, const std::map< std::string, float > & research_progress, const std::map< std::string, TechStatus > & research_status, ResearchQueue::QueueType & queue, float & total_RPs_spent, int & projects_in_progress, int empire_id)
sets the .allocated_rp, value for each Tech in the queue. Only sets nonzero funding to a Tech if it is researchable this turn. Also determines total number of spent RP (returning by reference in total_RPs_spent)
References DebugLogger, ErrorLogger, AIInterface::GetTech(), Tech::PerTurnCost(), and Tech::ResearchCost().
Referenced by ResearchQueue::Update().
Variable Documentation
const std::string anonymous_namespace{Empire.cpp}::EMPTY_STRING
Referenced by System::ApparentName(), SitRepEntry::GetDataString(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Empire::LeastExpensiveEnqueuedTech(), Empire::LeastExpensiveResearchableTech(), Empire::MostExpensiveEnqueuedTech(), Empire::MostExpensiveResearchableTech(), Empire::MostRPCostLeftEnqueuedTech(), Empire::MostRPCostLeftResearchableTech(), Empire::MostRPSpentEnqueuedTech(), Empire::MostRPSpentResearchableTech(), Empire::TopPriorityEnqueuedTech(), and Empire::TopPriorityResearchableTech().
const float anonymous_namespace{Empire.cpp}::EPSILON = 0.01f
Referenced by Empire::CheckProductionProgress(), Empire::CheckResearchProgress(), ResearchQueue::Update(), and ProductionQueue::Update().