FreeOrion: anonymous_namespace{SaveLoad.cpp} Namespace Reference
anonymous_namespace{SaveLoad.cpp} Namespace Reference
Functions
const std::string BINARY_MARKER ("binary")
void CompileSaveGamePreviewData (const ServerSaveGameData &server_save_game_data, const std::vector< PlayerSaveGameData > &player_save_game_data, const std::map< int, SaveGameEmpireData > &empire_save_game_data, SaveGamePreviewData &preview)
const std::string UNABLE_TO_OPEN_FILE ("Unable to open file")
const std::string XML_COMPRESSED_BASE64_MARKER ("zb64-xml")
const std::string XML_COMPRESSED_MARKER ("zlib-xml")
const std::string XML_DIRECT_MARKER ("raw-xml")
Function Documentation
BINARY_MARKER()
const std::string anonymous_namespace{SaveLoad.cpp}::BINARY_MARKER ("binary")
Referenced by CompileSaveGamePreviewData(), and SaveGame().
CompileSaveGamePreviewData()
void anonymous_namespace{SaveLoad.cpp}::CompileSaveGamePreviewData (const ServerSaveGameData & server_save_game_data, const std::vector< PlayerSaveGameData > & player_save_game_data, const std::map< int, SaveGameEmpireData > & empire_save_game_data, SaveGamePreviewData & preview)
References BINARY_MARKER(), PlayerSaveHeaderData::client_type, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, SaveGamePreviewData::current_turn, ServerSaveGameData::current_turn, DebugLogger, PlayerSaveHeaderData::empire_id, SaveGamePreviewData::main_player_empire_colour, SaveGamePreviewData::main_player_empire_name, SaveGamePreviewData::main_player_name, PlayerSaveHeaderData::name, SaveGamePreviewData::number_of_empires, SaveGamePreviewData::number_of_human_players, SaveGamePreviewData::save_time, UNABLE_TO_OPEN_FILE(), UserString(), XML_COMPRESSED_BASE64_MARKER(), XML_COMPRESSED_MARKER(), and XML_DIRECT_MARKER().
Referenced by SaveGame().
UNABLE_TO_OPEN_FILE()
const std::string anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE ("Unable to open file")
Referenced by CompileSaveGamePreviewData(), LoadEmpireSaveGameData(), LoadGalaxySetupData(), LoadGame(), LoadPlayerSaveHeaderData(), and SaveGame().
XML_COMPRESSED_BASE64_MARKER()
const std::string anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_BASE64_MARKER ("zb64-xml")
Referenced by CompileSaveGamePreviewData(), LoadGame(), and SaveGame().
XML_COMPRESSED_MARKER()
const std::string anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_MARKER ("zlib-xml")
Referenced by CompileSaveGamePreviewData(), and LoadGame().
XML_DIRECT_MARKER()
const std::string anonymous_namespace{SaveLoad.cpp}::XML_DIRECT_MARKER ("raw-xml")
Referenced by CompileSaveGamePreviewData(), LoadGame(), and SaveGame().