FreeOrion: anonymous_namespace{Conditions.cpp} Namespace Reference
anonymous_namespace{Conditions.cpp} Namespace Reference
Functions
void AddAllObjectsSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddBuildingSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddFieldSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddFleetSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddOptions (OptionsDB &db)
void AddPlanetSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddPopCenterSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddResCenterSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddShipSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
void AddSystemSet (const ObjectMap &objects, Condition::ObjectSet &condition_non_targets)
std::map< std::string, bool > ConditionDescriptionAndTest (const std::vector< const Condition::Condition *> &conditions, const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate_object)
DeclareThreadSafeLogger (conditions)
template<typename Pred >
void EvalImpl (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, Condition::SearchDomain search_domain, const Pred &pred)
Used by 4-parameter Condition::Eval function, and some of its overrides, to scan through matches or non_matches set and apply pred to each object, to test if it should remain in its current set or be transferred from the search_domain specified set into the other.
std::vector< const Condition::Condition * > FlattenAndNestedConditions (const std::vector< const Condition::Condition *> &input_conditions)
Variables
const std::string EMPTY_STRING
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddAllObjectsSet()
void anonymous_namespace{Conditions.cpp}::AddAllObjectsSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingObjects().
Referenced by Condition::Condition::GetDefaultInitialCandidateObjects(), Condition::InOrIsSystem::GetDefaultInitialCandidateObjects(), and Condition::ObjectID::GetDefaultInitialCandidateObjects().
AddBuildingSet()
void anonymous_namespace{Conditions.cpp}::AddBuildingSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingBuildings().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects(), Condition::Building::GetDefaultInitialCandidateObjects(), Condition::ContainedBy::GetDefaultInitialCandidateObjects(), Condition::OnPlanet::GetDefaultInitialCandidateObjects(), Condition::PlanetType::GetDefaultInitialCandidateObjects(), Condition::PlanetSize::GetDefaultInitialCandidateObjects(), Condition::PlanetEnvironment::GetDefaultInitialCandidateObjects(), Condition::Species::GetDefaultInitialCandidateObjects(), and Condition::FocusType::GetDefaultInitialCandidateObjects().
AddFieldSet()
void anonymous_namespace{Conditions.cpp}::AddFieldSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingFields().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects().
AddFleetSet()
void anonymous_namespace{Conditions.cpp}::AddFleetSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingFleets().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects(), Condition::Contains::GetDefaultInitialCandidateObjects(), and Condition::ContainedBy::GetDefaultInitialCandidateObjects().
AddOptions()
void anonymous_namespace{Conditions.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
AddPlanetSet()
void anonymous_namespace{Conditions.cpp}::AddPlanetSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingPlanets().
Referenced by Condition::Homeworld::GetDefaultInitialCandidateObjects(), Condition::Capital::GetDefaultInitialCandidateObjects(), Condition::Type::GetDefaultInitialCandidateObjects(), Condition::Contains::GetDefaultInitialCandidateObjects(), Condition::ContainedBy::GetDefaultInitialCandidateObjects(), Condition::PlanetType::GetDefaultInitialCandidateObjects(), Condition::PlanetSize::GetDefaultInitialCandidateObjects(), Condition::PlanetEnvironment::GetDefaultInitialCandidateObjects(), Condition::Species::GetDefaultInitialCandidateObjects(), Condition::Enqueued::GetDefaultInitialCandidateObjects(), and Condition::FocusType::GetDefaultInitialCandidateObjects().
AddPopCenterSet()
void anonymous_namespace{Conditions.cpp}::AddPopCenterSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingPopCenters().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects().
AddResCenterSet()
void anonymous_namespace{Conditions.cpp}::AddResCenterSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingResourceCenters().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects().
AddShipSet()
void anonymous_namespace{Conditions.cpp}::AddShipSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingShips().
Referenced by Condition::Monster::GetDefaultInitialCandidateObjects(), Condition::Type::GetDefaultInitialCandidateObjects(), Condition::ContainedBy::GetDefaultInitialCandidateObjects(), Condition::Species::GetDefaultInitialCandidateObjects(), Condition::DesignHasHull::GetDefaultInitialCandidateObjects(), Condition::DesignHasPart::GetDefaultInitialCandidateObjects(), and Condition::DesignHasPartClass::GetDefaultInitialCandidateObjects().
AddSystemSet()
void anonymous_namespace{Conditions.cpp}::AddSystemSet (const ObjectMap & objects, Condition::ObjectSet & condition_non_targets)
References ObjectMap::ExistingSystems().
Referenced by Condition::Type::GetDefaultInitialCandidateObjects(), and Condition::Contains::GetDefaultInitialCandidateObjects().
ConditionDescriptionAndTest()
std::map<std::string, bool> anonymous_namespace{Conditions.cpp}::ConditionDescriptionAndTest (const std::vector< const Condition::Condition *> & conditions, const ScriptingContext & parent_context, std::shared_ptr< const UniverseObject > candidate_object)
References FlattenAndNestedConditions().
Referenced by Condition::ConditionDescription(), and Condition::ConditionFailedDescription().
DeclareThreadSafeLogger()
anonymous_namespace{Conditions.cpp}::DeclareThreadSafeLogger (conditions)
EvalImpl()
template<typename Pred > void anonymous_namespace{Conditions.cpp}::EvalImpl (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, Condition::SearchDomain search_domain, const Pred & pred)
Used by 4-parameter Condition::Eval function, and some of its overrides, to scan through matches or non_matches set and apply pred to each object, to test if it should remain in its current set or be transferred from the search_domain specified set into the other.
References Condition::MATCHES.
Referenced by ValueRef::Operation< T >::Clone(), Condition::Condition::Eval(), Condition::EmpireAffiliation::Eval(), Condition::Homeworld::Eval(), Condition::Type::Eval(), Condition::Building::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Condition::InOrIsSystem::Eval(), Condition::OnPlanet::Eval(), Condition::ObjectID::Eval(), Condition::PlanetType::Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::Enqueued::Eval(), Condition::FocusType::Eval(), Condition::StarType::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::Chance::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::OwnerHasShipPartAvailable::Eval(), Condition::VisibleToEmpire::Eval(), Condition::WithinDistance::Eval(), Condition::CanAddStarlaneConnection::Eval(), Condition::ExploredByEmpire::Eval(), Condition::FleetSupplyableByEmpire::Eval(), Condition::ResourceSupplyConnectedByEmpire::Eval(), and Condition::OrderedBombarded::Eval().
FlattenAndNestedConditions()
std::vector<const Condition::Condition*> anonymous_namespace{Conditions.cpp}::FlattenAndNestedConditions (const std::vector< const Condition::Condition *> & input_conditions)
Referenced by ConditionDescriptionAndTest().
Variable Documentation
EMPTY_STRING
const std::string anonymous_namespace{Conditions.cpp}::EMPTY_STRING
Referenced by Condition::anonymous_namespace{Conditions.cpp}::GetCandidateFocus(), Condition::anonymous_namespace{Conditions.cpp}::GetCandidateSpecies(), and Condition::anonymous_namespace{Conditions.cpp}::GetContentTypeName().
temp_bool
bool anonymous_namespace{Conditions.cpp}::temp_bool = RegisterOptions(&AddOptions)