FreeOrion: anonymous_namespace{AIWrapper.cpp} Namespace Reference
anonymous_namespace{AIWrapper.cpp} Namespace Reference
Functions
std::vector< int > AllEmpireIDs ()
Return all empire identifiers that are in game.
std::vector< int > AllPlayerIDs ()
Return all player identifiers that are in game.
int AppendFleetMoveOrder (int fleet_id, int destination_id)
int EmpireID ()
int EmpirePlayerID (int empire_id)
std::string GetAIDir ()
Return the canonical AI directory path.
const Empire * GetEmpireByID (int empire_id)
boost::python::list GetUserStringList (const std::string &list_key)
void InitMeterEstimatesAndDiscrepancies ()
template<typename OrderType , typename... Args>
int Issue (Args &&... args)
int IssueAggressionOrder (int object_id, bool aggressive)
int IssueAllowStockpileProductionOrder (int queue_index, bool use_stockpile)
int IssueBombardOrder (int ship_id, int planet_id)
int IssueChangeFocusOrder (int planet_id, const std::string &focus)
int IssueChangeProductionQuantityOrder (int queue_index, int new_quantity, int new_blocksize)
int IssueColonizeOrder (int ship_id, int planet_id)
int IssueCreateShipDesignOrder (const std::string &name, const std::string &description, const std::string &hull, const boost::python::list parts_list, const std::string &icon, const std::string &model, bool name_desc_in_stringtable)
int IssueDequeueProductionOrder (int queue_index)
int IssueDequeueTechOrder (const std::string &tech_name)
OrderSet & IssuedOrders ()
int IssueEnqueueBuildingProductionOrder (const std::string &item_name, int location_id)
int IssueEnqueueShipProductionOrder (int design_id, int location_id)
int IssueEnqueueTechOrder (const std::string &tech_name, int position)
int IssueFleetMoveOrder (int fleet_id, int destination_id)
int IssueFleetTransferOrder (int ship_id, int new_fleet_id)
int IssueGiveObjectToEmpireOrder (int object_id, int recipient_id)
int IssueInvadeOrder (int ship_id, int planet_id)
int IssueNewFleetOrder (const std::string &fleet_name, int ship_id)
int IssuePauseProductionOrder (int queue_index, bool pause)
int IssueRenameOrder (int object_id, const std::string &new_name)
int IssueRequeueProductionOrder (int old_queue_index, int new_queue_index)
int IssueScrapOrder (int object_id)
const Empire * PlayerEmpire ()
Return the Empire this client controls.
int PlayerEmpireID (int player_id)
Return the empire identifier of the empire player_id controls.
int PlayerID ()
bool PlayerIsAI (int player_id)
Return if the player identified by player_id is an AI.
bool PlayerIsHost (int player_id)
Return if the player identified by player_id is the game host.
const std::string & PlayerName ()
const std::string & PlayerNameByID (int player_id)
Return the player name of the client identified by player_id.
const GalaxySetupData & PythonGalaxySetupData ()
static std::string s_save_state_string ("")
void SendDiplomaticMessage (const DiplomaticMessage &diplo_message)
void SendPlayerChatMessage (int recipient_player_id, const std::string &message_text)
void UpdateMeterEstimates (bool pretend_to_own_unowned_planets)
Set Universe Meter instances to their estimated values as if the next turn processing phase were done.
void UpdateProductionQueue ()
void UpdateResearchQueue ()
void UpdateResourcePools ()
Function Documentation
AllEmpireIDs()
std::vector<int> anonymous_namespace{AIWrapper.cpp}::AllEmpireIDs ()
Return all empire identifiers that are in game.
Returns
A vector containing the identifiers of all empires.
References ALL_EMPIRES, and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
AllPlayerIDs()
std::vector<int> anonymous_namespace{AIWrapper.cpp}::AllPlayerIDs ()
Return all player identifiers that are in game.
Returns
A vector containing the identifiers of all players.
References AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
AppendFleetMoveOrder()
int anonymous_namespace{AIWrapper.cpp}::AppendFleetMoveOrder (int fleet_id, int destination_id)
Referenced by FreeOrionPython::WrapAI().
EmpireID()
int anonymous_namespace{AIWrapper.cpp}::EmpireID ()
References ClientApp::EmpireID(), and AIClientApp::GetApp().
Referenced by TechTreeWnd::AddTechToResearchQueue(), BuildDesignatorWnd::BuildItemRequested(), anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints(), TechTreeWnd::CenterOnTech(), ResearchQueueWnd::CompleteConstruction(), ProductionQueueWnd::CompleteConstruction(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitTurn(), IssueCreateShipDesignOrder(), SitRepPanel::LastClicked(), FleetButton::LayoutIcons(), MapWnd::MidTurnUpdate(), SitRepPanel::NextClicked(), SitRepPanel::NumVisibleSitrepsThisTurn(), PlayerEmpire(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender(), anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), SitRepPanel::PrevClicked(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), PlayingGame::react(), WaitingForTurnData::react(), ResearchWnd::Refresh(), BuildDesignatorWnd::Refresh(), RotatingPlanetControl::Refresh(), MapWnd::RefreshDetectionIndicator(), TechTreeArcs::Impl::RefreshHighlights(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTradeResourceIndicator(), MapWnd::RenderSystems(), MapWnd::ResetEmpireShown(), SidePanel::PlanetPanel::SetFocus(), MapWnd::ShowProduction(), TechTreeWnd::TechListBox::TechRightClicked(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), SitRepPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), MapWnd::UpdateEmpireResourcePools(), ResearchWnd::UpdateQueue(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), FreeOrionPython::WrapAI(), MapWnd::ZoomToHomeSystem(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToPrevFleet(), MapWnd::ZoomToPrevIdleFleet(), and MapWnd::ZoomToPrevOwnedSystem().
EmpirePlayerID()
int anonymous_namespace{AIWrapper.cpp}::EmpirePlayerID (int empire_id)
References DebugLogger, ClientApp::EmpirePlayerID(), AIClientApp::GetApp(), and Networking::INVALID_PLAYER_ID.
Referenced by FreeOrionPython::WrapAI().
GetAIDir()
std::string anonymous_namespace{AIWrapper.cpp}::GetAIDir ()
Return the canonical AI directory path.
The value depends on the OptionsDB resource.path and ai-path keys.
Returns
The canonical path pointing to the directory containing all python AI scripts.
References GetOptionsDB(), and GetResourceDir().
Referenced by FreeOrionPython::WrapAI().
GetEmpireByID()
const Empire* anonymous_namespace{AIWrapper.cpp}::GetEmpireByID (int empire_id)
References AIClientApp::GetApp(), and ClientApp::GetEmpire().
Referenced by FreeOrionPython::WrapAI().
GetUserStringList()
boost::python::list anonymous_namespace{AIWrapper.cpp}::GetUserStringList (const std::string & list_key)
References UserStringList().
Referenced by FreeOrionPython::WrapAI().
InitMeterEstimatesAndDiscrepancies()
void anonymous_namespace{AIWrapper.cpp}::InitMeterEstimatesAndDiscrepancies ()
References AIClientApp::GetApp(), ClientApp::GetUniverse(), and Universe::InitMeterEstimatesAndDiscrepancies().
Referenced by FreeOrionPython::WrapAI().
Issue()
template<typename OrderType , typename... Args> int anonymous_namespace{AIWrapper.cpp}::Issue (Args &&... args)
References tag_parser::args, and ClientApp::GetApp().
IssueAggressionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueAggressionOrder (int object_id, bool aggressive)
Referenced by FreeOrionPython::WrapAI().
IssueAllowStockpileProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder (int queue_index, bool use_stockpile)
References ProductionQueueOrder::ALLOW_STOCKPILE_USE, ClientApp::EmpireID(), ProductionQueue::end(), ErrorLogger, ProductionQueue::find(), AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
IssueBombardOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueBombardOrder (int ship_id, int planet_id)
Referenced by FreeOrionPython::WrapAI().
IssueChangeFocusOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueChangeFocusOrder (int planet_id, const std::string & focus)
Referenced by FreeOrionPython::WrapAI().
IssueChangeProductionQuantityOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder (int queue_index, int new_quantity, int new_blocksize)
References ClientApp::EmpireID(), ProductionQueue::end(), ErrorLogger, ProductionQueue::find(), AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), ProductionQueueOrder::SET_QUANTITY_AND_BLOCK_SIZE, and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
IssueColonizeOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueColonizeOrder (int ship_id, int planet_id)
Referenced by FreeOrionPython::WrapAI().
IssueCreateShipDesignOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrder (const std::string & name, const std::string & description, const std::string & hull, const boost::python::list parts_list, const std::string & icon, const std::string & model, bool name_desc_in_stringtable)
References CurrentTurn(), ClientApp::EmpireID(), EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetApp(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
IssueDequeueProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder (int queue_index)
References ClientApp::EmpireID(), ProductionQueue::end(), ErrorLogger, ProductionQueue::find(), AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), ProductionQueueOrder::REMOVE_FROM_QUEUE, and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
IssueDequeueTechOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueDequeueTechOrder (const std::string & tech_name)
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetTech(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
IssuedOrders()
OrderSet& anonymous_namespace{AIWrapper.cpp}::IssuedOrders ()
References AIClientApp::GetApp(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
IssueEnqueueBuildingProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueEnqueueBuildingProductionOrder (const std::string & item_name, int location_id)
References ClientApp::EmpireID(), Empire::EnqueuableItem(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), OrderSet::IssueOrder(), ClientApp::Orders(), ProductionQueueOrder::PLACE_IN_QUEUE, and Empire::ProducibleItem().
Referenced by FreeOrionPython::WrapAI().
IssueEnqueueShipProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueEnqueueShipProductionOrder (int design_id, int location_id)
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), OrderSet::IssueOrder(), ClientApp::Orders(), ProductionQueueOrder::PLACE_IN_QUEUE, and Empire::ProducibleItem().
Referenced by FreeOrionPython::WrapAI().
IssueEnqueueTechOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueEnqueueTechOrder (const std::string & tech_name, int position)
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetTech(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
IssueFleetMoveOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueFleetMoveOrder (int fleet_id, int destination_id)
Referenced by FreeOrionPython::WrapAI().
IssueFleetTransferOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueFleetTransferOrder (int ship_id, int new_fleet_id)
Referenced by FreeOrionPython::WrapAI().
IssueGiveObjectToEmpireOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueGiveObjectToEmpireOrder (int object_id, int recipient_id)
Referenced by FreeOrionPython::WrapAI().
IssueInvadeOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueInvadeOrder (int ship_id, int planet_id)
Referenced by FreeOrionPython::WrapAI().
IssueNewFleetOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueNewFleetOrder (const std::string & fleet_name, int ship_id)
References NewFleetOrder::Check(), and ClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
IssuePauseProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder (int queue_index, bool pause)
References ClientApp::EmpireID(), ProductionQueue::end(), ErrorLogger, ProductionQueue::find(), AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), ProductionQueueOrder::PAUSE_PRODUCTION, and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
IssueRenameOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueRenameOrder (int object_id, const std::string & new_name)
Referenced by FreeOrionPython::WrapAI().
IssueRequeueProductionOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder (int old_queue_index, int new_queue_index)
References ClientApp::EmpireID(), ProductionQueue::end(), ErrorLogger, ProductionQueue::find(), AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ProductionQueueOrder::MOVE_ITEM_TO_INDEX, ClientApp::Orders(), and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
IssueScrapOrder()
int anonymous_namespace{AIWrapper.cpp}::IssueScrapOrder (int object_id)
Referenced by FreeOrionPython::WrapAI().
PlayerEmpire()
const Empire* anonymous_namespace{AIWrapper.cpp}::PlayerEmpire ()
Return the Empire this client controls.
Returns
A pointer to the Empire instance this client has the control over.
References EmpireID(), AIClientApp::GetApp(), and ClientApp::GetEmpire().
Referenced by FreeOrionPython::WrapAI().
PlayerEmpireID()
int anonymous_namespace{AIWrapper.cpp}::PlayerEmpireID (int player_id)
Return the empire identifier of the empire player_id controls.
Parameters
player_id An client identifier.
Returns
An empire identifier.
References ALL_EMPIRES, and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
PlayerID()
int anonymous_namespace{AIWrapper.cpp}::PlayerID ()
References AIClientApp::GetApp(), and ClientApp::PlayerID().
Referenced by MultiPlayerLobbyWnd::ChatMessage(), ServerNetworking::GetPlayer(), MultiPlayerLobbyWnd::PopulatePlayerList(), MPLobby::react(), PlayingGame::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), MultiPlayerLobbyWnd::SendUpdate(), and FreeOrionPython::WrapAI().
PlayerIsAI()
bool anonymous_namespace{AIWrapper.cpp}::PlayerIsAI (int player_id)
Return if the player identified by player_id is an AI.
Parameters
player_id An client identifier.
Returns
True if the player is an AI, false if not.
References Networking::CLIENT_TYPE_AI_PLAYER, AIClientApp::GetApp(), and ClientApp::GetPlayerClientType().
Referenced by FreeOrionPython::WrapAI().
PlayerIsHost()
bool anonymous_namespace{AIWrapper.cpp}::PlayerIsHost (int player_id)
Return if the player identified by player_id is the game host.
Parameters
player_id An client identifier.
Returns
True if the player is the game host, false if not.
References AIClientApp::GetApp(), and ClientApp::Players().
Referenced by HumanClientApp::Autosave(), HumanClientApp::CanSaveNow(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), MPLobby::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), and FreeOrionPython::WrapAI().
PlayerName()
const std::string& anonymous_namespace{AIWrapper.cpp}::PlayerName ()
References AIClientApp::GetApp(), and AIClientApp::PlayerName().
Referenced by FreeOrionPython::WrapAI().
PlayerNameByID()
const std::string& anonymous_namespace{AIWrapper.cpp}::PlayerNameByID (int player_id)
Return the player name of the client identified by player_id.
Parameters
player_id An client identifier.
Returns
An UTF-8 encoded and NUL terminated string containing the player name of this client or an empty string the player is not known or does not exist.
References DebugLogger, AIClientApp::GetApp(), ClientApp::Players(), and to_string().
Referenced by FreeOrionPython::WrapAI().
PythonGalaxySetupData()
const GalaxySetupData& anonymous_namespace{AIWrapper.cpp}::PythonGalaxySetupData ()
References AIClientApp::GetApp(), and ClientApp::GetGalaxySetupData().
Referenced by FreeOrionPython::WrapAI().
s_save_state_string()
static std::string anonymous_namespace{AIWrapper.cpp}::s_save_state_string ("") static
Referenced by FreeOrionPython::ClearStaticSaveStateString(), FreeOrionPython::GetStaticSaveStateString(), and FreeOrionPython::SetStaticSaveStateString().
SendDiplomaticMessage()
void anonymous_namespace{AIWrapper.cpp}::SendDiplomaticMessage (const DiplomaticMessage & diplo_message)
References DiplomacyMessage(), ClientApp::EmpirePlayerID(), AIClientApp::GetApp(), Networking::INVALID_PLAYER_ID, ClientApp::Networking(), ClientApp::PlayerID(), DiplomaticMessage::RecipientEmpireID(), and ClientNetworking::SendMessage().
Referenced by FreeOrionPython::WrapAI().
SendPlayerChatMessage()
void anonymous_namespace{AIWrapper.cpp}::SendPlayerChatMessage (int recipient_player_id, const std::string & message_text)
References AIClientApp::GetApp(), ClientApp::Networking(), PlayerChatMessage(), and ClientNetworking::SendMessage().
Referenced by FreeOrionPython::WrapAI().
UpdateMeterEstimates()
void anonymous_namespace{AIWrapper.cpp}::UpdateMeterEstimates (bool pretend_to_own_unowned_planets)
Set Universe Meter instances to their estimated values as if the next turn processing phase were done.
Parameters
pretend_to_own_unowned_planets When set to true pretend during calculation that this clients Empire owns all known uncolonized planets. The unowned planets MAX Meter values will contain the estimated value for those planets.
References ObjectMap::all(), ALL_EMPIRES, AIClientApp::GetApp(), ClientApp::GetUniverse(), Universe::InhibitUniverseObjectSignals(), Universe::Objects(), ClientApp::PlayerID(), and Universe::UpdateMeterEstimates().
Referenced by FreeOrionPython::WrapAI().
UpdateProductionQueue()
void anonymous_namespace{AIWrapper.cpp}::UpdateProductionQueue ()
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetEmpire(), and Empire::UpdateProductionQueue().
Referenced by Empire::meter_end(), and FreeOrionPython::WrapAI().
UpdateResearchQueue()
void anonymous_namespace{AIWrapper.cpp}::UpdateResearchQueue ()
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetEmpire(), and Empire::UpdateResearchQueue().
Referenced by Empire::meter_end(), and FreeOrionPython::WrapAI().
UpdateResourcePools()
void anonymous_namespace{AIWrapper.cpp}::UpdateResourcePools ()
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetEmpire(), and Empire::UpdateResourcePools().
Referenced by Empire::meter_end(), and FreeOrionPython::WrapAI().