FreeOrion: CheckSums Namespace Reference
CheckSums Namespace Reference
Functions
void CheckSumCombine (unsigned int &sum, const char *s)
void CheckSumCombine (unsigned int &sum, const std::string &c)
void CheckSumCombine (unsigned int &sum, double t)
template<typename T >
void CheckSumCombine (unsigned int &sum, const typename ValueRef::ValueRefBase< T > &c)
template<class T >
void CheckSumCombine (unsigned int &sum, T t, typename std::enable_if< std::is_signed< T >::value, T >::type *=nullptr)
template<class T >
void CheckSumCombine (unsigned int &sum, T t, typename std::enable_if< std::is_unsigned< T >::value, T >::type *=nullptr)
void CheckSumCombine (unsigned int &sum, float t)
template<class C >
void CheckSumCombine (unsigned int &sum, const C &c, decltype(std::declval< C >().GetCheckSum())*=nullptr)
template<class T >
void CheckSumCombine (unsigned int &sum, T t, typename std::enable_if< std::is_enum< T >::value, T >::type *=nullptr)
template<class T >
void CheckSumCombine (unsigned int &sum, const T *p)
template<class T >
void CheckSumCombine (unsigned int &sum, const typename std::shared_ptr< T > &p)
template<class T >
void CheckSumCombine (unsigned int &sum, const typename std::unique_ptr< T > &p)
void CheckSumCombine (unsigned int &sum, const ItemSpec &item)
void CheckSumCombine (unsigned int &sum, const TechCategory &cat)
template<class C , class D >
void CheckSumCombine (unsigned int &sum, const std::pair< C, D > &p)
template<class C >
void CheckSumCombine (unsigned int &sum, const C &c, decltype(std::declval< C >().begin())*=nullptr, decltype(std::declval< C >().end())*=nullptr)
void CheckSumCombine (unsigned int &sum, const HullType::Slot &slot)
Variables
const unsigned int CHECKSUM_MODULUS = 10000000U
Function Documentation
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, const char * s)
References CheckSumCombine().
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, const std::string & c)
References CHECKSUM_MODULUS, CheckSumCombine(), and TraceLogger.
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, double t)
References CHECKSUM_MODULUS.
template<typename T > void CheckSums::CheckSumCombine (unsigned int & sum, const typename ValueRef::ValueRefBase< T > & c)
References CHECKSUM_MODULUS, ValueRef::ValueRefBase< T >::GetCheckSum(), and TraceLogger.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, T t, typename std::enable_if< std::is_signed< T >::value, T >::type * = nullptr)
References CHECKSUM_MODULUS.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, T t, typename std::enable_if< std::is_unsigned< T >::value, T >::type * = nullptr)
References CHECKSUM_MODULUS.
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, float t)
References CHECKSUM_MODULUS.
template<class C > void CheckSums::CheckSumCombine (unsigned int & sum, const C & c, decltype(std::declval< C >().GetCheckSum())* = nullptr)
References CHECKSUM_MODULUS, and TraceLogger.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, T t, typename std::enable_if< std::is_enum< T >::value, T >::type * = nullptr)
References CheckSumCombine(), and TraceLogger.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, const T * p)
References CheckSumCombine(), and TraceLogger.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, const typename std::shared_ptr< T > & p)
References CheckSumCombine(), and TraceLogger.
template<class T > void CheckSums::CheckSumCombine (unsigned int & sum, const typename std::unique_ptr< T > & p)
References CheckSumCombine(), and TraceLogger.
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, const ItemSpec & item)
References CheckSumCombine(), ItemSpec::name, TraceLogger, and ItemSpec::type.
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, const TechCategory & cat)
References CheckSumCombine(), TechCategory::colour, TechCategory::graphic, TechCategory::name, and TraceLogger.
template<class C , class D > void CheckSums::CheckSumCombine (unsigned int & sum, const std::pair< C, D > & p)
References CheckSumCombine(), and TraceLogger.
template<class C > void CheckSums::CheckSumCombine (unsigned int & sum, const C & c, decltype(std::declval< C >().begin())* = nullptr, decltype(std::declval< C >().end())* = nullptr)
References CHECKSUM_MODULUS, CheckSumCombine(), and TraceLogger.
FO_COMMON_API void CheckSums::CheckSumCombine (unsigned int & sum, const HullType::Slot & slot)
References TraceLogger, HullType::Slot::type, HullType::Slot::x, and HullType::Slot::y.
Referenced by CheckSumCombine(), Encyclopedia::GetCheckSum(), anonymous_namespace{Special.cpp}::SpecialManager::GetCheckSum(), FocusType::GetCheckSum(), Special::GetCheckSum(), Effect::EffectsGroup::GetCheckSum(), FieldType::GetCheckSum(), Tech::GetCheckSum(), FieldTypeManager::GetCheckSum(), Effect::EffectBase::GetCheckSum(), PartType::GetCheckSum(), Effect::NoOp::GetCheckSum(), BuildingType::GetCheckSum(), Species::GetCheckSum(), ValueRef::Constant< T >::GetCheckSum(), Condition::Number::GetCheckSum(), PartTypeManager::GetCheckSum(), Effect::SetMeter::GetCheckSum(), BuildingTypeManager::GetCheckSum(), ValueRef::Variable< T >::GetCheckSum(), Condition::Turn::GetCheckSum(), Effect::SetShipPartMeter::GetCheckSum(), ValueRef::Statistic< T >::GetCheckSum(), TechManager::GetCheckSum(), Effect::SetEmpireMeter::GetCheckSum(), Condition::SortedNumberOf::GetCheckSum(), SpeciesManager::GetCheckSum(), Effect::SetEmpireStockpile::GetCheckSum(), Condition::All::GetCheckSum(), ValueRef::ComplexVariable< T >::GetCheckSum(), Effect::SetEmpireCapital::GetCheckSum(), HullType::GetCheckSum(), Condition::None::GetCheckSum(), Effect::SetPlanetType::GetCheckSum(), ValueRef::StaticCast< FromType, ToType >::GetCheckSum(), Effect::SetPlanetSize::GetCheckSum(), Condition::EmpireAffiliation::GetCheckSum(), HullTypeManager::GetCheckSum(), ValueRef::StringCast< FromType >::GetCheckSum(), Effect::SetSpecies::GetCheckSum(), Condition::Source::GetCheckSum(), Effect::SetOwner::GetCheckSum(), ValueRef::UserStringLookup< FromType >::GetCheckSum(), Effect::SetSpeciesEmpireOpinion::GetCheckSum(), Condition::RootCandidate::GetCheckSum(), Effect::SetSpeciesSpeciesOpinion::GetCheckSum(), ValueRef::NameLookup::GetCheckSum(), Condition::Target::GetCheckSum(), ShipDesign::GetCheckSum(), Effect::CreatePlanet::GetCheckSum(), Effect::CreateBuilding::GetCheckSum(), Condition::Homeworld::GetCheckSum(), ValueRef::Operation< T >::GetCheckSum(), Effect::CreateShip::GetCheckSum(), Condition::Capital::GetCheckSum(), PredefinedShipDesignManager::GetCheckSum(), Condition::Monster::GetCheckSum(), Effect::CreateField::GetCheckSum(), Condition::Armed::GetCheckSum(), Effect::CreateSystem::GetCheckSum(), Condition::Type::GetCheckSum(), Effect::Destroy::GetCheckSum(), Effect::AddSpecial::GetCheckSum(), Condition::Building::GetCheckSum(), Effect::RemoveSpecial::GetCheckSum(), Effect::AddStarlanes::GetCheckSum(), Effect::RemoveStarlanes::GetCheckSum(), Condition::HasSpecial::GetCheckSum(), Effect::SetStarType::GetCheckSum(), Condition::HasTag::GetCheckSum(), Effect::MoveTo::GetCheckSum(), Effect::MoveInOrbit::GetCheckSum(), Condition::CreatedOnTurn::GetCheckSum(), Effect::MoveTowards::GetCheckSum(), Condition::Contains::GetCheckSum(), Effect::SetDestination::GetCheckSum(), Effect::SetAggression::GetCheckSum(), Condition::ContainedBy::GetCheckSum(), Effect::Victory::GetCheckSum(), Effect::SetEmpireTechProgress::GetCheckSum(), Condition::InSystem::GetCheckSum(), Effect::GiveEmpireTech::GetCheckSum(), Condition::ObjectID::GetCheckSum(), Condition::PlanetType::GetCheckSum(), Effect::GenerateSitRepMessage::GetCheckSum(), Condition::PlanetSize::GetCheckSum(), Effect::SetOverlayTexture::GetCheckSum(), Condition::PlanetEnvironment::GetCheckSum(), Effect::SetTexture::GetCheckSum(), Effect::SetVisibility::GetCheckSum(), Condition::Species::GetCheckSum(), Effect::Conditional::GetCheckSum(), Condition::Enqueued::GetCheckSum(), Condition::FocusType::GetCheckSum(), Condition::StarType::GetCheckSum(), Condition::DesignHasHull::GetCheckSum(), Condition::DesignHasPart::GetCheckSum(), Condition::DesignHasPartClass::GetCheckSum(), Condition::PredefinedShipDesign::GetCheckSum(), Condition::NumberedShipDesign::GetCheckSum(), Condition::ProducedByEmpire::GetCheckSum(), Condition::Chance::GetCheckSum(), Condition::MeterValue::GetCheckSum(), Condition::ShipPartMeterValue::GetCheckSum(), Condition::EmpireMeterValue::GetCheckSum(), Condition::EmpireStockpileValue::GetCheckSum(), Condition::OwnerHasTech::GetCheckSum(), Condition::OwnerHasBuildingTypeAvailable::GetCheckSum(), Condition::OwnerHasShipDesignAvailable::GetCheckSum(), Condition::OwnerHasShipPartAvailable::GetCheckSum(), Condition::VisibleToEmpire::GetCheckSum(), Condition::WithinDistance::GetCheckSum(), Condition::WithinStarlaneJumps::GetCheckSum(), Condition::CanAddStarlaneConnection::GetCheckSum(), Condition::ExploredByEmpire::GetCheckSum(), Condition::Stationary::GetCheckSum(), Condition::Aggressive::GetCheckSum(), Condition::FleetSupplyableByEmpire::GetCheckSum(), Condition::ResourceSupplyConnectedByEmpire::GetCheckSum(), Condition::CanColonize::GetCheckSum(), Condition::CanProduceShips::GetCheckSum(), Condition::OrderedBombarded::GetCheckSum(), Condition::ValueTest::GetCheckSum(), Condition::Location::GetCheckSum(), Condition::And::GetCheckSum(), Condition::Or::GetCheckSum(), Condition::Not::GetCheckSum(), Condition::Described::GetCheckSum(), and EmpireStatistics::GetEmpireStats().
Variable Documentation
const unsigned int CheckSums::CHECKSUM_MODULUS = 10000000U
Referenced by CheckSumCombine().