FreeOrion: anonymous_namespace{BuildDesignatorWnd.cpp} Namespace Reference
anonymous_namespace{BuildDesignatorWnd.cpp} Namespace Reference
Classes
class BuildableItemsListBox
class ProductionItemPanel
class ProductionItemRow
Functions
void AddOptions (OptionsDB &db)
std::string EnqueueAndLocationConditionDescription (const std::string &building_name, int candidate_object_id, int empire_id, bool only_failed_conditions)
std::shared_ptr< const UniverseObject > GetSourceObjectForEmpire (int empire_id)
std::string LocationConditionDescription (int ship_design_id, int candidate_object_id, int empire_id, bool only_failed_conditions)
std::shared_ptr< GG::BrowseInfoWnd > ProductionItemRowBrowseWnd (const ProductionQueue::ProductionItem &item, int candidate_object_id, int empire_id)
int ProductionTurns (float total_cost, int minimum_production_time, float local_pp_output, float stockpile, float stockpile_limit_per_turn)
Variables
const float EPSILON = 0.001f
const int MAX_PRODUCTION_TURNS = 200
const std::string PROD_PEDIA_WND_NAME = "production.pedia"
const std::string PROD_SELECTOR_WND_NAME = "production.selector"
const std::string PROD_SIDEPANEL_WND_NAME = "production.sidepanel"
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{BuildDesignatorWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
EnqueueAndLocationConditionDescription()
std::string anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription (const std::string & building_name, int candidate_object_id, int empire_id, bool only_failed_conditions)
References Condition::ConditionDescription(), Condition::ConditionFailedDescription(), GetBuildingType(), GetSourceObjectForEmpire(), and Objects().
Referenced by ProductionItemRowBrowseWnd().
GetSourceObjectForEmpire()
std::shared_ptr<const UniverseObject> anonymous_namespace{BuildDesignatorWnd.cpp}::GetSourceObjectForEmpire (int empire_id)
References ObjectMap::all(), ALL_EMPIRES, GetEmpire(), GetUniverse(), Objects(), and Universe::Objects().
Referenced by EnqueueAndLocationConditionDescription(), and LocationConditionDescription().
LocationConditionDescription()
std::string anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription (int ship_design_id, int candidate_object_id, int empire_id, bool only_failed_conditions)
References Condition::ConditionDescription(), Condition::ConditionFailedDescription(), GetShipDesign(), GetShipHull(), GetShipPart(), GetSourceObjectForEmpire(), and Objects().
Referenced by ProductionItemRowBrowseWnd().
ProductionItemRowBrowseWnd()
std::shared_ptr<GG::BrowseInfoWnd> anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd (const ProductionQueue::ProductionItem & item, int candidate_object_id, int empire_id)
References ClientUI::BuildingIcon(), ShipDesign::Description(), DoubleToString(), EnqueueAndLocationConditionDescription(), FlexibleFormat(), ObjectMap::get(), GetBuildingType(), GetEmpire(), GetOptionsDB(), GetShipDesign(), ShipDesign::Hull(), LocationConditionDescription(), ClientUI::MeterIcon(), ShipDesign::Name(), Objects(), ShipDesign::Parts(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionTime(), ProductionTurns(), ClientUI::ShipDesignIcon(), to_string(), UserString(), and UserStringExists().
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow().
ProductionTurns()
int anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionTurns (float total_cost, int minimum_production_time, float local_pp_output, float stockpile, float stockpile_limit_per_turn)
References EPSILON.
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), and ProductionItemRowBrowseWnd().
Variable Documentation
EPSILON
const float anonymous_namespace{BuildDesignatorWnd.cpp}::EPSILON = 0.001f
Referenced by ProductionTurns().
MAX_PRODUCTION_TURNS
const int anonymous_namespace{BuildDesignatorWnd.cpp}::MAX_PRODUCTION_TURNS = 200
PROD_PEDIA_WND_NAME
const std::string anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_PEDIA_WND_NAME = "production.pedia"
Referenced by BuildDesignatorWnd::CompleteConstruction(), BuildDesignatorWnd::HidePedia(), and BuildDesignatorWnd::ShowPedia().
PROD_SELECTOR_WND_NAME
const std::string anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_SELECTOR_WND_NAME = "production.selector"
Referenced by BuildDesignatorWnd::CompleteConstruction().
PROD_SIDEPANEL_WND_NAME
const std::string anonymous_namespace{BuildDesignatorWnd.cpp}::PROD_SIDEPANEL_WND_NAME = "production.sidepanel"
Referenced by BuildDesignatorWnd::CompleteConstruction().
temp_bool
bool anonymous_namespace{BuildDesignatorWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)