FreeOrion: anonymous_namespace{ServerConnectWnd.cpp} Namespace Reference
anonymous_namespace{ServerConnectWnd.cpp} Namespace Reference
Classes
class ClientTypeRow
Functions
void AddOptions (OptionsDB &db)
bool NameOK (const std::string &name)
const GG::Y WINDOW_HEIGHT (535)
const GG::X WINDOW_WIDTH (400)
Variables
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{ServerConnectWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
NameOK()
bool anonymous_namespace{ServerConnectWnd.cpp}::NameOK (const std::string & name)
Referenced by ServerConnectWnd::EnableDisableControls().
WINDOW_HEIGHT()
const GG::Y anonymous_namespace{ServerConnectWnd.cpp}::WINDOW_HEIGHT (535)
Referenced by ServerConnectWnd::CalculatePosition().
WINDOW_WIDTH()
const GG::X anonymous_namespace{ServerConnectWnd.cpp}::WINDOW_WIDTH (400)
Referenced by ServerConnectWnd::CalculatePosition().
Variable Documentation
temp_bool
bool anonymous_namespace{ServerConnectWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)