FreeOrion: anonymous_namespace{CUIControls.cpp} Namespace Reference
anonymous_namespace{CUIControls.cpp} Namespace Reference
Classes
struct ColorRow
struct SpeciesRow
Functions
void AddOptions (OptionsDB &db)
void PlayButtonClickSound ()
void PlayButtonRolloverSound ()
void PlayDropDownListOpenSound ()
void PlayItemDropSound (GG::ListBox::iterator)
void PlayListSelectSound (const GG::ListBox::SelectionSet &)
void PlayTextTypingSound (const std::string &)
GG::Y VERTICAL_SECTION_GAP (4)
Variables
const double ARROW_BRIGHTENING_SCALE_FACTOR = 1.5
constexpr GG::X COLOR_SELECTOR_WIDTH {75}
const int CUIBUTTON_ANGLE_OFFSET = 5
const int CUIDROPDOWNLIST_ANGLE_OFFSET = 5
const std::string EMPTY_STRING
ScanlineRenderer scanline_shader
const int STAT_ICON_PAD = 2
const double STATE_BUTTON_BRIGHTENING_SCALE_FACTOR = 1.25
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{CUIControls.cpp}::AddOptions (OptionsDB & db)
References Hotkey::AddHotkey(), and UserStringNop.
PlayButtonClickSound()
void anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIArrowButton::CUIArrowButton(), CUIButton::CUIButton(), CUICheckBoxRepresenter::OnChecked(), CUIRadioRepresenter::OnChecked(), CUITabRepresenter::OnChecked(), CUILabelButtonRepresenter::OnChecked(), and CUIIconButtonRepresenter::OnChecked().
PlayButtonRolloverSound()
void anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIScroll::ScrollTab::MouseEnter(), CUIDropDownList::MouseEnter(), CUIButton::MouseHere(), CUIArrowButton::MouseHere(), CUICheckBoxRepresenter::OnChanged(), CUIRadioRepresenter::OnChanged(), CUITabRepresenter::OnChanged(), and CUILabelButtonRepresenter::OnChanged().
PlayDropDownListOpenSound()
void anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIDropDownList::LClick().
PlayItemDropSound()
void anonymous_namespace{CUIControls.cpp}::PlayItemDropSound (GG::ListBox::iterator)
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIListBox::CUIListBox().
PlayListSelectSound()
void anonymous_namespace{CUIControls.cpp}::PlayListSelectSound (const GG::ListBox::SelectionSet &)
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIListBox::CUIListBox().
PlayTextTypingSound()
void anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound (const std::string &)
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUIEdit::CompleteConstruction().
VERTICAL_SECTION_GAP()
GG::Y anonymous_namespace{CUIControls.cpp}::VERTICAL_SECTION_GAP (4)
Referenced by FileDlg::CompleteConstruction().
Variable Documentation
ARROW_BRIGHTENING_SCALE_FACTOR
const double anonymous_namespace{CUIControls.cpp}::ARROW_BRIGHTENING_SCALE_FACTOR = 1.5
Referenced by CUIDropDownList::Render(), and CUIArrowButton::RenderRollover().
COLOR_SELECTOR_WIDTH
constexpr GG::X anonymous_namespace{CUIControls.cpp}::COLOR_SELECTOR_WIDTH {75}
Referenced by anonymous_namespace{CUIControls.cpp}::ColorRow::ColorSquare::ColorSquare(), and EmpireColorSelector::EmpireColorSelector().
CUIBUTTON_ANGLE_OFFSET
const int anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET = 5
Referenced by CUIButton::InWindow(), CUITabRepresenter::Render(), CUILabelButtonRepresenter::Render(), CUIIconButtonRepresenter::Render(), CUIButton::RenderPressed(), CUIButton::RenderRollover(), and CUIButton::RenderUnpressed().
CUIDROPDOWNLIST_ANGLE_OFFSET
const int anonymous_namespace{CUIControls.cpp}::CUIDROPDOWNLIST_ANGLE_OFFSET = 5
Referenced by CUIDropDownList::InitBuffer().
EMPTY_STRING
const std::string anonymous_namespace{CUIControls.cpp}::EMPTY_STRING
Referenced by ResourceInfoPanel::ClearLocalInfo(), SpeciesSelector::CurrentSpeciesName(), ResourceInfoPanel::SetEmpireID(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), and SpeciesSelector::SpeciesSelector().
scanline_shader
ScanlineRenderer anonymous_namespace{CUIControls.cpp}::scanline_shader
Referenced by ScanlineControl::Render().
STAT_ICON_PAD
const int anonymous_namespace{CUIControls.cpp}::STAT_ICON_PAD = 2
Referenced by StatisticIcon::DoLayout().
STATE_BUTTON_BRIGHTENING_SCALE_FACTOR
const double anonymous_namespace{CUIControls.cpp}::STATE_BUTTON_BRIGHTENING_SCALE_FACTOR = 1.25
Referenced by CUICheckBoxRepresenter::Render(), and CUIRadioRepresenter::Render().
temp_bool
bool anonymous_namespace{CUIControls.cpp}::temp_bool = RegisterOptions(&AddOptions)