FreeOrion: anonymous_namespace{MapWnd.cpp} Namespace Reference
anonymous_namespace{MapWnd.cpp} Namespace Reference
Classes
struct CustomRowCmp
class FleetDetailBrowseWnd
BrowseInfoWnd for the fleet icon tooltip.
struct hash_set
class NotCoveredMapWndCondition
On when the MapWnd window is visible and not covered.
Typedefs
typedef std::unordered_set< int > FleetIDListType
typedef std::pair< int, RouteListType > FleetRouteType
template<typename Key >
using KeyToFleetsMap = std::unordered_map< Key, std::vector< int >, boost::hash< Key > >
using LocationXEmpireToFleetsMap = KeyToFleetsMap< std::pair< std::pair< double, double >, int > >
typedef std::pair< double, FleetRouteType > OrderedFleetRouteType
typedef std::pair< double, RouteListType > OrderedRouteType
typedef std::vector< int > RouteListType
using StarlaneToFleetsMap = KeyToFleetsMap< std::pair< int, int > >
typedef std::unordered_map< int, int > SystemFleetMap
typedef std::set< int > SystemIDListType
using SystemXEmpireToFleetsMap = KeyToFleetsMap< std::pair< int, int > >
Functions
SystemIDListType AddNeighboorsToSet (const Empire *empire, const SystemIDListType &system_ids)
void AddOptions (OptionsDB &db)
GG::Y AppHeight ()
GG::X AppWidth ()
const unsigned int BUFFER_CAPACITY (512)
std::map< std::pair< int, int >, LaneEndpoints > CalculateStarlaneEndpoints (const std::unordered_map< int, std::shared_ptr< SystemIcon >> &sys_icons)
bool CanResupplyAfterDestination (const std::shared_ptr< Fleet > &fleet, const RouteListType &route)
If fleet would be able to reach a system with supply after completing route.
bool ClientPlayerIsModerator ()
DeclareThreadSafeLogger (effects)
OrderedRouteType ExploringFleetResupplyRoute (const std::shared_ptr< Fleet > &fleet)
Route from current system of fleet to nearest system with supply as determined by owning empire of fleet.
bool FleetRouteInRange (const std::shared_ptr< Fleet > &fleet, const RouteListType &route)
If fleet can determine an eta for route.
double FractionalDistanceBetweenPoints (double startX, double startY, double midX, double midY, double endX, double endY)
std::shared_ptr< GG::Texture > GetGasTexture ()
OrderedRouteType GetNearestSupplyRoute (const Empire *empire, int dest_id, int max_jumps=-1)
Shortest route not exceeding max_jumps from dest_id to a system with supply as known to empire.
OrderedFleetRouteType GetOrderedFleetRoute (const std::shared_ptr< Fleet > &fleet, const std::shared_ptr< System > &destination)
Route from fleet current location to destination.
std::set< std::pair< std::string, int >, CustomRowCmp > GetOwnedSystemNamesIDs (int empire_id)
void GetResPoolLaneInfo (int empire_id, std::unordered_map< std::set< int >, std::set< int >, hash_set > &res_pool_systems, std::unordered_map< std::set< int >, std::set< int >, hash_set > &res_group_cores, std::unordered_set< int > &res_group_core_members, std::unordered_map< int, std::set< int >> &member_to_core, std::unordered_set< int > &under_alloc_res_grp_core_members)
OrderedRouteType GetShortestRoute (int empire_id, int start_id, int destination_id)
Get the shortest suitable route from start_id to destination_id as known to empire_id.
std::set< std::pair< std::string, int >, CustomRowCmp > GetSystemNamesIDs ()
const GG::X ICON_DUAL_WIDTH (64)
const GG::X ICON_SINGLE_WIDTH (40)
const GG::X ICON_WIDTH (24)
bool InRect (GG::X left, GG::Y top, GG::X right, GG::Y bottom, const GG::Pt &pt)
std::shared_ptr< const System > IsDepartingFromSystem (const std::shared_ptr< const Fleet > &fleet)
If the fleet has orders and is departing from a valid system, return the system.
bool IsMoving (const std::shared_ptr< const Fleet > &fleet)
If the fleet has a valid destination and it not at a system, return true.
boost::optional< std::pair< int, int > > IsMovingOnStarlane (const std::shared_ptr< const Fleet > &fleet)
If the fleet has a valid destination, is not at a system and is on a starlane, return the starlane's endpoint system ids.
bool IsOffRoad (const std::shared_ptr< const Fleet > &fleet)
If the fleet has a valid destination and it not on a starlane, return true.
boost::optional< std::pair< int, int > > IsOnStarlane (const std::shared_ptr< const Fleet > &fleet)
Return the starlane's endpoints if the fleet is on a starlane.
std::shared_ptr< const Fleet > IsQualifiedFleet (const std::shared_ptr< const UniverseObject > &obj, int empire_id, const std::set< int > &known_destroyed_objects, const std::set< int > &stale_object_info)
Return fleet if obj is not destroyed, not stale, a fleet and not empty.
std::shared_ptr< const System > IsStationaryInSystem (const std::shared_ptr< const Fleet > &fleet)
If the fleet is stationary in a valid system, return the system.
void IssueExploringFleetOrders (FleetIDListType &idle_fleets, SystemFleetMap &systems_being_explored, const FleetRouteType &fleet_route)
Determine and issue move order for fleet and route fleet_route.
bool IssueFleetExploreOrder (const std::shared_ptr< Fleet > &fleet, const RouteListType &route)
Issue order for fleet to move using route.
bool IssueFleetResupplyOrder (const std::shared_ptr< Fleet > &fleet)
Issue an order for fleet to move to nearest system with supply.
int JumpsForRoute (const RouteListType &route)
Number of jumps in a given route.
std::shared_ptr< GG::Texture > MoveLineDotTexture ()
void PlayTurnButtonClickSound ()
std::pair< double, double > PositionFractionalAtDistanceBetweenPoints (double X1, double Y1, double X2, double Y2, double dist)
void PrepFullLanesToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> &sys_icons, GG::GL2DVertexBuffer &starlane_vertices, GG::GLRGBAColorBuffer &starlane_colors)
void PrepObstructedLaneTraversalsToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> &sys_icons, int empire_id, std::set< std::pair< int, int >> &rendered_half_starlanes, GG::GL2DVertexBuffer &starlane_vertices, GG::GLRGBAColorBuffer &starlane_colors)
void PrepResourceConnectionLanesToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> &sys_icons, int empire_id, std::set< std::pair< int, int >> &rendered_half_starlanes, GG::GL2DVertexBuffer &rc_starlane_vertices, GG::GLRGBAColorBuffer &rc_starlane_colors)
const GG::Y SCALE_LINE_HEIGHT (20)
const GG::X SCALE_LINE_MAX_WIDTH (240)
boost::optional< std::pair< double, double > > ScreenPosOnStarlane (double X, double Y, int lane_start_sys_id, int lane_end_sys_id, const LaneEndpoints &screen_lane_endpoints)
const GG::Y SITREP_PANEL_HEIGHT (200)
const GG::X SITREP_PANEL_WIDTH (400)
LaneEndpoints StarlaneEndPointsFromSystemPositions (double X1, double Y1, double X2, double Y2)
bool ToggleBoolOption (const std::string &option_name)
const GG::Y TOOLBAR_HEIGHT (32)
GG::Y WndBottom (const GG::Wnd *wnd)
GG::X WndLeft (const GG::Wnd *wnd)
GG::X WndRight (const GG::Wnd *wnd)
GG::Y WndTop (const GG::Wnd *wnd)
const GG::Y ZOOM_SLIDER_HEIGHT (200)
double ZoomScaleFactor (double steps_in)
Variables
const std::string COMBAT_REPORT_WND_NAME = "combat.summary"
GG::GLTexCoordBuffer dot_star_texture_coords
GG::GL2DVertexBuffer dot_vertices_buffer
const std::string FLEET_DETAIL_ARMED_COUNT {UserStringNop("MAP_FLEET_ARMED_COUNT")}
const std::string FLEET_DETAIL_CARRIER_COUNT {UserStringNop("MAP_FLEET_CARRIER_COUNT")}
const std::string FLEET_DETAIL_COLONY_COUNT {UserStringNop("MAP_FLEET_COLONY_COUNT")}
const std::string FLEET_DETAIL_PART_COUNT {UserStringNop("MAP_FLEET_PART_COUNT")}
const std::string FLEET_DETAIL_SHIP_COUNT {UserStringNop("MAP_FLEET_SHIP_COUNT")}
const std::string FLEET_DETAIL_SLOT_COUNT {UserStringNop("MAP_FLEET_SLOT_COUNT")}
const std::string FLEET_DETAIL_TROOP_COUNT {UserStringNop("MAP_FLEET_TROOP_COUNT")}
const std::string FLEET_DETAIL_UNARMED_COUNT {UserStringNop("MAP_FLEET_UNARMED_COUNT")}
const std::string GOVERNMENT_WND_NAME = "map.government"
const GG::Pt ICON_SIZE {GG::X{24}, GG::Y{24}}
const int LAYOUT_MARGIN = 5
const std::string MAP_PEDIA_WND_NAME = "map.pedia"
const std::string MAP_SIDEPANEL_WND_NAME = "map.sidepanel"
const GG::Pt MENU_ICON_SIZE {GG::X{32}, GG::Y{32}}
const int MIN_SYSTEM_NAME_SIZE = 10
const std::string MODERATOR_WND_NAME = "map.moderator"
const std::string OBJECT_WND_NAME = "map.object-list"
const std::string SITREP_WND_NAME = "map.sitrep"
bool temp_bool = RegisterOptions(&AddOptions)
constexpr double TWO_PI = 2.0*3.1415926536
const double ZOOM_IN_MAX_STEPS = 12.0
const double ZOOM_IN_MIN_STEPS = -10.0
const double ZOOM_MAX = std::pow(ZOOM_STEP_SIZE, ZOOM_IN_MAX_STEPS)
const double ZOOM_MIN = std::pow(ZOOM_STEP_SIZE, ZOOM_IN_MIN_STEPS)
const double ZOOM_STEP_SIZE = std::pow(2.0, 1.0/4.0)
Typedef Documentation
FleetIDListType
typedef std::unordered_set<int> anonymous_namespace{MapWnd.cpp}::FleetIDListType
FleetRouteType
typedef std::pair<int, RouteListType> anonymous_namespace{MapWnd.cpp}::FleetRouteType
KeyToFleetsMap
template<typename Key > using anonymous_namespace{MapWnd.cpp}::KeyToFleetsMap = typedef std::unordered_map<Key, std::vector<int>, boost::hash<Key> >
LocationXEmpireToFleetsMap
using anonymous_namespace{MapWnd.cpp}::LocationXEmpireToFleetsMap = typedef KeyToFleetsMap<std::pair<std::pair<double, double>, int> >
OrderedFleetRouteType
typedef std::pair<double, FleetRouteType> anonymous_namespace{MapWnd.cpp}::OrderedFleetRouteType
OrderedRouteType
typedef std::pair<double, RouteListType> anonymous_namespace{MapWnd.cpp}::OrderedRouteType
RouteListType
typedef std::vector<int> anonymous_namespace{MapWnd.cpp}::RouteListType
StarlaneToFleetsMap
using anonymous_namespace{MapWnd.cpp}::StarlaneToFleetsMap = typedef KeyToFleetsMap<std::pair<int, int> >
SystemFleetMap
typedef std::unordered_map<int, int> anonymous_namespace{MapWnd.cpp}::SystemFleetMap
SystemIDListType
typedef std::set<int> anonymous_namespace{MapWnd.cpp}::SystemIDListType
SystemXEmpireToFleetsMap
using anonymous_namespace{MapWnd.cpp}::SystemXEmpireToFleetsMap = typedef KeyToFleetsMap<std::pair<int, int> >
Function Documentation
AddNeighboorsToSet()
SystemIDListType anonymous_namespace{MapWnd.cpp}::AddNeighboorsToSet (const Empire * empire, const SystemIDListType & system_ids)
Referenced by MapWnd::DispatchFleetsExploring().
AddOptions()
void anonymous_namespace{MapWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), Hotkey::AddHotkey(), and UserStringNop.
AppHeight()
GG::Y anonymous_namespace{MapWnd.cpp}::AppHeight ()
References HumanClientApp::GetApp().
Referenced by PasswordEnterWnd::CalculatePosition(), OptionsWnd::CalculatePosition(), ServerConnectWnd::CalculatePosition(), SaveFileDialog::CalculatePosition(), MultiPlayerLobbyWnd::CalculatePosition(), FleetWnd::CalculatePosition(), GalaxySetupWnd::CalculatePosition(), MapWnd::CenterOnMapCoord(), MapWnd::ClientUpperLeft(), MapWnd::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), MapWnd::CorrectMapPosition(), MapWnd::DoLayout(), ClientUI::InitializeWindows(), MapWnd::InitializeWindows(), MapWnd::InitTurnRendering(), MapWnd::LDrag(), MapWnd::Pan(), CreditsWnd::Render(), MapWnd::Render(), anonymous_namespace{SidePanel.cpp}::RenderPlanet(), MapWnd::RenderStarfields(), MapWnd::RestoreFromSaveData(), MapWnd::Sanitize(), MapWnd::SetZoom(), and MapWnd::Zoom().
AppWidth()
GG::X anonymous_namespace{MapWnd.cpp}::AppWidth ()
References HumanClientApp::GetApp().
Referenced by InGameMenu::CalculatePosition(), PasswordEnterWnd::CalculatePosition(), OptionsWnd::CalculatePosition(), ServerConnectWnd::CalculatePosition(), SaveFileDialog::CalculatePosition(), MultiPlayerLobbyWnd::CalculatePosition(), GalaxySetupWnd::CalculatePosition(), MapWnd::CenterOnMapCoord(), MapWnd::ClientUpperLeft(), MapWnd::CompleteConstruction(), CUIEditWnd::CompleteConstruction(), MapWnd::CorrectMapPosition(), MapWnd::DoLayout(), MapWnd::InitializeWindows(), MapWnd::InitTurnRendering(), MapWnd::LDrag(), MapWnd::Pan(), MapWnd::Render(), anonymous_namespace{SidePanel.cpp}::RenderPlanet(), MapWnd::RenderStarfields(), MapWnd::RestoreFromSaveData(), MapWnd::Sanitize(), MapWnd::SetZoom(), and MapWnd::Zoom().
BUFFER_CAPACITY()
const unsigned int anonymous_namespace{MapWnd.cpp}::BUFFER_CAPACITY (512)
Referenced by MapWnd::RenderFleetMovementLines(), and MapWnd::RenderMovementLine().
CalculateStarlaneEndpoints()
std::map<std::pair<int, int>, LaneEndpoints> anonymous_namespace{MapWnd.cpp}::CalculateStarlaneEndpoints (const std::unordered_map< int, std::shared_ptr< SystemIcon >> & sys_icons)
References Universe::EmpireKnownDestroyedObjectIDs(), ErrorLogger, ObjectMap::get(), HumanClientApp::GetApp(), GetUniverse(), Objects(), and StarlaneEndPointsFromSystemPositions().
Referenced by MapWnd::InitStarlaneRenderingBuffers().
CanResupplyAfterDestination()
bool anonymous_namespace{MapWnd.cpp}::CanResupplyAfterDestination (const std::shared_ptr< Fleet > & fleet, const RouteListType & route)
If fleet would be able to reach a system with supply after completing route.
References GetEmpire(), GetNearestSupplyRoute(), JumpsForRoute(), to_string(), TraceLogger, and WarnLogger.
Referenced by IssueExploringFleetOrders().
ClientPlayerIsModerator()
bool anonymous_namespace{MapWnd.cpp}::ClientPlayerIsModerator ()
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, HumanClientApp::GetApp(), and ClientApp::GetClientType().
Referenced by MapWnd::BuildingRightClicked(), MapWnd::FieldRightClicked(), MapWnd::FleetsRightClicked(), MapWnd::MouseEnteringSystem(), MapWnd::PlanetRightClicked(), MapWnd::RClick(), MapWnd::ShipsRightClicked(), and MapWnd::SystemRightClicked().
DeclareThreadSafeLogger()
anonymous_namespace{MapWnd.cpp}::DeclareThreadSafeLogger (effects)
ExploringFleetResupplyRoute()
OrderedRouteType anonymous_namespace{MapWnd.cpp}::ExploringFleetResupplyRoute (const std::shared_ptr< Fleet > & fleet)
Route from current system of fleet to nearest system with supply as determined by owning empire of fleet.
References FleetRouteInRange(), GetEmpire(), GetNearestSupplyRoute(), and WarnLogger.
Referenced by IssueFleetResupplyOrder().
FleetRouteInRange()
bool anonymous_namespace{MapWnd.cpp}::FleetRouteInRange (const std::shared_ptr< Fleet > & fleet, const RouteListType & route)
If fleet can determine an eta for route.
Referenced by ExploringFleetResupplyRoute(), GetOrderedFleetRoute(), and IssueFleetExploreOrder().
FractionalDistanceBetweenPoints()
double anonymous_namespace{MapWnd.cpp}::FractionalDistanceBetweenPoints (double startX, double startY, double midX, double midY, double endX, double endY)
Referenced by ScreenPosOnStarlane().
GetGasTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{MapWnd.cpp}::GetGasTexture ()
References ClientUI::ArtDir(), ClientUI::GetClientUI(), and ClientUI::GetTexture().
Referenced by MapWnd::InitSystemRenderingBuffers(), and MapWnd::RenderGalaxyGas().
GetNearestSupplyRoute()
OrderedRouteType anonymous_namespace{MapWnd.cpp}::GetNearestSupplyRoute (const Empire * empire, int dest_id, int max_jumps = -1)
Shortest route not exceeding max_jumps from dest_id to a system with supply as known to empire.
References SupplyManager::FleetSupplyableSystemIDs(), GetShortestRoute(), GetSupplyManager(), JumpsForRoute(), to_string(), TraceLogger, and WarnLogger.
Referenced by CanResupplyAfterDestination(), and ExploringFleetResupplyRoute().
GetOrderedFleetRoute()
OrderedFleetRouteType anonymous_namespace{MapWnd.cpp}::GetOrderedFleetRoute (const std::shared_ptr< Fleet > & fleet, const std::shared_ptr< System > & destination)
Route from fleet current location to destination.
References FleetRouteInRange(), OptionsDB::Get(), GetOptionsDB(), GetShortestRoute(), to_string(), TraceLogger, and WarnLogger.
Referenced by MapWnd::DispatchFleetsExploring().
GetOwnedSystemNamesIDs()
std::set<std::pair<std::string, int>, CustomRowCmp> anonymous_namespace{MapWnd.cpp}::GetOwnedSystemNamesIDs (int empire_id)
References ObjectMap::find(), and Objects().
Referenced by MapWnd::ZoomToNextOwnedSystem(), and MapWnd::ZoomToPrevOwnedSystem().
GetResPoolLaneInfo()
void anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo (int empire_id, std::unordered_map< std::set< int >, std::set< int >, hash_set > & res_pool_systems, std::unordered_map< std::set< int >, std::set< int >, hash_set > & res_group_cores, std::unordered_set< int > & res_group_core_members, std::unordered_map< int, std::set< int >> & member_to_core, std::unordered_set< int > & under_alloc_res_grp_core_members)
References ObjectMap::get(), GetEmpire(), GetPathsThroughSupplyLanes::GetPathsThroughSupplyLanes(), GetSupplyManager(), Objects(), and SupplyManager::SupplyStarlaneTraversals().
Referenced by PrepResourceConnectionLanesToRender().
GetShortestRoute()
OrderedRouteType anonymous_namespace{MapWnd.cpp}::GetShortestRoute (int empire_id, int start_id, int destination_id)
Get the shortest suitable route from start_id to destination_id as known to empire_id.
References Empires(), ObjectMap::get(), OptionsDB::Get(), GetOptionsDB(), GetPathfinder(), Objects(), and WarnLogger.
Referenced by GetNearestSupplyRoute(), and GetOrderedFleetRoute().
GetSystemNamesIDs()
std::set<std::pair<std::string, int>, CustomRowCmp> anonymous_namespace{MapWnd.cpp}::GetSystemNamesIDs ()
References Objects().
Referenced by MapWnd::ZoomToNextSystem(), and MapWnd::ZoomToPrevSystem().
ICON_DUAL_WIDTH()
const GG::X anonymous_namespace{MapWnd.cpp}::ICON_DUAL_WIDTH (64)
Referenced by MapWnd::CompleteConstruction().
ICON_SINGLE_WIDTH()
const GG::X anonymous_namespace{MapWnd.cpp}::ICON_SINGLE_WIDTH (40)
Referenced by MapWnd::CompleteConstruction().
ICON_WIDTH()
const GG::X anonymous_namespace{MapWnd.cpp}::ICON_WIDTH (24)
Referenced by MapWnd::CompleteConstruction(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::DoLayout(), and ObjectPanel::DoLayout().
InRect()
bool anonymous_namespace{MapWnd.cpp}::InRect (GG::X left, GG::Y top, GG::X right, GG::Y bottom, const GG::Pt & pt)
Referenced by MapWnd::CompleteConstruction().
IsDepartingFromSystem()
std::shared_ptr<const System> anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem (const std::shared_ptr< const Fleet > & fleet)
If the fleet has orders and is departing from a valid system, return the system.
References ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, and Objects().
Referenced by MapWnd::DeferredRefreshFleetButtons().
IsMoving()
bool anonymous_namespace{MapWnd.cpp}::IsMoving (const std::shared_ptr< const Fleet > & fleet)
If the fleet has a valid destination and it not at a system, return true.
References INVALID_OBJECT_ID.
Referenced by IsMovingOnStarlane(), and IsOffRoad().
IsMovingOnStarlane()
boost::optional<std::pair<int, int> > anonymous_namespace{MapWnd.cpp}::IsMovingOnStarlane (const std::shared_ptr< const Fleet > & fleet)
If the fleet has a valid destination, is not at a system and is on a starlane, return the starlane's endpoint system ids.
References IsMoving(), and IsOnStarlane().
Referenced by MapWnd::DeferredRefreshFleetButtons(), and MapWnd::FleetIDsOfFleetButtonsOverlapping().
IsOffRoad()
bool anonymous_namespace{MapWnd.cpp}::IsOffRoad (const std::shared_ptr< const Fleet > & fleet)
If the fleet has a valid destination and it not on a starlane, return true.
References IsMoving(), and IsOnStarlane().
Referenced by MapWnd::DeferredRefreshFleetButtons(), and MapWnd::FleetIDsOfFleetButtonsOverlapping().
IsOnStarlane()
boost::optional<std::pair<int, int> > anonymous_namespace{MapWnd.cpp}::IsOnStarlane (const std::shared_ptr< const Fleet > & fleet)
Return the starlane's endpoints if the fleet is on a starlane.
References ObjectMap::get(), and Objects().
Referenced by IsMovingOnStarlane(), and IsOffRoad().
IsQualifiedFleet()
std::shared_ptr<const Fleet> anonymous_namespace{MapWnd.cpp}::IsQualifiedFleet (const std::shared_ptr< const UniverseObject > & obj, int empire_id, const std::set< int > & known_destroyed_objects, const std::set< int > & stale_object_info)
Return fleet if obj is not destroyed, not stale, a fleet and not empty.
Referenced by MapWnd::DeferredRefreshFleetButtons().
IsStationaryInSystem()
std::shared_ptr<const System> anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem (const std::shared_ptr< const Fleet > & fleet)
If the fleet is stationary in a valid system, return the system.
References ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, and Objects().
Referenced by MapWnd::DeferredRefreshFleetButtons().
IssueExploringFleetOrders()
void anonymous_namespace{MapWnd.cpp}::IssueExploringFleetOrders (FleetIDListType & idle_fleets, SystemFleetMap & systems_being_explored, const FleetRouteType & fleet_route)
Determine and issue move order for fleet and route fleet_route.
References CanResupplyAfterDestination(), ErrorLogger, ObjectMap::get(), IssueFleetExploreOrder(), IssueFleetResupplyOrder(), Objects(), to_string(), TraceLogger, and WarnLogger.
Referenced by MapWnd::DispatchFleetsExploring().
IssueFleetExploreOrder()
bool anonymous_namespace{MapWnd.cpp}::IssueFleetExploreOrder (const std::shared_ptr< Fleet > & fleet, const RouteListType & route)
Issue order for fleet to move using route.
References FleetRouteInRange(), HumanClientApp::GetApp(), OrderSet::IssueOrder(), ClientApp::Orders(), to_string(), TraceLogger, and WarnLogger.
Referenced by IssueExploringFleetOrders().
IssueFleetResupplyOrder()
bool anonymous_namespace{MapWnd.cpp}::IssueFleetResupplyOrder (const std::shared_ptr< Fleet > & fleet)
Issue an order for fleet to move to nearest system with supply.
References ExploringFleetResupplyRoute(), HumanClientApp::GetApp(), OrderSet::IssueOrder(), JumpsForRoute(), ClientApp::Orders(), to_string(), TraceLogger, and WarnLogger.
Referenced by IssueExploringFleetOrders().
JumpsForRoute()
int anonymous_namespace{MapWnd.cpp}::JumpsForRoute (const RouteListType & route)
Number of jumps in a given route.
Referenced by CanResupplyAfterDestination(), GetNearestSupplyRoute(), and IssueFleetResupplyOrder().
MoveLineDotTexture()
std::shared_ptr<GG::Texture> anonymous_namespace{MapWnd.cpp}::MoveLineDotTexture ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by MapWnd::RenderFleetMovementLines().
PlayTurnButtonClickSound()
void anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by MapWnd::CompleteConstruction().
PositionFractionalAtDistanceBetweenPoints()
std::pair<double, double> anonymous_namespace{MapWnd.cpp}::PositionFractionalAtDistanceBetweenPoints (double X1, double Y1, double X2, double Y2, double dist)
Referenced by ScreenPosOnStarlane().
PrepFullLanesToRender()
void anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> & sys_icons, GG::GL2DVertexBuffer & starlane_vertices, GG::GLRGBAColorBuffer & starlane_colors)
References Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ErrorLogger, ObjectMap::get(), OptionsDB::Get(), HumanClientApp::GetApp(), GetOptionsDB(), GetSupplyManager(), GetUniverse(), Objects(), StarlaneEndPointsFromSystemPositions(), SupplyManager::SupplyStarlaneTraversals(), LaneEndpoints::X1, LaneEndpoints::X2, LaneEndpoints::Y1, and LaneEndpoints::Y2.
Referenced by MapWnd::InitStarlaneRenderingBuffers().
PrepObstructedLaneTraversalsToRender()
void anonymous_namespace{MapWnd.cpp}::PrepObstructedLaneTraversalsToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> & sys_icons, int empire_id, std::set< std::pair< int, int >> & rendered_half_starlanes, GG::GL2DVertexBuffer & starlane_vertices, GG::GLRGBAColorBuffer & starlane_colors)
References Universe::EmpireKnownDestroyedObjectIDs(), Empires(), ErrorLogger, ObjectMap::get(), HumanClientApp::GetApp(), GetEmpire(), GetSupplyManager(), GetUniverse(), Objects(), StarlaneEndPointsFromSystemPositions(), SupplyManager::SupplyObstructedStarlaneTraversals(), LaneEndpoints::X1, LaneEndpoints::X2, LaneEndpoints::Y1, and LaneEndpoints::Y2.
Referenced by MapWnd::InitStarlaneRenderingBuffers().
PrepResourceConnectionLanesToRender()
void anonymous_namespace{MapWnd.cpp}::PrepResourceConnectionLanesToRender (const std::unordered_map< int, std::shared_ptr< SystemIcon >> & sys_icons, int empire_id, std::set< std::pair< int, int >> & rendered_half_starlanes, GG::GL2DVertexBuffer & rc_starlane_vertices, GG::GLRGBAColorBuffer & rc_starlane_colors)
References Universe::EmpireKnownDestroyedObjectIDs(), ErrorLogger, ObjectMap::get(), HumanClientApp::GetApp(), GetEmpire(), GetResPoolLaneInfo(), GetUniverse(), Objects(), StarlaneEndPointsFromSystemPositions(), LaneEndpoints::X1, LaneEndpoints::X2, LaneEndpoints::Y1, and LaneEndpoints::Y2.
Referenced by MapWnd::InitStarlaneRenderingBuffers().
SCALE_LINE_HEIGHT()
const GG::Y anonymous_namespace{MapWnd.cpp}::SCALE_LINE_HEIGHT (20)
Referenced by MapWnd::CompleteConstruction().
SCALE_LINE_MAX_WIDTH()
const GG::X anonymous_namespace{MapWnd.cpp}::SCALE_LINE_MAX_WIDTH (240)
Referenced by MapWnd::CompleteConstruction(), and MapWnd::InitializeWindows().
ScreenPosOnStarlane()
boost::optional<std::pair<double, double> > anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarlane (double X, double Y, int lane_start_sys_id, int lane_end_sys_id, const LaneEndpoints & screen_lane_endpoints)
References ClientApp::EmpireID(), EmpireKnownObjects(), ErrorLogger, FractionalDistanceBetweenPoints(), ObjectMap::get(), HumanClientApp::GetApp(), PositionFractionalAtDistanceBetweenPoints(), LaneEndpoints::X1, LaneEndpoints::X2, LaneEndpoints::Y1, and LaneEndpoints::Y2.
Referenced by MapWnd::MovementLineData::MovementLineData(), and MapWnd::MovingFleetMapPositionOnLane().
SITREP_PANEL_HEIGHT()
const GG::Y anonymous_namespace{MapWnd.cpp}::SITREP_PANEL_HEIGHT (200)
Referenced by MapWnd::InitializeWindows().
SITREP_PANEL_WIDTH()
const GG::X anonymous_namespace{MapWnd.cpp}::SITREP_PANEL_WIDTH (400)
Referenced by MapWnd::InitializeWindows().
StarlaneEndPointsFromSystemPositions()
LaneEndpoints anonymous_namespace{MapWnd.cpp}::StarlaneEndPointsFromSystemPositions (double X1, double Y1, double X2, double Y2)
References ClientUI::SystemCircleSize().
Referenced by CalculateStarlaneEndpoints(), PrepFullLanesToRender(), PrepObstructedLaneTraversalsToRender(), and PrepResourceConnectionLanesToRender().
ToggleBoolOption()
bool anonymous_namespace{MapWnd.cpp}::ToggleBoolOption (const std::string & option_name)
References OptionsDB::Get(), GetOptionsDB(), and OptionsDB::Set().
Referenced by MapWnd::ConnectKeyboardAcceleratorSignals().
TOOLBAR_HEIGHT()
const GG::Y anonymous_namespace{MapWnd.cpp}::TOOLBAR_HEIGHT (32)
Referenced by MapWnd::DoLayout().
WndBottom()
GG::Y anonymous_namespace{MapWnd.cpp}::WndBottom (const GG::Wnd * wnd)
Referenced by MapWnd::CompleteConstruction().
WndLeft()
GG::X anonymous_namespace{MapWnd.cpp}::WndLeft (const GG::Wnd * wnd)
Referenced by MapWnd::CompleteConstruction().
WndRight()
GG::X anonymous_namespace{MapWnd.cpp}::WndRight (const GG::Wnd * wnd)
Referenced by MapWnd::CompleteConstruction().
WndTop()
GG::Y anonymous_namespace{MapWnd.cpp}::WndTop (const GG::Wnd * wnd)
Referenced by MapWnd::CompleteConstruction().
ZOOM_SLIDER_HEIGHT()
const GG::Y anonymous_namespace{MapWnd.cpp}::ZOOM_SLIDER_HEIGHT (200)
Referenced by MapWnd::CompleteConstruction().
ZoomScaleFactor()
double anonymous_namespace{MapWnd.cpp}::ZoomScaleFactor (double steps_in)
References ErrorLogger, ZOOM_IN_MAX_STEPS, and ZOOM_IN_MIN_STEPS.
Referenced by MapWnd::ZoomFactor().
Variable Documentation
COMBAT_REPORT_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::COMBAT_REPORT_WND_NAME = "combat.summary"
Referenced by MapWnd::CompleteConstruction().
dot_star_texture_coords
GG::GLTexCoordBuffer anonymous_namespace{MapWnd.cpp}::dot_star_texture_coords
Referenced by MapWnd::RenderFleetMovementLines(), and MapWnd::RenderMovementLine().
dot_vertices_buffer
GG::GL2DVertexBuffer anonymous_namespace{MapWnd.cpp}::dot_vertices_buffer
Referenced by MapWnd::RenderMovementLine().
FLEET_DETAIL_ARMED_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_ARMED_COUNT {UserStringNop("MAP_FLEET_ARMED_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_CARRIER_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_CARRIER_COUNT {UserStringNop("MAP_FLEET_CARRIER_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_COLONY_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_COLONY_COUNT {UserStringNop("MAP_FLEET_COLONY_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_PART_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_PART_COUNT {UserStringNop("MAP_FLEET_PART_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_SHIP_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SHIP_COUNT {UserStringNop("MAP_FLEET_SHIP_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_SLOT_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_SLOT_COUNT {UserStringNop("MAP_FLEET_SLOT_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_TROOP_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_TROOP_COUNT {UserStringNop("MAP_FLEET_TROOP_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
FLEET_DETAIL_UNARMED_COUNT
const std::string anonymous_namespace{MapWnd.cpp}::FLEET_DETAIL_UNARMED_COUNT {UserStringNop("MAP_FLEET_UNARMED_COUNT")}
Referenced by anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::DoLayout(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::PreRender(), and anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateValues().
GOVERNMENT_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::GOVERNMENT_WND_NAME = "map.government"
Referenced by MapWnd::CompleteConstruction().
ICON_SIZE
const GG::Pt anonymous_namespace{MapWnd.cpp}::ICON_SIZE {GG::X{24}, GG::Y{24}}
Referenced by MapWnd::CompleteConstruction(), EncyclopediaDetailPanel::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
LAYOUT_MARGIN
const int anonymous_namespace{MapWnd.cpp}::LAYOUT_MARGIN = 5
Referenced by MapWnd::CompleteConstruction(), and MapWnd::InitializeWindows().
MAP_PEDIA_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::MAP_PEDIA_WND_NAME = "map.pedia"
Referenced by MapWnd::CompleteConstruction().
MAP_SIDEPANEL_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::MAP_SIDEPANEL_WND_NAME = "map.sidepanel"
Referenced by MapWnd::CompleteConstruction().
MENU_ICON_SIZE
const GG::Pt anonymous_namespace{MapWnd.cpp}::MENU_ICON_SIZE {GG::X{32}, GG::Y{32}}
Referenced by MapWnd::CompleteConstruction().
MIN_SYSTEM_NAME_SIZE
const int anonymous_namespace{MapWnd.cpp}::MIN_SYSTEM_NAME_SIZE = 10
Referenced by MapWnd::MidTurnUpdate(), and MapWnd::SetZoom().
MODERATOR_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::MODERATOR_WND_NAME = "map.moderator"
Referenced by MapWnd::CompleteConstruction().
OBJECT_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::OBJECT_WND_NAME = "map.object-list"
Referenced by MapWnd::CompleteConstruction().
SITREP_WND_NAME
const std::string anonymous_namespace{MapWnd.cpp}::SITREP_WND_NAME = "map.sitrep"
Referenced by MapWnd::CompleteConstruction().
temp_bool
bool anonymous_namespace{MapWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
TWO_PI
constexpr double anonymous_namespace{MapWnd.cpp}::TWO_PI = 2.0*3.1415926536
Referenced by MapWnd::InitFieldRenderingBuffers(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitVisibilityRadiiRenderingBuffers(), MapWnd::RenderMovementLineETAIndicators(), and MapWnd::RenderSystems().
ZOOM_IN_MAX_STEPS
const double anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MAX_STEPS = 12.0
Referenced by MapWnd::CompleteConstruction(), MapWnd::SetZoom(), and ZoomScaleFactor().
ZOOM_IN_MIN_STEPS
const double anonymous_namespace{MapWnd.cpp}::ZOOM_IN_MIN_STEPS = -10.0
Referenced by MapWnd::CompleteConstruction(), MapWnd::SetZoom(), and ZoomScaleFactor().
ZOOM_MAX
const double anonymous_namespace{MapWnd.cpp}::ZOOM_MAX = std::pow(ZOOM_STEP_SIZE, ZOOM_IN_MAX_STEPS)
Referenced by MapWnd::InitTurnRendering(), and MapWnd::MapScaleLine::Update().
ZOOM_MIN
const double anonymous_namespace{MapWnd.cpp}::ZOOM_MIN = std::pow(ZOOM_STEP_SIZE, ZOOM_IN_MIN_STEPS)
Referenced by MapWnd::MapScaleLine::Update().
ZOOM_STEP_SIZE
const double anonymous_namespace{MapWnd.cpp}::ZOOM_STEP_SIZE = std::pow(2.0, 1.0/4.0)
Referenced by MapWnd::MapScaleLine::Update().