FreeOrion: anonymous_namespace{UniverseGenerator.cpp} Namespace Reference
anonymous_namespace{UniverseGenerator.cpp} Namespace Reference
Functions
bool ConnectedWithin (int system1, int system2, int maxLaneJumps, const std::map< int, std::set< int >> &system_lanes)
Used by GenerateStarlanes.
void CullAngularlyTooCloseLanes (double max_lane_uvect_dot_product, std::map< int, std::set< int >> &system_lanes, const std::map< int, std::shared_ptr< System >> &systems)
Removes lanes from passed graph that are angularly too close to each other.
void CullTooLongLanes (double max_lane_length, std::map< int, std::set< int >> &system_lanes, const std::map< int, std::shared_ptr< System >> &systems)
Removes lanes from passed graph that are angularly too close to each other.
DeclareThreadSafeLogger (effects)
int IntSetMapSizeCount (const std::map< int, std::set< int >> &in)
Function Documentation
ConnectedWithin()
bool anonymous_namespace{UniverseGenerator.cpp}::ConnectedWithin (int system1, int system2, int maxLaneJumps, const std::map< int, std::set< int >> & system_lanes)
Used by GenerateStarlanes.
Determines if two systems are connected by maxLaneJumps or less edges on graph.
Referenced by CullAngularlyTooCloseLanes(), CullTooLongLanes(), and GenerateStarlanes().
CullAngularlyTooCloseLanes()
void anonymous_namespace{UniverseGenerator.cpp}::CullAngularlyTooCloseLanes (double max_lane_uvect_dot_product, std::map< int, std::set< int >> & system_lanes, const std::map< int, std::shared_ptr< System >> & systems)
Removes lanes from passed graph that are angularly too close to each other.
componenets of vectors of lanes of current system, indexed by destination system number
References ConnectedWithin(), and ErrorLogger.
Referenced by GenerateStarlanes().
CullTooLongLanes()
void anonymous_namespace{UniverseGenerator.cpp}::CullTooLongLanes (double max_lane_length, std::map< int, std::set< int >> & system_lanes, const std::map< int, std::shared_ptr< System >> & systems)
Removes lanes from passed graph that are angularly too close to each other.
References ConnectedWithin(), DebugLogger, IntSetMapSizeCount(), and TraceLogger.
Referenced by GenerateStarlanes().
DeclareThreadSafeLogger()
anonymous_namespace{UniverseGenerator.cpp}::DeclareThreadSafeLogger (effects)
IntSetMapSizeCount()
int anonymous_namespace{UniverseGenerator.cpp}::IntSetMapSizeCount (const std::map< int, std::set< int >> & in)
Referenced by CullTooLongLanes(), and GenerateStarlanes().