FreeOrion: Delauney Namespace Reference
Delauney Namespace Reference
Classes
class DTPoint
simple 2D point.
class DTTriangle
list of three interger array indices, and some additional info about the triangle that the corresponding points make up, such as the circumcentre and radius, and a function to find if another point is in the circumcircle
class SortValInt
Functions
std::list< Delauney::DTTriangle > DelauneyTriangulate (const std::vector< std::shared_ptr< System >> &systems_vec)
Runs a Delauney Triangulation on a set of 2D points corresponding to the locations of the systems in systems_vec.
Function Documentation
DelauneyTriangulate()
std::list<Delauney::DTTriangle> Delauney::DelauneyTriangulate (const std::vector< std::shared_ptr< System >> & systems_vec)
Runs a Delauney Triangulation on a set of 2D points corresponding to the locations of the systems in systems_vec.
References DebugLogger, ErrorLogger, GetUniverse(), Delauney::DTTriangle::PointInCircumCircle(), Universe::UniverseWidth(), and Delauney::DTTriangle::Verts().
Referenced by GenerateStarlanes().