FreeOrion: anonymous_namespace{Supply.cpp} Namespace Reference
anonymous_namespace{Supply.cpp} Namespace Reference
Functions
float DistanceBetweenObjects (int obj1_id, int obj2_id)
float EmpireTotalSupplyRange (int empire_id)
std::pair< float, float > EmpireTotalSupplyRangeSumInSystem (int empire_id, int system_id)
Variables
static const std::map< int, float > EMPTY_INT_FLOAT_MAP
static const std::set< std::pair< int, int > > EMPTY_INT_PAIR_SET
static const std::set< int > EMPTY_INT_SET
static const std::set< std::set< int > > EMPTY_INT_SET_SET
Function Documentation
DistanceBetweenObjects()
float anonymous_namespace{Supply.cpp}::DistanceBetweenObjects (int obj1_id, int obj2_id)
References GetSystem().
Referenced by SupplyManager::Update().
EmpireTotalSupplyRange()
float anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRange (int empire_id)
References ALL_EMPIRES, METER_SUPPLY, and Objects().
Referenced by SupplyManager::Update().
EmpireTotalSupplyRangeSumInSystem()
std::pair<float, float> anonymous_namespace{Supply.cpp}::EmpireTotalSupplyRangeSumInSystem (int empire_id, int system_id)
References ALL_EMPIRES, GetSystem(), INVALID_OBJECT_ID, METER_MAX_SUPPLY, METER_SUPPLY, and Objects().
Referenced by SupplyManager::Update().
Variable Documentation
EMPTY_INT_FLOAT_MAP
const std::map<int, float> anonymous_namespace{Supply.cpp}::EMPTY_INT_FLOAT_MAP static
Referenced by SupplyManager::PropagatedSupplyDistances(), and SupplyManager::PropagatedSupplyRanges().
EMPTY_INT_PAIR_SET
const std::set<std::pair<int, int> > anonymous_namespace{Supply.cpp}::EMPTY_INT_PAIR_SET static
Referenced by SupplyManager::SupplyObstructedStarlaneTraversals(), and SupplyManager::SupplyStarlaneTraversals().
EMPTY_INT_SET
const std::set<int> anonymous_namespace{Supply.cpp}::EMPTY_INT_SET static
Referenced by SupplyManager::FleetSupplyableSystemIDs().
EMPTY_INT_SET_SET
const std::set<std::set<int> > anonymous_namespace{Supply.cpp}::EMPTY_INT_SET_SET static
Referenced by SupplyManager::ResourceSupplyGroups().