FreeOrion: Effect Namespace Reference
Effect Namespace Reference
Classes
struct AccountingInfo
Accounting information about what the causes are and changes produced by effects groups acting on meters of objects.
class AddSpecial
Adds the Special with the name name to the target object.
class AddStarlanes
Creates starlane(s) between the target system and systems that match other_lane_endpoint_condition.
class Conditional
Executes a set of effects if an execution-time condition is met, or an alterative set of effects if the condition is not met.
class CreateBuilding
Creates a new Building with specified type on the target Planet.
class CreateField
Creates a new Field with specified field_type_name FieldType of the specified size.
class CreatePlanet
Creates a new Planet with specified type and size at the system with specified location_id.
class CreateShip
Creates a new Ship with specified predefined_ship_design_name design from those in the list of PredefinedShipDesignManager, and owned by the empire with the specified empire_id.
class CreateSystem
Creates a new system with the specified colour and at the specified location.
class Destroy
Destroys the target object.
class Effect
The base class for all Effects.
struct EffectCause
Description of cause of an effect: the general cause type, and the specific cause.
class EffectsGroup
Contains one or more Effects, a Condition which indicates the objects in the scope of the Effect(s), and a Condition which indicates whether or not the Effect(s) will be executed on the objects in scope during the current turn.
class GenerateSitRepMessage
Generates a sitrep message for the empire with id recipient_empire_id.
class GiveEmpireTech
class MoveInOrbit
Moves an UniverseObject to a location as though it was moving in orbit of some object or position on the map.
class MoveTo
Moves an UniverseObject to a location of another UniverseObject that matches the condition location_condition.
class MoveTowards
Moves an UniverseObject a specified distance towards some object or position on the map.
class NoOp
Does nothing when executed.
class RemoveSpecial
Removes the Special with the name name to the target object.
class RemoveStarlanes
Removes starlane(s) between the target system and systems that match other_lane_endpoint_condition.
class SetAggression
Sets aggression level of the target object.
class SetDestination
Sets the route of the target fleet to move to an UniverseObject that matches the condition location_condition.
class SetEmpireCapital
Makes the target planet the capital of its owner's empire.
class SetEmpireMeter
Sets the indicated meter on the empire with the indicated id to the indicated value.
class SetEmpireStockpile
Sets the empire stockpile of the target's owning empire to value.
class SetEmpireTechProgress
Sets whether an empire has researched at tech, and how much research progress towards that tech has been completed.
class SetMeter
Sets the meter of the given kind to value.
class SetOverlayTexture
Applies an overlay texture to Systems.
class SetOwner
Sets empire empire_id as the owner of the target.
class SetPlanetSize
Sets the planet size of the target to size.
class SetPlanetType
Sets the planet type of the target to type.
class SetShipPartMeter
Sets the indicated meter on all ship parts in the indicated subset.
class SetSpecies
Sets the species on the target to species_name.
class SetSpeciesEmpireOpinion
Sets the opinion of Species species for empire with id empire_id to opinion.
class SetSpeciesSpeciesOpinion
Sets the opinion of Species opinionated_species for other species rated_species to opinion.
class SetStarType
Sets the star type of the target to type.
class SetTexture
Applies a texture to Planets.
class SetVisibility
Sets visibility of an object for an empire, independent of standard visibility mechanics.
struct SourcedEffectsGroup
Combination of an EffectsGroup and the id of a source object.
struct TargetsAndCause
Combination of targets and cause for an effects group.
class Victory
Causes the owner empire of the target object to win the game.
Typedefs
typedef std::unordered_map< int, boost::container::flat_map< MeterType, std::vector< AccountingInfo > > > AccountingMap
Effect accounting information for all meters of all objects that are acted on by effects.
typedef std::vector< std::pair< SourcedEffectsGroup, TargetsAndCause > > TargetsCauses
Map from (effects group and source object) to target set of for that effects group with that source object.
typedef std::vector< std::shared_ptr< UniverseObject > > TargetSet
Functions
FO_COMMON_API std::string Dump (const std::vector< std::shared_ptr< EffectsGroup >> &effects_groups)
Returns a single string which Dumps a vector of EffectsGroups.
Typedef Documentation
AccountingMap
typedef std::unordered_map< int, boost::container::flat_map< MeterType, std::vector< AccountingInfo > > > Effect::AccountingMap
Effect accounting information for all meters of all objects that are acted on by effects.
TargetsCauses
typedef std::vector< std::pair< SourcedEffectsGroup, TargetsAndCause > > Effect::TargetsCauses
Map from (effects group and source object) to target set of for that effects group with that source object.
A multimap is used so that a single source object can have multiple instances of the same effectsgroup. This is useful when a Ship has multiple copies of the same effects group due to having multiple copies of the same ship part in its design.
TargetSet
typedef std::vector< std::shared_ptr< UniverseObject > > Effect::TargetSet
Function Documentation
Dump()
std::string Effect::Dump (const std::vector< std::shared_ptr< EffectsGroup >> & effects_groups)
Returns a single string which Dumps a vector of EffectsGroups.
Referenced by ObjectMap::all(), Condition::All::All(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Species::CombatTargets(), ValueRef::ValueRef< ToType >::ConstantExpr(), ValueRef::Constant< T >::ConstantExpr(), ValueRef::Operation< T >::ConstantExpr(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), FieldType::Description(), BuildingType::Description(), ResearchQueue::Element::Element(), ResearchQueue::EmpireID(), Condition::None::GetDefaultInitialCandidateObjects(), SitRepEntry::GetLabelString(), FocusType::Graphic(), Effect::GenerateSitRepMessage::IsSitrepEffect(), ItemSpec::ItemSpec(), MultiplayerLobbyData::MultiplayerLobbyData(), Special::Name(), ShipDesign::PartClassCount(), Effect::EffectsGroup::Priority(), DiplomaticMessage::RecipientEmpireID(), BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), Tech::ShortDescription(), Condition::Condition::SourceInvariant(), Condition::RootCandidate::SourceInvariant(), Condition::Target::SourceInvariant(), Condition::Capital::SourceInvariant(), Condition::Monster::SourceInvariant(), Condition::Armed::SourceInvariant(), Condition::Stationary::SourceInvariant(), Condition::Aggressive::SourceInvariant(), Condition::CanColonize::SourceInvariant(), Condition::CanProduceShips::SourceInvariant(), PopCenter::SpeciesName(), System::SystemID(), Condition::Source::TargetInvariant(), and SpecialsPanel::Update().