FreeOrion: anonymous_namespace{SitRepEntry.cpp} Namespace Reference
anonymous_namespace{SitRepEntry.cpp} Namespace Reference
Functions
SitRepEntry GenericCombatDamagedObjectSitrep (int combat_system_id)
SitRepEntry GenericCombatDestroyedObjectSitrep (int combat_system_id)
Function Documentation
GenericCombatDamagedObjectSitrep()
SitRepEntry anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep (int combat_system_id)
References VarText::AddVariable(), CurrentTurn(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by CreateCombatDamagedObjectSitRep().
GenericCombatDestroyedObjectSitrep()
SitRepEntry anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep (int combat_system_id)
References VarText::AddVariable(), CurrentTurn(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by CreateCombatDamagedObjectSitRep(), and CreateCombatDestroyedObjectSitRep().