FreeOrion: boost::asio Namespace Reference
boost::asio Namespace Reference
Classes
struct thread_pool
Typedefs
typedef io_service io_context
Functions
void post (const thread_pool &, std::function< void()> func)
Typedef Documentation
io_context
typedef io_service boost::asio::io_context
Function Documentation
post()
void boost::asio::post (const thread_pool & , std::function< void()> func)
Referenced by anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations(), EncyclopediaDetailPanel::HandleSearchTextEntered(), and boost::asio::thread_pool::join().