FreeOrion: anonymous_namespace{ObjectMap.cpp} Namespace Reference
anonymous_namespace{ObjectMap.cpp} Namespace Reference
Functions
template<typename T >
static void ClearMap (ObjectMap::container_type< T > &map)
template<typename T >
void EraseFromMap (ObjectMap::container_type< T > &map, int id)
template<typename T >
void TryInsertIntoMap (ObjectMap::container_type< T > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< Ship > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< Fleet > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< Building > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< Planet > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< System > &map, std::shared_ptr< UniverseObject > item)
template<>
void TryInsertIntoMap (ObjectMap::container_type< Field > &map, std::shared_ptr< UniverseObject > item)
Function Documentation
ClearMap()
template<typename T > static void anonymous_namespace{ObjectMap.cpp}::ClearMap (ObjectMap::container_type< T > & map) static
Referenced by ObjectMap::clear(), ObjectMap::CopyObjectsToSpecializedMaps(), and ObjectMap::UpdateCurrentDestroyedObjects().
EraseFromMap()
template<typename T > void anonymous_namespace{ObjectMap.cpp}::EraseFromMap (ObjectMap::container_type< T > & map, int id)
Referenced by ObjectMap::erase().
TryInsertIntoMap() [1/7]
template<typename T > void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< T > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [2/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< Ship > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [3/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< Fleet > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [4/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< Building > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [5/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< Planet > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [6/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< System > & map, std::shared_ptr< UniverseObject > item)
TryInsertIntoMap() [7/7]
template<> void anonymous_namespace{ObjectMap.cpp}::TryInsertIntoMap (ObjectMap::container_type< Field > & map, std::shared_ptr< UniverseObject > item)
Referenced by ObjectMap::CopyObjectsToSpecializedMaps(), and ObjectMap::insertCore().