FreeOrion: anonymous_namespace{PlayerListWnd.cpp} Namespace Reference
anonymous_namespace{PlayerListWnd.cpp} Namespace Reference
Classes
class DiplomaticStatusIndicator
Shows specified diplomatic status from specified empire to each other empire.
class PlayerDataPanel
Represents a player.
class PlayerRow
Functions
std::shared_ptr< GG::Texture > AIIcon ()
std::shared_ptr< GG::Texture > AlliedIcon ()
std::shared_ptr< GG::Texture > DetectionIcon ()
std::shared_ptr< GG::Texture > HostIcon ()
std::shared_ptr< GG::Texture > HumanIcon ()
std::shared_ptr< GG::Texture > LostIcon ()
std::function< void()> MakeSendDiplomaticAction (const int client_empire_id, const int clicked_empire_id, const std::function< DiplomaticMessage(int, int)> &message)
std::shared_ptr< GG::Texture > MessageIcon ()
std::shared_ptr< GG::Texture > ModeratorIcon ()
std::shared_ptr< GG::Texture > ObserverIcon ()
std::shared_ptr< GG::Texture > PeaceIcon ()
std::shared_ptr< GG::Texture > PlayingIcon ()
std::shared_ptr< GG::Texture > ProductionIcon ()
std::shared_ptr< GG::Texture > ResearchIcon ()
std::shared_ptr< GG::Texture > ShipIcon ()
std::shared_ptr< GG::Texture > UnknownIcon ()
std::shared_ptr< GG::Texture > WaitingIcon ()
std::shared_ptr< GG::Texture > WarIcon ()
std::shared_ptr< GG::Texture > WonIcon ()
Variables
const int DATA_PANEL_BORDER = 1
Function Documentation
AIIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::AIIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
AlliedIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::AlliedIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::CompleteConstruction(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
DetectionIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::DetectionIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
HostIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::HostIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
HumanIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::HumanIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
LostIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::LostIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
MakeSendDiplomaticAction()
std::function<void()> anonymous_namespace{PlayerListWnd.cpp}::MakeSendDiplomaticAction (const int client_empire_id, const int clicked_empire_id, const std::function< DiplomaticMessage(int, int)> & message)
References DiplomacyMessage(), HumanClientApp::GetApp(), ClientApp::Networking(), and ClientNetworking::SendMessage().
Referenced by PlayerListWnd::PlayerRightClicked().
MessageIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::MessageIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
ModeratorIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::ModeratorIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
ObserverIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::ObserverIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
PeaceIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::PeaceIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::CompleteConstruction(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
PlayingIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::PlayingIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
ProductionIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::ProductionIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
ResearchIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::ResearchIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
ShipIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::ShipIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
UnknownIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::UnknownIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::CompleteConstruction(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
WaitingIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::WaitingIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
WarIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::WarIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::CompleteConstruction(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
WonIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{PlayerListWnd.cpp}::WonIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
Variable Documentation
DATA_PANEL_BORDER
const int anonymous_namespace{PlayerListWnd.cpp}::DATA_PANEL_BORDER = 1