FreeOrion: anonymous_namespace{IntroScreen.cpp} Namespace Reference
anonymous_namespace{IntroScreen.cpp} Namespace Reference
Functions
const GG::Y MAIN_MENU_HEIGHT (450)
const GG::X MAIN_MENU_WIDTH (200)
void Options (OptionsDB &db)
Variables
bool foo_bool = RegisterOptions(&Options)
Function Documentation
const GG::Y anonymous_namespace{IntroScreen.cpp}::MAIN_MENU_HEIGHT (450)
Referenced by IntroScreen::CompleteConstruction().
const GG::X anonymous_namespace{IntroScreen.cpp}::MAIN_MENU_WIDTH (200)
Referenced by IntroScreen::CompleteConstruction().
void anonymous_namespace{IntroScreen.cpp}::Options (OptionsDB & db)
References OptionsDB::Add(), OptionsDB::AddFlag(), and UserStringNop.
Variable Documentation
bool anonymous_namespace{IntroScreen.cpp}::foo_bool = RegisterOptions(&Options)