FreeOrion: anonymous_namespace{ServerWrapper.cpp} Namespace Reference
anonymous_namespace{ServerWrapper.cpp} Namespace Reference
Classes
class FleetPlanWrapper
class MonsterFleetPlanWrapper
Functions
void AddSpecial (int object_id, const std::string special_name)
int AllEmpires ()
int CreateBuilding (const std::string &building_type, int planet_id, int empire_id)
int CreateField (const std::string &field_type_name, double x, double y, double size)
std::shared_ptr< Field > CreateFieldImpl (const std::string &field_type_name, double x, double y, double size)
int CreateFieldInSystem (const std::string &field_type_name, double size, int system_id)
int CreateFleet (const std::string &name, int system_id, int empire_id, bool aggressive=false)
int CreateMonster (const std::string &design_name, int fleet_id)
int CreateMonsterFleet (int system_id)
int CreatePlanet (PlanetSize size, PlanetType planet_type, int system_id, int orbit, const std::string &name)
int CreateShip (const std::string &name, const std::string &design_name, const std::string &species, int fleet_id)
int CreateSystem (StarType star_type, const std::string &star_name, double x, double y)
void EmpireAddShipDesign (int empire_id, const std::string &design_name)
bool EmpireSetHomeworld (int empire_id, int planet_id, const std::string &species_name)
void EmpireSetName (int empire_id, const std::string &name)
void EmpireUnlockItem (int empire_id, UnlockableItemType item_type, const std::string &item_name)
list FilterIDsWithCondition (const Condition::Condition *cond, const list &obj_ids)
void GenerateSitRep (int empire_id, const std::string &template_string, const dict &py_params, const std::string &icon)
void GenerateSitRep1 (int empire_id, const std::string &template_string, const std::string &icon)
list GetAllEmpires ()
list GetAllObjects ()
list GetAllSpecials ()
list GetAllSpecies ()
object GetName (int object_id)
list GetNativeSpecies ()
int GetOwner (int object_id)
list GetPlayableSpecies ()
tuple GetPos (int object_id)
object GetResourceDirWrapper ()
list GetSystems ()
double GetUniverseWidth ()
double GetX (int object_id)
double GetY (int object_id)
int InvalidObjectID ()
double InvalidPosition ()
int JumpDistanceBetweenSystems (int system1_id, int system2_id)
float LargeMeterValue ()
double LinearDistance (int system1_id, int system2_id)
list LoadFleetPlanList ()
list LoadItemSpecList ()
list LoadMonsterFleetPlanList ()
list LoadStartingBuildings ()
list ObjectsGetSystems (const list &obj_ids)
list PlanetAvailableFoci (int planet_id)
object PlanetCardinalSuffix (int planet_id)
object PlanetGetFocus (int planet_id)
PlanetSize PlanetGetSize (int planet_id)
object PlanetGetSpecies (int planet_id)
PlanetType PlanetGetType (int planet_id)
bool PlanetMakeColony (int planet_id, int empire_id, const std::string &species, double population)
bool PlanetMakeOutpost (int planet_id, int empire_id)
void PlanetSetFocus (int planet_id, const std::string &focus)
void PlanetSetSize (int planet_id, PlanetSize planet_size)
void PlanetSetSpecies (int planet_id, const std::string &species_name)
void PlanetSetType (int planet_id, PlanetType planet_type)
void RemoveSpecial (int object_id, const std::string special_name)
void SetName (int object_id, const std::string &name)
void SetUniverseWidth (double width)
bool ShipDesignCreate (const std::string &name, const std::string &description, const std::string &hull, const list &py_parts, const std::string &icon, const std::string &model, bool monster)
list ShipDesignGetMonsterList ()
list ShipDesignGetPremadeList ()
bool SpecialHasLocation (const std::string special_name)
list SpecialLocations (const std::string special_name, const list &object_ids)
int SpecialSpawnLimit (const std::string special_name)
double SpecialSpawnRate (const std::string special_name)
void SpeciesAddHomeworld (const std::string &species_name, int homeworld_id)
bool SpeciesCanColonize (const std::string &species_name)
PlanetEnvironment SpeciesGetPlanetEnvironment (const std::string &species_name, PlanetType planet_type)
object SpeciesPreferredFocus (const std::string &species_name)
void SpeciesRemoveHomeworld (const std::string &species_name, int homeworld_id)
void SystemAddStarlane (int from_sys_id, int to_sys_id)
list SystemFreeOrbits (int system_id)
list SystemGetFleets (int system_id)
int SystemGetNumOrbits (int system_id)
list SystemGetPlanets (int system_id)
list SystemGetStarlanes (int system_id)
StarType SystemGetStarType (int system_id)
bool SystemOrbitOccupied (int system_id, int orbit)
int SystemOrbitOfPlanet (int system_id, int planet_id)
void SystemRemoveStarlane (int from_sys_id, int to_sys_id)
void SystemSetStarType (int system_id, StarType star_type)
list SystemsWithinJumps (size_t jumps, const list &sys_ids)
Function Documentation
AddSpecial()
void anonymous_namespace{ServerWrapper.cpp}::AddSpecial (int object_id, const std::string special_name)
References ErrorLogger, ObjectMap::get(), GetSpecial(), Special::InitialCapacity(), and Objects().
Referenced by UniverseObject::Meters(), and FreeOrionPython::WrapServer().
AllEmpires()
int anonymous_namespace{ServerWrapper.cpp}::AllEmpires ()
References ALL_EMPIRES.
Referenced by FreeOrionPython::WrapServer().
CreateBuilding()
int anonymous_namespace{ServerWrapper.cpp}::CreateBuilding (const std::string & building_type, int planet_id, int empire_id)
References ErrorLogger, ObjectMap::get(), GetEmpire(), GetUniverse(), Universe::InsertNew(), INVALID_OBJECT_ID, and Objects().
Referenced by FreeOrionPython::WrapServer().
CreateField()
int anonymous_namespace{ServerWrapper.cpp}::CreateField (const std::string & field_type_name, double x, double y, double size)
References CreateFieldImpl(), and INVALID_OBJECT_ID.
Referenced by FreeOrionPython::WrapServer().
CreateFieldImpl()
std::shared_ptr<Field> anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl (const std::string & field_type_name, double x, double y, double size)
References ErrorLogger, GetFieldType(), GetUniverse(), Universe::InsertNew(), FieldType::Name(), ServerNetworking::size(), and UserString().
Referenced by CreateField(), and CreateFieldInSystem().
CreateFieldInSystem()
int anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem (const std::string & field_type_name, double size, int system_id)
References CreateFieldImpl(), ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, Objects(), and ServerNetworking::size().
Referenced by FreeOrionPython::WrapServer().
CreateFleet()
int anonymous_namespace{ServerWrapper.cpp}::CreateFleet (const std::string & name, int system_id, int empire_id, bool aggressive = false)
References ErrorLogger, ObjectMap::get(), GetUniverse(), Universe::InsertNew(), INVALID_OBJECT_ID, Objects(), to_string(), and UserString().
Referenced by CreateMonsterFleet(), and FreeOrionPython::WrapServer().
CreateMonster()
int anonymous_namespace{ServerWrapper.cpp}::CreateMonster (const std::string & design_name, int fleet_id)
References CreateShip(), and NewMonsterName().
Referenced by FreeOrionPython::WrapServer().
CreateMonsterFleet()
int anonymous_namespace{ServerWrapper.cpp}::CreateMonsterFleet (int system_id)
References ALL_EMPIRES, CreateFleet(), and UserString().
Referenced by FreeOrionPython::WrapServer().
CreatePlanet()
int anonymous_namespace{ServerWrapper.cpp}::CreatePlanet (PlanetSize size, PlanetType planet_type, int system_id, int orbit, const std::string & name)
References ErrorLogger, ObjectMap::get(), GetUniverse(), Universe::InsertNew(), INVALID_OBJECT_ID, Objects(), ServerNetworking::size(), SZ_ASTEROIDS, SZ_GASGIANT, and SZ_TINY.
Referenced by FreeOrionPython::WrapServer().
CreateShip()
int anonymous_namespace{ServerWrapper.cpp}::CreateShip (const std::string & name, const std::string & design_name, const std::string & species, int fleet_id)
References ALL_EMPIRES, ErrorLogger, ObjectMap::get(), GetEmpire(), Universe::GetGenericShipDesign(), GetSpecies(), GetUniverse(), ShipDesign::ID(), Universe::InsertNew(), INVALID_OBJECT_ID, Empire::NewShipName(), Objects(), parse::species(), to_string(), and UserString().
Referenced by CreateMonster(), and FreeOrionPython::WrapServer().
CreateSystem()
int anonymous_namespace{ServerWrapper.cpp}::CreateSystem (StarType star_type, const std::string & star_name, double x, double y)
References ErrorLogger, GetUniverse(), Universe::InsertNew(), INVALID_OBJECT_ID, and INVALID_STAR_TYPE.
Referenced by FreeOrionPython::WrapServer().
EmpireAddShipDesign()
void anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign (int empire_id, const std::string & design_name)
References Empire::AddShipDesign(), ErrorLogger, GetEmpire(), Universe::GetGenericShipDesign(), GetUniverse(), ShipDesign::ID(), and Universe::SetEmpireKnowledgeOfShipDesign().
Referenced by FreeOrionPython::WrapServer().
EmpireSetHomeworld()
bool anonymous_namespace{ServerWrapper.cpp}::EmpireSetHomeworld (int empire_id, int planet_id, const std::string & species_name)
References ErrorLogger, GetEmpire(), and SetEmpireHomeworld().
Referenced by FreeOrionPython::WrapServer().
EmpireSetName()
void anonymous_namespace{ServerWrapper.cpp}::EmpireSetName (int empire_id, const std::string & name)
References ErrorLogger, GetEmpire(), and Empire::SetName().
Referenced by FreeOrionPython::WrapServer().
EmpireUnlockItem()
void anonymous_namespace{ServerWrapper.cpp}::EmpireUnlockItem (int empire_id, UnlockableItemType item_type, const std::string & item_name)
References ErrorLogger, GetEmpire(), and Empire::UnlockItem().
Referenced by FreeOrionPython::WrapServer().
FilterIDsWithCondition()
list anonymous_namespace{ServerWrapper.cpp}::FilterIDsWithCondition (const Condition::Condition * cond, const list & obj_ids)
References ServerNetworking::end(), ErrorLogger, Condition::Condition::Eval(), Objects(), and Condition::Condition::SourceInvariant().
Referenced by anonymous_namespace{ServerWrapper.cpp}::MonsterFleetPlanWrapper::Locations(), and SpecialLocations().
GenerateSitRep()
void anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep (int empire_id, const std::string & template_string, const dict & py_params, const std::string & icon)
References Empire::AddSitRepEntry(), ALL_EMPIRES, CreateSitRep(), CurrentTurn(), Empires(), ErrorLogger, and GetEmpire().
Referenced by GenerateSitRep1(), and FreeOrionPython::WrapServer().
GenerateSitRep1()
void anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep1 (int empire_id, const std::string & template_string, const std::string & icon)
References GenerateSitRep().
Referenced by FreeOrionPython::WrapServer().
GetAllEmpires()
list anonymous_namespace{ServerWrapper.cpp}::GetAllEmpires ()
References Empires().
Referenced by FreeOrionPython::WrapServer().
GetAllObjects()
list anonymous_namespace{ServerWrapper.cpp}::GetAllObjects ()
References Objects().
Referenced by FreeOrionPython::WrapServer().
GetAllSpecials()
list anonymous_namespace{ServerWrapper.cpp}::GetAllSpecials ()
References SpecialNames().
Referenced by FreeOrionPython::WrapServer().
GetAllSpecies()
list anonymous_namespace{ServerWrapper.cpp}::GetAllSpecies ()
References GetSpeciesManager().
Referenced by FreeOrionPython::WrapServer().
GetName()
object anonymous_namespace{ServerWrapper.cpp}::GetName (int object_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
GetNativeSpecies()
list anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies ()
References GetSpeciesManager(), SpeciesManager::native_begin(), and SpeciesManager::native_end().
Referenced by FreeOrionPython::WrapServer().
GetOwner()
int anonymous_namespace{ServerWrapper.cpp}::GetOwner (int object_id)
References ALL_EMPIRES, ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
GetPlayableSpecies()
list anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies ()
References GetSpeciesManager(), SpeciesManager::playable_begin(), and SpeciesManager::playable_end().
Referenced by FreeOrionPython::WrapServer().
GetPos()
tuple anonymous_namespace{ServerWrapper.cpp}::GetPos (int object_id)
References ErrorLogger, ObjectMap::get(), UniverseObject::INVALID_POSITION, and Objects().
Referenced by FreeOrionPython::WrapServer().
GetResourceDirWrapper()
object anonymous_namespace{ServerWrapper.cpp}::GetResourceDirWrapper ()
References GetResourceDir(), and PathToString().
Referenced by FreeOrionPython::WrapServer().
GetSystems()
list anonymous_namespace{ServerWrapper.cpp}::GetSystems ()
References Objects().
Referenced by FreeOrionPython::WrapServer().
GetUniverseWidth()
double anonymous_namespace{ServerWrapper.cpp}::GetUniverseWidth ()
References GetUniverse(), and Universe::UniverseWidth().
Referenced by FreeOrionPython::WrapServer().
GetX()
double anonymous_namespace{ServerWrapper.cpp}::GetX (int object_id)
References ErrorLogger, ObjectMap::get(), UniverseObject::INVALID_POSITION, and Objects().
Referenced by FreeOrionPython::WrapServer().
GetY()
double anonymous_namespace{ServerWrapper.cpp}::GetY (int object_id)
References ErrorLogger, ObjectMap::get(), UniverseObject::INVALID_POSITION, and Objects().
Referenced by FreeOrionPython::WrapServer().
InvalidObjectID()
int anonymous_namespace{ServerWrapper.cpp}::InvalidObjectID ()
References INVALID_OBJECT_ID.
Referenced by FreeOrionPython::WrapServer().
InvalidPosition()
double anonymous_namespace{ServerWrapper.cpp}::InvalidPosition ()
References UniverseObject::INVALID_POSITION.
Referenced by FreeOrionPython::WrapServer().
JumpDistanceBetweenSystems()
int anonymous_namespace{ServerWrapper.cpp}::JumpDistanceBetweenSystems (int system1_id, int system2_id)
References GetPathfinder().
Referenced by Pathfinder::PathfinderImpl::PathfinderImpl(), and FreeOrionPython::WrapServer().
LargeMeterValue()
float anonymous_namespace{ServerWrapper.cpp}::LargeMeterValue ()
References Meter::LARGE_VALUE.
Referenced by FreeOrionPython::WrapServer().
LinearDistance()
double anonymous_namespace{ServerWrapper.cpp}::LinearDistance (int system1_id, int system2_id)
References GetPathfinder().
Referenced by FreeOrionPython::WrapServer().
LoadFleetPlanList()
list anonymous_namespace{ServerWrapper.cpp}::LoadFleetPlanList ()
References parse::fleet_plans(), GetUniverse(), and Universe::InitiallyUnlockedFleetPlans().
Referenced by FreeOrionPython::WrapServer().
LoadItemSpecList()
list anonymous_namespace{ServerWrapper.cpp}::LoadItemSpecList ()
References GetUniverse(), Universe::InitiallyUnlockedItems(), and parse::items().
Referenced by FreeOrionPython::WrapServer().
LoadMonsterFleetPlanList()
list anonymous_namespace{ServerWrapper.cpp}::LoadMonsterFleetPlanList ()
References GetUniverse(), parse::monster_fleet_plans(), and Universe::MonsterFleetPlans().
Referenced by FreeOrionPython::WrapServer().
LoadStartingBuildings()
list anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings ()
References parse::buildings(), ErrorLogger, GetBuildingType(), GetUniverse(), and Universe::InitiallyUnlockedBuildings().
Referenced by FreeOrionPython::WrapServer().
ObjectsGetSystems()
list anonymous_namespace{ServerWrapper.cpp}::ObjectsGetSystems (const list & obj_ids)
References ServerNetworking::end(), ErrorLogger, INVALID_OBJECT_ID, and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetAvailableFoci()
list anonymous_namespace{ServerWrapper.cpp}::PlanetAvailableFoci (int planet_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetCardinalSuffix()
object anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix (int planet_id)
References ErrorLogger, ObjectMap::get(), Objects(), and UserString().
Referenced by FreeOrionPython::WrapServer().
PlanetGetFocus()
object anonymous_namespace{ServerWrapper.cpp}::PlanetGetFocus (int planet_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetGetSize()
PlanetSize anonymous_namespace{ServerWrapper.cpp}::PlanetGetSize (int planet_id)
References ErrorLogger, ObjectMap::get(), INVALID_PLANET_SIZE, and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetGetSpecies()
object anonymous_namespace{ServerWrapper.cpp}::PlanetGetSpecies (int planet_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetGetType()
PlanetType anonymous_namespace{ServerWrapper.cpp}::PlanetGetType (int planet_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetMakeColony()
bool anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony (int planet_id, int empire_id, const std::string & species, double population)
References ErrorLogger, ObjectMap::get(), GetEmpire(), GetSpecies(), Objects(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
PlanetMakeOutpost()
bool anonymous_namespace{ServerWrapper.cpp}::PlanetMakeOutpost (int planet_id, int empire_id)
References ErrorLogger, ObjectMap::get(), GetEmpire(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetSetFocus()
void anonymous_namespace{ServerWrapper.cpp}::PlanetSetFocus (int planet_id, const std::string & focus)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetSetSize()
void anonymous_namespace{ServerWrapper.cpp}::PlanetSetSize (int planet_id, PlanetSize planet_size)
References ErrorLogger, ObjectMap::get(), Objects(), SZ_ASTEROIDS, and SZ_GASGIANT.
Referenced by FreeOrionPython::WrapServer().
PlanetSetSpecies()
void anonymous_namespace{ServerWrapper.cpp}::PlanetSetSpecies (int planet_id, const std::string & species_name)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
PlanetSetType()
void anonymous_namespace{ServerWrapper.cpp}::PlanetSetType (int planet_id, PlanetType planet_type)
References ErrorLogger, ObjectMap::get(), Objects(), SZ_ASTEROIDS, SZ_GASGIANT, SZ_HUGE, and SZ_TINY.
Referenced by FreeOrionPython::WrapServer().
RemoveSpecial()
void anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial (int object_id, const std::string special_name)
References ErrorLogger, ObjectMap::get(), GetSpecial(), and Objects().
Referenced by UniverseObject::Meters(), and FreeOrionPython::WrapServer().
SetName()
void anonymous_namespace{ServerWrapper.cpp}::SetName (int object_id, const std::string & name)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by ResourceInfoPanel::Clear(), ResourceInfoPanel::ClearLocalInfo(), CombatLogWnd::CombatLogWnd(), BuildingsPanel::CompleteConstruction(), MilitaryPanel::CompleteConstruction(), MultiIconValueIndicator::CompleteConstruction(), PopulationPanel::CompleteConstruction(), ResourcePanel::CompleteConstruction(), MapWnd::CompleteConstruction(), StatisticIcon::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), ObjectRow::CompleteConstruction(), CUIWnd::CUIWnd(), FleetDetailPanel::FleetDetailPanel(), anonymous_namespace{FleetWnd.cpp}::FleetRow::FleetRow(), ShipDesign::ID(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::Init(), Empire::meter_end(), MultiMeterStatusBar::MultiMeterStatusBar(), SidePanel::PlanetPanelContainer::PlanetPanelContainer(), anonymous_namespace{PlayerListWnd.cpp}::PlayerRow::PlayerRow(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), SystemIcon::Refresh(), FleetWnd::Refresh(), BuildDesignatorWnd::BuildSelector::Refresh(), SaveFileRow::SaveFileRow(), ResearchQueueWnd::SetEmpire(), ProductionQueueWnd::SetEmpire(), ResourceInfoPanel::SetEmpireID(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), anonymous_namespace{FleetWnd.cpp}::ShipRow::ShipRow(), anonymous_namespace{SitRepPanel.cpp}::SitRepRow::SitRepRow(), SpecialsPanel::SpecialsPanel(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow(), anonymous_namespace{SidePanel.cpp}::SystemRow::SystemRow(), SitRepPanel::Update(), anonymous_namespace{GalaxySetupWnd.cpp}::UserStringRow::UserStringRow(), and FreeOrionPython::WrapServer().
SetUniverseWidth()
void anonymous_namespace{ServerWrapper.cpp}::SetUniverseWidth (double width)
References GetUniverse(), and Universe::SetUniverseWidth().
Referenced by FreeOrionPython::WrapServer().
ShipDesignCreate()
bool anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate (const std::string & name, const std::string & description, const std::string & hull, const list & py_parts, const std::string & icon, const std::string & model, bool monster)
References ALL_EMPIRES, BEFORE_FIRST_TURN, ErrorLogger, Universe::GetGenericShipDesign(), GetUniverse(), and Universe::InsertShipDesign().
Referenced by FreeOrionPython::WrapServer().
ShipDesignGetMonsterList()
list anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetMonsterList ()
References GetPredefinedShipDesignManager().
Referenced by FreeOrionPython::WrapServer().
ShipDesignGetPremadeList()
list anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetPremadeList ()
References GetPredefinedShipDesignManager().
Referenced by FreeOrionPython::WrapServer().
SpecialHasLocation()
bool anonymous_namespace{ServerWrapper.cpp}::SpecialHasLocation (const std::string special_name)
References ErrorLogger, GetSpecial(), and Special::Location().
Referenced by FreeOrionPython::WrapServer().
SpecialLocations()
list anonymous_namespace{ServerWrapper.cpp}::SpecialLocations (const std::string special_name, const list & object_ids)
References ErrorLogger, FilterIDsWithCondition(), GetSpecial(), and Special::Location().
Referenced by FreeOrionPython::WrapServer().
SpecialSpawnLimit()
int anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnLimit (const std::string special_name)
References ErrorLogger, GetSpecial(), and Special::SpawnLimit().
Referenced by FreeOrionPython::WrapServer().
SpecialSpawnRate()
double anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnRate (const std::string special_name)
References ErrorLogger, GetSpecial(), and Special::SpawnRate().
Referenced by FreeOrionPython::WrapServer().
SpeciesAddHomeworld()
void anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld (const std::string & species_name, int homeworld_id)
References Species::AddHomeworld(), ErrorLogger, SpeciesManager::GetSpecies(), SpeciesManager::GetSpeciesManager(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
SpeciesCanColonize()
bool anonymous_namespace{ServerWrapper.cpp}::SpeciesCanColonize (const std::string & species_name)
References Species::CanColonize(), ErrorLogger, SpeciesManager::GetSpecies(), SpeciesManager::GetSpeciesManager(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
SpeciesGetPlanetEnvironment()
PlanetEnvironment anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment (const std::string & species_name, PlanetType planet_type)
References ErrorLogger, Species::GetPlanetEnvironment(), GetSpecies(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
SpeciesPreferredFocus()
object anonymous_namespace{ServerWrapper.cpp}::SpeciesPreferredFocus (const std::string & species_name)
References ErrorLogger, GetSpecies(), Species::PreferredFocus(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
SpeciesRemoveHomeworld()
void anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld (const std::string & species_name, int homeworld_id)
References ErrorLogger, SpeciesManager::GetSpecies(), SpeciesManager::GetSpeciesManager(), Species::RemoveHomeworld(), and parse::species().
Referenced by FreeOrionPython::WrapServer().
SystemAddStarlane()
void anonymous_namespace{ServerWrapper.cpp}::SystemAddStarlane (int from_sys_id, int to_sys_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemFreeOrbits()
list anonymous_namespace{ServerWrapper.cpp}::SystemFreeOrbits (int system_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemGetFleets()
list anonymous_namespace{ServerWrapper.cpp}::SystemGetFleets (int system_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemGetNumOrbits()
int anonymous_namespace{ServerWrapper.cpp}::SystemGetNumOrbits (int system_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemGetPlanets()
list anonymous_namespace{ServerWrapper.cpp}::SystemGetPlanets (int system_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemGetStarlanes()
list anonymous_namespace{ServerWrapper.cpp}::SystemGetStarlanes (int system_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemGetStarType()
StarType anonymous_namespace{ServerWrapper.cpp}::SystemGetStarType (int system_id)
References ErrorLogger, ObjectMap::get(), INVALID_STAR_TYPE, and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemOrbitOccupied()
bool anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOccupied (int system_id, int orbit)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemOrbitOfPlanet()
int anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOfPlanet (int system_id, int planet_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemRemoveStarlane()
void anonymous_namespace{ServerWrapper.cpp}::SystemRemoveStarlane (int from_sys_id, int to_sys_id)
References ErrorLogger, ObjectMap::get(), and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemSetStarType()
void anonymous_namespace{ServerWrapper.cpp}::SystemSetStarType (int system_id, StarType star_type)
References ErrorLogger, ObjectMap::get(), INVALID_STAR_TYPE, and Objects().
Referenced by FreeOrionPython::WrapServer().
SystemsWithinJumps()
list anonymous_namespace{ServerWrapper.cpp}::SystemsWithinJumps (size_t jumps, const list & sys_ids)
References ServerNetworking::end(), and GetPathfinder().
Referenced by FreeOrionPython::WrapServer().