FreeOrion: parse::detail Namespace Reference
parse::detail Namespace Reference
Classes
struct arithmetic_rules
struct BracketedParserSignature
struct BracketedParserSignature< Synthesized(Inherited...)>
struct cast_T_to_int
struct color_parser_grammar
struct common_params_rules
struct condition_parser_rules_1
struct condition_parser_rules_2
struct condition_parser_rules_3
struct condition_parser_rules_4
struct condition_parser_rules_5
struct condition_parser_rules_6
struct condition_parser_rules_7
struct construct_movable
construct_movable is a functor that constructs a MovableEnvelope<T>
class deconstruct_movable
class deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1
Note: This simpler to use version of deconstruct_movable works with clang version 4.0.1 and gcc version 7.2.1 with boost 1.63.
class deconstruct_movable_vector
class deconstruct_movable_vector_pair
struct double_grammar
struct effect_parser_rules_1
struct effect_parser_rules_2
struct effect_parser_rules_3
struct effect_parser_rules_4
struct effect_parser_rules_5
struct enum_value_ref_rules
struct info_visitor
struct int_grammar
struct is_unique
A functor to determine if key will be unique in map of type, and log an error otherwise.
class Labeller
Store label_rules.
struct MoreCommonParams
class MovableEnvelope
MovableEnvelope enables the boost::spirit parser to handle a T with move semantics.
struct planet_environment_parser_rules
struct planet_size_parser_rules
struct planet_type_parser_rules
struct simple_double_parser_rules
struct simple_int_parser_rules
struct simple_variable_rules
struct single_or_bracketed_repeat
single_or_bracketed_repeat uses Parser to parser expressions with either a single element or repeated elements within square brackets.
struct single_or_repeated_string
struct star_type_parser_rules
struct string_complex_parser_grammar
struct tags_grammar
struct universe_object_type_parser_rules
struct unlockable_item_grammar
struct visibility_complex_parser_grammar
struct visibility_parser_rules
Typedefs
using color_grammar_type = grammar< color_parser_signature >
using color_parser_signature = std::array< unsigned char, 4 >()
using color_rule_type = rule< color_parser_signature >
typedef std::array< unsigned char, 4 > ColorType
template<typename T >
using complex_variable_grammar = grammar< complex_variable_signature< T > >
template<typename T >
using complex_variable_payload = MovableEnvelope< ValueRef::ComplexVariable< T > >
template<typename T >
using complex_variable_rule = rule< complex_variable_signature< T > >
template<typename T >
using complex_variable_signature = complex_variable_payload< T >()
using condition_parser_grammar = grammar< condition_signature >
using condition_parser_rule = rule< condition_signature >
using condition_payload = MovableEnvelope< Condition::Condition >
using condition_signature = condition_payload()
using effect_parser_grammar = grammar< effect_signature >
using effect_parser_rule = rule< effect_signature >
using effect_payload = MovableEnvelope< Effect::Effect >
using effect_signature = effect_payload()
template<typename T >
using enum_grammar = grammar< T()>
template<typename T >
using enum_rule = rule< T()>
template<typename T >
using expression_rule = rule< value_ref_payload< T >(), boost::spirit::qi::locals< value_ref_payload< T >, value_ref_payload< T >, ValueRef::OpType, std::vector< value_ref_payload< T > > > >
template<typename signature = boost::spirit::qi::unused_type, typename locals = boost::spirit::qi::unused_type>
using grammar = boost::spirit::qi::grammar< parse::token_iterator, parse::skipper_type, signature, locals >
using label_rule = rule<>
using name_token_rule = rule< std::string()>
typedef std::tuple< boost::optional< double >, boost::optional< double >, boost::optional< parse::detail::MovableEnvelope< Condition::Condition > > > OptCap_OptStat2_OptMoveableTargets
using PassedMessageParams = std::vector< std::pair< std::string, MovableEnvelope< ValueRef::ValueRef< std::string > >> >
using reference_token_rule = rule< ValueRef::ReferenceType()>
template<typename signature = boost::spirit::qi::unused_type, typename locals = boost::spirit::qi::unused_type>
using rule = boost::spirit::qi::rule< parse::token_iterator, parse::skipper_type, signature, locals >
template<typename T >
using statistic_payload = MovableEnvelope< ValueRef::ValueRef< T > >
template<typename T >
using statistic_rule = rule< statistic_signature< T >, boost::spirit::qi::locals< value_ref_payload< T >, ValueRef::StatisticType, value_ref_payload< std::string > > >
template<typename T >
using statistic_signature = statistic_payload< T >()
using tags_grammar_type = grammar< std::set< std::string >()>
using tags_rule_type = rule< std::set< std::string >()>
using unlockable_item_grammar_type = grammar< UnlockableItem()>
using unlockable_item_rule_type = rule< UnlockableItem()>
template<typename T >
using value_ref_grammar = detail::grammar< value_ref_signature< T > >
template<typename T >
using value_ref_payload = MovableEnvelope< ValueRef::ValueRef< T > >
template<typename T >
using value_ref_rule = detail::rule< value_ref_signature< T > >
template<typename T >
using value_ref_signature = value_ref_payload< T >()
template<typename T >
using variable_payload = MovableEnvelope< ValueRef::Variable< T > >
template<typename T >
using variable_rule = rule< variable_signature< T >, boost::spirit::qi::locals< std::vector< std::string >, ValueRef::ReferenceType > >
template<typename T >
using variable_signature = variable_payload< T >()
Functions
std::array< unsigned char, 4 > construct_color (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
effect_payload construct_GenerateSitRepMessage1 (std::string &message_string, std::string &icon, const PassedMessageParams &message_parameters, const MovableEnvelope< ValueRef::ValueRef< int >> &recipient_empire_id, EmpireAffiliationType affiliation, std::string label, bool stringtable_lookup, bool &pass)
effect_payload construct_GenerateSitRepMessage2 (std::string &message_string, std::string &icon, const PassedMessageParams &message_parameters, EmpireAffiliationType affiliation, const parse::detail::condition_payload &condition, std::string label, bool stringtable_lookup, bool &pass)
effect_payload construct_GenerateSitRepMessage3 (std::string &message_string, std::string &icon, const PassedMessageParams &message_parameters, EmpireAffiliationType affiliation, std::string label, bool stringtable_lookup, bool &pass)
const name_token_rule container_type (const parse::lexer &tok)
void default_send_error_string (const std::string &str)
template<typename T >
void initialize_bound_variable_parser (variable_rule< T > &bound_variable, variable_rule< T > &unwrapped_bound_variable, variable_rule< T > &value_wrapped_bound_variable, const name_token_rule &variable_name, const reference_token_rule &variable_scope_rule, const name_token_rule &container_type_rule, const parse::lexer &tok)
template<typename T >
void initialize_nonnumeric_statistic_parser (parse::detail::statistic_rule< T > &statistic, const parse::lexer &tok, parse::detail::Labeller &label, const parse::detail::condition_parser_grammar &condition_parser, const typename parse::detail::value_ref_rule< T > &value_ref)
template<typename T >
void initialize_nonnumeric_statistic_parser (statistic_rule< T > &statistic, const parse::lexer &tok, Labeller &label, const condition_parser_grammar &condition_parser, const value_ref_rule< T > &value_ref)
template<typename T >
void open_and_register_as_string (std::string &nameref, ::parse::detail::MovableEnvelope< ValueRef::ValueRef< T >> &obj, bool &pass)
template<typename T >
ConsumptionMap< T > OpenConsumptionEnvelopes (const common_params_rules::ConsumptionMapPackaged< T > &in, bool &pass)
Open parsed envelopes of consumption pairs.
template<typename T >
std::vector< std::unique_ptr< T > > OpenEnvelopes (const std::vector< MovableEnvelope< T >> &envelopes, bool &pass)
Free functions converting containers of MovableEnvelope to unique_ptrs.
template<typename T >
std::vector< std::pair< std::string, std::unique_ptr< T > > > OpenEnvelopes (const std::vector< std::pair< std::string, MovableEnvelope< T >>> &in, bool &pass)
template<typename K , typename V >
std::map< K, std::unique_ptr< V > > OpenEnvelopes (const std::map< K, MovableEnvelope< V >> &in, bool &pass)
template<typename Grammar , typename Arg1 >
bool parse_file (const lexer &lexer, const boost::filesystem::path &path, Arg1 &arg1)
template<typename Grammar , typename Arg1 , typename Arg2 >
bool parse_file (const lexer &lexer, const boost::filesystem::path &path, Arg1 &arg1, Arg2 &arg2)
void parse_file_common (const boost::filesystem::path &path, const parse::lexer &lexer, std::string &filename, std::string &file_contents, parse::text_iterator &first, parse::text_iterator &last, parse::token_iterator &it)
Load and parse script file(s) from given path.
bool parse_file_end_of_file_warnings (const boost::filesystem::path &path, bool parser_success, std::string &file_contents, text_iterator &first, text_iterator &last)
Report warnings about unparsed end of file and return true for a good parse.
void pretty_print (std::ostream &os, boost::spirit::info const &what)
const reference_token_rule variable_scope (const parse::lexer &tok)
Typedef Documentation
color_grammar_type
using parse::detail::color_grammar_type = typedef grammar<color_parser_signature>
color_parser_signature
using parse::detail::color_parser_signature = typedef std::array<unsigned char, 4> ()
color_rule_type
using parse::detail::color_rule_type = typedef rule<color_parser_signature>
ColorType
typedef std::array<unsigned char, 4> parse::detail::ColorType
complex_variable_grammar
template<typename T > using parse::detail::complex_variable_grammar = typedef grammar<complex_variable_signature<T> >
complex_variable_payload
template<typename T > using parse::detail::complex_variable_payload = typedef MovableEnvelope<ValueRef::ComplexVariable<T> >
complex_variable_rule
template<typename T > using parse::detail::complex_variable_rule = typedef rule<complex_variable_signature<T> >
complex_variable_signature
template<typename T > using parse::detail::complex_variable_signature = typedef complex_variable_payload<T> ()
condition_parser_grammar
typedef grammar< condition_signature > parse::detail::condition_parser_grammar
condition_parser_rule
using parse::detail::condition_parser_rule = typedef rule<condition_signature>
condition_payload
typedef parse::detail::condition_payload
condition_signature
using parse::detail::condition_signature = typedef condition_payload ()
effect_parser_grammar
using parse::detail::effect_parser_grammar = typedef grammar<effect_signature>
effect_parser_rule
using parse::detail::effect_parser_rule = typedef rule<effect_signature>
effect_payload
using parse::detail::effect_payload = typedef MovableEnvelope<Effect::Effect>
effect_signature
using parse::detail::effect_signature = typedef effect_payload ()
enum_grammar
template<typename T > using parse::detail::enum_grammar = typedef grammar<T ()>
enum_rule
template<typename T > using parse::detail::enum_rule = typedef rule<T ()>
expression_rule
template<typename T > using parse::detail::expression_rule = typedef rule< value_ref_payload<T> (), boost::spirit::qi::locals< value_ref_payload<T>, value_ref_payload<T>, ValueRef::OpType, std::vector<value_ref_payload<T> > > >
grammar
template<typename signature = boost::spirit::qi::unused_type, typename locals = boost::spirit::qi::unused_type> using parse::detail::grammar = typedef boost::spirit::qi::grammar< parse::token_iterator, parse::skipper_type, signature, locals >
label_rule
using parse::detail::label_rule = typedef rule<>
name_token_rule
using parse::detail::name_token_rule = typedef rule<std::string ()>
OptCap_OptStat2_OptMoveableTargets
typedef std::tuple< boost::optional<double>, boost::optional<double>, boost::optional<parse::detail::MovableEnvelope<Condition::Condition> > > parse::detail::OptCap_OptStat2_OptMoveableTargets
PassedMessageParams
using parse::detail::PassedMessageParams = typedef std::vector<std::pair<std::string, MovableEnvelope<ValueRef::ValueRef<std::string> >> >
reference_token_rule
using parse::detail::reference_token_rule = typedef rule<ValueRef::ReferenceType ()>
rule
template<typename signature = boost::spirit::qi::unused_type, typename locals = boost::spirit::qi::unused_type> using parse::detail::rule = typedef boost::spirit::qi::rule< parse::token_iterator, parse::skipper_type, signature, locals >
statistic_payload
template<typename T > using parse::detail::statistic_payload = typedef MovableEnvelope<ValueRef::ValueRef<T> >
statistic_rule
template<typename T > using parse::detail::statistic_rule = typedef rule< statistic_signature<T>, boost::spirit::qi::locals< value_ref_payload<T>, ValueRef::StatisticType, value_ref_payload<std::string> > >
statistic_signature
template<typename T > using parse::detail::statistic_signature = typedef statistic_payload<T> ()
tags_grammar_type
using parse::detail::tags_grammar_type = typedef grammar<std::set<std::string> ()>
tags_rule_type
using parse::detail::tags_rule_type = typedef rule<std::set<std::string> ()>
unlockable_item_grammar_type
using parse::detail::unlockable_item_grammar_type = typedef grammar<UnlockableItem ()>
unlockable_item_rule_type
using parse::detail::unlockable_item_rule_type = typedef rule<UnlockableItem ()>
value_ref_grammar
template<typename T > using parse::detail::value_ref_grammar = typedef detail::grammar<value_ref_signature<T> >
value_ref_payload
template<typename T > using parse::detail::value_ref_payload = typedef MovableEnvelope<ValueRef::ValueRef<T> >
value_ref_rule
template<typename T > using parse::detail::value_ref_rule = typedef detail::rule<value_ref_signature<T> >
value_ref_signature
template<typename T > using parse::detail::value_ref_signature = typedef value_ref_payload<T> ()
variable_payload
template<typename T > using parse::detail::variable_payload = typedef MovableEnvelope<ValueRef::Variable<T> >
variable_rule
template<typename T > using parse::detail::variable_rule = typedef rule< variable_signature<T>, boost::spirit::qi::locals< std::vector<std::string>, ValueRef::ReferenceType > >
variable_signature
template<typename T > using parse::detail::variable_signature = typedef variable_payload<T> ()
Function Documentation
construct_color()
std::array<unsigned char, 4> parse::detail::construct_color (unsigned char r, unsigned char g, unsigned char b, unsigned char a) inline
construct_GenerateSitRepMessage1()
effect_payload parse::detail::construct_GenerateSitRepMessage1 (std::string & message_string, std::string & icon, const PassedMessageParams & message_parameters, const MovableEnvelope< ValueRef::ValueRef< int >> & recipient_empire_id, EmpireAffiliationType affiliation, std::string label, bool stringtable_lookup, bool & pass)
References OpenEnvelopes().
Referenced by construct_GenerateSitRepMessage3().
construct_GenerateSitRepMessage2()
effect_payload parse::detail::construct_GenerateSitRepMessage2 (std::string & message_string, std::string & icon, const PassedMessageParams & message_parameters, EmpireAffiliationType affiliation, const parse::detail::condition_payload & condition, std::string label, bool stringtable_lookup, bool & pass)
References parse::detail::MovableEnvelope< T >::OpenEnvelope(), and OpenEnvelopes().
Referenced by construct_GenerateSitRepMessage3().
construct_GenerateSitRepMessage3()
effect_payload parse::detail::construct_GenerateSitRepMessage3 (std::string & message_string, std::string & icon, const PassedMessageParams & message_parameters, EmpireAffiliationType affiliation, std::string label, bool stringtable_lookup, bool & pass)
References construct_GenerateSitRepMessage1(), construct_GenerateSitRepMessage2(), and OpenEnvelopes().
container_type()
const parse::detail::name_token_rule parse::detail::container_type (const parse::lexer & tok)
Referenced by parse::detail::enum_value_ref_rules< UniverseObjectType >::enum_value_ref_rules(), parse::detail::simple_variable_rules< int >::simple_variable_rules(), and parse::string_parser_grammar::string_parser_grammar().
default_send_error_string()
void parse::detail::default_send_error_string (const std::string & str)
References ErrorLogger, and parse::report_error_::send_error_string.
initialize_bound_variable_parser()
template<typename T > void parse::detail::initialize_bound_variable_parser (variable_rule< T > & bound_variable, variable_rule< T > & unwrapped_bound_variable, variable_rule< T > & value_wrapped_bound_variable, const name_token_rule & variable_name, const reference_token_rule & variable_scope_rule, const name_token_rule & container_type_rule, const parse::lexer & tok)
References anonymous_namespace{EnumParser.cpp}::_val.
initialize_nonnumeric_statistic_parser() [1/2]
template<typename T > void parse::detail::initialize_nonnumeric_statistic_parser (parse::detail::statistic_rule< T > & statistic, const parse::lexer & tok, parse::detail::Labeller & label, const parse::detail::condition_parser_grammar & condition_parser, const typename parse::detail::value_ref_rule< T > & value_ref)
initialize_nonnumeric_statistic_parser() [2/2]
template<typename T > void parse::detail::initialize_nonnumeric_statistic_parser (statistic_rule< T > & statistic, const parse::lexer & tok, Labeller & label, const condition_parser_grammar & condition_parser, const value_ref_rule< T > & value_ref)
References anonymous_namespace{EnumParser.cpp}::_val.
open_and_register_as_string()
template<typename T > void parse::detail::open_and_register_as_string (std::string & nameref, ::parse::detail::MovableEnvelope< ValueRef::ValueRef< T >> & obj, bool & pass)
References ErrorLogger.
OpenConsumptionEnvelopes()
template<typename T > ConsumptionMap<T> parse::detail::OpenConsumptionEnvelopes (const common_params_rules::ConsumptionMapPackaged< T > & in, bool & pass)
Open parsed envelopes of consumption pairs.
Return a map of unique_ptr.
OpenEnvelopes() [1/3]
template<typename T > std::vector<std::unique_ptr<T> > parse::detail::OpenEnvelopes (const std::vector< MovableEnvelope< T >> & envelopes, bool & pass)
Free functions converting containers of MovableEnvelope to unique_ptrs.
Referenced by parse::construct_EffectsGroup(), construct_GenerateSitRepMessage1(), construct_GenerateSitRepMessage2(), construct_GenerateSitRepMessage3(), anonymous_namespace{EmpireStatsParser.cpp}::grammar::grammar(), anonymous_namespace{FieldsParser.cpp}::insert_fieldtype(), anonymous_namespace{PoliciesParser.cpp}::insert_policy(), anonymous_namespace{SpecialsParser.cpp}::insert_special(), anonymous_namespace{SpeciesParser.cpp}::insert_species(), anonymous_namespace{TechsParser.cpp}::insert_tech(), parse::detail::deconstruct_movable_simple_version_that_works_gcc7p2p1_and_clang4p0p1::operator()(), parse::detail::deconstruct_movable_vector::operator()(), and parse::detail::deconstruct_movable_vector_pair::operator()().
OpenEnvelopes() [2/3]
template<typename T > std::vector<std::pair<std::string, std::unique_ptr<T> > > parse::detail::OpenEnvelopes (const std::vector< std::pair< std::string, MovableEnvelope< T >>> & in, bool & pass)
OpenEnvelopes() [3/3]
template<typename K , typename V > std::map<K, std::unique_ptr<V> > parse::detail::OpenEnvelopes (const std::map< K, MovableEnvelope< V >> & in, bool & pass)
parse_file() [1/2]
template<typename Grammar , typename Arg1 > bool parse::detail::parse_file (const lexer & lexer, const boost::filesystem::path & path, Arg1 & arg1)
References parse_file_common(), and parse_file_end_of_file_warnings().
parse_file() [2/2]
template<typename Grammar , typename Arg1 , typename Arg2 > bool parse::detail::parse_file (const lexer & lexer, const boost::filesystem::path & path, Arg1 & arg1, Arg2 & arg2)
References parse_file_common(), and parse_file_end_of_file_warnings().
parse_file_common()
void parse::detail::parse_file_common (const boost::filesystem::path & path, const parse::lexer & lexer, std::string & filename, std::string & file_contents, parse::text_iterator & first, parse::text_iterator & last, parse::token_iterator & it)
Load and parse script file(s) from given path.
Parameters
[in] path absolute path to a regular file
[in] l lexer instance to use
[out] filename filename of the given path
[out] file_contents parsed contents of file(s)
[out] first content iterator
[out] it lexer iterator
References ErrorLogger, parse::file_substitution(), parse::macro_substitution(), and anonymous_namespace{About.cpp}::ReadFile().
Referenced by parse_file().
parse_file_end_of_file_warnings()
bool parse::detail::parse_file_end_of_file_warnings (const boost::filesystem::path & path, bool parser_success, std::string & file_contents, text_iterator & first, text_iterator & last)
Report warnings about unparsed end of file and return true for a good parse.
References WarnLogger.
Referenced by parse_file().
pretty_print()
void parse::detail::pretty_print (std::ostream & os, boost::spirit::info const & what)
Referenced by parse::report_error_::generate_error_string().
variable_scope()
const parse::detail::reference_token_rule parse::detail::variable_scope (const parse::lexer & tok)
References anonymous_namespace{EnumParser.cpp}::_val, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, ValueRef::EFFECT_TARGET_REFERENCE, and ValueRef::SOURCE_REFERENCE.
Referenced by parse::detail::enum_value_ref_rules< UniverseObjectType >::enum_value_ref_rules(), parse::detail::simple_variable_rules< int >::simple_variable_rules(), and parse::string_parser_grammar::string_parser_grammar().