FreeOrion: tag_parser Namespace Reference
tag_parser Namespace Reference
Functions
def add_doc_source (_file_name, _line_number, _content, _tags)
def get_link (_file, _line_number)
def parse_file (_parse_file, _tags)
Variables
abs_dir = os.path.dirname(os.path.abspath(args.get('output')))
action
all_tags = defaultdict(set)
args = vars(arguments.parse_args())
arguments
default
description = str.format('{0} ', source[2])
bool file_match = False
help
def link_str = get_link(source[0], source[1])
metavar
nargs
list output_buff = []
int source_count = 0
tag_close = args.get('tag')[1]
tag_open = args.get('tag')[0]
Function Documentation
add_doc_source()
def tag_parser.add_doc_source (_file_name, _line_number, _content, _tags)
Referenced by parse_file().
get_link()
def tag_parser.get_link (_file, _line_number)
parse_file()
def tag_parser.parse_file (_parse_file, _tags)
References add_doc_source().
Variable Documentation
abs_dir
tag_parser.abs_dir = os.path.dirname(os.path.abspath(args.get('output')))
action
tag_parser.action
Referenced by ModeratorActionMessage(), ProductionWnd.QueueItemPaused(), ProductionWnd.QueueItemUseImperialPP(), and PlayingGame.react().
all_tags
tag_parser.all_tags = defaultdict(set)
Referenced by ConditionWidget.UpdateParameterControls().
args
tag_parser.args = vars(arguments.parse_args())
Referenced by ServerApp.CreateAIClients(), Process::Impl.Impl(), Universe.InsertByEmpireWithID(), Universe.InsertID(), Universe.InsertNew(), Universe.InsertTemp(), anonymous_namespace{AIWrapper.cpp}.Issue(), main(), OptionsDB.SetDefault(), and HumanClientApp.StartServer().
arguments
tag_parser.arguments
Initial value:
 =  argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,
                                     description='Parses files for content tags and creates and a doxygen suitable listing from the parse results.',
                                     epilog='%(prog)s Parses FILES in the MATCH directory for TAGs.'
                                            'The comment lines may be in either # or /// form in a file,'
                                            ' but only one form throughout a file.  The results of the parse are'
                                            ' formatted for a doxygen ".dox" file.')
default
tag_parser.default
Referenced by anonymous_namespace{SidePanel.cpp}.PlanetDiameter().
description
tag_parser.description = str.format('{0} ', source[2])
Referenced by GameRules.Add(), DesignWnd::MainPanel.AddDesign(), anonymous_namespace{LoggerWithOptionsDB.cpp}.AddLoggerToOptionsDB(), parse.construct_EffectsGroup(), Special.Description(), FocusType.FocusType(), Species.GameplayDescription(), GG_ENUM(), anonymous_namespace{ShipPart.cpp}.IncreaseMeterRuleScaled(), anonymous_namespace{BuildingsParser.cpp}.insert_building(), anonymous_namespace{FieldsParser.cpp}.insert_fieldtype(), Universe.Objects(), DesignWnd::MainPanel.RefreshIncompleteDesign(), and ShipDesign.SetDescription().
file_match
bool tag_parser.file_match = False
help
tag_parser.help
link_str
def tag_parser.link_str = get_link(source[0], source[1])
metavar
tag_parser.metavar
nargs
tag_parser.nargs
output_buff
list tag_parser.output_buff = []
source_count
int tag_parser.source_count = 0
tag_close
tag_parser.tag_close = args.get('tag')[1]
tag_open
tag_parser.tag_open = args.get('tag')[0]