FreeOrion: anonymous_namespace{ResearchQueue.cpp} Namespace Reference
anonymous_namespace{ResearchQueue.cpp} Namespace Reference
Functions
void SetTechQueueElementSpending (float RPs, const std::map< std::string, float > &research_progress, const std::map< std::string, TechStatus > &research_status, ResearchQueue::QueueType &queue, float &total_RPs_spent, int &projects_in_progress, int empire_id)
sets the .allocated_rp, value for each Tech in the queue.
Variables
const float EPSILON = 0.01f
Function Documentation
void anonymous_namespace{ResearchQueue.cpp}::SetTechQueueElementSpending (float RPs, const std::map< std::string, float > & research_progress, const std::map< std::string, TechStatus > & research_status, ResearchQueue::QueueType & queue, float & total_RPs_spent, int & projects_in_progress, int empire_id)
sets the .allocated_rp, value for each Tech in the queue.
Only sets nonzero funding to a Tech if it is researchable this turn. Also determines total number of spent RP (returning by reference in total_RPs_spent)
References DebugLogger, ErrorLogger, AIInterface::GetTech(), Tech::PerTurnCost(), and Tech::ResearchCost().
Referenced by ResearchQueue::Update().
Variable Documentation
const float anonymous_namespace{ResearchQueue.cpp}::EPSILON = 0.01f
Referenced by ResearchQueue::Update().