FreeOrion: anonymous_namespace{ShipPart.cpp} Namespace Reference
anonymous_namespace{ShipPart.cpp} Namespace Reference
Functions
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, const std::string &part_name, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr, bool allow_stacking=true)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, const std::string &part_name, float fixed_increase, bool allow_stacking=true)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeterRuleScaled (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeterRuleScaled (MeterType meter_type, const std::string &part_name, float base_increase, const std::string &scaling_factor_rule_name, bool allow_stacking=true)
Variables
const float ARBITRARY_LARGE_COST = 999999.9f
const int ARBITRARY_LARGE_TURNS = 999999
Function Documentation
IncreaseMeter() [1/4]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> && increase_vr)
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, and ValueRef::PLUS.
IncreaseMeter() [2/4]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
References IncreaseMeter().
IncreaseMeter() [3/4]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, const std::string & part_name, std::unique_ptr< ValueRef::ValueRef< double >> && increase_vr, bool allow_stacking = true)
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, and ValueRef::PLUS.
IncreaseMeter() [4/4]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, const std::string & part_name, float fixed_increase, bool allow_stacking = true)
Referenced by IncreaseMeter(), and IncreaseMeterRuleScaled().
IncreaseMeterRuleScaled() [1/2]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled (MeterType meter_type, float base_increase, const std::string & scaling_factor_rule_name)
References IncreaseMeter(), and ValueRef::TIMES.
IncreaseMeterRuleScaled() [2/2]
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled (MeterType meter_type, const std::string & part_name, float base_increase, const std::string & scaling_factor_rule_name, bool allow_stacking = true)
References ARBITRARY_LARGE_COST, ARBITRARY_LARGE_TURNS, CheckSums::CheckSumCombine(), tag_parser::description, Empires(), FlexibleFormat(), ObjectMap::get(), GameRules::Get(), GetGameRules(), EmpireManager::GetSource(), IncreaseMeter(), Objects(), ShipPartManager::s_instance, ValueRef::TIMES, TraceLogger, and UserString().
Variable Documentation
ARBITRARY_LARGE_COST
const float anonymous_namespace{ShipPart.cpp}::ARBITRARY_LARGE_COST = 999999.9f
Referenced by IncreaseMeterRuleScaled().
ARBITRARY_LARGE_TURNS
const int anonymous_namespace{ShipPart.cpp}::ARBITRARY_LARGE_TURNS = 999999
Referenced by IncreaseMeterRuleScaled().