FreeOrion: anonymous_namespace{TechTreeWnd.cpp} Namespace Reference
anonymous_namespace{TechTreeWnd.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
constexpr double ConstExprPow (double base, int pow)
GG::Y TechPanelHeight ()
GG::X TechPanelWidth ()
bool TechVisible (const std::string &tech_name, const std::set< std::string > &categories_shown, const std::set< TechStatus > &statuses_shown)
Variables
constexpr double INITIAL_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -5)
constexpr double MAX_SCALE = ConstExprPow(ZOOM_STEP_SIZE, 10)
constexpr double MIN_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -25)
constexpr double PI = 3.1415926535897932384626433
const std::string RES_CONTROLS_WND_NAME = "research.control"
const std::string RES_PEDIA_WND_NAME = "research.pedia"
bool temp_bool = RegisterOptions(&AddOptions)
constexpr double ZOOM_STEP_SIZE = 1.12
Function Documentation
AddOptions()
void anonymous_namespace{TechTreeWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
ConstExprPow()
constexpr double anonymous_namespace{TechTreeWnd.cpp}::ConstExprPow (double base, int pow)
TechPanelHeight()
GG::Y anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight ()
References ClientUI::Pts().
Referenced by TechTreeWnd::LayoutPanel::TechPanel::InWindow(), TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), TechTreeWnd::LayoutPanel::TechPanel::Render(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
TechPanelWidth()
GG::X anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth ()
References ClientUI::Pts().
Referenced by TechTreeWnd::LayoutPanel::TechPanel::InWindow(), TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), and TechTreeWnd::LayoutPanel::TechPanel::Render().
TechVisible()
bool anonymous_namespace{TechTreeWnd.cpp}::TechVisible (const std::string & tech_name, const std::set< std::string > & categories_shown, const std::set< TechStatus > & statuses_shown)
References Tech::Category(), GGHumanClientApp::GetApp(), GetEmpire(), GetTech(), and Tech::Researchable().
Referenced by TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::TechIsVisible(), and TechTreeWnd::TechListBox::Update().
Variable Documentation
INITIAL_SCALE
constexpr double anonymous_namespace{TechTreeWnd.cpp}::INITIAL_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -5)
MAX_SCALE
constexpr double anonymous_namespace{TechTreeWnd.cpp}::MAX_SCALE = ConstExprPow(ZOOM_STEP_SIZE, 10)
Referenced by TechTreeWnd::LayoutPanel::SetScale().
MIN_SCALE
constexpr double anonymous_namespace{TechTreeWnd.cpp}::MIN_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -25)
Referenced by TechTreeWnd::LayoutPanel::SetScale().
PI
constexpr double anonymous_namespace{TechTreeWnd.cpp}::PI = 3.1415926535897932384626433
Referenced by TechTreeWnd::LayoutPanel::TechPanel::Render().
RES_CONTROLS_WND_NAME
const std::string anonymous_namespace{TechTreeWnd.cpp}::RES_CONTROLS_WND_NAME = "research.control"
Referenced by TechTreeWnd::CompleteConstruction().
RES_PEDIA_WND_NAME
const std::string anonymous_namespace{TechTreeWnd.cpp}::RES_PEDIA_WND_NAME = "research.pedia"
Referenced by TechTreeWnd::CompleteConstruction(), TechTreeWnd::HidePedia(), and TechTreeWnd::ShowPedia().
temp_bool
bool anonymous_namespace{TechTreeWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
ZOOM_STEP_SIZE
constexpr double anonymous_namespace{TechTreeWnd.cpp}::ZOOM_STEP_SIZE = 1.12
Referenced by TechTreeWnd::LayoutPanel::CompleteConstruction(), TechTreeWnd::LayoutPanel::SetScale(), and TechTreeWnd::LayoutPanel::TreeZoomedSlot().