FreeOrion: anonymous_namespace{FleetButton.cpp} Namespace Reference
anonymous_namespace{FleetButton.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
float FleetButtonScaling ()
const std::string & FleetIconSizePrefix (FleetButton::SizeType size_type)
int FleetSizeIconNumber (int number_ships)
Variables
bool temp_bool = RegisterOptions(&AddOptions)
constexpr float TWO_PI = 2.0*3.14159f
Function Documentation
AddOptions()
void anonymous_namespace{FleetButton.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
FleetButtonScaling()
float anonymous_namespace{FleetButton.cpp}::FleetButtonScaling ()
References OptionsDB::Get(), and GetOptionsDB().
Referenced by FleetButton::LayoutIcons(), and FleetButton::Refresh().
FleetIconSizePrefix()
const std::string& anonymous_namespace{FleetButton.cpp}::FleetIconSizePrefix (FleetButton::SizeType size_type)
References anonymous_namespace{Empire.cpp}::EMPTY_STRING, FleetButton::LARGE, FleetButton::MEDIUM, and FleetButton::SMALL.
Referenced by FleetBlockadedIcon(), FleetHeadIcons(), and FleetSizeIcon().
FleetSizeIconNumber()
int anonymous_namespace{FleetButton.cpp}::FleetSizeIconNumber (int number_ships)
Referenced by FleetSizeIcon().
Variable Documentation
temp_bool
bool anonymous_namespace{FleetButton.cpp}::temp_bool = RegisterOptions(&AddOptions)
TWO_PI
constexpr float anonymous_namespace{FleetButton.cpp}::TWO_PI = 2.0*3.14159f
Referenced by FleetButton::Refresh(), FleetButton::RenderPressed(), and FleetButton::RenderRollover().