FreeOrion: anonymous_namespace{LoggingWrapper.cpp} Namespace Reference
anonymous_namespace{LoggingWrapper.cpp} Namespace Reference
Functions
void ConfigurePythonFileSinkFrontEnd (LoggerTextFileSinkFrontend &sink_frontend, const std::string &channel_name)
void ConfigurePythonLogger (NamedThreadedLogger &logger, const std::string &name)
DeclareThreadSafePythonLogger (python)
void PythonLogger (const std::string &msg, const LogLevel log_level, const std::string &python_logger, const std::string &filename, const std::string &lineno)
void PythonLoggerDebug (const std::string &msg, const std::string &logger_name, const std::string &filename, const std::string &function_name, const std::string &lineno)
void PythonLoggerError (const std::string &msg, const std::string &logger_name, const std::string &filename, const std::string &function_name, const std::string &lineno)
void PythonLoggerInfo (const std::string &msg, const std::string &logger_name, const std::string &filename, const std::string &function_name, const std::string &lineno)
void PythonLoggerWarn (const std::string &msg, const std::string &logger_name, const std::string &filename, const std::string &function_name, const std::string &lineno)
void PythonLoggerWrapper (const LogLevel log_level, const std::string &msg, const std::string &logger_name, const std::string &filename, const std::string &lineno)
void send_to_log (std::stringstream &ss, const std::string &input, const std::function< void(const std::string &)> &logger)
Variables
static const std::size_t MAX_SINGLE_CHUNK_TEXT_SIZE = 4096
Function Documentation
void anonymous_namespace{LoggingWrapper.cpp}::ConfigurePythonFileSinkFrontEnd (LoggerTextFileSinkFrontend & sink_frontend, const std::string & channel_name)
Referenced by ConfigurePythonLogger().
void anonymous_namespace{LoggingWrapper.cpp}::ConfigurePythonLogger (NamedThreadedLogger & logger, const std::string & name)
References ApplyConfigurationToFileSinkFrontEnd(), ConfigurePythonFileSinkFrontEnd(), default_log_level_threshold, LoggerCreatedSignal, and SetLoggerThreshold().
anonymous_namespace{LoggingWrapper.cpp}::DeclareThreadSafePythonLogger (python)
void anonymous_namespace{LoggingWrapper.cpp}::PythonLogger (const std::string & msg, const LogLevel log_level, const std::string & python_logger, const std::string & filename, const std::string & lineno)
References debug, DebugLogger, error, ErrorLogger, info, InfoLogger, trace, TraceLogger, warn, and WarnLogger.
Referenced by PythonLoggerWrapper().
void anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerDebug (const std::string & msg, const std::string & logger_name, const std::string & filename, const std::string & function_name, const std::string & lineno)
References debug, and PythonLoggerWrapper().
Referenced by FreeOrionPython::WrapLogger().
void anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerError (const std::string & msg, const std::string & logger_name, const std::string & filename, const std::string & function_name, const std::string & lineno)
References error, and PythonLoggerWrapper().
Referenced by FreeOrionPython::WrapLogger().
void anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerInfo (const std::string & msg, const std::string & logger_name, const std::string & filename, const std::string & function_name, const std::string & lineno)
References info, and PythonLoggerWrapper().
Referenced by FreeOrionPython::WrapLogger().
void anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerWarn (const std::string & msg, const std::string & logger_name, const std::string & filename, const std::string & function_name, const std::string & lineno)
References PythonLoggerWrapper(), and warn.
Referenced by FreeOrionPython::WrapLogger().
void anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerWrapper (const LogLevel log_level, const std::string & msg, const std::string & logger_name, const std::string & filename, const std::string & lineno)
References PythonLogger(), and send_to_log().
Referenced by PythonLoggerDebug(), PythonLoggerError(), PythonLoggerInfo(), and PythonLoggerWarn().
void anonymous_namespace{LoggingWrapper.cpp}::send_to_log (std::stringstream & ss, const std::string & input, const std::function< void(const std::string &)> & logger)
Python streams text as strings which need to be concatenated before they are output to the logger. Each input may end with an incomplete line that is continued in the next input from the python executable. ss should be a persistent stringstream per output sink to persist the incomplete line of text. is a logger associated with the sink that ss represents.
References ErrorLogger, and MAX_SINGLE_CHUNK_TEXT_SIZE.
Referenced by PythonLoggerWrapper().
Variable Documentation
const std::size_t anonymous_namespace{LoggingWrapper.cpp}::MAX_SINGLE_CHUNK_TEXT_SIZE = 4096 static
Referenced by send_to_log().