FreeOrion: anonymous_namespace{Logger.cpp} Namespace Reference
anonymous_namespace{Logger.cpp} Namespace Reference
Classes
class LoggersToSinkFrontEnds
LoggersToSinkFrontEnds is used to track all of the global named loggers.
class LoggerThresholdSetter
LoggerThresholdSetter sets the threshold of a logger.
Typedefs
using LoggerFileSinkFrontEndConfigurer = std::function< void(LoggerTextFileSinkFrontend &sink_frontend)>
using LoggerTextFileSinkFrontend = boost::log::sinks::synchronous_sink< boost::log::sinks::text_file_backend >
Functions
BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log), NamedThreadedLogger)
void ConfigureFileSinkFrontEnd (LoggerTextFileSinkFrontend &sink_frontend, const std::string &channel_name)
void ConfigureToFileSinkFrontEndCore (const boost::shared_ptr< LoggerTextFileSinkFrontend::sink_backend_type > &file_sink_backend, const std::string &channel_name, const LoggerFileSinkFrontEndConfigurer &configure_front_end)
Create a new file sink front end for file_sink_backend for channel_name and configure it with configure_front_end.
const std::string & DisplayName (const std::string &channel_name)
boost::shared_ptr< LoggerTextFileSinkFrontend::sink_backend_type > & FileSinkBackend ()
boost::optional< LogLevel > & ForcedThreshold ()
LoggersToSinkFrontEnds & GetLoggersToSinkFrontEnds ()
bool InitializeLoggerCreatedSignal ()
std::stringstream InvalidLogLevelWarning (const std::string &text)
std::string & LocalUnnamedLoggerIdentifier ()
std::pair< std::string, LogLevel > SetLoggerThresholdCore (const std::string &source, LogLevel threshold)
Variables
constexpr const char *const log_level_names [] = {"trace", "debug", "info", "warn", "error"}
Typedef Documentation
LoggerFileSinkFrontEndConfigurer
using anonymous_namespace{Logger.cpp}::LoggerFileSinkFrontEndConfigurer = typedef std::function<void(LoggerTextFileSinkFrontend& sink_frontend)>
LoggerTextFileSinkFrontend
using anonymous_namespace{Logger.cpp}::LoggerTextFileSinkFrontend = typedef boost::log::sinks::synchronous_sink<boost::log::sinks::text_file_backend>
Function Documentation
BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT()
anonymous_namespace{Logger.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log) , NamedThreadedLogger)
References debug.
ConfigureFileSinkFrontEnd()
void anonymous_namespace{Logger.cpp}::ConfigureFileSinkFrontEnd (LoggerTextFileSinkFrontend & sink_frontend, const std::string & channel_name)
References DisplayName().
Referenced by ConfigureLogger(), and InitLoggingSystem().
ConfigureToFileSinkFrontEndCore()
void anonymous_namespace{Logger.cpp}::ConfigureToFileSinkFrontEndCore (const boost::shared_ptr< LoggerTextFileSinkFrontend::sink_backend_type > & file_sink_backend, const std::string & channel_name, const LoggerFileSinkFrontEndConfigurer & configure_front_end)
Create a new file sink front end for file_sink_backend for channel_name and configure it with configure_front_end.
References anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::AddOrReplaceLoggerName(), and GetLoggersToSinkFrontEnds().
Referenced by ApplyConfigurationToFileSinkFrontEnd(), anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::ConfigureFrontEnds(), and FileSinkBackend().
DisplayName()
const std::string& anonymous_namespace{Logger.cpp}::DisplayName (const std::string & channel_name)
References LocalUnnamedLoggerIdentifier().
Referenced by anonymous_namespace{Logger.cpp}::LoggersToSinkFrontEnds::AddOrReplaceLoggerName(), ConfigureFileSinkFrontEnd(), and anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::SetThreshold().
FileSinkBackend()
boost::shared_ptr<LoggerTextFileSinkFrontend::sink_backend_type>& anonymous_namespace{Logger.cpp}::FileSinkBackend ()
References ConfigureToFileSinkFrontEndCore().
Referenced by ApplyConfigurationToFileSinkFrontEnd(), and InitLoggingSystem().
ForcedThreshold()
boost::optional<LogLevel>& anonymous_namespace{Logger.cpp}::ForcedThreshold ()
Referenced by OverrideAllLoggersThresholds(), and anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::SetThreshold().
GetLoggersToSinkFrontEnds()
LoggersToSinkFrontEnds& anonymous_namespace{Logger.cpp}::GetLoggersToSinkFrontEnds ()
Referenced by ApplyConfigurationToFileSinkFrontEnd(), ConfigureToFileSinkFrontEndCore(), CreatedLoggersNames(), InitLoggingSystem(), OverrideAllLoggersThresholds(), and ShutdownLoggingSystemFileSink().
InitializeLoggerCreatedSignal()
bool anonymous_namespace{Logger.cpp}::InitializeLoggerCreatedSignal ()
Referenced by ConfigureLogger().
InvalidLogLevelWarning()
std::stringstream anonymous_namespace{Logger.cpp}::InvalidLogLevelWarning (const std::string & text)
References max, min, and to_string().
Referenced by to_LogLevel().
LocalUnnamedLoggerIdentifier()
std::string& anonymous_namespace{Logger.cpp}::LocalUnnamedLoggerIdentifier ()
Referenced by DefaultExecLoggerName(), DisplayName(), and InitLoggingSystem().
SetLoggerThresholdCore()
std::pair<std::string, LogLevel> anonymous_namespace{Logger.cpp}::SetLoggerThresholdCore (const std::string & source, LogLevel threshold)
References anonymous_namespace{Logger.cpp}::LoggerThresholdSetter::SetThreshold().
Referenced by ConfigureLogger(), InitLoggingSystem(), OverrideAllLoggersThresholds(), and SetLoggerThreshold().
Variable Documentation
log_level_names
constexpr const char* const anonymous_namespace{Logger.cpp}::log_level_names[] = {"trace", "debug", "info", "warn", "error"}
Referenced by to_string().