FreeOrion: anonymous_namespace{CUIWnd.cpp} Namespace Reference
anonymous_namespace{CUIWnd.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
void PlayCloseSound ()
void PlayMaximizeSound ()
void PlayMinimizeSound ()
bool RegisterWndFlags ()
std::string WindowNameFromOption (const std::string &option_name)
Variables
const double BUTTON_DIMMING_SCALE_FACTOR = 0.75
bool dummy = RegisterWndFlags()
const GG::X::value_type INVALID_POS = std::numeric_limits<GG::X::value_type>::min()
const GG::X INVALID_X = GG::X(INVALID_POS)
const GG::Y INVALID_Y = GG::Y(INVALID_POS)
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
void anonymous_namespace{CUIWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::AddFlag(), and UserStringNop.
void anonymous_namespace{CUIWnd.cpp}::PlayCloseSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUI_PinButton::CUI_PinButton(), and CUIWnd::InitButtons().
void anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUI_MinRestoreButton::Toggle().
void anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound ()
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
Referenced by CUI_MinRestoreButton::Toggle().
bool anonymous_namespace{CUIWnd.cpp}::RegisterWndFlags ()
References CLOSABLE(), MINIMIZABLE(), and PINABLE().
std::string anonymous_namespace{CUIWnd.cpp}::WindowNameFromOption (const std::string & option_name)
References CUIWnd::BORDER_BOTTOM, CUIWnd::BORDER_LEFT, CUIWnd::BORDER_RIGHT, CUIWnd::BUTTON_TOP_OFFSET, ErrorLogger, CUIWnd::INNER_BORDER_ANGLE_OFFSET, CUIWnd::MINIMIZED_WND_WIDTH, CUIWnd::OUTER_EDGE_ANGLE_OFFSET, CUIWnd::RESIZE_HASHMARK1_OFFSET, CUIWnd::RESIZE_HASHMARK2_OFFSET, and CUIWnd::TITLE_OFFSET.
Referenced by CUIWnd::InvalidateUnusedOptions().
Variable Documentation
const double anonymous_namespace{CUIWnd.cpp}::BUTTON_DIMMING_SCALE_FACTOR = 0.75
Referenced by CUI_MinRestoreButton::Render().
bool anonymous_namespace{CUIWnd.cpp}::dummy = RegisterWndFlags()
Referenced by ServerApp::AddPlayerIntoGame(), MapWnd::MapScaleLine::CompleteConstruction(), ConfigureLogger(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Empire::meter_end(), ResourcePool::serialize(), and Planet::serialize().
const GG::X::value_type anonymous_namespace{CUIWnd.cpp}::INVALID_POS = std::numeric_limits<GG::X::value_type>::min()
Referenced by CUIWnd::AddWindowOptions(), and CUIWnd::InvalidateWindowOptions().
const GG::X anonymous_namespace{CUIWnd.cpp}::INVALID_X = GG::X(INVALID_POS)
Referenced by CUIWnd::CalculatePosition(), CUIWnd::InitSizeMove(), CUIWnd::LoadOptions(), and CUIWnd::ResetDefaultPosition().
const GG::Y anonymous_namespace{CUIWnd.cpp}::INVALID_Y = GG::Y(INVALID_POS)
Referenced by CUIWnd::CalculatePosition(), and CUIWnd::LoadOptions().
bool anonymous_namespace{CUIWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)