FreeOrion: anonymous_namespace{Planet.cpp} Namespace Reference
anonymous_namespace{Planet.cpp} Namespace Reference
Functions
PlanetType LoopPlanetTypeIncrement (PlanetType initial_type, int step)
PlanetSize PlanetSizeIncrement (PlanetSize initial_size, int step)
PlanetType RingNextPlanetType (PlanetType current_type)
PlanetType RingPreviousPlanetType (PlanetType current_type)
float SizeRotationFactor (PlanetSize size)
Variables
static const std::string EMPTY_STRING
const float HIGH_TILT_THERESHOLD = 45.0f
const std::string TAG_STAT_SKIP_DEPOP = "CTRL_STAT_SKIP_DEPOP"
Function Documentation
LoopPlanetTypeIncrement()
PlanetType anonymous_namespace{Planet.cpp}::LoopPlanetTypeIncrement (PlanetType initial_type, int step)
References DebugLogger.
PlanetSizeIncrement()
PlanetSize anonymous_namespace{Planet.cpp}::PlanetSizeIncrement (PlanetSize initial_size, int step)
References ALL_EMPIRES, CreatePlanetDepopulatedSitRep(), CurrentTurn(), DebugLogger, Meter::DEFAULT_VALUE, Species::DefaultFocus(), PopCenter::Depopulate(), Universe::Destroy(), EMPTY_STRING, ErrorLogger, ObjectMap::get(), GetBuildingType(), GetEmpire(), GetSpecies(), GetUniverse(), HIGH_TILT_THERESHOLD, INVALID_OBJECT_ID, INVALID_PLANET_SIZE, anonymous_namespace{XMLDoc.cpp}::Name, Objects(), RandZeroToOne(), PopCenter::Reset(), ResourceCenter::Reset(), RomanNumber(), PopCenter::SetSpecies(), parse::species(), TAG_STAT_SKIP_DEPOP, UserString(), UniverseObjectVisitor::Visit(), and WarnLogger.
RingNextPlanetType()
PlanetType anonymous_namespace{Planet.cpp}::RingNextPlanetType (PlanetType current_type)
Referenced by RingPreviousPlanetType().
RingPreviousPlanetType()
PlanetType anonymous_namespace{Planet.cpp}::RingPreviousPlanetType (PlanetType current_type)
References RingNextPlanetType().
SizeRotationFactor()
float anonymous_namespace{Planet.cpp}::SizeRotationFactor (PlanetSize size)
Variable Documentation
EMPTY_STRING
const std::string anonymous_namespace{Planet.cpp}::EMPTY_STRING static
Referenced by PlanetSizeIncrement().
HIGH_TILT_THERESHOLD
const float anonymous_namespace{Planet.cpp}::HIGH_TILT_THERESHOLD = 45.0f
Referenced by PlanetSizeIncrement().
TAG_STAT_SKIP_DEPOP
const std::string anonymous_namespace{Planet.cpp}::TAG_STAT_SKIP_DEPOP = "CTRL_STAT_SKIP_DEPOP"
CTRL_STAT_SKIP_DEPOP Do not count PopCenters with this tag for SpeciesPlanetsDepoped stat
Referenced by PlanetSizeIncrement().