FreeOrion: anonymous_namespace{CombatEvents.cpp} Namespace Reference
anonymous_namespace{CombatEvents.cpp} Namespace Reference
Functions
void AddRules (GameRules &rules)
std::string EmpireColorWrappedText (int empire_id, const std::string &text)
std::string EmpireLink (int empire_id)
const std::string EMPTY_STRING ("")
std::string FighterOrPublicNameLink (int viewing_empire_id, int object_id, int object_empire_id, const ObjectMap &objects)
Creates a link tag of the appropriate type for either a fighter or another object.
const std::string & LinkTag (UniverseObjectType obj_type)
std::string PublicNameLink (int empire_id, int object_id, const ObjectMap &objects)
Creates a link tag of the appropriate type for object_id, with the content being the public name from the point of view of empire_id.
std::string ShipPartLink (const std::string &part)
std::string WrapColorTag (std::string const &text, const EmpireColor &c)
std::string WrapUserStringWithTag (const std::string &table_id, const std::string &tag)
std::string WrapWithTagAndId (const std::string &meat, const std::string &tag, int id)
Variables
bool temp_bool = RegisterGameRules(&AddRules)
Function Documentation
AddRules()
void anonymous_namespace{CombatEvents.cpp}::AddRules (GameRules & rules)
References GameRules::Add(), and UserStringNop.
EmpireColorWrappedText()
std::string anonymous_namespace{CombatEvents.cpp}::EmpireColorWrappedText (int empire_id, const std::string & text)
References GetEmpire(), and WrapColorTag().
Referenced by FighterLaunchEvent::CombatLogDescription(), EmpireLink(), and FighterOrPublicNameLink().
EmpireLink()
std::string anonymous_namespace{CombatEvents.cpp}::EmpireLink (int empire_id)
References VarText::EMPIRE_ID_TAG, EmpireColorWrappedText(), GetEmpire(), UserString(), and WrapWithTagAndId().
Referenced by InitialStealthEvent::CombatLogDescription(), StealthChangeEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), InitialStealthEvent::DebugString(), and StealthChangeEvent::DebugString().
EMPTY_STRING()
const std::string anonymous_namespace{CombatEvents.cpp}::EMPTY_STRING ("")
Referenced by LinkTag().
FighterOrPublicNameLink()
std::string anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink (int viewing_empire_id, int object_id, int object_empire_id, const ObjectMap & objects)
Creates a link tag of the appropriate type for either a fighter or another object.
References EmpireColorWrappedText(), PublicNameLink(), and UserString().
Referenced by InitialStealthEvent::CombatLogDescription(), StealthChangeEvent::CombatLogDescription(), StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription(), WeaponFireEvent::CombatLogDescription(), IncapacitationEvent::CombatLogDescription(), FightersAttackFightersEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), WeaponsPlatformEvent::CombatLogDescription(), InitialStealthEvent::DebugString(), and StealthChangeEvent::StealthChangeEventDetail::DebugString().
LinkTag()
const std::string& anonymous_namespace{CombatEvents.cpp}::LinkTag (UniverseObjectType obj_type)
References VarText::BUILDING_ID_TAG, EMPTY_STRING(), VarText::FLEET_ID_TAG, VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, and VarText::SYSTEM_ID_TAG.
Referenced by PublicNameLink().
PublicNameLink()
std::string anonymous_namespace{CombatEvents.cpp}::PublicNameLink (int empire_id, int object_id, const ObjectMap & objects)
Creates a link tag of the appropriate type for object_id, with the content being the public name from the point of view of empire_id.
Returns UserString("ENC_COMBAT_UNKNOWN_OBJECT") if object_id is not found.
References ObjectMap::get(), LinkTag(), UserString(), and WrapWithTagAndId().
Referenced by IncapacitationEvent::CombatLogDescription(), FighterLaunchEvent::CombatLogDescription(), and FighterOrPublicNameLink().
ShipPartLink()
std::string anonymous_namespace{CombatEvents.cpp}::ShipPartLink (const std::string & part)
References VarText::SHIP_PART_TAG, UserString(), and WrapUserStringWithTag().
Referenced by WeaponFireEvent::CombatLogDetails().
WrapColorTag()
std::string anonymous_namespace{CombatEvents.cpp}::WrapColorTag (std::string const & text, const EmpireColor & c)
Referenced by EmpireColorWrappedText().
WrapUserStringWithTag()
std::string anonymous_namespace{CombatEvents.cpp}::WrapUserStringWithTag (const std::string & table_id, const std::string & tag)
References UserString().
Referenced by ShipPartLink().
WrapWithTagAndId()
std::string anonymous_namespace{CombatEvents.cpp}::WrapWithTagAndId (const std::string & meat, const std::string & tag, int id)
References to_string().
Referenced by EmpireLink(), and PublicNameLink().
Variable Documentation
temp_bool
bool anonymous_namespace{CombatEvents.cpp}::temp_bool = RegisterGameRules(&AddRules)