FreeOrion: anonymous_namespace{SaveGamePreviewUtils.cpp} Namespace Reference
anonymous_namespace{SaveGamePreviewUtils.cpp} Namespace Reference
Functions
const std::string BIN_SAVE_FILE_DESCRIPTION ("This is binary archive FreeOrion saved game.")
bool LoadSaveGamePreviewData (const fs::path &path, FullPreview &full)
Populates a SaveGamePreviewData from a given file returns true on success, false if preview data could not be found.
std::string split_time (const std::string &time)
Splits time and date on separate lines for an ISO datetime string.
const std::string UNABLE_TO_OPEN_FILE ("Unable to open file")
const std::string XML_COMPRESSED_MARKER ("zlib-xml")
const std::string XML_SAVE_FILE_DESCRIPTION ("This is an XML archive FreeOrion saved game. Initial header information is uncompressed. The main gamestate information follows, possibly stored as zlib-comprssed XML archive in the last entry in the main archive.")
Function Documentation
BIN_SAVE_FILE_DESCRIPTION()
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::BIN_SAVE_FILE_DESCRIPTION ("This is binary archive FreeOrion saved game.")
Referenced by SaveGamePreviewData::SetBinary().
LoadSaveGamePreviewData()
bool anonymous_namespace{SaveGamePreviewUtils.cpp}::LoadSaveGamePreviewData (const fs::path & path, FullPreview & full)
Populates a SaveGamePreviewData from a given file returns true on success, false if preview data could not be found.
References DebugLogger, ErrorLogger, FullPreview::filename, FullPreview::galaxy, SaveGamePreviewData::number_of_human_players, PathToString(), FullPreview::preview, SaveGamePreviewData::save_format_marker, and SaveGamePreviewData::Valid().
Referenced by LoadSaveGamePreviews().
split_time()
std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::split_time (const std::string & time)
Splits time and date on separate lines for an ISO datetime string.
Referenced by ColumnInPreview().
UNABLE_TO_OPEN_FILE()
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::UNABLE_TO_OPEN_FILE ("Unable to open file")
XML_COMPRESSED_MARKER()
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_COMPRESSED_MARKER ("zlib-xml")
Referenced by SaveFileWithValidHeader().
XML_SAVE_FILE_DESCRIPTION()
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_SAVE_FILE_DESCRIPTION ("This is an XML archive FreeOrion saved game. Initial header information is uncompressed. The main gamestate information follows, possibly stored as zlib-comprssed XML archive in the last entry in the main archive.")
Referenced by SaveGamePreviewData::SetBinary().