FreeOrion: anonymous_namespace{MultiIconValueIndicator.cpp} Namespace Reference
anonymous_namespace{MultiIconValueIndicator.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
GG::Y IconHeight ()
int IconSpacing ()
GG::X IconWidth ()
Function Documentation
EDGE_PAD()
const int anonymous_namespace{MultiIconValueIndicator.cpp}::EDGE_PAD (3)
Referenced by MultiIconValueIndicator::CompleteConstruction().
IconHeight()
GG::Y anonymous_namespace{MultiIconValueIndicator.cpp}::IconHeight ()
References IconSpacing().
Referenced by MultiIconValueIndicator::CompleteConstruction().
IconSpacing()
int anonymous_namespace{MultiIconValueIndicator.cpp}::IconSpacing ()
References ClientUI::Pts().
Referenced by MultiIconValueIndicator::CompleteConstruction(), IconHeight(), and IconWidth().
IconWidth()
GG::X anonymous_namespace{MultiIconValueIndicator.cpp}::IconWidth ()
References IconSpacing().
Referenced by MultiIconValueIndicator::CompleteConstruction().