FreeOrion: anonymous_namespace{AIClientApp.cpp} Namespace Reference
anonymous_namespace{AIClientApp.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
template<typename T >
void AddTraitBypassOption (OptionsDB &db, std::string const &root, std::string ROOT, T def, ValidatorBase const &validator)
AddTraitBypassOption creates a set of options for debugging of the form: ai.trait.
Variables
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{AIClientApp.cpp}::AddOptions (OptionsDB & db)
References IApp::MAX_AI_PLAYERS().
AddTraitBypassOption()
template<typename T > void anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption (OptionsDB & db, std::string const & root, std::string ROOT, T def, ValidatorBase const & validator)
AddTraitBypassOption creates a set of options for debugging of the form: ai.trait.
<trait name>.force.enabled – If true use the following options to bypass the trait ai.trait.<trait name>.default – If present use this value for all of the AIs not individually set ai.trait.<trait name>.ai_1 – Use for AI_1 ... ai.trait.<trait name>.ai_40 – Use for AI_40
References OptionsDB::Add(), IApp::MAX_AI_PLAYERS(), to_string(), and UserStringNop.
Variable Documentation
temp_bool
bool anonymous_namespace{AIClientApp.cpp}::temp_bool = RegisterOptions(&AddOptions)