FreeOrion: anonymous_namespace{CUIDrawUtil.cpp} Namespace Reference
anonymous_namespace{CUIDrawUtil.cpp} Namespace Reference
Functions
void FindIsoscelesTriangleVertices (const GG::Pt &ul, const GG::Pt &lr, ShapeOrientation orientation, double &x1_, double &y1_, double &x2_, double &y2_, double &x3_, double &y3_)
Variables
const double TWO_PI = 2.0 * 3.14159
Function Documentation
FindIsoscelesTriangleVertices()
void anonymous_namespace{CUIDrawUtil.cpp}::FindIsoscelesTriangleVertices (const GG::Pt & ul, const GG::Pt & lr, ShapeOrientation orientation, double & x1_, double & y1_, double & x2_, double & y2_, double & x3_, double & y3_)
References DOWN, ErrorLogger, LEFT, RIGHT, and UP.
Referenced by BufferStoreIsoscelesTriangle(), InIsoscelesTriangle(), and IsoscelesTriangle().
Variable Documentation
TWO_PI
const double anonymous_namespace{CUIDrawUtil.cpp}::TWO_PI = 2.0 * 3.14159
Referenced by ScanlineRenderer::Impl::RenderCircle().