FreeOrion: anonymous_namespace{PopulationPanel.cpp} Namespace Reference
anonymous_namespace{PopulationPanel.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Function Documentation
const int anonymous_namespace{PopulationPanel.cpp}::EDGE_PAD (3)
Referenced by PopulationPanel::CompleteConstruction(), and PopulationPanel::DoLayout().
GG::Pt anonymous_namespace{PopulationPanel.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by PopulationPanel::CompleteConstruction(), and PopulationPanel::DoLayout().