FreeOrion: anonymous_namespace{ValueRef.cpp} Namespace Reference
anonymous_namespace{ValueRef.cpp} Namespace Reference
Classes
struct ObjectTypeVisitor
Functions
std::shared_ptr< const UniverseObject > FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
const std::map< std::string, MeterType > & GetMeterNameMap ()
std::string TraceReference (const std::vector< std::string > &property_name, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
Variables
std::map< std::string, MeterType > dummy = GetMeterNameMap()
Function Documentation
FollowReference()
std::shared_ptr<const UniverseObject> anonymous_namespace{ValueRef.cpp}::FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext & context)
References ScriptingContext::condition_local_candidate, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ScriptingContext::condition_root_candidate, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, ScriptingContext::effect_target, ValueRef::EFFECT_TARGET_REFERENCE, ErrorLogger, GetFleet(), GetPlanet(), GetSystem(), ValueRef::NON_OBJECT_REFERENCE, ScriptingContext::source, and ValueRef::SOURCE_REFERENCE.
Referenced by ValueRef::Variable< ToType >::Eval().
GetMeterNameMap()
const std::map<std::string, MeterType>& anonymous_namespace{ValueRef.cpp}::GetMeterNameMap ()
References METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STEALTH, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by ValueRef::MeterToName(), and ValueRef::NameToMeter().
TraceReference()
std::string anonymous_namespace{ValueRef.cpp}::TraceReference (const std::vector< std::string > & property_name, ValueRef::ReferenceType ref_type, const ScriptingContext & context)
References ScriptingContext::condition_local_candidate, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ScriptingContext::condition_root_candidate, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, ScriptingContext::effect_target, ValueRef::EFFECT_TARGET_REFERENCE, GetFleet(), GetPlanet(), GetSystem(), ValueRef::NON_OBJECT_REFERENCE, ValueRef::ReconstructName(), ScriptingContext::source, ValueRef::SOURCE_REFERENCE, to_string(), and UserString().
Referenced by ValueRef::Variable< ToType >::Eval().
Variable Documentation
dummy
std::map<std::string, MeterType> anonymous_namespace{ValueRef.cpp}::dummy = GetMeterNameMap()