FreeOrion: anonymous_namespace{TextBrowseWnd.cpp} Namespace Reference
anonymous_namespace{TextBrowseWnd.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
const GG::Y ICON_BROWSE_ICON_HEIGHT (64)
int IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
Function Documentation
const int anonymous_namespace{TextBrowseWnd.cpp}::EDGE_PAD (3)
Referenced by IconTextBrowseWndRowHeight(), and TextBrowseWnd::TextBrowseWnd().
const GG::Y anonymous_namespace{TextBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT (64)
Referenced by IconTextBrowseWndRowHeight(), and TextBrowseWnd::TextBrowseWnd().
int anonymous_namespace{TextBrowseWnd.cpp}::IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
References EDGE_PAD(), ICON_BROWSE_ICON_HEIGHT(), and ClientUI::Pts().
Referenced by TextBrowseWnd::CompleteConstruction(), TextBrowseWnd::Render(), and TextBrowseWnd::TextBrowseWnd().