FreeOrion: anonymous_namespace{ProductionWnd.cpp} Namespace Reference
anonymous_namespace{ProductionWnd.cpp} Namespace Reference
Classes
class ProdQueueListBox
class QuantitySelector
class QuantLabel
class QuantRow
class QueueProductionItemPanel
struct QueueRow
Functions
void AddOptions (OptionsDB &db)
std::shared_ptr< GG::BrowseInfoWnd > ProductionItemBrowseWnd (const ProductionQueue::Element &elem)
Variables
const int MARGIN = 2
const float OUTER_LINE_THICKNESS = 2.0f
bool temp_bool = RegisterOptions(&AddOptions)
const GG::X X_MARGIN = GG::X(MARGIN)
const GG::Y Y_MARGIN = GG::Y(MARGIN)
Function Documentation
AddOptions()
void anonymous_namespace{ProductionWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), OptionsDB::OptionExists(), and UserStringNop.
ProductionItemBrowseWnd()
std::shared_ptr<GG::BrowseInfoWnd> anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd (const ProductionQueue::Element & elem)
References ProductionQueue::Element::allocated_pp, ProductionQueue::Element::allowed_imperial_stockpile_use, ProductionQueue::Element::blocksize, BT_BUILDING, BT_SHIP, BT_STOCKPILE, ProductionQueue::ProductionItem::build_type, ClientUI::BuildingIcon(), ProductionQueue::ProductionItem::design_id, DoubleToString(), ProductionQueue::Element::empire_id, FlexibleFormat(), GetBuildingType(), GetShipDesign(), GetUniverseObject(), ProductionQueue::Element::item, ProductionQueue::Element::location, METER_STOCKPILE, ClientUI::MeterIcon(), ProductionQueue::ProductionItem::name, ShipDesign::Name(), BuildingType::PerTurnCost(), ShipDesign::PerTurnCost(), BuildingType::ProductionCost(), ShipDesign::ProductionCost(), BuildingType::ProductionLocation(), ShipDesign::ProductionLocation(), ProductionQueue::Element::progress, ProductionQueue::Element::rally_point_id, ClientUI::ShipDesignIcon(), to_string(), ProductionQueue::Element::turns_left_to_completion, and UserString().
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow().
Variable Documentation
MARGIN
const int anonymous_namespace{ProductionWnd.cpp}::MARGIN = 2
Referenced by anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::DoLayout(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), CUICheckBoxRepresenter::Render(), and CUIRadioRepresenter::Render().
OUTER_LINE_THICKNESS
const float anonymous_namespace{ProductionWnd.cpp}::OUTER_LINE_THICKNESS = 2.0f
temp_bool
bool anonymous_namespace{ProductionWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
X_MARGIN
const GG::X anonymous_namespace{ProductionWnd.cpp}::X_MARGIN = GG::X(MARGIN)
Referenced by TechTreeWnd::LayoutPanel::Layout().
Y_MARGIN
const GG::Y anonymous_namespace{ProductionWnd.cpp}::Y_MARGIN = GG::Y(MARGIN)