FreeOrion: ValueRef::anonymous_namespace{ValueRefs.cpp} Namespace Reference
ValueRef::anonymous_namespace{ValueRefs.cpp} Namespace Reference
Functions
const std::map< int, float > & GetEmpireIntFloatMap (int empire_id, const std::string &parsed_map_name)
const std::map< int, int > & GetEmpireIntIntMap (int empire_id, const std::string &parsed_map_name)
const std::map< std::string, int > & GetEmpireStringIntMap (int empire_id, const std::string &parsed_map_name)
float GetFloatEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, int map_key)
float GetFloatEmpirePropertySumAllIntKeys (int empire_id, const std::string &parsed_property_name)
int GetIntEmpirePropertyNoKey (int empire_id, const std::string &parsed_property_name)
int GetIntEmpirePropertyNoKeyImpl (int empire_id, const std::string &parsed_property_name)
int GetIntEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, const std::string &map_key)
int GetIntEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, int map_key)
int GetIntEmpirePropertySumAllIntKeys (int empire_id, const std::string &parsed_property_name)
int GetIntEmpirePropertySumAllStringKeys (int empire_id, const std::string &parsed_property_name)
int GetIntKeyFromContentStringKey (const std::string &parsed_property_name, const std::string &key_string)
std::vector< std::string > TechsResearchableByEmpire (int empire_id)
std::vector< std::string > TechsResearchedByEmpire (int empire_id)
std::vector< std::string > TransferrableTechs (int sender_empire_id, int receipient_empire_id)
Variables
static std::map< int, float > EMPTY_INT_FLOAT_MAP
static std::map< int, int > EMPTY_INT_INT_MAP
static std::map< std::string, int > EMPTY_STRING_INT_MAP
Function Documentation
GetEmpireIntFloatMap()
const std::map<int, float>& ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntFloatMap (int empire_id, const std::string & parsed_map_name)
References EMPTY_INT_FLOAT_MAP, GetEmpire(), GetSupplyManager(), SupplyManager::PropagatedSupplyDistances(), SupplyManager::PropagatedSupplyRanges(), and Empire::SystemSupplyRanges().
Referenced by GetFloatEmpirePropertySingleKey(), and GetFloatEmpirePropertySumAllIntKeys().
GetEmpireIntIntMap()
const std::map<int, int>& ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireIntIntMap (int empire_id, const std::string & parsed_map_name)
References Empire::EmpireShipsDestroyed(), EMPTY_INT_INT_MAP, GetEmpire(), Empire::ShipDesignsDestroyed(), Empire::ShipDesignsInProduction(), Empire::ShipDesignsLost(), Empire::ShipDesignsOwned(), Empire::ShipDesignsProduced(), and Empire::ShipDesignsScrapped().
Referenced by GetIntEmpirePropertySingleKey(), and GetIntEmpirePropertySumAllIntKeys().
GetEmpireStringIntMap()
const std::map<std::string, int>& ValueRef::anonymous_namespace{ValueRefs.cpp}::GetEmpireStringIntMap (int empire_id, const std::string & parsed_map_name)
References Empire::BuildingTypesOwned(), Empire::BuildingTypesProduced(), Empire::BuildingTypesScrapped(), EMPTY_STRING_INT_MAP, GetEmpire(), Empire::ResearchedTechs(), Empire::ShipPartTypesOwned(), Empire::SpeciesColoniesOwned(), Empire::SpeciesPlanetsBombed(), Empire::SpeciesPlanetsDepoped(), Empire::SpeciesPlanetsInvaded(), Empire::SpeciesShipsDestroyed(), Empire::SpeciesShipsLost(), Empire::SpeciesShipsOwned(), Empire::SpeciesShipsProduced(), and Empire::SpeciesShipsScrapped().
Referenced by GetIntEmpirePropertySingleKey(), and GetIntEmpirePropertySumAllStringKeys().
GetFloatEmpirePropertySingleKey()
float ValueRef::anonymous_namespace{ValueRefs.cpp}::GetFloatEmpirePropertySingleKey (int empire_id, const std::string & parsed_property_name, int map_key)
References ALL_EMPIRES, Empires(), and GetEmpireIntFloatMap().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetFloatEmpirePropertySumAllIntKeys()
float ValueRef::anonymous_namespace{ValueRefs.cpp}::GetFloatEmpirePropertySumAllIntKeys (int empire_id, const std::string & parsed_property_name)
References ALL_EMPIRES, Empires(), and GetEmpireIntFloatMap().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetIntEmpirePropertyNoKey()
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertyNoKey (int empire_id, const std::string & parsed_property_name)
References ALL_EMPIRES, Empires(), and GetIntEmpirePropertyNoKeyImpl().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetIntEmpirePropertyNoKeyImpl()
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertyNoKeyImpl (int empire_id, const std::string & parsed_property_name)
References GetEmpire(), and Empire::OutpostsOwned().
Referenced by GetIntEmpirePropertyNoKey().
GetIntEmpirePropertySingleKey() [1/2]
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertySingleKey (int empire_id, const std::string & parsed_property_name, const std::string & map_key)
References ALL_EMPIRES, Empires(), and GetEmpireStringIntMap().
GetIntEmpirePropertySingleKey() [2/2]
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertySingleKey (int empire_id, const std::string & parsed_property_name, int map_key)
References ALL_EMPIRES, Empires(), and GetEmpireIntIntMap().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetIntEmpirePropertySumAllIntKeys()
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertySumAllIntKeys (int empire_id, const std::string & parsed_property_name)
References ALL_EMPIRES, Empires(), and GetEmpireIntIntMap().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetIntEmpirePropertySumAllStringKeys()
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntEmpirePropertySumAllStringKeys (int empire_id, const std::string & parsed_property_name)
References ALL_EMPIRES, Empires(), and GetEmpireStringIntMap().
Referenced by ValueRef::ComplexVariable< T >::Eval().
GetIntKeyFromContentStringKey()
int ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntKeyFromContentStringKey (const std::string & parsed_property_name, const std::string & key_string)
References GetPredefinedShipDesign(), and ShipDesign::ID().
Referenced by ValueRef::ComplexVariable< T >::Eval().
TechsResearchableByEmpire()
std::vector<std::string> ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchableByEmpire (int empire_id)
References GetEmpire(), GetTechManager(), and Empire::ResearchableTech().
Referenced by ValueRef::ComplexVariable< T >::Eval(), and TransferrableTechs().
TechsResearchedByEmpire()
std::vector<std::string> ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchedByEmpire (int empire_id)
References GetEmpire(), GetTechManager(), and Empire::TechResearched().
Referenced by ValueRef::ComplexVariable< T >::Eval(), and TransferrableTechs().
TransferrableTechs()
std::vector<std::string> ValueRef::anonymous_namespace{ValueRefs.cpp}::TransferrableTechs (int sender_empire_id, int receipient_empire_id)
References TechsResearchableByEmpire(), and TechsResearchedByEmpire().
Referenced by ValueRef::ComplexVariable< T >::Eval().
Variable Documentation
EMPTY_INT_FLOAT_MAP
std::map<int, float> ValueRef::anonymous_namespace{ValueRefs.cpp}::EMPTY_INT_FLOAT_MAP static
Referenced by GetEmpireIntFloatMap().
EMPTY_INT_INT_MAP
std::map<int, int> ValueRef::anonymous_namespace{ValueRefs.cpp}::EMPTY_INT_INT_MAP static
Referenced by GetEmpireIntIntMap().
EMPTY_STRING_INT_MAP
std::map<std::string, int> ValueRef::anonymous_namespace{ValueRefs.cpp}::EMPTY_STRING_INT_MAP static
Referenced by GetEmpireStringIntMap().