FreeOrion: anonymous_namespace{SpecialsPanel.cpp} Namespace Reference
anonymous_namespace{SpecialsPanel.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
const GG::Y SPECIAL_ICON_HEIGHT (24)
const GG::X SPECIAL_ICON_WIDTH (24)
Function Documentation
EDGE_PAD()
const int anonymous_namespace{SpecialsPanel.cpp}::EDGE_PAD (3)
Referenced by SpecialsPanel::Update().
SPECIAL_ICON_HEIGHT()
const GG::Y anonymous_namespace{SpecialsPanel.cpp}::SPECIAL_ICON_HEIGHT (24)
Referenced by SpecialsPanel::Update().
SPECIAL_ICON_WIDTH()
const GG::X anonymous_namespace{SpecialsPanel.cpp}::SPECIAL_ICON_WIDTH (24)
Referenced by SpecialsPanel::Update().