FreeOrion: anonymous_namespace{EncyclopediaDetailPanel.cpp} Namespace Reference
anonymous_namespace{EncyclopediaDetailPanel.cpp} Namespace Reference
Classes
class SearchEdit
Functions
void AddOptions (OptionsDB &db)
int DefaultLocationForEmpire (int empire_id)
constexpr int DESCRIPTION_PADDING (3)
std::string DetermineCustomCategory (const std::set< std::string > &tags)
Checks content tags for a custom defined pedia category.
std::set< std::string > ExtractWords (const std::string &search_text)
const std::string & GeneralTypeOfObject (UniverseObjectType obj_type)
std::string GetDetailedDescriptionBase (const ShipDesign *design)
std::string GetDetailedDescriptionStats (const std::shared_ptr< Ship > ship, const ShipDesign *design, float enemy_DR, std::set< float > enemy_shots, float cost)
void GetRefreshDetailPanelInfo (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, std::weak_ptr< const ShipDesign > &incomplete_design, bool only_description=false)
const std::vector< std::string > & GetSearchTextDirNames ()
void GetSortedPediaDirEntires (const std::string &dir_name, std::multimap< std::string, std::pair< std::string, std::string >> &sorted_entries_list, bool exclude_custom_categories_from_dir_name=true)
Returns map from (Human-readable and thus sorted article name) to pair of (article link tag text, stringtable key for article category or subcategorization of it).
std::map< std::pair< std::string, std::string >, std::pair< std::string, std::string > > GetSubDirs (const std::string &dir_name, bool exclude_custom_categories_from_dir_name=true, int depth=0)
Recursively searches pedia directory dir_name for articles and sub-directories.
GG::Pt HairSpaceExtent ()
int IconSize ()
void MeterTypeDirEntry (const MeterType &meter_type, std::multimap< std::string, std::pair< std::string, std::string >> &list)
std::pair< std::string, std::string > MeterValueLabelAndString (const MeterType &meter_type)
Retreive a value label and general string representation for meter_type.
std::string PediaDirText (const std::string &dir_name)
const std::vector< std::string > & PlanetEnvFilenames (PlanetType planet_type)
void RefreshDetailPanelBuildingTypeTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelEmpireTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelFieldTypeTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelIncomplDesignTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, std::weak_ptr< const ShipDesign > &inc_design, bool only_description=false)
void RefreshDetailPanelMeterTypeTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelObjectTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelPediaTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color)
void RefreshDetailPanelPolicyTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelSearchResultsTag (std::string item_name, std::shared_ptr< GG::Texture > &texture, std::string &general_type, std::string &detailed_description)
void RefreshDetailPanelShipDesignTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelShipHullTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelShipPartTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelSpecialTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelSpeciesTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
void RefreshDetailPanelSuitabilityTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color)
void RefreshDetailPanelTechTag (const std::string &item_type, const std::string &item_name, std::string &name, std::shared_ptr< GG::Texture > &texture, std::shared_ptr< GG::Texture > &other_texture, int &turns, float &cost, std::string &cost_units, std::string &general_type, std::string &specific_type, std::string &detailed_description, GG::Clr &color, bool only_description=false)
std::unordered_set< std::string > ReportedSpeciesForPlanet (std::shared_ptr< Planet > planet)
void SearchPediaArticlesForWords (std::string article_key, std::string article_directory, std::pair< std::string, std::string > article_name_link, std::pair< std::string, std::string > &exact_match, std::pair< std::string, std::string > &word_match, std::pair< std::string, std::string > &partial_match, std::pair< std::string, std::string > &article_match, const std::string &search_text, const std::set< std::string > &words_in_search_text, std::size_t idx, bool search_article_text)
std::multimap< float, std::pair< std::string, PlanetEnvironment > > SpeciesEnvByTargetPop (Planet &planet, const std::unordered_set< std::string > &species_names)
std::unordered_map< std::string, std::string > SpeciesSuitabilityColumn1 (const std::unordered_set< std::string > &species_names)
std::vector< std::string > TechsThatUnlockItem (const UnlockableItem &item)
Variables
const int BTN_WIDTH = 36
const std::string EMPTY_STRING
const std::string GRAPH = "data graph"
const std::string INCOMPLETE_DESIGN = "incomplete design"
const int PAD = 2
const std::string PLANET_SUITABILITY_REPORT = "planet suitability report"
const std::string TAG_ALWAYS_REPORT = "CTRL_ALWAYS_REPORT"
const std::string TAG_EXTINCT = "CTRL_EXTINCT"
const std::string TAG_PEDIA_PREFIX = "PEDIA_"
bool temp_bool = RegisterOptions(&AddOptions)
const std::string TEXT_SEARCH_RESULTS = "dynamic generated text"
const std::string UNIVERSE_OBJECT = "universe object"
Function Documentation
AddOptions()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
DefaultLocationForEmpire()
int anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire (int empire_id)
References ObjectMap::all(), ALL_EMPIRES, DebugLogger, ObjectMap::get(), GetEmpire(), INVALID_OBJECT_ID, and Objects().
Referenced by RefreshDetailPanelBuildingTypeTag(), RefreshDetailPanelIncomplDesignTag(), RefreshDetailPanelShipDesignTag(), RefreshDetailPanelShipHullTag(), and RefreshDetailPanelShipPartTag().
DESCRIPTION_PADDING()
constexpr int anonymous_namespace{EncyclopediaDetailPanel.cpp}::DESCRIPTION_PADDING (3)
Referenced by EncyclopediaDetailPanel::CompleteConstruction().
DetermineCustomCategory()
std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::DetermineCustomCategory (const std::set< std::string > & tags)
Checks content tags for a custom defined pedia category.
Parameters
[in,out] tags content tags to check for a matching pedia prefix tag
Returns
The first matched pedia category for this set of tags, or empty string if there are no matches.
References EMPTY_STRING, and TAG_PEDIA_PREFIX.
Referenced by GetSortedPediaDirEntires().
ExtractWords()
std::set<std::string> anonymous_namespace{EncyclopediaDetailPanel.cpp}::ExtractWords (const std::string & search_text)
Referenced by EncyclopediaDetailPanel::HandleSearchTextEntered().
GeneralTypeOfObject()
const std::string& anonymous_namespace{EncyclopediaDetailPanel.cpp}::GeneralTypeOfObject (UniverseObjectType obj_type)
References EMPTY_STRING, and UserString().
Referenced by RefreshDetailPanelObjectTag().
GetDetailedDescriptionBase()
std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase (const ShipDesign * design)
References ShipDesign::Description(), FlexibleFormat(), ShipDesign::Hull(), LinkTaggedText(), ShipDesign::Parts(), VarText::SHIP_HULL_TAG, VarText::SHIP_PART_TAG, to_string(), and UserString().
Referenced by RefreshDetailPanelIncomplDesignTag(), and RefreshDetailPanelShipDesignTag().
GetDetailedDescriptionStats()
std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats (const std::shared_ptr< Ship > ship, const ShipDesign * design, float enemy_DR, std::set< float > enemy_shots, float cost)
References FlexibleFormat(), parse::species(), and UserString().
Referenced by RefreshDetailPanelIncomplDesignTag(), and RefreshDetailPanelShipDesignTag().
GetRefreshDetailPanelInfo()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetRefreshDetailPanelInfo (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, std::weak_ptr< const ShipDesign > & incomplete_design, bool only_description = false)
References TextLinker::ENCYCLOPEDIA_TAG, TextLinker::GRAPH_TAG, INCOMPLETE_DESIGN, PLANET_SUITABILITY_REPORT, RefreshDetailPanelBuildingTypeTag(), RefreshDetailPanelEmpireTag(), RefreshDetailPanelFieldTypeTag(), RefreshDetailPanelIncomplDesignTag(), RefreshDetailPanelMeterTypeTag(), RefreshDetailPanelObjectTag(), RefreshDetailPanelPediaTag(), RefreshDetailPanelPolicyTag(), RefreshDetailPanelSearchResultsTag(), RefreshDetailPanelShipDesignTag(), RefreshDetailPanelShipHullTag(), RefreshDetailPanelShipPartTag(), RefreshDetailPanelSpecialTag(), RefreshDetailPanelSpeciesTag(), RefreshDetailPanelSuitabilityTag(), RefreshDetailPanelTechTag(), TEXT_SEARCH_RESULTS, and UNIVERSE_OBJECT.
Referenced by EncyclopediaDetailPanel::RefreshImpl(), and SearchPediaArticlesForWords().
GetSearchTextDirNames()
const std::vector<std::string>& anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSearchTextDirNames ()
Referenced by GetSortedPediaDirEntires().
GetSortedPediaDirEntires()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires (const std::string & dir_name, std::multimap< std::string, std::pair< std::string, std::string >> & sorted_entries_list, bool exclude_custom_categories_from_dir_name = true)
Returns map from (Human-readable and thus sorted article name) to pair of (article link tag text, stringtable key for article category or subcategorization of it).
Category is something like "ENC_TECH" and subcategorization is something like a tech category (eg. growth).
References ObjectMap::all(), AllStringtableEntries(), Encyclopedia::Articles(), Universe::beginShipDesigns(), VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, EncyclopediaArticle::category, VarText::DESIGN_ID_TAG, DetermineCustomCategory(), VarText::EMPIRE_ID_TAG, ClientApp::EmpireID(), Empires(), TextLinker::ENCYCLOPEDIA_TAG, Universe::endShipDesigns(), VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, FlexibleFormat(), VarText::FOCS_VALUE_TAG, ObjectMap::get(), GGHumanClientApp::GetApp(), Encyclopedia::GetArticleByKey(), GetBuildingTypeManager(), GetEncyclopedia(), GetFieldTypeManager(), GetNamedValueRefManager(), GetPolicyManager(), GetSearchTextDirNames(), GetShipHullManager(), GetShipPartManager(), SpeciesManager::GetSpeciesHomeworldsMap(), GetSpeciesManager(), Universe::GetStatRecords(), GetTech(), GetTechManager(), GetUniverse(), TextLinker::GRAPH_TAG, LinkTaggedIDText(), LinkTaggedText(), MeterTypeDirEntry(), EncyclopediaArticle::name, Objects(), VarText::PLANET_ID_TAG, VarText::POLICY_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, SpecialNames(), VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, Tech::Tags(), VarText::TECH_TAG, to_string(), and UserString().
Referenced by GetSubDirs(), and PediaDirText().
GetSubDirs()
std::map<std::pair<std::string, std::string>, std::pair<std::string, std::string> > anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSubDirs (const std::string & dir_name, bool exclude_custom_categories_from_dir_name = true, int depth = 0)
Recursively searches pedia directory dir_name for articles and sub-directories.
Returns a map from (category_str_key, dir_name) to (readable_article_name, link_text)
References GetSortedPediaDirEntires(), to_string(), TraceLogger, and WarnLogger.
Referenced by EncyclopediaDetailPanel::HandleSearchTextEntered().
HairSpaceExtent()
GG::Pt anonymous_namespace{EncyclopediaDetailPanel.cpp}::HairSpaceExtent ()
References ClientUI::GetFont().
Referenced by SpeciesSuitabilityColumn1().
IconSize()
int anonymous_namespace{EncyclopediaDetailPanel.cpp}::IconSize ()
References ClientUI::Pts(), and ClientUI::TitlePts().
Referenced by EncyclopediaDetailPanel::DoLayout(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render(), and anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Render().
MeterTypeDirEntry()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterTypeDirEntry (const MeterType & meter_type, std::multimap< std::string, std::pair< std::string, std::string >> & list)
References LinkTaggedPresetText(), VarText::METER_TYPE_TAG, and MeterValueLabelAndString().
Referenced by GetSortedPediaDirEntires().
MeterValueLabelAndString()
std::pair<std::string, std::string> anonymous_namespace{EncyclopediaDetailPanel.cpp}::MeterValueLabelAndString (const MeterType & meter_type)
Retreive a value label and general string representation for meter_type.
References DebugLogger, UserString(), and UserStringExists().
Referenced by MeterTypeDirEntry(), and RefreshDetailPanelMeterTypeTag().
PediaDirText()
std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::PediaDirText (const std::string & dir_name)
References GetSortedPediaDirEntires().
Referenced by RefreshDetailPanelPediaTag().
PlanetEnvFilenames()
const std::vector<std::string>& anonymous_namespace{EncyclopediaDetailPanel.cpp}::PlanetEnvFilenames (PlanetType planet_type)
References ClientUI::ArtDir(), IsExistingFile(), ListDir(), and PathToString().
Referenced by RefreshDetailPanelSuitabilityTag().
RefreshDetailPanelBuildingTypeTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References ClientUI::BuildingIcon(), DefaultLocationForEmpire(), Effect::Dump(), ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), GGHumanClientApp::GetApp(), GetBuildingType(), ClientUI::GetClientUI(), ClientUI::GetMapWnd(), GetOptionsDB(), INVALID_OBJECT_ID, LinkTaggedText(), Objects(), VarText::TECH_TAG, TechsThatUnlockItem(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelEmpireTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References ALL_EMPIRES, BEFORE_FIRST_TURN, VarText::BUILDING_TYPE_TAG, parse::buildings(), DoubleToString(), OrderSet::Dump(), ClientApp::EmpireID(), ErrorLogger, ObjectMap::find(), VarText::FLEET_ID_TAG, FlexibleFormat(), ObjectMap::get(), GGHumanClientApp::GetApp(), GetEmpire(), GetShipDesign(), LinkTaggedIDText(), LinkTaggedText(), ShipDesign::Name(), Objects(), ClientApp::Orders(), VarText::PLANET_ID_TAG, parse::policies(), VarText::POLICY_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_PART_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, parse::techs(), to_string(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelFieldTypeTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References FieldType::Description(), Effect::Dump(), FieldType::Effects(), ErrorLogger, ClientUI::FieldTexture(), OptionsDB::Get(), GetFieldType(), GetOptionsDB(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelIncomplDesignTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, std::weak_ptr< const ShipDesign > & inc_design, bool only_description = false)
References FleetUIManager::ActiveFleetWnd(), ClientUI::ArtDir(), CurrentTurn(), DebugLogger, DefaultLocationForEmpire(), Universe::Delete(), Universe::DeleteShipDesign(), ClientApp::EmpireID(), Empires(), ObjectMap::find(), GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), GetDetailedDescriptionBase(), GetDetailedDescriptionStats(), FleetUIManager::GetFleetUIManager(), ClientUI::GetMapWnd(), ClientUI::GetTexture(), GetUniverse(), ClientUI::HullIcon(), Universe::InhibitUniverseObjectSignals(), Universe::InsertShipDesignID(), Universe::InsertTemp(), INVALID_OBJECT_ID, Objects(), FleetWnd::SelectedFleetIDs(), FleetUIManager::SelectedShipID(), TEMPORARY_OBJECT_ID, Universe::UpdateMeterEstimates(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelMeterTypeTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelMeterTypeTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References ClientUI::MeterIcon(), MeterValueLabelAndString(), UserString(), and UserStringExists().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelObjectTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References ClientApp::EmpireID(), ErrorLogger, GeneralTypeOfObject(), ObjectMap::get(), GGHumanClientApp::GetApp(), INVALID_OBJECT_ID, and Objects().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelPediaTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color)
References GalaxySetupData::age, GalaxySetupData::ai_aggr, ClientUI::ArtDir(), EncyclopediaArticle::category, EncyclopediaArticle::description, FlexibleFormat(), GalaxySetupData::game_uid, ClientApp::GetApp(), GetEncyclopedia(), ClientApp::GetGalaxySetupData(), GetGameRules(), ClientUI::GetTexture(), EncyclopediaArticle::icon, GalaxySetupData::monster_freq, EncyclopediaArticle::name, GalaxySetupData::native_freq, PediaDirText(), GalaxySetupData::planet_density, GalaxySetupData::seed, GalaxySetupData::shape, EncyclopediaArticle::short_description, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, TextForAIAggression(), TextForGalaxySetupSetting(), TextForGalaxyShape(), to_string(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelPolicyTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPolicyTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References Policy::AdoptionCost(), Policy::Category(), Policy::Description(), Effect::Dump(), Policy::Effects(), ClientApp::EmpireID(), ErrorLogger, Policy::Exclusions(), FlexibleFormat(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetOptionsDB(), GetPolicy(), LinkTaggedText(), VarText::POLICY_TAG, ClientUI::PolicyIcon(), Policy::Prerequisites(), Policy::ShortDescription(), VarText::TECH_TAG, TechsThatUnlockItem(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelSearchResultsTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSearchResultsTag (std::string item_name, std::shared_ptr< GG::Texture > & texture, std::string & general_type, std::string & detailed_description)
References ClientUI::ArtDir(), ClientUI::GetTexture(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelShipDesignTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References FleetUIManager::ActiveFleetWnd(), CurrentTurn(), DebugLogger, DefaultLocationForEmpire(), Universe::Delete(), ClientApp::EmpireID(), Empires(), ErrorLogger, ObjectMap::ExistingShips(), ObjectMap::find(), FleetWnd::FleetIDs(), ObjectMap::get(), GGHumanClientApp::GetApp(), ClientUI::GetClientUI(), GetDetailedDescriptionBase(), GetDetailedDescriptionStats(), FleetUIManager::GetFleetUIManager(), ClientUI::GetMapWnd(), GetShipDesign(), GetUniverse(), Universe::InhibitUniverseObjectSignals(), Universe::InsertTemp(), INVALID_DESIGN_ID, INVALID_OBJECT_ID, ShipDesign::IsMonster(), LinkTaggedIDText(), ShipDesign::Name(), Universe::Objects(), ShipDesign::ProductionCost(), ShipDesign::ProductionTime(), FleetWnd::SelectedFleetIDs(), FleetUIManager::SelectedShipID(), FleetWnd::SelectedShipIDs(), VarText::SHIP_ID_TAG, ClientUI::ShipDesignIcon(), Universe::UpdateMeterEstimates(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelShipHullTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References DefaultLocationForEmpire(), Effect::Dump(), ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), GGHumanClientApp::GetApp(), GetOptionsDB(), GetShipHull(), GetShipPart(), ClientUI::HullTexture(), LinkTaggedText(), VarText::SHIP_HULL_TAG, VarText::SHIP_PART_TAG, VarText::TECH_TAG, TechsThatUnlockItem(), to_string(), UserString(), UserStringExists(), and UserStringList().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelShipPartTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References DefaultLocationForEmpire(), Effect::Dump(), ClientApp::EmpireID(), ErrorLogger, GGHumanClientApp::GetApp(), GetOptionsDB(), GetShipHull(), GetShipPart(), LinkTaggedText(), ClientUI::PartIcon(), VarText::SHIP_HULL_TAG, VarText::SHIP_PART_TAG, VarText::TECH_TAG, TechsThatUnlockItem(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelSpecialTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References ObjectMap::all(), VarText::BUILDING_ID_TAG, Special::Description(), Condition::Condition::Dump(), Effect::Dump(), Special::Effects(), ClientApp::EmpireID(), EMPTY_STRING, ErrorLogger, VarText::FLEET_ID_TAG, GGHumanClientApp::GetApp(), GetOptionsDB(), GetSpecial(), LinkTaggedIDText(), Special::Location(), Objects(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, ObjectMap::size(), ClientUI::SpecialIcon(), VarText::SYSTEM_ID_TAG, and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelSpeciesTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References Species::CanColonize(), Species::CanProduceShips(), Species::DefaultFocus(), Species::Description(), Species::Dislikes(), DoubleToString(), Effect::Dump(), Species::Effects(), ClientApp::EmpireID(), ErrorLogger, Species::GameplayDescription(), ObjectMap::get(), OptionsDB::Get(), GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), GetSpecies(), SpeciesManager::GetSpeciesEmpireOpinionsMap(), SpeciesManager::GetSpeciesHomeworldsMap(), GetSpeciesManager(), SpeciesManager::GetSpeciesSpeciesOpinionsMap(), Species::Likes(), LinkTaggedIDText(), Species::Name(), Objects(), VarText::PLANET_ID_TAG, Species::PlanetEnvironments(), parse::species(), ClientUI::SpeciesIcon(), SpeciesManager::SpeciesObjectPopulations(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelSuitabilityTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color)
References DoubleToString(), FlexibleFormat(), ObjectMap::get(), Objects(), PlanetEnvFilenames(), ReportedSpeciesForPlanet(), SpeciesEnvByTargetPop(), SpeciesSuitabilityColumn1(), ClientUI::StatDecrColor(), ClientUI::StatIncrColor(), TraceLogger, and UserString().
Referenced by GetRefreshDetailPanelInfo().
RefreshDetailPanelTechTag()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag (const std::string & item_type, const std::string & item_name, std::string & name, std::shared_ptr< GG::Texture > & texture, std::shared_ptr< GG::Texture > & other_texture, int & turns, float & cost, std::string & cost_units, std::string & general_type, std::string & specific_type, std::string & detailed_description, GG::Clr & color, bool only_description = false)
References VarText::BUILDING_TYPE_TAG, Tech::Category(), ClientUI::CategoryColor(), ClientUI::CategoryIcon(), Tech::Description(), Effect::Dump(), Tech::Effects(), ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), GGHumanClientApp::GetApp(), GetOptionsDB(), GetTech(), LinkTaggedText(), VarText::POLICY_TAG, VarText::PREDEFINED_DESIGN_TAG, Tech::Prerequisites(), Tech::ResearchCost(), Tech::ResearchTime(), VarText::SHIP_HULL_TAG, VarText::SHIP_PART_TAG, Tech::ShortDescription(), VarText::TECH_TAG, ClientUI::TechIcon(), Tech::UnlockedItems(), Tech::UnlockedTechs(), and UserString().
Referenced by GetRefreshDetailPanelInfo().
ReportedSpeciesForPlanet()
std::unordered_set<std::string> anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet (std::shared_ptr< Planet > planet)
References Species::CanColonize(), ClientApp::EmpireID(), GGHumanClientApp::GetApp(), ClientApp::GetEmpire(), GetSpecies(), GetSpeciesManager(), GetTech(), Objects(), parse::species(), TAG_ALWAYS_REPORT, TAG_EXTINCT, and Tech::Tags().
Referenced by RefreshDetailPanelSuitabilityTag().
SearchPediaArticlesForWords()
void anonymous_namespace{EncyclopediaDetailPanel.cpp}::SearchPediaArticlesForWords (std::string article_key, std::string article_directory, std::pair< std::string, std::string > article_name_link, std::pair< std::string, std::string > & exact_match, std::pair< std::string, std::string > & word_match, std::pair< std::string, std::string > & partial_match, std::pair< std::string, std::string > & article_match, const std::string & search_text, const std::set< std::string > & words_in_search_text, std::size_t idx, bool search_article_text)
References Encyclopedia::GetArticleByCategoryAndKey(), GetEncyclopedia(), GetRefreshDetailPanelInfo(), and UserString().
Referenced by EncyclopediaDetailPanel::HandleSearchTextEntered().
SpeciesEnvByTargetPop()
std::multimap<float, std::pair<std::string, PlanetEnvironment> > anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop (Planet & planet, const std::unordered_set< std::string > & species_names)
References Universe::ApplyMeterEffectsAndUpdateMeters(), ClientApp::EmpireID(), Empires(), GGHumanClientApp::GetApp(), GetSpecies(), GetUniverse(), Universe::InhibitUniverseObjectSignals(), and parse::species().
Referenced by RefreshDetailPanelSuitabilityTag().
SpeciesSuitabilityColumn1()
std::unordered_map<std::string, std::string> anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1 (const std::unordered_set< std::string > & species_names)
References ErrorLogger, FlexibleFormat(), ClientUI::GetFont(), HairSpaceExtent(), LinkTaggedText(), VarText::SPECIES_TAG, to_string(), TraceLogger, and UserString().
Referenced by RefreshDetailPanelSuitabilityTag().
TechsThatUnlockItem()
std::vector<std::string> anonymous_namespace{EncyclopediaDetailPanel.cpp}::TechsThatUnlockItem (const UnlockableItem & item)
References GetTechManager().
Referenced by RefreshDetailPanelBuildingTypeTag(), RefreshDetailPanelPolicyTag(), RefreshDetailPanelShipHullTag(), and RefreshDetailPanelShipPartTag().
Variable Documentation
BTN_WIDTH
const int anonymous_namespace{EncyclopediaDetailPanel.cpp}::BTN_WIDTH = 36
Referenced by EncyclopediaDetailPanel::DoLayout(), and EncyclopediaDetailPanel::InitBuffers().
EMPTY_STRING
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::EMPTY_STRING
Referenced by DetermineCustomCategory(), GeneralTypeOfObject(), RefreshDetailPanelSpecialTag(), EncyclopediaDetailPanel::SetIncompleteDesign(), and EncyclopediaDetailPanel::SetItem().
GRAPH
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::GRAPH = "data graph"
INCOMPLETE_DESIGN
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::INCOMPLETE_DESIGN = "incomplete design"
Referenced by GetRefreshDetailPanelInfo(), and EncyclopediaDetailPanel::SetIncompleteDesign().
PAD
const int anonymous_namespace{EncyclopediaDetailPanel.cpp}::PAD = 2
Referenced by IntroScreen::CompleteConstruction(), GraphControl::DoLayout(), SitRepPanel::DoLayout(), MessageWnd::DoLayout(), EncyclopediaDetailPanel::DoLayout(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout(), EncyclopediaDetailPanel::InitBuffers(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), GraphControl::Render(), anonymous_namespace{PlayerListWnd.cpp}::DiplomaticStatusIndicator::Render(), TechTreeWnd::LayoutPanel::TechPanel::Render(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
PLANET_SUITABILITY_REPORT
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::PLANET_SUITABILITY_REPORT = "planet suitability report"
Referenced by GetRefreshDetailPanelInfo(), and EncyclopediaDetailPanel::SetPlanet().
TAG_ALWAYS_REPORT
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::TAG_ALWAYS_REPORT = "CTRL_ALWAYS_REPORT"
CTRL_ALWAYS_REPORT Always display a species on a planet suitability report.
Referenced by ReportedSpeciesForPlanet().
TAG_EXTINCT
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::TAG_EXTINCT = "CTRL_EXTINCT"
CTRL_EXTINCT Added to both a species and their enabling tech.Handles display in planet suitability report.
Referenced by ReportedSpeciesForPlanet().
TAG_PEDIA_PREFIX
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::TAG_PEDIA_PREFIX = "PEDIA_"
PEDIA_ Defines an encyclopedia category for the generated article of the containing content definition.The category name should be postfixed to this tag.
Referenced by DetermineCustomCategory().
temp_bool
bool anonymous_namespace{EncyclopediaDetailPanel.cpp}::temp_bool = RegisterOptions(&AddOptions)
TEXT_SEARCH_RESULTS
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::TEXT_SEARCH_RESULTS = "dynamic generated text"
Referenced by GetRefreshDetailPanelInfo(), and EncyclopediaDetailPanel::HandleSearchTextEntered().
UNIVERSE_OBJECT
const std::string anonymous_namespace{EncyclopediaDetailPanel.cpp}::UNIVERSE_OBJECT = "universe object"
Referenced by GetRefreshDetailPanelInfo(), and EncyclopediaDetailPanel::SetObject().