FreeOrion: anonymous_namespace{MilitaryPanel.cpp} Namespace Reference
anonymous_namespace{MilitaryPanel.cpp} Namespace Reference
Functions
constexpr int EDGE_PAD (3)
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Function Documentation
EDGE_PAD()
constexpr int anonymous_namespace{MilitaryPanel.cpp}::EDGE_PAD (3)
Referenced by MilitaryPanel::CompleteConstruction(), and MilitaryPanel::DoLayout().
MeterIconSize()
GG::Pt anonymous_namespace{MilitaryPanel.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by MilitaryPanel::CompleteConstruction(), and MilitaryPanel::DoLayout().