FreeOrion: anonymous_namespace{ShipDesign.cpp} Namespace Reference
anonymous_namespace{ShipDesign.cpp} Namespace Reference
Functions
void AddDesignToUniverse (std::unordered_map< std::string, int > &design_generic_ids, const std::unique_ptr< ShipDesign > &design, bool monster)
void AddRules (GameRules &rules)
template<typename PendingShips , typename Map1 , typename Map2 , typename Ordering >
void CheckPendingAndFillDesignsOrderingAndNameTables (PendingShips &pending, Map1 &designs, Ordering &ordering, Map2 &name_to_uuid, bool are_monsters)
bool DesignsTheSame (const ShipDesign &one, const ShipDesign &two)
template<typename Map1 , typename Map2 , typename Ordering >
void FillDesignsOrderingAndNameTables (PredefinedShipDesignManager::ParsedShipDesignsType &parsed_designs, Map1 &designs, Ordering &ordering, Map2 &name_to_uuid)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRefBase< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
std::shared_ptr< Effect::EffectsGroup > IncreaseMeter (MeterType meter_type, const std::string &part_name, float increase, bool allow_stacking=true)
Variables
const std::string EMPTY_STRING
bool temp_bool = RegisterGameRules(&AddRules)
Function Documentation
void anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse (std::unordered_map< std::string, int > & design_generic_ids, const std::unique_ptr< ShipDesign > & design, bool monster)
References Universe::beginShipDesigns(), DesignsTheSame(), Universe::endShipDesigns(), ErrorLogger, GetUniverse(), ShipDesign::ID(), Universe::InsertShipDesign(), ShipDesign::ShipDesign(), TraceLogger, and WarnLogger.
Referenced by PredefinedShipDesignManager::AddShipDesignsToUniverse().
void anonymous_namespace{ShipDesign.cpp}::AddRules (GameRules & rules)
References GameRules::Add().
template<typename PendingShips , typename Map1 , typename Map2 , typename Ordering > void anonymous_namespace{ShipDesign.cpp}::CheckPendingAndFillDesignsOrderingAndNameTables (PendingShips & pending, Map1 & designs, Ordering & ordering, Map2 & name_to_uuid, bool are_monsters)
References DebugLogger, FillDesignsOrderingAndNameTables(), TraceLogger, and Pending::WaitForPending().
Referenced by PredefinedShipDesignManager::CheckPendingDesignsTypes().
bool anonymous_namespace{ShipDesign.cpp}::DesignsTheSame (const ShipDesign & one, const ShipDesign & two)
References ShipDesign::Description(), ShipDesign::DesignedOnTurn(), ShipDesign::Hull(), ShipDesign::Icon(), ShipDesign::Model(), ShipDesign::Name(), and ShipDesign::Parts().
Referenced by AddDesignToUniverse().
template<typename Map1 , typename Map2 , typename Ordering > void anonymous_namespace{ShipDesign.cpp}::FillDesignsOrderingAndNameTables (PredefinedShipDesignManager::ParsedShipDesignsType & parsed_designs, Map1 & designs, Ordering & ordering, Map2 & name_to_uuid)
References ErrorLogger, and LoadShipDesignsAndManifestOrderFromParseResults().
Referenced by CheckPendingAndFillDesignsOrderingAndNameTables().
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRefBase< double >> && increase_vr)
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, and ValueRef::PLUS.
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
References IncreaseMeter().
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, float base_increase, const std::string & scaling_factor_rule_name)
References IncreaseMeter(), and ValueRef::TIMES.
std::shared_ptr<Effect::EffectsGroup> anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, const std::string & part_name, float increase, bool allow_stacking = true)
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, and ValueRef::PLUS.
Referenced by IncreaseMeter(), PartType::Init(), and HullType::Init().
Variable Documentation
const std::string anonymous_namespace{ShipDesign.cpp}::EMPTY_STRING
Referenced by ShipDesign::ProductionLocation().
bool anonymous_namespace{ShipDesign.cpp}::temp_bool = RegisterGameRules(&AddRules)