FreeOrion: anonymous_namespace{Pathfinder.cpp} Namespace Reference
anonymous_namespace{Pathfinder.cpp} Namespace Reference
Classes
class distance_matrix_cache
distance_matrix_cache is a cache of symmetric hop distances based on distance_matrix_storage.
struct distance_matrix_storage
distance_matrix_storage implements the storage and the mutexes for distance in number of hops from system to system.
struct GraphImpl
Typedefs
typedef boost::variant< std::nullptr_t, int, std::pair< int, int > > GeneralizedLocationType
GeneralizedLocationType abstracts the location of a UniverseObject.
Functions
std::shared_ptr< const Fleet > FleetFromObject (const std::shared_ptr< const UniverseObject > &obj, const ObjectMap &objects)
GeneralizedLocationType GeneralizedLocation (const std::shared_ptr< const UniverseObject > &obj, const ObjectMap &objects)
Return the location of obj.
GeneralizedLocationType GeneralizedLocation (int object_id, const ObjectMap &objects)
Return the location of the object with id object_id.
Variables
const double WORMHOLE_TRAVEL_DISTANCE = 0.1
Typedef Documentation
GeneralizedLocationType
typedef boost::variant<std::nullptr_t, int, std::pair<int, int> > anonymous_namespace{Pathfinder.cpp}::GeneralizedLocationType
GeneralizedLocationType abstracts the location of a UniverseObject.
GeneralizedLocationType can be nowhere, one system or two systems in the case of a ship or fleet in transit. The returned variant is null_ptr – nowhere System id – somewhere pair of System ids – in transit
Function Documentation
FleetFromObject()
std::shared_ptr<const Fleet> anonymous_namespace{Pathfinder.cpp}::FleetFromObject (const std::shared_ptr< const UniverseObject > & obj, const ObjectMap & objects)
References ObjectMap::get().
Referenced by GeneralizedLocation(), and Pathfinder::PathfinderImpl::ShortestPathDistance().
GeneralizedLocation() [1/2]
GeneralizedLocationType anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation (const std::shared_ptr< const UniverseObject > & obj, const ObjectMap & objects)
Return the location of obj.
References ErrorLogger, FleetFromObject(), ObjectMap::get(), INVALID_OBJECT_ID, TEMPORARY_OBJECT_ID, and TraceLogger.
GeneralizedLocation() [2/2]
GeneralizedLocationType anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation (int object_id, const ObjectMap & objects)
Return the location of the object with id object_id.
References ObjectMap::get().
Referenced by Pathfinder::PathfinderImpl::JumpDistanceBetweenObjects(), Pathfinder::PathfinderImpl::WithinJumpsOfOthers(), and Pathfinder::PathfinderImpl::WithinJumpsOfOthersCacheHit().
Variable Documentation
WORMHOLE_TRAVEL_DISTANCE
const double anonymous_namespace{Pathfinder.cpp}::WORMHOLE_TRAVEL_DISTANCE = 0.1
Referenced by Pathfinder::PathfinderImpl::InitializeSystemGraph().