FreeOrion: anonymous_namespace{ResourcePanel.cpp} Namespace Reference
anonymous_namespace{ResourcePanel.cpp} Namespace Reference
Functions
const int EDGE_PAD (3)
const GG::X METER_BROWSE_LABEL_WIDTH (300)
const GG::X METER_BROWSE_VALUE_WIDTH (50)
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
bool SortByMeterValue (std::pair< MeterType, std::shared_ptr< StatisticIcon >> left, std::pair< MeterType, std::shared_ptr< StatisticIcon >> right)
Function Documentation
EDGE_PAD()
const int anonymous_namespace{ResourcePanel.cpp}::EDGE_PAD (3)
Referenced by ResourcePanel::CompleteConstruction(), and ResourcePanel::DoLayout().
METER_BROWSE_LABEL_WIDTH()
const GG::X anonymous_namespace{ResourcePanel.cpp}::METER_BROWSE_LABEL_WIDTH (300)
METER_BROWSE_VALUE_WIDTH()
const GG::X anonymous_namespace{ResourcePanel.cpp}::METER_BROWSE_VALUE_WIDTH (50)
MeterIconSize()
GG::Pt anonymous_namespace{ResourcePanel.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by ResourcePanel::CompleteConstruction(), and ResourcePanel::DoLayout().
SortByMeterValue()
bool anonymous_namespace{ResourcePanel.cpp}::SortByMeterValue (std::pair< MeterType, std::shared_ptr< StatisticIcon >> left, std::pair< MeterType, std::shared_ptr< StatisticIcon >> right)
Referenced by ResourcePanel::Update().