FreeOrion: anonymous_namespace{FleetWnd.cpp} Namespace Reference
anonymous_namespace{FleetWnd.cpp} Namespace Reference
Classes
class FleetRow
A ListBox::Row subclass used to represent fleets in FleetsListBoxes.
class ShipDataPanel
Shows info about a single ship.
class ShipRow
A ListBox::Row subclass used to represent ships in ShipListBoxes.
Functions
void AddOptions (OptionsDB &db)
FleetAggression AggressionForFleet (FleetAggression aggression_mode, const std::vector< int > &ship_ids)
bool ClientPlayerIsModerator ()
std::shared_ptr< GG::Texture > ColonyIcon ()
bool ContainsArmedShips (const std::vector< int > &ship_ids)
void CreateNewFleetFromShips (const std::vector< int > &ship_ids, FleetAggression aggression)
void CreateNewFleetFromShipsWithDesign (const std::set< int > &ship_ids, int design_id, FleetAggression aggression)
void CreateNewFleetsFromShipsForEachDesign (const std::set< int > &ship_ids, FleetAggression aggression)
GG::Rect CreateOrGrowBox (bool create, const GG::Rect box, const GG::Pt pt)
create or grow a bounding box from pt.
std::shared_ptr< GG::Texture > DamageIcon ()
const GG::Pt DataPanelIconSpace ()
const GG::Flags< GG::GraphicStyle > DataPanelIconStyle ()
std::shared_ptr< GG::Texture > FightersIcon ()
std::shared_ptr< GG::Texture > FleetAggressiveIcon ()
std::shared_ptr< GG::Texture > FleetAggressiveMouseoverIcon ()
std::shared_ptr< GG::Texture > FleetAutoIcon ()
std::shared_ptr< GG::Texture > FleetAutoMouseoverIcon ()
std::shared_ptr< GG::Texture > FleetCountIcon ()
std::string FleetDestinationText (int fleet_id)
std::shared_ptr< GG::Texture > FleetObstructiveIcon ()
std::shared_ptr< GG::Texture > FleetObstructiveMouseoverIcon ()
std::shared_ptr< GG::Texture > FleetPassiveIcon ()
std::shared_ptr< GG::Texture > FleetPassiveMouseoverIcon ()
std::shared_ptr< GG::Texture > IndustryIcon ()
std::shared_ptr< GG::Texture > InfluenceIcon ()
GG::Y LabelHeight ()
GG::Y ListRowHeight ()
void MergeFleetsIntoFleet (int fleet_id)
FleetAggression NewFleetsAggressiveOptionSetting ()
std::map< int, int > PendingScrapOrders ()
Returns map from object ID to issued colonize orders affecting it.
std::shared_ptr< GG::Texture > ResearchIcon ()
void SetNewFleetAggressiveOptionSetting (FleetAggression aggression)
bool SmallerOrEqual (GG::Rect ll, GG::Rect rr)
Is ll smaller or equal to the size of rr?
GG::Pt StatIconSize ()
How big fleet and ship statistics icons should be relative to the current font size.
std::string SystemNameNearestToFleet (int client_empire_id, int fleet_id)
std::shared_ptr< GG::Texture > TroopIcon ()
bool ValidFleetMerge (std::shared_ptr< const Fleet > fleet, std::shared_ptr< const Fleet > target_fleet)
bool ValidShipTransfer (std::shared_ptr< const Ship > ship, std::shared_ptr< const Fleet > new_fleet)
Variables
const int DATA_PANEL_BORDER = 1
const GG::X DATA_PANEL_TEXT_PAD = GG::X(4)
const std::string FLEET_DROP_TYPE_STRING = "FleetWnd FleetRow"
GG::Y FLEET_WND_HEIGHT = GG::Y(400)
const std::string FLEET_WND_NAME = "map.fleet"
GG::X FLEET_WND_WIDTH = GG::X(360)
const int PAD = 4
const std::string SHIP_DROP_TYPE_STRING = "FleetWnd ShipRow"
bool temp_bool = RegisterOptions(&AddOptions)
Function Documentation
AddOptions()
void anonymous_namespace{FleetWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), and UserStringNop.
AggressionForFleet()
FleetAggression anonymous_namespace{FleetWnd.cpp}::AggressionForFleet (FleetAggression aggression_mode, const std::vector< int > & ship_ids)
References ContainsArmedShips().
Referenced by CreateNewFleetFromShips().
ClientPlayerIsModerator()
bool anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator ()
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, HumanClientApp::GetApp(), and ClientApp::GetClientType().
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), CreateNewFleetFromShips(), CreateNewFleetFromShipsWithDesign(), CreateNewFleetsFromShipsForEachDesign(), FleetWnd::FleetRightClicked(), MergeFleetsIntoFleet(), FleetDetailPanel::ShipRightClicked(), and FleetDataPanel::ToggleAggression().
ColonyIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::ColonyIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetWnd::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), and anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh().
ContainsArmedShips()
bool anonymous_namespace{FleetWnd.cpp}::ContainsArmedShips (const std::vector< int > & ship_ids)
References Objects().
Referenced by AggressionForFleet().
CreateNewFleetFromShips()
void anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips (const std::vector< int > & ship_ids, FleetAggression aggression)
References AggressionForFleet(), ALL_EMPIRES, ClientPlayerIsModerator(), ClientApp::EmpireID(), ErrorLogger, ObjectMap::find(), ObjectMap::get(), HumanClientApp::GetApp(), OrderSet::IssueOrder(), Objects(), and ClientApp::Orders().
Referenced by FleetWnd::CreateNewFleetFromDrops(), CreateNewFleetFromShipsWithDesign(), CreateNewFleetsFromShipsForEachDesign(), and FleetWnd::FleetRightClicked().
CreateNewFleetFromShipsWithDesign()
void anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign (const std::set< int > & ship_ids, int design_id, FleetAggression aggression)
References ALL_EMPIRES, ClientPlayerIsModerator(), CreateNewFleetFromShips(), DebugLogger, ClientApp::EmpireID(), ObjectMap::find(), HumanClientApp::GetApp(), INVALID_DESIGN_ID, and Objects().
Referenced by FleetDetailPanel::ShipRightClicked().
CreateNewFleetsFromShipsForEachDesign()
void anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign (const std::set< int > & ship_ids, FleetAggression aggression)
References ALL_EMPIRES, ClientPlayerIsModerator(), CreateNewFleetFromShips(), DebugLogger, ClientApp::EmpireID(), HumanClientApp::GetApp(), and Objects().
Referenced by FleetWnd::FleetRightClicked(), and FleetDetailPanel::ShipRightClicked().
CreateOrGrowBox()
GG::Rect anonymous_namespace{FleetWnd.cpp}::CreateOrGrowBox (bool create, const GG::Rect box, const GG::Pt pt)
create or grow a bounding box from pt.
Referenced by FleetWnd::FleetWnd(), and FleetWnd::Refresh().
DamageIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::DamageIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetWnd::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), and FleetDataPanel::Init().
DataPanelIconSpace()
const GG::Pt anonymous_namespace{FleetWnd.cpp}::DataPanelIconSpace ()
References ClientUI::Pts().
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::DoLayout(), FleetDataPanel::DoLayout(), ListRowHeight(), FleetDataPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), FleetDataPanel::Render(), and anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon().
DataPanelIconStyle()
const GG::Flags<GG::GraphicStyle> anonymous_namespace{FleetWnd.cpp}::DataPanelIconStyle ()
Referenced by FleetDataPanel::Refresh(), and anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon().
FightersIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FightersIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetWnd::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), and FleetDataPanel::Init().
FleetAggressiveIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetAggressiveIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::Init(), and FleetDataPanel::UpdateAggressionToggle().
FleetAggressiveMouseoverIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetAggressiveMouseoverIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::Init(), and FleetDataPanel::UpdateAggressionToggle().
FleetAutoIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetAutoIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::UpdateAggressionToggle().
FleetAutoMouseoverIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::UpdateAggressionToggle().
FleetCountIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetCountIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetWnd::CompleteConstruction(), and FleetDataPanel::Init().
FleetDestinationText()
std::string anonymous_namespace{FleetWnd.cpp}::FleetDestinationText (int fleet_id)
References ClientApp::EmpireID(), FlexibleFormat(), ObjectMap::get(), OptionsDB::Get(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), ClientUI::GetMapWnd(), GetOptionsDB(), Objects(), to_string(), and UserString().
Referenced by FleetDataPanel::Refresh().
FleetObstructiveIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetObstructiveIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::UpdateAggressionToggle().
FleetObstructiveMouseoverIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetObstructiveMouseoverIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::UpdateAggressionToggle().
FleetPassiveIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetPassiveIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::Init(), and FleetDataPanel::UpdateAggressionToggle().
FleetPassiveMouseoverIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::FleetPassiveMouseoverIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetDataPanel::UpdateAggressionToggle().
IndustryIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::IndustryIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), and FleetDataPanel::Init().
InfluenceIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::InfluenceIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), and FleetDataPanel::Init().
LabelHeight()
GG::Y anonymous_namespace{FleetWnd.cpp}::LabelHeight ()
References ClientUI::Pts().
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::DoLayout(), FleetDataPanel::DoLayout(), FleetDetailPanel::DoLayout(), ListRowHeight(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), and FleetDataPanel::Render().
ListRowHeight()
GG::Y anonymous_namespace{FleetWnd.cpp}::ListRowHeight ()
References DataPanelIconSpace(), LabelHeight(), PAD, and StatIconSize().
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::BuildableItemsListBox(), FleetWnd::CompleteConstruction(), ObjectListBox::CompleteConstruction(), SaveFileListBox::ListRowSize(), anonymous_namespace{BuildDesignatorWnd.cpp}::BuildableItemsListBox::ListRowSize(), PlayerListBox::ListRowSize(), ObjectListBox::ListRowSize(), FleetsListBox::ListRowSize(), and ShipsListBox::ListRowSize().
MergeFleetsIntoFleet()
void anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet (int fleet_id)
References ALL_EMPIRES, ClientPlayerIsModerator(), ClientApp::EmpireID(), ErrorLogger, ObjectMap::get(), HumanClientApp::GetApp(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), Objects(), and ClientApp::Orders().
Referenced by FleetWnd::FleetRightClicked().
NewFleetsAggressiveOptionSetting()
FleetAggression anonymous_namespace{FleetWnd.cpp}::NewFleetsAggressiveOptionSetting ()
References OptionsDB::Get(), and GetOptionsDB().
PendingScrapOrders()
std::map<int, int> anonymous_namespace{FleetWnd.cpp}::PendingScrapOrders ()
Returns map from object ID to issued colonize orders affecting it.
References ClientApp::GetApp(), and ClientApp::Orders().
Referenced by FleetDetailPanel::ShipRightClicked().
ResearchIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::ResearchIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), and FleetDataPanel::Init().
SetNewFleetAggressiveOptionSetting()
void anonymous_namespace{FleetWnd.cpp}::SetNewFleetAggressiveOptionSetting (FleetAggression aggression)
References GetOptionsDB(), and OptionsDB::Set().
Referenced by FleetDataPanel::ToggleAggression().
SmallerOrEqual()
bool anonymous_namespace{FleetWnd.cpp}::SmallerOrEqual (GG::Rect ll, GG::Rect rr)
Is ll smaller or equal to the size of rr?
Referenced by FleetWnd::Refresh().
StatIconSize()
GG::Pt anonymous_namespace{FleetWnd.cpp}::StatIconSize ()
How big fleet and ship statistics icons should be relative to the current font size.
Icons shouldn't scale below what they are for the default, 12 pt, font size.
References ClientUI::Pts().
Referenced by FleetWnd::CompleteConstruction(), FleetWnd::DoLayout(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::DoLayout(), FleetDataPanel::DoLayout(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), and ListRowHeight().
SystemNameNearestToFleet()
std::string anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet (int client_empire_id, int fleet_id)
References ObjectMap::get(), GetPathfinder(), and Objects().
Referenced by FleetWnd::TitleText().
TroopIcon()
std::shared_ptr<GG::Texture> anonymous_namespace{FleetWnd.cpp}::TroopIcon ()
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by FleetWnd::CompleteConstruction(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), and anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh().
ValidFleetMerge()
bool anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge (std::shared_ptr< const Fleet > fleet, std::shared_ptr< const Fleet > target_fleet)
References INVALID_OBJECT_ID.
Referenced by FleetsListBox::DragDropHere(), and FleetsListBox::DropsAcceptable().
ValidShipTransfer()
bool anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer (std::shared_ptr< const Ship > ship, std::shared_ptr< const Fleet > new_fleet)
References ObjectMap::get(), INVALID_OBJECT_ID, and Objects().
Referenced by FleetsListBox::DragDropHere(), FleetsListBox::DropsAcceptable(), and ShipsListBox::DropsAcceptable().
Variable Documentation
DATA_PANEL_BORDER
const int anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER = 1
Referenced by anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::ClientLowerRight(), FleetDataPanel::ClientLowerRight(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::ClientUpperLeft(), FleetDataPanel::ClientUpperLeft(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), and FleetDataPanel::Render().
DATA_PANEL_TEXT_PAD
const GG::X anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_TEXT_PAD = GG::X(4)
Referenced by FleetWnd::DoLayout(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::DoLayout(), and FleetDataPanel::DoLayout().
FLEET_DROP_TYPE_STRING
const std::string anonymous_namespace{FleetWnd.cpp}::FLEET_DROP_TYPE_STRING = "FleetWnd FleetRow"
Referenced by FleetsListBox::AcceptDrops(), FleetWnd::CompleteConstruction(), FleetsListBox::DragDropHere(), FleetsListBox::DropsAcceptable(), and anonymous_namespace{FleetWnd.cpp}::FleetRow::FleetRow().
FLEET_WND_HEIGHT
GG::Y anonymous_namespace{FleetWnd.cpp}::FLEET_WND_HEIGHT = GG::Y(400)
Referenced by FleetWnd::CalculatePosition().
FLEET_WND_NAME
const std::string anonymous_namespace{FleetWnd.cpp}::FLEET_WND_NAME = "map.fleet"
Referenced by FleetUIManager::NewFleetWnd().
FLEET_WND_WIDTH
GG::X anonymous_namespace{FleetWnd.cpp}::FLEET_WND_WIDTH = GG::X(360)
Referenced by FleetWnd::CalculatePosition().
PAD
const int anonymous_namespace{FleetWnd.cpp}::PAD = 4
Referenced by FleetWnd::CompleteConstruction(), FleetWnd::DoLayout(), and ListRowHeight().
SHIP_DROP_TYPE_STRING
const std::string anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING = "FleetWnd ShipRow"
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), FleetWnd::CompleteConstruction(), FleetsListBox::DragDropHere(), FleetDataPanel::DropsAcceptable(), FleetsListBox::DropsAcceptable(), FleetDetailPanel::FleetDetailPanel(), and anonymous_namespace{FleetWnd.cpp}::ShipRow::ShipRow().
temp_bool
bool anonymous_namespace{FleetWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)