FreeOrion: anonymous_namespace{ServerFSM.cpp} Namespace Reference
anonymous_namespace{ServerFSM.cpp} Namespace Reference
Functions
DeclareThreadSafeLogger (FSM)
std::string GenerateEmpireName (const std::string &player_name, std::list< std::pair< int, PlayerSetupData >> &players)
std::string GetAutoSaveFileName (int current_turn)
std::string GetHostNameFromSinglePlayerSetupData (const SinglePlayerSetupData &single_player_setup_data)
EmpireColor GetUnusedEmpireColour (const std::list< std::pair< int, PlayerSetupData >> &psd, const std::map< int, SaveGameEmpireData > &sged=std::map< int, SaveGameEmpireData >())
bool HandleErrorMessage (const Error &msg, ServerApp &server)
Return true for fatal errors.
bool IsPlayerChanged (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
void LogPlayerSetupData (const std::list< std::pair< int, PlayerSetupData >> &psd)
void SendMessageToAllPlayers (const Message &message)
void SendMessageToHost (const Message &message)
Variables
constexpr EmpireColor CLR_SERVER {255, 255, 255, 255}
constexpr EmpireColor CLR_ZERO {0, 0, 0, 0}
Function Documentation
DeclareThreadSafeLogger()
anonymous_namespace{ServerFSM.cpp}::DeclareThreadSafeLogger (FSM)
GenerateEmpireName()
std::string anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName (const std::string & player_name, std::list< std::pair< int, PlayerSetupData >> & players)
References RandInt(), and UserStringList().
Referenced by MPLobby::EstablishPlayer(), IsPlayerChanged(), Idle::react(), and MPLobby::react().
GetAutoSaveFileName()
std::string anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName (int current_turn)
References FilenameTimestamp(), GetGalaxySetupData(), GalaxySetupData::GetGameUID(), GetServerSaveDir(), and MP_SAVE_FILE_EXTENSION.
Referenced by ServerFSM::HandleNonLobbyDisconnection(), PlayingGame::react(), WaitingForTurnEnd::react(), ProcessingTurn::react(), and WaitingForTurnEnd::SaveTimedoutHandler().
GetHostNameFromSinglePlayerSetupData()
std::string anonymous_namespace{ServerFSM.cpp}::GetHostNameFromSinglePlayerSetupData (const SinglePlayerSetupData & single_player_setup_data)
References PlayerSetupData::client_type, Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, SinglePlayerSetupData::filename, LoadPlayerSaveHeaderData(), SinglePlayerSetupData::new_game, PlayerSetupData::player_name, and SinglePlayerSetupData::players.
Referenced by Idle::react().
GetUnusedEmpireColour()
EmpireColor anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour (const std::list< std::pair< int, PlayerSetupData >> & psd, const std::map< int, SaveGameEmpireData > & sged = std::map<int, SaveGameEmpireData>())
References EmpireColors().
Referenced by MPLobby::EstablishPlayer(), IsPlayerChanged(), Idle::react(), and MPLobby::react().
HandleErrorMessage()
bool anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage (const Error & msg, ServerApp & server)
Return true for fatal errors.
References ErrorLogger, ErrorMessage(), ExtractErrorMessageData(), and SendMessageToAllPlayers().
Referenced by Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), and ShuttingDownServer::react().
IsPlayerChanged()
bool anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged (const PlayerSetupData & lhs, const PlayerSetupData & rhs)
References PlayerSetupData::authenticated, PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ClockSeed(), DebugLogger, ServerNetworking::Disconnect(), PlayerSetupData::empire_color, PlayerSetupData::empire_name, EmpireColors(), GenerateEmpireName(), OptionsDB::Get(), GetGameRules(), GetOptionsDB(), ServerNetworking::GetPlayer(), GameRules::GetRulesAsStrings(), GetSpeciesManager(), GetUnusedEmpireColour(), ServerNetworking::HostPlayerID(), Networking::INVALID_PLAYER_ID, ServerApp::IsHostless(), ServerApp::LoadChatHistory(), ServerApp::m_networking, MPLobby::MPLobby(), ServerApp::Networking(), PlayerSetupData::player_id, PlayerSetupData::player_name, SpeciesManager::RandomPlayableSpeciesName(), PlayerSetupData::save_game_empire_id, ServerNetworking::SendMessageAll(), SpeciesManager::SequentialPlayableSpeciesName(), ServerLobbyUpdateMessage(), PlayerSetupData::starting_species_name, to_string(), TraceLogger, UserString(), and MPLobby::~MPLobby().
Referenced by MPLobby::react().
LogPlayerSetupData()
void anonymous_namespace{ServerFSM.cpp}::LogPlayerSetupData (const std::list< std::pair< int, PlayerSetupData >> & psd)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, and to_string().
Referenced by MPLobby::react().
SendMessageToAllPlayers()
void anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers (const Message & message)
References ErrorLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerApp::GetApp(), and ServerApp::Networking().
Referenced by HandleErrorMessage(), ServerFSM::HandleNonLobbyDisconnection(), MPLobby::react(), PlayingGame::react(), and WaitingForTurnEnd::react().
SendMessageToHost()
void anonymous_namespace{ServerFSM.cpp}::SendMessageToHost (const Message & message)
References ErrorLogger, ServerNetworking::established_end(), ServerApp::GetApp(), ServerNetworking::GetPlayer(), ServerNetworking::HostPlayerID(), and ServerApp::Networking().
Referenced by WaitingForSPGameJoiners::react(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
Variable Documentation
CLR_SERVER
constexpr EmpireColor anonymous_namespace{ServerFSM.cpp}::CLR_SERVER {255, 255, 255, 255}
Referenced by ServerFSM::EstablishPlayer(), ServerFSM::HandleNonLobbyDisconnection(), MPLobby::react(), WaitingForMPGameJoiners::react(), and MPLobby::ValidateClientLimits().
CLR_ZERO
constexpr EmpireColor anonymous_namespace{ServerFSM.cpp}::CLR_ZERO {0, 0, 0, 0}
Referenced by PlayerListWnd::CompleteConstruction(), ObjectListWnd::CompleteConstruction(), CUILinkTextBlock::CompleteConstruction(), FleetWnd::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), FleetDetailPanel::FleetDetailPanel(), anonymous_namespace{GalaxySetupWnd.cpp}::GameRulesList::GameRulesList(), InitEmpires(), CUIStyle::NewHScrollTabButton(), CUIStyle::NewVScrollTabButton(), anonymous_namespace{OptionsWnd.cpp}::OptionsList::OptionsList(), MPLobby::react(), SidePanel::PlanetPanel::Refresh(), EncyclopediaDetailPanel::RefreshImpl(), MultiMeterStatusBar::Render(), CUISlider< T >::Render(), CUI_MinRestoreButton::Render(), QueueListBox::Render(), DesignWnd::Render(), CreditsWnd::Render(), CUICheckBoxRepresenter::Render(), CUIRadioRepresenter::Render(), CUIListBox::Render(), CUIEdit::Render(), ParticipantBar::Render(), SaveFileRow::Render(), CUIMultiEdit::Render(), TechTreeWnd::LayoutPanel::Render(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Render(), FleetDataPanel::Render(), anonymous_namespace{CUIControls.cpp}::ColorRow::ColorSquare::Render(), TextLinker::Render_(), MapWnd::RenderMovementLine(), MapWnd::RenderMovementLineETAIndicators(), CUIArrowButton::RenderPressed(), CUIArrowButton::RenderRollover(), CUIArrowButton::RenderUnpressed(), and Triangle().