FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp} Namespace Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp} Namespace Reference
Classes
struct EmptyPlayerRow
struct LoadGameEmpireRow
struct LoadGamePlayerRow
struct NewGamePlayerRow
struct PlayerRow
class TypeSelector
Functions
constexpr GG::X BROWSE_BTN_WIDTH (50)
constexpr GG::X CHAT_WIDTH (350)
constexpr GG::X EMPIRE_NAME_WIDTH (150)
constexpr GG::Y GALAXY_SETUP_PANEL_HEIGHT (340)
constexpr GG::X GALAXY_SETUP_PANEL_WIDTH (250)
const std::shared_ptr< GG::Texture > GetHostTexture ()
const std::shared_ptr< GG::Texture > GetReadyTexture (bool ready)
constexpr GG::Y LOBBY_WND_HEIGHT (720)
constexpr GG::X LOBBY_WND_WIDTH (960)
void LogPlayerSetupData (const std::list< std::pair< int, PlayerSetupData >> &psd)
GG::Y PlayerFontHeight ()
GG::X PlayerReadyBrowseWidth ()
std::vector< GG::X > PlayerRowColWidths (GG::X width=GG::X{600})
GG::Y PlayerRowHeight ()
GG::Y PlayerRowMargin ()
constexpr GG::Pt PREVIEW_SZ (GG::X{PREVIEW_WIDTH}, GG::Y{186})
constexpr GG::Y SAVED_GAMES_LIST_DROP_HEIGHT (10 *Value(SAVED_GAMES_LIST_ROW_HEIGHT))
constexpr GG::Y SAVED_GAMES_LIST_ROW_HEIGHT (22)
Variables
constexpr int CONTROL_MARGIN = 5
GG::Pt g_preview_ul
constexpr int GALAXY_SETUP_PANEL_MARGIN = 45
constexpr int PREVIEW_MARGIN = 3
constexpr int PREVIEW_WIDTH = 248
Function Documentation
BROWSE_BTN_WIDTH()
constexpr GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::BROWSE_BTN_WIDTH (50)
Referenced by GetHostTexture().
CHAT_WIDTH()
constexpr GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::CHAT_WIDTH (350)
Referenced by MultiPlayerLobbyWnd::DoLayout().
EMPIRE_NAME_WIDTH()
constexpr GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::EMPIRE_NAME_WIDTH (150)
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::DoLayout(), and GetHostTexture().
GALAXY_SETUP_PANEL_HEIGHT()
constexpr GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_HEIGHT (340)
Referenced by MultiPlayerLobbyWnd::CompleteConstruction(), and MultiPlayerLobbyWnd::DoLayout().
GALAXY_SETUP_PANEL_WIDTH()
constexpr GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_WIDTH (250)
Referenced by MultiPlayerLobbyWnd::CompleteConstruction(), and MultiPlayerLobbyWnd::DoLayout().
GetHostTexture()
const std::shared_ptr<GG::Texture> anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetHostTexture ()
References ClientUI::ArtDir(), BROWSE_BTN_WIDTH(), EMPIRE_NAME_WIDTH(), and ClientUI::GetTexture().
Referenced by MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction().
GetReadyTexture()
const std::shared_ptr<GG::Texture> anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetReadyTexture (bool ready)
References ClientUI::ArtDir(), and ClientUI::GetTexture().
Referenced by MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction().
LOBBY_WND_HEIGHT()
constexpr GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::LOBBY_WND_HEIGHT (720)
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::PlayerTypeChanged().
LOBBY_WND_WIDTH()
constexpr GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::LOBBY_WND_WIDTH (960)
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::PlayerTypeChanged().
LogPlayerSetupData()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LogPlayerSetupData (const std::list< std::pair< int, PlayerSetupData >> & psd)
References DebugLogger, and to_string().
Referenced by MultiPlayerLobbyWnd::LobbyUpdate().
PlayerFontHeight()
GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight ()
References ClientUI::GetFont(), and ClientUI::Pts().
Referenced by MultiPlayerLobbyWnd::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::CompleteConstruction(), and PlayerRowHeight().
PlayerReadyBrowseWidth()
GG::X anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerReadyBrowseWidth ()
References ClientUI::Pts().
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction().
PlayerRowColWidths()
std::vector<GG::X> anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowColWidths (GG::X width = GG::X{600})
References CONTROL_MARGIN, and ClientUI::Pts().
Referenced by MultiPlayerLobbyWnd::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), MultiPlayerLobbyWnd::DoLayout(), and MultiPlayerLobbyWnd::PopulatePlayerList().
PlayerRowHeight()
GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight ()
References PlayerFontHeight(), and PlayerRowMargin().
Referenced by MultiPlayerLobbyWnd::CompleteConstruction(), MultiPlayerLobbyWnd::PlayerLabelRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::CompleteConstruction(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::CompleteConstruction().
PlayerRowMargin()
GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowMargin ()
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::CompleteConstruction(), and PlayerRowHeight().
PREVIEW_SZ()
constexpr GG::Pt anonymous_namespace{MultiplayerLobbyWnd.cpp}::PREVIEW_SZ (GG::X{PREVIEW_WIDTH} , GG::Y{186})
Referenced by MultiPlayerLobbyWnd::DoLayout(), and MultiPlayerLobbyWnd::Render().
SAVED_GAMES_LIST_DROP_HEIGHT()
constexpr GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::SAVED_GAMES_LIST_DROP_HEIGHT (10 * ValueSAVED_GAMES_LIST_ROW_HEIGHT)
SAVED_GAMES_LIST_ROW_HEIGHT()
constexpr GG::Y anonymous_namespace{MultiplayerLobbyWnd.cpp}::SAVED_GAMES_LIST_ROW_HEIGHT (22)
Variable Documentation
CONTROL_MARGIN
constexpr int anonymous_namespace{MultiplayerLobbyWnd.cpp}::CONTROL_MARGIN = 5
Referenced by MultiPlayerLobbyWnd::DoLayout(), and PlayerRowColWidths().
g_preview_ul
GG::Pt anonymous_namespace{MultiplayerLobbyWnd.cpp}::g_preview_ul
GALAXY_SETUP_PANEL_MARGIN
constexpr int anonymous_namespace{MultiplayerLobbyWnd.cpp}::GALAXY_SETUP_PANEL_MARGIN = 45
PREVIEW_MARGIN
constexpr int anonymous_namespace{MultiplayerLobbyWnd.cpp}::PREVIEW_MARGIN = 3
PREVIEW_WIDTH
constexpr int anonymous_namespace{MultiplayerLobbyWnd.cpp}::PREVIEW_WIDTH = 248