FreeOrion: anonymous_namespace{ObjectListWnd.cpp} Namespace Reference
anonymous_namespace{ObjectListWnd.cpp} Namespace Reference
Classes
struct CustomRowCmp
Typedefs
using id_range = boost::any_range< int, boost::forward_traversal_tag >
Enumerations
enum VIS_DISPLAY { SHOW_VISIBLE, SHOW_PREVIOUSLY_VISIBLE, SHOW_DESTROYED }
Functions
void AddOptions (OptionsDB &db)
const std::string ALL_CONDITION (UserStringNop("CONDITION_ALL"))
const std::string ARMED_CONDITION (UserStringNop("CONDITION_ARMED"))
const std::string ASTWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_AST"))
const std::map< std::pair< std::string, std::string >, std::unique_ptr< ValueRef::ValueRef< std::string > > > & AvailableColumnTypes ()
const std::string BUILDING_CONDITION (UserStringNop("CONDITION_BUILDING"))
const std::string CANCOLONIZE_CONDITION (UserStringNop("CONDITION_CANCOLONIZE"))
const std::string CANPRODUCESHIPS_CONDITION (UserStringNop("CONDITION_CANPRODUCESHIPS"))
const std::string CAPITAL_CONDITION (UserStringNop("CONDITION_CAPITAL"))
const std::string & ConditionClassName (const Condition::Condition *const condition)
std::unique_ptr< Condition::Condition > ConditionForObjectTypes (const std::vector< UniverseObjectType > &object_types)
const std::string CONTAINEDBY_CONDITION (UserStringNop("CONDITION_CONTAINEDBY"))
template<typename enumT >
std::unique_ptr< ValueRef::ValueRef< enumT > > CopyEnumValueRef (const ValueRef::ValueRef< enumT > *const value_ref)
const std::string CREATEDONTURN_CONDITION (UserStringNop("CONDITION_CREATEDONTURN"))
std::unique_ptr< ValueRef::Variable< std::string > > DesignCostValueRef ()
std::unique_ptr< ValueRef::Variable< std::string > > DesignNameValueRef (const char *token)
const std::string EMPIREAFFILIATION_CONDITION (UserStringNop("CONDITION_EMPIREAFFILIATION"))
std::unique_ptr< ValueRef::Variable< std::string > > EmpireNameValueRef (const char *token)
const std::string EXPLOREDBYEMPIRE_CONDITION (UserStringNop("CONDITION_EXPLOREDBYEMPIRE"))
const std::string FOCUSTYPE_CONDITION (UserStringNop("CONDITION_FOCUSTYPE"))
std::string GetColumnName (int column)
unused function.
const ValueRef::ValueRef< std::string > * GetColumnValueRef (int column)
int GetColumnWidth (int column)
const ValueRef::ValueRef< std::string > * GetValueRefByName (const std::string &name)
const std::string GGWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_GG"))
const std::string HASGROWTHSPECIAL_CONDITION (UserStringNop("CONDITION_HAS_GROWTH_SPECIAL"))
const std::string HASSPECIAL_CONDITION (UserStringNop("CONDITION_HASSPECIAL"))
const std::string HASTAG_CONDITION (UserStringNop("CONDITION_HASTAG"))
const std::string HOMEWORLD_CONDITION (UserStringNop("CONDITION_HOMEWORLD"))
const std::string INSYSTEM_CONDITION (UserStringNop("CONDITION_INSYSTEM"))
const std::string METERVALUE_CONDITION (UserStringNop("CONDITION_METERVALUE"))
const std::string MONSTER_CONDITION (UserStringNop("CONDITION_MONSTER"))
const unsigned int NUM_COLUMNS (12u)
const std::string OBJECTID_CONDITION (UserStringNop("CONDITION_OBJECTID"))
std::unique_ptr< ValueRef::Variable< std::string > > ObjectNameValueRef (const char *token)
std::vector< std::shared_ptr< GG::Texture > > ObjectTextures (std::shared_ptr< const UniverseObject > obj)
template<typename T >
std::unique_ptr< ValueRef::ValueRef< T > > ObjectTypeFilteredRef (const std::vector< UniverseObjectType > &object_types, std::unique_ptr< ValueRef::ValueRef< T >> &&value_ref)
const GG::X PAD (3)
std::unique_ptr< ValueRef::ValueRef< std::string > > PlanetEnvForSpecies (const std::string &species_name)
const std::string PLANETSIZE_CONDITION (UserStringNop("CONDITION_PLANETSIZE"))
const std::string PLANETTYPE_CONDITION (UserStringNop("CONDITION_PLANETTYPE"))
const std::string PRODUCEDBYEMPIRE_CONDITION (UserStringNop("CONDITION_PRODUCEDBYEMPIRE"))
void SetColumnName (int column, const std::string &name)
const std::string SPECIES_CONDITION (UserStringNop("CONDITION_SPECIES"))
const std::string STARTYPE_CONDITION (UserStringNop("CONDITION_STARTYPE"))
const std::string STATIONARY_CONDITION (UserStringNop("CONDITION_STATIONARY"))
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > StringCastedComplexValueRef (const char *token, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref1=nullptr, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref2=nullptr, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref3=nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> &&string_ref1=nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> &&string_ref2=nullptr)
std::unique_ptr< ValueRef::Variable< std::string > > StringCastedImmediateValueRef (std::string token)
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > StringCastedValueRef (const char *token)
template<typename enumT >
std::vector< std::string > StringsFromEnums (const std::vector< enumT > &enum_vals)
std::unique_ptr< ValueRef::Variable< std::string > > StringValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > SystemSupplyDistanceValueRef ()
std::unique_ptr< ValueRef::Variable< std::string > > SystemSupplyRangeValueRef (bool propagated=false)
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > UserStringCastedValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > UserStringValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > UserStringVecValueRef (const char *token)
Variables
const int DATA_PANEL_BORDER = 1
const std::string EMPTY_STRING
const std::string FILTER_OPTIONS_WND_NAME = "object-list-filter"
std::map< std::string, std::string > object_list_cond_description_map
bool temp_bool = RegisterOptions(&AddOptions)
Typedef Documentation
id_range
using anonymous_namespace{ObjectListWnd.cpp}::id_range = typedef boost::any_range<int, boost::forward_traversal_tag>
Enumeration Type Documentation
VIS_DISPLAY
enum anonymous_namespace{ObjectListWnd.cpp}::VIS_DISPLAY
Enumerator
SHOW_VISIBLE
SHOW_PREVIOUSLY_VISIBLE
SHOW_DESTROYED
Function Documentation
AddOptions()
void anonymous_namespace{ObjectListWnd.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), NUM_COLUMNS(), to_string(), and UserStringNop.
ALL_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::ALL_CONDITION (UserStringNop("CONDITION_ALL"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
ARMED_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::ARMED_CONDITION (UserStringNop("CONDITION_ARMED"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
ASTWITHPTYPE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::ASTWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_AST"))
Referenced by ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
AvailableColumnTypes()
const std::map<std::pair<std::string, std::string>, std::unique_ptr<ValueRef::ValueRef<std::string> > >& anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes ()
References DesignCostValueRef(), DesignNameValueRef(), EmpireNameValueRef(), GetSpeciesManager(), ValueRef::MeterToName(), ObjectNameValueRef(), PlanetEnvForSpecies(), StringCastedImmediateValueRef(), StringValueRef(), SystemSupplyDistanceValueRef(), SystemSupplyRangeValueRef(), UserStringNop, UserStringValueRef(), and UserStringVecValueRef().
Referenced by ObjectHeaderPanel::ButtonRightClicked(), and GetValueRefByName().
BUILDING_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::BUILDING_CONDITION (UserStringNop("CONDITION_BUILDING"))
Referenced by ConditionClassName().
CANCOLONIZE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::CANCOLONIZE_CONDITION (UserStringNop("CONDITION_CANCOLONIZE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
CANPRODUCESHIPS_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::CANPRODUCESHIPS_CONDITION (UserStringNop("CONDITION_CANPRODUCESHIPS"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
CAPITAL_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::CAPITAL_CONDITION (UserStringNop("CONDITION_CAPITAL"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
ConditionClassName()
const std::string& anonymous_namespace{ObjectListWnd.cpp}::ConditionClassName (const Condition::Condition *const condition)
References ALL_CONDITION(), ARMED_CONDITION(), BUILDING_CONDITION(), CANCOLONIZE_CONDITION(), CANPRODUCESHIPS_CONDITION(), CAPITAL_CONDITION(), CONTAINEDBY_CONDITION(), CREATEDONTURN_CONDITION(), Condition::Condition::Description(), EMPIREAFFILIATION_CONDITION(), EXPLOREDBYEMPIRE_CONDITION(), FOCUSTYPE_CONDITION(), HASSPECIAL_CONDITION(), HASTAG_CONDITION(), HOMEWORLD_CONDITION(), INSYSTEM_CONDITION(), METERVALUE_CONDITION(), MONSTER_CONDITION(), OBJECTID_CONDITION(), PLANETSIZE_CONDITION(), PLANETTYPE_CONDITION(), PRODUCEDBYEMPIRE_CONDITION(), SPECIES_CONDITION(), STARTYPE_CONDITION(), and STATIONARY_CONDITION().
Referenced by ConditionWidget::Init().
ConditionForObjectTypes()
std::unique_ptr<Condition::Condition> anonymous_namespace{ObjectListWnd.cpp}::ConditionForObjectTypes (const std::vector< UniverseObjectType > & object_types)
Referenced by ObjectTypeFilteredRef().
CONTAINEDBY_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::CONTAINEDBY_CONDITION (UserStringNop("CONDITION_CONTAINEDBY"))
Referenced by ConditionClassName().
CopyEnumValueRef()
template<typename enumT > std::unique_ptr<ValueRef::ValueRef<enumT> > anonymous_namespace{ObjectListWnd.cpp}::CopyEnumValueRef (const ValueRef::ValueRef< enumT > *const value_ref)
References parse::constant.
CREATEDONTURN_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::CREATEDONTURN_CONDITION (UserStringNop("CONDITION_CREATEDONTURN"))
Referenced by ConditionClassName().
DesignCostValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::DesignCostValueRef ()
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
DesignNameValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::DesignNameValueRef (const char * token)
References ValueRef::NameLookup::SHIP_DESIGN_NAME, and ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
EMPIREAFFILIATION_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::EMPIREAFFILIATION_CONDITION (UserStringNop("CONDITION_EMPIREAFFILIATION"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
EmpireNameValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::EmpireNameValueRef (const char * token)
References ValueRef::NameLookup::EMPIRE_NAME, and ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
EXPLOREDBYEMPIRE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::EXPLOREDBYEMPIRE_CONDITION (UserStringNop("CONDITION_EXPLOREDBYEMPIRE"))
Referenced by ConditionClassName().
FOCUSTYPE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::FOCUSTYPE_CONDITION (UserStringNop("CONDITION_FOCUSTYPE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
GetColumnName()
std::string anonymous_namespace{ObjectListWnd.cpp}::GetColumnName (int column)
unused function.
Kept because it will be useful for making persistent column widths void SetColumnWidth(int column, int width) { if (column < 0) return; std::string option_name = "ui.objects.columns.c" + std::to_string(column) + ".width"; if (GetOptionsDB().OptionExists(option_name)) GetOptionsDB().Set(option_name, width); }
References OptionsDB::Get(), GetOptionsDB(), and to_string().
Referenced by ObjectHeaderPanel::ButtonRightClicked(), ObjectHeaderPanel::GetControls(), and ObjectListBox::SortingClicked().
GetColumnValueRef()
const ValueRef::ValueRef<std::string>* anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef (int column)
References OptionsDB::Get(), GetOptionsDB(), GetValueRefByName(), and to_string().
Referenced by ObjectPanel::SortKey().
GetColumnWidth()
int anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth (int column)
References OptionsDB::Get(), GetOptionsDB(), ClientUI::Pts(), and to_string().
Referenced by ObjectPanel::DoLayout(), ObjectHeaderPanel::DoLayout(), and ObjectPanel::GetControls().
GetValueRefByName()
const ValueRef::ValueRef<std::string>* anonymous_namespace{ObjectListWnd.cpp}::GetValueRefByName (const std::string & name)
References AvailableColumnTypes().
Referenced by GetColumnValueRef().
GGWITHPTYPE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::GGWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_GG"))
Referenced by ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
HASGROWTHSPECIAL_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASGROWTHSPECIAL_CONDITION (UserStringNop("CONDITION_HAS_GROWTH_SPECIAL"))
Referenced by ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
HASSPECIAL_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASSPECIAL_CONDITION (UserStringNop("CONDITION_HASSPECIAL"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
HASTAG_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASTAG_CONDITION (UserStringNop("CONDITION_HASTAG"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
HOMEWORLD_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::HOMEWORLD_CONDITION (UserStringNop("CONDITION_HOMEWORLD"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
INSYSTEM_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::INSYSTEM_CONDITION (UserStringNop("CONDITION_INSYSTEM"))
Referenced by ConditionClassName().
METERVALUE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::METERVALUE_CONDITION (UserStringNop("CONDITION_METERVALUE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
MONSTER_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::MONSTER_CONDITION (UserStringNop("CONDITION_MONSTER"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
NUM_COLUMNS()
const unsigned int anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS (12u)
Referenced by AddOptions(), ObjectPanel::GetControls(), ObjectHeaderPanel::GetControls(), PoliciesListBox::Populate(), PartsListBox::Populate(), PoliciesListBox::SizeMove(), and PartsListBox::SizeMove().
OBJECTID_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::OBJECTID_CONDITION (UserStringNop("CONDITION_OBJECTID"))
Referenced by ConditionClassName().
ObjectNameValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::ObjectNameValueRef (const char * token)
References ValueRef::NameLookup::OBJECT_NAME, and ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
ObjectTextures()
std::vector<std::shared_ptr<GG::Texture> > anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures (std::shared_ptr< const UniverseObject > obj)
References ClientUI::ArtDir(), ClientUI::BuildingIcon(), ClientUI::FieldTexture(), FleetHeadIcons(), FleetSizeIcon(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), ClientUI::GetTexture(), ClientUI::HaloStarTypeFilePrefixes(), INVALID_OBJECT_ID, FleetButton::LARGE, PAD(), ClientUI::PlanetIcon(), ClientUI::ShipDesignIcon(), and ClientUI::StarTypeFilePrefixes().
Referenced by ObjectPanel::Init().
ObjectTypeFilteredRef()
template<typename T > std::unique_ptr<ValueRef::ValueRef<T> > anonymous_namespace{ObjectListWnd.cpp}::ObjectTypeFilteredRef (const std::vector< UniverseObjectType > & object_types, std::unique_ptr< ValueRef::ValueRef< T >> && value_ref)
References ConditionForObjectTypes(), ValueRef::IF, and ValueRef::TIMES.
PAD()
const GG::X anonymous_namespace{ObjectListWnd.cpp}::PAD (3)
Referenced by ObjectListWnd::DoLayout(), ObjectPanel::DoLayout(), ObjectHeaderPanel::DoLayout(), ObjectTextures(), and ConditionWidget::UpdateParameterControls().
PlanetEnvForSpecies()
std::unique_ptr<ValueRef::ValueRef<std::string> > anonymous_namespace{ObjectListWnd.cpp}::PlanetEnvForSpecies (const std::string & species_name)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
PLANETSIZE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::PLANETSIZE_CONDITION (UserStringNop("CONDITION_PLANETSIZE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
PLANETTYPE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::PLANETTYPE_CONDITION (UserStringNop("CONDITION_PLANETTYPE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
PRODUCEDBYEMPIRE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::PRODUCEDBYEMPIRE_CONDITION (UserStringNop("CONDITION_PRODUCEDBYEMPIRE"))
Referenced by ConditionClassName().
SetColumnName()
void anonymous_namespace{ObjectListWnd.cpp}::SetColumnName (int column, const std::string & name)
References GetOptionsDB(), OptionsDB::Set(), and to_string().
Referenced by ObjectHeaderPanel::ButtonRightClicked().
SPECIES_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::SPECIES_CONDITION (UserStringNop("CONDITION_SPECIES"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), and ConditionWidget::UpdateParameterControls().
STARTYPE_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::STARTYPE_CONDITION (UserStringNop("CONDITION_STARTYPE"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
STATIONARY_CONDITION()
const std::string anonymous_namespace{ObjectListWnd.cpp}::STATIONARY_CONDITION (UserStringNop("CONDITION_STATIONARY"))
Referenced by ConditionClassName(), ConditionWidget::GetCondition(), ConditionWidget::Init(), and ConditionWidget::UpdateParameterControls().
StringCastedComplexValueRef()
template<typename T > std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::StringCastedComplexValueRef (const char * token, std::unique_ptr< ValueRef::ValueRef< int >> && int_ref1 = nullptr, std::unique_ptr< ValueRef::ValueRef< int >> && int_ref2 = nullptr, std::unique_ptr< ValueRef::ValueRef< int >> && int_ref3 = nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> && string_ref1 = nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> && string_ref2 = nullptr)
StringCastedImmediateValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::StringCastedImmediateValueRef (std::string token)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
StringCastedValueRef()
template<typename T > std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::StringCastedValueRef (const char * token)
References ValueRef::SOURCE_REFERENCE.
StringsFromEnums()
template<typename enumT > std::vector<std::string> anonymous_namespace{ObjectListWnd.cpp}::StringsFromEnums (const std::vector< enumT > & enum_vals)
References CONDITION_WIDGET_WIDTH().
Referenced by ConditionWidget::UpdateParameterControls().
StringValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::StringValueRef (const char * token)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
SystemSupplyDistanceValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::SystemSupplyDistanceValueRef ()
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
SystemSupplyRangeValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::SystemSupplyRangeValueRef (bool propagated = false)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
UserStringCastedValueRef()
template<typename T > std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::UserStringCastedValueRef (const char * token)
References ValueRef::SOURCE_REFERENCE.
UserStringValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::UserStringValueRef (const char * token)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
UserStringVecValueRef()
std::unique_ptr<ValueRef::Variable<std::string> > anonymous_namespace{ObjectListWnd.cpp}::UserStringVecValueRef (const char * token)
References ValueRef::SOURCE_REFERENCE.
Referenced by AvailableColumnTypes().
Variable Documentation
DATA_PANEL_BORDER
const int anonymous_namespace{ObjectListWnd.cpp}::DATA_PANEL_BORDER = 1
EMPTY_STRING
const std::string anonymous_namespace{ObjectListWnd.cpp}::EMPTY_STRING
Referenced by ConditionWidget::GetString(), and ConditionWidget::StringRow::StringRow().
FILTER_OPTIONS_WND_NAME
const std::string anonymous_namespace{ObjectListWnd.cpp}::FILTER_OPTIONS_WND_NAME = "object-list-filter"
object_list_cond_description_map
std::map<std::string, std::string> anonymous_namespace{ObjectListWnd.cpp}::object_list_cond_description_map
Referenced by ConditionWidget::GetCondition().
temp_bool
bool anonymous_namespace{ObjectListWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)