FreeOrion: Condition::anonymous_namespace{Condition.cpp} Namespace Reference
Condition::anonymous_namespace{Condition.cpp} Namespace Reference
Classes
struct BuildingSimpleMatch
struct CanAddStarlaneConnectionSimpleMatch
struct ChanceSimpleMatch
struct ContainedBySimpleMatch
struct ContainsSimpleMatch
struct CreatedOnTurnSimpleMatch
struct DesignHasHullSimpleMatch
struct DesignHasPartClassSimpleMatch
struct DesignHasPartSimpleMatch
struct EmpireAffiliationSimpleMatch
struct EmpireMeterValueSimpleMatch
struct EmpireStockpileValueSimpleMatch
struct EnqueuedSimpleMatch
struct ExploredByEmpireSimpleMatch
struct FleetSupplyableSimpleMatch
struct FocusTypeSimpleMatch
struct HasSpecialSimpleMatch
struct HasTagSimpleMatch
struct HomeworldSimpleMatch
struct InSystemSimpleMatch
struct MeterValueSimpleMatch
struct NumberedShipDesignSimpleMatch
struct ObjectIDSimpleMatch
struct OrderedBombardedSimpleMatch
struct OwnerHasBuildingTypeAvailableSimpleMatch
struct OwnerHasShipDesignAvailableSimpleMatch
struct OwnerHasShipPartAvailableSimpleMatch
struct OwnerHasTechSimpleMatch
struct PlanetEnvironmentSimpleMatch
struct PlanetSizeSimpleMatch
struct PlanetTypeSimpleMatch
struct PredefinedShipDesignSimpleMatch
struct ProducedByEmpireSimpleMatch
struct ResourceSupplySimpleMatch
struct ShipPartMeterValueSimpleMatch
struct SpeciesSimpleMatch
struct StarTypeSimpleMatch
struct TypeSimpleMatch
struct VisibleToEmpireSimpleMatch
struct WithinDistanceSimpleMatch
Functions
std::string CompareTypeString (ComparisonType comp)
bool Comparison (float val1, ComparisonType comp, float val2)
bool Comparison (const std::string &val1, ComparisonType comp, const std::string &val2)
float CrossProduct (float dx1, float dy1, float dx2, float dy2)
int CustomRandInt (int max_plus_one)
Random number genrator function to use with random_shuffle.
const ConditionBase * GetLocationCondition (ContentType content_type, const std::string &name1, const std::string &name2)
bool LaneCrossesExistingLane (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
bool LanesAngularlyTooClose (std::shared_ptr< const UniverseObject > sys1, std::shared_ptr< const UniverseObject > lane1_sys2, std::shared_ptr< const UniverseObject > lane2_sys2)
bool LanesCross (std::shared_ptr< const System > lane1_end_sys1, std::shared_ptr< const System > lane1_end_sys2, std::shared_ptr< const System > lane2_end_sys1, std::shared_ptr< const System > lane2_end_sys2)
bool LaneTooCloseToOtherSystem (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
std::string MeterTypeDumpString (MeterType meter)
int NumberOnQueue (const ProductionQueue &queue, BuildType build_type, const int location_id, const std::string &name="", int design_id=INVALID_DESIGN_ID)
bool ObjectTooCloseToLane (std::shared_ptr< const UniverseObject > lane_end_sys1, std::shared_ptr< const UniverseObject > lane_end_sys2, std::shared_ptr< const UniverseObject > obj)
void TransferRandomObjects (unsigned int number, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
void TransferSortedObjects (unsigned int number, ValueRef::ValueRefBase< double > *sort_key, const ScriptingContext &context, SortingMethod sorting_method, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
Variables
int(* CRI)(int) = CustomRandInt
Function Documentation
std::string Condition::anonymous_namespace{Condition.cpp}::CompareTypeString (ComparisonType comp)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
Referenced by Condition::ValueTest::Description(), and Condition::ValueTest::Dump().
bool Condition::anonymous_namespace{Condition.cpp}::Comparison (float val1, ComparisonType comp, float val2)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
bool Condition::anonymous_namespace{Condition.cpp}::Comparison (const std::string & val1, ComparisonType comp, const std::string & val2)
References Condition::EQUAL, Condition::INVALID_COMPARISON, and Condition::NOT_EQUAL.
Referenced by Condition::ValueTest::Eval(), and Condition::ValueTest::Match().
float Condition::anonymous_namespace{Condition.cpp}::CrossProduct (float dx1, float dy1, float dx2, float dy2) inline
Referenced by LanesCross().
int Condition::anonymous_namespace{Condition.cpp}::CustomRandInt (int max_plus_one)
Random number genrator function to use with random_shuffle.
References RandSmallInt().
const ConditionBase* Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition (ContentType content_type, const std::string & name1, const std::string & name2)
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, GetBuildingType(), GetHullType(), GetPartType(), GetSpecial(), and GetSpecies().
Referenced by Condition::Location::Eval(), and Condition::Location::Match().
bool Condition::anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
References ObjectMap::FindObjects(), GetSystem(), LanesCross(), and Objects().
Referenced by Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
bool Condition::anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose (std::shared_ptr< const UniverseObject > sys1, std::shared_ptr< const UniverseObject > lane1_sys2, std::shared_ptr< const UniverseObject > lane2_sys2)
Referenced by Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
bool Condition::anonymous_namespace{Condition.cpp}::LanesCross (std::shared_ptr< const System > lane1_end_sys1, std::shared_ptr< const System > lane1_end_sys2, std::shared_ptr< const System > lane2_end_sys1, std::shared_ptr< const System > lane2_end_sys2)
References CrossProduct().
Referenced by LaneCrossesExistingLane().
bool Condition::anonymous_namespace{Condition.cpp}::LaneTooCloseToOtherSystem (std::shared_ptr< const System > lane_end_sys1, std::shared_ptr< const System > lane_end_sys2)
References ObjectMap::FindObjects(), Objects(), and ObjectTooCloseToLane().
Referenced by Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
std::string Condition::anonymous_namespace{Condition.cpp}::MeterTypeDumpString (MeterType meter)
References INVALID_METER_TYPE, METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_RESEARCH, METER_SHIELD, METER_SPEED, METER_STEALTH, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
Referenced by Condition::MeterValue::Dump(), and Condition::ShipPartMeterValue::Dump().
int Condition::anonymous_namespace{Condition.cpp}::NumberOnQueue (const ProductionQueue & queue, BuildType build_type, const int location_id, const std::string & name = "", int design_id = INVALID_DESIGN_ID)
References BT_BUILDING, BT_SHIP, anonymous_namespace{XMLDoc.cpp}::element, GetShipDesign(), INVALID_BUILD_TYPE, INVALID_DESIGN_ID, and ShipDesign::Name().
Referenced by Condition::anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator()().
bool Condition::anonymous_namespace{Condition.cpp}::ObjectTooCloseToLane (std::shared_ptr< const UniverseObject > lane_end_sys1, std::shared_ptr< const UniverseObject > lane_end_sys2, std::shared_ptr< const UniverseObject > obj)
Referenced by LaneTooCloseToOtherSystem().
void Condition::anonymous_namespace{Condition.cpp}::TransferRandomObjects (unsigned int number, ObjectSet & from_set, ObjectSet & to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
References CRI.
Referenced by TransferSortedObjects().
void Condition::anonymous_namespace{Condition.cpp}::TransferSortedObjects (unsigned int number, ValueRef::ValueRefBase< double > * sort_key, const ScriptingContext & context, SortingMethod sorting_method, ObjectSet & from_set, ObjectSet & to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
The objects transferred are selected based on the value of sort_key evaluated on them, with the largest / smallest / most common sort keys chosen, or a random selection chosen, depending on the specified sorting_method
References ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, Condition::SORT_RANDOM, and TransferRandomObjects().
Referenced by Condition::SortedNumberOf::Eval().
Variable Documentation
int(* Condition::anonymous_namespace{Condition.cpp}::CRI) (int) = CustomRandInt
Referenced by TransferRandomObjects().