FreeOrion: anonymous_namespace{OptionsDB.cpp} Namespace Reference
anonymous_namespace{OptionsDB.cpp} Namespace Reference
Functions
bool OptionNameHasParentSection (const std::string &lhs, const std::string &rhs)
std::vector< OptionsDBFn > & OptionsRegistry ()
std::string PreviousSectionName (const std::vector< XMLElement *> &elem_stack)
std::string SplitText (const std::string &text, std::pair< std::size_t, std::size_t > indents={ 0, 0 }, std::pair< std::size_t, std::size_t > widths={ TERMINAL_LINE_WIDTH, TERMINAL_LINE_WIDTH })
Breaks and indents text over multiple lines when it exceeds width limits.
void StripQuotation (std::string &str)
the master list of abbreviated option names, and their corresponding long-form names
Variables
const auto lexical_true_str = boost::lexical_cast<std::string>(true)
OptionsDB options_db
std::map< char, std::string > short_names
constexpr std::size_t TERMINAL_LINE_WIDTH = 80
Function Documentation
OptionNameHasParentSection()
bool anonymous_namespace{OptionsDB.cpp}::OptionNameHasParentSection (const std::string & lhs, const std::string & rhs)
Referenced by OptionsDB::GetUsage().
OptionsRegistry()
std::vector<OptionsDBFn>& anonymous_namespace{OptionsDB.cpp}::OptionsRegistry ()
Referenced by GetOptionsDB(), and RegisterOptions().
PreviousSectionName()
std::string anonymous_namespace{OptionsDB.cpp}::PreviousSectionName (const std::vector< XMLElement *> & elem_stack)
Referenced by OptionsDB::GetXML().
SplitText()
std::string anonymous_namespace{OptionsDB.cpp}::SplitText (const std::string & text, std::pair< std::size_t, std::size_t > indents = { 0, 0 }, std::pair< std::size_t, std::size_t > widths = { TERMINAL_LINE_WIDTH, TERMINAL_LINE_WIDTH })
Breaks and indents text over multiple lines when it exceeds width limits.
Parameters
text String to format, tokenized by spaces, tabs, and newlines (newlines retained but potentially indented)
indents amount of space prior to text. First for initial line, second for any new lines.
widths width to limit the text to. First for initial line, second for any new lines.
Returns
string Formatted results of text
References TERMINAL_LINE_WIDTH.
Referenced by OptionsDB::GetUsage().
StripQuotation()
void anonymous_namespace{OptionsDB.cpp}::StripQuotation (std::string & str)
the master list of abbreviated option names, and their corresponding long-form names
Referenced by OptionsDB::SetFromCommandLine().
Variable Documentation
lexical_true_str
const auto anonymous_namespace{OptionsDB.cpp}::lexical_true_str = boost::lexical_cast<std::string>(true)
Referenced by OptionsDB::SetFromXMLRecursive().
options_db
OptionsDB anonymous_namespace{OptionsDB.cpp}::options_db
Referenced by GetOptionsDB().
short_names
std::map<char, std::string> anonymous_namespace{OptionsDB.cpp}::short_names
Referenced by OptionsDB::Option::Option(), OptionsDB::Remove(), and OptionsDB::SetFromCommandLine().
TERMINAL_LINE_WIDTH
constexpr std::size_t anonymous_namespace{OptionsDB.cpp}::TERMINAL_LINE_WIDTH = 80
Referenced by SplitText().