FreeOrion: anonymous_namespace{ValueRefs.cpp} Namespace Reference
anonymous_namespace{ValueRefs.cpp} Namespace Reference
Classes
struct ObjectTypeVisitor
Functions
std::shared_ptr< const UniverseObject > FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
const std::map< std::string, MeterType > & GetMeterNameMap ()
std::string TraceReference (const std::vector< std::string > &property_name, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
Variables
std::map< std::string, MeterType > dummy = GetMeterNameMap()
const std::string EMPTY_STRING
Function Documentation
FollowReference()
std::shared_ptr<const UniverseObject> anonymous_namespace{ValueRefs.cpp}::FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext & context)
References ScriptingContext::condition_local_candidate, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ScriptingContext::condition_root_candidate, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, ScriptingContext::ContextObjects(), ScriptingContext::effect_target, ValueRef::EFFECT_TARGET_REFERENCE, ErrorLogger, ObjectMap::get(), ValueRef::NON_OBJECT_REFERENCE, ScriptingContext::source, and ValueRef::SOURCE_REFERENCE.
Referenced by ValueRef::Variable< ToType >::Eval().
GetMeterNameMap()
const std::map<std::string, MeterType>& anonymous_namespace{ValueRefs.cpp}::GetMeterNameMap ()
Referenced by ValueRef::MeterToName(), and ValueRef::NameToMeter().
TraceReference()
std::string anonymous_namespace{ValueRefs.cpp}::TraceReference (const std::vector< std::string > & property_name, ValueRef::ReferenceType ref_type, const ScriptingContext & context)
References ScriptingContext::condition_local_candidate, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ScriptingContext::condition_root_candidate, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, ScriptingContext::ContextObjects(), ScriptingContext::effect_target, ValueRef::EFFECT_TARGET_REFERENCE, ObjectMap::get(), ValueRef::NON_OBJECT_REFERENCE, ValueRef::ReconstructName(), ScriptingContext::source, ValueRef::SOURCE_REFERENCE, to_string(), and UserString().
Referenced by ValueRef::Variable< ToType >::Eval().
Variable Documentation
dummy
std::map<std::string, MeterType> anonymous_namespace{ValueRefs.cpp}::dummy = GetMeterNameMap()
EMPTY_STRING
const std::string anonymous_namespace{ValueRefs.cpp}::EMPTY_STRING
Referenced by ValueRef::MeterToName().