FreeOrion: anonymous_namespace{OptionsWnd.cpp} Namespace Reference
anonymous_namespace{OptionsWnd.cpp} Namespace Reference
Classes
struct BrowseForPathButtonFunctor
class FontTextureWnd
class KeyPressCatcher
class OptionsList
class OptionsListRow
class RowContentsWnd
Functions
void HandleResetHotkeyOption (const std::string &hk_name, GG::Button *button)
void HandleSetHotkeyOption (const std::string &hk_name, GG::Button *button)
std::map< std::string, std::vector< std::string > > HotkeysBySection ()
void LoggerLevelOption (GG::ListBox &page, bool is_sink, std::string label, const std::string &option_name)
Create UI controls for a logger level option.
void ShowFontTextureWnd ()
bool ValidDirectory (const std::string &file)
bool ValidExecutableBinary (const std::string &file)
bool ValidFontFile (const std::string &file)
bool ValidMusicFile (const std::string &file)
std::string ValidSectionForHotkey (const std::string &hotkey_name)
bool ValidSoundFile (const std::string &file)
bool ValidStringtableFile (const std::string &file)
Variables
constexpr GG::X COLOR_SELECTOR_WIDTH {75}
const std::string EXE_FILE_SUFFIX = ".exe"
const std::string FONT_FILE_SUFFIX = ".ttf"
constexpr GG::X INDENTATION {20}
constexpr int LAYOUT_MARGIN = 5
const std::string MUSIC_FILE_SUFFIX = ".ogg"
const std::string OPTIONS_WND_NAME = "options"
constexpr GG::Y PAGE_HEIGHT {520}
constexpr GG::X PAGE_WIDTH {400}
constexpr GG::X ROW_WIDTH {Value(PAGE_WIDTH) - 4 - 14 - 5}
const std::string SOUND_FILE_SUFFIX = ".ogg"
constexpr GG::X SPIN_WIDTH {92}
const std::string STRINGTABLE_FILE_SUFFIX = ".txt"
Function Documentation
HandleResetHotkeyOption()
void anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption (const std::string & hk_name, GG::Button * button)
References Hotkey::ClearHotkey(), HotkeyManager::GetManager(), Hotkey::IsDefault(), Hotkey::NamedHotkey(), HotkeyManager::RebuildShortcuts(), and Hotkey::ResetHotkey().
Referenced by OptionsWnd::HotkeyOption().
HandleSetHotkeyOption()
void anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption (const std::string & hk_name, GG::Button * button)
References HotkeyManager::GetManager(), Hotkey::m_key, Hotkey::m_mod_keys, Hotkey::NamedHotkey(), HotkeyManager::RebuildShortcuts(), and Hotkey::SetHotkey().
Referenced by OptionsWnd::HotkeyOption().
HotkeysBySection()
std::map<std::string, std::vector<std::string> > anonymous_namespace{OptionsWnd.cpp}::HotkeysBySection ()
References Hotkey::DefinedHotkeys(), and ValidSectionForHotkey().
Referenced by OptionsWnd::HotkeysPage().
LoggerLevelOption()
void anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption (GG::ListBox & page, bool is_sink, std::string label, const std::string & option_name)
Create UI controls for a logger level option.
References GGHumanClientApp::ChangeLoggerThreshold(), GGHumanClientApp::GetApp(), GetOptionsDB(), LAYOUT_MARGIN, max, min, ClientUI::Pts(), ROW_WIDTH, to_LogLevel(), to_string(), and UserString().
Referenced by OptionsWnd::CompleteConstruction().
ShowFontTextureWnd()
void anonymous_namespace{OptionsWnd.cpp}::ShowFontTextureWnd ()
Referenced by OptionsWnd::CompleteConstruction().
ValidDirectory()
bool anonymous_namespace{OptionsWnd.cpp}::ValidDirectory (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::DirectoryOption().
ValidExecutableBinary()
bool anonymous_namespace{OptionsWnd.cpp}::ValidExecutableBinary (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::CompleteConstruction().
ValidFontFile()
bool anonymous_namespace{OptionsWnd.cpp}::ValidFontFile (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::FontOption().
ValidMusicFile()
bool anonymous_namespace{OptionsWnd.cpp}::ValidMusicFile (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::CompleteConstruction().
ValidSectionForHotkey()
std::string anonymous_namespace{OptionsWnd.cpp}::ValidSectionForHotkey (const std::string & hotkey_name)
References UserStringExists().
Referenced by HotkeysBySection().
ValidSoundFile()
bool anonymous_namespace{OptionsWnd.cpp}::ValidSoundFile (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::SoundFileOption().
ValidStringtableFile()
bool anonymous_namespace{OptionsWnd.cpp}::ValidStringtableFile (const std::string & file)
References FilenameToPath().
Referenced by OptionsWnd::CompleteConstruction().
Variable Documentation
COLOR_SELECTOR_WIDTH
constexpr GG::X anonymous_namespace{OptionsWnd.cpp}::COLOR_SELECTOR_WIDTH {75}
Referenced by OptionsWnd::ColorOption().
EXE_FILE_SUFFIX
const std::string anonymous_namespace{OptionsWnd.cpp}::EXE_FILE_SUFFIX = ".exe"
Referenced by OptionsWnd::CompleteConstruction().
FONT_FILE_SUFFIX
const std::string anonymous_namespace{OptionsWnd.cpp}::FONT_FILE_SUFFIX = ".ttf"
Referenced by OptionsWnd::FontOption().
INDENTATION
constexpr GG::X anonymous_namespace{OptionsWnd.cpp}::INDENTATION {20}
Referenced by anonymous_namespace{OptionsWnd.cpp}::RowContentsWnd::CompleteConstruction().
LAYOUT_MARGIN
constexpr int anonymous_namespace{OptionsWnd.cpp}::LAYOUT_MARGIN = 5
Referenced by OptionsWnd::BoolOption(), OptionsWnd::CompleteConstruction(), OptionsWnd::CreateSectionHeader(), OptionsWnd::DoLayout(), LoggerLevelOption(), and OptionsWnd::ResolutionOption().
MUSIC_FILE_SUFFIX
const std::string anonymous_namespace{OptionsWnd.cpp}::MUSIC_FILE_SUFFIX = ".ogg"
Referenced by OptionsWnd::CompleteConstruction().
OPTIONS_WND_NAME
const std::string anonymous_namespace{OptionsWnd.cpp}::OPTIONS_WND_NAME = "options"
PAGE_HEIGHT
constexpr GG::Y anonymous_namespace{OptionsWnd.cpp}::PAGE_HEIGHT {520}
Referenced by OptionsWnd::CalculatePosition(), and OptionsWnd::CompleteConstruction().
PAGE_WIDTH
constexpr GG::X anonymous_namespace{OptionsWnd.cpp}::PAGE_WIDTH {400}
Referenced by OptionsWnd::CalculatePosition(), and OptionsWnd::CompleteConstruction().
ROW_WIDTH
constexpr GG::X anonymous_namespace{OptionsWnd.cpp}::ROW_WIDTH {Value(PAGE_WIDTH) - 4 - 14 - 5}
Referenced by OptionsWnd::BoolOption(), OptionsWnd::ColorOption(), OptionsWnd::CompleteConstruction(), OptionsWnd::CreateSectionHeader(), OptionsWnd::DoubleOption(), OptionsWnd::FileOptionImpl(), OptionsWnd::HotkeyOption(), ShipFightersBrowseWnd::Initialize(), OptionsWnd::IntOption(), LoggerLevelOption(), OptionsWnd::MusicVolumeOption(), OptionsWnd::PathDisplay(), OptionsWnd::ResolutionOption(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), and OptionsWnd::VolumeOption().
SOUND_FILE_SUFFIX
const std::string anonymous_namespace{OptionsWnd.cpp}::SOUND_FILE_SUFFIX = ".ogg"
Referenced by OptionsWnd::SoundFileOption().
SPIN_WIDTH
constexpr GG::X anonymous_namespace{OptionsWnd.cpp}::SPIN_WIDTH {92}
Referenced by OptionsWnd::DoubleOption(), OptionsWnd::FileOptionImpl(), OptionsWnd::IntOption(), and OptionsWnd::PathDisplay().
STRINGTABLE_FILE_SUFFIX
const std::string anonymous_namespace{OptionsWnd.cpp}::STRINGTABLE_FILE_SUFFIX = ".txt"
Referenced by OptionsWnd::CompleteConstruction().