FreeOrion: FreeOrionPython Namespace Reference
FreeOrionPython Namespace Reference
Classes
class SetWrapper
Functions
void ClearStaticSaveStateString ()
const std::string & GetStaticSaveStateString ()
void SetStaticSaveStateString (const std::string &new_state_string)
void WrapAI ()
Expose AIInterface to Python.
void WrapConfig ()
void WrapEmpire ()
CallPolicies:
void WrapGalaxySetupData ()
void WrapGameStateEnums ()
void WrapLogger ()
void WrapServer ()
void WrapUniverseClasses ()
CallPolicies:
Function Documentation
ClearStaticSaveStateString()
void FreeOrionPython::ClearStaticSaveStateString ()
References anonymous_namespace{AIWrapper.cpp}::s_save_state_string().
Referenced by PythonAI::StartNewGame().
GetStaticSaveStateString()
const std::string & FreeOrionPython::GetStaticSaveStateString ()
References anonymous_namespace{AIWrapper.cpp}::s_save_state_string().
Referenced by PythonAI::GetSaveStateString(), PythonAI::ResumeLoadedGame(), and WrapAI().
SetStaticSaveStateString()
void FreeOrionPython::SetStaticSaveStateString (const std::string & new_state_string)
References anonymous_namespace{AIWrapper.cpp}::s_save_state_string().
Referenced by PythonAI::ResumeLoadedGame(), and WrapAI().
WrapAI()
void FreeOrionPython::WrapAI ()
Expose AIInterface to Python.
CallPolicies:
return_value_policy<copy_const_reference> when returning a relatively small object, such as a string, that is returned by const reference or pointer
return_value_policy<return_by_value> when returning either a simple data type or a temporary object in a function that will go out of scope after being returned
return_value_policy<reference_existing_object> when returning an object from a non-member function
References AIIntGetEmpireInt, AIIntGetEmpireVoid, AIIntPlayerNameInt, AIIntPlayerNameVoid, AIInterface::AllEmpireIDs(), AIInterface::AllPlayerIDs(), anonymous_namespace{AIWrapper.cpp}::AppendFleetMoveOrder(), CurrentTurn(), Order::EmpireID(), AIInterface::EmpireID(), AIInterface::EmpirePlayerID(), Order::Executed(), anonymous_namespace{AIWrapper.cpp}::GetAIDir(), AIInterface::GetGalaxySetupData(), GetStaticSaveStateString(), GetUniverse(), anonymous_namespace{AIWrapper.cpp}::GetUserStringList(), AIInterface::InitMeterEstimatesAndDiscrepancies(), INVALID_GAME_TURN, anonymous_namespace{AIWrapper.cpp}::IssueAggressionOrder(), AIInterface::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueBombardOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeFocusOrder(), AIInterface::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueColonizeOrder(), anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrderWrapper(), AIInterface::IssueDequeueProductionOrder(), AIInterface::IssueDequeueTechOrder(), AIInterface::IssuedOrders(), AIInterface::IssueEnqueueBuildingProductionOrder(), AIInterface::IssueEnqueueShipProductionOrder(), AIInterface::IssueEnqueueTechOrder(), anonymous_namespace{AIWrapper.cpp}::IssueFleetMoveOrder(), anonymous_namespace{AIWrapper.cpp}::IssueFleetTransferOrder(), anonymous_namespace{AIWrapper.cpp}::IssueGiveObjectToEmpireOrder(), anonymous_namespace{AIWrapper.cpp}::IssueInvadeOrder(), anonymous_namespace{AIWrapper.cpp}::IssueNewFleetOrder(), AIInterface::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRenameOrder(), AIInterface::IssueRequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueScrapOrder(), AIInterface::PlayerEmpireID(), AIInterface::PlayerID(), AIInterface::PlayerIsAI(), AIInterface::PlayerIsHost(), AIInterface::SendDiplomaticMessage(), AIInterface::SendPlayerChatMessage(), SetStaticSaveStateString(), OrderSet::size(), AIInterface::UpdateMeterEstimates(), AIInterface::UpdateProductionQueue(), AIInterface::UpdateResearchQueue(), AIInterface::UpdateResourcePools(), UserString(), and UserStringExists().
Referenced by BOOST_PYTHON_MODULE().
WrapConfig()
void FreeOrionPython::WrapConfig ()
References anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionBool(), anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionDouble(), anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionInt(), anonymous_namespace{ConfigWrapper.cpp}::GetOptionsDBOptionStr(), anonymous_namespace{ConfigWrapper.cpp}::GetUserConfigDirWrapper(), and anonymous_namespace{ConfigWrapper.cpp}::GetUserDataDirWrapper().
Referenced by BOOST_PYTHON_MODULE().
WrapEmpire()
void FreeOrionPython::WrapEmpire ()
CallPolicies:
return_value_policy<copy_const_reference> when returning a relatively small object, such as a string, that is returned by const reference or pointer
return_value_policy<return_by_value> when returning either a simple data type or a temporary object in a function that will go out of scope after being returned
return_internal_reference<> when returning an object or data that is a member of the object on which the function is called (and shares its lifetime)
return_value_policy<reference_existing_object> when returning an object from a non-member function, or a member function where the returned object's lifetime is not fixed to the lifetime of the object on which the function is called
References ProductionQueue::Element::allocated_pp, ResearchQueue::Element::allocated_rp, ProductionQueue::AllocatedPP(), ProductionQueue::Element::allowed_imperial_stockpile_use, Empire::AvailableBuildingTypes(), ProductionQueue::AvailablePP(), Empire::AvailableShipDesigns(), Empire::AvailableShipHulls(), Empire::AvailableShipParts(), ProductionQueue::Element::blocksize, anonymous_namespace{EmpireWrapper.cpp}::BuildableItemBuilding, anonymous_namespace{EmpireWrapper.cpp}::BuildableItemShip, Empire::BuildingTypeAvailable(), anonymous_namespace{EmpireWrapper.cpp}::BuildTypeFromProductionQueueElement(), Empire::CapitalID(), Tech::Category(), TechManager::CategoryNames(), Empire::Color(), Tech::Description(), anonymous_namespace{EmpireWrapper.cpp}::DesignIDFromProductionQueueElement(), DiplomaticStatusUpdateInfo::diplo_status, Empire::Eliminated(), DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, anonymous_namespace{EmpireWrapper.cpp}::empireFleetSupplyableSystemIDsFunc, anonymous_namespace{EmpireWrapper.cpp}::EmpireGetMeter, Empire::EmpireID(), ResearchQueue::EmpireID(), ProductionQueue::EmpireID(), ResearchQueue::empty(), ProductionQueue::empty(), Empire::ExploredSystems(), SitRepEntry::GetDataIDNumber(), SitRepEntry::GetDataString(), anonymous_namespace{EmpireWrapper.cpp}::GetEmpireSitRepFunc, Empire::GetProductionQueue(), Empire::GetResearchQueue(), Empire::GetResourcePool(), GetTech(), GetTechManager(), Empire::GetTechStatus(), VarText::GetTemplateString(), SitRepEntry::GetTurn(), DiplomaticMessage::GetType(), VarText::GetVariableTags(), Empire::HasExploredSystem(), ResearchQueue::InQueue(), anonymous_namespace{EmpireWrapper.cpp}::InQueueFromResearchQueueElementFunc, anonymous_namespace{EmpireWrapper.cpp}::jumpsToSuppliedSystemFunc, ProductionQueue::Element::location, ResearchQueue::Element::name, Empire::Name(), Tech::Name(), ItemSpec::name, anonymous_namespace{EmpireWrapper.cpp}::NameFromProductionQueueElement(), Empire::NumSitRepEntries(), ProductionQueue::ObjectsWithWastedPP(), anonymous_namespace{EmpireWrapper.cpp}::obstructedStarlanesFunc, ProductionQueue::Element::paused, Tech::PerTurnCost(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_Func, anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_Func, anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_Func, Empire::PlayerName(), Empire::Population(), Tech::Prerequisites(), Empire::PreservedLaneTravel(), anonymous_namespace{EmpireWrapper.cpp}::ProductionCostAndTimeFunc, Empire::ProductionPoints(), anonymous_namespace{EmpireWrapper.cpp}::ProductionQueueOperatorSquareBrackets, ProductionQueue::Element::progress, DiplomaticMessage::RecipientEmpireID(), ProductionQueue::Element::remaining, Tech::ResearchCost(), Empire::ResearchProgress(), anonymous_namespace{EmpireWrapper.cpp}::ResearchTechNamesFunc, Tech::ResearchTime(), Empire::ResourceAvailable(), Empire::ResourceOutput(), Empire::ResourceStockpile(), DiplomaticMessage::SenderEmpireID(), Empire::ShipDesignAvailable(), Empire::ShipDesigns(), Tech::ShortDescription(), ResearchQueue::size(), ProductionQueue::size(), Empire::SupplyUnobstructedSystems(), Empire::SystemSupplyRanges(), anonymous_namespace{EmpireWrapper.cpp}::TechNamesCategoryMemberFunc, anonymous_namespace{EmpireWrapper.cpp}::TechNamesMemberFunc, anonymous_namespace{EmpireWrapper.cpp}::TechRecursivePrereqsFunc, Empire::TechResearched(), ProductionQueue::TotalPPsSpent(), ResearchQueue::TotalRPsSpent(), ResearchQueue::Element::turns_left, ProductionQueue::Element::turns_left_to_completion, ItemSpec::type, Tech::UnlockedItems(), Tech::UnlockedTechs(), Empire::Won(), and FreeOrionPython::SetWrapper< ElementType >::Wrap().
Referenced by BOOST_PYTHON_MODULE().
WrapGalaxySetupData()
void FreeOrionPython::WrapGalaxySetupData ()
References GameRules::Empty(), GalaxySetupData::GetAge(), GalaxySetupData::GetAggression(), GameRules::GetDescription(), GetGameRules(), GalaxySetupData::GetGameUID(), GalaxySetupData::GetMonsterFreq(), GalaxySetupData::GetNativeFreq(), GalaxySetupData::GetPlanetDensity(), GameRules::GetRulesAsStrings(), GalaxySetupData::GetSeed(), GalaxySetupData::GetShape(), GalaxySetupData::GetSize(), GalaxySetupData::GetSpecialsFreq(), GalaxySetupData::GetStarlaneFreq(), anonymous_namespace{UniverseWrapper.cpp}::RuleExistsAnyType(), anonymous_namespace{UniverseWrapper.cpp}::RuleExistsWithType(), and GalaxySetupData::SetGameUID().
Referenced by BOOST_PYTHON_MODULE().
WrapGameStateEnums()
void FreeOrionPython::WrapGameStateEnums ()
References DiplomaticMessage::ACCEPT_ALLIES_PROPOSAL, DiplomaticMessage::ACCEPT_PEACE_PROPOSAL, AGGRESSIVE, DiplomaticMessage::ALLIES_PROPOSAL, BEGINNER, BT_BUILDING, BT_SHIP, BT_STOCKPILE, DiplomaticMessage::CANCEL_PROPOSAL, CAUTIOUS, CR_CAPTURE, CR_DESTROY, GameRules::DOUBLE, DiplomaticMessage::END_ALLIANCE_DECLARATION, GameRules::INT, GameRules::INVALID, INVALID_AGGRESSION, DiplomaticMessage::INVALID_DIPLOMATIC_MESSAGE_TYPE, INVALID_PLANET_SIZE, INVALID_STAR_TYPE, INVALID_UNLOCKABLE_ITEM_TYPE, MANIACAL, METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STEALTH, METER_STOCKPILE, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, METER_TROOPS, PC_ARMOUR, PC_BOMBARD, PC_COLONY, PC_DETECTION, PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, PC_FUEL, PC_GENERAL, PC_INDUSTRY, PC_PRODUCTION_LOCATION, PC_RESEARCH, PC_SHIELD, PC_SPEED, PC_STEALTH, PC_TRADE, PC_TROOPS, DiplomaticMessage::PEACE_PROPOSAL, DiplomaticMessage::REJECT_PROPOSAL, Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, Networking::ROLE_GALAXY_SETUP, Networking::ROLE_HOST, STAR_BLACK, STAR_BLUE, STAR_NEUTRON, STAR_NONE, STAR_ORANGE, STAR_RED, STAR_WHITE, STAR_YELLOW, GameRules::STRING, SZ_ASTEROIDS, SZ_GASGIANT, SZ_HUGE, SZ_LARGE, SZ_MEDIUM, SZ_NOWORLD, SZ_SMALL, SZ_TINY, GameRules::TOGGLE, TURTLE, TYPICAL, UIT_BUILDING, UIT_SHIP_DESIGN, UIT_SHIP_HULL, UIT_SHIP_PART, UIT_TECH, and DiplomaticMessage::WAR_DECLARATION.
Referenced by BOOST_PYTHON_MODULE().
WrapLogger()
void FreeOrionPython::WrapLogger ()
References anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerDebug(), anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerError(), anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerInfo(), and anonymous_namespace{LoggingWrapper.cpp}::PythonLoggerWarn().
Referenced by BOOST_PYTHON_MODULE().
WrapServer()
void FreeOrionPython::WrapServer ()
References anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), anonymous_namespace{ServerWrapper.cpp}::AllEmpires(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateField(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateMonster(), anonymous_namespace{ServerWrapper.cpp}::CreateMonsterFleet(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{ServerWrapper.cpp}::CreateSystem(), CurrentTurn(), anonymous_namespace{ServerWrapper.cpp}::EmpireAddShipDesign(), anonymous_namespace{ServerWrapper.cpp}::EmpireSetHomeworld(), anonymous_namespace{ServerWrapper.cpp}::EmpireSetName(), anonymous_namespace{ServerWrapper.cpp}::EmpireUnlockItem(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep(), anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep1(), GenerateStarlanes(), anonymous_namespace{ServerWrapper.cpp}::GetAllEmpires(), anonymous_namespace{ServerWrapper.cpp}::GetAllObjects(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecials(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecies(), GetEmpire(), GetGalaxySetupData(), anonymous_namespace{ServerWrapper.cpp}::GetName(), anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies(), anonymous_namespace{ServerWrapper.cpp}::GetOwner(), anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{ServerWrapper.cpp}::GetResourceDirWrapper(), anonymous_namespace{ServerWrapper.cpp}::GetSystems(), GetUniverse(), anonymous_namespace{ServerWrapper.cpp}::GetUniverseWidth(), anonymous_namespace{ServerWrapper.cpp}::GetX(), anonymous_namespace{ServerWrapper.cpp}::GetY(), anonymous_namespace{ServerWrapper.cpp}::InvalidObjectID(), anonymous_namespace{ServerWrapper.cpp}::InvalidPosition(), anonymous_namespace{ServerWrapper.cpp}::JumpDistanceBetweenSystems(), anonymous_namespace{ServerWrapper.cpp}::LargeMeterValue(), anonymous_namespace{ServerWrapper.cpp}::LinearDistance(), anonymous_namespace{ServerWrapper.cpp}::LoadFleetPlanList(), anonymous_namespace{ServerWrapper.cpp}::LoadItemSpecList(), anonymous_namespace{ServerWrapper.cpp}::LoadMonsterFleetPlanList(), anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings(), PlayerSetupData::m_empire_color, PlayerSetupData::m_empire_name, PlayerSetupData::m_player_name, PlayerSetupData::m_starting_species_name, PlayerSetupData::m_starting_team, anonymous_namespace{XMLDoc.cpp}::Name, anonymous_namespace{ServerWrapper.cpp}::ObjectsGetSystems(), anonymous_namespace{ServerWrapper.cpp}::PlanetAvailableFoci(), anonymous_namespace{ServerWrapper.cpp}::PlanetCardinalSuffix(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetType(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeOutpost(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetFocus(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSize(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSpecies(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetType(), anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), RomanNumber(), anonymous_namespace{ServerWrapper.cpp}::SetName(), anonymous_namespace{ServerWrapper.cpp}::SetUniverseWidth(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetMonsterList(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetPremadeList(), anonymous_namespace{ServerWrapper.cpp}::SpecialHasLocation(), anonymous_namespace{ServerWrapper.cpp}::SpecialLocations(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnLimit(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnRate(), anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld(), anonymous_namespace{ServerWrapper.cpp}::SpeciesCanColonize(), anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment(), anonymous_namespace{ServerWrapper.cpp}::SpeciesPreferredFocus(), anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld(), anonymous_namespace{ServerWrapper.cpp}::SystemAddStarlane(), anonymous_namespace{ServerWrapper.cpp}::SystemFreeOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetFleets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetNumOrbits(), anonymous_namespace{ServerWrapper.cpp}::SystemGetPlanets(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarlanes(), anonymous_namespace{ServerWrapper.cpp}::SystemGetStarType(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOccupied(), anonymous_namespace{ServerWrapper.cpp}::SystemOrbitOfPlanet(), anonymous_namespace{ServerWrapper.cpp}::SystemRemoveStarlane(), anonymous_namespace{ServerWrapper.cpp}::SystemSetStarType(), anonymous_namespace{ServerWrapper.cpp}::SystemsWithinJumps(), and UserString().
Referenced by BOOST_PYTHON_MODULE().
WrapUniverseClasses()
void FreeOrionPython::WrapUniverseClasses ()
CallPolicies:
return_value_policy<copy_const_reference> when returning a relatively small object, such as a string, that is returned by const reference or pointer
return_value_policy<return_by_value> when returning either a simple data type or a temporary object in a function that will go out of scope after being returned
return_internal_reference<> when returning an object or data that is a member of the object on which the function is called (and shares its lifetime)
return_value_policy<reference_existing_object> when returning an object from a non-member function, or a member function where the returned object's lifetime is not fixed to the lifetime of the object on which the function is called
References UniverseObject::AgeInTurns(), Fleet::Aggressive(), Ship::ArrivedOnTurn(), ShipDesign::Attack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStatsFunc, ResourceCenter::AvailableFoci(), Planet::BuildingIDs(), System::BuildingIDs(), Building::BuildingTypeName(), Ship::CanBombard(), Fleet::CanChangeDirectionEnRoute(), Ship::CanColonize(), Species::CanColonize(), ShipDesign::CanColonize(), PartType::CanMountInSlotType(), Species::CanProduceShips(), PartType::Capacity(), Effect::EffectCause::cause_type, PartType::Class(), Planet::ClockwiseNextPlanetType(), Ship::ColonyCapacity(), ShipDesign::ColonyCapacity(), UniverseObject::ContainedBy(), UniverseObject::ContainedObjectIDs(), UniverseObject::ContainerObjectID(), UniverseObject::Contains(), Planet::CounterClockwiseNextPlanetType(), UniverseObject::CreationTurn(), Meter::Current(), UniverseObject::CurrentMeterValue(), Ship::CurrentPartMeterValue(), Effect::EffectCause::custom_label, ShipDesign::Defense(), Special::Description(), FieldType::Description(), BuildingType::Description(), Species::Description(), Ship::Design(), ShipDesign::DesignedOnTurn(), Ship::DesignID(), ShipDesign::Detection(), Planet::DistanceFromOriginalType(), Meter::Dump(), Special::Dump(), FieldType::Dump(), BuildingType::Dump(), Species::Dump(), ShipDesign::Dump(), anonymous_namespace{UniverseWrapper.cpp}::DumpObjects(), Universe::EmpireKnownDestroyedObjectIDs(), Fleet::Empty(), anonymous_namespace{UniverseWrapper.cpp}::EnqueueLocationTest(), Planet::EnvironmentForSpecies(), System::FieldIDs(), Field::FieldTypeName(), Fleet::FinalDestinationID(), Ship::FleetID(), System::FleetIDs(), ResourceCenter::Focus(), Fleet::Fuel(), HullType::Fuel(), ShipDesign::Fuel(), anonymous_namespace{UniverseWrapper.cpp}::GetBuildingP(), GetBuildingType(), BuildingType::GetCaptureResult(), Universe::GetEffectAccountingMap(), anonymous_namespace{UniverseWrapper.cpp}::GetFieldP(), GetFieldType(), anonymous_namespace{UniverseWrapper.cpp}::GetFleetP(), Universe::GetGenericShipDesign(), ShipDesign::GetHull(), GetHullType(), Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetPartType(), Species::GetPlanetEnvironment(), anonymous_namespace{UniverseWrapper.cpp}::GetPlanetP(), GetPredefinedShipDesign(), GetShipDesign(), anonymous_namespace{UniverseWrapper.cpp}::GetShipP(), GetSpecial(), GetSpecies(), System::GetStarType(), anonymous_namespace{UniverseWrapper.cpp}::GetSystemP(), anonymous_namespace{UniverseWrapper.cpp}::GetUniverseObjectP(), Planet::HabitableSize(), Fleet::HasArmedShips(), Fleet::HasColonyShips(), ShipDesign::HasDirectWeapons(), Ship::HasFighters(), ShipDesign::HasFighters(), Fleet::HasFighterShips(), Fleet::HasMonsters(), Fleet::HasOutpostShips(), UniverseObject::HasSpecial(), System::HasStarlaneTo(), UniverseObject::HasTag(), HullType::HasTag(), Ship::HasTroops(), ShipDesign::HasTroops(), Fleet::HasTroopShips(), System::HasWormholeTo(), Species::Homeworlds(), ShipDesign::Hull(), anonymous_namespace{UniverseWrapper.cpp}::HullSlotsFunc, UniverseObject::ID(), ShipDesign::ID(), anonymous_namespace{UniverseWrapper.cpp}::ImmediateNeighborsFunc, ShipDesign::IndustryGeneration(), Meter::Initial(), UniverseObject::InitialMeterValue(), Planet::InitialOrbitalPosition(), Ship::InitialPartMeterValue(), Ship::IsArmed(), ShipDesign::IsArmed(), Ship::IsMonster(), ShipDesign::IsMonster(), Ship::LastResuppliedOnTurn(), Ship::LastTurnActiveInCombat(), Planet::LastTurnAttackedByShip(), System::LastTurnBattleHere(), Planet::LastTurnConquered(), anonymous_namespace{UniverseWrapper.cpp}::LeastJumpsFunc, anonymous_namespace{UniverseWrapper.cpp}::LocationInField, Fleet::MaxFuel(), Effect::AccountingInfo::meter_change, PartType::MountableSlotTypes(), Special::Name(), UniverseObject::Name(), FieldType::Name(), BuildingType::Name(), PartType::Name(), Species::Name(), HullType::Name(), Planet::NextBetterPlanetTypeForSpecies(), Planet::NextLargerPlanetSize(), Planet::NextSmallerPlanetSize(), Fleet::NextSystemID(), Fleet::NumShips(), anonymous_namespace{UniverseWrapper.cpp}::NumSlotsOfSlotType, anonymous_namespace{UniverseWrapper.cpp}::NumSlotsTotal, System::NumStarlanes(), System::NumWormholes(), anonymous_namespace{UniverseWrapper.cpp}::ObjectDump(), anonymous_namespace{UniverseWrapper.cpp}::ObjectGetMeter, anonymous_namespace{UniverseWrapper.cpp}::ObjectInField(), anonymous_namespace{UniverseWrapper.cpp}::ObjectMeters, anonymous_namespace{UniverseWrapper.cpp}::ObjectSpecials(), Planet::OrbitalPeriod(), Planet::OrbitalPositionOnTurn(), Ship::OrderedColonizePlanet(), Ship::OrderedInvadePlanet(), Building::OrderedScrapped(), Ship::OrderedScrapped(), Planet::OriginalType(), UniverseObject::OwnedBy(), UniverseObject::Owner(), anonymous_namespace{UniverseWrapper.cpp}::PartsVoid, BuildingType::PerTurnCost(), ShipDesign::PerTurnCost(), Building::PlanetID(), System::PlanetIDs(), Species::PreferredFocus(), Fleet::PreviousSystemID(), Building::ProducedByEmpireID(), Ship::ProducedByEmpireID(), BuildingType::ProductionCost(), PartType::ProductionCost(), HullType::ProductionCost(), ShipDesign::ProductionCost(), BuildingType::ProductionCostTimeLocationInvariant(), PartType::ProductionCostTimeLocationInvariant(), HullType::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionCostTimeLocationInvariant(), BuildingType::ProductionLocation(), ShipDesign::ProductionLocation(), BuildingType::ProductionTime(), PartType::ProductionTime(), HullType::ProductionTime(), ShipDesign::ProductionTime(), ShipDesign::ResearchGeneration(), Planet::RotationalPeriod(), Effect::AccountingInfo::running_meter_total, PartType::SecondaryStat(), ShipDesign::Shields(), anonymous_namespace{UniverseWrapper.cpp}::ShipDesignDescriptionFunc, anonymous_namespace{UniverseWrapper.cpp}::ShipDesignNameFunc, anonymous_namespace{UniverseWrapper.cpp}::ShipGetPartMeter, Fleet::ShipIDs(), System::ShipIDs(), anonymous_namespace{UniverseWrapper.cpp}::ShipPartMeters, anonymous_namespace{UniverseWrapper.cpp}::ShortestNonHostilePathFunc, anonymous_namespace{UniverseWrapper.cpp}::ShortestPathFunc, Planet::Size(), Effect::AccountingInfo::source_id, Special::SpawnLimit(), Special::SpawnRate(), UniverseObject::SpecialAddedOnTurn(), anonymous_namespace{UniverseWrapper.cpp}::SpecialInitialCapacityOnObject, anonymous_namespace{UniverseWrapper.cpp}::SpeciesFoci(), PopCenter::SpeciesName(), Ship::SpeciesName(), Effect::EffectCause::specific_cause, Ship::Speed(), Fleet::Speed(), HullType::Speed(), ShipDesign::Speed(), System::StarlanesWormholes(), HullType::Stealth(), ShipDesign::Stealth(), HullType::Structure(), ShipDesign::Structure(), UniverseObject::SystemID(), anonymous_namespace{UniverseWrapper.cpp}::SystemNeighborsMapFunc, UniverseObject::Tags(), Species::Tags(), ShipDesign::TradeGeneration(), Ship::TroopCapacity(), ShipDesign::TroopCapacity(), ResourceCenter::TurnsSinceFocusChange(), Planet::Type(), UniverseObject::Unowned(), anonymous_namespace{UniverseWrapper.cpp}::UpdateMetersWrapper(), anonymous_namespace{UniverseWrapper.cpp}::ValidDesignHullAndParts, UniverseObject::X(), and UniverseObject::Y().
Referenced by BOOST_PYTHON_MODULE().