FreeOrion: Condition::anonymous_namespace{Conditions.cpp} Namespace Reference
Condition::anonymous_namespace{Conditions.cpp} Namespace Reference
Classes
struct BuildingSimpleMatch
struct CanAddStarlaneConnectionSimpleMatch
struct ChanceSimpleMatch
struct ContainedBySimpleMatch
struct ContainsSimpleMatch
struct CreatedOnTurnSimpleMatch
struct DesignHasHullSimpleMatch
struct DesignHasPartClassSimpleMatch
struct DesignHasPartSimpleMatch
struct EmpireAffiliationSimpleMatch
struct EnqueuedSimpleMatch
struct ExploredByEmpireSimpleMatch
struct FleetSupplyableSimpleMatch
struct FocusTypeSimpleMatch
struct HasSpecialSimpleMatch
struct HasTagSimpleMatch
struct HomeworldSimpleMatch
struct InSystemSimpleMatch
struct MeterValueSimpleMatch
struct NumberedShipDesignSimpleMatch
struct ObjectIDSimpleMatch
struct OnPlanetSimpleMatch
struct OrderedBombardedSimpleMatch
struct OwnerHasBuildingTypeAvailableSimpleMatch
struct OwnerHasShipDesignAvailableSimpleMatch
struct OwnerHasShipPartAvailableSimpleMatch
struct OwnerHasTechSimpleMatch
struct PlanetEnvironmentSimpleMatch
struct PlanetSizeSimpleMatch
struct PlanetTypeSimpleMatch
struct PredefinedShipDesignSimpleMatch
struct ProducedByEmpireSimpleMatch
struct ResourceSupplySimpleMatch
struct ShipPartMeterValueSimpleMatch
struct SpeciesSimpleMatch
struct StarTypeSimpleMatch
struct TypeSimpleMatch
struct VisibleToEmpireSimpleMatch
struct WithinDistanceSimpleMatch
Functions
std::string CompareTypeString (ComparisonType comp)
bool Comparison (float val1, ComparisonType comp, float val2)
bool Comparison (const std::string &val1, ComparisonType comp, const std::string &val2)
float CrossProduct (float dx1, float dy1, float dx2, float dy2)
void FCMoveContent (ObjectSet &from_set, ObjectSet &to_set)
const std::string & GetCandidateFocus (const UniverseObject *candidate, const ObjectMap &objects)
const std::string & GetCandidateSpecies (const UniverseObject *candidate, const ObjectMap &objects)
const Condition * GetCombatTargetCondition (ContentType content_type, const std::string &name)
const std::string & GetContentTypeName (ContentType content_type)
const Condition * GetLocationCondition (ContentType content_type, const std::string &name1, const std::string &name2)
bool LaneCrossesExistingLane (const System *lane_end_sys1, const System *lane_end_sys2, const ObjectMap &objects)
bool LanesAngularlyTooClose (const UniverseObject *sys1, const UniverseObject *lane1_sys2, const UniverseObject *lane2_sys2)
bool LanesCross (const System *lane1_end_sys1, const System *lane1_end_sys2, const System *lane2_end_sys1, const System *lane2_end_sys2)
bool LaneTooCloseToOtherSystem (const System *lane_end_sys1, const System *lane_end_sys2, const ObjectMap &objects)
std::string MeterTypeDumpString (MeterType meter)
int NumberOnQueue (const ProductionQueue &queue, BuildType build_type, const int location_id, const std::string &name="", int design_id=INVALID_DESIGN_ID)
bool ObjectTooCloseToLane (const UniverseObject *lane_end_sys1, const UniverseObject *lane_end_sys2, const UniverseObject *obj)
void TransferRandomObjects (unsigned int number, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
void TransferSortedObjects (unsigned int number, ValueRef::ValueRef< double > *sort_key, const ScriptingContext &context, SortingMethod sorting_method, ObjectSet &from_set, ObjectSet &to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
Function Documentation
CompareTypeString()
std::string Condition::anonymous_namespace{Conditions.cpp}::CompareTypeString (ComparisonType comp)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
Referenced by Condition::ValueTest::Description(), and Condition::ValueTest::Dump().
Comparison() [1/2]
bool Condition::anonymous_namespace{Conditions.cpp}::Comparison (float val1, ComparisonType comp, float val2)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
Comparison() [2/2]
bool Condition::anonymous_namespace{Conditions.cpp}::Comparison (const std::string & val1, ComparisonType comp, const std::string & val2)
References Condition::EQUAL, Condition::INVALID_COMPARISON, and Condition::NOT_EQUAL.
Referenced by Condition::ValueTest::Match().
CrossProduct()
float Condition::anonymous_namespace{Conditions.cpp}::CrossProduct (float dx1, float dy1, float dx2, float dy2) inline
Referenced by LanesCross().
FCMoveContent()
void Condition::anonymous_namespace{Conditions.cpp}::FCMoveContent (ObjectSet & from_set, ObjectSet & to_set)
Referenced by Condition::OrderedAlternativesOf::Eval().
GetCandidateFocus()
const std::string& Condition::anonymous_namespace{Conditions.cpp}::GetCandidateFocus (const UniverseObject * candidate, const ObjectMap & objects)
References anonymous_namespace{Conditions.cpp}::EMPTY_STRING, ResourceCenter::Focus(), ObjectMap::get(), and UniverseObject::ObjectType().
Referenced by Condition::FocusType::Match(), and Condition::anonymous_namespace{Conditions.cpp}::FocusTypeSimpleMatch::operator()().
GetCandidateSpecies()
const std::string& Condition::anonymous_namespace{Conditions.cpp}::GetCandidateSpecies (const UniverseObject * candidate, const ObjectMap & objects)
References anonymous_namespace{Conditions.cpp}::EMPTY_STRING, ObjectMap::get(), UniverseObject::ObjectType(), PopCenter::SpeciesName(), and Ship::SpeciesName().
Referenced by Condition::Species::Match(), and Condition::anonymous_namespace{Conditions.cpp}::SpeciesSimpleMatch::operator()().
GetCombatTargetCondition()
const Condition* Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition (ContentType content_type, const std::string & name)
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, GetShipPart(), and GetSpecies().
Referenced by Condition::CombatTarget::Eval(), and Condition::CombatTarget::Match().
GetContentTypeName()
const std::string& Condition::anonymous_namespace{Conditions.cpp}::GetContentTypeName (ContentType content_type)
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, anonymous_namespace{Conditions.cpp}::EMPTY_STRING, and UserString().
Referenced by Condition::Location::Description(), and Condition::CombatTarget::Description().
GetLocationCondition()
const Condition* Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition (ContentType content_type, const std::string & name1, const std::string & name2)
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, GetBuildingType(), GetShipHull(), GetShipPart(), GetSpecial(), and GetSpecies().
Referenced by Condition::Location::Eval(), and Condition::Location::Match().
LaneCrossesExistingLane()
bool Condition::anonymous_namespace{Conditions.cpp}::LaneCrossesExistingLane (const System * lane_end_sys1, const System * lane_end_sys2, const ObjectMap & objects)
References ObjectMap::all(), ObjectMap::get(), and LanesCross().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
LanesAngularlyTooClose()
bool Condition::anonymous_namespace{Conditions.cpp}::LanesAngularlyTooClose (const UniverseObject * sys1, const UniverseObject * lane1_sys2, const UniverseObject * lane2_sys2)
References UniverseObject::X(), and UniverseObject::Y().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
LanesCross()
bool Condition::anonymous_namespace{Conditions.cpp}::LanesCross (const System * lane1_end_sys1, const System * lane1_end_sys2, const System * lane2_end_sys1, const System * lane2_end_sys2)
References CrossProduct().
Referenced by LaneCrossesExistingLane().
LaneTooCloseToOtherSystem()
bool Condition::anonymous_namespace{Conditions.cpp}::LaneTooCloseToOtherSystem (const System * lane_end_sys1, const System * lane_end_sys2, const ObjectMap & objects)
References ObjectMap::all(), and ObjectTooCloseToLane().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
MeterTypeDumpString()
std::string Condition::anonymous_namespace{Conditions.cpp}::MeterTypeDumpString (MeterType meter)
Referenced by Condition::MeterValue::Dump(), and Condition::ShipPartMeterValue::Dump().
NumberOnQueue()
int Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue (const ProductionQueue & queue, BuildType build_type, const int location_id, const std::string & name = "", int design_id = INVALID_DESIGN_ID)
References anonymous_namespace{XMLDoc.cpp}::element, GetShipDesign(), INVALID_DESIGN_ID, and ShipDesign::Name().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::operator()().
ObjectTooCloseToLane()
bool Condition::anonymous_namespace{Conditions.cpp}::ObjectTooCloseToLane (const UniverseObject * lane_end_sys1, const UniverseObject * lane_end_sys2, const UniverseObject * obj)
References UniverseObject::X(), and UniverseObject::Y().
Referenced by LaneTooCloseToOtherSystem().
TransferRandomObjects()
void Condition::anonymous_namespace{Conditions.cpp}::TransferRandomObjects (unsigned int number, ObjectSet & from_set, ObjectSet & to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set.
References RandomShuffle().
Referenced by TransferSortedObjects().
TransferSortedObjects()
void Condition::anonymous_namespace{Conditions.cpp}::TransferSortedObjects (unsigned int number, ValueRef::ValueRef< double > * sort_key, const ScriptingContext & context, SortingMethod sorting_method, ObjectSet & from_set, ObjectSet & to_set)
Transfers the indicated number of objects, selected from from_set into to_set.
The objects transferred are selected based on the value of sort_key evaluated on them, with the largest / smallest / most common sort keys chosen, or a random selection chosen, depending on the specified sorting_method
References ErrorLogger, ValueRef::ValueRef< T >::Eval(), Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, Condition::SORT_RANDOM, and TransferRandomObjects().
Referenced by Condition::SortedNumberOf::Eval().