FreeOrion: anonymous_namespace{TechsParser.cpp} Namespace Reference
anonymous_namespace{TechsParser.cpp} Namespace Reference
Classes
struct grammar
struct py_grammar_category
struct py_grammar_techs
Typedefs
using start_rule_signature = void(TechManager::TechContainer &)
Functions
bool check_tech (TechManager::TechContainer &techs, const std::unique_ptr< Tech > &tech)
Check if the tech will be unique.
void insert_category (std::map< std::string, std::unique_ptr< TechCategory >> &categories, std::string &name, std::string &graphic, const std::array< unsigned char, 4 > &color)
boost::python::object insert_category_ (const boost::python::tuple &args, const boost::python::dict &kw)
condition_wrapper insert_contained_by_ (const condition_wrapper &cond)
condition_wrapper insert_contains_ (const condition_wrapper &cond)
effect_group_wrapper insert_effects_group_ (const boost::python::tuple &args, const boost::python::dict &kw)
boost::python::object insert_game_rule_ (const py_grammar_techs &g, const boost::python::tuple &args, const boost::python::dict &kw)
effect_wrapper insert_generate_sit_rep_message_ (const boost::python::tuple &args, const boost::python::dict &kw)
condition_wrapper insert_has_tag_ (const boost::python::tuple &args, const boost::python::dict &kw)
unlockable_item_wrapper insert_item_ (const boost::python::tuple &args, const boost::python::dict &kw)
template<MeterType M>
condition_wrapper insert_meter_value_ (const boost::python::tuple &args, const boost::python::dict &kw)
template<ValueRef::OpType O>
boost::python::object insert_minmaxoneof_ (const py_grammar_techs &g, const boost::python::tuple &args, const boost::python::dict &kw)
template<typename T >
value_ref_wrapper< T > insert_named_lookup_ (const boost::python::tuple &args, const boost::python::dict &kw)
condition_wrapper insert_owned_by_ (const boost::python::tuple &args, const boost::python::dict &kw)
condition_wrapper insert_planet_ (const boost::python::tuple &args, const boost::python::dict &kw)
template<MeterType M>
effect_wrapper insert_set_meter_ (const boost::python::tuple &args, const boost::python::dict &kw)
void insert_tech (TechManager::TechContainer &techs, parse::detail::MovableEnvelope< Tech::TechInfo > &tech_info, boost::optional< parse::effects_group_payload > &effects, boost::optional< std::set< std::string >> &prerequisites, boost::optional< std::vector< UnlockableItem >> &unlocked_items, boost::optional< std::string > &graphic, bool &pass)
condition_wrapper insert_visible_to_empire_ (const boost::python::tuple &args, const boost::python::dict &kw)
boost::python::object py_insert_tech_ (TechManager::TechContainer &techs, const boost::python::tuple &args, const boost::python::dict &kw)
Variables
std::map< std::string, std::unique_ptr< TechCategory > > * g_categories = nullptr
std::set< std::string > * g_categories_seen = nullptr
const boost::phoenix::function< parse::detail::is_unique > is_unique_
Typedef Documentation
start_rule_signature
using anonymous_namespace{TechsParser.cpp}::start_rule_signature = typedef void(TechManager::TechContainer&)
Function Documentation
check_tech()
bool anonymous_namespace{TechsParser.cpp}::check_tech (TechManager::TechContainer & techs, const std::unique_ptr< Tech > & tech)
Check if the tech will be unique.
References ErrorLogger.
Referenced by insert_tech(), and py_insert_tech_().
insert_category()
void anonymous_namespace{TechsParser.cpp}::insert_category (std::map< std::string, std::unique_ptr< TechCategory >> & categories, std::string & name, std::string & graphic, const std::array< unsigned char, 4 > & color)
Referenced by insert_category_().
insert_category_()
boost::python::object anonymous_namespace{TechsParser.cpp}::insert_category_ (const boost::python::tuple & args, const boost::python::dict & kw)
References g_categories, and insert_category().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_category::operator()().
insert_contained_by_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_contained_by_ (const condition_wrapper & cond)
References ValueRef::CloneUnique(), and condition_wrapper::condition.
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_contains_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_contains_ (const condition_wrapper & cond)
References ValueRef::CloneUnique(), and condition_wrapper::condition.
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_effects_group_()
effect_group_wrapper anonymous_namespace{TechsParser.cpp}::insert_effects_group_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_game_rule_()
boost::python::object anonymous_namespace{TechsParser.cpp}::insert_game_rule_ (const py_grammar_techs & g, const boost::python::tuple & args, const boost::python::dict & kw)
References ErrorLogger, anonymous_namespace{TechsParser.cpp}::py_grammar_techs::m_parser, PythonParser::type_float, and PythonParser::type_int.
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_generate_sit_rep_message_()
effect_wrapper anonymous_namespace{TechsParser.cpp}::insert_generate_sit_rep_message_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_has_tag_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_has_tag_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_item_()
unlockable_item_wrapper anonymous_namespace{TechsParser.cpp}::insert_item_ (const boost::python::tuple & args, const boost::python::dict & kw)
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_meter_value_()
template<MeterType M> condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_meter_value_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
insert_minmaxoneof_()
template<ValueRef::OpType O> boost::python::object anonymous_namespace{TechsParser.cpp}::insert_minmaxoneof_ (const py_grammar_techs & g, const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique(), ErrorLogger, anonymous_namespace{TechsParser.cpp}::py_grammar_techs::m_parser, PythonParser::type_float, and PythonParser::type_int.
insert_named_lookup_()
template<typename T > value_ref_wrapper<T> anonymous_namespace{TechsParser.cpp}::insert_named_lookup_ (const boost::python::tuple & args, const boost::python::dict & kw)
insert_owned_by_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_owned_by_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_planet_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_planet_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
insert_set_meter_()
template<MeterType M> effect_wrapper anonymous_namespace{TechsParser.cpp}::insert_set_meter_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
insert_tech()
void anonymous_namespace{TechsParser.cpp}::insert_tech (TechManager::TechContainer & techs, parse::detail::MovableEnvelope< Tech::TechInfo > & tech_info, boost::optional< parse::effects_group_payload > & effects, boost::optional< std::set< std::string >> & prerequisites, boost::optional< std::vector< UnlockableItem >> & unlocked_items, boost::optional< std::string > & graphic, bool & pass)
References check_tech(), parse::detail::MovableEnvelope< T >::OpenEnvelope(), and parse::detail::OpenEnvelopes().
insert_visible_to_empire_()
condition_wrapper anonymous_namespace{TechsParser.cpp}::insert_visible_to_empire_ (const boost::python::tuple & args, const boost::python::dict & kw)
References ValueRef::CloneUnique().
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
py_insert_tech_()
boost::python::object anonymous_namespace{TechsParser.cpp}::py_insert_tech_ (TechManager::TechContainer & techs, const boost::python::tuple & args, const boost::python::dict & kw)
References check_tech(), ValueRef::CloneUnique(), tag_parser::description, and g_categories_seen.
Referenced by anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs().
Variable Documentation
g_categories
std::map<std::string, std::unique_ptr<TechCategory> >* anonymous_namespace{TechsParser.cpp}::g_categories = nullptr
Referenced by insert_category_(), and parse::techs().
g_categories_seen
std::set<std::string>* anonymous_namespace{TechsParser.cpp}::g_categories_seen = nullptr
Referenced by py_insert_tech_(), and parse::techs().
is_unique_
const boost::phoenix::function<parse::detail::is_unique> anonymous_namespace{TechsParser.cpp}::is_unique_