FreeOrion: anonymous_namespace{MultiMeterStatusBar.cpp} Namespace Reference
anonymous_namespace{MultiMeterStatusBar.cpp} Namespace Reference
Functions
const GG::Y BAR_HEIGHT (10)
const int BAR_PAD (1)
const int EDGE_PAD (3)
GG::Clr MeterColor (MeterType meter_type)
Returns GG::Clr with which to display programatically coloured things (such as meter bars) for the indicated meter_type.
Variables
const double MULTI_METER_STATUS_BAR_DISPLAYED_METER_RANGE_INCREMENT = 100.0
Function Documentation
const GG::Y anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_HEIGHT (10)
Referenced by MeterColor(), MultiMeterStatusBar::Render(), and MultiMeterStatusBar::Update().
const int anonymous_namespace{MultiMeterStatusBar.cpp}::BAR_PAD (1)
Referenced by MeterColor(), MultiMeterStatusBar::Render(), and MultiMeterStatusBar::Update().
const int anonymous_namespace{MultiMeterStatusBar.cpp}::EDGE_PAD (3)
Referenced by MeterColor(), MultiMeterStatusBar::Render(), and MultiMeterStatusBar::Update().
GG::Clr anonymous_namespace{MultiMeterStatusBar.cpp}::MeterColor (MeterType meter_type)
Returns GG::Clr with which to display programatically coloured things (such as meter bars) for the indicated meter_type.
References BAR_HEIGHT(), BAR_PAD(), EDGE_PAD(), METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_SHIELD, METER_MAX_STOCKPILE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SHIELD, METER_STEALTH, METER_STOCKPILE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by MultiMeterStatusBar::Update().
Variable Documentation
const double anonymous_namespace{MultiMeterStatusBar.cpp}::MULTI_METER_STATUS_BAR_DISPLAYED_METER_RANGE_INCREMENT = 100.0
Referenced by MultiMeterStatusBar::Render().