FreeOrion: anonymous_namespace{LoggerWithOptionsDB.cpp} Namespace Reference
anonymous_namespace{LoggerWithOptionsDB.cpp} Namespace Reference
Functions
LogLevel AddLoggerToOptionsDB (const std::string &full_option_name)
Add the log threshold for a logger with full_option_name to OptionsDB and return the threshold read from OptionsDB.
BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log), NamedThreadedLogger)
std::regex exec_name_regex ("(?:logging\execs\)(\+)")
std::set< std::tuple< std::string, std::string, LogLevel > > LoggerOptionsLabelsAndLevels (const std::string prefix, const std::regex &prefix_regex)
Returns the list of full option names, logger names and thresholds for loggers in OptionsDB will prefix using prefix_regex.
std::regex source_name_regex ("(?:logging\sources\)(\+)")
Variables
constexpr LogLevel default_sink_level = default_log_level_threshold
constexpr LogLevel default_source_level = default_log_level_threshold
constexpr auto exec_option_name_prefix = "logging.execs."
constexpr auto source_option_name_prefix = "logging.sources."
Function Documentation
AddLoggerToOptionsDB()
LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB (const std::string & full_option_name)
Add the log threshold for a logger with full_option_name to OptionsDB and return the threshold read from OptionsDB.
References OptionsDB::Add(), tag_parser::description, exec_name_regex(), GetOptionsDB(), LogLevelValidator(), source_name_regex(), to_LogLevel(), to_string(), UserStringNop, and WarnLogger.
Referenced by InitLoggingOptionsDBSystem(), LoggerOptionsLabelsAndLevels(), and RegisterLoggerWithOptionsDB().
BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT()
anonymous_namespace{LoggerWithOptionsDB.cpp}::BOOST_LOG_INLINE_GLOBAL_LOGGER_INIT (FO_GLOBAL_LOGGER_NAME(log) , NamedThreadedLogger)
References debug.
exec_name_regex()
std::regex anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_name_regex ("(?:logging\ecs\\")
Referenced by AddLoggerToOptionsDB(), ChangeLoggerThresholdInOptionsDB(), LoggerOptionsLabelsAndLevels(), and SetLoggerThresholds().
LoggerOptionsLabelsAndLevels()
std::set<std::tuple<std::string, std::string, LogLevel> > anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels (const std::string prefix, const std::regex & prefix_regex)
Returns the list of full option names, logger names and thresholds for loggers in OptionsDB will prefix using prefix_regex.
References AddLoggerToOptionsDB(), ErrorLogger, OptionsDB::FindOptions(), and GetOptionsDB().
Referenced by OptionsWnd::CompleteConstruction(), MPLobby::EstablishPlayer(), WaitingForSPGameJoiners::react(), WaitingForMPGameJoiners::react(), and HumanClientApp::SendLoggingConfigToServer().
source_name_regex()
std::regex anonymous_namespace{LoggerWithOptionsDB.cpp}::source_name_regex ("(?:logging\urces\\")
Referenced by AddLoggerToOptionsDB(), ChangeLoggerThresholdInOptionsDB(), and LoggerOptionsLabelsAndLevels().
Variable Documentation
default_sink_level
constexpr LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::default_sink_level = default_log_level_threshold
default_source_level
constexpr LogLevel anonymous_namespace{LoggerWithOptionsDB.cpp}::default_source_level = default_log_level_threshold
exec_option_name_prefix
constexpr auto anonymous_namespace{LoggerWithOptionsDB.cpp}::exec_option_name_prefix = "logging.execs."
Referenced by InitLoggingOptionsDBSystem(), LoggerOptionsLabelsAndLevels(), and RegisterLoggerWithOptionsDB().
source_option_name_prefix
constexpr auto anonymous_namespace{LoggerWithOptionsDB.cpp}::source_option_name_prefix = "logging.sources."
Referenced by LoggerOptionsLabelsAndLevels(), and RegisterLoggerWithOptionsDB().