FreeOrion: anonymous_namespace{CensusBrowseWnd.cpp} Namespace Reference
anonymous_namespace{CensusBrowseWnd.cpp} Namespace Reference
Functions
const GG::X BrowseTextWidth ()
const int EDGE_PAD (3)
const GG::Y ICON_BROWSE_ICON_HEIGHT (64)
int IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
GG::Pt MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Function Documentation
BrowseTextWidth()
const GG::X anonymous_namespace{CensusBrowseWnd.cpp}::BrowseTextWidth ()
References FontBasedUpscale().
Referenced by CensusBrowseWnd::CompleteConstruction().
EDGE_PAD()
const int anonymous_namespace{CensusBrowseWnd.cpp}::EDGE_PAD (3)
Referenced by CensusBrowseWnd::CompleteConstruction(), CensusRowPanel::DoLayout(), and IconTextBrowseWndRowHeight().
ICON_BROWSE_ICON_HEIGHT()
const GG::Y anonymous_namespace{CensusBrowseWnd.cpp}::ICON_BROWSE_ICON_HEIGHT (64)
Referenced by IconTextBrowseWndRowHeight().
IconTextBrowseWndRowHeight()
int anonymous_namespace{CensusBrowseWnd.cpp}::IconTextBrowseWndRowHeight ()
Returns height of rows of text in InfoTextBrowseWnd.
References EDGE_PAD(), ICON_BROWSE_ICON_HEIGHT(), and ClientUI::Pts().
Referenced by CensusBrowseWnd::InitBuffer().
MeterIconSize()
GG::Pt anonymous_namespace{CensusBrowseWnd.cpp}::MeterIconSize ()
How big we want meter icons with respect to the current UI font size.
Meters should scale along font size, but not below the size for the default 12 points font.
References ClientUI::Pts().
Referenced by CensusBrowseWnd::CompleteConstruction(), and CensusRowPanel::DoLayout().