FreeOrion: anonymous_namespace{VarText.cpp} Namespace Reference
anonymous_namespace{VarText.cpp} Namespace Reference
Classes
struct StringAppend
struct SubstituteAndAppend
Typedefs
typedef std::string(* TagString) (const std::string &data, const std::string &tag, bool &valid)
Functions
std::string CombatLogString (const std::string &data, const std::string &tag, bool &valid)
combat links always just labelled "Combat"; don't need to look up details
std::map< std::string, TagString > CreateSubstituterMap ()
std::string EmpireString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for an empire tag.
const std::string END_VAR ("%")
const std::string LABEL_SEPARATOR (":")
std::string MeterTypeString (const std::string &data, const std::string &tag, bool &valid)
template<typename T , const T *(*)(const std::string &) GetByName>
std::string NameString (const std::string &data, const std::string &tag, bool &valid)
std::string PredefinedShipDesignString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for a predefined ship design tag.
std::string RawTextString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a raw text tag.
std::string ShipDesignString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for a ship design tag.
const std::string START_VAR ("%")
const std::map< std::string, TagString > & SubstitutionMap ()
Global substitution map, wrapped in a function to avoid initialization order issues.
std::string TextString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a translated text tag.
std::string UniverseObjectString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a tag that is a universe object.
std::string WithTags (const std::string &content, const std::string &tag, const std::string &data)
Surround content with approprite tags based on tag_of.
Typedef Documentation
typedef std::string(* anonymous_namespace{VarText.cpp}::TagString) (const std::string &data, const std::string &tag, bool &valid)
The signature of functions that generate substitution strings for tags.
Function Documentation
std::string anonymous_namespace{VarText.cpp}::CombatLogString (const std::string & data, const std::string & tag, bool & valid)
combat links always just labelled "Combat"; don't need to look up details
References UserString(), and WithTags().
Referenced by CreateSubstituterMap().
std::map<std::string, TagString> anonymous_namespace{VarText.cpp}::CreateSubstituterMap ()
Returns a map that tells shich function should be used to generate a substitution for which tag.
References VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, CombatLogString(), VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, EmpireString(), VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, VarText::METER_TYPE_TAG, MeterTypeString(), VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, PredefinedShipDesignString(), VarText::RAW_TEXT_TAG, RawTextString(), VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, ShipDesignString(), VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, VarText::TEXT_TAG, TextString(), and UniverseObjectString().
Referenced by SubstitutionMap().
std::string anonymous_namespace{VarText.cpp}::EmpireString (const std::string & data, const std::string & tag, bool & valid)
Returns substitution string for an empire tag.
References ALL_EMPIRES, ErrorLogger, GetEmpire(), Empire::Name(), UserString(), and WithTags().
Referenced by CreateSubstituterMap().
const std::string anonymous_namespace{VarText.cpp}::END_VAR ("%")
Referenced by VarText::GenerateVarText().
const std::string anonymous_namespace{VarText.cpp}::LABEL_SEPARATOR (":")
std::string anonymous_namespace{VarText.cpp}::MeterTypeString (const std::string & data, const std::string & tag, bool & valid)
References INVALID_METER_TYPE, UserString(), UserStringExists(), and WithTags().
Referenced by CreateSubstituterMap().
template<typename T , const T *(*)(const std::string &) GetByName> std::string anonymous_namespace{VarText.cpp}::NameString (const std::string & data, const std::string & tag, bool & valid)
Interprets value of data as a name. Returns translation of name, if Get says that a thing by that name exists, otherwise ERROR.
References UserString(), and WithTags().
std::string anonymous_namespace{VarText.cpp}::PredefinedShipDesignString (const std::string & data, const std::string & tag, bool & valid)
Returns substitution string for a predefined ship design tag.
References ErrorLogger, GetPredefinedShipDesign(), ShipDesign::Name(), UserString(), and WithTags().
Referenced by CreateSubstituterMap().
std::string anonymous_namespace{VarText.cpp}::RawTextString (const std::string & data, const std::string & tag, bool & valid)
Get string substitute for a raw text tag.
Referenced by CreateSubstituterMap().
std::string anonymous_namespace{VarText.cpp}::ShipDesignString (const std::string & data, const std::string & tag, bool & valid)
Returns substitution string for a ship design tag.
References ErrorLogger, GetShipDesign(), ShipDesign::INVALID_DESIGN_ID, ShipDesign::Name(), UserString(), and WithTags().
Referenced by CreateSubstituterMap().
const std::string anonymous_namespace{VarText.cpp}::START_VAR ("%")
Referenced by VarText::GenerateVarText().
const std::map<std::string, TagString>& anonymous_namespace{VarText.cpp}::SubstitutionMap ()
Global substitution map, wrapped in a function to avoid initialization order issues.
References CreateSubstituterMap().
Referenced by anonymous_namespace{VarText.cpp}::SubstituteAndAppend::operator()().
std::string anonymous_namespace{VarText.cpp}::TextString (const std::string & data, const std::string & tag, bool & valid)
Get string substitute for a translated text tag.
References UserString().
Referenced by CreateSubstituterMap().
std::string anonymous_namespace{VarText.cpp}::UniverseObjectString (const std::string & data, const std::string & tag, bool & valid)
Get string substitute for a tag that is a universe object.
References ErrorLogger, GetUniverseObject(), GetVisibleObjectName(), INVALID_OBJECT_ID, UserString(), and WithTags().
Referenced by CreateSubstituterMap().
std::string anonymous_namespace{VarText.cpp}::WithTags (const std::string & content, const std::string & tag, const std::string & data)
Surround content with approprite tags based on tag_of.
Referenced by CombatLogString(), EmpireString(), MeterTypeString(), NameString(), PredefinedShipDesignString(), ShipDesignString(), and UniverseObjectString().