FreeOrion: ObjectListWnd.cpp File Reference
ObjectListWnd.cpp File Reference
#include "ObjectListWnd.h"
#include "ClientUI.h"
#include "CUIControls.h"
#include "CUISpin.h"
#include "FleetButton.h"
#include "../client/human/GGHumanClientApp.h"
#include "../client/ClientNetworking.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/Order.h"
#include "../util/ModeratorAction.h"
#include "../util/ScopedTimer.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../universe/System.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/ShipDesign.h"
#include "../universe/Planet.h"
#include "../universe/Building.h"
#include "../universe/Field.h"
#include "../universe/Species.h"
#include "../universe/Conditions.h"
#include "../universe/ValueRefs.h"
#include <GG/Layout.h>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/random_generator.hpp>
#include <iterator>
#include <sstream>
Classes
struct anonymous_namespace{ObjectListWnd.cpp}::CustomRowCmp
class ConditionWidget
class ConditionWidget::ConditionRow
class ConditionWidget::StringRow
class FilterDialog
class ObjectHeaderPanel
class ObjectHeaderRow
class ObjectListBox
class ObjectPanel
class ObjectRow
Namespaces
anonymous_namespace{ObjectListWnd.cpp}
Typedefs
using anonymous_namespace{ObjectListWnd.cpp}::id_range = boost::any_range< int, boost::forward_traversal_tag >
Enumerations
enum anonymous_namespace{ObjectListWnd.cpp}::VIS_DISPLAY : int { anonymous_namespace{ObjectListWnd.cpp}::VIS_DISPLAY::SHOW_VISIBLE, anonymous_namespace{ObjectListWnd.cpp}::VIS_DISPLAY::SHOW_PREVIOUSLY_VISIBLE, anonymous_namespace{ObjectListWnd.cpp}::VIS_DISPLAY::SHOW_DESTROYED }
Functions
void anonymous_namespace{ObjectListWnd.cpp}::AddOptions (OptionsDB &db)
const std::string anonymous_namespace{ObjectListWnd.cpp}::ALL_CONDITION (UserStringNop("CONDITION_ALL"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::ARMED_CONDITION (UserStringNop("CONDITION_ARMED"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::ASTWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_AST"))
const std::map< std::pair< std::string, std::string >, std::unique_ptr< ValueRef::ValueRef< std::string > > > & anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes ()
const std::string anonymous_namespace{ObjectListWnd.cpp}::BUILDING_CONDITION (UserStringNop("CONDITION_BUILDING"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::CANCOLONIZE_CONDITION (UserStringNop("CONDITION_CANCOLONIZE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::CANPRODUCESHIPS_CONDITION (UserStringNop("CONDITION_CANPRODUCESHIPS"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::CAPITAL_CONDITION (UserStringNop("CONDITION_CAPITAL"))
const GG::X CONDITION_WIDGET_WIDTH (380)
const std::string & anonymous_namespace{ObjectListWnd.cpp}::ConditionClassName (const Condition::Condition *const condition)
std::unique_ptr< Condition::Condition > anonymous_namespace{ObjectListWnd.cpp}::ConditionForObjectTypes (const std::vector< UniverseObjectType > &object_types)
const std::string anonymous_namespace{ObjectListWnd.cpp}::CONTAINEDBY_CONDITION (UserStringNop("CONDITION_CONTAINEDBY"))
template<typename enumT >
std::unique_ptr< ValueRef::ValueRef< enumT > > anonymous_namespace{ObjectListWnd.cpp}::CopyEnumValueRef (const ValueRef::ValueRef< enumT > *const value_ref)
const std::string anonymous_namespace{ObjectListWnd.cpp}::CREATEDONTURN_CONDITION (UserStringNop("CONDITION_CREATEDONTURN"))
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::DesignCostValueRef ()
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::DesignNameValueRef (const char *token)
const std::string anonymous_namespace{ObjectListWnd.cpp}::EMPIREAFFILIATION_CONDITION (UserStringNop("CONDITION_EMPIREAFFILIATION"))
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::EmpireNameValueRef (const char *token)
const std::string anonymous_namespace{ObjectListWnd.cpp}::EXPLOREDBYEMPIRE_CONDITION (UserStringNop("CONDITION_EXPLOREDBYEMPIRE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::FOCUSTYPE_CONDITION (UserStringNop("CONDITION_FOCUSTYPE"))
std::string anonymous_namespace{ObjectListWnd.cpp}::GetColumnName (int column)
unused function.
const ValueRef::ValueRef< std::string > * anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef (int column)
int anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth (int column)
const ValueRef::ValueRef< std::string > * anonymous_namespace{ObjectListWnd.cpp}::GetValueRefByName (const std::string &name)
const std::string anonymous_namespace{ObjectListWnd.cpp}::GGWITHPTYPE_CONDITION (UserStringNop("CONDITION_PTYPE_W_GG"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASGROWTHSPECIAL_CONDITION (UserStringNop("CONDITION_HAS_GROWTH_SPECIAL"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASSPECIAL_CONDITION (UserStringNop("CONDITION_HASSPECIAL"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::HASTAG_CONDITION (UserStringNop("CONDITION_HASTAG"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::HOMEWORLD_CONDITION (UserStringNop("CONDITION_HOMEWORLD"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::INSYSTEM_CONDITION (UserStringNop("CONDITION_INSYSTEM"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::METERVALUE_CONDITION (UserStringNop("CONDITION_METERVALUE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::MONSTER_CONDITION (UserStringNop("CONDITION_MONSTER"))
const unsigned int anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS (12u)
const std::string anonymous_namespace{ObjectListWnd.cpp}::OBJECTID_CONDITION (UserStringNop("CONDITION_OBJECTID"))
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::ObjectNameValueRef (const char *token)
std::vector< std::shared_ptr< GG::Texture > > anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures (std::shared_ptr< const UniverseObject > obj)
template<typename T >
std::unique_ptr< ValueRef::ValueRef< T > > anonymous_namespace{ObjectListWnd.cpp}::ObjectTypeFilteredRef (const std::vector< UniverseObjectType > &object_types, std::unique_ptr< ValueRef::ValueRef< T >> &&value_ref)
const GG::X anonymous_namespace{ObjectListWnd.cpp}::PAD (3)
std::unique_ptr< ValueRef::ValueRef< std::string > > anonymous_namespace{ObjectListWnd.cpp}::PlanetEnvForSpecies (const std::string &species_name)
const std::string anonymous_namespace{ObjectListWnd.cpp}::PLANETSIZE_CONDITION (UserStringNop("CONDITION_PLANETSIZE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::PLANETTYPE_CONDITION (UserStringNop("CONDITION_PLANETTYPE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::PRODUCEDBYEMPIRE_CONDITION (UserStringNop("CONDITION_PRODUCEDBYEMPIRE"))
void anonymous_namespace{ObjectListWnd.cpp}::SetColumnName (int column, const std::string &name)
std::vector< std::string > SpecialNames ()
const std::string anonymous_namespace{ObjectListWnd.cpp}::SPECIES_CONDITION (UserStringNop("CONDITION_SPECIES"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::STARTYPE_CONDITION (UserStringNop("CONDITION_STARTYPE"))
const std::string anonymous_namespace{ObjectListWnd.cpp}::STATIONARY_CONDITION (UserStringNop("CONDITION_STATIONARY"))
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::StringCastedComplexValueRef (const char *token, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref1=nullptr, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref2=nullptr, std::unique_ptr< ValueRef::ValueRef< int >> &&int_ref3=nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> &&string_ref1=nullptr, std::unique_ptr< ValueRef::ValueRef< std::string >> &&string_ref2=nullptr)
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::StringCastedImmediateValueRef (std::string token)
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::StringCastedValueRef (const char *token)
template<typename enumT >
std::vector< std::string > anonymous_namespace{ObjectListWnd.cpp}::StringsFromEnums (const std::vector< enumT > &enum_vals)
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::StringValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::SystemSupplyDistanceValueRef ()
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::SystemSupplyRangeValueRef (bool propagated=false)
template<typename T >
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::UserStringCastedValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::UserStringValueRef (const char *token)
std::unique_ptr< ValueRef::Variable< std::string > > anonymous_namespace{ObjectListWnd.cpp}::UserStringVecValueRef (const char *token)
Variables
const int anonymous_namespace{ObjectListWnd.cpp}::DATA_PANEL_BORDER = 1
const std::string anonymous_namespace{ObjectListWnd.cpp}::EMPTY_STRING
const std::string anonymous_namespace{ObjectListWnd.cpp}::FILTER_OPTIONS_WND_NAME = "object-list-filter"
std::map< std::string, std::string > anonymous_namespace{ObjectListWnd.cpp}::object_list_cond_description_map
bool anonymous_namespace{ObjectListWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
CONDITION_WIDGET_WIDTH()
const GG::X CONDITION_WIDGET_WIDTH (380)
Referenced by anonymous_namespace{ObjectListWnd.cpp}::StringsFromEnums().
SpecialNames()
std::vector<std::string> SpecialNames ()
Referenced by MessageWndEdit::FindGameWords(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecials(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ConditionWidget::UpdateParameterControls(), and ClientUI::ZoomToContent().