FreeOrion: OptionsDB.h File Reference
OptionsDB.h File Reference
#include "Export.h"
#include "Logger.h"
#include "OptionValidators.h"
#include <boost/any.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/signals2/signal.hpp>
#include <map>
Classes
class OptionsDB
struct OptionsDB::Option
Typedefs
typedef void(* OptionsDBFn) (OptionsDB &)
the function signature for functions that add Options to the OptionsDB (void (OptionsDB&))
Functions
FO_COMMON_API OptionsDB & GetOptionsDB ()
FO_COMMON_API bool RegisterOptions (OptionsDBFn function)
Typedef Documentation
typedef void(* OptionsDBFn) (OptionsDB &)
the function signature for functions that add Options to the OptionsDB (void (OptionsDB&))
Function Documentation
FO_COMMON_API OptionsDB& GetOptionsDB ()
returns the single instance of the OptionsDB class
References anonymous_namespace{OptionsDB.cpp}::OptionsRegistry(), and OptionsDB::Option::short_names.
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), CUIWnd::AddWindowOptions(), AIClientApp::AIClientApp(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateTargetMaxUnpairedMeters(), HumanClientApp::Autosave(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), BasesListBox::BasesListBoxRow::BasesListBoxRow(), OptionsWnd::BoolOption(), GameRulesPanel::BoolRuleWidget(), ClientUI::ClientUI(), OptionsWnd::ColorOption(), TechTreeWnd::TechListBox::TechRow::ColWidths(), InGameMenu::CompleteConstruction(), ModeratorActionsWnd::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), ProductionWnd::CompleteConstruction(), FleetButton::CompleteConstruction(), TechTreeWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), StatisticIcon::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), TechTreeWnd::LayoutPanel::CompleteConstruction(), MapWnd::MapScaleLine::CompleteConstruction(), TechTreeWnd::LayoutPanel::TechPanel::CompleteConstruction(), PartControl::CompleteConstruction(), SlotControl::CompleteConstruction(), DesignWnd::MainPanel::CompleteConstruction(), CompleteXDGMigration(), anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption(), anonymous_namespace{ClientUI.cpp}::ConditionalForward(), ServerApp::CreateAIClients(), GameRulesPanel::CreateSectionHeader(), OptionsWnd::CreateSectionHeader(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), CUIWnd::CUIWnd(), ClientUI::DefaultLinkColor(), DesignWnd::MainPanel::DesignNameChanged(), Networking::DiscoveryPort(), TechTreeWnd::TechTreeControls::DoButtonLayout(), ResearchWnd::DoLayout(), ProductionWnd::DoLayout(), OptionsWnd::DoneClicked(), OptionsWnd::DoubleOption(), GameRulesPanel::DoubleRuleWidget(), ClientUI::DropDownListArrowColor(), ClientUI::EditHiliteColor(), AIClientApp::EffectsProcessingThreads(), HumanClientApp::EffectsProcessingThreads(), ServerApp::EffectsProcessingThreads(), SystemIcon::EnclosingCircleDiameter(), OptionsWnd::FileOptionImpl(), SaveFileListBox::FilterColumns(), anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), FleetButton::FleetButton(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FPSIndicator::FPSIndicator(), BarSizer::Get(), AIInterface::GetAIDir(), ClientUI::GetBoldFont(), SaveFileColumn::GetColumn(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), ClientUI::GetFont(), anonymous_namespace{SitRepPanel.cpp}::GetIconSize(), AIInterface::GetOptionsDBOptionBool(), AIInterface::GetOptionsDBOptionDouble(), AIInterface::GetOptionsDBOptionInt(), AIInterface::GetOptionsDBOptionStr(), GetResourceDir(), GetSaveDir(), anonymous_namespace{SitRepPanel.cpp}::GetSitRepsSortedByTurn(), anonymous_namespace{i18n.cpp}::GetStringTableFileName(), ClientUI::GetTitleFont(), HumanClientApp::GetWindowLeftTop(), HumanClientApp::GetWindowWidthHeight(), HumanClientApp::HandleFocusChange(), ClientUI::HandleFullscreenSwitch(), EncyclopediaDetailPanel::HandleSearchTextEntered(), ClientUI::HandleSizeChange(), HumanClientApp::HandleWindowMove(), HumanClientApp::HandleWindowResize(), anonymous_namespace{SitRepPanel.cpp}::HiddenSitRepTemplateStringsFromOptions(), TechTreeWnd::HidePedia(), BuildDesignatorWnd::HidePedia(), HumanClientApp::HumanClientApp(), if(), Sound::Impl::Impl(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), ServerNetworking::Init(), ShipDataPanel::Init(), FleetDataPanel::Init(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::Init(), BuildDesignatorWnd::InitializeWindows(), MapWnd::InitializeWindows(), PythonAI::InitModules(), CUIWnd::InitSizeMove(), MapWnd::InitTurn(), MapWnd::InitVisibilityRadiiRenderingBuffers(), OptionsWnd::IntOption(), GameRulesPanel::IntRuleWidget(), CUIWnd::InvalidateUnusedOptions(), CUIWnd::InvalidateWindowOptions(), ServerApp::IsHostless(), ClientUI::KnownTechFillColor(), ClientUI::KnownTechTextAndBorderColor(), TechTreeWnd::LayoutPanel::Layout(), FleetButton::LayoutIcons(), MapWnd::LClick(), CUIWnd::LoadOptions(), SaveFileListBox::LoadSaveGamePreviews(), HumanClientApp::LoadSinglePlayerGame(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), main(), mainConfigOptionsSetup(), mainSetupAndRun(), anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), ClientUI::MediumFleetButtonZoomThreshold(), ClientUI::MessageBox(), Networking::MessagePort(), SystemIcon::MouseEnter(), HumanClientApp::MultiPlayerGame(), OptionsWnd::SoundOptionsFeedback::MusicClicked(), OptionsWnd::MusicVolumeOption(), OptionsWnd::SoundOptionsFeedback::MusicVolumeSlid(), anonymous_namespace{FleetWnd.cpp}::NewFleetsAggressiveOptionSetting(), HumanClientApp::NewSinglePlayerGame(), ServerConnectWnd::OkClicked(), GalaxySetupWnd::OkClicked(), detail::PlayValueChangedSound::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ParticipantBar::ParticipantBar(), anonymous_namespace{SidePanel.cpp}::PlanetDiameter(), anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound(), anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound(), anonymous_namespace{CUIWnd.cpp}::PlayCloseSound(), anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound(), FleetButton::PlayFleetButtonOpenSound(), FleetButton::PlayFleetButtonRolloverSound(), PlayingTurn::PlayingTurn(), anonymous_namespace{CUIControls.cpp}::PlayItemDropSound(), anonymous_namespace{CUIControls.cpp}::PlayListSelectSound(), anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound(), anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound(), anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound(), Sound::Impl::PlaySound(), anonymous_namespace{SystemIcon.cpp}::PlaySounds(), anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound(), anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), IntroScreen::PreRender(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), ClientUI::Pts(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), MapWnd::RClick(), PlayingTurn::react(), BuildingIndicator::Refresh(), ShipDataPanel::Refresh(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshDetectionIndicator(), MapWnd::RefreshFleetResourceIndicator(), MapWnd::RefreshIndustryResourceIndicator(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshSliders(), MapWnd::RefreshTradeResourceIndicator(), HumanClientApp::Reinitialize(), BuildingIndicator::Render(), RotatingPlanetControl::Render(), MapWnd::RenderFields(), MapWnd::RenderFleetMovementLines(), MapWnd::RenderGalaxyGas(), MapWnd::RenderScaleCircle(), MapWnd::RenderStarfields(), MapWnd::RenderStarlanes(), MapWnd::RenderSystems(), MapWnd::RenderVisibilityRadii(), anonymous_namespace{ClientUI.cpp}::RequiredCharsets(), ClientUI::ResearchableTechFillColor(), ClientUI::ResearchableTechTextAndBorderColor(), ResearchWnd::ResearchWnd(), Hotkey::ResetHotkey(), HumanClientApp::ResetOrExitApp(), OptionsWnd::ResolutionOption(), ClientUI::RolloverLinkColor(), SaveGame(), CUIWnd::SaveOptions(), ClientUI::ScrollWidth(), ServerApp::ServerApp(), ServerNetworking::ServerNetworking(), BarSizer::Set(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), Hotkey::SetHotkey(), SetLoggerThresholds(), Sound::Impl::SetMusicVolume(), anonymous_namespace{FleetWnd.cpp}::SetNewFleetAggressiveOptionSetting(), SlotControl::SetPart(), TechTreeWnd::LayoutPanel::SetScale(), ShipDataPanel::SetShipIcon(), anonymous_namespace{HumanClientApp.cpp}::SetStringtableDependentOptionDefaults(), TechTreeWnd::SetTechStatus(), Sound::Impl::SetUISoundsVolume(), TechTreeWnd::Show(), TechTreeWnd::ShowPedia(), BuildDesignatorWnd::ShowPedia(), MapWnd::ShowProduction(), MapWnd::ShowResearch(), SystemIcon::SizeMove(), ClientUI::SmallFleetButtonZoomThreshold(), OptionsWnd::SoundOptionsFeedback::SoundEffectsEnableClicked(), OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure(), ShipDesignManager::StartGame(), HumanClientApp::StartServer(), HumanClientApp::StartTurn(), ScanlineRenderer::Impl::StartUsing(), ClientUI::StatDecrColor(), ClientUI::StateButtonColor(), ClientUI::StatIncrColor(), GameRulesPanel::StringRuleWidget(), ClientUI::SystemCircleSize(), ClientUI::SystemIconSize(), ClientUI::SystemNameTextColor(), ClientUI::SystemSelectionIndicatorRPM(), ClientUI::SystemSelectionIndicatorSize(), ClientUI::SystemTinyIconSizeThreshold(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), ClientUI::TextColor(), ClientUI::TinyFleetButtonZoomThreshold(), ClientUI::TitlePts(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{MapWnd.cpp}::ToggleBoolOption(), HumanClientApp::ToggleFullscreen(), OptionsWnd::SoundOptionsFeedback::UISoundsVolumeSlid(), ClientUI::UnresearchableTechFillColor(), ClientUI::UnresearchableTechTextAndBorderColor(), SpecialsPanel::Update(), FleetDataPanel::UpdateAggressionToggle(), FPSIndicator::UpdateEnabled(), MapWnd::MapScaleLine::UpdateEnabled(), HumanClientApp::UpdateFPSLimit(), Universe::UpdateMeterEstimatesImpl(), OptionsWnd::VolumeOption(), ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), ClientUI::WndOuterBorderColor(), and CUIWnd::~CUIWnd().
FO_COMMON_API bool RegisterOptions (OptionsDBFn function)
adds function to a vector of pointers to functions that add Options to the OptionsDB. This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterOption(&foo)").
References anonymous_namespace{OptionsDB.cpp}::OptionsRegistry().
Referenced by mainSetupAndRun().