FreeOrion: OptionValidators.h File Reference
OptionValidators.h File Reference
#include <boost/any.hpp>
#include <boost/lexical_cast.hpp>
#include <cmath>
#include <memory>
#include <set>
#include <string>
#include <vector>
Classes
struct DiscreteValidator< T >
a Validator that specifies a finite number of valid values.
struct OrValidator< T >
a Validator that performs a logical OR of two validators.
struct RangedStepValidator< T >
a Validator similar to a StepValidator, but that further constrains the valid values to be within a certain range (eg: [25, 50, ..., 200]).
struct RangedValidator< T >
a Validator that constrains the range of valid values
struct StepValidator< T >
a Validator that constrains valid values to certain step-values (eg: 0, 25, 50, ...).
struct Validator< T >
determines if a string is a valid value for an OptionsDB option
struct Validator< std::vector< std::string > >
struct ValidatorBase
base class for all OptionsDB validators.
Namespaces
details
Functions
FO_COMMON_API std::string ListToString (const std::vector< std::string > &input_list)
template<class T >
T details::mod (T dividend, T divisor)
template<>
double details::mod< double > (double dividend, double divisor)
template<>
float details::mod< float > (float dividend, float divisor)
template<>
long double details::mod< long double > (long double dividend, long double divisor)
FO_COMMON_API std::vector< std::string > StringToList (const std::string &input_string)
Function Documentation
ListToString()
FO_COMMON_API std::string ListToString (const std::vector< std::string > & input_list)
Referenced by Validator< T >::Clone(), and Validator< std::vector< std::string > >::String().
StringToList()
FO_COMMON_API std::vector<std::string> StringToList (const std::string & input_string)
Referenced by anonymous_namespace{SaveFileDialog.cpp}::AddOptions(), Validator< T >::Clone(), and Validator< std::vector< std::string > >::Validate().