FreeOrion: OptionsDB.cpp File Reference
OptionsDB.cpp File Reference
#include "OptionsDB.h"
#include "i18n.h"
#include "Logger.h"
#include "OptionValidators.h"
#include "XMLDoc.h"
#include "util/Directories.h"
#include <iostream>
#include <iomanip>
#include <stdexcept>
#include <string>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/erase.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/range/algorithm_ext/erase.hpp>
#include <boost/tokenizer.hpp>
Namespaces
anonymous_namespace{OptionsDB.cpp}
Functions
OptionsDB & GetOptionsDB ()
returns the single instance of the OptionsDB class
std::string ListToString (const std::vector< std::string > &input_list)
bool anonymous_namespace{OptionsDB.cpp}::OptionNameHasParentSection (const std::string &lhs, const std::string &rhs)
std::vector< OptionsDBFn > & anonymous_namespace{OptionsDB.cpp}::OptionsRegistry ()
std::string anonymous_namespace{OptionsDB.cpp}::PreviousSectionName (const std::vector< XMLElement * > &elem_stack)
bool RegisterOptions (OptionsDBFn function)
adds function to a vector of pointers to functions that add Options to the OptionsDB.
std::string anonymous_namespace{OptionsDB.cpp}::SplitText (const std::string &text, std::pair< std::size_t, std::size_t > indents={0, 0}, std::pair< std::size_t, std::size_t > widths={TERMINAL_LINE_WIDTH, TERMINAL_LINE_WIDTH})
Breaks and indents text over multiple lines when it exceeds width limits.
std::vector< std::string > StringToList (const std::string &input_string)
void anonymous_namespace{OptionsDB.cpp}::StripQuotation (std::string &str)
Variables
const std::size_t anonymous_namespace{OptionsDB.cpp}::TERMINAL_LINE_WIDTH = 80
Function Documentation
OptionsDB& GetOptionsDB ()
returns the single instance of the OptionsDB class
References anonymous_namespace{OptionsDB.cpp}::OptionsRegistry(), and OptionsDB::Option::short_names.
Referenced by anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), CUIWnd::AddWindowOptions(), AIClientApp::AIClientApp(), Universe::ApplyAllEffectsAndUpdateMeters(), Universe::ApplyMeterEffectsAndUpdateMeters(), HumanClientApp::Autosave(), CompletedDesignsListBox::BaseRightClicked(), SavedDesignsListBox::BaseRightClicked(), BasesListBox::BasesListBoxRow::BasesListBoxRow(), OptionsWnd::BoolOption(), GameRulesPanel::BoolRuleWidget(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), ClientUI::ClientUI(), OptionsWnd::ColorOption(), TechTreeWnd::TechListBox::TechRow::ColWidths(), InGameMenu::CompleteConstruction(), ModeratorActionsWnd::CompleteConstruction(), MultiPlayerLobbyWnd::CompleteConstruction(), OptionsWnd::CompleteConstruction(), ProductionWnd::CompleteConstruction(), ServerConnectWnd::CompleteConstruction(), FleetButton::CompleteConstruction(), TechTreeWnd::CompleteConstruction(), MapWnd::CompleteConstruction(), GalaxySetupPanel::CompleteConstruction(), FleetWnd::CompleteConstruction(), GalaxySetupWnd::CompleteConstruction(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), TechTreeWnd::TechTreeControls::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction(), StatisticIcon::CompleteConstruction(), SidePanel::PlanetPanel::CompleteConstruction(), TechTreeWnd::LayoutPanel::CompleteConstruction(), MapWnd::MapScaleLine::CompleteConstruction(), TechTreeWnd::LayoutPanel::TechPanel::CompleteConstruction(), PartControl::CompleteConstruction(), SlotControl::CompleteConstruction(), DesignWnd::MainPanel::CompleteConstruction(), CompleteXDGMigration(), anonymous_namespace{ClientUI.cpp}::ConditionalConnectOption(), anonymous_namespace{ClientUI.cpp}::ConditionalForward(), ServerApp::CreateAIClients(), GameRulesPanel::CreateSectionHeader(), OptionsWnd::CreateSectionHeader(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), CUIWnd::CUIWnd(), ClientUI::DefaultLinkColor(), DesignWnd::MainPanel::DesignNameChanged(), Networking::DiscoveryPort(), MapWnd::DispatchFleetsExploring(), ClientUI::DisplayTimestamp(), TechTreeWnd::TechTreeControls::DoButtonLayout(), ResearchWnd::DoLayout(), ProductionWnd::DoLayout(), OptionsWnd::DoneClicked(), OptionsWnd::DoubleOption(), GameRulesPanel::DoubleRuleWidget(), ClientUI::DropDownListArrowColor(), ClientUI::EditHiliteColor(), AIClientApp::EffectsProcessingThreads(), HumanClientApp::EffectsProcessingThreads(), ServerApp::EffectsProcessingThreads(), SystemIcon::EnclosingCircleDiameter(), ServerFSM::EstablishPlayer(), OptionsWnd::FileOptionImpl(), SaveFileListBox::FilterColumns(), anonymous_namespace{FleetWnd.cpp}::FleetAutoMouseoverIcon(), FleetButton::FleetButton(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FPSIndicator::FPSIndicator(), BarSizer::Get(), AIInterface::GetAIDir(), ClientUI::GetBoldFont(), SaveFileColumn::GetColumn(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), ClientUI::GetFont(), anonymous_namespace{SitRepPanel.cpp}::GetIconSize(), AIInterface::GetOptionsDBOptionBool(), AIInterface::GetOptionsDBOptionDouble(), AIInterface::GetOptionsDBOptionInt(), AIInterface::GetOptionsDBOptionStr(), anonymous_namespace{MapWnd.cpp}::GetOrderedFleetRoute(), GetResourceDir(), GetSaveDir(), GetServerSaveDir(), anonymous_namespace{MapWnd.cpp}::GetShortestRoute(), anonymous_namespace{i18n.cpp}::GetStringTableFileName(), ClientUI::GetTitleFont(), HumanClientApp::GetWindowLeftTop(), HumanClientApp::GetWindowWidthHeight(), HumanClientApp::HandleFocusChange(), ClientUI::HandleFullscreenSwitch(), EncyclopediaDetailPanel::HandleSearchTextEntered(), ClientUI::HandleSizeChange(), HumanClientApp::HandleWindowMove(), HumanClientApp::HandleWindowResize(), anonymous_namespace{SitRepPanel.cpp}::HiddenSitRepTemplateStringsFromOptions(), TechTreeWnd::HidePedia(), BuildDesignatorWnd::HidePedia(), HumanClientApp::HumanClientApp(), if(), Sound::Impl::Impl(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), ServerNetworking::Init(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), FleetDataPanel::Init(), anonymous_namespace{CUIControls.cpp}::SpeciesRow::Init(), BuildDesignatorWnd::InitializeWindows(), MapWnd::InitializeWindows(), PythonAI::InitModules(), CUIWnd::InitSizeMove(), anonymous_namespace{i18n.cpp}::InitStringtableFileName(), MapWnd::InitTurn(), MapWnd::InitVisibilityRadiiRenderingBuffers(), OptionsWnd::IntOption(), GameRulesPanel::IntRuleWidget(), CUIWnd::InvalidateUnusedOptions(), CUIWnd::InvalidateWindowOptions(), ServerApp::IsHostless(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), SitRepPanel::IsSitRepInvalid(), ClientUI::KnownTechFillColor(), ClientUI::KnownTechTextAndBorderColor(), TechTreeWnd::LayoutPanel::Layout(), FleetButton::LayoutIcons(), MapWnd::LClick(), CUIWnd::LoadOptions(), SaveFileListBox::LoadSaveGamePreviews(), HumanClientApp::LoadSinglePlayerGame(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), main(), mainConfigOptionsSetup(), mainSetupAndRun(), anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter(), ClientUI::MediumFleetButtonZoomThreshold(), ClientUI::MessageBox(), Networking::MessagePort(), SystemIcon::MouseEnter(), HumanClientApp::MultiPlayerGame(), OptionsWnd::SoundOptionsFeedback::MusicClicked(), OptionsWnd::MusicVolumeOption(), OptionsWnd::SoundOptionsFeedback::MusicVolumeSlid(), anonymous_namespace{FleetWnd.cpp}::NewFleetsAggressiveOptionSetting(), HumanClientApp::NewSinglePlayerGame(), ServerConnectWnd::OkClicked(), GalaxySetupWnd::OkClicked(), detail::PlayValueChangedSound::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ParticipantBar::ParticipantBar(), anonymous_namespace{SidePanel.cpp}::PlanetDiameter(), anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound(), anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound(), anonymous_namespace{CUIWnd.cpp}::PlayCloseSound(), anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound(), FleetButton::PlayFleetButtonOpenSound(), FleetButton::PlayFleetButtonRolloverSound(), PlayingTurn::PlayingTurn(), anonymous_namespace{CUIControls.cpp}::PlayItemDropSound(), anonymous_namespace{CUIControls.cpp}::PlayListSelectSound(), anonymous_namespace{CUIWnd.cpp}::PlayMaximizeSound(), anonymous_namespace{CUIWnd.cpp}::PlayMinimizeSound(), anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound(), Sound::Impl::PlaySound(), anonymous_namespace{SystemIcon.cpp}::PlaySounds(), anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound(), anonymous_namespace{CUIControls.cpp}::PlayTextTypingSound(), anonymous_namespace{MapWnd.cpp}::PlayTurnButtonClickSound(), anonymous_namespace{MapWnd.cpp}::PrepFullLanesToRender(), IntroScreen::PreRender(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), ClientUI::Pts(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow(), GalaxySetupPanel::RandomClicked(), MapWnd::RClick(), Idle::react(), MPLobby::react(), WaitingForMPJoinAck::react(), WaitingForSPGameJoiners::react(), PlayingTurn::react(), ProcessingTurn::react(), BuildingIndicator::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), MapWnd::RefreshDetectionIndicator(), MapWnd::RefreshFleetResourceIndicator(), MapWnd::RefreshIndustryResourceIndicator(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshSliders(), MapWnd::RefreshTradeResourceIndicator(), HumanClientApp::Reinitialize(), BuildingIndicator::Render(), RotatingPlanetControl::Render(), MapWnd::RenderFields(), MapWnd::RenderFleetMovementLines(), MapWnd::RenderGalaxyGas(), MapWnd::RenderScaleCircle(), MapWnd::RenderStarfields(), MapWnd::RenderStarlanes(), MapWnd::RenderSystems(), MapWnd::RenderVisibilityRadii(), anonymous_namespace{ClientUI.cpp}::RequiredCharsets(), ClientUI::ResearchableTechFillColor(), ClientUI::ResearchableTechTextAndBorderColor(), ResearchWnd::ResearchWnd(), CompletedDesignsListBox::ResetEmptyListPrompt(), Hotkey::ResetHotkey(), HumanClientApp::ResetOrExitApp(), OptionsWnd::ResolutionOption(), ClientUI::RolloverLinkColor(), CUIWnd::SaveDefaultedOptions(), SaveGame(), CUIWnd::SaveOptions(), ClientUI::ScrollWidth(), ServerApp::ServerApp(), ServerNetworking::ServerNetworking(), BarSizer::Set(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), CUIWnd::SetDefaultedOptions(), anonymous_namespace{HumanClientApp.cpp}::SetEmptyStringDefaultOption(), anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), anonymous_namespace{SitRepPanel.cpp}::SetHiddenSitRepTemplateStringsInOptions(), Hotkey::SetHotkey(), SetLoggerThresholds(), Sound::Impl::SetMusicVolume(), anonymous_namespace{FleetWnd.cpp}::SetNewFleetAggressiveOptionSetting(), SlotControl::SetPart(), TechTreeWnd::LayoutPanel::SetScale(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::SetShipIcon(), TechTreeWnd::SetTechStatus(), Sound::Impl::SetUISoundsVolume(), TechTreeWnd::Show(), TechTreeWnd::ShowPedia(), BuildDesignatorWnd::ShowPedia(), MapWnd::ShowProduction(), MapWnd::ShowResearch(), SystemIcon::SizeMove(), ClientUI::SmallFleetButtonZoomThreshold(), OptionsWnd::SoundOptionsFeedback::SoundEffectsEnableClicked(), OptionsWnd::SoundOptionsFeedback::SoundInitializationFailure(), ShipDesignManager::StartGame(), HumanClientApp::StartServer(), HumanClientApp::StartTurn(), ScanlineRenderer::Impl::StartUsing(), ClientUI::StatDecrColor(), ClientUI::StateButtonColor(), ClientUI::StatIncrColor(), GameRulesPanel::StringRuleWidget(), ClientUI::SystemCircleSize(), ClientUI::SystemIconSize(), ClientUI::SystemNameTextColor(), ClientUI::SystemSelectionIndicatorRPM(), ClientUI::SystemSelectionIndicatorSize(), ClientUI::SystemTinyIconSizeThreshold(), TechTreeWnd::LayoutPanel::TechPanel::TechPanel(), ClientUI::TechWndProgressBarBackgroundColor(), ClientUI::TechWndProgressBarColor(), ClientUI::TextColor(), ClientUI::TinyFleetButtonZoomThreshold(), ClientUI::TitlePts(), MapWnd::ToggleAutoEndTurn(), anonymous_namespace{MapWnd.cpp}::ToggleBoolOption(), HumanClientApp::ToggleFullscreen(), OptionsWnd::SoundOptionsFeedback::UISoundsVolumeSlid(), ClientUI::UnresearchableTechFillColor(), ClientUI::UnresearchableTechTextAndBorderColor(), SpecialsPanel::Update(), FleetDataPanel::UpdateAggressionToggle(), FPSIndicator::UpdateEnabled(), MapWnd::MapScaleLine::UpdateEnabled(), HumanClientApp::UpdateFPSLimit(), Universe::UpdateMeterEstimates(), MPLobby::ValidateClientLimits(), OptionsWnd::VolumeOption(), ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), ClientUI::WndOuterBorderColor(), and CUIWnd::~CUIWnd().
std::string ListToString (const std::vector< std::string > & input_list)
Referenced by Validator< T >::Clone(), and Validator< std::vector< std::string > >::String().
bool RegisterOptions (OptionsDBFn function)
adds function to a vector of pointers to functions that add Options to the OptionsDB.
This function returns a boolean so that it can be used to declare a dummy static variable that causes function to be registered as a side effect (e.g. at file scope: "bool unused_bool = RegisterOption(&foo)").
References anonymous_namespace{OptionsDB.cpp}::OptionsRegistry().
Referenced by mainSetupAndRun().
std::vector<std::string> StringToList (const std::string & input_string)
Referenced by anonymous_namespace{SaveFileDialog.cpp}::AddOptions(), Validator< T >::Clone(), and Validator< std::vector< std::string > >::Validate().