FreeOrion: PopCenter.cpp File Reference
PopCenter.cpp File Reference
#include "PopCenter.h"
#include <algorithm>
#include <stdexcept>
#include "Enums.h"
#include "Meter.h"
#include "UniverseObject.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
Namespaces
anonymous_namespace{PopCenter.cpp}
Functions
const Species * GetSpecies (const std::string &name)
Variables
const double anonymous_namespace{PopCenter.cpp}::MINIMUM_POP_CENTER_POPULATION = 0.01001
Function Documentation
GetSpecies()
const Species* GetSpecies (const std::string & name)
Referenced by AutomaticallyChosenColonyShip(), Planet::AvailableFoci(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), Planet::Colonize(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Planet::EnvironmentForSpecies(), ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetSpecies::Execute(), Effect::CreateShip::Execute(), Planet::FocusIcon(), Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Planet::HasTag(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), HumanClientApp::NewSinglePlayerGame(), Planet::NextBetterPlanetTypeForSpecies(), Condition::anonymous_namespace{Conditions.cpp}::HomeworldSimpleMatch::operator()(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), ShipDesign::ProductionLocation(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), MapWnd::RefreshPopulationIndicator(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), PopCenter::SetSpecies(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment(), ClientUI::SpeciesIcon(), anonymous_namespace{ServerWrapper.cpp}::SpeciesPreferredFocus(), anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition(), Planet::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToSpecies().