FreeOrion: PythonBase.cpp File Reference
PythonBase.cpp File Reference
#include "PythonBase.h"
#include "../util/Directories.h"
#include "../util/Logger.h"
#include "CommonWrappers.h"
#include <boost/filesystem.hpp>
#include <boost/python/tuple.hpp>
#include <boost/python/list.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/docstring_options.hpp>
Functions
BOOST_PYTHON_MODULE (freeorion_logger)
const std::string GetPythonCommonDir ()
const std::string GetPythonDir ()
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (freeorion_logger)
References FreeOrionPython::WrapLogger().
GetPythonCommonDir()
const std::string GetPythonCommonDir ()
References GetPythonDir().
Referenced by PythonBase::Initialize().
GetPythonDir()
const std::string GetPythonDir ()
References GetResourceDir().
Referenced by GetPythonAuthDir(), GetPythonChatDir(), GetPythonCommonDir(), GetPythonTurnEventsDir(), and GetPythonUniverseGeneratorDir().