FreeOrion: Random.h File Reference
Random.h File Reference
A collection of robust and portable random number generation functors and functions.
#include <boost/random/mersenne_twister.hpp>
#include <boost/random/uniform_smallint.hpp>
#include <boost/random/uniform_int.hpp>
#include <boost/random/uniform_01.hpp>
#include <boost/random/uniform_real.hpp>
#include <boost/random/normal_distribution.hpp>
#include <boost/random/variate_generator.hpp>
#include <ctime>
#include "Export.h"
Typedefs
typedef boost::variate_generator< GeneratorType &, boost::uniform_real<> > DoubleDistType
typedef boost::variate_generator< GeneratorType &, boost::normal_distribution<> > GaussianDistType
typedef boost::mt19937 GeneratorType
typedef boost::variate_generator< GeneratorType &, boost::uniform_int<> > IntDistType
typedef boost::variate_generator< GeneratorType &, boost::uniform_smallint<> > SmallIntDistType
Functions
FO_COMMON_API void ClockSeed ()
seeds the underlying random number generator used to drive all random number distributions with the current clock time
FO_COMMON_API DoubleDistType DoubleDist (double min, double max)
returns a functor that provides a uniform distribution of doubles in the range [min, max)
FO_COMMON_API GaussianDistType GaussianDist (double mean, double sigma)
returns a functor that provides a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
IntDistType IntDist (int min, int max)
returns a functor that provides a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, SmallIntDist() may be used instead
FO_COMMON_API double RandDouble (double min, double max)
returns a double from a uniform distribution of doubles in the range [min, max)
FO_COMMON_API double RandGaussian (double mean, double sigma)
returns a double from a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
FO_COMMON_API int RandInt (int min, int max)
returns an int from a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, RandSmallInt() may be used instead
FO_COMMON_API int RandSmallInt (int min, int max)
returns an int from a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use RandInt() instead
FO_COMMON_API double RandZeroToOne ()
returns a double from a uniform distribution of doubles in the range [0.0, 1.0)
FO_COMMON_API void Seed (unsigned int seed)
seeds the underlying random number generator used to drive all random number distributions
FO_COMMON_API SmallIntDistType SmallIntDist (int min, int max)
returns a functor that provides a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use IntDist() instead
Detailed Description
A collection of robust and portable random number generation functors and functions.
If you need to generate one or two random numbers, prefer the functions (e.g. RandomInt()).
If you need to generate a large volume of random numbers with the same parameterization, generate a functor (e.g. with a call to IntDist()) and then call the functor repeatedly to generate the numbers. This eliminates the overhead associated with repeatedly contructing distributions, when you call the Random*() functions.
Typedef Documentation
DoubleDistType
typedef boost::variate_generator<GeneratorType&, boost::uniform_real<> > DoubleDistType
GaussianDistType
typedef boost::variate_generator<GeneratorType&, boost::normal_distribution<> > GaussianDistType
GeneratorType
typedef boost::mt19937 GeneratorType
IntDistType
typedef boost::variate_generator<GeneratorType&, boost::uniform_int<> > IntDistType
SmallIntDistType
typedef boost::variate_generator<GeneratorType&, boost::uniform_smallint<> > SmallIntDistType
Function Documentation
ClockSeed()
FO_COMMON_API void ClockSeed ()
seeds the underlying random number generator used to drive all random number distributions with the current clock time
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by ServerApp::GenerateUniverse(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), and GalaxySetupData::SetSeed().
DoubleDist()
FO_COMMON_API DoubleDistType DoubleDist (double min, double max)
returns a functor that provides a uniform distribution of doubles in the range [min, max)
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandDouble(), and RandZeroToOne().
GaussianDist()
FO_COMMON_API GaussianDistType GaussianDist (double mean, double sigma)
returns a functor that provides a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandGaussian().
IntDist()
IntDistType IntDist (int min, int max)
returns a functor that provides a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, SmallIntDist() may be used instead
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandInt().
RandDouble()
FO_COMMON_API double RandDouble (double min, double max)
returns a double from a uniform distribution of doubles in the range [min, max)
References DoubleDist().
Referenced by ValueRef::Operation< T >::EvalImpl(), and MapWnd::RenderStarfields().
RandGaussian()
FO_COMMON_API double RandGaussian (double mean, double sigma)
returns a double from a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
References GaussianDist().
Referenced by Planet::Planet(), and MapWnd::RenderStarfields().
RandInt()
FO_COMMON_API int RandInt (int min, int max)
returns an int from a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, RandSmallInt() may be used instead
References IntDist().
Referenced by ValueRef::Operation< T >::EvalImpl(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::GetShuffledValidAttackerIDs(), and anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons().
RandSmallInt()
FO_COMMON_API int RandSmallInt (int min, int max)
returns an int from a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use RandInt() instead
References SmallIntDist().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::CustomRandInt(), ValueRef::ComplexVariable< T >::Eval(), ValueRef::Operation< T >::EvalImpl(), Effect::CreateSystem::Execute(), Effect::SetDestination::Execute(), anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), AIClientApp::HandleMessage(), NewMonsterName(), Empire::NewShipName(), SpeciesManager::RandomPlayableSpeciesName(), SpeciesManager::RandomSpeciesName(), RotatingPlanetControl::Refresh(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), and GalaxySetupData::SetSeed().
RandZeroToOne()
FO_COMMON_API double RandZeroToOne ()
returns a double from a uniform distribution of doubles in the range [0.0, 1.0)
References DoubleDist().
Referenced by InitEmpires(), Condition::Chance::Match(), Condition::anonymous_namespace{Conditions.cpp}::ChanceSimpleMatch::operator()(), Planet::Planet(), MapWnd::RenderStarfields(), Planet::SetHighAxialTilt(), and SetNativePopulationValues().
Seed()
FO_COMMON_API void Seed (unsigned int seed)
seeds the underlying random number generator used to drive all random number distributions
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
SmallIntDist()
FO_COMMON_API SmallIntDistType SmallIntDist (int min, int max)
returns a functor that provides a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use IntDist() instead
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by IDAllocator::ObfuscateBeforeSerialization(), ClientUI::PrefixedTexturesAndDist(), and RandSmallInt().