FreeOrion: Random.cpp File Reference
Random.cpp File Reference
#include "Random.h"
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/thread/mutex.hpp>
Namespaces
anonymous_namespace{Random.cpp}
Functions
void ClockSeed ()
seeds the underlying random number generator used to drive all random number distributions with the current clock time
DoubleDistType DoubleDist (double min, double max)
returns a functor that provides a uniform distribution of doubles in the range [min, max)
GaussianDistType GaussianDist (double mean, double sigma)
returns a functor that provides a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
IntDistType IntDist (int min, int max)
returns a functor that provides a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, SmallIntDist() may be used instead
double RandDouble (double min, double max)
returns a double from a uniform distribution of doubles in the range [min, max)
double RandGaussian (double mean, double sigma)
returns a double from a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
int RandInt (int min, int max)
returns an int from a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, RandSmallInt() may be used instead
int RandSmallInt (int min, int max)
returns an int from a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use RandInt() instead
double RandZeroToOne ()
returns a double from a uniform distribution of doubles in the range [0.0, 1.0)
void Seed (unsigned int seed)
seeds the underlying random number generator used to drive all random number distributions
SmallIntDistType SmallIntDist (int min, int max)
returns a functor that provides a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use IntDist() instead
Variables
GeneratorType anonymous_namespace{Random.cpp}::gen
static boost::mutex anonymous_namespace{Random.cpp}::s_prng_mutex
Function Documentation
ClockSeed()
void ClockSeed ()
seeds the underlying random number generator used to drive all random number distributions with the current clock time
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by ServerApp::GenerateUniverse(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), and GalaxySetupData::SetSeed().
DoubleDist()
DoubleDistType DoubleDist (double min, double max)
returns a functor that provides a uniform distribution of doubles in the range [min, max)
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandDouble(), and RandZeroToOne().
GaussianDist()
GaussianDistType GaussianDist (double mean, double sigma)
returns a functor that provides a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandGaussian().
IntDist()
IntDistType IntDist (int min, int max)
returns a functor that provides a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, SmallIntDist() may be used instead
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by RandInt().
RandDouble()
double RandDouble (double min, double max)
returns a double from a uniform distribution of doubles in the range [min, max)
References DoubleDist().
Referenced by ValueRef::Operation< T >::EvalImpl(), and MapWnd::RenderStarfields().
RandGaussian()
double RandGaussian (double mean, double sigma)
returns a double from a Gaussian (normal) distribution of doubles centered around mean, with standard deviation sigma
References GaussianDist().
Referenced by Planet::Planet(), and MapWnd::RenderStarfields().
RandInt()
int RandInt (int min, int max)
returns an int from a uniform distribution of integers in the range [min, max]; if the integers desired are smaller than 10000, RandSmallInt() may be used instead
References IntDist().
Referenced by ValueRef::Operation< T >::EvalImpl(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::GetShuffledValidAttackerIDs(), and anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons().
RandSmallInt()
int RandSmallInt (int min, int max)
returns an int from a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use RandInt() instead
References SmallIntDist().
Referenced by Condition::anonymous_namespace{Conditions.cpp}::CustomRandInt(), ValueRef::ComplexVariable< T >::Eval(), ValueRef::Operation< T >::EvalImpl(), Effect::CreateSystem::Execute(), Effect::SetDestination::Execute(), anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), AIClientApp::HandleMessage(), NewMonsterName(), Empire::NewShipName(), SpeciesManager::RandomPlayableSpeciesName(), SpeciesManager::RandomSpeciesName(), RotatingPlanetControl::Refresh(), SidePanel::PlanetPanel::RefreshPlanetGraphic(), and GalaxySetupData::SetSeed().
RandZeroToOne()
double RandZeroToOne ()
returns a double from a uniform distribution of doubles in the range [0.0, 1.0)
References DoubleDist().
Referenced by InitEmpires(), Condition::Chance::Match(), Condition::anonymous_namespace{Conditions.cpp}::ChanceSimpleMatch::operator()(), Planet::Planet(), MapWnd::RenderStarfields(), Planet::SetHighAxialTilt(), and SetNativePopulationValues().
Seed()
void Seed (unsigned int seed)
seeds the underlying random number generator used to drive all random number distributions
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by AutoResolveCombat(), anonymous_namespace{ServerApp.cpp}::EnemyId(), ServerApp::GenerateUniverse(), AIClientApp::HandleMessage(), ServerApp::PostCombatProcessTurns(), Idle::react(), MPLobby::react(), and MapWnd::RenderStarfields().
SmallIntDist()
SmallIntDistType SmallIntDist (int min, int max)
returns a functor that provides a uniform distribution of small integers in the range [min, max]; if the integers desired are larger than 10000, use IntDist() instead
References anonymous_namespace{Random.cpp}::gen, and anonymous_namespace{Random.cpp}::s_prng_mutex.
Referenced by IDAllocator::ObfuscateBeforeSerialization(), ClientUI::PrefixedTexturesAndDist(), and RandSmallInt().