FreeOrion: ResourcePool.cpp File Reference
ResourcePool.cpp File Reference
#include "ResourcePool.h"
#include <cassert>
#include <boost/lexical_cast.hpp>
#include "../universe/Enums.h"
#include "../universe/ObjectMap.h"
#include "../universe/Planet.h"
#include "../util/AppInterface.h"
#include "../util/Logger.h"
Functions
ResourceType MeterToResource (MeterType type)
Returns the equivalent resource type for the given meter type; if no such resource type exists, returns INVALID_RESOURCE_TYPE.
MeterType ResourceToMeter (ResourceType type)
MeterType ResourceToTargetMeter (ResourceType type)
Function Documentation
MeterToResource()
ResourceType MeterToResource (MeterType type)
Returns the equivalent resource type for the given meter type; if no such resource type exists, returns INVALID_RESOURCE_TYPE.
Referenced by SidePanel::RefreshImpl().
ResourceToMeter()
MeterType ResourceToMeter (ResourceType type)
Referenced by Fleet::ResourceOutput(), ResourcePool::Update(), and SystemResourceSummaryBrowseWnd::UpdateProduction().
ResourceToTargetMeter()
MeterType ResourceToTargetMeter (ResourceType type)
Referenced by ResourcePool::Update().