FreeOrion: SaveGamePreviewUtils.h File Reference
SaveGamePreviewUtils.h File Reference
#include <vector>
#include <string>
#include <boost/serialization/version.hpp>
#include <GG/Clr.h>
#include "MultiplayerCommon.h"
#include "Export.h"
#include "Serialize.h"
Classes
struct FullPreview
Stores all aggregated information about a save file.
struct PreviewInformation
The preview information the server sends to the client.
struct SaveGamePreviewData
Contains preview information about a savegame.
Functions
BOOST_CLASS_VERSION (SaveGamePreviewData, 4)
FO_COMMON_API std::string ColumnInPreview (const FullPreview &full, const std::string &name, bool thin=true)
Get the value of column name in this preview.
FO_COMMON_API void LoadSaveGamePreviews (const boost::filesystem::path &path, const std::string &extension, std::vector< FullPreview > &previews)
Load previews from files.
FO_COMMON_API bool SaveFileWithValidHeader (const boost::filesystem::path &path)
Attempts to load headers of a save file.
Function Documentation
BOOST_CLASS_VERSION()
BOOST_CLASS_VERSION (SaveGamePreviewData , 4)
ColumnInPreview()
FO_COMMON_API std::string ColumnInPreview (const FullPreview & full, const std::string & name, bool thin = true)
Get the value of column name in this preview.
Parameters
full FullPreview to match for column name
name The name of the column
thin If true, tries to make the value less wide
References SaveGamePreviewData::current_turn, ErrorLogger, FullPreview::filename, FullPreview::galaxy, GalaxySetupData::m_age, GalaxySetupData::m_ai_aggr, GalaxySetupData::m_monster_freq, GalaxySetupData::m_native_freq, GalaxySetupData::m_planet_density, GalaxySetupData::m_seed, GalaxySetupData::m_shape, GalaxySetupData::m_size, GalaxySetupData::m_specials_freq, GalaxySetupData::m_starlane_freq, SaveGamePreviewData::main_player_empire_name, SaveGamePreviewData::main_player_name, SaveGamePreviewData::number_of_empires, SaveGamePreviewData::number_of_human_players, FullPreview::preview, SaveGamePreviewData::save_time, anonymous_namespace{SaveGamePreviewUtils.cpp}::split_time(), TextForAIAggression(), TextForGalaxySetupSetting(), TextForGalaxyShape(), and to_string().
Referenced by SaveFileColumn::CellForColumn(), and SaveFileFileRow::Init().
LoadSaveGamePreviews()
FO_COMMON_API void LoadSaveGamePreviews (const boost::filesystem::path & path, const std::string & extension, std::vector< FullPreview > & previews)
Load previews from files.
Parameters
path Directory where to look for files
extension File name extension to filter by
[out] previews The previews will be put here
SaveFileWithValidHeader()
FO_COMMON_API bool SaveFileWithValidHeader (const boost::filesystem::path & path)
Attempts to load headers of a save file.
Returns true on success, false if header data could not be loaded
Parameters
path Filename to load headers of
References DebugLogger, ErrorLogger, SaveGamePreviewData::save_format_marker, and anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_COMPRESSED_MARKER().
Referenced by anonymous_namespace{HumanClientApp.cpp}::NewestSinglePlayerSavegame().