FreeOrion: SaveLoad.cpp File Reference
SaveLoad.cpp File Reference
#include "SaveLoad.h"
#include "ServerApp.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../universe/Building.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/Planet.h"
#include "../universe/ShipDesign.h"
#include "../universe/System.h"
#include "../universe/Species.h"
#include "../util/Directories.h"
#include "../util/base64_filter.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/Order.h"
#include "../util/OrderSet.h"
#include "../util/SaveGamePreviewUtils.h"
#include "../util/Serialize.h"
#include "../util/ScopedTimer.h"
#include "../combat/CombatLogManager.h"
#include <boost/filesystem/fstream.hpp>
#include <boost/serialization/deque.hpp>
#include <boost/serialization/list.hpp>
#include <boost/serialization/map.hpp>
#include <boost/serialization/set.hpp>
#include <boost/serialization/vector.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/iostreams/filter/zlib.hpp>
#include <boost/iostreams/filtering_streambuf.hpp>
#include <boost/iostreams/copy.hpp>
#include <boost/iostreams/device/back_inserter.hpp>
#include <boost/iostreams/stream.hpp>
#include <boost/thread.hpp>
#include <boost/serialization/shared_ptr.hpp>
Namespaces
anonymous_namespace{SaveLoad.cpp}
Functions
const std::string anonymous_namespace{SaveLoad.cpp}::BINARY_MARKER ("binary")
std::map< int, SaveGameEmpireData > CompileSaveGameEmpireData ()
Prepared empire data for save game or lobby.
void anonymous_namespace{SaveLoad.cpp}::CompileSaveGamePreviewData (const ServerSaveGameData &server_save_game_data, const std::vector< PlayerSaveGameData > &player_save_game_data, const std::map< int, SaveGameEmpireData > &empire_save_game_data, SaveGamePreviewData &preview)
void LoadEmpireSaveGameData (const std::string &filename, std::map< int, SaveGameEmpireData > &empire_save_game_data, std::vector< PlayerSaveHeaderData > &player_save_header_data, GalaxySetupData &galaxy_setup_data, int &current_turn)
Loads from a savefile filename some basic empire information that is useful when selecting which player will control which empire when reloading a saved game: player name, empire name, and empire colour (and empire id).
void LoadGalaxySetupData (const std::string &filename, GalaxySetupData &galaxy_setup_data)
void LoadGame (const std::string &filename, ServerSaveGameData &server_save_game_data, std::vector< PlayerSaveGameData > &player_save_game_data, Universe &universe, EmpireManager &empire_manager, SpeciesManager &species_manager, CombatLogManager &combat_log_manager, GalaxySetupData &galaxy_setup_data)
Loads the indicated data from savefile filename.
void LoadPlayerSaveHeaderData (const std::string &filename, std::vector< PlayerSaveHeaderData > &player_save_header_data)
Loads from a savefile filename some basic info about players in the save that is needed when resuming the game.
int SaveGame (const std::string &filename, const ServerSaveGameData &server_save_game_data, const std::vector< PlayerSaveGameData > &player_save_game_data, const Universe &universe, const EmpireManager &empire_manager, const SpeciesManager &species_manager, const CombatLogManager &combat_log_manager, const GalaxySetupData &galaxy_setup_data, bool multiplayer)
Saves the provided data to savefile filename.
const std::string anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE ("Unable to open file")
const std::string anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_BASE64_MARKER ("zb64-xml")
const std::string anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_MARKER ("zlib-xml")
const std::string anonymous_namespace{SaveLoad.cpp}::XML_DIRECT_MARKER ("raw-xml")
Function Documentation
CompileSaveGameEmpireData()
std::map<int, SaveGameEmpireData> CompileSaveGameEmpireData ()
Prepared empire data for save game or lobby.
References Empires().
Referenced by SaveGame(), and ServerFSM::UpdateIngameLobby().
LoadEmpireSaveGameData()
void LoadEmpireSaveGameData (const std::string & filename, std::map< int, SaveGameEmpireData > & empire_save_game_data, std::vector< PlayerSaveHeaderData > & player_save_header_data, GalaxySetupData & galaxy_setup_data, int & current_turn)
Loads from a savefile filename some basic empire information that is useful when selecting which player will control which empire when reloading a saved game: player name, empire name, and empire colour (and empire id).
Also loads galaxy setup data to show it in lobby window.
References DebugLogger, ErrorLogger, FilenameToPath(), GalaxySetupData::m_age, GalaxySetupData::m_ai_aggr, ServerSaveGameData::m_current_turn, GalaxySetupData::m_game_rules, GalaxySetupData::m_game_uid, GalaxySetupData::m_monster_freq, GalaxySetupData::m_native_freq, GalaxySetupData::m_planet_density, GalaxySetupData::m_seed, GalaxySetupData::m_shape, GalaxySetupData::m_size, GalaxySetupData::m_specials_freq, GalaxySetupData::m_starlane_freq, anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE(), and UserString().
Referenced by MPLobby::react().
LoadGalaxySetupData()
void LoadGalaxySetupData (const std::string & filename, GalaxySetupData & galaxy_setup_data)
References DebugLogger, ErrorLogger, FilenameToPath(), and anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE().
LoadGame()
void LoadGame (const std::string & filename, ServerSaveGameData & server_save_game_data, std::vector< PlayerSaveGameData > & player_save_game_data, Universe & universe, EmpireManager & empire_manager, SpeciesManager & species_manager, CombatLogManager & combat_log_manager, GalaxySetupData & galaxy_setup_data)
Loads the indicated data from savefile filename.
References ALL_EMPIRES, EmpireManager::Clear(), Universe::Clear(), SaveGamePreviewData::compressed_text_size, DebugLogger, Deserialize(), Universe::EncodingEmpire(), ErrorLogger, FilenameToPath(), ServerApp::GetApp(), GetUniverse(), Message::LOADING_GAME, SaveGamePreviewData::save_format_marker, TurnProgressMessage(), anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE(), SaveGamePreviewData::uncompressed_text_size, anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_BASE64_MARKER(), anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_MARKER(), and anonymous_namespace{SaveLoad.cpp}::XML_DIRECT_MARKER().
Referenced by Idle::react(), MPLobby::react(), and WaitingForSPGameJoiners::react().
LoadPlayerSaveHeaderData()
void LoadPlayerSaveHeaderData (const std::string & filename, std::vector< PlayerSaveHeaderData > & player_save_header_data)
Loads from a savefile filename some basic info about players in the save that is needed when resuming the game.
References DebugLogger, ErrorLogger, FilenameToPath(), anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE(), and UserString().
Referenced by anonymous_namespace{ServerFSM.cpp}::GetHostNameFromSinglePlayerSetupData(), and WaitingForSPGameJoiners::WaitingForSPGameJoiners().
SaveGame()
int SaveGame (const std::string & filename, const ServerSaveGameData & server_save_game_data, const std::vector< PlayerSaveGameData > & player_save_game_data, const Universe & universe, const EmpireManager & empire_manager, const SpeciesManager & species_manager, const CombatLogManager & combat_log_manager, const GalaxySetupData & galaxy_setup_data, bool multiplayer)
Saves the provided data to savefile filename.
References ALL_EMPIRES, anonymous_namespace{SaveLoad.cpp}::BINARY_MARKER(), CompileSaveGameEmpireData(), anonymous_namespace{SaveLoad.cpp}::CompileSaveGamePreviewData(), SaveGamePreviewData::compressed_text_size, DebugLogger, Universe::EncodingEmpire(), SectionedScopedTimer::EnterSection(), ErrorLogger, FilenameToPath(), OptionsDB::Get(), GetOptionsDB(), GetSaveDir(), GetServerSaveDir(), GetUniverse(), IsInDir(), SaveGamePreviewData::save_format_marker, Serialize(), SaveGamePreviewData::SetBinary(), anonymous_namespace{SaveLoad.cpp}::UNABLE_TO_OPEN_FILE(), SaveGamePreviewData::uncompressed_text_size, UserString(), WarnLogger, anonymous_namespace{SaveLoad.cpp}::XML_COMPRESSED_BASE64_MARKER(), and anonymous_namespace{SaveLoad.cpp}::XML_DIRECT_MARKER().
Referenced by ServerFSM::HandleNonLobbyDisconnection(), PlayingGame::react(), and WaitingForTurnEnd::react().