FreeOrion: SaveGamePreviewUtils.cpp File Reference
SaveGamePreviewUtils.cpp File Reference
#include "OptionsDB.h"
#include "SaveGamePreviewUtils.h"
#include "i18n.h"
#include "Directories.h"
#include "Logger.h"
#include "Serialize.h"
#include "Serialize.ipp"
#include "ScopedTimer.h"
#include <boost/filesystem.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <boost/graph/graph_concepts.hpp>
#include <boost/iostreams/filter/zlib.hpp>
#include <boost/iostreams/filtering_streambuf.hpp>
#include <boost/iostreams/copy.hpp>
#include <boost/iostreams/device/back_inserter.hpp>
#include <boost/iostreams/stream.hpp>
#include <fstream>
Namespaces
anonymous_namespace{SaveGamePreviewUtils.cpp}
Functions
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::BIN_SAVE_FILE_DESCRIPTION ("This is binary archive FreeOrion saved game.")
std::string ColumnInPreview (const FullPreview &full, const std::string &name, bool thin)
Get the value of column name in this preview.
bool anonymous_namespace{SaveGamePreviewUtils.cpp}::LoadSaveGamePreviewData (const fs::path &path, FullPreview &full)
Populates a SaveGamePreviewData from a given file returns true on success, false if preview data could not be found.
void LoadSaveGamePreviews (const fs::path &orig_path, const std::string &extension, std::vector< FullPreview > &previews)
bool SaveFileWithValidHeader (const boost::filesystem::path &path)
Attempts to load headers of a save file.
std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::split_time (const std::string &time)
Splits time and date on separate lines for an ISO datetime string.
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::UNABLE_TO_OPEN_FILE ("Unable to open file")
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_COMPRESSED_MARKER ("zlib-xml")
const std::string anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_SAVE_FILE_DESCRIPTION ("This is an XML archive FreeOrion saved game. Initial header information is uncompressed. The main gamestate information follows, possibly stored as zlib-comprssed XML archive in the last entry in the main archive.")
Function Documentation
ColumnInPreview()
std::string ColumnInPreview (const FullPreview & full, const std::string & name, bool thin = true)
Get the value of column name in this preview.
Parameters
full FullPreview to match for column name
name The name of the column
thin If true, tries to make the value less wide
References GalaxySetupData::age, GalaxySetupData::ai_aggr, SaveGamePreviewData::current_turn, ErrorLogger, FullPreview::filename, FullPreview::galaxy, SaveGamePreviewData::main_player_empire_name, SaveGamePreviewData::main_player_name, GalaxySetupData::monster_freq, GalaxySetupData::native_freq, SaveGamePreviewData::number_of_empires, SaveGamePreviewData::number_of_human_players, GalaxySetupData::planet_density, FullPreview::preview, SaveGamePreviewData::save_time, GalaxySetupData::seed, GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, anonymous_namespace{SaveGamePreviewUtils.cpp}::split_time(), GalaxySetupData::starlane_freq, TextForAIAggression(), TextForGalaxySetupSetting(), TextForGalaxyShape(), and to_string().
Referenced by SaveFileColumn::CellForColumn(), and SaveFileFileRow::Init().
LoadSaveGamePreviews()
void LoadSaveGamePreviews (const fs::path & orig_path, const std::string & extension, std::vector< FullPreview > & previews)
References ErrorLogger, and anonymous_namespace{SaveGamePreviewUtils.cpp}::LoadSaveGamePreviewData().
Referenced by SaveFileListBox::LoadLocalSaveGamePreviews(), and ServerApp::UpdateSavePreviews().
SaveFileWithValidHeader()
bool SaveFileWithValidHeader (const boost::filesystem::path & path)
Attempts to load headers of a save file.
Returns true on success, false if header data could not be loaded
Parameters
path Filename to load headers of
References DebugLogger, ErrorLogger, SaveGamePreviewData::save_format_marker, and anonymous_namespace{SaveGamePreviewUtils.cpp}::XML_COMPRESSED_MARKER().
Referenced by anonymous_namespace{GGHumanClientApp.cpp}::NewestSinglePlayerSavegame().