FreeOrion: SerializeUniverse.cpp File Reference
SerializeUniverse.cpp File Reference
#include "Serialize.h"
#include "Logger.h"
#include "Serialize.ipp"
#include "../universe/IDAllocator.h"
#include "../universe/Building.h"
#include "../universe/Enums.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/Planet.h"
#include "../universe/ShipDesign.h"
#include "../universe/Species.h"
#include "../universe/System.h"
#include "../universe/Field.h"
#include "../universe/Universe.h"
#include "ScopedTimer.h"
#include "AppInterface.h"
#include "OptionsDB.h"
#include <boost/lexical_cast.hpp>
#include <boost/uuid/nil_generator.hpp>
Namespaces
boost
In Boost 1.66, io_service was replaced with a typedef of io_context.
boost::serialization
Functions
template<typename Archive >
void Deserialize (Archive &ia, Universe &universe)
Deserialize universe from input archive ia.
template<typename Archive >
void Deserialize (Archive &ia, std::map< int, std::shared_ptr< UniverseObject >> &objects)
Deserialize object_map from input archive ia.
template FO_COMMON_API void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &ia, Universe &universe)
template void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &ia, std::map< int, std::shared_ptr< UniverseObject >> &objects)
template FO_COMMON_API void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &ia, Universe &universe)
template void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &ia, std::map< int, std::shared_ptr< UniverseObject >> &objects)
template<class Archive , class Key , class Value >
void boost::serialization::load (Archive &ar, flat_map< Key, Value > &m, const unsigned int)
template<typename Archive >
void load_construct_data (Archive &ar, System *obj, unsigned int const version)
template<typename Archive >
void load_construct_data (Archive &ar, Field *obj, unsigned int const version)
template<typename Archive >
void load_construct_data (Archive &ar, Planet *obj, unsigned int const version)
template<typename Archive >
void load_construct_data (Archive &ar, Building *obj, unsigned int const version)
template<typename Archive >
void load_construct_data (Archive &ar, Fleet *obj, unsigned int const version)
template<class Archive , class Key , class Value >
void boost::serialization::save (Archive &ar, const flat_map< Key, Value > &m, const unsigned int)
template<typename Archive >
void serialize (Archive &ar, PopCenter &p, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, ResourceCenter &rs, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, ObjectMap &objmap, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Universe &u, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, UniverseObject &o, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, System &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Field &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Planet &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Building &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Fleet &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, Ship &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, ShipDesign &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SpeciesManager &sm, unsigned int const version)
template<typename Archive >
void Serialize (Archive &oa, const Universe &universe)
Serialize universe to output archive oa.
template<typename Archive >
void Serialize (Archive &oa, const std::map< int, std::shared_ptr< UniverseObject >> &objects)
Serialize object_map to output archive oa.
template<class Archive , class Key , class Value >
void boost::serialization::serialize (Archive &ar, flat_map< Key, Value > &m, const unsigned int file_version)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PopCenter &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, ResourceCenter &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &ar, System &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SpeciesManager &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PopCenter &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, ResourceCenter &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &ar, System &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &oa, const Universe &universe)
template void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &oa, const std::map< int, std::shared_ptr< UniverseObject >> &objects)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PopCenter &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, ResourceCenter &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &ar, System &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SpeciesManager &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PopCenter &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, ResourceCenter &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &ar, System &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &oa, const Universe &universe)
template void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &oa, const std::map< int, std::shared_ptr< UniverseObject >> &objects)
Function Documentation
Deserialize() [1/2]
template<typename Archive > void Deserialize (Archive & ia, Universe & universe)
Deserialize universe from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), Deserialize< freeorion_xml_iarchive >(), and FO_COMMON_API.
Referenced by ExtractGameStartMessageData(), ExtractTurnOrdersMessageData(), ExtractTurnPartialOrdersMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnUpdateMessageData(), and LoadGame().
Deserialize() [2/2]
template<typename Archive > void Deserialize (Archive & ia, std::map< int, std::shared_ptr< UniverseObject >> & objects)
Deserialize object_map from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), and Deserialize< freeorion_xml_iarchive >().
Deserialize< freeorion_bin_iarchive >() [1/2]
template FO_COMMON_API void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & ia, Universe & universe)
Referenced by Deserialize().
Deserialize< freeorion_bin_iarchive >() [2/2]
template void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & ia, std::map< int, std::shared_ptr< UniverseObject >> & objects)
Deserialize< freeorion_xml_iarchive >() [1/2]
template FO_COMMON_API void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & ia, Universe & universe)
Referenced by Deserialize().
Deserialize< freeorion_xml_iarchive >() [2/2]
template void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & ia, std::map< int, std::shared_ptr< UniverseObject >> & objects)
load_construct_data() [1/5]
template<typename Archive > void load_construct_data (Archive & ar, System * obj, unsigned int const version)
load_construct_data() [2/5]
template<typename Archive > void load_construct_data (Archive & ar, Field * obj, unsigned int const version)
load_construct_data() [3/5]
template<typename Archive > void load_construct_data (Archive & ar, Planet * obj, unsigned int const version)
load_construct_data() [4/5]
template<typename Archive > void load_construct_data (Archive & ar, Building * obj, unsigned int const version)
References ALL_EMPIRES.
load_construct_data() [5/5]
template<typename Archive > void load_construct_data (Archive & ar, Fleet * obj, unsigned int const version)
References ALL_EMPIRES.
serialize() [1/13]
template<typename Archive > void serialize (Archive & ar, PopCenter & p, unsigned int const version)
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [2/13]
template<typename Archive > void serialize (Archive & ar, ResourceCenter & rs, unsigned int const version)
References ResourceCenter::m_focus, ResourceCenter::m_focus_turn_initial, ResourceCenter::m_last_turn_focus_changed, ResourceCenter::m_last_turn_focus_changed_turn_initial, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [3/13]
template<typename Archive > void serialize (Archive & ar, ObjectMap & objmap, unsigned int const version)
References ObjectMap::CopyObjectsToSpecializedMaps(), and ObjectMap::m_objects.
serialize() [4/13]
template<typename Archive > void serialize (Archive & ar, Universe & u, unsigned int const version)
References ALL_EMPIRES, BOOST_CLASS_VERSION(), Universe::Clear(), DebugLogger, SectionedScopedTimer::EnterSection(), Universe::GetDestroyedObjectsToSerialize(), Universe::GetEmpireKnownDestroyedObjects(), Universe::GetEmpireKnownObjectsToSerialize(), Universe::GetEmpireObjectVisibilityMap(), Universe::GetEmpireObjectVisibilityTurnMap(), Universe::GetEmpireStaleKnowledgeObjects(), Universe::GetObjectsToSerialize(), GetOptionsDB(), Universe::GetShipDesignsToSerialize(), GlobalSerializationEncodingForEmpire(), Universe::m_design_id_allocator, Universe::m_destroyed_object_ids, Universe::m_empire_known_destroyed_object_ids, Universe::m_empire_known_ship_design_ids, Universe::m_empire_latest_known_objects, Universe::m_empire_object_visibility, Universe::m_empire_object_visibility_turns, Universe::m_empire_stale_knowledge_object_ids, Universe::m_object_id_allocator, Universe::m_objects, Universe::m_ship_designs, Universe::m_stat_records, Universe::m_universe_width, Universe::ResetAllIDAllocation(), and parse::ship_designs().
serialize() [5/13]
template<typename Archive > void serialize (Archive & ar, UniverseObject & o, unsigned int const version)
serialize() [6/13]
template<typename Archive > void serialize (Archive & ar, System & obj, unsigned int const version)
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [7/13]
template<typename Archive > void serialize (Archive & ar, Field & obj, unsigned int const version)
References Field::m_type_name.
serialize() [8/13]
template<typename Archive > void serialize (Archive & ar, Planet & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), CurrentTurn(), anonymous_namespace{CUIWnd.cpp}::dummy, and INVALID_GAME_TURN.
serialize() [9/13]
template<typename Archive > void serialize (Archive & ar, Building & obj, unsigned int const version)
References Building::m_building_type, Building::m_ordered_scrapped, Building::m_planet_id, and Building::m_produced_by_empire_id.
serialize() [10/13]
template<typename Archive > void serialize (Archive & ar, Fleet & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), Fleet::m_aggression, Fleet::m_arrival_starlane, Fleet::m_arrived_this_turn, Fleet::m_last_turn_move_ordered, Fleet::m_next_system, Fleet::m_ordered_given_to_empire_id, Fleet::m_prev_system, Fleet::m_ships, and Fleet::m_travel_route.
serialize() [11/13]
template<typename Archive > void serialize (Archive & ar, Ship & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), Ship::m_arrived_on_turn, Ship::m_design_id, Ship::m_fleet_id, Ship::m_last_resupplied_on_turn, Ship::m_last_turn_active_in_combat, Ship::m_ordered_bombard_planet_id, Ship::m_ordered_colonize_planet_id, Ship::m_ordered_invade_planet_id, Ship::m_ordered_scrapped, Ship::m_part_meters, Ship::m_produced_by_empire_id, and Ship::m_species_name.
serialize() [12/13]
template<typename Archive > void serialize (Archive & ar, ShipDesign & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), ShipDesign::BuildStatCaches(), ShipDesign::ForceValidDesignOrThrow(), ShipDesign::m_3D_model, ShipDesign::m_description, ShipDesign::m_designed_by_empire, ShipDesign::m_designed_on_turn, ShipDesign::m_hull, ShipDesign::m_icon, ShipDesign::m_id, ShipDesign::m_is_monster, ShipDesign::m_name, ShipDesign::m_name_desc_in_stringtable, ShipDesign::m_parts, ShipDesign::m_uuid, to_string(), and TraceLogger.
serialize() [13/13]
template<typename Archive > void serialize (Archive & ar, SpeciesManager & sm, unsigned int const version)
References SpeciesManager::GetSpeciesEmpireOpinionsMap(), SpeciesManager::GetSpeciesHomeworldsMap(), SpeciesManager::GetSpeciesSpeciesOpinionsMap(), GlobalSerializationEncodingForEmpire(), SpeciesManager::m_species_object_populations, SpeciesManager::m_species_species_ships_destroyed, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), SpeciesManager::SetSpeciesEmpireOpinions(), SpeciesManager::SetSpeciesHomeworlds(), SpeciesManager::SetSpeciesSpeciesOpinions(), SpeciesManager::SpeciesObjectPopulations(), and SpeciesManager::SpeciesShipsDestroyed().
Serialize() [1/2]
template<typename Archive > void Serialize (Archive & oa, const Universe & universe)
Serialize universe to output archive oa.
Warning
Do not try to serialize types that contain longs, since longs are different sizes on 32- and 64-bit architectures. Replace your longs with long longs for portability. It would seem that short of writing some Boost.Serialization archive that handles longs portably, we cannot transmit longs across machines with different bit-size architectures.
References FO_COMMON_API, Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
Referenced by GameStartMessage(), SaveGame(), TurnOrdersMessage(), TurnPartialOrdersMessage(), TurnPartialUpdateMessage(), and TurnUpdateMessage().
Serialize() [2/2]
template<typename Archive > void Serialize (Archive & oa, const std::map< int, std::shared_ptr< UniverseObject >> & objects)
Serialize object_map to output archive oa.
References Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
serialize< freeorion_bin_iarchive >() [1/4]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PopCenter & , unsigned int const)
Referenced by serialize().
serialize< freeorion_bin_iarchive >() [2/4]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , ResourceCenter & , unsigned int const)
serialize< freeorion_bin_iarchive >() [3/4]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & ar, System & , unsigned int const)
serialize< freeorion_bin_iarchive >() [4/4]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SpeciesManager & , unsigned int const)
serialize< freeorion_bin_oarchive >() [1/4]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PopCenter & , unsigned int const)
Referenced by serialize().
serialize< freeorion_bin_oarchive >() [2/4]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , ResourceCenter & , unsigned int const)
serialize< freeorion_bin_oarchive >() [3/4]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & ar, System & , unsigned int const)
serialize< freeorion_bin_oarchive >() [4/4]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SpeciesManager & , unsigned int const)
Serialize< freeorion_bin_oarchive >() [1/2]
template FO_COMMON_API void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & oa, const Universe & universe)
Referenced by Serialize().
Serialize< freeorion_bin_oarchive >() [2/2]
template void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & oa, const std::map< int, std::shared_ptr< UniverseObject >> & objects)
serialize< freeorion_xml_iarchive >() [1/4]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PopCenter & , unsigned int const)
Referenced by serialize().
serialize< freeorion_xml_iarchive >() [2/4]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , ResourceCenter & , unsigned int const)
serialize< freeorion_xml_iarchive >() [3/4]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & ar, System & , unsigned int const)
serialize< freeorion_xml_iarchive >() [4/4]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SpeciesManager & , unsigned int const)
serialize< freeorion_xml_oarchive >() [1/4]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PopCenter & , unsigned int const)
Referenced by serialize().
serialize< freeorion_xml_oarchive >() [2/4]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , ResourceCenter & , unsigned int const)
serialize< freeorion_xml_oarchive >() [3/4]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & ar, System & , unsigned int const)
serialize< freeorion_xml_oarchive >() [4/4]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SpeciesManager & , unsigned int const)
Serialize< freeorion_xml_oarchive >() [1/2]
template FO_COMMON_API void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & oa, const Universe & universe)
Referenced by Serialize().
Serialize< freeorion_xml_oarchive >() [2/2]
template void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & oa, const std::map< int, std::shared_ptr< UniverseObject >> & objects)