FreeOrion: SerializeOrderSet.cpp File Reference
SerializeOrderSet.cpp File Reference
#include "Serialize.h"
#include "../universe/Fleet.h"
#include "Order.h"
#include "OrderSet.h"
#include "Serialize.ipp"
#include <boost/serialization/version.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/nil_generator.hpp>
#include "Logger.h"
Functions
template<typename Archive >
void Deserialize (Archive &ia, OrderSet &order_set)
Deserialize order_set from input archive ia.
template void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &ia, OrderSet &order_set)
template void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &ia, OrderSet &order_set)
template<typename Archive >
void Serialize (Archive &oa, const OrderSet &order_set)
Serialize order_set to output archive oa.
template void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &oa, const OrderSet &order_set)
template void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &oa, const OrderSet &order_set)
Function Documentation
Deserialize()
template<typename Archive > void Deserialize (Archive & ia, OrderSet & order_set)
Deserialize order_set from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), and Deserialize< freeorion_xml_iarchive >().
Deserialize< freeorion_bin_iarchive >()
template void Deserialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & ia, OrderSet & order_set)
Referenced by Deserialize().
Deserialize< freeorion_xml_iarchive >()
template void Deserialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & ia, OrderSet & order_set)
Referenced by Deserialize().
Serialize()
template<typename Archive > void Serialize (Archive & oa, const OrderSet & order_set)
Serialize order_set to output archive oa.
References Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
Serialize< freeorion_bin_oarchive >()
template void Serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & oa, const OrderSet & order_set)
Referenced by Serialize().
Serialize< freeorion_xml_oarchive >()
template void Serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & oa, const OrderSet & order_set)
Referenced by Serialize().