FreeOrion: SerializeEmpire.cpp File Reference
SerializeEmpire.cpp File Reference
#include "Serialize.h"
#include "AppInterface.h"
#include "SitRepEntry.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Supply.h"
#include "../Empire/Diplomacy.h"
#include "../universe/Universe.h"
#include "GameRules.h"
#include "Serialize.ipp"
#include <boost/serialization/version.hpp>
#include <boost/uuid/random_generator.hpp>
Namespaces
anonymous_namespace{SerializeEmpire.cpp}
Functions
std::pair< int, int > anonymous_namespace{SerializeEmpire.cpp}::DiploKey (int id1, int ind2)
template<typename Archive >
void serialize (Archive &ar, EmpireManager &em, unsigned int const version)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, EmpireManager &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, EmpireManager &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, EmpireManager &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, EmpireManager &, unsigned int const)
Function Documentation
serialize()
template<typename Archive > void serialize (Archive & ar, EmpireManager & em, unsigned int const version)
References EmpireManager::Clear(), anonymous_namespace{SerializeEmpire.cpp}::DiploKey(), ErrorLogger, EmpireManager::GetDiplomaticMessagesToSerialize(), GlobalSerializationEncodingForEmpire(), EmpireManager::m_diplomatic_messages, EmpireManager::m_empire_diplomatic_statuses, EmpireManager::m_empire_map, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Referenced by ResearchQueue::serialize(), and InfluenceQueue::serialize().
serialize< freeorion_bin_iarchive >()
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , EmpireManager & , unsigned int const)
Referenced by ResearchQueue::Element::serialize(), InfluenceQueue::Element::serialize(), ResearchQueue::serialize(), InfluenceQueue::serialize(), SupplyManager::serialize(), and serialize().
serialize< freeorion_bin_oarchive >()
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , EmpireManager & , unsigned int const)
Referenced by ResearchQueue::Element::serialize(), InfluenceQueue::Element::serialize(), ResearchQueue::serialize(), InfluenceQueue::serialize(), SupplyManager::serialize(), and serialize().
serialize< freeorion_xml_iarchive >()
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , EmpireManager & , unsigned int const)
Referenced by ResearchQueue::Element::serialize(), InfluenceQueue::Element::serialize(), ResearchQueue::serialize(), InfluenceQueue::serialize(), SupplyManager::serialize(), and serialize().
serialize< freeorion_xml_oarchive >()
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , EmpireManager & , unsigned int const)
Referenced by ResearchQueue::Element::serialize(), InfluenceQueue::Element::serialize(), ResearchQueue::serialize(), InfluenceQueue::serialize(), SupplyManager::serialize(), and serialize().