FreeOrion: SerializeMultiplayerCommon.cpp File Reference
SerializeMultiplayerCommon.cpp File Reference
#include "Serialize.h"
#include "MultiplayerCommon.h"
#include "OptionsDB.h"
#include "OrderSet.h"
#include "Order.h"
#include "SaveGamePreviewUtils.h"
#include "Version.h"
#include "../universe/System.h"
#include "Serialize.ipp"
#include <boost/date_time/posix_time/time_serialize.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
Functions
int & GlobalSerializationEncodingForEmpire ()
This must be set to the encoding empire's id when serializing various gamestate information, so that only the relevant info is serialized for the intended recieipient.
template<typename Archive >
void serialize (Archive &ar, FullPreview &fp, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, GalaxySetupData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SinglePlayerSetupData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SaveGamePreviewData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SaveGameUIData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SaveGameEmpireData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, PlayerSaveHeaderData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, PlayerSaveGameData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, PreviewInformation &pi, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, ServerSaveGameData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, PlayerSetupData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, MultiplayerLobbyData &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, ChatHistoryEntity &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, PlayerInfo &obj, unsigned int const version)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, FullPreview &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, GalaxySetupData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SinglePlayerSetupData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGamePreviewData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGameUIData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGameEmpireData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSaveHeaderData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSaveGameData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PreviewInformation &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, ServerSaveGameData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSetupData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, MultiplayerLobbyData &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, ChatHistoryEntity &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerInfo &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, FullPreview &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, GalaxySetupData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SinglePlayerSetupData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGamePreviewData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGameUIData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGameEmpireData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSaveHeaderData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSaveGameData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PreviewInformation &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, ServerSaveGameData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSetupData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, MultiplayerLobbyData &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, ChatHistoryEntity &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerInfo &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, FullPreview &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, GalaxySetupData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SinglePlayerSetupData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGamePreviewData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGameUIData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGameEmpireData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSaveHeaderData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSaveGameData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PreviewInformation &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, ServerSaveGameData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSetupData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, MultiplayerLobbyData &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, ChatHistoryEntity &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerInfo &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, FullPreview &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, GalaxySetupData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SinglePlayerSetupData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGamePreviewData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGameUIData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGameEmpireData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSaveHeaderData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSaveGameData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PreviewInformation &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, ServerSaveGameData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSetupData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, MultiplayerLobbyData &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, ChatHistoryEntity &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerInfo &, unsigned int const)
Function Documentation
GlobalSerializationEncodingForEmpire()
int& GlobalSerializationEncodingForEmpire ()
This must be set to the encoding empire's id when serializing various gamestate information, so that only the relevant info is serialized for the intended recieipient.
This is implemented this way so that we don't need to write custom boost::serialization classes that implement empire-dependent visibility.
References ALL_EMPIRES.
Referenced by ExtractGameStartMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnUpdateMessageData(), GameStartMessage(), LoadGame(), SaveGame(), InfluenceQueue::serialize(), serialize(), TurnPartialUpdateMessage(), and TurnUpdateMessage().
serialize() [1/14]
template<typename Archive > void serialize (Archive & ar, FullPreview & fp, unsigned int const version)
References FullPreview::filename, FullPreview::galaxy, FullPreview::preview, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [2/14]
template<typename Archive > void serialize (Archive & ar, GalaxySetupData & obj, unsigned int const version)
References GalaxySetupData::age, GalaxySetupData::ai_aggr, ALL_EMPIRES, anonymous_namespace{CUIWnd.cpp}::dummy, GalaxySetupData::encoding_empire, GalaxySetupData::game_rules, GalaxySetupData::game_uid, GetOptionsDB(), GalaxySetupData::monster_freq, GalaxySetupData::native_freq, GalaxySetupData::planet_density, GalaxySetupData::seed, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, and to_string().
serialize() [3/14]
template<typename Archive > void serialize (Archive & ar, SinglePlayerSetupData & obj, unsigned int const version)
References SinglePlayerSetupData::filename, SinglePlayerSetupData::new_game, SinglePlayerSetupData::players, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [4/14]
template<typename Archive > void serialize (Archive & ar, SaveGamePreviewData & obj, unsigned int const version)
References SaveGamePreviewData::compressed_text_size, SaveGamePreviewData::current_turn, SaveGamePreviewData::description, SaveGamePreviewData::freeorion_version, FreeOrionVersionString(), SaveGamePreviewData::magic_number, SaveGamePreviewData::main_player_empire_colour, SaveGamePreviewData::main_player_empire_name, SaveGamePreviewData::main_player_name, SaveGamePreviewData::number_of_empires, SaveGamePreviewData::number_of_human_players, SaveGamePreviewData::save_format_marker, SaveGamePreviewData::save_time, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and SaveGamePreviewData::uncompressed_text_size.
serialize() [5/14]
template<typename Archive > void serialize (Archive & ar, SaveGameUIData & obj, unsigned int const version)
References ErrorLogger, SaveGameUIData::fleets_exploring, SaveGameUIData::map_left, SaveGameUIData::map_top, SaveGameUIData::map_zoom_steps_in, SaveGameUIData::obsolete_ship_parts, SaveGameUIData::obsolete_ui_event_count, SaveGameUIData::ordered_ship_design_ids_and_obsolete, SaveGameUIData::ordered_ship_hull_and_obsolete, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and TraceLogger.
serialize() [6/14]
template<typename Archive > void serialize (Archive & ar, SaveGameEmpireData & obj, unsigned int const version)
References SaveGameEmpireData::authenticated, SaveGameEmpireData::color, SaveGameEmpireData::eliminated, SaveGameEmpireData::empire_id, SaveGameEmpireData::empire_name, SaveGameEmpireData::player_name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and SaveGameEmpireData::won.
serialize() [7/14]
template<typename Archive > void serialize (Archive & ar, PlayerSaveHeaderData & obj, unsigned int const version)
References PlayerSaveHeaderData::client_type, PlayerSaveHeaderData::empire_id, PlayerSaveHeaderData::name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [8/14]
template<typename Archive > void serialize (Archive & ar, PlayerSaveGameData & obj, unsigned int const version)
References PlayerSaveHeaderData::client_type, PlayerSaveHeaderData::empire_id, PlayerSaveHeaderData::name, PlayerSaveGameData::orders, PlayerSaveGameData::save_state_string, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and PlayerSaveGameData::ui_data.
serialize() [9/14]
template<typename Archive > void serialize (Archive & ar, PreviewInformation & pi, unsigned int const version)
References PreviewInformation::folder, PreviewInformation::previews, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and PreviewInformation::subdirectories.
serialize() [10/14]
template<typename Archive > void serialize (Archive & ar, ServerSaveGameData & obj, unsigned int const version)
References ServerSaveGameData::current_turn, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [11/14]
template<typename Archive > void serialize (Archive & ar, PlayerSetupData & obj, unsigned int const version)
References PlayerSetupData::authenticated, PlayerSetupData::client_type, PlayerSetupData::empire_color, PlayerSetupData::empire_name, PlayerSetupData::player_id, PlayerSetupData::player_name, PlayerSetupData::player_ready, PlayerSetupData::save_game_empire_id, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), PlayerSetupData::starting_species_name, and PlayerSetupData::starting_team.
serialize() [12/14]
template<typename Archive > void serialize (Archive & ar, MultiplayerLobbyData & obj, unsigned int const version)
References MultiplayerLobbyData::any_can_edit, MultiplayerLobbyData::in_game, MultiplayerLobbyData::new_game, MultiplayerLobbyData::players, MultiplayerLobbyData::save_game, MultiplayerLobbyData::save_game_current_turn, MultiplayerLobbyData::save_game_empire_data, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), MultiplayerLobbyData::start_lock_cause, and MultiplayerLobbyData::start_locked.
serialize() [13/14]
template<typename Archive > void serialize (Archive & ar, ChatHistoryEntity & obj, unsigned int const version)
References ChatHistoryEntity::player_name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), ChatHistoryEntity::text, ChatHistoryEntity::text_color, and ChatHistoryEntity::timestamp.
Referenced by GG_ENUM().
serialize() [14/14]
template<typename Archive > void serialize (Archive & ar, PlayerInfo & obj, unsigned int const version)
References PlayerInfo::client_type, PlayerInfo::empire_id, PlayerInfo::host, PlayerInfo::name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize< freeorion_bin_iarchive >() [1/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , FullPreview & , unsigned int const)
Referenced by serialize().
serialize< freeorion_bin_iarchive >() [2/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [3/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [4/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [5/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [6/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [7/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [8/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [9/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_bin_iarchive >() [10/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [11/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [12/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [13/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , ChatHistoryEntity & , unsigned int const)
serialize< freeorion_bin_iarchive >() [14/14]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_bin_oarchive >() [1/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , FullPreview & , unsigned int const)
Referenced by serialize().
serialize< freeorion_bin_oarchive >() [2/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [3/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [4/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [5/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [6/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [7/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [8/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [9/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_bin_oarchive >() [10/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [11/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [12/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [13/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , ChatHistoryEntity & , unsigned int const)
serialize< freeorion_bin_oarchive >() [14/14]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_xml_iarchive >() [1/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , FullPreview & , unsigned int const)
Referenced by serialize().
serialize< freeorion_xml_iarchive >() [2/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [3/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [4/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [5/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [6/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [7/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [8/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [9/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_xml_iarchive >() [10/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [11/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [12/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [13/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , ChatHistoryEntity & , unsigned int const)
serialize< freeorion_xml_iarchive >() [14/14]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_xml_oarchive >() [1/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , FullPreview & , unsigned int const)
Referenced by serialize().
serialize< freeorion_xml_oarchive >() [2/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [3/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [4/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [5/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [6/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [7/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [8/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [9/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_xml_oarchive >() [10/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [11/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [12/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [13/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , ChatHistoryEntity & , unsigned int const)
serialize< freeorion_xml_oarchive >() [14/14]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerInfo & , unsigned int const)