FreeOrion: Serialize.h File Reference
Serialize.h File Reference
#include <boost/archive/binary_iarchive.hpp>
#include <boost/archive/binary_oarchive.hpp>
#include <boost/archive/xml_iarchive.hpp>
#include <boost/archive/xml_oarchive.hpp>
#include <boost/serialization/version.hpp>
#include <map>
#include "Export.h"
Typedefs
typedef boost::archive::binary_iarchive freeorion_bin_iarchive
typedef boost::archive::binary_oarchive freeorion_bin_oarchive
typedef boost::archive::xml_iarchive freeorion_xml_iarchive
typedef boost::archive::xml_oarchive freeorion_xml_oarchive
Functions
BOOST_CLASS_VERSION (ChatHistoryEntity, 1)
BOOST_CLASS_VERSION (CombatLog, 1)
BOOST_CLASS_VERSION (EmpireManager, 1)
BOOST_CLASS_VERSION (GalaxySetupData, 3)
BOOST_CLASS_VERSION (MultiplayerLobbyData, 2)
BOOST_CLASS_VERSION (PlayerSaveGameData, 2)
BOOST_CLASS_VERSION (SaveGamePreviewData, 5)
BOOST_CLASS_VERSION (PlayerSetupData, 2)
BOOST_CLASS_VERSION (SaveGameEmpireData, 3)
BOOST_CLASS_VERSION (SaveGameUIData, 4)
template<typename Archive >
FO_COMMON_API void Deserialize (Archive &ia, Universe &universe)
Deserialize universe from input archive ia.
template<typename Archive >
void Deserialize (Archive &ia, std::map< int, std::shared_ptr< UniverseObject >> &objects)
Deserialize object_map from input archive ia.
template<typename Archive >
void Deserialize (Archive &ia, OrderSet &order_set)
Deserialize order_set from input archive ia.
FO_COMMON_API int & GlobalSerializationEncodingForEmpire ()
This must be set to the encoding empire's id when serializing various gamestate information, so that only the relevant info is serialized for the intended recieipient.
template<typename Archive >
FO_COMMON_API void Serialize (Archive &oa, const Universe &universe)
Serialize universe to output archive oa.
template<typename Archive >
void Serialize (Archive &oa, const std::map< int, std::shared_ptr< UniverseObject >> &objects)
Serialize object_map to output archive oa.
template<typename Archive >
void Serialize (Archive &oa, const OrderSet &order_set)
Serialize order_set to output archive oa.
template<typename Archive >
void serialize (Archive &, ChatHistoryEntity &, unsigned int const)
template<typename Archive >
void serialize (Archive &, CombatLog &, const unsigned int)
template<typename Archive >
void serialize (Archive &, CombatLogManager &, const unsigned int)
template<typename Archive >
void serialize (Archive &, EmpireManager &, unsigned int const)
template<typename Archive >
void serialize (Archive &, GalaxySetupData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, MultiplayerLobbyData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PlayerInfo &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PlayerSaveGameData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PlayerSaveHeaderData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, SaveGamePreviewData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PlayerSetupData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PopCenter &, unsigned int const)
template<typename Archive >
void serialize (Archive &, PreviewInformation &, unsigned int const)
template<typename Archive >
void serialize (Archive &, SaveGameEmpireData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, SaveGameUIData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, ServerSaveGameData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, SinglePlayerSetupData &, unsigned int const)
template<typename Archive >
void serialize (Archive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, ChatHistoryEntity &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLog &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, EmpireManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, GalaxySetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, MultiplayerLobbyData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerInfo &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSaveHeaderData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGamePreviewData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PopCenter &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, PreviewInformation &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGameEmpireData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SaveGameUIData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, ServerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SinglePlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, ChatHistoryEntity &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLog &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, EmpireManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, GalaxySetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, MultiplayerLobbyData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerInfo &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSaveHeaderData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGamePreviewData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PopCenter &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, PreviewInformation &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGameEmpireData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SaveGameUIData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, ServerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SinglePlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, ChatHistoryEntity &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLog &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, EmpireManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, GalaxySetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, MultiplayerLobbyData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerInfo &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSaveHeaderData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGamePreviewData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PopCenter &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, PreviewInformation &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGameEmpireData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SaveGameUIData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, ServerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SinglePlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SpeciesManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, ChatHistoryEntity &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLog &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, EmpireManager &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, GalaxySetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, MultiplayerLobbyData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerInfo &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSaveHeaderData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGamePreviewData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PopCenter &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, PreviewInformation &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGameEmpireData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SaveGameUIData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, ServerSaveGameData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SinglePlayerSetupData &, unsigned int const)
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SpeciesManager &, unsigned int const)
template<typename Archive >
void SerializeIncompleteLogs (Archive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLogManager &, const unsigned int)
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLogManager &, const unsigned int)
Typedef Documentation
freeorion_bin_iarchive
typedef boost::archive::binary_iarchive freeorion_bin_iarchive
freeorion_bin_oarchive
typedef boost::archive::binary_oarchive freeorion_bin_oarchive
freeorion_xml_iarchive
typedef boost::archive::xml_iarchive freeorion_xml_iarchive
freeorion_xml_oarchive
typedef boost::archive::xml_oarchive freeorion_xml_oarchive
Function Documentation
BOOST_CLASS_VERSION() [1/10]
BOOST_CLASS_VERSION (ChatHistoryEntity , 1)
Referenced by serialize(), ResearchQueue::serialize(), and InfluenceQueue::serialize().
BOOST_CLASS_VERSION() [2/10]
BOOST_CLASS_VERSION (CombatLog , 1)
BOOST_CLASS_VERSION() [3/10]
BOOST_CLASS_VERSION (EmpireManager , 1)
BOOST_CLASS_VERSION() [4/10]
BOOST_CLASS_VERSION (GalaxySetupData , 3)
BOOST_CLASS_VERSION() [5/10]
BOOST_CLASS_VERSION (MultiplayerLobbyData , 2)
BOOST_CLASS_VERSION() [6/10]
BOOST_CLASS_VERSION (PlayerSaveGameData , 2)
BOOST_CLASS_VERSION() [7/10]
BOOST_CLASS_VERSION (SaveGamePreviewData , 5)
BOOST_CLASS_VERSION() [8/10]
BOOST_CLASS_VERSION (PlayerSetupData , 2)
BOOST_CLASS_VERSION() [9/10]
BOOST_CLASS_VERSION (SaveGameEmpireData , 3)
BOOST_CLASS_VERSION() [10/10]
BOOST_CLASS_VERSION (SaveGameUIData , 4)
Deserialize() [1/3]
template<typename Archive > FO_COMMON_API void Deserialize (Archive & ia, Universe & universe)
Deserialize universe from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), Deserialize< freeorion_xml_iarchive >(), and FO_COMMON_API.
Referenced by ExtractGameStartMessageData(), ExtractTurnOrdersMessageData(), ExtractTurnPartialOrdersMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnUpdateMessageData(), and LoadGame().
Deserialize() [2/3]
template<typename Archive > void Deserialize (Archive & ia, std::map< int, std::shared_ptr< UniverseObject >> & objects)
Deserialize object_map from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), and Deserialize< freeorion_xml_iarchive >().
Deserialize() [3/3]
template<typename Archive > void Deserialize (Archive & ia, OrderSet & order_set)
Deserialize order_set from input archive ia.
References Deserialize< freeorion_bin_iarchive >(), and Deserialize< freeorion_xml_iarchive >().
GlobalSerializationEncodingForEmpire()
FO_COMMON_API int& GlobalSerializationEncodingForEmpire ()
This must be set to the encoding empire's id when serializing various gamestate information, so that only the relevant info is serialized for the intended recieipient.
This is implemented this way so that we don't need to write custom boost::serialization classes that implement empire-dependent visibility.
References ALL_EMPIRES.
Referenced by ExtractGameStartMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnUpdateMessageData(), GameStartMessage(), LoadGame(), SaveGame(), InfluenceQueue::serialize(), serialize(), TurnPartialUpdateMessage(), and TurnUpdateMessage().
Serialize() [1/3]
template<typename Archive > FO_COMMON_API void Serialize (Archive & oa, const Universe & universe)
Serialize universe to output archive oa.
Warning
Do not try to serialize types that contain longs, since longs are different sizes on 32- and 64-bit architectures. Replace your longs with long longs for portability. It would seem that short of writing some Boost.Serialization archive that handles longs portably, we cannot transmit longs across machines with different bit-size architectures.
References FO_COMMON_API, Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
Referenced by GameStartMessage(), SaveGame(), TurnOrdersMessage(), TurnPartialOrdersMessage(), TurnPartialUpdateMessage(), and TurnUpdateMessage().
Serialize() [2/3]
template<typename Archive > void Serialize (Archive & oa, const std::map< int, std::shared_ptr< UniverseObject >> & objects)
Serialize object_map to output archive oa.
References Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
Serialize() [3/3]
template<typename Archive > void Serialize (Archive & oa, const OrderSet & order_set)
Serialize order_set to output archive oa.
References Serialize< freeorion_bin_oarchive >(), and Serialize< freeorion_xml_oarchive >().
serialize() [1/18]
template<typename Archive > void serialize (Archive & , ChatHistoryEntity & , unsigned int const)
References ChatHistoryEntity::player_name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), ChatHistoryEntity::text, ChatHistoryEntity::text_color, and ChatHistoryEntity::timestamp.
Referenced by GG_ENUM().
serialize() [2/18]
template<typename Archive > void serialize (Archive & , CombatLog & , const unsigned int)
References CombatLog::combat_events, CombatLog::damaged_object_ids, CombatLog::destroyed_object_ids, CombatLog::empire_ids, ErrorLogger, CombatLog::object_ids, CombatLog::participant_states, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), CombatLog::system_id, TraceLogger, and CombatLog::turn.
serialize() [3/18]
template<typename Archive > void serialize (Archive & , CombatLogManager & , const unsigned int)
References CombatLogManager::m_latest_log_id, CombatLogManager::m_logs, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [4/18]
template<typename Archive > void serialize (Archive & , EmpireManager & , unsigned int const)
References EmpireManager::Clear(), anonymous_namespace{SerializeEmpire.cpp}::DiploKey(), ErrorLogger, EmpireManager::GetDiplomaticMessagesToSerialize(), GlobalSerializationEncodingForEmpire(), EmpireManager::m_const_empire_map, EmpireManager::m_diplomatic_messages, EmpireManager::m_empire_diplomatic_statuses, EmpireManager::m_empire_map, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and TraceLogger.
Referenced by ResearchQueue::serialize(), and InfluenceQueue::serialize().
serialize() [5/18]
template<typename Archive > void serialize (Archive & , GalaxySetupData & , unsigned int const)
References GalaxySetupData::age, GalaxySetupData::ai_aggr, ALL_EMPIRES, anonymous_namespace{CUIWnd.cpp}::dummy, GalaxySetupData::encoding_empire, GalaxySetupData::game_rules, GalaxySetupData::game_uid, GetOptionsDB(), GalaxySetupData::monster_freq, GalaxySetupData::native_freq, GalaxySetupData::planet_density, GalaxySetupData::seed, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), GalaxySetupData::shape, GalaxySetupData::size, GalaxySetupData::specials_freq, GalaxySetupData::starlane_freq, and to_string().
serialize() [6/18]
template<typename Archive > void serialize (Archive & , MultiplayerLobbyData & , unsigned int const)
References MultiplayerLobbyData::any_can_edit, MultiplayerLobbyData::in_game, MultiplayerLobbyData::new_game, MultiplayerLobbyData::players, MultiplayerLobbyData::save_game, MultiplayerLobbyData::save_game_current_turn, MultiplayerLobbyData::save_game_empire_data, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), MultiplayerLobbyData::start_lock_cause, and MultiplayerLobbyData::start_locked.
serialize() [7/18]
template<typename Archive > void serialize (Archive & , PlayerInfo & , unsigned int const)
References PlayerInfo::client_type, PlayerInfo::empire_id, PlayerInfo::host, PlayerInfo::name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [8/18]
template<typename Archive > void serialize (Archive & , PlayerSaveGameData & , unsigned int const)
References PlayerSaveHeaderData::client_type, PlayerSaveHeaderData::empire_id, PlayerSaveHeaderData::name, PlayerSaveGameData::orders, PlayerSaveGameData::save_state_string, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and PlayerSaveGameData::ui_data.
serialize() [9/18]
template<typename Archive > void serialize (Archive & , PlayerSaveHeaderData & , unsigned int const)
References PlayerSaveHeaderData::client_type, PlayerSaveHeaderData::empire_id, PlayerSaveHeaderData::name, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [10/18]
template<typename Archive > void serialize (Archive & , SaveGamePreviewData & , unsigned int const)
References CompatColor::a, CompatColor::b, SaveGamePreviewData::compressed_text_size, SaveGamePreviewData::current_turn, SaveGamePreviewData::description, SaveGamePreviewData::freeorion_version, FreeOrionVersionString(), CompatColor::g, SaveGamePreviewData::magic_number, SaveGamePreviewData::main_player_empire_colour, SaveGamePreviewData::main_player_empire_name, SaveGamePreviewData::main_player_name, SaveGamePreviewData::number_of_empires, SaveGamePreviewData::number_of_human_players, CompatColor::r, SaveGamePreviewData::save_format_marker, SaveGamePreviewData::save_time, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and SaveGamePreviewData::uncompressed_text_size.
serialize() [11/18]
template<typename Archive > void serialize (Archive & , PlayerSetupData & , unsigned int const)
References PlayerSetupData::authenticated, PlayerSetupData::client_type, PlayerSetupData::empire_color, PlayerSetupData::empire_name, PlayerSetupData::player_id, PlayerSetupData::player_name, PlayerSetupData::player_ready, PlayerSetupData::save_game_empire_id, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), PlayerSetupData::starting_species_name, and PlayerSetupData::starting_team.
serialize() [12/18]
template<typename Archive > void serialize (Archive & , PopCenter & , unsigned int const)
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [13/18]
template<typename Archive > void serialize (Archive & , PreviewInformation & , unsigned int const)
References PreviewInformation::folder, PreviewInformation::previews, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and PreviewInformation::subdirectories.
serialize() [14/18]
template<typename Archive > void serialize (Archive & , SaveGameEmpireData & , unsigned int const)
References CompatColor::a, SaveGameEmpireData::authenticated, CompatColor::b, SaveGameEmpireData::color, SaveGameEmpireData::eliminated, SaveGameEmpireData::empire_id, SaveGameEmpireData::empire_name, CompatColor::g, SaveGameEmpireData::player_name, CompatColor::r, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and SaveGameEmpireData::won.
serialize() [15/18]
template<typename Archive > void serialize (Archive & , SaveGameUIData & , unsigned int const)
References ErrorLogger, SaveGameUIData::fleets_exploring, SaveGameUIData::map_left, SaveGameUIData::map_top, SaveGameUIData::map_zoom_steps_in, SaveGameUIData::obsolete_ship_parts, SaveGameUIData::obsolete_ui_event_count, SaveGameUIData::ordered_ship_design_ids_and_obsolete, SaveGameUIData::ordered_ship_hull_and_obsolete, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), and TraceLogger.
serialize() [16/18]
template<typename Archive > void serialize (Archive & , ServerSaveGameData & , unsigned int const)
References ServerSaveGameData::current_turn, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [17/18]
template<typename Archive > void serialize (Archive & , SinglePlayerSetupData & , unsigned int const)
References SinglePlayerSetupData::filename, SinglePlayerSetupData::new_game, SinglePlayerSetupData::players, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [18/18]
template<typename Archive > void serialize (Archive & , SpeciesManager & , unsigned int const)
References SpeciesManager::GetSpeciesEmpireOpinionsMap(), SpeciesManager::GetSpeciesHomeworldsMap(), SpeciesManager::GetSpeciesSpeciesOpinionsMap(), GlobalSerializationEncodingForEmpire(), SpeciesManager::m_species_object_populations, SpeciesManager::m_species_species_ships_destroyed, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), SpeciesManager::SetSpeciesEmpireOpinions(), SpeciesManager::SetSpeciesHomeworlds(), SpeciesManager::SetSpeciesSpeciesOpinions(), SpeciesManager::SpeciesObjectPopulations(), and SpeciesManager::SpeciesShipsDestroyed().
serialize< freeorion_bin_iarchive >() [1/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , ChatHistoryEntity & , unsigned int const)
Referenced by Moderator::ModeratorAction::serialize(), Moderator::DestroyUniverseObject::serialize(), Moderator::SetOwner::serialize(), Moderator::AddStarlane::serialize(), Moderator::RemoveStarlane::serialize(), Moderator::CreateSystem::serialize(), and Moderator::CreatePlanet::serialize().
serialize< freeorion_bin_iarchive >() [2/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLog & , const unsigned int)
serialize< freeorion_bin_iarchive >() [3/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_bin_iarchive >() [4/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , EmpireManager & , unsigned int const)
serialize< freeorion_bin_iarchive >() [5/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [6/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [7/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_bin_iarchive >() [8/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [9/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [10/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [11/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [12/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PopCenter & , unsigned int const)
serialize< freeorion_bin_iarchive >() [13/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_bin_iarchive >() [14/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [15/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [16/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [17/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_bin_iarchive >() [18/18]
template FO_COMMON_API void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SpeciesManager & , unsigned int const)
serialize< freeorion_bin_oarchive >() [1/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , ChatHistoryEntity & , unsigned int const)
Referenced by Moderator::ModeratorAction::serialize(), Moderator::DestroyUniverseObject::serialize(), Moderator::SetOwner::serialize(), Moderator::AddStarlane::serialize(), Moderator::RemoveStarlane::serialize(), Moderator::CreateSystem::serialize(), and Moderator::CreatePlanet::serialize().
serialize< freeorion_bin_oarchive >() [2/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLog & , const unsigned int)
serialize< freeorion_bin_oarchive >() [3/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_bin_oarchive >() [4/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , EmpireManager & , unsigned int const)
serialize< freeorion_bin_oarchive >() [5/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [6/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [7/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_bin_oarchive >() [8/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [9/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [10/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [11/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [12/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PopCenter & , unsigned int const)
serialize< freeorion_bin_oarchive >() [13/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_bin_oarchive >() [14/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [15/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [16/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [17/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_bin_oarchive >() [18/18]
template FO_COMMON_API void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SpeciesManager & , unsigned int const)
serialize< freeorion_xml_iarchive >() [1/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , ChatHistoryEntity & , unsigned int const)
Referenced by Moderator::ModeratorAction::serialize(), Moderator::DestroyUniverseObject::serialize(), Moderator::SetOwner::serialize(), Moderator::AddStarlane::serialize(), Moderator::RemoveStarlane::serialize(), Moderator::CreateSystem::serialize(), and Moderator::CreatePlanet::serialize().
serialize< freeorion_xml_iarchive >() [2/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLog & , const unsigned int)
serialize< freeorion_xml_iarchive >() [3/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_xml_iarchive >() [4/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , EmpireManager & , unsigned int const)
serialize< freeorion_xml_iarchive >() [5/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [6/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [7/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_xml_iarchive >() [8/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [9/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [10/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [11/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [12/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PopCenter & , unsigned int const)
serialize< freeorion_xml_iarchive >() [13/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_xml_iarchive >() [14/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [15/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [16/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [17/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_xml_iarchive >() [18/18]
template FO_COMMON_API void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SpeciesManager & , unsigned int const)
serialize< freeorion_xml_oarchive >() [1/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , ChatHistoryEntity & , unsigned int const)
Referenced by Moderator::ModeratorAction::serialize(), Moderator::DestroyUniverseObject::serialize(), Moderator::SetOwner::serialize(), Moderator::AddStarlane::serialize(), Moderator::RemoveStarlane::serialize(), Moderator::CreateSystem::serialize(), and Moderator::CreatePlanet::serialize().
serialize< freeorion_xml_oarchive >() [2/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLog & , const unsigned int)
serialize< freeorion_xml_oarchive >() [3/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_xml_oarchive >() [4/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , EmpireManager & , unsigned int const)
serialize< freeorion_xml_oarchive >() [5/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , GalaxySetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [6/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , MultiplayerLobbyData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [7/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerInfo & , unsigned int const)
serialize< freeorion_xml_oarchive >() [8/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSaveGameData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [9/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSaveHeaderData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [10/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGamePreviewData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [11/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PlayerSetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [12/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PopCenter & , unsigned int const)
serialize< freeorion_xml_oarchive >() [13/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , PreviewInformation & , unsigned int const)
serialize< freeorion_xml_oarchive >() [14/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGameEmpireData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [15/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SaveGameUIData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [16/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , ServerSaveGameData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [17/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SinglePlayerSetupData & , unsigned int const)
serialize< freeorion_xml_oarchive >() [18/18]
template FO_COMMON_API void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SpeciesManager & , unsigned int const)
SerializeIncompleteLogs()
template<typename Archive > void SerializeIncompleteLogs (Archive & , CombatLogManager & , const unsigned int)
References CombatLogManager::m_incomplete_logs, CombatLogManager::m_latest_log_id, SerializeIncompleteLogs< freeorion_bin_iarchive >(), SerializeIncompleteLogs< freeorion_bin_oarchive >(), SerializeIncompleteLogs< freeorion_xml_iarchive >(), and SerializeIncompleteLogs< freeorion_xml_oarchive >().
Referenced by ExtractGameStartMessageData(), ExtractTurnUpdateMessageData(), GameStartMessage(), and TurnUpdateMessage().
SerializeIncompleteLogs< freeorion_bin_iarchive >()
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLogManager & , const unsigned int)
SerializeIncompleteLogs< freeorion_bin_oarchive >()
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLogManager & , const unsigned int)
SerializeIncompleteLogs< freeorion_xml_iarchive >()
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLogManager & , const unsigned int)
SerializeIncompleteLogs< freeorion_xml_oarchive >()
template FO_COMMON_API void SerializeIncompleteLogs< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLogManager & , const unsigned int)