FreeOrion: SerializeCombat.cpp File Reference
SerializeCombat.cpp File Reference
#include "Serialize.h"
#include "Serialize.ipp"
#include "../combat/CombatEvents.h"
#include "../combat/CombatLogManager.h"
Functions
template<typename Archive >
void serialize (Archive &, CombatEvent &, unsigned int const)
template<typename Archive >
void serialize (Archive &ar, BoutBeginEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, BoutEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, SimultaneousEvents &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, InitialStealthEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, StealthChangeEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, StealthChangeEvent::StealthChangeEventDetail &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, WeaponFireEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, IncapacitationEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, FightersAttackFightersEvent &obj, unsigned int const)
template<typename Archive >
void serialize (Archive &ar, FighterLaunchEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, FightersDestroyedEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, WeaponsPlatformEvent &obj, unsigned int const version)
template<typename Archive >
void serialize (Archive &ar, CombatParticipantState &obj, const unsigned int version)
template<typename Archive >
void serialize (Archive &ar, CombatLog &obj, const unsigned int version)
template<typename Archive >
void serialize (Archive &ar, CombatLogManager &obj, const unsigned int version)
template<typename Archive >
void serialize (Archive &ar, CombatInfo &obj, const unsigned int version)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatEvent &, const unsigned int)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, BoutBeginEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, BoutEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, SimultaneousEvents &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, InitialStealthEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, StealthChangeEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, StealthChangeEvent::StealthChangeEventDetail &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, WeaponFireEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, IncapacitationEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, FightersAttackFightersEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, FighterLaunchEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, FightersDestroyedEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, WeaponsPlatformEvent &, unsigned int const)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLog &, const unsigned int)
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLogManager &, const unsigned int)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatEvent &, const unsigned int)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, BoutBeginEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, BoutEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, SimultaneousEvents &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, InitialStealthEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, StealthChangeEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, StealthChangeEvent::StealthChangeEventDetail &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, WeaponFireEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, IncapacitationEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, FightersAttackFightersEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, FighterLaunchEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, FightersDestroyedEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, WeaponsPlatformEvent &, unsigned int const)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLog &, const unsigned int)
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLogManager &, const unsigned int)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatEvent &, const unsigned int)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, BoutBeginEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, BoutEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, SimultaneousEvents &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, InitialStealthEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, StealthChangeEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, StealthChangeEvent::StealthChangeEventDetail &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, WeaponFireEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, IncapacitationEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, FightersAttackFightersEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, FighterLaunchEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, FightersDestroyedEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, WeaponsPlatformEvent &, unsigned int const)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLog &, const unsigned int)
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLogManager &, const unsigned int)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatEvent &, const unsigned int)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, BoutBeginEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, BoutEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, SimultaneousEvents &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, InitialStealthEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, StealthChangeEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, StealthChangeEvent::StealthChangeEventDetail &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, WeaponFireEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, IncapacitationEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, FightersAttackFightersEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, FighterLaunchEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, FightersDestroyedEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, WeaponsPlatformEvent &, unsigned int const)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLog &, const unsigned int)
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLogManager &, const unsigned int)
template<typename Archive >
void SerializeIncompleteLogs (Archive &ar, CombatLogManager &obj, const unsigned int version)
template void SerializeIncompleteLogs< freeorion_bin_iarchive > (freeorion_bin_iarchive &, CombatLogManager &, unsigned int const)
template void SerializeIncompleteLogs< freeorion_bin_oarchive > (freeorion_bin_oarchive &, CombatLogManager &, unsigned int const)
template void SerializeIncompleteLogs< freeorion_xml_iarchive > (freeorion_xml_iarchive &, CombatLogManager &, unsigned int const)
template void SerializeIncompleteLogs< freeorion_xml_oarchive > (freeorion_xml_oarchive &, CombatLogManager &, unsigned int const)
Function Documentation
serialize() [1/17]
template<typename Archive > void serialize (Archive & , CombatEvent & , unsigned int const)
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [2/17]
template<typename Archive > void serialize (Archive & ar, BoutBeginEvent & obj, unsigned int const version)
References BoutBeginEvent::bout, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [3/17]
template<typename Archive > void serialize (Archive & ar, BoutEvent & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), BoutEvent::bout, BoutEvent::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [4/17]
template<typename Archive > void serialize (Archive & ar, SimultaneousEvents & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), SimultaneousEvents::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [5/17]
template<typename Archive > void serialize (Archive & ar, InitialStealthEvent & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), InitialStealthEvent::empire_to_object_visibility, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [6/17]
template<typename Archive > void serialize (Archive & ar, StealthChangeEvent & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), StealthChangeEvent::bout, StealthChangeEvent::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [7/17]
template<typename Archive > void serialize (Archive & ar, StealthChangeEvent::StealthChangeEventDetail & obj, unsigned int const version)
References StealthChangeEvent::StealthChangeEventDetail::attacker_empire_id, StealthChangeEvent::StealthChangeEventDetail::attacker_id, BOOST_CLASS_VERSION(), serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), StealthChangeEvent::StealthChangeEventDetail::target_empire_id, StealthChangeEvent::StealthChangeEventDetail::target_id, and StealthChangeEvent::StealthChangeEventDetail::visibility.
serialize() [8/17]
template<typename Archive > void serialize (Archive & ar, WeaponFireEvent & obj, unsigned int const version)
References WeaponFireEvent::attacker_id, WeaponFireEvent::attacker_owner_id, BOOST_CLASS_VERSION(), WeaponFireEvent::bout, WeaponFireEvent::damage, WeaponFireEvent::power, WeaponFireEvent::round, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), WeaponFireEvent::shield, WeaponFireEvent::target_id, WeaponFireEvent::target_owner_id, and WeaponFireEvent::weapon_name.
serialize() [9/17]
template<typename Archive > void serialize (Archive & ar, IncapacitationEvent & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), IncapacitationEvent::bout, IncapacitationEvent::object_id, IncapacitationEvent::object_owner_id, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [10/17]
template<typename Archive > void serialize (Archive & ar, FightersAttackFightersEvent & obj, unsigned int const)
References BOOST_CLASS_VERSION(), FightersAttackFightersEvent::bout, FightersAttackFightersEvent::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [11/17]
template<typename Archive > void serialize (Archive & ar, FighterLaunchEvent & obj, unsigned int const version)
References FighterLaunchEvent::bout, FighterLaunchEvent::fighter_owner_empire_id, FighterLaunchEvent::launched_from_id, FighterLaunchEvent::number_launched, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [12/17]
template<typename Archive > void serialize (Archive & ar, FightersDestroyedEvent & obj, unsigned int const version)
References BOOST_CLASS_VERSION(), FightersDestroyedEvent::bout, FightersDestroyedEvent::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [13/17]
template<typename Archive > void serialize (Archive & ar, WeaponsPlatformEvent & obj, unsigned int const version)
References WeaponsPlatformEvent::attacker_id, WeaponsPlatformEvent::attacker_owner_id, BOOST_CLASS_VERSION(), WeaponsPlatformEvent::bout, WeaponsPlatformEvent::events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [14/17]
template<typename Archive > void serialize (Archive & ar, CombatParticipantState & obj, const unsigned int version)
References CombatParticipantState::current_health, and CombatParticipantState::max_health.
serialize() [15/17]
template<typename Archive > void serialize (Archive & ar, CombatLog & obj, const unsigned int version)
References CombatLog::combat_events, CombatLog::damaged_object_ids, CombatLog::destroyed_object_ids, CombatLog::empire_ids, ErrorLogger, CombatLog::object_ids, CombatLog::participant_states, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), serialize< freeorion_xml_oarchive >(), CombatLog::system_id, TraceLogger, and CombatLog::turn.
serialize() [16/17]
template<typename Archive > void serialize (Archive & ar, CombatLogManager & obj, const unsigned int version)
References CombatLogManager::m_latest_log_id, CombatLogManager::m_logs, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
serialize() [17/17]
template<typename Archive > void serialize (Archive & ar, CombatInfo & obj, const unsigned int version)
References CombatInfo::combat_events, CombatInfo::damaged_object_ids, CombatInfo::destroyed_object_ids, CombatInfo::destroyed_object_knowers, CombatInfo::empire_ids, CombatInfo::empire_object_visibility, CombatInfo::GetCombatEventsToSerialize(), CombatInfo::GetDamagedObjectsToSerialize(), CombatInfo::GetDestroyedObjectKnowersToSerialize(), CombatInfo::GetDestroyedObjectsToSerialize(), CombatInfo::GetEmpireIdsToSerialize(), CombatInfo::GetEmpireObjectVisibilityToSerialize(), CombatInfo::GetObjectsToSerialize(), GlobalSerializationEncodingForEmpire(), CombatInfo::objects, ObjectMap::swap(), CombatInfo::system_id, and CombatInfo::turn.
serialize< freeorion_bin_iarchive >() [1/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatEvent & , const unsigned int)
Referenced by serialize().
serialize< freeorion_bin_iarchive >() [2/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , BoutBeginEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [3/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , BoutEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [4/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , SimultaneousEvents & , unsigned int const)
serialize< freeorion_bin_iarchive >() [5/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , InitialStealthEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [6/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , StealthChangeEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [7/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , StealthChangeEvent::StealthChangeEventDetail & , unsigned int const)
serialize< freeorion_bin_iarchive >() [8/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , WeaponFireEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [9/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , IncapacitationEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [10/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , FightersAttackFightersEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [11/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , FighterLaunchEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [12/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , FightersDestroyedEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [13/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , WeaponsPlatformEvent & , unsigned int const)
serialize< freeorion_bin_iarchive >() [14/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLog & , const unsigned int)
serialize< freeorion_bin_iarchive >() [15/15]
template void serialize< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_bin_oarchive >() [1/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatEvent & , const unsigned int)
Referenced by serialize().
serialize< freeorion_bin_oarchive >() [2/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , BoutBeginEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [3/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , BoutEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [4/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , SimultaneousEvents & , unsigned int const)
serialize< freeorion_bin_oarchive >() [5/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , InitialStealthEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [6/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , StealthChangeEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [7/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , StealthChangeEvent::StealthChangeEventDetail & , unsigned int const)
serialize< freeorion_bin_oarchive >() [8/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , WeaponFireEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [9/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , IncapacitationEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [10/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , FightersAttackFightersEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [11/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , FighterLaunchEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [12/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , FightersDestroyedEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [13/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , WeaponsPlatformEvent & , unsigned int const)
serialize< freeorion_bin_oarchive >() [14/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLog & , const unsigned int)
serialize< freeorion_bin_oarchive >() [15/15]
template void serialize< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_xml_iarchive >() [1/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatEvent & , const unsigned int)
Referenced by serialize().
serialize< freeorion_xml_iarchive >() [2/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , BoutBeginEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [3/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , BoutEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [4/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , SimultaneousEvents & , unsigned int const)
serialize< freeorion_xml_iarchive >() [5/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , InitialStealthEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [6/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , StealthChangeEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [7/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , StealthChangeEvent::StealthChangeEventDetail & , unsigned int const)
serialize< freeorion_xml_iarchive >() [8/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , WeaponFireEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [9/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , IncapacitationEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [10/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , FightersAttackFightersEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [11/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , FighterLaunchEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [12/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , FightersDestroyedEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [13/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , WeaponsPlatformEvent & , unsigned int const)
serialize< freeorion_xml_iarchive >() [14/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLog & , const unsigned int)
serialize< freeorion_xml_iarchive >() [15/15]
template void serialize< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLogManager & , const unsigned int)
serialize< freeorion_xml_oarchive >() [1/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatEvent & , const unsigned int)
Referenced by serialize().
serialize< freeorion_xml_oarchive >() [2/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , BoutBeginEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [3/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , BoutEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [4/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , SimultaneousEvents & , unsigned int const)
serialize< freeorion_xml_oarchive >() [5/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , InitialStealthEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [6/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , StealthChangeEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [7/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , StealthChangeEvent::StealthChangeEventDetail & , unsigned int const)
serialize< freeorion_xml_oarchive >() [8/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , WeaponFireEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [9/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , IncapacitationEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [10/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , FightersAttackFightersEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [11/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , FighterLaunchEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [12/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , FightersDestroyedEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [13/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , WeaponsPlatformEvent & , unsigned int const)
serialize< freeorion_xml_oarchive >() [14/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLog & , const unsigned int)
serialize< freeorion_xml_oarchive >() [15/15]
template void serialize< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLogManager & , const unsigned int)
SerializeIncompleteLogs()
template<typename Archive > void SerializeIncompleteLogs (Archive & ar, CombatLogManager & obj, const unsigned int version)
References CombatLogManager::m_incomplete_logs, CombatLogManager::m_latest_log_id, SerializeIncompleteLogs< freeorion_bin_iarchive >(), SerializeIncompleteLogs< freeorion_bin_oarchive >(), SerializeIncompleteLogs< freeorion_xml_iarchive >(), and SerializeIncompleteLogs< freeorion_xml_oarchive >().
Referenced by ExtractGameStartMessageData(), ExtractTurnUpdateMessageData(), GameStartMessage(), and TurnUpdateMessage().
SerializeIncompleteLogs< freeorion_bin_iarchive >()
template void SerializeIncompleteLogs< freeorion_bin_iarchive > (freeorion_bin_iarchive & , CombatLogManager & , unsigned int const)
Referenced by SerializeIncompleteLogs().
SerializeIncompleteLogs< freeorion_bin_oarchive >()
template void SerializeIncompleteLogs< freeorion_bin_oarchive > (freeorion_bin_oarchive & , CombatLogManager & , unsigned int const)
Referenced by SerializeIncompleteLogs().
SerializeIncompleteLogs< freeorion_xml_iarchive >()
template void SerializeIncompleteLogs< freeorion_xml_iarchive > (freeorion_xml_iarchive & , CombatLogManager & , unsigned int const)
Referenced by SerializeIncompleteLogs().
SerializeIncompleteLogs< freeorion_xml_oarchive >()
template void SerializeIncompleteLogs< freeorion_xml_oarchive > (freeorion_xml_oarchive & , CombatLogManager & , unsigned int const)
Referenced by SerializeIncompleteLogs().