FreeOrion: ServerFramework.h File Reference
ServerFramework.h File Reference
#include "../python/CommonFramework.h"
#include "../util/MultiplayerCommon.h"
#include <boost/circular_buffer.hpp>
#include <map>
Classes
class PythonServer
Functions
const std::string GetPythonAuthDir ()
const std::string GetPythonChatDir ()
const std::string GetPythonTurnEventsDir ()
const std::string GetPythonUniverseGeneratorDir ()
Function Documentation
GetPythonAuthDir()
const std::string GetPythonAuthDir ()
References GetPythonDir().
Referenced by ServerApp::FillListPlayers(), ServerApp::GetPlayerDelegation(), PythonServer::InitModules(), ServerApp::IsAuthRequiredOrFillRoles(), and ServerApp::IsAuthSuccessAndFillRoles().
GetPythonChatDir()
const std::string GetPythonChatDir ()
References GetPythonDir().
Referenced by PythonServer::InitModules(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
GetPythonTurnEventsDir()
const std::string GetPythonTurnEventsDir ()
References GetPythonDir().
Referenced by ServerApp::ExecuteScriptedTurnEvents(), and PythonServer::InitModules().
GetPythonUniverseGeneratorDir()
const std::string GetPythonUniverseGeneratorDir ()
References GetPythonDir().
Referenced by PythonServer::CreateUniverse(), ServerApp::GenerateUniverse(), and PythonServer::InitModules().