FreeOrion: ServerApp.cpp File Reference
ServerApp.cpp File Reference
#include "ServerApp.h"
#include <ctime>
#include <stdexcept>
#include <thread>
#include <boost/date_time/posix_time/time_formatters.hpp>
#include <boost/filesystem/exception.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/functional/hash.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
#include "SaveLoad.h"
#include "ServerFSM.h"
#include "UniverseGenerator.h"
#include "../combat/CombatEvents.h"
#include "../combat/CombatLogManager.h"
#include "../combat/CombatSystem.h"
#include "../Empire/Empire.h"
#include "../parse/Parse.h"
#include "../universe/Building.h"
#include "../universe/Condition.h"
#include "../universe/Fleet.h"
#include "../universe/FleetPlan.h"
#include "../universe/Planet.h"
#include "../universe/ShipDesign.h"
#include "../universe/Ship.h"
#include "../universe/Special.h"
#include "../universe/Species.h"
#include "../universe/System.h"
#include "../universe/Tech.h"
#include "../universe/UniverseObjectVisitors.h"
#include "../universe/UnlockableItem.h"
#include "../universe/ValueRef.h"
#include "../util/Directories.h"
#include "../util/GameRules.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/LoggerWithOptionsDB.h"
#include "../util/OptionsDB.h"
#include "../util/Order.h"
#include "../util/OrderSet.h"
#include "../util/Pending.h"
#include "../util/Random.h"
#include "../util/SaveGamePreviewUtils.h"
#include "../util/ScopedTimer.h"
#include "../util/SitRepEntry.h"
#include "../util/Version.h"
Classes
struct anonymous_namespace{ServerApp.cpp}::PopulatedOwnedVisitor
Namespaces
anonymous_namespace{ServerApp.cpp}
Functions
std::string anonymous_namespace{ServerApp.cpp}::AIClientExe ()
int anonymous_namespace{ServerApp.cpp}::AIPlayerIDWithName (const ServerNetworking &sn, const std::string &player_name)
Returns ID of AI player with the indicated player_name.
void anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo (std::vector< CombatInfo > &combats)
Clears and refills combats with CombatInfo structs for every system where a combat should occur this turn.
void anonymous_namespace{ServerApp.cpp}::BackProjectSystemCombatInfoObjectMeters (std::vector< CombatInfo > &combats)
Back project meter values of objects in combat info, so that changes to meter values from combat aren't lost when resetting meters during meter updating after combat.
void anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets ()
Deletes empty fleets.
void anonymous_namespace{ServerApp.cpp}::CleanUpBombardmentStateInfo ()
Removes bombardment state info from objects.
bool anonymous_namespace{ServerApp.cpp}::ColonizePlanet (int ship_id, int planet_id)
Does colonization, with safety checks.
bool anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem (int system_id)
Returns true iff there is an appropriate combination of objects in the system with id system_id for a combat to occur.
void anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps (const std::vector< CombatInfo > &combats)
Creates sitreps for all empires involved in a combat.
anonymous_namespace{ServerApp.cpp}::DeclareThreadSafeLogger (effects)
anonymous_namespace{ServerApp.cpp}::DeclareThreadSafeLogger (combat)
void anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo (const std::vector< CombatInfo > &combats)
Takes contents of CombatInfo struct and puts it into the universe.
bool anonymous_namespace{ServerApp.cpp}::EmpireEliminated (int empire_id)
Returns true if empire has been eliminated by the applicable definition of elimination.
int anonymous_namespace{ServerApp.cpp}::EnemyId (int empire_id, const std::set< int > &empire_ids)
void anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem (std::map< int, std::set< int >> &empire_fleets, int system_id)
void anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem (std::map< int, std::set< int >> &empire_planets, int system_id)
void anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem (std::set< int > &visible_fleets, int empire_id, int system_id)
void anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem (std::set< int > &visible_planets, int empire_id, int system_id)
void anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForAIPlayer (std::vector< std::pair< int, int >> &player_id_to_save_game_data_index, const PlayerSetupData &psd, const std::vector< PlayerSaveGameData > &player_save_game_data, const ServerNetworking &sn)
Adds entry to player_id_to_save_game_data_index after validation.
void anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForHumanPlayer (std::vector< std::pair< int, int >> &player_id_to_save_game_data_index, const PlayerSetupData &psd, int setup_data_player_id, const std::vector< PlayerSaveGameData > &player_save_game_data, const ServerNetworking &sn)
Adds entry to player_id_to_save_game_data_index after validation.
void anonymous_namespace{ServerApp.cpp}::HandleColonization ()
Determines which ships ordered to colonize planet succeed, does appropriate colonization, and cleans up after colonization orders.
void anonymous_namespace{ServerApp.cpp}::HandleGifting ()
Determines which fleets or planets ordered given to other empires, and sets their new ownership.
void anonymous_namespace{ServerApp.cpp}::HandleInvasion ()
Determines which ships ordered to invade planets, does invasion and ground combat resolution.
void anonymous_namespace{ServerApp.cpp}::HandleScrapping ()
Destroys suitable objects that have been ordered scrapped.
bool anonymous_namespace{ServerApp.cpp}::HumanPlayerWithIdConnected (const ServerNetworking &sn, int id)
Verifies that a human player is connected with the indicated id.
bool anonymous_namespace{ServerApp.cpp}::IsInServerSaveDir (const fs::path &path)
Check that path is a file or directory in the server save directory.
std::vector< std::string > anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories (const fs::path &directory)
Generates information on the subdirectories of directory.
void anonymous_namespace{ServerApp.cpp}::ResolveGroundCombat (std::map< int, double > &empires_troops)
Given initial set of ground forces on planet, determine ground forces on planet after a turn of ground combat.
void Seed (unsigned int seed)
void anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo (const std::vector< CombatInfo > &combats)
Records info in Empires about what they destroyed or had destroyed during combat.
void anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo (const std::map< int, std::map< int, double >> &planet_empire_invasion_troops)
Records info in Empires about where they invaded.
void anonymous_namespace{ServerApp.cpp}::UpdateEmpirePolicies ()
Check validity of adopted policies, overwrite initial adopted policies with those currently adopted, update adopted turns counters.
void UpdateEmpireSupply (bool precombat=false)
void anonymous_namespace{ServerApp.cpp}::UpdateResourceCenterFocusHistoryInfo ()
Causes ResourceCenters (Planets) to update their focus records.
int anonymous_namespace{ServerApp.cpp}::VectorIndexForPlayerSaveGameDataForEmpireID (const std::vector< PlayerSaveGameData > &player_save_game_data, int empire_id)
Returns index into vector parameter that matches parameter empire id.
Function Documentation
Seed()
void Seed (unsigned int seed)
Referenced by AutoResolveCombat(), anonymous_namespace{ServerApp.cpp}::EnemyId(), ServerApp::GenerateUniverse(), AIClientApp::HandleMessage(), ServerApp::PostCombatProcessTurns(), Idle::react(), MPLobby::react(), and MapWnd::RenderStarfields().
UpdateEmpireSupply()
void UpdateEmpireSupply (bool precombat = false)
References ServerApp::Empires(), ServerApp::GetSupplyManager(), and SupplyManager::Update().
Referenced by ServerApp::LoadGameInit(), ServerApp::NewGameInitConcurrentWithJoiners(), and ServerApp::PostCombatProcessTurns().