FreeOrion: ServerFSM.cpp File Reference
ServerFSM.cpp File Reference
#include "ServerFSM.h"
#include "SaveLoad.h"
#include "ServerApp.h"
#include "ServerNetworking.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../universe/System.h"
#include "../universe/Species.h"
#include "../network/Message.h"
#include "../util/Directories.h"
#include "../util/GameRules.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/LoggerWithOptionsDB.h"
#include "../util/Order.h"
#include "../util/OrderSet.h"
#include "../util/Random.h"
#include "../util/ModeratorAction.h"
#include <boost/filesystem/path.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/asio/high_resolution_timer.hpp>
#include <boost/functional/hash.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/uuid/nil_generator.hpp>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <iterator>
Namespaces
anonymous_namespace{ServerFSM.cpp}
Macros
#define MESSAGE_EVENT_CASE(r, data, name)
Functions
anonymous_namespace{ServerFSM.cpp}::DeclareThreadSafeLogger (FSM)
std::string anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName (const std::string &player_name, std::list< std::pair< int, PlayerSetupData >> &players)
std::string anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName (int current_turn)
CombatLogManager & GetCombatLogManager ()
returns the singleton combat log manager
std::string anonymous_namespace{ServerFSM.cpp}::GetHostNameFromSinglePlayerSetupData (const SinglePlayerSetupData &single_player_setup_data)
EmpireColor anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour (const std::list< std::pair< int, PlayerSetupData >> &psd, const std::map< int, SaveGameEmpireData > &sged=std::map< int, SaveGameEmpireData >())
bool anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage (const Error &msg, ServerApp &server)
Return true for fatal errors.
bool anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged (const PlayerSetupData &lhs, const PlayerSetupData &rhs)
void anonymous_namespace{ServerFSM.cpp}::LogPlayerSetupData (const std::list< std::pair< int, PlayerSetupData >> &psd)
void anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers (const Message &message)
void anonymous_namespace{ServerFSM.cpp}::SendMessageToHost (const Message &message)
Variables
constexpr EmpireColor anonymous_namespace{ServerFSM.cpp}::CLR_SERVER {255, 255, 255, 255}
constexpr EmpireColor anonymous_namespace{ServerFSM.cpp}::CLR_ZERO {0, 0, 0, 0}
const auto SHUTDOWN_POLLING_TIME = std::chrono::milliseconds(5000)
Macro Definition Documentation
MESSAGE_EVENT_CASE
#define MESSAGE_EVENT_CASE (r, data, name)
Value:
else if (dynamic_cast<const name*>(event_ptr))                      \
        most_derived_message_type_str = BOOST_PP_STRINGIZE(name);
Referenced by ServerFSM::unconsumed_event().
Function Documentation
GetCombatLogManager()
CombatLogManager& GetCombatLogManager ()
returns the singleton combat log manager
Referenced by GetCombatLog(), ServerFSM::HandleNonLobbyDisconnection(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), PlayingGame::react(), and WaitingForTurnEnd::react().
Variable Documentation
SHUTDOWN_POLLING_TIME
const auto SHUTDOWN_POLLING_TIME = std::chrono::milliseconds(5000)