FreeOrion: ServerFramework.cpp File Reference
ServerFramework.cpp File Reference
#include "ServerFramework.h"
#include "ServerWrapper.h"
#include "../python/SetWrapper.h"
#include "../python/CommonWrappers.h"
#include "../util/Logger.h"
#include "../universe/Condition.h"
#include "../universe/Universe.h"
#include <boost/filesystem.hpp>
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
#include <boost/python/suite/indexing/map_indexing_suite.hpp>
#include <boost/python/docstring_options.hpp>
#include <boost/python/stl_iterator.hpp>
#include <stdexcept>
Functions
BOOST_PYTHON_MODULE (freeorion)
auto GetPythonAuthDir () -> const std::string
auto GetPythonChatDir () -> const std::string
auto GetPythonTurnEventsDir () -> const std::string
auto GetPythonUniverseGeneratorDir () -> const std::string
Function Documentation
BOOST_PYTHON_MODULE()
BOOST_PYTHON_MODULE (freeorion)
References FreeOrionPython::SetWrapper< ElementType >::Wrap(), FreeOrionPython::WrapConfig(), FreeOrionPython::WrapEmpire(), FreeOrionPython::WrapGalaxySetupData(), FreeOrionPython::WrapGameStateEnums(), FreeOrionPython::WrapServer(), and FreeOrionPython::WrapUniverseClasses().
GetPythonAuthDir()
auto GetPythonAuthDir () -> const std::string
References GetPythonDir().
Referenced by ServerApp::FillListPlayers(), ServerApp::GetPlayerDelegation(), PythonServer::InitModules(), ServerApp::IsAuthRequiredOrFillRoles(), and ServerApp::IsAuthSuccessAndFillRoles().
GetPythonChatDir()
auto GetPythonChatDir () -> const std::string
References GetPythonDir().
Referenced by PythonServer::InitModules(), ServerApp::LoadChatHistory(), and ServerApp::PushChatMessage().
GetPythonTurnEventsDir()
auto GetPythonTurnEventsDir () -> const std::string
References GetPythonDir().
Referenced by ServerApp::ExecuteScriptedTurnEvents(), and PythonServer::InitModules().
GetPythonUniverseGeneratorDir()
auto GetPythonUniverseGeneratorDir () -> const std::string
References GetPythonDir().
Referenced by PythonServer::CreateUniverse(), ServerApp::GenerateUniverse(), and PythonServer::InitModules().