FreeOrion: Ship.cpp File Reference
Ship.cpp File Reference
#include "Ship.h"
#include "Fleet.h"
#include "ShipDesign.h"
#include "ShipHull.h"
#include "ShipPart.h"
#include "Species.h"
#include "UniverseObjectVisitor.h"
#include "Universe.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../util/AppInterface.h"
#include "../util/GameRules.h"
#include "../util/Logger.h"
#include "../util/Random.h"
#include "../util/i18n.h"
Namespaces
anonymous_namespace{Ship.cpp}
Functions
const Species * GetSpecies (const std::string &name)
std::string NewMonsterName ()
std::vector< float > anonymous_namespace{Ship.cpp}::WeaponDamageImpl (const Ship *ship, const ShipDesign *design, float DR, bool max, bool include_fighters)
Function Documentation
GetSpecies()
const Species* GetSpecies (const std::string & name)
Referenced by Ship::CanColonize(), Ship::HasTag(), Ship::SetSpecies(), and Ship::Ship().
NewMonsterName()
std::string NewMonsterName ()
References RandInt(), RomanNumber(), UserString(), and UserStringList().
Referenced by Effect::CreateShip::Execute(), and FreeOrionPython::WrapServer().