FreeOrion: ShipDesign.cpp File Reference
ShipDesign.cpp File Reference
#include "ShipDesign.h"
#include "../util/OptionsDB.h"
#include "../util/Logger.h"
#include "../util/AppInterface.h"
#include "../util/GameRules.h"
#include "../util/CheckSums.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "Conditions.h"
#include "Effects.h"
#include "Planet.h"
#include "Ship.h"
#include "Predicates.h"
#include "Species.h"
#include "Universe.h"
#include "ValueRefs.h"
#include "Enums.h"
#include <cfloat>
#include <unordered_set>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/fstream.hpp>
#include <boost/uuid/nil_generator.hpp>
#include <boost/uuid/random_generator.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <boost/lexical_cast.hpp>
Namespaces
anonymous_namespace{ShipDesign.cpp}
CheckSums
Functions
void anonymous_namespace{ShipDesign.cpp}::AddDesignToUniverse (std::unordered_map< std::string, int > &design_generic_ids, const std::unique_ptr< ShipDesign > &design, bool monster)
void anonymous_namespace{ShipDesign.cpp}::AddRules (GameRules &rules)
template<typename PendingShips , typename Map1 , typename Map2 , typename Ordering >
void anonymous_namespace{ShipDesign.cpp}::CheckPendingAndFillDesignsOrderingAndNameTables (PendingShips &pending, Map1 &designs, Ordering &ordering, Map2 &name_to_uuid, bool are_monsters)
void CheckSums::CheckSumCombine (unsigned int &sum, const HullType::Slot &slot)
bool anonymous_namespace{ShipDesign.cpp}::DesignsTheSame (const ShipDesign &one, const ShipDesign &two)
template<typename Map1 , typename Map2 , typename Ordering >
void anonymous_namespace{ShipDesign.cpp}::FillDesignsOrderingAndNameTables (PredefinedShipDesignManager::ParsedShipDesignsType &parsed_designs, Map1 &designs, Ordering &ordering, Map2 &name_to_uuid)
const HullType * GetHullType (const std::string &name)
Returns the ship HullType specification object with name name.
HullTypeManager & GetHullTypeManager ()
returns the singleton hull type manager
const PartType * GetPartType (const std::string &name)
Returns the ship PartType specification object with name name.
PartTypeManager & GetPartTypeManager ()
returns the singleton part type manager
const ShipDesign * GetPredefinedShipDesign (const std::string &name)
Returns the predefined ShipDesign with the name name.
PredefinedShipDesignManager & GetPredefinedShipDesignManager ()
returns the singleton predefined ship design manager type manager
const ShipDesign * GetShipDesign (int ship_design_id)
Returns the ShipDesign specification object with id ship_design_id.
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipDesign.cpp}::IncreaseMeter (MeterType meter_type, const std::string &part_name, float increase, bool allow_stacking=true)
std::tuple< bool, std::unordered_map< boost::uuids::uuid, std::pair< std::unique_ptr< ShipDesign >, boost::filesystem::path >, boost::hash< boost::uuids::uuid > >, std::vector< boost::uuids::uuid > > LoadShipDesignsAndManifestOrderFromParseResults (PredefinedShipDesignManager::ParsedShipDesignsType &designs_paths_and_ordering)
Load all ship designs in parsed and return a tuple is_error, the map from uuid to ship design and path and the ship ordering from the manifest.
bool operator== (const ShipDesign &first, const ShipDesign &second)
Variables
const std::string anonymous_namespace{ShipDesign.cpp}::EMPTY_STRING
FO_COMMON_API const int INVALID_DESIGN_ID = -1
bool anonymous_namespace{ShipDesign.cpp}::temp_bool = RegisterGameRules(&AddRules)
Function Documentation
GetHullType()
const HullType* GetHullType (const std::string & name)
Returns the ship HullType specification object with name name.
If no such HullType exists, 0 is returned instead.
References HullTypeManager::GetHullType(), and GetHullTypeManager().
Referenced by DesignWnd::MainPanel::AddDesign(), Empire::AddHullType(), EmptyHullsListBox::BaseLeftClicked(), ShipDesign::BuildStatCaches(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), ValueRef::ComplexVariable< T >::Eval(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Ship::HasTag(), ClientUI::HullIcon(), ClientUI::HullTexture(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionTime(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), DesignWnd::MainPanel::SetHull(), Ship::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipHull().
GetHullTypeManager()
HullTypeManager& GetHullTypeManager ()
returns the singleton hull type manager
References HullTypeManager::GetHullTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), ShipDesign::GetHull(), GetHullType(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ShipDesign::MaybeInvalidDesign(), EmptyHullsListBox::PopulateCore(), IApp::StartBackgroundParsing(), ShipDesignManager::StartGame(), and ClientUI::ZoomToContent().
GetPartType()
const PartType* GetPartType (const std::string & name)
Returns the ship PartType specification object with name name.
If no such PartType exists, 0 is returned instead.
References PartTypeManager::GetPartType(), and GetPartTypeManager().
Referenced by Empire::AddPartType(), ShipDesign::AdjustedAttack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStatsP(), ShipDesign::BuildStatCaches(), ShipDesign::CanColonize(), Ship::ColonyCapacity(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), DesignWnd::MainPanel::DesignChanged(), ValueRef::ComplexVariable< T >::Eval(), Ship::FighterCount(), Ship::FighterMax(), Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Ship::HasTag(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), ShipDesign::MaybeInvalidDesign(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartClassSimpleMatch::operator()(), ClientUI::PartIcon(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionLocation(), ShipDesign::ProductionTime(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), SlotControl::SetPart(), DesignWnd::MainPanel::SetPart(), Ship::Ship(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), Ship::TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), ShipDesign::Weapons(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipPart().
GetPartTypeManager()
PartTypeManager& GetPartTypeManager ()
returns the singleton part type manager
References PartTypeManager::GetPartTypeManager().
Referenced by CheckSumContent(), DesignWnd::PartPalette::CompleteConstruction(), ShipDesign::Defense(), Universe::GetEffectsAndTargets(), GetPartType(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PartsListBox::GroupAvailableDisplayableParts(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().
GetPredefinedShipDesign()
const ShipDesign* GetPredefinedShipDesign (const std::string & name)
Returns the predefined ShipDesign with the name name.
If no such ship design exists, 0 is returned instead.
References Universe::GetGenericShipDesign(), and GetUniverse().
Referenced by Effect::CreateShip::Execute(), Effect::GenerateSitRepMessage::Execute(), ValueRef::anonymous_namespace{ValueRefs.cpp}::GetIntKeyFromContentStringKey(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), anonymous_namespace{VarText.cpp}::PredefinedShipDesignString(), and FreeOrionPython::WrapUniverseClasses().
GetPredefinedShipDesignManager()
PredefinedShipDesignManager& GetPredefinedShipDesignManager ()
returns the singleton predefined ship design manager type manager
References PredefinedShipDesignManager::GetPredefinedShipDesignManager().
Referenced by CheckSumContent(), MessageWndEdit::FindGameWords(), ServerApp::GenerateUniverse(), Empire::LockItem(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetMonsterList(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetPremadeList(), IApp::StartBackgroundParsing(), and Empire::UnlockItem().
GetShipDesign()
const ShipDesign* GetShipDesign (int ship_design_id)
Returns the ShipDesign specification object with id ship_design_id.
If no such ShipDesign is present in the Universe (because it doesn't exist, or isn't know to this client), 0 is returned instead.
References Universe::GetShipDesign(), and GetUniverse().
Referenced by DesignWnd::MainPanel::AcceptDrops(), Ship::AllWeaponsDamage(), Ship::AllWeaponsMaxDamage(), CompletedDesignsListBox::BaseLeftClicked(), MonstersListBox::BaseLeftClicked(), AllDesignsListBox::BaseLeftClicked(), CompletedDesignsListBox::BaseRightClicked(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), anonymous_namespace{DesignWnd.cpp}::CanAddDesignToDisplayedDesigns(), Empire::CheckProductionProgress(), CompletedDesignsListBox::ChildrenDraggedAwayCore(), MonstersListBox::ChildrenDraggedAwayCore(), AllDesignsListBox::ChildrenDraggedAwayCore(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), Ship::Design(), DesignWnd::MainPanel::EditingCurrentDesign(), ValueRef::NameLookup::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateShip::Execute(), ShipDesignOrder::ExecuteImpl(), Ship::HasTag(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{DesignWnd.cpp}::DisplayedShipDesignManager::IsObsolete(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue(), ObjectListWnd::ObjectRightClicked(), Universe::Objects(), CompletedDesignsListBox::PopulateCore(), BuildDesignatorWnd::BuildSelector::PopulateList(), Empire::ProducibleItem(), Empire::ProductionCostAndTime(), ProductionQueue::ProductionItem::ProductionItem(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::ResetShipDesignLabels(), BuildDesignatorWnd::SetBuild(), DesignWnd::MainPanel::SetDesign(), anonymous_namespace{DesignWnd.cpp}::SetObsoleteInDisplayedDesigns(), Ship::Ship(), Empire::ShipDesignAvailable(), ClientUI::ShipDesignIcon(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), Empire::UpdateOwnedObjectCounters(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipDesign().
LoadShipDesignsAndManifestOrderFromParseResults()
std::tuple< bool, std::unordered_map<boost::uuids::uuid, std::pair<std::unique_ptr<ShipDesign>, boost::filesystem::path>, boost::hash<boost::uuids::uuid> >, std::vector<boost::uuids::uuid> > LoadShipDesignsAndManifestOrderFromParseResults (PredefinedShipDesignManager::ParsedShipDesignsType & parsed)
Load all ship designs in parsed and return a tuple is_error, the map from uuid to ship design and path and the ship ordering from the manifest.
References DebugLogger, ErrorLogger, INVALID_OBJECT_ID, TraceLogger, and WarnLogger.
Referenced by anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::CheckPendingDesigns(), anonymous_namespace{ShipDesign.cpp}::FillDesignsOrderingAndNameTables(), and HullType::serialize().
operator==()
bool operator== (const ShipDesign & first, const ShipDesign & second)
References ShipDesign::Hull(), ShipDesign::Parts(), and PredefinedShipDesignManager::s_instance.
Referenced by ShipDesign::PartClassCount().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID = -1
Referenced by PredefinedShipDesignManager::GetDesignID().