FreeOrion: ShipHull.h File Reference
ShipHull.h File Reference
#include "CommonParams.h"
#include "ScriptingContext.h"
#include "../util/Enum.h"
#include "../util/Pending.h"
Classes
class ShipHullManager
Holds FreeOrion hull types.
Namespaces
CheckSums
Functions
void CheckSums::CheckSumCombine (unsigned int &sum, const ShipHull::Slot &slot)
FO_ENUM ((ShipSlotType),((INVALID_SHIP_SLOT_TYPE, -1))((SL_EXTERNAL))((SL_INTERNAL))((SL_CORE))((NUM_SHIP_SLOT_TYPES))) class FO_COMMON_API ShipHull
Types of slots in ShipHulls Parts may be restricted to only certain slot types.
FO_COMMON_API auto GetShipHull (const std::string &name) -> const ShipHull *
Returns the ship ShipHull specification object with name name.
FO_COMMON_API auto GetShipHullManager () -> ShipHullManager &
Returns the singleton hull type manager.
Variables
FO_COMMON_API const int INVALID_DESIGN_ID
Function Documentation
FO_ENUM()
FO_ENUM ((ShipSlotType) , ((INVALID_SHIP_SLOT_TYPE, -1))((SL_EXTERNAL))((SL_INTERNAL))((SL_CORE))((NUM_SHIP_SLOT_TYPES)))
Types of slots in ShipHulls Parts may be restricted to only certain slot types.
Specification for the hull, or base, on which ship designs are created by adding parts. The hull determines some final design characteristics directly, and also determine how many parts can be added to the design.
Returns name of hull
Returns description, including a description of the stats and effects of this hull
Returns starlane speed of hull
Returns fuel capacity of hull
Returns stealth of hull
Returns structure of hull
Returns shields of hull
Returns colonist capacity of hull
Returns the troop capacity of hull
Returns detection ability of hull
Returns true if the production cost and time are invariant (does not depend on) the location
Returns the number of production points required to produce this hull
Returns the number of turns required to produce this hull
Returns whether this hull type is producible by players and appears on the design screen
Returns total number of of slots in hull
Returns number of of slots of indicated type in hull
Returns vector of slots in hull
Returns the condition that determines the locations where ShipDesign containing hull can be produced
Returns the names of other content that cannot be used in the same ship design as this part
Returns the EffectsGroups that encapsulate the effects this part hull has.
Returns the image that represents the hull on the design screen
Returns the small icon to represent hull
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function. Useful to verify that the parsed content is consistent without sending it all between clients and server.
References CheckSums::CheckSumCombine(), tag_parser::description, FO_COMMON_API, INVALID_DESIGN_ID, and anonymous_namespace{XMLDoc.cpp}::Name.
GetShipHull()
FO_COMMON_API auto GetShipHull (const std::string & name) -> const ShipHull *
Returns the ship ShipHull specification object with name name.
If no such ShipHull exists, nullptr is returned instead.
GetShipHullManager()
FO_COMMON_API auto GetShipHullManager () -> ShipHullManager &
Returns the singleton hull type manager.
References ShipHullManager::GetShipHullManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ShipDesign::MaybeInvalidDesign(), ShipDesign::Parts(), EmptyHullsListBox::PopulateCore(), IApp::StartBackgroundParsing(), ShipDesignManager::StartGame(), and ClientUI::ZoomToContent().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by FO_ENUM().