FreeOrion: ShipHull.cpp File Reference
ShipHull.cpp File Reference
#include "ShipHull.h"
#include "ConditionSource.h"
#include "Effects.h"
#include "Enums.h"
#include "ValueRefs.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "../util/GameRules.h"
Namespaces
anonymous_namespace{ShipHull.cpp}
CheckSums
Functions
void anonymous_namespace{ShipHull.cpp}::AddRules (GameRules &rules)
void CheckSums::CheckSumCombine (unsigned int &sum, const ShipHull::Slot &slot)
const ShipHull * GetShipHull (const std::string &name)
Returns the ship ShipHull specification object with name name.
ShipHullManager & GetShipHullManager ()
Returns the singleton hull type manager.
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipHull.cpp}::IncreaseMeter (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
Variables
const float anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_COST = 999999.9f
const int anonymous_namespace{ShipHull.cpp}::ARBITRARY_LARGE_TURNS = 999999
bool anonymous_namespace{ShipHull.cpp}::temp_bool = RegisterGameRules(&AddRules)
Function Documentation
GetShipHull()
const ShipHull* GetShipHull (const std::string & name) -> const ShipHull *
Returns the ship ShipHull specification object with name name.
If no such ShipHull exists, nullptr is returned instead.
References ShipHullManager::GetShipHullManager().
Referenced by DesignWnd::MainPanel::AddDesign(), EmptyHullsListBox::BaseLeftClicked(), ShipDesign::BuildStatCaches(), ValueRef::ComplexVariable< T >::Eval(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), GetSpeciesConst(), Ship::HasTag(), ClientUI::HullIcon(), ClientUI::HullTexture(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionLocation(), ShipDesign::ProductionTime(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), DesignWnd::MainPanel::SetHull(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), Ship::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipHull().
GetShipHullManager()
ShipHullManager& GetShipHullManager ()
Returns the singleton hull type manager.
References ShipHullManager::GetShipHullManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ShipDesign::MaybeInvalidDesign(), ShipDesign::Parts(), EmptyHullsListBox::PopulateCore(), IApp::StartBackgroundParsing(), ShipDesignManager::StartGame(), and ClientUI::ZoomToContent().