FreeOrion: ShipPart.h File Reference
ShipPart.h File Reference
#include "CommonParams.h"
#include "../util/Enum.h"
#include "../util/Pending.h"
Classes
class ShipPartManager
Holds FreeOrion available ShipParts.
Functions
FO_ENUM ((ShipPartClass),((INVALID_SHIP_PART_CLASS, -1))((PC_DIRECT_WEAPON))((PC_FIGHTER_BAY))((PC_FIGHTER_HANGAR))((PC_SHIELD))((PC_ARMOUR))((PC_TROOPS))((PC_DETECTION))((PC_STEALTH))((PC_FUEL))((PC_COLONY))((PC_SPEED))((PC_GENERAL))((PC_BOMBARD))((PC_INDUSTRY))((PC_RESEARCH))((PC_INFLUENCE))((PC_PRODUCTION_LOCATION))((NUM_SHIP_PART_CLASSES))) class FO_COMMON_API ShipPart
Classifies ShipParts by general function.
FO_COMMON_API const ShipPart * GetShipPart (const std::string &name)
Returns the ShipPart specification object with name name.
FO_COMMON_API ShipPartManager & GetShipPartManager ()
Returns the singleton ShipPart manager.
Variables
FO_COMMON_API const int INVALID_DESIGN_ID
Function Documentation
FO_ENUM()
FO_ENUM ((ShipPartClass) , ((INVALID_SHIP_PART_CLASS, -1))((PC_DIRECT_WEAPON))((PC_FIGHTER_BAY))((PC_FIGHTER_HANGAR))((PC_SHIELD))((PC_ARMOUR))((PC_TROOPS))((PC_DETECTION))((PC_STEALTH))((PC_FUEL))((PC_COLONY))((PC_SPEED))((PC_GENERAL))((PC_BOMBARD))((PC_INDUSTRY))((PC_RESEARCH))((PC_INFLUENCE))((PC_PRODUCTION_LOCATION))((NUM_SHIP_PART_CLASSES)))
Classifies ShipParts by general function.
Describes an equipable part for a ship.
Returns name of part
Returns description string, generally a UserString key.
Returns that class of part that this is.
Returns a translated description of the part capacity, with numeric value
Returns true if this part can be placed in a slot of the indicated type
Returns the condition for possible targets. may be nullptr if no condition was specified.
Returns true if the production cost and time are invariant (does not depend on) the location
Returns the number of production points required to produce this part
Returns the number of turns required to produce this part
Returns whether this part type is producible by players and appears on the design screen
Returns the condition that determines the locations where ShipDesign containing part can be produced
Returns the names of other content that cannot be used in the same ship design as this part
Returns the EffectsGroups that encapsulate the effects this part has.
Returns icon graphic that represents part in UI
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function. Useful to verify that the parsed content is consistent without sending it all between clients and server.
Damage for a hangar bay, shots per turn for a weapon, etc.
References tag_parser::description, INVALID_DESIGN_ID, and anonymous_namespace{XMLDoc.cpp}::Name.
GetShipPart()
FO_COMMON_API const ShipPart* GetShipPart (const std::string & name)
Returns the ShipPart specification object with name name.
If no such ShipPart exists, nullptr is returned instead.
GetShipPartManager()
FO_COMMON_API ShipPartManager& GetShipPartManager ()
Returns the singleton ShipPart manager.
References ShipPartManager::GetShipPartManager().
Referenced by CheckSumContent(), DesignWnd::PartPalette::CompleteConstruction(), ShipDesign::Defense(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PartsListBox::GroupAvailableDisplayableParts(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by FO_ENUM().