FreeOrion: Ship.h File Reference
Ship.h File Reference
#include "UniverseObject.h"
#include "Meter.h"
#include "../util/Export.h"
Classes
class Ship
Functions
FO_COMMON_API std::string NewMonsterName ()
Variables
FO_COMMON_API const int ALL_EMPIRES
FO_COMMON_API const int BEFORE_FIRST_TURN
FO_COMMON_API const int INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_GAME_TURN
FO_COMMON_API const int INVALID_OBJECT_ID
Function Documentation
FO_COMMON_API std::string NewMonsterName ()
References RandSmallInt(), RomanNumber(), UserString(), and UserStringList().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateMonster(), and Effect::CreateShip::Execute().
Variable Documentation
FO_COMMON_API const int ALL_EMPIRES
Referenced by Ship::ContainerObjectID().
FO_COMMON_API const int BEFORE_FIRST_TURN
Referenced by UniverseObject::AgeInTurns(), Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), Condition::HasSpecial::Dump(), Condition::Turn::Eval(), Condition::HasSpecial::Eval(), Condition::CreatedOnTurn::Eval(), Condition::HasSpecial::Match(), Condition::CreatedOnTurn::Match(), ServerApp::NewGameInitConcurrentWithJoiners(), and anonymous_namespace{ServerWrapper.cpp}::ShipDesignCreate().
FO_COMMON_API const int INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_GAME_TURN
FO_COMMON_API const int INVALID_OBJECT_ID