FreeOrion: ShipPartHull.h File Reference
ShipPartHull.h File Reference
#include <boost/serialization/access.hpp>
#include <boost/serialization/nvp.hpp>
#include "CommonParams.h"
#include "../util/Pending.h"
Classes
class HullType
Specification for the hull, or base, on which ship designs are created by adding parts.
struct HullType::Slot
class HullTypeManager
Holds FreeOrion hull types.
struct HullTypeStats
Hull stats.
Namespaces
CheckSums
Functions
void CheckSums::CheckSumCombine (unsigned int &sum, const HullType::Slot &slot)
FO_COMMON_API const HullType * GetHullType (const std::string &name)
Returns the ship HullType specification object with name name.
FO_COMMON_API HullTypeManager & GetHullTypeManager ()
returns the singleton hull type manager
Variables
FO_COMMON_API const int ALL_EMPIRES
FO_COMMON_API const int INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_GAME_TURN
FO_COMMON_API const int INVALID_OBJECT_ID
Function Documentation
GetHullType()
FO_COMMON_API const HullType* GetHullType (const std::string & name)
Returns the ship HullType specification object with name name.
If no such HullType exists, 0 is returned instead.
GetHullTypeManager()
FO_COMMON_API HullTypeManager& GetHullTypeManager ()
returns the singleton hull type manager
References HullTypeManager::GetHullTypeManager().
Referenced by CheckSumContent(), Universe::GetEffectsAndTargets(), GetHullType(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ShipDesign::MaybeInvalidDesign(), ShipDesign::Parts(), EmptyHullsListBox::PopulateCore(), IApp::StartBackgroundParsing(), ShipDesignManager::StartGame(), and ClientUI::ZoomToContent().
Variable Documentation
ALL_EMPIRES
FO_COMMON_API const int ALL_EMPIRES
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by HullType::Detection().
INVALID_GAME_TURN
FO_COMMON_API const int INVALID_GAME_TURN
INVALID_OBJECT_ID
FO_COMMON_API const int INVALID_OBJECT_ID