FreeOrion: ShipPart.cpp File Reference
ShipPart.cpp File Reference
#include "ShipPart.h"
#include <boost/algorithm/string/case_conv.hpp>
#include "ConditionSource.h"
#include "Effects.h"
#include "ShipHull.h"
#include "ValueRefs.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../util/CheckSums.h"
#include "../util/GameRules.h"
Namespaces
anonymous_namespace{ShipPart.cpp}
Functions
const ShipPart * GetShipPart (const std::string &name)
Returns the ShipPart specification object with name name.
ShipPartManager & GetShipPartManager ()
Returns the singleton ShipPart manager.
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, float fixed_increase)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, const std::string &part_name, std::unique_ptr< ValueRef::ValueRef< double >> &&increase_vr, bool allow_stacking=true)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeter (MeterType meter_type, const std::string &part_name, float fixed_increase, bool allow_stacking=true)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled (MeterType meter_type, float base_increase, const std::string &scaling_factor_rule_name)
std::shared_ptr< Effect::EffectsGroup > anonymous_namespace{ShipPart.cpp}::IncreaseMeterRuleScaled (MeterType meter_type, const std::string &part_name, float base_increase, const std::string &scaling_factor_rule_name, bool allow_stacking=true)
Variables
const float anonymous_namespace{ShipPart.cpp}::ARBITRARY_LARGE_COST = 999999.9f
const int anonymous_namespace{ShipPart.cpp}::ARBITRARY_LARGE_TURNS = 999999
Function Documentation
GetShipPart()
const ShipPart* GetShipPart (const std::string & name)
Returns the ShipPart specification object with name name.
If no such ShipPart exists, nullptr is returned instead.
References ShipPartManager::GetShipPartManager().
Referenced by ShipDesign::AdjustedAttack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStats(), ShipDesign::BuildStatCaches(), ShipDesign::CanColonize(), Ship::ColonyCapacity(), DesignWnd::MainPanel::DesignChanged(), ValueRef::ComplexVariable< T >::Eval(), Ship::FighterCount(), Ship::FighterMax(), Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), GetSpeciesConst(), Ship::HasTag(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), ShipDesign::MaybeInvalidDesign(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasPartClassSimpleMatch::operator()(), ClientUI::PartIcon(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionLocation(), ShipDesign::ProductionTime(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), SlotControl::SetPart(), DesignWnd::MainPanel::SetPart(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), Ship::Ship(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), Ship::TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), ShipDesign::Weapons(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipPart().
GetShipPartManager()
ShipPartManager& GetShipPartManager ()
Returns the singleton ShipPart manager.
References ShipPartManager::GetShipPartManager().
Referenced by CheckSumContent(), DesignWnd::PartPalette::CompleteConstruction(), ShipDesign::Defense(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PartsListBox::GroupAvailableDisplayableParts(), IApp::StartBackgroundParsing(), and ClientUI::ZoomToContent().