FreeOrion: ShipDesign.h File Reference
ShipDesign.h File Reference
#include "ValueRefFwd.h"
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/variant.hpp>
#include <boost/serialization/access.hpp>
#include <boost/serialization/nvp.hpp>
#include "EnumsFwd.h"
#include "../util/Export.h"
Classes
struct CommonParams
class HullType
struct HullType::Slot
class HullTypeManager
struct HullTypeStats
struct MoreCommonParams
class PartType
class PartTypeManager
class PredefinedShipDesignManager
class ShipDesign
Returns true if the two designs have the same hull and parts.
Namespaces
Condition
Effect
Functions
FO_COMMON_API const HullType * GetHullType (const std::string &name)
FO_COMMON_API const HullTypeManager & GetHullTypeManager ()
FO_COMMON_API const PartType * GetPartType (const std::string &name)
FO_COMMON_API const PartTypeManager & GetPartTypeManager ()
FO_COMMON_API const ShipDesign * GetPredefinedShipDesign (const std::string &name)
const FO_COMMON_API PredefinedShipDesignManager & GetPredefinedShipDesignManager ()
FO_COMMON_API const ShipDesign * GetShipDesign (int ship_design_id)
FO_COMMON_API bool operator== (const ShipDesign &first, const ShipDesign &second)
Function Documentation
FO_COMMON_API const HullType* GetHullType (const std::string & name)
Returns the ship HullType specification object with name name. If no such HullType exists, 0 is returned instead.
References HullTypeManager::GetHullType(), and GetHullTypeManager().
Referenced by DesignWnd::AddDesign(), Empire::AddHullType(), BasesListBox::BaseLeftClicked(), ShipDesign::BuildStatCaches(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), ValueRef::ComplexVariable< T >::Eval(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), Ship::HasTag(), ClientUI::HullIcon(), ClientUI::HullTexture(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionTime(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), DesignWnd::MainPanel::SetHull(), ShipDesign::ShipDesign(), Ship::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipHull().
FO_COMMON_API const HullTypeManager& GetHullTypeManager ()
returns the singleton hull type manager
References HullTypeManager::GetHullTypeManager().
Referenced by Universe::GetEffectsAndTargets(), ShipDesign::GetHull(), GetHullType(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), BasesListBox::PopulateWithEmptyHulls(), ShipDesign::ValidDesign(), and ClientUI::ZoomToContent().
FO_COMMON_API const PartType* GetPartType (const std::string & name)
Returns the ship PartType specification object with name name. If no such PartType exists, 0 is returned instead.
References PartTypeManager::GetPartType(), and GetPartTypeManager().
Referenced by Empire::AddPartType(), ShipDesign::AdjustedAttack(), anonymous_namespace{UniverseWrapper.cpp}::AttackStatsP(), ShipDesign::BuildStatCaches(), ShipDesign::CanColonize(), Ship::ColonyCapacity(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), DesignWnd::MainPanel::DesignChanged(), ValueRef::ComplexVariable< T >::Eval(), Ship::FighterCount(), Ship::FighterMax(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), Ship::HasTag(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartClassSimpleMatch::operator()(), ClientUI::PartIcon(), ShipDesign::ProductionCost(), ShipDesign::ProductionCostTimeLocationInvariant(), ShipDesign::ProductionLocation(), ShipDesign::ProductionTime(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), DesignWnd::MainPanel::SetDesign(), SlotControl::SetPart(), DesignWnd::MainPanel::SetPart(), Ship::Ship(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), Ship::TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), ShipDesign::ValidDesign(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), ShipDesign::Weapons(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToShipPart().
FO_COMMON_API const PartTypeManager& GetPartTypeManager ()
returns the singleton part type manager
References PartTypeManager::GetPartTypeManager().
Referenced by ShipDesign::Defense(), Universe::GetEffectsAndTargets(), GetPartType(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), PartsListBox::GroupAvailableDisplayableParts(), DesignWnd::PartPalette::PartPalette(), and ClientUI::ZoomToContent().
FO_COMMON_API const ShipDesign* GetPredefinedShipDesign (const std::string & name)
Returns the predefined ShipDesign with the name name. If no such ship design exists, 0 is returned instead.
References Universe::GetGenericShipDesign(), and GetUniverse().
Referenced by Effect::CreateShip::Execute(), Effect::GenerateSitRepMessage::Execute(), ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntKeyFromContentStringKey(), anonymous_namespace{SitRepPanel.cpp}::HandleLinkClick(), CombatReportWnd::Impl::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkClick(), EncyclopediaDetailPanel::HandleLinkDoubleClick(), and anonymous_namespace{VarText.cpp}::PredefinedShipDesignString().
const FO_COMMON_API PredefinedShipDesignManager& GetPredefinedShipDesignManager ()
returns the singleton predefined ship design manager type manager
References PredefinedShipDesignManager::GetPredefinedShipDesignManager().
Referenced by MessageWndEdit::FindGameWords(), ServerApp::GenerateUniverse(), Empire::LockItem(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetMonsterList(), anonymous_namespace{ServerWrapper.cpp}::ShipDesignGetPremadeList(), and Empire::UnlockItem().
FO_COMMON_API const ShipDesign* GetShipDesign (int ship_design_id)
Returns the ShipDesign specification object with id ship_design_id. If no such ShipDesign is present in the Universe (because it doesn't exist, or isn't know to this client), 0 is returned instead.
References Universe::GetShipDesign(), GetUniverse(), and PartTypeManager::s_instance.
Referenced by Ship::AllWeaponsDamage(), Ship::AllWeaponsMaxDamage(), BasesListBox::BaseLeftClicked(), BasesListBox::BaseRightClicked(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), BuildDesignatorWnd::BuildSelector::BuildItemRightClicked(), Empire::CheckProductionProgress(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), DesignWnd::MainPanel::CurrentDesignIsRegistered(), Ship::Design(), DesignWnd::MainPanel::DesignChanged(), ValueRef::NameLookup::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateShip::Execute(), ShipDesignOrder::ExecuteImpl(), Ship::HasTag(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::LoadAllSavedDesigns(), anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription(), Condition::anonymous_namespace{Condition.cpp}::NumberOnQueue(), ObjectListWnd::ObjectRightClicked(), Universe::Objects(), BuildDesignatorWnd::BuildSelector::PopulateList(), BasesListBox::PopulateWithCompletedDesigns(), Empire::ProducibleItem(), Empire::ProductionCostAndTime(), ProductionQueue::ProductionItem::ProductionItem(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::QueueProductionItemPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), DesignWnd::MainPanel::ReregisterDesigns(), BuildDesignatorWnd::SetBuild(), DesignWnd::MainPanel::SetDesign(), Ship::Ship(), Empire::ShipDesignAvailable(), ClientUI::ShipDesignIcon(), ShipDesignPanel::ShipDesignPanel(), anonymous_namespace{VarText.cpp}::ShipDesignString(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), anonymous_namespace{DesignWnd.cpp}::ShowSaveDesignDialog(), Ship::SumCurrentPartMeterValuesForPartClass(), Ship::Tags(), ShipDesignPanel::Update(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), Empire::UpdateOwnedObjectCounters(), FreeOrionPython::WrapUniverseClasses(), anonymous_namespace{DesignWnd.cpp}::WriteDesignToFile(), and ClientUI::ZoomToShipDesign().
FO_COMMON_API bool operator== (const ShipDesign & first, const ShipDesign & second)
References ShipDesign::Hull(), ShipDesign::Parts(), and PredefinedShipDesignManager::s_instance.
Referenced by ShipDesign::PartClassCount().