FreeOrion: SitRepEntry.h File Reference
SitRepEntry.h File Reference
Declares the SitRepEntry calls and related factory functions.
#include "VarText.h"
#include <string>
#include <vector>
#include "Export.h"
Classes
class SitRepEntry
Represents a situation report entry for a significant game event.
Functions
SitRepEntry factories
Factory functions to create SitRepEntry(s) for specific situation report events.
SitRepEntry CreateTechResearchedSitRep (const std::string &tech_name)
SitRepEntry CreateShipBuiltSitRep (int ship_id, int system_id, int shipdesign_id)
SitRepEntry CreateShipBlockBuiltSitRep (int system_id, int shipdesign_id, int number)
SitRepEntry CreateBuildingBuiltSitRep (int building_id, int planet_id)
SitRepEntry CreateTechUnlockedSitRep (const std::string &tech_name)
SitRepEntry CreateBuildingTypeUnlockedSitRep (const std::string &building_type_name)
SitRepEntry CreateShipHullUnlockedSitRep (const std::string &ship_hull_name)
SitRepEntry CreateShipPartUnlockedSitRep (const std::string &ship_part_name)
FO_COMMON_API SitRepEntry CreateCombatSitRep (int system_id, int log_id, int empire_id)
FO_COMMON_API SitRepEntry CreateGroundCombatSitRep (int planet_id, int empire_id)
FO_COMMON_API SitRepEntry CreatePlanetCapturedSitRep (int planet_id, int empire_id)
FO_COMMON_API SitRepEntry CreateCombatDamagedObjectSitRep (int object_id, int combat_system_id, int empire_id)
FO_COMMON_API SitRepEntry CreateCombatDestroyedObjectSitRep (int object_id, int combat_system_id, int empire_id)
SitRepEntry CreatePlanetDepopulatedSitRep (int planet_id)
FO_COMMON_API SitRepEntry CreatePlanetColonizedSitRep (int planet_id, const std::string &species)
FO_COMMON_API SitRepEntry CreatePlanetOutpostedSitRep (int planet_id)
FO_COMMON_API SitRepEntry CreateFleetArrivedAtDestinationSitRep (int system_id, int fleet_id, int recipient_empire_id)
SitRepEntry CreateEmpireEliminatedSitRep (int empire_id)
SitRepEntry CreateVictorySitRep (const std::string &reason_string, int empire_id)
FO_COMMON_API SitRepEntry CreateSitRep (const std::string &template_string, int turn, const std::string &icon, const std::vector< std::pair< std::string, std::string >> &parameters, const std::string label="", bool stringtable_lookup=true)
Detailed Description
Declares the SitRepEntry calls and related factory functions.
Function Documentation
CreateBuildingBuiltSitRep()
SitRepEntry CreateBuildingBuiltSitRep (int building_id, int planet_id)
References VarText::AddVariable(), VarText::BUILDING_ID_TAG, CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by Empire::CheckProductionProgress().
CreateBuildingTypeUnlockedSitRep()
SitRepEntry CreateBuildingTypeUnlockedSitRep (const std::string & building_type_name)
References VarText::AddVariable(), VarText::BUILDING_TYPE_TAG, CurrentTurn(), and UserStringNop.
Referenced by Empire::AddBuildingType().
CreateCombatDamagedObjectSitRep()
FO_COMMON_API SitRepEntry CreateCombatDamagedObjectSitRep (int object_id, int combat_system_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), ObjectMap::get(), Objects(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, SitRepEntry::SitRepEntry(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateCombatDestroyedObjectSitRep()
FO_COMMON_API SitRepEntry CreateCombatDestroyedObjectSitRep (int object_id, int combat_system_id, int empire_id)
References VarText::AddVariable(), VarText::BUILDING_ID_TAG, CurrentTurn(), DebugLogger, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, EmpireKnownObjects(), VarText::FLEET_ID_TAG, anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), ObjectMap::get(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, SitRepEntry::SitRepEntry(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateCombatSitRep()
FO_COMMON_API SitRepEntry CreateCombatSitRep (int system_id, int log_id, int empire_id)
References VarText::AddVariable(), ALL_EMPIRES, VarText::COMBAT_ID_TAG, CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateEmpireEliminatedSitRep()
SitRepEntry CreateEmpireEliminatedSitRep (int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, to_string(), and UserStringNop.
Referenced by Empire::Eliminate().
CreateFleetArrivedAtDestinationSitRep()
FO_COMMON_API SitRepEntry CreateFleetArrivedAtDestinationSitRep (int system_id, int fleet_id, int recipient_empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, VarText::FLEET_ID_TAG, ObjectMap::get(), Objects(), VarText::RAW_TEXT_TAG, VarText::SHIP_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by ServerApp::PreCombatProcessTurns().
CreateGroundCombatSitRep()
FO_COMMON_API SitRepEntry CreateGroundCombatSitRep (int planet_id, int empire_id)
References VarText::AddVariable(), ALL_EMPIRES, CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleInvasion().
CreatePlanetCapturedSitRep()
FO_COMMON_API SitRepEntry CreatePlanetCapturedSitRep (int planet_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleInvasion().
CreatePlanetColonizedSitRep()
FO_COMMON_API SitRepEntry CreatePlanetColonizedSitRep (int planet_id, const std::string & species)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, VarText::SPECIES_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleColonization().
CreatePlanetDepopulatedSitRep()
SitRepEntry CreatePlanetDepopulatedSitRep (int planet_id)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by Planet::PopGrowthProductionResearchPhase().
CreatePlanetOutpostedSitRep()
FO_COMMON_API SitRepEntry CreatePlanetOutpostedSitRep (int planet_id)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleColonization().
CreateShipBlockBuiltSitRep()
SitRepEntry CreateShipBlockBuiltSitRep (int system_id, int shipdesign_id, int number)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::RAW_TEXT_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by Empire::CheckProductionProgress().
CreateShipBuiltSitRep()
SitRepEntry CreateShipBuiltSitRep (int ship_id, int system_id, int shipdesign_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::SHIP_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by Empire::CheckProductionProgress().
CreateShipHullUnlockedSitRep()
SitRepEntry CreateShipHullUnlockedSitRep (const std::string & ship_hull_name)
References VarText::AddVariable(), CurrentTurn(), VarText::SHIP_HULL_TAG, and UserStringNop.
Referenced by Empire::AddHullType().
CreateShipPartUnlockedSitRep()
SitRepEntry CreateShipPartUnlockedSitRep (const std::string & ship_part_name)
References VarText::AddVariable(), CurrentTurn(), VarText::SHIP_PART_TAG, and UserStringNop.
Referenced by Empire::AddPartType().
CreateSitRep()
FO_COMMON_API SitRepEntry CreateSitRep (const std::string & template_string, int turn, const std::string & icon, const std::vector< std::pair< std::string, std::string >> & parameters, const std::string label = "", bool stringtable_lookup = true)
References VarText::AddVariable().
Referenced by Effect::GenerateSitRepMessage::Execute(), and anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep().
CreateTechResearchedSitRep()
SitRepEntry CreateTechResearchedSitRep (const std::string & tech_name)
References VarText::AddVariable(), CurrentTurn(), VarText::TECH_TAG, and UserStringNop.
Referenced by Empire::ApplyNewTechs().
CreateTechUnlockedSitRep()
SitRepEntry CreateTechUnlockedSitRep (const std::string & tech_name)
References VarText::AddVariable(), CurrentTurn(), VarText::TECH_TAG, and UserStringNop.
CreateVictorySitRep()
SitRepEntry CreateVictorySitRep (const std::string & reason_string, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, to_string(), and UserStringNop.
Referenced by Empire::Win().