FreeOrion: SitRepEntry.cpp File Reference
SitRepEntry.cpp File Reference
#include "SitRepEntry.h"
#include "i18n.h"
#include "Logger.h"
#include "AppInterface.h"
#include "../universe/Building.h"
#include "../universe/Planet.h"
#include "../universe/System.h"
#include "../universe/Ship.h"
#include "../universe/Fleet.h"
#include "../universe/Universe.h"
Namespaces
anonymous_namespace{SitRepEntry.cpp}
Functions
SitRepEntry CreateBuildingBuiltSitRep (int building_id, int planet_id)
SitRepEntry CreateBuildingTypeUnlockedSitRep (const std::string &building_type_name)
SitRepEntry CreateCombatDamagedObjectSitRep (int object_id, int combat_system_id, int empire_id)
SitRepEntry CreateCombatDestroyedObjectSitRep (int object_id, int combat_system_id, int empire_id)
SitRepEntry CreateCombatSitRep (int system_id, int log_id, int enemy_id)
SitRepEntry CreateEmpireEliminatedSitRep (int empire_id)
SitRepEntry CreateFleetArrivedAtDestinationSitRep (int system_id, int fleet_id, int recipient_empire_id)
SitRepEntry CreateFleetGiftedSitRep (int fleet_id, int empire_id)
SitRepEntry CreateGroundCombatSitRep (int planet_id, int enemy_id)
SitRepEntry CreatePlanetCapturedSitRep (int planet_id, int empire_id)
SitRepEntry CreatePlanetColonizedSitRep (int planet_id, const std::string &species)
SitRepEntry CreatePlanetDepopulatedSitRep (int planet_id)
SitRepEntry CreatePlanetGiftedSitRep (int planet_id, int empire_id)
SitRepEntry CreatePlanetOutpostedSitRep (int planet_id)
SitRepEntry CreatePolicyUnlockedSitRep (const std::string &policy_name)
SitRepEntry CreateShipBlockBuiltSitRep (int system_id, int shipdesign_id, int number)
SitRepEntry CreateShipBuiltSitRep (int ship_id, int system_id, int shipdesign_id)
SitRepEntry CreateShipHullUnlockedSitRep (const std::string &ship_hull_name)
SitRepEntry CreateShipPartUnlockedSitRep (const std::string &ship_part_name)
SitRepEntry CreateSitRep (const std::string &template_string, int turn, const std::string &icon, std::vector< std::pair< std::string, std::string >> parameters, const std::string label, bool stringtable_lookup)
SitRepEntry CreateTechResearchedSitRep (const std::string &tech_name)
SitRepEntry CreateTechUnlockedSitRep (const std::string &tech_name)
SitRepEntry CreateVictorySitRep (const std::string &reason_string, int empire_id)
SitRepEntry anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep (int combat_system_id)
SitRepEntry anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep (int combat_system_id)
Function Documentation
CreateBuildingBuiltSitRep()
SitRepEntry CreateBuildingBuiltSitRep (int building_id, int planet_id)
References VarText::AddVariable(), VarText::BUILDING_ID_TAG, CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Empire.cpp}::SanitizeResearchQueue().
CreateBuildingTypeUnlockedSitRep()
SitRepEntry CreateBuildingTypeUnlockedSitRep (const std::string & building_type_name)
References VarText::AddVariable(), VarText::BUILDING_TYPE_TAG, CurrentTurn(), and UserStringNop.
CreateCombatDamagedObjectSitRep()
SitRepEntry CreateCombatDamagedObjectSitRep (int object_id, int combat_system_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), ObjectMap::get(), Objects(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, SitRepEntry::SitRepEntry(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateCombatDestroyedObjectSitRep()
SitRepEntry CreateCombatDestroyedObjectSitRep (int object_id, int combat_system_id, int empire_id)
References VarText::AddVariable(), VarText::BUILDING_ID_TAG, CurrentTurn(), DebugLogger, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, EmpireKnownObjects(), VarText::FLEET_ID_TAG, anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), ObjectMap::get(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, SitRepEntry::SitRepEntry(), VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateCombatSitRep()
SitRepEntry CreateCombatSitRep (int system_id, int log_id, int enemy_id)
References VarText::AddVariable(), ALL_EMPIRES, VarText::COMBAT_ID_TAG, CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps().
CreateEmpireEliminatedSitRep()
SitRepEntry CreateEmpireEliminatedSitRep (int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters().
CreateFleetArrivedAtDestinationSitRep()
SitRepEntry CreateFleetArrivedAtDestinationSitRep (int system_id, int fleet_id, int recipient_empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, VarText::FLEET_ID_TAG, ObjectMap::get(), Objects(), VarText::RAW_TEXT_TAG, VarText::SHIP_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by ServerApp::PreCombatProcessTurns().
CreateFleetGiftedSitRep()
SitRepEntry CreateFleetGiftedSitRep (int fleet_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::FLEET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleGifting().
CreateGroundCombatSitRep()
SitRepEntry CreateGroundCombatSitRep (int planet_id, int enemy_id)
References VarText::AddVariable(), ALL_EMPIRES, CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleInvasion().
CreatePlanetCapturedSitRep()
SitRepEntry CreatePlanetCapturedSitRep (int planet_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleInvasion().
CreatePlanetColonizedSitRep()
SitRepEntry CreatePlanetColonizedSitRep (int planet_id, const std::string & species)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, VarText::SPECIES_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleColonization().
CreatePlanetDepopulatedSitRep()
SitRepEntry CreatePlanetDepopulatedSitRep (int planet_id)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Planet.cpp}::PlanetSizeIncrement().
CreatePlanetGiftedSitRep()
SitRepEntry CreatePlanetGiftedSitRep (int planet_id, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleGifting().
CreatePlanetOutpostedSitRep()
SitRepEntry CreatePlanetOutpostedSitRep (int planet_id)
References VarText::AddVariable(), CurrentTurn(), VarText::PLANET_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{ServerApp.cpp}::HandleColonization().
CreatePolicyUnlockedSitRep()
SitRepEntry CreatePolicyUnlockedSitRep (const std::string & policy_name)
References VarText::AddVariable(), CurrentTurn(), VarText::POLICY_TAG, and UserStringNop.
CreateShipBlockBuiltSitRep()
SitRepEntry CreateShipBlockBuiltSitRep (int system_id, int shipdesign_id, int number)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::RAW_TEXT_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Empire.cpp}::SanitizeResearchQueue().
CreateShipBuiltSitRep()
SitRepEntry CreateShipBuiltSitRep (int ship_id, int system_id, int shipdesign_id)
References VarText::AddVariable(), CurrentTurn(), VarText::DESIGN_ID_TAG, VarText::SHIP_ID_TAG, VarText::SYSTEM_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Empire.cpp}::SanitizeResearchQueue().
CreateShipHullUnlockedSitRep()
SitRepEntry CreateShipHullUnlockedSitRep (const std::string & ship_hull_name)
References VarText::AddVariable(), CurrentTurn(), VarText::SHIP_HULL_TAG, and UserStringNop.
CreateShipPartUnlockedSitRep()
SitRepEntry CreateShipPartUnlockedSitRep (const std::string & ship_part_name)
References VarText::AddVariable(), CurrentTurn(), VarText::SHIP_PART_TAG, and UserStringNop.
CreateSitRep()
SitRepEntry CreateSitRep (const std::string & template_string, int turn, const std::string & icon, std::vector< std::pair< std::string, std::string >> parameters, const std::string label, bool stringtable_lookup)
References VarText::AddVariables().
Referenced by Effect::GenerateSitRepMessage::Execute(), and anonymous_namespace{ServerWrapper.cpp}::GenerateSitRep().
CreateTechResearchedSitRep()
SitRepEntry CreateTechResearchedSitRep (const std::string & tech_name)
References VarText::AddVariable(), CurrentTurn(), VarText::TECH_TAG, and UserStringNop.
CreateTechUnlockedSitRep()
SitRepEntry CreateTechUnlockedSitRep (const std::string & tech_name)
References VarText::AddVariable(), CurrentTurn(), VarText::TECH_TAG, and UserStringNop.
CreateVictorySitRep()
SitRepEntry CreateVictorySitRep (const std::string & reason_string, int empire_id)
References VarText::AddVariable(), CurrentTurn(), VarText::EMPIRE_ID_TAG, to_string(), and UserStringNop.
Referenced by anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters().