FreeOrion: Special.cpp File Reference
Special.cpp File Reference
#include "Special.h"
#include <boost/filesystem/fstream.hpp>
#include "Condition.h"
#include "Effect.h"
#include "UniverseObject.h"
#include "ValueRef.h"
#include "../util/AppInterface.h"
#include "../util/CheckSums.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/ScopedTimer.h"
#include "../util/i18n.h"
Functions
const Special * GetSpecial (const std::string &name)
Returns the Special object used to represent specials of type name.
SpecialsManager & GetSpecialsManager ()
std::vector< std::string > SpecialNames ()
Returns names of all specials.
Function Documentation
GetSpecial()
const Special* GetSpecial (const std::string & name)
Returns the Special object used to represent specials of type name.
If no such Special exists, 0 is returned instead.
References SpecialsManager::GetSpecial(), and GetSpecialsManager().
Referenced by anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), SpecialsManager::NumSpecials(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), anonymous_namespace{ServerWrapper.cpp}::SpecialHasLocation(), ClientUI::SpecialIcon(), anonymous_namespace{ServerWrapper.cpp}::SpecialLocations(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnLimit(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnRate(), SpecialsPanel::Update(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToSpecial().
GetSpecialsManager()
SpecialsManager& GetSpecialsManager ()
Referenced by CheckSumContent(), GetSpecial(), SpecialNames(), and IApp::StartBackgroundParsing().
SpecialNames()
std::vector<std::string> SpecialNames ()
Returns names of all specials.
References GetSpecialsManager(), and SpecialsManager::SpecialNames().
Referenced by MessageWndEdit::FindGameWords(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecials(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), SpecialsManager::NumSpecials(), ConditionWidget::UpdateParameterControls(), and ClientUI::ZoomToContent().