FreeOrion: Species.cpp File Reference
Species.cpp File Reference
#include "Species.h"
#include <iterator>
#include <boost/filesystem/fstream.hpp>
#include "Conditions.h"
#include "Effect.h"
#include "PopCenter.h"
#include "Planet.h"
#include "Ship.h"
#include "UniverseObject.h"
#include "ValueRefs.h"
#include "../util/AppInterface.h"
#include "../util/CheckSums.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/Random.h"
#include "../util/ScopedTimer.h"
Namespaces
anonymous_namespace{Species.cpp}
Functions
const Species * GetSpecies (const std::string &name)
Returns the Species object used to represent species of type name.
SpeciesManager & GetSpeciesManager ()
returns the singleton species manager
std::string anonymous_namespace{Species.cpp}::PlanetEnvironmentToString (PlanetEnvironment env)
std::string anonymous_namespace{Species.cpp}::PlanetTypeToString (PlanetType type)
PlanetType anonymous_namespace{Species.cpp}::RingNextPlanetType (PlanetType current_type)
PlanetType anonymous_namespace{Species.cpp}::RingPreviousPlanetType (PlanetType current_type)
Variables
const std::string anonymous_namespace{Species.cpp}::EMPTY_STRING
Function Documentation
GetSpecies()
const Species* GetSpecies (const std::string & name)
Returns the Species object used to represent species of type name.
If no such Species exists, 0 is returned instead.
References SpeciesManager::GetSpecies(), and SpeciesManager::GetSpeciesManager().
Referenced by AutomaticallyChosenColonyShip(), Planet::AvailableFoci(), Ship::CanColonize(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), Planet::Colonize(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Planet::EnvironmentForSpecies(), ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetSpecies::Execute(), Effect::CreateShip::Execute(), Planet::FocusIcon(), Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Conditions.cpp}::GetLocationCondition(), Ship::HasTag(), Planet::HasTag(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), HumanClientApp::NewSinglePlayerGame(), Planet::NextBetterPlanetTypeForSpecies(), Condition::anonymous_namespace{Conditions.cpp}::HomeworldSimpleMatch::operator()(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), ShipDesign::ProductionLocation(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), MapWnd::RefreshPopulationIndicator(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), PopCenter::SetSpecies(), Ship::SetSpecies(), Ship::Ship(), anonymous_namespace{ServerWrapper.cpp}::SpeciesDefaultFocus(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesEnvByTargetPop(), anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment(), ClientUI::SpeciesIcon(), anonymous_namespace{CombatSystem.cpp}::SpeciesTargettingCondition(), Planet::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToSpecies().
GetSpeciesManager()
SpeciesManager& GetSpeciesManager ()
returns the singleton species manager
References SpeciesManager::GetSpeciesManager().
Referenced by ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), anonymous_namespace{ObjectListWnd.cpp}::AvailableColumnTypes(), CheckSumContent(), MPLobby::EstablishPlayer(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetSpeciesEmpireOpinion::Execute(), Effect::SetSpeciesSpeciesOpinion::Execute(), MessageWndEdit::FindGameWords(), ServerApp::GenerateUniverse(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecies(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies(), anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), AIClientApp::HandleMessage(), ServerFSM::HandleNonLobbyDisconnection(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadGameInit(), Condition::Homeworld::Match(), HumanClientApp::NewSinglePlayerGame(), Condition::anonymous_namespace{Conditions.cpp}::HomeworldSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ServerApp::PostCombatProcessTurns(), Idle::react(), MPLobby::react(), WaitingForSPGameJoiners::react(), PlayingGame::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), WaitingForTurnEnd::react(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), MapWnd::RefreshPopulationIndicator(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), ServerApp::SendNewGameStartMessages(), SetEmpireHomeworld(), SpeciesSelector::SpeciesSelector(), IApp::StartBackgroundParsing(), ConditionWidget::UpdateParameterControls(), and ClientUI::ZoomToContent().