FreeOrion: Special.h File Reference
Special.h File Reference
#include "ValueRefFwd.h"
#include <boost/serialization/nvp.hpp>
#include <boost/optional/optional.hpp>
#include "../util/Export.h"
#include "../util/Pending.h"
#include <memory>
#include <string>
#include <vector>
#include <map>
Classes
class Special
A predefined set of EffectsGroups that can be attached to a UniverseObject (often referred to as the "source" object).
class SpecialsManager
Look up table for specials.
Namespaces
Condition
this namespace holds ConditionBase and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Effect
Functions
FO_COMMON_API const Special * GetSpecial (const std::string &name)
Returns the Special object used to represent specials of type name.
FO_COMMON_API SpecialsManager & GetSpecialsManager ()
FO_COMMON_API std::vector< std::string > SpecialNames ()
Returns names of all specials.
Function Documentation
GetSpecial()
FO_COMMON_API const Special* GetSpecial (const std::string & name)
Returns the Special object used to represent specials of type name.
If no such Special exists, 0 is returned instead.
GetSpecialsManager()
FO_COMMON_API SpecialsManager& GetSpecialsManager ()
Referenced by GetSpecial(), SpecialNames(), and IApp::StartBackgroundParsing().
SpecialNames()
FO_COMMON_API std::vector<std::string> SpecialNames ()
Returns names of all specials.
References GetSpecialsManager(), and SpecialsManager::SpecialNames().