FreeOrion: Species.h File Reference
Species.h File Reference
#include "EnumsFwd.h"
#include "../util/Export.h"
#include "../util/Serialize.h"
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/serialization/nvp.hpp>
#include <boost/iterator/filter_iterator.hpp>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
Classes
class FocusType
class Species
class SpeciesManager
struct SpeciesManager::NativeSpecies
struct SpeciesManager::PlayableSpecies
struct SpeciesParams
struct SpeciesStrings
Namespaces
Condition
Effect
Functions
FO_COMMON_API const Species * GetSpecies (const std::string &name)
FO_COMMON_API SpeciesManager & GetSpeciesManager ()
Variables
FO_COMMON_API const int ALL_EMPIRES
Function Documentation
FO_COMMON_API const Species* GetSpecies (const std::string & name)
Returns the Species object used to represent species of type name. If no such Species exists, 0 is returned instead.
FO_COMMON_API SpeciesManager& GetSpeciesManager ()
returns the singleton species manager
References SpeciesManager::GetSpeciesManager().
Referenced by ContentCheckSumMessage(), MPLobby::EstablishPlayer(), ValueRef::Variable< T >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetSpeciesEmpireOpinion::Execute(), Effect::SetSpeciesSpeciesOpinion::Execute(), MessageWndEdit::FindGameWords(), anonymous_namespace{ServerWrapper.cpp}::GetAllSpecies(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerWrapper.cpp}::GetNativeSpecies(), anonymous_namespace{ServerWrapper.cpp}::GetPlayableSpecies(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), AIClientApp::HandleMessage(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), ServerApp::LoadGameInit(), Condition::Homeworld::Match(), HumanClientApp::NewSinglePlayerGame(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), ServerApp::PostCombatProcessTurns(), MPLobby::react(), WaitingForSPGameJoiners::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), WaitingForSaveData::react(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), Universe::ResetUniverse(), ServerApp::SendNewGameStartMessages(), SetEmpireHomeworld(), SpeciesSelector::SpeciesSelector(), ConditionWidget::UpdateParameterControls(), and ClientUI::ZoomToContent().
Variable Documentation
FO_COMMON_API const int ALL_EMPIRES