FreeOrion: WaitingForSPHostAck Struct Reference
WaitingForSPHostAck Struct Reference
The human client state in which the player has requested to host a single player game and is waiting for the server to acknowledge the request.
#include <HumanClientFSM.h>
Public Types
typedef boost::statechart::simple_state< WaitingForSPHostAck, HumanClientFSM > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< HostSPGame >, boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< Error >, boost::statechart::custom_reaction< CheckSum > > reactions
Public Member Functions
WaitingForSPHostAck ()
~WaitingForSPHostAck ()
boost::statechart::result react (const HostSPGame &a)
boost::statechart::result react (const Disconnection &d)
boost::statechart::result react (const StartQuittingGame &msg)
boost::statechart::result react (const Error &msg)
boost::statechart::result react (const CheckSum &msg)
Detailed Description
The human client state in which the player has requested to host a single player game and is waiting for the server to acknowledge the request.
Member Typedef Documentation
Base
typedef boost::statechart::simple_state<WaitingForSPHostAck, HumanClientFSM> WaitingForSPHostAck::Base
reactions
typedef boost::mpl::list< boost::statechart::custom_reaction<HostSPGame>, boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<Error>, boost::statechart::custom_reaction<CheckSum> > WaitingForSPHostAck::reactions
Constructor & Destructor Documentation
WaitingForSPHostAck()
WaitingForSPHostAck::WaitingForSPHostAck ()
References TraceLogger.
~WaitingForSPHostAck()
WaitingForSPHostAck::~WaitingForSPHostAck ()
References TraceLogger.
Member Function Documentation
react() [1/5]
boost::statechart::result WaitingForSPHostAck::react (const HostSPGame & a)
References ErrorLogger, and TraceLogger.
react() [2/5]
boost::statechart::result WaitingForSPHostAck::react (const Disconnection & d)
References ClientUI::MessageBox(), TraceLogger, and UserString().
react() [3/5]
boost::statechart::result WaitingForSPHostAck::react (const StartQuittingGame & msg)
References TraceLogger, and UserString().
react() [4/5]
boost::statechart::result WaitingForSPHostAck::react (const Error & msg)
References ErrorLogger, ExtractErrorMessageData(), HumanClientApp::GetClientUI(), ClientUI::GetMessageWnd(), ClientUI::MessageBox(), TraceLogger, and UserString().
react() [5/5]
boost::statechart::result WaitingForSPHostAck::react (const CheckSum & msg)
References ClientUI::MessageBox(), TraceLogger, and UserString().
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp