FreeOrion: Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch Struct Reference
Public Member Functions
FleetSupplyableSimpleMatch (int empire_id)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
int m_empire_id
Constructor & Destructor Documentation
FleetSupplyableSimpleMatch()
Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::FleetSupplyableSimpleMatch (int empire_id) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References SupplyManager::FleetSupplyableSystemIDs(), GetEmpire(), GetSupplyManager(), and Condition::FleetSupplyableByEmpire::m_empire_id.
Member Data Documentation
m_empire_id
int Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::m_empire_id
The documentation for this struct was generated from the following file:
Condition.cpp