FreeOrion: Condition::OrderedBombarded Struct Reference
Condition::OrderedBombarded Struct Reference final
Matches the objects that have been targeted for bombardment by at least one object that matches m_by_object_condition.
#include <Condition.h>
Public Member Functions
OrderedBombarded (std::unique_ptr< ConditionBase > &&by_object_condition)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
virtual void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ConditionBase > m_by_object_condition
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches the objects that have been targeted for bombardment by at least one object that matches m_by_object_condition.
Constructor & Destructor Documentation
OrderedBombarded()
Condition::OrderedBombarded::OrderedBombarded (std::unique_ptr< ConditionBase > && by_object_condition) explicit
Member Function Documentation
Description()
std::string Condition::OrderedBombarded::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), m_by_object_condition, and UserString().
Dump()
std::string Condition::OrderedBombarded::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_by_object_condition.
Eval()
void Condition::OrderedBombarded::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_by_object_condition, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::OrderedBombarded::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_by_object_condition, and TraceLogger.
Match()
bool Condition::OrderedBombarded::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, and m_by_object_condition.
operator==()
bool Condition::OrderedBombarded::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_by_object_condition.
RootCandidateInvariant()
bool Condition::OrderedBombarded::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_by_object_condition.
Referenced by Eval().
serialize()
template<class Archive > void Condition::OrderedBombarded::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::OrderedBombarded::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_by_object_condition.
SourceInvariant()
bool Condition::OrderedBombarded::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_by_object_condition.
TargetInvariant()
bool Condition::OrderedBombarded::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_by_object_condition.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_by_object_condition
std::unique_ptr<ConditionBase> Condition::OrderedBombarded::m_by_object_condition private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp