FreeOrion: anonymous_namespace{GameRulesParser.cpp}::insert_rule_ Struct Reference
anonymous_namespace{GameRulesParser.cpp}::insert_rule_ Struct Reference
Public Types
typedef void result_type
Public Member Functions
void operator() (GameRules &game_rules, const std::string &name, const std::string &desc, const std::string &category, bool default_value) const
void operator() (GameRules &game_rules, const std::string &name, const std::string &desc, const std::string &category, int default_value, int min, int max) const
void operator() (GameRules &game_rules, const std::string &name, const std::string &desc, const std::string &category, double default_value, double min, double max) const
void operator() (GameRules &game_rules, const std::string &name, const std::string &desc, const std::string &category, const std::string &default_value, const std::set< std::string > &allowed={}) const
Member Typedef Documentation
result_type
typedef void anonymous_namespace{GameRulesParser.cpp}::insert_rule_::result_type
Member Function Documentation
operator()() [1/4]
void anonymous_namespace{GameRulesParser.cpp}::insert_rule_::operator() (GameRules & game_rules, const std::string & name, const std::string & desc, const std::string & category, bool default_value) const inline
References GameRules::Add(), and DebugLogger.
operator()() [2/4]
void anonymous_namespace{GameRulesParser.cpp}::insert_rule_::operator() (GameRules & game_rules, const std::string & name, const std::string & desc, const std::string & category, int default_value, int min, int max) const inline
References GameRules::Add(), DebugLogger, max, and min.
operator()() [3/4]
void anonymous_namespace{GameRulesParser.cpp}::insert_rule_::operator() (GameRules & game_rules, const std::string & name, const std::string & desc, const std::string & category, double default_value, double min, double max) const inline
References GameRules::Add(), DebugLogger, max, and min.
operator()() [4/4]
void anonymous_namespace{GameRulesParser.cpp}::insert_rule_::operator() (GameRules & game_rules, const std::string & name, const std::string & desc, const std::string & category, const std::string & default_value, const std::set< std::string > & allowed = {}) const inline
References GameRules::Add(), and DebugLogger.
The documentation for this struct was generated from the following file:
GameRulesParser.cpp