FreeOrion: ValueRef::ImmediateValueVariable Struct Reference
ValueRef::ImmediateValueVariable Struct Reference
#include <ValueRef.h>
Public Member Functions
ImmediateValueVariable (ReferenceType ref_type, const std::string &property_name="")
ImmediateValueVariable (ReferenceType ref_type, const std::vector< std::string > &property_name)
double Eval (const ScriptingContext &context) const override
bool operator== (const ValueRefBase< double > &rhs) const override
Public Member Functions inherited from ValueRef::Variable< double >
Variable (ReferenceType ref_type, const std::string &property_name="")
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name)
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
double Eval (const ScriptingContext &context) const override
unsigned int GetCheckSum () const override
ReferenceType GetReferenceType () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRefBase< double > &rhs) const override
const std::vector< std::string > & PropertyName () const
bool RootCandidateInvariant () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRefBase< T >
virtual ~ValueRefBase ()
virtual bool ConstantExpr () const
T Eval () const
bool operator!= (const ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRefBase< T > &rhs) const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SimpleIncrement () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from ValueRef::Variable< double >
std::vector< std::string > m_property_name
ReferenceType m_ref_type
Detailed Description
The immediate variable value ValueRef class. This node is a special-case for meters, in which it is sometimes useful to reference the immediate value rather than the intial value at the start of a turn.
Constructor & Destructor Documentation
ValueRef::ImmediateValueVariable::ImmediateValueVariable (ReferenceType ref_type, const std::string & property_name = "") explicit
ValueRef::ImmediateValueVariable::ImmediateValueVariable (ReferenceType ref_type, const std::vector< std::string > & property_name)
Member Function Documentation
double ValueRef::ImmediateValueVariable::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRefBase< T >.
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{ValueRef.cpp}::FollowReference(), INVALID_METER_TYPE, ValueRef::INVALID_REFERENCE_TYPE, ValueRef::Variable< double >::m_property_name, ValueRef::Variable< double >::m_ref_type, ValueRef::NameToMeter(), ValueRef::NON_OBJECT_REFERENCE, ScriptingContext::source, and anonymous_namespace{ValueRef.cpp}::TraceReference().
bool ValueRef::ImmediateValueVariable::operator== (const ValueRefBase< double > & rhs) const override
References ValueRef::Variable< double >::m_property_name, ValueRef::Variable< T >::m_property_name, ValueRef::Variable< double >::m_ref_type, and ValueRef::Variable< T >::m_ref_type.
template<class Archive > void ValueRef::ImmediateValueVariable::serialize (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
ValueRef.h
ValueRef.cpp