FreeOrion: Condition::RootCandidate Struct Reference
Condition::RootCandidate Struct Reference final
Matches the root candidate object in a condition tree.
#include <Condition.h>
Public Member Functions
RootCandidate ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches the root candidate object in a condition tree.
This is useful within a subcondition to match the object actually being matched by the whole compound condition, rather than an object just being matched in a subcondition in order to evaluate the outer condition.
Constructor & Destructor Documentation
RootCandidate()
Condition::RootCandidate::RootCandidate () inline
References operator==().
Member Function Documentation
Description()
std::string Condition::RootCandidate::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString().
Dump()
std::string Condition::RootCandidate::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
GetCheckSum()
unsigned int Condition::RootCandidate::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::RootCandidate::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate.
Match()
bool Condition::RootCandidate::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, and ScriptingContext::condition_root_candidate.
operator==()
bool Condition::RootCandidate::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::operator==().
RootCandidateInvariant()
bool Condition::RootCandidate::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::RootCandidate::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::RootCandidate::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::RootCandidate::SourceInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Effect::Dump().
TargetInvariant()
bool Condition::RootCandidate::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp