FreeOrion: ServerFSM Struct Reference
ServerFSM Struct Reference
The finite state machine that represents the server's operation.
#include <ServerFSM.h>
Public Member Functions
ServerFSM (ServerApp &server)
bool EstablishPlayer (const PlayerConnectionPtr &player_connection, const std::string &player_name, Networking::ClientType client_type, const std::string &client_version_string, const Networking::AuthRoles &roles)
void HandleNonLobbyDisconnection (const Disconnection &d)
ServerApp & Server ()
void unconsumed_event (const sc::event_base &event)
void UpdateIngameLobby ()
Public Attributes
std::shared_ptr< MultiplayerLobbyData > m_lobby_data
std::vector< PlayerSaveGameData > m_player_save_game_data
std::shared_ptr< ServerSaveGameData > m_server_save_game_data
std::shared_ptr< SinglePlayerSetupData > m_single_player_setup_data
Private Attributes
ServerApp & m_server
Detailed Description
The finite state machine that represents the server's operation.
Constructor & Destructor Documentation
ServerFSM()
ServerFSM::ServerFSM (ServerApp & server)
Member Function Documentation
EstablishPlayer()
bool ServerFSM::EstablishPlayer (const PlayerConnectionPtr & player_connection, const std::string & player_name, Networking::ClientType client_type, const std::string & client_version_string, const Networking::AuthRoles & roles)
References ChatHistoryMessage(), Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ContentCheckSumMessage(), DebugLogger, ServerNetworking::Disconnect(), ServerApp::DropPlayerEmpireLink(), ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerNetworking::GenerateCookie(), ServerApp::GetChatHistory(), GetOptionsDB(), HostIDMessage(), ServerNetworking::HostPlayerID(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, JoinAckMessage(), ServerApp::m_networking, m_server, ServerApp::Networking(), ServerNetworking::NewPlayerID(), ServerApp::PushChatMessage(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, ServerPlayerChatMessage(), UserString(), and UserStringNop.
Referenced by PlayingGame::EstablishPlayer(), and WaitingForMPGameJoiners::react().
HandleNonLobbyDisconnection()
void ServerFSM::HandleNonLobbyDisconnection (const Disconnection & d)
References ServerNetworking::CleanupCookies(), Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerApp::CurrentTurn(), DebugLogger, ServerApp::DropPlayerEmpireLink(), Empires(), error, ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), OptionsDB::Get(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), GetCombatLogManager(), GetEmpire(), ServerApp::GetEmpireClientType(), GetOptionsDB(), ServerApp::GetPlayerSaveGameData(), GetSpeciesManager(), GetUniverse(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, ServerApp::IsHostless(), ServerApp::m_fsm, ServerApp::m_galaxy_setup_data, ServerApp::m_networking, Disconnection::m_player_connection, m_server, ServerApp::m_single_player_game, ServerApp::Networking(), ServerApp::PlayerEmpireID(), ServerNetworking::PlayerIsHost(), ServerApp::PushChatMessage(), SaveGame(), ServerApp::SelectNewHost(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerPlayerChatMessage(), ServerSaveGameCompleteMessage(), ServerNetworking::UpdateCookie(), UpdateIngameLobby(), UserStringNop, and WarnLogger.
Server()
ServerApp & ServerFSM::Server ()
References m_server.
unconsumed_event()
void ServerFSM::unconsumed_event (const sc::event_base & event)
References ErrorLogger, MESSAGE_EVENT_CASE, MESSAGE_EVENTS, and NON_MESSAGE_SERVER_FSM_EVENTS.
UpdateIngameLobby()
void ServerFSM::UpdateIngameLobby ()
References MultiplayerLobbyData::any_can_edit, PlayerSetupData::authenticated, PlayerSetupData::client_type, Networking::CLIENT_TYPE_HUMAN_PLAYER, CompileSaveGameEmpireData(), ServerApp::CurrentTurn(), PlayerSetupData::empire_color, PlayerSetupData::empire_name, ServerNetworking::established_begin(), ServerNetworking::established_end(), GetEmpire(), ServerApp::GetGalaxySetupData(), ServerApp::GetPlayerInfoMap(), MultiplayerLobbyData::in_game, ServerApp::m_networking, m_server, MultiplayerLobbyData::new_game, PlayerSetupData::player_id, PlayerSetupData::player_name, ServerApp::PlayerEmpireID(), PlayerInfoMessage(), MultiplayerLobbyData::players, MultiplayerLobbyData::save_game_current_turn, MultiplayerLobbyData::save_game_empire_data, PlayerSetupData::save_game_empire_id, ServerLobbyUpdateMessage(), MultiplayerLobbyData::start_lock_cause, MultiplayerLobbyData::start_locked, and UserStringNop.
Referenced by PlayingGame::EstablishPlayer(), and HandleNonLobbyDisconnection().
Member Data Documentation
m_lobby_data
std::shared_ptr<MultiplayerLobbyData> ServerFSM::m_lobby_data
m_player_save_game_data
std::vector<PlayerSaveGameData> ServerFSM::m_player_save_game_data
m_server
ServerApp& ServerFSM::m_server private
Referenced by EstablishPlayer(), HandleNonLobbyDisconnection(), Server(), and UpdateIngameLobby().
m_server_save_game_data
std::shared_ptr<ServerSaveGameData> ServerFSM::m_server_save_game_data
m_single_player_setup_data
std::shared_ptr<SinglePlayerSetupData> ServerFSM::m_single_player_setup_data
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp