FreeOrion: ShuttingDownServer Struct Reference
ShuttingDownServer Struct Reference
#include <ServerFSM.h>
Public Types
using Clock = std::chrono::high_resolution_clock
typedef boost::mpl::list< sc::in_state_reaction< Disconnection >, sc::custom_reaction< LeaveGame >, sc::custom_reaction< CheckEndConditions >, sc::custom_reaction< DisconnectClients >, sc::custom_reaction< Error > > reactions
Public Member Functions
ShuttingDownServer (my_context c)
~ShuttingDownServer ()
sc::result react (const LeaveGame &msg)
sc::result react (const CheckEndConditions &u)
sc::result react (const DisconnectClients &u)
sc::result react (const Disconnection &d)
sc::result react (const Error &msg)
Public Attributes
std::unordered_set< int > m_player_id_ack_expected
boost::asio::high_resolution_timer m_timeout
Detailed Description
The server state in which the server is shutting down and waiting for AIs to exit.
Member Typedef Documentation
using ShuttingDownServer::Clock = std::chrono::high_resolution_clock
typedef boost::mpl::list< sc::in_state_reaction<Disconnection>, sc::custom_reaction<LeaveGame>, sc::custom_reaction<CheckEndConditions>, sc::custom_reaction<DisconnectClients>, sc::custom_reaction<Error> > ShuttingDownServer::reactions
Constructor & Destructor Documentation
ShuttingDownServer::ShuttingDownServer (my_context c)
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::empty(), EndGameMessage(), ServerApp::m_ai_client_processes, ServerApp::m_networking, m_player_id_ack_expected, m_timeout, Message::PLAYER_DISCONNECT, ServerApp::ShutdownTimedoutHandler(), and TraceLogger.
ShuttingDownServer::~ShuttingDownServer ()
References TraceLogger.
Member Function Documentation
sc::result ShuttingDownServer::react (const LeaveGame & msg)
References DebugLogger, m_player_id_ack_expected, TraceLogger, and WarnLogger.
sc::result ShuttingDownServer::react (const CheckEndConditions & u)
References DebugLogger, Process::Free(), ServerApp::m_ai_client_processes, m_player_id_ack_expected, and TraceLogger.
sc::result ShuttingDownServer::react (const DisconnectClients & u)
References ServerNetworking::DisconnectAll(), ServerApp::m_ai_client_processes, ServerApp::m_networking, and TraceLogger.
sc::result ShuttingDownServer::react (const Disconnection & d)
References DebugLogger, Disconnection::m_player_connection, m_player_id_ack_expected, and TraceLogger.
sc::result ShuttingDownServer::react (const Error & msg)
References anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage().
Member Data Documentation
std::unordered_set<int> ShuttingDownServer::m_player_id_ack_expected
Referenced by react(), and ShuttingDownServer().
boost::asio::high_resolution_timer ShuttingDownServer::m_timeout
Referenced by ShuttingDownServer().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp