FreeOrion: parse::report_error_ Struct Reference
parse::report_error_ Struct Reference
#include <ReportParseError.h>
Public Types
typedef void result_type
Public Member Functions
template<typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 >
void operator() (const std::string &filename, const text_iterator &begin, const text_iterator &end, Arg1 first, Arg2, Arg3 it, Arg4 rule_name) const
Static Public Attributes
static boost::function< void(const std::string &)> send_error_string
Private Member Functions
void generate_error_string (const std::string &filename, const text_iterator &begin, const text_iterator &end, const token_iterator &first, const token_iterator &it, const boost::spirit::info &rule_name, std::string &str) const
std::string get_line (const text_iterator &end, text_iterator line_start) const
std::string get_lines_after (const text_iterator &begin, const text_iterator &end, text_iterator line_start) const
std::string get_lines_before (const text_iterator &begin, const text_iterator &end, text_iterator line_start) const
std::pair< text_iterator, unsigned int > line_start_and_line_number (const text_iterator &begin, const text_iterator &end, text_iterator error_position) const
Member Typedef Documentation
result_type
typedef void parse::report_error_::result_type
Member Function Documentation
generate_error_string()
void parse::report_error_::generate_error_string (const std::string & filename, const text_iterator & begin, const text_iterator & end, const token_iterator & first, const token_iterator & it, const boost::spirit::info & rule_name, std::string & str) const private
References parse::detail::pretty_print().
get_line()
std::string parse::report_error_::get_line (const text_iterator & end, text_iterator line_start) const private
get_lines_after()
std::string parse::report_error_::get_lines_after (const text_iterator & begin, const text_iterator & end, text_iterator line_start) const private
References anonymous_namespace{ReportParseError.cpp}::LineStarts().
get_lines_before()
std::string parse::report_error_::get_lines_before (const text_iterator & begin, const text_iterator & end, text_iterator line_start) const private
References anonymous_namespace{ReportParseError.cpp}::LineStarts().
line_start_and_line_number()
std::pair< parse::text_iterator, unsigned int > parse::report_error_::line_start_and_line_number (const text_iterator & begin, const text_iterator & end, text_iterator error_position) const private
References anonymous_namespace{ReportParseError.cpp}::LineStarts().
operator()()
template<typename Arg1 , typename Arg2 , typename Arg3 , typename Arg4 > void parse::report_error_::operator() (const std::string & filename, const text_iterator & begin, const text_iterator & end, Arg1 first, Arg2 , Arg3 it, Arg4 rule_name) const inline
Member Data Documentation
send_error_string
boost::function< void(const std::string &)> parse::report_error_::send_error_string static
Initial value:
=
    &detail::default_send_error_string
Referenced by parse::detail::default_send_error_string().
The documentation for this struct was generated from the following files:
ReportParseError.h
ReportParseError.cpp