FreeOrion: anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2 Struct Reference
anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2 Struct Reference
Public Types
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< std::string > * > > common_rule
Public Member Functions
condition_parser_rules_2 ()
Public Attributes
common_rule design_has_part
common_rule design_has_part_class
common_rule enqueued
common_rule enqueued1
common_rule enqueued2
common_rule enqueued3
common_rule enqueued4
common_rule has_special_since_turn
common_rule in_system
parse::condition_parser_rule start
Member Typedef Documentation
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<std::string>* > > anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::common_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2 () inline
References anonymous_namespace{EnumParser.cpp}::_val, BT_BUILDING, BT_SHIP, parse::flexible_int_value_ref(), parse::lexer::instance(), parse::int_value_ref(), INVALID_BUILD_TYPE, parse::detail::label(), parse::ship_part_class_enum(), and parse::string_value_ref().
Member Data Documentation
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::design_has_part
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::design_has_part_class
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::enqueued
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::enqueued1
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::enqueued2
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::enqueued3
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::enqueued4
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::has_special_since_turn
common_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::in_system
parse::condition_parser_rule anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::start
The documentation for this struct was generated from the following file:
ConditionParser2.cpp