FreeOrion: ValueRef::Operation< T > Struct Template Reference
ValueRef::Operation< T > Struct Template Reference final
An arithmetic operation node ValueRef class.
#include <ValueRefs.h>
Public Member Functions
Operation (OpType op_type, std::unique_ptr< ValueRef< T >> &&operand1, std::unique_ptr< ValueRef< T >> &&operand2)
Binary operation ctor.
Operation (OpType op_type, std::unique_ptr< ValueRef< T >> &&operand)
Unary operation ctor.
Operation (OpType op_type, std::vector< std::unique_ptr< ValueRef< T >>> &&operands)
bool ConstantExpr () const override
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a text description of this type of special.
T Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
OpType GetOpType () const
const ValueRef< T > * LHS () const
1st operand (or 0 if none exists).
bool LocalCandidateInvariant () const override
const std::vector< ValueRef< T > * > Operands () const
all operands
bool operator== (const ValueRef< T > &rhs) const override
const ValueRef< T > * RHS () const
2nd operand (or 0 if only one exists)
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SimpleIncrement () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRef< T >
virtual ~ValueRef ()
T Eval () const
Evaluates the expression tree with an empty context.
bool operator!= (const ValueRef< T > &rhs) const
Private Member Functions
void CacheConstValue ()
void DetermineIfConstantExpr ()
T EvalImpl (const ScriptingContext &context) const
template<>
FO_COMMON_API std::string EvalImpl (const ScriptingContext &context) const
template<>
FO_COMMON_API double EvalImpl (const ScriptingContext &context) const
template<>
FO_COMMON_API int EvalImpl (const ScriptingContext &context) const
template<>
std::string EvalImpl (const ScriptingContext &context) const
template<>
double EvalImpl (const ScriptingContext &context) const
template<>
int EvalImpl (const ScriptingContext &context) const
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
T m_cached_const_value = T()
bool m_constant_expr = false
OpType m_op_type = TIMES
std::vector< std::unique_ptr< ValueRef< T > > > m_operands
Friends
class boost::serialization::access
Detailed Description
template<typename T>
struct ValueRef::Operation< T >
An arithmetic operation node ValueRef class.
Unary or binary operations such as addition, mutiplication, negation, exponentiation, rounding, value substitution, value comparisons, or random value selection or random number generation are performed on the child(ren) of this node, and the result is returned.
Constructor & Destructor Documentation
Operation() [1/3]
template<typename T > ValueRef::Operation< T >::Operation (OpType op_type, std::unique_ptr< ValueRef< T >> && operand1, std::unique_ptr< ValueRef< T >> && operand2)
Binary operation ctor.
References ValueRef::Operation< T >::CacheConstValue(), ValueRef::Operation< T >::DetermineIfConstantExpr(), and ValueRef::Operation< T >::m_operands.
Operation() [2/3]
template<typename T > ValueRef::Operation< T >::Operation (OpType op_type, std::unique_ptr< ValueRef< T >> && operand)
Unary operation ctor.
References ValueRef::Operation< T >::CacheConstValue(), ValueRef::Operation< T >::DetermineIfConstantExpr(), and ValueRef::Operation< T >::m_operands.
Operation() [3/3]
template<typename T > ValueRef::Operation< T >::Operation (OpType op_type, std::vector< std::unique_ptr< ValueRef< T >>> && operands)
References ValueRef::Operation< T >::CacheConstValue(), and ValueRef::Operation< T >::DetermineIfConstantExpr().
Member Function Documentation
CacheConstValue()
template<typename T > void ValueRef::Operation< T >::CacheConstValue () private
References ValueRef::Operation< T >::EvalImpl(), ValueRef::Operation< T >::m_cached_const_value, and ValueRef::Operation< T >::m_constant_expr.
Referenced by ValueRef::Operation< T >::Operation().
ConstantExpr()
template<typename T> bool ValueRef::Operation< T >::ConstantExpr () const inline override virtual
Reimplemented from ValueRef::ValueRef< T >.
References Effect::Dump(), and anonymous_namespace{Conditions.cpp}::EvalImpl().
Description()
template<typename T > std::string ValueRef::Operation< T >::Description () const override virtual
Implements ValueRef::ValueRef< T >.
References ValueRef::ABS, ValueRef::COSINE, ValueRef::DIVIDE, ValueRef::EXPONENTIATE, ValueRef::Operation< T >::LHS(), ValueRef::LOGARITHM, ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::MINUS, ValueRef::NEGATE, ValueRef::PLUS, ValueRef::RANDOM_PICK, ValueRef::RANDOM_UNIFORM, ValueRef::Operation< T >::RHS(), ValueRef::ROUND_DOWN, ValueRef::ROUND_NEAREST, ValueRef::ROUND_UP, ValueRef::SINE, and ValueRef::TIMES.
DetermineIfConstantExpr()
template<typename T > void ValueRef::Operation< T >::DetermineIfConstantExpr () private
References ValueRef::Operation< T >::m_constant_expr, ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::RANDOM_PICK, and ValueRef::RANDOM_UNIFORM.
Referenced by ValueRef::Operation< T >::Operation().
Dump()
template<typename T > std::string ValueRef::Operation< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a text description of this type of special.
Implements ValueRef::ValueRef< T >.
References ValueRef::ABS, ValueRef::COSINE, ValueRef::DIVIDE, ValueRef::EXPONENTIATE, ValueRef::Operation< T >::LHS(), ValueRef::LOGARITHM, ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::MINUS, ValueRef::NEGATE, ValueRef::PLUS, ValueRef::RANDOM_PICK, ValueRef::RANDOM_UNIFORM, ValueRef::Operation< T >::RHS(), ValueRef::ROUND_DOWN, ValueRef::ROUND_NEAREST, ValueRef::ROUND_UP, ValueRef::SINE, and ValueRef::TIMES.
Eval()
template<typename T > T ValueRef::Operation< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::EvalImpl(), ValueRef::Operation< T >::m_cached_const_value, and ValueRef::Operation< T >::m_constant_expr.
EvalImpl() [1/7]
template<typename T > T ValueRef::Operation< T >::EvalImpl (const ScriptingContext & context) const private
References ValueRef::COMPARE_EQUAL, ValueRef::COMPARE_GREATER_THAN, ValueRef::COMPARE_GREATER_THAN_OR_EQUAL, ValueRef::COMPARE_LESS_THAN, ValueRef::COMPARE_LESS_THAN_OR_EQUAL, ValueRef::COMPARE_NOT_EQUAL, ValueRef::ValueRef< T >::Eval(), ValueRef::Operation< T >::LHS(), ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::RANDOM_PICK, RandSmallInt(), ValueRef::Operation< T >::RHS(), and ValueRef::TIMES.
Referenced by ValueRef::Operation< T >::CacheConstValue(), ValueRef::Operation< T >::Eval(), and ValueRef::Operation< T >::GetCheckSum().
EvalImpl() [2/7]
template<> FO_COMMON_API std::string ValueRef::Operation< std::string >::EvalImpl (const ScriptingContext & context) const private
EvalImpl() [3/7]
template<> FO_COMMON_API double ValueRef::Operation< double >::EvalImpl (const ScriptingContext & context) const private
EvalImpl() [4/7]
template<> FO_COMMON_API int ValueRef::Operation< int >::EvalImpl (const ScriptingContext & context) const private
EvalImpl() [5/7]
template<> std::string ValueRef::Operation< std::string >::EvalImpl (const ScriptingContext & context) const private
References ValueRef::COMPARE_EQUAL, ValueRef::COMPARE_GREATER_THAN, ValueRef::COMPARE_GREATER_THAN_OR_EQUAL, ValueRef::COMPARE_LESS_THAN, ValueRef::COMPARE_LESS_THAN_OR_EQUAL, ValueRef::COMPARE_NOT_EQUAL, ValueRef::ValueRef< std::string >::Eval(), FlexibleFormat(), ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::PLUS, ValueRef::RANDOM_PICK, RandSmallInt(), ValueRef::SUBSTITUTION, and ValueRef::TIMES.
EvalImpl() [6/7]
template<> double ValueRef::Operation< double >::EvalImpl (const ScriptingContext & context) const private
References ValueRef::ABS, ValueRef::COMPARE_EQUAL, ValueRef::COMPARE_GREATER_THAN, ValueRef::COMPARE_GREATER_THAN_OR_EQUAL, ValueRef::COMPARE_LESS_THAN, ValueRef::COMPARE_LESS_THAN_OR_EQUAL, ValueRef::COMPARE_NOT_EQUAL, ValueRef::COSINE, ValueRef::DIVIDE, ErrorLogger, ValueRef::ValueRef< std::string >::Eval(), ValueRef::EXPONENTIATE, ValueRef::LOGARITHM, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::MINUS, ValueRef::NEGATE, ValueRef::PLUS, RandDouble(), ValueRef::RANDOM_PICK, ValueRef::RANDOM_UNIFORM, RandSmallInt(), ValueRef::ROUND_DOWN, ValueRef::ROUND_NEAREST, ValueRef::ROUND_UP, ValueRef::SINE, and ValueRef::TIMES.
EvalImpl() [7/7]
template<> int ValueRef::Operation< int >::EvalImpl (const ScriptingContext & context) const private
References ValueRef::ABS, ValueRef::COMPARE_EQUAL, ValueRef::COMPARE_GREATER_THAN, ValueRef::COMPARE_GREATER_THAN_OR_EQUAL, ValueRef::COMPARE_LESS_THAN, ValueRef::COMPARE_LESS_THAN_OR_EQUAL, ValueRef::COMPARE_NOT_EQUAL, ValueRef::COSINE, ValueRef::DIVIDE, ErrorLogger, ValueRef::ValueRef< std::string >::Eval(), ValueRef::EXPONENTIATE, ValueRef::LOGARITHM, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::MINUS, ValueRef::NEGATE, ValueRef::PLUS, RandInt(), ValueRef::RANDOM_PICK, ValueRef::RANDOM_UNIFORM, RandSmallInt(), ValueRef::ROUND_DOWN, ValueRef::ROUND_NEAREST, ValueRef::ROUND_UP, ValueRef::SINE, and ValueRef::TIMES.
GetCheckSum()
template<typename T > unsigned int ValueRef::Operation< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References CheckSums::CheckSumCombine(), ValueRef::Operation< T >::EvalImpl(), FO_COMMON_API, ValueRef::Operation< T >::m_cached_const_value, ValueRef::Operation< T >::m_constant_expr, ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, and TraceLogger.
GetOpType()
template<typename T > OpType ValueRef::Operation< T >::GetOpType () const
References ValueRef::Operation< T >::m_op_type.
LHS()
template<typename T > const ValueRef< T > * ValueRef::Operation< T >::LHS () const
1st operand (or 0 if none exists).
References ValueRef::Operation< T >::m_operands.
Referenced by ValueRef::Operation< T >::Description(), ValueRef::Operation< T >::Dump(), and ValueRef::Operation< T >::EvalImpl().
LocalCandidateInvariant()
template<typename T > bool ValueRef::Operation< T >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::RANDOM_PICK, and ValueRef::RANDOM_UNIFORM.
Operands()
template<typename T > const std::vector< ValueRef< T > * > ValueRef::Operation< T >::Operands () const
all operands
References ValueRef::Operation< T >::m_operands.
operator==()
template<typename T > bool ValueRef::Operation< T >::operator== (const ValueRef< T > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_constant_expr, and ValueRef::Operation< T >::m_operands.
RHS()
template<typename T > const ValueRef< T > * ValueRef::Operation< T >::RHS () const
2nd operand (or 0 if only one exists)
References ValueRef::Operation< T >::m_operands.
Referenced by ValueRef::Operation< T >::Description(), ValueRef::Operation< T >::Dump(), and ValueRef::Operation< T >::EvalImpl().
RootCandidateInvariant()
template<typename T > bool ValueRef::Operation< T >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::RANDOM_PICK, and ValueRef::RANDOM_UNIFORM.
serialize()
template<typename T > template<typename Archive > void ValueRef::Operation< T >::serialize (Archive & ar, const unsigned int version) private
References ValueRef::Operation< T >::m_cached_const_value, ValueRef::Operation< T >::m_constant_expr, ValueRef::Operation< T >::m_op_type, and ValueRef::Operation< T >::m_operands.
SetTopLevelContent()
template<typename T > void ValueRef::Operation< T >::SetTopLevelContent (const std::string & content_name) override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_operands.
SimpleIncrement()
template<typename T > bool ValueRef::Operation< T >::SimpleIncrement () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::EFFECT_TARGET_VALUE_REFERENCE, ValueRef::Variable< T >::GetReferenceType(), ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::MINUS, ValueRef::PLUS, and ValueRef::Operation< T >::TargetInvariant().
SourceInvariant()
template<typename T > bool ValueRef::Operation< T >::SourceInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::RANDOM_PICK, and ValueRef::RANDOM_UNIFORM.
TargetInvariant()
template<typename T > bool ValueRef::Operation< T >::TargetInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Operation< T >::m_op_type, ValueRef::Operation< T >::m_operands, ValueRef::RANDOM_PICK, and ValueRef::RANDOM_UNIFORM.
Referenced by ValueRef::Operation< T >::SimpleIncrement().
Friends And Related Function Documentation
boost::serialization::access
template<typename T> friend class boost::serialization::access friend
Member Data Documentation
m_cached_const_value
template<typename T> T ValueRef::Operation< T >::m_cached_const_value = T() private
Referenced by ValueRef::Operation< T >::CacheConstValue(), ValueRef::Operation< T >::Eval(), ValueRef::Operation< T >::GetCheckSum(), and ValueRef::Operation< T >::serialize().
m_constant_expr
template<typename T> bool ValueRef::Operation< T >::m_constant_expr = false private
Referenced by ValueRef::Operation< T >::CacheConstValue(), ValueRef::Operation< T >::DetermineIfConstantExpr(), ValueRef::Operation< T >::Eval(), ValueRef::Operation< T >::GetCheckSum(), ValueRef::Operation< T >::operator==(), and ValueRef::Operation< T >::serialize().
m_op_type
template<typename T> OpType ValueRef::Operation< T >::m_op_type = TIMES private
Referenced by ValueRef::Operation< T >::Description(), ValueRef::Operation< T >::DetermineIfConstantExpr(), ValueRef::Operation< T >::Dump(), ValueRef::Operation< T >::EvalImpl(), ValueRef::Operation< T >::GetCheckSum(), ValueRef::Operation< T >::GetOpType(), ValueRef::Operation< T >::LocalCandidateInvariant(), ValueRef::Operation< T >::RootCandidateInvariant(), ValueRef::Operation< T >::serialize(), ValueRef::Operation< T >::SimpleIncrement(), ValueRef::Operation< T >::SourceInvariant(), and ValueRef::Operation< T >::TargetInvariant().
m_operands
template<typename T> std::vector<std::unique_ptr<ValueRef<T> > > ValueRef::Operation< T >::m_operands private
Referenced by ValueRef::Operation< T >::Description(), ValueRef::Operation< T >::DetermineIfConstantExpr(), ValueRef::Operation< T >::Dump(), ValueRef::Operation< T >::EvalImpl(), ValueRef::Operation< T >::GetCheckSum(), ValueRef::Operation< T >::LHS(), ValueRef::Operation< T >::LocalCandidateInvariant(), ValueRef::Operation< T >::Operands(), ValueRef::Operation< T >::Operation(), ValueRef::Operation< T >::operator==(), ValueRef::Operation< T >::RHS(), ValueRef::Operation< T >::RootCandidateInvariant(), ValueRef::Operation< T >::serialize(), ValueRef::Operation< T >::SetTopLevelContent(), ValueRef::Operation< T >::SimpleIncrement(), ValueRef::Operation< T >::SourceInvariant(), and ValueRef::Operation< T >::TargetInvariant().
The documentation for this struct was generated from the following file:
ValueRefs.h