FreeOrion: Condition::Source Struct Reference
Condition::Source Struct Reference final
Matches the source object only.
#include <ConditionSource.h>
Public Member Functions
Source ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
virtual bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches the source object only.
Constructor & Destructor Documentation
Source()
Condition::Source::Source () inline
References operator==().
Member Function Documentation
Description()
std::string Condition::Source::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References UserString().
Dump()
std::string Condition::Source::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent().
GetCheckSum()
unsigned int Condition::Source::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::Source::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::source.
Match()
bool Condition::Source::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, and ScriptingContext::source.
operator==()
bool Condition::Source::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References Condition::Condition::operator==().
RootCandidateInvariant()
bool Condition::Source::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
serialize()
template<typename Archive > void Condition::Source::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Source::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::Condition.
TargetInvariant()
bool Condition::Source::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References Effect::Dump().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
ConditionSource.h
Conditions.cpp
Conditions.h