FreeOrion: WaitingForTurnData Struct Reference
WaitingForTurnData Struct Reference
The substate of PlayingGame in which a game is about to start, or the player is waiting for turn resolution and a new turn.
#include <HumanClientFSM.h>
Classes
struct TurnDataUnpackedNotification
struct UnpackFailedNotification
Public Types
typedef boost::statechart::state< WaitingForTurnData, PlayingGame > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< SaveGameComplete >, boost::statechart::custom_reaction< TurnUpdate >, boost::statechart::custom_reaction< TurnDataUnpackedNotification >, boost::statechart::custom_reaction< UnpackFailedNotification >, boost::statechart::custom_reaction< TurnRevoked >, boost::statechart::custom_reaction< DispatchCombatLogs > > reactions
Public Member Functions
WaitingForTurnData (my_context ctx)
~WaitingForTurnData ()
boost::statechart::result react (const SaveGameComplete &d)
boost::statechart::result react (const TurnUpdate &msg)
boost::statechart::result react (const TurnDataUnpackedNotification &data)
boost::statechart::result react (const UnpackFailedNotification &)
boost::statechart::result react (const TurnRevoked &msg)
boost::statechart::result react (const DispatchCombatLogs &msg)
Detailed Description
The substate of PlayingGame in which a game is about to start, or the player is waiting for turn resolution and a new turn.
Member Typedef Documentation
Base
typedef boost::statechart::state<WaitingForTurnData, PlayingGame> WaitingForTurnData::Base
reactions
typedef boost::mpl::list< boost::statechart::custom_reaction<SaveGameComplete>, boost::statechart::custom_reaction<TurnUpdate>, boost::statechart::custom_reaction<TurnDataUnpackedNotification>, boost::statechart::custom_reaction<UnpackFailedNotification>, boost::statechart::custom_reaction<TurnRevoked>, boost::statechart::custom_reaction<DispatchCombatLogs> > WaitingForTurnData::reactions
Constructor & Destructor Documentation
WaitingForTurnData()
WaitingForTurnData::WaitingForTurnData (my_context ctx)
References TraceLogger.
~WaitingForTurnData()
WaitingForTurnData::~WaitingForTurnData ()
References TraceLogger.
Member Function Documentation
react() [1/6]
boost::statechart::result WaitingForTurnData::react (const SaveGameComplete & d)
References ExtractServerSaveGameCompleteMessageData(), FlexibleFormat(), TraceLogger, and UserString().
react() [2/6]
boost::statechart::result WaitingForTurnData::react (const TurnUpdate & msg)
References ErrorLogger, TraceLogger, and UserString().
react() [3/6]
boost::statechart::result WaitingForTurnData::react (const TurnDataUnpackedNotification & data)
References DebugLogger, Empires(), ErrorLogger, GetCombatLogManager(), GetSpeciesManager(), GetSupplyManager(), GetUniverse(), and WaitingForTurnData::TurnDataUnpackedNotification::unpacked.
react() [4/6]
boost::statechart::result WaitingForTurnData::react (const UnpackFailedNotification &)
react() [5/6]
boost::statechart::result WaitingForTurnData::react (const TurnRevoked & msg)
References TraceLogger.
react() [6/6]
boost::statechart::result WaitingForTurnData::react (const DispatchCombatLogs & msg)
References DebugLogger.
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp