FreeOrion: Condition::Turn Struct Reference
Condition::Turn Struct Reference final
Matches all objects if the current game turn is >= low and < high.
#include <Conditions.h>
Public Member Functions
Turn (std::unique_ptr< ValueRef::ValueRef< int >> &&low, std::unique_ptr< ValueRef::ValueRef< int >> &&high=nullptr)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Condition::Condition
Condition ()=default
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_high
std::unique_ptr< ValueRef::ValueRef< int > > m_low
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
Matches all objects if the current game turn is >= low and < high.
Constructor & Destructor Documentation
Turn()
Condition::Turn::Turn (std::unique_ptr< ValueRef::ValueRef< int >> && low, std::unique_ptr< ValueRef::ValueRef< int >> && high = nullptr) explicit
References m_high, m_low, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, and Condition::Condition::m_target_invariant.
Member Function Documentation
Description()
std::string Condition::Turn::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), m_high, m_low, to_string(), and UserString().
Dump()
std::string Condition::Turn::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), m_high, and m_low.
Eval()
void Condition::Turn::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), m_high, m_low, Match(), Condition::MATCHES, Condition::NON_MATCHES, and Condition::Condition::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::Turn::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_high, m_low, and TraceLogger.
Match()
bool Condition::Turn::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References BEFORE_FIRST_TURN, CurrentTurn(), IMPOSSIBLY_LARGE_TURN, m_high, and m_low.
Referenced by Eval().
operator==()
bool Condition::Turn::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, m_high, and m_low.
SetTopLevelContent()
void Condition::Turn::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_high, and m_low.
Member Data Documentation
m_high
std::unique_ptr<ValueRef::ValueRef<int> > Condition::Turn::m_high private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), operator==(), SetTopLevelContent(), and Turn().
m_low
std::unique_ptr<ValueRef::ValueRef<int> > Condition::Turn::m_low private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), operator==(), SetTopLevelContent(), and Turn().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp