FreeOrion: Condition::PlanetEnvironment Struct Reference
Condition::PlanetEnvironment Struct Reference final
Matches all Planet objects that have one of the PlanetEnvironments in environments.
#include <Conditions.h>
Public Member Functions
PlanetEnvironment (std::vector< std::unique_ptr< ValueRef::ValueRef< ::PlanetEnvironment >>> &&environments, std::unique_ptr< ValueRef::ValueRef< std::string >> &&species_name_ref=nullptr)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< std::unique_ptr< ValueRef::ValueRef<::PlanetEnvironment > > > m_environments
std::unique_ptr< ValueRef::ValueRef< std::string > > m_species_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all Planet objects that have one of the PlanetEnvironments in environments.
Note that all Building objects which are on matching planets are also matched.
Constructor & Destructor Documentation
PlanetEnvironment()
Condition::PlanetEnvironment::PlanetEnvironment (std::vector< std::unique_ptr< ValueRef::ValueRef< ::PlanetEnvironment >>> && environments, std::unique_ptr< ValueRef::ValueRef< std::string >> && species_name_ref = nullptr)
Member Function Documentation
Description()
std::string Condition::PlanetEnvironment::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References Eval(), FlexibleFormat(), m_environments, m_species_name, UserString(), and UserStringExists().
Dump()
std::string Condition::PlanetEnvironment::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), m_environments, and m_species_name.
Eval()
void Condition::PlanetEnvironment::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), m_environments, m_species_name, ScriptingContext::objects, and RootCandidateInvariant().
Referenced by Description().
GetCheckSum()
unsigned int Condition::PlanetEnvironment::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_environments, m_species_name, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::PlanetEnvironment::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References anonymous_namespace{Conditions.cpp}::AddBuildingSet(), anonymous_namespace{Conditions.cpp}::AddPlanetSet(), and ScriptingContext::objects.
Match()
bool Condition::PlanetEnvironment::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, ObjectMap::get(), m_environments, m_species_name, and ScriptingContext::objects.
operator==()
bool Condition::PlanetEnvironment::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, m_environments, and m_species_name.
RootCandidateInvariant()
bool Condition::PlanetEnvironment::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
References m_environments, and m_species_name.
Referenced by Eval().
serialize()
template<class Archive > void Condition::PlanetEnvironment::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::PlanetEnvironment::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_environments, and m_species_name.
SourceInvariant()
bool Condition::PlanetEnvironment::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References m_environments, and m_species_name.
TargetInvariant()
bool Condition::PlanetEnvironment::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References m_environments, and m_species_name.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_environments
std::vector<std::unique_ptr<ValueRef::ValueRef<::PlanetEnvironment> > > Condition::PlanetEnvironment::m_environments private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Conditions.cpp}::PlanetEnvironmentSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
m_species_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Condition::PlanetEnvironment::m_species_name private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp