FreeOrion: anonymous_namespace{CUIControls.cpp}::SpeciesRow Struct Reference
anonymous_namespace{CUIControls.cpp}::SpeciesRow Struct Reference
Public Member Functions
SpeciesRow (const Species *species, GG::X w, GG::Y h)
SpeciesRow (std::string species_name, std::string localized_name, std::string species_desc, GG::X w, GG::Y h, std::shared_ptr< GG::Texture > species_icon)
void CompleteConstruction () override
Private Member Functions
void Init (std::string species_name, std::string localized_name, std::string species_desc, GG::X width, GG::Y height, std::shared_ptr< GG::Texture > species_icon)
Private Attributes
std::shared_ptr< GG::StaticGraphic > m_icon
std::shared_ptr< CUILabel > m_species_label
Constructor & Destructor Documentation
SpeciesRow() [1/2]
anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow (const Species * species, GG::X w, GG::Y h) inline
References Species::GameplayDescription(), Species::Name(), anonymous_namespace{ServerWrapper.cpp}::SetName(), ClientUI::SpeciesIcon(), and UserString().
SpeciesRow() [2/2]
anonymous_namespace{CUIControls.cpp}::SpeciesRow::SpeciesRow (std::string species_name, std::string localized_name, std::string species_desc, GG::X w, GG::Y h, std::shared_ptr< GG::Texture > species_icon) inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{CUIControls.cpp}::SpeciesRow::CompleteConstruction () inline override
Init()
void anonymous_namespace{CUIControls.cpp}::SpeciesRow::Init (std::string species_name, std::string localized_name, std::string species_desc, GG::X width, GG::Y height, std::shared_ptr< GG::Texture > species_icon) inline private
References GetOptionsDB(), and anonymous_namespace{ServerWrapper.cpp}::SetName().
Member Data Documentation
m_icon
std::shared_ptr<GG::StaticGraphic> anonymous_namespace{CUIControls.cpp}::SpeciesRow::m_icon private
m_species_label
std::shared_ptr<CUILabel> anonymous_namespace{CUIControls.cpp}::SpeciesRow::m_species_label private
The documentation for this struct was generated from the following file:
CUIControls.cpp