FreeOrion: UniverseObjectVisitor Struct Reference
UniverseObjectVisitor Struct Reference
Base class for UniverseObject visitores.
#include <UniverseObjectVisitor.h>
Public Member Functions
virtual ~UniverseObjectVisitor ()
virtual auto Visit (const std::shared_ptr< UniverseObject > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Building > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Fleet > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Planet > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Ship > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< System > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Field > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Fighter > &obj) const -> std::shared_ptr< UniverseObject >
Detailed Description
Base class for UniverseObject visitores.
These visitors have Visit() overloads for each type in the UniversObject-based class herarchy. Calling Visit() returns the obj parameter, if some predicate is true of that object. Each UniverseObject subclass needs to have an Accept(const UniverseObjectVisitor& visitor) method that consists only of "visitor->Visit(this)". Because of the specific-type overloads, passing a UniverseObjectVisitor into the Accept() method of a UniverseObject will cause the UniverseObjectVisitor's appropriate Visit() method to be called. Since the specific type of the obj parameter is known within each Visit() method,obj can be accessed by type, without using a dynamic_cast. Note that is is therefore safe to static_cast a UniversObject pointer that is returned from a UniverseObjectVisitor subclass that only returns a nonzero for one specific UniverseObject subclass (e.g. StationaryFleetVisitor<Planet>). The default behavior of all Visit() methods besides Visit(UniverseObject*) is to return the result of a call to Visit(UniverseObject*). This means that UniverseObjectVisitor subclasses can override Visit(UniverseObject*) only, and calls to all Visit() overloads will work. The default return value for Visit(UniverseObject*) is 0, so overridding any one Visit() method besides this one will ensure that only UniverseObjects of a single subclass are recognized by the visitor.
Constructor & Destructor Documentation
~UniverseObjectVisitor()
UniverseObjectVisitor::~UniverseObjectVisitor () virtual default
Member Function Documentation
Visit() [1/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< UniverseObject > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in HostileVisitor, and OwnedVisitor.
Referenced by Building::Accept(), Fighter::Accept(), Ship::Accept(), Field::Accept(), Fleet::Accept(), Planet::Accept(), and UniverseObject::Accept().
Visit() [2/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Building > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor.
Visit() [3/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Fleet > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor, MovingFleetVisitor, OrderedMovingFleetVisitor, and StationaryFleetVisitor.
Visit() [4/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Planet > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor.
Visit() [5/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Ship > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor.
Visit() [6/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< System > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor.
Visit() [7/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Field > & obj) const -> std::shared_ptr<UniverseObject> virtual
Reimplemented in anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor.
Visit() [8/8]
auto UniverseObjectVisitor::Visit (const std::shared_ptr< Fighter > & obj) const -> std::shared_ptr<UniverseObject> virtual
The documentation for this struct was generated from the following files:
UniverseObjectVisitor.h
UniverseObjectVisitor.cpp