FreeOrion: Condition::OwnerHasShipDesignAvailable Struct Reference
Condition::OwnerHasShipDesignAvailable Struct Reference final
Matches all objects whose owner who has the ship design id available.
#include <Condition.h>
Public Member Functions
OwnerHasShipDesignAvailable (int id)
OwnerHasShipDesignAvailable (std::unique_ptr< ValueRef::ValueRefBase< int >> &&id)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRefBase< int > > m_id
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all objects whose owner who has the ship design id available.
Constructor & Destructor Documentation
OwnerHasShipDesignAvailable() [1/2]
Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable (int id) explicit
OwnerHasShipDesignAvailable() [2/2]
Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable (std::unique_ptr< ValueRef::ValueRefBase< int >> && id) explicit
Member Function Documentation
Description()
std::string Condition::OwnerHasShipDesignAvailable::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString().
Dump()
std::string Condition::OwnerHasShipDesignAvailable::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_id.
Eval()
void Condition::OwnerHasShipDesignAvailable::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), INVALID_DESIGN_ID, m_id, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::OwnerHasShipDesignAvailable::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_id, and TraceLogger.
Match()
bool Condition::OwnerHasShipDesignAvailable::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, INVALID_DESIGN_ID, and m_id.
operator==()
bool Condition::OwnerHasShipDesignAvailable::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_id.
RootCandidateInvariant()
bool Condition::OwnerHasShipDesignAvailable::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_id.
Referenced by Eval().
serialize()
template<class Archive > void Condition::OwnerHasShipDesignAvailable::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::OwnerHasShipDesignAvailable::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_id.
SourceInvariant()
bool Condition::OwnerHasShipDesignAvailable::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_id.
TargetInvariant()
bool Condition::OwnerHasShipDesignAvailable::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_id.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_id
std::unique_ptr<ValueRef::ValueRefBase<int> > Condition::OwnerHasShipDesignAvailable::m_id private
Referenced by Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipDesignAvailableSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp