FreeOrion: Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch Struct Reference
Public Member Functions
DesignHasPartSimpleMatch (int low, int high, const std::string &name)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
int m_high
int m_low
const std::string & m_name
Constructor & Destructor Documentation
DesignHasPartSimpleMatch()
Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::DesignHasPartSimpleMatch (int low, int high, const std::string & name) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References Condition::DesignHasPart::m_high, Condition::DesignHasPart::m_low, Condition::DesignHasPart::m_name, ObjectMap::Object(), Objects(), and ShipDesign::Parts().
Member Data Documentation
m_high
int Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::m_high
m_low
int Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::m_low
m_name
const std::string& Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::m_name
The documentation for this struct was generated from the following file:
Condition.cpp