FreeOrion: anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7 Struct Reference
anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7 Struct Reference
Public Types
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< std::vector< ValueRef::ValueRefBase< StarType > * > > > star_type_vec_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< Condition::ContentType, ValueRef::ValueRefBase< std::string > *, ValueRef::ValueRefBase< std::string > * > > string_ref_rule
Public Member Functions
condition_parser_rules_7 ()
Public Attributes
parse::condition_parser_rule contained_by
parse::condition_parser_rule contains
string_ref_rule location
parse::condition_parser_rule ordered_bombarded_by
parse::condition_parser_rule owner_has_shippart_available
star_type_vec_rule star_type
parse::condition_parser_rule start
Member Typedef Documentation
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals<std::vector<ValueRef::ValueRefBase<StarType>*> > > anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::star_type_vec_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< Condition::ContentType, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<std::string>* > > anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::string_ref_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::condition_parser_rules_7 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, parse::detail::enum_value_ref_rules< T >::expr, parse::lexer::instance(), parse::detail::label(), parse::detail::star_type_rules(), and parse::string_value_ref().
Member Data Documentation
parse::condition_parser_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::contained_by
parse::condition_parser_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::contains
string_ref_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::location
parse::condition_parser_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::ordered_bombarded_by
parse::condition_parser_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::owner_has_shippart_available
star_type_vec_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::star_type
parse::condition_parser_rule anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::start
The documentation for this struct was generated from the following file:
ConditionParser7.cpp