FreeOrion: Condition::Chance Struct Reference
Condition::Chance Struct Reference final
Matches a given object with a linearly distributed probability of chance.
#include <Conditions.h>
Public Member Functions
Chance (std::unique_ptr< ValueRef::ValueRef< double >> &&chance)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< double > > m_chance
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches a given object with a linearly distributed probability of chance.
Constructor & Destructor Documentation
Chance()
Condition::Chance::Chance (std::unique_ptr< ValueRef::ValueRef< double >> && chance)
Member Function Documentation
Description()
std::string Condition::Chance::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), m_chance, to_string(), and UserString().
Dump()
std::string Condition::Chance::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_chance.
Eval()
void Condition::Chance::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), m_chance, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::Chance::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_chance, and TraceLogger.
Match()
bool Condition::Chance::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References m_chance, and RandZeroToOne().
operator==()
bool Condition::Chance::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_chance.
RootCandidateInvariant()
bool Condition::Chance::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
References m_chance.
Referenced by Eval().
serialize()
template<typename Archive > void Condition::Chance::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Chance::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_chance.
SourceInvariant()
bool Condition::Chance::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References m_chance.
TargetInvariant()
bool Condition::Chance::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References m_chance.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_chance
std::unique_ptr<ValueRef::ValueRef<double> > Condition::Chance::m_chance private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Conditions.cpp}::ChanceSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp