FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow Struct Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow Struct Reference
Public Member Functions
LoadGameEmpireRow (const SaveGameEmpireData &save_game_empire_data, bool disabled)
void CompleteConstruction () override
Public Member Functions inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
PlayerRow ()
PlayerRow (const PlayerSetupData &player_data, int player_id)
Private Member Functions
void PlayerTypeChanged (Networking::ClientType type)
Private Attributes
std::shared_ptr< EmpireColorSelector > m_color_selector
bool m_initial_disabled = false
const SaveGameEmpireData & m_save_game_empire_data
Additional Inherited Members
Public Attributes inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
boost::signals2::signal< void()> DataChangedSignal
PlayerSetupData m_player_data
int m_player_id
Constructor & Destructor Documentation
LoadGameEmpireRow()
anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::LoadGameEmpireRow (const SaveGameEmpireData & save_game_empire_data, bool disabled) inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::CompleteConstruction () inline override
References Networking::INVALID_CLIENT_TYPE, anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowMargin().
PlayerTypeChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::PlayerTypeChanged (Networking::ClientType type) inline private
Member Data Documentation
m_color_selector
std::shared_ptr<EmpireColorSelector> anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::m_color_selector private
m_initial_disabled
bool anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::m_initial_disabled = false private
m_save_game_empire_data
const SaveGameEmpireData& anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGameEmpireRow::m_save_game_empire_data private
The documentation for this struct was generated from the following file:
MultiplayerLobbyWnd.cpp