FreeOrion: Idle Struct Reference
Idle Struct Reference
The server's initial state.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::custom_reaction< HostMPGame >, sc::custom_reaction< HostSPGame >, sc::custom_reaction< ShutdownServer >, sc::custom_reaction< Error >, sc::custom_reaction< Hostless > > reactions
Public Member Functions
Idle (my_context c)
~Idle ()
sc::result react (const HostMPGame &msg)
sc::result react (const HostSPGame &msg)
sc::result react (const ShutdownServer &u)
sc::result react (const Error &msg)
sc::result react (const Hostless &)
Detailed Description
The server's initial state.
Member Typedef Documentation
reactions
typedef boost::mpl::list< sc::custom_reaction<HostMPGame>, sc::custom_reaction<HostSPGame>, sc::custom_reaction<ShutdownServer>, sc::custom_reaction<Error>, sc::custom_reaction<Hostless> > Idle::reactions
Constructor & Destructor Documentation
Idle()
Idle::Idle (my_context c)
References GetOptionsDB(), and TraceLogger.
~Idle()
Idle::~Idle ()
References TraceLogger.
Member Function Documentation
react() [1/5]
sc::result Idle::react (const HostMPGame & msg)
References Networking::CLIENT_TYPE_HUMAN_PLAYER, ContentCheckSumMessage(), DebugLogger, ErrorLogger, ExtractHostMPGameMessageData(), GetOptionsDB(), HostMPAckMessage(), ServerApp::m_networking, ServerApp::m_single_player_game, ServerNetworking::NewPlayerID(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, Networking::ROLE_GALAXY_SETUP, Networking::ROLE_HOST, ServerNetworking::SetHostPlayerID(), and TraceLogger.
react() [2/5]
sc::result Idle::react (const HostSPGame & msg)
References Networking::CLIENT_TYPE_HUMAN_PLAYER, ContentCheckSumMessage(), ErrorLogger, ErrorMessage(), ExtractHostSPGameMessageData(), anonymous_namespace{ServerFSM.cpp}::GetHostNameFromSinglePlayerSetupData(), GetOptionsDB(), HostSPAckMessage(), ServerApp::m_networking, ServerApp::m_single_player_game, ServerNetworking::NewPlayerID(), Networking::ROLE_CLIENT_TYPE_PLAYER, Networking::ROLE_GALAXY_SETUP, Networking::ROLE_HOST, ServerNetworking::SetHostPlayerID(), TraceLogger, and UserStringNop.
react() [3/5]
sc::result Idle::react (const ShutdownServer & u)
References TraceLogger.
react() [4/5]
sc::result Idle::react (const Error & msg)
References anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage().
react() [5/5]
sc::result Idle::react (const Hostless &)
References PlayerSetupData::client_type, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, PlayerSetupData::empire_color, PlayerSetupData::empire_name, Empires(), ServerApp::FillListPlayers(), anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), OptionsDB::Get(), GetCombatLogManager(), GetGameRules(), GetOptionsDB(), GameRules::GetRulesAsStrings(), GetSpeciesManager(), GetUniverse(), anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour(), ServerApp::InitializePython(), Networking::INVALID_PLAYER_ID, ServerApp::LoadChatHistory(), LoadGame(), ServerApp::m_galaxy_setup_data, PlayerSetupData::player_id, PlayerSetupData::player_name, SpeciesManager::RandomPlayableSpeciesName(), PlayerSetupData::save_game_empire_id, Seed(), GalaxySetupData::seed, SpeciesManager::SequentialPlayableSpeciesName(), PlayerSetupData::starting_species_name, to_string(), TraceLogger, and UserString().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp