FreeOrion: ValueRef::ComplexVariable< T > Struct Template Reference
ValueRef::ComplexVariable< T > Struct Template Reference final
The complex variable ValueRef class.
#include <ValueRefs.h>
Public Member Functions
template<typename S >
ComplexVariable (S &&variable_name, std::unique_ptr< ValueRef< int >> &&int_ref1=nullptr, std::unique_ptr< ValueRef< int >> &&int_ref2=nullptr, std::unique_ptr< ValueRef< int >> &&int_ref3=nullptr, std::unique_ptr< ValueRef< std::string >> &&string_ref1=nullptr, std::unique_ptr< ValueRef< std::string >> &&string_ref2=nullptr, bool return_immediate_value=false)
ComplexVariable (const char *variable_name, std::unique_ptr< ValueRef< int >> &&int_ref1=nullptr, std::unique_ptr< ValueRef< int >> &&int_ref2=nullptr, std::unique_ptr< ValueRef< int >> &&int_ref3=nullptr, std::unique_ptr< ValueRef< std::string >> &&string_ref1=nullptr, std::unique_ptr< ValueRef< std::string >> &&string_ref2=nullptr, bool return_immediate_value=false)
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
T Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
const ValueRef< int > * IntRef1 () const
const ValueRef< int > * IntRef2 () const
const ValueRef< int > * IntRef3 () const
bool operator== (const ValueRef< T > &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Returns a textual representation that should be parseable to recreate this ValueRef.
const ValueRef< std::string > * StringRef1 () const
const ValueRef< std::string > * StringRef2 () const
Public Member Functions inherited from ValueRef::Variable< T >
template<typename S >
Variable (ReferenceType ref_type, S &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const char *property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, bool return_immediate_value=false)
Variable (ReferenceType ref_type, boost::optional< std::string > &&container_name, std::string &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, std::vector< std::string > &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name, bool return_immediate_value=false)
ReferenceType GetReferenceType () const
const std::vector< std::string > & PropertyName () const
bool ReturnImmediateValue () const
Public Member Functions inherited from ValueRef::ValueRef< T >
ValueRef ()=default
virtual ~ValueRef ()=default
T Eval () const
Evaluates the expression tree with an empty context.
std::string EvalAsString () const final
Evaluates the expression tree with an empty context and retuns the a string representation of the result value iff the result type is supported (currently std::string, int, float, double, enum).
bool operator!= (const ValueRef< T > &rhs) const
Public Member Functions inherited from ValueRef::ValueRefBase
ValueRefBase ()=default
virtual ~ValueRefBase ()=default
virtual bool ConstantExpr () const
std::string InvariancePattern () const
virtual bool LocalCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Protected Member Functions
void InitInvariants ()
Protected Member Functions inherited from ValueRef::Variable< T >
void InitInvariants ()
Protected Attributes
std::unique_ptr< ValueRef< int > > m_int_ref1
std::unique_ptr< ValueRef< int > > m_int_ref2
std::unique_ptr< ValueRef< int > > m_int_ref3
std::unique_ptr< ValueRef< std::string > > m_string_ref1
std::unique_ptr< ValueRef< std::string > > m_string_ref2
Protected Attributes inherited from ValueRef::Variable< T >
std::vector< std::string > m_property_name
ReferenceType m_ref_type = ReferenceType::INVALID_REFERENCE_TYPE
bool m_return_immediate_value = false
Protected Attributes inherited from ValueRef::ValueRefBase
bool m_local_candidate_invariant = false
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
template<typename T>
struct ValueRef::ComplexVariable< T >
The complex variable ValueRef class.
The value returned by this node is taken from the gamestate.
Constructor & Destructor Documentation
ComplexVariable() [1/2]
template<typename T > template<typename S > ValueRef::ComplexVariable< T >::ComplexVariable (S && variable_name, std::unique_ptr< ValueRef< int >> && int_ref1 = nullptr, std::unique_ptr< ValueRef< int >> && int_ref2 = nullptr, std::unique_ptr< ValueRef< int >> && int_ref3 = nullptr, std::unique_ptr< ValueRef< std::string >> && string_ref1 = nullptr, std::unique_ptr< ValueRef< std::string >> && string_ref2 = nullptr, bool return_immediate_value = false) explicit
References ValueRef::ComplexVariable< T >::InitInvariants().
ComplexVariable() [2/2]
template<typename T > ValueRef::ComplexVariable< T >::ComplexVariable (const char * variable_name, std::unique_ptr< ValueRef< int >> && int_ref1 = nullptr, std::unique_ptr< ValueRef< int >> && int_ref2 = nullptr, std::unique_ptr< ValueRef< int >> && int_ref3 = nullptr, std::unique_ptr< ValueRef< std::string >> && string_ref1 = nullptr, std::unique_ptr< ValueRef< std::string >> && string_ref2 = nullptr, bool return_immediate_value = false) explicit
References ValueRef::ComplexVariable< T >::InitInvariants().
Member Function Documentation
Description()
template<typename T > std::string ValueRef::ComplexVariable< T >::Description () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::ComplexVariableDescription(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::Variable< T >::m_property_name, ValueRef::ComplexVariable< T >::m_string_ref1, and ValueRef::ComplexVariable< T >::m_string_ref2.
Dump() [1/11]
template<typename T > std::string ValueRef::ComplexVariable< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::ComplexVariableDump(), ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::Variable< T >::m_property_name, ValueRef::ComplexVariable< T >::m_string_ref1, and ValueRef::ComplexVariable< T >::m_string_ref2.
Referenced by ValueRef::ComplexVariable< T >::Description(), and ValueRef::ComplexVariable< T >::GetCheckSum().
Dump() [2/11]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< std::vector< std::string > >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [3/11]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< Visibility >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [4/11]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< double >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [5/11]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< int >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [6/11]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< std::string >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [7/11]
template<> std::string ValueRef::ComplexVariable< Visibility >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [8/11]
template<> std::string ValueRef::ComplexVariable< double >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [9/11]
template<> std::string ValueRef::ComplexVariable< int >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [10/11]
template<> std::string ValueRef::ComplexVariable< std::string >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Dump() [11/11]
template<> std::string ValueRef::ComplexVariable< std::vector< std::string > >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Reimplemented from ValueRef::Variable< T >.
Eval() [1/21]
template<typename T> T ValueRef::ComplexVariable< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Referenced by ValueRef::ComplexVariable< T >::Eval().
Eval() [2/21]
template<> PlanetSize ValueRef::ComplexVariable< PlanetSize >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References INVALID_PLANET_SIZE.
Eval() [3/21]
template<> PlanetType ValueRef::ComplexVariable< PlanetType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [4/21]
template<> PlanetEnvironment ValueRef::ComplexVariable< PlanetEnvironment >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ScriptingContext::ContextObjects(), Planet::EnvironmentForSpecies(), ObjectMap::get(), and INVALID_OBJECT_ID.
Eval() [5/21]
template<> UniverseObjectType ValueRef::ComplexVariable< UniverseObjectType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [6/21]
template<> FO_COMMON_API PlanetSize ValueRef::ComplexVariable< PlanetSize >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [7/21]
template<> StarType ValueRef::ComplexVariable< StarType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [8/21]
template<> FO_COMMON_API PlanetType ValueRef::ComplexVariable< PlanetType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [9/21]
template<> Visibility ValueRef::ComplexVariable< Visibility >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ALL_EMPIRES, Universe::GetObjectVisibilityByEmpire(), GetUniverse(), INVALID_OBJECT_ID, INVALID_VISIBILITY, and VIS_NO_VISIBILITY.
Eval() [10/21]
template<> FO_COMMON_API PlanetEnvironment ValueRef::ComplexVariable< PlanetEnvironment >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [11/21]
template<> FO_COMMON_API UniverseObjectType ValueRef::ComplexVariable< UniverseObjectType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [12/21]
template<> FO_COMMON_API StarType ValueRef::ComplexVariable< StarType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [13/21]
template<> FO_COMMON_API std::vector< std::string > ValueRef::ComplexVariable< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [14/21]
template<> FO_COMMON_API Visibility ValueRef::ComplexVariable< Visibility >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [15/21]
template<> FO_COMMON_API double ValueRef::ComplexVariable< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [16/21]
template<> FO_COMMON_API int ValueRef::ComplexVariable< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [17/21]
template<> FO_COMMON_API std::string ValueRef::ComplexVariable< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
Eval() [18/21]
template<> int ValueRef::ComplexVariable< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ALL_EMPIRES, ScriptingContext::ContextObjects(), GameRules::DOUBLE, Empires(), ValueRef::ComplexVariable< T >::Eval(), ObjectMap::get(), GameRules::Get(), GetEmpire(), GetGameRules(), GetPathfinder(), GetPredefinedShipDesign(), GetShipDesign(), GetShipHull(), GetShipPart(), GameRules::GetType(), ShipDesign::Hull(), ShipDesign::ID(), IMPOSSIBLY_LARGE_TURN, GameRules::INT, INVALID_DESIGN_ID, INVALID_OBJECT_ID, ShipDesign::PartCount(), ShipDesign::Parts(), GameRules::RuleExists(), and GameRules::TOGGLE.
Eval() [19/21]
template<> double ValueRef::ComplexVariable< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ALL_EMPIRES, ScriptingContext::ContextObjects(), Meter::Current(), GameRules::DOUBLE, Empires(), ValueRef::ComplexVariable< T >::Eval(), ObjectMap::get(), GameRules::Get(), GetEmpire(), GetGameRules(), GetPathfinder(), GetShipDesign(), GetShipHull(), GetShipPart(), GetSpecies(), GetSpeciesManager(), GetSupplyManager(), GameRules::GetType(), GameRules::INT, INVALID_DESIGN_ID, INVALID_OBJECT_ID, ValueRef::NameToMeter(), ShipDesign::ProductionCost(), SupplyManager::PropagatedSupplyDistances(), SupplyManager::PropagatedSupplyRanges(), GameRules::RuleExists(), parse::species(), SpeciesManager::SpeciesEmpireOpinion(), SpeciesManager::SpeciesSpeciesOpinion(), and GameRules::TOGGLE.
Eval() [20/21]
template<> std::string ValueRef::ComplexVariable< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ALL_EMPIRES, ResearchQueue::begin(), GameRules::DOUBLE, DoubleToString(), ResearchQueue::end(), ResearchQueue::find(), GameRules::Get(), GetEmpire(), GetGameRules(), GetTech(), GameRules::GetType(), GameRules::INT, RandInt(), Tech::ResearchCost(), GameRules::RuleExists(), GameRules::STRING, ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchableByEmpire(), ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchedByEmpire(), to_string(), GameRules::TOGGLE, and ValueRef::anonymous_namespace{ValueRefs.cpp}::TransferrableTechs().
Eval() [21/21]
template<> std::vector< std::string > ValueRef::ComplexVariable< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ALL_EMPIRES, and GetEmpire().
GetCheckSum()
template<typename T > unsigned int ValueRef::ComplexVariable< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::Variable< T >.
References CheckSums::CheckSumCombine(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ValueRef< T >::Eval(), FO_COMMON_API, ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::ComplexVariable< T >::m_string_ref1, ValueRef::ComplexVariable< T >::m_string_ref2, and TraceLogger.
InitInvariants()
template<typename T > void ValueRef::ComplexVariable< T >::InitInvariants () protected
References ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::ValueRefBase::m_local_candidate_invariant, ValueRef::ValueRefBase::m_root_candidate_invariant, ValueRef::ValueRefBase::m_source_invariant, ValueRef::ComplexVariable< T >::m_string_ref1, ValueRef::ComplexVariable< T >::m_string_ref2, and ValueRef::ValueRefBase::m_target_invariant.
Referenced by ValueRef::ComplexVariable< T >::ComplexVariable().
IntRef1()
template<typename T > const ValueRef< int > * ValueRef::ComplexVariable< T >::IntRef1 () const
References ValueRef::ComplexVariable< T >::m_int_ref1.
IntRef2()
template<typename T > const ValueRef< int > * ValueRef::ComplexVariable< T >::IntRef2 () const
References ValueRef::ComplexVariable< T >::m_int_ref2.
IntRef3()
template<typename T > const ValueRef< int > * ValueRef::ComplexVariable< T >::IntRef3 () const
References ValueRef::ComplexVariable< T >::m_int_ref3.
operator==()
template<typename T > bool ValueRef::ComplexVariable< T >::operator== (const ValueRef< T > & rhs) const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::Variable< T >::m_property_name, ValueRef::Variable< T >::m_return_immediate_value, ValueRef::ComplexVariable< T >::m_string_ref1, and ValueRef::ComplexVariable< T >::m_string_ref2.
SetTopLevelContent()
template<typename T > void ValueRef::ComplexVariable< T >::SetTopLevelContent (const std::string & content_name) override virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::ComplexVariable< T >::m_int_ref1, ValueRef::ComplexVariable< T >::m_int_ref2, ValueRef::ComplexVariable< T >::m_int_ref3, ValueRef::ComplexVariable< T >::m_string_ref1, and ValueRef::ComplexVariable< T >::m_string_ref2.
StringRef1()
template<typename T > const ValueRef< std::string > * ValueRef::ComplexVariable< T >::StringRef1 () const
References ValueRef::ComplexVariable< T >::m_string_ref1.
StringRef2()
template<typename T > const ValueRef< std::string > * ValueRef::ComplexVariable< T >::StringRef2 () const
References ValueRef::ComplexVariable< T >::m_string_ref2.
Member Data Documentation
m_int_ref1
template<typename T> std::unique_ptr<ValueRef<int> > ValueRef::ComplexVariable< T >::m_int_ref1 protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::InitInvariants(), ValueRef::ComplexVariable< T >::IntRef1(), ValueRef::ComplexVariable< T >::operator==(), and ValueRef::ComplexVariable< T >::SetTopLevelContent().
m_int_ref2
template<typename T> std::unique_ptr<ValueRef<int> > ValueRef::ComplexVariable< T >::m_int_ref2 protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::InitInvariants(), ValueRef::ComplexVariable< T >::IntRef2(), ValueRef::ComplexVariable< T >::operator==(), and ValueRef::ComplexVariable< T >::SetTopLevelContent().
m_int_ref3
template<typename T> std::unique_ptr<ValueRef<int> > ValueRef::ComplexVariable< T >::m_int_ref3 protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::InitInvariants(), ValueRef::ComplexVariable< T >::IntRef3(), ValueRef::ComplexVariable< T >::operator==(), and ValueRef::ComplexVariable< T >::SetTopLevelContent().
m_string_ref1
template<typename T> std::unique_ptr<ValueRef<std::string> > ValueRef::ComplexVariable< T >::m_string_ref1 protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::InitInvariants(), ValueRef::ComplexVariable< T >::operator==(), ValueRef::ComplexVariable< T >::SetTopLevelContent(), and ValueRef::ComplexVariable< T >::StringRef1().
m_string_ref2
template<typename T> std::unique_ptr<ValueRef<std::string> > ValueRef::ComplexVariable< T >::m_string_ref2 protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::ComplexVariable< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::InitInvariants(), ValueRef::ComplexVariable< T >::operator==(), ValueRef::ComplexVariable< T >::SetTopLevelContent(), and ValueRef::ComplexVariable< T >::StringRef2().
The documentation for this struct was generated from the following file:
ValueRefs.h