FreeOrion: InfluenceQueue Struct Reference
InfluenceQueue Struct Reference
#include <InfluenceQueue.h>
Classes
struct Element
The type of a single element in the Influence queue.
Public Types
typedef QueueType::const_iterator const_iterator
The const InfluenceQueue iterator type.
typedef QueueType::iterator iterator
The InfluenceQueue iterator type.
typedef std::deque< Element > QueueType
Public Member Functions
Structors
InfluenceQueue (int empire_id)
Accessors
bool InQueue (const std::string &name) const
Returns true iff name influence project is in this queue.
int ProjectsInProgress () const
Returns the number of Influence projects currently (perhaps partially) funded.
float TotalIPsSpent () const
Returns the number of IPs currently spent on the projects in this queue.
int EmpireID () const
Returns true iff name influence project is in this queue.
float AllocatedStockpileIP () const
Returns amount of stockpile IP allocated to Influence queue elements.
float ExpectedNewStockpileAmount () const
Returns the value expected for the Influence Stockpile for the next turn, based on the current InfluenceQueue allocations.
bool empty () const
Returns true iff name influence project is in this queue.
unsigned int size () const
Returns true iff name influence project is in this queue.
const_iterator begin () const
Returns true iff name influence project is in this queue.
const_iterator end () const
Returns true iff name influence project is in this queue.
const_iterator find (const std::string &item_name) const
Returns true iff name influence project is in this queue.
const Element & operator[] (int i) const
Returns true iff name influence project is in this queue.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_empire_id = ALL_EMPIRES
float m_expected_new_stockpile_amount = 0.0f
int m_projects_in_progress = 0
QueueType m_queue
float m_total_IPs_spent = 0.0f
Friends
class boost::serialization::access
Mutators
boost::signals2::signal< void()> InfluenceQueueChangedSignal
Recalculates the PPs spent on and number of turns left for each project in the queue.
void Update ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
void push_back (const Element &element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void insert (iterator it, const Element &element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void erase (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator erase (iterator it)
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator begin ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator end ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator find (const std::string &item_name)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Element & operator[] (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void clear ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Member Typedef Documentation
const_iterator
typedef QueueType::const_iterator InfluenceQueue::const_iterator
The const InfluenceQueue iterator type.
Dereference yields a Element.
iterator
typedef QueueType::iterator InfluenceQueue::iterator
The InfluenceQueue iterator type.
Dereference yields a Element.
QueueType
typedef std::deque<Element> InfluenceQueue::QueueType
Constructor & Destructor Documentation
InfluenceQueue()
InfluenceQueue::InfluenceQueue (int empire_id) inline explicit
Member Function Documentation
AllocatedStockpileIP()
float InfluenceQueue::AllocatedStockpileIP () const
Returns amount of stockpile IP allocated to Influence queue elements.
Referenced by MapWnd::RefreshInfluenceResourceIndicator(), and FreeOrionPython::WrapEmpire().
begin() [1/2]
InfluenceQueue::const_iterator InfluenceQueue::begin () const
Returns true iff name influence project is in this queue.
References m_queue.
Referenced by erase(), and find().
begin() [2/2]
InfluenceQueue::iterator InfluenceQueue::begin ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
clear()
void InfluenceQueue::clear ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References InfluenceQueueChangedSignal, m_projects_in_progress, and m_queue.
Referenced by Empire::Eliminate().
EmpireID()
int InfluenceQueue::EmpireID () const inline
Returns true iff name influence project is in this queue.
Referenced by FreeOrionPython::WrapEmpire().
empty()
bool InfluenceQueue::empty () const
Returns true iff name influence project is in this queue.
References m_queue.
Referenced by FreeOrionPython::WrapEmpire().
end() [1/2]
InfluenceQueue::const_iterator InfluenceQueue::end () const
Returns true iff name influence project is in this queue.
References m_queue.
Referenced by erase(), and find().
end() [2/2]
InfluenceQueue::iterator InfluenceQueue::end ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
erase() [1/2]
void InfluenceQueue::erase (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References begin(), m_queue, and size().
erase() [2/2]
InfluenceQueue::iterator InfluenceQueue::erase (iterator it)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References end(), and m_queue.
ExpectedNewStockpileAmount()
float InfluenceQueue::ExpectedNewStockpileAmount () const inline
Returns the value expected for the Influence Stockpile for the next turn, based on the current InfluenceQueue allocations.
References anonymous_namespace{XMLDoc.cpp}::element, and anonymous_namespace{EncyclopediaParser.cpp}::insert.
Referenced by Empire::CheckInfluenceProgress(), MapWnd::RefreshInfluenceResourceIndicator(), and FreeOrionPython::WrapEmpire().
find() [1/2]
InfluenceQueue::const_iterator InfluenceQueue::find (const std::string & item_name) const
Returns true iff name influence project is in this queue.
References begin(), and end().
find() [2/2]
InfluenceQueue::iterator InfluenceQueue::find (const std::string & item_name)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References begin(), and end().
InQueue()
bool InfluenceQueue::InQueue (const std::string & name) const
Returns true iff name influence project is in this queue.
References m_queue, and InfluenceQueue::Element::name.
Referenced by FreeOrionPython::WrapEmpire().
insert()
void InfluenceQueue::insert (iterator it, const Element & element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
operator[]() [1/2]
const InfluenceQueue::Element & InfluenceQueue::operator[] (int i) const
Returns true iff name influence project is in this queue.
References m_queue.
operator[]() [2/2]
InfluenceQueue::Element & InfluenceQueue::operator[] (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
ProjectsInProgress()
int InfluenceQueue::ProjectsInProgress () const
Returns the number of Influence projects currently (perhaps partially) funded.
References m_projects_in_progress.
push_back()
void InfluenceQueue::push_back (const Element & element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
serialize()
template<class Archive > template void InfluenceQueue::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References ResearchQueue::m_empire_id, ResearchQueue::m_projects_in_progress, and ResearchQueue::m_queue.
size()
unsigned int InfluenceQueue::size () const
Returns true iff name influence project is in this queue.
References m_queue.
Referenced by erase(), and FreeOrionPython::WrapEmpire().
TotalIPsSpent()
float InfluenceQueue::TotalIPsSpent () const
Returns the number of IPs currently spent on the projects in this queue.
References m_total_IPs_spent.
Referenced by Empire::CheckInfluenceProgress(), MapWnd::RefreshInfluenceResourceIndicator(), and FreeOrionPython::WrapEmpire().
Update()
void InfluenceQueue::Update ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
References CurrentTurn(), DebugLogger, ErrorLogger, GetEmpire(), GetPolicy(), InfluenceQueueChangedSignal, m_empire_id, m_expected_new_stockpile_amount, m_projects_in_progress, m_total_IPs_spent, RE_INFLUENCE, Empire::ResourceOutput(), Empire::ResourceStockpile(), and Empire::TurnsPoliciesAdopted().
Referenced by Empire::UpdateInfluenceSpending().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
InfluenceQueueChangedSignal
boost::signals2::signal<void ()> InfluenceQueue::InfluenceQueueChangedSignal mutable
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckInfluenceProgress() will actually spend PP, remove items from queue and create them in the universe.
Referenced by clear(), and Update().
m_empire_id
int InfluenceQueue::m_empire_id = ALL_EMPIRES private
Referenced by Update().
m_expected_new_stockpile_amount
float InfluenceQueue::m_expected_new_stockpile_amount = 0.0f private
Referenced by Update().
m_projects_in_progress
int InfluenceQueue::m_projects_in_progress = 0 private
Referenced by clear(), ProjectsInProgress(), and Update().
m_queue
QueueType InfluenceQueue::m_queue private
Referenced by begin(), clear(), empty(), end(), erase(), InQueue(), insert(), operator[](), push_back(), and size().
m_total_IPs_spent
float InfluenceQueue::m_total_IPs_spent = 0.0f private
Referenced by TotalIPsSpent(), and Update().
The documentation for this struct was generated from the following files:
InfluenceQueue.h
InfluenceQueue.cpp
SerializeEmpire.cpp