FreeOrion: Condition::All Struct Reference
Condition::All Struct Reference final
Matches all objects.
#include <Condition.h>
Public Member Functions
All ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all objects.
Constructor & Destructor Documentation
All()
Condition::All::All () inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Member Function Documentation
Description()
std::string Condition::All::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString().
Dump()
std::string Condition::All::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
Eval()
void Condition::All::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::NON_MATCHES.
GetCheckSum()
unsigned int Condition::All::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
operator==()
bool Condition::All::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::operator==().
RootCandidateInvariant()
bool Condition::All::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::All::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::All::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::All::SourceInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
TargetInvariant()
bool Condition::All::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp