FreeOrion: CombatInfo Struct Reference
CombatInfo Struct Reference
Contains information about the state of a combat before or after the combat occurs.
#include <CombatSystem.h>
Public Member Functions
Structors
CombatInfo ()=default
ctor taking system id where combat occurs and game turn on which combat occurs
CombatInfo (int system_id_, int turn_)
ctor taking system id where combat occurs and game turn on which combat occurs
Accessors
std::shared_ptr< const System > GetSystem () const
Returns System object in this CombatInfo's objects if one exists with id system_id.
Mutators
int turn = INVALID_GAME_TURN
main game turn
int system_id = INVALID_OBJECT_ID
ID of system where combat is occurring (could be INVALID_OBJECT_ID ?)
std::set< int > empire_ids
IDs of empires involved in combat.
ObjectMap objects
actual state of objects relevant to combat
std::set< int > damaged_object_ids
ids of objects damaged during this battle
std::set< int > destroyed_object_ids
ids of objects destroyed during this battle
std::map< int, std::set< int > > destroyed_object_knowers
indexed by empire ID, the set of ids of objects the empire knows were destroyed during the combat
Universe::EmpireObjectVisibilityMap empire_object_visibility
indexed by empire id and object id, the visibility level the empire has of each object. may be increased during battle
std::vector< CombatEventPtr > combat_events
list of combat attack events that occur in combat
class boost::serialization::access
main game turn
std::shared_ptr< System > GetSystem ()
Returns System object in this CombatInfo's objects if one exists with id system_id.
float GetMonsterDetection () const
main game turn
void GetEmpireIdsToSerialize (std::set< int > &filtered_empire_ids, int encoding_empire) const
main game turn
void GetObjectsToSerialize (ObjectMap &filtered_objects, int encoding_empire) const
main game turn
void GetDamagedObjectsToSerialize (std::set< int > &filtered_damaged_objects, int encoding_empire) const
main game turn
void GetDestroyedObjectsToSerialize (std::set< int > &filtered_destroyed_objects, int encoding_empire) const
main game turn
void GetDestroyedObjectKnowersToSerialize (std::map< int, std::set< int >> &filtered_destroyed_object_knowers, int encoding_empire) const
main game turn
void GetEmpireObjectVisibilityToSerialize (Universe::EmpireObjectVisibilityMap &filtered_empire_object_visibility, int encoding_empire) const
main game turn
void GetCombatEventsToSerialize (std::vector< CombatEventPtr > &filtered_combat_events, int encoding_empire) const
main game turn
void InitializeObjectVisibility ()
main game turn
template<class Archive >
void save (Archive &ar, const unsigned int version) const
main game turn
template<class Archive >
void load (Archive &ar, const unsigned int version)
main game turn
Detailed Description
Contains information about the state of a combat before or after the combat occurs.
Constructor & Destructor Documentation
CombatInfo() [1/2]
CombatInfo::CombatInfo () default
ctor taking system id where combat occurs and game turn on which combat occurs
CombatInfo() [2/2]
CombatInfo::CombatInfo (int system_id_, int turn_)
ctor taking system id where combat occurs and game turn on which combat occurs
References empire_ids, ErrorLogger, ObjectMap::FindObjects(), GetSystem(), InitializeObjectVisibility(), ObjectMap::Insert(), METER_POPULATION, objects, Objects(), and system_id.
Member Function Documentation
GetCombatEventsToSerialize()
void CombatInfo::GetCombatEventsToSerialize (std::vector< CombatEventPtr > & filtered_combat_events, int encoding_empire) const private
main game turn
References combat_events.
Referenced by save().
GetDamagedObjectsToSerialize()
void CombatInfo::GetDamagedObjectsToSerialize (std::set< int > & filtered_damaged_objects, int encoding_empire) const private
main game turn
References ALL_EMPIRES, and damaged_object_ids.
Referenced by save().
GetDestroyedObjectKnowersToSerialize()
void CombatInfo::GetDestroyedObjectKnowersToSerialize (std::map< int, std::set< int >> & filtered_destroyed_object_knowers, int encoding_empire) const private
main game turn
References ALL_EMPIRES, and destroyed_object_knowers.
Referenced by save().
GetDestroyedObjectsToSerialize()
void CombatInfo::GetDestroyedObjectsToSerialize (std::set< int > & filtered_destroyed_objects, int encoding_empire) const private
main game turn
References ALL_EMPIRES, and destroyed_object_ids.
Referenced by save().
GetEmpireIdsToSerialize()
void CombatInfo::GetEmpireIdsToSerialize (std::set< int > & filtered_empire_ids, int encoding_empire) const private
main game turn
References ALL_EMPIRES, and empire_ids.
Referenced by save().
GetEmpireObjectVisibilityToSerialize()
void CombatInfo::GetEmpireObjectVisibilityToSerialize (Universe::EmpireObjectVisibilityMap & filtered_empire_object_visibility, int encoding_empire) const private
main game turn
References empire_object_visibility.
Referenced by save().
GetMonsterDetection()
float CombatInfo::GetMonsterDetection () const
main game turn
References ObjectMap::const_begin(), ObjectMap::const_end(), METER_DETECTION, and objects.
Referenced by anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths().
GetObjectsToSerialize()
void CombatInfo::GetObjectsToSerialize (ObjectMap & filtered_objects, int encoding_empire) const private
main game turn
References ALL_EMPIRES, ObjectMap::Clear(), and objects.
Referenced by save().
GetSystem() [1/2]
std::shared_ptr< const System > CombatInfo::GetSystem () const
Returns System object in this CombatInfo's objects if one exists with id system_id.
References ObjectMap::Object(), objects, and system_id.
Referenced by CombatInfo().
GetSystem() [2/2]
std::shared_ptr< System > CombatInfo::GetSystem ()
Returns System object in this CombatInfo's objects if one exists with id system_id.
References ObjectMap::Object(), objects, and system_id.
InitializeObjectVisibility()
void CombatInfo::InitializeObjectVisibility () private
main game turn
References ALL_EMPIRES, DebugLogger, empire_ids, empire_object_visibility, anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths(), GetFleet(), GetGameRules(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), METER_STEALTH, and objects.
Referenced by CombatInfo().
load()
template<class Archive > void CombatInfo::load (Archive & ar, const unsigned int version) private
main game turn
References combat_events, damaged_object_ids, destroyed_object_ids, destroyed_object_knowers, empire_ids, empire_object_visibility, objects, ObjectMap::swap(), system_id, and turn.
save()
template<class Archive > void CombatInfo::save (Archive & ar, const unsigned int version) const private
main game turn
References GetCombatEventsToSerialize(), GetDamagedObjectsToSerialize(), GetDestroyedObjectKnowersToSerialize(), GetDestroyedObjectsToSerialize(), GetEmpireIdsToSerialize(), GetEmpireObjectVisibilityToSerialize(), GetObjectsToSerialize(), GetUniverse(), system_id, and turn.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
main game turn
Member Data Documentation
combat_events
std::vector<CombatEventPtr> CombatInfo::combat_events
list of combat attack events that occur in combat
Referenced by AutoResolveCombat(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GetCombatEventsToSerialize(), and load().
damaged_object_ids
std::set<int> CombatInfo::damaged_object_ids
ids of objects damaged during this battle
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackFighterPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), GetDamagedObjectsToSerialize(), and load().
destroyed_object_ids
std::set<int> CombatInfo::destroyed_object_ids
ids of objects destroyed during this battle
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), CombatLog::CombatLog(), GetDestroyedObjectsToSerialize(), anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasUnlauchedArmedFighters(), load(), and anonymous_namespace{CombatSystem.cpp}::RecoverFighters().
destroyed_object_knowers
std::map<int, std::set<int> > CombatInfo::destroyed_object_knowers
indexed by empire ID, the set of ids of objects the empire knows were destroyed during the combat
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), GetDestroyedObjectKnowersToSerialize(), and load().
empire_ids
std::set<int> CombatInfo::empire_ids
IDs of empires involved in combat.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), CombatInfo(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GetEmpireIdsToSerialize(), anonymous_namespace{CombatSystem.cpp}::GetEmpiresDetectionStrengths(), InitializeObjectVisibility(), load(), and anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects().
empire_object_visibility
Universe::EmpireObjectVisibilityMap CombatInfo::empire_object_visibility
indexed by empire id and object id, the visibility level the empire has of each object. may be increased during battle
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), GetEmpireObjectVisibilityToSerialize(), InitializeObjectVisibility(), load(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), and anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons().
objects
ObjectMap CombatInfo::objects
actual state of objects relevant to combat
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), AutoResolveCombat(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CleanEmpires(), CombatInfo(), CombatLog::CombatLog(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), GetMonsterDetection(), GetObjectsToSerialize(), GetSystem(), anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasUnlauchedArmedFighters(), InitializeObjectVisibility(), load(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackers(), anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), and anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons().
system_id
int CombatInfo::system_id = INVALID_OBJECT_ID
ID of system where combat is occurring (could be INVALID_OBJECT_ID ?)
Referenced by AutoResolveCombat(), CombatInfo(), GetSystem(), load(), and save().
turn
int CombatInfo::turn = INVALID_GAME_TURN
main game turn
Referenced by load(), and save().
The documentation for this struct was generated from the following files:
CombatSystem.h
CombatSystem.cpp