FreeOrion: anonymous_namespace{EmpireStatsParser.cpp}::rules Struct Reference
anonymous_namespace{EmpireStatsParser.cpp}::rules Struct Reference
Public Types
typedef parse::detail::rule< void(std::map< std::string, ValueRef::ValueRefBase< double > * > &) > start_rule
typedef parse::detail::rule< std::pair< std::string, ValueRef::ValueRefBase< double > * >), boost::spirit::qi::locals< std::string > > stat_rule
Public Member Functions
rules ()
Public Attributes
start_rule start
stat_rule stat
Member Typedef Documentation
typedef parse::detail::rule< void (std::map<std::string, ValueRef::ValueRefBase<double>*>&) > anonymous_namespace{EmpireStatsParser.cpp}::rules::start_rule
typedef parse::detail::rule< std::pair<std::string, ValueRef::ValueRefBase<double>*>), boost::spirit::qi::locals<std::string> > anonymous_namespace{EmpireStatsParser.cpp}::rules::stat_rule
Constructor & Destructor Documentation
anonymous_namespace{EmpireStatsParser.cpp}::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::double_value_ref(), anonymous_namespace{BuildingsParser.cpp}::insert, parse::lexer::instance(), parse::detail::label(), parse::report_error, and parse::lexer::string.
Member Data Documentation
start_rule anonymous_namespace{EmpireStatsParser.cpp}::rules::start
stat_rule anonymous_namespace{EmpireStatsParser.cpp}::rules::stat
The documentation for this struct was generated from the following file:
EmpireStatsParser.cpp