FreeOrion: Condition::PlanetSize Struct Reference
Condition::PlanetSize Struct Reference final
Matches all Planet objects that have one of the PlanetSizes in sizes.
#include <Condition.h>
Public Member Functions
PlanetSize (std::vector< std::unique_ptr< ValueRef::ValueRefBase< ::PlanetSize >>> &&sizes)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< std::unique_ptr< ValueRef::ValueRefBase<::PlanetSize > > > m_sizes
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all Planet objects that have one of the PlanetSizes in sizes.
Note that all Building objects which are on matching planets are also matched.
Constructor & Destructor Documentation
PlanetSize()
Condition::PlanetSize::PlanetSize (std::vector< std::unique_ptr< ValueRef::ValueRefBase< ::PlanetSize >>> && sizes)
Member Function Documentation
Description()
std::string Condition::PlanetSize::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References Eval(), FlexibleFormat(), m_sizes, and UserString().
Dump()
std::string Condition::PlanetSize::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_sizes.
Eval()
void Condition::PlanetSize::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_sizes, and RootCandidateInvariant().
Referenced by Description().
GetCheckSum()
unsigned int Condition::PlanetSize::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_sizes, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::PlanetSize::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddBuildingSet(), and anonymous_namespace{Condition.cpp}::AddPlanetSet().
Match()
bool Condition::PlanetSize::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, GetPlanet(), and m_sizes.
operator==()
bool Condition::PlanetSize::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_sizes.
RootCandidateInvariant()
bool Condition::PlanetSize::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_sizes.
Referenced by Eval().
serialize()
template<class Archive > void Condition::PlanetSize::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::PlanetSize::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_sizes.
SourceInvariant()
bool Condition::PlanetSize::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_sizes.
TargetInvariant()
bool Condition::PlanetSize::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_sizes.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_sizes
std::vector<std::unique_ptr<ValueRef::ValueRefBase<::PlanetSize> > > Condition::PlanetSize::m_sizes private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::PlanetSizeSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp