FreeOrion: Condition::ContainedBy Struct Reference
Condition::ContainedBy Struct Reference final
Matches all objects that are contained by an object that matches Condition condition.
#include <Condition.h>
Public Member Functions
ContainedBy (std::unique_ptr< ConditionBase > &&condition)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ConditionBase > m_condition
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all objects that are contained by an object that matches Condition condition.
Container objects are Systems, Planets (which contain Buildings), and Fleets (which contain Ships).
Constructor & Destructor Documentation
ContainedBy()
Condition::ContainedBy::ContainedBy (std::unique_ptr< ConditionBase > && condition) inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Member Function Documentation
Description()
std::string Condition::ContainedBy::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), and UserString().
Dump()
std::string Condition::ContainedBy::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
Eval()
void Condition::ContainedBy::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, anonymous_namespace{CUIWnd.cpp}::dummy, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), INVALID_OBJECT_ID, Condition::MATCHES, Condition::NON_MATCHES, Objects(), and Condition::CreatedOnTurn::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::ContainedBy::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::ContainedBy::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddBuildingSet(), anonymous_namespace{Condition.cpp}::AddFleetSet(), anonymous_namespace{Condition.cpp}::AddPlanetSet(), and anonymous_namespace{Condition.cpp}::AddShipSet().
Match()
bool Condition::ContainedBy::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ObjectMap::find(), INVALID_OBJECT_ID, and Objects().
operator==()
bool Condition::ContainedBy::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER.
RootCandidateInvariant()
bool Condition::ContainedBy::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::ContainedBy::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::ContainedBy::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::ContainedBy::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
TargetInvariant()
bool Condition::ContainedBy::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_condition
std::unique_ptr<ConditionBase> Condition::ContainedBy::m_condition private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp