FreeOrion: anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3 Struct Reference
anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3 Struct Reference
Public Types
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< ValueRef::ValueRefBase< double > *, ValueRef::ValueRefBase< double > *, ValueRef::ValueRefBase< std::string > *, Condition::ComparisonType, Condition::ComparisonType, ValueRef::ValueRefBase< std::string > *, ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< int > * > > double_ref_double_ref_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< ValueRef::ValueRefBase< int > *, ValueRef::ValueRefBase< int > * > > int_ref_int_ref_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< ValueRef::ValueRefBase< int > *, Condition::SortingMethod, ValueRef::ValueRefBase< double > * > > int_ref_sorting_method_double_ref_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< ResourceType, ValueRef::ValueRefBase< double > * > > resource_type_double_ref_rule
Public Member Functions
condition_parser_rules_3 ()
Public Attributes
parse::condition_parser_rule can_add_starlane
int_ref_int_ref_rule created_on_turn
double_ref_double_ref_rule has_special_capacity
int_ref_int_ref_rule number
int_ref_sorting_method_double_ref_rule number_of
int_ref_sorting_method_double_ref_rule number_of1
int_ref_sorting_method_double_ref_rule number_of2
resource_type_double_ref_rule owner_stockpile
parse::condition_parser_rule random
int_ref_int_ref_rule resource_supply_connected
parse::condition_parser_rule start
int_ref_int_ref_rule turn
double_ref_double_ref_rule value_test_1
double_ref_double_ref_rule value_test_2
double_ref_double_ref_rule value_test_3
double_ref_double_ref_rule value_test_4
double_ref_double_ref_rule value_test_5
double_ref_double_ref_rule value_test_6
double_ref_double_ref_rule within_distance
int_ref_int_ref_rule within_starlane_jumps
Member Typedef Documentation
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<std::string>*, Condition::ComparisonType, Condition::ComparisonType, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>* > > anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::double_ref_double_ref_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>* > > anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::int_ref_int_ref_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< ValueRef::ValueRefBase<int>*, Condition::SortingMethod, ValueRef::ValueRefBase<double>* > > anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::int_ref_sorting_method_double_ref_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals< ResourceType, ValueRef::ValueRefBase<double>* > > anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::resource_type_double_ref_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, debug, parse::double_value_ref(), Condition::EQUAL, parse::flexible_int_value_ref(), Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, parse::lexer::instance(), parse::int_value_ref(), parse::detail::label(), Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, Condition::NOT_EQUAL, Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, and parse::string_value_ref().
Member Data Documentation
parse::condition_parser_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::can_add_starlane
int_ref_int_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::created_on_turn
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::has_special_capacity
int_ref_int_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::number
int_ref_sorting_method_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::number_of
int_ref_sorting_method_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::number_of1
int_ref_sorting_method_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::number_of2
resource_type_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::owner_stockpile
parse::condition_parser_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::random
int_ref_int_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::resource_supply_connected
parse::condition_parser_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::start
int_ref_int_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::turn
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_1
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_2
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_3
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_4
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_5
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::value_test_6
double_ref_double_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::within_distance
int_ref_int_ref_rule anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::within_starlane_jumps
The documentation for this struct was generated from the following file:
ConditionParser3.cpp