FreeOrion: anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString Struct Reference
anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString Struct Reference
Public Member Functions
StartNewFormatterFromUserString (boost::format &formatter_)
void operator() (const char *first, const char *last) const
Public Attributes
boost::format & formatter
Constructor & Destructor Documentation
StartNewFormatterFromUserString()
anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::StartNewFormatterFromUserString (boost::format & formatter_) inline
Member Function Documentation
operator()()
void anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::operator() (const char * first, const char * last) const inline
References FlexibleFormat(), UserString(), and UserStringExists().
Member Data Documentation
formatter
boost::format& anonymous_namespace{ChatWnd.cpp}::StartNewFormatterFromUserString::formatter
The documentation for this struct was generated from the following file:
ChatWnd.cpp