FreeOrion: OptionsDB::OptionSection Struct Reference
OptionsDB::OptionSection Struct Reference
#include <OptionsDB.h>
Public Member Functions
OptionSection ()
OptionSection (const std::string &name_, const std::string &description_, std::function< bool(const std::string &)> option_predicate_)
Public Attributes
std::string description
std::string name
std::function< bool(const std::string &)> option_predicate = nullptr
Constructor & Destructor Documentation
OptionsDB::OptionSection::OptionSection () default
Referenced by OptionsDB::AddSection(), and OptionsDB::Option::ValueIsDefault().
OptionsDB::OptionSection::OptionSection (const std::string & name_, const std::string & description_, std::function< bool(const std::string &)> option_predicate_)
References OptionsDB::s_options_db.
Member Data Documentation
std::string OptionsDB::OptionSection::description
std::string OptionsDB::OptionSection::name
Referenced by OptionsDB::GetXML().
std::function<bool (const std::string&)> OptionsDB::OptionSection::option_predicate = nullptr
Referenced by OptionsDB::AddSection().
The documentation for this struct was generated from the following files:
OptionsDB.h
OptionsDB.cpp