FreeOrion: ValueRef::ValueRefBase< T > Struct Template Reference
ValueRef::ValueRefBase< T > Struct Template Reference abstract
#include <ValueRefFwd.h>
Public Member Functions
virtual ~ValueRefBase ()
virtual bool ConstantExpr () const
virtual std::string Description () const =0
virtual std::string Dump () const =0
T Eval () const
virtual T Eval (const ScriptingContext &context) const =0
virtual bool LocalCandidateInvariant () const
bool operator!= (const ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRefBase< T > &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<class T>
struct ValueRef::ValueRefBase< T >
The base class for all ValueRef classes. This class provides the public interface for a ValueRef expression tree.
Constructor & Destructor Documentation
template<class T> virtual ValueRef::ValueRefBase< T >::~ValueRefBase () inline virtual
Member Function Documentation
template<class T> virtual bool ValueRef::ValueRefBase< T >::ConstantExpr () const inline virtual
Reimplemented in ValueRef::Operation< T >, and ValueRef::Constant< T >.
Referenced by Condition::EmpireAffiliation::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::Enqueued::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::MeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::OwnerHasTech::Description(), Condition::EmpireAffiliation::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), PartType::ProductionCost(), HullType::ProductionCost(), PartType::ProductionTime(), HullType::ProductionTime(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), Tech::ResearchCost(), Tech::ResearchTime(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
template<class T> virtual std::string ValueRef::ValueRefBase< T >::Description () const pure virtual
Implemented in ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::StaticCast< FromType, ToType >::Description(), Condition::EmpireAffiliation::Description(), ValueRef::StringCast< FromType >::Description(), ValueRef::UserStringLookup< FromType >::Description(), ValueRef::NameLookup::Description(), Condition::HasSpecial::Description(), Condition::HasTag::Description(), Condition::Enqueued::Description(), Condition::DesignHasHull::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::PredefinedShipDesign::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), and Condition::OwnerHasTech::Description().
template<class T> virtual std::string ValueRef::ValueRefBase< T >::Dump () const pure virtual
Returns a text description of this type of special.
Implemented in ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::StaticCast< FromType, ToType >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::ComplexVariable< T >, ValueRef::Constant< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by Tech::Dump(), Effect::SetMeter::Dump(), Effect::SetShipPartMeter::Dump(), Effect::SetEmpireMeter::Dump(), Effect::SetEmpireStockpile::Dump(), Effect::SetEmpireCapital::Dump(), Effect::SetPlanetType::Dump(), ValueRef::StaticCast< FromType, ToType >::Dump(), Effect::SetPlanetSize::Dump(), Condition::EmpireAffiliation::Dump(), ValueRef::StringCast< FromType >::Dump(), Effect::SetSpecies::Dump(), Effect::SetOwner::Dump(), ValueRef::UserStringLookup< FromType >::Dump(), Effect::SetSpeciesEmpireOpinion::Dump(), ValueRef::NameLookup::Dump(), Effect::CreatePlanet::Dump(), Effect::CreateBuilding::Dump(), Effect::CreateShip::Dump(), Effect::CreateField::Dump(), Effect::CreateSystem::Dump(), Effect::AddSpecial::Dump(), Effect::RemoveSpecial::Dump(), Condition::HasSpecial::Dump(), Effect::SetStarType::Dump(), Condition::HasTag::Dump(), Effect::MoveInOrbit::Dump(), Effect::MoveTowards::Dump(), Effect::SetEmpireTechProgress::Dump(), Effect::GiveEmpireTech::Dump(), Effect::GenerateSitRepMessage::Dump(), Effect::SetOverlayTexture::Dump(), Effect::SetVisibility::Dump(), Condition::Enqueued::Dump(), Condition::DesignHasHull::Dump(), Condition::DesignHasPart::Dump(), Condition::DesignHasPartClass::Dump(), Condition::PredefinedShipDesign::Dump(), Condition::NumberedShipDesign::Dump(), Condition::ProducedByEmpire::Dump(), Condition::MeterValue::Dump(), Condition::ShipPartMeterValue::Dump(), Condition::EmpireMeterValue::Dump(), Condition::EmpireStockpileValue::Dump(), Condition::OwnerHasTech::Dump(), Condition::OwnerHasBuildingTypeAvailable::Dump(), Condition::OwnerHasShipDesignAvailable::Dump(), Condition::OwnerHasShipPartAvailable::Dump(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag().
template<class T> T ValueRef::ValueRefBase< T >::Eval () const inline
Evaluates the expression tree with an empty context. Useful for evaluating expressions that do not depend on context.
Referenced by Condition::EmpireAffiliation::Description(), Condition::Enqueued::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::NumberedShipDesign::Description(), Condition::ProducedByEmpire::Description(), Condition::MeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), ValueRef::Variable< T >::Dump(), ValueRef::Statistic< T >::Eval(), ValueRef::StaticCast< FromType, ToType >::Eval(), Condition::EmpireAffiliation::Eval(), ValueRef::StringCast< FromType >::Eval(), ValueRef::UserStringLookup< FromType >::Eval(), ValueRef::NameLookup::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::Enqueued::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::OwnerHasShipPartAvailable::Eval(), ValueRef::Operation< T >::EvalImpl(), Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), Effect::SetEmpireMeter::Execute(), Effect::SetEmpireStockpile::Execute(), Effect::SetEmpireCapital::Execute(), Effect::SetPlanetType::Execute(), Effect::SetPlanetSize::Execute(), Effect::SetSpecies::Execute(), Effect::SetOwner::Execute(), Effect::SetSpeciesEmpireOpinion::Execute(), Effect::SetSpeciesSpeciesOpinion::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), Effect::CreateSystem::Execute(), Effect::AddSpecial::Execute(), Effect::RemoveSpecial::Execute(), Effect::SetStarType::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), Effect::SetEmpireTechProgress::Execute(), Effect::GiveEmpireTech::Execute(), Effect::GenerateSitRepMessage::Execute(), Effect::SetOverlayTexture::Execute(), Effect::SetVisibility::Execute(), Condition::EmpireAffiliation::Match(), Condition::HasSpecial::Match(), Condition::HasTag::Match(), Condition::Enqueued::Match(), Condition::DesignHasHull::Match(), Condition::DesignHasPart::Match(), Condition::DesignHasPartClass::Match(), Condition::PredefinedShipDesign::Match(), Condition::NumberedShipDesign::Match(), Condition::ProducedByEmpire::Match(), Condition::MeterValue::Match(), Condition::ShipPartMeterValue::Match(), Condition::EmpireMeterValue::Match(), Condition::EmpireStockpileValue::Match(), Condition::OwnerHasTech::Match(), Condition::OwnerHasBuildingTypeAvailable::Match(), Condition::OwnerHasShipDesignAvailable::Match(), Condition::OwnerHasShipPartAvailable::Match(), PartType::ProductionCost(), HullType::ProductionCost(), PartType::ProductionTime(), HullType::ProductionTime(), ObjectPanel::RefreshCache(), Tech::ResearchCost(), Tech::ResearchTime(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), ValueRef::Constant< T >::SetTopLevelContent(), ValueRef::ComplexVariable< T >::SetTopLevelContent(), Condition::anonymous_namespace{Condition.cpp}::TransferSortedObjects(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and Universe::UpdateStatRecords().
template<class T> virtual T ValueRef::ValueRefBase< T >::Eval (const ScriptingContext & context) const pure virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implemented in ValueRef::UserStringLookup< FromType >, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::UserStringLookup< FromType >, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Constant< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Variable< T >, ValueRef::Operation< T >, ValueRef::Variable< T >, ValueRef::NameLookup, ValueRef::Variable< T >, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::Constant< T >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
template<class T> virtual bool ValueRef::ValueRefBase< T >::LocalCandidateInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by Condition::EmpireAffiliation::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::Enqueued::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::OwnerHasShipPartAvailable::Eval(), ValueRef::ComplexVariable< T >::LocalCandidateInvariant(), ValueRef::StaticCast< FromType, ToType >::LocalCandidateInvariant(), ValueRef::StringCast< FromType >::LocalCandidateInvariant(), ValueRef::UserStringLookup< FromType >::LocalCandidateInvariant(), ValueRef::NameLookup::LocalCandidateInvariant(), and HullType::ProductionCostTimeLocationInvariant().
template<class T> bool ValueRef::ValueRefBase< T >::operator!= (const ValueRefBase< T > & rhs) const inline
template<class T> bool ValueRef::ValueRefBase< T >::operator== (const ValueRefBase< T > & rhs) const virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, and ValueRef::Constant< T >.
template<class T> virtual bool ValueRef::ValueRefBase< T >::RootCandidateInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by ValueRef::ComplexVariable< T >::RootCandidateInvariant(), ValueRef::StaticCast< FromType, ToType >::RootCandidateInvariant(), Condition::EmpireAffiliation::RootCandidateInvariant(), ValueRef::StringCast< FromType >::RootCandidateInvariant(), ValueRef::UserStringLookup< FromType >::RootCandidateInvariant(), ValueRef::NameLookup::RootCandidateInvariant(), Condition::HasSpecial::RootCandidateInvariant(), Condition::HasTag::RootCandidateInvariant(), Condition::Enqueued::RootCandidateInvariant(), Condition::DesignHasHull::RootCandidateInvariant(), Condition::DesignHasPart::RootCandidateInvariant(), Condition::DesignHasPartClass::RootCandidateInvariant(), Condition::PredefinedShipDesign::RootCandidateInvariant(), Condition::NumberedShipDesign::RootCandidateInvariant(), Condition::ProducedByEmpire::RootCandidateInvariant(), Condition::MeterValue::RootCandidateInvariant(), Condition::ShipPartMeterValue::RootCandidateInvariant(), Condition::EmpireMeterValue::RootCandidateInvariant(), Condition::EmpireStockpileValue::RootCandidateInvariant(), Condition::OwnerHasTech::RootCandidateInvariant(), Condition::OwnerHasBuildingTypeAvailable::RootCandidateInvariant(), Condition::OwnerHasShipDesignAvailable::RootCandidateInvariant(), and Condition::OwnerHasShipPartAvailable::RootCandidateInvariant().
template<class T > template<class Archive > void ValueRef::ValueRefBase< T >::serialize (Archive & ar, const unsigned int version) private
template<class T> virtual void ValueRef::ValueRefBase< T >::SetTopLevelContent (const std::string & content_name) inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, and ValueRef::Constant< T >.
Referenced by Tech::Init(), Effect::SetMeter::SetTopLevelContent(), Effect::SetShipPartMeter::SetTopLevelContent(), Effect::SetEmpireMeter::SetTopLevelContent(), Effect::SetEmpireStockpile::SetTopLevelContent(), ValueRef::ComplexVariable< T >::SetTopLevelContent(), Effect::SetEmpireCapital::SetTopLevelContent(), Effect::SetPlanetType::SetTopLevelContent(), ValueRef::StaticCast< FromType, ToType >::SetTopLevelContent(), Effect::SetPlanetSize::SetTopLevelContent(), Condition::EmpireAffiliation::SetTopLevelContent(), ValueRef::StringCast< FromType >::SetTopLevelContent(), Effect::SetSpecies::SetTopLevelContent(), Effect::SetOwner::SetTopLevelContent(), ValueRef::UserStringLookup< FromType >::SetTopLevelContent(), Effect::SetSpeciesEmpireOpinion::SetTopLevelContent(), ValueRef::NameLookup::SetTopLevelContent(), Effect::SetSpeciesSpeciesOpinion::SetTopLevelContent(), Effect::CreatePlanet::SetTopLevelContent(), Effect::CreateBuilding::SetTopLevelContent(), Effect::CreateShip::SetTopLevelContent(), Effect::CreateField::SetTopLevelContent(), Effect::CreateSystem::SetTopLevelContent(), Effect::AddSpecial::SetTopLevelContent(), Effect::RemoveSpecial::SetTopLevelContent(), Condition::HasSpecial::SetTopLevelContent(), Effect::SetStarType::SetTopLevelContent(), Condition::HasTag::SetTopLevelContent(), Effect::MoveInOrbit::SetTopLevelContent(), Effect::MoveTowards::SetTopLevelContent(), Effect::SetEmpireTechProgress::SetTopLevelContent(), Effect::GiveEmpireTech::SetTopLevelContent(), Effect::GenerateSitRepMessage::SetTopLevelContent(), Effect::SetOverlayTexture::SetTopLevelContent(), Effect::SetVisibility::SetTopLevelContent(), Condition::Enqueued::SetTopLevelContent(), Condition::DesignHasHull::SetTopLevelContent(), Condition::DesignHasPart::SetTopLevelContent(), Condition::DesignHasPartClass::SetTopLevelContent(), Condition::PredefinedShipDesign::SetTopLevelContent(), Condition::NumberedShipDesign::SetTopLevelContent(), Condition::ProducedByEmpire::SetTopLevelContent(), Condition::MeterValue::SetTopLevelContent(), Condition::ShipPartMeterValue::SetTopLevelContent(), Condition::EmpireMeterValue::SetTopLevelContent(), Condition::EmpireStockpileValue::SetTopLevelContent(), Condition::OwnerHasTech::SetTopLevelContent(), Condition::OwnerHasBuildingTypeAvailable::SetTopLevelContent(), Condition::OwnerHasShipDesignAvailable::SetTopLevelContent(), and Condition::OwnerHasShipPartAvailable::SetTopLevelContent().
template<class T> virtual bool ValueRef::ValueRefBase< T >::SimpleIncrement () const inline virtual
Reimplemented in ValueRef::Operation< T >.
Referenced by Effect::SetMeter::Execute(), and Effect::SetShipPartMeter::Execute().
template<class T> virtual bool ValueRef::ValueRefBase< T >::SourceInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by PartType::ProductionCost(), HullType::ProductionCost(), PartType::ProductionTime(), HullType::ProductionTime(), Tech::ResearchCost(), Tech::ResearchTime(), ValueRef::ComplexVariable< T >::SourceInvariant(), ValueRef::StaticCast< FromType, ToType >::SourceInvariant(), Condition::EmpireAffiliation::SourceInvariant(), ValueRef::StringCast< FromType >::SourceInvariant(), ValueRef::UserStringLookup< FromType >::SourceInvariant(), ValueRef::NameLookup::SourceInvariant(), Condition::HasSpecial::SourceInvariant(), Condition::HasTag::SourceInvariant(), Condition::Enqueued::SourceInvariant(), Condition::DesignHasHull::SourceInvariant(), Condition::DesignHasPart::SourceInvariant(), Condition::DesignHasPartClass::SourceInvariant(), Condition::PredefinedShipDesign::SourceInvariant(), Condition::NumberedShipDesign::SourceInvariant(), Condition::ProducedByEmpire::SourceInvariant(), Condition::MeterValue::SourceInvariant(), Condition::ShipPartMeterValue::SourceInvariant(), Condition::EmpireMeterValue::SourceInvariant(), Condition::EmpireStockpileValue::SourceInvariant(), Condition::OwnerHasTech::SourceInvariant(), Condition::OwnerHasBuildingTypeAvailable::SourceInvariant(), Condition::OwnerHasShipDesignAvailable::SourceInvariant(), Condition::OwnerHasShipPartAvailable::SourceInvariant(), and Universe::UpdateStatRecords().
template<class T> virtual bool ValueRef::ValueRefBase< T >::TargetInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), PartType::ProductionCostTimeLocationInvariant(), ValueRef::ComplexVariable< T >::TargetInvariant(), ValueRef::StaticCast< FromType, ToType >::TargetInvariant(), Condition::EmpireAffiliation::TargetInvariant(), ValueRef::StringCast< FromType >::TargetInvariant(), ValueRef::UserStringLookup< FromType >::TargetInvariant(), ValueRef::NameLookup::TargetInvariant(), Condition::HasSpecial::TargetInvariant(), Condition::HasTag::TargetInvariant(), Condition::Enqueued::TargetInvariant(), Condition::DesignHasHull::TargetInvariant(), Condition::DesignHasPart::TargetInvariant(), Condition::DesignHasPartClass::TargetInvariant(), Condition::PredefinedShipDesign::TargetInvariant(), Condition::NumberedShipDesign::TargetInvariant(), Condition::ProducedByEmpire::TargetInvariant(), Condition::MeterValue::TargetInvariant(), Condition::ShipPartMeterValue::TargetInvariant(), Condition::EmpireMeterValue::TargetInvariant(), Condition::EmpireStockpileValue::TargetInvariant(), Condition::OwnerHasTech::TargetInvariant(), Condition::OwnerHasBuildingTypeAvailable::TargetInvariant(), Condition::OwnerHasShipDesignAvailable::TargetInvariant(), and Condition::OwnerHasShipPartAvailable::TargetInvariant().
Friends And Related Function Documentation
template<class T> friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Effect.h
ValueRef.h