FreeOrion: WaitingForMPHostAck Struct Reference
WaitingForMPHostAck Struct Reference
#include <HumanClientFSM.h>
Public Types
typedef boost::statechart::simple_state< WaitingForMPHostAck, HumanClientFSM > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< HostMPGame >, boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< Error >, boost::statechart::custom_reaction< CheckSum > > reactions
Public Member Functions
WaitingForMPHostAck ()
~WaitingForMPHostAck ()
boost::statechart::result react (const HostMPGame &a)
boost::statechart::result react (const Disconnection &d)
boost::statechart::result react (const StartQuittingGame &msg)
boost::statechart::result react (const Error &msg)
boost::statechart::result react (const CheckSum &msg)
Detailed Description
The human client state in which the player has requested to host a multiplayer game and is waiting for the server to acknowledge the request.
Member Typedef Documentation
typedef boost::statechart::simple_state<WaitingForMPHostAck, HumanClientFSM> WaitingForMPHostAck::Base
typedef boost::mpl::list< boost::statechart::custom_reaction<HostMPGame>, boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<Error>, boost::statechart::custom_reaction<CheckSum> > WaitingForMPHostAck::reactions
Constructor & Destructor Documentation
WaitingForMPHostAck::WaitingForMPHostAck ()
References TraceLogger.
WaitingForMPHostAck::~WaitingForMPHostAck ()
References TraceLogger.
Member Function Documentation
boost::statechart::result WaitingForMPHostAck::react (const HostMPGame & a)
References ErrorLogger, and TraceLogger.
boost::statechart::result WaitingForMPHostAck::react (const Disconnection & d)
References ClientUI::MessageBox(), TraceLogger, and UserString().
boost::statechart::result WaitingForMPHostAck::react (const StartQuittingGame & msg)
References TraceLogger, and UserString().
boost::statechart::result WaitingForMPHostAck::react (const Error & msg)
References ErrorLogger, ExtractErrorMessageData(), HumanClientApp::GetClientUI(), ClientUI::GetMessageWnd(), ClientUI::MessageBox(), TraceLogger, and UserString().
boost::statechart::result WaitingForMPHostAck::react (const CheckSum & msg)
References ExtractContentCheckSumMessageData(), InfoLogger, and TraceLogger.
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp