FreeOrion: WaitingForSPGameJoiners Struct Reference
WaitingForSPGameJoiners Struct Reference
The server state in which a new single-player game has been initiated, and the server is waiting for all players to join.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::in_state_reaction< Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection >, sc::custom_reaction< JoinGame >, sc::custom_reaction< CheckStartConditions >, sc::custom_reaction< LoadSaveFileFailed >, sc::custom_reaction< ShutdownServer >, sc::custom_reaction< Error > > reactions
Public Member Functions
WaitingForSPGameJoiners (my_context c)
~WaitingForSPGameJoiners ()
sc::result react (const JoinGame &msg)
sc::result react (const CheckStartConditions &u)
sc::result react (const LoadSaveFileFailed &u)
sc::result react (const ShutdownServer &u)
sc::result react (const Error &msg)
Public Attributes
std::map< std::string, int > m_expected_ai_names_and_ids
int m_num_expected_players
std::vector< PlayerSaveGameData > m_player_save_game_data
std::shared_ptr< ServerSaveGameData > m_server_save_game_data
std::shared_ptr< SinglePlayerSetupData > m_single_player_setup_data
Detailed Description
The server state in which a new single-player game has been initiated, and the server is waiting for all players to join.
Member Typedef Documentation
reactions
typedef boost::mpl::list< sc::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, sc::custom_reaction<JoinGame>, sc::custom_reaction<CheckStartConditions>, sc::custom_reaction<LoadSaveFileFailed>, sc::custom_reaction<ShutdownServer>, sc::custom_reaction<Error> > WaitingForSPGameJoiners::reactions
Constructor & Destructor Documentation
WaitingForSPGameJoiners()
WaitingForSPGameJoiners::WaitingForSPGameJoiners (my_context c)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerApp::CreateAIClients(), DebugLogger, ErrorLogger, ErrorMessage(), ServerNetworking::HostPlayerID(), ServerApp::InitializePython(), PythonBase::IsPythonRunning(), LoadPlayerSaveHeaderData(), PlayerSetupData::m_client_type, m_expected_ai_names_and_ids, ServerApp::m_networking, m_num_expected_players, PlayerSetupData::m_player_id, PlayerSetupData::m_player_name, ServerApp::m_python_server, PlayerSetupData::m_save_game_empire_id, m_single_player_setup_data, ServerApp::Networking(), ServerNetworking::NewPlayerID(), ServerApp::NewSPGameInit(), anonymous_namespace{ServerFSM.cpp}::SendMessageToHost(), to_string(), TraceLogger, and UserStringNop.
~WaitingForSPGameJoiners()
WaitingForSPGameJoiners::~WaitingForSPGameJoiners ()
References TraceLogger.
Member Function Documentation
react() [1/5]
sc::result WaitingForSPGameJoiners::react (const JoinGame & msg)
References both, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ContentCheckSumMessage(), DebugLogger, ServerNetworking::Disconnect(), ErrorLogger, ExtractJoinGameMessageData(), GetOptionsDB(), ServerNetworking::HostPlayerID(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, JoinAckMessage(), LoggerConfigMessage(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), m_expected_ai_names_and_ids, ServerApp::m_networking, m_num_expected_players, m_single_player_setup_data, ServerApp::Networking(), ServerApp::NewSPGameInit(), ServerNetworking::NumEstablishedPlayers(), and TraceLogger.
react() [2/5]
sc::result WaitingForSPGameJoiners::react (const CheckStartConditions & u)
References DebugLogger, Empires(), ErrorMessage(), GetCombatLogManager(), GetSpeciesManager(), GetUniverse(), PythonBase::IsPythonRunning(), LoadGame(), ServerApp::LoadSPGameInit(), ServerApp::m_galaxy_setup_data, ServerApp::m_networking, m_num_expected_players, m_player_save_game_data, ServerApp::m_python_server, m_server_save_game_data, m_single_player_setup_data, ServerNetworking::NumEstablishedPlayers(), anonymous_namespace{ServerFSM.cpp}::SendMessageToHost(), ServerApp::SendNewGameStartMessages(), TraceLogger, UserStringNop, and ServerApp::VerifySPGameAIs().
react() [3/5]
sc::result WaitingForSPGameJoiners::react (const LoadSaveFileFailed & u)
References TraceLogger.
react() [4/5]
sc::result WaitingForSPGameJoiners::react (const ShutdownServer & u)
References TraceLogger.
react() [5/5]
sc::result WaitingForSPGameJoiners::react (const Error & msg)
References DebugLogger, and anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage().
Member Data Documentation
m_expected_ai_names_and_ids
std::map<std::string, int> WaitingForSPGameJoiners::m_expected_ai_names_and_ids
Referenced by react(), and WaitingForSPGameJoiners().
m_num_expected_players
int WaitingForSPGameJoiners::m_num_expected_players
Referenced by react(), and WaitingForSPGameJoiners().
m_player_save_game_data
std::vector<PlayerSaveGameData> WaitingForSPGameJoiners::m_player_save_game_data
Referenced by react().
m_server_save_game_data
std::shared_ptr<ServerSaveGameData> WaitingForSPGameJoiners::m_server_save_game_data
Referenced by react().
m_single_player_setup_data
std::shared_ptr<SinglePlayerSetupData> WaitingForSPGameJoiners::m_single_player_setup_data
Referenced by react(), and WaitingForSPGameJoiners().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp