FreeOrion: Condition::EmpireAffiliation Struct Reference
Condition::EmpireAffiliation Struct Reference final
Matches all objects that are owned (if exclusive == false) or only owned (if exclusive == true) by an empire that has affilitation type affilitation with Empire empire_id.
#include <Condition.h>
Public Member Functions
EmpireAffiliation (std::unique_ptr< ValueRef::ValueRefBase< int >> &&empire_id, EmpireAffiliationType affiliation)
EmpireAffiliation (std::unique_ptr< ValueRef::ValueRefBase< int >> &&empire_id)
EmpireAffiliation (EmpireAffiliationType affiliation)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
EmpireAffiliationType m_affiliation
std::unique_ptr< ValueRef::ValueRefBase< int > > m_empire_id
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all objects that are owned (if exclusive == false) or only owned (if exclusive == true) by an empire that has affilitation type affilitation with Empire empire_id.
Constructor & Destructor Documentation
EmpireAffiliation() [1/3]
Condition::EmpireAffiliation::EmpireAffiliation (std::unique_ptr< ValueRef::ValueRefBase< int >> && empire_id, EmpireAffiliationType affiliation)
EmpireAffiliation() [2/3]
Condition::EmpireAffiliation::EmpireAffiliation (std::unique_ptr< ValueRef::ValueRefBase< int >> && empire_id) explicit
EmpireAffiliation() [3/3]
Condition::EmpireAffiliation::EmpireAffiliation (EmpireAffiliationType affiliation) explicit
Member Function Documentation
Description()
std::string Condition::EmpireAffiliation::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References AFFIL_ANY, AFFIL_NONE, AFFIL_SELF, ALL_EMPIRES, FlexibleFormat(), GetEmpire(), m_affiliation, m_empire_id, and UserString().
Dump()
std::string Condition::EmpireAffiliation::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References AFFIL_ALLY, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_ENEMY, AFFIL_HUMAN, AFFIL_NONE, AFFIL_SELF, DumpIndent(), m_affiliation, and m_empire_id.
Eval()
void Condition::EmpireAffiliation::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ALL_EMPIRES, ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_affiliation, m_empire_id, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::EmpireAffiliation::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_affiliation, m_empire_id, and TraceLogger.
Match()
bool Condition::EmpireAffiliation::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ALL_EMPIRES, ScriptingContext::condition_local_candidate, ErrorLogger, m_affiliation, and m_empire_id.
operator==()
bool Condition::EmpireAffiliation::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, m_affiliation, and m_empire_id.
RootCandidateInvariant()
bool Condition::EmpireAffiliation::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_empire_id.
Referenced by Eval().
serialize()
template<class Archive > void Condition::EmpireAffiliation::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::EmpireAffiliation::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_empire_id.
SourceInvariant()
bool Condition::EmpireAffiliation::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_empire_id.
TargetInvariant()
bool Condition::EmpireAffiliation::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_empire_id.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_affiliation
EmpireAffiliationType Condition::EmpireAffiliation::m_affiliation private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), and operator==().
m_empire_id
std::unique_ptr<ValueRef::ValueRefBase<int> > Condition::EmpireAffiliation::m_empire_id private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp