FreeOrion: WaitingForMPGameJoiners Struct Reference
WaitingForMPGameJoiners Struct Reference
The server state in which a multiplayer game has been initiated, and the server is waiting for all players to join.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::in_state_reaction< Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection >, sc::custom_reaction< JoinGame >, sc::custom_reaction< AuthResponse >, sc::custom_reaction< CheckStartConditions >, sc::custom_reaction< ShutdownServer >, sc::custom_reaction< Hostless >, sc::custom_reaction< Error > > reactions
Public Member Functions
WaitingForMPGameJoiners (my_context c)
~WaitingForMPGameJoiners ()
sc::result react (const JoinGame &msg)
sc::result react (const AuthResponse &msg)
sc::result react (const CheckStartConditions &u)
sc::result react (const ShutdownServer &u)
sc::result react (const Hostless &u)
sc::result react (const Error &msg)
Public Attributes
std::set< std::string > m_expected_ai_player_names
std::shared_ptr< MultiplayerLobbyData > m_lobby_data
std::vector< PlayerSaveGameData > m_player_save_game_data
std::shared_ptr< ServerSaveGameData > m_server_save_game_data
Detailed Description
The server state in which a multiplayer game has been initiated, and the server is waiting for all players to join.
Member Typedef Documentation
reactions
typedef boost::mpl::list< sc::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, sc::custom_reaction<JoinGame>, sc::custom_reaction<AuthResponse>, sc::custom_reaction<CheckStartConditions>, sc::custom_reaction<ShutdownServer>, sc::custom_reaction<Hostless>, sc::custom_reaction<Error> > WaitingForMPGameJoiners::reactions
Constructor & Destructor Documentation
WaitingForMPGameJoiners()
WaitingForMPGameJoiners::WaitingForMPGameJoiners (my_context c)
References Networking::CLIENT_TYPE_AI_PLAYER, ServerApp::CreateAIClients(), ServerApp::InitializePython(), m_expected_ai_player_names, m_lobby_data, m_player_save_game_data, m_server_save_game_data, and TraceLogger.
~WaitingForMPGameJoiners()
WaitingForMPGameJoiners::~WaitingForMPGameJoiners ()
References TraceLogger.
Member Function Documentation
react() [1/6]
sc::result WaitingForMPGameJoiners::react (const JoinGame & msg)
References AuthRequestMessage(), both, ServerNetworking::CheckCookie(), Networking::AuthRoles::Clear(), Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerNetworking::Disconnect(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerFSM::EstablishPlayer(), ExtractJoinGameMessageData(), FlexibleFormat(), ServerNetworking::GetCookiesSize(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAvailableName(), JoinAckMessage(), LoggerConfigMessage(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), m_expected_ai_player_names, m_lobby_data, ServerApp::m_networking, ServerApp::Networking(), ServerNetworking::NewPlayerID(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, to_string(), TraceLogger, UserString(), and UserStringNop.
react() [2/6]
sc::result WaitingForMPGameJoiners::react (const AuthResponse & msg)
References Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerNetworking::Disconnect(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ServerFSM::EstablishPlayer(), ExtractAuthResponseMessageData(), FlexibleFormat(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::m_networking, ServerApp::Networking(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, TraceLogger, UserString(), and UserStringNop.
react() [3/6]
sc::result WaitingForMPGameJoiners::react (const CheckStartConditions & u)
References DebugLogger, PythonBase::IsPythonRunning(), ServerApp::LoadMPGameInit(), m_expected_ai_player_names, m_lobby_data, m_player_save_game_data, ServerApp::m_python_server, m_server_save_game_data, ServerApp::NewMPGameInit(), and TraceLogger.
react() [4/6]
sc::result WaitingForMPGameJoiners::react (const ShutdownServer & u)
References TraceLogger.
react() [5/6]
sc::result WaitingForMPGameJoiners::react (const Hostless & u)
References ServerApp::m_ai_client_processes, and TraceLogger.
react() [6/6]
sc::result WaitingForMPGameJoiners::react (const Error & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, Empires(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ExtractDiplomacyMessageData(), ExtractPlayerChatMessageData(), OptionsDB::Get(), GetEmpire(), GetOptionsDB(), EmpireManager::HandleDiplomaticMessage(), anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), ServerApp::m_networking, PlayingGame::PlayingGame(), ServerApp::PushChatMessage(), PlayingGame::react(), ServerPlayerChatMessage(), TraceLogger, PlayingGame::TurnTimedoutHandler(), WarnLogger, and PlayingGame::~PlayingGame().
Member Data Documentation
m_expected_ai_player_names
std::set<std::string> WaitingForMPGameJoiners::m_expected_ai_player_names
Referenced by react(), and WaitingForMPGameJoiners().
m_lobby_data
std::shared_ptr<MultiplayerLobbyData> WaitingForMPGameJoiners::m_lobby_data
Referenced by react(), and WaitingForMPGameJoiners().
m_player_save_game_data
std::vector<PlayerSaveGameData> WaitingForMPGameJoiners::m_player_save_game_data
Referenced by react(), and WaitingForMPGameJoiners().
m_server_save_game_data
std::shared_ptr<ServerSaveGameData> WaitingForMPGameJoiners::m_server_save_game_data
Referenced by react(), and WaitingForMPGameJoiners().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp