FreeOrion: Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch Struct Reference
Public Member Functions
HomeworldSimpleMatch (const std::vector< std::string > &names)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
const std::vector< std::string > & m_names
Constructor & Destructor Documentation
HomeworldSimpleMatch()
Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::HomeworldSimpleMatch (const std::vector< std::string > & names) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References SpeciesManager::begin(), SpeciesManager::end(), GetPlanet(), GetSpecies(), GetSpeciesManager(), Condition::Homeworld::m_names, and parse::species().
Member Data Documentation
m_names
const std::vector<std::string>& Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::m_names
The documentation for this struct was generated from the following file:
Condition.cpp