FreeOrion: Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch Struct Reference
Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch Struct Reference
Public Member Functions
CanAddStarlaneConnectionSimpleMatch (const ObjectSet &destination_objects, const ObjectMap &objects)
bool operator() (const std::shared_ptr< const UniverseObject > &candidate) const
Public Attributes
std::vector< std::shared_ptr< const System > > m_destination_systems
const ObjectMap & m_objects
Constructor & Destructor Documentation
CanAddStarlaneConnectionSimpleMatch()
Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::CanAddStarlaneConnectionSimpleMatch (const ObjectSet & destination_objects, const ObjectMap & objects) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::operator() (const std::shared_ptr< const UniverseObject > & candidate) const inline
References Condition::anonymous_namespace{Conditions.cpp}::LaneCrossesExistingLane(), Condition::anonymous_namespace{Conditions.cpp}::LanesAngularlyTooClose(), and Condition::anonymous_namespace{Conditions.cpp}::LaneTooCloseToOtherSystem().
Member Data Documentation
m_destination_systems
std::vector<std::shared_ptr<const System> > Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::m_destination_systems
m_objects
const ObjectMap& Condition::anonymous_namespace{Conditions.cpp}::CanAddStarlaneConnectionSimpleMatch::m_objects
The documentation for this struct was generated from the following file:
Conditions.cpp