FreeOrion: InfluenceQueue::Element Struct Reference
InfluenceQueue::Element Struct Reference
The type of a single element in the Influence queue.
#include <InfluenceQueue.h>
Public Member Functions
Element ()=default
Element (int empire_id_, std::string name_, bool paused_=false)
std::string Dump () const
Public Attributes
float allocated_ip = 0.0f
IP allocated to this InfluenceQueue Element by Empire Influence update.
int empire_id = ALL_EMPIRES
std::string name
name of influence project
bool paused = false
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
The type of a single element in the Influence queue.
Constructor & Destructor Documentation
Element() [1/2]
InfluenceQueue::Element::Element () explicit default
Element() [2/2]
InfluenceQueue::Element::Element (int empire_id_, std::string name_, bool paused_ = false) inline
Member Function Documentation
Dump()
std::string InfluenceQueue::Element::Dump () const
References allocated_ip, empire_id, name, and paused.
serialize()
template<typename Archive > template void InfluenceQueue::Element::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References ResearchQueue::Element::empire_id, ResearchQueue::Element::name, ResearchQueue::Element::paused, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
allocated_ip
float InfluenceQueue::Element::allocated_ip = 0.0f
IP allocated to this InfluenceQueue Element by Empire Influence update.
Referenced by Dump(), and FreeOrionPython::WrapEmpire().
empire_id
int InfluenceQueue::Element::empire_id = ALL_EMPIRES
Referenced by Dump().
name
std::string InfluenceQueue::Element::name
name of influence project
Referenced by Dump(), InfluenceQueue::InQueue(), and FreeOrionPython::WrapEmpire().
paused
bool InfluenceQueue::Element::paused = false
Referenced by Dump().
The documentation for this struct was generated from the following files:
InfluenceQueue.h
InfluenceQueue.cpp
SerializeEmpire.cpp