FreeOrion: WaitingForMPJoinAck Struct Reference
WaitingForMPJoinAck Struct Reference
The human client state in which the player has requested to join a single-player game and is waiting for the server to acknowledge the player's join.
#include <HumanClientFSM.h>
Public Types
typedef boost::statechart::simple_state< WaitingForMPJoinAck, HumanClientFSM > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< JoinGame >, boost::statechart::custom_reaction< AuthRequest >, boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< CancelMPGameClicked >, boost::statechart::custom_reaction< Error > > reactions
Public Member Functions
WaitingForMPJoinAck ()
~WaitingForMPJoinAck ()
boost::statechart::result react (const JoinGame &a)
boost::statechart::result react (const AuthRequest &a)
boost::statechart::result react (const Disconnection &d)
boost::statechart::result react (const StartQuittingGame &msg)
boost::statechart::result react (const CancelMPGameClicked &msg)
boost::statechart::result react (const Error &msg)
Detailed Description
The human client state in which the player has requested to join a single-player game and is waiting for the server to acknowledge the player's join.
Member Typedef Documentation
Base
typedef boost::statechart::simple_state<WaitingForMPJoinAck, HumanClientFSM> WaitingForMPJoinAck::Base
reactions
typedef boost::mpl::list< boost::statechart::custom_reaction<JoinGame>, boost::statechart::custom_reaction<AuthRequest>, boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<CancelMPGameClicked>, boost::statechart::custom_reaction<Error> > WaitingForMPJoinAck::reactions
Constructor & Destructor Documentation
WaitingForMPJoinAck()
WaitingForMPJoinAck::WaitingForMPJoinAck ()
References TraceLogger.
~WaitingForMPJoinAck()
WaitingForMPJoinAck::~WaitingForMPJoinAck ()
References TraceLogger.
Member Function Documentation
react() [1/6]
boost::statechart::result WaitingForMPJoinAck::react (const JoinGame & a)
References OptionsDB::Add(), OptionsDB::Commit(), HumanClientApp::EncodeServerAddressOption(), ErrorLogger, ExtractJoinAckMessageData(), GetOptionsDB(), OptionsDB::Set(), to_string(), TraceLogger, and WarnLogger.
react() [2/6]
boost::statechart::result WaitingForMPJoinAck::react (const AuthRequest & a)
References ExtractAuthRequestMessageData(), and TraceLogger.
react() [3/6]
boost::statechart::result WaitingForMPJoinAck::react (const Disconnection & d)
References ClientUI::MessageBox(), TraceLogger, and UserString().
react() [4/6]
boost::statechart::result WaitingForMPJoinAck::react (const StartQuittingGame & msg)
References TraceLogger, and UserString().
react() [5/6]
boost::statechart::result WaitingForMPJoinAck::react (const CancelMPGameClicked & msg)
References TraceLogger.
react() [6/6]
boost::statechart::result WaitingForMPJoinAck::react (const Error & msg)
References ErrorLogger, ExtractErrorMessageData(), HumanClientApp::GetClientUI(), ClientUI::GetMessageWnd(), ClientUI::MessageBox(), TraceLogger, and UserString().
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp