FreeOrion: Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch Struct Reference
Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch Struct Reference
Public Member Functions
EmpireAffiliationSimpleMatch (int empire_id, EmpireAffiliationType affiliation)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
EmpireAffiliationType m_affiliation
int m_empire_id
Constructor & Destructor Documentation
EmpireAffiliationSimpleMatch()
Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch::EmpireAffiliationSimpleMatch (int empire_id, EmpireAffiliationType affiliation) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References AFFIL_ALLY, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_ENEMY, AFFIL_HUMAN, AFFIL_NONE, AFFIL_PEACE, AFFIL_SELF, ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_PLAYER, Empires(), EmpireManager::GetDiplomaticStatus(), GetEmpireClientType(), Condition::EmpireAffiliation::m_affiliation, and Condition::EmpireAffiliation::m_empire_id.
Member Data Documentation
m_affiliation
EmpireAffiliationType Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch::m_affiliation
m_empire_id
int Condition::anonymous_namespace{Conditions.cpp}::EmpireAffiliationSimpleMatch::m_empire_id
The documentation for this struct was generated from the following file:
Conditions.cpp