FreeOrion: Empire::PolicyAdoptionInfo Struct Reference
Empire::PolicyAdoptionInfo Struct Reference
Public Member Functions
PolicyAdoptionInfo ()
PolicyAdoptionInfo (int turn, const std::string &cat, int slot)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Public Attributes
int adoption_turn = -1
std::string category = ""
int slot_in_category = -1
Friends
class boost::serialization::access
Constructor & Destructor Documentation
PolicyAdoptionInfo() [1/2]
Empire::PolicyAdoptionInfo::PolicyAdoptionInfo ()
PolicyAdoptionInfo() [2/2]
Empire::PolicyAdoptionInfo::PolicyAdoptionInfo (int turn, const std::string & cat, int slot)
Member Function Documentation
serialize()
template<class Archive > template void Empire::PolicyAdoptionInfo::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version)
References serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
adoption_turn
int Empire::PolicyAdoptionInfo::adoption_turn = -1
category
std::string Empire::PolicyAdoptionInfo::category = ""
slot_in_category
int Empire::PolicyAdoptionInfo::slot_in_category = -1
The documentation for this struct was generated from the following files:
Empire.h
Empire.cpp
SerializeEmpire.cpp