FreeOrion: parse::detail::info_visitor Struct Reference
parse::detail::info_visitor Struct Reference
#include <ReportParseError.h>
Public Types
typedef void result_type
typedef boost::spirit::utf8_string string
Public Member Functions
info_visitor (std::ostream &os, const string &tag, std::size_t indent)
void indent () const
template<typename Iter >
void multi_info (Iter first, const Iter last) const
void operator() (boost::spirit::info::nil_) const
void operator() (const string &str) const
void operator() (const boost::spirit::info &what) const
void operator() (const std::pair< boost::spirit::info, boost::spirit::info > &pair) const
void operator() (const std::list< boost::spirit::info > &l) const
std::string prepare (const string &s) const
void print (const string &str) const
Public Attributes
int m_indent
std::ostream & m_os
const string & m_tag
Member Typedef Documentation
result_type
typedef void parse::detail::info_visitor::result_type
string
typedef boost::spirit::utf8_string parse::detail::info_visitor::string
Constructor & Destructor Documentation
info_visitor()
parse::detail::info_visitor::info_visitor (std::ostream & os, const string & tag, std::size_t indent)
Referenced by multi_info(), and operator()().
Member Function Documentation
indent()
void parse::detail::info_visitor::indent () const
References m_indent, and m_os.
Referenced by multi_info(), and operator()().
multi_info()
template<typename Iter > void parse::detail::info_visitor::multi_info (Iter first, const Iter last) const
References indent(), info_visitor(), m_os, and m_tag.
Referenced by operator()().
operator()() [1/5]
void parse::detail::info_visitor::operator() (boost::spirit::info::nil_) const
References indent(), m_tag, and print().
operator()() [2/5]
void parse::detail::info_visitor::operator() (const string & str) const
References indent(), and print().
operator()() [3/5]
void parse::detail::info_visitor::operator() (const boost::spirit::info & what) const
References info_visitor(), m_indent, and m_os.
operator()() [4/5]
void parse::detail::info_visitor::operator() (const std::pair< boost::spirit::info, boost::spirit::info > & pair) const
References multi_info().
operator()() [5/5]
void parse::detail::info_visitor::operator() (const std::list< boost::spirit::info > & l) const
References multi_info().
prepare()
std::string parse::detail::info_visitor::prepare (const string & s) const
References parse::lexer::bool_regex, parse::lexer::double_regex, parse::lexer::int_regex, and parse::lexer::string_regex.
Referenced by print().
print()
void parse::detail::info_visitor::print (const string & str) const
References m_os, and prepare().
Referenced by operator()().
Member Data Documentation
m_indent
int parse::detail::info_visitor::m_indent
Referenced by indent(), and operator()().
m_os
std::ostream& parse::detail::info_visitor::m_os
Referenced by indent(), multi_info(), operator()(), and print().
m_tag
const string& parse::detail::info_visitor::m_tag
Referenced by multi_info(), and operator()().
The documentation for this struct was generated from the following files:
ReportParseError.h
ReportParseError.cpp