FreeOrion: WaitingForTurnEndIdle Struct Reference
WaitingForTurnEndIdle Struct Reference
The default substate of WaitingForTurnEnd.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::custom_reaction< SaveGameRequest > > reactions
Public Member Functions
WaitingForTurnEndIdle (my_context c)
~WaitingForTurnEndIdle ()
sc::result react (const SaveGameRequest &msg)
Detailed Description
The default substate of WaitingForTurnEnd.
Member Typedef Documentation
typedef boost::mpl::list< sc::custom_reaction<SaveGameRequest> > WaitingForTurnEndIdle::reactions
Constructor & Destructor Documentation
WaitingForTurnEndIdle::WaitingForTurnEndIdle (my_context c)
References TraceLogger.
WaitingForTurnEndIdle::~WaitingForTurnEndIdle ()
References TraceLogger.
Member Function Documentation
sc::result WaitingForTurnEndIdle::react (const SaveGameRequest & msg)
References Empires(), error, ErrorLogger, ErrorMessage(), GetCombatLogManager(), ServerApp::GetPlayerSaveGameData(), GetSpeciesManager(), GetUniverse(), ServerApp::m_current_turn, ServerApp::m_galaxy_setup_data, ServerApp::m_networking, ServerApp::m_single_player_game, ServerNetworking::PlayerIsHost(), SaveGame(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerSaveGameCompleteMessage(), Message::Text(), TraceLogger, and UserStringNop.
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp