FreeOrion: boost::iostreams::base64_traits Struct Reference
boost::iostreams::base64_traits Struct Reference
#include <base64_filter.h>
Static Public Member Functions
static unsigned char decode (char c)
static char encode (unsigned char n)
Static Public Attributes
static const char padding = '='
Member Function Documentation
decode()
static unsigned char boost::iostreams::base64_traits::decode (char c) inline static
Referenced by boost::iostreams::basic_base64_decoder< Traits >::decode(), and boost::iostreams::basic_base64_decoder< Traits >::read_blocks().
encode()
static char boost::iostreams::base64_traits::encode (unsigned char n) inline static
Referenced by boost::iostreams::basic_base64_encoder< Traits >::close_with_flush(), and boost::iostreams::basic_base64_encoder< Traits >::write_blocks().
Member Data Documentation
padding
const char boost::iostreams::base64_traits::padding = '=' static
The documentation for this struct was generated from the following file:
base64_filter.h