FreeOrion: Condition::Species Struct Reference
Condition::Species Struct Reference final
Matches all planets or ships that have one of the species in species.
#include <Condition.h>
Public Member Functions
Species (std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string >>> &&names)
Species ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string > > > m_names
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all planets or ships that have one of the species in species.
Note that all Building object which are on matching planets are also matched.
Constructor & Destructor Documentation
Species() [1/2]
Species::Species (std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string >>> && names) explicit
Species() [2/2]
Species::Species ()
Member Function Documentation
Description()
std::string Species::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References Eval(), FlexibleFormat(), m_names, and UserString().
Dump()
std::string Species::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_names.
Eval()
void Species::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_names, and RootCandidateInvariant().
Referenced by Description().
GetCheckSum()
unsigned int Species::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_names, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Species::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddBuildingSet(), anonymous_namespace{Condition.cpp}::AddPlanetSet(), and anonymous_namespace{Condition.cpp}::AddShipSet().
Match()
bool Species::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, GetPlanet(), m_names, and Ship::SpeciesName().
operator==()
bool Species::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_names.
RootCandidateInvariant()
bool Species::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_names.
Referenced by Eval().
serialize()
template<class Archive > void Species::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Species::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_names.
SourceInvariant()
bool Species::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_names.
TargetInvariant()
bool Species::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_names.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_names
std::vector<std::unique_ptr<ValueRef::ValueRefBase<std::string> > > Condition::Species::m_names private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::SpeciesSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp