FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow Struct Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow Struct Reference
Public Member Functions
NewGamePlayerRow (const PlayerSetupData &player_data, int player_id, bool disabled)
void CompleteConstruction () override
Public Member Functions inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
PlayerRow ()
PlayerRow (const PlayerSetupData &player_data, int player_id)
Private Member Functions
void ColorChanged (const GG::Clr &clr)
void EmpireNameChanged (const std::string &str)
void PlayerTypeChanged (Networking::ClientType type)
void SpeciesChanged (const std::string &str)
Private Attributes
bool m_initial_disabled
Additional Inherited Members
Public Attributes inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
boost::signals2::signal< void()> DataChangedSignal
PlayerSetupData m_player_data
int m_player_id
Constructor & Destructor Documentation
NewGamePlayerRow()
anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::NewGamePlayerRow (const PlayerSetupData & player_data, int player_id, bool disabled) inline
Member Function Documentation
ColorChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::ColorChanged (const GG::Clr & clr) inline private
CompleteConstruction()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::CompleteConstruction () inline override
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, anonymous_namespace{MultiplayerLobbyWnd.cpp}::EMPIRE_NAME_WIDTH(), HumanClientApp::GetApp(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetHostTexture(), GetOptionsDB(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetReadyTexture(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerReadyBrowseWidth(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowMargin(), ClientUI::Pts(), and UserString().
EmpireNameChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::EmpireNameChanged (const std::string & str) inline private
PlayerTypeChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::PlayerTypeChanged (Networking::ClientType type) inline private
SpeciesChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::SpeciesChanged (const std::string & str) inline private
Member Data Documentation
m_initial_disabled
bool anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::m_initial_disabled private
The documentation for this struct was generated from the following file:
MultiplayerLobbyWnd.cpp