FreeOrion: Condition::Stationary Struct Reference
Condition::Stationary Struct Reference final
Matches objects that are moving.
#include <Conditions.h>
Public Member Functions
Stationary ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches objects that are moving.
... What does that mean? Departing this turn, or were located somewhere else last turn...?
Constructor & Destructor Documentation
Stationary()
Condition::Stationary::Stationary () inline explicit
References operator==().
Member Function Documentation
Description()
std::string Condition::Stationary::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References UserString().
Dump()
std::string Condition::Stationary::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent().
GetCheckSum()
unsigned int Condition::Stationary::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), and TraceLogger.
Match()
bool Condition::Stationary::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ScriptingContext::ContextObjects(), ErrorLogger, ObjectMap::get(), INVALID_OBJECT_ID, and Fleet::NextSystemID().
operator==()
bool Condition::Stationary::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References Condition::Condition::operator==().
RootCandidateInvariant()
bool Condition::Stationary::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
serialize()
template<typename Archive > void Condition::Stationary::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Stationary::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::Condition.
SourceInvariant()
bool Condition::Stationary::SourceInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References Effect::Dump().
TargetInvariant()
bool Condition::Stationary::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp