FreeOrion: anonymous_namespace{BuildingsParser.cpp}::rules Struct Reference
anonymous_namespace{BuildingsParser.cpp}::rules Struct Reference
Public Types
typedef parse::detail::rule< void(std::map< std::string, std::unique_ptr< BuildingType >> &), boost::spirit::qi::locals< std::string, std::string, CommonParams, CaptureResult > > building_type_rule
typedef parse::detail::rule< void(std::map< std::string, std::unique_ptr< BuildingType >> &) > start_rule
Public Member Functions
rules (const std::string &filename, const parse::text_iterator &first, const parse::text_iterator &last)
Public Attributes
building_type_rule building_type
start_rule start
Member Typedef Documentation
typedef parse::detail::rule< void (std::map<std::string, std::unique_ptr<BuildingType>>&), boost::spirit::qi::locals< std::string, std::string, CommonParams, CaptureResult > > anonymous_namespace{BuildingsParser.cpp}::rules::building_type_rule
typedef parse::detail::rule< void (std::map<std::string, std::unique_ptr<BuildingType>>&) > anonymous_namespace{BuildingsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{BuildingsParser.cpp}::rules::rules (const std::string & filename, const parse::text_iterator & first, const parse::text_iterator & last) inline
References parse::capture_result_enum(), parse::detail::common_params_parser(), CR_CAPTURE, debug, parse::lexer::instance(), anonymous_namespace{BuildingsParser.cpp}::is_unique_, parse::detail::label(), parse::report_error, and parse::lexer::string.
Member Data Documentation
building_type_rule anonymous_namespace{BuildingsParser.cpp}::rules::building_type
start_rule anonymous_namespace{BuildingsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
BuildingsParser.cpp