FreeOrion: Condition::Aggressive Struct Reference
Condition::Aggressive Struct Reference final
Matches objects that are aggressive fleets or are in aggressive fleets.
#include <Condition.h>
Public Member Functions
Aggressive ()
Aggressive (bool aggressive)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
bool GetAggressive () const
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_aggressive
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches objects that are aggressive fleets or are in aggressive fleets.
Constructor & Destructor Documentation
Aggressive() [1/2]
Condition::Aggressive::Aggressive () inline explicit
Aggressive() [2/2]
Condition::Aggressive::Aggressive (bool aggressive) inline explicit
References operator==().
Member Function Documentation
Description()
std::string Condition::Aggressive::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString().
Dump()
std::string Condition::Aggressive::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
GetAggressive()
bool Condition::Aggressive::GetAggressive () const inline
GetCheckSum()
unsigned int Condition::Aggressive::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
Match()
bool Condition::Aggressive::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, and GetFleet().
operator==()
bool Condition::Aggressive::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::operator==().
RootCandidateInvariant()
bool Condition::Aggressive::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::Aggressive::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Aggressive::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::Aggressive::SourceInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Effect::Dump().
TargetInvariant()
bool Condition::Aggressive::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_aggressive
bool Condition::Aggressive::m_aggressive private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp