FreeOrion: ValueRef::ValueRef< T > Struct Template Reference
ValueRef::ValueRef< T > Struct Template Reference abstract
The base class for all ValueRef classes.
#include <ValueRef.h>
Public Member Functions
virtual ~ValueRef ()
virtual bool ConstantExpr () const
virtual std::string Description () const =0
virtual std::string Dump (unsigned short ntabs=0) const =0
Returns a text description of this type of special.
T Eval () const
Evaluates the expression tree with an empty context.
virtual T Eval (const ScriptingContext &context) const =0
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
virtual unsigned int GetCheckSum () const
virtual bool LocalCandidateInvariant () const
bool operator!= (const ValueRef< T > &rhs) const
virtual bool operator== (const ValueRef< T > &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<typename T>
struct ValueRef::ValueRef< T >
The base class for all ValueRef classes.
This class provides the public interface for a ValueRef expression tree.
Constructor & Destructor Documentation
~ValueRef()
template<typename T> virtual ValueRef::ValueRef< T >::~ValueRef () inline virtual
Member Function Documentation
ConstantExpr()
template<typename T> virtual bool ValueRef::ValueRef< T >::ConstantExpr () const inline virtual
Reimplemented in ValueRef::Operation< T >, and ValueRef::Constant< T >.
Referenced by TechTreeWnd::LayoutPanel::TechPanel::Update().
Description()
template<typename T> virtual std::string ValueRef::ValueRef< T >::Description () const pure virtual
Implemented in ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by ValueRef::ComplexVariableDescription().
Dump()
template<typename T> virtual std::string ValueRef::ValueRef< T >::Dump (unsigned short ntabs = 0) const pure virtual
Returns a text description of this type of special.
Implemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Constant< T >, ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by ValueRef::ComplexVariableDump().
Eval() [1/2]
template<typename T> T ValueRef::ValueRef< T >::Eval () const inline
Evaluates the expression tree with an empty context.
Useful for evaluating expressions that do not depend on context.
Referenced by ValueRef::Operation< T >::EvalImpl(), ValueRef::Constant< T >::GetCheckSum(), ValueRef::Statistic< T >::GetCheckSum(), ValueRef::ComplexVariable< T >::GetCheckSum(), ObjectPanel::SortKey(), Condition::anonymous_namespace{Conditions.cpp}::TransferSortedObjects(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
Eval() [2/2]
template<typename T> virtual T ValueRef::ValueRef< T >::Eval (const ScriptingContext & context) const pure virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implemented in ValueRef::UserStringLookup< FromType >, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::UserStringLookup< FromType >, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::StringCast< FromType >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Constant< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, ValueRef::Constant< T >, ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
GetCheckSum()
template<typename T> virtual unsigned int ValueRef::ValueRef< T >::GetCheckSum () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Referenced by CheckSums::CheckSumCombine().
LocalCandidateInvariant()
template<typename T> virtual bool ValueRef::ValueRef< T >::LocalCandidateInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
operator!=()
template<typename T> bool ValueRef::ValueRef< T >::operator!= (const ValueRef< T > & rhs) const inline
operator==()
template<typename T > bool ValueRef::ValueRef< T >::operator== (const ValueRef< T > & rhs) const virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
RootCandidateInvariant()
template<typename T> virtual bool ValueRef::ValueRef< T >::RootCandidateInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
serialize()
template<typename T > template<typename Archive > void ValueRef::ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
template<typename T> virtual void ValueRef::ValueRef< T >::SetTopLevelContent (const std::string & content_name) inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, and ValueRef::Constant< T >.
SimpleIncrement()
template<typename T> virtual bool ValueRef::ValueRef< T >::SimpleIncrement () const inline virtual
Reimplemented in ValueRef::Operation< T >.
SourceInvariant()
template<typename T> virtual bool ValueRef::ValueRef< T >::SourceInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
TargetInvariant()
template<typename T> virtual bool ValueRef::ValueRef< T >::TargetInvariant () const inline virtual
Reimplemented in ValueRef::Operation< T >, ValueRef::NameLookup, ValueRef::UserStringLookup< FromType >, ValueRef::StringCast< FromType >, ValueRef::StaticCast< FromType, ToType >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Variable< T >, ValueRef::Variable< std::string >, ValueRef::Variable< ToType >, and ValueRef::Constant< T >.
Friends And Related Function Documentation
boost::serialization::access
template<typename T> friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Parse.h
ValueRef.h
ValueRefs.h