FreeOrion: MPLobby Struct Reference
MPLobby Struct Reference
The human client state in which the multiplayer lobby is active.
#include <ServerFSM.h>
Public Types
typedef boost::statechart::state< MPLobby, HumanClientFSM > Base
typedef boost::mpl::list< sc::custom_reaction< Disconnection >, sc::custom_reaction< JoinGame >, sc::custom_reaction< AuthResponse >, sc::custom_reaction< LobbyUpdate >, sc::custom_reaction< PlayerChat >, sc::custom_reaction< StartMPGame >, sc::custom_reaction< HostMPGame >, sc::custom_reaction< HostSPGame >, sc::custom_reaction< ShutdownServer >, sc::custom_reaction< Hostless >, sc::custom_reaction< Error > > reactions
typedef boost::mpl::list< boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< HostID >, boost::statechart::custom_reaction< LobbyUpdate >, boost::statechart::custom_reaction< PlayerChat >, boost::statechart::custom_reaction< CancelMPGameClicked >, boost::statechart::custom_reaction< StartMPGameClicked >, boost::statechart::custom_reaction< GameStart >, boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< Error >, boost::statechart::custom_reaction< CheckSum >, boost::statechart::custom_reaction< ChatHistory >, boost::statechart::custom_reaction< PlayerStatus >, boost::statechart::custom_reaction< SaveGameComplete >, boost::statechart::custom_reaction< TurnProgress > > reactions
Public Member Functions
MPLobby (my_context c)
MPLobby (my_context ctx)
~MPLobby ()
~MPLobby ()
sc::result react (const Disconnection &d)
sc::result react (const JoinGame &msg)
sc::result react (const AuthResponse &msg)
sc::result react (const LobbyUpdate &msg)
sc::result react (const PlayerChat &msg)
sc::result react (const StartMPGame &msg)
sc::result react (const HostMPGame &msg)
sc::result react (const HostSPGame &msg)
sc::result react (const ShutdownServer &u)
sc::result react (const Hostless &u)
sc::result react (const Error &msg)
boost::statechart::result react (const Disconnection &d)
boost::statechart::result react (const HostID &msg)
boost::statechart::result react (const LobbyUpdate &msg)
boost::statechart::result react (const PlayerChat &msg)
boost::statechart::result react (const CancelMPGameClicked &a)
boost::statechart::result react (const StartMPGameClicked &a)
boost::statechart::result react (const GameStart &msg)
boost::statechart::result react (const StartQuittingGame &msg)
boost::statechart::result react (const Error &msg)
boost::statechart::result react (const CheckSum &msg)
boost::statechart::result react (const ChatHistory &msg)
boost::statechart::result react (const PlayerStatus &msg)
boost::statechart::result react (const SaveGameComplete &msg)
boost::statechart::result react (const TurnProgress &msg)
Public Attributes
int m_ai_next_index
std::shared_ptr< MultiplayerLobbyData > m_lobby_data
std::vector< PlayerSaveGameData > m_player_save_game_data
std::shared_ptr< ServerSaveGameData > m_server_save_game_data
Private Member Functions
void EstablishPlayer (const PlayerConnectionPtr &player_connection, const std::string &player_name, Networking::ClientType client_type, const std::string &client_version_string, const Networking::AuthRoles &roles)
void ValidateClientLimits ()
Detailed Description
The human client state in which the multiplayer lobby is active.
The server state in which the multiplayer lobby is active.
Member Typedef Documentation
Base
typedef boost::statechart::state<MPLobby, HumanClientFSM> MPLobby::Base
reactions [1/2]
typedef boost::mpl::list< sc::custom_reaction<Disconnection>, sc::custom_reaction<JoinGame>, sc::custom_reaction<AuthResponse>, sc::custom_reaction<LobbyUpdate>, sc::custom_reaction<PlayerChat>, sc::custom_reaction<StartMPGame>, sc::custom_reaction<HostMPGame>, sc::custom_reaction<HostSPGame>, sc::custom_reaction<ShutdownServer>, sc::custom_reaction<Hostless>, sc::custom_reaction<Error> > MPLobby::reactions
reactions [2/2]
typedef boost::mpl::list< boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<HostID>, boost::statechart::custom_reaction<LobbyUpdate>, boost::statechart::custom_reaction<PlayerChat>, boost::statechart::custom_reaction<CancelMPGameClicked>, boost::statechart::custom_reaction<StartMPGameClicked>, boost::statechart::custom_reaction<GameStart>, boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<Error>, boost::statechart::custom_reaction<CheckSum>, boost::statechart::custom_reaction<ChatHistory>, boost::statechart::custom_reaction<PlayerStatus>, boost::statechart::custom_reaction<SaveGameComplete>, boost::statechart::custom_reaction<TurnProgress> > MPLobby::reactions
Constructor & Destructor Documentation
MPLobby() [1/2]
MPLobby::MPLobby (my_context ctx)
References TraceLogger.
Referenced by anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged().
~MPLobby() [1/2]
MPLobby::~MPLobby ()
References TraceLogger.
Referenced by anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged().
MPLobby() [2/2]
MPLobby::MPLobby (my_context c)
~MPLobby() [2/2]
MPLobby::~MPLobby ()
Member Function Documentation
EstablishPlayer()
void MPLobby::EstablishPlayer (const PlayerConnectionPtr & player_connection, const std::string & player_name, Networking::ClientType client_type, const std::string & client_version_string, const Networking::AuthRoles & roles) private
References both, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerNetworking::established_begin(), ServerNetworking::established_end(), anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), GetSpeciesManager(), anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour(), Networking::INVALID_PLAYER_ID, LoggerConfigMessage(), anonymous_namespace{LoggerWithOptionsDB.cpp}::LoggerOptionsLabelsAndLevels(), PlayerSetupData::m_authenticated, PlayerSetupData::m_client_type, PlayerSetupData::m_empire_color, PlayerSetupData::m_empire_name, ServerApp::m_networking, PlayerSetupData::m_player_name, PlayerSetupData::m_starting_species_name, SpeciesManager::RandomPlayableSpeciesName(), SpeciesManager::SequentialPlayableSpeciesName(), and ServerLobbyUpdateMessage().
react() [1/25]
sc::result MPLobby::react (const Disconnection & d)
react() [2/25]
sc::result MPLobby::react (const JoinGame & msg)
References AuthRequestMessage(), ServerNetworking::CheckCookie(), Networking::AuthRoles::Clear(), Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::Disconnect(), ErrorLogger, ErrorMessage(), ExtractJoinGameMessageData(), FlexibleFormat(), ServerNetworking::GetCookiesSize(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAvailableName(), ServerApp::Networking(), to_string(), TraceLogger, and UserString().
react() [3/25]
sc::result MPLobby::react (const AuthResponse & msg)
References ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerNetworking::Disconnect(), Empires(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ExtractAuthResponseMessageData(), ExtractLobbyUpdateMessageData(), ExtractPlayerChatMessageData(), FlexibleFormat(), anonymous_namespace{ServerFSM.cpp}::GenerateEmpireName(), OptionsDB::Get(), GetCombatLogManager(), GetOptionsDB(), ServerNetworking::GetPlayer(), GetServerSaveDir(), GetSpeciesManager(), GetUniverse(), anonymous_namespace{ServerFSM.cpp}::GetUnusedEmpireColour(), if(), Networking::INVALID_CLIENT_TYPE, Networking::INVALID_PLAYER_ID, ServerApp::IsAuthSuccessAndFillRoles(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), LoadEmpireSaveGameData(), LoadGame(), anonymous_namespace{ServerFSM.cpp}::LogPlayerSetupData(), GalaxySetupData::m_age, GalaxySetupData::m_ai_aggr, MultiplayerLobbyData::m_any_can_edit, PlayerSetupData::m_client_type, PlayerSetupData::m_empire_color, PlayerSetupData::m_empire_name, ServerApp::m_galaxy_setup_data, GalaxySetupData::m_game_rules, GalaxySetupData::m_monster_freq, GalaxySetupData::m_native_freq, ServerApp::m_networking, MultiplayerLobbyData::m_new_game, GalaxySetupData::m_planet_density, PlayerSetupData::m_player_id, PlayerSetupData::m_player_name, MultiplayerLobbyData::m_players, MultiplayerLobbyData::m_save_game, PlayerSetupData::m_save_game_empire_id, GalaxySetupData::m_seed, GalaxySetupData::m_shape, GalaxySetupData::m_size, GalaxySetupData::m_specials_freq, GalaxySetupData::m_starlane_freq, PlayerSetupData::m_starting_species_name, ServerApp::Networking(), ServerApp::PushChatMessage(), SpeciesManager::RandomPlayableSpeciesName(), react(), Networking::ROLE_CLIENT_TYPE_MODERATOR, Networking::ROLE_CLIENT_TYPE_OBSERVER, Networking::ROLE_CLIENT_TYPE_PLAYER, Networking::ROLE_GALAXY_SETUP, Networking::ROLE_HOST, Seed(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), SpeciesManager::SequentialPlayableSpeciesName(), ServerLobbyUpdateMessage(), ServerPlayerChatMessage(), to_string(), TraceLogger, UserString(), UserStringNop, and WarnLogger.
react() [4/25]
sc::result MPLobby::react (const LobbyUpdate & msg)
react() [5/25]
sc::result MPLobby::react (const PlayerChat & msg)
react() [6/25]
sc::result MPLobby::react (const StartMPGame & msg)
References DebugLogger, ServerNetworking::Disconnect(), Empires(), ErrorLogger, ErrorMessage(), GetCombatLogManager(), GetServerSaveDir(), GetSpeciesManager(), GetUniverse(), LoadGame(), ServerApp::LoadMPGameInit(), ServerApp::m_galaxy_setup_data, ServerApp::m_networking, GalaxySetupData::m_seed, ServerApp::NewMPGameInit(), ServerNetworking::NumEstablishedPlayers(), ServerNetworking::PlayerIsHost(), Seed(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), TraceLogger, and UserStringNop.
react() [7/25]
sc::result MPLobby::react (const HostMPGame & msg)
References ErrorLogger, ErrorMessage(), and UserStringNop.
react() [8/25]
sc::result MPLobby::react (const HostSPGame & msg)
References ErrorLogger, ErrorMessage(), and UserStringNop.
react() [9/25]
sc::result MPLobby::react (const ShutdownServer & u)
References TraceLogger.
react() [10/25]
sc::result MPLobby::react (const Hostless & u)
References anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), react(), and TraceLogger.
react() [11/25]
sc::result MPLobby::react (const Error & msg)
react() [12/25]
sc::result MPLobby::react (const Disconnection & d)
References ClientUI::MessageBox(), TraceLogger, and UserString().
Referenced by react(), and ValidateClientLimits().
react() [13/25]
boost::statechart::result MPLobby::react (const HostID & msg)
References ErrorLogger, and Networking::INVALID_PLAYER_ID.
react() [14/25]
sc::result MPLobby::react (const LobbyUpdate & msg)
References ExtractLobbyUpdateMessageData(), and TraceLogger.
react() [15/25]
sc::result MPLobby::react (const PlayerChat & msg)
References ExtractServerPlayerChatMessageData(), and TraceLogger.
react() [16/25]
boost::statechart::result MPLobby::react (const CancelMPGameClicked & a)
References TraceLogger.
react() [17/25]
boost::statechart::result MPLobby::react (const StartMPGameClicked & a)
References ErrorLogger, anonymous_namespace{AIWrapper.cpp}::PlayerID(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), StartMPGameMessage(), and TraceLogger.
react() [18/25]
boost::statechart::result MPLobby::react (const GameStart & msg)
References TraceLogger.
react() [19/25]
boost::statechart::result MPLobby::react (const StartQuittingGame & msg)
References TraceLogger, and UserString().
react() [20/25]
sc::result MPLobby::react (const Error & msg)
References ErrorLogger, ExtractErrorMessageData(), ClientUI::MessageBox(), TraceLogger, and UserString().
react() [21/25]
boost::statechart::result MPLobby::react (const CheckSum & msg)
References ClientUI::MessageBox(), TraceLogger, and UserString().
react() [22/25]
boost::statechart::result MPLobby::react (const ChatHistory & msg)
References ExtractChatHistoryMessage(), and TraceLogger.
react() [23/25]
boost::statechart::result MPLobby::react (const PlayerStatus & msg)
References TraceLogger.
react() [24/25]
boost::statechart::result MPLobby::react (const SaveGameComplete & msg)
References TraceLogger.
react() [25/25]
boost::statechart::result MPLobby::react (const TurnProgress & msg)
References ExtractTurnProgressMessageData(), and TraceLogger.
ValidateClientLimits()
void MPLobby::ValidateClientLimits () private
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerNetworking::empty(), ServerNetworking::established_begin(), ServerNetworking::established_end(), OptionsDB::Get(), GetOptionsDB(), Networking::INVALID_PLAYER_ID, ServerApp::IsHostless(), ServerApp::m_ai_client_processes, ServerApp::m_networking, Disconnection::m_player_connection, ServerNetworking::NumEstablishedPlayers(), ServerNetworking::PlayerIsHost(), ServerApp::PushChatMessage(), react(), ServerApp::SelectNewHost(), ServerLobbyUpdateMessage(), ServerPlayerChatMessage(), OptionsDB::Set(), TraceLogger, UserStringNop, and WarnLogger.
Member Data Documentation
m_ai_next_index
int MPLobby::m_ai_next_index
m_lobby_data
std::shared_ptr<MultiplayerLobbyData> MPLobby::m_lobby_data
m_player_save_game_data
std::vector<PlayerSaveGameData> MPLobby::m_player_save_game_data
m_server_save_game_data
std::shared_ptr<ServerSaveGameData> MPLobby::m_server_save_game_data
The documentation for this struct was generated from the following files:
HumanClientFSM.h
ServerFSM.h
HumanClientFSM.cpp
ServerFSM.cpp