FreeOrion: anonymous_namespace{FieldsParser.cpp}::rules Struct Reference
anonymous_namespace{FieldsParser.cpp}::rules Struct Reference
Public Types
typedef parse::detail::rule< void(std::map< std::string, std::unique_ptr< FieldType >> &), boost::spirit::qi::locals< std::string, std::string, float, std::set< std::string >, std::vector< std::shared_ptr< Effect::EffectsGroup > > > > field_rule
typedef parse::detail::rule< void(std::map< std::string, std::unique_ptr< FieldType >> &) > start_rule
Public Member Functions
rules (const std::string &filename, const parse::text_iterator &first, const parse::text_iterator &last)
Public Attributes
field_rule field
start_rule start
Member Typedef Documentation
typedef parse::detail::rule< void (std::map<std::string, std::unique_ptr<FieldType>>&), boost::spirit::qi::locals< std::string, std::string, float, std::set<std::string>, std::vector<std::shared_ptr<Effect::EffectsGroup> > > > anonymous_namespace{FieldsParser.cpp}::rules::field_rule
typedef parse::detail::rule< void (std::map<std::string, std::unique_ptr<FieldType>>&) > anonymous_namespace{FieldsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{FieldsParser.cpp}::rules::rules (const std::string & filename, const parse::text_iterator & first, const parse::text_iterator & last) inline
References debug, parse::detail::double_, parse::detail::effects_group_parser(), parse::lexer::instance(), anonymous_namespace{FieldsParser.cpp}::is_unique_, parse::detail::label(), parse::report_error, parse::lexer::string, and parse::detail::tags_parser().
Member Data Documentation
field_rule anonymous_namespace{FieldsParser.cpp}::rules::field
start_rule anonymous_namespace{FieldsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
FieldsParser.cpp