FreeOrion: anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter Struct Reference
anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter Struct Reference
Public Member Functions
SystemPredicateFilter ()
SystemPredicateFilter (const SystemGraph *graph, int empire_id, const Pathfinder::SystemExclusionPredicateType &pred)
template<typename EdgeDescriptor >
bool operator() (const EdgeDescriptor &edge) const
Private Attributes
int m_empire_id
const SystemGraph * m_graph
Pathfinder::SystemExclusionPredicateType m_pred
Constructor & Destructor Documentation
SystemPredicateFilter() [1/2]
anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::SystemPredicateFilter () inline
SystemPredicateFilter() [2/2]
anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::SystemPredicateFilter (const SystemGraph * graph, int empire_id, const Pathfinder::SystemExclusionPredicateType & pred) inline
References ErrorLogger.
Member Function Documentation
operator()()
template<typename EdgeDescriptor > bool anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::operator() (const EdgeDescriptor & edge) const inline
References DebugLogger, EmpireKnownObjects(), ErrorLogger, boost::get(), and GetEmpireKnownSystem().
Member Data Documentation
m_empire_id
int anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::m_empire_id private
m_graph
const SystemGraph* anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::m_graph private
m_pred
Pathfinder::SystemExclusionPredicateType anonymous_namespace{Pathfinder.cpp}::GraphImpl::SystemPredicateFilter::m_pred private
The documentation for this struct was generated from the following file:
Pathfinder.cpp