FreeOrion: anonymous_namespace{Parse.cpp}::item_spec_parser_rules Struct Reference
anonymous_namespace{Parse.cpp}::item_spec_parser_rules Struct Reference
Public Member Functions
item_spec_parser_rules ()
Public Attributes
parse::detail::item_spec_parser_rule start
Constructor & Destructor Documentation
anonymous_namespace{Parse.cpp}::item_spec_parser_rules::item_spec_parser_rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), parse::detail::label(), parse::lexer::string, and parse::unlockable_item_type_enum().
Member Data Documentation
parse::detail::item_spec_parser_rule anonymous_namespace{Parse.cpp}::item_spec_parser_rules::start
The documentation for this struct was generated from the following file:
Parse.cpp