FreeOrion: FightersDestroyedEvent Struct Reference
FightersDestroyedEvent Struct Reference
FightersDestroyedEvent aggregates all the fighters destroyed during one combat bout.
#include <CombatEvents.h>
Public Member Functions
FightersDestroyedEvent ()
FightersDestroyedEvent (int bout)
void AddEvent (int target_empire_)
std::string CombatLogDescription (int viewing_empire_id) const override
Generate the combat log description.
std::string DebugString () const override
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
Return true if there are no details;.
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
Return true if there are no sub events;.
virtual std::string CombatLogDetails (int viewing_empire_id) const
Generate the combat log details.
virtual bool FlattenSubEvents () const
Return true if sub events are to be flattened on display;.
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
Return principal faction.
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int bout = 0
std::map< int, unsigned int > events
Friends
class boost::serialization::access
Detailed Description
FightersDestroyedEvent aggregates all the fighters destroyed during one combat bout.
Constructor & Destructor Documentation
FightersDestroyedEvent() [1/2]
FightersDestroyedEvent::FightersDestroyedEvent () explicit
FightersDestroyedEvent() [2/2]
FightersDestroyedEvent::FightersDestroyedEvent (int bout) explicit
Member Function Documentation
AddEvent()
void FightersDestroyedEvent::AddEvent (int target_empire_)
References events.
CombatLogDescription()
std::string FightersDestroyedEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description.
Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References ALL_EMPIRES, anonymous_namespace{CombatEvents.cpp}::EmpireLink(), events, anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormat(), INVALID_OBJECT_ID, to_string(), and UserString().
DebugString()
std::string FightersDestroyedEvent::DebugString () const override virtual
Implements CombatEvent.
References events.
serialize()
template<typename Archive > template void FightersDestroyedEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), bout, events, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
bout
int FightersDestroyedEvent::bout = 0 private
Referenced by serialize().
events
std::map<int, unsigned int> FightersDestroyedEvent::events private
Referenced by AddEvent(), CombatLogDescription(), DebugString(), and serialize().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp