FreeOrion: FightersAttackFightersEvent Struct Reference
FightersAttackFightersEvent Struct Reference
#include <CombatEvents.h>
Public Member Functions
FightersAttackFightersEvent ()
FightersAttackFightersEvent (int bout)
virtual ~FightersAttackFightersEvent ()
void AddEvent (int attacker_empire_, int target_empire_)
std::string CombatLogDescription (int viewing_empire_id) const override
std::string DebugString () const override
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
virtual std::string CombatLogDetails (int viewing_empire_id) const
virtual bool FlattenSubEvents () const
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int bout
std::map< std::pair< int, int >, unsigned int > events
Friends
class boost::serialization::access
Detailed Description
FightersAttackFightersEvent aggregates all the fighter on fighter combat for one bout.
Constructor & Destructor Documentation
FightersAttackFightersEvent::FightersAttackFightersEvent ()
FightersAttackFightersEvent::FightersAttackFightersEvent (int bout)
virtual FightersAttackFightersEvent::~FightersAttackFightersEvent () inline virtual
Member Function Documentation
void FightersAttackFightersEvent::AddEvent (int attacker_empire_, int target_empire_)
References events.
std::string FightersAttackFightersEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description. Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References ALL_EMPIRES, events, anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormat(), INVALID_OBJECT_ID, to_string(), and UserString().
std::string FightersAttackFightersEvent::DebugString () const override virtual
Implements CombatEvent.
References events.
template<class Archive > template void FightersAttackFightersEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), bout, and events.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
int FightersAttackFightersEvent::bout private
Referenced by serialize().
std::map<std::pair<int, int>, unsigned int> FightersAttackFightersEvent::events private
Referenced by AddEvent(), CombatLogDescription(), DebugString(), and serialize().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp