FreeOrion: Condition::CombatTarget Struct Reference
Condition::CombatTarget Struct Reference final
Matches objects that match the combat targeting condition of the specified content.
#include <Conditions.h>
Public Member Functions
CombatTarget (ContentType content_type, std::unique_ptr< ValueRef::ValueRef< std::string >> &&name)
std::unique_ptr< Condition > Clone () const override
Makes a clone of this Condition in a new owning pointer.
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Condition::Condition
Condition ()=default
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
ContentType m_content_type
std::unique_ptr< ValueRef::ValueRef< std::string > > m_name
Additional Inherited Members
Protected Member Functions inherited from Condition::Condition
Condition (const Condition &rhs)=default
Copies invariants from other Condition.
Condition (Condition &&rhs)=delete
Condition & operator= (const Condition &rhs)=delete
Condition & operator= (Condition &&rhs)=delete
Protected Attributes inherited from Condition::Condition
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
Matches objects that match the combat targeting condition of the specified content.
Constructor & Destructor Documentation
CombatTarget()
Condition::CombatTarget::CombatTarget (ContentType content_type, std::unique_ptr< ValueRef::ValueRef< std::string >> && name)
References m_name, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, and Condition::Condition::m_target_invariant.
Member Function Documentation
Clone()
std::unique_ptr< Condition > Condition::CombatTarget::Clone () const override virtual
Makes a clone of this Condition in a new owning pointer.
Required for Boost.Python, which doesn't support move semantics for returned values.
Implements Condition::Condition.
References ValueRef::CloneUnique(), m_content_type, and m_name.
Description()
std::string Condition::CombatTarget::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), Condition::anonymous_namespace{Conditions.cpp}::GetContentTypeName(), m_content_type, m_name, and UserString().
Dump()
std::string Condition::CombatTarget::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, DumpIndent(), m_content_type, and m_name.
Eval()
void Condition::CombatTarget::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), m_content_type, m_name, Condition::MATCHES, and Condition::Condition::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::CombatTarget::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_content_type, m_name, and TraceLogger.
Match()
bool Condition::CombatTarget::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, Condition::anonymous_namespace{Conditions.cpp}::GetCombatTargetCondition(), m_content_type, and m_name.
operator==()
bool Condition::CombatTarget::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, m_content_type, and m_name.
SetTopLevelContent()
void Condition::CombatTarget::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_name.
Member Data Documentation
m_content_type
ContentType Condition::CombatTarget::m_content_type private
Referenced by Clone(), Description(), Dump(), Eval(), GetCheckSum(), Match(), and operator==().
m_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Condition::CombatTarget::m_name private
Referenced by Clone(), CombatTarget(), Description(), Dump(), Eval(), GetCheckSum(), Match(), operator==(), and SetTopLevelContent().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp