FreeOrion: Condition::EmpireMeterValue Struct Reference
Condition::EmpireMeterValue Struct Reference
#include <Condition.h>
Public Member Functions
EmpireMeterValue (const std::string &meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
EmpireMeterValue (ValueRef::ValueRefBase< int > *empire_id, const std::string &meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
virtual ~EmpireMeterValue ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual unsigned int GetCheckSum () const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
ValueRef::ValueRefBase< int > * m_empire_id
ValueRef::ValueRefBase< double > * m_high
ValueRef::ValueRefBase< double > * m_low
const std::string m_meter
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects if the empire with id empire_id has an empire meter meter whose current value is >= low and <= high.
Constructor & Destructor Documentation
Condition::EmpireMeterValue::EmpireMeterValue (const std::string & meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Condition::EmpireMeterValue::EmpireMeterValue (ValueRef::ValueRefBase< int > * empire_id, const std::string & meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::EmpireMeterValue::~EmpireMeterValue () virtual
References Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
Member Function Documentation
std::string Condition::EmpireMeterValue::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ALL_EMPIRES, ValueRef::ValueRefBase< T >::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), GetEmpire(), Meter::LARGE_VALUE, Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, to_string(), and UserString().
std::string Condition::EmpireMeterValue::Dump () const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
void Condition::EmpireMeterValue::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), Meter::LARGE_VALUE, ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::RootCandidateInvariant().
bool Condition::EmpireMeterValue::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ALL_EMPIRES, ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Meter::LARGE_VALUE, Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
bool Condition::EmpireMeterValue::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, Condition::Enqueued::m_empire_id, m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and m_meter.
bool Condition::EmpireMeterValue::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
void Condition::EmpireMeterValue::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::EmpireMeterValue::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::EmpireMeterValue::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::TargetInvariant().
Member Data Documentation
ValueRef::ValueRefBase<int>* Condition::EmpireMeterValue::m_empire_id private
Referenced by operator==().
ValueRef::ValueRefBase<double>* Condition::EmpireMeterValue::m_high private
ValueRef::ValueRefBase<double>* Condition::EmpireMeterValue::m_low private
const std::string Condition::EmpireMeterValue::m_meter private
Referenced by operator==().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp