FreeOrion: ProcessingTurn Struct Reference
ProcessingTurn Struct Reference
The substate of PlayingGame in which the server has received turn orders from players and is determining what happens between turns.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::custom_reaction< ProcessTurn >, sc::deferral< SaveGameRequest >, sc::deferral< TurnOrders >, sc::deferral< TurnPartialOrders >, sc::deferral< RevokeReadiness >, sc::deferral< Diplomacy >, sc::custom_reaction< CheckTurnEndConditions > > reactions
Public Member Functions
ProcessingTurn (my_context c)
~ProcessingTurn ()
sc::result react (const ProcessTurn &u)
sc::result react (const CheckTurnEndConditions &c)
Public Attributes
std::chrono::high_resolution_clock::time_point m_start
Detailed Description
The substate of PlayingGame in which the server has received turn orders from players and is determining what happens between turns.
This includes executing orders, resolving combat, various steps in determining what happens before and after combats occur, and updating players on changes in the Universe.
Member Typedef Documentation
reactions
typedef boost::mpl::list< sc::custom_reaction<ProcessTurn>, sc::deferral<SaveGameRequest>, sc::deferral<TurnOrders>, sc::deferral<TurnPartialOrders>, sc::deferral<RevokeReadiness>, sc::deferral<Diplomacy>, sc::custom_reaction<CheckTurnEndConditions> > ProcessingTurn::reactions
Constructor & Destructor Documentation
ProcessingTurn()
ProcessingTurn::ProcessingTurn (my_context c)
References DebugLogger, m_start, and TraceLogger.
~ProcessingTurn()
ProcessingTurn::~ProcessingTurn ()
References TraceLogger.
Member Function Documentation
react() [1/2]
sc::result ProcessingTurn::react (const ProcessTurn & u)
References ServerApp::CurrentTurn(), ServerApp::Empires(), ServerNetworking::established_begin(), ServerNetworking::established_end(), OptionsDB::Get(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), GetOptionsDB(), HostSaveGameInitiateMessage(), ServerApp::IsHostless(), ServerApp::m_networking, PlayerStatusMessage(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), ServerApp::ProcessCombats(), ServerApp::SetAIsProcessPriorityToLow(), and TraceLogger.
react() [2/2]
sc::result ProcessingTurn::react (const CheckTurnEndConditions & c)
References TraceLogger.
Member Data Documentation
m_start
std::chrono::high_resolution_clock::time_point ProcessingTurn::m_start
Referenced by ProcessingTurn().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp