FreeOrion: Condition::ObjectID Struct Reference
Condition::ObjectID Struct Reference final
Matches the object with the id object_id.
#include <Conditions.h>
Public Member Functions
ObjectID (std::unique_ptr< ValueRef::ValueRef< int >> &&object_id)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_object_id
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches the object with the id object_id.
Constructor & Destructor Documentation
ObjectID()
Condition::ObjectID::ObjectID (std::unique_ptr< ValueRef::ValueRef< int >> && object_id)
Member Function Documentation
Description()
std::string Condition::ObjectID::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), INVALID_OBJECT_ID, m_object_id, Objects(), and UserString().
Dump()
std::string Condition::ObjectID::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_object_id.
Eval()
void Condition::ObjectID::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), INVALID_OBJECT_ID, m_object_id, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::ObjectID::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_object_id, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::ObjectID::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References anonymous_namespace{Conditions.cpp}::AddAllObjectsSet(), ScriptingContext::condition_root_candidate, ObjectMap::ExistingObject(), INVALID_OBJECT_ID, m_object_id, Objects(), and RootCandidateInvariant().
Match()
bool Condition::ObjectID::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, and m_object_id.
operator==()
bool Condition::ObjectID::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_object_id.
RootCandidateInvariant()
bool Condition::ObjectID::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
References m_object_id.
Referenced by Eval(), and GetDefaultInitialCandidateObjects().
serialize()
template<class Archive > void Condition::ObjectID::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::ObjectID::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_object_id.
SourceInvariant()
bool Condition::ObjectID::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References m_object_id.
TargetInvariant()
bool Condition::ObjectID::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References m_object_id.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_object_id
std::unique_ptr<ValueRef::ValueRef<int> > Condition::ObjectID::m_object_id private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), GetDefaultInitialCandidateObjects(), Match(), Condition::anonymous_namespace{Conditions.cpp}::ObjectIDSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp