FreeOrion: StealthChangeEvent Struct Reference
StealthChangeEvent Struct Reference
StealthChangeEvent describes changes in the visibility of objects during combat.
#include <CombatEvents.h>
Classes
struct StealthChangeEventDetail
Public Types
typedef std::shared_ptr< const StealthChangeEventDetail > ConstStealthChangeEventDetailPtr
typedef std::shared_ptr< StealthChangeEventDetail > StealthChangeEventDetailPtr
Public Member Functions
StealthChangeEvent ()
StealthChangeEvent (int bout)
void AddEvent (int attacker_id_, int target_id_, int attacker_empire_, int target_empire_, Visibility new_visibility_)
bool AreSubEventsEmpty (int viewing_empire_id) const override
Return true if there are no sub events;.
std::string CombatLogDescription (int viewing_empire_id) const override
Generate the combat log description.
std::string DebugString () const override
std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const override
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
Return true if there are no details;.
virtual std::string CombatLogDetails (int viewing_empire_id) const
Generate the combat log details.
virtual bool FlattenSubEvents () const
Return true if sub events are to be flattened on display;.
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
Return principal faction.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int bout = 0
std::map< int, std::vector< StealthChangeEventDetailPtr > > events
Friends
class boost::serialization::access
Detailed Description
StealthChangeEvent describes changes in the visibility of objects during combat.
At this time always decloaking.
Member Typedef Documentation
ConstStealthChangeEventDetailPtr
typedef std::shared_ptr<const StealthChangeEventDetail> StealthChangeEvent::ConstStealthChangeEventDetailPtr
StealthChangeEventDetailPtr
typedef std::shared_ptr<StealthChangeEventDetail> StealthChangeEvent::StealthChangeEventDetailPtr
Constructor & Destructor Documentation
StealthChangeEvent() [1/2]
StealthChangeEvent::StealthChangeEvent () explicit
StealthChangeEvent() [2/2]
StealthChangeEvent::StealthChangeEvent (int bout) explicit
Member Function Documentation
AddEvent()
void StealthChangeEvent::AddEvent (int attacker_id_, int target_id_, int attacker_empire_, int target_empire_, Visibility new_visibility_)
References events.
AreSubEventsEmpty()
bool StealthChangeEvent::AreSubEventsEmpty (int viewing_empire_id) const override virtual
Return true if there are no sub events;.
Reimplemented from CombatEvent.
References events.
CombatLogDescription()
std::string StealthChangeEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description.
Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References anonymous_namespace{CombatEvents.cpp}::EmpireLink(), events, anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormatList(), and UserString().
DebugString()
std::string StealthChangeEvent::DebugString () const override virtual
Implements CombatEvent.
References anonymous_namespace{CombatEvents.cpp}::EmpireLink(), and events.
serialize()
template<typename Archive > template void StealthChangeEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), bout, and events.
SubEvents()
std::vector< ConstCombatEventPtr > StealthChangeEvent::SubEvents (int viewing_empire_id) const override virtual
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Reimplemented from CombatEvent.
References events.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
bout
int StealthChangeEvent::bout = 0 private
Referenced by serialize().
events
std::map<int, std::vector<StealthChangeEventDetailPtr> > StealthChangeEvent::events private
Referenced by AddEvent(), AreSubEventsEmpty(), CombatLogDescription(), DebugString(), serialize(), and SubEvents().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp