FreeOrion: VisibilityChangeEvent Struct Reference
VisibilityChangeEvent Struct Reference
#include <CombatEvents.h>
Classes
struct VisibilityChangeEventDetail
Public Types
typedef std::shared_ptr< const VisibilityChangeEventDetail > ConstVisibilityChangeEventDetailPtr
typedef std::shared_ptr< VisibilityChangeEventDetail > VisibilityChangeEventDetailPtr
Public Member Functions
VisibilityChangeEvent ()
VisibilityChangeEvent (int bout)
virtual ~VisibilityChangeEvent ()
void AddEvent (int object_id_, int detector_empire_id_, Visibility new_visibility_)
bool AreSubEventsEmpty (int viewing_empire_id) const override
std::string CombatLogDescription (int viewing_empire_id) const override
std::string DebugString () const override
std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const override
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
virtual std::string CombatLogDetails (int viewing_empire_id) const
virtual bool FlattenSubEvents () const
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int bout = -1
std::map< int, std::vector< VisibilityChangeEventDetailPtr > > events
Friends
class boost::serialization::access
Detailed Description
VisibilityChangeEvent describes changes in the visibility of objects during combat.
Member Typedef Documentation
typedef std::shared_ptr<const VisibilityChangeEventDetail> VisibilityChangeEvent::ConstVisibilityChangeEventDetailPtr
typedef std::shared_ptr<VisibilityChangeEventDetail> VisibilityChangeEvent::VisibilityChangeEventDetailPtr
Constructor & Destructor Documentation
VisibilityChangeEvent::VisibilityChangeEvent ()
VisibilityChangeEvent::VisibilityChangeEvent (int bout)
virtual VisibilityChangeEvent::~VisibilityChangeEvent () inline virtual
References CombatEvent::AreSubEventsEmpty(), CombatEvent::CombatLogDescription(), CombatEvent::DebugString(), and CombatEvent::SubEvents().
Member Function Documentation
void VisibilityChangeEvent::AddEvent (int object_id_, int detector_empire_id_, Visibility new_visibility_)
References events.
bool VisibilityChangeEvent::AreSubEventsEmpty (int viewing_empire_id) const override virtual
Return true if there are no sub events;
Reimplemented from CombatEvent.
References events.
std::string VisibilityChangeEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description. Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References ALL_EMPIRES, anonymous_namespace{CombatEvents.cpp}::EmpireLink(), events, anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormatList(), and UserString().
std::string VisibilityChangeEvent::DebugString () const override virtual
Implements CombatEvent.
References anonymous_namespace{CombatEvents.cpp}::EmpireLink(), and events.
template<class Archive > template void VisibilityChangeEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), bout, and events.
std::vector< ConstCombatEventPtr > VisibilityChangeEvent::SubEvents (int viewing_empire_id) const override virtual
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Reimplemented from CombatEvent.
References events.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
int VisibilityChangeEvent::bout = -1 private
Referenced by serialize().
std::map<int, std::vector<VisibilityChangeEventDetailPtr> > VisibilityChangeEvent::events private
Referenced by AddEvent(), AreSubEventsEmpty(), CombatLogDescription(), DebugString(), serialize(), and SubEvents().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp