FreeOrion: WaitingForTurnEnd Struct Reference
WaitingForTurnEnd Struct Reference
The substate of PlayingGame in which players are playing their turns and the server is waiting for all players to finish their moves, after which the server will process the turn.
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::custom_reaction< TurnOrders >, sc::custom_reaction< TurnPartialOrders >, sc::custom_reaction< RevokeReadiness >, sc::custom_reaction< CheckTurnEndConditions >, sc::custom_reaction< SaveGameRequest > > reactions
Public Member Functions
WaitingForTurnEnd (my_context c)
~WaitingForTurnEnd ()
sc::result react (const TurnOrders &msg)
sc::result react (const TurnPartialOrders &msg)
sc::result react (const RevokeReadiness &msg)
sc::result react (const CheckTurnEndConditions &c)
sc::result react (const SaveGameRequest &msg)
void SaveTimedoutHandler (const boost::system::error_code &error)
Public Attributes
std::string m_save_filename
boost::asio::high_resolution_timer m_timeout
Detailed Description
The substate of PlayingGame in which players are playing their turns and the server is waiting for all players to finish their moves, after which the server will process the turn.
Member Typedef Documentation
reactions
typedef boost::mpl::list< sc::custom_reaction<TurnOrders>, sc::custom_reaction<TurnPartialOrders>, sc::custom_reaction<RevokeReadiness>, sc::custom_reaction<CheckTurnEndConditions>, sc::custom_reaction<SaveGameRequest> > WaitingForTurnEnd::reactions
Constructor & Destructor Documentation
WaitingForTurnEnd()
WaitingForTurnEnd::WaitingForTurnEnd (my_context c)
References OptionsDB::Get(), GetOptionsDB(), m_timeout, SaveTimedoutHandler(), TraceLogger, PlayingGame::TurnTimedoutHandler(), and TurnTimeoutMessage().
~WaitingForTurnEnd()
WaitingForTurnEnd::~WaitingForTurnEnd ()
References m_timeout, and TraceLogger.
Member Function Documentation
react() [1/5]
sc::result WaitingForTurnEnd::react (const TurnOrders & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerNetworking::Disconnect(), Empire::EmpireID(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ExtractTurnOrdersMessageData(), GetEmpire(), Networking::INVALID_CLIENT_TYPE, ServerApp::IsLocalHumanPlayer(), ServerApp::m_networking, ServerApp::Networking(), ServerApp::PlayerEmpireID(), Empire::PlayerName(), PlayerStatusMessage(), ServerApp::SetAIsProcessPriorityToLow(), ServerApp::SetEmpireSaveGameData(), TraceLogger, TurnProgressMessage(), UserStringNop, and Message::WAITING_FOR_PLAYERS.
react() [2/5]
sc::result WaitingForTurnEnd::react (const TurnPartialOrders & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, ServerNetworking::Disconnect(), Empire::EmpireID(), ErrorLogger, ErrorMessage(), ExtractTurnPartialOrdersMessageData(), GetEmpire(), Networking::INVALID_CLIENT_TYPE, ServerApp::Networking(), ServerApp::PlayerEmpireID(), Empire::PlayerName(), TraceLogger, ServerApp::UpdatePartialOrders(), and UserStringNop.
react() [3/5]
sc::result WaitingForTurnEnd::react (const RevokeReadiness & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, Empire::EmpireID(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), GetEmpire(), ServerApp::m_networking, ServerApp::PlayerEmpireID(), PlayerStatusMessage(), ServerApp::RevokeEmpireTurnReadyness(), TraceLogger, and UserStringNop.
react() [4/5]
sc::result WaitingForTurnEnd::react (const CheckTurnEndConditions & c)
References ServerApp::AllOrdersReceived(), OptionsDB::Get(), GetOptionsDB(), ServerApp::IsTurnExpired(), ServerApp::m_networking, ServerNetworking::ModeratorsInGame(), and TraceLogger.
react() [5/5]
sc::result WaitingForTurnEnd::react (const SaveGameRequest & msg)
References Empires(), error, ErrorLogger, ErrorMessage(), GetCombatLogManager(), ServerApp::GetPlayerSaveGameData(), GetSpeciesManager(), GetUniverse(), ServerApp::m_current_turn, ServerApp::m_galaxy_setup_data, ServerApp::m_networking, ServerApp::m_single_player_game, ServerNetworking::PlayerIsHost(), SaveGame(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerSaveGameCompleteMessage(), Message::Text(), TraceLogger, and UserStringNop.
SaveTimedoutHandler()
void WaitingForTurnEnd::SaveTimedoutHandler (const boost::system::error_code & error)
References CurrentTurn(), DebugLogger, anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), GetOptionsDB(), HostSaveGameInitiateMessage(), and m_timeout.
Referenced by WaitingForTurnEnd().
Member Data Documentation
m_save_filename
std::string WaitingForTurnEnd::m_save_filename
m_timeout
boost::asio::high_resolution_timer WaitingForTurnEnd::m_timeout
Referenced by SaveTimedoutHandler(), WaitingForTurnEnd(), and ~WaitingForTurnEnd().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp