FreeOrion: Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch Struct Reference
Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch Struct Reference
Public Member Functions
EmpireMeterValueSimpleMatch (int empire_id, float low, float high, const std::string &meter)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
int m_empire_id
float m_high
float m_low
std::string m_meter
Constructor & Destructor Documentation
EmpireMeterValueSimpleMatch()
Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::EmpireMeterValueSimpleMatch (int empire_id, float low, float high, const std::string & meter) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References Meter::Current(), GetEmpire(), Empire::GetMeter(), Condition::EmpireMeterValue::m_empire_id, Condition::EmpireMeterValue::m_high, Condition::EmpireMeterValue::m_low, and Condition::EmpireMeterValue::m_meter.
Member Data Documentation
m_empire_id
int Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::m_empire_id
m_high
float Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::m_high
m_low
float Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::m_low
m_meter
std::string Condition::anonymous_namespace{Conditions.cpp}::EmpireMeterValueSimpleMatch::m_meter
The documentation for this struct was generated from the following file:
Conditions.cpp