FreeOrion: ValueRef::StaticCast< FromType, ToType > Struct Template Reference
ValueRef::StaticCast< FromType, ToType > Struct Template Reference
#include <ValueRefFwd.h>
Public Member Functions
StaticCast (Variable< FromType > *value_ref)
StaticCast (ValueRefBase< FromType > *value_ref)
~StaticCast ()
std::string Description () const override
std::string Dump () const override
ToType Eval (const ScriptingContext &context) const override
const ValueRefBase< FromType > * GetValueRef () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRefBase< ToType > &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::Variable< ToType >
Variable (ReferenceType ref_type, const std::string &property_name="")
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name)
std::string Description () const override
std::string Dump () const override
ToType Eval (const ScriptingContext &context) const override
ReferenceType GetReferenceType () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRefBase< ToType > &rhs) const override
const std::vector< std::string > & PropertyName () const
bool RootCandidateInvariant () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRefBase< T >
virtual ~ValueRefBase ()
virtual bool ConstantExpr () const
T Eval () const
virtual unsigned int GetCheckSum () const
bool operator!= (const ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRefBase< T > &rhs) const
virtual bool SimpleIncrement () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRefBase< FromType > * m_value_ref
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from ValueRef::Variable< ToType >
std::vector< std::string > m_property_name
ReferenceType m_ref_type
Detailed Description
template<class FromType, class ToType>
struct ValueRef::StaticCast< FromType, ToType >
The variable static_cast class. The value returned by this node is taken from the ctor value_ref parameter's FromType value, static_cast to ToType.
Constructor & Destructor Documentation
template<class FromType , class ToType > ValueRef::StaticCast< FromType, ToType >::StaticCast (Variable< FromType > * value_ref)
template<class FromType , class ToType > ValueRef::StaticCast< FromType, ToType >::StaticCast (ValueRefBase< FromType > * value_ref)
template<class FromType , class ToType > ValueRef::StaticCast< FromType, ToType >::~StaticCast ()
References ValueRef::StaticCast< FromType, ToType >::m_value_ref.
Member Function Documentation
template<class FromType , class ToType > std::string ValueRef::StaticCast< FromType, ToType >::Description () const override virtual
Implements ValueRef::ValueRefBase< T >.
References ValueRef::ValueRefBase< T >::Description(), and ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType , class ToType > std::string ValueRef::StaticCast< FromType, ToType >::Dump () const override virtual
Returns a text description of this type of special.
Implements ValueRef::ValueRefBase< T >.
References ValueRef::ValueRefBase< T >::Dump(), and ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType , class ToType > ToType ValueRef::StaticCast< FromType, ToType >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRefBase< T >.
References ValueRef::ValueRefBase< T >::Eval(), and ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType, class ToType> const ValueRefBase<FromType>* ValueRef::StaticCast< FromType, ToType >::GetValueRef () const inline
template<class FromType , class ToType > bool ValueRef::StaticCast< FromType, ToType >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), and ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType , class ToType > bool ValueRef::StaticCast< FromType, ToType >::operator== (const ValueRefBase< ToType > & rhs) const override
References ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType , class ToType > bool ValueRef::StaticCast< FromType, ToType >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::StaticCast< FromType, ToType >::m_value_ref, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
template<class FromType , class ToType > template<class Archive > void ValueRef::StaticCast< FromType, ToType >::serialize (Archive & ar, const unsigned int version) private
References ValueRef::StaticCast< FromType, ToType >::m_value_ref.
template<class FromType , class ToType > void ValueRef::StaticCast< FromType, ToType >::SetTopLevelContent (const std::string & content_name) override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::StaticCast< FromType, ToType >::m_value_ref, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
template<class FromType , class ToType > bool ValueRef::StaticCast< FromType, ToType >::SourceInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::StaticCast< FromType, ToType >::m_value_ref, and ValueRef::ValueRefBase< T >::SourceInvariant().
template<class FromType , class ToType > bool ValueRef::StaticCast< FromType, ToType >::TargetInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::StaticCast< FromType, ToType >::m_value_ref, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
template<class FromType, class ToType> friend class boost::serialization::access friend
Member Data Documentation
template<class FromType, class ToType> ValueRefBase<FromType>* ValueRef::StaticCast< FromType, ToType >::m_value_ref private
Referenced by ValueRef::StaticCast< FromType, ToType >::Description(), ValueRef::StaticCast< FromType, ToType >::Dump(), ValueRef::StaticCast< FromType, ToType >::Eval(), ValueRef::StaticCast< FromType, ToType >::LocalCandidateInvariant(), ValueRef::StaticCast< FromType, ToType >::operator==(), ValueRef::StaticCast< FromType, ToType >::RootCandidateInvariant(), ValueRef::StaticCast< FromType, ToType >::serialize(), ValueRef::StaticCast< FromType, ToType >::SetTopLevelContent(), ValueRef::StaticCast< FromType, ToType >::SourceInvariant(), ValueRef::StaticCast< FromType, ToType >::TargetInvariant(), and ValueRef::StaticCast< FromType, ToType >::~StaticCast().
The documentation for this struct was generated from the following file:
ValueRef.h