FreeOrion: ValueRef::Variable< T > Struct Template Reference
ValueRef::Variable< T > Struct Template Reference
The variable value ValueRef class.
#include <ValueRefs.h>
Public Member Functions
Variable (ReferenceType ref_type, const std::string &property_name="", bool return_immediate_value=false)
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const boost::optional< std::string > &container_name, const std::string &property_name, bool return_immediate_value=false)
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a text description of this type of special.
T Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
ReferenceType GetReferenceType () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRef< T > &rhs) const override
const std::vector< std::string > & PropertyName () const
bool ReturnImmediateValue () const
bool RootCandidateInvariant () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRef< T >
virtual ~ValueRef ()
virtual bool ConstantExpr () const
T Eval () const
Evaluates the expression tree with an empty context.
bool operator!= (const ValueRef< T > &rhs) const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SimpleIncrement () const
Protected Attributes
std::vector< std::string > m_property_name
ReferenceType m_ref_type = INVALID_REFERENCE_TYPE
bool m_return_immediate_value = false
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
template<class T>
struct ValueRef::Variable< T >
The variable value ValueRef class.
The value returned by this node is taken from the gamestate, most often from the Source or Target objects.
Constructor & Destructor Documentation
Variable() [1/3]
template<class T > ValueRef::Variable< T >::Variable (ReferenceType ref_type, const std::string & property_name = "", bool return_immediate_value = false) explicit
Variable() [2/3]
template<class T > ValueRef::Variable< T >::Variable (ReferenceType ref_type, const std::vector< std::string > & property_name, bool return_immediate_value = false)
Variable() [3/3]
template<class T > ValueRef::Variable< T >::Variable (ReferenceType ref_type, const boost::optional< std::string > & container_name, const std::string & property_name, bool return_immediate_value = false)
Member Function Documentation
Description()
template<class T > std::string ValueRef::Variable< T >::Description () const override virtual
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Referenced by ValueRef::Statistic< T >::Description().
Dump()
template<class T > std::string ValueRef::Variable< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a text description of this type of special.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Eval() [1/21]
template<class T> T ValueRef::Variable< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Eval() [2/21]
template<> PlanetSize ValueRef::Variable< PlanetSize >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [3/21]
template<> PlanetType ValueRef::Variable< PlanetType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [4/21]
template<> PlanetEnvironment ValueRef::Variable< PlanetEnvironment >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [5/21]
template<> UniverseObjectType ValueRef::Variable< UniverseObjectType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [6/21]
template<> FO_COMMON_API PlanetSize ValueRef::Variable< PlanetSize >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [7/21]
template<> FO_COMMON_API PlanetType ValueRef::Variable< PlanetType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [8/21]
template<> FO_COMMON_API PlanetEnvironment ValueRef::Variable< PlanetEnvironment >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [9/21]
template<> FO_COMMON_API UniverseObjectType ValueRef::Variable< UniverseObjectType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [10/21]
template<> FO_COMMON_API StarType ValueRef::Variable< StarType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [11/21]
template<> FO_COMMON_API Visibility ValueRef::Variable< Visibility >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [12/21]
template<> FO_COMMON_API double ValueRef::Variable< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [13/21]
template<> FO_COMMON_API int ValueRef::Variable< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [14/21]
template<> FO_COMMON_API std::string ValueRef::Variable< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [15/21]
template<> FO_COMMON_API std::vector< std::string > ValueRef::Variable< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [16/21]
template<> StarType ValueRef::Variable< StarType >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [17/21]
template<> Visibility ValueRef::Variable< Visibility >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [18/21]
template<> double ValueRef::Variable< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [19/21]
template<> int ValueRef::Variable< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [20/21]
template<> std::vector< std::string > ValueRef::Variable< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
Eval() [21/21]
template<> std::string ValueRef::Variable< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::ComplexVariable< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, ValueRef::Statistic< T >, and ValueRef::Statistic< T >.
GetCheckSum()
template<class T > unsigned int ValueRef::Variable< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
GetReferenceType()
template<class T > ReferenceType ValueRef::Variable< T >::GetReferenceType () const
Referenced by ValueRef::Operation< T >::SimpleIncrement().
LocalCandidateInvariant()
template<class T > bool ValueRef::Variable< T >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Referenced by ValueRef::Statistic< T >::LocalCandidateInvariant().
operator==()
template<class T> bool ValueRef::Variable< T >::operator== (const ValueRef< T > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
PropertyName()
template<class T > const std::vector< std::string > & ValueRef::Variable< T >::PropertyName () const
ReturnImmediateValue()
template<class T > bool ValueRef::Variable< T >::ReturnImmediateValue () const
RootCandidateInvariant()
template<class T > bool ValueRef::Variable< T >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Referenced by ValueRef::Statistic< T >::RootCandidateInvariant(), and ValueRef::ComplexVariable< T >::RootCandidateInvariant().
serialize()
template<class T > template<class Archive > void ValueRef::Variable< T >::serialize (Archive & ar, const unsigned int version) private
SourceInvariant()
template<class T > bool ValueRef::Variable< T >::SourceInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Referenced by ValueRef::Statistic< T >::SourceInvariant().
TargetInvariant()
template<class T > bool ValueRef::Variable< T >::TargetInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< T >.
Reimplemented in ValueRef::ComplexVariable< T >, and ValueRef::Statistic< T >.
Referenced by ValueRef::Statistic< T >::TargetInvariant().
Friends And Related Function Documentation
boost::serialization::access
template<class T> friend class boost::serialization::access friend
Member Data Documentation
m_property_name
template<class T> std::vector<std::string> ValueRef::Variable< T >::m_property_name protected
Referenced by ValueRef::ComplexVariable< T >::Description(), ValueRef::ComplexVariable< T >::Dump(), ValueRef::Variable< ToType >::operator==(), and ValueRef::ComplexVariable< T >::operator==().
m_ref_type
template<class T> ReferenceType ValueRef::Variable< T >::m_ref_type = INVALID_REFERENCE_TYPE mutable protected
Referenced by ValueRef::Variable< ToType >::operator==().
m_return_immediate_value
template<class T> bool ValueRef::Variable< T >::m_return_immediate_value = false protected
Referenced by ValueRef::Variable< ToType >::operator==(), and ValueRef::ComplexVariable< T >::operator==().
The documentation for this struct was generated from the following file:
ValueRefs.h