FreeOrion: XMLDoc::RuleDefiner Struct Reference
XMLDoc::RuleDefiner Struct Reference
Creates the XML parsing rules at static initialization time.
Public Member Functions
RuleDefiner ()
Detailed Description
Creates the XML parsing rules at static initialization time.
Constructor & Destructor Documentation
RuleDefiner()
XMLDoc::RuleDefiner::RuleDefiner ()
References XMLDoc::AddAttribute(), XMLDoc::AppendToText(), anonymous_namespace{XMLDoc.cpp}::Attribute, anonymous_namespace{XMLDoc.cpp}::AttValue, anonymous_namespace{XMLDoc.cpp}::CData, anonymous_namespace{XMLDoc.cpp}::CDSect, anonymous_namespace{XMLDoc.cpp}::Char(), anonymous_namespace{XMLDoc.cpp}::CharData, anonymous_namespace{XMLDoc.cpp}::CharRef, anonymous_namespace{XMLDoc.cpp}::Comment, anonymous_namespace{XMLDoc.cpp}::Comment1, anonymous_namespace{XMLDoc.cpp}::content, anonymous_namespace{XMLDoc.cpp}::doctypedecl, anonymous_namespace{XMLDoc.cpp}::document, anonymous_namespace{XMLDoc.cpp}::element, anonymous_namespace{XMLDoc.cpp}::EmptyElemTag, anonymous_namespace{XMLDoc.cpp}::EncName, anonymous_namespace{XMLDoc.cpp}::EncodingDecl, anonymous_namespace{XMLDoc.cpp}::EntityRef, anonymous_namespace{XMLDoc.cpp}::Eq, anonymous_namespace{XMLDoc.cpp}::ETag, anonymous_namespace{XMLDoc.cpp}::Letter(), anonymous_namespace{XMLDoc.cpp}::Misc, anonymous_namespace{XMLDoc.cpp}::Name, anonymous_namespace{XMLDoc.cpp}::NameChar, XMLDoc::PopElem(), anonymous_namespace{XMLDoc.cpp}::prolog, XMLDoc::PushElem1(), XMLDoc::PushElem2(), anonymous_namespace{XMLDoc.cpp}::Reference, anonymous_namespace{XMLDoc.cpp}::S, anonymous_namespace{XMLDoc.cpp}::Sch(), anonymous_namespace{XMLDoc.cpp}::SDDecl, XMLDoc::SetAttributeName(), XMLDoc::SetElemName(), anonymous_namespace{XMLDoc.cpp}::STag, anonymous_namespace{XMLDoc.cpp}::VersionInfo, anonymous_namespace{XMLDoc.cpp}::VersionNum, and anonymous_namespace{XMLDoc.cpp}::XMLDecl.
The documentation for this struct was generated from the following files:
XMLDoc.h
XMLDoc.cpp