FreeOrion: anonymous_namespace{TechsParser.cpp}::py_grammar_techs Struct Reference
anonymous_namespace{TechsParser.cpp}::py_grammar_techs Struct Reference
Public Member Functions
py_grammar_techs (const PythonParser &parser, TechManager::TechContainer &techs)
boost::python::dict operator() () const
Public Attributes
boost::python::dict globals
const PythonParser & m_parser
TechManager::TechContainer & m_techs
Constructor & Destructor Documentation
py_grammar_techs()
anonymous_namespace{TechsParser.cpp}::py_grammar_techs::py_grammar_techs (const PythonParser & parser, TechManager::TechContainer & techs) inline
References tag_parser::args, ValueRef::EFFECT_TARGET_VALUE_REFERENCE, anonymous_namespace{TechsParser.cpp}::insert_contained_by_(), anonymous_namespace{TechsParser.cpp}::insert_contains_(), anonymous_namespace{TechsParser.cpp}::insert_effects_group_(), anonymous_namespace{TechsParser.cpp}::insert_game_rule_(), anonymous_namespace{TechsParser.cpp}::insert_generate_sit_rep_message_(), anonymous_namespace{TechsParser.cpp}::insert_has_tag_(), anonymous_namespace{TechsParser.cpp}::insert_item_(), anonymous_namespace{TechsParser.cpp}::insert_owned_by_(), anonymous_namespace{TechsParser.cpp}::insert_planet_(), anonymous_namespace{TechsParser.cpp}::insert_visible_to_empire_(), ValueRef::NON_OBJECT_REFERENCE, anonymous_namespace{TechsParser.cpp}::py_insert_tech_(), and parse::techs().
Member Function Documentation
operator()()
boost::python::dict anonymous_namespace{TechsParser.cpp}::py_grammar_techs::operator() () const inline
Member Data Documentation
globals
boost::python::dict anonymous_namespace{TechsParser.cpp}::py_grammar_techs::globals
m_parser
const PythonParser& anonymous_namespace{TechsParser.cpp}::py_grammar_techs::m_parser
Referenced by anonymous_namespace{TechsParser.cpp}::insert_game_rule_(), and anonymous_namespace{TechsParser.cpp}::insert_minmaxoneof_().
m_techs
TechManager::TechContainer& anonymous_namespace{TechsParser.cpp}::py_grammar_techs::m_techs
The documentation for this struct was generated from the following file:
TechsParser.cpp