FreeOrion: Condition::DesignHasHull Struct Reference
Condition::DesignHasHull Struct Reference final
Matches all ships whose ShipDesign has the hull specified by name.
#include <Conditions.h>
Public Member Functions
DesignHasHull (std::unique_ptr< ValueRef::ValueRef< std::string >> &&name)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRef< std::string > > m_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all ships whose ShipDesign has the hull specified by name.
Constructor & Destructor Documentation
DesignHasHull()
Condition::DesignHasHull::DesignHasHull (std::unique_ptr< ValueRef::ValueRef< std::string >> && name) explicit
Member Function Documentation
Description()
std::string Condition::DesignHasHull::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), m_name, UserString(), and UserStringExists().
Dump()
std::string Condition::DesignHasHull::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_name.
Eval()
void Condition::DesignHasHull::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), m_name, and RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::DesignHasHull::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_name, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::DesignHasHull::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References anonymous_namespace{Conditions.cpp}::AddShipSet(), and ScriptingContext::ContextObjects().
Match()
bool Condition::DesignHasHull::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, and m_name.
operator==()
bool Condition::DesignHasHull::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_name.
RootCandidateInvariant()
bool Condition::DesignHasHull::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
References m_name.
Referenced by Eval().
serialize()
template<typename Archive > void Condition::DesignHasHull::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::DesignHasHull::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_name.
SourceInvariant()
bool Condition::DesignHasHull::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References m_name.
TargetInvariant()
bool Condition::DesignHasHull::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References m_name.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Condition::DesignHasHull::m_name private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Conditions.cpp}::DesignHasHullSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp