FreeOrion: Condition::None Struct Reference
Condition::None Struct Reference final
Matches no objects.
#include <Condition.h>
Public Member Functions
None ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches no objects.
Currently only has an experimental use for efficient immediate rejection as the top-line condition. Essentially the entire point of this Condition is to provide the specialized GetDefaultInitialCandidateObjects()
Constructor & Destructor Documentation
None()
Condition::None::None () inline
References Condition::NON_MATCHES, and operator==().
Member Function Documentation
Description()
std::string Condition::None::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString().
Dump()
std::string Condition::None::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
Eval()
void Condition::None::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::MATCHES.
GetCheckSum()
unsigned int Condition::None::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::None::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const inline override virtual
Reimplemented from Condition::ConditionBase.
References Effect::Dump().
operator==()
bool Condition::None::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::operator==().
RootCandidateInvariant()
bool Condition::None::RootCandidateInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::None::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::None::SetTopLevelContent (const std::string & content_name) inline override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::None::SourceInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
TargetInvariant()
bool Condition::None::TargetInvariant () const inline override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp