FreeOrion: ValueRef::Constant< T > Struct Template Reference
ValueRef::Constant< T > Struct Template Reference final
the constant value leaf ValueRef class.
#include <ValueRefs.h>
Public Member Functions
Constant (T value)
std::unique_ptr< ValueRef< T > > Clone () const override
Makes a clone of this ValueRef in a new owning pointer.
bool ConstantExpr () const override
std::string Description () const override
template<>
std::string Description () const
template<>
std::string Description () const
template<>
std::string Description () const
template<>
FO_COMMON_API std::string Description () const
template<>
FO_COMMON_API std::string Description () const
template<>
FO_COMMON_API std::string Description () const
std::string Dump (unsigned short ntabs=0) const override
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
FO_COMMON_API std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
template<>
std::string Dump (unsigned short ntabs) const
Returns a textual representation of the evaluation result with an empty/default context.
T Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
bool operator== (const ValueRef< T > &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Returns a textual representation that should be parseable to recreate this ValueRef.
template<>
FO_COMMON_API void SetTopLevelContent (const std::string &content_name)
Returns a textual representation that should be parseable to recreate this ValueRef.
template<>
void SetTopLevelContent (const std::string &content_name)
Returns a textual representation that should be parseable to recreate this ValueRef.
T Value () const
Public Member Functions inherited from ValueRef::ValueRef< T >
ValueRef ()=default
virtual ~ValueRef ()=default
T Eval () const
Evaluates the expression tree with a default context.
std::string EvalAsString () const final
Evaluates the expression tree with an empty context and retuns the a string representation of the result value iff the result type is supported (currently std::string, int, float, double, enum).
bool operator!= (const ValueRef< T > &rhs) const
Public Member Functions inherited from ValueRef::ValueRefBase
ValueRefBase ()=default
virtual ~ValueRefBase ()=default
std::string InvariancePattern () const
virtual bool LocalCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Private Attributes
std::string m_top_level_content
T m_value
Additional Inherited Members
Protected Attributes inherited from ValueRef::ValueRefBase
bool m_local_candidate_invariant = false
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
template<typename T>
struct ValueRef::Constant< T >
the constant value leaf ValueRef class.
Constructor & Destructor Documentation
Constant()
template<typename T > ValueRef::Constant< T >::Constant (T value) explicit
References ValueRef::ValueRefBase::m_local_candidate_invariant, ValueRef::ValueRefBase::m_root_candidate_invariant, ValueRef::ValueRefBase::m_source_invariant, and ValueRef::ValueRefBase::m_target_invariant.
Member Function Documentation
Clone()
template<typename T> std::unique_ptr<ValueRef<T> > ValueRef::Constant< T >::Clone () const inline override virtual
Makes a clone of this ValueRef in a new owning pointer.
Required for Boost.Python, which doesn't supports move semantics for returned values.
Implements ValueRef::ValueRef< T >.
ConstantExpr()
template<typename T> bool ValueRef::Constant< T >::ConstantExpr () const inline override virtual
Reimplemented from ValueRef::ValueRefBase.
References Effect::Dump().
Description() [1/7]
template<typename T > std::string ValueRef::Constant< T >::Description () const override virtual
Implements ValueRef::ValueRefBase.
References ValueRef::Constant< T >::m_value, and UserString().
Referenced by ValueRef::Constant< T >::GetCheckSum().
Description() [2/7]
template<> std::string ValueRef::Constant< int >::Description () const virtual
Implements ValueRef::ValueRefBase.
References DoubleToString(), and to_string().
Description() [3/7]
template<> std::string ValueRef::Constant< double >::Description () const virtual
Implements ValueRef::ValueRefBase.
References DoubleToString().
Description() [4/7]
template<> std::string ValueRef::Constant< std::string >::Description () const virtual
Implements ValueRef::ValueRefBase.
Description() [5/7]
template<> FO_COMMON_API std::string ValueRef::Constant< int >::Description () const virtual
Implements ValueRef::ValueRefBase.
Description() [6/7]
template<> FO_COMMON_API std::string ValueRef::Constant< double >::Description () const virtual
Implements ValueRef::ValueRefBase.
Description() [7/7]
template<> FO_COMMON_API std::string ValueRef::Constant< std::string >::Description () const virtual
Implements ValueRef::ValueRefBase.
Dump() [1/19]
template<typename T> std::string ValueRef::Constant< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Referenced by ValueRef::Constant< T >::GetCheckSum().
Dump() [2/19]
template<> std::string ValueRef::Constant< PlanetSize >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [3/19]
template<> std::string ValueRef::Constant< PlanetType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [4/19]
template<> std::string ValueRef::Constant< PlanetEnvironment >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [5/19]
template<> std::string ValueRef::Constant< UniverseObjectType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [6/19]
template<> FO_COMMON_API std::string ValueRef::Constant< PlanetSize >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [7/19]
template<> FO_COMMON_API std::string ValueRef::Constant< PlanetType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [8/19]
template<> std::string ValueRef::Constant< StarType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [9/19]
template<> FO_COMMON_API std::string ValueRef::Constant< PlanetEnvironment >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [10/19]
template<> FO_COMMON_API std::string ValueRef::Constant< UniverseObjectType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [11/19]
template<> FO_COMMON_API std::string ValueRef::Constant< StarType >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [12/19]
template<> FO_COMMON_API std::string ValueRef::Constant< Visibility >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [13/19]
template<> FO_COMMON_API std::string ValueRef::Constant< double >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [14/19]
template<> std::string ValueRef::Constant< Visibility >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
References VIS_NO_VISIBILITY().
Dump() [15/19]
template<> FO_COMMON_API std::string ValueRef::Constant< int >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [16/19]
template<> FO_COMMON_API std::string ValueRef::Constant< std::string >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Dump() [17/19]
template<> std::string ValueRef::Constant< int >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
References to_string().
Dump() [18/19]
template<> std::string ValueRef::Constant< double >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
References to_string().
Dump() [19/19]
template<> std::string ValueRef::Constant< std::string >::Dump (unsigned short ntabs) const virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
Eval() [1/3]
template<typename T > T ValueRef::Constant< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
References ValueRef::Constant< T >::m_value.
Eval() [2/3]
template<> FO_COMMON_API std::string ValueRef::Constant< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
Eval() [3/3]
template<> std::string ValueRef::Constant< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
GetCheckSum()
template<typename T > unsigned int ValueRef::Constant< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References CheckSums::CheckSumCombine(), ValueRef::Constant< T >::Description(), ValueRef::Constant< T >::Dump(), ValueRef::ValueRef< T >::Eval(), FO_COMMON_API, ValueRef::Constant< T >::m_value, ValueRef::Constant< T >::SetTopLevelContent(), and TraceLogger.
operator==()
template<typename T > bool ValueRef::Constant< T >::operator== (const ValueRef< T > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::Constant< T >::m_top_level_content, and ValueRef::Constant< T >::m_value.
SetTopLevelContent() [1/3]
template<typename T > void ValueRef::Constant< T >::SetTopLevelContent (const std::string & content_name) override virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
Referenced by ValueRef::Constant< T >::GetCheckSum().
SetTopLevelContent() [2/3]
template<> FO_COMMON_API void ValueRef::Constant< std::string >::SetTopLevelContent (const std::string & content_name) virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
SetTopLevelContent() [3/3]
template<> void ValueRef::Constant< std::string >::SetTopLevelContent (const std::string & content_name) virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
References DebugLogger, and ErrorLogger.
Value()
template<typename T > T ValueRef::Constant< T >::Value () const
References ValueRef::Constant< T >::m_value.
Member Data Documentation
m_top_level_content
template<typename T> std::string ValueRef::Constant< T >::m_top_level_content private
Referenced by ValueRef::Constant< T >::operator==().
m_value
template<typename T> T ValueRef::Constant< T >::m_value private
Referenced by ValueRef::Constant< T >::Description(), ValueRef::Constant< T >::Eval(), ValueRef::Constant< T >::GetCheckSum(), ValueRef::Constant< T >::operator==(), and ValueRef::Constant< T >::Value().
The documentation for this struct was generated from the following file:
ValueRefs.h