FreeOrion: ValueRef::Statistic< T > Struct Template Reference
ValueRef::Statistic< T > Struct Template Reference
#include <ValueRefFwd.h>
Public Member Functions
Statistic (std::unique_ptr< ValueRefBase< T >> &&value_ref, StatisticType stat_type, std::unique_ptr< Condition::ConditionBase > &&sampling_condition)
~Statistic ()
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
T Eval (const ScriptingContext &context) const override
template<>
FO_COMMON_API double Eval (const ScriptingContext &context) const
template<>
FO_COMMON_API int Eval (const ScriptingContext &context) const
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
template<>
double Eval (const ScriptingContext &context) const
template<>
int Eval (const ScriptingContext &context) const
template<>
std::string Eval (const ScriptingContext &context) const
unsigned int GetCheckSum () const override
const Condition::ConditionBase * GetSamplingCondition () const
StatisticType GetStatisticType () const
const ValueRefBase< T > * GetValueRef () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRefBase< T > &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::Variable< T >
Variable (ReferenceType ref_type, const std::string &property_name="", bool return_immediate_value=false)
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const boost::optional< std::string > &container_name, const std::string &property_name, bool return_immediate_value=false)
ReferenceType GetReferenceType () const
const std::vector< std::string > & PropertyName () const
bool ReturnImmediateValue () const
Public Member Functions inherited from ValueRef::ValueRefBase< T >
virtual ~ValueRefBase ()
virtual bool ConstantExpr () const
T Eval () const
bool operator!= (const ValueRefBase< T > &rhs) const
virtual bool SimpleIncrement () const
Protected Member Functions
void GetConditionMatches (const ScriptingContext &context, Condition::ObjectSet &condition_targets, Condition::ConditionBase *condition) const
void GetObjectPropertyValues (const ScriptingContext &context, const Condition::ObjectSet &objects, std::map< std::shared_ptr< const UniverseObject >, T > &object_property_values) const
T ReduceData (const std::map< std::shared_ptr< const UniverseObject >, T > &object_property_values) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< Condition::ConditionBase > m_sampling_condition
StatisticType m_stat_type
std::unique_ptr< ValueRefBase< T > > m_value_ref
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from ValueRef::Variable< T >
std::vector< std::string > m_property_name
ReferenceType m_ref_type = INVALID_REFERENCE_TYPE
bool m_return_immediate_value = false
Detailed Description
template<class T>
struct ValueRef::Statistic< T >
The variable statistic class. The value returned by this node is computed from the general gamestate; the value of the indicated property_name is computed for each object that matches sampling_condition and the statistic indicated by stat_type is calculated from them and returned.
Constructor & Destructor Documentation
template<class T > ValueRef::Statistic< T >::Statistic (std::unique_ptr< ValueRefBase< T >> && value_ref, StatisticType stat_type, std::unique_ptr< Condition::ConditionBase > && sampling_condition)
template<class T > ValueRef::Statistic< T >::~Statistic ()
Member Function Documentation
template<class T > std::string ValueRef::Statistic< T >::Description () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::COUNT, ValueRef::Variable< T >::Description(), ValueRef::IF, ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_stat_type, ValueRef::Statistic< T >::m_value_ref, ValueRef::MAX, ValueRef::MEAN, ValueRef::MIN, ValueRef::MODE, ValueRef::PRODUCT, ValueRef::RMS, ValueRef::SPREAD, ValueRef::STDEV, ValueRef::SUM, ValueRef::UNIQUE_COUNT, and UserString().
Referenced by ValueRef::Statistic< T >::Dump().
template<class T > std::string ValueRef::Statistic< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a text description of this type of special.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::Description().
template<class T > T ValueRef::Statistic< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::GetConditionMatches(), ValueRef::Statistic< T >::GetObjectPropertyValues(), ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_stat_type, and ValueRef::MODE.
template<> FO_COMMON_API double ValueRef::Statistic< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
template<> FO_COMMON_API int ValueRef::Statistic< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
template<> FO_COMMON_API std::string ValueRef::Statistic< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
template<> double ValueRef::Statistic< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::COUNT, and ValueRef::IF.
template<> int ValueRef::Statistic< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::COUNT, and ValueRef::IF.
template<> std::string ValueRef::Statistic< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< T >.
References ValueRef::MODE.
template<class T > unsigned int ValueRef::Statistic< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::Variable< T >.
References CheckSums::CheckSumCombine(), ValueRef::ValueRefBase< T >::Eval(), FO_COMMON_API, ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_stat_type, ValueRef::Statistic< T >::m_value_ref, and TraceLogger.
template<class T > void ValueRef::Statistic< T >::GetConditionMatches (const ScriptingContext & context, Condition::ObjectSet & condition_targets, Condition::ConditionBase * condition) const protected
Gets the set of objects in the Universe that match the sampling condition.
References Condition::ConditionBase::Eval().
Referenced by ValueRef::Statistic< T >::Eval().
template<class T > void ValueRef::Statistic< T >::GetObjectPropertyValues (const ScriptingContext & context, const Condition::ObjectSet & objects, std::map< std::shared_ptr< const UniverseObject >, T > & object_property_values) const protected
Evaluates the property for the specified objects.
References ValueRef::Statistic< T >::m_value_ref.
Referenced by ValueRef::Statistic< T >::Eval().
template<class T> const Condition::ConditionBase* ValueRef::Statistic< T >::GetSamplingCondition () const inline
template<class T> StatisticType ValueRef::Statistic< T >::GetStatisticType () const inline
template<class T> const ValueRefBase<T>* ValueRef::Statistic< T >::GetValueRef () const inline
template<class T > bool ValueRef::Statistic< T >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Variable< T >::LocalCandidateInvariant(), and ValueRef::Statistic< T >::m_value_ref.
template<class T > bool ValueRef::Statistic< T >::operator== (const ValueRefBase< T > & rhs) const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_stat_type, and ValueRef::Statistic< T >::m_value_ref.
template<class T > T ValueRef::Statistic< T >::ReduceData (const std::map< std::shared_ptr< const UniverseObject >, T > & object_property_values) const protected
Computes the statistic from the specified set of property values.
References ValueRef::COUNT, ValueRef::IF, ValueRef::Statistic< T >::m_stat_type, ValueRef::MAX, ValueRef::MEAN, ValueRef::MIN, ValueRef::MODE, ValueRef::PRODUCT, ValueRef::RMS, ValueRef::SPREAD, ValueRef::STDEV, ValueRef::SUM, and ValueRef::UNIQUE_COUNT.
template<class T > bool ValueRef::Statistic< T >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_value_ref, and ValueRef::Variable< T >::RootCandidateInvariant().
template<class T > template<class Archive > void ValueRef::Statistic< T >::serialize (Archive & ar, const unsigned int version) private
References ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_stat_type, and ValueRef::Statistic< T >::m_value_ref.
template<class T > void ValueRef::Statistic< T >::SetTopLevelContent (const std::string & content_name) override virtual
Reimplemented from ValueRef::ValueRefBase< T >.
References ValueRef::Statistic< T >::m_sampling_condition, and ValueRef::Statistic< T >::m_value_ref.
template<class T > bool ValueRef::Statistic< T >::SourceInvariant () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_value_ref, and ValueRef::Variable< T >::SourceInvariant().
template<class T > bool ValueRef::Statistic< T >::TargetInvariant () const override virtual
Reimplemented from ValueRef::Variable< T >.
References ValueRef::Statistic< T >::m_sampling_condition, ValueRef::Statistic< T >::m_value_ref, and ValueRef::Variable< T >::TargetInvariant().
Friends And Related Function Documentation
template<class T> friend class boost::serialization::access friend
Member Data Documentation
template<class T> std::unique_ptr<Condition::ConditionBase> ValueRef::Statistic< T >::m_sampling_condition private
Referenced by ValueRef::Statistic< T >::Description(), ValueRef::Statistic< T >::Eval(), ValueRef::Statistic< T >::GetCheckSum(), ValueRef::Statistic< T >::operator==(), ValueRef::Statistic< T >::RootCandidateInvariant(), ValueRef::Statistic< T >::serialize(), ValueRef::Statistic< T >::SetTopLevelContent(), ValueRef::Statistic< T >::SourceInvariant(), and ValueRef::Statistic< T >::TargetInvariant().
template<class T> StatisticType ValueRef::Statistic< T >::m_stat_type private
Referenced by ValueRef::Statistic< T >::Description(), ValueRef::Statistic< T >::Eval(), ValueRef::Statistic< T >::GetCheckSum(), ValueRef::Statistic< T >::operator==(), ValueRef::Statistic< T >::ReduceData(), and ValueRef::Statistic< T >::serialize().
template<class T> std::unique_ptr<ValueRefBase<T> > ValueRef::Statistic< T >::m_value_ref private
Referenced by ValueRef::Statistic< T >::Description(), ValueRef::Statistic< T >::GetCheckSum(), ValueRef::Statistic< T >::GetObjectPropertyValues(), ValueRef::Statistic< T >::LocalCandidateInvariant(), ValueRef::Statistic< T >::operator==(), ValueRef::Statistic< T >::RootCandidateInvariant(), ValueRef::Statistic< T >::serialize(), ValueRef::Statistic< T >::SetTopLevelContent(), ValueRef::Statistic< T >::SourceInvariant(), and ValueRef::Statistic< T >::TargetInvariant().
The documentation for this struct was generated from the following file:
ValueRef.h