FreeOrion: ValueRef::StringCast< FromType > Struct Template Reference
ValueRef::StringCast< FromType > Struct Template Reference final
The variable lexical_cast to string class.
#include <ValueRefs.h>
Public Member Functions
StringCast (std::unique_ptr< ValueRef< FromType >> &&value_ref)
std::unique_ptr< ValueRef< std::string > > Clone () const override
Makes a clone of this ValueRef in a new owning pointer.
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a textual representation of the evaluation result with an empty/default context.
std::string Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
const ValueRef< FromType > * GetValueRef () const
bool operator== (const ValueRef< std::string > &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Returns a textual representation that should be parseable to recreate this ValueRef.
Public Member Functions inherited from ValueRef::Variable< std::string >
Variable (ReferenceType ref_type, S &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const char *property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, bool return_immediate_value=false)
Variable (ReferenceType ref_type, boost::optional< std::string > &&container_name, S &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, std::vector< std::string > &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name, bool return_immediate_value=false)
std::unique_ptr< ValueRef< std::string > > Clone () const override
Makes a clone of this ValueRef in a new owning pointer.
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a textual representation of the evaluation result with an empty/default context.
std::string Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
ReferenceType GetReferenceType () const
bool operator== (const ValueRef< std::string > &rhs) const override
const std::vector< std::string > & PropertyName () const
bool ReturnImmediateValue () const
Public Member Functions inherited from ValueRef::ValueRef< std::string >
ValueRef ()=default
virtual ~ValueRef ()=default
std::string Eval () const
Evaluates the expression tree with a default context.
std::string EvalAsString () const final
Evaluates the expression tree with an empty context and retuns the a string representation of the result value iff the result type is supported (currently std::string, int, float, double, enum).
bool operator!= (const ValueRef< std::string > &rhs) const
Public Member Functions inherited from ValueRef::ValueRefBase
ValueRefBase ()=default
virtual ~ValueRefBase ()=default
virtual bool ConstantExpr () const
std::string InvariancePattern () const
virtual bool LocalCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Private Attributes
std::unique_ptr< ValueRef< FromType > > m_value_ref
Additional Inherited Members
Protected Member Functions inherited from ValueRef::Variable< std::string >
void InitInvariants ()
Protected Attributes inherited from ValueRef::Variable< std::string >
std::vector< std::string > m_property_name
ReferenceType m_ref_type
bool m_return_immediate_value
Protected Attributes inherited from ValueRef::ValueRefBase
bool m_local_candidate_invariant = false
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
template<typename FromType>
struct ValueRef::StringCast< FromType >
The variable lexical_cast to string class.
The value returned by this node is taken from the ctor value_ref parameter's FromType value, lexical_cast to std::string
Constructor & Destructor Documentation
StringCast()
template<typename FromType > ValueRef::StringCast< FromType >::StringCast (std::unique_ptr< ValueRef< FromType >> && value_ref) explicit
References ValueRef::ValueRefBase::m_local_candidate_invariant, ValueRef::Variable< std::string >::m_property_name, ValueRef::Variable< std::string >::m_ref_type, ValueRef::ValueRefBase::m_root_candidate_invariant, ValueRef::ValueRefBase::m_source_invariant, ValueRef::ValueRefBase::m_target_invariant, and ValueRef::StringCast< FromType >::m_value_ref.
Member Function Documentation
Clone()
template<typename FromType> std::unique_ptr<ValueRef<std::string> > ValueRef::StringCast< FromType >::Clone () const inline override virtual
Makes a clone of this ValueRef in a new owning pointer.
Required for Boost.Python, which doesn't supports move semantics for returned values.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::CloneUnique().
Description()
template<typename FromType > std::string ValueRef::StringCast< FromType >::Description () const override virtual
Implements ValueRef::ValueRefBase.
References ValueRef::StringCast< FromType >::m_value_ref.
Dump()
template<typename FromType > std::string ValueRef::StringCast< FromType >::Dump (unsigned short ntabs = 0) const override virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
References ValueRef::StringCast< FromType >::m_value_ref.
Eval() [1/7]
template<typename FromType > std::string ValueRef::StringCast< FromType >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::StringCast< FromType >::m_value_ref.
Referenced by ValueRef::StringCast< FromType >::Eval().
Eval() [2/7]
template<> FO_COMMON_API std::string ValueRef::StringCast< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
Eval() [3/7]
template<> FO_COMMON_API std::string ValueRef::StringCast< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
Eval() [4/7]
template<> FO_COMMON_API std::string ValueRef::StringCast< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
Eval() [5/7]
template<> std::string ValueRef::StringCast< double >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References DoubleToString(), ValueRef::StringCast< FromType >::Eval(), and UserString().
Eval() [6/7]
template<> std::string ValueRef::StringCast< int >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References Fleet::ETA_NEVER, Fleet::ETA_OUT_OF_RANGE, Fleet::ETA_UNKNOWN, ValueRef::StringCast< FromType >::Eval(), to_string(), and UserString().
Eval() [7/7]
template<> std::string ValueRef::StringCast< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::StringCast< FromType >::Eval().
GetCheckSum()
template<typename FromType > unsigned int ValueRef::StringCast< FromType >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References CheckSums::CheckSumCombine(), ValueRef::ValueRef< std::string >::Eval(), FO_COMMON_API, ValueRef::StringCast< FromType >::m_value_ref, and TraceLogger.
GetValueRef()
template<typename FromType> const ValueRef<FromType>* ValueRef::StringCast< FromType >::GetValueRef () const inline
operator==()
template<typename FromType > bool ValueRef::StringCast< FromType >::operator== (const ValueRef< std::string > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::StringCast< FromType >::m_value_ref.
SetTopLevelContent()
template<typename FromType > void ValueRef::StringCast< FromType >::SetTopLevelContent (const std::string & content_name) override virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::StringCast< FromType >::m_value_ref.
Member Data Documentation
m_value_ref
template<typename FromType> std::unique_ptr<ValueRef<FromType> > ValueRef::StringCast< FromType >::m_value_ref private
Referenced by ValueRef::StringCast< FromType >::Description(), ValueRef::StringCast< FromType >::Dump(), ValueRef::StringCast< FromType >::Eval(), ValueRef::StringCast< FromType >::GetCheckSum(), ValueRef::StringCast< FromType >::operator==(), ValueRef::StringCast< FromType >::SetTopLevelContent(), and ValueRef::StringCast< FromType >::StringCast().
The documentation for this struct was generated from the following file:
ValueRefs.h