FreeOrion: Condition::OnPlanet Struct Reference
Condition::OnPlanet Struct Reference final
Matches all objects that are on the planet with the indicated planet_id or that are that planet.
#include <Conditions.h>
Public Member Functions
OnPlanet (std::unique_ptr< ValueRef::ValueRef< int >> &&planet_id)
std::unique_ptr< Condition > Clone () const override
Makes a clone of this Condition in a new owning pointer.
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Condition::Condition
Condition ()=default
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_planet_id
Additional Inherited Members
Protected Member Functions inherited from Condition::Condition
Condition (const Condition &rhs)=default
Copies invariants from other Condition.
Protected Attributes inherited from Condition::Condition
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
Matches all objects that are on the planet with the indicated planet_id or that are that planet.
If planet_id is INVALID_OBJECT_ID then matches all objects on any planet
Constructor & Destructor Documentation
OnPlanet()
Condition::OnPlanet::OnPlanet (std::unique_ptr< ValueRef::ValueRef< int >> && planet_id)
References m_planet_id, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, and Condition::Condition::m_target_invariant.
Member Function Documentation
Clone()
std::unique_ptr< Condition > Condition::OnPlanet::Clone () const override virtual
Makes a clone of this Condition in a new owning pointer.
Required for Boost.Python, which doesn't supports move semantics for returned values.
Implements Condition::Condition.
References ValueRef::CloneUnique(), and m_planet_id.
Description()
std::string Condition::OnPlanet::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), INVALID_OBJECT_ID, m_planet_id, Objects(), and UserString().
Dump()
std::string Condition::OnPlanet::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_planet_id.
Eval()
void Condition::OnPlanet::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), INVALID_OBJECT_ID, m_planet_id, and Condition::Condition::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::OnPlanet::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_planet_id, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::OnPlanet::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References anonymous_namespace{Conditions.cpp}::AddBuildingSet(), ScriptingContext::condition_root_candidate, ScriptingContext::ContextObjects(), ObjectMap::find(), ObjectMap::get(), m_planet_id, and Condition::Condition::RootCandidateInvariant().
Match()
bool Condition::OnPlanet::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, INVALID_OBJECT_ID, and m_planet_id.
operator==()
bool Condition::OnPlanet::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_planet_id.
SetTopLevelContent()
void Condition::OnPlanet::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_planet_id.
Member Data Documentation
m_planet_id
std::unique_ptr<ValueRef::ValueRef<int> > Condition::OnPlanet::m_planet_id private
Referenced by Clone(), Description(), Dump(), Eval(), GetCheckSum(), GetDefaultInitialCandidateObjects(), Match(), OnPlanet(), Condition::anonymous_namespace{Conditions.cpp}::OnPlanetSimpleMatch::operator()(), operator==(), and SetTopLevelContent().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp