FreeOrion: ResearchQueue Struct Reference
ResearchQueue Struct Reference
#include <ResearchQueue.h>
Classes
struct Element
The type of a single element in the research queue.
Public Types
typedef QueueType::const_iterator const_iterator
The const ResearchQueue iterator type.
typedef QueueType::iterator iterator
The ResearchQueue iterator type.
typedef std::deque< Element > QueueType
Public Member Functions
Structors
ResearchQueue (int empire_id)
Accessors
bool InQueue (const std::string &tech_name) const
Returns true iff tech is in this queue.
bool Paused (const std::string &tech_name) const
Returns true iff tech is in this queue and paused.
bool Paused (int idx) const
Returns true iff there are at least idx - 1 items in the queue and item with index idx is paused.
int ProjectsInProgress () const
Returns the number of research projects currently (perhaps partially) funded.
float TotalRPsSpent () const
Returns the number of RPs currently spent on the projects in this queue.
int EmpireID () const
Returns true iff tech is in this queue.
std::vector< std::string > AllEnqueuedProjects () const
Returns true iff tech is in this queue.
std::string Dump () const
Returns true iff tech is in this queue.
bool empty () const
Returns true iff tech is in this queue.
unsigned int size () const
Returns true iff tech is in this queue.
const_iterator begin () const
Returns true iff tech is in this queue.
const_iterator end () const
Returns true iff tech is in this queue.
const_iterator find (const std::string &tech_name) const
Returns true iff tech is in this queue.
const Element & operator[] (int i) const
Returns true iff tech is in this queue.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_empire_id = ALL_EMPIRES
int m_projects_in_progress = 0
QueueType m_queue
float m_total_RPs_spent = 0.0f
Friends
class boost::serialization::access
Mutators
boost::signals2::signal< void()> ResearchQueueChangedSignal
Recalculates the RPs spent on and number of turns left for each project in the queue.
void Update (float RPs, const std::map< std::string, float > &research_progress)
Recalculates the RPs spent on and number of turns left for each project in the queue.
void push_back (const std::string &tech_name, bool paused=false)
Recalculates the RPs spent on and number of turns left for each project in the queue.
void insert (iterator it, const std::string &tech_name, bool paused=false)
Recalculates the RPs spent on and number of turns left for each project in the queue.
void erase (iterator it)
Recalculates the RPs spent on and number of turns left for each project in the queue.
iterator begin ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
iterator end ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
iterator find (const std::string &tech_name)
Recalculates the RPs spent on and number of turns left for each project in the queue.
void clear ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
Member Typedef Documentation
const_iterator
typedef QueueType::const_iterator ResearchQueue::const_iterator
The const ResearchQueue iterator type.
Dereference yields an Element.
iterator
typedef QueueType::iterator ResearchQueue::iterator
The ResearchQueue iterator type.
Dereference yields an Element.
QueueType
typedef std::deque<Element> ResearchQueue::QueueType
Constructor & Destructor Documentation
ResearchQueue()
ResearchQueue::ResearchQueue (int empire_id) inline
Member Function Documentation
AllEnqueuedProjects()
std::vector< std::string > ResearchQueue::AllEnqueuedProjects () const
Returns true iff tech is in this queue.
References m_queue.
Referenced by ValueRef::ComplexVariable< T >::Eval().
begin() [1/2]
ResearchQueue::const_iterator ResearchQueue::begin () const
Returns true iff tech is in this queue.
References m_queue.
Referenced by ResearchWnd::AddTechsToQueueSlot(), ValueRef::ComplexVariable< T >::Eval(), find(), Paused(), Empire::PlaceTechInQueue(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), and Empire::TopPriorityEnqueuedTech().
begin() [2/2]
ResearchQueue::iterator ResearchQueue::begin ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References m_queue.
clear()
void ResearchQueue::clear ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References m_projects_in_progress, m_queue, m_total_RPs_spent, and ResearchQueueChangedSignal.
Referenced by Empire::Eliminate().
Dump()
std::string ResearchQueue::Dump () const
Returns true iff tech is in this queue.
References m_queue.
EmpireID()
int ResearchQueue::EmpireID () const inline
Returns true iff tech is in this queue.
References Effect::Dump(), and anonymous_namespace{EncyclopediaParser.cpp}::insert.
Referenced by anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), and FreeOrionPython::WrapEmpire().
empty()
bool ResearchQueue::empty () const
Returns true iff tech is in this queue.
References m_queue.
Referenced by Empire::LeastExpensiveEnqueuedTech(), Empire::MostExpensiveEnqueuedTech(), Empire::TopPriorityEnqueuedTech(), Empire::TopPriorityResearchableTech(), and FreeOrionPython::WrapEmpire().
end() [1/2]
ResearchQueue::const_iterator ResearchQueue::end () const
Returns true iff tech is in this queue.
References m_queue.
Referenced by erase(), ValueRef::ComplexVariable< T >::Eval(), find(), Paused(), Empire::PauseResearch(), Empire::PlaceTechInQueue(), Empire::RemoveTechFromQueue(), Empire::ResumeResearch(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), TechRowBrowseWnd(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
end() [2/2]
ResearchQueue::iterator ResearchQueue::end ()
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References m_queue.
erase()
void ResearchQueue::erase (iterator it)
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References end(), and m_queue.
Referenced by Empire::PlaceTechInQueue(), Empire::RemoveTechFromQueue(), and anonymous_namespace{Empire.cpp}::SanitizeResearchQueue().
find() [1/2]
ResearchQueue::const_iterator ResearchQueue::find (const std::string & tech_name) const
Returns true iff tech is in this queue.
References begin(), and end().
Referenced by ResearchWnd::AddTechsToQueueSlot(), ValueRef::ComplexVariable< T >::Eval(), Paused(), Empire::PauseResearch(), Empire::PlaceTechInQueue(), Empire::RemoveTechFromQueue(), Empire::ResumeResearch(), TechRowBrowseWnd(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
find() [2/2]
ResearchQueue::iterator ResearchQueue::find (const std::string & tech_name)
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References begin(), and end().
InQueue()
bool ResearchQueue::InQueue (const std::string & tech_name) const
Returns true iff tech is in this queue.
References m_queue.
Referenced by ResearchWnd::AddTechsToQueueSlot(), Empire::MostRPCostLeftEnqueuedTech(), Empire::MostRPSpentEnqueuedTech(), TechTreeArcs::Impl::RefreshHighlights(), Empire::SetTechResearchProgress(), TechTreeWnd::TechListBox::TechRow::Update(), and FreeOrionPython::WrapEmpire().
insert()
void ResearchQueue::insert (iterator it, const std::string & tech_name, bool paused = false)
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References ResearchQueue::Element::Element(), m_empire_id, and m_queue.
Referenced by Empire::PlaceTechInQueue(), and TechTreeArcs::Impl::RefreshHighlights().
operator[]()
const ResearchQueue::Element & ResearchQueue::operator[] (int i) const
Returns true iff tech is in this queue.
References m_queue.
Paused() [1/2]
bool ResearchQueue::Paused (const std::string & tech_name) const
Returns true iff tech is in this queue and paused.
References end(), and find().
Paused() [2/2]
bool ResearchQueue::Paused (int idx) const
Returns true iff there are at least idx - 1 items in the queue and item with index idx is paused.
References begin(), and m_queue.
ProjectsInProgress()
int ResearchQueue::ProjectsInProgress () const
Returns the number of research projects currently (perhaps partially) funded.
References m_projects_in_progress.
push_back()
void ResearchQueue::push_back (const std::string & tech_name, bool paused = false)
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References ResearchQueue::Element::Element(), m_empire_id, and m_queue.
Referenced by Empire::PlaceTechInQueue(), and Empire::SetTechResearchProgress().
serialize()
template<class Archive > template void ResearchQueue::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References m_empire_id, m_projects_in_progress, m_queue, and m_total_RPs_spent.
size()
unsigned int ResearchQueue::size () const
Returns true iff tech is in this queue.
References m_queue.
Referenced by Empire::PlaceTechInQueue(), and FreeOrionPython::WrapEmpire().
TotalRPsSpent()
float ResearchQueue::TotalRPsSpent () const
Returns the number of RPs currently spent on the projects in this queue.
References m_total_RPs_spent.
Referenced by MapWnd::RefreshResearchResourceIndicator(), ResearchWnd::UpdateInfoPanel(), and FreeOrionPython::WrapEmpire().
Update()
void ResearchQueue::Update (float RPs, const std::map< std::string, float > & research_progress)
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
References DebugLogger, anonymous_namespace{XMLDoc.cpp}::element, anonymous_namespace{ResearchQueue.cpp}::EPSILON, ErrorLogger, GetEmpire(), GetTech(), GetTechManager(), Empire::GetTechStatus(), m_empire_id, m_projects_in_progress, m_queue, m_total_RPs_spent, ResearchQueue::Element::paused, Tech::Prerequisites(), Tech::ResearchCost(), ResearchQueueChangedSignal, Tech::ResearchTime(), anonymous_namespace{ResearchQueue.cpp}::SetTechQueueElementSpending(), TS_COMPLETE, TS_HAS_RESEARCHED_PREREQ, TS_RESEARCHABLE, TS_UNRESEARCHABLE, and Tech::UnlockedTechs().
Referenced by Empire::UpdateResearchQueue().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_empire_id
int ResearchQueue::m_empire_id = ALL_EMPIRES private
Referenced by insert(), push_back(), serialize(), ProductionQueue::serialize(), and Update().
m_projects_in_progress
int ResearchQueue::m_projects_in_progress = 0 private
Referenced by clear(), ProjectsInProgress(), serialize(), ProductionQueue::serialize(), and Update().
m_queue
QueueType ResearchQueue::m_queue private
Referenced by AllEnqueuedProjects(), begin(), clear(), Dump(), empty(), end(), erase(), InQueue(), insert(), operator[](), Paused(), push_back(), serialize(), ProductionQueue::serialize(), size(), and Update().
m_total_RPs_spent
float ResearchQueue::m_total_RPs_spent = 0.0f private
Referenced by clear(), serialize(), TotalRPsSpent(), and Update().
ResearchQueueChangedSignal
boost::signals2::signal<void ()> ResearchQueue::ResearchQueueChangedSignal mutable
Recalculates the RPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in prgress, and the total number of RPs spent on the projects in the queue.
Note
A precondition of this function that RPs must be greater than some epsilon > 0; see the implementation for the actual value used for epsilon.
Referenced by clear(), and Update().
The documentation for this struct was generated from the following files:
ResearchQueue.h
ResearchQueue.cpp
SerializeEmpire.cpp