FreeOrion: ValueRef::UserStringLookup< FromType > Struct Template Reference
ValueRef::UserStringLookup< FromType > Struct Template Reference final
Looks up a string ValueRef or vector of string ValueRefs, and returns and returns the UserString equivalent(s).
#include <ValueRefs.h>
Public Member Functions
UserStringLookup (std::unique_ptr< ValueRef< FromType >> &&value_ref)
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a text description of this type of special.
std::string Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
template<>
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
const ValueRef< FromType > * GetValueRef () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRef< std::string > &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::Variable< std::string >
Variable (ReferenceType ref_type, S &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const char *property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, bool return_immediate_value=false)
Variable (ReferenceType ref_type, boost::optional< std::string > &&container_name, std::string &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, std::vector< std::string > &&property_name, bool return_immediate_value=false)
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name, bool return_immediate_value=false)
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a text description of this type of special.
std::string Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetSize Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API PlanetEnvironment Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API UniverseObjectType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API StarType Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
FO_COMMON_API std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Visibility Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
double Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
int Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
std::vector< std::string > Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
std::string Eval (const ScriptingContext &context) const
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
ReferenceType GetReferenceType () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRef< std::string > &rhs) const override
const std::vector< std::string > & PropertyName () const
bool ReturnImmediateValue () const
bool RootCandidateInvariant () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRef< std::string >
virtual ~ValueRef ()
virtual bool ConstantExpr () const
std::string Eval () const
Evaluates the expression tree with an empty context.
bool operator!= (const ValueRef< std::string > &rhs) const
virtual bool SimpleIncrement () const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef< FromType > > m_value_ref
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from ValueRef::Variable< std::string >
std::vector< std::string > m_property_name
ReferenceType m_ref_type
bool m_return_immediate_value
Detailed Description
template<typename FromType>
struct ValueRef::UserStringLookup< FromType >
Looks up a string ValueRef or vector of string ValueRefs, and returns and returns the UserString equivalent(s).
Constructor & Destructor Documentation
UserStringLookup()
template<typename FromType > ValueRef::UserStringLookup< FromType >::UserStringLookup (std::unique_ptr< ValueRef< FromType >> && value_ref) explicit
References ValueRef::Variable< std::string >::m_property_name, ValueRef::Variable< std::string >::m_ref_type, and ValueRef::UserStringLookup< FromType >::m_value_ref.
Member Function Documentation
Description()
template<typename FromType > std::string ValueRef::UserStringLookup< FromType >::Description () const override virtual
Implements ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
Dump()
template<typename FromType > std::string ValueRef::UserStringLookup< FromType >::Dump (unsigned short ntabs = 0) const override virtual
Returns a text description of this type of special.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
Eval() [1/5]
template<typename FromType > std::string ValueRef::UserStringLookup< FromType >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::ValueRef< std::string >::Eval(), FO_COMMON_API, ValueRef::UserStringLookup< FromType >::m_value_ref, UserString(), and UserStringExists().
Referenced by ValueRef::UserStringLookup< FromType >::Eval().
Eval() [2/5]
template<> FO_COMMON_API std::string ValueRef::UserStringLookup< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
Eval() [3/5]
template<> FO_COMMON_API std::string ValueRef::UserStringLookup< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
Eval() [4/5]
template<> std::string ValueRef::UserStringLookup< std::string >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::Eval(), UserString(), and UserStringExists().
Eval() [5/5]
template<> std::string ValueRef::UserStringLookup< std::vector< std::string > >::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::Eval(), UserString(), and UserStringExists().
GetCheckSum()
template<typename FromType > unsigned int ValueRef::UserStringLookup< FromType >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References CheckSums::CheckSumCombine(), ValueRef::UserStringLookup< FromType >::m_value_ref, and TraceLogger.
GetValueRef()
template<typename FromType > const ValueRef<FromType>* ValueRef::UserStringLookup< FromType >::GetValueRef () const inline
LocalCandidateInvariant()
template<typename FromType > bool ValueRef::UserStringLookup< FromType >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
operator==()
template<typename FromType > bool ValueRef::UserStringLookup< FromType >::operator== (const ValueRef< std::string > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
RootCandidateInvariant()
template<typename FromType > bool ValueRef::UserStringLookup< FromType >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
serialize()
template<typename FromType > template<typename Archive > void ValueRef::UserStringLookup< FromType >::serialize (Archive & ar, const unsigned int version) private
References ValueRef::UserStringLookup< FromType >::m_value_ref.
SetTopLevelContent()
template<typename FromType > void ValueRef::UserStringLookup< FromType >::SetTopLevelContent (const std::string & content_name) override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
SourceInvariant()
template<typename FromType > bool ValueRef::UserStringLookup< FromType >::SourceInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
TargetInvariant()
template<typename FromType > bool ValueRef::UserStringLookup< FromType >::TargetInvariant () const override virtual
Reimplemented from ValueRef::ValueRef< std::string >.
References ValueRef::UserStringLookup< FromType >::m_value_ref.
Friends And Related Function Documentation
boost::serialization::access
template<typename FromType > friend class boost::serialization::access friend
Member Data Documentation
m_value_ref
template<typename FromType > std::unique_ptr<ValueRef<FromType> > ValueRef::UserStringLookup< FromType >::m_value_ref private
Referenced by ValueRef::UserStringLookup< FromType >::Description(), ValueRef::UserStringLookup< FromType >::Dump(), ValueRef::UserStringLookup< FromType >::Eval(), ValueRef::UserStringLookup< FromType >::GetCheckSum(), ValueRef::UserStringLookup< FromType >::LocalCandidateInvariant(), ValueRef::UserStringLookup< FromType >::operator==(), ValueRef::UserStringLookup< FromType >::RootCandidateInvariant(), ValueRef::UserStringLookup< FromType >::serialize(), ValueRef::NameLookup::serialize(), ValueRef::UserStringLookup< FromType >::SetTopLevelContent(), ValueRef::UserStringLookup< FromType >::SourceInvariant(), ValueRef::UserStringLookup< FromType >::TargetInvariant(), and ValueRef::UserStringLookup< FromType >::UserStringLookup().
The documentation for this struct was generated from the following file:
ValueRefs.h