FreeOrion: QuittingGame Struct Reference
QuittingGame Struct Reference
#include <HumanClientFSM.h>
Public Types
using Clock = std::chrono::steady_clock
using reactions = boost::mpl::list< boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< ShutdownServer >, boost::statechart::custom_reaction< WaitForDisconnect >, boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< TerminateServer > >
Public Member Functions
QuittingGame (my_context ctx)
~QuittingGame ()
boost::statechart::result react (const StartQuittingGame &d)
boost::statechart::result react (const ShutdownServer &msg)
boost::statechart::result react (const WaitForDisconnect &msg)
boost::statechart::result react (const Disconnection &msg)
boost::statechart::result react (const TerminateServer &msg)
Public Attributes
bool m_reset_to_intro
Process * m_server_process
std::chrono::steady_clock::time_point m_start_time
Detailed Description
The state for the orderly shutdown of the server.
Member Typedef Documentation
using QuittingGame::Clock = std::chrono::steady_clock
using QuittingGame::reactions = boost::mpl::list< boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<ShutdownServer>, boost::statechart::custom_reaction<WaitForDisconnect>, boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<TerminateServer> >
Constructor & Destructor Documentation
QuittingGame::QuittingGame (my_context c)
The QuittingGame state expects to start with a StartQuittingGame message posted.
References DebugLogger, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
QuittingGame::~QuittingGame ()
References DebugLogger, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
Member Function Documentation
boost::statechart::result QuittingGame::react (const StartQuittingGame & d)
References DebugLogger, StartQuittingGame::m_reset_to_intro, m_reset_to_intro, StartQuittingGame::m_server, m_server_process, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
boost::statechart::result QuittingGame::react (const ShutdownServer & msg)
References DebugLogger, Process::Empty(), ErrorLogger, m_server_process, ShutdownServerMessage(), anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION, and WarnLogger.
boost::statechart::result QuittingGame::react (const WaitForDisconnect & msg)
References DebugLogger, m_start_time, QUITTING_POLLING_INTERVAL, QUITTING_TIMEOUT, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
boost::statechart::result QuittingGame::react (const Disconnection & msg)
References DebugLogger, ErrorLogger, Process::Free(), m_server_process, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
boost::statechart::result QuittingGame::react (const TerminateServer & msg)
References DebugLogger, Process::Empty(), m_reset_to_intro, m_server_process, Process::RequestTermination(), and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
Member Data Documentation
bool QuittingGame::m_reset_to_intro
Referenced by react().
Process* QuittingGame::m_server_process
Referenced by react().
std::chrono::steady_clock::time_point QuittingGame::m_start_time
Referenced by react().
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp