FreeOrion: PlayingGame Struct Reference
PlayingGame Struct Reference
The human client state in which a game has been started.
#include <ServerFSM.h>
Public Types
typedef boost::statechart::state< PlayingGame, HumanClientFSM, WaitingForGameStart > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< HostID >, boost::statechart::custom_reaction< PlayerChat >, boost::statechart::custom_reaction< Disconnection >, boost::statechart::custom_reaction< PlayerStatus >, boost::statechart::custom_reaction< Diplomacy >, boost::statechart::custom_reaction< DiplomaticStatusUpdate >, boost::statechart::custom_reaction< EndGame >, boost::statechart::custom_reaction< StartQuittingGame >, boost::statechart::custom_reaction< Error >, boost::statechart::custom_reaction< TurnProgress >, boost::statechart::custom_reaction< TurnPartialUpdate >, boost::statechart::custom_reaction< LobbyUpdate >, boost::statechart::custom_reaction< TurnTimeout >, boost::statechart::custom_reaction< PlayerInfoMsg > > reactions
typedef boost::mpl::list< sc::in_state_reaction< Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection >, sc::custom_reaction< PlayerChat >, sc::custom_reaction< Diplomacy >, sc::custom_reaction< ModeratorAct >, sc::custom_reaction< RequestCombatLogs >, sc::custom_reaction< ShutdownServer >, sc::custom_reaction< Hostless >, sc::custom_reaction< JoinGame >, sc::custom_reaction< AuthResponse >, sc::custom_reaction< EliminateSelf >, sc::custom_reaction< AutoTurn >, sc::custom_reaction< Error >, sc::custom_reaction< LobbyUpdate > > reactions
Public Member Functions
PlayingGame (my_context ctx)
PlayingGame (my_context c)
~PlayingGame ()
~PlayingGame ()
void EstablishPlayer (const PlayerConnectionPtr &player_connection, const std::string &player_name, Networking::ClientType client_type, const std::string &client_version_string, const Networking::AuthRoles &roles)
boost::statechart::result react (const HostID &msg)
boost::statechart::result react (const PlayerChat &msg)
boost::statechart::result react (const Disconnection &d)
boost::statechart::result react (const PlayerStatus &msg)
boost::statechart::result react (const Diplomacy &d)
boost::statechart::result react (const DiplomaticStatusUpdate &u)
boost::statechart::result react (const EndGame &msg)
boost::statechart::result react (const StartQuittingGame &msg)
boost::statechart::result react (const Error &msg)
boost::statechart::result react (const TurnProgress &msg)
boost::statechart::result react (const TurnPartialUpdate &msg)
boost::statechart::result react (const LobbyUpdate &msg)
boost::statechart::result react (const TurnTimeout &msg)
boost::statechart::result react (const PlayerInfoMsg &msg)
sc::result react (const PlayerChat &msg)
sc::result react (const Diplomacy &msg)
sc::result react (const ModeratorAct &msg)
sc::result react (const ShutdownServer &u)
sc::result react (const Hostless &u)
sc::result react (const RequestCombatLogs &msg)
sc::result react (const JoinGame &msg)
sc::result react (const AuthResponse &msg)
sc::result react (const EliminateSelf &msg)
sc::result react (const AutoTurn &msg)
sc::result react (const Error &msg)
sc::result react (const LobbyUpdate &msg)
void TurnTimedoutHandler (const boost::system::error_code &error)
Public Attributes
std::chrono::high_resolution_clock::time_point m_start
boost::asio::deadline_timer m_turn_timeout
Detailed Description
The human client state in which a game has been started.
The server state in which a game has been started, and is actually being played.
Member Typedef Documentation
Base
typedef boost::statechart::state<PlayingGame, HumanClientFSM, WaitingForGameStart> PlayingGame::Base
reactions [1/2]
typedef boost::mpl::list< boost::statechart::custom_reaction<HostID>, boost::statechart::custom_reaction<PlayerChat>, boost::statechart::custom_reaction<Disconnection>, boost::statechart::custom_reaction<PlayerStatus>, boost::statechart::custom_reaction<Diplomacy>, boost::statechart::custom_reaction<DiplomaticStatusUpdate>, boost::statechart::custom_reaction<EndGame>, boost::statechart::custom_reaction<StartQuittingGame>, boost::statechart::custom_reaction<Error>, boost::statechart::custom_reaction<TurnProgress>, boost::statechart::custom_reaction<TurnPartialUpdate>, boost::statechart::custom_reaction<LobbyUpdate>, boost::statechart::custom_reaction<TurnTimeout>, boost::statechart::custom_reaction<PlayerInfoMsg> > PlayingGame::reactions
reactions [2/2]
typedef boost::mpl::list< sc::in_state_reaction<Disconnection, ServerFSM, &ServerFSM::HandleNonLobbyDisconnection>, sc::custom_reaction<PlayerChat>, sc::custom_reaction<Diplomacy>, sc::custom_reaction<ModeratorAct>, sc::custom_reaction<RequestCombatLogs>, sc::custom_reaction<ShutdownServer>, sc::custom_reaction<Hostless>, sc::custom_reaction<JoinGame>, sc::custom_reaction<AuthResponse>, sc::custom_reaction<EliminateSelf>, sc::custom_reaction<AutoTurn>, sc::custom_reaction<Error>, sc::custom_reaction<LobbyUpdate> > PlayingGame::reactions
Constructor & Destructor Documentation
PlayingGame() [1/2]
PlayingGame::PlayingGame (my_context ctx)
References TraceLogger.
Referenced by WaitingForMPGameJoiners::react().
~PlayingGame() [1/2]
PlayingGame::~PlayingGame ()
References TraceLogger.
Referenced by WaitingForMPGameJoiners::react().
PlayingGame() [2/2]
PlayingGame::PlayingGame (my_context c)
~PlayingGame() [2/2]
PlayingGame::~PlayingGame ()
Member Function Documentation
EstablishPlayer()
void PlayingGame::EstablishPlayer (const PlayerConnectionPtr & player_connection, const std::string & player_name, Networking::ClientType client_type, const std::string & client_version_string, const Networking::AuthRoles & roles)
References ServerApp::AddObserverPlayerIntoGame(), ServerApp::AddPlayerIntoGame(), ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerFSM::EstablishPlayer(), GetOptionsDB(), TurnTimeoutMessage(), and ServerFSM::UpdateIngameLobby().
react() [1/26]
boost::statechart::result PlayingGame::react (const HostID & msg)
References DebugLogger, ErrorLogger, and Networking::INVALID_PLAYER_ID.
Referenced by WaitingForMPGameJoiners::react(), and react().
react() [2/26]
sc::result PlayingGame::react (const PlayerChat & msg)
References ExtractServerPlayerChatMessageData(), GetEmpire(), Networking::INVALID_PLAYER_ID, to_string(), TraceLogger, and UserString().
react() [3/26]
boost::statechart::result PlayingGame::react (const Disconnection & d)
References ClientUI::MessageBox(), TraceLogger, and UserString().
react() [4/26]
boost::statechart::result PlayingGame::react (const PlayerStatus & msg)
References ExtractPlayerStatusMessageData(), Message::PlayerStatus, and TraceLogger.
react() [5/26]
sc::result PlayingGame::react (const Diplomacy & d)
References Empires(), ExtractDiplomacyMessageData(), EmpireManager::SetDiplomaticMessage(), and TraceLogger.
react() [6/26]
boost::statechart::result PlayingGame::react (const DiplomaticStatusUpdate & u)
References DiplomaticStatusUpdateInfo::diplo_status, DiplomaticStatusUpdateInfo::empire1_id, DiplomaticStatusUpdateInfo::empire2_id, Empires(), ExtractDiplomaticStatusMessageData(), EmpireManager::SetDiplomaticStatus(), and TraceLogger.
react() [7/26]
boost::statechart::result PlayingGame::react (const EndGame & msg)
References Message::EndGameReason, error, ExtractEndGameMessageData(), FlexibleFormat(), ClientUI::MessageBox(), TraceLogger, and UserString().
react() [8/26]
boost::statechart::result PlayingGame::react (const StartQuittingGame & msg)
References TraceLogger, and UserString().
react() [9/26]
sc::result PlayingGame::react (const Error & msg)
References ErrorLogger, ExtractErrorMessageData(), ClientUI::MessageBox(), TraceLogger, and UserString().
react() [10/26]
boost::statechart::result PlayingGame::react (const TurnProgress & msg)
References ExtractTurnProgressMessageData(), TraceLogger, and Message::TurnProgressPhase.
react() [11/26]
boost::statechart::result PlayingGame::react (const TurnPartialUpdate & msg)
References ExtractTurnPartialUpdateMessageData(), GetUniverse(), and TraceLogger.
react() [12/26]
sc::result PlayingGame::react (const LobbyUpdate & msg)
References TraceLogger.
react() [13/26]
boost::statechart::result PlayingGame::react (const TurnTimeout & msg)
References DebugLogger, and ErrorLogger.
react() [14/26]
boost::statechart::result PlayingGame::react (const PlayerInfoMsg & msg)
References DebugLogger, and ExtractPlayerInfoMessageData().
react() [15/26]
sc::result PlayingGame::react (const PlayerChat & msg)
react() [16/26]
sc::result PlayingGame::react (const Diplomacy & msg)
react() [17/26]
sc::result PlayingGame::react (const ModeratorAct & msg)
References tag_parser::action, Networking::CLIENT_TYPE_HUMAN_MODERATOR, DebugLogger, Moderator::ModeratorAction::Dump(), ErrorLogger, Moderator::ModeratorAction::Execute(), ExtractModeratorActionMessageData(), GetUniverse(), ServerApp::PlayerEmpireID(), TraceLogger, TurnPartialUpdateMessage(), and TurnProgressMessage().
react() [18/26]
sc::result PlayingGame::react (const ShutdownServer & u)
References ServerApp::CurrentTurn(), Empires(), error, ErrorLogger, ErrorMessage(), OptionsDB::Get(), anonymous_namespace{ServerFSM.cpp}::GetAutoSaveFileName(), GetCombatLogManager(), GetOptionsDB(), ServerApp::GetPlayerSaveGameData(), GetSpeciesManager(), GetUniverse(), ServerApp::IsHostless(), ServerApp::m_galaxy_setup_data, ServerApp::m_single_player_game, SaveGame(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerSaveGameCompleteMessage(), TraceLogger, and UserStringNop.
react() [19/26]
sc::result PlayingGame::react (const Hostless & u)
References ServerApp::m_ai_client_processes, and TraceLogger.
react() [20/26]
sc::result PlayingGame::react (const RequestCombatLogs & msg)
References DebugLogger.
react() [21/26]
sc::result PlayingGame::react (const JoinGame & msg)
References AuthRequestMessage(), ServerNetworking::CheckCookie(), Networking::AuthRoles::Clear(), Networking::CLIENT_TYPE_AI_PLAYER, DebugLogger, ServerNetworking::Disconnect(), ServerApp::Empires(), ErrorLogger, ErrorMessage(), ExtractJoinGameMessageData(), FlexibleFormat(), ServerNetworking::GetCookiesSize(), ServerApp::IsAuthRequiredOrFillRoles(), ServerApp::IsAvailableName(), ServerApp::Networking(), ServerNetworking::NumEstablishedPlayers(), to_string(), UserString(), and WarnLogger.
react() [22/26]
sc::result PlayingGame::react (const AuthResponse & msg)
References DebugLogger, ServerNetworking::Disconnect(), ErrorMessage(), ExtractAuthResponseMessageData(), FlexibleFormat(), ServerApp::IsAuthSuccessAndFillRoles(), ServerApp::Networking(), and UserString().
react() [23/26]
sc::result PlayingGame::react (const EliminateSelf & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerNetworking::Disconnect(), ServerApp::EliminatePlayer(), ErrorMessage(), ServerApp::Networking(), UserStringNop, and WarnLogger.
react() [24/26]
sc::result PlayingGame::react (const AutoTurn & msg)
References ServerApp::AddPlayerIntoGame(), ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ServerNetworking::Disconnect(), ErrorLogger, ErrorMessage(), ServerNetworking::established_begin(), ServerNetworking::established_end(), ExtractLobbyUpdateMessageData(), GetEmpire(), anonymous_namespace{ServerFSM.cpp}::HandleErrorMessage(), ServerApp::m_networking, ServerApp::Networking(), ServerApp::PlayerEmpireID(), MultiplayerLobbyData::players, PlayerStatusMessage(), react(), TraceLogger, and UserStringNop.
react() [25/26]
sc::result PlayingGame::react (const Error & msg)
react() [26/26]
sc::result PlayingGame::react (const LobbyUpdate & msg)
TurnTimedoutHandler()
void PlayingGame::TurnTimedoutHandler (const boost::system::error_code & error)
References DebugLogger, and GetOptionsDB().
Referenced by WaitingForMPGameJoiners::react(), and WaitingForTurnEnd::WaitingForTurnEnd().
Member Data Documentation
m_start
std::chrono::high_resolution_clock::time_point PlayingGame::m_start
m_turn_timeout
boost::asio::deadline_timer PlayingGame::m_turn_timeout
The documentation for this struct was generated from the following files:
HumanClientFSM.h
ServerFSM.h
HumanClientFSM.cpp
ServerFSM.cpp