FreeOrion: Condition::SortedNumberOf Struct Reference
Condition::SortedNumberOf Struct Reference
#include <Condition.h>
Public Member Functions
SortedNumberOf (ValueRef::ValueRefBase< int > *number, ConditionBase *condition)
SortedNumberOf (ValueRef::ValueRefBase< int > *number, ValueRef::ValueRefBase< double > *sort_key_ref, SortingMethod sorting_method, ConditionBase *condition)
virtual ~SortedNumberOf ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ConditionBase * m_condition
ValueRef::ValueRefBase< int > * m_number
ValueRef::ValueRefBase< double > * m_sort_key
SortingMethod m_sorting_method
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches a specified number of objects that match Condition condition or as many objects as match the condition if the number of objects is less than the number requested. If more objects match the condition than are requested, the objects are sorted according to the value of the specified property_name and objects are matched according to whether they have the specified sorting_type of those property values. For example, objects with the largest, smallest or most common property value may be selected preferentially.
Constructor & Destructor Documentation
Condition::SortedNumberOf::SortedNumberOf (ValueRef::ValueRefBase< int > * number, ConditionBase * condition) inline
Sorts randomly, without considering a sort key.
Condition::SortedNumberOf::SortedNumberOf (ValueRef::ValueRefBase< int > * number, ValueRef::ValueRefBase< double > * sort_key_ref, SortingMethod sorting_method, ConditionBase * condition) inline
Sorts according to the specified method, based on the key values evaluated for each object.
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::SortedNumberOf::~SortedNumberOf () virtual
Member Function Documentation
std::string Condition::SortedNumberOf::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, Condition::SORT_RANDOM, and UserString().
std::string Condition::SortedNumberOf::Dump () const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), g_indent, Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, and Condition::SORT_RANDOM.
void Condition::SortedNumberOf::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::NON_MATCHES, and Condition::anonymous_namespace{Condition.cpp}::TransferSortedObjects().
unsigned int Condition::SortedNumberOf::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
void Condition::SortedNumberOf::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::GetDefaultInitialCandidateObjects().
bool Condition::SortedNumberOf::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_sorting_method.
bool Condition::SortedNumberOf::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
template<class Archive > void Condition::SortedNumberOf::serialize (Archive & ar, const unsigned int version) private
void Condition::SortedNumberOf::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
bool Condition::SortedNumberOf::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
bool Condition::SortedNumberOf::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ConditionBase* Condition::SortedNumberOf::m_condition private
ValueRef::ValueRefBase<int>* Condition::SortedNumberOf::m_number private
ValueRef::ValueRefBase<double>* Condition::SortedNumberOf::m_sort_key private
SortingMethod Condition::SortedNumberOf::m_sorting_method private
Referenced by operator==().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp