FreeOrion: WaitingForSaveData Struct Reference
WaitingForSaveData Struct Reference
#include <ServerFSM.h>
Public Types
typedef boost::mpl::list< sc::custom_reaction< ClientSaveData >, sc::deferral< SaveGameRequest >, sc::deferral< TurnOrders >, sc::deferral< PlayerChat >, sc::deferral< Diplomacy > > reactions
Public Member Functions
WaitingForSaveData (my_context c)
~WaitingForSaveData ()
sc::result react (const ClientSaveData &msg)
Public Attributes
std::set< int > m_needed_reponses
std::vector< PlayerSaveGameData > m_player_save_game_data
std::set< int > m_players_responded
Detailed Description
The substate of WaitingForTurnEnd in which a player has initiated a save and the server is waiting for all players to send their save data, after which the server will actually preform the save.
Member Typedef Documentation
typedef boost::mpl::list< sc::custom_reaction<ClientSaveData>, sc::deferral<SaveGameRequest>, sc::deferral<TurnOrders>, sc::deferral<PlayerChat>, sc::deferral<Diplomacy> > WaitingForSaveData::reactions
Constructor & Destructor Documentation
WaitingForSaveData::WaitingForSaveData (my_context c)
References ServerNetworking::established_begin(), ServerNetworking::established_end(), m_needed_reponses, ServerApp::m_networking, ServerSaveGameDataRequestMessage(), and TraceLogger.
WaitingForSaveData::~WaitingForSaveData ()
References TraceLogger.
Member Function Documentation
sc::result WaitingForSaveData::react (const ClientSaveData & msg)
References DebugLogger, Empires(), ErrorLogger, ErrorMessage(), ExtractClientSaveDataMessageData(), GetCombatLogManager(), GetEmpire(), GetSpeciesManager(), GetUniverse(), ServerApp::m_current_turn, ServerApp::m_galaxy_setup_data, m_needed_reponses, m_player_save_game_data, m_players_responded, ServerApp::m_single_player_game, ServerApp::m_turn_sequence, ServerApp::PlayerEmpireID(), SaveGame(), anonymous_namespace{ServerFSM.cpp}::SendMessageToAllPlayers(), ServerSaveGameCompleteMessage(), TraceLogger, and UserStringNop.
Member Data Documentation
std::set<int> WaitingForSaveData::m_needed_reponses
Referenced by react(), and WaitingForSaveData().
std::vector<PlayerSaveGameData> WaitingForSaveData::m_player_save_game_data
Referenced by react().
std::set<int> WaitingForSaveData::m_players_responded
Referenced by react().
The documentation for this struct was generated from the following files:
ServerFSM.h
ServerFSM.cpp