FreeOrion: Condition::Condition Struct Reference
Condition::Condition Struct Reference abstract
The base class for all Conditions.
#include <Condition.h>
Classes
struct MatchHelper
Public Member Functions
Condition ()=default
virtual ~Condition ()
virtual std::string Description (bool negated=false) const =0
virtual std::string Dump (unsigned short ntabs=0) const =0
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual unsigned int GetCheckSum () const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
virtual bool operator== (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
virtual void SetTopLevelContent (const std::string &content_name)=0
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Protected Attributes
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
Friends
struct MatchHelper
Detailed Description
The base class for all Conditions.
Constructor & Destructor Documentation
Condition()
Condition::Condition::Condition () default
~Condition()
Condition::Condition::~Condition () virtual default
Member Function Documentation
Description()
std::string Condition::Condition::Description (bool negated = false) const pure virtual
Implemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, Condition::All, and Condition::Source.
Referenced by anonymous_namespace{ObjectListWnd.cpp}::ConditionClassName().
Dump()
std::string Condition::Condition::Dump (unsigned short ntabs = 0) const pure virtual
Implemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, Condition::All, and Condition::Source.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag().
Eval() [1/6]
void Condition::Condition::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const virtual
Reimplemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Homeworld, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, and Condition::All.
References anonymous_namespace{Conditions.cpp}::EvalImpl().
Referenced by Condition::Number::Eval(), Condition::Turn::Eval(), Condition::EmpireAffiliation::Eval(), Condition::Homeworld::Eval(), Condition::Type::Eval(), Condition::Building::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Condition::InOrIsSystem::Eval(), Condition::OnPlanet::Eval(), Condition::ObjectID::Eval(), Condition::PlanetType::Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::Enqueued::Eval(), Condition::FocusType::Eval(), Condition::StarType::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::Chance::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), Condition::EmpireHasAdoptedPolicy::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::OwnerHasShipPartAvailable::Eval(), Condition::VisibleToEmpire::Eval(), Condition::WithinDistance::Eval(), Condition::WithinStarlaneJumps::Eval(), Condition::CanAddStarlaneConnection::Eval(), Condition::ExploredByEmpire::Eval(), Condition::FleetSupplyableByEmpire::Eval(), Condition::ResourceSupplyConnectedByEmpire::Eval(), Condition::OrderedBombarded::Eval(), Condition::ValueTest::Eval(), Condition::Location::Eval(), Condition::CombatTarget::Eval(), and ValueRef::Statistic< T, V >::GetConditionMatches().
Eval() [2/6]
void Condition::Condition::Eval (const ScriptingContext & parent_context, Effect::TargetSet & matches, Effect::TargetSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const
References GetOptionsDB().
Eval() [3/6]
void Condition::Condition::Eval (const ScriptingContext & parent_context, ObjectSet & matches) const
Tests all objects in universe as NON_MATCHES.
Eval() [4/6]
void Condition::Condition::Eval (const ScriptingContext & parent_context, Effect::TargetSet & matches) const
Tests all objects in universe as NON_MATCHES.
References GetOptionsDB().
Eval() [5/6]
bool Condition::Condition::Eval (const ScriptingContext & parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
Eval() [6/6]
bool Condition::Condition::Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
If this condition is not invariant to
GetCheckSum()
virtual unsigned int Condition::Condition::GetCheckSum () const inline virtual
Reimplemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, Condition::All, and Condition::Source.
GetDefaultInitialCandidateObjects()
void Condition::Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const virtual
Reimplemented in Condition::Or, Condition::And, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::Building, Condition::Type, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::None, Condition::SortedNumberOf, and Condition::Source.
References anonymous_namespace{Conditions.cpp}::AddAllObjectsSet(), and ScriptingContext::ContextObjects().
Referenced by Condition::SortedNumberOf::GetDefaultInitialCandidateObjects(), Condition::Type::GetDefaultInitialCandidateObjects(), Condition::And::GetDefaultInitialCandidateObjects(), and Condition::Or::GetDefaultInitialCandidateObjects().
LocalCandidateInvariant()
bool Condition::Condition::LocalCandidateInvariant () const inline
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
This funciton is provided for consistency with ValueRef, which may not depend on the local candidiate of an enclosing condition.
Match()
bool Condition::Condition::Match (const ScriptingContext & local_context) const private virtual
Reimplemented in Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::Turn, Condition::Number, and Condition::Source.
operator!=()
bool Condition::Condition::operator!= (const Condition & rhs) const inline
operator==()
bool Condition::Condition::operator== (const Condition & rhs) const virtual
Reimplemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, Condition::All, and Condition::Source.
Referenced by Condition::All::operator==(), Condition::Source::operator==(), Condition::None::operator==(), Condition::RootCandidate::operator==(), Condition::Target::operator==(), Condition::Capital::operator==(), Condition::Monster::operator==(), Condition::Armed::operator==(), Condition::Stationary::operator==(), Condition::Aggressive::operator==(), Condition::CanColonize::operator==(), and Condition::CanProduceShips::operator==().
RootCandidateInvariant()
bool Condition::Condition::RootCandidateInvariant () const inline
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Referenced by Condition::Turn::Eval(), Condition::EmpireAffiliation::Eval(), Condition::Homeworld::Eval(), Condition::Type::Eval(), Condition::Building::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Condition::InOrIsSystem::Eval(), Condition::OnPlanet::Eval(), Condition::ObjectID::Eval(), Condition::PlanetType::Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::Enqueued::Eval(), Condition::FocusType::Eval(), Condition::StarType::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::Chance::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), Condition::EmpireHasAdoptedPolicy::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::OwnerHasShipPartAvailable::Eval(), Condition::VisibleToEmpire::Eval(), Condition::WithinDistance::Eval(), Condition::WithinStarlaneJumps::Eval(), Condition::CanAddStarlaneConnection::Eval(), Condition::ExploredByEmpire::Eval(), Condition::FleetSupplyableByEmpire::Eval(), Condition::ResourceSupplyConnectedByEmpire::Eval(), Condition::OrderedBombarded::Eval(), Condition::ValueTest::Eval(), Condition::Location::Eval(), Condition::CombatTarget::Eval(), Condition::InOrIsSystem::GetDefaultInitialCandidateObjects(), Condition::OnPlanet::GetDefaultInitialCandidateObjects(), and Condition::ObjectID::GetDefaultInitialCandidateObjects().
SetTopLevelContent()
virtual void Condition::Condition::SetTopLevelContent (const std::string & content_name) pure virtual
Implemented in Condition::Described, Condition::OrderedAlternativesOf, Condition::Not, Condition::Or, Condition::And, Condition::CombatTarget, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Aggressive, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipPartAvailable, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireHasAdoptedPolicy, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::OnPlanet, Condition::InOrIsSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::SortedNumberOf, Condition::Turn, Condition::Number, Condition::All, and Condition::Source.
SourceInvariant()
bool Condition::Condition::SourceInvariant () const inline
Returns true iff this condition's evaluation does not reference the source object.
References Effect::Dump().
TargetInvariant()
bool Condition::Condition::TargetInvariant () const inline
Returns true iff this condition's evaluation does not reference the target object.
Friends And Related Function Documentation
MatchHelper
friend struct MatchHelper friend
Member Data Documentation
m_root_candidate_invariant
bool Condition::Condition::m_root_candidate_invariant = false protected
Referenced by Condition::Aggressive::Aggressive(), Condition::All::All(), Condition::And::And(), Condition::Armed::Armed(), Condition::Building::Building(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Condition::CanColonize::CanColonize(), Condition::CanProduceShips::CanProduceShips(), Condition::Capital::Capital(), Condition::Chance::Chance(), Condition::CombatTarget::CombatTarget(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), Condition::CreatedOnTurn::CreatedOnTurn(), Condition::Described::Described(), Condition::DesignHasHull::DesignHasHull(), Condition::DesignHasPart::DesignHasPart(), Condition::DesignHasPartClass::DesignHasPartClass(), Condition::EmpireAffiliation::EmpireAffiliation(), Condition::EmpireHasAdoptedPolicy::EmpireHasAdoptedPolicy(), Condition::EmpireMeterValue::EmpireMeterValue(), Condition::EmpireStockpileValue::EmpireStockpileValue(), Condition::Enqueued::Enqueued(), Condition::ExploredByEmpire::ExploredByEmpire(), Condition::FleetSupplyableByEmpire::FleetSupplyableByEmpire(), Condition::FocusType::FocusType(), Condition::HasSpecial::HasSpecial(), Condition::HasTag::HasTag(), Condition::Homeworld::Homeworld(), Condition::InOrIsSystem::InOrIsSystem(), Condition::Location::Location(), Condition::MeterValue::MeterValue(), Condition::Monster::Monster(), Condition::None::None(), Condition::Not::Not(), Condition::Number::Number(), Condition::NumberedShipDesign::NumberedShipDesign(), Condition::ObjectID::ObjectID(), Condition::OnPlanet::OnPlanet(), Condition::Or::Or(), Condition::OrderedAlternativesOf::OrderedAlternativesOf(), Condition::OrderedBombarded::OrderedBombarded(), Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable(), Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable(), Condition::OwnerHasShipPartAvailable::OwnerHasShipPartAvailable(), Condition::OwnerHasTech::OwnerHasTech(), Condition::PlanetEnvironment::PlanetEnvironment(), Condition::PlanetSize::PlanetSize(), Condition::PlanetType::PlanetType(), Condition::PredefinedShipDesign::PredefinedShipDesign(), Condition::ProducedByEmpire::ProducedByEmpire(), Condition::ResourceSupplyConnectedByEmpire::ResourceSupplyConnectedByEmpire(), Condition::RootCandidate::RootCandidate(), Condition::ShipPartMeterValue::ShipPartMeterValue(), Condition::SortedNumberOf::SortedNumberOf(), Condition::Source::Source(), Condition::Species::Species(), Condition::StarType::StarType(), Condition::Stationary::Stationary(), Condition::Target::Target(), Condition::Turn::Turn(), Condition::Type::Type(), Condition::ValueTest::ValueTest(), Condition::VisibleToEmpire::VisibleToEmpire(), Condition::WithinDistance::WithinDistance(), and Condition::WithinStarlaneJumps::WithinStarlaneJumps().
m_source_invariant
bool Condition::Condition::m_source_invariant = false protected
Referenced by Condition::Aggressive::Aggressive(), Condition::All::All(), Condition::And::And(), Condition::Armed::Armed(), Condition::Building::Building(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Condition::CanColonize::CanColonize(), Condition::CanProduceShips::CanProduceShips(), Condition::Capital::Capital(), Condition::Chance::Chance(), Condition::CombatTarget::CombatTarget(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), Condition::CreatedOnTurn::CreatedOnTurn(), Condition::Described::Described(), Condition::DesignHasHull::DesignHasHull(), Condition::DesignHasPart::DesignHasPart(), Condition::DesignHasPartClass::DesignHasPartClass(), Condition::EmpireAffiliation::EmpireAffiliation(), Condition::EmpireHasAdoptedPolicy::EmpireHasAdoptedPolicy(), Condition::EmpireMeterValue::EmpireMeterValue(), Condition::EmpireStockpileValue::EmpireStockpileValue(), Condition::Enqueued::Enqueued(), Condition::ExploredByEmpire::ExploredByEmpire(), Condition::FleetSupplyableByEmpire::FleetSupplyableByEmpire(), Condition::FocusType::FocusType(), Condition::HasSpecial::HasSpecial(), Condition::HasTag::HasTag(), Condition::Homeworld::Homeworld(), Condition::InOrIsSystem::InOrIsSystem(), Condition::Location::Location(), Condition::MeterValue::MeterValue(), Condition::Monster::Monster(), Condition::None::None(), Condition::Not::Not(), Condition::Number::Number(), Condition::NumberedShipDesign::NumberedShipDesign(), Condition::ObjectID::ObjectID(), Condition::OnPlanet::OnPlanet(), Condition::Or::Or(), Condition::OrderedAlternativesOf::OrderedAlternativesOf(), Condition::OrderedBombarded::OrderedBombarded(), Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable(), Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable(), Condition::OwnerHasShipPartAvailable::OwnerHasShipPartAvailable(), Condition::OwnerHasTech::OwnerHasTech(), Condition::PlanetEnvironment::PlanetEnvironment(), Condition::PlanetSize::PlanetSize(), Condition::PlanetType::PlanetType(), Condition::PredefinedShipDesign::PredefinedShipDesign(), Condition::ProducedByEmpire::ProducedByEmpire(), Condition::ResourceSupplyConnectedByEmpire::ResourceSupplyConnectedByEmpire(), Condition::RootCandidate::RootCandidate(), Condition::ShipPartMeterValue::ShipPartMeterValue(), Condition::SortedNumberOf::SortedNumberOf(), Condition::Source::Source(), Condition::Species::Species(), Condition::StarType::StarType(), Condition::Stationary::Stationary(), Condition::Target::Target(), Condition::Turn::Turn(), Condition::Type::Type(), Condition::ValueTest::ValueTest(), Condition::VisibleToEmpire::VisibleToEmpire(), Condition::WithinDistance::WithinDistance(), and Condition::WithinStarlaneJumps::WithinStarlaneJumps().
m_target_invariant
bool Condition::Condition::m_target_invariant = false protected
Referenced by Condition::Aggressive::Aggressive(), Condition::All::All(), Condition::And::And(), Condition::Armed::Armed(), Condition::Building::Building(), Condition::CanAddStarlaneConnection::CanAddStarlaneConnection(), Condition::CanColonize::CanColonize(), Condition::CanProduceShips::CanProduceShips(), Condition::Capital::Capital(), Condition::Chance::Chance(), Condition::CombatTarget::CombatTarget(), Condition::ContainedBy::ContainedBy(), Condition::Contains::Contains(), Condition::CreatedOnTurn::CreatedOnTurn(), Condition::Described::Described(), Condition::DesignHasHull::DesignHasHull(), Condition::DesignHasPart::DesignHasPart(), Condition::DesignHasPartClass::DesignHasPartClass(), Condition::EmpireAffiliation::EmpireAffiliation(), Condition::EmpireHasAdoptedPolicy::EmpireHasAdoptedPolicy(), Condition::EmpireMeterValue::EmpireMeterValue(), Condition::EmpireStockpileValue::EmpireStockpileValue(), Condition::Enqueued::Enqueued(), Condition::ExploredByEmpire::ExploredByEmpire(), Condition::FleetSupplyableByEmpire::FleetSupplyableByEmpire(), Condition::FocusType::FocusType(), Condition::HasSpecial::HasSpecial(), Condition::HasTag::HasTag(), Condition::Homeworld::Homeworld(), Condition::InOrIsSystem::InOrIsSystem(), Condition::Location::Location(), Condition::MeterValue::MeterValue(), Condition::Monster::Monster(), Condition::None::None(), Condition::Not::Not(), Condition::Number::Number(), Condition::NumberedShipDesign::NumberedShipDesign(), Condition::ObjectID::ObjectID(), Condition::OnPlanet::OnPlanet(), Condition::Or::Or(), Condition::OrderedAlternativesOf::OrderedAlternativesOf(), Condition::OrderedBombarded::OrderedBombarded(), Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable(), Condition::OwnerHasShipDesignAvailable::OwnerHasShipDesignAvailable(), Condition::OwnerHasShipPartAvailable::OwnerHasShipPartAvailable(), Condition::OwnerHasTech::OwnerHasTech(), Condition::PlanetEnvironment::PlanetEnvironment(), Condition::PlanetSize::PlanetSize(), Condition::PlanetType::PlanetType(), Condition::PredefinedShipDesign::PredefinedShipDesign(), Condition::ProducedByEmpire::ProducedByEmpire(), Condition::ResourceSupplyConnectedByEmpire::ResourceSupplyConnectedByEmpire(), Condition::RootCandidate::RootCandidate(), Condition::ShipPartMeterValue::ShipPartMeterValue(), Condition::SortedNumberOf::SortedNumberOf(), Condition::Source::Source(), Condition::Species::Species(), Condition::StarType::StarType(), Condition::Stationary::Stationary(), Condition::Target::Target(), Condition::Turn::Turn(), Condition::Type::Type(), Condition::ValueTest::ValueTest(), Condition::VisibleToEmpire::VisibleToEmpire(), Condition::WithinDistance::WithinDistance(), and Condition::WithinStarlaneJumps::WithinStarlaneJumps().
The documentation for this struct was generated from the following files:
Condition.h
Conditions.cpp