FreeOrion: InitialStealthEvent Struct Reference
InitialStealthEvent Struct Reference
InitialStealthEvent describes the initially stealthy combatants.
#include <CombatEvents.h>
Public Types
typedef std::map< int, std::map< int, Visibility > > EmpireToObjectVisibilityMap
Public Member Functions
InitialStealthEvent ()
InitialStealthEvent (const EmpireToObjectVisibilityMap &x)
std::string CombatLogDescription (int viewing_empire_id) const override
Generate the combat log description.
std::string DebugString () const override
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
Return true if there are no details;.
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
Return true if there are no sub events;.
virtual std::string CombatLogDetails (int viewing_empire_id) const
Generate the combat log details.
virtual bool FlattenSubEvents () const
Return true if sub events are to be flattened on display;.
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
Return principal faction.
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
EmpireToObjectVisibilityMap empire_to_object_visibility
Friends
class boost::serialization::access
Detailed Description
InitialStealthEvent describes the initially stealthy combatants.
Note: Because it is initialized with the unfiltered stealth information it contains information not availble to all empires.
Member Typedef Documentation
EmpireToObjectVisibilityMap
typedef std::map<int, std::map<int, Visibility> > InitialStealthEvent::EmpireToObjectVisibilityMap
Constructor & Destructor Documentation
InitialStealthEvent() [1/2]
InitialStealthEvent::InitialStealthEvent ()
InitialStealthEvent() [2/2]
InitialStealthEvent::InitialStealthEvent (const EmpireToObjectVisibilityMap & x)
Member Function Documentation
CombatLogDescription()
std::string InitialStealthEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description.
Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References ALL_EMPIRES, DebugLogger, empire_to_object_visibility, anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormatList(), ObjectMap::get(), Objects(), and UserString().
DebugString()
std::string InitialStealthEvent::DebugString () const override virtual
Implements CombatEvent.
References ALL_EMPIRES, empire_to_object_visibility, anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), ObjectMap::get(), and Objects().
serialize()
template<class Archive > template void InitialStealthEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), and empire_to_object_visibility.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
empire_to_object_visibility
EmpireToObjectVisibilityMap InitialStealthEvent::empire_to_object_visibility private
Referenced by CombatLogDescription(), DebugString(), and serialize().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp