FreeOrion: WaitingForGameStart Struct Reference
WaitingForGameStart Struct Reference
The human client state in which a game has been started but the start of game message hasn't been received yet from the server.
#include <HumanClientFSM.h>
Public Types
typedef boost::statechart::state< WaitingForGameStart, PlayingGame > Base
typedef boost::mpl::list< boost::statechart::custom_reaction< GameStart > > reactions
Public Member Functions
WaitingForGameStart (my_context ctx)
~WaitingForGameStart ()
boost::statechart::result react (const GameStart &msg)
Detailed Description
The human client state in which a game has been started but the start of game message hasn't been received yet from the server.
Member Typedef Documentation
Base
typedef boost::statechart::state<WaitingForGameStart, PlayingGame> WaitingForGameStart::Base
reactions
typedef boost::mpl::list< boost::statechart::custom_reaction<GameStart> > WaitingForGameStart::reactions
Constructor & Destructor Documentation
WaitingForGameStart()
WaitingForGameStart::WaitingForGameStart (my_context ctx)
References TraceLogger.
~WaitingForGameStart()
WaitingForGameStart::~WaitingForGameStart ()
References TraceLogger.
Member Function Documentation
react()
boost::statechart::result WaitingForGameStart::react (const GameStart & msg)
References ALL_EMPIRES, DebugLogger, Empires(), ExtractGameStartMessageData(), GetCombatLogManager(), GetGalaxySetupData(), GetGameRules(), GetSpeciesManager(), GetSupplyManager(), GetUniverse(), INVALID_GAME_TURN, anonymous_namespace{AIWrapper.cpp}::PlayerID(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), GameRules::SetFromStrings(), and TraceLogger.
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp