FreeOrion: anonymous_namespace{ResearchWnd.cpp}::QueueRow Struct Reference
anonymous_namespace{ResearchWnd.cpp}::QueueRow Struct Reference
Public Member Functions
QueueRow (GG::X w, const ResearchQueue::Element &queue_element)
void Init ()
void PreRender () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
const ResearchQueue::Element elem
std::shared_ptr< GG::Control > panel
Constructor & Destructor Documentation
QueueRow()
anonymous_namespace{ResearchWnd.cpp}::QueueRow::QueueRow (GG::X w, const ResearchQueue::Element & queue_element) inline
Member Function Documentation
Init()
void anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init () inline
References GetEmpire(), GetOptionsDB(), GetTech(), Tech::PerTurnCost(), Tech::ResearchCost(), Empire::ResearchProgress(), Empire::TechResearched(), and TechRowBrowseWnd().
PreRender()
void anonymous_namespace{ResearchWnd.cpp}::QueueRow::PreRender () inline override
SizeMove()
void anonymous_namespace{ResearchWnd.cpp}::QueueRow::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline override
Member Data Documentation
elem
const ResearchQueue::Element anonymous_namespace{ResearchWnd.cpp}::QueueRow::elem
panel
std::shared_ptr<GG::Control> anonymous_namespace{ResearchWnd.cpp}::QueueRow::panel
The documentation for this struct was generated from the following file:
ResearchWnd.cpp