FreeOrion: IncapacitationEvent Struct Reference
IncapacitationEvent Struct Reference
Created when an object becomes unable to fight anymore, eg.
#include <CombatEvents.h>
Public Member Functions
IncapacitationEvent ()
IncapacitationEvent (int bout_, int object_id_, int object_owner_id_)
std::string CombatLogDescription (int viewing_empire_id) const override
Generate the combat log description.
std::string DebugString () const override
boost::optional< int > PrincipalFaction (int viewing_empire_id) const override
Return principal faction.
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
Return true if there are no details;.
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
Return true if there are no sub events;.
virtual std::string CombatLogDetails (int viewing_empire_id) const
Generate the combat log details.
virtual bool FlattenSubEvents () const
Return true if sub events are to be flattened on display;.
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Public Attributes
int bout = 0
int object_id = INVALID_OBJECT_ID
int object_owner_id = ALL_EMPIRES
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
Created when an object becomes unable to fight anymore, eg.
a ship is destroyed or a planet loses all defence
Constructor & Destructor Documentation
IncapacitationEvent() [1/2]
IncapacitationEvent::IncapacitationEvent () explicit
IncapacitationEvent() [2/2]
IncapacitationEvent::IncapacitationEvent (int bout_, int object_id_, int object_owner_id_)
Member Function Documentation
CombatLogDescription()
std::string IncapacitationEvent::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description.
Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormat(), ObjectMap::get(), GetEmpire(), object_id, object_owner_id, Objects(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), and UserString().
DebugString()
std::string IncapacitationEvent::DebugString () const override virtual
Implements CombatEvent.
References bout, object_id, and object_owner_id.
PrincipalFaction()
boost::optional< int > IncapacitationEvent::PrincipalFaction (int viewing_empire_id) const override virtual
Return principal faction.
PrincipalFaction is used by UnorderedEvents to sort the display of events by Facton. The principal faction should be the faction most active in the event (i.e. the attacker in a WeaponEvent). It is from the perspective of the viewing_empire_id. Some events like BoutBegin are not associated with any faction.
Reimplemented from CombatEvent.
References object_owner_id.
serialize()
template<typename Archive > template void IncapacitationEvent::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References BOOST_CLASS_VERSION(), bout, object_id, and object_owner_id.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
bout
int IncapacitationEvent::bout = 0
Referenced by DebugString(), and serialize().
object_id
int IncapacitationEvent::object_id = INVALID_OBJECT_ID
Referenced by CombatLogDescription(), DebugString(), and serialize().
object_owner_id
int IncapacitationEvent::object_owner_id = ALL_EMPIRES
Referenced by CombatLogDescription(), DebugString(), PrincipalFaction(), and serialize().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp