FreeOrion: StealthChangeEvent::StealthChangeEventDetail Struct Reference
StealthChangeEvent::StealthChangeEventDetail Struct Reference
#include <CombatEvents.h>
Public Member Functions
StealthChangeEventDetail ()
StealthChangeEventDetail (int attacker_id_, int target_id_, int attacker_empire_, int target_empire_, Visibility new_visibility_)
std::string CombatLogDescription (int viewing_empire_id) const override
Generate the combat log description.
std::string DebugString () const override
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Public Member Functions inherited from CombatEvent
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
Return true if there are no details;.
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
Return true if there are no sub events;.
virtual std::string CombatLogDetails (int viewing_empire_id) const
Generate the combat log details.
virtual bool FlattenSubEvents () const
Return true if sub events are to be flattened on display;.
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
Return principal faction.
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Public Attributes
int attacker_empire_id
int attacker_id
int target_empire_id
int target_id
Visibility visibility
Friends
class boost::serialization::access
Constructor & Destructor Documentation
StealthChangeEventDetail() [1/2]
StealthChangeEvent::StealthChangeEventDetail::StealthChangeEventDetail ()
StealthChangeEventDetail() [2/2]
StealthChangeEvent::StealthChangeEventDetail::StealthChangeEventDetail (int attacker_id_, int target_id_, int attacker_empire_, int target_empire_, Visibility new_visibility_)
Member Function Documentation
CombatLogDescription()
std::string StealthChangeEvent::StealthChangeEventDetail::CombatLogDescription (int viewing_empire_id) const override virtual
Generate the combat log description.
Describe the result of a combat event (i.e. what happened).
Implements CombatEvent.
References attacker_empire_id, attacker_id, anonymous_namespace{CombatEvents.cpp}::EmpireLink(), anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), FlexibleFormat(), target_empire_id, target_id, and UserString().
DebugString()
std::string StealthChangeEvent::StealthChangeEventDetail::DebugString () const override virtual
Implements CombatEvent.
References ALL_EMPIRES, attacker_empire_id, attacker_id, anonymous_namespace{CombatEvents.cpp}::FighterOrPublicNameLink(), and visibility.
serialize()
template<typename Archive > template void StealthChangeEvent::StealthChangeEventDetail::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version)
References attacker_empire_id, attacker_id, BOOST_CLASS_VERSION(), target_empire_id, target_id, and visibility.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
attacker_empire_id
int StealthChangeEvent::StealthChangeEventDetail::attacker_empire_id
Referenced by CombatLogDescription(), DebugString(), and serialize().
attacker_id
int StealthChangeEvent::StealthChangeEventDetail::attacker_id
Referenced by CombatLogDescription(), DebugString(), and serialize().
target_empire_id
int StealthChangeEvent::StealthChangeEventDetail::target_empire_id
Referenced by CombatLogDescription(), and serialize().
target_id
int StealthChangeEvent::StealthChangeEventDetail::target_id
Referenced by CombatLogDescription(), and serialize().
visibility
Visibility StealthChangeEvent::StealthChangeEventDetail::visibility
Referenced by DebugString(), and serialize().
The documentation for this struct was generated from the following files:
CombatEvents.h
CombatEvents.cpp