FreeOrion: Condition::Or Struct Reference
Condition::Or Struct Reference final
Matches all objects that match at least one Condition in operands.
#include <Conditions.h>
Public Member Functions
Or (std::vector< std::unique_ptr< Condition >> &&operands)
Or (std::unique_ptr< Condition > &&operand1, std::unique_ptr< Condition > &&operand2, std::unique_ptr< Condition > &&operand3=nullptr, std::unique_ptr< Condition > &&operand4=nullptr)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
virtual void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::Condition
Condition ()
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< std::unique_ptr< Condition > > m_operands
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches all objects that match at least one Condition in operands.
Constructor & Destructor Documentation
Or() [1/2]
Condition::Or::Or (std::vector< std::unique_ptr< Condition >> && operands) explicit
References m_operands, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, Condition::Condition::m_target_invariant, and Condition::anonymous_namespace{Conditions.cpp}::SetConditionVariance().
Or() [2/2]
Condition::Or::Or (std::unique_ptr< Condition > && operand1, std::unique_ptr< Condition > && operand2, std::unique_ptr< Condition > && operand3 = nullptr, std::unique_ptr< Condition > && operand4 = nullptr)
References m_operands, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, Condition::Condition::m_target_invariant, and Condition::anonymous_namespace{Conditions.cpp}::SetConditionVariance().
Member Function Documentation
Description()
std::string Condition::Or::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References m_operands, and UserString().
Dump()
std::string Condition::Or::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_operands.
Eval()
void Condition::Or::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ErrorLogger, m_operands, Condition::MATCHES, and Condition::NON_MATCHES.
GetCheckSum()
unsigned int Condition::Or::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_operands, and TraceLogger.
operator==()
bool Condition::Or::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_operands.
RootCandidateInvariant()
bool Condition::Or::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::Condition.
References Condition::INVARIANT, and Condition::Condition::m_root_candidate_invariant.
serialize()
template<typename Archive > void Condition::Or::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Or::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_operands.
SourceInvariant()
bool Condition::Or::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::Condition.
References Condition::INVARIANT, and Condition::Condition::m_source_invariant.
TargetInvariant()
bool Condition::Or::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::Condition.
References Condition::INVARIANT, and Condition::Condition::m_target_invariant.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_operands
std::vector<std::unique_ptr<Condition> > Condition::Or::m_operands private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), operator==(), Or(), and SetTopLevelContent().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp