FreeOrion: Condition::DesignHasPartClass Struct Reference
Condition::DesignHasPartClass Struct Reference
#include <Condition.h>
Public Member Functions
DesignHasPartClass (ShipPartClass part_class, ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high)
virtual ~DesignHasPartClass ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ShipPartClass m_class
ValueRef::ValueRefBase< int > * m_high
ValueRef::ValueRefBase< int > * m_low
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches ships whose ShipDesign has >= low and < high of ship parts of the specified part_class
Constructor & Destructor Documentation
Condition::DesignHasPartClass::DesignHasPartClass (ShipPartClass part_class, ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high) inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::DesignHasPartClass::~DesignHasPartClass () virtual
References Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
Member Function Documentation
std::string Condition::DesignHasPartClass::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, to_string(), and UserString().
std::string Condition::DesignHasPartClass::Dump () const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and UserString().
void Condition::DesignHasPartClass::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::RootCandidateInvariant().
unsigned int Condition::DesignHasPartClass::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and TraceLogger.
void Condition::DesignHasPartClass::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddShipSet().
bool Condition::DesignHasPartClass::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
bool Condition::DesignHasPartClass::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, m_class, Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
bool Condition::DesignHasPartClass::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
template<class Archive > void Condition::DesignHasPartClass::serialize (Archive & ar, const unsigned int version) private
void Condition::DesignHasPartClass::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::DesignHasPartClass::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::DesignHasPartClass::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ShipPartClass Condition::DesignHasPartClass::m_class private
Referenced by operator==().
ValueRef::ValueRefBase<int>* Condition::DesignHasPartClass::m_high private
ValueRef::ValueRefBase<int>* Condition::DesignHasPartClass::m_low private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp