FreeOrion: Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch Struct Reference
Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch Struct Reference
Public Member Functions
EnqueuedSimpleMatch (BuildType build_type, const std::string &name, int design_id, int empire_id, int low, int high)
bool operator() (std::shared_ptr< const UniverseObject > candidate) const
Public Attributes
BuildType m_build_type
int m_design_id
int m_empire_id
int m_high
int m_low
std::string m_name
Constructor & Destructor Documentation
EnqueuedSimpleMatch()
Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::EnqueuedSimpleMatch (BuildType build_type, const std::string & name, int design_id, int empire_id, int low, int high) inline
Member Function Documentation
operator()()
bool Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::operator() (std::shared_ptr< const UniverseObject > candidate) const inline
References ALL_EMPIRES, Empires(), GetEmpire(), Empire::GetProductionQueue(), Condition::Enqueued::m_build_type, Condition::Enqueued::m_design_id, Condition::Enqueued::m_empire_id, Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and Condition::anonymous_namespace{Conditions.cpp}::NumberOnQueue().
Member Data Documentation
m_build_type
BuildType Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_build_type
m_design_id
int Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_design_id
m_empire_id
int Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_empire_id
m_high
int Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_high
m_low
int Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_low
m_name
std::string Condition::anonymous_namespace{Conditions.cpp}::EnqueuedSimpleMatch::m_name
The documentation for this struct was generated from the following file:
Conditions.cpp