FreeOrion: anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter Struct Reference
anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter Struct Reference
Public Member Functions
EdgeVisibilityFilter ()
EdgeVisibilityFilter (const SystemGraph *graph, int empire_id)
template<typename EdgeDescriptor >
bool operator() (const EdgeDescriptor &edge) const
Private Attributes
int m_empire_id = ALL_EMPIRES
const SystemGraph * m_graph = nullptr
Constructor & Destructor Documentation
EdgeVisibilityFilter() [1/2]
anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::EdgeVisibilityFilter () inline
EdgeVisibilityFilter() [2/2]
anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::EdgeVisibilityFilter (const SystemGraph * graph, int empire_id) inline
References ErrorLogger.
Member Function Documentation
operator()()
template<typename EdgeDescriptor > bool anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::operator() (const EdgeDescriptor & edge) const inline
References EmpireKnownObjects(), ErrorLogger, ObjectMap::get(), and boost::get().
Member Data Documentation
m_empire_id
int anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::m_empire_id = ALL_EMPIRES private
m_graph
const SystemGraph* anonymous_namespace{Pathfinder.cpp}::GraphImpl::EdgeVisibilityFilter::m_graph = nullptr private
The documentation for this struct was generated from the following file:
Pathfinder.cpp