FreeOrion: Condition::InOrIsSystem Struct Reference
Condition::InOrIsSystem Struct Reference final
Matches all objects that are in the system with the indicated system_id or that are that system.
#include <Conditions.h>
Public Member Functions
InOrIsSystem (std::unique_ptr< ValueRef::ValueRef< int >> &&system_id)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const Condition &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Condition::Condition
Condition ()=default
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_system_id
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
Matches all objects that are in the system with the indicated system_id or that are that system.
If system_id is INVALID_OBJECT_ID then matches all objects in any system
Constructor & Destructor Documentation
InOrIsSystem()
Condition::InOrIsSystem::InOrIsSystem (std::unique_ptr< ValueRef::ValueRef< int >> && system_id)
References Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, m_system_id, and Condition::Condition::m_target_invariant.
Member Function Documentation
Description()
std::string Condition::InOrIsSystem::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), INVALID_OBJECT_ID, m_system_id, Objects(), and UserString().
Dump()
std::string Condition::InOrIsSystem::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), and m_system_id.
Eval()
void Condition::InOrIsSystem::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), anonymous_namespace{Conditions.cpp}::EvalImpl(), INVALID_OBJECT_ID, m_system_id, and Condition::Condition::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::InOrIsSystem::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_system_id, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::InOrIsSystem::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::Condition.
References anonymous_namespace{Conditions.cpp}::AddAllObjectsSet(), ScriptingContext::condition_root_candidate, ScriptingContext::ContextObjects(), ObjectMap::find(), ObjectMap::get(), m_system_id, and Condition::Condition::RootCandidateInvariant().
Match()
bool Condition::InOrIsSystem::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_local_candidate, ErrorLogger, INVALID_OBJECT_ID, and m_system_id.
operator==()
bool Condition::InOrIsSystem::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, and m_system_id.
SetTopLevelContent()
void Condition::InOrIsSystem::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_system_id.
Member Data Documentation
m_system_id
std::unique_ptr<ValueRef::ValueRef<int> > Condition::InOrIsSystem::m_system_id private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), GetDefaultInitialCandidateObjects(), InOrIsSystem(), Match(), Condition::anonymous_namespace{Conditions.cpp}::InSystemSimpleMatch::operator()(), operator==(), and SetTopLevelContent().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp