FreeOrion: HostileVisitor Struct Reference
HostileVisitor Struct Reference
#include <UniverseObjectVisitors.h>
Public Member Functions
HostileVisitor (int viewing_empire, int owning_empire=ALL_EMPIRES)
virtual ~HostileVisitor ()
auto Visit (const std::shared_ptr< UniverseObject > &obj) const -> std::shared_ptr< UniverseObject > override
Public Member Functions inherited from UniverseObjectVisitor
virtual ~UniverseObjectVisitor ()
virtual auto Visit (const std::shared_ptr< Building > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Fleet > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Planet > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Ship > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< System > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Field > &obj) const -> std::shared_ptr< UniverseObject >
virtual auto Visit (const std::shared_ptr< Fighter > &obj) const -> std::shared_ptr< UniverseObject >
Public Attributes
int const owning_empire_id
int const viewing_empire_id
Constructor & Destructor Documentation
HostileVisitor()
HostileVisitor::HostileVisitor (int viewing_empire, int owning_empire = ALL_EMPIRES)
References ~HostileVisitor().
~HostileVisitor()
HostileVisitor::~HostileVisitor () virtual default
Referenced by HostileVisitor().
Member Function Documentation
Visit()
auto HostileVisitor::Visit (const std::shared_ptr< UniverseObject > & obj) const -> std::shared_ptr<UniverseObject> override virtual
Reimplemented from UniverseObjectVisitor.
References Empires(), and viewing_empire_id.
Member Data Documentation
owning_empire_id
int const HostileVisitor::owning_empire_id
viewing_empire_id
int const HostileVisitor::viewing_empire_id
Referenced by Visit().
The documentation for this struct was generated from the following files:
UniverseObjectVisitors.h
UniverseObjectVisitors.cpp