FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow Struct Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow Struct Reference
Public Member Functions
LoadGamePlayerRow (const PlayerSetupData &player_data, int player_id, const std::map< int, SaveGameEmpireData > &save_game_empire_data, bool disabled, bool in_game)
void CompleteConstruction () override
Public Member Functions inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
PlayerRow ()
PlayerRow (const PlayerSetupData &player_data, int player_id)
Private Member Functions
void EmpireChanged (GG::DropDownList::iterator selected_it)
void PlayerTypeChanged (Networking::ClientType type)
Private Attributes
std::shared_ptr< EmpireColorSelector > m_color_selector
std::shared_ptr< GG::DropDownList > m_empire_list
bool m_in_game
bool m_initial_disabled
const std::map< int, SaveGameEmpireData > & m_save_game_empire_data
Additional Inherited Members
Public Attributes inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
boost::signals2::signal< void()> DataChangedSignal
PlayerSetupData m_player_data
int m_player_id
Constructor & Destructor Documentation
LoadGamePlayerRow()
anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::LoadGamePlayerRow (const PlayerSetupData & player_data, int player_id, const std::map< int, SaveGameEmpireData > & save_game_empire_data, bool disabled, bool in_game) inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::CompleteConstruction () inline override
References ALL_EMPIRES, Networking::CLIENT_TYPE_AI_PLAYER, HumanClientApp::GetApp(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetHostTexture(), GetOptionsDB(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::GetReadyTexture(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerFontHeight(), anonymous_namespace{AIWrapper.cpp}::PlayerIsHost(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerReadyBrowseWidth(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowMargin(), ClientUI::Pts(), and UserString().
EmpireChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::EmpireChanged (GG::DropDownList::iterator selected_it) inline private
References ErrorLogger.
PlayerTypeChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::PlayerTypeChanged (Networking::ClientType type) inline private
Member Data Documentation
m_color_selector
std::shared_ptr<EmpireColorSelector> anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::m_color_selector private
m_empire_list
std::shared_ptr<GG::DropDownList> anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::m_empire_list private
m_in_game
bool anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::m_in_game private
m_initial_disabled
bool anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::m_initial_disabled private
m_save_game_empire_data
const std::map<int, SaveGameEmpireData>& anonymous_namespace{MultiplayerLobbyWnd.cpp}::LoadGamePlayerRow::m_save_game_empire_data private
The documentation for this struct was generated from the following file:
MultiplayerLobbyWnd.cpp