FreeOrion: Condition::PredefinedShipDesign Struct Reference
Condition::PredefinedShipDesign Struct Reference
#include <Condition.h>
Public Member Functions
PredefinedShipDesign (std::unique_ptr< ValueRef::ValueRefBase< std::string >> &&name)
PredefinedShipDesign (ValueRef::ValueRefBase< std::string > *name)
virtual ~PredefinedShipDesign ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ValueRef::ValueRefBase< std::string > > m_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches ships who ShipDesign is a predefined shipdesign with the name name
Constructor & Destructor Documentation
Condition::PredefinedShipDesign::PredefinedShipDesign (std::unique_ptr< ValueRef::ValueRefBase< std::string >> && name) explicit
Condition::PredefinedShipDesign::PredefinedShipDesign (ValueRef::ValueRefBase< std::string > * name) explicit
Condition::PredefinedShipDesign::~PredefinedShipDesign () virtual
Member Function Documentation
std::string Condition::PredefinedShipDesign::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), m_name, UserString(), and UserStringExists().
std::string Condition::PredefinedShipDesign::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_name.
void Condition::PredefinedShipDesign::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_name, and RootCandidateInvariant().
unsigned int Condition::PredefinedShipDesign::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_name, and TraceLogger.
bool Condition::PredefinedShipDesign::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, and m_name.
bool Condition::PredefinedShipDesign::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_name.
bool Condition::PredefinedShipDesign::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_name.
Referenced by Eval().
template<class Archive > void Condition::PredefinedShipDesign::serialize (Archive & ar, const unsigned int version) private
void Condition::PredefinedShipDesign::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_name.
bool Condition::PredefinedShipDesign::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_name.
bool Condition::PredefinedShipDesign::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_name.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::unique_ptr<ValueRef::ValueRefBase<std::string> > Condition::PredefinedShipDesign::m_name private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::PredefinedShipDesignSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp