FreeOrion: anonymous_namespace{ProductionWnd.cpp}::QueueRow Struct Reference
anonymous_namespace{ProductionWnd.cpp}::QueueRow Struct Reference
Public Member Functions
QueueRow (GG::X w, const ProductionQueue::Element &elem_, int queue_index_)
void CompleteConstruction () override
void Disable (bool b) override
void PreRender () override
void RowQuantChanged (int quantity, int blocksize)
Public Attributes
const ProductionQueue::Element elem
std::shared_ptr< QueueProductionItemPanel > panel
const int queue_index
boost::signals2::signal< void(int, int, int)> RowQuantChangedSignal
Constructor & Destructor Documentation
QueueRow()
anonymous_namespace{ProductionWnd.cpp}::QueueRow::QueueRow (GG::X w, const ProductionQueue::Element & elem_, int queue_index_) inline
References GGHumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), anonymous_namespace{ProductionWnd.cpp}::MARGIN, BuildDesignatorWnd::PRODUCTION_ITEM_DROP_TYPE, and anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd().
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{ProductionWnd.cpp}::QueueRow::CompleteConstruction () inline override
Disable()
void anonymous_namespace{ProductionWnd.cpp}::QueueRow::Disable (bool b) inline override
PreRender()
void anonymous_namespace{ProductionWnd.cpp}::QueueRow::PreRender () inline override
RowQuantChanged()
void anonymous_namespace{ProductionWnd.cpp}::QueueRow::RowQuantChanged (int quantity, int blocksize) inline
Member Data Documentation
elem
const ProductionQueue::Element anonymous_namespace{ProductionWnd.cpp}::QueueRow::elem
Referenced by anonymous_namespace{ProductionWnd.cpp}::ProdQueueListBox::ItemRightClickedImpl().
panel
std::shared_ptr<QueueProductionItemPanel> anonymous_namespace{ProductionWnd.cpp}::QueueRow::panel
queue_index
const int anonymous_namespace{ProductionWnd.cpp}::QueueRow::queue_index
RowQuantChangedSignal
boost::signals2::signal<void (int,int,int)> anonymous_namespace{ProductionWnd.cpp}::QueueRow::RowQuantChangedSignal mutable
The documentation for this struct was generated from the following file:
ProductionWnd.cpp