FreeOrion: ValueRef::NamedRef< T > Struct Template Reference
ValueRef::NamedRef< T > Struct Template Reference final
The NamedRef class.
#include <NamedValueRefManager.h>
Public Member Functions
NamedRef (std::string value_ref_name)
bool ConstantExpr () const override
std::string Description () const override
std::string Dump (unsigned short ntabs=0) const override
Returns a textual representation of the evaluation result with an empty/default context.
T Eval (const ScriptingContext &context) const override
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
unsigned int GetCheckSum () const override
const ValueRef< T > * GetValueRef () const
bool LocalCandidateInvariant () const override
bool operator== (const ValueRef< T > &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
Returns a textual representation that should be parseable to recreate this ValueRef.
bool SimpleIncrement () const override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from ValueRef::ValueRef< T >
ValueRef ()=default
virtual ~ValueRef ()=default
T Eval () const
Evaluates the expression tree with an empty context.
std::string EvalAsString () const final
Evaluates the expression tree with an empty context and retuns the a string representation of the result value iff the result type is supported (currently std::string, int, float, double, enum).
template<>
std::string EvalAsString () const
Returns a user-readable text description of this ValueRef.
template<>
std::string EvalAsString () const
Returns a user-readable text description of this ValueRef.
bool operator!= (const ValueRef< T > &rhs) const
Public Member Functions inherited from ValueRef::ValueRefBase
ValueRefBase ()=default
virtual ~ValueRefBase ()=default
std::string InvariancePattern () const
Private Attributes
std::string m_value_ref_name
Additional Inherited Members
Protected Attributes inherited from ValueRef::ValueRefBase
bool m_local_candidate_invariant = false
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
template<typename T>
struct ValueRef::NamedRef< T >
The NamedRef class.
Looks up a named ValueRef from the NamedValueRefManager
Constructor & Destructor Documentation
NamedRef()
template<typename T > ValueRef::NamedRef< T >::NamedRef (std::string value_ref_name)
References DebugLogger, and ValueRef::NamedRef< T >::m_value_ref_name.
Member Function Documentation
ConstantExpr()
template<typename T > bool ValueRef::NamedRef< T >::ConstantExpr () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
Description()
template<typename T > std::string ValueRef::NamedRef< T >::Description () const override virtual
Implements ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef(), and UserString().
Dump()
template<typename T > std::string ValueRef::NamedRef< T >::Dump (unsigned short ntabs = 0) const override virtual
Returns a textual representation of the evaluation result with an empty/default context.
Implements ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
Eval()
template<typename T > T ValueRef::NamedRef< T >::Eval (const ScriptingContext & context) const override virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Implements ValueRef::ValueRef< T >.
References DebugLogger, ErrorLogger, ValueRef::ValueRef< T >::Eval(), ValueRef::NamedRef< T >::m_value_ref_name, and TraceLogger.
GetCheckSum()
template<typename T > unsigned int ValueRef::NamedRef< T >::GetCheckSum () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References CheckSums::CheckSumCombine(), ValueRef::NamedRef< T >::m_value_ref_name, and TraceLogger.
GetValueRef()
template<typename T > const ValueRef< T > * ValueRef::NamedRef< T >::GetValueRef () const
References DebugLogger, and ValueRef::NamedRef< T >::m_value_ref_name.
Referenced by ValueRef::NamedRef< T >::ConstantExpr(), ValueRef::NamedRef< T >::Description(), ValueRef::NamedRef< T >::Dump(), ValueRef::NamedRef< T >::LocalCandidateInvariant(), ValueRef::NamedRef< T >::RootCandidateInvariant(), ValueRef::NamedRef< T >::SetTopLevelContent(), ValueRef::NamedRef< T >::SimpleIncrement(), ValueRef::NamedRef< T >::SourceInvariant(), and ValueRef::NamedRef< T >::TargetInvariant().
LocalCandidateInvariant()
template<typename T > bool ValueRef::NamedRef< T >::LocalCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
operator==()
template<typename T > bool ValueRef::NamedRef< T >::operator== (const ValueRef< T > & rhs) const override virtual
Reimplemented from ValueRef::ValueRef< T >.
References ValueRef::NamedRef< T >::m_value_ref_name.
RootCandidateInvariant()
template<typename T > bool ValueRef::NamedRef< T >::RootCandidateInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
SetTopLevelContent()
template<typename T > void ValueRef::NamedRef< T >::SetTopLevelContent (const std::string & content_name) override virtual
Returns a textual representation that should be parseable to recreate this ValueRef.
Reimplemented from ValueRef::ValueRefBase.
References ErrorLogger, and ValueRef::NamedRef< T >::GetValueRef().
SimpleIncrement()
template<typename T > bool ValueRef::NamedRef< T >::SimpleIncrement () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
SourceInvariant()
template<typename T > bool ValueRef::NamedRef< T >::SourceInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
TargetInvariant()
template<typename T > bool ValueRef::NamedRef< T >::TargetInvariant () const override virtual
Reimplemented from ValueRef::ValueRefBase.
References ValueRef::NamedRef< T >::GetValueRef().
Member Data Documentation
m_value_ref_name
template<typename T> std::string ValueRef::NamedRef< T >::m_value_ref_name private
Referenced by ValueRef::NamedRef< T >::Eval(), ValueRef::NamedRef< T >::GetCheckSum(), ValueRef::NamedRef< T >::GetValueRef(), ValueRef::NamedRef< T >::NamedRef(), and ValueRef::NamedRef< T >::operator==().
The documentation for this struct was generated from the following files:
NamedValueRefManager.h
NamedValueRefManager.cpp