FreeOrion: Condition::ShipPartMeterValue Struct Reference
Condition::ShipPartMeterValue Struct Reference
#include <Condition.h>
Public Member Functions
ShipPartMeterValue (ValueRef::ValueRefBase< std::string > *ship_part_name, MeterType meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
virtual ~ShipPartMeterValue ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
ValueRef::ValueRefBase< double > * m_high
ValueRef::ValueRefBase< double > * m_low
MeterType m_meter
ValueRef::ValueRefBase< std::string > * m_part_name
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches ships that have a ship part meter of type meter for part part whose current value is >= low and <= high.
Constructor & Destructor Documentation
Condition::ShipPartMeterValue::ShipPartMeterValue (ValueRef::ValueRefBase< std::string > * ship_part_name, MeterType meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::ShipPartMeterValue::~ShipPartMeterValue () virtual
References Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
Member Function Documentation
std::string Condition::ShipPartMeterValue::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Description(), FlexibleFormat(), Meter::LARGE_VALUE, Condition::Enqueued::m_high, Condition::Enqueued::m_low, UserString(), and UserStringExists().
std::string Condition::ShipPartMeterValue::Dump () const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::anonymous_namespace{Condition.cpp}::MeterTypeDumpString().
void Condition::ShipPartMeterValue::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), Meter::LARGE_VALUE, ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::RootCandidateInvariant().
bool Condition::ShipPartMeterValue::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Meter::LARGE_VALUE, Condition::Enqueued::m_high, and Condition::Enqueued::m_low.
bool Condition::ShipPartMeterValue::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and m_meter.
bool Condition::ShipPartMeterValue::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
void Condition::ShipPartMeterValue::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::ShipPartMeterValue::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::ShipPartMeterValue::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and ValueRef::ValueRefBase< T >::TargetInvariant().
Member Data Documentation
ValueRef::ValueRefBase<double>* Condition::ShipPartMeterValue::m_high private
ValueRef::ValueRefBase<double>* Condition::ShipPartMeterValue::m_low private
MeterType Condition::ShipPartMeterValue::m_meter private
Referenced by operator==().
ValueRef::ValueRefBase<std::string>* Condition::ShipPartMeterValue::m_part_name private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp