FreeOrion: Condition::Homeworld Struct Reference
Condition::Homeworld Struct Reference final
Matches planets that are a homeworld for any of the species specified in names.
#include <Condition.h>
Public Member Functions
Homeworld ()
Homeworld (std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string >>> &&names)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string > > > m_names
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches planets that are a homeworld for any of the species specified in names.
If names is empty, matches any planet that is a homeworld for any species in the current game Universe.
Constructor & Destructor Documentation
Homeworld() [1/2]
Condition::Homeworld::Homeworld ()
Homeworld() [2/2]
Condition::Homeworld::Homeworld (std::vector< std::unique_ptr< ValueRef::ValueRefBase< std::string >>> && names) explicit
Member Function Documentation
Description()
std::string Condition::Homeworld::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References Eval(), FlexibleFormat(), m_names, and UserString().
Dump()
std::string Condition::Homeworld::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_names.
Eval()
void Condition::Homeworld::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_names, and RootCandidateInvariant().
Referenced by Description().
GetCheckSum()
unsigned int Condition::Homeworld::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_names, and TraceLogger.
GetDefaultInitialCandidateObjects()
void Condition::Homeworld::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddPlanetSet().
Match()
bool Condition::Homeworld::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, GetPlanet(), SpeciesManager::GetSpecies(), GetSpeciesManager(), m_names, and parse::species().
operator==()
bool Condition::Homeworld::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_names.
RootCandidateInvariant()
bool Condition::Homeworld::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_names.
Referenced by Eval().
serialize()
template<class Archive > void Condition::Homeworld::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Homeworld::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_names.
SourceInvariant()
bool Condition::Homeworld::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_names.
TargetInvariant()
bool Condition::Homeworld::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_names.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_names
std::vector<std::unique_ptr<ValueRef::ValueRefBase<std::string> > > Condition::Homeworld::m_names private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), and TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp