FreeOrion: Condition::DesignHasPart Struct Reference
Condition::DesignHasPart Struct Reference
#include <Condition.h>
Public Member Functions
DesignHasPart (ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< int > *low=nullptr, ValueRef::ValueRefBase< int > *high=nullptr)
virtual ~DesignHasPart ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< int > * m_high
ValueRef::ValueRefBase< int > * m_low
ValueRef::ValueRefBase< std::string > * m_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all ships whose ShipDesign has >= low and < high of the ship part specified by name.
Constructor & Destructor Documentation
Condition::DesignHasPart::DesignHasPart (ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< int > * low = nullptr, ValueRef::ValueRefBase< int > * high = nullptr) inline
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::DesignHasPart::~DesignHasPart () virtual
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::m_name.
Member Function Documentation
std::string Condition::DesignHasPart::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, UserString(), and UserStringExists().
std::string Condition::DesignHasPart::Dump () const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::m_name.
void Condition::DesignHasPart::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and Condition::Enqueued::RootCandidateInvariant().
void Condition::DesignHasPart::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddShipSet().
bool Condition::DesignHasPart::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), IMPOSSIBLY_LARGE_TURN, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::m_name.
bool Condition::DesignHasPart::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, Condition::Enqueued::m_high, Condition::Enqueued::m_low, and Condition::Enqueued::m_name.
bool Condition::DesignHasPart::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
template<class Archive > void Condition::DesignHasPart::serialize (Archive & ar, const unsigned int version) private
void Condition::DesignHasPart::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::DesignHasPart::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::DesignHasPart::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References Condition::Enqueued::m_high, Condition::Enqueued::m_low, Condition::Enqueued::m_name, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<int>* Condition::DesignHasPart::m_high private
ValueRef::ValueRefBase<int>* Condition::DesignHasPart::m_low private
ValueRef::ValueRefBase<std::string>* Condition::DesignHasPart::m_name private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp