FreeOrion: Condition::CanAddStarlaneConnection Struct Reference
Condition::CanAddStarlaneConnection Struct Reference
#include <Condition.h>
Public Member Functions
CanAddStarlaneConnection (ConditionBase *condition)
virtual ~CanAddStarlaneConnection ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ConditionBase * m_condition
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches objects that are in systems that could have starlanes added between them and all (not just one) of the systems containing (or that are) one of the objects matched by condition. "Could have starlanes added" means that a lane would be geometrically acceptable, meaning it wouldn't cross any other lanes, pass too close to another system, or be too close in angle to an existing lane.
Constructor & Destructor Documentation
Condition::CanAddStarlaneConnection::CanAddStarlaneConnection (ConditionBase * condition) inline explicit
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::CanAddStarlaneConnection::~CanAddStarlaneConnection () virtual
Member Function Documentation
std::string Condition::CanAddStarlaneConnection::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), and UserString().
std::string Condition::CanAddStarlaneConnection::Dump () const override virtual
Implements Condition::ConditionBase.
References DumpIndent(), and g_indent.
void Condition::CanAddStarlaneConnection::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), and Condition::OwnerHasShipPartAvailable::RootCandidateInvariant().
unsigned int Condition::CanAddStarlaneConnection::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
bool Condition::CanAddStarlaneConnection::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, and ErrorLogger.
bool Condition::CanAddStarlaneConnection::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER.
bool Condition::CanAddStarlaneConnection::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
template<class Archive > void Condition::CanAddStarlaneConnection::serialize (Archive & ar, const unsigned int version) private
void Condition::CanAddStarlaneConnection::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
bool Condition::CanAddStarlaneConnection::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
bool Condition::CanAddStarlaneConnection::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ConditionBase* Condition::CanAddStarlaneConnection::m_condition private
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp