FreeOrion: Condition::HasTag Struct Reference
Condition::HasTag Struct Reference
#include <Condition.h>
Public Member Functions
HasTag (const std::string &name)
HasTag (ValueRef::ValueRefBase< std::string > *name=nullptr)
virtual ~HasTag ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< std::string > * m_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects that have the tag tag.
Constructor & Destructor Documentation
Condition::HasTag::HasTag (const std::string & name) explicit
Condition::HasTag::HasTag (ValueRef::ValueRefBase< std::string > * name = nullptr) inline explicit
References Effect::Dump(), Condition::NON_MATCHES, and operator==().
Condition::HasTag::~HasTag () virtual
References m_name.
Member Function Documentation
std::string Condition::HasTag::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), FlexibleFormat(), m_name, UserString(), and UserStringExists().
std::string Condition::HasTag::Dump () const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_name.
void Condition::HasTag::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), m_name, and RootCandidateInvariant().
Referenced by Condition::PlanetType::Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), and Condition::Species::Description().
unsigned int Condition::HasTag::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), m_name, and TraceLogger.
bool Condition::HasTag::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), and m_name.
bool Condition::HasTag::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_name.
bool Condition::HasTag::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
Referenced by Eval(), Condition::CreatedOnTurn::Eval(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Condition::InSystem::Eval(), Condition::ObjectID::Eval(), Condition::PlanetType::Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::InSystem::GetDefaultInitialCandidateObjects(), and Condition::ObjectID::GetDefaultInitialCandidateObjects().
template<class Archive > void Condition::HasTag::serialize (Archive & ar, const unsigned int version) private
void Condition::HasTag::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::HasTag::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::HasTag::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<std::string>* Condition::HasTag::m_name private
Referenced by Description(), Dump(), Eval(), GetCheckSum(), Match(), Condition::anonymous_namespace{Condition.cpp}::HasTagSimpleMatch::operator()(), operator==(), RootCandidateInvariant(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~HasTag().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp