FreeOrion: Condition::Described Struct Reference
Condition::Described Struct Reference final
Matches whatever its subcondition matches, but has a customized description string that is returned by Description() by looking up in the stringtable.
#include <Condition.h>
Public Member Functions
Described (std::unique_ptr< ConditionBase > &&condition, const std::string &desc_stringtable_key)
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const override
Returns true iff this condition's evaluation does not reference the target object.
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::unique_ptr< ConditionBase > m_condition
std::string m_desc_stringtable_key
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant = UNKNOWN_INVARIANCE
Invariance m_source_invariant = UNKNOWN_INVARIANCE
Invariance m_target_invariant = UNKNOWN_INVARIANCE
Detailed Description
Matches whatever its subcondition matches, but has a customized description string that is returned by Description() by looking up in the stringtable.
Constructor & Destructor Documentation
Described()
Condition::Described::Described (std::unique_ptr< ConditionBase > && condition, const std::string & desc_stringtable_key) inline
References Condition::NON_MATCHES, and operator==().
Member Function Documentation
Description()
std::string Condition::Described::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References UserString(), and UserStringExists().
Dump()
std::string Condition::Described::Dump (unsigned short ntabs = 0) const inline override virtual
Implements Condition::ConditionBase.
Eval()
void Condition::Described::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ErrorLogger.
GetCheckSum()
unsigned int Condition::Described::GetCheckSum () const override virtual
Reimplemented from Condition::ConditionBase.
References CheckSums::CheckSumCombine(), and TraceLogger.
operator==()
bool Condition::Described::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_desc_stringtable_key.
RootCandidateInvariant()
bool Condition::Described::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
serialize()
template<class Archive > void Condition::Described::serialize (Archive & ar, const unsigned int version) private
SetTopLevelContent()
void Condition::Described::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
SourceInvariant()
bool Condition::Described::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
TargetInvariant()
bool Condition::Described::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_condition
std::unique_ptr<ConditionBase> Condition::Described::m_condition private
m_desc_stringtable_key
std::string Condition::Described::m_desc_stringtable_key private
Referenced by operator==().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp