FreeOrion: ProductionQueue Struct Reference
ProductionQueue Struct Reference
#include <ProductionQueue.h>
Classes
struct Element
The type of a single element in the production queue.
struct ProductionItem
The type that specifies a single production item (BuildType and name string).
Public Types
typedef QueueType::const_iterator const_iterator
The const ProductionQueue iterator type.
typedef QueueType::iterator iterator
The ProductionQueue iterator type.
typedef std::deque< Element > QueueType
Public Member Functions
Structors
ProductionQueue (int empire_id)
Accessors
int ProjectsInProgress () const
Returns the number of production projects currently (perhaps partially) funded.
float TotalPPsSpent () const
Returns the number of PPs currently spent on the projects in this queue.
int EmpireID () const
Returns the number of production projects currently (perhaps partially) funded.
std::map< std::set< int >, float > AvailablePP (const std::shared_ptr< ResourcePool > &industry_pool) const
Returns map from sets of object ids that can share resources to amount of PP available in those groups of objects ; does not include stockpile.
const std::map< std::set< int >, float > & AllocatedPP () const
Returns map from sets of object ids that can share resources to amount of PP allocated to production queue elements that have build locations in systems in the group.
const std::map< std::set< int >, float > & AllocatedStockpilePP () const
Returns map from sets of object ids that can share resources to amount of stockpile PP allocated to production queue elements that have build locations in systems in the group.
float StockpileCapacity () const
Returns sum of stockpile meters of empire-owned objects.
float ExpectedNewStockpileAmount () const
Returns the value expected for the Imperial Stockpile for the next turn, based on the current ProductionQueue allocations.
float ExpectedProjectTransferToStockpile () const
Returns the PP amount expected to be transferred via stockpiling projects to the Imperial Stockpile for the next turn, based on the current ProductionQueue allocations.
std::set< std::set< int > > ObjectsWithWastedPP (const std::shared_ptr< ResourcePool > &industry_pool) const
Returns sets of object ids that have more available than allocated PP.
bool empty () const
Returns the number of production projects currently (perhaps partially) funded.
unsigned int size () const
Returns the number of production projects currently (perhaps partially) funded.
const_iterator begin () const
Returns the number of production projects currently (perhaps partially) funded.
const_iterator end () const
Returns the number of production projects currently (perhaps partially) funded.
const_iterator find (int i) const
Returns the number of production projects currently (perhaps partially) funded.
const Element & operator[] (int i) const
Returns the number of production projects currently (perhaps partially) funded.
const_iterator find (boost::uuids::uuid uuid) const
Returns the number of production projects currently (perhaps partially) funded.
int IndexOfUUID (boost::uuids::uuid uuid) const
Returns the number of production projects currently (perhaps partially) funded.
Private Member Functions
template<typename Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_empire_id = ALL_EMPIRES
float m_expected_new_stockpile_amount = 0.0f
float m_expected_project_transfer_to_stockpile = 0.0f
std::map< std::set< int >, float > m_object_group_allocated_pp
std::map< std::set< int >, float > m_object_group_allocated_stockpile_pp
int m_projects_in_progress = 0
QueueType m_queue
Friends
class boost::serialization::access
Mutators
boost::signals2::signal< void()> ProductionQueueChangedSignal
Recalculates the PPs spent on and number of turns left for each project in the queue.
void Update ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
void push_back (const Element &element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void insert (iterator it, const Element &element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void erase (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator erase (iterator it)
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator begin ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator end ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
iterator find (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Element & operator[] (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
void clear ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Member Typedef Documentation
const_iterator
typedef QueueType::const_iterator ProductionQueue::const_iterator
The const ProductionQueue iterator type.
Dereference yields a Element.
iterator
typedef QueueType::iterator ProductionQueue::iterator
The ProductionQueue iterator type.
Dereference yields a Element.
QueueType
typedef std::deque<Element> ProductionQueue::QueueType
Constructor & Destructor Documentation
ProductionQueue()
ProductionQueue::ProductionQueue (int empire_id)
Member Function Documentation
AllocatedPP()
const std::map< std::set< int >, float > & ProductionQueue::AllocatedPP () const
Returns map from sets of object ids that can share resources to amount of PP allocated to production queue elements that have build locations in systems in the group.
References m_object_group_allocated_pp.
Referenced by anonymous_namespace{MapWnd.cpp}::GetResPoolLaneInfo(), ProductionWnd::UpdateInfoPanel(), and FreeOrionPython::WrapEmpire().
AllocatedStockpilePP()
const std::map< std::set< int >, float > & ProductionQueue::AllocatedStockpilePP () const
Returns map from sets of object ids that can share resources to amount of stockpile PP allocated to production queue elements that have build locations in systems in the group.
References m_object_group_allocated_stockpile_pp.
Referenced by MapWnd::RefreshIndustryResourceIndicator(), and ProductionWnd::UpdateInfoPanel().
AvailablePP()
std::map< std::set< int >, float > ProductionQueue::AvailablePP (const std::shared_ptr< ResourcePool > & industry_pool) const
Returns map from sets of object ids that can share resources to amount of PP available in those groups of objects ; does not include stockpile.
TODO: Is there any reason to keep this method in addition to the more specific information directly available from the empire? This should probably at least be renamed to clarify it is non-stockpile output.
References ErrorLogger.
Referenced by ObjectsWithWastedPP(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), Update(), ProductionWnd::UpdateInfoPanel(), and FreeOrionPython::WrapEmpire().
begin() [1/2]
ProductionQueue::const_iterator ProductionQueue::begin () const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
Referenced by Empire::ConquerProductionQueueItemsAtLocation(), erase(), find(), IndexOfUUID(), Empire::MoveProductionWithinQueue(), and Empire::PlaceProductionOnQueue().
begin() [2/2]
ProductionQueue::iterator ProductionQueue::begin ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
clear()
void ProductionQueue::clear ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_object_group_allocated_pp, m_projects_in_progress, m_queue, and ProductionQueueChangedSignal.
Referenced by Empire::Eliminate().
EmpireID()
int ProductionQueue::EmpireID () const inline
Returns the number of production projects currently (perhaps partially) funded.
Referenced by FreeOrionPython::WrapEmpire().
empty()
bool ProductionQueue::empty () const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
Referenced by FreeOrionPython::WrapEmpire().
end() [1/2]
ProductionQueue::const_iterator ProductionQueue::end () const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
Referenced by ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), Empire::ConquerProductionQueueItemsAtLocation(), ProductionWnd::DeleteQueueItem(), erase(), find(), IndexOfUUID(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), ProductionWnd::QueueItemDuped(), ProductionWnd::QueueItemMoved(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), and ProductionWnd::QueueItemUseImperialPP().
end() [2/2]
ProductionQueue::iterator ProductionQueue::end ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
erase() [1/2]
void ProductionQueue::erase (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References begin(), and m_queue.
Referenced by Empire::ConquerProductionQueueItemsAtLocation(), Empire::MoveProductionWithinQueue(), and Empire::RemoveProductionFromQueue().
erase() [2/2]
ProductionQueue::iterator ProductionQueue::erase (iterator it)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References end(), and m_queue.
ExpectedNewStockpileAmount()
float ProductionQueue::ExpectedNewStockpileAmount () const inline
Returns the value expected for the Imperial Stockpile for the next turn, based on the current ProductionQueue allocations.
Referenced by MapWnd::RefreshIndustryResourceIndicator().
ExpectedProjectTransferToStockpile()
float ProductionQueue::ExpectedProjectTransferToStockpile () const inline
Returns the PP amount expected to be transferred via stockpiling projects to the Imperial Stockpile for the next turn, based on the current ProductionQueue allocations.
References anonymous_namespace{XMLDoc.cpp}::element, and anonymous_namespace{EncyclopediaParser.cpp}::insert.
Referenced by MapWnd::RefreshIndustryResourceIndicator().
find() [1/3]
ProductionQueue::const_iterator ProductionQueue::find (int i) const
Returns the number of production projects currently (perhaps partially) funded.
References begin(), end(), and size().
Referenced by ProductionWnd::ChangeBuildQuantityBlockSlot(), ProductionWnd::ChangeBuildQuantitySlot(), ProductionWnd::DeleteQueueItem(), IndexOfUUID(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), ProductionWnd::QueueItemDuped(), ProductionWnd::QueueItemMoved(), ProductionWnd::QueueItemPaused(), ProductionWnd::QueueItemRallied(), ProductionWnd::QueueItemSplit(), and ProductionWnd::QueueItemUseImperialPP().
find() [2/3]
ProductionQueue::const_iterator ProductionQueue::find (boost::uuids::uuid uuid) const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
find() [3/3]
ProductionQueue::iterator ProductionQueue::find (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References begin(), end(), and size().
IndexOfUUID()
int ProductionQueue::IndexOfUUID (boost::uuids::uuid uuid) const
Returns the number of production projects currently (perhaps partially) funded.
References begin(), end(), and find().
insert()
void ProductionQueue::insert (iterator it, const Element & element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
Referenced by Empire::MoveProductionWithinQueue(), Empire::PlaceProductionOnQueue(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAllocatedPP_P(), anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithAvailablePP_P(), and anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P().
ObjectsWithWastedPP()
std::set< std::set< int > > ProductionQueue::ObjectsWithWastedPP (const std::shared_ptr< ResourcePool > & industry_pool) const
Returns sets of object ids that have more available than allocated PP.
References AvailablePP(), ErrorLogger, and m_object_group_allocated_pp.
Referenced by anonymous_namespace{EmpireWrapper.cpp}::PlanetsWithWastedPP_P(), FreeOrionPython::WrapEmpire(), and MapWnd::ZoomToSystemWithWastedPP().
operator[]() [1/2]
const ProductionQueue::Element & ProductionQueue::operator[] (int i) const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
operator[]() [2/2]
ProductionQueue::Element & ProductionQueue::operator[] (int i)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
ProjectsInProgress()
int ProductionQueue::ProjectsInProgress () const
Returns the number of production projects currently (perhaps partially) funded.
References m_projects_in_progress.
push_back()
void ProductionQueue::push_back (const Element & element)
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References m_queue.
Referenced by Empire::ConquerProductionQueueItemsAtLocation(), and Empire::PlaceProductionOnQueue().
serialize()
template<typename Archive > template void ProductionQueue::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
References ResearchQueue::m_empire_id, ResearchQueue::m_projects_in_progress, ResearchQueue::m_queue, serialize< freeorion_bin_iarchive >(), serialize< freeorion_bin_oarchive >(), serialize< freeorion_xml_iarchive >(), and serialize< freeorion_xml_oarchive >().
size()
unsigned int ProductionQueue::size () const
Returns the number of production projects currently (perhaps partially) funded.
References m_queue.
Referenced by Empire::AllowUseImperialPP(), BuildDesignatorWnd::CenterOnBuild(), Empire::DuplicateProductionItem(), find(), anonymous_namespace{AIWrapper.cpp}::IssueAllowStockpileProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueChangeProductionQuantityOrder(), anonymous_namespace{AIWrapper.cpp}::IssueDequeueProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssuePauseProductionOrder(), anonymous_namespace{AIWrapper.cpp}::IssueRequeueProductionOrder(), Empire::MoveProductionWithinQueue(), Empire::PauseProduction(), Empire::PlaceProductionOnQueue(), Empire::ProductionStatus(), Empire::RemoveProductionFromQueue(), Empire::ResumeProduction(), BuildDesignatorWnd::SetBuild(), Empire::SetProductionQuantity(), Empire::SetProductionQuantityAndBlocksize(), Empire::SetProductionRallyPoint(), Empire::SplitIncompleteProductionItem(), and FreeOrionPython::WrapEmpire().
StockpileCapacity()
float ProductionQueue::StockpileCapacity () const
Returns sum of stockpile meters of empire-owned objects.
References ALL_EMPIRES, m_empire_id, METER_STOCKPILE, and Objects().
Referenced by anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), MapWnd::RefreshIndustryResourceIndicator(), Update(), and ProductionWnd::UpdateInfoPanel().
TotalPPsSpent()
float ProductionQueue::TotalPPsSpent () const
Returns the number of PPs currently spent on the projects in this queue.
References m_object_group_allocated_pp.
Referenced by MapWnd::RefreshIndustryResourceIndicator(), ProductionWnd::UpdateInfoPanel(), and FreeOrionPython::WrapEmpire().
Update()
void ProductionQueue::Update ()
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
References AvailablePP(), anonymous_namespace{ProductionQueue.cpp}::CalculateNewStockpile(), DebugLogger, anonymous_namespace{XMLDoc.cpp}::element, anonymous_namespace{ProductionQueue.cpp}::EPSILON, ErrorLogger, GetEmpire(), Empire::GetResourcePool(), INVALID_OBJECT_ID, m_empire_id, m_expected_new_stockpile_amount, m_expected_project_transfer_to_stockpile, m_object_group_allocated_pp, m_object_group_allocated_stockpile_pp, m_projects_in_progress, m_queue, Empire::ProducibleItem(), Empire::ProductionCostAndTime(), ProductionQueueChangedSignal, ProductionQueue::Element::progress, RE_INDUSTRY, ProductionQueue::Element::remaining, Empire::ResourceOutput(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), StockpileCapacity(), TraceLogger, ProductionQueue::Element::turns_left_to_completion, and ProductionQueue::Element::turns_left_to_next_item.
Referenced by Empire::UpdateProductionQueue().
Friends And Related Function Documentation
boost::serialization::access
friend class boost::serialization::access friend
Member Data Documentation
m_empire_id
int ProductionQueue::m_empire_id = ALL_EMPIRES private
Referenced by StockpileCapacity(), and Update().
m_expected_new_stockpile_amount
float ProductionQueue::m_expected_new_stockpile_amount = 0.0f private
Referenced by Update().
m_expected_project_transfer_to_stockpile
float ProductionQueue::m_expected_project_transfer_to_stockpile = 0.0f private
Referenced by Update().
m_object_group_allocated_pp
std::map<std::set<int>, float> ProductionQueue::m_object_group_allocated_pp private
Referenced by AllocatedPP(), clear(), ObjectsWithWastedPP(), TotalPPsSpent(), and Update().
m_object_group_allocated_stockpile_pp
std::map<std::set<int>, float> ProductionQueue::m_object_group_allocated_stockpile_pp private
Referenced by AllocatedStockpilePP(), and Update().
m_projects_in_progress
int ProductionQueue::m_projects_in_progress = 0 private
Referenced by clear(), ProjectsInProgress(), and Update().
m_queue
QueueType ProductionQueue::m_queue private
Referenced by begin(), clear(), empty(), end(), erase(), find(), insert(), operator[](), push_back(), size(), and Update().
ProductionQueueChangedSignal
boost::signals2::signal<void ()> ProductionQueue::ProductionQueueChangedSignal mutable
Recalculates the PPs spent on and number of turns left for each project in the queue.
Also determines the number of projects in progress, and the industry consumed by projects in each resource-sharing group of systems. Does not actually "spend" the PP; a later call to empire->CheckProductionProgress() will actually spend PP, remove items from queue and create them in the universe.
Referenced by clear(), BuildingsPanel::CompleteConstruction(), and Update().
The documentation for this struct was generated from the following files:
ProductionQueue.h
ProductionQueue.cpp
SerializeEmpire.cpp