FreeOrion: anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow Struct Reference
anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow Struct Reference
Public Member Functions
EmptyPlayerRow ()
void CompleteConstruction () override
Public Member Functions inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
PlayerRow ()
PlayerRow (const PlayerSetupData &player_data, int player_id)
Private Member Functions
void PlayerTypeChanged (Networking::ClientType type)
Additional Inherited Members
Public Attributes inherited from anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRow
boost::signals2::signal< void()> DataChangedSignal
PlayerSetupData m_player_data
int m_player_id
Constructor & Destructor Documentation
EmptyPlayerRow()
anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::EmptyPlayerRow () inline
Member Function Documentation
CompleteConstruction()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::CompleteConstruction () inline override
References Networking::INVALID_CLIENT_TYPE, and anonymous_namespace{MultiplayerLobbyWnd.cpp}::PlayerRowHeight().
PlayerTypeChanged()
void anonymous_namespace{MultiplayerLobbyWnd.cpp}::EmptyPlayerRow::PlayerTypeChanged (Networking::ClientType type) inline private
References anonymous_namespace{MultiplayerLobbyWnd.cpp}::LOBBY_WND_HEIGHT(), and anonymous_namespace{MultiplayerLobbyWnd.cpp}::LOBBY_WND_WIDTH().
The documentation for this struct was generated from the following file:
MultiplayerLobbyWnd.cpp