FreeOrion: anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo Struct Reference
anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo Struct Reference
Public Member Functions
bool HasAttackers () const
bool HasUnlauchedArmedFighters (const CombatInfo &combat_info) const
Public Attributes
std::set< int > attacker_ids
Member Function Documentation
HasAttackers()
bool anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasAttackers () const inline
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CanSomeoneAttackSomething().
HasUnlauchedArmedFighters()
bool anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::HasUnlauchedArmedFighters (const CombatInfo & combat_info) const inline
References CombatInfo::destroyed_object_ids, ObjectMap::find(), ScriptingCombatInfo::objects, and anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths().
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CanSomeoneAttackSomething().
Member Data Documentation
attacker_ids
std::set<int> anonymous_namespace{CombatSystem.cpp}::EmpireCombatInfo::attacker_ids
The documentation for this struct was generated from the following file:
CombatSystem.cpp