FreeOrion: Condition::EmpireHasAdoptedPolicy Struct Reference
Condition::EmpireHasAdoptedPolicy Struct Reference final
Matches all objects if the empire with id empire_id has adopted the imperial policy with name name.
#include <Conditions.h>
Public Member Functions
EmpireHasAdoptedPolicy (std::unique_ptr< ValueRef::ValueRef< int >> &&empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> &&name)
EmpireHasAdoptedPolicy (std::unique_ptr< ValueRef::ValueRef< std::string >> &&name)
virtual ~EmpireHasAdoptedPolicy ()
std::string Description (bool negated=false) const override
std::string Dump (unsigned short ntabs=0) const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const override
unsigned int GetCheckSum () const override
bool operator== (const Condition &rhs) const override
void SetTopLevelContent (const std::string &content_name) override
Public Member Functions inherited from Condition::Condition
Condition ()=default
virtual ~Condition ()
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches, Effect::TargetSet &non_matches, SearchDomain search_domain=SearchDomain::NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
Tests all objects in universe as NON_MATCHES.
void Eval (const ScriptingContext &parent_context, Effect::TargetSet &matches) const
Tests all objects in universe as NON_MATCHES.
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition.
bool operator!= (const Condition &rhs) const
bool RootCandidateInvariant () const
Returns true iff this condition's evaluation does not reference the RootCandidate objects.
bool SourceInvariant () const
Returns true iff this condition's evaluation does not reference the source object.
bool TargetInvariant () const
Returns true iff this condition's evaluation does not reference the target object.
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
Private Attributes
std::unique_ptr< ValueRef::ValueRef< int > > m_empire_id
std::unique_ptr< ValueRef::ValueRef< std::string > > m_name
Additional Inherited Members
Protected Attributes inherited from Condition::Condition
bool m_root_candidate_invariant = false
bool m_source_invariant = false
bool m_target_invariant = false
Detailed Description
Matches all objects if the empire with id empire_id has adopted the imperial policy with name name.
Constructor & Destructor Documentation
EmpireHasAdoptedPolicy() [1/2]
Condition::EmpireHasAdoptedPolicy::EmpireHasAdoptedPolicy (std::unique_ptr< ValueRef::ValueRef< int >> && empire_id, std::unique_ptr< ValueRef::ValueRef< std::string >> && name)
References m_empire_id, m_name, Condition::Condition::m_root_candidate_invariant, Condition::Condition::m_source_invariant, and Condition::Condition::m_target_invariant.
EmpireHasAdoptedPolicy() [2/2]
Condition::EmpireHasAdoptedPolicy::EmpireHasAdoptedPolicy (std::unique_ptr< ValueRef::ValueRef< std::string >> && name) explicit
~EmpireHasAdoptedPolicy()
Condition::EmpireHasAdoptedPolicy::~EmpireHasAdoptedPolicy () virtual
Member Function Documentation
Description()
std::string Condition::EmpireHasAdoptedPolicy::Description (bool negated = false) const override virtual
Implements Condition::Condition.
References FlexibleFormat(), m_name, UserString(), and UserStringExists().
Dump()
std::string Condition::EmpireHasAdoptedPolicy::Dump (unsigned short ntabs = 0) const override virtual
Implements Condition::Condition.
References DumpIndent(), m_empire_id, and m_name.
Eval()
void Condition::EmpireHasAdoptedPolicy::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = SearchDomain::NON_MATCHES) const override virtual
Reimplemented from Condition::Condition.
References ScriptingContext::condition_root_candidate, Condition::Condition::Eval(), m_empire_id, m_name, Match(), Condition::MATCHES, Condition::NON_MATCHES, and Condition::Condition::RootCandidateInvariant().
GetCheckSum()
unsigned int Condition::EmpireHasAdoptedPolicy::GetCheckSum () const override virtual
Reimplemented from Condition::Condition.
References CheckSums::CheckSumCombine(), m_empire_id, m_name, and TraceLogger.
Match()
bool Condition::EmpireHasAdoptedPolicy::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::Condition.
References ALL_EMPIRES, ScriptingContext::condition_local_candidate, ErrorLogger, ScriptingContext::GetEmpire(), m_empire_id, and m_name.
Referenced by Eval().
operator==()
bool Condition::EmpireHasAdoptedPolicy::operator== (const Condition & rhs) const override virtual
Reimplemented from Condition::Condition.
References CHECK_COND_VREF_MEMBER, m_empire_id, and m_name.
SetTopLevelContent()
void Condition::EmpireHasAdoptedPolicy::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::Condition.
References m_empire_id, and m_name.
Member Data Documentation
m_empire_id
std::unique_ptr<ValueRef::ValueRef<int> > Condition::EmpireHasAdoptedPolicy::m_empire_id private
Referenced by Dump(), EmpireHasAdoptedPolicy(), Eval(), GetCheckSum(), Match(), operator==(), and SetTopLevelContent().
m_name
std::unique_ptr<ValueRef::ValueRef<std::string> > Condition::EmpireHasAdoptedPolicy::m_name private
Referenced by Description(), Dump(), EmpireHasAdoptedPolicy(), Eval(), GetCheckSum(), Match(), operator==(), and SetTopLevelContent().
The documentation for this struct was generated from the following files:
Conditions.h
Conditions.cpp