FreeOrion: TechTreeWnd.cpp File Reference
TechTreeWnd.cpp File Reference
#include "TechTreeWnd.h"
#include "ClientUI.h"
#include "CUIControls.h"
#include "CUIDrawUtil.h"
#include "CUIWnd.h"
#include "Sound.h"
#include "IconTextBrowseWnd.h"
#include "EncyclopediaDetailPanel.h"
#include "../client/human/GGHumanClientApp.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/OptionsDB.h"
#include "../util/ScopedTimer.h"
#include "../universe/Effects.h"
#include "../universe/Tech.h"
#include "../universe/UnlockableItem.h"
#include "../universe/ValueRef.h"
#include "../Empire/Empire.h"
#include "TechTreeLayout.h"
#include "TechTreeArcs.h"
#include "Hotkeys.h"
#include <GG/GLClientAndServerBuffer.h>
#include <GG/GUI.h>
#include <GG/Layout.h>
#include <GG/StaticGraphic.h>
#include <algorithm>
Classes
class TechTreeWnd::LayoutPanel
The window that contains the actual tech panels and dependency arcs.
class TechTreeWnd::LayoutPanel::LayoutSurface
class TechTreeWnd::LayoutPanel::TechPanel
Represents a single tech in the LayoutPanel.
class TechTreeWnd::TechListBox
class TechTreeWnd::TechListBox::TechRow
class TechTreeWnd::TechTreeControls
A panel of buttons that control how the tech tree is displayed: what categories, statuses and types of techs to show.
Namespaces
anonymous_namespace{TechTreeWnd.cpp}
Functions
void anonymous_namespace{TechTreeWnd.cpp}::AddOptions (OptionsDB &db)
constexpr double anonymous_namespace{TechTreeWnd.cpp}::ConstExprPow (double base, int pow)
GG::Y anonymous_namespace{TechTreeWnd.cpp}::TechPanelHeight ()
GG::X anonymous_namespace{TechTreeWnd.cpp}::TechPanelWidth ()
std::shared_ptr< GG::BrowseInfoWnd > TechRowBrowseWnd (const std::string &tech_name, int empire_id)
Returns a browse wnd for tech entries.
bool anonymous_namespace{TechTreeWnd.cpp}::TechVisible (const std::string &tech_name, const std::set< std::string > &categories_shown, const std::set< TechStatus > &statuses_shown)
Variables
constexpr double anonymous_namespace{TechTreeWnd.cpp}::INITIAL_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -5)
constexpr double anonymous_namespace{TechTreeWnd.cpp}::MAX_SCALE = ConstExprPow(ZOOM_STEP_SIZE, 10)
constexpr double anonymous_namespace{TechTreeWnd.cpp}::MIN_SCALE = ConstExprPow(ZOOM_STEP_SIZE, -25)
constexpr double anonymous_namespace{TechTreeWnd.cpp}::PI = 3.1415926535897932384626433
const std::string anonymous_namespace{TechTreeWnd.cpp}::RES_CONTROLS_WND_NAME = "research.control"
const std::string anonymous_namespace{TechTreeWnd.cpp}::RES_PEDIA_WND_NAME = "research.pedia"
bool anonymous_namespace{TechTreeWnd.cpp}::temp_bool = RegisterOptions(&AddOptions)
constexpr double anonymous_namespace{TechTreeWnd.cpp}::ZOOM_STEP_SIZE = 1.12
Function Documentation
TechRowBrowseWnd()
std::shared_ptr<GG::BrowseInfoWnd> TechRowBrowseWnd (const std::string & tech_name, int empire_id)
Returns a browse wnd for tech entries.
References Tech::Category(), DoubleToString(), ResearchQueue::end(), ResearchQueue::find(), FlexibleFormat(), GetEmpire(), GetTech(), Tech::PerTurnCost(), Tech::Prerequisites(), Tech::Researchable(), Tech::ResearchCost(), Tech::ResearchTime(), Tech::ShortDescription(), ClientUI::TechIcon(), and UserString().
Referenced by anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and TechTreeWnd::TechListBox::TechRow::Update().