FreeOrion: TechTreeWnd.h File Reference
TechTreeWnd.h File Reference
#include <boost/signals2/signal.hpp>
#include <GG/Wnd.h>
#include "../Empire/Empire.h"
Classes
class TechTreeWnd
Contains the tech graph layout, some controls to control what is visible in the tech layout, the tech navigator, and the tech detail window.
Functions
std::shared_ptr< GG::BrowseInfoWnd > TechRowBrowseWnd (const std::string &tech_name, int empire_id)
Returns a browse wnd for tech entries.
Function Documentation
TechRowBrowseWnd()
std::shared_ptr<GG::BrowseInfoWnd> TechRowBrowseWnd (const std::string & tech_name, int empire_id)
Returns a browse wnd for tech entries.
References Tech::Category(), DoubleToString(), ResearchQueue::end(), ResearchQueue::find(), FlexibleFormat(), GetEmpire(), GetTech(), Tech::PerTurnCost(), Tech::Prerequisites(), Tech::Researchable(), Tech::ResearchCost(), Tech::ResearchTime(), Tech::ShortDescription(), ClientUI::TechIcon(), and UserString().
Referenced by anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and TechTreeWnd::TechListBox::TechRow::Update().