FreeOrion: Tech.cpp File Reference
Tech.cpp File Reference
#include "Tech.h"
#include "Effect.h"
#include "UniverseObject.h"
#include "ObjectMap.h"
#include "../util/OptionsDB.h"
#include "../util/Logger.h"
#include "../util/AppInterface.h"
#include "../util/GameRules.h"
#include "../util/CheckSums.h"
#include "../util/ScopedTimer.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "ValueRef.h"
#include "Enums.h"
#include <boost/filesystem/fstream.hpp>
Namespaces
anonymous_namespace{Tech.cpp}
CheckSums
Functions
void anonymous_namespace{Tech.cpp}::AddRules (GameRules &rules)
const Tech * anonymous_namespace{Tech.cpp}::Cheapest (const std::vector< const Tech * > &next_techs, int empire_id)
void CheckSums::CheckSumCombine (unsigned int &sum, const ItemSpec &item)
void CheckSums::CheckSumCombine (unsigned int &sum, const TechCategory &cat)
const Tech * GetTech (const std::string &name)
Returns the Tech identified by name.
const TechCategory * GetTechCategory (const std::string &name)
returns a pointer to the tech category with the name name, or 0 if no such category exists
TechManager & GetTechManager ()
returns the singleton tech manager
void anonymous_namespace{Tech.cpp}::NextTechs (std::vector< const Tech * > &retval, const std::set< std::string > &known_techs, std::set< const Tech * > &checked_techs, TechManager::iterator it, TechManager::iterator end_it)
bool operator!= (const ItemSpec &lhs, const ItemSpec &rhs)
bool operator== (const ItemSpec &lhs, const ItemSpec &rhs)
Variables
bool anonymous_namespace{Tech.cpp}::temp_bool = RegisterGameRules(&AddRules)
Function Documentation
const Tech* GetTech (const std::string & name)
Returns the Tech identified by name.
Parameters
name The identifying name of the requested Tech.
Returns
A pointer to the Tech matching name or nullptr if no Tech with that name was found.
References TechManager::GetTech(), and GetTechManager().
Referenced by TechTreeLayout::AddNode(), Empire::AddTech(), TechTreeWnd::AddTechToResearchQueue(), TechManager::AllChildren(), TechTreeWnd::CenterOnTech(), TechManager::CheckPendingTechs(), Empire::CheckResearchProgress(), TechTreeLayout::DoLayout(), TechTreeLayout::Edge::Edge(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetEmpireTechProgress::Execute(), Effect::GiveEmpireTech::Execute(), TechTreeArcs::Impl::FillArcBuffer(), TechManager::FindFirstDependencyCycle(), TechManager::FindIllegalDependencies(), TechManager::FindRedundantDependency(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), Empire::HasResearchedPrereqAndUnresearchedPrereq(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), AIInterface::IssueDequeueTechOrder(), AIInterface::IssueEnqueueTechOrder(), Empire::LeastExpensiveEnqueuedTech(), Empire::MostExpensiveEnqueuedTech(), Empire::MostRPCostLeftEnqueuedTech(), anonymous_namespace{Tech.cpp}::NextTechs(), Empire::PlaceTechInQueue(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), TechManager::RecursivePrereqs(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::ReportedSpeciesForPlanet(), Empire::ResearchableTech(), Empire::ResearchProgress(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), anonymous_namespace{ResearchQueue.cpp}::SetTechQueueElementSpending(), Empire::SetTechResearchProgress(), TechRowBrowseWnd(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), ResearchQueue::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), FreeOrionPython::WrapEmpire(), and ClientUI::ZoomToTech().
const TechCategory* GetTechCategory (const std::string & name)
returns a pointer to the tech category with the name name, or 0 if no such category exists
References TechManager::GetTechCategory(), and GetTechManager().
Referenced by ClientUI::CategoryColor(), and ClientUI::CategoryIcon().
TechManager& GetTechManager ()
returns the singleton tech manager
References TechManager::GetTechManager().
Referenced by TechTreeWnd::AddTechToResearchQueue(), Empire::CheckResearchProgress(), CheckSumContent(), TechTreeWnd::TechTreeControls::CompleteConstruction(), TechTreeWnd::LayoutPanel::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), MessageWndEdit::FindGameWords(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), GetTech(), GetTechCategory(), TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::TechListBox::Populate(), TechTreeWnd::LayoutPanel::ShowAllCategories(), TechTreeWnd::TechListBox::ShowAllCategories(), IApp::StartBackgroundParsing(), ClientUI::TechIcon(), anonymous_namespace{EmpireWrapper.cpp}::TechRecursivePrereqs(), ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchableByEmpire(), ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchedByEmpire(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::TechsThatUnlockItem(), TechTreeWnd::ToggleAllCategories(), ResearchQueue::Update(), FreeOrionPython::WrapEmpire(), and ClientUI::ZoomToContent().
bool operator!= (const ItemSpec & lhs, const ItemSpec & rhs)
References TechManager::s_instance.
bool operator== (const ItemSpec & lhs, const ItemSpec & rhs)
References ItemSpec::name, and ItemSpec::type.