FreeOrion: Tech.h File Reference
Tech.h File Reference
#include <array>
#include <map>
#include <set>
#include <string>
#include <vector>
#include <boost/algorithm/string/case_conv.hpp>
#include <boost/multi_index/key_extractors.hpp>
#include <boost/multi_index/ordered_index.hpp>
#include <boost/multi_index_container.hpp>
#include <boost/optional/optional.hpp>
#include "EnumsFwd.h"
#include "../util/Export.h"
#include "../util/Pending.h"
Classes
class Tech
encasulates the data for a single FreeOrion technology
struct Tech::TechInfo
Helper struct for parsing tech definitions.
struct TechCategory
specifies a category of techs, with associated name, graphic (icon), and colour.
class TechManager
holds all FreeOrion techs.
struct TechManager::CategoryIndex
struct TechManager::NameIndex
struct ValueRef::ValueRef< T >
The base class for all ValueRef classes returning type T.
Namespaces
CheckSums
Effect
ValueRef
Functions
void CheckSums::CheckSumCombine (unsigned int &sum, const TechCategory &cat)
FO_COMMON_API const Tech * GetTech (const std::string &name)
Returns the Tech identified by name.
FO_COMMON_API const TechCategory * GetTechCategory (const std::string &name)
returns a pointer to the tech category with the name name, or 0 if no such category exists
FO_COMMON_API TechManager & GetTechManager ()
returns the singleton tech manager
Function Documentation
GetTech()
FO_COMMON_API const Tech* GetTech (const std::string & name)
Returns the Tech identified by name.
Parameters
name The identifying name of the requested Tech.
Returns
A pointer to the Tech matching name or nullptr if no Tech with that name was found.
GetTechCategory()
FO_COMMON_API const TechCategory* GetTechCategory (const std::string & name)
returns a pointer to the tech category with the name name, or 0 if no such category exists
References TechManager::GetTechCategory(), and GetTechManager().
Referenced by ClientUI::CategoryColor(), and ClientUI::CategoryIcon().
GetTechManager()
FO_COMMON_API TechManager& GetTechManager ()
returns the singleton tech manager
References TechManager::GetTechManager().
Referenced by TechTreeWnd::AddTechToResearchQueue(), CheckSumContent(), TechTreeWnd::LayoutPanel::CompleteConstruction(), TechTreeWnd::TechListBox::CompleteConstruction(), MessageWndEdit::FindGameWords(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), GetTech(), GetTechCategory(), TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::TechListBox::Populate(), TechTreeWnd::TechTreeControls::RefreshCategoryButtons(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), TechTreeWnd::LayoutPanel::ShowAllCategories(), TechTreeWnd::TechListBox::ShowAllCategories(), IApp::StartBackgroundParsing(), ClientUI::TechIcon(), ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchableByEmpire(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::TechsThatUnlockItem(), TechTreeWnd::ToggleAllCategories(), ResearchQueue::Update(), FreeOrionPython::WrapEmpire(), and ClientUI::ZoomToContent().