FreeOrion: UniverseGenerator.cpp File Reference
UniverseGenerator.cpp File Reference
#include "UniverseGenerator.h"
#include "../util/Directories.h"
#include "../util/Random.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/GameRules.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "Planet.h"
#include "System.h"
#include "Species.h"
#include "Enums.h"
#include "Condition.h"
#include <limits>
Classes
class Delauney::DTPoint
simple 2D point.
class Delauney::DTTriangle
list of three interger array indices, and some additional info about the triangle that the corresponding points make up, such as the circumcentre and radius, and a function to find if another point is in the circumcircle
class Delauney::SortValInt
Namespaces
anonymous_namespace{UniverseGenerator.cpp}
Delauney
Functions
bool anonymous_namespace{UniverseGenerator.cpp}::ConnectedWithin (int system1, int system2, int maxLaneJumps, const std::map< int, std::set< int >> &system_lanes)
Used by GenerateStarlanes.
void anonymous_namespace{UniverseGenerator.cpp}::CullAngularlyTooCloseLanes (double max_lane_uvect_dot_product, std::map< int, std::set< int >> &system_lanes, const std::map< int, std::shared_ptr< System >> &systems)
Removes lanes from passed graph that are angularly too close to each other.
void anonymous_namespace{UniverseGenerator.cpp}::CullTooLongLanes (double max_lane_length, std::map< int, std::set< int >> &system_lanes, const std::map< int, std::shared_ptr< System >> &systems)
Removes lanes from passed graph that are angularly too close to each other.
anonymous_namespace{UniverseGenerator.cpp}::DeclareThreadSafeLogger (effects)
std::list< Delauney::DTTriangle > Delauney::DelauneyTriangulate (const std::vector< std::shared_ptr< System >> &systems_vec)
Runs a Delauney Triangulation on a set of 2D points corresponding to the locations of the systems in systems_vec.
void GenerateStarlanes (int max_jumps_between_systems, int max_starlane_length)
Creates starlanes and adds them systems already generated.
void InitEmpires (const std::map< int, PlayerSetupData > &player_setup_data)
Creates Empires objects for each entry in player_setup_data with empire ids equal to the corresponding map keys (so that the calling code can know which empire belongs to which player).
int anonymous_namespace{UniverseGenerator.cpp}::IntSetMapSizeCount (const std::map< int, std::set< int >> &in)
void SetActiveMetersToTargetMaxCurrentValues (ObjectMap &object_map)
Set active meter current values equal to target/max meter current values.
bool SetEmpireHomeworld (Empire *empire, int planet_id, std::string species_name)
Sets empire homeworld This includes setting ownership, capital, species, preferred environment (planet type) for the species.
void SetNativePopulationValues (ObjectMap &object_map)
Set the population of unowned planets to a random fraction of their target values.
Function Documentation
GenerateStarlanes()
void GenerateStarlanes (int max_jumps_between_systems, int max_starlane_length)
Creates starlanes and adds them systems already generated.
References ObjectMap::all(), anonymous_namespace{UniverseGenerator.cpp}::ConnectedWithin(), anonymous_namespace{UniverseGenerator.cpp}::CullAngularlyTooCloseLanes(), anonymous_namespace{UniverseGenerator.cpp}::CullTooLongLanes(), DebugLogger, Delauney::DelauneyTriangulate(), ErrorLogger, GameRules::Get(), GetGameRules(), GetUniverse(), Universe::InitializeSystemGraph(), anonymous_namespace{UniverseGenerator.cpp}::IntSetMapSizeCount(), INVALID_OBJECT_ID, and Objects().
Referenced by FreeOrionPython::WrapServer().
InitEmpires()
void InitEmpires (const std::map< int, PlayerSetupData > & player_setup_data)
Creates Empires objects for each entry in player_setup_data with empire ids equal to the corresponding map keys (so that the calling code can know which empire belongs to which player).
References ALL_EMPIRES, EmpireManager::CreateEmpire(), DebugLogger, EmpireColors(), Empires(), ErrorLogger, RandZeroToOne(), EmpireManager::ResetDiplomacy(), EmpireManager::SetDiplomaticStatus(), to_string(), and UserString().
Referenced by ServerApp::GenerateUniverse().
SetActiveMetersToTargetMaxCurrentValues()
void SetActiveMetersToTargetMaxCurrentValues (ObjectMap & object_map)
Set active meter current values equal to target/max meter current values.
Useful when creating new object after applying effects.
References ObjectMap::all(), AssociatedMeterTypes(), and TraceLogger.
Referenced by ServerApp::GenerateUniverse().
SetEmpireHomeworld()
bool SetEmpireHomeworld (Empire * empire, int planet_id, std::string species_name)
Sets empire homeworld This includes setting ownership, capital, species, preferred environment (planet type) for the species.
References Empire::AddExploredSystem(), Species::AddHomeworld(), DebugLogger, Empire::EmpireID(), ErrorLogger, GetPlanet(), SpeciesManager::GetSpecies(), GetSpeciesManager(), GetSystem(), Meter::LARGE_VALUE, Species::PlanetEnvironments(), Empire::SetCapitalID(), parse::species(), SZ_ASTEROIDS, SZ_GASGIANT, and SZ_MEDIUM.
Referenced by anonymous_namespace{ServerWrapper.cpp}::EmpireSetHomeworld().
SetNativePopulationValues()
void SetNativePopulationValues (ObjectMap & object_map)
Set the population of unowned planets to a random fraction of their target values.
References ObjectMap::all(), Meter::Current(), METER_POPULATION, METER_TARGET_POPULATION, RandZeroToOne(), and Meter::SetCurrent().
Referenced by ServerApp::GenerateUniverse().