FreeOrion: UniverseGenerator.h File Reference
UniverseGenerator.h File Reference
#include <map>
#include <string>
Functions
void GenerateStarlanes (int max_jumps_between_systems, int max_starlane_length)
Creates starlanes and adds them systems already generated.
void InitEmpires (const std::map< int, PlayerSetupData > &player_setup_data)
Creates Empires objects for each entry in player_setup_data with empire ids equal to the corresponding map keys (so that the calling code can know which empire belongs to which player).
void SetActiveMetersToTargetMaxCurrentValues (ObjectMap &object_map)
Set active meter current values equal to target/max meter current values.
bool SetEmpireHomeworld (Empire *empire, int planet_id, std::string species_name)
Sets empire homeworld This includes setting ownership, capital, species, preferred environment (planet type) for the species.
void SetNativePopulationValues (ObjectMap &object_map)
Set the population of unowned planets to a random fraction of heir target values.
Function Documentation
GenerateStarlanes()
void GenerateStarlanes (int max_jumps_between_systems, int max_starlane_length)
Creates starlanes and adds them systems already generated.
References ObjectMap::all(), anonymous_namespace{UniverseGenerator.cpp}::ConnectedWithin(), anonymous_namespace{UniverseGenerator.cpp}::CullAngularlyTooCloseLanes(), anonymous_namespace{UniverseGenerator.cpp}::CullTooLongLanes(), DebugLogger, Delauney::DelauneyTriangulate(), ErrorLogger, GameRules::Get(), GetGameRules(), GetUniverse(), Universe::InitializeSystemGraph(), anonymous_namespace{UniverseGenerator.cpp}::IntSetMapSizeCount(), INVALID_OBJECT_ID, and Objects().
Referenced by FreeOrionPython::WrapServer().
InitEmpires()
void InitEmpires (const std::map< int, PlayerSetupData > & player_setup_data)
Creates Empires objects for each entry in player_setup_data with empire ids equal to the corresponding map keys (so that the calling code can know which empire belongs to which player).
References ALL_EMPIRES, EmpireManager::CreateEmpire(), DebugLogger, EmpireColors(), Empires(), ErrorLogger, RandZeroToOne(), EmpireManager::ResetDiplomacy(), EmpireManager::SetDiplomaticStatus(), to_string(), and UserString().
Referenced by ServerApp::GenerateUniverse().
SetActiveMetersToTargetMaxCurrentValues()
void SetActiveMetersToTargetMaxCurrentValues (ObjectMap & object_map)
Set active meter current values equal to target/max meter current values.
Useful when creating new object after applying effects.
References ObjectMap::all(), AssociatedMeterTypes(), and TraceLogger.
Referenced by ServerApp::GenerateUniverse().
SetEmpireHomeworld()
bool SetEmpireHomeworld (Empire * empire, int planet_id, std::string species_name)
Sets empire homeworld This includes setting ownership, capital, species, preferred environment (planet type) for the species.
References SpeciesManager::AddSpeciesHomeworld(), DebugLogger, ErrorLogger, ObjectMap::get(), GetSpecies(), GetSpeciesManager(), Meter::LARGE_VALUE, Objects(), parse::species(), SZ_ASTEROIDS, SZ_GASGIANT, and SZ_MEDIUM.
Referenced by anonymous_namespace{ServerWrapper.cpp}::EmpireSetHomeworld().
SetNativePopulationValues()
void SetNativePopulationValues (ObjectMap & object_map)
Set the population of unowned planets to a random fraction of heir target values.
References ObjectMap::all(), Meter::Current(), RandZeroToOne(), and Meter::SetCurrent().
Referenced by ServerApp::GenerateUniverse().