FreeOrion: Universe.cpp File Reference
Universe.cpp File Reference
#include "Universe.h"
#include "../util/OptionsDB.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/Random.h"
#include "../util/ScopedTimer.h"
#include "../util/CheckSums.h"
#include "../util/GameRules.h"
#include "../Empire/Empire.h"
#include "../Empire/EmpireManager.h"
#include "IDAllocator.h"
#include "Building.h"
#include "BuildingType.h"
#include "Effect.h"
#include "Fleet.h"
#include "FleetPlan.h"
#include "Planet.h"
#include "Ship.h"
#include "System.h"
#include "Field.h"
#include "FieldType.h"
#include "UniverseObject.h"
#include "UnlockableItem.h"
#include "Predicates.h"
#include "ShipPart.h"
#include "ShipHull.h"
#include "ShipDesign.h"
#include "Special.h"
#include "Species.h"
#include "Tech.h"
#include "Conditions.h"
#include "ValueRef.h"
#include "Enums.h"
#include "Pathfinder.h"
#include "Encyclopedia.h"
#include <boost/property_map/property_map.hpp>
#include <boost/algorithm/string.hpp>
Classes
struct anonymous_namespace{Universe.cpp}::constant_property< Key, Value >
struct boost::asio::thread_pool
struct boost::property_traits< constant_property< Key, Value > >
Namespaces
anonymous_namespace{Universe.cpp}
boost
In Boost 1.66, io_service was replaced with a typedef of io_context.
boost::asio
Functions
void anonymous_namespace{Universe.cpp}::AddOptions (OptionsDB &db)
void anonymous_namespace{Universe.cpp}::AddRules (GameRules &rules)
std::map< std::string, unsigned int > CheckSumContent ()
Compute a checksum for each of the universe's content managers.
anonymous_namespace{Universe.cpp}::DeclareThreadSafeLogger (effects)
anonymous_namespace{Universe.cpp}::DeclareThreadSafeLogger (conditions)
void anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations (EffectsCauseType effect_cause_type, const std::string &specific_cause_name, const Condition::ObjectSet &source_objects, const std::vector< std::shared_ptr< Effect::EffectsGroup >> &effects_groups, bool only_meter_effects, const ObjectMap &object_map, const Condition::ObjectSet &potential_targets, const std::unordered_set< int > &potential_target_ids, std::list< std::pair< Effect::SourcesEffectsTargetsAndCausesVec, Effect::SourcesEffectsTargetsAndCausesVec *>> &source_effects_targets_causes_reorder_buffer_out, boost::asio::thread_pool &thread_pool, int &n)
Collect info for scope condition evaluations and dispatch those evaluations to thread_pool.
void anonymous_namespace{Universe.cpp}::FilterObjectIDsByKnownDestruction (std::vector< int > &object_ids, int empire_id, const std::map< int, std::set< int >> &empire_known_destroyed_object_ids)
removes ids of objects that the indicated empire knows have been destroyed
std::vector< int > anonymous_namespace{Universe.cpp}::FilterObjectPositionsByDetectorPositionsAndRanges (const std::map< std::pair< double, double >, std::vector< int >> &object_positions, const std::map< std::pair< double, double >, float > &detector_position_ranges)
filters set of objects at locations by which of those locations are within range of a set of detectors and ranges
template<typename Key , typename Value >
const Value & boost::get (const constant_property< Key, Value > &pmap, const Key &)
std::map< int, float > anonymous_namespace{Universe.cpp}::GetEmpiresDetectionStrengths (int empire_id=ALL_EMPIRES)
std::map< int, std::map< std::pair< double, double >, float > > anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges ()
for each empire: for each position where the empire has detector objects, what is the empire's detection range at that location? (this is the largest of the detection ranges of objects the empire has at that spot)
std::map< int, std::map< std::pair< double, double >, std::vector< int > > > anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects (const ObjectMap &objects, int empire_id=ALL_EMPIRES)
for each empire: for each position, what objects have low enough stealth that the empire could detect them if an detector owned by the empire is in range?
void boost::asio::post (thread_pool, std::function< void()> func)
void anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void anonymous_namespace{Universe.cpp}::PropagateVisibilityToSystemsAlongStarlanes (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void anonymous_namespace{Universe.cpp}::SetAllObjectsVisibleToAllEmpires ()
sets all objects visible to all empires
void anonymous_namespace{Universe.cpp}::SetEmpireFieldVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> &empire_location_detection_ranges, const ObjectMap &objects)
sets visibility of field objects for empires based on input locations and stealth of fields in supplied ObjectMap and input empire detection ranges at locations.
void anonymous_namespace{Universe.cpp}::SetEmpireObjectVisibilitiesFromRanges (const std::map< int, std::map< std::pair< double, double >, float >> &empire_location_detection_ranges, const std::map< int, std::map< std::pair< double, double >, std::vector< int >>> &empire_location_potentially_detectable_objects)
sets visibility of objects for empires based on input locations of potentially detectable objects (if in range) and and input empire detection ranges at locations.
void anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities ()
sets visibility of objects that empires own for those objects
void anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities (ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility, Universe::EmpireObjectSpecialsMap &empire_object_visible_specials)
void anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible (const ObjectMap &objects)
sets planets in system where an empire owns an object to be basically visible, and those systems to be partially visible
void anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible (const ObjectMap &objects, Universe::EmpireObjectVisibilityMap &empire_object_visibility)
void anonymous_namespace{Universe.cpp}::ShareVisbilitiesBetweenAllies (Universe::EmpireObjectVisibilityMap &empire_object_visibility, Universe::EmpireObjectSpecialsMap &empire_object_visible_specials)
void anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroup (const ObjectMap &object_map, const Effect::EffectsGroup *effects_group, const Condition::ObjectSet &source_objects, EffectsCauseType effect_cause_type, const std::string &specific_cause_name, const std::unordered_set< int > &candidate_object_ids, Condition::ObjectSet &candidate_objects_in, Effect::SourcesEffectsTargetsAndCausesVec &source_effects_targets_causes_out, int n)
Evaluate activation, and scope conditions of effects_group for each of the objects in source_objects for the candidate target objects in candidate_objects_in (unless it is empty, in which case the default candidate objects for the scope condition is used.
Variables
FO_COMMON_API const int ALL_EMPIRES = -1
const bool anonymous_namespace{Universe.cpp}::ENABLE_VISIBILITY_EMPIRE_MEMORY = true
FO_COMMON_API const int INVALID_DESIGN_ID
bool anonymous_namespace{Universe.cpp}::temp_bool = RegisterOptions(&AddOptions)
bool anonymous_namespace{Universe.cpp}::temp_bool2 = RegisterGameRules(&AddRules)
Function Documentation
CheckSumContent()
std::map<std::string, unsigned int> CheckSumContent ()
Compute a checksum for each of the universe's content managers.
Each value will be of the form ("BuildingManager", <checksum>)
References GetBuildingTypeManager(), Encyclopedia::GetCheckSum(), FieldTypeManager::GetCheckSum(), BuildingTypeManager::GetCheckSum(), ShipPartManager::GetCheckSum(), TechManager::GetCheckSum(), PredefinedShipDesignManager::GetCheckSum(), ShipHullManager::GetCheckSum(), SpeciesManager::GetCheckSum(), GetEncyclopedia(), GetFieldTypeManager(), GetPredefinedShipDesignManager(), GetShipHullManager(), GetShipPartManager(), GetSpeciesManager(), and GetTechManager().
Referenced by ContentCheckSumMessage(), and ClientApp::VerifyCheckSum().
Variable Documentation
ALL_EMPIRES
FO_COMMON_API const int ALL_EMPIRES = -1
Referenced by boost::get(), and Universe::GetShipDesignsToSerialize().
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by boost::asio::post(), and Universe::ResetAllIDAllocation().