FreeOrion: Universe.h File Reference
Universe.h File Reference
#include "EnumsFwd.h"
#include "ObjectMap.h"
#include "UniverseObject.h"
#include "../util/Pending.h"
#include <boost/signals2/signal.hpp>
#include <boost/serialization/access.hpp>
#include <boost/thread/shared_mutex.hpp>
#include <boost/container/flat_map.hpp>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <string>
#include <vector>
#include <unordered_map>
#include "../util/Export.h"
Classes
class Universe
The Universe class contains the majority of FreeOrion gamestate: All the UniverseObjects in a game, and (of less importance) all ShipDesigns in a game.
struct ValueRef::ValueRef< T >
The base class for all ValueRef classes.
Namespaces
Condition
this namespace holds Condition and its subclasses; these classes represent predicates about UniverseObjects used by, for instance, the Effect system.
Effect
ValueRef
Functions
FO_COMMON_API std::map< std::string, unsigned int > CheckSumContent ()
Compute a checksum for each of the universe's content managers.
Function Documentation
CheckSumContent()
FO_COMMON_API std::map<std::string, unsigned int> CheckSumContent ()
Compute a checksum for each of the universe's content managers.
Each value will be of the form ("BuildingManager", <checksum>)
References GetBuildingTypeManager(), Encyclopedia::GetCheckSum(), FieldTypeManager::GetCheckSum(), HullTypeManager::GetCheckSum(), BuildingTypeManager::GetCheckSum(), ShipPartManager::GetCheckSum(), TechManager::GetCheckSum(), PredefinedShipDesignManager::GetCheckSum(), SpeciesManager::GetCheckSum(), GetEncyclopedia(), GetFieldTypeManager(), GetHullTypeManager(), GetPredefinedShipDesignManager(), GetShipPartManager(), GetSpeciesManager(), and GetTechManager().
Referenced by ContentCheckSumMessage(), and ClientApp::VerifyCheckSum().