FreeOrion: UniverseObject.h File Reference
UniverseObject.h File Reference
#include <set>
#include <string>
#include <vector>
#include <boost/container/flat_map.hpp>
#include <boost/python/detail/destroy.hpp>
#include <boost/signals2/optional_last_value.hpp>
#include <boost/signals2/signal.hpp>
#include "EnumsFwd.h"
#include "Meter.h"
#include "../util/blocking_combiner.h"
#include "../util/Enum.h"
#include "../util/Export.h"
Functions
std::string DumpIndent (unsigned short ntabs=1)
A function that returns the correct amount of spacing for an indentation of ntabs during a dump.
FO_ENUM ((UniverseObjectType),((INVALID_UNIVERSE_OBJECT_TYPE, -1))((OBJ_BUILDING))((OBJ_SHIP))((OBJ_FLEET))((OBJ_PLANET))((OBJ_POP_CENTER))((OBJ_PROD_CENTER))((OBJ_SYSTEM))((OBJ_FIELD))((OBJ_FIGHTER))((NUM_OBJ_TYPES))) FO_ENUM((Visibility)
The various major subclasses of UniverseObject.
VIS_NO_VISIBILITY ((VIS_BASIC_VISIBILITY))((VIS_PARTIAL_VISIBILITY))((VIS_FULL_VISIBILITY))((NUM_VISIBILITIES))) class FO_COMMON_API UniverseObject
The abstract base class for all objects in the universe The UniverseObject class itself has an ID number, a name, a position, an ID of the system in which it is, a list of zero or more owners, and other common object data.
Variables
FO_COMMON_API const int ALL_EMPIRES
FO_COMMON_API const int INVALID_GAME_TURN
FO_COMMON_API const int INVALID_OBJECT_ID
INVALID_VISIBILITY
constexpr int TEMPORARY_OBJECT_ID = -2
Function Documentation
DumpIndent()
std::string DumpIndent (unsigned short ntabs = 1) inline
A function that returns the correct amount of spacing for an indentation of ntabs during a dump.
Referenced by Condition::All::Dump(), Condition::Source::Dump(), Effect::NoOp::Dump(), Policy::Dump(), FieldType::Dump(), Special::Dump(), Effect::SetMeter::Dump(), Tech::Dump(), Condition::Number::Dump(), Effect::SetShipPartMeter::Dump(), Condition::Turn::Dump(), Species::Dump(), Effect::SetEmpireMeter::Dump(), Condition::SortedNumberOf::Dump(), Effect::SetEmpireStockpile::Dump(), ShipDesign::Dump(), Condition::None::Dump(), Effect::SetEmpireCapital::Dump(), Condition::NoOp::Dump(), Effect::SetPlanetType::Dump(), Condition::EmpireAffiliation::Dump(), Effect::SetPlanetSize::Dump(), Condition::RootCandidate::Dump(), Effect::SetSpecies::Dump(), Effect::SetOwner::Dump(), Condition::Target::Dump(), Effect::SetSpeciesEmpireOpinion::Dump(), Condition::Homeworld::Dump(), Effect::SetSpeciesSpeciesOpinion::Dump(), Condition::Capital::Dump(), Effect::CreatePlanet::Dump(), Condition::Monster::Dump(), Condition::Armed::Dump(), Effect::CreateBuilding::Dump(), Condition::Type::Dump(), Effect::CreateShip::Dump(), Condition::Building::Dump(), Effect::CreateField::Dump(), Condition::HasSpecial::Dump(), Condition::HasTag::Dump(), Effect::CreateSystem::Dump(), Condition::CreatedOnTurn::Dump(), Effect::Destroy::Dump(), Effect::AddSpecial::Dump(), Condition::Contains::Dump(), Effect::RemoveSpecial::Dump(), Condition::ContainedBy::Dump(), Effect::AddStarlanes::Dump(), Condition::InOrIsSystem::Dump(), Effect::RemoveStarlanes::Dump(), Effect::SetStarType::Dump(), Condition::OnPlanet::Dump(), Effect::MoveTo::Dump(), Condition::ObjectID::Dump(), Effect::MoveInOrbit::Dump(), Condition::PlanetType::Dump(), Effect::MoveTowards::Dump(), Condition::PlanetSize::Dump(), Effect::SetDestination::Dump(), Effect::SetAggression::Dump(), Condition::PlanetEnvironment::Dump(), Effect::Victory::Dump(), Condition::Species::Dump(), Effect::GiveEmpireTech::Dump(), Condition::Enqueued::Dump(), Condition::FocusType::Dump(), Effect::GenerateSitRepMessage::Dump(), Condition::StarType::Dump(), Condition::DesignHasHull::Dump(), Effect::SetOverlayTexture::Dump(), Effect::SetTexture::Dump(), Condition::DesignHasPart::Dump(), Effect::SetVisibility::Dump(), Condition::DesignHasPartClass::Dump(), Condition::PredefinedShipDesign::Dump(), Effect::Conditional::Dump(), Condition::NumberedShipDesign::Dump(), Condition::ProducedByEmpire::Dump(), Condition::Chance::Dump(), Condition::MeterValue::Dump(), Condition::ShipPartMeterValue::Dump(), Condition::EmpireMeterValue::Dump(), Condition::EmpireStockpileValue::Dump(), Condition::EmpireHasAdoptedPolicy::Dump(), Condition::OwnerHasTech::Dump(), Condition::OwnerHasBuildingTypeAvailable::Dump(), Condition::OwnerHasShipDesignAvailable::Dump(), Condition::OwnerHasShipPartAvailable::Dump(), Condition::VisibleToEmpire::Dump(), Condition::WithinDistance::Dump(), Condition::WithinStarlaneJumps::Dump(), Condition::CanAddStarlaneConnection::Dump(), Condition::ExploredByEmpire::Dump(), Condition::Stationary::Dump(), Condition::Aggressive::Dump(), Condition::FleetSupplyableByEmpire::Dump(), Condition::ResourceSupplyConnectedByEmpire::Dump(), Condition::CanColonize::Dump(), Condition::CanProduceShips::Dump(), Condition::OrderedBombarded::Dump(), Condition::ValueTest::Dump(), Condition::Location::Dump(), Condition::CombatTarget::Dump(), Condition::And::Dump(), Condition::Or::Dump(), Condition::Not::Dump(), Condition::OrderedAlternativesOf::Dump(), and anonymous_namespace{Effects.cpp}::GenerateSystemName().
FO_ENUM()
FO_ENUM ((UniverseObjectType) , ((INVALID_UNIVERSE_OBJECT_TYPE, -1))((OBJ_BUILDING))((OBJ_SHIP))((OBJ_FLEET))((OBJ_PLANET))((OBJ_POP_CENTER))((OBJ_PROD_CENTER))((OBJ_SYSTEM))((OBJ_FIELD))((OBJ_FIGHTER))((NUM_OBJ_TYPES)))
The various major subclasses of UniverseObject.
Degrees of visibility an Empire or UniverseObject can have for an UniverseObject. Determines how much information the empire gets about the (non)visible object.
VIS_NO_VISIBILITY()
VIS_NO_VISIBILITY ((VIS_BASIC_VISIBILITY))
The abstract base class for all objects in the universe The UniverseObject class itself has an ID number, a name, a position, an ID of the system in which it is, a list of zero or more owners, and other common object data.
Position in the Universe can range from 0 (left) to 1000 (right) in X, and 0 (top) to 1000 (bottom) in Y. This coordinate system was chosen to help with conversion to and from screen coordinates, which originate at the upper-left corner of the screen and increase down and to the right. Each UniverseObject-derived class inherits several pure virtual members that perform its actions during various game phases, such as the movement phase. These subclasses must define what actions to perform during those phases. UniverseObjects advertise changes to themselves via the StateChanged Signal. This means that all mutators on UniverseObject and its subclasses need to emit this signal. This is how the UI becomes aware that an object that is being displayed has changed.
< returns the ID number of this object. Each object in FreeOrion has a unique ID number.
< returns the name of this object; some valid objects will have no name
< the X-coordinate of this object
< the Y-coordinate of this object
< returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
< returns true iff there are no owners of this object
< returns true iff the empire with id empire owns this object; unowned objects always return false;
Object owner is at war with empire empire_id
< returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
< returns the Specials attached to this object
< returns true iff this object has a special with the indicated name
< returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
returns the capacity of the special with name name or 0 if that special is not present
Returns all tags this object has.
Returns true iff this object has the tag with the indicated name.
Return human readable string description of object offset ntabs from margin.
Returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other.
Returns ids of objects contained within this object.
Returns true if there is an object with id object_id is contained within this UniverseObject.
< returns the subset of contained object IDs that is visible to empire with id empire_id
< returns the requested Meter, or 0 if no such Meter of that type is found in this object
< returns the visibility status of this universe object relative to the input empire.
Returns the name of this objectas it appears to empire empire_id .
Accepts a visitor object
See also
UniverseObjectVisitor
< returns game turn on which object was created
< returns elapsed number of turns between turn object was created and current game turn
< emitted when the UniverseObject is altered in any way
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
< sets the ID number of the object to id
< renames this object to name // TODO: by-value + move instead of const reference
moves this object by relative displacements x and y.
calls MoveTo(std::shared_ptr<const UniverseObject>) with the object pointed to by object_id.
moves this object to exact map coordinates of specified object.
moves this object to map coordinates (x, y).
< returns the requested Meter, or 0 if no such Meter of that type is found in this object
Sets all this UniverseObject's meters' initial values equal to their current values.
Sets the empire that owns this object.
< assigns this object to a System. does not actually move object in universe
< adds the Special name to this object, if it is not already present
< removes the Special name from this object, if it is already present
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE. This should be done before any Effects that alter these meter(s) act on the object.
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
< the position in x and y at which default-constructed objects are placed
< the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
< the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system. Caller takes ownership of returned pointee.
< inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
< adds stealth meter
Used by public UniverseObject::Copy and derived classes' ::Copy methods.
< returns set of meters of this object that are censored based on the specified Visibility vis
References anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), ALL_EMPIRES, ObjectMap::Clone(), ObjectMap::Copy(), Effect::Dump(), INVALID_GAME_TURN, INVALID_OBJECT_ID, anonymous_namespace{XMLDoc.cpp}::Name, anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), and serialize().
Referenced by InitialStealthEvent::CombatLogDescription(), ObjectMap::CopyObject(), ValueRef::Constant< T >::Dump(), ValueRef::ComplexVariable< T >::Eval(), Universe::GetEmpireObjectVisibilityMap(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), Universe::GetObjectVisibilityByEmpire(), anonymous_namespace{CombatSystem.cpp}::GetObjectVisibilityByEmpire(), CombatInfo::InitializeObjectVisibility(), Condition::anonymous_namespace{Conditions.cpp}::VisibleToEmpireSimpleMatch::operator()(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects(), Ship::PublicName(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), Universe::SetEmpireObjectVisibility(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), anonymous_namespace{Fleet.cpp}::TruncateRouteToEndAtSystem(), Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns(), Universe::UpdateEmpireStaleObjectKnowledge(), parse::detail::visibility_parser_rules::visibility_parser_rules(), and FreeOrionPython::WrapGameStateEnums().
Variable Documentation
ALL_EMPIRES
FO_COMMON_API const int ALL_EMPIRES
Referenced by VIS_NO_VISIBILITY().
INVALID_GAME_TURN
FO_COMMON_API const int INVALID_GAME_TURN
Referenced by VIS_NO_VISIBILITY().
INVALID_OBJECT_ID
FO_COMMON_API const int INVALID_OBJECT_ID
Referenced by VIS_NO_VISIBILITY().
INVALID_VISIBILITY
INVALID_VISIBILITY
Referenced by ValueRef::Variable< ToType >::Eval(), ValueRef::ComplexVariable< T >::Eval(), and FreeOrionPython::WrapGameStateEnums().
TEMPORARY_OBJECT_ID
constexpr int TEMPORARY_OBJECT_ID = -2
Referenced by anonymous_namespace{Pathfinder.cpp}::GeneralizedLocation(), Universe::InsertTemp(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelIncomplDesignTag(), and Universe::ResetAllIDAllocation().