FreeOrion: UnlockableItem.h File Reference
UnlockableItem.h File Reference
#include <GG/Enum.h>
#include "../util/Export.h"
Namespaces
CheckSums
Functions
void CheckSums::CheckSumCombine (unsigned int &sum, const UnlockableItem &item)
GG_ENUM (UnlockableItemType, INVALID_UNLOCKABLE_ITEM_TYPE=-1, UIT_BUILDING, UIT_SHIP_PART, UIT_SHIP_HULL, UIT_SHIP_DESIGN, UIT_TECH, NUM_UNLOCKABLE_ITEM_TYPES) struct FO_COMMON_API UnlockableItem
types of items that can be unlocked for empires
bool operator!= (const UnlockableItem &lhs, const UnlockableItem &rhs)
FO_COMMON_API bool operator== (const UnlockableItem &lhs, const UnlockableItem &rhs)
Function Documentation
GG_ENUM()
GG_ENUM (UnlockableItemType , INVALID_UNLOCKABLE_ITEM_TYPE = -1, UIT_BUILDING , UIT_SHIP_PART , UIT_SHIP_HULL , UIT_SHIP_DESIGN , UIT_TECH , NUM_UNLOCKABLE_ITEM_TYPES)
types of items that can be unlocked for empires
Specifies single item of game content that may be unlocked for an empire. The type field stores the type of item that is being unlocked, such as building or ship component, and the name field contains the name of the actual item (e.g. (UIT_BUILDING, "Superfarm") or (UIT_SHIP_PART, "Death Ray")).
Returns a data file format representation of this object
Returns a number, calculated from the contained data, which should be different for different contained data, and must be the same for the same contained data, and must be the same on different platforms and executions of the program and the function. Useful to verify that the parsed content is consistent without sending it all between clients and server.
The kind of item this is
the exact item this is
References CheckSums::CheckSumCombine(), Effect::Dump(), FO_COMMON_API, operator!=(), and operator==().
operator!=()
bool operator!= (const UnlockableItem & lhs, const UnlockableItem & rhs)
Referenced by GG_ENUM().
operator==()
FO_COMMON_API bool operator== (const UnlockableItem & lhs, const UnlockableItem & rhs)
Referenced by GG_ENUM().