FreeOrion: ValueRefPythonParser.h File Reference
ValueRefPythonParser.h File Reference
#include <memory>
#include "../universe/ValueRefs.h"
#include "ConditionPythonParser.h"
Classes
struct value_ref_wrapper< T >
Functions
value_ref_wrapper< double > operator* (int, const value_ref_wrapper< double > &)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &, int)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &, double)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &, const value_ref_wrapper< double > &)
value_ref_wrapper< double > operator- (const value_ref_wrapper< double > &, const value_ref_wrapper< double > &)
condition_wrapper operator< (const value_ref_wrapper< int > &, const value_ref_wrapper< int > &)
condition_wrapper operator== (const value_ref_wrapper< int > &, const value_ref_wrapper< int > &)
Function Documentation
operator*()
value_ref_wrapper<double> operator* (int , const value_ref_wrapper< double > &)
References ValueRef::CloneUnique(), ValueRef::TIMES, and value_ref_wrapper< T >::value_ref.
operator+() [1/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & , int)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator+() [2/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & , double)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator+() [3/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & , const value_ref_wrapper< double > &)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator-()
value_ref_wrapper<double> operator- (const value_ref_wrapper< double > & , const value_ref_wrapper< double > &)
References ValueRef::CloneUnique(), ValueRef::MINUS, and value_ref_wrapper< T >::value_ref.
operator<()
condition_wrapper operator< (const value_ref_wrapper< int > & , const value_ref_wrapper< int > &)
References ValueRef::CloneUnique(), and Condition::LESS_THAN.
Referenced by FO_ENUM(), and anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending().
operator==()
condition_wrapper operator== (const value_ref_wrapper< int > & , const value_ref_wrapper< int > &)
References ValueRef::CloneUnique(), Condition::EQUAL, and value_ref_wrapper< T >::value_ref.