FreeOrion: ValueRefs.cpp File Reference
ValueRefs.cpp File Reference
#include "ValueRefs.h"
#include <algorithm>
#include <functional>
#include <iomanip>
#include <iterator>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/range/adaptors.hpp>
#include <boost/range/numeric.hpp>
#include "Building.h"
#include "Enums.h"
#include "Field.h"
#include "Fighter.h"
#include "Fleet.h"
#include "Pathfinder.h"
#include "Planet.h"
#include "ShipDesign.h"
#include "ShipHull.h"
#include "ShipPart.h"
#include "Ship.h"
#include "Species.h"
#include "System.h"
#include "Tech.h"
#include "UniverseObjectVisitors.h"
#include "UniverseObject.h"
#include "Universe.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../Empire/Supply.h"
#include "../util/GameRules.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/Random.h"
Classes
struct anonymous_namespace{ValueRefs.cpp}::ObjectTypeVisitor
Namespaces
anonymous_namespace{ValueRefs.cpp}
ValueRef
ValueRef::anonymous_namespace{ValueRefs.cpp}
Macros
#define IF_CURRENT_VALUE(T)
#define LOG_UNKNOWN_VARIABLE_PROPERTY_TRACE(T)
Functions
std::string ValueRef::ComplexVariableDescription (const std::vector< std::string > &property_names, const ValueRef< int > *int_ref1, const ValueRef< int > *int_ref2, const ValueRef< int > *int_ref3, const ValueRef< std::string > *string_ref1, const ValueRef< std::string > *string_ref2)
std::string ValueRef::ComplexVariableDump (const std::vector< std::string > &property_names, const ValueRef< int > *int_ref1, const ValueRef< int > *int_ref2, const ValueRef< int > *int_ref3, const ValueRef< std::string > *string_ref1, const ValueRef< std::string > *string_ref2)
std::string DoubleToString (double val, int digits, bool always_show_sign)
std::shared_ptr< const UniverseObject > anonymous_namespace{ValueRefs.cpp}::FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
std::string ValueRef::FormatedDescriptionPropertyNames (ReferenceType ref_type, const std::vector< std::string > &property_names, bool return_immediate_value)
const std::map< std::string, MeterType > & anonymous_namespace{ValueRefs.cpp}::GetMeterNameMap ()
const std::string & ValueRef::MeterToName (MeterType meter)
MeterType ValueRef::NameToMeter (const std::string &name)
std::string ValueRef::ReconstructName (const std::vector< std::string > &property_name, ReferenceType ref_type, bool return_immediate_value)
std::string ValueRef::StatisticDescription (StatisticType stat_type, const std::string &value_desc, const std::string &condition_desc)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchableByEmpire (int empire_id)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRefs.cpp}::TechsResearchedByEmpire (int empire_id)
template<typename T >
std::enable_if< std::is_enum< T >::value, std::string >::type to_string (T val)
std::string anonymous_namespace{ValueRefs.cpp}::TraceReference (const std::vector< std::string > &property_name, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRefs.cpp}::TransferrableTechs (int sender_empire_id, int receipient_empire_id)
bool UserStringExists (const std::string &str)
Variables
std::map< std::string, MeterType > anonymous_namespace{ValueRefs.cpp}::dummy = GetMeterNameMap()
const std::string anonymous_namespace{ValueRefs.cpp}::EMPTY_STRING
FO_COMMON_API const int INVALID_DESIGN_ID
Macro Definition Documentation
IF_CURRENT_VALUE
#define IF_CURRENT_VALUE (T)
Value:
if (m_ref_type == ReferenceType::EFFECT_TARGET_VALUE_REFERENCE) {      \
    if (context.current_value.empty())                                 \
        throw std::runtime_error(                                      \
            "Variable<" #T ">::Eval(): Value could not be evaluated, " \
            "because no current value was provided.");                 \
    try {                                                              \
        return boost::any_cast<T>(context.current_value);              \
    } catch (const boost::bad_any_cast&) {                             \
        throw std::runtime_error(                                      \
            "Variable<" #T ">::Eval(): Value could not be evaluated, " \
            "because the provided current value is not an " #T ".");   \
    }                                                                  \
}
Referenced by ValueRef::Variable< ToType >::Eval().
LOG_UNKNOWN_VARIABLE_PROPERTY_TRACE
#define LOG_UNKNOWN_VARIABLE_PROPERTY_TRACE (T)
Value:
ErrorLogger() << "Variable<" #T ">::Eval unrecognized object "         \
                 "property: "                                          \
              << TraceReference(m_property_name, m_ref_type, context); \
if (context.source)                                                    \
    ErrorLogger() << "source: " << context.source->ObjectType() << " " \
                  << context.source->ID() << " ( "                     \
                  << context.source->Name() << " ) ";                  \
else                                                                   \
    ErrorLogger() << "source (none)";
Referenced by ValueRef::Variable< ToType >::Eval().
Function Documentation
DoubleToString()
std::string DoubleToString (double val, int digits, bool always_show_sign)
Referenced by CensusRowPanel::CensusRowPanel(), anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ValueRef::Constant< T >::Description(), ValueRef::ComplexVariable< T >::Eval(), ValueRef::StringCast< FromType >::Eval(), ParticipantBar::ParticipantBar(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), EncyclopediaDetailPanel::RefreshImpl(), ResourceBrowseWnd::ResourceBrowseWnd(), anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), StatisticIcon::SetValue(), TechRowBrowseWnd(), SpecialsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
to_string()
template<typename T > std::enable_if<std::is_enum<T>::value, std::string>::type to_string (T val)
Referenced by FleetDataPanel::AcceptDrops(), anonymous_namespace{LoggerWithOptionsDB.cpp}::AddLoggerToOptionsDB(), anonymous_namespace{ObjectListWnd.cpp}::AddOptions(), anonymous_namespace{AIClientApp.cpp}::AddTraitBypassOption(), Universe::ApplyAppearanceEffects(), Universe::ApplyMeterEffectsAndUpdateMeters(), anonymous_namespace{MapWnd.cpp}::CanResupplyAfterDestination(), MultiPlayerLobbyWnd::ChatMessage(), anonymous_namespace{HumanClientApp.cpp}::ClearPreviousPendingSaves(), ColumnInPreview(), FightersAttackFightersEvent::CombatLogDescription(), FightersDestroyedEvent::CombatLogDescription(), OptionsWnd::CompleteConstruction(), TechTreeWnd::TechListBox::TechRow::CompleteConstruction(), ClientNetworking::Impl::ConnectToServer(), CreateBuildingBuiltSitRep(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateCombatSitRep(), CreateEmpireEliminatedSitRep(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), CreateFleetArrivedAtDestinationSitRep(), CreateFleetGiftedSitRep(), CreateGroundCombatSitRep(), CreatePlanetCapturedSitRep(), CreatePlanetColonizedSitRep(), CreatePlanetDepopulatedSitRep(), CreatePlanetGiftedSitRep(), CreatePlanetOutpostedSitRep(), anonymous_namespace{DesignWnd.cpp}::CreateSavePathForDesign(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), CreateShipBlockBuiltSitRep(), CreateShipBuiltSitRep(), CreateVictorySitRep(), Condition::Number::Description(), Condition::Turn::Description(), Condition::HasSpecial::Description(), Condition::CreatedOnTurn::Description(), ValueRef::Constant< T >::Description(), Condition::Enqueued::Description(), Condition::DesignHasPart::Description(), Condition::DesignHasPartClass::Description(), Condition::NumberedShipDesign::Description(), Condition::Chance::Description(), Condition::MeterValue::Description(), Condition::ShipPartMeterValue::Description(), Condition::EmpireMeterValue::Description(), Condition::EmpireStockpileValue::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), anonymous_namespace{ClientNetworking.cpp}::ServerDiscoverer::DiscoverServers(), anonymous_namespace{Universe.cpp}::DispatchEffectsGroupScopeEvaluations(), MapWnd::DispatchFleetsExploring(), DoubleToString(), SitRepEntry::Dump(), Special::Dump(), Moderator::DestroyUniverseObject::Dump(), ResourcePool::Dump(), OrderSet::Dump(), SupplyManager::Dump(), Moderator::SetOwner::Dump(), Moderator::AddStarlane::Dump(), Moderator::RemoveStarlane::Dump(), Moderator::CreateSystem::Dump(), Moderator::CreatePlanet::Dump(), NewFleetOrder::Dump(), ShipDesign::Dump(), Condition::HasSpecial::Dump(), ValueRef::Constant< T >::Dump(), EmpireManager::DumpDiplomacy(), anonymous_namespace{CombatLogWnd.cpp}::EmpireIdToText(), MapWnd::EnableOrderIssuing(), Condition::And::Eval(), ValueRef::ComplexVariable< T >::Eval(), ValueRef::StringCast< FromType >::Eval(), ValueRef::ValueRef< ToType >::EvalAsString(), FleetMoveOrder::ExecuteImpl(), ProductionQueueOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{Effects.cpp}::GenerateSystemName(), ServerApp::GenerateUniverse(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDamagedObjectSitrep(), anonymous_namespace{SitRepEntry.cpp}::GenericCombatDestroyedObjectSitrep(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnName(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionBase(), anonymous_namespace{MapWnd.cpp}::GetNearestSupplyRoute(), anonymous_namespace{MapWnd.cpp}::GetOrderedFleetRoute(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSubDirs(), DiscoveryServer::HandleReceive(), HostIDMessage(), HostMPAckMessage(), HostSPAckMessage(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Init(), InitEmpires(), anonymous_namespace{MeterBrowseWnd.cpp}::IntToString(), anonymous_namespace{ServerFSM.cpp}::IsPlayerChanged(), anonymous_namespace{MapWnd.cpp}::IssueExploringFleetOrders(), anonymous_namespace{MapWnd.cpp}::IssueFleetExploreOrder(), anonymous_namespace{MapWnd.cpp}::IssueFleetResupplyOrder(), LinkTaggedIDText(), anonymous_namespace{OptionsWnd.cpp}::LoggerLevelOption(), anonymous_namespace{ServerFSM.cpp}::LogPlayerSetupData(), anonymous_namespace{MultiplayerLobbyWnd.cpp}::LogPlayerSetupData(), anonymous_namespace{ServerNetworking.cpp}::MessageTypeName(), HumanClientApp::MultiPlayerGame(), HumanClientApp::NewSinglePlayerGame(), operator!=(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{AIWrapper.cpp}::PlayerNameByID(), anonymous_namespace{Empire.cpp}::PolicyCategoriesSlotsMeters(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackers(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRow::ProductionItemRow(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), Idle::react(), MPLobby::react(), WaitingForMPJoinAck::react(), WaitingForMPGameJoiners::react(), PlayingGame::react(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{FleetWnd.cpp}::ShipDataPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelPediaTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), RegisterLoggerWithOptionsDB(), FPSIndicator::Render(), MapWnd::RenderMovementLineETAIndicators(), parse::replace_macro_references(), anonymous_namespace{ClientUI.cpp}::RequiredCharsets(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::ResetShipDesignLabels(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), serialize(), ResearchQueue::serialize(), ProductionQueueOrder::serialize(), ShipDesignOrder::serialize(), anonymous_namespace{ObjectListWnd.cpp}::SetColumnName(), EncyclopediaDetailPanel::SetDesign(), EncyclopediaDetailPanel::SetEmpire(), SetLoggerThresholds(), EncyclopediaDetailPanel::SetObject(), EncyclopediaDetailPanel::SetPlanet(), anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending(), MapWnd::SetZoom(), anonymous_namespace{SidePanel.cpp}::SystemRow::SortKey(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::SpeciesSuitabilityColumn1(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroup(), anonymous_namespace{ValueRefs.cpp}::TraceReference(), TurnTimeoutMessage(), TechTreeWnd::LayoutPanel::TechPanel::Update(), MapWnd::MapScaleLine::Update(), TechTreeWnd::TechListBox::TechRow::Update(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), anonymous_namespace{MapWnd.cpp}::FleetDetailBrowseWnd::UpdateLabels(), Universe::UpdateMeterEstimatesImpl(), WaitingForSPGameJoiners::WaitingForSPGameJoiners(), and anonymous_namespace{CombatEvents.cpp}::WrapWithTagAndId().
UserStringExists()
bool UserStringExists (const std::string & str)
Referenced by ValueRef::ComplexVariableDescription(), ValueRef::UserStringLookup< FromType >::Eval(), and ValueRef::StatisticDescription().
Variable Documentation
INVALID_DESIGN_ID
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by ValueRef::Variable< ToType >::Eval(), and ValueRef::ComplexVariable< T >::Eval().