FreeOrion: ValueRef.cpp File Reference
ValueRef.cpp File Reference
#include "ValueRef.h"
#include "Building.h"
#include "Fleet.h"
#include "Ship.h"
#include "Planet.h"
#include "Predicates.h"
#include "Species.h"
#include "System.h"
#include "Field.h"
#include "Pathfinder.h"
#include "Universe.h"
#include "UniverseObject.h"
#include "Condition.h"
#include "Enums.h"
#include "Tech.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "../Empire/Supply.h"
#include "../util/Random.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/GameRules.h"
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
#include <iomanip>
#include <iterator>
Classes
struct anonymous_namespace{ValueRef.cpp}::ObjectTypeVisitor
Namespaces
anonymous_namespace{ValueRef.cpp}
ValueRef
ValueRef::anonymous_namespace{ValueRef.cpp}
Macros
#define IF_CURRENT_VALUE(T)
Functions
std::string DoubleToString (double val, int digits, bool always_show_sign)
std::shared_ptr< const UniverseObject > anonymous_namespace{ValueRef.cpp}::FollowReference (std::vector< std::string >::const_iterator first, std::vector< std::string >::const_iterator last, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
std::string ValueRef::FormatedDescriptionPropertyNames (ReferenceType ref_type, const std::vector< std::string > &property_names, bool return_immediate_value)
const std::map< int, float > & ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireIntFloatMap (int empire_id, const std::string &parsed_map_name)
const std::map< int, int > & ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireIntIntMap (int empire_id, const std::string &parsed_map_name)
const std::map< std::string, int > & ValueRef::anonymous_namespace{ValueRef.cpp}::GetEmpireStringIntMap (int empire_id, const std::string &parsed_map_name)
float ValueRef::anonymous_namespace{ValueRef.cpp}::GetFloatEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, int map_key)
float ValueRef::anonymous_namespace{ValueRef.cpp}::GetFloatEmpirePropertySumAllIntKeys (int empire_id, const std::string &parsed_property_name)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertyNoKey (int empire_id, const std::string &parsed_property_name)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertyNoKeyImpl (int empire_id, const std::string &parsed_property_name)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, const std::string &map_key)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySingleKey (int empire_id, const std::string &parsed_property_name, int map_key)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySumAllIntKeys (int empire_id, const std::string &parsed_property_name)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntEmpirePropertySumAllStringKeys (int empire_id, const std::string &parsed_property_name)
int ValueRef::anonymous_namespace{ValueRef.cpp}::GetIntKeyFromContentStringKey (const std::string &parsed_property_name, const std::string &key_string)
const std::map< std::string, MeterType > & anonymous_namespace{ValueRef.cpp}::GetMeterNameMap ()
std::string ValueRef::MeterToName (MeterType meter)
MeterType ValueRef::NameToMeter (const std::string &name)
std::string ValueRef::ReconstructName (const std::vector< std::string > &property_name, ReferenceType ref_type, bool return_immediate_value)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchableByEmpire (int empire_id)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRef.cpp}::TechsResearchedByEmpire (int empire_id)
std::string anonymous_namespace{ValueRef.cpp}::TraceReference (const std::vector< std::string > &property_name, ValueRef::ReferenceType ref_type, const ScriptingContext &context)
std::vector< std::string > ValueRef::anonymous_namespace{ValueRef.cpp}::TransferrableTechs (int sender_empire_id, int receipient_empire_id)
bool UserStringExists (const std::string &str)
Variables
std::map< std::string, MeterType > anonymous_namespace{ValueRef.cpp}::dummy = GetMeterNameMap()
static std::map< int, float > ValueRef::anonymous_namespace{ValueRef.cpp}::EMPTY_INT_FLOAT_MAP
static std::map< int, int > ValueRef::anonymous_namespace{ValueRef.cpp}::EMPTY_INT_INT_MAP
static std::map< std::string, int > ValueRef::anonymous_namespace{ValueRef.cpp}::EMPTY_STRING_INT_MAP
FO_COMMON_API const int INVALID_DESIGN_ID
Macro Definition Documentation
#define IF_CURRENT_VALUE (T)
Value:
if (m_ref_type == EFFECT_TARGET_VALUE_REFERENCE) {                     \
    if (context.current_value.empty())                                 \
        throw std::runtime_error(                                      \
            "Variable<" #T ">::Eval(): Value could not be evaluated, " \
            "because no current value was provided.");                 \
    try {                                                              \
        return boost::any_cast<T>(context.current_value);              \
    } catch (const boost::bad_any_cast&) {                             \
        throw std::runtime_error(                                      \
            "Variable<" #T ">::Eval(): Value could not be evaluated, " \
            "because the provided current value is not an " #T ".");   \
    }                                                                  \
}
Referenced by ValueRef::Variable< T >::Eval().
Function Documentation
std::string DoubleToString (double val, int digits, bool always_show_sign)
Referenced by CensusRowPanel::CensusRowPanel(), anonymous_namespace{MeterBrowseWnd.cpp}::ColouredNumber(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::CompleteConstruction(), ValueRef::Constant< T >::Description(), StatisticIcon::DoLayout(), ValueRef::StringCast< FromType >::Eval(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemPanel::Init(), ParticipantBar::ParticipantBar(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), EncyclopediaDetailPanel::RefreshImpl(), anonymous_namespace{HumanClientApp.cpp}::SetGLVersionDependentOptionDefaults(), ResourceInfoPanel::SetLocalPointsCost(), ResourceInfoPanel::SetStockpileCost(), ResourceInfoPanel::SetTotalPointsCost(), TechRowBrowseWnd(), SpecialsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{SidePanel.cpp}::SystemMeterBrowseWnd::UpdateImpl(), SystemResourceSummaryBrowseWnd::UpdateImportExport(), SystemResourceSummaryBrowseWnd::UpdateProduction(), MeterBrowseWnd::UpdateSummary(), ShipDamageBrowseWnd::UpdateSummary(), and ShipFightersBrowseWnd::UpdateSummary().
bool UserStringExists (const std::string & str)
Referenced by ValueRef::UserStringLookup< FromType >::Eval().
Variable Documentation
FO_COMMON_API const int INVALID_DESIGN_ID
Referenced by ValueRef::Variable< T >::Eval(), and ValueRef::ComplexVariable< T >::Eval().