FreeOrion: ValueRefPythonParser.cpp File Reference
ValueRefPythonParser.cpp File Reference
#include "ValueRefPythonParser.h"
#include <stdexcept>
#include "../universe/ValueRefs.h"
#include "../universe/Conditions.h"
Functions
value_ref_wrapper< double > operator* (int lhs, const value_ref_wrapper< double > &rhs)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &lhs, int rhs)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &lhs, double rhs)
value_ref_wrapper< double > operator+ (const value_ref_wrapper< double > &lhs, const value_ref_wrapper< double > &rhs)
value_ref_wrapper< double > operator- (const value_ref_wrapper< double > &lhs, const value_ref_wrapper< double > &rhs)
condition_wrapper operator< (const value_ref_wrapper< int > &lhs, const value_ref_wrapper< int > &rhs)
condition_wrapper operator== (const value_ref_wrapper< int > &lhs, const value_ref_wrapper< int > &rhs)
Function Documentation
operator*()
value_ref_wrapper<double> operator* (int lhs, const value_ref_wrapper< double > & rhs)
References ValueRef::CloneUnique(), ValueRef::TIMES, and value_ref_wrapper< T >::value_ref.
operator+() [1/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & lhs, int rhs)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator+() [2/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & lhs, double rhs)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator+() [3/3]
value_ref_wrapper<double> operator+ (const value_ref_wrapper< double > & lhs, const value_ref_wrapper< double > & rhs)
References ValueRef::CloneUnique(), ValueRef::PLUS, and value_ref_wrapper< T >::value_ref.
operator-()
value_ref_wrapper<double> operator- (const value_ref_wrapper< double > & lhs, const value_ref_wrapper< double > & rhs)
References ValueRef::CloneUnique(), ValueRef::MINUS, and value_ref_wrapper< T >::value_ref.
operator<()
condition_wrapper operator< (const value_ref_wrapper< int > & lhs, const value_ref_wrapper< int > & rhs)
References ValueRef::CloneUnique(), and Condition::LESS_THAN.
Referenced by FO_ENUM(), and anonymous_namespace{ProductionQueue.cpp}::SetProdQueueElementSpending().
operator==()
condition_wrapper operator== (const value_ref_wrapper< int > & lhs, const value_ref_wrapper< int > & rhs)
References ValueRef::CloneUnique(), Condition::EQUAL, and value_ref_wrapper< T >::value_ref.