FreeOrion: VarText.cpp File Reference
VarText.cpp File Reference
#include "VarText.h"
#include "../universe/Universe.h"
#include "../universe/ShipDesign.h"
#include "../universe/System.h"
#include "../universe/Enums.h"
#include "../Empire/EmpireManager.h"
#include "../Empire/Empire.h"
#include "i18n.h"
#include "Logger.h"
#include <boost/algorithm/string/split.hpp>
#include <boost/static_assert.hpp>
#include <boost/spirit/include/classic.hpp>
#include <map>
Classes
struct anonymous_namespace{VarText.cpp}::StringAppend
struct anonymous_namespace{VarText.cpp}::SubstituteAndAppend
Namespaces
anonymous_namespace{VarText.cpp}
Typedefs
typedef std::string(* anonymous_namespace{VarText.cpp}::TagString) (const std::string &data, const std::string &tag, bool &valid)
Functions
std::string anonymous_namespace{VarText.cpp}::CombatLogString (const std::string &data, const std::string &tag, bool &valid)
combat links always just labelled "Combat"; don't need to look up details
std::map< std::string, TagString > anonymous_namespace{VarText.cpp}::CreateSubstituterMap ()
std::string anonymous_namespace{VarText.cpp}::EmpireString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for an empire tag.
const std::string anonymous_namespace{VarText.cpp}::END_VAR ("%")
const BuildingType * GetBuildingType (const std::string &name)
const FieldType * GetFieldType (const std::string &name)
const Special * GetSpecial (const std::string &name)
const Species * GetSpecies (const std::string &name)
const Tech * GetTech (const std::string &name)
Return the Tech identified by name.
const std::string anonymous_namespace{VarText.cpp}::LABEL_SEPARATOR (":")
std::string anonymous_namespace{VarText.cpp}::MeterTypeString (const std::string &data, const std::string &tag, bool &valid)
template<typename T , const T *(*)(const std::string &) GetByName>
std::string anonymous_namespace{VarText.cpp}::NameString (const std::string &data, const std::string &tag, bool &valid)
std::string anonymous_namespace{VarText.cpp}::PredefinedShipDesignString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for a predefined ship design tag.
std::string anonymous_namespace{VarText.cpp}::RawTextString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a raw text tag.
std::string anonymous_namespace{VarText.cpp}::ShipDesignString (const std::string &data, const std::string &tag, bool &valid)
Returns substitution string for a ship design tag.
const std::string anonymous_namespace{VarText.cpp}::START_VAR ("%")
const std::map< std::string, TagString > & anonymous_namespace{VarText.cpp}::SubstitutionMap ()
Global substitution map, wrapped in a function to avoid initialization order issues.
std::string anonymous_namespace{VarText.cpp}::TextString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a translated text tag.
std::string anonymous_namespace{VarText.cpp}::UniverseObjectString (const std::string &data, const std::string &tag, bool &valid)
Get string substitute for a tag that is a universe object.
std::string anonymous_namespace{VarText.cpp}::WithTags (const std::string &content, const std::string &tag, const std::string &data)
Surround content with approprite tags based on tag_of.
Function Documentation
const BuildingType* GetBuildingType (const std::string & name)
Returns the BuildingType specification object for a building of type name. If no such BuildingType exists, 0 is returned instead.
References BuildingTypeManager::GetBuildingType(), and GetBuildingTypeManager().
Referenced by Empire::AddBuildingType(), BuildDesignatorWnd::BuildSelector::BuildableItemVisible(), Building::Building(), ClientUI::BuildingIcon(), BuildingIndicator::BuildingIndicator(), BuildDesignatorWnd::BuildSelector::BuildItemLeftClicked(), ProductionQueue::ProductionItem::CompletionMeterConsumption(), ProductionQueue::ProductionItem::CompletionSpecialConsumption(), Planet::Conquer(), Empire::ConquerProductionQueueItemsAtLocation(), ProductionQueue::ProductionItem::CostIsProductionLocationInvariant(), Building::Dump(), Empire::EnqueuableItem(), anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), Effect::CreateBuilding::Execute(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), Building::HasTag(), anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings(), Empire::ProducibleItem(), Empire::ProductionCostAndTime(), anonymous_namespace{ProductionWnd.cpp}::ProductionItemBrowseWnd(), anonymous_namespace{BuildDesignatorWnd.cpp}::ProductionItemRowBrowseWnd(), BuildingIndicator::RClick(), BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), BuildDesignatorWnd::SetBuild(), Building::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToBuildingType().
const FieldType* GetFieldType (const std::string & name)
Returns the BuildingType specification object for a field of type name. If no such FieldType exists, 0 is returned instead.
References FieldTypeManager::GetFieldType(), and FieldTypeManager::GetFieldTypeManager().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), Effect::CreateField::Execute(), Field::Field(), ClientUI::FieldTexture(), Universe::GetEffectsAndTargets(), Field::HasTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), Field::Tags(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToFieldType().
const Special* GetSpecial (const std::string & name)
Returns the Special object used to represent specials of type name. If no such Special exists, 0 is returned instead.
References anonymous_namespace{Special.cpp}::SpecialManager::GetSpecial(), and anonymous_namespace{Special.cpp}::GetSpecialManager().
Referenced by anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), Universe::GetEffectsAndTargets(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), anonymous_namespace{ServerWrapper.cpp}::SpecialHasLocation(), ClientUI::SpecialIcon(), anonymous_namespace{ServerWrapper.cpp}::SpecialLocations(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnLimit(), anonymous_namespace{ServerWrapper.cpp}::SpecialSpawnRate(), SpecialsPanel::Update(), FreeOrionPython::WrapUniverseClasses(), and ClientUI::ZoomToSpecial().
const Species* GetSpecies (const std::string & name)
Returns the Species object used to represent species of type name. If no such Species exists, 0 is returned instead.
References SpeciesManager::GetSpecies(), and SpeciesManager::GetSpeciesManager().
const Tech* GetTech (const std::string & name)
Return the Tech identified by name.
Parameters
name The identifying name of the requested Tech.
Returns
A pointer to the Tech matching name or nullptr if no Tech with that name was found.
References TechManager::GetTech(), TechManager::GetTechManager(), and GetTechManager().
Referenced by TechTreeLayout::AddNode(), Empire::AddTech(), TechManager::AllChildren(), TechTreeWnd::CenterOnTech(), Empire::CheckResearchProgress(), TechTreeLayout::DoLayout(), TechTreeLayout::Edge::Edge(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetEmpireTechProgress::Execute(), Effect::GiveEmpireTech::Execute(), TechTreeArcs::Impl::FillArcBuffer(), TechManager::FindFirstDependencyCycle(), TechManager::FindIllegalDependencies(), TechManager::FindRedundantDependency(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), Empire::HasResearchedPrereqAndUnresearchedPrereq(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), AIInterface::IssueDequeueTechOrder(), AIInterface::IssueEnqueueTechOrder(), Empire::LeastExpensiveEnqueuedTech(), Empire::MostExpensiveEnqueuedTech(), Empire::MostRPCostLeftEnqueuedTech(), anonymous_namespace{Tech.cpp}::NextTechs(), Empire::PlaceTechInQueue(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), TechManager::RecursivePrereqs(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), Empire::ResearchableTech(), Empire::ResearchProgress(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), anonymous_namespace{Empire.cpp}::SetTechQueueElementSpending(), Empire::SetTechResearchProgress(), TechTreeWnd::TechDoubleClickedSlot(), TechManager::TechManager(), TechPanelRowBrowseWnd(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), ResearchQueue::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and FreeOrionPython::WrapEmpire().