FreeOrion: Version.h File Reference
Version.h File Reference
Declares free functions to access the application and dependency versions.
#include <string>
#include <map>
#include "Export.h"
Functions
FO_COMMON_API std::map< std::string, std::string > DependencyVersions ()
Returns a map of dependency versions.
FO_COMMON_API const std::string & FreeOrionVersionString ()
Returns the version string of FreeOrion.
void LogDependencyVersions ()
Log the map returned by DependencyVersions() into the info log channel.
Detailed Description
Declares free functions to access the application and dependency versions.
Function Documentation
FO_COMMON_API std::map<std::string, std::string> DependencyVersions ()
Returns a map of dependency versions.
Returns
A map with the dependency versions. The key represents the dependency name, the value corresponding dependency version string.
Note
This function returns different dependencies, depending on which game executable it was called from.
Referenced by LogDependencyVersions(), and target_sources().
FO_COMMON_API const std::string& FreeOrionVersionString ()
Returns the version string of FreeOrion.
The version strings consists of:
the VERSION number composed from MAJOR.MINOR.PATCH numbers. An optional '+' suffix indicates an in between test releases (think 0.4.6 + some more). Release candidates are suffixed with rcNUMBER.
the BRANCH, which represents the Git branch used to create this build.
the DATE as ISO 8601 date format.
the SHORT_COMMIT_HASH, which is the shortes Git commit hash, which identifies the commit this build was created from.
the BUILD_SYSTEM, which can be one of "CMake", "MSVC" or "XCode".
Returns
The version string with the format VERSION BRANCH_NAME [build DATE.SHORT_COMMIT_HASH] BUILD_SYSTEM
Referenced by PlayerConnection::ClientVersionStringMatchesThisServer(), HostMPGameMessage(), HostSPGameMessage(), if(), InitLoggingSystem(), IntroScreen::IntroScreen(), JoinGameMessage(), main(), mainConfigOptionsSetup(), mainSetupAndRun(), and SaveGamePreviewData::serialize().
void LogDependencyVersions ()
Log the map returned by DependencyVersions() into the info log channel.
References DependencyVersions(), and InfoLogger.
Referenced by HumanClientApp::HumanClientApp(), and ServerApp::ServerApp().