FreeOrion: anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string > Struct Template Reference
anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string > Struct Template Reference
Public Member Functions
SetOptionFunctor (const std::string &option_name, GG::Edit *edit=0, OptionsWnd::StringValidator string_validator=0)
void operator() (const std::string &str)
Public Attributes
GG::Edit * m_edit
const std::string m_option_name
OptionsWnd::StringValidator m_string_validator
Constructor & Destructor Documentation
anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string >::SetOptionFunctor (const std::string & option_name, GG::Edit * edit = 0, OptionsWnd::StringValidator string_validator = 0) inline
Member Function Documentation
void anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string >::operator() (const std::string & str) inline
References GetOptionsDB(), OptionsDB::Set(), and ClientUI::TextColor().
Member Data Documentation
GG::Edit* anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string >::m_edit
const std::string anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string >::m_option_name
OptionsWnd::StringValidator anonymous_namespace{OptionsWnd.cpp}::SetOptionFunctor< std::string >::m_string_validator
The documentation for this struct was generated from the following file:
OptionsWnd.cpp