FreeOrion: MultiTextureStaticGraphic Class Reference
MultiTextureStaticGraphic Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
MultiTextureStaticGraphic (const std::vector< boost::shared_ptr< GG::Texture > > &textures, const std::vector< GG::Flags< GG::GraphicStyle > > &styles=std::vector< GG::Flags< GG::GraphicStyle > >())
MultiTextureStaticGraphic (const std::vector< GG::SubTexture > &subtextures, const std::vector< GG::Flags< GG::GraphicStyle > > &styles=std::vector< GG::Flags< GG::GraphicStyle > >())
Mutators
virtual void Render ()
renders textures in order specified in constructor, back-to-front
Protected Member Functions
MultiTextureStaticGraphic ()
default ctor
GG::Rect RenderedArea (const GG::SubTexture &subtexture, GG::Flags< GG::GraphicStyle > style) const
Private Member Functions
void Init ()
void ValidateStyles ()
ensures that the style flags are consistent
Private Attributes
std::vector< GG::SubTexture > m_graphics
std::vector< GG::Flags
< GG::GraphicStyle > > m_styles
position of texture wrt the window area
Detailed Description
Functions like a StaticGraphic, except can have multiple textures rendered on top of eachother, rather than just a single texture.
Constructor & Destructor Documentation
MultiTextureStaticGraphic::MultiTextureStaticGraphic (const std::vector< boost::shared_ptr< GG::Texture > > & textures, const std::vector< GG::Flags< GG::GraphicStyle > > & styles = std::vector<GG::Flags<GG::GraphicStyle> >())
creates a MultiTextureStaticGraphic from multiple pre-existing Textures which are rendered back-to-front in the order they are specified in textures with GraphicStyles specified in the same-indexed value of styles. if styles is not specified or contains fewer entres than textures, entries in textures without associated styles use the style GRAPHIC_CENTER.
References Init(), and m_graphics.
MultiTextureStaticGraphic::MultiTextureStaticGraphic (const std::vector< GG::SubTexture > & subtextures, const std::vector< GG::Flags< GG::GraphicStyle > > & styles = std::vector<GG::Flags<GG::GraphicStyle> >())
creates a MultiTextureStaticGraphic from multiple pre-existing SubTextures which are rendered back-to-front in the order they are specified in subtextures with GraphicStyles specified in the same-indexed value of styles. if styles is not specified or contains fewer entres than subtextures, entries in subtextures without associated styles use the style GRAPHIC_CENTER.
References Init().
MultiTextureStaticGraphic::MultiTextureStaticGraphic () protected
default ctor
Member Function Documentation
void MultiTextureStaticGraphic::Init () private
References ValidateStyles().
Referenced by MultiTextureStaticGraphic().
void MultiTextureStaticGraphic::Render () virtual
renders textures in order specified in constructor, back-to-front
References m_graphics, m_styles, and RenderedArea().
GG::Rect MultiTextureStaticGraphic::RenderedArea (const GG::SubTexture & subtexture, GG::Flags< GG::GraphicStyle > style) const protected
Returns the area in which the graphic is actually rendered, in UpperLeft()-relative coordinates. This may not be the entire area of the StaticGraphic, based on the style being used.
Referenced by Render().
void MultiTextureStaticGraphic::ValidateStyles () private
ensures that the style flags are consistent
References m_graphics, and m_styles.
Referenced by Init().
Member Data Documentation
std::vector<GG::SubTexture> MultiTextureStaticGraphic::m_graphics private
Referenced by MultiTextureStaticGraphic(), Render(), and ValidateStyles().
std::vector<GG::Flags<GG::GraphicStyle> > MultiTextureStaticGraphic::m_styles private
position of texture wrt the window area
Referenced by Render(), and ValidateStyles().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp