FreeOrion: Sound::SoundImpl Class Reference
Sound::SoundImpl Class Reference
Public Member Functions
SoundImpl ()
ctor.
~SoundImpl ()
dotr.
void DecDisabledCount ()
void Disable ()
void DoFrame ()
void Enable ()
void FreeAllSounds ()
void FreeSound (const boost::filesystem::path &path)
void IncDisabledCount ()
void InitOpenAL ()
Initialize OpenAl and return true on success.
void PlayMusic (const boost::filesystem::path &path, int loops=0)
void PlaySound (const boost::filesystem::path &path, bool is_ui_sound=false)
void SetMusicVolume (int vol)
void SetUISoundsVolume (int vol)
void ShutdownOpenAL ()
void StopMusic ()
bool UISoundsTemporarilyDisabled () const
Private Attributes
std::map< std::string, ALuint > m_buffers
the currently-cached (and possibly playing) sounds, if any; keyed on filename
bool m_initialized
ALuint m_music_buffers [NUM_MUSIC_BUFFERS]
two additional buffers for music. statically defined as they'll be changed many times.
int m_music_loops
the number of loops of the current music to play (< 0 for loop forever)
std::string m_music_name
the name of the currently-playing music file
OggVorbis_File m_ogg_file
the currently open ogg file
ALenum m_ogg_format
mono or stereo
ALsizei m_ogg_freq
sampling frequency
ALuint m_sources [NUM_SOURCES]
OpenAL sound sources. The first one is used for music.
unsigned int m_temporary_disable_count
Count of the number of times sound was disabled. Sound is enabled when this is zero.
Static Private Attributes
static const int NUM_MUSIC_BUFFERS = 2
static const int NUM_SOURCES = 16
Constructor & Destructor Documentation
Sound::SoundImpl::SoundImpl ()
ctor.
References Enable(), and GetOptionsDB().
Sound::SoundImpl::~SoundImpl ()
dotr.
References Sound::Disable().
Member Function Documentation
void Sound::SoundImpl::DecDisabledCount ()
Decrease the temporary disabled depth.
void Sound::SoundImpl::Disable ()
Disable the sound system.
References DebugLogger, and Sound::StopMusic().
void Sound::SoundImpl::DoFrame ()
Does the work that must be done by the sound system once per frame.
this happens if RefillBuffer returns 1, meaning it encountered EOF and the file shouldn't be repeated
this may happen if the source plays all its buffers before we manage to refill them
References anonymous_namespace{Sound.cpp}::BUFFER_SIZE, and anonymous_namespace{Sound.cpp}::RefillBuffer().
void Sound::SoundImpl::Enable ()
Enables the sound system. Throws Sound::InitializationFailureException on failure.
References DebugLogger, and ErrorLogger.
Referenced by SoundImpl().
void Sound::SoundImpl::FreeAllSounds ()
Frees all cached sound data.
References ErrorLogger.
void Sound::SoundImpl::FreeSound (const boost::filesystem::path & path)
Frees the cached sound data associated with the filename.
References ErrorLogger, and PathString().
void Sound::SoundImpl::IncDisabledCount ()
Increment the temporary disabled depth.
void Sound::SoundImpl::InitOpenAL ()
Initialize OpenAl and return true on success.
Initialize OpenAL
References DebugLogger, and ErrorLogger.
void Sound::SoundImpl::PlayMusic (const boost::filesystem::path & path, int loops = 0)
Plays a music file. The file will be played in an infinitve loop if loop is < 0, and it will be played loops + 1 times otherwise.
References anonymous_namespace{Sound.cpp}::BUFFER_SIZE, ErrorLogger, PathString(), anonymous_namespace{Sound.cpp}::RefillBuffer(), and Sound::StopMusic().
void Sound::SoundImpl::PlaySound (const boost::filesystem::path & path, bool is_ui_sound = false)
Plays a sound file.
References ErrorLogger, GetOptionsDB(), PathString(), and anonymous_namespace{Sound.cpp}::RefillBuffer().
void Sound::SoundImpl::SetMusicVolume (int vol)
Sets the music volume from 0 (muted) to 255 (full volume); vol is range-adjusted.
References ErrorLogger, GetOptionsDB(), and OptionsDB::Set().
void Sound::SoundImpl::SetUISoundsVolume (int vol)
Sets the UI sounds volume from 0 (muted) to 255 (full volume); vol is range-adjusted.
References ErrorLogger, GetOptionsDB(), and OptionsDB::Set().
void Sound::SoundImpl::ShutdownOpenAL ()
Shutdown OpenAL.
void Sound::SoundImpl::StopMusic ()
Stops playing music.
bool Sound::SoundImpl::UISoundsTemporarilyDisabled () const
Member Data Documentation
std::map<std::string, ALuint> Sound::SoundImpl::m_buffers private
the currently-cached (and possibly playing) sounds, if any; keyed on filename
bool Sound::SoundImpl::m_initialized private
m_initialized indicates if the sound system has been initialized. The system will not be initialized if both sound effects and music are disabled or if initialization failed.
ALuint Sound::SoundImpl::m_music_buffers[NUM_MUSIC_BUFFERS] private
two additional buffers for music. statically defined as they'll be changed many times.
int Sound::SoundImpl::m_music_loops private
the number of loops of the current music to play (< 0 for loop forever)
std::string Sound::SoundImpl::m_music_name private
the name of the currently-playing music file
OggVorbis_File Sound::SoundImpl::m_ogg_file private
the currently open ogg file
ALenum Sound::SoundImpl::m_ogg_format private
mono or stereo
ALsizei Sound::SoundImpl::m_ogg_freq private
sampling frequency
ALuint Sound::SoundImpl::m_sources[NUM_SOURCES] private
OpenAL sound sources. The first one is used for music.
unsigned int Sound::SoundImpl::m_temporary_disable_count private
Count of the number of times sound was disabled. Sound is enabled when this is zero.
const int Sound::SoundImpl::NUM_MUSIC_BUFFERS = 2 static private
const int Sound::SoundImpl::NUM_SOURCES = 16 static private
The documentation for this class was generated from the following file:
Sound.cpp