FreeOrion: anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch Struct Reference
anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch Struct Reference
Public Member Functions
EnqueuedSimpleMatch (BuildType build_type, const std::string &name, int design_id, int empire_id, int low, int high)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
BuildType m_build_type
int m_design_id
int m_empire_id
int m_high
int m_low
std::string m_name
Constructor & Destructor Documentation
anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::EnqueuedSimpleMatch (BuildType build_type, const std::string & name, int design_id, int empire_id, int low, int high) inline
Member Function Documentation
bool anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References ALL_EMPIRES, Empires(), EmpireManager::end(), GetEmpire(), Empire::GetProductionQueue(), UniverseObject::ID(), m_build_type, m_design_id, m_empire_id, m_high, m_low, m_name, and anonymous_namespace{Condition.cpp}::NumberOnQueue().
Member Data Documentation
BuildType anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_build_type
Referenced by operator()().
int anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_design_id
Referenced by operator()().
int anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_empire_id
Referenced by operator()().
int anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_high
Referenced by operator()().
int anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_low
Referenced by operator()().
std::string anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::m_name
Referenced by operator()().
The documentation for this struct was generated from the following file:
Condition.cpp