FreeOrion: anonymous_namespace{SpecialsParser.cpp}::rules Struct Reference
anonymous_namespace{SpecialsParser.cpp}::rules Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(double
&, int &), parse::skipper_type > spawn_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::string
&, std::string
&), parse::skipper_type > special_prefix_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, Special * >
&), qi::locals< std::string,
std::string, double, int,
Condition::ConditionBase
*, std::vector
< boost::shared_ptr
< Effect::EffectsGroup >
>, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< double >
* >, parse::skipper_type > special_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, Special * >
&), parse::skipper_type > start_rule
Public Member Functions
rules ()
Public Attributes
spawn_rule spawn
special_rule special
special_prefix_rule special_prefix
start_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (double&, int&), parse::skipper_type > anonymous_namespace{SpecialsParser.cpp}::rules::spawn_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::string&, std::string&), parse::skipper_type > anonymous_namespace{SpecialsParser.cpp}::rules::special_prefix_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, Special*>&), qi::locals< std::string, std::string, double, int, Condition::ConditionBase*, std::vector<boost::shared_ptr<Effect::EffectsGroup> >, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>* >, parse::skipper_type > anonymous_namespace{SpecialsParser.cpp}::rules::special_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, Special*>&), parse::skipper_type > anonymous_namespace{SpecialsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{SpecialsParser.cpp}::rules::rules () inline
References parse::detail::condition_parser, parse::double_, parse::detail::effects_group_parser(), anonymous_namespace{SpecialsParser.cpp}::insert, parse::lexer::instance(), parse::int_, parse::label(), parse::report_error, parse::lexer::string, and parse::value_ref_parser< double >().
Member Data Documentation
spawn_rule anonymous_namespace{SpecialsParser.cpp}::rules::spawn
special_rule anonymous_namespace{SpecialsParser.cpp}::rules::special
special_prefix_rule anonymous_namespace{SpecialsParser.cpp}::rules::special_prefix
start_rule anonymous_namespace{SpecialsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
SpecialsParser.cpp