FreeOrion: anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2 Struct Reference
anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals< MeterType,
ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< double > *, std::string >
, parse::skipper_type > set_meter_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals< ResourceType,
ValueRef::ValueRefBase< int >
*, Visibility,
EmpireAffiliationType,
Condition::ConditionBase * >
, parse::skipper_type > set_stockpile_or_vis_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< int >
* >, parse::skipper_type > string_string_int_rule
Public Member Functions
effect_parser_rules_2 ()
Public Attributes
parse::effect_parser_rule set_empire_capital
set_stockpile_or_vis_rule set_empire_stockpile
set_meter_rule set_meter
parse::effect_parser_rule set_owner
parse::effect_parser_rule set_planet_size
parse::effect_parser_rule set_planet_type
set_meter_rule set_ship_part_meter
parse::effect_parser_rule set_species
string_string_int_rule set_species_opinion
set_stockpile_or_vis_rule set_visibility
parse::effect_parser_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< MeterType, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<double>*, std::string >, parse::skipper_type > anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_meter_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ResourceType, ValueRef::ValueRefBase<int>*, Visibility, EmpireAffiliationType, Condition::ConditionBase* >, parse::skipper_type > anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_stockpile_or_vis_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<int>* >, parse::skipper_type > anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::string_string_int_rule
Constructor & Destructor Documentation
anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2 () inline
References anonymous_namespace{EnumParser.cpp}::_1, anonymous_namespace{EnumParser.cpp}::_val, AFFIL_ANY, AFFIL_SELF, parse::detail::condition_parser, parse::enum_parser< EmpireAffiliationType >(), parse::lexer::instance(), parse::label(), parse::set_non_ship_part_meter_type_enum(), parse::set_ship_part_meter_type_enum(), parse::lexer::string, parse::value_ref_parser< double >(), parse::value_ref_parser< int >(), parse::value_ref_parser< PlanetSize >(), and parse::value_ref_parser< PlanetType >().
Member Data Documentation
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_empire_capital
set_stockpile_or_vis_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_empire_stockpile
set_meter_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_meter
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_owner
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_planet_size
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_planet_type
set_meter_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_ship_part_meter
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_species
string_string_int_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_species_opinion
set_stockpile_or_vis_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::set_visibility
parse::effect_parser_rule anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::start
The documentation for this struct was generated from the following file:
EffectParser2.cpp