FreeOrion: anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules Struct Reference
anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules Struct Reference
Public Member Functions
variable_parser_rules ()
Public Attributes
name_token_rule container_type
reference_token_rule variable_scope
Constructor & Destructor Documentation
anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_parser_rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, container_type(), ValueRef::EFFECT_TARGET_REFERENCE, parse::lexer::instance(), ValueRef::SOURCE_REFERENCE, and variable_scope().
Member Data Documentation
name_token_rule anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::container_type
Referenced by container_type().
reference_token_rule anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_scope
Referenced by variable_scope().
The documentation for this struct was generated from the following file:
ValueRefParserImpl.cpp