FreeOrion: ValueRef< T > Struct Template Reference
ValueRef< T > Struct Template Reference
#include <ValueRef.h>
Classes
struct ComplexVariable
struct Constant
struct Operation
struct StaticCast
struct Statistic
struct StringCast
struct Variable
Public Types
enum LookupType { INVALID_LOOKUP = -1, OBJECT_NAME, EMPIRE_NAME, SHIP_DESIGN_NAME }
enum OpType {
PLUS, MINUS, TIMES, DIVIDE,
NEGATE, EXPONENTIATE, ABS, LOGARITHM,
SINE, COSINE, MINIMUM, MAXIMUM,
RANDOM_UNIFORM, RANDOM_PICK, SUBSTITUTION
}
enum ReferenceType {
INVALID_REFERENCE_TYPE = -1, NON_OBJECT_REFERENCE, SOURCE_REFERENCE, EFFECT_TARGET_REFERENCE,
EFFECT_TARGET_VALUE_REFERENCE, CONDITION_LOCAL_CANDIDATE_REFERENCE, CONDITION_ROOT_CANDIDATE_REFERENCE
}
enum StatisticType {
INVALID_STATISTIC_TYPE = -1, COUNT, UNIQUE_COUNT, IF,
SUM, MEAN, RMS, MODE,
MAX, MIN, SPREAD, STDEV,
PRODUCT
}
Public Member Functions
~ComplexVariable ()
~NameLookup ()
~Operation ()
~StaticCast ()
~Statistic ()
~StringCast ()
~UserStringLookup ()
ComplexVariable (const std::string &variable_name, ValueRefBase< int > *int_ref1=0, ValueRefBase< int > *int_ref2=0, ValueRefBase< int > *int_ref3=0, ValueRefBase< std::string > *string_ref1=0, ValueRefBase< std::string > *string_ref2=0)
Constant (T value)
basic ctor
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual T Eval (const ScriptingContext &context) const
virtual T Eval (const ScriptingContext &context) const
virtual T Eval (const ScriptingContext &context) const
virtual T Eval (const ScriptingContext &context) const
virtual ToType Eval (const ScriptingContext &context) const
virtual std::string Eval (const ScriptingContext &context) const
virtual std::string Eval (const ScriptingContext &context) const
virtual std::string Eval (const ScriptingContext &context) const
virtual T Eval (const ScriptingContext &context) const
LookupType GetLookupType () const
OpType GetOpType () const
ReferenceType GetReferenceType () const
const Condition::ConditionBase * GetSamplingCondition () const
StatisticType GetStatisticType () const
const ValueRef::ValueRefBase< T > * GetValueRef () const
const ValueRefBase< FromType > * GetValueRef () const
const ValueRefBase< FromType > * GetValueRef () const
const ValueRefBase< std::string > * GetValueRef () const
const ValueRefBase< int > * GetValueRef () const
const ValueRefBase< int > * IntRef1 () const
const ValueRefBase< int > * IntRef2 () const
const ValueRefBase< int > * IntRef3 () const
const ValueRefBase< T > * LHS () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
virtual bool LocalCandidateInvariant () const
NameLookup (ValueRef::ValueRefBase< int > *value_ref, LookupType lookup_type)
const std::vector
< ValueRefBase< T > * > & Operands () const
Operation (OpType op_type, ValueRefBase< T > *operand1, ValueRefBase< T > *operand2)
binary operation ctor
Operation (OpType op_type, ValueRefBase< T > *operand)
unary operation ctor
Operation (OpType op_type, const std::vector< ValueRefBase< T > * > &operands)
nary operation ctor
virtual bool operator== (const ValueRef::ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< T > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< ToType > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< std::string > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< std::string > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< std::string > &rhs) const
virtual bool operator== (const ValueRef::ValueRefBase< T > &rhs) const
const std::vector< std::string > & PropertyName () const
const ValueRefBase< T > * RHS () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SimpleIncrement () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
StaticCast (ValueRef::Variable< FromType > *value_ref)
StaticCast (ValueRef::ValueRefBase< FromType > *value_ref)
Statistic (ValueRef::ValueRefBase< T > *value_ref, StatisticType stat_type, Condition::ConditionBase *sampling_condition)
StringCast (ValueRef::Variable< FromType > *value_ref)
StringCast (ValueRef::ValueRefBase< FromType > *value_ref)
const ValueRefBase< std::string > * StringRef1 () const
const ValueRefBase< std::string > * StringRef2 () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
UserStringLookup (ValueRef::Variable< std::string > *value_ref)
UserStringLookup (ValueRef::ValueRefBase< std::string > *value_ref)
T Value () const
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name)
Variable (ReferenceType ref_type, const std::string &property_name="")
Protected Member Functions
void GetConditionMatches (const ScriptingContext &context, Condition::ObjectSet &condition_targets, Condition::ConditionBase *condition) const
void GetObjectPropertyValues (const ScriptingContext &context, const Condition::ObjectSet &objects, std::map< TemporaryPtr< const UniverseObject >, T > &object_property_values) const
T ReduceData (const std::map< TemporaryPtr< const UniverseObject >, T > &object_property_values) const
Protected Attributes
ValueRefBase< int > * m_int_ref1
ValueRefBase< int > * m_int_ref2
ValueRefBase< int > * m_int_ref3
std::vector< std::string > m_property_name
ReferenceType m_ref_type
ValueRefBase< std::string > * m_string_ref1
ValueRefBase< std::string > * m_string_ref2
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
LookupType m_lookup_type
OpType m_op_type
std::vector< ValueRefBase< T > * > m_operands
Condition::ConditionBase * m_sampling_condition
StatisticType m_stat_type
std::string m_top_level_content
T m_value
ValueRef::ValueRefBase< T > * m_value_ref
ValueRefBase< FromType > * m_value_ref
ValueRefBase< std::string > * m_value_ref
ValueRefBase< int > * m_value_ref
Friends
class boost::serialization::access
Detailed Description
template<class T>
struct ValueRef< T >
the constant value leaf ValueRef class.
The variable value ValueRef class. The value returned by this node is taken from the gamestate, most often from the Source or Target objects.
The variable statistic class. The value returned by this node is computed from the general gamestate; the value of the indicated property_name is computed for each object that matches sampling_condition and the statistic indicated by stat_type is calculated from them and returned.
The complex variable ValueRef class. The value returned by this node is taken from the gamestate.
The variable static_cast class. The value returned by this node is taken from the ctor value_ref parameter's FromType value, static_cast to ToType.
The variable lexical_cast to string class. The value returned by this node is taken from the ctor value_ref parameter's FromType value, lexical_cast to std::string
Looks up a string ValueRef and returns the UserString equivalent.
Returns the in-game name of the object / empire / etc. with a specified id.
An arithmetic operation node ValueRef class. One of addition, subtraction, mutiplication, division, or unary negation is performed on the child(ren) of this node, and the result is returned.
Member Enumeration Documentation
template<class T > enum ValueRef::LookupType
Enumerator
INVALID_LOOKUP
OBJECT_NAME
EMPIRE_NAME
SHIP_DESIGN_NAME
template<class T > enum ValueRef::OpType
Enumerator
PLUS
MINUS
TIMES
DIVIDE
NEGATE
EXPONENTIATE
ABS
LOGARITHM
SINE
COSINE
MINIMUM
MAXIMUM
RANDOM_UNIFORM
RANDOM_PICK
SUBSTITUTION
template<class T > enum ValueRef::ReferenceType
Enumerator
INVALID_REFERENCE_TYPE
NON_OBJECT_REFERENCE
SOURCE_REFERENCE
EFFECT_TARGET_REFERENCE
EFFECT_TARGET_VALUE_REFERENCE
CONDITION_LOCAL_CANDIDATE_REFERENCE
CONDITION_ROOT_CANDIDATE_REFERENCE
template<class T > enum ValueRef::StatisticType
Enumerator
INVALID_STATISTIC_TYPE
COUNT
UNIQUE_COUNT
IF
SUM
MEAN
RMS
MODE
MAX
MIN
SPREAD
STDEV
PRODUCT
Constructor & Destructor Documentation
template<class T > ValueRef< T >::~Statistic ()
template<class T > ValueRef< T >::~ComplexVariable ()
template<class T > ValueRef< T >::~StaticCast ()
template<class T > ValueRef< T >::~StringCast ()
template<class T > ValueRef< T >::~UserStringLookup ()
template<class T > ValueRef< T >::~NameLookup ()
template<class T > ValueRef< T >::~Operation ()
Member Function Documentation
template<class T > ValueRef< T >::ComplexVariable (const std::string & variable_name, ValueRefBase< int > * int_ref1 = 0, ValueRefBase< int > * int_ref2 = 0, ValueRefBase< int > * int_ref3 = 0, ValueRefBase< std::string > * string_ref1 = 0, ValueRefBase< std::string > * string_ref2 = 0) explicit
template<class T > ValueRef< T >::Constant (T value)
basic ctor
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Description () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual std::string ValueRef< T >::Dump () const virtual
template<class T > virtual T ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual T ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual T ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual T ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual ToType ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual std::string ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual std::string ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual std::string ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > virtual T ValueRef< T >::Eval (const ScriptingContext & context) const virtual
template<class T > void ValueRef< T >::GetConditionMatches (const ScriptingContext & context, Condition::ObjectSet & condition_targets, Condition::ConditionBase * condition) const protected
Gets the set of objects in the Universe that match the sampling condition.
template<class T > LookupType ValueRef< T >::GetLookupType () const inline
References ValueRef< T >::m_lookup_type.
template<class T > void ValueRef< T >::GetObjectPropertyValues (const ScriptingContext & context, const Condition::ObjectSet & objects, std::map< TemporaryPtr< const UniverseObject >, T > & object_property_values) const protected
Evaluates the property for the specified objects.
template<class T > OpType ValueRef< T >::GetOpType () const
template<class T > ReferenceType ValueRef< T >::GetReferenceType () const
template<class T > const Condition::ConditionBase* ValueRef< T >::GetSamplingCondition () const inline
References ValueRef< T >::m_sampling_condition.
template<class T > StatisticType ValueRef< T >::GetStatisticType () const inline
References ValueRef< T >::m_stat_type.
template<class T > const ValueRef::ValueRefBase<T>* ValueRef< T >::GetValueRef () const inline
References ValueRef< T >::m_value_ref.
template<class T > const ValueRefBase<FromType>* ValueRef< T >::GetValueRef () const inline
References ValueRef< T >::m_value_ref.
template<class T > const ValueRefBase<FromType>* ValueRef< T >::GetValueRef () const inline
References ValueRef< T >::m_value_ref.
template<class T > const ValueRefBase<std::string>* ValueRef< T >::GetValueRef () const inline
References ValueRef< T >::m_value_ref.
template<class T > const ValueRefBase<int>* ValueRef< T >::GetValueRef () const inline
References ValueRef< T >::m_value_ref.
template<class T > const ValueRefBase<int>* ValueRef< T >::IntRef1 () const
template<class T > const ValueRefBase<int>* ValueRef< T >::IntRef2 () const
template<class T > const ValueRefBase<int>* ValueRef< T >::IntRef3 () const
template<class T > const ValueRefBase<T>* ValueRef< T >::LHS () const
Referenced by ValueRef< T >::Operation< T >::Eval().
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const inline virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::LocalCandidateInvariant () const virtual
template<class T > ValueRef< T >::NameLookup (ValueRef< T >::ValueRefBase< int > * value_ref, LookupType lookup_type)
Referenced by anonymous_namespace{ObjectListWnd.cpp}::DesignNameValueRef(), anonymous_namespace{ObjectListWnd.cpp}::EmpireNameValueRef(), and anonymous_namespace{ObjectListWnd.cpp}::ObjectNameValueRef().
template<class T > const std::vector<ValueRefBase<T>*>& ValueRef< T >::Operands () const
template<class T > ValueRef< T >::Operation (OpType op_type, ValueRefBase< T > * operand1, ValueRefBase< T > * operand2)
binary operation ctor
template<class T > ValueRef< T >::Operation (OpType op_type, ValueRefBase< T > * operand)
unary operation ctor
template<class T > ValueRef< T >::Operation (OpType op_type, const std::vector< ValueRefBase< T > * > & operands)
nary operation ctor
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< T > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< T > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< T > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< T > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< ToType > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< std::string > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< std::string > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< std::string > & rhs) const virtual
template<class T > virtual bool ValueRef< T >::operator== (const ValueRef< T >::ValueRefBase< T > & rhs) const virtual
template<class T > const std::vector<std::string>& ValueRef< T >::PropertyName () const
template<class T > T ValueRef< T >::ReduceData (const std::map< TemporaryPtr< const UniverseObject >, T > & object_property_values) const protected
Computes the statistic from the specified set of property values.
template<class T > const ValueRefBase<T>* ValueRef< T >::RHS () const
Referenced by ValueRef< T >::Operation< T >::Eval().
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const inline virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > virtual bool ValueRef< T >::RootCandidateInvariant () const virtual
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > template<class Archive > void ValueRef< T >::serialize (Archive & ar, const unsigned int version) private
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual void ValueRef< T >::SetTopLevelContent (const std::string & content_name) virtual
template<class T > virtual bool ValueRef< T >::SimpleIncrement () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const inline virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > virtual bool ValueRef< T >::SourceInvariant () const virtual
template<class T > ValueRef< T >::StaticCast (ValueRef< T >::Variable< FromType > * value_ref)
template<class T > ValueRef< T >::StaticCast (ValueRef< T >::ValueRefBase< FromType > * value_ref)
template<class T > ValueRef< T >::Statistic (ValueRef< T >::ValueRefBase< T > * value_ref, StatisticType stat_type, Condition::ConditionBase * sampling_condition)
template<class T > ValueRef< T >::StringCast (ValueRef< T >::Variable< FromType > * value_ref)
template<class T > ValueRef< T >::StringCast (ValueRef< T >::ValueRefBase< FromType > * value_ref)
template<class T > const ValueRefBase<std::string>* ValueRef< T >::StringRef1 () const
template<class T > const ValueRefBase<std::string>* ValueRef< T >::StringRef2 () const
template<class T > virtual bool ValueRef< T >::TargetInvariant () const inline virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > virtual bool ValueRef< T >::TargetInvariant () const virtual
template<class T > ValueRef< T >::UserStringLookup (ValueRef< T >::Variable< std::string > * value_ref)
Referenced by anonymous_namespace{ObjectListWnd.cpp}::UserStringCastedValueRef(), and anonymous_namespace{ObjectListWnd.cpp}::UserStringValueRef().
template<class T > ValueRef< T >::UserStringLookup (ValueRef< T >::ValueRefBase< std::string > * value_ref)
template<class T > T ValueRef< T >::Value () const
template<class T > ValueRef< T >::Variable (ReferenceType ref_type, const std::vector< std::string > & property_name)
template<class T > ValueRef< T >::Variable (ReferenceType ref_type, const std::string & property_name = "")
Friends And Related Function Documentation
template<class T > boost::serialization::access friend
Member Data Documentation
template<class T > ValueRefBase<int>* ValueRef< T >::m_int_ref1 protected
Referenced by ValueRef< T >::ComplexVariable< T >::Eval().
template<class T > ValueRefBase<int>* ValueRef< T >::m_int_ref2 protected
Referenced by ValueRef< T >::ComplexVariable< T >::Eval().
template<class T > ValueRefBase<int>* ValueRef< T >::m_int_ref3 protected
template<class T > LookupType ValueRef< T >::m_lookup_type private
Referenced by ValueRef< T >::GetLookupType().
template<class T > OpType ValueRef< T >::m_op_type private
Referenced by ValueRef< T >::Operation< T >::Eval().
template<class T > std::vector<ValueRefBase<T>*> ValueRef< T >::m_operands private
Referenced by ValueRef< T >::Operation< T >::Eval().
template<class T > std::vector<std::string> ValueRef< T >::m_property_name protected
Referenced by ValueRef< T >::Variable< T >::Eval(), and ValueRef< T >::ComplexVariable< T >::Eval().
template<class T > ReferenceType ValueRef< T >::m_ref_type mutable protected
Referenced by ValueRef< T >::Variable< T >::Eval().
template<class T > Condition::ConditionBase* ValueRef< T >::m_sampling_condition private
Referenced by ValueRef< T >::GetSamplingCondition().
template<class T > StatisticType ValueRef< T >::m_stat_type private
Referenced by ValueRef< T >::GetStatisticType().
template<class T > ValueRefBase<std::string>* ValueRef< T >::m_string_ref1 protected
Referenced by ValueRef< T >::ComplexVariable< T >::Eval().
template<class T > ValueRefBase<std::string>* ValueRef< T >::m_string_ref2 protected
Referenced by ValueRef< T >::ComplexVariable< T >::Eval().
template<class T > std::string ValueRef< T >::m_top_level_content private
template<class T > T ValueRef< T >::m_value private
template<class T > ValueRefBase< FromType > * ValueRef< T >::m_value_ref private
Referenced by ValueRef< T >::StringCast< FromType >::Eval(), and ValueRef< T >::GetValueRef().
template<class T > ValueRefBase<FromType>* ValueRef< T >::m_value_ref private
template<class T > ValueRefBase<std::string>* ValueRef< T >::m_value_ref private
template<class T > ValueRefBase<int>* ValueRef< T >::m_value_ref private
The documentation for this struct was generated from the following files:
ValueRef.h
ValueRefFwd.h