FreeOrion: anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch Struct Reference
anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch Struct Reference
Public Member Functions
EmpireMeterValueSimpleMatch (int empire_id, float low, float high, const std::string &meter)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
int m_empire_id
float m_high
float m_low
std::string m_meter
Constructor & Destructor Documentation
anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::EmpireMeterValueSimpleMatch (int empire_id, float low, float high, const std::string & meter) inline
Member Function Documentation
bool anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References Meter::Current(), GetEmpire(), Empire::GetMeter(), m_empire_id, m_high, m_low, and m_meter.
Member Data Documentation
int anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::m_empire_id
Referenced by operator()().
float anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::m_high
Referenced by operator()().
float anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::m_low
Referenced by operator()().
std::string anonymous_namespace{Condition.cpp}::EmpireMeterValueSimpleMatch::m_meter
Referenced by operator()().
The documentation for this struct was generated from the following file:
Condition.cpp