FreeOrion: PartsListBox Class Reference
PartsListBox Class Reference
Classes
class PartsListBoxRow
Public Member Functions
bool GetShowingSuperfluous () const
Structors
PartsListBox (void)
Accessors
const std::set< ShipPartClass > & GetClassesShown () const
const std::set< ShipSlotType > & GetSlotTypesShown () const
const std::pair< bool, bool > & GetAvailabilitiesShown () const
Mutators
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
PartGroupsType GroupAvailableDisplayableParts (const Empire *empire)
void CullSuperfluousParts (std::vector< const PartType * > &this_group, ShipPartClass pclass, int empire_id, int loc_id)
void Populate ()
void ShowClass (ShipPartClass part_class, bool refresh_list=true)
void ShowAllClasses (bool refresh_list=true)
void HideClass (ShipPartClass part_class, bool refresh_list=true)
void HideAllClasses (bool refresh_list=true)
void ShowAvailability (bool available, bool refresh_list=true)
void HideAvailability (bool available, bool refresh_list=true)
void ShowSuperfluousParts (bool refresh_list=true)
void HideSuperfluousParts (bool refresh_list=true)
Public Member Functions inherited from CUIListBox
CUIListBox (void)
basic ctor
virtual void Render ()
Public Attributes
boost::signals2::signal< void(const
PartType *)> PartTypeClickedSignal
boost::signals2::signal< void(const
PartType *)> PartTypeDoubleClickedSignal
Private Attributes
std::pair< bool, bool > m_availabilities_shown
std::set< ShipPartClass > m_part_classes_shown
int m_previous_num_columns
bool m_show_superfluous_parts
Detailed Description
Arrangement of PartControls that can be dragged onto SlotControls
Constructor & Destructor Documentation
PartsListBox::PartsListBox (void)
Member Function Documentation
void PartsListBox::CullSuperfluousParts (std::vector< const PartType * > & this_group, ShipPartClass pclass, int empire_id, int loc_id)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References anonymous_namespace{DesignWnd.cpp}::GetMainStat(), PartALocationSubsumesPartB(), PartType::ProductionCost(), PartType::ProductionTime(), UserString(), UserStringExists(), and UserStringList().
Referenced by Populate().
const std::pair< bool, bool > & PartsListBox::GetAvailabilitiesShown () const
References m_availabilities_shown.
const std::set< ShipPartClass > & PartsListBox::GetClassesShown () const
References m_part_classes_shown.
bool PartsListBox::GetShowingSuperfluous () const inline
References m_show_superfluous_parts.
const std::set<ShipSlotType>& PartsListBox::GetSlotTypesShown () const
PartGroupsType PartsListBox::GroupAvailableDisplayableParts (const Empire * empire)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References PartTypeManager::begin(), PartType::Class(), PartTypeManager::end(), GetPartTypeManager(), m_availabilities_shown, m_part_classes_shown, PartType::MountableSlotTypes(), PartType::Name(), PartType::Producible(), and Empire::ShipPartAvailable().
Referenced by Populate().
void PartsListBox::HideAllClasses (bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_part_classes_shown, and Populate().
void PartsListBox::HideAvailability (bool available, bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_availabilities_shown, and Populate().
void PartsListBox::HideClass (ShipPartClass part_class, bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_part_classes_shown, and Populate().
void PartsListBox::HideSuperfluousParts (bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_show_superfluous_parts, and Populate().
void PartsListBox::Populate ()
The Parts are first filtered for availability to this empire and according to the current selections of which part classes are to be displayed. Then, in order to eliminate presentation of clearly suboptimal parts, such as Mass Driver I when Mass Driver II is available at the same cost & build time, some orgnization, paring and sorting of parts is done. The previously filtered parts are grouped according to (class, slot). Within each group, parts are compared and pared for display; only parts within the same group may suppress display of each other. The paring is (currently) done on the basis of main stat, construction cost, and construction time. If two parts have the same class and slot, and one has a lower main stat but also a lower cost, they will both be presented; if one has a higher main stat and is at least as good on cost and time, it will suppress the other.
An example of one of the more subtle possible results is that if a part class had multiple parts with different but overlapping MountableSlotType patterns, then a part with two possible slot types might be rendered superfluous for the first slot type by a first other part, be rendered superfluous for the second slot type by a second other part, even if neither of the latter two parts would be considered to individually render the former part obsolete.
filter parts by availability and current designation of classes for display; group according to (class, slot)
References Empire::CapitalID(), PartControl::ClickedSignal, CullSuperfluousParts(), PartControl::DoubleClickedSignal, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), anonymous_namespace{DesignWnd.cpp}::GetMainStat(), GetUniverseObject(), GroupAvailableDisplayableParts(), UniverseObject::ID(), INVALID_OBJECT_ID, m_previous_num_columns, m_show_superfluous_parts, anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS(), anonymous_namespace{DesignWnd.cpp}::PAD(), PartTypeClickedSignal, PartTypeDoubleClickedSignal, ClientUI::ScrollWidth(), anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_HEIGHT(), and anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH().
Referenced by HideAllClasses(), HideAvailability(), HideClass(), HideSuperfluousParts(), ShowAllClasses(), ShowAvailability(), ShowClass(), ShowSuperfluousParts(), and SizeMove().
void PartsListBox::ShowAllClasses (bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_part_classes_shown, and Populate().
void PartsListBox::ShowAvailability (bool available, bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_availabilities_shown, and Populate().
void PartsListBox::ShowClass (ShipPartClass part_class, bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_part_classes_shown, and Populate().
void PartsListBox::ShowSuperfluousParts (bool refresh_list = true)
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_show_superfluous_parts, and Populate().
void PartsListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
This is not merely a check for obsolescence; see PartsListBox::Populate for more info
References m_previous_num_columns, anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS(), anonymous_namespace{DesignWnd.cpp}::PAD(), Populate(), ClientUI::ScrollWidth(), and anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH().
Member Data Documentation
std::pair<bool, bool> PartsListBox::m_availabilities_shown private
Referenced by GetAvailabilitiesShown(), GroupAvailableDisplayableParts(), HideAvailability(), and ShowAvailability().
std::set<ShipPartClass> PartsListBox::m_part_classes_shown private
Referenced by GetClassesShown(), GroupAvailableDisplayableParts(), HideAllClasses(), HideClass(), ShowAllClasses(), and ShowClass().
int PartsListBox::m_previous_num_columns private
Referenced by Populate(), and SizeMove().
bool PartsListBox::m_show_superfluous_parts private
Referenced by GetShowingSuperfluous(), HideSuperfluousParts(), Populate(), and ShowSuperfluousParts().
boost::signals2::signal<void (const PartType*)> PartsListBox::PartTypeClickedSignal mutable
Referenced by PartsListBox::PartsListBoxRow::ChildrenDraggedAway(), DesignWnd::PartPalette::PartPalette(), and Populate().
boost::signals2::signal<void (const PartType*)> PartsListBox::PartTypeDoubleClickedSignal mutable
Referenced by PartsListBox::PartsListBoxRow::ChildrenDraggedAway(), DesignWnd::PartPalette::PartPalette(), and Populate().
The documentation for this class was generated from the following file:
DesignWnd.cpp