FreeOrion: CombatReportWnd::CombatReportPrivate Class Reference
CombatReportWnd::CombatReportPrivate Class Reference
Public Member Functions
CombatReportPrivate (CombatReportWnd &wnd)
void DoLayout ()
GG::Pt GetMinSize () const
void HandleLinkClick (const std::string &link_type, const std::string &data)
void HandleLinkDoubleClick (const std::string &link_type, const std::string &data)
void SetLog (int log_id)
Private Member Functions
void HandleTabChanged (size_t tabnum)
void HandleWindowChanged ()
void RectangleEnter (int data)
void SetFocus (int id)
void UpdateMinSize ()
Private Attributes
GraphicalSummaryWnd * m_graphical
CombatLogWnd * m_log
GG::ScrollPanel * m_log_scroller
GG::Pt m_min_size
GG::TabWnd * m_tabs
CombatReportWnd & m_wnd
Constructor & Destructor Documentation
CombatReportWnd::CombatReportPrivate::CombatReportPrivate (CombatReportWnd & wnd) inline
References ClientUI::CtrlColor(), ClientUI::GetFont(), HandleLinkClick(), HandleLinkDoubleClick(), HandleTabChanged(), HandleWindowChanged(), CombatLogWnd::LinkClickedSignal, CombatLogWnd::LinkDoubleClickedSignal, CombatLogWnd::LinkRightClickedSignal, m_graphical, m_log, m_log_scroller, m_tabs, m_wnd, GraphicalSummaryWnd::MinSizeChangedSignal, CombatLogWnd::SetFont(), UpdateMinSize(), UserString(), and CombatLogWnd::WndChangedSignal.
Member Function Documentation
void CombatReportWnd::CombatReportPrivate::DoLayout () inline
References CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_tabs, and m_wnd.
Referenced by HandleWindowChanged().
GG::Pt CombatReportWnd::CombatReportPrivate::GetMinSize () const inline
References m_min_size.
void CombatReportWnd::CombatReportPrivate::HandleLinkClick (const std::string & link_type, const std::string & data) inline
References VarText::BUILDING_ID_TAG, VarText::BUILDING_TYPE_TAG, VarText::COMBAT_ID_TAG, VarText::DESIGN_ID_TAG, VarText::EMPIRE_ID_TAG, TextLinker::ENCYCLOPEDIA_TAG, ErrorLogger, VarText::FIELD_ID_TAG, VarText::FIELD_TYPE_TAG, VarText::FLEET_ID_TAG, ClientUI::GetClientUI(), GetPredefinedShipDesign(), TextLinker::GRAPH_TAG, VarText::PLANET_ID_TAG, VarText::PREDEFINED_DESIGN_TAG, VarText::SHIP_HULL_TAG, VarText::SHIP_ID_TAG, VarText::SHIP_PART_TAG, VarText::SPECIAL_TAG, VarText::SPECIES_TAG, VarText::SYSTEM_ID_TAG, VarText::TECH_TAG, ClientUI::ZoomToBuilding(), ClientUI::ZoomToBuildingType(), ClientUI::ZoomToCombatLog(), ClientUI::ZoomToEmpire(), ClientUI::ZoomToEncyclopediaEntry(), ClientUI::ZoomToField(), ClientUI::ZoomToFieldType(), ClientUI::ZoomToFleet(), ClientUI::ZoomToPlanet(), ClientUI::ZoomToShip(), ClientUI::ZoomToShipDesign(), ClientUI::ZoomToShipHull(), ClientUI::ZoomToShipPart(), ClientUI::ZoomToSpecial(), ClientUI::ZoomToSpecies(), ClientUI::ZoomToSystem(), and ClientUI::ZoomToTech().
Referenced by CombatReportPrivate(), and HandleLinkDoubleClick().
void CombatReportWnd::CombatReportPrivate::HandleLinkDoubleClick (const std::string & link_type, const std::string & data) inline
References HandleLinkClick().
Referenced by CombatReportPrivate().
void CombatReportWnd::CombatReportPrivate::HandleTabChanged (size_t tabnum) inline private
References CombatLogWnd::HandleMadeVisible(), HandleWindowChanged(), and m_log.
Referenced by CombatReportPrivate().
void CombatReportWnd::CombatReportPrivate::HandleWindowChanged () inline private
References DoLayout(), and UpdateMinSize().
Referenced by CombatReportPrivate(), and HandleTabChanged().
void CombatReportWnd::CombatReportPrivate::RectangleEnter (int data) inline private
References DebugLogger, and SetFocus().
void CombatReportWnd::CombatReportPrivate::SetFocus (int id) inline private
References DebugLogger.
Referenced by RectangleEnter().
void CombatReportWnd::CombatReportPrivate::SetLog (int log_id) inline
References ClientUI::GetFont(), m_graphical, m_log, m_log_scroller, CombatLogWnd::SetFont(), CombatLogWnd::SetLog(), and GraphicalSummaryWnd::SetLog().
void CombatReportWnd::CombatReportPrivate::UpdateMinSize () inline private
References ClientUI::GetFont(), CUIWnd::INNER_BORDER_ANGLE_OFFSET, m_min_size, m_tabs, and m_wnd.
Referenced by CombatReportPrivate(), and HandleWindowChanged().
Member Data Documentation
GraphicalSummaryWnd* CombatReportWnd::CombatReportPrivate::m_graphical private
Referenced by CombatReportPrivate(), and SetLog().
CombatLogWnd* CombatReportWnd::CombatReportPrivate::m_log private
Referenced by CombatReportPrivate(), HandleTabChanged(), and SetLog().
GG::ScrollPanel* CombatReportWnd::CombatReportPrivate::m_log_scroller private
Referenced by CombatReportPrivate(), and SetLog().
GG::Pt CombatReportWnd::CombatReportPrivate::m_min_size private
Referenced by GetMinSize(), and UpdateMinSize().
GG::TabWnd* CombatReportWnd::CombatReportPrivate::m_tabs private
Referenced by CombatReportPrivate(), DoLayout(), and UpdateMinSize().
CombatReportWnd& CombatReportWnd::CombatReportPrivate::m_wnd private
Referenced by CombatReportPrivate(), DoLayout(), and UpdateMinSize().
The documentation for this class was generated from the following file:
CombatReportWnd.cpp