FreeOrion: Condition::Number Struct Reference
Condition::Number Struct Reference
#include <Condition.h>
Public Member Functions
Number (ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high, ConditionBase *condition)
virtual ~Number ()
virtual std::string Description (bool negated=false) const
virtual std::string Dump () const
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
const ConditionBase * GetCondition () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * Low () const
virtual bool operator== (const ConditionBase &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
void Eval (ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ConditionBase * m_condition
ValueRef::ValueRefBase< int > * m_high
ValueRef::ValueRefBase< int > * m_low
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects if the number of objects that match Condition condition is is >= low and < high. Matched objects may or may not themselves match the condition.
Constructor & Destructor Documentation
Condition::Number::Number (ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high, ConditionBase * condition) inline
Condition::Number::~Number () virtual
References m_condition, m_high, and m_low.
Member Function Documentation
std::string Condition::Number::Description (bool negated = false) const virtual
Implements Condition::ConditionBase.
References ValueRef::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), Condition::ConditionBase::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), m_condition, m_high, m_low, and UserString().
std::string Condition::Number::Dump () const virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), Condition::ConditionBase::Dump(), DumpIndent(), g_indent, m_condition, m_high, and m_low.
void Condition::Number::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, ErrorLogger, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), m_condition, m_high, m_low, Condition::MATCHES, Condition::NON_MATCHES, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
void Condition::Number::Eval (ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
References Condition::ConditionBase::Eval().
const ConditionBase* Condition::Number::GetCondition () const inline
const ValueRef::ValueRefBase<int>* Condition::Number::High () const inline
const ValueRef::ValueRefBase<int>* Condition::Number::Low () const inline
bool Condition::Number::Match (const ScriptingContext & local_context) const private virtual
Reimplemented from Condition::ConditionBase.
References Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), m_condition, m_high, and m_low.
bool Condition::Number::operator== (const ConditionBase & rhs) const virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, m_condition, m_high, and m_low.
bool Condition::Number::RootCandidateInvariant () const virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_condition, m_high, m_low, ValueRef::ValueRefBase< T >::RootCandidateInvariant(), and Condition::ConditionBase::RootCandidateInvariant().
template<class Archive > void Condition::Number::serialize (Archive & ar, const unsigned int version) private
References m_condition, m_high, and m_low.
void Condition::Number::SetTopLevelContent (const std::string & content_name) virtual
Implements Condition::ConditionBase.
References m_high, m_low, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::Number::SourceInvariant () const virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_condition, m_high, m_low, ValueRef::ValueRefBase< T >::SourceInvariant(), and Condition::ConditionBase::SourceInvariant().
bool Condition::Number::TargetInvariant () const virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_condition, m_high, m_low, ValueRef::ValueRefBase< T >::TargetInvariant(), and Condition::ConditionBase::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ConditionBase* Condition::Number::m_condition private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SourceInvariant(), TargetInvariant(), and ~Number().
ValueRef::ValueRefBase<int>* Condition::Number::m_high private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~Number().
ValueRef::ValueRefBase<int>* Condition::Number::m_low private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~Number().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp