FreeOrion: anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch Struct Reference
anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch Struct Reference
Public Member Functions
WithinStarlaneJumpsSimpleMatch (const Condition::ObjectSet &from_objects, int jump_limit)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
const Condition::ObjectSet & m_from_objects
int m_jump_limit
Constructor & Destructor Documentation
anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch::WithinStarlaneJumpsSimpleMatch (const Condition::ObjectSet & from_objects, int jump_limit) inline
Member Function Documentation
bool anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References GetUniverse(), UniverseObject::ID(), Universe::JumpDistanceBetweenObjects(), m_from_objects, and m_jump_limit.
Member Data Documentation
const Condition::ObjectSet& anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch::m_from_objects
Referenced by operator()().
int anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch::m_jump_limit
Referenced by operator()().
The documentation for this struct was generated from the following file:
Condition.cpp