FreeOrion: Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch Struct Reference
Public Member Functions
OrderedBombardedSimpleMatch (const ObjectSet &by_objects)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
const ObjectSet & m_by_objects
Constructor & Destructor Documentation
Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::OrderedBombardedSimpleMatch (const ObjectSet & by_objects) inline
Member Function Documentation
bool Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References boost::dynamic_pointer_cast(), UniverseObject::ID(), INVALID_OBJECT_ID, and Ship::OrderedBombardPlanet().
Member Data Documentation
const ObjectSet& Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::m_by_objects
The documentation for this struct was generated from the following file:
Condition.cpp