FreeOrion: Ship Class Reference
Ship Class Reference
#include <Ship.h>
Public Types
typedef std::map< std::pair
< MeterType, std::string >
, Meter > PartMeterMap
Public Types inherited from UniverseObject
typedef
boost::signals2::signal< void(),
blocking_combiner
< boost::signals2::optional_last_value
< void > > > StateChangedSignalType
typedef
StateChangedSignalType::slot_type StateChangedSlotType
Public Types inherited from EnableTemporaryFromThis< UniverseObject >
typedef
EnableTemporaryFromThis
< UniverseObject > enable_temporary_from_this_type
Public Member Functions
Accessors
virtual std::set< std::string > Tags () const
returns all tags this object has
virtual bool HasTag (const std::string &name) const
returns true iff this object has the tag with the indicated name
virtual UniverseObjectType ObjectType () const
returns all tags this object has
virtual std::string Dump () const
returns all tags this object has
const ShipDesign * Design () const
returns the design of the ship, containing engine type, weapons, etc.
int DesignID () const
returns the design id of the ship
virtual int ContainerObjectID () const
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
virtual bool ContainedBy (int object_id) const
returns true if there is an object with id object_id that contains this UniverseObject
int FleetID () const
returns the ID of the fleet the ship is residing in
int ProducedByEmpireID () const
returns the empire ID of the empire that produced this ship
int ArrivedOnTurn () const
returns the turn on which this ship arrived in its current system
virtual const std::string & PublicName (int empire_id) const
returns all tags this object has
bool IsMonster () const
returns all tags this object has
bool IsArmed () const
returns all tags this object has
bool CanColonize () const
returns all tags this object has
bool HasTroops () const
returns all tags this object has
bool CanBombard () const
returns all tags this object has
const std::string & SpeciesName () const
returns all tags this object has
float Speed () const
returns all tags this object has
float ColonyCapacity () const
returns all tags this object has
float TroopCapacity () const
returns all tags this object has
virtual TemporaryPtr
< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const
returns all tags this object has
virtual float NextTurnCurrentMeterValue (MeterType type) const
returns expected value of specified meter current value on the next turn
bool OrderedScrapped () const
returns true iff this ship has been ordered scrapped, or false otherwise
int OrderedColonizePlanet () const
returns the ID of the planet this ship has been ordered to colonize, or INVALID_OBJECT_ID if this ship hasn't been ordered to colonize a planet
int OrderedInvadePlanet () const
returns the ID of the planet this ship has been ordered to invade with ground troops, or INVALID_OBJECT_ID if this ship hasn't been ordered to invade a planet
int OrderedBombardPlanet () const
returns the ID of the planet this ship has been ordered to bombard, or INVALID_OBJECT_ID if this ship hasn't been ordered to bombard a planet
int LastTurnActiveInCombat () const
returns the last turn this ship has been actively involved in combat
const PartMeterMap & PartMeters () const
returns this Ship's part meters
const Meter * GetPartMeter (MeterType type, const std::string &part_name) const
returns the requested part Meter, or 0 if no such part Meter of that type is found in this ship for that part name
float CurrentPartMeterValue (MeterType type, const std::string &part_name) const
returns current value of the specified part meter type for the specified part name
float InitialPartMeterValue (MeterType type, const std::string &part_name) const
returns this turn's initial value for the speicified part meter type for the specified part name
float TotalWeaponsDamage (float shield_DR=0.0f, bool include_fighters=true) const
versus an enemy with a given shields DR
std::vector< float > AllWeaponsDamage (float shield_DR=0.0f, bool include_fighters=true) const
any nonzero weapons strengths after adjustment versus an enemy with a given shields DR
std::vector< float > AllWeaponsMaxDamage (float shield_DR=0.0f, bool include_fighters=true) const
any nonzero weapons strengths, assuming the shpi has been refueled recently, after adjustment versus an enemy with a given shields DR
Mutators
virtual void Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES)
back propegates part meters (which UniverseObject equivalent doesn't)
virtual void BackPropegateMeters ()
back propegates part meters (which UniverseObject equivalent doesn't)
void SetFleetID (int fleet_id)
sets the ID of the fleet the ship resides in
void SetArrivedOnTurn (int turn)
back propegates part meters (which UniverseObject equivalent doesn't)
void Resupply ()
back propegates part meters (which UniverseObject equivalent doesn't)
void SetSpecies (const std::string &species_name)
back propegates part meters (which UniverseObject equivalent doesn't)
void SetOrderedScrapped (bool b=true)
flags ship for scrapping
void SetColonizePlanet (int planet_id)
marks ship to colonize the indicated planet
void ClearColonizePlanet ()
marks ship to colonize no planets
void SetInvadePlanet (int planet_id)
marks ship to invade the indicated planet
void ClearInvadePlanet ()
marks ship to invade no planets
void SetBombardPlanet (int planet_id)
marks ship to bombard the indicated planet
void ClearBombardPlanet ()
marks ship to bombard no planets
void SetLastTurnActiveInCombat (int turn)
sets the last turn this ship was actively involved in combat
Meter * GetPartMeter (MeterType type, const std::string &part_name)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void ResetTargetMaxUnpairedMeters ()
back propegates part meters (which UniverseObject equivalent doesn't)
virtual void ResetPairedActiveMeters ()
back propegates part meters (which UniverseObject equivalent doesn't)
virtual void SetShipMetersToMax ()
back propegates part meters (which UniverseObject equivalent doesn't)
Public Member Functions inherited from UniverseObject
void SetID (int id)
sets the ID number of the object to id
void Rename (const std::string &name)
renames this object to name
void Move (double x, double y)
void MoveTo (int object_id)
void MoveTo (TemporaryPtr< UniverseObject > object)
void MoveTo (double x, double y)
std::map< MeterType, Meter > & Meters ()
returns this UniverseObject's meters
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void SetOwner (int id)
sets the empire that owns this object
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void SetSpecialCapacity (const std::string &name, float capacity)
virtual void MovementPhase ()
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const std::string & Name () const
returns the name of this object; some valid objects will have no name
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
bool Unowned () const
returns true iff there are no owners of this object
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
const std::map< std::string,
std::pair< int, float > > & Specials () const
returns the Specials attached to this object
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
emitted when the UniverseObject is altered in any way
virtual const std::set< int > & ContainedObjectIDs () const
returns ids of objects contained within this object
virtual bool Contains (int object_id) const
returns true if there is an object with id object_id is contained within this UniverseObject
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
const std::map< MeterType,
Meter > & Meters () const
returns this UniverseObject's meters
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
float CurrentMeterValue (MeterType type) const
returns current value of the specified meter type
float InitialMeterValue (MeterType type) const
returns this turn's initial value for the speicified meter type
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
int CreationTurn () const
returns game turn on which object was created
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
Public Member Functions inherited from EnableTemporaryFromThis< UniverseObject >
EnableTemporaryFromThis ()
TemporaryPtr< UniverseObject > TemporaryFromThis ()
TemporaryPtr< const
UniverseObject > TemporaryFromThis () const
Private Member Functions
virtual void ClampMeters ()
virtual void PopGrowthProductionResearchPhase ()
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_arrived_on_turn
int m_design_id
int m_fleet_id
int m_last_turn_active_in_combat
int m_ordered_bombard_planet_id
int m_ordered_colonize_planet_id
int m_ordered_invade_planet_id
bool m_ordered_scrapped
PartMeterMap m_part_meters
int m_produced_by_empire_id
std::string m_species_name
Friends
class boost::serialization::access
class Universe
Structors
template<class T >
void boost::python::detail::value_destroyer (T const volatile *p)
default ctor
template<class T >
void boost::checked_delete (T *x)
default ctor
Ship ()
default ctor
Ship (int empire_id, int design_id, const std::string &species_name, int produced_by_empire_id=ALL_EMPIRES)
general ctor taking ship's empire and design id, species name and production empire id.
~Ship ()
default ctor
virtual Ship * Clone (int empire_id=ALL_EMPIRES) const
returns new copy of this Ship
Additional Inherited Members
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Member Functions inherited from UniverseObject
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (TemporaryPtr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
used by public UniverseObject::Copy and derived classes' ::Copy methods
void Init ()
adds stealth meter
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
virtual ~UniverseObject ()
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
a class representing a single FreeOrion ship
Member Typedef Documentation
typedef std::map<std::pair<MeterType, std::string>, Meter> Ship::PartMeterMap
Constructor & Destructor Documentation
Ship::Ship () protected
default ctor
Referenced by Clone().
Ship::Ship (int empire_id, int design_id, const std::string & species_name, int produced_by_empire_id = ALL_EMPIRES) protected
general ctor taking ship's empire and design id, species name and production empire id.
References UniverseObject::AddMeter(), PartType::Class(), DebugLogger, Design(), ErrorLogger, GetPartType(), GetShipDesign(), GetSpecies(), UniverseObject::Init(), m_part_meters, m_species_name, METER_CAPACITY, METER_DETECTION, METER_FUEL, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SPEED, METER_STRUCTURE, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, PartType::Name(), ShipDesign::Parts(), PC_COLONY, PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, PC_TROOPS, and UniverseObject::SetOwner().
Ship::~Ship () inline protected
default ctor
Member Function Documentation
TemporaryPtr< UniverseObject > Ship::Accept (const UniverseObjectVisitor & visitor) const virtual
returns all tags this object has
Reimplemented from UniverseObject.
References EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis(), and UniverseObjectVisitor::Visit().
std::vector< float > Ship::AllWeaponsDamage (float shield_DR = 0.0f, bool include_fighters = true) const
any nonzero weapons strengths after adjustment versus an enemy with a given shields DR
References GetShipDesign(), m_design_id, and anonymous_namespace{Ship.cpp}::WeaponDamageImpl().
Referenced by TotalWeaponsDamage().
std::vector< float > Ship::AllWeaponsMaxDamage (float shield_DR = 0.0f, bool include_fighters = true) const
any nonzero weapons strengths, assuming the shpi has been refueled recently, after adjustment versus an enemy with a given shields DR
References GetShipDesign(), m_design_id, and anonymous_namespace{Ship.cpp}::WeaponDamageImpl().
int Ship::ArrivedOnTurn () const inline
returns the turn on which this ship arrived in its current system
void Ship::BackPropegateMeters () virtual
back propegates part meters (which UniverseObject equivalent doesn't)
Reimplemented from UniverseObject.
References UniverseObject::BackPropegateMeters(), and m_part_meters.
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::CreateShip::Execute().
bool Ship::CanBombard () const
returns all tags this object has
References ShipDesign::CanBombard(), and Design().
Referenced by BombardOrder::ExecuteImpl(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), and FreeOrionPython::WrapUniverseClasses().
bool Ship::CanColonize () const
returns all tags this object has
References Species::CanColonize(), ShipDesign::CanColonize(), Design(), GetSpecies(), m_species_name, and parse::species().
Referenced by anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), ColonizeOrder::ExecuteImpl(), Fleet::HasColonyShips(), Fleet::HasOutpostShips(), and FreeOrionPython::WrapUniverseClasses().
void Ship::ClampMeters () private virtual
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
Reimplemented from UniverseObject.
References Meter::ClampCurrentToRange(), UniverseObject::ClampMeters(), Meter::Current(), Meter::DEFAULT_VALUE, UniverseObject::GetMeter(), m_part_meters, METER_CAPACITY, METER_DETECTION, METER_FUEL, METER_INDUSTRY, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_RESEARCH, METER_SECONDARY_STAT, METER_SHIELD, METER_SPEED, METER_STRUCTURE, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
void Ship::ClearBombardPlanet ()
marks ship to bombard no planets
References INVALID_OBJECT_ID, and SetBombardPlanet().
Referenced by BombardOrder::UndoImpl().
void Ship::ClearColonizePlanet ()
marks ship to colonize no planets
References INVALID_OBJECT_ID, and SetColonizePlanet().
Referenced by ColonizeOrder::UndoImpl().
void Ship::ClearInvadePlanet ()
marks ship to invade no planets
References INVALID_OBJECT_ID, and SetInvadePlanet().
Referenced by InvadeOrder::UndoImpl().
Ship * Ship::Clone (int empire_id = ALL_EMPIRES) const protected virtual
returns new copy of this Ship
Implements UniverseObject.
References Copy(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), Ship(), and EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis().
float Ship::ColonyCapacity () const
returns all tags this object has
References PartType::Class(), CurrentPartMeterValue(), Design(), GetPartType(), METER_CAPACITY, ShipDesign::Parts(), and PC_COLONY.
Referenced by anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), ColonizeOrder::ExecuteImpl(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), SidePanel::PlanetPanel::Refresh(), and FreeOrionPython::WrapUniverseClasses().
bool Ship::ContainedBy (int object_id) const virtual
returns true if there is an object with id object_id that contains this UniverseObject
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, m_fleet_id, and UniverseObject::SystemID().
virtual int Ship::ContainerObjectID () const inline virtual
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
Reimplemented from UniverseObject.
void Ship::Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) virtual
back propegates part meters (which UniverseObject equivalent doesn't)
Implements UniverseObject.
References UniverseObject::Copy(), boost::dynamic_pointer_cast(), ErrorLogger, GetFleet(), Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), UniverseObject::ID(), m_arrived_on_turn, m_design_id, m_fleet_id, m_last_turn_active_in_combat, UniverseObject::m_name, m_ordered_bombard_planet_id, m_ordered_colonize_planet_id, m_ordered_invade_planet_id, m_ordered_scrapped, m_part_meters, m_produced_by_empire_id, m_species_name, and UniverseObject::Unowned().
Referenced by Clone().
float Ship::CurrentPartMeterValue (MeterType type, const std::string & part_name) const
returns current value of the specified part meter type for the specified part name
References GetPartMeter().
Referenced by ColonyCapacity(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), TroopCapacity(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{Ship.cpp}::WeaponDamageImpl(), and FreeOrionPython::WrapUniverseClasses().
const ShipDesign * Ship::Design () const
returns the design of the ship, containing engine type, weapons, etc.
References GetShipDesign(), and m_design_id.
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), AutomaticallyChosenColonyShip(), CanBombard(), CanColonize(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), ColonyCapacity(), Effect::CreateShip::Execute(), Universe::GetEffectsAndTargets(), Fleet::HasColonyShips(), Fleet::HasOutpostShips(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), ShipDataPanel::Init(), IsArmed(), IsMonster(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), Condition::anonymous_namespace{Condition.cpp}::DesignHasHullSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartClassSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PredefinedShipDesignSimpleMatch::operator()(), PublicName(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), ShipDataPanel::Refresh(), ShipDataPanel::SetShipIcon(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), Ship(), TroopCapacity(), and FreeOrionPython::WrapUniverseClasses().
int Ship::DesignID () const inline
returns the design id of the ship
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), anonymous_namespace{Universe.cpp}::GetDesignIDFromObject(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), Empire::UpdateOwnedObjectCounters(), and FreeOrionPython::WrapUniverseClasses().
std::string Ship::Dump () const virtual
returns all tags this object has
Reimplemented from UniverseObject.
References Meter::Current(), UniverseObject::Dump(), m_arrived_on_turn, m_design_id, m_fleet_id, m_part_meters, m_produced_by_empire_id, m_species_name, and UserString().
int Ship::FleetID () const inline
returns the ID of the fleet the ship is residing in
Referenced by FleetsListBox::AcceptDrops(), ShipsListBox::AcceptDrops(), anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), CombatInfo::CombatInfo(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsForShips(), ShipsListBox::DropsAcceptable(), Effect::MoveTo::Execute(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), ShipDataPanel::Init(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), AIInterface::IssueColonizeOrder(), AIInterface::IssueInvadeOrder(), ColonizeOrder::UndoImpl(), InvadeOrder::UndoImpl(), BombardOrder::UndoImpl(), Universe::UpdateEmpireStaleObjectKnowledge(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), and FreeOrionPython::WrapUniverseClasses().
const Meter * Ship::GetPartMeter (MeterType type, const std::string & part_name) const
returns the requested part Meter, or 0 if no such part Meter of that type is found in this ship for that part name
Referenced by CurrentPartMeterValue(), Effect::SetShipPartMeter::Execute(), anonymous_namespace{CombatSystem.cpp}::IncreaseStoredFighterCount(), InitialPartMeterValue(), Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::operator()(), and anonymous_namespace{CombatSystem.cpp}::ReduceStoredFighterCount().
Meter * Ship::GetPartMeter (MeterType type, const std::string & part_name)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
References m_part_meters.
bool Ship::HasTag (const std::string & name) const virtual
returns true iff this object has the tag with the indicated name
Reimplemented from UniverseObject.
References GetHullType(), GetPartType(), GetShipDesign(), GetSpecies(), ShipDesign::Hull(), m_design_id, ShipDesign::Parts(), parse::species(), SpeciesName(), Species::Tags(), PartType::Tags(), and HullType::Tags().
bool Ship::HasTroops () const
returns all tags this object has
References TroopCapacity().
Referenced by anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), InvadeOrder::ExecuteImpl(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), Fleet::HasTroopShips(), ShipDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
float Ship::InitialPartMeterValue (MeterType type, const std::string & part_name) const
returns this turn's initial value for the speicified part meter type for the specified part name
References GetPartMeter().
Referenced by FreeOrionPython::WrapUniverseClasses().
bool Ship::IsArmed () const
returns all tags this object has
References Design(), and ShipDesign::IsArmed().
Referenced by Fleet::HasArmedShips(), ShipDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
bool Ship::IsMonster () const
returns all tags this object has
References Design(), and ShipDesign::IsMonster().
Referenced by Effect::CreateShip::Execute(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), Fleet::HasMonsters(), PublicName(), and FreeOrionPython::WrapUniverseClasses().
int Ship::LastTurnActiveInCombat () const inline
returns the last turn this ship has been actively involved in combat
float Ship::NextTurnCurrentMeterValue (MeterType type) const virtual
returns expected value of specified meter current value on the next turn
Reimplemented from UniverseObject.
References Meter::Current(), CurrentTurn(), UniverseObject::GetMeter(), INVALID_METER_TYPE, m_last_turn_active_in_combat, METER_INDUSTRY, METER_MAX_SHIELD, METER_RESEARCH, METER_SHIELD, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and UniverseObject::NextTurnCurrentMeterValue().
Referenced by PopGrowthProductionResearchPhase().
UniverseObjectType Ship::ObjectType () const virtual
returns all tags this object has
Reimplemented from UniverseObject.
int Ship::OrderedBombardPlanet () const inline
returns the ID of the planet this ship has been ordered to bombard, or INVALID_OBJECT_ID if this ship hasn't been ordered to bombard a planet
Referenced by anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::operator()(), ShipDataPanel::SetShipIcon(), and BombardOrder::UndoImpl().
int Ship::OrderedColonizePlanet () const inline
returns the ID of the planet this ship has been ordered to colonize, or INVALID_OBJECT_ID if this ship hasn't been ordered to colonize a planet
Referenced by anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), ShipDataPanel::SetShipIcon(), ColonizeOrder::UndoImpl(), and FreeOrionPython::WrapUniverseClasses().
int Ship::OrderedInvadePlanet () const inline
returns the ID of the planet this ship has been ordered to invade with ground troops, or INVALID_OBJECT_ID if this ship hasn't been ordered to invade a planet
Referenced by anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), ShipDataPanel::SetShipIcon(), InvadeOrder::UndoImpl(), and FreeOrionPython::WrapUniverseClasses().
bool Ship::OrderedScrapped () const inline
returns true iff this ship has been ordered scrapped, or false otherwise
Referenced by anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), Fleet::Fuel(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), Fleet::HasShipsOrderedScrapped(), Fleet::HasShipsWithoutScrapOrders(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), Fleet::MaxFuel(), ShipDataPanel::SetShipIcon(), FleetDetailPanel::ShipRightClicked(), and FreeOrionPython::WrapUniverseClasses().
const PartMeterMap& Ship::PartMeters () const inline
returns this Ship's part meters
void Ship::PopGrowthProductionResearchPhase () private virtual
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
Reimplemented from UniverseObject.
References UniverseObject::GetMeter(), METER_INDUSTRY, METER_RESEARCH, METER_SHIELD, METER_TRADE, NextTurnCurrentMeterValue(), UniverseObject::PopGrowthProductionResearchPhase(), Meter::SetCurrent(), and UniverseObject::StateChangedSignal.
int Ship::ProducedByEmpireID () const inline
returns the empire ID of the empire that produced this ship
Referenced by FreeOrionPython::WrapUniverseClasses().
const std::string & Ship::PublicName (int empire_id) const virtual
returns all tags this object has
Reimplemented from UniverseObject.
References ALL_EMPIRES, Design(), GetUniverse(), UniverseObject::GetVisibility(), IsMonster(), UniverseObject::Name(), ShipDesign::Name(), UniverseObject::OwnedBy(), UniverseObject::Owner(), UniverseObject::Unowned(), and UserString().
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), and ShipDataPanel::Refresh().
void Ship::ResetPairedActiveMeters () virtual
back propegates part meters (which UniverseObject equivalent doesn't)
Reimplemented from UniverseObject.
References m_part_meters, METER_CAPACITY, METER_MAX_CAPACITY, METER_MAX_SECONDARY_STAT, METER_SECONDARY_STAT, and UniverseObject::ResetPairedActiveMeters().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::CreateShip::Execute().
void Ship::ResetTargetMaxUnpairedMeters () virtual
back propegates part meters (which UniverseObject equivalent doesn't)
Reimplemented from UniverseObject.
References UniverseObject::GetMeter(), m_part_meters, METER_CAPACITY, METER_DETECTION, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_SECONDARY_STAT, METER_SPEED, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, Meter::ResetCurrent(), and UniverseObject::ResetTargetMaxUnpairedMeters().
Referenced by anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::CreateShip::Execute().
void Ship::Resupply ()
back propegates part meters (which UniverseObject equivalent doesn't)
References Meter::BackPropegate(), Meter::Current(), ErrorLogger, UniverseObject::GetMeter(), m_part_meters, METER_CAPACITY, METER_FUEL, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_SECONDARY_STAT, and Meter::SetCurrent().
Referenced by Fleet::MovementPhase(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
template<class Archive > void Ship::serialize (Archive & ar, const unsigned int version) private
References m_arrived_on_turn, m_design_id, m_fleet_id, m_last_turn_active_in_combat, m_ordered_bombard_planet_id, m_ordered_colonize_planet_id, m_ordered_invade_planet_id, m_ordered_scrapped, m_part_meters, m_produced_by_empire_id, and m_species_name.
void Ship::SetArrivedOnTurn (int turn)
back propegates part meters (which UniverseObject equivalent doesn't)
References m_arrived_on_turn, and UniverseObject::StateChangedSignal.
void Ship::SetBombardPlanet (int planet_id)
marks ship to bombard the indicated planet
References m_ordered_bombard_planet_id, and UniverseObject::StateChangedSignal.
Referenced by ClearBombardPlanet(), and BombardOrder::ExecuteImpl().
void Ship::SetColonizePlanet (int planet_id)
marks ship to colonize the indicated planet
References m_ordered_colonize_planet_id, and UniverseObject::StateChangedSignal.
Referenced by ClearColonizePlanet(), ColonizeOrder::ExecuteImpl(), and anonymous_namespace{ServerApp.cpp}::HandleColonization().
void Ship::SetFleetID (int fleet_id)
sets the ID of the fleet the ship resides in
References m_fleet_id, and UniverseObject::StateChangedSignal.
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), NewFleetOrder::ExecuteImpl(), and FleetTransferOrder::ExecuteImpl().
void Ship::SetInvadePlanet (int planet_id)
marks ship to invade the indicated planet
References m_ordered_invade_planet_id, and UniverseObject::StateChangedSignal.
Referenced by ClearInvadePlanet(), and InvadeOrder::ExecuteImpl().
void Ship::SetLastTurnActiveInCombat (int turn) inline
sets the last turn this ship was actively involved in combat
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipFighter(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), and anonymous_namespace{CombatSystem.cpp}::LaunchFighters().
void Ship::SetOrderedScrapped (bool b = true)
flags ship for scrapping
References m_ordered_scrapped, and UniverseObject::StateChangedSignal.
void Ship::SetShipMetersToMax () virtual
back propegates part meters (which UniverseObject equivalent doesn't)
References UniverseObject::GetMeter(), Meter::LARGE_VALUE, m_part_meters, METER_CAPACITY, METER_FUEL, METER_MAX_CAPACITY, METER_MAX_FUEL, METER_MAX_SECONDARY_STAT, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_SECONDARY_STAT, METER_SHIELD, METER_STRUCTURE, and Meter::SetCurrent().
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::CreateShip::Execute().
void Ship::SetSpecies (const std::string & species_name)
back propegates part meters (which UniverseObject equivalent doesn't)
References ErrorLogger, GetSpecies(), and m_species_name.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
const std::string& Ship::SpeciesName () const inline
returns all tags this object has
Referenced by AutomaticallyChosenColonyShip(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), ColonizeOrder::ExecuteImpl(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescription(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), Universe::GetEffectsAndTargets(), anonymous_namespace{Universe.cpp}::GetSpeciesFromObject(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), HasTag(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Condition::Species::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), ShipDataPanel::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), Empire::UpdateOwnedObjectCounters(), and FreeOrionPython::WrapUniverseClasses().
float Ship::Speed () const
returns all tags this object has
References UniverseObject::CurrentMeterValue(), and METER_SPEED.
Referenced by FreeOrionPython::WrapUniverseClasses().
std::set< std::string > Ship::Tags () const virtual
returns all tags this object has
Reimplemented from UniverseObject.
References GetHullType(), GetPartType(), GetShipDesign(), ShipDesign::Hull(), m_design_id, ShipDesign::Parts(), and HullType::Tags().
float Ship::TotalWeaponsDamage (float shield_DR = 0.0f, bool include_fighters = true) const
versus an enemy with a given shields DR
References AllWeaponsDamage().
Referenced by anonymous_namespace{CombatSystem.cpp}::AttackShipFighter(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), AIInterface::IssueBombardOrder(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), and ShipDamageBrowseWnd::UpdateSummary().
float Ship::TroopCapacity () const
returns all tags this object has
References PartType::Class(), CurrentPartMeterValue(), Design(), GetPartType(), METER_CAPACITY, ShipDesign::Parts(), and PC_TROOPS.
Referenced by AutomaticallyChosenInvasionShips(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), HasTroops(), SidePanel::PlanetPanel::Refresh(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), and FreeOrionPython::WrapUniverseClasses().
Friends And Related Function Documentation
template<class T > void boost::checked_delete (T * x) friend
default ctor
template<class T > void boost::python::detail::value_destroyer (T const volatile * p) friend
default ctor
friend class boost::serialization::access friend
friend class Universe friend
Member Data Documentation
int Ship::m_arrived_on_turn private
Referenced by Copy(), Dump(), serialize(), and SetArrivedOnTurn().
int Ship::m_design_id private
Referenced by AllWeaponsDamage(), AllWeaponsMaxDamage(), Copy(), Design(), Dump(), HasTag(), serialize(), and Tags().
int Ship::m_fleet_id private
Referenced by ContainedBy(), Copy(), Dump(), serialize(), and SetFleetID().
int Ship::m_last_turn_active_in_combat private
Referenced by Copy(), NextTurnCurrentMeterValue(), and serialize().
int Ship::m_ordered_bombard_planet_id private
Referenced by Copy(), serialize(), and SetBombardPlanet().
int Ship::m_ordered_colonize_planet_id private
Referenced by Copy(), serialize(), and SetColonizePlanet().
int Ship::m_ordered_invade_planet_id private
Referenced by Copy(), serialize(), and SetInvadePlanet().
bool Ship::m_ordered_scrapped private
Referenced by Copy(), serialize(), and SetOrderedScrapped().
PartMeterMap Ship::m_part_meters private
Referenced by BackPropegateMeters(), ClampMeters(), Copy(), Dump(), GetPartMeter(), ResetPairedActiveMeters(), ResetTargetMaxUnpairedMeters(), Resupply(), serialize(), SetShipMetersToMax(), and Ship().
int Ship::m_produced_by_empire_id private
Referenced by Copy(), Dump(), and serialize().
std::string Ship::m_species_name private
Referenced by CanColonize(), Copy(), Dump(), serialize(), SetSpecies(), and Ship().
The documentation for this class was generated from the following files:
Ship.h
Ship.cpp
SerializeUniverse.cpp