FreeOrion: Effect Class Reference
Effect Class Reference abstract
#include <Effect.h>
Classes
struct AccountingInfo
struct EffectCause
struct SourcedEffectsGroup
struct TargetsAndCause
Public Types
typedef std::map< int,
std::map< MeterType,
std::vector< AccountingInfo > > > AccountingMap
typedef std::map< int,
std::map< MeterType,
std::vector< AccountingInfo > > > AccountingMap
typedef std::map< int,
std::map< MeterType, double > > DiscrepancyMap
typedef std::map< int,
std::map< MeterType, double > > DiscrepancyMap
typedef std::vector< std::pair
< SourcedEffectsGroup,
TargetsAndCause > > TargetsCauses
typedef std::vector< std::pair
< SourcedEffectsGroup,
TargetsAndCause > > TargetsCauses
typedef std::vector
< TemporaryPtr< UniverseObject > > TargetSet
typedef std::vector
< TemporaryPtr< UniverseObject > > TargetSet
Public Member Functions
~AddSpecial ()
virtual ~AddStarlanes ()
virtual ~CreateBuilding ()
virtual ~CreateField ()
virtual ~CreatePlanet ()
virtual ~CreateShip ()
virtual ~CreateSystem ()
virtual ~EffectBase ()
virtual ~EffectsGroup ()
virtual ~GenerateSitRepMessage ()
virtual ~GiveEmpireTech ()
virtual ~MoveInOrbit ()
virtual ~MoveTo ()
virtual ~MoveTowards ()
~RemoveSpecial ()
virtual ~RemoveStarlanes ()
virtual ~SetDestination ()
virtual ~SetEmpireCapital ()
virtual ~SetEmpireMeter ()
virtual ~SetEmpireStockpile ()
virtual ~SetEmpireTechProgress ()
virtual ~SetMeter ()
virtual ~SetOverlayTexture ()
virtual ~SetOwner ()
virtual ~SetPlanetSize ()
virtual ~SetPlanetType ()
virtual ~SetShipPartMeter ()
virtual ~SetSpecies ()
virtual ~SetSpeciesEmpireOpinion ()
virtual ~SetSpeciesSpeciesOpinion ()
virtual ~SetStarType ()
virtual ~SetVisibility ()
const std::string & AccountingLabel () const
Condition::ConditionBase * Activation () const
AddSpecial (const std::string &name, float capacity=1.0f)
AddSpecial (ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< double > *capacity=0)
AddStarlanes (Condition::ConditionBase *other_lane_endpoint_condition)
EmpireAffiliationType Affiliation () const
EmpireAffiliationType Affiliation () const
std::string AutoGeneratedDescription () const
Conditional (Condition::ConditionBase *target_condition, const std::vector< EffectBase * > &true_effects, const std::vector< EffectBase * > &false_effects)
CreateBuilding (ValueRef::ValueRefBase< std::string > *building_type_name, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateField (ValueRef::ValueRefBase< std::string > *field_type_name, ValueRef::ValueRefBase< double > *size=0, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateField (ValueRef::ValueRefBase< std::string > *field_type_name, ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< double > *size=0, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreatePlanet (ValueRef::ValueRefBase< PlanetType > *type, ValueRef::ValueRefBase< PlanetSize > *size, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateShip (ValueRef::ValueRefBase< std::string > *predefined_ship_design_name, ValueRef::ValueRefBase< int > *empire_id=0, ValueRef::ValueRefBase< std::string > *species_name=0, ValueRef::ValueRefBase< std::string > *ship_name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateShip (ValueRef::ValueRefBase< int > *ship_design_id, ValueRef::ValueRefBase< int > *empire_id=0, ValueRef::ValueRefBase< std::string > *species_name=0, ValueRef::ValueRefBase< std::string > *ship_name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateSystem (ValueRef::ValueRefBase< ::StarType > *type, ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
CreateSystem (ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< Effect::EffectBase * > &effects_to_apply_after=std::vector< Effect::EffectBase * >())
virtual std::string Description () const =0
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
virtual std::string Description () const
Destroy ()
std::string Dump () const
virtual std::string Dump () const =0
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
EffectsGroup (Condition::ConditionBase *scope, Condition::ConditionBase *activation, const std::vector< EffectBase * > &effects, const std::string &accounting_label="", const std::string &stacking_group="", int priority=0, std::string description="")
const std::vector< EffectBase * > & EffectsList () const
ValueRef::ValueRefBase< int > * EmpireID () const
void Execute (const Effect::TargetsCauses &targets_causes, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context) const =0
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const Effect::TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const ScriptingContext &context) const
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, ValueRef::ValueRefBase< int > *recipient_empire_id, EmpireAffiliationType affiliation, const std::string label="", bool stringtable_lookup=true)
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, EmpireAffiliationType affiliation, Condition::ConditionBase *condition=0, const std::string label="", bool stringtable_lookup=true)
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, EmpireAffiliationType affiliation, const std::string &label="", bool stringtable_lookup=true)
Condition::ConditionBase * GetCondition () const
const std::string & GetDescription () const
MeterType GetMeterType () const
MeterType GetMeterType () const
const ValueRef::ValueRefBase
< std::string > * GetPartName () const
const ValueRef::ValueRefBase
< std::string > * GetSpecialName () const
void GetTargetSet (int source_id, TargetSet &targets) const
void GetTargetSet (int source_id, TargetSet &targets, const TargetSet &potential_targets) const
void GetTargetSet (int source_id, TargetSet &targets, TargetSet &potential_targets) const
Visibility GetVisibility () const
GiveEmpireTech (ValueRef::ValueRefBase< std::string > *tech_name, ValueRef::ValueRefBase< int > *empire_id=0)
const std::string & Icon () const
const std::vector< std::pair
< std::string,
ValueRef::ValueRefBase
< std::string > * > > & MessageParameters () const
const std::string & MessageString () const
MoveInOrbit (ValueRef::ValueRefBase< double > *speed, Condition::ConditionBase *focal_point_condition)
MoveInOrbit (ValueRef::ValueRefBase< double > *speed, ValueRef::ValueRefBase< double > *focus_x=0, ValueRef::ValueRefBase< double > *focus_y=0)
MoveTo (Condition::ConditionBase *location_condition)
MoveTowards (ValueRef::ValueRefBase< double > *speed, Condition::ConditionBase *dest_condition)
MoveTowards (ValueRef::ValueRefBase< double > *speed, ValueRef::ValueRefBase< double > *dest_x=0, ValueRef::ValueRefBase< double > *dest_y=0)
int Priority () const
ValueRef::ValueRefBase< int > * RecipientID () const
RemoveSpecial (const std::string &name)
RemoveSpecial (ValueRef::ValueRefBase< std::string > *name)
RemoveStarlanes (Condition::ConditionBase *other_lane_endpoint_condition)
Condition::ConditionBase * Scope () const
SetAggression (bool aggressive)
SetDestination (Condition::ConditionBase *location_condition)
SetEmpireCapital ()
SetEmpireCapital (ValueRef::ValueRefBase< int > *empire_id)
SetEmpireMeter (const std::string &meter, ValueRef::ValueRefBase< double > *value)
SetEmpireMeter (ValueRef::ValueRefBase< int > *empire_id, const std::string &meter, ValueRef::ValueRefBase< double > *value)
SetEmpireStockpile (ResourceType stockpile, ValueRef::ValueRefBase< double > *value)
SetEmpireStockpile (ValueRef::ValueRefBase< int > *empire_id, ResourceType stockpile, ValueRef::ValueRefBase< double > *value)
SetEmpireTechProgress (ValueRef::ValueRefBase< std::string > *tech_name, ValueRef::ValueRefBase< double > *research_progress)
SetEmpireTechProgress (ValueRef::ValueRefBase< std::string > *tech_name, ValueRef::ValueRefBase< double > *research_progress, ValueRef::ValueRefBase< int > *empire_id)
SetMeter (MeterType meter, ValueRef::ValueRefBase< double > *value)
SetOverlayTexture (const std::string &texture, ValueRef::ValueRefBase< double > *size)
SetOwner (ValueRef::ValueRefBase< int > *empire_id)
SetPlanetSize (ValueRef::ValueRefBase< PlanetSize > *size)
SetPlanetType (ValueRef::ValueRefBase< PlanetType > *type)
SetShipPartMeter (MeterType meter_type, ValueRef::ValueRefBase< std::string > *part_name, ValueRef::ValueRefBase< double > *value)
SetSpecies (ValueRef::ValueRefBase< std::string > *species)
SetSpeciesEmpireOpinion (ValueRef::ValueRefBase< std::string > *species_name, ValueRef::ValueRefBase< int > *empire_id, ValueRef::ValueRefBase< double > *opinion)
SetSpeciesSpeciesOpinion (ValueRef::ValueRefBase< std::string > *opinionated_species_name, ValueRef::ValueRefBase< std::string > *rated_species_name, ValueRef::ValueRefBase< double > *opinion)
SetStarType (ValueRef::ValueRefBase< StarType > *type)
SetTexture (const std::string &texture)
void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)=0
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
SetVisibility (Visibility vis, EmpireAffiliationType affiliation, ValueRef::ValueRefBase< int > *empire_id=0)
const std::string & StackingGroup () const
Victory (const std::string &reason_string)
Protected Attributes
std::string m_accounting_label
Condition::ConditionBase * m_activation
std::string m_description
std::vector< EffectBase * > m_effects
int m_priority
Condition::ConditionBase * m_scope
std::string m_stacking_group
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
EmpireAffiliationType m_affiliation
bool m_aggressive
ValueRef::ValueRefBase
< std::string > * m_building_type_name
ValueRef::ValueRefBase< double > * m_capacity
Condition::ConditionBase * m_condition
ValueRef::ValueRefBase< int > * m_design_id
ValueRef::ValueRefBase
< std::string > * m_design_name
Condition::ConditionBase * m_dest_condition
ValueRef::ValueRefBase< double > * m_dest_x
ValueRef::ValueRefBase< double > * m_dest_y
std::vector< Effect::EffectBase * > m_effects_to_apply_after
ValueRef::ValueRefBase< int > * m_empire_id
std::vector< EffectBase * > m_false_effects
ValueRef::ValueRefBase
< std::string > * m_field_type_name
Condition::ConditionBase * m_focal_point_condition
ValueRef::ValueRefBase< double > * m_focus_x
ValueRef::ValueRefBase< double > * m_focus_y
std::string m_icon
std::string m_label
Condition::ConditionBase * m_location_condition
std::vector< std::pair
< std::string,
ValueRef::ValueRefBase
< std::string > * > > m_message_parameters
std::string m_message_string
MeterType m_meter
std::string m_meter
ValueRef::ValueRefBase
< std::string > * m_name
ValueRef::ValueRefBase< double > * m_opinion
ValueRef::ValueRefBase
< std::string > * m_opinionated_species_name
Condition::ConditionBase * m_other_lane_endpoint_condition
ValueRef::ValueRefBase
< std::string > * m_part_name
ValueRef::ValueRefBase
< std::string > * m_rated_species_name
std::string m_reason_string
ValueRef::ValueRefBase< int > * m_recipient_empire_id
ValueRef::ValueRefBase< double > * m_research_progress
ValueRef::ValueRefBase
< PlanetSize > * m_size
ValueRef::ValueRefBase< double > * m_size
ValueRef::ValueRefBase
< std::string > * m_species_name
ValueRef::ValueRefBase< double > * m_speed
ResourceType m_stockpile
bool m_stringtable_lookup
Condition::ConditionBase * m_target_condition
ValueRef::ValueRefBase
< std::string > * m_tech_name
std::string m_texture
std::vector< EffectBase * > m_true_effects
ValueRef::ValueRefBase
< PlanetType > * m_type
ValueRef::ValueRefBase
< ::StarType > * m_type
ValueRef::ValueRefBase
< StarType > * m_type
ValueRef::ValueRefBase< double > * m_value
Visibility m_vis
ValueRef::ValueRefBase< double > * m_x
ValueRef::ValueRefBase< double > * m_y
Friends
class boost::serialization::access
Detailed Description
Contains one or more Effects, a Condition which indicates the objects in the scope of the Effect(s), and a Condition which indicates whether or not the Effect(s) will be executed on the objects in scope during the current turn. Since Conditions operate on sets of objects (usually all objects in the universe), the activation condition bears some explanation. It exists to allow an EffectsGroup to be activated or suppressed based on the source object only (the object to which the EffectsGroup is attached). It does this by considering the "universe" containing only the source object. If the source object meets the activation condition, the EffectsGroup will be active in the current turn.
The base class for all Effects. When an Effect is executed, the source object (the object to which the Effect or its containing EffectGroup is attached) and the target object are both required. Note that this means that ValueRefs contained within Effects can refer to values in either the source or target objects.
Sets the meter of the given kind to value. The max value of the meter is set if max == true; otherwise the current value of the meter is set. If the target of the Effect does not have the requested meter, nothing is done.
Sets the indicated meter on all ship parts in the indicated subset. This has no effect on non-Ship targets. If slot_type is specified, only parts that can mount in the indicated slot type (internal or external) are affected (this is not the same at the slot type in which the part is actually located, as a part might be mountable in both types, and located in a different type than specified, and would be matched).
Sets the indicated meter on the empire with the indicated id to the indicated value. If meter is not a valid meter for empires, does nothing.
Sets the empire stockpile of the target's owning empire to value. If the target does not have exactly one owner, nothing is done.
Makes the target planet the capital of its owner's empire. If the target object is not a planet, does not have an owner, or has more than one owner the effect does nothing.
Sets the planet type of the target to type. This has no effect on non-Planet targets. Note that changing the type of a PT_ASTEROID or PT_GASGIANT planet will also change its size to SZ_TINY or SZ_HUGE, respectively. Similarly, changing type to PT_ASTEROID or PT_GASGIANT will also cause the size to change to SZ_ASTEROID or SZ_GASGIANT, respectively.
Sets the planet size of the target to size. This has no effect on non- Planet targets. Note that changing the size of a PT_ASTEROID or PT_GASGIANT planet will also change its type to PT_BARREN. Similarly, changing size to SZ_ASTEROID or SZ_GASGIANT will also cause the type to change to PT_ASTEROID or PT_GASGIANT, respectively.
Sets the species on the target to species_name. This works on planets and ships, but has no effect on other objects.
Sets empire empire_id as the owner of the target. This has no effect if empire_id was already the owner of the target object.
Sets the opinion of Species species for empire with id empire_id to opinion
Sets the opinion of Species opinionated_species for other species rated_species to opinion
Creates a new Planet with specified type and size at the system with specified location_id
Creates a new Building with specified type on the target Planet.
Creates a new Ship with specified predefined_ship_design_name design from those in the list of PredefinedShipDesignManager, and owned by the empire with the specified empire_id
Creates a new Field with specified field_type_name FieldType of the specified size.
Creates a new system with the specified colour and at the specified location.
Destroys the target object. When executed on objects that contain other objects (such as Fleets and Planets), all contained objects are destroyed as well. Destroy effects delay the desctruction of their targets until after other all effects have executed, to ensure the source or target of other effects are present when they execute.
Adds the Special with the name name to the target object.
Removes the Special with the name name to the target object. This has no effect if no such Special was already attached to the target object.
Creates starlane(s) between the target system and systems that match other_lane_endpoint_condition
Removes starlane(s) between the target system and systems that match other_lane_endpoint_condition
Sets the star type of the target to type. This has no effect on non-System targets.
Moves an UniverseObject to a location of another UniverseObject that matches the condition location_condition. If multiple objects match the condition, then one is chosen. If no objects match the condition, then nothing is done.
Moves an UniverseObject to a location as though it was moving in orbit of some object or position on the map. Sign of speed indicates CCW / CW rotation.
Moves an UniverseObject a specified distance towards some object or position on the map.
Sets the route of the target fleet to move to an UniverseObject that matches the condition location_condition. If multiple objects match the condition, then one is chosen. If no objects match the condition, then nothing is done.
Sets aggression level of the target object.
Causes the owner empire of the target object to win the game. If the target object has multiple owners, nothing is done.
Sets whether an empire has researched at tech, and how much research progress towards that tech has been completed.
Generates a sitrep message for the empire with id recipient_empire_id. The message text is the user string specified in message_string with string substitutions into the message text as specified in message_parameters which are substituted as string parameters %1%, %2%, %3%, etc. in the order they are specified. Extra parameters beyond those needed by message_string are ignored, and missing parameters are left as blank text.
Applies an overlay texture to Systems.
Applies a texture to Planets.
Sets visibility of an object for an empire, independent of standard visibility mechanics.
Executes a set of effects if an execution-time condition is met, or an alterative set of effects if the condition is not met.
Member Typedef Documentation
typedef std::map<int, std::map<MeterType, std::vector<AccountingInfo> > > Effect::AccountingMap
Effect accounting information for all meters of all objects that are acted on by effects.
typedef std::map<int, std::map<MeterType, std::vector<AccountingInfo> > > Effect::AccountingMap
typedef std::map<int, std::map<MeterType, double> > Effect::DiscrepancyMap
typedef std::map<int, std::map<MeterType, double> > Effect::DiscrepancyMap
Discrepancy between meter's value at start of turn, and the value that this client calculate that the meter should have with the knowledge available -> the unknown factor affecting the meter. This is used when generating effect accounting, in the case where the expected and actual meter values don't match.
typedef std::vector<std::pair<SourcedEffectsGroup, TargetsAndCause> > Effect::TargetsCauses
typedef std::vector<std::pair<SourcedEffectsGroup, TargetsAndCause> > Effect::TargetsCauses
Map from (effects group and source object) to target set of for that effects group with that source object. A multimap is used so that a single source object can have multiple instances of the same effectsgroup. This is useful when a Ship has multiple copies of the same effects group due to having multiple copies of the same ship part in its design.
typedef std::vector<TemporaryPtr<UniverseObject> > Effect::TargetSet
typedef std::vector<TemporaryPtr<UniverseObject> > Effect::TargetSet
Constructor & Destructor Documentation
virtual Effect::~EffectsGroup () virtual
virtual Effect::~EffectBase () virtual
virtual Effect::~SetMeter () virtual
virtual Effect::~SetShipPartMeter () virtual
virtual Effect::~SetEmpireMeter () virtual
virtual Effect::~SetEmpireStockpile () virtual
virtual Effect::~SetEmpireCapital () virtual
virtual Effect::~SetPlanetType () virtual
virtual Effect::~SetPlanetSize () virtual
virtual Effect::~SetSpecies () virtual
virtual Effect::~SetOwner () virtual
virtual Effect::~SetSpeciesEmpireOpinion () virtual
virtual Effect::~SetSpeciesSpeciesOpinion () virtual
virtual Effect::~CreatePlanet () virtual
virtual Effect::~CreateBuilding () virtual
virtual Effect::~CreateShip () virtual
virtual Effect::~CreateField () virtual
virtual Effect::~CreateSystem () virtual
Effect::~AddSpecial ()
Effect::~RemoveSpecial ()
virtual Effect::~AddStarlanes () virtual
virtual Effect::~RemoveStarlanes () virtual
virtual Effect::~SetStarType () virtual
virtual Effect::~MoveTo () virtual
virtual Effect::~MoveInOrbit () virtual
virtual Effect::~MoveTowards () virtual
virtual Effect::~SetDestination () virtual
virtual Effect::~SetEmpireTechProgress () virtual
virtual Effect::~GiveEmpireTech () virtual
virtual Effect::~GenerateSitRepMessage () virtual
virtual Effect::~SetOverlayTexture () virtual
virtual Effect::~SetVisibility () virtual
Member Function Documentation
const std::string& Effect::AccountingLabel () const inline
Condition::ConditionBase* Effect::Activation () const inline
Effect::AddSpecial (const std::string & name, float capacity = 1.0f) explicit
Referenced by TechTreeWnd::LayoutPanel::TechPanel::Update().
Effect::AddSpecial (ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< double > * capacity = 0) explicit
Effect::AddStarlanes (Condition::ConditionBase * other_lane_endpoint_condition) explicit
EmpireAffiliationType Effect::Affiliation () const inline
EmpireAffiliationType Effect::Affiliation () const inline
std::string Effect::AutoGeneratedDescription () const
Referenced by AutoGeneratedDescription().
Effect::Conditional (Condition::ConditionBase * target_condition, const std::vector< EffectBase * > & true_effects, const std::vector< EffectBase * > & false_effects)
Effect::CreateBuilding (ValueRef::ValueRefBase< std::string > * building_type_name, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >()) explicit
Effect::CreateField (ValueRef::ValueRefBase< std::string > * field_type_name, ValueRef::ValueRefBase< double > * size = 0, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >()) explicit
Effect::CreateField (ValueRef::ValueRefBase< std::string > * field_type_name, ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< double > * size = 0, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >())
Effect::CreatePlanet (ValueRef::ValueRefBase< PlanetType > * type, ValueRef::ValueRefBase< PlanetSize > * size, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >())
Effect::CreateShip (ValueRef::ValueRefBase< std::string > * predefined_ship_design_name, ValueRef::ValueRefBase< int > * empire_id = 0, ValueRef::ValueRefBase< std::string > * species_name = 0, ValueRef::ValueRefBase< std::string > * ship_name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >()) explicit
Effect::CreateShip (ValueRef::ValueRefBase< int > * ship_design_id, ValueRef::ValueRefBase< int > * empire_id = 0, ValueRef::ValueRefBase< std::string > * species_name = 0, ValueRef::ValueRefBase< std::string > * ship_name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >()) explicit
Effect::CreateSystem (ValueRef::ValueRefBase< ::StarType > * type, ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >())
Effect::CreateSystem (ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< Effect::EffectBase * > & effects_to_apply_after = std::vector< Effect::EffectBase * >())
virtual std::string Effect::Description () const pure virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
virtual std::string Effect::Description () const virtual
Effect::Destroy ()
std::string Effect::Dump () const
virtual std::string Effect::Dump () const pure virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
virtual std::string Effect::Dump () const virtual
Effect::EffectsGroup (Condition::ConditionBase * scope, Condition::ConditionBase * activation, const std::vector< EffectBase * > & effects, const std::string & accounting_label = "", const std::string & stacking_group = "", int priority = 0, std::string description = "") inline
Referenced by Universe::ExecuteEffects(), anonymous_namespace{Field.cpp}::IncreaseMeter(), and anonymous_namespace{ShipDesign.cpp}::IncreaseMeter().
const std::vector<EffectBase*>& Effect::EffectsList () const inline
ValueRef::ValueRefBase<int>* Effect::EmpireID () const inline
void Effect::Execute (const Effect::TargetsCauses & targets_causes, AccountingMap * accounting_map = 0, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const
execute all effects in group
virtual void Effect::Execute (const ScriptingContext & context) const pure virtual
virtual void Effect::Execute (const ScriptingContext & context, const TargetSet & targets) const virtual
virtual void Effect::Execute (const Effect::TargetsCauses & targets_causes, bool stacking, AccountingMap * accounting_map = 0, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context, const TargetSet & targets) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context, const TargetSet & targets) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
virtual void Effect::Execute (const ScriptingContext & context) const virtual
Effect::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, ValueRef::ValueRefBase< int > * recipient_empire_id, EmpireAffiliationType affiliation, const std::string label = "", bool stringtable_lookup = true)
Effect::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, EmpireAffiliationType affiliation, Condition::ConditionBase * condition = 0, const std::string label = "", bool stringtable_lookup = true)
Effect::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, EmpireAffiliationType affiliation, const std::string & label = "", bool stringtable_lookup = true)
Condition::ConditionBase* Effect::GetCondition () const inline
const std::string& Effect::GetDescription () const
MeterType Effect::GetMeterType () const inline
MeterType Effect::GetMeterType () const inline
const ValueRef::ValueRefBase<std::string>* Effect::GetPartName () const inline
const ValueRef::ValueRefBase<std::string>* Effect::GetSpecialName () const inline
void Effect::GetTargetSet (int source_id, TargetSet & targets) const
void Effect::GetTargetSet (int source_id, TargetSet & targets, const TargetSet & potential_targets) const
void Effect::GetTargetSet (int source_id, TargetSet & targets, TargetSet & potential_targets) const
WARNING: this GetTargetSet version will modify potential_targets. in particular, it will move detected targets from potential_targets to targets. Cast the second parameter to const TargetSet& in order to leave potential_targets unchanged.
Visibility Effect::GetVisibility () const inline
Effect::GiveEmpireTech (ValueRef::ValueRefBase< std::string > * tech_name, ValueRef::ValueRefBase< int > * empire_id = 0) explicit
const std::string& Effect::Icon () const inline
const std::vector<std::pair<std::string, ValueRef::ValueRefBase<std::string>*> >& Effect::MessageParameters () const inline
const std::string& Effect::MessageString () const inline
Effect::MoveInOrbit (ValueRef::ValueRefBase< double > * speed, Condition::ConditionBase * focal_point_condition)
Effect::MoveInOrbit (ValueRef::ValueRefBase< double > * speed, ValueRef::ValueRefBase< double > * focus_x = 0, ValueRef::ValueRefBase< double > * focus_y = 0)
Effect::MoveTo (Condition::ConditionBase * location_condition) explicit
Effect::MoveTowards (ValueRef::ValueRefBase< double > * speed, Condition::ConditionBase * dest_condition)
Effect::MoveTowards (ValueRef::ValueRefBase< double > * speed, ValueRef::ValueRefBase< double > * dest_x = 0, ValueRef::ValueRefBase< double > * dest_y = 0)
int Effect::Priority () const inline
ValueRef::ValueRefBase<int>* Effect::RecipientID () const inline
Effect::RemoveSpecial (const std::string & name) explicit
Effect::RemoveSpecial (ValueRef::ValueRefBase< std::string > * name) explicit
Effect::RemoveStarlanes (Condition::ConditionBase * other_lane_endpoint_condition) explicit
Condition::ConditionBase* Effect::Scope () const inline
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Effect::serialize (Archive & ar, const unsigned int version) private
Effect::SetAggression (bool aggressive) explicit
Effect::SetDestination (Condition::ConditionBase * location_condition) explicit
Effect::SetEmpireCapital () explicit
Effect::SetEmpireCapital (ValueRef::ValueRefBase< int > * empire_id) explicit
Effect::SetEmpireMeter (const std::string & meter, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireMeter (ValueRef::ValueRefBase< int > * empire_id, const std::string & meter, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireStockpile (ResourceType stockpile, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireStockpile (ValueRef::ValueRefBase< int > * empire_id, ResourceType stockpile, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireTechProgress (ValueRef::ValueRefBase< std::string > * tech_name, ValueRef::ValueRefBase< double > * research_progress)
Effect::SetEmpireTechProgress (ValueRef::ValueRefBase< std::string > * tech_name, ValueRef::ValueRefBase< double > * research_progress, ValueRef::ValueRefBase< int > * empire_id)
Effect::SetMeter (MeterType meter, ValueRef::ValueRefBase< double > * value)
Referenced by anonymous_namespace{Field.cpp}::IncreaseMeter(), anonymous_namespace{ShipDesign.cpp}::IncreaseMeter(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
Effect::SetOverlayTexture (const std::string & texture, ValueRef::ValueRefBase< double > * size)
Effect::SetOwner (ValueRef::ValueRefBase< int > * empire_id) explicit
Effect::SetPlanetSize (ValueRef::ValueRefBase< PlanetSize > * size) explicit
Effect::SetPlanetType (ValueRef::ValueRefBase< PlanetType > * type) explicit
Effect::SetShipPartMeter (MeterType meter_type, ValueRef::ValueRefBase< std::string > * part_name, ValueRef::ValueRefBase< double > * value)
Affects the meter_type meter that belongs to part(s) named part_name.
Referenced by anonymous_namespace{ShipDesign.cpp}::IncreaseMeter(), and TechTreeWnd::LayoutPanel::TechPanel::Update().
Effect::SetSpecies (ValueRef::ValueRefBase< std::string > * species) explicit
Effect::SetSpeciesEmpireOpinion (ValueRef::ValueRefBase< std::string > * species_name, ValueRef::ValueRefBase< int > * empire_id, ValueRef::ValueRefBase< double > * opinion)
Effect::SetSpeciesSpeciesOpinion (ValueRef::ValueRefBase< std::string > * opinionated_species_name, ValueRef::ValueRefBase< std::string > * rated_species_name, ValueRef::ValueRefBase< double > * opinion)
Effect::SetStarType (ValueRef::ValueRefBase< StarType > * type) explicit
Effect::SetTexture (const std::string & texture) explicit
void Effect::SetTopLevelContent (const std::string & content_name)
virtual void Effect::SetTopLevelContent (const std::string & content_name) pure virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
virtual void Effect::SetTopLevelContent (const std::string & content_name) virtual
Effect::SetVisibility (Visibility vis, EmpireAffiliationType affiliation, ValueRef::ValueRefBase< int > * empire_id = 0)
const std::string& Effect::StackingGroup () const inline
Effect::Victory (const std::string & reason_string) explicit
Friends And Related Function Documentation
boost::serialization::access friend
Member Data Documentation
std::string Effect::m_accounting_label protected
Condition::ConditionBase* Effect::m_activation protected
EmpireAffiliationType Effect::m_affiliation private
bool Effect::m_aggressive private
ValueRef::ValueRefBase<std::string>* Effect::m_building_type_name private
ValueRef::ValueRefBase<double>* Effect::m_capacity private
Condition::ConditionBase* Effect::m_condition private
std::string Effect::m_description protected
ValueRef::ValueRefBase<int>* Effect::m_design_id private
ValueRef::ValueRefBase<std::string>* Effect::m_design_name private
Condition::ConditionBase* Effect::m_dest_condition private
ValueRef::ValueRefBase<double>* Effect::m_dest_x private
ValueRef::ValueRefBase<double>* Effect::m_dest_y private
std::vector<EffectBase*> Effect::m_effects protected
std::vector< Effect::EffectBase * > Effect::m_effects_to_apply_after private
ValueRef::ValueRefBase< int > * Effect::m_empire_id private
std::vector<EffectBase*> Effect::m_false_effects private
ValueRef::ValueRefBase<std::string>* Effect::m_field_type_name private
Condition::ConditionBase* Effect::m_focal_point_condition private
ValueRef::ValueRefBase<double>* Effect::m_focus_x private
ValueRef::ValueRefBase<double>* Effect::m_focus_y private
std::string Effect::m_icon private
std::string Effect::m_label private
Condition::ConditionBase * Effect::m_location_condition private
std::vector<std::pair<std::string, ValueRef::ValueRefBase<std::string>*> > Effect::m_message_parameters private
std::string Effect::m_message_string private
MeterType Effect::m_meter private
std::string Effect::m_meter private
ValueRef::ValueRefBase< std::string > * Effect::m_name private
ValueRef::ValueRefBase< double > * Effect::m_opinion private
ValueRef::ValueRefBase<std::string>* Effect::m_opinionated_species_name private
Condition::ConditionBase * Effect::m_other_lane_endpoint_condition private
ValueRef::ValueRefBase<std::string>* Effect::m_part_name private
int Effect::m_priority protected
ValueRef::ValueRefBase<std::string>* Effect::m_rated_species_name private
std::string Effect::m_reason_string private
ValueRef::ValueRefBase<int>* Effect::m_recipient_empire_id private
ValueRef::ValueRefBase<double>* Effect::m_research_progress private
Condition::ConditionBase* Effect::m_scope protected
ValueRef::ValueRefBase< double > * Effect::m_size private
ValueRef::ValueRefBase<double>* Effect::m_size private
ValueRef::ValueRefBase< std::string > * Effect::m_species_name private
ValueRef::ValueRefBase< double > * Effect::m_speed private
std::string Effect::m_stacking_group protected
ResourceType Effect::m_stockpile private
bool Effect::m_stringtable_lookup private
Condition::ConditionBase* Effect::m_target_condition private
ValueRef::ValueRefBase< std::string > * Effect::m_tech_name private
std::string Effect::m_texture private
std::vector<EffectBase*> Effect::m_true_effects private
ValueRef::ValueRefBase< PlanetType > * Effect::m_type private
ValueRef::ValueRefBase< ::StarType>* Effect::m_type private
ValueRef::ValueRefBase<StarType>* Effect::m_type private
ValueRef::ValueRefBase< double > * Effect::m_value private
Visibility Effect::m_vis private
ValueRef::ValueRefBase< double > * Effect::m_x private
ValueRef::ValueRefBase< double > * Effect::m_y private
The documentation for this class was generated from the following files:
Effect.h
EffectAccounting.h
Universe.h