FreeOrion: Effect::RemoveSpecial Class Reference
Effect::RemoveSpecial Class Reference
#include <Effect.h>
Public Member Functions
RemoveSpecial (const std::string &name)
RemoveSpecial (ValueRef::ValueRefBase< std::string > *name)
~RemoveSpecial ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase
< std::string > * m_name
Friends
class boost::serialization::access
Detailed Description
Removes the Special with the name name to the target object. This has no effect if no such Special was already attached to the target object.
Constructor & Destructor Documentation
Effect::RemoveSpecial::RemoveSpecial (const std::string & name) explicit
Effect::RemoveSpecial::RemoveSpecial (ValueRef::ValueRefBase< std::string > * name) explicit
Effect::RemoveSpecial::~RemoveSpecial ()
References m_name.
Member Function Documentation
std::string Effect::RemoveSpecial::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_name.
void Effect::RemoveSpecial::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), m_name, and UniverseObject::RemoveSpecial().
template<class Archive > void Effect::RemoveSpecial::serialize (Archive & ar, const unsigned int version) private
References m_name.
void Effect::RemoveSpecial::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_name, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<std::string>* Effect::RemoveSpecial::m_name private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~RemoveSpecial().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp