FreeOrion: FleetsListBox Class Reference
FleetsListBox Class Reference
Public Member Functions
FleetsListBox (bool order_issuing_enabled)
virtual void AcceptDrops (const GG::Pt &pt, const std::vector< GG::Wnd * > &wnds, GG::Flags< GG::ModKey > mod_keys)
virtual void DragDropHere (const GG::Pt &pt, std::map< const GG::Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys)
virtual void DragDropLeave ()
void EnableOrderIssuing (bool enable)
GG::Pt ListRowSize () const
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Public Member Functions inherited from CUIListBox
CUIListBox (void)
basic ctor
virtual void Render ()
Protected Member Functions
virtual void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const
Private Member Functions
void ClearHighlighting ()
void HighlightRow (iterator row_it)
void InitRowSizes ()
Private Attributes
iterator m_highlighted_row_it
bool m_order_issuing_enabled
Detailed Description
A CUIListBox subclass used to list all the fleets, and handle drag-and-drop operations on them, in FleetWnd.
Constructor & Destructor Documentation
FleetsListBox::FleetsListBox (bool order_issuing_enabled) inline
References InitRowSizes().
Member Function Documentation
virtual void FleetsListBox::AcceptDrops (const GG::Pt & pt, const std::vector< GG::Wnd * > & wnds, GG::Flags< GG::ModKey > mod_keys) inline virtual
References anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), DebugLogger, ClientApp::EmpireID(), Fleet::Empty(), ErrorLogger, anonymous_namespace{FleetWnd.cpp}::FLEET_DROP_TYPE_STRING, Ship::FleetID(), HumanClientApp::GetApp(), GetFleet(), GetShip(), UniverseObject::ID(), OrderSet::IssueOrder(), m_order_issuing_enabled, ClientApp::Orders(), anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING, and Fleet::ShipIDs().
void FleetsListBox::ClearHighlighting () inline private
References ErrorLogger, m_highlighted_row_it, and FleetDataPanel::Select().
Referenced by DragDropLeave().
virtual void FleetsListBox::DragDropHere (const GG::Pt & pt, std::map< const GG::Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) inline virtual
References DropsAcceptable(), anonymous_namespace{FleetWnd.cpp}::FLEET_DROP_TYPE_STRING, GetFleet(), GetShip(), HighlightRow(), m_order_issuing_enabled, FleetDataPanel::Selected(), anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING, anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), and anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer().
virtual void FleetsListBox::DragDropLeave () inline virtual
References ClearHighlighting().
virtual void FleetsListBox::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const inline protected virtual
References ErrorLogger, anonymous_namespace{FleetWnd.cpp}::FLEET_DROP_TYPE_STRING, GetFleet(), GetShip(), if(), m_order_issuing_enabled, anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING, anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), and anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer().
Referenced by DragDropHere().
void FleetsListBox::EnableOrderIssuing (bool enable) inline
References m_order_issuing_enabled.
Referenced by FleetWnd::EnableOrderIssuing().
void FleetsListBox::HighlightRow (iterator row_it) inline private
References m_highlighted_row_it, FleetDataPanel::Select(), and FleetDataPanel::Selected().
Referenced by DragDropHere().
void FleetsListBox::InitRowSizes () inline private
Referenced by FleetsListBox().
GG::Pt FleetsListBox::ListRowSize () const inline
References anonymous_namespace{FleetWnd.cpp}::ListRowHeight(), and ClientUI::ScrollWidth().
Referenced by FleetWnd::AddFleet(), FleetWnd::DoLayout(), and SizeMove().
virtual void FleetsListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References ListRowSize().
Referenced by FleetWnd::DoLayout().
Member Data Documentation
iterator FleetsListBox::m_highlighted_row_it private
Referenced by ClearHighlighting(), and HighlightRow().
bool FleetsListBox::m_order_issuing_enabled private
Referenced by AcceptDrops(), DragDropHere(), DropsAcceptable(), and EnableOrderIssuing().
The documentation for this class was generated from the following file:
FleetWnd.cpp