FreeOrion: anonymous_namespace{SpeciesParser.cpp}::rules Struct Reference
anonymous_namespace{SpeciesParser.cpp}::rules Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::vector
< boost::shared_ptr
< Effect::EffectsGroup >
> &), parse::skipper_type > effects_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
std::pair< PlanetType,
PlanetEnvironment >
), qi::locals< PlanetType >
, parse::skipper_type > environment_map_element_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
std::map< PlanetType,
PlanetEnvironment >
), parse::skipper_type > environment_map_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< PlanetType,
PlanetEnvironment >
&), parse::skipper_type > environments_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::vector
< FocusType >
&), parse::skipper_type > foci_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
FocusType(), qi::locals
< std::string, std::string,
Condition::ConditionBase * >
, parse::skipper_type > focus_type_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
SpeciesParams(), qi::locals
< bool, bool, bool, bool >
, parse::skipper_type > species_params_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, Species * >
&), qi::locals
< SpeciesStrings,
SpeciesParams, std::set
< std::string >, std::vector
< FocusType >, std::vector
< boost::shared_ptr
< Effect::EffectsGroup >
>, std::map< PlanetType,
PlanetEnvironment >
, std::string >
, parse::skipper_type > species_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
SpeciesStrings(), qi::locals
< std::string, std::string,
std::string >
, parse::skipper_type > species_strings_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, Species * >
&), parse::skipper_type > start_rule
Public Member Functions
rules ()
Public Attributes
effects_rule effects
environment_map_rule environment_map
environment_map_element_rule environment_map_element
environments_rule environments
foci_rule foci
focus_type_rule focus_type
species_rule species
species_params_rule species_params
species_strings_rule species_strings
start_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<boost::shared_ptr<Effect::EffectsGroup> >&), parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::effects_rule
typedef boost::spirit::qi::rule< parse::token_iterator, std::pair<PlanetType, PlanetEnvironment>), qi::locals<PlanetType>, parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::environment_map_element_rule
typedef boost::spirit::qi::rule< parse::token_iterator, std::map<PlanetType, PlanetEnvironment>), parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::environment_map_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<PlanetType, PlanetEnvironment>&), parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::environments_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<FocusType>&), parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::foci_rule
typedef boost::spirit::qi::rule< parse::token_iterator, FocusType (), qi::locals< std::string, std::string, Condition::ConditionBase* >, parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::focus_type_rule
typedef boost::spirit::qi::rule< parse::token_iterator, SpeciesParams (), qi::locals< bool, bool, bool, bool >, parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::species_params_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, Species*>&), qi::locals< SpeciesStrings, SpeciesParams, std::set<std::string>, std::vector<FocusType>, std::vector<boost::shared_ptr<Effect::EffectsGroup> >, std::map<PlanetType, PlanetEnvironment>, std::string >, parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::species_rule
typedef boost::spirit::qi::rule< parse::token_iterator, SpeciesStrings (), qi::locals< std::string, std::string, std::string >, parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::species_strings_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, Species*>&), parse::skipper_type > anonymous_namespace{SpeciesParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{SpeciesParser.cpp}::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_1, anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::detail::effects_group_parser(), parse::enum_parser< PlanetEnvironment >(), parse::enum_parser< PlanetType >(), anonymous_namespace{BuildingsParser.cpp}::insert, anonymous_namespace{SpeciesParser.cpp}::insert_species, parse::lexer::instance(), parse::label(), parse::report_error, parse::species(), parse::lexer::string, and parse::detail::tags_parser().
Member Data Documentation
effects_rule anonymous_namespace{SpeciesParser.cpp}::rules::effects
environment_map_rule anonymous_namespace{SpeciesParser.cpp}::rules::environment_map
environment_map_element_rule anonymous_namespace{SpeciesParser.cpp}::rules::environment_map_element
environments_rule anonymous_namespace{SpeciesParser.cpp}::rules::environments
foci_rule anonymous_namespace{SpeciesParser.cpp}::rules::foci
focus_type_rule anonymous_namespace{SpeciesParser.cpp}::rules::focus_type
species_rule anonymous_namespace{SpeciesParser.cpp}::rules::species
species_params_rule anonymous_namespace{SpeciesParser.cpp}::rules::species_params
species_strings_rule anonymous_namespace{SpeciesParser.cpp}::rules::species_strings
start_rule anonymous_namespace{SpeciesParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
SpeciesParser.cpp