FreeOrion: TemporaryPtr< T > Class Template Reference
TemporaryPtr< T > Class Template Reference
#include <Serialize.h>
Public Member Functions
Accessors
void reset ()
T * get () const
operator bool () const
T * operator-> () const
T & operator* () const
Private Member Functions
operator int () const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
boost::shared_ptr< T > m_ptr
Friends
template<class Y >
class TemporaryPtr
template<class Y , class R >
TemporaryPtr< Y > boost::const_pointer_cast (TemporaryPtr< R > const &item)
template<class Y , class R >
TemporaryPtr< Y > boost::dynamic_pointer_cast (TemporaryPtr< R > const &item)
template<class Y , class R >
TemporaryPtr< Y > boost::reinterpret_pointer_cast (TemporaryPtr< R > const &item)
class boost::serialization::access
template<class Y , class R >
TemporaryPtr< Y > boost::static_pointer_cast (TemporaryPtr< R > const &item)
template<class Y >
class EnableTemporaryFromThis
class ObjectMap
template<class Y , class R >
bool operator< (const TemporaryPtr< Y > &first, const TemporaryPtr< R > &second)
template<class Y , class R >
bool operator< (const TemporaryPtr< Y > &first, R *second)
template<class Y , class R >
bool operator< (Y *first, const TemporaryPtr< R > &second)
template<class Y , class R >
bool operator== (const TemporaryPtr< Y > &first, const TemporaryPtr< R > &second)
template<class Y , class R >
bool operator== (const TemporaryPtr< Y > &first, R *second)
Structors
TemporaryPtr ()
template<class Y >
TemporaryPtr (const TemporaryPtr< Y > &rhs)
template<class Y >
TemporaryPtr (EnableTemporaryFromThis< Y > *rhs)
template<class Y >
TemporaryPtr (const EnableTemporaryFromThis< Y > *rhs)
template<class Y >
TemporaryPtr< T > & operator= (const TemporaryPtr< Y > &rhs)
template<class Y >
TemporaryPtr (const boost::shared_ptr< Y > &rhs)
template<class Y >
TemporaryPtr (const boost::weak_ptr< Y > &rhs)
template<class P >
TemporaryPtr< T > & internal_assign (const P &rhs)
Constructor & Destructor Documentation
template<class T> TemporaryPtr< T >::TemporaryPtr () inline
template<class T> template<class Y > TemporaryPtr< T >::TemporaryPtr (const TemporaryPtr< Y > & rhs) inline
template<class T> template<class Y > TemporaryPtr< T >::TemporaryPtr (EnableTemporaryFromThis< Y > * rhs) inline
template<class T> template<class Y > TemporaryPtr< T >::TemporaryPtr (const EnableTemporaryFromThis< Y > * rhs) inline
template<class T> template<class Y > TemporaryPtr< T >::TemporaryPtr (const boost::shared_ptr< Y > & rhs) inline explicit private
template<class T> template<class Y > TemporaryPtr< T >::TemporaryPtr (const boost::weak_ptr< Y > & rhs) inline explicit private
Member Function Documentation
template<class T> T* TemporaryPtr< T >::get () const
Referenced by boost::hash< TemporaryPtr< const Y > >::operator()().
template<class T> template<class P > TemporaryPtr<T>& TemporaryPtr< T >::internal_assign (const P & rhs) private
Referenced by TemporaryPtr< const T >::operator=(), TemporaryPtr< const T >::reset(), and TemporaryPtr< const T >::TemporaryPtr().
template<class T> TemporaryPtr< T >::operator bool () const inline
template<class T> TemporaryPtr< T >::operator int () const private
template<class T> T& TemporaryPtr< T >::operator* () const inline
template<class T> T* TemporaryPtr< T >::operator-> () const inline
template<class T> template<class Y > TemporaryPtr<T>& TemporaryPtr< T >::operator= (const TemporaryPtr< Y > & rhs) inline
template<class T> void TemporaryPtr< T >::reset () inline
template<class T> template<class Archive > void TemporaryPtr< T >::serialize (Archive & ar, const unsigned int version) inline private
Friends And Related Function Documentation
template<class T> template<class Y > friend class TemporaryPtr friend
template<class T> template<class Y , class R > TemporaryPtr<Y> boost::const_pointer_cast (TemporaryPtr< R > const & item) friend
template<class T> template<class Y , class R > TemporaryPtr<Y> boost::dynamic_pointer_cast (TemporaryPtr< R > const & item) friend
template<class T> template<class Y , class R > TemporaryPtr<Y> boost::reinterpret_pointer_cast (TemporaryPtr< R > const & item) friend
template<class T> friend class boost::serialization::access friend
template<class T> template<class Y , class R > TemporaryPtr<Y> boost::static_pointer_cast (TemporaryPtr< R > const & item) friend
template<class T> template<class Y > friend class EnableTemporaryFromThis friend
template<class T> friend class ObjectMap friend
template<class T> template<class Y , class R > bool operator< (const TemporaryPtr< Y > & first, const TemporaryPtr< R > & second) friend
template<class T> template<class Y , class R > bool operator< (const TemporaryPtr< Y > & first, R * second) friend
template<class T> template<class Y , class R > bool operator< (Y * first, const TemporaryPtr< R > & second) friend
template<class T> template<class Y , class R > bool operator== (const TemporaryPtr< Y > & first, const TemporaryPtr< R > & second) friend
template<class T> template<class Y , class R > bool operator== (const TemporaryPtr< Y > & first, R * second) friend
Member Data Documentation
template<class T> boost::shared_ptr<T> TemporaryPtr< T >::m_ptr private
Referenced by ObjectMap::Insert(), TemporaryPtr< const T >::operator=(), TemporaryPtr< const T >::serialize(), and TemporaryPtr< const T >::TemporaryPtr().
The documentation for this class was generated from the following files:
ClientUI.h
TemporaryPtr.h