FreeOrion: BasesListBox::SavedDesignPanel Class Reference
BasesListBox::SavedDesignPanel Class Reference
Public Member Functions
SavedDesignPanel (GG::X w, GG::Y h, const std::string &saved_design_name)
void Render () override
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Private Attributes
GG::StaticGraphic * m_graphic
GG::Label * m_name
Constructor & Destructor Documentation
BasesListBox::SavedDesignPanel::SavedDesignPanel (GG::X w, GG::Y h, const std::string & saved_design_name)
References anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::GetDesign(), anonymous_namespace{DesignWnd.cpp}::GetSavedDesignsManager(), ShipDesign::Hull(), ClientUI::HullIcon(), m_graphic, m_name, and ShipDesign::Name().
Member Function Documentation
void BasesListBox::SavedDesignPanel::Render () inline override
void BasesListBox::SavedDesignPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References m_graphic, and m_name.
Member Data Documentation
GG::StaticGraphic* BasesListBox::SavedDesignPanel::m_graphic private
Referenced by SavedDesignPanel(), and SizeMove().
GG::Label* BasesListBox::SavedDesignPanel::m_name private
Referenced by SavedDesignPanel(), and SizeMove().
The documentation for this class was generated from the following file:
DesignWnd.cpp