FreeOrion: SaveFileListBox Class Reference
SaveFileListBox Class Reference
Public Member Functions
SaveFileListBox ()
bool HasFile (const std::string &filename)
GG::Pt ListRowSize () const
void LoadDirectories (const fs::path &path)
void LoadSaveGamePreviews (const fs::path &path, const std::string &extension)
void LoadSaveGamePreviews (const std::vector< FullPreview > &previews)
void RefreshRowSizes ()
void ResetColHeaders ()
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Public Member Functions inherited from CUIListBox
CUIListBox (void)
basic ctor
virtual void Render ()
Static Public Member Functions
static GG::Y ListRowHeight ()
Private Member Functions
std::vector< SaveFileColumn > FilterColumns ()
Static Private Member Functions
static bool DirectoryAwareCmp (const Row &row1, const Row &row2, int column_int)
static bool IsDelimitedWith (const std::string &str, const std::string &begin, const std::string &end)
Private Attributes
std::vector< SaveFileColumn > m_columns
std::vector< SaveFileColumn > m_visible_columns
Constructor & Destructor Documentation
SaveFileListBox::SaveFileListBox () inline
References DirectoryAwareCmp(), FilterColumns(), SaveFileColumn::GetColumns(), m_columns, m_visible_columns, and anonymous_namespace{SaveFileDialog.cpp}::WHEEL_INCREMENT.
Member Function Documentation
static bool SaveFileListBox::DirectoryAwareCmp (const Row & row1, const Row & row2, int column_int) inline static private
We want the timestamps to be sorted in ascending order to get the latest save first, but we want the directories to a) always be first b) be sorted alphabetically, ignoring the PATH_DELIM_BEGIN and PATH_DELIM_END they are wrapped with This custom comparer achieves these goals.
References IsDelimitedWith(), anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_BEGIN, and anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_END.
Referenced by SaveFileListBox().
std::vector<SaveFileColumn> SaveFileListBox::FilterColumns () inline private
References DebugLogger, ErrorLogger, OptionsDB::Get(), GetOptionsDB(), and m_columns.
Referenced by SaveFileListBox().
bool SaveFileListBox::HasFile (const std::string & filename) inline
References SaveFileRow::Filename().
Referenced by SaveFileDialog::CheckChoiceValidity().
static bool SaveFileListBox::IsDelimitedWith (const std::string & str, const std::string & begin, const std::string & end) inline static private
Referenced by DirectoryAwareCmp().
static GG::Y SaveFileListBox::ListRowHeight () inline static
References ClientUI::Pts().
Referenced by ListRowSize().
GG::Pt SaveFileListBox::ListRowSize () const inline
References ListRowHeight().
Referenced by RefreshRowSizes().
void SaveFileListBox::LoadDirectories (const fs::path & path) inline
References DebugLogger, IsValidUTF8(), and PathString().
Referenced by LoadSaveGamePreviews().
void SaveFileListBox::LoadSaveGamePreviews (const fs::path & path, const std::string & extension) inline
Loads preview data on all save files in a directory specidifed by path.
Parameters
[in] path The path of the directory
References LoadDirectories().
Referenced by SaveFileDialog::UpdatePreviewList().
void SaveFileListBox::LoadSaveGamePreviews (const std::vector< FullPreview > & previews) inline
Loads preview data on all save files in a directory specidifed by path.
Parameters
[in] previews The preview data
References OptionsDB::Get(), GetOptionsDB(), m_columns, and m_visible_columns.
void SaveFileListBox::RefreshRowSizes () inline
References SaveFileRow::AdjustColumns(), ListRowSize(), m_visible_columns, and ResetColHeaders().
Referenced by SizeMove(), and SaveFileDialog::UpdatePreviewList().
void SaveFileListBox::ResetColHeaders () inline
References m_visible_columns.
Referenced by RefreshRowSizes(), and SaveFileDialog::UpdatePreviewList().
virtual void SaveFileListBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References RefreshRowSizes().
Member Data Documentation
std::vector<SaveFileColumn> SaveFileListBox::m_columns private
Referenced by FilterColumns(), LoadSaveGamePreviews(), and SaveFileListBox().
std::vector<SaveFileColumn> SaveFileListBox::m_visible_columns private
Referenced by LoadSaveGamePreviews(), RefreshRowSizes(), ResetColHeaders(), and SaveFileListBox().
The documentation for this class was generated from the following file:
SaveFileDialog.cpp