FreeOrion: ParticipantBar Class Reference
ParticipantBar Class Reference
A Bar that shows the health of a single battle participant.
Public Member Functions
ParticipantBar (const ParticipantSummary &participant, const BarSizer &sizer)
bool Alive () const
Tells whether this participant is still alive.
void DoLayout (const GG::X &label_margin)
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseLeave ()
void MoveBottomTo (GG::Pt pt)
Moves the bottom left of the bar to pt.
virtual void Render ()
Private Attributes
GG::Clr m_dead_color
GG::Clr m_health_color
bool m_hovered
const ParticipantSummary & m_participant
const BarSizer & m_sizer
GG::Clr m_wound_color
Detailed Description
A Bar that shows the health of a single battle participant.
Constructor & Destructor Documentation
ParticipantBar::ParticipantBar (const ParticipantSummary & participant, const BarSizer & sizer) inline
References ParticipantSummary::current_health, DoubleToString(), ClientApp::EmpireID(), OptionsDB::Get(), ClientApp::GetApp(), GetOptionsDB(), m_dead_color, m_health_color, m_wound_color, ParticipantSummary::max_health, ObjectMap::Object(), ParticipantSummary::object_id, Objects(), and UniverseObject::PublicName().
Member Function Documentation
bool ParticipantBar::Alive () const inline
Tells whether this participant is still alive.
References ParticipantSummary::current_health, and m_participant.
Referenced by SideBar::DoLayout(), and Render().
void ParticipantBar::DoLayout (const GG::X & label_margin) inline
Resizes the bar to have a width and height based on the current and maximal health of the participant.
References BarSizer::GetBarSize(), m_participant, and m_sizer.
Referenced by SideBar::DoLayout().
virtual void ParticipantBar::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline virtual
References m_hovered.
virtual void ParticipantBar::MouseLeave () inline virtual
References m_hovered.
void ParticipantBar::MoveBottomTo (GG::Pt pt) inline
Moves the bottom left of the bar to pt.
Referenced by SideBar::DoLayout().
virtual void ParticipantBar::Render () inline virtual
References Alive(), ParticipantSummary::current_health, BarSizer::Get(), anonymous_namespace{GraphicalSummary.cpp}::interpolate(), m_dead_color, m_health_color, m_hovered, m_participant, m_sizer, m_wound_color, ParticipantSummary::max_health, and anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEALTH_SMOOTH.
Member Data Documentation
GG::Clr ParticipantBar::m_dead_color private
Referenced by ParticipantBar(), and Render().
GG::Clr ParticipantBar::m_health_color private
Referenced by ParticipantBar(), and Render().
bool ParticipantBar::m_hovered private
Referenced by MouseEnter(), MouseLeave(), and Render().
const ParticipantSummary& ParticipantBar::m_participant private
Referenced by Alive(), DoLayout(), and Render().
const BarSizer& ParticipantBar::m_sizer private
Referenced by DoLayout(), and Render().
GG::Clr ParticipantBar::m_wound_color private
Referenced by ParticipantBar(), and Render().
The documentation for this class was generated from the following file:
GraphicalSummary.cpp