FreeOrion: CUIButton Class Reference
CUIButton Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
CUIButton (const std::string &str)
basic ctor
CUIButton (const std::string &str, GG::Clr background, GG::Clr border)
basic ctor
CUIButton (const GG::SubTexture &unpressed, const GG::SubTexture &pressed, const GG::SubTexture &rollover)
basic ctor
Accessors
virtual GG::Pt MinUsableSize () const
virtual bool InWindow (const GG::Pt &pt) const
Mutators
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void SetCheck (bool b=true)
Protected Member Functions
Mutators control
virtual void RenderPressed ()
virtual void RenderRollover ()
virtual void RenderUnpressed ()
Private Attributes
GG::Clr m_border_color
int m_border_thick
bool m_checked
true when this button in a checked, active state
Detailed Description
a FreeOrion Button control
Constructor & Destructor Documentation
CUIButton::CUIButton (const std::string & str)
basic ctor
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
CUIButton::CUIButton (const std::string & str, GG::Clr background, GG::Clr border)
basic ctor
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
CUIButton::CUIButton (const GG::SubTexture & unpressed, const GG::SubTexture & pressed, const GG::SubTexture & rollover)
basic ctor
References anonymous_namespace{CUIControls.cpp}::PlayButtonClickSound().
Member Function Documentation
bool CUIButton::InWindow (const GG::Pt & pt) const virtual
Reimplemented in SettableInWindowCUIButton.
References anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, and InAngledCornerRect().
Referenced by SettableInWindowCUIButton::InWindow().
GG::Pt CUIButton::MinUsableSize () const virtual
void CUIButton::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
void CUIButton::RenderPressed () protected virtual
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, m_border_color, m_border_thick, and m_checked.
void CUIButton::RenderRollover () protected virtual
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, m_border_color, m_border_thick, and m_checked.
void CUIButton::RenderUnpressed () protected virtual
References AngledCornerRectangle(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, m_border_color, m_border_thick, and m_checked.
void CUIButton::SetCheck (bool b = true)
References m_checked.
Member Data Documentation
GG::Clr CUIButton::m_border_color private
Referenced by RenderPressed(), RenderRollover(), and RenderUnpressed().
int CUIButton::m_border_thick private
Referenced by RenderPressed(), RenderRollover(), and RenderUnpressed().
bool CUIButton::m_checked private
true when this button in a checked, active state
Referenced by RenderPressed(), RenderRollover(), RenderUnpressed(), and SetCheck().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp