FreeOrion: ResourceCenter Class Reference
ResourceCenter Class Reference abstract
#include <ResourceCenter.h>
Public Member Functions
Structors
ResourceCenter ()
default ctor
virtual ~ResourceCenter ()
dtor
ResourceCenter (const ResourceCenter &rhs)
copy ctor
Mutators
void Copy (TemporaryPtr< const ResourceCenter > copied_object, Visibility vis=VIS_FULL_VISIBILITY)
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
void SetFocus (const std::string &focus)
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
void ClearFocus ()
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
void UpdateFocusHistory ()
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
virtual void Reset ()
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
Public Member Functions inherited from EnableTemporaryFromThis< UniverseObject >
EnableTemporaryFromThis ()
TemporaryPtr< UniverseObject > TemporaryFromThis ()
TemporaryPtr< const
UniverseObject > TemporaryFromThis () const
Protected Member Functions
void Init ()
initialization that needs to be called by derived class after derived class is constructed
void ResourceCenterClampMeters ()
float ResourceCenterNextTurnMeterValue (MeterType meter_type) const
returns estimate of the next turn's current values of meters relevant to this ResourceCenter
void ResourceCenterPopGrowthProductionResearchPhase ()
void ResourceCenterResetTargetMaxUnpairedMeters ()
Private Member Functions
virtual void AddMeter (MeterType meter_type)=0
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
virtual const Meter * GetMeter (MeterType type) const =0
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
virtual Meter * GetMeter (MeterType type)=0
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
virtual Visibility GetVisibility (int empire_id) const =0
implementation should return the visibility of this ResourceCenter for the empire with the specified empire_id
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_focus
std::string m_focus_turn_initial
int m_last_turn_focus_changed
int m_last_turn_focus_changed_turn_initial
Friends
class boost::serialization::access
Accessors
boost::signals2::signal< void()> ResourceCenterChangedSignal
const std::string & Focus () const
current focus to which this ResourceCenter is set
int TurnsSinceFocusChange () const
number of turns since focus was last changed.
virtual std::vector< std::string > AvailableFoci () const
focus settings available to this ResourceCenter
virtual const std::string & FocusIcon (const std::string &focus_name) const
icon representing focus with name focus_name for this ResourceCenter
std::string Dump () const
virtual float InitialMeterValue (MeterType type) const =0
implementation should return the initial value of the specified meter type
virtual float CurrentMeterValue (MeterType type) const =0
implementation should return the current value of the specified meter type
virtual float NextTurnCurrentMeterValue (MeterType type) const =0
implementation should return an estimate of the next turn's current value of the specified meter type
Additional Inherited Members
Public Types inherited from EnableTemporaryFromThis< UniverseObject >
typedef
EnableTemporaryFromThis
< UniverseObject > enable_temporary_from_this_type
Detailed Description
The ResourceCenter class is an abstract base class for anything in the FreeOrion gamestate that generates resources (minerals, etc.). Most likely, such an object will also be a subclass of UniverseObject.
Planet is the most obvious class to inherit ResourceCenter, but other classes could be made from it as well (e.g., a trade-ship or mining vessel, or a non-Planet UniverseObject- and PopCenter- derived object of some sort.
Constructor & Destructor Documentation
ResourceCenter::ResourceCenter ()
default ctor
ResourceCenter::~ResourceCenter () virtual
dtor
ResourceCenter::ResourceCenter (const ResourceCenter & rhs)
copy ctor
Member Function Documentation
virtual void ResourceCenter::AddMeter (MeterType meter_type) private pure virtual
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
Implemented in Planet.
Referenced by Init().
std::vector< std::string > ResourceCenter::AvailableFoci () const virtual
focus settings available to this ResourceCenter
Reimplemented in Planet.
Referenced by SidePanel::PlanetPanel::FocusDropListSelectionChangedSlot(), SetFocus(), and FreeOrionPython::WrapUniverseClasses().
void ResourceCenter::ClearFocus ()
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
References CurrentTurn(), m_focus, m_last_turn_focus_changed, and ResourceCenterChangedSignal.
Referenced by Planet::Depopulate(), and SetFocus().
void ResourceCenter::Copy (TemporaryPtr< const ResourceCenter > copied_object, Visibility vis = VIS_FULL_VISIBILITY)
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
References ErrorLogger, m_focus, m_focus_turn_initial, m_last_turn_focus_changed, and m_last_turn_focus_changed_turn_initial.
Referenced by Planet::Copy().
virtual float ResourceCenter::CurrentMeterValue (MeterType type) const pure virtual
implementation should return the current value of the specified meter type
Implemented in Planet.
std::string ResourceCenter::Dump () const
the state changed signal object for this ResourceCenter
References m_focus, and m_last_turn_focus_changed.
Referenced by Planet::Dump(), and SetFocus().
const std::string & ResourceCenter::Focus () const
current focus to which this ResourceCenter is set
References m_focus.
Referenced by Condition::FocusType::Match(), Condition::anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::operator()(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetFocus(), SidePanel::PlanetPanel::Refresh(), and FreeOrionPython::WrapUniverseClasses().
const std::string & ResourceCenter::FocusIcon (const std::string & focus_name) const virtual
icon representing focus with name focus_name for this ResourceCenter
Reimplemented in Planet.
References anonymous_namespace{ResourceCenter.cpp}::EMPTY_STRING.
virtual const Meter* ResourceCenter::GetMeter (MeterType type) const private pure virtual
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
Implemented in Planet.
Referenced by Reset(), ResourceCenterClampMeters(), ResourceCenterNextTurnMeterValue(), ResourceCenterPopGrowthProductionResearchPhase(), and ResourceCenterResetTargetMaxUnpairedMeters().
virtual Meter* ResourceCenter::GetMeter (MeterType type) private pure virtual
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
Implemented in Planet.
virtual Visibility ResourceCenter::GetVisibility (int empire_id) const private pure virtual
implementation should return the visibility of this ResourceCenter for the empire with the specified empire_id
Implemented in Planet.
void ResourceCenter::Init () protected
initialization that needs to be called by derived class after derived class is constructed
References AddMeter(), INVALID_GAME_TURN, m_focus, m_focus_turn_initial, m_last_turn_focus_changed, m_last_turn_focus_changed_turn_initial, METER_CONSTRUCTION, METER_INDUSTRY, METER_RESEARCH, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
Referenced by Planet::Planet().
virtual float ResourceCenter::InitialMeterValue (MeterType type) const pure virtual
implementation should return the initial value of the specified meter type
Implemented in Planet.
Referenced by SystemResourceSummaryBrowseWnd::UpdateProduction().
virtual float ResourceCenter::NextTurnCurrentMeterValue (MeterType type) const pure virtual
implementation should return an estimate of the next turn's current value of the specified meter type
Implemented in Planet.
void ResourceCenter::Reset () virtual
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
Reimplemented in Planet.
References GetMeter(), INVALID_GAME_TURN, m_focus, m_last_turn_focus_changed, METER_CONSTRUCTION, METER_INDUSTRY, METER_RESEARCH, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and Meter::Reset().
Referenced by Planet::Reset().
void ResourceCenter::ResourceCenterClampMeters () protected
References Meter::ClampCurrentToRange(), GetMeter(), METER_CONSTRUCTION, METER_INDUSTRY, METER_RESEARCH, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
Referenced by Planet::ClampMeters().
float ResourceCenter::ResourceCenterNextTurnMeterValue (MeterType meter_type) const protected
returns estimate of the next turn's current values of meters relevant to this ResourceCenter
References Meter::Current(), ErrorLogger, GetMeter(), INVALID_METER_TYPE, METER_CONSTRUCTION, METER_INDUSTRY, METER_RESEARCH, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
Referenced by Planet::NextTurnCurrentMeterValue(), and ResourceCenterPopGrowthProductionResearchPhase().
void ResourceCenter::ResourceCenterPopGrowthProductionResearchPhase () protected
References GetMeter(), METER_CONSTRUCTION, METER_INDUSTRY, METER_RESEARCH, METER_TRADE, ResourceCenterNextTurnMeterValue(), and Meter::SetCurrent().
Referenced by Planet::PopGrowthProductionResearchPhase().
void ResourceCenter::ResourceCenterResetTargetMaxUnpairedMeters () protected
References GetMeter(), METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and Meter::ResetCurrent().
Referenced by Planet::ResetTargetMaxUnpairedMeters().
template<class Archive > void ResourceCenter::serialize (Archive & ar, const unsigned int version) private
References m_focus, m_focus_turn_initial, m_last_turn_focus_changed, and m_last_turn_focus_changed_turn_initial.
void ResourceCenter::SetFocus (const std::string & focus)
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
References AvailableFoci(), ClearFocus(), CurrentTurn(), Dump(), ErrorLogger, m_focus, m_focus_turn_initial, m_last_turn_focus_changed, m_last_turn_focus_changed_turn_initial, and ResourceCenterChangedSignal.
Referenced by Planet::Colonize(), ChangeFocusOrder::ExecuteImpl(), ObjectListWnd::ObjectRightClicked(), and anonymous_namespace{ServerWrapper.cpp}::PlanetSetFocus().
int ResourceCenter::TurnsSinceFocusChange () const
number of turns since focus was last changed.
References CurrentTurn(), INVALID_GAME_TURN, and m_last_turn_focus_changed.
Referenced by FreeOrionPython::WrapUniverseClasses().
void ResourceCenter::UpdateFocusHistory ()
Resets the meters, etc. This should be called when a ResourceCenter is wiped out due to starvation, etc.
References m_focus, m_focus_turn_initial, m_last_turn_focus_changed, and m_last_turn_focus_changed_turn_initial.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::string ResourceCenter::m_focus private
Referenced by ClearFocus(), Copy(), Dump(), Focus(), Init(), Reset(), serialize(), SetFocus(), and UpdateFocusHistory().
std::string ResourceCenter::m_focus_turn_initial private
Referenced by Copy(), Init(), serialize(), SetFocus(), and UpdateFocusHistory().
int ResourceCenter::m_last_turn_focus_changed private
Referenced by ClearFocus(), Copy(), Dump(), Init(), Reset(), serialize(), SetFocus(), TurnsSinceFocusChange(), and UpdateFocusHistory().
int ResourceCenter::m_last_turn_focus_changed_turn_initial private
Referenced by Copy(), Init(), serialize(), SetFocus(), and UpdateFocusHistory().
boost::signals2::signal<void ()> ResourceCenter::ResourceCenterChangedSignal mutable
the state changed signal object for this ResourceCenter
Referenced by ClearFocus(), ObjectPanel::ObjectPanel(), SidePanel::RefreshInPreRender(), and SetFocus().
The documentation for this class was generated from the following files:
ResourceCenter.h
ResourceCenter.cpp