FreeOrion: Fleet Class Reference
Fleet Class Reference
#include <Fleet.h>
Public Member Functions
std::string GenerateFleetName ()
Accessors
virtual UniverseObjectType ObjectType () const
returns set of IDs of ships in fleet.
virtual std::string Dump () const
returns set of IDs of ships in fleet.
const std::set< int > & ShipIDs () const
returns set of IDs of ships in fleet.
virtual int ContainerObjectID () const
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
virtual const std::set< int > & ContainedObjectIDs () const
returns ids of objects directly contained within this object
virtual bool Contains (int object_id) const
returns true if there is an object with id object_id is contained within this UniverseObject
virtual bool ContainedBy (int object_id) const
returns true if there is an object with id object_id that contains this UniverseObject
virtual const std::string & PublicName (int empire_id) const
returns set of IDs of ships in fleet.
const std::list< int > & TravelRoute () const
int OrderedGivenToEmpire () const
returns the ID of the empire this fleet has been ordered given to, or ALL_EMPIRES if this fleet hasn't been ordered given to an empire
bool Aggressive () const
returns set of IDs of ships in fleet.
std::list< MovePathNode > MovePath (const std::list< int > &route, bool flag_blockades=false) const
std::list< MovePathNode > MovePath (bool flag_blockades=false) const
Returns MovePath for fleet's current TravelRoute.
std::pair< int, int > ETA () const
Returns the number of turns which must elapse before the fleet arrives at its current final destination and the turns to the next system, respectively.
std::pair< int, int > ETA (const std::list< MovePathNode > &move_path) const
Returns the number of turns which must elapse before the fleet arrives at the final destination and next system in the spepcified move_path.
float Damage () const
Returns total amount of damage this fleet has, which is the sum of the ships' damage.
float Structure () const
Returns total amount of structure this fleet has, which is the sum of the ships' structure.
float Shields () const
Returns total amount of shields this fleet has, which is the sum of the ships' shields.
float Fuel () const
Returns effective amount of fuel this fleet has, which is the least of the amounts of fuel that the ships have.
float MaxFuel () const
Returns effective maximum amount of fuel this fleet has, which is the least of the max amounts of fuel that the ships can have.
int FinalDestinationID () const
Returns ID of system that this fleet is moving to or INVALID_OBJECT_ID if staying still.
int PreviousSystemID () const
Returns ID of system that this fleet is moving away from as it moves to its destination.
int NextSystemID () const
Returns ID of system that this fleet is moving to next as it moves to its destination.
bool BlockadedAtSystem (int start_system_id, int dest_system_id) const
returns true iff this fleet's movement would be blockaded at system.
float Speed () const
Returns speed of fleet. (Should be equal to speed of slowest ship in fleet, unless in future the calculation of fleet speed changes.)
bool CanChangeDirectionEnRoute () const
Returns true iff this fleet can change its direction while in interstellar space.
bool HasMonsters () const
returns true iff this fleet contains monster ships.
bool HasArmedShips () const
Returns true if there is at least one armed ship in the fleet.
bool HasFighterShips () const
Returns true if there is at least one ship with fighters in the fleet.
bool HasColonyShips () const
Returns true if there is at least one colony ship with nonzero capacity in the fleet.
bool HasOutpostShips () const
Returns true if there is at least one colony ship with zero capacity in the fleet.
bool HasTroopShips () const
Returns true if there is at least one troop ship in the fleet.
bool HasShipsOrderedScrapped () const
Returns true if there is at least one ship ordered scrapped in the fleet.
bool HasShipsWithoutScrapOrders () const
Returns true if there is at least one ship without any scrap orders in the fleet.
int NumShips () const
Returns number of ships in fleet.
bool Empty () const
Returns true if fleet contains no ships, false otherwise.
float ResourceOutput (ResourceType type) const
returns set of IDs of ships in fleet.
bool UnknownRoute () const
bool ArrivedThisTurn () const
int ArrivalStarlane () const
virtual TemporaryPtr
< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const
returns set of IDs of ships in fleet.
Mutators
virtual void Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id=ALL_EMPIRES)
sets this fleet to move through the series of systems in the list, in order
void SetRoute (const std::list< int > &route)
sets this fleet to move through the series of systems in the list, in order
void CalculateRouteTo (int target_system_id)
sets this fleet to move through the series of systems that makes the shortest path from its current location to target_system_id
void SetAggressive (bool aggressive=true)
sets this fleet to be agressive (true) or passive (false)
virtual void MovementPhase ()
void AddShip (int ship_id)
adds the ship to the fleet
void AddShips (const std::vector< int > &ship_ids)
adds the ships to the fleet
void RemoveShip (int ship_id)
removes the ship from the fleet.
void RemoveShips (const std::vector< int > &ship_ids)
removes the ships from the fleet.
void SetNextAndPreviousSystems (int next, int prev)
sets the previous and next systems for this fleet. Useful after moving a moving fleet to a different location, so that it moves along its new local starlanes
void SetArrivalStarlane (int starlane)
sets the arrival starlane, used to clear blockaded status after combat
void ClearArrivalFlag ()
used to clear the m_arrived_this_turn flag, prior to any fleets moving, for accurate blockade tests
void SetGiveToEmpire (int empire_id)
marks fleet to be given to empire
void ClearGiveToEmpire ()
marks fleet not to be given to any empire
virtual void ResetTargetMaxUnpairedMeters ()
sets this fleet to move through the series of systems in the list, in order
Public Member Functions inherited from UniverseObject
void SetID (int id)
sets the ID number of the object to id
void Rename (const std::string &name)
renames this object to name
void Move (double x, double y)
void MoveTo (int object_id)
void MoveTo (TemporaryPtr< UniverseObject > object)
void MoveTo (double x, double y)
std::map< MeterType, Meter > & Meters ()
returns this UniverseObject's meters
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void BackPropagateMeters ()
sets all this UniverseObject's meters' initial values equal to their current values
virtual void SetOwner (int id)
sets the empire that owns this object
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void SetSpecialCapacity (const std::string &name, float capacity)
virtual void ResetPairedActiveMeters ()
virtual void ClampMeters ()
virtual void PopGrowthProductionResearchPhase ()
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const std::string & Name () const
returns the name of this object; some valid objects will have no name
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
bool Unowned () const
returns true iff there are no owners of this object
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
const std::map< std::string,
std::pair< int, float > > & Specials () const
returns the Specials attached to this object
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
emitted when the UniverseObject is altered in any way
virtual std::set< std::string > Tags () const
returns the capacity of the special with name name or 0 if that special is not present
virtual bool HasTag (const std::string &name) const
returns true iff this object has the tag with the indicated name
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
const std::map< MeterType,
Meter > & Meters () const
returns this UniverseObject's meters
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
float CurrentMeterValue (MeterType type) const
returns current value of the specified meter type
float InitialMeterValue (MeterType type) const
returns this turn's initial value for the speicified meter type
virtual float NextTurnCurrentMeterValue (MeterType type) const
returns an estimate of the next turn's current value of the specified meter type
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
int CreationTurn () const
returns game turn on which object was created
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
Public Member Functions inherited from EnableTemporaryFromThis< UniverseObject >
EnableTemporaryFromThis ()
TemporaryPtr< UniverseObject > TemporaryFromThis ()
TemporaryPtr< const
UniverseObject > TemporaryFromThis () const
Static Public Attributes
static const int ETA_NEVER = (1 << 30) - 2
returned by ETA when fleet can't reach destination due to lack of route or inability to move
static const int ETA_OUT_OF_RANGE = (1 << 30) - 1
returned by ETA when fleet can't reach destination due to insufficient fuel capacity and lack of fleet resupply on route
static const int ETA_UNKNOWN = (1 << 30)
returned when ETA can't be determined
Static Public Attributes inherited from UniverseObject
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
void ShortenRouteToEndAtSystem (std::list< int > &travel_route, int last_system)
< removes any systems on the route after the specified system
Private Attributes
bool m_aggressive
should this fleet attack enemies in the same system?
int m_arrival_starlane
bool m_arrived_this_turn
int m_next_system
the next system in the route, if any
int m_ordered_given_to_empire_id
int m_prev_system
the previous system in the route, if any
std::set< int > m_ships
double m_travel_distance
std::list< int > m_travel_route
Friends
class boost::serialization::access
class ObjectMap
class Universe
Structors
template<class T >
void boost::python::detail::value_destroyer (T const volatile *p)
general ctor taking name, position and owner id
template<class T >
void boost::checked_delete (T *x)
general ctor taking name, position and owner id
Fleet ()
general ctor taking name, position and owner id
Fleet (const std::string &name, double x, double y, int owner)
general ctor taking name, position and owner id
~Fleet ()
general ctor taking name, position and owner id
virtual Fleet * Clone (int empire_id=ALL_EMPIRES) const
returns new copy of this Fleet
Additional Inherited Members
Public Types inherited from UniverseObject
typedef
boost::signals2::signal< void(),
blocking_combiner
< boost::signals2::optional_last_value
< void > > > StateChangedSignalType
typedef
StateChangedSignalType::slot_type StateChangedSlotType
Public Types inherited from EnableTemporaryFromThis< UniverseObject >
typedef
EnableTemporaryFromThis
< UniverseObject > enable_temporary_from_this_type
Public Attributes inherited from UniverseObject
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
Protected Member Functions inherited from UniverseObject
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (TemporaryPtr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
used by public UniverseObject::Copy and derived classes' ::Copy methods
void Init ()
adds stealth meter
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
virtual ~UniverseObject ()
Protected Attributes inherited from UniverseObject
std::string m_name
Detailed Description
Encapsulates data for a FreeOrion fleet. Fleets are basically a group of ships that travel together.
Constructor & Destructor Documentation
Fleet::Fleet () inline protected
general ctor taking name, position and owner id
Referenced by Clone().
Fleet::Fleet (const std::string & name, double x, double y, int owner) protected
general ctor taking name, position and owner id
References UniverseObject::Init(), and UniverseObject::SetOwner().
Fleet::~Fleet () inline protected
general ctor taking name, position and owner id
Member Function Documentation
TemporaryPtr< UniverseObject > Fleet::Accept (const UniverseObjectVisitor & visitor) const virtual
returns set of IDs of ships in fleet.
Reimplemented from UniverseObject.
References EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis(), and UniverseObjectVisitor::Visit().
void Fleet::AddShip (int ship_id)
adds the ship to the fleet
References AddShips().
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), and Effect::MoveTo::Execute().
void Fleet::AddShips (const std::vector< int > & ship_ids)
adds the ships to the fleet
References m_ships, and UniverseObject::StateChangedSignal.
Referenced by AddShip(), NewFleetOrder::ExecuteImpl(), and FleetTransferOrder::ExecuteImpl().
bool Fleet::Aggressive () const inline
returns set of IDs of ships in fleet.
Referenced by FleetDataPanel::AggressionToggleButtonPressed(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), CombatInfo::CombatInfo(), FleetWnd::FleetRightClicked(), Condition::Aggressive::Match(), FleetDataPanel::UpdateAggressionToggle(), and FreeOrionPython::WrapUniverseClasses().
int Fleet::ArrivalStarlane () const inline
Has two primary uses: orientation in tactical combat, and determination of starlane blockade restrictions. Returns the ID of the starlane that this fleet arrived on, if it arrived into a blockade which is not yet broken. If in a system and not blockaded, the value is the current system ID. The blockade intent is that you can't break a blockade unless you beat the blockaders (via combat or they retreat).
Referenced by NewFleetOrder::ExecuteImpl(), MapWnd::SetFleetMovementLine(), and MapWnd::SetProjectedFleetMovementLine().
bool Fleet::ArrivedThisTurn () const inline
Returns true iff this fleet arrived at its current System this turn.
bool Fleet::BlockadedAtSystem (int start_system_id, int dest_system_id) const
returns true iff this fleet's movement would be blockaded at system.
If a newly arrived fleet joins a non-blockaded fleet of the same empire (perhaps should include allies?) already at the system, the newly arrived fleet will not be blockaded. Additionally, since fleets are blockade-checked at movement phase and also postcombat, the following tests mean that post-compbat, this fleet will be blockaded iff it was blockaded pre-combat AND there are armed aggressive enemies surviving in system post-combat which can detect this fleet. Fleets arriving at the same time do not blockade each other. Unrestricted lane access (i.e, (fleet->ArrivalStarlane() == system->ID())) is used as a proxy for order of arrival – if an enemy has unrestricted l*ane access and you don't, they must have arrived before you, or be in cahoots with someone who did.
References Meter::Current(), UniverseObject::CurrentMeterValue(), DebugLogger, Empires(), ObjectMap::FindObjects(), System::FleetIDs(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), UniverseObject::GetMeter(), GetSystem(), UniverseObject::ID(), INVALID_OBJECT_ID, m_arrival_starlane, METER_DETECTION, METER_STEALTH, Objects(), UniverseObject::Owner(), ShipIDs(), Empire::SupplyUnobstructedSystems(), UniverseObject::SystemID(), UniverseObject::Unowned(), and Empire::UnrestrictedLaneTravel().
Referenced by MovementPhase(), MovePath(), MapWnd::SetFleetMovementLine(), and MapWnd::SetProjectedFleetMovementLine().
void Fleet::CalculateRouteTo (int target_system_id)
sets this fleet to move through the series of systems that makes the shortest path from its current location to target_system_id
References CanChangeDirectionEnRoute(), DebugLogger, ErrorLogger, GetSystem(), GetUniverse(), GetUniverseObject(), INVALID_OBJECT_ID, m_next_system, m_prev_system, UniverseObject::Owner(), SetRoute(), Universe::ShortestPath(), UniverseObject::SystemID(), UniverseObject::X(), and UniverseObject::Y().
Referenced by Empire::CheckProductionProgress().
bool Fleet::CanChangeDirectionEnRoute () const inline
Returns true iff this fleet can change its direction while in interstellar space.
Referenced by CalculateRouteTo(), SetRoute(), and FreeOrionPython::WrapUniverseClasses().
void Fleet::ClearArrivalFlag () inline
used to clear the m_arrived_this_turn flag, prior to any fleets moving, for accurate blockade tests
Referenced by ServerApp::PreCombatProcessTurns().
void Fleet::ClearGiveToEmpire ()
marks fleet not to be given to any empire
References ALL_EMPIRES, and SetGiveToEmpire().
Fleet * Fleet::Clone (int empire_id = ALL_EMPIRES) const protected virtual
returns new copy of this Fleet
Implements UniverseObject.
References Copy(), Fleet(), Universe::GetObjectVisibilityByEmpire(), GetUniverse(), UniverseObject::ID(), and EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis().
bool Fleet::ContainedBy (int object_id) const virtual
returns true if there is an object with id object_id that contains this UniverseObject
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and UniverseObject::SystemID().
const std::set< int > & Fleet::ContainedObjectIDs () const virtual
returns ids of objects directly contained within this object
Reimplemented from UniverseObject.
References m_ships.
int Fleet::ContainerObjectID () const virtual
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
Reimplemented from UniverseObject.
References UniverseObject::SystemID().
bool Fleet::Contains (int object_id) const virtual
returns true if there is an object with id object_id is contained within this UniverseObject
Reimplemented from UniverseObject.
References INVALID_OBJECT_ID, and m_ships.
void Fleet::Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id = ALL_EMPIRES) virtual
sets this fleet to move through the series of systems in the list, in order
Implements UniverseObject.
References UniverseObject::Copy(), DebugLogger, boost::dynamic_pointer_cast(), ErrorLogger, Universe::GetObjectVisibilityByEmpire(), Universe::GetObjectVisibleSpecialsByEmpire(), GetUniverse(), UniverseObject::ID(), m_aggressive, m_arrival_starlane, m_arrived_this_turn, UniverseObject::m_name, m_next_system, m_ordered_given_to_empire_id, m_prev_system, m_ships, m_travel_distance, m_travel_route, ShortenRouteToEndAtSystem(), Universe::ShortestPath(), UniverseObject::Unowned(), and UniverseObject::VisibleContainedObjectIDs().
Referenced by Clone().
float Fleet::Damage () const
Returns total amount of damage this fleet has, which is the sum of the ships' damage.
References GetShip(), and m_ships.
std::string Fleet::Dump () const virtual
returns set of IDs of ships in fleet.
Reimplemented from UniverseObject.
References UniverseObject::Dump(), FinalDestinationID(), m_aggressive, m_arrival_starlane, m_next_system, m_prev_system, m_ships, and UniverseObject::SystemID().
bool Fleet::Empty () const inline
Returns true if fleet contains no ships, false otherwise.
Referenced by FleetsListBox::AcceptDrops(), Effect::SetOwner::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), DeleteFleetOrder::ExecuteImpl(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), anonymous_namespace{MapWnd.cpp}::IsQualifiedFleet(), Universe::RecursiveDestroy(), FleetDetailPanel::SetFleet(), Universe::UpdateEmpireStaleObjectKnowledge(), and FreeOrionPython::WrapUniverseClasses().
std::pair< int, int > Fleet::ETA () const
Returns the number of turns which must elapse before the fleet arrives at its current final destination and the turns to the next system, respectively.
References MovePath().
Referenced by Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), and anonymous_namespace{FleetWnd.cpp}::FleetDestinationText().
std::pair< int, int > Fleet::ETA (const std::list< MovePathNode > & move_path) const
Returns the number of turns which must elapse before the fleet arrives at the final destination and next system in the spepcified move_path.
References MovePathNode::eta, ETA_UNKNOWN, INVALID_OBJECT_ID, and MovePathNode::object_id.
int Fleet::FinalDestinationID () const
Returns ID of system that this fleet is moving to or INVALID_OBJECT_ID if staying still.
References INVALID_OBJECT_ID, and m_travel_route.
Referenced by MapWnd::DeferredRefreshFleetButtons(), MapWnd::DispatchFleetsExploring(), Dump(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsMoving(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), ShortenRouteToEndAtSystem(), anonymous_namespace{Effect.cpp}::UpdateFleetRoute(), StationaryFleetVisitor::Visit(), OrderedMovingFleetVisitor::Visit(), MovingFleetVisitor::Visit(), and FreeOrionPython::WrapUniverseClasses().
float Fleet::Fuel () const
Returns effective amount of fuel this fleet has, which is the least of the amounts of fuel that the ships have.
References Meter::Current(), ErrorLogger, Meter::LARGE_VALUE, m_ships, METER_FUEL, NumShips(), and Objects().
Referenced by MapWnd::DispatchFleetsExploring(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MovePath(), and FreeOrionPython::WrapUniverseClasses().
std::string Fleet::GenerateFleetName ()
References FlexibleFormat(), GetShip(), UniverseObject::ID(), INVALID_OBJECT_ID, m_ships, and UserString().
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), and NewFleetOrder::ExecuteImpl().
bool Fleet::HasArmedShips () const
Returns true if there is at least one armed ship in the fleet.
References m_ships, and Objects().
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), FleetDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
bool Fleet::HasColonyShips () const
Returns true if there is at least one colony ship with nonzero capacity in the fleet.
References m_ships, and Objects().
Referenced by FleetDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
bool Fleet::HasFighterShips () const
Returns true if there is at least one ship with fighters in the fleet.
References m_ships, and Objects().
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), FleetDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
bool Fleet::HasMonsters () const
returns true iff this fleet contains monster ships.
References m_ships, and Objects().
Referenced by CreateFleetArrivedAtDestinationSitRep(), PublicName(), FleetDataPanel::Refresh(), MapWnd::SetFleetMovementLine(), and FreeOrionPython::WrapUniverseClasses().
bool Fleet::HasOutpostShips () const
Returns true if there is at least one colony ship with zero capacity in the fleet.
References m_ships, and Objects().
Referenced by FreeOrionPython::WrapUniverseClasses().
bool Fleet::HasShipsOrderedScrapped () const
Returns true if there is at least one ship ordered scrapped in the fleet.
References m_ships, and Objects().
Referenced by FleetWnd::FleetRightClicked().
bool Fleet::HasShipsWithoutScrapOrders () const
Returns true if there is at least one ship without any scrap orders in the fleet.
References m_ships, and Objects().
Referenced by FleetWnd::FleetRightClicked().
bool Fleet::HasTroopShips () const
Returns true if there is at least one troop ship in the fleet.
References m_ships, and Objects().
Referenced by FleetDataPanel::Init(), and FreeOrionPython::WrapUniverseClasses().
float Fleet::MaxFuel () const
Returns effective maximum amount of fuel this fleet has, which is the least of the max amounts of fuel that the ships can have.
References Meter::Current(), ErrorLogger, Meter::LARGE_VALUE, m_ships, METER_MAX_FUEL, NumShips(), and Objects().
Referenced by MapWnd::DispatchFleetsExploring(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MovePath(), and FreeOrionPython::WrapUniverseClasses().
void Fleet::MovementPhase () virtual
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
update m_arrival_starlane if no blockade, if needed
Reimplemented from UniverseObject.
References Empire::AddExploredSystem(), BlockadedAtSystem(), boost::dynamic_pointer_cast(), ErrorLogger, ObjectMap::FindObjects(), GetEmpire(), GetSupplyManager(), GetSystem(), UniverseObject::ID(), anonymous_namespace{Fleet.cpp}::InsertFleetWithShips(), INVALID_OBJECT_ID, m_arrival_starlane, m_arrived_this_turn, m_next_system, m_prev_system, m_ships, m_travel_route, METER_FUEL, anonymous_namespace{Fleet.cpp}::MoveFleetWithShips(), MovePath(), Objects(), UniverseObject::Owner(), Empire::RecordPendingLaneUpdate(), System::Remove(), Ship::Resupply(), SetRoute(), UniverseObject::SetSystem(), ShortenRouteToEndAtSystem(), Empire::SupplyUnobstructedSystems(), SupplyManager::SystemHasFleetSupply(), UniverseObject::SystemID(), EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis(), and TravelRoute().
std::list< MovePathNode > Fleet::MovePath (const std::list< int > & route, bool flag_blockades = false) const
Returns a list of locations at which notable events will occur along the fleet's path if it follows the specified route. It is assumed in the calculation that the fleet starts its move path at its actual current location, however the fleet's current location will not be on the list, even if it is currently in a system.
References BlockadedAtSystem(), DebugLogger, anonymous_namespace{Fleet.cpp}::EMPTY_SET, ErrorLogger, ETA_NEVER, ETA_OUT_OF_RANGE, anonymous_namespace{Fleet.cpp}::FLEET_MOVEMENT_EPSILON, SupplyManager::FleetSupplyableSystemIDs(), Fuel(), GetEmpire(), GetEmpireKnownSystem(), GetSupplyManager(), GetSystem(), System::HasStarlaneTo(), UniverseObject::ID(), INVALID_OBJECT_ID, m_arrival_starlane, MaxFuel(), UniverseObject::Name(), UniverseObject::Owner(), PreviousSystemID(), Speed(), Empire::SupplyUnobstructedSystems(), UniverseObject::SystemID(), Empire::UnrestrictedLaneTravel(), UniverseObject::X(), and UniverseObject::Y().
Referenced by MapWnd::DispatchFleetsExploring(), ETA(), Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), MovementPhase(), MovePath(), MapWnd::SetFleetMovementLine(), and MapWnd::SetProjectedFleetMovementLine().
std::list< MovePathNode > Fleet::MovePath (bool flag_blockades = false) const
Returns MovePath for fleet's current TravelRoute.
References MovePath(), and TravelRoute().
int Fleet::NextSystemID () const inline
Returns ID of system that this fleet is moving to next as it moves to its destination.
Referenced by Effect::SetOwner::Execute(), Effect::MoveTo::Execute(), Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), FleetButton::Init(), AIInterface::IssueFleetMoveOrder(), Universe::JumpDistanceBetweenObjects(), Condition::Stationary::Match(), MapWnd::MovingFleetMapPositionOnLane(), MapWnd::PlotFleetMovement(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), Universe::ShortestPathDistance(), and FreeOrionPython::WrapUniverseClasses().
int Fleet::NumShips () const inline
Returns number of ships in fleet.
Referenced by CreateFleetArrivedAtDestinationSitRep(), FleetSizeIcon(), Fuel(), MaxFuel(), MapWnd::PlotFleetMovement(), ResourceOutput(), FleetDataPanel::SetStatIconValues(), and FreeOrionPython::WrapUniverseClasses().
UniverseObjectType Fleet::ObjectType () const virtual
returns set of IDs of ships in fleet.
Reimplemented from UniverseObject.
int Fleet::OrderedGivenToEmpire () const inline
returns the ID of the empire this fleet has been ordered given to, or ALL_EMPIRES if this fleet hasn't been ordered given to an empire
Referenced by FleetWnd::FleetRightClicked(), and FleetDataPanel::Refresh().
int Fleet::PreviousSystemID () const inline
Returns ID of system that this fleet is moving away from as it moves to its destination.
Referenced by Effect::SetOwner::Execute(), Effect::MoveTo::Execute(), Universe::JumpDistanceBetweenObjects(), MovePath(), MapWnd::MovingFleetMapPositionOnLane(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), and FreeOrionPython::WrapUniverseClasses().
const std::string & Fleet::PublicName (int empire_id) const virtual
returns set of IDs of ships in fleet.
Reimplemented from UniverseObject.
References ALL_EMPIRES, GetUniverse(), UniverseObject::GetVisibility(), HasMonsters(), UniverseObject::Name(), UniverseObject::OwnedBy(), UniverseObject::Unowned(), and UserString().
Referenced by FleetDataPanel::Refresh().
void Fleet::RemoveShip (int ship_id)
removes the ship from the fleet.
References RemoveShips().
Referenced by Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), and Universe::RecursiveDestroy().
void Fleet::RemoveShips (const std::vector< int > & ship_ids)
removes the ships from the fleet.
References m_ships, and UniverseObject::StateChangedSignal.
Referenced by RemoveShip().
void Fleet::ResetTargetMaxUnpairedMeters () virtual
sets this fleet to move through the series of systems in the list, in order
Reimplemented from UniverseObject.
References UniverseObject::GetMeter(), METER_STEALTH, and UniverseObject::ResetTargetMaxUnpairedMeters().
float Fleet::ResourceOutput (ResourceType type) const
returns set of IDs of ships in fleet.
References INVALID_METER_TYPE, m_ships, NumShips(), Objects(), and ResourceToMeter().
Referenced by FleetDataPanel::Init(), and FleetDataPanel::SetStatIconValues().
template<class Archive > void Fleet::serialize (Archive & ar, const unsigned int version) private
References m_aggressive, m_arrival_starlane, m_arrived_this_turn, m_next_system, m_ordered_given_to_empire_id, m_prev_system, m_ships, m_travel_distance, and m_travel_route.
void Fleet::SetAggressive (bool aggressive = true)
sets this fleet to be agressive (true) or passive (false)
References m_aggressive, and UniverseObject::StateChangedSignal.
Referenced by Empire::CheckProductionProgress(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Effect::SetAggression::Execute(), and NewFleetOrder::ExecuteImpl().
void Fleet::SetArrivalStarlane (int starlane) inline
sets the arrival starlane, used to clear blockaded status after combat
Referenced by NewFleetOrder::ExecuteImpl(), and ServerApp::UpdateMonsterTravelRestrictions().
void Fleet::SetGiveToEmpire (int empire_id)
marks fleet to be given to empire
References m_ordered_given_to_empire_id, and UniverseObject::StateChangedSignal.
Referenced by ClearGiveToEmpire().
void Fleet::SetNextAndPreviousSystems (int next, int prev)
sets the previous and next systems for this fleet. Useful after moving a moving fleet to a different location, so that it moves along its new local starlanes
References m_arrival_starlane, m_next_system, and m_prev_system.
Referenced by Empire::CheckProductionProgress(), Effect::SetOwner::Execute(), and anonymous_namespace{Effect.cpp}::UpdateFleetRoute().
void Fleet::SetRoute (const std::list< int > & route)
sets this fleet to move through the series of systems in the list, in order
References CanChangeDirectionEnRoute(), ErrorLogger, GetSystem(), INVALID_OBJECT_ID, m_next_system, m_prev_system, m_travel_distance, m_travel_route, anonymous_namespace{Fleet.cpp}::PathLength(), UniverseObject::StateChangedSignal, UniverseObject::SystemID(), UnknownRoute(), UniverseObject::X(), and UniverseObject::Y().
Referenced by CalculateRouteTo(), Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), MovementPhase(), and anonymous_namespace{Effect.cpp}::UpdateFleetRoute().
float Fleet::Shields () const
Returns total amount of shields this fleet has, which is the sum of the ships' shields.
References GetShip(), m_ships, and METER_SHIELD.
const std::set<int>& Fleet::ShipIDs () const inline
returns set of IDs of ships in fleet.
Referenced by BlockadedAtSystem(), CreateFleetArrivedAtDestinationSitRep(), FleetWnd::FleetRightClicked(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{Fleet.cpp}::InsertFleetWithShips(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), anonymous_namespace{Fleet.cpp}::MoveFleetWithShips(), ShipsListBox::Refresh(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), FleetDetailPanel::ShipRightClicked(), Universe::UpdateEmpireStaleObjectKnowledge(), and FreeOrionPython::WrapUniverseClasses().
void Fleet::ShortenRouteToEndAtSystem (std::list< int > & travel_route, int last_system) private
< removes any systems on the route after the specified system
References FinalDestinationID(), m_travel_route, UniverseObject::Owner(), and anonymous_namespace{Fleet.cpp}::SystemHasNoVisibleStarlanes().
Referenced by Copy(), and MovementPhase().
float Fleet::Speed () const
Returns speed of fleet. (Should be equal to speed of slowest ship in fleet, unless in future the calculation of fleet speed changes.)
References GetShip(), m_ships, and anonymous_namespace{Fleet.cpp}::MAX_SHIP_SPEED.
Referenced by MovePath(), and FreeOrionPython::WrapUniverseClasses().
float Fleet::Structure () const
Returns total amount of structure this fleet has, which is the sum of the ships' structure.
References GetShip(), m_ships, and METER_STRUCTURE.
const std::list< int > & Fleet::TravelRoute () const
Returns the list of systems that this fleet will move through en route to its destination (may be empty). If this fleet is currently at a system, that system will be the first one in the list.
References m_travel_route.
Referenced by MapWnd::DeferredRefreshFleetButtons(), FleetMoveOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), MovementPhase(), MovePath(), MapWnd::PlotFleetMovement(), MapWnd::SetFleetMovementLine(), StationaryFleetVisitor::Visit(), and OrderedMovingFleetVisitor::Visit().
bool Fleet::UnknownRoute () const
Returns true iff this fleet is moving, but the route is unknown. This is usually the case when a foreign player A's fleet is represented on another player B's client, and player B has never seen one or more of the systems in the fleet's route.
References INVALID_OBJECT_ID, and m_travel_route.
Referenced by SetRoute().
Friends And Related Function Documentation
template<class T > void boost::checked_delete (T * x) friend
general ctor taking name, position and owner id
template<class T > void boost::python::detail::value_destroyer (T const volatile * p) friend
general ctor taking name, position and owner id
friend class boost::serialization::access friend
friend class ObjectMap friend
friend class Universe friend
Member Data Documentation
const int Fleet::ETA_NEVER = (1 << 30) - 2 static
returned by ETA when fleet can't reach destination due to lack of route or inability to move
Referenced by ValueRef::StringCast< FromType >::Eval(), Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MapWnd::MovementLineData::MovementLineData(), and MovePath().
const int Fleet::ETA_OUT_OF_RANGE = (1 << 30) - 1 static
returned by ETA when fleet can't reach destination due to insufficient fuel capacity and lack of fleet resupply on route
Referenced by ValueRef::StringCast< FromType >::Eval(), Effect::SetDestination::Execute(), FleetMoveOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), MapWnd::MovementLineData::MovementLineData(), and MovePath().
const int Fleet::ETA_UNKNOWN = (1 << 30) static
returned when ETA can't be determined
Referenced by ETA(), ValueRef::StringCast< FromType >::Eval(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), and MapWnd::MovementLineData::MovementLineData().
bool Fleet::m_aggressive private
should this fleet attack enemies in the same system?
Referenced by Copy(), Dump(), serialize(), and SetAggressive().
int Fleet::m_arrival_starlane private
Referenced by BlockadedAtSystem(), Copy(), Dump(), MovementPhase(), MovePath(), serialize(), and SetNextAndPreviousSystems().
bool Fleet::m_arrived_this_turn private
Referenced by Copy(), MovementPhase(), and serialize().
int Fleet::m_next_system private
the next system in the route, if any
Referenced by CalculateRouteTo(), Copy(), Dump(), MovementPhase(), serialize(), SetNextAndPreviousSystems(), and SetRoute().
int Fleet::m_ordered_given_to_empire_id private
Referenced by Copy(), serialize(), and SetGiveToEmpire().
int Fleet::m_prev_system private
the previous system in the route, if any
Referenced by CalculateRouteTo(), Copy(), Dump(), MovementPhase(), serialize(), SetNextAndPreviousSystems(), and SetRoute().
std::set<int> Fleet::m_ships private
Referenced by AddShips(), ObjectMap::AuditContainment(), ContainedObjectIDs(), Contains(), Copy(), Damage(), Dump(), Fuel(), GenerateFleetName(), HasArmedShips(), HasColonyShips(), HasFighterShips(), HasMonsters(), HasOutpostShips(), HasShipsOrderedScrapped(), HasShipsWithoutScrapOrders(), HasTroopShips(), MaxFuel(), MovementPhase(), RemoveShips(), ResourceOutput(), serialize(), Shields(), Speed(), and Structure().
double Fleet::m_travel_distance mutable private
Referenced by Copy(), serialize(), and SetRoute().
std::list<int> Fleet::m_travel_route private
list of systems on travel route of fleet from current position to destination. If the fleet is currently in a system, that will be the first system on the list. Otherwise, the first system on the list will be the next system the fleet will reach along its path. The list may also contain a single null pointer, which indicates that the route is unknown. The list may also be empty, which indicates that the fleet is not planning to move.
Referenced by Copy(), FinalDestinationID(), MovementPhase(), serialize(), SetRoute(), ShortenRouteToEndAtSystem(), TravelRoute(), and UnknownRoute().
The documentation for this class was generated from the following files:
Fleet.h
Fleet.cpp
SerializeUniverse.cpp