FreeOrion: CUIDropDownList Class Reference
CUIDropDownList Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
CUIDropDownList (size_t num_shown_elements)
basic ctor
Mutators
virtual void Render ()
disables rendering of the small downward-facing arrow on the right of the control
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
disables rendering of the small downward-facing arrow on the right of the control
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
disables rendering of the small downward-facing arrow on the right of the control
virtual void MouseLeave ()
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Private Member Functions
virtual void InitBuffer ()
Private Attributes
bool m_mouse_here
bool m_render_drop_arrow
Detailed Description
a FreeOrion DropDownList control
Constructor & Destructor Documentation
CUIDropDownList::CUIDropDownList (size_t num_shown_elements) explicit
basic ctor
References ClientUI::CtrlColor(), and CUISimpleDropDownListRow::DEFAULT_ROW_HEIGHT.
Member Function Documentation
void CUIDropDownList::DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
References m_render_drop_arrow.
Referenced by SidePanel::SidePanel().
void CUIDropDownList::EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
References m_render_drop_arrow.
void CUIDropDownList::InitBuffer () private virtual
References BufferStoreAngledCornerRectangleVertices(), BufferStoreIsoscelesTriangle(), anonymous_namespace{CUIControls.cpp}::CUIDROPDOWNLIST_ANGLE_OFFSET, and SHAPE_DOWN.
void CUIDropDownList::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
disables rendering of the small downward-facing arrow on the right of the control
Reimplemented in anonymous_namespace{ProductionWnd.cpp}::QuantitySelector.
References anonymous_namespace{CUIControls.cpp}::PlayDropDownListOpenSound().
void CUIDropDownList::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
disables rendering of the small downward-facing arrow on the right of the control
References m_mouse_here, and anonymous_namespace{CUIControls.cpp}::PlayButtonRolloverSound().
void CUIDropDownList::MouseLeave () virtual
disables rendering of the small downward-facing arrow on the right of the control
References m_mouse_here.
void CUIDropDownList::Render () virtual
disables rendering of the small downward-facing arrow on the right of the control
References AdjustBrightness(), anonymous_namespace{CUIControls.cpp}::ARROW_BRIGHTENING_SCALE_FACTOR, ClientUI::DropDownListArrowColor(), m_mouse_here, and m_render_drop_arrow.
Member Data Documentation
bool CUIDropDownList::m_mouse_here private
Referenced by MouseEnter(), MouseLeave(), and Render().
bool CUIDropDownList::m_render_drop_arrow private
Referenced by DisableDropArrow(), EnableDropArrow(), and Render().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp