FreeOrion: PopCenter Class Reference
PopCenter Class Reference abstract
#include <PopCenter.h>
Public Member Functions
Structors
PopCenter ()
default ctor
PopCenter (const std::string &species_name)
basic ctor
virtual ~PopCenter ()
dtor
Accessors
const std::string & SpeciesName () const
returns the name of the species that populates this planet
std::string Dump () const
returns the name of the species that populates this planet
float NextTurnPopGrowth () const
predicted pop growth next turn
virtual float InitialMeterValue (MeterType type) const =0
implementation should return the initial value of the specified meter type
virtual float CurrentMeterValue (MeterType type) const =0
implementation should current value of the specified meter type
virtual float NextTurnCurrentMeterValue (MeterType type) const =0
implementation should return an estimate of the next turn's current value of the specified meter type
Mutators
void Copy (TemporaryPtr< const PopCenter > copied_object, Visibility vis=VIS_FULL_VISIBILITY)
sets the species of the population to species_name
void SetSpecies (const std::string &species_name)
sets the species of the population to species_name
virtual void Reset ()
sets all meters to 0, clears race name
virtual void Depopulate ()
removes population
Public Member Functions inherited from EnableTemporaryFromThis< UniverseObject >
EnableTemporaryFromThis ()
TemporaryPtr< UniverseObject > TemporaryFromThis ()
TemporaryPtr< const
UniverseObject > TemporaryFromThis () const
Protected Member Functions
void Init ()
initialization that needs to be called by derived class after derived class is constructed
void PopCenterClampMeters ()
float PopCenterNextTurnMeterValue (MeterType meter_type) const
returns estimate of the next turn's current values of meters relevant to this PopCenter
void PopCenterPopGrowthProductionResearchPhase ()
void PopCenterResetTargetMaxUnpairedMeters ()
Private Member Functions
virtual void AddMeter (MeterType meter_type)=0
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
virtual Meter * GetMeter (MeterType type)=0
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
virtual const Meter * GetMeter (MeterType type) const =0
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::string m_species_name
the name of the species that occupies this planet
Friends
class boost::serialization::access
Additional Inherited Members
Public Types inherited from EnableTemporaryFromThis< UniverseObject >
typedef
EnableTemporaryFromThis
< UniverseObject > enable_temporary_from_this_type
Detailed Description
The PopCenter class is an abstract base class for anything in the FreeOrion gamestate that has population on or in it. Most likely, such an object will also be a subclass of UniverseObject. Planet is the most obvious class to inherit PopCenter, but other classes could be made from it as well (e.g., a ship that is large enough to support population and still travel between systems).
Constructor & Destructor Documentation
PopCenter::PopCenter ()
default ctor
PopCenter::PopCenter (const std::string & species_name) explicit
basic ctor
PopCenter::~PopCenter () virtual
dtor
Member Function Documentation
virtual void PopCenter::AddMeter (MeterType meter_type) private pure virtual
implementation should add a meter to the object so that it can be accessed with the GetMeter() functions
Implemented in Planet.
Referenced by Init().
void PopCenter::Copy (TemporaryPtr< const PopCenter > copied_object, Visibility vis = VIS_FULL_VISIBILITY)
sets the species of the population to species_name
References ErrorLogger, and m_species_name.
Referenced by Planet::Copy().
float PopCenter::CurrentMeterValue (MeterType type) const pure virtual
implementation should current value of the specified meter type
Implemented in Planet.
References Meter::Current(), and GetMeter().
Referenced by PopCenterPopGrowthProductionResearchPhase(), and MapWnd::RefreshPopulationIndicator().
void PopCenter::Depopulate () virtual
removes population
Reimplemented in Planet.
References GetMeter(), METER_HAPPINESS, METER_POPULATION, and Meter::Reset().
Referenced by Planet::Depopulate(), and PopCenterPopGrowthProductionResearchPhase().
std::string PopCenter::Dump () const
returns the name of the species that populates this planet
References m_species_name.
Referenced by Planet::Dump().
virtual Meter* PopCenter::GetMeter (MeterType type) private pure virtual
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
Implemented in Planet.
Referenced by CurrentMeterValue(), Depopulate(), NextTurnPopGrowth(), PopCenterClampMeters(), PopCenterNextTurnMeterValue(), PopCenterPopGrowthProductionResearchPhase(), PopCenterResetTargetMaxUnpairedMeters(), and Reset().
virtual const Meter* PopCenter::GetMeter (MeterType type) const private pure virtual
implementation should return the requested Meter, or 0 if no such Meter of that type is found in this object
Implemented in Planet.
void PopCenter::Init () protected
initialization that needs to be called by derived class after derived class is constructed
References AddMeter(), METER_HAPPINESS, METER_POPULATION, METER_TARGET_HAPPINESS, and METER_TARGET_POPULATION.
Referenced by Planet::Planet().
virtual float PopCenter::InitialMeterValue (MeterType type) const pure virtual
implementation should return the initial value of the specified meter type
Implemented in Planet.
Referenced by PopulationPanel::Update().
virtual float PopCenter::NextTurnCurrentMeterValue (MeterType type) const pure virtual
implementation should return an estimate of the next turn's current value of the specified meter type
Implemented in Planet.
float PopCenter::NextTurnPopGrowth () const
predicted pop growth next turn
References Meter::Current(), GetMeter(), METER_POPULATION, and METER_TARGET_POPULATION.
Referenced by PopCenterNextTurnMeterValue(), PopCenterPopGrowthProductionResearchPhase(), and FreeOrionPython::WrapUniverseClasses().
void PopCenter::PopCenterClampMeters () protected
References Meter::ClampCurrentToRange(), GetMeter(), and METER_POPULATION.
Referenced by Planet::ClampMeters().
float PopCenter::PopCenterNextTurnMeterValue (MeterType meter_type) const protected
returns estimate of the next turn's current values of meters relevant to this PopCenter
References Meter::Current(), DebugLogger, ErrorLogger, GetMeter(), METER_HAPPINESS, METER_POPULATION, METER_TARGET_HAPPINESS, METER_TARGET_POPULATION, and NextTurnPopGrowth().
Referenced by Planet::NextTurnCurrentMeterValue(), and PopCenterPopGrowthProductionResearchPhase().
void PopCenter::PopCenterPopGrowthProductionResearchPhase () protected
References CurrentMeterValue(), Depopulate(), GetMeter(), METER_HAPPINESS, METER_POPULATION, anonymous_namespace{PopCenter.cpp}::MINIMUM_POP_CENTER_POPULATION, NextTurnPopGrowth(), PopCenterNextTurnMeterValue(), and Meter::SetCurrent().
Referenced by Planet::PopGrowthProductionResearchPhase().
void PopCenter::PopCenterResetTargetMaxUnpairedMeters () protected
References GetMeter(), METER_TARGET_HAPPINESS, METER_TARGET_POPULATION, and Meter::ResetCurrent().
Referenced by Planet::ResetTargetMaxUnpairedMeters().
void PopCenter::Reset () virtual
sets all meters to 0, clears race name
Reimplemented in Planet.
References GetMeter(), m_species_name, METER_HAPPINESS, METER_POPULATION, METER_TARGET_HAPPINESS, METER_TARGET_POPULATION, and Meter::Reset().
Referenced by Planet::Colonize(), and Planet::Reset().
template<class Archive > void PopCenter::serialize (Archive & ar, const unsigned int version) private
References m_species_name.
void PopCenter::SetSpecies (const std::string & species_name)
sets the species of the population to species_name
References ErrorLogger, GetSpecies(), m_species_name, and parse::species().
Referenced by AutomaticallyChosenColonyShip(), Planet::Colonize(), anonymous_namespace{ServerWrapper.cpp}::PlanetSetSpecies(), Planet::PopGrowthProductionResearchPhase(), and SidePanel::PlanetPanel::Refresh().
const std::string& PopCenter::SpeciesName () const inline
returns the name of the species that populates this planet
Referenced by AutomaticallyChosenColonyShip(), Planet::AvailableFoci(), Planet::EnvironmentForSpecies(), PopulationPanel::EventFilter(), MultiIconValueIndicator::EventFilter(), Planet::FocusIcon(), Universe::GetEffectsAndTargets(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{Universe.cpp}::GetSpeciesFromObject(), Planet::HasTag(), AIInterface::IssueInvadeOrder(), Condition::Species::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), Planet::NextBetterPlanetTypeForSpecies(), Condition::anonymous_namespace{Condition.cpp}::SpeciesSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{ServerWrapper.cpp}::PlanetGetSpecies(), Planet::PopGrowthProductionResearchPhase(), PopulationPanel::PopulationPanel(), ShipDesign::ProductionLocation(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), MapWnd::RefreshPopulationIndicator(), Planet::Tags(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo(), Empire::UpdateOwnedObjectCounters(), SpeciesManager::UpdatePopulationCounter(), and FreeOrionPython::WrapUniverseClasses().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::string PopCenter::m_species_name private
the name of the species that occupies this planet
Referenced by Copy(), Dump(), Reset(), serialize(), and SetSpecies().
The documentation for this class was generated from the following files:
PopCenter.h
PopCenter.cpp