FreeOrion: TechTreeWnd Class Reference
TechTreeWnd Class Reference
#include <TechTreeWnd.h>
Classes
class LayoutPanel
class TechListBox
class TechTreeControls
Public Types
typedef
boost::signals2::signal< void(const
std::vector< std::string >
&, int)> QueueAddTechsSignalType
typedef
boost::signals2::signal< void(const
std::string &, const GG::Flags
< GG::ModKey > &)> TechClickSignalType
typedef
boost::signals2::signal< void(const
std::string &)> TechSignalType
Public Member Functions
Structors
TechTreeWnd (GG::X w, GG::Y h, bool initially_hidden=true)
~TechTreeWnd ()
Accessors
double Scale () const
std::set< std::string > GetCategoriesShown () const
std::set< TechStatus > GetTechStatusesShown () const
bool PediaVisible ()
Mutators //@{
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
void Show (bool children=true) override
void Update ()
void Clear ()
void Reset ()
void SetScale (double scale)
void ShowCategory (const std::string &category)
void ShowAllCategories ()
void HideCategory (const std::string &category)
void HideAllCategories ()
void ToggleAllCategories ()
void ShowStatus (const TechStatus status)
void HideStatus (const TechStatus status)
void ToggleViewType (bool show_list_view)
void ShowTreeView ()
void ShowListView ()
void CenterOnTech (const std::string &tech_name)
void SetEncyclopediaTech (const std::string &tech_name)
void SelectTech (const std::string &tech_name)
void ShowPedia ()
void HidePedia ()
void TogglePedia ()
Public Attributes
QueueAddTechsSignalType AddTechsToQueueSignal
TechSignalType TechBrowsedSignal
TechSignalType TechSelectedSignal
Private Member Functions
void InitializeWindows ()
void TechBrowsedSlot (const std::string &tech_name)
void TechDoubleClickedSlot (const std::string &tech_name, const GG::Flags< GG::ModKey > &modkeys)
void TechLeftClickedSlot (const std::string &tech_name, const GG::Flags< GG::ModKey > &modkeys)
void TechPediaDisplaySlot (const std::string &tech_name)
void TechRightClickedSlot (const std::string &tech_name, const GG::Flags< GG::ModKey > &modkeys)
Private Attributes
EncyclopediaDetailPanel * m_enc_detail_panel
bool m_init_flag
LayoutPanel * m_layout_panel
TechListBox * m_tech_list
TechTreeControls * m_tech_tree_controls
Detailed Description
Contains the tech graph layout, some controls to control what is visible in the tech layout, the tech navigator, and the tech detail window.
Member Typedef Documentation
typedef boost::signals2::signal<void (const std::vector<std::string>&, int)> TechTreeWnd::QueueAddTechsSignalType
typedef boost::signals2::signal<void (const std::string&, const GG::Flags<GG::ModKey>&)> TechTreeWnd::TechClickSignalType
typedef boost::signals2::signal<void (const std::string&)> TechTreeWnd::TechSignalType
Constructor & Destructor Documentation
TechTreeWnd::TechTreeWnd (GG::X w, GG::Y h, bool initially_hidden = true)
TechTreeWnd contructor is usually called before client has access to techs. Attempting to show the tech tree takes a long time and generates errors. If initially_hidden is true then the tech categories are not parsed until the first time Show() is called, speeding up the constructor and preventing spurious errors.
References CLOSABLE, EncyclopediaDetailPanel::ClosingSignal, HumanClientApp::GetApp(), HidePedia(), InitializeWindows(), TechTreeWnd::TechTreeControls::m_all_cat_button, TechTreeWnd::TechTreeControls::m_cat_buttons, m_enc_detail_panel, m_init_flag, m_layout_panel, TechTreeWnd::TechTreeControls::m_status_buttons, m_tech_list, m_tech_tree_controls, TechTreeWnd::TechTreeControls::m_view_type_button, PINABLE, anonymous_namespace{TechTreeWnd.cpp}::RES_CONTROLS_WND_NAME, anonymous_namespace{TechTreeWnd.cpp}::RES_PEDIA_WND_NAME, ClientUI::ScrollWidth(), ShowAllCategories(), ShowStatus(), ShowTreeView(), TechTreeWnd::LayoutPanel::TechBrowsedSignal, TechTreeWnd::TechListBox::TechBrowsedSignal, TechBrowsedSlot(), TechTreeWnd::LayoutPanel::TechDoubleClickedSignal, TechTreeWnd::TechListBox::TechDoubleClickedSignal, TechDoubleClickedSlot(), TechTreeWnd::LayoutPanel::TechLeftClickedSignal, TechTreeWnd::TechListBox::TechLeftClickedSignal, TechLeftClickedSlot(), TechTreeWnd::LayoutPanel::TechPediaDisplaySignal, TechTreeWnd::TechListBox::TechPediaDisplaySignal, TechPediaDisplaySlot(), TechTreeWnd::LayoutPanel::TechRightClickedSignal, TechTreeWnd::TechListBox::TechRightClickedSignal, TechRightClickedSlot(), and ToggleViewType().
TechTreeWnd::~TechTreeWnd ()
TechTreeWnd contructor is usually called before client has access to techs. Attempting to show the tech tree takes a long time and generates errors. If initially_hidden is true then the tech categories are not parsed until the first time Show() is called, speeding up the constructor and preventing spurious errors.
References m_layout_panel, and m_tech_list.
Member Function Documentation
void TechTreeWnd::CenterOnTech (const std::string & tech_name)
References Tech::Category(), TechTreeWnd::LayoutPanel::CenterOnTech(), AIInterface::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), AIInterface::GetTech(), Empire::GetTechStatus(), m_layout_panel, ShowCategory(), and ShowStatus().
Referenced by ResearchWnd::CenterOnTech(), TechTreeWnd::LayoutPanel::Layout(), and ResearchWnd::ShowTech().
void TechTreeWnd::Clear ()
References TechTreeWnd::LayoutPanel::Clear(), m_enc_detail_panel, m_layout_panel, and EncyclopediaDetailPanel::OnIndex().
Referenced by TechTreeWnd::LayoutPanel::Layout(), TechTreeWnd::TechListBox::Populate(), and ResearchWnd::Sanitize().
std::set< std::string > TechTreeWnd::GetCategoriesShown () const
References TechTreeWnd::LayoutPanel::GetCategoriesShown(), and m_layout_panel.
std::set< TechStatus > TechTreeWnd::GetTechStatusesShown () const
References TechTreeWnd::LayoutPanel::GetTechStatusesShown(), and m_layout_panel.
void TechTreeWnd::HideAllCategories ()
References TechTreeWnd::LayoutPanel::HideAllCategories(), TechTreeWnd::TechListBox::HideAllCategories(), TechTreeWnd::TechTreeControls::m_cat_buttons, m_layout_panel, m_tech_list, and m_tech_tree_controls.
Referenced by ToggleAllCategories().
void TechTreeWnd::HideCategory (const std::string & category)
References TechTreeWnd::LayoutPanel::HideCategory(), TechTreeWnd::TechListBox::HideCategory(), TechTreeWnd::TechTreeControls::m_cat_buttons, m_layout_panel, m_tech_list, and m_tech_tree_controls.
void TechTreeWnd::HidePedia ()
References GetOptionsDB(), CUIWnd::Hide(), m_enc_detail_panel, anonymous_namespace{TechTreeWnd.cpp}::RES_PEDIA_WND_NAME, and OptionsDB::Set().
Referenced by ResearchWnd::HidePedia(), TechTreeWnd(), and TogglePedia().
void TechTreeWnd::HideStatus (const TechStatus status)
References TechTreeWnd::LayoutPanel::HideStatus(), TechTreeWnd::TechListBox::HideStatus(), m_layout_panel, and m_tech_list.
void TechTreeWnd::InitializeWindows () private
References CUIWnd::InitSizeMove(), m_enc_detail_panel, m_layout_panel, m_tech_tree_controls, and ClientUI::ScrollWidth().
Referenced by TechTreeWnd().
bool TechTreeWnd::PediaVisible ()
References m_enc_detail_panel.
Referenced by ResearchWnd::PediaVisible(), and TechPediaDisplaySlot().
void TechTreeWnd::Reset ()
References m_layout_panel, m_tech_list, TechTreeWnd::LayoutPanel::Reset(), and TechTreeWnd::TechListBox::Reset().
Referenced by ResearchWnd::Reset().
double TechTreeWnd::Scale () const
References m_layout_panel, and TechTreeWnd::LayoutPanel::Scale().
void TechTreeWnd::SelectTech (const std::string & tech_name)
References m_layout_panel, and TechTreeWnd::LayoutPanel::ShowTech().
Referenced by ResearchWnd::ShowTech().
void TechTreeWnd::SetEncyclopediaTech (const std::string & tech_name)
References m_enc_detail_panel, and EncyclopediaDetailPanel::SetTech().
Referenced by ResearchWnd::ShowTech(), TechLeftClickedSlot(), and TechPediaDisplaySlot().
void TechTreeWnd::SetScale (double scale)
References m_layout_panel, and TechTreeWnd::LayoutPanel::SetScale().
Referenced by TechTreeWnd::LayoutPanel::TreeZoomedSlot().
void TechTreeWnd::Show (bool children = true) override
References m_init_flag, ShowAllCategories(), and ShowStatus().
void TechTreeWnd::ShowAllCategories ()
References TechTreeWnd::TechTreeControls::m_cat_buttons, m_layout_panel, m_tech_list, m_tech_tree_controls, TechTreeWnd::LayoutPanel::ShowAllCategories(), and TechTreeWnd::TechListBox::ShowAllCategories().
Referenced by Show(), TechTreeWnd(), and ToggleAllCategories().
void TechTreeWnd::ShowCategory (const std::string & category)
References TechTreeWnd::TechTreeControls::m_cat_buttons, m_layout_panel, m_tech_list, m_tech_tree_controls, TechTreeWnd::LayoutPanel::ShowCategory(), and TechTreeWnd::TechListBox::ShowCategory().
Referenced by CenterOnTech().
void TechTreeWnd::ShowListView ()
References m_layout_panel, m_tech_list, m_tech_tree_controls, and TechTreeWnd::TechListBox::Reset().
Referenced by ToggleViewType().
void TechTreeWnd::ShowPedia ()
References GetOptionsDB(), m_enc_detail_panel, EncyclopediaDetailPanel::Refresh(), anonymous_namespace{TechTreeWnd.cpp}::RES_PEDIA_WND_NAME, OptionsDB::Set(), and CUIWnd::Show().
Referenced by ResearchWnd::ShowPedia(), TechPediaDisplaySlot(), and TogglePedia().
void TechTreeWnd::ShowStatus (const TechStatus status)
References m_layout_panel, m_tech_list, TechTreeWnd::LayoutPanel::ShowStatus(), and TechTreeWnd::TechListBox::ShowStatus().
Referenced by CenterOnTech(), Show(), and TechTreeWnd().
void TechTreeWnd::ShowTreeView ()
References m_layout_panel, m_tech_list, and m_tech_tree_controls.
Referenced by TechTreeWnd(), and ToggleViewType().
void TechTreeWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References m_enc_detail_panel, m_layout_panel, m_tech_list, m_tech_tree_controls, and CUIWnd::ValidatePosition().
Referenced by ResearchWnd::DoLayout().
void TechTreeWnd::TechBrowsedSlot (const std::string & tech_name) private
References TechBrowsedSignal.
Referenced by TechTreeWnd().
void TechTreeWnd::TechDoubleClickedSlot (const std::string & tech_name, const GG::Flags< GG::ModKey > & modkeys) private
References AddTechsToQueueSignal, ClientApp::EmpireID(), AIInterface::EmpireID(), HumanClientApp::GetApp(), GetEmpire(), AIInterface::GetTech(), GetTechManager(), Empire::GetTechStatus(), TechManager::RecursivePrereqs(), and parse::techs().
Referenced by TechLeftClickedSlot(), and TechTreeWnd().
void TechTreeWnd::TechLeftClickedSlot (const std::string & tech_name, const GG::Flags< GG::ModKey > & modkeys) private
References SetEncyclopediaTech(), TechDoubleClickedSlot(), and TechSelectedSignal.
Referenced by TechTreeWnd::LayoutPanel::ShowTech(), and TechTreeWnd().
void TechTreeWnd::TechPediaDisplaySlot (const std::string & tech_name) private
References PediaVisible(), SetEncyclopediaTech(), and ShowPedia().
Referenced by TechTreeWnd().
void TechTreeWnd::TechRightClickedSlot (const std::string & tech_name, const GG::Flags< GG::ModKey > & modkeys) private
Referenced by TechTreeWnd().
void TechTreeWnd::ToggleAllCategories ()
References TechManager::CategoryNames(), TechTreeWnd::LayoutPanel::GetCategoriesShown(), GetTechManager(), HideAllCategories(), m_layout_panel, and ShowAllCategories().
void TechTreeWnd::TogglePedia ()
References HidePedia(), m_enc_detail_panel, and ShowPedia().
Referenced by ResearchWnd::TogglePedia().
void TechTreeWnd::ToggleViewType (bool show_list_view)
References ShowListView(), and ShowTreeView().
Referenced by TechTreeWnd().
void TechTreeWnd::Update ()
References m_layout_panel, m_tech_list, TechTreeWnd::LayoutPanel::Update(), and TechTreeWnd::TechListBox::Update().
Referenced by ResearchWnd::ResearchQueueChangedSlot(), and ResearchWnd::Update().
Member Data Documentation
QueueAddTechsSignalType TechTreeWnd::AddTechsToQueueSignal mutable
Referenced by ResearchWnd::ResearchWnd(), and TechDoubleClickedSlot().
EncyclopediaDetailPanel* TechTreeWnd::m_enc_detail_panel private
Referenced by Clear(), HidePedia(), InitializeWindows(), PediaVisible(), SetEncyclopediaTech(), ShowPedia(), SizeMove(), TechTreeWnd(), and TogglePedia().
bool TechTreeWnd::m_init_flag private
If m_init_flag is true tech categories are not parsed until the first time Show() is called. TechTreeWnd is constructed before the tech categories are available to be parsed.
Referenced by Show(), and TechTreeWnd().
LayoutPanel* TechTreeWnd::m_layout_panel private
Referenced by CenterOnTech(), Clear(), GetCategoriesShown(), GetTechStatusesShown(), HideAllCategories(), HideCategory(), HideStatus(), InitializeWindows(), TechTreeWnd::LayoutPanel::TechPanel::InWindow(), TechTreeWnd::LayoutPanel::TechPanel::LClick(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), TechTreeWnd::LayoutPanel::TechPanel::Render(), Reset(), Scale(), SelectTech(), SetScale(), ShowAllCategories(), ShowCategory(), ShowListView(), ShowStatus(), ShowTreeView(), SizeMove(), TechTreeWnd(), ToggleAllCategories(), Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), and ~TechTreeWnd().
TechListBox* TechTreeWnd::m_tech_list private
Referenced by HideAllCategories(), HideCategory(), HideStatus(), Reset(), ShowAllCategories(), ShowCategory(), ShowListView(), ShowStatus(), ShowTreeView(), SizeMove(), TechTreeWnd(), Update(), and ~TechTreeWnd().
TechTreeControls* TechTreeWnd::m_tech_tree_controls private
Referenced by HideAllCategories(), HideCategory(), InitializeWindows(), ShowAllCategories(), ShowCategory(), ShowListView(), ShowTreeView(), SizeMove(), and TechTreeWnd().
TechSignalType TechTreeWnd::TechBrowsedSignal mutable
Referenced by TechBrowsedSlot(), and TechTreeWnd::LayoutPanel::TechBrowsedSlot().
TechSignalType TechTreeWnd::TechSelectedSignal mutable
Referenced by TechLeftClickedSlot().
The documentation for this class was generated from the following files:
TechTreeWnd.h
TechTreeWnd.cpp