FreeOrion: ObjectPanel Class Reference
ObjectPanel Class Reference
Public Member Functions
ObjectPanel (GG::X w, GG::Y h, TemporaryPtr< const UniverseObject > obj, bool expanded, bool has_contents, int indent)
int ObjectID () const
virtual void PreRender ()
void RefreshLayout ()
virtual void Render ()
void ResourceCenterChanged ()
void Select (bool b)
void SetHasContents (bool has_contents)
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
std::string SortKey (std::size_t column) const
Public Attributes
boost::signals2::signal< void()> ExpandCollapseSignal
Private Member Functions
void DoLayout ()
void ExpandCollapseButtonPressed ()
std::vector< GG::Control * > GetControls ()
void Init ()
void RefreshCache () const
Private Attributes
std::vector< std::string > m_column_val_cache
std::vector< GG::Control * > m_controls
GG::StaticGraphic * m_dot
GG::Button * m_expand_button
bool m_expanded
bool m_has_contents
MultiTextureStaticGraphic * m_icon
int m_indent
bool m_initialized
int m_object_id
bool m_selected
Constructor & Destructor Documentation
ObjectPanel::ObjectPanel (GG::X w, GG::Y h, TemporaryPtr< const UniverseObject > obj, bool expanded, bool has_contents, int indent) inline
References boost::dynamic_pointer_cast(), ResourceCenterChanged(), and ResourceCenter::ResourceCenterChangedSignal.
Member Function Documentation
void ObjectPanel::DoLayout () inline private
References anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), m_controls, m_dot, m_expand_button, m_icon, m_indent, m_initialized, and anonymous_namespace{ObjectListWnd.cpp}::PAD().
Referenced by RefreshLayout(), and SizeMove().
void ObjectPanel::ExpandCollapseButtonPressed () inline private
References ExpandCollapseSignal, and m_expanded.
Referenced by RefreshLayout().
std::vector<GG::Control*> ObjectPanel::GetControls () inline private
References anonymous_namespace{ObjectListWnd.cpp}::GetColumnWidth(), m_column_val_cache, anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS(), and RefreshCache().
Referenced by RefreshLayout().
void ObjectPanel::Init () inline private
References m_initialized, and RefreshLayout().
Referenced by Render().
int ObjectPanel::ObjectID () const inline
References m_object_id.
Referenced by ObjectRow::ExpandCollapseClicked(), and ObjectRow::ObjectID().
virtual void ObjectPanel::PreRender () inline virtual
References RefreshLayout().
void ObjectPanel::RefreshCache () const inline private
References ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{ObjectListWnd.cpp}::GetColumnValueRef(), GetUniverseObject(), m_column_val_cache, m_object_id, and anonymous_namespace{ObjectListWnd.cpp}::NUM_COLUMNS().
Referenced by GetControls(), ResourceCenterChanged(), and SortKey().
void ObjectPanel::RefreshLayout () inline
References ClientUI::ArtDir(), DoLayout(), ExpandCollapseButtonPressed(), GetControls(), ClientUI::GetTexture(), GetUniverseObject(), m_controls, m_dot, m_expand_button, m_expanded, m_has_contents, m_icon, m_initialized, m_object_id, and anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures().
Referenced by Init(), and PreRender().
virtual void ObjectPanel::Render () inline virtual
References Init(), m_initialized, m_selected, ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
void ObjectPanel::ResourceCenterChanged () inline
References RefreshCache().
Referenced by ObjectPanel().
void ObjectPanel::Select (bool b) inline
References m_selected.
Referenced by ObjectListWnd::ObjectSelectionChanged().
void ObjectPanel::SetHasContents (bool has_contents) inline
References m_has_contents.
Referenced by ObjectRow::SetContainedPanels().
virtual void ObjectPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References DoLayout().
std::string ObjectPanel::SortKey (std::size_t column) const inline
References m_column_val_cache, and RefreshCache().
Referenced by ObjectRow::SortKey().
Member Data Documentation
boost::signals2::signal<void ()> ObjectPanel::ExpandCollapseSignal mutable
Referenced by ExpandCollapseButtonPressed(), and ObjectRow::Init().
std::vector<std::string> ObjectPanel::m_column_val_cache mutable private
Referenced by GetControls(), RefreshCache(), and SortKey().
std::vector<GG::Control*> ObjectPanel::m_controls private
Referenced by DoLayout(), and RefreshLayout().
GG::StaticGraphic* ObjectPanel::m_dot private
Referenced by DoLayout(), and RefreshLayout().
GG::Button* ObjectPanel::m_expand_button private
Referenced by DoLayout(), and RefreshLayout().
bool ObjectPanel::m_expanded private
Referenced by ExpandCollapseButtonPressed(), and RefreshLayout().
bool ObjectPanel::m_has_contents private
Referenced by RefreshLayout(), and SetHasContents().
MultiTextureStaticGraphic* ObjectPanel::m_icon private
Referenced by DoLayout(), and RefreshLayout().
int ObjectPanel::m_indent private
Referenced by DoLayout().
bool ObjectPanel::m_initialized private
Referenced by DoLayout(), Init(), RefreshLayout(), and Render().
int ObjectPanel::m_object_id private
Referenced by ObjectID(), RefreshCache(), and RefreshLayout().
bool ObjectPanel::m_selected private
Referenced by Render(), and Select().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp