FreeOrion: SaveFileDirectoryRow Class Reference
SaveFileDirectoryRow Class Reference
Public Member Functions
SaveFileDirectoryRow (const boost::shared_ptr< std::vector< SaveFileColumn > > &columns, const std::string &directory)
GG::X DirectoryNameSize ()
virtual void Init ()
virtual SortKeyType SortKey (std::size_t column) const
Public Member Functions inherited from SaveFileRow
SaveFileRow ()
SaveFileRow (const boost::shared_ptr< std::vector< SaveFileColumn > > &columns, const std::string &filename)
virtual void AdjustColumns ()
virtual GG::Pt ClientLowerRight () const
virtual GG::Pt ClientUpperLeft () const
const std::string & Filename () const
virtual void PreRender ()
virtual void Render ()
Additional Inherited Members
Protected Attributes inherited from SaveFileRow
boost::shared_ptr< std::vector
< SaveFileColumn > > m_columns
std::string m_filename
bool m_initialized
Constructor & Destructor Documentation
SaveFileDirectoryRow::SaveFileDirectoryRow (const boost::shared_ptr< std::vector< SaveFileColumn > > & columns, const std::string & directory) inline
References anonymous_namespace{SaveFileDialog.cpp}::ROW_MARGIN.
Member Function Documentation
GG::X SaveFileDirectoryRow::DirectoryNameSize () inline
References SaveFileColumn::FixedWidth(), ClientUI::GetFont(), and SaveFileRow::m_columns.
Referenced by Init().
virtual void SaveFileDirectoryRow::Init () inline virtual
Reimplemented from SaveFileRow.
References SaveFileRow::AdjustColumns(), DirectoryNameSize(), ClientUI::GetFont(), SaveFileRow::Init(), parse::label(), SaveFileRow::m_columns, SaveFileRow::m_filename, anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_BEGIN, and anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_END.
virtual SortKeyType SaveFileDirectoryRow::SortKey (std::size_t column) const inline virtual
References SaveFileRow::m_filename.
The documentation for this class was generated from the following file:
SaveFileDialog.cpp