FreeOrion: CUIToggleRepresenter Class Reference
CUIToggleRepresenter Class Reference
Represents a CUIToggleButton.
#include <CUIControls.h>
Public Member Functions
Structors
CUIToggleRepresenter (boost::shared_ptr< GG::SubTexture > icon, const GG::Clr &highlight_clr)
ctor
CUIToggleRepresenter (boost::shared_ptr< GG::SubTexture > unchecked_icon, const GG::Clr &unchecked_clr, boost::shared_ptr< GG::SubTexture > checked_icon, const GG::Clr &checked_clr)
ctor
Mutators
virtual void OnChecked (bool checked) const
virtual void Render (const GG::StateButton &button) const
Private Attributes
GG::Clr m_checked_color
boost::shared_ptr< GG::SubTexture > m_checked_icon
GG::Clr m_unchecked_color
boost::shared_ptr< GG::SubTexture > m_unchecked_icon
Detailed Description
Represents a CUIToggleButton.
Renders a SubTexture depending on the checked state of the CUIToggleButton. When the button has single texture and is unchecked, it renders the same icon recolored towards grey. If a second SubTexture is assigned to the button, it will render the appropriate SubTexture. When a mouse pointer hovers over this button, the opposing SubTexture and color are used and highlighted
Constructor & Destructor Documentation
CUIToggleRepresenter::CUIToggleRepresenter (boost::shared_ptr< GG::SubTexture > icon, const GG::Clr & highlight_clr)
ctor
CUIToggleRepresenter::CUIToggleRepresenter (boost::shared_ptr< GG::SubTexture > unchecked_icon, const GG::Clr & unchecked_clr, boost::shared_ptr< GG::SubTexture > checked_icon, const GG::Clr & checked_clr)
ctor
Member Function Documentation
void CUIToggleRepresenter::OnChecked (bool checked) const virtual
References anonymous_namespace{CUIControls.cpp}::PlayButtonCheckSound().
void CUIToggleRepresenter::Render (const GG::StateButton & button) const virtual
References AdjustBrightness(), AngledCornerRectangle(), ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), anonymous_namespace{CUIControls.cpp}::CUIBUTTON_ANGLE_OFFSET, m_checked_color, m_checked_icon, m_unchecked_color, and m_unchecked_icon.
Member Data Documentation
GG::Clr CUIToggleRepresenter::m_checked_color private
Referenced by Render().
boost::shared_ptr<GG::SubTexture> CUIToggleRepresenter::m_checked_icon private
Referenced by Render().
GG::Clr CUIToggleRepresenter::m_unchecked_color private
Referenced by Render().
boost::shared_ptr<GG::SubTexture> CUIToggleRepresenter::m_unchecked_icon private
Referenced by Render().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp