FreeOrion: SectionedScopedTimer::SectionedScopedTimerImpl Class Reference
SectionedScopedTimer::SectionedScopedTimerImpl Class Reference
Classes
struct Sections
Public Member Functions
SectionedScopedTimerImpl (const std::string &timed_name, bool enable_output, boost::chrono::microseconds threshold)
~SectionedScopedTimerImpl ()
Sections * CreateSections (const boost::chrono::high_resolution_clock::time_point &now)
void EnterSection (const std::string &section_name)
Public Member Functions inherited from ScopedTimer::ScopedTimerImpl
ScopedTimerImpl (const std::string &timed_name, bool enable_output, boost::chrono::microseconds threshold)
~ScopedTimerImpl ()
void FormatDuration (std::stringstream &ss, const boost::chrono::nanoseconds &duration)
bool ShouldOutput (const boost::chrono::nanoseconds &duration)
Public Attributes
boost::scoped_ptr< Sections > m_sections
Public Attributes inherited from ScopedTimer::ScopedTimerImpl
bool m_enable_output
std::string m_name
boost::chrono::high_resolution_clock::time_point m_start
boost::chrono::microseconds m_threshold
Constructor & Destructor Documentation
SectionedScopedTimer::SectionedScopedTimerImpl::SectionedScopedTimerImpl (const std::string & timed_name, bool enable_output, boost::chrono::microseconds threshold) inline
SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl () inline
The destructor will print the table of accumulated times.
References DebugLogger, EnterSection(), ErrorLogger, ScopedTimer::ScopedTimerImpl::FormatDuration(), ScopedTimer::ScopedTimerImpl::m_enable_output, ScopedTimer::ScopedTimerImpl::m_name, m_sections, ScopedTimer::ScopedTimerImpl::m_start, and ScopedTimer::ScopedTimerImpl::ShouldOutput().
Member Function Documentation
Sections* SectionedScopedTimer::SectionedScopedTimerImpl::CreateSections (const boost::chrono::high_resolution_clock::time_point & now) inline
CreateSections allow m_sections to only be initialized if it is used.
References m_sections, and ScopedTimer::ScopedTimerImpl::m_start.
Referenced by EnterSection().
void SectionedScopedTimer::SectionedScopedTimerImpl::EnterSection (const std::string & section_name) inline
References CreateSections(), and m_sections.
Referenced by ~SectionedScopedTimerImpl().
Member Data Documentation
boost::scoped_ptr<Sections> SectionedScopedTimer::SectionedScopedTimerImpl::m_sections
Referenced by CreateSections(), EnterSection(), and ~SectionedScopedTimerImpl().
The documentation for this class was generated from the following file:
ScopedTimer.cpp