FreeOrion: FleetDetailPanel Class Reference
FleetDetailPanel Class Reference
Public Member Functions
FleetDetailPanel (GG::X w, GG::Y h, int fleet_id, bool order_issuing_enabled, GG::Flags< GG::WndFlag > flags=GG::NO_WND_FLAGS)
void EnableOrderIssuing (bool enabled=true)
int FleetID () const
void Refresh ()
std::set< int > SelectedShipIDs () const
returns ids of ships selected in the detail panel's ShipsListBox
void SetFleet (int fleet_id)
sets the currently-displayed Fleet. setting to INVALID_OBJECT_ID shows no fleet
void SetSelectedShips (const std::set< int > &ship_ids)
sets the currently-selected ships in the ships list
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
Public Attributes
boost::signals2::signal< void(const
ShipsListBox::SelectionSet &)> SelectedShipsChangedSignal
boost::signals2::signal< void(int)> ShipRightClickedSignal
Private Member Functions
void DoLayout ()
int GetShipIDOfListRow (GG::ListBox::iterator it) const
returns the ID number of the ship in row row_idx of the ships listbox
void ShipBrowsed (GG::ListBox::iterator it)
int ShipInRow (GG::ListBox::iterator it) const
void ShipRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void ShipSelectionChanged (const GG::ListBox::SelectionSet &rows)
void UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj)
Private Attributes
boost::signals2::connection m_fleet_connection
int m_fleet_id
bool m_order_issuing_enabled
ShipsListBox * m_ships_lb
Detailed Description
Used in lower half of FleetWnd to show the ships in a fleet, and some basic info about the fleet.
Constructor & Destructor Documentation
FleetDetailPanel::FleetDetailPanel (GG::X w, GG::Y h, int fleet_id, bool order_issuing_enabled, GG::Flags< GG::WndFlag > flags = GG::NO_WND_FLAGS)
References DoLayout(), GetUniverse(), INVALID_OBJECT_ID, m_order_issuing_enabled, m_ships_lb, SetFleet(), anonymous_namespace{ServerWrapper.cpp}::SetName(), anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING, ShipBrowsed(), ShipRightClicked(), ShipSelectionChanged(), and UniverseObjectDeleted().
Member Function Documentation
void FleetDetailPanel::DoLayout () private
References anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_ships_lb, and ShipsListBox::SizeMove().
Referenced by FleetDetailPanel(), and SizeMove().
void FleetDetailPanel::EnableOrderIssuing (bool enabled = true)
References ShipsListBox::EnableOrderIssuing(), m_order_issuing_enabled, and m_ships_lb.
Referenced by FleetWnd::EnableOrderIssuing().
int FleetDetailPanel::FleetID () const
References m_fleet_id.
Referenced by FleetWnd::UniverseObjectDeleted().
int FleetDetailPanel::GetShipIDOfListRow (GG::ListBox::iterator it) const private
returns the ID number of the ship in row row_idx of the ships listbox
void FleetDetailPanel::Refresh ()
References m_fleet_id, and SetFleet().
Referenced by FleetWnd::FleetSelectionChanged(), and SetFleet().
std::set< int > FleetDetailPanel::SelectedShipIDs () const
returns ids of ships selected in the detail panel's ShipsListBox
References ErrorLogger, INVALID_OBJECT_ID, and m_ships_lb.
Referenced by FleetWnd::SelectedShipIDs().
void FleetDetailPanel::SetFleet (int fleet_id)
sets the currently-displayed Fleet. setting to INVALID_OBJECT_ID shows no fleet
References DebugLogger, Fleet::Empty(), GetFleet(), INVALID_OBJECT_ID, m_fleet_connection, m_fleet_id, m_ships_lb, ShipsListBox::Refresh(), Refresh(), ShipsListBox::SetFleet(), and UniverseObject::StateChangedSignal.
Referenced by FleetDetailPanel(), FleetWnd::FleetSelectionChanged(), Refresh(), FleetWnd::UniverseObjectDeleted(), and UniverseObjectDeleted().
void FleetDetailPanel::SetSelectedShips (const std::set< int > & ship_ids)
sets the currently-selected ships in the ships list
References ErrorLogger, m_ships_lb, and ShipSelectionChanged().
Referenced by FleetWnd::CreateNewFleetFromDrops(), and FleetWnd::SetSelectedShips().
void FleetDetailPanel::ShipBrowsed (GG::ListBox::iterator it) private
Referenced by FleetDetailPanel().
int FleetDetailPanel::ShipInRow (GG::ListBox::iterator it) const private
References INVALID_OBJECT_ID, and m_ships_lb.
void FleetDetailPanel::ShipRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), Ship::DesignID(), boost::dynamic_pointer_cast(), ClientApp::EmpireID(), FlexibleFormat(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), GetFleet(), ClientUI::GetMapWnd(), MapWnd::GetModeratorActionSetting(), FleetWnd::GetNewFleetAggression(), GetShip(), GetShipDesign(), UniverseObject::ID(), ShipDesign::ID(), OrderSet::IssueOrder(), m_fleet_id, MAS_NoAction, UniverseObject::Name(), ShipDesign::Name(), Ship::OrderedScrapped(), ClientApp::Orders(), UniverseObject::OwnedBy(), anonymous_namespace{FleetWnd.cpp}::PendingScrapOrders(), OrderSet::RescindOrder(), CUIEditWnd::Result(), Fleet::ShipIDs(), ShipRightClickedSignal, UserString(), and ClientUI::ZoomToShipDesign().
Referenced by FleetDetailPanel().
void FleetDetailPanel::ShipSelectionChanged (const GG::ListBox::SelectionSet & rows) private
References ErrorLogger, m_ships_lb, ShipDataPanel::Select(), and SelectedShipsChangedSignal.
Referenced by FleetDetailPanel(), and SetSelectedShips().
void FleetDetailPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
References DoLayout().
Referenced by FleetWnd::DoLayout().
void FleetDetailPanel::UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj) private
References UniverseObject::ID(), INVALID_OBJECT_ID, m_fleet_id, and SetFleet().
Referenced by FleetDetailPanel().
Member Data Documentation
boost::signals2::connection FleetDetailPanel::m_fleet_connection private
Referenced by SetFleet().
int FleetDetailPanel::m_fleet_id private
Referenced by FleetID(), Refresh(), SetFleet(), ShipRightClicked(), and UniverseObjectDeleted().
bool FleetDetailPanel::m_order_issuing_enabled private
Referenced by EnableOrderIssuing(), and FleetDetailPanel().
ShipsListBox* FleetDetailPanel::m_ships_lb private
Referenced by DoLayout(), EnableOrderIssuing(), FleetDetailPanel(), SelectedShipIDs(), SetFleet(), SetSelectedShips(), ShipInRow(), and ShipSelectionChanged().
boost::signals2::signal<void (const ShipsListBox::SelectionSet&)> FleetDetailPanel::SelectedShipsChangedSignal mutable
emitted when the set of selected ships changes
Referenced by FleetWnd::Init(), and ShipSelectionChanged().
boost::signals2::signal<void (int)> FleetDetailPanel::ShipRightClickedSignal mutable
Referenced by FleetWnd::Init(), and ShipRightClicked().
The documentation for this class was generated from the following file:
FleetWnd.cpp