FreeOrion: XMLElement Class Reference
XMLElement Class Reference
Represents a simplified XML markup element.
#include <XMLDoc.h>
Classes
class Exception
The base class for XMLElement based exceptions.
class NoSuchChild
Thrown when a request for a tag-name named child element cannot be fulfilled.
class NoSuchIndex
Thrown when a request for an indexed child element cannot be fulfilled.
Public Types
Iterators
typedef std::vector
< XMLElement >::iterator child_iterator
Iterator to iterate over child XMLElements.
typedef std::vector
< XMLElement >::const_iterator const_child_iterator
Iterator to iterate over child XMLElements.
typedef std::map< std::string,
std::string >::iterator attr_iterator
Iterator to iterate over a XMLElement attributes.
typedef std::map< std::string,
std::string >::const_iterator const_attr_iterator
Iterator to iterate over a XMLElement attributes.
Public Member Functions
Accessors
const std::string & Tag () const
Returns the the tag-name of this XMLElement.
const std::string & Text () const
Returns the text body of this XMLElement.
int NumChildren () const
Returns the number of child nodes inside this XMLElement.
int NumAttributes () const
Returns the number of attributes attached to this XMLElement.
bool ContainsChild (const std::string &tag) const
Returns if this XMLElement contains a child with tag as tag-name.
bool ContainsAttribute (const std::string &key) const
Returns if this XMLElement contains an attribute with the attribute key key.
int ChildIndex (const std::string &tag) const
Returns the index of the first child XMLElement with tag as tag-name or -1 if none found.
const XMLElement & Child (unsigned int index) const
Returns the XMLElement child at the indexed position of the child list of this XMLElement.
const XMLElement & Child (const std::string &tag) const
Returns the first XMLElement child that has tag as tag-name.
const XMLElement & LastChild () const
Returns the last XMLElement child of this XMLElement.
const std::string & Attribute (const std::string &key) const
Returns the value of the attribute with name key or an empty string if there is no with attribute with this key.
std::ostream & WriteElement (std::ostream &os, int indent=0, bool whitespace=true) const
Write this XMLElement XML formatted into the given output stream os with indentation level indent when whitespace is set.
std::string WriteElement (int indent=0, bool whitespace=true) const
Return this XMLElement XML formatted as string with indentation level indent when whitespace is set.
const_child_iterator child_begin () const
Return an iterator to the first child in this XMLElement.
const_child_iterator child_end () const
Return an iterator to the one beyond last child in this XMLElement.
const_attr_iterator attr_begin () const
Return an iterator to the first attribute in this XMLElement.
const_attr_iterator attr_end () const
Return an iterator to the one beyond last attribute in this XMLElement.
Mutators
XMLElement & Child (unsigned int index)
Returns the XMLElement child at the indexed position of the child list of this XMLElement.
XMLElement & Child (const std::string &tag)
Returns the first XMLElement child that has tag as tag-name.
XMLElement & LastChild ()
Returns the last XMLElement child of this XMLElement.
void SetAttribute (const std::string &key, const std::string &value)
Sets the value of the attribute key in this XMLElement.
void SetTag (const std::string &tag)
Sets the tag-name of this XMLElement to tag.
void SetText (const std::string &text)
Sets the text content of this XMLEement to text.
void RemoveAttribute (const std::string &key)
Removes the attribute with key from this XMLElement.
void RemoveAttributes ()
Removes all attributes from this XMLElement.
void AppendChild (const XMLElement &child)
Adds a given child XMLElement child to the end of the child list of this XMLElement.
void AppendChild (const std::string &tag)
Creates an new empty XMLElement with the tag-name tag and appends it to the child list of this XMLElement.
void AddChildBefore (const XMLElement &child, unsigned int index)
Adds a given child XMLElement child before the child element at the indexed position in the child list of this XMLElement.
void RemoveChild (unsigned int index)
Removes the XMLElement child at the indexed position of the child list of this XMLElement.
void RemoveChild (const std::string &tag)
Removes the XMLElement child with the tag-name tag from this XMLElement.
void RemoveChildren ()
Removes all children from this XMLElement.
child_iterator child_begin ()
Return an iterator to the first child in this XMLElement.
child_iterator child_end ()
Return an iterator to the one beyond last child in this XMLElement.
attr_iterator attr_begin ()
Return an iterator to the first attribute in this XMLElement.
attr_iterator attr_end ()
Return an iterator to the one beyond last attribute in this XMLElement.
Private Attributes
std::map< std::string,
std::string > m_attributes
Stores the attributes associated to this XMLElement by key name mapping.
std::vector< XMLElement > m_children
Stores a list of the child XMLElements associated to this XMLElement.
bool m_root
Set to true if this XMLElement is the root element of an XMLDoc document.
std::string m_tag
Stores the tag-name associated to this XMLElement.
std::string m_text
Stores the text content associated to this XMLElement.
Friends
class XMLDoc
Structors
XMLElement ()
Creates a new XMLElement with an empty tag-name assigned.
XMLElement (const std::string &tag)
Creates a new XMLElement with the given tag tag-name.
XMLElement (const std::string &tag, const std::string &text)
Creates a new XMLElement with the given tag tag-name and text content.
XMLElement (const std::string &tag, const XMLElement &body)
Creates a new XMLElement with the given tag tag-name and body a single child element.
XMLElement (const std::string &tag, bool root)
Creates a new XMLElement with the given tag tag-name and marked as root node, if root is set.
Detailed Description
Represents a simplified XML markup element.
An XMLElement represents a XML element from the opening tag * <tag-name>, including its attributes to the corresponding closing tag </tag-name>. This may or may not include a text data section OR child XML elements.
Using the "burns" example:
<burns>Say <quote>Goodnight</quote> Gracie.</burns>
may not work as expected. The resulting XMLElement <burns> node will contain both the "Say " and the " Gracie." text fragment. Or represented differently:
burns.Text() == "Say  Gracie."
However, if used to represent data structures like the example struct foo:
struct foo
{
   int ref_ct;
   double data;
};
the current implementation creates a XML representation similar to:
<bar>
  <foo>
    <ref_ct>13<ref_ct/>
    <data>0.364951<data/>
  </foo>
</bar>
Further, while the "burns" example is standard XML, an XMLElement optionally accepts its single text string in quotes, and strips off trailing white space, in direct contrary to the XML standard. So "burns" from above is equivalent to:
<burns>"Say  Gracie."<quote>Goodnight</quote></burns>
or:
<burns>Say  Gracie.<quote>Goodnight</quote></burns>
or:
<burns>"Say  Gracie."
  <quote>Goodnight</quote>
</burns>
or:
<burns>Say  Gracie.
  <quote>Goodnight</quote>
</burns>
Each of these examples yields to
burns.Text() == "Say  Gracie."
When an XMLElement is saved, its text is saved within a CDATA section. Any string can be put inside one of these quoted text fields, even text that includes an arbitrary number of quotes. So any std::string or c-string can be assigned to an element. However, when hand-editing an XML file containing such text strings, one needs to be careful. The closing quote must be the last thing other than white space. Adding more than one quoted text string to the XML element, with each string separated by other elements, will result in a single concatenated string, as illustrated above.
This is not the most time- or space-efficient way to organize object data, but it may just be one of the simplest and most easily read.
Member Typedef Documentation
typedef std::map<std::string, std::string>::iterator XMLElement::attr_iterator
Iterator to iterate over a XMLElement attributes.
typedef std::vector<XMLElement>::iterator XMLElement::child_iterator
Iterator to iterate over child XMLElements.
typedef std::map<std::string, std::string>::const_iterator XMLElement::const_attr_iterator
Iterator to iterate over a XMLElement attributes.
typedef std::vector<XMLElement>::const_iterator XMLElement::const_child_iterator
Iterator to iterate over child XMLElements.
Constructor & Destructor Documentation
XMLElement::XMLElement () inline
Creates a new XMLElement with an empty tag-name assigned.
Create a new XMLElement with no tag-name, text, attribute or child nodes set. Also the new instance isn't marked as root node.
Referenced by AppendChild().
XMLElement::XMLElement (const std::string & tag) inline
Creates a new XMLElement with the given tag tag-name.
Create a new XMLElement with the given tag tag-name but no text, attribute or child nodes set. Also the new instance isn't marked as root node.
Parameters
[in] tag The tag name of this XML element.
XMLElement::XMLElement (const std::string & tag, const std::string & text) inline
Creates a new XMLElement with the given tag tag-name and text content.
Create a new XMLElement with the given tag tag-name and text content, but no attribute or child nodes set. Also the new instance isn't marked as root node.
Parameters
[in] tag The tag name of this XML element.
[in] text The text assigned to this XML element.
XMLElement::XMLElement (const std::string & tag, const XMLElement & body) inline
Creates a new XMLElement with the given tag tag-name and body a single child element.
Parameters
[in] tag The tag name of this XML element.
[in] body The child XML element assigned as body to this XML element.
XMLElement::XMLElement (const std::string & tag, bool root) private
Creates a new XMLElement with the given tag tag-name and marked as root node, if root is set.
Parameters
[in] tag The tag name of this XML element.
[in] root When true this XMLElement should be interpreted as root node in a XMLElement tree.
Note
Called by friend XMLDoc.
Member Function Documentation
void XMLElement::AddChildBefore (const XMLElement & child, unsigned int index)
Adds a given child XMLElement child before the child element at the indexed position in the child list of this XMLElement.
Parameters
[in] child The XMLElement to be inserted into the child list.
[in] index The index of the child XMLElement where the child put be in front of. The passed value must be between 0 and NumChildren() - 1.
Exceptions
XMLElement::NoSuchIndex When index is out of range in this XMLElement child list.
References m_children, and Tag().
void XMLElement::AppendChild (const XMLElement & child)
Adds a given child XMLElement child to the end of the child list of this XMLElement.
Parameters
[in] child The XMLElement to be appended to the child list.
References m_children.
Referenced by ClrToXML(), OptionsDB::GetXML(), and anonymous_namespace{SidePanel.cpp}::RotatingPlanetData::XMLEncode().
void XMLElement::AppendChild (const std::string & tag)
Creates an new empty XMLElement with the tag-name tag and appends it to the child list of this XMLElement.
Parameters
[in] tag The tag of the created XMLElement.
References m_children, and XMLElement().
XMLElement::const_attr_iterator XMLElement::attr_begin () const
Return an iterator to the first attribute in this XMLElement.
References m_attributes.
XMLElement::attr_iterator XMLElement::attr_begin ()
Return an iterator to the first attribute in this XMLElement.
References m_attributes.
XMLElement::const_attr_iterator XMLElement::attr_end () const
Return an iterator to the one beyond last attribute in this XMLElement.
References m_attributes.
XMLElement::attr_iterator XMLElement::attr_end ()
Return an iterator to the one beyond last attribute in this XMLElement.
References m_attributes.
const std::string & XMLElement::Attribute (const std::string & key) const
Returns the value of the attribute with name key or an empty string if there is no with attribute with this key.
Parameters
[in] key The attribute key of the searched attribute.
Returns
The value of the attribute with the key or an empty string if there is no such attribute.
References m_attributes.
Referenced by CreditsWnd::DrawCredits(), and XMLToClr().
const XMLElement & XMLElement::Child (unsigned int index) const
Returns the XMLElement child at the indexed position of the child list of this XMLElement.
Parameters
[in] index The index of the child XMLElement requested. The passed value must be between 0 and NumChildren() - 1.
Returns
A reference to the XMLElement child at the indexed position of this XMLElement child list.
Exceptions
XMLElement::NoSuchIndex When index is out of range in this XMLElement child list.
References m_children.
Referenced by anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::Atmosphere::Atmosphere(), CreditsWnd::DrawCredits(), EmpireColors(), anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetLightPosition(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), mainConfigOptionsSetup(), IntroScreen::OnCredits(), anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::PlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::RotatingPlanetData::RotatingPlanetData(), OptionsDB::SetFromXML(), OptionsDB::SetFromXMLRecursive(), and XMLToClr().
const XMLElement & XMLElement::Child (const std::string & tag) const
Returns the first XMLElement child that has tag as tag-name.
Parameters
[in] tag The tag-name of the child XMLElement requested.
Returns
A reference to the first XMLElement child which has the tag-name tag.
Exceptions
XMLElement::NoSuchChild When no child with a tag-name tag exists.
References m_children, m_tag, and Tag().
XMLElement & XMLElement::Child (unsigned int index)
Returns the XMLElement child at the indexed position of the child list of this XMLElement.
Parameters
[in] index The index of the child XMLElement requested. The passed value must be between 0 and NumChildren() - 1.
Returns
A reference to the XMLElement child at the indexed position of this XMLElement child list.
Exceptions
XMLElement::NoSuchIndex When index is out of range in this XMLElement child list.
References m_children.
XMLElement & XMLElement::Child (const std::string & tag)
Returns the first XMLElement child that has tag as tag-name.
Parameters
[in] tag The tag-name of the child XMLElement requested.
Returns
A reference to the first XMLElement child which has the tag-name tag.
Exceptions
XMLElement::NoSuchChild When no child with a tag-name tag exists.
References m_children, m_tag, and Tag().
XMLElement::const_child_iterator XMLElement::child_begin () const
Return an iterator to the first child in this XMLElement.
References m_children.
Referenced by anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), and anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::PlanetAtmosphereData().
XMLElement::child_iterator XMLElement::child_begin ()
Return an iterator to the first child in this XMLElement.
References m_children.
XMLElement::const_child_iterator XMLElement::child_end () const
Return an iterator to the one beyond last child in this XMLElement.
References m_children.
Referenced by anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), and anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::PlanetAtmosphereData().
XMLElement::child_iterator XMLElement::child_end ()
Return an iterator to the one beyond last child in this XMLElement.
References m_children.
int XMLElement::ChildIndex (const std::string & tag) const
Returns the index of the first child XMLElement with tag as tag-name or -1 if none found.
Parameters
[in] tag The tag-name of the searched child XMLElement.
Returns
The index of the first found child XMLElement with tag as tag-name or -1 of no such child XMLElement can be found.
References m_children, and m_tag.
Referenced by ContainsChild(), and RemoveChild().
bool XMLElement::ContainsAttribute (const std::string & key) const
Returns if this XMLElement contains an attribute with the attribute key key.
Parameters
[in] key The attribute key of the searched attribute.
Returns
True if there is an attribute with a key, false if not.
References m_attributes.
Referenced by CreditsWnd::DrawCredits(), and XMLToClr().
bool XMLElement::ContainsChild (const std::string & tag) const
Returns if this XMLElement contains a child with tag as tag-name.
Parameters
[in] tag The tag-name of the searched child XMLElement.
Returns
True if there is at least one child with a tag tag-name, false if not.
References ChildIndex().
Referenced by anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), mainConfigOptionsSetup(), IntroScreen::OnCredits(), and XMLToClr().
const XMLElement & XMLElement::LastChild () const
Returns the last XMLElement child of this XMLElement.
Returns
A reference to the last XMLElement child.
Exceptions
XMLElement:NoSuchIndex When there are no child XMLElements.
References m_children, and Tag().
XMLElement & XMLElement::LastChild ()
Returns the last XMLElement child of this XMLElement.
Returns
A reference to the last XMLElement child.
Exceptions
XMLElement:NoSuchIndex When there are no child XMLElements.
References m_children, and Tag().
int XMLElement::NumAttributes () const
Returns the number of attributes attached to this XMLElement.
Returns
The number of attributes attached to this XMLElement. Is always positive.
References m_attributes.
int XMLElement::NumChildren () const
Returns the number of child nodes inside this XMLElement.
Returns
The number of child XMLElements contained by this this XMLElement. Is always positive.
References m_children.
Referenced by CreditsWnd::DrawCredits(), EmpireColors(), anonymous_namespace{SidePanel.cpp}::GetStarLightColors(), OptionsDB::SetFromXML(), and OptionsDB::SetFromXMLRecursive().
void XMLElement::RemoveAttribute (const std::string & key)
Removes the attribute with key from this XMLElement.
Parameters
[in] key The key of the attribute to be deleted. If no such attribute exist no action is taken.
References m_attributes.
void XMLElement::RemoveAttributes ()
Removes all attributes from this XMLElement.
References m_attributes.
void XMLElement::RemoveChild (unsigned int index)
Removes the XMLElement child at the indexed position of the child list of this XMLElement.
Parameters
[in] index The index of the child XMLElement that should be removed. The passed value must be between 0 and NumChildren() - 1.
Exceptions
XMLElement::NoSuchIndex When index is out of range in this XMLElement child list.
References m_children, and Tag().
void XMLElement::RemoveChild (const std::string & tag)
Removes the XMLElement child with the tag-name tag from this XMLElement.
Parameters
[in] tag The tag-name of the child XMLElement to be deleted.
Exceptions
XMLElement::NoSuchChild When no child with a tag-name tag exists.
References ChildIndex(), m_children, and Tag().
void XMLElement::RemoveChildren ()
Removes all children from this XMLElement.
References m_children.
void XMLElement::SetAttribute (const std::string & key, const std::string & value)
Sets the value of the attribute key in this XMLElement.
When the attribute key already has a value set it will be overwritten with the new value.
Parameters
[in] key The key of the attribute to set.
[in] value The new value the attribute should be set to.
References m_attributes.
Referenced by XMLDoc::AddAttribute().
void XMLElement::SetTag (const std::string & tag)
Sets the tag-name of this XMLElement to tag.
Parameters
[in] tag The new tag-name this XMLElement should have.
References m_tag.
void XMLElement::SetText (const std::string & text)
Sets the text content of this XMLEement to text.
Parameters
[in] text The new text content this XMLElement should have.
References m_text.
Referenced by OptionsDB::GetXML().
const std::string & XMLElement::Tag () const
Returns the the tag-name of this XMLElement.
Returns
The tag-name of this XMLElement. Can be an empty string.
References m_tag.
Referenced by AddChildBefore(), anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::Atmosphere::Atmosphere(), Child(), CreditsWnd::DrawCredits(), OptionsDB::GetXML(), LastChild(), anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::PlanetAtmosphereData(), RemoveChild(), anonymous_namespace{SidePanel.cpp}::RotatingPlanetData::RotatingPlanetData(), and OptionsDB::SetFromXMLRecursive().
const std::string & XMLElement::Text () const
Returns the text body of this XMLElement.
Returns
The text content of this XMLElement. Can be an empty string.
References m_text.
Referenced by anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::Atmosphere::Atmosphere(), anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS(), anonymous_namespace{SidePanel.cpp}::GetLightPosition(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity(), anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity(), mainConfigOptionsSetup(), anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::PlanetAtmosphereData(), anonymous_namespace{SidePanel.cpp}::RotatingPlanetData::RotatingPlanetData(), OptionsDB::SetFromXMLRecursive(), and XMLToClr().
std::ostream & XMLElement::WriteElement (std::ostream & os, int indent = 0, bool whitespace = true) const
Write this XMLElement XML formatted into the given output stream os with indentation level indent when whitespace is set.
Parameters
[in] os The output stream this document should be written to.
[in] indent The indentation level this element should be indented.
[in] whitespace If set to true the child XMLElements are indented and newline separated.
Returns
The given os output stream.
References if(), anonymous_namespace{XMLDoc.cpp}::INDENT_STR, m_attributes, m_children, m_root, m_tag, and m_text.
Referenced by XMLDoc::WriteDoc(), and WriteElement().
std::string XMLElement::WriteElement (int indent = 0, bool whitespace = true) const
Return this XMLElement XML formatted as string with indentation level indent when whitespace is set.
Parameters
[in] indent The indentation level this element should be indented.
[in] whitespace If set to true the child XMLElements are indented and newline separated.
Returns
A string containing the XML formatted representation of this XMLElement.
References WriteElement().
Friends And Related Function Documentation
friend class XMLDoc friend
Member Data Documentation
std::map<std::string, std::string> XMLElement::m_attributes private
Stores the attributes associated to this XMLElement by key name mapping.
Referenced by attr_begin(), attr_end(), Attribute(), ContainsAttribute(), NumAttributes(), RemoveAttribute(), RemoveAttributes(), SetAttribute(), and WriteElement().
std::vector<XMLElement> XMLElement::m_children private
Stores a list of the child XMLElements associated to this XMLElement.
This list can be empty when this XMLElement has no associated child elements.
Referenced by AddChildBefore(), AppendChild(), Child(), child_begin(), child_end(), ChildIndex(), LastChild(), NumChildren(), RemoveChild(), RemoveChildren(), and WriteElement().
bool XMLElement::m_root private
Set to true if this XMLElement is the root element of an XMLDoc document.
Referenced by WriteElement().
std::string XMLElement::m_tag private
Stores the tag-name associated to this XMLElement.
Bug:
Currently this can contain an empty string but I doubt it will be useful as it will cause invalid XML documents serializations.
Referenced by Child(), ChildIndex(), SetTag(), Tag(), and WriteElement().
std::string XMLElement::m_text private
Stores the text content associated to this XMLElement.
Referenced by SetText(), Text(), and WriteElement().
The documentation for this class was generated from the following files:
XMLDoc.h
XMLDoc.cpp