FreeOrion: CUILinkTextBlock::Factory Class Reference
CUILinkTextBlock::Factory Class Reference
#include <CUILinkTextBlock.h>
Public Member Functions
virtual GG::BlockControl * CreateFromTag (const std::string &tag, const GG::RichText::TAG_PARAMS &params, const std::string &content, const boost::shared_ptr< GG::Font > &font, const GG::Clr &color, GG::Flags< GG::TextFormat > format)
link clicked signals: first string is the link type, second string is the specific item clicked
Public Attributes
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkDoubleClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkRightClickedSignal
Member Function Documentation
GG::BlockControl * CUILinkTextBlock::Factory::CreateFromTag (const std::string & tag, const GG::RichText::TAG_PARAMS & params, const std::string & content, const boost::shared_ptr< GG::Font > & font, const GG::Clr & color, GG::Flags< GG::TextFormat > format) virtual
link clicked signals: first string is the link type, second string is the specific item clicked
Creates a control from the tag (with unparsed parameters) and the content between the tags. You own the returned control.
References CUILinkTextBlock::CUILinkTextBlock(), TextLinker::LinkClickedSignal, TextLinker::LinkDoubleClickedSignal, TextLinker::LinkRightClickedSignal, CUILinkTextBlock::m_link_text, VarText::PLANET_ID_TAG, TextLinker::SetDecorator(), and VarText::SHIP_ID_TAG.
Member Data Documentation
boost::signals2::signal<void (const std::string&, const std::string&)> CUILinkTextBlock::Factory::LinkClickedSignal mutable
Referenced by EncyclopediaDetailPanel::EncyclopediaDetailPanel().
boost::signals2::signal<void (const std::string&, const std::string&)> CUILinkTextBlock::Factory::LinkDoubleClickedSignal mutable
Referenced by EncyclopediaDetailPanel::EncyclopediaDetailPanel().
boost::signals2::signal<void (const std::string&, const std::string&)> CUILinkTextBlock::Factory::LinkRightClickedSignal mutable
Referenced by EncyclopediaDetailPanel::EncyclopediaDetailPanel().
The documentation for this class was generated from the following files:
CUILinkTextBlock.h
CUILinkTextBlock.cpp