FreeOrion: TechTreeWnd::LayoutPanel::LayoutSurface Class Reference
TechTreeWnd::LayoutPanel::LayoutSurface Class Reference
Public Member Functions
LayoutSurface ()
virtual void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys)
Public Attributes
boost::signals2::signal< void(const
GG::Pt &)> ButtonDownSignal
boost::signals2::signal< void(const
GG::Pt &)> ButtonUpSignal
boost::signals2::signal< void(const
GG::Pt &)> DraggedSignal
boost::signals2::signal< void(int)> ZoomedSignal
Constructor & Destructor Documentation
TechTreeWnd::LayoutPanel::LayoutSurface::LayoutSurface () inline
Member Function Documentation
virtual void TechTreeWnd::LayoutPanel::LayoutSurface::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline virtual
References ButtonDownSignal.
virtual void TechTreeWnd::LayoutPanel::LayoutSurface::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) inline virtual
References ButtonUpSignal.
virtual void TechTreeWnd::LayoutPanel::LayoutSurface::LDrag (const GG::Pt & pt, const GG::Pt & move, GG::Flags< GG::ModKey > mod_keys) inline virtual
References DraggedSignal.
virtual void TechTreeWnd::LayoutPanel::LayoutSurface::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) inline virtual
References ZoomedSignal.
Member Data Documentation
boost::signals2::signal<void (const GG::Pt&)> TechTreeWnd::LayoutPanel::LayoutSurface::ButtonDownSignal mutable
Referenced by TechTreeWnd::LayoutPanel::LayoutPanel(), and LButtonDown().
boost::signals2::signal<void (const GG::Pt&)> TechTreeWnd::LayoutPanel::LayoutSurface::ButtonUpSignal mutable
Referenced by TechTreeWnd::LayoutPanel::LayoutPanel(), and LButtonUp().
boost::signals2::signal<void (const GG::Pt&)> TechTreeWnd::LayoutPanel::LayoutSurface::DraggedSignal mutable
Referenced by TechTreeWnd::LayoutPanel::LayoutPanel(), and LDrag().
boost::signals2::signal<void (int)> TechTreeWnd::LayoutPanel::LayoutSurface::ZoomedSignal mutable
Referenced by TechTreeWnd::LayoutPanel::LayoutPanel(), and MouseWheel().
The documentation for this class was generated from the following file:
TechTreeWnd.cpp