FreeOrion: Message Class Reference
Message Class Reference
#include <Message.h>
Public Types
typedef std::array< int, 5 > HeaderBuffer
Public Member Functions
GG_CLASS_ENUM (MessageType, UNDEFINED=0, DEBUG, ERROR_MSG, HOST_SP_GAME, HOST_MP_GAME, JOIN_GAME, HOST_ID, LOBBY_UPDATE, LOBBY_CHAT, LOBBY_EXIT, START_MP_GAME, SAVE_GAME_INITIATE, SAVE_GAME_DATA_REQUEST, SAVE_GAME_COMPLETE, LOAD_GAME, GAME_START, TURN_UPDATE, TURN_PARTIAL_UPDATE, TURN_ORDERS, TURN_PROGRESS, PLAYER_STATUS, CLIENT_SAVE_DATA, PLAYER_CHAT, DIPLOMACY, DIPLOMATIC_STATUS, REQUEST_NEW_OBJECT_ID, DISPATCH_NEW_OBJECT_ID, REQUEST_NEW_DESIGN_ID, DISPATCH_NEW_DESIGN_ID, END_GAME, AI_END_GAME_ACK, MODERATOR_ACTION, SHUT_DOWN_SERVER, REQUEST_SAVE_PREVIEWS, DISPATCH_SAVE_PREVIEWS, REQUEST_COMBAT_LOGS, DISPATCH_COMBAT_LOGS) GG_CLASS_ENUM(TurnProgressPhase
STARTING_AIS GG_CLASS_ENUM (PlayerStatus, PLAYING_TURN, RESOLVING_COMBAT, WAITING) GG_CLASS_ENUM(EndGameReason
< creating AI clients
Structors
Message ()
Message (MessageType message_type, int sending_player, int receiving_player, const std::string &text, bool synchronous_response=false)
Accessors
MessageType Type () const
Returns the type of the message.
int SendingPlayer () const
Returns the ID of the sending player.
int ReceivingPlayer () const
Returns the ID of the receiving player.
bool SynchronousResponse () const
Returns true if this message is in reponse to a synchronous message.
std::size_t Size () const
Returns the size of the underlying buffer.
const char * Data () const
Returns the underlying buffer.
std::string Text () const
Returns the underlying buffer as a std::string.
void Resize (std::size_t size)
Resizes the underlying char buffer to size uninitialized bytes.
char * Data ()
Returns the underlying buffer.
void Swap (Message &rhs)
Swaps the contents of *this with rhs. Does not throw.
Public Attributes
COLONIZE_AND_SCRAP
enacting colonization and scrapping orders
COMBAT
combat turn progress message
DOWNLOADING
downloading new game state from server
EMPIRE_PRODUCTION
empire production turn progress message
FLEET_MOVEMENT
fleet movement turn progress message
GENERATING_UNIVERSE
creating new universe
LOADING_GAME
loading gamestate from save
STARTING_AIS LOCAL_CLIENT_DISCONNECT
the local player's client networking detected a disconnection from the server
STARTING_AIS PLAYER_DISCONNECT
an active player (not an observer) was disconnected
PROCESSING_ORDERS
processing orders
WAITING_FOR_PLAYERS
waiting for other to end their turn
Static Public Attributes
static constexpr size_t HeaderBufferSize
Private Attributes
int m_message_size
boost::shared_array< char > m_message_text
int m_receiving_player
int m_sending_player
bool m_synchronous_response
MessageType m_type
Friends
FO_COMMON_API void BufferToHeader (const HeaderBuffer &, Message &)
Detailed Description
Encapsulates a variable-length char buffer containing a message to be passed among the server and one or more clients. Note that std::string is often thread unsafe on many platforms, so a dynamically allocated char array is used instead. (It was feared that using another STL container of char might misbehave as well.)
Member Typedef Documentation
typedef std::array<int, 5> Message::HeaderBuffer
Constructor & Destructor Documentation
Message::Message ()
Referenced by AIEndGameAcknowledgeMessage(), ClientSaveDataMessage(), DiplomacyMessage(), DiplomaticStatusMessage(), DispatchCombatLogsMessage(), DispatchDesignIDMessage(), DispatchObjectIDMessage(), DispatchSavePreviewsMessage(), EndGameMessage(), ErrorMessage(), GameStartMessage(), GlobalChatMessage(), HostIDMessage(), HostMPAckMessage(), HostMPGameMessage(), HostSaveGameInitiateMessage(), HostSPAckMessage(), HostSPGameMessage(), JoinAckMessage(), JoinGameMessage(), LobbyChatMessage(), LobbyUpdateMessage(), ModeratorActionMessage(), PlayerStatusMessage(), RequestCombatLogsMessage(), RequestNewDesignIDMessage(), RequestNewObjectIDMessage(), RequestSavePreviewsMessage(), ServerLobbyChatMessage(), ServerLobbyUpdateMessage(), ServerSaveGameCompleteMessage(), ServerSaveGameDataRequestMessage(), ShutdownServerMessage(), SingleRecipientChatMessage(), StartMPGameMessage(), TurnOrdersMessage(), TurnPartialUpdateMessage(), TurnProgressMessage(), and TurnUpdateMessage().
Message::Message (MessageType message_type, int sending_player, int receiving_player, const std::string & text, bool synchronous_response = false)
References m_message_text.
Member Function Documentation
const char * Message::Data () const
Returns the underlying buffer.
References m_message_text.
Referenced by ClientNetworking::Impl::HandleMessageHeaderRead(), PlayerConnection::HandleMessageHeaderRead(), and PlayerConnection::SyncWriteMessage().
char * Message::Data ()
Returns the underlying buffer.
References m_message_text.
Message::GG_CLASS_ENUM (MessageType , UNDEFINED = 0, DEBUG , ERROR_MSG , HOST_SP_GAME , HOST_MP_GAME , JOIN_GAME , HOST_ID , LOBBY_UPDATE , LOBBY_CHAT , LOBBY_EXIT , START_MP_GAME , SAVE_GAME_INITIATE , SAVE_GAME_DATA_REQUEST , SAVE_GAME_COMPLETE , LOAD_GAME , GAME_START , TURN_UPDATE , TURN_PARTIAL_UPDATE , TURN_ORDERS , TURN_PROGRESS , PLAYER_STATUS , CLIENT_SAVE_DATA , PLAYER_CHAT , DIPLOMACY , DIPLOMATIC_STATUS , REQUEST_NEW_OBJECT_ID , DISPATCH_NEW_OBJECT_ID , REQUEST_NEW_DESIGN_ID , DISPATCH_NEW_DESIGN_ID , END_GAME , AI_END_GAME_ACK , MODERATOR_ACTION , SHUT_DOWN_SERVER , REQUEST_SAVE_PREVIEWS , DISPATCH_SAVE_PREVIEWS , REQUEST_COMBAT_LOGS , DISPATCH_COMBAT_LOGS)
Represents the type of the message
STARTING_AIS Message::GG_CLASS_ENUM (PlayerStatus , PLAYING_TURN , RESOLVING_COMBAT , WAITING)
< creating AI clients
int Message::ReceivingPlayer () const
Returns the ID of the receiving player.
References m_receiving_player.
Referenced by AIClientApp::HandleMessage(), HeaderToBuffer(), operator<<(), operator==(), MPLobby::react(), and ServerNetworking::SendMessage().
void Message::Resize (std::size_t size)
Resizes the underlying char buffer to size uninitialized bytes.
References m_message_size, and m_message_text.
Referenced by ClientNetworking::Impl::HandleMessageHeaderRead(), and PlayerConnection::HandleMessageHeaderRead().
int Message::SendingPlayer () const
Returns the ID of the sending player.
References m_sending_player.
Referenced by AIClientApp::HandleMessage(), ServerApp::HandleMessage(), PlayerConnection::HandleMessageBodyRead(), HeaderToBuffer(), operator<<(), operator==(), MPLobby::react(), PlayingGame::react(), WaitingForTurnEnd::react(), WaitingForTurnEndIdle::react(), WaitingForSaveData::react(), and ShuttingDownServer::react().
std::size_t Message::Size () const
Returns the size of the underlying buffer.
References m_message_size.
Referenced by PlayerConnection::HandleMessageBodyRead(), ClientNetworking::Impl::HandleMessageHeaderRead(), PlayerConnection::HandleMessageHeaderRead(), HeaderToBuffer(), and PlayerConnection::SyncWriteMessage().
void Message::Swap (Message & rhs)
Swaps the contents of *this with rhs. Does not throw.
References m_message_size, m_message_text, m_receiving_player, m_sending_player, m_synchronous_response, m_type, and swap().
Referenced by swap().
bool Message::SynchronousResponse () const
Returns true if this message is in reponse to a synchronous message.
References m_synchronous_response.
Referenced by HeaderToBuffer(), and anonymous_namespace{MessageQueue.cpp}::SynchronousResponseMessage::operator()().
std::string Message::Text () const
Returns the underlying buffer as a std::string.
References m_message_size, and m_message_text.
Referenced by ExtractClientSaveDataMessageData(), ExtractDiplomacyMessageData(), ExtractDiplomaticStatusMessageData(), ExtractDispatchCombatLogsMessageData(), ExtractDispatchSavePreviewsMessageData(), ExtractEndGameMessageData(), ExtractErrorMessageData(), ExtractGameStartMessageData(), ExtractHostMPGameMessageData(), ExtractHostSPGameMessageData(), ExtractJoinGameMessageData(), ExtractLobbyUpdateMessageData(), ExtractModeratorActionMessageData(), ExtractPlayerStatusMessageData(), ExtractRequestCombatLogsMessageData(), ExtractRequestSavePreviewsMessageData(), ExtractServerSaveGameCompleteMessageData(), ExtractTurnOrdersMessageData(), ExtractTurnPartialUpdateMessageData(), ExtractTurnProgressMessageData(), ExtractTurnUpdateMessageData(), ClientApp::GetNewDesignID(), ClientApp::GetNewObjectID(), AIClientApp::HandleMessage(), HumanClientApp::HandleSystemEvents(), operator<<(), operator==(), MPLobby::react(), and WaitingForTurnEndIdle::react().
Message::MessageType Message::Type () const
Returns the type of the message.
References m_type.
Referenced by AIClientApp::HandleMessage(), HumanClientApp::HandleMessage(), ServerApp::HandleMessage(), PlayerConnection::HandleMessageBodyRead(), ServerApp::HandleNonPlayerMessage(), HumanClientApp::HandleSystemEvents(), HeaderToBuffer(), operator<<(), operator==(), and HumanClientApp::RequestSavePreviews().
Friends And Related Function Documentation
FO_COMMON_API void BufferToHeader (const HeaderBuffer & , Message &) friend
Fills in the relevant portions of message with the values in the buffer buffer.
Member Data Documentation
Message::COLONIZE_AND_SCRAP
enacting colonization and scrapping orders
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::PreCombatProcessTurns().
Message::COMBAT
combat turn progress message
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::ProcessCombats().
Message::DOWNLOADING
downloading new game state from server
Referenced by MessageWnd::HandleTurnPhaseUpdate(), ServerApp::PostCombatProcessTurns(), ServerApp::PreCombatProcessTurns(), and PlayingGame::react().
Message::EMPIRE_PRODUCTION
empire production turn progress message
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::PostCombatProcessTurns().
Message::FLEET_MOVEMENT
fleet movement turn progress message
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::PreCombatProcessTurns().
Message::GENERATING_UNIVERSE
creating new universe
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::NewGameInitConcurrentWithJoiners().
constexpr size_t Message::HeaderBufferSize static
Initial value:
=
        std::tuple_size<HeaderBuffer>::value * sizeof(HeaderBuffer::value_type)
Referenced by ClientNetworking::Impl::HandleMessageHeaderRead(), PlayerConnection::HandleMessageHeaderRead(), and ClientNetworking::Impl::HandleMessageWrite().
Message::LOADING_GAME
loading gamestate from save
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and LoadGame().
STARTING_AIS Message::LOCAL_CLIENT_DISCONNECT
the local player's client networking detected a disconnection from the server
Referenced by PlayingGame::react().
int Message::m_message_size private
Referenced by BufferToHeader(), Resize(), Size(), Swap(), and Text().
boost::shared_array<char> Message::m_message_text private
Referenced by Data(), Message(), Resize(), Swap(), and Text().
int Message::m_receiving_player private
Referenced by BufferToHeader(), ReceivingPlayer(), and Swap().
int Message::m_sending_player private
Referenced by BufferToHeader(), SendingPlayer(), and Swap().
bool Message::m_synchronous_response private
Referenced by BufferToHeader(), Swap(), and SynchronousResponse().
MessageType Message::m_type private
Referenced by BufferToHeader(), Swap(), and Type().
STARTING_AIS Message::PLAYER_DISCONNECT
an active player (not an observer) was disconnected
Referenced by ServerApp::CleanupAIs(), ServerFSM::HandleNonLobbyDisconnection(), PlayingGame::react(), and ShuttingDownServer::ShuttingDownServer().
Message::PROCESSING_ORDERS
processing orders
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and ServerApp::PreCombatProcessTurns().
Message::WAITING_FOR_PLAYERS
waiting for other to end their turn
Referenced by MessageWnd::HandleTurnPhaseUpdate(), and WaitingForTurnEnd::react().
The documentation for this class was generated from the following files:
Message.h
Message.cpp