FreeOrion: PopulationPool Class Reference
PopulationPool Class Reference
#include <ResourcePool.h>
Public Member Functions
Structors
PopulationPool ()
Accessors
const std::vector< int > & PopCenterIDs () const
returns the PopCenter vector
float Population () const
returns current total population
float Growth () const
returns predicted growth for next turn
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
float m_growth
total predicted population growth for next turn for all PopCenters in pool
std::vector< int > m_pop_center_ids
UniverseObject ids of PopCenters that contribute to the pool.
float m_population
total population of all PopCenters in pool
Friends
class boost::serialization::access
Mutators
boost::signals2::signal< void()> ChangedSignal
void SetPopCenters (const std::vector< int > &pop_center_ids)
void Update ()
recalculates total population and growth
Detailed Description
The PopulationPool class keeps track of an empire's total population and its growth.
Constructor & Destructor Documentation
PopulationPool::PopulationPool ()
Member Function Documentation
float PopulationPool::Growth () const
returns predicted growth for next turn
References m_growth.
const std::vector<int>& PopulationPool::PopCenterIDs () const inline
returns the PopCenter vector
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), and MapWnd::RefreshPopulationIndicator().
float PopulationPool::Population () const
returns current total population
References m_population.
Referenced by Empire::Population(), and MapWnd::RefreshPopulationIndicator().
template<class Archive > void PopulationPool::serialize (Archive & ar, const unsigned int version) private
References m_pop_center_ids.
void PopulationPool::SetPopCenters (const std::vector< int > & pop_center_ids)
emitted after updating population and growth numbers
References m_pop_center_ids.
Referenced by Empire::Eliminate(), and Empire::InitResourcePools().
void PopulationPool::Update ()
recalculates total population and growth
References ChangedSignal, GetPopCenter(), m_growth, m_pop_center_ids, m_population, and METER_POPULATION.
Referenced by Empire::UpdatePopulationGrowth().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
boost::signals2::signal<void ()> PopulationPool::ChangedSignal mutable
emitted after updating population and growth numbers
Referenced by MapWnd::InitTurn(), and Update().
float PopulationPool::m_growth private
total predicted population growth for next turn for all PopCenters in pool
Referenced by Growth(), and Update().
std::vector<int> PopulationPool::m_pop_center_ids private
UniverseObject ids of PopCenters that contribute to the pool.
Referenced by serialize(), SetPopCenters(), and Update().
float PopulationPool::m_population private
total population of all PopCenters in pool
Referenced by Population(), and Update().
The documentation for this class was generated from the following files:
ResourcePool.h
ResourcePool.cpp