FreeOrion: HotkeyManager Class Reference
HotkeyManager Class Reference
#include <Hotkeys.h>
Classes
struct ConditionalConnection
Public Member Functions
~HotkeyManager ()
template<class T , class R >
void Connect (T *instance, R(T::*member)(), const std::string &name, HotkeyCondition *cond=nullptr)
Connects a named shortcut to the target slot in the target instance.
void Connect (boost::function< bool()> func, const std::string &name, HotkeyCondition *cond=nullptr)
void RebuildShortcuts ()
Static Public Member Functions
static HotkeyManager * GetManager ()
Returns the singleton instance.
Private Types
typedef std::list
< ConditionalConnection > ConditionalConnectionList
typedef std::map< std::string,
ConditionalConnectionList > Connections
Private Member Functions
HotkeyManager ()
void AddConditionalConnection (const std::string &name, const boost::signals2::connection &conn, HotkeyCondition *cond)
Add the given conditional connection.
GG::GUI::AcceleratorSignalType & NamedSignal (const std::string &name)
bool ProcessNamedShortcut (const std::string &name, GG::Key key, GG::Flags< GG::ModKey > mod)
The shortcut processing function. Passed using boost::bind.
Private Attributes
Connections m_connections
A set of connected shortcuts.
std::set
< boost::signals2::connection > m_internal_connections
std::map< std::string,
GG::GUI::AcceleratorSignalType * > m_signals
Static Private Attributes
static HotkeyManager * s_singleton = nullptr
Member Typedef Documentation
typedef std::list<ConditionalConnection> HotkeyManager::ConditionalConnectionList private
typedef std::map<std::string, ConditionalConnectionList> HotkeyManager::Connections private
Constructor & Destructor Documentation
HotkeyManager::~HotkeyManager ()
HotkeyManager::HotkeyManager () private
Referenced by GetManager().
Member Function Documentation
void HotkeyManager::AddConditionalConnection (const std::string & name, const boost::signals2::connection & conn, HotkeyCondition * cond) private
Add the given conditional connection.
References m_connections.
Referenced by Connect().
template<class T , class R > void HotkeyManager::Connect (T * instance, R(T::*)() member, const std::string & name, HotkeyCondition * cond = nullptr) inline
Connects a named shortcut to the target slot in the target instance.
References AddConditionalConnection(), and NamedSignal().
Referenced by HumanClientApp::ConnectKeyboardAcceleratorSignals(), MapWnd::ConnectKeyboardAcceleratorSignals(), and TechTreeWnd::LayoutPanel::ConnectKeyboardAcceleratorSignals().
void HotkeyManager::Connect (boost::function< bool()> func, const std::string & name, HotkeyCondition * cond = nullptr) inline
References AddConditionalConnection(), and NamedSignal().
HotkeyManager * HotkeyManager::GetManager () static
Returns the singleton instance.
References HotkeyManager(), and s_singleton.
Referenced by HumanClientApp::ConnectKeyboardAcceleratorSignals(), MapWnd::ConnectKeyboardAcceleratorSignals(), TechTreeWnd::LayoutPanel::ConnectKeyboardAcceleratorSignals(), anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption(), and anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption().
GG::GUI::AcceleratorSignalType & HotkeyManager::NamedSignal (const std::string & name) private
Returns the signal for the given named accelerator, creating it if necessary.
Unsure why GG::AcceleratorSignal implementation uses shared pointers. Maybe I should, too ?
References m_signals.
Referenced by Connect().
bool HotkeyManager::ProcessNamedShortcut (const std::string & name, GG::Key key, GG::Flags< GG::ModKey > mod) private
The shortcut processing function. Passed using boost::bind.
References Hotkey::IsTypingSafe(), m_connections, and m_signals.
Referenced by RebuildShortcuts().
void HotkeyManager::RebuildShortcuts ()
Rebuilds all shortcuts/connections. Should be called again at the end of every function that registers new connections (just once, though cause calling it every time would get expensive), and every time as well a shortcut is changed.
Todo:
Disable the shortcuts that we've enabled so far ? Is it really necessary ? An unconnected signal should simply be ignored.
References m_connections, m_internal_connections, Hotkey::m_key, Hotkey::m_mod_keys, Hotkey::m_name, Hotkey::NamedHotkey(), and ProcessNamedShortcut().
Referenced by HumanClientApp::ConnectKeyboardAcceleratorSignals(), MapWnd::ConnectKeyboardAcceleratorSignals(), TechTreeWnd::LayoutPanel::ConnectKeyboardAcceleratorSignals(), anonymous_namespace{OptionsWnd.cpp}::HandleResetHotkeyOption(), and anonymous_namespace{OptionsWnd.cpp}::HandleSetHotkeyOption().
Member Data Documentation
Connections HotkeyManager::m_connections private
A set of connected shortcuts.
Referenced by AddConditionalConnection(), ProcessNamedShortcut(), and RebuildShortcuts().
std::set<boost::signals2::connection> HotkeyManager::m_internal_connections private
Referenced by RebuildShortcuts().
std::map<std::string, GG::GUI::AcceleratorSignalType*> HotkeyManager::m_signals private
Referenced by NamedSignal(), and ProcessNamedShortcut().
HotkeyManager * HotkeyManager::s_singleton = nullptr static private
Referenced by GetManager().
The documentation for this class was generated from the following files:
Hotkeys.h
Hotkeys.cpp