FreeOrion: TechTreeArcsImplementation Class Reference
TechTreeArcsImplementation Class Reference
Public Member Functions
TechTreeArcsImplementation (const TechTreeLayout &layout, const std::set< std::string > &techs_to_show)
void RefreshHighlights ()
void Render (double scale)
Private Member Functions
void FillArcBuffer (GG::GL2DVertexBuffer &buffer, const std::set< std::string > &techs)
Private Attributes
GG::GL2DVertexBuffer m_buffer
std::map< std::string,
std::set< std::string > > m_edges_to_show
GG::GL2DVertexBuffer m_highlight_buffer
const TechTreeLayout & m_layout
Constructor & Destructor Documentation
TechTreeArcsImplementation::TechTreeArcsImplementation (const TechTreeLayout & layout, const std::set< std::string > & techs_to_show) inline
References FillArcBuffer(), m_buffer, and RefreshHighlights().
Member Function Documentation
void TechTreeArcsImplementation::FillArcBuffer (GG::GL2DVertexBuffer & buffer, const std::set< std::string > & techs) inline private
Fills buffer with the ends points for the lines that connect technologies in techs
References ErrorLogger, TechTreeLayout::GetOutEdges(), AIInterface::GetTech(), m_edges_to_show, and m_layout.
Referenced by RefreshHighlights(), and TechTreeArcsImplementation().
void TechTreeArcsImplementation::RefreshHighlights () inline
References AIInterface::EmpireID(), FillArcBuffer(), HumanClientApp::GetApp(), GetEmpire(), ResearchQueue::InQueue(), ResearchQueue::insert(), m_edges_to_show, and m_highlight_buffer.
Referenced by TechTreeArcsImplementation().
void TechTreeArcsImplementation::Render (double scale) inline
References anonymous_namespace{TechTreeArcs.cpp}::ARC_THICKNESS, m_buffer, and m_highlight_buffer.
Referenced by TechTreeArcs::Render().
Member Data Documentation
GG::GL2DVertexBuffer TechTreeArcsImplementation::m_buffer private
Referenced by Render(), and TechTreeArcsImplementation().
std::map<std::string, std::set<std::string> > TechTreeArcsImplementation::m_edges_to_show private
Referenced by FillArcBuffer(), and RefreshHighlights().
GG::GL2DVertexBuffer TechTreeArcsImplementation::m_highlight_buffer private
Referenced by RefreshHighlights(), and Render().
const TechTreeLayout& TechTreeArcsImplementation::m_layout private
Referenced by FillArcBuffer().
The documentation for this class was generated from the following file:
TechTreeArcs.cpp