FreeOrion: SpecialsPanel Class Reference
SpecialsPanel Class Reference
#include <SpecialsPanel.h>
Public Member Functions
Structors
SpecialsPanel (GG::X w, int object_id)
Accessors
bool InWindow (const GG::Pt &pt) const override
int ObjectID () const
Mutators
void Render () override
regenerates indicators according specials on object
void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys) override
regenerates indicators according specials on object
void SizeMove (const GG::Pt &ul, const GG::Pt &lr) override
regenerates indicators according specials on object
bool EventFilter (GG::Wnd *w, const GG::WndEvent &event) override
regenerates indicators according specials on object
void Update ()
regenerates indicators according specials on object
Private Member Functions
void SpecialRightClicked (const std::string &name)
Private Attributes
std::map< std::string, StatisticIcon * > m_icons
int m_object_id
id for the Object whose specials this panel displays
Detailed Description
Displays a set of specials attached to an UniverseObject
Constructor & Destructor Documentation
SpecialsPanel::SpecialsPanel (GG::X w, int object_id)
References anonymous_namespace{ServerWrapper.cpp}::SetName(), and Update().
Member Function Documentation
bool SpecialsPanel::EventFilter (GG::Wnd * w, const GG::WndEvent & event) override
regenerates indicators according specials on object
References FlexibleFormat(), ClientUI::GetClientUI(), m_icons, UserString(), and ClientUI::ZoomToSpecial().
Referenced by ObjectID().
bool SpecialsPanel::InWindow (const GG::Pt & pt) const override
References m_icons.
void SpecialsPanel::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) override
regenerates indicators according specials on object
Referenced by ObjectID().
int SpecialsPanel::ObjectID () const inline
References EventFilter(), m_object_id, MouseWheel(), Render(), SizeMove(), SpecialRightClicked(), and Update().
void SpecialsPanel::Render () override
regenerates indicators according specials on object
Referenced by ObjectID().
void SpecialsPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) override
regenerates indicators according specials on object
References Update().
Referenced by SidePanel::PlanetPanel::DoLayout(), and ObjectID().
void SpecialsPanel::SpecialRightClicked (const std::string & name) private
Referenced by ObjectID().
void SpecialsPanel::Update ()
regenerates indicators according specials on object
References Special::Description(), DoubleToString(), Effect::Dump(), anonymous_namespace{SpecialsPanel.cpp}::EDGE_PAD(), Special::Effects(), ErrorLogger, FlexibleFormat(), GetOptionsDB(), GetSpecial(), GetUniverseObject(), m_icons, m_object_id, Special::Name(), StatisticIcon::SizeMove(), anonymous_namespace{SpecialsPanel.cpp}::SPECIAL_ICON_HEIGHT(), anonymous_namespace{SpecialsPanel.cpp}::SPECIAL_ICON_WIDTH(), ClientUI::SpecialIcon(), and UserString().
Referenced by ObjectID(), SidePanel::PlanetPanel::Refresh(), SizeMove(), and SpecialsPanel().
Member Data Documentation
std::map<std::string, StatisticIcon*> SpecialsPanel::m_icons private
Referenced by EventFilter(), InWindow(), and Update().
int SpecialsPanel::m_object_id private
id for the Object whose specials this panel displays
Referenced by ObjectID(), and Update().
The documentation for this class was generated from the following files:
SpecialsPanel.h
SpecialsPanel.cpp