FreeOrion: CombatLogWnd::CombatLogWndImpl Class Reference
CombatLogWnd::CombatLogWndImpl Class Reference
Public Member Functions
CombatLogWndImpl (CombatLogWnd &_log)
LinkText * DecorateLinkText (std::string const &text)
void HandleWndChanged ()
std::vector< GG::Wnd * > MakeCombatLogPanel (GG::X w, int viewing_empire_id, ConstCombatEventPtr event)
void PopulateWithFlatLogs (GG::X w, int viewing_empire_id, std::vector< GG::Wnd * > &new_logs, ConstCombatEventPtr &event, std::string &details)
Accessors
GG::Pt MinUsableSize () const
Mutators
void SetFont (boost::shared_ptr< GG::Font > font)
Set which log to show.
void SetLog (int log_id)
Set which log to show.
void AddRow (GG::Wnd *wnd)
Public Attributes
boost::shared_ptr< GG::Font > m_font
GG::Flags< GG::TextFormat > m_text_format_flags
CombatLogWnd & m_wnd
Constructor & Destructor Documentation
CombatLogWnd::CombatLogWndImpl::CombatLogWndImpl (CombatLogWnd & _log)
Member Function Documentation
void CombatLogWnd::CombatLogWndImpl::AddRow (GG::Wnd * wnd)
Add a row at the end of the combat report
LinkText * CombatLogWnd::CombatLogWndImpl::DecorateLinkText (std::string const & text)
DecorateLinkText creates a CUILinkTextMultiEdit using text and attaches it to handlers and_flags are anded to the default flags.
References VarText::EMPIRE_ID_TAG, HandleWndChanged(), VarText::PLANET_ID_TAG, VarText::SHIP_ID_TAG, and VarText::SYSTEM_ID_TAG.
void CombatLogWnd::CombatLogWndImpl::HandleWndChanged ()
When windows changes forces a re-layout
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::CombatLogAccordionPanel(), and DecorateLinkText().
std::vector< GG::Wnd * > CombatLogWnd::CombatLogWndImpl::MakeCombatLogPanel (GG::X w, int viewing_empire_id, ConstCombatEventPtr event)
GG::Pt CombatLogWnd::CombatLogWndImpl::MinUsableSize () const
void CombatLogWnd::CombatLogWndImpl::PopulateWithFlatLogs (GG::X w, int viewing_empire_id, std::vector< GG::Wnd * > & new_logs, ConstCombatEventPtr & event, std::string & details)
Fill new_logs with pointers to the flat log contents of event using the pre-calculated details.
Referenced by anonymous_namespace{CombatLogWnd.cpp}::CombatLogAccordionPanel::ToggleExpansion().
void CombatLogWnd::CombatLogWndImpl::SetFont (boost::shared_ptr< GG::Font > font)
Set which log to show.
< numrows, numcols
< wnd margin, cell margin
void CombatLogWnd::CombatLogWndImpl::SetLog (int log_id)
Set which log to show.
< numrows, numcols
< wnd margin, cell margin
References CombatLog::combat_events, CombatLogAvailable(), anonymous_namespace{CombatLogWnd.cpp}::CountByOwner(), anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), DebugLogger, CombatLog::destroyed_object_ids, CombatLog::empire_ids, ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), HumanClientApp::GetApp(), GetCombatLog(), GetSystem(), LinkTaggedIDText(), CombatLog::object_ids, UniverseObject::PublicName(), CombatLog::system_id, VarText::SYSTEM_ID_TAG, CombatLog::turn, and UserString().
Member Data Documentation
boost::shared_ptr<GG::Font> CombatLogWnd::CombatLogWndImpl::m_font
GG::Flags<GG::TextFormat> CombatLogWnd::CombatLogWndImpl::m_text_format_flags
CombatLogWnd& CombatLogWnd::CombatLogWndImpl::m_wnd
The documentation for this class was generated from the following file:
CombatLogWnd.cpp