FreeOrion: Effect::GenerateSitRepMessage Class Reference
Effect::GenerateSitRepMessage Class Reference
#include <Effect.h>
Public Member Functions
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, ValueRef::ValueRefBase< int > *recipient_empire_id, EmpireAffiliationType affiliation, const std::string label="", bool stringtable_lookup=true)
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, EmpireAffiliationType affiliation, Condition::ConditionBase *condition=0, const std::string label="", bool stringtable_lookup=true)
GenerateSitRepMessage (const std::string &message_string, const std::string &icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > &message_parameters, EmpireAffiliationType affiliation, const std::string &label="", bool stringtable_lookup=true)
virtual ~GenerateSitRepMessage ()
EmpireAffiliationType Affiliation () const
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void Execute (const TargetsCauses &targets_causes, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Condition::ConditionBase * GetCondition () const
const std::string & Icon () const
virtual bool IsAppearanceEffect () const
const std::vector< std::pair
< std::string,
ValueRef::ValueRefBase
< std::string > * > > & MessageParameters () const
const std::string & MessageString () const
ValueRef::ValueRefBase< int > * RecipientID () const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual bool IsEmpireMeterEffect () const
virtual bool IsMeterEffect () const
virtual bool IsSitrepEffect () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
EmpireAffiliationType m_affiliation
Condition::ConditionBase * m_condition
std::string m_icon
std::string m_label
std::vector< std::pair
< std::string,
ValueRef::ValueRefBase
< std::string > * > > m_message_parameters
std::string m_message_string
ValueRef::ValueRefBase< int > * m_recipient_empire_id
bool m_stringtable_lookup
Friends
class boost::serialization::access
Detailed Description
Generates a sitrep message for the empire with id recipient_empire_id. The message text is the user string specified in message_string with string substitutions into the message text as specified in message_parameters which are substituted as string parameters %1%, %2%, %3%, etc. in the order they are specified. Extra parameters beyond those needed by message_string are ignored, and missing parameters are left as blank text.
Constructor & Destructor Documentation
Effect::GenerateSitRepMessage::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, ValueRef::ValueRefBase< int > * recipient_empire_id, EmpireAffiliationType affiliation, const std::string label = "", bool stringtable_lookup = true)
Effect::GenerateSitRepMessage::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, EmpireAffiliationType affiliation, Condition::ConditionBase * condition = 0, const std::string label = "", bool stringtable_lookup = true)
Effect::GenerateSitRepMessage::GenerateSitRepMessage (const std::string & message_string, const std::string & icon, const std::vector< std::pair< std::string, ValueRef::ValueRefBase< std::string > * > > & message_parameters, EmpireAffiliationType affiliation, const std::string & label = "", bool stringtable_lookup = true)
Effect::GenerateSitRepMessage::~GenerateSitRepMessage () virtual
References m_message_parameters, and m_recipient_empire_id.
Member Function Documentation
EmpireAffiliationType Effect::GenerateSitRepMessage::Affiliation () const inline
std::string Effect::GenerateSitRepMessage::Dump () const virtual
Implements Effect::EffectBase.
References AFFIL_ALLY, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_ENEMY, AFFIL_HUMAN, AFFIL_SELF, ValueRef::ValueRefBase< T >::Dump(), Condition::ConditionBase::Dump(), DumpIndent(), g_indent, m_affiliation, m_condition, m_icon, m_message_parameters, m_message_string, and m_recipient_empire_id.
void Effect::GenerateSitRepMessage::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References Empire::AddSitRepEntry(), AFFIL_ALLY, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_ENEMY, AFFIL_HUMAN, AFFIL_NONE, AFFIL_SELF, ALL_EMPIRES, CreateSitRep(), CurrentTurn(), Empires(), EmpireManager::end(), Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), GetPredefinedShipDesign(), GetUniverse(), m_affiliation, m_condition, m_icon, m_label, m_message_parameters, m_message_string, m_recipient_empire_id, m_stringtable_lookup, VarText::PREDEFINED_DESIGN_TAG, and Universe::SetEmpireKnowledgeOfShipDesign().
void Effect::GenerateSitRepMessage::Execute (const TargetsCauses & targets_causes, AccountingMap * accounting_map = 0, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const virtual
Reimplemented from Effect::EffectBase.
References Effect::EffectBase::Execute(), GetUniverseObject(), and ScriptingContext::source.
Condition::ConditionBase* Effect::GenerateSitRepMessage::GetCondition () const inline
const std::string& Effect::GenerateSitRepMessage::Icon () const inline
virtual bool Effect::GenerateSitRepMessage::IsAppearanceEffect () const inline virtual
Reimplemented from Effect::EffectBase.
const std::vector<std::pair<std::string, ValueRef::ValueRefBase<std::string>*> >& Effect::GenerateSitRepMessage::MessageParameters () const inline
const std::string& Effect::GenerateSitRepMessage::MessageString () const inline
ValueRef::ValueRefBase<int>* Effect::GenerateSitRepMessage::RecipientID () const inline
template<class Archive > void Effect::GenerateSitRepMessage::serialize (Archive & ar, const unsigned int version) private
References m_affiliation, m_condition, m_icon, m_label, m_message_parameters, m_message_string, m_recipient_empire_id, and m_stringtable_lookup.
void Effect::GenerateSitRepMessage::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_condition, m_message_parameters, m_recipient_empire_id, ValueRef::ValueRefBase< T >::SetTopLevelContent(), and Condition::ConditionBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
EmpireAffiliationType Effect::GenerateSitRepMessage::m_affiliation private
Referenced by Dump(), Execute(), and serialize().
Condition::ConditionBase* Effect::GenerateSitRepMessage::m_condition private
Referenced by Dump(), Execute(), serialize(), and SetTopLevelContent().
std::string Effect::GenerateSitRepMessage::m_icon private
Referenced by Dump(), Execute(), and serialize().
std::string Effect::GenerateSitRepMessage::m_label private
Referenced by Execute(), and serialize().
std::vector<std::pair<std::string, ValueRef::ValueRefBase<std::string>*> > Effect::GenerateSitRepMessage::m_message_parameters private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~GenerateSitRepMessage().
std::string Effect::GenerateSitRepMessage::m_message_string private
Referenced by Dump(), Execute(), and serialize().
ValueRef::ValueRefBase<int>* Effect::GenerateSitRepMessage::m_recipient_empire_id private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~GenerateSitRepMessage().
bool Effect::GenerateSitRepMessage::m_stringtable_lookup private
Referenced by Execute(), and serialize().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp