FreeOrion: FleetWnd Class Reference
FleetWnd Class Reference
#include <FleetWnd.h>
Public Member Functions
Accessors //@{
int SystemID () const
returns ID of system whose fleets are shown in this FleetWnd, which may be INVALID_OBJECT_ID if this FleetWnd isn't set to show fleets of a system
int EmpireID () const
returns ID of empire whose fleets are shown in this FleetWnd, which may be ALL_EMPIRES if this FleetWnd isn't set to show fleets of a particular empire
bool ContainsFleet (int fleet_id) const
returns true if fleet with ID fleet_id is shown in this FleetWnd
const std::set< int > & FleetIDs () const
returns IDs of all fleets shown in this FleetWnd
std::set< int > SelectedFleetIDs () const
returns IDs of selected fleets in this FleetWnd
std::set< int > SelectedShipIDs () const
returns IDs of selected ships in this FleetWnd
NewFleetAggression GetNewFleetAggression () const
returns this FleetWnd's setting for new fleet aggression (auto, aggressive, or passive)
virtual GG::Rect CalculatePosition () const
returns ID of system whose fleets are shown in this FleetWnd, which may be INVALID_OBJECT_ID if this FleetWnd isn't set to show fleets of a system
Public Member Functions inherited from MapWndPopup
MapWndPopup (const std::string &t, GG::X default_x, GG::Y default_y, GG::X default_w, GG::Y default_h, GG::Flags< GG::WndFlag > flags, const std::string &config_name="")
MapWndPopup (const std::string &t, GG::Flags< GG::WndFlag > flags, const std::string &config_name="")
virtual ~MapWndPopup ()
void Close ()
void CloseClicked ()
called when window is closed via the close button
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
virtual GG::Pt ClientUpperLeft () const
returns true if window is minimized
virtual GG::Pt ClientLowerRight () const
returns true if window is minimized
virtual bool InWindow (const GG::Pt &pt) const
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
virtual void Render ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseLeave ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void Hide (bool children=true)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void Show (bool children=true)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void(FleetWnd *)> ClickedSignal
boost::signals2::signal< void(int)> FleetRightClickedSignal
boost::signals2::signal< void()> SelectedFleetsChangedSignal
boost::signals2::signal< void()> SelectedShipsChangedSignal
boost::signals2::signal< void(int)> ShipRightClickedSignal
Private Member Functions
void AddFleet (int fleet_id)
adds a new fleet row to this FleetWnd's ListBox of FleetRows and updates internal fleets bookkeeping
void CreateNewFleetFromDrops (const std::vector< int > &ship_ids)
void FleetDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
int FleetInRow (GG::ListBox::iterator it) const
void FleetLeftClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void FleetRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void FleetSelectionChanged (const GG::ListBox::SelectionSet &rows)
void Init (int selected_fleet_id)
void Refresh ()
regenerates contents
void RefreshStateChangedSignals ()
void RemoveFleet (int fleet_id)
removes fleet row and updates internal bookkeeping
void SetStatIconValues ()
sets values for multi-fleet aggregate stat icons at top of FleetWnd
void ShipSelectionChanged (const GG::ListBox::SelectionSet &rows)
void SystemChangedSlot ()
responds to StateChangedSignal emitted by the system this FleetWnd is showing the contents of
std::string TitleText () const
void UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj)
Private Attributes
boost::signals2::signal< void(FleetWnd *)> ClosingSignal
int m_empire_id
ID of empire whose fleets are shown in this wnd. May be ALL_EMPIRES if this FleetWnd wasn't set to shown a particular empire's fleets.
FleetDetailPanel * m_fleet_detail_panel
std::set< int > m_fleet_ids
IDs of fleets shown in this wnd (always. set when creating wnd, either by being passed in directly, or found by checking indicated system for indicated empire's fleets. If set directly, never updates. If set by checking system, updates when the system has a fleet added or removed.
FleetsListBox * m_fleets_lb
FleetDataPanel * m_new_fleet_drop_target
bool m_order_issuing_enabled
std::vector< std::pair
< MeterType, StatisticIcon * > > m_stat_icons
boost::signals2::connection m_system_connection
int m_system_id
ID of system whose fleets are shown in this wnd. May be INVALID_OBJECT_ID if this FleetWnd wasn't set to show a system's fleets.
Friends
class FleetUIManager
statistic icons and associated meter types for multi-fleet aggregate
Structors
FleetWnd ()
dtor
~FleetWnd ()
dtor
FleetWnd (const std::vector< int > &fleet_ids, bool order_issuing_enabled, int selected_fleet_id=INVALID_OBJECT_ID, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE|GG::DRAGABLE|GG::ONTOP|CLOSABLE|GG::RESIZABLE, const std::string &config_name="")
dtor
Mutators //@{
virtual void PreRender ()
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
void SelectFleet (int fleet_id)
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
void SetSelectedFleets (const std::set< int > &fleet_ids)
deselects any selected fleets, and selects the fleets with the indicated ids
void SetSelectedShips (const std::set< int > &ship_ids)
deselected any selected ships, and selects the ships with the indicated ids if they are in the selected fleet.
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
void EnableOrderIssuing (bool enable=true)
virtual void CloseClicked ()
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
void DoLayout ()
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init (const std::string &t)
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
virtual void SetParent (GG::Wnd *wnd)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "UI.windows."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair
< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
GG::Button * m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save
true if SaveOptions() is currently allowed to write to the OptionsDB
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
CUI_MinRestoreButton * m_minimize_button
the minimize/restore button
bool m_minimized
true if the window is currently minimized
bool m_mouse_in_resize_tab
GG::Pt m_original_size
keeps track of the size of the window before resizing
CUI_PinButton * m_pin_button
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Detailed Description
This is the top level Fleet UI element. It shows a list of fleets, a new-fleet drop target, and a detail view of the currently selectd fleet (a FleetDetailPanel).
Constructor & Destructor Documentation
FleetWnd::FleetWnd ()
dtor
FleetWnd::~FleetWnd ()
dtor
References MapWnd::ClearProjectedFleetMovementLines(), ClosingSignal, ClientUI::GetClientUI(), and ClientUI::GetMapWnd().
FleetWnd::FleetWnd (const std::vector< int > & fleet_ids, bool order_issuing_enabled, int selected_fleet_id = INVALID_OBJECT_ID, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE | GG::DRAGABLE | GG::ONTOP | CLOSABLE | GG::RESIZABLE, const std::string & config_name = "") private
dtor
References GetFleet(), Init(), m_empire_id, m_fleet_ids, and UniverseObject::Owner().
Member Function Documentation
void FleetWnd::AddFleet (int fleet_id) private
adds a new fleet row to this FleetWnd's ListBox of FleetRows and updates internal fleets bookkeeping
References GetFleet(), FleetsListBox::ListRowSize(), and m_fleets_lb.
Referenced by Refresh().
GG::Rect FleetWnd::CalculatePosition () const virtual
returns ID of system whose fleets are shown in this FleetWnd, which may be INVALID_OBJECT_ID if this FleetWnd isn't set to show fleets of a system
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppHeight(), anonymous_namespace{FleetWnd.cpp}::FLEET_WND_HEIGHT, and anonymous_namespace{FleetWnd.cpp}::FLEET_WND_WIDTH.
void FleetWnd::CloseClicked () protected virtual
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
Reimplemented from CUIWnd.
References CUIWnd::CloseClicked().
bool FleetWnd::ContainsFleet (int fleet_id) const
returns true if fleet with ID fleet_id is shown in this FleetWnd
References FleetInRow(), GetFleet(), UniverseObject::ID(), and m_fleets_lb.
void FleetWnd::CreateNewFleetFromDrops (const std::vector< int > & ship_ids) private
References anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), DebugLogger, FleetDataPanel::GetNewFleetAggression(), m_fleet_detail_panel, m_new_fleet_drop_target, and FleetDetailPanel::SetSelectedShips().
Referenced by Init().
void FleetWnd::DoLayout () protected
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_TEXT_PAD, ClientApp::EmpireID(), HumanClientApp::GetApp(), GetFleet(), CUIWnd::INNER_BORDER_ANGLE_OFFSET, FleetsListBox::ListRowSize(), m_fleet_detail_panel, m_fleet_ids, m_fleets_lb, m_new_fleet_drop_target, m_stat_icons, UniverseObject::OwnedBy(), anonymous_namespace{FleetWnd.cpp}::PAD, FleetDataPanel::SizeMove(), FleetsListBox::SizeMove(), FleetDetailPanel::SizeMove(), and anonymous_namespace{FleetWnd.cpp}::StatIconSize().
Referenced by Init(), and SizeMove().
int FleetWnd::EmpireID () const
returns ID of empire whose fleets are shown in this FleetWnd, which may be ALL_EMPIRES if this FleetWnd isn't set to show fleets of a particular empire
References m_empire_id.
void FleetWnd::EnableOrderIssuing (bool enable = true)
Enables, or disables if enable is false, issuing orders via this FleetWnd.
References FleetsListBox::EnableOrderIssuing(), FleetDetailPanel::EnableOrderIssuing(), m_fleet_detail_panel, m_fleets_lb, m_new_fleet_drop_target, and m_order_issuing_enabled.
void FleetWnd::FleetDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ClickedSignal.
Referenced by Init().
const std::set< int > & FleetWnd::FleetIDs () const
returns IDs of all fleets shown in this FleetWnd
References m_fleet_ids.
Referenced by anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
int FleetWnd::FleetInRow (GG::ListBox::iterator it) const private
References ErrorLogger, INVALID_OBJECT_ID, and m_fleets_lb.
Referenced by ContainsFleet(), FleetRightClicked(), FleetSelectionChanged(), Refresh(), SelectedFleetIDs(), and UniverseObjectDeleted().
void FleetWnd::FleetLeftClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ClickedSignal.
Referenced by Init().
void FleetWnd::FleetRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References Fleet::Aggressive(), ALL_EMPIRES, OrderSet::begin(), anonymous_namespace{FleetWnd.cpp}::ClientPlayerIsModerator(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsForShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), CurrentTurn(), ClientApp::EmpireID(), Empires(), EmpireManager::end(), OrderSet::end(), ObjectMap::FindObjects(), FleetInRow(), Universe::ForgetKnownObject(), HumanClientApp::GetApp(), ClientUI::GetClientUI(), EmpireManager::GetDiplomaticStatus(), GetFleet(), ClientUI::GetMapWnd(), FleetDataPanel::GetNewFleetAggression(), Universe::GetObjectVisibilityTurnMapByEmpire(), GetShip(), GetSystem(), GetUniverse(), UniverseObject::GetVisibility(), Fleet::HasShipsOrderedScrapped(), Fleet::HasShipsWithoutScrapOrders(), UniverseObject::ID(), UniverseObject::InitialMeterValue(), MapWnd::IsFleetExploring(), OrderSet::IssueOrder(), m_new_fleet_drop_target, anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), METER_FUEL, METER_MAX_STRUCTURE, METER_STRUCTURE, UniverseObject::Name(), System::ObjectIDs(), Objects(), Fleet::OrderedGivenToEmpire(), ClientApp::Orders(), UniverseObject::OwnedBy(), UniverseObject::Owner(), MapWnd::RemoveFleet(), OrderSet::RescindOrder(), CUIEditWnd::Result(), MapWnd::SetFleetExploring(), Fleet::ShipIDs(), MapWnd::StopFleetExploring(), UniverseObject::SystemID(), UniverseObject::Unowned(), and UserString().
Referenced by Init().
void FleetWnd::FleetSelectionChanged (const GG::ListBox::SelectionSet & rows) private
References ErrorLogger, FleetInRow(), INVALID_OBJECT_ID, m_fleet_detail_panel, m_fleets_lb, FleetDetailPanel::Refresh(), FleetDataPanel::Select(), SelectedFleetsChangedSignal, and FleetDetailPanel::SetFleet().
Referenced by Init(), SelectFleet(), and SetSelectedFleets().
NewFleetAggression FleetWnd::GetNewFleetAggression () const
returns this FleetWnd's setting for new fleet aggression (auto, aggressive, or passive)
References FleetDataPanel::GetNewFleetAggression(), and m_new_fleet_drop_target.
Referenced by FleetDetailPanel::ShipRightClicked().
void FleetWnd::Init (int selected_fleet_id) private
References CUIWnd::BORDER_BOTTOM, anonymous_namespace{FleetWnd.cpp}::ColonyIcon(), CreateNewFleetFromDrops(), anonymous_namespace{FleetWnd.cpp}::DamageIcon(), DoLayout(), ErrorLogger, anonymous_namespace{FleetWnd.cpp}::FightersIcon(), anonymous_namespace{FleetWnd.cpp}::FLEET_DROP_TYPE_STRING, anonymous_namespace{FleetWnd.cpp}::FleetCountIcon(), FleetDoubleClicked(), FleetLeftClicked(), FleetRightClicked(), FleetSelectionChanged(), OptionsDB::Get(), GetOptionsDB(), GetUniverse(), CUIWnd::INNER_BORDER_ANGLE_OFFSET, INVALID_OBJECT_ID, anonymous_namespace{FleetWnd.cpp}::ListRowHeight(), m_fleet_detail_panel, m_fleet_ids, m_fleets_lb, m_new_fleet_drop_target, m_order_issuing_enabled, m_stat_icons, m_system_id, METER_CAPACITY, METER_POPULATION, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_STRUCTURE, METER_TROOPS, ClientUI::MeterIcon(), CUIWnd::MinimizedSize(), FleetDataPanel::NewFleetFromShipsSignal, anonymous_namespace{FleetWnd.cpp}::PAD, Refresh(), RefreshStateChangedSignals(), CUIWnd::ResetDefaultPosition(), FleetDetailPanel::SelectedShipsChangedSignal, anonymous_namespace{FleetWnd.cpp}::SHIP_DROP_TYPE_STRING, ShipRightClickedSignal, FleetDetailPanel::ShipRightClickedSignal, ShipSelectionChanged(), anonymous_namespace{FleetWnd.cpp}::StatIconSize(), CUIWnd::TopBorder(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), UniverseObjectDeleted(), and UserString().
Referenced by FleetWnd().
void FleetWnd::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) protected virtual
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
Reimplemented from CUIWnd.
References ClickedSignal, and CUIWnd::LClick().
void FleetWnd::PreRender () virtual
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
References Refresh().
void FleetWnd::Refresh () private
regenerates contents
References AddFleet(), ALL_EMPIRES, ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), ObjectMap::FindObjects(), FleetInRow(), HumanClientApp::GetApp(), GetFleet(), GetSystem(), GetUniverse(), UniverseObject::ID(), INVALID_OBJECT_ID, m_empire_id, m_fleet_ids, m_fleets_lb, m_system_id, Objects(), UniverseObject::OwnedBy(), RefreshStateChangedSignals(), SelectedFleetIDs(), SelectedShipIDs(), anonymous_namespace{ServerWrapper.cpp}::SetName(), SetSelectedFleets(), SetSelectedShips(), SetStatIconValues(), UniverseObject::SystemID(), TitleText(), UniverseObject::Unowned(), UniverseObject::X(), and UniverseObject::Y().
Referenced by Init(), and PreRender().
void FleetWnd::RefreshStateChangedSignals () private
References GetSystem(), m_system_connection, m_system_id, and SystemChangedSlot().
Referenced by Init(), and Refresh().
void FleetWnd::RemoveFleet (int fleet_id) private
removes fleet row and updates internal bookkeeping
std::set< int > FleetWnd::SelectedFleetIDs () const
returns IDs of selected fleets in this FleetWnd
References FleetInRow(), INVALID_OBJECT_ID, and m_fleets_lb.
Referenced by MapWnd::FleetButtonLeftClicked(), Refresh(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
std::set< int > FleetWnd::SelectedShipIDs () const
returns IDs of selected ships in this FleetWnd
References m_fleet_detail_panel, and FleetDetailPanel::SelectedShipIDs().
Referenced by Refresh(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag().
void FleetWnd::SelectFleet (int fleet_id)
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
References FleetSelectionChanged(), GetFleet(), INVALID_OBJECT_ID, and m_fleets_lb.
Referenced by MapWnd::SelectFleet().
void FleetWnd::SetSelectedFleets (const std::set< int > & fleet_ids)
deselects any selected fleets, and selects the fleets with the indicated ids
References ErrorLogger, FleetSelectionChanged(), and m_fleets_lb.
Referenced by Refresh().
void FleetWnd::SetSelectedShips (const std::set< int > & ship_ids)
deselected any selected ships, and selects the ships with the indicated ids if they are in the selected fleet.
References m_fleet_detail_panel, and FleetDetailPanel::SetSelectedShips().
Referenced by Refresh().
void FleetWnd::SetStatIconValues () private
sets values for multi-fleet aggregate stat icons at top of FleetWnd
References ALL_EMPIRES, Ship::ColonyCapacity(), Ship::Design(), ClientApp::EmpireID(), Universe::EmpireKnownDestroyedObjectIDs(), Universe::EmpireStaleKnowledgeObjectIDs(), Ship::FighterCount(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), GetUniverse(), UniverseObject::ID(), UniverseObject::InitialMeterValue(), m_empire_id, m_fleet_ids, m_stat_icons, METER_CAPACITY, METER_POPULATION, METER_SECONDARY_STAT, METER_SHIELD, METER_SIZE, METER_STRUCTURE, METER_TROOPS, Objects(), UniverseObject::OwnedBy(), Fleet::ShipIDs(), Ship::TotalWeaponsDamage(), Ship::TroopCapacity(), and UniverseObject::Unowned().
Referenced by Refresh().
void FleetWnd::ShipSelectionChanged (const GG::ListBox::SelectionSet & rows) private
References SelectedShipsChangedSignal.
Referenced by Init().
void FleetWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
deselects any selected fleets, and selects the indicated fleet, bringing it into the fleet detail window
Reimplemented from CUIWnd.
References DoLayout(), and CUIWnd::SizeMove().
void FleetWnd::SystemChangedSlot () private
responds to StateChangedSignal emitted by the system this FleetWnd is showing the contents of
References ErrorLogger, GetSystem(), and m_system_id.
Referenced by RefreshStateChangedSignals().
int FleetWnd::SystemID () const
returns ID of system whose fleets are shown in this FleetWnd, which may be INVALID_OBJECT_ID if this FleetWnd isn't set to show fleets of a system
References m_system_id.
std::string FleetWnd::TitleText () const private
References ClientApp::EmpireID(), FlexibleFormat(), HumanClientApp::GetApp(), GetEmpire(), GetSystem(), m_empire_id, m_fleet_ids, m_system_id, Empire::Name(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), and UserString().
Referenced by Refresh().
void FleetWnd::UniverseObjectDeleted (TemporaryPtr< const UniverseObject > obj) private
References boost::dynamic_pointer_cast(), FleetDetailPanel::FleetID(), FleetInRow(), GetFleet(), GetUniverse(), INVALID_OBJECT_ID, m_fleet_detail_panel, m_fleets_lb, ObjectMap::Object(), Universe::Objects(), and FleetDetailPanel::SetFleet().
Referenced by Init().
Friends And Related Function Documentation
friend class FleetUIManager friend
statistic icons and associated meter types for multi-fleet aggregate
Member Data Documentation
boost::signals2::signal<void (FleetWnd*)> FleetWnd::ClickedSignal mutable
Referenced by FleetDoubleClicked(), FleetLeftClicked(), and LClick().
boost::signals2::signal<void (FleetWnd*)> FleetWnd::ClosingSignal mutable private
Referenced by ~FleetWnd().
boost::signals2::signal<void (int)> FleetWnd::FleetRightClickedSignal mutable
int FleetWnd::m_empire_id private
ID of empire whose fleets are shown in this wnd. May be ALL_EMPIRES if this FleetWnd wasn't set to shown a particular empire's fleets.
Referenced by EmpireID(), FleetWnd(), Refresh(), SetStatIconValues(), and TitleText().
FleetDetailPanel* FleetWnd::m_fleet_detail_panel private
Referenced by CreateNewFleetFromDrops(), DoLayout(), EnableOrderIssuing(), FleetSelectionChanged(), Init(), SelectedShipIDs(), SetSelectedShips(), and UniverseObjectDeleted().
std::set<int> FleetWnd::m_fleet_ids private
IDs of fleets shown in this wnd (always. set when creating wnd, either by being passed in directly, or found by checking indicated system for indicated empire's fleets. If set directly, never updates. If set by checking system, updates when the system has a fleet added or removed.
Referenced by DoLayout(), FleetIDs(), FleetWnd(), Init(), Refresh(), SetStatIconValues(), and TitleText().
FleetsListBox* FleetWnd::m_fleets_lb private
Referenced by AddFleet(), ContainsFleet(), DoLayout(), EnableOrderIssuing(), FleetInRow(), FleetSelectionChanged(), Init(), Refresh(), SelectedFleetIDs(), SelectFleet(), SetSelectedFleets(), and UniverseObjectDeleted().
FleetDataPanel* FleetWnd::m_new_fleet_drop_target private
Referenced by CreateNewFleetFromDrops(), DoLayout(), EnableOrderIssuing(), FleetRightClicked(), GetNewFleetAggression(), and Init().
bool FleetWnd::m_order_issuing_enabled private
Referenced by EnableOrderIssuing(), and Init().
std::vector<std::pair<MeterType, StatisticIcon*> > FleetWnd::m_stat_icons private
Referenced by DoLayout(), Init(), and SetStatIconValues().
boost::signals2::connection FleetWnd::m_system_connection private
Referenced by RefreshStateChangedSignals().
int FleetWnd::m_system_id private
ID of system whose fleets are shown in this wnd. May be INVALID_OBJECT_ID if this FleetWnd wasn't set to show a system's fleets.
Referenced by Init(), Refresh(), RefreshStateChangedSignals(), SystemChangedSlot(), SystemID(), and TitleText().
boost::signals2::signal<void ()> FleetWnd::SelectedFleetsChangedSignal mutable
Referenced by FleetSelectionChanged().
boost::signals2::signal<void ()> FleetWnd::SelectedShipsChangedSignal mutable
Referenced by ShipSelectionChanged().
boost::signals2::signal<void (int)> FleetWnd::ShipRightClickedSignal mutable
Referenced by Init().
The documentation for this class was generated from the following files:
FleetWnd.h
FleetWnd.cpp