FreeOrion: EmpireColorSelector Class Reference
EmpireColorSelector Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
EmpireColorSelector (GG::Y h)
Accessors
GG::Clr CurrentColor () const
returns the color that is currently selected, or GG::CLR_ZERO if none is selected
Mutators
void SelectColor (const GG::Clr &clr)
Public Member Functions inherited from CUIDropDownList
GG::Pt ClientLowerRight () const override
GG::X DroppedRowWidth () const override
CUIDropDownList (size_t num_shown_elements)
void Render () override
disables rendering of the small downward-facing arrow on the right of the control
void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) override
disables rendering of the small downward-facing arrow on the right of the control
void MouseLeave () override
disables rendering of the small downward-facing arrow on the right of the control
void DisableDropArrow ()
disables rendering of the small downward-facing arrow on the right of the control
void EnableDropArrow ()
enables rendering of the small downward-facing arrow on the right of the control
Public Attributes
boost::signals2::signal< void(const
GG::Clr &)> ColorChangedSignal
Private Member Functions
void SelectionChanged (GG::DropDownList::iterator it)
Detailed Description
A control used to pick from the empire colors returned by EmpireColors().
Constructor & Destructor Documentation
EmpireColorSelector::EmpireColorSelector (GG::Y h) explicit
References anonymous_namespace{CUIControls.cpp}::COLOR_SELECTOR_WIDTH(), EmpireColors(), and SelectionChanged().
Member Function Documentation
GG::Clr EmpireColorSelector::CurrentColor () const
returns the color that is currently selected, or GG::CLR_ZERO if none is selected
Referenced by GalaxySetupWnd::EmpireColor().
void EmpireColorSelector::SelectColor (const GG::Clr & clr)
References ErrorLogger.
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::NewGamePlayerRow().
void EmpireColorSelector::SelectionChanged (GG::DropDownList::iterator it) private
References ColorChangedSignal, and ErrorLogger.
Referenced by EmpireColorSelector().
Member Data Documentation
boost::signals2::signal<void (const GG::Clr&)> EmpireColorSelector::ColorChangedSignal mutable
Referenced by anonymous_namespace{MultiplayerLobbyWnd.cpp}::NewGamePlayerRow::NewGamePlayerRow(), and SelectionChanged().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp