FreeOrion: ObjectListWnd Class Reference
ObjectListWnd Class Reference
#include <ObjectListWnd.h>
Public Member Functions
Structors //!@{
ObjectListWnd (const std::string &config_name="")
Mutators
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Refresh ()
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
virtual GG::Pt ClientUpperLeft () const
returns true if window is minimized
virtual GG::Pt ClientLowerRight () const
returns true if window is minimized
virtual bool InWindow (const GG::Pt &pt) const
returns true if window is minimized
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
virtual void Render ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void MouseLeave ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void Hide (bool children=true)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
virtual void Show (bool children=true)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ToggleMinimized ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void Close ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Public Attributes
boost::signals2::signal< void()> ClosingSignal
boost::signals2::signal< void(int)> ObjectDoubleClickedSignal
boost::signals2::signal< void(int)> ObjectDumpSignal
boost::signals2::signal< void()> SelectedObjectsChangedSignal
Private Member Functions
virtual void CloseClicked ()
called when window is closed via the close button
void CollapseExpandClicked ()
void DoLayout ()
void FilterClicked ()
void ObjectDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
int ObjectInRow (GG::ListBox::iterator it) const
void ObjectRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void ObjectSelectionChanged (const GG::ListBox::SelectionSet &rows)
std::set< int > SelectedObjectIDs () const
void SetSelectedObjects (std::set< int > sel_ids)
Private Attributes
GG::Button * m_collapse_button
GG::Button * m_filter_button
ObjectListBox * m_list_box
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void LoadOptions ()
loads options for this window from the OptionsDB
void Init (const std::string &t)
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
virtual void SetParent (GG::Wnd *wnd)
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "UI.windows."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair
< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
GG::Button * m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save
true if SaveOptions() is currently allowed to write to the OptionsDB
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
CUI_MinRestoreButton * m_minimize_button
the minimize/restore button
bool m_minimized
true if the window is currently minimized
bool m_mouse_in_resize_tab
GG::Pt m_original_size
keeps track of the size of the window before resizing
CUI_PinButton * m_pin_button
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Constructor & Destructor Documentation
ObjectListWnd::ObjectListWnd (const std::string & config_name = "")
References CollapseExpandClicked(), DoLayout(), ObjectListBox::ExpandCollapseSignal, FilterClicked(), m_collapse_button, m_filter_button, m_list_box, ObjectDoubleClicked(), ObjectRightClicked(), ObjectSelectionChanged(), and UserString().
Member Function Documentation
void ObjectListWnd::CloseClicked () private virtual
called when window is closed via the close button
Reimplemented from CUIWnd.
References ClosingSignal.
void ObjectListWnd::CollapseExpandClicked () private
References ObjectListBox::AnythingCollapsed(), ObjectListBox::CollapseObject(), DoLayout(), ObjectListBox::ExpandObject(), INVALID_OBJECT_ID, and m_list_box.
Referenced by ObjectListWnd().
void ObjectListWnd::DoLayout () private
References ObjectListBox::AnythingCollapsed(), m_collapse_button, m_filter_button, m_list_box, anonymous_namespace{ObjectListWnd.cpp}::PAD(), ClientUI::Pts(), ObjectListBox::SizeMove(), and UserString().
Referenced by CollapseExpandClicked(), ObjectListWnd(), and SizeMove().
void ObjectListWnd::FilterClicked () private
References ObjectListBox::FilterCondition(), m_list_box, ObjectListBox::SetFilterCondition(), ObjectListBox::SetVisibilityFilters(), and ObjectListBox::Visibilities().
Referenced by ObjectListWnd().
void ObjectListWnd::ObjectDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ClientUI::GetClientUI(), INVALID_OBJECT_ID, ObjectDoubleClickedSignal, ObjectInRow(), and ClientUI::ZoomToObject().
Referenced by ObjectListWnd().
int ObjectListWnd::ObjectInRow (GG::ListBox::iterator it) const private
References INVALID_OBJECT_ID, and m_list_box.
Referenced by ObjectDoubleClicked(), and ObjectRightClicked().
void ObjectListWnd::ObjectRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References ALL_EMPIRES, Empire::AvailableBuildingTypes(), Planet::AvailableFoci(), Empire::AvailableShipDesigns(), BT_BUILDING, BT_SHIP, Networking::CLIENT_TYPE_HUMAN_MODERATOR, ClientUI::EditHiliteColor(), ClientApp::EmpireID(), Empire::EnqueuableItem(), HumanClientApp::GetApp(), ClientApp::GetClientType(), ClientUI::GetClientUI(), GetEmpire(), ClientUI::GetFont(), GetPlanet(), GetShipDesign(), GetUniverseObject(), UniverseObject::ID(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), m_list_box, ModeratorActionMessage(), ShipDesign::Name(), ClientApp::Networking(), ObjectDumpSignal, ObjectRow::ObjectID(), ObjectInRow(), ObjectSelectionChanged(), UniverseObject::ObjectType(), ClientApp::Orders(), UniverseObject::OwnedBy(), ClientApp::PlayerID(), Empire::ProducibleItem(), Refresh(), SelectedObjectIDs(), ClientNetworking::SendMessage(), ResourceCenter::SetFocus(), SetSelectedObjects(), parse::ship_designs(), ClientUI::TextColor(), Empire::UpdateProductionQueue(), UserString(), ClientUI::WndColor(), ClientUI::WndOuterBorderColor(), and ClientUI::ZoomToPlanetPedia().
Referenced by ObjectListWnd().
void ObjectListWnd::ObjectSelectionChanged (const GG::ListBox::SelectionSet & rows) private
References ErrorLogger, m_list_box, ObjectPanel::Select(), and SelectedObjectsChangedSignal.
Referenced by ObjectListWnd(), and ObjectRightClicked().
void ObjectListWnd::Refresh ()
References m_list_box, and ObjectListBox::Refresh().
Referenced by MapWnd::InitTurn(), ObjectRightClicked(), and MapWnd::ShowObjects().
std::set< int > ObjectListWnd::SelectedObjectIDs () const private
References INVALID_OBJECT_ID, m_list_box, and ObjectRow::ObjectID().
Referenced by ObjectRightClicked().
void ObjectListWnd::SetSelectedObjects (std::set< int > sel_ids) private
References INVALID_OBJECT_ID, m_list_box, and ObjectRow::ObjectID().
Referenced by ObjectRightClicked().
void ObjectListWnd::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
Reimplemented from CUIWnd.
References DoLayout(), and CUIWnd::SizeMove().
Member Data Documentation
boost::signals2::signal<void ()> ObjectListWnd::ClosingSignal mutable
Referenced by CloseClicked(), and MapWnd::MapWnd().
GG::Button* ObjectListWnd::m_collapse_button private
Referenced by DoLayout(), and ObjectListWnd().
GG::Button* ObjectListWnd::m_filter_button private
Referenced by DoLayout(), and ObjectListWnd().
ObjectListBox* ObjectListWnd::m_list_box private
Referenced by CollapseExpandClicked(), DoLayout(), FilterClicked(), ObjectInRow(), ObjectListWnd(), ObjectRightClicked(), ObjectSelectionChanged(), Refresh(), SelectedObjectIDs(), and SetSelectedObjects().
boost::signals2::signal<void (int)> ObjectListWnd::ObjectDoubleClickedSignal mutable
Referenced by ObjectDoubleClicked().
boost::signals2::signal<void (int)> ObjectListWnd::ObjectDumpSignal mutable
Referenced by MapWnd::MapWnd(), and ObjectRightClicked().
boost::signals2::signal<void ()> ObjectListWnd::SelectedObjectsChangedSignal mutable
Referenced by ObjectSelectionChanged().
The documentation for this class was generated from the following files:
ObjectListWnd.h
ObjectListWnd.cpp