FreeOrion: ScopedTimer::Impl Class Reference
ScopedTimer::Impl Class Reference
Public Member Functions
Impl (const std::string &timed_name, bool enable_output, boost::chrono::microseconds threshold)
~Impl ()
void FormatDuration (std::stringstream &ss, const boost::chrono::nanoseconds &duration)
bool ShouldOutput (const boost::chrono::nanoseconds &duration)
Public Attributes
bool m_enable_output
std::string m_name
boost::chrono::high_resolution_clock::time_point m_start
boost::chrono::microseconds m_threshold
Constructor & Destructor Documentation
ScopedTimer::Impl::Impl (const std::string & timed_name, bool enable_output, boost::chrono::microseconds threshold) inline
ScopedTimer::Impl::~Impl () inline
References DebugLogger, FormatDuration(), m_name, m_start, and ShouldOutput().
Member Function Documentation
void ScopedTimer::Impl::FormatDuration (std::stringstream & ss, const boost::chrono::nanoseconds & duration) inline
Referenced by ~Impl(), and SectionedScopedTimer::Impl::~Impl().
bool ScopedTimer::Impl::ShouldOutput (const boost::chrono::nanoseconds & duration) inline
References GetOptionsDB(), m_enable_output, and m_threshold.
Referenced by ~Impl(), and SectionedScopedTimer::Impl::~Impl().
Member Data Documentation
bool ScopedTimer::Impl::m_enable_output
Referenced by ShouldOutput(), and SectionedScopedTimer::Impl::~Impl().
std::string ScopedTimer::Impl::m_name
Referenced by ~Impl(), and SectionedScopedTimer::Impl::~Impl().
boost::chrono::high_resolution_clock::time_point ScopedTimer::Impl::m_start
Referenced by SectionedScopedTimer::Impl::CreateSections(), ~Impl(), and SectionedScopedTimer::Impl::~Impl().
boost::chrono::microseconds ScopedTimer::Impl::m_threshold
Referenced by ShouldOutput().
The documentation for this class was generated from the following file:
ScopedTimer.cpp