FreeOrion: ConditionWidget::ConditionRow Class Reference
ConditionWidget::ConditionRow Class Reference
Public Member Functions
ConditionRow (const std::string &key, GG::Y row_height)
const std::string & GetKey () const
Private Attributes
std::string m_condition_key
Constructor & Destructor Documentation
ConditionWidget::ConditionRow::ConditionRow (const std::string & key, GG::Y row_height) inline
References m_condition_key, and UserString().
Referenced by ConditionWidget::Init().
Member Function Documentation
const std::string& ConditionWidget::ConditionRow::GetKey () const inline
References m_condition_key.
Referenced by ConditionWidget::GetCondition(), and ConditionWidget::UpdateParameterControls().
Member Data Documentation
std::string ConditionWidget::ConditionRow::m_condition_key private
Referenced by ConditionRow(), and GetKey().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp