FreeOrion: Effect::SetEmpireCapital Class Reference
Effect::SetEmpireCapital Class Reference
#include <Effect.h>
Public Member Functions
SetEmpireCapital ()
SetEmpireCapital (ValueRef::ValueRefBase< int > *empire_id)
virtual ~SetEmpireCapital ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< int > * m_empire_id
Friends
class boost::serialization::access
Detailed Description
Makes the target planet the capital of its owner's empire. If the target object is not a planet, does not have an owner, or has more than one owner the effect does nothing.
Constructor & Destructor Documentation
Effect::SetEmpireCapital::SetEmpireCapital () explicit
Effect::SetEmpireCapital::SetEmpireCapital (ValueRef::ValueRefBase< int > * empire_id) explicit
Effect::SetEmpireCapital::~SetEmpireCapital () virtual
References m_empire_id.
Member Function Documentation
std::string Effect::SetEmpireCapital::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_empire_id.
void Effect::SetEmpireCapital::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References boost::dynamic_pointer_cast(), ScriptingContext::effect_target, ValueRef::ValueRefBase< T >::Eval(), GetEmpire(), UniverseObject::ID(), m_empire_id, and Empire::SetCapitalID().
template<class Archive > void Effect::SetEmpireCapital::serialize (Archive & ar, const unsigned int version) private
References m_empire_id.
void Effect::SetEmpireCapital::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_empire_id, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<int>* Effect::SetEmpireCapital::m_empire_id private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~SetEmpireCapital().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp