FreeOrion: UniverseObject Class Reference
UniverseObject Class Reference abstract
#include <UniverseObject.h>
Public Types
Signal Types
typedef
boost::signals2::signal< void(),
blocking_combiner
< boost::signals2::optional_last_value
< void > > > StateChangedSignalType
Slot Types
typedef
StateChangedSignalType::slot_type StateChangedSlotType
Public Types inherited from EnableTemporaryFromThis< UniverseObject >
typedef
EnableTemporaryFromThis
< UniverseObject > enable_temporary_from_this_type
Public Member Functions
Mutators
virtual void Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id)=0
void SetID (int id)
sets the ID number of the object to id
void Rename (const std::string &name)
renames this object to name
void Move (double x, double y)
void MoveTo (int object_id)
void MoveTo (TemporaryPtr< UniverseObject > object)
void MoveTo (double x, double y)
std::map< MeterType, Meter > & Meters ()
returns this UniverseObject's meters
Meter * GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
virtual void BackPropagateMeters ()
sets all this UniverseObject's meters' initial values equal to their current values
virtual void SetOwner (int id)
sets the empire that owns this object
void SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
virtual void AddSpecial (const std::string &name, float capacity=0.0f)
adds the Special name to this object, if it is not already present
virtual void RemoveSpecial (const std::string &name)
removes the Special name from this object, if it is already present
void SetSpecialCapacity (const std::string &name, float capacity)
virtual void MovementPhase ()
virtual void ResetTargetMaxUnpairedMeters ()
virtual void ResetPairedActiveMeters ()
virtual void ClampMeters ()
virtual void PopGrowthProductionResearchPhase ()
Public Member Functions inherited from EnableTemporaryFromThis< UniverseObject >
EnableTemporaryFromThis ()
TemporaryPtr< UniverseObject > TemporaryFromThis ()
TemporaryPtr< const
UniverseObject > TemporaryFromThis () const
Static Public Attributes
static const int INVALID_OBJECT_AGE = -(1 << 30) - 1
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
static const double INVALID_POSITION = -100000.0
the position in x and y at which default-constructed objects are placed
static const int SINCE_BEFORE_TIME_AGE = (1 << 30) + 1
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Protected Member Functions
void AddMeter (MeterType meter_type)
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
void Copy (TemporaryPtr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > &visible_specials)
used by public UniverseObject::Copy and derived classes' ::Copy methods
void Init ()
adds stealth meter
Structors
UniverseObject ()
UniverseObject (const std::string name, double x, double y)
virtual ~UniverseObject ()
virtual UniverseObject * Clone (int empire_id=ALL_EMPIRES) const =0
Protected Attributes
std::string m_name
Private Member Functions
std::map< MeterType, Meter > CensoredMeters (Visibility vis) const
returns set of meters of this object that are censored based on the specified Visibility vis
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_created_on_turn
int m_id
std::map< MeterType, Meter > m_meters
int m_owner_empire_id
std::map< std::string,
std::pair< int, float > > m_specials
int m_system_id
double m_x
double m_y
Friends
template<class T >
void boost::checked_delete (T *x)
template<class T >
void boost::python::detail::value_destroyer (T const volatile *p)
class boost::serialization::access
class ObjectMap
class Universe
Accessors
StateChangedSignalType StateChangedSignal
emitted when the UniverseObject is altered in any way
int ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
const std::string & Name () const
returns the name of this object; some valid objects will have no name
virtual double X () const
the X-coordinate of this object
virtual double Y () const
the Y-coordinate of this object
virtual int Owner () const
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
bool Unowned () const
returns true iff there are no owners of this object
bool OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
virtual int SystemID () const
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
const std::map< std::string,
std::pair< int, float > > & Specials () const
returns the Specials attached to this object
bool HasSpecial (const std::string &name) const
returns true iff this object has a special with the indicated name
int SpecialAddedOnTurn (const std::string &name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
float SpecialCapacity (const std::string &name) const
emitted when the UniverseObject is altered in any way
virtual std::set< std::string > Tags () const
returns the capacity of the special with name name or 0 if that special is not present
virtual bool HasTag (const std::string &name) const
returns true iff this object has the tag with the indicated name
virtual UniverseObjectType ObjectType () const
emitted when the UniverseObject is altered in any way
virtual std::string Dump () const
outputs textual description of object to logger
virtual int ContainerObjectID () const
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
virtual const std::set< int > & ContainedObjectIDs () const
returns ids of objects contained within this object
virtual bool Contains (int object_id) const
returns true if there is an object with id object_id is contained within this UniverseObject
virtual bool ContainedBy (int object_id) const
returns true if there is an object with id object_id that contains this UniverseObject
std::set< int > VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
const std::map< MeterType,
Meter > & Meters () const
returns this UniverseObject's meters
const Meter * GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
float CurrentMeterValue (MeterType type) const
returns current value of the specified meter type
float InitialMeterValue (MeterType type) const
returns this turn's initial value for the speicified meter type
virtual float NextTurnCurrentMeterValue (MeterType type) const
returns an estimate of the next turn's current value of the specified meter type
Visibility GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
virtual const std::string & PublicName (int empire_id) const
returns the name of this objectas it appears to empire empire_id
virtual TemporaryPtr
< UniverseObject > Accept (const UniverseObjectVisitor &visitor) const
int CreationTurn () const
returns game turn on which object was created
int AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
Detailed Description
The abstract base class for all objects in the universe The UniverseObject class itself has an ID number, a name, a position, an ID of the system in which it is, a list of zero or more owners, and other common object data. Position in the Universe can range from 0 (left) to 1000 (right) in X, and 0 (top) to 1000 (bottom) in Y. This coordinate system was chosen to help with conversion to and from screen coordinates, which originate at the upper-left corner of the screen and increase down and to the right. Each UniverseObject-derived class inherits several pure virtual members that perform its actions during various game phases, such as the movement phase. These subclasses must define what actions to perform during those phases. UniverseObjects advertise changes to themselves via the StateChanged Signal. This means that all mutators on UniverseObject and its subclasses need to emit this signal. This is how the UI becomes aware that an object that is being displayed has changed.
Member Typedef Documentation
typedef boost::signals2::signal<void (), blocking_combiner<boost::signals2::optional_last_value<void> > > UniverseObject::StateChangedSignalType
typedef StateChangedSignalType::slot_type UniverseObject::StateChangedSlotType
Constructor & Destructor Documentation
UniverseObject::UniverseObject () protected
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system. Caller takes ownership of returned pointee.
References CurrentTurn(), and m_created_on_turn.
UniverseObject::UniverseObject (const std::string name, double x, double y) protected
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system. Caller takes ownership of returned pointee.
References CurrentTurn(), and m_created_on_turn.
UniverseObject::~UniverseObject () protected virtual
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system. Caller takes ownership of returned pointee.
Member Function Documentation
TemporaryPtr< UniverseObject > UniverseObject::Accept (const UniverseObjectVisitor & visitor) const virtual
accepts a visitor object
See Also
UniverseObjectVisitor
Reimplemented in Fleet, System, Planet, Ship, Building, Fighter, and Field.
References EnableTemporaryFromThis< UniverseObject >::TemporaryFromThis(), and UniverseObjectVisitor::Visit().
Referenced by ValueRef::Variable< T >::Eval(), and ObjectMap::FindObjects().
void UniverseObject::AddMeter (MeterType meter_type) protected
inserts a meter into object as the meter_type meter. Should be used by derived classes to add their specialized meters to objects
References ErrorLogger, INVALID_METER_TYPE, and m_meters.
Referenced by Planet::AddMeter(), Field::Field(), Init(), and Ship::Ship().
void UniverseObject::AddSpecial (const std::string & name, float capacity = 0.0f) virtual
adds the Special name to this object, if it is not already present
References CurrentTurn(), and m_specials.
Referenced by anonymous_namespace{ServerWrapper.cpp}::AddSpecial(), and SetSpecialCapacity().
int UniverseObject::AgeInTurns () const
returns elapsed number of turns between turn object was created and current game turn
References BEFORE_FIRST_TURN, CurrentTurn(), INVALID_GAME_TURN, INVALID_OBJECT_AGE, m_created_on_turn, and SINCE_BEFORE_TIME_AGE.
Referenced by FreeOrionPython::WrapUniverseClasses().
void UniverseObject::BackPropagateMeters () virtual
sets all this UniverseObject's meters' initial values equal to their current values
Reimplemented in Ship.
References GetMeter().
Referenced by Ship::BackPropagateMeters(), Planet::Colonize(), and anonymous_namespace{ServerApp.cpp}::HandleInvasion().
std::map< MeterType, Meter > UniverseObject::CensoredMeters (Visibility vis) const private
returns set of meters of this object that are censored based on the specified Visibility vis
References Meter::LARGE_VALUE, m_meters, and METER_STEALTH.
Referenced by Copy().
void UniverseObject::ClampMeters () virtual
calls Clamp(min, max) on meters each meter in this UniverseObject, to ensure that meter current values aren't outside the valid range for each meter.
Reimplemented in Planet, Ship, and Field.
References Meter::ClampCurrentToRange(), GetMeter(), and METER_STEALTH.
Referenced by Field::ClampMeters(), Ship::ClampMeters(), and Planet::ClampMeters().
virtual UniverseObject* UniverseObject::Clone (int empire_id = ALL_EMPIRES) const protected pure virtual
returns new copy of this UniverseObject, limited to only copy data that is visible to the empire with the specified empire_id as determined by the detection and visibility system. Caller takes ownership of returned pointee.
Implemented in Fleet, System, Planet, Ship, Building, Field, and Fighter.
Referenced by ObjectMap::CopyObject(), and Universe::UpdateEmpireLatestKnownObjectsAndVisibilityTurns().
bool UniverseObject::ContainedBy (int object_id) const virtual
returns true if there is an object with id object_id that contains this UniverseObject
Reimplemented in System, Planet, Fleet, Building, Field, and Ship.
Referenced by Condition::anonymous_namespace{Condition.cpp}::ContainedBySimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
const std::set< int > & UniverseObject::ContainedObjectIDs () const virtual
returns ids of objects contained within this object
Reimplemented in Planet, System, and Fleet.
References anonymous_namespace{UniverseObject.cpp}::EMPTY_SET.
Referenced by Universe::ExecuteEffects(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), Condition::anonymous_namespace{Condition.cpp}::ContainsSimpleMatch::operator()(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects(), Universe::UpdateMeterEstimates(), VisibleContainedObjectIDs(), and FreeOrionPython::WrapUniverseClasses().
int UniverseObject::ContainerObjectID () const virtual
returns id of the object that directly contains this object, if any, or INVALID_OBJECT_ID if this object is not contained by any other
Reimplemented in Planet, Fleet, Building, Field, and Ship.
References INVALID_OBJECT_ID.
Referenced by ObjectMap::AuditContainment(), CombatInfo::ForceAtLeastBasicVisibility(), Universe::ForgetKnownObject(), Condition::ContainedBy::Match(), Condition::anonymous_namespace{Condition.cpp}::ContainedBySimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
bool UniverseObject::Contains (int object_id) const virtual
returns true if there is an object with id object_id is contained within this UniverseObject
Reimplemented in System, Planet, and Fleet.
Referenced by Condition::Contains::Match(), Condition::anonymous_namespace{Condition.cpp}::ContainsSimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
virtual void UniverseObject::Copy (TemporaryPtr< const UniverseObject > copied_object, int empire_id) pure virtual
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
Implemented in Fleet, System, Planet, Ship, Building, Field, and Fighter.
Referenced by Fighter::Copy(), Field::Copy(), Building::Copy(), Ship::Copy(), Planet::Copy(), System::Copy(), and Fleet::Copy().
void UniverseObject::Copy (TemporaryPtr< const UniverseObject > copied_object, Visibility vis, const std::set< std::string > & visible_specials) protected
used by public UniverseObject::Copy and derived classes' ::Copy methods
References CensoredMeters(), Meter::Current(), ErrorLogger, Meter::Initial(), Meter::LARGE_VALUE, m_created_on_turn, m_id, m_meters, m_name, m_owner_empire_id, m_specials, m_system_id, m_x, and m_y.
int UniverseObject::CreationTurn () const
returns game turn on which object was created
References m_created_on_turn.
Referenced by Empire::CheckProductionProgress(), Condition::anonymous_namespace{Condition.cpp}::CreatedOnTurnSimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
float UniverseObject::CurrentMeterValue (MeterType type) const
returns current value of the specified meter type
References m_meters.
Referenced by Fleet::BlockadedAtSystem(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), Planet::CurrentMeterValue(), MapWnd::DoFieldIconsLayout(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{CombatSystem.cpp}::GetMonsterDetection(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), ShipDataPanel::Init(), MapWnd::InitFieldRenderingBuffers(), NextTurnCurrentMeterValue(), anonymous_namespace{CombatSystem.cpp}::ObjectTargettableByMonsters(), anonymous_namespace{CombatSystem.cpp}::ObjectTypeCanBeAttacked(), Ship::Speed(), ResourcePool::Update(), SpeciesManager::UpdatePopulationCounter(), and FreeOrionPython::WrapUniverseClasses().
std::string UniverseObject::Dump () const virtual
outputs textual description of object to logger
Reimplemented in Fleet, Building, System, Planet, Ship, Field, and Fighter.
References Empires(), EmpireManager::GetEmpireName(), GetSystem(), GetUniverse(), ID(), m_created_on_turn, m_meters, m_owner_empire_id, m_specials, Name(), Universe::NearestSystemTo(), ObjectType(), SystemID(), Unowned(), X(), and Y().
Referenced by Fighter::Dump(), Field::Dump(), Ship::Dump(), Planet::Dump(), System::Dump(), Building::Dump(), Fleet::Dump(), ClientUI::DumpObject(), Effect::SetDestination::Execute(), Effect::SetAggression::Execute(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), and FreeOrionPython::WrapUniverseClasses().
const Meter * UniverseObject::GetMeter (MeterType type) const
returns the requested Meter, or 0 if no such Meter of that type is found in this object
References m_meters.
Referenced by BackPropagateMeters(), Fleet::BlockadedAtSystem(), Empire::CheckProductionProgress(), Field::ClampMeters(), Ship::ClampMeters(), Planet::ClampMeters(), ClampMeters(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), DualMeter::CurrentProjectedTarget(), ValueRef::Variable< T >::Eval(), Effect::SetMeter::Execute(), NewFleetOrder::ExecuteImpl(), Field::Field(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), Planet::GetMeter(), Field::InField(), MeterBrowseWnd::Initialize(), MapWnd::InitVisibilityRadiiRenderingBuffers(), Ship::NextTurnCurrentMeterValue(), Condition::anonymous_namespace{Condition.cpp}::MeterValueSimpleMatch::operator()(), Ship::PopGrowthProductionResearchPhase(), BuildingIndicator::Refresh(), ResetPairedActiveMeters(), Field::ResetTargetMaxUnpairedMeters(), Ship::ResetTargetMaxUnpairedMeters(), System::ResetTargetMaxUnpairedMeters(), Fleet::ResetTargetMaxUnpairedMeters(), ResetTargetMaxUnpairedMeters(), Ship::Resupply(), Ship::SetShipMetersToMax(), MultiMeterStatusBar::Update(), ResourcePool::Update(), MeterBrowseWnd::UpdateSummary(), and Empire::UpdateSystemSupplyRanges().
Meter * UniverseObject::GetMeter (MeterType type)
returns the requested Meter, or 0 if no such Meter of that type is found in this object
References m_meters.
Visibility UniverseObject::GetVisibility (int empire_id) const
returns the visibility status of this universe object relative to the input empire.
References Universe::GetObjectVisibilityByEmpire(), GetUniverse(), and ID().
Referenced by Universe::Destroy(), FleetWnd::FleetRightClicked(), Planet::GetVisibility(), FleetDataPanel::Init(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), Condition::VisibleToEmpire::Match(), Condition::anonymous_namespace{Condition.cpp}::VisibleToEmpireSimpleMatch::operator()(), ServerApp::PreCombatProcessTurns(), Ship::PublicName(), Fleet::PublicName(), SidePanel::PlanetPanel::RClick(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), and ShipDataPanel::SetShipIcon().
bool UniverseObject::HasSpecial (const std::string & name) const
returns true iff this object has a special with the indicated name
References m_specials.
Referenced by Empire::CheckProductionProgress(), and FreeOrionPython::WrapUniverseClasses().
bool UniverseObject::HasTag (const std::string & name) const virtual
returns true iff this object has the tag with the indicated name
Reimplemented in Building, Planet, Ship, and Field.
Referenced by Condition::anonymous_namespace{Condition.cpp}::HasTagSimpleMatch::operator()(), and FreeOrionPython::WrapUniverseClasses().
int UniverseObject::ID () const
returns the ID number of this object. Each object in FreeOrion has a unique ID number.
References m_id.
Referenced by FleetsListBox::AcceptDrops(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), MapWnd::AddFleetsStateChangedSignal(), ObjectListBox::AddObjectRow(), System::AddStarlane(), System::AddWormhole(), System::ApparentName(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetFighter(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipFighter(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), ObjectMap::AuditContainment(), AutomaticallyChosenColonyShip(), Fleet::BlockadedAtSystem(), anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders(), Planet::CardinalSuffix(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickColonize(), SidePanel::PlanetPanel::ClickInvade(), Field::Clone(), Building::Clone(), Ship::Clone(), Planet::Clone(), System::Clone(), Fleet::Clone(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), CombatInfo::CombatInfo(), Planet::Conquer(), FleetWnd::ContainsFleet(), Field::Copy(), Building::Copy(), Ship::Copy(), Planet::Copy(), System::Copy(), Fleet::Copy(), ObjectMap::CopyObject(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{ServerWrapper.cpp}::CreateField(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetFromShipsWithDesign(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsForShips(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsFromShipsForEachDesign(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), DualMeter::CurrentProjectedTarget(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::DefaultLocationForEmpire(), MapWnd::DeferredRefreshFleetButtons(), MapWnd::DispatchFleetsExploring(), MapWnd::DoFleetButtonsLayout(), SupplyManager::Dump(), Dump(), ValueRef::Variable< T >::Eval(), Effect::SetEmpireCapital::Execute(), Effect::SetOwner::Execute(), Effect::CreateBuilding::Execute(), Effect::Destroy::Execute(), Effect::AddStarlanes::Execute(), Effect::RemoveStarlanes::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), Effect::SetVisibility::Execute(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), DeleteFleetOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), SidePanel::FleetsInserted(), SidePanel::FleetsRemoved(), CombatInfo::ForceAtLeastBasicVisibility(), Fleet::GenerateFleetName(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), GetVisibility(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), MapWnd::InitFieldRenderingBuffers(), CombatInfo::InitializeObjectVisibility(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitTurn(), MapWnd::InitTurnRendering(), System::Insert(), anonymous_namespace{MapWnd.cpp}::IsQualifiedFleet(), Universe::JumpDistanceBetweenObjects(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Condition::Homeworld::Match(), Condition::Capital::Match(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), Fleet::MovementPhase(), Fleet::MovePath(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), ObjectListWnd::ObjectRightClicked(), ObjectListBox::ObjectShown(), anonymous_namespace{CombatSystem.cpp}::ObjectTargettableByEmpire(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ContainedBySimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ObjectIDSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::WithinStarlaneJumpsSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ExploredByEmpireSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), Planet::PopGrowthProductionResearchPhase(), PartsListBox::Populate(), ServerApp::PreCombatProcessTurns(), BuildingIndicator::RClick(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), Universe::RecursiveDestroy(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), ObjectListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), MapWnd::RefreshFleetResourceIndicator(), SidePanel::RefreshImpl(), SidePanel::RefreshInPreRender(), MapWnd::RemoveFleetsStateChangedSignal(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), BuildDesignatorWnd::SelectDefaultPlanet(), MapWnd::SelectFleet(), SetEmpireHomeworld(), SidePanel::PlanetPanel::SetFocus(), EncyclopediaDetailPanel::SetItem(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), Universe::ShortestPathDistance(), System::System(), System::SystemID(), MapWnd::SystemRightClicked(), anonymous_namespace{ValueRef.cpp}::TraceReference(), MapWnd::UniverseObjectDeleted(), ObjectListBox::UniverseObjectDeleted(), FleetDetailPanel::UniverseObjectDeleted(), SupplyManager::Update(), ResourcePool::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), ShipFightersBrowseWnd::UpdateEffectLabelsAndValues(), Universe::UpdateEmpireStaleObjectKnowledge(), ServerApp::UpdateMonsterTravelRestrictions(), SpeciesManager::UpdatePopulationCounter(), Empire::UpdateSupplyUnobstructedSystems(), Empire::UpdateUnobstructedFleets(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), anonymous_namespace{CombatSystem.cpp}::ValidTargetsForAttackerType(), System::VisibleStarlanesWormholes(), FreeOrionPython::WrapUniverseClasses(), ClientUI::ZoomToFleet(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToNextSystem(), MapWnd::ZoomToPrevOwnedSystem(), MapWnd::ZoomToPrevSystem(), and ClientUI::ZoomToSystem().
void UniverseObject::Init () protected
adds stealth meter
References AddMeter(), and METER_STEALTH.
Referenced by Building::Building(), Field::Field(), Fighter::Fighter(), Fleet::Fleet(), Planet::Planet(), Ship::Ship(), and System::System().
float UniverseObject::InitialMeterValue (MeterType type) const
returns this turn's initial value for the speicified meter type
References m_meters.
Referenced by ValueRef::Variable< T >::Eval(), FleetWnd::FleetRightClicked(), Planet::InitialMeterValue(), FleetWnd::SetStatIconValues(), FleetDataPanel::SetStatIconValues(), MultiIconValueIndicator::Update(), MilitaryPanel::Update(), ResourcePanel::Update(), and FreeOrionPython::WrapUniverseClasses().
const std::map<MeterType, Meter>& UniverseObject::Meters () const inline
returns this UniverseObject's meters
Referenced by Universe::InitMeterEstimatesAndDiscrepancies().
std::map<MeterType, Meter>& UniverseObject::Meters () inline
returns this UniverseObject's meters
void UniverseObject::Move (double x, double y)
moves this object by relative displacements x and y.
References m_x, m_y, and MoveTo().
virtual void UniverseObject::MovementPhase () inline virtual
Performs the movement that this object is responsible for this object's actions during the movement phase of a turn.
Reimplemented in Fleet.
void UniverseObject::MoveTo (int object_id)
calls MoveTo(TemporaryPtr<const UniverseObject>) with the object pointed to by object_id.
References GetUniverseObject().
Referenced by Universe::Delete(), System::Insert(), Move(), anonymous_namespace{Fleet.cpp}::MoveFleetWithShips(), and MoveTo().
void UniverseObject::MoveTo (TemporaryPtr< UniverseObject > object)
moves this object to exact map coordinates of specified object.
References ErrorLogger, MoveTo(), and X().
void UniverseObject::MoveTo (double x, double y)
moves this object to map coordinates (x, y).
References DebugLogger, GetUniverse(), m_name, m_x, m_y, and StateChangedSignal.
const std::string & UniverseObject::Name () const
returns the name of this object; some valid objects will have no name
References m_name.
Referenced by System::AddStarlane(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), Planet::CardinalSuffix(), Empire::CheckProductionProgress(), CombatInfo::CombatInfo(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), Planet::Copy(), MapWnd::DeferredRefreshFleetButtons(), Dump(), ValueRef::NameLookup::Eval(), ValueRef::Variable< T >::Eval(), Effect::CreatePlanet::Execute(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), FleetWnd::FleetRightClicked(), anonymous_namespace{ServerWrapper.cpp}::GetName(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), ShipDataPanel::Init(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), Fleet::MovePath(), ObjectListBox::ObjectStateChanged(), anonymous_namespace{CombatSystem.cpp}::ObjectTargettableByEmpire(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackersAndTargets(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateEmpireTargets(), Ship::PublicName(), Fleet::PublicName(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), SystemIcon::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), SidePanel::PlanetPanelContainer::SetPlanets(), FleetDetailPanel::ShipRightClicked(), anonymous_namespace{CombatSystem.cpp}::ShipWeaponsStrengths(), anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), System::System(), anonymous_namespace{ValueRef.cpp}::TraceReference(), BuildingsPanel::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), ShipDamageBrowseWnd::UpdateEffectLabelsAndValues(), ProductionWnd::UpdateInfoPanel(), SystemResourceSummaryBrowseWnd::UpdateProduction(), FreeOrionPython::WrapUniverseClasses(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToNextSystem(), MapWnd::ZoomToPrevOwnedSystem(), and MapWnd::ZoomToPrevSystem().
float UniverseObject::NextTurnCurrentMeterValue (MeterType type) const virtual
returns an estimate of the next turn's current value of the specified meter type
Reimplemented in Planet, and Ship.
References CurrentMeterValue().
Referenced by DualMeter::CurrentProjectedTarget(), Ship::NextTurnCurrentMeterValue(), Planet::NextTurnCurrentMeterValue(), Empire::UpdateSystemSupplyRanges(), and FreeOrionPython::WrapUniverseClasses().
UniverseObjectType UniverseObject::ObjectType () const virtual
emitted when the UniverseObject is altered in any way
Reimplemented in Fleet, Building, System, Planet, Ship, Field, and Fighter.
Referenced by ObjectMap::AuditContainment(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), Empire::CheckProductionProgress(), IncapacitationEvent::CombatLogDescription(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), anonymous_namespace{CombatLogWnd.cpp}::CountByOwner(), Dump(), ValueRef::Variable< T >::Eval(), Effect::MoveTo::Execute(), CombatInfo::ForceAtLeastBasicVisibility(), anonymous_namespace{Universe.cpp}::GetDesignIDFromObject(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{CombatSystem.cpp}::GetMonsterDetection(), anonymous_namespace{Universe.cpp}::GetSpeciesFromObject(), MapWnd::InitVisibilityRadiiRenderingBuffers(), System::Insert(), AIInterface::IssueGiveObjectToEmpireOrder(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), ObjectListWnd::ObjectRightClicked(), ObjectListBox::ObjectShown(), ObjectListBox::ObjectStateChanged(), anonymous_namespace{CombatSystem.cpp}::ObjectTargettableByEmpire(), anonymous_namespace{CombatSystem.cpp}::ObjectTargettableByMonsters(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), anonymous_namespace{CombatSystem.cpp}::ObjectTypeCanBeAttacked(), Condition::anonymous_namespace{Condition.cpp}::TypeSimpleMatch::operator()(), anonymous_namespace{Universe.cpp}::PropagateVisibilityToContainerObjects(), anonymous_namespace{CombatEvents.cpp}::PublicNameLink(), Universe::RecursiveDestroy(), ObjectListBox::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), MapWnd::SystemRightClicked(), anonymous_namespace{ValueRef.cpp}::TraceReference(), SupplyManager::Update(), SpeciesManager::UpdatePopulationCounter(), and anonymous_namespace{CombatSystem.cpp}::ValidTargetsForAttackerType().
bool UniverseObject::OwnedBy (int empire) const
returns true iff the empire with id empire owns this object; unowned objects always return false;
References ALL_EMPIRES, and Owner().
Referenced by AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), SidePanel::PlanetPanel::ClickColonize(), Planet::Colonize(), CreateFleetArrivedAtDestinationSitRep(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsForShips(), FleetWnd::DoLayout(), FleetDataPanel::DropsAcceptable(), SidePanel::PlanetPanel::EnableOrderIssuing(), RenameOrder::ExecuteImpl(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), DeleteFleetOrder::ExecuteImpl(), ChangeFocusOrder::ExecuteImpl(), FleetMoveOrder::FleetMoveOrder(), FleetWnd::FleetRightClicked(), Universe::ForgetKnownObject(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), FleetDataPanel::Init(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), AIInterface::IssueAggressionOrder(), AIInterface::IssueBombardOrder(), AIInterface::IssueChangeFocusOrder(), AIInterface::IssueColonizeOrder(), AIInterface::IssueFleetMoveOrder(), AIInterface::IssueFleetTransferOrder(), AIInterface::IssueGiveObjectToEmpireOrder(), AIInterface::IssueInvadeOrder(), AIInterface::IssueNewFleetOrder(), AIInterface::IssueRenameOrder(), AIInterface::IssueScrapOrder(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), anonymous_namespace{CombatSystem.cpp}::ObjectDiplomaticallyAttackableByEmpire(), anonymous_namespace{SystemResourceSummaryBrowseWnd.cpp}::ObjectResourceConsumption(), ObjectListWnd::ObjectRightClicked(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), MapWnd::PlotFleetMovement(), ShipDesign::ProductionLocation(), Ship::PublicName(), Fleet::PublicName(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), MapWnd::RefreshFleetResourceIndicator(), SidePanel::RefreshImpl(), Planet::Reset(), SidePanel::PlanetPanel::SetFocus(), FleetWnd::SetStatIconValues(), FleetDetailPanel::ShipRightClicked(), SupplyManager::Update(), SystemResourceSummaryBrowseWnd::UpdateAllocation(), SystemResourceSummaryBrowseWnd::UpdateProduction(), Empire::UpdateSupplyUnobstructedSystems(), Empire::UpdateUnobstructedFleets(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), and FreeOrionPython::WrapUniverseClasses().
int UniverseObject::Owner () const virtual
returns the ID of the empire that owns this object, or ALL_EMPIRES if there is no owner
Reimplemented in System.
References m_owner_empire_id.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), anonymous_namespace{CombatSystem.cpp}::AttackFighterFighter(), anonymous_namespace{CombatSystem.cpp}::AttackFighterShip(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetFighter(), anonymous_namespace{CombatSystem.cpp}::AttackPlanetShip(), anonymous_namespace{CombatSystem.cpp}::AttackShipFighter(), anonymous_namespace{CombatSystem.cpp}::AttackShipPlanet(), anonymous_namespace{CombatSystem.cpp}::AttackShipShip(), AutomaticallyChosenColonyShip(), Fleet::BlockadedAtSystem(), BuildingsPanel::BuildingsPanel(), Fleet::CalculateRouteTo(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), CombatInfo::CombatInfo(), anonymous_namespace{CombatSystem.cpp}::CombatRound(), anonymous_namespace{CombatLogWnd.cpp}::CountByOwner(), Universe::CountDestructionInStats(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateFleetArrivedAtDestinationSitRep(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), ColorByOwner::Decorate(), MapWnd::DeferredRefreshFleetButtons(), ValueRef::Variable< T >::Eval(), Effect::SetOwner::Execute(), Effect::CreateBuilding::Execute(), Effect::MoveTo::Execute(), Effect::SetDestination::Execute(), Effect::Victory::Execute(), RenameOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), anonymous_namespace{Effect.cpp}::ExploreSystem(), FleetWnd::FleetRightClicked(), FleetWnd::FleetWnd(), CombatInfo::ForceAtLeastBasicVisibility(), anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{ServerWrapper.cpp}::GetOwner(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), FleetButton::Init(), MapWnd::InitVisibilityRadiiRenderingBuffers(), AIInterface::IssueBombardOrder(), AIInterface::IssueGiveObjectToEmpireOrder(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Condition::EmpireMeterValue::Match(), Fleet::MovementPhase(), Fleet::MovePath(), anonymous_namespace{CombatSystem.cpp}::ObjectDiplomaticallyAttackableByEmpire(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EmpireStockpileValueSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasTechSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipDesignAvailableSimpleMatch::operator()(), OwnedBy(), OwnerColoredSystemName::OwnerColoredSystemName(), Planet::PopGrowthProductionResearchPhase(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackersAndTargets(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateEmpireTargets(), Ship::PublicName(), SidePanel::PlanetPanel::RClick(), anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), ShipDataPanel::Refresh(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), MapWnd::SetFleetMovementLine(), MapWnd::SetProjectedFleetMovementLine(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), Fleet::ShortenRouteToEndAtSystem(), Unowned(), BuildingsPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), MeterBrowseWnd::UpdateEffectLabelsAndValues(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), anonymous_namespace{Effect.cpp}::UpdateFleetRoute(), Empire::UpdateSupplyUnobstructedSystems(), anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), StationaryFleetVisitor::Visit(), OrderedMovingFleetVisitor::Visit(), MovingFleetVisitor::Visit(), and FreeOrionPython::WrapUniverseClasses().
virtual void UniverseObject::PopGrowthProductionResearchPhase () inline virtual
performs the movement that this object is responsible for this object's actions during the pop growth/production/research phase of a turn.
Reimplemented in Planet, and Ship.
Referenced by Ship::PopGrowthProductionResearchPhase(), and Planet::PopGrowthProductionResearchPhase().
const std::string & UniverseObject::PublicName (int empire_id) const virtual
returns the name of this objectas it appears to empire empire_id
Reimplemented in Fleet, Ship, and Field.
References m_name.
Referenced by System::ApparentName(), SupplyManager::Dump(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), ParticipantBar::ParticipantBar(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelObjectTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), and CombatLogWnd::CombatLogWndImpl::SetLog().
void UniverseObject::RemoveSpecial (const std::string & name) virtual
removes the Special name from this object, if it is already present
References m_specials.
Referenced by Effect::RemoveSpecial::Execute(), and anonymous_namespace{ServerWrapper.cpp}::RemoveSpecial().
void UniverseObject::Rename (const std::string & name)
renames this object to name
References m_name, and StateChangedSignal.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters(), Building::Building(), Empire::CheckProductionProgress(), Planet::Copy(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldImpl(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{ServerWrapper.cpp}::CreatePlanet(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), RenameOrder::ExecuteImpl(), NewFleetOrder::ExecuteImpl(), Field::Field(), and anonymous_namespace{ServerWrapper.cpp}::SetName().
void UniverseObject::ResetPairedActiveMeters () virtual
Sets current value of active paired meters (the non-max non-target meters that have a max or target meter associated with them) back to the initial value the meter had at the start of this turn.
Reimplemented in Ship.
References GetMeter(), METER_POPULATION, and METER_TROOPS.
Referenced by Ship::ResetPairedActiveMeters().
void UniverseObject::ResetTargetMaxUnpairedMeters () virtual
Sets current value of max, target and unpaired meters in in this UniverseObject to Meter::DEFAULT_VALUE. This should be done before any Effects that alter these meter(s) act on the object.
Reimplemented in Fleet, Planet, System, Ship, Building, and Field.
References GetMeter(), and METER_STEALTH.
Referenced by Field::ResetTargetMaxUnpairedMeters(), Building::ResetTargetMaxUnpairedMeters(), Ship::ResetTargetMaxUnpairedMeters(), Planet::ResetTargetMaxUnpairedMeters(), System::ResetTargetMaxUnpairedMeters(), and Fleet::ResetTargetMaxUnpairedMeters().
template<class Archive > void UniverseObject::serialize (Archive & ar, const unsigned int version) private
References m_created_on_turn, m_id, m_meters, m_name, m_owner_empire_id, m_specials, m_system_id, m_x, and m_y.
void UniverseObject::SetID (int id)
sets the ID number of the object to id
References m_id, and StateChangedSignal.
Referenced by anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters().
void UniverseObject::SetOwner (int id) virtual
sets the empire that owns this object
Reimplemented in System.
References m_owner_empire_id, and StateChangedSignal.
Referenced by AutomaticallyChosenColonyShip(), Building::Building(), Planet::Colonize(), Planet::Conquer(), Moderator::SetOwner::Execute(), Effect::SetOwner::Execute(), Effect::CreateBuilding::Execute(), Fighter::Fighter(), Fleet::Fleet(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), SidePanel::PlanetPanel::Refresh(), Building::Reset(), Planet::Reset(), Ship::Ship(), and AIInterface::UpdateMeterEstimates().
void UniverseObject::SetSpecialCapacity (const std::string & name, float capacity)
copies data from copied_object to this object, limited to only copy data about the copied object that is known to the empire with id empire_id (or all data if empire_id is ALL_EMPIRES)
References AddSpecial(), and m_specials.
Referenced by Empire::CheckProductionProgress(), and Effect::AddSpecial::Execute().
void UniverseObject::SetSystem (int sys)
assigns this object to a System. does not actually move object in universe
References m_system_id, and StateChangedSignal.
Referenced by anonymous_namespace{Effect.cpp}::CreateNewFleet(), System::Insert(), Fleet::MovementPhase(), and System::System().
int UniverseObject::SpecialAddedOnTurn (const std::string & name) const
returns the turn on which the special with name name was added to this object, or INVALID_GAME_TURN if that special is not present
References INVALID_GAME_TURN, and m_specials.
Referenced by FreeOrionPython::WrapUniverseClasses().
float UniverseObject::SpecialCapacity (const std::string & name) const
emitted when the UniverseObject is altered in any way
References m_specials.
Referenced by Empire::CheckProductionProgress(), and Effect::AddSpecial::Execute().
const std::map< std::string, std::pair< int, float > > & UniverseObject::Specials () const
returns the Specials attached to this object
References m_specials.
Referenced by Universe::GetObjectVisibleSpecialsByEmpire(), Condition::anonymous_namespace{Condition.cpp}::HasSpecialSimpleMatch::operator()(), anonymous_namespace{Universe.cpp}::SetEmpireSpecialVisibilities(), and SpecialsPanel::Update().
int UniverseObject::SystemID () const virtual
returns the ID number of the system in which this object can be found, or INVALID_OBJECT_ID if the object is not within any system
Reimplemented in System.
References m_system_id.
Referenced by ObjectMap::AuditContainment(), AutomaticallyChosenBombardShips(), AutomaticallyChosenColonyShip(), AutomaticallyChosenInvasionShips(), Fleet::BlockadedAtSystem(), Fleet::CalculateRouteTo(), Planet::CardinalSuffix(), Empire::CheckProductionProgress(), anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), Planet::Conquer(), Field::ContainedBy(), Ship::ContainedBy(), Building::ContainedBy(), Fleet::ContainedBy(), Planet::ContainedBy(), Field::ContainerObjectID(), Fleet::ContainerObjectID(), Planet::ContainerObjectID(), anonymous_namespace{ServerWrapper.cpp}::CreateBuilding(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), anonymous_namespace{FleetWnd.cpp}::CreateNewFleetsForShips(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), MapWnd::DispatchFleetsExploring(), FleetDataPanel::DropsAcceptable(), Fleet::Dump(), Dump(), ValueRef::Variable< T >::Eval(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::AddStarlanes::Execute(), Effect::RemoveStarlanes::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::SetDestination::Execute(), NewFleetOrder::ExecuteImpl(), FleetMoveOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), DeleteFleetOrder::ExecuteImpl(), anonymous_namespace{FleetWnd.cpp}::FleetDestinationText(), FleetWnd::FleetRightClicked(), anonymous_namespace{ValueRef.cpp}::FollowReference(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), anonymous_namespace{ServerApp.cpp}::HandleScrapping(), FleetButton::Init(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitVisibilityRadiiRenderingBuffers(), anonymous_namespace{SidePanel.cpp}::IsAvailable(), anonymous_namespace{MapWnd.cpp}::IsDepartingFromSystem(), anonymous_namespace{MapWnd.cpp}::IsMoving(), anonymous_namespace{MapWnd.cpp}::IsStationaryInSystem(), AIInterface::IssueBombardOrder(), AIInterface::IssueColonizeOrder(), AIInterface::IssueFleetMoveOrder(), AIInterface::IssueFleetTransferOrder(), AIInterface::IssueGiveObjectToEmpireOrder(), AIInterface::IssueInvadeOrder(), AIInterface::IssueNewFleetOrder(), Universe::JumpDistanceBetweenObjects(), Condition::ContainedBy::Match(), Condition::StarType::Match(), Condition::Stationary::Match(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), Fleet::MovementPhase(), Fleet::MovePath(), Condition::anonymous_namespace{Condition.cpp}::ContainedBySimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::InSystemSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::StarTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::FleetSupplyableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ResourceSupplySimpleMatch::operator()(), MapWnd::PlanetDoubleClicked(), MapWnd::PlotFleetMovement(), ServerApp::PreCombatProcessTurns(), SidePanel::PlanetPanel::RClick(), Universe::RecursiveDestroy(), FleetWnd::Refresh(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelEmpireTag(), SetEmpireHomeworld(), MapWnd::SetFleetMovementLine(), SidePanel::PlanetPanelContainer::SetPlanets(), MapWnd::SetProjectedFleetMovementLine(), Fleet::SetRoute(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), Universe::ShortestPathDistance(), anonymous_namespace{ValueRef.cpp}::TraceReference(), BuildingsPanel::Update(), SupplyManager::Update(), ResourcePool::Update(), anonymous_namespace{Effect.cpp}::UpdateFleetRoute(), ServerApp::UpdateMonsterTravelRestrictions(), Empire::UpdateSupplyUnobstructedSystems(), Empire::UpdateSystemSupplyRanges(), anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), OrderedMovingFleetVisitor::Visit(), MovingFleetVisitor::Visit(), FreeOrionPython::WrapUniverseClasses(), MapWnd::ZoomToHomeSystem(), and MapWnd::ZoomToSystemWithWastedPP().
std::set< std::string > UniverseObject::Tags () const virtual
returns the capacity of the special with name name or 0 if that special is not present
returns all tags this object has
Reimplemented in Building, Planet, Ship, and Field.
Referenced by Condition::anonymous_namespace{Condition.cpp}::HasTagSimpleMatch::operator()(), ConditionWidget::UpdateParameterControls(), and FreeOrionPython::WrapUniverseClasses().
bool UniverseObject::Unowned () const
returns true iff there are no owners of this object
References ALL_EMPIRES, and Owner().
Referenced by AutomaticallyChosenColonyShip(), Fleet::BlockadedAtSystem(), SidePanel::PlanetPanel::ClickBombard(), SidePanel::PlanetPanel::ClickInvade(), anonymous_namespace{ServerApp.cpp}::ColonizePlanet(), anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem(), CombatInfo::CombatInfo(), Ship::Copy(), Fleet::Copy(), CreateFleetArrivedAtDestinationSitRep(), ColorByOwner::Decorate(), Dump(), ColonizeOrder::ExecuteImpl(), InvadeOrder::ExecuteImpl(), BombardOrder::ExecuteImpl(), FleetWnd::FleetRightClicked(), Universe::GetEffectsAndTargets(), anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem(), anonymous_namespace{CombatSystem.cpp}::GetMonsterDetection(), anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem(), anonymous_namespace{ServerApp.cpp}::HandleColonization(), anonymous_namespace{ServerApp.cpp}::HandleGifting(), anonymous_namespace{ServerApp.cpp}::HandleInvasion(), MapWnd::InitVisibilityRadiiRenderingBuffers(), AIInterface::IssueBombardOrder(), AIInterface::IssueColonizeOrder(), AIInterface::IssueInvadeOrder(), anonymous_namespace{CombatSystem.cpp}::ObjectDiplomaticallyAttackableByEmpire(), anonymous_namespace{CombatSystem.cpp}::ObjectDiplomaticallyAttackableByMonsters(), anonymous_namespace{CombatSystem.cpp}::ObjectTypeCanBeAttacked(), Condition::anonymous_namespace{Condition.cpp}::EmpireAffiliationSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::EmpireStockpileValueSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasTechSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasBuildingTypeAvailableSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OwnerHasShipDesignAvailableSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), Ship::PublicName(), Fleet::PublicName(), SidePanel::PlanetPanel::RClick(), FleetWnd::Refresh(), ShipDataPanel::Refresh(), SidePanel::PlanetPanel::Refresh(), FleetDataPanel::Refresh(), anonymous_namespace{Universe.cpp}::SetEmpireOwnedObjectVisibilities(), MapWnd::SetFleetMovementLine(), anonymous_namespace{Universe.cpp}::SetSameSystemPlanetsVisible(), FleetWnd::SetStatIconValues(), AIInterface::UpdateMeterEstimates(), ServerApp::UpdateMonsterTravelRestrictions(), anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), StationaryFleetVisitor::Visit(), OrderedMovingFleetVisitor::Visit(), MovingFleetVisitor::Visit(), and FreeOrionPython::WrapUniverseClasses().
std::set< int > UniverseObject::VisibleContainedObjectIDs (int empire_id) const
returns the subset of contained object IDs that is visible to empire with id empire_id
References ContainedObjectIDs(), Universe::GetObjectVisibilityByEmpire(), and GetUniverse().
Referenced by Planet::Copy(), System::Copy(), Fleet::Copy(), and Universe::ForgetKnownObject().
double UniverseObject::X () const virtual
the X-coordinate of this object
References m_x.
Referenced by Fleet::CalculateRouteTo(), MapWnd::CenterOnObject(), Empire::CheckProductionProgress(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), MapWnd::DeferredRefreshFleetButtons(), MapWnd::DoFieldIconsLayout(), MapWnd::DoFleetButtonsLayout(), MapWnd::DoSystemIconsLayout(), Dump(), ValueRef::Variable< T >::Eval(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateField::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), NewFleetOrder::ExecuteImpl(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{ServerWrapper.cpp}::GetX(), Field::InField(), FleetButton::Init(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitSystemRenderingBuffers(), MapWnd::InitVisibilityRadiiRenderingBuffers(), System::Insert(), Condition::anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose(), Condition::anonymous_namespace{Condition.cpp}::LanesCross(), Universe::LinearDistance(), Fleet::MovePath(), MoveTo(), MapWnd::MovingFleetMapPositionOnLane(), anonymous_namespace{UniverseWrapper.cpp}::ObjectInField(), Condition::anonymous_namespace{Condition.cpp}::ObjectTooCloseToLane(), Condition::anonymous_namespace{Condition.cpp}::WithinDistanceSimpleMatch::operator()(), anonymous_namespace{Fleet.cpp}::PathLength(), FleetWnd::Refresh(), anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarane(), MapWnd::SetProjectedFleetMovementLine(), Fleet::SetRoute(), Universe::ShortestPathDistance(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), and FreeOrionPython::WrapUniverseClasses().
double UniverseObject::Y () const virtual
the Y-coordinate of this object
References m_y.
Referenced by Fleet::CalculateRouteTo(), MapWnd::CenterOnObject(), Empire::CheckProductionProgress(), anonymous_namespace{ServerWrapper.cpp}::CreateFieldInSystem(), anonymous_namespace{ServerWrapper.cpp}::CreateFleet(), anonymous_namespace{Effect.cpp}::CreateNewFleet(), MapWnd::DeferredRefreshFleetButtons(), MapWnd::DoFieldIconsLayout(), MapWnd::DoFleetButtonsLayout(), MapWnd::DoSystemIconsLayout(), Dump(), ValueRef::ComplexVariable< T >::Eval(), Effect::CreateField::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), Effect::MoveTowards::Execute(), NewFleetOrder::ExecuteImpl(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionsPotentiallyDetectableObjects(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{ServerWrapper.cpp}::GetY(), Field::InField(), FleetButton::Init(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitScaleCircleRenderingBuffer(), MapWnd::InitStarlaneRenderingBuffers(), MapWnd::InitSystemRenderingBuffers(), MapWnd::InitVisibilityRadiiRenderingBuffers(), System::Insert(), Condition::anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose(), Condition::anonymous_namespace{Condition.cpp}::LanesCross(), Universe::LinearDistance(), Fleet::MovePath(), MapWnd::MovingFleetMapPositionOnLane(), anonymous_namespace{UniverseWrapper.cpp}::ObjectInField(), Condition::anonymous_namespace{Condition.cpp}::ObjectTooCloseToLane(), Condition::anonymous_namespace{Condition.cpp}::WithinDistanceSimpleMatch::operator()(), anonymous_namespace{Fleet.cpp}::PathLength(), FleetWnd::Refresh(), anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarane(), MapWnd::SetProjectedFleetMovementLine(), Fleet::SetRoute(), Universe::ShortestPathDistance(), anonymous_namespace{FleetWnd.cpp}::SystemNameNearestToFleet(), anonymous_namespace{FleetWnd.cpp}::ValidFleetMerge(), anonymous_namespace{FleetWnd.cpp}::ValidShipTransfer(), and FreeOrionPython::WrapUniverseClasses().
Friends And Related Function Documentation
template<class T > void boost::checked_delete (T * x) friend
template<class T > void boost::python::detail::value_destroyer (T const volatile * p) friend
friend class boost::serialization::access friend
friend class ObjectMap friend
friend class Universe friend
Member Data Documentation
const int UniverseObject::INVALID_OBJECT_AGE = -(1 << 30) - 1 static
the age returned by UniverseObject::AgeInTurns() if the current turn is INVALID_GAME_TURN, or if the turn on which an object was created is INVALID_GAME_TURN
Referenced by AgeInTurns().
const double UniverseObject::INVALID_POSITION = -100000.0 static
the position in x and y at which default-constructed objects are placed
Referenced by Universe::Delete(), MapWnd::DoFleetButtonsLayout(), anonymous_namespace{ServerWrapper.cpp}::GetPos(), anonymous_namespace{ServerWrapper.cpp}::GetX(), anonymous_namespace{ServerWrapper.cpp}::GetY(), anonymous_namespace{ServerWrapper.cpp}::InvalidPosition(), MapWnd::MovingFleetMapPositionOnLane(), and anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarane().
int UniverseObject::m_created_on_turn private
Referenced by AgeInTurns(), Copy(), CreationTurn(), Dump(), serialize(), and UniverseObject().
int UniverseObject::m_id private
Referenced by Copy(), ID(), serialize(), and SetID().
std::map<MeterType, Meter> UniverseObject::m_meters private
Referenced by AddMeter(), CensoredMeters(), Copy(), CurrentMeterValue(), Dump(), GetMeter(), InitialMeterValue(), and serialize().
std::string UniverseObject::m_name protected
Referenced by Field::Copy(), Building::Copy(), Ship::Copy(), Planet::Copy(), System::Copy(), Fleet::Copy(), Copy(), MoveTo(), Name(), PublicName(), Rename(), and serialize().
int UniverseObject::m_owner_empire_id private
Referenced by Copy(), Dump(), Owner(), serialize(), and SetOwner().
std::map<std::string, std::pair<int, float> > UniverseObject::m_specials private
Referenced by AddSpecial(), Copy(), Dump(), HasSpecial(), RemoveSpecial(), serialize(), SetSpecialCapacity(), SpecialAddedOnTurn(), SpecialCapacity(), and Specials().
int UniverseObject::m_system_id private
Referenced by Copy(), serialize(), SetSystem(), and SystemID().
double UniverseObject::m_x private
Referenced by Copy(), Move(), MoveTo(), serialize(), and X().
double UniverseObject::m_y private
Referenced by Copy(), Move(), MoveTo(), serialize(), and Y().
const int UniverseObject::SINCE_BEFORE_TIME_AGE = (1 << 30) + 1 static
the age returned by UniverseObject::AgeInTurns() if an object was created on turn BEFORE_FIRST_TURN
Referenced by AgeInTurns().
StateChangedSignalType UniverseObject::StateChangedSignal mutable
emitted when the UniverseObject is altered in any way
Referenced by Planet::AddBuilding(), MapWnd::AddFleetsStateChangedSignal(), ObjectListBox::AddObjectRow(), Fleet::AddShips(), System::AddStarlane(), System::AddWormhole(), NewFleetOrder::ExecuteImpl(), FleetTransferOrder::ExecuteImpl(), SidePanel::FleetsInserted(), ShipDataPanel::Init(), FleetDataPanel::Init(), System::Insert(), anonymous_namespace{FleetWnd.cpp}::MergeFleetsIntoFleet(), MoveTo(), Ship::PopGrowthProductionResearchPhase(), Planet::PopGrowthProductionResearchPhase(), SystemIcon::Refresh(), SidePanel::PlanetPanel::Refresh(), SidePanel::RefreshInPreRender(), System::Remove(), Planet::RemoveBuilding(), Fleet::RemoveShips(), System::RemoveStarlane(), System::RemoveWormhole(), Rename(), Fleet::SetAggressive(), Ship::SetArrivedOnTurn(), Ship::SetBombardPlanet(), Ship::SetColonizePlanet(), FleetDetailPanel::SetFleet(), Ship::SetFleetID(), Planet::SetGiveToEmpire(), Fleet::SetGiveToEmpire(), SetID(), Ship::SetInvadePlanet(), Planet::SetIsAboutToBeBombarded(), Planet::SetIsAboutToBeColonized(), Planet::SetIsAboutToBeInvaded(), Building::SetOrderedScrapped(), Ship::SetOrderedScrapped(), Planet::SetOriginalType(), System::SetOverlayTexture(), SetOwner(), Building::SetPlanetID(), Fleet::SetRoute(), Planet::SetSize(), System::SetStarType(), Planet::SetSurfaceTexture(), SetSystem(), and Planet::SetType().
The documentation for this class was generated from the following files:
UniverseObject.h
UniverseObject.cpp
SerializeUniverse.cpp