FreeOrion: OptionsBar Class Reference
OptionsBar Class Reference
A Bar that contains the display options.
Classes
struct ToggleData
Public Member Functions
OptionsBar (std::unique_ptr< BarSizer > &sizer)
virtual ~OptionsBar ()
void DoLayout ()
GG::Pt MinUsableSize () const override
Public Attributes
boost::signals2::signal< void()> ChangedSignal
Private Attributes
std::unique_ptr< BarSizer > & m_sizer
std::vector< ToggleData * > m_toggles
Detailed Description
A Bar that contains the display options.
Constructor & Destructor Documentation
OptionsBar::OptionsBar (std::unique_ptr< BarSizer > & sizer) inline
References anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEALTH_SMOOTH, anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_HEIGHT_PROPORTIONAL, anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_BAR_WIDTH_PROPORTIONAL, anonymous_namespace{GraphicalSummary.cpp}::TOGGLE_GRAPH_HEIGHT_PROPORTIONAL, and UserString().
virtual OptionsBar::~OptionsBar () inline virtual
Member Function Documentation
void OptionsBar::DoLayout () inline
References ClientUI::GetFont(), parse::label(), anonymous_namespace{GraphicalSummary.cpp}::OPTION_BUTTON_HEIGHT(), and anonymous_namespace{GraphicalSummary.cpp}::OPTION_BUTTON_PADDING().
Referenced by GraphicalSummaryWnd::DoLayout(), and OptionsBar::ToggleData::SetValue().
GG::Pt OptionsBar::MinUsableSize () const inline override
References anonymous_namespace{GraphicalSummary.cpp}::OPTION_BAR_HEIGHT(), and anonymous_namespace{GraphicalSummary.cpp}::OPTION_BUTTON_PADDING().
Referenced by GraphicalSummaryWnd::MinUsableSize().
Member Data Documentation
boost::signals2::signal<void ()> OptionsBar::ChangedSignal
Referenced by GraphicalSummaryWnd::GenerateGraph(), and OptionsBar::ToggleData::SetValue().
std::unique_ptr<BarSizer>& OptionsBar::m_sizer private
std::vector<ToggleData*> OptionsBar::m_toggles private
The documentation for this class was generated from the following file:
GraphicalSummary.cpp