FreeOrion: Effect::SetEmpireStockpile Class Reference
Effect::SetEmpireStockpile Class Reference
#include <Effect.h>
Public Member Functions
SetEmpireStockpile (ResourceType stockpile, ValueRef::ValueRefBase< double > *value)
SetEmpireStockpile (ValueRef::ValueRefBase< int > *empire_id, ResourceType stockpile, ValueRef::ValueRefBase< double > *value)
virtual ~SetEmpireStockpile ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< int > * m_empire_id
ResourceType m_stockpile
ValueRef::ValueRefBase< double > * m_value
Friends
class boost::serialization::access
Detailed Description
Sets the empire stockpile of the target's owning empire to value. If the target does not have exactly one owner, nothing is done.
Constructor & Destructor Documentation
Effect::SetEmpireStockpile::SetEmpireStockpile (ResourceType stockpile, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireStockpile::SetEmpireStockpile (ValueRef::ValueRefBase< int > * empire_id, ResourceType stockpile, ValueRef::ValueRefBase< double > * value)
Effect::SetEmpireStockpile::~SetEmpireStockpile () virtual
References m_empire_id, and m_value.
Member Function Documentation
std::string Effect::SetEmpireStockpile::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_empire_id, m_stockpile, and m_value.
void Effect::SetEmpireStockpile::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References DebugLogger, ValueRef::ValueRefBase< T >::Eval(), GetEmpire(), m_empire_id, m_stockpile, m_value, Empire::ResourceStockpile(), and Empire::SetResourceStockpile().
template<class Archive > void Effect::SetEmpireStockpile::serialize (Archive & ar, const unsigned int version) private
References m_empire_id, m_stockpile, and m_value.
void Effect::SetEmpireStockpile::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_empire_id, m_value, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<int>* Effect::SetEmpireStockpile::m_empire_id private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~SetEmpireStockpile().
ResourceType Effect::SetEmpireStockpile::m_stockpile private
Referenced by Dump(), Execute(), and serialize().
ValueRef::ValueRefBase<double>* Effect::SetEmpireStockpile::m_value private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~SetEmpireStockpile().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp