FreeOrion: MessageQueue Class Reference
MessageQueue Class Reference
#include <MessageQueue.h>
Public Member Functions
MessageQueue (boost::mutex &monitor)
void Clear ()
bool Empty () const
void EraseFirstSynchronousResponse (Message &message)
void PopFront (Message &message)
void PushBack (Message &message)
std::size_t Size () const
Private Attributes
boost::condition m_have_synchronous_response
boost::mutex & m_monitor
std::list< Message > m_queue
Detailed Description
A thread-safe message queue. The entire public interface is guarded with mutex locks.
Constructor & Destructor Documentation
MessageQueue::MessageQueue (boost::mutex & monitor)
Member Function Documentation
void MessageQueue::Clear ()
Empties the queue.
References m_monitor, and m_queue.
Referenced by ClientNetworking::NetworkingThread().
bool MessageQueue::Empty () const
Returns true iff the queue is empty.
References m_monitor, and m_queue.
Referenced by ClientNetworking::MessageAvailable().
void MessageQueue::EraseFirstSynchronousResponse (Message & message)
Returns the first synchronous repsonse message in the queue. If no such message is found, this function blocks the calling thread until a synchronous response element is added.
References m_have_synchronous_response, m_monitor, m_queue, and swap().
Referenced by ClientNetworking::SendSynchronousMessage().
void MessageQueue::PopFront (Message & message)
Returns the front message in the queue.
References m_monitor, m_queue, and swap().
Referenced by ClientNetworking::GetMessage().
void MessageQueue::PushBack (Message & message)
Adds message to the end of the queue.
References m_have_synchronous_response, m_monitor, m_queue, and swap().
Referenced by ClientNetworking::HandleMessageBodyRead().
std::size_t MessageQueue::Size () const
Returns the number of messages in the queue.
References m_monitor, and m_queue.
Member Data Documentation
boost::condition MessageQueue::m_have_synchronous_response private
Referenced by EraseFirstSynchronousResponse(), and PushBack().
boost::mutex& MessageQueue::m_monitor private
Referenced by Clear(), Empty(), EraseFirstSynchronousResponse(), PopFront(), PushBack(), and Size().
std::list<Message> MessageQueue::m_queue private
Referenced by Clear(), Empty(), EraseFirstSynchronousResponse(), PopFront(), PushBack(), and Size().
The documentation for this class was generated from the following files:
MessageQueue.h
MessageQueue.cpp