FreeOrion: TechTreeWnd::TechListBox Class Reference
TechTreeWnd::TechListBox Class Reference
Classes
class TechRow
Public Member Functions
Structors
TechListBox (GG::X w, GG::Y h)
virtual ~TechListBox ()
Accessors
std::set< std::string > GetCategoriesShown () const
std::set< TechStatus > GetTechStatusesShown () const
bool TechRowCmp (const GG::ListBox::Row &lhs, const GG::ListBox::Row &rhs, std::size_t column)
Mutators //@{
void Reset ()
void Update ()
void ShowCategory (const std::string &category)
void ShowAllCategories ()
void HideCategory (const std::string &category)
void HideAllCategories ()
void ShowStatus (TechStatus status)
void HideStatus (TechStatus status)
Public Member Functions inherited from CUIListBox
CUIListBox (void)
void Render () override
Public Attributes
TechClickSignalType TechDoubleClickedSignal
emitted when a technology is double-clicked
TechClickSignalType TechLeftClickedSignal
emitted when a technology is single-left-clicked
TechSignalType TechPediaDisplaySignal
emitted when requesting a pedia lookup
Private Member Functions
void Populate ()
void TechDoubleClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void TechLeftClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void TechPediaDisplay (const std::string &tech_name)
void TechRightClicked (GG::ListBox::iterator it, const GG::Pt &pt, const GG::Flags< GG::ModKey > &modkeys)
void ToggleSortCol (unsigned int col)
Private Attributes
std::multimap< std::string, TechRow * > m_all_tech_rows
std::set< std::string > m_categories_shown
GG::ListBox::Row * m_header_row
size_t m_previous_sort_col
std::set< TechStatus > m_tech_statuses_shown
Constructor & Destructor Documentation
TechTreeWnd::TechListBox::TechListBox (GG::X w, GG::Y h)
References TechTreeWnd::TechListBox::TechRow::ColAlignments(), TechTreeWnd::TechListBox::TechRow::ColWidths(), GetTechManager(), m_categories_shown, m_header_row, m_previous_sort_col, m_tech_statuses_shown, ClientUI::Pts(), ClientUI::ScrollWidth(), TechDoubleClicked(), TechLeftClicked(), TechRightClicked(), TechRowCmp(), ToggleSortCol(), and UserString().
TechTreeWnd::TechListBox::~TechListBox () virtual
References m_all_tech_rows.
Member Function Documentation
std::set< std::string > TechTreeWnd::TechListBox::GetCategoriesShown () const
References m_categories_shown.
std::set< TechStatus > TechTreeWnd::TechListBox::GetTechStatusesShown () const
References m_tech_statuses_shown.
void TechTreeWnd::TechListBox::HideAllCategories ()
References m_categories_shown, and Populate().
Referenced by TechTreeWnd::HideAllCategories().
void TechTreeWnd::TechListBox::HideCategory (const std::string & category)
References m_categories_shown, and Populate().
Referenced by TechTreeWnd::HideCategory().
void TechTreeWnd::TechListBox::HideStatus (TechStatus status)
References m_tech_statuses_shown, and Populate().
Referenced by TechTreeWnd::HideStatus().
void TechTreeWnd::TechListBox::Populate () private
References TechTreeWnd::Clear(), TechTreeWnd::TechListBox::TechRow::ColWidths(), DebugLogger, TechTreeWnd::TechListBox::TechRow::GetTech(), GetTechManager(), m_all_tech_rows, m_categories_shown, m_tech_statuses_shown, ClientUI::Pts(), ClientUI::ScrollWidth(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), TechTreeWnd::TechListBox::TechRow::Update(), and UserString().
Referenced by HideAllCategories(), HideCategory(), HideStatus(), Reset(), ShowAllCategories(), ShowCategory(), and ShowStatus().
void TechTreeWnd::TechListBox::Reset ()
References Populate().
Referenced by TechTreeWnd::Reset(), and TechTreeWnd::ShowListView().
void TechTreeWnd::TechListBox::ShowAllCategories ()
References TechManager::CategoryNames(), GetTechManager(), m_categories_shown, and Populate().
Referenced by TechTreeWnd::ShowAllCategories().
void TechTreeWnd::TechListBox::ShowCategory (const std::string & category)
References m_categories_shown, and Populate().
Referenced by TechTreeWnd::ShowCategory().
void TechTreeWnd::TechListBox::ShowStatus (TechStatus status)
References m_tech_statuses_shown, and Populate().
Referenced by TechTreeWnd::ShowStatus().
void TechTreeWnd::TechListBox::TechDoubleClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References TechTreeWnd::TechListBox::TechRow::GetTech(), and TechDoubleClickedSignal.
Referenced by TechListBox(), and TechRightClicked().
void TechTreeWnd::TechListBox::TechLeftClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References TechLeftClickedSignal.
Referenced by TechListBox().
void TechTreeWnd::TechListBox::TechPediaDisplay (const std::string & tech_name) private
References TechPediaDisplaySignal.
Referenced by TechRightClicked().
void TechTreeWnd::TechListBox::TechRightClicked (GG::ListBox::iterator it, const GG::Pt & pt, const GG::Flags< GG::ModKey > & modkeys) private
References AIInterface::EmpireID(), ResearchQueue::end(), ResearchQueue::find(), FlexibleFormat(), HumanClientApp::GetApp(), GetEmpire(), Empire::GetResearchQueue(), TechTreeWnd::TechListBox::TechRow::GetTech(), ResearchQueue::push_back(), TechDoubleClicked(), TechPediaDisplay(), Empire::TechResearched(), and UserString().
Referenced by TechListBox().
bool TechTreeWnd::TechListBox::TechRowCmp (const GG::ListBox::Row & lhs, const GG::ListBox::Row & rhs, std::size_t column)
References anonymous_namespace{TechTreeWnd.cpp}::GetLocale().
Referenced by TechListBox().
void TechTreeWnd::TechListBox::ToggleSortCol (unsigned int col) private
References m_previous_sort_col.
Referenced by TechListBox().
void TechTreeWnd::TechListBox::Update ()
References TechTreeWnd::TechListBox::TechRow::GetTech(), m_all_tech_rows, m_categories_shown, m_tech_statuses_shown, anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), and TechTreeWnd::TechListBox::TechRow::Update().
Referenced by TechTreeWnd::Update().
Member Data Documentation
std::multimap<std::string, TechRow*> TechTreeWnd::TechListBox::m_all_tech_rows private
Referenced by Populate(), Update(), and ~TechListBox().
std::set<std::string> TechTreeWnd::TechListBox::m_categories_shown private
Referenced by GetCategoriesShown(), HideAllCategories(), HideCategory(), Populate(), ShowAllCategories(), ShowCategory(), TechListBox(), and Update().
GG::ListBox::Row* TechTreeWnd::TechListBox::m_header_row private
Referenced by TechListBox().
size_t TechTreeWnd::TechListBox::m_previous_sort_col private
Referenced by TechListBox(), and ToggleSortCol().
std::set<TechStatus> TechTreeWnd::TechListBox::m_tech_statuses_shown private
Referenced by GetTechStatusesShown(), HideStatus(), Populate(), ShowStatus(), TechListBox(), and Update().
TechClickSignalType TechTreeWnd::TechListBox::TechDoubleClickedSignal mutable
emitted when a technology is double-clicked
Referenced by TechDoubleClicked(), and TechTreeWnd::TechTreeWnd().
TechClickSignalType TechTreeWnd::TechListBox::TechLeftClickedSignal mutable
emitted when a technology is single-left-clicked
Referenced by TechLeftClicked(), and TechTreeWnd::TechTreeWnd().
TechSignalType TechTreeWnd::TechListBox::TechPediaDisplaySignal mutable
emitted when requesting a pedia lookup
Referenced by TechPediaDisplay(), and TechTreeWnd::TechTreeWnd().
The documentation for this class was generated from the following file:
TechTreeWnd.cpp