FreeOrion: ClientUI.h File Reference
ClientUI.h File Reference
#include <boost/filesystem/path.hpp>
#include <GG/GGFwd.h>
#include "../universe/Enums.h"
#include "../util/Random.h"
Classes
class ClientUI
ClientUI Main Module This is the main class of the ClientUI module. it contains objects of many other classes and controls the display of all information onscreen.
struct StreamableColor
class TemporaryPtr< T >
Functions
int FontBasedUpscale (int x)
std::ostream & operator<< (std::ostream &os, const StreamableColor &clr)
std::istream & operator>> (std::istream &is, StreamableColor &clr)
Function Documentation
int FontBasedUpscale (int x)
Increases the given value when font size is larger than 12
References ClientUI::Pts().
Referenced by anonymous_namespace{ResourceBrowseWnd.cpp}::BrowseTextWidth(), anonymous_namespace{CensusBrowseWnd.cpp}::BrowseTextWidth(), GalaxySetupPanel::DefaultWidth(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndHeight(), anonymous_namespace{GalaxySetupWnd.cpp}::GalSetupWndWidth(), and ResourceBrowseWnd::ResourceBrowseWnd().
std::ostream& operator<< (std::ostream & os, const StreamableColor & clr)
References StreamableColor::a, StreamableColor::b, StreamableColor::g, and StreamableColor::r.
std::istream& operator>> (std::istream & is, StreamableColor & clr)
References StreamableColor::a, StreamableColor::b, StreamableColor::g, and StreamableColor::r.