FreeOrion: CommonFramework.cpp File Reference
CommonFramework.cpp File Reference
#include "CommonFramework.h"
#include "../util/Directories.h"
#include "../util/Logger.h"
#include "CommonWrappers.h"
#include <boost/python/docstring_options.hpp>
Functions
BOOST_PYTHON_MODULE (freeorion_logger)
const std::string GetPythonCommonDir ()
const std::string GetPythonDir ()
Function Documentation
BOOST_PYTHON_MODULE (freeorion_logger)
References FreeOrionPython::WrapLogger().
const std::string GetPythonCommonDir ()
References GetPythonDir().
Referenced by PythonBase::Initialize().
const std::string GetPythonDir ()
References GetResourceDir().
Referenced by GetPythonCommonDir(), GetPythonTurnEventsDir(), and GetPythonUniverseGeneratorDir().