FreeOrion: CUIDrawUtil.cpp File Reference
CUIDrawUtil.cpp File Reference
#include "CUIDrawUtil.h"
#include "ShaderProgram.h"
#include "../util/Logger.h"
#include "../util/Directories.h"
#include "../util/OptionsDB.h"
#include <GG/DrawUtil.h>
#include <cmath>
Classes
class ScanlineRenderer::Impl
Namespaces
anonymous_namespace{CUIDrawUtil.cpp}
Functions
void AdjustBrightness (GG::Clr &color, int amount, bool jointly_capped)
void AdjustBrightness (GG::Clr &color, double amount, bool jointly_capped)
void AngledCornerRectangle (const GG::Pt &ul, const GG::Pt &lr, GG::Clr color, GG::Clr border, int angle_offset, int thick, bool upper_left_angled, bool lower_right_angled, bool draw_bottom)
void BufferStoreAngledCornerRectangleVertices (GG::GL2DVertexBuffer &buffer, const GG::Pt &ul, const GG::Pt &lr, int angle_offset, bool upper_left_angled, bool lower_right_angled, bool connect_bottom_line)
void BufferStoreCircleArcVertices (GG::GL2DVertexBuffer &buffer, const GG::Pt &ul, const GG::Pt &lr, double theta1, double theta2, bool filled_shape, int num_slices, bool fan)
void BufferStoreIsoscelesTriangle (GG::GL2DVertexBuffer &buffer, const GG::Pt &ul, const GG::Pt &lr, ShapeOrientation orientation)
void BufferStorePartlyRoundedRectVertices (GG::GL2DVertexBuffer &buffer, const GG::Pt &ul, const GG::Pt &lr, int radius, bool ur_round, bool ul_round, bool ll_round, bool lr_round)
void BufferStoreRectangle (GG::GL2DVertexBuffer &buffer, const GG::Rect &area, const GG::Rect &border_thickness)
void CircleArc (const GG::Pt &ul, const GG::Pt &lr, double theta1, double theta2, bool filled_shape)
void anonymous_namespace{CUIDrawUtil.cpp}::FindIsoscelesTriangleVertices (const GG::Pt &ul, const GG::Pt &lr, ShapeOrientation orientation, double &x1_, double &y1_, double &x2_, double &y2_, double &x3_, double &y3_)
bool InAngledCornerRect (const GG::Pt &pt, const GG::Pt &ul, const GG::Pt &lr, int angle_offset, bool upper_left_angled, bool lower_right_angled)
bool InIsoscelesTriangle (const GG::Pt &pt, const GG::Pt &ul, const GG::Pt &lr, ShapeOrientation orientation)
bool InTriangle (const GG::Pt &pt, double x1, double y1, double x2, double y2, double x3, double y3)
void IsoscelesTriangle (const GG::Pt &ul, const GG::Pt &lr, ShapeOrientation orientation, GG::Clr color, bool border)
GG::Clr OpaqueColor (const GG::Clr &color)
void PartlyRoundedRect (const GG::Pt &ul, const GG::Pt &lr, int radius, bool ur_round, bool ul_round, bool ll_round, bool lr_round, bool fill)
void Triangle (double x1, double y1, double x2, double y2, double x3, double y3, GG::Clr color, bool border)
Variables
const double anonymous_namespace{CUIDrawUtil.cpp}::TWO_PI = 2.0 * 3.14159
Function Documentation
void AdjustBrightness (GG::Clr & color, int amount, bool jointly_capped = false)
adjusts the intensity of the color up or down by amount units per color channel; leaves alpha unchanged if jointly_capped is true then, if the original amount would out any of the rgb channel values above 255, amount for all channels is reduced so that the highest resulting rgb channel value is 255.
Referenced by ClientUI::ButtonHiliteBorderColor(), ClientUI::ButtonHiliteColor(), MapWnd::InitVisibilityRadiiRenderingBuffers(), CUI_MinRestoreButton::Render(), CUICheckBoxRepresenter::Render(), CUIRadioRepresenter::Render(), CUITabRepresenter::Render(), CUILabelButtonRepresenter::Render(), CUIIconButtonRepresenter::Render(), CUIScroll::ScrollTab::Render(), CUIDropDownList::Render(), CUIButton::RenderPressed(), CUIButton::RenderRollover(), CUIArrowButton::RenderRollover(), and Triangle().
void AdjustBrightness (GG::Clr & color, double amount, bool jointly_capped = false)
adjusts the intensity of the color up or down by multiplying the non-alpa channels by amount if jointly_capped is true then, if the original amount would out any of the rgb channel values above 255, amount for all channels is reduced so that the highest resulting rgb channel value is 255.
void AngledCornerRectangle (const GG::Pt & ul, const GG::Pt & lr, GG::Clr color, GG::Clr border, int angle_offset, int thick, bool upper_left_angled = true, bool lower_right_angled = true, bool draw_bottom = true)
Using immediate GL calls, renders a rectangle whose upper left and lower right corners are angled. If upper_left_angled == false, the upper left corner is drawn as a normal corner
References BufferStoreAngledCornerRectangleVertices().
Referenced by CUICheckBoxRepresenter::Render(), CUITabRepresenter::Render(), CUILabelButtonRepresenter::Render(), CUIIconButtonRepresenter::Render(), CUIScroll::ScrollTab::Render(), CUIButton::RenderPressed(), CUIButton::RenderRollover(), and CUIButton::RenderUnpressed().
void BufferStoreAngledCornerRectangleVertices (GG::GL2DVertexBuffer & buffer, const GG::Pt & ul, const GG::Pt & lr, int angle_offset, bool upper_left_angled = true, bool lower_right_angled = true, bool connect_bottom_line = true)
Stores, in buffer verticies in CCW order that outline a rectangle with upper left and lower right corners are angled.
Referenced by AngledCornerRectangle(), and CUIDropDownList::InitBuffer().
void BufferStoreCircleArcVertices (GG::GL2DVertexBuffer & buffer, const GG::Pt & ul, const GG::Pt & lr, double theta1, double theta2, bool filled_shape = false, int num_slices = 0, bool fan = true)
Stores, in buffer vertices in CCW order that outline a circular arc or num_slices indicates how many triangles to use to compose the circle, or if 0, indicates that the function should auto-determine how many slices. if fan is true, the vertices are stored as a triangle fan- compatible list, while false indicates a triangle list (where each triangle has all 3 vertices specified explicitly. filled_shape indicates that a vertex at the centre of the circle should be present and shared with all triangles.
References anonymous_namespace{SystemIcon.cpp}::PI.
Referenced by BufferStorePartlyRoundedRectVertices(), CircleArc(), MapWnd::InitFieldRenderingBuffers(), MapWnd::InitScaleCircleRenderingBuffer(), and MapWnd::InitVisibilityRadiiRenderingBuffers().
void BufferStoreIsoscelesTriangle (GG::GL2DVertexBuffer & buffer, const GG::Pt & ul, const GG::Pt & lr, ShapeOrientation orientation)
Stores, in buffer, vertices in CCW order that outline an isosceles triangle.
References anonymous_namespace{CUIDrawUtil.cpp}::FindIsoscelesTriangleVertices().
Referenced by CUIDropDownList::InitBuffer().
void BufferStorePartlyRoundedRectVertices (GG::GL2DVertexBuffer & buffer, const GG::Pt & ul, const GG::Pt & lr, int radius, bool ur_round, bool ul_round, bool ll_round, bool lr_round)
Stores, in buffer verticies in CCW order that outline rectangle with corners rounded with radius radrius as determined by the *_round parameters.
References BufferStoreCircleArcVertices(), and anonymous_namespace{SystemIcon.cpp}::PI.
Referenced by PartlyRoundedRect().
void BufferStoreRectangle (GG::GL2DVertexBuffer & buffer, const GG::Rect & area, const GG::Rect & border_thickness)
Stores verticies in CCW order that outline a rectangle
Parameters
[out] buffer Buffer to store verticies
[in] area Outside corners of rectangle
[in] border_thickness Thickness of border for each corner, drawn towards the interior of area.
Referenced by MultiTurnProgressBar::Render().
void CircleArc (const GG::Pt & ul, const GG::Pt & lr, double theta1, double theta2, bool filled_shape)
Draws a filled portion of a circle when filled_shape is true or an unfilled portion when filled_shape is false.
References BufferStoreCircleArcVertices().
Referenced by TechTreeWnd::LayoutPanel::TechPanel::Render(), ScanlineRenderer::Impl::RenderCircle(), MapWnd::RenderMovementLineETAIndicators(), FleetButton::RenderPressed(), FleetButton::RenderRollover(), and MapWnd::RenderSystems().
bool InAngledCornerRect (const GG::Pt & pt, const GG::Pt & ul, const GG::Pt & lr, int angle_offset, bool upper_left_angled = true, bool lower_right_angled = true)
returns true iff pt falls within rect, with the missing bits of the angled corners not catching the point. If upper_left_angled == false, the upper left corner is treated as a normal corner.
Referenced by CUIButton::InWindow().
bool InIsoscelesTriangle (const GG::Pt & pt, const GG::Pt & ul, const GG::Pt & lr, ShapeOrientation orientation)
returns true iff pt falls within the isosceles triangle described by the other parameters
References anonymous_namespace{CUIDrawUtil.cpp}::FindIsoscelesTriangleVertices(), and InTriangle().
Referenced by CUIArrowButton::InWindow().
bool InTriangle (const GG::Pt & pt, double x1, double y1, double x2, double y2, double x3, double y3)
Referenced by InIsoscelesTriangle().
void IsoscelesTriangle (const GG::Pt & ul, const GG::Pt & lr, ShapeOrientation orientation, GG::Clr color, bool border = true)
renders a triangle with two equal-length sides, oriented in the desired direction. The triangle will have a base length of one of (x2 - x1) and (y2 - y1), depending on orientation, and a height of the other.
References anonymous_namespace{CUIDrawUtil.cpp}::FindIsoscelesTriangleVertices(), and Triangle().
Referenced by CUIArrowButton::RenderRollover(), and CUIArrowButton::RenderUnpressed().
GG::Clr OpaqueColor (const GG::Clr & color)
returns fully opaque (max alpha channel) version of the color
Referenced by SystemResourceSummaryBrowseWnd::Render(), and MeterBrowseWnd::Render().
void PartlyRoundedRect (const GG::Pt & ul, const GG::Pt & lr, int radius, bool ur_round, bool ul_round, bool ll_round, bool lr_round, bool fill)
Draws a rectangle whose corners are rounded with radius radius as indicated by the *_round parameters. If fill is true, the resulting rectangle is solid; it is drawn in outline otherwise.
References BufferStorePartlyRoundedRectVertices().
Referenced by anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::Draw(), anonymous_namespace{ProductionWnd.cpp}::QueueProductionItemPanel::Draw(), and TechTreeWnd::LayoutPanel::TechPanel::Render().
void Triangle (double x1, double y1, double x2, double y2, double x3, double y3, GG::Clr color, bool border)
References AdjustBrightness().
Referenced by IsoscelesTriangle().