FreeOrion: IntValueRefParser.cpp File Reference
IntValueRefParser.cpp File Reference
#include "ValueRefParserImpl.h"
Classes
struct anonymous_namespace{IntValueRefParser.cpp}::castable_as_int_parser_rules
struct anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules
struct anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules
Namespaces
anonymous_namespace{IntValueRefParser.cpp}
parse
The namespace that encloses the script file lexer and parser.
Functions
castable_as_int_parser_rules & anonymous_namespace{IntValueRefParser.cpp}::get_castable_as_int_parser_rules ()
int_parser_rules & anonymous_namespace{IntValueRefParser.cpp}::get_int_parser_rules ()
simple_int_parser_rules & anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules ()
const variable_rule< int >::type & int_bound_variable ()
const name_token_rule & int_bound_variable_name ()
const int_rule & int_constant ()
const variable_rule< int >::type & int_free_variable ()
const name_token_rule & int_free_variable_name ()
const int_rule & int_simple ()
const statistic_rule< int >::type & int_var_statistic ()
template<>
value_ref_parser_rule< int >
::type & parse::value_ref_parser< int > ()
value_ref_parser_rule< int >
::type & parse::value_ref_parser_flexible_int ()
Function Documentation
const variable_rule<int>::type& int_bound_variable ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::bound_variable, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules().
const name_token_rule& int_bound_variable_name ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::bound_variable_name, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const int_rule& int_constant ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::constant, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const variable_rule<int>::type& int_free_variable ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::free_variable, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules().
const name_token_rule& int_free_variable_name ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::free_variable_name, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const int_rule& int_simple ()
References anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules(), and anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::simple.
Referenced by parse::double_complex_parser_rules::double_complex_parser_rules(), parse::int_complex_parser_rules::int_complex_parser_rules(), anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules::int_parser_rules(), and parse::string_complex_parser_rules::string_complex_parser_rules().
const statistic_rule<int>::type& int_var_statistic ()
References anonymous_namespace{IntValueRefParser.cpp}::get_int_parser_rules(), and anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules::statistic.
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), and parse::int_complex_parser_rules::int_complex_parser_rules().