FreeOrion: anonymous_namespace{EmpireManager.cpp} Namespace Reference
anonymous_namespace{EmpireManager.cpp} Namespace Reference
Functions
std::pair< int, int > DiploKey (int id1, int ind2)
Variables
const std::string EMPTY_STRING
Function Documentation
std::pair<int, int> anonymous_namespace{EmpireManager.cpp}::DiploKey (int id1, int ind2)
Referenced by EmpireManager::DiplomaticMessageAvailable(), EmpireManager::GetDiplomaticMessage(), EmpireManager::GetDiplomaticStatus(), EmpireManager::RemoveDiplomaticMessage(), EmpireManager::ResetDiplomacy(), EmpireManager::SetDiplomaticMessage(), and EmpireManager::SetDiplomaticStatus().
Variable Documentation
const std::string anonymous_namespace{EmpireManager.cpp}::EMPTY_STRING
Referenced by EmpireManager::GetEmpireName().