FreeOrion: boost Namespace Reference
boost Namespace Reference
Namespaces
serialization
spirit
Classes
struct hash< TemporaryPtr< const Y > >
struct property_traits< constant_property< Key, Value > >
Functions
template<class Y , class R >
TemporaryPtr< Y > const_pointer_cast (const TemporaryPtr< R > &item)
template<class Y , class R >
TemporaryPtr< Y > dynamic_pointer_cast (const TemporaryPtr< R > &item)
template<class Key , class Value >
const Value & get (const constant_property< Key, Value > &pmap, const Key &)
template<class Y , class R >
TemporaryPtr< Y > reinterpret_pointer_cast (const TemporaryPtr< R > &item)
template<class Y , class R >
TemporaryPtr< Y > static_pointer_cast (const TemporaryPtr< R > &item)
Function Documentation
template<class Y , class R > TemporaryPtr<Y> boost::const_pointer_cast (const TemporaryPtr< R > & item)
Referenced by ProductionQueue::ProductionItem::CompletionSpecialConsumption(), Effect::MoveTo::Execute(), and Effect::SetDestination::Execute().
template<class Y , class R > TemporaryPtr<Y> boost::dynamic_pointer_cast (const TemporaryPtr< R > & item)
Referenced by anonymous_namespace{CombatSystem.cpp}::Attack(), ObjectMap::AuditContainment(), Planet::AvailableFoci(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction(), Fighter::Copy(), Field::Copy(), Planet::Copy(), Ship::Copy(), Building::Copy(), System::Copy(), Fleet::Copy(), OptionsWnd::DoubleOption(), MultiIconValueIndicator::EventFilter(), Effect::SetShipPartMeter::Execute(), Effect::SetEmpireCapital::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateField::Execute(), Effect::AddStarlanes::Execute(), Effect::RemoveStarlanes::Execute(), Effect::MoveTo::Execute(), Effect::SetDestination::Execute(), Effect::SetAggression::Execute(), anonymous_namespace{Universe.cpp}::FleetFromObject(), SidePanel::PlanetPanel::FocusDropListSelectionChangedSlot(), anonymous_namespace{Universe.cpp}::GetEmpiresPositionDetectionRanges(), MilitaryPanel::GetPlanet(), PopulationPanel::GetPopCenter(), ResourcePanel::GetResCenter(), anonymous_namespace{CombatSystem.cpp}::GetWeapons(), MapWnd::InitVisibilityRadiiRenderingBuffers(), OptionsWnd::IntOption(), anonymous_namespace{MapWnd.cpp}::IsQualifiedFleet(), anonymous_namespace{CombatSystem.cpp}::LaunchFighters(), Condition::Homeworld::Match(), Condition::Building::Match(), Condition::PlanetType::Match(), Condition::PlanetSize::Match(), Condition::PlanetEnvironment::Match(), Condition::Species::Match(), Condition::FocusType::Match(), Condition::Stationary::Match(), Condition::Aggressive::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), Fleet::MovementPhase(), OptionsWnd::MusicVolumeOption(), ObjectPanel::ObjectPanel(), anonymous_namespace{ObjectListWnd.cpp}::ObjectTextures(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::TypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::BuildingSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetSizeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::DesignHasHullSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::DesignHasPartClassSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::PredefinedShipDesignSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::OrderedBombardedSimpleMatch::operator()(), ShipDesign::ProductionLocation(), anonymous_namespace{CombatSystem.cpp}::RecoverFighters(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipDesignTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), MapWnd::RefreshPopulationIndicator(), OptionsWnd::ResolutionOption(), anonymous_namespace{Universe.cpp}::SetTravelledStarlaneEndpointsVisible(), FleetDetailPanel::ShipRightClicked(), ObjectMap::TryInsertIntoMap(), FleetWnd::UniverseObjectDeleted(), anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo(), Universe::UpdateEmpireStaleObjectKnowledge(), Empire::UpdateOwnedObjectCounters(), SpeciesManager::UpdatePopulationCounter(), SystemResourceSummaryBrowseWnd::UpdateProduction(), and OptionsWnd::VolumeOption().
template<class Key , class Value > const Value& boost::get (const constant_property< Key, Value > & pmap, const Key &)
Referenced by SystemPathing::ImmediateNeighborsImpl(), Universe::InitializeSystemGraph(), InitLogger(), SystemPathing::LeastJumpsPathImpl(), Universe::GraphImpl::EdgeVisibilityFilter::operator()(), SetLoggerPriority(), and SystemPathing::ShortestPathImpl().
template<class Y , class R > TemporaryPtr<Y> boost::reinterpret_pointer_cast (const TemporaryPtr< R > & item)
template<class Y , class R > TemporaryPtr<Y> boost::static_pointer_cast (const TemporaryPtr< R > & item)
Referenced by anonymous_namespace{CombatSystem.cpp}::CombatRound(), anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead(), anonymous_namespace{Universe.cpp}::GetDesignIDFromObject(), and anonymous_namespace{Universe.cpp}::GetSpeciesFromObject().