FreeOrion: anonymous_namespace{SaveFileDialog.cpp} Namespace Reference
anonymous_namespace{SaveFileDialog.cpp} Namespace Reference
Functions
void AddOptions (OptionsDB &db)
GG::Label * CreateResizingText (const std::string &string, GG::X width)
Creates a text control that support resizing and word wrap.
std::string GenericPathString (const fs::path &path)
bool HasRow (const GG::DropDownList *list, const std::string &str)
Returns true if list contains a row with the text str.
bool Prompt (const std::string &question)
const GG::Y PROMPT_HEIGHT (75)
const GG::X PROMT_WIDTH (200)
const GG::X SAVE_FILE_BUTTON_MARGIN (10)
const GG::Y SAVE_FILE_DIALOG_HEIGHT (400)
const GG::Y SAVE_FILE_DIALOG_MIN_HEIGHT (100)
const GG::X SAVE_FILE_DIALOG_MIN_WIDTH (160)
const GG::X SAVE_FILE_DIALOG_WIDTH (600)
Variables
const double DEFAULT_STRETCH = 1.0
const std::string PATH_DELIM_BEGIN = "["
const std::string PATH_DELIM_END = "]"
const unsigned int ROW_MARGIN = 2
const unsigned int SAVE_FILE_CELL_MARGIN = 2
const std::string SAVE_FILE_WND_NAME = "save-load"
const std::string SERVER_LABEL = "SERVER"
const std::string STRETCH = "stretch"
bool temp_bool = RegisterOptions(&AddOptions)
const unsigned int VALID_PREVIEW_COLUMN_COUNT = sizeof(VALID_PREVIEW_COLUMNS) / sizeof(std::string)
const std::string VALID_PREVIEW_COLUMNS []
const int WHEEL_INCREMENT = 80
const std::string WIDE_AS = "wide-as"
Function Documentation
void anonymous_namespace{SaveFileDialog.cpp}::AddOptions (OptionsDB & db)
References OptionsDB::Add(), STRETCH, StringToList(), UserStringNop, and WIDE_AS.
GG::Label* anonymous_namespace{SaveFileDialog.cpp}::CreateResizingText (const std::string & string, GG::X width)
Creates a text control that support resizing and word wrap.
References ClientUI::GetFont().
Referenced by SaveFileColumn::CellForColumn().
std::string anonymous_namespace{SaveFileDialog.cpp}::GenericPathString (const fs::path & path)
References anonymous_namespace{Version.cpp}::retval.
Referenced by SaveFileDialog::SetDirPath().
bool anonymous_namespace{SaveFileDialog.cpp}::HasRow (const GG::DropDownList * list, const std::string & str)
Returns true if list contains a row with the text str.
Referenced by SaveFileDialog::CheckChoiceValidity().
bool anonymous_namespace{SaveFileDialog.cpp}::Prompt (const std::string & question)
References ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), ClientUI::GetFont(), PROMPT_HEIGHT(), PROMT_WIDTH(), ClientUI::TextColor(), and UserString().
Referenced by SaveFileDialog::AskDelete(), and SaveFileDialog::Confirm().
const GG::Y anonymous_namespace{SaveFileDialog.cpp}::PROMPT_HEIGHT (75)
Referenced by Prompt().
const GG::X anonymous_namespace{SaveFileDialog.cpp}::PROMT_WIDTH (200)
Referenced by Prompt().
const GG::X anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_BUTTON_MARGIN (10)
Referenced by SaveFileDialog::Init().
const GG::Y anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_DIALOG_HEIGHT (400)
const GG::Y anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_DIALOG_MIN_HEIGHT (100)
const GG::X anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_DIALOG_MIN_WIDTH (160)
const GG::X anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_DIALOG_WIDTH (600)
Variable Documentation
const double anonymous_namespace{SaveFileDialog.cpp}::DEFAULT_STRETCH = 1.0
Referenced by SaveFileColumn::GetColumn().
const std::string anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_BEGIN = "["
Referenced by SaveFileDirectoryRow::Init().
const std::string anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_END = "]"
Referenced by SaveFileDirectoryRow::Init().
const unsigned int anonymous_namespace{SaveFileDialog.cpp}::ROW_MARGIN = 2
Referenced by SaveFileDirectoryRow::SaveFileDirectoryRow(), SaveFileFileRow::SaveFileFileRow(), and SaveFileHeaderRow::SaveFileHeaderRow().
const unsigned int anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_CELL_MARGIN = 2
Referenced by SaveFileRow::ClientLowerRight(), SaveFileRow::ClientUpperLeft(), SaveFileColumn::ComputeFixedWidth(), SaveFileDialog::Init(), and SaveFileRow::Render().
const std::string anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_WND_NAME = "save-load"
const std::string anonymous_namespace{SaveFileDialog.cpp}::SERVER_LABEL = "SERVER"
Referenced by SaveFileDialog::GetDirPath(), SaveFileDialog::Init(), SaveFileDialog::SetDirPath(), and SaveFileDialog::UpdatePreviewList().
const std::string anonymous_namespace{SaveFileDialog.cpp}::STRETCH = "stretch"
Referenced by AddOptions(), and SaveFileColumn::GetColumn().
bool anonymous_namespace{SaveFileDialog.cpp}::temp_bool = RegisterOptions(&AddOptions)
const unsigned int anonymous_namespace{SaveFileDialog.cpp}::VALID_PREVIEW_COLUMN_COUNT = sizeof(VALID_PREVIEW_COLUMNS) / sizeof(std::string)
Referenced by SaveFileColumn::GetColumns().
const std::string anonymous_namespace{SaveFileDialog.cpp}::VALID_PREVIEW_COLUMNS[]
Initial value:
= {
        "player", "empire", "turn", "time", "file", "seed", "galaxy_age", "galaxy_size", "galaxy_shape",
        "monster_freq", "native_freq", "planet_freq", "specials_freq", "starlane_freq", "ai_aggression",
        "number_of_empires", "number_of_humans"
    }
Referenced by SaveFileColumn::GetColumns().
const int anonymous_namespace{SaveFileDialog.cpp}::WHEEL_INCREMENT = 80
Referenced by SaveFileListBox::Init().
const std::string anonymous_namespace{SaveFileDialog.cpp}::WIDE_AS = "wide-as"
Referenced by AddOptions(), and SaveFileColumn::GetColumn().