FreeOrion: AIInterface Namespace Reference
AIInterface Namespace Reference
List of functions for AIs to query the game state, interact with other players and issue game orders.
Functions
Game state accessors
const std::string & PlayerName ()
Return the player name of this client.
const std::string & PlayerName (int player_id)
Return the player name of the client identified by player_id.
int PlayerID ()
Return the player identifier of this client.
int EmpireID ()
Return the empire identifier of the empire this client controls.
int PlayerEmpireID (int player_id)
Return the empire identifier of the empire player_id controls.
std::vector< int > AllEmpireIDs ()
Return all empire identifiers that are in game.
const Empire * GetEmpire ()
Return the Empire this client controls.
const Empire * GetEmpire (int empire_id)
Return the Empire identified by empire_id.
int EmpirePlayerID (int empire_id)
Return the player identfier of the player controlling the empire empire_id.
std::vector< int > AllPlayerIDs ()
Return all player identifiers that are in game.
bool PlayerIsAI (int player_id)
Return if the player identified by player_id is an AI.
bool PlayerIsHost (int player_id)
Return if the player identified by player_id is the game host.
const Universe & GetUniverse ()
Return the Universe known to this client.
const Tech * GetTech (const std::string &name)
Return the Tech identified by name.
int CurrentTurn ()
Return the current game turn.
object GetOptionsDBOptionStr (std::string const &option)
Return the OptionsDB option option.
object GetOptionsDBOptionInt (std::string const &option)
Return the OptionsDB option option.
object GetOptionsDBOptionBool (std::string const &option)
Return the OptionsDB option option.
object GetOptionsDBOptionDouble (std::string const &option)
Return the OptionsDB option option.
std::string GetAIDir ()
Return the canonical AI directory path.
const GalaxySetupData & GetGalaxySetupData ()
Return the GalaxySetupData of this game.
Game state prediction
void InitTurn ()
Initialize and update game state based last turn update.
void InitMeterEstimatesAndDiscrepancies ()
Initialize and update the Universe Meter s.
void UpdateMeterEstimates (bool pretend_to_own_unowned_planets=false)
Set Universe Meter instances to their estimated values as if the next turn processing phase were done.
void UpdateResourcePools ()
Calculate resource generation, update ResourcePool s and change queue spending.
void UpdateResearchQueue ()
Initialize and update game state based last turn update.
void UpdateProductionQueue ()
Initialize and update game state based last turn update.
Issuing orders
int IssueFleetMoveOrder (int fleet_id, int destination_id)
Notify server that all orders for this client are given.
int IssueRenameOrder (int object_id, const std::string &new_name)
Notify server that all orders for this client are given.
int IssueScrapOrder (const std::vector< int > &object_ids)
Notify server that all orders for this client are given.
int IssueScrapOrder (int object_id)
Notify server that all orders for this client are given.
int IssueNewFleetOrder (const std::string &fleet_name, const std::vector< int > &ship_ids)
Notify server that all orders for this client are given.
int IssueNewFleetOrder (const std::string &fleet_name, int ship_id)
Notify server that all orders for this client are given.
int IssueFleetTransferOrder (int ship_id, int new_fleet_id)
Notify server that all orders for this client are given.
int IssueColonizeOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
int IssueInvadeOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
int IssueBombardOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
int IssueDeleteFleetOrder ()
Notify server that all orders for this client are given.
int IssueAggressionOrder (int object_id, bool aggressive)
Notify server that all orders for this client are given.
int IssueGiveObjectToEmpireOrder (int object_id, int recipient_id)
Notify server that all orders for this client are given.
int IssueChangeFocusOrder (int planet_id, const std::string &focus)
Notify server that all orders for this client are given.
int IssueEnqueueTechOrder (const std::string &tech_name, int position)
Notify server that all orders for this client are given.
int IssueDequeueTechOrder (const std::string &tech_name)
Notify server that all orders for this client are given.
int IssueEnqueueBuildingProductionOrder (const std::string &item_name, int location_id)
Notify server that all orders for this client are given.
int IssueEnqueueShipProductionOrder (int design_id, int location_id)
Notify server that all orders for this client are given.
int IssueChangeProductionQuantityOrder (int queue_index, int new_quantity, int new_blocksize)
Notify server that all orders for this client are given.
int IssueRequeueProductionOrder (int old_queue_index, int new_queue_index)
Notify server that all orders for this client are given.
int IssueDequeueProductionOrder (int queue_index)
Notify server that all orders for this client are given.
int IssueCreateShipDesignOrder (const std::string &name, const std::string &description, const std::string &hull, const std::vector< std::string > parts, const std::string &icon, const std::string &model, bool nameDescInStringTable)
Notify server that all orders for this client are given.
void SendPlayerChatMessage (int recipient_player_id, const std::string &message_text)
Notify server that all orders for this client are given.
void SendDiplomaticMessage (const DiplomaticMessage &diplo_message)
Notify server that all orders for this client are given.
void DoneTurn ()
Notify server that all orders for this client are given.
void LogOutput (const std::string &log_text)
Log log_text with DEBUG level.
void ErrorOutput (const std::string &log_text)
Log log_text with ERROR level.
Detailed Description
List of functions for AIs to query the game state, interact with other players and issue game orders.
Function Documentation
std::vector< int > AIInterface::AllEmpireIDs ()
Return all empire identifiers that are in game.
Returns
A vector containing the identifiers of all empires.
References AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
std::vector< int > AIInterface::AllPlayerIDs ()
Return all player identifiers that are in game.
Returns
A vector containing the identifiers of all players.
References AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::CurrentTurn ()
Return the current game turn.
Returns
The number representing the current game turn.
References ClientApp::CurrentTurn(), and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::DoneTurn ()
Notify server that all orders for this client are given.
References DebugLogger, AIClientApp::GetApp(), and ClientApp::StartTurn().
Referenced by PythonAI::GenerateOrders(), AIBase::GenerateOrders(), and FreeOrionPython::WrapAI().
int AIInterface::EmpireID ()
Return the empire identifier of the empire this client controls.
Returns
An empire identifier.
References ClientApp::EmpireID(), and AIClientApp::GetApp().
Referenced by DesignWnd::AddDesignCore(), BasesListBox::BaseLeftClicked(), BuildDesignatorWnd::BuildItemRequested(), TechTreeWnd::CenterOnTech(), GetEmpire(), anonymous_namespace{ProductionWnd.cpp}::QueueRow::Init(), MapWnd::InitTurn(), IssueCreateShipDesignOrder(), MapWnd::MidTurnUpdate(), SitRepPanel::NextClicked(), SitRepPanel::NumVisibleSitrepsThisTurn(), TechTreeWnd::LayoutPanel::TechPanel::PreRender(), SitRepPanel::PrevClicked(), ProductionQueueWnd::ProductionQueueWnd(), SidePanel::PlanetPanel::RClick(), SidePanel::SystemNameDropDownList::RClick(), PlayingGame::react(), WaitingForTurnData::react(), ResearchWnd::Refresh(), BuildDesignatorWnd::Refresh(), RotatingPlanetControl::Refresh(), MapWnd::RefreshDetectionIndicator(), TechTreeArcsImplementation::RefreshHighlights(), SidePanel::RefreshImpl(), DesignWnd::MainPanel::RefreshIncompleteDesign(), MapWnd::RefreshIndustryResourceIndicator(), MapWnd::RefreshPopulationIndicator(), MapWnd::RefreshResearchResourceIndicator(), MapWnd::RefreshTradeResourceIndicator(), ResearchQueueWnd::ResearchQueueWnd(), MapWnd::ResetEmpireShown(), SidePanel::PlanetPanel::SetFocus(), MapWnd::ShowProduction(), TechTreeWnd::TechDoubleClickedSlot(), TechTreeWnd::TechListBox::TechRightClicked(), TechTreeWnd::TechListBox::TechRow::TechRow(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), SitRepPanel::Update(), anonymous_namespace{PlayerListWnd.cpp}::PlayerDataPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), MapWnd::UpdateEmpireResourcePools(), ResearchWnd::UpdateQueue(), anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips(), ValidSelectedColonyShip(), anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips(), FreeOrionPython::WrapAI(), MapWnd::ZoomToHomeSystem(), MapWnd::ZoomToNextFleet(), MapWnd::ZoomToNextIdleFleet(), MapWnd::ZoomToNextOwnedSystem(), MapWnd::ZoomToPrevFleet(), MapWnd::ZoomToPrevIdleFleet(), and MapWnd::ZoomToPrevOwnedSystem().
int AIInterface::EmpirePlayerID (int empire_id)
Return the player identfier of the player controlling the empire empire_id.
Parameters
empire_id An empire identifier representing an empire.
Returns
The player identifier of the client controlling the empire.
References DebugLogger, ClientApp::EmpirePlayerID(), and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::ErrorOutput (const std::string & log_text)
Log log_text with ERROR level.
Writes the given text and appends a new line
Parameters
log_text The text that should be written to the log system.
References ErrorLogger.
std::string AIInterface::GetAIDir ()
Return the canonical AI directory path.
The value depends on the OptionsDB resource-dir and ai-path keys.
Returns
The canonical path pointing to the directory containing all python AI scripts.
References GetOptionsDB(), and GetResourceDir().
Referenced by FreeOrionPython::WrapAI().
const Empire * AIInterface::GetEmpire ()
Return the Empire this client controls.
Returns
A pointer to the Empire instance this client has the control over.
References EmpireID(), AIClientApp::GetApp(), and ClientApp::GetEmpire().
const Empire * AIInterface::GetEmpire (int empire_id)
Return the Empire identified by empire_id.
Parameters
empire_id An empire identifier.
Returns
A pointer to the Empire instance identified by empire_id.
References AIClientApp::GetApp(), and ClientApp::GetEmpire().
const GalaxySetupData & AIInterface::GetGalaxySetupData ()
Return the GalaxySetupData of this game.
Returns
A reference to the GalaxySetupData used in this game session.
References AIClientApp::GetApp(), and ClientApp::GetGalaxySetupData().
Referenced by FreeOrionPython::WrapAI().
boost::python::object AIInterface::GetOptionsDBOptionBool (std::string const & option)
Return the OptionsDB option option.
Returns
Return the OptionsDB option option or None if not set. @ throw boost::bad_any_cast if option exists but is not bool
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapAI().
boost::python::object AIInterface::GetOptionsDBOptionDouble (std::string const & option)
Return the OptionsDB option option.
Returns
Return the OptionsDB option option or None if not set. @ throw boost::bad_any_cast if option exists but is not a double
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapAI().
boost::python::object AIInterface::GetOptionsDBOptionInt (std::string const & option)
Return the OptionsDB option option.
Returns
Return the OptionsDB option option or None if not set. @ throw boost::bad_any_cast if option exists but is not an int
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapAI().
boost::python::object AIInterface::GetOptionsDBOptionStr (std::string const & option)
Return the OptionsDB option option.
Returns
Return the OptionsDB option option or None if not set. @ throw boost::bad_any_cast if option exists but is not a string
References GetOptionsDB(), and OptionsDB::OptionExists().
Referenced by FreeOrionPython::WrapAI().
const Tech * AIInterface::GetTech (const std::string & name)
Return the Tech identified by name.
Parameters
name The identifying name of the requested Tech.
Returns
A pointer to the Tech matching name or NULL if no Tech with that name was found.
Referenced by TechTreeLayout::Node::AddChild(), TechTreeLayout::AddNode(), Empire::AddTech(), TechTreeWnd::CenterOnTech(), Empire::CheckResearchProgress(), TechTreeLayout::DoLayout(), TechTreeLayout::Edge::Edge(), ValueRef::ComplexVariable< T >::Eval(), Effect::SetEmpireTechProgress::Execute(), Effect::GiveEmpireTech::Execute(), TechTreeArcsImplementation::FillArcBuffer(), Universe::GetEffectsAndTargets(), Empire::HasResearchedPrereqAndUnresearchedPrereq(), anonymous_namespace{ResearchWnd.cpp}::QueueRow::Init(), IssueDequeueTechOrder(), IssueEnqueueTechOrder(), Empire::LeastExpensiveEnqueuedTech(), Empire::MostExpensiveEnqueuedTech(), Empire::MostRPCostLeftEnqueuedTech(), TechTreeLayout::Node::operator<(), Empire::PlaceTechInQueue(), anonymous_namespace{ResearchWnd.cpp}::QueueTechPanel::QueueTechPanel(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), Empire::ResearchableTech(), Empire::ResearchProgress(), anonymous_namespace{Empire.cpp}::SanitizeResearchQueue(), anonymous_namespace{Empire.cpp}::SetTechQueueElementSpending(), Empire::SetTechResearchProgress(), TechTreeWnd::TechDoubleClickedSlot(), TechPanelRowBrowseWnd(), anonymous_namespace{TechTreeWnd.cpp}::TechVisible(), ResearchQueue::UnderfundedProject(), ResearchQueue::Update(), TechTreeWnd::LayoutPanel::TechPanel::Update(), TechTreeWnd::TechListBox::TechRow::Update(), and FreeOrionPython::WrapEmpire().
const Universe & AIInterface::GetUniverse ()
Return the Universe known to this client.
Returns
A constant reference to the single Universe instance representing the known universe of this client.
References AIClientApp::GetApp(), and ClientApp::GetUniverse().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::InitMeterEstimatesAndDiscrepancies ()
Initialize and update the Universe Meter s.
See Also
Universe::InitMeterEstimatesAndDiscrepancies
References AIClientApp::GetApp(), ClientApp::GetUniverse(), and Universe::InitMeterEstimatesAndDiscrepancies().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::InitTurn ()
Initialize and update game state based last turn update.
Initialize and update game state by updating this client
Global Meter
ResourcePool
ProductionQueue
ResearchQueue
instances based on the latest turn update.
int AIInterface::IssueAggressionOrder (int object_id, bool aggressive)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetFleet(), OrderSet::IssueOrder(), ClientApp::Orders(), and UniverseObject::OwnedBy().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueBombardOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), Empires(), ErrorLogger, AIClientApp::GetApp(), EmpireManager::GetDiplomaticStatus(), GetPlanet(), GetShip(), GetUniverse(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), ClientApp::Orders(), UniverseObject::OwnedBy(), UniverseObject::Owner(), UniverseObject::SystemID(), Ship::TotalWeaponsDamage(), and UniverseObject::Unowned().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueChangeFocusOrder (int planet_id, const std::string & focus)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetPlanet(), OrderSet::IssueOrder(), ClientApp::Orders(), and UniverseObject::OwnedBy().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueChangeProductionQuantityOrder (int queue_index, int new_quantity, int new_blocksize)
Notify server that all orders for this client are given.
References BT_SHIP, ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueColonizeOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
References Planet::CurrentMeterValue(), ClientApp::EmpireID(), ErrorLogger, Ship::FleetID(), AIClientApp::GetApp(), GetFleet(), GetPlanet(), GetShip(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), METER_POPULATION, ClientApp::Orders(), UniverseObject::OwnedBy(), UniverseObject::SystemID(), and UniverseObject::Unowned().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueCreateShipDesignOrder (const std::string & name, const std::string & description, const std::string & hull, const std::vector< std::string > parts, const std::string & icon, const std::string & model, bool nameDescInStringTable)
Notify server that all orders for this client are given.
References CurrentTurn(), ClientApp::EmpireID(), EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetApp(), ClientApp::GetNewDesignID(), OrderSet::IssueOrder(), ClientApp::Orders(), and ShipDesign::ValidDesign().
Referenced by anonymous_namespace{AIWrapper.cpp}::IssueCreateShipDesignOrderWrapper().
int AIInterface::IssueDeleteFleetOrder ()
Notify server that all orders for this client are given.
int AIInterface::IssueDequeueProductionOrder (int queue_index)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueDequeueTechOrder (const std::string & tech_name)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetTech(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueEnqueueBuildingProductionOrder (const std::string & item_name, int location_id)
Notify server that all orders for this client are given.
References BT_BUILDING, ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), OrderSet::IssueOrder(), ClientApp::Orders(), and Empire::ProducibleItem().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueEnqueueShipProductionOrder (int design_id, int location_id)
Notify server that all orders for this client are given.
References BT_SHIP, ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), OrderSet::IssueOrder(), ClientApp::Orders(), and Empire::ProducibleItem().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueEnqueueTechOrder (const std::string & tech_name, int position)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetTech(), OrderSet::IssueOrder(), and ClientApp::Orders().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueFleetMoveOrder (int fleet_id, int destination_id)
Notify server that all orders for this client are given.
References DebugLogger, ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetFleet(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), Fleet::NextSystemID(), ClientApp::Orders(), UniverseObject::OwnedBy(), and UniverseObject::SystemID().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueFleetTransferOrder (int ship_id, int new_fleet_id)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetFleet(), GetShip(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), ClientApp::Orders(), UniverseObject::OwnedBy(), and UniverseObject::SystemID().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueGiveObjectToEmpireOrder (int object_id, int recipient_id)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), Empires(), ErrorLogger, ObjectMap::FindObjects(), AIClientApp::GetApp(), GetEmpire(), GetSystem(), GetUniverseObject(), OrderSet::IssueOrder(), System::ObjectIDs(), Objects(), UniverseObject::ObjectType(), ClientApp::Orders(), UniverseObject::OwnedBy(), UniverseObject::Owner(), and UniverseObject::SystemID().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueInvadeOrder (int ship_id, int planet_id)
Notify server that all orders for this client are given.
References Planet::CurrentMeterValue(), ClientApp::EmpireID(), ErrorLogger, Ship::FleetID(), AIClientApp::GetApp(), GetFleet(), Universe::GetObjectVisibilityByEmpire(), GetPlanet(), GetShip(), GetUniverse(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), METER_POPULATION, METER_SHIELD, ClientApp::Orders(), UniverseObject::OwnedBy(), PopCenter::SpeciesName(), UniverseObject::SystemID(), and UniverseObject::Unowned().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueNewFleetOrder (const std::string & fleet_name, const std::vector< int > & ship_ids)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetApp(), ClientApp::GetNewObjectID(), GetShip(), INVALID_OBJECT_ID, OrderSet::IssueOrder(), ClientApp::Orders(), UniverseObject::OwnedBy(), and UniverseObject::SystemID().
int AIInterface::IssueNewFleetOrder (const std::string & fleet_name, int ship_id)
Notify server that all orders for this client are given.
int AIInterface::IssueRenameOrder (int object_id, const std::string & new_name)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetUniverseObject(), OrderSet::IssueOrder(), ClientApp::Orders(), and UniverseObject::OwnedBy().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueRequeueProductionOrder (int old_queue_index, int new_queue_index)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), ClientApp::GetEmpire(), Empire::GetProductionQueue(), OrderSet::IssueOrder(), ClientApp::Orders(), and ProductionQueue::size().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::IssueScrapOrder (const std::vector< int > & object_ids)
Notify server that all orders for this client are given.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetUniverseObject(), OrderSet::IssueOrder(), ClientApp::Orders(), and UniverseObject::OwnedBy().
int AIInterface::IssueScrapOrder (int object_id)
Notify server that all orders for this client are given.
void AIInterface::LogOutput (const std::string & log_text)
Log log_text with DEBUG level.
LoggingWrites the given text and appends a new line
Parameters
log_text The text that should be written to the log system.
References DebugLogger.
int AIInterface::PlayerEmpireID (int player_id)
Return the empire identifier of the empire player_id controls.
Parameters
player_id An client identifier.
Returns
An empire identifier.
References ALL_EMPIRES, and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().
int AIInterface::PlayerID ()
Return the player identifier of this client.
Returns
The player identifier of this client as assigned by the server.
References AIClientApp::GetApp(), and ClientApp::PlayerID().
Referenced by ServerNetworking::GetPlayer(), MultiPlayerLobbyWnd::KeyPress(), PlayingTurn::PlayingTurn(), MapWnd::RClick(), MPLobby::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), SendPlayerChatMessage(), MultiPlayerLobbyWnd::ThisClientIsHost(), UpdateMeterEstimates(), and FreeOrionPython::WrapAI().
bool AIInterface::PlayerIsAI (int player_id)
Return if the player identified by player_id is an AI.
Parameters
player_id An client identifier.
Returns
True if the player is an AI, false if not.
References Networking::CLIENT_TYPE_AI_PLAYER, AIClientApp::GetApp(), and ClientApp::GetPlayerClientType().
Referenced by FreeOrionPython::WrapAI().
bool AIInterface::PlayerIsHost (int player_id)
Return if the player identified by player_id is the game host.
Parameters
player_id An client identifier.
Returns
True if the player is the game host, false if not.
References AIClientApp::GetApp(), and ClientApp::Players().
Referenced by HumanClientApp::CanSaveNow(), MPLobby::react(), WaitingForGameStart::react(), WaitingForTurnData::react(), and FreeOrionPython::WrapAI().
const std::string & AIInterface::PlayerName ()
Return the player name of this client.
Returns
An UTF-8 encoded and NUL terminated string containing the player name of this client.
References AIClientApp::GetApp(), and AIClientApp::PlayerName().
const std::string & AIInterface::PlayerName (int player_id)
Return the player name of the client identified by player_id.
Parameters
player_id An client identifier.
Returns
An UTF-8 encoded and NUL terminated string containing the player name of this client or an empty string the player is not known or does not exist.
References DebugLogger, AIClientApp::GetApp(), and ClientApp::Players().
void AIInterface::SendDiplomaticMessage (const DiplomaticMessage & diplo_message)
Notify server that all orders for this client are given.
References DiplomacyMessage(), ClientApp::EmpirePlayerID(), AIClientApp::GetApp(), Networking::INVALID_PLAYER_ID, ClientApp::Networking(), ClientApp::PlayerID(), DiplomaticMessage::RecipientEmpireID(), and ClientNetworking::SendMessage().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::SendPlayerChatMessage (int recipient_player_id, const std::string & message_text)
Notify server that all orders for this client are given.
References AIClientApp::GetApp(), GlobalChatMessage(), ClientApp::Networking(), PlayerID(), ClientNetworking::SendMessage(), and SingleRecipientChatMessage().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::UpdateMeterEstimates (bool pretend_to_own_unowned_planets = false)
Set Universe Meter instances to their estimated values as if the next turn processing phase were done.
Parameters
pretend_to_own_unowned_planets When set to true pretend during calculation that this clients Empire owns all known uncolonized planets. The unowned planets MAX Meter values will contain the estimated value for those planets.
References ALL_EMPIRES, ObjectMap::FindObjects(), AIClientApp::GetApp(), ClientApp::GetUniverse(), Universe::InhibitUniverseObjectSignals(), Universe::Objects(), PlayerID(), and Universe::UpdateMeterEstimates().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::UpdateProductionQueue ()
Initialize and update game state based last turn update.
Initialize and update game state by updating this client
Global Meter
ResourcePool
ProductionQueue
ResearchQueue
instances based on the latest turn update.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetEmpire(), and Empire::UpdateProductionQueue().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::UpdateResearchQueue ()
Initialize and update game state based last turn update.
Initialize and update game state by updating this client
Global Meter
ResourcePool
ProductionQueue
ResearchQueue
instances based on the latest turn update.
References ClientApp::EmpireID(), ErrorLogger, AIClientApp::GetApp(), GetEmpire(), and Empire::UpdateResearchQueue().
Referenced by FreeOrionPython::WrapAI().
void AIInterface::UpdateResourcePools ()
Calculate resource generation, update ResourcePool s and change queue spending.
References Empires(), and AIClientApp::GetApp().
Referenced by FreeOrionPython::WrapAI().