FreeOrion: anonymous_namespace{ServerApp.cpp} Namespace Reference
anonymous_namespace{ServerApp.cpp} Namespace Reference
Functions
std::string AIClientExe ()
int AIPlayerIDWithName (const ServerNetworking &sn, const std::string &player_name)
void AssembleSystemCombatInfo (std::vector< CombatInfo > &combats)
void BackProjectSystemCombatInfoObjectMeters (std::vector< CombatInfo > &combats)
void CleanEmptyFleets ()
void CleanUpBombardmentStateInfo ()
bool ColonizePlanet (int ship_id, int planet_id)
bool CombatConditionsInSystem (int system_id)
void CreateCombatSitReps (const std::vector< CombatInfo > &combats)
void DisseminateSystemCombatInfo (const std::vector< CombatInfo > &combats)
bool EmpireEliminated (int empire_id)
int EnemyId (int empire_id, const std::set< int > &empire_ids)
void GetEmpireFleetsAtSystem (std::map< int, std::set< int > > &empire_fleets, int system_id)
void GetEmpirePlanetsAtSystem (std::map< int, std::set< int > > &empire_planets, int system_id)
void GetFleetsVisibleToEmpireAtSystem (std::set< int > &visible_fleets, int empire_id, int system_id)
void GetPlanetsVisibleToEmpireAtSystem (std::set< int > &visible_planets, int empire_id, int system_id)
void GetSaveGameDataIndexForAIPlayer (std::vector< std::pair< int, int > > &player_id_to_save_game_data_index, const PlayerSetupData &psd, const std::vector< PlayerSaveGameData > &player_save_game_data, const ServerNetworking &sn)
void GetSaveGameDataIndexForHumanPlayer (std::vector< std::pair< int, int > > &player_id_to_save_game_data_index, const PlayerSetupData &psd, int setup_data_player_id, const std::vector< PlayerSaveGameData > &player_save_game_data, const ServerNetworking &sn)
void HandleColonization ()
void HandleGifting ()
void HandleInvasion ()
void HandleScrapping ()
std::set< int > HumanControlledEmpires (const ServerApp *server_app, const ServerNetworking &server_networking)
bool HumanPlayerWithIdConnected (const ServerNetworking &sn, int id)
void ListSaveSubdirectories (std::vector< std::string > &list)
Generates information on the subdirectories of the save directory.
void ResolveGroundCombat (std::map< int, double > &empires_troops)
void UpdateEmpireCombatDestructionInfo (const std::vector< CombatInfo > &combats)
void UpdateEmpireInvasionInfo (const std::map< int, std::map< int, double > > &planet_empire_invasion_troops)
void UpdateResourceCenterFocusHistoryInfo ()
int VectorIndexForPlayerSaveGameDataForEmpireID (const std::vector< PlayerSaveGameData > &player_save_game_data, int empire_id)
Function Documentation
std::string anonymous_namespace{ServerApp.cpp}::AIClientExe ()
References GetBinDir().
Referenced by ServerApp::CreateAIClients().
int anonymous_namespace{ServerApp.cpp}::AIPlayerIDWithName (const ServerNetworking & sn, const std::string & player_name)
Returns ID of AI player with the indicated player_name.
References Networking::CLIENT_TYPE_AI_PLAYER, ServerNetworking::established_begin(), ServerNetworking::established_end(), and Networking::INVALID_PLAYER_ID.
Referenced by GetSaveGameDataIndexForAIPlayer().
void anonymous_namespace{ServerApp.cpp}::AssembleSystemCombatInfo (std::vector< CombatInfo > & combats)
Clears and refills combats with CombatInfo structs for every system where a combat should occur this turn.
References CombatConditionsInSystem(), CurrentTurn(), ObjectMap::FindObjectIDs(), GetUniverse(), and Universe::Objects().
Referenced by ServerApp::ProcessCombats().
void anonymous_namespace{ServerApp.cpp}::BackProjectSystemCombatInfoObjectMeters (std::vector< CombatInfo > & combats)
Back project meter values of objects in combat info, so that changes to meter values from combat aren't lost when resetting meters during meter updating after combat.
References ObjectMap::begin(), and ObjectMap::end().
Referenced by ServerApp::ProcessCombats().
void anonymous_namespace{ServerApp.cpp}::CleanEmptyFleets ()
Deletes empty fleets.
References Fleet::Empty(), ObjectMap::FindObjects(), GetSystem(), GetUniverse(), UniverseObject::ID(), Objects(), Universe::RecursiveDestroy(), System::Remove(), and UniverseObject::SystemID().
Referenced by ServerApp::PreCombatProcessTurns().
void anonymous_namespace{ServerApp.cpp}::CleanUpBombardmentStateInfo ()
Removes bombardment state info from objects. Actual effects of bombardment are handled during
References ObjectMap::end(), GetUniverse(), Objects(), and Universe::Objects().
Referenced by ServerApp::PreCombatProcessTurns().
bool anonymous_namespace{ServerApp.cpp}::ColonizePlanet (int ship_id, int planet_id)
Does colonization, with safety checks
References Planet::Colonize(), Ship::ColonyCapacity(), Universe::Destroy(), Planet::EnvironmentForSpecies(), ErrorLogger, Ship::FleetID(), GetFleet(), GetPlanet(), GetShip(), GetSystem(), GetUniverse(), UniverseObject::ID(), UniverseObject::Owner(), Universe::RecursiveDestroy(), System::Remove(), Ship::SpeciesName(), UniverseObject::SystemID(), and UniverseObject::Unowned().
Referenced by HandleColonization().
bool anonymous_namespace{ServerApp.cpp}::CombatConditionsInSystem (int system_id)
Returns true iff there is an appropriate combination of objects in the system with id system_id for a combat to occur.
References Fleet::Aggressive(), ALL_EMPIRES, Empires(), EmpireManager::GetDiplomaticStatus(), GetEmpireFleetsAtSystem(), GetEmpirePlanetsAtSystem(), GetFleet(), GetFleetsVisibleToEmpireAtSystem(), GetPlanet(), GetPlanetsVisibleToEmpireAtSystem(), Fleet::HasArmedShips(), Fleet::HasFighterShips(), UniverseObject::Owner(), and UniverseObject::Unowned().
Referenced by AssembleSystemCombatInfo().
void anonymous_namespace{ServerApp.cpp}::CreateCombatSitReps (const std::vector< CombatInfo > & combats)
Creates sitreps for all empires involved in a combat.
References CombatLogManager::AddLog(), Empire::AddSitRepEntry(), CreateCombatDamagedObjectSitRep(), CreateCombatDestroyedObjectSitRep(), CreateCombatSitRep(), CombatInfo::damaged_object_ids, CombatInfo::destroyed_object_ids, CombatInfo::destroyed_object_knowers, CombatInfo::empire_ids, CombatInfo::empire_known_objects, EnemyId(), GetCombatLogManager(), GetEmpire(), ObjectMap::Object(), and CombatInfo::system_id.
Referenced by ServerApp::ProcessCombats().
void anonymous_namespace{ServerApp.cpp}::DisseminateSystemCombatInfo (const std::vector< CombatInfo > & combats)
Takes contents of CombatInfo struct and puts it into the universe. Used to store results of combat in main universe.
References ALL_EMPIRES, ObjectMap::CopyObject(), CombatInfo::destroyed_object_ids, CombatInfo::destroyed_object_knowers, CombatInfo::empire_ids, CombatInfo::empire_object_visibility, Universe::EmpireKnownObjects(), Universe::GetObjectVisibilityByEmpire(), GetShip(), GetSystem(), GetUniverse(), INVALID_OBJECT_ID, Universe::RecursiveDestroy(), Universe::SetEmpireKnowledgeOfDestroyedObject(), Universe::SetEmpireObjectVisibility(), and CombatInfo::system_id.
Referenced by ServerApp::ProcessCombats().
bool anonymous_namespace{ServerApp.cpp}::EmpireEliminated (int empire_id)
Returns true if empire has been eliminated by the applicable definition of elimination. As of this writing, elimination means having no ships and no planets.
References Objects().
Referenced by ServerApp::CheckForEmpireElimination().
int anonymous_namespace{ServerApp.cpp}::EnemyId (int empire_id, const std::set< int > & empire_ids)
References ALL_EMPIRES.
Referenced by CreateCombatSitReps(), and HandleInvasion().
void anonymous_namespace{ServerApp.cpp}::GetEmpireFleetsAtSystem (std::map< int, std::set< int > > & empire_fleets, int system_id)
References ObjectMap::FindObjects(), System::FleetIDs(), GetSystem(), UniverseObject::ID(), Objects(), and UniverseObject::Owner().
Referenced by CombatConditionsInSystem().
void anonymous_namespace{ServerApp.cpp}::GetEmpirePlanetsAtSystem (std::map< int, std::set< int > > & empire_planets, int system_id)
References ALL_EMPIRES, Planet::CurrentMeterValue(), ObjectMap::FindObjects(), GetSystem(), UniverseObject::ID(), METER_POPULATION, Objects(), UniverseObject::Owner(), System::PlanetIDs(), and UniverseObject::Unowned().
Referenced by CombatConditionsInSystem().
void anonymous_namespace{ServerApp.cpp}::GetFleetsVisibleToEmpireAtSystem (std::set< int > & visible_fleets, int empire_id, int system_id)
References ALL_EMPIRES, UniverseObject::CurrentMeterValue(), System::FleetIDs(), GetEmpire(), GetFleet(), Universe::GetObjectVisibilityByEmpire(), GetShip(), GetSystem(), GetUniverse(), UniverseObject::ID(), METER_DETECTION, METER_STEALTH, UniverseObject::OwnedBy(), Fleet::ShipIDs(), System::ShipIDs(), and UniverseObject::Unowned().
Referenced by CombatConditionsInSystem().
void anonymous_namespace{ServerApp.cpp}::GetPlanetsVisibleToEmpireAtSystem (std::set< int > & visible_planets, int empire_id, int system_id)
References ALL_EMPIRES, Planet::CurrentMeterValue(), UniverseObject::CurrentMeterValue(), ObjectMap::FindObjects(), GetEmpire(), Universe::GetObjectVisibilityByEmpire(), GetPlanet(), GetSystem(), GetUniverse(), UniverseObject::ID(), METER_DETECTION, METER_POPULATION, METER_STEALTH, Objects(), System::PlanetIDs(), System::ShipIDs(), and UniverseObject::Unowned().
Referenced by CombatConditionsInSystem().
void anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForAIPlayer (std::vector< std::pair< int, int > > & player_id_to_save_game_data_index, const PlayerSetupData & psd, const std::vector< PlayerSaveGameData > & player_save_game_data, const ServerNetworking & sn)
Adds entry to player_id_to_save_game_data_index after validation.
References AIPlayerIDWithName(), ALL_EMPIRES, DebugLogger, ErrorLogger, Networking::INVALID_PLAYER_ID, PlayerSetupData::m_player_name, PlayerSetupData::m_save_game_empire_id, and VectorIndexForPlayerSaveGameDataForEmpireID().
Referenced by ServerApp::LoadMPGameInit().
void anonymous_namespace{ServerApp.cpp}::GetSaveGameDataIndexForHumanPlayer (std::vector< std::pair< int, int > > & player_id_to_save_game_data_index, const PlayerSetupData & psd, int setup_data_player_id, const std::vector< PlayerSaveGameData > & player_save_game_data, const ServerNetworking & sn)
Adds entry to player_id_to_save_game_data_index after validation.
References ALL_EMPIRES, ErrorLogger, HumanPlayerWithIdConnected(), PlayerSetupData::m_save_game_empire_id, and VectorIndexForPlayerSaveGameDataForEmpireID().
Referenced by ServerApp::LoadMPGameInit().
void anonymous_namespace{ServerApp.cpp}::HandleColonization ()
Determines which ships ordered to colonize planet succeed, does appropriate colonization, and cleans up after colonization orders
References Empire::AddSitRepEntry(), Fleet::Aggressive(), ALL_EMPIRES, ColonizePlanet(), Ship::ColonyCapacity(), CreatePlanetColonizedSitRep(), CreatePlanetOutpostedSitRep(), Empires(), ErrorLogger, ObjectMap::FindObjects(), System::FleetIDs(), EmpireManager::GetDiplomaticStatus(), GetEmpire(), GetPlanet(), GetShip(), GetSystem(), GetUniverse(), Fleet::HasArmedShips(), Fleet::HasFighterShips(), UniverseObject::ID(), INVALID_OBJECT_ID, Objects(), Universe::Objects(), Ship::OrderedColonizePlanet(), UniverseObject::Owner(), Planet::ResetIsAboutToBeColonized(), Ship::SetColonizePlanet(), Ship::SpeciesName(), UniverseObject::SystemID(), and UniverseObject::Unowned().
Referenced by ServerApp::PreCombatProcessTurns().
void anonymous_namespace{ServerApp.cpp}::HandleGifting ()
Determines which fleets or planets ordered given to other empires, and sets their new ownership
References ALL_EMPIRES, Planet::ClearGiveToEmpire(), Fleet::ClearGiveToEmpire(), UniverseObject::ContainedObjectIDs(), ObjectMap::FindObjects(), GetSystem(), GetUniverse(), UniverseObject::ID(), INVALID_OBJECT_ID, System::ObjectIDs(), Objects(), Universe::Objects(), Fleet::OrderedGivenToEmpire(), Planet::OrderedGivenToEmpire(), UniverseObject::OwnedBy(), UniverseObject::Owner(), UniverseObject::SetOwner(), UniverseObject::SystemID(), and UniverseObject::Unowned().
Referenced by ServerApp::PreCombatProcessTurns().
void anonymous_namespace{ServerApp.cpp}::HandleInvasion ()
Determines which ships ordered to invade planets, does invasion and ground combat resolution
References ALL_EMPIRES, UniverseObject::BackPropagateMeters(), Planet::Conquer(), ObjectMap::CopyObject(), CreateGroundCombatSitRep(), CreatePlanetCapturedSitRep(), Planet::CurrentMeterValue(), DebugLogger, Universe::Destroy(), EmpireKnownObjects(), EnemyId(), ErrorLogger, ObjectMap::FindObjects(), Ship::FleetID(), GetEmpire(), GetFleet(), Planet::GetMeter(), GetPlanet(), GetSystem(), GetUniverse(), Ship::HasTroops(), UniverseObject::ID(), INVALID_OBJECT_ID, METER_REBEL_TROOPS, METER_TROOPS, UniverseObject::Name(), Objects(), Ship::OrderedInvadePlanet(), UniverseObject::OwnedBy(), UniverseObject::Owner(), Universe::RecursiveDestroy(), System::Remove(), Planet::ResetIsAboutToBeInvaded(), ResolveGroundCombat(), UniverseObject::SystemID(), Ship::TroopCapacity(), UniverseObject::Unowned(), and UpdateEmpireInvasionInfo().
Referenced by ServerApp::PreCombatProcessTurns().
void anonymous_namespace{ServerApp.cpp}::HandleScrapping ()
Destroys suitable objects that have been ordered scrapped.
References parse::buildings(), Building::BuildingTypeName(), Empire::BuildingTypesScrapped(), DebugLogger, Ship::DesignID(), Universe::Destroy(), Fleet::Empty(), ObjectMap::FindObjects(), Ship::FleetID(), GetEmpire(), GetFleet(), GetPlanet(), GetSystem(), GetUniverse(), UniverseObject::ID(), Objects(), Building::OrderedScrapped(), Ship::OrderedScrapped(), UniverseObject::Owner(), Building::PlanetID(), System::Remove(), Fleet::RemoveShip(), Empire::ShipDesignsScrapped(), Ship::SpeciesName(), Empire::SpeciesShipsScrapped(), and UniverseObject::SystemID().
Referenced by ServerApp::PreCombatProcessTurns().
std::set<int> anonymous_namespace{ServerApp.cpp}::HumanControlledEmpires (const ServerApp * server_app, const ServerNetworking & server_networking)
Compiles and return set of ids of empires that are controlled by a human player.
References ALL_EMPIRES, Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, ServerNetworking::established_begin(), ServerNetworking::established_end(), Networking::INVALID_PLAYER_ID, ServerApp::PlayerEmpireID(), and anonymous_namespace{Version.cpp}::retval.
Referenced by ServerApp::ProcessCombats().
bool anonymous_namespace{ServerApp.cpp}::HumanPlayerWithIdConnected (const ServerNetworking & sn, int id)
Verifies that a human player is connected with the indicated id.
References Networking::CLIENT_TYPE_HUMAN_PLAYER, ErrorLogger, ServerNetworking::established_end(), and ServerNetworking::GetPlayer().
Referenced by GetSaveGameDataIndexForHumanPlayer().
void anonymous_namespace{ServerApp.cpp}::ListSaveSubdirectories (std::vector< std::string > & list)
Generates information on the subdirectories of the save directory.
References ErrorLogger, and GetSaveDir().
Referenced by ServerApp::UpdateSavePreviews().
void anonymous_namespace{ServerApp.cpp}::ResolveGroundCombat (std::map< int, double > & empires_troops)
Given initial set of ground forces on planet, determine ground forces on planet after a turn of ground combat.
Referenced by HandleInvasion().
void anonymous_namespace{ServerApp.cpp}::UpdateEmpireCombatDestructionInfo (const std::vector< CombatInfo > & combats)
Records info in Empires about what they destroyed or had destroyed during combat.
References WeaponFireEvent::attacker_id, CombatInfo::combat_events, Ship::DesignID(), CombatInfo::destroyed_object_ids, boost::dynamic_pointer_cast(), Empire::EmpireShipsDestroyed(), GetEmpire(), GetShip(), GetUniverseObject(), UniverseObject::Owner(), Empire::ShipDesignsDestroyed(), Empire::ShipDesignsLost(), Ship::SpeciesName(), Empire::SpeciesShipsDestroyed(), Empire::SpeciesShipsLost(), WeaponsPlatformEvent::SubEvents(), and WeaponFireEvent::target_id.
Referenced by ServerApp::ProcessCombats().
void anonymous_namespace{ServerApp.cpp}::UpdateEmpireInvasionInfo (const std::map< int, std::map< int, double > > & planet_empire_invasion_troops)
Records info in Empires about where they invaded.
References GetEmpire(), GetPlanet(), PopCenter::SpeciesName(), and Empire::SpeciesPlanetsInvaded().
Referenced by HandleInvasion().
void anonymous_namespace{ServerApp.cpp}::UpdateResourceCenterFocusHistoryInfo ()
Causes ResourceCenters (Planets) to update their focus records
References ObjectMap::end(), GetUniverse(), Objects(), and Universe::Objects().
Referenced by ServerApp::PreCombatProcessTurns().
int anonymous_namespace{ServerApp.cpp}::VectorIndexForPlayerSaveGameDataForEmpireID (const std::vector< PlayerSaveGameData > & player_save_game_data, int empire_id)
Returns index into vector parameter that matches parameter empire id.
References ALL_EMPIRES, and PlayerSaveHeaderData::m_empire_id.
Referenced by GetSaveGameDataIndexForAIPlayer(), and GetSaveGameDataIndexForHumanPlayer().