FreeOrion: anonymous_namespace{Tech.cpp} Namespace Reference
anonymous_namespace{Tech.cpp} Namespace Reference
Functions
const Tech * Cheapest (const std::vector< const Tech * > &next_techs, int empire_id)
void NextTechs (std::vector< const Tech * > &retval, const std::set< std::string > &known_techs, std::set< const Tech * > &checked_techs, TechManager::iterator it, TechManager::iterator end_it)
TemporaryPtr< const
UniverseObject > SourceForEmpire (int empire_id)
Variables
const bool CHEAP_AND_FAST_TECH_RESEARCH = false
Function Documentation
const Tech* anonymous_namespace{Tech.cpp}::Cheapest (const std::vector< const Tech * > & next_techs, int empire_id)
References Tech::ResearchCost().
Referenced by TechManager::CheapestNextTech(), and TechManager::CheapestNextTechTowards().
void anonymous_namespace{Tech.cpp}::NextTechs (std::vector< const Tech * > & retval, const std::set< std::string > & known_techs, std::set< const Tech * > & checked_techs, TechManager::iterator it, TechManager::iterator end_it)
References GetTech(), Tech::Name(), and Tech::Prerequisites().
Referenced by TechManager::AllNextTechs(), and TechManager::NextTechsTowards().
TemporaryPtr<const UniverseObject> anonymous_namespace{Tech.cpp}::SourceForEmpire (int empire_id)
References Empire::CapitalID(), DebugLogger, GetEmpire(), GetUniverseObject(), and Objects().
Referenced by Tech::ResearchCost(), and Tech::ResearchTime().
Variable Documentation
const bool anonymous_namespace{Tech.cpp}::CHEAP_AND_FAST_TECH_RESEARCH = false
Referenced by Tech::ResearchCost(), and Tech::ResearchTime().