FreeOrion: parse Namespace Reference
parse Namespace Reference
The namespace that encloses the script file lexer and parser.
Namespaces
detail
Classes
struct double_complex_parser_rules
struct int_complex_parser_rules
struct lexer
struct report_error_
struct string_complex_parser_rules
Typedefs
typedef detail::rule< Condition::ConditionBase *() > condition_parser_rule
typedef detail::rule< Effect::EffectBase *() > effect_parser_rule
template<typename E >
using enum_rule = detail::rule< E() >
typedef lexer::lexer_def lexer_def
typedef boost::spirit::qi::in_state_skipper< lexer_def > skipper_type
typedef boost::spirit::lex::lexertl::actor_lexer< token_type > spirit_lexer_base_type
typedef std::string::const_iterator text_iterator
typedef lexer::iterator_type token_iterator
typedef boost::spirit::lex::lexertl::position_token< text_iterator, boost::mpl::vector< bool, int, double, const char *, std::string >> token_type
template<typename T >
using value_ref_rule = detail::rule< ValueRef::ValueRefBase< T > *() >
Functions
bool alignments (std::vector< Alignment > &alignments_, std::vector< std::shared_ptr< Effect::EffectsGroup >> &effects_groups)
bool buildings (std::map< std::string, BuildingType * > &building_types)
enum_rule< CaptureResult > & capture_result_enum ()
void check_for_cyclic_macro_references (const std::map< std::string, std::string > &macros)
condition_parser_rule & condition_parser ()
value_ref_rule< double > & double_value_ref ()
effect_parser_rule & effect_parser ()
enum_rule< EmpireAffiliationType > & empire_affiliation_type_enum ()
bool encyclopedia_articles (Encyclopedia &enc)
bool fields (std::map< std::string, FieldType * > &field_types)
void file_substitution (std::string &text, const boost::filesystem::path &file_search_path)
Resolve script directives.
bool fleet_plans (std::vector< FleetPlan * > &fleet_plans_)
value_ref_rule< int > & flexible_int_value_ref ()
void init ()
value_ref_rule< int > & int_value_ref ()
bool items (std::vector< ItemSpec > &items_)
FO_PARSE_API bool keymaps (std::map< std::string, std::map< int, int >> &nkm)
bool keymaps (NamedKeymaps &nkm)
std::vector< boost::filesystem::path > ListScripts (const boost::filesystem::path &path)
Return a vector of absolute paths to script files in the given path.
bool macro_deep_referenced_in_text (const std::string &macro_to_find, const std::string &text, const std::map< std::string, std::string > &macros)
void macro_substitution (std::string &text)
std::set< std::string > macros_directly_referenced_in_text (const std::string &text)
FO_PARSE_API bool monster_designs (std::map< std::string, ShipDesign * > &designs)
bool monster_fleet_plans (std::vector< MonsterFleetPlan * > &monster_fleet_plans_)
enum_rule< MeterType > & non_ship_part_meter_type_enum ()
void parse_and_erase_macro_definitions (std::string &text, std::map< std::string, std::string > &macros)
void process_include_substitutions (std::string &text, const boost::filesystem::path &file_search_path, std::set< boost::filesystem::path > &files_included)
Replace all include statements with contents of file.
bool read_file (const boost::filesystem::path &path, std::string &file_contents)
void replace_macro_references (std::string &text, const std::map< std::string, std::string > &macros)
enum_rule< MeterType > & set_non_ship_part_meter_type_enum ()
enum_rule< MeterType > & set_ship_part_meter_type_enum ()
FO_PARSE_API bool ship_designs (const boost::filesystem::path &path, std::map< std::string, ShipDesign * > &designs)
FO_PARSE_API bool ship_designs (std::map< std::string, ShipDesign * > &designs)
FO_PARSE_API bool ship_hulls (std::map< std::string, HullType * > &hulls)
enum_rule< ShipPartClass > & ship_part_class_enum ()
enum_rule< MeterType > & ship_part_meter_type_enum ()
FO_PARSE_API bool ship_parts (std::map< std::string, PartType * > &parts)
enum_rule< ShipSlotType > & ship_slot_type_enum ()
FO_PARSE_API bool specials (std::map< std::string, Special * > &specials_)
FO_PARSE_API bool species (std::map< std::string, Species * > &species_)
bool starting_buildings (std::vector< ItemSpec > &starting_buildings_)
enum_rule< ValueRef::StatisticType > & statistic_type_enum ()
bool statistics (std::map< std::string, ValueRef::ValueRefBase< double > * > &stats_)
value_ref_rule< std::string > & string_value_ref ()
FO_PARSE_API bool techs (TechManager::TechContainer &techs_, std::map< std::string, TechCategory * > &tech_categories, std::set< std::string > &categories_seen)
enum_rule< UnlockableItemType > & unlockable_item_type_enum ()
Variables
const sregex FILENAME_INSERTION = bol >> "#include" >> *space >> "\"" >> (s1 = FILENAME_TEXT) >> "\"" >> *space >> _n
const sregex FILENAME_TEXT = -+_
const sregex MACRO_DEFINITION = (s1 = MACRO_KEY) >> _n >> "'''" >> (s2 = MACRO_TEXT) >> "'''" >> _n
const sregex MACRO_INSERTION = "[[" >> *space >> (s1 = MACRO_KEY) >> *space >> !("(" >> (s2 = +~(set = ')', '\n')) >> ")") >> "]]"
const sregex MACRO_KEY = +_w
const sregex MACRO_TEXT = -*_
std::set< std::string > missing_include_files
const boost::phoenix::function< report_error_ > report_error
Detailed Description
The namespace that encloses the script file lexer and parser.
Typedef Documentation
typedef detail::rule< Condition::ConditionBase* () > parse::condition_parser_rule
typedef detail::rule< Effect::EffectBase* () > parse::effect_parser_rule
template<typename E > using parse::enum_rule = typedef detail::rule< E () >
typedef lexer::lexer_def parse::lexer_def
typedef boost::spirit::qi::in_state_skipper<lexer_def> parse::skipper_type
The type of the skip-parser, defined in the script file lexer, used by the script file parser iterator.
typedef boost::spirit::lex::lexertl::actor_lexer<token_type> parse::spirit_lexer_base_type
typedef std::string::const_iterator parse::text_iterator
The type of iterator used by the script file lexer.
typedef lexer::iterator_type parse::token_iterator
The type of iterator passed to the script file parser by the script file lexer.
typedef boost::spirit::lex::lexertl::position_token< text_iterator, boost::mpl::vector< bool, int, double, const char*, std::string >> parse::token_type
The type of token used by the script file lexer.
template<typename T > using parse::value_ref_rule = typedef detail::rule< ValueRef::ValueRefBase<T>* () >
Function Documentation
FO_PARSE_API bool parse::alignments (std::vector< Alignment > & alignments_, std::vector< std::shared_ptr< Effect::EffectsGroup >> & effects_groups)
References anonymous_namespace{AlignmentsParser.cpp}::g_effects_groups, and ListScripts().
Referenced by anonymous_namespace{Empire.cpp}::AlignmentManager::AlignmentManager().
FO_PARSE_API bool parse::buildings (std::map< std::string, BuildingType * > & building_types)
References ListScripts().
Referenced by BuildingTypeManager::BuildingTypeManager(), and anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings().
enum_rule< CaptureResult > & parse::capture_result_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, CR_CAPTURE, CR_DESTROY, and parse::lexer::instance().
Referenced by anonymous_namespace{BuildingsParser.cpp}::rules::rules().
void parse::check_for_cyclic_macro_references (const std::map< std::string, std::string > & macros)
References ErrorLogger, and macro_deep_referenced_in_text().
Referenced by macro_substitution().
condition_parser_rule & parse::condition_parser ()
Returns a const reference to the Condition parser.
References parse::detail::condition_parser, parse::detail::condition_parser_1(), parse::detail::condition_parser_2(), parse::detail::condition_parser_3(), parse::detail::condition_parser_4(), parse::detail::condition_parser_5(), parse::detail::condition_parser_6(), and parse::detail::condition_parser_7().
value_ref_rule< double > & parse::double_value_ref ()
References arithmetic_rules< T >::expr, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
Referenced by anonymous_namespace{IntValueRefParser.cpp}::castable_as_int_parser_rules::castable_as_int_parser_rules(), anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3(), anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2(), anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::effect_parser_rules_3(), anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4(), anonymous_namespace{EmpireStatsParser.cpp}::rules::rules(), parse::detail::rules::rules(), anonymous_namespace{SpecialsParser.cpp}::rules::rules(), and anonymous_namespace{TechsParser.cpp}::rules::rules().
effect_parser_rule & parse::effect_parser ()
Returns a const reference to the Effect parser.
References parse::detail::effect_parser, parse::detail::effect_parser_1(), parse::detail::effect_parser_2(), parse::detail::effect_parser_3(), parse::detail::effect_parser_4(), and parse::detail::effect_parser_5().
Referenced by anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4(), anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::effect_parser_rules_5(), and anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rules().
enum_rule< EmpireAffiliationType > & parse::empire_affiliation_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, AFFIL_ALLY, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_ENEMY, AFFIL_HUMAN, AFFIL_NONE, AFFIL_SELF, and parse::lexer::instance().
Referenced by anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::condition_parser_rules_1(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), and anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2().
FO_PARSE_API bool parse::encyclopedia_articles (Encyclopedia & enc)
References ListScripts().
Referenced by Encyclopedia::Encyclopedia().
FO_PARSE_API bool parse::fields (std::map< std::string, FieldType * > & field_types)
References ListScripts().
Referenced by FieldTypeManager::FieldTypeManager(), and ObjectListBox::Refresh().
FO_PARSE_API void parse::file_substitution (std::string & text, const boost::filesystem::path & file_search_path)
Resolve script directives.
Parameters
[in,out] text contents to search through
[in] file_search_path base path of content
References ErrorLogger, and process_include_substitutions().
Referenced by StringTable_::Load(), and parse::detail::parse_file_common().
FO_PARSE_API bool parse::fleet_plans (std::vector< FleetPlan * > & fleet_plans_)
References GetResourceDir().
Referenced by anonymous_namespace{UniverseGenerator.cpp}::FleetPlanManager::FleetPlanManager(), and anonymous_namespace{ServerWrapper.cpp}::LoadFleetPlanList().
value_ref_rule< int > & parse::flexible_int_value_ref ()
References anonymous_namespace{IntValueRefParser.cpp}::castable_as_int_parser_rules::flexible_int, and anonymous_namespace{IntValueRefParser.cpp}::get_castable_as_int_parser_rules().
Referenced by anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2(), anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3(), parse::detail::rules::rules(), and anonymous_namespace{TechsParser.cpp}::rules::rules().
FO_PARSE_API void parse::init ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::lexer::double_, parse::detail::double_, parse::lexer::int_, parse::detail::int_, and int_value_ref().
Referenced by main(), and mainSetupAndRun().
value_ref_rule< int > & parse::int_value_ref ()
References arithmetic_rules< T >::expr, and anonymous_namespace{IntValueRefParser.cpp}::get_int_arithmetic_rules().
Referenced by anonymous_namespace{IntValueRefParser.cpp}::castable_as_int_parser_rules::castable_as_int_parser_rules(), anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::condition_parser_rules_1(), anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2(), anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3(), anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), anonymous_namespace{ConditionParser5.cpp}::condition_parser_rules_5::condition_parser_rules_5(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2(), anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4(), init(), and parse::int_complex_parser_rules::int_complex_parser_rules().
FO_PARSE_API bool parse::items (std::vector< ItemSpec > & items_)
References GetResourceDir().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadItemSpecList().
FO_PARSE_API bool parse::keymaps (std::map< std::string, std::map< int, int >> & nkm)
bool parse::keymaps (NamedKeymaps & nkm)
References GetResourceDir().
Referenced by HumanClientApp::HumanClientApp().
FO_PARSE_API std::vector< boost::filesystem::path > parse::ListScripts (const boost::filesystem::path & path)
Return a vector of absolute paths to script files in the given path.
Parameters
[in] path relative or absolute directory (searched recursively)
Returns
Any *.focs.txt files in path or 'GetResourceDir() / path'.
References ErrorLogger, ListDir(), and TraceLogger.
Referenced by alignments(), buildings(), encyclopedia_articles(), fields(), monster_designs(), ship_designs(), ship_hulls(), ship_parts(), specials(), species(), statistics(), and techs().
bool parse::macro_deep_referenced_in_text (const std::string & macro_to_find, const std::string & text, const std::map< std::string, std::string > & macros)
References ErrorLogger, and macros_directly_referenced_in_text().
Referenced by check_for_cyclic_macro_references(), and replace_macro_references().
void parse::macro_substitution (std::string & text)
References check_for_cyclic_macro_references(), parse_and_erase_macro_definitions(), and replace_macro_references().
Referenced by parse::detail::parse_file_common().
std::set<std::string> parse::macros_directly_referenced_in_text (const std::string & text)
References ErrorLogger, and MACRO_INSERTION.
Referenced by macro_deep_referenced_in_text().
bool parse::monster_designs (std::map< std::string, ShipDesign * > & designs)
References ListScripts().
Referenced by PredefinedShipDesignManager::PredefinedShipDesignManager().
FO_PARSE_API bool parse::monster_fleet_plans (std::vector< MonsterFleetPlan * > & monster_fleet_plans_)
References GetResourceDir().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadMonsterFleetPlanList(), and anonymous_namespace{UniverseGenerator.cpp}::MonsterFleetPlanManager::MonsterFleetPlanManager().
enum_rule< MeterType > & parse::non_ship_part_meter_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STEALTH, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), and parse::detail::rules::rules().
void parse::parse_and_erase_macro_definitions (std::string & text, std::map< std::string, std::string > & macros)
References ErrorLogger, and MACRO_DEFINITION.
Referenced by macro_substitution().
FO_PARSE_API void parse::process_include_substitutions (std::string & text, const boost::filesystem::path & file_search_path, std::set< boost::filesystem::path > & files_included)
Replace all include statements with contents of file.
Search for any include statements in text and replace them with the contents of the file given. File lookup is relative to file_search_path and will not be included if found in files_included. Each included file is added to files_included. This is a recursive function, processing the contents of any included files.
Parameters
[in,out] text content to search through
[in] file_search_path base path of content
[in,out] files_included canonical path of any files previously included
References DebugLogger, ErrorLogger, FILENAME_INSERTION, GetResourceDir(), ListDir(), PathString(), and read_file().
Referenced by file_substitution().
FO_PARSE_API bool parse::read_file (const boost::filesystem::path & path, std::string & file_contents)
Referenced by StringTable_::Load(), parse::detail::parse_file_common(), and process_include_substitutions().
void parse::replace_macro_references (std::string & text, const std::map< std::string, std::string > & macros)
References ErrorLogger, macro_deep_referenced_in_text(), and MACRO_INSERTION.
Referenced by macro_substitution().
enum_rule< MeterType > & parse::set_non_ship_part_meter_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_HAPPINESS, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_MAX_SUPPLY, METER_MAX_TROOPS, METER_POPULATION, METER_REBEL_TROOPS, METER_RESEARCH, METER_SHIELD, METER_SIZE, METER_SPEED, METER_STEALTH, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_HAPPINESS, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, METER_TRADE, and METER_TROOPS.
Referenced by anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2().
enum_rule< MeterType > & parse::set_ship_part_meter_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), METER_CAPACITY, METER_MAX_CAPACITY, METER_MAX_SECONDARY_STAT, and METER_SECONDARY_STAT.
Referenced by anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2().
bool parse::ship_designs (const boost::filesystem::path & path, std::map< std::string, ShipDesign * > & designs)
Referenced by PredefinedShipDesignManager::PredefinedShipDesignManager(), anonymous_namespace{DesignWnd.cpp}::SavedDesignsManager::RefreshDesigns(), and Universe::serialize().
bool parse::ship_designs (std::map< std::string, ShipDesign * > & designs)
References ListScripts().
bool parse::ship_hulls (std::map< std::string, HullType * > & hulls)
References ListScripts().
Referenced by HullTypeManager::HullTypeManager().
enum_rule< ShipPartClass > & parse::ship_part_class_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), PC_ARMOUR, PC_BOMBARD, PC_COLONY, PC_DETECTION, PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, PC_FUEL, PC_GENERAL, PC_INDUSTRY, PC_PRODUCTION_LOCATION, PC_RESEARCH, PC_SHIELD, PC_SPEED, PC_STEALTH, PC_TRADE, and PC_TROOPS.
Referenced by anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2(), parse::int_complex_parser_rules::int_complex_parser_rules(), and anonymous_namespace{ShipPartsParser.cpp}::rules::rules().
enum_rule< MeterType > & parse::ship_part_meter_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), METER_CAPACITY, and METER_MAX_CAPACITY.
Referenced by anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4().
bool parse::ship_parts (std::map< std::string, PartType * > & parts)
References ListScripts().
Referenced by PartTypeManager::PartTypeManager().
enum_rule< ShipSlotType > & parse::ship_slot_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, and parse::lexer::instance().
Referenced by anonymous_namespace{ShipPartsParser.cpp}::rules::rules(), and anonymous_namespace{ShipHullsParser.cpp}::rules::rules().
bool parse::specials (std::map< std::string, Special * > & specials_)
References ListScripts().
Referenced by anonymous_namespace{Special.cpp}::SpecialManager::SpecialManager().
bool parse::species (std::map< std::string, Species * > & species_)
References ListScripts().
Referenced by AutomaticallyChosenColonyShip(), Planet::AvailableFoci(), Ship::CanColonize(), Planet::Colonize(), anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::condition_parser_rules_6(), anonymous_namespace{ServerWrapper.cpp}::CreateShip(), Planet::EnvironmentForSpecies(), ValueRef::Variable< T >::Eval(), Effect::SetSpecies::Execute(), Planet::FocusIcon(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetDetailedDescriptionStats(), Universe::GetEffectsAndTargets(), EncyclopediaDetailPanel::GetItemsSize(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::GetSortedPediaDirEntires(), SpeciesManager::GetSpeciesHomeworldsMap(), Ship::HasTag(), Planet::HasTag(), Condition::Homeworld::Match(), Condition::CanColonize::Match(), Condition::CanProduceShips::Match(), Planet::NextBetterPlanetTypeForSpecies(), Condition::anonymous_namespace{Condition.cpp}::HomeworldSimpleMatch::operator()(), OwnerColoredSystemName::OwnerColoredSystemName(), anonymous_namespace{ServerWrapper.cpp}::PlanetMakeColony(), ShipDesign::ProductionLocation(), SidePanel::PlanetPanel::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSuitabilityTag(), MapWnd::RefreshPopulationIndicator(), anonymous_namespace{SpeciesParser.cpp}::rules::rules(), SetEmpireHomeworld(), PopCenter::SetSpecies(), SpeciesManager::SetSpeciesHomeworlds(), anonymous_namespace{ServerWrapper.cpp}::SpeciesAddHomeworld(), anonymous_namespace{ServerWrapper.cpp}::SpeciesCanColonize(), anonymous_namespace{ServerWrapper.cpp}::SpeciesGetPlanetEnvironment(), ClientUI::SpeciesIcon(), SpeciesManager::SpeciesManager(), anonymous_namespace{ServerWrapper.cpp}::SpeciesPreferredFocus(), anonymous_namespace{ServerWrapper.cpp}::SpeciesRemoveHomeworld(), Planet::Tags(), and SpeciesManager::UpdatePopulationCounter().
FO_PARSE_API bool parse::starting_buildings (std::vector< ItemSpec > & starting_buildings_)
References GetResourceDir().
Referenced by anonymous_namespace{ServerWrapper.cpp}::LoadStartingBuildings().
enum_rule< ValueRef::StatisticType > & parse::statistic_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, ValueRef::COUNT, ValueRef::IF, parse::lexer::instance(), ValueRef::MAX, ValueRef::MEAN, ValueRef::MIN, ValueRef::MODE, ValueRef::PRODUCT, ValueRef::RMS, ValueRef::SPREAD, ValueRef::STDEV, ValueRef::SUM, and ValueRef::UNIQUE_COUNT.
Referenced by arithmetic_rules< int >::arithmetic_rules().
FO_PARSE_API bool parse::statistics (std::map< std::string, ValueRef::ValueRefBase< double > * > & stats_)
References ListScripts().
Referenced by EmpireStatistics::GetEmpireStats().
value_ref_rule< std::string > & parse::string_value_ref ()
Referenced by anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2(), anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3(), anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), anonymous_namespace{ConditionParser5.cpp}::condition_parser_rules_5::condition_parser_rules_5(), anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::condition_parser_rules_6(), anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::condition_parser_rules_7(), parse::double_complex_parser_rules::double_complex_parser_rules(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2(), anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::effect_parser_rules_3(), anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4(), and parse::int_complex_parser_rules::int_complex_parser_rules().
bool parse::techs (TechManager::TechContainer & techs_, std::map< std::string, TechCategory * > & tech_categories, std::set< std::string > & categories_seen)
References anonymous_namespace{TechsParser.cpp}::g_categories, anonymous_namespace{TechsParser.cpp}::g_categories_seen, GetResourceDir(), and ListScripts().
Referenced by TechTreeWnd::TechDoubleClickedSlot(), and TechManager::TechManager().
enum_rule< UnlockableItemType > & parse::unlockable_item_type_enum ()
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), UIT_BUILDING, UIT_SHIP_DESIGN, UIT_SHIP_HULL, UIT_SHIP_PART, and UIT_TECH.
Referenced by anonymous_namespace{Parse.cpp}::item_spec_parser_rules::item_spec_parser_rules().
Variable Documentation
const sregex parse::FILENAME_INSERTION = bol >> "#include" >> *space >> "\"" >> (s1 = FILENAME_TEXT) >> "\"" >> *space >> _n
Referenced by process_include_substitutions().
const sregex parse::FILENAME_TEXT = -+_
const sregex parse::MACRO_DEFINITION = (s1 = MACRO_KEY) >> _n >> "'''" >> (s2 = MACRO_TEXT) >> "'''" >> _n
Referenced by parse_and_erase_macro_definitions().
const sregex parse::MACRO_INSERTION = "[[" >> *space >> (s1 = MACRO_KEY) >> *space >> !("(" >> (s2 = +~(set = ')', '\n')) >> ")") >> "]]"
Referenced by macros_directly_referenced_in_text(), and replace_macro_references().
const sregex parse::MACRO_KEY = +_w
const sregex parse::MACRO_TEXT = -*_
std::set<std::string> parse::missing_include_files
const boost::phoenix::function< parse::report_error_ > parse::report_error
Referenced by anonymous_namespace{EmpireStatsParser.cpp}::rules::rules(), anonymous_namespace{ItemsParser.cpp}::rules::rules(), anonymous_namespace{FleetPlansParser.cpp}::rules::rules(), anonymous_namespace{AlignmentsParser.cpp}::rules::rules(), anonymous_namespace{EncyclopediaParser.cpp}::rules::rules(), anonymous_namespace{MonsterFleetPlansParser.cpp}::rules::rules(), anonymous_namespace{FieldsParser.cpp}::rules::rules(), anonymous_namespace{ShipDesignsParser.cpp}::rules::rules(), anonymous_namespace{SpecialsParser.cpp}::rules::rules(), anonymous_namespace{BuildingsParser.cpp}::rules::rules(), anonymous_namespace{SpeciesParser.cpp}::rules::rules(), anonymous_namespace{KeymapParser.cpp}::rules::rules(), anonymous_namespace{ShipPartsParser.cpp}::rules::rules(), anonymous_namespace{ShipHullsParser.cpp}::rules::rules(), and anonymous_namespace{TechsParser.cpp}::rules::rules().