FreeOrion: anonymous_namespace{IntValueRefParser.cpp} Namespace Reference
anonymous_namespace{IntValueRefParser.cpp} Namespace Reference
Classes
struct castable_as_int_parser_rules
struct int_parser_rules
struct simple_int_parser_rules
Functions
castable_as_int_parser_rules & get_castable_as_int_parser_rules ()
int_parser_rules & get_int_parser_rules ()
simple_int_parser_rules & get_simple_int_parser_rules ()
Function Documentation
castable_as_int_parser_rules& anonymous_namespace{IntValueRefParser.cpp}::get_castable_as_int_parser_rules ()
References anonymous_namespace{Version.cpp}::retval.
Referenced by parse::value_ref_parser_flexible_int().
int_parser_rules& anonymous_namespace{IntValueRefParser.cpp}::get_int_parser_rules ()
References anonymous_namespace{Version.cpp}::retval.
Referenced by int_var_statistic(), and parse::value_ref_parser< int >().
simple_int_parser_rules& anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules ()
References anonymous_namespace{Version.cpp}::retval.
Referenced by int_bound_variable(), int_bound_variable_name(), int_constant(), int_free_variable(), int_free_variable_name(), and int_simple().