FreeOrion: monsters Namespace Reference
monsters Namespace Reference
Classes
class StarlaneAlteringMonsters
Functions
def generate_monsters
def populate_monster_fleet
Variables
dictionary fleet_can_alter_starlanes
tuple fleet_plan = random.choice(suitable_fleet_plans)
tuple starlane_altering_monsters = StarlaneAlteringMonsters(systems)
list suitable_fleet_plans
Function Documentation
def monsters.generate_monsters (monster_freq, systems)
Adds space monsters to systems.
def monsters.populate_monster_fleet (fleet_plan, system)
Create a monster fleet in ''system'' according to ''fleet_plan''
Referenced by monsters.StarlaneAlteringMonsters.place().
Variable Documentation
dictionary monsters.fleet_can_alter_starlanes
Initial value:
 = {fp for fp in fleet_plans
                                  if any([universe.getGenericShipDesign(design).hull_type.hasTag("CAN_ALTER_STARLANES")
                                          for design in fp.ship_designs()])}
Definition Tag:
CAN_ALTER_STARLANES universe_generator special handling for fleets containing a hull design with this tag.
tuple monsters.fleet_plan = random.choice(suitable_fleet_plans)
Referenced by anonymous_namespace{ServerWrapper.cpp}::FleetPlanWrapper.FleetPlanWrapper(), anonymous_namespace{ServerWrapper.cpp}.LoadFleetPlanList(), anonymous_namespace{ServerWrapper.cpp}.LoadMonsterFleetPlanList(), and anonymous_namespace{FleetPlansParser.cpp}::rules.rules().
tuple monsters.starlane_altering_monsters = StarlaneAlteringMonsters(systems)
list monsters.suitable_fleet_plans
Initial value:
 = [fp for fp in fleet_plans
                                 if spawn_limits[fp]
                                 and fp.location(system)
                                 and (fp not in fleet_can_alter_starlanes
                                      or starlane_altering_monsters.can_place_at(system, fp))]