FreeOrion: SidePanel.cpp File Reference
SidePanel.cpp File Reference
#include <GL/glew.h>
#include "SidePanel.h"
#include "CUIWnd.h"
#include "CUIControls.h"
#include "MultiIconValueIndicator.h"
#include "SystemIcon.h"
#include "Sound.h"
#include "FleetWnd.h"
#include "BuildingsPanel.h"
#include "MilitaryPanel.h"
#include "PopulationPanel.h"
#include "ResourcePanel.h"
#include "MapWnd.h"
#include "ShaderProgram.h"
#include "SpecialsPanel.h"
#include "SystemResourceSummaryBrowseWnd.h"
#include "TextBrowseWnd.h"
#include "../universe/Predicates.h"
#include "../universe/ShipDesign.h"
#include "../universe/Fleet.h"
#include "../universe/Ship.h"
#include "../universe/Building.h"
#include "../universe/Species.h"
#include "../universe/System.h"
#include "../Empire/Empire.h"
#include "../util/Directories.h"
#include "../util/i18n.h"
#include "../util/Logger.h"
#include "../util/MultiplayerCommon.h"
#include "../util/Random.h"
#include "../util/XMLDoc.h"
#include "../util/Order.h"
#include "../util/OptionsDB.h"
#include "../util/ScopedTimer.h"
#include "../client/human/HumanClientApp.h"
#include <GG/GUI.h>
#include <GG/Layout.h>
#include <GG/DrawUtil.h>
#include <GG/StaticGraphic.h>
#include <GG/DynamicGraphic.h>
#include <GG/Scroll.h>
#include <GG/dialogs/ThreeButtonDlg.h>
#include <boost/cast.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/format.hpp>
#include <boost/filesystem/fstream.hpp>
Classes
struct anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData
struct anonymous_namespace{SidePanel.cpp}::PlanetAtmosphereData::Atmosphere
struct anonymous_namespace{SidePanel.cpp}::RotatingPlanetData
class anonymous_namespace{SidePanel.cpp}::SystemRow
class RotatingPlanetControl
class SidePanel::PlanetPanel
class SidePanel::PlanetPanelContainer
class SidePanel::SystemNameDropDownList
Namespaces
anonymous_namespace{SidePanel.cpp}
Functions
void anonymous_namespace{SidePanel.cpp}::AddOptions (OptionsDB &db)
std::set< TemporaryPtr< const
Ship > > AutomaticallyChosenBombardShips (int target_planet_id)
int AutomaticallyChosenColonyShip (int target_planet_id)
std::set< TemporaryPtr< const
Ship > > AutomaticallyChosenInvasionShips (int target_planet_id)
bool anonymous_namespace{SidePanel.cpp}::AvailableToBombard (TemporaryPtr< const Ship > ship, int system_id, int empire_id)
bool anonymous_namespace{SidePanel.cpp}::AvailableToColonize (TemporaryPtr< const Ship > ship, int system_id, int empire_id)
bool anonymous_namespace{SidePanel.cpp}::AvailableToInvade (TemporaryPtr< const Ship > ship, int system_id, int empire_id)
std::vector< std::string > anonymous_namespace{SidePanel.cpp}::BombardTagsForShip (TemporaryPtr< const Ship > ship)
void anonymous_namespace{SidePanel.cpp}::CancelColonizeInvadeBombardScrapShipOrders (TemporaryPtr< const Ship > ship)
bool anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType (TemporaryPtr< const Ship > ship, PlanetType planet_type)
bool anonymous_namespace{SidePanel.cpp}::ClientPlayerIsModerator ()
const int anonymous_namespace{SidePanel.cpp}::EDGE_PAD (3)
double anonymous_namespace{SidePanel.cpp}::GetAsteroidsFPS ()
const std::vector
< boost::shared_ptr
< GG::Texture > > & anonymous_namespace{SidePanel.cpp}::GetAsteroidTextures ()
GLfloat * anonymous_namespace{SidePanel.cpp}::GetLightPosition ()
const std::map< std::string,
PlanetAtmosphereData > & anonymous_namespace{SidePanel.cpp}::GetPlanetAtmosphereData ()
const std::string & anonymous_namespace{SidePanel.cpp}::GetPlanetEnvironmentName (TemporaryPtr< const Planet > planet, const std::string &species_name)
const std::string & anonymous_namespace{SidePanel.cpp}::GetPlanetSizeName (TemporaryPtr< const Planet > planet)
const std::string & anonymous_namespace{SidePanel.cpp}::GetPlanetTypeName (TemporaryPtr< const Planet > planet)
double anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetAmbientIntensity ()
const std::map< PlanetType,
std::vector
< RotatingPlanetData > > & anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetData ()
double anonymous_namespace{SidePanel.cpp}::GetRotatingPlanetDiffuseIntensity ()
const std::map< StarType,
std::vector< float > > & anonymous_namespace{SidePanel.cpp}::GetStarLightColors ()
const std::string & anonymous_namespace{SidePanel.cpp}::GetStarTypeName (TemporaryPtr< const System > system)
bool anonymous_namespace{SidePanel.cpp}::IsAvailable (TemporaryPtr< const Ship > ship, int system_id, int empire_id)
int anonymous_namespace{SidePanel.cpp}::MaxPlanetDiameter ()
GG::Pt anonymous_namespace{SidePanel.cpp}::MeterIconSize ()
std::map< int, std::set< int > > anonymous_namespace{SidePanel.cpp}::PendingBombardOrders ()
std::map< int, int > anonymous_namespace{SidePanel.cpp}::PendingColonizationOrders ()
std::map< int, std::set< int > > anonymous_namespace{SidePanel.cpp}::PendingInvadeOrders ()
int anonymous_namespace{SidePanel.cpp}::PlanetDiameter (PlanetSize size)
void anonymous_namespace{SidePanel.cpp}::PlaySidePanelOpenSound ()
void anonymous_namespace{SidePanel.cpp}::RenderPlanet (const GG::Pt &center, int diameter, boost::shared_ptr< GG::Texture > texture, boost::shared_ptr< GG::Texture > overlay_texture, double initial_rotation, double RPM, double axial_tilt, double shininess, StarType star_type)
void anonymous_namespace{SidePanel.cpp}::RenderSphere (double r, const GG::Clr &ambient, const GG::Clr &diffuse, const GG::Clr &spec, double shine, boost::shared_ptr< GG::Texture > texture)
const std::vector< float > & anonymous_namespace{SidePanel.cpp}::StarLightColour (StarType star_type)
int anonymous_namespace{SidePanel.cpp}::SystemNameFontSize ()
std::set< TemporaryPtr< const
Ship > > anonymous_namespace{SidePanel.cpp}::ValidSelectedBombardShips (int system_id)
TemporaryPtr< const Ship > ValidSelectedColonyShip (int system_id)
std::set< TemporaryPtr< const
Ship > > anonymous_namespace{SidePanel.cpp}::ValidSelectedInvasionShips (int system_id)
Variables
std::map< std::pair< int, int >
, float > anonymous_namespace{SidePanel.cpp}::colony_projections
const std::string anonymous_namespace{SidePanel.cpp}::EMPTY_STRING
const GG::Y anonymous_namespace{SidePanel.cpp}::PLANET_PANEL_TOP = GG::Y(140)
static const bool anonymous_namespace{SidePanel.cpp}::SHOW_ALL_PLANET_PANELS = false
toggles whether to show population, resource, military and building info panels on planet panels that this player doesn't control
std::map< std::pair
< std::string, int >, float > anonymous_namespace{SidePanel.cpp}::species_colony_projections
const std::string anonymous_namespace{SidePanel.cpp}::TAG_BOMBARD_ALWAYS = "CTRL_ALWAYS_BOMBARD"
const std::string anonymous_namespace{SidePanel.cpp}::TAG_BOMBARD_PREFIX = "CTRL_BOMBARD_"
bool anonymous_namespace{SidePanel.cpp}::temp_bool = RegisterOptions(&AddOptions)
Function Documentation
std::set<TemporaryPtr<const Ship> > AutomaticallyChosenBombardShips (int target_planet_id)
Returns valid Ships capable of bombarding a given Planet.
Parameters
target_planet_id ID of Planet to potentially bombard
References ALL_EMPIRES, anonymous_namespace{SidePanel.cpp}::AvailableToBombard(), anonymous_namespace{SidePanel.cpp}::BombardTagsForShip(), ClientApp::EmpireID(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), GetPlanet(), GetSystem(), Planet::HasTag(), Objects(), UniverseObject::OwnedBy(), anonymous_namespace{Version.cpp}::retval, UniverseObject::SystemID(), and anonymous_namespace{SidePanel.cpp}::TAG_BOMBARD_ALWAYS.
Referenced by SidePanel::PlanetPanel::ClickBombard(), and SidePanel::PlanetPanel::Refresh().
int AutomaticallyChosenColonyShip (int target_planet_id)
References ALL_EMPIRES, anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), anonymous_namespace{SidePanel.cpp}::colony_projections, ShipDesign::ColonyCapacity(), Planet::CurrentMeterValue(), Ship::Design(), ClientApp::EmpireID(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), Planet::GetMeter(), GetPlanet(), Species::GetPlanetEnvironment(), GetSpecies(), GetSystem(), GetUniverse(), UniverseObject::ID(), Universe::InhibitUniverseObjectSignals(), Meter::Initial(), INVALID_OBJECT_ID, METER_POPULATION, METER_TARGET_POPULATION, Objects(), UniverseObject::OwnedBy(), UniverseObject::Owner(), Meter::Set(), UniverseObject::SetOwner(), PopCenter::SetSpecies(), System::ShipIDs(), parse::species(), anonymous_namespace{SidePanel.cpp}::species_colony_projections, PopCenter::SpeciesName(), Ship::SpeciesName(), UniverseObject::SystemID(), Planet::Type(), UniverseObject::Unowned(), and Universe::UpdateMeterEstimates().
Referenced by SidePanel::PlanetPanel::ClickColonize(), and SidePanel::PlanetPanel::Refresh().
std::set<TemporaryPtr<const Ship> > AutomaticallyChosenInvasionShips (int target_planet_id)
References ALL_EMPIRES, anonymous_namespace{SidePanel.cpp}::AvailableToInvade(), ClientApp::EmpireID(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), GetPlanet(), GetSystem(), METER_TROOPS, Planet::NextTurnCurrentMeterValue(), Objects(), UniverseObject::OwnedBy(), anonymous_namespace{Version.cpp}::retval, UniverseObject::SystemID(), and Ship::TroopCapacity().
Referenced by SidePanel::PlanetPanel::ClickInvade(), and SidePanel::PlanetPanel::Refresh().
TemporaryPtr<const Ship> ValidSelectedColonyShip (int system_id)
References AIInterface::EmpireID(), HumanClientApp::GetApp(), GetShip(), and INVALID_OBJECT_ID.
Referenced by SidePanel::PlanetPanel::ClickColonize(), and SidePanel::PlanetPanel::Refresh().