FreeOrion: Condition::Location Struct Reference
Condition::Location Struct Reference
#include <Condition.h>
Public Member Functions
Location (ContentType content_type, ValueRef::ValueRefBase< std::string > *name1, ValueRef::ValueRefBase< std::string > *name2=nullptr)
virtual ~Location ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
const ValueRef::ValueRefBase
< std::string > * GetName1 () const
const ValueRef::ValueRefBase
< std::string > * GetName2 () const
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
void Eval (ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ContentType m_content_type
ValueRef::ValueRefBase
< std::string > * m_name1
ValueRef::ValueRefBase
< std::string > * m_name2
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches objects that match the location condition of the specified content.
Constructor & Destructor Documentation
Condition::Location::Location (ContentType content_type, ValueRef::ValueRefBase< std::string > * name1, ValueRef::ValueRefBase< std::string > * name2 = nullptr) inline
Condition::Location::~Location () virtual
References m_name1, and m_name2.
Member Function Documentation
std::string Condition::Location::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Description(), FlexibleFormat(), m_name1, m_name2, and UserString().
std::string Condition::Location::Dump () const override virtual
Implements Condition::ConditionBase.
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_content_type, m_name1, and m_name2.
void Condition::Location::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), m_content_type, m_name1, m_name2, Condition::MATCHES, and RootCandidateInvariant().
void Condition::Location::Eval (ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
References Condition::ConditionBase::Eval().
const ValueRef::ValueRefBase<std::string>* Condition::Location::GetName1 () const inline
const ValueRef::ValueRefBase<std::string>* Condition::Location::GetName2 () const inline
bool Condition::Location::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), Condition::anonymous_namespace{Condition.cpp}::GetLocationCondition(), m_content_type, m_name1, and m_name2.
bool Condition::Location::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, m_content_type, m_name1, and m_name2.
bool Condition::Location::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_name1, m_name2, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
Referenced by Eval().
template<class Archive > void Condition::Location::serialize (Archive & ar, const unsigned int version) private
References m_content_type, m_name1, and m_name2.
void Condition::Location::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_name1, m_name2, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::Location::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_name1, m_name2, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::Location::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_name1, m_name2, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ContentType Condition::Location::m_content_type private
Referenced by Dump(), Eval(), Match(), operator==(), and serialize().
ValueRef::ValueRefBase<std::string>* Condition::Location::m_name1 private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~Location().
ValueRef::ValueRefBase<std::string>* Condition::Location::m_name2 private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~Location().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp