FreeOrion: anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo Struct Reference
anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo Struct Reference
A collection of information the autoresolution must keep around.
Public Types
typedef std::map< int,
EmpireCombatInfo >::iterator empire_it
Public Member Functions
AutoresolveInfo (CombatInfo &combat_info)
std::vector< int > AddFighters (int number, float damage, int owner_empire_id, int from_ship_id, const std::string &species)
bool CanSomeoneAttackSomething () const
bool CheckDestruction (const TemporaryPtr< const UniverseObject > &target)
void CleanEmpires ()
void CullTheDead (int bout, BoutEvent::BoutEventPtr &bout_event)
Removes dead units from lists of attackers and defenders.
void GetShuffledValidAttackerIDs (std::vector< int > &shuffled)
Returns the list of attacker ids in a random order.
InitialStealthEvent::StealthInvisbleMap ReportInvisibleObjects (const CombatInfo &combat_info) const
Public Attributes
CombatInfo & combat_info
std::map< int, EmpireCombatInfo > empire_infos
float monster_detection
int next_fighter_id
std::set< int > valid_attacker_object_ids
std::set< int > valid_target_object_ids
Private Types
typedef std::set< int >
::const_iterator const_id_iterator
Private Member Functions
void PopulateAttackersAndTargets (const CombatInfo &combat_info)
void PopulateEmpireTargets (const CombatInfo &combat_info)
Detailed Description
A collection of information the autoresolution must keep around.
Member Typedef Documentation
typedef std::set<int>::const_iterator anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::const_id_iterator private
typedef std::map<int, EmpireCombatInfo>::iterator anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::empire_it
Constructor & Destructor Documentation
anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AutoresolveInfo (CombatInfo & combat_info) inline
References anonymous_namespace{CombatSystem.cpp}::GetMonsterDetection().
Member Function Documentation
std::vector<int> anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::AddFighters (int number, float damage, int owner_empire_id, int from_ship_id, const std::string & species) inline
References DebugLogger, ErrorLogger, UniverseObject::ID(), anonymous_namespace{CombatSystem.cpp}::ObjectAttackableByEmpire(), UniverseObject::Owner(), UniverseObject::Rename(), anonymous_namespace{Version.cpp}::retval, UniverseObject::SetID(), and UserString().
Referenced by anonymous_namespace{CombatSystem.cpp}::LaunchFighters().
bool anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CanSomeoneAttackSomething () const inline
bool anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CheckDestruction (const TemporaryPtr< const UniverseObject > & target) inline
Checks if target is destroyed and if it is, update lists of living objects. Return true if is incapacitated
References ALL_EMPIRES, UniverseObject::CurrentMeterValue(), DebugLogger, Fighter::Destroyed(), boost::dynamic_pointer_cast(), OptionsDB::Get(), GetOptionsDB(), UniverseObject::ID(), METER_CONSTRUCTION, METER_DEFENSE, METER_SHIELD, METER_STRUCTURE, anonymous_namespace{CombatSystem.cpp}::ObjectCanAttack(), UniverseObject::ObjectType(), and UniverseObject::Owner().
void anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CleanEmpires () inline
check if any empire has no remaining target or attacker objects. If so, remove that empire's entry
References DebugLogger, OptionsDB::Get(), and GetOptionsDB().
void anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::CullTheDead (int bout, BoutEvent::BoutEventPtr & bout_event) inline
Removes dead units from lists of attackers and defenders.
References SimultaneousEvents::AddEvent(), ALL_EMPIRES, UniverseObject::ID(), UniverseObject::Owner(), and boost::static_pointer_cast().
Referenced by anonymous_namespace{CombatSystem.cpp}::CombatRound().
void anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::GetShuffledValidAttackerIDs (std::vector< int > & shuffled) inline
Returns the list of attacker ids in a random order.
References RandInt(), and swap().
Referenced by anonymous_namespace{CombatSystem.cpp}::CombatRound().
void anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateAttackersAndTargets (const CombatInfo & combat_info) inline private
References ObjectMap::const_begin(), ObjectMap::const_end(), DebugLogger, OptionsDB::Get(), GetOptionsDB(), UniverseObject::Name(), anonymous_namespace{CombatSystem.cpp}::ObjectCanAttack(), CombatInfo::objects, anonymous_namespace{CombatSystem.cpp}::ObjectTypeCanBeAttacked(), and UniverseObject::Owner().
void anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::PopulateEmpireTargets (const CombatInfo & combat_info) inline private
References ALL_EMPIRES, DebugLogger, CombatInfo::empire_ids, OptionsDB::Get(), GetOptionsDB(), UniverseObject::Name(), ObjectMap::Object(), anonymous_namespace{CombatSystem.cpp}::ObjectAttackableByEmpire(), anonymous_namespace{CombatSystem.cpp}::ObjectAttackableByMonsters(), CombatInfo::objects, and UniverseObject::Owner().
InitialStealthEvent::StealthInvisbleMap anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::ReportInvisibleObjects (const CombatInfo & combat_info) const inline
Report for each empire the stealth objects in the combat.
References ALL_EMPIRES, DebugLogger, CombatInfo::empire_ids, CombatInfo::empire_object_visibility, OptionsDB::Get(), GetOptionsDB(), UniverseObject::ID(), UniverseObject::Name(), ObjectMap::Object(), CombatInfo::objects, anonymous_namespace{CombatSystem.cpp}::ObjectUnTargettableByEmpire(), anonymous_namespace{CombatSystem.cpp}::ObjectUnTargettableByMonsters(), and UniverseObject::Owner().
Member Data Documentation
CombatInfo& anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::combat_info
Referenced by anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons(), and anonymous_namespace{CombatSystem.cpp}::ValidTargetsForAttackerType().
std::map<int, EmpireCombatInfo> anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::empire_infos
Referenced by anonymous_namespace{CombatSystem.cpp}::CombatRound(), and anonymous_namespace{CombatSystem.cpp}::ShootAllWeapons().
float anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::monster_detection
int anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::next_fighter_id
std::set<int> anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::valid_attacker_object_ids
Referenced by anonymous_namespace{CombatSystem.cpp}::CombatRound().
std::set<int> anonymous_namespace{CombatSystem.cpp}::AutoresolveInfo::valid_target_object_ids
The documentation for this struct was generated from the following file:
CombatSystem.cpp