FreeOrion: Condition::PlanetType Struct Reference
Condition::PlanetType Struct Reference
#include <Condition.h>
Public Member Functions
PlanetType (const std::vector< ValueRef::ValueRefBase< ::PlanetType > * > &types)
virtual ~PlanetType ()
virtual std::string Description (bool negated=false) const
virtual std::string Dump () const
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
virtual bool operator== (const ConditionBase &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
const std::vector
< ValueRef::ValueRefBase
< ::PlanetType > * > & Types () const
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
void Eval (ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector
< ValueRef::ValueRefBase
< ::PlanetType > * > m_types
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all Planet objects that have one of the PlanetTypes in types. Note that all Building objects which are on matching planets are also matched.
Constructor & Destructor Documentation
Condition::PlanetType::PlanetType (const std::vector< ValueRef::ValueRefBase< ::PlanetType > * > & types) inline
Condition::PlanetType::~PlanetType () virtual
References m_types.
Member Function Documentation
std::string Condition::PlanetType::Description (bool negated = false) const virtual
Implements Condition::ConditionBase.
References Eval(), FlexibleFormat(), m_types, and UserString().
std::string Condition::PlanetType::Dump () const virtual
Implements Condition::ConditionBase.
References DumpIndent(), and m_types.
void Condition::PlanetType::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_types, and RootCandidateInvariant().
Referenced by Description(), Condition::PlanetSize::Description(), Condition::PlanetEnvironment::Description(), Condition::Species::Description(), Condition::FocusType::Description(), Condition::StarType::Description(), Condition::PlanetSize::Match(), Condition::PlanetEnvironment::Match(), Condition::Species::Match(), Condition::FocusType::Match(), and Condition::StarType::Match().
void Condition::PlanetType::Eval (ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
References Condition::ConditionBase::Eval().
void Condition::PlanetType::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddBuildingSet(), and anonymous_namespace{Condition.cpp}::AddPlanetSet().
bool Condition::PlanetType::Match (const ScriptingContext & local_context) const private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, boost::dynamic_pointer_cast(), ErrorLogger, GetPlanet(), m_types, and Planet::Type().
bool Condition::PlanetType::operator== (const ConditionBase & rhs) const virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_types.
bool Condition::PlanetType::RootCandidateInvariant () const virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_types.
Referenced by Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::Enqueued::Eval(), Condition::FocusType::Eval(), Condition::StarType::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::Chance::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), and Condition::OwnerHasTech::Eval().
template<class Archive > void Condition::PlanetType::serialize (Archive & ar, const unsigned int version) private
References m_types.
void Condition::PlanetType::SetTopLevelContent (const std::string & content_name) virtual
Implements Condition::ConditionBase.
References m_types.
bool Condition::PlanetType::SourceInvariant () const virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_types.
bool Condition::PlanetType::TargetInvariant () const virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_types.
const std::vector<ValueRef::ValueRefBase< ::PlanetType>*>& Condition::PlanetType::Types () const inline
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<ValueRef::ValueRefBase< ::PlanetType>*> Condition::PlanetType::m_types private
Referenced by Description(), Condition::StarType::Description(), Dump(), Condition::StarType::Dump(), Eval(), Condition::StarType::Eval(), Match(), Condition::StarType::Match(), Condition::anonymous_namespace{Condition.cpp}::PlanetTypeSimpleMatch::operator()(), Condition::anonymous_namespace{Condition.cpp}::StarTypeSimpleMatch::operator()(), operator==(), Condition::StarType::operator==(), RootCandidateInvariant(), Condition::StarType::RootCandidateInvariant(), serialize(), SetTopLevelContent(), Condition::StarType::SetTopLevelContent(), SourceInvariant(), Condition::StarType::SourceInvariant(), TargetInvariant(), Condition::StarType::TargetInvariant(), ~PlanetType(), and Condition::StarType::~StarType().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp