FreeOrion: anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules Struct Reference
anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules Struct Reference
Public Types
typedef expression_rule
< double >::type expression_rule
typedef
parse::value_ref_parser_rule
< double >::type rule
typedef statistic_rule< double >
::type statistic_rule
typedef variable_rule< double >
::type variable_rule
Public Member Functions
double_parser_rules ()
Public Attributes
expression_rule additive_expr
variable_rule bound_variable
name_token_rule bound_variable_name
rule constant
expression_rule exponential_expr
rule expr
variable_rule free_variable
name_token_rule free_variable_name
expression_rule function_expr
rule int_bound_variable_cast
rule int_complex_variable_cast
rule int_statistic_cast
expression_rule multiplicative_expr
rule primary_expr
statistic_rule statistic
statistic_rule statistic_1
statistic_rule statistic_2
Member Typedef Documentation
typedef expression_rule<double>::type anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::expression_rule
typedef parse::value_ref_parser_rule<double>::type anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::rule
typedef statistic_rule<double>::type anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::statistic_rule
typedef variable_rule<double>::type anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::variable_rule
Constructor & Destructor Documentation
anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::double_, double_var_complex(), ValueRef::EFFECT_TARGET_VALUE_REFERENCE, parse::lexer::instance(), parse::lexer::int_, int_bound_variable(), int_free_variable(), int_var_complex(), int_var_statistic(), and ValueRef::NON_OBJECT_REFERENCE.
Member Data Documentation
expression_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::additive_expr
variable_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::bound_variable
Referenced by double_bound_variable().
name_token_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::bound_variable_name
Referenced by double_bound_variable_name().
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::constant
Referenced by double_constant().
expression_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::exponential_expr
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::expr
Referenced by parse::value_ref_parser< double >().
variable_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::free_variable
Referenced by double_free_variable().
name_token_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::free_variable_name
Referenced by double_free_variable_name().
expression_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::function_expr
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::int_bound_variable_cast
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::int_complex_variable_cast
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::int_statistic_cast
expression_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::multiplicative_expr
rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::primary_expr
statistic_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::statistic
Referenced by double_var_statistic().
statistic_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::statistic_1
statistic_rule anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::statistic_2
The documentation for this struct was generated from the following file:
DoubleValueRefParser.cpp