FreeOrion: anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4 Struct Reference
anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< std::string > *, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > create_building_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< double > *, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > create_field_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< ::PlanetType >
*, ValueRef::ValueRefBase
< ::PlanetSize >
*, ValueRef::ValueRefBase
< std::string > *, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > create_planet_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< int >
*, ValueRef::ValueRefBase
< int >
*, ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< std::string > *, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > create_ship_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< ::StarType >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< std::string > *, std::vector
< Effect::EffectBase * >
>, parse::skipper_type > create_system_rule
Public Member Functions
effect_parser_rules_4 ()
Public Attributes
create_building_rule create_building
create_field_rule create_field_1
create_field_rule create_field_2
create_planet_rule create_planet
create_ship_rule create_ship_1
create_ship_rule create_ship_2
create_system_rule create_system_1
create_system_rule create_system_2
parse::effect_parser_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<std::string>*, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_building_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<double>*, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_field_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase< ::PlanetType>*, ValueRef::ValueRefBase< ::PlanetSize>*, ValueRef::ValueRefBase<std::string>*, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_planet_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<std::string>*, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_ship_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase< ::StarType>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<std::string>*, std::vector<Effect::EffectBase*> >, parse::skipper_type > anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_system_rule
Constructor & Destructor Documentation
anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::effect_parser(), parse::lexer::instance(), parse::label(), parse::value_ref_parser< double >(), and parse::value_ref_parser< int >().
Member Data Documentation
create_building_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_building
create_field_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_field_1
create_field_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_field_2
create_planet_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_planet
create_ship_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_ship_1
create_ship_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_ship_2
create_system_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_system_1
create_system_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::create_system_2
parse::effect_parser_rule anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::start
The documentation for this struct was generated from the following file:
EffectParser4.cpp