FreeOrion: Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch Struct Reference
Public Member Functions
CanAddStarlaneConnectionSimpleMatch (const ObjectSet &destination_objects)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
std::vector< TemporaryPtr
< const System > > m_destination_systems
Constructor & Destructor Documentation
Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::CanAddStarlaneConnectionSimpleMatch (const ObjectSet & destination_objects) inline
References GetSystem().
Member Function Documentation
bool Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References boost::dynamic_pointer_cast(), GetSystem(), System::HasStarlaneTo(), UniverseObject::ID(), Condition::anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane(), Condition::anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose(), Condition::anonymous_namespace{Condition.cpp}::LaneTooCloseToOtherSystem(), System::StarlanesWormholes(), and UniverseObject::SystemID().
Member Data Documentation
std::vector<TemporaryPtr<const System> > Condition::anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::m_destination_systems
The documentation for this struct was generated from the following file:
Condition.cpp