FreeOrion: MapWnd::MovementLineData Struct Reference
MapWnd::MovementLineData Struct Reference
Classes
struct Vertex
Public Member Functions
MovementLineData ()
MovementLineData (const std::list< MovePathNode > &path_, const std::map< std::pair< int, int >, LaneEndpoints > &lane_end_points_map, GG::Clr colour_=GG::CLR_WHITE, int empireID=ALL_EMPIRES)
Public Attributes
GG::Clr colour
std::list< MovePathNode > path
std::vector< Vertex > vertices
Detailed Description
contains information necessary to render a single fleet movement line on the main map. also contains cached infromation
Constructor & Destructor Documentation
MapWnd::MovementLineData::MovementLineData ()
MapWnd::MovementLineData::MovementLineData (const std::list< MovePathNode > & path_, const std::map< std::pair< int, int >, LaneEndpoints > & lane_end_points_map, GG::Clr colour_ = GG::CLR_WHITE, int empireID = ALL_EMPIRES)
References ErrorLogger, MovePathNode::eta, Fleet::ETA_NEVER, Fleet::ETA_OUT_OF_RANGE, Fleet::ETA_UNKNOWN, GetEmpire(), INVALID_OBJECT_ID, MovePathNode::object_id, path, anonymous_namespace{MapWnd.cpp}::ScreenPosOnStarane(), Empire::SupplyUnobstructedSystems(), anonymous_namespace{MapWnd.cpp}::UnorderedIntPair(), vertices, MovePathNode::x, and MovePathNode::y.
Member Data Documentation
GG::Clr MapWnd::MovementLineData::colour
Referenced by MapWnd::RenderMovementLine(), and MapWnd::RenderMovementLineETAIndicators().
std::list<MovePathNode> MapWnd::MovementLineData::path
Referenced by MovementLineData(), and MapWnd::ReplotProjectedFleetMovement().
std::vector<Vertex> MapWnd::MovementLineData::vertices
Referenced by MovementLineData(), MapWnd::RenderMovementLine(), and MapWnd::RenderMovementLineETAIndicators().
The documentation for this struct was generated from the following files:
MapWnd.h
MapWnd.cpp