FreeOrion: anonymous_namespace{VarText.cpp}::SubstituteAndAppend Struct Reference
anonymous_namespace{VarText.cpp}::SubstituteAndAppend Struct Reference
Public Member Functions
SubstituteAndAppend (const XMLElement &variables, std::string &str, bool &valid)
void operator() (const char *first, const char *last) const
Public Attributes
std::string & m_str
bool & m_valid
const XMLElement & m_variables
Detailed Description
Converts (first, last) to a string, looks up its value in the Universe, then appends this to the end of a std::string.
Constructor & Destructor Documentation
anonymous_namespace{VarText.cpp}::SubstituteAndAppend::SubstituteAndAppend (const XMLElement & variables, std::string & str, bool & valid) inline
Member Function Documentation
void anonymous_namespace{VarText.cpp}::SubstituteAndAppend::operator() (const char * first, const char * last) const inline
References XMLElement::Child(), ErrorLogger, parse::label(), anonymous_namespace{VarText.cpp}::SubstitutionMap(), and UserString().
Member Data Documentation
std::string& anonymous_namespace{VarText.cpp}::SubstituteAndAppend::m_str
bool& anonymous_namespace{VarText.cpp}::SubstituteAndAppend::m_valid
const XMLElement& anonymous_namespace{VarText.cpp}::SubstituteAndAppend::m_variables
The documentation for this struct was generated from the following file:
VarText.cpp