FreeOrion: anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1 Struct Reference
anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1 Struct Reference
Public Types
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< std::vector< Condition::ConditionBase * > > > and_or_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< std::string > > described_rule
typedef parse::detail::rule< Condition::ConditionBase *(), qi::locals< EmpireAffiliationType > > owned_by_rule
Public Member Functions
condition_parser_rules_1 ()
Public Attributes
parse::condition_parser_rule aggressive
parse::condition_parser_rule all
and_or_rule and_
parse::condition_parser_rule armed
parse::condition_parser_rule can_colonize
parse::condition_parser_rule can_produce_ships
parse::condition_parser_rule capital
described_rule described
parse::condition_parser_rule monster
parse::condition_parser_rule none
parse::condition_parser_rule not_
and_or_rule or_
parse::condition_parser_rule owned_by
parse::condition_parser_rule owned_by_1
parse::condition_parser_rule owned_by_2
parse::condition_parser_rule owned_by_3
parse::condition_parser_rule owned_by_4
owned_by_rule owned_by_5
parse::condition_parser_rule root_candidate
parse::condition_parser_rule source
parse::condition_parser_rule start
parse::condition_parser_rule stationary
parse::condition_parser_rule target
Member Typedef Documentation
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals<std::vector<Condition::ConditionBase*> > > anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::and_or_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals<std::string> > anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::described_rule
typedef parse::detail::rule< Condition::ConditionBase* (), qi::locals<EmpireAffiliationType> > anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::condition_parser_rules_1 () inline
References anonymous_namespace{EnumParser.cpp}::_val, AFFIL_ANY, AFFIL_HUMAN, AFFIL_NONE, parse::detail::condition_parser, parse::empire_affiliation_type_enum(), parse::lexer::instance(), parse::int_value_ref(), parse::detail::label(), and parse::lexer::string.
Member Data Documentation
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::aggressive
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::all
and_or_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::and_
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::armed
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::can_colonize
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::can_produce_ships
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::capital
described_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::described
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::monster
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::none
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::not_
and_or_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::or_
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_1
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_2
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_3
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_4
owned_by_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::owned_by_5
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::root_candidate
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::source
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::start
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::stationary
parse::condition_parser_rule anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::target
The documentation for this struct was generated from the following file:
ConditionParser1.cpp