FreeOrion: Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch Struct Reference
Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch Struct Reference
Public Member Functions
ShipPartMeterValueSimpleMatch (const std::string &ship_part_name, MeterType meter, float low, float high)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
float m_high
float m_low
MeterType m_meter
std::string m_part_name
Constructor & Destructor Documentation
Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::ShipPartMeterValueSimpleMatch (const std::string & ship_part_name, MeterType meter, float low, float high) inline
Member Function Documentation
bool Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References Meter::Current(), boost::dynamic_pointer_cast(), and Ship::GetPartMeter().
Member Data Documentation
float Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::m_high
float Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::m_low
MeterType Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::m_meter
std::string Condition::anonymous_namespace{Condition.cpp}::ShipPartMeterValueSimpleMatch::m_part_name
The documentation for this struct was generated from the following file:
Condition.cpp