FreeOrion: parse::detail::rules Struct Reference
parse::detail::rules Struct Reference
Public Types
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::map< MeterType, val_cond_pair > &, std::map< std::string, val_cond_pair > &), qi::locals< MeterType, std::string, ValueRef::ValueRefBase< double > *, Condition::ConditionBase * >, parse::skipper_type > consumable_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::map< MeterType, val_cond_pair > &, std::map< std::string, val_cond_pair > &), parse::skipper_type > consumption_rule
typedef qi::rule< token_iterator, void(std::set< std::string > &), parse::skipper_type > exclusions_rule
typedef std::pair< ValueRef::ValueRefBase< double > *, Condition::ConditionBase * > val_cond_pair
Public Member Functions
rules ()
Public Attributes
common_params_rule common
consumable_rule consumable_meter
consumable_rule consumable_special
consumption_rule consumption
location_rule enqueue_location
exclusions_rule exclusions
location_rule location
more_common_params_rule more_common
producible_rule producible
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<MeterType, val_cond_pair>&, std::map<std::string, val_cond_pair>&), qi::locals< MeterType, std::string, ValueRef::ValueRefBase<double>*, Condition::ConditionBase* >, parse::skipper_type > parse::detail::rules::consumable_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<MeterType, val_cond_pair>&, std::map<std::string, val_cond_pair>&), parse::skipper_type > parse::detail::rules::consumption_rule
typedef qi::rule< token_iterator, void (std::set<std::string>&), parse::skipper_type > parse::detail::rules::exclusions_rule
typedef std::pair<ValueRef::ValueRefBase<double>*, Condition::ConditionBase*> parse::detail::rules::val_cond_pair
Constructor & Destructor Documentation
parse::detail::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, consumable_meter, consumable_special, consumption, parse::detail::effects_group_parser(), enqueue_location, exclusions, anonymous_namespace{BuildingsParser.cpp}::insert, parse::lexer::instance(), parse::label(), location, more_common, parse::non_ship_part_meter_type_enum(), producible, parse::lexer::string, parse::detail::tags_parser(), parse::value_ref_parser< double >(), and parse::value_ref_parser_flexible_int().
Member Data Documentation
common_params_rule parse::detail::rules::common
Referenced by parse::detail::common_params_parser().
consumable_rule parse::detail::rules::consumable_meter
Referenced by rules().
consumable_rule parse::detail::rules::consumable_special
Referenced by rules().
consumption_rule parse::detail::rules::consumption
Referenced by rules().
location_rule parse::detail::rules::enqueue_location
Referenced by rules().
exclusions_rule parse::detail::rules::exclusions
Referenced by rules().
location_rule parse::detail::rules::location
Referenced by parse::detail::location_parser(), and rules().
more_common_params_rule parse::detail::rules::more_common
Referenced by parse::detail::more_common_params_parser(), and rules().
producible_rule parse::detail::rules::producible
Referenced by parse::detail::producible_parser(), and rules().
The documentation for this struct was generated from the following file:
CommonParamsParser.cpp