FreeOrion: CombatEvent Struct Reference
CombatEvent Struct Reference abstract
An abstract base class for combat events.
#include <CombatEvent.h>
Public Member Functions
CombatEvent ()
virtual ~CombatEvent ()
virtual bool AreDetailsEmpty (int viewing_empire_id) const
virtual bool AreSubEventsEmpty (int viewing_empire_id) const
virtual std::string CombatLogDescription (int viewing_empire_id) const =0
virtual std::string CombatLogDetails (int viewing_empire_id) const
virtual std::string DebugString () const =0
virtual bool FlattenSubEvents () const
virtual boost::optional< int > PrincipalFaction (int viewing_empire_id) const
virtual std::vector< ConstCombatEventPtr > SubEvents (int viewing_empire_id) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
An abstract base class for combat events.
Combat events are created during combat processing to act as a log of combat events.
Many combat events are created, but few are examined by players. The constructors must be fast. They should not do any string processing in the contructor. The descriptions can be expanded on request.
Constructor & Destructor Documentation
CombatEvent::CombatEvent ()
virtual CombatEvent::~CombatEvent () inline virtual
Member Function Documentation
virtual bool CombatEvent::AreDetailsEmpty (int viewing_empire_id) const inline virtual
Return true if there are no details;
Reimplemented in WeaponFireEvent.
virtual bool CombatEvent::AreSubEventsEmpty (int viewing_empire_id) const inline virtual
Return true if there are no sub events;
Reimplemented in WeaponsPlatformEvent, StealthChangeEvent, SimultaneousEvents, and BoutEvent.
Referenced by StealthChangeEvent::~StealthChangeEvent().
virtual std::string CombatEvent::CombatLogDescription (int viewing_empire_id) const pure virtual
Generate the combat log description. Describe the result of a combat event (i.e. what happened).
Implemented in WeaponsPlatformEvent, FighterLaunchEvent, FightersAttackFightersEvent, IncapacitationEvent, WeaponFireEvent, StealthChangeEvent::StealthChangeEventDetail, StealthChangeEvent, InitialStealthEvent, SimultaneousEvents, BoutEvent, and BoutBeginEvent.
Referenced by BoutBeginEvent::~BoutBeginEvent(), BoutEvent::~BoutEvent(), InitialStealthEvent::~InitialStealthEvent(), SimultaneousEvents::~SimultaneousEvents(), and StealthChangeEvent::~StealthChangeEvent().
virtual std::string CombatEvent::CombatLogDetails (int viewing_empire_id) const inline virtual
Generate the combat log details. Describe how it happened in enough detail to avoid a trip to the Pedia.
Reimplemented in WeaponFireEvent.
virtual std::string CombatEvent::DebugString () const pure virtual
Implemented in WeaponsPlatformEvent, FighterLaunchEvent, FightersAttackFightersEvent, IncapacitationEvent, WeaponFireEvent, StealthChangeEvent::StealthChangeEventDetail, StealthChangeEvent, InitialStealthEvent, SimultaneousEvents, BoutEvent, and BoutBeginEvent.
Referenced by PrincipalFaction(), BoutBeginEvent::~BoutBeginEvent(), BoutEvent::~BoutEvent(), InitialStealthEvent::~InitialStealthEvent(), SimultaneousEvents::~SimultaneousEvents(), and StealthChangeEvent::~StealthChangeEvent().
virtual bool CombatEvent::FlattenSubEvents () const inline virtual
Return true if sub events are to be flattened on display;
Reimplemented in SimultaneousEvents, and BoutEvent.
boost::optional< int > CombatEvent::PrincipalFaction (int viewing_empire_id) const virtual
Return principal faction.
PrincipalFaction is used by UnorderedEvents to sort the display of events by Facton. The principal faction should be the faction most active in the event (i.e. the attacker in a WeaponEvent). It is from the perspective of the viewing_empire_id. Some events like BoutBegin are not associated with any faction.
Reimplemented in WeaponsPlatformEvent, FighterLaunchEvent, IncapacitationEvent, and WeaponFireEvent.
References DebugString(), and ErrorLogger.
template<typename Archive > template void CombatEvent::serialize< freeorion_xml_oarchive > (Archive & ar, const unsigned int version) private
virtual std::vector<ConstCombatEventPtr> CombatEvent::SubEvents (int viewing_empire_id) const inline virtual
If the combat event is composed of smaller events then return a vector of the sub events, otherwise returns an empty vector.
Reimplemented in WeaponsPlatformEvent, StealthChangeEvent, SimultaneousEvents, and BoutEvent.
Referenced by BoutEvent::~BoutEvent(), SimultaneousEvents::~SimultaneousEvents(), and StealthChangeEvent::~StealthChangeEvent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
The documentation for this struct was generated from the following files:
CombatEvent.h
CombatEvent.cpp