FreeOrion: anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3 Struct Reference
anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3 Struct Reference
Public Types
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase *(), qi::locals< ValueRef::ValueRefBase< double > *, ValueRef::ValueRefBase< double > *, ValueRef::ValueRefBase< std::string > * >, parse::skipper_type > doubles_string_rule
Public Member Functions
effect_parser_rules_3 ()
Public Attributes
parse::effect_parser_rule add_special_1
doubles_string_rule add_special_2
parse::effect_parser_rule add_starlanes
parse::effect_parser_rule destroy
doubles_string_rule move_in_orbit
parse::effect_parser_rule move_to
doubles_string_rule move_towards
parse::effect_parser_rule noop
parse::effect_parser_rule remove_special
parse::effect_parser_rule remove_starlanes
parse::effect_parser_rule set_aggression
parse::effect_parser_rule set_destination
parse::effect_parser_rule set_star_type
parse::effect_parser_rule set_texture
parse::effect_parser_rule start
parse::effect_parser_rule victory
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<std::string>* >, parse::skipper_type > anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::doubles_string_rule
Constructor & Destructor Documentation
anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::effect_parser_rules_3 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::double_value_ref(), parse::lexer::instance(), parse::label(), parse::star_type_value_ref(), parse::lexer::string, and parse::string_value_ref().
Member Data Documentation
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::add_special_1
doubles_string_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::add_special_2
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::add_starlanes
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::destroy
doubles_string_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::move_in_orbit
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::move_to
doubles_string_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::move_towards
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::noop
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::remove_special
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::remove_starlanes
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::set_aggression
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::set_destination
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::set_star_type
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::set_texture
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::start
parse::effect_parser_rule anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::victory
The documentation for this struct was generated from the following file:
EffectParser3.cpp