FreeOrion: anonymous_namespace{TechsParser.cpp}::rules Struct Reference
anonymous_namespace{TechsParser.cpp}::rules Struct Reference
Public Types
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::map< std::string, TechCategory * > &), qi::locals< std::string, std::string >, parse::skipper_type > category_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo(std::set< std::string > &), parse::skipper_type > prerequisites_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(TechManager::TechContainer &), parse::skipper_type > start_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo(std::string &, std::string &, std::string &), parse::skipper_type > tech_info_name_desc_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo(), qi::locals< std::string, std::string, std::string, std::set< std::string >, std::string, ValueRef::ValueRefBase< double > *, ValueRef::ValueRefBase< int > *, bool >, parse::skipper_type > tech_info_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(TechManager::TechContainer &), qi::locals< Tech::TechInfo, std::set< std::string >, std::vector< ItemSpec >, std::vector< std::shared_ptr< Effect::EffectsGroup > >, std::string >, parse::skipper_type > tech_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo(std::vector< ItemSpec > &), parse::skipper_type > unlocks_rule
Public Member Functions
rules ()
Public Attributes
category_rule category
prerequisites_rule prerequisites
start_rule start
tech_rule tech
tech_info_rule tech_info
tech_info_name_desc_rule tech_info_name_desc
unlocks_rule unlocks
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, TechCategory*>&), qi::locals< std::string, std::string >, parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::category_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo (std::set<std::string>&), parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::prerequisites_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (TechManager::TechContainer&), parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::start_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo (std::string&, std::string&, std::string&), parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::tech_info_name_desc_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo (), qi::locals< std::string, std::string, std::string, std::set<std::string>, std::string, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<int>*, bool >, parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::tech_info_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (TechManager::TechContainer&), qi::locals< Tech::TechInfo, std::set<std::string>, std::vector<ItemSpec>, std::vector<std::shared_ptr<Effect::EffectsGroup> >, std::string >, parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::tech_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Tech::TechInfo (std::vector<ItemSpec>&), parse::skipper_type > anonymous_namespace{TechsParser.cpp}::rules::unlocks_rule
Constructor & Destructor Documentation
anonymous_namespace{TechsParser.cpp}::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::color_parser(), parse::detail::effects_group_parser(), anonymous_namespace{BuildingsParser.cpp}::insert, anonymous_namespace{TechsParser.cpp}::insert_category, anonymous_namespace{TechsParser.cpp}::insert_tech, parse::lexer::instance(), parse::detail::item_spec_parser(), parse::label(), parse::report_error, parse::lexer::string, parse::detail::tags_parser(), parse::value_ref_parser< double >(), and parse::value_ref_parser_flexible_int().
Member Data Documentation
category_rule anonymous_namespace{TechsParser.cpp}::rules::category
prerequisites_rule anonymous_namespace{TechsParser.cpp}::rules::prerequisites
start_rule anonymous_namespace{TechsParser.cpp}::rules::start
tech_rule anonymous_namespace{TechsParser.cpp}::rules::tech
tech_info_rule anonymous_namespace{TechsParser.cpp}::rules::tech_info
tech_info_name_desc_rule anonymous_namespace{TechsParser.cpp}::rules::tech_info_name_desc
unlocks_rule anonymous_namespace{TechsParser.cpp}::rules::unlocks
The documentation for this struct was generated from the following file:
TechsParser.cpp