FreeOrion: anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6 Struct Reference
anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< std::vector
< ValueRef::ValueRefBase
< std::string >
* > >, parse::skipper_type > building_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< std::vector
< ValueRef::ValueRefBase
< PlanetEnvironment >
* >, ValueRef::ValueRefBase
< std::string >
* >, parse::skipper_type > planet_environment_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< std::vector
< ValueRef::ValueRefBase
< PlanetSize >
* > >, parse::skipper_type > planet_size_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< std::vector
< ValueRef::ValueRefBase
< PlanetType >
* > >, parse::skipper_type > planet_type_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
std::vector
< ValueRef::ValueRefBase
< std::string >
* >), parse::skipper_type > string_ref_vec_rule
Public Member Functions
condition_parser_rules_6 ()
Public Attributes
building_rule building
parse::condition_parser_rule focus_type
parse::condition_parser_rule homeworld
parse::condition_parser_rule object_type
planet_environment_rule planet_environment
planet_size_rule planet_size
planet_type_rule planet_type
parse::condition_parser_rule species
parse::condition_parser_rule start
string_ref_vec_rule string_ref_vec
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals<std::vector<ValueRef::ValueRefBase<std::string>*> >, parse::skipper_type > anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::building_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals< std::vector<ValueRef::ValueRefBase<PlanetEnvironment>*>, ValueRef::ValueRefBase<std::string>* >, parse::skipper_type > anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_environment_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals<std::vector<ValueRef::ValueRefBase<PlanetSize>*> >, parse::skipper_type > anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_size_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals<std::vector<ValueRef::ValueRefBase<PlanetType>*> >, parse::skipper_type > anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_type_rule
typedef boost::spirit::qi::rule< parse::token_iterator, std::vector<ValueRef::ValueRefBase<std::string>*>), parse::skipper_type > anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::string_ref_vec_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::condition_parser_rules_6 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::enum_parser< UniverseObjectType >(), parse::lexer::instance(), parse::label(), parse::species(), parse::value_ref_parser< PlanetEnvironment >(), parse::value_ref_parser< PlanetSize >(), parse::value_ref_parser< PlanetType >(), and parse::value_ref_parser< UniverseObjectType >().
Member Data Documentation
building_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::building
parse::condition_parser_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::focus_type
parse::condition_parser_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::homeworld
parse::condition_parser_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::object_type
planet_environment_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_environment
planet_size_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_size
planet_type_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::planet_type
parse::condition_parser_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::species
parse::condition_parser_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::start
string_ref_vec_rule anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::string_ref_vec
The documentation for this struct was generated from the following file:
ConditionParser6.cpp