FreeOrion: Condition::Contains Struct Reference
Condition::Contains Struct Reference
#include <Condition.h>
Public Member Functions
Contains (ConditionBase *condition)
virtual ~Contains ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ConditionBase * m_condition
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects that contain an object that matches Condition condition. Container objects are Systems, Planets (which contain Buildings), and Fleets (which contain Ships).
Constructor & Destructor Documentation
Condition::Contains::Contains (ConditionBase * condition) inline
Condition::Contains::~Contains () virtual
References m_condition.
Member Function Documentation
std::string Condition::Contains::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References Condition::ConditionBase::Description(), FlexibleFormat(), m_condition, and UserString().
std::string Condition::Contains::Dump () const override virtual
Implements Condition::ConditionBase.
References Condition::ConditionBase::Dump(), DumpIndent(), g_indent, m_condition, and anonymous_namespace{Version.cpp}::retval.
void Condition::Contains::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, anonymous_namespace{CUIWnd.cpp}::dummy, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), m_condition, Condition::MATCHES, Condition::NON_MATCHES, Objects(), and RootCandidateInvariant().
void Condition::Contains::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const override virtual
Reimplemented from Condition::ConditionBase.
References anonymous_namespace{Condition.cpp}::AddFleetSet(), anonymous_namespace{Condition.cpp}::AddPlanetSet(), and anonymous_namespace{Condition.cpp}::AddSystemSet().
bool Condition::Contains::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, UniverseObject::Contains(), ErrorLogger, Condition::ConditionBase::Eval(), and m_condition.
bool Condition::Contains::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_condition.
bool Condition::Contains::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_condition, and Condition::ConditionBase::RootCandidateInvariant().
Referenced by Eval().
template<class Archive > void Condition::Contains::serialize (Archive & ar, const unsigned int version) private
References m_condition.
void Condition::Contains::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
References m_condition, and Condition::ConditionBase::SetTopLevelContent().
bool Condition::Contains::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_condition, and Condition::ConditionBase::SourceInvariant().
bool Condition::Contains::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_condition, and Condition::ConditionBase::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ConditionBase* Condition::Contains::m_condition private
Referenced by Description(), Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~Contains().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp