FreeOrion: anonymous_namespace{Parse.cpp}::effects_group_rules Struct Reference
anonymous_namespace{Parse.cpp}::effects_group_rules Struct Reference
Public Types
typedef parse::detail::rule< Effect::EffectsGroup *(), qi::locals< Condition::ConditionBase *, Condition::ConditionBase *, std::string, std::vector< Effect::EffectBase * >, std::string, int, std::string > > effects_group_rule
Public Member Functions
effects_group_rules ()
Public Attributes
effects_group_rule effects_group
parse::detail::effects_group_rule start
Member Typedef Documentation
typedef parse::detail::rule< Effect::EffectsGroup* (), qi::locals< Condition::ConditionBase*, Condition::ConditionBase*, std::string, std::vector<Effect::EffectBase*>, std::string, int, std::string > > anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rule
Constructor & Destructor Documentation
anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::effect_parser(), parse::lexer::instance(), parse::lexer::int_, parse::detail::label(), and parse::lexer::string.
Member Data Documentation
effects_group_rule anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group
parse::detail::effects_group_rule anonymous_namespace{Parse.cpp}::effects_group_rules::start
The documentation for this struct was generated from the following file:
Parse.cpp