FreeOrion: anonymous_namespace{AlignmentsParser.cpp}::rules Struct Reference
anonymous_namespace{AlignmentsParser.cpp}::rules Struct Reference
Public Types
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::vector< Alignment > &), qi::locals< std::string, std::string >, parse::skipper_type > alignment_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::vector< Alignment > &), parse::skipper_type > start_rule
Public Member Functions
rules ()
Public Attributes
alignment_rule alignment
start_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<Alignment>&), qi::locals< std::string, std::string >, parse::skipper_type > anonymous_namespace{AlignmentsParser.cpp}::rules::alignment_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<Alignment>&), parse::skipper_type > anonymous_namespace{AlignmentsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{AlignmentsParser.cpp}::rules::rules () inline
References parse::detail::effects_group_parser(), parse::lexer::instance(), parse::label(), parse::report_error, and parse::lexer::string.
Member Data Documentation
alignment_rule anonymous_namespace{AlignmentsParser.cpp}::rules::alignment
start_rule anonymous_namespace{AlignmentsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
AlignmentsParser.cpp