FreeOrion: Condition::EmpireStockpileValue Struct Reference
Condition::EmpireStockpileValue Struct Reference
#include <Condition.h>
Public Member Functions
EmpireStockpileValue (ResourceType stockpile, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
virtual ~EmpireStockpileValue ()
std::string Description (bool negated=false) const override
std::string Dump () const override
void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const override
bool operator== (const ConditionBase &rhs) const override
bool RootCandidateInvariant () const override
void SetTopLevelContent (const std::string &content_name) override
bool SourceInvariant () const override
bool TargetInvariant () const override
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, std::shared_ptr< const UniverseObject > candidate) const
bool Eval (std::shared_ptr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
bool Match (const ScriptingContext &local_context) const override
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase< double > * m_high
ValueRef::ValueRefBase< double > * m_low
ResourceType m_stockpile
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects whose owner's stockpile of stockpile is between low and high, inclusive.
Constructor & Destructor Documentation
Condition::EmpireStockpileValue::EmpireStockpileValue (ResourceType stockpile, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Condition::EmpireStockpileValue::~EmpireStockpileValue () virtual
Member Function Documentation
std::string Condition::EmpireStockpileValue::Description (bool negated = false) const override virtual
Implements Condition::ConditionBase.
References FlexibleFormat(), and UserString().
std::string Condition::EmpireStockpileValue::Dump () const override virtual
Implements Condition::ConditionBase.
References DumpIndent().
void Condition::EmpireStockpileValue::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const override virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), and Condition::FocusType::RootCandidateInvariant().
bool Condition::EmpireStockpileValue::Match (const ScriptingContext & local_context) const override private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, and ErrorLogger.
bool Condition::EmpireStockpileValue::operator== (const ConditionBase & rhs) const override virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_stockpile.
bool Condition::EmpireStockpileValue::RootCandidateInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
template<class Archive > void Condition::EmpireStockpileValue::serialize (Archive & ar, const unsigned int version) private
References m_high, and m_low.
void Condition::EmpireStockpileValue::SetTopLevelContent (const std::string & content_name) override virtual
Implements Condition::ConditionBase.
bool Condition::EmpireStockpileValue::SourceInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
bool Condition::EmpireStockpileValue::TargetInvariant () const override virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<double>* Condition::EmpireStockpileValue::m_high private
Referenced by serialize().
ValueRef::ValueRefBase<double>* Condition::EmpireStockpileValue::m_low private
Referenced by serialize().
ResourceType Condition::EmpireStockpileValue::m_stockpile private
Referenced by operator==().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp