FreeOrion: parse::double_complex_parser_rules Struct Reference
parse::double_complex_parser_rules Struct Reference
Public Member Functions
double_complex_parser_rules ()
Public Attributes
complex_variable_rule< double > direct_distance
complex_variable_rule< double > empire_meter_value
complex_variable_rule< double > part_capacity
complex_variable_rule< double > shortest_path
complex_variable_rule< double > species_empire_opinion
complex_variable_rule< double > species_species_opinion
complex_variable_rule< double > start
Constructor & Destructor Documentation
parse::double_complex_parser_rules::double_complex_parser_rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, direct_distance, empire_meter_value, parse::lexer::instance(), int_simple(), parse::detail::label(), part_capacity, shortest_path, species_empire_opinion, species_species_opinion, start, parse::lexer::string, and parse::string_value_ref().
Member Data Documentation
complex_variable_rule<double> parse::double_complex_parser_rules::direct_distance
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::empire_meter_value
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::part_capacity
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::shortest_path
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::species_empire_opinion
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::species_species_opinion
Referenced by double_complex_parser_rules().
complex_variable_rule<double> parse::double_complex_parser_rules::start
Referenced by double_complex_parser_rules(), and double_var_complex().
The documentation for this struct was generated from the following file:
DoubleComplexValueRefParser.cpp