FreeOrion: anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4 Struct Reference
anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< std::string,
ValueRef::ValueRefBase< int >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< double >
* >, parse::skipper_type > empire_meter_value_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Condition::ConditionBase
*(), qi::locals< MeterType,
ValueRef::ValueRefBase< double >
*, ValueRef::ValueRefBase
< double > *, std::string,
ValueRef::ValueRefBase
< std::string >
* >, parse::skipper_type > meter_value_rule
Public Member Functions
condition_parser_rules_4 ()
Public Attributes
empire_meter_value_rule empire_meter_value
empire_meter_value_rule empire_meter_value1
empire_meter_value_rule empire_meter_value2
meter_value_rule meter_value
meter_value_rule ship_part_meter_value
parse::condition_parser_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals< std::string, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>* >, parse::skipper_type > anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::empire_meter_value_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Condition::ConditionBase* (), qi::locals< MeterType, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>*, std::string, ValueRef::ValueRefBase<std::string>* >, parse::skipper_type > anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::meter_value_rule
Constructor & Destructor Documentation
anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4 () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), parse::label(), parse::non_ship_part_meter_type_enum(), parse::ship_part_meter_type_enum(), parse::lexer::string, parse::value_ref_parser< double >(), and parse::value_ref_parser< int >().
Member Data Documentation
empire_meter_value_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::empire_meter_value
empire_meter_value_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::empire_meter_value1
empire_meter_value_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::empire_meter_value2
meter_value_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::meter_value
meter_value_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::ship_part_meter_value
parse::condition_parser_rule anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::start
The documentation for this struct was generated from the following file:
ConditionParser4.cpp