FreeOrion: anonymous_namespace{ShipHullsParser.cpp}::rules Struct Reference
anonymous_namespace{ShipHullsParser.cpp}::rules Struct Reference
Public Types
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::map< std::string, HullType * > &), qi::locals< MoreCommonParams, std::string, HullTypeStats, CommonParams, std::vector< HullType::Slot >, std::string >, parse::skipper_type > hull_rule
typedef boost::spirit::qi::rule< parse::token_iterator, HullTypeStats(), qi::locals< double, double, double, double >, parse::skipper_type > hull_stats_rule
typedef boost::spirit::qi::rule< parse::token_iterator, HullType::Slot(), qi::locals< ShipSlotType, double, double >, parse::skipper_type > slot_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::vector< HullType::Slot > &), parse::skipper_type > slots_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void(std::map< std::string, HullType * > &), parse::skipper_type > start_rule
Public Member Functions
rules ()
Public Attributes
hull_rule hull
hull_stats_rule hull_stats
slot_rule slot
slots_rule slots
start_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, HullType*>&), qi::locals< MoreCommonParams, std::string, HullTypeStats, CommonParams, std::vector<HullType::Slot>, std::string >, parse::skipper_type > anonymous_namespace{ShipHullsParser.cpp}::rules::hull_rule
typedef boost::spirit::qi::rule< parse::token_iterator, HullTypeStats (), qi::locals< double, double, double, double >, parse::skipper_type > anonymous_namespace{ShipHullsParser.cpp}::rules::hull_stats_rule
typedef boost::spirit::qi::rule< parse::token_iterator, HullType::Slot (), qi::locals< ShipSlotType, double, double >, parse::skipper_type > anonymous_namespace{ShipHullsParser.cpp}::rules::slot_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<HullType::Slot>&), parse::skipper_type > anonymous_namespace{ShipHullsParser.cpp}::rules::slots_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, HullType*>&), parse::skipper_type > anonymous_namespace{ShipHullsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{ShipHullsParser.cpp}::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::common_params_parser(), parse::double_, anonymous_namespace{BuildingsParser.cpp}::insert, anonymous_namespace{ShipHullsParser.cpp}::insert_hull, parse::lexer::instance(), parse::label(), parse::detail::more_common_params_parser(), parse::report_error, parse::ship_slot_type_enum(), and parse::lexer::string.
Member Data Documentation
hull_rule anonymous_namespace{ShipHullsParser.cpp}::rules::hull
hull_stats_rule anonymous_namespace{ShipHullsParser.cpp}::rules::hull_stats
slot_rule anonymous_namespace{ShipHullsParser.cpp}::rules::slot
slots_rule anonymous_namespace{ShipHullsParser.cpp}::rules::slots
start_rule anonymous_namespace{ShipHullsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
ShipHullsParser.cpp