FreeOrion: anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache Struct Reference
anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache Struct Reference
Public Member Functions
std::pair< bool,
Effect::TargetSet > * Find (const Condition::ConditionBase *cond, bool insert)
void LockShared (boost::shared_lock< boost::shared_mutex > &guard)
void MarkComplete (std::pair< bool, Effect::TargetSet > *cache_entry)
Private Attributes
std::map< const
Condition::ConditionBase
*, std::pair< bool,
Effect::TargetSet > > m_entries
boost::shared_mutex m_mutex
boost::condition_variable_any m_state_changed
Member Function Documentation
std::pair< bool, Effect::TargetSet > * anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::Find (const Condition::ConditionBase * cond, bool insert)
References m_entries, m_mutex, and m_state_changed.
Referenced by anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GetConditionMatches().
void anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::LockShared (boost::shared_lock< boost::shared_mutex > & guard)
Referenced by anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator()().
void anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::MarkComplete (std::pair< bool, Effect::TargetSet > * cache_entry)
Referenced by anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GetConditionMatches().
Member Data Documentation
std::map<const Condition::ConditionBase*, std::pair<bool, Effect::TargetSet> > anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::m_entries private
Referenced by Find().
boost::shared_mutex anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::m_mutex private
Referenced by Find().
boost::condition_variable_any anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::m_state_changed private
Referenced by Find().
The documentation for this struct was generated from the following file:
Universe.cpp