FreeOrion: Version.cpp File Reference
Version.cpp File Reference
Implement a free function to access the application version.
#include "util/Version.h"
Namespaces
anonymous_namespace{Version.cpp}
Functions
const std::string & FreeOrionVersionString ()
Returns the version string of FreeOrion.
Variables
static const std::string anonymous_namespace{Version.cpp}::retval = "v0.4.6+ HEAD [build 2016-12-16.aaa01b8] CMake"
Detailed Description
Implement a free function to access the application version.
Warning
DON'T EDIT MANUALLY Version.cpp. Version.cpp is generated from Version.cpp.in by the cmake/make_versioncpp.py utility script that is used or should be used by all build systems.
Function Documentation
const std::string& FreeOrionVersionString ()
Returns the version string of FreeOrion.
The version strings consists of:
the VERSION number composed from MAJOR.MINOR.PATCH numbers. An optional '+' suffix indicates an in between test releases (think 0.4.6 + some more). Release candidates are suffixed with rcNUMBER.
the BRANCH, which represents the Git branch used to create this build.
the DATE as ISO 8601 date format.
the SHORT_COMMIT_HASH, which is the shortes Git commit hash, which identifies the commit this build was created from.
the BUILD_SYSTEM, which can be one of "CMake", "MSVC" or "XCode".
Returns
The version string with the format VERSION BRANCH_NAME [build DATE.SHORT_COMMIT_HASH] BUILD_SYSTEM
References anonymous_namespace{Version.cpp}::retval.
Referenced by PlayerConnection::ClientVersionStringMatchesThisServer(), HostMPGameMessage(), HostSPGameMessage(), if(), InitLogger(), IntroScreen::IntroScreen(), JoinGameMessage(), main(), mainConfigOptionsSetup(), mainSetupAndRun(), and SaveGamePreviewData::serialize().