FreeOrion: anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1 Struct Reference
anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1 Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals< std::string,
std::string, std::vector
< std::pair< std::string,
ValueRef::ValueRefBase
< std::string >
* > >, EmpireAffiliationType,
std::string, bool >
, parse::skipper_type > generate_sitrep_message_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals< std::string,
ValueRef::ValueRefBase< int >
*, ValueRef::ValueRefBase
< int >
*, ValueRef::ValueRefBase
< std::string >
* >, parse::skipper_type > string_and_intref_and_intref_rule
typedef std::pair< std::string,
ValueRef::ValueRefBase
< std::string > * > string_and_string_ref_pair
typedef
boost::spirit::qi::rule
< parse::token_iterator,
string_and_string_ref_pair(),
qi::locals< std::string >
, parse::skipper_type > string_and_string_ref_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
std::vector
< string_and_string_ref_pair >
), parse::skipper_type > string_and_string_ref_vector_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator,
Effect::EffectBase
*(), qi::locals
< ValueRef::ValueRefBase
< std::string >
*, ValueRef::ValueRefBase
< double >
*, ValueRef::ValueRefBase
< double >
* >, parse::skipper_type > stringref_and_doubleref_rule
Public Member Functions
effect_parser_rules_1 ()
Public Attributes
generate_sitrep_message_rule generate_sitrep_message
string_and_intref_and_intref_rule give_empire_tech
string_and_intref_and_intref_rule set_empire_meter_1
string_and_intref_and_intref_rule set_empire_meter_2
stringref_and_doubleref_rule set_empire_tech_progress
string_and_intref_and_intref_rule set_overlay_texture
parse::effect_parser_rule start
string_and_string_ref_rule string_and_string_ref
string_and_string_ref_vector_rule string_and_string_ref_vector
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< std::string, std::string, std::vector<std::pair<std::string, ValueRef::ValueRefBase<std::string>*> >, EmpireAffiliationType, std::string, bool >, parse::skipper_type > anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::generate_sitrep_message_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< std::string, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<int>*, ValueRef::ValueRefBase<std::string>* >, parse::skipper_type > anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_intref_and_intref_rule
typedef std::pair<std::string, ValueRef::ValueRefBase<std::string>*> anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_string_ref_pair
typedef boost::spirit::qi::rule< parse::token_iterator, string_and_string_ref_pair (), qi::locals<std::string>, parse::skipper_type > anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_string_ref_rule
typedef boost::spirit::qi::rule< parse::token_iterator, std::vector<string_and_string_ref_pair>), parse::skipper_type > anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_string_ref_vector_rule
typedef boost::spirit::qi::rule< parse::token_iterator, Effect::EffectBase* (), qi::locals< ValueRef::ValueRefBase<std::string>*, ValueRef::ValueRefBase<double>*, ValueRef::ValueRefBase<double>* >, parse::skipper_type > anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::stringref_and_doubleref_rule
Constructor & Destructor Documentation
anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1 () inline
References anonymous_namespace{EnumParser.cpp}::_1, anonymous_namespace{EnumParser.cpp}::_val, AFFIL_ANY, AFFIL_CAN_SEE, AFFIL_HUMAN, AFFIL_SELF, parse::detail::condition_parser, parse::enum_parser< EmpireAffiliationType >(), parse::lexer::instance(), parse::label(), parse::lexer::string, parse::value_ref_parser< double >(), and parse::value_ref_parser< int >().
Member Data Documentation
generate_sitrep_message_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::generate_sitrep_message
string_and_intref_and_intref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::give_empire_tech
string_and_intref_and_intref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::set_empire_meter_1
string_and_intref_and_intref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::set_empire_meter_2
stringref_and_doubleref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::set_empire_tech_progress
string_and_intref_and_intref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::set_overlay_texture
parse::effect_parser_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::start
string_and_string_ref_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_string_ref
string_and_string_ref_vector_rule anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::string_and_string_ref_vector
The documentation for this struct was generated from the following file:
EffectParser1.cpp