FreeOrion: ColorSelector Class Reference
ColorSelector Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
ColorSelector (GG::Clr color, GG::Clr default_color)
virtual ~ColorSelector ()
Mutators
virtual void Render ()
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Public Attributes
boost::signals2::signal< void(const
GG::Clr &)> ColorChangedSignal
Private Member Functions
virtual void InitBuffer ()
Private Attributes
GG::GL2DVertexBuffer m_border_buffer
GG::Clr m_default_color
Detailed Description
A control used to pick arbitrary colors using GG::ColorDlg.
Constructor & Destructor Documentation
ColorSelector::ColorSelector (GG::Clr color, GG::Clr default_color)
ColorSelector::~ColorSelector () virtual
References m_border_buffer.
Member Function Documentation
void ColorSelector::InitBuffer () private virtual
References m_border_buffer.
Referenced by SizeMove().
void ColorSelector::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
References ColorChangedSignal, ClientUI::CtrlBorderColor(), ClientUI::CtrlColor(), ClientUI::GetFont(), and ClientUI::TextColor().
void ColorSelector::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
References ColorChangedSignal, ClientUI::EditHiliteColor(), ClientUI::GetFont(), m_default_color, ClientUI::TextColor(), UserString(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void ColorSelector::Render () virtual
References m_border_buffer.
void ColorSelector::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
References InitBuffer().
Member Data Documentation
boost::signals2::signal<void (const GG::Clr&)> ColorSelector::ColorChangedSignal mutable
Referenced by OptionsWnd::ColorOption(), LClick(), and RClick().
GG::GL2DVertexBuffer ColorSelector::m_border_buffer private
Referenced by InitBuffer(), Render(), and ~ColorSelector().
GG::Clr ColorSelector::m_default_color private
Referenced by RClick().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp