FreeOrion: MarkupBox Class Reference
MarkupBox Class Reference
#include <MarkupBox.h>
Classes
class MarkupSurface
Public Member Functions
Structors
MarkupBox (GG::X x, GG::Y y, GG::X w, GG::Y h, const std::string &str, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE)
MarkupBox ()
default ctor
virtual ~MarkupBox ()
dtor
Accessors
const std::string & Text () const
Mutators
virtual void Render ()
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
virtual void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys)
virtual void KeyPress (GG::Key key, boost::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys)
virtual void SetText (const std::string &str)
void Clear ()
void Refresh ()
Private Member Functions
void AdjustScrolls ()
sets the sizes of the scroll-space and the screen-space of the scrolls
void VScrolled (int upper, int ignored1, int ignored2, int ignored3)
Private Attributes
MarkupSurface * m_surface
all contents are attached as children of surface so that scrolling only needs to update the surface position to move all contents
GG::Y m_surface_top
position, relative to top of MarkupBox where MarkupSurface is located. Used to keep track of scrolling position.
std::vector< MarkupTextBlock > m_text_blocks
result of parsing raw text. each entry can be rendered as a single GG::Control
GG::Scroll * m_vscroll
scrollbar used to scroll through marked up text
Detailed Description
A control similar to GG::MultiEdit that displayed text, links, and images with layout determined from HTML-like markup in the provided text.
Constructor & Destructor Documentation
MarkupBox::MarkupBox (GG::X x, GG::Y y, GG::X w, GG::Y h, const std::string & str, GG::Flags< GG::WndFlag > flags = GG::INTERACTIVE)
Ctor.
References AdjustScrolls(), anonymous_namespace{MarkupBox.cpp}::EDGE_PAD(), m_surface, Refresh(), anonymous_namespace{MarkupBox.cpp}::RegisterMarkupTags(), and VScrolled().
MarkupBox::MarkupBox ()
default ctor
References m_surface, Refresh(), anonymous_namespace{MarkupBox.cpp}::RegisterMarkupTags(), and VScrolled().
MarkupBox::~MarkupBox () virtual
dtor
References m_vscroll.
Member Function Documentation
void MarkupBox::AdjustScrolls () private
sets the sizes of the scroll-space and the screen-space of the scrolls
References ClientUI::GetFont(), m_surface, m_vscroll, MarkupBox::MarkupSurface::Refresh(), anonymous_namespace{MarkupBox.cpp}::SCROLL_WIDTH(), ClientUI::TextColor(), and VScrolled().
Referenced by MarkupBox(), and SetText().
void MarkupBox::Clear ()
References MarkupBox::MarkupSurface::Clear(), m_surface, and VScrolled().
Referenced by MarkupBox::MarkupSurface::SetText(), and MarkupBox::MarkupSurface::~MarkupSurface().
void MarkupBox::KeyPress (GG::Key key, boost::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) virtual
References m_surface, and m_vscroll.
void MarkupBox::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) virtual
References m_vscroll.
void MarkupBox::Refresh ()
References m_surface, and MarkupBox::MarkupSurface::Refresh().
Referenced by MarkupBox(), MarkupBox::MarkupSurface::SetText(), and SizeMove().
void MarkupBox::Render () virtual
References ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void MarkupBox::SetText (const std::string & str) virtual
References AdjustScrolls(), m_surface, and MarkupBox::MarkupSurface::SetText().
void MarkupBox::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
References anonymous_namespace{MarkupBox.cpp}::EDGE_PAD(), m_surface, m_vscroll, Refresh(), and anonymous_namespace{MarkupBox.cpp}::SCROLL_WIDTH().
const std::string & MarkupBox::Text () const
References anonymous_namespace{MarkupBox.cpp}::EMPTY_STRING(), m_surface, and MarkupBox::MarkupSurface::Text().
void MarkupBox::VScrolled (int upper, int ignored1, int ignored2, int ignored3) private
References m_surface.
Referenced by AdjustScrolls(), Clear(), and MarkupBox().
Member Data Documentation
MarkupSurface* MarkupBox::m_surface private
all contents are attached as children of surface so that scrolling only needs to update the surface position to move all contents
Referenced by AdjustScrolls(), Clear(), KeyPress(), MarkupBox(), Refresh(), SetText(), SizeMove(), Text(), and VScrolled().
GG::Y MarkupBox::m_surface_top private
position, relative to top of MarkupBox where MarkupSurface is located. Used to keep track of scrolling position.
std::vector<MarkupTextBlock> MarkupBox::m_text_blocks private
result of parsing raw text. each entry can be rendered as a single GG::Control
GG::Scroll* MarkupBox::m_vscroll private
scrollbar used to scroll through marked up text
Referenced by AdjustScrolls(), KeyPress(), MouseWheel(), SizeMove(), and ~MarkupBox().
The documentation for this class was generated from the following files:
MarkupBox.h
MarkupBox.cpp