FreeOrion: Effect::SetStarType Class Reference
Effect::SetStarType Class Reference
#include <Effect.h>
Public Member Functions
SetStarType (ValueRef::ValueRefBase< StarType > *type)
virtual ~SetStarType ()
virtual std::string Description () const
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase
< StarType > * m_type
Friends
class boost::serialization::access
Detailed Description
Sets the star type of the target to type. This has no effect on non-System targets.
Constructor & Destructor Documentation
Effect::SetStarType::SetStarType (ValueRef::ValueRefBase< StarType > * type) explicit
Effect::SetStarType::~SetStarType () virtual
References m_type.
Member Function Documentation
std::string Effect::SetStarType::Description () const virtual
Implements Effect::EffectBase.
References ValueRef::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), m_type, and UserString().
std::string Effect::SetStarType::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_type.
void Effect::SetStarType::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References ScriptingContext::effect_target, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), and m_type.
template<class Archive > void Effect::SetStarType::serialize (Archive & ar, const unsigned int version) private
References m_type.
void Effect::SetStarType::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_type, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<StarType>* Effect::SetStarType::m_type private
Referenced by Description(), Dump(), Execute(), serialize(), SetTopLevelContent(), and ~SetStarType().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp