FreeOrion: SidePanel.h File Reference
SidePanel.h File Reference
#include "CUIControls.h"
#include "CUIWnd.h"
#include "../universe/ResourceCenter.h"
#include "../universe/Planet.h"
#include "../universe/System.h"
#include <GG/DynamicGraphic.h>
#include <GG/SignalsAndSlots.h>
#include <GG/Texture.h>
#include <vector>
Classes
class SidePanel
Functions
int AutomaticallyChosenColonyShip (int target_planet_id)
TemporaryPtr< const Ship > ValidSelectedColonyShip (int system_id)
Function Documentation
int AutomaticallyChosenColonyShip (int target_planet_id)
References ALL_EMPIRES, anonymous_namespace{SidePanel.cpp}::AvailableToColonize(), anonymous_namespace{SidePanel.cpp}::CanColonizePlanetType(), anonymous_namespace{SidePanel.cpp}::colony_projections, ShipDesign::ColonyCapacity(), Planet::CurrentMeterValue(), Ship::Design(), ClientApp::EmpireID(), ObjectMap::FindObjects(), HumanClientApp::GetApp(), Planet::GetMeter(), GetPlanet(), Species::GetPlanetEnvironment(), GetSpecies(), GetSystem(), GetUniverse(), UniverseObject::ID(), Universe::InhibitUniverseObjectSignals(), Meter::Initial(), INVALID_OBJECT_ID, METER_POPULATION, METER_TARGET_POPULATION, Objects(), UniverseObject::OwnedBy(), UniverseObject::Owner(), Meter::Set(), UniverseObject::SetOwner(), PopCenter::SetSpecies(), System::ShipIDs(), parse::species(), anonymous_namespace{SidePanel.cpp}::species_colony_projections, PopCenter::SpeciesName(), Ship::SpeciesName(), UniverseObject::SystemID(), Planet::Type(), UniverseObject::Unowned(), and Universe::UpdateMeterEstimates().
Referenced by SidePanel::PlanetPanel::ClickColonize(), and SidePanel::PlanetPanel::Refresh().
TemporaryPtr<const Ship> ValidSelectedColonyShip (int system_id)
References AIInterface::EmpireID(), HumanClientApp::GetApp(), GetShip(), and INVALID_OBJECT_ID.
Referenced by SidePanel::PlanetPanel::ClickColonize(), and SidePanel::PlanetPanel::Refresh().