FreeOrion: anonymous_namespace{Condition.cpp} Namespace Reference
anonymous_namespace{Condition.cpp} Namespace Reference
Classes
struct BuildingSimpleMatch
struct CanAddStarlaneConnectionSimpleMatch
struct ChanceSimpleMatch
struct ContainedBySimpleMatch
struct ContainsSimpleMatch
struct CreatedOnTurnSimpleMatch
struct DesignHasHullSimpleMatch
struct DesignHasPartClassSimpleMatch
struct DesignHasPartSimpleMatch
struct EmpireAffiliationSimpleMatch
struct EmpireMeterValueSimpleMatch
struct EmpireStockpileValueSimpleMatch
struct EnqueuedSimpleMatch
struct ExploredByEmpireSimpleMatch
struct FleetSupplyableSimpleMatch
struct FocusTypeSimpleMatch
struct HasSpecialSimpleMatch
struct HasTagSimpleMatch
struct HomeworldSimpleMatch
struct InSystemSimpleMatch
struct MeterValueSimpleMatch
struct NumberedShipDesignSimpleMatch
struct ObjectIDSimpleMatch
struct OrderedBombardedSimpleMatch
struct OwnerHasBuildingTypeAvailableSimpleMatch
struct OwnerHasShipDesignAvailableSimpleMatch
struct OwnerHasTechSimpleMatch
struct PlanetEnvironmentSimpleMatch
struct PlanetSizeSimpleMatch
struct PlanetTypeSimpleMatch
struct PredefinedShipDesignSimpleMatch
struct ProducedByEmpireSimpleMatch
struct ResourceSupplySimpleMatch
struct ShipPartMeterValueSimpleMatch
struct SpeciesSimpleMatch
struct StarTypeSimpleMatch
struct TypeSimpleMatch
struct VisibleToEmpireSimpleMatch
struct WithinDistanceSimpleMatch
struct WithinStarlaneJumpsSimpleMatch
Functions
void AddAllObjectsSet (Condition::ObjectSet &condition_non_targets)
void AddBuildingSet (Condition::ObjectSet &condition_non_targets)
void AddFieldSet (Condition::ObjectSet &condition_non_targets)
void AddFleetSet (Condition::ObjectSet &condition_non_targets)
void AddPlanetSet (Condition::ObjectSet &condition_non_targets)
void AddPopCenterSet (Condition::ObjectSet &condition_non_targets)
void AddResCenterSet (Condition::ObjectSet &condition_non_targets)
void AddShipSet (Condition::ObjectSet &condition_non_targets)
void AddSystemSet (Condition::ObjectSet &condition_non_targets)
std::string CompareTypeString (Condition::ComparisonType comp)
bool Comparison (float val1, Condition::ComparisonType comp, float val2)
std::map< std::string, bool > ConditionDescriptionAndTest (const std::vector< Condition::ConditionBase * > &conditions, const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate_object)
float CrossProduct (float dx1, float dy1, float dx2, float dy2)
int CustomRandInt (int max_plus_one)
template<class Pred >
void EvalImpl (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, Condition::SearchDomain search_domain, const Pred &pred)
std::vector
< Condition::ConditionBase * > FlattenAndNestedConditions (const std::vector< Condition::ConditionBase * > &input_conditions)
TemporaryPtr< const Fleet > FleetFromObject (TemporaryPtr< const UniverseObject > obj)
const Condition::ConditionBase * GetLocationCondition (Condition::ContentType content_type, const std::string &name1, const std::string &name2)
bool LaneCrossesExistingLane (TemporaryPtr< const System > lane_end_sys1, TemporaryPtr< const System > lane_end_sys2)
bool LanesAngularlyTooClose (TemporaryPtr< const UniverseObject > sys1, TemporaryPtr< const UniverseObject > lane1_sys2, TemporaryPtr< const UniverseObject > lane2_sys2)
bool LanesCross (TemporaryPtr< const System > lane1_end_sys1, TemporaryPtr< const System > lane1_end_sys2, TemporaryPtr< const System > lane2_end_sys1, TemporaryPtr< const System > lane2_end_sys2)
bool LaneTooCloseToOtherSystem (TemporaryPtr< const System > lane_end_sys1, TemporaryPtr< const System > lane_end_sys2)
std::string MeterTypeDumpString (MeterType meter)
int NumberOnQueue (const ProductionQueue &queue, BuildType build_type, const int location_id, const std::string &name="", int design_id=ShipDesign::INVALID_DESIGN_ID)
bool ObjectTooCloseToLane (TemporaryPtr< const UniverseObject > lane_end_sys1, TemporaryPtr< const UniverseObject > lane_end_sys2, TemporaryPtr< const UniverseObject > obj)
void TransferRandomObjects (unsigned int number, Condition::ObjectSet &from_set, Condition::ObjectSet &to_set)
void TransferSortedObjects (unsigned int number, ValueRef::ValueRefBase< double > *sort_key, const ScriptingContext &context, Condition::SortingMethod sorting_method, Condition::ObjectSet &from_set, Condition::ObjectSet &to_set)
Variables
int(* CRI)(int) = CustomRandInt
Function Documentation
void anonymous_namespace{Condition.cpp}::AddAllObjectsSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingObjects(), and Objects().
void anonymous_namespace{Condition.cpp}::AddBuildingSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingBuildings(), and Objects().
void anonymous_namespace{Condition.cpp}::AddFieldSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingFields(), and Objects().
void anonymous_namespace{Condition.cpp}::AddFleetSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingFleets(), and Objects().
void anonymous_namespace{Condition.cpp}::AddPlanetSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingPlanets(), and Objects().
void anonymous_namespace{Condition.cpp}::AddPopCenterSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingPopCenters(), and Objects().
void anonymous_namespace{Condition.cpp}::AddResCenterSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingResourceCenters(), and Objects().
void anonymous_namespace{Condition.cpp}::AddShipSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingShips(), and Objects().
void anonymous_namespace{Condition.cpp}::AddSystemSet (Condition::ObjectSet & condition_non_targets)
References anonymous_namespace{EnumParser.cpp}::_1, ObjectMap::NumExistingSystems(), and Objects().
std::string anonymous_namespace{Condition.cpp}::CompareTypeString (Condition::ComparisonType comp)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
bool anonymous_namespace{Condition.cpp}::Comparison (float val1, Condition::ComparisonType comp, float val2)
References Condition::EQUAL, Condition::GREATER_THAN, Condition::GREATER_THAN_OR_EQUAL, Condition::INVALID_COMPARISON, Condition::LESS_THAN, Condition::LESS_THAN_OR_EQUAL, and Condition::NOT_EQUAL.
std::map<std::string, bool> anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest (const std::vector< Condition::ConditionBase * > & conditions, const ScriptingContext & parent_context, TemporaryPtr< const UniverseObject > candidate_object)
References Condition::And(), Condition::ConditionBase(), and FlattenAndNestedConditions().
Referenced by ConditionDescription(), and ConditionFailedDescription().
float anonymous_namespace{Condition.cpp}::CrossProduct (float dx1, float dy1, float dx2, float dy2) inline
Referenced by LanesCross().
int anonymous_namespace{Condition.cpp}::CustomRandInt (int max_plus_one)
Random number genrator function to use with random_shuffle
References RandSmallInt().
template<class Pred > void anonymous_namespace{Condition.cpp}::EvalImpl (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, Condition::SearchDomain search_domain, const Pred & pred)
Used by 4-parameter ConditionBase::Eval function, and some of its overrides, to scan through matches or non_matches set and apply pred to each object, to test if it should remain in its current set or be transferred from the search_domain specified set into the other.
References Condition::MATCHES, and Condition::NON_MATCHES.
std::vector<Condition::ConditionBase*> anonymous_namespace{Condition.cpp}::FlattenAndNestedConditions (const std::vector< Condition::ConditionBase * > & input_conditions)
References Condition::And().
Referenced by ConditionDescriptionAndTest().
TemporaryPtr<const Fleet> anonymous_namespace{Condition.cpp}::FleetFromObject (TemporaryPtr< const UniverseObject > obj)
Attempts to cast obj to a Fleet pointer. If that fails, attempts to cast obj to a Ship pointer, and then get the Fleet of the ship. If both fail then returns a null object Fleet pointer.
References boost::dynamic_pointer_cast(), and GetFleet().
const Condition::ConditionBase* anonymous_namespace{Condition.cpp}::GetLocationCondition (Condition::ContentType content_type, const std::string & name1, const std::string & name2)
References Condition::CONTENT_BUILDING, Condition::CONTENT_FOCUS, Condition::CONTENT_SHIP_HULL, Condition::CONTENT_SHIP_PART, Condition::CONTENT_SPECIAL, Condition::CONTENT_SPECIES, GetBuildingType(), GetHullType(), GetPartType(), GetSpecial(), GetSpecies(), FocusType::Location(), Species::Location(), and FocusType::Name().
bool anonymous_namespace{Condition.cpp}::LaneCrossesExistingLane (TemporaryPtr< const System > lane_end_sys1, TemporaryPtr< const System > lane_end_sys2)
References ObjectMap::FindObjects(), GetSystem(), LanesCross(), Objects(), and System::StarlanesWormholes().
Referenced by anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
bool anonymous_namespace{Condition.cpp}::LanesAngularlyTooClose (TemporaryPtr< const UniverseObject > sys1, TemporaryPtr< const UniverseObject > lane1_sys2, TemporaryPtr< const UniverseObject > lane2_sys2)
References UniverseObject::X(), and UniverseObject::Y().
Referenced by anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
bool anonymous_namespace{Condition.cpp}::LanesCross (TemporaryPtr< const System > lane1_end_sys1, TemporaryPtr< const System > lane1_end_sys2, TemporaryPtr< const System > lane2_end_sys1, TemporaryPtr< const System > lane2_end_sys2)
References CrossProduct(), UniverseObject::X(), and UniverseObject::Y().
Referenced by LaneCrossesExistingLane().
bool anonymous_namespace{Condition.cpp}::LaneTooCloseToOtherSystem (TemporaryPtr< const System > lane_end_sys1, TemporaryPtr< const System > lane_end_sys2)
References ObjectMap::FindObjects(), Objects(), and ObjectTooCloseToLane().
Referenced by anonymous_namespace{Condition.cpp}::CanAddStarlaneConnectionSimpleMatch::operator()().
std::string anonymous_namespace{Condition.cpp}::MeterTypeDumpString (MeterType meter)
References INVALID_METER_TYPE, METER_CAPACITY, METER_CONSTRUCTION, METER_DEFENSE, METER_DETECTION, METER_FUEL, METER_INDUSTRY, METER_MAX_DEFENSE, METER_MAX_FUEL, METER_MAX_SHIELD, METER_MAX_STRUCTURE, METER_POPULATION, METER_RESEARCH, METER_SHIELD, METER_SPEED, METER_STEALTH, METER_STRUCTURE, METER_SUPPLY, METER_TARGET_CONSTRUCTION, METER_TARGET_INDUSTRY, METER_TARGET_POPULATION, METER_TARGET_RESEARCH, METER_TARGET_TRADE, and METER_TRADE.
int anonymous_namespace{Condition.cpp}::NumberOnQueue (const ProductionQueue & queue, BuildType build_type, const int location_id, const std::string & name = "", int design_id = ShipDesign::INVALID_DESIGN_ID)
References ProductionQueue::begin(), BT_BUILDING, BT_SHIP, ProductionQueue::end(), GetShipDesign(), INVALID_BUILD_TYPE, ShipDesign::INVALID_DESIGN_ID, and ShipDesign::Name().
Referenced by anonymous_namespace{Condition.cpp}::EnqueuedSimpleMatch::operator()().
bool anonymous_namespace{Condition.cpp}::ObjectTooCloseToLane (TemporaryPtr< const UniverseObject > lane_end_sys1, TemporaryPtr< const UniverseObject > lane_end_sys2, TemporaryPtr< const UniverseObject > obj)
References UniverseObject::X(), and UniverseObject::Y().
Referenced by LaneTooCloseToOtherSystem().
void anonymous_namespace{Condition.cpp}::TransferRandomObjects (unsigned int number, Condition::ObjectSet & from_set, Condition::ObjectSet & to_set)
Transfers the indicated number of objects, randomly selected from from_set to to_set
References CRI.
Referenced by TransferSortedObjects().
void anonymous_namespace{Condition.cpp}::TransferSortedObjects (unsigned int number, ValueRef::ValueRefBase< double > * sort_key, const ScriptingContext & context, Condition::SortingMethod sorting_method, Condition::ObjectSet & from_set, Condition::ObjectSet & to_set)
Transfers the indicated number of objects, selected from from_set into to_set. The objects transferred are selected based on the value of sort_key evaluated on them, with the largest / smallest / most common sort keys chosen, or a random selection chosen, depending on the specified sorting_method
References DebugLogger, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Condition::SORT_MAX, Condition::SORT_MIN, Condition::SORT_MODE, Condition::SORT_RANDOM, and TransferRandomObjects().
Variable Documentation
int(* anonymous_namespace{Condition.cpp}::CRI)(int) = CustomRandInt
Referenced by TransferRandomObjects().