FreeOrion: AIFramework.cpp File Reference
AIFramework.cpp File Reference
#include "AIFramework.h"
#include "../../universe/Building.h"
#include "../../universe/Universe.h"
#include "../../util/Directories.h"
#include "../../util/Logger.h"
#include "../../util/i18n.h"
#include "../../util/MultiplayerCommon.h"
#include "../../util/OptionsDB.h"
#include "../../Empire/Empire.h"
#include "../../Empire/EmpireManager.h"
#include "../../Empire/Diplomacy.h"
#include "../CommonFramework.h"
#include "../SetWrapper.h"
#include "../CommonWrappers.h"
#include "AIWrapper.h"
#include <boost/python.hpp>
#include <boost/python/suite/indexing/vector_indexing_suite.hpp>
#include <boost/python/suite/indexing/map_indexing_suite.hpp>
#include <boost/python/docstring_options.hpp>
#include <boost/mpl/vector.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/timer.hpp>
#include <boost/python/list.hpp>
#include <boost/python/extract.hpp>
#include <boost/python/scope.hpp>
#include <boost/filesystem.hpp>
Functions
BOOST_PYTHON_MODULE (freeOrionAIInterface)
Function Documentation
BOOST_PYTHON_MODULE (freeOrionAIInterface)
References FreeOrionPython::SetWrapper< ElementType >::Wrap(), FreeOrionPython::WrapAI(), FreeOrionPython::WrapEmpire(), FreeOrionPython::WrapGalaxySetupData(), FreeOrionPython::WrapGameStateEnums(), and FreeOrionPython::WrapUniverseClasses().