FreeOrion: SideBar Class Reference
SideBar Class Reference
Public Member Functions
SideBar (const CombatSummary &combat_summary, const BarSizer &sizer)
virtual GG::Pt ClientLowerRight () const
virtual GG::Pt ClientUpperLeft () const
void DoLayout ()
void DrawArrow (GG::Pt begin, GG::Pt end)
void MakeBars ()
GG::Pt RelativeClientUpperLeft () const
virtual void Render ()
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Private Member Functions
float MaxMaxHealth ()
Private Attributes
GG::Label * m_dead_label
std::vector< ParticipantBar * > m_participant_bars
const CombatSummary & m_side_summary
const BarSizer & m_sizer
GG::Label * m_x_axis_label
GG::Label * m_y_axis_label
Detailed Description
A Bar that shows the aggregate health of a side, and the statuses of all its units
Constructor & Destructor Documentation
SideBar::SideBar (const CombatSummary & combat_summary, const BarSizer & sizer) inline
References CombatSummary::DestroyedUnits(), m_dead_label, m_side_summary, m_x_axis_label, m_y_axis_label, MakeBars(), CombatSummary::SideColor(), CombatSummary::SideName(), CombatSummary::total_current_health, CombatSummary::total_max_health, and UserString().
Member Function Documentation
virtual GG::Pt SideBar::ClientLowerRight () const inline virtual
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT(), m_x_axis_label, and anonymous_namespace{GraphicalSummary.cpp}::X_AXIS_LABEL_MARGIN().
Referenced by Render().
virtual GG::Pt SideBar::ClientUpperLeft () const inline virtual
References RelativeClientUpperLeft().
Referenced by Render().
void SideBar::DoLayout () inline
References ParticipantBar::Alive(), anonymous_namespace{GraphicalSummary.cpp}::AXIS_WIDTH(), ParticipantBar::DoLayout(), CombatSummary::empire, BarSizer::GetSideBarSize(), m_dead_label, m_participant_bars, m_side_summary, m_sizer, m_x_axis_label, m_y_axis_label, and ParticipantBar::MoveBottomTo().
Referenced by GraphicalSummaryWnd::DoLayout(), MakeBars(), and SizeMove().
void SideBar::DrawArrow (GG::Pt begin, GG::Pt end) inline
Referenced by Render().
void SideBar::MakeBars () inline
References DoLayout(), m_participant_bars, m_side_summary, m_sizer, and CombatSummary::unit_summaries.
Referenced by SideBar().
float SideBar::MaxMaxHealth () inline private
References m_side_summary, and CombatSummary::unit_summaries.
GG::Pt SideBar::RelativeClientUpperLeft () const inline
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_WIDTH(), m_y_axis_label, and anonymous_namespace{GraphicalSummary.cpp}::Y_AXIS_LABEL_MARGIN().
Referenced by ClientUpperLeft().
virtual void SideBar::Render () inline virtual
References anonymous_namespace{GraphicalSummary.cpp}::AXIS_HEIGHT(), anonymous_namespace{GraphicalSummary.cpp}::AXIS_WIDTH(), ClientLowerRight(), ClientUpperLeft(), and DrawArrow().
virtual void SideBar::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline virtual
References DoLayout().
Member Data Documentation
GG::Label* SideBar::m_dead_label private
Referenced by DoLayout(), and SideBar().
std::vector<ParticipantBar*> SideBar::m_participant_bars private
Referenced by DoLayout(), and MakeBars().
const CombatSummary& SideBar::m_side_summary private
Referenced by DoLayout(), MakeBars(), MaxMaxHealth(), and SideBar().
const BarSizer& SideBar::m_sizer private
Referenced by DoLayout(), and MakeBars().
GG::Label* SideBar::m_x_axis_label private
Referenced by ClientLowerRight(), DoLayout(), and SideBar().
GG::Label* SideBar::m_y_axis_label private
Referenced by DoLayout(), RelativeClientUpperLeft(), and SideBar().
The documentation for this class was generated from the following file:
GraphicalSummary.cpp