FreeOrion: DualMeter Namespace Reference
DualMeter Namespace Reference
Functions
boost::tuple< float, float, float > CurrentProjectedTarget (const UniverseObject &obj, const MeterType &actual_meter_type, const MeterType &target_meter_type)
Function Documentation
boost::tuple< float, float, float > DualMeter::CurrentProjectedTarget (const UniverseObject & obj, const MeterType & actual_meter_type, const MeterType & target_meter_type)
Return the triplet of {Current, Projected, Target} meter value for the pair of meters actual_meter_type and target_meter_type associated with obj.
References Meter::Current(), anonymous_namespace{MeterBrowseWnd.cpp}::GetAccountingInfo(), UniverseObject::GetMeter(), UniverseObject::ID(), Meter::Initial(), Meter::INVALID_VALUE, and UniverseObject::NextTurnCurrentMeterValue().
Referenced by MultiMeterStatusBar::Update(), and MeterBrowseWnd::UpdateSummary().