FreeOrion: Effect.h File Reference
Effect.h File Reference
#include "EffectAccounting.h"
#include "../util/Export.h"
#include <boost/serialization/access.hpp>
#include <boost/serialization/nvp.hpp>
#include <vector>
Classes
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
class Effect
struct ValueRef::ValueRefBase< T >
Namespaces
Condition
Effect
ValueRef
Functions
FO_COMMON_API std::string AutoGeneratedDescription (const std::vector< boost::shared_ptr< Effect::EffectsGroup > > &effects_groups)
Function Documentation
FO_COMMON_API std::string AutoGeneratedDescription (const std::vector< boost::shared_ptr< Effect::EffectsGroup > > & effects_groups)
Returns a single string which describes a vector of EffectsGroups.
References Effect::AutoGeneratedDescription(), FlexibleFormat(), and UserString().
Referenced by BuildingIndicator::Refresh(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelFieldTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpeciesTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelTechTag(), and SpecialsPanel::Update().