FreeOrion: ValueRefIntFixture Struct Reference
ValueRefIntFixture Struct Reference
Public Types
typedef std::pair
< ValueRef::ReferenceType,
std::string > ReferenceType
typedef std::pair
< ValueRef::StatisticType,
std::string > StatisticType
Public Member Functions
ValueRefIntFixture ()
~ValueRefIntFixture ()
void assertion_result (bool passed)
bool parse (std::string phrase, ValueRef::ValueRefBase< int > *&result)
void printTree (const ValueRef::ValueRefBase< int > *root, int depth)
Public Attributes
const ValueRef::Operation< int > * operation1
const ValueRef::Operation< int > * operation2
const ValueRef::Operation< int > * operation3
const ValueRef::Operation< int > * operation4
const ValueRef::Operation< int > * operation5
const ValueRef::Operation< int > * operation6
ValueRef::ValueRefBase< int > * result
const ValueRef::Statistic< int > * statistic
const ValueRef::Constant< int > * value
const ValueRef::Variable< int > * variable
Static Public Attributes
static const boost::array
< std::string, 13 > attributes
static const boost::array
< std::string, 3 > containerTypes
static const boost::array
< ReferenceType, 4 > referenceTypes
static const boost::array
< StatisticType, 9 > statisticTypes
Member Typedef Documentation
typedef std::pair<ValueRef::ReferenceType, std::string> ValueRefIntFixture::ReferenceType
typedef std::pair<ValueRef::StatisticType, std::string> ValueRefIntFixture::StatisticType
Constructor & Destructor Documentation
ValueRefIntFixture::ValueRefIntFixture () inline
ValueRefIntFixture::~ValueRefIntFixture () inline
References result.
Member Function Documentation
void ValueRefIntFixture::assertion_result (bool passed) inline
References printTree(), and result.
bool ValueRefIntFixture::parse (std::string phrase, ValueRef::ValueRefBase< int > *& result) inline
References anonymous_namespace{EnumParser.cpp}::_1, lexer, and parse::value_ref_parser< int >().
void ValueRefIntFixture::printTree (const ValueRef::ValueRefBase< int > * root, int depth) inline
References value.
Referenced by assertion_result().
Member Data Documentation
const boost::array< std::string, 13 > ValueRefIntFixture::attributes static
Initial value:
= {{
    "Age",
    "CreationTurn",
    "DesignID",
    "FinalDestinationID",
    "FleetID",
    "ID",
    "NextSystemID",
    "NumShips",
    "Owner",
    "PlanetID",
    "PreviousSystemID",
    "ProducedByEmpireID",
    "SystemID"
}}
const boost::array< std::string, 3 > ValueRefIntFixture::containerTypes static
Initial value:
= {{
    "Fleet",
    "Planet",
    "System"
}}
const ValueRef::Operation<int>* ValueRefIntFixture::operation1
const ValueRef::Operation<int>* ValueRefIntFixture::operation2
const ValueRef::Operation<int>* ValueRefIntFixture::operation3
const ValueRef::Operation<int>* ValueRefIntFixture::operation4
const ValueRef::Operation<int>* ValueRefIntFixture::operation5
const ValueRef::Operation<int>* ValueRefIntFixture::operation6
const boost::array< ValueRefIntFixture::ReferenceType, 4 > ValueRefIntFixture::referenceTypes static
Initial value:
= {{
    std::make_pair(ValueRef::SOURCE_REFERENCE, "Source"),
    std::make_pair(ValueRef::EFFECT_TARGET_REFERENCE, "Target"),
    std::make_pair(ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, "LocalCandidate"),
    std::make_pair(ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, "RootCandidate")
}}
ValueRef::ValueRefBase<int>* ValueRefIntFixture::result
Referenced by assertion_result(), and ~ValueRefIntFixture().
const ValueRef::Statistic<int>* ValueRefIntFixture::statistic
const boost::array< ValueRefIntFixture::StatisticType, 9 > ValueRefIntFixture::statisticTypes static
Initial value:
= {{
    std::make_pair(ValueRef::MAX,     "Max"),
    std::make_pair(ValueRef::MEAN,    "Mean"),
    std::make_pair(ValueRef::MIN,     "Min"),
    std::make_pair(ValueRef::MODE,    "Mode"),
    std::make_pair(ValueRef::PRODUCT, "Product"),
    std::make_pair(ValueRef::RMS,     "RMS"),
    std::make_pair(ValueRef::SPREAD,  "Spread"),
    std::make_pair(ValueRef::STDEV,   "StDev"),
    std::make_pair(ValueRef::SUM,     "Sum")
}}
const ValueRef::Constant<int>* ValueRefIntFixture::value
Referenced by printTree().
const ValueRef::Variable<int>* ValueRefIntFixture::variable
The documentation for this struct was generated from the following file:
TestValueRefIntParser.cpp