FreeOrion: ValueRef::NameLookup Struct Reference
ValueRef::NameLookup Struct Reference
#include <ValueRef.h>
Public Types
enum LookupType { INVALID_LOOKUP = -1, OBJECT_NAME, EMPIRE_NAME, SHIP_DESIGN_NAME }
Public Member Functions
NameLookup (ValueRefBase< int > *value_ref, LookupType lookup_type)
~NameLookup ()
virtual std::string Description () const
virtual std::string Dump () const
returns a text description of this type of special
virtual std::string Eval (const ScriptingContext &context) const
LookupType GetLookupType () const
const ValueRefBase< int > * GetValueRef () const
virtual bool LocalCandidateInvariant () const
virtual bool operator== (const ValueRefBase< std::string > &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Public Member Functions inherited from ValueRef::Variable< std::string >
Variable (ReferenceType ref_type, const std::vector< std::string > &property_name)
Variable (ReferenceType ref_type, const std::string &property_name="")
ReferenceType GetReferenceType () const
const std::vector< std::string > & PropertyName () const
Public Member Functions inherited from ValueRef::ValueRefBase< std::string >
virtual ~ValueRefBase ()
virtual dtor
std::string Eval () const
bool operator!= (const ValueRefBase< std::string > &rhs) const
virtual bool SimpleIncrement () const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
LookupType m_lookup_type
ValueRefBase< int > * m_value_ref
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from ValueRef::Variable< std::string >
std::vector< std::string > m_property_name
ReferenceType m_ref_type
Detailed Description
Returns the in-game name of the object / empire / etc. with a specified id.
Member Enumeration Documentation
enum ValueRef::NameLookup::LookupType
Enumerator
INVALID_LOOKUP
OBJECT_NAME
EMPIRE_NAME
SHIP_DESIGN_NAME
Constructor & Destructor Documentation
ValueRef::NameLookup::NameLookup (ValueRefBase< int > * value_ref, LookupType lookup_type)
ValueRef::NameLookup::~NameLookup ()
References m_value_ref.
Member Function Documentation
std::string ValueRef::NameLookup::Description () const virtual
Reimplemented from ValueRef::Variable< std::string >.
References ValueRef::ValueRefBase< T >::Description(), and m_value_ref.
std::string ValueRef::NameLookup::Dump () const virtual
returns a text description of this type of special
Reimplemented from ValueRef::Variable< std::string >.
References ValueRef::ValueRefBase< T >::Dump(), and m_value_ref.
std::string ValueRef::NameLookup::Eval (const ScriptingContext & context) const virtual
Evaluates the expression tree and return the results; context is used to fill in any instances of the "Value" variable or references to objects such as the source, effect target, or condition candidates that exist in the tree.
Reimplemented from ValueRef::Variable< std::string >.
References EMPIRE_NAME, ValueRef::ValueRefBase< T >::Eval(), GetEmpire(), GetShipDesign(), GetUniverseObject(), INVALID_LOOKUP, m_lookup_type, m_value_ref, UniverseObject::Name(), Empire::Name(), ShipDesign::Name(), OBJECT_NAME, and SHIP_DESIGN_NAME.
LookupType ValueRef::NameLookup::GetLookupType () const inline
const ValueRefBase<int>* ValueRef::NameLookup::GetValueRef () const inline
bool ValueRef::NameLookup::LocalCandidateInvariant () const virtual
Reimplemented from ValueRef::Variable< std::string >.
References ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), and m_value_ref.
bool ValueRef::NameLookup::operator== (const ValueRefBase< std::string > & rhs) const virtual
Reimplemented from ValueRef::Variable< std::string >.
References m_lookup_type, and m_value_ref.
bool ValueRef::NameLookup::RootCandidateInvariant () const virtual
Reimplemented from ValueRef::Variable< std::string >.
References m_value_ref, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
template<class Archive > void ValueRef::NameLookup::serialize (Archive & ar, const unsigned int version) private
References m_lookup_type, and m_value_ref.
void ValueRef::NameLookup::SetTopLevelContent (const std::string & content_name) virtual
Reimplemented from ValueRef::ValueRefBase< std::string >.
References m_value_ref, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool ValueRef::NameLookup::SourceInvariant () const virtual
Reimplemented from ValueRef::Variable< std::string >.
References m_value_ref, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool ValueRef::NameLookup::TargetInvariant () const virtual
Reimplemented from ValueRef::Variable< std::string >.
References m_value_ref, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
LookupType ValueRef::NameLookup::m_lookup_type private
Referenced by Eval(), operator==(), and serialize().
ValueRefBase<int>* ValueRef::NameLookup::m_value_ref private
Referenced by Description(), Dump(), Eval(), LocalCandidateInvariant(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~NameLookup().
The documentation for this struct was generated from the following files:
ValueRef.h
ValueRef.cpp