FreeOrion: FleetMoveOrder Class Reference
FleetMoveOrder Class Reference
#include <Order.h>
Public Member Functions
Structors
FleetMoveOrder ()
FleetMoveOrder (int empire, int fleet_id, int start_system_id, int dest_system_id, bool append=false)
Accessors
int FleetID () const
returns ID of fleet selected in this order
int StartSystemID () const
returns ID of system set as the start system for this order (the system the route starts from)
int DestinationSystemID () const
returns ID of system set as destination for this order
const std::vector< int > & Route () const
returns the IDs of the systems in the route specified by this Order
Public Member Functions inherited from Order
void Execute () const
executes the order on the Universe and Empires
bool Undo () const
if this function returns true, it reverts the game state to what it was before this order was executed, otherwise it returns false and has no effect
Order ()
default ctor
Order (int empire)
ctor taking the ID of the Empire issuing the order
virtual ~Order ()
int EmpireID () const
returns the ID of the Empire issuing the order
Private Member Functions
virtual void ExecuteImpl () const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
bool m_append
int m_dest_system
int m_fleet
std::vector< int > m_route
int m_start_system
Friends
class boost::serialization::access
Additional Inherited Members
Protected Member Functions inherited from Order
void ValidateEmpireID () const
verifies that the empire ID in this order is that of an existing empire. Throws an std::runtime_error if not
bool Executed () const
returns true iff this order has been executed (a second execution indicates server-side execution)
Detailed Description
the Order subclass that represents fleet movement These orders change the current destination of a fleet
Constructor & Destructor Documentation
FleetMoveOrder::FleetMoveOrder ()
FleetMoveOrder::FleetMoveOrder (int empire, int fleet_id, int start_system_id, int dest_system_id, bool append = false)
References DestinationSystemID(), Order::EmpireID(), ErrorLogger, FleetID(), GetFleet(), GetSystem(), GetUniverse(), m_dest_system, m_route, m_start_system, UniverseObject::OwnedBy(), and Universe::ShortestPath().
Member Function Documentation
int FleetMoveOrder::DestinationSystemID () const inline
returns ID of system set as destination for this order
Referenced by ExecuteImpl(), and FleetMoveOrder().
void FleetMoveOrder::ExecuteImpl () const private virtual
Preconditions of execute:
m_fleet is a valid id of a fleet owned by the order-giving empire
if the fleet is located in a system, m_start_system is the id of that system
if the fleet is not located in a system, m_start_system is the id of the system the fleet is moving to
Postconditions:
TODO: WRITE THIS
Implements Order.
References DebugLogger, DestinationSystemID(), Order::EmpireID(), ErrorLogger, Fleet::ETA(), Fleet::ETA_NEVER, Fleet::ETA_OUT_OF_RANGE, FleetID(), GetEmpireKnownSystem(), GetFleet(), UniverseObject::ID(), INVALID_OBJECT_ID, m_append, m_route, m_start_system, Fleet::MovePath(), Fleet::NextSystemID(), UniverseObject::OwnedBy(), Fleet::SetRoute(), UniverseObject::SystemID(), Fleet::TravelRoute(), and Order::ValidateEmpireID().
int FleetMoveOrder::FleetID () const inline
returns ID of fleet selected in this order
Referenced by ExecuteImpl(), and FleetMoveOrder().
const std::vector<int>& FleetMoveOrder::Route () const inline
returns the IDs of the systems in the route specified by this Order
template<class Archive > void FleetMoveOrder::serialize (Archive & ar, const unsigned int version) private
References m_append, m_dest_system, m_fleet, m_route, and m_start_system.
int FleetMoveOrder::StartSystemID () const inline
returns ID of system set as the start system for this order (the system the route starts from)
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
bool FleetMoveOrder::m_append private
Referenced by ExecuteImpl(), and serialize().
int FleetMoveOrder::m_dest_system private
Referenced by FleetMoveOrder(), and serialize().
int FleetMoveOrder::m_fleet private
Referenced by serialize().
std::vector<int> FleetMoveOrder::m_route private
Referenced by ExecuteImpl(), FleetMoveOrder(), and serialize().
int FleetMoveOrder::m_start_system private
Referenced by ExecuteImpl(), FleetMoveOrder(), and serialize().
The documentation for this class was generated from the following files:
Order.h
Order.cpp
SerializeOrderSet.cpp