FreeOrion: anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch Struct Reference
anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch Struct Reference
Public Member Functions
FocusTypeSimpleMatch (const std::vector< std::string > &names)
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
const std::vector< std::string > & m_names
Constructor & Destructor Documentation
anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::FocusTypeSimpleMatch (const std::vector< std::string > & names) inline
Member Function Documentation
bool anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References boost::dynamic_pointer_cast(), ResourceCenter::Focus(), GetPlanet(), and m_names.
Member Data Documentation
const std::vector<std::string>& anonymous_namespace{Condition.cpp}::FocusTypeSimpleMatch::m_names
Referenced by operator()().
The documentation for this struct was generated from the following file:
Condition.cpp