FreeOrion: SaveFileRow Class Reference
SaveFileRow Class Reference
Public Types
enum RowType { HEADER, PREVIEW, DIRECTORY }
What sort of a row.
Public Member Functions
SaveFileRow (const std::vector< SaveFileColumn > &columns)
Creates a header row.
SaveFileRow (const FullPreview &full, const std::vector< SaveFileColumn > &visible_columns, const std::vector< SaveFileColumn > &columns, int tooltip_delay)
Creates a row for the given savefile.
SaveFileRow (const std::string &directory)
Creates a directory row.
void AdjustColumns (const std::vector< SaveFileColumn > &columns)
virtual GG::Pt ClientLowerRight () const
virtual GG::Pt ClientUpperLeft () const
const std::string & Filename () const
virtual void Render ()
const RowType Type () const
Private Attributes
std::string m_filename
RowType m_type
Detailed Description
A Specialized row for the save dialog list box.
Member Enumeration Documentation
enum SaveFileRow::RowType
What sort of a row.
Enumerator
HEADER
PREVIEW
DIRECTORY
Constructor & Destructor Documentation
SaveFileRow::SaveFileRow (const std::vector< SaveFileColumn > & columns) inline
Creates a header row.
References AdjustColumns(), anonymous_namespace{SaveFileDialog.cpp}::ROW_MARGIN, and SaveFileColumn::TitleForColumn().
SaveFileRow::SaveFileRow (const FullPreview & full, const std::vector< SaveFileColumn > & visible_columns, const std::vector< SaveFileColumn > & columns, int tooltip_delay) inline
Creates a row for the given savefile.
References VarText::AddVariable(), AdjustColumns(), SaveFileColumn::CellForColumn(), ColumnInPreview(), FullPreview::filename, VarText::GetText(), m_filename, anonymous_namespace{SaveFileDialog.cpp}::ROW_MARGIN, and UserStringNop.
SaveFileRow::SaveFileRow (const std::string & directory) inline
Creates a directory row.
References anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_BEGIN, anonymous_namespace{SaveFileDialog.cpp}::PATH_DELIM_END, and anonymous_namespace{SaveFileDialog.cpp}::ROW_MARGIN.
Member Function Documentation
void SaveFileRow::AdjustColumns (const std::vector< SaveFileColumn > & columns) inline
References DIRECTORY, SaveFileColumn::FixedWidth(), SaveFileColumn::Stretch(), and Type().
Referenced by SaveFileListBox::RefreshRowSizes(), and SaveFileRow().
virtual GG::Pt SaveFileRow::ClientLowerRight () const inline virtual
Excludes border from the client area.
References anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_CELL_MARGIN.
Referenced by Render().
virtual GG::Pt SaveFileRow::ClientUpperLeft () const inline virtual
Excludes border from the client area.
References anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_CELL_MARGIN.
Referenced by Render().
const std::string& SaveFileRow::Filename () const inline
References m_filename.
Referenced by SaveFileListBox::HasFile(), and SaveFileDialog::SelectionChanged().
virtual void SaveFileRow::Render () inline virtual
References ClientLowerRight(), ClientUpperLeft(), HEADER, m_type, anonymous_namespace{SaveFileDialog.cpp}::SAVE_FILE_CELL_MARGIN, and ClientUI::WndOuterBorderColor().
const RowType SaveFileRow::Type () const inline
References m_type.
Referenced by AdjustColumns().
Member Data Documentation
std::string SaveFileRow::m_filename private
Referenced by Filename(), and SaveFileRow().
RowType SaveFileRow::m_type private
Referenced by Render(), and Type().
The documentation for this class was generated from the following file:
SaveFileDialog.cpp