FreeOrion: ScopedTimer::ScopedTimerImpl Class Reference
ScopedTimer::ScopedTimerImpl Class Reference
Public Member Functions
ScopedTimerImpl (const std::string &timed_name, bool enable_output, boost::chrono::microseconds threshold)
~ScopedTimerImpl ()
void FormatDuration (std::stringstream &ss, const boost::chrono::nanoseconds &duration)
bool ShouldOutput (const boost::chrono::nanoseconds &duration)
Public Attributes
bool m_enable_output
std::string m_name
boost::chrono::high_resolution_clock::time_point m_start
boost::chrono::microseconds m_threshold
Constructor & Destructor Documentation
ScopedTimer::ScopedTimerImpl::ScopedTimerImpl (const std::string & timed_name, bool enable_output, boost::chrono::microseconds threshold) inline
ScopedTimer::ScopedTimerImpl::~ScopedTimerImpl () inline
References DebugLogger, FormatDuration(), m_name, m_start, and ShouldOutput().
Member Function Documentation
void ScopedTimer::ScopedTimerImpl::FormatDuration (std::stringstream & ss, const boost::chrono::nanoseconds & duration) inline
Referenced by ~ScopedTimerImpl(), and SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl().
bool ScopedTimer::ScopedTimerImpl::ShouldOutput (const boost::chrono::nanoseconds & duration) inline
References GetOptionsDB(), m_enable_output, and m_threshold.
Referenced by ~ScopedTimerImpl(), and SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl().
Member Data Documentation
bool ScopedTimer::ScopedTimerImpl::m_enable_output
Referenced by ShouldOutput(), and SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl().
std::string ScopedTimer::ScopedTimerImpl::m_name
Referenced by ~ScopedTimerImpl(), and SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl().
boost::chrono::high_resolution_clock::time_point ScopedTimer::ScopedTimerImpl::m_start
Referenced by SectionedScopedTimer::SectionedScopedTimerImpl::CreateSections(), ~ScopedTimerImpl(), and SectionedScopedTimer::SectionedScopedTimerImpl::~SectionedScopedTimerImpl().
boost::chrono::microseconds ScopedTimer::ScopedTimerImpl::m_threshold
Referenced by ShouldOutput().
The documentation for this class was generated from the following file:
ScopedTimer.cpp