FreeOrion: anonymous_namespace{ShipPartsParser.cpp}::rules Struct Reference
anonymous_namespace{ShipPartsParser.cpp}::rules Struct Reference
Public Types
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, PartType * >
&), qi::locals
< MoreCommonParams,
std::string, ShipPartClass,
double, CommonParams,
std::vector< ShipSlotType >
, bool, double >
, parse::skipper_type > part_type_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::vector
< ShipSlotType >
&), parse::skipper_type > slots_rule
typedef
boost::spirit::qi::rule
< parse::token_iterator, void(std::map
< std::string, PartType * >
&), parse::skipper_type > start_rule
Public Member Functions
rules ()
Public Attributes
part_type_rule part_type
slots_rule slots
start_rule start
Member Typedef Documentation
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, PartType*>&), qi::locals< MoreCommonParams, std::string, ShipPartClass, double, CommonParams, std::vector<ShipSlotType>, bool, double >, parse::skipper_type > anonymous_namespace{ShipPartsParser.cpp}::rules::part_type_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::vector<ShipSlotType>&), parse::skipper_type > anonymous_namespace{ShipPartsParser.cpp}::rules::slots_rule
typedef boost::spirit::qi::rule< parse::token_iterator, void (std::map<std::string, PartType*>&), parse::skipper_type > anonymous_namespace{ShipPartsParser.cpp}::rules::start_rule
Constructor & Destructor Documentation
anonymous_namespace{ShipPartsParser.cpp}::rules::rules () inline
References anonymous_namespace{EnumParser.cpp}::_1, parse::detail::common_params_parser(), parse::double_, parse::enum_parser< ShipPartClass >(), parse::enum_parser< ShipSlotType >(), anonymous_namespace{ShipPartsParser.cpp}::insert_part_type, parse::lexer::instance(), parse::label(), parse::detail::more_common_params_parser(), parse::report_error, parse::lexer::string, parse::value_ref_parser< double >(), and parse::value_ref_parser_flexible_int().
Member Data Documentation
part_type_rule anonymous_namespace{ShipPartsParser.cpp}::rules::part_type
slots_rule anonymous_namespace{ShipPartsParser.cpp}::rules::slots
start_rule anonymous_namespace{ShipPartsParser.cpp}::rules::start
The documentation for this struct was generated from the following file:
ShipPartsParser.cpp