var searchData=
[
  ['rangedstepvalidator',['RangedStepValidator',['../structRangedStepValidator.html',1,'']]],
  ['rangedvalidator',['RangedValidator',['../structRangedValidator.html',1,'']]],
  ['reacheddepthlimit',['ReachedDepthLimit',['../classSystemPathing_1_1BFSVisitorImpl_1_1ReachedDepthLimit.html',1,'SystemPathing::BFSVisitorImpl']]],
  ['removespecial',['RemoveSpecial',['../classEffect_1_1RemoveSpecial.html',1,'Effect']]],
  ['removestarlane',['RemoveStarlane',['../classModerator_1_1RemoveStarlane.html',1,'Moderator']]],
  ['removestarlanes',['RemoveStarlanes',['../classEffect_1_1RemoveStarlanes.html',1,'Effect']]],
  ['renameorder',['RenameOrder',['../classRenameOrder.html',1,'']]],
  ['report_5ferror_5f',['report_error_',['../structparse_1_1report__error__.html',1,'parse']]],
  ['researchqueue',['ResearchQueue',['../structResearchQueue.html',1,'']]],
  ['researchqueuelistbox',['ResearchQueueListBox',['../classResearchQueueListBox.html',1,'']]],
  ['researchqueueorder',['ResearchQueueOrder',['../classResearchQueueOrder.html',1,'']]],
  ['researchqueuewnd',['ResearchQueueWnd',['../classResearchQueueWnd.html',1,'']]],
  ['researchwnd',['ResearchWnd',['../classResearchWnd.html',1,'']]],
  ['resourcebrowsewnd',['ResourceBrowseWnd',['../classResourceBrowseWnd.html',1,'']]],
  ['resourcecenter',['ResourceCenter',['../classResourceCenter.html',1,'']]],
  ['resourceinfopanel',['ResourceInfoPanel',['../classResourceInfoPanel.html',1,'']]],
  ['resourcepanel',['ResourcePanel',['../classResourcePanel.html',1,'']]],
  ['resourcepool',['ResourcePool',['../classResourcePool.html',1,'']]],
  ['resourcesupplyconnectedbyempire',['ResourceSupplyConnectedByEmpire',['../structCondition_1_1ResourceSupplyConnectedByEmpire.html',1,'Condition']]],
  ['resourcesupplysimplematch',['ResourceSupplySimpleMatch',['../structCondition_1_1anonymous__namespace_02Condition_8cpp_03_1_1ResourceSupplySimpleMatch.html',1,'Condition::anonymous_namespace{Condition.cpp}']]],
  ['result',['result',['../structparse_1_1detail_1_1deconstruct__movable__vector__pair_1_1result.html',1,'parse::detail::deconstruct_movable_vector_pair']]],
  ['result',['result',['../structparse_1_1detail_1_1deconstruct__movable__vector_1_1result.html',1,'parse::detail::deconstruct_movable_vector']]],
  ['result',['result',['../structparse_1_1detail_1_1deconstruct__movable_1_1result.html',1,'parse::detail::deconstruct_movable']]],
  ['result_3c_20f_28movableenvelope_5ft_2c_20bool_29_3e',['result&lt; F(MovableEnvelope_T, Bool)&gt;',['../structparse_1_1detail_1_1deconstruct__movable__vector__pair_1_1result_3_01F_07MovableEnvelope__T_00_01Bool_08_4.html',1,'parse::detail::deconstruct_movable_vector_pair']]],
  ['result_3c_20f_28movableenvelope_5ft_2c_20bool_29_3e',['result&lt; F(MovableEnvelope_T, Bool)&gt;',['../structparse_1_1detail_1_1deconstruct__movable__vector_1_1result_3_01F_07MovableEnvelope__T_00_01Bool_08_4.html',1,'parse::detail::deconstruct_movable_vector']]],
  ['result_3c_20f_28movableenvelope_5ft_2c_20bool_29_3e',['result&lt; F(MovableEnvelope_T, Bool)&gt;',['../structparse_1_1detail_1_1deconstruct__movable_1_1result_3_01F_07MovableEnvelope__T_00_01Bool_08_4.html',1,'parse::detail::deconstruct_movable']]],
  ['rootcandidate',['RootCandidate',['../structCondition_1_1RootCandidate.html',1,'Condition']]],
  ['rotatinggraphic',['RotatingGraphic',['../classRotatingGraphic.html',1,'']]],
  ['rotatingplanetcontrol',['RotatingPlanetControl',['../classRotatingPlanetControl.html',1,'']]],
  ['rotatingplanetdata',['RotatingPlanetData',['../structanonymous__namespace_02SidePanel_8cpp_03_1_1RotatingPlanetData.html',1,'anonymous_namespace{SidePanel.cpp}']]],
  ['rowcontentswnd',['RowContentsWnd',['../classanonymous__namespace_02OptionsWnd_8cpp_03_1_1RowContentsWnd.html',1,'anonymous_namespace{OptionsWnd.cpp}']]],
  ['rowcontentswnd',['RowContentsWnd',['../classanonymous__namespace_02GalaxySetupWnd_8cpp_03_1_1RowContentsWnd.html',1,'anonymous_namespace{GalaxySetupWnd.cpp}']]],
  ['rule',['Rule',['../structGameRules_1_1Rule.html',1,'GameRules']]],
  ['ruledefiner',['RuleDefiner',['../structXMLDoc_1_1RuleDefiner.html',1,'XMLDoc']]],
  ['rulelistrow',['RuleListRow',['../classanonymous__namespace_02GalaxySetupWnd_8cpp_03_1_1RuleListRow.html',1,'anonymous_namespace{GalaxySetupWnd.cpp}']]],
  ['runqueue',['RunQueue',['../classRunQueue.html',1,'']]]
];
