FreeOrion: CUIScroll::ScrollTab Class Reference
CUIScroll::ScrollTab Class Reference
#include <CUIControls.h>
Public Member Functions
ScrollTab (GG::Orientation orientation, int scroll_width, GG::Clr color, GG::Clr border_color)
basic ctor
virtual void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseLeave ()
virtual void Render ()
virtual void SetColor (GG::Clr c)
Private Attributes
bool m_being_dragged
GG::Clr m_border_color
bool m_mouse_here
GG::Orientation m_orientation
Detailed Description
represents the tab button for a CUIScroll
Constructor & Destructor Documentation
CUIScroll::ScrollTab::ScrollTab (GG::Orientation orientation, int scroll_width, GG::Clr color, GG::Clr border_color)
basic ctor
References m_orientation.
Member Function Documentation
void CUIScroll::ScrollTab::LButtonDown (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
void CUIScroll::ScrollTab::LButtonUp (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
void CUIScroll::ScrollTab::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
void CUIScroll::ScrollTab::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
References GetOptionsDB(), Sound::GetSound(), and Sound::PlaySound().
void CUIScroll::ScrollTab::MouseLeave () virtual
void CUIScroll::ScrollTab::Render () virtual
References AdjustBrightness(), AngledCornerRectangle(), and CUIScroll::m_border_color.
void CUIScroll::ScrollTab::SetColor (GG::Clr c) virtual
Member Data Documentation
bool CUIScroll::ScrollTab::m_being_dragged private
GG::Clr CUIScroll::ScrollTab::m_border_color private
bool CUIScroll::ScrollTab::m_mouse_here private
GG::Orientation CUIScroll::ScrollTab::m_orientation private
Referenced by ScrollTab().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp