FreeOrion: Moderator::SetOwner Class Reference
Moderator::SetOwner Class Reference
#include <ModeratorAction.h>
Public Member Functions
SetOwner ()
SetOwner (int object_id, int new_owner_empire_id)
virtual ~SetOwner ()
virtual std::string Dump () const
virtual void Execute () const
Public Member Functions inherited from Moderator::ModeratorAction
ModeratorAction ()
virtual ~ModeratorAction ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
int m_new_owner_empire_id
int m_object_id
Friends
class boost::serialization::access
Constructor & Destructor Documentation
Moderator::SetOwner::SetOwner ()
Moderator::SetOwner::SetOwner (int object_id, int new_owner_empire_id)
SetOwner::~SetOwner () inline virtual
Member Function Documentation
std::string Moderator::SetOwner::Dump () const virtual
Reimplemented from Moderator::ModeratorAction.
References DumpIndent().
void Moderator::SetOwner::Execute () const virtual
Reimplemented from Moderator::ModeratorAction.
References anonymous_namespace{Effect.cpp}::CreateNewFleet(), ScriptingContext::effect_target, Universe::EffectDestroy(), Fleet::Empty(), Ship::FleetID(), GetFleet(), GetSystem(), GetUniverse(), UniverseObject::ID(), INVALID_OBJECT_ID, Fleet::NextSystemID(), UniverseObject::Owner(), Fleet::PreviousSystemID(), Fleet::SetNextAndPreviousSystems(), UniverseObject::SetOwner(), UniverseObject::SystemID(), UniverseObject::X(), and UniverseObject::Y().
template<class Archive > template void Moderator::SetOwner::serialize< freeorion_xml_iarchive > (Archive & ar, const unsigned int version) private
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
int Moderator::SetOwner::m_new_owner_empire_id private
int Moderator::SetOwner::m_object_id private
The documentation for this class was generated from the following files:
ModeratorAction.h
Effect.cpp
ModeratorAction.cpp
SerializeModeratorAction.cpp