FreeOrion: ShipDataPanel Class Reference
ShipDataPanel Class Reference
#include <FleetWnd.h>
Public Member Functions
Structors
ShipDataPanel (GG::X w, GG::Y h, int ship_id)
~ShipDataPanel ()
Accessors //@{
virtual GG::Pt ClientUpperLeft () const
virtual GG::Pt ClientLowerRight () const
Mutators //@{
virtual void Render ()
void Select (bool b)
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
Private Member Functions
void DoLayout ()
void Init ()
void Refresh ()
void SetShipIcon ()
double StatValue (MeterType stat_name) const
Private Attributes
GG::StaticGraphic * m_bombard_indicator
GG::StaticGraphic * m_colonize_indicator
GG::Label * m_design_name_text
boost::signals2::connection m_fleet_connection
bool m_initialized
GG::StaticGraphic * m_invade_indicator
ScanlineControl * m_scanline_control
GG::StaticGraphic * m_scrap_indicator
bool m_selected
boost::signals2::connection m_ship_connection
GG::StaticGraphic * m_ship_icon
int m_ship_id
GG::Label * m_ship_name_text
std::vector< std::pair
< MeterType, StatisticIcon * > > m_stat_icons
Detailed Description
Shows info about a single ship.
Constructor & Destructor Documentation
ShipDataPanel::ShipDataPanel (GG::X w, GG::Y h, int ship_id)
ShipDataPanel::~ShipDataPanel ()
References m_fleet_connection, and m_ship_connection.
Member Function Documentation
GG::Pt ShipDataPanel::ClientLowerRight () const virtual
Excludes border from the client area.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
GG::Pt ShipDataPanel::ClientUpperLeft () const virtual
Excludes border from the client area.
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER.
Referenced by Render().
void ShipDataPanel::DoLayout () private
References anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_TEXT_PAD, anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_bombard_indicator, m_colonize_indicator, m_design_name_text, m_invade_indicator, m_scanline_control, m_scrap_indicator, m_ship_icon, m_ship_name_text, m_stat_icons, and anonymous_namespace{FleetWnd.cpp}::StatIconSize().
Referenced by Refresh(), and SizeMove().
void ShipDataPanel::Init () private
References anonymous_namespace{FleetWnd.cpp}::DamageIcon(), Ship::Design(), Ship::FleetID(), OptionsDB::Get(), GetFleet(), GetOptionsDB(), GetShip(), Ship::HasTroops(), Ship::IsArmed(), m_design_name_text, m_fleet_connection, m_initialized, m_ship_connection, m_ship_id, m_ship_name_text, m_stat_icons, METER_CAPACITY, METER_DETECTION, METER_FUEL, METER_SHIELD, METER_SPEED, METER_STEALTH, METER_STRUCTURE, METER_TROOPS, ClientUI::MeterIcon(), UniverseObject::Name(), Refresh(), UniverseObject::StateChangedSignal, and anonymous_namespace{FleetWnd.cpp}::TroopIcon().
Referenced by Render().
void ShipDataPanel::Refresh () private
References AssociatedMeterType(), Ship::Design(), DoLayout(), ClientApp::EmpireID(), FlexibleFormat(), HumanClientApp::GetApp(), GetEmpire(), GetShip(), m_design_name_text, m_ship_id, m_ship_name_text, m_stat_icons, METER_CAPACITY, METER_TROOPS, Empire::Name(), UniverseObject::Owner(), Ship::PublicName(), SetShipIcon(), Ship::SpeciesName(), StatValue(), anonymous_namespace{FleetWnd.cpp}::TroopIcon(), UniverseObject::Unowned(), and UserString().
Referenced by Init().
void ShipDataPanel::Render () virtual
Renders black panel background, border with color depending on the current state and a background for the ship's name text.
References ClientUpperLeft(), anonymous_namespace{FleetWnd.cpp}::DATA_PANEL_BORDER, Init(), anonymous_namespace{FleetWnd.cpp}::LabelHeight(), m_initialized, m_selected, ClientUI::WndColor(), ClientUI::WndInnerBorderColor(), and ClientUI::WndOuterBorderColor().
void ShipDataPanel::Select (bool b)
Renders black panel background, border with color depending on the current state and a background for the ship's name text.
References m_design_name_text, m_selected, m_ship_name_text, and ClientUI::TextColor().
Referenced by FleetDetailPanel::ShipSelectionChanged().
void ShipDataPanel::SetShipIcon () private
References ClientUI::ArtDir(), anonymous_namespace{FleetWnd.cpp}::DataPanelIconStyle(), Ship::Design(), ClientApp::EmpireID(), HumanClientApp::GetApp(), GetShip(), ClientUI::GetTexture(), UniverseObject::GetVisibility(), INVALID_OBJECT_ID, m_bombard_indicator, m_colonize_indicator, m_invade_indicator, m_scanline_control, m_scrap_indicator, m_ship_icon, m_ship_id, Ship::OrderedBombardPlanet(), Ship::OrderedColonizePlanet(), Ship::OrderedInvadePlanet(), Ship::OrderedScrapped(), and ClientUI::ShipDesignIcon().
Referenced by Refresh().
void ShipDataPanel::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
Renders black panel background, border with color depending on the current state and a background for the ship's name text.
References DoLayout().
double ShipDataPanel::StatValue (MeterType stat_name) const private
References ErrorLogger, GetShip(), m_ship_id, METER_CAPACITY, and METER_TROOPS.
Referenced by Refresh().
Member Data Documentation
GG::StaticGraphic* ShipDataPanel::m_bombard_indicator private
Referenced by DoLayout(), and SetShipIcon().
GG::StaticGraphic* ShipDataPanel::m_colonize_indicator private
Referenced by DoLayout(), and SetShipIcon().
GG::Label* ShipDataPanel::m_design_name_text private
Referenced by DoLayout(), Init(), Refresh(), and Select().
boost::signals2::connection ShipDataPanel::m_fleet_connection private
Referenced by Init(), and ~ShipDataPanel().
bool ShipDataPanel::m_initialized private
Referenced by Init(), and Render().
GG::StaticGraphic* ShipDataPanel::m_invade_indicator private
Referenced by DoLayout(), and SetShipIcon().
ScanlineControl* ShipDataPanel::m_scanline_control private
Referenced by DoLayout(), and SetShipIcon().
GG::StaticGraphic* ShipDataPanel::m_scrap_indicator private
Referenced by DoLayout(), and SetShipIcon().
bool ShipDataPanel::m_selected private
Referenced by Render(), and Select().
boost::signals2::connection ShipDataPanel::m_ship_connection private
Referenced by Init(), and ~ShipDataPanel().
GG::StaticGraphic* ShipDataPanel::m_ship_icon private
Referenced by DoLayout(), and SetShipIcon().
int ShipDataPanel::m_ship_id private
Referenced by Init(), Refresh(), SetShipIcon(), and StatValue().
GG::Label* ShipDataPanel::m_ship_name_text private
Referenced by DoLayout(), Init(), Refresh(), and Select().
std::vector<std::pair<MeterType, StatisticIcon*> > ShipDataPanel::m_stat_icons private
Referenced by DoLayout(), Init(), and Refresh().
The documentation for this class was generated from the following files:
FleetWnd.h
FleetWnd.cpp