FreeOrion: anonymous_namespace{Effect.cpp} Namespace Reference
anonymous_namespace{Effect.cpp} Namespace Reference
Functions
TemporaryPtr< Fleet > CreateNewFleet (double x, double y, TemporaryPtr< Ship > ship)
TemporaryPtr< Fleet > CreateNewFleet (TemporaryPtr< System > system, TemporaryPtr< Ship > ship)
void ExploreSystem (int system_id, TemporaryPtr< const UniverseObject > target_object)
std::string GenerateSystemName ()
boost::tuple< bool,
ValueRef::OpType, double > SimpleMeterModification (MeterType meter, ValueRef::ValueRefBase< double > *ref)
void UpdateFleetRoute (TemporaryPtr< Fleet > fleet, int new_next_system, int new_previous_system)
Function Documentation
TemporaryPtr<Fleet> anonymous_namespace{Effect.cpp}::CreateNewFleet (double x, double y, TemporaryPtr< Ship > ship)
creates a new fleet at a specified x and y location within the Universe, and and inserts ship into it. Used when a ship has been moved by the MoveTo effect separately from the fleet that previously held it. All ships need to be within fleets.
References Fleet::AddShip(), Universe::CreateFleet(), Fleet::GenerateFleetName(), UniverseObject::GetMeter(), GetUniverse(), Fleet::HasArmedShips(), UniverseObject::ID(), Meter::LARGE_VALUE, METER_STEALTH, UniverseObject::Owner(), UniverseObject::Rename(), Fleet::SetAggressive(), Meter::SetCurrent(), and Ship::SetFleetID().
TemporaryPtr<Fleet> anonymous_namespace{Effect.cpp}::CreateNewFleet (TemporaryPtr< System > system, TemporaryPtr< Ship > ship)
Creates a new fleet at system and inserts ship into it. Used when a ship has been moved by the MoveTo effect separately from the fleet that previously held it. Also used by CreateShip effect to give the new ship a fleet. All ships need to be within fleets.
References Ship::FleetID(), GetFleet(), GetSystem(), UniverseObject::ID(), System::Insert(), INVALID_OBJECT_ID, UniverseObject::SetSystem(), UniverseObject::SystemID(), UniverseObject::X(), and UniverseObject::Y().
Referenced by Effect::SetOwner::Execute(), Effect::CreateShip::Execute(), Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), and Effect::MoveTowards::Execute().
void anonymous_namespace{Effect.cpp}::ExploreSystem (int system_id, TemporaryPtr< const UniverseObject > target_object)
Explores the system with the specified system_id for the owner of the specified target_object. Used when moving objects into a system with the MoveTo effect, as otherwise the system wouldn't get explored, and objects being moved into unexplored systems might disappear for players or confuse the AI.
References GetEmpire(), and UniverseObject::Owner().
Referenced by Effect::MoveTo::Execute().
std::string anonymous_namespace{Effect.cpp}::GenerateSystemName ()
References ObjectMap::FindObjects(), Objects(), and UserStringList().
Referenced by Effect::CreateSystem::Execute().
boost::tuple<bool, ValueRef::OpType, double> anonymous_namespace{Effect.cpp}::SimpleMeterModification (MeterType meter, ValueRef::ValueRefBase< double > * ref)
References ValueRef::PLUS, and UserString().
Referenced by Effect::SetMeter::Description().
void anonymous_namespace{Effect.cpp}::UpdateFleetRoute (TemporaryPtr< Fleet > fleet, int new_next_system, int new_previous_system)
Resets the previous and next systems of fleet and recalcultes / resets the fleet's move route. Used after a fleet has been moved with the MoveTo effect, as its previous route was assigned based on its previous location, and may not be valid for its new location.
References ErrorLogger, Fleet::FinalDestinationID(), GetSystem(), GetUniverse(), INVALID_OBJECT_ID, UniverseObject::Owner(), Fleet::SetNextAndPreviousSystems(), Fleet::SetRoute(), Universe::ShortestPath(), and UniverseObject::SystemID().
Referenced by Effect::MoveTo::Execute(), Effect::MoveInOrbit::Execute(), and Effect::MoveTowards::Execute().