FreeOrion: SlotControl Class Reference
SlotControl Class Reference
Public Member Functions
Structors
SlotControl ()
SlotControl (double x, double y, ShipSlotType slot_type)
Accessors
ShipSlotType SlotType () const
double XPositionFraction () const
double YPositionFraction () const
const PartType * GetPart () const
Mutators
virtual void StartingChildDragDrop (const GG::Wnd *wnd, const GG::Pt &offset)
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void CancellingChildDragDrop (const std::vector< const GG::Wnd * > &wnds)
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void AcceptDrops (const GG::Pt &pt, const std::vector< GG::Wnd * > &wnds, GG::Flags< GG::ModKey > mod_keys)
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void ChildrenDraggedAway (const std::vector< GG::Wnd * > &wnds, const GG::Wnd *destination)
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void DragDropEnter (const GG::Pt &pt, std::map< const GG::Wnd *, bool > &drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys)
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void DragDropLeave ()
used to programmatically set the PartControl in this slot. Does not emit signal
virtual void Render ()
used to programmatically set the PartControl in this slot. Does not emit signal
void Highlight (bool actually=true)
used to programmatically set the PartControl in this slot. Does not emit signal
void SetPart (const std::string &part_name)
used to programmatically set the PartControl in this slot. Does not emit signal
void SetPart (const PartType *part_type=0)
used to programmatically set the PartControl in this slot. Does not emit signal
Public Attributes
boost::signals2::signal< void(const
PartType *)> PartTypeClickedSignal
boost::signals2::signal< void(const
PartType *)> SlotContentsAlteredSignal
Protected Member Functions
virtual void DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys) const
virtual bool EventFilter (GG::Wnd *w, const GG::WndEvent &event)
Private Member Functions
void EmitNullSlotContentsAlteredSignal ()
Private Attributes
GG::StaticGraphic * m_background
bool m_highlighted
PartControl * m_part_control
ShipSlotType m_slot_type
double m_x_position_fraction
double m_y_position_fraction
position on hull image where slot should be shown, as a fraction of that image's size
Detailed Description
UI representation and drop-target for slots of a design. PartControl may be dropped into slots to add the corresponding parts to the ShipDesign, or the part may be set programmatically with SetPart().
Constructor & Destructor Documentation
SlotControl::SlotControl ()
SlotControl::SlotControl (double x, double y, ShipSlotType slot_type)
References GetOptionsDB(), m_background, m_slot_type, anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_HEIGHT(), anonymous_namespace{DesignWnd.cpp}::SLOT_CONTROL_WIDTH(), anonymous_namespace{DesignWnd.cpp}::SlotBackgroundTexture(), and UserString().
Member Function Documentation
void SlotControl::AcceptDrops (const GG::Pt & pt, const std::vector< GG::Wnd * > & wnds, GG::Flags< GG::ModKey > mod_keys) virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References ErrorLogger, PartControl::Part(), and SlotContentsAlteredSignal.
void SlotControl::CancellingChildDragDrop (const std::vector< const GG::Wnd * > & wnds) virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References m_part_control.
void SlotControl::ChildrenDraggedAway (const std::vector< GG::Wnd * > & wnds, const GG::Wnd * destination) virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References m_part_control, and SlotContentsAlteredSignal.
void SlotControl::DragDropEnter (const GG::Pt & pt, std::map< const GG::Wnd *, bool > & drop_wnds_acceptable, GG::Flags< GG::ModKey > mod_keys) virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References DropsAcceptable(), and m_part_control.
void SlotControl::DragDropLeave () virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References m_part_control.
void SlotControl::DropsAcceptable (DropsAcceptableIter first, DropsAcceptableIter last, const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) const protected virtual
References if(), m_part_control, m_slot_type, PartControl::Part(), and anonymous_namespace{DesignWnd.cpp}::PART_CONTROL_DROP_TYPE_STRING.
Referenced by DragDropEnter().
void SlotControl::EmitNullSlotContentsAlteredSignal () private
emits SlotContentsAlteredSignal with PartType* = 0. needed because boost::signals2::signal is noncopyable, so boost::bind can't be used to bind the parameter 0 to SlotContentsAlteredSignal::operator()
References SlotContentsAlteredSignal.
Referenced by SetPart().
bool SlotControl::EventFilter (GG::Wnd * w, const GG::WndEvent & event) protected virtual
References ErrorLogger.
const PartType * SlotControl::GetPart () const
References m_part_control, and PartControl::Part().
void SlotControl::Highlight (bool actually = true)
used to programmatically set the PartControl in this slot. Does not emit signal
References m_highlighted.
Referenced by DesignWnd::MainPanel::HighlightSlotType().
void SlotControl::Render () virtual
used to programmatically set the PartControl in this slot. Does not emit signal
void SlotControl::SetPart (const std::string & part_name)
used to programmatically set the PartControl in this slot. Does not emit signal
References GetPartType().
void SlotControl::SetPart (const PartType * part_type = 0)
used to programmatically set the PartControl in this slot. Does not emit signal
References PartControl::ClickedSignal, PartType::Description(), PartControl::DoubleClickedSignal, EmitNullSlotContentsAlteredSignal(), GetOptionsDB(), m_part_control, m_slot_type, PartType::Name(), ClientUI::PartIcon(), PartTypeClickedSignal, and UserString().
ShipSlotType SlotControl::SlotType () const
References m_slot_type.
Referenced by DesignWnd::MainPanel::HighlightSlotType().
void SlotControl::StartingChildDragDrop (const GG::Wnd * wnd, const GG::Pt & offset) virtual
used to programmatically set the PartControl in this slot. Does not emit signal
References m_part_control.
double SlotControl::XPositionFraction () const
References m_x_position_fraction.
Referenced by DesignWnd::MainPanel::DoLayout().
double SlotControl::YPositionFraction () const
References m_y_position_fraction.
Referenced by DesignWnd::MainPanel::DoLayout().
Member Data Documentation
GG::StaticGraphic* SlotControl::m_background private
Referenced by SlotControl().
bool SlotControl::m_highlighted private
Referenced by Highlight().
PartControl* SlotControl::m_part_control private
Referenced by CancellingChildDragDrop(), ChildrenDraggedAway(), DragDropEnter(), DragDropLeave(), DropsAcceptable(), GetPart(), SetPart(), and StartingChildDragDrop().
ShipSlotType SlotControl::m_slot_type private
Referenced by DropsAcceptable(), SetPart(), SlotControl(), and SlotType().
double SlotControl::m_x_position_fraction private
Referenced by XPositionFraction().
double SlotControl::m_y_position_fraction private
position on hull image where slot should be shown, as a fraction of that image's size
Referenced by YPositionFraction().
boost::signals2::signal<void (const PartType*)> SlotControl::PartTypeClickedSignal mutable
Referenced by DesignWnd::MainPanel::Populate(), and SetPart().
boost::signals2::signal<void (const PartType*)> SlotControl::SlotContentsAlteredSignal mutable
emitted when the contents of a slot are altered by the dragging a PartControl in or out of the slot. signal should be caught and the slot contents set using SetPart accordingly
Referenced by AcceptDrops(), ChildrenDraggedAway(), EmitNullSlotContentsAlteredSignal(), and DesignWnd::MainPanel::Populate().
The documentation for this class was generated from the following file:
DesignWnd.cpp