FreeOrion: PlayingTurn Struct Reference
PlayingTurn Struct Reference
#include <HumanClientFSM.h>
Public Types
typedef
boost::statechart::state
< PlayingTurn, PlayingGame > Base
typedef boost::mpl::list
< boost::statechart::custom_reaction
< SaveGameDataRequest >
, boost::statechart::custom_reaction
< SaveGameComplete >
, boost::statechart::custom_reaction
< AdvanceTurn >
, boost::statechart::custom_reaction
< TurnUpdate >
, boost::statechart::custom_reaction
< TurnEnded >
, boost::statechart::custom_reaction
< PlayerStatus > > reactions
Public Member Functions
PlayingTurn (my_context ctx)
~PlayingTurn ()
boost::statechart::result react (const SaveGameDataRequest &d)
boost::statechart::result react (const SaveGameComplete &d)
boost::statechart::result react (const AdvanceTurn &d)
boost::statechart::result react (const TurnUpdate &msg)
boost::statechart::result react (const TurnEnded &d)
boost::statechart::result react (const PlayerStatus &msg)
Detailed Description
The substate of PlayingGame in which the player is actively playing a turn.
Member Typedef Documentation
typedef boost::statechart::state<PlayingTurn, PlayingGame> PlayingTurn::Base
typedef boost::mpl::list< boost::statechart::custom_reaction<SaveGameDataRequest>, boost::statechart::custom_reaction<SaveGameComplete>, boost::statechart::custom_reaction<AdvanceTurn>, boost::statechart::custom_reaction<TurnUpdate>, boost::statechart::custom_reaction<TurnEnded>, boost::statechart::custom_reaction<PlayerStatus> > PlayingTurn::reactions
Constructor & Destructor Documentation
PlayingTurn::PlayingTurn (my_context ctx)
References Networking::CLIENT_TYPE_HUMAN_OBSERVER, Networking::CLIENT_TYPE_HUMAN_PLAYER, CurrentTurn(), DebugLogger, FlexibleFormat(), GetOptionsDB(), AIInterface::PlayerID(), anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION, and UserString().
PlayingTurn::~PlayingTurn ()
References DebugLogger, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
Member Function Documentation
boost::statechart::result PlayingTurn::react (const SaveGameDataRequest & d)
References DebugLogger, anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION, and UserString().
boost::statechart::result PlayingTurn::react (const SaveGameComplete & d)
References DebugLogger, ExtractMessageData(), FlexibleFormat(), anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION, and UserString().
boost::statechart::result PlayingTurn::react (const AdvanceTurn & d)
boost::statechart::result PlayingTurn::react (const TurnUpdate & msg)
References DebugLogger, anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION, and UserString().
boost::statechart::result PlayingTurn::react (const TurnEnded & d)
References DebugLogger, and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
boost::statechart::result PlayingTurn::react (const PlayerStatus & msg)
References Networking::CLIENT_TYPE_AI_PLAYER, Networking::CLIENT_TYPE_HUMAN_MODERATOR, Networking::CLIENT_TYPE_HUMAN_PLAYER, DebugLogger, ExtractMessageData(), and anonymous_namespace{HumanClientFSM.cpp}::TRACE_EXECUTION.
The documentation for this struct was generated from the following files:
HumanClientFSM.h
HumanClientFSM.cpp