FreeOrion: Effect::CreatePlanet Class Reference
Effect::CreatePlanet Class Reference
#include <Effect.h>
Public Member Functions
CreatePlanet (ValueRef::ValueRefBase< PlanetType > *type, ValueRef::ValueRefBase< PlanetSize > *size, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< EffectBase * > &effects_to_apply_after=std::vector< EffectBase * >())
virtual ~CreatePlanet ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< EffectBase * > m_effects_to_apply_after
ValueRef::ValueRefBase
< std::string > * m_name
ValueRef::ValueRefBase
< PlanetSize > * m_size
ValueRef::ValueRefBase
< PlanetType > * m_type
Friends
class boost::serialization::access
Detailed Description
Creates a new Planet with specified type and size at the system with specified location_id
Constructor & Destructor Documentation
Effect::CreatePlanet::CreatePlanet (ValueRef::ValueRefBase< PlanetType > * type, ValueRef::ValueRefBase< PlanetSize > * size, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< EffectBase * > & effects_to_apply_after = std::vector<EffectBase*>())
Effect::CreatePlanet::~CreatePlanet () virtual
References m_effects_to_apply_after, m_name, m_size, and m_type.
Member Function Documentation
std::string Effect::CreatePlanet::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_name, m_size, and m_type.
void Effect::CreatePlanet::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References Planet::CardinalSuffix(), ValueRef::ConstantExpr(), Universe::CreatePlanet(), ScriptingContext::effect_target, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Effect::EffectBase::Execute(), FlexibleFormat(), System::FreeOrbits(), GetSystem(), GetUniverse(), System::Insert(), INVALID_PLANET_SIZE, m_effects_to_apply_after, m_name, m_size, m_type, UniverseObject::Name(), UniverseObject::Rename(), UniverseObject::SystemID(), UserString(), and UserStringExists().
template<class Archive > void Effect::CreatePlanet::serialize (Archive & ar, const unsigned int version) private
References m_effects_to_apply_after, m_name, m_size, and m_type.
void Effect::CreatePlanet::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_effects_to_apply_after, m_name, m_size, m_type, ValueRef::ValueRefBase< T >::SetTopLevelContent(), and Effect::EffectBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<EffectBase*> Effect::CreatePlanet::m_effects_to_apply_after private
Referenced by Execute(), serialize(), SetTopLevelContent(), and ~CreatePlanet().
ValueRef::ValueRefBase<std::string>* Effect::CreatePlanet::m_name private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreatePlanet().
ValueRef::ValueRefBase<PlanetSize>* Effect::CreatePlanet::m_size private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreatePlanet().
ValueRef::ValueRefBase<PlanetType>* Effect::CreatePlanet::m_type private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreatePlanet().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp