FreeOrion: SystemIcon Class Reference
SystemIcon Class Reference
#include <SystemIcon.h>
Public Member Functions
Structors //!@{
SystemIcon (GG::X x, GG::Y y, GG::X w, int system_id)
construct from a universe ID at specified size and position
~SystemIcon ()
Accessors //!@{
int SystemID () const
returns ID of system this icon represents
const boost::shared_ptr
< GG::Texture > & DiscTexture () const
returns the solid star disc texture
const boost::shared_ptr
< GG::Texture > & HaloTexture () const
returns the transparent star halo texture
const boost::shared_ptr
< GG::Texture > & TinyTexture () const
returns the alternate texture shown when icon very small
virtual bool InWindow (const GG::Pt &pt) const
Overrides GG::Wnd::InWindow. Checks to see if point lies inside in-system fleet buttons before checking main InWindow method.
GG::Pt NthFleetButtonUpperLeft (unsigned int button_number, bool moving) const
returns upper left point of moving or stationary fleetbutton number button_number
int EnclosingCircleDiameter () const
Private Member Functions
void PositionSystemName ()
Private Attributes
OwnerColoredSystemName * m_colored_name
the control that holds the name of the system
boost::shared_ptr< GG::Texture > m_disc_texture
solid star disc texture
boost::shared_ptr< GG::Texture > m_halo_texture
transparent star halo texture
GG::StaticGraphic * m_mouseover_indicator
shown when the mouse cursor is over the system and the system has been explored by the client empire
GG::StaticGraphic * m_mouseover_unexplored_indicator
shown when the mouse cursor is over the system and teh system is unexplored by the client empire
double m_overlay_size
size of extra texture in universe units
boost::shared_ptr< GG::Texture > m_overlay_texture
extra texture drawn over / behind system
bool m_selected
is this icon presently selected / should it show m_selected_indicator
RotatingGraphic * m_selection_indicator
shown to indicate system is selected in sidepanel
bool m_showing_name
is the icon supposed to show its name?
boost::signals2::connection m_system_connection
int m_system_id
the System associated with this SystemIcon
GG::StaticGraphic * m_tiny_graphic
non-scaled texture shown when zoomed far enough out
GG::StaticGraphic * m_tiny_mouseover_indicator
non-scaled indicator shown when showing tiny graphic
RotatingGraphic * m_tiny_selection_indicator
non-scaled indicator shown when showing tiny graphic
boost::shared_ptr< GG::Texture > m_tiny_texture
alternate texture shown when icon very small
Mutators //!@{
boost::signals2::signal< void(int,
GG::Flags< GG::ModKey >
mod_keys)> MouseEnteringSignal
shows/hides the system selection indicator over this system
boost::signals2::signal< void(int)> MouseLeavingSignal
shows/hides the system selection indicator over this system
boost::signals2::signal< void(int)> LeftClickedSignal
shows/hides the system selection indicator over this system
boost::signals2::signal< void(int,
GG::Flags< GG::ModKey >
mod_keys)> RightClickedSignal
shows/hides the system selection indicator over this system
boost::signals2::signal< void(int)> LeftDoubleClickedSignal
shows/hides the system selection indicator over this system
boost::signals2::signal< void(int)> RightDoubleClickedSignal
shows/hides the system selection indicator over this system
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
shows/hides the system selection indicator over this system
virtual void Render ()
shows/hides the system selection indicator over this system
void RenderDisc ()
shows/hides the system selection indicator over this system
void RenderHalo (double scale_factor)
shows/hides the system selection indicator over this system
void RenderOverlay (double zoom_factor)
shows/hides the system selection indicator over this system
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
virtual void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
virtual void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
virtual void RDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
virtual void MouseLeave ()
shows/hides the system selection indicator over this system
virtual void MouseWheel (const GG::Pt &pt, int move, GG::Flags< GG::ModKey > mod_keys)
shows/hides the system selection indicator over this system
void SetSelected (bool selected=true)
shows/hides the system selection indicator over this system
void Refresh ()
Resets system name text and calls RefreshFleetButtons(). Should be called after an icon is attached to the map.
void ShowName ()
enables the system name text
void HideName ()
disables the system name text
Detailed Description
A control that allows interaction with a star system. This class allows user interaction with star systems on the galaxy map. It contains the graphic to display the system, along with the object ID of the UniverseObject associated with it.
Constructor & Destructor Documentation
SystemIcon::SystemIcon (GG::X x, GG::Y y, GG::X w, int system_id)
construct from a universe ID at specified size and position
References ClientUI::ArtDir(), ClientUI::GetClientUI(), ClientUI::GetModuloTexture(), GetSystem(), ClientUI::GetTexture(), ClientUI::HaloStarTypeFilePrefixes(), m_disc_texture, m_halo_texture, m_mouseover_indicator, m_mouseover_unexplored_indicator, m_selection_indicator, m_system_id, m_tiny_graphic, m_tiny_mouseover_indicator, m_tiny_selection_indicator, m_tiny_texture, Refresh(), RotatingGraphic::SetRPM(), ClientUI::StarTypeFilePrefixes(), and ClientUI::SystemSelectionIndicatorRPM().
SystemIcon::~SystemIcon ()
dtor
References m_colored_name, m_mouseover_indicator, m_selection_indicator, m_tiny_graphic, m_tiny_mouseover_indicator, and m_tiny_selection_indicator.
Member Function Documentation
const boost::shared_ptr< GG::Texture > & SystemIcon::DiscTexture () const
returns the solid star disc texture
References m_disc_texture.
Referenced by MapWnd::InitSystemRenderingBuffers().
int SystemIcon::EnclosingCircleDiameter () const
returns diameter of circle enclosing icon around which other icons can be placed and within which the mouse is over the icon
References OptionsDB::Get(), and GetOptionsDB().
Referenced by InWindow(), NthFleetButtonUpperLeft(), PositionSystemName(), and MapWnd::RenderSystems().
const boost::shared_ptr< GG::Texture > & SystemIcon::HaloTexture () const
returns the transparent star halo texture
References m_halo_texture.
Referenced by MapWnd::InitSystemRenderingBuffers().
void SystemIcon::HideName ()
disables the system name text
References m_colored_name, and m_showing_name.
bool SystemIcon::InWindow (const GG::Pt & pt) const virtual
Overrides GG::Wnd::InWindow. Checks to see if point lies inside in-system fleet buttons before checking main InWindow method.
References EnclosingCircleDiameter().
void SystemIcon::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
References LeftClickedSignal, and m_system_id.
void SystemIcon::LDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
References LeftDoubleClickedSignal, and m_system_id.
void SystemIcon::MouseEnter (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
References ClientApp::EmpireID(), OptionsDB::Get(), HumanClientApp::GetApp(), GetEmpire(), GetOptionsDB(), Empire::HasExploredSystem(), m_colored_name, m_mouseover_indicator, m_mouseover_unexplored_indicator, m_showing_name, m_system_id, m_tiny_mouseover_indicator, MouseEnteringSignal, and anonymous_namespace{SystemIcon.cpp}::PlaySystemIconRolloverSound().
void SystemIcon::MouseLeave () virtual
shows/hides the system selection indicator over this system
References m_colored_name, m_mouseover_indicator, m_mouseover_unexplored_indicator, m_showing_name, m_system_id, m_tiny_mouseover_indicator, and MouseLeavingSignal.
void SystemIcon::MouseWheel (const GG::Pt & pt, int move, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
GG::Pt SystemIcon::NthFleetButtonUpperLeft (unsigned int button_number, bool moving) const
returns upper left point of moving or stationary fleetbutton number button_number
References EnclosingCircleDiameter(), ErrorLogger, MapWnd::FleetButtonSizeType(), FleetSizeIcon(), ClientUI::GetClientUI(), ClientUI::GetMapWnd(), anonymous_namespace{SystemIcon.cpp}::MAX_TRIES, anonymous_namespace{SystemIcon.cpp}::PI, and anonymous_namespace{Version.cpp}::retval.
Referenced by MapWnd::DoFleetButtonsLayout().
void SystemIcon::PositionSystemName () private
References EnclosingCircleDiameter(), and m_colored_name.
Referenced by Refresh().
void SystemIcon::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
References m_system_id, and RightClickedSignal.
void SystemIcon::RDoubleClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
shows/hides the system selection indicator over this system
References m_system_id, and RightDoubleClickedSignal.
void SystemIcon::Refresh ()
Resets system name text and calls RefreshFleetButtons(). Should be called after an icon is attached to the map.
References ClientUI::ArtDir(), ClientUI::GetClientUI(), GetSystem(), ClientUI::GetTexture(), m_colored_name, m_overlay_size, m_overlay_texture, m_showing_name, m_system_connection, m_system_id, UniverseObject::Name(), System::OverlaySize(), System::OverlayTexture(), PositionSystemName(), ClientUI::Pts(), anonymous_namespace{ServerWrapper.cpp}::SetName(), and UniverseObject::StateChangedSignal.
Referenced by ShowName(), SizeMove(), and SystemIcon().
void SystemIcon::Render () virtual
shows/hides the system selection indicator over this system
void SystemIcon::RenderDisc ()
shows/hides the system selection indicator over this system
References m_disc_texture.
void SystemIcon::RenderHalo (double scale_factor)
shows/hides the system selection indicator over this system
References m_halo_texture.
void SystemIcon::RenderOverlay (double zoom_factor)
shows/hides the system selection indicator over this system
References m_overlay_size, and m_overlay_texture.
void SystemIcon::SetSelected (bool selected = true)
shows/hides the system selection indicator over this system
References m_selected.
Referenced by MapWnd::InitTurnRendering().
void SystemIcon::ShowName ()
enables the system name text
References m_colored_name, m_showing_name, and Refresh().
void SystemIcon::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
shows/hides the system selection indicator over this system
References OptionsDB::Get(), GetOptionsDB(), m_mouseover_indicator, m_mouseover_unexplored_indicator, m_selected, m_selection_indicator, m_tiny_graphic, m_tiny_mouseover_indicator, m_tiny_selection_indicator, Refresh(), ClientUI::SystemIconSize(), and ClientUI::SystemSelectionIndicatorSize().
int SystemIcon::SystemID () const
returns ID of system this icon represents
References m_system_id.
const boost::shared_ptr< GG::Texture > & SystemIcon::TinyTexture () const
returns the alternate texture shown when icon very small
References m_tiny_texture.
Member Data Documentation
boost::signals2::signal<void (int)> SystemIcon::LeftClickedSignal mutable
shows/hides the system selection indicator over this system
Referenced by MapWnd::InitTurnRendering(), and LClick().
boost::signals2::signal<void (int)> SystemIcon::LeftDoubleClickedSignal mutable
shows/hides the system selection indicator over this system
Referenced by MapWnd::InitTurnRendering(), and LDoubleClick().
OwnerColoredSystemName* SystemIcon::m_colored_name private
the control that holds the name of the system
Referenced by HideName(), MouseEnter(), MouseLeave(), PositionSystemName(), Refresh(), ShowName(), and ~SystemIcon().
boost::shared_ptr<GG::Texture> SystemIcon::m_disc_texture private
solid star disc texture
Referenced by DiscTexture(), RenderDisc(), and SystemIcon().
boost::shared_ptr<GG::Texture> SystemIcon::m_halo_texture private
transparent star halo texture
Referenced by HaloTexture(), RenderHalo(), and SystemIcon().
GG::StaticGraphic* SystemIcon::m_mouseover_indicator private
shown when the mouse cursor is over the system and the system has been explored by the client empire
Referenced by MouseEnter(), MouseLeave(), SizeMove(), SystemIcon(), and ~SystemIcon().
GG::StaticGraphic* SystemIcon::m_mouseover_unexplored_indicator private
shown when the mouse cursor is over the system and teh system is unexplored by the client empire
Referenced by MouseEnter(), MouseLeave(), SizeMove(), and SystemIcon().
double SystemIcon::m_overlay_size private
size of extra texture in universe units
Referenced by Refresh(), and RenderOverlay().
boost::shared_ptr<GG::Texture> SystemIcon::m_overlay_texture private
extra texture drawn over / behind system
Referenced by Refresh(), and RenderOverlay().
bool SystemIcon::m_selected private
is this icon presently selected / should it show m_selected_indicator
Referenced by SetSelected(), and SizeMove().
RotatingGraphic* SystemIcon::m_selection_indicator private
shown to indicate system is selected in sidepanel
Referenced by SizeMove(), SystemIcon(), and ~SystemIcon().
bool SystemIcon::m_showing_name private
is the icon supposed to show its name?
Referenced by HideName(), MouseEnter(), MouseLeave(), Refresh(), and ShowName().
boost::signals2::connection SystemIcon::m_system_connection private
Referenced by Refresh().
int SystemIcon::m_system_id private
the System associated with this SystemIcon
Referenced by LClick(), LDoubleClick(), MouseEnter(), MouseLeave(), RClick(), RDoubleClick(), Refresh(), SystemIcon(), and SystemID().
GG::StaticGraphic* SystemIcon::m_tiny_graphic private
non-scaled texture shown when zoomed far enough out
Referenced by SizeMove(), SystemIcon(), and ~SystemIcon().
GG::StaticGraphic* SystemIcon::m_tiny_mouseover_indicator private
non-scaled indicator shown when showing tiny graphic
Referenced by MouseEnter(), MouseLeave(), SizeMove(), SystemIcon(), and ~SystemIcon().
RotatingGraphic* SystemIcon::m_tiny_selection_indicator private
non-scaled indicator shown when showing tiny graphic
Referenced by SizeMove(), SystemIcon(), and ~SystemIcon().
boost::shared_ptr<GG::Texture> SystemIcon::m_tiny_texture private
alternate texture shown when icon very small
Referenced by SystemIcon(), and TinyTexture().
boost::signals2::signal<void (int, GG::Flags< GG::ModKey > mod_keys)> SystemIcon::MouseEnteringSignal mutable
shows/hides the system selection indicator over this system
Referenced by MapWnd::InitTurnRendering(), and MouseEnter().
boost::signals2::signal<void (int)> SystemIcon::MouseLeavingSignal mutable
shows/hides the system selection indicator over this system
Referenced by MapWnd::InitTurnRendering(), and MouseLeave().
boost::signals2::signal<void (int, GG::Flags< GG::ModKey > mod_keys)> SystemIcon::RightClickedSignal mutable
shows/hides the system selection indicator over this system
Referenced by MapWnd::InitTurnRendering(), and RClick().
boost::signals2::signal<void (int)> SystemIcon::RightDoubleClickedSignal mutable
shows/hides the system selection indicator over this system
Referenced by RDoubleClick().
The documentation for this class was generated from the following files:
SystemIcon.h
SystemIcon.cpp