FreeOrion: MarkupBox::MarkupSurface Class Reference
MarkupBox::MarkupSurface Class Reference
Public Member Functions
Structors
MarkupSurface (GG::X x, GG::Y y, GG::X w, GG::Y h, const std::string &str)
MarkupSurface ()
default ctor
~MarkupSurface ()
dtor
Accessors
const std::string & Text () const
Mutators
void SetText (const std::string &str)
void Clear ()
Removes all controls from surface.
void Refresh ()
Removes and recreates all controls on surface using existing text.
virtual void Render ()
Private Attributes
std::vector< GG::Control * > m_controls
GG::Controls used to display marked up text.
std::string m_text
Constructor & Destructor Documentation
MarkupBox::MarkupSurface::MarkupSurface (GG::X x, GG::Y y, GG::X w, GG::Y h, const std::string & str)
Ctor.
References SetText().
MarkupBox::MarkupSurface::MarkupSurface ()
default ctor
MarkupBox::MarkupSurface::~MarkupSurface ()
dtor
References MarkupBox::Clear().
Member Function Documentation
void MarkupBox::MarkupSurface::Clear ()
Removes all controls from surface.
Referenced by MarkupBox::Clear().
void MarkupBox::MarkupSurface::Refresh ()
Removes and recreates all controls on surface using existing text.
References ClientUI::ArtDir(), anonymous_namespace{MarkupBox.cpp}::EDGE_PAD(), permute_labels::filename, ClientUI::GetFont(), ClientUI::GetTexture(), ClientUI::GetTitleFont(), anonymous_namespace{MarkupBox.cpp}::HEADING_MARKUP, anonymous_namespace{MarkupBox.cpp}::IMAGE_MARKUP, anonymous_namespace{MarkupBox.cpp}::ParseMarkupText(), anonymous_namespace{MarkupBox.cpp}::PLAIN_TEXT_MARKUP, ClientUI::TextColor(), and anonymous_namespace{MarkupBox.cpp}::VERY_FAR_DOWN_LAYOUT_SURFACE().
Referenced by MarkupBox::AdjustScrolls(), and MarkupBox::Refresh().
void MarkupBox::MarkupSurface::Render () virtual
void MarkupBox::MarkupSurface::SetText (const std::string & str)
Removes old controls and recreates new contents of surface from passed str text. If PreserveScrollPositionOnNextTextSet() has been called, does not alter scroll position. Otherwise, resets scroll position to top of contents.
References MarkupBox::Clear(), and MarkupBox::Refresh().
Referenced by MarkupSurface(), and MarkupBox::SetText().
const std::string & MarkupBox::MarkupSurface::Text () const
Referenced by MarkupBox::Text().
Member Data Documentation
std::vector<GG::Control*> MarkupBox::MarkupSurface::m_controls private
GG::Controls used to display marked up text.
std::string MarkupBox::MarkupSurface::m_text private
The documentation for this class was generated from the following file:
MarkupBox.cpp