FreeOrion: Condition Struct Reference
Condition Struct Reference abstract
#include <Condition.h>
Public Types
enum ComparisonType {
INVALID_COMPARISON = -1, EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL,
LESS_THAN, LESS_THAN_OR_EQUAL, NOT_EQUAL
}
enum ContentType {
CONTENT_BUILDING, CONTENT_SPECIES, CONTENT_SHIP_HULL, CONTENT_SHIP_PART,
CONTENT_SPECIAL, CONTENT_FOCUS
}
enum Invariance { UNKNOWN_INVARIANCE, INVARIANT, VARIANT }
typedef std::vector
< TemporaryPtr< const
UniverseObject > > ObjectSet
typedef std::vector
< TemporaryPtr< const
UniverseObject > > ObjectSet
typedef std::vector
< TemporaryPtr< const
UniverseObject > > ObjectSet
enum SearchDomain { NON_MATCHES, MATCHES }
enum SortingMethod { SORT_MAX, SORT_MIN, SORT_MODE, SORT_RANDOM }
Public Member Functions
virtual ~And ()
virtual ~Building ()
virtual ~CanAddStarlaneConnection ()
virtual ~Chance ()
virtual ~ConditionBase ()
virtual ~ContainedBy ()
virtual ~Contains ()
virtual ~CreatedOnTurn ()
virtual ~Described ()
virtual ~DesignHasHull ()
virtual ~DesignHasPart ()
virtual ~DesignHasPartClass ()
virtual ~EmpireAffiliation ()
virtual ~EmpireMeterValue ()
virtual ~EmpireStockpileValue ()
virtual ~Enqueued ()
virtual ~ExploredByEmpire ()
virtual ~FleetSupplyableByEmpire ()
virtual ~FocusType ()
virtual ~HasSpecial ()
virtual ~HasTag ()
virtual ~Homeworld ()
virtual ~InSystem ()
virtual ~Location ()
virtual ~MeterValue ()
virtual ~Not ()
virtual ~Number ()
virtual ~NumberedShipDesign ()
virtual ~ObjectID ()
virtual ~Or ()
virtual ~OrderedBombarded ()
virtual ~OwnerHasBuildingTypeAvailable ()
virtual ~OwnerHasShipDesignAvailable ()
virtual ~OwnerHasTech ()
virtual ~PlanetEnvironment ()
virtual ~PlanetSize ()
virtual ~PlanetType ()
virtual ~PredefinedShipDesign ()
virtual ~ProducedByEmpire ()
virtual ~ResourceSupplyConnectedByEmpire ()
virtual ~ShipPartMeterValue ()
virtual ~SortedNumberOf ()
virtual ~Species ()
virtual ~StarType ()
virtual ~Turn ()
virtual ~Type ()
virtual ~ValueTest ()
virtual ~VisibleToEmpire ()
virtual ~WithinDistance ()
virtual ~WithinStarlaneJumps ()
All ()
And (const std::vector< ConditionBase * > &operands)
Armed ()
Building (const std::vector< ValueRef::ValueRefBase< std::string > * > &names)
CanAddStarlaneConnection (ConditionBase *condition)
CanColonize ()
CanProduceShips ()
const ValueRef::ValueRefBase
< double > * CapacityHigh () const
const ValueRef::ValueRefBase
< double > * CapacityLow () const
Capital ()
Chance (ValueRef::ValueRefBase< double > *chance)
ShipPartClass Class () const
ConditionBase ()
ContainedBy (ConditionBase *condition)
Contains (ConditionBase *condition)
CreatedOnTurn (ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high)
Described (ConditionBase *condition, const std::string &desc_stringtable_key)
virtual std::string Description (bool negated=false) const =0
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
virtual std::string Description (bool negated=false) const
const std::string & DescriptionStringKey () const
DesignHasHull (ValueRef::ValueRefBase< std::string > *name)
DesignHasPart (ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< int > *low=0, ValueRef::ValueRefBase< int > *high=0)
DesignHasPartClass (ShipPartClass part_class, ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high)
const ValueRef::ValueRefBase
< int > * DesignID () const
const ValueRef::ValueRefBase
< int > * DesignID () const
virtual std::string Dump () const =0
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
virtual std::string Dump () const
EmpireAffiliation (ValueRef::ValueRefBase< int > *empire_id, EmpireAffiliationType affiliation=AFFIL_SELF)
EmpireAffiliation (EmpireAffiliationType affiliation)
const ValueRef::ValueRefBase
< int > * EmpireID () const
const ValueRef::ValueRefBase
< int > * EmpireID () const
const ValueRef::ValueRefBase
< int > * EmpireID () const
const ValueRef::ValueRefBase
< int > * EmpireID () const
const ValueRef::ValueRefBase
< int > * EmpireID () const
EmpireMeterValue (const std::string &meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
EmpireMeterValue (ValueRef::ValueRefBase< int > *empire_id, const std::string &meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
EmpireStockpileValue (ResourceType stockpile, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
Enqueued (BuildType build_type, ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< int > *empire_id=0, ValueRef::ValueRefBase< int > *low=0, ValueRef::ValueRefBase< int > *high=0)
Enqueued (ValueRef::ValueRefBase< int > *design_id, ValueRef::ValueRefBase< int > *empire_id=0, ValueRef::ValueRefBase< int > *low=0, ValueRef::ValueRefBase< int > *high=0)
Enqueued ()
const std::vector
< ValueRef::ValueRefBase
< ::PlanetEnvironment > * > & Environments () const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches) const
void Eval (Condition::ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
virtual void Eval (const ScriptingContext &parent_context, Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (Condition::ObjectSet &matches, Condition::ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
ExploredByEmpire (ValueRef::ValueRefBase< int > *empire_id)
FleetSupplyableByEmpire (ValueRef::ValueRefBase< int > *empire_id)
FocusType (const std::vector< ValueRef::ValueRefBase< std::string > * > &names)
EmpireAffiliationType GetAffiliation () const
const ValueRef::ValueRefBase
< std::string > * GetBuildingType () const
BuildType GetBuildType () const
const ValueRef::ValueRefBase
< double > * GetChance () const
ComparisonType GetComparisonType1 () const
ComparisonType GetComparisonType2 () const
const ConditionBase * GetCondition () const
const ConditionBase * GetCondition () const
const ConditionBase * GetCondition () const
const ConditionBase * GetCondition () const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, Condition::ObjectSet &condition_non_targets) const
const ValueRef::ValueRefBase
< int > * GetDesignID () const
MeterType GetMeterType () const
MeterType GetMeterType () const
const ValueRef::ValueRefBase
< std::string > * GetName () const
const ValueRef::ValueRefBase
< std::string > * GetName1 () const
const ValueRef::ValueRefBase
< std::string > * GetName2 () const
SortingMethod GetSortingMethod () const
const ValueRef::ValueRefBase
< UniverseObjectType > * GetType () const
const ValueRef::ValueRefBase
< double > * GetValueRef1 () const
const ValueRef::ValueRefBase
< double > * GetValueRef2 () const
const ValueRef::ValueRefBase
< double > * GetValueRef3 () const
HasSpecial (const std::string &name)
HasSpecial (ValueRef::ValueRefBase< std::string > *name=0)
HasSpecial (ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< int > *since_turn_low, ValueRef::ValueRefBase< int > *since_turn_high=0)
HasSpecial (ValueRef::ValueRefBase< std::string > *name, ValueRef::ValueRefBase< double > *capacity_low, ValueRef::ValueRefBase< double > *capacity_high=0)
HasTag (const std::string &name)
HasTag (ValueRef::ValueRefBase< std::string > *name=0)
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< int > * High () const
const ValueRef::ValueRefBase
< double > * High () const
const ValueRef::ValueRefBase
< double > * High () const
const ValueRef::ValueRefBase
< double > * High () const
const ValueRef::ValueRefBase
< double > * High () const
Homeworld ()
Homeworld (const std::vector< ValueRef::ValueRefBase< std::string > * > &names)
InSystem (ValueRef::ValueRefBase< int > *system_id)
bool LocalCandidateInvariant () const
Location (ContentType content_type, ValueRef::ValueRefBase< std::string > *name1, ValueRef::ValueRefBase< std::string > *name2=0)
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< int > * Low () const
const ValueRef::ValueRefBase
< double > * Low () const
const ValueRef::ValueRefBase
< double > * Low () const
const ValueRef::ValueRefBase
< double > * Low () const
const ValueRef::ValueRefBase
< double > * Low () const
const std::string & Meter () const
MeterValue (MeterType meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
Monster ()
const ValueRef::ValueRefBase
< std::string > * Name () const
ValueRef::ValueRefBase
< std::string > * Name () const
const ValueRef::ValueRefBase
< std::string > * Name () const
const ValueRef::ValueRefBase
< std::string > * Name () const
const ValueRef::ValueRefBase
< std::string > * Name () const
const std::vector
< ValueRef::ValueRefBase
< std::string > * > Names () const
const std::vector
< ValueRef::ValueRefBase
< std::string > * > Names () const
const std::vector
< ValueRef::ValueRefBase
< std::string > * > & Names () const
const std::vector
< ValueRef::ValueRefBase
< std::string > * > & Names () const
None ()
Not (ConditionBase *operand)
Number (ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high, ConditionBase *condition)
const ValueRef::ValueRefBase
< int > * Number () const
NumberedShipDesign (ValueRef::ValueRefBase< int > *design_id)
ObjectID (ValueRef::ValueRefBase< int > *object_id)
const ValueRef::ValueRefBase
< int > * ObjectId () const
const ConditionBase * Operand () const
const std::vector
< ConditionBase * > & Operands () const
const std::vector
< ConditionBase * > & Operands () const
bool operator!= (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
virtual bool operator== (const Condition::ConditionBase &rhs) const
Or (const std::vector< ConditionBase * > &operands)
OrderedBombarded (ConditionBase *by_object_condition)
OwnerHasBuildingTypeAvailable (const std::string &name)
OwnerHasBuildingTypeAvailable (ValueRef::ValueRefBase< std::string > *name)
OwnerHasShipDesignAvailable (int id)
OwnerHasShipDesignAvailable (ValueRef::ValueRefBase< int > *id)
OwnerHasTech (ValueRef::ValueRefBase< std::string > *name)
const ValueRef::ValueRefBase
< std::string > * PartName () const
PlanetEnvironment (const std::vector< ValueRef::ValueRefBase< ::PlanetEnvironment > * > &environments, ValueRef::ValueRefBase< std::string > *species_name_ref=0)
PlanetSize (const std::vector< ValueRef::ValueRefBase< ::PlanetSize > * > &sizes)
PlanetType (const std::vector< ValueRef::ValueRefBase< ::PlanetType > * > &types)
PredefinedShipDesign (ValueRef::ValueRefBase< std::string > *name)
ProducedByEmpire (ValueRef::ValueRefBase< int > *empire_id)
ResourceSupplyConnectedByEmpire (ValueRef::ValueRefBase< int > *empire_id, ConditionBase *condition)
RootCandidate ()
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)=0
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
virtual void SetTopLevelContent (const std::string &content_name)
ShipPartMeterValue (ValueRef::ValueRefBase< std::string > *ship_part_name, MeterType meter, ValueRef::ValueRefBase< double > *low, ValueRef::ValueRefBase< double > *high)
const ValueRef::ValueRefBase
< int > * SinceTurnHigh () const
const ValueRef::ValueRefBase
< int > * SinceTurnLow () const
const std::vector
< ValueRef::ValueRefBase
< ::PlanetSize > * > & Sizes () const
SortedNumberOf (ValueRef::ValueRefBase< int > *number, ConditionBase *condition)
SortedNumberOf (ValueRef::ValueRefBase< int > *number, ValueRef::ValueRefBase< double > *sort_key_ref, SortingMethod sorting_method, ConditionBase *condition)
const ValueRef::ValueRefBase
< double > * SortKey () const
Source ()
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
virtual bool SourceInvariant () const
Species (const std::vector< ValueRef::ValueRefBase< std::string > * > &names)
Species ()
StarType (const std::vector< ValueRef::ValueRefBase< ::StarType > * > &types)
Stationary ()
ResourceType Stockpile () const
const ConditionBase * SubCondition () const
const ValueRef::ValueRefBase
< int > * SystemId () const
Target ()
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
virtual bool TargetInvariant () const
const ValueRef::ValueRefBase
< std::string > * Tech () const
Turn (ValueRef::ValueRefBase< int > *low, ValueRef::ValueRefBase< int > *high=0)
Type (ValueRef::ValueRefBase< UniverseObjectType > *type)
const std::vector
< ValueRef::ValueRefBase
< ::PlanetType > * > & Types () const
const std::vector
< ValueRef::ValueRefBase
< ::StarType > * > & Types () const
ValueTest (ValueRef::ValueRefBase< double > *value_ref1, ComparisonType comp1, ValueRef::ValueRefBase< double > *value_ref2, ComparisonType comp2=INVALID_COMPARISON, ValueRef::ValueRefBase< double > *value_ref3=0)
VisibleToEmpire (ValueRef::ValueRefBase< int > *empire_id)
WithinDistance (ValueRef::ValueRefBase< double > *distance, ConditionBase *condition)
WithinStarlaneJumps (ValueRef::ValueRefBase< int > *jumps, ConditionBase *condition)
Protected Attributes
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
virtual bool Match (const ScriptingContext &local_context) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
EmpireAffiliationType m_affiliation
BuildType m_build_type
ConditionBase * m_by_object_condition
ValueRef::ValueRefBase< double > * m_capacity_high
ValueRef::ValueRefBase< double > * m_capacity_low
ValueRef::ValueRefBase< double > * m_chance
ShipPartClass m_class
ComparisonType m_compare_type1
ComparisonType m_compare_type2
ConditionBase * m_condition
ContentType m_content_type
std::string m_desc_stringtable_key
ValueRef::ValueRefBase< int > * m_design_id
ValueRef::ValueRefBase< double > * m_distance
ValueRef::ValueRefBase< int > * m_empire_id
std::vector
< ValueRef::ValueRefBase
< ::PlanetEnvironment > * > m_environments
ValueRef::ValueRefBase< int > * m_high
ValueRef::ValueRefBase< double > * m_high
ValueRef::ValueRefBase< int > * m_id
ValueRef::ValueRefBase< int > * m_jumps
ValueRef::ValueRefBase< int > * m_low
ValueRef::ValueRefBase< double > * m_low
MeterType m_meter
const std::string m_meter
ValueRef::ValueRefBase
< std::string > * m_name
ValueRef::ValueRefBase
< std::string > * m_name1
ValueRef::ValueRefBase
< std::string > * m_name2
std::vector
< ValueRef::ValueRefBase
< std::string > * > m_names
ValueRef::ValueRefBase< int > * m_number
ValueRef::ValueRefBase< int > * m_object_id
ConditionBase * m_operand
std::vector< ConditionBase * > m_operands
ValueRef::ValueRefBase
< std::string > * m_part_name
ValueRef::ValueRefBase< int > * m_since_turn_high
ValueRef::ValueRefBase< int > * m_since_turn_low
std::vector
< ValueRef::ValueRefBase
< ::PlanetSize > * > m_sizes
ValueRef::ValueRefBase< double > * m_sort_key
SortingMethod m_sorting_method
ValueRef::ValueRefBase
< std::string > * m_species_name
ResourceType m_stockpile
ValueRef::ValueRefBase< int > * m_system_id
ValueRef::ValueRefBase
< UniverseObjectType > * m_type
std::vector
< ValueRef::ValueRefBase
< ::PlanetType > * > m_types
std::vector
< ValueRef::ValueRefBase
< ::StarType > * > m_types
ValueRef::ValueRefBase< double > * m_value_ref1
ValueRef::ValueRefBase< double > * m_value_ref2
ValueRef::ValueRefBase< double > * m_value_ref3
Friends
class boost::serialization::access
struct MatchHelper
Detailed Description
The base class for all Conditions.
Matches all objects if the number of objects that match Condition condition is is >= low and < high. Matched objects may or may not themselves match the condition.
Matches all objects if the current game turn is >= low and < high.
Matches a specified number of objects that match Condition condition or as many objects as match the condition if the number of objects is less than the number requested. If more objects match the condition than are requested, the objects are sorted according to the value of the specified property_name and objects are matched according to whether they have the specified sorting_type of those property values. For example, objects with the largest, smallest or most common property value may be selected preferentially.
Matches all objects.
Matches no objects. Currently only has an experimental use for efficient immediate rejection as the top-line condition. Essentially the entire point of this Condition is to provide the specialized GetDefaultInitialCandidateObjects()
Matches all objects that are owned (if exclusive == false) or only owned (if exclusive == true) by an empire that has affilitation type affilitation with Empire empire_id.
Matches the source object only.
Matches the root candidate object in a condition tree. This is useful within a subcondition to match the object actually being matched by the whole compound condition, rather than an object just being matched in a subcondition in order to evaluate the outer condition.
There is no LocalCandidate condition. To match any local candidate object, use the All condition. Matches the target of an effect being executed.
Matches planets that are a homeworld for any of the species specified in names. If names is empty, matches any planet that is a homeworld for any species in the current game Universe.
Matches planets that are an empire's capital.
Matches space monsters.
Matches armed ships and monsters.
Matches all objects that are of UniverseObjectType type.
Matches all Building objects that are one of the building types specified in names.
Matches all objects that have an attached Special named name.
Matches all objects that have the tag tag.
Matches all objects that were created on turns within the specified range.
Matches all objects that contain an object that matches Condition condition. Container objects are Systems, Planets (which contain Buildings), and Fleets (which contain Ships).
Matches all objects that are contained by an object that matches Condition condition. Container objects are Systems, Planets (which contain Buildings), and Fleets (which contain Ships).
Matches all objects that are in the system with the indicated system_id
Matches the object with the id object_id
Matches all Planet objects that have one of the PlanetTypes in types. Note that all Building objects which are on matching planets are also matched.
Matches all Planet objects that have one of the PlanetSizes in sizes. Note that all Building objects which are on matching planets are also matched.
Matches all Planet objects that have one of the PlanetEnvironments in environments. Note that all Building objects which are on matching planets are also matched.
Matches all planets or ships that have one of the species in species. Note that all Building object which are on matching planets are also matched.
Matches planets where the indicated number of the indicated building type or ship design are enqueued on the production queue.
Matches all ProdCenter objects that have one of the FocusTypes in foci.
Matches all System objects that have one of the StarTypes in types. Note that all objects in matching Systems are also matched (Ships, Fleets, Buildings, Planets, etc.).
Matches all ships whose ShipDesign has the hull specified by name.
Matches all ships whose ShipDesign has >= low and < high of the ship part specified by name.
Matches ships whose ShipDesign has >= low and < high of ship parts of the specified part_class
Matches ships who ShipDesign is a predefined shipdesign with the name name
Matches ships whose design id id.
Matches ships or buildings produced by the empire with id empire_id.
Matches a given object with a linearly distributed probability of chance.
Matches all objects that have a meter of type meter, and whose current value is >= low and <= high.
Matches ships that have a ship part meter of type meter for part part whose current value is >= low and <= high.
Matches all objects if the empire with id empire_id has an empire meter meter whose current value is >= low and <= high.
Matches all objects whose owner's stockpile of stockpile is between low and high, inclusive.
Matches all objects whose owner who has tech name.
Matches all objects whose owner who has the building type name available.
Matches all objects whose owner who has the ship design id available.
Matches all objects that are visible to at least one Empire in empire_ids.
Matches all objects that are within distance units of at least one object that meets condition. Warning: this Condition can slow things down considerably if overused. It is best to use Conditions that yield relatively few matches.
Matches all objects that are within jumps starlane jumps of at least one object that meets condition. Warning: this Condition can slow things down considerably if overused. It is best to use Conditions that yield relatively few matches.
Matches objects that are in systems that could have starlanes added between them and all (not just one) of the systems containing (or that are) one of the objects matched by condition. "Could have starlanes added" means that a lane would be geometrically acceptable, meaning it wouldn't cross any other lanes, pass too close to another system, or be too close in angle to an existing lane.
Matches systems that have been explored by at least one Empire in empire_ids.
Matches objects that are moving. ... What does that mean? Departing this turn, or were located somewhere else last turn...?
Matches objects that are in systems that can be fleet supplied by the empire with id empire_id
Matches objects that are in systems that are connected by resource-sharing to at least one object that meets condition using the resource-sharing network of the empire with id empire_id
Matches objects whose species has the ability to found new colonies.
Matches objects whose species has the ability to produce ships.
Matches the objects that have been targeted for bombardment by at least one object that matches m_by_object_condition.
Matches all objects if the comparisons between values of ValueRefs meet the specified comparison types.
Matches objects that match the location condition of the specified content.
Matches all objects that match every Condition in operands.
Matches all objects that match at least one Condition in operands.
Matches all objects that do not match the Condition operand.
Matches whatever its subcondition matches, but has a customized description string that is returned by Description() by looking up in the stringtable.
Member Typedef Documentation
typedef std::vector<TemporaryPtr<const UniverseObject> > Condition::ObjectSet
typedef std::vector<TemporaryPtr<const UniverseObject> > Condition::ObjectSet
typedef std::vector<TemporaryPtr<const UniverseObject> > Condition::ObjectSet
Member Enumeration Documentation
enum Condition::ComparisonType
Enumerator
INVALID_COMPARISON
EQUAL
GREATER_THAN
GREATER_THAN_OR_EQUAL
LESS_THAN
LESS_THAN_OR_EQUAL
NOT_EQUAL
enum Condition::ContentType
Enumerator
CONTENT_BUILDING
CONTENT_SPECIES
CONTENT_SHIP_HULL
CONTENT_SHIP_PART
CONTENT_SPECIAL
CONTENT_FOCUS
enum Condition::Invariance
Enumerator
UNKNOWN_INVARIANCE
This condition hasn't yet calculated this invariance type.
INVARIANT
This condition is invariant to a particular type of object change.
VARIANT
This condition's result depends on the state of a particular object.
enum Condition::SearchDomain
Enumerator
NON_MATCHES
The Condition will only examine items in the non matches set; those that match the Condition will be inserted into the matches set.
MATCHES
The Condition will only examine items in the matches set; those that do not match the Condition will be inserted into the nonmatches set.
enum Condition::SortingMethod
Enumerator
SORT_MAX
Objects with the largest sort key will be selected.
SORT_MIN
Objects with the smallest sort key will be selected.
SORT_MODE
Objects with the most common sort key will be selected.
SORT_RANDOM
Objects will be selected randomly, without consideration of property values.
Constructor & Destructor Documentation
virtual Condition::~ConditionBase () virtual
virtual Condition::~Number () virtual
virtual Condition::~Turn () virtual
virtual Condition::~SortedNumberOf () virtual
virtual Condition::~EmpireAffiliation () virtual
virtual Condition::~Homeworld () virtual
virtual Condition::~Type () virtual
virtual Condition::~Building () virtual
virtual Condition::~HasSpecial () virtual
virtual Condition::~HasTag () virtual
virtual Condition::~CreatedOnTurn () virtual
virtual Condition::~Contains () virtual
virtual Condition::~ContainedBy () virtual
virtual Condition::~InSystem () virtual
virtual Condition::~ObjectID () virtual
virtual Condition::~PlanetType () virtual
virtual Condition::~PlanetSize () virtual
virtual Condition::~PlanetEnvironment () virtual
virtual Condition::~Species () virtual
virtual Condition::~Enqueued () virtual
virtual Condition::~FocusType () virtual
virtual Condition::~StarType () virtual
virtual Condition::~DesignHasHull () virtual
virtual Condition::~DesignHasPart () virtual
virtual Condition::~DesignHasPartClass () virtual
virtual Condition::~PredefinedShipDesign () virtual
virtual Condition::~NumberedShipDesign () virtual
virtual Condition::~ProducedByEmpire () virtual
virtual Condition::~Chance () virtual
virtual Condition::~MeterValue () virtual
virtual Condition::~ShipPartMeterValue () virtual
virtual Condition::~EmpireMeterValue () virtual
virtual Condition::~EmpireStockpileValue () virtual
virtual Condition::~OwnerHasTech () virtual
virtual Condition::~OwnerHasBuildingTypeAvailable () virtual
virtual Condition::~OwnerHasShipDesignAvailable () virtual
virtual Condition::~VisibleToEmpire () virtual
virtual Condition::~WithinDistance () virtual
virtual Condition::~WithinStarlaneJumps () virtual
virtual Condition::~CanAddStarlaneConnection () virtual
virtual Condition::~ExploredByEmpire () virtual
virtual Condition::~FleetSupplyableByEmpire () virtual
virtual Condition::~ResourceSupplyConnectedByEmpire () virtual
virtual Condition::~OrderedBombarded () virtual
virtual Condition::~ValueTest () virtual
virtual Condition::~Location () virtual
virtual Condition::~And () virtual
virtual Condition::~Or () virtual
virtual Condition::~Not () virtual
virtual Condition::~Described () virtual
Member Function Documentation
Condition::All () inline
Referenced by BOOST_AUTO_TEST_CASE(), ConditionWidget::ConditionWidget(), ConditionWidget::GetCondition(), and ObjectListBox::ObjectListBox().
Condition::And (const std::vector< ConditionBase * > & operands) inline
Referenced by ConditionDescription(), anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest(), anonymous_namespace{Condition.cpp}::FlattenAndNestedConditions(), ConditionWidget::GetCondition(), and Species::Location().
Condition::Armed () inline
Referenced by ConditionWidget::GetCondition().
Condition::Building (const std::vector< ValueRef::ValueRefBase< std::string > * > & names) inline explicit
Condition::CanAddStarlaneConnection (ConditionBase * condition) inline explicit
Condition::CanColonize () inline explicit
Referenced by ConditionWidget::GetCondition(), and anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().
Condition::CanProduceShips () inline
Referenced by ConditionWidget::GetCondition(), and anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().
const ValueRef::ValueRefBase<double>* Condition::CapacityHigh () const inline
const ValueRef::ValueRefBase<double>* Condition::CapacityLow () const inline
Condition::Capital () inline
Referenced by ConditionWidget::GetCondition().
Condition::Chance (ValueRef::ValueRefBase< double > * chance) inline
ShipPartClass Condition::Class () const inline
Condition::ConditionBase () inline
Referenced by Planet::AvailableFoci(), anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest(), ConditionWidget::ConditionWidget(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::ConditionCache::Find(), Species::Location(), anonymous_namespace{ServerWrapper.cpp}::MonsterFleetPlanWrapper::Location(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator()(), PartALocationSubsumesPartB(), and anonymous_namespace{ServerWrapper.cpp}::SpecialLocation().
Condition::ContainedBy (ConditionBase * condition) inline
Referenced by ConditionWidget::GetCondition().
Condition::Contains (ConditionBase * condition) inline
Referenced by ConditionWidget::GetCondition().
Condition::CreatedOnTurn (ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high) inline
Condition::Described (ConditionBase * condition, const std::string & desc_stringtable_key) inline
virtual std::string Condition::Description (bool negated = false) const pure virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
virtual std::string Condition::Description (bool negated = false) const virtual
const std::string& Condition::DescriptionStringKey () const inline
Condition::DesignHasHull (ValueRef::ValueRefBase< std::string > * name) inline explicit
Condition::DesignHasPart (ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< int > * low = 0, ValueRef::ValueRefBase< int > * high = 0) inline
Condition::DesignHasPartClass (ShipPartClass part_class, ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high) inline
const ValueRef::ValueRefBase<int>* Condition::DesignID () const inline
const ValueRef::ValueRefBase<int>* Condition::DesignID () const inline
virtual std::string Condition::Dump () const pure virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const virtual
virtual std::string Condition::Dump () const inline virtual
Condition::EmpireAffiliation (ValueRef::ValueRefBase< int > * empire_id, EmpireAffiliationType affiliation = AFFIL_SELF) inline explicit
Referenced by ConditionWidget::GetCondition().
Condition::EmpireAffiliation (EmpireAffiliationType affiliation) inline explicit
const ValueRef::ValueRefBase<int>* Condition::EmpireID () const inline
const ValueRef::ValueRefBase<int>* Condition::EmpireID () const inline
const ValueRef::ValueRefBase<int>* Condition::EmpireID () const inline
const ValueRef::ValueRefBase<int>* Condition::EmpireID () const inline
const ValueRef::ValueRefBase<int>* Condition::EmpireID () const inline
Condition::EmpireMeterValue (const std::string & meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Condition::EmpireMeterValue (ValueRef::ValueRefBase< int > * empire_id, const std::string & meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Condition::EmpireStockpileValue (ResourceType stockpile, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Condition::Enqueued (BuildType build_type, ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< int > * empire_id = 0, ValueRef::ValueRefBase< int > * low = 0, ValueRef::ValueRefBase< int > * high = 0) inline
Condition::Enqueued (ValueRef::ValueRefBase< int > * design_id, ValueRef::ValueRefBase< int > * empire_id = 0, ValueRef::ValueRefBase< int > * low = 0, ValueRef::ValueRefBase< int > * high = 0) inline explicit
Condition::Enqueued () inline
const std::vector<ValueRef::ValueRefBase< ::PlanetEnvironment>*>& Condition::Environments () const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const
Matches with an empty ScriptingContext
void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches) const
Tests all objects in universe as NON_MATCHES.
void Condition::Eval (Condition::ObjectSet & matches) const
Tests all objects in universe as NON_MATCHES with empty ScriptingContext.
bool Condition::Eval (const ScriptingContext & parent_context, TemporaryPtr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
bool Condition::Eval (TemporaryPtr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
virtual void Condition::Eval (const ScriptingContext & parent_context, Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
void Condition::Eval (Condition::ObjectSet & matches, Condition::ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
Condition::ExploredByEmpire (ValueRef::ValueRefBase< int > * empire_id) inline explicit
Condition::FleetSupplyableByEmpire (ValueRef::ValueRefBase< int > * empire_id) inline explicit
Condition::FocusType (const std::vector< ValueRef::ValueRefBase< std::string > * > & names) inline
Referenced by ConditionWidget::GetCondition().
EmpireAffiliationType Condition::GetAffiliation () const inline
const ValueRef::ValueRefBase<std::string>* Condition::GetBuildingType () const inline
BuildType Condition::GetBuildType () const inline
const ValueRef::ValueRefBase<double>* Condition::GetChance () const inline
ComparisonType Condition::GetComparisonType1 () const inline
ComparisonType Condition::GetComparisonType2 () const inline
const ConditionBase* Condition::GetCondition () const inline
const ConditionBase* Condition::GetCondition () const inline
const ConditionBase* Condition::GetCondition () const inline
const ConditionBase* Condition::GetCondition () const inline
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const inline virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const
void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const
void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const
virtual void Condition::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, Condition::ObjectSet & condition_non_targets) const virtual
const ValueRef::ValueRefBase<int>* Condition::GetDesignID () const inline
MeterType Condition::GetMeterType () const inline
MeterType Condition::GetMeterType () const inline
const ValueRef::ValueRefBase<std::string>* Condition::GetName () const inline
const ValueRef::ValueRefBase<std::string>* Condition::GetName1 () const inline
const ValueRef::ValueRefBase<std::string>* Condition::GetName2 () const inline
SortingMethod Condition::GetSortingMethod () const inline
const ValueRef::ValueRefBase<UniverseObjectType>* Condition::GetType () const inline
const ValueRef::ValueRefBase<double>* Condition::GetValueRef1 () const inline
const ValueRef::ValueRefBase<double>* Condition::GetValueRef2 () const inline
const ValueRef::ValueRefBase<double>* Condition::GetValueRef3 () const inline
Condition::HasSpecial (const std::string & name) explicit
Referenced by ConditionWidget::GetCondition().
Condition::HasSpecial (ValueRef::ValueRefBase< std::string > * name = 0) inline explicit
Condition::HasSpecial (ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< int > * since_turn_low, ValueRef::ValueRefBase< int > * since_turn_high = 0) inline
Condition::HasSpecial (ValueRef::ValueRefBase< std::string > * name, ValueRef::ValueRefBase< double > * capacity_low, ValueRef::ValueRefBase< double > * capacity_high = 0) inline
Condition::HasTag (const std::string & name) explicit
Referenced by ConditionWidget::GetCondition().
Condition::HasTag (ValueRef::ValueRefBase< std::string > * name = 0) inline explicit
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<int>* Condition::High () const inline
const ValueRef::ValueRefBase<double>* Condition::High () const inline
const ValueRef::ValueRefBase<double>* Condition::High () const inline
const ValueRef::ValueRefBase<double>* Condition::High () const inline
const ValueRef::ValueRefBase<double>* Condition::High () const inline
Condition::Homeworld () inline
Referenced by ConditionWidget::GetCondition().
Condition::Homeworld (const std::vector< ValueRef::ValueRefBase< std::string > * > & names) inline explicit
Condition::InSystem (ValueRef::ValueRefBase< int > * system_id) inline
bool Condition::LocalCandidateInvariant () const inline
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition. This funciton is provided for consistency with ValueRef, which may not depend on the local candidiate of an enclosing condition.
Condition::Location (ContentType content_type, ValueRef::ValueRefBase< std::string > * name1, ValueRef::ValueRefBase< std::string > * name2 = 0) inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<int>* Condition::Low () const inline
const ValueRef::ValueRefBase<double>* Condition::Low () const inline
const ValueRef::ValueRefBase<double>* Condition::Low () const inline
const ValueRef::ValueRefBase<double>* Condition::Low () const inline
const ValueRef::ValueRefBase<double>* Condition::Low () const inline
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
virtual bool Condition::Match (const ScriptingContext & local_context) const private virtual
const std::string& Condition::Meter () const inline
Condition::MeterValue (MeterType meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
Referenced by ConditionWidget::GetCondition().
Condition::Monster () inline
Referenced by ConditionWidget::GetCondition().
const ValueRef::ValueRefBase<std::string>* Condition::Name () const inline
ValueRef::ValueRefBase<std::string>* Condition::Name () const inline
const ValueRef::ValueRefBase<std::string>* Condition::Name () const inline
const ValueRef::ValueRefBase<std::string>* Condition::Name () const inline
const ValueRef::ValueRefBase<std::string>* Condition::Name () const inline
const std::vector<ValueRef::ValueRefBase<std::string>*> Condition::Names () const inline
const std::vector<ValueRef::ValueRefBase<std::string>*> Condition::Names () const inline
const std::vector<ValueRef::ValueRefBase<std::string>*>& Condition::Names () const inline
const std::vector<ValueRef::ValueRefBase<std::string>*>& Condition::Names () const inline
Condition::None () inline
Condition::Not (ConditionBase * operand) inline
Referenced by ConditionWidget::GetCondition(), and Species::Location().
Condition::Number (ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high, ConditionBase * condition) inline
const ValueRef::ValueRefBase<int>* Condition::Number () const inline
Condition::NumberedShipDesign (ValueRef::ValueRefBase< int > * design_id) inline
Condition::ObjectID (ValueRef::ValueRefBase< int > * object_id) inline
const ValueRef::ValueRefBase<int>* Condition::ObjectId () const inline
const ConditionBase* Condition::Operand () const inline
const std::vector<ConditionBase*>& Condition::Operands () const inline
const std::vector<ConditionBase*>& Condition::Operands () const inline
bool Condition::operator!= (const Condition::ConditionBase & rhs) const inline
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
virtual bool Condition::operator== (const Condition::ConditionBase & rhs) const virtual
Condition::Or (const std::vector< ConditionBase * > & operands) inline
Referenced by ConditionWidget::GetCondition().
Condition::OrderedBombarded (ConditionBase * by_object_condition) inline
Condition::OwnerHasBuildingTypeAvailable (const std::string & name) explicit
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::EnqueueAndLocationConditionDescription(), and anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().
Condition::OwnerHasBuildingTypeAvailable (ValueRef::ValueRefBase< std::string > * name) inline explicit
Condition::OwnerHasShipDesignAvailable (int id) explicit
Referenced by anonymous_namespace{BuildDesignatorWnd.cpp}::LocationConditionDescription().
Condition::OwnerHasShipDesignAvailable (ValueRef::ValueRefBase< int > * id) inline explicit
Condition::OwnerHasTech (ValueRef::ValueRefBase< std::string > * name) inline explicit
const ValueRef::ValueRefBase<std::string>* Condition::PartName () const inline
Condition::PlanetEnvironment (const std::vector< ValueRef::ValueRefBase< ::PlanetEnvironment > * > & environments, ValueRef::ValueRefBase< std::string > * species_name_ref = 0) inline
Referenced by Species::Location().
Condition::PlanetSize (const std::vector< ValueRef::ValueRefBase< ::PlanetSize > * > & sizes) inline
Referenced by ConditionWidget::GetCondition().
Condition::PlanetType (const std::vector< ValueRef::ValueRefBase< ::PlanetType > * > & types) inline
Referenced by ConditionWidget::GetCondition().
Condition::PredefinedShipDesign (ValueRef::ValueRefBase< std::string > * name) inline explicit
Condition::ProducedByEmpire (ValueRef::ValueRefBase< int > * empire_id) inline
Condition::ResourceSupplyConnectedByEmpire (ValueRef::ValueRefBase< int > * empire_id, ConditionBase * condition) inline
Condition::RootCandidate () inline
virtual bool Condition::RootCandidateInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const inline virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
virtual bool Condition::RootCandidateInvariant () const virtual
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
template<class Archive > void Condition::serialize (Archive & ar, const unsigned int version) private
virtual void Condition::SetTopLevelContent (const std::string & content_name) pure virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) inline virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
virtual void Condition::SetTopLevelContent (const std::string & content_name) virtual
Condition::ShipPartMeterValue (ValueRef::ValueRefBase< std::string > * ship_part_name, MeterType meter, ValueRef::ValueRefBase< double > * low, ValueRef::ValueRefBase< double > * high) inline
const ValueRef::ValueRefBase<int>* Condition::SinceTurnHigh () const inline
const ValueRef::ValueRefBase<int>* Condition::SinceTurnLow () const inline
const std::vector<ValueRef::ValueRefBase< ::PlanetSize>*>& Condition::Sizes () const inline
Condition::SortedNumberOf (ValueRef::ValueRefBase< int > * number, ConditionBase * condition) inline
Sorts randomly, without considering a sort key.
Condition::SortedNumberOf (ValueRef::ValueRefBase< int > * number, ValueRef::ValueRefBase< double > * sort_key_ref, SortingMethod sorting_method, ConditionBase * condition) inline
Sorts according to the specified method, based on the key values evaluated for each object.
const ValueRef::ValueRefBase<double>* Condition::SortKey () const inline
Condition::Source () inline
Referenced by anonymous_namespace{Field.cpp}::IncreaseMeter(), and anonymous_namespace{ShipDesign.cpp}::IncreaseMeter().
virtual bool Condition::SourceInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the source object.
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const inline virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
virtual bool Condition::SourceInvariant () const virtual
Condition::Species (const std::vector< ValueRef::ValueRefBase< std::string > * > & names) inline
Condition::Species () inline
Referenced by ConditionWidget::GetCondition().
Condition::StarType (const std::vector< ValueRef::ValueRefBase< ::StarType > * > & types) inline
Referenced by ConditionWidget::GetCondition().
Condition::Stationary () inline explicit
Referenced by ConditionWidget::GetCondition().
ResourceType Condition::Stockpile () const inline
const ConditionBase* Condition::SubCondition () const inline
const ValueRef::ValueRefBase<int>* Condition::SystemId () const inline
Condition::Target () inline
virtual bool Condition::TargetInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the target object.
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const inline virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
virtual bool Condition::TargetInvariant () const virtual
const ValueRef::ValueRefBase<std::string>* Condition::Tech () const inline
Condition::Turn (ValueRef::ValueRefBase< int > * low, ValueRef::ValueRefBase< int > * high = 0) inline explicit
Condition::Type (ValueRef::ValueRefBase< UniverseObjectType > * type) inline explicit
Referenced by ConditionWidget::GetCondition(), and Species::Location().
const std::vector<ValueRef::ValueRefBase< ::PlanetType>*>& Condition::Types () const inline
const std::vector<ValueRef::ValueRefBase< ::StarType>*>& Condition::Types () const inline
Condition::ValueTest (ValueRef::ValueRefBase< double > * value_ref1, ComparisonType comp1, ValueRef::ValueRefBase< double > * value_ref2, ComparisonType comp2 = INVALID_COMPARISON, ValueRef::ValueRefBase< double > * value_ref3 = 0) inline
Condition::VisibleToEmpire (ValueRef::ValueRefBase< int > * empire_id) inline explicit
Condition::WithinDistance (ValueRef::ValueRefBase< double > * distance, ConditionBase * condition) inline
Condition::WithinStarlaneJumps (ValueRef::ValueRefBase< int > * jumps, ConditionBase * condition) inline
Friends And Related Function Documentation
boost::serialization::access friend
friend struct MatchHelper friend
Member Data Documentation
EmpireAffiliationType Condition::m_affiliation private
BuildType Condition::m_build_type private
ConditionBase* Condition::m_by_object_condition private
ValueRef::ValueRefBase<double>* Condition::m_capacity_high private
ValueRef::ValueRefBase<double>* Condition::m_capacity_low private
ValueRef::ValueRefBase<double>* Condition::m_chance private
ShipPartClass Condition::m_class private
ComparisonType Condition::m_compare_type1 private
ComparisonType Condition::m_compare_type2 private
ConditionBase * Condition::m_condition private
ContentType Condition::m_content_type private
std::string Condition::m_desc_stringtable_key private
ValueRef::ValueRefBase< int > * Condition::m_design_id private
ValueRef::ValueRefBase<double>* Condition::m_distance private
ValueRef::ValueRefBase< int > * Condition::m_empire_id private
std::vector<ValueRef::ValueRefBase< ::PlanetEnvironment>*> Condition::m_environments private
ValueRef::ValueRefBase< double > * Condition::m_high private
ValueRef::ValueRefBase<double>* Condition::m_high private
ValueRef::ValueRefBase<int>* Condition::m_id private
ValueRef::ValueRefBase<int>* Condition::m_jumps private
ValueRef::ValueRefBase< double > * Condition::m_low private
ValueRef::ValueRefBase<double>* Condition::m_low private
MeterType Condition::m_meter private
const std::string Condition::m_meter private
ValueRef::ValueRefBase< std::string > * Condition::m_name private
ValueRef::ValueRefBase<std::string>* Condition::m_name1 private
ValueRef::ValueRefBase<std::string>* Condition::m_name2 private
std::vector< ValueRef::ValueRefBase< std::string > * > Condition::m_names private
ValueRef::ValueRefBase<int>* Condition::m_number private
ValueRef::ValueRefBase<int>* Condition::m_object_id private
ConditionBase* Condition::m_operand private
std::vector< ConditionBase * > Condition::m_operands private
ValueRef::ValueRefBase<std::string>* Condition::m_part_name private
Invariance Condition::m_root_candidate_invariant mutable protected
ValueRef::ValueRefBase<int>* Condition::m_since_turn_high private
ValueRef::ValueRefBase<int>* Condition::m_since_turn_low private
std::vector<ValueRef::ValueRefBase< ::PlanetSize>*> Condition::m_sizes private
ValueRef::ValueRefBase<double>* Condition::m_sort_key private
SortingMethod Condition::m_sorting_method private
Invariance Condition::m_source_invariant mutable protected
ValueRef::ValueRefBase<std::string>* Condition::m_species_name private
ResourceType Condition::m_stockpile private
ValueRef::ValueRefBase<int>* Condition::m_system_id private
Invariance Condition::m_target_invariant mutable protected
ValueRef::ValueRefBase<UniverseObjectType>* Condition::m_type private
std::vector<ValueRef::ValueRefBase< ::PlanetType>*> Condition::m_types private
std::vector<ValueRef::ValueRefBase< ::StarType>*> Condition::m_types private
ValueRef::ValueRefBase<double>* Condition::m_value_ref1 private
ValueRef::ValueRefBase<double>* Condition::m_value_ref2 private
ValueRef::ValueRefBase<double>* Condition::m_value_ref3 private
The documentation for this struct was generated from the following files:
Condition.h
Effect.h
Universe.h