FreeOrion: CombatLogWnd Class Reference
CombatLogWnd Class Reference
Displays a textual log of combat events.
#include <CombatLogWnd.h>
Public Member Functions
CombatLogWnd ()
void SetLog (int log_id)
Set which log to show.
Public Member Functions inherited from CUILinkTextMultiEdit
CUILinkTextMultiEdit (const std::string &str, GG::Flags< GG::MultiEditStyle > style=GG::MULTI_LINEWRAP)
basic ctor
virtual const std::vector
< GG::Font::LineData > & GetLineData () const
virtual const
boost::shared_ptr< GG::Font > & GetFont () const
virtual GG::Pt TextUpperLeft () const
virtual GG::Pt TextLowerRight () const
virtual const std::string & RawText () const
returns text being displayed before any link formatting is added
virtual void Render ()
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LDoubleClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseLeave ()
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
virtual void SetText (const std::string &str)
Public Member Functions inherited from CUIMultiEdit
CUIMultiEdit (const std::string &str, GG::Flags< GG::MultiEditStyle > style=GG::MULTI_LINEWRAP)
basic ctor
Public Member Functions inherited from TextLinker
void SetDecorator (const std::string &link_type, LinkDecorator *decorator)
link clicked signals: first string is the link type, second string is the specific item clicked
TextLinker ()
virtual ~TextLinker ()
Additional Inherited Members
Public Attributes inherited from TextLinker
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkDoubleClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkRightClickedSignal
Static Public Attributes inherited from TextLinker
static const std::string ENCYCLOPEDIA_TAG
static const std::string GRAPH_TAG
Protected Member Functions inherited from TextLinker
void FindLinks ()
finds the links in the text, with which to populate m_links.
int GetLinkUnderPt (const GG::Pt &pt)
returns the index of the link under screen coordinate pt, or -1 if none
void LClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LDoubleClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LocateLinks ()
calculates the physical locations of the links in m_links
void MarkLinks ()
wraps text for each link in text formatting tags so that the links appear visually distinct from other text
void MouseHere_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void MouseLeave_ ()
void RClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void Render_ ()
Detailed Description
Displays a textual log of combat events.
Constructor & Destructor Documentation
CombatLogWnd::CombatLogWnd ()
References VarText::PLANET_ID_TAG, TextLinker::SetDecorator(), and VarText::SHIP_ID_TAG.
Member Function Documentation
void CombatLogWnd::SetLog (int log_id)
Set which log to show.
References ClientUI::ArtDir(), CombatLog::combat_events, CombatLogAvailable(), anonymous_namespace{CombatLogWnd.cpp}::CountByOwner(), anonymous_namespace{CombatLogWnd.cpp}::CountsToText(), DebugLogger, CombatLog::destroyed_object_ids, anonymous_namespace{CombatLogWnd.cpp}::EmpireColourWrappedText(), ClientApp::EmpireID(), ErrorLogger, FlexibleFormat(), HumanClientApp::GetApp(), GetCombatLog(), GetEmpire(), GetSystem(), ClientUI::GetTexture(), GetUniverseObject(), LinkTaggedIDText(), CombatLog::object_ids, UniverseObject::ObjectType(), UniverseObject::PublicName(), anonymous_namespace{CombatLogWnd.cpp}::PublicNameLink(), CUILinkTextMultiEdit::SetText(), CombatLog::system_id, VarText::SYSTEM_ID_TAG, CombatLog::turn, and UserString().
Referenced by CombatReportWnd::CombatReportPrivate::SetLog().
The documentation for this class was generated from the following files:
CombatLogWnd.h
CombatLogWnd.cpp