FreeOrion: Effect::EffectBase Class Reference
Effect::EffectBase Class Reference abstract
#include <Effect.h>
Public Member Functions
virtual ~EffectBase ()
virtual std::string Description () const =0
virtual std::string Dump () const =0
virtual void Execute (const ScriptingContext &context) const =0
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
virtual void SetTopLevelContent (const std::string &content_name)=0
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
Detailed Description
The base class for all Effects. When an Effect is executed, the source object (the object to which the Effect or its containing EffectGroup is attached) and the target object are both required. Note that this means that ValueRefs contained within Effects can refer to values in either the source or target objects.
Constructor & Destructor Documentation
Effect::EffectBase::~EffectBase () virtual
Member Function Documentation
virtual std::string Effect::EffectBase::Description () const pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
virtual std::string Effect::EffectBase::Dump () const pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
Referenced by Execute().
virtual void Effect::EffectBase::Execute (const ScriptingContext & context) const pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
Referenced by Execute(), Effect::SetMeter::Execute(), Effect::SetShipPartMeter::Execute(), Effect::CreatePlanet::Execute(), Effect::CreateBuilding::Execute(), Effect::CreateShip::Execute(), Effect::CreateField::Execute(), and Effect::CreateSystem::Execute().
void Effect::EffectBase::Execute (const ScriptingContext & context, const TargetSet & targets) const virtual
Reimplemented in Effect::SetShipPartMeter, and Effect::SetMeter.
References ScriptingContext::effect_target, and Execute().
void Effect::EffectBase::Execute (const TargetsCauses & targets_causes, bool stacking, AccountingMap * accounting_map = 0, bool only_meter_effects = false, bool only_appearance_effects = false, bool include_empire_meter_effects = false, bool only_generate_sitrep_effects = false) const virtual
References Effect::EffectCause::cause_type, Meter::Current(), Effect::EffectCause::custom_label, DebugLogger, Dump(), Effect::TargetsAndCause::effect_cause, Execute(), OptionsDB::Get(), UniverseObject::GetMeter(), Effect::SetMeter::GetMeterType(), Effect::SetShipPartMeter::GetMeterType(), GetOptionsDB(), Ship::GetPartMeter(), Effect::SetShipPartMeter::GetPartName(), GetUniverseObject(), UniverseObject::ID(), INVALID_METER_TYPE, Effect::AccountingInfo::meter_change, UniverseObject::ObjectType(), Effect::AccountingInfo::running_meter_total, Effect::AccountingInfo::source_id, Effect::SourcedEffectsGroup::source_object_id, Effect::EffectCause::specific_cause, boost::static_pointer_cast(), and Effect::TargetsAndCause::target_set.
template<class Archive > void Effect::EffectBase::serialize (Archive & ar, const unsigned int version) private
virtual void Effect::EffectBase::SetTopLevelContent (const std::string & content_name) pure virtual
Implemented in Effect::Conditional, Effect::SetVisibility, Effect::SetTexture, Effect::SetOverlayTexture, Effect::GenerateSitRepMessage, Effect::GiveEmpireTech, Effect::SetEmpireTechProgress, Effect::Victory, Effect::SetAggression, Effect::SetDestination, Effect::MoveTowards, Effect::MoveInOrbit, Effect::MoveTo, Effect::SetStarType, Effect::RemoveStarlanes, Effect::AddStarlanes, Effect::RemoveSpecial, Effect::AddSpecial, Effect::Destroy, Effect::CreateSystem, Effect::CreateField, Effect::CreateShip, Effect::CreateBuilding, Effect::CreatePlanet, Effect::SetSpeciesSpeciesOpinion, Effect::SetSpeciesEmpireOpinion, Effect::SetOwner, Effect::SetSpecies, Effect::SetPlanetSize, Effect::SetPlanetType, Effect::SetEmpireCapital, Effect::SetEmpireStockpile, Effect::SetEmpireMeter, Effect::SetShipPartMeter, and Effect::SetMeter.
Referenced by Effect::CreatePlanet::SetTopLevelContent(), Effect::CreateBuilding::SetTopLevelContent(), Effect::CreateShip::SetTopLevelContent(), Effect::CreateField::SetTopLevelContent(), and Effect::CreateSystem::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp