FreeOrion: parse::lexer Struct Reference
parse::lexer Struct Reference
#include <Lexer.h>
Public Member Functions
const
boost::spirit::lex::token_def
< const char * > & name_token (const char *name) const
Static Public Member Functions
static const lexer & instance ()
Public Attributes
Comment tokens
boost::spirit::lex::token_def
< boost::spirit::lex::omit > inline_comment
boost::spirit::lex::token_def
< boost::spirit::lex::omit > end_of_line_comment
Tokens for common C++ types and builtins.
boost::spirit::lex::token_def
< bool > bool_
boost::spirit::lex::token_def
< int > int_
boost::spirit::lex::token_def
< double > double_
boost::spirit::lex::token_def
< std::string > string
Error token.
boost::spirit::lex::token_def
< boost::spirit::lex::omit > error_token
Static Public Attributes
static const char * bool_regex = "(?i:true|false)"
static const char * double_regex = "\\d+\\.\\d*|\\d*\\.\\d+"
static const char * int_regex = "\\d+"
static const char * string_regex = "\\\"[^\\\"]*\\\""
Private Member Functions
lexer ()
Private Attributes
std::map< const char
*, boost::spirit::lex::token_def
< const char * > * > m_name_tokens
Detailed Description
The script file lexer.
Constructor & Destructor Documentation
lexer::lexer () private
Ctor.
References anonymous_namespace{EnumParser.cpp}::_val, bool_, double_, end_of_line_comment, error_token, inline_comment, int_, REGISTER_TOKEN, anonymous_namespace{Lexer.cpp}::strip_quotes, TOKEN_SEQ_1, TOKEN_SEQ_10, TOKEN_SEQ_11, TOKEN_SEQ_12, TOKEN_SEQ_13, TOKEN_SEQ_14, TOKEN_SEQ_2, TOKEN_SEQ_3, TOKEN_SEQ_4, TOKEN_SEQ_5, TOKEN_SEQ_6, TOKEN_SEQ_7, TOKEN_SEQ_8, and TOKEN_SEQ_9.
Member Function Documentation
const lexer & lexer::instance () static
References anonymous_namespace{Version.cpp}::retval.
Referenced by anonymous_namespace{Parse.cpp}::color_parser_rules::color_parser_rules(), anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::condition_parser_rules_1(), anonymous_namespace{ConditionParser2.cpp}::condition_parser_rules_2::condition_parser_rules_2(), anonymous_namespace{ConditionParser3.cpp}::condition_parser_rules_3::condition_parser_rules_3(), anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), anonymous_namespace{ConditionParser5.cpp}::condition_parser_rules_5::condition_parser_rules_5(), anonymous_namespace{ConditionParser6.cpp}::condition_parser_rules_6::condition_parser_rules_6(), anonymous_namespace{ConditionParser7.cpp}::condition_parser_rules_7::condition_parser_rules_7(), parse::double_complex_parser_rules::double_complex_parser_rules(), anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), anonymous_namespace{EffectParser2.cpp}::effect_parser_rules_2::effect_parser_rules_2(), anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::effect_parser_rules_3(), anonymous_namespace{EffectParser4.cpp}::effect_parser_rules_4::effect_parser_rules_4(), anonymous_namespace{EffectParser5.cpp}::effect_parser_rules_5::effect_parser_rules_5(), anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rules(), parse::enum_parser< CaptureResult >(), parse::enum_parser< EmpireAffiliationType >(), parse::enum_parser< PlanetEnvironment >(), parse::enum_parser< PlanetSize >(), parse::enum_parser< PlanetType >(), parse::enum_parser< ShipPartClass >(), parse::enum_parser< ShipSlotType >(), parse::enum_parser< StarType >(), parse::enum_parser< UniverseObjectType >(), parse::enum_parser< UnlockableItemType >(), parse::enum_parser< ValueRef::StatisticType >(), parse::init(), initialize_nonnumeric_expression_parsers(), initialize_nonnumeric_expression_parsers< std::string >(), initialize_nonnumeric_statistic_parser(), initialize_numeric_expression_parsers(), initialize_numeric_statistic_parser(), parse::int_complex_parser_rules::int_complex_parser_rules(), anonymous_namespace{Parse.cpp}::item_spec_parser_rules::item_spec_parser_rules(), parse::label(), lexer_test_rules::lexer_test_rules(), main(), parse::non_ship_part_meter_type_enum(), parse::detail::parse_file(), EnumParserFixture::parse_nonship_meter(), EnumParserFixture::parse_ship_meter(), anonymous_namespace{PlanetEnvironmentValueRefParser.cpp}::planet_environment_parser_rules::planet_environment_parser_rules(), anonymous_namespace{PlanetSizeValueRefParser.cpp}::planet_size_parser_rules::planet_size_parser_rules(), anonymous_namespace{PlanetTypeValueRefParser.cpp}::planet_type_parser_rules::planet_type_parser_rules(), anonymous_namespace{EmpireStatsParser.cpp}::rules::rules(), parse::detail::rules::rules(), anonymous_namespace{FleetPlansParser.cpp}::rules::rules(), anonymous_namespace{AlignmentsParser.cpp}::rules::rules(), anonymous_namespace{EncyclopediaParser.cpp}::rules::rules(), anonymous_namespace{ShipDesignsParser.cpp}::rules::rules(), anonymous_namespace{MonsterFleetPlansParser.cpp}::rules::rules(), anonymous_namespace{FieldsParser.cpp}::rules::rules(), anonymous_namespace{SpecialsParser.cpp}::rules::rules(), anonymous_namespace{BuildingsParser.cpp}::rules::rules(), anonymous_namespace{SpeciesParser.cpp}::rules::rules(), anonymous_namespace{ShipPartsParser.cpp}::rules::rules(), anonymous_namespace{ShipHullsParser.cpp}::rules::rules(), anonymous_namespace{KeymapParser.cpp}::rules::rules(), anonymous_namespace{TechsParser.cpp}::rules::rules(), parse::set_non_ship_part_meter_type_enum(), EnumParserFixture::set_parse_nonship_meter(), EnumParserFixture::set_parse_ship_meter(), parse::set_ship_part_meter_type_enum(), parse::ship_part_meter_type_enum(), anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::simple_int_parser_rules(), anonymous_namespace{StarTypeValueRefParser.cpp}::star_type_parser_rules::star_type_parser_rules(), parse::string_complex_parser_rules::string_complex_parser_rules(), anonymous_namespace{StringValueRefParser.cpp}::string_parser_rules::string_parser_rules(), anonymous_namespace{Parse.cpp}::tags_rules::tags_rules(), anonymous_namespace{UniverseObjectTypeValueRefParser.cpp}::universe_object_type_parser_rules::universe_object_type_parser_rules(), and anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_parser_rules().
const boost::spirit::lex::token_def< const char * > & lexer::name_token (const char * name) const
Returns the token_def<const char*> associated with name.
References m_name_tokens.
Referenced by parse::label().
Member Data Documentation
boost::spirit::lex::token_def<bool> parse::lexer::bool_
Referenced by lexer(), and lexer_test_rules::lexer_test_rules().
const char * lexer::bool_regex = "(?i:true|false)" static
Referenced by parse::detail::info_visitor::prepare().
boost::spirit::lex::token_def<double> parse::lexer::double_
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), parse::init(), lexer(), and lexer_test_rules::lexer_test_rules().
const char * lexer::double_regex = "\\d+\\.\\d*|\\d*\\.\\d+" static
Referenced by parse::detail::info_visitor::prepare().
boost::spirit::lex::token_def<boost::spirit::lex::omit> parse::lexer::end_of_line_comment
Referenced by lexer().
boost::spirit::lex::token_def<boost::spirit::lex::omit> parse::lexer::error_token
Referenced by lexer().
boost::spirit::lex::token_def<boost::spirit::lex::omit> parse::lexer::inline_comment
Referenced by lexer().
boost::spirit::lex::token_def<int> parse::lexer::int_
Referenced by anonymous_namespace{Parse.cpp}::color_parser_rules::color_parser_rules(), anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rules(), parse::init(), lexer(), lexer_test_rules::lexer_test_rules(), anonymous_namespace{KeymapParser.cpp}::rules::rules(), and anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::simple_int_parser_rules().
const char * lexer::int_regex = "\\d+" static
Referenced by parse::detail::info_visitor::prepare().
std::map<const char*, boost::spirit::lex::token_def<const char*>*> parse::lexer::m_name_tokens private
Referenced by name_token().
boost::spirit::lex::token_def<std::string> parse::lexer::string
Referenced by anonymous_namespace{ConditionParser1.cpp}::condition_parser_rules_1::condition_parser_rules_1(), anonymous_namespace{ConditionParser4.cpp}::condition_parser_rules_4::condition_parser_rules_4(), parse::double_complex_parser_rules::double_complex_parser_rules(), anonymous_namespace{EffectParser1.cpp}::effect_parser_rules_1::effect_parser_rules_1(), anonymous_namespace{EffectParser3.cpp}::effect_parser_rules_3::effect_parser_rules_3(), anonymous_namespace{Parse.cpp}::effects_group_rules::effects_group_rules(), anonymous_namespace{Parse.cpp}::item_spec_parser_rules::item_spec_parser_rules(), lexer_test_rules::lexer_test_rules(), anonymous_namespace{EmpireStatsParser.cpp}::rules::rules(), parse::detail::rules::rules(), anonymous_namespace{AlignmentsParser.cpp}::rules::rules(), anonymous_namespace{FleetPlansParser.cpp}::rules::rules(), anonymous_namespace{EncyclopediaParser.cpp}::rules::rules(), anonymous_namespace{ShipDesignsParser.cpp}::rules::rules(), anonymous_namespace{MonsterFleetPlansParser.cpp}::rules::rules(), anonymous_namespace{FieldsParser.cpp}::rules::rules(), anonymous_namespace{SpecialsParser.cpp}::rules::rules(), anonymous_namespace{BuildingsParser.cpp}::rules::rules(), anonymous_namespace{SpeciesParser.cpp}::rules::rules(), anonymous_namespace{ShipPartsParser.cpp}::rules::rules(), anonymous_namespace{ShipHullsParser.cpp}::rules::rules(), anonymous_namespace{KeymapParser.cpp}::rules::rules(), anonymous_namespace{TechsParser.cpp}::rules::rules(), anonymous_namespace{StringValueRefParser.cpp}::string_parser_rules::string_parser_rules(), and anonymous_namespace{Parse.cpp}::tags_rules::tags_rules().
const char * lexer::string_regex = "\\\"[^\\\"]*\\\"" static
Referenced by parse::detail::info_visitor::prepare().
The documentation for this struct was generated from the following files:
Lexer.h
Lexer.cpp