FreeOrion: ConditionWidget Class Reference
ConditionWidget Class Reference
Classes
class ConditionRow
class StringRow
Public Member Functions
ConditionWidget (GG::X x, GG::Y y, const Condition::ConditionBase *initial_condition=0)
~ConditionWidget ()
Condition::ConditionBase * GetCondition ()
virtual void Render ()
Private Member Functions
void ConditionClassSelected (GG::ListBox::iterator iterator)
int DropListDropHeight () const
GG::Y DropListHeight () const
GG::X DropListWidth () const
double GetDouble1 ()
ValueRef::ValueRefBase< double > * GetDouble1ValueRef ()
double GetDouble2 ()
ValueRef::ValueRefBase< double > * GetDouble2ValueRef ()
template<typename T >
T GetEnum ()
template<typename T >
ValueRef::ValueRefBase< T > * GetEnumValueRef ()
template<typename T >
std::vector
< ValueRef::ValueRefBase< T > * > GetEnumValueRefVec ()
int GetInt1 ()
ValueRef::ValueRefBase< int > * GetInt1ValueRef ()
int GetInt2 ()
ValueRef::ValueRefBase< int > * GetInt2ValueRef ()
const std::string & GetString ()
ValueRef::ValueRefBase
< std::string > * GetStringValueRef ()
std::vector
< ValueRef::ValueRefBase
< std::string > * > GetStringValueRefVec ()
void Init (const Condition::ConditionBase *init_condition)
GG::X ParamsDropListWidth () const
GG::X SpinDropListWidth () const
void UpdateParameterControls ()
Private Attributes
GG::DropDownList * m_class_drop
GG::Spin< int > * m_param_spin1
GG::Spin< int > * m_param_spin2
GG::DropDownList * m_string_drop
Constructor & Destructor Documentation
ConditionWidget::ConditionWidget (GG::X x, GG::Y y, const Condition::ConditionBase * initial_condition = 0) inline
References Condition::All(), Condition::ConditionBase(), and Init().
ConditionWidget::~ConditionWidget () inline
References m_class_drop, m_param_spin1, m_param_spin2, and m_string_drop.
Member Function Documentation
void ConditionWidget::ConditionClassSelected (GG::ListBox::iterator iterator) inline private
References UpdateParameterControls().
Referenced by Init().
int ConditionWidget::DropListDropHeight () const inline private
Referenced by Init(), and UpdateParameterControls().
GG::Y ConditionWidget::DropListHeight () const inline private
References ClientUI::Pts().
Referenced by Init(), and UpdateParameterControls().
GG::X ConditionWidget::DropListWidth () const inline private
References ClientUI::Pts().
Referenced by Init(), ParamsDropListWidth(), and UpdateParameterControls().
Condition::ConditionBase* ConditionWidget::GetCondition () inline
References AFFIL_SELF, Condition::All(), anonymous_namespace{ObjectListWnd.cpp}::ALL_CONDITION(), ALL_EMPIRES, Condition::And(), Condition::Armed(), anonymous_namespace{ObjectListWnd.cpp}::ARMED_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ASTWITHPTYPE_CONDITION(), EmpireManager::begin(), Condition::CanColonize(), anonymous_namespace{ObjectListWnd.cpp}::CANCOLONIZE_CONDITION(), Condition::CanProduceShips(), anonymous_namespace{ObjectListWnd.cpp}::CANPRODUCESHIPS_CONDITION(), Condition::Capital(), anonymous_namespace{ObjectListWnd.cpp}::CAPITAL_CONDITION(), Condition::ContainedBy(), Condition::Contains(), Condition::EmpireAffiliation(), anonymous_namespace{ObjectListWnd.cpp}::EMPIREAFFILIATION_CONDITION(), Empires(), EmpireManager::end(), Condition::FocusType(), anonymous_namespace{ObjectListWnd.cpp}::FOCUSTYPE_CONDITION(), GetDouble1ValueRef(), GetDouble2ValueRef(), ConditionWidget::ConditionRow::GetKey(), GetString(), GetStringValueRefVec(), anonymous_namespace{ObjectListWnd.cpp}::GGWITHPTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASGROWTHSPECIAL_CONDITION(), Condition::HasSpecial(), anonymous_namespace{ObjectListWnd.cpp}::HASSPECIAL_CONDITION(), Condition::HasTag(), anonymous_namespace{ObjectListWnd.cpp}::HASTAG_CONDITION(), Condition::Homeworld(), anonymous_namespace{ObjectListWnd.cpp}::HOMEWORLD_CONDITION(), m_class_drop, Condition::MeterValue(), anonymous_namespace{ObjectListWnd.cpp}::METERVALUE_CONDITION(), Condition::Monster(), anonymous_namespace{ObjectListWnd.cpp}::MONSTER_CONDITION(), Condition::Not(), anonymous_namespace{ObjectListWnd.cpp}::object_list_cond_description_map, Condition::Or(), Condition::PlanetSize(), anonymous_namespace{ObjectListWnd.cpp}::PLANETSIZE_CONDITION(), Condition::PlanetType(), anonymous_namespace{ObjectListWnd.cpp}::PLANETTYPE_CONDITION(), Condition::Species(), anonymous_namespace{ObjectListWnd.cpp}::SPECIES_CONDITION(), Condition::StarType(), anonymous_namespace{ObjectListWnd.cpp}::STARTYPE_CONDITION(), Condition::Stationary(), anonymous_namespace{ObjectListWnd.cpp}::STATIONARY_CONDITION(), Condition::Type(), and UserString().
Referenced by FilterDialog::GetConditionFilter().
double ConditionWidget::GetDouble1 () inline private
References m_param_spin1.
Referenced by GetDouble1ValueRef().
ValueRef::ValueRefBase<double>* ConditionWidget::GetDouble1ValueRef () inline private
References GetDouble1().
Referenced by GetCondition().
double ConditionWidget::GetDouble2 () inline private
References m_param_spin2.
Referenced by GetDouble2ValueRef().
ValueRef::ValueRefBase<double>* ConditionWidget::GetDouble2ValueRef () inline private
References GetDouble2().
Referenced by GetCondition().
template<typename T > T ConditionWidget::GetEnum () inline private
References ErrorLogger, and GetString().
template<typename T > ValueRef::ValueRefBase<T>* ConditionWidget::GetEnumValueRef () inline private
template<typename T > std::vector<ValueRef::ValueRefBase<T>*> ConditionWidget::GetEnumValueRefVec () inline private
int ConditionWidget::GetInt1 () inline private
References m_param_spin1.
Referenced by GetInt1ValueRef().
ValueRef::ValueRefBase<int>* ConditionWidget::GetInt1ValueRef () inline private
References GetInt1().
int ConditionWidget::GetInt2 () inline private
References m_param_spin2.
Referenced by GetInt2ValueRef().
ValueRef::ValueRefBase<int>* ConditionWidget::GetInt2ValueRef () inline private
References GetInt2().
const std::string& ConditionWidget::GetString () inline private
References anonymous_namespace{ObjectListWnd.cpp}::EMPTY_STRING, m_string_drop, and ConditionWidget::StringRow::Text().
Referenced by GetCondition(), GetEnum(), and GetStringValueRef().
ValueRef::ValueRefBase<std::string>* ConditionWidget::GetStringValueRef () inline private
References GetString().
Referenced by GetStringValueRefVec().
std::vector<ValueRef::ValueRefBase<std::string>*> ConditionWidget::GetStringValueRefVec () inline private
References GetStringValueRef().
Referenced by GetCondition().
void ConditionWidget::Init (const Condition::ConditionBase * init_condition) inline private
References anonymous_namespace{ObjectListWnd.cpp}::ALL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ARMED_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ASTWITHPTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::CANCOLONIZE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::CANPRODUCESHIPS_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::CAPITAL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ConditionClassName(), ConditionClassSelected(), DropListDropHeight(), DropListHeight(), DropListWidth(), anonymous_namespace{ObjectListWnd.cpp}::EMPIREAFFILIATION_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::FOCUSTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::GGWITHPTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASGROWTHSPECIAL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASSPECIAL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASTAG_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HOMEWORLD_CONDITION(), m_class_drop, anonymous_namespace{ObjectListWnd.cpp}::METERVALUE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::MONSTER_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::PLANETSIZE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::PLANETTYPE_CONDITION(), ClientUI::Pts(), anonymous_namespace{ObjectListWnd.cpp}::SPECIES_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::STARTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::STATIONARY_CONDITION(), and UpdateParameterControls().
Referenced by ConditionWidget().
GG::X ConditionWidget::ParamsDropListWidth () const inline private
References CONDITION_WIDGET_WIDTH(), and DropListWidth().
Referenced by UpdateParameterControls().
virtual void ConditionWidget::Render () inline virtual
References ClientUI::CtrlBorderColor(), and ClientUI::CtrlColor().
GG::X ConditionWidget::SpinDropListWidth () const inline private
References ClientUI::Pts().
Referenced by UpdateParameterControls().
void ConditionWidget::UpdateParameterControls () inline private
References anonymous_namespace{ObjectListWnd.cpp}::ALL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ARMED_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::ASTWITHPTYPE_CONDITION(), EmpireManager::begin(), SpeciesManager::begin(), anonymous_namespace{ObjectListWnd.cpp}::CANCOLONIZE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::CANPRODUCESHIPS_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::CAPITAL_CONDITION(), ObjectMap::const_begin(), ObjectMap::const_end(), DropListDropHeight(), DropListHeight(), DropListWidth(), anonymous_namespace{ObjectListWnd.cpp}::EMPIREAFFILIATION_CONDITION(), Empires(), EmpireManager::end(), SpeciesManager::end(), anonymous_namespace{ObjectListWnd.cpp}::FOCUSTYPE_CONDITION(), ConditionWidget::ConditionRow::GetKey(), GetSpeciesManager(), GetUniverse(), anonymous_namespace{ObjectListWnd.cpp}::GGWITHPTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASGROWTHSPECIAL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASSPECIAL_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HASTAG_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::HOMEWORLD_CONDITION(), m_class_drop, m_param_spin1, m_param_spin2, m_string_drop, METER_TARGET_POPULATION, anonymous_namespace{ObjectListWnd.cpp}::METERVALUE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::MONSTER_CONDITION(), Objects(), Universe::Objects(), anonymous_namespace{ObjectListWnd.cpp}::PAD(), ParamsDropListWidth(), anonymous_namespace{ObjectListWnd.cpp}::PLANETSIZE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::PLANETTYPE_CONDITION(), ClientUI::Pts(), SpecialNames(), anonymous_namespace{ObjectListWnd.cpp}::SPECIES_CONDITION(), SpinDropListWidth(), STAR_BLUE, anonymous_namespace{ObjectListWnd.cpp}::STARTYPE_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::STATIONARY_CONDITION(), anonymous_namespace{ObjectListWnd.cpp}::StringsFromEnums(), SZ_TINY, UniverseObject::Tags(), and UserString().
Referenced by ConditionClassSelected(), and Init().
Member Data Documentation
GG::DropDownList* ConditionWidget::m_class_drop private
Referenced by GetCondition(), Init(), UpdateParameterControls(), and ~ConditionWidget().
GG::Spin<int>* ConditionWidget::m_param_spin1 private
Referenced by GetDouble1(), GetInt1(), UpdateParameterControls(), and ~ConditionWidget().
GG::Spin<int>* ConditionWidget::m_param_spin2 private
Referenced by GetDouble2(), GetInt2(), UpdateParameterControls(), and ~ConditionWidget().
GG::DropDownList* ConditionWidget::m_string_drop private
Referenced by GetString(), UpdateParameterControls(), and ~ConditionWidget().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp