FreeOrion: anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch Struct Reference
anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch Struct Reference
Public Member Functions
PlanetEnvironmentSimpleMatch (const std::vector< ::PlanetEnvironment > &environments, const std::string &species="")
bool operator() (TemporaryPtr< const UniverseObject > candidate) const
Public Attributes
const std::vector
< ::PlanetEnvironment > & m_environments
const std::string & m_species
Constructor & Destructor Documentation
anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::PlanetEnvironmentSimpleMatch (const std::vector< ::PlanetEnvironment > & environments, const std::string & species = "") inline
Member Function Documentation
bool anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::operator() (TemporaryPtr< const UniverseObject > candidate) const inline
References boost::dynamic_pointer_cast(), Planet::EnvironmentForSpecies(), GetPlanet(), m_environments, and m_species.
Member Data Documentation
const std::vector< ::PlanetEnvironment>& anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::m_environments
Referenced by operator()().
const std::string& anonymous_namespace{Condition.cpp}::PlanetEnvironmentSimpleMatch::m_species
Referenced by operator()().
The documentation for this struct was generated from the following file:
Condition.cpp