FreeOrion: TestValueRefUniverseObjectTypeParser.cpp File Reference
TestValueRefUniverseObjectTypeParser.cpp File Reference
#include <boost/test/unit_test.hpp>
#include "ValueRefParser.h"
#include "universe/ValueRef.h"
#include "CommonTest.h"
Classes
struct ValueRefUniverseObjectTypeFixture
Functions
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserBuilding)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserShip)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserFleet)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserPlanet)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserPopulationCenter)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserProductionCenter)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserSystem)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserField)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserSource)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserTarget)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserLocalCandidate)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserRootCandidate)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserFleetSource)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserSytemTarget)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserLocalCandidatePlanet)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserRootCandidateFleet)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserMalformed)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserFleet)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserPlanet)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserSystem)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserFleetShort)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserMalformed)
Function Documentation
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserBuilding)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserShip)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserFleet)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserPlanet)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserPopulationCenter)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserProductionCenter)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserSystem)
BOOST_AUTO_TEST_CASE (UniverseObjectTypeLiteralParserField)
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserSource)
References ValueRef< T >::SOURCE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserTarget)
References ValueRef< T >::EFFECT_TARGET_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserLocalCandidate)
References ValueRef< T >::CONDITION_LOCAL_CANDIDATE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserRootCandidate)
References ValueRef< T >::CONDITION_ROOT_CANDIDATE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserFleetSource)
References ValueRef< T >::SOURCE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserSytemTarget)
References ValueRef< T >::EFFECT_TARGET_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserLocalCandidatePlanet)
References ValueRef< T >::CONDITION_LOCAL_CANDIDATE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserRootCandidateFleet)
References ValueRef< T >::CONDITION_ROOT_CANDIDATE_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectVariableParserMalformed)
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserFleet)
References Condition::All(), ValueRef< T >::MODE, and ValueRef< T >::NON_OBJECT_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserPlanet)
References Condition::All(), ValueRef< T >::MODE, and ValueRef< T >::NON_OBJECT_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserSystem)
References Condition::All(), ValueRef< T >::MODE, and ValueRef< T >::NON_OBJECT_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserFleetShort)
References Condition::All(), ValueRef< T >::MODE, and ValueRef< T >::NON_OBJECT_REFERENCE.
BOOST_AUTO_TEST_CASE (UniverseObjectStatisticParserMalformed)