FreeOrion: ObjectRow Class Reference
ObjectRow Class Reference
Public Member Functions
ObjectRow (GG::X w, GG::Y h, TemporaryPtr< const UniverseObject > obj, bool expanded, int container_object_panel, const std::set< int > &contained_object_panels, int indent)
int ContainedByPanel () const
const std::set< int > & ContainedPanels () const
void ExpandCollapseClicked ()
int ObjectID () const
void SetContainedPanels (const std::set< int > &contained_object_panels)
void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
virtual
GG::ListBox::Row::SortKeyType SortKey (std::size_t column) const
void Update ()
Public Attributes
boost::signals2::signal< void(int)> ExpandCollapseSignal
Private Attributes
std::set< int > m_contained_object_panels
int m_container_object_panel
ObjectPanel * m_panel
Constructor & Destructor Documentation
ObjectRow::ObjectRow (GG::X w, GG::Y h, TemporaryPtr< const UniverseObject > obj, bool expanded, int container_object_panel, const std::set< int > & contained_object_panels, int indent) inline
References ExpandCollapseClicked(), ObjectPanel::ExpandCollapseSignal, m_contained_object_panels, m_panel, and anonymous_namespace{ServerWrapper.cpp}::SetName().
Member Function Documentation
int ObjectRow::ContainedByPanel () const inline
References m_container_object_panel.
Referenced by ObjectListBox::RemoveObjectRow().
const std::set<int>& ObjectRow::ContainedPanels () const inline
References m_contained_object_panels.
Referenced by ObjectListBox::RemoveObjectRow().
void ObjectRow::ExpandCollapseClicked () inline
References ExpandCollapseSignal, INVALID_OBJECT_ID, m_panel, and ObjectPanel::ObjectID().
Referenced by ObjectRow().
int ObjectRow::ObjectID () const inline
References INVALID_OBJECT_ID, m_panel, and ObjectPanel::ObjectID().
Referenced by ObjectListWnd::ObjectRightClicked(), ObjectListBox::RemoveObjectRow(), ObjectListWnd::SelectedObjectIDs(), and ObjectListWnd::SetSelectedObjects().
void ObjectRow::SetContainedPanels (const std::set< int > & contained_object_panels) inline
References m_contained_object_panels, m_panel, ObjectPanel::Refresh(), and ObjectPanel::SetHasContents().
void ObjectRow::SizeMove (const GG::Pt & ul, const GG::Pt & lr) inline
References m_panel.
virtual GG::ListBox::Row::SortKeyType ObjectRow::SortKey (std::size_t column) const inline virtual
References m_panel, and ObjectPanel::SortKey().
void ObjectRow::Update () inline
References m_panel, and ObjectPanel::Refresh().
Member Data Documentation
boost::signals2::signal<void (int)> ObjectRow::ExpandCollapseSignal mutable
Referenced by ObjectListBox::AddObjectRow(), and ExpandCollapseClicked().
std::set<int> ObjectRow::m_contained_object_panels private
Referenced by ContainedPanels(), ObjectRow(), and SetContainedPanels().
int ObjectRow::m_container_object_panel private
Referenced by ContainedByPanel().
ObjectPanel* ObjectRow::m_panel private
Referenced by ExpandCollapseClicked(), ObjectID(), ObjectRow(), SetContainedPanels(), SizeMove(), SortKey(), and Update().
The documentation for this class was generated from the following file:
ObjectListWnd.cpp