FreeOrion: Condition::OwnerHasBuildingTypeAvailable Struct Reference
Condition::OwnerHasBuildingTypeAvailable Struct Reference
#include <Condition.h>
Public Member Functions
OwnerHasBuildingTypeAvailable (const std::string &name)
OwnerHasBuildingTypeAvailable (ValueRef::ValueRefBase< std::string > *name)
virtual ~OwnerHasBuildingTypeAvailable ()
virtual std::string Description (bool negated=false) const
virtual std::string Dump () const
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
const ValueRef::ValueRefBase
< std::string > * GetBuildingType () const
virtual bool operator== (const ConditionBase &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Public Member Functions inherited from Condition::ConditionBase
ConditionBase ()
virtual ~ConditionBase ()
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
void Eval (ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
ValueRef::ValueRefBase
< std::string > * m_name
Friends
class boost::serialization::access
Additional Inherited Members
Protected Attributes inherited from Condition::ConditionBase
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Detailed Description
Matches all objects whose owner who has the building type name available.
Constructor & Destructor Documentation
Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable (const std::string & name) explicit
Condition::OwnerHasBuildingTypeAvailable::OwnerHasBuildingTypeAvailable (ValueRef::ValueRefBase< std::string > * name) inline explicit
Condition::OwnerHasBuildingTypeAvailable::~OwnerHasBuildingTypeAvailable () virtual
References m_name.
Member Function Documentation
std::string Condition::OwnerHasBuildingTypeAvailable::Description (bool negated = false) const virtual
Implements Condition::ConditionBase.
References UserString().
std::string Condition::OwnerHasBuildingTypeAvailable::Dump () const virtual
Implements Condition::ConditionBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), and m_name.
void Condition::OwnerHasBuildingTypeAvailable::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_root_candidate, Condition::ConditionBase::Eval(), ValueRef::ValueRefBase< T >::Eval(), anonymous_namespace{Condition.cpp}::EvalImpl(), ValueRef::ValueRefBase< T >::LocalCandidateInvariant(), m_name, and RootCandidateInvariant().
void Condition::OwnerHasBuildingTypeAvailable::Eval (ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const inline
References Condition::ConditionBase::Eval().
const ValueRef::ValueRefBase<std::string>* Condition::OwnerHasBuildingTypeAvailable::GetBuildingType () const inline
bool Condition::OwnerHasBuildingTypeAvailable::Match (const ScriptingContext & local_context) const private virtual
Reimplemented from Condition::ConditionBase.
References ScriptingContext::condition_local_candidate, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), and m_name.
bool Condition::OwnerHasBuildingTypeAvailable::operator== (const ConditionBase & rhs) const virtual
Reimplemented from Condition::ConditionBase.
References CHECK_COND_VREF_MEMBER, and m_name.
bool Condition::OwnerHasBuildingTypeAvailable::RootCandidateInvariant () const virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::RootCandidateInvariant().
Referenced by Eval().
template<class Archive > void Condition::OwnerHasBuildingTypeAvailable::serialize (Archive & ar, const unsigned int version) private
References m_name.
void Condition::OwnerHasBuildingTypeAvailable::SetTopLevelContent (const std::string & content_name) virtual
Implements Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::SetTopLevelContent().
bool Condition::OwnerHasBuildingTypeAvailable::SourceInvariant () const virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::SourceInvariant().
bool Condition::OwnerHasBuildingTypeAvailable::TargetInvariant () const virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented from Condition::ConditionBase.
References m_name, and ValueRef::ValueRefBase< T >::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
ValueRef::ValueRefBase<std::string>* Condition::OwnerHasBuildingTypeAvailable::m_name private
Referenced by Dump(), Eval(), Match(), operator==(), RootCandidateInvariant(), serialize(), SetTopLevelContent(), SourceInvariant(), TargetInvariant(), and ~OwnerHasBuildingTypeAvailable().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp