FreeOrion: Condition::ConditionBase Struct Reference
Condition::ConditionBase Struct Reference abstract
#include <Condition.h>
Classes
struct MatchHelper
Public Member Functions
ConditionBase ()
virtual ~ConditionBase ()
virtual std::string Description (bool negated=false) const =0
virtual std::string Dump () const =0
virtual void Eval (const ScriptingContext &parent_context, ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (ObjectSet &matches, ObjectSet &non_matches, SearchDomain search_domain=NON_MATCHES) const
void Eval (const ScriptingContext &parent_context, ObjectSet &matches) const
void Eval (ObjectSet &matches) const
bool Eval (const ScriptingContext &parent_context, TemporaryPtr< const UniverseObject > candidate) const
bool Eval (TemporaryPtr< const UniverseObject > candidate) const
virtual void GetDefaultInitialCandidateObjects (const ScriptingContext &parent_context, ObjectSet &condition_non_targets) const
bool LocalCandidateInvariant () const
bool operator!= (const ConditionBase &rhs) const
virtual bool operator== (const ConditionBase &rhs) const
virtual bool RootCandidateInvariant () const
virtual void SetTopLevelContent (const std::string &content_name)=0
virtual bool SourceInvariant () const
virtual bool TargetInvariant () const
Protected Attributes
Invariance m_root_candidate_invariant
Invariance m_source_invariant
Invariance m_target_invariant
Private Member Functions
virtual bool Match (const ScriptingContext &local_context) const
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Friends
class boost::serialization::access
struct MatchHelper
Detailed Description
The base class for all Conditions.
Constructor & Destructor Documentation
Condition::ConditionBase::ConditionBase () inline
Condition::ConditionBase::~ConditionBase () virtual
Member Function Documentation
std::string Condition::ConditionBase::Description (bool negated = false) const pure virtual
Implemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by anonymous_namespace{ObjectListWnd.cpp}::ConditionClassName(), anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest(), Condition::Number::Description(), Condition::SortedNumberOf::Description(), Condition::Contains::Description(), Condition::ContainedBy::Description(), Condition::WithinDistance::Description(), Condition::WithinStarlaneJumps::Description(), Condition::CanAddStarlaneConnection::Description(), Condition::ResourceSupplyConnectedByEmpire::Description(), Condition::OrderedBombarded::Description(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelBuildingTypeTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipHullTag(), anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelShipPartTag(), and anonymous_namespace{EncyclopediaDetailPanel.cpp}::RefreshDetailPanelSpecialTag().
std::string Condition::ConditionBase::Dump () const pure virtual
Implemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by Special::Dump(), BuildingType::Dump(), Condition::Number::Dump(), Condition::SortedNumberOf::Dump(), Condition::Contains::Dump(), Condition::ContainedBy::Dump(), Condition::WithinDistance::Dump(), Condition::WithinStarlaneJumps::Dump(), Condition::CanAddStarlaneConnection::Dump(), Condition::ResourceSupplyConnectedByEmpire::Dump(), and Condition::OrderedBombarded::Dump().
void Condition::ConditionBase::Eval (const ScriptingContext & parent_context, ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const virtual
Reimplemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Homeworld, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
References anonymous_namespace{Condition.cpp}::EvalImpl(), and MatchHelper.
Referenced by anonymous_namespace{Condition.cpp}::ConditionDescriptionAndTest(), BuildingType::EnqueueLocation(), Eval(), Condition::Number::Eval(), Condition::Turn::Eval(), Condition::SortedNumberOf::Eval(), Condition::All::Eval(), Condition::None::Eval(), Condition::EmpireAffiliation::Eval(), Condition::Homeworld::Eval(), Condition::Type::Eval(), Condition::Building::Eval(), Condition::HasSpecial::Eval(), Condition::HasTag::Eval(), Condition::CreatedOnTurn::Eval(), Condition::Contains::Eval(), Condition::ContainedBy::Eval(), Condition::InSystem::Eval(), Condition::ObjectID::Eval(), Condition::PlanetType::Eval(), Condition::PlanetSize::Eval(), Condition::PlanetEnvironment::Eval(), Condition::Species::Eval(), Condition::Enqueued::Eval(), Condition::FocusType::Eval(), Condition::StarType::Eval(), Condition::DesignHasHull::Eval(), Condition::DesignHasPart::Eval(), Condition::DesignHasPartClass::Eval(), Condition::PredefinedShipDesign::Eval(), Condition::NumberedShipDesign::Eval(), Condition::ProducedByEmpire::Eval(), Condition::Chance::Eval(), Condition::MeterValue::Eval(), Condition::ShipPartMeterValue::Eval(), Condition::EmpireMeterValue::Eval(), Condition::EmpireStockpileValue::Eval(), Condition::OwnerHasTech::Eval(), Condition::OwnerHasBuildingTypeAvailable::Eval(), Condition::OwnerHasShipDesignAvailable::Eval(), Condition::VisibleToEmpire::Eval(), Condition::WithinDistance::Eval(), Condition::WithinStarlaneJumps::Eval(), Condition::CanAddStarlaneConnection::Eval(), Condition::ExploredByEmpire::Eval(), Condition::FleetSupplyableByEmpire::Eval(), Condition::ResourceSupplyConnectedByEmpire::Eval(), Condition::OrderedBombarded::Eval(), Condition::ValueTest::Eval(), Condition::Location::Eval(), Condition::And::Eval(), Condition::Or::Eval(), Condition::Not::Eval(), Condition::Described::Eval(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::GetConditionMatches(), anonymous_namespace{ServerWrapper.cpp}::MonsterFleetPlanWrapper::Location(), Condition::Number::Match(), Condition::Contains::Match(), Condition::ContainedBy::Match(), Condition::WithinDistance::Match(), Condition::WithinStarlaneJumps::Match(), Condition::CanAddStarlaneConnection::Match(), Condition::ResourceSupplyConnectedByEmpire::Match(), Condition::OrderedBombarded::Match(), Condition::Location::Match(), ObjectListBox::ObjectShown(), anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator()(), BuildingType::ProductionLocation(), ShipDesign::ProductionLocation(), and anonymous_namespace{ServerWrapper.cpp}::SpecialLocation().
void Condition::ConditionBase::Eval (ObjectSet & matches, ObjectSet & non_matches, SearchDomain search_domain = NON_MATCHES) const
Matches with an empty ScriptingContext
References Eval().
void Condition::ConditionBase::Eval (const ScriptingContext & parent_context, ObjectSet & matches) const
Tests all objects in universe as NON_MATCHES.
References Eval(), and GetDefaultInitialCandidateObjects().
void Condition::ConditionBase::Eval (ObjectSet & matches) const
Tests all objects in universe as NON_MATCHES with empty ScriptingContext.
References Eval().
bool Condition::ConditionBase::Eval (const ScriptingContext & parent_context, TemporaryPtr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition.
References Eval().
bool Condition::ConditionBase::Eval (TemporaryPtr< const UniverseObject > candidate) const
Tests single candidate object, returning true iff it matches condition with empty ScriptingContext.
References Eval().
void Condition::ConditionBase::GetDefaultInitialCandidateObjects (const ScriptingContext & parent_context, ObjectSet & condition_non_targets) const virtual
Reimplemented in Condition::And, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::Contains, Condition::Building, Condition::Type, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::Source, Condition::None, and Condition::SortedNumberOf.
References anonymous_namespace{Condition.cpp}::AddAllObjectsSet().
Referenced by Eval(), Condition::SortedNumberOf::GetDefaultInitialCandidateObjects(), Condition::Type::GetDefaultInitialCandidateObjects(), and Condition::And::GetDefaultInitialCandidateObjects().
bool Condition::ConditionBase::LocalCandidateInvariant () const inline
(Almost) all conditions are varying with local candidates; this is the point of evaluating a condition. This funciton is provided for consistency with ValueRef, which may not depend on the local candidiate of an enclosing condition.
bool Condition::ConditionBase::Match (const ScriptingContext & local_context) const private virtual
Reimplemented in Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::Turn, and Condition::Number.
Referenced by Condition::ConditionBase::MatchHelper::operator()().
bool Condition::ConditionBase::operator!= (const ConditionBase & rhs) const inline
bool Condition::ConditionBase::operator== (const ConditionBase & rhs) const virtual
Reimplemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by Condition::All::operator==(), Condition::None::operator==(), Condition::Source::operator==(), Condition::RootCandidate::operator==(), Condition::Target::operator==(), Condition::Capital::operator==(), Condition::Monster::operator==(), Condition::Armed::operator==(), Condition::Stationary::operator==(), Condition::CanColonize::operator==(), and Condition::CanProduceShips::operator==().
virtual bool Condition::ConditionBase::RootCandidateInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the RootCandidate objects. This requirement ensures that if this condition is a subcondition to another Condition or a ValueRef, this condition may be evaluated once and its result used to match all local candidates to that condition.
Reimplemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by Condition::Number::RootCandidateInvariant(), Condition::Contains::RootCandidateInvariant(), Condition::ContainedBy::RootCandidateInvariant(), Condition::WithinDistance::RootCandidateInvariant(), Condition::WithinStarlaneJumps::RootCandidateInvariant(), Condition::CanAddStarlaneConnection::RootCandidateInvariant(), Condition::ResourceSupplyConnectedByEmpire::RootCandidateInvariant(), and Condition::OrderedBombarded::RootCandidateInvariant().
template<class Archive > void Condition::ConditionBase::serialize (Archive & ar, const unsigned int version) private
virtual void Condition::ConditionBase::SetTopLevelContent (const std::string & content_name) pure virtual
Implemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by Special::Init(), BuildingType::Init(), Species::Init(), Condition::SortedNumberOf::SetTopLevelContent(), Condition::Contains::SetTopLevelContent(), Condition::ContainedBy::SetTopLevelContent(), Condition::WithinDistance::SetTopLevelContent(), Condition::WithinStarlaneJumps::SetTopLevelContent(), Condition::CanAddStarlaneConnection::SetTopLevelContent(), Condition::ResourceSupplyConnectedByEmpire::SetTopLevelContent(), and Condition::OrderedBombarded::SetTopLevelContent().
virtual bool Condition::ConditionBase::SourceInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the source object.
Reimplemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by anonymous_namespace{Universe.cpp}::StoreTargetsAndCausesOfEffectsGroupsWorkItem::operator()(), Condition::SortedNumberOf::RootCandidateInvariant(), Condition::Number::SourceInvariant(), Condition::SortedNumberOf::SourceInvariant(), Condition::Contains::SourceInvariant(), Condition::ContainedBy::SourceInvariant(), Condition::WithinDistance::SourceInvariant(), Condition::WithinStarlaneJumps::SourceInvariant(), Condition::CanAddStarlaneConnection::SourceInvariant(), Condition::ResourceSupplyConnectedByEmpire::SourceInvariant(), Condition::OrderedBombarded::SourceInvariant(), and Condition::SortedNumberOf::TargetInvariant().
virtual bool Condition::ConditionBase::TargetInvariant () const inline virtual
Returns true iff this condition's evaluation does not reference the target object.
Reimplemented in Condition::Described, Condition::Not, Condition::Or, Condition::And, Condition::Location, Condition::ValueTest, Condition::OrderedBombarded, Condition::CanProduceShips, Condition::CanColonize, Condition::ResourceSupplyConnectedByEmpire, Condition::FleetSupplyableByEmpire, Condition::Stationary, Condition::ExploredByEmpire, Condition::CanAddStarlaneConnection, Condition::WithinStarlaneJumps, Condition::WithinDistance, Condition::VisibleToEmpire, Condition::OwnerHasShipDesignAvailable, Condition::OwnerHasBuildingTypeAvailable, Condition::OwnerHasTech, Condition::EmpireStockpileValue, Condition::EmpireMeterValue, Condition::ShipPartMeterValue, Condition::MeterValue, Condition::Chance, Condition::ProducedByEmpire, Condition::NumberedShipDesign, Condition::PredefinedShipDesign, Condition::DesignHasPartClass, Condition::DesignHasPart, Condition::DesignHasHull, Condition::StarType, Condition::FocusType, Condition::Enqueued, Condition::Species, Condition::PlanetEnvironment, Condition::PlanetSize, Condition::PlanetType, Condition::ObjectID, Condition::InSystem, Condition::ContainedBy, Condition::Contains, Condition::CreatedOnTurn, Condition::HasTag, Condition::HasSpecial, Condition::Building, Condition::Type, Condition::Armed, Condition::Monster, Condition::Capital, Condition::Homeworld, Condition::Target, Condition::RootCandidate, Condition::Source, Condition::EmpireAffiliation, Condition::None, Condition::All, Condition::SortedNumberOf, Condition::Turn, and Condition::Number.
Referenced by Condition::Number::TargetInvariant(), Condition::Contains::TargetInvariant(), Condition::ContainedBy::TargetInvariant(), Condition::WithinDistance::TargetInvariant(), Condition::WithinStarlaneJumps::TargetInvariant(), Condition::CanAddStarlaneConnection::TargetInvariant(), Condition::ResourceSupplyConnectedByEmpire::TargetInvariant(), and Condition::OrderedBombarded::TargetInvariant().
Friends And Related Function Documentation
friend class boost::serialization::access friend
friend struct MatchHelper friend
Referenced by Eval().
Member Data Documentation
Invariance Condition::ConditionBase::m_root_candidate_invariant mutable protected
Referenced by Condition::And::RootCandidateInvariant(), Condition::Or::RootCandidateInvariant(), and Condition::Not::RootCandidateInvariant().
Invariance Condition::ConditionBase::m_source_invariant mutable protected
Referenced by Condition::And::SourceInvariant(), Condition::Or::SourceInvariant(), and Condition::Not::SourceInvariant().
Invariance Condition::ConditionBase::m_target_invariant mutable protected
Referenced by Condition::And::TargetInvariant(), Condition::Or::TargetInvariant(), and Condition::Not::TargetInvariant().
The documentation for this struct was generated from the following files:
Condition.h
Condition.cpp