FreeOrion: ValueRefParserImpl.h File Reference
ValueRefParserImpl.h File Reference
#include "ValueRefParser.h"
#include "ConditionParserImpl.h"
#include "EnumParser.h"
#include "Label.h"
#include "../universe/ValueRef.h"
#include <boost/spirit/include/phoenix.hpp>
Classes
struct complex_variable_rule< T >
struct expression_rule< T >
struct statistic_rule< T >
struct variable_rule< T >
Macros
#define DEBUG_VALUEREF_PARSERS 0
Typedefs
typedef
parse::value_ref_parser_rule
< double >::type double_rule
typedef
parse::value_ref_parser_rule
< int >::type int_rule
typedef qi::rule
< parse::token_iterator, const
char *(), parse::skipper_type > name_token_rule
typedef qi::rule
< parse::token_iterator,
ValueRef::ReferenceType(),
parse::skipper_type > reference_token_rule
Functions
const name_token_rule & container_type ()
const variable_rule< double >
::type & double_bound_variable ()
const name_token_rule & double_bound_variable_name ()
const double_rule & double_constant ()
const variable_rule< double >
::type & double_free_variable ()
const name_token_rule & double_free_variable_name ()
const complex_variable_rule
< double >::type & double_var_complex ()
const statistic_rule< double >
::type & double_var_statistic ()
template<typename T >
void initialize_bound_variable_parser (typename variable_rule< T >::type &bound_variable, const name_token_rule &variable_name)
template<typename T >
void initialize_nonnumeric_expression_parsers (typename expression_rule< T >::type &function_expr, typename expression_rule< T >::type &operated_expr, typename parse::value_ref_parser_rule< T >::type &expr, typename parse::value_ref_parser_rule< T >::type &primary_expr)
template<>
void initialize_nonnumeric_expression_parsers< std::string > (typename expression_rule< std::string >::type &function_expr, typename expression_rule< std::string >::type &operated_expr, typename parse::value_ref_parser_rule< std::string >::type &expr, typename parse::value_ref_parser_rule< std::string >::type &primary_expr)
template<typename T >
void initialize_nonnumeric_statistic_parser (typename statistic_rule< T >::type &statistic, const typename parse::value_ref_parser_rule< T >::type &value_ref)
template<typename T >
void initialize_numeric_expression_parsers (typename expression_rule< T >::type &function_expr, typename expression_rule< T >::type &exponential_expr, typename expression_rule< T >::type &multiplicative_expr, typename expression_rule< T >::type &additive_expr, typename parse::value_ref_parser_rule< T >::type &expr, typename parse::value_ref_parser_rule< T >::type &primary_expr)
template<typename T >
void initialize_numeric_statistic_parser (typename statistic_rule< T >::type &statistic, typename statistic_rule< T >::type &statistic_1, typename statistic_rule< T >::type &statistic_2, const typename parse::value_ref_parser_rule< T >::type &value_ref)
const variable_rule< int >::type & int_bound_variable ()
const name_token_rule & int_bound_variable_name ()
const int_rule & int_constant ()
const variable_rule< int >::type & int_free_variable ()
const name_token_rule & int_free_variable_name ()
const int_rule & int_simple ()
const complex_variable_rule
< int >::type & int_var_complex ()
const statistic_rule< int >::type & int_var_statistic ()
const complex_variable_rule
< std::string >::type & string_var_complex ()
const reference_token_rule & variable_scope ()
Macro Definition Documentation
#define DEBUG_VALUEREF_PARSERS 0
Typedef Documentation
typedef parse::value_ref_parser_rule<double>::type double_rule
typedef parse::value_ref_parser_rule<int>::type int_rule
typedef qi::rule< parse::token_iterator, const char* (), parse::skipper_type> name_token_rule
typedef qi::rule< parse::token_iterator, ValueRef::ReferenceType (), parse::skipper_type> reference_token_rule
Function Documentation
const name_token_rule& container_type ()
References anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::container_type, and anonymous_namespace{ValueRefParserImpl.cpp}::get_variable_parser_rules().
Referenced by initialize_bound_variable_parser(), and anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_parser_rules().
const variable_rule<double>::type& double_bound_variable ()
References anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::bound_variable, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
const name_token_rule& double_bound_variable_name ()
References anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::bound_variable_name, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
const double_rule& double_constant ()
References anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::constant, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
const variable_rule<double>::type& double_free_variable ()
References anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::free_variable, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
const name_token_rule& double_free_variable_name ()
References anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::free_variable_name, and anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules().
const complex_variable_rule<double>::type& double_var_complex ()
References parse::detail::double_complex_parser, and parse::double_complex_parser_rules::start.
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules().
const statistic_rule<double>::type& double_var_statistic ()
References anonymous_namespace{DoubleValueRefParser.cpp}::get_double_parser_rules(), and anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::statistic.
template<typename T > void initialize_bound_variable_parser (typename variable_rule< T >::type & bound_variable, const name_token_rule & variable_name)
References anonymous_namespace{EnumParser.cpp}::_val, container_type(), and variable_scope().
template<typename T > void initialize_nonnumeric_expression_parsers (typename expression_rule< T >::type & function_expr, typename expression_rule< T >::type & operated_expr, typename parse::value_ref_parser_rule< T >::type & expr, typename parse::value_ref_parser_rule< T >::type & primary_expr)
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), ValueRef::MAXIMUM, ValueRef::MINIMUM, and ValueRef::RANDOM_PICK.
template<> void initialize_nonnumeric_expression_parsers< std::string > (typename expression_rule< std::string >::type & function_expr, typename expression_rule< std::string >::type & operated_expr, typename parse::value_ref_parser_rule< std::string >::type & expr, typename parse::value_ref_parser_rule< std::string >::type & primary_expr)
References anonymous_namespace{EnumParser.cpp}::_val, parse::lexer::instance(), ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::PLUS, ValueRef::RANDOM_PICK, and ValueRef::SUBSTITUTION.
template<typename T > void initialize_nonnumeric_statistic_parser (typename statistic_rule< T >::type & statistic, const typename parse::value_ref_parser_rule< T >::type & value_ref)
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, parse::lexer::instance(), parse::label(), and ValueRef::MODE.
template<typename T > void initialize_numeric_expression_parsers (typename expression_rule< T >::type & function_expr, typename expression_rule< T >::type & exponential_expr, typename expression_rule< T >::type & multiplicative_expr, typename expression_rule< T >::type & additive_expr, typename parse::value_ref_parser_rule< T >::type & expr, typename parse::value_ref_parser_rule< T >::type & primary_expr)
References anonymous_namespace{EnumParser.cpp}::_val, ValueRef::ABS, ValueRef::COSINE, ValueRef::DIVIDE, ValueRef::EXPONENTIATE, parse::lexer::instance(), ValueRef::LOGARITHM, ValueRef::MAXIMUM, ValueRef::MINIMUM, ValueRef::MINUS, ValueRef::NEGATE, ValueRef::PLUS, ValueRef::RANDOM_PICK, ValueRef::RANDOM_UNIFORM, ValueRef::SINE, and ValueRef::TIMES.
template<typename T > void initialize_numeric_statistic_parser (typename statistic_rule< T >::type & statistic, typename statistic_rule< T >::type & statistic_1, typename statistic_rule< T >::type & statistic_2, const typename parse::value_ref_parser_rule< T >::type & value_ref)
References anonymous_namespace{EnumParser.cpp}::_val, parse::detail::condition_parser, ValueRef::COUNT, ValueRef::IF, parse::lexer::instance(), and parse::label().
const variable_rule<int>::type& int_bound_variable ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::bound_variable, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules().
const name_token_rule& int_bound_variable_name ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::bound_variable_name, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const int_rule& int_constant ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::constant, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const variable_rule<int>::type& int_free_variable ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::free_variable, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules().
const name_token_rule& int_free_variable_name ()
References anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::free_variable_name, and anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules().
const int_rule& int_simple ()
References anonymous_namespace{IntValueRefParser.cpp}::get_simple_int_parser_rules(), and anonymous_namespace{IntValueRefParser.cpp}::simple_int_parser_rules::simple.
Referenced by parse::double_complex_parser_rules::double_complex_parser_rules(), parse::int_complex_parser_rules::int_complex_parser_rules(), anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules::int_parser_rules(), and parse::string_complex_parser_rules::string_complex_parser_rules().
const complex_variable_rule<int>::type& int_var_complex ()
References parse::detail::int_complex_parser, and parse::int_complex_parser_rules::start.
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), and anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules::int_parser_rules().
const statistic_rule<int>::type& int_var_statistic ()
References anonymous_namespace{IntValueRefParser.cpp}::get_int_parser_rules(), and anonymous_namespace{IntValueRefParser.cpp}::int_parser_rules::statistic.
Referenced by anonymous_namespace{DoubleValueRefParser.cpp}::double_parser_rules::double_parser_rules(), and parse::int_complex_parser_rules::int_complex_parser_rules().
const complex_variable_rule<std::string>::type& string_var_complex ()
References parse::string_complex_parser_rules::start, and parse::detail::string_complex_parser.
Referenced by anonymous_namespace{StringValueRefParser.cpp}::string_parser_rules::string_parser_rules().
const reference_token_rule& variable_scope ()
References anonymous_namespace{ValueRefParserImpl.cpp}::get_variable_parser_rules(), and anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_scope.
Referenced by initialize_bound_variable_parser(), and anonymous_namespace{ValueRefParserImpl.cpp}::variable_parser_rules::variable_parser_rules().