FreeOrion: CombatSummary Struct Reference
CombatSummary Struct Reference
#include <CombatReportData.h>
Public Types
typedef boost::shared_ptr
< ParticipantSummary > ParticipantSummaryPtr
typedef std::vector
< ParticipantSummaryPtr > UnitSummaries
Public Member Functions
CombatSummary ()
CombatSummary (int empire_id)
void AddUnit (int unit_id, const CombatParticipantState &state)
unsigned int DestroyedUnits () const
GG::Clr SideColor () const
std::string SideName () const
void Sort ()
Public Attributes
Empire * empire
float max_current_health
float max_max_health
float total_current_health
float total_max_health
UnitSummaries unit_summaries
Member Typedef Documentation
typedef boost::shared_ptr<ParticipantSummary> CombatSummary::ParticipantSummaryPtr
typedef std::vector<ParticipantSummaryPtr> CombatSummary::UnitSummaries
Constructor & Destructor Documentation
CombatSummary::CombatSummary ()
CombatSummary::CombatSummary (int empire_id)
Member Function Documentation
void CombatSummary::AddUnit (int unit_id, const CombatParticipantState & state)
References empire, max_current_health, max_max_health, anonymous_namespace{CombatReportData.cpp}::SafeEmpireId(), total_current_health, total_max_health, and unit_summaries.
unsigned int CombatSummary::DestroyedUnits () const
References unit_summaries.
Referenced by SideBar::SideBar().
GG::Clr CombatSummary::SideColor () const
References Empire::Color(), and empire.
Referenced by SideBar::SideBar().
std::string CombatSummary::SideName () const
References empire, Empire::Name(), and UserString().
Referenced by SideBar::SideBar().
void CombatSummary::Sort ()
References ParticipantCompare(), and unit_summaries.
Member Data Documentation
Empire* CombatSummary::empire
Referenced by AddUnit(), SideBar::DoLayout(), SideColor(), and SideName().
float CombatSummary::max_current_health
Referenced by AddUnit().
float CombatSummary::max_max_health
Referenced by AddUnit(), and BarSizer::GetBarSize().
float CombatSummary::total_current_health
Referenced by AddUnit(), and SideBar::SideBar().
float CombatSummary::total_max_health
Referenced by AddUnit(), and SideBar::SideBar().
UnitSummaries CombatSummary::unit_summaries
Referenced by AddUnit(), DestroyedUnits(), SideBar::MakeBars(), SideBar::MaxMaxHealth(), and Sort().
The documentation for this struct was generated from the following files:
CombatReportData.h
CombatReportData.cpp