FreeOrion: Effect::CreateField Class Reference
Effect::CreateField Class Reference
#include <Effect.h>
Public Member Functions
CreateField (ValueRef::ValueRefBase< std::string > *field_type_name, ValueRef::ValueRefBase< double > *size=0, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< EffectBase * > &effects_to_apply_after=std::vector< EffectBase * >())
CreateField (ValueRef::ValueRefBase< std::string > *field_type_name, ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< double > *size=0, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< EffectBase * > &effects_to_apply_after=std::vector< EffectBase * >())
virtual ~CreateField ()
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< EffectBase * > m_effects_to_apply_after
ValueRef::ValueRefBase
< std::string > * m_field_type_name
ValueRef::ValueRefBase
< std::string > * m_name
ValueRef::ValueRefBase< double > * m_size
ValueRef::ValueRefBase< double > * m_x
ValueRef::ValueRefBase< double > * m_y
Friends
class boost::serialization::access
Detailed Description
Creates a new Field with specified field_type_name FieldType of the specified size.
Constructor & Destructor Documentation
Effect::CreateField::CreateField (ValueRef::ValueRefBase< std::string > * field_type_name, ValueRef::ValueRefBase< double > * size = 0, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< EffectBase * > & effects_to_apply_after = std::vector<EffectBase*>()) explicit
Effect::CreateField::CreateField (ValueRef::ValueRefBase< std::string > * field_type_name, ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< double > * size = 0, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< EffectBase * > & effects_to_apply_after = std::vector<EffectBase*>())
Effect::CreateField::~CreateField () virtual
References m_effects_to_apply_after, m_field_type_name, m_name, m_size, m_x, and m_y.
Member Function Documentation
std::string Effect::CreateField::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_field_type_name, m_name, m_size, m_x, and m_y.
void Effect::CreateField::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References ValueRef::ConstantExpr(), Universe::CreateField(), ValueRef::ValueRefBase< T >::Dump(), boost::dynamic_pointer_cast(), ScriptingContext::effect_target, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Effect::EffectBase::Execute(), GetFieldType(), GetUniverse(), System::Insert(), m_effects_to_apply_after, m_field_type_name, m_name, m_size, m_x, m_y, FieldType::Name(), UniverseObject::Rename(), UserString(), UserStringExists(), UniverseObject::X(), and UniverseObject::Y().
template<class Archive > void Effect::CreateField::serialize (Archive & ar, const unsigned int version) private
References m_effects_to_apply_after, m_field_type_name, m_name, m_size, m_x, and m_y.
void Effect::CreateField::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_effects_to_apply_after, m_field_type_name, m_name, m_size, m_x, m_y, ValueRef::ValueRefBase< T >::SetTopLevelContent(), and Effect::EffectBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<EffectBase*> Effect::CreateField::m_effects_to_apply_after private
Referenced by Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
ValueRef::ValueRefBase<std::string>* Effect::CreateField::m_field_type_name private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
ValueRef::ValueRefBase<std::string>* Effect::CreateField::m_name private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
ValueRef::ValueRefBase<double>* Effect::CreateField::m_size private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
ValueRef::ValueRefBase<double>* Effect::CreateField::m_x private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
ValueRef::ValueRefBase<double>* Effect::CreateField::m_y private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateField().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp