FreeOrion: Effect::CreateSystem Class Reference
Effect::CreateSystem Class Reference
#include <Effect.h>
Public Member Functions
CreateSystem (ValueRef::ValueRefBase< ::StarType > *type, ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< EffectBase * > &effects_to_apply_after=std::vector< EffectBase * >())
CreateSystem (ValueRef::ValueRefBase< double > *x, ValueRef::ValueRefBase< double > *y, ValueRef::ValueRefBase< std::string > *name=0, const std::vector< EffectBase * > &effects_to_apply_after=std::vector< EffectBase * >())
virtual ~CreateSystem ()
virtual std::string Description () const
virtual std::string Dump () const
virtual void Execute (const ScriptingContext &context) const
virtual void SetTopLevelContent (const std::string &content_name)
Public Member Functions inherited from Effect::EffectBase
virtual ~EffectBase ()
virtual void Execute (const ScriptingContext &context, const TargetSet &targets) const
virtual void Execute (const TargetsCauses &targets_causes, bool stacking, AccountingMap *accounting_map=0, bool only_meter_effects=false, bool only_appearance_effects=false, bool include_empire_meter_effects=false, bool only_generate_sitrep_effects=false) const
Private Member Functions
template<class Archive >
void serialize (Archive &ar, const unsigned int version)
Private Attributes
std::vector< EffectBase * > m_effects_to_apply_after
ValueRef::ValueRefBase
< std::string > * m_name
ValueRef::ValueRefBase
< ::StarType > * m_type
ValueRef::ValueRefBase< double > * m_x
ValueRef::ValueRefBase< double > * m_y
Friends
class boost::serialization::access
Detailed Description
Creates a new system with the specified colour and at the specified location.
Constructor & Destructor Documentation
Effect::CreateSystem::CreateSystem (ValueRef::ValueRefBase< ::StarType > * type, ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< EffectBase * > & effects_to_apply_after = std::vector<EffectBase*>())
Effect::CreateSystem::CreateSystem (ValueRef::ValueRefBase< double > * x, ValueRef::ValueRefBase< double > * y, ValueRef::ValueRefBase< std::string > * name = 0, const std::vector< EffectBase * > & effects_to_apply_after = std::vector<EffectBase*>())
Effect::CreateSystem::~CreateSystem () virtual
References m_effects_to_apply_after, m_name, m_type, m_x, and m_y.
Member Function Documentation
std::string Effect::CreateSystem::Description () const virtual
Implements Effect::EffectBase.
References ValueRef::ConstantExpr(), ValueRef::ValueRefBase< T >::Description(), ValueRef::ValueRefBase< T >::Eval(), FlexibleFormat(), m_type, and UserString().
std::string Effect::CreateSystem::Dump () const virtual
Implements Effect::EffectBase.
References ValueRef::ValueRefBase< T >::Dump(), DumpIndent(), m_name, m_type, m_x, and m_y.
void Effect::CreateSystem::Execute (const ScriptingContext & context) const virtual
Implements Effect::EffectBase.
References ValueRef::ConstantExpr(), Universe::CreateSystem(), ScriptingContext::effect_target, ErrorLogger, ValueRef::ValueRefBase< T >::Eval(), Effect::EffectBase::Execute(), anonymous_namespace{Effect.cpp}::GenerateSystemName(), GetUniverse(), m_effects_to_apply_after, m_name, m_type, m_x, m_y, RandSmallInt(), STAR_NONE, UserString(), and UserStringExists().
template<class Archive > void Effect::CreateSystem::serialize (Archive & ar, const unsigned int version) private
References m_effects_to_apply_after, m_name, m_type, m_x, and m_y.
void Effect::CreateSystem::SetTopLevelContent (const std::string & content_name) virtual
Implements Effect::EffectBase.
References m_effects_to_apply_after, m_name, m_type, m_x, m_y, ValueRef::ValueRefBase< T >::SetTopLevelContent(), and Effect::EffectBase::SetTopLevelContent().
Friends And Related Function Documentation
friend class boost::serialization::access friend
Member Data Documentation
std::vector<EffectBase*> Effect::CreateSystem::m_effects_to_apply_after private
Referenced by Execute(), serialize(), SetTopLevelContent(), and ~CreateSystem().
ValueRef::ValueRefBase<std::string>* Effect::CreateSystem::m_name private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateSystem().
ValueRef::ValueRefBase< ::StarType>* Effect::CreateSystem::m_type private
Referenced by Description(), Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateSystem().
ValueRef::ValueRefBase<double>* Effect::CreateSystem::m_x private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateSystem().
ValueRef::ValueRefBase<double>* Effect::CreateSystem::m_y private
Referenced by Dump(), Execute(), serialize(), SetTopLevelContent(), and ~CreateSystem().
The documentation for this class was generated from the following files:
Effect.h
Effect.cpp