FreeOrion: CUILinkTextMultiEdit Class Reference
CUILinkTextMultiEdit Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
CUILinkTextMultiEdit (const std::string &str, GG::Flags< GG::MultiEditStyle > style=GG::MULTI_LINEWRAP)
basic ctor
Accessors
virtual const std::vector
< GG::Font::LineData > & GetLineData () const
virtual const
boost::shared_ptr< GG::Font > & GetFont () const
virtual GG::Pt TextUpperLeft () const
virtual GG::Pt TextLowerRight () const
virtual const std::string & RawText () const
returns text being displayed before any link formatting is added
Mutators
virtual void Render ()
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void RClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseLeave ()
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
virtual void SetText (const std::string &str)
Public Member Functions inherited from CUIMultiEdit
CUIMultiEdit (const std::string &str, GG::Flags< GG::MultiEditStyle > style=GG::MULTI_LINEWRAP)
basic ctor
Public Member Functions inherited from TextLinker
void SetDecorator (const std::string &link_type, LinkDecorator *decorator)
link clicked signals: first string is the link type, second string is the specific item clicked
TextLinker ()
virtual ~TextLinker ()
Private Member Functions
virtual void SetLinkedText (const std::string &str)
Private Attributes
bool m_already_setting_text_so_dont_link
std::string m_raw_text
Additional Inherited Members
Public Attributes inherited from TextLinker
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkDoubleClickedSignal
boost::signals2::signal< void(const
std::string &, const
std::string &)> LinkRightClickedSignal
Static Public Attributes inherited from TextLinker
static const std::string ENCYCLOPEDIA_TAG
static const std::string GRAPH_TAG
Protected Member Functions inherited from TextLinker
void FindLinks ()
finds the links in the text, with which to populate m_links.
int GetLinkUnderPt (const GG::Pt &pt)
returns the index of the link under screen coordinate pt, or -1 if none
void LClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LDoubleClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void LocateLinks ()
calculates the physical locations of the links in m_links
void MarkLinks ()
wraps text for each link in text formatting tags so that the links appear visually distinct from other text
void MouseHere_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void MouseLeave_ ()
void RClick_ (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
void Render_ ()
Detailed Description
a FreeOrion MultiEdit control that parses its text and makes links within clickable
Constructor & Destructor Documentation
CUILinkTextMultiEdit::CUILinkTextMultiEdit (const std::string & str, GG::Flags< GG::MultiEditStyle > style = GG::MULTI_LINEWRAP)
basic ctor
References TextLinker::FindLinks(), and TextLinker::MarkLinks().
Member Function Documentation
const boost::shared_ptr< GG::Font > & CUILinkTextMultiEdit::GetFont () const virtual
Implements TextLinker.
Referenced by SizeMove().
const std::vector< GG::Font::LineData > & CUILinkTextMultiEdit::GetLineData () const virtual
Implements TextLinker.
void CUILinkTextMultiEdit::LClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::LClick_().
void CUILinkTextMultiEdit::MouseHere (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::MouseHere_().
void CUILinkTextMultiEdit::MouseLeave () virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::MouseLeave_().
const std::string & CUILinkTextMultiEdit::RawText () const virtual
returns text being displayed before any link formatting is added
Implements TextLinker.
References m_raw_text.
Referenced by SizeMove().
void CUILinkTextMultiEdit::RClick (const GG::Pt & pt, GG::Flags< GG::ModKey > mod_keys) virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
Reimplemented from CUIMultiEdit.
References ClientUI::EditHiliteColor(), ClientUI::GetFont(), TextLinker::GetLinkUnderPt(), TextLinker::RClick_(), ClientUI::TextColor(), UserString(), ClientUI::WndColor(), and ClientUI::WndOuterBorderColor().
void CUILinkTextMultiEdit::Render () virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
Reimplemented from CUIMultiEdit.
References CUIMultiEdit::Render(), and TextLinker::Render_().
void CUILinkTextMultiEdit::SetLinkedText (const std::string & str) private virtual
Implements TextLinker.
void CUILinkTextMultiEdit::SetText (const std::string & str) virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References TextLinker::FindLinks(), TextLinker::LocateLinks(), m_already_setting_text_so_dont_link, m_raw_text, and TextLinker::MarkLinks().
Referenced by SizeMove().
void CUILinkTextMultiEdit::SizeMove (const GG::Pt & ul, const GG::Pt & lr) virtual
sets the text to str; may resize the window. If the window was constructed to fit the size of the text (i.e. if the second ctor type was used), calls to this function cause the window to be resized to whatever space the newly rendered text occupies.
References GetFont(), RawText(), and SetText().
GG::Pt CUILinkTextMultiEdit::TextLowerRight () const virtual
Implements TextLinker.
GG::Pt CUILinkTextMultiEdit::TextUpperLeft () const virtual
Implements TextLinker.
Member Data Documentation
bool CUILinkTextMultiEdit::m_already_setting_text_so_dont_link private
Referenced by SetText().
std::string CUILinkTextMultiEdit::m_raw_text private
Referenced by RawText(), and SetText().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp