FreeOrion: TechTreeLayout::Node Class Reference
TechTreeLayout::Node Class Reference
#include <TechTreeLayout.h>
Public Member Functions
Node (const std::string &tech, GG::X width, GG::Y height)
~Node ()
void Debug () const
int GetDepth () const
int GetNumberOfChildren () const
int GetNumberOfParents () const
const std::vector< Edge * > & GetOutEdges () const
const std::string & GetTech () const
int GetWeight () const
const GG::X GetX () const
const GG::Y GetY () const
bool IsFinalNode () const
bool IsStartNode () const
bool operator< (const Node &y) const
Private Member Functions
Node (Node *parent, Node *child, std::vector< Node * > &nodes)
void AddChild (Node *node)
void CalculateCoordinate (double column_width, double row_height)
double CalculateFamilyDistance (int row)
void CreateEdges (double x_margin, double column_width, double row_height)
void CreatePlaceHolder (std::vector< Node * > &nodes)
void DoLayout (std::vector< Column > &row_index, bool cat)
bool IsPlaceHolder () const
void SetDepthRecursive (int depth)
bool Wobble (Column &column)
Private Attributes
std::vector< Node * > m_children
int m_children_rows
int m_depth
double m_height
std::vector< Edge * > m_out_edges
std::vector< Node * > m_parents
bool m_place_holder
Node * m_primary_child
int m_row
std::string m_tech
const int m_weight
double m_width
double m_x
double m_y
Friends
class Column
class TechTreeLayout
Constructor & Destructor Documentation
TechTreeLayout::Node::Node (const std::string & tech, GG::X width, GG::Y height)
creates a node for that tech
References GetTech().
TechTreeLayout::Node::~Node ()
TechTreeLayout::Node::Node (Node * parent, Node * child, std::vector< Node * > & nodes) private
recursively creates dummy nodes between parent and child
References ErrorLogger, m_children, m_depth, m_parents, m_primary_child, and m_tech.
Member Function Documentation
void TechTreeLayout::Node::AddChild (Node * node) private
References Tech::Category(), AIInterface::GetTech(), m_parents, m_place_holder, and m_tech.
void TechTreeLayout::Node::CalculateCoordinate (double column_width, double row_height) private
Referenced by CreateEdges().
double TechTreeLayout::Node::CalculateFamilyDistance (int row) private
Referenced by Wobble().
void TechTreeLayout::Node::CreateEdges (double x_margin, double column_width, double row_height) private
References TechTreeLayout::Edge::AddPoint(), CalculateCoordinate(), TechTreeLayout::m_height, m_height, m_place_holder, m_primary_child, m_tech, TechTreeLayout::m_width, m_x, and m_y.
void TechTreeLayout::Node::CreatePlaceHolder (std::vector< Node * > & nodes) private
References anonymous_namespace{TechTreeLayout.cpp}::LINE_CELL_HEIGHT, m_depth, and anonymous_namespace{TechTreeLayout.cpp}::NODE_CELL_HEIGHT.
void TechTreeLayout::Node::Debug () const
References DebugLogger.
void TechTreeLayout::Node::DoLayout (std::vector< Column > & row_index, bool cat) private
Referenced by TechTreeLayout::DoLayout().
int TechTreeLayout::Node::GetDepth () const
Referenced by TechTreeLayout::DoLayout().
int TechTreeLayout::Node::GetNumberOfChildren () const
int TechTreeLayout::Node::GetNumberOfParents () const
const std::vector< TechTreeLayout::Edge * > & TechTreeLayout::Node::GetOutEdges () const
const std::string & TechTreeLayout::Node::GetTech () const
Referenced by TechTreeLayout::DoLayout(), and Node().
int TechTreeLayout::Node::GetWeight () const inline
References m_weight.
Referenced by TechTreeLayout::Column::Fit(), TechTreeLayout::Column::Move(), TechTreeLayout::Column::Place(), and TechTreeLayout::Column::Swap().
const GG::X TechTreeLayout::Node::GetX () const
Referenced by TechTreeWnd::LayoutPanel::Layout().
const GG::Y TechTreeLayout::Node::GetY () const
Referenced by TechTreeWnd::LayoutPanel::Layout().
bool TechTreeLayout::Node::IsFinalNode () const
bool TechTreeLayout::Node::IsPlaceHolder () const private
bool TechTreeLayout::Node::IsStartNode () const
bool TechTreeLayout::Node::operator< (const Node & y) const
References Tech::Category(), AIInterface::GetTech(), m_depth, and m_tech.
void TechTreeLayout::Node::SetDepthRecursive (int depth) private
bool TechTreeLayout::Node::Wobble (Column & column) private
References CalculateFamilyDistance(), TechTreeLayout::Column::ClosestFreeIndex(), m_row, TechTreeLayout::Column::Move(), TechTreeLayout::Column::Seek(), and TechTreeLayout::Column::Swap().
Friends And Related Function Documentation
friend class Column friend
friend class TechTreeLayout friend
Member Data Documentation
std::vector<Node*> TechTreeLayout::Node::m_children private
Referenced by Node().
int TechTreeLayout::Node::m_children_rows private
int TechTreeLayout::Node::m_depth private
Referenced by CreatePlaceHolder(), Node(), and operator<().
double TechTreeLayout::Node::m_height private
Referenced by CreateEdges().
std::vector<Edge*> TechTreeLayout::Node::m_out_edges private
std::vector<Node*> TechTreeLayout::Node::m_parents private
Referenced by AddChild(), and Node().
bool TechTreeLayout::Node::m_place_holder private
Referenced by AddChild(), and CreateEdges().
Node* TechTreeLayout::Node::m_primary_child private
Referenced by CreateEdges(), and Node().
int TechTreeLayout::Node::m_row private
Referenced by TechTreeLayout::Column::Move(), TechTreeLayout::Column::Place(), TechTreeLayout::Column::Seek(), TechTreeLayout::Column::Swap(), and Wobble().
std::string TechTreeLayout::Node::m_tech private
Referenced by AddChild(), CreateEdges(), Node(), and operator<().
const int TechTreeLayout::Node::m_weight private
Referenced by GetWeight().
double TechTreeLayout::Node::m_width private
double TechTreeLayout::Node::m_x private
Referenced by CreateEdges().
double TechTreeLayout::Node::m_y private
Referenced by CreateEdges().
The documentation for this class was generated from the following files:
TechTreeLayout.h
TechTreeLayout.cpp