FreeOrion: anonymous_namespace{Ship.cpp} Namespace Reference
anonymous_namespace{Ship.cpp} Namespace Reference
Functions
std::vector< float > WeaponDamageImpl (const Ship *ship, const ShipDesign *design, float DR, bool max, bool include_fighters)
Function Documentation
std::vector<float> anonymous_namespace{Ship.cpp}::WeaponDamageImpl (const Ship * ship, const ShipDesign * design, float DR, bool max, bool include_fighters)
References PartType::Class(), Ship::CurrentPartMeterValue(), GetPartType(), METER_CAPACITY, METER_MAX_CAPACITY, METER_MAX_SECONDARY_STAT, METER_SECONDARY_STAT, ShipDesign::Parts(), PC_DIRECT_WEAPON, PC_FIGHTER_BAY, PC_FIGHTER_HANGAR, and anonymous_namespace{Version.cpp}::retval.
Referenced by Ship::AllWeaponsDamage(), and Ship::AllWeaponsMaxDamage().