FreeOrion: InGameMenu Class Reference
InGameMenu Class Reference
#include <InGameMenu.h>
Public Member Functions
Structors
InGameMenu ()
default ctor
~InGameMenu ()
dtor
Mutators
virtual void KeyPress (GG::Key key, boost::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys)
void DoLayout ()
Public Member Functions inherited from CUIWnd
CUIWnd (const std::string &wnd_name, GG::X x, GG::Y y, GG::X w, GG::Y h, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
CUIWnd (const std::string &wnd_name, GG::Flags< GG::WndFlag > flags=GG::INTERACTIVE, const std::string &config_name="", bool visible=true)
virtual ~CUIWnd ()
bool Minimized () const
returns true if window is minimized
virtual GG::Pt ClientUpperLeft () const
virtual GG::Pt ClientLowerRight () const
virtual bool InWindow (const GG::Pt &pt) const
GG::X LeftBorder () const
the distance on the left side between the outer edge of the window and the inner border
GG::Y TopBorder () const
the distance at the top between the outer edge of the window and the inner border
GG::X RightBorder () const
the distance on the right side between the outer edge of the window and the inner border
GG::Y BottomBorder () const
the distance at the bottom between the outer edge of the window and the inner border
virtual void SizeMove (const GG::Pt &ul, const GG::Pt &lr)
virtual void Render ()
virtual void LButtonDown (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LDrag (const GG::Pt &pt, const GG::Pt &move, GG::Flags< GG::ModKey > mod_keys)
virtual void LButtonUp (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void LClick (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseEnter (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseHere (const GG::Pt &pt, GG::Flags< GG::ModKey > mod_keys)
virtual void MouseLeave ()
virtual void Hide (bool children=true)
virtual void Show (bool children=true)
void ToggleMinimized ()
void Close ()
void ValidatePosition ()
calls SizeMove() to trigger position-checking and position the window entirely within the parent window/app window
void InitSizeMove (const GG::Pt &ul, const GG::Pt &lr)
sets default positions and if default positions were set beforehand, calls SizeMove()
virtual void CloseClicked ()
called when window is closed via the close button
virtual void PinClicked ()
called when window is pinned or unpinned via the pin button
Protected Member Functions
virtual GG::Rect CalculatePosition () const
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Protected Member Functions inherited from CUIWnd
virtual GG::Pt MinimizedSize () const
the size of a minimized CUIWnd
int InnerBorderAngleOffset () const
the distance from where the lower right corner of the inner border should be to where the angled portion of the inner border meets the right and bottom lines of the border
bool InResizeTab (const GG::Pt &pt) const
returns true iff the specified pt is in the region where dragging will resize this Wnd
void SaveOptions () const
saves options for this window to the OptionsDB if config_name was specified in the constructor
virtual void MinimizeClicked ()
called when window is minimized or restored via the minimize/restore button
virtual void InitButtons ()
called to create the buttons, withtout positioning them
virtual void PositionButtons ()
called to position the buttons
virtual void InitBuffers ()
void LoadOptions ()
loads options for this window from the OptionsDB
void Init (const std::string &t)
performs initialization common to all CUIWnd constructors
void ResetDefaultPosition ()
called via signal from the ClientUI, passes the value from CalculatePosition() to InitSizeMove()
virtual void SetParent (GG::Wnd *wnd)
Private Member Functions
GG::Y ButtonCellHeight () const
Helper function.
GG::X ButtonWidth () const
Helper function.
void Done ()
when m_done_btn is pressed
void Exit ()
when m_quit_btn button is pressed
void Load ()
when m_load_btn button is pressed
void Options ()
when m_options_btn button is pressed
void Save ()
when m_save_btn button is pressed
Private Attributes
GG::Button * m_done_btn
Done button.
GG::Button * m_exit_btn
Quit game button.
GG::Button * m_load_btn
Load game button.
GG::Button * m_options_btn
Options button.
GG::Button * m_save_btn
Save game button.
Additional Inherited Members
Static Public Member Functions inherited from CUIWnd
static void InvalidateUnusedOptions ()
removes unregistered and registered-but-unused window options from the OptionsDB so that new windows fall back to their default properties.
Static Protected Member Functions inherited from CUIWnd
static const std::string AddWindowOptions (const std::string &config_name, int left, int top, int width, int height, bool visible, bool pinned, bool minimized)
Adds OptionsDB entries for a window under a given name along with default values.
static const std::string AddWindowOptions (const std::string &config_name, GG::X left, GG::Y top, GG::X width, GG::Y height, bool visible, bool pinned, bool minimized)
overload that accepts GG::X and GG::Y instead of ints
static void InvalidateWindowOptions (const std::string &config_name)
removes options containing config_name, logs an error instead if "UI.windows."+config_name+".initialized" exists (i.e. if a window is currently using that name)
Protected Attributes inherited from CUIWnd
std::vector< std::pair
< std::size_t, std::size_t > > m_buffer_indices
bool m_closable
true if the window is able to be closed with a button press
GG::Button * m_close_button
the close button
const std::string m_config_name
the name that this window will use to save its properties to the OptionsDB, the default empty string means "do not save"
bool m_config_save
true if SaveOptions() is currently allowed to write to the OptionsDB
GG::Pt m_drag_offset
offset from the lower-right corner of the point being used to drag-resize
bool m_minimizable
true if the window is able to be minimized
CUI_MinRestoreButton * m_minimize_button
the minimize/restore button
bool m_minimized
true if the window is currently minimized
bool m_mouse_in_resize_tab
GG::Pt m_original_size
keeps track of the size of the window before resizing
CUI_PinButton * m_pin_button
the pin button
bool m_pinable
true if the window is able to be pinned
bool m_pinned
true if the window is currently pinned
bool m_resizable
true if the window is able to be resized
GG::GL2DVertexBuffer m_vertex_buffer
Static Protected Attributes inherited from CUIWnd
static const GG::Y BORDER_BOTTOM
static const GG::X BORDER_LEFT
static const GG::X BORDER_RIGHT
static const GG::X BUTTON_RIGHT_OFFSET
static const GG::Y BUTTON_TOP_OFFSET
static const int INNER_BORDER_ANGLE_OFFSET = 11
static const GG::X MINIMIZED_WND_WIDTH
static const int OUTER_EDGE_ANGLE_OFFSET = 8
static const int RESIZE_HASHMARK1_OFFSET = 7
static const int RESIZE_HASHMARK2_OFFSET = 3
static const int TITLE_OFFSET = 3
Constructor & Destructor Documentation
InGameMenu::InGameMenu ()
default ctor
References DoLayout(), Done(), Exit(), HumanClientApp::GetApp(), GetOptionsDB(), Load(), m_done_btn, m_exit_btn, m_load_btn, m_options_btn, m_save_btn, Options(), CUIWnd::ResetDefaultPosition(), Save(), and UserString().
InGameMenu::~InGameMenu ()
dtor
Member Function Documentation
GG::Y InGameMenu::ButtonCellHeight () const private
Helper function.
References m_done_btn.
Referenced by CalculatePosition(), and DoLayout().
GG::X InGameMenu::ButtonWidth () const private
Helper function.
References m_done_btn, m_exit_btn, m_load_btn, m_options_btn, and m_save_btn.
Referenced by CalculatePosition(), and DoLayout().
GG::Rect InGameMenu::CalculatePosition () const protected virtual
override this if a class determines its own position/size and return the calculated values, called by ResetDefaultPosition()
Reimplemented from CUIWnd.
References anonymous_namespace{MapWnd.cpp}::AppWidth(), ButtonCellHeight(), ButtonWidth(), and HumanClientApp::GetApp().
void InGameMenu::DoLayout ()
References ButtonCellHeight(), ButtonWidth(), m_done_btn, m_exit_btn, m_load_btn, m_options_btn, and m_save_btn.
Referenced by InGameMenu().
void InGameMenu::Done () private
when m_done_btn is pressed
Referenced by InGameMenu(), and KeyPress().
void InGameMenu::Exit () private
when m_quit_btn button is pressed
References CUIWnd::CloseClicked(), HumanClientApp::EndGame(), and HumanClientApp::GetApp().
Referenced by InGameMenu().
void InGameMenu::KeyPress (GG::Key key, boost::uint32_t key_code_point, GG::Flags< GG::ModKey > mod_keys) virtual
References Done().
void InGameMenu::Load () private
when m_load_btn button is pressed
References CUIWnd::CloseClicked(), HumanClientApp::GetApp(), CUIWnd::Hide(), and HumanClientApp::LoadSinglePlayerGame().
Referenced by InGameMenu().
void InGameMenu::Options () private
when m_options_btn button is pressed
Referenced by InGameMenu().
void InGameMenu::Save () private
when m_save_btn button is pressed
Multiplayer save. Talk to the server.
References HumanClientApp::CanSaveNow(), CUIWnd::CloseClicked(), DebugLogger, ErrorLogger, permute_labels::filename, HumanClientApp::GetApp(), ClientUI::MessageBox(), MP_SAVE_FILE_EXTENSION, SaveFileDialog::Result(), HumanClientApp::SaveGame(), HumanClientApp::SelectSaveFile(), HumanClientApp::SinglePlayerGame(), SP_SAVE_FILE_EXTENSION, and UserString().
Referenced by InGameMenu().
Member Data Documentation
GG::Button* InGameMenu::m_done_btn private
Done button.
Referenced by ButtonCellHeight(), ButtonWidth(), DoLayout(), and InGameMenu().
GG::Button* InGameMenu::m_exit_btn private
Quit game button.
Referenced by ButtonWidth(), DoLayout(), and InGameMenu().
GG::Button* InGameMenu::m_load_btn private
Load game button.
Referenced by ButtonWidth(), DoLayout(), and InGameMenu().
GG::Button* InGameMenu::m_options_btn private
Options button.
Referenced by ButtonWidth(), DoLayout(), and InGameMenu().
GG::Button* InGameMenu::m_save_btn private
Save game button.
Referenced by ButtonWidth(), DoLayout(), and InGameMenu().
The documentation for this class was generated from the following files:
InGameMenu.h
InGameMenu.cpp