FreeOrion: RotatingGraphic Class Reference
RotatingGraphic Class Reference
#include <CUIControls.h>
Public Member Functions
Structors
RotatingGraphic (const boost::shared_ptr< GG::Texture > &texture, GG::Flags< GG::GraphicStyle > style=GG::GRAPHIC_NONE, GG::Flags< GG::WndFlag > flags=GG::NO_WND_FLAGS)
Mutators
void SetRPM (float rpm)
void SetPhaseOffset (float degrees)
virtual void Render ()
Private Attributes
float m_phase_offset
float m_rpm
Detailed Description
Functions like a StaticGraphic, except can be rotated with a fixed phase and/or at a continuous angular rate.
Constructor & Destructor Documentation
RotatingGraphic::RotatingGraphic (const boost::shared_ptr< GG::Texture > & texture, GG::Flags< GG::GraphicStyle > style = GG::GRAPHIC_NONE, GG::Flags< GG::WndFlag > flags = GG::NO_WND_FLAGS)
Member Function Documentation
void RotatingGraphic::Render () virtual
References m_phase_offset, and m_rpm.
void RotatingGraphic::SetPhaseOffset (float degrees) inline
References m_phase_offset.
Referenced by FleetButton::Init().
void RotatingGraphic::SetRPM (float rpm) inline
References m_rpm.
Referenced by FleetButton::Init(), and SystemIcon::SystemIcon().
Member Data Documentation
float RotatingGraphic::m_phase_offset private
Referenced by Render(), and SetPhaseOffset().
float RotatingGraphic::m_rpm private
Referenced by Render(), and SetRPM().
The documentation for this class was generated from the following files:
CUIControls.h
CUIControls.cpp