FreeOrion: OrderedMovingFleetVisitor Struct Reference
OrderedMovingFleetVisitor Struct Reference
#include <Predicates.h>
Public Member Functions
OrderedMovingFleetVisitor (int empire=ALL_EMPIRES)
virtual ~OrderedMovingFleetVisitor ()
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Fleet > obj) const
Public Member Functions inherited from UniverseObjectVisitor
virtual ~UniverseObjectVisitor ()
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< UniverseObject > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Building > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Planet > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Ship > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< System > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Field > obj) const
virtual TemporaryPtr
< UniverseObject > Visit (TemporaryPtr< Fighter > obj) const
Public Attributes
const int empire_id
Detailed Description
returns obj iff obj is a Fleet belonging to the given empire, and that is under orders to move, but is not yet moving. If the given empire is -1, all stationary fleets will be returned. Note that it is preferable to use this functor on System searches, rather than Universe ones.
Constructor & Destructor Documentation
OrderedMovingFleetVisitor::OrderedMovingFleetVisitor (int empire = ALL_EMPIRES)
OrderedMovingFleetVisitor::~OrderedMovingFleetVisitor () virtual
Member Function Documentation
TemporaryPtr< UniverseObject > OrderedMovingFleetVisitor::Visit (TemporaryPtr< Fleet > obj) const virtual
Reimplemented from UniverseObjectVisitor.
References ALL_EMPIRES, empire_id, Fleet::FinalDestinationID(), INVALID_OBJECT_ID, UniverseObject::Owner(), UniverseObject::SystemID(), Fleet::TravelRoute(), and UniverseObject::Unowned().
Member Data Documentation
const int OrderedMovingFleetVisitor::empire_id
Referenced by Visit().
The documentation for this struct was generated from the following files:
Predicates.h
Predicates.cpp