FreeOrion: anonymous_namespace{SitRepPanel.cpp}::ColorEmpire Class Reference
anonymous_namespace{SitRepPanel.cpp}::ColorEmpire Class Reference
Public Member Functions
virtual std::string Decorate (const std::string &target, const std::string &content) const
Public Member Functions inherited from LinkDecorator
virtual std::string DecorateRollover (const std::string &target, const std::string &content) const
LinkDecorator ()
Additional Inherited Members
Static Protected Member Functions inherited from LinkDecorator
static int CastStringToInt (const std::string &str)
Member Function Documentation
virtual std::string anonymous_namespace{SitRepPanel.cpp}::ColorEmpire::Decorate (const std::string & target, const std::string & content) const inline virtual
Gets called for each link of the type this decorator is assigned to. The return value is shown to the user as the link. The default implementation wraps content in an rgba tag that colors it by ClientUI::DefaultLinkColor
Parameters
target The target of the link. Usually an id of something or the name of an encyclopedia entry.
content The text the link tag was wrapped around.
Returns
The text that should be shown to the user in the place of content
Reimplemented from LinkDecorator.
References Empire::Color(), ClientUI::DefaultLinkColor(), and GetEmpire().
The documentation for this class was generated from the following file:
SitRepPanel.cpp