FreeOrion: ValueRefDoubleFixture Struct Reference
ValueRefDoubleFixture Struct Reference
Public Types
typedef std::pair
< ValueRef::ReferenceType,
std::string > ReferenceType
typedef std::pair
< ValueRef::StatisticType,
std::string > StatisticType
Public Member Functions
ValueRefDoubleFixture ()
~ValueRefDoubleFixture ()
void assertion_result (bool passed)
bool parse (std::string phrase, ValueRef::ValueRefBase< double > *&result)
void printTree (const ValueRef::ValueRefBase< double > *root, int depth)
Public Attributes
const ValueRef::Operation
< double > * operation1
const ValueRef::Operation
< double > * operation2
const ValueRef::Operation
< double > * operation3
const ValueRef::Operation
< double > * operation4
const ValueRef::Operation
< double > * operation5
const ValueRef::Operation
< double > * operation6
ValueRef::ValueRefBase< double > * result
const ValueRef::Statistic
< double > * statistic
const ValueRef::Constant
< double > * value
const ValueRef::Variable
< double > * variable
Static Public Attributes
static const boost::array
< std::string, 36 > attributes
static const boost::array
< std::string, 3 > containerTypes
static const boost::array
< ReferenceType, 4 > referenceTypes
static const boost::array
< StatisticType, 9 > statisticTypes
Member Typedef Documentation
typedef std::pair<ValueRef::ReferenceType, std::string> ValueRefDoubleFixture::ReferenceType
typedef std::pair<ValueRef::StatisticType, std::string> ValueRefDoubleFixture::StatisticType
Constructor & Destructor Documentation
ValueRefDoubleFixture::ValueRefDoubleFixture () inline
ValueRefDoubleFixture::~ValueRefDoubleFixture () inline
References result.
Member Function Documentation
void ValueRefDoubleFixture::assertion_result (bool passed) inline
References printTree(), and result.
bool ValueRefDoubleFixture::parse (std::string phrase, ValueRef::ValueRefBase< double > *& result) inline
References anonymous_namespace{EnumParser.cpp}::_1, lexer, and parse::value_ref_parser< double >().
void ValueRefDoubleFixture::printTree (const ValueRef::ValueRefBase< double > * root, int depth) inline
References value, and ValueRef::Constant< T >::Value().
Referenced by assertion_result().
Member Data Documentation
const boost::array< std::string, 36 > ValueRefDoubleFixture::attributes static
const boost::array< std::string, 3 > ValueRefDoubleFixture::containerTypes static
Initial value:
= {{
    "Fleet",
    "Planet",
    "System"
}}
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation1
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation2
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation3
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation4
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation5
const ValueRef::Operation<double>* ValueRefDoubleFixture::operation6
const boost::array< ValueRefDoubleFixture::ReferenceType, 4 > ValueRefDoubleFixture::referenceTypes static
Initial value:
= {{
    std::make_pair(ValueRef::SOURCE_REFERENCE, "Source"),
    std::make_pair(ValueRef::EFFECT_TARGET_REFERENCE, "Target"),
    std::make_pair(ValueRef::CONDITION_LOCAL_CANDIDATE_REFERENCE, "LocalCandidate"),
    std::make_pair(ValueRef::CONDITION_ROOT_CANDIDATE_REFERENCE, "RootCandidate")
}}
ValueRef::ValueRefBase<double>* ValueRefDoubleFixture::result
Referenced by assertion_result(), and ~ValueRefDoubleFixture().
const ValueRef::Statistic<double>* ValueRefDoubleFixture::statistic
const boost::array< ValueRefDoubleFixture::StatisticType, 9 > ValueRefDoubleFixture::statisticTypes static
Initial value:
= {{
    std::make_pair(ValueRef::MAX,     "Max"),
    std::make_pair(ValueRef::MEAN,    "Mean"),
    std::make_pair(ValueRef::MIN,     "Min"),
    std::make_pair(ValueRef::MODE,    "Mode"),
    std::make_pair(ValueRef::PRODUCT, "Product"),
    std::make_pair(ValueRef::RMS,     "RMS"),
    std::make_pair(ValueRef::SPREAD,  "Spread"),
    std::make_pair(ValueRef::STDEV,   "StDev"),
    std::make_pair(ValueRef::SUM,     "Sum")
}}
const ValueRef::Constant<double>* ValueRefDoubleFixture::value
Referenced by printTree().
const ValueRef::Variable<double>* ValueRefDoubleFixture::variable
The documentation for this struct was generated from the following file:
TestValueRefDoubleParser.cpp